### ISSUE TITLE
Uncapturable attribute for ships

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1000]
Relating to my asteroid pull, it would be nice to include an attribute that makes ships unable to be captured. This would solve the current problem in the asteroid mining pull that you can actually capture asteroids.

**Comment by lehgogh** [comment]
btw, this is the 1000th issue!

**Comment by lehgogh** [comment]
This shouldn't be too hard to implement. I'll see if I can add the attribute.

**Comment by lehgogh** [comment]
#1003

**Comment by endless-sky** [comment]
Added in commit 711c79a.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
