### ISSUE TITLE
In the new Quarg conversation, there is a broken dialog chain

### ISSUE THREAD

**Issue by nathan-b** [endless-sky/endless-sky#10007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After joining the Heliarch, if you land on a Quarg ringworld you can enter into a conversation with a Quarg about the Heliarch. 

If you select the option "What if I do want to aid the Heliarchs?", you are brought into a weird state where you only have two options: "Is that a threat?" or re-asking "What if I do want to aid the Heliarchs?".

Cc. @Arachi-Lover 

### Steps to Reproduce

1. Land on Quarg ringworld
2. (Yes)
3. "Hello, I'm..."
4. "Why did..."
5. "You 'jumped'..."
6. "Even now..."
7. "What if I do want to aid the Heliarchs?"

### Expected Behavior

I shouldn't be able to re-ask the same question and get into a dialog loop. I would expect the only option to be "Is that a threat?" (or, ideally, another way to exit the conversation).

### Operating System

Arch Linux

### Game Source

Other (please describe)

### Game Version

v0.10.6

### Additional Information

Installed from Arch Linux package repository

**Comment by Arachi-Lover** [comment]
Was a problem with the indentation of the choices' `to display` blocks. The recently opened PR should fix it (I think).

Thanks for the heads up!
