### ISSUE TITLE
[Bug] Reduced image quality in Water4 caused by #9459

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#10004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

PR #9459, in addition to updating some copyright issues, also replaced several pictures. Two of the pictures are, as described in the PR, virtually un-distinguishable. Unfortunately, `Water4` is decidedly brighter and more pink, and I think is just overall worse quality. 

### Steps to Reproduce

1. Go to PR #9459
2. Click on the changes to see the comparison
3. See error

### Expected Behavior

If we're replacing a picture, I would expect the picture to be equal to or superior in quality; not a downgrade.

If we need to replace that picture to adhere to copyright, then I would suggest that we do our own color balancing work on the image to bring it back inline with the old version.

### Operating System

Windows 10 Pro

### Game Source

Built from source

### Game Version

commit 46a392f85cba1112849ed96a3129aa63e1f36fce

**Comment by ziproot** [comment]
Here is water4 with saturation reduced by 50% and hue shifted to the left 10% using imagemagick:
![water4](https://github.com/endless-sky/endless-sky/assets/109186806/b2fecaab-a5a0-43ca-b98a-e8227c15e469)

As the pixabay version is public domain, this is not an issue.

**Comment by OcelotWalrus** [comment]
Indeed, the original image has a better quality (in my opinion)
![image](https://github.com/endless-sky/endless-sky/assets/87318892/716f5f3c-9e3f-40f9-a109-21aeffc402db)

The new image seems to be way too much saturated. Maybe the change should be reverted? Or reworked on?

**Comment by mOctave** [comment]
I think Ziproot's edit is a passable replacement.
