### ISSUE TITLE
Impossible to arrive at trial during war with Empire

### ISSUE THREAD

**Issue by alexpyattaev** [endless-sky/endless-sky#10026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When landing on Deep during the war with empire, you can still get summoned to court for terraforming, but completing this quest is actually impossible without leaving a trail of corpses due to sol system being rather well guarded. Suggest introduce a delay in the script to prevent summon from being issued when Empire is hostile.

### Steps to Reproduce

1. Go to Deep immediately after combat with Empire ends
2. Receive summon for trial
3. Be unable to land on Earth without leaving a trail of wrecked empire ships.
4. Cry.

### Expected Behavior

Quest is delayed to time more appropriate (after war ends).

### Operating System

Linux

### Game Source

GitHub Releases

### Game Version

0.10.6

**Comment by lumbar527** [comment]
I made a PR that might help with this problem: #10027.
