### ISSUE TITLE
Departure flight check may show slightly confusing warning

### ISSUE THREAD

**Issue by SomeTroglodyte** [endless-sky/endless-sky#10035]
### Problem Description

Funny little issue, not marking as bug since the words are ***technically*** correct.

Steps:
- Board a disabled enemy, "T"ake its hyperdrive/jumpdrive
- then "C"apture it
- then travel to a friendly system and "L"and
- "D"epart

<details><summary>Screenshots</summary>

This message...
![image](https://github.com/endless-sky/endless-sky/assets/63000004/ab14ede0-115f-4a3b-b5e5-42f703394b89)
...refers to...
![image](https://github.com/endless-sky/endless-sky/assets/63000004/193f87ff-b784-43e7-9f60-762ca8efe7cc)
...and indeed it cannot leave the system it is in...
![image](https://github.com/endless-sky/endless-sky/assets/63000004/4cec314f-2dbc-4267-b95e-48dd6f8fa756)

</details>

:laughing: 

### Related Issue Links

?

### Desired Solution

None, actually. You *can* find out what's up and the warning *is* useful...

### Alternative Approaches

Limit pre-flight check to local system?

**Comment by TomGoodIdea** [comment]
#8985
