### ISSUE TITLE
New cloaking attributes not defined in the wiki

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#10048]
### Location

wiki

### Describe the issue

Commit https://github.com/endless-sky/endless-sky/commit/aa0a95d8a63a64c1506acc70a639588b91b09552 adds additional cloaking attributes, however, they are not defined in the [CreatingOutfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits) page in the wiki.

### Expected content

The CreatingOutfits page in the wiki should define the additional cloaking attributes.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits/_compare/a8b0a8586b0e2d0c1b015a1897ad267ab07eff5e
