### ISSUE TITLE
Holding J does not work in wormholes

### ISSUE THREAD

**Issue by eebop** [endless-sky/endless-sky#10065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you hold but don't release J, your escorts are supposed to prep for a jump but not due it. However, if your next jump goes through a wormhole, they will just go through it on keydown, not keyup.

### Steps to Reproduce

1. Get a escort
2. Plan a path through a wormhole
3. hold J

### Expected Behavior

The escorts hover above the wormhole, but do not enter.

### Operating System

Ubuntu 22.04

### Game Source

Steam

### Game Version

0.10.6

**Comment by TomGoodIdea** [comment]
Can't reproduce on master

**Comment by Koranir** [comment]
I can confirm this issue.
On a ship going from Aescolanus->Cardea->Nenia, if I hold down the Jump key my ship(s) will travel through the wormhole before holding position, ready to jump when I release the key.

**Comment by Koranir** [comment]
Pressing the Jump key creates the travel plan, which the AI will follow through with until they need to jump as there is no special check for that. Normal prevention of jumping works fine, as there is a check for if the Jump key is held down before the AI starts hyperspacing.

**Comment by Koranir** [comment]
I think this could be solved by making sure the Jump button is no longer held before starting to land on the wormhole, but in a way that the AI will still move on top of the wormhole object in a state where they can land at a moments notice.

**Comment by eebop** [comment]
Pr merged
