### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1008]
Discovered by someone on Steam - haven't verified it myself.

> Just thought i should put this out there. But the Sapira Mereti Station in Similisti doesn't have a an image when you land. Dont know if its intended but thought i should mention it

**Comment by Amazinite** [comment]
land/lava9
There is no lava9 in the images/land folder.

**Comment by endless-sky** [comment]
Technically there's no way to land there without cheating (since there's no way to get the Kor Mereti to be friendly), but I fixed it in 93c1620.
