### ISSUE TITLE
Bug: Missions with only illegal passengers and not cargo are not illegal

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#10084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you take a mission with illegal passengers and not illegal cargo (e.g. the slave transport jobs or the shady passenger jobs), you cannot actually be fined or sentenced to death.

### Steps to Reproduce

1. Load the save
2. Depart
3. Wait for Hai authorities to scan you
4. See how you are not fined
5. Land on Everhope (security 1)
6. See how you are not fined

### Expected Behavior

If you are successfully scanned or caught by planetary security, you should be fined and the mission should fail.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/109186806/96625e39-c1ce-41be-aa50-c01efcaa0111)

### Link to save file

[Remnant Test~Shady Passenger.txt](https://github.com/endless-sky/endless-sky/files/15370486/Remnant.Test.Shady.Passenger.txt)

### Operating System

Debian 12 Bookworm

### Game Source

GitHub Releases

### Game Version

v0.10.6

**Comment by ziproot** [comment]
The mission in the attached save has the `illegal` tag.

**Comment by OcelotWalrus** [comment]
Well this's really weird.
