### ISSUE TITLE
People aren't following Discussions by default. 

### ISSUE THREAD

**Issue by xX-Dillinger-Xx** [endless-sky/endless-sky#10083]
EDITED: I only posted this here to reach a larger number of people. It's only intent was to relay information. 

### Location

Github

### Describe the issue

There are some people that are starting to use the `Discussions` for a starting point to develop ideas. The problem is, by default, Github doesn't send notifications when a new discussion is started. Because of this, many people are missing out on the discussions where their input would be a valuable contribution. 

I just found out how to receive notifications for all activity in `Discussions` tab. 
- goto the main _**code**_ page for this repo
- click on the `watch` or `unwatch` button (depends on whether you are watching this repo or not)  
- in the pop-up click _**Custom**_ 
- select _**Discussions**_

You will receive a notification when someone opens a new discussion.

**Comment by Zitchas** [comment]
Thanks for sharing that!

**Comment by Saugia** [comment]
Issues are for issues regarding the game itself, not Github policies. This isn't a proper use of our issue system; it's not appropriate to abuse it to get more people to see this.

**Comment by xX-Dillinger-Xx** [comment]
>This isn't a proper use of our issue system; it's not appropriate to abuse it to get more people to see this.

How is passing on useful information abusing the system? 

The whole point of putting the information here, as an issue, was because if I started it in a Discussion no-one would see it, and now that you have closed it we have the same problem. People don't get notifications about `Closed` issues.
I know it's not a game issue but it has been recently discussed in a Discussion and at least 2 prominent contributors where unaware of how to get notifications about  from the `Discussions` tab. Does it really make sense to start a topic about people not seeing notifications about **_new discussions_** by default, in a new discussion?

**Comment by tibetiroka** [comment]
> People don't get notifications about Closed issues.

Most people don't get notifications about issues at all, whether they are open or not. Also, if they did get a notification about this issue, it will still be there after the issue is closed.

GitHub could do a better job of telling people about discussions, sure. That's not an issue with Endless Sky however, so the issue shouldn't be opened here.

**Comment by xX-Dillinger-Xx** [comment]
It's not an issue I'm trying to solve. It's the only place I had, that would be seen, to pass on useful information.  Sorry for trying to help. I had no idea it was cause such a big problem. Feel free to delete the whole thing if it's so inappropriate.
