### ISSUE TITLE
Bug: Double bribing NPCs (again)

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1009]
I just doubled checked the double bribing method, and it still somewhat works. The government of the enemy that you attacked will now turn hostile on you when you attack an NPC that you double bribed, but the specific NPC that you double bribed will not become "fully" hostile. By that I mean that they will not attempt to attack you, but if you just so happen to be right in front of their ship they will fire their weapons. I tested this on a freighter with 2 turrets and it would only fire on me if I placed myself in front of it, but being near the freighter would not cause him to target me.

So it isn't as abusable as before, but double bribing a single ship still has pretty much the same effect.

**Comment by endless-sky** [comment]
I've tried this with the latest code, and ships I attack twice and bribe twice still seem to attak me if I provoke them again.

**Comment by Amazinite** [comment]
I've just checked again in the latest steam build and I'm getting the same results as you are now. Has anything changed with the steam build since the v0.9.0 release, because I was getting different results when I posted this.

**Comment by endless-sky** [comment]
No, the only change in the Steam build after 0.9.0 was a data change to fix the southern carriers infection.

**Comment by Amazinite** [comment]
I just tried a few dozen times and everything seems to be fine. It appears to have been fixed, so I'll close this now.
