### ISSUE TITLE
mission "Lunarium: Smuggling: Heat" does not get offered

### ISSUE THREAD

**Issue by alexpyattaev** [endless-sky/endless-sky#10109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The lunarium mission in question never gets offered even when all conditions are met. Removing the conditions from the quest does trigger it, as expected. I believe the "offending" condition is the one with random in it.

### Steps to Reproduce

1. Go to saryd planet
2. Land and do not get mission offered
3. open sources and kill the conditions that do not trigger for whatever reason
4. enjoy the bug reporting=)

### Expected Behavior

I'd like for mission to get offered, as one would expect.

### Link to save file

[Troll Headcrab.txt](https://github.com/endless-sky/endless-sky/files/15453262/Troll.Headcrab.txt)

### Operating System

Linux

### Game Source

GitHub Releases

### Game Version

0.10.6

**Comment by tibetiroka** [comment]
You have `"assisting heliarchy" -1` in your save file, which prevents the mission from triggering.

Do you remember the last time you were able to take a Lunarium mission, and what Heliarch missions you did afterwards?

**Comment by tibetiroka** [comment]
Nah. It's a counter for how many Heliarch missions you have active. It shouldn't be negative.

The only thing I can think of is one of the coalition missions not incrementing that value correctly, but I can't find anything.

**Comment by alexpyattaev** [comment]
Woa thats odd. I'll set it to zero then?

**Comment by alexpyattaev** [comment]
Hm... the next mission triggered normally.

**Comment by ziproot** [comment]
There was a bug that led to you having a negative asssisting heliarchy value, but it was fixed months ago.
