### ISSUE TITLE
Bug: Game Crash with Automaton fleet

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1010]
If you have all automaton ships in your fleet and remove the command center on your flag ship, you will still get all the options on the main planet menu when you leave the outfitter, including depart, while normally having all automaton ships would make only the bank and shipyard buttons appear (as if you had no ships at all). Clicking depart then crashes the game, since you don't have any ships that have space for you. Reloading the game cause the game to recognize that you have no pilotable ships, leaving only the bank and shipyard buttons.

This occurred because I was messing around and set the Korath ships to be purchasable, but if someone were to replace their entire fleet with automatons and remove their command center on a planet with only an outfitter then they could possibly get stuck on the planet, as to fix this requires having to buy a ship with bunks on it to make the outfitter button and everything else reappear.

**Comment by endless-sky** [comment]
Fixed in commit a10992f.

**Comment by Amazinite** [comment]
Closing cus v0.9.1

**Comment by Amazinite** [comment]
Can confirm fixed.
