### ISSUE TITLE
Add "game rule" to disable fighters not getting hit by stray shots when disabled.

### ISSUE THREAD

**Issue by 43897689431805741092** [endless-sky/endless-sky#10110]
### Problem Description

In my experience so far, this feature leads to a lot of fighters being left strewn around after battles, which, particularly in plugins with carriers that can hold like 80+ fighters, leads to a lot of distracting mess. I find it very unimmersive for the smallest and most fragile ships to be the main ones specifically and consistently surviving battles. Nor do I personally think collecting one's disabled fighters after a battle is any more convenient than buying and outfitting new ones anyway.

The feature itself is fine, though; I'm not looking to complain about it or get it changed with this issue, and it sounds from other comments like a lot of other people are happy with it. I just want an option to not use it and it strikes as a perfect fit for a game rule. I practically assumed it would be when reading the 10.7 changelog since it seems like somewhat of a "difficulty setting" type thing – "do you want your fighter gameplay to be brutal or economically-viable?".

### Related Issue Links

https://github.com/endless-sky/endless-sky/pull/9760
Hurleveur said: Definitely worth opening an issue to at least get the option to turn it off for the AI, I think.
So here I am.

### Desired Solution

A new "game rule" with settings that allow this behaviour to be disabled for the AI and globally (as in, three settings total: on, on for player only, off).

The fourth possible option (on for AI only) could just as well be added for the sake of completeness, but this would essentially be a toggle to allow the farming of enemy fighters and drones much more easily – not sure this possibilitiy is desirable regarding e.g. Kor Sestor carriers.

### Alternative Approaches

- In-game setting.
- Have the behaviour be an attribute applied directly to ships (like things such as "never disabled") instead of being universal.

**Comment by Zitchas** [comment]
Definitely sounds like a good candidate for a gamerule.

**Comment by binaryspica** [comment]
It would let some fighters of the advanced races and leaves the annoying disabled fighters all around the system, so I think that it's worth a look. Even before this many of those are leaves as disabled and make me annoying as hell, and this means I got even more of those annoyance.

I wonder that it would matters when using fighters of your own, for that doesn't actually affects the gameplay when you are using fighters for your fighters would be destroyed as they always does regardless and this change does nothing actually - for the shots already targets them still hits regardless, as well as blasts of dying ships. So overall that update was only a bad thing, for it won't makes our fighters usable while makes the game even wonky.

Anyway the option to turn on/off won't hurts anyone, as always.
