### ISSUE TITLE
Add "Trader Reputation" to info panel. 

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1011]
Like name suggests, the more trading you do the better your rating. Perhaps more trading could give you access to more lucrative trade missions or spur mission dialog.

**Comment by endless-sky** [comment]
There are already condition variables that track your total cargo space and your number of ships of each category. That's how the large bulk missions work, for example.

**Comment by lehgogh** [comment]
A trader reputation value would also be good to see how reliable you are (arriving late or cancelling jobs lowers your trader reputation) before special missions become available. For example, if there was a job to transport one thousand tons of cargo for the Navy, they wouldn't want to hire someone with a bad reputation.

**Comment by endless-sky** [comment]
That could be done just by having cargo missions add to a "reputation" condition variable when they are completed, and subtract a larger amount when they fail. (Fail includes aborting missions and missing deadlines.)
