### ISSUE TITLE
Hide empty mission description pane

### ISSUE THREAD

**Issue by nickshanks** [endless-sky/endless-sky#10123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Do not display an empty mission description pane when no mission is selected in the mission map.

### Steps to Reproduce

1. Land on an uninhabited world
2. Press 'm' to open the map
3. Click the Missions tab in the bottom right
4. Observe big empty box

### Expected Behavior

You would no see the empty box, and see more map.

### Screenshots

Before:
<img width="1312" alt="before" src="https://github.com/endless-sky/endless-sky/assets/206120/647f2f56-54a5-4111-ba6d-70a6d7112020">

After:
<img width="1312" alt="after" src="https://github.com/endless-sky/endless-sky/assets/206120/2f46d16f-52e3-4bb7-825f-06867cfaa319">

### Operating System

MacOS X

### Game Source

Built from source

### Game Version

commit SHA 081a60a

### Additional Information

I have a patch coming. I just need a ticket number for the commit message.

**Comment by Amazinite** [comment]
>I have a patch coming. I just need a ticket number for the commit message.

The ticket numbers in the commit messages on the master branch are to the pull request that added that commit. We don't expect ticket numbers in the commits of pull requests, since we squash merge every commit down anyway.

**Comment by nickshanks** [comment]
> The ticket numbers in the commit messages on the master branch are to the pull request that added that commit.

Ahh, OK, my bad! I need to make a 2x version of the pane now!

**Comment by nickshanks** [comment]
FWIW I considered just returning early from the DrawMissionInfo() function and not rendering the panel at all, but I apprieciate the information that gets displayed, even if the disabled buttons are a bit useless. Also the intent was that this would also be used for missions that had no description text (though the code does not do that at present).
