### ISSUE TITLE
`die` does not block player interactions

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#10125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the player `die`s on a planet, they are still able to take off, though no ships take off with them. In this disembodied state, they are still able to use their flagship's ammo selection box (though I've yet to confirm if it actually affects anything other than the UI), can hail ships and planets.

### Steps to Reproduce

1. Choose the first option
2. Choose the third option
3. Press 'D' to take off

### Expected Behavior

The player should not be able to:
 - take off
 - hail planets
 - hail ships
 - change ammo selection

In fact, the player's flagship pointer should probably get reset - that would probably solve most of these issues by itself.

### Link to save file

[Matthew_WeaverGhost.txt](https://github.com/endless-sky/endless-sky/files/15504111/Matthew_WeaverGhost.txt)

### Operating System

EndeavourOS (Linux 6.9.2-arch1-1)

### Game Source

Built from source

### Game Version

continuous

**Comment by RisingLeaf** [comment]
Should we get the ghost busters?

**Comment by TomGoodIdea** [comment]
related: #9717

**Comment by tibetiroka** [comment]
In my understanding, 9717 is a feature request, while this is a bug report about the current implementation. It's also easier to track this way, since #10128 fixes this issue.
