### ISSUE TITLE
Androids and Crew Capacity (0.9.0)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1013]
This stuff is confusing.
Max out androids, and subtract 1.
You have your crew capacity.
Add one more (even though it says it can't replace the captain).
You have the same crew capacity.
But when you check the "hire crew" menu, max androids allows you to purchase one more crew member than max-1.
Confuse.
Also, since the androids take the spots of your crew, shouldn't the crew capacity decrease as well?
Androids confuse me.
I confuse myself as well. I have no idea how to put what I saw in Endless Sky into words here. Sorry.
Anyway, thoughts?
EDIT: On an unrelated note, androids have broken (read- overpowered) Endless Sky. With maximum tribute, I can now have a lot of ships without going over the payment. A LOT.

**Comment by endless-sky** [comment]
Androids don't need to sleep, so they don't use up one of your bunks. So, your ship's total crew capacity should be the same regardless of how many of them you install.

The first crew member on your flagship represents you, yourself.

I suppose the price of androids should probably be higher, to make the break-even point maybe more like 1000 days instead of 300.

**Comment by Bladewood** [comment]
I wonder what life in a bunk room is like.
Yes, but but it also happens for the other ships, and the problem is: you can actually buy the last android. You should not be able to, because even a robot could not take the helm. If it was just the rest of the fleet, I could probably understand, it's the captain that is coordinating their actions. But, at least for the flagship, you should not be able to buy your full required crew, only required crew - 1.
Doesn't really make a difference when you have 180,000+ credits of tribute a day.

**Comment by endless-sky** [comment]
The very last android's job is to hang around on the bridge annoying the captain and complaining about this terrible pain he has in the transistors on his left side.

**Comment by Gkramme** [comment]
Gotta love the Hitchhiker's Guide To the Galaxy. Maybe androids could also require charging stations, instead of rasing the price. Or you could give them the brain the size of a planet so they annoy the heck out of the player :)

**Comment by Wrzlprnft** [comment]
If you have androids in your fleet, the chat gets slightly spammed by them?

**Comment by jafdy** [comment]
What if androids can only replace 80-90% of the crew the other 10-20% being 'high skilled' jobs that no one wants to trust an android to.

**Comment by Gkramme** [comment]
@jafdy I like that idea.

**Comment by LocalGod79** [comment]
yes, @Wrzlprnft - started a new issue about it... #1095

**Comment by jafdy** [comment]
@LocalGod79 I think you are slightly confused. I think it was a way to annoy the player the Marvin would.

**Comment by Wrzlprnft** [comment]
Indeed.

**Comment by LocalGod79** [comment]
all the same, chat is being spammed with "insufficient crew", and i thought that the Androids might be causing it...

**Comment by Bladewood** [comment]
Found another thing that makes androids bad:

`mission "FW Pirates 1"`
`As you are about to leave, he [Tomek] says, "Oh, one other thing: you've been approved for a salary raise to 800 credits. We figure that helping you maintain a slightly larger ship is a worthwhile investment. Congratulations, Captain."`

Goes against the plot!
Barely, but it still does!

**Comment by endless-sky** [comment]
Removed androids in 4abc9b8. The outfit thumbnail still exists in case someone wants to have a try at adding a more balanced version of them back in some day.
