### ISSUE TITLE
Tutorial/hint text that shows guns/turrets can be manually swapped around in Ship details screen

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10132]
### Problem Description

I noticed this hidden mechanic very late into the game, when I tried to use ships with angled ports (like the Tubfalet): The game automatically and randomly assigns guns and turrets to the ports/mounts available. This can be seen by opening the Ship details screen. 

This randomness can lock the player out of some outfitting choices, such as wanting to use a beam weapon at the front and projectile ones on the side. Or maybe a Banisher turret at the back and a Grab at the front.

More examples: wanting to use long-range guns at rear ports and short range ones in the front for concentrated firepower. Or the opposite, for more coverage. Wanting to use anti-missiles in the rear and attacking turrets in the front, because escaping via forward acceleration is easier, and this would use weapon ranges more effectively.

### Related Issue Links

None.

### Desired Solution

Much easier solution that won't crowd the already dense Outfitter screen: the ability to swap guns and turrets to different ports/mounts in the Ship details screen. Something like clicking+dragging from slot 1 to slot 2. If it's empty, the weapon is just moved. If it's not, both weapons are swapped.

### Alternative Approaches

Much clunkier: the ability to select which gun/turret goes in which port/mount in the Outfitter screen, when buying/installing.

**Comment by RisingLeaf** [comment]
This is already possible you can drag and drop weapons in the ship detail panel

**Comment by RisingLeaf** [comment]
This is only possible when landed iirc

**Comment by eebop** [comment]
Hit "I", select the ship you want to modify, and drag the weapons around

**Comment by RisingLeaf** [comment]
Sure a tutorial might help.

**Comment by RisingLeaf** [comment]
Actually such a help already exists and it will pop up if you open the ship info panel for the first time, you can reset helps in the settings to get it again

**Comment by RisingLeaf** [comment]
No opinion on that you can leave the issue open if you want some from others.

In general we don't have hints in the game.

**Comment by TomGoodIdea** [comment]
Doesn't hitting F1 work in the Ship Info panel?

**Comment by TomGoodIdea** [comment]
sounds interesting, you can open a new issue for this
