### ISSUE TITLE
Typo? Inconsistent naming of Gegno Excavator.

### ISSUE THREAD

**Issue by 43897689431805741092** [endless-sky/endless-sky#10138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Outfit "Excavator" is called... that, but the description says "Excavator Drills", with capitalised "Drills", as though the outfit was named "Excavator Drill" and not "Excavator" in development and then changed.

### Steps to Reproduce

Inconsistency appears on lines 795 & 822 of this file: https://github.com/endless-sky/endless-sky/blob/master/data/gegno/gegno%20outfits.txt

### Expected Behavior

Outfit to be called "Excavator" in its description; consistent use of proper nouns.

### Operating System

Prefer not to say

### Game Source

GitHub Releases

### Game Version

v0.10.7

**Comment by TheGiraffe3** [comment]
@43897689431805741092 see #10236 for a fix, though Saugia will need to look at it before merge.
