### ISSUE TITLE
[bug] Minor mission error

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1014]
http://steamcommunity.com/sharedfiles/filedetails/?id=675464706

This mission has the blue circle surrounding the destination, but it doesn't have the system indicator, making it look like it's pointing randomly into the middle of endless space (see what I did there?)

Edit: even after accepting, doing this: https://steamcommunity.com/linkfilter/?url=https://github.com/endless-sky/endless-sky/issues/1014

**Comment by endless-sky** [comment]
That's happening because the system in question is a "stopover" for the mission, and the map panel is only considering a system known if it's a mission destination. Should be relatively easy to fix, I just need to think through what other systems that should apply to (e.g. waypoints).

**Comment by endless-sky** [comment]
Fixed in commit 12afa82.
