### ISSUE TITLE
Suggestion: Give all pirate planets pirate basics

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#10153]
### Problem Description

I noticed that you cannot buy gatling gun ammo on all pirate planets. It turns out that this is because originally there was only “pirate outfits,” so the smaller pirate planets wouldn’t be selling advanced weapons. However, this was recently split into “pirate basics” and “pirate advanced,” so I don’t see why this should still be the case. 

### Related Issue Links

[Discord](https://discord.com/channels/251118043411775489/308902312741568512/1247341544478871662)

### Desired Solution

All pirate planets sell basic outfits.

### Alternative Approaches

The outfits are split into three sections, one for the smallest pirate planets, which currently don’t have outfits, one for medium-sized planets, which currently just have “pirate basics,” and one for the largest planets, which also have “pirate advanced.”

### Additional Context

The outfits were split in #9944

**Comment by bene-dictator** [comment]
Gatling Gun ammo is sold at both Pirate Basics and Pirate Advanced (and I'm pretty sure Pirate Advanced has all the outfits of Pirate Basics) The discord link is talking about Gatling Guns.

**Comment by ziproot** [comment]
There are pirate planets that sell neither pirate basics nor pirate advanced.

**Comment by bene-dictator** [comment]
I see what you mean now.

Only some of the new CCOR spobs and Mutiny don't sell anything, and I think they all have reasons to not have outfitters anyway. Jakobsen (in the CCOR) has an outfitter, but it never had any pirate outfitters; #9944 didn't change that.
