### ISSUE TITLE
[bug] XCode Iconutil warning

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1015]
![screen shot 2016-04-30 at 2 46 02 am](https://cloud.githubusercontent.com/assets/16969517/14934433/c2cb9608-0e7d-11e6-9fe4-f86660b4c94c.png)

**Comment by endless-sky** [comment]
Yes, my icon source graphic is only 256x256 and I haven't gotten around to creating a new one.

Also, I think it's ridiculous to require an icon at such high resolution that it becomes 2% of the entire download size.

**Comment by LocalGod79** [comment]
i know very little about iconset...would better image compression help with that burden?

**Comment by endless-sky** [comment]
This is a duplicate of #378.
