### ISSUE TITLE
Ship Switching

### ISSUE THREAD

**Issue by TheGiraffe3** [endless-sky/endless-sky#10161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When in a Kimek Spire and with a Kar Ik Vot escort in the same system, getting killed causes the flagship to switch to the Kar Ik Vot.

### Steps to Reproduce

Go to Watcher (Algieba) with a Kimek Spire and a Kar Ik Vot as an escort. Take off and get killed by the Republic. Watch as your flagship becomes the Kar Ik Vot. 

### Expected Behavior

Player dies instead of being teleported.

### Link to save file

[The Pilot~3024-04-29-bug.txt](https://github.com/user-attachments/files/15592662/The.Pilot.3024-04-29-bug.txt)

### Operating System

MacOS Ventura

### Game Source

GitHub Releases

### Game Version

commit c7997bf017f468850824a9e56dfa43b153fe28eb

### Additional Information

The video is too big to upload, but [here it is](https://github.com/TheGiraffe3/bug)

There is a longer version, but it was also too big to upload. Not sure how to attach it…

**Comment by tibetiroka** [comment]
Looks like I broke this :(

**Comment by TheGiraffe3** [comment]
In which commit? I’d be interested in seeing the diff.

**Comment by tibetiroka** [comment]
Nah, it's alright. Ended up switching out the fix halfway through the PR and some parts of the old solution remained, breaking things.
