### ISSUE TITLE
self-destruct makes all copies  of that ship explode

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1017]
not absolutely definite but the probabilities suggest that about 30% I should be able to capture Korath automatons but if the first attempt is not a success then all the ships of that type just blow up in my face. I think it should apply a new test for every attempt but at tho moment it appears to make one test and use that yes/no value for the rest of the time you are in the system.

**Comment by endless-sky** [comment]
It takes one self-destruct check to board a ship, and another the capture it. So, for example, if the ship has 70% self-destruct odds you're only going to be able to capture it 9% of the time.

A new random number is picked each time you try to board or capture. If you try capturing enough ships, you should see that on average the odds even out.

**Comment by thenerdfreak** [comment]
I can't manage to get one to not blow up on the first try. They all blow up to me it seems

**Comment by jmhorjus** [comment]
"if the ship has 70% self-destruct odds you're only going to be able to capture it 9% of the time."

That is very counter-intuitive.  

Also: With random events people feel, psychologically, much better about losing a random roll if they get to observe the roll.  So, for example, if you tell someone they have a 95% chance to hit and then they miss they will think the game is busted, or if they have a 10% chance and they fail more than ten times they will get frustrated and think the odds are stacked or the thing can never really happen.  
But if you *show* someone the generated number or the die roll, they will accept that "oh, I guess I rolled a 0.03...bad luck." or "Wow...I rolled 2d6 and got 10, that's *almost* the 11 I needed...gotta keep trying!". 

Something to think about if trying again and again for something that has a very low % chance of happening is going to be a part of the game. The experience of that kind of random game mechanic can be improved a lot by showing a process, even if the process is super simple and/or player has no control over that process.

**Comment by endless-sky** [comment]
> That is very counter-intuitive.

No, it's just math. You have a 30% chance of boarding it without it self-destructing, and once you board it if you choose to capture it you have a 30% chance of that succeeding. So, your chance to capture it is 30% * 30% = 9%.

**Comment by jafdy** [comment]
Every first time I try to board one it doesn't blow until I try to capture it and every second of third (and so on) ship will just blow before I can even start pulling stuff out.

**Comment by jmhorjus** [comment]
@jafdy That's not what the code says...it really ought to be an independent roll each and every time you either try to board or try to capture. 
@endless-sky I didn't mean that multiplication was counter-intuitive. :)  I just meant it's not explicit in the data file that the same "self destruct" probability is checked in two different situations.  It's also not explicitly communicated to a player that they should keep trying if the first several ships they try to board self-destruct without showing a boarding panel - someone might "intuitively", but incorrectly, conclude that since the first 4 ships all self-destructed that they all will.  I'm not saying it's a big problem or anything, it's just something that may have to be explained to some people before they understand it.

**Comment by endless-sky** [comment]
From the [wiki](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits#outfit-attributes):

> self destruct: a value between 0 and 1, representing the probability that a ship will self destruct when you try to plunder it or, after succeeding in boarding it without it self destructing, try to capture it. That is, the probability of successfully boarding a ship with self destruct is (1 - "self destruct"), and the probability of both boarding and capturing it is (1 - "self destruct")^2
