### ISSUE TITLE
Dynamic trade can cause low costing goods to go negative

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1018]
This was on a modded planet. Dynamic trade made the cost of luxury goods become -32, so they payed you to take their stuff.
http://prntscr.com/aywf0z

I question the quality of these goods.

**Comment by endless-sky** [comment]
The dynamic economy can adjust the price of goods by up to 100 credits per ton. The very cheapest good is food, which has a range from 100 to 600 (not counting dynamic effects). So, as long as you keep your base commodity prices within the defined range, they'll never go negative.
