### ISSUE TITLE
Boarding ship changed as active target changed

### ISSUE THREAD

**Issue by adamsnd** [endless-sky/endless-sky#102]
When a disabled ship is targeted for boarding, cycling through other disabled ships (disabled pirates) changed the autopilot's destination to the other disabled ship. It's possible that I was cycling through other disabled ships via the "nearest hostile ship" key with no active hostile ships remaining in the system.

Having the "nearest hostile ship" key work on disabled, formerly hostile ships is a very nice feature since it allows me to skip over any neutral ships in the system when looking over potential ships to capture. I would rather manually give boarding orders rather than have them reassigned upon targeting a new ship since I often have priorities for boarding ships (most expensive/desired first) since neutral ships will often try to destroy formerly hostile ships (pirates in this case) that I've already disabled.

**Comment by endless-sky** [comment]
Right now, the board command only works on your ship's current target. Changing that would be complicated enough that I probably won't do it in the stable 0.8 series of releases, but I've put it on my to-do list to look at later, once I've got 0.8 fully tested and released on Steam.
