### ISSUE TITLE
Denab being landable regardless of the relationship with the Pug in the free world campaign

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#10209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I got the jump drive from korath ships and is just wandering human space and testing the equipment out, I am surprised to find that by jumping into deneab during the free world campaign when the Pugs cut off the hyperlinks between the systems that, despite me disabeling and killing alot of their ships and their planet being one 5 spike alerts, I can still bribe the officials to allow me to land there.

### Steps to Reproduce

1. Go to Denab 
2. Kill or fire a few Pugs
3. Scroll down to land on the planet
4. Offer Bribe to land on Planet

### Expected Behavior

Deneb shouldn't have landable planets for the player when the Pugs are harmed by the later.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/110284440/c5fa03cb-073d-446d-b6ef-b27436d923a4)

### Operating System

Macbook 2019 Intel Os

### Game Source

Steam

### Game Version

v0.10.2(or the latest stable version on steam)

### Additional Information

N/A

**Comment by TheGiraffe3** [comment]
Can someone remove the `unconfirmed` label, because it obviously is that way?
