### ISSUE TITLE
Nerve Gas should be more widely spread

### ISSUE THREAD

**Issue by TheGiraffe3** [endless-sky/endless-sky#10204]
### Problem Description

Pirates have no Nerve Gas on their ship, although it is a very pirate outfit. Nerve Gas is used on one ship in the game (Marauding Max), and nowhere else. EDIT: Actually, it is used on the Nighthawk, which unfortunately is not really ever used in-game. 
_And the Korath say Please don’t use Nerve Gas on us!_ How do they know about it?

### Related Issue Links

There was one issue (#2218) that was basically a duplicate of this, but I commented on that about 36 hours ago and haven’t received a reply, so I’ll open a new one. 

### Desired Solution

All (read: most) pirate ships should be given Nerve Gas. It may make capping slightly harder, and pirate ships harder to buy, but as a lore point, it’s pretty important. 

EDIT: After discussion down below, it’s fine if just a few have Nerve Gas, as long as it is in use. 

### Alternative Approaches

Not do it? Breaks lore.
We could remove NG from the game altogether. 
For either of these, we’d also need to remove the Korath hail about Nerve Gas. 

### Additional Context

I have a PR (#10222) to give Nerve Gas to some special pirate ships, the Modified Argosy, Bulwark, and the Aerie. The Nighthawk already has Nerve Gas.

**Comment by ProNooberEX** [comment]
I think the reason for pirates not having nerve gas is to prevent the player from getting too powerfull, there are players out there who sold ships as their main income, and the addition of nerve gas on pirate ships meant that the player's attack would grow exponnetially after a few boarding of ships, causing the player to progress forward too fast in the game(imagine a medium utlity with 100+ nerve gas bording heavy warships and capturing them with ease)

**Comment by Quantumshark** [comment]
> I think the reason for pirates not having nerve gas is to prevent the player from getting too powerfull, there are players out there who sold ships as their main income, and the addition of nerve gas on pirate ships meant that the player's attack would grow exponnetially after a few boarding of ships, causing the player to progress forward too fast in the game(imagine a medium utlity with 100+ nerve gas bording heavy warships and capturing them with ease)

Capturing nerve gas from pirates isn't massively easier than just buying it, so I don't think that's really an issue. And, each crew member can only use one weapon, so having more nerve gas than your bunk count doesn't make capturing any easier.

**Comment by Saugia** [comment]
> There was one issue (https://github.com/endless-sky/endless-sky/issues/2218) that was basically a duplicate of this, but I commented on that about 36 hours ago and haven’t recorded a reply, so I’ll open a new one.

The issue was closed and a reason was given as to why the issue wasn't a fit for the game. I will say that may change over time, but if an issue is closed, it means it is resolved and a decision was made. I won't say to close this one since it is probably worth talking about again, but I wouldn't be opening issues for things that have been already said and done.

**Comment by TomGoodIdea** [comment]
related: #10180

**Comment by Saugia** [comment]
After some discussion, I would open to a *few* Pirate ships having Nerve Gas to show use of it, but I disagree on the notion that *most* should.

**Comment by Saugia** [comment]
Well, currently, the Pirate Variants are still in question on whether or not they should actually be part of the game, so if you were thinking about a few other rare variants or such then that would work. Rare not necessarily being ship type, but fleet value.

**Comment by TheGiraffe3** [comment]
I put Marauders in at @Quantumshark’s suggestion. 
The Valkyrie could be used in one of the @ProNooberEX missions involving the Northern Pirates, though I’m not sure about the Bulwark because #9933 was closed.

**Comment by Saugia** [comment]
Well, considering the Northern Pirates, I'd say we'd wait for us to expand upon them considering there is a large expansion planned for the area.

**Comment by TheGiraffe3** [comment]
Fixed by #10222. @SomeTroglodyte cam you open a new issue for it, because the focus of this was for _adding_ Nerve Gas?
