### ISSUE TITLE
[bug/enhancement] spare energy/cooling/hull repair rate is not granted to docked fighters/drones

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1020]
as is the case with shields

not sure if it's intentional

**Comment by DingusShingleton** [comment]
This might be an opportune time to bring up recharging/cooling docked fighters as well. I think it would be a nice little boost that doesn't really affect combat but would make the player feel good.

**Comment by endless-sky** [comment]
Added in commit 2a0bda1.

**Comment by LocalGod79** [comment]
but not cooling and energy?

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
