### ISSUE TITLE
Pirates with electron Beams Sprawning before free world campaign

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#10211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Before the free world campaign and as I am going to rob some pirate leviathans to establish my fleet to raid korath ships, but I found out that one of the pirates leviathan boarded had the electron beam installed even before the Navy had develope and equipped it.

### Steps to Reproduce

1. Go to Northern Pirate Space near Wanderer Space
2. Farm pirate ships

### Expected Behavior

No pirates with electron beams should be spawned.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/110284440/74c4ffe6-1258-4b85-bf37-1b277b69c3dc)

### Operating System

Macbook 2019 Intel Os

### Game Source

Steam

### Game Version

v0.10.2(or the latest stable version on steam)

### Additional Information

N/A

**Comment by TomGoodIdea** [comment]
wasn't this changed in #9819?

**Comment by ProNooberEX** [comment]
<img width="842" alt="截屏2024-06-16 00 07 10" src="https://github.com/endless-sky/endless-sky/assets/110284440/2bae3f71-8092-4492-856c-a3cb28a3ceda">

**Comment by ProNooberEX** [comment]
> > wasn't this changed in #9819?
> 
> You’re right, it was. @ProNooberEX there is an update available on Steam, maybe you should update? On the latest release you shouldn’t be having this problem.

It is up to date

**Comment by ProNooberEX** [comment]
> The ships you captured, when did you capture them? You’ve already started and gotten through a considerable portion of Free Worlds.

In  the system of Almaaz

**Comment by ProNooberEX** [comment]
> But when? A while ago, or just now?

A while ago

**Comment by ProNooberEX** [comment]
> Because you may have captured them before the update, or because you’ve done parts of FW they’ve been added
 They are all after the update and I haven't reached the Navy new beam weapon by then.

**Comment by ProNooberEX** [comment]
> Well, it should be fixed now. Can you find any more with Electron Beams?

No.
