### ISSUE TITLE
Planets near the Denab System after cutting off from human space in free world campaign pay 1 dollar tributes

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#10212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As I am roaming around near the system of Deneb after "What happened to Rand" and before attacking the pugs, the planets cut off from human space would pay 1 dollar tribute.

### Steps to Reproduce

1. Go to Denab
2. Ask For Tribute for any one planet
3. See return message with 1 dollar tribute

### Expected Behavior

the planets inside should be either paying normal tributes or not being able to be dominated at all.

### Screenshots

N/A

### Operating System

Macbook 2019 Intel Os

### Game Source

Steam

### Game Version

v0.10.2(or the latest stable version on steam)

**Comment by TheGiraffe3** [comment]
Should this be closed, because the question was answered?
