### ISSUE TITLE
Captured Korath Automaton ships are self-destructing when you're in other systems

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#1022]

**Comment by endless-sky** [comment]
Can you explain when this is happening? Self destruct is only triggered when a ship is disabled and boarded by a hostile enemy ship, so it shouldn't be happening unless you've left a disabled ship behind where pirates of some sort can get at it.

**Comment by thenerdfreak** [comment]
I disabled, boarded, and took over a Kor Sestor ship but there were no more in the system. I was gonna use a method of getting it down to the Kor Efreti systems by jumping out into Hai space and safely going down there and waiting for it to eventually run out of fuel then going and refueling it, but before it ran out of fuel I got the notification that it self destructed
