### ISSUE TITLE
Show total remaining cargo in fleet when picking up things floating in space

### ISSUE THREAD

**Issue by Zarkonnen** [endless-sky/endless-sky#10228]
### Problem Description

I'm doing asteroid mining, and I only want to return to port when my fleet's cargo bays are reasonably full of delicious uranium. The current messages about picking up items in-flight only show the remaining cargo capacity in the ship that's doing the picking up, not in the fleet as a whole.

### Related Issue Links

I looked at all the issues relating to cargo and did not find any related ones.

Tangentially related
* [Steam discussion about cargo management](https://steamcommunity.com/app/404410/discussions/0/3130541122095340293/)

### Desired Solution

Add the total remaining cargo space to pickup messages.

### Alternative Approaches

An on-screen fleet cargo capacity indicator.

**Comment by TheGiraffe3** [comment]
This would also show remaining cargo space in the ship, right?

**Comment by Zarkonnen** [comment]
> This would also show remaining cargo space in the ship, right?

The cargo capacity indicator option should show both space in the ship and in the fleet, yes.

The pickup message would be changed from e.g
_Your ship "Fishcake" picked up 5 tons of uranium. (10 tons of free space remaining.)_
to
_Your ship "Fishcake" picked up 5 tons of uranium. (10 tons of free space remaining, 91 in fleet.)_

**Comment by TomGoodIdea** [comment]
I think if you tell the fleet to harvest (`Z` by default), they'll try to collect flotsam as long as they are able to pick it up, so when you see that none of your ships are trying to collect the minerals, it means they have no free cargo space.

But still, the proposed feature sounds nice.

**Comment by TheGiraffe3** [comment]
This would still be a quite useful feature to have, if someone could implement it.

**Comment by TheGiraffe3** [comment]
There’s only one way to find out…

**Comment by TheGiraffe3** [comment]
https://github.com/SomeTroglodyte/endless-sky says that you don’t rebase anything. 😉 Well, your choice, but if you don’t no-one else may.

**Comment by tibetiroka** [comment]
> ... but how to PR that and adhere to the code quality guidelines I haven't found... ???

The guidelines are available [here](https://endless-sky.github.io/styleguide/styleguide.xml) (it's linked in contributing.md and on the wiki).

If you need help with opening a PR, there are [resources available on discord](https://discord.com/channels/251118043411775489/266345072554016768/832408959180472330).

**Comment by tibetiroka** [comment]
We actually do have an  editorconfig file. It's nowhere near good enough to enforce those standards, unfortunately editorconfig isn't good enough for that.

We have a dedicated linter written that gives a lot better results, but it can only support so many things without becoming a maintenance nightmare...

We even looked into clang-format a couple years ago, but that wasn't good enough either. (Though I hear it's better now, so that might be an option.)

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/af6ba799ec3f6fe39ececd3df8ca0bbd15a92536
