### ISSUE TITLE
Dumping a limited ammount of cargo

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#1024]
There should be an alternative to dumping the whole cargo hold to make space for some loot.
Sometimes, I don't want to dump 300 Luxury Goods in the Ship Panel to gain about 70 space or so for a small ship. Overall, I'd loose money making so.

I propose the Ship info panel to present several options (1/4, 1/2, 3/4, 4/4) for dumping the cargo in space. I suppose micromanaging this is impossible in space (for example, dump minimum qty needed to make space for all loot). Perhaps finer increments for larger holds

**Comment by Wrzlprnft** [comment]
Or maybe "dump cargo" refers in future to 1 unit, and the modifiers (shift, alt) of the trading tab are copied onto that situation

**Comment by wargwargwarg** [comment]
the way I see it, the things are packed together in the cargo hold in sizeable pallets for easy (un)loading. That's why I proposed those fractions (dump rapidly one pallet or how many you need).

**Comment by endless-sky** [comment]
This will probably get changed at the same time as I make dumped cargo into something other ships can pick up.

**Comment by endless-sky** [comment]
In commit fd2770a I've added a dialog box asking how many tons of cargo you want to dump.
