### ISSUE TITLE
Concerning help, Drak Archons suddenly start talking.

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1025]
![talking drak](https://cloud.githubusercontent.com/assets/15857993/14950956/f4e52cb0-1055-11e6-91a1-599251d05407.png)
Edit: also if you ask for help with enough fuel (#catalyticramscoop)

**Comment by endless-sky** [comment]
There's really no particular reason for them *not* to talk, since they are certainly able to communicate with you. The only reason they don't have hails defined is that I want them to appear sort of disinterested and immersed in their own affairs.

**Comment by Wrzlprnft** [comment]
Ah, i get it.
