### ISSUE TITLE
not saving when save file has been edited or imported by another program

### ISSUE THREAD

**Issue by 40476** [endless-sky/endless-sky#10267]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

not saving when save file has been edited by another program

### Steps to Reproduce

1. edit a well developed game save file to have a larger amount of credits, (99999999)
2. the game refuses to save

### Expected Behavior

the game should allow me to save

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/63472353/7b6bc516-ced6-4c14-9b37-518d6d8c4a27)

### Link to save file

`/home/usr_40476/.local/share/endless-sky/saves/40476 thatguy.txt`

### Operating System

openSUSE Tumbleweed

### Game Source

Other (please describe)

### Game Version

0.10.6

### Additional Information

https://paste.opensuse.org/pastes/dc04469772ec

**Comment by lumbar527** [comment]
What do you mean by "save"? Does the file not save? Does the game not save on landing?

**Comment by warp-core** [comment]
Have you closed the file in your other editor before attempting to have Endless Sky update it?

I suspect the issue is that the game is not allowed to modify the file because it is in use by another program.

Alternatively, the game is saving correctly, but the data it saves does not match what you're expecting to see.

If all you've done is edited the latest save file to have more credits and then tried to save again in Endless Sky, you're probably overwriting your manual edits with the previous state of the file because Endless Sky has not loaded the save file with your modifications. It has the old state in memory, and that state is what it then saves.

**Comment by 40476** [comment]
it is refusing to save at all,or even add snapshots
![image](https://github.com/endless-sky/endless-sky/assets/63472353/a187f6e9-a5b2-47af-bfb9-141e3c265c77)

**Comment by 40476** [comment]
this behavior occurs anytime the save file is changed by an external program

**Comment by TomGoodIdea** [comment]
Try this:
1. Close the game.
2. Open an editor and modify the save file.
3. Close the editor.
4. Open the game.

Are there any problems if you do it this way?

**Comment by 40476** [comment]
yes, it prevents my from saving an pausing, just like before. reinstalling does not fix the issue

**Comment by 40476** [comment]
you can see my save file at https://paste.opensuse.org/pastes/dc04469772ec

**Comment by TheGiraffe3** [comment]
You said it wasn't save specific though?

**Comment by 40476** [comment]
yes, it also disables snpashots, which is the manual save option

**Comment by 40476** [comment]
I tried editing the file using `sed` it still did that, addtionally, this also happens when I import a save file by pasting it into the saves directory

**Comment by TomGoodIdea** [comment]
@40476, check the error log as SomeTroglodyte suggested. It should be in `~/.local/share/endless-sky/errors.txt`.

**Comment by 40476** [comment]
![image](https://github.com/endless-sky/endless-sky/assets/63472353/c6068a4c-a54f-4dcd-93c3-67fe79a8f9fc)

**Comment by TomGoodIdea** [comment]
Where did you get the game from?

**Comment by 40476** [comment]
`sudo zypper install endless-sky`
(openSUSE tumbleweed default repos)

**Comment by TomGoodIdea** [comment]
Can you download 0.10.8 directly from GitHub and check if it works on this version?

**Comment by 40476** [comment]
`sudo zypper install endless-sky`
(openSUSE tumbleweed default repos)

**Comment by 40476** [comment]
it has the same behavior.

**Comment by 40476** [comment]
I have an idea, where are the files and code that handle saving and reading the save files, my plugins.txt also does not appear to exist.

**Comment by 40476** [comment]
my distribution just updated the `endless-sky` package but it still has the behavior

**Comment by TomGoodIdea** [comment]
Do you run both the game and the editor as the same user, on the same privilege level?

Maybe editing the save file somehow changed its ownership or permissions.

**Comment by 40476** [comment]
I have no idea what changed but it is working normally now.
