### ISSUE TITLE
Escorts Prefer Hyperdrive over Jump Drive when Jumping to Range Limited Systems

### ISSUE THREAD

**Issue by tekker2234** [endless-sky/endless-sky#10271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When jumping to systems that limit the range of your jump drive from systems that are outside of the range of the destination's range restriction, escorts will jump along connecting hyperlanes rather than using their Jump Drives.
Additionally your escorts may occasionally get stuck in the intervening system if you jump beyond your original destination before they reach you.

### Steps to Reproduce

1. Go to Aliet
2. Jump to Iigen
3. See escorts jump to Yllke before jumping to Iigen
4. (If you want to go farther) jump to Uelawan before they jump to Iigen and watch them not move from Yllke
5. Go to Yllke to get them to move again
(They do not get stuck if you jump to Uttna, Heutesl or Oosuoro from Iigen)

Alternatively
1. Go to Yllke
2. Jump to Uttna
3. See escorts jump to Iigen before jumping to Uttna via hyperdrive
(They do not get stuck if you jump beyond Uttna)

Alternate 2
1. Go to Msalbit
5. Jump to Aierena
6. See escorts jump to Yranjiu before jumping to Aierena
(They do not get stuck in Yranjiu if you jump beyond Aierena)

### Expected Behavior

Escorts should jump with you to the destination system using their equipped Jump drives.
Escorts should not stay in Yllke when juming beyond Iigen.

### Link to save file

[Tesser Centra.txt](https://github.com/user-attachments/files/15992863/Tesser.Centra.txt)

### Operating System

Windows 10 Home build 19045.4529

### Game Source

Steam

### Game Version

0.10.8

**Comment by BZFENDSKY** [comment]
[Discord where this was originally reported](https://discord.com/channels/251118043411775489/536900466655887360/1255565483009118341).

**Comment by esksp** [comment]
I've noticed something like that too, in the letter+number systems on the far east of the map.
Traveling there with 2 identical ships with jump drives and scram drives, trying to jump from one system to another: My flagship did jump directly from MS-219 to G-6186, while my escort did use the hyperlanes MS-219 -> M-1188 -> G-6186. It happens all the time in that area.

**Comment by tekker2234** [comment]
I believe this was fixed by the pathing change (at least I've not gotten it since).
(Can't remember off the top of my head which PR that was though)

**Comment by TheGiraffe3** [comment]
#6940
