### ISSUE TITLE
Automaton may mess up combat rating...

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1027]
...as well as reputation.

How's disabling automaton ships (like the new korathi ships) accounted in combat rating and reputation? Even if in the korath case, taking out a single ship in an "eternal" conflict with "unlimited" resources may not be really valuable for reputation, the combat rating should go up.

PS: i am not aware of changes that may have happened to the combat rating mechanics.

**Comment by endless-sky** [comment]
Yes, probably what needs to be done is to create a way to define a strength rating for the ships separate from their crew count. (For example, killing a Summer Leaf should count for more than killing a Gunboat even though they're the same size and the same crew complement.)

**Comment by Wrzlprnft** [comment]
Maybe a hardcodes value for the category as well as the worth of the ship, since alien ships tend to be more expensive than human ships.

**Comment by jmhorjus** [comment]
It could be based on the cost of the ship (maybe cost/500k rounded up?) by default. That's the only other universal attribute for ships and outfits that we already have.  The AI already uses cost to estimate strength.

**Comment by Wrzlprnft** [comment]
Reputation will stay the same? In the actual case, with a look on the lore, i think it is okay, but i am not sure about the general case.

**Comment by endless-sky** [comment]
Commit 0c7d39d makes it so combat rating is based on the value of the ships (cost / 500k, rounded, so drones are still zero, sparrows are 1, other interceptors are 2, clippers are 3, etc.).

**Comment by Wrzlprnft** [comment]
Good job. But the reputation?

**Comment by Wrzlprnft** [comment]
I guess we outsource the topic then
