### ISSUE TITLE
Formation flying: Less corrections for staying in formation

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#10285]
### Problem Description

Ships move a bit restlessly when flying in formation. They perform corrections to get to their positions often, and this often causes holes in the formation.

### Related Issue Links

N/A

### Desired Solution

Ships stay in formation a little bit better, without as much corrections as is done now. Station-keeping seems much more stable. The expectation is that formation flying should be able to also be a lot more stable.

### Alternative Approaches

There have been some discussions if formations should do some "cheating" by automatically getting a little bit of backwards force on ships, or if the ships should be able to maintain position without any "cheating".

### Additional Context

Position stability didn't get a lot of attention for formation flying yet, so it seems like a good idea to look into this a bit more.

**Comment by TheGiraffe3** [comment]
~You made the problem.~
Yes. One way to see this is to buy 500 Falcons and tell them to go into the "X" formation. Especially if there are hostiles, the ships will be quite unsettled.

**Comment by petervdmeer** [comment]
A suggestion for an implementation (using the cheating option) was mentioned in https://github.com/endless-sky/endless-sky/pull/4471#pullrequestreview-2180215869.
As noticed before; the station-keeping code also seems more stable.
