### ISSUE TITLE
Merchant Swizzle being applied again globally

### ISSUE THREAD

**Issue by XymaScope** [endless-sky/endless-sky#10283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The colours of the game have appeared incorrect since updating from 0.10.6 to 0.10.8, though i can't confirm it was because of the update. The colours that have been changed are very consistent with how the Merchant swizzle changes the ship colours, but it is applied to the whole window, effectively unswizzling merchant ships, and strangely also swizzling the Steam Overlay (??????!!)

i'm not aware of any other behavior in Steam, GNOME, or any other software on my computer that would do this. nothing i have done has managed to restore it, all non-flatpak versions of ~~10.8~~ the game on my PC exhibits this behavior.

I have tested:
removing all plugins
disabling Steam Overlay
reinstalling the game
disabling High DPI DLC plugin
installing github release Appimage
applying a different swizzle with the World Forge plugin (correctly changes the swizzle of the ships but they still appear incorrect due to the global swizzle)

### Steps to Reproduce

1. Have my cursed PC
2. Load any version of ~~0.10.8~~ the game, except Flatpak?
3. Observe Blue sun on launch
4. Continue to observe swizzled colours

i have no clue what is causing it, i need more troubleshooting steps. i am fairly sure nothing has changed and there is no state that should be left that would continue to apply to different versions, it has to be some sort of interaction with something that changed in the update and the libraries on my machine... but an Appimage negates that sooo...

### Expected Behavior

Swizzle should only apply to ships

### Screenshots

![Screenshot from 2024-06-27 02-23-25](https://github.com/endless-sky/endless-sky/assets/61898531/7cfdad89-c831-4cd4-82fb-c9addb083d9a)
![Screenshot from 2024-06-27 02-22-56](https://github.com/endless-sky/endless-sky/assets/61898531/a92c3f25-897f-4fa8-a95f-1029050531cd)
![Screenshot from 2024-06-27 02-23-52](https://github.com/endless-sky/endless-sky/assets/61898531/b47955e0-b362-4ad6-8677-47095d030c01)
![Screenshot from 2024-06-27 02-25-28](https://github.com/endless-sky/endless-sky/assets/61898531/2bdc23a2-5fbf-41fa-911c-9fc3e95ee3ef)
![Screenshot from 2024-06-27 03-19-42](https://github.com/endless-sky/endless-sky/assets/61898531/c3f9f9a6-587a-43e3-9b1f-204d2102546e)
![Screenshot from 2024-06-27 03-32-26](https://github.com/endless-sky/endless-sky/assets/61898531/04cf8270-6c68-4f93-9eed-4b383392b3ed)

### Link to save file

[Xydari Testing~broken???.txt](https://github.com/user-attachments/files/16045180/Xydari.Testing.broken.txt)

### Operating System

Zorin OS 17.1 Core (Ubuntu 22.04 Jammy Jellyfish)

### Game Source

Other (please describe)

### Game Version

Steam and AppImage:
0.10.8
AppImage:
0.10.7, 0.10.6

**Comment by TomGoodIdea** [comment]
Reinstall libsdl2, libglew, libgl, and your graphics drivers

**Comment by eebop** [comment]
I don't think it's the swizzle, my guess is that there is something using RGB and something else interpreting it as BGR, because it appears the blue & red channels are swapped

**Comment by XymaScope** [comment]
yeah, it seems like its actually pretty common for RGB and BGR to coexist in weird ways, i've since run into it again in a completely different environment.

the issue has disappeared now, i didn't get around to the reinstalling steps from Tom, but i had since moved the installation to a different drive and i'm not sure if that fixed it. its been a bit chaotic and i haven't been able to dedicate any time to this. i am curious what it could have been, but i'll close this issue.
