### ISSUE TITLE
Failed assertion in TextArea::Hover sometimes

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#10299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

First reported on Discord: https://discord.com/channels/251118043411775489/536900466655887360/1258186514966253669

> I'm not sure how to cause it, but spamming m and j while launching the ship can sometimes crash the game:
> I get this error:
> ```
> endless-sky: /home/eebop/esdev/endless-sky/source/TextArea.cpp:207: virtual bool TextArea::Hover(int, int): Assertion `buffer' failed.
> Aborted (core dumped)
> ```

I can also reproduce it while loading a save that references missing content, triggering a warning dialog when loading it.
It's a slightly constructed scenario, but not impossible or unreasonable.

Edit: I also encountered the issue in one case while loading the save without trying to intentionally trigger it, as well.

Here's the call stack when built with clang:
```
Endless Sky.exe!TextArea::Hover(int x, int y) Line 208
Endless Sky.exe!Panel::EventVisit<int,int,int,int>(bool(Panel::*)(int, int) f, int args, int args) Line 182
Endless Sky.exe!Panel::EventVisit<int,int,int,int>(bool(Panel::*)(int, int) f, int args, int args) Line 178
Endless Sky.exe!Panel::DoHover(int x, int y) Line 244
Endless Sky.exe!UI::Handle(const SDL_Event & event) Line 51
Endless Sky.exe!GameLoop::<lambda_0>::operator()() Line 320
Endless Sky.exe!GameLoop(PlayerInfo & player, TaskQueue & queue, const Conversation & conversation, const std::string & testToRunName, bool debugMode) Line 347
Endless Sky.exe!SDL_main(int argc, char * * argv) Line 216
Endless Sky.exe!main_getcmdline() Line 80 (vcpkg\buildtrees\sdl2\src\ase-2.28.2-705f8fad22.clean\src\main\windows\SDL_windows_main.c:80)
Endless Sky.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, char * szCmdLine, int sw) Line 110 (vcpkg\buildtrees\sdl2\src\ase-2.28.2-705f8fad22.clean\src\main\windows\SDL_windows_main.c:110)
Endless Sky.exe!invoke_main() Line 107 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:107)
Endless Sky.exe!__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
Endless Sky.exe!__scrt_common_main() Line 331 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
Endless Sky.exe!WinMainCRTStartup(void * __formal) Line 17 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp:17)
```

### Steps to Reproduce

1. Install the attached save file.
2. Launch the game.
3. Open the load menu.
4. Load the save (use the 'e' key) while the cursor is hovering/moving near the centre of the screen (where the warning dialog will appear).
5. Assertion failed.

### Expected Behavior

The application doesn't give up on existence.

### Link to save file

[revjim crash test.txt](https://github.com/user-attachments/files/16103717/revjim.crash.test.txt)

### Operating System

Windows 10 Pro 21H2

### Game Source

Built from source

### Game Version

e613d0d

### Additional Information

Assertion fails in the same way when compiling with either g++ or clang.

I can also reproduce when building from source on a Ubuntu 22.04 based Linux distro.

**Comment by Saugia** [comment]
Not sure the specifics, but I'm also getting this error. I'm running Omnis as a plug-in and I'm on continuous. If I go to the shipyard and hit "s" to sell a ship, half of the time I get an error (presumably on the display of the ship being sold. I can ignore it and the game keeps running though, and after I ignore it, I'm at the "Sell the blank for blank?" dialog box.

**Comment by TomGoodIdea** [comment]
These asserts look safe to remove. Their functions (Hover and Click) already are supposed to return false with no buffer.

**Comment by eebop** [comment]
As discovered by warp-core on discord, the error ocures when a dialog appears while the mouse is moving
