### ISSUE TITLE
Drak Displacer sometimes freezes game when used against korathi robot ships.

### ISSUE THREAD

**Issue by Isaacssv552** [endless-sky/endless-sky#1029]
For whatever reason the game sometimes freezes when a Drak Archon is fighting the automated korathi ships. I first noticed this when fighting an Archon with two of the robot ships in my fleet. When I removed the never disable tag, captured the archon, and flew it over to one of the robot systems I encountered frequent freezing, requiring me to force quit the game. When I removed the displacer turrets before attacking the freezing stopped.

**Comment by endless-sky** [comment]
Do you mean "disruptor," or "detainer"?

**Comment by Isaacssv552** [comment]
Drak Distancer, I thought it was displacer for some reason. None of the other drak weapons seem to cause the problem.

**Comment by XOwnagex** [comment]
My game freezes as well often when I am fighting the Drak Archons with my fleet.
Might possibly be a bug?

**Comment by Isaacssv552** [comment]
What ships and outfits did you have? I've only tested the archon against quarg and korathi robot ships. (the robot ships freeze versus a Distancer, the quarg don't.) Since removing the Distancer I've been able to farm the robots for half an hour (with the Archon) with no freezing, with it I'd get a crashing within 5 minutes using an Archon.

**Comment by endless-sky** [comment]
Commit ef1ba82 should fix this.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
