### ISSUE TITLE
Required fuel for jump with both hyperdrive and jump drive installed.

### ISSUE THREAD

**Issue by adamsnd** [endless-sky/endless-sky#103]
Tested on Bactrian with both jump drive and hyperdrive simultaneously installed. When direct hyperspace route (hyperdrive-compatible) is selected, it appears that the hyperdrive-style jump is performed, including using 1 bar (100 units) fuel. Otherwise, jump drive is used, using 2 bars (200 units) fuel.

This appears to work as expected, saving fuel for close jumps and utilizing the jump drive for more distant/faster jumps. However, when a direct (hyperdrive-compatible) jump is the next jump, the "you do not have enough fuel to complete the jump" message appears even when fuel is above 100 but below 200. Once fuel reaches 200 (tested via ramscoop), the jump can be completed, but it only takes 100 fuel.

**Comment by endless-sky** [comment]
Are you running the latest release (0.8.3)? This ought to have been fixed in commit 58d6c94, which is included in that release.
