### ISSUE TITLE
MacOS Catalina Support Dropped

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#10307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In #10218, support for MacOS older than 13 was dropped. I use MacOS Catalina and probably won't update.

### Steps to Reproduce

1. Have a mac running Catalina (or any other pre-13 version)
2. Attempt to run Endless Sky post- 7c991d25ce96479b82bcf7ef4e80d38f9a45dc47
3. See error

### Expected Behavior

I expected support for older MacOS versions to continue.

### Screenshots

<img width="979" alt="Screen Shot 2024-07-08 at 11 16 06 AM" src="https://github.com/endless-sky/endless-sky/assets/125756761/b6f492ed-5168-4d7d-ac6b-5dd787fd6a3f">
<img width="419" alt="Screen Shot 2024-07-08 at 11 15 38 AM" src="https://github.com/endless-sky/endless-sky/assets/125756761/914ee078-6027-4bb2-a768-4b8edfe5d709">

### Link to save file

n/a

### Operating System

MacOS Catalina (10.15.7)

### Game Source

ESLauncher2

### Game Version

b2e805bdec73ab987d5d40e2ed87864ec3e2005f

### Additional Information

The game source is both ESLauncher2 and Github.

**Comment by tibetiroka** [comment]
macOS Catalina went end of life nearly two years ago. It's not supported by Apple, and having it as a release target prevents us from using modern C++ features.

Is there any good reason why you don't update? We can't maintain compatibility forever, especially if upstream discontinued the OS.
