### ISSUE TITLE
Add attribute to allow burst radius to go off immediately without the need of a target

### ISSUE THREAD

**Issue by Maryn-s** [endless-sky/endless-sky#10315]
### Problem Description

So not sure if this is a bug or a feature, but if not let's leave it as a feature :grin:

After fiddling around and combining the `penetration count` and `blast radius` attributes I realized we are pretty close to having a true mini-indiscriminate aoe field weapon. Only problem being that the projectile only triggers its blast radius when near its target OR at the end of its lifetime if using the `"fused"` attribute, which means the aoe field is **VERY** situational.

### Related Issue Links

#7891 brought up allowing `blast radius` to hit anything in the projectile's path. I can see this being a solution to that, but it does not fully address the issue with the projectiles themselves being indiscriminate, like an opposite of `no ship collisions` attribute. It would at most provide the illusion of a solution.

### Desired Solution

What I would like to be added is an attribute that acts independently or as an alternative to `trigger radius` that would simply make the projectile activate its `burst radius` as soon as it spawns. This would mean that the attribute would only be useful when combined with `penetration counter`, otherwise it would provide the same outcome as a `lifetime` of 1 with the `"fused"` attribute. **EDIT**: Now thinking about it, it would be something like in the opposite direction of `"fused"`, so instead of activating at the end of its lifetime, it would be at the start and throughout. Maybe `"fused"` could be changed so that it allows the option of setting when in the projectile's lifetime it applies its `blast radius` and how often.

### Alternative Approaches

I've thought about possibly making it so `split range` is changed so it does not always set a projectile's `lifetime` to 0. This would allow for a weapon to create a submunition every frame that would detonate as soon as it spawns, but it seems like a long workaround solution. Though it could resolve other issues, like the need to create dozens of the same outfit to allow the illusion of a projectile that keeps firing submunitions each time it splits. But I feel if such a feature were to be added it would be incomplete through this suggestion alone, because I would like some other properties to be added to it to address other issues that are unspecific to aoe field weapons.

### Additional Context

This issue is mostly meant to address aoe fields or waves, in particular to allow for aoe fields/waves that are nondiscriminatory. 

**EDIT**: Further Clarification: what this issue is meant to resolve is the lack of ability to create a true "hot zone", that is, an area on the map that would be instantiated by a weapon's projectile independent of the ship's behavior. i.e. a temporary ionized zone that damages all ship's energy systems that pass through it or are in its path (in the case of waves). This is only meant to address how the projectile behaves once it's live, not the ship itself. So the ship should have its own separate behavior in how it responds to using the weapon.

**Comment by Saugia** [comment]
Related: https://github.com/endless-sky/endless-sky/issues/9765

**Comment by Maryn-s** [comment]
Now thinking about it, it would be something like in the opposite direction of `"fused"`, so instead of activating at the end of its lifetime, it would be at the start and throughout. Maybe `"fused"` could be changed so that it allows the option of setting when in the projectile's lifetime it applies its blast radius and how often?

**Comment by Maryn-s** [comment]
After sifting through the source code I've come across a better means of approaching this. Since the problem described here relies on non-clarified information or information that may not be true, I will open a separate issue to not detract from the intended solution.
