### ISSUE TITLE
[enhancement] when combat ends, escorts should assist disabled escorts.

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1031]
at the moment, the player is left to fix up the remnants of their disabled fighters when large ships explode.

**Comment by lehgogh** [comment]
I haven't thought about it until now, but a command to tell members of your fleet to help other disabled fleet members would be nice.

**Comment by Alkallid** [comment]
Yes, they just gather around instead, while other NPCs repair their allies.

**Comment by jafdy** [comment]
Yes, would be so helpful.

**Comment by endless-sky** [comment]
I think the best way to do this would to have it apply to your escorts only if:
* they are not under orders to hold position or gather, and
* there are no enemy ships in-system.

**Comment by LocalGod79** [comment]
@endless-sky i like your analysis, but perhaps this could be dealt with similarly to "out of fuel" (and be easier to implement)?

**Comment by endless-sky** [comment]
I've added this in commit 3b962e4.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
