### ISSUE TITLE
Duplicate Outfit Descriptions

### ISSUE THREAD

**Issue by TheGiraffe3** [endless-sky/endless-sky#10310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In all outfitters I go to, the outfit descriptions are duplicated.

### Steps to Reproduce

Load the provided save file and go to the outfitter. See bug.

### Expected Behavior

Outfit descriptions are not duplicated.

### Screenshots

![Screenshot 1](https://github.com/endless-sky/endless-sky/assets/145969603/03bdeb87-4a30-4673-96eb-669f3a0cc19d)
![Screenshot 2](https://github.com/endless-sky/endless-sky/assets/145969603/83a2f7f5-1350-434a-9fca-595b28598ea2)
![Screenshot 3](https://github.com/endless-sky/endless-sky/assets/145969603/deb9bcf8-5483-49ce-b85b-f40147b8e068)

### Link to save file

[Asiah Racer Descriptions.txt](https://github.com/user-attachments/files/16162895/Asiah.Racer.Descriptions.txt)

### Operating System

MacOS Ventura 13.6.7

### Game Source

GitHub Releases

### Game Version

commit b2e805b

### Additional Information

While getting screenshots, it turned to three outfit descriptions. See the last screenshot.

**Comment by warp-core** [comment]
I suspect this is a result of the "Drop Loot" plugin (zip linked in this post: https://github.com/endless-sky/endless-sky/discussions/7928#discussion-4690076).

That plugin appears to redefine various outfits, including their descriptions, and descriptions are appended, not overwritten.
Related: 1764

**Comment by warp-core** [comment]
Could you also try disabling all the other plugins?

**Comment by TheGiraffe3** [comment]
That works, though I'm not sure why.
