### ISSUE TITLE
endless sky seems to crash with too many systems  even with large amounts of free memory? 

### ISSUE THREAD

**Issue by tigercoding56** [endless-sky/endless-sky#10328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

endless sky crashes with many plugins adding new systems

### Steps to Reproduce

install plugins adding custom thumbnails and then install as many plugins adding custom systems as you need to crash , then remove custom thumbnail plugins  (or resize all images in it to be 50% scale), it should still crash confirming that it is not a OOM

### Expected Behavior

let me eat as many plugins as i need to until memory is consumed or my thirst for missions is quelched

### Screenshots

not a screenshot but here to confirm not OOM
https://github.com/user-attachments/assets/e493001c-200e-4d66-be04-85d485ff0977

### Link to save file

not applicable but here anyway
[c56 c56.txt](https://github.com/user-attachments/files/16301516/c56.c56.txt)

### Operating System

 Nyarch Linux x86_64 

### Game Source

Other (please describe)

### Game Version

0.10.8-1

### Additional Information

got it from distro package manager

**Comment by tigercoding56** [comment]
here is terminal output  from when it crashes (log file says same thing)
![image](https://github.com/user-attachments/assets/9ed26d84-1fa4-4b0a-8a5d-8887596b15f0)
could it be possible that endless sky is still 32 bit

**Comment by tibetiroka** [comment]
> Normally what it is in this case is that the hardware can't handle the amount of memory ES is using.

I don't think so. The error suggests the issue is on our side; probably a system didn't get defined properly, and we are missing a check for that somewhere.

**Comment by tibetiroka** [comment]
Can you try enabling/disabling plugins one by one, to see if there is a specific plugin that triggers the crash? (I suppose it's possible that a combination of plugins trigger it...)

**Comment by tigercoding56** [comment]
the plugin causing it to crash is "/The Jump Gate Project/" but if i remove map.txt from it it is fine

**Comment by tigercoding56** [comment]
> Is that the new zuckung one? And if not, can you provide a link to the plugin?

it is the one from endless sky plugin archive (i just tested running it alone without other plugins and no crash)  here it is
[The Jump Gate Project.zip](https://github.com/user-attachments/files/16314861/The.Jump.Gate.Project.zip)

**Comment by warp-core** [comment]
Can you place your entire "plugins" folder into an archive of some sort (such as a zip) and upload that?
I've tried installing all the plugins I see listed in your save file (and I actually don't see the jump gate project there) and can't reproduce the crash (even after installing hte jump gate project).
Does it crash while loading or were you doing something in particular?

**Comment by xX-Dillinger-Xx** [comment]
And this is the problem with plugins. No control over quality.

**Comment by warp-core** [comment]
Your opinions on plugins are not at all useful in determining what is going on here and what should be done about it.

**Comment by tigercoding56** [comment]
> Can you place your entire "plugins" folder into an archive of some sort (such as a zip) and upload that? I've tried installing all the plugins I see listed in your save file (and I actually don't see the jump gate project there) and can't reproduce the crash (even after installing hte jump gate project). Does it crash while loading or were you doing something in particular?

crashes while loading 
(google drive link file size is a bit large ) https://drive.google.com/file/d/1F-1j7MzYfSCAGMhpDwblW60c8Dmg7P2S/view?usp=sharing

**Comment by tigercoding56** [comment]
should i rename the issue ?

**Comment by mOctave** [comment]
One thing that I notice with the Jump Gate Project is that it seems to include a copy of a good chunk of the map. Maybe that's related to the issue?

But it doesn't crash for me either (MacOS), and the plugin seems to work just fine despite the bloat.

My guess is it's a problem with how ES works with Nyarch, and there's something in that plugin file that trips it, maybe the fact that it's so long? `map.txt` in that plugin is slightly longer than the vanilla `map systems.txt`. Or the fact that its redefining so many systems?

Just shooting in the dark, though it definitely looks like an issue with ES rather than your plugins, (although on a side note I'd probably use [zuckung's new jump gate plugin](https://github.com/zuckung/endless-sky-plugins/tree/main/myplugins/jump.gates) over the Jump Gate Project myself if you want jump gates, it seems to be much better implemented).

**Comment by tibetiroka** [comment]
> My guess is it's a problem with how ES works with Nyarch, and there's something in that plugin file that trips it, maybe the fact that it's so long? map.txt in that plugin is slightly longer than the vanilla map systems.txt. Or the fact that its redefining so many systems?

It's probably system redefinitions. It seems to be missing one end of a wormhole somewhere. (Maybe that wormhole was added by another plugin, before the system got redefined.)

**Comment by tigercoding56** [comment]
> One thing that I notice with the Jump Gate Project is that it seems to include a copy of a good chunk of the map. Maybe that's related to the issue?
> 
i tried the modifications from https://github.com/endless-sky/endless-sky/pull/10333 , and it does not crash with them (it still starts crashing if i put in all of the endless-sky-plugin archive plugins but that  is probably actual OOM)
