### ISSUE TITLE
[bug] planets/systems without spaceport behave strangely when demanding tribute

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1032]
reported by the steam community
http://steamcommunity.com/app/404410/discussions/1/412446292774548942/

**Comment by endless-sky** [comment]
Fixed in 149d916. According to the Steam thread, the only remaining bug was that systems were displaying as dominated when the main planet had been dominated but any stations without spaceports had not been.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
