### ISSUE TITLE
Licence that lowers prices for outfits

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#1033]
What if there was a licence that had the ability to lower outfit prices? You could get the licence via a special mission, and would give the player the ability to buy outifit at a certian price, lower than the regular. It also would make looting less valuable, a fix to how overpowered looting is.

**Comment by jafdy** [comment]
Would it be global  or for single governments?

**Comment by Gkramme** [comment]
Single goverments, this would hopefully help in a future Quarg storyline.

**Comment by jafdy** [comment]
Ok, single government. I buy as many hand-to-hand outfits as I can in republic space, two or three jumps and I'm in free world space, and sell all for profit.

So global then. I can get a licence from the republic and buy stuff cheaper from the Wanderers. 

Sorry, I'm not trying to mean but there are problems with it at the moment.

**Comment by Gkramme** [comment]
It would lower prices universialy, render plundering less usefull. And be like a ship lisence.

**Comment by jmhorjus** [comment]
Many people down through the ages of history have complained about plundering being too quick a path to riches.  My preferred solution is https://github.com/endless-sky/endless-sky/pull/852

**Comment by Gkramme** [comment]
It wouldn't be a universal road to riches, it might make plundering, for a few select outfits, less valuable and overpowered.

**Comment by endless-sky** [comment]
Equivalently, if game events were able to change the statistics for outfits this could be done that way.

**Comment by LocalGod79** [comment]
#927?

**Comment by Gkramme** [comment]
@LocalGod79 no, that doesn't seem to be related to this.

**Comment by LocalGod79** [comment]
@Gkramme i think that it does - an outfit by the same name with different specs sounds exactly like a variant, and swapping them in and out of outfitters seems easier to code than making it possible to redefine weapons attributes.
