### ISSUE TITLE
Header guard naming scheme

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#10354]
### Location

code style guide

### Describe the issue

> All header files should have #define guards, and they should be in the format "#ifndef MY_CLASS_H_".
> The C++ standard technically does not allow source code files to define macros that start with an underscore or contain a double underscore.

The description of header guard naming is rather vague. Namely, it fails to address the naming scheme for files within subdirectories of the source directory. It also doesn't include information about whether we should be using custom prefixes for classes with common names.

### Expected content

It should have clear guidance on what header guards should be used in a file, even if it's in a different directory or has a special name.

**Comment by TomGoodIdea** [comment]
IMO every guard should either be based only on the class name / filename, without any prefixes for subdirs or special names, or we should add the `ES_` prefix to all guards. I prefer the former, if it doesn't create any conflicts.

**Comment by petervdmeer** [comment]
Discussed on Discord today with some Devs; let's first try "#pragma once" on the header files in the codebase. If it works for all our platforms and compilers, then let's update the Wiki to switch to "#pragma once" for all header files.

**Comment by gunqqer** [comment]
We already list gcc/g++ as a dependency, and it support #pragma once, I say switch to it
