### ISSUE TITLE
Cloaking device issues

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1035]
Cloaking device allows player to phase through mines and Drak should be able to target regardless of  cloaking.

**Comment by jafdy** [comment]
A 3D mine field in space dense enough to catch a ship that would go through it takes alot of mines. Every time you add a dimension you increase the power on the number of mines you need. To create a 1km line with 10m separation takes 100 mines, a 1km square with 10m separation takes 10,000 mines and if you want a cube then 1,000,000 mines. Practically if a space mine filed is to work then you need to have mines that can track you to some degree, the cloaking device blocks all but gravitational signals so most tracking will be useless.

As for the Drak it would imply they have gravitational sensors and why not. But It would probably be more effort then it is worth, but that is not for me to decide.

**Comment by endless-sky** [comment]
The cloaking device allows your ship to travel into the hypothetical "third dimension." :)

It's really no different than how your ship can fly above or below non-hostile weapons fire. I don't see why that one weapon, in particular, should work differently than all the others.

**Comment by mdsmestad** [comment]
@endless-sky Oh okay I guess that makes sense for the mines thing. Would it be difficult to create an atribute for the drak that allows them to see cloaked vessels (that mission where the drak warns you about the nanobots works when your cloaked)

**Comment by Bladewood** [comment]
Genius. We now have a canon explanation for the cloaking device: The universe is 2-dimensional.

**Comment by endless-sky** [comment]
It's a [Simpsons joke](http://globalwahrman.blogspot.com/2013/01/polygonal-artifacts-and-homer-simpson.html):

> Professor Frink: Here is an ordinary square.
> Chief Wiggum: Whoa, whoa! Slow down, egghead!
> Professor Frink: But suppose we extend the square beyond the two dimensions of our universe along the hypothetical z-axis . . . There.
> Everyone: [gasps]

At present, anything with a blast radius will damage cloaked ships, which I think is a good balance - you're still safe from most things, but if you wade right into a war zone you can take damage from exploding ships and large missiles.

It wouldn't be too hard to add a ship attribute allowing them to see cloaked ships, as well as a weapon attribute allowing it to hit cloaked ships, but at the moment that's not terribly high on my list of priorities.

**Comment by mdsmestad** [comment]
@endless-sky lol this whole thread made me chuckle.

**Comment by tehhowch** [comment]
a4a4b3e705ba39e2ab4310932cc1e9f4fcf8d87a made this true.
We don't have an attribute yet that allows tracking cloaked ships, but with #3599 a weapon could be designed to be blind fired and "shake loose" any cloaked ships (large blast radius, poor damage).
AI support for such a weapon's use is lacking (cloaking is treated like you jumped away.. goodbye, thanks for all the fish, back to our lives now) and would require cloaking to emit a ShipEvent, and the AI to react to such a ShipEvent by blindfiring weapons that have the "cloak disruption" attribute in the last known direction. (Support for firing at an estimated position and not a targeted ship would also need adding).
