### ISSUE TITLE
Feature Request: More intricate minable missions

### ISSUE THREAD

**Issue by Saugia** [endless-sky/endless-sky#10367]
### Problem Description

Currently, missions for collecting and delivering minables can only specify a single number. Cargo missions can be randomized because they're based on changing the cargo's type and number:

```
	job
	repeat
	description "Deliver <cargo> to <destination>. Payment is <payment>."
	cargo random 25 2 .05
	to offer
		random < 70
	on complete
		payment
```

However, minable missions are based on you delivering a total amount at the end of the mission, with an accept condition of the equivalent cargo space:

```
	job
	repeat
	name "Gather 10 tons of aluminum"
	description "Mine and collect 10 tons of aluminum, then bring the minerals back to <origin>."
	to offer
		random < 10
	to accept
		"cargo space" > 10
	on complete
		payment 36000
		outfit "Aluminum" -10
```

### Related Issue Links

N/A

### Desired Solution

I would like for minable missions to be able to be randomized similarly to how cargo missions are. That way, instead of there being set numbers for minable missions (smaller ones = 10, medium = 50, large = 100 or such). there can be a random variance to make the missions more unique (one job could read "Mine 7" and another "Mine 62").

Using the above example. perhaps something like this:
```
	job
	repeat
	name "Gather 10 tons of aluminum"
	description "Mine and collect 10 tons of aluminum, then bring the minerals back to <origin>."
	minable "iron" 7 62
	to offer
		random < 10
```

Though that would also require either a default check if the player has cargo space relevant to the given number or not. That could either be baked into the code for minable missions (I don't know if that's even possible), or user-defined like this?
```
	to accept
		"cargo space" > minable
```

Additionally, perhaps we could make it so that you could define more than one minable:
```
	job
	repeat
	name "Gather 10 tons of aluminum"
	description "Mine and collect 10 tons of aluminum, then bring the minerals back to <origin>."
	minable "silicon" 24 46
	minable "iron" 7 62
	minable "lead" 2 11
	to offer
		random < 10
```

Though these are just possible thoughts. There might be a more intuitive way to organize it, or code might require otherwise.

### Alternative Approaches

~~Making 100 jobs with 1-100 minables.~~

**Comment by TomGoodIdea** [comment]
related: #7761

**Comment by TomGoodIdea** [comment]
found one more, and this time it's exactly the same problem: #4926
