### ISSUE TITLE
Stuck in FW missions

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#104]
I have done the Katya missions and all escort missions for the Free Worlds, but I missed the Recon missions before the war has begun.

Now I'm stuck with "assisted free worlds" = 2 and cannot progress further, because the next mission "FW Commitment" requires "assisted free worlds" >= 3. Is it intentionally that you cannot do further FW missions if you missed the Recon missions before the event "war begins"?

AFAIS the FW missions is the only main quest in the game (right now), so this would be a pretty harsh decision.

**Comment by endless-sky** [comment]
The Pact recon missions are optional. Joining the Free worlds requires 
completing three mission threads:

- Helping Katya
- Recon for the Free Worlds (starts with scanning a cruiser in orbit)
- Escorting convoys

If you open your saved game file and find the "conditions" section, you 
can check whether there is a "FW ..." mission that has been offered but 
not "done"; that would indicate a mission that you declined, failed, or 
aborted. It might just be that you have not been offered the third 
mission thread yet.

**Comment by schlamar** [comment]
Ah yes, I might have declined the Recon mission, it is just as offered in my save game. I have removed the entry from my save game and I'm back on track now. 

Still weird, that you can be off from the main quest line with a simple decision and there is no way of getting back (officially).
