### ISSUE TITLE
ES is not longer buildable on the most recent Linux Mint

### ISSUE THREAD

**Issue by SomeTroglodyte** [endless-sky/endless-sky#10403]
### Location

General

### Describe the issue

Up until two weeks ago, ES was buildable on the most recent Linux Mint 22 "Wilma". Thanks to #10362 this is no longer the case. With Mint 22 being a month old, Mint users will be excluded for the next 23 months.

### Expected content

Clarify that distributions emphasizing long term support are undesirables.

https://github.com/endless-sky/endless-sky/blob/master/docs/readme-cmake.md#linux states a minimum of Ubuntu 22.04, however, by now, 24.04 "noble" is NOT ENOUGH.

**Comment by warp-core** [comment]
Linux Mint 22 seems to come with GCC 13 which, as far as I know, can still build Endless Sky.
What are you using to build the game?

**Comment by eebop** [comment]
Ubuntu 22.04 compiles fine on my system

**Comment by tibetiroka** [comment]
Have you tried doing a clean build? `cmake --build build --target clean` should clear the build directory. CMake sometimes gets confused when compiler options change, and doesn't recompile everything by itself.

**Comment by warp-core** [comment]
I set up a VM and installed [Linux Mint 22](https://www.linuxmint.com/edition.php?id=316), ran:
```bash
sudo apt install git cmake ninja-build curl libsdl2-dev libpng-dev libjpeg-dev libgl1-mesa-dev libglew-dev libopenal-dev libmad0-dev uuid-dev catch2
git clone https://github.com/endless-sky/endless-sky
cd endless-sky
cmake --preset linux
cmake --build --preset linux-debug
```
And it built.
It already had gcc 13.2.0 installed.

It seems to me like your cmake configuration hasn't been updated and it's still trying to build with an older version of C++.
Have you tried deleting the `build` directory and running `cmake --preset linux` before building?
