### ISSUE TITLE
Building on macOS Sonoma on Apple Silicon crashes

### ISSUE THREAD

**Issue by danaris** [endless-sky/endless-sky#10417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to build Endless Sky on macOS Sonoma on an Apple Silicon machine, it builds successfully, but instantly crashes on launch with the error message "Unable to query OpenGL version."

I have attempted to debug this some with little success, and do not currently have the time to devote to more detailed explorations, so I will do my best to document my findings here for others to pick up where I left off.

The error occurs in `GameWindow::Init()` on line 205. The call to `glGetString(GL_VERSION)` returns 0 rather than a string with the version info. When I added a call to `glGetError()` afterward, it returned `GL_NO_ERROR`.

- There does appear (from my limited explorations) to be one genuine bug related to this: the calls to `SDL_GL_SetAttribute` for the OpenGL major and minor versions should not be `#ifdef`ed out for Apple builds.
- Doing this, creating the GL context, then querying the OpenGL versions through the SDL functions does return the correct major and minor versions. If the only problem were the query to the version, this would be a feasible workaround.
- However, the other `gl*` functions also seem to return 0, with the next critical one being the call to `glCreateShader()` in `Shader::Compile()` on line 96 of Shader.cpp.
- I put together a minimal test file with just the bare-bones calls to SDL and OpenGL that ES uses to initialize, and it exhibited the same behavior.

My provisional hypothesis is that there is some kind of initialization that the version of OpenGL on Sonoma is expecting (that previous versions, and non-Mac versions, don't for some reason), that we're not doing because SDL should be handling all that fine. Unfortunately, I don't know enough about the various different ways of using OpenGL to be able to check without significantly more research.

It's also worth noting that **OpenGL support is deprecated on macOS as a whole**. While _hopefully_ this particular bug can be resolved by something much simpler, I would be very interested in whether it's feasible to work on porting the graphics code of ES over to Vulkan, which is more modern and will continue to work on macOS through the MoltenVK library (which translates the Vulkan commands to Metal commands). The other potential option in this vein would be to abstract the graphics processing in such a way that we can have multiple rendering pipelines (selected at compile-time)—a Metal pipeline for macOS and the legacy OpenGL pipeline for other platforms. IMO, abstracting the graphics processing would be very valuable in any case. However, I recognize that _any_ of these options would be a pretty monumental undertaking.

### Steps to Reproduce

1. Check out a current copy of the repository.
2. Configure CMake for macOS ARM `cmake --preset macos-arm`
3. Open VS Code and point it at the ES directory.
4. Build & run the game.

### Expected Behavior

Game should run with the same OpenGL code it's used for years.

### Operating System

macOS Sonoma 14.6.1 (23G93)

### Game Source

Built from source

### Game Version

9d47765833fb68079a169e4bb453808d1ca265a2

**Comment by TomGoodIdea** [comment]
If we're going to add Vulkan, we should leave OpenGL as a fallback option as there's a lot of older hardware without Vulkan support.

**Comment by tibetiroka** [comment]
> having two render backends is not as much work as people might think.

We could probably just use some translation layer like MoltenVK or GLOVE.

**Comment by danaris** [comment]
> I can confirm that this is an ES specific issue, all my other opengl projects executed fine, worth noting that I use glew for them.

Yeah; I also have another tiny project (just doing some OpenGL tutorials to try to learn how to do the stuff better) that still works fine, but it's using glut rather than glew.

**Comment by Koranir** [comment]
Have you tried uninstalling xcode/clearing build files/reinstalling homebrew dependencies? I've seen reports that this fixes similar issues.

**Comment by danaris** [comment]
> Have you tried uninstalling xcode/clearing build files/reinstalling homebrew dependencies? I've seen reports that this fixes similar issues.

- Uninstalling/reinstalling Xcode: Just tried now; same result
- Clearing build files: Yes; when I tried the build yesterday the first thing I did was to set aside my old build folder(s) and rerun the `cmake --preset`
- Reinstalling homebrew: I don't use Homebrew; I use MacPorts, and my setup right now is...a bit of a mess, such that it would be quite a pain to try to uninstall and reinstall it. However, I can definitely test it on a completely separate Apple Silicon machine tomorrow morning.

**Comment by danaris** [comment]
> * Reinstalling homebrew: I don't use Homebrew; I use MacPorts, and my setup right now is...a bit of a mess, such that it would be quite a pain to try to uninstall and reinstall it. However, I can definitely test it on a completely separate Apple Silicon machine tomorrow morning.

I have now tested on the aforementioned separate Apple Silicon machine, with good results:

- I didn't have the ES code, nor did I have most of the dependencies installed, on the second machine, so it gave a good chance to get a clean slate.
- Once I installed the dependencies, it ran just fine!
- I then compared the CMakeCache.txt files between the two machines, and found that my primary machine was attempting to build using the copy of OpenGL installed by MacPorts rather than the Apple-supplied one in Xcode. I'm not at all sure _why_ this made the difference, but when I changed the value in CMakeCache.txt to the Xcode version of OpenGL, I was able to successfully build and run ES again on my primary machine.

I do still have 2 notes about the whole process that I'm not sure where they fall:

1. When running ES this way, the version of OpenGL it reports in the `glVersion` variable is 4.1. Presumably this doesn't cause any problems with our expectation of "3.0 or greater"? Also presumably, this invalidates my earlier comment about not setting the GL version for Mac being a bug (previously, when I left it unset and retrieved the version with the SDL functions, it was getting a version of 2.1).
2. For reasons I don't entirely understand, Visual Studio Code, with the C/C++ and CMake Tools extensions, doesn't seem to know how to invoke lldb in a way that works out of the box. I had to install a shim and symlink that into the directory with the Xcode dev tools where VSC was expecting to see it. 

So...I don't know whether this is the same reason that other people have had this error attempting to build ES on macOS Sonoma on an Apple Silicon machine, but it does seem to have fixed it for me.

I also think that it would be valuable to continue discussing the possibility of migrating to Vulkan or some other modern rendering method—as I said, OpenGL is deprecated on macOS, and they could decide any year with the new version that it's finally time to abandon it entirely. However, that is best shunted to a Discussion, rather than a mostly-unrelated issue report.

**Comment by danaris** [comment]
> Reopening as I am not using ports and still experiencing the issue

Fascinating.

In your CMakeCache, what values do you have for `OPENGL_GLU_INCLUDE_DIR`, `OPENGL_INCLUDE_DIR`, `OPENGL_gl_LIBRARY`, and `OPENGL_glu_LIBRARY`?

**Comment by mOctave** [comment]
I haven't been having any problems with Apple Silicon lately myself, but in case you want info from someone without any issues:

```
//Include for OpenGL on OS X
OPENGL_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework

//OpenGL library for OS X
OPENGL_gl_LIBRARY:FILEPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework

//GLU library for OS X (usually same as OpenGL library)
OPENGL_glu_LIBRARY:FILEPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework
```
and no value for `OPENGL_GLU_INCLUDE_DIR`

I am building with `-DES_USE_SYSTEM_LIBRARIES=OFF`, which might have some effect?

As someone with very, very little knowledge about OpenGL, Vulkan, and MoltenVK, transitioning to Vulkan seems like a good idea, both because OpenGL is deprecated and because I think it would probably make writing an iOS port for ES significantly easier.

**Comment by danaris** [comment]
I've posted a Discussion (#10428) to bring the broader issue of the graphics pipeline out to be addressed on its own merits.

**Comment by waterhouse** [comment]
Thanks for this thread, it enabled me to figure out what went wrong on my system.  I had used homebrew to try to build wine, which made it install "xquartz", which caused CMake to find the wrong OpenGL stuff (i.e. "OPENGL_INCLUDE_DIR:PATH=/usr/X11R6/include" and similar); editing the OPENGL_INCLUDE_DIR and associated variables to @mOctave 's values made it work, and uninstalling "xquartz" allowed me to "cmake .. && make" a full build from scratch with no problems.
