### ISSUE TITLE
Mod maker inside of Endless Sky

### ISSUE THREAD

**Issue by ehervidush** [endless-sky/endless-sky#1043]
My idea is to have a "Mod Maker" mode inside of the endless sky game. I think that this would make mods easier to make and have them run

**Comment by toilethinges** [comment]
Steam workshop support/modding site is on the roadmap.

**Comment by endless-sky** [comment]
Do you have ideas of what a "mod maker" mode would allow the user to do? I suppose it could be useful for tweaking a ship's or weapon's attributes and test-driving it in realtime, but nearly all the time involved in making a mod is things that can't easily be done within the game: creating graphics, composing test, etc. And, there's already a [map editor](https://github.com/endless-sky/endless-sky-editor/releases), a [ship builder](http://endless-sky.github.io/ship_builder.html) and various other [tools](https://github.com/endless-sky/endless-sky-tools) available to assist with mod-making.

**Comment by Isaacssv552** [comment]
I can't believe I didn't realize there was a ship builder. That would have made things so much easier than manually adjusting the pixel count of savegames for repeated testing.
