### ISSUE TITLE
0.9 unstable: Unable to complete Free Worlds "Defend Sabik" mission

### ISSUE THREAD

**Issue by Griffinhart** [endless-sky/endless-sky#1044]
Got the "Defend Sabik" mission. Destroyed/captured all Republic Navy ships in local space (i.e. mashing the "Select Nearest Hostile Ship" key did nothing), landed back on Longjump, mission's still not complete. Undocked, and there are no Republic ships in space at all, though I still have a bunch of Free World militia ships following me.

What do? I can provide a save, if necessary.

**Comment by Disiuze** [comment]
Capturing ships for missions has been causing a lot of bugs lately. I think it's best you restart from your autosave or edit your save to do the mission again but without capturing.

**Comment by Griffinhart** [comment]
Bah, damn. I don't think I have a particularly recent autosave. What would I need to modify in the save file to redo the mission?

**Comment by endless-sky** [comment]
This will be fixed in 0.9.1. Right now there's a bug where if you capture a ship, it doesn't count as evaded / destroyed, but commit 9deba41 fixes that.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
