### ISSUE TITLE
(Bug) Weapons Still Not Firing After Scramble Wears Off

### ISSUE THREAD

**Issue by AvianGeneticist** [endless-sky/endless-sky#10442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As a foreword, I have found **very** few consistencies with iterations of this bug. Please forgive the ensuing onslaught of "likelies" and similar adjectives.

Scrambling Damage is designed to stop weapons from firing, but this is very particular. After scrambling, a weapon will uncommonly become seemingly permanently disabled; it won't fire for an extended period of time. In some cases, I've had the bug persist for upwards of 10 minutes' time, before just fixing itself and not being able to be retriggered until the next time I jump or take off.

The behaviour is inconsistent with scrambling in the way that it affects weapons. It ignores fire rate (though the bug does seem to like slower firing weapons more), and consistently affects the same weapon, at least for a while, until (presumably) enough changes about the ship's kit for the bug to go to someweapon else.

### Steps to Reproduce

It's hard to give a definitive guide on how to trigger this bug, but I'll do my best.

For best results (based on the corroboration of others), use a Dragonflame Cannon. This bug seems to like it the most (though presumably other slow firing weapons like a Nullifier or whathaveyou would work as well; I've personally had it happen on pulsed beams before).

The second part is simple... If you can get it to happen at all. Fight something with scrambling damage, let it rough you up, then run away and wait for the scramble to dissipate. If the bug has triggered, you won't be able to fire one of your weapons.

### Expected Behavior

I'd assume when scramble is gone I'd be able to fire all my weapons like normal.

### Operating System

Windows 11

### Game Source

ESLauncher2

### Game Version

v0.10.9-alpha

**Comment by Quantumshark** [comment]
I have also experienced this.
