### ISSUE TITLE
Tace Mesa are scannable

### ISSUE THREAD

**Issue by tekker2234** [endless-sky/endless-sky#10457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The new indigineous lifeforms added with the Incipias lack "inscrutiable" and can thus have their outfits scanned. I assume this is unintentional.

### Steps to Reproduce

1. Go to Il'le
2. Scan Tace Mesa
3. See their outfits

### Expected Behavior

You should not be able to see their outfits when scanning them.

### Screenshots

![Screenshot 2024-09-12 125731](https://github.com/user-attachments/assets/52f49f1b-978f-4e6e-bdf0-247008e40e5f)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

10.9 alpha (6889a08)

**Comment by TomGoodIdea** [comment]
Feel free to open a fix PR.
