### ISSUE TITLE
Invert Fast Forward Toggle

### ISSUE THREAD

**Issue by mnyamamo** [endless-sky/endless-sky#10450]
### Problem Description

For those who constantly have fast forward on, typing causes constant toggling as users switch between caps lock on and caps lock off.

### Related Issue Links

https://discordapp.com/channels/251118043411775489/285540320823869441/1282807639419392030

### Desired Solution

Create a toggle in the settings tab to invert the fast forward toggle. This would allow users who constantly have fast forward on to play with their caps lock off.

### Alternative Approaches

NONE

**Comment by Koranir** [comment]
You could change the fast-forward keybind instead (mine is set to left alt, for instance).

**Comment by mnyamamo** [comment]
> You could change the fast-forward keybind instead (mine is set to left alt, for instance).

This works just as well
