### ISSUE TITLE
Rename "repair" energy and heat to separate "hull repair" and "shield regen"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1045]
Below "firing" energy and heat, there is this one obscure "repair" label. It took me quite a while to figure out that the value next to it was the shield energy.
Looking at the code, it appears that you have implemented the hull repair mechanism, and where it is applied, it usually takes energy to repair. But, I think you mixed this energy with the shield energy.
I think you should separate them, with individual labels, so that people without batteries who are using this technology have an easier time trying to figure out what the hell is holding them in place when their shields are down or their hull is damaged.

**Comment by endless-sky** [comment]
I renamed it to "charging shields" if the ship has no hull repair (76dd50d). If I split the two out into separate lines, I'd have to make the player / ship info panel even taller to accommodate the extra line of text, and I'd prefer not to do that for a line that is so often zero.

**Comment by Bladewood** [comment]
Okay, that helps, I guess.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
