### ISSUE TITLE
Map jump pathing breaks when in a system with increased jump distance while jump drive equipped

### ISSUE THREAD

**Issue by Lauren-Ray** [endless-sky/endless-sky#10462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having a player ship with an equipped jump drive, in a system with a jump range greater than the default 100, and attempting to plot a course to another system beyond the default jump range in the map screen, results in no jump path being plotted. The destination system is selected, the number of required jumps displayed on the top of the screen is correct, but no yellow line is traced. If the player subsequently attempts to jump, the player ship will instead jump towards the system in front of its current heading, which is the behaviour when no navigation path is selected in the map screen. This jump **can** use the extended jump range, suggesting that the issue might be somewhere in the map's pathfinding.

### Steps to Reproduce

1. Modify a system, e.g. Sol, or create a new one, with an increased jump range. Tests were done with values of 200, 250, and 1000.
2. Have the player ship with a jump drive. It can in addition have a hyperdrive or a scram drive, this does not change the unwanted behaviour.
3. Have the player ship inside the system with extended jump range.
4. Open the map view and select a system outside the default jump range of 100. It can be inside or outside the extended range, the unwanted behaviour stays the same. The sign at the top of the screen will show the correct amount of jumps, but a path to the system will not be traced.
5. Leave the map screen and press the jump button. The ship will instead jump towards the system that is in front of the ship's current heading, as it does when jumping without a path plotted in the map screen.

### Expected Behavior

Expected behaviour is that a ship with a jump drive installed, existing in a system with a jump range >100, will be able to trace a jump path to its destination in the map screen and thus navigate to other systems normally.

### Screenshots

Showing Sol system with jump range of 250, player ship with a normal jump drive, selecting a destination beyond 100 units:
![image](https://github.com/user-attachments/assets/c346c67d-9de4-460c-8929-d1eaccd4044a)

Same situation, selecting a destination within the jump drive's normal range works as usual:
![image](https://github.com/user-attachments/assets/435acc31-263c-4280-b81d-10598d9dbc8b)

### Operating System

Windows 10 Pro, 10.0.19045

### Game Source

GitHub Releases

### Game Version

v0.10.8

**Comment by alextd** [comment]
The DistanceMap code gets a list of neighbors based on ship range, and only after that checks the system's range, so it won't find those longer ranges.

https://github.com/endless-sky/endless-sky/blob/4c1462557fcb0ae63135dfd3dd06c0b546d4f810/source/DistanceMap.cpp#L280

https://github.com/endless-sky/endless-sky/blob/4c1462557fcb0ae63135dfd3dd06c0b546d4f810/source/DistanceMap.cpp#L335

PS: please don't fix this until My DistanceMap overhaul is merged in #6940 Heck I'll fix it myself once that's done

**Comment by alextd** [comment]
Hello, I'll do this soon, so navigation uses system's jump range ( along with handling multiple jump drives on a ship )

https://github.com/alextd/endless-sky/tree/multi-jump-range

**Comment by alextd** [comment]
Oh my guys, that was a real debugging adventure. PR is #10704

This problem wasn't even in DistanceMap. JumpNeighbors actually does use the system's range. The real bug was in a change last year (also about Ssil Vida) that double-checked the jump range of the travel plan and invalidated it, but didn't check the system jump range correctly!

**Comment by tibetiroka** [comment]
In runtime? You can just use a debugger, with breakpoints and all the fancy features you want. Otherwise, just by reading the source code? I'm not quite sure what you mean.

**Comment by tibetiroka** [comment]
I just use JetBrains' CLion for free with a student license... it has modest gdb integration, with conditional breakpoints and stuff. Other people probably just use vscode.
