### ISSUE TITLE
Enhancement: Add a `has <outfit>` condition. 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1047]
Add a `has <outfit>` condition.

**Comment by endless-sky** [comment]
Have you tried the [require &lt;outfit&gt;](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#triggers) mission action? That should do what you're looking for.

**Comment by jafdy** [comment]
Cool. Didn't Know that was there.
