### ISSUE TITLE
Improve mission list UI

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#105]
My mission list is full with "Hunt down" missions:

![screen shot 2015-09-17 at 15 12 04](https://cloud.githubusercontent.com/assets/238652/9933923/9f745b94-5d4e-11e5-889e-ffb376e619d0.png)

It's really hard to get the current important missions, especially because scrolling does not really work smoothly here (you need to click to scroll).

Reverse the mission list would be an acceptable solution for me, but a better UI would be nicer.

**Comment by endless-sky** [comment]
As a first step, I'm planning to add scroll wheel support and to make all
"unique" missions show up at the start of the list. I'm open to suggestions
for reworking the whole UI, but that might take longer.

**Comment by endless-sky** [comment]
The next release (in a few weeks) will include three changes to help with this:

* Scroll wheel support for the mission lists
* Unique missions will show up at the top of the list
* The "current missions" list will be able to scroll up a bit more to clear the buttons at the bottom of the screen (so they won't overlap as shown in your screenshot above).
