### ISSUE TITLE
enhancement: shield/hull heat attribute

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1050]
at the moment, the outfitter screen has an option that is always 0. (repair/shield heat)

perhaps some shield generators create (edit; or consume) a lot of heat (while being more/less energy efficient) while recharging?

new attribute, please.

**Comment by endless-sky** [comment]
Added in commit 2a0bda1 and 8bc9d0e.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
