### ISSUE TITLE
Outfits with no heat generation value listed 

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#1051]
There are various outfits with no heat generation value listed that still add to your heat generation.
Examples include photovoltaics, Battery Packs and Supercapacitor.

**Comment by brendanjones** [comment]
...and fuel pod. That's odd.

**Comment by DingusShingleton** [comment]
Do you mean the "Max:" statistic? Cause I am buying and selling those outfits and only "max" changes, which is not heat generation. What version are you using?

**Comment by endless-sky** [comment]
Max heat capacity depends on the mass of your ship, so adding any outfit with nonzero weight increases it. It shouldn't increase any of the heat generation values, though (idle, moving, firing, or repairing).

**Comment by brendanjones** [comment]
Yes, only max. That's a very odd mechanic - shouldn't it be a static number for each ship type?

**Comment by Disiuze** [comment]
Not really, if I heat up 1 kilogram of iron it takes longer than heating up 1 gram of iron. So it's not very odd but just Physics.

**Comment by jafdy** [comment]
Yes but different materials take different amounts of energy to heat the same mass by the same amount.

Lets no go to far down that road.

**Comment by DingusShingleton** [comment]
The point is, increasing heat dissipation by increasing mass is physically sound. It is the whole basis of heat sinks in fact.

**Comment by brendanjones** [comment]
Yes but your entire ship does not act as a heat sink, so only outfits that directly add to/mitigate heat should actually change the values. 

Let's use your car as an example. If I pop a jerry can of fuel in my car's boot to extend my car's range, it's not going to change my car's how much heat my car can take, at all (ok, very very very slighty, but's let's not nitpick). 

Also, if every bit of mass added to your ship acts as a heat sink, then why doesn't adding cargo and/or crew add to your max heat value?

And on a slightly separate note, I think Photovoltaic panels should generate heat.

**Comment by endless-sky** [comment]
Actually, adding cargo *does* increase your heat capacity. Adding crew does not because they don't increase your ship's mass.

As a first-order approximation, your ship is one big conductor surrounded by an exceptionally good insulator (the vacuum of space). That's very different from your car (unless you take it outside the troposphere) because the rate of heat exchange between parts of your car and the atmosphere can be considerably higher than the rate of exchange between different parts of your car.

**Comment by brendanjones** [comment]
> Actually, adding cargo does increase your heat capacity. 

Huh - so it does. I checked by adding cargo to my ship before I posted above, but I didn't leave the planet, hence my mistake. But that brings up another issue: your heat capacity due to cargo doesn't change while still planetside. 

If you add cargo then take off and look at your ship info then the change due to cargo shows up, but when you land again and check your ship stats (before selling the cargo), your stats display as if you have no cargo onboard.

**Comment by toilethinges** [comment]
@brendanjones - The outfitter screen is for your ship itself, and it already says "mass without cargo" on it. That suggests that cargo increases your mass, therefore increasing your max heat capacity. It doesn't show your plain mass (current mass) there, does it?
