### ISSUE TITLE
Fines for illegal outfits on uninhabited worlds

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#1053]
This has come up before, but it looks like the fix hasn't been applied for any of the new worlds added in 0.9.0, as I'm getting fines on uninhabited Korath worlds.

**Comment by toilethinges** [comment]
The security was changed to 0 after 0.9, so this is fixed in 0.9.x, if I'm correct.

**Comment by jafdy** [comment]
0.9.1
0.9.x  is a mid term to-do-list

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
