### ISSUE TITLE
Unusual Bug (No ship?)

### ISSUE THREAD

**Issue by VaelophisNyx** [endless-sky/endless-sky#10547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Struggling to find anything in the search about this, but
got a weird bug, and it potentially could be a side-effect of some plugin but...when I try to land on the Quarg ring-world over by the gegno, the game auto-relaunches instantly...but...My flagship is not under my command and it acts like there's no ship for me to control at all. And qualifies my pilot as Dead? No dialogue at all.
The quarg also turn hostile after the broken launch.
I haven't even interacted with the gegno or quarg in any capacity on this pilot.

I'll attach a copy of my save file, and link an exact copy of my entire plugins list (except the High-DPI addon)

### Steps to Reproduce

1. Load the save and jump to the quarg-gegno ringworld
2. Land
3. Get relaunched into a broken state

### Expected Behavior

Expected to land and at least be able to refuel, save, and launch

### Screenshots

![image](https://github.com/user-attachments/assets/2052fbdf-7726-4ec4-9787-307b6ddb7192)
![image](https://github.com/user-attachments/assets/6073f396-8b24-4407-b603-8fc2b9fd531a)

### Link to save file
-Redacted, no longer needed-

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v0.10.9 (Unstable)

**Comment by TheGiraffe3** [comment]
Related: #10504 #10507

You're on the Quarg planet but can't read the conversation because you die too quickly. That accounts for part 1.

I've also experienced the die-and-launch aspect. Apparently when you die the people who kill you commandeer your ship, but whenever you reach a `die` endpoint your ship launches while you're staring at the empty space above the planet.

**Comment by VaelophisNyx** [comment]
I just use the steam betas feature so I'll just have to wait I guess.
Thanks for pointing out what was happening

**Comment by TheGiraffe3** [comment]
No, keep it open, because ships shouldn't be launching after death.

**Comment by VaelophisNyx** [comment]
Oh, I see. Thought that was covered by one of the two mentioned issues already

**Comment by VaelophisNyx** [comment]
Easier reproduction steps:
Just land on a quarg world with any quarg outfit. Should be repeatable, and needs no plugins to trigger

**Comment by TomGoodIdea** [comment]
> No, keep it open, because ships shouldn't be launching after death.

Could you explain why they shouldn't?

**Comment by VaelophisNyx** [comment]
> > No, keep it open, because ships shouldn't be launching after death.
> 
> Could you explain why they shouldn't?

if you hit a "you die" event it shouldn't continue the game from there; or in other words, the post-death launch causing this somewhat broken game state shouldn't be happening at all

**Comment by TomGoodIdea** [comment]
> if you hit a "you die" event it shouldn't continue the game from there; or in other words, the post-death launch causing this somewhat broken game state shouldn't be happening at all

see #9717

**Comment by TheGiraffe3** [comment]
Except for that issue doesn't describe the ship launching seemingly without control.

**Comment by TomGoodIdea** [comment]
> Except for that issue doesn't describe the ship launching seemingly without control.

This issue is essentially a duplicate of that one (and the death conversation one) even if it adds some more context. If you feel that this context should be mentioned somewhere not to be forgotten, please comment on the original issue.
