### ISSUE TITLE
Fleet jumps while only partially refueled

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1054]
I have a jump drive. The rest of my fleet has hyperdrives. Nothing wrong there.
I jump to another system and wait for my fleet to follow.
They take forever, and in the meantime, I board a ship and land with its cargo.
But when I land, it does not 'instantly' refuel the rest of my fleet, like it does with their shields and hull.
They jump, only partially refueled.
Confuse.

**Comment by Wrzlprnft** [comment]
If they are not in the same system, they won't repair or refuel, as far as i know.

**Comment by Bladewood** [comment]
That's sad.

**Comment by jafdy** [comment]
If they did we would get a bug report about it.

**Comment by Isaacssv552** [comment]
It's most annoying when you have to escort freighters. It would be nice to temporarily install jump drives for escort mission and have them returned to cargo afterwards.

**Comment by DingusShingleton** [comment]
If you are tossing around jump drives that easily, do you really need to worry about escorting freighters?

**Comment by Isaacssv552** [comment]
You do for story missions. Also Ursa Polaris and probably many other plugins.

**Comment by jafdy** [comment]
I just equip 15 of my ships with jump drives. I get more ships by the end of it.

**Comment by Isaacssv552** [comment]
I did that too, but it's annoying to have your allies complain about the lack of jump drives when you have 100+ in storage and 10+ in cargo.

**Comment by LocalGod79** [comment]
whoah, whoah, whoah...

mission npcs *do* refuel when you land, regardless of whether or not they are in the same system as you. (referring to Ursa Polaris, and other escort missions)

that your owned escorts do not (refuel in other systems when you land) is balance to you being able to park them, fly to where you're going, unpark them, and pay only one day's salary to get them across the galaxy...
