### ISSUE TITLE
Bug: Reverse thrusting prevents flagship from turning to face cursor 

### ISSUE THREAD

**Issue by Koranir** [endless-sky/endless-sky#10546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using mouse turning your flagship doesn't turn to the cursor while reverse thrusting, despite being able to while thrusting normally. I don't think this is the intended behaviour as you can still turn with the keyboard (if you disable mouse turning) while reverse thrusting.

### Steps to Reproduce

1. Enable mouse controls
2. Start reversing
3. Wiggle your cursor and watch as your flagship does nothing but reverse

### Expected Behavior

The flagship should still turn to face the mouse cursor while reverse thrusting. 

### Operating System

EndavourOS with Linux 6.10, KDE Plasma 6.2 Beta on Wayland

### Game Source

Built from source

### Game Version

Latest Commit

### Additional Information

Reverse is bound to the 's' key in my case but I doubt it'd make a difference, it works perfectly normally.

**Comment by TomGoodIdea** [comment]
> I don't think this is the intended behaviour as you can still turn with the keyboard (if you disable mouse turning) while reverse thrusting.

Actually, it may be intended:
https://github.com/endless-sky/endless-sky/blob/c8c2d8e3956d700743c4ec3ca0c462f7d570a187/source/AI.cpp#L4525-L4526
but I agree it doesn't seem logical.

**Comment by Koranir** [comment]
> > ` && !ship.IsReversing()`
> 
> Plays perfectly fine IMO with this piece removed. Good find. Nice being able to precisely back up into a narrow driveway - what no garages in ES either?

Does it work fine if the ship has no reverse thrusters and/or shift+reverse is used?

**Comment by Koranir** [comment]
> In case anyone wants to try: [endless-sky - Linux-release + starry + reverse-manoeuvres-in-the-dark.tar.gz](https://github.com/user-attachments/files/17297480/endless-sky.-.Linux-release.%2B.starry.%2B.reverse-manoeuvres-in-the-dark.tar.gz) [1](#user-content-fn-1-b316539bd012398c258ac16491a8bb7a)

>Does it work fine if the ship has no reverse thrusters and/or shift+reverse is used?

>Untested. You test it. No reason why not though. Could give some jittery jerks with Mouse and Turnaround contradicting each other each frame, but who would want to fly without RV? Those Bow Drives are what we massacre all those Korath for after all...

Interestingly enough, this works perfectly. No jitter, turning takes priority over the mouse. It does seem like that restriction is just useless.

**Comment by tibetiroka** [comment]
Fixed in #10790.
