### ISSUE TITLE
13+ bounty quests accepted, 13th quest marker does not show

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1056]

**Comment by Gkramme** [comment]
That's because the missions loop around the system, so you cannot see it until you complete one of the missions for that system.

**Comment by jafdy** [comment]
It will happen if you have enough mission of any kind. Could you change the title to 13+ missions accepted...
the limit is good as that stops parts of the map being filled with small blue arrows.

**Comment by endless-sky** [comment]
It seems to me that if you have more than 12 missions to a destination, the exact matter won't really matter to you. That is, I can't think of a situation where the player would say, "Oh, if there were 13 missions I would go there but I won't because there are only 12."

**Comment by Haravikk** [comment]
Could the arrows "double up"? For example, the first twelve missions give regular arrows, then accepting a thirteenth adds a mark above the first arrow, fourteenth adds one above the second and so-on. It means that accepting more missions would slowly cause the ring of arrows to grow in size, but it would take 12 more missions for every increase so it shouldn't be too disruptive, plus there could still be an upper limit of say 36, which should be even less attainable than 12 (I've hit the 12 limit myself by accepting a load of bounties then getting a heap of other missions back to the same system).
