### ISSUE TITLE
More interesting backrounds/backdrops.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1057]
I like black starscapes, but I'd love to see more diverse backrounds. Add some purple and blue haze textures to some systems, moving comets, etc. Would add a little extra something.

**Comment by endless-sky** [comment]
I think it's really hard to do that without it looking tacky. I also like the fact that right now, systems with "backgrounds" (i.e. [huge star graphics](https://github.com/endless-sky/endless-sky/blob/master/images/star/nova%2B.jpg)) are rare enough that when you find something, you feel like you've discovered something special.

Note that in terms of real physics, even if you were in the center of a nebula it wouldn't appear to you to be anything more than a barely visible haze in the distance; the only way telescopes get those bright images is with very long exposure times (and often, false coloration, as well).

**Comment by mdsmestad** [comment]
@endless-sky You have a point there..What about backround comets or other moving elements (other than asteroids) that are non-interactable (purely backdrop like stars)

**Comment by jafdy** [comment]
Again it is prone to become tacky. Besides anything that you can see moving must be going very fast or be close to you or more likely both.
Could you make something to show what you would like?

**Comment by LocalGod79** [comment]
comets could be added as planetary sprites...

**Comment by jafdy** [comment]
Dose the game engine support elliptical orbits?

**Comment by LocalGod79** [comment]
while i'm pretty sure they're all circular, i'm also pretty sure that the sprite would always be oriented correctly, and that an offset (if still round) orbit is possible.

**Comment by mdsmestad** [comment]
@LocalGod79 I'm envisioning a bright, smallish glowing blue orb with a transulent blue tail slow moving in orbit around a system in the backround.

**Comment by Gkramme** [comment]
A comet's tail always points away from a star, so the comet would need to be programmed to keep it's tail side away from the star

**Comment by LocalGod79** [comment]
@mdsmestad that would be incongruous with the rest of the planetary movement within systems.  i'm not averse to the tails of the comets being animated, but their movement should not be drastically different than the rest of the planets...

@Gkramme i knew this - since planetary objects are already programmed to orient their sprites in relation to the star, having the comet's tails point in the correct direction should just be a matter of making sure that the sprites are oriented according to the standard...

**Comment by jafdy** [comment]
The orientation could also be along the normal of there orbit which would look odd with offset orbits.
