### ISSUE TITLE
Trouble building on Debian 12

### ISSUE THREAD

**Issue by zjdev** [endless-sky/endless-sky#10583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

cmake fails looking for catch2/catch_all.hpp on Debian 12 / bookworm

### Steps to Reproduce

1. ensure dependencies are installed
2. unzip 0.10.9 zip
3. start build

### Expected Behavior

cmake succeeds

### Operating System

Debian 12.7

### Game Source

GitHub Releases

### Game Version

0.10.9

### Additional Information

Unsure if I should be building tests at all, not building debug target.

root:/opt/endless-sky/endless-sky-0.10.9 # apt install g++ cmake ninja-build curl libsdl2-dev libpng-dev libjpeg-dev libgl1-mesa-dev libglew-dev libopenal-dev libmad0-dev uuid-dev catch2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
g++ is already the newest version (4:12.2.0-3).
cmake is already the newest version (3.25.1-1).
ninja-build is already the newest version (1.11.1-1).
curl is already the newest version (7.88.1-10+deb12u7).
libsdl2-dev is already the newest version (2.26.5+dfsg-1).
libpng-dev is already the newest version (1.6.39-2).
libjpeg-dev is already the newest version (1:2.1.5-2).
libgl1-mesa-dev is already the newest version (22.3.6-1+deb12u1).
libglew-dev is already the newest version (2.2.0-4+b1).
libopenal-dev is already the newest version (1:1.19.1-2).
libmad0-dev is already the newest version (0.15.1b-10.1+b1).
uuid-dev is already the newest version (2.38.1-5+deb12u1).
catch2 is already the newest version (2.13.10-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root:/opt/endless-sky/endless-sky-0.10.9 # cmake --preset linux
Preset CMake variables:

  CMAKE_COLOR_DIAGNOSTICS="ON"
  CMAKE_EXPORT_COMPILE_COMMANDS="ON"
  CMAKE_INSTALL_PREFIX:PATH="/opt/endless-sky/endless-sky-0.10.9/install/linux"
  VCPKG_TARGET_TRIPLET="x64-linux-dynamic"

-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.13") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.39") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Found GLEW: /usr/include (found version "2.2.0") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/endless-sky/endless-sky-0.10.9/build/linux

root:/opt/endless-sky/endless-sky-0.10.9 # cmake --build --preset linux-release
[168/212] Building CXX object tests/CMakeFiles/EndlessSkyTests.dir/Release/unit/src/comparators/test_byGivenOrder.cpp.o
FAILED: tests/CMakeFiles/EndlessSkyTests.dir/Release/unit/src/comparators/test_byGivenOrder.cpp.o 
/usr/bin/c++ -DCMAKE_INTDIR=\"Release\" -I/opt/endless-sky/endless-sky-0.10.9/tests/unit/include -isystem /usr/include/SDL2 -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -fdiagnostics-color=always -Wall -pedantic-errors -Wold-style-cast -fno-rtti -g -fsanitize=address,undefined,pointer-compare,pointer-subtract,unreachable,builtin,integer-divide-by-zero,vla-bound,null,return,signed-integer-overflow,bounds,alignment,bool,enum,pointer-overflow -fno-omit-frame-pointer -fsanitize=leak,vptr -std=c++20 -MD -MT tests/CMakeFiles/EndlessSkyTests.dir/Release/unit/src/comparators/test_byGivenOrder.cpp.o -MF tests/CMakeFiles/EndlessSkyTests.dir/Release/unit/src/comparators/test_byGivenOrder.cpp.o.d -o tests/CMakeFiles/EndlessSkyTests.dir/Release/unit/src/comparators/test_byGivenOrder.cpp.o -c /opt/endless-sky/endless-sky-0.10.9/tests/unit/src/comparators/test_byGivenOrder.cpp
In file included from /opt/endless-sky/endless-sky-0.10.9/tests/unit/src/comparators/test_byGivenOrder.cpp:16:
/opt/endless-sky/endless-sky-0.10.9/tests/unit/include/es-test.hpp:28:10: fatal error: catch2/catch_all.hpp: No such file or directory
   28 | #include <catch2/catch_all.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[177/212] Building CXX object source/CMakeFiles/EndlessSkyLib.dir/Release/test/Test.cpp.o
ninja: build stopped: subcommand failed.
root:/opt/endless-sky/endless-sky-0.10.9 #

**Comment by tibetiroka** [comment]
You generally don't need to build the tests manually. You can get the correct catch2 version from vcpkg if it isn't available in your distro (but you don't need it if you only want to build the game).

**Comment by TomGoodIdea** [comment]
> you don't need it if you only want to build the game

you can build the game without the tests?

**Comment by zjdev** [comment]
I phrased that poorly.  Please read 

"Unsure if I should be building tests at all, not building debug target" 

as 

"Unsure why the tests are being built at all, I am not building the debug target."

**Comment by tibetiroka** [comment]
Ah yes, it's configured to build the tests as well out of the box. Can you try running
```bash
cmake --build build --preset linux-release --target EndlessSky
```
to build the game?

**Comment by zjdev** [comment]
Thank you!  On my system "--build" doesn't take an argument.  But this works well:

cmake --build --preset linux-release --target EndlessSky

**Comment by TomGoodIdea** [comment]
We should add this to the build instructions.
