### ISSUE TITLE
"Remnant: Tech Retrieval" ignores prior Taely meeting

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have completed "Remnant: Face to Maw 2", your "has met taely" counter goes up. However, there's no check in "Remnant: Tech Retrieval" for this case.

I got the Retrieval mission immediately after completing Maw 2, and Taely introduced herself as a stranger twice.

### Steps to Reproduce

1. Finish Maw 2 and get introduced to Taely.
2. Leave and land on Viminal (might need to land elsewhere in between).
3. Taely introduces herself all over again.

### Expected Behavior

Just like Maw 2, Retrieval should account for prior Taely meetings using the `has "remnant met taely"` conditional at this point: https://github.com/endless-sky/endless-sky/blob/4db7110868157c1f98821e908250e7bcaf43ac2f/data/remnant/remnant%201%20introduction.txt#L1639

### Operating System

W10

### Game Source

GitHub Releases

### Game Version

0.10.8

### Additional Information

I would have opened a PR myself, since it is such a small patch, but I'm not confident that I wouldn't screw up the conditional somehow.

**Comment by TheGiraffe3** [comment]
#8853 should fix this.

**Comment by TheGiraffe3** [comment]
It hasn't been merged yet, so you could maybe keep this issue open.
