### ISSUE TITLE
Dumping cargo as escape mechanic

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10597]
### Problem Description

Merchant cargo ships often dump their cargo and escape the system. It's hard to tell whether or not this affects the behaviour of pirate ships attacking them, but we can assume an in-lore explanation where they ignore the ship in favour of the dumped cargo. Otherwise dumping the cargo would be a dumb, pointless move.

The player has the ability to dump cargo, but as of now, the pirates just go "Hah boys! Looks like he shat himself!" and continue attacking you like nothing happened.

This is strange because the game has an explicit mechanic where your cargo raises the piracy threat. For pirates to just ignore that contradicts the lore.

### Related Issue Links

#5317

### Desired Solution

When you use the 'Dump cargo' button, pirates should stop attacking for a few seconds to collect it.

Ideas:
- There can be an element of randomness to this: only some of the attacking pirates switch to cargo hunting, or maybe there's a single RNG roll upon dumping that decides whether all the pirates attacking you will pause or not.
- The more cargo you have, the bigger the escape window could be (pirates take longer to collect it).
- The more valuable your cargo, the higher the chance that pirates switch their attentions.
- When you selectively jettison cargo, that works too.
- If the number of cargo items are less than the number of attacking pirates, only an equal number of attackers are distracted.

### Alternative Approaches

If you have cargo in your ship, the game could automatically assign a threshold where if your ship is moments away from being disabled, it automatically dumps its cargo in order to create an escape window.

Maybe this happens with mission cargo too. You fail the mission, but at least you survive.

The cargo could be dumped over time instead of all at once: this might work better in some scenarios in terms of creating an escape window by forcing pirates to slow down repeatedly to collect it, instead of in one swooping arc.

**Comment by Anarchist2** [comment]
All pirate fleet already have the `harvests` personality; so long as their ship still has cargo space, they will prioritise picking up flotsam over attacking another ship.

See the following clip: my Argosy is being attacked by several pirate ships. However, when I drop 50 tons of luxury goods and thrust away, the pirate ships are distracted and follow my dropped cargo, allowing me to jump away.

https://github.com/user-attachments/assets/9c7ed7c1-9d66-4088-a756-9a3d57a46116
