### ISSUE TITLE
Travel to Mutiny: Syndicate is not hostile

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#106]
I'm currently on the mission "Travel to Mutiny". According to the mission description, Syndicate should be hostile towards me and should not let me land on planets. However, I can land on the Syndicate planets without bribing and they are not attacking me. However, they attack the Navy Intelligence ship, which I'm escorting.

**Comment by schlamar** [comment]
They didn't attack after the attack on Nimbus, too.

**Comment by schlamar** [comment]
Actually, the Syndicate ships are following my flagship. Pretty weird.

**Comment by endless-sky** [comment]
Can you check what your reputation with the Syndicate is? (Near the top of your saved game file.) It's possible that if you did a *ton* of pirate hunting in between the first fight with them and the subsequent missions, that would boost your reputation with them high enough that they don't attack.

**Comment by endless-sky** [comment]
Also, were they hostile toward you in the initial mission with the defector on New Tibet?

**Comment by schlamar** [comment]
Syndicate 2495.25
    Pirate -6529.52

Would this make sense?

Or could this be the same issue than #107? 

For some time, the Syndicate stars were painted yellow in the map, but then they were suddenly blue again... 

Uploaded two save games around that time, maybe that helps: https://gist.github.com/schlamar/046ef36bfc657049b246

**Comment by endless-sky** [comment]
Yeah, that actually is the same bug as #107; the reputation change is in an "on accept" action that was not getting triggered. So, my fix for #107 should handle this, too.

**Comment by endless-sky** [comment]
This should be fixed in release 0.8.4.
