### ISSUE TITLE
Unique/Minerals wrongly show "(not sold here)" instead of "in stock: [number]"

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This behaviour doesn't match up with what is shown for the rest of the categories. Normally, if you sell items to an outfitter which are not sold there, it shows "in stock: [number]", until you repurchase all of them, after which it shows either "installed:[number] + (not sold here)", or "in cargo/storage: [number]".

For unique/minerals, it just shows "(not sold here)", regardless of the fact that these items remain in stock and can be repurchased as usual until the stock runs out.

### Steps to Reproduce

1. Sell one or more minerals/unique items at an outfitter until there's no more of that item installed/in cargo.
2. See the "(not sold here)" label. Now there's no indication of how many items are there.
3. Try to buy back all the items, and succeed.

### Expected Behavior

These categories should behave exactly like the other ones, except there's no installation status for minerals, and certain unique items.

### Operating System

W10

### Game Source

GitHub Releases

### Game Version

0.10.8

**Comment by warp-core** [comment]
Are you seeing this with any "Unique" items other than "Void Sprite Parts"?

**Comment by esksp** [comment]
I _did_ see it with mined asteroid minerals. Once sold, they appear with a mention they aren't for sale there (duh).
