### ISSUE TITLE
Stopped ships sometimes drift slightly (tiny bug)

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes, despite having come to a stop, a ship can continue to _very_ slowly drift. This is more obvious when fast-forward is turned on.

I haven't been able to reliably reproduce this yet. But crazing around and repeatedly stopping a few times is enough to encounter this bug.

When drifting this way, Pressing Shift+Down again does nothing, because the game considers the ship stopped. To break out of it, you simply move, and then stop again.

Edit: Seems like it only happens in fast-forward mode. Something to do with frames, maybe?

### Steps to Reproduce

(Not figured out yet)

### Expected Behavior

Ships should never drift when they are intended to stop completely.

### Operating System

W10

### Game Source

GitHub Releases

### Game Version

0.10.8

**Comment by esksp** [comment]
Yes, I have noticed that too, especially for escorts: While stopping for some time over a star to scoop some fuel, especially the escort(s) (but sometimes the flagship too) seem(s) to drift randomly around, not very far but still very noticeably in fast forward. And hitting Shift+down does indeed not stop them. Just FYI.

**Comment by TheGiraffe3** [comment]
You can also press H.
