### ISSUE TITLE
`energy capacity` attribute description tweak + stat exposure

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Look at a Warder Anti-Missile. It has an `energy capacity` of 50. When you view the tooltip, it says "The amount of energy this **_ship_** can store".

For batteries and generators, this sort of makes sense in context, but not for a weapon.

### Steps to Reproduce

N/A

### Expected Behavior

The simplest solution would be to replace "ship" with "outfit" in that tooltip.

However, there are ships like the Tern which have an inbuilt energy capacity (how?). For these, the tooltip makes perfect sense.

So, maybe the tooltip should say both, "outfit or ship".

And then, this attribute must be exposed when viewing such ships in the shipyard, or on the map screen ship list. It is quite confusing to remove all energy storage from a ship and still somehow end up with a positive number. If you're unaware of inbuilt storage, it leads to checking and rechecking the installed outfits to find out the culprit. And the answer isn't found until you dig into the game files.

### Operating System

W10

### Game Source

GitHub Releases

### Game Version

0.10.8

**Comment by TomGoodIdea** [comment]
related: #4215

**Comment by esksp** [comment]
> it says "The amount of energy this ship can store"

Maybe "This outfit increases your ship's energy capacity by X"? (The key word is "increases")
For ships you need a _clear_ mention that a given ship has in-built energy storage (or shield regeneration, or repair, and so on) is indeed needed. After all it can be a selling point...

> inbuilt energy capacity (how?)

Built-in batteries, somewhere in the structure?
I don't see the issue, all those in-built perks sound like cars' standard/optional equipment. One model can have some equipment built-in as standard, for others it's only a paying (potentially aftermarket) option.

And built-in stuff isn't removable, think car's navigation system for a very good example: Even if it's substandard or old and outdated, you're stuck with it, it will keep taking up space in your car even if you don't (can't) use it anymore.

**Comment by warp-core** [comment]
> However, there are ships like the Tern which have an inbuilt energy capacity (how?). For these, the tooltip makes perfect sense.

As far as I can tell, this tooltip will not be shown in relation to this built in energy capacity and so does not need to account for it.

> And then, this attribute must be exposed when viewing such ships in the shipyard, or on the map screen ship list. It is quite confusing to remove all energy storage from a ship and still somehow end up with a positive number. If you're unaware of inbuilt storage, it leads to checking and rechecking the installed outfits to find out the culprit. And the answer isn't found until you dig into the game files.

There are existing issues about this topic, like the one TomGoodIdea linked.

**Comment by Quantumshark** [comment]
> Look at a Warder Anti-Missile. It has an energy capacity of 50. When you view the tooltip, it says "The amount of energy this ship can store".

> For batteries and generators, this sort of makes sense in context, but not for a weapon.

In what way does it not make sense? In-game, all of these numbers are simply added together, and become the energy capacity of the ship. It's _not_ the case that this stored energy on the Warder can only be used by the Warder, for example - it's stored energy on the ship, just like it is with any other outfit that provides `energy capacity`, or with `energy capacity` that's inherent to the ship.

**Comment by TheGiraffe3** [comment]
What about "The amount of energy this outfit adds to the ship's storage?"

**Comment by esksp** [comment]
Two days ago, further up, I suggested: "This outfit increases your ship's energy capacity by X"...  :-)
Make it "This outfit increases your ship's energy _storage_ capacity by X".

**Comment by TheGiraffe3** [comment]
"The amount of energy this outfit adds."?

**Comment by TheGiraffe3** [comment]
> Two days ago, further up, I suggested: "This outfit increases your ship's energy capacity by X"... :-)
> Make it "This outfit increases your ship's energy _storage_ capacity by X".

Oh, just saw this.
But I'm not sure you know the context?
There is `energy capacity [some number]`. When you hover your mouse over it, the tooltip pops up.
However, the tooltip is generic, and doesn't know what the value of the attribute it's for is.
So adding "X" wouldn't work. Though maybe "This outfit increases your ship's energy storage capacity by this amount."?

**Comment by esksp** [comment]
> "The amount of energy this outfit adds."?

Yes, "adds to your ship's energy capacity" if you prefer, it's the same thing.

> However, the tooltip is generic, and doesn't know what the value of the attribute it's for is.

I see.
Well, just drop the "by X" then, no? Just "This outfit adds to your ship's energy storage capacity" (or some such).
