### ISSUE TITLE
Kamikazes: Shouldn't damaged or absurdly weaker enemies flee at some point?

### ISSUE THREAD

**Issue by esksp** [endless-sky/endless-sky#10647]
### Problem Description

In one of my games I own by now a couple heavy warships, heavily armed, optimized by alien technology (found about all the aliens out there and earned their licenses). To make it short, nothing in human space could make me even worry.
And still the small pirate interceptors keep attacking me on sight, again and again, and I destroy them instantly, while they're closing in, one after the other. It's aggravating. It's boring.

Shouldn't absurdly weaker enemies avoid you, flee, or at least stop attacking you and try to save their hides? Are they all religious fanatics? Suicidal madmen?
Yes, I know, the "heroic" personality. But outside of specific cases it is a little silly, especially for pirates, so could we have a less suicidal but still aggressive personality?

### Related Issue Links

#3898

### Desired Solution

A personality which is **just as aggressive as the "heroic"**, but which **will immediately turn and flee if**:
1. Your **combat rating** is off the charts compared to his
2. Your **cumulative firepower** (you+your escorts) is more than 1.5 times his (him+his friends)
3. His **shields** OR **hull** OR **energy** have slipped under 50%

- So there would be cases where when seeing you, the enemies will just make a hasty U-turn and run for the hills: They have decided they're definitely out of their league, and wish to live to tell their grand-children about that encounter (case 1).
- Or where the enemies initially fight, but after you have destroyed a couple of them, the rest suddenly just turns and flees (you have triggered case 2).
- Or a lightly damaged ship flees, but after a while, energy and shields recharged, it turns and attacks again (case 3). BTW, that "fleeing" ship counts towards case 2, its firepower isn't available anymore.

**When fleeing**, enemies would flee to the **outer reaches of the current system** (would need to become `unconstrained` while actively fleeing). This is so you can still try to capture them.
But it won't be easy, because **if you hunt a fleeing ship down and damage it** (further) by firing at them for over 2-3 seconds, **they will try to jump away** from that system. You'll have to be quick.

Such a behavior would give the enemies a more human feeling, less like mosquitoes. 
The drawback is that at some point you will become too powerful for pirates or such to even dare cross your path. But well, at that point you most likely have better things to do than to chase puny pirates for a couple dollars, so you won't miss the incessant buzzing too much... 

The only real **issue** I see is calculating that "firepower". I don't know what's under the hood, so it might or it might not be easy. 

### Alternative Approaches

N/A

**Comment by warp-core** [comment]
How does this differ from the related issue you've linked?

**Comment by esksp** [comment]
First of all, it is TomGoodIdea who pointed me to that issue, I just added his link to the initial post.
I didn't find it myself because it was too old, 6 years old! I assume the game has changed some since then.
But most of all, #3898 sounds more like a _general discussion_ than as a _concrete suggestion for improvement_.

**Comment by warp-core** [comment]
> #3898 sounds more like a _general discussion_ than as a _concrete suggestion for improvement_.

Can these suggestions not be discussed there?

**Comment by esksp** [comment]
> Can these suggestions not be discussed there?

Technically yes, of course... But as I said #3898 lacks clear suggestions for improvement (I could find none, but then again I'm new to this GitHub thing), it also sounds like that issue is in limbo (long forgotten), so I think this new issue here is different enough to have merit.

Of course the ES team is the sole and final judge.
Consider this as my 2 cents worth - There _is_ a problem, apparently I'm not the only one to think so. Now the practical details of GitHub posting are rather irrelevant _as long as the problem is acknowledged_ (i.e. not forgotten).

**Comment by Anarchist2** [comment]
Very rarely do issues come with a fully formed solution at the get-go. After a general complaint is made, there is discussion on what solutions could work, which is eventually refined into a comprehensive solution that is turned into a PR. This process of "general discussion" to "concrete suggestion for improvement" is the standard workflow for a GitHub issue.

Issues don't have some arbitrary expiry date. By default, GitHub sends an email for any new activity on an issue or PR, meaning that leaving a comment on an old issue is enough to bring some attention to it again. Creating a brand-new issue for something that already has one serves only to obfuscate previous discussion, by putting information in several different issues rather than all in one place.

I'm closing this issue in lieu of #3898. Please post the desired solutions from this issue in that thread.
