### ISSUE TITLE
[bug] death benefits don't appear as a message if you withdraw from combat...

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1064]
...(and both parties defend) before capturing the ship.

**Comment by Isaacssv552** [comment]
Does this mean you don't have to pay death benefits or you just aren't notified?

**Comment by LocalGod79** [comment]
not sure - i was already carrying death benefits when i noticed it.

**Comment by LocalGod79** [comment]
and it appears that this bug has also rectified itself overnight...
