### ISSUE TITLE
Ghost and corporeal Dromedaries side by side

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This only happened to me once. Didn't occur on subsequent retries.

I launched from Far Monad with the real Dromedary, and found that the ghost Dromedary was _still_ present right nearby. I immediately reloaded and launched again, and it was gone. ~~No idea why it happened.~~ Figured it out.

### Steps to Reproduce

1. Launch from Arculus. Land on Far Monad when told to.
2. Launch from Far Monad.
3. See ghost.
4. Rinse and repeat.

### Expected Behavior

For a duplicate ghost not to appear? The mission in the file contains just one real ship, so this was probably some weird code interaction.

### Link to save file

[Peter Quill~3020-05-23 - Ghost ship save.txt](https://github.com/user-attachments/files/17445642/Peter.Quill.3020-05-23.-.Ghost.ship.save.txt)

### Operating System

W10

### Game Source

GitHub Releases

### Game Version

0.10.8

**Comment by warp-core** [comment]
Related reports on Discord:
https://discord.com/channels/251118043411775489/536900466655887360/1051717600381513788
https://discord.com/channels/251118043411775489/536900466655887360/1080445225497014272
https://discord.com/channels/251118043411775489/536900466655887360/1251836617249783828

**Comment by TomGoodIdea** [comment]
This may be the same bug that causes the single Gunboat in the FW sensors mission on Hope to be seen departing only once - if you reload the game, it doesn't appear anymore. (I think it was reported somewhere, but I don't remember where)

**Comment by warp-core** [comment]
Do you have a save file for this?

**Comment by warp-core** [comment]
Unedited would be best. If you don't want to include the pilot name or any ship names, removing those is fine.

**Comment by warp-core** [comment]
Thanks

**Comment by tibetiroka** [comment]
Resolved in #10653.
