### ISSUE TITLE
[bug] Winter's landscape is missing

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1065]
free worlds campaign complete, only my own mod running (which doesn't touch the system)

the only modification in my save file to this system is the founding of the university.  i can find no reason for this behaviour.
![screen shot 2016-05-09 at 11 50 43 pm](https://cloud.githubusercontent.com/assets/16969517/15135136/f1239e5e-1640-11e6-8288-bc6fa4db91c0.png)

**Comment by jafdy** [comment]
Check if the landscape is still defined in `map` and that the image is still in the `image` file.

**Comment by LocalGod79** [comment]
thanks; not my first rodeo - that one is kind of obvious, isn't it?

**Comment by LocalGod79** [comment]
http://steamcommunity.com/app/404410/discussions/1/358415738185766392/

**Comment by endless-sky** [comment]
Landscape images are loaded and freed on the fly, because they take up 1 MB of VRAM apiece and there are over 200 of them. Apparently it's possible in some rare cases for the image to not load, but I haven't been able to track down why it happens.

**Comment by endless-sky** [comment]
I think the recent change to make sure the images are uploaded to the GPU as soon as they are available, instead of only doing the upload once you land, should fix this (5d9c33e). The issue was occurring when someone traveled a very large distance without landing and filled up the queue of landscape images to load.

**Comment by KiLEdEnNis** [comment]
@endless-sky I have heard of other issues after extended travel without landing (game crashes), so that's probably the cause
can't remember the issue number, but it's around 1350-1400

**Comment by Amazinite** [comment]
Hey, that's pretty good.
![40307fe98e0b4ce193fc52a9c593cd2e](https://cloud.githubusercontent.com/assets/17688683/19622242/548a5f8c-9873-11e6-81d8-cfe0362294fc.png)

**Comment by LocalGod79** [comment]
can you give us some details about this?  more "loiter", jumping from system to system before actually landing?

**Comment by Amazinite** [comment]
I went from Albireo to Algorel with no stops, using a high turn speed + scram drive ship. I'd been doing passenger missions for some time, doing similar long distance jumps, and this is the first time it's happened in a while.
