### ISSUE TITLE
[question] Should an Arfecta be capturable?

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1066]
Title. They are indeed capturable, but it seems like they shouldn't be. I took on Luna, Earth, and Mars, with only the Arfecta, and won. Seems rather imbalanced.

Edit: they're also easily capturable, if you can disable them.
Edit: you can probably conquer all of human space with a single one.

**Comment by jafdy** [comment]
Yes but how did you do it? An Arfecta has more than 3000 defense.

**Comment by toilethinges** [comment]
@jafdy - With a Bactrian (245 crew, and 245 frags - nope, not even nerve gas) I had 7.5% chance, and got lucky. By this I meant "should it be possible to disable it," because, once again, I could conquer all of human space with a single one. I thought originally that it wasn't possible, but it took quite a few Skylances and Disruptors before it was disabled..

**Comment by mdsmestad** [comment]
@toilethinges And this is why skylances should not be so easy to get. You can do junk like that.

**Comment by Bladewood** [comment]
My fleet has 128 skylances. The Arfecta was downed in seconds.

**Comment by Isaacssv552** [comment]
The Arfecta is in the same boat as the Quarg, extremely hard to capture, but not impossible.

**Comment by LocalGod79** [comment]
i think M.Z. is quietly smirking at all the artificial content he's created for all the cap'-happy steamers...

**Comment by Isaacssv552** [comment]
Right now the only neverdisable ships are living and thus unplunderable for lore reasons. It doesn't seem like we'll see the more powerful ships become uncapturable purely to limit the players potential power. I think we are more likely to see better boarding defense and more Arfecta-esqe responses to farming.

**Comment by endless-sky** [comment]
Given that right now you can only collect one of them, and that doing so requires that you already have an absurd fleet, I don't think there's a problem with it being capturable.

**Comment by Bladewood** [comment]
I now have 3 Arfectas in my fleet.

**Comment by toilethinges** [comment]
I was wondering if this would come back up...
