### ISSUE TITLE
HUD texture glitch when in hyperspace

### ISSUE THREAD

**Issue by Noobly20932** [endless-sky/endless-sky#1067]
If you hold down 'J' until your whole fleet is ready to jump to another system, normally, the icons in the bottom-left corner that show the stats of your fleet turn green, then turn white as soon as you let go of 'J'. However, for some reason, the Freighter class' icon stays green until your fleet leaves hyperspace.
![a](https://cloud.githubusercontent.com/assets/19326057/15214252/ab861232-1811-11e6-8d82-5f98b17494f8.png)
![b](https://cloud.githubusercontent.com/assets/19326057/15214253/ab8cf43a-1811-11e6-9494-7f6c602ca45c.png)
![c](https://cloud.githubusercontent.com/assets/19326057/15214254/ab8dfc68-1811-11e6-808d-92a1154490c8.png)
![d](https://cloud.githubusercontent.com/assets/19326057/15214255/ab8ef550-1811-11e6-8f9e-81a335be690e.png)

**Comment by Gkramme** [comment]
This happens with all ships that have scam drives

**Comment by Noobly20932** [comment]
Scam drives? What are those?

**Comment by lehgogh** [comment]
I think he meant "scram drives". These use more fuel, but allow you to jump while moving faster.

**Comment by Gkramme** [comment]
Yup. Sorry, I mispelled it.

**Comment by Amazinite** [comment]
They scam you by slowly draining your money instead of using fuel.

**Comment by jafdy** [comment]
The long way of putting it . . . Scram Drives allow for any velocity along the Jump vector so as all Hyperspace jumps are is a very fast move along the Jump vector, therefor icons stay green. Also most Freighters come with Scram Drives as standard.

**Comment by Bladewood** [comment]
The same thing happens with jump drives for some reason :|

**Comment by endless-sky** [comment]
Fixed in 660b6d8.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
