### ISSUE TITLE
Feature: Expanded Font support

### ISSUE THREAD

**Issue by SomeTroglodyte** [endless-sky/endless-sky#10673]
### Problem Description

The way text drawing seems implemented now, all text is limited to 98 glyphs containing Lating letters and some punctuation and thus any accent- and diacritic-free western language. Which mostly only leaves Engrish.

Expanding the Glyph set significantly would provoke problems with the ~kerning~ advances table, which is (#glyphs)^2*4 bytes. Imagine having a glyph set suitable for japanese - memory may not yet become relevant, but loading time might since advance calculation is done by pixel scanning.

Codepoint-to-glyph mapping seems to be strictly by position in the font png, "sparsely" populating a few noncontiguous sections of the unicode space with glyphs would need a lot more code.

I suppose there's no i10n for ES nor plans, but if there ever were...

### Related Issue Links

Found none

### Desired Solution

The simplest idea I could come up with, that could cover at least some of the missing western script requirements, would be adding a very limited (<< 20) set of glyphs that all function as diacritics, meaning their advance vs any previous glyph is zero, they will always be painted right over the previous one. That could cover a lot - e.g. áéíóúàèìòùâêîôûäëïöüćĉĝĵńŝŵŷź with just 4 extra glyphs. Game text would need to be "mapped" - not "Chasseur de têtes" but "Chasseur de te ̂ tes" - whether using U+0302 for this combining mark or any other arbitrary code point does not really matter.

### Alternative Approaches

* Data tables might define codepoint to glyph mapping
* Data tables might be used for kerning instead of pixel scanning
* Migrate from a static font png to having the OS render glyphs into textures on demand like Unciv does :zany_face:

**Comment by Koranir** [comment]
We have plans to implement full unicode/i18n support to ES, it's just a pretty hard thing to do in general. There's been prior PRs that all had their own issues, and I've been working on a full harfbuzz/freetype text stack myself.

**Comment by Koranir** [comment]
See #8572 for more details
