### ISSUE TITLE
[bug] graphics files pushing 256MB VRAM limit (previously; 0.9.0 effects question)

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1069]
a couple of steam users have mentioned that, especially when using jump drives, they are experiencing slowdown (greater than in 0.8.11).  otherwise, effects in general (korath space is a nightmare for these users) appear to be bogging their systems.

i'll admit that they are both using dated hardware (one using a (edit:)10 year-old athlon 64-bit processor, the other using a 4 year-old intel i3 mobile chip) - at the very least we're finding out the base system requirements for E.S. as it stands are, and what sorts of things are making them so.

http://steamcommunity.com/app/404410/discussions/0/364041517006227596/?tscn=1463103312

**Comment by endless-sky** [comment]
One possible explanation is that 0.9.0 contains just enough new sprites to put the total graphics memory usage of the game (not counting the high dpi plugin) above 256 MB, which is a common size of the reserved graphics RAM for older video cards as well as for integrated graphics with some settings. For example, on my own computer, which is a 4-year-old desktop i3-2100:

```
	Region 0: Memory at fe000000 (64-bit, non-prefetchable) [size=4M]
	Region 2: Memory at c0000000 (64-bit, prefetchable) [size=256M]
```

Currently the game limits graphics memory use by only loading landscapes as needed and keeping only a small number of them in memory at once, but for all other graphics it loads them when it starts up. That makes things a lot simple, and avoids visual glitches, but would mean long delays if the video card has to transfer images between video RAM and main RAM.

On other systems, it won't make a difference; for example, my computer runs fine even with the high dpi plugin (over 600 MB of video memory used) even though it supposedly only has 256 MB reserved. For someone having trouble with integrated graphics, it's possible their BIOS would let them increase the memory allocation.

In general, as long as the game's collection of graphics is doubling in size no more than once every two years, it should at least keep pace with Moore's law and avoid inflicting this problem on too many people. :) These days very few video cards are still for sale that have less than 1 GB of graphics memory, and the high-end ones go as high as 12 GB.

**Comment by jafdy** [comment]
Moore's law broke. We started getting field leak. Also high end graphics memory can go up to 16GB.

**Comment by LocalGod79** [comment]
@Wrzlprnft suggested a "low-dpi-plugin" on the Steam thread, which i think is a great idea - if you wanted to support computers from the actual era of E.V....

**Comment by Wrzlprnft** [comment]
Oh hey, i did. It doesn't have to be some hardcoded picture-size-stuff like the high-dpi-plugin, but just a set of simpler effects, less explosions and simpler jump drive animations.

**Comment by LocalGod79** [comment]
i think, though, that a 'hardcoded picture-size-stuff solution' is exactly what's indicated - i think it would be the easiest to implement, too.

**Comment by endless-sky** [comment]
Here's the game's current memory usage for sprites, broken down by category:

 | MB | percent
--- | --- | ---
_menu | 1.02 | 0.5%
asteroid | 9.82 | 5.3%
effect | 19.84 | 10.6%
font | 0.80 | 0.4%
icon | 0.04 | 0.0%
label | 2.08 | 1.1%
land | 19.78 | 9.6%
outfit | 12.54 | 6.7%
planet | 21.37 | 11.5%
projectile | 4.13 | 2.2%
scene | 10.38 | 5.6%
ship | 18.61 | 10.0%
star | 38.57 | 20.7%
ui | 46.32 | 24.8%
total | 205.30 | 

When you add memory for buffers, etc. and for whatever else the OS is doing, that's when you approach the 256 MB limit on some computers (2.3% of Steam users, according to their survey). If that is indeed what is causing the slowdown for them, they could try removing the "nova+.jpg" image in the star folder to reduce VRAM usage by almost 20%, which might get it under to 256 MB threshold.

**Comment by lehgogh** [comment]
Perhaps a toggle in the settings to enable/disable special effects (nova+, for example)? This could be automatically set depending on your hardware, but still be changeable for other users.

**Comment by LocalGod79** [comment]
M.Z. made small sprites to replace the two largest ones, that for the moment, solves the problem.  i suspect that in the future, some additional assets may get colour stripped.
http://endless-sky.github.io/low-dpi.zip

**Comment by LocalGod79** [comment]
ftr; i've embarked on colour stripping otherwise grey assets in a new fork.  it's only a few KB per image, but i have a feeling i might even pile up a MB or two...

**Comment by endless-sky** [comment]
The video card stores all sprites as RGBA, so the only advantage to color stripping would be for disk space - which is not really a problem at present.

**Comment by LocalGod79** [comment]
this problem is not going to go away, as the game grows.

i'm afraid that going forward, those players are going to be further pressed for new hardware.

@Wrzlprnft for the future of the "low-dpi" plugin, perhaps outfits/weapons/engines/ships.txt that reference the regular sprites for the Marauders (trimming ships somewhat), and placeholder outfit sprites (i.e. - the fuel cells all look alike; batteries, atomic engines, ion engines, etc.)

planets look like a good place that one could trim, too (perhaps only one of each variation - this planet is hot, this planet is icy, this planet is like earth, etc.).

@endless-sky , the UI is glaringly the largest consumer of these resources - i wonder if loading these, or some of these, "only as necessary" might be a good idea (since the player is most likely going into a "paused" state, if not already in one, and a "hiccup" might be less noticeable.

**Comment by endless-sky** [comment]
The second biggest sprite in the game is the galaxy backdrop - that accounts for 33.4 of the 46.3 MB of VRAM used by "UI" images. The supernova is slightly bigger, at 34.3 MB.

With the low DPI plugin installed, memory use becomes:

 | MB | percent
---- | ---- | ----
_menu | 1.02 | 0.7%
asteroid | 9.82 | 7.1%
effect | 19.84 | 14.4%
font | 0.80 | 0.6%
icon | 0.04 | 0.0%
label | 2.08 | 1.5%
land | 19.78 | 14.4%
outfit | 12.54 | 9.1%
planet | 21.37 | 15.5%
projectile | 4.13 | 3.0%
scene | 10.38 | 7.5%
ship | 18.61 | 13.5%
star | 4.24 | 3.1%
ui | 12.94 | 9.4%
total | 137.59 | 

So, the UI (aside from the galaxy image) is actually not that big of a problem.

**Comment by LocalGod79** [comment]
wow - that gives quite a buffer, for a while - possibly until 1.0.0 release...

**Comment by endless-sky** [comment]
In terms of disk usage, the game grew from 38.4 MB of disk space in November 2015 to 55.4 MB in April 2016, as a result of adding two new species, the Wanderers and the Korath, along with some new human ships. If new graphics keep getting added at that rate the game could hit the 512 MB limit about 16 months from now.

Realistically though, until the Wanderer story it done I'll be more focused on story than on new graphics, so the huge jump in size between 0.8.11 and 0.9.0 is probably an outlier. Unless a ton of new people start contributing alien species, it could be 2-3 years before the vanilla game hits the 512 MB limit, and meanwhile the market share for 256 MB is doing this:

![256](https://cloud.githubusercontent.com/assets/11450262/15345523/d1facb68-1c7d-11e6-8564-0449c5f82aa9.png)

That's an exponential curve, so it will take a while to reach zero, but 2 years from now it will be well below 1%. And, we don't even know if everyone with 256 MB has this problem, or only particular people whose drivers are making bad decisions about VRAM usage.
