### ISSUE TITLE
Not getting jump drive

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#107]
On the planet to get the jump drive, my hyper drive is removed, but I'm not getting any jump drive.

**Comment by schlamar** [comment]
This is on current master, on 0.8.3 it seems to work.

**Comment by endless-sky** [comment]
Good catch! I switched to having unique missions appear at the start of the mission list, but when you accept a mission I was always calling the "accept" action on the mission at the end of the list. Should be fixed in commit 072b81e.

**Comment by endless-sky** [comment]
This should be working properly now in release 0.8.4.

**Comment by reagan166** [comment]
question is where TO GET a jump drive?

**Comment by Wrzlprnft** [comment]
this is a question for the forums. though, the answer is: play the story or try and loot alien ships (which will get mad at you for that)

**Comment by reagan166** [comment]
Sorry but thanks
