### ISSUE TITLE
Feature Requests: Store Credits in the Bank, Asteroid Mining, and Colonizing

### ISSUE THREAD

**Issue by Noobly20932** [endless-sky/endless-sky#1070]
To make banks more realistic and useful, you can store money inside them, where every month compounding interest is added to your account. Also, if you owe some money for something, i.e. paying a dead crew members' families, it will pull as much money from your account as possible before charging daily payments, as normal. It would also be nice to mine asteroids or planets for ores that you can sell at a profit, or the ability to scan planets, start colonies on them, and terraform them.

**Comment by Amazinite** [comment]
Asteroid mining us already on its way.

**Comment by Isaacssv552** [comment]
If I put my 17B in the bank at 0.5% interest per day I would be making over 80M a day. Even if it was cut to 0.05% per day I would still make 8M a day. I support this addition :)

**Comment by toilethinges** [comment]
Isn't all money in the bank?

**Comment by jafdy** [comment]
We already have a bad case of it's too easy to get money. Interest would just make it worse.

**Comment by Isaacssv552** [comment]
You can never have too much moneys. Money! My Ship! Money! :)

On a more serious note, being able to give loans and buy stock would be cool, especially if we could buy out the Syndicate and perform a hostile corporate takeover, but it seems like something to add post 1.0.0, if ever. It might tie into a Syndicate storyline though.

**Comment by endless-sky** [comment]
The only reason to add new features that make the game more complicated is if they would make the player's behavior more varied or interesting. Charging interest would just add one more way for rich players to get richer while not changing the early game at all (except perhaps by making players want to hoard money instead of spending it on their ships). So, I don't think it would make the game better, and adding it just because you want an additional income stream is not a good enough reason.

**Comment by Isaacssv552** [comment]
It would be more interesting if you could directly finance other Captain's ships, outfits, and trade goods, and balance the possibility of their death or bankruptcy with the potential profit. It would be especially interesting if you could encounter the Captain(s) while traveling and accept alternate methods of payment, such as a captured outfit.

**Comment by LocalGod79** [comment]
it sounds like you're trying to make Endless Sky into an empire game, which i don't think was ever the intention.  these sorts of features were not available in this game's inspiration, either - because that isn't the style of game this is...

there are plenty of "empire style" games out there to play - this one is pretty unique.

**Comment by Isaacssv552** [comment]
I was proposing the addition of missions/jobs themed around giving another pilot a loan to help them buy that new ship/load of trade goods/whatever. Less "build 100 ships and invade the Korath," more "help fund an expedition of other independent treasure seekers to loot Korath space". The idea is to give more interaction with other independent captains.

**Comment by Noobly20932** [comment]
There are already missions where you learn how to terraform, and it would be cool if you could use that knowledge to terraform inhospitable planets and sponsor colony growth on them. As you would be able to collect taxes from the colonists, this would be better in the late-game, otherwise it would discourage doing missions in the early-game.
   If you could put money in the bank, and gather interest like 0.05% every year, then it wouldn't affect the early game all that much, as you wouldn't have enough to make serious profit. As for the later game, you could put several million credits in and leave it for several years. However, I do understand that some people would use this function to attempt to break the system by achieving such an amount of credits that the game registers it as negative or whatever, however, this can be fixed by changing the interest based on how much you have, i.e., if you put 1 Megacredit in, interest would be 0.05%, while if you put 10 Gigacredits in, interest would be >0.0000000001%, or more simply, 0%. Being able to invest in stocks would be another way to make quick cash, while adding some risk. You would need to posses a license to use the galactic stock exchange, though, and it would only be obtainable in the late-game.
   It would also be cool if you could purchase a mining ship that you could have land on any uninhabited planet and send out several drillers (up to 5 per mining ship) to dig for various resources, like iron, titanium, gold, uranium, plutonium, cinnibar, tin, diamond, galactic jade (or another extremely rare mineral). You could also get special drills that could harvest H-2, H-3, and He-3 from gas planets. These minerals would be sold in a similar fashion to how you sell most resources, at the Traders Depot. Minerals like these would sell for more at rich, industrial worlds than at the poor, agricultural worlds.

**Comment by raymoo** [comment]
This might already be the case, but storing credits as arbitrary precision integers would be enough to prevent overflow. To calculate interest, you could just use the integer division provided by the library (libgmp?). E.g. for 0.05% interest rate, divide by 2000. In general, any rational interest rate ```m/n``` would work, by multiplying by ```m``` then dividing by ```n```. If I was too lazy to see that 0.05% was 1/2000, for example, I could use 5/10000 instead. So any interest rate that could be represented as a floating point value could be used on integers. The only problem I see is that integer division would round down, but a single credit probably is not a big deal.
