### ISSUE TITLE
Jump Route Gets Erased When Setting New Destination Mid Jump

### ISSUE THREAD

**Issue by tekker2234** [endless-sky/endless-sky#10722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you set a new destination mid jump, the route to the system gets cleared if certain conditions are met.
I am not entirely sure if there are more scenarios in which this bug happens, but these are the two scenarios where I have been able to consistently replicate the bug:

If the next system that you would jump to is not within the jump range of the starting system.
If the next system that you would jump to along the new route is the system you started the jump in.

This works with both hyperdrive and jump drive, though the hyperdrive appears easier to do.

### Steps to Reproduce

1. Plan first route
2. Jump
3. Open map before jump finishes (before the flash happens and you see the new system)
4. Plan new route matching one of the above criteria.
5. See route get deleted as soon as you click on it. (you can get routes to work by clicking around until one has the next jump outside of the above criteria.)

### Expected Behavior

Route should be recalculated with new destinaton and autopilot should fly new route without interruption (as seen in 0.10.10.)

### Screenshots

All of these are the total routes to replicate the bug, they do not set it off if you just jump with it fully planned out, the first jump in any direction should be done as part of it's own route with the diversion input mid jump. These can also be part of larger routes, neither the first jump nor the diversion mid jump have to be single jump routes.

Route to Muphrid (menkent only also works) with diversion to Vega (also works in reverse, no bug if you try to divert to Ruticulus)
![Screenshot 2024-10-31 224818](https://github.com/user-attachments/assets/d5d755e2-aa72-48ce-8d6f-708f702eb9ad)

Route to Menkent with diversion to Kaus Borealis
![Screenshot 2024-10-31 224631](https://github.com/user-attachments/assets/de7481d2-03c5-418a-8bf9-172bec262a55)

Route to Zeta Aquilae with diversion to Alphecca
![Screenshot 2024-10-31 224838](https://github.com/user-attachments/assets/4121d5f0-a3bc-4177-8244-6f86ac6adac9)

Route to Zeta Aquilae with diversion to Deneb (not mapped)
![Screenshot 2024-10-31 231352](https://github.com/user-attachments/assets/b2f3af08-c3de-4f13-b199-043c5d02bce4)

### Link to save file

[Rennie Drewson.txt](https://github.com/user-attachments/files/17595556/Rennie.Drewson.txt)

Does have some plugins on it but these do not affect the bug, I am merely attatching this rather than a vanilla pilot because it corresponds with my screenshots. This should be easily testable on any save.

### Operating System

Windows 10 Home

### Game Source

Steam

### Game Version

10.10.11-alpha (2256988)

**Comment by tibetiroka** [comment]
Pinging @alextd as they are the most familiar with the new DistanceMap changes.

**Comment by alextd** [comment]
Confirmed that the #6940 merge introduced this problem.

Notably, I think the problem can better be summarized as: the route when you plot a course mid-FTL used to start from your jump destination

**Comment by alextd** [comment]
#10725 should do it. I'm not even gonna check what might've changed in the past 2 years since that feature was branched, but simply enough now, two lines that got removed in the merge seem to be restored for this to work.
