### ISSUE TITLE
Piercing and shields

### ISSUE THREAD

**Issue by OmegaZanicus** [endless-sky/endless-sky#1073]
So I was messing around with piercing attribute, when I noticed that sometimes ships with shields but no hull would remain disabled. 
![thing](https://cloud.githubusercontent.com/assets/18507229/15262010/b4a7fbf6-192d-11e6-8da2-400816e4cf39.PNG)
Edit: I figured out how its happening, just don't know why. I made a pierce weapon that does 2000 damage, and one shotting small enemies will trigger the glitch.

**Comment by endless-sky** [comment]
I can't reproduce this with the latest code. Is it possible your weapon does zero shield damage? If so, there's a known bug in 0.9.0 that might cause something like this.

**Comment by OmegaZanicus** [comment]
300 shield damage, 2000 hull damage.
This is the code for the weapon:

`outfit "Mass Driver Cannon"`

		cost 450000
		category "Guns"
		thumbnail "outfits/massdriver"
		"mass" 30`
		"outfit space" -30
		"weapon capacity" -30
		"gun ports" -1
		"DR capacity" 10

		weapon
			sprite "projectile/thunderhead"
			sound "explosion huge"
			"hit effect" "fire-lance impact"
			ammo "Driver Round"
			"firing energy" 500
			"reload" 1500
			"piercing" .5
			"shield damage" 300
			"hull damage" 2000
			"blast radius" 30
			"lifetime" 1000000000
			"velocity" 200

**Comment by endless-sky** [comment]
I can't reproduce this with the latest code.

**Comment by OmegaZanicus** [comment]
Ok, well I'll keep a look to see if it keeps happening.
