### ISSUE TITLE
Wrong defense fleet assigned to Hai-captured Wanderer planets

### ISSUE THREAD

**Issue by palant** [endless-sky/endless-sky#10737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The events “wanderers: unfettered invasion starts” and “wanderers: more systems lost” assign various Wanderer planets to the unfettered Hai. However, their defense fleet doesn’t change and still belongs to the Wanderers.

https://github.com/endless-sky/endless-sky/blob/c25fda412d72fc6c0b6553d95b3ca4c84fe5314f/data/wanderer/wanderers.txt#L776-L782

https://github.com/endless-sky/endless-sky/blob/c25fda412d72fc6c0b6553d95b3ca4c84fe5314f/data/wanderer/wanderers.txt#L863-L880

### Steps to Reproduce

1. Complete the Wanderer campaign to the point where the Eye opens.
1. Go to the Chy'chra system.
2. Demand tribute.
3. Note how you are attacked by a Wanderer fleet and the Wanderer systems get hostile as you destroy it.

### Expected Behavior

You should be attacked by a Hai fleet

### Operating System

Linux

### Game Source

Other (please describe)

### Game Version

0.10.9

**Comment by TheGiraffe3** [comment]
Could you provide a save file please?
The tribute for Wanderer worlds was added in #10221.

And for the coders (especially warp-core), could it be possible something broke the `tribute clear` keyword?
The PR worked when I was testing it.

**Comment by palant** [comment]
My bad, I got things mixed up. It’s Kort Vek’ki where you can still demand tribute and get attacked by a Wanderer fleet, despite it being under Unfettered control.

The `tribute clear` attribute works correctly in fact. But there is no such attribute for Kort Vek’ki.

**Comment by TheGiraffe3** [comment]
Sorry about that. I've made a pull request (#10738) that should fix this bug.
