### ISSUE TITLE
jumping between Hatysa and Aya'k'k

### ISSUE THREAD

**Issue by spameaterz** [endless-sky/endless-sky#10742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

has existed for a while, but why can we jump in only one direction between Hatysa and Aya'k'k ?  its like the jump radius around Hatysa is large enough to reach Wanderer Space (Aya'k'k) but the jump radius around Aya'k'k is too small to reach Hatysa.

### Steps to Reproduce

1. Go to 'Hatysa'
2. Jumpdrive to Aya'k'k
3. Try to jump back
4. Outside of jump radius  :(

### Expected Behavior

expected to be able to jump back

### Operating System

win7pro

### Game Source

GitHub Releases

### Game Version

0.10.10

**Comment by Hecter94** [comment]
I seem to be able to jump between the two without issue: 

![image](https://github.com/user-attachments/assets/79d9e694-5f5f-4539-bbb4-0115505a78f0)

Are you running any plugins or anything that could be affecting it?

**Comment by spameaterz** [comment]
hadn't considered that...  went back and played musical chairs with the plugins and it seems to be the IRM mod.
