### ISSUE TITLE
[question] 2250

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1076]
In the historical timeline, the year 2250 says that they "explored with long-range scout ships and unmanned drones." If we USED to have long-range, hyperspace capable drones, why do we not anymore?

Forgive me, this probably has no meaning.

**Comment by endless-sky** [comment]
I was seeing it as the same as our exploration of the solar system: right now we do everything with unmanned drones, but if we were able to quickly and safely send humans all through the solar system, I bet the drones would stop being used.

**Comment by toilethinges** [comment]
Although I could see the value of unmanned, hyperspace capable freighter-drones, that makes sense.
