### ISSUE TITLE
Add a clock with time of day display on system screen

### ISSUE THREAD

**Issue by MrPetovan** [endless-sky/endless-sky#10763]
### Problem Description

I figured out pretty early in the game that jumping and landing were moving the date forward one day. This predictable pattern made deadline missions manageable (can I stop mid-way to drop off cargo/pax?). Because of this I assumed that time wasn't passing otherwise, which I discovered wasn't true while I was mining in an asteroid-rich system.

However the in-game clock speed isn't obvious without an actual clock display, leading to anxiety over the completion of tight schedule missions using a slow ship and jump points far from the station/colony.

### Related Issue Links

Looked for "clock" and "time" in every place except Discord.

### Desired Solution

I believe a time display would make the passing time in flight mechanic more obvious, it doesn't have to be a second or even minute-precise display, just showing the current hour would be enough.

![image](https://github.com/user-attachments/assets/e89d32a5-a8f0-4a15-add2-a5142bcaec8b)

### Alternative Approaches

- An actual analog clock?
- A day loading bar/disc?

**Comment by Saugia** [comment]
Days passing are based per jump, not by real-time.

**Comment by warp-core** [comment]
> ### Problem Description
> I figured out pretty early in the game that jumping and landing were moving the date forward one day. This predictable pattern made deadline missions manageable (can I stop mid-way to drop off cargo/pax?). Because of this I assumed that time wasn't passing otherwise, which I discovered wasn't true while I was mining in an asteroid-rich system.

Time does indeed not pass outside of taking off from a planet or jumping from one system to another.
I don't know what happened to you while mining, but it most likely wasn't that a day elapsed, unless we have a bug.

**Comment by MrPetovan** [comment]
Thanks for the consideration! I seem to remember having a deadline mission expiring while in flight, but maybe it was unrelated (like ship carrying cargo/pax exploding).

**Comment by Saugia** [comment]
If you do end up finding a case where time passes while you're mining, please let us know.
