### ISSUE TITLE
Issue: Game allows you to buy outfits even if you have less money than the cost

### ISSUE THREAD

**Issue by exocakes** [endless-sky/endless-sky#10775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Game allows you to buy outfits even if you have less money than the cost making your balance to the negatives and the warning pop up that you have no money only shows up when you try to install something when you don't have the outfit space for it.

### Steps to Reproduce

1. Go to outfitter
2. Buy an expensive outfit that you don't have enough money for
3. See error

### Expected Behavior

Game should pop up a warning that you have insufficient funds

### Screenshots

![image_2024-11-11_191558266](https://github.com/user-attachments/assets/91074e81-d52f-419c-a329-5f1dcd4e4ada)

![image_2024-11-11_191708310](https://github.com/user-attachments/assets/5611f59a-5ec9-4a82-b693-ff510e60b9e2)

![image_2024-11-11_191726460](https://github.com/user-attachments/assets/23c606c8-4f50-49d8-bee2-08295647cb3a)

### Link to save file

[aa a aa a.txt](https://github.com/user-attachments/files/17701570/aa.a.aa.a.txt)

### Operating System

Windows 11

### Game Source

ESLauncher2

### Game Version

version 0.10.11-alpha (6ab8e8f)

### Additional Information

I have a couple disabled plugins but they don't alter money in some way (Better Vanilla Pirates, Cutlass, Early Starts, High DPI, repair-hai-reveal and too.many.asteroids), selling the ship would return all the money + the ship's hull cost. The save is also before I updated to the latest continuous version but it wasn't far apart from before. Updating to it also made me lose access to Hai Start
edit: I got access to Hai Start again after going back to my proper save and landing on a Hai planet

**Comment by Hecter94** [comment]
![image](https://github.com/user-attachments/assets/c771cc31-b82e-4071-8f24-614204938c70)

Can confirm

**Comment by petervdmeer** [comment]
Fixed in #10777
