### ISSUE TITLE
[bug/unconfirmed] Ship is moving erratically...

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1079]
...from AI fleet ships. Not my ship, not escorts, but random escorts.

I'll have a screenshot in a minute.

Game version: 0.9 beta (Steam release)
I do have my own mod installed (was testing burst weapons.)

Also, these ships appear to not be ships that are in this system.

Edit: closing this, can't reproduce.

Edit: Got one! I don't know the cause, it just randomly happened, although it may be caused by my tinkering with weapons. http://steamcommunity.com/sharedfiles/filedetails/?id=684548090

Edit: here's my plug-in, although I haven't updated in a while, so it's slightly outdated. http://steamcommunity.com/app/404410/tradingforum/392183857632240163/

**Comment by Amazinite** [comment]
I've noticed this too, but only in the space that include the ships that @toilethinges mod adds.
![img](https://cloud.githubusercontent.com/assets/17688683/15271023/d21a0956-1a02-11e6-88d7-983cb1848ced.png)
My five ships are the only ones in the system, and they are all unnamed

**Comment by endless-sky** [comment]
Is it possible that the ships have fewer bunks than their required crew? (In particular, could you have added turrets that increase the required crew beyond what they have bunks for?)

**Comment by toilethinges** [comment]
No, @endless-sky, the smallest ship (that isn't a fighter or drone) has 10 bunks, 22 required crew, no turrets, or anything else which increases required crew, and everything else has, at minimum, 25 bunks free after base required crew. I don't see any way that they could possibly do that.

**Comment by endless-sky** [comment]
Well, next time it happens, pull up the info page and take a screen shot of your fleet info.

Also, the beta version of your plugin is reporting several errors:
```
Unrecognized condition expression:
  mission "Assisting Adamas 2"
    to offer
      has credits > 1500000

Unrecognized condition expression:
  mission "Assisting Adamas 2"
    on complete
      conversation
Unrecognized outfit in Blaze ""
Unrecognized outfit in Colossus ""
Unrecognized outfit in Shard ""
Unrecognized outfit in Shard ""
Unrecognized outfit in Shard ""
Unrecognized outfit in Vault ""
Unrecognized outfit in Vitreus ""
Unrecognized outfit in Vitreus ""
Unrecognized outfit in Vitreus ""
```

**Comment by toilethinges** [comment]
@endless-sky, the last several are fixed (the unknown outfits and the conditions), but the first I really don't understand. Is it the `require` tag for credits, or how do you make a mission require credits? Another plugin did it, unless I'm mistaken (looking at you, local god. :})

http://steamcommunity.com/sharedfiles/filedetails/?id=684605624
http://steamcommunity.com/sharedfiles/filedetails/?id=684605578

Also, I must admit that I do have a lot of licenses, most of them from other mods.

**Comment by Isaacssv552** [comment]
I've had this issue when I make a typo in the fleet definition and spawn a non-existent ship. It also happens with Ursa Polaris, but I can't find the problem.

**Comment by endless-sky** [comment]
A "has" check only takes one argument, e.g. `has "credits"`. If you want to check if a condition is greater than some amount, you should write `"credits" > 1500000`.

But, your other problem is that there's no condition named "credits". You should use "net worth" instead. See the [wiki](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#conditions) for a complete list of what conditions exist.

**Comment by endless-sky** [comment]
In this case, it appears that your typo is:

```bash
fleet "Small Adamas"
	...
	variant 10
		"Shard(Needler-0)" 3
```

You need a space before the parentheses in the name.

**Comment by endless-sky** [comment]
I've added an error check for unknown ships in fleet definitions: 4d9adea.

**Comment by toilethinges** [comment]
This is still happening, even after fixing both errors.
