### ISSUE TITLE
Crewspawning

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#10804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ships in bounty missions don't despawn after you land until the bounty deadline is exceeded. This means that it's possible for you to try to capture a ship in hand to hand combat, fail, land on a planet to hire more people, and then try again with a fresh crew. I attempted this to try to avoid getting more bunks but noticed that the crew started respawning after I landed. I know this is an incredibly niche issue but it still seems weird to make that the crew magically respawn after you land.

### Steps to Reproduce

1. Activate a bounty mission
2. Engage H2H with the bounty target after disabling it
3. Choose to defend midway through the battle until combat ends
4. Land on a planet
5. Come back to the disabled ship, board, and observe the respawned crew

### Expected Behavior

The crew in the bounty ship should have respawned after you landed.

### Screenshots

https://youtu.be/YmfuNHfj0Vk
(Github wouldn't let me upload the video file. Here you'll see I killed three of their crew but after I land they come back.)

### Link to save file

[Samuel Edwards.txt](https://github.com/user-attachments/files/17836573/Samuel.Edwards.txt)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

10.10

### Additional Information

N/A

**Comment by warp-core** [comment]
Replenishing crew (up to the required amount) is the intended behaviour.
https://github.com/endless-sky/endless-sky/issues/1638

**Comment by McloughlinGuy** [comment]
> Replenishing crew (up to the required amount) is the intended behaviour. #1638

Don't know how I didn't find that but thanks. I think some of the things said in the mentioned issue (ie: having the ships self repair or disappear) could be done but that wasn't the point of this issue so I'll just end it here.
