### ISSUE TITLE
After "FW Diplomacy  mission, returning before ceasefire ends (with jump drive) breaks the storyline (for about a week)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1080]
When the above happens, the ceasefire ends in about a week, which it is supposed to take, I guess, but the mission is completed long before then.

On a related note, it also breaks any other mission that uses an event as a timer.

**Comment by jafdy** [comment]
Are you able to continue with story lines that involve fighting the republic while the ceasefire is in affect?

**Comment by Bladewood** [comment]
I am, but it becomes far easier. For a few days, at least.

**Comment by jafdy** [comment]
Good job @LocalGod79. Looks like a good fix.

**Comment by LocalGod79** [comment]
bug, done

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
