### ISSUE TITLE
bug/content: wrong assignments and overcomplete has-keywords

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#10811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some data-files use `=` where `==` was likely meant to be used, and some data-files use `has "condition" >= number`, while has is supposed to only check for existence of a condition.

### Steps to Reproduce

1. Fetch the AST parser from https://github.com/endless-sky/endless-sky/pull/10810 and compile/build that branch
2. Disable any unit-tests that might interfere with a succesfull build
3. Start the game
4. See new error-messages that shouldn't be there.

### Expected Behavior

Those error-messages should not appear on the screen.

### Screenshots

Here is the list of issues that I noticed today:

```
Error: expected infix operator instead of "=":
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/human/human missions.txt"
L8345:   mission "Timothy Radrickson 5b: New Britain"
L8353:     on complete
L8354:       conversation
L8357:         choice
L8377:           "      (Find someone that can procure a fake ID for you.)"
L8379:             to display
L8380:               "timothy radrickson id" = 0

Error: expected infix operator instead of "=":
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/human/human missions.txt"
L8590:   mission "Timothy Radrickson 5c: Dancer"
L8598:     on complete
L8599:       conversation
L8607:         choice
L8617:           "      (Check the medicine shelves.)"
L8619:             to display
L8620:               "timothy radrickson medicine" = 0

Error: expected infix operator instead of "=":
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/human/human missions.txt"
L8772:   mission "Timothy Radrickson 5d: Greenrock"
L8781:     on complete
L8782:       conversation
L8790:         choice
L8800:           "      (Look for a survival suit.)"
L8802:             to display
L8803:               "timothy radrickson suit" = 0

Error: expected infix operator instead of "=":
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/remnant/remnant 2 side missions.txt"
L155:   mission "Remnant: Celebration 1"
L163:     to offer
L167:       day = 7

Error: has keyword requires a single condition:
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/remnant/remnant jobs.txt"
L263:   mission "Remnant: Logistics Industrial Delivery"
L269:     to offer
L272:       has "Remnant: Logistics Civil Engineering: done" >= 9

Error: has keyword requires a single condition:
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/remnant/remnant jobs.txt"
L290:   mission "Remnant: Logistics Outfitter Delivery"
L296:     to offer
L300:       has "Remnant: Logistics Industrial Delivery: done" >= 9

Error: has keyword requires a single condition:
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/remnant/remnant jobs.txt"
L318:   mission "Remnant: Logistics Salvage Delivery"
L324:     to offer
L328:       has "Remnant: Logistics Outfitter Delivery: done" >= 9

Error: has keyword requires a single condition:
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/successors/successor 1 prologue.txt"
L884:   mission "Successors: Trusted"
L892:     to offer
L894:       has "successor jobs" >= 10

Error: has keyword requires a single condition:
file "/home/peter/scorpio/Documents/progs/games/endless_sky/endless-sky/data/successors/successor side missions.txt"
L14:   mission "Successors: Predecessor Research 1"
L22:     to offer
L24:       has "flagship attribute: quantum keystone" > 0
```

### Link to save file

N/A; The issue is in the data files, and seen by the AST parser when the game is starting/loading.

### Operating System

Not relevant for this issue.

### Game Source

Built from source

### Game Version

b61df20111b0579188946eff534f65529d236a33

### Additional Information

I needed to disable one of the unit-tests to compile the game succesfully with this parser. (Since there is an issue within the parser itself when parsing brackets).

**Comment by TheGiraffe3** [comment]
Is there a reason that checks do not catch this mistake?
I've been trying to reproduce on GitHub with a copy of your branch (two commits behind as I write this); after deleting all unit tests and making all GitHub tests run on all pushes, there's still nothing from the Content Style check.

**Comment by TheGiraffe3** [comment]
Or would it be the Data Files check that gives the errors?

**Comment by petervdmeer** [comment]
The Data Files check should indeed give the errors mentioned in this ticket.

**Comment by petervdmeer** [comment]
The coding style issues are mine to fix. :smiley:

**Comment by TheGiraffe3** [comment]
Well, for some reason I'm still not able to get this with GHA.
Definitely is a bug, but none of the actions catch it, even without unit tests.
https://github.com/TheGiraffe3/endless-sky: only the MacOS check is failing.
