### ISSUE TITLE
crash entering job board

### ISSUE THREAD

**Issue by nicm** [endless-sky/endless-sky#10823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi

The game often crashes for me when I click on the "job board" after landing. It only seems to be if I immediately click on "job board", if I click on "space port" or "hire crew" first it seems to be less likely to crash (although that could be my imagination), and if I load the game and then click on "job board" it doesn't seem to crash, only if I leave/jump/land.

It doesn't happen every time, but often. I just started a new game and it on the second jump it happened. Here is that save file if it is any use, it happens consistently but I can have to try three or four jumps: [Test Test.txt](https://github.com/user-attachments/files/17937210/Test.Test.txt)

On macOS: Darwin macbook-pro 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64 x86_64

Here is the backtrace, it is always much the same: [bt.txt](https://github.com/user-attachments/files/17937086/bt.txt) [bt_all.txt](https://github.com/user-attachments/files/17937094/bt_all.txt)

Thanks

### Steps to Reproduce

- Land on a planet and immediately click on "job board".

### Expected Behavior

- Not crash.

### Operating System

Darwin macbook-pro 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64 x86_64

### Game Source

Built from source

### Game Version

14183eaeab1b95d4c9f42119257f882d0bda6bc9

**Comment by nicm** [comment]
Oh I just turned the "filter out mission with a deadline" option on and it never seems to crash now...

**Comment by warp-core** [comment]
Can you turn that option back off and try to reproduce the crash, this time creating a snapshot each time you land before visiting the job board, and upload the snapshot immediately before a crash?

**Comment by nicm** [comment]
Here is the snapshot freom right before a crash: 
[Test Test~3013-12-05x.txt](https://github.com/user-attachments/files/17938026/Test.Test.3013-12-05x.txt)

**Comment by warp-core** [comment]
Can you try out the [continuous build](https://github.com/endless-sky/endless-sky/releases/tag/continuous) and see if the crash is reproducible there?

**Comment by TheGiraffe3** [comment]
That's what he's on.

**Comment by warp-core** [comment]
> That's what he's on.

The issue description says "built from source", not the continuous release downloaded from GitHub (or ESL2).

**Comment by nicm** [comment]
OK I think I have found the problem, endless-sky is linked against the Homebrew libuuid:
~~~~
	/usr/local/opt/ossp-uuid/lib/libuuid.16.dylib (compatibility version 17.0.0, current version 17.22.0)
~~~~
But it is using the Xcode header:
~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/uuid/uuid.h
~~~~
If I `brew uninstall ossp-uuid` it doesn't link because of missing uuid so clearly I need something else...

**Comment by nicm** [comment]
OK I just need to remove "uuid" from SConstruct, it isn't needed on macOS (at least not for me):
~~~~
diff --git a/SConstruct b/SConstruct
index 7b8fb62cf..43c73cbc5 100644
--- a/SConstruct
+++ b/SConstruct
@@ -10,6 +10,7 @@ def pathjoin(*args):
 # Load environment variables, including some that should be renamed.
 # If we are compiling on Windows, then we need to change the toolset to MinGW.
 is_windows_host = platform.system().startswith('Windows')
+is_macos_host = platform.system().startswith('Darwin')
 scons_toolset = ['mingw' if is_windows_host else 'default']
 env = DefaultEnvironment(tools = scons_toolset, ENV = os.environ, COMPILATIONDB_USE_ABSPATH=True)
 # If manually building within the Steam Runtime (scout), SCons will need to be invoked directly
@@ -90,6 +91,7 @@ sys_libs = [
        "rpcrt4",
 ] if is_windows_host else [
        "uuid"
+] if not is_macos_host else [
 ]
 env.Append(LIBS = sys_libs)

**Comment by TomGoodIdea** [comment]
Why are you still using SCons?

**Comment by nicm** [comment]
I have always used scons, it still builds so I didn't know I needed to change, I'll try cmake at some point. This issue can probably be closed now since it is clearly an issue with my build. Thanks.

**Comment by TomGoodIdea** [comment]
I think the current status of SCons is something like: it should work, but we can't 100% guarantee it will work with all setups, because not many people use it and we don't test it actively.

**Comment by nicm** [comment]
Yeah I completely missed the change to cmake (I only rebuild relatively rarely). I'll use cmake next time.
