### ISSUE TITLE
"FW Reconciliation Break" and "FW Conservatory 1" can both be active at the same time

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1083]
And if you complete one of the missions, the other one stays active.
Ijs Springborn confirmed master of cloning.

**Comment by LocalGod79** [comment]
i remember this happening to me some time ago, before i got onto GitHub...

**Comment by endless-sky** [comment]
This has been fixed. (ce88f7c)

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
