### ISSUE TITLE
Typo in Remnant mission in the Patir system

### ISSUE THREAD

**Issue by sebadesca** [endless-sky/endless-sky#10849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm on a Remnant mission in Builder Settlement in Patir, the black-hole next to the Graveyard.
After landing on the Ka'sei asteroid with Dusk, we are entering the ancient Builder structure.
at the end of one of the paragraphs, it reads:
'(...) The ring itself is too small for you to pass through it standing upright, but the low gravity of the asteroid lets you almost fly though it without much trouble. (...)'
Despite English not being my first language, I understand that it should read '(...) lets you almost fly THROUGH it without much trouble.(...)'

Thank you for your amazing work.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

It's just a typo

### Operating System

Android

### Game Source

Other (please describe)

### Game Version

v0.10.10-46

### Additional Information

Game downloaded via F-Droid

**Comment by TheGiraffe3** [comment]
Somebody want to remove the "unconfirmed" label?
