### ISSUE TITLE
Too many missions in one system causes stopovers to be hidden

### ISSUE THREAD

**Issue by tekker2234** [endless-sky/endless-sky#10840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the player accepts more than 12 missions that have stopovers in one system, then any additional missions with stopovers will appear with no visible waypoint marker.

### Steps to Reproduce

1. Go to the Deep
2. accept all available jobs with stopovers (science vessel, science team, science department, mystery retrieval)
3. launch, then land again
4. repeat 2 and 3 until you stop seeing pips appear when you accept the mission. (should be at 12)

### Expected Behavior

waypoints and stopovers should continue to appear on the map after you accept a lot of missions.

### Screenshots

![Screenshot 2024-12-06 185549](https://github.com/user-attachments/assets/eb889e82-c4cf-4dec-b3cc-b137e67c4951)

### Link to save file
[Lakna Byrdock~Mission Marker Testing.txt](https://github.com/user-attachments/files/18045976/Lakna.Byrdock.Mission.Marker.Testing.txt)
Accept the Transport Science Department mission and see no pip appear in Mimosa.

### Operating System

Windows 10 Home

### Game Source

ESLauncher2

### Game Version

Continuous

### Additional Information

First reported on discord by ShadowDragon8565 [Link](https://discord.com/channels/251118043411775489/308902312741568512/1314619428721397821)

**Comment by tekker2234** [comment]
Updated the save

**Comment by petervdmeer** [comment]
Fixed in #10841
