### ISSUE TITLE
Question: Marauder Fury self destructs?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1084]
To my understanding, the only Marauder Fury that is available to the player is that from MMK. If MMK's Fury goes then you can never get a Marauder Fury of your own. So given that it is so unique, should it really have a self destruct?

```
ship "Marauder Fury"
	sprite "ship/mfury"
	attributes
		...
		"self destruct" .25
		...
```
Local's thought process when giving the Marauders self destructs was to make rarer ships have less of an explosion chance as to not cause frustration, but the M-Fury being the rarest has a self destruct rating as if it was one of the common ones.

**Comment by LocalGod79** [comment]
i think you'd better double check that.

**Comment by LocalGod79** [comment]
fixed #1085

**Comment by Amazinite** [comment]
👌

**Comment by psychiclegume** [comment]
When did you put in the self destruct? I've never had a Marauder ship self-destruct on me.

**Comment by Amazinite** [comment]
Self destructing marauders are a v0.9.1 addition.

**Comment by Amazinite** [comment]
Closing this, as it was never in a full release to begin with and there's no way it could be brought up again.
