### ISSUE TITLE
Moderators in the steam forum

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1087]
Since 

> the ravening hordes of Steam users

sometimes goes wild, i think we need a small group of moderators to prevent chaos. Someone like @LocalGod79 or active steam community members like @Amazinite (derpy) and @Disiuze (creator of alphean-boolean)or so.

Their task wouldn't be much active moderation, but to intervene if a thread explodes and insults fly around.

**Comment by jafdy** [comment]
It would be a good idea. Any volunteers?

Any one who moderates the steam forums will be seen to speak for us on github as a whole so we need people who we trust to keep there head on and to be sensible at all times.
ps if it comes to it I vote for @LocalGod79.

**Comment by Disiuze** [comment]
I can be a mod if necessary and I believe @LocalGod79 will be a good mod as he's active both on here and on Steam.

**Comment by Wrzlprnft** [comment]
I would suggest a group of three too five, so if one mod looses his head about another repost of the navy license question, another may be online to calm him/her down.

**Comment by Gkramme** [comment]
I will volunteer.

**Comment by LocalGod79** [comment]
wow guys, thanks for the votes of confidence.

i'd take the job, but as @Wrzlprnft suggests, i'd prefer a committee - sometimes my patience wears out and i can get downright savage, and i don't always have time to be around.  in fact, with summer finally arriving, and Republic plot writing, i expect my time to become more limited in the near future...

**Comment by Amazinite** [comment]
Derpy here. I think it does make sense to have at least a few mods to keep things in order. One of my main issues with the forums is that threads like the 2 (actual) noob threads would probably be best pinned to the top as to avoid people making duplicate threads. There is also the case of people posting in the mods forum when they really shouldn't, so either a pinned topic at the top of the mods forum explaining what it is for and/or someone who locks/deletes threads that shouldn't be there.

**Comment by Amazinite** [comment]
Should we bring this up to the Steam forums to see what everyone else thinks?

**Comment by Wrzlprnft** [comment]
I don't know.

**Comment by Amazinite** [comment]
My only fear with bringing it up is that we would get s dozen people saying "choose me."

**Comment by Wrzlprnft** [comment]
Indeed. In general i think the feedback on the steam forum would be a positive one, too.

**Comment by LocalGod79** [comment]
i also believe that friendly' would make a good crowd controller (besides those nominated already)

**Comment by Amazinite** [comment]
12 pages of 50 posts each. If we had the four requested mods so far all go through it, three pages each, we could probably pick out all the valid questions after only about an hour.

**Comment by jafdy** [comment]
What ever group of people we choose need to be good for people on steam and for us on github. I think we should set up a pole of people who we think would be for the job and let steam help the decision. The github side is small enough that we can sort it out between us as to who we will nominate.

**Comment by toilethinges** [comment]
Yes. @LocalGod79, @Amazinite, Friendly Neighbor and @Disuize would all make very good mods.

**Comment by psychiclegume** [comment]
Maybe as an addition to that, put those questions on FAQ and have a few quotes that could be referenced by mods?

**Comment by mdsmestad** [comment]
I agree, need's some moderators to keep things legit.

**Comment by Wrzlprnft** [comment]
If there are any votes within moderators, a odd number would be better.
Anyway, can the suggested candidates write their usual online times with timezone?
Also, a job for moderators: create a topic in the bug section and pin it: OpenGL errors.
Further, if we(including @endless-sky ) agree, we should post a topic in the steam forum if anyone has problems with the choice. Would prevent a "choose me" flood, but if any major cons we overlooked are there, they'll rise up.

**Comment by Disiuze** [comment]
I am most active between 16:00 and 22:00 (UTC +2).

Yes, an odd number would be necessary for votes.

**Comment by Amazinite** [comment]
I'm usually active from 15:00 to 23:00 EDT / 19:00 to 03:00 UTC, along with hopping on at other times throughout the day.

**Comment by jafdy** [comment]
Is it possible to make a Mods only thread on the forum to let them discus/vote when they are not certain about what to do in a situation.

**Comment by Amazinite** [comment]
We could make a mod only group on Steam, instead of needing to devote a subforum/thread to them.

**Comment by Disiuze** [comment]
I can create the group if everyone is fine with that.

**Comment by LocalGod79** [comment]
i'm utc-4 right now, -5 through the winter, and am on periodically over my waking 12-16 hours a day.  some days i'm more "present" than others, which is another reason i was *really* hesitant to take it on alone.

five of us is good coverage.  three could do it, i'm just not sure that i would want to be one of them...

@Amazinite - you're going to have to tone your trolling down a little (at least in the E.S. forums), if you're going to take this responsibility seriously.

i don't think anybody's put @Wrzlprnft up for nom, so i'll do that, too.

so, as I see it, we can put a list of 7 or 8 moderator candidates up (careful with 'mod', especially with this game - i keep reading "modification"), and take a vote in a Steam thread which has a closing date near the end of July (for example), to get a better sample?

users could have one "objection" (-1), and one "vote" (+1) (but no "pick me"), in a single post - top 5 become moderators when the post closes.

**Comment by Amazinite** [comment]
@LocalGod79 Yeah, I understand that. 

That sounds like a pretty good way to do it.

**Comment by Disiuze** [comment]
Sounds like a good plan.

**Comment by Amazinite** [comment]
Should we not do a "pick five" scenario instead of a "vote for your favorite," as the second one could end up with some people getting all the votes and not enough people getting voted for. Say we have 17/14/10/3, and the rest are zero. We'd need to revote for the last person, but a pick five scenario would avoid this.

**Comment by Amazinite** [comment]
https://www.zoho.com/survey/
We could use this website. It ensures that each person only votes once and it's free.

**Comment by jafdy** [comment]
Do we have 7 or 8 candidates yet? 
I don't think having an objection option would be helpful. If a valid objection is made ether it would be disregarded or be enough the candidate should be withdrawn. 
Could you have a list up for 2 or 3 weeks to give a chance for people to object and then make the vote for 4 or 5 weeks.

**Comment by Amazinite** [comment]
As of right now, i believe that we only have 5 considered candidates. @localgod79 @wrzlprnft @disiuze friendly neighbor and me.

**Comment by LocalGod79** [comment]
i see your point, @Amazinite.  perhaps a +1 for five candidates is better, with an option for a -1 objection (i don't know that justification is necessary - it might lead to character attacks and argument)

i believe @toilethinges is a worthy candidate, as well.

**Comment by Amazinite** [comment]
Definitely.

**Comment by jafdy** [comment]
The trouble with having a -1 without justification is that some people will use it just because they don't like them rather than they would be good for the job.

**Comment by Amazinite** [comment]
True. If the justification is just that they don't like the person then we wouldn't take that into consideration, but if the justification seems valid then we would use it.

**Comment by jafdy** [comment]
The time covered by @Disiuze and @Amazinite is 14:00 to 03:00 UTC
@LocalGod79 is harder, my best guess is about 03:00 to 17:00 UTC
American evening is about 06:00 to 15:00. Most of that is only covered by @LocalGod79 
Don't know about @Wrzlprnft, @toilethinges or friendly neighbor.
I would be prepared to help but I can only do weekends until mid July.

**Comment by LocalGod79** [comment]
@jafdy i feel like these cases will be isolated, and will not generally alter the eventual outcome.  when tallying the results, we can compile two sets of data - one with the objections, and one without - to see how it skews results.  i'm not entirely sure that being disliked is a desirable trait in a forum moderator (before they become one), making the justification of the "-1" irrelevant in your argument.  don't get me wrong - i'm sure i'll even get a couple - i noticed a less than warm reception when my mod was finally published on steam - it didn't change the result of that release.

i'm in a situation where i have access to my pc most of the day/evening (so, your guess is mostly accurate - occasionally the back end of it gets pushed a little later), but i have some flexibility during the north american day (where there is generally less traffic)

@Wrzlprnft is also UTC+2 (i think), and i believe he is a University student, so his schedule is also "all over the place".

ideally, we'd find a candidate on the west coast of N.A. to fill in my "late night"...

**Comment by jafdy** [comment]
But saying that you take 2 data sets and picking the one you like best is going to degrade the respect the moderators get as people will see it as forcing the result. You would be better off just setting up 5 moderators with out warning. 
@Disiuze covers your late evening some one is needed to help cover your morning/mid day.
I've also updated my time guess.

**Comment by Amazinite** [comment]
I know Allallid is on the west coast, but I don't know if he would be willing to give up his trolling privileges for a moderator job.

**Comment by Amazinite** [comment]
@Localgod79 I believe that Wrzl has mentioned being in UTC+1 time.

**Comment by jafdy** [comment]
if @Wrzlprnft is UTC+1 then the gap comes to 2 hours from 03:00 to 05:00.

**Comment by LocalGod79** [comment]
@jafdy as i've suggested - i do not believe that "i don't like this person" is an invalid reason to "downvote" them as a moderator.  making individual downvotes conditional has the same effect as making choosing which data set one likes better than the other.

i would prefer to leave it, and suggest that *if* you removed the data set later, the results will probably not be different.

**Comment by jafdy** [comment]
How ever it is done it must be open and final.

**Comment by Amazinite** [comment]
> American evening is about 22:00 to 06:00

American evening is 19:00 to 6:00, if we include the entire continent/country. 22:00 to 6:00 is just PDT.

![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/15336344/29df2232-1c44-11e6-8d87-638b2af1a0e4.png)

I'm awake 11:00 to 03:00 and able to be at my computer 15:00 to 03:00, so that's 8 hours guaranteed covered with another 8 hours on and off with my phone.

Friendly and @toilethinges are in the same timezone as @LocalGod79 and I, so that would be 4 people all in UTC-4
@Wrzlprnft and @Disiuze are both either UTC+2 or +1.
@Jafdy, what timezone are you?
If Fallen Cat is able to get on his feet and would accept a mod position, he is UTC-7 and would be able to cover that 03:00 to 06:00 time slot by himself for a bit.

**Comment by Wrzlprnft** [comment]
I am UTC+2, and indeed, my schedule varies, but i guess i do take looks at the forums from 06:00 up to 22:00 regularily, during "workdays" often later.

Also, i don't think we need a 100% coverage, because -once immediatly closing a thread or whatever is needed- no one will be present, wether right on the spot, nor at the moment looking at the forum. I just wanted to know how large the coverage actually is, i prefer good moderators over good timeslots. Also, maybe we do need to talk about some topics from time to time, and that would be easier if everyone is actually online, but doesn't prevent a good discussion.

We still need mr. Z's opinion on this.

**Comment by toilethinges** [comment]
Actually, I'm UTC-5, Amazinite. I can cover 15:00-1:00, approximately.

**Comment by LocalGod79** [comment]
i tend to agree with @Wrzlprnft a little - at the moment, five moderators seems excessive - most of us will be silent most of the time, and the number is more to give others a break when they need to just step away from it for a while...

agreed that M.Z. needs to weigh in: we have a rough selection, with a possible voting system if required.  M.Z. may pick five names (possibly including someone he knows personally that we have not named), and it'll all be settled before it comes to that.

**Comment by jafdy** [comment]
I'm GMT.

Including Fallen Cat (same local times as @LocalGod79)  and me everyone would be on roughly between 15:00 to 20:00 UTC and someone would be on at all times, lowest cover between 03:00 and 08:00 (When I come on) mostly by @Wrzlprnft.

Not including Fallen Cat and me the everyone time would be the same but with only @Wrzlprnft between 04:00 and 11:00 when @Amazinite comes on.

**Comment by LocalGod79** [comment]
Fallen Cat is West Coast U.S.A. - UTC -7, right now...

**Comment by Amazinite** [comment]
I talked to Friendly about being a mod, since he doesn't have a GitHub account. 

>I would be glad to assume the position if other players were fond of my capabilities

**Comment by jafdy** [comment]
Same times *local* times so 2 hours behind you.

**Comment by jafdy** [comment]
![image](https://cloud.githubusercontent.com/assets/15716454/15354458/a092e228-1ce5-11e6-97e1-8fcdad019a17.png)

That's my best guess at coverage.

**Comment by Wrzlprnft** [comment]
I repeat, there is, even only with the top 5 of those on the list, enough coverage, in my humble opinions.

**Comment by jafdy** [comment]
I'm mostly just interested on how much coverage and the time everyone is on at the same time.

**Comment by toilethinges** [comment]
@jafdy - Red represents computer online time, yellow is awake?

**Comment by jafdy** [comment]
Sorry I should have explained that.
Red - at a computer - definitely can help
Yellow - on and off - some times on - or not sure/best guess
Green - american evening

**Comment by toilethinges** [comment]
Should add yellow 2 hours before the starting, and 1 hour after the end, for mine. That's when I possibly can get on/stay on, but only some days.

**Comment by LocalGod79** [comment]
@endless-sky i wasn't really convinced that the Steam forums really needed moderation until i saw this post, which refuses to die (and is irritating a number of users), in spite of being completely addressed *by you* on post 15 (it's now up to post 122);
http://steamcommunity.com/app/404410/discussions/0/364041517010954696/

**Comment by Alkallid** [comment]
Does it make you question your holy community? Hue

**Comment by toilethinges** [comment]
@LocalGod79, I've managed to ignore that post until yesterday, but it's gone a bit too far at this point.

**Comment by Amazinite** [comment]
The post has been resolved. Now just wait till someone bumps it a week from now and tells someone to die in a hole again.

**Comment by Gkramme** [comment]
Gosh. You'd think people would be nicer online... But _nope_

**Comment by toilethinges** [comment]
@Gkramme, don't people have better things to do than telling people online to die in holes?

Answer: Yes, yes they do.

**Comment by jafdy** [comment]
Can we stop expanding that steam thread on to github.

**Comment by Gkramme** [comment]
@toilethinges like playing endless sky :)

**Comment by mdsmestad** [comment]
@endless-sky Is this ever gonna die?

**Comment by Gkramme** [comment]
Probably not

**Comment by Amazinite** [comment]
Now that I think of it, 5 may be a little excessive. 1-3 would be fine, but if the purpose of a mod is just to calm down flame wars then we really only need one. They might not be there 24/7 to see them right away, but if a flame war continues on for a while then we'd really only need one mod to act upon it.

**Comment by Gkramme** [comment]
We could all just act like a mod. We really don't need a specified mod to calm down flame wars.

**Comment by toilethinges** [comment]
@Gkramme, someone to close the posts would be very helpful...

**Comment by psychiclegume** [comment]
Going back to @Gkramme , It seemed like when @LocalGod79 tried to calm the trolls on https://steamcommunity.com/app/404410/discussions/0/364041517010954696/ It seemed that he was shouted down a little, and that he was not well recognized. Maybe adding the Moderator label will help, like how putting someone in a policeman's uniform will make people respect them a little more.

**Comment by Amazinite** [comment]
Simply having a moderator with the label nearby would definitely make people calm down more knowing that they could probably get banned for telling people to die in a hole...

**Comment by jafdy** [comment]
@Amazinite If there where 3 moderators and one say went on holiday so couldn't help for a couple of weeks that would leave 2 people. Having a couple of extra moderators means that chances are you wont ever get less than 3 people active. 3 is about the minimum needed for a vote to work if it is needed.

**Comment by toilethinges** [comment]
@psychiclegume, very good example.

@jafdy, yep.

**Comment by LocalGod79** [comment]
@jafdy you're assuming that there needs to be a tie-break.

if there are three moderators, and one is on vacation for a couple of weeks, *and* the two "on-duty" moderators are at odds on a particular issue - it could probably wait until the third gets back to resolve (and probably won't come to even that)...

**Comment by LocalGod79** [comment]
another case-in-point;
http://steamcommunity.com/app/404410/discussions/0/357287935546649380/

**Comment by wambat1** [comment]
sorry to bug, but is this happening or what? at least one person who can come in once a day and move posts into their appropriate sub-forums. gotta start somewhere.

**Comment by jafdy** [comment]
To get this moving we need @endless-sky to approve it. (and probably decide who dose it)

**Comment by endless-sky** [comment]
If you guys pick who you want to be moderators, I can go ahead and add them to the forum.

**Comment by Amazinite** [comment]
@LocalGod79 guaranteed.

**Comment by jafdy** [comment]
+ @Amazinite.
+ a Europe person so @Wrzlprnft or me.

**Comment by Disiuze** [comment]
@toilethinges as well

**Comment by FriendlyNeighbour** [comment]
Yeah, Local God 100%

**Comment by Wrzlprnft** [comment]
Local said he will have not as much time for the game as he used to, and i'd rather see him worrieng about game issues than steam threads, but if he thinks he doesn't get distracted too much ill vote for him too

**Comment by Amazinite** [comment]
If I am one to get chosen, my Steam name is "Derpy Horse"
@wrzlprnft I don't think it would hurt to have Local be a mod, even if he focuses more on game issues than Steam threads. But that is up to him.

**Comment by jafdy** [comment]
@Disiuze Your Europe but your online times could be from anywhere. The reason I said me or @Wrzlprnft is because one of us will usually respond first to anything before @Amazinite comes on. The other way of putting it is that for Europeans the moderators will only be on in the evening without ether me or @Wrzlprnft.

**Comment by LocalGod79** [comment]
wow! thanks, guys!

i'd be honoured to take a "Moderator" position for Endless Sky on Steam.

i'll start by saying i've been really impressed with the showing from the entire community that is now bridging Steam and GitHub.  great job, guys! i'm sure @endless-sky appreciates not having to spend so much time sifting "the pile" that is our Steam Forum...

i've been watching the forums more from the perspective of a moderator over the past couple of weeks, and i believe that 3Ms would be *way more* than sufficient, even with fluctuating availability.  generally, threads take a full day (or more) before they get to the point where a Moderator would *need* to step in - more than enough time with the activity of *any* of the candidates.

my ideal "fleet" of two "wingmen":
@Wrzlprnft, since he's been the coolest, most level-headed responder in the forums (i dare anyone to disagree).

and i've also especially impressed by the way @Amazinite a.k.a. "Derpy Horse" has stepped his maturity up (one presumes because he wants the job), coupled with his enthusiasm and activity.

it's not that the rest of you haven't been *stellar* - you *have* been - please keep it up, we can use as many "escorts" as we can get, as this game gets more popular.

i mean it.

just because we all don't get "Moderator" next to our name, doesn't mean that you're not an "Elder", and can't help the way you have been (the Moderators *will* back you up, as long as you're not salty) - it's just that these *two* seem to stand out to *me* most.

**Comment by endless-sky** [comment]
@Wrzlprnft, are you officially a "member" of the Steam forum? The admin tools aren't letting my select you - maybe it has something to do with you being Steam level 0?

**Comment by Disiuze** [comment]
@endless-sky Odd. I don't think Steam level has to do anything with it, though.

**Comment by Wrzlprnft** [comment]
Indeed, i am steam level 10. I did set all my privacy settings to public for now, maybe that helps.

**Comment by endless-sky** [comment]
For some reason I can't add Derpy Horse or Wrzlprnft. Could you both check if you are "following" Endless Sky (the button on the main [community hub](http://steamcommunity.com/app/404410) page)? I found one forum post saying people have to do that before they can be added as moderators.

**Comment by Amazinite** [comment]
I'm following it now.

**Comment by endless-sky** [comment]
...and now you're a moderator. So, @Wrzlprnft, it looks like you need to "follow" the game in order for me to be able to add you as a moderator.

**Comment by Wrzlprnft** [comment]
Oh ok. I'm now following,too.

**Comment by Wrzlprnft** [comment]
It worked. Thx, let's see how this works out.
