### ISSUE TITLE
Wanderer storyline bug - Defense Fleets on Captured Systems

### ISSUE THREAD

**Issue by Wakashio-Macron** [endless-sky/endless-sky#10873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After the Unfettered Hai take over of Ik'kara'ka, Chy'chra, Sich'ka'ara, Chirr'ay'akai, Kiro'ku, and Ka'pru the system fleets that spawn when you "demand tribute" have not changed from Wanderer to Unfettered Hai.

### Steps to Reproduce

Demand Tribute from a planet in Ik'kara'ka, Chy'chra, Sich'ka'ara, Chirr'ay'akai, Kiro'ku, or Ka'pru and a Wanderer fleet will spawn.

### Expected Behavior

When tribute is demanded from a planet in Ik'kara'ka, Chy'chra, Sich'ka'ara, Chirr'ay'akai, Kiro'ku, or Ka'pru systems after the Unfettered Hai have captured the systems a Unfettered Hai fleet will spawn.

### Operating System

MacOS 15.1.1

### Game Source

Steam

### Game Version

0.10.10

**Comment by TomGoodIdea** [comment]
Has #10738 solved this?

**Comment by Wakashio-Macron** [comment]
It seems to. I ran the added code as a plugin and it removed the fleet. Story wise I would think that the Unfettered would place a new defensive fleet.

**Comment by TomGoodIdea** [comment]
> Story wise I would think that the Unfettered would place a new defensive fleet.

#7875 describes why they don't do so.

**Comment by Wakashio-Macron** [comment]
Makes sense, thank you.
