### ISSUE TITLE
Illegal Outfit Notice

### ISSUE THREAD

**Issue by RaptorKyelok** [endless-sky/endless-sky#10880]
### Problem Description

I just capped a pirate ship, then unexpectedly got tagged with a $1M fine upon landing.

### Related Issue Links

I'm not aware of any past discussion related to this.

### Desired Solution

I would have preferred that when I capped the ship, a popup came up telling me the ship had illegal outfits and asking me if I wanted to dump them. It'll be annoying if I have to manually verify every ship I cap doesn't have illegal outfits each time I cap something.

### Alternative Approaches

Some possible alternatives:
- Never have pirates spawn with illegal outfits
- Make it more obvious that a ship has illegal outfits equipped, maybe an icon or a special outline or something in menus and in game
- Track that a ship was capped and instead of the authorities issuing a fine right away, only issue a warning on first offense with a newly captured ship
  - Could also offer the option of having the authorities seize the illegal outfits and not fining the player

**Comment by TheGiraffe3** [comment]
That was a Marauder ship. In general, Marauders have more advanced technology in all areas, including hand to hand combat.
So the Marauder you captured had Nerve Gas (#10222); that outfit is illegal all over human space.
Related: https://github.com/endless-sky/endless-sky/issues/10180#issuecomment-2156613303 and the further discussion on that.

**Comment by RaptorKyelok** [comment]
I'm aware it's illegal. I believe putting it in pirate ships is new to version ~10? This is the first time I've dealt with this mechanic as I've deliberately avoided illegal outfits.

The other thread is much more comprehensive. If you want to mark this as duplicate and just register that a player was unpleasantly surprised by this mechanic, that seems like a logical thing to do.
