### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1090]
This is not to ask about a certain translation, but how much effort would it take to read in stuff like
button labels or so of text files at the start-up of the game? it would make a functional translation possible, even if the content is not yet translated.

**Comment by endless-sky** [comment]
The most difficult part would probably be adding support for non-ASCII characters, which would require completely changing how text is rendered. It's certainly on the long-term todo list, but there are other things I think are more important at the moment.
