### ISSUE TITLE
Combat Rating and Tribute

### ISSUE THREAD

**Issue by MOZZIEJR** [endless-sky/endless-sky#1092]
I have a combat rating of 7, but can't demand tribute to any pirate planets, such as planets in the Antares system, Shaula system and the Alcyone system. I'm not sure if this is a problem or not. Please help.

**Comment by endless-sky** [comment]
The UI rounds your combat rating, but it needs to be at least 7.3 (1500 "kills") to demand tribute anywhere, and some planets don't let you demand tribute until it is above 9.

**Comment by MOZZIEJR** [comment]
Ok. Thank you very much.

**Comment by jafdy** [comment]
That translates to 750M credits of defeated ships. (I think)

**Comment by egilburg** [comment]
@endless-sky perhaps link conditions such as these to the exact combat tribute rather than a fraction, to avoid similar confusion?

**Comment by endless-sky** [comment]
Combat rating is stored internally as a number on a linear scale (up to 0.9.0, essentially the number of people you have killed; after 0.9.1, it will be roughly twice the cost, in millions of credits, of all ships you've disabled).

For display, that linear combat rating is converted to a "level" on a logarithmic scale, i.e. combat rating level = ln(combat rating). The reasoning is that your ship's strength grows exponentially, so the requirement to reach each combat level should grow exponentially, too. (This is the same as how XP works in most RPGs, and how combat ratings worked in EV.)

**Comment by Bladewood** [comment]
*very valuable fleet*
*destroys it*
I am now max combat tier.

**Comment by jafdy** [comment]
If I use the Kestrel mission as a bench mark that's 8000 kills or 4B credits. So what's this fleet your talking about anyway?

**Comment by Forlarren** [comment]
Can the combat rating on a planet be changed?

I'd love to make a early side mission where you can kick the teeth of some pirates in and get a little rent income but not game breaking.

**Comment by Bladewood** [comment]
Use code tags.
```
text
```
Three backticks on one line, actual code in the following, and a final three backticks on another line at the end.
