### ISSUE TITLE
Ship Density

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1094]
So I wanted to start by saying I'm a huge fan of Escape Velocity and am loving Endless Sky so far, playing the latest version currently on Steam.

However, one thing I'd like to see improved is the density of NPC ships; EV had relatively few ships and these stuck around for longer, whereas in Endless Sky the ships seem to come and go too quickly, this is partly the result of several factors that I'd like to see adjusted:

**Minimum Jump Distance**

In EV games there was a minimum distance from the system's centre from which you could perform a hyperspace jump, which isn't the case in Endless Sky. This has a big impact on the NPC ships who jump the moment they've nothing else to do.

At the very least the NPC ships (except escorts and some special ships) should move to a minimum distance from the centre before jumping, ideally in the direction that they wish to jump. This will force them to stick around for longer, and allow the overall density to be reduced from lots of ships jumping in frequently.

The player could also be affected by this requirement, possibly scaled based upon ship size and/or quality of hyperspace engine?

**Ship Swallowing Planets**

While I kind of like that my ship appears to land, having NPCs do it too removes them from the area which I think doesn't help with ship density. I'd like to see larger ships remain in orbit instead, as this keeps them handy to respond to attacks.

**Patrols**

Apologies if this is in, but I haven't noticed any military ships actually performing patrols; in EV games many systems had some type of system defence ships that would hang about near a planet and/or randomly scan ships. I've noticed Republic vessels scanning me, but only before jumping out of the system.

**Uninhabited Systems**

Despite being uninhabited, these systems can get pretty busy too. That's fine nearer core worlds, but I've never really had an encounter with pirates quite like I did in EV; where I'm all alone in an empty system being pursued to jump range by a pirate, or jumping in to the aid of a lone freighter being picked on. In fact I'm really struggling to disable and board pirates as there are usually so many ships jumping in and out of the system that no-one lasts long.

**Fleets**

I feel as though fleets may be a bit common at the moment too, perhaps it would make more sense to scale the chances of encountering them based upon the player's strength or progression through a storyline?

I want to stress, I don't want this to sound overly critical as I'm still having a great time playing, but I just feel that the amount of ships and the amount of time that they stick around for is a bit unbalanced; pirate attacks don't feel unexpected and tense, instead they're often either overwhelming or easily mopped up before I can get to them because they frequently arrive in force, or there's so much in system they're trivially repelled.

**Comment by jafdy** [comment]
That is alot of text I think I can address some of them.

1) **Jump distance**
The fastest way for a ship to leave system with a Hyperdrive like this would be to fly the wrong way and make a jump across the center. So the AI would need to decide weather it is faster to fly in the direction of the jump (Scramdrive) or fly the oppsit way (Hyperdrive). This would need to be a fleet decision or the freighters end up on one side of the system with the war ships on the other side. 

2) **Planets "swallowing" ships**
Well a ship lands for a day so if they could take off in less time it wouldn't make sense. I *am* aware that the players escorts don't follow this rule at all.

3)**Patrols**
Planets do have defense fleets they launch in planetary defense missions and if you demand tribute. Government fleets will come through and will then leave if there is nothing to kill.

4)**Uninhabited Systems**
In endless sky most uninhabited systems are used as trade routes and are paroled the local government. The exception is the far north where no one goes because its a bat trade route so no traders and no traders so no pirates and no pirates so small navy presence.

5)**Fleets**
The world doesn't scale to you so why should the galaxy. When you are flying around in your cargo crate with thrusters you should be out powered by everything, when you are flying around with your 40 Shield Beatles you should be able to stomp any fleet in human space.

**Comment by Haravikk** [comment]
> The fastest way for a ship to leave system with a Hyperdrive like this would be to fly the wrong way and make a jump across the centre.

This will depend on whether you prefer to implement this optimally or thematically. For example, in Escape Velocity games the AI will fly in the direction of their next jump, so if their next jump is "north" they will fly to the point "north" of the system's centre that is past the minimum jump distance.

For the player in EV games the direction didn't matter, they could just jump as long as they were past the minimum distance, and any escorts they had would just jump with them (i.e- escorts ignored the distance).

It lacks a bit in consistency sure, but it means that regular NPC ships behave a bit more logically, and they're "trapped" in the system for the amount of time it takes to manoeuvre to their intended jump point or otherwise get outside of the distance (iirc in EV games if a ship is already outside the distance when it decides to jump it just does it from its current location, regardless of direction). The advantage of making the player reach the minimum distance too is that it increases the amount of time it takes to leave a system, which makes escort and pursuit missions harder, as you have to survive longer; currently escort missions are too easy except when pirates jump in in overly large groups.

> Well a ship lands for a day so if they could take off in less time it wouldn't make sense.

For the player sure, but all kinds of things could be going on for NPCs, plus it arguably makes less sense for huge ships to land at all due to the cost of taking off again (and the risk a landing could entail). It's more likely they'd remain in orbit with crew shuttling down to make deals, and most transfers happening in orbit at small space stations etc. Again in EV NPC ships never landed in the same sense as the player, they just stopped over a planet, hung around for a minute or two, then headed off again, but it meant they could be attacked and such.

Anyway, the point is to keep NPC ships on the map when the player is flitting about. The way things stand now I'm not really sure how you're supposed to become a pirate when ships jump out of systems so easily and disappear if they get to a planet before you can disable them.

> Planets do have defense fleets they launch in planetary defense missions and if you demand tribute

The purpose of this issue is the ship density in systems, i.e- how populated with ships they are, which is why I raised patrols. In EV many systems have fighters or even larger ships they fly around inspecting ships on a semi-permanent basis. It's not about defending the system, but making it feel more populated and have semi-permanent ships in it, currently it's just a constant mix of ships jumping in and out rapidly, no sense that anyone sticks around at all.

> In endless sky most uninhabited systems are used as trade routes and are paroled the local government.

They're still the mostly likely place for a pirate to want to attack within populated regions, due to the lack of permanently stationed defence ships. Still, this is an issue of ship density; in EV for example uninhabited systems are patrolled too, but there are less ships in general in these systems, and when pirates show up it's more dangerous as a result as traders flee to jump distance to escape.

> The world doesn't scale to you so why should the galaxy.

It's about player experience; yes flying in a tiny shuttle should be dangerous, but even when you've upgrade to several million credits worth of ship you're in danger of randomly encountering full-sized pirate fleets, pirate heavy warships and the like. This exacerbated by them sometimes jump in on top of you, and pirates seeming to focus more on the player than other ships (regardless of whether they're more valuable or not) but those are other issues.

This is why I mentioned tying it to the story as a possible means of scaling; yes heading into lawless space should be riddled with pirate fleets, but I've seen them jump into systems nearer core worlds, systems that should be relatively safe. This doesn't really make much sense unless the military fleets are busy elsewhere.

Fact is that while a level of tension and danger is good, getting stomped randomly for no reason is no fun, and again it comes back to ship density. Since there can be a lot of non-pirate ships it seems like the pirate fleets are there to balance the equation, but because of the random nature it doesn't always work out as a fair fight (or the pirates just pummel me with missiles even though I'm not fighting them).

Also, it does make sense for pirate attacks to scale with the player, as there's not much profit for a fleet of pirate warships in attacking a small player, but it would make sense for them to pursue and attempt to ambush a player with a huge ship or fleet.

**Comment by jafdy** [comment]
> For the player in EV games the direction didn't matter, they could just jump as long as they were past the minimum distance.

Yes and this is not EV. Our ships need to slow down and line up for jumps this is what slows ships down.

>Less sense for huge ships to land at all due to the cost of taking off again

We have an excuse for that.
>2360: Invention of "repulsor" engines that work only within a gravity well, but make taking off from or landing on planets much easier.

>In EV many systems have fighters or even larger ships they fly around inspecting ships on a semi-permanent basis.

Could you stop making EV comparisons, this is not a EV game. If you feel so strongly about this you set fleets in each system that don't have Hyperdrives and put it in a plugin.

>When pirates show up it's more dangerous as a result as traders flee to jump distance to escape.

The endless sky version has the same effect. Pirates are more common in uninhabited systems.

>It's about player experience; yes flying in a tiny shuttle should be dangerous, but even when you've upgrade to several million credits worth of ship you're in danger of randomly encountering full-sized pirate fleets, pirate heavy warships and the like.

Yep, yep and yep. We have that, don't know what game your playing.

>I've seen them jump into systems nearer core worlds, systems that should be relatively safe.

You said it your self, it is easy to just jump through a system so the pirates can get everywhere. If your having trouble fly up by the paradise planets and the Deep.

>getting stomped randomly

I have never had this problem, are you flying on the south edge of Human space?

>There's not much profit for a fleet of pirate warships in attacking a small player.

But 20 small players . . . Pirates only go after you especially if you have a critical mass of freighters (or in bounty hunting missions).

p.s. Have you completed the main story yet? And if so what branch?

**Comment by Wrzlprnft** [comment]
jafdy, don't stomp everything he says, the "busy systems" is a complain we have very often, and only a few times like this: not primarily about the combat, but more about the atmosphere.

Getting randomly stomped by pirates can happen, though.

But, you are right, this is not EV. It is aiming to be similar, but it is not the same game.

**Comment by jafdy** [comment]
Then I have been incredibly lucky.

**Comment by Haravikk** [comment]
> Our ships need to slow down and line up for jumps this is what slows ships down.
They did in EV too, but it doesn't really keep ships in the system for very long, whereas a minimum jump distance does.

> Could you stop making EV comparisons, this is not a EV game
The main page of the site states "A space exploration and combat game similar to Escape Velocity". I'm not saying the game should be identical by any means, but the EV series gets the ship density right IMO so it's worth exploring why as a lot of it comes down to relatively simple behaviours like those I mentioned.

Modding the game to put bunches of stranded ships in system wouldn't really help as this wouldn't feel any more like real ships jumping into system to do business. I mean, it might help to have a few, but really that's a workaround to the problem being that regular ships disappear very quickly.

>> Less sense for huge ships to land at all due to the cost of taking off again
> We have an excuse for that.

I'm not saying it can't be explained away, that's not my point, my point is that having them disappear is part of what leads to a system feeling empty, it's also impossible to know how many ships are currently landed and about to erupt out of a planet; having them remain in the system by taking up position near their target world makes it completely clear, and gives more of a sense that the ships are still there. It's about the atmosphere more than anything and about having ships stick around for a while. Right now there's no much incentive to cycle through ships or fly in for a look as most of the time they jump away or land too quickly; I only cycle ships if I have a specific target to find, otherwise I just use nearest enemy.

>> getting stomped randomly
> I have never had this problem, are you flying on the south edge of Human space?

Anywhere pirates can be seems to have the potential to bring in an overly powerful one, or even a fleet of pirates. This isn't necessarily the problem though, the reason I mentioned it in terms of ship density is that the problem is partly one of frequency; because ships jump in and out fairly quickly, it's possible to be in a challenging fight with a pirate and then have more jump in and destroy you.

If ships stuck around longer, then more wouldn't need to jump in as often, which means this wouldn't be as likely to occur. Still could, but more time in between means more time to defeat earlier enemies, or to get away etc.

Bad luck in running across a tougher pirate is the nature of randomness, that happened in EV games too, but at the moment in Endless Sky it seems like it's just too variable; I very rarely get to square off against some pirates I can beat, either they overwhelm me, or they are hopelessly outmatched by ships in the system (in which case I don't often get to do much). There are some other issues, pirate fleets may be a little too common, even in some of the more southerly areas (e.g- between Earth and the Dirt Belt), as Republic and Free Worlds ships do appear here commonly, yet pirates can be present every few jumps.

I'm doing the Free Worlds arc of the main story, so Rand (in one of the Kaus systems I think, I'm no good with names) is a destination a lot. It seems to get pirates much of the time, often spawning around the planet rather than jumping in. Groups of them might make sense here due to proximity to the south, but it seems like they should jump in rather than wait in ambush, and that a system like Rand would have a few guaranteed patrol vessels to prevent there from being cases where it's just the player and a bunch of pirates.

**Comment by jafdy** [comment]
What ships are in your fleet?

**Comment by endless-sky** [comment]
In EV each system only contained one or two planets. If ES were modified so that you can't jump while near a planet, getting away from all the planets would be complicated in some situations, and non-trivial for the AI to plan. (I actually tried adding in that constraint, a year or so ago, but concluded that it just made hyperspace jumping too annoying.)

Both NAEV and OOlite make it considerably more difficult to jump between systems, and it can be quite annoying - especially when trying to cover a large distance quickly.

**Comment by Haravikk** [comment]
> In EV each system only contained one or two planets.

EV doesn't measure minimum jump distance from planets, and that's not what I proposed; it measures from the centre of the system. EV Nova actually had several systems with planets that were far part, such that you can actually jump right on top of them.

This easy for AI ships to plan their jumps as all they have to do is take the direction of their jump from the centre of the system, and plot a point that minimum distance out and jump from there; fleets could jump based on the flagship alone for simplicity (i.e- other ships just ignore the restriction so long as the flagship is far enough out).
