### ISSUE TITLE
[bug] ships erroneously reporting erratic movement due to lack of crew

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1095]
didn't click until now (reading a post on steam) what might be causing the spamming - androids?

edit; perhaps not - the steam user is using 0.8.11 (no androids) - still, i get spammed by this a lot, with no apparently good reason.

**Comment by endless-sky** [comment]
I'd guess this is probably the same as bug #1079 - if they have a plugin installed that has a typo in a ship name in a fleet definition, it occasionally spawns "undefined" ships that have 1 required crew and 0 bunks.

**Comment by LocalGod79** [comment]
i am not using any modifications but my own, and i haven't finished the storyline with this character yet (a prerequisite for all of the content contained within).

**Comment by Amazinite** [comment]
Another user on Steam has made a bug report with the same issue. I'd post the link, but I can't copy steam post links on mobile.

**Comment by LocalGod79** [comment]
http://steamcommunity.com/app/404410/discussions/1/364042262878567711/

**Comment by endless-sky** [comment]
The asteroid bug is fixed in 0.9.1 (6153f05). I don't know for sure if these other issues have been fixed, but I haven't seen any "moving erratically" messages in my testing lately.

**Comment by toilethinges** [comment]
If there's a drone, make sure it has automaton attribute. That, it turns out, was what caused my issue.
