### ISSUE TITLE
Freeze when dominating with large fleet

### ISSUE THREAD

**Issue by tomowad** [endless-sky/endless-sky#1097]
When trying to dominate planets, with a fleet of about a hundred ships, the game regularly freezes. It seems as though it may be happening most frequently when the ships are tightly clustered together, and firing heavily.

**Comment by Quantumshark** [comment]
what ships are you using?

**Comment by tomowad** [comment]
The following:

ship "Shield Beetle"
ship Dreadnought
ship Bactrian
ship "Marauder Leviathan"
ship "Marauder Arrow"
ship "Korath Chaser"
ship Splinter
ship "Marauder Raven"
ship "Marauder Manta"
ship "Marauder Raven"
ship "Marauder Manta"
ship "Marauder Quicksilver"
ship "Marauder Quicksilver"
ship "Marauder Quicksilver"
ship "Marauder Raven"
ship "Marauder Quicksilver"
ship Osprey
ship "Marauder Raven"
ship "Marauder Raven"
ship "Marauder Quicksilver"
ship "Marauder Quicksilver"
ship "Marauder Raven"
ship Firebird
ship Manta
ship Firebird
ship Firebird
ship Splinter
ship Osprey
ship Leviathan
ship Vanguard
ship Leviathan
ship "Marauder Quicksilver"
ship "Marauder Manta"
ship Falcon
ship Osprey
ship Manta
ship "Marauder Raven"
ship "Marauder Quicksilver"
ship Manta
ship "Marauder Quicksilver"
ship "Marauder Manta"
ship "Marauder Raven"
ship "Marauder Quicksilver"
ship Firebird
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Splinter
ship Manta
ship Quicksilver
ship Quicksilver
ship Firebird
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Headhunter
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Hawk
ship Quicksilver
ship Quicksilver
ship Firebird
ship Quicksilver
ship Manta
ship Headhunter
ship Headhunter
ship "Korath Chaser"
ship Manta
ship Firebird
ship Firebird
ship Firebird
ship "Marauder Raven"
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Manta
ship Splinter
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Splinter
ship Splinter
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Quicksilver
ship Vanguard

**Comment by Wrzlprnft** [comment]
I think it may be the sheer amount. Can you give us more information on your system? Esp. processor

**Comment by tomowad** [comment]
MacBook Pro (Retina, 15-inch, Mid 2014)
Processor: 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel Iris Pro 1536 MB

OS X 10.11.4

**Comment by Wrzlprnft** [comment]
Hmmmm. Would have been too easy.

**Comment by tomowad** [comment]
I typically run ES full screen on an external 1900x1200 display. I tried using a small window rather than the whole screen, but it made no difference.

**Comment by Gkramme** [comment]
Sell your quicksilvers and other ships, and buy some heavy warships. That should reduce your lag.

**Comment by tomowad** [comment]
I've been thinking about doing that. I should clarify that there's no lag, however - the game just suddenly freezes mid-fight. The screen freezes, audio freezes, and I have to force quit.

Wrzlprnft: that's a good question. It's never happened when the heart of the battle is off screen, but it's very rarely been offscreen, too.

**Comment by Gkramme** [comment]
It just may be that all the ships suddenly overload the game and crash it. I still would recomend selling your ships and buying a few heavy warships (Sheild Beetles prefeberly). If that doesn't work, it is probably an internal issue.

**Comment by Wrzlprnft** [comment]
The question is: is it a game engine-, a processor load- or graphic load issue. I would say graphics.

**Comment by tomowad** [comment]
I'm leaning towards graphics as well. What I've been doing is hovering the whole fleet of a hundred right on top of the planet. So a hundred ships stacked on top of one another start blasting everything the moment a ship emerges from the planet.

I was not able to move my ship away in a manner that would be useful for testing. If I move off, the fleet follows me, and then they're not all stacked up there at the planet. If I tell them to hold position, it eliminates all the movement.

**Comment by LocalGod79** [comment]
if you are running the high dpi plugin, try removing it.

**Comment by tomowad** [comment]
I'm running no plug-ins.

**Comment by tomowad** [comment]
I should clarify that this doesn't actually bug me too much - I just thought it was worth reporting.

**Comment by endless-sky** [comment]
Could you post your saved game? Then others could give it a try and check whether it's specific to your computer or not.
