### ISSUE TITLE
Shield Quadrants

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1099]
When it comes to top-down manoeuvring I've always missed having the concept of shield quadrants in EV, i.e- your shields would be divided up into four sections (fore, aft, port, starboard) and drained separately. If your aft shield is down for example then any further hits are against your hull, while hits from other directions continue to be absorbed by the relevant shield facing.

This gives more importance to manoeuvring, with fast ships able to pummel one facing of a ship, and encourages turning to take damage on stronger shields.

Personally I feel that most ships are too quickly destroyed, so I'd in favour of each shield facing be as strong as shields are now; a ship will die just as quickly if one facing is focused upon, but turning could prolong a slow ship's life. The other issue is whether facings should be equal; I'd like to see the addition of guns weaken aft and side shields by 5%, adding their strength to the fore shields, since ships configured with guns generally need to face the enemy to be effective.

**Comment by Gkramme** [comment]
This wouldn't make sense and would just make ships with powerful sheilds even more powerful. Like @jafdy said before, this is not EV. The game is not trying to be EV either.

**Comment by Haravikk** [comment]
> this is not EV. The game is not trying to be EV either.

EV didn't have this, I'm saying I wish it had, and think that Endless Sky would benefit from it. It would only make shields more powerful on ships that turn to absorb fire on less damaged sides, punching one side would be no different from how it is now.

The only problem really is that ships can currently jump away at any point in a system, I've mentioned in the Ship Density issue that ships should really need to get to a minimum distance, as this would make it harder for enemies to flee once you bring their shields down.

**Comment by Amazinite** [comment]
They can jump from any point, but only if they are facing in the correct direction and have slowed down to the correct speed. It is highly possible to stop ships from warping by shooting at them with certain weapons that push them around and make them have to continually readjust their trajectory. Such weapons include particle cannons, proton cannons, missiles, and a few others that have hit force. Laser based weaponry won't disrupt a ship's jump capabilities.

**Comment by Amazinite** [comment]
This is a duplicate of #876, which also suggested shield quadrants. I just don't see how this could work, as it's already pretty easy to get a large warship turning as fast as a small interceptor, completely nullifying the point of this being to give small ships the upper hand.

**Comment by Gkramme** [comment]
This actually makes the origional problem worse because it exponetally increases the sheild strength of ships, making larger ships _harder_ to destroy, and not giving small ships any sort of advantage whatsoever.

**Comment by jafdy** [comment]
Its half a duplicate. As @Amazinite said large ships can turn as fast as small ones. The game would need a dramatic rebalancing in the direction of slow large ships. It would almost be a different game . . .

**Comment by Haravikk** [comment]
> This is a duplicate of #876

Is it? That issue looks to me like it just wants visible shield impacts, i.e- a Star Trek style shield impact effect when you hit a ship with active shields. At least that's how I interpreted it when I searched, I think the image was just a confusing example since MOO2 has shield facings in addition to showing shield strength.

> I just don't see how this could work, as it's already pretty easy to get a large warship turning as fast as a small interceptor, completely nullifying the point of this being to give small ships the upper hand.

The point isn't necessarily to give smaller ships the upper hand, besides, to get that kind of manoeuvrability on a big ship requires a lot of investment in credits and space, especially if it's just to turn shield arcs faster (if you do it to bring guns to bear then you'll be mostly using the front arc anyway).

It's more about the extra depth it adds to positioning, especially for slower ships reliant on turrets.

> This actually makes the origional problem worse because it exponetally increases the sheild strength of ships, making larger ships harder to destroy

When taking damage from one side a ship would be just as easy or difficult to destroy, the difference comes in when a ship can turn away from damage while continuing to fire (i.e- has turrets) as it can turn undamaged sides towards the attacker. Or if a ship is surrounded it won't go down as quickly since it'll be taking damage on all sides rather than just one or two.

**Comment by Amazinite** [comment]
>It is?

>somewhat suggested

**Comment by psychiclegume** [comment]
> When taking damage from one side a ship would be just as easy or difficult to destroy, the difference comes in when a ship can turn away from damage while continuing to fire (i.e- has turrets) as it can turn undamaged sides towards the attacker. Or if a ship is surrounded it won't go down as quickly since it'll be taking damage on all sides rather than just one or two.

This just makes it harder for the player to be destroyed, as an AI opponent will try to keep the nose of the ship pointed at the target, nullifying the shield benefits, and making it more vulnerable then before.

It is also is heavily biased in favor of ships that have massive turrets instead of fixed guns, such as the Dreadnought and other late-Free Worlds models that use Plasma Turrets. If the player had one of these, they could keep the ship turning to reduce shield damage, while still firing your main guns and possibly pelting the target with missiles. If you only had guns, like a Manta or Vanguard, you would have to keep one set of shields pointed at the target.

**Comment by jafdy** [comment]
Think about a Atomic equipped Bactrian with plasma turrets (or any other powerful turret). 
AI controlled no major difference, player controlled about 4 times tougher.

Now think about a Vanguard.
AI controlled no major difference, player controlled no major difference.

In addition to avoid over balancing in favor of the player AI ships with lots of turrets will need to start spinning. Yep that would look so good, I can see it now, a screen full of spinning ships doing battle.

**Comment by Haravikk** [comment]
> If you only had guns, like a Manta or Vanguard, you would have to keep one set of shields pointed at the target.

I mentioned this in the initial post when I suggested that equipped guns could cause shields to balance in favour of the front. This could just be a default for AI and new ships though, as player screen support could let the player redistribute their shields how they like, but with some kind of limit (to prevent them dumping all shields onto the front for example).

> In addition to avoid over balancing in favor of the player AI ships with lots of turrets will need to start spinning.

No, they'd need to detect when a shield facing is becoming too weak and attempt to manoeuvre it away from the enemy, which would be appropriate and IMO would look good.


On the issue of balance I did forget about regeneration; I was thinking it would make sense for this to be split between all damaged shield facings, so if only one facing is damaged it regenerates at full speed, but if more are damaged they will all regenerate slower until some reach full strength again.

It also doesn't have to be quadrupled shields as such; the total could be less if they instead redistributed somehow so that a single shield facing remains roughly as tough as they are now, e.g- by draining other facings slowly (not fast enough to give one facing a super shield).

The key point is that I'd love to see shield quadrants as it's added a lot to games I've played that had them.

**Comment by jafdy** [comment]
>It also doesn't have to be quadrupled shields as such; the total could be less if they instead redistributed somehow so that a single shield facing remains roughly as tough as they are now, e.g- by draining other facings slowly (not fast enough to give one facing a super shield).

That is a contradictory paragraph. The effect is the same ether way just one way ships die faster.

>No, they'd need to detect when a shield facing is becoming too weak and attempt to manoeuvre it away from the enemy, which would be appropriate and IMO would look good.

True but the AI for simply spinning would be much simpler.

>The key point is that I'd love to see shield quadrants as it's added a lot to games I've played that had them.

The key point is that _**YOU**_ would like to shield quadrants added. The game moves to fast, if it moved 60x slower the maybe.

**Comment by Wrzlprnft** [comment]
I think this game is too fleet based and less flagship centered for that idea.

As our quite salty @jafdy said, it would be quite complicated to add in the current state of the game, and don't bring thaaat much. don't get me wrong, shield quadrants are a nice thing, esp. on player controlled ships, adding depth to combat (  e.g. star trek online benefits a hell lot of that), but for this game, it wouldn't fit. At least not the player has a better option to control his fleet so he can focus solely on his ship.

**Comment by jafdy** [comment]
I do try to be nice by I tend to fail spectacularly.

**Comment by Wrzlprnft** [comment]
Nah, it's okay :)

**Comment by Amazinite** [comment]
*sees thumbs down emoji*
Holy hell I'm dying.

**Comment by Haravikk** [comment]
>  shield quadrants are a nice thing, esp. on player controlled ships, adding depth to combat ( e.g. star trek online benefits a hell lot of that)

Star Trek online is a good example, as it can get pretty fast-paced (ships can die very quickly) and involve a lot of ships. I get that it's more player-ship focused, but I still think it could add to the game.

The current speed of combat has been mentioned in terms of quadrants making more sense if combat were slower, but that's kind of circular, as full-strength shield quadrants would slow down the rate at which ships are killed (I hasten to say it'd slow the game down, as I think combat would still be action packed). I also think that having the AI peel away as shield facings fail could lead to some good fleet behaviours as currently it's usually too late by the time an AI ship has decided it's had enough, by turning away it would present its rear shield, survive and potentially rejoin the battle elsewhere (or be able to get away).


Even if it's not a fit for the main game, is it something that could be added for modding purposes? Are the modding capabilities enough to add something like that? I haven't had a chance to fully investigate them. If the engine can support it (or could be made to in future) I think it'd be a great capability to have for the future. In the main game it could still be a cool feature to have if heavier classes of ship are added; e.g- big "boss" type ships that are like fleets in their own right, shield facings would be a great way to implement these without them simply being enormous damage sponges.

So I think it'd be a good capability to have whether it makes sense for all ships or not.

**Comment by LocalGod79** [comment]
also, #504
