### ISSUE TITLE
Sound glitches on FreeBSD

### ISSUE THREAD

**Issue by AMDmi3** [endless-sky/endless-sky#11]
It runs fine on FreeBSD, however the only sounds I hear are creaking and scraping. openal-soft-1.16.0 is used.

**Comment by endless-sky** [comment]
Are the creaking and scraping sounds continuous, or only when a sound
effect would be expected (when you are entering hyperspace, or when a ship
is firing weapons or exploding)? The sound effects are kind of lame,
anyways, so you may just want to turn them off in the preferences for now
(click the bottom of the volume bar to set it to zero).

**Comment by endless-sky** [comment]
Can you try compiling and running the following program, to test if OpenAL is playing sounds correctly on your computer?

```c++
/* To run this program:
$ g++ al_test.cpp -o al_test `pkg-config --cflags --libs freealut`
$ ./al_test path/to/sound.wav

You should hear the given sound file play in a loop, moving from your left
speaker to your right speaker as if passing by you.
*/

#include <AL/alut.h>

#include <iostream>
#include <cstring>
#include <unistd.h>

using namespace std;

int main(int argc, char *argv[])
{
	if(!argv[1])
	{
		cerr << "Usage: $ al_test <wav file>" << endl;
		return 1;
	}
	alutInit(&argc, argv);
	
	ALuint source;
	alGenSources((ALuint)1, &source);
	
	alSourcef(source, AL_PITCH, 1);
	alSourcef(source, AL_GAIN, 1);
	alSource3f(source, AL_POSITION, -10., 0, 0);
	alSource3f(source, AL_VELOCITY, 0, 0, 0);
	alSourcei(source, AL_LOOPING, AL_TRUE);
	
	ALuint buffer = alutCreateBufferFromFile(argv[1]);
	cout << "Loaded buffer: " << buffer << endl;
	alSourcei(source, AL_BUFFER, buffer);
	alSourcePlay(source);
	
	for(int i = -1000; i < 1000; ++i)
	{
		alSource3f(source, AL_POSITION, i * .01, 0, 0);
		usleep(5000);
	}
	
	alSourceStop(source);
	
	alDeleteSources(1, &source);
	alDeleteBuffers(1, &buffer);
	alutExit();
	
	return 0;
}
```

**Comment by AMDmi3** [comment]
Thanks for the hint! It turned out that openal-soft was miscompiled by clang, so sound was broken in all openal-using applications. After openal's fixed sounds play correctly.
