### ISSUE TITLE
[balance] androids

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1100]
the ability to reduce/eliminate one's crew salaries, in spite of their expense, still seems somewhat unbalanced. (as it removes the inconvenience of erratically moving flagship when you've captured too many ships, and enables the capture of even more without said inconvenience - 70 or so *extra* Furys in a Bactrian)

from my own testing on a bunk-use model within my plugin, i found that adding:

`      "energy generation" -0.1`

scaled very well with ships - larger ships with huge power-plants were more easily able to cope with large numbers of them.

adding this attribute would fit canon (where are these androids getting their energy?), and introduce a tiny secondary tonnage requirement (through added power/cooling requirements).

edit (after three thumbs up); with this addition, you could probably nerf the cost back down to where you had it for 0.9.0 (30k)

edit2; i'm going to add this to #1002, as it's almost finished, and should probably be merged as a part of 0.9.1 (as an "unstable" test of that content).

**Comment by endless-sky** [comment]
Outfits with negative energy generation (currently, just the shield regenerators) cause a huge amount of confusion for beginning players, and annoyance even for people who aren't beginners, because you can't sell all your generators if you have one of those outfits installed.

**Comment by wambat1** [comment]
another issue i have noticed with the androids is that they can be purchased for the automated Kor ships. if a Kor ship is equipped with turrets that would normally be manned, this enables you to hire an android for that turret despite the fact that the turret would not otherwise require crew

**Comment by LocalGod79** [comment]
@endless-sky; while i agree with you that negative energy has caused confusion in the past, this outfit has fielded a couple of posts on Steam all by itself already.

that said, part of the hassle of those shield generators is the outfit space that one needs to reserve while swapping power plants (which one presumes differ in size).  the androids have no such requirements.

i feel like sacrificing balance for convenience at the moment, may make sense - but you must acknowledge that the current formula is certainly incomplete.

for the record, i believe that this might introduce the "negative attribute" mechanic to new players sooner, and give something for the ravening hordes to chew on.  at this point, players seem to be figuring it out without too much difficulty (the most recent post that i could find about this problem was 23Nov2015).

**Comment by Amazinite** [comment]
It's never fun getting the negative attributes message and not knowing why you're getting it. Could it be possible to allow the message to specify what is negative instead of being like "Oh, SOMETHING is negative, and it could be any of these things. Or it could be something else, I won't tell you."

**Comment by wambat1** [comment]
i remember seeing posted a mod on steam that introduced color coding on the outfitter screen to show what was wrong with a ship; more importantly, which ship. i don't remember if this mod included other things, but if it had only that it would be an excellent thing to include in vanilla. i will try to find the link. 

    On Friday, May 20, 2016 4:30 AM, Amazinite <notifications@github.com> wrote:
 

 It's never fun getting the negative attributes message and not knowing why you're getting it. Could it be possible to allow the message to specify what is negative instead of being like "Oh, SOMETHING is negative, and it could be any of these things. Or it could be something else, I won't tell you."—

**Comment by wambat1** [comment]
i have looked through the steam forums for several hours now and cannot find that post. i remember that the developer of the mod posted a link to his mod as a response in someone else's thread, but i cannot find it now. anybody remember a mod like that and how to find it?

**Comment by LocalGod79** [comment]
might you mean #852 @wambat1?

**Comment by wambat1** [comment]
thank you, it was item 11 on the list. i saw him plug his mod on on Steam somewhere, but for the life of me i could not find it. unfortunately i do not believe it was a thread i had posted to. i think that one feature of all his mod is well worth including in vanilla. scanning through dozens of "storage" ships to find the one you forgot to put thrusters or something on is no fun.

**Comment by LocalGod79** [comment]
@endless-sky i'll also add that the androids already pose the risk of triggering the negative attribute check when a ship is wholly loaded with them, and the user tries to swap turrets.

**Comment by topromulan** [comment]
The androids enabled me to fairly capture a Korath Raider, not sure if that was intentional (it has some outfits without icons, not sure if player was meant to have). Anyway, looks cute in my fleet with the blue rings instead of red. Korath fruit loops.

**Comment by Alkallid** [comment]
I think these really need to have the new deprecation thing Jafdy of Gkramme or whomever is working on, because you can sell all androids back for full price, absolutely canceling out crew costs. Buy them along with a ship, pay nothing and get money back upon selling.

**Comment by topromulan** [comment]
Depreciation

Yep a work in progress it seems like it should be not so advantageous to have so may androids as it is right now. They could get more expensive. I don't know if I buy them drawing on the ship's power although that is feasible. Actually, yes maybe LocalGod's idea of them drawing on the ship's power is good. After all we have cell phone charger cases you just set on the charger and don't have to plug in. so the android might not have its own power source and require the ship's supply, that seems reasonable.

**Comment by LocalGod79** [comment]
wow, @Alkallid, just wow. two guesses - both wrong, and the referenced pull (with link *and* author) is four posts up...*and* you mixed up deprecation with depreciation?  our spazi/grazi has fallen...

i'd tag him, but there's no reason to spam jmhorjus about yet another issue that his pull at least partly addresses...

**Comment by Alkallid** [comment]
I have no idea what spazi/grazi is, buy man,


the feels is bad yo

**Comment by Amazinite** [comment]
1ff8e92

**Comment by Amazinite** [comment]
4abc9b8

**Comment by Alkallid** [comment]
Nuuuuuu

**Comment by LocalGod79** [comment]
it might come back one day with the energy requirement (or something else)...

**Comment by topromulan** [comment]
Sounds good. Maybe like a fractional amount of outfit space, or a support unit that requires a pittance of outfit space to drive n androids.

**Comment by LocalGod79** [comment]
the simplest solution is for it to take up a bunk, but mere crew replacement is an insufficient reward for losing such a resource...

#1247

**Comment by KiLEdEnNis** [comment]
I was looking for an issue but stumbled on this one, and I do have an idea for it
similar to bunks; android storages, which take up outfit space, but can haev a few androids stored inside which can take the place of crew members
for example, you buy an android storage that like 4 outfit space, but enables 6 androids or so (or the storage itself reduces crew requirement)
another idea is maybe a "control bay" of like 3 different sizes (small, medium and large), where the small one may take 5 outfit space and reduces crew needed by up to 3, medium is 12 space, and reduces crew needed by 9, large takes 25 space and reduces crew by 20 (this idea is from an old DS game I have, a control unit reduced crew needed)

I've had these ideas for a while and thought pasting them here could help creating a balanced alternative
