### ISSUE TITLE
ABOUT FREE WORLDS STORYLINE

### ISSUE THREAD

**Issue by MOZZIEJR** [endless-sky/endless-sky#1101]
I just dropped off Kayla on Klink and dropped Eyes back to Zug, how do I continue the storyline? I aborted the "Rat Pack" mission and the "Free Worlds Renaissance" mission, does this affect/terminate the storyline? Please advise. Thank you.

P.S. I'm combat rating 7 if that helps.

**Comment by jafdy** [comment]
To get into the story line proper you need to do Katya's line and some of the others as well. Unless you have dropped too many missions you will get the mission at some point. 

p.s. did you do the "Thousand Eyes" missions for the defense pact?

**Comment by mdsmestad** [comment]
Um, this really isn't the right place to post this kind of discussion. Post one the Google discussions board under general https://groups.google.com/forum/#!forum/endless-sky/categories and close this discussion.

**Comment by endless-sky** [comment]
Yes, please only use the issue tracker for bug reports and feature requests.
