### ISSUE TITLE
Bug?: Unexplored Systems showing links

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1102]
If there are a number of unexplored systems near you that have links to each other, you can shift click the systems to show those links without actually discovering them.

![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/15412962/0b153456-1dfa-11e6-9b3b-7cf30f6430cf.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/15412921/bd4a78da-1df9-11e6-9552-5514112185c1.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/17688683/15413002/6a2c8520-1dfa-11e6-8edd-429b066a6c71.png)

Not sure if this is intended or not, but I would think it wouldn't be.

**Comment by endless-sky** [comment]
I can't seem to duplicate this - if I click one unexplored system and then shift+click another that is linked to it (but the link is not explored) the game picks a path using only the systems I know about. What version are you running?

**Comment by Gkramme** [comment]
Could this be because that map is custom made?

**Comment by Amazinite** [comment]
I'll attempt to test this on vanilla systems tomorrow when I'm back on my computer. 

I am currently running the latest steam version, v0.9.0 unstable.

**Comment by Amazinite** [comment]
It would appear that this is occurring only when a jump drive is installed

**Comment by endless-sky** [comment]
The jump drive lets you plot a jump between two unexplored systems because in almost all cases, if you can jump between two systems it's because they're within the jump drive range of each other, and if you know the positions of the two systems you know whether they're in range. On the normal map you never have hyperspace links this far apart, so people will seldom encounter this. 

I suppose I could change the rule to say that jump drive route planning between unexplored systems can only use links that are within the jump range, though.

**Comment by Amazinite** [comment]
The only triangular jumps that look big enough to replicate this in the vanilla game are in Wanderer space, and I don't even believe you could get your ship in a position to cause this to occur anyways without spawning your ship at one of the systems, as otherwise you would reveal too many paths and the bug wouldn't be noticeable. So not really a top priority thing, I guess.

**Comment by endless-sky** [comment]
Fixed in commit 7ae0c1d.

**Comment by Amazinite** [comment]
Nice.

**Comment by Wrzlprnft** [comment]
Lol. Seems like that plugin was more useful than i thought.
Github.com/wrzlprnft/world-forge

**Comment by Amazinite** [comment]
Closing because v0.9.1 is out.

**Comment by Amazinite** [comment]
Can confirm fixed.
