### ISSUE TITLE
[enhancement] Configurable Number of Autosaves

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1104]
So it's great that the game auto-saves when leaving a planet, however I would really like to be able to keep a few more auto-saves, especially during the early game when a loss of a fleet ship can be a huge set-back.

In some of the more chaotic missions it's easy to miss a ship's destruction in the rush to land, at which point taking off again means that that ship is gone if you don't take frequent snapshots. Retaining an extra auto-save or two would allow for easier jumping back in these kinds of cases.

**Comment by Amazinite** [comment]
#848

**Comment by wambat1** [comment]
i just tried to implement this; #848; and the following three lines, which i have tried to change, revert to what follows each time i load regardless how i change them in my preferences file:

"window size" 1436 764
zoom 100
"save backups" 1

i was able to change "fullscreen 0" to "fullscreen 1"

**Comment by Amazinite** [comment]
I think that would be something to bring up on the PR itself.

**Comment by wambat1** [comment]
ok, i will not be able to do so until tonight. not urgent; i did really want to make changes; just fiddling around to see what would happen. 

    On Saturday, May 21, 2016 6:31 AM, Amazinite <notifications@github.com> wrote:
 

 I think that would be something to bring up on the PR itself. —

**Comment by endless-sky** [comment]
Fixed in 8e94c82.
