### ISSUE TITLE
[documentation] Race Tiers

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1105]
I've noticed that the new Pug warship, said to be "on par with the Quarg," is a Tier 3. Does this mean humans are Tier 2? And what Tier would the Drak be?

What I'm asking for is a list of what Tier the different races are. It'd be interesting to see, and it would allow people to, in plug-in descriptions, state "adds a new tier-2 race," or "adds two new races, a tier 3 and a tier 4."

**Comment by IFailAtGaming** [comment]
https://groups.google.com/forum/#!searchin/endless-sky/tier$203/endless-sky/bdBvklrIoPw/hhAgFR-jEAAJ

**Comment by toilethinges** [comment]
@IFailAtGaming, thanks for pointing that out to me. Still, that's buried somewhere under the google group, and it would be very helpful to be put into the wiki.

**Comment by endless-sky** [comment]
Added to the [Story Ideas}(https://github.com/endless-sky/endless-sky/wiki/Story-Ideas) wiki page, because that's the one place where "spoiler" information is stored right now.
