### ISSUE TITLE
ridiculous Quarg engines

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1107]
i have had an idea about the description for those ridiculous Quarg engines:

"our human engineers have not been able to rig these thrusters to operate at anything near the efficiency observed when mounted on their native ships; however, the great demand for examples of this advanced alien technology for study have driven up the market value of these otherwise impractical engines."

anybody who wishes is welcome to make use and alter as desired.

**Comment by endless-sky** [comment]
Quarg tech is basically a placeholder right now. Once the whole galaxy is populated with aliens of various technological levels, the Quarg will need a complete overhaul to make sure they're still the most advanced and to make their outfits balance better with the other species. So until those other aliens exist, making modifications to the Quarg is a pretty low priority.

**Comment by wambat1** [comment]
i hope it is helpful to appreciate that is not necessarily the case that humans will be able to make alien tech work as well as it would for the aliens who understand the technology. that position, i think, gives some more flexibility in content creation. 

    On Saturday, May 21, 2016 7:58 AM, Endless Sky <notifications@github.com> wrote:
 

 Quarg tech is basically a placeholder right now. Once the whole galaxy is populated with aliens of various technological levels, the Quarg will need a complete overhaul to make sure they're still the most advanced and to make their outfits balance better with the other species. So until those other aliens exist, making modifications to the Quarg is a pretty low priority.—
