### ISSUE TITLE
Game does not open

### ISSUE THREAD

**Issue by MrMarma1ade** [endless-sky/endless-sky#1108]
If I try to run the game (either steam or direct EndlessSky.exe) almost nothing happens. 
If opened with steam sometimes, for a very short time, a steam window shows up and then closes again, vanishing in the depths of the universe, and nothing happens.
Although the .exe shows up in the task manager for a second if started either with steam or direct.

Important: The game ran perfectly fine a while ago. I also reinstalled the game but nothing changed.
I really have no clue what to do.
Please help me!

**Comment by MrMarma1ade** [comment]
I downloaded the 0.9 Version and it works now !

**Comment by LocalGod79** [comment]
troubleshooting issues are better posted in the google group;
https://groups.google.com/forum/#!categories/endless-sky
