### ISSUE TITLE
[enhancement] Shield Systems Should Require Power

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1109]
So I was going to post an issue about giving the bulk freighter more cargo space, but I realised that cargo space that this could be abused by converting any added cargo space into outfit space then slapping on as many shield generators as you can fit/afford, since there is currently no downside to installing them.

I find it strange that shield generators don't produce heat or require power, and think that they should, as this would increase the cost of installing more of them, by requiring better cooling to cope.

I think it would make sense for them to produce different amounts of power when idle and when recharging the shields.

Anyway, with this modification there should be less of a balance issue with bumping the bulk freighter up in cargo capacity (800 seems more reasonable IMO) as currently it doesn't really have enough extra to compare favourably against the Behemoth which is a far better ship and still hauls a lot of goods.

**Comment by Wrzlprnft** [comment]
Shield generators do require power, once recharging.

**Comment by Amazinite** [comment]
What wrzl said. They only use power when in use. The shield generators are not what cause you to have a shield, they simply repair any shield that you have lost.

**Comment by Haravikk** [comment]
Really? Is this visible in the UI v0.8.11 UI somewhere? All I can find is shield generation and outfit space needed, nothing about energy requirements. If they have an impact on energy then it can't be very high as I've never noticed any significant drain under fire beyond the usual for my weapons/engines/thrusters.

If they do already have drain though then I suppose this proposal should then be that they should require more power and/or cooling, as the trade off doesn't seem to be very significant right now.

**Comment by toilethinges** [comment]
@Haravikk, no, not in v.8. It's on the wiki, though.

**Comment by LocalGod79** [comment]
in 0.8.x, all shield generators use 1 energy to repair 1 shields (except for the last few versions, where there are some alien generators that will use more energy per shield unit charged)

**Comment by jafdy** [comment]
I think `shield energy` was added as part of 0.9.0 it may be that it was added to all shied generators as part of that release.
@Haravikk If you want to help with developing the game you should use the beta steam release.
