### ISSUE TITLE
Improve chance to disable

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#111]
With a powerful fleet it's almost impossible to disable ships, even heavy warships. Maybe you can introduce a command "Attack to disable" where your fleet is reducing firepower when the target is nearly disabled.

**Comment by endless-sky** [comment]
Do you find that this is a problem even with a fleet equipped entirely with laser weapons? Your escorts should stop firing the moment the target is disabled, so equipping them all with beam weapons gives them much better control over how much damage they do.

**Comment by schlamar** [comment]
Well, I don't want to equip my complete fleet (14 ships) with beam weapons. I worked out a pretty good weapon mix (including Korath Grab-Strike, Pulse and Ion cannons and turrets) which covers almost every fighting situation very well but fails at disabling/capturing ships.
