### ISSUE TITLE
[fix/enhancement] Make Doombat Indestructible

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1110]
So I got the second weapon testing mission after being given a fleet of shiny new Free Worlds ships, figured I'd swing by Rust to check it out first, took off to find that the Doombat was a Fury and watched it be instantly destroyed.

Even after restoring a save, taking the fleet to fight the republic, ditching my own fleet in another system then fighting Doombat myself I found it very hard to disable the damned thing without buying a new ship with intentionally weak weapons.

Either it should be a much heavier ship, become disabled the moment its shields are down, or be indestructible, my preference is the latter. I believe the same should be the case for all unique ships that need to be disabled; non-unique ships are fine for the challenge, such as looting surveillance tech and electron beams, but when a mission can be failed I don't think it's good.

It's also not helped by the fact that the mission implies that destroying the ship isn't important (since it was hauled off a scrapyard), yet destroying it appears to have no alternative branch that I could find, like delaying the availability of the new weapon or whatever.

**Comment by LocalGod79** [comment]
the free worlds weapons testing missions assume that you are flying a medium human warship, rather than a kill-everything fleet (a reasonable assumption, for most players on their first or second play through).

perhaps park your fleet when you embark on those missions.

**Comment by endless-sky** [comment]
If you're specifically warned not to destroy a ship and you go after it with that amount of firepower, it's your own fault that it got destroyed. Making a ship that is magically indestructible would be very unrealistic, *and* it would eliminate some of the challenge of missions like this one.

**Comment by johndh** [comment]
You can park your own fleet, but if you have armed mission escorts with you, they will still blow the target away.

**Comment by endless-sky** [comment]
Mission escorts that are assigned to the player's government are actually a bug; I just tracked down and fixed the last of those in 91d5f5f. Mission escorts that belong to governments other than the player's won't attack the "Test Dummy" ship.

**Comment by Haravikk** [comment]
> If you're specifically warned not to destroy a ship and you go after it with that amount of firepower, it's your own fault that it got destroyed. Making a ship that is magically indestructible would be very unrealistic, and it would eliminate some of the challenge of missions like this one.

As johndh says I had no control over the mission escorts, and the weapon testing mission actually dumps you out of the planet without a chance to delay the mission, meaning my escorts simply blew away the Doombat away before I could do anything about it.

The dialogue heavily implies that destroying the ship would be no loss, but that I should try not to do it, which is the same as dialogue about fighting the Republic fleets; I destroy their ships all the time with no ill effects, so this goes against the precedent set. I think that having it be "indestructible" is perfectly realistic, it can be argued away as your gunners being ordered to disable the target or are set to fire on low power to simulate damage. Either way, the point of the mission is supposed to be to show off the new weapon surely? Mounting it on one of the weakest ships in the game and sending it in a suicide attack against the player, then failing them for destroying it isn't ideal IMO.

> Mission escorts that are assigned to the player's government are actually a bug; I just tracked down and fixed the last of those in 91d5f5f. Mission escorts that belong to governments other than the player's won't attack the "Test Dummy" ship.

That's great to hear! That said, even if it had only been my own fleet the result would have been the same; the mission dumped me out of the planet without a chance to back out or delay it, and the ship starts too close for me to jump away to ditch my fleet. This wouldn't have been a problem if the ship were something larger than a basic early game pirate ship that I've been swatting away dismissively for (in-game) years.

> the free worlds weapons testing missions assume that you are flying a medium human warship, rather than a kill-everything fleet (a reasonable assumption, for most players on their first or second play through).

Since when? I got offered this mission right before capturing Rastaban (iirc), which is a system full of Republic Cruisers covered in electron beam turrets; I barely survived it in my Vanguard and two Behemoth escorts, as the jump puts you right in the middle of the enemy fleet. I can't believe for a second that I was expected to be on my own in a medium warship at that point!

**Comment by endless-sky** [comment]
Did you accept a planetary defense mission at the same time, or something? The flamethrower mission itself doesn't force you to take off immediately.

**Comment by endless-sky** [comment]
Also, are you familiar with the "park" command in the info panel? Your comment about trying to get your fleet occupied in a different system makes me think maybe you aren't aware that you can just park them on the planet.

**Comment by jafdy** [comment]
You could also try beams. You need a lot of beam fire power to out right kill a ship by accident.
On a more related note, don't make the ships indestructible. It would spoil the missions.

**Comment by Bladewood** [comment]
> You need a lot of beam fire power to out right kill a ship by accident.

*looks at fleet with 128 skylances*
Is this considered a lot of firepower?

**Comment by jafdy** [comment]
Yes
