### ISSUE TITLE
[enhancement] Display Own Ship Stats in Shipyard

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1111]
I like how the shipyard screen lets me see the sale value of my own ships on the right, however it'd be nice if I could also see their detailed stats as well (such as shown on the Outfitter screen), as this would make it easier to compare new ships to those that I already have.

In fact, it might make sense to just merge the two. In other words, both the Shipyard and Outfitter sidebars would give detailed stats for ships in your fleet, plus their sale value, this way both sets of information are available in both of these locations.

**Comment by LocalGod79** [comment]
#852

**Comment by LocalGod79** [comment]
truly, you should try that branch (he needs more testers, and it's a worthy addition to the game) - what you're asking for actually clutters the interface somewhat, and makes the information that you'd like more readily accessible, slightly less so...

**Comment by Haravikk** [comment]
While it sounds like a great addition to the game, I'm not sure I see how it's relevant to this issue.

I want to be able to compare things like shield capacity, hull points, speed etc. of my existing ship(s) against one I'm considering buying. This information is display in the Outfitter screen just fine, but switching between them, or leaving the Shipyard to open the player info screen is cumbersome as it means flicking between them and remembering values for comparison, rather than being able to see them side-by-side.

It's possible there are other alternatives, like a ship for sale's stats could have coloured differences added that display whether a stat is superior/inferior compared against the currently selected ship in the sidebar. For example, say my flagship is selected and has 7,200 shield capacity, and I select a ship for sale that has 10,000, it would show a green +2,800 next to its shield capacity to show this difference.

**Comment by jafdy** [comment]
If you are comparing stock ships you could do it in the map, it is a bit easier. Comparing to personalized ships is a bit pointless as most of the time they are much better for you.

**Comment by Haravikk** [comment]
Maybe for turning, acceleration, shield generation and the like, but for things like shield capacity, outfit capacity, weapon capacity and other things that are "fixed" it'd be useful. I put fixed in quotes as I realise outfit capacity can be altered against cargo capacity, but that could be shown in the UI as a later update.

The map's Shipyard view is okay, but it's a bit awkward, I'm really looking for a side-by-side comparison, even if it's a little rough I'd find it useful. As you suggest, anything that you can upgrade isn't important anyway, but I'd like to be able to compare wasn't upgradeable more easily.

I suppose the Shipyard view could work if there was a way to select the base ships for comparison to see them side by side, perhaps with differences highlighted depending upon which you select. This would be more complicated to add as a feature though I think, compared to showing your ship's stats on the right sidebar of the Shipyard, which I'd still like anyway.

**Comment by jafdy** [comment]
For now you can use the general rule of shield beetles are the toughest and bactrian is the biggest.

**Comment by LocalGod79** [comment]
@Haravikk if you compiled the branch (as advised), and visited the shipyard, you would see this;
![screen shot 2016-05-22 at 9 48 48 am](https://cloud.githubusercontent.com/assets/16969517/15454285/7122cfc4-2002-11e6-8910-1ac28ed8ff80.png)

forgive me, but that looks *exactly* like what you're asking for...

**Comment by Haravikk** [comment]
> @Haravikk if you compile the branch (as advised), and visit the Shipyard, you would see this;

Aha! That's exactly what I'm looking for yes, sorry, the page you linked didn't mention any UI changes along those lines that I could see so I wasn't sure what the relevance was. Is that something that's going to be added to the main game, or is it only going to be available via custom compilation?

**Comment by LocalGod79** [comment]
for the moment, it's a custom compilation that is in development (and nearly completely so).

whether M.Z. actually plans to merge it or not, is known only by him...

**Comment by endless-sky** [comment]
Added in 4097b71:

![shipyard](https://cloud.githubusercontent.com/assets/11450262/15526981/0e8bd62c-2204-11e6-8bca-f46b8a95f63e.jpg)

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
