### ISSUE TITLE
Image Coordinates

### ISSUE THREAD

**Issue by evan153** [endless-sky/endless-sky#1112]
This is probably a dumb question, but I can't find anything. When making a new ship how do I get the coordinates for the parts? I tried Photoshop and other programs, but those show coordinates with the top left being 0,0 What programs and techniques do you guys use?

**Comment by endless-sky** [comment]
Load the @2x version of the graphic into the [ship builder](http://endless-sky.github.io/ship_builder.html). It lets you specify hardpoints and has a few other features as well (like letting you preview what the different color swizzles will look like).

**Comment by evan153** [comment]
Thanks!
