### ISSUE TITLE
refined interface for mission map and outfitter/shipyard windows

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1114]
both of these windows are currently suffering form lists which become inconveniently long. a helpful feature would be selective view. i imagine a short category list; maybe a drop down list; with check boxes which control what is displayed.

in the mission map we could have the categories:

![image](https://cloud.githubusercontent.com/assets/16410142/15452329/fa6d86e2-1f9f-11e6-9bb5-7aa77703a583.png)

i expect story missions should always be displayed. for the outfitter/shipyard window:

![image](https://cloud.githubusercontent.com/assets/16410142/15452323/c129c7f6-1f9f-11e6-89ea-454eb473d730.png)

drop down menus for these check lists might be best.

this would help pilots immensely.

**Comment by jafdy** [comment]
They already are drop down. Click the names to move them back up.

**Comment by LocalGod79** [comment]
Shipyard and Outfitter categories are not collapsing on planets, yet - only the sidebars on the map display...

**Comment by wambat1** [comment]
for the shipyard/outfitter screen, i am not concerned with what is for sale, but what the player already has. the column on the right hand side with the player's ships. it gets to be a pain when you have, for example, dozens of fighters sharing the screen with with your heavy warships, and you only want to deal with your heavy warship's outfits. if you could only display the ships classes you want to make changes to, this would make it easier for the player.

**Comment by Amazinite** [comment]
At some point we added the ability to collapse ship and outfit categories in all locations.

Missions can't be collapse, but we do have scrolling and sorting now that can help with a long list of missions.
