### ISSUE TITLE
[enhancement] more info in ship status overlays/target display

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1115]
e.g. heat load, energy level (i'd be happy with those two), and hyperspace fuel.

edit; perhaps as additional rings?

**Comment by wambat1** [comment]
for my part i should like to see the empty areas at the bottom right of the ship info window, and under the item/ship info on the right side of the outfitter/shipyard map view to e used to display the ship/item description currently only on view while docked at an outfitter or shipyard. this would more exposure to this entertaining content and would allow the player to view descriptions for things he has acquired, but has not yet discovered a shipyard/outfitter who sells it. it could still be empty for ships that are currently never in shipyards the player has access to, but would give the option of publishing descriptions for those ships as well, which is another opportunity to increase immersion.

**Comment by LocalGod79** [comment]
that sounds like a different issue entirely.

please confine your conversation to the subject of that issue (in this case, status overlays and targeting displays, rather than outfitter and shipyard user interface).

**Comment by endless-sky** [comment]
The reason I only show shields and hull is because it doesn't seem reasonable for the player to know what is going on "inside" a ship without special sensors. (Although, arguably, the ship's temperature could easily be measured from the outside.) I also wanted to avoid making the display too confusing for new players.

**Comment by LocalGod79** [comment]
okay, i can get behind energy and fuel not being in the display, without special sensors.

i think given that Meteor missiles have i.r. tracking equipment, it would not be unreasonable for ships to be equipped with i.r. sensors as well - perhaps just a reddish ring for heat?

had you considered adding support for outfits that did enable said overlay options?

i think that this also ties well into #352

**Comment by Pointedstick** [comment]
Ooh this would be so nice. To prevent confusing new players, the additional information could only be shown if you buy a special scanner ("combat scanner"?).

**Comment by KiLEdEnNis** [comment]
(battle scanner)
and it could also buff the useless surveillance pod

**Comment by endless-sky** [comment]
This has been added in da4e4c4.
