### ISSUE TITLE
[bug/content] M.M.K. can't take Korath heat.

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1116]
that is, he is in for a doozy if he happens to cross the player's path in Korath space (or indeed any of the future upper tier hostile aliens)...

would it be possible to limit where persons spawn?

**Comment by Amazinite** [comment]
Maybe make it that only cause persons to disappear forever if the player is the one to kill them, just so there aren't any situations where the player has no control and they end up losing a person.

**Comment by endless-sky** [comment]
See the ["creating persons"](https://github.com/endless-sky/endless-sky/wiki/CreatingPersons) wiki page. You can define a system location filter that limits where the person appears, using any of the same filters that missions and NPCs can use. For example, to limit MMK to human space you could just do:

```html
system
    near Sol 1 100
```

**Comment by endless-sky** [comment]
Also, the "Author" government is not at war with anyone except for Pirates, at the moment.
