### ISSUE TITLE
navy chatter

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1117]
i don't often pay attention to this feature any more, but tonight i noticed:

"join the navy, see the world!"

which world, i wonder? maybe "see the galaxy!" would be more appropriate, or at least "see the worlds!".

**Comment by LocalGod79** [comment]
"see the world!" is a very old u.s. navy recruiting slogan, which often painted a very different picture of life in the navy than reality.

while it may seem inappropriate to use "world" in this context, it's not technically wrong, and makes the historic reference (which makes it *very* right).

**Comment by wambat1** [comment]
"worlds" would include the historical reference as a pun, and recognize the in-game reality. in the classical sense the world was everything, but i doubt that interpretation of the word is likely to persist into the 31st century.

**Comment by endless-sky** [comment]
That whole phrase is feeling a bit awkward to me. Changing it to "worlds" would allow other variants like "Defend the worlds" and "Tour the worlds" that don't work very well, and "View the Republic" is kind of clumsy too. Any ideas for retooling the whole thing?

**Comment by endless-sky** [comment]
Fixed in #1140.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
