### ISSUE TITLE
[enhancement] Highlight Most Profitable Commodity in Map's List

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1118]
First up I want to say I love what's been done with trading in Endless Sky, it feels so much less like a chore than it does in EV thanks to the simplicity of finding good places to sell goods on your intended route etc.

However, at the moment I'm not really trading for its own sake but instead have some intended destination due to a story mission or other mission, and use the map to determine which commodity will be the most profitable in that system (or one on the way) so I can load up and head out to make some extra profit on the side.

This is fine, as it's usually fairly easy to pick out which commodity is the most valuable, but I think it would be useful if it were highlighted in some way, for example if the most valuable commodity (or its price difference) appeared in white, or even if they were all given a brightness based upon their relative value. I've added a super-simple mockup of the first of these (only the top commodity is brighter), but I think the graded option may be best.

![mockup](https://cloud.githubusercontent.com/assets/2184328/15453418/1d7a086e-200d-11e6-86c4-e7eb707d7af8.png)

After making this it occurs to me that hovering over or clicking on commodities also changes their colour, so it may make sense to apply this grading only to the price difference (the bracketed number) so that this is applied normally to the commodity name.

Anyway, the point is that it would be nice if the commodities were somehow highlighted based upon their relative value between the current and target systems, as this is usually what I need to see so I can quickly load up on the most profitable to cover my crew wages and make a bit of extra money while I go around saving the Free Worlds from disaster etc.

**Comment by lshart** [comment]
That would be a nice feature.  I think it would be even more convenient if you could buy commodities from the map screen as well, perhaps with some kind of "fill up on most valuable" button.

**Comment by jafdy** [comment]
I can't help but feel that it would detract from the interest of trading. If all the information is given to you color coded for your convenience you would never really look at what you are doing. More so with @lshart suggestion.

You can already click on commodities to see there relative price across the galaxy.

**Comment by LocalGod79** [comment]
hypothetical situation; i'm on a planet, and i have some goods i bought at "very low", and they're "medium" here, but the next system over, they're "high".

under your proposal, when i click the next system over in the map, it will highlight the commodity with the highest profit margin compared to the system i'm in - not the commodity i had already selected to find a more profitable destination for.

**Comment by wambat1** [comment]
@local: i think this is meant t be a convenience for hose who are trading incidentally; i.e.: the player is concentrating on story-missions, or has an escort mission, or s going to that system to buy a specific ship or outfit, and whats to ore easily see the most profitable good to transport to the system he is going to in any case. this would not be a primary tool for a dedicated trader.

I wouldn't mind it as it is currently quite difficult for me to make out the numbers as grey against black.

**Comment by jafdy** [comment]
Contrast is a slightly different thing (could do with being a bit brighter). If you can't compare the numbers them selves then you are probably looking for a school not a new game feature.

**Comment by LocalGod79** [comment]
@wambat1: i understood perfectly the first time - read it twice.

the point *i'm* making is that it is quite possible to play this game as a merchant, where commodity trading is *much* more than incidental - and i believe your suggestion might make that playstyle more difficult (and therefore even less attractive).

@jafdy there's no need for personal jabs - they're proposing a feature from their perspective, which they admitted was limited.

**Comment by wambat1** [comment]
i did get the impression that this game was trying to accommodate several play-styles simultaneously. as i rectal, the very first story mission offered in this game prompts the player to make just such an incidental trade as we are talking about. i am not sure it follows that if a tool is incorporated that helps one play-style, it necessarily detracts from another. the heat map seems to be very effective for dedicated traders, but less so for incidental traders. can we not accommodate the needs of both?

**Comment by jafdy** [comment]
If you know what system you are going to you can just look for the biggest +ve number. I'm not convinced that anything extra is needed.

**Comment by wambat1** [comment]
i think it has to do with legibility for those of us with less than perfect vision. there are other potential ways to address the issue: print size could be increased, contrast could be adjusted; color coding (green and red, say) for positive and negative values, which is the thing i have trouble making out.

**Comment by endless-sky** [comment]
It's always a tricky balance to decide how much information and annotation to display. If you provide too much, it becomes hard to interpret. And if the display has [too much decoration](http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00040Z) or too much color and contrast, that's also a problem.

**Comment by Haravikk** [comment]
> If you know what system you are going to you can just look for the biggest +ve number. I'm not convinced that anything extra is needed.

Because the commodities are always listed in the same order, the list is a mix of negative and positive values, and sometimes this are very close (e.g- one commodity is +38, and another is +39) so it can be easy to miss the highest.

Sure it's pure convenience, but I already know that I would benefit from it a lot of the time, and I'm sure there are others who do incidental trading like I do.

> under your proposal, when i click the next system over in the map, it will highlight the commodity with the highest profit margin compared to the system i'm in - not the commodity i had already selected to find a more profitable destination for.

By highlight I mean visually, this is why I remarked that my mockup is probably less than perfect as it doesn't disambiguate from having a value selected or hovered over, which I forgot about when I made it. It should look visually different as I don't want the selection to change or become non-obvious; the key point of the proposal is that I'd like to see some kind of visual indicator of the scale of profitability between here and there, I'm not really bothered about what the indicator actually is, I just wanted to give a few ideas. It could just as easily be some kind of dots or stars next to the more profitable commodities or something else entirely.

**Comment by jafdy** [comment]
>one commodity is +38, and another is +39

1 credit per ton. Why are you concerned about that one credit? By the time that's a noticeable amount of profit your profit is so large it is no longer a noticeable amount of profit.

**Comment by Haravikk** [comment]
> 1 credit per ton. Why are you concerned about that one credit?

Why aren't you? If that's the best commodity to buy then that's the one to buy, plain and simple. Maybe I've nearly bankrupted myself buying a new ship with loads of cargo space, and every credit matters, maybe I'm psychotic and bigger numbers quiet the voices in my head. Maybe every time I make an extra credit trading in ES I put a new mark on my wall and when the wall is full my mission here on earth is complete.

It doesn't matter; what matters is that I'd like a minor tweak to the UI to make it easier to distinguish the top commodities faster, and I gave a quick example of a case when the best option isn't always obvious right away.

**Comment by jafdy** [comment]
Nice rant.

> If that's the best commodity to buy then that's the one to buy

Yes but one credit, seriously.

>nearly bankrupted myself 

On a decent trading route one credit is 0.5% of what you other wise get. Besides if you only do incidental trading then it isn't your main source of income anyway.

>maybe I'm psychotic

~~Yes, maybe you are.~~
Then let it feel like an achievement when you find your extra one credit.

>Maybe every time I make an extra credit trading in ES I put a new mark on my wall and when the wall is full my mission here on earth is complete.

See above.
And maybe get a smaller wall.

>It doesn't matter

It dose. someone has to set the game up to that.

>I'd like

We've been here before.

**Comment by endless-sky** [comment]
If you took this reasoning to the logical conclusion, the game should just buy whatever cargo sells the best for wherever the player says they're going, and sell it automatically when they get there. There has to be some sort of balance between giving the player a sense of agency vs. just holding their hand the whole way and doing everything for them, and I think the current system already does that pretty well.

**Comment by wambat1** [comment]
could we address this as an "ease of access" issue? it seriously is difficult for me to make out the numbers, and plus and minus signs, and i should hope i do not have the worst eyesight among the players (though it would be my luck). it is a contributing factor to my not engaging in the trade feature very much. if we could make the numbers a bit larger and/or color code them i don't think that would require any less work on the part of the player, but would help him avoid headaches from squinting.

**Comment by Haravikk** [comment]
> Nice rant.

Seriously? You're basically implying that I'm playing the game wrong simply because I want to buy the best commodity for my destination, and what I'm suggesting is a feature to make that a little easier; the actual difference in value is irrelevant, I would like to see commodities highlighted by value, if a 1 credit difference is more valuable, then that *is the more valuable commodity*, maybe you don't care, but I'm not completely convinced that anything matters to you given your generally negative attitude towards every issue I've seen you post to.

> > I'd like
> We've been here before.

Meaning what exactly? I don't recall reading anywhere that the policy for issues is that only features people *don't* want will actually be implemented. I suggested this because I know for a fact that I would find it useful, maybe some people won't, but I fully expect that anyone else who trades incidentally like I do would also benefit.

> If you took this reasoning to the logical conclusion, the game should just buy whatever cargo sells the best for wherever the player says they're going, and sell it automatically when they get there. 

That's a pretty big leap from "I'd like the UI to do a little more to highlight profitability for me" to "I want Endless Sky to play itself". Besides which, there are cases where I won't want to fill my hold with the most profitable commodity, maybe I want to buy something that canonically I know a world would want more for RP reasons, maybe I don't want to fill my hold because I have some bounties I want space for looting disabled pirates. The UI tweak *is* a balance between helping and doing because it would reduce the time it takes to identify the "best" commodity, so I can get right to buying it if I want to, it's also useful if I'm clicking around several systems as I can quickly see what the maximum profit would be for those that I click on. I'd hardly call it hand-holding; on those grounds you might as well get rid of all the trading improvements, because colouring the systems is hand-holding too when a real trader should be drawing up their own maps of profitability… kind of works both ways.

Seriously, it's a minor UI tweak to make incidental trading a tiny bit smoother, I cannot for the life of me understand the sheer degree of negativity in some comments here. UI clutter concerns I can appreciate, but there are ways around it, like instead of grading by colour/brightness some kind of icon(s) could be used; like I say the important part is that the UI could show which commodity is most profitable a little more, exactly how that is achieved is entirely up for debate.

At the very least it would be nice to see commodities have a different visual appearance for positive/negative profit, but I still thing that degree of profitability is important too. The map already shows this in terms of recommending where I should buy/sell something, so this really is no different, it just benefits a different type of trading.

**Comment by Gkramme** [comment]
Guys, let's not be like the
| Hoardes of steamers
So, please, don't fight. Keep it on topic and adress the real issue at hand please.

**Comment by jafdy** [comment]
@Gkramme yes, your right. I'm just getting a bit irritated.

@Haravikk You can play the game the way you like but my feeling is this would not ad much to the game.

@endless-sky Contrast option? For people like @wambat1.

**Comment by endless-sky** [comment]
I think the option of increasing the zoom level addresses any legibility issues (unless your screen is so small that you're unable to zoom the display). Eventually, it should probably be possible to zoom the UI independently, though.

**Comment by wambat1** [comment]
i am using a laptop; 17in i think; resolution 1920 x 1080 dpi. currently i cannot change the zoom setting, even by editing the preferences; it changes back to 100% regardless.

**Comment by endless-sky** [comment]
Are you running in windowed mode, or full-screen? That resolution should be just high enough to allow you to run at 150% in full-screen mode. (That's the resolution I have, and I've tested it.)

**Comment by johndh** [comment]
Instead of highlighting the most profitable, would it make more sense to list the commodities in order of profit margin?

**Comment by Haravikk** [comment]
> Instead of highlighting the most profitable, would it make more sense to list the commodities in order of profit margin?

That could be a neat solution, the only concern there is wether people rely on the current fixed order of commodities (i.e- heavy metals and luxury goods are always the last two items etc.), but I tend not to personally.

**Comment by jafdy** [comment]
I prefer a stable order. As it is the most expensive are at the end. If the most profitable is moved to the top I would end up always buying food.
