### ISSUE TITLE
unused space in ship info tab and shipyard/outfitter maps

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1119]
for my part i should like to see the empty areas at the bottom right of the ship info window, and under the item/ship info on the right side of the outfitter/shipyard map view to be used to display the ship/item description currently only on view while docked at an outfitter or shipyard. this would give more exposure to that content and would allow the player to view descriptions for things he has acquired, but has not yet discovered a shipyard/outfitter who sells it. it could still be empty for ships that are currently never in shipyards the player has access to, but would give the option of publishing descriptions for those ships as well, which is another opportunity to increase immersion.

**Comment by LocalGod79** [comment]
that "column" is currently used for cargo contents (which can get quite lengthy if one is plundering outfits and capturing ships).

perhaps the ship description could be appended after the cargo contents.

i'm worried that scrolling might effectively make that UI ugly/awkward if the player accumulates a lot of cargo types, and selects a ship with a long description (a fairly likely possibility, given the desire to read the Marauder descriptions).

**Comment by wambat1** [comment]
maybe a pop-up button for the description so it is normally hidden on the ship info screen?

**Comment by psychiclegume** [comment]
Espesially for ships like the Korath, or Quarg, ships that can't be bought at an shipyard, and some have very interesting descriptions.

**Comment by LocalGod79** [comment]
ftr; #852 allows you to view ship hulls (and their descriptions) you've sold (and buy them back, empty)
