### ISSUE TITLE
Unable to repair escort ships

### ISSUE THREAD

**Issue by mbrickner** [endless-sky/endless-sky#112]
Issue: Damaged escort is immobilized.  When trying to hail for help, the merchant ships say "You don't seem to be in need of fuel or repairs".

I have a fleet of 4 cargo ships that I run cargo with.  One of the escorts was damaged and is immobile.

I can't make the escorts my primary so I am able to repair them?  Maybe I'm missing something?  I was able to workaround now by editing the snapshot and raising the hull to full heath.

Thanks for the great game!!!  Worthy successor to EV:N.

**Comment by seanfahey** [comment]
Try targeting the escort and then boarding it, that should repair the escort.

**Comment by schlamar** [comment]
Next (N) does not target escorts, but you can target it with a mouse click.

**Comment by endless-sky** [comment]
Shift + Target next also works, but yes, mouse clicking is easier.

>
