### ISSUE TITLE
accidental boarding

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1121]
i just had an unfortunate experience losing quite bit of farming time due to unintentionally taping the board ship button after pilfering some fittings (it is conveniently located right next to the "done" button). i can think of two ways to address this problem for players in future (well, three, we could do nothing and tell them sometimes life sucks):
1) give a warning window asking if the player is sure he wants to board if his chances of success are less than 50%.
2) allow the player to back out of a boarding action if neither the attack or defend buttons have been used yet.

**Comment by jafdy** [comment]
A subtle change so that you can always retreat if you use the defend button first round.
In the mean time you could try the `D` key when your done.

**Comment by wambat1** [comment]
sound advice.

**Comment by endless-sky** [comment]
In commit 9ee6c0c I've made it so that if you click "defend" immediately after clicking "capture ship," you end the fight without bloodshed on either side.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
