### ISSUE TITLE
Freya says that the wormhole closes, but it's still open

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1126]
After beating the Free Worlds campaign and after a few years of taking missions, I eventually ended up with a mission leading to Pugglemug.
When I landed, Freya says,

> There's no way to reopen that wormhole

but the wormhole is still there, as far as I can tell. I can enter it, and it still leads to the Pleiades.
I think this may have something to do with the fact that at the end of the campaign, I entered the wormhole before going to Pugglemug.
Or maybe it doesn't.
I don't know.
Thoughts?

**Comment by endless-sky** [comment]
That dialogue was left over from back when the wormhole closed permanently once you completed the mission. I later changed it to stay open (so players wouldn't end up with escorts stranded in the other galaxy) but only just now fixed the dialogue to match: fa862e7.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
