### ISSUE TITLE
Improve undermanned ship system

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1127]
Currently when you have a ship that is undermanned, you get the normal "erratic movement" message and you lose control of your ship for a bit. My thought is to make it so that instead of losing complete control, you lose control of certain things depending on the number of crew undermanned you are. 

Say you have a ship with 7 crew and 2 turrets. If you lose two crew then instead of losing control every few seconds, you just can't use those two turrets. Either that, or movement remains as normal until you start shooting and your crew has to split up to use the turrets. Further crew loss could cause things like a loss of steering every few seconds, or the movement controls aren't as responsive (your ship doesn't move exactly when you press your movement keys and may continue to move after letting go), instead of the current complete loss of control.

**Comment by LocalGod79** [comment]
erratic weapons is already a part of the algorithm, if i'm not mistaken.

i think the problem with "turrets stop firing" is that on a Heavy Warship a single turret is such a minor component of the entire crew compliment, that most players would rather take the extremely sporadic behaviour than completely lose a turret until they could land to replace a single crew member...at least i would...

**Comment by jafdy** [comment]
Less responsive movement would be less annoying than the dead stop we have at the moment. If you plan well you would be able to fly around about as well out of combat.

**Comment by Amazinite** [comment]
@localgod79 That's why I also mentioned about that second bit where your movement is not hindered until you get into combat and actually have to use the turrets. As of right now, it seems like your crew keeps running back and forth between the turret and movement controls when they don't need to.

**Comment by endless-sky** [comment]
The whole point of being under-crewed is that it's supposed to be a major penalty. Modifying it so that you can be under-crewed with less severe side effects would defeat the whole purpose.

**Comment by Amazinite** [comment]
I don't know if I would refer to these as being "less severe side effects." It's true that the first idea with missing crew just not manning the turrets gives a little leniency when under crewed, but the second idea of the movement controls being less responsive would be something that happens all the time, and thus would always hinder combat, as opposed to the current system where every few seconds (depending on crew lost) you just lose complete control and then everything is normal again. So things would be a little easier on the low end but harder on the high end. 

I guess I just think it's a good idea because I would rather have the illusion of control rather than losing control entirely.

**Comment by endless-sky** [comment]
The mechanics related to ship capture have gone through quite a few different iterations in an attempt to balance the economic payoff of capture compared to other ways of making money, and most experienced players still think that capture is way over-powered.  So, the only way I would make a change like this is if it makes being under-crewed even worse (say, you lose your turrets *and* you have equal or worse steering trouble to the current mechanics).

**Comment by Tadrix** [comment]
storywise, there are two serious flaws:

1. There isn't any way to, for example, arrest pirates and turn them to authorities. Or tow their ship to the nearest landable planet in the same system, if there is one. The only choice is kill them, or… kill them. Or watch someone else kill them. Pirates sometimes rave about being at the mercy of such a wimp, except, there's no mercy. Not even of a fair trial. But ok, it's just a game.
2. There's this narrative about asking my crew to do more than they signed for. This is BS. Yep, it would be a strong point for minimum crew (flight crew and gunners), but usually there's an extra crew. What else I would hire them for? They are basically marines. I'd be content to pay them double, or even quintuple if I'd be spared from hearing about asking too much. They are there to board ships. I'm paying for it. There isn't any other reason to carry extra crew.

**Comment by jafdy** [comment]
related: #1650 
I think this is a case of gameplay over realism.
