### ISSUE TITLE
Korath cargo?

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1129]
what is this? i cannot sell it or see what it does in the outfitter.
![image](https://cloud.githubusercontent.com/assets/16410142/15462024/82f1c508-2074-11e6-804a-3b536c4a9815.png)

**Comment by LocalGod79** [comment]
are you running any plugins?

**Comment by LocalGod79** [comment]
it's mission cargo

**Comment by LocalGod79** [comment]
when you click the "New Issue" button, a message appears telling you to check the guidelines for submission (with a link).

at the very top of said document is the below;

```
The issues page here on GitHub is for tracking bugs and feature requests. When posting a new issue, please:

• Check to make sure it's not a duplicate of an existing issue.
• Create a separate "issue" for each bug you are reporting and each feature you are requesting.
• Do not use the issues page for things other than bug reports and feature requests.
```

**Comment by wambat1** [comment]
thank you for the reminder. i had intended to post on Steam, but could not figure out how to post the picture. i did not realize that the cargo list would show all the cargo in my fleet. i thought that cargo was on the fighter specifically.

**Comment by LocalGod79** [comment]
yes, this post would have been more appropriate on Steam, or on Endless Sky's Google Group (where you can also easily upload screenshots and pilot character files);
https://groups.google.com/forum/#!forum/endless-sky
