### ISSUE TITLE
Cannot refuel stranded escorts

### ISSUE THREAD

**Issue by w0ntoan** [endless-sky/endless-sky#113]
How do you refuel stranded escorts? It seems impossible to do anything with them. No boarding, no hailing.

**Comment by endless-sky** [comment]
Change f91f77f makes it possible to refuel your escorts and allies: they will allow you to board them if they are entirely out of fuel and you're in an uninhabited system. Note that escorts will also request fuel from other friendly ships in system, but that is not much help if you are in the middle of nowhere.

**Comment by endless-sky** [comment]
This should be fixed in the latest release (0.8.4).
