### ISSUE TITLE
[bug] flotsam doesn't appear to be working

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1130]
since https://github.com/endless-sky/endless-sky/commit/73db708adcddb9adcd29d1df66905168a9890d60

**Comment by endless-sky** [comment]
It's working fine for me (it's being created as always, and I'm able to pick it up). Can you be more specific about what isn't working?

**Comment by LocalGod79** [comment]
sorry, yes - i apologize in advance, i've been compiling three different branches lately (not all of which contained the commit), and i just wanted to make sure i got everything straight.

flotsam was being generated, but pickups had stopped entirely.

they seem to be back...
