### ISSUE TITLE
[Balance] Quarg ships are very easy to kill with Korath disrupters 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1131]
They end up disabled with most of their shield intact. Especially the War Dragon. 
Using 16 disrupters, 29 slicers, 26 detainers,  only the detainers in range much of the time.

**Comment by Amazinite** [comment]
This was already brought up. Quarg hull is getting buffed in v0.9.1.

**Comment by jafdy** [comment]
Yup, OK.
