### ISSUE TITLE
munitions storage

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1136]
i had a request to remove munitions from the "sell all" feature, but it occurs to me that there might be a content solution: a munitions locker which takes up some reasonable amount of outfitter space and has a considerable munitions capacity; say, one or two thousand. it could basically be set up like the current launchers, but while it can hold missiles, it cannot launch them. it could then be used at local outfitters to resupply your fleet with non-local munitions.

**Comment by LocalGod79** [comment]
this was discussed in #928

**Comment by wambat1** [comment]
this issue is currently moot with the release of 0.9.1. my apologies for not reading the release notes more closely.
