### ISSUE TITLE
[bug] fleet 'holding position' no longer defends itself

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1137]
not sure if this is an intentional response to "i want to be able to tell my fleet to stop shooting" or a side effect of other recent changes.

**Comment by endless-sky** [comment]
I can't duplicate this: if I tell my ships to hold position, they still pick targets, turn to face them, and fire on them (while remaining stationary).

Is it possible your ships are somehow not managing to come to a complete stop, so they keep trying to steer instead of aiming at their targets?

**Comment by LocalGod79** [comment]
i'm not sure why bugs like these keep popping up and then disappearing - i'm not altering code.

**Comment by Wrzlprnft** [comment]
Are you building from your own branch or a copy/clone of the endless-sky-master ? You know your commit habits ;)

**Comment by LocalGod79** [comment]
i think these might be associated with GitHub Desktop updating the local branch from the Endless Sky master while XCode is open - even when i re-compile (even in different branches, enabling those feature sets) "core" behaviours seem to get a little buggy (apparently until the computer is restarted - restarting XCode doesn't appear to fix the problem).

my computer restarts every morning, so when i come back the next day to check a bug that i've reported that has comes back "unable to replicate", i'm no longer able to replicate it either...

**Comment by LocalGod79** [comment]
ftr; this behaviour takes place on "just captured" ships, that are not flying your swizzle yet.

**Comment by Alkallid** [comment]
I think that's because dangerously injured ships always flock to your ship without orders, and only fight when commanded to. They should still defend, however.
