### ISSUE TITLE
[bug] ships that set off their self-destruct don't count as killed (until landing)

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1138]
for mission completion purposes. (just had a two out of three Marauders blow up under me, and the mission is incomplete)

edit; both ships registered as destroyed upon landing, giving me the 'npc kill' dialog, and then immediately the 'on complete' payment dialog.

**Comment by Amazinite** [comment]
Wasnt this fixed in a commit for v0.9.1?

**Comment by LocalGod79** [comment]
yep - as i said in the edit, the completion dialog came up upon landing, rather than the (self-)destruction of the final Marauder bounty.

it's perhaps the behaviour is less "not present", and more "not as expected".

**Comment by LocalGod79** [comment]
yes, definitely "not as expected"...

if i land at the planet where the Marauder Bounty job was taken immediately after having had said ships s/d beneath me, the npc kill dialog appears *after* the government gratefully pays me one...

**Comment by endless-sky** [comment]
Fixed in dbdc9f9.
