### ISSUE TITLE
[mechanics] Destroying automaton ships should impact reputation

### ISSUE THREAD

**Issue by ubik2** [endless-sky/endless-sky#1143]
Currently, since the RequiredCrew is 0 for automaton ships, killing them doesn't have a reputation effect.
I think I'd prefer to use a combination of the ship value (which was used for the combat rating), and the required crew.
If this is a desirable change, I can make a pull request.
In my local build, I give one reputation point for each required crew, and one point for each million credits of ship value.

This change does make it easy to get friendly with one of the automaton factions (by killing their enemy). It also makes it easier to repair Quarg faction if you don't want to kill pirates.

**Comment by LocalGod79** [comment]
#1027

**Comment by jmhorjus** [comment]
I think it is intended to be impossible to become friendly with the automation factions.  
In order to maintain that behavior while changing the underlying system to respect ship value, we'd need to have additional support for making a faction permanently hostile based on something other than reputation, or having your reputation with certain factions vary only within a certain range.

**Comment by ubik2** [comment]
My first thought was that you can simply remove the "attitude towards" in the governments, so that negative actions against one faction don't benefit the other faction. This would cause the much larger issue that they would no longer fight each other though.

Another negative side effect is that attacking a drone now does have a permanent effect on the player's reputation.

It looks like this isn't a desirable change, and perhaps this issue should be closed.

**Comment by Alkallid** [comment]
Is there a way to make a mission that just says "reputation towards: Kor _", repeats, has no other requirements, and activates "on landing"?

**Comment by Amazinite** [comment]
Yes, you could make a repeating invisible mission that causes a certain government to always be negative towards you.
