### ISSUE TITLE
Rebalance fitting and cargo sizes to balance boarding.

### ISSUE THREAD

**Issue by sivael** [endless-sky/endless-sky#1145]
I find it extremely odd that You can fit 100m3 in a tiny ship and 200 in a much larger one.
It also contributes to an unbalanced effort vs reward where all You do is board ships and get rich superquick.

What I would prefer in this case is make a few classes of fittings - small, medium, large weapons; each with appropriate damage, tracking and accuracy stats.

For example - a small omnidirectional laser turret would take up say 10m3, be able to track small targets effectively and deal small amount of damage.
a medium dual laser turret would take up 25m3 and be able to track small targets effectively with double the damage of the small one.
a medium laser turret would take up 25m3 and be able to track medium targets effectively with 4x the small turret damage.

Then the cargo sizes - trading is already a very low margin operation and being able to carry 250m3 of stuff on a basic hauler would be tle *low* end for me, with 5k - 25k - 250k being progression for medium, large and freighter sizes.

Also, it should not be possible to steal reactors or shield generators from an active ship.
Weapon systems and cargo - yes, those are mostly external or easy to haul around.
Cooling ducts? shield systems? nuclear reactors? who is hauling that out? And during operation too?

It would also limit the *insane* profits from boarding and stealing stuff from ships that aren't defeated(the idea itself is IMO bad that you can grab whatever without killing off/bribing/etc... of the crew)
I'd prefer too if You could pay them off, or convince them to stand down. Maybe let them go if they hand over the turbolaser turret. Maybe they hand over a booby trapped commodity if they are evil?

After all of the above changes, each ship captured worth around 2M would yield say 200-300k in a volume of 150-200m3.
A comparable transport would haul 5k of goods and with a good margin of 50 each, would bring in 250k for say 6-7 jumps.

Boarding a ship and stealing stuff when others were shooting should require you to share in the loot as well.

**Comment by jafdy** [comment]
Your not making much sense, I think I understand what you are after. 
First, we measure everything in tonnes.
Second, this sort of thing has been brought up several times before and is one of the major balancing points of the game at the moment.

When you see can board and steal stuff from ships that aren't defeated, you can't. Ships you can board I will disabled meaning that it doesn't really work any more, shields already on a different circuit as they can be run about shield generator and life support can probably run off a separate small generator. Therefore none of the stuff that you can actually steal is in use.

The reason for not creating really large transports is because by converting all of the cargo room into outfit space they will be able to soak damage more effectively then any of the current warships. It would also mean that unloaded they would be more agile then some interceptors if they are still able to move when fully loaded.

In theory the balance between trading and looting is maintained by the relative safety of the two occupations. In all likelihood you will be completely safe trading your way across the galaxy, whereas looting ships is intrinsically dangerous as you are going up against ships that want to kill you.

Also was your suggestion about the laser turrets another thing on "space dodging"?

**Comment by sivael** [comment]
Okay, Yes, I believe I have convoluted my point above, so let's start again:
1. Volume/weight of the cargo and cargoholds
Cargo ships that can carry 100-650tons/metric tons/units of something are pretty small especially considering the ROI in buying them. I would want to increase the size as well as base mass of large craft to make it possible to haul 5k / 25k / 250k of a particular good at one time, which would start making sense investment-wise. Getting 162k for a long trip with 250 markup on an item in a bactrian is very low. Such a large ship should be much bigger and have much more cargo space. If I want to earn real money in space, I should be able to haul large quantities of merchandise. Mercantile profession should not be discounted as "the bad way to play this game" and punished by barely scraping by

2. Ships aren't defeated if they have crew onboard. A crew that can fight. That ship has non functional systems, but it doesn't mean that those systems are offline, or have the possiblilty of being extracted from the ship without meeting resistance from the onboard crew. Exception would be weaponry as it's external.

3. Converting cargo space into outfit space
Simply make a flag that this cargo space can't be transformed into fittings, or provide the amount of "convertible" cargo space as a stat. Problem solved. (eg. 5k cargo but only 50 cargo is convertible)

4. Agile unloaded freighters - all that needs to happen is an increase in mass of larger craft.
A fighter having a mass of 100t vs a beetle having a mass of 1400t? The volume itself hints at much higher differences - with a size factor of 5 the volume increases about 125 times so it sould be more like 100t vs 12500t and then the issue is gone.
Also, transport starships may be equipped with inertial dampeners which reduce the effective mass of cargo in physics calculations. Might be a module.
Another point is small, medium, and large thrusters and directional thrusters. They all have a progression of 5 - 25 - 100 volume for each and larger craft would frequently fit more than one thruster. So oversized fitting is a specialized build.

5. Risk vs reward:
Trading is not safe, contrary to what You're saying. If You jump into a system in a freighter and there is a combat ship there, you're dead - the missiles push you away and you can't outDPS or outtank them anyway.
Combat isn't at all hard if all You're doing is hunting for not-destroyed-by-navy ships, looting them and paying off your debt in one go.

6. Laser turret sizing:
What I meant here was for creation of different loot size for expanded cargo sizes.
But overall - this is a topic that hints at reduced chance to hit with big guns of smaller targets but it's mostly to faciliate having small, medium and large craft in your fleet with all of them being at least usable and not having a "bigger=better" mentality.
How it's resolved - by % to hit, evasive manuevers/whatever else is secondary to the aim - rebalance the outfit sizes in cargo space and outfit space.

**Comment by jafdy** [comment]
Ok I get it. 
What you can loot without defeating a ship's crew has come up before so technically that would be a duplicate point. The risk reward structure for looting ships and especially capturing ships has been discussed many many times and so far no satisfactory solution has been found.

Restricting the amount of cargo space that can be converted into outfits space is essentially the same thing as limiting the number of mass expansions you can buy. One of the principal points of balancing in this game is that the number of something you can buy is not limited providing you have the space/power/heat capacity and so on to have it in your ship.

Your laser turrets are basically space dodging. This is another thing that has come up before and the main conclusion was that if we included it makes the game look like it has terrible collision detection. The thing to remember here is that smaller ships have the most fighting power for the amount of money required by them.

Other than that most of your points seem to revolve around having each craft be orders of magnitude larger than the last size down. Such a change would be a huge thing in the context of this game so I'm not really qualified to make such a decision on it. Instinctively my feel is it is not for this game as to make a large transport ship balanced it would have to be expensive and if it was expensive you would also expect it to have decent defences. It could however lead to some interesting new fleet balances.

Personally I've never experienced dangerous trading and I also found it quite fun. In general when I'm not playing storyline mission capturing unbuyable technology or testing something I will be trading in commodities from one end of the galaxy to the other.

**Comment by jmhorjus** [comment]
@sivael Have you managed to build ES for yourself yet? Look for build instructions on the wiki. If you can build the game, you might try out the branch at #852 (jmhorjus:used_parts) or the more experimental (jmhorjus:econ_balance) branch. I have been slowly working toward what I consider a better economic balance over there for some time now.  It does not do all the things you are suggesting (making ship sizes "realistic", which may never happen and I'm kinda ok with it), but it does make changes that address some of your concerns.

**Comment by sivael** [comment]
@jmhorjus that is a very nice idea, will try that once I find a few moments to do so. Thanks:)
Will give feedback once I get there

**Comment by endless-sky** [comment]
The relative payoff of cargo hauling vs. other activities is already pretty finely tuned. In terms of how much of the player's time it takes vs. how much it pays off, the exponential star barge strategy is still a quite competitive way to make money - the only reason more people don't do it is that it's boring compared to capturing ships.

As for small vs. large ships, you can't reasonably expect a ship that costs 0.5M to be able to do much against a ship that costs 25M credits. Again, the ship prices have been very carefully balanced. If you want a small ship that can stand up to capital ships, you need a Korath fighter or a Wanderer ship.
