### ISSUE TITLE
[question] Should we be able to complete missions with hostile factions?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1148]
Say I am on a very important campaign mission (that does not exist yet and probably never will). The mission commands me to go to a Quarg ringworld. However, my reputation with them is negative (to be exact, `-50624.79`). Would it make sense for me to be able to land on the station? If not, how should we be able to complete the mission otherwise?

**Comment by endless-sky** [comment]
A mission can grant "clearance" to its destination planet or to all planets that match a particular filter. For example, that's how the main story line missions allow you to visit pirate worlds. You can also mark a mission as "infiltrating" meaning that you can land on the destination but you do not get access to any of the services there - as if you've landed secretly somewhere other than the spaceport.

**Comment by wambat1** [comment]
the pirate planet missions from the story line can assume that you  would not normally have clearance. can a mission b made to check whether or not the player has clearance and proceed accordingly?

**Comment by endless-sky** [comment]
If a mission wants to be absolutely sure a player can land somewhere, it needs to grant clearance. But, in the example in the original post, there's no way the Quarg would be willing to help a player who has destroyed so many of their ships, so it's reasonable for a player who has been farming the Quarg to be unable to complete the mission string. (Similarly, anyone who is farming the Wanderers would not be able to continue working with them.)
