### ISSUE TITLE
Player ship click zones are now smaller than the ship tiles.  

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#1149]
Clicking on the outer edges of a tile doesn't register.

https://github.com/endless-sky/endless-sky/blob/master/source/ShopPanel.cpp#L153

I don't think you need the .5 multiplier there.

(I noticed this while doing a somewhat tough merge of that code to my branches.)

**Comment by LocalGod79** [comment]
noticed irregular behaviour - "couldn't put my pointer on it"...

**Comment by endless-sky** [comment]
Oops. Well, I guess that's why it's called an "unstable" release. :)

Fixed in bc36f6f.
