### ISSUE TITLE
Ubuntu 14.04 Space is blank

### ISSUE THREAD

**Issue by ThunderSock** [endless-sky/endless-sky#115]
This bug has occurred two times since the October 6 update. What happens is the game runs normally when suddenly this happens: http://imgur.com/XP4hOEI . There is nothing whatsoever on the main game screen or the radar screen. I can hear weapons still firing but I never take damage. Ship targeting works normally, but I can't target planets that should be there. The map menu, communications menu and the main menu work. I can jump into other systems, but this does not resolve the issue. The only way I can resolve the issue is to reload from a save file.

I do not know how to reproduce this issue. In both times I was fighting pirates in uninhabited systems for ~5 minutes, before the bug happened. In the first instance I was using a shield beetle, and then I was using a kestrel.

![screenshot from 2015-10-08 13 42 05](https://cloud.githubusercontent.com/assets/14982889/10419296/33b3387a-7041-11e5-953e-28ab89e45652.png)

**Comment by endless-sky** [comment]
I'm running Ubuntu 14.04 and have not personally seen this bug happen, but
I've received one report of it happening on Windows. So, it probably isn't
OS-dependent. Was your ship being boarded, or boarding someone, when the
bug occurred? In the other report I got that seemed to be what triggered
the bug.

**Comment by ThunderSock** [comment]
I was not being boarded, and I was not boarding anyone. I suppose NPCs could have been boarding each other.

**Comment by endless-sky** [comment]
When you jumped to other systems while this bug was happening, would the
screen flash white like it normally does, or remain completely black?

**Comment by ThunderSock** [comment]
I will check for that if the bug happens again.

**Comment by ThunderSock** [comment]
When I jumped to another system under this bug, the screen did flash white like normally.

(This time I had my fleet with me. During the bug I could board my ships to refuel them, but they do not follow me into other systems like normally.)

**Comment by endless-sky** [comment]
Were your escorts visible, or was there still nothing at all showing up on screen? And, do you remember if your escort icons on the left side showed up?

**Comment by ThunderSock** [comment]
The escorts were still invisible, and the escort icons (with stat bars like fuel) were visible the whole time.

**Comment by endless-sky** [comment]
I think this was due to a bug in the boarding button handler, but I'll leave this open until I'm sure it's not happening anymore.

**Comment by endless-sky** [comment]
I haven't heard any reports of this in a few months, so I think it's safe to say it was fixed by the boarding bug fix.
