### ISSUE TITLE
[Bug] `require` condition seems broken. 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1151]
[errors.txt](https://github.com/endless-sky/endless-sky/files/286815/errors.txt)

I'm just getting errors when I try to use it.

**Comment by Amazinite** [comment]
The wiki says it only works on offer, but most of yours are to offer. The last one might be that you  @can't use it inside of a branch.

**Comment by jafdy** [comment]
No, the example uses the `to offer` check so I should be able to use it in a branch.

**Comment by Amazinite** [comment]
> For example, this could be used in the "on offer" phase to only offer a mission to players who have a Jump Drive.

**Comment by endless-sky** [comment]
The "to offer" clause only operates on condition variables (things that appear in the "conditions" section of the player file). The "require" keyword needs to be part of "on offer," instead.
