### ISSUE TITLE
The Chameleon turret mass is 32?

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#1152]
The Bullfrog's mass matches.

**Comment by LocalGod79** [comment]
@endless-sky i've already started making changes to the Hai outfits locally. the battery capacities are not quite balanced either.

p.r. to come.

**Comment by toilethinges** [comment]
On a slightly different note concerning the anti-missiles, the names kind of run over each other in the outfitter screen, and when scanning a ship, having multiple of one kind forces it to wrap.

**Comment by Alkallid** [comment]
Noticed that^

**Comment by LocalGod79** [comment]
#1159
