### ISSUE TITLE
Bug: Planet Indicators Movement

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1154]
The name and government indicators around planets don't move when a nearby moon is blocking the hostile and restricted markers.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/15620563/f2824908-2428-11e6-94dc-d6c675e2633d.png)

And this one makes it look as though it is only restricted and not hostile.
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/15620564/f3d5af0c-2428-11e6-948b-ce9fab5fcd26.png)

The indicator only moves when the moon would be blocking the name, but not the markers.
![screenshot_3](https://cloud.githubusercontent.com/assets/17688683/15620565/f5149086-2428-11e6-88c9-8d3b6aa72e6c.png)

**Comment by endless-sky** [comment]
I don't think this is worth changing - the hostility marker is not terribly important, because the color and the "you cannot land here" message already communicate the same thing.

**Comment by Amazinite** [comment]
Fair enough.

**Comment by Pointedstick** [comment]
Many duplicate reports; re-opening. Not a big deal, but it's something people seem to notice a lot.

**Comment by warp-core** [comment]
Can this be closed since #6857 was merged (f261828)?

**Comment by quyykk** [comment]
Nope, there's another similar issue but with the hostility markings (see description).

**Comment by warp-core** [comment]
Is the desired solution for the ring to appear above other stellar objects, as well, then?

**Comment by Amazinite** [comment]
As outlined by MZ, the little tick markers on the planet label circle really aren't that important. This was only reopened by Pointed because I equated the name not moving to the ticks not moving in various issues. So insofar as this issue became more about the name not moving, I'd say we can just consider it resolved.
