### ISSUE TITLE
Bug: Systems With Multiple Governments

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1155]
If a system has multiple governments within it and one of them is hostile towards you, the system itself shows up as friendly. 

![screenshot_4](https://cloud.githubusercontent.com/assets/17688683/15620703/ea22c610-2429-11e6-939d-52200874178b.png)

This was a situation where the Free Worlds were hostile, but Kraz had a modded other governmental station in it that was highly friendly, making the system appear to be low friendly.

Maybe systems should show the hostility of the ruling government in the system, in this case the Free Worlds.

Edit: This one shows the opposite effect, with the modded government being hostile. The system itself remains showing friendly.
![screenshot_5](https://cloud.githubusercontent.com/assets/17688683/15620756/3d4b7166-242a-11e6-96bc-e1b63b914b00.png)

**Comment by endless-sky** [comment]
A system shows up as friendly whenever it is possible to refuel there. In my opinion, knowing whether or not you will be able to refuel is more important than knowing whether there is an unfriendly planet.

The same logic works with restricted planets - as long as there's at least one planet that will let you land, the whole system doesn't show up as restricted.

**Comment by Wrzlprnft** [comment]
Maybe you could split the coloring up into "360/amount of planets of goverment x" and color that system that way in a additional map, so the player is able to look up multi government systema "just in case"
