### ISSUE TITLE
[question] Are you still supporting the map editor?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1156]
The last commit to the editor was exactly 1 year ago and there has only been 1 release :|

And when I posted https://github.com/endless-sky/endless-sky-editor/issues/6 , I waited for 4 days and nobody posted :(

Are you still developing the map editor?

**Comment by endless-sky** [comment]
Right now it's a low priority - the editor is good enough to do the basics, and I'm trying to focus on getting new releases of the game itself out. Since it's a completely separate code base, maybe some Qt programmer will come along who wants to pick it up and start making improvements.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky-editor/pull/9
