### ISSUE TITLE
The Kestrel version on the map is the non-custom version

### ISSUE THREAD

**Issue by ThunderSock** [endless-sky/endless-sky#116]
The Kestrel that is sold on Wayfarer is the correct one that I selected in the Kestrel mission (more shields), but the map screen only shows the unmodified Kestrel.
![screenshot from 2015-10-13 20 09 36](https://cloud.githubusercontent.com/assets/14982889/10471775/20abd00a-71e7-11e5-9ed9-97792bbc0672.png)

**Comment by endless-sky** [comment]
I've fixed this in commit f252f16. The fix will be in the next release, whenever that happens.
