### ISSUE TITLE
[Bug] Auto planed route is too long.

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1160]
Alheka to Almaaz with only jump drives. Direct, 4 jumps, 4 days. Through wormhole, 4 jumps, 5 days.

**Comment by Amazinite** [comment]
My auto planned route from Alheka to Almaaz is giving me the direct 4 day trip and not going through the wormhole.

**Comment by jafdy** [comment]
No, I have also got other routes that go though the wormhole for no reason.

**Comment by Wrzlprnft** [comment]
I had the feeling that my nav-computer likes that buzz of flying through a wormhole way too much, too. But i have no evidence.

**Comment by endless-sky** [comment]
The route-finding is based on amount of fuel needed, not amount of time needed. So, those two routes are equivalent, and as of 0.9.1 it will pick the "safer" one.

**Comment by jafdy** [comment]
I'm not convinced it is that much safer but it won't bother me all that much.

**Comment by endless-sky** [comment]
Fixed in 75beae2 by having wormhole travel count as a distance of 1 rather than 0 (to account for the fact that it takes 1 day of travel).
