### ISSUE TITLE
New buy into cargo bug

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#1164]
Sometimes, and I'm not sure if it's random ot something, when you sell a ship and go into the outfitter, you can buy into cargo with the space of the last ship you had. I sold a Shuttle, went to the outfitter, and had 20 tons of cargo. This also happened with a Met Tek Par.

**Comment by LocalGod79** [comment]
#1172

**Comment by endless-sky** [comment]
Commit 9c6b766 should fix this.
