### ISSUE TITLE
Mission "Wanderers: Hai Diplomat" on uninhabited Hai planets (Darkwaste)

### ISSUE THREAD

**Issue by ThunderSock** [endless-sky/endless-sky#1165]
I'm guessing this was an oversight - you can visit the governor's office on an abandoned planet? Reproduction in case I wan not clear: during the Wanderer first contact string, try to find a diplomat on Darkwaste, you talk to an official on an abandoned planet.

**Comment by endless-sky** [comment]
Fixed in 2c18486.
