### ISSUE TITLE
Aborting Drak mission?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1166]
(Or maybe any other mission, this is a weird one.)

I landed on a Wanderer planet and looked for a job. I took one, but then saw that the other, more profitable one, was then grayed out. I aborted the first job, and thought I was clicking the accept button on the second job (note, the two jobs are directed to the same system, so it should auto-select the next job), but instead, this appeared:

`Abort mission "Drak guarding Korath space"?` `Cancel` `OK`

I clicked cancel, the abort button remains. But then I selected another job, and the bug went away.

I am confused.

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/1/364043054110071818/

**Comment by endless-sky** [comment]
Fixed in commit 77ba03a. The issue was that there were some ways that an "invisible" mission could end up selected.
