### ISSUE TITLE
Wanderer Anti-Missile unavailable unless Autumn Leaf is bought.

### ISSUE THREAD

**Issue by kurzatem** [endless-sky/endless-sky#1167]
I think the title says it all, but I would hazard to guess that the anti-missile should be made available either at the same time as the Autumn Leaf or sooner.

**Comment by endless-sky** [comment]
Yes, looks like there was a typo in the data file. Fixed in 5546269, although I'll have to also find a way to patch it for players who have already upgraded to 0.9.1.

**Comment by endless-sky** [comment]
In 006cd6e I added a patch that will fix this for players that got the event with the typo.
