### ISSUE TITLE
board ship priorities

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1168]
currently the auto select priority for the board ship button seams to be:

disabled enemy > disabled ally > disabled escort

it seems to me it should be thus:

disabled enemy > disabled escort > disabled ally

**Comment by endless-sky** [comment]
You can press Shift+B to board the nearest disabled escort (as mentioned in the preferences panel). So, it's reasonable to assume that if the player is not holding down shift, boarding one of their escorts is the lowest priority.

**Comment by wambat1** [comment]
i am aware that player escorts are currently the lowest priority. i am suggesting that they should not be, but respect if this is not a shared view. 

    On Monday, May 30, 2016 8:10 AM, Endless Sky <notifications@github.com> wrote:
 

 You can press Shift+B to board the nearest disabled escort (as mentioned in the preferences panel). So, it's reasonable to assume that if the player is not holding down shift, boarding one of their escorts is the lowest priority.—
