### ISSUE TITLE
Particle cannons broken in 9.1 unstable release?

### ISSUE THREAD

**Issue by onnikyla** [endless-sky/endless-sky#1169]
I just tried installing eight particle cannons to my shield beetle. I have 2 boulder reactors and the best hai battery. The cannons dont shoot. i thought it might be the lack of energy but doest work with only one cannon ether. Any ideas why this is happening?

**Comment by Alkallid** [comment]
What about on any other ship?

Wait, did you buy into cargo?

**Comment by onnikyla** [comment]
no i installed them, Im not abled to try with other other ships at the moment because the free worlds storyline

**Comment by Amazinite** [comment]
I just used the same set up as you're describing and I'm able to fire them. Two Boulders, a Ravine battery, and eight Particle Cannons (as well as some Williwaw cooling).

**Comment by LocalGod79** [comment]
sounds like you forgot the battery/supercapacitor.

**Comment by toilethinges** [comment]
@LocalGod79 

> I have 2 boulder reactors and the best hai battery.
