### ISSUE TITLE
Selecting "Food" from the Map view doesn't translate back into the Trading view

### ISSUE THREAD

**Issue by willbeason** [endless-sky/endless-sky#1171]
To recreate:

1. Land on any planet.
2. Go to the Trading screen.
3. Select any non-"Food" commodity.
4. Press "M" to see the map with the trading overlay.
5. [Select "Food" from the panel on the left-hand side.](https://cloud.githubusercontent.com/assets/4982707/15643256/24acb6fa-2601-11e6-8646-fcdda7e810d5.PNG)
6. Click on "Done".
7. [The "Food" option is not selected on the trading screen.](https://cloud.githubusercontent.com/assets/4982707/15643259/24afba6c-2601-11e6-8806-b32b711a9e96.PNG)

The intended behavior is that "Food" should be selected. For example, [I select "Industrial" from the Map screen](https://cloud.githubusercontent.com/assets/4982707/15643257/24acca14-2601-11e6-875e-c10b38040623.PNG), when I go back to the Trading screen, [the state is preserved](https://cloud.githubusercontent.com/assets/4982707/15643258/24acecc4-2601-11e6-9e77-383cae4a094b.PNG).

**Comment by endless-sky** [comment]
Fixed in 17915d6.
