### ISSUE TITLE
[Bug] Can vanish outfits and money.

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1172]
http://steamcommunity.com/app/404410/discussions/1/364043054109777782/?tscn=1464605910

**Comment by LocalGod79** [comment]
#1164?

**Comment by jafdy** [comment]
No. Same area different bug.

**Comment by endless-sky** [comment]
This should be fixed by commit 9c6b766. If buying into cargo, it was not checking whether you had space for it before spending money on it.
