### ISSUE TITLE
Earth Shapers disabled

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1173]
the auto-select for the board selected ship button thinks all the Earth Shapers are disabled. this is quite annoying. it may be due to their having no fuel. maybe they can be given one bar of fuel. maybe an afterburner to justify the fuel, and a run-away-from-Unfettered-Hai personality.

**Comment by wambat1** [comment]
correction to previous observation:

not all Earth Shapers are considered disabled. only some. i cannot see why some are and some are not. it cannot be due to damage because the ones being erroneously selected are not always damaged.

**Comment by toilethinges** [comment]
Earth Shapers have 300 fuel, enough for three jumps, and a hyperdrive..

> it may be due to their having no fuel. maybe they can be given one bar of fuel. maybe an afterburner to justify the fue

**Comment by endless-sky** [comment]
Right now the player is allowed to board ships of friendly governments in order to refuel them if they are stranded. If that's the reason that the Earth Shapers are allowed to be boarded, then I'd prefer to keep that mechanic in place because it's useful for various missions where you have to escort other ships.

**Comment by wambat1** [comment]
the curiosity is that the board-ship command is acting like these ships are out of fuel.
a) they shouldn't be out of fuel. my observation has been that ai ships will not refuel other ships if doing so will reduce them to below one bar of fuel.
b) other ai ships are not refueling these "out of fuel" ships. again, contrary to my observations of ai behavior. btw, i cannot refuel these ships myself, and my fleet ships do not do so either.
it is particularly annoying as it makes it very difficult to navigate efficiently while trying to farm Unfettered Hai in Wanderer space. it has even caused me to accidentally go hostile to Wanderers when i was trying to blow up a disabled Unfettered Hai ship.
are some of these Earth Shapers spawned when entering the system and made to stay there. if so, maybe whatever is causing them to stay there is what is causing the this phenomenon. 

    On Monday, May 30, 2016 1:49 PM, Endless Sky <notifications@github.com> wrote:
 

 Right now the player is allowed to board ships of friendly governments in order to refuel them if they are stranded. If that's the reason that the Earth Shapers are allowed to be boarded, then I'd prefer to keep that mechanic in place because it's useful for various missions where you have to escort other ships.—
