### ISSUE TITLE
EXTREME lag in a Kor Sestor-Kor Mereti firefight

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1175]
It's... it's just horrible.
...and it's also probably just my crappy computer, but not even a fleet of jump drive-equipped ships jumping comes close to the torment experienced there.
Either the ship spam or the Kor Mereti's evil mine field spam is to blame.

**Comment by endless-sky** [comment]
Is it possible your computer only has 256 MB of VRAM? If so, have you tried installing the "low DPI" [plugin](endless-sky.github.io/low-dpi.zip)?

**Comment by endless-sky** [comment]
Also, if you turn on the "show CPU / GPU load" preference, is the CPU or the GPU showing a higher load? (>100 means it's lagging.)

**Comment by endless-sky** [comment]
I've got an improved collision detection algorithm in the works that should help speed things up, but it won't be in the 0.9.2 release because that release is just focused on smaller, "safer" fixes to the engine.

**Comment by Bladewood** [comment]
Now that I've actually had time to check on it, I've flown into a firefight, and CPU load is greater than GPU load.
Much, much greater.
CPU is 200%, while GPU is 25%.

**Comment by wambat1** [comment]
Mekislepti firefight is giving my system 260/40 with blur on; 150/25 with blur off.
here is some of my laptop's info:
![image](https://cloud.githubusercontent.com/assets/16410142/15809219/119f8db8-2b41-11e6-9789-c51f9ce377f6.png)
![image](https://cloud.githubusercontent.com/assets/16410142/15809224/1deea1e4-2b41-11e6-80ae-e27d7af88386.png)
![image](https://cloud.githubusercontent.com/assets/16410142/15809227/30865f22-2b41-11e6-8abe-6a9d69d1a01f.png)

**Comment by endless-sky** [comment]
My computer is not terribly fast (a Core i3-2100 CPU @ 3.10GHz) but with the latest code changes, especially optimizing anti-missiles, I can hang out in the busiest Sestor vs. Mereti system (Mesuket) and never see CPU use go above 100%. So, it's possible 0.9.2 will help you out a bit.
