### ISSUE TITLE
[balance] anti-missile turrets

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1176]
i apologize for the wall - this is mostly transcribed from a conversation in #1159 

a steam user has recently indicated that the *mass efficiency* of a/m systems should scale inversely to their mass, because of their turret mount occupation. after sleeping on the idea, i believe that he is correct (and that all a/m systems may require an overhaul).

an example (with numbers) that caused it all to fall into place in my mind;
2x16T anti missile turrets reloading every 8 frames with a/m 5 should be more effective than a single 30 ton Heavy Anti-Missile Turret (because the user has occupied more tonnage *and* an extra mount - a fairly valuable commodity), but it's not. 50% more "shots" with 62.5% "power" is a loss of 6.25% efficacy (and we haven't even factored the shorter range, yet).

this makes the heavy a/m turret a "no-brainer" choice (over two a/m turrets) - which by your own advice in the outfit wiki, is unbalanced.

at the end of the day, when an outfit is only limited by mass/capacity, smaller outfits *should* be less efficient than larger ones, because you could break the system by installing equivalent capacity in the smaller outfit.

when you introduce the turret mount as a requirement for defensive capabilities, it consumes a very limited and valuable hull resource - one that compromises the offensive capabilities of that ship far greater than the mass/outfit/weapons capacity usage ever could (therefore smaller individual a/m turrets should be slightly more efficient than larger more powerful ones in the same tech tier).

at first, i was also resistant to the idea, but the concept is solid;
if i use more of a very (arguably "the most") limited and powerful capacity type on my ship, i should be rewarded more, if all other things are (more or less) equal.

**Comment by LocalGod79** [comment]
from my matrix;
mathematically, this can be accomplished by changing the a/m *and* reload attributes of the human AMT to 7, and energy to 6 (to balance that efficacy boost).

mathematically, it's still worse on every spec than the HAMT, and every matrix except efficacy/mass - and even balances the efficacy/cost, which should have seen the HAMT closer to 180k or the AMT closer to 50k.

to boot, a pair of them still don't quite mathematically match "efficacy" of a single HAMT due to their shorter range (coming up ~6% short) - but this is bound to be made up for by better coverage - assuming the player spends the time distributing their turrets.

**Comment by LocalGod79** [comment]
also from my matrix;
the Pug tier 1 a/m would get a small reload bump to 3 (2), and energy cut to 7 (8) to keep the system consistent across the entire tier.

**Comment by wambat1** [comment]
i should like to see the effect of range factored into considerations. i don't think players factor in the significance of range nearly as much as is warranted for AM systems. a system with range 350 will, in effect, get  75% more chances to take down an incoming missile over an system with range 200, all other things being equal. and this is considering only the protection of the AM bearing ship; the greater range means more ships of the fleet potentially protected.

**Comment by LocalGod79** [comment]
@wambat1, it is - my whole "efficacy" formula is "a.m. X range / reload" with balance metrics that use that value to measure its efficacy versus mass, energy and heat, and cost...

there's a link to my spreadsheet in the pull conversation.

**Comment by endless-sky** [comment]
The smaller anti-missiles are basically just intended for ships too small to mount a large anti-missile. So, it doesn't necessarily make sense that two small AMs should be better than one big one, any more than two small guns need to do more damage than one big one.
