### ISSUE TITLE
Two ships boarding

### ISSUE THREAD

**Issue by w0ntoan** [endless-sky/endless-sky#118]
I tried to board an first non-hostile NPC ship and an second NPC also tried to board. The second NPC arrived on but unaligned with the first NPC before it was ready to go. The first NPC was revived before the second NPC could align. The first NPC was revived and turned to jump, and the second NPC continued to try to align. But when the first NPC jumped, the second NPC was dragged along with it even though it was facing the wrong direction. It did slow down and stop, but it certainly was not moving appropriately when the first NPC was jumping.

Not entirely a big deal, but it was hilarious to see a tiny shuttle zip off, and a Protector get flung by it.

**Comment by endless-sky** [comment]
This should be fixed in commit 630f367.
