### ISSUE TITLE
Weird flickers on escort icons

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#1180]
http://images.akamai.steamusercontent.com/ugc/264964143180794694/1B7AAE2802847DB5B9D3F0B82FE376A11E926E1A/
http://images.akamai.steamusercontent.com/ugc/264964143180794528/F2F7A8D5BD0A2EC6DC8F1F4FDAB10301B9F8CFA4/
http://images.akamai.steamusercontent.com/ugc/264964143180749735/D7269155C374ADDF4F9781913407995EED757A37/
http://images.akamai.steamusercontent.com/ugc/264964143180750049/2A86ABC9A689618ADEC4AF89BA5D6C582424D709/

I have many more screenshots,but I don't want to garbage-fill yet.

**Comment by Alkallid** [comment]
It's still flickering as I play, even after closing and reopening.

**Comment by Bladewood** [comment]
Not related to the issue at hand, but I want those 8.83 quintillion credits and that Korath flagship. On that note, how does one actually capture an AI ship?

**Comment by Alkallid** [comment]
Rngeseus.

**Comment by endless-sky** [comment]
Are you talking about the stars under the status bars? The status bars are drawn in additive blending mode so that they'll be visible even when they're overlaying other things:

![screenshot from 2016-06-01 23 05 56](https://cloud.githubusercontent.com/assets/11450262/15732726/8659ffd6-284d-11e6-8bef-15c20884f056.png)

**Comment by Alkallid** [comment]
No, as in the screenshots, my Hawks would sporadically go from one icon saying I have 20 of them, to all of them laid out with an extra 6 collapsed together, as if they had different stats or were in different systems. And back.

**Comment by endless-sky** [comment]
Do you have a saved game that would replicate this?

**Comment by Alkallid** [comment]
I have the game, but I sold the Hawks.

**Comment by endless-sky** [comment]
I think I found the issue. Should be fixed in aa763ca.
