### ISSUE TITLE
different solar collection rates for different star types

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1181]
http://steamcommunity.com/app/404410/discussions/2/357287935541222169/

**Comment by LocalGod79** [comment]
i think that the subject could be more descriptive - when i read it, i think "just turn the brightness/contrast of your monitor down"...

perhaps "different solar collection rates for different star types"?

**Comment by Amazinite** [comment]
This should be marked v0.9.9 (done). (https://github.com/endless-sky/endless-sky/commit/317b495a7217784bb490637564e1ff57e22c0193)
