### ISSUE TITLE
Timid Personality vs Piercing

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1183]
If a fleet has the timid personality, it would normally try and run from a fight if its shields drop below a certain point, but if you have a piercing weapon and are able to do damage directly to their hull to the point where their shields do not drop below that threshold of fleeing, they will never flee no matter how much hull damage they have taken. Maybe make it so that timid personalities will run if either their hull or shield drops to a certain percentage, instead of it just being the shield.

This behavior of timid fleets not fleeing when taking direct hull damage occurred while attacking World Ships in the old Korath territory. Normally they try to run after their shield is lowered to about 1/3rd, but they done seem to care when taking piercing damage.

**Comment by endless-sky** [comment]
In 9670159 I've tweaked the AI so it will flee at:

* shields = 0%, hull = 100%
* shields = 100%, hull = 50%

or any point on a line in between those (e.g. hull at 60% and shields at 80%). For non-piercing weapons it will still behave exactly the same (fleeing when shields drop), but ships taking piercing damage will now flee sooner.
