### ISSUE TITLE
[enhancement] "over" tag for engine mounts

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1185]
that would cause the flare to be rendered above the ship sprite.

this would be most noticeable on the Ravens, but would allow more engine arrangements on future ships

**Comment by endless-sky** [comment]
I think that would look really ugly for a lot of the existing engine flare sprites, just because I didn't make any effort to make the end of them that is hidden by the engine look good.

**Comment by LocalGod79** [comment]
so, if someone gave the engine flares a touchup, you'd consider it?

**Comment by endless-sky** [comment]
I'd consider it, but it doesn't seem like a high priority.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/435ab5c32047d589b14bb73e380e3d1869410893
