### ISSUE TITLE
Reputation from killing robotic ships

### ISSUE THREAD

**Issue by TELunus** [endless-sky/endless-sky#1187]
Killing large and dangerous armies of Mereti or Sestor ships doesn't increase your reputation with governments that have a negative attitude towards the Mereti and/or Sestor because their ships, being automated, have a crew of zero.  I realize that this is in keeping with the way the mechanics was designed, but it seems to me that most governments would appreciate the destruction of enemy armies even if no actual lives were lost.  My guess is that before the introduction of automated ships crew was used as a rough measure of threat level of a ship, which makes a decent amount of sense until there are robotic ships.

**Comment by jafdy** [comment]
The `automaton` attribute was made to let the Earth Shaper be a transport without crew.
If reputation was changed then it would be possible to become friendly with the Mereti or the Sestor.

**Comment by TELunus** [comment]
I am confident that there exists a system of mechanics whereby a government could like it when you destroy huge swaths of Sestor and Mereti without making it so that either of them would ever start to like the player.

**Comment by TELunus** [comment]
Also, maybe it's important that the Sestor and Mereti always hate you, I don't really know where the story is trying to go, but I don't think there's anything inherent about warring robot factions that makes them have to always hate you. To me it makes some sense that the super advanced alien robots that are at war with each other could notice which side you're taking in their war.

**Comment by TELunus** [comment]
Perhaps they're always supposed to hate everyone who isn't of their own government?  If that's the case it definitely sounds like it should be its own attribute instead of making sure they "attack" everyone by making everyone hate them and attack them on sight, and then also making them dislike the player (because you can't guarantee that the player will always attack them) and then because there are two of them making sure they don't start to like the player for attacking the other one by making both of them not count because they're crew-less.

**Comment by jafdy** [comment]
This is now a code change propitiation so I'm going to keep out of it.

**Comment by Wrzlprnft** [comment]
I haven't read through this, because lack of time, but it might be a duplicate issue. I know of 2 closed issues about the same title, not the content, though. Can somebody chexk this?

**Comment by Amazinite** [comment]
#1143

**Comment by Amazinite** [comment]
>  but it seems to me that most governments would appreciate the destruction of enemy armies even if no actual lives were lost.

What governments would appreciate this though? The only two governments that have any relations with the two automaton Kor factions are the Kor Effret and Quarg. The Quarg wouldn't care if you kill the automatons because they understand that there is no point in doing so, and only exist in Kor space to defend the Effret, and the Effret understand this as well are are completely fine with hiding behind the protection of the Quarg to not have to partake in the endless and pointless war between the machines.

**Comment by Wrzlprnft** [comment]
Maybe a attribute to turn on a money based rep-factor(similar to CR) for automatons?

**Comment by Amazinite** [comment]
Maybe an attribute in governments that stops them from changing their player rep?

**Comment by wambat1** [comment]
i think having a "faction reputation" line which functions the same as the "player reputation" line would add a great deal of flexibility to relationships in the game going forward. currently relations are too rigidly linked to "attitudes". it works for things as they stand, but presents perceivable roadblocks to future developments.

**Comment by Bladewood** [comment]
Idea: Somehow, Hi Yahr in the Unfettered Hai network becomes connected to Celeborim (damn you Pug), and you have to help the Unfettered fend off the Kor Sestor fleets that will now swarm and rek them.
