### ISSUE TITLE
You can put spaces as your first and last names

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1191]
`pilot " " " "`
`date 16 11 3013`
`system Rutilicus`
`planet "New Boston"`
Nope, nothing wrong there.

**Comment by Amazinite** [comment]
I don't really see how there's anything wrong with that. That's what I did, so people just call me "Captain  "

**Comment by endless-sky** [comment]
Arguably, there's no reason not to let the player do that if they want to. (And similarly, there are no constraints keeping them from filling in things other than a proper name if it amuses them to do so.)

**Comment by IFailAtGaming** [comment]
i'd personally go for asking for support for alt 0173, just so you don't get that weird space at the end
