### ISSUE TITLE
[mechanics/accessibility] "completed" mission map indicator

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1193]
is apparently difficult for some Steam users to discern from "incomplete" ones.

the initial suggestion was for a different colour (green), but the colourblindness explanation was given and accepted.

further suggestion was to "invert" the pip, though i believe they actually meant to "flip" it, so that the fade is away from the system, rather than toward it.  i personally believe this technique would appear better if the completed mission pip were "flipped", rather than the incomplete...

edit: i believe this is a possible statistical limitation of some individuals (and their "blue cones"); humans in general perceive red better than any other colour, which might explain why there are no complaints about the jobs "that have not been taken" and "cannot be taken" pips, while the blue pips seem to have been complained about a number of times.

of course, these users may also be using aged crt displays which have blue phosphors that are wearing out (as it's a popular colour) and fail to display the intended contrast.

all of that said, perhaps adjusting one of the blue pips a tiny bit toward purple would achieve the desired effect without compromising access to the colourblind?

**Comment by LocalGod79** [comment]
i guess this is further to;
#72 
#414 
#820

**Comment by endless-sky** [comment]
I've made the "active mission" pointers bigger than all the others, and the "blocked mission" pointers a tad darker, to address this. (4973ccf)
