### ISSUE TITLE
Game crashes when the last save file is on an nonexistent planet/system

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#1194]
1. Create a new pilot
2. Quit
3. Go to `map.txt` and delete the object `New Boston`
4. Start the game again
5. Stare as ES crashes.

It is particularly problematic when you play with mods (which add new systems) before, and then you remove it.

**Comment by endless-sky** [comment]
Fixed in commit d2a2037, by having your location default to the starting planet if the saved game either does not name a location, or names a location that does not exist.

**Comment by KiLEdEnNis** [comment]
what if someone is dumb enough to delete the starting planet? :P

**Comment by Wrzlprnft** [comment]
Well, then he probably did not start there
