### ISSUE TITLE
Person out of fuel?

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1195]
http://steamcommunity.com/app/404410/discussions/1/357287935555588979/

Summary: Melongrubber saw cap'n'pester fyling around in a system, not jumping, and getting followed by a swarm of ships, including MZ's kestrel. 
Assumption: out of fuel and the ships wanted to refuel

Edit: Earthshapers

**Comment by endless-sky** [comment]
Presumably, this could be fixed by just giving ramscoops to all special persons.

**Comment by endless-sky** [comment]
Fixed in 836ea18.
