### ISSUE TITLE
Make it possible to limit what commodity types a fleet may carry.

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1196]
Kor ships are dropping commodities that do not make sense for robots. can the commodities they carry be restricted to ones they should be likely to carry.

**Comment by Wrzlprnft** [comment]
I support that idea, but i am not sure where one would define that. In the government?

**Comment by jafdy** [comment]
Just to check, are you only talking about the Kor Meriti and the Kor Sestor.

**Comment by Amazinite** [comment]
@jafdy

>do not make sense for robots

**Comment by Amazinite** [comment]
Would robots really have any need to carry around cargo anyways? All of the ships are warships built on the planets and launched into space. I would think that the warships wouldn't need to carry any cargo because all the supplies are on the planet. Maybe if there were hauler type automatons that would salvage the wreckage to be reused on more ships, but other than that I wouldn't think they'd have use for cargo of any kind.

**Comment by jafdy** [comment]
@Amazinite Call me paranoid but I wanted to check that everyone is on the same (metaphorical) page.

**Comment by wambat1** [comment]
Mereti & Sestor: it is still reasonable to expect their ships to carry cargoes between their various planets and stations.

recommend restricting commodities to: Plastic, Equipment, Industrial, Electronics, Heavy Metals.

balance point: i think cloaked vessels can still get free commodities from Mereti/Sestor battles without uncloaking. near zero risk. probably not enough profit to warrant addressing, but i thought i would point that out.

**Comment by Amazinite** [comment]
Maybe this could be some sort of attribute located within the fleet. After `cargo` has been defined, you could specify the different types of commodities that that fleet would be carrying, so it would look like
`cargo 1
         Plastic Equipment "Heavy Metals"`

**Comment by endless-sky** [comment]
This would also be useful for missions. For example, the Free Worlds missions where you're attacking a food convoy could ensure that the convoy really is created with food in its cargo holds.

**Comment by endless-sky** [comment]
Implemented in 69d618c. It's limited to ordinary commodities, because if custom-named cargo was used (like mission cargo), you wouldn't be able to sell it.

**Comment by KiLEdEnNis** [comment]
not sure if equipment makes much more sense, but it's a great addition

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
