### ISSUE TITLE
Quarg in the Korath AI region will easily be disabled by the Korath

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1198]
Lure a Quarg ship into a Korath firefight somehow.
The Quarg WILL be disabled.
Free skylances and quantum shield generators.
Buff Quarg plz.

**Comment by toilethinges** [comment]
In the new version, where their hull is 50k, or back in the older version where it was 8k..?

**Comment by wambat1** [comment]
any way they could develop a tech that makes the Quarg's shields immune/resistant to Mereti disruptors? i think that would better reflect the Quarg's style (relatively small/fast warships, so low hull strength), and be a more elegant display of their technological prowess.

**Comment by MarcelineVQ** [comment]
This isn't really a problem is it? Typically by the time you can weather a mereti group large enough to disable a quarg vessel you could have done it yourself.
Though that's a bit tougher to do effectively with the combined changes of ships fleeing at 50% hull plus increased quarg hp so you need a fair bit more firepower just to stop them before they jump out.
Are you mainly concerned about being able to get the tech without the rep loss?

**Comment by endless-sky** [comment]
@Bladewood, what release are you using? This should be fixed in 0.9.1.

**Comment by wambat1** [comment]
i don't think you can avoid the rep loss. if you want to plunder a disabled Qurag you still have to shoot it first. if you are already hostile due to bad rep, i don't think you are worried about the rep loss.

**Comment by Bladewood** [comment]
No, no, no, not a Quarg vs Mereti fight, a Quarg vs a swarm of Mereti and Sestor ships.
Also, I am not trying to attack their fleets. I have a crappy ship, but it has a cloaking device. You have no idea how useful that is in this situation.

**Comment by Bladewood** [comment]
I've managed to reproduce this (sort of):
https://dl.dropboxusercontent.com/s/zlcx27nvhqsncvr/quarggetrekt.png?dl=0

You know it's a serious threat when the Quarg get rekt. (unintentional rhyme ftw)
