### ISSUE TITLE
Fleet management: how to refill secondary ship's fuel?

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#12]
This might not be an issue strictly speaking, but as I'm struggling with this point, it might mean that it needs to be better documented in the game (unless it's an actual bug that needs to be fixed).

I have two Star Barges, and the second one seems to be stuck in a world without colonised system. I can't seem to find a way to make it ask other ships for fuel, so it's just stuck in this world. What am I missing?

**Comment by endless-sky** [comment]
Yes, that would qualify as a bug. Right now the AI will ask for help from ships of its own government if it is disabled, but I should expand that so it also asks for help from any friendly ship with enough fuel to spare, if it is stranded.

As a work-around, it's possible that if you save and reload the game, the stranded ship will magically refuel itself. I'm not sure if that will work, though.

A third option would be to equip your ship with some weapons, disable your own escort, and board it - if you do that with enough fuel in your tank, I think you'll transfer some over. Not an elegant solution, though.

**Comment by akien-mga** [comment]
Interesting workarounds :-) In the end I used a saved snapshot that was only ~10 game days earlier or so, so I could retrieve my second ship.

**Comment by endless-sky** [comment]
I've checked in changes that ought to make your ships (and all other ships, too) ask for help from other ships if they run out of fuel. I tested it with a Star Barge in an uninhabited system and verified that it called over a merchant ship to help it. But, given how complicated the AI can be this should probably be tested a bit more before we conclude that it's working and has not introduced other bugs.

**Comment by akien-mga** [comment]
Great! I'll check that in and play a bit to see if I find regressions.

**Comment by akien-mga** [comment]
It's working fine for fuel refills AFAICT. I now have issues with getting my secondary ship repaired after it got disabled during a fight. Even on friendly systems with a lot of traffic, the AI does not seem to call for help.

**Comment by endless-sky** [comment]
The AI will only call for help if there are no enemy ships in system. But, you can repair your own ship: just press Shift+` (or whatever your "target next" key is) to cycle through your ships. Or, if you press the board key, and no other ships are disabled, it will select your own ship to board.

**Comment by akien-mga** [comment]
Ah nice! I guess the function of the Shift modifier to manage one's own fleet needs to be better documented. I don't see the binding for the board key either in the preferences menu, I guess it should be added there.

**Comment by endless-sky** [comment]
I added a small side pane in the preferences panel, next to the targeting keys, describing their alternative behavior if the Shift key is pressed. I also added the board command to the preferences screen.

**Comment by akien-mga** [comment]
Works fine, thanks for that! I guess the issue can be considered fixed by 0b889cf.
