### ISSUE TITLE
A way to see your friends ships?

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1200]
This is just an idea I'm throwing out there, but it's inspired by this idea for a pluggin I've been working on for adding your friends ship's in as people in the galaxy. It's also inspired by another game I've been playing called re-assembly. For those who don't know, in reassembly, you can build your ship and upload it into the galaxy and then people can see the ship you've built, and your name on it in your galaxy in a single player game. What I'm wonder is, could a similar system be implemented for ES at some point? How could this be done?

Any way I realize a lot of other things have priority right now, and I have very little C++ skill to realize something like this, but I wanted to put the idea out there as food for thought.

**Comment by Amazinite** [comment]
So pretty much fake multiplayer, making it seem as though your friends are in the universe when they really aren't? I guess you could make an npc kill mission that creates a ship with your friend's name and it would just fly around doing stuff.

**Comment by jafdy** [comment]
Except that it wouldn't. A better way would be to create a plugin that adds a person to the `person` file.

**Comment by mdsmestad** [comment]
@Amazinite Well that's pretty much the idea, this requires uploading data to a server, and then pushing it out to every ones game. There has to be some way in game to initiate upload  to the server, as well as some kind of parameters to dictate what ships can be uploaded. 

What I'd like to see, is the ability to upload a legal ship (existing ship data) and then add a custom sprite/hail to it via request/screening approval system. If someone wants to upload a ship with stock sprite/data then it auto uploads there ship name/ship configuration/player name and then you can see it in the galaxy!

I suppose when you start your game up, it should randomize which players you see, or perhaps have a setting to only see your steam friends..whichever.

**Comment by wambat1** [comment]
are these persons going to be plunder-able/capture-able? will they perma-die, or be repopulated each time you load the game? seems like this might be better addressed by a user-friendly plugin with instructions on the mod sub-forum(s) where players would have the option of posting their ships as "persons" plug-ins for others to add to taste.

**Comment by mdsmestad** [comment]
@wambat1 Ya, there are definitely some issues with the idea. I am actually doing a pluggin like this right now though.

**Comment by jafdy** [comment]
Everyone creates a plugin with a common template and you can add the ones you want to your game. No code here and that lets us focus on other things.
