### ISSUE TITLE
Wormhole Cost Change Affecting NPC Pathing

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1202]
75beae206ae3d39b905c266a6d631ea31e94084b
very recent wormhole distance cost change

The change to the Add function causes my escorts to fail to find a route through the wormhole if the player isn't in the system. Reverting that one line reliably causes them to path flawlessly.

**Comment by endless-sky** [comment]
Should be fixed by b51c57e.

**Comment by MarcelineVQ** [comment]
confirmed that b51c57efd4c95fee5c226dfa6711e38af41fac8c fixes the issue for me
