### ISSUE TITLE
Crash using latest windows 10 version

### ISSUE THREAD

**Issue by m31317015** [endless-sky/endless-sky#1206]
Issue: Crashing on startup
Version: 0.8.11, 0.9.1
System: Windows 10
Status: Fixed
Description:
I've been crashing for a couple times when I tried to launch the unstable version 0.9.1, it crashed right at the startup process. And I've been playing around with x64dbg for a while, so I tried to use it to debug the exe file, then it turns out that it works perfectly using x64dbg, and such I guess that it's the problem of the latest windows update for windows 10

How I fix it:
I switched to windows 8 compatible and it works fine again.

Request:
Since it's fixed I won't beg for anything but please can you fix the bug where the game would crash at startup using windows 10? I'm not able to use my screen dimmer to dim the game window since it's not compatible with windows 10 but with windows 8.

**Comment by jafdy** [comment]
I'm also using windows 10 and I don't get this.

**Comment by m31317015** [comment]
Is it related to the use of Spybot Anti-Beacon?

**Comment by Bladewood** [comment]
If you are concerned about that, disable it temporarily (if possible) and attempt to run Endless Sky.
I am running Windows 10 myself, and I am perfectly fine.

**Comment by endless-sky** [comment]
I don't have access to a Windows 10 machine. If someone with a Windows 10 machine is seeing this bug, they could try to fix it or at least figure out what causes it.
