### ISSUE TITLE
Feature Request, Button for Information Panel

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1207]
I'm not sure whether my experience is common but here goes:
I had played for tens of hours before discovering you could press i and get an info screen about your player and fleet. Further I had no idea the panel was different on a planet in that you could park ships on planets. I only just now learned about that feature by hearing about parking on these issue pages and trying to figure out what it was and how to do it.

I'd like to put in a request for an Info Button that brings up your info panel, possibly on the Map screen if such a thing would clutter the main UI, to make it more likely that people find out about the info panel due to a visual hint, and by extension its cargo and parking features.

P.S.: Gosh hehe, researching whether this issue has been address just taught me you can press Alt to highlight shortcuts in menus, which made me wonder what it would show on the trade screen and now I know about the 500x modifier. Now I'm curious about what other stuff I've missed. Though to be fair I see the 500x modifier is mentioned in the player's guide.

**Comment by LocalGod79** [comment]
this sort of thing could probably go into #921
