### ISSUE TITLE
transported outfits vanished after switching flagship

### ISSUE THREAD

**Issue by DanielT** [endless-sky/endless-sky#1209]
I was flying a Bactrian and had several outfits on board for captured ships, i.e jump drives, reactors etc.
Then I captured a Model 256 and switched to that. I parked my Bactrian because it was the weakest ship in my fleet at that point and I figured I'd just return to it later for the stored outfits.
Turns out it doesn't work that way. The outfits were gone once I returned.

My guess is that the outfits are not stored on a specific ship, but didn't fit in the holds of the remaining fleet because I sacrificed the entire cargo space on all my war ships for extra outfit space.
Perhaps they were forcibly sold, or maybe they were just destroyed?

**Comment by Amazinite** [comment]
If you have a large fleet, the cargo will be swapped from your flagship to your other ships upon landing. If you park a ship with cargo in it, the cargo is sold.

**Comment by Amazinite** [comment]
I think I found a bug. Cargo that is sold when you park a ship doesn't give you credits back. I just did it three times and all three times the cargo was sold, but the message said "600 cargo sold for 0 credits."

**Comment by jafdy** [comment]
Commodities or outfits?

**Comment by Amazinite** [comment]
Outfits.

**Comment by Amazinite** [comment]
Found two bugs with cargo, actually. I believe that one was fixed already; you can continue to buy outfits even if you have no space for them. The money is taken from you, but you don't get the outfit. The other bug is the first one I stated, where you get no credits for cargo that is sold from parked ships.

**Comment by jafdy** [comment]
Yes, the first is already fixed.

**Comment by Amazinite** [comment]
Screenshots of the second glitch occurring.

Parked my Bulk Freighter. 7 Dual Sunbeam Turrets in cargo. No space in the rest of my fleet.
![screenshot_6](https://cloud.githubusercontent.com/assets/17688683/15874137/da730dac-2ccf-11e6-967c-ced624d6d4b0.png)

I depart. It gives me the message that it sold, but I get 0 credits.
![screenshot_7](https://cloud.githubusercontent.com/assets/17688683/15874136/da711dee-2ccf-11e6-9969-2421cb1a136a.png)

**Comment by jafdy** [comment]
And it is not giving you the credits as well.

**Comment by MarcelineVQ** [comment]
took a stab at a selling fix, probably a popup asking you if you're sure you want to leave would be best though. In the rare case where you're being forced off a planet for a mission and have parked down your cargo space the popup could be a little immersion breaking but otherwise it could make someone's day.

**Comment by endless-sky** [comment]
Fixed by merging in @MarcelineVQ's PR.

**Comment by Amazinite** [comment]
> took a stab

Is that suppose to be a pun? :3
