### ISSUE TITLE
Suggestion: Jump drive map

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1211]
Because I'm too lazy to map everything myself.
And also because potential mod project thing.

**Comment by toilethinges** [comment]
Clarification?

(or, in other words, what does this mean?)

**Comment by Bladewood** [comment]
Maps the surrounding systems, regardless of whether it requires a hyperdrive or a jump drive, in the 'visible' radius. Or something.
I plan to probably use this for Korath worlds.

**Comment by toilethinges** [comment]
So when in Jump Drive range, you can see it as a gray system, like you've never been there before, but discovered? This is already done.

**Comment by Alkallid** [comment]
I think he means the Local Map for unlinked systems.

**Comment by Bladewood** [comment]
More or less.

**Comment by toilethinges** [comment]
@Alkallid, thanks for clearing that up...
