### ISSUE TITLE
crash causes loss of "in-stock" items

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1212]
i just had a crash; my first; it occurred when i was docked and messing around in my ship info screens. the game froze and i had to force it to close. i doubt the crash is reproducible, but the important thing i noticed is that, while the few items i had moved into cargo were preserved, i lost large numbers of outfits (having just finished farming Kor) that were still "in stock". as items in cargo seem to be protected from these adverse circumstances, it seems there ought to be a way for "in-stock" items to be likewise protected. i was fortunate in that i had essentially installed all the outfits i was going to use, but this sort of thing happening at a less opportune time might cause less level headed players to severely damage their computers.

**Comment by endless-sky** [comment]
Fixed in 7c04872.

**Comment by Bladewood** [comment]
Oh, good, now reloading a save is much more useful. Namely when I get a new ship and I have to discard outfits and to check whether getting the ship was actually a good idea or not.
