### ISSUE TITLE
Pay Extra to Other should treat Other as a lump

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1215]
I'd like to suggest that pay extra for Other pays out to as many accounts as it can get through, one at a time, with the money you've given it.

Currently when you hit pay extra for Other it will pay as much as it can to the first item in the list of accounts that Other is hiding and then it stops. This is a bit painful when you want to pay off a large chunk worth of Other that is made up of many smaller loans or fines but not willing or able to Pay All.

Cases where this occurs:
When I play a merchant character my typical pattern is to make some trades, let the value of the trades bump up my borrowing bracket, then use that to buy more more ships, rinse and repeat with a few breaks from borrowing interspersed to keep running costs lower than profits.
When playing a scavenger I might get a fair run of Death Benefits or Illegal Outfit fines (Nerve Gas) and income from captures is sporadic and comes in lumps.
In both cases the Bank Panel fills up quite rapidly and a fair chunk of the fees I'm paying are actually in the Other row.

If this is a change that makes sense let me know, I've already wrote the modification but I don't know if the etiquette is to make an issue first then make a PR if there's interest or just make a PR

**Comment by MarcelineVQ** [comment]
gosh, sorry about this reference spam, github is kinda weird and I'm still getting used to it

**Comment by jafdy** [comment]
I'm sorry. Could you explain that more clearly.

**Comment by MarcelineVQ** [comment]
The commit links above, github apparently makes a link to something you reference so if you do it a few times the messages pile up :(

**Comment by jafdy** [comment]
No, the original statement. All this talk of "Other" has confused me.

**Comment by MarcelineVQ** [comment]
In the Bank panel on a planet when you have enough mortgages or fines they show up in a row called Other because there isn't room to display them all. When you try to use 'pay extra' to pay them it'll pay the first mortgage that Other is hiding.
If there happens to be a number of hidden mortgages/fines then you may need to 'pay extra' many times to pay down a sizeable chunk of what Other is hiding because no matter what you put in the 'pay extra' box it can only pay the principal of the first item hidden by Other.
You can try this out yourself by taking out 12+ small loans then trying to pay Other off with 'pay extra'.

The proposed fix will pay out each principal hidden by Other in turn until you've used up what you entered in 'pay extra'. It doesn't have any downsides I can spot under the current ui and should be a quality of life improvement for players that play like I sometimes do.

**Comment by jafdy** [comment]
Ok, that makes sense. I don't normally pile up that many mortgages/fines/death benefits at a time. 
This could be worth extending to the "in view" ones as well.
