### ISSUE TITLE
Allow missions to deduct more money than the player has by creating a mortgage

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1216]
If the negative payment can't be made the the money is not deducted. The alternative is to be able to set a mortgage but I don't know how to do that ether.

**Comment by MarcelineVQ** [comment]
I can't get a mission to trigger with an on accept payment costing more than I have.
Is this a feature you're requesting? If so give this branch a try:
https://github.com/MarcelineVQ/endless-sky/tree/mission-payment

**Comment by LocalGod79** [comment]
@jafdy i've commented on your pull with the possible explanation, and a check that you need to do.

**Comment by jafdy** [comment]
That branch should work but it is no use to me if it isn't merged. (not to mention that I haven't worked out how to compile for windows yet)

**Comment by endless-sky** [comment]
It seems to me that having a mission give you a new mortgage but only if its payment is negative *and* you can't afford the payment is a somewhat confusing behavior. And, it means that it's no longer possible to create missions that are only offered if you have a certain amount of cash on hand (e.g. the "drop bear" attacks in EV Nova). Wouldn't a better option be to allow missions to specify that they apply a new debt to the player, instead? That would have the added advantage that the debt could be at a considerably higher interest rate than a typical mortgage.

**Comment by jafdy** [comment]
That was my preference.

**Comment by NomadicVolcano** [comment]
> Wouldn't a better option be to allow missions to specify that they apply a new debt to the player, instead? That would have the added advantage that the debt could be at a considerably higher interest rate than a typical mortgage.

PR #5073 implements this solution

**Comment by Hurleveur** [comment]
I have the same issue of not knowing if the player has the money or not and not wanting to branch too much, but I just use fines all the time, and try to justify them. Granted its not as flexible as a fully fledged out mortage.
