### ISSUE TITLE
Bounty fleet mission typo

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#1218]
Bounty missions with fleets include a grammatical typo, it should say "the <flagship> and its fleet has been destroyed" or even "the <flagship>'s fleet has been destroyed"
The current form has a plural for flagships

**Comment by LocalGod79** [comment]
the dialog you reference is worded:
`The <npc> and their fleet have been eliminated. You can claim...`

i don't know that it's poor grammar to attribute the fleet to the flagship...

**Comment by Alkallid** [comment]
It could be 'her' fleet.

**Comment by endless-sky** [comment]
It depends on whether you think of the NPC as the ship itself "it" or the ship's crew "them."
