### ISSUE TITLE
Thesaurus Error

### ISSUE THREAD

**Issue by ThunderSock** [endless-sky/endless-sky#122]
Sorry about the joke title. The Pug hails have a strange entry... understandable?
		"a regrettable "
		"an understandable " <<<
		"an unfortunate "
		"a serious "
		"a grave "
		"an extreme "
		"an ill-advised "
		"an absurd "
		"a foolish "
		"a stupid "
		"a crazy "
		"a preposterous "
		"an unwise "
		"a bad "
every word sounds like a version of "bad" except for "understandable" which is not like the others.

**Comment by endless-sky** [comment]
I honestly can't remember if that was intentional or not. Given that (spoiler!) the Pug are taking over human systems, it does make sense for them to refer to a counterattack against them as "understandable," though.
