### ISSUE TITLE
[enhancement] selectable navigation priority

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1220]
what we really need are some options. a drop down menu, or check boxes, so the player can select what priority he wants to use in navigation: time (days), fuel, safety, avoiding police, etc.

**Comment by LocalGod79** [comment]
perhaps rename this issue "[enhancement] selectable navigation priority" to be more concise?

**Comment by Amazinite** [comment]
Does least fuel not already equal quickest time? In the case of using a jump drive, the pathing will choose to use the jump drive if it can get from point A to point B with the least fuel. That means that if it were to switch to a hyperdrive in a situation where a jump drive was used then it would take longer and require either the same or more fuel. So choosing least fuel usage and fastest time would yield the same path anyways.

**Comment by endless-sky** [comment]
There are some cases where they are different. For example, if you can get somewhere in three hyperspace jumps, or follow a different route that takes two jump drive jumps. Then, the route that uses the least fuel is not the fastest.

**Comment by wambat1** [comment]
one of the potential benefits of this suggestion it that it makes the navigation priority explicit to the player. this should reduce the number of post inquiring on that aspect of the game. 

    On Friday, June 10, 2016 11:00 AM, Endless Sky <notifications@github.com> wrote:
 

 There are some cases where they are different. For example, if you can get somewhere in three hyperspace jumps, or follow a different route that takes two jump drive jumps. Then, the route that uses the least fuel is not the fastest.—

**Comment by endless-sky** [comment]
That would make it useful for the 0.1% of players who actually have both types of drive installed and want to fine-tune how pathfinding is done, but would add clutter and extraneous details that would confuse the other 99.9% of players.

If someone cares that much about pathfinding (e.g. because they're under a tight time constraint) they can always hand-tune the route. That seems better than adding new interface elements that nearly all players will have no use for.

**Comment by wambat1** [comment]
i am not sure where your statistics are coming from. each example i gave "time (days), fuel, safety, avoiding police ... " was derived from a player's request; none of them mine; on the steam forums. so, i should think that brings the percentage up to at least 0.4%.
still, if the change was to be made, it would not be coded by me, so i am hardly in a position to argue. 

    On Saturday, June 11, 2016 12:12 PM, Endless Sky <notifications@github.com> wrote:
 

 That would make it useful for the 0.1% of players who actually have both types of drive installed and want to fine-tune how pathfinding is done, but would add clutter and extraneous details that would confuse the other 99.9% of players.If someone cares that much about pathfinding (e.g. because they're under a tight time constraint) they can always hand-tune the route. That seems better than adding new interface elements that nearly all players will have no use for.—

**Comment by jafdy** [comment]
If there is a steam forum link then you should post it. 

Also both your statistics seem a bit off, may I ask where you are quoting them from?

**Comment by LocalGod79** [comment]
there are nearly 6000 steam users who have played/are playing Endless Sky.

unless you can reference 24 users' requests for the feature, i believe M.Z.'s statistic is probably accurate, if not already generous.

**Comment by jafdy** [comment]
Not necessarily. I often use both drives and I have never requested this feature. I'm thinking MZ's way at the moment.
Also please don't try to argue stats with a mathematician.

**Comment by LocalGod79** [comment]
i'm not arguing.

0.1% of Steam E.S. users is ~6 people - a generous estimate of users who have both outfits, and are unhappy with the current course plotting options.

**Comment by jafdy** [comment]
I'm not reading things properly again.
Well one of MZ's parts is definitely wrong as I represent about 0.02% on my own.

**Comment by LocalGod79** [comment]
let's be clear - it's not that you "need 0.1% of players asking for a feature" for it to be implemented, rather "a new feature should not confuse 99.9% of players" - which, in this case, would actually be 100% of new players, until they finally got a Jump Drive.
