### ISSUE TITLE
[enhancement] capture "flight-check-fail" dialog

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1221]
http://steamcommunity.com/app/404410/discussions/2/357287935563555039/

**Comment by MarcelineVQ** [comment]
If you could install outfits from cargo in space or anywhere this would resolve by extension. There could be a mass limit on outfits installed this way to keep outfitters relevant as more than just shops and also to add the flavor of limping home on tiny temporary engines.
Is that feature at all in the cards for down the road?

**Comment by LocalGod79** [comment]
#677 @MarcelineVQ

**Comment by MarcelineVQ** [comment]
Thank you @LocalGod79

**Comment by endless-sky** [comment]
I kind of think it's the player's own fault if they gut a ship and then decide to take it over. Allowing the player to swap arbitrary outfits while in flight could create all sorts of balance issues, so I'm hesitant to do that.
