### ISSUE TITLE
Plugins do not seem to be able to alter "interface" colors

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1222]
I saw a recent post in the [Google Group](https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/VCtI-XGBrxs) and on [Steam](http://steamcommunity.com/app/404410/discussions/0/357288572119124938/) asking about why their plugins were not working when they tried to change the interface colors. I've tested to see if it works for me and it appears not to. 
Here we have the normal colors for the hull, shield, fuel, energy, and heat indicators.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/15982037/83c1bb78-2f4c-11e6-9336-3573a361cb60.png)
And the following is the default values for those colors
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/15982038/8bea2a4c-2f4c-11e6-974f-e7986d3694f7.png)
So I went into the interface files of the game itself, not a plugin folder, and changed them to this
![screenshot_3](https://cloud.githubusercontent.com/assets/17688683/15982042/95c5e178-2f4c-11e6-864d-da9f2cba43f0.png)
And as this picture shows, it works.
![screenshot_4](https://cloud.githubusercontent.com/assets/17688683/15982044/9cc10818-2f4c-11e6-9893-2a2eaa9cda54.png)
Now I took these changed values and put them in a plugins folder while reverting the original interfaces file back to normal. As you can see at the top, the plugin file pathing is proper.
![screenshot_5](https://cloud.githubusercontent.com/assets/17688683/15982052/b8d673da-2f4c-11e6-9295-8bf056b413fd.png)
But in game, there are no changes to the colors of the GUI from normal. It remains looking like this.
![screenshot_6](https://cloud.githubusercontent.com/assets/17688683/15982057/c8011572-2f4c-11e6-906a-27f874dc7855.png)
So I moved the "Test" plugin from the plugins folder I normally use (which is located along side the files for the game itself) and moved them to the plugins folder that is located next to the saves folder. @localgod79 has told me that people have had issues when they make their own plugins folder next to the other folders and files, so I thought that this may have been causing the problem.
![screenshot_7](https://cloud.githubusercontent.com/assets/17688683/15982075/3916d04e-2f4d-11e6-8ea9-3a878e5f36b0.png)
But this still did not make any change to the default GUI colors.
Any idea why plugins would be unable to change this?
It may be important to note that I am on Windows 8.

**Comment by endless-sky** [comment]
Commit 6e33151 fixes that.

The issue was that unlike most data in the game, the "color" values in the interface were storing whatever that named color is set to when it reads the interface data, rather than storing a pointer so the color can be changed by later data.
