### ISSUE TITLE
[bug] missile reload from cargo message

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1224]
when reloading from cargo, the message still displays the cost of the reload (in spite of the missiles already having been purchased, and no actual fee being applied)

**Comment by endless-sky** [comment]
Fixed in a4c4017. But, that raises another issue: ammo should have a nonzero mass (but still zero outfit space), so that you can't store an infinite amount in cargo.

**Comment by LocalGod79** [comment]
your issue was discussed here;
https://github.com/endless-sky/endless-sky/issues/928
