### ISSUE TITLE
During return-to-Earth mission after talking to Pug at Pugglemug, Pug may follow you

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1228]
Finished talking to the Pug at Deneb. Jumped to Vega, Pug ships appeared. Jumped to Sol. But then a Pug ship jumped in.

I think this is a side-effect of having ships in systems adjacent to your current system remain "active" even after you've left.

Or maybe it isn't. I probably worded that badly.
I don't know. Thoughts?

Edit: I found that this also happens for the next missions, specifically the ones where you jump in and out of the Pug systems. It's entertaining to see the Pug get rekt by the Navy.

**Comment by jafdy** [comment]
The planet is Pugglemug.

Can you give a more precise mission reference?

If I'm correct about the mission then what you are describing should be impossible.

**Comment by Bladewood** [comment]
The first mission where this happened was `FW Pug 3`, but it also happens with `FW Pug 4`, `FW Pug 4B`,...

I don't think it's necessarily tied to the mission, I think it has to do with ship spawning in general...

**Comment by jafdy** [comment]
Don't know what you where doing with `FW Pug 4` as you are attacking them. After that mission it is intentional.
As for `FW Pug 3`, I can't help much as I don't know what the game is doing.

**Comment by wambat1** [comment]
are you hostile to the Pug at that point? if so they might be pursuing you, as i have observed pirates do.

**Comment by jafdy** [comment]
In `FW Pug 4B` he is but he shouldn't be during `FW Pug 3`

**Comment by Bladewood** [comment]
If they were pursuing me just because I was hostile to them, then the same should apply whenever I jump into a Republic system while we are at war, and yet not one electron beamer follows me, just regular heavy beamers. *memories of pain and suffering*

**Comment by jafdy** [comment]
To the best of my knowledge only mission ships can follow you. Out side of checking the obvious this is not my area of experience.

**Comment by Bladewood** [comment]
It's closer to 'wandering and just happening to enter the same system' then 'following'.
