### ISSUE TITLE
[enhancement] normally collapsed shipyard/outfitter-map categories

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1231]
when you switch to the outfitter-map, should look like this;
![screen shot 2016-06-12 at 1 13 11 pm](https://cloud.githubusercontent.com/assets/16969517/15992669/7f429c94-309f-11e6-9e48-3b92bf021cb5.png)

rather than this;
![screen shot 2016-06-12 at 1 13 18 pm](https://cloud.githubusercontent.com/assets/16969517/15992667/7b458dc2-309f-11e6-80cc-4876132fe625.png)

edit; the aim of collapsing categories was to speed access to outfit display - a normally collapsed display allows a user to select any given outfit with more efficient clicking, scrolling and pointer movement.

edit2; perhaps the shipyard-map would get a similar treatment?

**Comment by Bladewood** [comment]
One would assume that the not-collapsed version would be for new players, but for older players, I totally support this.

**Comment by endless-sky** [comment]
If I were a new player pulling up that page for the first time, I wouldn't have any way to know that I could click those category names to expand them. I think it makes a lot more sense for the categories to start out expanded.

The only other option that would make sense would be to have the preferences remember what categories are expanded and default to that.

**Comment by jafdy** [comment]
If you put a up/down arrow next to the name (up for collapsed, down for open) most people would get it as it is used in lots of places. You could just put a down arrow in the stile of a drop-down menu.

**Comment by LocalGod79** [comment]
@endless-sky, feedback so far on the UI is that many features are generally hidden, and when players (playing 0.8.11) heard about collapsing categories, the immediate response there (and here) is that the categories should be normally collapsed.

i believe that a triangle next to the categories (perhaps at the right edge of that line) pointed left (which turned down on expansion) would ease your concern for new player confusion (as it's a pretty universally used icon) with a normally collapsed view.

**Comment by Bladewood** [comment]
Perhaps the unwise player would think that they ['collapsed' outfitters] would be filled with outfits once they have reached a point in the campaign, or perhaps when they have already found enough outfitters through adventuring... or something... I don't know :|

**Comment by DingusShingleton** [comment]
Or simply use the commonly accepted UI parlance for "click to expand"... the mighty [+]. Put one of those in front of each category, bam, problem solved.

**Comment by Pointedstick** [comment]
Relatedly, this is why the "button" is a UI element: it specifically, deliberately looks clickable. No need to worry that the words don't look clickable because they could be contained within clickable buttons.

**Comment by ssokolow** [comment]
> i believe that a triangle next to the categories (perhaps at the right edge of that frame) pointed right, which turned downward on expansion, would ease your concern for new player confusion (as it's a pretty universally used icon) with a normally collapsed view.

The rotating triangle is the Apple convention. Things have become fairly mixed these days but, historically, the Windows world used a bordered `+` as a "click to expand" button and a bordered `-` as a "click to collapse" button.

My main concern is that putting a triangle at the left end would be mistaken for a fancy bullet point.

A triangle on the right end paired with an on-hover glow and a cursor change, however, would work. (Even if you're not seeing it as a rotating expanded/collapsed indicator, I've also seen triangles on the right end of clickable text used in many game UIs as a way to indicate that the text will pull up a new page/dialog/panel by analogy to the triangles in menus which indicate the presence of a submenu.)

**Comment by ssokolow** [comment]
It also occurs to me that another possible cue to new players would be to leave each header slightly expanded while in the collapsed state, showing the top third of the top entry in the section fading away toward the bottom.
