### ISSUE TITLE
Date increment on hyperspace jump skips leap day

### ISSUE THREAD

**Issue by woolsweater** [endless-sky/endless-sky#1234]
My fleet is in Alphecca on the game date 28 Feb 3016:

    pilot Clever Nickname
    date 28 2 3016
    system Alphecca
    
![Pre-jump map screen](https://cloud.githubusercontent.com/assets/761245/15994986/3e63ff56-30c7-11e6-9f8f-f99d2ee57dbf.png)

I have an active mission "Rush delivery to New Tibet", due on 29 Feb 3016:

    mission "Rush Delivery [0]"
    	name "Rush delivery to New Tibet"
    	description "Deliver 9 tons of gold to New Tibet in the Alioth system by Thu, 29 Feb 3016. Payment is 22,750 credits."
    	deadline 29 2 3016
    	cargo gold 9
    	job
    	repeat 0
    	to offer
    		random < 90
    	destination "New Tibet"
    	on complete
    		dialog
    			"You drop off your cargo of gold and collect your payment of 22,750 credits."
    		payment 22750
        
When I jump, using a normal hyperdrive, to Alioth, the ticker tells me that the mission has failed, and, crucially, **that the date is 1 Mar 3016**:

![Mission failed message](https://cloud.githubusercontent.com/assets/761245/15994991/4e5ba6d4-30c7-11e6-9450-21bac2d89aa6.png)

But the mission still appears to be active when looking at the Missions pane of the map:

![Post-jump map screen; job still present](https://cloud.githubusercontent.com/assets/761245/15994999/76c5b7cc-30c7-11e6-8528-c13b9966d45d.png)

Until I actually land on New Tibet:

![Post-landing map screen; job is gone](https://cloud.githubusercontent.com/assets/761245/15995010/d3112d7c-30c7-11e6-95c8-13c7d2661a73.png)

The date change on hyperspace jump appears to be erroneously skipping over 29 Feb 3016.

If I simply land again on New Holland, the date increments correctly:

![screen shot 2016-06-12 at 6 05 41 pm](https://cloud.githubusercontent.com/assets/761245/15995039/adbb9c0a-30c8-11e6-8c5b-69bc7b29fa5d.png))

Also, jumping back to Alphecca from Alioth only increments by one day, to 2 Mar 3016.

**Comment by endless-sky** [comment]
If you're on the planet on 28 Feb, when you take off (still in the same system) it will be 29 Feb, and when you jump to the next system it will be 1 Mar. That is, taking off from a planet takes a day.

**Comment by woolsweater** [comment]
Bah. That's it. Sorry, thought I had checked that.
