### ISSUE TITLE
[enhancement] colour-coding of systems on mission map based on highest total planet payout

### ISSUE THREAD

**Issue by XHawk87** [endless-sky/endless-sky#1235]
Edit: Updated title to switch focus to last suggestion of colour-coding by value, as filters have been suggested in #236 already.

If you rely heavily on the Job Boards for a lot of your income, especially bounty hunting and passenger transport, you can end up with a map littered with blue teardrops, which can make it hard to understand and manage. I suggest a filter feature could be added to the map to support this choice of playstyle.

Filter by category:
- Select one or more categories from a set of mission types
- Hides the mission descriptions and teardrops of all those not selected

This would allow you to look up missions that you are currently interested in. When your list goes on for several screens, cutting out the irrelevant clutter would make it far easier to find a particular mission.

Another consideration is the total amount gained by landing at a planet from all completed missions.

Filter by value:
- When activated, filter out missions on planets whose total payout on arrival is below a set threshold

Currently, to avoid wasting game time landing on planets with very low mission payouts, you have to click the planet several times to see each one in turn for every planet you pass by. So you can either waste game days or waste real time. A filter would allow you to see at a glance which planets have reasonable payouts.

A possible alternative...

Colour-code by value:
- Determine the total payout of each station, using the highest of all stations for the value of each system
- Calculate the range of payouts currently available and colour-code the systems by their payout value in a similar manner to how trade prices are colour-coded

This would allow an instant impression of which systems give better or worse payouts than eachother. It would greatly speed up the process of deciding where best to go next.

**Comment by jafdy** [comment]
This seems helpful for a very precise play stile. 
For everyone else, how helpful would it be? Not very.
Would it be worth the effort to code? Probably not.
It sounds good but the more I think about it the less implementable it seems.

**Comment by XHawk87** [comment]
That's like saying "This is a sandbox game, you can play any way you like, but we'll only give you the tools to support doing X". 

The traders already have their tools, and plundering is ridiculously OP so doesn't need any; this would support everyone interested in bounty hunting, courier, passenger lining and odd-job professions. That sounds more like a major wide-ranging playstyle to me. 

If its niche, that is only because the most-efficient playstyle is plundering. If (hopefully when) that gets nerfed, this will become a major issue for a lot of players.

**Comment by MarcelineVQ** [comment]
The color-code by value seems like a good idea.

**Comment by jafdy** [comment]
@XHawk87 absolutely but how do you go about it. Color coding is already coursing enough trouble for for some people so there is a limit there. As for filters, they will make the interface more cluttered and much of the UI goal is to avoid clutter. While you could only have them on hotkeys then they are not going to be found by most players.

**Comment by XHawk87** [comment]
Surely the solution for colour-coding will be the same for trading as for missions. Assuming we're talking about colour-blindness, its having a configurable set of colours to use. If you're going to have colour-coding for one, we can have colour-coding for two without any additional problem.

As for clutter, the purpose of this was to reduce screen clutter. It is an important consideration, but I am sure it can be placed unobtrusively, and perhaps even disabled until players actually need it, if that is a concern.

**Comment by LocalGod79** [comment]
@XHawk87 i think the problem is, how do you colour code "value" as well as completed/incomplete/acceptable/blocked missions? an inelegant 2-mission-map system?

colour blindness is a serious hurdle, since you really only have two colours (blue and green), and interpolated spectra (yellows) - i'm aware that this seems counter-intuitive (since green is technically between blue and yellow), but we're talking about *human* colour perception, sans-red.

**Comment by LocalGod79** [comment]
more consideration, and hopefully a middle ground solution:

pips as they are (to indicate number - up to 12), as well as completed/incomplete/acceptable/blocked

a colour scale of how much payment is waiting in each system, similar to commodity trading.

**Comment by wambat1** [comment]
current policy is that it will take at least 6 request of this nature to represent a 0.1% interest in your proposition. i know i have posted a similar request, so you only have 4 more to go. good luck ;-)

**Comment by LocalGod79** [comment]
don't get salty, @wambat1 - you already have the option to customize your course if you're not completely happy with the auto-course plotting.

and i count three thumbs up on @XHawk87's justification of the concept, showing considerable support for his request - within the 10 hours of the original post.

**Comment by wambat1** [comment]
congratulations @XHawk87, you have hit the 0.1% mark! yay!

**Comment by LocalGod79** [comment]
oh yeah, and #236

**Comment by XHawk87** [comment]
@LocalGod79 That is an interesting idea, however I was imagining it would be the circle ring indicating the system that would be colour-coded, much the same way it works for trade prices, not the mission pips. Apologies if that was not clear from my original post.

It would be nice to be able to see individual mission values at a glance, but I would imagine that'd be confusing even for people able to perceive the full human optical spectrum. I would be happy with just knowing the relative approximate value of landing at the 'best' planet in a given system instead.

**Comment by LocalGod79** [comment]
@XHawk87 perhaps i was somewhat unclear in my suggestion:
the pips remain as they are, while the "system ring" on the map (that the pips point at) progresses from dark blue, through green, to yellow as the value of active missions stack up within that system.

unfortunately, there have been already been a number of complaints about the shading/contrast of pips, and i don't believe that it's a viable solution in this particular case (as the individual variation would be difficult for some to perceive.)

**Comment by XHawk87** [comment]
@LocalGod79 You know, I believe we are saying the same thing in different ways. I was just confused by the idea of pips showing a number, but I realise now you meant they keep their current purpose of showing how many missions there are to do with that system.

I think consistency is important, so if both trade prices and mission payouts use colour-coding to show value, they should use the same system. Once they are tied together, any improvement to the trade prices colour-coding could then be carried over to mission payouts as well, and the issue will be solved for both.

**Comment by LocalGod79** [comment]
@XHawk87 perhaps rename this issue something more relevant to the resolution of this conversation: it appears that "filters" are a very old request (which apparently requires a great deal of effort to code, and would make this a duplicate issue), while our "[enhancement] payment based colour coding of systems on mission-map" discussion is far more concise, and may be easier to implement.

if you choose to edit the o.p. as well, please do not delete content (as it will make some of the other conversation confusing)
