### ISSUE TITLE
orientation indicator for flagship

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1236]
once you have a large fleet of ships; most bigger than your flagship; it can get disorienting. i often find myself flying in the wrong direction because i cannot easily make out my ship from the mass of other ships in my fleet. it would be handy for the flagship indicator in the upper right to give a directional reading the way the target indicator does.

while i do recognize that there is currently only a verifiable 1/60th of 1% interest in a change of this sort, i do hope the idea itself might be of some merit in its own right. if it is not found so, i will see what i can do about starting an online petition.

**Comment by jafdy** [comment]
The flagship is always drawn on top for precisely this reason.

**Comment by wambat1** [comment]
the proposal has been submitted for precisely the reason that the present solution is not optimal.

**Comment by Bladewood** [comment]
Personally, I support this idea, just to match selected ships and their rotating models in the HUD.

**Comment by XHawk87** [comment]
This has tripped me up a few times as well. A fleet of identical Bactrians all massed together can get confusing. I am not sure of the best solution however, other than using a different ship as your flagship.

Just throwing out ideas:
- Let us paint/decorate our flagship in some way so it stands out (this would also be fun!)
- Change mechanics/AI to encourage using a variety of different ships
- Some kind of highlighting/glowiness/outline anything to make the flagship stand out more

**Comment by jafdy** [comment]
I like the 1st idea.
2nd, How would that work and what would the ravening hordes think about it.
I think the 3rd idea would be a bit weird and would be better covered by the 1st.

**Comment by endless-sky** [comment]
Would making the "status indicator" for your flagship a different color be an acceptable solution? Or do you prefer playing with those turned off?

**Comment by wambat1** [comment]
i do like to play with status indicators off for aesthetics, but find it necessary to keep them on now that we have to deal with piercing damage. unfortunately, the current status indicator is not a help as, being a circle, it does not, of itself, communicate orientation well, and tends to get lost in one's vision among all the other green circles. it could be made to help by giving it a special color; say, blue; AND a special shape; say, a teardrop with the point on the direction the ship is facing. still, this solution would only help when the status indicators are turned on. i had hoped my original proposition would merely require some copy and paste work; would this solution be easier to implement? 

    On Tuesday, June 14, 2016 7:16 PM, Endless Sky <notifications@github.com> wrote:
 

 Would making the "status indicator" for your flagship a different color be an acceptable solution? Or do you prefer playing with those turned off?—

**Comment by endless-sky** [comment]
I think between the flagship highlight and the option to rotate your flagship's outline in the status HUD, this is pretty well covered now.
