### ISSUE TITLE
Stuck on alpha planet.

### ISSUE THREAD

**Issue by onnikyla** [endless-sky/endless-sky#1237]
Im stuck on the planet, every time I depart, 1) the alpha ships destroy both me and the navy ship, 2) I manage to jump out and get to safety, but the navy doesnt get out. any suggestions?

I have no hope of destroying the alpha with only 2 skylances on a bactrian. I have a 3 bactrians in hai territory, but I cannot survive for long enough for them to arrive.

maybe a solution to this is to make it impossible to accept the mission with a ship too weak.

**Comment by jafdy** [comment]
We don't have a "strength" metric out side of value.
@endless-sky having an autosave on `Wanderers: Alpha Surveillance F` would fix this. I don't know is there is a better way.

**Comment by Alkallid** [comment]
There is a way to check what category ship you have. 
Aside, this barely belongs here, and should be moved to Google Groups as the more personal questions are.

**Comment by onnikyla** [comment]
Yes, this doesnt relly belong here, even tho it is an issue. I have never used google groups and I dont relly want to learn how to use it for this one thing. If no one has anything to comment about this I will close this In a few hours.

**Comment by jafdy** [comment]
@Alkallid he has a heavy warship so that won't help.
Not refueling you and then throwing 3 Sestor ships at you could do with looking at. This is a personal question but it dose bring up a real issue with a mission.

**Comment by Alkallid** [comment]
I think the difficulty is accounted for, how else would you have _gotten_ there without save-scumming? The only other way is with cloaking, so there might need to be a buff for the _Peacemaker_.

**Comment by jafdy** [comment]
True, I still recon putting that autosave in would be a good step.

**Comment by onnikyla** [comment]
Its easy to get there, just jump from system to system without stopping. getting out is hard because the ship has to stop to jump but the sestor ships have the slowing weapons.

**Comment by jafdy** [comment]
An auto save in `D` as well.

**Comment by Alkallid** [comment]
Before the chance of stealing and lying about the devices?

**Comment by onnikyla** [comment]
now I got relly messed up, I landed in a hai system thinking the navy ship was alive. now i dont have an autosave and the storyline is Impossible to continue without code editing.

**Comment by onnikyla** [comment]
The ability to set the game to autosave every month or so would be nice.

**Comment by Alkallid** [comment]
Well, it isn't too difficult. Looking around the various forums should glean your solution.

**Comment by Alkallid** [comment]
That is a very cool idea. I second.

**Comment by jafdy** [comment]
@Alkallid that's `Wanderers: Alpha Surveillance C` you are thinking of.
@onnikyla #848 Is working on that but I haven't seen much activity in there for a while.

**Comment by onnikyla** [comment]
Wouldnt a toggleable autosave in the preferenses... menu be easy to implement with the next stable release?

**Comment by endless-sky** [comment]
The next release will include three "previous" saves that are automatically updated, allowing you at any point to back up to three planets ago. That should be enough to fix problems like this, for those players who don't take the repeated difficulty warnings in the mission text seriously enough. :)
