### ISSUE TITLE
[bug] Small Mortgages have Payments of 0

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1239]
Small enough mortgages can have payments of 0 which results in them sticking around forever. Pay All will remove them easily so it's not gamebreaking, but it's strange behavior for a bank not to want its money back.
This may be rectified by ceil instead of round in Mortgage::Payment but I'm not sure if there's other hidden concerns with doing that so I'm making an issues instead of a PR.

**Comment by endless-sky** [comment]
Are you sure those mortgages won't be paid when they reach the end of their term? The payment is:

`principal * interest * (1 + interest)^term / ((1+interest)^term - 1)`

If the principal is 1 and the term is 1 day left, that becomes:

`1 * interest * (1 + interest) / (1 + interest - 1)`
`= (1 + interest)`

As long as the interest is greater than 0, that means the payment will be nonzero on the last day of the mortgage term.

**Comment by MarcelineVQ** [comment]
I see, they are payed on the last day, sorry for the frivolous report
