### ISSUE TITLE
Korath mines should still damage you while cloaked

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1241]
They don't need to track your ship or anything, unlike missiles, they just need you to fly into them. Since they always hit when you're uncloaked, it doesn't make sense for them to not explode while you are cloaked. Unless they rely on some form of tracking other than physical 'sensors' to detect a ship less than a planck unit away and then explode, but even then, you should at least be able to push them out of the way or something.

**Comment by toilethinges** [comment]
#1035?

**Comment by Bladewood** [comment]
For jafdy's explanation, we should at least put a tracking-related statement in the minelayer description.
For Michael's explanation, that now makes me question why we can't fly [above] or [below] enemy fire in general and are instead guaranteed to get hit by a Korath detainer shot from thousands of [distance units] away. Unless the universe really is 2-dimensional, in which case, wow, just wow.

**Comment by Alkallid** [comment]
Iis gaim.

**Comment by Bladewood** [comment]
...and my first claim is invalidated, because while I was working on a little project, I found this line:
`"infrared tracking" .9`
I... wow.

**Comment by endless-sky** [comment]
If projectiles could never pass above or below ships, there would be no way to avoid friendly fire. So, projectiles magically only hit things that they "want" to hit (except for asteroids, which they always hit).

While cloaked you can be hit by blast damage, but there's no conceivable reason why you would be able to dodge every other type of projectile but not dodge mines.

**Comment by Bladewood** [comment]
I never knew there was a "wontfix" label.

**Comment by tehhowch** [comment]
This is now done - all projectiles hit if you are cloaked (but do not track).
a4a4b3e705ba39e2ab4310932cc1e9f4fcf8d87a
