### ISSUE TITLE
Make Low DPI Downloadable on Steam...

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1242]
...as DLC similar to the high DPI plugin.

**Comment by Amazinite** [comment]
Maybe also include https://github.com/Wrzlprnft/endless-sky-no-hit-effects in the low DPI plugin, or somehow make it an option in the preferences.

**Comment by LocalGod79** [comment]
in the 0.9.2 release, there is a preference (toggleable through text editing) that enables a "low dpi mode" reducing graphics memory usage...

**Comment by Amazinite** [comment]
So it only works if you go in to your preferences.txt and change it? That sounds like something that should be in the preferences menu, or at least made known.

**Comment by LocalGod79** [comment]
ideally, the engine would auto-detect the VRAM available, and switch to "low VRAM usage" on its own when <256MB is present...

**Comment by endless-sky** [comment]
Determining the amount of VRAM available is surprisingly difficult - there's no standard OpenGL way to do it, so you have to use calls specific to AMD and nVidia. And if you're using integrated graphics on some older Windows systems, I beleive there's a VRAM limit there too, and I have no idea how to query it.
