### ISSUE TITLE
[bug] subsequent saves when loading from "~previous" behave strangely

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1245]
to replicate the behaviour:
play, land, play some more, land, play yet more, land.
load any "~previous-{x}" file (ignoring warning).
take off, die
try to reload.

**Comment by endless-sky** [comment]
I just merged #1246 in - see if that fixes it for you.

**Comment by LocalGod79** [comment]
seems to be working as expected.
