### ISSUE TITLE
campaign bug

### ISSUE THREAD

**Issue by vexual-sy** [endless-sky/endless-sky#1251]
hey guys,
Just did the jump to the alpha space, returned to hai to complete the mission where the guy turns out to be immortal or some sort of other alph thing ( cant remember as it was a few weeks back, and have just been sandboxing the universe), but the campaign has just stalled. is it unfinished?
or am i stuck?

**Comment by jafdy** [comment]
It's unfinished.

**Comment by Amazinite** [comment]
It stops after you return the Beta to the Quarg. The rest is coming in the future.

**Comment by endless-sky** [comment]
That story line is implemented up until the point where you report back to the Wanderers and get access to their latest technology (Sunbeam turrets and Wanderer Anti-Missile). If you'v reached that point, then you're at the end of their story line (for now).
