### ISSUE TITLE
Cannot capture AI ships when you have only 1 crew member

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1252]
I've been trying for days now to board the ships of the Kor Mereti fleets. Boarding takes a lot of time because of the fact that the Korath AI ships tend to commit suicide, but that's not too much of a problem.
My big problem is that I find that when your ship is manned by a one-man-army (i.e. you only have one crew member aboard your ship, yourself), the Korath AI ships always have the boarding options grayed out.
**I'm not sure if this is intentional, as another part of Endless Sky's cruel RNG, or if this is caused by the fact that there is no point in boarding another ship if you have no crew members to pilot it.** If it's the former, then I must be REALLY unlucky with all of these boarding attempts. If it's the latter, it should be clear that this rule must only apply to non-automatons.
I saw that you removed androids, and it's a little bit of a bittersweet situation for me. After 0.9.2, this won't be as significant, except for ships which are already filled with androids and piloted by captains who are too lazy to hire crew, or for AI ships with command centers installed. Or perhaps for some weird guy who brought a shuttle to Korath space. But, I'd still prefer if you fixed this, because I am part of the first group out of the three.

In news that are probably related, for some reason, boarding fighters is sometimes grayed out, regardless of whether you have crew or not.
And whether or not your fighter slots are actually open.

**Comment by Alkallid** [comment]
The fighter thing might be a known bug where baving just one bay couldn't allow capture.

**Comment by Amazinite** [comment]
I've noticed this when trying to capture a vastly better crewed ship and getting down to 1 crew left. You aren't able to attack when you only have 1 crew, you can only defend.

**Comment by wambat1** [comment]
to capture automated ships you have to have at least 2 crew. in 0.9.1 you have to have ships with bays aside from the flag ship in order to capture fighters.

**Comment by endless-sky** [comment]
Fixed in a8fb5a8.
