### ISSUE TITLE
Ships do not respond to the hold position command when they are moving to board other ships

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1253]
I have a fleet, located in the Kor Efreti systems. I plan to jump to the southern Korath systems. We do not all have enough fuel to make the jump to and back from their systems, so we have to pass into the Drak systems first so that an Archon can refuel my fleet. It seems that my other ships have a tendency to board other ships in my fleet when they are out of fuel, so I tell them to hold position so that the Archon can give us free fuel.
However, they do not obey my command, and continue on their mission to refuel my other ships, only stopping once their target has enough fuel.
michaelfixplz

On an unrelated note, is there any "proper" term to refer to the southern Korath? Just calling them the Korath is confusing, since their northern and autonomous cousins are also technically "Korath".

**Comment by Alkallid** [comment]
The exiles?

**Comment by Amazinite** [comment]
> On an unrelated note, is there any "proper" term to refer to the southern Korath? Just calling them the Korath is confusing, since their northern and autonomous cousins are also technically "Korath".

I usually just refer to the old Korath as the Korath, and refer to the new Korath areas as "Kor space." Then from there I just say "Sestor," "Mereti," or "Efreti."

**Comment by wambat1** [comment]
i'm Efreti you might be confusing him. @Bladewood, i would not Sestor in anything @Amazinite has to say.

**Comment by Alkallid** [comment]
no

**Comment by Alkallid** [comment]
jus no

**Comment by jafdy** [comment]
@wambat1 The steam forum has a pun thread, this is not the place.

**Comment by Alkallid** [comment]
Also, what was the Sestor supposed to be?

**Comment by Bladewood** [comment]
Sestor are the brownish-reddish AI ships. Mereti are the metallic AI ring/lineships. Efreti are Korath exiles minus the jump drivers. Korath exiles are Efreti plus jump driving Raiders.

**Comment by wambat1** [comment]
@jafdy it was just too good. i could not help myself. i will delete.

**Comment by Alkallid** [comment]
I meant what was the pun. I know what they are.

**Comment by endless-sky** [comment]
The new escort orders system works as requested in this issue: your escorts will only move to help each other if they are not under any other orders.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
