### ISSUE TITLE
[bug] game crashes after series of somewhat unlikely events

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1254]
engage in capture combat
lose
escort fleet destroys your former flagship -or- launched fighters try to dock with disabled hostile captured flagship
{hang}

XCode's line note reads: `Thread 1: EXC_BAD_ACCESS (code=1, address=0x7a8)`
and points to
```
int Ship::Crew() const
{
	return crew;
}
```
in Ship.cpp

**Comment by MarcelineVQ** [comment]
I'm a little confused about how to reproduce this, do you get disabled then helped, and the next capture combat you lose will cause it?

Or are you saying enemy ships will capture you when you're disabled? I've never had this happen. Though it would make the capture defense stat a lot more useful than it has been for me as a player.

**Comment by endless-sky** [comment]
d37d36a should fix this.
