### ISSUE TITLE
Are mod configs possible? 

### ISSUE THREAD

**Issue by lokegustafsson** [endless-sky/endless-sky#1255]
Is there a way to enable and disable the loading of different text files through preferences or similar?
Of course it would need a reload to apply.

**Comment by LocalGod79** [comment]
from:
https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap

> Plugins:
>  Centralized website for all available plugins.
>  Better support for total overrides.
>  Viewing and editing a list of installed plugins.
>  Show plugin about text for each plugin.
>  Downloading new plugins in-game, from a website repository.

**Comment by Wrzlprnft** [comment]
Remove the text files from the game data folder or the plugins folder until we have a more triple A solution

**Comment by Alkallid** [comment]
Or have a seperate folder on your computer to drag plug-ins in and put of to activate so you don't need to re-download them every time.

**Comment by Disiuze** [comment]
A solution to making mods load in a specific order is to put numbers in front of them like "000_plugin" so that any plugin that comes after 000_plugin will overwrite 000_plugin's contents, provided it is trying to do so. A few mods already do this, I think.

**Comment by warp-core** [comment]
Who merged #7192 and didn't close this?
