### ISSUE TITLE
[question/enhancement] Follow Target

### ISSUE THREAD

**Issue by NickGrease** [endless-sky/endless-sky#1258]
I may be remembering incorrectly, but did't EV/Nova have a keybinding for 'Follow Target' that would align your ship in the direction of your target (and full throttle, I think)? I've only been playing a few days, and auto-aim seems to partially work in pointing your ship the right way, as long as it's an enemy, and already in your general bow direction. Seems impossible to follow/align to friendlies off screen, not to mention planets/stations which, again, I seem to remember doing in Nova. The very non-obvious white dot around the target display reticle helps, but getting your ship going in the right direction seems clunkier  then it needs to be. 

Anyways, I want to thank everyone involved in making this great game.

**Comment by Alkallid** [comment]
Pressing the land key can get you in the direction of any planets, and so usually the center of the system if you maybe happened to idle and drift off. Generally all ships will be around there, so I don't really see the need unless you're pirating merchants in uninhabited systems.

**Comment by NickGrease** [comment]
This has more to do with keeping your forward guns pointing at the target than where ships are generally located in the system. It made switching targets and facing/moving toward them them a lot easier, especially if the targets were offscreen. The AI can do it, the original game could do it, and at this point, my muscle memory still has my finger searching for the follow key :) Maybe I'll get used to it, but I miss being able to do a fly-by, coast for a bit, hit a key to rotate to target direction and fly head on guns blazing.

**Comment by Alkallid** [comment]
Ah, so moment strafing?

**Comment by NickGrease** [comment]
Sorry, I'm not sure where the confusion is coming from. Either it wasn't in the original, which is explains your response, or it was, and you're suggesting I was the only person to use it. Either way, I would find it useful to have a key that would align your ship to the target.

**Comment by LocalGod79** [comment]
duplicate:
#166

**Comment by NickGrease** [comment]
Thanks @LocalGod79
