### ISSUE TITLE
Balance: Comet Class Steering Efficiency

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1262]
Is the comet class steering intended to be this bad compared to the lunar class steering?

http://steamcommunity.com/app/404410/discussions/1/358415738187829398/

An energy value of 1.4 and heat value of 4.1 bring the Comet steering in line with the rest of the Korath steering.

**Comment by endless-sky** [comment]
Yeah, I mistakenly gave it the values for the thruster instead of for the steering. Wish I'd seen this *before* doing the new release. :)
