### ISSUE TITLE
Deep Archeology: Evading Deep ships in mission 3 should have an effect on the following missions

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1263]
Deep Archeology 3 and 5 have the same ships following you: `D.P.S. Wyrd`, `D.P.S. Skuld`, and `D.P.S. Verthandi`. If we can destroy them somehow in mission 3 (for example, annihilating the ships with a decent fleet or luring them into a fleet of pirates to annihilate them for you), it should have an impact on the story, what with them not being able to attack you in mission 5 since they don't exist.

**Comment by jafdy** [comment]
Unless you code for each ship in DA 3 and more code for DA 5 for every possible combination (8 missions). Of coarse I may be wrong.

**Comment by Amazinite** [comment]
A combination of #5248 and the NPC spawn/despawn node would make this possible.
