### ISSUE TITLE
outfitter should warn if you have no energy generation

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1264]
I think it's valid and even kind of interesting to have a ship that runs on batteries so it'd be nice to keep it as an allowed thing, but I do think the outfitter should warn you if your energy generation drops to 0 during your visit to the outfitter. If it warned just because it saw a 0 it would warn you every time your battery boat went to an outfitter which may not be desired.

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/1/358415738182471848/

Someone has managed to not realize that he installed a battery not a generator.

**Comment by Bladewood** [comment]
*regenerator shields*

**Comment by Alkallid** [comment]
I think pirates did that.

**Comment by MarcelineVQ** [comment]
as far as I can deduce, pirates can only steal things from the cargo hold
