### ISSUE TITLE
[bug] Player Info Page

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1266]
When you clicked a ship in the player info page, it brings up the park or unpark button at the bottom of the interface as if you shift clicked it, so you need to double click ships to actually get to their info.

Just opened the info screen
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/16354534/fadef25c-3a64-11e6-8d6c-3d22bfeac3d7.png)
Clicked one of my ships to see the info, but instead if just makes the park button appear.
![screenshot_3](https://cloud.githubusercontent.com/assets/17688683/16354535/fe7b81b4-3a64-11e6-94be-df10455b6eac.png)

Also, clicking your flagship brings up the "unpark" button at the bottom no matter what and it does not allow you to actually park it.
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/16354536/012767d4-3a65-11e6-9cbe-fcf0d900aedb.png)
Given that when you go to the ship info of your flagship there is no park button at the bottom, I would think that this unpark button is not suppose to even show up, hence why you can not toggle it.

**Comment by MarcelineVQ** [comment]
The first thing is due to being able to select multiple ships now. Possibly it could be changed so that you need to ctrl+click to start selecting ships, which is how you cherry-pick ships currently, though that would result in less people discovering the selection feature on their own.

**Comment by Amazinite** [comment]
What it should be changed to is that you need to shift+click for it to show the park/unpark button at the bottom of the player info page. It's acting as though you shift+clicked, but in reality you didn't.

It won't select multiple ships without shift+clicking, so there's no point in also adding a ctrl+click to it.

**Comment by MarcelineVQ** [comment]
Just to be clear are you aware that you can currently select multiple ships using ctrl+click?

**Comment by endless-sky** [comment]
Right now, the mechanics are designed to work the same way as file selection does on just about every OS out there. Nearly every computer user will already have those rules in their head, at least implicitly, so following those rules exactly will avoid confusing the user.

**Comment by Amazinite** [comment]
>Just to be clear are you aware that you can currently select multiple ships using ctrl+click?

It is to my understanding that in pretty much every case, shift+clicking is used to select multiple things while ctrl+clicking is used to deselect things. Are you saying that in this case both shift+click and ctrl+click allow you to select multiple ships at once?

**Comment by Amazinite** [comment]
Fair enough.
