### ISSUE TITLE
[bug] "abort mission" and "done" buttons overlap

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1268]
on monitors at 1024x768 resolution

**Comment by endless-sky** [comment]
<2% of Steam users, and probably the same 2% that also have only 256 MB of VRAM. :)

Given that the key shortcuts still work or that you can just switch to a different panel (Ports, Shipyards, or Outfitters) and then click Done, I'm not sure this is worth fixing. For everyone else I'd consider it an improvement that the same buttons are in the same place on all the map panels now.
