### ISSUE TITLE
Can't Turn, Can't jump

### ISSUE THREAD

**Issue by mlgrote** [endless-sky/endless-sky#127]
So I died. Which was fine, I had to work the next day. I restore my game today and I can't jump to lightspeed or turn my ship. I hit "L" to land, except I don't land. I can thrust forward though.

**Comment by sirkyuubi** [comment]
I'm also having this exact problem.

**Comment by mlgrote** [comment]
Find your save file (it should be a simple text file named after your character) open it and above your hyperdrive type in "X1200 Ion Steering" (no quotes). That should fix your steering.

**Comment by FruitWave** [comment]
I've built a new ship (the code) using some online tools. Everything works--except for the steering. Because I can't turn, I can't jump or land.
The real kicker is that it clearly lists a powerful steering and a powerful thruster.
Please assist!

**Comment by MCOfficer** [comment]
maybe the steering draws more power than the thruster? what components did you use?

**Comment by tehhowch** [comment]
Without seeing anything useful, we cannot help. That said, Content Creating troubleshooting (as opposed to bugs in existing game code or feature requests) is better suited for the Endless Sky Google Groups, Discord server, or Steam subforum.

**Comment by FruitWave** [comment]
Uhhhh....I intend to make more ships (this is my first), so it's really overpowered. Just for sh**s and giggles. Anyways, ship code below, and then the current save code. Tysm for replying so quickly.
[hellhecklershipcode.txt](https://github.com/endless-sky/endless-sky/files/1609237/hellhecklershipcode.txt)
[Harken Digm Delifeu.txt](https://github.com/endless-sky/endless-sky/files/1609239/Harken.Digm.Delifeu.txt)

**Comment by FruitWave** [comment]
I did post it to the Steam forum as well

**Comment by FruitWave** [comment]
@MCOfficer im using
"Triple Plasma Core" x 1
"LP036a Battery Pack" x 1
"Antimatter Core" x 100
	"nGVF-BB Fuel Cell" x 1 
"Armageddon Core" x 100

**Comment by FruitWave** [comment]
Update:
I just removed all but 4 of the dual sunbeams to make inspecting the ship easier

**Comment by tehhowch** [comment]
We replied quickly because we receive notifications, as do at least 100 others. GitHub is a place for resolving feature requests and bugs in the current game (see Contributing.md, a file that is suggested to be reviewed when one attempts to create a GitHub Issue), and not problems with why some custom ships aren't working quite right.
Please focus your assistance requests on Steam or Discord.

**Comment by FruitWave** [comment]
@tehhowch yea yea i program too i know this

**Comment by MCOfficer** [comment]
since you received a lot of replies & help [on steam](https://steamcommunity.com/app/404410/discussions/0/1621726179574241176/), i guess one can close this issue now.
