### ISSUE TITLE
Buying outfits that require crew may silently abort missions

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#1270]
I was doing the Terraforming Rand mission earlier and bought a turret along the way. The mission was suddenly gone, and I had to backtrack several times before realising that this was because the turret requires a crew member and I didn't have the bunks available for both. Would it be possible to implement some sort of warning to avoid this happening?

**Comment by Wrzlprnft** [comment]
I think it is displayed in the chat in the bottom left when leaving the planet. But i guess you're looking for a more straightforward warning.

**Comment by lheckemann** [comment]
Yes — there are warnings for such things as selling conventional cargo (which is easily replaced), while storyline missions are a little more of a pain to lose.

**Comment by endless-sky** [comment]
Merged #1271 to fix this. Tweaked it a bit in 4accbec.
