### ISSUE TITLE
Issue #744 is back

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1272]
Remember [this](https://github.com/endless-sky/endless-sky/issues/744)?
It's back, apparently.

**Comment by Alkallid** [comment]
Exactly?

**Comment by Amazinite** [comment]
Are you sure? I can't reproduce it anymore.

**Comment by Bladewood** [comment]
Yes, I'm sure, although it might be a different bug :|
While docked, select a neighboring system. Leave the planet, and try to deselect it.
It doesn't work for me.

**Comment by MarcelineVQ** [comment]
You don't need to land at a planet, simply exiting the map screen with set it as you describe. I can reproduce this issue but I don't really see it as a problem, what would the advantage of selecting no path be? One will still be chosen if you hit 'j' in the main view.

**Comment by Alkallid** [comment]
Yes, what was the initial point of doing this?

**Comment by Bladewood** [comment]
Accidents.
Accidents, lots and lots of annoying accidents :|
There may be no good point, but if that's true, what reason did Michael have to apply commit https://github.com/endless-sky/endless-sky/commit/81ceac70ce49205f07b5a0b595cb935a35386987?

**Comment by MarcelineVQ** [comment]
Dunno for sure, the code's changed quite a bit since then so it may have had more consequences than it does now.
It's the same root cause though so maybe a pr is in order.
