### ISSUE TITLE
In missions on the "reconcilation" path, in battles against the Syndicate, you can bribe your way to victory

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1276]
For example, on my current mission, `FW Syndicate Capture 1B`, we are assaulted by hordes of Syndicate ships that try to nuke us. I have found that the easiest solution is to bribe my way through as soon as I enter the system. Unlike Republic ships, the Syndicate can actually be bribed while you're playing through the storyline.

This was not how I beat it on my first run, but I found that flying with the most overpowered ship in the game, the Bactrian, is surprisingly difficult during some sections of the campaign. Luckily, the Syndicate is greedier than any other group in human space.

**Comment by endless-sky** [comment]
Fixed in 5be9082.
