### ISSUE TITLE
Can't relaunch "Liberate Kornephoros" Mission

### ISSUE THREAD

**Issue by Mcgode** [endless-sky/endless-sky#128]
So here's the issue:
Sooner, I started the mission after flying away like a coward during Longjump attack, and it turned out, after dozens of deaths that this mission was impossible at this state of the game (if I don't die at the beginning, we get recked by the Navy's cruisers), due to incredible difficulty of the mission, or to my weak ship (Raven then Bastion).
So I decided to abort the mission during some time in order to increase my firepower by farming credits to hell. When I finally got a better gear, I tried to go back to Longjump, where I first launched the mission, to relaunch it, but I can't. I can't find any planet where I can launch the mission, and I'm basically stuck.

**Comment by endless-sky** [comment]
Yes, if you abort a main-story mission, there's no way to pick up the story line again. I'd recommend saving snapshots more often so you can back up a bit if that happens.

**Comment by Mcgode** [comment]
I was able to fix it by changing my save file, thanks to the missions data files. I was able to finally win this battle so not a problem anymore.
Although I would suggest to make story missions unabortable, that should help a lot.
