### ISSUE TITLE
Suggestion: Pug ships at Pug Iyik should be Tier 2 ships

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1282]
During the Human-Pug war, the Pug use ships of the Tier 1 category, just like humans. I think you should replace the ships at Pug Iyik with Tier 2 ships, or at least give them Tier 2 equipment, to put them on the same level as the Wanderers and the Korath. If you go through the effort to give the Pug a Tier 3 ship for fighting the Quarg (and annoying lesser than-Tier 3 races), should you not give them a Tier 2 ship for fighting [Tier 2 races] as well?
[(source)](https://groups.google.com/forum/#!searchin/endless-sky/tier$203/endless-sky/bdBvklrIoPw/hhAgFR-jEAAJ)
On a side note, the Quarg claim that the Pug have previously lost to much less advanced races, implying that they used ships of a lesser tier (although I'm not sure how that would be represented in this ranking system). Other than maybe humans being the dominant race of the galaxy, there is no point in having the Pug's Tier 1 ships as the "base" of their fleet.

I'm sorry if this is hard to read or if there are conflicting thoughts, it's getting late over here :(

**Comment by onnikyla** [comment]
This would be a great feature, but I think this should wait till human, hai, wanderer and the korath story are fully done, and a few more pug planets are added. If this gets done now there will probably be a lot of unnessasary tweaking later on.

**Comment by jafdy** [comment]
It's a lot of work for a change in one systems fleets.

**Comment by LocalGod79** [comment]
i'm not sure that this is necessarily true: the Pug are not fighting the Wanderers or Korath, or vice versa. 

in fact, the Wanderers appear woefully ignorant of any of their neighbours excepting the Unfettered (and even them...) until the player arrives.

there is not currently any story to indicate that tier 2 Pug ships exist (though admittedly implied that they probably do).  when it comes along, i'm sure they'll be added...

**Comment by jafdy** [comment]
The Wanderers do have some idea about the existence of the Pug, although I don't see them ever fighting the Pug unless they are attacked first. See `mission "Tell Wanderers about the Pug"`.

**Comment by endless-sky** [comment]
In terms of story, there's no big need for Tier 2 Pug ships yet. The Wanderers are the pet project of that particular group of Pug, so they are not going to attack the Wanderers.
