### ISSUE TITLE
[Bug] Forced sale of drone breaks UI

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#1287]
1. Capture a drone while not having any space for drones
2. Land on a planet (might require the planet not to have a shipyard for the bug to occur) without parking the drone
3. Go to Trading, Bank, Space Port or Hire Crew panel
4. Leave planet (accept drone sale)
5. This happens
![Drone bug](https://sphalerite.org/es-drone-bug.png)

**Comment by lheckemann** [comment]
Tried it again, it didn't happen :/

**Comment by MarcelineVQ** [comment]
Any of the full storage popups do this if you have another planet panel open when you leave (bank, hire, trade, etc), it's fixed in https://github.com/endless-sky/endless-sky/pull/1271 but I have to do some work on another part of that before it's accepted

**Comment by lheckemann** [comment]
Great!

**Comment by endless-sky** [comment]
Fixed this in in commit bcf5f8f, by applying part of @MarcelineVQ's PR.
