### ISSUE TITLE
"Varu K'est" can still be visited after the Unfettered have conquered it

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1288]
You can't bribe them to let you in, of course, but you can sell them a jump drive on their other worlds and it works.
Also, it appears that, when selected in the map, it is entirely unchanged. The planet description and the shipyard and outfitters are the same.
It's also unchanged when you actually dock there.

**Comment by toilethinges** [comment]
The Unfettered never conquered it, according to my research in the files. It looks like they're just being raided?

**Comment by endless-sky** [comment]
That invasion is really just a hook for the plot continuation (to avoid the problem I had in the last few releases, where I hadn't yet scheduled whatever event would advance the Wanderer story, so the new story wouldn't show up right away when you loaded the update). That said, I probably should've changed the planet description, and maybe the jump drive missions should no longer be offered if you've helped out the Wanderers this much.

**Comment by endless-sky** [comment]
Fixed in 8b4e43d. It's not quite perfect because the description won't change for players who have already gotten to that point, but it's too minor an issue to warrant a "patch" mission just to change the planet.
