### ISSUE TITLE
Autopilot should use reverse thrusters

### ISSUE THREAD

**Issue by gdcolella** [endless-sky/endless-sky#129]
When I purchased reverse thrusters, the autopilot doesn't use them to slow down when entering a system (in preparation for another jump).  This would make them much more useful!

**Comment by davefp** [comment]
:+1:

**Comment by Dr-Terrible** [comment]
:+1:

**Comment by Mcgode** [comment]
👍

**Comment by PhoenixRiver** [comment]
Makes them much more useful on freighters with rubbish turning thrusters! :)

**Comment by endless-sky** [comment]
Commit c62a5d7 adds AI support for reverse thrusters when landing, boarding, and coming to a stop for hyperspace jumps.

Eventually I will try to figure out how they can be used for combat, as well. Like, if a ship strafes its target at high speed, should it use reverse thrusters to stop and turn around more quickly for a second pass? Or should it keep going at full speed until it has turned to face the target again, to avoid getting shot in the back while its weapons are not yet pointed at the target? And, I suppose a ship might also use reverse thrusters to stay pointed towards a target while kiting away from it.

**Comment by PhoenixRiver** [comment]
Hello :)

> Commit c62a5d7 adds AI support for reverse thrusters when landing, boarding,
> and coming to a stop for hyperspace jumps.

Just this makes a huge difference for some freighter fleet
configurations :) - thank you

> Eventually I will try to figure out how they can be used for combat, as
> well. Like, if a ship strafes its target at high speed, should it use
> reverse thrusters to stop and turn around more quickly for a second pass? Or
> should it keep going at full speed until it has turned to face the target
> again, to avoid getting shot in the back while its weapons are not yet
> pointed at the target? And, I suppose a ship might also use reverse
> thrusters to stay pointed towards a target while kiting away from it.

If the ship it is fighting only turns slowly reverse thrusters would
help keep it in range while behind the ship (useful if it has turrets
but also if it can turn quicker than the opponent)... backing up from
an opponent while keeping guns trained on them would also be useful,
especially with ranged weapons and for running away from high dps but
short-ranged attackers.

**Comment by endless-sky** [comment]
This issue is fixed in 0.8.8, and 0.8.8 is now the default on Steam, so I'm closing this issue.

**Comment by HamsterBoo** [comment]
I've noticed that the AI for reverse thrusters tends to overcompensate in a weird way. I put a ton of reverse thrusters on a bactrian (I think I actually have more reverse thrust than forward thrust) and every time it goes to land on a planet it gets close and:

1. Starts reversing
2. Starts turning
3. Stops everything when its 10-45 degrees turned.
4. Drifts a little bit past the target.
5. Reverses a tiny bit
6. Goes forward a tiny bit and lands.

It's worse with boarding, but that's harder to characterize because it tries to line your ship up with the target.

**Comment by tehhowch** [comment]
@hamsterboo Open a new issue with exact loadout and use case (e.g. post a video on YouTube showing all the details). 
Also include how you play the game, i.e. what game version or commit you play from.
