### ISSUE TITLE
Republic ships doing multiple scans

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1291]
Independant ships seem to be doing inordinate amount of scanning, I'm getting as many as 28 scans at one time from a single gunboat against a single flagship that make it to Politics::Fine
The check from AI::MoveIndependent that sets the Command::SCAN bit seems to let a lot of these extra scans through, is it possible that many scans are able to be enqueued before they end up in AI::Has for the ship doing the scanning?

Redundant scanning aside this issue has the effect of massively reducing the effectiveness of interference plating.

**Comment by LocalGod79** [comment]
if a fix is implemented, a proportional increase in fines should also take place so that statistically, someone carrying Nerve Gas is still just as likely to Pay The Man the same amount per system visited...

**Comment by MarcelineVQ** [comment]
I think the numbers are working as intended in terms of when fines should occur and how the value of plating stacks vs a ship scanning you: it's just that too many scans are being allowed to be done at once.
Currently if you avoid paying up it's almost solely just due to a ship not targeting you for a scan in the first place.

The equation for skipping a fine is:
```
if(Random::Real() > 1. / (1. + ship->Attributes().Get("scan interference")))
    continue;
```

Such that Random::Real() is a floating number between 0 and 1. The more plating you have the more likely it is for random to roll higher than the right side of the equation and skip doing a fine.

With 20 plates your odds of avoiding a fine when scanned once are about 91%, not too shabby, seems fairly reasonable for that many. By contrast 5 plates gets you to 71% and 10 plates gets you to 83%, diminishing returns.
But, assuming I'm doing the math halfway decent, your odds of avoiding a fine from 28 scans with 20 plates is 7%. And with just 11 plates it's less than 1%.

Consider that you currently also tend to get scanned by multiple ships at once since things move in fleets and that number becomes fairly infinitesimal. Though I'm not sure if that's intended either since I think you only get one "you are being scanned by" message per fleet, or possibly per the ships that were present when that message was sent.
Fines may need to be looked at again when things are in order but I want to make the point that currently if you avoid a fine it's mostly because you got out of the system before something came by and scanned you.

**Comment by MarcelineVQ** [comment]
The check failing seems to be caused by cargo and outfit scanners having different ranges, so when a ship has both and it's in range for just one it still tries to queue for both other which causes the one in range to pile up while it waits for the other to be in range too. I'm not quite sure how to tackle it but hopefully that narrows down the problem.

**Comment by Sinsling** [comment]
I would like to point out a fleet will do multiple scans of you. One carrier trying to scan you can launch a number of serveillance drones, on top of any gunboats/rainmakers that may be with it. I'm pretty sure the break-down on that turns into something like 110+ scans off a good sized carrier fleet based on your numbers. A 91% evasion chance becomes pretty abysmal by that point.

**Comment by endless-sky** [comment]
This is addressed in commit 40d87c4, which makes it so the scans take time but will stop once a scan of that particular type has been performed on the current target.

**Comment by MarcelineVQ** [comment]
Mechanically this issue is fixed. Interference plating is now a good investment, very likely too good as @LocalGod79 was concerned about, but that's not relevant to this fix.
A separate issue caused by this change is that the message "The <gov> ship <name> is attempting to scan you." will get spammed to the message box while the scanning is ongoing.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
