### ISSUE TITLE
"Collective" fleet personality

### ISSUE THREAD

**Issue by Disiuze** [endless-sky/endless-sky#1297]
A "collective" fleet personality could be useful for fleet that depend on every ship of the fleet.
However, if one, or more, of the ships die, then the rest of the ships begin to exhibit what happens when you do not have enough crew for a ship.
This could be very useful for hivemind aliens who are dependent on each other

**Comment by Bladewood** [comment]
I was going to put an argument against this here concerning how the not-enough-crew mechanism actually works, but I seem to have lost my source.
