### ISSUE TITLE
Not one ship in the game actually has a gun-mounted Korath slicer

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1300]
I've checked every byte of the game files for it (and so have others like Alkallid), and I can conclude that not one ship in the game actually has a gun-mounted Korath slicer. It's just a mysterious piece of text above the slicer turret, with an equally mysterious image file in the outfit folder to match.

So then it's impossible to obtain. That's sad. I'd have preferred it over that silly little contraption they call a minelayer. (mostly because it doesn't involve any of that "limited ammunition" stuff)

Unless you plan to add it later and have the Wanderers reverse-engineering Korath weapons or something.

**Comment by Amazinite** [comment]
Yup.
Only Minelayers.

**Comment by Amazinite** [comment]
It would also appear that the gun port Korath Slicer requires crew...

**Comment by KiLEdEnNis** [comment]
there are old items like the Antimatter Core (which was the Quarg reactor, but the ships themselves generate the energy/heat now), I'm not sure if the Korath Slicer was ever equipped in a previous update (if so it'd be kinda the same as these kinda outfits), but I think they made it and forgot to use it
adding a black market w/ alien technology in Kor Efreti space would be cool AND fix the issue :3

**Comment by Alkallid** [comment]
No, it  came the same in the Korath update.

**Comment by KiLEdEnNis** [comment]
then again I'd suggest that black market idea

**Comment by toilethinges** [comment]
I don't think the Efreti are capable of taking stuff from the Mereti - otherwise, they might be rocketing around Mereti ships, or toting Mereti weapons.

**Comment by Bladewood** [comment]
The Kor Efreti have bigger problems than lack of warship diversity. Namely, their imminent extinction.

**Comment by KiLEdEnNis** [comment]
the Command Center's description suggests that the Kor Efreti captured some AI ships, so that means they'd have some of the outfits as well

**Comment by endless-sky** [comment]
My plan is for the Kor Mereti drones to gather most of their raw materials via asteroid mining (once that's implemented and supported by the AI). That was the main reason for a gun-mounted Slicer, because asteroids will be all hull and no shields, making it an ideal mining weapon.

**Comment by KiLEdEnNis** [comment]
then adding a "Model 8" that's made for mining could go with that, or having the smaller models appear more as miners could help too, so that the idea is that new models would mine for resources (& "pay" a bit to bigger drones) and then gear up, and after becoming like model 64/128 they get income from the smaller ones
just an idea :)

**Comment by endless-sky** [comment]
As of commit 02835bf, the new "Model 8" Kor Mereti mining drones use them.

**Comment by KiLEdEnNis** [comment]
just noticed my idea actually got added, proud of myself

**Comment by Bladewood** [comment]
wee
