### ISSUE TITLE
hardpoint refactoring variant issue

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1303]
Hardpoint refactoring 47749bbf43423bd7bb3494e80fdc3df909610259 has caused an issue loading variants, specifically in the Korath World-Ship B/C but possibly elsewhere. The difference between world ship variants happens to be just the sprite image and turrets which may be why it's more apparent with them.

The issue seems to be that the base ship's outfits are for some reason overwritten entirely instead of being modified resulting in ships that can't move, since they don't have engines, and oddities in the boarding list.

Boarded affected worldship:
![worldship](https://cloud.githubusercontent.com/assets/16345659/16611459/3da88076-4316-11e6-860e-2b2942a51080.png)

**Comment by endless-sky** [comment]
Commit 7f1d47a should fix that.
