### ISSUE TITLE
Bug: Pirates suddenly like me

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#1304]
I don't know how this came about, but pirate ships suddenly aren't hostile to me anymore. Is this meant to happen, ever? Hailing them also just gives blank responses. Is there any way to find out how this could have happened?

On a side note, it's fun to sit about in a Pirate world repairing both Pirate and Syndicate ships that are battling it out.

**Comment by MarcelineVQ** [comment]
Can confirm, friendly pirates have blank responses. The blank responses means something's wrong but often if pirates fall in love with you it's because you beat up a lot of Korath, or possibly Syndicate or Merchants.

**Comment by lheckemann** [comment]
Ah right, it's the Korath then. Thanks for the info! Should this really be possible though, at least with the Korath?

**Comment by Alkallid** [comment]
They just have no friendly hails. They're pirates.

**Comment by MarcelineVQ** [comment]
The game treats Pirates like any other government and basically you're beating up their enemies so you gain reputation with them. You start at -10 rep with them so it's not too far to go to make them neutral or friendly.

```
government "Pirate"
...
"player reputation" -10
"attitude toward"
	"Merchant" -.1
	"Syndicate" -.1
	"Korath" -.1
	"Author" -.1
```

There are some cases, I think, where reputations don't change despite the player's actions. Korath rep can be lowered by attacking them but Kor Mereti and Kor Sestor don't lose reputation when you attack them for example. You can't gain Kor Efret rep by killing their enemies (Mereti or Sestor). Little oddities, I'm not really sure about the mechanics behind that.

**Comment by Wrzlprnft** [comment]
Reputation is based on the crew count of ships you have disabled.

**Comment by MarcelineVQ** [comment]
Oh I see it's in Politics::Offend, thank you @Wrzlprnft
