### ISSUE TITLE
dual carry tokens for drones too [enhancement]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1305]
currently only fighters appear to be able to use the under/over token coupled with right/left/back token.

**Comment by endless-sky** [comment]
Are you sure you don't have some sort of syntax error? I tested it with a Tek Far 109 and both types were displaying properly.

**Comment by LocalGod79** [comment]
i think actually, i was compiling Wrzlprnft's Hai Carrier branch, which has not been updated from master since the commit that enables them...

**Comment by Wrzlprnft** [comment]
While wrzlprnft can actually point to the merge commit 5 days ago which contains the changes of the commit that introduced that option. I think this may be one of the phantom bugs?

**Comment by LocalGod79** [comment]
i was using the Hai carrier branch, which had not been updated...

resolved.
