### ISSUE TITLE
Allied Ship Lost Hyperdrive

### ISSUE THREAD

**Issue by CubicDolphin** [endless-sky/endless-sky#131]
TWO of my allied ships lost their hyperdrives while in a system without outfitters to equip a new one, or shipyards to sell the ship. Now they just float around in that system, charging me crew costs and worrying me that they will die and I will have to pay massive death benefits. Is there any way to remove them or equip them with a new hyperdrive?

**Comment by nebruin** [comment]
I have a similar issue, my 2nd escort cargo ship was damaged, and I boarded it to repair it, and then landed on a planet, and it was marked as fully repaired, but when I depart the planet the ship doesn't follow any commands, and just drifts in to space.

**Comment by DerekTheMorris** [comment]
Same here. Boarded a disabled fighter, captured it, then found that it had no engines. Now i cant move it, and i cant figure out how to re-equip it with engines.

**Comment by endless-sky** [comment]
It may have been plundered by someone before you boarded it.

Also, there's a bug in the 0.8.4 release where when a ship is plundered, it behaves like it still has engines, etc. until the game is reloaded.

**Comment by nebruin** [comment]
I've reloaded the game (using 0.8.4) and my ship still seems to be stuck in drift mode. I can send you my data files if you want them.

**Comment by nebruin** [comment]
In case anyone else has this issue, you can work around it for now by editing your save file and adding the engines you need. For me my save files were on C:\Users\USER_NAME_HERE\AppData\Roaming\endless-sky\saves

You will probably need to look at other ships you have, or look at old save files to edit your current ship to have the right equipment. Longer term I think there needs to be a gameplay way to fix this, but this allows you to continue for now at least.

**Comment by endless-sky** [comment]
As of 0.8.7, pirates no longer steal outfits out of ships, because it was just way too confusing for players who did not notice one of their ships had been plundered.
