### ISSUE TITLE
Include salary and tribute under the "bank" tab

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1310]
Because I'm too lazy to subtract 6000 credits and tribute payments from my crew salary and mortgages.

**Comment by MarcelineVQ** [comment]
I like the idea.  While the Bank tab is already pretty crowded having Other appear one row sooner if needed probably isn't that big a deal. Another addition while the bank tab is getting some love could include the 'total' row also tallying your principal total or [Pay All] having a confirmation dialogue that says what you'll pay.

**Comment by LocalGod79** [comment]
perhaps this is a good time to add a new "Finances" tab to the player info screen?  we've additionally had requests for more detailed tribute display which could help fill that amount of ui space (in addition to displaying more mortgages, which would be rearrangeable similar to fleets?)...

it's a big task, but i can't think of anywhere else you could cram this much info...

**Comment by endless-sky** [comment]
Added in 4832cd3.

**Comment by Bladewood** [comment]
It worked _very_ well.
![imrich](https://cloud.githubusercontent.com/assets/16506683/18236748/a814b626-72f7-11e6-9120-230f9baf5d7f.png)
