### ISSUE TITLE
Pirates and Navy ships can appear in Nocte (and probably Orvala as well)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1311]
After a quick check on the files, it appears that for Nocte and Orvala, all you did was change the governments, without changing the fleets. Thus pirates and Navy ships can spawn in the Nocte system, and probably in Orvala as well. This also implies that the Pug cannot spawn there.

**Comment by MarcelineVQ** [comment]
Those are non-landable systems right? Pug might not care about policing them.

**Comment by endless-sky** [comment]
Fixed in 4e0cfaa.
