### ISSUE TITLE
[question] Is Flycatcher Category Correct

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1314]
Flycatcher is currently an Interceptor. Was flycatcher supposed to be in the Fighter or Drone category? It lacks hyperspace and fuel and its stats seem to be more in line with a Korath Chaser than the outfit space typical of interceptors. If it's the way it is for flavor then that's totally cool but making it available to the player is a little weird since it can't be transported.

**Comment by Disiuze** [comment]
I think it's because Fighters and Drones can't independently take off from planets (i. e. without a carrier).

**Comment by Alkallid** [comment]
I think it's right, as Euroman said, because they are more for defending systems while the Leafs(?) are patrolling.

**Comment by Amazinite** [comment]
It's the same reason why the Earth Shaper is considered a light freighter. While it is technically a surveillance drone, it could not be independent of labeled as such.

**Comment by MarcelineVQ** [comment]
That's fine but it's still weird to sell it to the player as it is :>
@endless-sky Would instead selling a Drone Category variant be appropriate for players? The equipment totals needed to make this unit able to travel between systems leaves little room for usefulness. If it's just a variant the wanderers can use it as they are but players can find them useful too.

**Comment by KiLEdEnNis** [comment]
maybe the Wanderers should get a ship that can transport ships below a certain mass amount, whether clamped on the outside or stored on the inside (like a slender long ship that has a transport clamp where a ship can be stored under it), that would fix the issue and create new possibilities for the future

**Comment by Amazinite** [comment]
4ec09c9
