### ISSUE TITLE
in-game screen messing up

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1316]
so if you press D (to depart) and H (hold position/hire crew) immediately after the game launches the ship but goes back to the menu to hire crew, and this will probably happen with the T, J, B and P keys as well (which are the planet shortcut keys)
loading the game again fixes it and probably nobody will ever have that issue but it may be useful to know
![game screen mess](https://cloud.githubusercontent.com/assets/10348657/16807478/e1b109ec-4918-11e6-99b9-ccf8cf61dd27.jpg)

**Comment by endless-sky** [comment]
Are you building from source, or using the pre-built binary for release 0.9.2? This should have been fixed by commit bcf5f8f, unless there's some other case where it can crop up.

**Comment by toilethinges** [comment]
I can reproduce with the current stable Steam release.

**Comment by KiLEdEnNis** [comment]
I'm using Steam and I use the latest version (Beta versions too, usually testing new content, so maybe I could be a Beta tester), but from what I understand it's not the same issue, that "fix" was that the panel remains after depart, I never had that, what I did was depart, and press a shortcut too quickly so that I departed AND went to the hire crew section, or is that the same issue?

**Comment by endless-sky** [comment]
Fixed in commit 59b4808. The issue seemed to be that the two commands - depart, and show the hiring panel - where being received simultaneously and both got acted on.

**Comment by KiLEdEnNis** [comment]
I thought so, keep up the great work, my milestone = 1000 hours ( ͡° ͜ʖ ͡°)
