### ISSUE TITLE
Republic fleets appear in Lesath after starting FW Checkmate

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1317]
in the main story you get a choice, save a guy from the Syndicate and make peace with the Republic or ignore it and start the Checkmate plan

when choosing the Checkmate plan, after recapturing Delta saggittarii (since you were cut off), the uninhabited Lesath sector remains with these fleets in the save file:
system Lesath
	fleet "Small Southern Merchants" 6000
	fleet "Large Southern Merchants" 9000
	fleet "Small Republic" 1000
	fleet "Large Republic" 1000
	fleet "Large Free Worlds" 800
![lesath checkmate issue](https://cloud.githubusercontent.com/assets/10348657/16808878/92916c52-491e-11e6-983d-0743291f8b0e.jpg)

I played Endless Sky over 350 hours (yes I have a life) and I saw dozens of (possibly unfixed) bugs/typos but I only really figured how to use Github now (and this was 1 of the most annoying bugs, so when I play the story a 7th(?) time I'll look closely to bugs/typos and actually report them (sorry I never did, github confused me too much)

also in the picture, the unidentified sector top left is from editing

**Comment by endless-sky** [comment]
Fixed in 12d3304.

**Comment by KiLEdEnNis** [comment]
and I'm going to start closing my "fixed" issues (since after a week of Github it's time I do that) :)
