### ISSUE TITLE
Republic derelict ships in Checkmate reappearing after capturing

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1318]
when the FW Checkmate starts, the Wolf Pack "disables" Republic ships, which appear as derelict (I think, not sure)
anyway, if you win the battle, you can capture those ships, jump to another system, park them and repeat to get an infinite supply of Republic ships
they DO disappear after landing on the planet & ending the mission, but if you win a battle they will always reappear to be captured again

**Comment by Wrzlprnft** [comment]
Make a extra issue for the circumvent of the death benefits.

**Comment by KiLEdEnNis** [comment]
ok, on it, removed that from this issue

**Comment by Wrzlprnft** [comment]
It is way easier to keep track of it then :) thx

**Comment by endless-sky** [comment]
To clarify, are you saying that the mission keeps re-appearing and spawning derelicts, thus allowing you to literally capture an infinite number of them? Or just that you are able to capture a large number of derelicts because so many are lying around?

**Comment by KiLEdEnNis** [comment]
I can capture them, leave sector, park, and they actually reappear (and I'm sure since there were 6 Frigates, a Cruiser & a Carrier, and I had like 13 Frigates from that, so either 2 or 3 identical Frigates, because they had the same name)
so in short I'm 100% sure they reappear

**Comment by KiLEdEnNis** [comment]
playing on 0.9.4 on my laptop, the first Wolf Pack strike mission; I think only a cruiser or carrier reappeared, the rest disappeared after capture
I'll post if the rest disappears later today if I remember it

**Comment by KiLEdEnNis** [comment]
as far as I know it got fixed somehow
