### ISSUE TITLE
Can't Change Main/Pilot Ship

### ISSUE THREAD

**Issue by Calik666** [endless-sky/endless-sky#132]
Let's say I have a shuttle. I buy an Argosy. I want the Argosy to the be main ship I pilot and the shuttle to follow me. How is this done, or is it simply sell the shuttle and rebuy it?

**Comment by endless-sky** [comment]
Your first ship is always your flagship. You can click and drag the Argosy to the first position in your set of ships in the player info page, the Shipyard, or the Outfitter.

**Comment by fcfort** [comment]
This seems to work on intermittently on the Player Info page. If I hit "I" and bring up the Player Info page, I am unable to click & drag the ships. Every single time I try, I am brought to the Ship Info page for that ship. This seems to happen no matter where on the row for a given ship I click.

**Comment by endless-sky** [comment]
You can only reorder your ships when you are landed on a planet. Could that be why it's not working for you?

**Comment by fcfort** [comment]
Yep, exactly right, sorry about that. I can see why it makes sense in-game, but it could be made a bit more obvious what's happening.
