### ISSUE TITLE
Kraz Cybernetics ask to test flamethrowers (during FW Checkmate) when FW already uses them

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1320]
so it's about my 7th time I play the campaign (350+ hours), and it's going quickly because I kill everything in my path

anyway, as my previous issues may have shown, I'm in the FW Checkmate, and Kraz Cybernetics just messaged me to test flamethrowers, while I already captured Cebalrai and the FW already use them

so to fix that the story needs to "pause", then give that mission, and THEN continue w/ flamethrowers, since it makes no sense that the FW uses weapons that aren't yet released

**Comment by endless-sky** [comment]
It's an optional side mission, so I don't want it to block the main mission thread.

One option would be to have the flamethrower mission simply disappear if you don't do it by a certain point in the main plot, but that would be annoying (it would mean that pilot never gets access to the flamethrower).

**Comment by toilethinges** [comment]
@endless-sky, you could make it where the event for flamethrower sales is triggered the same time after you fail the missions as if you did the missions.

For clarification (I'm not being too clear here), say you get them on sale 30 days after you complete the mission. Make the mission have a some failing point (at a point where they show up on fleets) and set

on fail
_event "flamethrowers for sale" 30

or something like that.

**Comment by KiLEdEnNis** [comment]
maybe if you'd add some message later right before the FW implement the flamethrowers saying that he found someone else to test it instead if you didn't test it yourself it'd make sense, but all Kraz side missions are a bit weird, like testing plasma turrets: you can outrun the test ship, destroy the target, didn't test the weapon yet progress the mission as if you did
