### ISSUE TITLE
just a typo in the mission "FWC Pug 5"

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1325]
in the mission "FWC Pug 5", General Danforth says
"During the battle, we managed to salvage jump drives from a few of the Pug ships. We've installed them in three of our cruisers."

then the fleet: 3 "Carrier (Jump)"

those are carriers, not cruisers
poor Danforth getting old, forgetting the difference between Cruisers & Carriers
(& the Navy should get a Battleship, far better than Cruisers :3)

**Comment by toilethinges** [comment]
For the afternote, do you mean far better than Cruisers or Carriers? Carriers are the bigger, more powerful ones. :+1:

**Comment by KiLEdEnNis** [comment]
I mean better than both, like the Navy developes it at the near-end of the story, a battleship that can compete with alien species like the shield beetle, Korath raider and Wanderer strong winds (probably can do the last already)

**Comment by toilethinges** [comment]
Strong Winds belong to the Wanderers which, according to the chart on "storyideas", are Tier 2, meaning they are much more advanced than us. Looking at the ship and its outfits stats, you can tell that Strong Winds are much more powerful than any human warship.

**Comment by endless-sky** [comment]
Thanks. Fixed in 7aabd50.

I left out "battleships" from the Navy armada to give them the possibility of developing one later on (the same way that the FW develop Dreadnoughts), but I never got around to creating one...

**Comment by KiLEdEnNis** [comment]
yes my idea is that they make battleships in the story around the checkmate (where you encounter one) or when you all invade the Syndicate's extremists (also just one), and then giving the large fleets file a tiny chance for them to spawn (and giving you a Navy license after finishing the story would be nice too)
and in real life navy's have gunboats, frigates, cruisers, destroyers (also nice idea, because the Navy seems a bit dull & boring), carriers, battleships and dreadnought

but is there also a part to list game ideas? because I'm putting a few here and that may be annoying

**Comment by Bladewood** [comment]
[For the rebellion!](http://ftl.wikia.com/wiki/The_Rebel_Flagship)

**Comment by KiLEdEnNis** [comment]
For the horde!

**Comment by Bladewood** [comment]
Although, I do think a Battleship might be able to defeat a Strong Wind, depending on how powerful their engines are, the range of their weapons, how many turret mounts they have vs gun ports, ...

**Comment by KiLEdEnNis** [comment]
yes but I meant something that (however probably slower, unless w/ atomic/Korath engines) far outperforms Cruisers/Dreadnoughts, and that it would be able to compete against Shield Beetles, Korath Raiders etc.
and about fighters/drones, I personally prefer a change where they are smaller & only special turrets (AA) can target them, and Cruisers, Carriers etc. would get "special space" that doesn't fill outfit space, only AA space, and if/when fighters/drones die, they "respawn" after landing (even if you have to pay, it'd be better imo)

**Comment by Alkallid** [comment]
That isn't possible with this current engine, but I do agree that each main human faction are eventually going to get an ultra-ship, like Mega-Bactrian and Super-Carrier.

**Comment by KiLEdEnNis** [comment]
no I mean Navy gets Battleship, Deep gets an equivalent, Syndicate needs an actual "super ship", and idk about the FW, they did get the Dreadnought
and the huge ships (like that Battleship) should get a "special weapon capacity" where they can install a superweapon, like an extremely strong long range laser that passes through ships, but the reload should be extremely long & consume massive amounts of power

**Comment by Alkallid** [comment]
The Dreadnought is just their super ship.

**Comment by KiLEdEnNis** [comment]
yes I know, but they're on par w/ Cruisers, which aren't their super ships
renaming Dreadnought to Destroyer, then make an FW super ship (Dreadnought) & a Republic super ship (Battleship)

**Comment by Wrzlprnft** [comment]
https://github.com/endless-sky/endless-sky/issues/234

Look at the tag

**Comment by KiLEdEnNis** [comment]
my idea wasn't that they'd get that kinda super ships, but that at least the Navy gets a Battleship that's far better than a Cruiser and that it can solo a Korath Raider or something
(because the Navy doesn't develop ships, & the Cruiser/Carrier don't feel like flagships)

**Comment by Alkallid** [comment]
Everyone gets it; repetition is unappreciated.

**Comment by KiLEdEnNis** [comment]
yes, I just tend do be a bit unclear about the things I say
