### ISSUE TITLE
Having more than 2^31 cargo space causes negative trades.

### ISSUE THREAD

**Issue by hdhdhd95** [endless-sky/endless-sky#1326]
I created a ship that has 2^31 cargo space and when it trades anywhere the game gives negative money due to a overflow.

**Comment by davidwhitman** [comment]
Then don't do that?

**Comment by hdhdhd95** [comment]
> Then don't do that?
But how can I transport that much cargo then?

**Comment by Amazinite** [comment]
I don't think that anyone is ever going to realistically reach a cargo space that high. The same thing happens with any value; once it reached a certain (Massive with a capital M) point, it goes negative. But there is no realistic way to reach those kinds of points without modding in something that is massively OP and unbalanced.

**Comment by Amazinite** [comment]
Just to put it in to perspective, you would need 2,825,637 of the best freighter in the game to get that much cargo. It isn't realistic at all, so I think it's a non-issue.

**Comment by hdhdhd95** [comment]
It costs less than 4 Trillion to get that many ships.

**Comment by Amazinite** [comment]
It would actually cost 67.8 trillion to get that many of the biggest freighter.

**Comment by davidwhitman** [comment]
The dev could 'fix' this, probably fairly easily, by changing from an int to a long. Or maybe double the amount by changing to an unsigned int (might not be possible, negative cargo space might exist). 

But again, there's no reason to. This isn't Diablo III, where every new update increases all of the stats exponentially. Somebody would have to give a compelling argument for a realistic situation where this is a problem for it to be worth the dev time to change.

It's also (partially) a question of performance. I think that the dev wants this to run on basically any machine out there. Increasing this number would increase the amount of memory required by the game; not by anything close to a noticeable amount, but it's about the principle. If "cheater-proof" data values were used everywhere in the game, then it would most likely use a noticeably larger amount of ram (again, not a problem for 99% of users, but I guess it's about principle).

**Comment by endless-sky** [comment]
I really don't anticipate many players ever needing more than 2 billion tons of cargo space, so "fixing" this doesn't seem worthwhile. No matter what, there are going to be limits in the game; the only question is whether those limits are beyond what a normal player should ever encounter, and in this case I think they are.

**Comment by lkraider** [comment]
Just noting, a fix doesn't mean increasing, just means not overflowing (have a ceiling cap - whatever that value is).

**Comment by Sinsling** [comment]
You can actually hit this cap at 2 million cargo space. I currently have a fleet of 3100 bulk freighters who tried moving ~ 2m tons of luxury goods with a profit of ~400 per ton.

If there is going to be a ceiling that is lower than the maximum bulk-buy of some of the mid-high cargo ships you can buy, why bother enabling ctrl+shift+alt buying for ships at all?

**Comment by KiLEdEnNis** [comment]
if you sell 2 billion+ cargo to a planet I can imagine they'd demand a huge amount of money to compensate for you annoying them, cheating, and them carving a planet out to store it
still love the issue

**Comment by Amazinite** [comment]
@Sinsling people could still alt+shift+ctrl buy warships. And selling with no profit causing no problem makes sense, because selling them elsewhere makes so much profit that it shoves your amount of credits through the roof, causing them to fall over and drop all the way down into the negatives. Metaphorically, that is.

**Comment by davidwhitman** [comment]
Seems like this was addressed in eb8790832a71c02ed3e11f389f3e9282d66e5eb5 ?

**Comment by KiLEdEnNis** [comment]
if MZ would enhance the game so players could cheat on everything (like 2M+ cargo space) it'd be a whole lot of work, just don't cheat that far lol
