### ISSUE TITLE
While the Pug have disabled the hyperspace links, you can still receive a message from the Smuggler's Den couple

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1330]
(ftr, I have a jump drive :laughing: )

Talk to the Smuggler's Den couple. Bring them to Millrace.
1 year later, if you can line it up correctly with all the jumps and stuff, you can land on Sunracer during the peak of the Free Worlds war, in order to stop the Syndicate, the suspects, who are (apparently) collapsing hyperspace links. You find everyone in a panic.
But then, you can receive the payment from Joe and Maria.
Who are on Millrace.
Which is separated from the rest of human space.

**Comment by endless-sky** [comment]
I'm not sure if it's worth having every mission like that one sort through all the situations where a follow-up message can be sent, or not. It's unlikely to happen very often.

**Comment by KiLEdEnNis** [comment]
indeed, it would be way too complicated to add a tiny bit of realism, unless it'd be a message that was sent earlier but just reached the ship
