### ISSUE TITLE
enemy drones docking in flagship (if it  has capacity)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1333]
so I was doing a Transport Mission where the band There Might Be Riots goes annoy Lovelace labs and you encounter 70 drones (Team Red & Team Blue)
since my ship is a Carrier, and I noticed Free World fighters docking in me a few times (because the Skeins were destroyed), I wasn't very surprised, but here is what happened
I launched, and while taking down drones I noticed some docking me, and when I cleared the sector and pressed Q to release fighters/drones, I saw I released some Team Blue and Team Red drones, even though they were hostile to me & each other

**Comment by endless-sky** [comment]
This should be fixed by 209871f.

**Comment by KiLEdEnNis** [comment]
for drones too? (because it says fighters)

**Comment by Amazinite** [comment]
> for drones too? 

`if(isDrone || isFighter)`
