### ISSUE TITLE
value of commodities is 0 (in empty space?)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1336]
so I disabled a World Ship, (and I saw the bug earlier,) and the commodities' money value appears to be 0
I think that is because it can't be sold in Korath space, but is this really something to be fixed? because putting down the average value in human space would be kinda weird (or maybe scale the value on the closest known sector where you can sell it, beyond hyperspace links too)
![0 value](https://cloud.githubusercontent.com/assets/10348657/16900530/6ec63e72-4c27-11e6-8eb1-b2474e2ea982.jpg)

and yes I am jettisoning everything in that ship to look what the AI does after it
(it ignored the disabled ship)

**Comment by Amazinite** [comment]
Yeah, commodity prices when boarding will display the price of that commodity in the system that you are in. Not sure what else it would should display though if not the worth in the system.

**Comment by MarcelineVQ** [comment]
Another option is to not show the value of an item on the boarding screen when the value is 0

**Comment by KiLEdEnNis** [comment]
I'd go with either the value of the closest system or not showing it at all

**Comment by endless-sky** [comment]
Commodity prices haven't been filled in yet for the Korath systems. Eventually I'll need to set them in anticipation of once there are Wanderer outposts there instead of them being uninhabited, but I just hadn't gotten around to it yet.

**Comment by KiLEdEnNis** [comment]
I also mean the area where the Raiders are (I was talking about that), my bad for not making it clear

**Comment by endless-sky** [comment]
Fixed in dbdd018.
