### ISSUE TITLE
flight check [mechanics]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1337]
a similar treatment to the negative attribute check that identifies the specific ship(s) that are failing flight check.

while it didn't start out as a feature request, it serves as case and point;
http://steamcommunity.com/app/404410/discussions/0/366298942110222088/

(oh yeah, and i guess this issue is 'leet...420, no scope)

**Comment by toilethinges** [comment]
That sounds like a great idea!

(1337 - the Hundred Years War :})

**Comment by endless-sky** [comment]
Fixed in 5b0b926.
