### ISSUE TITLE
Impossible to complete "Alpha Surveillance" mission if you are hostile to the Quarg

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1338]
I already said this before, but my reputation with the Quarg is at `-53527.71`.
The Alpha Surveillance mission requires you to land on Alta Hai.
It does not give you clearance.
It is impossible to complete this mission, unless you edit your save, which I don't like to do.

**Comment by toilethinges** [comment]
This is on purpose. #1148

**Comment by Bladewood** [comment]
uuuuu, but then what do we do with the mission?
Am I supposed to kill pirate ships in excess of 50000?

**Comment by toilethinges** [comment]
...don't kill Quarg, or kill a few and yes, kill a ton of pirates.

**Comment by endless-sky** [comment]
Decisions have consequences. You chose to alienate the Quarg. Not being able to get their help is the consequence.

**Comment by KiLEdEnNis** [comment]
@endless-sky then making another branch in case you can't get their help would fit, although it'd be hard & weird, but someone saying that you should look in empty sectors would be enough (finding w/o tracking)
