### ISSUE TITLE
Blurry, almost unreadable text

### ISSUE THREAD

**Issue by ColonelCipher** [endless-sky/endless-sky#134]
Windows 10 64 bit
I3-4030U
4.00GB RAM
http://steamcommunity.com/sharedfiles/filedetails/?id=547124284

**Comment by endless-sky** [comment]
Weird. Is the game always like that, or did it suddenly become blurry while you were playing?

It looks like some sort of graphics driver error, so I'm not sure how much I can do on the software side.

**Comment by ColonelCipher** [comment]
It was always like that. I will try updating the graphics drivers and see what happens.
Thanks for the quick response!

**Comment by ColonelCipher** [comment]
It was just a graphical driver bug.
Thanks for the help!
