### ISSUE TITLE
governments don't care about dying from splash damage

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1341]
so I was bored, played around with some Drak weaponry (like 2 antimatter cannons), and I found out something:
I fought for tribute from the Republic, and the splash damage killed merchants: they stayed friendly
later I fired at pirates, killed merchants and Oathkeepers doing so: they stayed friendly
I even deliberately killed some by shooting at asteroids next to them and they didn't turn hostile at all
there should be a mechanics change that makes a government hostile if killed by splash damage or after receiving significant damage (because an accident shot can happen)

**Comment by jafdy** [comment]
This has been brought up before. The risk was that your "Ally" could turn hostile if you had too many heavy rockets. In this case realism was sacrificed for playability.

**Comment by KiLEdEnNis** [comment]
well the reputation still lowers and can make friendlies hostile (tested w/ Hai, had 19.25 reputation, killed a water bug w/ an asteroid, they became hostile due to reputation loss)

**Comment by toilethinges** [comment]
#821

**Comment by endless-sky** [comment]
@KiLEdEnNis, is it possible you had the Water Bug selected as a target when you killed it? That would count as a hostile action even if it was killed with splash damage.

If allies couldn't take splash damage that would drastically alter the balance of certain weapons (like nukes). I am planning at some point to add "field" weapons, however, that damage all hostile ships within some range but not friendly ones. (For example, to allow the Drak ion field to properly damage all ships in range, not just one.)

**Comment by KiLEdEnNis** [comment]
@endless-sky no, but killing ships w/o targetting does lower reputation, and mine with the Hai was maybe 20, killing a few through splash damage lowers reputation to under 0
like if you have -0,1 reputation w/ merchants that are in the sector, you can kill a pirate & they stop firing (had that too w/ Republic once, were some in sector, killed a pirate Bastion, they liked me again & stopped firing)

**Comment by endless-sky** [comment]
Yes, you're right, killing people with splash damage affects your reputation, even though it doesn't "provoke" an angry response. But, in my opinion that's a pretty good balance - if you keep killing friendly ships as collateral damage, people *should* get mad at you.

**Comment by KiLEdEnNis** [comment]
yeah, only weird things is that people die & they don't get mad, adding a "rescue" part to ships after they are destroyed (they don't disappear but they have holes & everything) could help a bit
so adding a limit of ships or crew, and when you destroy/kill more than that limit they get angry, could maybe help?

**Comment by Alkallid** [comment]
Are you proposing boarding and repairing to boost rep?

**Comment by KiLEdEnNis** [comment]
partially, but when a big ship explodes, it disappears, but more realistically, it would leave a main chunk of the ship with survivors, and being able to do rescue operations on "destroyed" ships would be cool
but the board/repair boarding to get more reputation should actually be implemented
