### ISSUE TITLE
Alphas are friendly during Hai/Wanderer missions

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1343]
so the Alpha Carrier was friendly when I saw it, why? well:
it's like the Syndicate (Extremists) issue; their governments have a bad reputation to Republic etc. so if you kill Republic ships they will like you more
how to fix it? (if I'm right, 99% sure) change the Alphas government by deleting hostility to the Republic and Oathkeepers, and instead add hostility TO Alphas on the Republic & Oathkeepers
that means that by killing the Republic won't make them like you, but by killing Alphas the Republic likes you more
so like this:

change this:
government "Alpha"
	swizzle 1
	"player reputation" -1000
	"attitude toward"
		"Republic" -.1
		"Navy (Oathkeeper)" -.1
	"bribe" 0

to this:
government "Alpha"
	swizzle 1
	"player reputation" -1000
	"bribe" 0

change:
government "Republic"
	swizzle 0
	color .91 .42 .09
	
	"player reputation" 2
	"attitude toward"
		"Merchant" .25
		"Militia" .1
		"Pirate" -.3
		"Navy (Oathkeeper)" 1
		"Neutral" .1
	"friendly hail" "friendly navy"
	"hostile hail" "hostile navy"
	raid "pirate raid"

to:
government "Republic"
	swizzle 0
	color .91 .42 .09
	
	"player reputation" 2
	"attitude toward"
		"Alpha" -.1
		"Merchant" .25
		"Militia" .1
		"Pirate" -.3
		"Navy (Oathkeeper)" 1
		"Neutral" .1
	"friendly hail" "friendly navy"
	"hostile hail" "hostile navy"
	raid "pirate raid"

change:
government "Navy (Oathkeeper)"
	swizzle 0
	color .91 .42 .09
	
	"player reputation" 100
	"attitude toward"
		"Merchant" .25
		"Militia" .1
		"Pirate" -.3
		"Kor Sestor" -.1
		"Kor Mereti" -.1
	"friendly hail" "friendly navy"
	"hostile hail" "hostile navy"

to:
government "Navy (Oathkeeper)"
	swizzle 0
	color .91 .42 .09
	
	"player reputation" 100
	"attitude toward"
		"Alpha" -.1
		"Merchant" .25
		"Militia" .1
		"Pirate" -.3
		"Kor Sestor" -.1
		"Kor Mereti" -.1
	"friendly hail" "friendly navy"
	"hostile hail" "hostile navy"

if there are tiny differences, I edited my data a bit to add more stuff (have a small area of new space, a new government, they are like improved human ships with alien technology, if interested (MZ) tell me where to put the data, I'm gonna make a story sometime)

**Comment by KiLEdEnNis** [comment]
^ and the tab's are messed up, so maybe do it yourself

**Comment by OmegaZanicus** [comment]
This is actually a really good idea, for people who like to farm for republic carriers/cruisers/drones,
or change the player reputation when the mission starts.

**Comment by KiLEdEnNis** [comment]
my first good idea o:

**Comment by Amazinite** [comment]
> change the player reputation when the mission starts.

**Comment by KiLEdEnNis** [comment]
that works too, I personally prefer the other but that's more work

**Comment by endless-sky** [comment]
Fixed (both ways, for good measure) in 073c023.
