### ISSUE TITLE
Arfecta cloaking device irremovable

### ISSUE THREAD

**Issue by OmegaZanicus** [endless-sky/endless-sky#1344]
I don't know if this was on purpose, but it is possible to capture the Arfecta, but since the ship has
`-.2 cloaking fuel`
It is impossible to remove the cloaking device.
1) If this was done on purpose, why not simply add cloaking device as a built-in.
2) If not, make it so the cloaking fuel can go negative.

**Comment by KiLEdEnNis** [comment]
can you try and describe it a little bit better?
I saw in the files that the ship itself has the cloaking fuel stat, and I'm not sure why it has that, because in the main story, if you help the Syndicate defector, you later get a cloaking device in your flagship which you can remove, and it drains fuel, so I think that stat just has to get removed
in case it's on purpose (which I doubt), having it built-in may be very hard

**Comment by OmegaZanicus** [comment]
This isn't really user error, more a feature request I guess but:

The Arfecta ship has a built in stat, like `cargo space`, or `shields`, `-.2 cloaking fuel` that balanced out the `.2 cloaking fuel` that the cloaking device uses. This allows it to stay cloaked forever. However, this stat also prevents the user from removing the cloaking device, because that would cause the `cloaking fuel` stat to go below zero, and the game doesn't allow that.

What I was asking, was if this was intentional for the Arfecta, or if MZ hadn't anticipated players capturing it, or if it was in fact a mistake.

**Comment by KiLEdEnNis** [comment]
I don't think he intended it to be captured, but then he could add the "never disabled" feature
giving it a massive amount of fuel and ramscoop would nearly have the same effect

enabling it to go below 0 would require that stat to do absolutely nothing if no cloaking device was installed, so it's not really a bug, more a mechanics thing

**Comment by KiLEdEnNis** [comment]
and in case MZ reads this; I am working on extra content (for myself), where can I put the idea and could it be released if I made an actual story?

**Comment by OmegaZanicus** [comment]
the thing is, it _doesn't do anything when there is no cloak_, because it only has effect when the ship is cloaked.

P.S. please go make your own issue, don't just hijack my problem please. its a little rude.

**Comment by KiLEdEnNis** [comment]
I try to help (but the last comment I understand, just don't know where to put it at all)

I know it doesn't do anything, but the game may not see it that way, maybe making another cloaking device for the Arfecta might help, like an upgraded version of the other one the player can get, although that'll enable the player to infinitely cloak

**Comment by toilethinges** [comment]
#1066

**Comment by KiLEdEnNis** [comment]
it should get the "never disabled" tag yes

**Comment by OmegaZanicus** [comment]
Did you read MZ's response @KiLEdEnNis

**Comment by KiLEdEnNis** [comment]
yes, but still

**Comment by toilethinges** [comment]
I think that if he wanted it to be never disabled, or thought it would be right to, he would have done it already. He answered, in that issue, that he was fine with it being captured, and it was discussed (or, rather, someone said) that it really wouldn't make sense for it to be never disabled - currently, the only never disabled ships are person ships or Archons.

**Comment by KiLEdEnNis** [comment]
yes, but the Pug have artificial wormholes, even the Drak don't, meaning that the Pug would nearly have the same capabilies if they wanted to (and from what the Wanderer say the Pug have the wormhole technology for hundreds of thousands, maybe millions of years)
and tbh to disable an Arfecta you need a huge fleet and flamethrowers to keep it from cloaking, so to disable it you already need to do a lot, so maybe it's fine how it is
as for the cloaking device, selling the Arfecta & buying the device helps, but you can't buy a sold ship back, so making it that selling it, then buying the cloaking device on another ship, then buying theb Arfecta back would fix it, even though it's confusing & weird

**Comment by OmegaZanicus** [comment]
This makes no sense considering you already disproved that I could get the arfecta back.
> selling the Arfecta & buying the device helps, but you can't buy a sold ship back, so making it that selling it, then buying the cloaking device on another ship, then buying theb Arfecta back would fix it, even though it's confusing & weird

**Comment by KiLEdEnNis** [comment]
I mean that if you can buy a ship after selling you can circumvent that bug

**Comment by OmegaZanicus** [comment]
_Go make an issue about it then_

**Comment by KiLEdEnNis** [comment]
issues are for game ideas then? didn't know as I'm relatively new to github

**Comment by endless-sky** [comment]
Basically, it's intended to be like an "integrated" cloaking device: you can choose to have a cloaking device but no Arfecta, but you can't separate the ship from the device and keep the ship.

**Comment by KiLEdEnNis** [comment]
@endless-sky but can't you integrate it in the Arfecta itself? or isn't that an option? maybe I'll test it after I get home (oral exams so ye)

**Comment by Alkallid** [comment]
He said he's giving the option of one, but not both seperately.

**Comment by KiLEdEnNis** [comment]
ah like that, kinda weird though
