### ISSUE TITLE
Mission "FW Bloodsea 1" description is wrong

### ISSUE THREAD

**Issue by sargon14** [endless-sky/endless-sky#1345]
The description for the mission "FW Bloodsea 1" is:

> "Bring Alondo to `<planet>` to meet up with Freya, who has succeeded in working out most of the remaining kinks in the Dreadnought production line."

But that's not what you're doing. You're bringing Alondo to Bloodsea to find out what to give them to get them to join the Free Worlds. Freya isn't on Bloodsea at this point, anyway.

**Comment by KiLEdEnNis** [comment]
I also saw "to to", isn't there a <destination> between them?

**Comment by sargon14** [comment]
The tag got eaten because I didn't encapsulate it in `backticks`. Fixed now.

**Comment by endless-sky** [comment]
Fixed in 32d36dc.
