### ISSUE TITLE
landing while ships enter hyperspace consumes fuel w/o them traveling

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1348]
so I landed on a planet when a jump drive escort jumped; in consumed fuel, but it was still in the same sector when I departed (an empty sector)
maybe escorts should jump and then consume fuel?

**Comment by Alkallid** [comment]
Does it matter? It still refueled, right? It consumes at a gradual pace.

**Comment by Alkallid** [comment]
Ending when it actually jumps system.

**Comment by KiLEdEnNis** [comment]
no it drained fuel, I landed, and it was still in that system with lost fuel, temporarily stuck since it was an empty (Korath) sector, near the Kor Efreti area

**Comment by LocalGod79** [comment]
@Alkallid to replicate:

• have an owned escort that is slower at jumping than your flag.
• jump three or four times to another system
• while your escort is catching up, position yourself over the planet, more or less stationary
• wait until you see the fuel bar of your escort begin to drop
• land immediately

your escort will still be in the system it was jumping out of, and the partial jump of fuel will have been consumed.  if they are in an uninhabited system and have less than a jump of fuel, they will be stuck until you rescue them.

**Comment by KiLEdEnNis** [comment]
what you said was what I meant, since it's technically a bug I just gave my escort some fuel through save game edit since I can't be bothered to rescue it because of a bug

**Comment by LocalGod79** [comment]
how you rescue them is up to you (edit save, go to system and destroy/board, or just wait until the built in ramscoop fills them enough to jump) - but it can happen, so it's a bug...

**Comment by KiLEdEnNis** [comment]
it's up to MZ, make it look a bit less good to solve a tiny bug no one ever sees

**Comment by endless-sky** [comment]
Technically, if you had waited until the ship jumped out of system, you would have lost even *more* fuel.

There's no good way to avoid this, unless ships were made to only lose fuel at the exact moment they jump. (If they lost fuel after they jumped, you'd have the opposite problem where you could gain fuel by landing before your escorts were done jumping in.)

**Comment by KiLEdEnNis** [comment]
yes, I just thought that fixing it would be annoying while no one ever saw the bug

**Comment by Bladewood** [comment]
I see this bug all the time, and it's very annoying :|

**Comment by KiLEdEnNis** [comment]
yes but I don't see how it could be fixed unless the ships still move sectors after using their hyperspace

**Comment by Alkallid** [comment]
@KiLEdEnNis "yeah, sorry about that, trying to stay "mature" here, just failed to do so once
(won't respond after this)"
"Once"

**Comment by KiLEdEnNis** [comment]
@Alkallid I don't see how that fits here, because this was about a bug and I just saying some ideas

**Comment by Alkallid** [comment]
You're unnecessarily commenting.

**Comment by KiLEdEnNis** [comment]
some call it discussing but ok
