### ISSUE TITLE
"Timer Ship" for Rim Archeology missions can be selected

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1349]
http://i.imgur.com/admML5G.png
On that note, you can also select the Kor Mereti's nanobots in Sayaiban. Who have merchant ship names.

Also, when the Timer Ship self-disables, I can apparently board it. And take its timer weapon. And capture it.

**Comment by KiLEdEnNis** [comment]
I saw the target part, but the nanobots have those team Red/Blue names if I remember, but forgot to post, so ty

**Comment by Bladewood** [comment]
No, Team Red and Blue are used by the combat drones that attack you when you leave Pilot to bring There Will Be Riots to Hai space.

**Comment by endless-sky** [comment]
Fixed in cb4af77.
