### ISSUE TITLE
Pirates spawning too frequently in too many numbers

### ISSUE THREAD

**Issue by Cupelix14** [endless-sky/endless-sky#135]
In every system I go to, even in the core worlds, there are at least 5 pirate ships already there. More usually jump in before I can leave. This is in a brand new game without any stories being started. Just doing some missions and assembling a basic fleet.

In EV games, pirates were only seen this frequently around their havens. And even then in much smaller swarm sizes. Seeing one at a core world was very rare, much less entire fleets every time you visit. It's frankly annoying and pretty unrealistic.

**Comment by endless-sky** [comment]
"Assembling a basic fleet..." of freighters, by any chance? A large fleet of freighters will draw pirates like flies - it's a game balancing mechanic to make the exponential Star Barge strategy a bit harder to pull off.

**Comment by Cupelix14** [comment]
Okay, that would make sense. But a couple of points then. The big one is if my freighters are parked, I shouldn't have pirates in every system I go to, especially if I'm far from the pirate havens. Also, even if I'm travelling with them maybe there should be some mitigation of how many or how frequently a pirate fleet will spawn. For example if I have a few freighters AND some warships as escorts, pirate bands should be less inclined to want to ambush my convoy. Maybe they spawn 50% of the time then instead of 100%.

**Comment by endless-sky** [comment]
The bug where pirate raid strength was based on all the ships in your fleet, even the parked ones, is fixed in 0.8.5.
