### ISSUE TITLE
Pug Seeker has "homing" equal to 5?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1351]
> outfit "Pug Seeker"
...
"homing" 5

The wiki states that homing takes an integer value from 0 to 4.
What does 5 do? Is it supposed to give godlike homing capabilities? Or is it a typo? Does it just activate level 4 homing, being the highest possible value?

**Comment by MarcelineVQ** [comment]
Only values up to 4 affect what the game does so functionally anything above 4 is just 4 currently

**Comment by KiLEdEnNis** [comment]
so a typo without any negative effects?

**Comment by Alkallid** [comment]
Yes.
