### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1353]
is the issues tab also for ideas? since I have a lot of ideas and I can even add a part of new space, a story for it etc.

already a quick idea: special outfit storages than can store torpedoes, rockets or whatever (like it takes less outfit space than the launcher, stores as much but can't shoot, and when the launcher is empty it takes time to reload it)

**Comment by Disiuze** [comment]
https://github.com/endless-sky/endless-sky/blob/master/CONTRIBUTING.md

**Comment by KiLEdEnNis** [comment]
so can I put all ideas in one post or make a seperate per thing? since half of them aren't that big

**Comment by endless-sky** [comment]
Every idea should be in a separate "issue" so they can be separately categorized and prioritized.

But first, search the issues (including the closed ones) and make sure it's not an idea that has already been suggested.

**Comment by KiLEdEnNis** [comment]
@endless-sky alright, I joined the stream group yesterday too about the editing project I have
