### ISSUE TITLE
Hai regenerators create heat only while recharging, while regular regenerators create constant heat

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1356]
The Corundum regenerator has a `"shield heat" 180` tag, meaning it creates heat when your shields are damaged, while the S-270 has a `"heat generation" 120` tag, meaning that it constantly generates heat, just like a reactor.
Is this supposed to distinguish human regenerators from Hai regenerators?

**Comment by LocalGod79** [comment]
yep

in addition to the regenerators being slightly more tonnage/energy efficient (i think - it's been a while), they only generate the heat component of the Syndicate outfits while regenerating the shields.

**Comment by KiLEdEnNis** [comment]
the Hai are more advanced and particularly efficient, so I think it's intended

**Comment by Wrzlprnft** [comment]
Local managed the addition of those, so no reason for speculating after his answer :)

**Comment by KiLEdEnNis** [comment]
yes, I just like answering when bored (had nothing to do at school)

**Comment by LocalGod79** [comment]
except you spam people's mailboxes with an issue that should be closed.

please.

**Comment by KiLEdEnNis** [comment]
yeah, sorry about that, trying to stay "mature" here, just failed to do so once
(won't respond after this)
