### ISSUE TITLE
Game hung when landing on Avalon

### ISSUE THREAD

**Issue by kmdavis** [endless-sky/endless-sky#1358]
I went exploring once I got a Jump Drive, and tried landing on Avalon (up in the NE corner of the map) and the game hung. No errors were logged anywhere that I can find though.

**Comment by kmdavis** [comment]
UPDATE: after force quitting the app (BTW, this is on OS X, if that makes a difference)) I relaunched it, and it looks like the game did save when I landed, and I was able to load that save, and I was able to take off and land again.

**Comment by LocalGod79** [comment]
are you compiling from source?

i've also (Mac OS X) had some sporadic hanging since the recent code updates...

**Comment by kmdavis** [comment]
No, it’s installed from Steam

**Comment by jafdy** [comment]
Sounds like a hang I got back in 0.8.11. Different planet but otherwise almost the same.

**Comment by KiLEdEnNis** [comment]
I think it's OS X related, I never had it & I doubt anyone else has that

**Comment by Wrzlprnft** [comment]
@KiLEdEnNis not so quick judgement, e.g. local is on OS X.Also, i consider that comment somewhat unneccessary, at least on github. Try to keep it constructive on here.

**Comment by jafdy** [comment]
I'm on windows 10 so if this is the same bug the then it is not OSX related.

**Comment by KiLEdEnNis** [comment]
yes but I did the mission thing like 5x and I didn't have it, and yes that's not accurate but if it wasn't OS X related it would probably be reported earlier

**Comment by Amazinite** [comment]
Windows 8; I've had similar experiences on a number of different planets, but they're rare occurances and I've never been able to figure out exactly why it happens. It may just be a coincidence, but at least for me it tends to happen after not landing for a long amount of time, usually when I have a ton of stacked ramscoops and rarely have to land.

**Comment by MarcelineVQ** [comment]
@Amazinite @kmdavis 
Does the planet panel pop up before the freeze? If it does did the landscape image load? Are either of you on 32bit systems?

**Comment by Amazinite** [comment]
The panel does not pop up and I am on a 64 bit system.

**Comment by jafdy** [comment]
@KiLEdEnNis I don't think it has anything to do with mission.
@Amazinite Time might be it, I got my hang after demanding tribute from about 20 planets without landing.

**Comment by kmdavis** [comment]
The panel does not pop up and I am on a 64 bit system.

**Comment by KiLEdEnNis** [comment]
yeah I thought it'd be weird if it was tied to the mission, I think it's an issue that happens when a lot has happened (or a lot of numbers, as 1 of my escorts kept landing & departing on nothing, while I had like 60 big warships)
so a lot of tributes, extended travel, maybe it's an overload of data saving at a time, which would be weird considering a Gameboy or DS could practically run the game

**Comment by Bladewood** [comment]
I, for one, vouch for the second of KiLEdEnNis's possibilities.
During the escort Earth ambassadors to Gamma Corvi mission, make all 18 jumps consecutively, without landing to refuel.
It will freeze.
Or at least it froze my game.
I tested it many times, and it did.

**Comment by kmdavis** [comment]
I’m not sure how many jumps I had made before landing, but I’m sure it was
more than usual.

**Comment by Amazinite** [comment]
I haven't experienced a random hang when landing on a planet in months; anyone else? This might have been fixed along the way somewhere in the past year.

**Comment by KiLEdEnNis** [comment]
it may be a bit related to how good the PC is, if it is we can't really test it that easily
I'd say keep this issue open in case as we can't really confirm if it is fixed

**Comment by gunqqer** [comment]
Have a shitty computer running OS X, don't get any random hangs when landing.

**Comment by Bladewood** [comment]
Even [this](https://github.com/endless-sky/endless-sky/files/1223029/Doctor.Hax.autosave.txt) (based on [this](https://github.com/endless-sky/endless-sky/issues/1358#issuecomment-234698967)) works now, so I think we can call this resolved.

**Comment by kmdavis** [comment]
(Original reporter here) I can't reproduce anymore either

**Comment by gunqqer** [comment]
Ah issue is... resolved, please close this issue

**Comment by endless-sky** [comment]
I assume this was fixed by 5d9c33eb, but it's such an intermittent error that I didn't want to close the issue until I was sure people had stopped seeing it.
