### ISSUE TITLE
Trouble Getting Interference Plating to Work

### ISSUE THREAD

**Issue by FinalCatch** [endless-sky/endless-sky#136]
How does Interference Plating work. The tool tip says Scan interference 0.5  to what does this refer? Do you need as certain amount of plating for a certain amount of illegal goods? If so is that based on the number or the illegal out fits or mass?
Or is it based on the Cargo Scanner or outfit scanner strength? If so (as the outfit scanner has strength 500) do you need 500/0.5=1000 Interference Plating to avoid being scanned? This seems unfeasible as it would cost 4000 outfit space. 
Any help appreciated.

**Comment by endless-sky** [comment]
When you are scanned, your chance of the scan finding your illegal items is equal to:

`1 / (1 + scan interference)`

So, 2 plates reduces your chance of a fine to 1/2, 4 reduce it to 1/3, etc.

(Note: the scanner "strength" is just its range, not its chance of finding something.)

**Comment by FinalCatch** [comment]
Thanks for the quick replay that really helps! 

Just to double check. Is this for all your illegal items or for each illegal item 

ie. 100 items then 100 * 1 / ( 1 + scan interference).

From what you've said I'm guessing its the former (not the latter). 

Thanks again!

**Comment by endless-sky** [comment]
It's for all of them. That is, when you get scanned (either by a ship or
because of spaceport security), the game checks to see whether the scan
pierces the interference or not, and if it does it looks through all your
illegal items and fines you for the most illegal one of them.

**Comment by FinalCatch** [comment]
Cool thanks for explaining!
