### ISSUE TITLE
Can "on enter" apply to any system with a specified attribute?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1360]
For example, let's say we wanted an event to occur once we enter a Syndicate system, ANY Syndicate system. Could we use "on enter" to specify just any system part of Syndicate territory?

I made this issue to address the problem of arriving in a Syndicate system by jump drive, during the last parts of the Free Worlds war, where you're supposed to enter Syndicate systems by going through the "backdoor route". If this is implemented, we could fix that problem by adding a `on enter (government Syndicate)` line, or something like that, instead of a `event "fw syndicate welcoming" 11` line.

**Comment by Wrzlprnft** [comment]
As far as i know you can specify the missiom to be offered on planets with the syndicate government, and, in a seperate line, set it to being offered on enter. It's basically two different conditions.

**Comment by endless-sky** [comment]
At the moment, it needs to be either tied to a particular system, or left blank (in which case it applies as soon as you take off from the current planet).

**Comment by jafdy** [comment]
#1082 would fix this. It could do with some rewriting though and I don't think I can bring it up to standard.

**Comment by KiLEdEnNis** [comment]
jump drives ruin some mission mechanics, but adding an "on enter" tag that's tied to any sector governed by that government (unless unlinked) could help
and in this case having it as "on enter", tied to any Syndicate government, with a "near Foundry" limit should fix it
very confusing & complicated, but it's an idea

**Comment by tehhowch** [comment]
With #3141 and e1c1a55c3a1bc2ec42ef0f9676a97c9a0c855e92, this is resolved.
