### ISSUE TITLE
[bug] Plugins are unable to remove the original start mortgage

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1361]
This may be similar to the interface problem. 
When creating a plugin that makes a new start to the game, you are able to overwrite everything except the mortgage. This means that if you want a start to have no mortgage, you are unable to do this, and adding your own mortgage on start will create two mortgages when you start a new pilot: the vanilla mortgage and the plugin mortgage. 

http://steamcommunity.com/app/404410/discussions/2/358416640401338233/

**Comment by MarcelineVQ** [comment]
Adding mortgages.clear() at the top of Account::Load should resolve this

**Comment by endless-sky** [comment]
Fixed in fb40d6d.
