### ISSUE TITLE
"FW Pug 3: Quarg" typo?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1362]
On the reconciliation path, you are given the option to take Alondo to Lagrange to talk to the Quarg about the Pug.

Halfway through the conversation, the Quarg talks about the Pug playing a "game".
And then someone asks it a question about "dying for the sake of a game".
Except, that someone is not Alondo. It's Freya.

**Comment by MarcelineVQ** [comment]
Yes there seems to be two mentions of Freya in `FW Pug 3: Quarg` that were missed when, I assume, it was copied from `FWC Pug 4B: Quarg` I can't find mention of her being on your ship so it's likely an error.  
Try making a [PR](https://help.github.com/articles/using-pull-requests/) for it, this is a good issue to tackle to learn how if you want to.

**Comment by Bladewood** [comment]
I refuse, I have no skill in using github properly.

**Comment by KiLEdEnNis** [comment]
same, but try it :3

**Comment by endless-sky** [comment]
Fixed in 7f4058d.
