### ISSUE TITLE
Question about an installer for the game on Windows listed in the help wanted page

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1363]
I was just wondering if there were any requirements for it to be written in C++ because I've got some of the back-end stuff done but in C#.
Sorry if this isn't the right place for a question like this but I want sure where to ask it.

**Comment by endless-sky** [comment]
I was thinking it could probably just be an NSIS script:

https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System

I'm not sure how big a deal it is for Windows users that the game (unless you're on Steam) just downloads in the form of a folder with an executable file, rather than properly placing itself within your Start menu, etc.

**Comment by warp-core** [comment]
I was thinking of also making it into something like the minecraft launcher and allowing the user to enable and disable plugins and allowing automatic updating, even allowing them to use an older version.
NSIS would probably be a much better way of making something that is only an installer though and the demand for a full 'launcher' probably isn't enormous given how the game is available on steam. The only useful difference would be the ability to enable and disable plugins, maybe even allow pre-selected groups of plugins to be enabled and disabled for those that use a lot however, the ability to enable and disable plugins will be a part of the base game at some point based on the development roadmap so I'm not sure if there is any point.

**Comment by KiLEdEnNis** [comment]
even if the game would be made into a stand-alone (I believe that's what it is), it would take a lot of time and programming to do so for very little result, although improving the title screen with the ability to enable/disable plugins could be a good idea
I don't know how much that would take, but a few buttons to plugin settings shouldn't be that hard, and could even be on the Steam version

**Comment by jafdy** [comment]
> allowing the user to enable and disable plugins

This is in the development map.

**Comment by capnchainsaw** [comment]
I didnt do it in NSIS (tho I'd be willing to) but I setup an installer in WiX (which I was already familiar with). Wasnt sure where to go so I posted in the forums here - https://groups.google.com/forum/#!category-topic/endless-sky/general-discussion/bGQX-1c7wAA

the scripts for making a Win64 MSI installer are here https://github.com/capnchainsaw/endless-sky-installer tho they assume the libraries needed are in the Release dir of the build

I have a working installer and LocalGod pointed me to the releases page. Is it okay to add there?

**Comment by BobbusMaximus** [comment]
Does anyone have a rundown on  the system requirements ? I can't get this to run on my PC at all. I have Vista 32 bit nvidea geforce 7350LE which is an older card. Sorry to ask here but Im at a loss.

**Comment by Amazinite** [comment]
If it's an older card then you probably don't have OpenGL 3.0, which is required to run the game.

**Comment by endless-sky** [comment]
Yes, it looks like the GeForce 7xxx series only supports OpenGL 2.1.
