### ISSUE TITLE
[content] Missing Ship Specs Gatling

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1364]
@LocalGod79 
"Fury (Gatling)" is specified in fleets.txt and events.txt but doesn't have a `ship "Fury" "Fury (Gatling)"` specification

This is also the case for "Barb (Gatling)" "Dagger (Gatling)" "Sparrow (Gatling)"
Which is causing occasional error messages when loading fleets

**Comment by LocalGod79** [comment]
oops - our little group had gotten together a fair bit of content in separate pulls, and when gatling #1295 was merged with #1284, i must have missed variants.txt

**Comment by KiLEdEnNis** [comment]
so someone has to make variants of those ships and give them gatling guns?
I could use the practise and I like doing these things
