### ISSUE TITLE
Unable to compile in windows 10

### ISSUE THREAD

**Issue by Sinsling** [endless-sky/endless-sky#1366]
I am attempting to compile in windows 10, and have finally gotten code::blocks to create a .exe file. After creating it, I recieved a missing dlls error from the compiler, so I copied over the dlls located in my steam's endless sky folder. After doing this, I received an "entry point not found" error from the compiler.

Based on what I have found so far, there are 3 possibilities:

1)Accidental over-write of a system .dll file with a third party .dll. - no files were over-written
2)Worm from an infected zip file. -I have only downloaded the linked win64-dev and the endless-sky-master zips recently.
3)An out-of-date .dll file. -Seems most likely as my mingw-w64 file has 4 versions of libgcc_s_sjlj-1 located inside of it; a .dll file asked for by the created .exe application.

Any suggestions on how to fix this issue?

**Comment by Sinsling** [comment]
I noticed that my steam folder uses seh's dll and not sjlj's. I attempted to install mingw-w64's seh version instead, but recieved undefined reference errors.

I assume I am meant to run the sjlj version, but I am not sure which sjlj-1 dll to use. I also find it highly strange that my steam download runs with the seh dll and not the sjlj required for compiling.

**Comment by jmhorjus** [comment]
I've been building on windows 10 for a while.  The most common issue is indeed having a wrong version of a dll.  
I don't recommend copying anything from your steam folder.  The "entry point not found" *might* mean it's a 32/64 bit mismatch, but I'm not 100% sure.  Just get the latest actual version of the dll from the official source, and then if the linker still says it's missing, check the path very *very* VERY carefully (probably some crazy long file path with like six versions and ".", "-", etc embedded in it).  

If you're still having trouble, let me know and include the exact error in your log.

**Comment by Sinsling** [comment]
This could most likely be the problem. I am using the 64bit builder version. I will try the 32bit compiler when I have enough free time and see if that works.

**Comment by Sinsling** [comment]
jmhorjus, are you using the 64 bit libraries or 32 bit libraries found on the build instructions?

I tried using win32 seh and sjlj versions of mingww64 with no luck, both returning different errors.

From sjlj's failed compile, some of the errors I get are:

"undefined reference to 'pthread_self'"
"undefined reference to 'pthread_mutix_init'"
"undefined reference to 'nanosleep'"

**Comment by jmhorjus** [comment]
You need to use the 32bit libs for the 32bit build, yeah.  

It may be an issue with your MinGW install or the paths to those files in the Code::Blocks project.  You should have the "pthread" version of MinGW with "dwarf" exceptions, NOT "sjlj".
