### ISSUE TITLE
Possible mistake in Quarg First Contact

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1368]
In the Quarg First Contace mission, when talking about weapons of mass destruction and how the Drak protect the galaxy from them, the Quarg says: "These things will attract the attention of the Drak, because they nearly destroyed this galaxy once, and must not be allowed to do so again." This implies that it is the Drak who must be prevented from using these weapons but it is the Drak who are preventing others.

**Comment by Bladewood** [comment]
Uh, no. It's supposed to only imply that the weapons nearly destroyed the galaxy. Who actually used said weapons is a mystery (probably the Korath), but in any case, the Drak are just supposed to stop them from being used again.

**Comment by warp-core** [comment]
Ok, that makes sense. Thanks for the clarification.
