### ISSUE TITLE
[Documentation] Variants remove special tags

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1369]
#1367 

Stuff like `"never disabled"` and `uncapturable` don't persist through variants, which isn't currently documented on the wiki.

**Comment by KiLEdEnNis** [comment]
thanks, didn't know I had to do this

**Comment by Amazinite** [comment]
You didn't have you, it was just something that I brought up in that issue and thought it should be documented.

**Comment by endless-sky** [comment]
I've added notes to the wiki page on [creating ships](https://github.com/endless-sky/endless-sky/wiki/CreatingShips#data).

**Comment by Amazinite** [comment]
Nice.
