### ISSUE TITLE
Minor nitpick: Kestrel's turret mounts are asymmetrical

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1371]
This is most obvious when you're using beams: one of the turret mounts seems to be a little farther up front than the corresponding mount on the other side.

**Comment by Amazinite** [comment]
?
```
turret -7 -4 "Heavy Laser Turret"
turret 7 4 "Heavy Laser Turret"
turret -23	14 "Heavy Laser Turret"
turret 23 14 "Heavy Laser Turret"
```

**Comment by Bladewood** [comment]
It would have to be `-7 4`.

**Comment by Amazinite** [comment]
Wait, yeah. Just noticed that missing negative.
