### ISSUE TITLE
[Question] How hard are the FW combat missions meant to be?

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1375]
EDIT: Testing missions to compile advice for other players.

With Defend Sabik the FW fleet can't defeat the Republic fleet without the player. And I can't beet them with a sooped up Argosy (original testing craft?), I am not a brilliant in combat. 

Extra questions:
What ship should I use to test?
How capable are the FW fleets meant to be?

**Comment by Sinsling** [comment]
The argosy is a light FREIGHTER. While the pirate modified is  pretty decent as a light warship, it is not meant to stand up to military medium-heavy (frigate/cruiser/carrier) warships. Try atleast a bastion (medium) or falcon (heavy) warship. If you can, it may be preferable to fight the pirates and try to capture a leviathan, unless you can still get to the Betelgeuse shipyards to buy one.

Bringing your own fleet can really help. If you already have an argosy, use it to capture pirate clippers/argosies for income and to build up a small freighter warfleet.

**Comment by jafdy** [comment]
Let me clarify. I'm not asking for help to defeat the mission, I am bringing up a possible balance issue and asking what the original difficulty was intended to be.

**Comment by Sinsling** [comment]
Test with a bastion. They are great medium tier warships that can go toe-to-toe with heavies. The assumed difficulty is most likely that the player has a medium or heavy warship instead of a trade ship. The mission may also be possible in a combat-fitted medium or heavy freighter, or one of the more war-ready transports.

Granted, it may be a bit rough on someone who just suddenly got dragged into a war environment with no idea wtf was going on. I think I was in an argosy right when I hit that point and kinda got rolled as well. Had to buy a bastion to win.

**Comment by LocalGod79** [comment]
i believe the difficulty roughly scales slightly ahead of the salary curve through my experience.

with that said, if you are piloting a ship (available in the south) that roughly corresponds to your salary, you should be able to complete the reconciliation arc without reloading excessively (always those random occasions).

**Comment by KiLEdEnNis** [comment]
it wouldn't be fun if the FW fleet could win without the player, or if the placer would only have to take out a Gunboat to win, but maybe adding 1 Osprey to the FW fleet could make it a bit easier

**Comment by LocalGod79** [comment]
sorry, it was late when i made that comment, and i didn't read the o.p. very well.

i've completed said mission in a mildly tuned Corvette...

something else has occurred to me: it's possible that `event "capture of Kornephoros"` is unbalancing the mission: if the player is not "cleaning up" quickly enough, more navy ships will pile into the system than FW, eventually overwhelming the player...

**Comment by jafdy** [comment]
Thank you @LocalGod79. I'll see what I can find but I am still worried that some of the changes have unintentionally unbalanced the campaign since 0.8. Perhaps rechecking for balance needs to be a 1.0.0 goal.

**Comment by jafdy** [comment]
The following mission (Liberate Kornephoros) is much easier to the point where the FW fleet will normally beet the Navy fleet. This feels a bit inconsistent.

**Comment by KiLEdEnNis** [comment]
yeah the game is boring if it's not challenging at all

**Comment by endless-sky** [comment]
The original balancing assumed a 5M credit ship at the start of the FW missions, and a 20M credit ship by the end, also assuming the player makes intelligent choices to assist their side in the battle, and may have to reload several times anyway.

For example, an argosy armed with nothing but anti-missiles and some fast engines is more than enough to win the early battles for the Free Worlds. Or, a light warship fast enough to kill the Rainmakers before they can unload all their ammunition. Or, the player can just try to distract large numbers of Navy ships and draw them away from the main battle so the other FW ships can mop things up piecemeal.

**Comment by jafdy** [comment]
"A370 Atomic Thruster"
"A525 Atomic Steering"
"Fusion Reactor"
"LP144a Battery Pack"
"D94-YV Shield Generator"
"Mass Expansion" 5
"Liquid Nitrogen Cooler"
"D14-RN Shield Generator"
"Plasma Cannon" 4
"Quad Blaster Turret" 3

This 12M and a bit Bastion is the ship I'm testing with.
