### ISSUE TITLE
"quiet" mission fail [mechanics]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1376]
essentially, a "fail" command, that doesn't tell the player that it's happened.

example of use:
```
npc kill
	...
on complete
	conversation
		`you report that several ships were in <system>, and that you destroyed them.`
on visit
	"quiet fail"
	set "missionname: done"
	set karma ++
	conversation
		`you report that several ships were in <system>, but that their numbers were superior to your own, and that a larger force will be needed to destroy or disperse them.`
```
this enables mission coders to have different mission endings within a series of "linked" missions - without spamming the player's chat with mysterious mission failure notifications (or having tandem/nested invisible missions).

**Comment by endless-sky** [comment]
If the mission is invisible, it should never show a "failed" message. So, just using invisible missions should allow you to achieve an effect similar to this, unless there's someplace in the code where invisible missions are displaying messages anyway.
