### ISSUE TITLE
Unable to really set the zoom scaling in preferences via the GUI

### ISSUE THREAD

**Issue by Exomancer** [endless-sky/endless-sky#1378]
In the preferences I can only toggle between 100 or 150.  I would assume that this should be a freely editable field.  I had to manually edit the preferences text file to 125 where I prefer it.  I am playing om an Ubuntu 16.04 setup.
Thanks.

**Comment by retrue** [comment]
More about this. In the preferences I can only change between 100 or 150 zoom when I am in full screen mode. If I am in window mode I cannot change zoom to 150.
However if I change to 150 zoom in full screen mode and I go back to window mode, the 150 zoom remains.
It should be possible to toggle zoom to 150 in window mode too.

**Comment by endless-sky** [comment]
The game tries not to let you set the zoom level high enough that some UI elements will be clipped off by the bottom of the screen. That's why you can't switch to zoom 150 when in windowed mode, because the window is too small to support it.
