### ISSUE TITLE
[BUG and ENHANCEMENT] Trade item highlighting not synced to ports item price highlighting

### ISSUE THREAD

**Issue by Exomancer** [endless-sky/endless-sky#1379]
[BUG]
If I land and go to the Spaceport, then go to the Map, Ports display, if I highlight say Heavy Metals, then go back to Trades, Clothing or Food may be highlighted.  I would think these should be synced so that one could make choices on what to buy and do so easily.

[ENHANCEMENT]
1) Actually, I would ask you to entertain MOVING the trades from a tab off the main pane to the Ports Map on the right side under the System Display.  Why? To quickly make decisions about buying and selling trades. I could move the highlighted items up and down and see the synced highlight on the trade and price panels at the SAME TIME without having to constantly toggle between screens which gets to be a pain.  I could then buy and sell right from the Ports Map very efficiently.

2) Also I would ask that in Port Map mode the navigation portion of the map be DISABLED.  This way one cud set up a run then explore the prices along the route without screwing up the navigation setup.

**Comment by endless-sky** [comment]
Other people have suggested merging the trade panel with the ports map, but it simply wouldn't work for people with small monitors unless either some of the columns of information are left out.

In the UI, there are a lot of places where I need to strike a balance between not being overwhelming and confusing for some players, vs. providing all the detailed information that other players want. In my opinion adding a trading interface to the map would make it way too cluttered.

**Comment by KiLEdEnNis** [comment]
unless you'd make an option for bigger monitors, but that'd be too unnecessary to be honest, because it's just a matter of remembering which good you want to buy for 5 seconds

**Comment by endless-sky** [comment]
This is fixed in 0.9.3: the "ports" map panel will always remember what coloring you were on last, and the trading panel will query to see if that coloring as a commodity, and if so it will select that commodity to start with. Similarly, selecting a commodity in the trade panel selects it in the ports map.
