### ISSUE TITLE
Make escort ships unable to target themselves

### ISSUE THREAD

**Issue by fcfort** [endless-sky/endless-sky#138]
If you have one escort, and you select the escort, then order escorts to fire on target, the escort will start to fire upon itself! This behavior is a bit unintuitive and dangerous. I think it might make more sense to make escorts unable to fire upon each other or upon the PC.

**Comment by endless-sky** [comment]
This is fixed in 0.8.7 - a ship can no longer fire on itself, and if escorts had been targeting a ship, they stop targeting it if you capture it.
