### ISSUE TITLE
[Enhancement] User set navigation waypoints

### ISSUE THREAD

**Issue by Exomancer** [endless-sky/endless-sky#1380]
Would it be possible to have user set navigation waypoints and/or stopovers.  I would love to set a string of jumps and set automatic refueling stops along the way.  Also along with this several options or types.  Automatic landing, ie: HARD Stopovers to end a mission, trade, or look at new missions, etc.  SOFT Stopovers were I get refueled but then automatically depart again and jump as set up in the navigation map ending in a Hard stop and autolanding to end a mission.  As you can see I would like some more automation in the leave to landing process.  Of course this can be a problem if on must fight.  That could be left as a limitation of auto-travel or one could put in presets as to HOW to fight and let the AI do it for you.  Also a limitation to auto-travel.  Finally a user override to fight or change something, ie: land at a non-preset location. and a resume like a car's cruise control.  Reason: Playing the game can lock me to my keyboard mindlessly watching for me to do everything.  This way I can do something else on my computer while I play and my ship has transited and landed and is waiting for me to come back to the game and do my transactions.
- Thanks

**Comment by Alkallid** [comment]
Hold shift as you path.

**Comment by psychiclegume** [comment]
That works for waypoints, but if you want to stop somnewher, that won't work.

**Comment by MarcelineVQ** [comment]
Currently there's a separation of playstyles where people who don't want to manage their flight can pay for that convenience in fuel tanks.

I can see the merit of a jump-then-land toggle though because it wouldn't negatively impact the outfitting ecosystem; something that makes 'j' do the path but then tries to land at the end and you have to over-ride autopilot in the usual way to prevent it.

**Comment by KiLEdEnNis** [comment]
I don't think it needs a change, you can sit back and press L once, and another issue w/ auto land would be: land on which planet/moon/station

**Comment by Alkallid** [comment]
You could click on the planet in the system menu to select it if needed, if it would be implemented.

**Comment by LocalGod79** [comment]
i think that doing this would detract from the spirit of this game.

yes, many features have been streamlined from the original E.V., but i don't think this game should end up so that you can visit your computer, take a bunch of jobs, plot your course and then walk away for 10 minutes while the a.i. plays the game for you.

this is already happening with the combat play style (gather fleet, demand tribute, try to land, come back five minutes later to demand tribute again and move on to the next system) - i don't think this encourages "intended use".

**Comment by Amazinite** [comment]
Hasn't auto-land been requested before anyways, making this a duplicate?

**Comment by Amazinite** [comment]
If you want to be able to have the game play in the background while you do something else, I'd have half of the screen be taken up by the ES window and the other half be whatever else I'm doing, allowing me to watch what's going on in the game while I work on other stuff. If your monitor isn't big enough for that then have each window take up most of the screen, but not all, and have one window shifted to the left and the other shifted to the right. This allows you to quickly click over to ES whenever you need to and then back to your other window with ease, and can leave either the ES map in the top left visible or the part of the HUD that displays your system in the top right so you know what's going on while you're in the other window.

**Comment by Exomancer** [comment]
This is a great idea except for the landing.  If you are working on something and you get to your last jump it you don't immediately hit 'L' you are going to wind up in no-man's lad out among the stars ... It's happened to me.  How does it really change ga,e plat to say have a modifier to immediately jump on departure and land on terminating the current series.  Then it's waiting for me to finish what I am concentrating on. Currently its 

> spaceport > 'D' > 'J' > jump*n > 'L' > spaceport

.  I could be 

> spaceport > '[SHIFT]+D' > jump*n > spaceport

.  One would use the [SHIFT] or [CTL] or [ALT] modifier with either the D or J key from the spaceport to initiate a programmed sequence.  One can hear pirate alarms and the sounds of shooting and pay attention, but otherwise I don't want to overshoot my landing after a long sequence when I have to go to the head.

**Comment by KiLEdEnNis** [comment]
escorts do land to refuel even if they have enough fuel to jump once (if they'd end in an empty sector)
that could also be applied to auto-pilot
