### ISSUE TITLE
Incorrect FWC Scouting 1 description

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1382]
The mission is to scout Kaus Borealis before an attack on it but the description in game says: "Travel through the Delta Sagittarii system to determine how strong the Navy presence is there, while JJ works to gather a fleet to attack it." In the game data it says: "Travel through the `<system>` system to determine how strong the Navy presence is there, while JJ works to gather a fleet to attack it." So I assume it's because '<system>' is the source and destination.

**Comment by Amazinite** [comment]
So `<system>` should be changed to `<stopover>`, right?

**Comment by Amazinite** [comment]
`<system>` needs to be changed to `<waypoint>`.

**Comment by warp-core** [comment]
The wiki doesn't list /<waypoint/> as a text replacement, I also haven't seen it used in other places where it could be.

**Comment by Amazinite** [comment]
Not sure how waypoint is different from stopover, but I know that stopover is an acceptable text replacement, is it not?

**Comment by Amazinite** [comment]
So stopovers are for planets and waypoints are for systems. So either waypoint needs to be made a text replacement or the system text replacement needs to apply for waypoints.

**Comment by warp-core** [comment]
I believe `<stopover>` is used when the mission requires the player to land on that planet, but I agree that there shouldn't really be a reason why one works but the other doesn't.

**Comment by warp-core** [comment]
`<waypoint>` may already be a text replacement, just not in the wiki.

**Comment by endless-sky** [comment]
Fixed in e3b394d.
