### ISSUE TITLE
Message reminder of deliveries when entering a system [enhancement]

### ISSUE THREAD

**Issue by woolsweater** [endless-sky/endless-sky#1383]
When concentrating on running jobs to build up cash, I find it hard to keep track of where I need to stop. The new map pop-up when jumping makes this much easier, but I still almost never remember which planet of a multi-planet system I'm supposed to land on.

I think it would be helpful to post a message on entering a system where you've got a stop to make, mentioning the destination.

I've knocked out an extremely simple implementation of this, in `Engine::EnterSystem()`

```
@@ -697,6 +697,44 @@ void Engine::EnterSystem()
        if(mission.ClearanceMessage() == "auto")
            mission.Destination()->Bribe(mission.HasFullClearance());

+   // If the system contains a mission destination or waypoint,
+   // show a message
+   for(const Mission &mission : player.Missions())
+   {
+       // No message about a mission the player should not be aware of
+       if(!mission.IsVisible())
+           continue;
+       
+       const Planet *destination = mission.Destination();
+       if(destination->GetSystem() == system)
+       {
+           string dropOffDescription;
+           if(mission.CargoSize() > 0)
+           {
+               dropOffDescription = "cargo";
+           }
+           else
+           {
+               dropOffDescription = mission.Passengers() == 1 ?
+               "a passenger" :
+               "passengers";
+           }
+           Messages::Add("You have " + dropOffDescription +
+                         " to drop off on " + destination->Name() + ".");
+       }
+       else
+       {
+           for(const Planet *stopover : mission.Stopovers())
+           {
+               if(stopover->GetSystem() == system)
+               {
+                   Messages::Add("You have a stop to make on " +
+                                 stopover->Name());
+               }
+           }
+       }
+   }
+   
```

Which I'm happy with for my own play:
<img width="301" alt="Shot of message feed with 'You have a stop to make...' entries" src="https://cloud.githubusercontent.com/assets/761245/17225467/e9dce3d2-54b9-11e6-8a37-1588c1bcaabc.png">

However, the simplicity of this logic does cause a bit of awkwardness:
<img width="280" alt="Doubled 'You have a stop to make...' message" src="https://cloud.githubusercontent.com/assets/761245/17225512/1e454a06-54ba-11e6-82a2-e2e88d01df56.png">

(It also refers to escorted ships as "passengers" due to the way the missions are defined.)

This is exacerbated when there are separate missions with one passenger and multiple passengers to the same destination: `Messages` can only combine identical messages, so you get "You have a passenger to drop off on Luna" _and_ "You have passengers to drop off on Luna" in the feed.

Obviously the logic either needs to be made much dumber: just "You need to stop on Luna" no matter what the mission is; or much more complex: 

> You have a passenger and cargo to drop off on Luna. 
>  You have passengers to drop off on Mars.

It looked, based on the way the mission, system, and planet data are mutually structured, as if the more complex logic would have to go into `PlayerInfo`, in a method that `Engine` would call from `EnterSystem()`. I wanted to get feedback on this whole idea before attempting to wrastle that.

**Comment by jafdy** [comment]
Looks nice. It may be an idea to make a PR with the dumber version first and get feedback from a much wider player base.

**Comment by Bladewood** [comment]
I support this.

**Comment by KiLEdEnNis** [comment]
great job (even though the only way of income for me is plundering/hijacking pirates, or doing escort missions to hijack the waiting ships)
but does it work for escort missions and such too?
looks awesome though :3

**Comment by MarcelineVQ** [comment]
Very cool idea, I vote for that latter example of yours where you combine multiple jobs for one location into one message. I'm not convinced you'd need to move the logic to PlayerInfo since Mission exposes the destination, if you're concerned the code is getting bulky you could move the code out to a function in the anonymous namespace at the top of Engine.cpp. It would make sense to move it to PlayerInfo if it was going to be used in more than one place though.

I was confused at first by what you said about escorts but I think what you're saying is there's no way to tell if a mission is an escort mission so you chose to have it say passengers?
That is basically determined by the NPC class in that an NPC of `npc accompany save` is an escort mission so one option is to have a bool and method in the NPC class, IsEscort(), that is set at the end of NPC::Load or during NPC::Instantiate by checking the failIf and mustAccompany fields. You could then check NPC::IsEscort against Mission::NPCs() in Engine to tell if your mission is an escort mission.

**Comment by woolsweater** [comment]
@MarcelineVQ Thanks for that information about escort missions! I had not dug deep enough into the data to see that part of it. I will keep that in mind for implementing this.

>It may be an idea to make a PR with the dumber version first

@jafdy That sounds reasonable; I will do that sometime this week unless I get commentary here from Author.

**Comment by Amazinite** [comment]
This is a thing now:
![screenshot_251](https://user-images.githubusercontent.com/17688683/29259863-df9c00c2-8093-11e7-8f6a-d09c0e54bcf8.png)
