### ISSUE TITLE
[Documentation] Weapons with blast radii always show on the minimap

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1384]
So people who are trying to make particle cannons with splash damage have an easier time figuring out why there are random blips appearing on the minimap 3 times a second.

I know from experience :|

**Comment by MarcelineVQ** [comment]
Splash shows on the radar? I had no idea

**Comment by Bladewood** [comment]
Neither did I, I only figured it out a few days ago.

**Comment by toilethinges** [comment]
Which is why this is tagged as "[documentation]".

**Comment by Bladewood** [comment]
Unless this is actually a bug and not just an undocumented feature of `blast radius`, I'd like it if there was something to the effect of a `force minimap` line to get around this issue: `"force minimap" 1` would cause all projectiles from the weapon to be shown on the minimap, while something else like `"force minimap" 0` would cause projectiles to not be shown.

**Comment by Alkallid** [comment]
@toilethinges To put in the wiki that this is so?

**Comment by KiLEdEnNis** [comment]
that does explain while missiles, torpedoes, rockets etc. show and other weapons don't, but yeah I doubt anyone knew/realized that

**Comment by Alkallid** [comment]
Missiles and torpedoes don't have blast radius, I think it's either missile strength or homing that does. Maybe just list all attributs that put it on the radar.

**Comment by MarcelineVQ** [comment]
Follow-up:
Any projectile with a `blast radius` or `missile strength` will show on the radar. With `blast radius`'s being nearly twice the size. 1.8 vs 1.
I'm not sure why blast radius uses a constant and isn't tied to the actual blast size, perhaps that would make a good enhancement. Stellar objects on the radar for example are based on the object's radius.

**Comment by endless-sky** [comment]
The current behavior is as intended, because in the current game anything with a blast radius is something you want to be aware of and steer clear of. The different sizes make it so that nukes can be distinguished from lesser missiles on the rader.
