### ISSUE TITLE
[Enhancement] FIle containing all finished missions finished text

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#1385]
Sorry about the title.... I could not come up with anything that good.

So long story short I may have messed up stuff with my save file and I deleted things that I should not have. It would be nice having something that lists all of the mission completion thingys with maybe it being sorted and in order (Order as in the FW missions are in order you can get them and do them). Ofc this could be used for cheating your way forward but you can already easy give yourself credits so...
Thanks for just reading this

**Comment by MarcelineVQ** [comment]
By finished text do you mean like`"FW Katya 1B: done"` ?
A map/tree of how missions are conected would be a pretty interesting side project for the benefit of creators or power users

**Comment by KiLEdEnNis** [comment]
but a save file is meant to be one file

anyway, a tree of missions that are done is a good idea but how can that be visible in-game without spoilers? maybe if it only shows missions that are done or active it could be implemented

**Comment by gunqqer** [comment]
The thing is this would be use so like if you were testing a mod or something that you made without needing to play the entire story to get where you want. So spoilers are not really a thing.
@MarcelineVQ yes that is what I do mean, I just could not think of that for some reason :P

**Comment by Amazinite** [comment]
Well if you wanted to test a mission that required previous missions to be done, then all you would need to do to test it would be to put the `to offer` conditions of the mission into your save file. Say I have a mission that only triggered after completing the FW campaign. The `to offer` condition would be `"main plot completed"`, so all I would need to do is put that condition into my save file, not play through the entire campaign.

**Comment by KiLEdEnNis** [comment]
or (what I did) copy a save file that has a lot of progress & make it a test file (that's how I tested my projec all the time)

**Comment by gunqqer** [comment]
One problem @KiLEdEnNis ... the save file I had before is a biiiit..... deleted... Wasn't my fault but... im a bit screwed right now :P

**Comment by jafdy** [comment]
Have you tried starting again? Armed with experience and starting again is really quite fun.

**Comment by KiLEdEnNis** [comment]
@jafdy yes I know, I may have played the story about 8 times... :3
(start interceptor, plunder, hijack sparrow, upgrade, hijack, have a heavy warship before the memorial day event)

**Comment by Alkallid** [comment]
@KiLEdEnNis Now was that a necassary comment?

**Comment by KiLEdEnNis** [comment]
@Alkallid the comment above that one was just about making a new game too, you can't forbid 1 person to comment if others do it

**Comment by Alkallid** [comment]
Jafdy was suggesting a solution. Don't make us destroy this issue.

**Comment by endless-sky** [comment]
You could just ask someone in the forum to post any saved game of theirs from after the main story is completed.

I don't think it would be a good idea to try to maintain a file in the wiki or the game data storing all those conditions and changes, though, because then that file would need to be updated every time the missions in the game were updated.

**Comment by KiLEdEnNis** [comment]
isn't it enough to just have the "condition" missions completed? (like "main plot completed" but none of the actual missions are)

**Comment by MarcelineVQ** [comment]
It's enough to have the condition fulfilled if the mission you want needs just that condition. `mission "Pug Cease Hostilities"` is an example of a mission that's just that simple.

The downside to skipping ahead by adding just "main plot completed" is that it will omit events, which means your world won't be the same as it would be if you had done the actual missions. You'll be missing the system and tech changes that happen through the story. And if future missions rely on you having triggered certain events or conditions throughout the story you simply won't have them.

`event`'s are what's responsible for changes in the galaxy like system links, planet descriptions, outfit availability, and such. If someone were to make a tool to allow you to pick your spot in the story it would also need to include events.

**Comment by Isaacssv552** [comment]
This seems like it would be best as some sort of modding tool.

**Comment by KiLEdEnNis** [comment]
what I do is just cloning a save file where nearly everything is done, and I keep that as a test file (like stated before)
I can give you a copy of my test file though (and remove the testing stuff I had)?
if there was some part on this piece of github where there was a downloadable test file with all missions / events completed it could help modders

**Comment by endless-sky** [comment]
As I said already above, if there were a file like this on GitHub it would mean that every time someone adds a new mission, they also have to update the "finished missions" file. That would be a maintenance nightmare and things would inevitably get left out. And, that's not even taking into account the fact that the finished missions will be different depending on what mission branches you follow.

**Comment by KiLEdEnNis** [comment]
it could just be updated once in a while, but the branches may mess it up indeed :/
