### ISSUE TITLE
{Bug} Pressing buttons after closing a menu may cause crash

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#1387]
To duplicate open your map, hit D to close then quickly hit F and it will close the map but the find thing will still pop up, and if you type something in and hit enter the game will crash. Also if on a planet and you leave then hit S or O the ship store and the outfitter respectively but there is nothing in them (you can still sell your ship)

**Comment by KiLEdEnNis** [comment]
like #1316 (which I made)? it's fixed too in next update

**Comment by gunqqer** [comment]
@KiLEdEnNis It is the same premise but this is including the map and hitting F to find which will cause a crash. #1316 is mostly the same

**Comment by KiLEdEnNis** [comment]
I think that's all the same problem, because the base problem is multiple commands executing at the same time, which got fixed
not sure though

**Comment by endless-sky** [comment]
Commit 8234e89 should fix this.
