### ISSUE TITLE
Possible bug/enhancement; changes to outfit/weapon/engine space do not show increases in max capacities

### ISSUE THREAD

**Issue by Sinsling** [endless-sky/endless-sky#1390]
When working on a mod that focuses on modules that convert outfit space to weapon/engine space, I noticed that outfits that convert space do not show any decreases or increases in the maximum room available.

While this usually is not a problem in the vanilla game, it is still possible to achieve an outfit space higher than a vessel's listed maximum. Or is the right-hand number simply to indicate the hull's base numbers?

**Comment by gunqqer** [comment]
The right hand number is the hull's base number, just buy a bactrian and get some mass expansions- you will get way over 700 whatever

**Comment by KiLEdEnNis** [comment]
yeah if you have an empty ship with mass expansions you have more available room than max room
