### ISSUE TITLE
Outfits from an outfitter that are placed in cargo are described as "plundered outfits"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1394]
I bought a scram drive and placed it into my cargo bay.
I looked at the trading tab.
"30 tons of plundered outfits."
This is preposterous! I legally acquired that scram drive, and it's calling it "plundered"!

**Comment by KiLEdEnNis** [comment]
maybe the outfitter stole it?

**Comment by toilethinges** [comment]
77b6c17
:)

**Comment by toilethinges** [comment]
8b4b678
:)
