### ISSUE TITLE
Allow outfits to also use license requirements

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1395]
Currently only ships can have licenses to own on them. Suggested that outfits also have this ability.
It's a topic that seems to pop up every once in a while on the Steam forums, so I thought I'd bring it up here.

**Comment by Amazinite** [comment]
:+1:

**Comment by Alkallid** [comment]
👍

**Comment by Bladewood** [comment]
...why

**Comment by MarcelineVQ** [comment]
gettin' steamy in here

**Comment by jafdy** [comment]
I feel this is important now because people are asking how to get the Coalition outfits. If they where put behind a licence then people might recognize that they need to do something for it.

**Comment by Bladewood** [comment]
I agree. Let's also do this for Wanderer worlds.
Then we could get Local Maps at pretty much every friendly world in the sky.

Would the Heliarch outfits also be available, behind a currently-unobtainable license akin to that used for Navy ships?

**Comment by jafdy** [comment]
I would put everything that "exists" in the law at that point in the appropriate outfitters behind an appropriate licence.

**Comment by KiLEdEnNis** [comment]
well, with the Coalition, having all warships, weapons & the reactors have a military license makes sense

**Comment by endless-sky** [comment]
Added (finally) in 14de6d8.
