### ISSUE TITLE
unable to clear huge mapping routes

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1398]
so I was bored and decided to do this
![jumps](https://cloud.githubusercontent.com/assets/10348657/17406948/caabdce6-5a65-11e6-9fee-0dd10efb010c.jpg)
but now I can't clear it (unless I clear it in my save file) :(
[edit] it MAY be possible because I also did it with a few sectors I created which I renamed, but after I cleared a big part of the travel [system]'s the rename thing didn't affect it and I could fix it

**Comment by MarcelineVQ** [comment]
You can press Del/Backspace to remove jumps without needing to click on a reachable unselected system.
You can also plan routes with J/Shift+J or Tab/Shift+Tab
https://github.com/MarcelineVQ/endless-sky/wiki/Tips,-Tricks,-and-UI-Features

**Comment by KiLEdEnNis** [comment]
I know about that, it just didn't clear when I plainly pressed a system (fixed now though)
still thanks for the help :)

**Comment by Bladewood** [comment]
...why would you do that in the first place

**Comment by KiLEdEnNis** [comment]
I liked the color :(
