### ISSUE TITLE
Reclassify Korath Raider as a medium warship instead of a heavy warship.

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1399]
My reasoning behind this suggestion is that it only has 27000 shield points which is significantly less than other tier 2 heavy warships. Furthermore, a strong wind can fairly easily disable one, as can a shield beetle.
The Tek Far 78 - Osk, a medium warship, does have lower capacities for outfits, weapons and engines, and one fewer turret mount, however, it has 7 more fighter bays than a raider, 4 gun ports where the raider has none and it has slightly more shielding (600 more than the raider) and multiple times as much hull strength (34100 as opposed to 9000). The only areas where the raider is significantly better than medium warships is in terms of cargo space and bunk space, however, a well outfitted Bactrian can disable a raider while having almost as many bunks and more cargo (even after mass expansion) as well as an extra fighter bay.

**Comment by KiLEdEnNis** [comment]
but one species' heavy warship is the other species' light warship, and even though they are all Korath, the Raider is (according to stories) thousands of years old, whereas the robotic Korath ships are quite new in comparison

the Korath always used the Raider, when they were still a strong species, and now they face extinction the robotic warships appeared (which were made during the end of their empire), which means they created far better technology
and the Raider is only better in bunks and cargo because the AI ships don't focus on that since they are warships rather than plundering raiders

so I think the Raider will stay a heavy warship (it is far better than for example the protector, which also loses from an AI light warship)

**Comment by warp-core** [comment]
As far as I know, there is no distinction between the Korath in the core and those who created the robotic warships in terms of the tier that their technology is at and so the Korath in the core are still a tier 2 civilization and so their heavy warships should be able to stand up to other tier 2 medium warships (wanderer strong wind for example) and tier 1 heavy warships (Hai shield beetle) which would be equivalent to tier 2 light warships.

**Comment by KiLEdEnNis** [comment]
yes, but in terms of in-game history the Korath Raider is way older than the AI warships, and the Korath didn't make an upgraded version of the Raider when they made the AI ships, meaning the Raider is outdated, but still a heavy warship

**Comment by Bladewood** [comment]
I was thinking about this yesterday, and so far I am impressed by my ability to make thoughts come true the next day.

History does not matter when it comes to ship classification. The Korath and Korath subraces are at tier 2, expected to be a match for other tier 2 races' ships, and their warships are split into three "subtiers": light, medium, and heavy warships, each expected to be a match for similar "subtiers," just like actual tiers, as well as also having tier 2 light warships be on par with tier 1 heavy warships and tier 2 heavy warships on par with tier 3 light warships.
Unless you are implying that the Korath exiles are a tier 1 faction, it does not make sense for the raider to stay a heavy warship. It probably does for their world-ships, given that those are also used by the tier 2 Kor Efreti, but the raiders should be demoted.

**Comment by KiLEdEnNis** [comment]
the Shield Beetle is tier 1, although it outmatches human heavy warships, and the Korath Raider does too, but unless I'm mistaken, the AI warships should be tier 3 (or there should be less space between tiers, because now it is human > huge AI Korath > Quarg that instakills inties > like 8 tiers of nothing > Drak)
the Raider can maybe be reclassified to tier 1, but it outmatches human ships by far, and the AI ships are even stronger
we'll see what MZ thinks though

**Comment by Bladewood** [comment]
Humans and Hai: Tier 1.
Korath and wanderers: Tier 2.
Quarg (at the moment): Tier 3.
Drak (at the moment): Tier 4.
Pug (at the moment): Tier 1 + Tier 3.

**Comment by KiLEdEnNis** [comment]
I personally think there should be a tier between 2 and 3 for the next generation of Wanderer ships and the massive AI ships

**Comment by jafdy** [comment]
Some people call the Hai tier 1.2 on the basis they are only a little bit better. Perhaps the same can be applied here, Korath and Kor Efret are tier 1.8.

**Comment by KiLEdEnNis** [comment]
the Raider seems like 1.6-1.8 yes, and the AI about 2.4

**Comment by Amazinite** [comment]
If we follow the "Tier X Heavy = Tier X+1 Light" then the Raider is far more like a light warship if it is considered T2.

**Comment by warp-core** [comment]
I don't think it's quite a light warship because of its fighter bays. It also has 6 turret mounts as well as having significantly higher outfit capacities than light warships, this coupled with its cargo space and crew compkiment and the fact that it can comfortably take on a wanderer light warship and almost all tier 1 heavy warships (except for the shield beetle and probably solitude) in stock configurations.

**Comment by Amazinite** [comment]
But it's T2, so that makes sense if it is a light warship.

**Comment by Bladewood** [comment]
Just to send something here...
https://github.com/endless-sky/endless-sky/wiki/Story-Ideas

Also, that page needs to be updated, at the bottom for example, where it says that the Drak are not yet in-game :|

**Comment by endless-sky** [comment]
The classification of the Raider reflects the fact that the Korath exiles have a much lower military technology level than the Korath automata. Warship classes are mostly based on size / mass. The Raider's mass is higher than quite a few heavy warships, and only one medium warship (the 128) is heavier than it.

**Comment by Bladewood** [comment]
So... literal heavy warship?

**Comment by KiLEdEnNis** [comment]
not tier 1, but I'd say the lowest tier 2
(which I stated too, the Korath exiles have outdated ships compared to the AI)

**Comment by Isaacssv552** [comment]
The ship that really needs to be a smaller class is the Quarg Wardragon. It is smaller (by mass) than some Light Warships and classified as a heavy. It is admittedly better than most heavies, but it is also T3, so that makes sense.

**Comment by Bladewood** [comment]
I thought about that, and I support that statement. It's even part of the description, which states that the Quarg use it as a "light warship".

**Comment by KiLEdEnNis** [comment]
the Quarg should get some more ships though, at least 1, to work as an actual heavy warship for defense, that would also pair with the Wardragon being reclassified to light (as on their tech level it is a basic ship with 2 skylances, not a heavy warship)

**Comment by jafdy** [comment]
The Quarg will be rebalanced at some point so what they have as ships at the moment will likely be changed to a much higher tier. My guess is that there will be at least a T5 region before the galaxy is full, therefor the Quarg will be at least T6. Such a shift is likely to render any discussion about where they belong now as obsolete.

**Comment by KiLEdEnNis** [comment]
having their 2 ships for now may be good for human space, but they need higher tier ships (like the Pug, the Quarg can have their 2 ships in this state, and higher tier ships for other areas, they can have the new ships in human space too, but they'd have to be rare)

**Comment by jafdy** [comment]
> The Quarg will be rebalanced at some point so what they have as ships at the moment will likely be changed to a much higher tier. My guess is that there will be at least a T5 region before the galaxy is full, therefor the Quarg will be at least T6. Such a shift is likely to render any discussion about where they belong now as obsolete.

**Comment by KiLEdEnNis** [comment]
yes I know, but I just feel that only 2 ships is a bit boring, so I'd like to see a few more Quarg ships (even just 1)
and a thing then is that the Quarg in human space become way stronger too

**Comment by jafdy** [comment]
I am not repeating myself again. All of the current Quarg are place holders and the entire race will be rebalanced at some point. But not yet.

**Comment by Bladewood** [comment]
It has been a long time since an issue surpassed 20 posts.
*clearly impressed*

**Comment by KiLEdEnNis** [comment]
I don't mean rebalance though, just more ships, I hope they'll be added too

**Comment by Disiuze** [comment]
@KiLEdEnNis https://groups.google.com/d/msg/endless-sky/IkoSYsZgMlQ/qSZUvTjFAQAJ

**Comment by KiLEdEnNis** [comment]
@Disiuze read something but didn't know it's actually happening
ty :)

**Comment by Isaacssv552** [comment]
@KiLEdEnNis 

If you use the plug-in could you please give some feed-back on what you'd like to see for a friendly Quarg mission line? Also, any feedback on the retaliation missions, which are balanced almost entirely on my own play experience. Thanks!

**Comment by KiLEdEnNis** [comment]
@Isaacssv552 took some time to look into it, posted my feedback on the link
still looks good though, the outfits (even though they're not the prettiest) are well-made (blame the Quarg for making ugly weapons :P)

**Comment by Isaacssv552** [comment]
@KiLEdEnNis

The images are all made by @msmestad, I do the coding and writing, not the graphics.

Also, I've replied to your feedback and will be looking into it.

**Comment by KiLEdEnNis** [comment]
@Isaacssv552 alright, and what I mean is, the things are well-made, but if I was a human in ES & saw a Quarg Skylance I would think "dang that's ugly", still great job, both of you
and msmestad makes ships too right? I have been working in Blender for about 3-4 days (never used it before), and I can use some instructions/tips on what to do when the Blender thing is done

**Comment by Bladewood** [comment]
This thread is about a Korath warship, not a Quarg weapon...

**Comment by KiLEdEnNis** [comment]
oh yes, excuse us
we already continued on the google groups
