### ISSUE TITLE
Map lost after loading savegame

### ISSUE THREAD

**Issue by uchua** [endless-sky/endless-sky#140]
When loading the default savegame that updates every you land at a planet/moon/station, when going into the map by hitting 'm' or the missions menu, all the systems I had mapped are gone. Reloading the save again causes even more previously mapped systems to disappear. Loading a snapshot seems to work fine, and the issue seems to go away for awhile, but it has been a recurring issue for me.

**Comment by endless-sky** [comment]
This is probably a file reading bug, maybe from the switch-over to using fopen() when I was not properly closing some files. I haven't heard any reports of this happening recently, so I'm going to assume that the fclose() fixes fixed this, and close it.
