### ISSUE TITLE
small hail mistake (hostile Syndicate)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1401]
so I was looking in the hails.txt and read this at the bottom (where the phrases are entire sentences"
		"Your hostile use of Syndicated Systems products is in violation the end user license agreement!"
does this sentence make any sense? and even if it does, isn't it too confusing? does there have to be a "to" between "violation the"?

**Comment by KiLEdEnNis** [comment]
also, is it even worth it to report hail mistakes? because for example "Join the Navy. Defend the Rim!" is a mistake since the Navy doesn't defend/patrol the Rim, and aren't that common in the Dirt Belt

**Comment by Alkallid** [comment]
The second one could just be standard advertising, because there are bound to be _some_ Gunboats checking for weapons of mass destruction.

**Comment by jafdy** [comment]
It should probably be this:

Your hostile use of Syndicated Systems products is in violation *of* the end user license agreement!

It makes sense as you would expect the Syndicate to say something along the lines of "Don't use our stuff to destroy our ships."

**Comment by Amazinite** [comment]
When I made the "( Defend || Tour || Visit || etc. ) the ( Rim || Core || Dirt Belt || Deep || etc.)" hail, I made it as more of an advertisement than a promise of where you're actually going to go. While it is true that they don't patrol those southern areas much, they're _technically_ suppose to.

**Comment by KiLEdEnNis** [comment]
maybe the "Rim" part should be gone, but indeed it's not a job description, more like advertising while they won't let you join yet until the story is made :(

**Comment by endless-sky** [comment]
Fixed (555ad6a).

**Comment by KiLEdEnNis** [comment]
weird that 2 missing letters made the entire sentence confusing, I'll have to take more English lessons :P
