### ISSUE TITLE
[bug] Able to launch with excess ammunition installed

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1402]
This was part of #1277, in which I listed three bugs that I noticed with ammunition when you for some reason have excess ammo (usually when installing or removing plugins). The first and third issue were fixed, but the second is still occurring.

If you have more ammunition installed than your capacity allows, you are still able to launch with that ammunition installed. I was thinking that the player should get a dialog box that prompts them to sell it similar to how having excess drones and fighters works.

**Comment by KiLEdEnNis** [comment]
I noticed these bugs as well but that only occurs while "cheating" or something, so I didn't think it'd be worthy to report

**Comment by jafdy** [comment]
Can happen after looting ammo from a disabled ship.

**Comment by endless-sky** [comment]
If you loot ammo in excess of what your weapons can hold, it goes into cargo, not into outfit space (unless there's a bug there).

**Comment by KiLEdEnNis** [comment]
and now that ammo has mass, you can't infinitely loot ammo; only as much mass as the cargo has space

**Comment by Amazinite** [comment]
@jafdy it's only something that occurs when messing around with plugins, as stated in OP.

**Comment by KiLEdEnNis** [comment]
similar to someone who made an issue that the game gives negative money when selling over 2 billion cargo; don't go that far (although this is more of an issue when you develop munition weapons)

**Comment by Amazinite** [comment]
@KiLEdEnNis I find that issue and this issue different, because that one is intentional and this one can happen on accident. That and the fact that the other two bugs in #1277 were fixed despite them never being an issue if you only play vanilla.

**Comment by KiLEdEnNis** [comment]
@Amazinite  yes, this one is a bit different since this can be an editing mistake, the other is just plain dumb, although they are both caused by editing files

**Comment by endless-sky** [comment]
This actually applies to any of a ship's attributes - if you edit the data files, you can create a ship which is able to launch even if one of its attributes is negative. However, that's actually useful in some situations - e.g. creating an outfit that cannot be reinstalled once it is removed from the ship it came in - so I don't think it's worth changing how that works.
