### ISSUE TITLE
Unfettered Hai are neutral to merchants

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1404]
the Unfettered Hai are plundering Hai ships and the player (as a merchant too, and escorts of course), but they leave all other merchants alone, is that intentional?

**Comment by LocalGod79** [comment]
those two governments don't interact, and the player's government is "escort".

**Comment by KiLEdEnNis** [comment]
can you describe what you mean exactly?
I saw Merchants in the same sector as Hai (Unfettered), and they ignored each other

**Comment by jafdy** [comment]
`system "Wah Ki"
...
	fleet "Large Unfettered" 800
	fleet "Small Northern Merchants" 18000
	fleet "Large Northern Merchants" 28000`

It's possible.

**Comment by KiLEdEnNis** [comment]
no problem, but they can be in the same sector, even though the Unfettered are not hostile to them (they shouldn't be hostile vs merchants, merchants should be made hostile to them, or else you'd have the Unfettered like you if you kill merchants)

**Comment by LocalGod79** [comment]
perhaps that's the one place where the merchants bring the Unfettered other technologies (like Supercapacitors) without raising suspicion that they're running supplies for both sides in exchange for neutrality...

that Merchant's guild is a wiley bunch...

**Comment by KiLEdEnNis** [comment]
that may be true, but I doubt every single merchant there is a dirty slut selling our technologies to the Unfettered

**Comment by Amazinite** [comment]
> I doubt every single merchant there is a dirty slut selling our technologies to the Unfettered

1) Harsh. 
2) Got something against the Unfettered?

**Comment by KiLEdEnNis** [comment]
no, I like the Unfettered except that they keep attacking the Wanderers (and there is no story where you help the Unfettered), but not every merchant bribes the Unfettered, so they should maybe be hostile to the Unfettered

**Comment by LocalGod79** [comment]
> but I doubt every single merchant there

> that Merchant's guild is a wiley bunch...

**Comment by KiLEdEnNis** [comment]
well, they tend to kill pirates a millisecond before I board them, so maybe you're right

**Comment by endless-sky** [comment]
Changed in 19eb0d8.

**Comment by KiLEdEnNis** [comment]
@endless-sky shouldn't it be the other way around? instead of making the Unfettered hostile to the merchants, make the merchants hostile to the Unfettered, or else you could kill merchants to be loved by the Unfettered, and the merchants wouldn't care about you killing Unfettered
just a question :)

**Comment by LocalGod79** [comment]
but then the merchants are the ones to instigate the attack...can of worms...

**Comment by KiLEdEnNis** [comment]
I thought it was that if one government is hostile to the other, the other opens fire even if not attacked?

**Comment by jafdy** [comment]
@KiLEdEnNis I think you missed the point.

**Comment by LocalGod79** [comment]
indeed - the point is, that in the rare instance that merchants and unfettered are in the same system, the Unfettered should attack the merchants (and the merchants respond) rather than visa versa (which would appear really strange)

**Comment by KiLEdEnNis** [comment]
never knew it worked that way, usually what I saw is (in my test project) the Republic opening fire on my new government even though I only made that government hostile to the Republic, before they attacked the Republic
knowing that could help a bit in the project
