### ISSUE TITLE
[enhancement] Mining personality

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1405]
Title says it all. This is probably already planned, but...

**Comment by Amazinite** [comment]
This was already mentioned by MZ in an earlier issue. Not 100% on the issue number but I can guarantee you it's already been mentioned before.

**Comment by KiLEdEnNis** [comment]
better to be sure, as long as there aren't 800 issues about it
mine hype o:

**Comment by toilethinges** [comment]
@Amazinite, I know, but I can't find it anywhere, so I figured I should make it.

**Comment by MarcelineVQ** [comment]
https://github.com/endless-sky/endless-sky/issues/1142 mentions the personality
https://github.com/endless-sky/endless-sky/issues/992 has additional interesting things
