### ISSUE TITLE
[bug] Minerals show a range and shots/sec

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1407]
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/17459238/b014fd06-5bfd-11e6-9141-8a709d7e99cc.png)

Likely because of the weapon icon:
```
weapon
		icon "effect/flotsam <mineral type>"
```

**Comment by KiLEdEnNis** [comment]
OP, MZ nerf it please D:

**Comment by Bladewood** [comment]
Impressive.

**Comment by endless-sky** [comment]
Fixed in 22fcd4a.

**Comment by Amazinite** [comment]
:ok_hand:
