### ISSUE TITLE
Strategic Ship Capturing

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1408]
Another thing that pops up on the Steam forums every so often.
http://steamcommunity.com/app/404410/discussions/0/360671583800202926/?tscn=1470534195

There are probably a number of ways of doing this (go ahead and give your two sense below), but here is a quick overview of my idea:
The current system could be the "automatic capturing" mode where you have no control over your crew and it's all up to RNGesus like it is now. This would be quicker to do, but depending on how good you are in the strategic mode it could lead to more crew deaths. 

Then there would be a "manual capturing" mode, where you take command of your crew and try to capture the enemy ship. It would likely be in a turn based top down fashion where you can see the inside of the ship and all it's rooms and compartments, not too much different from something like FTL. You would be shown the enemy ship with options on where to breach, how to breach, how many crew you want where, and so on. It would be fog of war style so that unless there are enemies in line of sight, you would be unable to see them. From there you are able to command squads of your crew and try to take out all the enemies on the ship in order to capture it.

This isn't anything I expect to see happening soon, but it would be nice to eventually have some form of ship capturing that gives the player more control over what happens.

**Comment by jafdy** [comment]
#871 
#292
These are vaguely related to this. This will probably encounter the same problems.

**Comment by KiLEdEnNis** [comment]
so like a top-down shooter in a ship?
what if the player dies then?
seems like a cool idea in my opinion though, but not easy to implement

**Comment by MessyMix** [comment]
For now we could have a text based thing, where there are buttons that control squad actions. It'll take one turn to move to places (e.g. Engine room, Crew Quarters, Flight Deck, Computer mainframe, Weapons platform), and if you're already there, then clicking the location again would have you try and "take" it with your squad. More squads / Better equipped squads will fare better, but then again a squad's defense will always be higher than its attack (makes logical sense, and is the current system). You should be able to, in the "hire crew" panel, assign crew to squads, and/or equipment to certain crew. If you already hold a location, then clicking the location again will have your squad "defend" it. Once you take hold of a minimum number of tactical locations on board a particular ship (e.g. 80% of its systems) OR the bridge (we can work out the details later), you "win" the ship. This should be in text feedback unless someone is willing to do an FTL / Hotline Miami thing for the game.

**Comment by KiLEdEnNis** [comment]
some details should be changed, I like the basic option but ADDING (instead of replacing) an option do actually put efford in it would be cool, but it'd maybe require every ship (and future ship) that can be boarded to have areas assigned to attack, defend, breach etc.

**Comment by Sinsling** [comment]
As I suggested on the linked thread, a simple text-based strategy would probably be easiest to add, including certain core systems on the ship. Included systems could be linked to ship class (medium/heavy/"city"/ext) with the smallest class ships not having a strategic option. (where the hell are you going to go on an interceptor?) Things might get weird with the transport class, considering the amount of size variance in that class.

Alternatively, it could be a ship attribute. This way adding strategic capture to a ship is optional. An example could be difficulty = x with 0 = no strategic option(default), 1 = medium sized ship, 2 = large, 3 = city, 4 = world/pug. It could even be paired with a forced strategic option (0(default)=off/1=on) so that ships like the korath automatic ships could require a strategy capture of some sorts instead of just relying on a suicide check due to their 0 crew.

**Comment by KiLEdEnNis** [comment]
tbh I don't think it'd be changed, at least not anytime soon

and w/ the AI ships it's good because for example the Kar Ik Vot has an 80% chance to blow up twice before capture, so 96% chance

**Comment by n545454** [comment]
Hello (new here)
What I would like to see (and millions more) would be an xcom(original) version of ship invasion.
To answer the question above what happens if the player dies. The player is just a boarding party commander. he dies, you lose men, the attack failed. You have more men and can attack as many times as you like. There is no save. Hardcore so to speak. You can invade as many times as you have men for your party.
To keep things simple a party of 4 max is appropriate, like every other game. However the 4 people represents say 400 in real life it is just trimmed down for visual simplicity etc.

This could happen, but clearly not for 1.0 release unless everyone screamed yes please.

I for one think that boarding should not be left to one ship and one crew as it is in 0.9. When you have a whole fleet, you should combine the total number of available crew for the assault into the attack.

The concept of countermeasures is also silly as it stands in the game, as you get counter-counter measures. This should be simplified to just a resistance factor of the crew so that T1 has resistance factor 1, tier 2 Resistance 2. That is the idea of Tiers, you don't need complicate it with a further countermeasure concept.

I have 7 more additions for the game but I think they would go in different areas.

**Comment by KiLEdEnNis** [comment]
it's supposed to be a "simple" 2D game, creating a 3D turn-based (or even 2D) ship invasion would ruin the boarding part, and having 4 people respresenting 400 crew members would be unrealistic and plain weird
if there as a "wait" option while boarding to allow allies to board could be an idea (in the meantime you can get shot by ships if you press wait), but having multi-boarding isn't an easy task and will not be done soon
and the countermeasures are just basic things to prevent Quarg ships to get captured, they'll get an actual description sometime,  a resistance factor is unneeded and adds unnecessary complexity to the game coding in my opinion, especially because stronger ships doesn't mean the controlling species are stronger

**Comment by n545454** [comment]
The counter measures do stop the ships being captured, but the Quarg ships are crap. 
I can take all their weapons, shields, anti missile technology, I would never take their ship, unless it could store 16 jumps in it and then I retrofit my entire fleet.
The only ship I would like to take is the Korath world ship and it is then that countermeasures are a pain. But my fleet is far more powerful than the world ships which last a second or two.

If I can destroy every ship in the game with my fleet including the quarg with electron beams only (I have upgraded them now), why not let players have a Quarg ship? What are you trying to do by stopping players achieving those ships in the game?

Is there going to be a plot in the game where the players learn the technology to get these ships?

**Comment by jafdy** [comment]
>I for one think that boarding should not be left to one ship and one crew as it is in 0.9. When you have a whole fleet, you should combine the total number of available crew for the assault into the attack.

This has been put forward before but was deemed as over-powering an over-powered feature.

The countermeasures are all just high defense hand to hand outfits. (see Security Station to compare)

**Comment by jafdy** [comment]
Quarg ships are very tough:
Bactrian: 17,500 shield
Skylark (week black one): 120,000 shield

yup that's useless.

**Comment by n545454** [comment]
Jafdy
Yes as a 1-1 ship the Quarg are very powerful. But I use a fleet and their most powerful ship lasts all of one second if mine are all targetting it.
I do notice there are mods to get all these ships.
One thing I don't especially like is the fuel pod system is so low on carriers, these are supposed to carry more fuel than every other ship by several times. But I guess this is for game balancing. I just cannot get 16 jumps into them so they can't follow my fleet anywhere.
Game needs a proper % indicator and missions completed list (greyed out, white, platinum if completed listing). You just don't know your progress for anything in it. 
The game is getting there, but it is still a 1.5X space game. 
Exploration. hyper space lanes and you know a planet is going to be there or not. So 2/10
Trading. You can buy and sell, missions, plots 3/10 (Still unsure why the Giant Bird Wanders want Squirrel clothing and will pay a high price for it...)
Building 0/10. 
Diplomacy 3/10.  There is some, disjointed. No progress indicators, no faction indicators.
Combat. Really good. 8/10 (Screen size is a little small when things happen, automated) Your ship is impossible to identify in your fleet and needs a highlight around it

So room for lots of improvement before v2.0

**Comment by KiLEdEnNis** [comment]
it's extremely logical that a Quarg ship loses vs a fleet, you can beat basically anything in large numbers, if you have 1000 jump drive carriers with skylances etc. you can even kill a Drak ship
Quarg ships ARE strong (very tough, built-in generator)
and the game is open source, the 2nd story is hardly halfway finished and the 1st one is going to get different versions (other sides), what makes the game good is that practically anyone can add a species, a story, make ships etc. (although harder than said), and the game isn't even 1.0 (which is usually the first real release before testing, and it takes long because MZ is only 1 person)
so either;
- have patience as there isn't a huge developing team
- quit the game if you hate it that much
- get involved, help adding content, make your own species, story, help develop the game and leave your mark in this open-source game (and I would like you to pick the 3rd option, everyone would)

**Comment by jafdy** [comment]
Carriers are meant to carry fighters not fuel. And why to you want 16 jumps worth of fuel anyway?

You do not want a mission completed list. A 1/2 hour play through without paying much attention to any mission makes the save look like this:
`	"Drak guarding Korath space: active"
	"Drak guarding Korath space: offered"
	"Drak guarding Sayaiban: active"
	"Drak guarding Sayaiban: offered"
	"Intro [0]: done"
	"Intro [0]: offered"
	"Intro [1 Freighter]: done"
	"Intro [1 Freighter]: offered"
	"Intro [2 Freighter]: done"
	"Intro [2 Freighter]: offered"
	"Intro [3 Freighter]: done"
	"Intro [3 Freighter]: offered"
	"Pact Recon 0: done"
	"Pact Recon 0: offered"
	"Pact Recon 1: active"
	"Pact Recon 1: offered"
	"Passengers [0]: done"
	"Passengers [0]: offered"
	"Passengers [1]: done" 2
	"Passengers [1]: offered" 2
	"Passengers [2]: done"
	"Passengers [2]: offered"
	"Rush Delivery [0]: done" 5
	"Rush Delivery [0]: offered" 5
	"Rush Delivery [1]: active"
	"Rush Delivery [1]: offered"
	"Rush Delivery [2]: done" 3
	"Rush Delivery [2]: offered" 3
	"Rush Delivery [3]: active"
	"Rush Delivery [3]: done" 3
	"Rush Delivery [3]: offered" 4
	"Tourists out [0]: done"
	"Tourists out [0]: offered"
	"Transport workers to <planet>: done"
	"Transport workers to <planet>: offered"`

On the whole I think you need to get used to the game and the community a bit more before throwing your wight around to much.

**Comment by jafdy** [comment]
Also a mostly done play through looks like this:
`	"Ask the Hai about the Unfettered: offered"
	"Bounty Hunting (Big): done" 9
	"Bounty Hunting (Big): offered" 10
	"Bounty Hunting (Marauder II): offered"
	"Bounty Hunting (Medium): done" 17
	"Bounty Hunting (Medium): offered" 18
	"Bounty Hunting (Small): done" 29
	"Bounty Hunting (Small): offered" 31
	"Bulk Delivery [0]: done" 32
	"Bulk Delivery [0]: offered" 33
	"Bulk Delivery [1]: done" 10
	"Bulk Delivery [1]: offered" 12
	"Bulk Delivery [2]: done" 5
	"Bulk Delivery [2]: offered" 5
	"Cargo [0]: done" 43
	"Cargo [0]: offered" 43
	"Cargo [1]: done" 40
	"Cargo [1]: offered" 40
	"Cargo [2]: done" 18
	"Cargo [2]: offered" 18
	"Cargo [3]: done" 8
	"Cargo [3]: offered" 8
	"Cargo [4]: done" 3
	"Cargo [4]: offered" 3
	"Colonists [0]: done" 16
	"Colonists [0]: offered" 16
	"Colonists [1]: done" 3
	"Colonists [1]: offered" 3
	"Cultural Data to Greenwater: done"
	"Cultural Data to Greenwater: offered"
	"Defend Sabik: done"
	"Defend Sabik: offered"
	"Drak guarding Korath space: active"
	"Drak guarding Korath space: offered"
	"Drak guarding Sayaiban: active"
	"Drak guarding Sayaiban: offered"
	"Escort (Extra Large, Northern): done" 2
	"Escort (Extra Large, Northern): offered" 2
	"Escort (Extra Large, Southern): done" 2
	"Escort (Extra Large, Southern): offered" 2
	"Escort (Large, Core): done" 4
	"Escort (Large, Core): offered" 4
	"Escort (Large, Northern): done" 4
	"Escort (Large, Northern): offered" 4
	"Escort (Large, Southern): done" 3
	"Escort (Large, Southern): offered" 3
	"Escort (Medium, Core): done" 2
	"Escort (Medium, Core): offered" 2
	"Escort (Medium, Northern): done" 2
	"Escort (Medium, Northern): offered" 2
	"Escort (Medium, Southern): done"
	"Escort (Medium, Southern): offered"
	"Escort (Small, Core): done" 4
	"Escort (Small, Core): offered" 4
	"Escort (Small, Northern): done" 2
	"Escort (Small, Northern): offered" 2
	"Escort (Small, Southern): done" 8
	"Escort (Small, Southern): offered" 8
	"FW Commitment: offered"
	"FW Conservatory 1: offered"
	"FW Escort 1: done"
	"FW Escort 1: offered"
	"FW Escort 1B: done"
	"FW Escort 1B: offered"
	"FW Escort 2: done"
	"FW Escort 2: offered"
	"FW Escort 2B: done"
	"FW Escort 2B: offered"
	"FW Escort 3: done"
	"FW Escort 3: offered"
	"FW Hope Recon 1: offered"
	"FW Hope Recon 1B: done"
	"FW Hope Recon 1D: offered"
	"FW Katya 1: offered"
	"FW Katya 2: done"
	"FW Katya 2B: done"
	"FW Katya 2B: offered"
	"FW Katya 2C: done"
	"FW Katya 2C: offered"
	"FW Katya 3: done"
	"FW Katya 3: offered"
	"FW Katya 4: done"
	"FW Katya 4: offered"
	"FW Katya 5: done"
	"FW Katya 5: offered"
	"FW Katya 5B: done"
	"FW Katya 5B: offered"
	"FW Katya 5C: done"
	"FW Katya 5C: offered"
	"FW Katya 6: done"
	"FW Katya 6: offered"
	"FW Katya 6B: done"
	"FW Katya 6B: offered"
	"FW Katya 6C: done"
	"FW Katya 6C: offered"
	"FW Katya 7: done"
	"FW Katya 7: offered"
	"FW Katya 7B: done"
	"FW Katya 7B: offered"
	"FW Katya 7C: done"
	"FW Katya 7C: offered"
	"FW Pirates 1: done"
	"FW Pirates 1: offered"
	"FW Pirates 2: done"
	"FW Pirates 2: offered"
	"FW Pirates 3.1: offered"
	"FW Pirates 3: done"
	"FW Pirates 3: offered"
	"FW Pirates 4: done"
	"FW Pirates 4: offered"
	"FW Pirates 4B: active"
	"FW Pirates 4B: offered"
	"FW Plasma Testing 1: done"
	"FW Plasma Testing 1: offered"
	"FW Plasma Testing 1B: done"
	"FW Plasma Testing 1B: offered"
	"FW Prisoner Parole 2: done"
	"FW Prisoner Parole 2: offered"
	"FW Prisoner Parole: done"
	"FW Prisoner Parole: offered"
	"FW Recon 0: done"
	"FW Recon 0: offered"
	"FW Recon 1: done"
	"FW Recon 1: offered"
	"FW Recon 2: done"
	"FW Recon 2: offered"
	"FW Recon 3: done"
	"FW Recon 3: offered"
	"FW Recon 3B: done"
	"FW Recon 3B: offered"
	"FW Senate 1: done"
	"FW Senate 1: offered"
	"FW Senate 1B: done"
	"FW Senate 1B: offered"
	"FW Supply Convoy 1: done"
	"FW Supply Convoy 1: offered"
	"FW Syndicate Diplomacy 1: done"
	"FW Syndicate Diplomacy 1: offered"
	"FW Syndicate Diplomacy 1B: done"
	"FW Syndicate Diplomacy 1B: offered"
	"FW Syndicate Diplomacy 1C: done"
	"FW Syndicate Diplomacy 1C: offered"
	"FW Syndicate Diplomacy 1D: done"
	"FW Syndicate Diplomacy 1D: offered"
	"FWCarrier License: offered"
	"Family [0]: done" 30
	"Family [0]: offered" 37
	"Family [1]: done" 23
	"Family [1]: offered" 33
	"Family [2]: done" 21
	"Family [2]: offered" 27
	"Family [3]: done" 8
	"Family [3]: offered" 14
	"First Contact: Hai: offered"
	"First Contact: Korath: offered"
	"First Contact: Korati Efreti: offered"
	"First Contact: Kuwaru Efreti: offered"
	"First Contact: Quarg: offered"
	"First Contact: Unfettered: offered"
	"First Contact: Wanderer: offered"
	"Geminus Rebuilt: offered"
	"Hired Mercenaries: offered" 4
	"Human Cultural Archives: done"
	"Human Cultural Archives: offered"
	"Intro [0]: done"
	"Intro [0]: offered"
	"Intro [1 Interceptor]: done"
	"Intro [1 Interceptor]: offered"
	"Intro [2 Interceptor]: done"
	"Intro [2 Interceptor]: offered"
	"Intro [3 Interceptor]: done"
	"Intro [3 Interceptor]: offered"
	"Kestrel Available: offered"
	"Kestrel Testing: done"
	"Kestrel Testing: offered"
	"Kestrel: More Weapons: active"
	"Kestrel: More Weapons: offered"
	"Language: Wanderer 1A: done"
	"Language: Wanderer 1A: offered"
	"Language: Wanderer 1B: done"
	"Language: Wanderer 1B: offered"
	"Language: Wanderer break: offered"
	"Large Bulk Delivery [0]: done" 24
	"Large Bulk Delivery [0]: offered" 24
	"Large Bulk Delivery [1]: done" 18
	"Large Bulk Delivery [1]: offered" 18
	"Large Bulk Delivery [2]: done" 2
	"Large Bulk Delivery [2]: offered" 2
	"Large Rush Delivery [0]: done" 20
	"Large Rush Delivery [0]: offered" 20
	"Large Rush Delivery [1]: done" 23
	"Large Rush Delivery [1]: offered" 23
	"Large Rush Delivery [2]: done" 6
	"Large Rush Delivery [2]: offered" 6
	"Large Rush Delivery [3]: done" 3
	"Large Rush Delivery [3]: offered" 3
	"Liberate Kornephoros: done"
	"Liberate Kornephoros: offered"
	"Pact Recon 0: done"
	"Pact Recon 0: offered"
	"Pact Recon 1: done"
	"Pact Recon 1: offered"
	"Passengers [0]: done" 64
	"Passengers [0]: offered" 69
	"Passengers [1]: done" 43
	"Passengers [1]: offered" 49
	"Passengers [2]: done" 27
	"Passengers [2]: offered" 29
	"Passengers [3]: done" 15
	"Passengers [3]: offered" 16
	"Passengers [4]: done" 5
	"Passengers [4]: offered" 5
	"Pookie, Part 1: active"
	"Pookie, Part 1: offered"
	"Provide security for pleasure cruise: done"
	"Provide security for pleasure cruise: offered"
	"Rescue Katya 2: done"
	"Rush Delivery [0]: done" 24
	"Rush Delivery [0]: offered" 25
	"Rush Delivery [1]: done" 12
	"Rush Delivery [1]: offered" 14
	"Rush Delivery [2]: done" 5
	"Rush Delivery [2]: offered" 5
	"Rush Delivery [3]: done"
	"Rush Delivery [3]: offered" 2
	"Southern Carriers Trigger: offered"
	"Strike Breakers [factory]: done" 7
	"Strike Breakers [factory]: offered" 8
	"Strike Breakers [mining]: offered" 3
	"Strike Breakers [textile]: done" 6
	"Strike Breakers [textile]: offered" 6
	"Terraforming 1: done"
	"Terraforming 1: offered"
	"Terraforming 2: done"
	"Terraforming 2: offered"
	"Terraforming 3: done"
	"Terraforming 3: offered"
	"Terraforming 4: done"
	"Terraforming 4: offered"
	"Terraforming 5: done"
	"Terraforming 5: offered"
	"Tourists back [0]: done"
	"Tourists back [0]: offered" 2
	"Tourists back [1]: done" 6
	"Tourists back [1]: offered" 8
	"Tourists back [2]: done" 8
	"Tourists back [2]: offered" 13
	"Tourists out [0]: done" 11
	"Tourists out [0]: offered" 11
	"Tourists out [1]: done" 34
	"Tourists out [1]: offered" 36
	"Tourists out [2]: done" 4
	"Tourists out [2]: offered" 5
	"Transport farmers to <planet>: done" 23
	"Transport farmers to <planet>: offered" 27
	"Transport mill workers to <planet>: done" 28
	"Transport mill workers to <planet>: offered" 28
	"Transport miners to <planet>: done" 25
	"Transport miners to <planet>: offered" 34
	"Transport scientists: done"
	"Transport scientists: offered"
	"Transport workers to <planet>: done" 47
	"Transport workers to <planet>: offered" 57
	"Unfettered Jump Drive 1: offered"
	"Unfettered Jump Drive 2: offered"
	"Unfettered Jump Drive 3: offered"
	"Unfettered Jump Drive 4: offered"
	"Unfettered Tribute 1: done" 2
	"Unfettered Tribute 1: offered" 2
	"Unfettered Tribute 2: done" 3
	"Unfettered Tribute 2: offered" 3
	"VIP transport: done"
	"VIP transport: offered"
	"Visit Wanderers Again: done"
	"Visit Wanderers Again: offered"
	"Wanderers Conversation: offered"
	"Wanderers: Defend Vara Ke'sok: done"
	"Wanderers: Defend Vara Ke'sok: offered"
	"Wanderers: Defended Vara Ke'sok: done"
	"Wanderers: Defended Vara Ke'sok: offered"
	"Wanderers: Diplomacy: done"
	"Wanderers: Diplomacy: offered"
	"Wanderers: Translation Machine: done"
	"Wanderers: Translation Machine: offered"
	"Wanderers: Truce Timer: offered"
	"Wanderers: Unfettered Diplomacy 1: done"
	"Wanderers: Unfettered Diplomacy 1: offered"
	"Wanderers: Unfettered Diplomacy 1A: done"
	"Wanderers: Unfettered Diplomacy 1A: offered"
	"Wanderers: Unfettered Diplomacy 1B: done"
	"Wanderers: Unfettered Diplomacy 1B: offered"
	"Wanderers: Unfettered Diplomacy 1C: done"
	"Wanderers: Unfettered Diplomacy 1C: offered"
	"a hobo with drugs: offered"
	"assisted free worlds" 3
	"cargo space" 10
	"combat rating" 280
	day 5
	"event: FWCarriers"
	"event: S license"
	"event: Sich'ka'ara empty"
	"event: Sich'ka'ara restored"
	"event: Tarazed neutrality"
	"event: battle for Thule"
	"event: catalytic ramscoop available"
	"event: geminus rebuilt"
	"event: initial deployment 1"
	"event: initial deployment 2"
	"event: initial deployment 3"
	"event: initial deployment 4"
	"event: joined the free worlds"
	"event: kestrel available: more weapons"
	"event: oathkeepers founded"
	"event: plasma turret available"
	"event: prepare for battle of Kornephoros"
	"event: recapture of Kornephoros"
	"event: remembrance day"
	"event: southern carriers 1"
	"event: southern carriers 2"
	"event: southern carriers 3"
	"event: southern carriers 4"
	"event: start of hostilities"
	"event: syndicate tech available"
	"event: temporary ceasefire"
	"event: terraforming Rand"
	"event: wanderer / unfettered peace"
	"event: wanderer technology available"
	"event: wanderers: truce timer"
	"event: war begins"
	"event: war begins: offered"
	"fw pirate suggestion: diplomacy"
	"hired mercenaries (large north): offered"
	"hired mercenaries (large syndicate): done" 3
	"hired mercenaries (large syndicate): offered" 10
	"hired mercenaries (medium north): offered" 2
	"hired mercenaries (medium south): offered" 2
	"hired mercenaries (medium syndicate): offered" 4
	"hired mercenaries (small north): done"
	"hired mercenaries (small north): offered" 7
	"hired mercenaries (small south): offered"
	"hired mercenaries (small syndicate): done" 7
	"hired mercenaries (small syndicate): offered" 15
	"hired mercenaries (swarm south): offered" 2
	"hired mercenaries (swarm syndicate): offered" 2
	karma
	"kestrel available"
	"kestrel: more weapons"
	"language: Wanderer"
	"license: Militia Carrier"
	"license: Pilot's"
	"license: Wanderer"
	month 5
	"net worth" 2000000000
	"oathkeepers founded: offered"
	"passenger space" 13
	"plasma turret available: offered"
	"remembrance day: offered"

And a progress bar is meaning less as there are a (theoretically) infinite number of mission.

**Comment by endless-sky** [comment]
This is a classic example of "feature creep." If you want to play XCom, play XCom. If you want to play FTL, play FTL. If you want to play a 4x game, play a 4x game. But all those are well beyond the scope of a space trading and combat game, which is all ES is intended to be.

**Comment by Amazinite** [comment]
Fair enough.
