### ISSUE TITLE
mission; 43 people want to colonize Charon station

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1409]
![colonize](https://cloud.githubusercontent.com/assets/10348657/17461639/eb27dbb6-5c93-11e6-8bd7-ca34be0e4753.jpg)
why is this a thing? why would 43 people want to colonize a refueling station? (42 ok, but 43)

**Comment by toilethinges** [comment]
Notice the line in the description "tiny, cramped, and aging, with twice as many workers as it was designed for." :laughing:

**Comment by KiLEdEnNis** [comment]
@toilethinges yes, workers, not colonists lol

**Comment by Bladewood** [comment]
Trust me, this is the kind of entertaining thing you will find on the Steam forums, and that's the way it should be, for the lulz.
For example,
http://steamcommunity.com/sharedfiles/filedetails/?id=700810715
http://steamcommunity.com/sharedfiles/filedetails/?id=553088398
http://steamcommunity.com/sharedfiles/filedetails/?id=580593723
http://steamcommunity.com/sharedfiles/filedetails/?id=545058331
http://steamcommunity.com/sharedfiles/filedetails/?id=610420921
http://steamcommunity.com/sharedfiles/filedetails/?id=675822571
The list goes on.

**Comment by KiLEdEnNis** [comment]
it would make missions a bit unrealistic, but to be honest full-realism is boring (like Elite Dangerous, landing takes ages, jumping takes ages, got bored after 2 hours)

**Comment by endless-sky** [comment]
They're members of a cult seeking to form a colony in a place where they can be isolated from all worldly distractions. Shame on you for your religiously insensitive criticism of their life choices. :)

**Comment by KiLEdEnNis** [comment]
@endless-sky and that's why YOU are the owner of the game, not me :P
