### ISSUE TITLE
FW Hope Recon 1C mistake

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1410]
in it (where you investigate on Hope and notice a Gunboat w/ crew setting up the equipment) it says "A gunboat typically only has two crew members", while the Gunboat has a required crew stat of 7
(lowering required crew would make no sense, so this part needs a minor rewrite, or this piece of text should be deleted)

btw, file: free worlds start

**Comment by kitsunemochi** [comment]
Yea I noticed that as well, also when you're testing the plasma turrets on Rust, there is a line where Barmy Edwards says "Anything other weak spots?"  It's line 760 in 'free worlds start.txt', perhaps just "Any other weak spots?" Didn't think it warranted an Issue.

**Comment by KiLEdEnNis** [comment]
people make issues about spelling mistakes; if they didn't they'd remain in the game
just like a spelling mistake disabled large asteroids for as long as the game existed
I noticed this gunboat thing before, but that was before I was even on github (months ago)

**Comment by endless-sky** [comment]
Fixed in 47b3af2.

**Comment by KiLEdEnNis** [comment]
I think MZ got confused with 2 similar issues :P

**Comment by endless-sky** [comment]
Fixed in b168ab7.

**Comment by KiLEdEnNis** [comment]
from a huge amount of notifications & a lot of recent fixes, I assume 0.9.5 release is drawing near? o:

**Comment by KiLEdEnNis** [comment]
I realized a few weeks ago & keep thinking; if you pick off the 7 crew members (minimum would already be 8 as it has a turret), there could be 4, max. (+ turret) 5 other crew members on the Gunboat, and with the minimum requirement of 7 or (+ turret) 8 crew members, the Gunboat would move erratically because it lacks crew

simplified
Gunboat max crew: 12
mistake 1: since the Gunboat has a turret, there'd be 8 crew members, not 7, in the snow
mistake 2: if you would pick them all off & try to capture the ship which tries to escape, they would lack the minimum crew required

reopen this issue for that or...?
