### ISSUE TITLE
New outfit tags

### ISSUE THREAD

**Issue by Isaacssv552** [endless-sky/endless-sky#1412]
I would like to add two more tags to outfits.

1. An "unremovable" tag, similar to the unplunderable tag, that designates an outfit as not being removable. This would be useful for built-in outfits not meant to be removed. For example, a ship might have an integrated fusion reactor or a special weapon.
2. A "canfirewhilecloaked" tag for both weapons, ships, and outfits. Preferable with 4 values. 
0: default, can't fire while cloaked.
1: can fire this weapon (if on a weapon) or all weapons (if on a ship/outfit) while cloaked.
2: same as one but requires the tag be present on one other source. If weapon+ship only that weapon can fwc, if outfit+ship all weapons can fwc.
3: tag required in all 3 places. Outfit+ship+weapon and can only fire weapons with the tag.
This would be useful for special weapons, ships, and outfits.

How would I go about adding this to the c++ files? I've looked but cannot find the method that controls whether weapons can fire and can't figure out how to add a tag properly in the first place.

**Comment by Bladewood** [comment]
[Yay, my godthoughtpowerthingies worked!](http://steamcommunity.com/app/404410/tradingforum/360670708773365290/)

I'd like the second one to also apply to afterburners.

**Comment by Amazinite** [comment]
The unremoveable tag could be used on the Arfecta's cloaking device to explain to the player why they can't remove it instead of them having to look at the Arfecta's text code to know why.

**Comment by Sinsling** [comment]
I would love to see an unremovable tag as well if anyone with the knowledge is able to create these tags. (I actually need it for the mod I am working on XD)

For the fire while cloaked, it would seem simpler to just keep the tag on the weapon. 0 (default) for not firing, and perhaps 1 for firing at 1.5X the energy cost and 2 for firing at normal energy cost.

**Comment by Amazinite** [comment]
If a weapon could fire when cloaked then I feel like it would accelerate the fuel consumption of the cloak.

**Comment by Bladewood** [comment]
Just like in FTL. Except there is no Stealth Weapons augment.

**Comment by Isaacssv552** [comment]
The unremovable tag could be used with reactors to more clearly show where the power/heat is coming from to both player and modder. For example, the Quarg ships currently have excess outfit space because the 80 space needed for the Antimatter Core was never removed. 

Also, it would allow variant versions of ships with special, high-efficiency (or otherwise boosted), versions of outfits. For example, a upgraded variant of the republic cruiser meant to retain superiority of energy generation over the free worlds might have an integrated fusion reactor with a 10% reduced heat signature.

**Comment by Bladewood** [comment]
I thought about the Antimatter Core issue, and now I propose that we re-add the Antimatter Core, but set an `unplunderable` tag on it.

Those variants are the result of mixing the Navy with marauder ships.

As for the afterburner issue, once again, I didn't know either, I only just figured it out after playing with Michael's kestrel for a few hours :smile: 

And now I thought about it all, and here's what I have to say now:
If we sold a ship with these unremovable outfits, could we install them onto another ship?

**Comment by Amazinite** [comment]
You would probably want outfits marked as unremoveable to be sold with the ship and not go to the outfitter.

**Comment by Sinsling** [comment]
The general premise of an irremovable outfit is probably because it is in some way attached to the ship that it becomes an integral part of the hull. If you where to sell the ship, the parts could be cut back out of the hull to be reinstalled on a new ship. (lets just ignore that any sane shipwright would keep the ship intact and sell it with the mark-up instead of destroying the hull to take out the parts)

If you do not want the outfit to be installible (say an efficient chassis-mounted weapon or something), just use the uninstallible tag in addition to the unremovable tag.

**Comment by Isaacssv552** [comment]
I'm not sure what you mean by navy and marauder variants. I was referring to a hypothetical new variant. 

As far as the ACs, I was just using them as a vanilla example, I've considered using unplunderable, but it doesn't fit with all the other plunder able reactors, which are often larger than the AC. It should either accompany a change to all reactors over a certain size or wait for the Quarg, and T3 as a whole, to be expanded.

Unistallible shoul probably be its own tag, yes.

**Comment by KiLEdEnNis** [comment]
"canfirewhilecloaked" seems kinda OP, since you can cloak, then fire (free damage), and it ruins the cloaking because they know where you are

**Comment by Isaacssv552** [comment]
That is why it would have so much flexibility on the requirements. It is expected that the individual ship/weapon/outfit maker find a way to balance things. For example, a colorable afterburner with 50% higher fuel consumption would be reasonably balanced. A ship with "canfirewhilecloaked 1", no shields, and only 200 fuel might be balanced, and changing to "canfirewhilecloaked 2" would probably make it weak enough for balance.

**Comment by KiLEdEnNis** [comment]
I don't think that that'd be a thing though, the unremovable tag is a great idea but firing when cloaked seems a bad idea in my opinion
but then again, creating new ideas is good for the game, and there'll be a few bad ones, I do like the unremovable :)

**Comment by Sinsling** [comment]
Isaacssv, uninstallable is an incoming tag for 0.9.3.

**Comment by Isaacssv552** [comment]
Uninstallable and unremovable aren't the same thing, I would like both. Also, it doesn't seem to be in the code yet so there is no reason not to try and help implement it.

**Comment by KiLEdEnNis** [comment]
uninstallable would be removable, unremovable would be installable, they're like the opposite
and all ideas are good for the game, it keeps it alive

**Comment by Amazinite** [comment]
@Isaacssv552 `"installable" -1` makes things uninstallable already.

**Comment by Isaacssv552** [comment]
Nice, didn't realize ShipCanBuy checked that. Unremovable still fulfills a distinct role though, installable doesn't restrict selling.

**Comment by KiLEdEnNis** [comment]
maybe unremovable outfits shouldn't show up after selling the ship it carries, as that would be realistic

**Comment by Isaacssv552** [comment]
I'd let them show up and just allow developers to use installable -1 to prevent reinstallation if they wish. Someone might want a outfit that is merely difficult to uninstall without disassembling the ship, not impossible.

**Comment by MarcelineVQ** [comment]
@Isaacssv552 OutfitterPanel.h/.cpp
OutfitterPanel::CanBuy() and OutfitterPanel::FailBuy() might also be of interest to you
Also CanAdd() in ShipCanBuy() refers to Outfit::CanAdd()

**Comment by Bladewood** [comment]
I was working on an experimental ship that had a "brain" outfit with an `automaton 1` tag and an `installable -1` tag, so that it would require a decent crew if you removed the brain, and you could not reinstall the brain because you just caused brain death for the ship.

**Comment by KiLEdEnNis** [comment]
@Bladewood that brain idea could be cool for organic alien-ships (where the species themselves are the brains and the ships are bodies) o:

**Comment by endless-sky** [comment]
If you're creating a custom ship that should always come with a special weapon that can't be removed, you can accomplish that by giving the hull a negative attribute that the weapon satisfies (like the cloaking device on the Arfecta). If you want it to also be impossible to install that weapon on any other ship (say, if you sell the ship in order to gain access to its individual outfits), you can also give the outfit "installable" -1. So, it's pretty easy to do that with the existing game mechanics.

Firing while cloaked, on the other hand, would be absurdly unbalanced. (Although, you can create special "cloaked" enemies like the nanobots that do exactly that.)

**Comment by KiLEdEnNis** [comment]
but to make a (for example) weapon unremovable by applying a negative hull tag, what tag could you even use? the only tag I know of is fuel consumption
or can you just create a random word on the weapon attribute like "zxcv" 1 and then give the ship that "zxcv" -1?

**Comment by Bladewood** [comment]
As described in the Steam thread I linked way up there, you can use any attribute (as long as it doesn't break the game in some way), including non-existent attributes. I used a `"special weapon" -1` tag on a ship, and put a `"special weapon" 1` tag on a weapon. Now that weapon can never be removed (unless I sold the ship) because uninstalling it would set `"special weapon"` to -1.

Also, cloaked afterburners? :(

**Comment by KiLEdEnNis** [comment]
ah, so I can use an unexisting tag, and then set installable -1 for a 100% built-in ship-specific weapon?
that's very useful information for the ship(s) I am working on, now to learn to draw laser beams etc. :)

**Comment by Isaacssv552** [comment]
I still think and unremovable tag would be both simpler and more useful than the current system, but there doesn't seem to be interest so I'll close this issue.

I mostly wanted firewhilecloaked to open up more options for ship/weapon/outfit creation, if M.Z. thinks it is too inherently unbalanced to ever be used I will concede the point.
