### ISSUE TITLE
`In Stock` and `In Cargo` won't appear at the same time

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1414]
If there is >1 of an outfit in stock and you go to place one of them in your cargo, the in stock line is replaced with the in cargo line.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/17470991/bfc389d6-5d0e-11e6-9d42-fd25e30e5e98.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/17470992/c01b6606-5d0e-11e6-8d65-2537ab021eb1.png)

I think it would be better if it told you both how many were in stock and how much you had in your cargo.
![screenshot_4](https://cloud.githubusercontent.com/assets/17688683/17470998/cb949124-5d0e-11e6-8367-fecc4f774769.png)

**Comment by KiLEdEnNis** [comment]
don't forget the installed tag ;)
"installed: 1 in cargo: 1 in stock: 1" for example
still nice find :D

**Comment by Amazinite** [comment]
The installed tag already shows above where the in stock tag is in the photoshopped image, so that isn't really an issue.

**Comment by endless-sky** [comment]
What purpose would this serve? If you have an outfit in cargo, it gets installed from cargo. Otherwise, it gets installed from stock. So showing both just seems like extra clutter and would probably do more harm (in terms of being confusing and adding unnecessary information) than good.

**Comment by Amazinite** [comment]
My thought was just that it would be nice to know how many are in stock so that you can know how many more you are able to buy into cargo if you're intending to transport them somewhere, mainly when trying to outfit a new fleet.

**Comment by jafdy** [comment]
I always wanted this but i never got round to asking for it.
While it may well be extra clutter it would also reduce confusion as there would be no sudden changing of whats being shown.
At this point I would like to stress that this is your game and we will go with you however you play this.

**Comment by KiLEdEnNis** [comment]
it would be a nice addition but it's not that important

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/1/144512753470077181/
