### ISSUE TITLE
Accepting offer to reload ammunication causes crash

### ISSUE THREAD

**Issue by masnider** [endless-sky/endless-sky#1415]
I have an escort. I land on a planet and when checking the outfitter I have I receive a prompt "Do you want to reload all the ammunition for your ships?" (As far as I recall they only have a Javelin launcher, and still several hundred missiles). If I click cancel things are fine. If I click OK, the game crashes. Let me know what else I can do or need to do to help repro or capture the issue.

**Comment by jafdy** [comment]
#1277

**Comment by masnider** [comment]
I didn't realize that was the same issue. I can close this if you prefer. Thanks for the responsiveness!

**Comment by Amazinite** [comment]
It's already fixed for v0.9.3, so please close this.

**Comment by masnider** [comment]
No problem, is there some workaround in the meantime? Just sell off a bunch of the offending ammo? Is there some easy way to know what the limit should be? I have no mods running.

**Comment by KiLEdEnNis** [comment]
just look at the ammo capacity of a launcher x the amount of launchers, sell off all excess ammo (press cancel when it doesn't tell you how much reloading costs)

**Comment by masnider** [comment]
Ah that's a great way to tell the difference. Thanks!
