### ISSUE TITLE
No passengers in FW Conservatory 1

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1419]
FW Conservatory 1 should have 3 passengers but appears to have none.

**Comment by KiLEdEnNis** [comment]
did you check your ship hull to see 3 people in space suits holding on some exterior part of your ship?
be a gentleman and let them in :)

**Comment by jafdy** [comment]
I was going with they where standing around in the hold. Rounding to the nearest ton they would take up 0 tons of cargo space.

**Comment by endless-sky** [comment]
Fixed in 0e6b96f.
