### ISSUE TITLE
Selecting ships about to land causes them to land/depart loop

### ISSUE THREAD

**Issue by kitsunemochi** [endless-sky/endless-sky#1420]
Sometimes if you select a ship and then it tries to land on a planet, it will do the landing and departing animation in a loop, fairly rapidly, like they're bouncing on the planet.  Stops after you land or leave the system and return.  Happens in 0.9.2.r129
Can't quite get it to duplicate every time but some things to narrow it down;  it doesn't happen to your fleet
and sometimes happens after boarding to repair or refuel.  It's like it only happens if the planet it's trying to land on isn't its final destination.

**Comment by kitsunemochi** [comment]
this is much more rare than i thought to begin with, saw it three times in one system but haven't seen it since.  i think what was happening is sometimes they don't have enough fuel to jump away, but they're trying to anyway, then landing to refuel but not staying long enough to get it done, repeatedly.

**Comment by jafdy** [comment]
This is the first time someone has found a possible cause (as opposed to hypothesized cause). If you can find a set of steps that will always reproduce it you may help solve a longer standing bug.

**Comment by KiLEdEnNis** [comment]
I'll try to look if it happens to me as well

**Comment by kitsunemochi** [comment]
looks like [8fc5c5f](https://github.com/endless-sky/endless-sky/commit/8fc5c5faeafe94b631eff5820e57d57de0d13aa3) fixed this
