### ISSUE TITLE
semantic issue "AddZone" in Panel.cpp (XCode) [bug]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1423]
even after adding Minable and Rectangle classes, XCode reports `No matching member function for call to 'AddZone'` and fails to build.

and more depth (though i don't know what any of it means):

`~/endless-sky/source/Panel.cpp:81:13: Candidate function not viable: no known conversion from '__bind<bool (Panel::*)(int, unsigned short, const Command &), Panel *, int &, int, Command>' to 'const function<void ()>' for 2nd argument`

`~/endless-sky/source/Panel.cpp:90:13: Candidate function not viable: no known conversion from '__bind<bool (Panel::*)(int, unsigned short, const Command &), Panel *, int &, int, Command>' to 'SDL_Keycode' (aka 'int') for 2nd argument`

**Comment by endless-sky** [comment]
Fixed in 382bd3b (along with adding the missing files to the XCode project).
