### ISSUE TITLE
[question] ship creating

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1425]
for my project I've been trying to recreate a ship (from a game that quit 2013), for that I've been teaching myself Blender in the past 4 days (adding more details than I should, for fun and to learn)
I know how to get the good top-down view but once I'm done (nearly done) what do I have to do exactly (coloring etc.) to get it to GIMP for post-processing? (I've read https://github.com/endless-sky/endless-sky/wiki/CreatingShips etc. but I'm missing the steps as it's the first time ever)
![executioner nearly done](https://cloud.githubusercontent.com/assets/10348657/17589965/efed6296-5fd7-11e6-9813-812be76ff1d0.jpg)
here is what I have (need to do mid engine, bridge & gun/turrets)
can someone provide a bit of help on what steps to take after you finish the 3D model? and maybe implement it in the wiki?

**Comment by KiLEdEnNis** [comment]
side note, I had 0 Blender experience before this (been using a text file to help), if I learn the rest I can maybe become ship designer (project will create 7 new ships if it goes well, and if it goes really well I'll do the full plan and att a total of 21 ships, divided in 3 styles of 7 ships)

**Comment by endless-sky** [comment]
First, make sure you've got "sun" illumination with an angle matching this
template file (if you didn't create the ship using the template), and an
orthographic camera also matching the template (but with its field of view
set to whatever it needs to be to contain the whole ship):

https://drive.google.com/open?id=0B9aK8dG39P29OUJ3ME5pdUNPTmc

You'll also have to set the "sky" to transparent, and you may also want to
turn on screen-space ambient occlusion for a less artificial-looking
render. (Again, if you started with the template, all this should already
be set up.) Then, render the ship in Blender, save the rendered image, and
open it in GIMP.

From there, you can look at some of the other GIMP files to see what sort
of post-processing is being applied to the ships. Usually it involves a
"multiply" layer for manually adding extra shadows, and one or more
textures using "soft light" or "overlay" blending mode:

https://drive.google.com/open?id=0B9aK8dG39P29fmhaWE04RUdtSTM3ZElUeUhCT0xOSm5tajM5OVduaHFHSGZ3Z2ZxN0x2WnM

**Comment by KiLEdEnNis** [comment]
thanks a lot for the help, as I said I taught myself Blender when starting so I didn't use the template, transparent sky etc. yet, although I'll finish the ship and then take my time to follow your tips
also, do you like it? I had 0 experience when starting (although translating, scaling, 3D stuff etc. is my best math subject) and I'm proud of it :D

**Comment by KiLEdEnNis** [comment]
also I noticed a difference between the blends and my blend
the top right only shows "Cube.001", while the other blends have a "Cube", "Sphere" etc. for every single object, is there a way to split my ship's components into all those cubes etc. for recoloring?

**Comment by endless-sky** [comment]
In Blender, if you're in "Edit mode" when you add an object it gets
included inside the current object you are editing. If you're in "object
mode" it gets added as a separate object.

I'm sure there's some way to split a mesh into separate objects, but I'm
not sure what it is. Blender has the single most obtuse user interface of
any program that I use on a regular basis...

**Comment by KiLEdEnNis** [comment]
I noticed that first part, and the user interface is bad indeed, but I found a way to draw on the ship, which I will do when I am done
but if I get it to GIMP, do I have to screenshot it and paste it?

**Comment by LocalGod79** [comment]
my workaround for separating joined objects has been to duplicate (the joined objects) and delete (mutually exclusive components)

as a side note; would you mind closing issues that you created that have been "resolved"?

this is not the Steam Forum/Google Group: either of which are a far more suitable location for this and other questions you've been asking.

**Comment by KiLEdEnNis** [comment]
I'll close the resolved issues, about this one; wasn't sure to open it at all because github isn't that suitable, I'll move this on the google group

**Comment by endless-sky** [comment]
Once you've rendered the image, there's a "Save as image" option in the
Image menu, which is in the toolbar *below* the view of the rendering.

**Comment by KiLEdEnNis** [comment]
alright, thank you, if I have more questions I'll make a thread on the google group
@LocalGod79 closed all issues I made that are solved etc.
