### ISSUE TITLE
[enhancement/mechanics/question] Dumping outfits

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1427]
Apologies in advance, I should be in bed.

Dumping outfits (other than minables) yields nothing but a lost outfit. If I'm not mistaken, it should yield a flotsam box and be able to be picked up by other ships? I think I saw Michael say something about you being able to do that.

**Comment by MarcelineVQ** [comment]
After retesting just now in case something changed: Dumping a lone outfit, a specific number of an outfit, or all outfits all create floatsam. Do you happen to know what you dumped specifically?

**Comment by KiLEdEnNis** [comment]
maybe tiny outfits (supercapacitors) have that?

**Comment by toilethinges** [comment]
I was trying to dump Planetary Thrusters and Steering, I think some Jump Drives, (I don't remember if I did) some Electronics cargo, and some Clothing cargo. I know for sure that the Clothing did create a box and was picked up by my escorts.

It was on my compiled branch with the latest flotsam-related commits.

**Comment by toilethinges** [comment]
Yep. I recompiled with fresh data and images folders and all that, and it was apparently just me failing to compile correctly, or something of that sort. Sorry for wasting your time, have a good day[s].
