### ISSUE TITLE
"Suicidal" fleet personality

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1428]
Currently, the AI will not fire a weapon if it will end up hurting itself in the process, usually through blast radii. The suicidal personality would override this, and maybe also cause the ships in the fleet to try and get as close as possible to their target, opening themselves to more fire.

**Comment by Amazinite** [comment]
A less "triggering" word could probably be "reckless."

**Comment by KiLEdEnNis** [comment]
suicidal reminds me of an idea I had; small ships/drones that can self-destruct for a big AoE damage (similar to a ship with a weapon with a huge radius, hit force & damage), but suicide bomb drones should get a special unremovable weapon that blows themself up but does huge damage
that would be cool for suicidal, but reckless is also a good idea

**Comment by endless-sky** [comment]
It's relatively easy right now to trick the AI into thinking it won't damage itself with a weapon, by putting the blast radius in a submunition rather than the main projectile.

**Comment by petervdmeer** [comment]
I feel multiple personalities could be appropriate, for example:
- `"kamikaze"` for ships that damage themselves as long as they can do more damage to an enemy.
- `"suicidal"` for ships that fire weapons that damage themselves anytime.
- `"reckless"` for ships that take large risks.
- `"take with me"` for ships that try to take enemies with them when they are about to die.

**Comment by Zitchas** [comment]
I'd suggest "careless" instead of "suicidal", but otherwise, yeah, I like the sounds of those.

**Comment by tehhowch** [comment]
> I feel multiple personalities could be appropriate, for example:
> - `"kamikaze"` for ships that damage themselves as long as they can do more damage to an enemy.
> - `"suicidal"` for ships that fire weapons that damage themselves anytime.
> - `"reckless"` for ships that take large risks.
> - `"take with me"` for ships that try to take enemies with them when they are about to die.

I think "kamikaze" better suits the "take with me" behavior, while something relating to attrition suits the first behavior.

**Comment by gunqqer** [comment]
I think `kamikaze` is for when they'll just do as much damage as possible if it does more to the enemy no matter their own health, but `take with me` will only do that if they are at low health. So like, if they're about to die they will launch a nuke at point blank range, but at full health they won't.

**Comment by Amazinite** [comment]
#6084 takes the route of creating a special weapon attribute that allows a weapon to be fired by a ship even if the firing hull could disable itself, while this issue suggests making use of a ship personality. I'll note that while a ship personality might be more appropriate (as ship personalities are typically what defines the behavior of a ship, and "fire even if you hurt yourself" is a behavioral trait), it does bar the player's escorts from expressing this behavior.

**Comment by petervdmeer** [comment]
The "fire even if you hurt yourself" behavior is something which I would like to be able set for some of my escorts
I feel that a player should not be able to set all possible behaviors for escorts (for example mining as suggested in https://github.com/endless-sky/endless-sky/issues/5720 should imho not be available to players to set), but this behavior sounds one which I would like to be settable for players.

**Comment by petervdmeer** [comment]
Until we have the option to let players set some escort behaviors I would use the safe route of having escorts protect themselves by default.

**Comment by Hurleveur** [comment]
The ramming personality does this, I think, but not sure.
At least the recent AI changes made it so that if most of the dps comes from this dangerous weapon, they shoot anyway.
