### ISSUE TITLE
mission "Intro [1 Freighter]" refers to spaceport on wrong planet

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#143]
This freighter intro mission:
https://github.com/endless-sky/endless-sky/blob/master/data/intro%20missions.txt#L187

In the text, it comes out as "The spaceport on Heartland is small enough...", but the planet the player is on at that point is New Greenland in the Arcturus system.  Heartland is the target planet in the system the player needs to travel to to complete the mission.

**Comment by endless-sky** [comment]
Fixed in db8f6c4. Thanks!
