### ISSUE TITLE
button to unpark flagship

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1432]
![image](https://cloud.githubusercontent.com/assets/15716454/17625593/6f9fe120-60a1-11e6-8a73-f31342ba41a2.png)

**Comment by KiLEdEnNis** [comment]
ooh, naugty cheater o:

**Comment by endless-sky** [comment]
I can't seem to duplicate this. Could you describe the steps you took, and what version of the game you're running? (This might have been fixed with my recent changes to the Info Panel UI.)

**Comment by jafdy** [comment]
@KiLEdEnNis This is a test file, it has all sorts of thing it shouldn't. 

@endless-sky Most resent steam version. It just came up, It is still coming up though.

**Comment by warp-core** [comment]
I have seen this happen on 0.9.3 from Steam:
If the ship in the second slot is parked and I move the flagship into the second slot, the parked ship that has just been moved to the first slot is selected, I can click the unpark button at the bottom which unparks it and then the unpark button is still there.
I'm not sure if there are other ways that this can happen as well.

**Comment by KiLEdEnNis** [comment]
@jafdy I have a test file too (carrier w/ even antimatter cannons) lol

does that mean 0.9.3 is on Steam?

**Comment by warp-core** [comment]
No, I messed up, I meant 0.9.2... I'm too hyped...

**Comment by KiLEdEnNis** [comment]
I really want 0.9.3, but idk if there's a general date for it
and on the bad side; I need to transfer parts of my project which are in the default files to the new ones (like map; have to search and copy-paste every system & planet)

**Comment by jafdy** [comment]
@KiLEdEnNis there is a thing called a plugin folder.

**Comment by endless-sky** [comment]
@KiLEdEnNis, you can just run a diff tool on the stock file and your modified file to extract just the lines that you modified. For example, on OS X or Linux you would just do something like:

`$ diff original_map.txt my_map.txt | grep '^>' | cut -b 3- > my_changes.txt`

On Windows the WinMerge program would let you do something similar.

**Comment by KiLEdEnNis** [comment]
I'll check WinMerge out, thanks

**Comment by Amazinite** [comment]
@MarcelineVQ fixed this a while back.
