### ISSUE TITLE
option to buy missiles that are not in stock

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1433]
Tried to buy some javelins at dancer, got the reload ammo pop-up, clicked OK, checked if missiles where reloaded, found them out of stock.
![image](https://cloud.githubusercontent.com/assets/15716454/17627515/6e270b90-60a9-11e6-85ca-83206ba81f94.png)

**Comment by endless-sky** [comment]
The dialog is shown if *any* of your ammunition can be reloaded. So, for example, if you have a Javelin pod and a missile launcher, and only Javelins are available, it will show the dialog but only the Javelins will be reloaded.

**Comment by warp-core** [comment]
I have seen this dialog appear whenever any ammunition can be reloaded regardless of whether the ammunition is available in the outfitter.
![capture](https://cloud.githubusercontent.com/assets/20605679/17628503/71d89386-60ad-11e6-9f99-7ede2ed51bbb.PNG)

**Comment by jafdy** [comment]
As @warp-core said.
Also I only have javelin pods (and some plasma turrets and heavy AMS).

**Comment by endless-sky** [comment]
Is this with 0.9.2, or the latest code? Is it possibly the same bug that was fixed in 284a747?

**Comment by warp-core** [comment]
0.9.2...

**Comment by jafdy** [comment]
yes 0.9.2. That probably fixed it.
Closing until 0.9.3 (if still occurring)

**Comment by Amazinite** [comment]
@jafdy I brought this issue up as well. It's fixed in the current code.
