### ISSUE TITLE
"Installable" in outfitters

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1434]
Have `"installable" -1` show as a message in the outfitter similar to `"unplunderable" 1`.
"This outfit can not be installed."

**Comment by Sinsling** [comment]
0.9.3...

**Comment by Amazinite** [comment]
What about it?

**Comment by Sinsling** [comment]
Derp. Forgot you probably are already playing it. It wasn't already generating a pop-up?

**Comment by Amazinite** [comment]
Nope. Check #1450. I have a screenshot showing how `"installable" -1` shows in the game as of the most recent code.
Also, installable is already in the game as of v0.9.0, it's only just not getting used in v0.9.3.

**Comment by endless-sky** [comment]
Fixed in 6ee3fea.
