### ISSUE TITLE
interface.txt in the code files messes up interface

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1435]
so I used WinMerge (MZ told me about it) to "update" my game with the Code files, and if I update the interface.txt the home menu, in-game menu etc. doesn't show, so all ui images don't show
for now I'll keep my old interface.txt, but I updated literally everything else so I think the problem is in the interface.txt itself

**Comment by toilethinges** [comment]
I can't really tell what you're saying. You compiled the source, and the new inteface.txt isn't working? I recompiled today and it worked fine.

**Comment by Amazinite** [comment]
The interface.txt file doesn't need any updating anyways, so not sure what you're trying to do.

**Comment by Amazinite** [comment]
That's because you're still using the v0.9.2 version of the game. The changes to the interface are for v0.9.3, which you are not using, therefore causing this bug where nothing is working properly.

**Comment by Bladewood** [comment]
difference is that the former is free while the latter is wtf I don't even have a phone :|

**Comment by KiLEdEnNis** [comment]
@toilethinges  I didn't use WinMerge to edit, I replaced the entire file
@Amazinite how does that work though, I changed every single file in steamapps/common/Endless Sky, are there more files somewhere else?

**Comment by Amazinite** [comment]
@KiLEdEnNis the actual .exe file. You've got v0.9.2. The interface update is for v0.9.3. You'd need a v0.9.3 .exe for the interface to work with the updated interface.txt file.

**Comment by KiLEdEnNis** [comment]
ah ok, ty
