### ISSUE TITLE
Allow variable fuel efficiency

### ISSUE THREAD

**Issue by Isaacssv552** [endless-sky/endless-sky#1436]
Fuel efficiency is currently constant for the various types of movement. I would like a "jumpcost" tag that allows outfits to directly set the cost of a jump, allowing for both more and less effective versions of the hyper/jump drive.

**Comment by Bladewood** [comment]
There is an unlisted `jump fuel` attribute, or at least that's what other people have been talking about.

**Comment by KiLEdEnNis** [comment]
worst case; you have to create a new hyperdrive

**Comment by Isaacssv552** [comment]
I've looked at the code and I'm fairly sure fuel cost is based solely on drive type, which is either 100, 150, or 200 and decides both whether you have a hyper, scram, or jump drive and the fuel cost.

**Comment by Wrzlprnft** [comment]
The range is based on drive type, but i'd suggest you try the jump fuel line

**Comment by Isaacssv552** [comment]
I tried "jump fuel" 100. It shows up in the outfitter, but when using the drive the cost is still 200 fuel.

**Comment by hdhdhd95** [comment]
I looked it up in the code that line does nothing I modified ship.cpp in the int Ship::HyperspaceType() const method and was able to make it so that you could modify the fuel consumption in a data file.

**Comment by hdhdhd95** [comment]
`int Ship::HyperspaceType() const
{
	if(IsDisabled())
		return 0;
	const System *destination = GetTargetSystem();
	if(!destination)
		return 0;
	
	// Check what equipment this ship has.
	bool hasHyperdrive = attributes.Get("hyperdrive");
	bool hasScramDrive = attributes.Get("scram drive");
	bool hasJumpDrive = attributes.Get("jump drive");
	
	double hasHyperdriveFuel = attributes.Get("hyperdrive fuel");
	double hasScramDriveFuel = attributes.Get("scram drive fuel");
	double hasJumpDriveFuel = attributes.Get("jump drive fuel");
	
	// Figure out what sort of jump we're making. 100 = normal hyperspace,
	// 150 = scram drive, 200 = jump drive.
	if(hasHyperdrive || hasScramDrive)
		for(const System *link : currentSystem->Links())
			if(link == destination)
				return hasScramDrive ?  (hasScramDriveFuel ? hasScramDriveFuel: 150 ): (hasHyperdriveFuel ? hasHyperdriveFuel: 100 );
	
	if(hasJumpDrive)
		for(const System *link : currentSystem->Neighbors())
			if(link == destination)
				return hasJumpDriveFuel ? hasJumpDriveFuel: 200 ;
	
	return 0;
}`

**Comment by Sinsling** [comment]
Ask for a pull request? I am pretty sure fuel cost was intended to be definable attribute.

**Comment by hdhdhd95** [comment]
Do you think he will accept it?

**Comment by hdhdhd95** [comment]
I made the pull request.

**Comment by Amazinite** [comment]
ebb46d8
