### ISSUE TITLE
collision issues with recent commit, e4bdde9

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1439]
commit e4bdde9 has introduced oddities with collision:

asteroids no longer block the `hit force` of a weapon, a Banisher can be visibly blocked by a normal asteroid and still push your ship, I didn't test destructibles
enemies which explode near you no longer impart damage or hit force

I thought they were separate issues at first but a bisect narrowed them both down to this.

**Comment by endless-sky** [comment]
41f02dc should fix that.

**Comment by MarcelineVQ** [comment]
Confirmed that fixes the banisher issue.

Ship death explosions still aren't hitting other ships though. It doesn't seem to make a difference whether the system has asteroids/mineables in it or not.

**Comment by endless-sky** [comment]
b8af410 should fix the ship explosions.

**Comment by MarcelineVQ** [comment]
Yep all good now
