### ISSUE TITLE
No UI to see/edit key for "scan outfit"

### ISSUE THREAD

**Issue by BrandonY** [endless-sky/endless-sky#144]
The preferences pane shows the key for most commands and allows them to be edited, but there's nothing for "scan target ship outfit".

(It's "S", by the way, for anyone who also couldn't figure it out)

**Comment by endless-sky** [comment]
It's listed, but under the "menus" section because, like the info dialog, etc., scanning a ship brings up a dialog. (I wasn't really sure what the best section to put it in was, so I know that may be confusing.)
