### ISSUE TITLE
railgun has too much ammo capacity(?)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1440]
so I looked at the railgun;
outfit space; 7
mass; 4
1 railgun slug mass; 0,2, 15 railgun slugs in the railgun would be 7 mass to pair w/ the outfit space, BUT it can carry 150 railgun slugs, and they don't look that small
to double check it I looked at the RPS (rounds per second); 0.5, experience taught me that no ammo-using secondary weapon can fire 5 minutes non-stop (30 seconds isn't much but it's for drones, and they don't last long)

**Comment by Amazinite** [comment]
Rail slug mass is .02 not .2.

**Comment by KiLEdEnNis** [comment]
@Amazinite I blame bad glasses :(
but those things don't look small at all

**Comment by LocalGod79** [comment]
i had to balance appearance - i tried a smaller projectile sprite, but it lost some of the desired visual effect.

further to your point: the Gatling bullets are so "small", you shouldn't be able to see them at all, and the tracers should be single pixels but...

at the end of the day it's a video game, and in some cases it's more important to have "arcady" visible rail-slugs than a few indiscernable pixels that are perhaps more realistic...

**Comment by KiLEdEnNis** [comment]
@LocalGod79 that seems logical, but it looked as big as actual rockets :P

**Comment by jafdy** [comment]
It's zoomed in. Like the shipyard.

**Comment by KiLEdEnNis** [comment]
yes I know
