### ISSUE TITLE
Too high combat rating makes missions impossible

### ISSUE THREAD

**Issue by kitsunemochi** [endless-sky/endless-sky#1443]
If you don't do the free worlds missions at the beginning of a playthrough, and make your money capturing ships and hunting pirates and get a high combat rating, the spawn rates in some of the missions become nearly insurmountable.  
Became really noticeable during the mission "Northern Expansion" where you're given a small fleet, a few interceptors and two falcons.  Warped into Alpha Arae on the way to Seginus and there were a couple cruisers and gunboats, ok, no problem.  As the fight started though, more kept warping in, and I lost count at over 50 carriers with innumerable cruisers, frigates, gunboats, and rainmakers.  As my ship died trying to run away, the combat drones made a solid circle around it, the lasers making it look like a ferris wheel.  So many missiles, like sand at the beach.  Legit it was like trying to demand tribute at Earth.
This was with a combat rating of only 10... 
It just doesn't make sense for the game to swamp you with CPU killing mega fleets just because you like to grind pirates for cash.
I suppose one could press pause on the missions and go build your own huge fleet but it seems silly to be handed two falcons and a few furys and be told "Go clear these ppl out."

**Comment by KiLEdEnNis** [comment]
if you hijack that much you should have a small battle fleet though
and the only way how I get money is hijacking as well, to me it's fine

**Comment by MarcelineVQ** [comment]
I'm not aware of combat rating effecting anything other than mission conditions (like whether you'll be offered a mission) and whether a planet responds to a tribute demand. Are you sure combat rating is responsible for this?
The game compares fleet strengths (based on ship cost) for whether it'll send in more units into a system when it has the opportunity to do so. If you lasted long enough to see 50 carriers, especially at once, you would have had a very impressive fleet since they're powerful vehicles.

**Comment by endless-sky** [comment]
Those ships aren't mission-related - you just picked a fight with the Republic in a heavily trafficked system, and that's the result.

**Comment by kitsunemochi** [comment]
> should have a fleet
i don't like keeping up with them, i just ride around in a shield beetle killing pirates all day
> very impressive fleet
it does have quarg shields which is why i lasted that long... far longer than the pitiful FW fleet

MZ is right though, i replayed and just warped through to the mission systems leaving everyone behind and things went fine.
Just find myself always doing that, warping ahead of all the fleets i'm in charge of, killing everything at the destination, and waiting on them.  Otherwise they're toast 100%
