### ISSUE TITLE
Ships that are destroyed while leaving the planet do not fully "resize" themselves

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1444]
I think I also saw fully-sized ship explosions coming from those ships, but I can't remember.

**Comment by KiLEdEnNis** [comment]
that isn't really a bug right? technically they get destroyed in orbit

**Comment by Amazinite** [comment]
Yeah, I've seen this when demanding tribute before.
Ships get damaged while their sprite is launching and increasing in size, and if they die then they get stuck on the frame they were at but have a full sized explosion.

**Comment by KiLEdEnNis** [comment]
when I ask tribute half the ships die before being fully sized (Syndicate has bad pleb ships)
I don't think it's an actual bug though, and even then; how to fix it

**Comment by Alkallid** [comment]
The hitboxes stay the same though, and your many lasers end up being blocked by empty space.

**Comment by KiLEdEnNis** [comment]
didn't notice that, but as soon as a ship takes off it can be attacked, and making hitboxes expand with them (or if they barely left orbit they "land", a.k.a. crash down) will add more complexity

**Comment by endless-sky** [comment]
This is fixed in 0.9.3 because ships can no longer be hit until they're done taking off.
