### ISSUE TITLE
use Alpha government for FW Alphas

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1447]
Now we have a government for them it would make some sense to use it here as well for the ships and the very temporary planetary government change.

**Comment by KiLEdEnNis** [comment]
that depends, they are Alphas but I would figure they'd disguise themselves as pirates

**Comment by Bladewood** [comment]
You never know.
Some people are just that dedicated to protecting their ways.
The Syndicate extremist ships may very well just be the extremists, no alphas on board.

**Comment by KiLEdEnNis** [comment]
even if they are Alphas, it would make sense if they "disguised" their ships using other names, swizzle and government name

**Comment by jafdy** [comment]
The extremists should be left alone. It's more that I know that they are Alphas so it would make sense to label them as such. It's such a minor thing I wouldn't have bothered if there wasn't a government for it already. 

Doing this could also generate the feeling that the Alphas are a major threat rather than a small side track from fighting the Republic

**Comment by Sinsling** [comment]
Keep in mind the Alphas have very limited numbers. They probably paid a bunch of pirates to fight for them.

**Comment by jafdy** [comment]
Yes and I rather expect there is a rather limited number of people who own part of the Syndicate, and yet they have hundreds of ships who are piloted by people they hired (indirectly) fighting for them. 

The point is this is a fleet effectively owned by the Alphas and a planet effectively controlled by the Alphas.

**Comment by endless-sky** [comment]
The Alphas exist as a bunch of independent enclaves, because if you put too many Alphas in a room together they'll eventually start killing each other. :) So it makes sense to give the extremists a different government name than other Alpha groups.
