### ISSUE TITLE
[question] max ship size?

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1448]
after https://github.com/endless-sky/endless-sky/issues/1425 I used the info to finish the general ship design (need to add details, and do GIMP post-processing), although I made the ship very large
the idea is that it IS by far the strongest ship in the project I'm making (about Quarg tier)
![executioner size](https://cloud.githubusercontent.com/assets/10348657/17650177/5c51d914-6247-11e6-8ddd-360f6da87b0d.png)
it is extremely large though, and thus ridiculously slow

so what I'm basically asking is; do I need to make it smaller?

**Comment by Amazinite** [comment]
I feel like this kind of question is better for the Steam or Google forums. GitHub isn't for getting help balancing your mod.

**Comment by KiLEdEnNis** [comment]
as for the stats (I'm gonna change some things a bit when I made my own outfits):
ship "Executioner"
	sprite "ship/regula executioner"
	"never disabled"
	attributes
		category "Heavy Warship"
		cost 300000000
		bunks 150
		"cargo space" 823
		drag 100
		"engine capacity" 260
		"fuel capacity" 900
		"gun ports" 7
		"heat dissipation" 1
		hull 900000
		mass 8000
		"outfit space" 1400
		"required crew" 80
		shields 90000
		"turret mounts" 11
		"weapon capacity" 740
		weapon
			"blast radius" 1000
			"shield damage" 50000
			"hull damage" 50000
			"hit force" 10000
	engine 0 319
	engine -137 314
	engine 137 314
	gun 0 -46
	gun -60 -358
	gun 60 -358
	gun -98 -103
	gun 98 -103
	gun -172 29
	gun 172 29
	turret -60 -185
	turret 60 -185
	turret -60 -126
	turret 60 -126
	turret -144 43
	turret 144 43
	turret -144 107
	turret 144 107
	turret -39 226
	turret 39 226
	turret 0 76
	explode "big explosion" 100
	explode "huge explosion" 50
	explode "nuke explosion" 10
	"final explode" "final explosion large" 1

if it's fine like that but OP for a player, I can make that ship unachievable (it can't be disabled anyway, but in the story maybe I'd sell the warships)

**Comment by KiLEdEnNis** [comment]
@Amazinite well, it's mostly just about if it's too large
(also tried to put the stats but yea, balancing is my own job)

**Comment by Amazinite** [comment]
I don't really see how that's a github issue then. If it isn't taking up half the screen then it's good. I don't think there's an actual "maximum size" that MZ has set for what should and should not exist. Plus, it's your mod, so you can do whatever you want with it.

**Comment by KiLEdEnNis** [comment]
alright, thanks

**Comment by Amazinite** [comment]
:ok_hand:

**Comment by Alkallid** [comment]
Nice work though.

**Comment by KiLEdEnNis** [comment]
@Alkallid thanks :D had 0 Blender experience before it but I was tryharding and I'm proud of it (3D, figures, 3D graphs, drawing, perspective etc. was my best math subject though)
I'll add the last details and then post-process it in Blender
also thanks to everyone who helped me (most importantly MZ for giving instructions on what to do) :3
