### ISSUE TITLE
Strange glitch with keyboard jump selection

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1449]
https://github.com/Amazinite/Enigma-Corp/issues/15
https://github.com/Amazinite/Enigma-Corp/pull/18

There was a system in my mod located at `pos -757 -411.5`. For some reason when trying to select where you jump with your keyboard, certain systems around this system just would not select. Strangely, shifting the position to `pos -757 -412` fixed this, and now all the systems around this system can be selected with the keyboard normally.

Edit: The two systems that the glitched system were having trouble selecting were linked to this system, so it isn't that the position change just moved it to the right spot to reach via jump drive.

**Comment by KevinKorzekwa** [comment]
Also relevant, selecting the systems with the mouse allowed jumps to happen, it is only the keyboard shortcut (tab and j) that was affected by the decimal.

**Comment by KiLEdEnNis** [comment]
the editor doesn't do decimals for coordinates does it?

**Comment by Amazinite** [comment]
It does.

**Comment by Amazinite** [comment]
Testing some vanilla systems with decimal positions didn't turn up the same glitch, so I don't know exactly what it is that caused it.

**Comment by KiLEdEnNis** [comment]
I never get decimals though, maybe an error with your editor?

**Comment by KiLEdEnNis** [comment]
I just looked in my map.txt and (I never knew) it DOES go up to 3 decimals, but I have no issues with it

**Comment by endless-sky** [comment]
Is it possible that you had two systems on exactly the same vector relative to the system you are jumping from? The way the toggle works is to always go through the systems in clockwise order, but if two systems were at the exact same clock direction one of them would get skipped.

**Comment by Amazinite** [comment]
No, that wasn't the case, but I can't seem to find this occurring anywhere else. It may have been one of those strange one-off glitches that will almost never happen again. I'll keep my eye out for it to see if it happens anywhere in vanilla, but in the meantime I'll leave this closed.

**Comment by KevinKorzekwa** [comment]
I went ahead and made a tarball my ~/.local/endless-sky directory and the directory with the game's source for the situation that replicates this, in case it is needed in the future.

@endless-sky The system that gets skipped is 180° from the one that is selected first, is that what you mean by 'exact same clock direction'?  

`  /
 . 
/`

**Comment by Amazinite** [comment]
Yeah, that's what it was. Say one system was at 1 o'clock, the other was at exactly 7 o'clock.

**Comment by KiLEdEnNis** [comment]
so this would happen if there are 3 systems in 1 straight line? seems weird

**Comment by endless-sky** [comment]
It's surprisingly hard to get sorting by angle right (mostly because of collinear points), but commit 5d8ab33 should fix this.
