### ISSUE TITLE
Can't use thruster

### ISSUE THREAD

**Issue by constantm** [endless-sky/endless-sky#145]
Such an awesome game! Have spent the last few hours playing. However, after I reloaded a saved game, I'm no longer able to use the thrusters to go forward. Just nothing happens. I could hyperspace once after that happened, but now the ship turns to the correct direction and nothing happens. HALP

**Comment by endless-sky** [comment]
Check in the player info panel (press 'i') to see if your ship still has thrusters installed. There's an intermittent file corruption bug that can cause you to lose outfits, which I still have not tracked down.

**Comment by constantm** [comment]
Ah yes, that is exactly what it was. Thanks! :)

**Comment by constantm** [comment]
Urgh. I'm at a planet that doesn't have any outfitters. Is there any way to use a cheat of something to get a basic thruster again, or at least get to a planet that has an outfitter?

**Comment by akien-mga** [comment]
You can try to edit your save game to add thrusters back to your ship (check an older snapshot that had thrusters, or start a new game and save it, to see what the syntax should be like).

**Comment by constantm** [comment]
Ah awesome thanks, that worked!
