### ISSUE TITLE
dumping cargo can bypass creating flotsam

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1453]
Dumping `Ship::Jettison()` cargo which doesn't fill an entire flotsam 'box' doesn't create one, which results in the item ceasing to exist. For example a flotsam box can hold 25 units of something with 0.2 mass, dumping 24 sidewinders won't create a flotsam box but dumping 25 will. Dumping 30 will only create one box so 5 disappear.

Tangentially I'm not sure box size should be `static`, it reported a box size of 25 for torpedos but the actual box size for torpedos should be 12 since they're 0.4 mass so it used the value set from dumping the sidewinders first. Though the number of boxes made isn't exactly a big deal as long as it's nonzero.

**Comment by KiLEdEnNis** [comment]
making it that an extra box appears for 1 missile may be some unnecessary work but it would make it more realistic
also if you dump for example an armageddon core, it should be in a huge box, not 1 or more small ones

**Comment by LocalGod79** [comment]
@KiLEdEnNis the capability has recently been added for outfits to have their own flotsam sprites, which i image will address both the expressed issues when said sprites are created...
