### ISSUE TITLE
Question: Do `on decline` and `on accept` work for `flee` and `launch`?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1458]
Because right now you can not set something to occur `on flee` or `on launch`. And if the answer is yes, that might be something to document.

**Comment by Bladewood** [comment]
According to the files, it works.
`mission "FW Katya 1C"`
If you choose to shut the hatch, you launch off into space, and then the `on accept` line triggers, causing the Republic to become very mad.

**Comment by MarcelineVQ** [comment]
The current `on` options are: complete, offer, accept, decline, fail, defer, visit, stopover

**Comment by LocalGod79** [comment]
also `on enter`

for `on flee` you would use `on decline`, and `on launch`, `on accept`

**Comment by KiLEdEnNis** [comment]
@Bladewood if you launch in that mission you have Rainmakers and Gunboats stalking you, even if you kill pirates to let the Republic like you again, those specific ("nemesis") ships keep stalking, I had to manually delete them in my save

**Comment by Wrzlprnft** [comment]
@KiLEdEnNis
I am sorry, but please don't post comments like that, if they do not contribute anything to the issue

**Comment by KiLEdEnNis** [comment]
@Wrzlprnft sorry, didn't pay much attention because I'm tired
next time I'll try to read better

**Comment by endless-sky** [comment]
* `launch` = `take off` + `accept`
* `flee` = `take off` + `decline`
* `depart` = `take off` + `defer`

I suppose I should update the wiki page on conversations accordingly.

**Comment by endless-sky** [comment]
Actually, it looks like the [wiki](https://github.com/endless-sky/endless-sky/wiki/WritingConversations#endpoints-and-goto) was already somewhat clear on that.

**Comment by Amazinite** [comment]
I was looking more at [this](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#triggers) than that.

**Comment by LocalGod79** [comment]
but the point is that there is already a "trigger" for each of the `launch | flee | depart` options, being `on accept | flee | defer`
