### ISSUE TITLE
Game not running at all

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1459]
http://steamcommunity.com/app/404410/discussions/1/361798516936208895/?tscn=1471421783

**Comment by Wrzlprnft** [comment]
Maybe something with the resolution? He/she/it should check the preference.txt if existing

**Comment by jafdy** [comment]
It?

It might be easier for you to head over but I'll suggest it.

**Comment by endless-sky** [comment]
The problem appears to have fixed itself, without any data on what might have caused it, so I'm closing this.
