### ISSUE TITLE
Suggestion: Politic map and visited/not visited map

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1467]
In the map view, beside Shipyards, Outfitters, Missions and Ports, I'd like to see a Politics map where you could see colour-coded the different factions and nations. Free Worlds, Syndicate, Hai, Unfettered Hai, Quarg, Pirates, etc.
You can see a small politic map when pressing the jump key, so I guess that part of the necessary code is already written.

A sugestion to represent systems with settlements or planets belonging to different factions like Tarazed with 2 human and 1 quarg settlements is to use half-circles. Half a circle of Republic colour, the other half circle of Quarg colour. I think it is an elegant solution. It is appropriate too, for example, in the ports and missions map  to represent pirate worlds with two planets where you have dominated only one of them.

The other map view to add would just show "visited", "partially visited", "unexplored" and "not yet visited". "Partially visited" is for systems with 2 or more settlements where you have visited one or two of them but not all. "Not yet visited" is for systems you have traversed without landing or systems that appear in your map only because you have purchased the local map in an outfitter.

**Comment by KiLEdEnNis** [comment]
the politics map; press M (map), top left you see your current sector and under that the name of the government that owns it, click the government to see the different colors (some may not fit that much, like Syndicate, but it works)

**Comment by retrue** [comment]
Thanks, I saw the politics map now. There is room for improvement, but it works. And the visited/not yet visited/some planets map is there too, just selecting the visited text in the information about a world in the top left corner.

**Comment by KiLEdEnNis** [comment]
I didn't know exactly what you meant by a "visited map", but you can indeed see it in the top left per sector, although I never use the visited part, so I'm not experienced with it
glad I could help, you can leave the issue open because of the "half-circle" idea, like dominated sectors (and maybe co-owned sectors)

**Comment by Bladewood** [comment]
For the domination issue, Michael already discussed this in a post, though I cannot remember where said post is or what his opinion on the issue was.

**Comment by Exomancer** [comment]
Wow ...
retrue has a point.  There is no way I would have know the map did that except for reading this post.  Making the politics and visited maps obvious would be great.  One other point.  When you click on 'has been visited' the text box describing the planet blocks a large portion of the map and I have not been able to figure out how to turn it off without changing the map type.

**Comment by jafdy** [comment]
@Exomancer If you have a low resolution this will happen a lot. For me the planet description box covers less than an eighth of the map.

**Comment by Bladewood** [comment]
relevant:
http://steamcommunity.com/sharedfiles/filedetails/?id=549291100
