### ISSUE TITLE
having Electron Turrets installed crashes save file/game at FW Southern Recon 1B

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1468]
so I was having fun in a sector (shooting surveillance Navy ships with my FW friends)
the only jumps I made were to a sector next to me and back (3 times), after maybe 15 minutes I landed, the game crashed, and the game now crashes when I launch it (it loads the title screen, but when it should be "done" it crashes)
I have the Steam version, Windows 10 64-bit, and updated my files with the "Code" part on github maybe a week ago

EDIT: after deleting the save file it worked again (I replaced it), so something in the save file may be corrupted
EDIT 2: I put the save file back (not the back-up saves though), opened the save.txt in WordPad, saved it, and the game works again

**Comment by KiLEdEnNis** [comment]
I found out WHAT the problem was; my flagship, I deleted it (and transported another ship to the planet I was on because I only use 1 ship), so basically my flagship caused the crash, but I have no idea what it is, currently trying to find out

**Comment by jafdy** [comment]
Have you tried deleting the electron beam instead?

Also, MZ don't both missions need to have a landing trigger?

**Comment by KiLEdEnNis** [comment]
I have tried only deleting the Electron Beam; still had the error, even deleting all but 1 Turret crashed if I remember

**Comment by endless-sky** [comment]
You're saying you're trying to run the content from Github, with the executable files from Steam? That will certainly cause all sorts of problems, because the content on Github contains things that the 0.9.2 executable will not be able to understand.

If you're trying to run the content from Github, you need to build the executable from the Github source.

**Comment by KiLEdEnNis** [comment]
@endless-sky I tried that, but I couldn't do it
and the game did work fine (unless I used the new interface.txt)
I'll try again to build the executable from github
