### ISSUE TITLE
{Bug}  being taken by enemy causes crash

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#1471]
You may not understand the title.
When you board a ship and fail the enemy ship takes over your ship. 
After this I decided to see what happens to them (I was trying to take Unfettered Hai raider ships attacking the Wanderers, forgot that the Pug T3 ship has zero crew, and tried anyway). The game crashed after that. It may be just the ship, the enemy, idk.

**Comment by MarcelineVQ** [comment]
Could you elaborate about the circumstances? Something seems a bit off about the situation because any ship you pilot will have at least 1 crew because you're piloting it. Additionally the minimum crew for a Pug Arfecta (the T3 Ship) is 36.

**Comment by KevinKorzekwa** [comment]
Did the game continue after your game over, without the "Game Over" message showing?

**Comment by Amazinite** [comment]
#1254

**Comment by MessyMix** [comment]
Maybe he got rid of the Biodefenses, and realized that his 36 crew was no match for the crew on Unfettered ships.

**Comment by gunqqer** [comment]
@MarcelineVQ I boarded a ship, forgot the Arfecta has only 36 crew, said fuck it, everyone die, enemy took the ship, game crashed

**Comment by KiLEdEnNis** [comment]
remind me I ain't serving on his ship

**Comment by Amazinite** [comment]
Again. #1254.

**Comment by gunqqer** [comment]
@KiLEdEnNis Serve on my troop ship, you'll have so many pug and quarg defences.... (Quarg from Korath raiders)

**Comment by endless-sky** [comment]
This ought to be fixed in 0.9.3.
