### ISSUE TITLE
Small bug. The wormhole in Deneb never appears as visited.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1472]
Once the Pug war finishes at the end of the FW campaign, a wormhole appears in Deneb. It doesn't matter how many times you visit the wormhole and go "Over the rainbow", the wormhole will appear in the map like a not visited place.
There is a link to an image of the map here: http://www115.zippyshare.com/v/pueSFjEs/file.html

**Comment by Wrzlprnft** [comment]
There is a commit made by MZ which fixes the visited map issue. Wormholes do not longer count for it.
