### ISSUE TITLE
Cannot define custom explosion damage in save files

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1473]
You can change which explosions are used and what the final explosion is, but you can't change the actual damage of the final explosion for some reason. If you add a custom `weapon` line to the attributes section, it's ignored completely, and removed when the game is saved.
Note that this is for the save files. If I were changing a file in the data folder, it would work fine.

**Comment by jafdy** [comment]
But, why? Is this actually a problem?

**Comment by Bladewood** [comment]
It can't let me have fun :(

**Comment by KevinKorzekwa** [comment]
> But, why? Is this actually a problem? 

Making the final explosion damage variable gives the data files even more power to customize the game, and gives more flexibility to content creators.

**Comment by jafdy** [comment]
@KevinKorzekwa He wants to change the save files and not the data files to get this effect.

**Comment by KiLEdEnNis** [comment]
for testing, editing the save file instead only requires you to save the game, then save (overwrite it with) the text file, and reload, instead of relaunching the game, testing explosion damage w/ the save file can save time as well

**Comment by endless-sky** [comment]
Ship explosions work the same way as all weapons: their effects are defined by a single outfit, and all projectiles created by that "weapon" refer to the same base outfit. So, the only way to change a given ship's explosion is to change its base ship type.

Internally, the reason for this is that when a ship explodes, the ship object itself is deleted at the same time as the invisible explosion projectile is created. So, that projectile can't refer to the ship that was just destroyed.
