### ISSUE TITLE
Mission Typo

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1477]
Sorry I cannot remember the exact mission for this one:
![image](https://cloud.githubusercontent.com/assets/13827055/17841165/adb33428-67ca-11e6-85f8-992a3d6c0bc8.png)

**Comment by KiLEdEnNis** [comment]
FW Katya 2B, free worlds intro.txt

**Comment by KevinKorzekwa** [comment]
@KeronCyst If you're not aware, the pull request #1479 fixed the typo here (and in #1478), and it was merged by the maintainer an hour ago.  Thanks a ton for reporting it, it helps so much.

**Comment by KeronCyst** [comment]
Oops, you're right. This is my first time working with Github issues. Thanks for letting me know!

**Comment by KevinKorzekwa** [comment]
You are most welcome.  Also, if your issue is resolved, you can go ahead and close it.

**Comment by KiLEdEnNis** [comment]
@KeronCyst if you see "endless-sky added this to the x.x.x (done) milestone" (if you see done) it is done (like now) :3
