### ISSUE TITLE
Free Worlds Mission Typo

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1478]
![image](https://cloud.githubusercontent.com/assets/13827055/17841180/cee04636-67ca-11e6-87dc-09bb289f2e7a.png)

**Comment by KiLEdEnNis** [comment]
I just fired the narrator :)

**Comment by jafdy** [comment]
So that's why we haven't seen MZ for the last 8 days!
@KiLEdEnNis could you rehire him, someone needs to complete the Wanderer story. 

This is a joke according to my unusual sense of humor.

**Comment by KiLEdEnNis** [comment]
MZ is the narrator? o:
