### ISSUE TITLE
Engines disapear 

### ISSUE THREAD

**Issue by aftrans57** [endless-sky/endless-sky#148]
During the Terraform Rand quest, I was killed by pirates after getting the order to move the asteroid. Reloading the games removed my side engines, x1200 Ion Steering, in my Freighter ship. I can't jump, turn, or land anymore and can only go straight. Rand has no outfitter to allow the purchasing of new engines.

**Comment by constantm** [comment]
https://github.com/endless-sky/endless-sky/issues/145

**Comment by endless-sky** [comment]
This is probably due to the bug where the effects of being plundered by pirates are not applied until you reload the game. That bug is fixed in 0.8.7.
