### ISSUE TITLE
Problem: Selling by mistake valuable plundered outfits.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1480]
I am actually trying to plunder jump drivers and other alien technology to equip the ships in my fleet and I am used to click on the buy all, sell all buttons when trading commodities. The problem is that too many times, when I have plundered cargo that I want to keep (and that has been hard to get), I have sold it by mistake pushing the "Sell all" button.
Proposed solution: To add in Preferences the option "Exclude plundered cargo when selling all" On or Off.
If, at the moment, you intend to sell all your plundered items you can leave the option off. If you want to collect valuable plundered outfitls, leave the option on. If, by mistake, you have the option off and you want to sell all your plundered cargo and that planet doesn't have Outfits, go to Preferences, change the option and return to game.

**Comment by KiLEdEnNis** [comment]
buying and placing said things in cargo would also fix it, and that has been requested before, this preference idea seems unlikely but the problem would be solved the other way as well

**Comment by retrue** [comment]
About placing in cargo I have an idea too.
The possibility of purchasing storage space in worlds with Outfits. The storage space would be expensive, for example 100 tons for 1M, but you could purchase as much storage space as you wanted and in so many worlds with Outfits as you wanted.
You could pull there the plundered cargo and all the other outfits from your ships that you don't want to sell, so you could use those outfits in the future in other ships.
But this idea doesn't exclude my previous idea. They are compatible.

**Comment by Bladewood** [comment]
We already discussed warehouses a long time ago. The thread is hidden somewhere in either the issue page or the pull request page.

As for your previous suggestion, I would enhance that by replacing the "Sell All" button with a "Sell Outfits" button once it is clicked. For example, I plunder outfits and cargo from a ship. I land on a planet, click "Sell All", and automatically sell all of the non-outfit cargo. Then, the button is replaced with "Sell Outfits", so I could choose if I wanted to sell the plundered outfits or not.

**Comment by MarcelineVQ** [comment]
If you make a point to sell as trade goods only at planets with outfitters you'll avoid this because if you sell outfits on the trade panel you can buy them back at the outfitter.

**Comment by KiLEdEnNis** [comment]
about the "warehouse" idea, just buy a big ship, give it only like the tiniest engines, a tiny fuel cell and nothing else, park it, and place outfits in it so the ship serves as a storage (I do that sometimes)

**Comment by Bladewood** [comment]
That's what I do.

It would help if we could store weapons and engines, tho, and not just regular outfits.

**Comment by endless-sky** [comment]
I've implemented @Bladewood's suggestion in commit e1810e9: if you have both outfits and other cargo, you'll need to click "Sell All" once to sell everything else, then it becomes "Sell Outfits" and you can click again to sell the outfits too.
