### ISSUE TITLE
Cargo-Selling Woes

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1481]
(I searched for "cargo" issues here and couldn't find one that addressed this; my bad if I missed it.)

- I captured a ship with a level-2 shield generator.
- I have in cargo a level-2 and a level-3 shield generator.
- The ship has enough outfit space to support a 2-to-3 swap.

It is not possible to do the swap at an Outfitter without first selling the level-2 generator in my cargo.

**Comment by jafdy** [comment]
You should be able to sell the equipped small and then install the medium with out touching the small in cargo.

**Comment by KiLEdEnNis** [comment]
like jafdy said, I think you mean you have a T2 shield gen equipped, and a T2 + T3 in cargo
what you say is you can't equip the T3 because a T2 is equipped
(felt that some explanation could be useful)

**Comment by KeronCyst** [comment]
It always sells cargo first and then what's installed. I mean, I guess I could just instantly buy it back but it would be nice if we could pick.

To me, a separate inventory management system apart from the Outfitter would rock.

**Comment by Bladewood** [comment]
I have come across this before.
I can say that it is situational.

**Comment by endless-sky** [comment]
Anything you sell on-planet can always be bought back, and you can buy into cargo. So, it's possible to deal with any situation like this, although it may be in a slightly roundabout way (selling something then buying it back instead of swapping directly).

**Comment by KeronCyst** [comment]
Wait, how do you buy into cargo? From my experience, you can't buy something that you can't install onto the selected ship right away.

**Comment by endless-sky** [comment]
If you don't have any ships selected, you buy and sell directly to cargo. That is, you can use the same modifiers used for selecting multiple ships (shift / control) to instead deselect all ships.

**Comment by KeronCyst** [comment]
Oh! I had no idea about this! Wow, that's awesome. If the tutorial character in the beginning could make this clear(er?), that would be great. If I just somehow missed it, then I'm dumb and never mind.

**Comment by KevinKorzekwa** [comment]
This is the type of thing that would fit in a "Tips and Tricks" section of an in-game encyclopedia, which we don't have yet.  It feels a bit awkward to me to be put into a tutorial.  Ideally, you would figure it out when you realize that shift-clicking and control-clicking work for selecting ships, since this behaviour matches what happens in a lot of other things.

**Comment by KeronCyst** [comment]
I thought it only applied to trading commodities at first, and then I discovered that it also modified Buy/Sell when trying to dump looted ammo, but I still didn't realize it could apply to ships.

I don't think it'd be awkward at all:

"You don't *have* to immediately install outfits to your ship, ya know. Deselect your ship with [CTRL] to work with just your cargo storage."

**Comment by KevinKorzekwa** [comment]
Fair point.  It might really be worth breaking the fourth wall a few times like that to give a feel that hotkeys and other advanced options are available, not to mention how to properly make a guess as to which hotkey will work in a given situation.  It might or might not call for a restructuring of that dialogue, which again could really help out new players learning how to get around efficiently.

**Comment by KeronCyst** [comment]
Haha. If we don't wanna go too fourth-wall, then maybe ship selection in the Shipyard could be remapped so that the "with [CTRL]" part of that hypothetical tutorial text can be entirely removed:

If only one ship is selected:
> If you left-click that ship icon
>> Deselect that ship

**Comment by endless-sky** [comment]
All of that is mentioned in the player's manual, as well as the official FAQ on Steam.

The problem with a tutorial is that it feeds the player information in a certain pre-determined order, at a time when they have just started playing and therefore don't really have any idea of what is important for them to remember and what isn't. That's where a manual, which the player can consult when they need it and just jump to the sections that matter to them, works a lot better. And anyone who wants a tutorial that holds their hand every step of the way probably isn't going to enjoy the rest of the game, anyway.

**Comment by KevinKorzekwa** [comment]
@endless-sky would it be possible for someone to put together an in-game encyclopedia on the home screen (the one you get to by pressing 'esc') that includes the Player's Manual, the official FAQ on Steam, and definitions of all (reached) in game content?  Or would that disagree with your idea for the game?

**Comment by KeronCyst** [comment]
I didn't even know there was a player's manual all this time. I do agree with @KevinKorzekwa about it being very helpful to add a link on the main menu screen, but either way... I sit corrected.

**Comment by endless-sky** [comment]
It's just a matter of priorities - making an in-game manual that is as easy to use as the manual in the wiki (allowing text searching, a table of contents, etc.) would take a huge amount of work. And the map already lets you look up info on any system, planet, outfit, or ship that you know about.

**Comment by KevinKorzekwa** [comment]
Fair enough.  It's good to know though, since it's something I would like to keep in mind as a possibility for the future.

**Comment by KeronCyst** [comment]
I was just thinking of having a menu link point simply to https://github.com/endless-sky/endless-sky/wiki/PlayersManual (as I had no idea this existed until now).

**Comment by jafdy** [comment]
There is a ingame ensiclopedea request open. #904
