### ISSUE TITLE
Outfitter GUI request

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1482]
In the Outfitter screen: Have a checkbox button that, when optionally checked, grays out the pictures to all equipment that your currently selected ship lacks sufficient outfitting space for.

Or maybe the text could be italicized or something.

**Comment by KiLEdEnNis** [comment]
decent idea, but it's not that important
even though I know basically everything by head I hope this gets added :)

**Comment by KevinKorzekwa** [comment]
It's quite important, any improvement in the user interface is quite valuable.  Improvement, for UI, includes keeping things from being bloated, so this has a lot of potential if developed further.

Even if it is delayed until, say, UI 2.0, it will be worth it.

**Comment by KiLEdEnNis** [comment]
@KevinKorzekwa I'm used to the interface and I don't use half the things, so maybe my opinion isn't that valuable :P

**Comment by KeronCyst** [comment]
Or, really, filters would be super-helpful:

- Show only equipment that the current ship has outfitting space for
- Show only what's installed on the current ship
- Show only what's in cargo (like especially when I wanna quickly dump stuff I claimed from boarding; this would *really* help versus searching through all of the Outfitter for the word "cargo" manually)

**Comment by jafdy** [comment]
@KeronCyst for the last point: you can do that with the sell all button in the trading panel.

**Comment by KevinKorzekwa** [comment]
> I'm used to the interface and I don't use half the things, so maybe my opinion isn't that valuable :P

Fear not, @KiLEdEnNis, your opinion here is still valuable.  In terms of the UI design, existing users that have learned the existing interface must also be fully considered for any change to the interface.  If it makes you unable to do things (other than making you think for a second when you first see it), then it fails.

**Comment by KeronCyst** [comment]
@jafdy: I'm not sure I'm following. Where is the sell-all button for in-cargo items in the Outfitter?

**Comment by KevinKorzekwa** [comment]
@KeronCyst it is in the Trading panel, not the Outfitter panel.  It sells all outfits and materials in cargo, excluding mission cargo.

**Comment by KeronCyst** [comment]
Wow, hm. Thanks, but see, these things aren't explained at all (I guess I just never noticed that it cleaned out my outfit cargo every time I used it).

Unless the tutorial did say it and I just forgot, it would be great if—for just the first time that you press "Sell All" in Trading—a popup would say something like, "Note that this button also sells all cargo outfits/non-mission cargo, not just trading commodities."

Hm... now that I think about it...

Outfits as mission cargo... that one distant system needs Ramscoops!

**Comment by Wrzlprnft** [comment]
The behaviour of that button was changes to only sell goods on the first click, and then change to a "sell outfits" button.
