### ISSUE TITLE
Fighter mass increases max heat on carriers

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#1484]
Observed using a nest with 2 lances, red bar moves up when releasing fighters.

**Comment by KiLEdEnNis** [comment]
technically fighters would absorb a small amount of heat because they are linked with their mothership, but it's still weird

**Comment by Amazinite** [comment]
So are you saying this is a bug? This is how maximum heat works; maximum heat is based off of the mass of the ship and its heat dissipation stat. Since fighters and drones docked on a carrier ship add towards its mass, it also adds towards its maximum heat capacity.

**Comment by endless-sky** [comment]
I think the right solution would be that when a fighter launches, it takes with it whatever share of the mothership's heat belongs to it. So, the mothership would stay at the same temperature, and the fighter would launch with that same temperature as well.

**Comment by KiLEdEnNis** [comment]
the only thing I can see happen then is fighters overheating when launched, but for that they have to run close to their limit anyway

**Comment by endless-sky** [comment]
Fixed in 7419604. Also fixed an identical issue that happens when you jettison cargo (d3f2128).
