### ISSUE TITLE
"fuel damage" attribute [mechanics/enhancement/balance]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1485]
pretty self explanatory, but just in case: reduces the target's amount of fuel by specified amount on hit...

was requested in the Google Group recently.

it may be an option down the road to fix Flamethrower-balance...

could also fill the additional "jump inhibitor" niche some people have been asking for, that happens to balance itself, since you can no longer refuel through plunder, or end up with an unfueled escort through capture, when you stop them this way.

**Comment by KiLEdEnNis** [comment]
you mean the interdictor thing?

**Comment by LocalGod79** [comment]
their subject was an announcement of a project they were starting, but the message was mostly this request.

**Comment by Amazinite** [comment]
I can see it now:
Have 200 fuel left.
Try and jump out of a system.
Get hit by a fuel damage weapon.
Crash the game.

**Comment by KiLEdEnNis** [comment]
a little irrelevant;
a new attribute that disables jumping could be added, and then set on a beam weapon (and when MZ makes "aura" weapons, like the Drak Drainer, it could be on that as well)

**Comment by Amazinite** [comment]
@KiLEdEnNis  That's pretty much what I asked for forever and a half ago in #855

**Comment by Amazinite** [comment]
@LocalGod79 for your confused face; what I'm trying to say is, what happens if you get hit mid jump and then don't have enough fuel to continue to jump? I can see that causing a bug if it isn't thought about when creating the weapon.

**Comment by KiLEdEnNis** [comment]
another idea (which is the worst one in comparison) is having all drives having to "charge" after you face the direction or something, and that damage would interrupt it
- hard to code
- annoying to jump if that's implemented

although, if jumping is only allowed after 5s of no combat, it'd be entirely solved

**Comment by Amazinite** [comment]
> although, if jumping is only allowed after 5s of no combat, it'd be entirely solved

Please no.

**Comment by KiLEdEnNis** [comment]
a long-range laser that does like .1 damage per second and having a little bit of negative hit force paired with a 1s no-combat jump system could also do
anyway I feel like this went too much off-topic, and I am usually the one causing that :P

**Comment by Amazinite** [comment]
> with a 1s no-combat jump system could also do

Still no. A "no jump if in combat" system is practically what my original warp inhibitor was (at least if you look at it at the most extreme level, because escape was still possible if you stack hyperdrives or are fast enough to escape the ship with the warp inhibitor). That's exactly the kind of thing Local is trying to avoid.

**Comment by LocalGod79** [comment]
i think if you got hit by a weapon bearing the attribute after the jump effect is occurring, you would have negative fuel (displayed as 0) once you entered the new system until you either 'scooped enough, or landed.

**Comment by Amazinite** [comment]
I just set my fuel to negative on an uninhabited world; that is how it works right now, with having to scoop up enough fuel to get into the positive.

**Comment by KiLEdEnNis** [comment]
I had the idea of a secondary weapon that launches buoys every so often that disables jumping in the system, but that'll be so annoying, but with a fast enough ship you can counter every idea, including a locking laser that disables drives :/

**Comment by Amazinite** [comment]
I think that any idea for a jump inhibitor should be escapable in some way.

**Comment by jafdy** [comment]
Could you say that if the effect has started (and fuel is being consumed) the jump will continue and the say [pusdo code]
`if fuel < 0 
   set fuel = 0
   else continue`

**Comment by Bladewood** [comment]
I say we just cancel the jump.

**Comment by LocalGod79** [comment]
i say that once the drive/jump effect is initiated, it doesn't matter what happens; you end up in the target system (perhaps with a fuel deficit to recover).

that said, if a target is being bombarded with fuel-draining weapons (that may also have hit force), the chances of actually turning to decelerate to jump speed, aligning to the target system, and initiating that effect before fuel drops too low will vary with the strength of the weapon, target's ramscoop ability, and turning rate - all of it allows for a lot of depth with this attribute.

**Comment by Nechochwen-D** [comment]
I have created a pull request which adds this damage type. #1492 # #

**Comment by Bladewood** [comment]
I just thought of an idea.
We could give the Drak an "anti-fuel field" weapon that quickly drains the fuel of any nearby hostile ship, including cloaked ships, who are forced to reveal themselves.

**Comment by Nechochwen-D** [comment]
[Drak edit.txt](https://github.com/endless-sky/endless-sky/files/453170/Drak.edit.txt)
Try this out.
(note it will need you to use my "fuel damage" attribute #1492 to work)

**Comment by Bladewood** [comment]
-3000*60=-180000 fuel a second is a lot...

**Comment by Nechochwen-D** [comment]
Then change it

**Comment by KiLEdEnNis** [comment]
180k fuel/s? so as soon as they fire you are screwed

**Comment by Bladewood** [comment]
It should be reduced to around 100/s...

**Comment by Nechochwen-D** [comment]
Do what you want.
I only threw it together for an example.

**Comment by KiLEdEnNis** [comment]
at least try to think about considering maybe keeping it slightly balanced lol, even the Drak aren't filthy cheaters like that

**Comment by Bladewood** [comment]
It wouldn't really matter anyway. Give it a value like 300/s and it could drain a ship before they even finished jumping in. Anything over 1000/s is effectively just the same thing, instantly zero fuel.

**Comment by Nechochwen-D** [comment]
You haven't seen my "interdiction" attribute.
Instant 0 fuel.

**Comment by Nechochwen-D** [comment]
And anyway. I was just playing around with what I could do. I would not use something so OP in a serious game.

**Comment by Nechochwen-D** [comment]
Just re-did the attribute. #2003

**Comment by tehhowch** [comment]
This can be marked for `0.9.9 (done)` as of c3cb2551f67e9d3b57d45c37122f00523b005a71
