### ISSUE TITLE
[question] plans for drawing landscape images (if they look realistic enough)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1486]
there is a need for more landscape images, and people who have projects may need completely different landscape images, so if they can create realistic images in the right aspect ratio (making them nearly as realistic as pictures) are they allowed for in-game purposes? (alien landscapes)

**Comment by jafdy** [comment]
Yes. The landscapes need to be of photo-realistic quality to be merged.

**Comment by KiLEdEnNis** [comment]
I'll give it a try, although I'm not sure how I'll do
still, others could try it as well

**Comment by jafdy** [comment]
Most people find it easier to take photos than to draw something but we always need more variety.

**Comment by KiLEdEnNis** [comment]
we can't exactly create irl ships and take pictures of actual alien planets (also because we found none), maybe rendering an image in Blender can help with that

**Comment by endless-sky** [comment]
My hope is to find some people willing to contribute "matte paintings" of sci-fi scenes. (Just do a Google images search for "science fiction matte painting" for examples.) The hard part is convincing people to release them under a Creative Commons license, though.

**Comment by retrue** [comment]
Sugestion: Take free photos and photoshop them. In a landscape change Earth's sun for a bigger red sun, or add a second sun, or a second moon, or change the colour or vegetation.
It would give that alien image and it is easier and faster than drawing a photorealistic landscape from scratch.

**Comment by KiLEdEnNis** [comment]
I know some music artists that use images they google up, so I'll steal a few of them :3
(not sure if I should close this issue so I'll leave it open)

**Comment by KevinKorzekwa** [comment]
@endless-sky, I have reached out to a few artists I know, and their reaction was positive (at the very least for playing the game :P ).  I hope to get them some lore to base their designs on.  I am waiting until I have a finished piece before reaching out to content creators on the google group.  Maybe keep an eye out for that in the coming months.

**Comment by KiLEdEnNis** [comment]
@KevinKorzekwa I snatched about 20 pictures which I "print screened" from music vids and cut to 720x360, I'll use them for my project and if I'm done (which will take months, maybe a year) they'll automatically be added

**Comment by Wrzlprnft** [comment]
@KiLEdEnNis unfortunately, snatching pictures is not covered by the games license

**Comment by KiLEdEnNis** [comment]
@Wrzlprnft they took it from some free site anyway (can try to find out which one), meaning the pictures are free to use

**Comment by jafdy** [comment]
Even if you think the pictures are from a free site you should find the site and get it from there.

**Comment by KiLEdEnNis** [comment]
@jafdy then I'll move the pics from my files to some storage & try to find actual images
