### ISSUE TITLE
Attacking and plundering Unfettered tribute freighters

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1493]
The water bug freighters that are sent once you negotiate the Wanderer-Unfettered ceasefire are slow and nigh defenseless. You can easily board them and harvest their jump drives and other goodies. And since the Unfettered are looking for jump drives, you can just go to Firelode and sell the jump drives for much more money and for peace, and the Unfettered are now in ignorance of your past crimes against them. And you can repeat this indefinitely (assuming you can get past the Unfettered guards in orbit around Firelode).

I don't think Endless Sky's supposed to be _that_ easy. Perhaps the water bugs should have some escorts with them.

Also, the water bugs are supposed to just carry food, so why do they have other types of cargo?

**Comment by KiLEdEnNis** [comment]
if they have escorts you'd have more free jump drives, the Wanderers want peace so maybe that if they have peace, the Wanderers become hostile if you attack the freighters (which would require a new government because they'd be hostile otherwise if you attack their home worlds)

but Endless Sky is easy in some ways, you can just hijack 20M+ credit ships and sell them :/

**Comment by toilethinges** [comment]
@KiLEdEnNis, yeah, and you don't even need to risk hijacking that big a ship - you can just take a reactor from a ship that's worth that much alone, and only takes up a third of your cargo space.

Back to the original topic, lore (other than the food). They're sending an unarmed freighter to go pick  up supplies. If they sent an escort, the Wanderers would decide it was an attack, and destroy them, causing war again. I really don't have any solution for that.

The food, though... maybe there should be an option in fleets to choose exactly which kinds of cargo that fleet can carry?

**Comment by KiLEdEnNis** [comment]
@toilethinges specific kinds of cargo was suggested before, I hope it gets implemented

**Comment by endless-sky** [comment]
The tribute ships are supposed to stop appearing once the Unfettered invasion begins, but got left in in one system. Fixed that in 37b11e8.
