### ISSUE TITLE
Deep Archaeology 1 has 150% random chance to offer [content/bug]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1494]
i'd have made a pull request, but i'm not sure what it's supposed to be.

**Comment by LocalGod79** [comment]
indeed - that there is more than one possibility was enough to keep my hands out of it - mostly to try to keep commit history cleaner for a single-character correction.

**Comment by Bladewood** [comment]
That explains why I was always offered the mission when I looked at Earth's spaceport.

**Comment by endless-sky** [comment]
Fixed in 37b11e8.

**Comment by Alkallid** [comment]
What kind of typo occurs with characters so far apart?

**Comment by KiLEdEnNis** [comment]
maybe he couldn't decide between 10, 15, and 50?

**Comment by LocalGod79** [comment]
when your hand is over the keypad, 0 is a very easy number to accidentally press...

perhaps the offer conditions were copied and pasted from another mission, and the random chance was edited hastily (and incorrectly)...

there are lots of possible explanations...

**Comment by endless-sky** [comment]
What probably happened is that I set the probability to 15%, then added a
zero to make it always fire (while still maintaining the "15" to remind me
of what probability I'd intended), then forgot to take the 0 out before
committing.
