### ISSUE TITLE
Thruster flare naming consistency

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1495]
The ion and plasma thruster flare image names are as follows:
> tiny
small
medium
big
huge

While the atomic and korath thruster flare image names are:
> tiny
small
medium
large
huge

Which series are we supposed to follow when naming thruster flares?

**Comment by Amazinite** [comment]
The second one, as the sizes are alphabetical from largest to smallest. MZ said how he needs to changes any mentions of "big" in size to "large" to keep it consistent. The only other place I know of this right now is the explosions.

**Comment by KiLEdEnNis** [comment]
*OCD intensifies* :P
just large asteroids were never shown in-game for like a year or so because the files named them "big" as well :(

**Comment by endless-sky** [comment]
Fixed in 3c28b5b. The alphabetization is so that the sets of sprites will show up in a logical progression when a folder is sorted by name, so it serves an actual purpose rather than just being an OCD thing. :)

**Comment by KiLEdEnNis** [comment]
now I'll sleep well tonight :3
