### ISSUE TITLE
[enhancement/mechanics] Hide trade panel when nothing is sold

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1497]
As the title says, when no commodity prices are listed in a system, hide the trade panel.

**Comment by endless-sky** [comment]
Addressed in 389d490 and 5edabee: the map shows "----" for the commodity prices, but still lets you click commodity names to color by them. The trading panel is visible if *any* trade good is for sale, but shows "---- (not for sale)" for any commodity that has no price in the current system.

**Comment by toilethinges** [comment]
389d490 is what I was referring to, but 5edabee is really nice, too!

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
