### ISSUE TITLE
Some scort ships in my fleet don't scort my flagship

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1499]
4 of my 20 scort ships don't follow the flagship. They do follow if I have ordered to gather around the flagship, but if not, they go to an extreme of the map, so far away that they don't come back when I order the fleet to gather or when the rest of my fleet is fighting. To get them back I need to go to that extreme of the map and order to gather.
I can provide screenshots or a savegame if necessary.

**Comment by KiLEdEnNis** [comment]
probably an AI bug (as usual)
or you really need new personnel

**Comment by MessyMix** [comment]
Screenshots or a savegame might be necessary.

Say, do you happen to have missile launchers on your ships, and perhaps no ammo? Sounds like missile fleet behavior.

**Comment by retrue** [comment]
Where I upload the savegame?

**Comment by toilethinges** [comment]
Just put it in Google Drive or Dropbox and put a link.

**Comment by retrue** [comment]
The savefile is [here](https://storage-us.mail.com/qx/mail_com/?locale=en&guestToken=h1RT3R3wRpek_Yqa6XTRkg&loginName=retrue@mail.com#%2Fcloud%2F%3Aexplorer)
Just depart from the spaceport and stay around the planet. Or jump to another planet and stay around the planet. In some seconds, the 3 kestrels and one shield beetle called "Cucaracha" will move to an extreme of the map.

**Comment by jafdy** [comment]
I believe you can upload a file within one of these comments. 
>Attach files by dragging & dropping, selecting them, or pasting from the clipboard.

It's at the bottom of the comment box.

**Comment by endless-sky** [comment]
This should be fixed by commit 0954a3d.

**Comment by endless-sky** [comment]
The underlying issue was that the AI was inaccurately estimating what direction your ships would travel in when they applied reverse thrusters but also had high drag coefficients.

**Comment by retrue** [comment]
I tried the last commit and my bad scort ships behave now. No more wandering.
