### ISSUE TITLE
Incoherent message when hailing a ship for assistance

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#15]
When hailing a drone for assistance (with empty fuel reserves), the drone answers that I appear to be in no need of repair or fuel.

**Comment by akien-mga** [comment]
Actually I got the same issue with a normal ship from the Republic, so it's not just that drones can't help refill the fuel reserves as I guess initially. No idea what's wrong then :-/

**Comment by endless-sky** [comment]
That's a bug. It looks like any ship that has the "surveillance" personality will give you that message. My latest commit should hopefully fix that.

**Comment by akien-mga** [comment]
I'm glad you managed to find the culprit based on so little debugging info :)
I don't see your commit online though, I guess you haven't git push'ed it yet.

**Comment by endless-sky** [comment]
This should be fixed in 7bc20c1, but let's leave it open for a while for further testing.

**Comment by endless-sky** [comment]
I made one final change in d8c7f53, but this should be fully fixed now.
