### ISSUE TITLE
Mission navigation

### ISSUE THREAD

**Issue by wisemonk** [endless-sky/endless-sky#150]
When in game and selecting a mission and it showing its destination and path, it would be easyer to be able to just select the mission and be able to jump through that path other wise it just jumps randomly unless you physically select the jump path to that system

**Comment by endless-sky** [comment]
That's actually what it used to do, but people got really confused that their jump paths would change just because they clicked on a different mission (e.g. to check what the mission requirements were). So, I switched it so that your jump path only changes when you click on a system.

**Comment by wisemonk** [comment]
No worries well since its open source and with you I can always make DLC content to change little things like that for people that may want to use IE plugin ect ?
