### ISSUE TITLE
Flycatchers think I'm their mother?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1501]
I sat in a Tempest and went to Ap'arak. Then I got bored and sat on their star.
Then these two flycatchers went up to me and started to *orbit* my ship.
I think their new drone classification causes them to attempt to dock in the nearest friendly ship (which happens to be my own). Even though it has no drone bays. And they have no scanner systems, so it can't be routine surveillance.
Eventually I flew away and they stopped following me, flying off to chase other ships instead.

**Comment by KiLEdEnNis** [comment]
they have the "swarming" tag, which means they behave like ships when you do the "gather around" command

**Comment by Bladewood** [comment]
These aren't my ships...
And the gather command isn't being used...

**Comment by KiLEdEnNis** [comment]
I know, gather works LIKE gather, but friendly ships w/ swarm "gather" around you, and they never stop

**Comment by toilethinges** [comment]
What he's trying to say (from the wiki):

> swarming: ships of this type will "swarm" around any friendly, non-swarming ships that are in-system. No more than six ships will swarm a given target. Any swarming ship with nothing to swarm will try to land on a planet instead. (v. 0.9.1)

**Comment by Bladewood** [comment]
Veeery interesting.
I have my own personal bodyguards now, yay!
