### ISSUE TITLE
An android port would be very welcomed

### ISSUE THREAD

**Issue by mquinson** [endless-sky/endless-sky#1502]
Hello,

it'd be cool if you could come up with an Android port of this great game. For my pleasure to be complete, you'd include it to the f-droid.org repository, since I banned the Google Play repository from my systems lately.

Thanks in advance, 
Mt.

**Comment by toilethinges** [comment]
https://groups.google.com/forum/#!category-topic/endless-sky/ZofHPq7bV3M

**Comment by Amazinite** [comment]
This too: http://steamcommunity.com/app/404410/discussions/0/368542585866379454/

**Comment by mquinson** [comment]
I'm not allowed to see the google forum (so I'm less ashamed to not find it before filling that bug). I should have found the steam discussion, maybe, but github search did not raise it.

Sorry, then.

**Comment by Amazinite** [comment]
We're just pulling up related posts on it.

**Comment by KevinKorzekwa** [comment]
Has a change been made to the google groups?  I cannot access it either, and I know I have in the past. I even get emailed weekly updates from that group.

**Comment by endless-sky** [comment]
I haven't changed anything in the Google Groups, and it still tells me that it's set up to be visible to the public, so I'm not sure what could be wrong.

**Comment by KevinKorzekwa** [comment]
I'm not signed in to Google, and this is what I see.
[http://i.imgur.com/tRO2EIq.png](url)
When I log in, I do see everything as normal.

**Comment by endless-sky** [comment]
By "android," are you talking about phones? Or tablets? It seems to me that ES would be rather hard to play without a full keyboard.

**Comment by jafdy** [comment]
If you gave up fleet commands and flagship firing you could control movement by pressing around the ship. You would need separate buttons for the ESC and I menus and probably R too but everything else can be controlled by clicks.

**Comment by Cat-Lady** [comment]
I would like to point out that even straight port without *any* added mobile control would be great - there are devices that have built-in keyboards (really! My mobile computer/phone have a fully 6-row one), most devices can connected keyboards via usb hostmode, and there are other possibilities, as well (like using sixaxis, the playstation 3 controller, with input mapped to fake keyboard inputs).

Things like proper on-screen controls could come in later (or never, for what I care, but I know there are people that would like them very much).

**Comment by samrocketman** [comment]
FYI (I know I'm raising the dead but...) there's an unofficial android port of the game at https://github.com/thewierdnut/endless-mobile
