### ISSUE TITLE
Automation of Repetitive Tasks

### ISSUE THREAD

**Issue by VladFurman** [endless-sky/endless-sky#1504]
Certain things in the game are done constantly, and once a player is familiar with the game, without thinking. These actions do not represent any strategy or decision on the part of the player, but are bookkeeping and extra clicks that can be frustrating after the player has done them hundreds of times.
Some examples:

1. Re-hiring lost crew
2. Buying ammunition
3. Buying/selling trade goods along your planned route
4. Flying to a shipyard to sell captured ships

While this could be accomplished with setting/buttons, I think there's opportunity for a more immersive/balanced method: specialist crew/hires.

As the game starts, the player is unfamiliar with crew/fleet/cargo management, and the margins are small - manually controlling all aspects of that makes sense. As the player's fleet grows, they start hiring and taking on more of the role of a commander or admiral than captain of a single fleet. Hiring specialists to manage trivial portions of your fleet enhances the feel of being an "admiral" and commanding a fleet as well as reducing frustration over constantly taking the same actions.

In general, specialists would be hired much like crew. They will probably take up crew slots on the ship, but they probably shouldn't fight. They would be paid significantly more than regular crew, and possibly take cuts instead of a straight salary.

## **Recruiter/Sergeant**:
This specialist hires crew for your flagship up to its maximum whenever they land (possibly up to a player set limit - letting the player keep X bunks free).
Possibly they will also improve your crew fighting capability by leading them in battle.

Replaces: Click on crew, (shift/control/alt) click hire.
Salary: 500
Possible bonuses: 10 for each crew hired; if improves fighting, 1000 credit bonus or percentage of ship taken.

## **Quartermaster**:
This specialist ensures your fleet is well armed. When landing at a planet with an outfitter, they'd automatically buy ammunition for your fleet if available, without needing to enter the outfit.

Salary: 200
Replaces: Click on outfit, click "yes" on popup.

## **Economist**
This graduate from a Republic university is an expert of the markets, and will handle your fleet's cargo for you.

This is the most complex specialist. When taking off from a planet, they will check the players planned route and buy the most profitable cargo for the final destination, and fill the fleet's cargo holds. When landing on a planet, if any cargo is profitable, it will be sold (even if the destination is not the final one; this may result in buying/selling the same cargo repeatedly, but it's guaranteed to be the most profitable set of transactions possibly assuming the players ends on the planet they marked on the map).

This specialist needs a toggle/set of controls; possibly limit them from using the flagship's cargo.

Salary: 1000
Bonus: % of profit made - 1%-5%, probably.
Replaces: check destination profit, go to buy screen, click buy max. Once reached, sell all.

## **Ship Selling**
This might not be a specialist so much as an order you can give to a ship - fly to the nearest shipyard and sell itself. If pilots can be ordered to stay in a system to their death, surely they can be trusted to fly to a shipyard and sell the ship. Possibly not for full price.

Alternatively, ships can be sold anywhere, but the player either:

1. Gets only a partial price
2. Gets the cash over time - like a reverse mortage

**Comment by KevinKorzekwa** [comment]
Possible change, have the crew types reduce the total crew capacity of the ship according to ship type or a percentage of total crew.  

Example ship has 30/200 crew (required/capacity). Uses the percentage rule.
Recruiter: Takes up 10% of the capacity. The ship has 30/180 crew, but now the player doesn't have to click hire at every spaceport.  
Quartermaster: Takes up 5% of the capacity. The ship has 30/190 crew, but now the refill ammunition doesn't pop up.
Economist: Takes up 20% of the capacity. The ship has 30/160 crew, but now trading is automatic when taking off and landing on planets.
Accountant: Takes up 5% of the capacity. The ship has 30/190 crew, but now fines and death benefits are automatically paid off on landing. Ignores mortgages to allow players to take care of that.

These could be made as outfits.  Probably should have a relatively high cost, maybe on the order of 100,000 to 1,000,000 credits as an upfront cost.  Could also have a higher than normal crew cost per jump.

They reduce the total crew so that they can't participate in boarding/defending, and give the impression that they are physical people on the ship.  Having multiple people for the jobs makes sense on big ships because they have a lot to manage, and hopefully lends itself to balancing more than just 1 crew member for each position. 

I like the idea of being able to give an order to a ship to go sell itself, giving the crew a percentage of the ship's value as incentive to the crew, and real cost to the player.

Just some ideas I had while reading your post.

**Comment by VladFurman** [comment]
Not sure percent capacity is the best way to do so, but it's interesting. It does mean that if the specialists are written as outfits, it'd be easy to adjust the crew capacity - just have a negative crew modifier, like inverse bunks. The data files support that.

**Comment by jafdy** [comment]
It seems like a good idea but I don't feel it would add any thing. You have clearly put some thought in to this but it is not some thing most people will use.
Of all of them only the automatic hiring would be of use to me.
I expect that the most used will be automatic trading as a good number of people can't be bothered to do this the harder way.

**Comment by Bladewood** [comment]
I certainly like this, but Michael has stated that he does not want Endless Sky to be a fully automated game that you can just run in the background.
Or something like that.

**Comment by Amazinite** [comment]
I know that something along the lines of auto purchasing goods has been noed in the past, and I really see no point in auto selling ships, but having a preference to auto stock available ammo or auto hiring the crew on your flagship to full seems good to me; I just don't think they need to be special crew that you hire.

**Comment by VladFurman** [comment]
I understand why goods auto-purchase may have been no'd - it's an important
part of the game, but at a certain point it's drudgework and no longer fun.
After a player's made a few million and has 2-3 Bactrians, the process is
generally the same all the time: Land, sell all, pick wherever they're
going, buy all of the most profitable good, fly, repeat. When I was
playing, at a certain point I'd focus more on trying to find story
missions. I'd forget to do the trading, and when I landed and had no goods,
it was frustrating/annoying. Not that it mattered that much, because I had
so much money - each individual transaction wouldn't do much for my cash,
so I ended up ignoring my cargo until crew costs made my funds dip. Either
way - it wasn't fun, I'd done it a hundred times before, and it felt like
my cargo capacity was being wasted.

For auto-selling ships, the issue is when captured ships have drives that
don't match your core fleet's. In that case, just jumping to the nearest
shipyard isn't enough - one has to shepherd their new ships around to it,
taking longer, etc.

As for why have it be special crew / outfits that remove crew slots - I
feel that doing it that way adds to the game. It means that an early player
is still managing all that personally, and it feels like they're a captain,
in charge of every detail on their ship. However, as a player's net worth
rises to the tens of millions, micromanaging that kind of stuff gets more
frustrating and less rewarding. Hiring specialists to manage it for you
would make the player feel more like an admiral/manager, who sets the
overall fleet decisions but can leave the micromanaging to other
captains/specialists. Having to pay cash/crew slots for it also balances it
- once the player is frustrated with an aspect of the game, they can use
some of their money to remove frustration. It's not attractive in early
game, when all of this is still fresh and fun, but once the player has
cash, it's up to them if it's worth it, or if they want to keep managing
things themselves.

All of the automation suggestions are tasks that are repetitive, done at
most spaceports, require no thought (are algorithmic and therefore easy to
code) and are no longer fun (for me, at least) after 20 hours into the game.

**Comment by jafdy** [comment]
For selling captured ships, we don't need things that make ship capping easier. And I'm inclined to think that just increasing the automation would make the game more boring.

For example most free MMORPGs have ended up with a "play the game for you" button. In practices it was a "level up" button and a "do a quest" button. I think this is at risk of doing the same.

**Comment by Wrzlprnft** [comment]
Also, if you capture a ship and go to a reachable system with a planet with shipyard, they follow automatically, refuelling where possible. If they can't reach a shipyard i'd park them until theu are enough worth the changing of the drives.

**Comment by endless-sky** [comment]
I want to avoid having this game get too unfocused and cluttered by trying to blend a bunch of different game genres together. One game cannot be everything that everyone wants from a space game, and if that's what people expect, it will either disappoint them (like No Man's Sky) or just never be finished (like Star Citizen).

My goal is for Endless Sky to focus on three different styles of play:

1. Firefly mode: you are a poor captain struggling to scrape together enough credits to avoid bankruptcy and improve your lot in life over time.

2. Star Wars mode: you are trying to survive an epic war and don't really have time to think about earning money, so the game "levels you up" with salary increases and bonus payments to make sure you can afford the bare minimum ship for each mission.

3. Star Trek mode: you have so much money and can earn more so easily that you essentially live in a post-scarcity economy. Your goal is now just to discover cool new things and to make your mark on the galaxy.

A lot of what you're suggesting here sounds more like a economy / business simulation game, which really isn't where I want the focus to be. If someone has a billion credits but still wants to live like they're a starving Malcolm Reynolds grinding to get by, I won't stop them, but I'm not going to put a lot of development time into that unless it's also going to improve the core game experience too.

**Comment by KiLEdEnNis** [comment]
> it will either disappoint them (like No Man's Sky)
shots fired
I like both the simplicity and complexity of the game though, as long as I get new content I'm happy :D
