### ISSUE TITLE
Allow reordering groups of ships in the player info panel

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1508]
I am talking specifically about handling the list of ships that appears when you are on a planet and push the key i.
In the info screen you can park/unpark several ships at once using your SHIFT and CTRL keys.
In that screen you can select a single ship to move it up or down the list of ships. This works great when your fleet is small, but it is a pain in the @$$ when you have a large fleet, for example with dozens of fighters and wingboxes and many other ships. If you have bought or captured a bunch of ships and you want to move them up the list to have them organized, you have to select one ship, move it to the top of the screen (you cannot move it directly to the top of the list because the list doesn't scroll when you are moving a ship), scroll the screen so the ship is on the bottom of that section of the list, move it up to the top of the section of the list, repeat one or more times, then go to the bottom of the list, select another ship, repeat the process, etc.
A way to improve this would be adding the possibility of scrolling the screen when you are moving a ship, another way would be being able to select several ships at move them at a time, or even better, **being able to select several ships and move them up or down the whole list to put them where you want them.**

**Comment by Bladewood** [comment]
Try using the ctrl-click function (on Windows) for small groups? And shift-click for large groups?

**Comment by retrue** [comment]
That can be used to select/unselect if you want to park/unpark. But it doesn't work to move the ships in the list. I tried.

**Comment by MCOfficer** [comment]
finally found this one - i'd suggest a hotkey, too. in any other menu we can use them (even buy/sell works with hotkeys). so binding park/unpark to p shouldn't be too much effort, i hope.

**Comment by KiLEdEnNis** [comment]
(un)park WAS linked to P, so was Previous & a 3rd option
so P was then set to only Previous
Park just didn't get a hotkey after I think

**Comment by tehhowch** [comment]
This is done :)
