### ISSUE TITLE
Linux Mint, Alt key doesn't work correctly in trading window

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1509]
I just installed the last development Endless-Sky in Linux Mint (up to the last commit). I have noticed the [ALT] key doesn't work correctly. When pressing it, it appears the multiplier x500, but then it does nothing, if pressed it doesn't let you to buy or sell. However, the [ALT GR] key works as x500 multiplier.

**Comment by endless-sky** [comment]
Your OS probably has Alt+Click set up as a shortcut to drag the current window. If that's the case, the OS is trapping the event before it ever gets to the game, so there's not much I can do about it.

**Comment by KevinKorzekwa** [comment]
I'm on Mint right now, both Alt keys are working to be x500 for me.  Let us know if you do have a shortcut set up and if that fixes it.

As a side note, I had no idea Alt acted like this, so thank you for enabling me to buy 50000 rifles and Autumn Leafs.

**Comment by KiLEdEnNis** [comment]
50.000 autumn leaves, why?

**Comment by retrue** [comment]
At KevinKorzekwa, in fact I use Windows 99% of the time but in another partition I have Linux Mint 17.3 Cinnamon, with Spanish keyboard. I haven't changed the default configuration in Mint or set up any shortcut.

**Comment by endless-sky** [comment]
You could also just use the keyboard to buy and sell (+, return, or space to buy; -, delete, or backspace to sell) rather than clicking the button.
