### ISSUE TITLE
Selling multiple ships in Shipyard, ship name in dialog is wrong

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#151]
When using shift or control to sell 5 or 20 ships in a row, the name in the confirmation dialog is always the name of the first ship that was selected, not the ship that is currently up for sale.  So the player isn't told what ship is actually being sold next.  The player cannot skip over a ship they do not wish to sell by hitting cancel on the confirmation, the next confirmation will be for the same ship.

For example, I have Skrilath and Kloozorg (two main ships), then Aquish, Bquish, Cquish, ... Hquish (freighters I want to sell).  If I select Aquish, hold shift, and hit sell, then the first confirmation will sell Aquish.  After Aquish is sold, the game puts Skrilath up for sale, but displays Aquish's name in the confirmation dialog.  Since I held shift, there will be 4 confirmations after selling Aquish, and clicking OK on any of them will sell Skrilath.

Selling multiple ships should start with the ship the player selected, then move forward from there.  Clicking cancel on the confirmation dialog should skip over the current ship.

**Comment by endless-sky** [comment]
Oops, I never expected someone to do that - the expected way to sell multiple ships is to use shift-click or control-click to select the ones you want to sell, then click the sell button. If you do that, the confirmation dialog will correctly list all of them. I've disabled the multiplier key for selling ships in commit 4c02a2a.

**Comment by kyzentun** [comment]
So, now it only sells one, but the x5 multiplier prompt still appears next to the button when the modifier key is held.  The x5 text shouldn't be there when it isn't going to do anything.

The list of names when selling multiple ships the intended way is good.

**Comment by endless-sky** [comment]
In 0.8.7, this is fixed and the multiplier is only shown by the "Buy" button, not the "Sell" button.
