### ISSUE TITLE
Derecho sprite has extra turret

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1512]
![derecho turrets](https://cloud.githubusercontent.com/assets/16506683/18072139/c5f36f84-6e29-11e6-8177-69b70b1d6726.png)
In the stock model, the top two turret mounts (circled in red) each have dual sunbeam turrets, while the bottom two turret mounts (also circled in red) each have wanderer anti-missile turrets.
But then what is the turret mount in the center (circled in blue)?
It does not appear in the wanderer ship file.

**Comment by endless-sky** [comment]
I decided that it was unbalanced to give it five turrets, but never went back and modified the sprite.

**Comment by endless-sky** [comment]
Fixed in 62bc5d9.

**Comment by KiLEdEnNis** [comment]
giving it the extra turret w/o extra outfit/weapon space seems good though, not like you'd use them all
