### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1514]
What is the range of "Random::Real"?

**Comment by KiLEdEnNis** [comment]
if you mean the random stat, it goes from 0 to 99 (or 1 to 100)

**Comment by Nechochwen-D** [comment]
And what about "Random::Int"

**Comment by KiLEdEnNis** [comment]
not sure at all, I'm not a C++ editor, I just meant the "random" you see in missions / save file

**Comment by LocalGod79** [comment]
i believe that's the player's "random" condition on landing; used for mission availability.

i've tried altering this stat to force missions to appear to no avail; i believe it is saved before the checks to offer missions (which, when available, also get written to the save file).

so once you've landed, you can basically see what your random number "roll" was...

might work for `self destruct`, though:  anyone care to test it?

**Comment by KiLEdEnNis** [comment]
from personal experience it feels like if you do missions it stays low, if you don't do missions it gets higher
not 100% true, but if I take regular missions & then land at a destination it becomes low

**Comment by LocalGod79** [comment]
i think you have your "cause" and "effect" mixed up, there @KiLEdEnNis 

most missions have `random < X`, so you'll tend to have more of them available (and offered) when the number is low...

**Comment by KiLEdEnNis** [comment]
@LocalGod79 if you mean that a lower number means more missions; I know, if you mean that I get more jobs available after I did jobs; didn't know

**Comment by endless-sky** [comment]
Random::Int(), if not given an argument, produces a random 32-bit number, with all numbers equally likely. If given a number, it produces a random number less than that number, again with all possibilities (nearly) equally likely.

**Comment by Nechochwen-D** [comment]
Thank you for the answer Michael. I am trying to make that crew hazard profile work and was having a hard time figuring it out.

Nechochwen out.

**Comment by Nechochwen-D** [comment]
How near is nearly.

**Comment by endless-sky** [comment]
If you're picking a random number from 1 to 100, the probability of some numbers may be 1/43,000,000 higher than the probability of others. In other words, not something you need to worry about. I'm just pointing out the fact that any pseudo-random number generator running on a computer is not, strictly speaking, perfectly random.

**Comment by Nechochwen-D** [comment]
Understood
