### ISSUE TITLE
Pug Zapper has a "reload" value of 2

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1515]
> outfit "Pug Zapper"
	...
	weapon
		sprite "projectile/lightning"
			"frame rate" 60
			"random start frame"
		...
		**"reload" 2**
		"firing energy" 5.4
		"firing heat" 2.9
		"shield damage" 7.4
		"hull damage" 5.9

Setting `reload 2` causes the zapper to have a fire rate of 30 shots per second, rather than the 60 shots for a beam weapon. This value is clearly displayed in the game, not hidden unlike all other beam weapons. And, the firing energy and heat per shot and the shield and hull damage per shot are displayed publicly, also unlike regular beam weapons. Being non-integer values, they are unlike most weapons in general.
Also, it sounds weird when you actually fire it. And the beam sprite also looks weird.

**Comment by Amazinite** [comment]
That's likely intentional; it keeps the dps similar to human weapons and gives it more of a "lightningy" effect to it.

**Comment by endless-sky** [comment]
The "reload" of 2 is so it will flicker on and off rather than being a constant beam.

Many weapons have fractional values in their stats; there's nothing unique about the zapper.

**Comment by Bladewood** [comment]
I forgot about the proton gun.
I'm an idiot.

Can you do something about the weird sound the zapper makes, though? It feels like it's only playing a fraction of the sound clip.
30 times a second.

**Comment by endless-sky** [comment]
I guess the "right" solution is to make the Zapper continuous fire, and to achieve the flicker effect by adding empty animation frames rather than by having it only fire every other frame.

**Comment by endless-sky** [comment]
This is fixed by commit 4b2e025.

**Comment by Bladewood** [comment]
...is the Zapper Turret also supposed to flicker?
Because it is. (just a lot less often than the Zapper)

**Comment by endless-sky** [comment]
Yes, that's intentional.

**Comment by Bladewood** [comment]
Okay, I see.
