### ISSUE TITLE
Animated Stars and Planets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1517]
Just a thought. Might take a bit, but it would definitely add to the visuals.

**Comment by Bladewood** [comment]
Then wormholes will look cooler, yay!

**Comment by KiLEdEnNis** [comment]
just like the way we can animate ships/projectiles, only 4 frames can already make it cooler

**Comment by davidwhitman** [comment]
Have you played Space Rangers? iirc it has pretty much everything animated. The end result is...well, we'd have to be careful not to make the animations distracting. There's already a lot of stuff flying around.

I totally support *having* support for animations, though. Remember the hypergate opening animations in EVN? Awww yeah.

**Comment by KiLEdEnNis** [comment]
the game looks a bit empty yes, empty plain stars

**Comment by Amazinite** [comment]
My first thought wasn't anything too extravagant; maybe just some clouds moving across the surface of planets or lights flickering on inhabited worlds, and stars would have a few sun spots or CMEs.

**Comment by Amazinite** [comment]
Animated novas and WR stars would definetly make them more exciting to come across.

**Comment by KiLEdEnNis** [comment]
even if MZ doesn't want a huge amount of animation, some small animations will add life to the game and make it more enjoyable

**Comment by MarcelineVQ** [comment]
Is this issue requesting additional animations or requesting the ability to animate things? You can currently animate any sprite, which includes planets and such.

**Comment by KiLEdEnNis** [comment]
@MarcelineVQ for projects yes, but I think he means it for the base game; have every star animated & some planets a little bit

**Comment by Amazinite** [comment]
I know you can already animate sprites (I've done it before, but I'm no artist), but I'm asking about having this done in the base game.

**Comment by Amazinite** [comment]
So I went ahead and messed around with one of the stars.
[star.zip](https://github.com/endless-sky/endless-sky/files/453590/star.zip)
This one is the star that's in the Sol system; g0. You'll have to remove the current g0 sprite for it to animate properly. I believe that the frame rate always defaults to 2, but I set the star's frame rate to 1 in map.txt.

**Comment by endless-sky** [comment]
Yeah, the EVN hypergate animations were pretty cool.

As for all stars and planets being animated, I'm worried that it would look rather tacky. If you were actually watching the Earth from space, everything would be moving much too slowly for your eyes to pick up. And, I really *want* the space backdrop to feel somewhat sparse and empty, and not to be visually distracting.

On the other hand, running lights on a space station, or even a space station that is slowly rotating to create simulated gravity, would be really cool.

**Comment by Pointedstick** [comment]
Slowly rotating space stations with running lights would be *unbelievably* cool.

**Comment by KiLEdEnNis** [comment]
@Pointedstick  for now; more Wanderer missions, I'd love it when some projects get finished & added to the game o:
(have school, mine may take more than a year, because I don't work on it daily D:)
