### ISSUE TITLE
fleets mod limitation

### ISSUE THREAD

**Issue by Phil-Morley** [endless-sky/endless-sky#1520]
Hello,

When creating new items and make changes with a mod you add a new item to an outfitter or shipyard using the format 
outfitter "Syndicate Advanced"
    "My Fancy New Outfit"
    "My Other Fine Outfit"

But if you create a mod that modifies the fleet structure or adds ships to the existing fleets you have to specify the entire existing fleet and make your change. This means that 

Any mod that adds ships or changes the fleet structure for story reasons etc is incompatible with any other mod that also does it.
Events such as southern carriers and dreadnought deployment rewrite the fleet structure and so have to be removed or rewritten by the mod otherwise that aspect of the mod is removed by the event

Can the way fleets work be changed to the same as outfitters / shipyards so that it is just specify
"Small Southern Pirates"
	variant 1
		"Fancy little southern pirate"

possibly also adding an option to remove with variant -1 or similar?

**Comment by KiLEdEnNis** [comment]
a bit confusing but I get what you mean, if you want new ships added you can just add them to an exusting fleet version, but the FW carrier/dreadnought changes that, so a change that instead of changing the FW fleets ADDS variants could help

**Comment by Phil-Morley** [comment]
Sorry rewrote to try and make clearer, but dont think it helped much :).

Also if I add to existing fleet and another mod does it will only take one version  (or if fleets are changed in core game then fleets in mods need to be manually updated to reflect core game changes)

**Comment by endless-sky** [comment]
The main trouble with that would be compatibility with existing save game files - suddenly everyone's fleets that have changed would end up skewed much more toward the "old" ships. Which wouldn't be the end of the world, of course, but it would still be a big enough change that it can't be made lightly.

**Comment by Disiuze** [comment]
To be honest, the modder should also be taking events into account themselves, adding this would not fix things, the modders learning the fleet replacement rules would.

**Comment by Phil-Morley** [comment]
Hi sorry I am obviously not making myself clear.

At present in fleets.txt is the structure of the fleets, so we have say

fleet "Small Southern Merchants"
	government "Merchant"
	names "civilian"
	cargo 3
	personality
		confusion 40
		timid frugal
	variant 60
		"Shuttle"
	variant 30
		"Star Barge"
	variant 20
		"Star Barge (Armed)"
 etc

Now if I want to add a ship to a fleet I copy that entire fleet into my mod and add my ship at the end, so within a text file in my mod we have

fleet "Small Southern Merchants"
	government "Merchant"
	names "civilian"
	cargo 3
	personality
		confusion 40
		timid frugal
	variant 60
		"Shuttle"
	variant 30
		"Star Barge"
	variant 20
		"Star Barge (Armed)"
etc
        variant 5
                 "My new ship"

And this works fine the game knows to use the version in the mod instead of the original. However I have now essentially hardcoded the structure of small southern merchants into my mod.

So if the core game wants to change any aspects of that structure i.e. replace ships, change variant levels that's too bad as it is specified in my mod and the new changes wont be seen. 

Next it is seen is in events such as with southern carriers etc which at a specified time rewrites that structure which removes "my new ship". 
Beyond the fact that if the core game wants to make changes to the fleets it needs to update events.txt, to take this into account for my mod I have write events which triggers after every relevant existing event to put 'my new ship' back in.

Finally, if another mod specifies that fleet structure and instead of "my new ship" has "their new ship" we have a conflict between the mods over which version of the fleet is loaded and only one of the two "new ships" will be loaded. (this is already seen between existing mods 'shields up' is in folder z_shields-up which makes sure it gets loaded last and doesn't get its fleets replaced by another mod). 

This is not a problem with outfitters and shipyards as the rules there are different. In sales.txt we have 

shipyard "Tarazed Basics"
	"Sparrow"
	"Hawk"
	"Blackbird"

to add to this my mod I just put in a text file

shipyard "Tarazed Basics"
	"My new ship"

this adds to tarazed without replacing the sparrow, hawk and blackbird. Also any number of mods can add to tarazed without a problem as it just keeps adding. The core game can make any changes as well and it all works. Outfitters use the same mechanism.

My suggestion is that the mechanism for adding or changing the fleets use the same format as shipyards and outfitters, so then to add to small southern merchants I would just put in my mod

fleet "Small Southern Merchants"
        variant 5
                 "My new ship"

without specifying the rest of the fleet. Possibly using variant -1 to remove a ship.

This way the core game, multiple mods and events can all change the fleet structure without affecting each other. For current saved games it shouldn't have any effect as you can add a mod with fleet changes now and it just starts using the new fleet, this should be the same.

Hope this is clearer :)

**Comment by Amazinite** [comment]
We understand what you're saying, but what MZ has said would remain true; all the events that change fleets would need to be changed and old save files with those event changes already done would be messed up if this change was made. 

And what Disiuze has said would fix your problem; you need to take events into account when adding your new ship into a fleet. Check [this file]( https://github.com/Amazinite/Enigma-Corp/blob/master/data/fw%20story%20-%20fleet%20compatability.txt) for what that means. This one here is specific to the fleets that actually spawn in systems, so what you would need to do is change it to just modify the fleets when they are modified in vanilla. That only happens a total of 8 times in the main game, not the 43 or so times that system fleet frequencies are changed, so it should only take a few minutes to make the events that account for all the fleet changes.

Mod conflicts still persist, but that's just a problem with having multiple mods installed; not every mod is going to be able to be 100% compatible with all other mods without one of the mod creators taking steps to specifically be compatible what that other mod.

**Comment by Phil-Morley** [comment]
Thanks, now I understand :) 

perhaps just delete this thread?

**Comment by Amazinite** [comment]
You can close it.
