### ISSUE TITLE
Cargo fighter autofails "deliver cargo" missions

### ISSUE THREAD

**Issue by shengyangzhong** [endless-sky/endless-sky#1521]
Having a bactrian with boxwings means that I can accept special cargo but it immediately disappears when I leave port. As soon as you leave the planet, you get, "Ship destroyed, mission failed". (This might only happen with only a single carrier with cargo fighters, b/c I used to have mules and I didn't remember having any issues)

Most noticeable during the Pug invasion when you go in with your fleet of 7, secure the planet, and then autofail when you can't deliver the mcguffin back to syndicate space. Game is then stuck in an unwinnable state. As soon as you take off the cargo is gone and mission failed.

If I sell my boxwings after reloading from the autosave before the strike, then I can get past that point.

**Comment by KiLEdEnNis** [comment]
repeated issue... #1339

**Comment by Amazinite** [comment]
Double repeated issue. #1476
