### ISSUE TITLE
Haven description typo

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1522]
The planet description reads: 'Haven was founded by a highly successful "_privateers_" nearly two centuries ago'. 'a highly successful' suggests a singular  but 'privateers' is plural.

**Comment by KiLEdEnNis** [comment]
1 privateer seems unlikely, so remove the a :)

**Comment by toilethinges** [comment]
Both plural and singular make sense, if you think about it.

**Comment by KiLEdEnNis** [comment]
still, singular seems unlikely

**Comment by toilethinges** [comment]
It's like how people say "a pirate", referring to the captain, when there are really a dozen or so pirates on ship. (Not referring to in this game (a pirate ship), but in classic ocean pirates).

"founded by a highly successful privateer"
or
"founded by a group of highly successful privateers"

**Comment by KeronCyst** [comment]
Actually, I could imagine one single ambitious, organized entrepreneur founding it. In fact... weaving his legacy into a side story could be awesome.

**Comment by Pointedstick** [comment]
Submitted a pull request for this: https://github.com/endless-sky/endless-sky/pull/1528
