### ISSUE TITLE
Nihal spaceport description mentions "dreadnought"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1523]
> The spaceport is a single massive complex of buildings, with hangars large enough for even a dreadnought or a carrier.

The Dreadnought is not available until far into the campaign.
I haven't even started the campaign yet.

**Comment by toilethinges** [comment]
Dreadnought is a ship class, as well as a ship. If it's in lowercase, like you stated, it's not really a mistake. However, this game mentions dreadnought usually only as the ship class, so it should probably be changed to some other large, heavy warship.

**Comment by Amazinite** [comment]
"...with hangars large enough for even a dreadnought class ship."

**Comment by Bladewood** [comment]
But what would be considered "dreadnought-class"?

**Comment by Wrzlprnft** [comment]
A Dreadnought...
Joke, i guess, even without a current new Dreadnougt as a flagship of the dreadnought-class it would work in my opinion.

**Comment by KiLEdEnNis** [comment]
I'd go with either "dreadnought class ship" (kinda confusing) or change it to like Cruiser, Bactrian or whatever (Kar Ik Vot's ( ͡° ͜ʖ ͡°))

**Comment by endless-sky** [comment]
Fixed in 32a6396.
