### ISSUE TITLE
Shipyard GUI: Tooltip Overlap

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1525]
It seems like it's referring to the Sell button, but that little footer should be tooltip-free:

![image](https://cloud.githubusercontent.com/assets/13827055/18262574/b95b6cca-73b7-11e6-84c1-4cdb434a2cf1.png)

**Comment by KiLEdEnNis** [comment]
it refers to engine space, because that is where "engine space" is listed, the sell button and that part are just above it, but I don't even think if that's a mistake in the game itself, other games have that sometimes as well

**Comment by Amazinite** [comment]
#1265 duplicate

**Comment by jafdy** [comment]
We're getting a lot of duplicates. It might be worth making a list of "solved bugs" and the issue numbers for reference until the next release comes out.
To demonstrate the time gap:
current gap: 2 months 1 week since 0.9.2 
largest recent gap: 3 months between 0.8.11 and 0.9.0

**Comment by Amazinite** [comment]
Github is already a list that can show solved bugs; just search a keyword about the bug and it pops up. Checking the v0.9.3 (done) milestone is also helpful, but like in this case, some people close their issues before being given the proper milestone.

**Comment by KiLEdEnNis** [comment]
I rarely check for duplicates, but a good thing about being on github for a couple of months is that somehow I manage to remember if an issue has been made about something (can't remember them, just recognize)
but I've been noticing a few new users, which is good

**Comment by Amazinite** [comment]
Same.

**Comment by Bladewood** [comment]
Michael intended for things with the "bug" tag to not be closed, so people who are going to report the issue can check and see if it already exists.
https://github.com/endless-sky/endless-sky/wiki/CreatingIssues
We were all doing it wrong :|

**Comment by Amazinite** [comment]
Well when people search (which is what you would do when finding duplicates), both closed and open issues pop up anyways.

**Comment by jafdy** [comment]
But if they just click the search box they will keep the is:issue and is:open tags as well as the searched word.

**Comment by jafdy** [comment]
But if they just click the search box they will keep the is:issue and is:open tags as well as the searched word.

**Comment by jafdy** [comment]
But if they just click the search box they will keep the is:issue and is:open tags as well as the searched word.

**Comment by jafdy** [comment]
But if they just click the search box they will keep the is:issue and is:open tags as well as the searched word.

**Comment by jafdy** [comment]
But if they just click the search box they will keep the is:issue and is:open tags as well as the searched word.

**Comment by jafdy** [comment]
But if they just click the search box they will keep the is:issue and is:open tags as well as the searched word.

**Comment by Bladewood** [comment]
received*
Posted 6 times on my end.

**Comment by KiLEdEnNis** [comment]
I have 400+ github (Endless Sky) emails to delete manually, a few won't matter that much :(

**Comment by Amazinite** [comment]
24+ hours
Duplicate issue still not closed. 
The end is nigh.

**Comment by KeronCyst** [comment]
So if it has a milestone tag, then close the issue?

**Comment by KiLEdEnNis** [comment]
@KeronCyst if it's a bug report, keep it open until the milestone's version is officially released (like 0.9.3 milestone, close it when 0.9.3 is released)
