### ISSUE TITLE
Weapons not working

### ISSUE THREAD

**Issue by sonicscriver** [endless-sky/endless-sky#153]
my weapons don't work. When I try to fire nothing happens. I do have them installed and have tried installing then re installing but nothing changes.

**Comment by endless-sky** [comment]
Can you post your saved game? It may be that you do not have enough energy generation to fire the weapons, or you do not have any batteries, or they require ammunition.

**Comment by sonicscriver** [comment]
Sorry I deleted the save file because of another frustrating problem. You're probably right though, I'll try it next time.
