### ISSUE TITLE
After plotting a map route while on a planet, ship does not jump properly until you hit any movement keys

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1531]
This issue is 100% reproducible for me with the latest compiled source as of yesterday (not the stuff you just pushed 10 minutes ago, which doesn't compile). Steps to reproduce:
- Land on a planet
- Open the map and select a route
- Take off from the planet
- _Immediately_ press or hold-and-release the key bound to Jump. Do not hit any movement keys first.

Instead of doing a hyperjump to the first system in the map route, my ship points itself in a seemingly random direction and just sits there. Moving the ship a tiny bit and then pressing or holding-and-releasing the key bound to Jump again makes the ship do the right thing and jump to the appropriate system.

The issue does not manifest if I plot a map route *after* taking off from the planet of if I hit any movement keys between taking off from the planet and jumping.

**Comment by endless-sky** [comment]
I can't reproduce this - could you try doing a fresh clean & build to see if it's a compiler issue?

Also, what are the compile issues with the latest code?

**Comment by Pointedstick** [comment]
> Also, what are the compile issues with the latest code?

MainPanel.cpp, line 259:
	if(std::isnan(value)) ❌Expected unqualified-id


Additional steps to reproduce added above: It happens only when I take off from a planet and _immediately_ press or hold-and-release the key bound to Jump without hit any movement keys first.

**Comment by Pointedstick** [comment]
76b347159fb12eb334255cd6800eba8dce686094 fixed the compile error. I recompiled with the latest source and the issue is still 100% reproducible for me with the steps to reproduce above, which are current.

**Comment by endless-sky** [comment]
I uploaded a code fix for isnan().

I still can't reproduce that, even if I press the jump key before my ship is done taking off. I tried both pressing it, and holding it.

**Comment by endless-sky** [comment]
Would it be possible to upload your saved game somewhere? It might be dependent on exactly what ship(s) you have or what system you're in.

**Comment by Pointedstick** [comment]
Sure, here's the saved game: https://www.dropbox.com/s/1ro3fl6eksofggl/Tester%20McTesty.txt?dl=0

FWIW my OS is macos 10.11 (15G31)

**Comment by endless-sky** [comment]
Thanks! It looks like it was dependent on your particular ship's take-off speed. Commit fed6097 should fix it.

**Comment by Pointedstick** [comment]
Re-compiled with that change and confirmed that it's fixed now! Thanks for the quick response.
