### ISSUE TITLE
Fighter weapon change: short range guns to long-range missiles

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1533]
I know we've discussed the issues with fighters a lot. I'd like to propose a very simple fix:

Change out their guns for launchers. For example, two blasters become one meteor missile launcher + ammo.

That's it. Everything else can stay the same. Suddenly fighters become genuinely dangerous when there's fewer than like 20 of them (their power only seems to be demonstrable in swarms not actually seen in gameplay), launching huge barrages of missiles from long distance, which negates their primary weakness of low durability. It's a simple and effective change that doesn't even require any code changes. Obviously you can do this yourself today for *your* fighters, but if it's made a default, then it changes for NPC carriers too, which is where most of the fighter action is anyway.

**Comment by Bladewood** [comment]
*Korath fighters*
but in general, I support this.

**Comment by retrue** [comment]
Barbs are sold with two configurations. I suggest to sell other fighters with two configurations too, so the player can buy whichever he prefers.

**Comment by Amazinite** [comment]
@retruevit There isn't really a point in selling fighters with two configurations, because the player can customize them either way, as selling a lot of ships in different variants would just clutter the shipyard screen. The Barb is a special case anyways, as one of the version has a turret while the other does not. What is being asked for is a fighter variant that have missiles as their weapon.

**Comment by endless-sky** [comment]
For fighters, there are two separate questions: 1. what weapons are most effective for them, and 2. what weapons actually look cool and make fighting against them not too annoying.

Fighters with missiles would just fly directly away from their targets while launching missiles, which would probably do a lot of damage but would look really lame. At that point, you're basically just treating the fighters as extra gun ports on your capital ship, which is a lot less interesting than a space battle where fighters are flying right in the thick of the battle.

**Comment by Pointedstick** [comment]
That's basically how fighters fight, though. Being right in the thick of things barely makes sense given their fragility. They'd only get close once their missile supplies are exhausted.

But if the missile-firing AI is annoying to fight against, maybe it should be changed. This is something I strongly support, as I agree that ships which flee while launching missiles are super annoying. If you tweak the AI to have them still fly toward the enemy, that might fix both problems, as well as reduce missile waste.

**Comment by Wrzlprnft** [comment]
Maybe change the "flying away" for missle-fighters to a "flying around". Capital ships with guns would still have trouble to kill them, but smaller vessels or a hoard of turrets (sharing mounts with our anti-missle systems!) Would still eliminate them (and therefore being a alternative to AM against "circling" fighters)
