### ISSUE TITLE
steam diskussions, new forum "contests", too many pinned topics in general discussions

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1534]
The pinned section is a little crowded in the general discussions because the community started to do contests.

Old contests also disappear into nowhere so noone can look the up besides searching (and we all know how search-friendly our community is ;) )

I did not find any tools to do that as a moderator, so, please, @endless-sky, if you don't disapprove those contest, can you make a new subforum? We'll do all the move work and stuff.

PS: i did not look again for those tools and have not yet talked about that idea to anyone else, so discussion about what topics to outsource here are welcome.

**Comment by Alkallid** [comment]
While we're at it, can there be an actual mods subforum? That doesn't require Amazinite to bump it all the time?

**Comment by Wrzlprnft** [comment]
Since the trade forum cannot be removed and we now have a mods website... I don't know if worth it.

**Comment by Disiuze** [comment]
We'd still need threads.

That is exactly why I made the content creators group which no one uses for some reason.

**Comment by endless-sky** [comment]
Done.
