### ISSUE TITLE
Solution for selling captured outfits being overpowered: make crews fight before you can board

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1535]
Everyone knows that selling captured outfits from boarding disabled ships is super duper overpowered for a variety of reasons. Here's a very simple way to fix it: make the crews fight _before_ you board, not just when you try to capture the ship!

This way you don't have to implement depreciation or reduced prices for captured outfits or anything like that. It also kind of makes sense, too: if you haven't neutralized the enemy crew yet, how is it that you're stripping the ship of its outfits, many of which are internal? It also makes it more difficult to do something silly like stealing the reactor off a Pirate Leviathan that somebody else disabled with 47 pissed off bloodthirsty killers on board when you're only flying a dinky Hauler with 5 crew. To make that even remotely plausible, you'd need to equip them all with nerve gas grenades or worse, making that class of outfit much more useful.

**Comment by Bladewood** [comment]
...didn't we come up with this a long time ago?

**Comment by Pointedstick** [comment]
I didn't see it referenced in any other open or closed issue, but if I missed it, then consider it another endorsement of the idea!

**Comment by Wrzlprnft** [comment]
I always thought like: you disabled their ship and while docking you point your weapons at their bridge so they sit there and wait for you to do your move. You only have to fight them if you want to get rid of them withoit doing any more major damage to the ship.

I do support the idea of fights, though i don't think everybody of the other ships crew would be fighting for everything, which would further unbalance plundering/capturing :/

In the right incarnation and implementation this idea is the way to go, though, imho.

**Comment by BorkBorkGoesTheCode** [comment]
Would you allow the player to capture externally-mounted outfits without a fight?

**Comment by Bladewood** [comment]
I think they could.

**Comment by Pointedstick** [comment]
A seemingly sensible compromise: in conjunction with depreciation, require the player to fight the crew for any "internal" outfits: everything in the "Power" and "Systems" categories (this would also make it appropriately more difficult to plunder jump drives). External outfits like guns, turrets, secondary weapons, and engines could be plundered safely, albeit in a depreciated state where the financial benefits are lower.

**Comment by Bladewood** [comment]
nuu, not jump drives
