### ISSUE TITLE
New phrase syntax to combine multiple phrase lists together and randomly choose from among the combined set

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1536]
Right now you can do this:

```
phrase "titles"
	word
		" of All"
		" of Old"
		" of the Stars"

phrase "names"
	word
		" Henry"
		" Nelson"
		" Randall"

phrase "civilian"
	word
		"Lord"
		"Prince"
		"King"
	phrase "names"
```

And "civilian" will generate names like "Lord Nelson" and "King Randall."

I'd further like to be able to do something like this:

```
	phrase "names" + "titles"
```

And then it will do a union of names and titles and select randomly from that set, potentially giving you "Lord of Old" as well as "King Randall". Why not just add the titles to the end of the names list, like they are now? Because then you can't re-use the names list for other combinations where "of Old" wouldn't make sense (such as "Poor Randall"; "Poor of Old" doesn't parse).

**Comment by endless-sky** [comment]
In commit 6401919 I've changed it so that "phrase" can take a list of any number of phrases to choose between, the same as how "word" takes a list of any number of words.

Note that what you were asking for was technically already possible without that change, but only in a roundabout way, e.g.:

```
phrase "names and titles"
    phrase "names"

phrase "names and titles"
    phrase "titles"

phrase civilian
    word
        "Lord"
        "Prince"
        "King"
    phrase "names and titles"
```

**Comment by Pointedstick** [comment]
Wonderful! Gonna go make some fun changes…

**Comment by Pointedstick** [comment]
This works beautifully.
