### ISSUE TITLE
Flight checks don't point to the proper ship

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1538]
My Bactrian, completely fine.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/18413243/21961928-7770-11e6-8e25-791434cfb2f2.png)
My Mule, which is overheated.
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/18413244/2953c462-7770-11e6-8ce9-3d31b04154b4.png)
But the flight check says it's my Bactrian that is overheating.
![screenshot_3](https://cloud.githubusercontent.com/assets/17688683/18413245/3090c5cc-7770-11e6-9b99-ebaa5290fe5c.png)

**Comment by endless-sky** [comment]
It works fine for me. Did you rebuild the code, or just update the data files?

**Comment by Amazinite** [comment]
I rebuilt from the latest code.

**Comment by Amazinite** [comment]
Okay, so I built the code from source again just to make sure something hadn't messed up in the process the first time, and it works properly now. But I went ahead and tried something different; to have two different ships with two different problems. The Mule still overheating, a Quicksilver with no engines, and my Bactrian completely fine. I try to leave the outfitter and it gives me the no engines conversation but points towards my Bactrian now.

**Comment by KiLEdEnNis** [comment]
maybe that recent pull from MZ that changes "your ship" to <ship> will automatically use the flagship name?

**Comment by endless-sky** [comment]
I've tested it with a bunch of different configurations (which problem I introduce, and on what ship) and it always names the correct ship for me. So I'm not sure what could be wrong.

**Comment by Pointedstick** [comment]
Can you paste in a link to your save file, @Amazinite?

**Comment by Amazinite** [comment]
No changes to the .exe that I was running on and everything seems to be working properly now. Not sure why it wouldn't have been working in the first place, but here's my save file anyways.
[Enigmac  .txt](https://github.com/endless-sky/endless-sky/files/466307/Enigmac.txt)

**Comment by toilethinges** [comment]
Working fine for me, with your save file. It's probably like my dumping outfits issue, where flotsam boxes weren't appearing after a while of playing, until I re-compiled.
