### ISSUE TITLE
The most profitable commodity to buy should be highlighted

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1539]
Which commodity should I buy?

<img width="171" alt="screen shot 2016-09-10 at 4 18 31 pm" src="https://cloud.githubusercontent.com/assets/1097249/18413821/3c427f12-7772-11e6-8ba0-05cf41a02884.png">

Looks like food. Took me a couple seconds to parse because not only was it not highlighted, but my current selection was. It would be nice if the most profitable commodity could be somehow highlighted in a manner that was still distinct from your current selection.

**Comment by endless-sky** [comment]
This is a duplicate of #1118. My worry is that if trading is made too "automatic," the player won't have any sense of agency - basically, the game would be telling the player, "this is the commodity you're supposed to buy," and that leaves even less for the player to actually do themselves.

**Comment by Pointedstick** [comment]
Fair enough. I see your point.

**Comment by KiLEdEnNis** [comment]
side note, buy the industrial
