### ISSUE TITLE
unable to repair damaged craft

### ISSUE THREAD

**Issue by mischief** [endless-sky/endless-sky#154]
hey, running 9db3fb2acfe306077da469dcfb436a2f3fa23470 on `Linux delta 4.1.6-gentoo #2 SMP Sun Aug 30 16:02:02 PDT 2015 x86_64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz GenuineIntel GNU/Linux`.

i played for a few hours, and got two additional freighters. they were both damaged by attacking pirates, but my "primary" freighter got away. it is unclear how to repair these additional ships in my control, or if repair of them is even possible. any ideas?

![ships](http://i.imgur.com/nIxzgJ7.png)

**Comment by endless-sky** [comment]
If the pirates didn't board them and yank out their engines or power generators, you can repair them by boarding them (target them and press B). You can check in the info panel whether they still have all their equipment.

**Comment by nebruin** [comment]
If they are missing their engines how do you fix them?

**Comment by wkoot** [comment]
Same problem here. They actually do have hyperdrive but not an engine, so they cannot get in line to jump to the neighbouring system which has an outfitter :(

**Comment by endless-sky** [comment]
If a ship has been scuttled by pirates removing key outfits, there's no way to get it working again. As of 0.8.7, pirates just never steal outfits, because way too many players were getting confused by that.
