### ISSUE TITLE
The Eye does not have a wormhole "link" on the map

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1540]
Unlike the Ultima Thule-Waypoint wormhole, when you pass through the Eye, it does not show a purple line on the map connecting Sko'karak to Sabriset.
confuse

**Comment by endless-sky** [comment]
Fixed in 332816a.

**Comment by Bladewood** [comment]
Actually, keeping this open, just for a few more minutes at least, so that others can see it.

**Comment by Bladewood** [comment]
Okay, I think enough time has passed.
