### ISSUE TITLE
Derecho outfits are not for sale even after Derecho mass production event

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1542]
Only red, yellow, and white suns are available after the Derecho enters mass production, even though the Derecho itself ships with a blue sun.
On that note, the Wanderer heat sink is not available either.

**Comment by endless-sky** [comment]
Fixed in d1cb528. You'll have to manually add the change to your saved game, though.

**Comment by Bladewood** [comment]
くそ!
I don't like to edit my main save :(
Also, as warp-core commented, you did not add the heat sink.

**Comment by Bladewood** [comment]
Closing because commit https://github.com/endless-sky/endless-sky/commit/a208f459238b379e239d18ac3ed25334e7671796 happened.
