### ISSUE TITLE
EndlessSky.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by Lineth** [endless-sky/endless-sky#1544]
`The procedure entry point _ZNKSt7__cxx1112basic_stringlcSt11char_straitslcESalcEE3endEv could not be located in the dynamic link library C:\msys\home\-omitted-\endless-sky\EndlessSky.exe.`

I tried following the Build Instructions and even what I could find [here](https://groups.google.com/forum/#!topic/endless-sky/j4JENYCIbSU).

I'm honestly stumped. I copypasta'd the libraries from multiple sources: the download on the BuildInstructions page, the Steam release, and the ones in the bin file on my MinGW; none of them worked; same error each time. I even tried running the file from it's original directory in bin/Debug with the dlls in there. Nope. What am I doing wrong?

**Comment by Wrzlprnft** [comment]
Um, i can't help you, but maybe i can ask the right questions so more experienced people have a easier time doing so.

When exactly does the error occur? While running or while compiling and building?

Have you successfully used the compiler before? If the error occured while trying to run the game, but everything before worked out without error messages, maybe something went wrong while installing the compiler.

What OS do you use exactly and which libraries did you choose? Maybe theres a mismatch you did not notice.

I just try to help without really being able to, though

**Comment by Wrzlprnft** [comment]
What i wanted to ask with the first question (since the error seems to occur while starting/running): can you compile without error?

**Comment by Lineth** [comment]
It shows up when I try to run the file, I.e. run the game. This was after I got the file to compile in the first place (that was mostly me figuring out how Code-Blocks worked in the first place). Without the DLLs, it gives the expected errors. I have Win10 64-bit. Libraries, as I said, I used what I could find. All of them had the same problem.

The compiler works, yes.

**Comment by Lineth** [comment]
Your second question came in as I was answering the first, if the format of that post is confusing, heh.

**Comment by uknesvuinng** [comment]
I literally just encountered the same problem (trying to solve it was how I found this thread).  The solution is annoyingly simple (or at least it annoyed me when I finally realized what was wrong).  First, open up the dev64\bin directory in the development libraries download on the Build Instructions page.  Copy all those DLLs to the same directory as the EndlessSky.exe.  Next, go to your mingw directory, and into the bin subdirectory within it (program files\mingw64\bin, for example).  You should see a bunch of exes (gcc.exe, g++.exe, etc); you should also see some DLLs.  Copy libgcc_s_seh-1.dll, libstdc++-6.dll, and libwinpthread-1.dll from this directory to the EndlessSky.exe directory.  It will overwrite the dll's you got from the dev64 download, replacing them with the dlls you compiled against.  After that, it should work.

**Comment by Lineth** [comment]
Nope. Didn't work.

**Comment by Lineth** [comment]
GOT IT TO WORK!

Turns out the problem was with the nonstandard mingw install I have (the files it wanted were scattered all over).

Thanks to  uknesvuinng. His instructions helped quite a bit.
