### ISSUE TITLE
Is it possible to complete the Story by editing game saves?

### ISSUE THREAD

**Issue by The-Borg-Captain** [endless-sky/endless-sky#1545]
I'm wonder if there's a way to complete the story line by cheating to test stuff

**Comment by Pointedstick** [comment]
Yep.

**Comment by The-Borg-Captain** [comment]
Could you say how or message me how?

**Comment by Pointedstick** [comment]
This is a conversation more suited for the Steam forums than the github issue tracker. Try there.

**Comment by The-Borg-Captain** [comment]
Ok

**Comment by Alkallid** [comment]
I don't think you did that, I'll just add here that the story is marked as names, and have a done or not done tag. If you added the mission names in your save file and just wrote done behind them, boom, you're done. You could this way finish the last mission in the story and then start it.

**Comment by KiLEdEnNis** [comment]
@Alkallid although events didn't happen then, which is the downside
