### ISSUE TITLE
[content/bug] Possible slight logic error in fine wording

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1547]
...I guess this is my punishment for having Nerve Gas...
http://steamcommunity.com/sharedfiles/filedetails/?id=762123129

It kind of can make sense, but seems a bit weird to me.

**Comment by Bladewood** [comment]
I mentioned this a long time ago, but nobody noticed apparently :(

**Comment by Pointedstick** [comment]
I don't see a grammatical issue, but agree that it's a bit awkward. Maybe it should be "The wanderer authorities" or something.

**Comment by toilethinges** [comment]
If you added "authorities" after the government name in a fine, it should make sense in all cases:

Republic authorities
Free Worlds authorities
Syndicate authorities
Kor Efreti authorities
Wanderer authorities
Alpha authorities (haha)
Hai authorities
Hai (Unfettered) authorities

**Comment by Pointedstick** [comment]
Easy fix. Made a pull request: https://github.com/endless-sky/endless-sky/pull/1548

**Comment by endless-sky** [comment]
Merged #1548.
