### ISSUE TITLE
Metagame: "Firefly mode" and especially "Star Trek mode" need to be more interesting

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1549]
I've seen Michael Z say that he intends for this game to have three basic styles/tones: "Firefly mode", "Star Wars mode", and "Star Trek mode."

## Star Wars mode ##
Star Wars mode is well fleshed out with the major plot lines and it gets better all the time as more content is added. It's incredibly fun and it really shines.

## Firefly mode ##
Firefly mode is significantly weaker and shorter because it's very easy to overcome the basic limitations of the start of the game: your mortgage, small ship, and dangerous space pirates. Opting for a combat-focused beginning can jump you past Firefly mode in about half an hour minutes due to how inappropriately lucrative it is to sell captured outfits. Even if you pick the peaceful path, within an hour or two you're flying around in a much better ship with significant upward mobility. There's also a paucity of truly interesting missions available to pilots of meager abilities. It's very grind-ey. Firefly mode was a bit more fun in the old-skool Escape Velocity games because for a variety of reasons it lasted longer and was a lot harder, giving you more of a challenge to overcome and more exposure to low-level missions you could do.

## Star Trek mode ##
But the weakest of all is Star Trek mode. Once you've completed all the missions, have a billion credits, and are flying around in a fleet of Bactrians, the game becomes rather boring. Once you tire of killing pirate fleets, farming aliens, and dominating planets, there's nothing to _do_. There are no gravimetric anomalies to investigate; no mysterious alien traps to escape from; no crystalline entity to humble even the toughest fleet; no parts of the galaxy that are accessible but so mysterious and dangerous that nobody sane goes there. This is why I dropped off the map for a few months. I basically won the Star Wars mode game, quickly got bored with what was available in the sandbox of Star Trek mode, and drifted away, only returning because I was excited by all the new content added since I left.

The nature of this type of game attracts optimizers and systems-thinkers who will quickly reach maximum power. The big risk is that once they get there, the game turns boring. The galaxy needs to somehow be more _interesting_ to retain people in Star Trek mode. Putting aside the character drama which is an awkward fit for this type of game, Star Trek is enjoyable because of all the cool space stuff for the Federation to explore. That's really what's missing from this game: neat space stuff to look at, investigate, and explore once you enter the post-scarcity phase of your captainship. Endless Sky's galaxy needs more excitement and mystery to it to be more alluring for explorers.

**Comment by jafdy** [comment]
In short you want more content. Yes?

**Comment by Pointedstick** [comment]
I see where you're going with this… and yes! I wanted to start a conversation about what **kind** of content, because I'm willing to create stuff, but only if it will be accepted because it fits with the direction of the game as Michael envisions it.

There are also potential improvements to Firefly Mode that don't involve new content (e.g. https://github.com/endless-sky/endless-sky/issues/1535, https://github.com/endless-sky/endless-sky/issues/275, https://github.com/endless-sky/endless-sky/issues/329).

**Comment by Pointedstick** [comment]
I think this came off as too negative though. I'm going to close it and open smaller, more targeted issues.
