### ISSUE TITLE
Particle and Plasma Cannons not firing at certain angles.

### ISSUE THREAD

**Issue by FinalCatch** [endless-sky/endless-sky#155]
I'm having trouble getting my Particle cannons and Plasma cannons to fire. But only at when my ship is pointing at certain angles, by pressing TAB. My Heavy Laser Turrets fire forward and at all angles at command. They seem to fire at 0, 45, 90, etc but not in-between. The lasers have no such problem. 
I'm sure that Energy and Heat are not an issue. (i have not batteries but more energy generation and heat capacity  that both my engines and guns need/produce. the heat gauge is very low. ) But I can post a save if you need to check. 
It might be some bug with the auto targeting. However I've also noticed t

hem not firing in battle too. Is this a known issue. Should I just switch to lasers heavy lasers or something instead?

**Comment by endless-sky** [comment]
I'm really not sure what could cause this. Is it possible to upload your saved game file?
