### ISSUE TITLE
Give Quarg ships hull repair outfits

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1551]
Because Korath disruptors.

Also, it doesn't make sense for us to be able to loot OP shield generators without being able to loot OP hull regenerators.

Also, we need something to take up that 80 outfit space in their ships after you removed the Antimatter Core.

Also, they should have developed _some_ kind of hull repair technology after being attacked by the Pug with gridfire turrets, right?

**Comment by KiLEdEnNis** [comment]
the Quarg didn't get attacked by Pug gridfire turrets, did they?

**Comment by Bladewood** [comment]
After reading the Arfecta's description, I would assume that they did.

**Comment by Bladewood** [comment]
Also, give Quarg ships ramscoops, so that they can't get trapped in Mesuket or something.

**Comment by tehhowch** [comment]
Ramscoops were added in 674a6d04ade5c4098ce80aab3df91f2ffb11377e
Dedicated hull repair outfits can probably be added in the eventual rebalance, while a sprite for one could be made in #3536 
Until that rebalance, baked-in `hull repair rate` could be added.

**Comment by Lineth** [comment]
For the ramscoop, I like the idea of their ramscoop being integrated into their (hopefully) reintroduced and rebalanced reactors.
