### ISSUE TITLE
Text system doesn't handle accented characters

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1554]
In e8038ad22769b05ba62900460566ec0f74750a70, I added the word "naiveté." Here's how it appears in the game:

<img width="246" alt="naivete" src="https://cloud.githubusercontent.com/assets/1097249/18443328/a6e24d56-78d1-11e6-94b3-ea02dcfa8fdb.png">

This will obviously be a major issue if the game is ever to be localized.

**Comment by retrue** [comment]
That is an old issue. The game was designed without considering other languages than English and adding accents or the whole UTF8 or UTF16 sets of characters would need to change the whole way the game use to represent text in the game. It seems it is a lot of work.

**Comment by Wrzlprnft** [comment]
Umm, there are already issues about it. I just can't give you a link since i am on phone and preparing dinner. Search for "non Ascii" letter support or so. I am sorry.

**Comment by jafdy** [comment]
#1090
#201
