### ISSUE TITLE
Pug Maboro Engines [minor]

### ISSUE THREAD

**Issue by natangold** [endless-sky/endless-sky#1558]
Right now the Pug Maboro has its engine sprites (engine ±11 68) showing up near(ish) the middle of the ship. I don't know exactly how it works, but just by eyeballing it looks better (to my eyes) when the second value is doubled (to engine ±11 136).

**Comment by endless-sky** [comment]
Yup, that's definitely a mistake. Fixed in f85e7b8.

**Comment by Bladewood** [comment]
Wait, you mean that was a mistake!?
It looked like a brilliant little trick to me.

**Comment by KiLEdEnNis** [comment]
that feel when no one noticed before :/

**Comment by natangold** [comment]
> that feel when no one noticed before :/

…when no one was OCD enough to notice it out before…

**Comment by KiLEdEnNis** [comment]
I always kill them too quickly to notice

**Comment by Bladewood** [comment]
I noticed, but I thought it was intentional, so I didn't mention it.
