### ISSUE TITLE
Zug planet landscape image is not showing

### ISSUE THREAD

**Issue by craigmccauley** [endless-sky/endless-sky#156]
When I land on Zug the planet landscape image is not there I just see the frame.
Windows 7 64-bit

![image](https://cloud.githubusercontent.com/assets/7706831/11010961/9c22990a-84a0-11e5-9dd5-5b2b1120db31.png)

**Comment by kyzentun** [comment]
This doesn't happen just on Zug, this can happen on other planets too.  I've seen it also happen on Mars.  It's also not Windows specific, the same problem can occur on Linux.

**Comment by endless-sky** [comment]
To save memory, the game only pre-loads up to 20 landscape images. Sometimes in a system with multiple planets, it ends up not loading one of them. I've checked in a code change to fix that (7b0d801), so it will be part of the next release.

**Comment by endless-sky** [comment]
This is the same as bug #209.
