### ISSUE TITLE
Cluttered text in ship info screen

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1560]
When a ship has many outfits, the name of the outfits is not displayed correctly on the ship info screen. Text is superimposed on top of other text and it becomes illegible. Possible solutions would be using the fourth column of text that is empty or with just some lines of cargo, adding a fifth column of text or a scrollbar.
I include a couple of pics.
![text1](https://cloud.githubusercontent.com/assets/18194241/18475721/d4b95c00-79c7-11e6-9079-24eb27beaf83.png)
![text2](https://cloud.githubusercontent.com/assets/18194241/18475733/dcfd9110-79c7-11e6-9943-7d0abdddcd37.png)

**Comment by Amazinite** [comment]
Duplicate.

**Comment by Amazinite** [comment]
#972

**Comment by KiLEdEnNis** [comment]
the outfits could be moved to the far right though, I suppose

**Comment by retrue** [comment]
I want to point out that this is the vanilla version of the game. No plugins here.
The far right is reserved to cargo, but imho it would be weird that a ship has so many different types of cargo as to fill the whole far right column.

**Comment by Amazinite** [comment]
Stil a duplicate.

**Comment by endless-sky** [comment]
Closing this because it's a duplicate. But, I'll try to work on this this weekend.
