### ISSUE TITLE
Wanderers ships are indistinguishable of your own wanderer ships

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1561]
When you buy or capture a ship it takes the colour of your fleet, but when you purchase a wanderer ship, your wanderer ships are indistinguishable of the other wanderer ships. There is not change of colour. I don't know if it is intentional or it is not.
As an example, one of my Deep Rivers beside a wanderer Deep River.
![deep rivers](https://cloud.githubusercontent.com/assets/18194241/18477392/cff4c2b2-79cd-11e6-8b96-03c00ac0f6b5.png)

**Comment by Amazinite** [comment]
/My ships aren't easily distinguishable from other Free World ships when there's a bunch around, or Merchant ships before you join the Free Worlds.

**Comment by Quantumshark** [comment]
This is because wanderers use the same colour as free worlds (and therefore players who have joined the free worlds)

**Comment by retrue** [comment]
Well, in that case, Wanderer ships colour should be changed to a different shade.

**Comment by jafdy** [comment]
There are only 6 Swizzles and I don't think more will be added. The same problem will crop up with Syndicate/unfettered Hai and Republic/Hai.

**Comment by KiLEdEnNis** [comment]
there is an unused swizzle, similar to the FW (greenish), maybe it could be that...?
(it should really be used, I love that swizzle)

**Comment by Amazinite** [comment]
All swizzles are used in game; the teal one is used for Test Dummies.

**Comment by KiLEdEnNis** [comment]
test dummies are shown like 2x, once of which is on the Kestrel; it uses no(?) swizzle
an actual government should get it, alien or human

**Comment by jafdy** [comment]
The Kestrel can't be swizzled. The sprite has noting that is some shade of red/orange/yellow.

**Comment by retrue** [comment]
I noticed that none of the Wanderer ships can be swizzled either. They have nothing that is red/orange/yellow.

**Comment by jafdy** [comment]
They can be swizzled
![derecho](https://cloud.githubusercontent.com/assets/15716454/18504480/59afcde4-7a5a-11e6-8fca-7abe741f6027.png)
 The brown gets swizzled to green.

**Comment by Amazinite** [comment]
It's not that the ship requires red-orange-yellow to swizzle, that's just the default colors used for swizzling. As long as it isn't black-grey-white, it will swizzle in some way.

**Comment by Bladewood** [comment]
Fun fact: The Kestrel is not a *perfect* shade of grey. If you go into the ship editor and try to swizzle it, you will notice tiny differences in color.

**Comment by KiLEdEnNis** [comment]
not enough to actually notice it though
