### ISSUE TITLE
"Conversation" doesn't seem to work inside an "on accept" block

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1562]
This doesn't work:

```
    on offer
        conversation
            `Do you want to gamble with some pirates?`
            choice
                `(Join their game.)`
                    accept
                `(Ignore them.)`
                    defer

    on accept
        conversation
            `   You gamble with the pirates!`
            ...
```

[The docs](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#conditions) seem to indicate that this should work:

```
on (offer | complete | accept | decline | defer | fail | visit | stopover | enter [<system>])
    dialog <text>
        <text>...
    conversation <name>
    conversation
        ...
```

**Comment by endless-sky** [comment]
This should be fixed by commit 1816039.

**Comment by Pointedstick** [comment]
Oh sweet! Now I can finish my pirate gambling mission!

**Comment by Pointedstick** [comment]
Hmm, or not. Looks like I still need either https://github.com/endless-sky/endless-sky/issues/1563 or https://github.com/endless-sky/endless-sky/issues/1564. Still, thanks!

**Comment by Elyssaen** [comment]
@endless-sky, I can't seem to get this to work. I've tried exactly the structure @Pointedstick was talking about, but the `on accept` conversation doesn't appear. What's the state of this at the moment?

**Comment by endless-sky** [comment]
Right now jobs can pop up a dialog when they are accepted, but missions offered somewhere other than the job board can't. Basically the only reason you would want to do that is if you want to show a dialog to offer the mission and then a conversation after it is accepted, or vice versa. And in that case I think just showing it all in a single conversation makes more sense.

**Comment by Elyssaen** [comment]
Ah, right. If it stays that way, you might save yourself some time if you could stick a note on the Wiki, as I imagine this'll confuse people again.

Just to say, sometimes things get really tricky (as @Pointedstick said, "fighting the system" in #1564) when you try to get creative with `payment` and `event` in conversations. I've given myself a headache over this a few times, and I can't remember right now if 'conversation on accept' is _necessary_ to making some of these creative things possible, but I know it often looked like it'd help.
