### ISSUE TITLE
Hauler III + Skein + Roost Assets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1565]
In the Google Drive folder, there are two .xcf files for the Hauler III, but no .blend file.

**Comment by KiLEdEnNis** [comment]
about the Roost, Nest and Skein; their .blend is literally empty btw
(at least when I checked it)

**Comment by endless-sky** [comment]
Fixed the Hauler III. It looks like I had uploaded a new .xcf, but
accidentally deleted the .blend instead of the old .xcf.

**Comment by Amazinite** [comment]
I'm also getting errors when trying to open skein.blend and roost.blend, but nest.blend is fine.

**Comment by KiLEdEnNis** [comment]
I don't remember the Nest being in the blend, but may be wrong myself, downloaded it (w/o checking) & it works

**Comment by endless-sky** [comment]
Looks like a Google Drive issue. I re-uploaded them.
