### ISSUE TITLE
Un-named ships in NPC description using "ship" don't get an appropriate random name

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1566]
Let's say I define a set of NPC ships like this:

```
	npc
		personality
			heroic
			plunders
			vindictive
			confusion 20
		government "Pirate"
		ship "Sparrow"
		ship "Sparrow"
```

Note that I haven't specifically given the ships defines names. I would expect the game to randomly choose appropriate names in this situation. Instead it names both ships "Sparrow."

**Comment by endless-sky** [comment]
How would it know which phrase you want to use for the names?

If you want a random name, just use "fleet":

```
npc
    personality
        heroic
        plunders
        vindictive
        confusion 20
    government "Pirate"
    fleet
        names "pirate"
        variant
            "Sparrow" 2

**Comment by Pointedstick** [comment]
I'm assuming it would know because of the government government (Pirate = pirate names). But that works, thanks.
