### ISSUE TITLE
Add an NPC personality that lets them take off from hostile planets

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1567]
I'm writing a mission that's like this:

```
mission "Pirate gambling"
    description "Gamble with pirates."
    minor
    repeat
    to offer
        "combat rating" < 10
        random < 10
    source
        attributes "dirt belt" south rim
    on offer
        conversation
            [bunch of stuff]
            `You blast off but the pirates are in hot pursuit!`
                launch

    on accept
        payment 23974
        fail

    npc
        personality
            heroic
            plunders
            vindictive
            confusion 20
        government "Pirate"
        ship "Sparrow"
        ship "Sparrow"
```

When you take off, the two pirate ships are there, as expected. But they didn't take off from the planet; they're already there. This is not what I expect to happen given the following passage in the documentation:

> If an NPC is specified as starting out in your current system and its personality is not "staying" or "waiting", it will take off from the planet along with you (e.g. a ship you are escorting)

**Comment by endless-sky** [comment]
If it's not a planet that they can land on, they won't be able to take off from it.

**Comment by Pointedstick** [comment]
That's disappointing. It prevents exactly the kind of situation I'm trying to set up.

**Comment by Alkallid** [comment]
It could mess up fleets, making things like a Falcon taking off from Smuggler's Den possible.

**Comment by tehhowch** [comment]
#3603 adds a personality flag (`launching`) that will supersede the other checks for landing ability. With it, you can make a Pirate armada launch from (the dark side of) Luna

**Comment by Pointedstick** [comment]
Done now with https://github.com/endless-sky/endless-sky/pull/3603.
