### ISSUE TITLE
[ENHANCMENT] Add "Turret Turn Rate" as a value for weapons

### ISSUE THREAD

**Issue by GalacticRuler** [endless-sky/endless-sky#1569]
as the title says, I feel that we could make use of a turn rate value for turrets, because it would make balancing huge firepower easier if it had to actually turn to hit the target instead of having a perfect tracking speed.

**Comment by GalacticRuler** [comment]
wait, seen a pull request with this in it. Never mind.

**Comment by KiLEdEnNis** [comment]
side note (besides duplicate) MZ stated that he doesn't want to penalize slow ships any further
