### ISSUE TITLE
"Provide security for pleasure cruise" mission's "on visit" text is misleading if you missed the waypoint

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#1570]
I landed at the final destination of a "Provide security for pleasure cruise" mission, and got the following message:

> You have reached Moonshake, but you left the Horizon Changes behind! Better depart and wait for them to arrive in this star system.

I spent a good five minutes trying to figure out why I was getting this message even though the Horizon Changes was most definitely in-system with me. I even did a convoluted hyperspace dance to arrange for Horizon Changes to be out of fuel and land on the planet ahead of me. Only then did I look more closely at the mission, and notice that there was supposed to be a stopover at Helheim.

I'm running a recent git build.

**Comment by endless-sky** [comment]
Fixed in 3bcd81e.
