### ISSUE TITLE
"Wanderers Pond Strider Recon"

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1572]
You changed the Pond Strider npcs to the Solifuge, but never changed the mission names.

**Comment by endless-sky** [comment]
I didn't want to mess up the missions for anyone who had already played through them. If the names changed, suddenly the missions would pop up for players all over again, which would be confusing.

**Comment by endless-sky** [comment]
Well... I guess it's easy enough to fix in a backward compatible way. 4f8a24d.

**Comment by Bladewood** [comment]
This mission still references "drones" and "drone carriers" in the completion description.

**Comment by endless-sky** [comment]
Switched it to "fighter" in 53552c0.
