### ISSUE TITLE
"Disown" crashes ship list (I) screen

### ISSUE THREAD

**Issue by majenkotech** [endless-sky/endless-sky#1573]
Immediately after you "disown" a ship the ship list (`I` from a planet menu) crashes. Not only that it is possible to crash the entire game that way.

* Land on a planet with an escort
* Press `I`
* Select a ship by double-clicking it
* Press `Disown`
* Press `OK`

Now you cannot interact with the ship list any more. You can press `Done` to get back to the planet menu, at which time you can go through the whole thing again with your next ship.

Instead of pressing `Done`, though, if you select the `Ship Info` tab instead (immediately after disowning a ship) the entire game crashes. 

    Program received signal SIGSEGV, Segmentation fault.
    0x000000000053674c in Ship::OutfitCount(Outfit const*) const ()

Of course, it hasn't saved your ship disownings by that point, so you end up with all your ships again.

**Comment by majenkotech** [comment]
Better debugging now I have built a debug version from source:

    Program received signal SIGSEGV, Segmentation fault.
    0x00000000004fab32 in Hardpoint::IsTurret (this=0x17400000113) at source/Hardpoint.cpp:81
81		return isTurret;
    (gdb) bt
    #0  0x00000000004fab32 in Hardpoint::IsTurret (this=0x17400000113) at source/Hardpoint.cpp:81
    #1  0x0000000000506087 in InfoPanel::DrawWeapon (this=0xa03ff80, index=0, pos=..., hardpoint=...) at source/InfoPanel.cpp:775
    #2  0x00000000005057e8 in InfoPanel::DrawShip (this=0xa03ff80) at source/InfoPanel.cpp:737
    #3  0x00000000004ff6f9 in InfoPanel::Draw (this=0xa03ff80) at source/InfoPanel.cpp:198
    #4  0x00000000006194ac in UI::DrawAll (this=0x7fffffffd370) at source/UI.cpp:129
    #5  0x000000000061fdde in main (argc=1, argv=0x7fffffffdcf8) at source/main.cpp:316

**Comment by endless-sky** [comment]
Fixed in 3dfe1de.
