### ISSUE TITLE
Random Major FPS Drops

### ISSUE THREAD

**Issue by XSaintsXWolfX** [endless-sky/endless-sky#1574]
Randomly When using a Hyperdrive to Jump from System to system, my game will go from running at a perfect 60 fps no problem, to a 20-30 fps until it randomly fixes it's self or i restart the game. This has nothing to do with the amount of planets in a system, the amount of ships, or the amount of asteroids, i have found out. It has occurred all throughout human space (haven't been able to get to any alien space yet due to this bug making it near impossible to do any sort of combat, as in slowness wise).

**Comment by jafdy** [comment]
Hyperdrive or Jumpdrive? Look at the outfit name.

**Comment by XSaintsXWolfX** [comment]
I did just update to prevent later confusion, but i did also state i hadn't seen any other alien species yet.

**Comment by jafdy** [comment]
Try removing the hyperspace flash. Change the 1 to a 0 in the preference file. USERNAME/AppData/Roming/endless-sky

**Comment by XSaintsXWolfX** [comment]
Apologies, left the house for a while. But it did not work. I don't think it's so much along Graphics wise, but something more like a process getting slowed down after Entering another System. Don't Quote me on this.

**Comment by endless-sky** [comment]
In the preferences, try turning on the CPU / GPU load display to see which
one is limiting the frame rate. If it's the GPU, you might also try turning
off motion blur to see if that changes anything.

If you have a relatively old GPU, it's possible that what is happening is
that when you enter a new system, it pre-loads the landscapes for any
planet(s) in that system and that is enough to push you over the limit of
your VRAM capacity. If so, you may be able to fix the problem by editing
your preferences.txt file and changing the "Reduce large graphics" value
from 0 to 1.

(Preferences files are one directory up from the saved games; see the Steam
FAQ for the exact path for each operating system.)

**Comment by XSaintsXWolfX** [comment]
Only had to jump once for the bug to occur, CPU stayed at a constant 2% and GPU went up for 3% for 5% that is all that occurred. Jumped again after i got those stats and it fixed it's self. GPU stayed at 5% and CPU Stayed at 2% Another thing i remember sometimes fixing, but only fixing, the glitch is if a lone ship jumps into the system i am in.

**Comment by XSaintsXWolfX** [comment]
I found what i do believe to be the Solution to this. I turned "Draw background haze" 1  to "Draw background haze" 0 and I did not experience this problem at all any more.
