### ISSUE TITLE
Just captured fighters cannot dock in the flagship.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1576]
Version 0.93. I have been trying to capture Kor Sestor and Kor Mereti ships. When I capture Far Osk 27s with my Bactrian that is not carrying any fighter at the moment, I can't take the Far Osk home because it doesn't obey the recalling order (pushing D). I didn't have any problems doing that in version 0.92.

Edit: I just checked and Far Osk 27s captured in version 0.92 can be deployed or recalled without problems.

**Comment by retrue** [comment]
I have changed the title of the bug report because I have been doing tests and I have discovered new things.
I wanted to know if the problem was related only to Far Osk 27s or not, so I decided to capture Korath Chasers. My flagship was a Bactrian. My scorts were 2 Bactrians, 3 Shield Beetles and 3 Korath Raiders. That would allow me to capture up to 15 Korath Chasers in a single raid (3 Chasers for each Bactrian and 2 Chasers for each Korath Raider).
I didn't have problems recalling the first 12 Chasers I captured. They could be deployed and recalled without problems. But I couldn't recall the next 3 Chasers I captured. **The just captured fighters can dock in the scort ships but they cannot dock in the flagship.**

**Comment by KiLEdEnNis** [comment]
it MAY be related to an issue where enemy fighters/drones tried (and succesfully) docked in the flagship #1333 
not sure though, just trying to help

anmyway, do the captured fighters TRY to dock in you, or do they ignore the flagship? if it's the latter, it's probably related

**Comment by retrue** [comment]
I think they ignore the flagship. They don't try to dock in the flagship, but if there are enemies around, the capturers fighter will attack them.

**Comment by KiLEdEnNis** [comment]
then I'd say it's related to issue 1333

**Comment by endless-sky** [comment]
I can't duplicate this: in 0.9.3 I'm able to capture fighters (including Chasers) and have them dock with my flagship.

**Comment by retrue** [comment]
I will prepare tomorrow a save file.

**Comment by retrue** [comment]
Ships are in Sheratan. The flagship is a Bactrian. Among the scort ships there is a Raider. Just depart and go to Kor Ak'Mari and capture chasers. First two captured chasers will dock in my Raider. Next captured chasers won't dock in the flagship.

[Doc Figure~Kor Ak'Mari Fighters.txt](https://github.com/endless-sky/endless-sky/files/479814/Doc.Figure.Kor.Ak.Mari.Fighters.txt)

**Comment by Lineth** [comment]
I've had similar issues with Sestor Fighters not docking with my Bactrian. Chasers worked, but Sestor drones didn't.

**Comment by jafdy** [comment]
The drones can only dock with ships with drone bays.

**Comment by Lineth** [comment]
Well that seems a bit silly, IMO.

**Comment by retrue** [comment]
I don't know why it seems that other people is not having this problem because the save file that I have used for my tests has been created using exclusively the version 0.92 of the game: no plugins, no edition of the save game. I load that save game with version 0.92 of the game and my flagship can capture fighters and dock them immediately. I load that save game with version 0.93 and it cannot.
So I have been having fun. I wanted to locate the commit that introduced this bug and I have been successful.
I have been downloading and compiling different versions of the code. At first I thought the problem was the commit to solve issue #1333. But that was not the problem. Docking of captured fighters in the flagship worked before and after that commit. So I read the description of the next commits until I found this commit on August 9: Little fixes, hails, volume, fighters and drones ( #1417) 
[](https://github.com/endless-sky/endless-sky/commit/11774348c22c72acf2608960ccb470fa16d05e4a) more concretely the changes in the file  source/AI.cpp
In the game compiled up to the previous commit docking works well. In the game compiled with this commit, docking in the flagship doesn't work when you are capturing fighters.
In fact, I have downloaded the source code of version 0.93. I have edited the file AI.cpp reverting the changes introduced in the commit. I have compiled and the bug is fixed.

**Comment by comnom** [comment]
@retrue Sorry to (possibly) semi-hijack the issue here, but can you explain the behavior of the fighters that won't dock? I've been trying to track down an issue in my mod where AI fighters and drones seem to get orphaned and drift forever. I thought they were getting disabled and knocked away at first but testing shows they're active(max hull with a blue outline in the target display). It's making the motherships hang in the system indefinitely and I can't track down why.

**Comment by endless-sky** [comment]
Commit a2b60de should fix this. The issue was that the code to assign a fighter to a carrier checks how many fighter escorts the carrier already has, so if the fighter has already been assigned to that carrier it thinks it has no room for more escorts.

**Comment by Amazinite** [comment]
@comnom I think some of your fighter/drone variants only have weapons on them.

**Comment by retrue** [comment]
I have just compiled in Linux the last development version (this last commit included) and the problem with fighters seems solved. Fighters that I capture dock in the flagship.
Thanks.

**Comment by comnom** [comment]
@Amazinite ...You are quite correct there. Move along nothing to see here then.
