### ISSUE TITLE
In Hai space, merchants flying Hai ships should also appear

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1577]
If we can buy Hai ships, why aren't other humans seen flying them? Is it because of the price?

**Comment by SolraBizna** [comment]
I've never flown the Hai cargo ships because they're extremely expensive for what they do. Maybe the AI merchants feel the same? :)

**Comment by Bladewood** [comment]
What about the shield beetle?

**Comment by Amazinite** [comment]
Or at least some variants of human ships using Hai outfits?

**Comment by ldsgsm** [comment]
Humankind is quietly aware of the Hai--that's why the Republic has such a strong presence posted northeast (according to nice Republic guy whose name I can't remember). This makes a lot of sense to me.

**Comment by Amazinite** [comment]
The Navy knows, but most of humanity does not.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
