### ISSUE TITLE
Pond Strider carrier and Flea drones are no longer available

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1579]
Before the solifuge patch, the only way to obtain pond striders, flea drones, and railguns, was by disabling and capturing them from the Unfettered. Now, they are completely unobtainable, as far as I can see.

**Comment by Amazinite** [comment]
That's probably because they're coming in the next story update, same as the Hurricane. Plus, Pond Striders are for the Hai, not the Unfettered.

**Comment by endless-sky** [comment]
Pond Striders and Fleas get added to the Unfettered fleet in the course of the Wanderer missions, as of 0.9.4.

**Comment by KiLEdEnNis** [comment]
aren't those the solifuges & their fighters instead?
