### ISSUE TITLE
Poisonwood Liberation, misleading message

### ISSUE THREAD

**Issue by stainfree** [endless-sky/endless-sky#158]
![bugss](https://cloud.githubusercontent.com/assets/3598068/11012994/6ffd3210-84cb-11e5-81cc-b1bd44256fef.png)

I was on the mission to liberate Poisonwood from the alphas, and I got this prompt once I had dealt with enemy ships.  It says I left the dreadlord in another system, but I hope you can see from my screenshot that all my escorts were in the same system.

I eventually I found out I had left a single disabled enemy ship in the system and that was preventing me from completing the mission.

I looked briefly at "free worlds middle.txt" and I'm not sure but it looks like this message is always triggered when visiting the destination planet without completing the mission, so I'm not sure how to resolve this other than having more detailed messages and triggers, or by considering disabled ships as destroyed when deciding mission completion.  Other than that, great game so far.

**Comment by endless-sky** [comment]
Yes, when I was adding messages to any mission with incomplete NPC conditions, it seems that some of the messages were inaccurate. Fixed in c62b7e0.

**Comment by stainfree** [comment]
Looks good!
