### ISSUE TITLE
Reverse thrusters no longer used when jumping or landing

### ISSUE THREAD

**Issue by philipandresen** [endless-sky/endless-sky#1583]
I saw that this feature was implemented in a version 0.8 release, but as of version 0.92 AI controlled maneuvers for landing and jumping are using steering/forward thrusters to stop instead of using reverse thrusters when they are equipped.

I haven't played the game in a while, but last time I played this was working normally.

Ship type: Blackbird
Reverse thrusters used: AR120 Reverse Thruster
Other thrusters equipped: A375 Atomic Steering, Impala Plasma Thruster

Behavior: Ship turns around to stop between jumps, lengthening jump intervals.
Expected: Ship slows with reverse thrusters, allowing for shorter jump intervals.

**Comment by jafdy** [comment]
Chances are it is taking the shortest time between jumps. To check swap the Impala for something weaker or as weak as the 120.

**Comment by philipandresen** [comment]
So I made 4 jumps with the impala, loaded my game, swappped the impala for the x1050 ion engines (1440 thrust vs the 127,440) and I made the same 4 jumps. 

With the X1050 the AI used the reverse thrusters and got to my destination about twice as fast. We're talking 7 seconds per jump with the impala, and 4 seconds with the X1050.

Perhaps it does not account for the time it takes to turn around, and only looks at the power of the thrusters themselves?

**Comment by retrue** [comment]
Check time needed to jump with the Impala or X1050 but without reverser thrusters and you will know.

**Comment by philipandresen** [comment]
It takes the same amount of time without the reverse thrusters, (did a different sequence of jumps, 18 seconds to make three jumps with both the implala and with the X1700 (I'm at a different outfitter now). 

It takes 13 seconds with the X1700 and reverse thrusters, but still 18 seconds with the impala and the reverse thrusters.

Perhaps this is actually just a balance issue - because reverse thrusters don't contribute to my max speed and I always jump in at my max speed, having a beefy reverse thruster and a wimpy forward one makes jumping a ton faster.

**Comment by jafdy** [comment]
You can jump in slower than max speed but it's hard to get a ship that is fast enough for that. 
Try keeping the Impala and swapping the steering thrusters, I forgot about the max speed thing. 
I normally use them on bulk freighters so I can cut out the scram drive and keep a good jump speed. My experience of them tend to be quite good.

**Comment by philipandresen** [comment]
@jafdy That doesn't address the issue that the AI is not utilizing the reverse thrusters properly.

**Comment by jafdy** [comment]
The max speed and the different masses will sque the results so the best way of testing is to try the AI's way and your way by hand to see if there is a difference. I don't think this needs changing, I just expect your over estimating the power of the reverse thrusters.
