### ISSUE TITLE
After giving electron beam to Freya, departing and landing again gives electron turret to Freya

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1585]
I have a ship.
I used it to disable and capture a gunboat.
I later sold the gunboat and equipped my ship with the two electron beams and the electron turret.
I went to Trinket and Freya took one of my electron beams. Nothing wrong there.
Then I went to Zug to take command of the dreadnought + flamethrower fury fleet.
Then I came back to Trinket.
Freya took my electron turret.
confuse

Save while I was on Zug provided. [Alpha Omega.txt](https://github.com/endless-sky/endless-sky/files/478448/Alpha.Omega.txt)
Below line 2058, we have this:
> "FW Southern Recon 1: done"
"FW Southern Recon 1: offered"
"FW Southern Recon 1B (Turret): active"
"FW Southern Recon 1B (Turret): offered"
"FW Southern Recon 1B: done"
"FW Southern Recon 1B: offered"

I think something weird is going on, because [you clearly tried to prevent this](https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20middle.txt#L176).

**Comment by KiLEdEnNis** [comment]
I think I see the problem
the FW Southern Recon 1B and the (turret) version should have to offer: not [each other]'
so:
FW Southern Recon 1B
to offer
not "FW Southern Recon 1B (Turret)"

FW Southern Recon 1B
to offer
not "FW Southern Recon 1B"

that's it right?

**Comment by jafdy** [comment]
Once the the mission is failed you should be unable to accept it. I've looked at the code and can't find any problem with it.

**Comment by endless-sky** [comment]
The issue was probably that you did the Electron Beam mission before I pushed that update. Then, when you go back there, the other mission triggers. Commit 71ac1d7 should prevent that.
