### ISSUE TITLE
Payment calculation algorithm sometimes doesn't work properly for uncharted routes

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1586]
A picture says a thousand words:

<img width="641" alt="problem" src="https://cloud.githubusercontent.com/assets/1097249/18611753/3635ddfa-7d01-11e6-8f1c-b0a7e70cc4f0.png">

This is a new mission I'm writing, for which the payment is:

```
	on complete
		payment
		payment 10000
```

No way 14,500 is enough. Around 11 jumps each way with 30 tons of goods should pay something like 100,000 credits (11*2*30*150 = 99,000).

This doesn't always happen, and I haven't been able to figure out a pattern.

**Comment by endless-sky** [comment]
5c98f1a should fix this. The travel distance calculation was previously only including stopovers given by name, not stopovers chosen randomly with a filter.

**Comment by Pointedstick** [comment]
Oh nice! Confirming…

**Comment by Pointedstick** [comment]
Hmm, seems like now it's way too much in the other direction:

<img width="523" alt="mission" src="https://cloud.githubusercontent.com/assets/1097249/18619071/5105b7f4-7db0-11e6-9b1d-67f5b7561180.png">

The payment section for this mission is:
```
	on complete
		payment
		payment 10000
```

**Comment by Pointedstick** [comment]
Actually no, that's accurate, it's just insanely lucrative to transport a large number of people a long distance both ways (10,000 + (27 * 10 * 150 * 23 * 2) ).

**Comment by endless-sky** [comment]
I think that's actually the right amount.

The travel distance is 11 each way, so the distance multiplier is 23.

Passengers count the same as 10 tons of cargo - that is, you get 1,500 credits per jump for them.

27 * 23 * 1,500 + 10,000 = 941,500.
