### ISSUE TITLE
"FW Northern 3" typo?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1587]
> "There's a good chance we've taken care of all the sensors in this sector," says Freya, "so we can start moving our fleets around here without tipping the Navy off. And I just heard from **Southbound Shipping** that they've got two more Dreadnoughts ready for service."

Should this be Southbound Shipyards? Or do they have a whole section dedicated to regular shipping?
(derp)

**Comment by endless-sky** [comment]
Fixed in 1448f19.
