### ISSUE TITLE
Stack Core is underpowered relative to Dwarf Core + Fusion Reactor?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1589]
Stack Core:
1374 energy production, 3300 heat production, for 140 outfit space.
Dwarf Core + Fusion Reactor:
1380 energy production, 3240 heat production, for 136 outfit space.

Minor differences, and it makes sense for the latter to be superior since they are more expensive (and because fusion > fission), but given the point when the stack core is unlocked in the game, shouldn't it at least trump the dwarf core and fusion reactor pair? +6 energy and -60 heat for 4 less outfit space is just unfair, isn't it?

**Comment by Amazinite** [comment]
Well you've got to think about the manufacturers. The Dwarf and Fusion power generators are both top-notch reactors that are trusted and used by the Navy, while the Stack Core is something pumped out during the war to try and rival the Navy's Armageddon Core. 

The difference doesn't really seem all that big to me anyways.

**Comment by jafdy** [comment]
The stack core is a cheap alternative but is also larger and less efficient. If your not swimming in cash then it may be a better choice.

**Comment by Pointedstick** [comment]
> If you're not swimming in cash

But when's that ever gonna be the case at that point in the game? 😉

**Comment by jafdy** [comment]
Star wars mode. Get to the story as fast as possible and don't worry about making money.

**Comment by endless-sky** [comment]
The real point of the Stack Core is that the Free Worlds doesn't technically have access to the regions of space that sell any reactor cores except the Breeder. So, they need to manufacture  big reactor core for themselves. That is, it's more for the sake of the story than for the sake of actually providing the player with an upgraded reactor.

**Comment by KiLEdEnNis** [comment]
adding that it's hardly less good than the dwarf+fusion (4 more space, 60 more heat and 6 less energy), and it's way cheaper, it's fine as it is

**Comment by Bladewood** [comment]
Closing because God shot down my request :(

**Comment by KiLEdEnNis** [comment]
@Bladewood All hail MZ. \( ͡° ͜ʖ ͡°)/
