### ISSUE TITLE
adjustable time scaling, "fast-forwarding"

### ISSUE THREAD

**Issue by MagneticDuck** [endless-sky/endless-sky#1590]
Proposal: to add an in-game toggle or slider to increase the rate of game-time. This toggle should be disregarded by the engine when it is not viable or graceful, e.g. during combat or while escort ships are trying to jump from a previous system. The goal is to make long distance travel through friendly space less time-consuming without fundamentally changing the way the game is played.

I looked briefly through the source, and it's my impression that some things would have to be refactored in minor ways for this feature to be added correctly. If nobody else springs on it, I'll try it myself at some point. I appreciate the documentation by the way :)

A feature like this has been discussed very briefly on the endless sky subreddit: [here](https://www.reddit.com/r/endlesssky/comments/4n9od8/speed_boost_2x_5x/).

This issue could be fixed along with #865 by introducing a time rate slider or trinary switch. However, the ability to slow the passage of time could potentially impact gameplay, and therefore warrants more careful consideration.

**Comment by tehhowch** [comment]
This is basically done, minus the bit about variable.

**Comment by Amazinite** [comment]
>The goal is to make long distance travel through friendly space less time-consuming without fundamentally changing the way the game is played.

If this is the goal, then I suggest you hit caps lock while playing. There's already a 3x speed toggle.

**Comment by tehhowch** [comment]
That was my point. OP made this before Caps Lock gained its new functionality.

**Comment by jafdy** [comment]
This is from 2016, way before that function, so lets stop shredding the guy.

**Comment by MagneticDuck** [comment]
I'm happy to see this game continuing to improve. Closing this issue since it has silently been addressed since I opened it.
