### ISSUE TITLE
Several missions are appearing on the mission list when they should not be there

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1591]
Got a commendation from the Republic for fighting the Pug.
Departed from Earth.
Looked at the map.
"Pug Cease Hostilities" was listed in the upper-right corner.
[Alpha Omega.txt](https://github.com/endless-sky/endless-sky/files/478832/Alpha.Omega.txt)
I don't think that's supposed to happen.

**Comment by Bladewood** [comment]
It seems that this is happening with many of my missions. I'm not sure what is going on. With the electron beams, with the Pug mission, and now I've tried giving jump drives to the unfettered, and I have "More Jump Drives" and "More Jump Drives" active (each with a different description, though).

**Comment by toilethinges** [comment]
Sounds like you broke something. :+1:

**Comment by Bladewood** [comment]
No, I don't think so.

**Comment by endless-sky** [comment]
I think the issue might have been that the "failed" state of a mission was not being saved, so if you reloaded the saved game it would not remember that the mission has failed. Commit f655f24 should fix that.

(Previously, the game removed missions from the list the moment they failed, but that was causing crashes if the game was iterating through the list of missions at the moment when one of them marked another as failed.)
