### ISSUE TITLE
The wanderers don't fly through the eye (wormhole)

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1593]
^
Seems a bit odd that nothing go through it. It makes sense with the Hai or Pug wormholes but not this one.
Also is it possible to have it show up as "The Eye" on the map and in the tag.

**Comment by endless-sky** [comment]
Ships only land on objects that have spaceports. Maybe adding a spaceport to the Eye (even though it would never be shown) makes them land there.

**Comment by jafdy** [comment]
It works but it looks a bit odd as it shows up as inhabited in the map.

**Comment by endless-sky** [comment]
Fixed in 04d94a3.

I can't decide whether it's better to just not have wormholes show up in the planet list in the ports map, or to leave it as it is now.

**Comment by KiLEdEnNis** [comment]
leaving them be would show that the Wormhole has a spaceport right?
for now it'll be ok
