### ISSUE TITLE
Attempting to land on the Wisp in Sko'karak calls it a planet

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1594]
Tried to land on what would later become the Eye.
Result:
"This planet is too cold to land on."

**Comment by KiLEdEnNis** [comment]
well, what should it be? "This future wormhole can't be landed on."?

**Comment by jafdy** [comment]
"If you try to fly through this wormhole only the middle of your ship will make it."

**Comment by Amazinite** [comment]
"There's nothing to actually land on. It's all gas."

**Comment by Lineth** [comment]
"You cannot land on this spacial anomaly."

**Comment by KiLEdEnNis** [comment]
"Go land somewhere else."

**Comment by Alkallid** [comment]
"No"

**Comment by Amazinite** [comment]
~~"What are you doing in my swamp?"~~
How about custom land messages for uninhabited planets? Because I know there's at least one place where a lava planet is described as being "too cold."

**Comment by KiLEdEnNis** [comment]
cold lava maybe?

**Comment by endless-sky** [comment]
Custom landing messages would indeed make the most sense, but ideally at the same time I'd clean up how the stock messages are chosen, too.

**Comment by KiLEdEnNis** [comment]
keeping the stock messages but enabling custom messages would only have good benefits?

**Comment by endless-sky** [comment]
Yes, my point is that when making a change to the code, it's generally good to think about the best way to implement it so that it can be done cleanly, rather than adding a partial implementation that needs further patching down the road.

**Comment by KiLEdEnNis** [comment]
then hype for custom messages I hope

**Comment by endless-sky** [comment]
Fixed in beb4dc0, by adding the ability to define custom messages for any stellar object sprite. (So, there are also now custom messages for lava worlds and ringworld segments.)
