### ISSUE TITLE
re-orient "guns" outfitter sprites [content/enhancement]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1595]
it's a small thing, and a lot of work, but...

i feel like looking at the end of a gun that is connected to the ship is less immersive than if it were angled toward the user (and it's something that's always bothered me a little bit).

proposal: guns continue to point toward the top left hand corner, but "toward" the user, rather than "away" (and update wiki to reflect new standard).

i rendered the Plasma Cannon with the adjusted camera angle and came up with this (as an unpostprocessed example of the default lighting from that angle):
![untitled](https://cloud.githubusercontent.com/assets/16969517/18622247/b5206744-7dfa-11e6-819d-70447b089636.png)
compared to the existing:
![plasma cannon 2x](https://cloud.githubusercontent.com/assets/16969517/18622337/ac9dfd06-7dfb-11e6-892e-7c884606c509.png)

**Comment by KiLEdEnNis** [comment]
the shadows would probably make it way too dark, especially for darker sprites, which would cause isues for very little reason

**Comment by MessyMix** [comment]
I completely agree with this! I don't find the back of guns attractive. Love the idea.

**Comment by Pointedstick** [comment]
FWIW, I prefer the status quo to your new one. I don't like how you're looking at the bun from below; maintenance man's eye view? 🤔

 I think a nicer re-orientation would look be if the gun in the original picture were simply rotated along its Z axis 90 degrees, to be pointing towards the southwest. That way you would be looking at the muzzle from above.

But this gets into "why bother?" territory.

**Comment by KiLEdEnNis** [comment]
@Pointedstick that rotation idea (pointing South-West) is what I thought, fixes the shadow issue

as for the rest, I think half the people'd say yes & half would say no

**Comment by Wrzlprnft** [comment]
*cough* secondary weapons *cough*

**Comment by KiLEdEnNis** [comment]
he got a point there; the flamethrowers?
but they are primary guns though

**Comment by LocalGod79** [comment]
the necker illusion was immediately apparent to me when i posted the render (though i didn't know its name until you said so)

i always understood that all other sprites are front-lit as a result of the camera being "above" the object - i was trying to find a solution that didn't involve shifting the lighting as well - something that is as easy to do as shifting the camera.

it seems that i'm not alone in my desire to see the business end of the primary guns, rather than some awkward connector(s)

so the debate becomes: does the outfitter look better with the primary guns being the exception of;
a) pointing away from the user, or 
b) being viewed from below: the "maintenance engineer" or "on the top shelf" view (which is also congruous with their location in the outfitter

lighting flipped as well
![untitled](https://cloud.githubusercontent.com/assets/16969517/18655261/50b88eec-7eb5-11e6-9a49-0685f7934f11.png)

**Comment by Pointedstick** [comment]
The view-from-below look is really unappealing to me.

**Comment by Lineth** [comment]
I have to agree that the from-below view isn't that good.

**Comment by LocalGod79** [comment]
not that i agree with you @Pointedstick, just that you're willing to voice an opinion that isn't the same as mine.

i think the Command Center, Wanderer Cooling, and Androids were the outfits that finally did it for me: why are the guns the only ones facing away (when most people who create sprites probably want to show off the scary end)?

what about "from below" on engines?
![untitled](https://cloud.githubusercontent.com/assets/16969517/18655623/690bc56a-7eb8-11e6-9fba-72f5fda24087.png)

**Comment by endless-sky** [comment]
Note that usually when you make use of a gun in the real world, if you are viewing it with the business end pointed toward you you are probably doing something wrong and probably need more training before ever being allowed to handle a gun again. :)

I think regardless of what outfit you're talking about, having the lighting or the camera angle change from one outfit to the next is not a good idea. The outfitter is supposed to look like a collection of objects (all lying on the same plane), not a collection of photographs of objects at all different angles.

**Comment by LocalGod79** [comment]
i agree with you: about all of it.

with that said, you're not making use of the weapon at the outfitter; you're shopping it, and i'm not alone when i say: the current orientation of the "primary gun platter" makes creating primary gun outfitter sprites (that are appealing) significantly more difficult than it should be.

i also understand your desire for the different styles of outfits to have their "unique" facing (as a subtle visible indication of core attribute distinctions).

in the o.p. 
> it's a small thing, and a lot of work, but...

and i'm trying to find a middle ground - the easiest would be to rotate the primary guns to the same as the engines.  *way* more work (but way more complete): rotate the engines to face the camera directly, plus the "easy route".

**Comment by endless-sky** [comment]
I also really don't think that pointing them the other way would change much in terms of how people design the images. Guns tend to be long and skinny, which means that most of the image is the sides of the gun, not the front or the back. So, the best way to give the gun a more interesting shape is to focus on that, not on the "business end."

**Comment by Bladewood** [comment]
After looking at local's second image for a few minutes, I thought about something.
And now I think this would look awesome with turrets.
