### ISSUE TITLE
The Mule is too much of a no-brainer

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1598]
Among its many advantages:
* Can carry 4 turrets and has generous weapon space
* Has a huge cargo bay and enormous passenger capacity
* Crew complement is low enough to be affordable before you're super rich (and anyway, its cargo and passenger capacities will make you super rich) 
* Good enough engine space for some Deep Sky engines
* Solid shields and hull

These advantages make it practically a no-brainer as an early-to-mid-game ship. Its turrets waste interceptor-sized craft, the two gun ports can be fitted with large heavy guns or torpedo launchers, and its enormous cargo hold lets you batch up lucrative missions, clean up in the commodities markets, or convert to outfit space to fit huge reactors and cooling systems to support all the heavy armament. In the Deep or the Rim where you can easily batch up jobs, it's possible to make a million credits every 5 minutes or so using its enormous cargo hold and passenger capacity.

All this for under 5M credits? The ship has no real weaknesses… except for its appearance! 🙂

Suggestions for re-balancing:
* Reduce cargo space and passenger bunks
* Increase crew complement
* Reduce engine space/make it handle worse
* Reduce weapon hardpoints by one gun or one turret

**Comment by KiLEdEnNis** [comment]
small nerfs don't update existing save file ships though

**Comment by jafdy** [comment]
Long run @KiLEdEnNis, long run.

**Comment by Bladewood** [comment]
I don't really think playing with the mule is a no-brainer. I only played with it for one run.

**Comment by Amazinite** [comment]
I love the Bactrian (and Mule) as much as the next guy, but it can be a little ridiculous compared to other ships.

How to knock both the Bactrian and Mule off their throwns:
(Slightly?) less engine space. They're both big and heavy ships for their class, so they should move like they're big and heavy.
Less cargo space (and/or maybe more for freighters). The amount of cargo space makes them too good at being jacks-of-all-trades. There's really no point in buying freighters (aside from them being a little cheaper) because the Mule and Bactrian are practically freighters already without needing to buy cargo expansions.

**Comment by Lineth** [comment]
I don't really consider the appearance of the Bactrian and Mule to be downsides. I rather like the asymmetrical look and would like it if more of the Deep Sky Ships followed it. I do have to agree a bit that the ships are REALLY powerful. Maybe up the price a pit and make them a reward for completing a mission string like the Bactrian's description implies?

**Comment by LocalGod79** [comment]
both of those ships carry crew compliment and price points that work to balance them.

i disliked the Mule at that stage of the game, opting for a few faster warship escorts.

the Bactrian license is a side project of mine that's been simmering on the back-burner for a while - which should complete its balancing.

**Comment by MessyMix** [comment]
Good idea. Lower engine space, raise minimum crew, decrease maximum crew.

**Comment by KiLEdEnNis** [comment]
increasing drag/mass can help too?

**Comment by endless-sky** [comment]
I think weakening the Mule would make it too similar to the Hauler III, so I've just raised its price by about 40% instead. (ece73dc)

**Comment by Pointedstick** [comment]
That helps, but as usual, since money isn't really a problem, raising the price doesn't represent that much of an improvement if you agree with my basic analysis. Maybe the Haulers should have more cargo space and the the Mule less, since it's really not supposed to be a freighter. It doesn't make sense to me that the Mule has more cargo space than the Hauler II.

**Comment by retrue** [comment]
There are bad ships in the game. I think it is fine that there are some good ships too, like the Mule or the Bactrian. A price increment is ok but I don't think it would be a good idea nerfing its other stats.

**Comment by KiLEdEnNis** [comment]
@Pointedstick about the "no-brainer", once the player gets Quarg technology, about anything is a no-brainer?

**Comment by Pointedstick** [comment]
It's a "no-brainer" relative to where the player is in the game. When you're looking for a moderately tough warship you can use to do the mission strings for a while, the Mule is a no-brainer because it's also got the functionality of a heavy freighter and passenger transport, allowing you to amass money incredibly quickly by taking bulk jobs or looting reactors and things.

**Comment by LocalGod79** [comment]
@Pointedstick only if you've put in as many hours as you have; ie know about its superiority, its location, its idea loadout.

i think that M.Z.'s price point change moves it's availability back far enough that the player is actually forced to choose between it, and several smaller ships (which we all know is more effective).

**Comment by Pointedstick** [comment]
Even with the latest cost adjustment, the Mule is still a far superior choice. For example, compare it to the Corvette:

Mule advantages:
- 3,200 more hull
- 1 less crew (cheaper to operate)
- 12 more passenger capacity
- 230 tons more cargo space (can loot Armageddon Cores and other lucrative reactors for big bucks, and turn as much as needed into outfit space)
- 30 tons more outfit space
- 60 tons more weapon space
- 10 tons more engine space (🤔)
- 1 jump greater hyperspace range
- 2 more turret hardpoints (can mount a heavy anti-missile turret + 3 heavy laser turrets!)
- Fighter bay

Mule disadvantages:
- About 250k more expensive
- 700 less shields
- Lower top speed, acceleration, and turning with stock engines (can easily mitigate with better engines given the greater engine capacity and room for cooling equipment)
- 2 fewer gun hardpoints

Which one would _you_ choose? It's still no contest for anyone who bothers to compares the numbers.

**Comment by LocalGod79** [comment]
you've completely ignored two *very* important stats that level the field a bit;

drag: Mule 5.7, Corvette 3.5
heat dissipation: Mule .5, Corvette .7

i think that if the base mass of the Mule is trimmed to be more in line with the other Medium warships, (and perhaps a minor nerf on it's heat dissipation) should accomplish the balancing you had in mind...

**Comment by Pointedstick** [comment]
It's true that the Mule is slower than the Corvette--inherently so, and with a higher top maneuverability limitation. That's one of its few disadvantages. However the heat issue is really a non-issue since you can stuff a Mule with as much heat-dissipation equipment as necessary using its prodigious cargo space; three mass expansions provide enough space for a Liquid Helium cooler with 5 tons to spare, and you'll still be left with 210 tons of cargo space!

**Comment by Pointedstick** [comment]
Another casualty: the Splinter, which is worse than the mule in literally every way except for purchase price and handling.

**Comment by Pointedstick** [comment]
In a nutshell, the Mule's problem is that is keeps you from having to make the otherwise challenging choice about what class of ship you prefer. It has better passenger capacity than most of the Transport-class ships, similar cargo capacity to most of the Heavy Freighter-class ships, and superior firepower potential (4 turret mounts!) than most of the Heavy Warship class ships. This one ship does the job of three.

Since it's a Medium Warship, the most straightforward change to bring it more in line with its actual role would be to reduce the passenger and cargo capacities.

**Comment by Pointedstick** [comment]
Also, I disagree that weakening the mule in any way will make it too similar to the Hauler III, or any Hauler. These are ships with enormous cargo space and terrible shields and handling. They play like cargo ships--exactly as they should. In my first playthrough I tried to make a light warship out a Hauler II, attracted by its high turret count, but it totally didn't work. The shields and handling were too poor. Haulers are just too fragile to use as real warships.

Reducing the Mule's cargo and passenger capacity will actually further **differentiate** it from the Haulers!

**Comment by LocalGod79** [comment]
@Pointedstick you didn't find the 140 weapons capacity of the Haulers to be the limiting factor to making it into a warship?  that was the bottleneck for me (and part of why i left it so on the "Type F Haulers")...

in fact, i found the massive cargo/outfit space more than compensated for the low shield stat - if you piled some beast gennies in there (and some a/m on a turret mount or two) - and the heavy duty hull (compared to it's MWS classmates) made it quite survivable...

**Comment by Pointedstick** [comment]
@LocalGod79 140 tons was enough for three heavy laser turrets and a light anti-missile turret. And yes, converting cargo space into shield generators worked initially, but the speed, firepower, and shield capacity was just too low after a while. I reached a situation I couldn't beat during the Free Worlds mission where three Leviathans take off from a pirate planet alongside you. Couldn't outfight or outrun them.

They are serviceable in combat if specifically upgraded for that purpose, but I think after a while they show their freighter roots. It's pretty perfect, really.

**Comment by LocalGod79** [comment]
thanks! (i preferred a load out more similar to the Sidewinder variants - pair of Heavy Laser Turrets, A/M, Sidewinders)

with all of that said, i found the Mule and "Type F"s to be nearly kindred spirits, not really being spectacular at anything in the very late game (being ultimately too slow/small), and offering plenty flexibility in mid game (especially with the addition of the Boxwing)...

to me, that makes the Roost or Skein the Mid-weight "no-brainer"...

**Comment by Pointedstick** [comment]
This hasn't been addressed yet…
