### ISSUE TITLE
Torpedoes are too fast and reverse course too quickly

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1599]
Because of their damage, speed, how fast they can reverse course if they miss, their unjammability, and how durable they are against anti-missile turrets, torpedoes are good against nearly any type of ship, making them a no-brainer weapon for ships that have enough room to mount the launchers.

It seems to me that they should be more for killing capital ships, which would entail reducing their moving, turning, and reversing speed, maybe in exchange for boosting their damage slightly. This would differentiate them better against the smaller (supposedly) more agile missiles.

**Comment by LocalGod79** [comment]
almost 1250 issues/pulls later:
https://github.com/endless-sky/endless-sky/issues/251

**Comment by endless-sky** [comment]
Against AI ships, maybe, since they don't know how to dodge. But the player can very easily create a ship that can outrun them.

Also, they use optical tracking, which makes it hard for them to accurately track small ships even if they're movign slowly.

**Comment by MessyMix** [comment]
Pull Request #1: Typo Fix (movign --> moving)

:P 

@topic: If AI learn to dodge missiles, then the Torpedo won't be overpowered.
BTW, if you think Torpedo is OP, why not the Typhoon? Isn't that just an even more OP weapon? If you're worried about availability or accessibility, maybe hitching the prices for the Torpedo will help..

**Comment by Pointedstick** [comment]
I actually think the Typhoon is perfect--it's what the regular torpedo should be. It's slow and easy to dodge in a fast ship, but it does a huge amount of damage against large ships.

**Comment by Pointedstick** [comment]
At some point I'm probably going to take a hiatus from this game, come back to it months later, see that torpedoes are still too effective against small ships, forget about the last two times I opened issues about it, and open a new one. 🙂

**Comment by KiLEdEnNis** [comment]
don't torpedoes have optical tracking? if not, they should

**Comment by jafdy** [comment]
They do.

**Comment by KiLEdEnNis** [comment]
then I don't see a problem, nearly all launchers (especially human ones) are quite ineffective, nerfing 1 won't help that much imo
