### ISSUE TITLE
Positive reputation can break storyline missions

### ISSUE THREAD

**Issue by Waladil** [endless-sky/endless-sky#160]
Per the bug described in http://steamcommunity.com/app/404410/discussions/0/496880203080242804/ and my response to that thread (edit 2), the "Attack Rastaban" mission can be unwinnable if the PC has a friendly reputation with the Republic. I accomplished this by fighting pirates and hostile aliens for several in-game years, or possibly some other bug. 

I don't know for sure, but I suspect this bug may be present in other missions too, probably any mission that hinges on defeating a hostile fleet at a location. If the fleet's non-hostile... oops.

**Comment by endless-sky** [comment]
You can always attack the Republic fleet, even if they are not hostile towards you. But, I've also added a reputation change in commit 5e92a7a.

**Comment by Waladil** [comment]
Seems a bit hacky of a fix, but okay! 
(Just attacking the non-hostile Republic fleet is what I did in the first few runs. However, the mission wont properly update if they weren't hostile when you jump in)
