### ISSUE TITLE
Give Admiral Danforth's ship a ramscoop

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1600]
Otherwise it takes a frustratingly long time for him to get to Host and back when we go Alpha hunting. We can't refuel him either, because the Korath ships (including the Alphas') will stop us and are naturally too strong for us to fight back at that point in the game.

**Comment by Amazinite** [comment]
I left from the eastern Unfettered world and didn't have to stop for fuel anywhere.

**Comment by Bladewood** [comment]
I do plan them. I know exactly how the mission plays out.

**Comment by Lineth** [comment]
I modded the files to give Danforth a Catalytic Ramscoop. Solved the problem and even makes sense from a lore perspective.

**Comment by Lineth** [comment]
Double-post: https://github.com/endless-sky/endless-sky/pull/1601 :3

**Comment by KiLEdEnNis** [comment]
while we're at it, rename it from "R.N.S. Peacemaker" to "R.N.S. Pacemaker", Danforth isn't young anymore :)

**Comment by endless-sky** [comment]
If you bribe the Unfettered, you can land on their planet and make it to Avalon without Danforth needing to wait to refuel.

Also, as mentioned in the PR, his ship *does* have a ramscoop.

**Comment by Bladewood** [comment]
I did.

Danforth's ramscoop is unbearably slow. If I was able to, I would give him all 800 fuel points directly, but I can only give 200, then I have to wait for a few centuries for his ramscoop to make fuel for him.

**Comment by Amazinite** [comment]
>I did.

Well if he already has enough fuel to make it to the destination without
needing to refuel then what's the problem?

**Comment by Bladewood** [comment]
Getting back to the Unfettered system.

**Comment by Amazinite** [comment]
If I recall, the return trip is a different "mission," and therefore Danforth is a different NPC that should have full fuel.

**Comment by Bladewood** [comment]
You've got to be kidding me.
I am an idiot.

**Comment by Amazinite** [comment]
Rip in peace.
