### ISSUE TITLE
Smuggler's Den description doesn't match reality

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1602]
<img width="523" alt="can you" src="https://cloud.githubusercontent.com/assets/1097249/18677740/0fc8ae6e-7f17-11e6-976d-66cdad8dfa28.png">

In fact, the outfitter has no unique items,  there's no way to get anyone to make special modifications to your ship, and there's only one refurbished ships in the Shipyard--the Modified Argosy, which is available elsewhere too and easily lootable. All in all it's a little underwhelming.

**Comment by LocalGod79** [comment]
also has the dubious distinction of having a completely empty job board, and only one spaceport mission string...

i think much of this was intentional - M.Z. apparently leaving a juicy government *and* port **_wide_** open for "Independent Content" development by the community.
