### ISSUE TITLE
Suggestion to increase dramatic effect in checkmate-reconcilation split mission

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1604]
> "If Katya were here," **JJ says quietly**, "she would tell us to choose justice over political expedience."

[spacer]

> **JJ is clearly disturbed by your decision, but nonetheless gives in to the pressure with a sigh.** "Very well," says JJ. "In that case, ..."

I think these would make the side-with-syndicate conversation choices sound much more serious.

**Comment by KiLEdEnNis** [comment]
add a love story too :P

**Comment by MessyMix** [comment]
Katya. Nuff said.

**Comment by Bladewood** [comment]
Thought Katya was taken by Ijs.

**Comment by jafdy** [comment]
And we don't reference the players gender.

**Comment by KiLEdEnNis** [comment]
@Bladewood from what I understand Ijs is her semi-elderly friend
@jafdy then we should add a gender before players start a save file o:
(rip existing ones but still)

**Comment by Bladewood** [comment]
The answer: Bisexuality!

**Comment by Alkallid** [comment]
No, if you try to fire on the Navy for the ship check, they'll say "him" when referring to you.

**Comment by KiLEdEnNis** [comment]
so the player is a man or a Russian woman that looks like a man, someone documentate that

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/df6ce0161f0ef6341493b05aae1e4ed8b6797bb5 rekt

**Comment by endless-sky** [comment]
Technically speaking, making the player male would impose the wrong identity on only about half the population, whereas making the player bisexual would be imposing the wrong identity on about 98% of the population. So, no, that's not going to happen.

Also, thanks @Alkallid. (df6ce01)

**Comment by retrue** [comment]
Still, when the game is translated, this issue must be addressed again. Not all languages are as gender neutral as English. The translator will have to pick up a gender for the character. Or an option to choose the gender of the character and alternate translations of some lines of dialogue to match the gender of the character.

**Comment by Wrzlprnft** [comment]
Indeed. But are there languages with gender references other than the third (insert right word - form?)
I
You
He/she/it <- is avoided as the commit shows

Since the possesive pronoun refers to the gender of the "possesed" thing - as far as i know - it should not be a major issue.

Feel free to prove me wrong, though

**Comment by retrue** [comment]
Easy. In many languages the form of the adjective depends on the genre.
For example, in the very first description of the game you find the sentence:
"You are wearing your very best clothes, but you feel shabby next to them."
In Spanish, the second part:
"pero tu te sientes desaliñad**o** al lado de ellos." (male character)
"pero tu te sientes desaliñad**a** al lado de ellos." (female character)
In French
"mais vous vous sentez misérablement vêt**u** à côté d'eux." (male character)
"mais vous vous sentez misérablement vêt**ue** à côté d'eux." (female character)
Same problem with Italian. Shabby is trasandat**o** (male) or trasandat**a** (female).

**Comment by KiLEdEnNis** [comment]
> Technically speaking, making the player male would impose the wrong identity on only about half the population, whereas making the player bisexual would be imposing the wrong identity on about 98% of the population. So, no, that's not going to happen.

well played :(

**Comment by Wrzlprnft** [comment]
Dang, i only thought of pronouns.

**Comment by Bladewood** [comment]
_meanwhile, not one mention was made of my **real** suggestion_
