### ISSUE TITLE
[Mechanincs] Events Creating Systems

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#1605]
So I was working with someone on steam who wanted a system to be created after a set of missions was complete. After working out a few errors, we got the event working, however the map would not show the system. So I modified the event to link it to an existing system, and this works but the system will not show on the map until you manually jump to it(the link just leads to empty space in the map).

So I'd like to know if this is a bug, intended feature, or just an unforseen use case.

**Comment by Amazinite** [comment]
Makes it super secret. 
If the event-made-system is not linked, is it still reachable by jump drive if you use the jump key to toggle your destination?

**Comment by KiLEdEnNis** [comment]
what I use; make sectors beyond jump-drive range (making them invisible), and have an event link a sector to a known sector

**Comment by comnom** [comment]
>Makes it super secret.
If the event-made-system is not linked, is it still reachable by jump drive if you use the jump key to toggle your destination?

I didn't check to see if you could use a jump drive to hop to it manually, but when toilethinges and I were playing with it, it made toggling routes screwy. The only way to get to it was to be in the linked system, point your ship in the general direction and press J.

>what I use; make sectors beyond jump-drive range (making them invisible), and have an event link a sector to a known sector

His story requires it to be an unlinked system, discovered through the missions.

**Comment by endless-sky** [comment]
The issue was that the game calculates what systems are visible from each system when the map is loaded, and wasn't updating those calculations when the map changed. Commit a266bb7 should fix that.
