### ISSUE TITLE
Sound causes lag on netbook

### ISSUE THREAD

**Issue by PenguinBartender** [endless-sky/endless-sky#1606]
Version 0.9.3: Unstable release

When the sound is enabled, he game will intermittently lag when in vicinity of planets/cluster of ships (I haven't been able to say for sure exactly which one it is).

When sound is set off (bar reduced to absolute bottom) there is no lag.

Watched CPU/GPU usage, neither spikes during these events.

Keep in mind the game runs GREAT except for this problem.

My specific laptop is:
Model: HP Pavilion x2 - 10-k010nr

Microprocessor: 1.33GHZ Intel Atom Processor Z3736F
Microprocessor Cache: 2MB L2 Cache
Memory On-board: 2GB 1333MHz DDR3L SDRAM
Video Graphics: Intel HD graphics
Display: 10.1-inch HD WLED-backlit WXGA Touchscreen (1280x800)
Hard Drive: 32GB eMMC
Sound: HD Audio with stereo speakers (Realtek High-Definition (HD) Audio)
* Realtek I2S Audio Codec
* Intel SST Audio Device

**Comment by PenguinBartender** [comment]
Update, the problem was helped by updating soundcard drivers to latest version, now lags intermittently and briefly upon jump to other system.

Unless someone feels a burning need to troubleshoot this with me, I assume this can be closed.

**Comment by Pointedstick** [comment]
You can close it yourself, in fact!
