### ISSUE TITLE
Electron beam & turret price vs plasma cannon & turret price

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1607]
Electron beam: 170000
Electron turret: 720000
Plasma cannon: 190000
Plasma turret: 520000
I'm not the only one who sees something wrong here, right?

**Comment by KiLEdEnNis** [comment]
plasma cannon was 25 space, x2 = 50, + 10 for turret
electron beam was 21 space, x2 = 42, + 12 for turret, right?
that means the electron turret has a bigger turret base that costs more (which some Americans prefer)

**Comment by Pointedstick** [comment]
> which some Americans prefer

🇺🇸🗽🏈🍔🍕🔫🎅🏻🚕💰📺🏡⛪️⛄️

**Comment by endless-sky** [comment]
Well I *was* going to fix the costs, but now I like @KiLEdEnNis's explanation so much that I may have to leave them as they are. :)

The trouble is that the prices also have to make sense relative to other similar weapons - if I change the Plasma Cannon, for example, I'll also have to change the Particle Cannon and Proton Gun costs. I suppose making the Plasma Turret cost about 800k would be the most obvious change...

**Comment by Bladewood** [comment]
*slow applaud*

**Comment by MessyMix** [comment]
I think that anywhere in the region of 70k is good. After all, I can totally imagine the Dirt Belt's Plasma gun being a lot more "cobbled together" than the Deep's electron beam. For me, a price hike for the turret might be good, but also maybe a _decrease_ in the price of the gun-mounted variant (or opposing this, a price raise for the electron beam). I just feel like the Deep's machinery will be a lot sleeker and compact, and thus expensive. Kind of like Apple products in the sense that even if the products aren't explicitly better than the products of their competitors, they can still sell for more.

**Comment by Bladewood** [comment]
I was under the impression that the most obvious change would be to change the electron beam, rather than the plasma turret.

**Comment by LocalGod79** [comment]
i think that all things considered, the p'turret's bolts will miss more often than the e'turret beam, so i always figured the skew was compensating for that aspect of the weapon's performance (in addition to the cooling systems one additionally requires)...

in this case, i would say that all things are not equal compared to the gun mounted version, because with the gun-mount, one's velocity vector (relative to firing resolution) is easier to control than with the turret (so the gun will not likely waste as large quantities of energy/cooling)...

i'm not averse to a change just; 70k seems like the _upper_ limit of a correction: we don't want to mess with the existing balance metrics too much...

**Comment by MessyMix** [comment]
You mean 700k?

I feel like a price increase in the BEAM, not the turret, should suffice. Sleeker and more efficient look = more bucks to pay.

**Comment by endless-sky** [comment]
Here are the current prices:

 | Gun | Turret
--- | --- | ---
Laser | 29000 | 140000
Heavy Laser | 60000 | 320000
Electron | 170000 | 720000
 |  | 
Proton | 150000 | 
Plasma | 190000 | 520000
Particle | 220000 | 

The constraints I want to maintain are:

Proton Gun < Plasma Cannon < Particle Cannon
Plasma Cannon < Electron Beam (both for guns and turrets)
Electron Beam > 2 * Heavy Laser > 4 * Laser (both for guns and turrets)

The electron beam is already 3 times the heavy laser price, so I wouldn't want to increase it without increasing the heavy laser price too. Or, we could decrease the Plasma and the Proton gun costs.

**Comment by Pointedstick** [comment]
No love for the Proton Gun!? Such an underrated weapon!

**Comment by Bladewood** [comment]
Just to note something: Pulse cannon price is 110000 credits, while the heavy laser is at 60000. Pulse turret price is 320000, same as the heavy laser turret.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/0b8243ff92d41d6b7e52f48ca6651eb27f2b3687
okay, that's over with.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
