### ISSUE TITLE
Robot ship with not enough bunks gets "you will fail a mission" message

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#1608]
I captured a Kar Ik Vot 349, placed a Command Center on it, did not remove its turrets or install extra bunk rooms, and tried to take off from the planet.

Got this message:

> If you take off now you will fail a mission due to not having enough bunks available for 6 of the passengers. Are you sure you want to continue?

Answering "OK" gave expected behavior: I took off and my ship behaved extremely erratically due to having only 1 of the necessary 7 crew members.

**Comment by KiLEdEnNis** [comment]
passengers or actual crew (for the turrets)?

**Comment by SolraBizna** [comment]
I was not carrying passengers.

**Comment by Bladewood** [comment]
I found that this always happens with insufficient crew when I'm using the all content plugin or world-forge. I'm not sure if it happens in vanilla, but it probably does there as well.

**Comment by LocalGod79** [comment]
turrets require crew when mounted on a ship that is not an `automaton`.

buy mass expansions and bunk rooms to man those turrets properly...

**Comment by SolraBizna** [comment]
> turrets require crew when mounted on a ship that is not an `automaton`.

Yes, I know. This bug is the wording of the message, not the fact that my ship did not function perfectly or the fact that I got a message at all.

**Comment by endless-sky** [comment]
Fixed in 50e2b07.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
