### ISSUE TITLE
Switch Mark II cruiser gun hardpoints

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1609]
> gun "Typhoon Launcher"
> gun "Typhoon Launcher"
> gun "Sidewinder Missile Launcher"
> gun "Sidewinder Missile Launcher"
> gun "Sidewinder Missile Launcher"
> gun "Sidewinder Missile Launcher"

![cruiserfail](https://cloud.githubusercontent.com/assets/16506683/18768771/84cba074-80f5-11e6-9a33-381b1359a76a.png)
Setting the hardpoints like this causes the sidewinders to come from the blue points above and the typhoons from the red, when instead it should be

> gun "Sidewinder Missile Launcher"
> gun "Sidewinder Missile Launcher"
> gun "Sidewinder Missile Launcher"
> gun "Sidewinder Missile Launcher"
> gun "Typhoon Launcher"
> gun "Typhoon Launcher"

which comes out to this:
![cruiserfail2](https://cloud.githubusercontent.com/assets/16506683/18768817/cf8d678c-80f5-11e6-8d73-24391506cfff.png)
Really minor issue, yes, but it annoys me every time I go into world-forge and build a perfect replica of a mark II cruiser with those settings.

**Comment by Admirial-Danforth** [comment]
I support this.

**Comment by Bladewood** [comment]
admiral danforth
y u so typo name

**Comment by Admirial-Danforth** [comment]
autocorrect why

**Comment by KiLEdEnNis** [comment]
someone should check if story mark II ships need to be changed as well
we don't want Danforth forgetting to change his R.N.S. Pacemaker, he is becoming old

**Comment by endless-sky** [comment]
Fixed in 6d4b1a7.
