### ISSUE TITLE
Landing on Vara Ke'sok prompts Unfettered Hai Dialogue

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1610]
When I land on Vara Ke'Sok it prompts me to talk to the Hai and when I have done they also want to do the jump drive trade. Note: I have not tried finding out what happens when you sell them all four jump drives.

It also has the post Unfettered Hai invasion description, as well as Varu Mer'ek and so does Varu K'est, although I do not know if this planet is pre or post invasion description.

**Comment by Admirial-Danforth** [comment]
The jump drive missions do count btw

**Comment by KiLEdEnNis** [comment]
I think because it gets the label "Unfettered" after they captured the planet

**Comment by endless-sky** [comment]
What version are you running? This should have been fixed in 0.9.3 by commit 8b4e43d.

**Comment by Admiral-Danforth** [comment]
0.9.3

**Comment by Admiral-Danforth** [comment]
this never happened in 0.9.2 and the unfettered have not invaded yet btw

**Comment by Admiral-Danforth** [comment]
It happened on Newhome as well, but never returned.

**Comment by endless-sky** [comment]
This is the bug that was fixed in #1571.
