### ISSUE TITLE
Typo? Ijs says the Free Worlds taxation model is probably totally unsustainable.

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#1611]
In FW Senate 1B, Ijs speaks about the Free Worlds taxation model.

```
It's brilliant. And probably totally unsustainable.
```

I think it may be "sustainable."

**Comment by retrue** [comment]
I think there is not typo. Ijs thinks that the taxation model is utopic, it looks great but it would ruin the Free Worlds in very few years.

**Comment by KiLEdEnNis** [comment]
what he means is it may be brilliant but impossible to do/keep up

**Comment by Pointedstick** [comment]
Exactly.
