### ISSUE TITLE
The change from Pond Striders to Solifuges in the Unfettered fleets

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1612]
Because the Wanderer missions used to set the Unfettered fleets to contain Pond Striders, anyone who completed those missions before the change to Solifuges would have Pond Striders and Fleas in the Unfettered fleets instead of Solifuges.

**Comment by LocalGod79** [comment]
wasn't this resolved before the 0.9.3 release?

**Comment by endless-sky** [comment]
The only people affected by this would be people who built the game from source, and they're probably capable of editing their saved games to fix it if they want to.
