### ISSUE TITLE
Limit how many ships of each type each shipyard has in stock

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1613]
http://steamcommunity.com/app/404410/discussions/2/350542683196178772/

to be implemented properly it might take a fair bit of coding, but it's an interesting concept that could build on #869 (which i'm closing, now that it's referenced here)

@jmhorjus do you think this could work its way into #852?

**Comment by jafdy** [comment]
I don't think #852 is going to get merged on account of being too wide ranging. 
Full support from me.

**Comment by spiral03** [comment]
Personally, I feel that #852 is such a huge improvement and so needed, that to NOT merge it could inspire the creation of an ES clone that would draw valuable developers away from ES.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/1344

**Comment by endless-sky** [comment]
Once the player is rich enough to be buying ships in bulk, there really aren't that many interesting things for them to do in the game, anyway (aside from dominating planets). I really think depreciation is the best way to slow the player's rise through the middle tiers of ships, but as I've said elsewhere I think there are much cleaner and simpler ways to implement that than what's in #852.

**Comment by jmhorjus** [comment]
@endless-sky  Re:"_I really think depreciation is the best way to slow the player's rise through the middle tiers of ships, but as I've said elsewhere I think there are much cleaner and simpler ways to implement that than what's in #852._"
I'm worried that a "simpler" solution might lack features or introduce limitations compared to what is in #852.  I am willing to update and modify my changes in any way you ask if it means a chance to be merged. I've stopped working on or playing ES, but I'd gladly come back if I thought I could make a difference in the main branch.  Can you confirm that you've built and tried out the #852 branch for yourself and what your experience was like?

**Comment by LocalGod79** [comment]
i think that the biggest take-away from the Steam suggestion for me was:
you *almost never* see npc fleets with more than two capital ships; but the player can (and quite often does) fairly easily end up with a fleet that looks like it consumed **every** resource in human space (and those npc admirals are still plugging away with their tiny fleets, and all the ships still cost the same)  - it's a little immersion breaking...
(sorry about the run-on...)

**Comment by MessyMix** [comment]
>sorry about the run-on...

Also a fragment with the "but" after the semicolon. ;)

Topic: I think that #852 tries to implement a lot of things, but the basic idea is good. I would love to see a shipyard constraint, because yes, you are right that it is immersion breaking. If I had the cash, I could buy thousands of sparrows from Rutilicus, even though the shipyard probably makes only a couple sales a day. Realistic? Probably not.
