### ISSUE TITLE
Allow flagship to refuel by itself (idea)

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1615]
One idea I have is an option, so your flagship will automatically land and refuel like escorts do. The fact that it does not do this is really annoying because I always end up one system away losing precious time. This could be part of Issue #1504.

**Comment by Admiral-Danforth** [comment]
Also possibly make it refuel at certain points on the jump path

**Comment by toilethinges** [comment]
That could mess stuff up with your escorts. I prefer waiting for all my ships to enter one system to land. Possibly a toggle?

**Comment by Admiral-Danforth** [comment]
What I was trying to say was have it set so say, escort x refuels our ship refuels or something like 
When Ships enter System X, Land and Refuel on Planet X
And yes I did want it to be a toggleable setting

**Comment by Admiral-Danforth** [comment]
I'm going to try to write this as clear as I can:
Idea 1. You configure your ship to refuel along with another ship in your fleet. The idea is something like this:
When Ship X Lands to refuel Your flagship will refuel as well

Idea 2. On the map you click on a planet on your jump route and say you want your ship to automatically land there and refuel, then when it has refueled it automatically departs and continues on the jump path.

Essentially I just want flagships to be automatically land, refuel, depart, and continue on their merry way.

**Comment by endless-sky** [comment]
My goal is for the player to actually feel like they are controlling the flagship directly and it is obeying their commands. If the flagship suddenly decides all on its own that it wants fuel and it's going to go find a planet and refuel itself, that kind of breaks the illusion.

Also, it would be really weird for the flagship to land but no planet panel to pop up - what if the player actually did want to land there, but just didn't hit the landing key before the flagship auto-landed? Plus, when the flagship lands a day has to pass in game time; if that happened without a planet panel popping up you'd see all the planets suddenly shift positions.

**Comment by Admiral-Danforth** [comment]
I just wanted this to be a toggle feature because at this point I am driven insane heck this could also be a mod.

**Comment by Pointedstick** [comment]
You're being driven insane by having to actually play the game? 😉

**Comment by Admiral-Danforth** [comment]
What I'm saying is that this would be useful for if you wanted to say go get a drink while you're jumped. This would prevent you from having to click land button them waiting 5 minutes to land (true story).

**Comment by Amazinite** [comment]
The Admiral needs some crutches in his old age.

**Comment by Amazinite** [comment]
> What I'm saying is that this would be useful for if you wanted to say go get a drink while you're jumped. This would prevent you from having to click land button them waiting 5 minutes to land (true story).

Plan your jump so that you have enough fuel for 1 jump left when you get back. That way, no matter how far you are from the center of the system, you can always use the last of your fuel to just jump to the center of the next system over.

**Comment by Admiral-Danforth** [comment]
I have ramscoops so this never works

**Comment by Amazinite** [comment]
Then you're doing it wrong.

**Comment by Amazinite** [comment]
Le map.
![le map](https://cloud.githubusercontent.com/assets/17688683/18805845/8fb36e4e-81e6-11e6-9064-657371f7a3c3.png)

Be here
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/18805846/93d19ff0-81e6-11e6-8180-7cdc905221b9.png)

Want to be here
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/18805847/9758c3b0-81e6-11e6-9634-f1bc4b05ab1f.png)

Have fuel to reach there
![screenshot_3](https://cloud.githubusercontent.com/assets/17688683/18805849/9dd3228a-81e6-11e6-862e-0276678d34fc.png)

But need to leave for a few minutes, so I instead go here.
![screenshot_4](https://cloud.githubusercontent.com/assets/17688683/18805851/a85c6d74-81e6-11e6-98b5-667c9d1f85c2.png)

That way when I return I can just hop over to the next system and be done.
Doesn't matter if you have a ramscoop or not, it still works.

**Comment by MessyMix** [comment]
He's saying stop your trip one stop away, and afterwards jump the last system because when you jump you always spawn in the middle of the system. You won't need to take five minutes to land this way.

**Comment by KiLEdEnNis** [comment]
or press the escape button which pauses the game? seems rational to me, and the easiest to do

**Comment by Admiral-Danforth** [comment]
other I'm trying to say that this would be best for people who do other things they jump it would be like slave chaining your shop temporarily to another

**Comment by MessyMix** [comment]
I think he wants to complete the jump while he's away.

**Comment by Admiral-Danforth** [comment]
Thank you @MessyMix for figuring it out

**Comment by Amazinite** [comment]
>@MessyMix

**Comment by MessyMix** [comment]
@MessyMix

**Comment by MessyMix** [comment]
someone called?
