### ISSUE TITLE
Ships in Rastaban during FW Liberate Delta Sagittarii

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1619]
Seems a bit odd that there would be a load of ships fighting in a system that the player won't go to.

**Comment by KiLEdEnNis** [comment]
does the player usually go through that system on the way to Rastaban?

**Comment by jafdy** [comment]
Other way round the player wont normally go through Rastaban to get to delta saittarii.

**Comment by KiLEdEnNis** [comment]
may be leftovers from early mission development, not sure

**Comment by endless-sky** [comment]
That was intentional - the point is to indicate that the Free Worlds are fighting over both those systems at the same time, and you're just joining one of the fights.

**Comment by KiLEdEnNis** [comment]
was my other idea but thought it would be unlikely
about similiar things, remember in the story you go after the Syndicate defector and the Syndicate send a huge fleet to Earth? such missions should get actual fleets too
