### ISSUE TITLE
Stuck in landing/takeoff loop

### ISSUE THREAD

**Issue by Nicodemus-IXR** [endless-sky/endless-sky#162]
I had my fleet set to gather on me, and I landed on a planet. While there, I sold my flagship. The next ship in my fleet became my flagship by default.

Then, I departed the planet.  But the rest of my fleet got stuck in a loop where they would take off from the planet and re-land, over and over.  I guess they were still following the flagship that I sold.

I then landed back on the planet and bought the ship back from the shipyard, made it my flagship, and departed.  This fixed the issue.

Then I re-landed, and in the shipyard, I changed my flagship to another ship BEFORE selling the ship, and it worked OK.

**Comment by endless-sky** [comment]
This is fixed in commit b5edbe4, so it will be part of the next release (0.8.5).
