### ISSUE TITLE
[Content] Please make the "Eye" the called the "Eye"

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1621]
At the moment it is called ???, but since this wormhole has a name I suggest just calling it the "Eye"

This is probably already suggested but oh well

**Comment by Admiral-Danforth** [comment]
Also completely unrelated the Hurricane is super strong, you can take on a sizeable defense fleet.

**Comment by jafdy** [comment]
It's a T2 heavy, it will outpower most T1 fleets.

**Comment by Admiral-Danforth** [comment]
I find it interesting you didn't ask why I had one

**Comment by Amazinite** [comment]
v0.9.5, according to Wrzl

**Comment by Admiral-Danforth** [comment]
thx

**Comment by Admiral-Danforth** [comment]
also which do you think is better the tough version or the turret version

**Comment by Bladewood** [comment]
Stop making random messages.
Get back to the topic at hand.

This is currently impossible because of how wormholes work in the game.

**Comment by Admiral-Danforth** [comment]
I was just wondering and I was unaware that this is how wormholes work

**Comment by Bladewood** [comment]
You did not need to close it :|
We can wait to see what Michael thinks about it.

**Comment by Admiral-Danforth** [comment]
I did that by accident and also it was suggested in issue #1593

**Comment by Admiral-Danforth** [comment]
Can anyone direct me to a GitHub issues suggestion board

**Comment by endless-sky** [comment]
I think I'd prefer to just have it show up as ???.

**Comment by Admiral-Danforth** [comment]
The only thing I don't understand about that is that the Wanderers have given it a name and since the character refers to it as that, it would make sense that your computers/landing/navigation would to.

**Comment by Bladewood** [comment]
You'd think that they would name the Pug and the Hai wormhole too, in that situation.

**Comment by Admiral-Danforth** [comment]
well the pug and hai wormhole never where called anything specific (as far as I remember)
