### ISSUE TITLE
Hai (unfettered) bug

### ISSUE THREAD

**Issue by kiwijim83** [endless-sky/endless-sky#1625]
I was exploring Wanderer space in yet another play through (0.9.3) and hadn't yet talked to the Unfettered , I landed on the planet Vara Ke'sok and it proceeded to give me the dialog you usually get on their home worlds north of the normal Hai when you first talk to them.

In one of the conversations it mentions that the Unfettered conquered a Wanderer planet and were then driven off, could this be why the dialog came up, or is it a bug?

P.s. I'm continuing from a save from the version before and cant see any of the new ships mentioned but still get the gattling gun, could it be my Hai being bugged?

P.s.s I get the 'hai have noticed you have a spare jump drive etc etc...' option when re-landing on planet

**Comment by Amazinite** [comment]
#1610

**Comment by kiwijim83** [comment]
Cant believe i missed ALL of those when I was looking through, I'll close this issue seeing as people are already aware, thanks.
