### ISSUE TITLE
The Corvette, Firebird, and Osprey are too similar to one another

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1626]
This is a follow-on to issue https://github.com/endless-sky/endless-sky/issues/1598, which made me realize that the Mule's superiority is exacerbated by issues with a number of other Medium Warships, which are not as good as they should be. In this issue, I will focus on three in particular that seem insufficiently differentiated from one another and not good enough either: the Corvette, Firebird, and Osprey.

These ships are very similar. They have identical weapon hardpoints, similar overall durability (shields+hull), crew complement, space for cargo, outfits, weapons, and engines. Differences are minimal: the Firebird is a little less maneuverable than the other two and has lower range but more hull, and the Osprey has more shields and is grossly overpriced. The Corvette is also overpriced and doesn't really stand out in any way at all--not even matching its description, which includes the following:

> Its weak hull is more than compensated for by its advanced shielding matrix.

…But it has lower shields than the Firebird (an older design!), and it doesn't come with an unusually powerful shield generator like the D94-YV (It only has the D67-TM, which is carried by other Medium Warships).

These three ships need to be better differentiated from one another, and probably a bit better in general to make them more competitive with the Bastion, Manta, and especially the Mule.

**Comment by LocalGod79** [comment]
i think it makes sense that the Syndicate, Betelgeuse and Tarazed shipyards would have competitors that were very similar to each other...

**Comment by Pointedstick** [comment]
Yes, but it's still a missed opportunity to differentiate them gameplay-wise, and there's also no in-world reason why they still couldn't be broadly similar with each having a specific obvious advantage versus the others--think of the advertising potential! For example the Corvette could be even faster and have greater range; the Firebird could have even more hull durability and cargo space; and the Osprey could have even more shields.

**Comment by MessyMix** [comment]
Agreed! I can try work up a solution. I think that the Bastion and the Mule are paragons of the Medium Warship class, so if we can buff the others to be close to—but not perfectly at—their level, we can have more warship to the two most obvious choices at the moment. However, considering the recent price hike to the Mule, we should keep it as a superior choice, reasonably justified by its higher cost.

**Comment by LocalGod79** [comment]
are you guys going to play test the FW storyline to make sure that your Firebird/Osprey tweaks didn't mess with any of the battles, too?

**Comment by MessyMix** [comment]
I will when I have time to do so, or I might get someone to do it for me. Do you think a steam thread would do any good?

**Comment by Pointedstick** [comment]
I'm preparing some tweaks that shouldn't require any playtesting since nothing I'm changing will affect the AI ships' combat performance: bunks, crew, fuel capacity, cargo space, etc--just things relevant to the player.

**Comment by Pointedstick** [comment]
Done now in https://github.com/endless-sky/endless-sky/pull/3411 and https://github.com/endless-sky/endless-sky/pull/3922
