### ISSUE TITLE
Korath Disruptors are way too effective when spammed

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1628]
[jafdy](http://steamcommunity.com/app/404410/discussions/0/350542683192110636/#c350542683199247930):

> Due to the nature of the disrupter the Mereti will always become more efective in larger engagements.

And thus, the Kor Mereti always win a fight, even against the Quarg (in their current state), if their swarms can grow sufficiently large, because they just deal so much disruption damage, effectively granting complete piercing.

I ask that you do something to prevent this.

**Comment by jafdy** [comment]
How about using a SQRT on the disruption value. This should lead to a faster drop off as more disruption points(?) are added.

**Comment by Bladewood** [comment]
[Could work.](http://www.wolframalpha.com/input/?i=graph+1%2F(1%2B0.01sqrt(x))+and+graph+1%2F(1%2B0.01x)+from+x%3D0+to+x%3D10)

**Comment by KiLEdEnNis** [comment]
putting a simple max on disruption percentage can help too?

**Comment by jafdy** [comment]
Ok that's a point but wouldn't you use a if x<0 then x=0.
Or you could use a cube root value, that would exist for all x.

**Comment by KiLEdEnNis** [comment]
either a limit to x% or an asymptote (value gets near x but never becomes it, so a cap)

**Comment by jafdy** [comment]
Out of interest @KiLEdEnNis how much maths have you studied. Also my comment was directed a @Bladewood not you (slow Github update).

**Comment by KiLEdEnNis** [comment]
@jafdy exam year at highschool :3

**Comment by Bladewood** [comment]
@jafdy Maybe some guy would want to make it so that attacking while disruption damage is negative causes attacks to regenerate a ship's hull or something.

**Comment by MessyMix** [comment]
@KiLEdEnNis I wouldn't put a cap, because I don't think it's realistic. I think that (sqrt) is more effective than having a horizontal asymptote, because for sqrt, lim[x-->∞](3√(x)) is infinity. Just because a manual cap would reduce immersion.

**Comment by Bladewood** [comment]
Uh, I don't think that formula was supposed to spawn a link to a nonexistent issue.

**Comment by KiLEdEnNis** [comment]
about negative damage (heal), one day, when MZ makes the aura weapons (like Drak Draining Field), I hope we'll get a small healing aura (that heals allies near)
OP in large amounts? anything in large amounts is OP tbh

**Comment by Bladewood** [comment]
Anything is OP in large amounts, yes, but a certain level of disruption damage and above is universally unstoppable, because disruption power(?) does not depend on shield or hull strength.

**Comment by MessyMix** [comment]
True. What would happen if we made disruption damage a function of shield strength? That would still make shields relevant! Or perhaps make it dependent on shield regeneration (then disruption would be a negative regeneration)... I think that in these cases, the damage gets to bypass the shields, but the amount of damage dealt directly to the hull will decrease if shield strength / regen is strong.

**Comment by MessyMix** [comment]
Okay since everyone is so confused, let me clarify. @Bladewood said that disruption damage does not depend on shield or hull strength, and I am suggesting that it be changed to do so.

If the amount of disruption dealt to a ship was dependent on the ship's shield strength, then having disruptors wouldn't be so OP, and shields would still be relevant. For instance, my ship with 8000 shields will be less affected by the disruption than a 6000 shields ship, so only some of the hull damage will go through.

If, on the other hand, disruption was dependent on shield _regeneration_, then faster regenerating shields would have less disruption dealt to it and less hull damage can bypass the shields. So, if I have a ship with 500 shield regeneration (I think my Bac has regen around this value :P), disruption would affect my ship _less_ than, say, a 149 regen ship.

This way, shields can still be made relevant, and disruption damage would be less OP.

**Comment by jafdy** [comment]
The regen relation is an interesting idea but might that be too much added complication?

**Comment by endless-sky** [comment]
If disruption was changed in order to be much more effective on small ships / ships with lower shield strength, that'd make it very hard to travel through Korath space in something small like a Summer Leaf.

**Comment by Lineth** [comment]
I think he means it would keep its current effectiveness against small ships and be weaker against large ships.

I wouldn't use a small ship in Kor space anyway. mereti too stronk

**Comment by MessyMix** [comment]
Correct. Just make damage taper off as shield regen increases.

**Comment by KiLEdEnNis** [comment]
*cough* anti-disruption/disruption resistant outfits? o:

**Comment by Bladewood** [comment]
Oh dear. I have found a problem with negative disruption damage.
Giving a ship or an outfit the above, with a sufficiently large magnitude, returns us a dividebyzero error.
This is slowed by using radicals in the disruption damage expression, but sufficiently powerful anti-disruptor fire will eventually break the game, no matter the degree of the radicals we use.

**Comment by Lineth** [comment]
I think basing its effectiveness on shield regen or lack thereof as mentioned before is the most elegant solution IMO. Might actually have to buff the Mereti/nerf the Sestor if it happens as they are roughly even at the moment.

**Comment by Wrzlprnft** [comment]
The sestors fleet size was buffed in the past, if i recall correclty, so we could undo that.

**Comment by retrue** [comment]
But I have the impression that most times are the Mereti who win against the Sestor when they battle in Mesuket.

**Comment by MessyMix** [comment]
Does anyone have the talent or ability to make a change and PR it? I think making disruption based on shield regen is a great idea.

**Comment by Bladewood** [comment]
All I can figure out so far is that it's found at https://github.com/endless-sky/endless-sky/blob/436d345cb9a2b9a1a9990574ab16013d8155923d/source/Ship.cpp#L1846.

**Comment by Bladewood** [comment]
Tried something.
Now the disruptor feels *too* weak for some reason.
`...`
`ionization += ionDamage * (1. - .5 * shieldFraction);`
`double shieldRate = attributes.Get("shield generation");`
`	if(shieldRate > 1.)`
`		disruption += disruptionDamage * (1. - .5 * shieldFraction) / shieldRate;`
`	else if(shieldRate < 1.)`
`		disruption += disruptionDamage * (1. - .5 * shieldFraction);`
`slowness += slowingDamage * (1. - .5 * shieldFraction);`
`...`
