### ISSUE TITLE
Inverse Square Explosions

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1630]
Looking over the source as I have been working on various modifications to the game I noticed that there is no provision for an inverse square damage profile for explosions.

I was wondering of this was intentional to save on processing time or merely an oversight. My question is if this is something that could be of value in the game.

**Comment by Bladewood** [comment]
I really want this to happen, but I can't help but feel that it was intentional because physics in space...

**Comment by KiLEdEnNis** [comment]
what does that mean at all; ships imploding on death?

**Comment by LocalGod79** [comment]
@KiLEdEnNis i believe he means that damage from explosions should be less, the further you are from the centre of said explosion.

e.g. at 100px from the explosion centre, take 10000 damage.  at 10000px from the explosion centre, take 100 damage...

**Comment by KiLEdEnNis** [comment]
ah, should be a thing tbh

**Comment by SolraBizna** [comment]
It wouldn't be that processor-intensive compared to what's already going on to detect collisions. If this is added, it'll need a cap, otherwise you'd take insane damage because you happened to be right on top of that Sparrow when it died...

**Comment by Amazinite** [comment]
Well it would probably just use the current damages, just with altered blast radii to account for the tiny damage that would be taken if the blast radii weren't changed.

**Comment by Nechochwen-D** [comment]
I suppose I should give a short explanation of what this is to remove some of the confusion.

As it stands right now when there is an explosion whether from a ship death, a missile, or some other effect if a ship is within the "blast radius" of the explosion it receives full damage from it.

What I propose is a damage profile along these lines, damageMod = ((blastRad / 4) / distance)^2, this would mean that at 1/4 of the "blast radius" you would receive the full damage levels escalating exponentially the nearer you get and deescalating the further you get from the blast. As the largest "blast radius" in the game is 450px from the center of the ship and while it is bad news if you are caught in the blast for these ships it already is. There would be a cutoff for the outer edge of the blast though set at   "blast radius" * 3 at which point the damage would only be 1/144 of the initial.

**Comment by KiLEdEnNis** [comment]
having 2 "weapon" attributes or making the one better like this;
-set initial damage & max radius, then enabling editing the scaling (so damage barely drops at the max range or already gets low near) for editing possibility
that could be an idea too?

**Comment by retrue** [comment]
When capturing robotic Kor ships most of them explode under your nose. If the explosion is bigger when you are closer, capturing ships would be much more difficult.
And this change would affect very much the outcomes of battles. The explosion of a ship would destroy other ships that would explode too beginning a chain reaction.

**Comment by Nechochwen-D** [comment]
You both kind of miss the point.

My intention with everything I do on here is to add an element of realism to the game it is otherwise missing. The fact is having 200 ships stacked on top of each other is not a smart idea anyway so it would require adding two more elements to the AI, one to keep ships spaced out and another to prioritize getting away from exploding ships.

This would also put something of a "soft" limit on the fleet size for those players who like using massive numbers of ships due to there being a sweet spot between fleet size and chain reaction.

**Comment by Bladewood** [comment]
Fun fact: Shield beetles are much smaller than Kar Ik Vot 349s, but have explosions that are almost the same size.
They're annoying.

**Comment by Nechochwen-D** [comment]
That is not really my problem.

**Comment by retrue** [comment]
@Nechochwen-D If you want realism, you must consider that space is 3-D. Even if the ships seem to be together they can be separated by miles.

**Comment by LocalGod79** [comment]
for the record, a.i. ships *do* try to space themselves out (or your fleet of identical ships would always appear as one, flying "on top of each other")

**Comment by Nechochwen-D** [comment]
Both of you bring up good points. However @LocalGod79 certain fleet commands like gather and target can override the spacing of ships clustering them together if there are sufficient numbers of them and if you have a large enough fleet they end up bunched together anyway.

@retrue I understand what you are saying however if you want to talk about true realism it space for the distance condensed onto the screen you would also need to factor c limitations into what is displayed on both the screen and radar, planets and stars should have gravity, stars should be hazardous to be near, stars should be at least larger than planets. asteroids should be arranged into proper belts, the distances between planets should be considerably greater than it is, I really could go on with this list. The fact is that this game is at its core a 2-D game, I am not trying to make it a serious space simulator, I am however trying to add enhance it with an element of pseudo-realism to add flavor to the game.

Though we walk together,
We walk alone.
Nechochwen

**Comment by endless-sky** [comment]
It would be easy to avoid exponential increases near the center of the blast by doing something like this:

```
strength = distance / blast radius
adjusted damage = damage / (1 + strength)^2
```

That way, the damage never exceeds the base damage, but it still drops off exponentially.

**Comment by Nechochwen-D** [comment]
I am not entirely sure what you were trying to do with that Michael but the damage profile is a bit strange.

The easiest way to cap the the damage at whatever is set would be to use:
`damageMod = min(1, damageMod)`
and then it would still use the proper formula to calculate the damage outside of that maximum damage zone.

Though we walk together,
We walk alone.
Nechochwen

**Comment by endless-sky** [comment]
The equation I suggested is what you get if the blast is separated by a z distance equal to the blast radius.

The effect is that instead of getting a sharp cropping effect at some radius, the damage drops off smoothly as you get farther out:

![dropoff](https://cloud.githubusercontent.com/assets/11450262/18936644/0f91b106-85b7-11e6-91ce-c32bedd4603f.png)

So, it has a rounded profile close in but a 1/x^2 profile farther out.

**Comment by Nechochwen-D** [comment]
That makes a bit more sense although if going with this it vastly shrinks the critical threat area. On the other hand I was trying apply the way explosions work in real life and define the blast radius as the limit of where you are seriously threatened by the blast but have the explosion point be almost certain death to anyone over it if it is a ship exploding. But also scale it in such a way that missiles and other things are not rendered OP by having them deal an exorbitant level of damage.

However you decide to do this (or if you decide to do this) it's your game and the last thing I want to do is step on toes. My primary goal in this was to bring it to the attention of the community.

Though we walk together,
We walk alone.
Nechochwen

P.S. Was I correct in my assumption that ship explosions originate from the images null point?
P.P.S. One more thing. Is the distance from the blast counted to the center of the ship of the edge?

**Comment by pcordes** [comment]
`1/(1+r)^2` seems like a good middle ground, and being based on physical reality is a nice bonus :).  It might still fall off a little faster than we want near the centre, making the worst-case damage a rare nasty surprise (not great for gameplay).

The proposed graph shows it down to about 0.75 at the clip radius of the other function.  But it has a longer tail, which also seems good.

> ... drops off exponentially.

You mean quadratically.  (`x^2`).  Exponentially gets used casually to mean "anything non linear", but we're actually talking about mathematical functions here, so lets please restrict usage of "exponential" to `e^x` (exponential growth) or `1/e^x` (exponential decay).

`e^x` grows faster than *any* polynomial.  It is its own derivative: slope of `e^x` = `e^x`.

**Comment by tehhowch** [comment]
Not quite the implementation discussed here, but falloff for blast radius weapons was added in #3276
Also added was a keyword to prevent that scaling.
