### ISSUE TITLE
Conflict between flavor text and mission text for Albatross

### ISSUE THREAD

**Issue by sir-aureus** [endless-sky/endless-sky#1632]
The description for the pirate world Albatross includes the line "The first settlers on Albatross were anarchists who believed that in a society free from unnatural laws and constraints, everyone would happily and freely work for the common good."  This doesn't seem to fit in with the mission "FW Albatross 1" mentioning that Albatross objected to Alondo being gay due to their being a "very traditional population."

**Comment by Pointedstick** [comment]
That's true. Anarchists are not generally known for their traditionalism.

**Comment by retrue** [comment]
Well, I don't see any conflict. Description is about the foundation of the world. It can have changed along the time. For example, Australia was founded as a penal colony. That does mean that Australians are criminals.

**Comment by LocalGod79** [comment]
indeed, another example: the U.S.A. was colonized by people fleeing British "traditionalism", only to become more "traditional" than their parent-nation...

**Comment by Bladewood** [comment]
accurate.

**Comment by retrue** [comment]
Maybe that dialogue on 'FW Albatross 1' could be changed, something like this:

`	She looks genuinely surprised that you don't know. "Alondo is gay," she says. "There are few worlds here in the South where that would bother anyone, but Albatross is one of them. **Ironic, considering that their world was founded by open-minded people. Anyway**, Alondo is taking a break to go visit the Senate, while JJ deals with this particular diplomatic situation."`

**Comment by KiLEdEnNis** [comment]
it just feels weird, could be changed but not a fan of it

**Comment by endless-sky** [comment]
"Anarchist" and "open-minded" are not necessarily the same thing. For example, the planet could be populated by extreme libertarians of the gun-hoarding variety, who are not generally known for their open-mindedness toward people who are not like them.

**Comment by sir-aureus** [comment]
The issue isn't that it's particularly strange that an anarchist colony is homophobic, it's that the anarchist colony is described as traditional.

**Comment by LocalGod79** [comment]
again, i'll draw the direct parallel from Britain/U.S.A.

American colonists flee Britain and their stifling traditions: they are labeled anarchists (when they revolt).

Britain's social climate matures at a faster rate than the U.S.A. over the next two and a half centuries, and the U.S.A. (majority populace) becomes a more homophobic/traditional society than their parent nation.

the parallel is uncanny.

(please close this issue)
