### ISSUE TITLE
Values slightly less than a billion (or a trillion (or probably quadrillions and higher)) act weird

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1634]
Say I had a ship with two crew members (including myself) and I had a billion credits. If I took off, it would deduct 200 credits.
And then it would look weird. It would say I had ,1000.00M credits, rather than 999.99M, or just rounding it up to 1B.
This also happens if I (somehow) have 1T credits and deplete it with an incredibly small value (relative to the 1T credits).
Proof:
Install the all content plugin and buy a shuttle. Or at least something that won't make a significant dent in my budget (i.e. anything that is not an Archon).

**Comment by toilethinges** [comment]
I feel like I saw a commit that fixed this already.

**Comment by Bladewood** [comment]
This is the latest build.

**Comment by toilethinges** [comment]
Did I have a dream about this or something? Because I feel like I saw a commit fixing this. :/

Well, probably just me being weird.

**Comment by endless-sky** [comment]
That's not necessarily a bug, it's just a question of whether the format transition should happen at 1.000B or at 0.995B. I'm not sure it's worth changing.

**Comment by Bladewood** [comment]
After I thought about the issue:
It should read something like `~1000B`.
I've never seen a comma used in that way before, so this should work better.

**Comment by LocalGod79** [comment]
@Bladewood there are many countries around the world that use commas instead of decimals (you will likely see it again).

in Canada, anglophones typically used decimals, while francophones use the comma (so it's not even a nation-wide "standard", here).

**Comment by Bladewood** [comment]
I am fully aware that there are countries which use commas in place of decimal points. But that is not the point.

**Comment by Amazinite** [comment]
The problem @Bladewood is trying to point out is that numbers right on the edge of switching to a new "-illion" are shown as `,1000.00X` with the comma in the front, instead of `1,000.00X`.

**Comment by endless-sky** [comment]
Fixed in cec21da. I'd originally misunderstood and didn't realize there was a spurious comma involved. :)

**Comment by Amazinite** [comment]
:)

**Comment by Bladewood** [comment]
Well, we've arrived at a solution, so closing this.
