### ISSUE TITLE
"More Realistic" Hyper Jumps

### ISSUE THREAD

**Issue by ben0bi** [endless-sky/endless-sky#1635]
This is not an Issue, it's a feature request. More a de-feature request as you will see:

In the original EV, you had to go somewhere outside the system to initiate a hyperjump.
As it is explained in Endless Sky, a hyperjump is somewhat like an atomar explosion and the ship rides on the explosion waves which create some space-time-wormhole-thingy. So, if such explosion would be made near a planet, this would be not good for the planet.

I can press D on the planet menu, then J and jump directly from the planet. I think, this is a little bit "unrealistic" taking into account, what "propulsion" Endless Sky propagates here.

It would be more realistic if the ship first has to move away from the planets.
I can understand if this is too much for the player to keep him motivated.
But there could be a checkbox "Realistic Flight" or somewhat like that in the main menu.

I will look at the code in some time, maybe I will do it myself.

This is my first post here.

Regards,
ben0bi

**Comment by Pointedstick** [comment]
It's probably done that way purely for gameplay reasons. Having to fly far enough from the system center is just 10 second of dead time, even though it might be more realistic. Not sure what kind of person would check your hypothetical checkbox; what's the reward?

**Comment by Amazinite** [comment]
This has been denied multiple times before. Give me a minute to find all the related issue. 

This feature actually use to be in an early build of the game, but MZ removed it because the number of planets in ES systems is higher than EV, and getting far enough away from all of them to warp out was frustrating.

**Comment by Bladewood** [comment]
Let's not forget about [this](https://github.com/endless-sky/endless-sky/wiki/HistoricalTimeline).

**Comment by ben0bi** [comment]
Ok thanks. Did not mention that it can have so much planets in the systems. Also, in EV they did not seem to move around.
