### ISSUE TITLE
Have mission NPCs replenish their crew whenever the player lands

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1638]
http://steamcommunity.com/app/404410/discussions/0/350542683210161321/?tscn=1474998061

Because mission ships don't change when you land it is very possible to capture the wardragon over Zug and the Arfectas over in wanderer space.

Proposed solution, replenish crew when the player lands. It might be a bit immersion breaking but it's better then the semi-cheat on display in that thread. You may want to also repair the ships when the player lands.

**Comment by Lineth** [comment]
You can do the same thing for Marauder ships in the bounty-hunting missions too. Generates a great deal of money in the process.

**Comment by KiLEdEnNis** [comment]
the most logical way is giving them a chance to disappear (as if they were patched up & fled)

**Comment by LocalGod79** [comment]
mission ships repairing themselves will cause problems elsewhere - in the FW storyline, the player would be forced to destroy all the Republic ships, rather than attempt to leave them disabled as instructed...

**Comment by Wrzlprnft** [comment]
How about another keyword for mission ships, which enables or disables self-repair?

**Comment by endless-sky** [comment]
Fixed in 2f63019.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
