### ISSUE TITLE
"Dropped" fighters

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1639]
#1019

http://steamcommunity.com/app/404410/discussions/1/350542683212783806/?tscn=1475009829

It's back. I'm just reporting this and then I'm keeping out of it.

**Comment by Mark4666** [comment]
Direct copy and paste from my report in the steam discussion

Mark4666  
Fighter bay/deployment issue
I was recently playing through a new pilot file of ES and bought a carrier and some fighters to support my flagship however when I landed on a planet while the carrier and it's fighters where in another system when I took off the carrier abandoned the fighters in that system. the fighters where in the carriers before i landed and I hadn't given an order to deploy so I can't think what might cause this. I apologise for bad grammar.

**Comment by Admiral-Danforth** [comment]
I may be incorrect, but I believe it also affects drones

**Comment by jafdy** [comment]
It will also affect drones as they are the same as fighters to all intents and purposes.

**Comment by retrue** [comment]
@jafdy Nope, they are not totally the same. That bug in 0.93 already corrected that didn't let me dock just captured fighters, didn't affect drones. I could dock drones but not fighters.

**Comment by KiLEdEnNis** [comment]
mission escort carriers have their fighters/drones(?) out when you take off & they are in system;
carriers in system, fighters/drones are docked
land
take off, the carriers are waiting, they 1st have to dock the fighters/drones again
probably the same w/ your own carriers, and other systems

**Comment by endless-sky** [comment]
This could be related to #1646, which turned out to be due to "parked" fighters taking up escort slots. If so, the fix for that bug would have also fixed this.

**Comment by Mark4666** [comment]
bug is still present in 0.9.4

**Comment by retrue** [comment]
Yes, I have just reproduced the problem. Bug confirmed.
I took a Bactrian (with a jump drive) as a flagship and a Tek Far 109 (with hyperdrive) as scort with several drones and fighters, all of them docked.
I went ahead with the Bactrian to another system (that was reachable with hyperdrive) several jumps away. I landed. When I departed the Tek Far 109 was going to my position, but it had left all their drones and fighters behind.

**Comment by Mark4666** [comment]
the bug only seems to happen if you land while the escort was jumping from the system it was in to the next system on it's jump path otherwise it waits for what it's carrying before jumping.

**Comment by geojak** [comment]
as of 0.94 i still have this happen to me from time to time. it is somehow related to the escape button and loading a safe. Some fighters will be deployed and left by their ships even thought they were not supposed to be deployed and docked in the snapshot

**Comment by TJesionowski** [comment]
As of 0.9.x (post 0.9.5) I still see this. It seems to be that fighters get dissociated from their carriers when you land if they are in another star system.

**Comment by tehhowch** [comment]
Should be fixed by https://github.com/endless-sky/endless-sky/commit/683078008ca0cff823288478a858a88730d622e3

**Comment by jafdy** [comment]
Hmm, it hasn't come up in a while anyway.
