### ISSUE TITLE
Kar Ik Vot 349 has two extra turret mounts in sprite?

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1640]
It seems that turret mounts on the Kar Ik Vot 349 and other Kor Sestor ships are represented by large flat metal "plates".
But I see a problem here.
The Kar Ik Vot 349 has 8 turret mounts in-game, but the sprite seems to contain 10.
![349fail](https://cloud.githubusercontent.com/assets/16506683/18895357/0bdb53bc-84e7-11e6-84a8-87b4f0cd6a46.png)
(where red represents used turret mounts and blue represents unused turret mounts, obviously)

**Comment by endless-sky** [comment]
That's because it originally had 10 turrets and was 33% bigger, then I decided that was ridiculous. (47148f3)

I'm not sure if it's worth taking the extra plates out, because I like the texture they add even if it's confusing that they don't count as turret mounts.

**Comment by Wrzlprnft** [comment]
It was really ridiculous :D

It seems to me that this change would need more effort because it needs quite a re-design. Let it be the way it is until someone (looks at MZ) has a good idea (like shower-idea-brilliant-caliber).

Because it looks really completed and awesome it looks now.

**Comment by KiLEdEnNis** [comment]
it's my personal favorite base game ship, it's so complex, well made and sexy :D
so plz don't change it :(

**Comment by Pointedstick** [comment]
Yes, it's unbelievably cool.

**Comment by KiLEdEnNis** [comment]
some appreciation never hurts, makes MZ feel good (I hope) :3
