### ISSUE TITLE
Hai trackers have no guidance method specified, making them unjammable

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1641]
It's not clear that this is intentional since all the other guided weapons have one or more guidance methods specified.

**Comment by Bladewood** [comment]
I agree, this is weird, but they are "trackers" after all.

**Comment by endless-sky** [comment]
I did intend for them to use tracking - maybe infrared with a bit of optical mixed in, to give small Wanderer ships a better chance to dodge them.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/69de1d82cb5e9624dd020ec6eba373dee5a8e3ea

**Comment by Pointedstick** [comment]
Neato!
