### ISSUE TITLE
Drone class ships cannot be piloted by the player

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1643]
as it turns out, the Flycatcher can be outfitted with a Hyperdrive, Fuel Pod, Command Center, and enough other outfits to pass flight check, but cannot be made the Flagship (ridiculous as it seems).

i almost feel foolish raising it, but...(this issue is linked in the Steam thread that raised the point)

**Comment by jamespglaze** [comment]
Hey look I made a problem!

**Comment by KiLEdEnNis** [comment]
I remember when I could make a fighter my flagship
not sure what commit changed that

**Comment by Zitchas** [comment]
Opening more possibilities for people's gameplay options seems like a good thing to me.
