### ISSUE TITLE
Quarg do not become hostile if you attack the Wanderers (post-wormhole)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1644]
I think the Quarg should have a positive reputation line with the Wanderers (post-wormhole, that is), because it is plainly obvious that the Wanderers are benevolent and innocent people. The Quarg (apparently) always fight on the side of the innocents, so shouldn't they become hostile if you attack the Wanderers?
I don't see why the Quarg only protect the Kor Efreti, when clearly both the Kor Efreti and the Wanderers are being threatened with extinction by omnicidal AI warships.

**Comment by Amazinite** [comment]
Well do the Quarg know about the Wanderers and that they are "benevolent and innocent?"

**Comment by Bladewood** [comment]
After the wormhole opens, the Quarg visit the sectors near Sabriset far more often, and can also be seen landing on Spera Anatrusk, so they are sure to have done plenty of investigations.

**Comment by endless-sky** [comment]
The Quarg see themselves as the servants of the Drak, and the Archons don't really consider it their duty to protect species that aren't indigenous to this galaxy. Besides which, the Wanderers are clearly allied with at least one Pug faction, and the Quarg aren't too fond of the Pug.

**Comment by Lineth** [comment]
"Besides which, the Wanderers are clearly allied with **at least one Pug faction**,"

*narrows eyes*

**Comment by Bladewood** [comment]
@Lineth potential plot
yay

Anyway, I guess that makes sense.
