### ISSUE TITLE
There are still more problems with fighters and drones.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1646]
I am in Mesuket capturing Kor Sestor fighters and drones with a TEK FAR 109. By mistake I captured 8 fighters when the Tek Far 109 only has bays for 7 fighters. This eighth fighter is quickly disabled but it is not distroyed.
So, I return to Sevrelet to leave there my captured drones and fighters and I return to Mesuket to recover this eighth fighter. I can see the fighter on the minimap like a small green dot, but it is so far away that after ten minutes flying in that direction I have not been able to reach it yet. Of course, that far away it is not where I left it before.
I am playing the last development version as of now (up to commit 36 of version 0.93).
I include savegame.
[Doc Figure.txt](https://github.com/endless-sky/endless-sky/files/500793/Doc.Figure.txt)

EDITED: I have made a test. I deployed a just captured fighter and I left it behind on purpose, jumping away and landing on a planet. When I returned to Mesuket this fighter was still there, close to the center of the map. I tried to recall it but it didn't obey and was quickly destroyed. Anyway, I reloaded the game, returned to Mesuket and I discovered that this second fighter was too on a extreme of the map. It had drifted far far away too. So, maybe it is loading again the save game what make unreachable the fighters left behind.
EDITED 2: Another test. I captured a drone, deployed it and  jumped away leaving it behind. When I returned to the system to recover the drone, it didn't obey the recalling order.
In all these cases I was using only the flagship, without scorts.

**Comment by endless-sky** [comment]
It looks like this was two separate bugs:

* A ship stranded in a system where it cannot land will just drift.
* Parked fighters were counting toward your flagship's fighter quota.

Commit c33b6f6 should fix both.

**Comment by retrue** [comment]
I have texted the last commit and both bugs seem fixed. No more fighters/drones drifting away and they dock on the flagship.
