### ISSUE TITLE
Give Korath Grab-Strike a Missile Strength value

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1648]
We've seen examples of homing energy-based weapons that are vulnerable to anti-missile turrets, like the Pug Seeker. It's not fair for the Korath Grab-Strike to also have the ability to home in on targets and more, while being completely shielded from anti-missile turrets.
Alternatively, we could just remove the Missile Strength value from the Pug Seeker, but I'm sure that would present more problems somehow.

**Comment by LocalGod79** [comment]
Seeker is T1
Grab-Strike T2

anything is fair.

**Comment by Bladewood** [comment]
seems legit

**Comment by endless-sky** [comment]
Anything with a missile strength is displayed as a dot on the radar. That works for Pug Seekers because they're long-range weapons, but it'd look pretty confusing for the Grab-Strike.

**Comment by Bladewood** [comment]
I know it's way too late for this, but...
if Grab-Strikes are confusing when shown on the minimap, what about gatling guns?

**Comment by LocalGod79** [comment]
do you actually see gatling rounds on the radar?  usually it's just a couple of pixels next to the fighter-blip...
