### ISSUE TITLE
Crash on Launch in Windows 10

### ISSUE THREAD

**Issue by bcrotty** [endless-sky/endless-sky#1649]
I can't launch the game right now. I get the following error as soon as I launch it. I've tried various Compatibility Mode settings, and I've reinstalled the game.
![es crash](https://cloud.githubusercontent.com/assets/6155964/18996536/47cb2314-86f6-11e6-967d-a94c69661754.png)

**Comment by endless-sky** [comment]
By "right now" do you mean that it used to work for you? What version are you running? And, through Steam, or downloaded from here, or built from source? Do you have any plugins installed? And, is there anything in the "errors.txt" file in C:\Users\yourusername\AppData\Roaming\endless-sky\?

**Comment by KiLEdEnNis** [comment]
I don't have this issue on Windows 10

**Comment by bcrotty** [comment]
Nevermind. My endless-sky folder was a symbolic link to a cloud drive, and the link target had changed. Thanks for the help diagnosing it!
