### ISSUE TITLE
Equipment list when boarding isn't scrollable without mouse wheel.

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#165]
I'm probably the only person that doesn't have a mouse wheel, but it would be nice to be able to scroll the equipment list with arrow keys.

The ship and outfit lists on the map should also be scrollable with arrow keys.  Repeatedly clicking and dragging to scroll is clumsy.

**Comment by endless-sky** [comment]
What do you mean by the "equipment list"? Don't arrow keys already work in the outfitter?

I've added arrow key and page up / down support to those two map panels (commit dbab9f2).

**Comment by kyzentun** [comment]
I'm talking about boarding a ship to steal its equipment.  It's not much of a problem, because the most valuable equipment is at the top, but if the player wants something specific from a ship with lots of equipment, the thing can be out of reach.
http://i.imgur.com/YRtNgbO.png


The outfitter has its own problems with scrolling.  The interface shifts items around to expand and collapse the description when something is selected, which makes keeping track of where things are more difficult.  I think it would be better to have the info for the item in a section on the side, separate from the main list of items in the outfitter.

**Comment by endless-sky** [comment]
I've added support for arrow keys and page up / down to the boarding panel in commit b0e7689.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
