### ISSUE TITLE
Kor Sestor and Kor Mereti ships don't attack Cap'n Pester.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1652]
I am in Mesuket. Cap's Pester flights around without being attacked.
Intentional or bug?

**Comment by endless-sky** [comment]
Intentional.

**Comment by KiLEdEnNis** [comment]
they are persons, meant to just fly around for fun :P

**Comment by LocalGod79** [comment]
indeed, the persons so far are "real", and related to the dev of the game:
•"Cap'n Pester" is the incarnation of the game's spiritual inspiration
•M.Z. is our favourite game's creator
•M.M.K. put a lot of pretty ship sprites into the game (and creating a "collectable milestone")

so, their relationship with the in-game governments should be neutral (not at war)...

**Comment by KiLEdEnNis** [comment]
yeah, why would they attack the persons that made their ships :P

**Comment by LocalGod79** [comment]
(please close this issue)
