### ISSUE TITLE
Far Osk 27 description abbreviates name as "FS27"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1657]
`Far Osk 27`
> Because it is piloted by a computer and has no need for a cockpit or life support systems, the FS27 fighter is able to carry far more weaponry than any comparable human ship.

Shouldn't it be "FO27"?

**Comment by endless-sky** [comment]
That was intentional, as a hint to what "Far", "Met", "Osk" etc. actually are. "Osk" is the name for the Korath equivalent of the letter Ess in English.

**Comment by Bladewood** [comment]
ooh
learning korathspeak
