### ISSUE TITLE
Unfettered Hai World Classified as Wanderer?

### ISSUE THREAD

**Issue by Robotia** [endless-sky/endless-sky#1660]
The world Vara Ke'sok in Sich'ka'ara is classed as being owned by Wanderer.

However, landing on it gives the same screen that shows up on Unfettered Hai worlds:
![image](https://cloud.githubusercontent.com/assets/11097096/19018213/9fef486c-881e-11e6-8b1e-959a99da3cd5.png)

The spaceport indicates it is owned by Unfettered Hai:
![image](https://cloud.githubusercontent.com/assets/11097096/19018221/112441a4-881f-11e6-9c90-5f0ddd90b1ec.png)

Then again, is currently classified as a Wanderer World in my save:
![image](https://cloud.githubusercontent.com/assets/11097096/19018214/c16deea8-881e-11e6-8b1c-8eab0c44121d.png)

Is this a bug, or is my save corrupted? :confused:

**Comment by Bladewood** [comment]
This has already been fixed. (The part that was shown in the first screenshot, at least.) https://github.com/endless-sky/endless-sky/commit/d9ba5ba96f819fe74183fde5c6d43837f490d578

**Comment by Amazinite** [comment]
Duplicate issue.

#1571
#1610 
#1625
[Steam](http://steamcommunity.com/app/404410/discussions/1/350542145706490853/)
[Google Group](https://groups.google.com/forum/#!category-topic/endless-sky/bugs-and-troubleshooting/fzRP7pYldiw)
[Google Group again](https://groups.google.com/forum/#!category-topic/endless-sky/bugs-and-troubleshooting/tkkmOshpPfo)

**Comment by Amazinite** [comment]
@Bladewood Sich'ka'area is the system, Vara Ke'sok is the planet in that system.

**Comment by Robotia** [comment]
Woops sorry about that, I'll go ahead and close it.

**Comment by Amazinite** [comment]
All good. :+1:

**Comment by Bladewood** [comment]
Oh.
Derp.
