### ISSUE TITLE
Problems with keyboard acting like capslock was pressed

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1661]
This is a problem that has happened sometimes since the first version I played (0.92) and continues with the version I am playing now (last development).
On rare occasions, entry of text behaves weird, like CapsLock were pressed, when it is not. In these occasions, if I want that what I type appears on screen correctly I need to leave CapsLock pressed.
For example, I type **Ship 120** and appears on screen **SHIP !@)**. But if I left CapsLock pressed, then it will appear **Ship 120**.  In addition to that, when the bug happens the keyboard inside of the game window behaves like if it were configured for English instead of Spanish. For example, in a Spanish keyboard brackets () are above 8 and 9, but when the bug is present, inside of the game brackets are above 9 and 0.
Curiously, while the text appears wrong inside of the game, if I go outside the game, the text will be input correctly.
The error happens sometimes when pressing several times Caps and or CapsLock.

**Comment by MessyMix** [comment]
Capslock does not "shift" numbers. If you're really seeing SHIP !@# instead of SHIP 120, then it's something else.

Also, I don't know if it's related, but the game engine only recognizes ASCII input.

**Comment by retrue** [comment]
Well, it is a bug if my keyboard sometimes behaves like an American/English keyboard when it should behave like a Spanish keyboard, and usually it does that. And when this bug happens my keyboard still works perfectly outside of the game. And the problem it is not that I cannot type Spanish characters, I know that.
What I say is that sometimes my keyboard doesn't work as it should, and in these cases, with CapsLock pressed the keyboard types the number when I pushed the numbers instead of symbols.
And this problem only happens with this game. It doesn't happen with any other game or app. In fact, while the keyboard is failing inside of the game, I switch to a different window, and the keyboard works well. Switch back to the game window, and the problem continues. Close the game, open it again and the problem disappears.

**Comment by endless-sky** [comment]
Is it possible you're on a system where pressing Shift several times in a row activates "sticky keys"? For example, I believe that's what the Mac does (as an accessibility feature).

**Comment by retrue** [comment]
Nope, I am on Windows 8.1 64 bits. I don't have activated any accesibility option. And this only happens inside the game on rare occasions, and when it happens in the game, it is working correctly outside the game.

**Comment by jafdy** [comment]
The "sticky keys" is part of windows as well.

**Comment by retrue** [comment]
Yep, if I press SHIFT 5 times in Windows, an option pops up so you won't need to press keys simulatenously. But the behaviour in the game when the bug happens is totally different, and if I had activated that by mistake the accessibility option would be working outside the game too, not just inside the game.

**Comment by MessyMix** [comment]
How do you know what you input into the game? Is it when it asks you to type your name and such? Does it actually affect gameplay?

**Comment by retrue** [comment]
It doesn't affect gameplay. So, it is possible that the bug is happening and you don't notice it.
The only moments when you need to input text in the game are when naming or renaming ships, when naming your savestate (snapshot), when naming your character or when doing a search in the map.

**Comment by Jorbulous** [comment]
I noticed the exact same bug while naming a new ship. I'm using an English keyboard and have explicitly turned off the "tap shift 5 times" shortcut for sticky keys. (Used to play a game where I tapped shift a lot)

**Comment by Hyratel** [comment]
I think I have Repro for this - the cAPS lOCK State is stored as a Click-toggle via direct keyboard listen, not queried from the OS enter and exit Window Focus. if you switch Caps Lock while outside the ES window, from that point forward you will have your Caps Lock State inverted in-game until you do so again. I think this is an artifact of sampling the keyboard directly, instead of listening to the OS-level "Text Input system" (if such exists). it also behaves more like Shift Latch than Caps Lock - it affects the numrow keys as well as letters

**Comment by Amazinite** [comment]
>I think I have Repro for this - the cAPS lOCK State is stored as a Click-toggle via direct keyboard listen, not queried from the OS enter and exit Window Focus. if you switch Caps Lock while outside the ES window, from that point forward you will have your Caps Lock State inverted in-game until you do so again.

This is still the case for 3x speed toggling.

**Comment by tehhowch** [comment]
At least for me, ES will remember the "speed state" while in a different window, but as soon as I activate the Endless Sky window, my current caps lock setting is applied. 

Ubuntu 16.04

**Comment by Amazinite** [comment]
While caps lock will toggle all caps for alphabetical characters in game when using a text input field, it won't cause numerical keys to be entered as their special characters. Text inputs have also always respected the state of your caps lock (unlike fast-forward, which only toggles when hitting the caps key in game).

Given that the fast forward state not matching the caps state is a separate issue (#5177) and there haven't been any new reports of this particular behavior with text input fields in many years, I'm marking this issue as unconfirmed and closing.
