### ISSUE TITLE
'distance' destination from a ship

### ISSUE THREAD

**Issue by OmegaLokkes** [endless-sky/endless-sky#1662]
This is related to new boarding missions I was working on, which came to a grinding halt when I came to the realization that the 'distance' destination filter probably doesn't work from ships. Correct, or did I mess up the boarding mission myself?

**Comment by endless-sky** [comment]
It works fine for me, e.g.:

```
mission "Boarding"
	boarding
	destination
		distance 2 4
	on offer
		dialog "Do this thing?"
	on complete
		dialog "Done!"
```
