### ISSUE TITLE
MMK is kinda wimpy for a person [content/question]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1666]
currently, he's pretty difficult to catch due to his high turn rate (and subsequent jump rate), but killing M.Z. will make him hostile, and he'll rage upon you with his quad Blasters and dual Sidewinders when he finally tracks you down; hardly a fitting revenge, imho...

the Marauder Fury was fitted before Hai outfits (also as Wanderer/Kor 'fits were appearing), and now that i'm playing in the sandbox, it might be time for him to get a refit - M.M.K. certainly seems like the kind of character that would have at least some Hai outfits on his ship...

the Mad Quest is the pinnacle of the Marauder collectibles, and i believe that its weapons should be (significantly) more deadly, more befitting of a member of the Author Government, and more suited to the ship's raw indication (speed, missile boat).

proposed weapons;
		"Nuclear Missile" 2
		"Meteor Missile Launcher" 2
		"Meteor Missile" 140
		"Hai Tracker Pod" 2
		"Hai Tracker" 224

the double load out of ammo is intentional; since the ship is faster than anything else out there, all the ammo will be expended before being disabled and the player will still end up with a "stock" ship (no extra built in hard points).

so questions:
should be Pug or Quarg Intrusion Countermeasures waiting (instead of the meagre Security Stations)?
and; since he can appear in Korath and Wanderer space, would it be terribly out of place if he got his hands on a Small Bio'Cell?

**Comment by Bladewood** [comment]
The Mad Quest is indeed very wimpy... it only ever tried to save my ship from pirates on one occasion.
And it was obliterated...

...
Wait, you're throwing NUKES on it!?

Also, he should get countermeasures. Just don't talk about them as if they belong to the Quarg :|

**Comment by LocalGod79** [comment]
except your Skylances/Gridfires can't reach him...

remember, with the missile a.i., he's flying *away* from you at speed 1200+ (firing Trackers and Meteors (yes, after the initial Nukes))...

**Comment by LocalGod79** [comment]
```
		"Hai Tracker Pod" 2
		"Meteor Missile Launcher" 2
		"Meteor Missile" 140
		"Nuclear Missile" 2
		"Hai Tracker" 224

		"Pebble Core"
		"Small Biochemical Cell"
		"Hai Corundum Regenerator"
		"Hai Williwaw Cooling"
		"Intrusion Countermeasures" 3

		`"Biroo" Atomic Thruster`
		"A255 Atomic Steering"
		Hyperdrive
```
of course, if Nukes are deemed overkill (e.g. M.M.K. rushes in to assist the player with Pirates, and *everybody* dies), more Meteors/Launchers could be added instead...

**Comment by KiLEdEnNis** [comment]
> but killing M.Z.

couldn't you wait after the Wanderer story was done? :(

**Comment by LocalGod79** [comment]
i've never actually done it: i just know that the easiest way to catch M.M.K. is to make him angry, and the only way to do that is to kill M.Z..

**Comment by Pointedstick** [comment]
What's wrong with all you crazy powergamers who are trying to kill MZ's ship, capture Pug Arfectas, and fly around the galaxy in a fleet of 200 Bactrians?! 😝

Probably MZ's ship should just be invincible, like Captain Hector was in EV. That way the weapon load-out would be irrelevant.

**Comment by LocalGod79** [comment]
it's not just the revenge, @Pointedstick - M.M.K.'s load out does not take advantage of many outfits that have been added since his addition (many by @Wrzlprnft himself), and his weapons were never optimized for the hull (i'll admit that i got a little hasty/lazy for the 28th ship i had to outfit in that project).

besides these truths, the installed Security Stations hardly do anything to make the player pay for the ship (a true injustice)...

**Comment by OmegaLokkes** [comment]
I believe given the nature of the game in its current state, it would be easier for someone to get their hands on Pug intrusion countermeasures, thanks to the campaign, them being human-level and all, but even with two nukes, I doubt that one fury could take on the Quarg.

**Comment by LocalGod79** [comment]
i think you missed something: the Quarg (and everyone else) owe their existence to the good folks of the Author government, so M.M.K. would have no need to plunder the 'fits - the Quarg (and everyone else) would be happy to just hand them over...

the 'measures are just there to ensure at least one casualty (to cause Death Benefits) - the Quarg measures offer less plunder to the player than the Pug, so i'm inclined to stick with them...

**Comment by OmegaLokkes** [comment]
Oh? I didn't realize that a capturable ship was allowed to break the 4th wall

**Comment by Wrzlprnft** [comment]
Maybe we could give it another government, too.

**Comment by OmegaLokkes** [comment]
MMK isn't really the author, so the government doesn't really fit.

**Comment by LocalGod79** [comment]
i think the Author government is appropriate; while @Wrzlprnft is not *the* author, he is a (prodigious) contributor, and i believe that if the player destroys M.M.K. first, M.Z. should get upset (and visa versa).  devs have each others backs like that.  Perhaps the `Author` government becomes the `Developer` government?

breaking the 4th wall behind the scenes is less concerning to me than boosting the value of the Mad Quest by another 100k (and giving the player yet more powerful outfits to board other ships) with no real benefit - taking on either the Quarg or the Pug in a Fury is suicidal, so i don't think either is really more likely than the other.

**Comment by Admiral-Danforth** [comment]
Excuse me, but how do you actually find the Mad Quest? Does it just show up like Cap'n Pester does?

**Comment by OmegaLokkes** [comment]
Yes. It has a rare chance of spawning near your system, like a random fleet. You could fly into it's system, or vice versa, for encounters

**Comment by LocalGod79** [comment]
https://github.com/endless-sky/endless-sky/wiki/CreatingPersons

M.Z. uses the default frequency
M.M.K. and Cap'n Pester have frequency 300

with that said, the current M.M.K. is usually in and out of the system so fast that you may not notice him...

**Comment by LocalGod79** [comment]
pulled.
