### ISSUE TITLE
Varu K'est not updating on map/not clearing shipyard

### ISSUE THREAD

**Issue by Jorbulous** [endless-sky/endless-sky#1668]
Unlike the other planets the unfettered take over, Varu K'est doesn't update on the map and its shipyard/outfitter doesn't seem to be cleared.
![varu kest not updating on map](https://cloud.githubusercontent.com/assets/22588151/19034586/234cba6e-8919-11e6-94f8-1eacc8e253c3.jpg)
The above screenshot is from after the eye appears.

**Comment by Amazinite** [comment]
From the invasion event. 
```
planet "Varu K'est"
		attributes unfettered
		description `Varu K'est is a spare, ancient planet...`
		spaceport `The Unfettered are...`
		shipyard clear
		outfitter clear
```

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/1288

**Comment by Jorbulous** [comment]
I remember getting v0.9.3 after the invasion started so Amazinite is probably right.
