### ISSUE TITLE
Quicksilver description vs Headhunter

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#1669]
The quicksilver's description says it was meant to be the fastest ship capable of carrying two particle cannons, yet the headhunter can also carry two particle cannons and is slightly faster.

**Comment by Bladewood** [comment]
> The Megaparsec Quicksilver is a warship built around a single concept: to design the **smallest** and fastest ship capable of carrying two particle cannons. ...

Quicksilver sprite is 80x110 pixels. Headhunter sprite is 100x120 pixels.

**Comment by KiLEdEnNis** [comment]
also, "concept", doesn't have to be that

**Comment by Quantumshark** [comment]
It just seems a bit odd is all.

**Comment by jafdy** [comment]
Nicely done @Bladewood. @Quantumshark Unless you can come up with something better you won't get any where, we want a good game but this isn't a problem in it's own right.

**Comment by Quantumshark** [comment]
Possibly have a mention in the quicksilver's description that newer shops exceed its effectiveness, but at a higher price?

**Comment by Amazinite** [comment]
But does it really? Lionheart makes some of the best ships; this is pretty much made apparent by the Bactrian. So when Lionheart create a newer light warship that itself is based on speed (as seen in its description), it is obviously going to be faster than older designs (i.e. Quicksilver). So the mention itself is in the description of the Headhunter, saying that it's a newer design. And as @KiLEdEnNis said, concept doesn't mean that it's true/works in practice.

**Comment by LocalGod79** [comment]
@Amazinite; apparently @Quantumshark isn't aware that the Headhunter was implemented well after the Quicksilver.

that said, M.Z. is really careful, and it's not surprising that @Bladewood settled this issue in the first comment: it's *smallest*, not *fastest* (rendering the o.p. moot).

(please close this issue)
