### ISSUE TITLE
Wormholes in Sko'karak and Sabriset show friendly spaceports in map

### ISSUE THREAD

**Issue by sir-aureus** [endless-sky/endless-sky#1674]
![screen shot 2016-10-05 at 5 48 08 pm](https://cloud.githubusercontent.com/assets/22457724/19132944/ecc8de98-8b23-11e6-8cd7-62650c5ced0b.png)

Unlike the wormholes in Deneb, Ultima Thule, or Waypoint, the wormholes in Sko'karak and Sabriset that open during the wanderer campaign show as friendly on the galaxy map.

**Comment by Amazinite** [comment]
That's because those wormholes were given spaceports. NPC ships will only land on objects with a spaceport, so these two wormholes were given spaceports to create the effect of the Wanderers entering the Eye.

**Comment by endless-sky** [comment]
Fixed in d11ce01.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
