### ISSUE TITLE
Long snapshot names get truncated

### ISSUE THREAD

**Issue by hasteech** [endless-sky/endless-sky#1679]
Truncating is fine, but the full name never gets displayed anywhere.  Add a line to the info panel?

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/210

**Comment by hasteech** [comment]
That's been addressed in 0.9.4 so that it gets truncated, which is why I posted this.

**Comment by jafdy** [comment]
Someone is always upset about the design choices made in a game, You seem to have half buried us it the ways you would like to change the game but the change was made to MZ preference. He dose also plan to overhaul it.

>Fixed in a0f1064. Eventually I should do a more thorough overhaul of the load / save UI code, though, because it's pretty messy.

**Comment by hasteech** [comment]
The issues were requested to be posted separately, so I did.

I think the truncation in the snapshot list is appropriate and that's how it should work, which is why I said it's fine to begin with.  However, now that it's truncated, information is being lost.  That's a flaw in the UI, which is what I'm pointing out, along with a pretty simple solution, which is to just display the full name of the save in the info panel where the pilot name, location, date, and such are shown.  It's one extra line of relevant and useful information.

**Comment by Bladewood** [comment]
Maybe we could have the snapshot's name slowly "scroll" from the left to the right, like they do in some other games (which games in particular, I don't remember)?

**Comment by endless-sky** [comment]
I can just add a tooltip that shows the full name if you hover the mouse over it. That's pretty standard UI behavior, so people will know to expect it to happen.

**Comment by KiLEdEnNis** [comment]
that would fix it for all future things (but it may look a little bad)
