### ISSUE TITLE
How do you start story?

### ISSUE THREAD

**Issue by CubicDolphin** [endless-sky/endless-sky#168]
As the name suggests, I have no idea how to start any sort of story! I thought it would be after a set amount of time, but I've been playing for quite some time now and still no story missions. I've got a Shield Beetle, two Mules, a Bactrian, a Behemoth, and an Osprey, and the year is 3018. I've done as many jobs or special jobs you get for visiting the space port as I could find. I have visited every planet accessible, even through the wormhole (but there are still little circles for planets that I cannot reach, I've tried visiting every border planet, assume these open with the story). Did I miss something, or is my game being weird?

**Comment by endless-sky** [comment]
If you visit enough spaceports in the Free Worlds region of space, eventually you should be offered some intro missions working for them. Of course, it's also possible that you were offered those missions and turned them down. Have a look at your saved game and see if the "conditions" section includes anything with "FW" that was offered to you.

**Comment by CubicDolphin** [comment]
I've done many of the intro missions, and then after a bit I stopped receiving new ones. Did I make a wrong move?

**Comment by endless-sky** [comment]
This isn't really a bug. See the Steam discussions or the forum (https://groups.google.com/forum/#!forum/endless-sky) if you want to ask people for hints on progressing the Free Worlds story line.
