### ISSUE TITLE
hull repair cost

### ISSUE THREAD

**Issue by hasteech** [endless-sky/endless-sky#1680]
Even with death benefits, it's still very profitable to go around capturing stuff (it's still more profitable to capture with up to 2 deaths or so, IIRC).  The in-game universe is also so kind as to repair all your damaged ships for free.  Adding a hull repair cost should make capturing consistently less profitable without reducing the cost to purchase.  Reducing/removing shields from the beginner ships should extend the "Firefly" phase of the game and help differentiate true warships.  For early balance, it might be better to have the repair cost be separate from the hull purchase price and fairly low for most beginner ships.  The repair cost might need to be almost trivially small for the starter ships, but it would fit the lore of starting in a junker of sorts.  This would also enable trade-off ships that are high powered but have very high repair/maintenance costs.  It would also fit well with limited quality repair shops (for example, high-end shipyards have fancy 100% repair facilities, decent outfitters have 80% repair facilities, crappy space ports have 50% repair facilities, and field repairs can only go up to 35%).

**Comment by KiLEdEnNis** [comment]
doing that won't really change capturing; by the time you can capture big ships you're strong enough to easily do so, it'll actually punish new players with more debts when they take hull damage
and removing shields from starter ships? that'll change the entire game, FW would need new fleets, Merchants etc. and starter ships would instantly die; horrible idea, it would discourage new players from playing the game

**Comment by hasteech** [comment]
It's not supposed to make capturing harder, just less profitable.  Good point about getting disabled at 50%, though.  I forgot about that, but it doesn't change the overall picture, and with a few tweaks, overall balance should be the same.  Shield regen is pretty minor on a starter ship (let's say roughly equivalent to maybe 10% of capacity most flights), so a new starter ship with no shields and armor worth 2*(1.1*oldShield+0.5*oldArmor) should give you about the same effective HP.  No fleets would need to change and merchants and starter ships die as instantly as before, since the effective HP would be about the same.  It shouldn't punish new players if the repair cost on starter ships was trivially low (10s of credits), as I said.  It will make the "Firefly" phase a little bit harder, but that's too short and too easy already.

**Comment by Amazinite** [comment]
Hull repair and refuel costs have been shot down multiple times before. This is essentially a duplicate issue.

**Comment by KiLEdEnNis** [comment]
some things have the "gameplay over realism" idea in them, I'd say this is one of them, it's annoying & not worth it imo

**Comment by LocalGod79** [comment]
indeed, @hasteech, many of your issues are duplicates of existing issues (both closed and open)

please read through the now ~1300 issues that have been raised before spamming the issues page with even more duplicates.

(and close the issues you've raised that have been addressed or are pending)

**Comment by KiLEdEnNis** [comment]
just go to the issues tab and type a few keywords';)

**Comment by DingusShingleton** [comment]
I think #1650 would be a much more streamlined and fair-to-new-players way of balancing capturing and looting. Also, I submitted it. /disclosure

**Comment by hasteech** [comment]
I just noticed the issues search by default only includes open issues.  There were a bunch of closed ones that didn't come up when I looked.

**Comment by hasteech** [comment]
Based on the flame wars from some of the earlier times this came up, I see this is a sensitive topic.  I still think it could be balanced in a way that wouldn't bankrupt new players, but I get the impression MZ isn't interested.
