### ISSUE TITLE
add tab to inflight info panel for in-system targets

### ISSUE THREAD

**Issue by hasteech** [endless-sky/endless-sky#1681]
There are sometimes a lot of ships in-system, and it can be hard to cycle through to the right one without cycling past, especially when there are lots of fighters/drones and ships keep jumping in.  It would be nice to have a tab in the inflight info panel that just lists the targets in the system by name, model, affiliation, shields, and hull.  Selecting a ship in the panel would target, just like with escorts.

**Comment by KiLEdEnNis** [comment]
explain a little more please

**Comment by hasteech** [comment]
When you press <i> inflight, there's a 3rd tab called "targets" that looks very similar to the <Player Info> tab, only listing everything you would see cycling <n>.  Cycling <n> is awkward when FW and the Korath launch tons of drones.

**Comment by Amazinite** [comment]
What are you specifically cycling through for?
Hit R for the closest target; you don't need to keep pressing N to find targets.

**Comment by KiLEdEnNis** [comment]
if you mean cycling with the N key & your idea is having a list of all ships in the system; I'd say no, not worth it (screen would be too cluttered)

**Comment by Wrzlprnft** [comment]
I think what he means is a second ship list on the "i"nfo screen, accessable via a tab, which has exactly the same format as the players ship list, except it displays all npcs in the system.

**Comment by KiLEdEnNis** [comment]
I don't think that the practical use would actually make it worth

**Comment by DingusShingleton** [comment]
Personally, I have always thought that adding a way to cycle backwards through targets would be a simpler solution. But targeting when the system has 100+ ships in it can be a real pain. EG when I am trying to target big ships to board them but there are a million drones everywhere.

**Comment by hasteech** [comment]
It's useful for when I don't want the closest target.  Maybe I want the carrier instead of the drones.  Maybe I want the 349 or that Arfecta instead of all the other cruft in-system.

As Wrzlprnft put it, it's in the "i"nfo screen, and it's a separate tab.

As an aside, I need to pay attention to the markdown.

**Comment by Bladewood** [comment]
After reading that first paragraph, I now understand and agree with your request, but couldn't we just fly to and click on the ships?
Also, what about "invisible" ships, like cloaked ships or nanobots?

**Comment by DingusShingleton** [comment]
>couldn't we just fly to and click on the ships

To be fair, this applies equally well to targeting *any* ship. IE why have a targeting system in general when we can just fly to the ship we want and click on it?

As to your other point, I think it stands to reason that if a ship can't be selected/isn't visible in the main screen, it wouldn't show up on the list either.

**Comment by hasteech** [comment]
It's hard to fly to and click on the ship when you can't find it because it's somewhere in a long list of ships.  I was thinking everything that's visible when cycling \<n\> should be in the list.  It's not intended to change the underlying game mechanics, just be a more convenient way to access information that currently can be somewhat awkward to access.

**Comment by KiLEdEnNis** [comment]
an option could be that;
n just cycles
shift+n does what it does as well
then add some keys+n for like: target the one with lowest hull or shield percentage

**Comment by tehhowch** [comment]
Accurate selection of a ship to target can be performed from the map with #3070

**Comment by Amazinite** [comment]
I can understand why such a feature would have been helpful back in 2016, but at the start of 2017 with 0.9.5 we added the ability to zoom the game view, giving you much better visual coverage of larger battles. This way you don't need to fly to get a ship on screen in order to click it as often.

I'm also not exactly sure a new tab listing every targetable ship in the system that isn't an escort would be the best solution to not being able to cycle to a ship or click on it because it's off screen. This sounds like something that's desired for larger battles where cycling to the exact ship you want is difficult, or the ship you want could have been off screen. Well large battles will also have a large list of ships to scroll through; if you're trying to attack a carrier but there are multiple carriers in the list, how would you know which one is the one you actually want?
