### ISSUE TITLE
unparking many ships in distant systems is CPU-crushing

### ISSUE THREAD

**Issue by hasteech** [endless-sky/endless-sky#1682]
Park a big fleet (hundreds of ships), cross the map, unpark, and watch the CPU usage go nuts.  I think the pathfinding algorithm in DistanceMap is being called redundantly.  All of the ships are navigating to your current location, so the path only has to be calculated once per source system, until you make a jump.

**Comment by KiLEdEnNis** [comment]
if one ship has a hyperdrive and 1 has a jump drive, it wouldn't work; the jump ship would follow the hyper ship route, or the hyper ship would get stuck trying to follow the jump ship route

**Comment by hasteech** [comment]
Good detail.  That's easily manageable.

**Comment by LocalGod79** [comment]
indeed, each ship has its own unique turn and acceleration rates, fuel capacity, regeneration and possibly also drives - each ship must be processed as an individual...

**Comment by Wrzlprnft** [comment]
It's not about the ships actually jumping, it is about the path all of the fly (in their own speed), only two paths need to be calculated: one line-bound and one jump drive path. At the moment, every ship does that calculation.

**Comment by LocalGod79** [comment]
i believe there is also the hybrid jump-hyper path (for ships equipped with both), in addition to the two @Wrzlprnft described...

**Comment by hasteech** [comment]
Is jump-hyper different from jump-scram, due to different fuel usage?

**Comment by KiLEdEnNis** [comment]
no, scram takes same path as hyper, because it looks for the best route

**Comment by jafdy** [comment]
Yes, the scram drive uses more fuel and the path is calculated based on fuel.

**Comment by KiLEdEnNis** [comment]
but the shortest path w/ hyperdrive is the same path w/ scram drive, but scram uses x1.5 fuel
or maybe scram/jump combo messes something up

**Comment by Lineth** [comment]
Wait, is there a hotkey for alternating between FTL methods (assuming you have multiple drives ofc)?

**Comment by jafdy** [comment]
@Lineth No.

**Comment by pcordes** [comment]
@endless-sky I thought of an efficient way to speed this up (without cluttering up `class Ship` with a path-finding cache):

Keep a small cache of recently-used path-finding results in a std::map, where the key includes all of:

* fuel (current and max)
* fuel per jump
* type of jump drive
* current and destination system.

If only the player's ships use it, it doesn't need the key to include a government.

If path-finding is really re-done every frame, the same paths are going to be re-used *many* times.  With multiple identical (or even similar) ships in a fleet, *many many* times.

Expire cache entries every 600 frames or something, or when the cache has more than 100 entries, or some other heuristic.  (600 frames means a ship in a distant system won't realize for up to 10 seconds that a certain government had become hostile, so it could no longer land there.  If anything, a time lag for that information to reach your fleet adds realism, although perhaps not in a fun way.)

**Comment by endless-sky** [comment]
I think the pathfinding optimizations in 0.9.5 (having ships remember where they're going instead of recalculating every frame) fixed this.
