### ISSUE TITLE
Escorts attempting to refuel at hostile/restricted planets

### ISSUE THREAD

**Issue by hasteech** [endless-sky/endless-sky#1683]
It's fine that they can't refuel at hostile/restricted planets.  It's not so nice that they try to.  The AI seems to account for uninhabited systems and refuels before entering those, but it will try and refuel at a planet it can't land at, stranding them.

**Comment by KiLEdEnNis** [comment]
that is annoying yes, maybe it could change from "refuel before uninhabited systems" to "refuel before systems where you can't land on any inhabited planets" thing
but it wouldn't take bribing into account, an option that could enable escorts to bribe a planet once could pair with that

**Comment by hasteech** [comment]
I hadn't thought of having escorts bribe.  Most of the time I have this problem, bribing isn't necessary, as the escorts have enough fuel to reach me if they stop 1 system earlier at the unrestricted planet.

**Comment by KiLEdEnNis** [comment]
I mean if they are allowed to bribe they will treat hostile systems as regular ones, if not they will treat them as uninhabited systems, landing before entering when low on fuel

**Comment by endless-sky** [comment]
I believe this was fixed in commit 19d904ba.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
