### ISSUE TITLE
macOS retina problem in v0.9.4

### ISSUE THREAD

**Issue by aglv** [endless-sky/endless-sky#1689]
This was fine in v0.9.3. With v0.9.4, on my MBP with Retina,
* ES opens in window mode (this is ok)
* When I switch to full screen or resize the window, the UI scales down and everything becomes very small
* Mouse interaction doesn't work anymore (I'm guessing the GUI is misinterpreting the mouse coordinates as if the screen weren't hi-res)

**Comment by plependu** [comment]
ditto

**Comment by Amazinite** [comment]
Nice, so the fix to the bug on Windows caused a bug on Mac.

**Comment by endless-sky** [comment]
I don't have a Retina computer to test on, but if you're building from source, see if commit 3c39d0b fixes this.

**Comment by MessyMix** [comment]
Can confirm for macOS retina. I've never tried resizing, but this exists. It's just the fullscreen makes  the game run on a different resolution. For example, when I bootcamp my mac, the 'native' resolution becomes 2880 x 1440, even though my normal 15" is 1440 x 900. Perhaps the same happens with ES?

**Comment by aglv** [comment]
@endless-sky, yes, commit 3c39d0b fixed it

**Comment by aglv** [comment]
It took quite some effort to obtain proper dylibs for building on mac. My pull request #1698 adds the libraries as part of the repository, inside the Xcode directory, and switches to static libraries (for libpng and libturbojpeg).

**Comment by racer1988** [comment]
Hello,

this is still broken on Steam 
correct?

I can still reproduce the issue in the steam version of the game

**Comment by jafdy** [comment]
Yes, the steam version is updated only every few months. If you want this update then you will need to build from source.
