### ISSUE TITLE
Bought new flagship. Saved game. Now loading it will place me on wrong flagship.

### ISSUE THREAD

**Issue by wverlaan** [endless-sky/endless-sky#169]
1)left a disabled escort behind in system Gienah.
2)flew my fleet to system Markab and bought new flagship.
3)saved game (time to go to sleep).
4)loading will start at planet Hephaestus in system Markab but with the disabled escort as flagship. (Pressing "I" will show the escort in red on the top of the list.) When I press [Depart] I will be at the disabled escort and killed in seconds by pirates...game over.
![wave popbear 3017-02-24 txt](https://cloud.githubusercontent.com/assets/15714302/11020181/b7add11c-8617-11e5-8353-8d081f9e644d.png)
5)attached my save game."WaVe PopBear-3017-02-24" !! altered the files extension to PNG because otherwise I was not allowed to upload it.
6)question... what can I do to be able to continue this save? (I am capable of editing the save if you tell me what to do.)

**Comment by endless-sky** [comment]
In the Player Info display, just click and drag your new "flagship" so it will be on the top of the list, instead of the disabled ship. (Or, you can do the same in the shipyard or the outfitter.)

**Comment by wverlaan** [comment]
Dear Reader,

Thank you very much!
This was so easy, I feel a bit ashamed that I did not think of this.

Yours sincerely,
Walter Verlaan.

**Comment by endless-sky** [comment]
The underlying issue with a parked or absent ship being chosen as your flagship should be fixed in 0.8.7, so I'm closing this.
