### ISSUE TITLE
Asteroid explosions use final explosion sounds

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1690]
Currently, destroying a mineable asteroid produces one of the three final explosion sounds, which is a bit extreme if you ask me, given how small they are relative to actual ships.

**Comment by KiLEdEnNis** [comment]
small or medium final explosion sounds add that extra feel to it though

**Comment by gunqqer** [comment]
Turns out each asteroid has a nuke in it but it blows up in an alternate reality and the sound and light are the only things to go through to ours.

**Comment by Bladewood** [comment]
No, that's not what a nuke sounds like :|

**Comment by KiLEdEnNis** [comment]
@Bladewood  this nuke is that special snowflake

**Comment by gunqqer** [comment]
@Bladewood ok, a nuke the size of OP's genitals. 
There we go, tiny tiny [tiny tiny tiny] explosion

**Comment by Bladewood** [comment]
@gunqqer
![raindrop nuke](https://what-if.xkcd.com/imgs/a/12/raindrop_hits.png)
(where that house is your house)

would you like this to happen to you? if not, stop talking about this :|

**Comment by KiLEdEnNis** [comment]
beautiful drawing :P

**Comment by Bladewood** [comment]
https://what-if.xkcd.com/12/ If you seriously don't know where that's from, you have a problem.

**Comment by Nechochwen-D** [comment]
Well said @Bladewood.
