### ISSUE TITLE
Dump cargo button calls asteroid materials "outfits"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1692]
Flying a berserker, had 10 tons of silicon in my cargo bay.
Tried to dump cargo to raid a sparrow.

> Are you sure you want to jettison all this ship's spare outfit cargo?
> `Cancel` `OK`

**Comment by retrue** [comment]
And asteroid materials appear under "Special Outfits" in oufitters when you try to sell them.
Asteroid mining is a work in process.

**Comment by Amazinite** [comment]
Maybe it should just drop `outfit` from the dialog.

>Are you sure you want to jettison all this ship's spare cargo?

**Comment by endless-sky** [comment]
Fixed in f2acfc0. That dialog only shows up if outfits are all you have left in cargo, so just saying "...all of this ship's cargo" works fine.
