### ISSUE TITLE
Flycatchers in systems conquered by Unfettered Hai

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1693]
I am playing version 0.94, the Eye is already open, and I find sometimes flycatchers in Sich'ka'ara that is currently a world conquered by the Unfettered Hai.
Flycatchers are drones, they don't have hyperdrives, and Wanderer carriers don't exist. There is not way they can travel to another system to fight.

**Comment by endless-sky** [comment]
I think what was actually causing that is that the fleet placement code randomly chooses between placing a fleet in the current system, or placing it in a neighboring system in the process of jumping to the current system. That works if a fleet is hyperspace-capable, but for Flycatcher fleets they're ending up stranded. Commit cd8b9f6 should fix that.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
