### ISSUE TITLE
Militia ships have Free Worlds lines

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1694]
![freeworlds](https://cloud.githubusercontent.com/assets/16506683/19214494/86e9a062-8d53-11e6-8267-9776f740cd51.png)

And yet the Free Worlds haven't even been formed yet.

**Comment by Amazinite** [comment]
They're on the brink of forming; maybe they have the name, they just haven't declared independence yet?

**Comment by Bladewood** [comment]
Oh, also, this was somewhere in the dirt belt region.

**Comment by MessyMix** [comment]
@Amazinite you could argue that, but from events.txt, the formation of what is known as the "Free Worlds" was very rushed process. Revolution was imminent, but I don't think the name would have existed a year before the bombings on Geminus.
>Recently, a collection of local governments in the southern galactic arm sent the Republic Parliament what amounted to an ultimatum [...] the coalition calls themselves the "Free Worlds."

**Comment by Amazinite** [comment]
Yeah. Especially if it's Dirt Belt militia, that would need changed.

**Comment by KiLEdEnNis** [comment]
wouldn't it require them to get their owm hails like this; all FW hails except the one that would imply they are FW or something

**Comment by endless-sky** [comment]
This was fixed by #1907.
