### ISSUE TITLE
Increase scroll speed in outfitter listing

### ISSUE THREAD

**Issue by ssokolow** [endless-sky/endless-sky#1696]
The scroll speed on the Outfitters feels far too low. (It feels useless and bothersome to go through so many detents (scroll wheel steps) to scroll a single row)

You'd need to experiment, but my intuition is that you'll at least want to double the distance per detent if you're not implementing "smooth scrolling"-style animations. 

However, if you do animate it so large "distance per detent" values aren't disorienting, I'd suggest trying "half a line per detent" or possibly even "one line per detent".

**Comment by endless-sky** [comment]
Tripled the speed in commit 80cedcd.

**Comment by Bladewood** [comment]
I think 150 is a bit too fast. How about something a little slower, like 120?

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now (and includes user-adjustable scroll speed).
