### ISSUE TITLE
Escorts attempt to refuel on The Eye

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1699]
http://steamcommunity.com/app/404410/discussions/1/350544272212567530/

**Comment by KiLEdEnNis** [comment]
probably because of the spaceport
maybe it's all ships, but npc's would just show as if they went through

**Comment by Amazinite** [comment]
I know, I said that in the thread.

**Comment by gunqqer** [comment]
@Amazinite should I edit the steam post I made to add what you said so people who don't scroll still get the info?

**Comment by Amazinite** [comment]
It's not necessary, but go ahead if you want to.

**Comment by endless-sky** [comment]
Should be fixed by 19d904b.
