### ISSUE TITLE
Outfit scanning key is not documented

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#17]
I finally found out that I had to press "S" and not just target a ship and follow it for a while, but it took me some time :)

**Comment by endless-sky** [comment]
It's in the preferences panel ("Scan selected ship") but it's in the "menus" section because I didn't have any space left in the first column. (At some point I suppose I should reorganize the preferences key mapping list a bit.)

**Comment by akien-mga** [comment]
Ah indeed, my bad. Closing as invalid then :)
