### ISSUE TITLE
Game Crashed After Ship Sale

### ISSUE THREAD

**Issue by ephemera222** [endless-sky/endless-sky#170]
I saved up some credits to buy a ship without having to take out a loan from the bank. So what I tried doing was landing on Castor, selling my light shuttle (first ship), which would then give me the credits I needed to buy a heavy shuttle. When I sold the light shuttle not having bought the heavy shuttle immediately after and went back to the Castor main screen, the game crashed to my windows desktop. 

I am playing via Steam on Windows 8 if that helps.

**Comment by cocoknightcom** [comment]
Similar issue here. Clicked 'sell' but nothing happened, the game didn't respond anymore so I closed it. After relaunch I discovered that all my ships had been sold.

**Comment by endless-sky** [comment]
Were you running 0.8.4 (the default Steam version) or something more recent (which you have to opt into in the Betas properties)? If you're still on 0.8.4, this has possibly been fixed in the latest release.

**Comment by cocoknightcom** [comment]
default steam version on linux

**Comment by ephemera222** [comment]
I was running the default steam version. I will try the beta opt in at next
boot up.

**Comment by ephemera222** [comment]
Confirmed the steam beta fix of the issue. Thank you.
