### ISSUE TITLE
Human mining ships and ability to have (if added) mining ships camp in a system and mine for you

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1701]
I already know that the Korath are getting mining ships, so why not humans. If the humans get mining ships it should be kind of like the surveillance cubes in the Wanderer Mission. You put them in the system and they auto sell or like the cubes you have to go pick them up and unload the cargo. 

The last point could also be controlled with a key press.

If this is already suggested, but I didn't find anything.

**Comment by Amazinite** [comment]
> There will also be AI ships that mine asteroids, both to show the player it can be done and to add realism.

**Comment by Admiral-Danforth** [comment]
Does this include humans or just the Korath

**Comment by Amazinite** [comment]
> to show the player it can be done

**Comment by Admiral-Danforth** [comment]
Well that was an idiotic question by me.

**Comment by Amazinite** [comment]
And I don't see some sort of automated mining being an option for the player; it falls under the same thing of investing stocks or buying trading routes and having your escorts auto trade for you, which MZ has said no to.

**Comment by Admiral-Danforth** [comment]
It is kind of like fighters you could have an Aerie with two mining fighters on it. You enter a system deploy them and they mine, you land, sell, and repeat.

**Comment by Wrzlprnft** [comment]
I think, the player needs at min. To mark the asteroids the fighters should be mining, but otherwise i like the idea.

The game is sometimes compared to a "free 2D elite dangerous". We could look how much automation the mining has there: the player still needs to shoot the asteroids, but i think he can buy little drones which collect the stuff.

**Comment by retrue** [comment]
A mining scanner, pushing a key would activate the mining mode and allow the player to target and cycle the minable asteroids and would put scort ships in mining mode. Scorts would need the mining scanner to be able to mine.

**Comment by KiLEdEnNis** [comment]
@Wrzlprnft having a fighter command ordering them to collect flotsam (like the asteroid debris) would be cool, and a special fighter to do so would be cool as well

**Comment by IFailAtGaming** [comment]
I think we already have that special fighter, that flying box could do it

**Comment by Admiral-Danforth** [comment]
im saying that the fighter can mine too

**Comment by Amazinite** [comment]
Any fighter would be able to mine as long as they have a weapon, they just don't have the cargo to pick ore up.
