### ISSUE TITLE
Weird hyperspace jump thing

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#1702]
If you initiate a jump then go into the map and select a new destination the jump will continue, but if you try to jump again it won't work. This could be from jumping to the wrong place and trying to change your destination. In the 'chat' it says "This system cannot be jumped to" or something similar

**Comment by Bladewood** [comment]
Hyperdrive or jump drive?

**Comment by gunqqer** [comment]
@Bladewood Jump drive but it may happen with a hyperdrive except I never tested it. Damn primitive things need hyperspace links to function

**Comment by LocalGod79** [comment]
indeed, re-plotting a hyperspace route during hyperspace travel is impossible.

your nav-computer cannot plot a course to somewhere in normal space *while you are **in or entering*** hyperspace - it doesn't know where you really are, in spite of knowing where you were and where you *were* going.

one wrong move and you could jump into a star...or an asteroid!

just wait until you re-enter normal space before plotting your new course?

**Comment by gunqqer** [comment]
Just pointing out a possible bug, @LocalGod79 . If it is intended it should be more explicit that you can't do it instead of just saying "you can't jump to selected system"

**Comment by LocalGod79** [comment]
sorry @gunqqer - was trying to be both humorous (Han Solo makes a similar comment about rushing hyperspace course plotting) and confirming the behaviour (putting it into different words)

**Comment by endless-sky** [comment]
That's because Han couldn't just tell Luke the truth, which was either, "There's a plot device that makes it so we can't just jump into hyperspace whenever we want," or, "This entire ship's computing resources are provided by a single TI-82 calculator. Including life support."

**Comment by endless-sky** [comment]
Fixed in 55e7ffd.

**Comment by WetDesertRock** [comment]
Shouldn't this be cloased?

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
