### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile (OS X)

### ISSUE THREAD

**Issue by andyspurgeon** [endless-sky/endless-sky#1703]
New contributor... wasn't sure if I should add this to [#567](https://github.com/endless-sky/endless-sky/issues/567) or open a new issue, but I decided to open a new issue because of the elapsed time since that report was filed.

I recently cloned the repo and built from source, using OSX. I received multiple instances of the warning: "libpng warning: iCCP: known incorrect sRGB profile"

I ran 'pngcheck' on the entire images folder and searched for iCCP chunks in the output. I found the following files had them:

- effect/bullet impact-0.png
- effect/bullet impact-1.png
- effect/bullet impact-2.png
- effect/bullet impact-3.png
- effect/bullet impact-4.png
- effect/bullet impact-5.png
- effect/bullet impact-6.png
- effect/bullet impact-7.png
- effect/flotsam copper.png
- effect/flotsam iron.png
- effect/flotsam platinum.pn
- effect/flotsam silver.png
- effect/railspark~0.png
- effect/railspark~1.png
- effect/railspark~2.png
- outfit/dwarf core hai.png
- outfit/huge atomic steering hai.png
- outfit/huge atomic thruster hai.png
- outfit/large atomic steering hai.png
- outfit/large atomic thruster hai.png
- outfit/medium atomic steering hai.png
- outfit/medium atomic thruster hai.png
- outfit/railgun.png
- outfit/small atomic steering hai.png
- outfit/small atomic thruster hai.png
- outfit/tiny atomic engines hai.png
- outfit/tiny atomic steering hai.png
- outfit/tiny atomic thruster hai.png
- projectile/tinyflare+0.png
- projectile/tinyflare+1.png
- projectile/tinyflare+2.png
- ship/hai flea.png

Please let me know if you need additional information.

**Comment by Alkallid** [comment]
This is all post-0.9.2, right? Local's mini weapons, Wrzl's Hai rebalance, and the astedoid minerals.

**Comment by Wrzlprnft** [comment]
Most of those should be from local.

**Comment by LocalGod79** [comment]
yeah...Photoshop saves the IEC standard IEC 61966-2.1:1999, while GIMP and libpng use a newer profile that is not the IEC standard.

i thought i had corrected the colour profiles before merging.  if i get some time tonight, i'll make a pull request with the corrected profiles (but i think i may need to re-fork my repo - remote tracking branch commits are getting excessive).

**Comment by endless-sky** [comment]
Fixed in endless-sky/endless-sky-high-dpi@1f3e638 for the high-dpi images, and 96d3185 for the regular images.

**Comment by andyspurgeon** [comment]
Fix confirmed after pulling the most recent update!
