### ISSUE TITLE
Option to change fps limit

### ISSUE THREAD

**Issue by Middleon** [endless-sky/endless-sky#1704]
Is there any chance that there could be options to run the game at frame rates higher than 60fps? 
Asking for a friend (warp_core).

**Comment by jafdy** [comment]
Game time is measured in frames so increasing the frame rate would increase running speed. If you where to set it so that for every "time" frame there are 2 "graphics" frames then you would see no change in what the game actually looks like as thing only happen once per time frame.

**Comment by Middleon** [comment]
Thank you, ill pass this on
