### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Middleon** [endless-sky/endless-sky#1705]
Is there any chance that this game is going to be multiplayer soon? My friend (warp_core) really wants to play the game with me.
He makes me post for him due to his epilepsy :(

**Comment by Amazinite** [comment]
REEEEEEEEEE

**Comment by Middleon** [comment]
He also wants to know if you can change the code to use java because he thinks its the better language...

**Comment by Amazinite** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=545464233

**Comment by Middleon** [comment]
Lmao he just asked if this game will ever be free...

**Comment by Amazinite** [comment]
Github isn't the place to be trolling.

**Comment by warp-core** [comment]
How dare you accuse me of preferring Java to C++ and suggesting that I have an illness that legitimately affects people and can cause enormous damage.

**Comment by Middleon** [comment]
How are you posting right now ! You made me look bad infront of my internet friends by making me ask stupid questions !!one!1! Im shaking with rage right now... Did you really lie about your epilepsy??????

**Comment by KiLEdEnNis** [comment]
> infront of my internet friends
are we?

**Comment by Middleon** [comment]
Are we not?

**Comment by Wrzlprnft** [comment]
Please keep the github page... Clean of such posts. Or, as derpy said: Github isn't the place to be trolling.

**Comment by Amazinite** [comment]
> (Please close this issue)

**Comment by Middleon** [comment]
Deepest and sincerest apologies.
