### ISSUE TITLE
Question: CMake/CLion

### ISSUE THREAD

**Issue by andyspurgeon** [endless-sky/endless-sky#1708]
I prefer Jetbrains CLion as my c++ IDE (it's cross platform and offers a consistent experience across my Macbook and Windows desktop). It's also very similar to the Webstorm IDE I use for node.js development.

Anyway, CLion is tightly integrated with CMake and uses it for build configurations. I've got the project building using CMake/CLion on both Windows and OSX. This required no repo changes, just the addition of some cmake-related scripts and a custom CMakeList file. 

Would anyone else be interested in me posting these files somewhere, or doing a short write-up on the setup? I could create a pull request, but I'm not sure that anyone wants to take on support for this, so I understand that may not be of interest.

Thanks!

**Comment by andyspurgeon** [comment]
I made [a fork of the project](https://github.com/andyspurgeon/endless-sky) and added my CMake/CLion solution there, along with a README that explains the solution and how others might use it. 

I'll close this issue shortly, but wanted to put that info in here for posterity, in the event someone else searches for the topic.

**Comment by Amazinite** [comment]
Why close?

**Comment by andyspurgeon** [comment]
Closed for 2 reasons:

1) Lack of comments/interest in the subject
2) I posted a solution in my fork of endless-sky and noted that in my last
comment, so there is a solution available

I can reopen if there is need/interest, but it didn't seem necessary.

Best,
Andy

**Comment by Amazinite** [comment]
I'm just wondering because @endless-sky hasn't chimed in on the subject yet. No comments from the common plebs doesn't always mean that it won't be interesting to MZ.

**Comment by andyspurgeon** [comment]
Reopened per Amazinite's comment.

**Comment by Bladewood** [comment]
Darn, I liked the perfect 6:1 issues:pulls ratio.
Oh well.

**Comment by endless-sky** [comment]
It's already complicated enough to maintain the existing three build systems, so I'd rather not add a fourth.

**Comment by andyspurgeon** [comment]
Totally understand. I'll close this issue and my fork is available if anyone wants to leverage my solution.
