### ISSUE TITLE
Dreadnought Deployment removes Skein and Roost from FW Large Fleets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1711]
http://steamcommunity.com/app/404410/discussions/1/348292957933795197/

[Inclusion of Roost and Skein in FW large](https://github.com/endless-sky/endless-sky/blob/master/data/events.txt#L729)
[Dreadnought deployment event that replaces them](https://github.com/endless-sky/endless-sky/blob/master/data/events.txt#L2041)

Intentional or mistake?

**Comment by KiLEdEnNis** [comment]
I'd say mistake, they'd want at least Skeins in their fleets

**Comment by LocalGod79** [comment]
oops on my part - didn't remember the last event that changed the FW fleets.

i don't think it's possible to have the dreadnoughts deploy before the Southern Carriers, so a small tweak to the dreadnought deployment is all that's required...
