### ISSUE TITLE
Long system names slip off of the right-hand map panel

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1714]
![55ffad77caa64415a879090e2696895d](https://cloud.githubusercontent.com/assets/17688683/19420461/c26e8136-93b9-11e6-9220-f88bf0792b13.png)

I believe that Gamma Cassiopeiae is the only vanilla system with a name long enough to do this.

**Comment by endless-sky** [comment]
As of 67980b7 I've added a bit more space for the names, so all vanilla system or planet names should fit.
