### ISSUE TITLE
engineers outfit

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1725]
i think i suggested something similar in the past, but cannot find it now, and this is a little different anyway.

human answer to hull repair. outfit takes up both outfit space and crew capacity. much lower repair rate than alien systems. crew requirement restricts to larger ships. large ships with low crews would have to install bunks to accommodate the outfit. this would also allow human carriers to repair their fighters/drones while docked.

**Comment by Bladewood** [comment]
The fact that there are no hull regenerators in the early game is what makes boarding and stuff risky imo.

**Comment by retrue** [comment]
But hull regenerators don't work if the ship is disabled anyway.

**Comment by Morcleon** [comment]
But when you successfully board a ship, its hull is set to the minimum required to not be disabled, and the shield starts regenerating again. This makes it so that a stray shot won't re-disable the ship as easily.

**Comment by pcordes** [comment]
An in-universe reason to justify not having this:  Being out of the ship working on the hull during flight (especially combat) seems like more risk than your crew is being paid for.

Repairing docked fighters in a carrier makes sense, though, since the fighters aren't powered on at the time, and they're inside a "safe" working area.

**Comment by Morcleon** [comment]
I feel like it's less that and more of damage control from inside the ship. Rerouting power, putting out fires, patching hull breaches, etc.

**Comment by wambat1** [comment]
perhaps it would be possible to set a cap to the hull repair on this unit to represent the limitations of human repair. somewhere between 50% and 75%? 

    On Sunday, October 23, 2016 10:54 PM, Morcleon <notifications@github.com> wrote:
 

 I feel like it's less that and more of damage control from inside the ship. Rerouting power, putting out fires, patching hull breaches, etc.—

**Comment by Morcleon** [comment]
I'd put it at 75%, since small ships become disabled at 50% hull. It would probably be possible to cap it by having it not function when the hull is above a certain percentage.

**Comment by wambat1** [comment]
i would envision this outfit being designed to be practical only on large ships with large crews; so would still be helpful even if capped at 50%. in fact, this outfit would be a likely response by the Oathkeeper's to contact with the shield negating technologies of the Kor.
