### ISSUE TITLE
merchant escort behavior

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1726]
merchant escorts with appropriately large crew capacity; like corvettes, mules, any of the heavy warships; will seek to claim disabled pirate ships if their fleet initiated the combat or did the most damage or fired the disabling shot (choose one or all for best balance). appropriate merchant ships would then board/capture the disabled pirates after combat is concluded.

if a disabled ship is thus claimed, a dialogue will be activated if the player attempts to board the disabled ship. if the player proceeds with capture the merchant fleet will become hostile; the player can then chose to pay off the merchant fleet (dialogue again) to end hostility and avoid negative impact to standings.

**Comment by retrue** [comment]
Capturing ships means a battle where crewmen die. I don't know if many crews of merchant ships would agree to do that.
And warships are more interested in disabling/destroying pirate ships than in capturing them.
A way of using your idea would be creating a "boarder" personality where a small random number of merchant ships would try to plunder or capturing pirate ships, but never as the default conduct for merchant ships.
