### ISSUE TITLE
[minor] Game blurred in a maximized window

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1727]
![boxfail1](https://cloud.githubusercontent.com/assets/16506683/19540641/e7bd55f8-962e-11e6-9d90-0107016840d0.png)
![boxfail2](https://cloud.githubusercontent.com/assets/16506683/19540643/ea20c94c-962e-11e6-8ce8-f14fe487ce6d.png)
Look closely and you will see that there is something wrong there.
(it's immediately obvious when you look just below the blue sun)
Very minor, but once you notice it...
(also, screen resolution is 1440x900, maximized resolution is idk (now I know, it's 1440x847))

**Comment by endless-sky** [comment]
Normally the game forces the window to have even dimensions, but on certain versions of Windows and on certain screens, a maximized window's dimensions are odd. As a result, the exact center of the window is not aligned with the pixel boundaries, and everything gets fuzzy. I'm really not sure what the most elegant solution to that is, so I haven't addressed it yet.

**Comment by Bladewood** [comment]
Yup, that seems to have fixed it!
