### ISSUE TITLE
[Pay Off] (a single loan) button for the banking screen

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#1728]
I somewhat often find myself in a position where I would like to pay off one or several loans/debts but not others. In order to do that, I select [pay extra] and then just mash a bunch of numbers, like 10 or 15 digits (enough to know that the loan will be completely paid). While this certainly works, it's not a particularly elegant way of doing business.

Initially I was thinking about another button on the banking screen, but I think it's already dense enough as is. However, if upon pressing [Pay Extra], there was a third button that said [Pay Off] or [Entire Amount] or something along those lines, I believe it would be splendid.

Obviously this isn't a big deal, but it is one of those little quality of life things that adds a certain polish to the game, so I figured I would post it up here anyway.

**Comment by endless-sky** [comment]
In the dialog, you can enter numbers with any of the suffixes that are used for displaying numbers elsewhere in the game (M, B, or T, and also k). That makes it relatively easy to specify a large number.

**Comment by DingusShingleton** [comment]
Aha! Good to know... i had a sneaking suspicion that there was some functionality I was unaware of which would make it easier
