### ISSUE TITLE
player info column organisation 

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1729]
click on ship/model/system/shields/hull/fuel/crew to organize the fleet list alphanumerically by that category.

**Comment by wambat1** [comment]
@DingusShingleton 

exactly what occurred to me when i read the first comment. if the player could edit that number column it would make changing ship order much easier, and less liable to error. the flagship issue could be handled by making the first row unaffected by column organisation. it would then be very easy to set a new flagship by simply entering the value of the first row (i assume either 0 or 1)

i have some further suggestions for the player info window:

- place licenses above tribute, since licenses can be expected to be a shorter list.

- make the list of tribute systems expandable (my clicking on the "others") and allow scrolling.

- provide a popup with the total value of ships destroyed when mousing over the combat rating (abbreviated in the same way as net worth).

**Comment by retrue** [comment]
Or you can always leave the flagship on top of  the list independently of the order of the rest of the ships.
Moving any ship above the flagship in the list would make it the new flagship.
With huge fleets it is necessary to have ways to arrange and manage the list.

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/2/1843493219419602035/?tscn=1481394912

**Comment by endless-sky** [comment]
Fleets with more than a dozen ships or so really aren't one of the primary focuses of the game; in fact, all the missions are designed to be beatable with a single ship. So anything that's only needed for giant fleets is not a high priority.

That said, if I have time I'm planning to add an experimental zoomed-out tactical mode in 0.9.5 (where you can click and drag to select squads of your ships, assign hotkeys to them, and give them separate orders), but it'll be a while before that kind of game play is fully supported.

**Comment by KiLEdEnNis** [comment]
that'd take a lot of coding etc, but it would give the game a whole new dimension
now it's a plain 2D space game, which would become like a "strategy game" (2D of course)

maybe also consider this;
if in a mission there are for example 2 fleets (a friendly and an enemy, for the sake of explanation), add support that would split the 2 fleets to different sides (so when you join they're not mixed like maniacs)
being able to do that for an individual ship would be very cool (even set the exact coordinates), but it shouldn't get too complicated

that would give a use for the "squads", and being able to control ally ships that aren't yours would be awesome (and of course Ctrl + clicking an escort would select/deselect them to add to a squad)
