### ISSUE TITLE
Exponential Bulk Freighter...

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#173]
(Sorry for the long-winded post; I am enamored with the sound of my own typing. Skip to the last two paragraphs if you're interested only in the "fix", but do stop to look at the screenshot on the way...)

In this game, there appears to be no limit on the number of "escort" ships you can have with you. (This is not a bug, this is _awesome_.)

Also in this game, there are random pirates who are attracted to your fleet according to the number of freighters you're flying with. (This is also _awesome_, especially since it is _far_ more balanced and fun than the corresponding "feature" in EV.)

Unfortunately, it seems that the pirates' composition is determined only by the number of freighters, not the size. This does manage to discourage the so-called "Exponential Star Barge" strategy, as a flock of Furies, Sparrows, and Hawks will manage to pick off at least a few in a given pass. However... if the ships are Bulk Freighters instead, even fairly stock ones... by the time pirates start showing up, you have an undulating mass of well-shielded Bulk Freighters capable of firing dozens/hundreds of Laser Turrets at any threats.

![2015-11-08_00001](https://cloud.githubusercontent.com/assets/427857/11022309/b87a9e76-8618-11e5-841a-964ba6247a81.jpg)

The bank will happily give you loans big enough to buy dozens of new Bulk Freighters at a time by the end, and your profits only grow and grow and grow. More and more pirates come, and more and more die. _No_ amount of Sparrows threatens this group at any point. Not only does your money increase exponentially, but your combat rating does as well... I had 829 kills (combat rating 6) when I started doing this yesterday, and had 21297 kills (combat rating _9_) by the time my session ended.

Out of curiosity, I decided to re-arm and re-outfit these ships to be more capable in combat. A Bulk Freighter can carry 3 Heavy Laser Turrets and 2 Heavy Anti-Missile Turrets. Equipping them all was a pain (literally, it hurt my wrist), but the result was an unstoppable death wave that followed me through every system I went to. Dominating planets and fighting off the strongest of ships became easy.

Now, I know that by doing this, it's my own fault if my fun was "ruined" by this being possible. I could just as easily have chosen not to fly around selling cargoes and buying bulk freighters while watching the pirate fleets burn around me. But in my defense, it was pretty amusing... :)

While this whole thing was going on, I tried to think of ways to fix this. It should remain _physically possible_ to have this many bulk freighters or other large ships flying with you. The main fix I came up with is to alter the _composition_ of the fleets that attack depending on the _composition_ of the player's fleet (in addition to altering the _size_ as is already done). I noticed that on the rare occasions a component of my "Unstoppable Death Wave" was disabled, it was because of a Leviathan or other large pirate warship. By my reckoning, if even 10% of the attracted pirates had been in Leviathans, I would have lost a Bulk Freighter every few jumps, absent skillful and proactive intervention on my part. (And skillful and proactive intervention is something we want to require, in the event of such a large freighter fleet, right?)

As for the exponential combat rating thing... in my opinion, very small ships should cease contributing to combat rating if you have a very large fleet (or ship). I think, however, that if exponential strategies in general are reduced in effectiveness, the combat rating problem becomes less important.

(Now to sell the Unstoppable Death Wave and go back to _playing the actual game_... :P)

**Comment by endless-sky** [comment]
This is unrelated to the main point of your post, but note that you can use shift-click or control-click to select any number of your ships in the Outfitter and customize them all at the same time instead of having to adjust their outfits one by one.

**Comment by SolraBizna** [comment]
Wow. I really, really wish I had known that before... :)

**Comment by Frozen-byte** [comment]
Another approach to stop your (awesome) strategy:
Adjust the pirates strength to the value of your carried goods (including that from current pending jobs).
If you carry food the pirates will become much weaker than carrying the shiny luxury goods!

**Comment by SolraBizna** [comment]
That's a good metric to go off of. Honestly, it makes more sense for pirates to attack based on cargo value rather than the number/type of ships involved. If I'm using Bactrians to mass-carry Luxury Goods, pirates should attack. If I'm using heavily upgraded Bulk Freighters as warships, but not carrying any cargo on them, the pirates shouldn't care.

**Comment by hcatlin** [comment]
Attacking on cargo is a brilliant idea. Fits into the storylines.

**Comment by brick96** [comment]
But how will they know? Gotta get fairly close to use a scanner

**Comment by SolraBizna** [comment]
A giant freighter fleet picking up 40,000 tons of medical supplies is bound to attract some attention on-world...

**Comment by endless-sky** [comment]
I think the best solution to this is going to be the dynamic economy, which will make any trade route unprofitable for a while when you've run enough commodities through it. More pirate raids, even big ships, won't matter when you've got dozens of Bactrians. So, I'm closing this in favor of just working on getting a dynamic economy working.
