### ISSUE TITLE
Tek Far 109 stats

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1735]
the Tek Far 109 seems to be larger visually now, but its stats still place it decidedly below Met Par Tek 53, including mass. maybe intentional, but i thought i would point it out.

**Comment by Quantumshark** [comment]
The Tek Far 109 is a carrier, so it has lower hull and shields and less weapon space and gun ports.
Not sure about the mass though.

**Comment by KiLEdEnNis** [comment]
not sure how Korath AI ships would be on the inside, but a Carrier wouldn't be densely equipped with shield systems or anything, they would be a "small" ship that got a big size to fit the Fighters/Drones

**Comment by wambat1** [comment]
i now feel compelled to point out that the 109 carries its fighters externally.

**Comment by KiLEdEnNis** [comment]
I know, but it needs a big surface to hold them, and internally it would just have lots of empty space (based on the stats)
