### ISSUE TITLE
Deprecation on in stock outfits don't carry over if you reload the save

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1738]
Title says it all.

If you sell an outfit that is deprecated then reload the save, that outfit will remain in stock but lose its deprecation and require the full cost to purchase.

**Comment by endless-sky** [comment]
Are you sure? It's working properly for me - i.e. if I sell a depreciated outfit, then quit and restart the game, it shows up with that outfit in stock and its "cost" being the depreciated value.

**Comment by endless-sky** [comment]
Could this actually just be #1741?

**Comment by Amazinite** [comment]
I don't believe so.

Here is an atomic engine that I've been using for a while now. It currently has full deprecation on it, and I just sold it into stock,
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/19622738/106893c6-987f-11e6-9b8a-f624d6eb5302.png)

I then reloaded the save, and the deprecation was removed.
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/19622739/18906556-987f-11e6-8ee3-4ab4c4a1b891.png)

This is only happening on outfits not normally sold at that outfitter; selling a deprecated outfit that is normally sold at that outfitter then reloading the save will still have that outfit being deprecated.

**Comment by Bladewood** [comment]
Had a fully depreciated (25%) NT-200 nucleovoltaic generator installed.
Plundered a fission reactor from a pirate clipper.
Landed and replaced the nucleovoltaic with the fission reactor.
Took off, reloaded save.
Nucleovoltaic was no longer depreciated.

**Comment by endless-sky** [comment]
It turns out this was only happening with fully depreciated items, which took me a while to track down. Commit cfdce03 fixes this.

**Comment by Amazinite** [comment]
Awesome.
