### ISSUE TITLE
Plunder screen does not show proper worth of outfits

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1739]
The plunder screen still displays the full value of the outfits in the ship that you can plunder, not their true value with the 75% worth-reduction.

**Comment by Amazinite** [comment]
Similarly, death penalties are still based off of the full undeprecated value of the ship, so losing even one crew member make capturing the ship not worth it anymore.

**Comment by endless-sky** [comment]
Fixed in 3c1eb25.
