### ISSUE TITLE
Capture death benefits based off of ship's undeprecated value

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1740]
Not sure if this is intentional, because the loss of even one crew member makes capturing not worth it economically anymore.

**Comment by Pointedstick** [comment]
> the loss of even one crew member makes capturing almost not worth it anymore.

Eeeeeexcellent. Now you'll capture a ship because you actually _want_ that ship, not just as a moneymaking exercise.

**Comment by Amazinite** [comment]
Maybe so, but it's a bit excessive right now. I lost 6 crew capturing a deprecated-worth ship of 2.5 million and had to pay out 7 million in death benefits; that's a 4.5 million credit loss for capturing a ship.

**Comment by Pointedstick** [comment]
Maybe throwing your clearly insufficient and unprepared crew into that kind of meat grinder was a bad idea then, eh? 😉

**Comment by Amazinite** [comment]
6 crew is barely anything compared to the 200+ crew I had fitted with Rail Rifles (a mod) that have 1.9 attack each.

**Comment by retrue** [comment]
Death benefits should be based on the valour in the market of that depreciated ship, not on the valour of that brand new ship.

**Comment by endless-sky** [comment]
Fixed in 3c1eb25. Depreciation was a major change and clearly I didn't notice all the ramifications it would have in my initial commit.
