### ISSUE TITLE
Can't buy a (deprecated) ship despite having the credits for it

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1743]
Check my credits and the cost of the ship
![5526e75f072447d7b0da27a624423f5f](https://cloud.githubusercontent.com/assets/17688683/19622711/47828e1c-987e-11e6-93f4-b29290886486.png)

I can't buy it. :(
![080180ddf66b43a49f1c372afc8c1c18](https://cloud.githubusercontent.com/assets/17688683/19622712/4a4a077e-987e-11e6-9385-960513da5fb8.png)

**Comment by endless-sky** [comment]
Fixed in 724a220.

**Comment by Admiral-Danforth** [comment]
Excuse, but is this a mod that you are playing and if so which one?

**Comment by Bladewood** [comment]
Presumably, he's messing around with the Shields Up modpack, found on the Steam forum.
I do not really like that mod, but I've played enough to recognize that "Skybus" ship.

**Comment by Amazinite** [comment]
@Admiral-Danforth I've got a bunch of plugins on, but the ones of the ships in that screenshot are from [Shields Up](https://github.com/Amazinite/Shields-Up) (the Archangel and Skybus) and [Phil's Flavours](http://steamcommunity.com/app/404410/tradingforum/348292957933722132/) (the Star Princess and Silver Stream).

**Comment by Admiral-Danforth** [comment]
Thanks

**Comment by Bladewood** [comment]
> actual balancing
better ship images
the whole lot

dear god.
you identified most of the problems I have with those mods.

**Comment by Alkallid** [comment]
>Backhanded compliments

**Comment by Amazinite** [comment]
>>rip indeed

**Comment by Bladewood** [comment]
Help, not working for outfits!
![whydepreciationwhy1](https://cloud.githubusercontent.com/assets/16506683/19950880/c6092236-a130-11e6-8b32-9c76b46747cd.png)

**Comment by Amazinite** [comment]
What do you mean by "when you depart"? Do you depart and reload the save, because departing and relanding would just remove it from stock. If it is the case that you're reloading your save, then #1738

**Comment by Bladewood** [comment]
okay yeah it's that.

**Comment by endless-sky** [comment]
898f7da should fix this.
