### ISSUE TITLE
Confusion could be caused by "sells for (25%)" showing on new outfits

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1744]
![d505e32104b7487d9269cb842ec33c96](https://cloud.githubusercontent.com/assets/17688683/19622757/9d1fd9aa-987f-11e6-82c5-07db20ab0843.png)

This makes it look like that after you buy it, selling it back immediately afterwards will sell it for only 25% the worth.

**Comment by endless-sky** [comment]
e278ffa should fix this.
