### ISSUE TITLE
"FW Pug 4B: Reinforcements": Syndicate ships are of the escort faction

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1745]
I don't think the mark II Syndicate ships that help you fight the Pug should have the green paint of the Free Worlds.

**Comment by KiLEdEnNis** [comment]
even if they do, the Carriers, Cruisers & Dreadnoughts (if they don't) should be Escort too then

**Comment by endless-sky** [comment]
Fixed in 9bd1758.
