### ISSUE TITLE
Hyperspace jump with only an afterburner equipped: arriving in the system pushes you backwards

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1746]
Got bored.
Removed my A520 thruster and I was left with a hyperdrive, A865 steering and an ionic afterburner.
Jumped to an adjacent system.
When I arrived in the system (and lost my "hyperspacey" effect), I was immediately blasted backwards by some unknown force.

Hyperspace is not afterburner-friendly, apparently.

**Comment by Amazinite** [comment]
#1170

**Comment by Bladewood** [comment]
rip my personal entertainment.
