### ISSUE TITLE
Turbochargers! or something

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1747]
Would it be possible to add turbochargers or something to either: A. increase power output (which makes no sense) or B. increase thrust.

This seems like something the Korath would use because there motto for engines seems to be, POWER!!!!! This could also be in Smugglers Den or independent outfitter.

**Comment by Amazinite** [comment]
>B. increase thrust.

You mean like an afterburner?

**Comment by Admiral-Danforth** [comment]
I meant for it to be a permanent affect instead of a temporary effect. The goal of this is just to create more thrust permanently from your engines at the expense of heat.

**Comment by retrue** [comment]
The effect would be getting more powerful engines with the same size than current ones, just giving off more heat that can be easily corrected with heat sinks.
Not a good idea, I think.

**Comment by Bladewood** [comment]
How about this:
A secondary weapon that has a limited ammo supply, but generates a great amount of energy while being used.
Maybe we could have it use fuel as ammunition.
`outfit "Korath Turbocharger"`
`	category "Secondary Weapons"`
`	cost 840000`
`	thumbnail "outfit/unknown"`
`	"mass" 16`
`	"outfit space" -16`
`	"weapon capacity" -16`
`	"turret mounts" -1`
`	weapon`
`		"fire effect" "distancer flare"`
`		sound "zapper"`
`		icon "icon/flamethrower"`
`		"lifetime" 1`
`		"reload" 1`
`		"firing energy" -9.6`
`		"firing fuel" .3`
`		"firing heat" 30`
`	description "This is a peculiar Korath turret. It is completely incapable of dealing damage, but is capable of draining fuel to provide a massive energy boost. Of course, as with all Korath technology, it generates a massive amount of heat while firing."`
(pretend there are indents, Github is being an ***)

**Comment by Amazinite** [comment]
From my mod...
```
outfit "Fuel Powered Generator"
	category "Power"
	cost 3675000
	thumbnail "outfit/known"
	"mass" 70
	"outfit space" -70
	"gun ports" -1
	weapon
		sprite "effect/afterburner"
		sound "flamethrower"
		icon "icon/flamethrower"
		"velocity" 1
		"lifetime" 5
		"reload" 1
		"firing energy" -15
		"firing heat" 83.333
		"firing fuel" .1
	description "For when you’re in the heat of battle and need some extra energy, say hello to the Fuel Powered Generator. Fire this thing up in the middle of battle to convert your hyperspace fuel into useable energy. Especially useful for those with a lot of fuel but not much space for batteries or reactors."
	description "Due to the massive amounts of heat generated when in use, the generator requires the use of one of your ship's gun ports to be used as an exhaust port to let out all the heat."
```

**Comment by Admiral-Danforth** [comment]
I was thinking more like this:
outfit "Turbocharger"
	category "Engines"
	"cost" 200000
	thumbnail "outfit/turbocharger"
	"mass" 5
	"outfit space" -5
	"engine capacity" -5
	"additional thrust" 1.0
	"additional thrusting energy" .4
	"additional thrusting heat" 2.
"This thing was developed by the Korath in order to squeeze that last amount of thrust from their engines. This works by directing more energy than normal at you engines allowing them to produce more thrust.

You wouldn't see it because in a car you do not see a turbocharger. It would just be there to provide more power at the expense of a lot of heat. It makes you engine provide more thrust. It would always be active.

**Comment by Bladewood** [comment]
Based on your description, you could just make a new thruster dedicated to this task :|

**Comment by Admiral-Danforth** [comment]
It does say or something, so who knows? I certainly don't.

**Comment by Pointedstick** [comment]
> It does say or something, so who knows? I certainly don't.

Then what was the point of your posting? You're just cluttering up the place with these kinds of random un-actionable suggestions. If you're serious about creating new content for this game, then you should *actually create new content for this game* instead of throwing out endless rough ideas in the GitHub issue tracker, which is not useful to anyone. I suggest making a mod instead. Work on creating stuff yourself, and if you lack any of the necessary skills, then acquire them.

**Comment by Amazinite** [comment]
To quote Local...

>(Please close this.)
