### ISSUE TITLE
Mouse selectable ships on minimap

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1748]
![screen shot 2016-10-22 at 6 34 46 pm](https://cloud.githubusercontent.com/assets/22384290/19623193/417c480c-9886-11e6-8b77-b47e1e74e2fe.png) selectable on this thing

**Comment by Bladewood** [comment]
I don't really think this will work, because dots on the minimap are INSANELY small.

**Comment by LocalGod79** [comment]
and when there are lots of ships piled together, which one does it select?

**Comment by Bladewood** [comment]
Well, the same thing would happen if you were up close and tried to select a ship in a pile without the minimap.

**Comment by LocalGod79** [comment]
okay; it would probably be handled the same way, but adding the feature would only make that particular problem worse, wouldn't it?

**Comment by Admiral-Danforth** [comment]
It would be useful if you have a ship that is ten miles away spewing missiles and your to lazy to click R or something.
