### ISSUE TITLE
allow missions to check base hull cost [feature request]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1751]
your recent commit https://github.com/endless-sky/endless-sky/commit/3a3b8e293a7f6424cce1be51e2d3758137e39213 gave me the idea, which combined with others (similarly to the Sparrow escort missions), could finally create custom missions for the Star Queen (which may also require total ship cost).

sorry - this was not well thought out...

**Comment by retrue** [comment]
I have been thinking about the Star Queen too. The idea would be to add deluxe passangers transport. That is, if the flagship or one of the scort ships is a Star Queen, there would be missions available to transport passangers for a higher price.
That would give Star Queen ships some usefulness.
Dunno if there are other ships that could be classified as deluxe transport.
