### ISSUE TITLE
Request: Add super urgent missions.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1753]
Normal urgent missions must be done before the double time that is necessary to go from origin to destiny.
More urgent missions for cargo or passengers could be added. Missions that could be done only with ships that don't need to land midway to fuel up, or ships that have ramscoops so they don't need to make scales.

On a side note, in the game there are very few urgent missions related to transport of passengers.

**Comment by LocalGod79** [comment]
i think this might be a request for a child token of the `deadline` mission attribute that is also tied to the `destination`...

**Comment by endless-sky** [comment]
Right now the deadline multiplier is only allowed to be an integer, but you can set it to 1 instead of 2, e.g.:

```deadline 2 1```

Meaning, 1 * number of jumps + 2.
