### ISSUE TITLE
"Oathkeepers on Farpoint": need to bribe in order to land

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#1755]
In the "FW Reconciliation 2A", where you travel to Farpoint, there is nothing to guarantee that you can actually land. In that mission and a few missions after it, I ended up having to pay over 10Mcr in bribes. (My net worth might be a little high right now...)

To be clear, it is not the amount of the bribe that matters, it's the fact that you must pay a bribe to complete the mission at all.

**Comment by Bladewood** [comment]
I encountered this issue before. You're expected to kill a few pirates on your way there. But I agree, you should get clearance on Farpoint.

**Comment by SolraBizna** [comment]
Well, since I was trying to win with a Clipper, I wasn't so much "killing pirates" as "running away from pirates screaming 'Speed is armor! SPEED IS ARMOR!'"... :)

**Comment by endless-sky** [comment]
Fixed in 9338810. But I suspect Danforth doesn't think very highly of people who run away from Pirates. :)

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
