### ISSUE TITLE
Got "Katya and Ijs to Skymoot" and "Take Ijs to Winter" the same day

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#1756]
During my recent attempt to complete the main storyline flying a Clipper (which ended up being successful, but tedious), after I landed and was offered "FW Reconciliation Break" ("Katya and Ijs to Skymoot"), I visited the space port. This led to me being offered "FW Conservatory 1" ("Take Ijs to Winter"). I accepted both. This created some oddities: I had Ijs occupying two separate bunks, and when I completed the Conservatory string, Ijs said "if you hear any more news about Katya, please let me know." (despite sharing a bunk room with her for the past few weeks)

I also vaguely remember the Conservatory being referenced as already set up in an earlier mission, but that memory is only ~30% reliable.

**Comment by Bladewood** [comment]
...I thought we already took away Ijs's cloning powers!

**Comment by Amazinite** [comment]
Apparently not. (#1086)

**Comment by endless-sky** [comment]
300136f should fix this.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
