### ISSUE TITLE
"What happened to Rand?": Actually landing on Rand does nothing

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#1757]
This last time through the main storyline, I already had a Jump Drive when this mission came up. Naturally, I went directly to Rand. I landed... and nothing happened. I ended up having to do the mission as if I had a normal hyperdrive.

The later mission where you are given a jump drive _does_ handle the case where you already have one.

I understand the difficulty of retooling this very complicated part of the storyline; already having a Jump Drive would drastically alter this entire section of the string. I also think anybody who acquires a Jump Drive before completing the main storyline is prepared for the mild balance and storyline breakage this will cause. So I won't complain if the response to this bug is "we'll leave it, unless somebody submits a really good patch".

**Comment by Amazinite** [comment]
#1082

**Comment by jafdy** [comment]
#1082 is (was) my somewhat inelegant attempt to fix this. Really it need someone who can actually write well to do it.

**Comment by gunqqer** [comment]
Does it work, @jafdy ? if so... I see nothing wrong with it.

**Comment by jafdy** [comment]
It works. It is also badly written. I think the only reason it is still open is because it is the only thing trying to fill that spot.
