### ISSUE TITLE
Recent scroll speed change makes scrolling terrible with two-finger trackpad scrolling

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1758]
I play on a MacBook Pro and use two-finger scrolling. The recent change to triple the scroll speed in shipyards and outfitters (80cedcd2ced5dcc26e9f49c00b220eb9f4b9e31a) makes scrolling almost impossible with my trackpad. It's way too fast.

**Comment by Admiral-Danforth** [comment]
For me it seems the exact same maybe change you trackpad settings?

**Comment by Bladewood** [comment]
Did you bother compiling the latest build? The scroll speed has been tripled.

**Comment by Admiral-Danforth** [comment]
As in 0.9.4? If so yes

**Comment by Pointedstick** [comment]
No. You need to re-compile from the latest sources. If you have not done that, you won't see the issue.

**Comment by Admiral-Danforth** [comment]
Does the compiling require building the game from source?

**Comment by Bladewood** [comment]
*facepalm* That is what compiling means, yes...

**Comment by Admiral-Danforth** [comment]
My head hurts from slamming it on my desk and that is why the English language is, so annoying you learn one definition and gains a new one like 300 years later.

**Comment by Bladewood** [comment]
You just downloaded the latest release build, which is a source build that was pre-compiled by Michael Zahniser. There is a distinction to be made between that and compiling a source build yourself.

**Comment by endless-sky** [comment]
Maybe if I adjusted the speed to 100 (halfway between the old speed of 50 and the new speed of 150) that would be a good compromise? I've looked to see if SDL gives you a way to query what the system's desired scroll speed per detent is, but there's no function to query that.

It could also be a preference, but in general I've been trying to avoid crowding the preferences panel. (Maybe that would provide a reason to go ahead and split the preferences onto two screens, though.)

**Comment by Pointedstick** [comment]
I understand why this change was made--for mouse wheel users whose top scroll speed is limited by the size of the wheel. Perhaps an acceleration algorithm would work. Normal, human-scale scrolling at low and medium speed, going up to super fast if the user is obviously trying to go as quickly as their hardware permits.

And you know, it wouldn't be so bad if it actually *scrolled*. The content doesn't move smoothly; it appears to jerk from one position to another. I believe this is called "smooth scrolling" in Firefox (or did in the past). Endless Sky doesn't have it.

**Comment by endless-sky** [comment]
I've added a scroll speed preference (toggling between three different speeds, one of which will make the shop scrolling equivalent to the old speed) in commit 770a424.

**Comment by Pointedstick** [comment]
Fixed now with that change. Thanks!
