### ISSUE TITLE
Ships that land while you have them targeted are still hail-able

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1759]
It looks like this when you do it:

![screen shot 2016-10-23 at 11 47 14 am](https://cloud.githubusercontent.com/assets/1097249/19628239/8b629832-9916-11e6-8b6f-f4773b2798f9.png)

**Comment by Alkallid** [comment]
Also when they jump out.

**Comment by Admiral-Danforth** [comment]
When they jump up it says: "Unable to send hail ship is entering hyperspace"

**Comment by endless-sky** [comment]
I guess this only applies to NPCs and escorts - non-mission targets are cleared the moment they land. But in any case, 6145ecc should fix this.

**Comment by Pointedstick** [comment]
Excellent. Confirmed that https://github.com/endless-sky/endless-sky/commit/6145ecc95d42189da2c9d0522dfa2ed8e0d81bd0 resolves this.
