### ISSUE TITLE
A few minor issues with very, very large fleets

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#176]
1. There is no apparent way to scroll the ship list in Player Info.
2. With a large homogenous fleet of ships spread across more than one system, the in-flight info list does not always "fold" correctly. (When they _are_ all in the same system, it does fold correctly. And the folding is _awesome_ when it works.)
3. When selling too many ships at once, the sell confirmation dialog becomes much larger than the screen. (It is still possible to sell, if you blindly hit "enter".)

I can provide a save file where I have a large homogenous fleet, if it will help. (It's also the Unstoppable Death Wave save...)

**Comment by endless-sky** [comment]
This is really three separate issues. Issue 1 was fixed in 0.8.7 by commits d3c4887 and 23343c3.

Issue 2 might be related to bug #191; I can't be sure without more details. What sort of incorrect folding do you observe?

Issue 3 should be fixed by commit 44a1a48, which I just uploaded.

**Comment by SolraBizna** [comment]
While they are all in the same system they folded correctly. After I jumped (assuming none jumped at the same time I did) they remained folded correctly. Then, after at least one jumped, all of the ones that had not yet jumped would unfold. As each one arrived, it would be folded, and once they were all in the same system as me, they were all folded correctly again.

I don't remember observing them folding incorrectly in any other way. It is possible that the fix for #191 also fixed this; when I encountered it, a few of my ships had different loadouts*. I'll have to test further, on a newer version... it's been several point releases since the version I was running when I made the report.

\*Thinking about it, this makes it dissimilar to #191... since they _did_ fold correctly when they were all in the same system.

**Comment by endless-sky** [comment]
All three of these bugs should be fixed in 0.8.8. The folding bug only occurred if the first ship of a given type which is in the current system is less expensive than other ships of the same type that you own, which explains why you might sometimes see it and sometimes not depending on which ships are in-system.

**Comment by endless-sky** [comment]
This issue is fixed in 0.8.8, and 0.8.8 is now the default on Steam, so I'm closing this issue.
