### ISSUE TITLE
Is Men supposed to be the capital of the independent planets?/Are Independent planets supposed to recognize each other?

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1760]
I made my own planet that was an independent and when I dominated Men it became hostile. Like when you attack Bourne, the Free Worlds become hostile. Is men supposed to be considered the capital of the Independent planets?

**Comment by jafdy** [comment]
If you kill enough ships that the Independent faction likes then all other independent ships stop liking you. You have a not quite complete understanding of the reputation system.

**Comment by LocalGod79** [comment]
that said, his question is legitimate: are governments on Independent planets supposed to care what happens on other Independent planets?  if so, doesn't that make them an (albeit weak) alliance (and not independent)?

**Comment by Bladewood** [comment]
how about making their government " Independent ", with spaces?

**Comment by Amazinite** [comment]
@bladewood I think a better way instead of the empty spaces would be to make their governments be called "*system name* (Independent)".

**Comment by daerogami** [comment]
If you show yourself to be an enemy of ships that don't have the backing of a large government, you would probably be identified as a marauder or pirate. A general threat that would be communicated with other planets, that being said, it should make other governments be wary of the player as well.

**Comment by LocalGod79** [comment]
i'm a little discombobulated by this problem - another solution would be to use synonyms other than "Independent" or "Neutral".

"Sovereign" or "Nonaligned" offer two more possibilities before resorting to spaces on either side of the government name.

an engine distinction would certainly make future "Independent" systems more immersive.

**Comment by endless-sky** [comment]
Aside from using a different government name for every independent system, I don't see a way to achieve this. Plus, it kind of makes sense that "independent" human worlds would care about the player's reputation for helping or hurting other independents.
