### ISSUE TITLE
Add a Republic Transport

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1761]
This could go with you to Poisonwood instead of the Cruiser, as well as maybe a Wolf Pack Mission.

**Comment by Bladewood** [comment]
Star Queen.

The Alphas are a serious threat. Only a Carrier has both the bunks needed to take on the Alphas on the ground, and the weapons to take out the pirate ships in orbit.

**Comment by Admiral-Danforth** [comment]
The Star Queen is luxury though and also secondary thought why not this in the Alphas on Host mission set.

**Comment by Admiral-Danforth** [comment]
ship _"I Can Not Think of a Name Now"_
	sprite "ship/carrier"
	licenses
		Navy
		Carrier
	attributes
		category "Transport"
		"cost" 15200000
		"shields" 20000
		"hull" 8300
		"required crew" 50
		"bunks" 300
		"mass" 910
		"drag" 17.7
		"heat dissipation" .45
		"fuel capacity" 700
		"cargo space" 300
		"outfit space" 600
		"weapon capacity" 200
		"engine capacity" 210
		weapon
			"blast radius" 300
			"shield damage" 3000
			"hull damage" 1500
			"hit force" 4500
	outfits
		"Sidewinder Missile Launcher" 4 (or whatever its called)
		"Sidewinder Missile" (how ever many that would have
		"Heavy Laser Turret" 2
		"Heavy Anti-Missile Turret" 2
		
		"Fusion Reactor"
		"LP288a Battery Pack"
		"D94-YV Shield Generator"
		"Large Radar Jammer"
		"Water Coolant System"
		
		"X5700 Ion Thruster"
		"X4200 Ion Steering"
		"Hyperdrive"
		
	engine -35 200
	engine 35 200
	gun -25 -166 "Sidewinder Missile Launcher"
	gun 25 -166 "Sidewinder Missile Launcher"
	gun -16 -176 "Sidewinder Missile Launcher"
	gun 16 -176 "Sidewinder Missile Launcher"
	turret 0 157 "Heavy Laser Turret"
	turret 0 157 "Heavy Laser Turret"
	turret 0 103 "Heavy Anti-Missile Turret"
	turret 0 103 "Heavy Anti-Missile Turret"
	explode "tiny explosion" 20
	explode "small explosion" 45
	explode "medium explosion" 50
	explode "large explosion" 40
	explode "huge explosion" 10
	"final explode" "final explosion large"
	description "The (insert name here) was made by the Republic during the (war against bunches of companies that own their own planet) in order to transport large amounts of troops and supplies relatively quickly and very safely across the galaxy. It is however very slow and cumbersome and for that reason carries two drones for protection.

**Comment by Admiral-Danforth** [comment]
Full Description: "The (insert name here) was made by the Republic during the (war against bunches of companies that own their own planet) in order to transport large amounts of troops and supplies relatively quickly and very safely across the galaxy. It is however very slow and cumbersome and for that reason carries two drones for protection.

**Comment by retrue** [comment]
@Admiral-Danforth And first thing I would do would be capture one of them and use it as flagship to capture other ships.
It has 300 crewmen and converting the cargo space in bunks cand add 75 crewmen more.
With 375 crewmen it could capture almost anything.

**Comment by Pointedstick** [comment]
@Admiral-Danforth, you're sort of abusing the GitHub issue tracker here. It's really supposed to be used for legitimate bug reports or *serious* suggestions for improvements or content changes. Most of what you've been posting is in the realm of forum material (and not particularly high-quality forum material... 😕).

**Comment by Admiral-Danforth** [comment]
I know of no other forums where this will actually get noticed and I'm not the only one.

**Comment by Amazinite** [comment]
There's always people on the Steam forum for the game and although I don't use the google group, it seems active enough that (meaningful) threads get replies within 24 hours.

**Comment by KiLEdEnNis** [comment]
@Admiral-Danforth you do know the link doesn't work, as it directs you to https://github.com/endless-sky/endless-sky/issues/url right?
