### ISSUE TITLE
Why don't escorts use afterburners? Also please make them use afterburners.

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1762]
Click A and your escorts are left behind even though they also have afterburners, but they don't use them.

**Comment by Bladewood** [comment]
Wait for an enemy to enter the system. Then all of your escorts will rush towards it using their afterburners.

Just following the flagship is not really a serious assignment. Being threatened is serious.

**Comment by Johny-Cash** [comment]
They also do use afterburners when you click "gather".

**Comment by endless-sky** [comment]
Escorts use afterburners only if there's an enemy present and using afterburner won't leave them with too little fuel to jump.
