### ISSUE TITLE
Allow outfits to be put in cargo

### ISSUE THREAD

**Issue by Johny-Cash** [endless-sky/endless-sky#1765]

**Comment by Bladewood** [comment]
Go to an outfitter. If any ships are selected, deselect them with ctrl-click.
Then buy an outfit from the outfitter. It will be placed into cargo.

**Comment by Johny-Cash** [comment]
Thanks

**Comment by Amazinite** [comment]
Already in the game, asBladewood has described. 

>(Please close this issue.)

**Comment by lheckemann** [comment]
Another mechanic I had no idea existed! This is incredibly useful, I used to just install them in "outfit mule" ships (I used heavy freighters with lots of mass expansions) but this is a much better way...

**Comment by KiLEdEnNis** [comment]
I don't think it's an actual feature though, more like just a "bug" that has a good use

**Comment by jafdy** [comment]
This is an actual added feature. It couldn't be done until 0.9.0 (I think).

**Comment by KiLEdEnNis** [comment]
it is? I haven't heard anything about it, and the fact that you have to open outfitter, deselect all ships & then buy seems a bit weird

**Comment by endless-sky** [comment]
It's mentioned in the Player's Manual, in the section on the Outfitter.

**Comment by DingusShingleton** [comment]
Maybe these type of issues could be mitigated with a good old fashioned "RTFM" when you start a game. Or make like a slick infographic with lots of useful tips. Actually, i could probably do that. Hmmm
