### ISSUE TITLE
Allow slave chaining of ships

### ISSUE THREAD

**Issue by Safari-Is-Amazing** [endless-sky/endless-sky#1766]
You could slave chain a group ships together, so just that group attacks a target and a different group attacks a different target. (That was for example). For more info: [http://starwars.wikia.com/wiki/Katana_fleet] this should help.

**Comment by jafdy** [comment]
Spam R+F? If your fleet is large enough for this to make sense then it is also large enough to steamroll more or less anything you come across.

**Comment by quantumandan** [comment]
I was going to open a new issue but OP is pretty close to what I was thinking too. Basically, I would like to be able to establish groups or "fleets" inside my collection of unparked ships and give different instructions to each group. For instance, before getting access to Flycatchers, I would use 20 Blackbirds  with anti-missile turrets and the problem I have is that I want to tell my Blackbirds to stay near my Dreadnoughts while they attack from afar with projectiles.

**Comment by tehhowch** [comment]
@quantumandan
You can instruct a ship to follow another ship. So it is possible to ask a blackbird to follow a dreadnought, and use a command group to select the dreadnoughts and issue attack orders that only they will follow.
