### ISSUE TITLE
Unfettered Hai Dialogue Appeared on Icelake

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1767]
Landed on Icelake and got Unfettered Hai dialogue.

**Comment by endless-sky** [comment]
Are you sure it wasn't the one where you ask the normal Hai what their side of the story about the Unfettered is?

**Comment by Admiral-Danforth** [comment]
ut was the jump drive one

**Comment by Admiral-Danforth** [comment]
this happened before on a different planet as well

**Comment by endless-sky** [comment]
There are five different jump drive missions, and they all specify that the source must be an unfettered planet. Do you know which of the five was offered?

**Comment by Admiral-Danforth** [comment]
no idea it was just the jump drive
