### ISSUE TITLE
Mission description text box in the map is awfully small and limiting

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1768]
I'd really like to be able to write mission descriptions that are just a _liiiiiiiitle_ bit longer than the non-expanding text box allows.

![screen shot 2016-10-23 at 8 45 29 pm](https://cloud.githubusercontent.com/assets/1097249/19632213/abe7410c-9961-11e6-8bba-77a9ffc06c34.png)

Yes, I know there are many ways to shorten this text (and what's what I wound up doing) but it would be nice to have the room to write mission descriptions with a bit more flavor text.

**Comment by LocalGod79** [comment]
do you perhaps mean jobs?

perhaps a `conversation` "on accept" is in order for a job that's this complex (with a decline/fail option)?
or make it a spaceport mission?

**Comment by Pointedstick** [comment]
It's not really a very complex job at all (disable some ship, scan it, and return here), and it's not a special mission--it's a recurring job you can take over and over again. I removed the first sentence in the end, but it would be nice if the box has enough room for it.

**Comment by endless-sky** [comment]
Anything that has that much specific detail should not be a mission that repeats over and over, and anything that is only offered once is better off being offered from the spaceport.

**Comment by Pointedstick** [comment]
Darn.

**Comment by endless-sky** [comment]
Also, you could put the details into an "on accept" dialog that provides more information, if you really want this to be offered as a job. Something like: "Glad you can help us," says the Syndicate rep. "Here's the details..."
