### ISSUE TITLE
Player Manual mentions wrong key

### ISSUE THREAD

**Issue by kkuchta** [endless-sky/endless-sky#177]
> By default, the back-tick key toggles between all targets in system, and the 'R' key targets the nearest hostile ship. Hold down the shift key while pressing the backtick key to toggle through your escorts, or while pressing the 'R' key to select the nearest non-hostile ship.

From https://github.com/endless-sky/endless-sky/wiki/PlayersManual

It says that backtick is the button to select the next ship, but it appears to actually be the `n` key by default.

**Comment by endless-sky** [comment]
Fixed. Thanks!

**Comment by kkuchta** [comment]
Awesome.  Thanks for the amazing game!
