### ISSUE TITLE
Would like a way to override mission location filter behavior of omitting planets that you don't have permission to land on

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1770]
This has come up a few times when I'm writing missions. For example, say I set a destination filter as follows:

```
    destination
        attributes pirate
```

As long as the pirates are hostile to me (and they generally are 🙂), the game will see all pirate planets as unavailable, the destination filter will never return any valid planets, and the mission will not be offered.

I'd like a way to override this so that planets you're not allowed to land on will match the filter. You'd need to bribe your way onto the planet to complete the mission, but hey, imagine the possibilities! 🙂

**Comment by toilethinges** [comment]
Or, technically, you could give clearance for the planet.

**Comment by jafdy** [comment]
And make the negative payment an on offer condition (with it being given back to you if you decline the mission).

**Comment by warp-core** [comment]
Is this still a thing?
If people are interested, I think adding support in LocationFilter for an "ignore permission" token to tell it to ignore if the player can land on the potential destination should do it.

**Comment by Zitchas** [comment]
I hadn't seen this issue/request previously, but this is definitely something I'd like to see. I run into a variant of this, with people not being offered missions going to planets that require gaslining when they aren't in a gaslined ship.

Honestly, I'd actually prefer to scrap the behavior entirely for most missions: Let players see the mission and even accept it if they want, and then let them figure out how to complete it. Whether that be bribery, making friends, using the correct ship... whatever. 

Short of that, though, having an `"ignore requirements"` token, in addition to an `"ignore permission"` would be a very good thing to have.

**Comment by UnorderedSigh** [comment]
Your wish has been granted: #8293
