### ISSUE TITLE
Type 2 radiant steering is slightly less efficient than type 1 in terms of cooling provided

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1771]
Type 2 steering has a 126 / 20 = 6.3 cooling:mass ratio, while type 1 steering has a ratio of 60 / 9 = 6.66~.

**Comment by endless-sky** [comment]
All the ratios are balanced based on amount per unit thrust, not amount per mass. Type 2 produces a little bit less heat per unit thrust than type 1, and also produces a bit more thrust per unit mass.
