### ISSUE TITLE
Bug: "Sell for" amount increases proportionally to how many I buy, so I can make money by buying and selling.

### ISSUE THREAD

**Issue by NHDaly** [endless-sky/endless-sky#1775]
As the title describes, I'm buying and selling Laser Rifles, and for every one I buy, the "Sell for" multiplier increases proportionally, meaning I can sell them back for millions of dollars:

<img width="1280" alt="screen shot 2016-10-26 at 11 27 56 am" src="https://cloud.githubusercontent.com/assets/1582097/19734978/4c518d50-9b6f-11e6-87f1-bb99f3b1260b.png">

I've built from head at 6145ecc95d42189. I'm in `Epsilon Leonis`.

**Comment by NHDaly** [comment]
Also, here is my save file:
[Issue1775_save.zip](https://github.com/endless-sky/endless-sky/files/553871/Issue1775_save.zip)

**Comment by Amazinite** [comment]
Gg deprecation.

**Comment by NHDaly** [comment]
lol

**Comment by endless-sky** [comment]
If you load the saved game that you posted above, does the bug persist? I tried it out and selling is working as expected.

**Comment by endless-sky** [comment]
You might also try doing a clean rebuild of the code. Sometimes the compiler makes a mistake in figuring out what parts of the code need to be rebuilt, which can cause weird memory errors if the size of a class changed.

**Comment by blr39** [comment]
This happened to me too with the laser rifles using the 0.95 unstable build on OSX 10.11.6. Persisted between saves. Tried it with some other outfit (forget what) and then my credits dropped to negative several hundred trillion. Worked with a new pilot as well.
