### ISSUE TITLE
Split Screen Issue

### ISSUE THREAD

**Issue by Safari-Is-Amazing** [endless-sky/endless-sky#1778]
![screen shot 2016-10-25 at 7 26 56 pm](https://cloud.githubusercontent.com/assets/23019063/19746903/1f7765dc-9b9e-11e6-9e7f-667357f471cc.png) As you can see the numbers go off to the side. In case you say it is not just the edited in ships.

**Comment by Bladewood** [comment]
What resolution do you play at, according to preferences.txt?

**Comment by endless-sky** [comment]
The game was designed for a minimum resolution of 1024 x 768. If your screen is smaller than that, some things won't fit.

**Comment by Admiral-Danforth** [comment]
It would be really useful if you could make it scale for spilt screen. On what bladewood said I do not believe it would be in preferences because it is MacOs doing split screen scaling, but you can configure items to scale to split screen (somehow).

**Comment by KiLEdEnNis** [comment]
how can you even play on such a tiny screen anyway, I would lose my mind on a 960x540 screen or something similar

**Comment by Admiral-Danforth** [comment]
Youtube at the same time
