### ISSUE TITLE
Suggestion: change integrated in hull outfits for not removable outfits.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1780]
Curently Quargs don't have any energy generator. Antimatter cores were removed from the game.
Pugs are even more mysterious. They don't have energy generators, shield generators, battery packs, etc.
The real explanation is that they were removed or not added to avoid that players could plunder them or install them in other ships, for balance in the game.
The in-game explanation is that all these systems are integrated in the hull. But in fact that is not explained anywhere in the game. Descriptions of the ships don't say anything about it.
My suggestion is to create an _undismountable_ label for outfits that could be added to antimatter cores and add too all the missing Pug outfits with this label.
You would have, for example, a Pug shiel/hull generator with their great stats, with their sprite or the unknown sprite and this _undismountable_ label.
And an in-game explanation for undismountable: 'No human engineer knows how to dismount this outfit.'
The outfits with this label would implicitly have the unplunderable label too.

This idea makes more sense than the actual situation where the issue is not explained.
The _undismountable_ label could be used too for missions, creating unique ships, in plugins, etc...

**Comment by Amazinite** [comment]
#1412 #1413

**Comment by Pointedstick** [comment]
I have to agree. Making certain outfits un-removable directly is a way better approach to preventing people from looting outfits that are overpowered or absurdly expensive than making their attributes built into the ship itself.

**Comment by retrue** [comment]
@Amazinite Oops, my mistake. I didn't see the thread about the unremovable label. Anyway, my reasoning for this label is a bit different than in those threads. That is, the necessity of creating Pug outfits (and get back the antimatter core) that cannot be removed. It is clearer than integrating invisible systems in a hull.
@Pointedstick Nope, it is completely different. Imagine a Pug shield generator outift. If it has the label "unplunderable" you cannot steal it when you board a Pug ship. But if you capture the Pug ship, then you can dismount the shield generator, sell it, or install it in a different ship. Imagine that this Pug shield generator is specially good. If it only has the unplunderable label you would be capturing Pug ships just to get the shield generators.
With a undismountable/unremovable label you wouldn't be able to plunder that outfit, or to uninstall it to install it in another ship, sell it or replace it.

I could change the name of the thread to "Suggestion: change integrated in hull outfits for not removable outfits".

**Comment by Pointedstick** [comment]
Oh ok, got it. Yeah, I see your point now.

**Comment by LocalGod79** [comment]
an outfit that is "undismountable" would be confusing at the outfitter, and i don't see how it's any different than having the corresponding attributes built into the hull (as they are now).

**Comment by retrue** [comment]
It is less mysterious than having a ship that lacks half its outfits and works magically.
This idea works for lore and this "undismountable" or "unremovable" label would have its usefulness for missions, mods, plugins, etc. Remember that it would implicitly include the "unplunderable" label.

You could create several unremovable Pug outfits or you could instead create a sort of unremovable all-in-one.
For example, for an Enfolta. The outfit would be something like this:

outfit "AIO Enfolta Control Unit"
	category "Systems"
	cost 1800000
	thumbnail "outfit/unknown"
	"mass" 148
	"outfit space" -148
	"energy generation" 22
	"shield generation" 8
	"shield energy" 8
	"heat generation" 32
	"energy capacity" 2000
	unremovable 1
	description "This piece of alien technology seems to be an all-in-one device. It produces energy, stores it, and even charges the ship shield. Unfortunately, not human engineer is able to separate it from the hull. Not that it would work outside of an Enfolta anyway."


ship "Pug Enfolta"
	sprite "ship/pug enfolta"
	attributes
		category "Medium Warship"
		"cost" 6300000
		"shields" 6800
		"hull" 1700
		"required crew" 19
		"bunks" 27
		"mass" 410
		"drag" 5.9
		"heat dissipation" .7
		"fuel capacity" 600
		"cargo space" 40
		"outfit space" 360
		"weapon capacity" 184
		"engine capacity" 106
		"energy generation" 22
		"shield generation" 8
		"shield energy" 8
		"heat generation" 32
		"energy capacity" 2000
		weapon
			"blast radius" 180
			"shield damage" 720
			"hull damage" 360
			"hit force" 1080
	outfits
		"AIO Enfolta Control Unit"
		"Pug Zapper" 2
		"Pug Seeker" 2
		"Pug Zapper Turret"
		"Pug Biodefenses" 6
		"Jump Drive"
		"Pug Cormet Thruster"
		"Pug Cormet Steering"
	engine -11 68
	engine 11 68
	gun -11 -85 "Pug Zapper"
	gun 11 -85 "Pug Zapper"
	gun -11 -85 "Pug Seeker"
	gun 11 -85 "Pug Seeker"
	turret 0 7 "Pug Zapper Turret"
	explode "tiny explosion" 5
	explode "small explosion" 20
	explode "medium explosion" 25
	explode "large explosion" 15
	"final explode" "final explosion medium"
	description "This is a medium-sized Pug warship."

Same thing or similar could be done with the other Pug ships, the Draks or the antimatter core.

**Comment by LocalGod79** [comment]
nope - not buying it.  because Pug magic.  because Quarg magic too.  because every-alien-race with-higher-technology magic (in our puny human minds).

you don't need to tell me all the examples of ships that have attributes that are normally carried by outfits: i've been playing for over a year - i understand your perceived problem:  your proposed solution is not less confusing than the "problem" you're trying to solve...

imagine this scenario, from the perspective of a new player;
player captures a pug ship at the end of the FW storyline.
player takes said pug ship to outfitter.
player tries to remove "non-removable outfit"
player reports stupid outfit as a bug.

because this is make-work (creating outfits, outfit sprites, altering existing hulls) for *literally* no gain, i'm gonna inb4 M.Z.: [unlikely]

**Comment by Amazinite** [comment]
Yeah, this really only seems like a (duplicate) request trying to get useless outfits into the game that will end up being extra work in terms of images.

**Comment by Bladewood** [comment]
Let us change our way of thinking:
Pug and Drak ships do not necessarily _have_ irremovable generators.
They **are** the generators.

**Comment by Please-Close-This-Issue** [comment]
The Name Says It All

**Comment by Safari-Is-Amazing** [comment]
Are you suggesting that Pug ships are alive?

**Comment by Bladewood** [comment]
@Please-Close-This-Issue no comment.
@Safari-Is-Amazing There are some on the Steam forums who theorize that Pug ships are, indeed, living creatures, and it certainly would explain their unusual appearance and features.

**Comment by Please-Close-This-Issue** [comment]
@Bladewood Well why thank you. This is not a comment.

**Comment by endless-sky** [comment]
Outfitting a ship is intended to be sort of like trying to pick the optimum set of components to build a computer from scratch: you've got to fit it all into the case, and worry about heat and power. And as anyone who's built a computer knows, some cases come with integrated power supplies and some don't...

**Comment by Bladewood** [comment]
I never knew that building a ship was so much like building a computer.

**Comment by KiLEdEnNis** [comment]
new species; huge computer cases
lolk
