### ISSUE TITLE
Reduce by half the FW salary once the campaign is finished.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1781]
The Free Worlds salary at the end of the campaign is 6000 daily credits. To most players, at that moment, is a negligible amount. But in-game, it means that you are earning 60 times more than a normal space crewman. When the FW campaign is finished, it means too that you are earning all that money for doing nothing. And you continue earning it indefinitely.
My sugestion is to reduce by half that salary when the FW campaign is finished. In-game it would be justified like the player has passed to the Military Reserve.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20checkmate.txt#L2636
I'd imagine that this would apply to the reconciliation route as well.

**Comment by retrue** [comment]
But whatever your choice you continue receiving that salary and you cannot return to civilian life.

**Comment by DingusShingleton** [comment]
You are a civilian at that point. You are getting the salary as a thank you for your past service. Think about it, after that point you arent beholden to the FW in any way, you can do whatever you want. You don't have to deal with a boss or any hierarchy of any kind. Sounds like a civilian to me

**Comment by Admiral-Danforth** [comment]
We should have access to any swizzle because well we are the princes of the universe!

**Comment by kilobyte** [comment]
The thing is, the war doesn't progress unless you complete missions.  As most are not timed, you can go elsewhere and explore the galaxy for years, all while being paid.

**Comment by KiLEdEnNis** [comment]
@kilobyte maybe sometime there'll be "consequences" if you ignore missions for too long (and if you fail a mission the story continues, like instead if you lose a battle you need to reload, you can just continue as if you lost it)
would be realistic and cool

**Comment by kilobyte** [comment]
That would require coding an entire story tree with a fork for every failable mission.  That's be a pretty monumental task...

**Comment by KiLEdEnNis** [comment]
not necessarily every mission, because this ain't a 60GB game, but a few keypoints
