### ISSUE TITLE
Fighter with jump drive will appear to be ready, but then will have to move about an inch before jumping.

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1784]

**Comment by Admiral-Danforth** [comment]
The same with hyperdrive

**Comment by Bladewood** [comment]
Just tried something: Solifuge + 6 violin spiders, all equipped with a hyperdrive (and in the spiders' case, a fuel pod).
LAUNCH FIGHTERS'd, then prepared to jump.
Spiders began repeatedly landing and taking off from the planet.
When I jumped, shortly after, all of the spiders jumped in as well.

**Comment by Admiral-Danforth** [comment]
Mine don't land (was with finches).

**Comment by toilethinges** [comment]
...fighters aren't supposed to have Jump Drives, though?

**Comment by Bladewood** [comment]
who cares
throw jump drives on them anyway
