### ISSUE TITLE
Balance: Large vs Small Biochemical Cell

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1785]
I was outfitting a ship when I realized that is more efficient to use several small biochemical cells than one large. Usually in the game it is better to install a big outfit than several small ones of the same technology.
Let's see some numbers.
Large Biochemical Cell has a mass of 63. Small one has a mass of 17. So, for 1 Ton:

Type --- Energy Capacity --- Energy Generation --- Heat Generation --- Price
Small -- 17.65---------------- 5.65------------------- 4.95----------------- 13530
Large -- 11.10---------------- 5.90------------------- 4.65----------------- 14920

To be well balanced the Energy Capacity of the Large Cell should be higher or the price of the Large Cell should be lower, or some other valour should be changed.

**Comment by jafdy** [comment]
I think the point here is that the energy generation and heat generation is better on the large cell. That said, you do have a point.

**Comment by endless-sky** [comment]
Wanderer ships are designed to rely almost entirely on instantaneous power production, not storage. The energy storage for all the generators is basically intended to be the equivalent of adding a supercapacitor: enough to smooth out fluctuations in demand, but not enough to last for any appreciable amount of time if demand is well over capacity.

**Comment by Pointedstick** [comment]
I hesitate to bring this up, but if that's your intention, than the Blue Sun Reactor may have too much storage capacity. My favorite ship config these days is a Derecho with four Dual Sunbeam Turrets powered by a Red Sun and a Blue Sun. Their combined generation doesn't quite meet demand when all four turrets are firing at once, but together they provide 10,000 energy storage which is more than enough to avoid running out of juice for more than a second or two. This ship is *super fun* to play with but maybe the Blue Sun Reactor's capacity should be reduced.

**Comment by Griffinhart** [comment]
`Blue Sun Reactor` + `Systems Core (Large)` is approximately just as fun. Not as much powergen, but the storage (14.1k) makes up for a lot of slack.

![image](https://cloud.githubusercontent.com/assets/3744055/19827432/dac504ae-9d5e-11e6-9a9e-8e3baa183f76.png)

**Comment by retrue** [comment]
These are tier 2 outfits.

**Comment by jafdy** [comment]
@retrue every outfit mentioned here is T2.

**Comment by KiLEdEnNis** [comment]
I'm more a fan of having enough generation to hardly need batteries anyway (I like having more generation than max. consumption)

**Comment by Pointedstick** [comment]
@KiLEdEnNis Me too. I think most people probably migrate in this direction eventually given batteries' huge size relative to some of the smaller reactors.
