### ISSUE TITLE
Pirate fleets function oddly if one of their ships is destroyed while the rest are intact

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1788]
Fought a few pirates.
They were easily defeated.
The ships that survived intact (meaning 100% hull) tried to escape.
Accidentally fired on a disabled ship.
It was left with 0% hull, and the explosions began.

And the survivors returned to attacking me, to avenge their fallen.
They failed miserably.

And when one of their ships was weakened to the point where it had to (or should have, rather) escape(d) as well (meaning <100% hull), it stopped trying to resist. The ship's [icon] turned from orange to yellow, and it just floated away in space.
And I killed them all.

**Comment by toilethinges** [comment]
It's because their flagship is dying, so they attempt to flee with their flagship, but when the flagship dies, a new flagship is selected, thus sending them back into battle.

**Comment by tehhowch** [comment]
I think this was fixed by c162a34a44ca749f3edebeae92afde1bd8c4a833
