### ISSUE TITLE
Game Crashing on Outfitter Ammunition Purchase Dialog With Negative Cost

### ISSUE THREAD

**Issue by jyork03** [endless-sky/endless-sky#179]
When I go to the outfitter, a dialog pops up that says, "Do you want to reload all the ammunition for your ships? It will cost -3,500 credits." Then the game crashes.  I recently sold a ship, and that may have triggered a bug with the ammuniton count.

Update:
Ok, so the issue was related to a specific ship that got locked up and couldn't move (even after being repaired).  It was stuck floating around in a system I was in, and I think it was somehow causing the ammunition count to throw an error on the outfit page.  I fixed it by flying back to it and destroying it myself.

I hope this helps.

**Comment by endless-sky** [comment]
I think that should be fixed by commits 58d7be2 and c39b849, which make the auto-reloading ignore ships that are disabled or absent.

**Comment by endless-sky** [comment]
Fixed in 0.8.7.
