### ISSUE TITLE
Vanguard hardpoints are off

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1791]
![vanguardfail](https://cloud.githubusercontent.com/assets/16506683/19832448/d09b6976-9df1-11e6-982f-9ee6b046f6e2.png)

**Comment by toilethinges** [comment]
...uhhhh, yeah...

**Comment by jafdy** [comment]
Looks fine to me.

**Comment by Amazinite** [comment]
@jafdy the hardpoint coordinates are located ahead of the actual guns on the sprites, same as the Rainmaker.

**Comment by Bladewood** [comment]
You should have at least noticed the floating thruster flare sprites :|

**Comment by jafdy** [comment]
I've found the problem. The engines need to move by -15 in y the weapons except the central gun needs to move by +10 in y.

**Comment by Pointedstick** [comment]
This was my bad, sorry. I didn't realize there was a visual tool to do the hardpoints way back when I created the Vanguard, and the problem isn't obvious unless you use beam-type guns.

**Comment by toilethinges** [comment]
@Pointedstick, it looks great with the guns it normally uses (Proton/Particle cannons)!

(Unrelated, does anyone else use the Vanguard? I like its appearance and, with 7 Particle Cannons, it can do some good damage to Korath Raiders.)

**Comment by Amazinite** [comment]
(If not Bactrian then usually Vanguard for me, in terms of human warships).

**Comment by Bladewood** [comment]
Dreadnought.
If you want particle cannon spam, go for a Kestrel.

**Comment by Pointedstick** [comment]
Derecho with quad Sunbeam turrets for me. I often run around in a Vanguard with 7 Proton cannons during earlier parts of the Free Worlds campaign, though. It's a heck of a lot more fun than the Protector (which is why I made it).

**Comment by Johny-Cash** [comment]
All flamethrower suicide troop. The Vanguard is great for this.

**Comment by KiLEdEnNis** [comment]
full Flamethrower & Dual Sunbeam, & fuel pods
lolk Vanguard > Korath

**Comment by Bladewood** [comment]
But... shield beetle...

**Comment by Admiral-Danforth** [comment]
But... Pug Maboro

**Comment by KiLEdEnNis** [comment]
but... Archon
lolk

**Comment by Admiral-Danforth** [comment]
Archon makes a great ship, but if you use more than one they end up killing each other.

**Comment by Bladewood** [comment]
They do not :|
(yes, I tried this, and in fact I did it a few hours ago)

**Comment by LocalGod79** [comment]
@Bladewood, a fix has been implemented.

if you are finished your misplaced Steam-talk, would you be so kind as to close this issue?

**Comment by Bladewood** [comment]
Of course.

**Comment by Bladewood** [comment]
Post-turret hardpoint sprite additions.

What we have **now**:
![vanguardfail3](https://user-images.githubusercontent.com/16506683/27254954-abefb4c6-5361-11e7-8a1b-1276320ab752.png)
(Closer to) what we **should** have:
![vanguardfail4](https://user-images.githubusercontent.com/16506683/27254955-b1808ed8-5361-11e7-94ec-72f8746669d9.png)

**Comment by endless-sky** [comment]
Fixed in 4596382.
