### ISSUE TITLE
Make it more obvious that targets that overheat are only temporarily disabled

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1792]
When I first started out playing with plasma cannons, I did not quite understand the heat damage stat it carried.
And so, when I covered a fleet full of shield beetles with plasma turrets, I did not understand why I was only able to board some of the Quarg wardragons they "disabled."
I think you should make the fact that they were actually disabled via heat damage a bit more obvious, such as by turning our targets' ship [icons] red, rather than a dark shade of gray.

**Comment by DingusShingleton** [comment]
Or a status effect, like disruption damage/slowing damage. That's... much more work obviously, but I would look really cool and make people want to use heat damage more, I think. Or at least, it would for me hehe

**Comment by Limb-Slaveee** [comment]
Or make smoke come out of the ship.

**Comment by retrue** [comment]
Smoke would never come out of a ship in space. If the fire is on the inside of the ship there is not outside smoke because the ship is completely closed to avoid air going out. But if the fire is on the outside, there is not fire because there is not air in space.

**Comment by KiLEdEnNis** [comment]
a red glow (like when cloaked but way less visible) could help? would be easy & does the job on most ships
downside? for example the Skylark, what to do... :/

**Comment by endless-sky** [comment]
As a possible solution, I've made it so the radar dot, outline, and crosshairs for overheated targets blink instead of being solid grey (86ee9ad).

**Comment by Bladewood** [comment]
Your commit makes it so that it blinks between gray and the ship's normal active color. I feel this actually makes it *more* confusing, rather than less.

**Comment by Amazinite** [comment]
Maybe instead, their HUD outline, those little pointer things around the sprite, and the minimap dot should turn a bright red that's distinctive from the normal orange/yellow that hostiles are.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
