### ISSUE TITLE
Expedition to Hope

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1794]
This might be a little nit-picky, but one of the scientists uses the words "You probably know about the supervolcano that forced the evacuation of Hope **two decades ago**." Depending on how long it has taken you to pick up this mission, it could be three or even four decades ago that it occurred.

**Comment by Bladewood** [comment]
Just take out the number and that should do it.

**Comment by Alkallid** [comment]
Is it an actual set date, though? If it does, then Katya's age would be determinable as impossible.

**Comment by Alkallid** [comment]
Or could be, if you aren't the grinding type.

**Comment by Amazinite** [comment]
@Alkallid 2994 is when the eruption happened, so yes. It is a set date.

**Comment by Alkallid** [comment]
I never saw that. Where does it say?

**Comment by Amazinite** [comment]
On Hope itself...

**Comment by Bladewood** [comment]
> In the year 2994, Hope was a somewhat cold but otherwise hospitable planet, ...

huh.

also, changing my earlier proposal, should be "a few decades ago" rather than just "decades ago".

**Comment by DingusShingleton** [comment]
'Several decades ago' sounds more scientisty

**Comment by LocalGod79** [comment]
couldn't a series of branches take place in that conversation, based on the year portion of the date conditions?

**Comment by KiLEdEnNis** [comment]
if you don't start the main story until 1000 years later, nothing would make sense either
you would be dead yourself by old age, & everyone else too, the FW would be taken over etc.

**Comment by LocalGod79** [comment]
you don't actually experience the passage of those days, though - you "spend" most of them in hyperspace - the Plot Device (a.k.a. hyperdrive) extended the lifespan of humans more than medical science had in over a millennia...

**Comment by KiLEdEnNis** [comment]
@LocalGod79 but the game could theoretically go on for thousands of years, & I doubt humans can live that long
this thread is about 1 small detail which could be fixed, but in-game "time" won't make sense anyway if you're in like 8054

**Comment by jafdy** [comment]
Some one should open an issue requesting an end for the game. (Retirement perhaps?)

**Comment by Amazinite** [comment]
Plot twist:
After a battle with the Pug, you get sent through a wormhole back in time.
You end up on New Boston in 3014.
You are James.

**Comment by Bladewood** [comment]
"3014"
but
the game starts in 3013
are we a clone of James or something?

**Comment by retrue** [comment]
About this I thought that after, dunno, maybe 100 years in game, you should be presented with a message saying that you retire and you are authomatically replaced by your grandchild and then you would be able to input your grandchild name.

**Comment by Bladewood** [comment]
...what makes you think we'd have children?

**Comment by retrue** [comment]
Maybe they are adopted.
In the Vorkosigan series of novels, some very rich people solved this problem with cloning themselves and then transplating the brain from the old body to the new one.
But I don't think that this idea should be adopted without some background.

**Comment by KiLEdEnNis** [comment]
the brains would become old anyway

**Comment by endless-sky** [comment]
Fixed by merging #2002.
