### ISSUE TITLE
Out of date information in HistoricalTimeline

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1795]
In the last entry for the year 3000, it states: "The Republic has made several unpopular decisions, including license fees on various classes of starships," I assume this is from when there were many different licenses for different ships in a previous iteration of the game however, since those have been removed, this is no longer true.

**Comment by Bladewood** [comment]
I think the licensing system still technically exists, just heavily simplified for the sake of gameplay.

**Comment by warp-core** [comment]
Yes but it only applies to the pilot's license and then those for Navy ships but I would assume that the Navy licenses would have been around for as long as the Republic and even if they hadn't, the introduction of Navy licenses probably wouldn't affect most ordinary citizens anyway because they'd likely be using freighters and some heavy warships but probably not Navy vessels. I think it should be modified in some way to at least reflect that only the pilot's license applies to ordinary citizens.

**Comment by endless-sky** [comment]
I tweaked the description slightly.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
