### ISSUE TITLE
Deep river cargo seems too low compared to other freighters

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1796]
![screen shot 2016-10-30 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/22384290/19839395/cd9766f4-9eae-11e6-917b-cf94b319442d.png)
Compared to the other freighters its cargo seems low.

**Comment by KiLEdEnNis** [comment]
still, it's a lot of cargo pods loaded on a ship, so kinda space-inefficient

**Comment by Amazinite** [comment]
If anything, having it be mostly cargo pods should make it more efficient.

**Comment by KiLEdEnNis** [comment]
space-efficient? if they were just 1 long straight line instead of cargo pods w/ space between them they could have more cargo

**Comment by Amazinite** [comment]
Each of those crates on the Deep River is bigger than the 12 cargo holds on the Bulk Freighter and they have little space in between them. It's not like they're loosing out on hundreds of tons of cargo space from the few pixels of space between each pod.

**Comment by KiLEdEnNis** [comment]
in total it could be more (probably is), but it's less space-efficient I think

**Comment by Admiral-Danforth** [comment]
Wanderer=Efficient that is also why it has pods in the first place.

**Comment by KiLEdEnNis** [comment]
long pods would still be better than small pods tbf but I get the point :P

**Comment by DingusShingleton** [comment]
Pods are less space-efficient in an absolute sense... but they make loading and unloading of gear exponentially more efficient. Just look at container ships.... they don't just load everything into one massive crate

**Comment by Amazinite** [comment]
Why close milestoned issues?

**Comment by endless-sky** [comment]
Addressed in 76863b5 (increased space from 760 to 1140). Now that mass expansions are nerfed, creating a ship with a lot more cargo space is not a problem.
