### ISSUE TITLE
Should Pug Gridfire Turrets damage other Pug ships?

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1797]
When you have a fleet of Pug Arfectas the #1 cause of death is other Pug Arfectas. Wouldn't it make sense if the Pug designed them, so they would be unable to damage fleets in their ships?

**Comment by toilethinges** [comment]
AoE will always hurt everything.

**Comment by Admiral-Danforth** [comment]
It seems like the Pug would have made it, so they cannot hurt each other.

**Comment by Pointedstick** [comment]
Who knows why the Pug do anything?

**Comment by Amazinite** [comment]
This is a duplicate of a previous issue asking that blast radius not damage friendlies. Not sure which one though.

**Comment by Amazinite** [comment]
#1341

**Comment by toilethinges** [comment]
#821

**Comment by Amazinite** [comment]
Was going to post both, but 1341 has MZ's explanation.

**Comment by Admiral-Danforth** [comment]
I'm not sure if you understand. There is two questions being asked:
A. Should Pug ships be able to damage each other with AoE?
B. Should AoE affect friendlies?

Question B. has been answered, A. has not.

**Comment by Bladewood** [comment]
A. It's fine if Pug ships damage each other, they have cloaking devices and can regenerate themselves and such.

**Comment by Amazinite** [comment]
Question A and B are the same thing, though...
"Should Pug be able to damage other Pug"
"Should friendlies be able to damage other friendlies."
Pug are friendly to eachother.

(Please close this issue.)

**Comment by Bladewood** [comment]
Not Pug vs Pug, Pug *ships* vs Pug *ships*.

**Comment by Amazinite** [comment]
So making Pug ships invincible to certain weapons?
Absolutely not.

**Comment by Admiral-Danforth** [comment]
Maybe just the AI?

**Comment by Amazinite** [comment]
How would that even make sense lore wise and even logically?

**Comment by Admiral-Danforth** [comment]
I've tried this, but in theory you could use this to your advantage and use it against the Pug Arfecta.

**Comment by Amazinite** [comment]
>How would that make sense lore wise and even logically?

**Comment by KiLEdEnNis** [comment]
> Pug are friendly to eachother.

remember MZ may have leaked 1 "Pug faction", and that there are apparently gonna be more? :3

**Comment by Pointedstick** [comment]
@Admiral-Danforth You're tempting me to create my own Please-Close-This-Issue sockpuppet account… 😝

**Comment by Amazinite** [comment]
The answer is yes.

**Comment by toilethinges** [comment]
@Amazinite 

> > How would that make sense lore wise and even logically?

Wyrmholes! (See what I did there?)
