### ISSUE TITLE
Help our ship has ran out of energy!

### ISSUE THREAD

**Issue by Safari-Is-Amazing** [endless-sky/endless-sky#1798]
Add this message for when your ship doesn't have enough energy.

**Comment by Amazinite** [comment]
But you can't transfer energy...

**Comment by jafdy** [comment]
Why not. Could be a good way of saving players who have set of with only batteries.

**Comment by Safari-Is-Amazing** [comment]
Umm you can charge a phone.....

**Comment by KiLEdEnNis** [comment]
you can't really connect an exterior cable from generator to battery in space

**Comment by Admiral-Danforth** [comment]
If you can provide fuel why not energy.

**Comment by Pointedstick** [comment]
> If you can provide fuel why not energy?

That would be a separate request. This request only concerns a message.

**Comment by Admiral-Danforth** [comment]
If you have one you must have the other, like surf & turf.

**Comment by KiLEdEnNis** [comment]
like in a car, you can easily add fuel, not power

**Comment by Admiral-Danforth** [comment]
Tesla

**Comment by KiLEdEnNis** [comment]
yes an electric car
we have electric hyperdrives? :P

**Comment by Admiral-Danforth** [comment]
This is for battery only ships

**Comment by Amazinite** [comment]
> you can't really connect an exterior cable from generator to battery in space

**Comment by Admiral-Danforth** [comment]
Who says it has to be exterior?

**Comment by Admiral-Danforth** [comment]
Who says it has to be exterior?

**Comment by Pointedstick** [comment]
@Admiral-Danforth, please go away. You're wasting everybody's time with this junk.

**Comment by KiLEdEnNis** [comment]
how can it be interior?
