### ISSUE TITLE
Ships in fleet will not attack each other with fire command

### ISSUE THREAD

**Issue by Safari-Is-Amazing** [endless-sky/endless-sky#1799]
Shift+n; choose ship; press f; nothing happens; I'm annoyed.

Please fix this

**Comment by Pointedstick** [comment]
Why would you want your ships to attack one another? And why would their captains comply with such an order?

**Comment by Safari-Is-Amazing** [comment]
Target practice, war games, and I'm to lazy to sell or disown them.

**Comment by Amazinite** [comment]
> I'm to lazy to sell or disown them.

Really? This just seems like a pointless request then since 99.99% of people will either sell or disown ships they don't want anyways, or even blow them up themselves with their flagship. No need to have your entire fleet attack your own escorts.

**Comment by Pointedstick** [comment]
> I'm to lazy to sell or disown them.

Boy, that sounds like a great reason to implement this. 😉

**Comment by Safari-Is-Amazing** [comment]
Also testing out modded weapons

**Comment by Amazinite** [comment]
Just test modded weapons on random pirates or merchants...
Or set up a job that can be offered anywhere and spawns two ships that fight each other.

**Comment by Please-Close-This-Issue** [comment]
**The Button's Right Below**

**Comment by Pointedstick** [comment]
Can we have a minimum age requirement for the Github issues page? 😁
