### ISSUE TITLE
No image on FreeBSD in fullscreen mode

### ISSUE THREAD

**Issue by AMDmi3** [endless-sky/endless-sky#18]
When I first ran the game, there was nothing than black screen. Turned out that this problem only exists in fullscreen mode, when I've created config file with fullscreen=0 line by hand everything went fine. I use nvidia driver and 2 monitor configuration.

PS. This is the last problem I see on FreeBSD, otherwise it works great!

**Comment by endless-sky** [comment]
My guess is that this is because of the 2-monitor configuration. I can look into how SDL is setting fullscreen mode and whether there are known bugs with that.

In the latest code, I switched to having it start windowed by default. That seems to be a better approach because if any bugs do occur the first time you run the program, dealing with a non-functioning window is a lot easier than dealing with a non-functioning full-screen app. :)

**Comment by AMDmi3** [comment]
> My guess is that this is because of the 2-monitor configuration. I can look into how SDL is setting fullscreen mode and whether there are known bugs with that.

Some games (red eclipse afair) really do try to set fullscreen on both monitors, and this works (e.g. graphics are shown, though it's of course ungly due to inter-monitor gap and different resolutions). This is usually fixed by Alt+Enter, and I'm not sure whether it's handled by the game itself or my wm (notion, tiled wm, which may also affect such stuff). With endless sky it doesn't work. Gonna experiment a bit more.

> In the latest code, I switched to having it start windowed by default. That seems to be a better approach because if any bugs do occur the first time you run the program, dealing with a non-functioning window is a lot easier than dealing with a non-functioning full-screen app. :)

That's great, gonna check it out.

**Comment by endless-sky** [comment]
I think Alt+Enter is just a common keyboard mapping for "Toggle fullscreen" - not something the window manager handles. I used F11 for fullscreen instead, which is the other common mapping for it. I could have Alt+Enter be an automatic second way of toggling full-screen. My only worry would be that someone might hit Alt+Enter by accident and say, "Why did that toggle full screen? I have that mapped to F11."

**Comment by AMDmi3** [comment]
No, notion has Alt+Enter explicitly mapped to fullscreen toggle.

**Comment by endless-sky** [comment]
Well, I explicitly added Alt+Enter as a shortcut for toggle full screen (commit aa3c2a6). I looked through the SDL documentation and a lot of web forums to see if there's a way to instead receive a "toggle full screen" message from the window manager, but could not find anything.
