### ISSUE TITLE
Infinite number (make a number that will allow for infinite outfit space/fuel/engine/ect.)

### ISSUE THREAD

**Issue by Johny-Cash** [endless-sky/endless-sky#1801]

**Comment by Pointedstick** [comment]
Why in the world would anyone want that? Relatedly, are you 12 years old, or a sock puppet of @Admiral-Danforth?

**Comment by Amazinite** [comment]
Just add a bunch of zeros.
Where's that "Please-close-this-issue" sock puppet when you need it?

**Comment by Please-Close-This-Issue** [comment]
**Hiding**

**Comment by Johny-Cash** [comment]
Use zeros and the game won't load, also too make Fliver go 400000mph

**Comment by Bladewood** [comment]
Set drag on a flivver to 0, and you have an infinite max speed.

A thruster with infinite thrust would just break the game.
