### ISSUE TITLE
Memory Leak on opened Map / Outfitter pages.

### ISSUE THREAD

**Issue by HearsAWho** [endless-sky/endless-sky#1806]
I have noticed that after I'de been playing the game for ~1 hour (on version 0.9.4 (win 64)) my game would start to have freezing issues, after checking with system processes looks like a memory leak (or 2?) that creeps up with opened map interface, and outfitter page. can anyone else confirm?

**Comment by HearsAWho** [comment]
happens on my machine with 32 bit version as well.

**Comment by Amazinite** [comment]
On 64 bit windows. My memory is fine, but my CPU skyrockets.
![map](https://cloud.githubusercontent.com/assets/17688683/19950046/8eccb6ac-a12b-11e6-9bae-e4cc58621721.png)
![map2](https://cloud.githubusercontent.com/assets/17688683/19950047/8eef83da-a12b-11e6-8428-3c273b14d1e4.png)

**Comment by endless-sky** [comment]
Valgrind isn't catching any memory leaks, and if I leave the program open to either of those panels for a long time without doing anything, I don't see memory increasing. But, I do see memory increasing when moving the map around. It's possible that the way I was doing the "fog of war" background in the map was using up video memory. If so, 1d13f13 should fix that.

**Comment by HearsAWho** [comment]
interesting because if i leave it on either page without doing anything it still increases. i opened the game, went to "in flight" and sat for a min to take the first screenshot, then landed  (opened paint and saved first pic, as noticed by the uptick and down tick in physical memory on second screenshot) then opened outfitter screen, and sat at outfitter screen for a couple min's with no inputs then took second screenshot. if i leave it there it will keep hoggin till my system starts to freeze up. (the process happens identically with map screen for me)

my system is definitely doing something screwy, any ideas?
![in world](https://cloud.githubusercontent.com/assets/23223852/19952759/6737530c-a12d-11e6-98c6-222094a13e85.png)

![outfitter](https://cloud.githubusercontent.com/assets/23223852/19952763/6c6883a0-a12d-11e6-9dbd-0254f26635f4.png)

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
