### ISSUE TITLE
Unselected outfits' images are not hidden by the black box (with the selected outfit description and stuff)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1807]
![whywhitesunwhy1](https://cloud.githubusercontent.com/assets/16506683/19989499/623acc50-a1fd-11e6-964e-c7d1f4ded4fa.png)
Note that the same thing does not happen if you select the offending outfit.
![whywhitesunwhy2](https://cloud.githubusercontent.com/assets/16506683/19989500/62bb6cc0-a1fd-11e6-92ac-e89a5c0479cc.png)

**Comment by Lineth** [comment]
Still overlaps in the second photo.

**Comment by Amazinite** [comment]
He means that the white line overlaps the outfit image when you aren't selecting it, but when you do select it then the white line is overlapped by the outfit image.

**Comment by jafdy** [comment]
@Lineth it overlaps in the second photo, the first photo shows the bug, the sprite "underlaps" the lines.

**Comment by Lineth** [comment]
Oh. Don't mind me I'm braindead/totally misread the title.

**Comment by Bladewood** [comment]
Noticed that the offending outfit's sprite only goes under the line if it is to the left of the selected outfit. Otherwise, it is above the line.

**Comment by KiLEdEnNis** [comment]
@Bladewood that's some weird bug then
not as weird as escorts w/o hyperdrives disappearing because they try & board themself though

**Comment by Amazinite** [comment]
> not as weird as escorts w/o hyperdrives disappearing because they try & board themself though

Best bug ever.
