### ISSUE TITLE
Ripple Fire vs Salvo Fire

### ISSUE THREAD

**Issue by Mavleg** [endless-sky/endless-sky#1808]
Currently, if you have more than one gun (like particle guns or a proton guns) mounted to your ship, they will take turns firing, creating a "ripple fire" effect. This maximizes the overall rate of fire, and theoretically can prevent enemy ships from flying through your line of fire.

I am trying to create a mod, and I want to know how I can force forward-facing guns to fire all at once, like a battleship firing a full salvo. ("salvo fire") Laser weapons seem to do this already, so perhaps they hold a clue on how to manipulate the firing sequences.

Can anyone tell me how, or point me to a stock weapon system that already does this?

Any assistance would be helpful.

**Comment by Amazinite** [comment]
Github is for feature requests and bug reports. If you're wanting to ask a question, you should do so over on either the Steam forums or Google Group, or see if the answer is on the wiki. 

But to answer your question here, most weapons will default to what is known as the "stream" mode where they fire one after another. Weapons will only default to "cluster," that is firing all at once, when they have a missile strength on them. So if you want to override it for non-missile weapons to fire in "cluster," simply give that weapon the `"cluster"` attribute.
