### ISSUE TITLE
Consolidate mission and commodity information in the map view

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#181]
I *love* how you can use the map view to see available missions, commodity prices, and ship and outfit availability. One thing I think would be helpful would be to show you both the available missions and also the commodity prices for the selected system at the same time. That way, I could accept a mission to a particular planet and instantly see which commodity I should buy to maximize my profit on the trip to that planet. I think there's enough room for all this information to be shown at once.

Bonus points if you can actually buy commodities on the map view too for true one-stop shopping!

**Comment by endless-sky** [comment]
The UI is designed to work on even modest-sized screens (e.g. 1440 x 900, or even 1024 x 768 with only a few issues). That means limiting how many UI elements are cluttering the side of the map in any one view of it. In the mission UI, the two lists of missions are allowed to take up the entire vertical space on the two sides. I suppose I could reserve enough space on the left for just the trade portion of the system info, but I think that would look rather random and cluttered.
