### ISSUE TITLE
[Mission] Free Worlds Reconnaissance: Minor continuity error

### ISSUE THREAD

**Issue by daerogami** [endless-sky/endless-sky#1811]
The (first?) Free Worlds Reconnaissance mission in the Aldhibain sytem, you scan the ship orbiting over the planet. When he questions you about your scans, one of the options results in him talking about his ship being equipped with Atomic thrusters when in the scan they were clearly Ion thrusters.

**Comment by KiLEdEnNis** [comment]
didn't it have Atomic Thruster/Steerings & an Ion Steering?

**Comment by daerogami** [comment]
It's possible I overlooked them, stranger things have happened. Would need to recreate. Is that ship hard-coded to have the configuration you specified?

**Comment by Amazinite** [comment]
This is the Cruiser in question.
```
ship "Cruiser" "Cruiser (Heavy)"
	outfits
		"Heavy Rocket Launcher" 2
		"Heavy Rocket" 40
		"Particle Cannon" 4
		"Heavy Laser Turret" 2
		"Heavy Anti-Missile Turret"
		"Quad Blaster Turret"
		"Laser Rifle" 20
		"Fragmentation Grenades" 20
		"Armageddon Core"
		"Dwarf Core"
		"Supercapacitor"
		"D94-YV Shield Generator"
		"Liquid Helium Cooler"
		"Ramscoop"
		"Mass Expansion"
		"A520 Atomic Thruster"
		"A525 Atomic Steering"
		"X2200 Ion Steering"
		"Scram Drive"
```

**Comment by KiLEdEnNis** [comment]
as I thought, Atomic set & extra Ion Steering

**Comment by MasterOfTheTiger** [comment]
Hey. This may not be the best place to mention it, but whenever I scan the ship, it doesn't open a conversation, and I cannot finish the mission. Is this a bug?

**Comment by jafdy** [comment]
If you are unsure, first check the obvious problems like is it the right ship and then ask on more casual forums, unless it is repeatable there is very little we can do about it.
