### ISSUE TITLE
[Mission] Electron Beam

### ISSUE THREAD

**Issue by daerogami** [endless-sky/endless-sky#1812]
This is a free worlds mission. Shouldn't either electron tech be acceptable? I stole an electron turret, but apparently a beam is the only outfit this mission will accept.

**Comment by KiLEdEnNis** [comment]
that was addressed before, should be added (if it was in the recent update)

**Comment by Amazinite** [comment]
This was addressed a while back.
@daerogami what version are you on? Or did you compile from source?

**Comment by daerogami** [comment]
I am on 0.9.4

**Comment by KiLEdEnNis** [comment]
it should be in then, did anything go wrong...?
