### ISSUE TITLE
Energy Requests

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1813]
I'm reopening this because I messed it up last time.
Request A. _Add the ability for ships to transfer energy._ 
Request B. (If A added) _Allow escorts to communicate lack of energy._
Request C. _Allow flagship to communicate lack of energy._

**Comment by Amazinite** [comment]
Why do you need multiple accounts?

**Comment by Admiral-Danforth** [comment]
Boredom

**Comment by DingusShingleton** [comment]
Honestly, I mean, running out of fuel is one thing, but there's only so much poor player judgement that I think the game should forgive by design. If you don't even have the foresight to install at least a solar panel (3 tons), then just bit the bullet and reload your save.

**Comment by Admiral-Danforth** [comment]
![screen shot 2016-11-06 at 8 04 55 am](https://cloud.githubusercontent.com/assets/22384290/20038351/c6b2e982-a3f7-11e6-9f8a-c3bda40a71af.png)

**Comment by Amazinite** [comment]
Note the last part of the description.

>trusting that they can reach their destination planet and recharge **before running out of battery power**...

**Comment by Admiral-Danforth** [comment]
That is exactly the part of the description that this is relating to.

**Comment by KiLEdEnNis** [comment]
just install a small fuel cell or whatever
if your idea was added;
how much energy would a ship give? how would it react if it lacked the energy? what if they just have enough & then don't have energy on their own? how would they give energy at all?
compare it to cars, you can just give another car some fuel (if you know how), but you can't charge the battery of another car
maybe adding a small outfit that consumes some fuel to create some energy could work, not sure about the balance of that

**Comment by Amazinite** [comment]
@Admiral-Danforth I'm saying that it's already said in the description that running only batteries is risky, and that is exactly due to the fact that you can not request for energy. To be able to request for energy would require the removing of that part of the description, since it wouldn't be a risky thing to do anymore.

**Comment by DingusShingleton** [comment]
The smallest ramscoop that the player can buy without unlocking anything is 16 tons and 60,000 credits. That's pretty sizable, and most pilots will probably not opt to install one unless they specifically want to do a lot of deep space exploring. The smallest energy producing outfit is 3 tons at 10,000 credits. This is less than 1/5th of the ramscoop's mass and is 1/6th the cost.

It's just hard to see this as a legitimate problem that needs an outfit or structural game changes to address, considering how easy and cheap it is to add energy generation to a ship.

**Comment by Bladewood** [comment]
> The smallest ramscoop that the player can buy without unlocking anything is 16 tons and 60,000 credits. That's pretty sizable, and most pilots will probably not opt to install one unless they specifically want to do a lot of deep space exploring. The smallest energy producing outfit is 3 tons at 10,000 credits. This is less than 1/5th of the ramscoop's mass and is 1/6th the cost.

...huh?
It's 10 outfit space and 60,000 credits for a ramscoop, 16 outfit space and 320,000 credits for a catalytic ramscoop.

**Comment by DingusShingleton** [comment]
Blast, I should have double checked those stats. Even so, the point still stands.

**Comment by 1Goryl** [comment]
I have some similar problem.
Ship: Bactrian
Turrets: 4x Quarg Skylance
Systems: 
1x Jump drive
5x Large Heat Shunt
26x Mass Expansion
3x System Core (Large)
1x Wanderer Ramscoop
2x Nanotech Battery
1x Triple Plasma Core
Engins:
1x Steering (Planetary Class)
1x Thruster (Planetary Class)

Now my problem:D Enegy
idle: 2,646
moving: -810
firing: -9,000
shields/hull: -1,728
max: 75,600
I can't balance my energy cuz ship don't have more space for more reactor but still needs more energy.
second problem is heat I tried but I do not know how to solve that. any advice?
Btw Nanotech Battery and Quarg Skylance They don't have a schedule

**Comment by Elyssaen** [comment]
Have to say I agree with DingusShingleton: there is _so much_ amazing stuff that could be done to enhance this already brilliant game, and if there was a central list somewhere of how important an enhancement was, this would have to be very, very far down. It does _make sense_, I get why you want it, but surely there is never, ever going to come a time when this is the most important thing to get added.

**Comment by KiLEdEnNis** [comment]
simply put; this addition isn't important, you can't protect the player from their own (dumb) mistakes when they know what can happen
(for example, remove all engines, press escape, get the no engine message, press escape again, load/save, reload game, depart without engines & get stuck)
