### ISSUE TITLE
Most Endless Sky ships are extremely phallic; could use some more variety in basic shape

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1814]
My wife, who contributes a lot of content to this game through me, was watching me play the other day and commented on how phallic most of the ships are. I had never thought of it that way or realized this before, but she's absolutely right. By far the commonest shape for this game's ships is:
* Long and skinny
* Bulbous head/cockpit/bridge/whatever at the very tip
* Wide rear end to fit two offset engine pods

This happens to look like a penis and testicles once you're attuned to it. Some obvious examples:

![arrow](https://cloud.githubusercontent.com/assets/1097249/20039438/2b1f9470-a401-11e6-9547-7727d4ec5b87.png)

![pug enfolta](https://cloud.githubusercontent.com/assets/1097249/20039501/3d6e9dfa-a402-11e6-98f8-0db052397b61.png)

![arach transport](https://cloud.githubusercontent.com/assets/1097249/20039624/41bc60ac-a404-11e6-82a0-53ef1f44872b.png)

![corvette](https://cloud.githubusercontent.com/assets/1097249/20039444/51018fa4-a401-11e6-803c-dc9fd2ba7f2b.png)

![cruiser](https://cloud.githubusercontent.com/assets/1097249/20039446/56486d48-a401-11e6-8bbe-a9205f3df049.png)

![frigate](https://cloud.githubusercontent.com/assets/1097249/20039449/673ff6f2-a401-11e6-9c0d-fde2acde433d.png)

The first time she saw a Hauler III she burst out laughing and declared it the Space Phallus:
![hauler iii](https://cloud.githubusercontent.com/assets/1097249/20039454/7253af3e-a401-11e6-8ab3-916e9f1ac6e4.png)
Once you see it, you can't un-see it.

I like penises as much as the next person, but let's get some variety here! Quite aside from the Freudian aspects, having so many ships with the same basic shape (single forward cockpit, long body, two rear engines) gets boring; all these long skinny wedge-shaped ships start to look the same! Let's get some more non-penile ships. The Flivver, Quicksilver, Kor Mereti Model 512, Archon, and many Hai ships are obvious ones. More variety is good!

It's absolutely possible. Think of how many famous, iconic sci-fi ships completely eschewed the phallic shape:

![enterprise-tos](https://cloud.githubusercontent.com/assets/1097249/20039651/95163958-a404-11e6-8031-1c70f2f80cfd.jpg)

![borg cube](https://cloud.githubusercontent.com/assets/1097249/20039725/d4a65c0a-a405-11e6-8a57-11c8eaefe39d.jpg)

![which-star-wars-vehicle-is-meant-for-you-millennium-falcon](https://cloud.githubusercontent.com/assets/1097249/20039650/94e92e22-a404-11e6-82c9-aa9aa5cbd374.jpeg)

![star-wars-slave-1](https://cloud.githubusercontent.com/assets/1097249/20039667/e3a81dca-a404-11e6-829e-a09efab655db.jpg)

![tfg3d0](https://cloud.githubusercontent.com/assets/1097249/20039681/26efdd20-a405-11e6-9431-0cd68682ca97.JPG)

![independence-day-236114](https://cloud.githubusercontent.com/assets/1097249/20039691/5baa5a7c-a405-11e6-8861-be3b1261178b.jpg)

![bstar03-06mod1](https://cloud.githubusercontent.com/assets/1097249/20039761/bafefe82-a406-11e6-81e6-a81cb38f3838.jpg)

Ships that are more round, square, concave, or radially-symetrical are noticeably absent from Endless Sky.

**Comment by BorkBorkGoesTheCode** [comment]
Why not use the body plan of the manta ray?

**Comment by Amazinite** [comment]
Got a problem with phallic ships?

**Comment by BorkBorkGoesTheCode** [comment]
Me or Pointedstick?

**Comment by Pointedstick** [comment]
> Got a problem with phallic ships?

No, not at all! Like I said:
>I like penises as much as the next person, but let's get some variety here!

I just think more variety would be good. Especially in Human space, it gets a little old looking at so many giant space dongs all the time.

**Comment by gunqqer** [comment]
I can make a ship that is literally a cube if you want. Is that un-phallic enough?

**Comment by DingusShingleton** [comment]
Wouldn't it just look like a square, since ES has a top down viewing angle?

**Comment by Amazinite** [comment]
>Wouldn't it just look like a square, since ES has a top down viewing angle?

Yeah, a lot of these example ships do look cool in 3D, but to look at them top-down, they're a lot blander than the current ships.

**Comment by retrue** [comment]
Next year we will see more alien races. Why not alien ships with very strange shapes?
In space there is friction. No need for a ship to be aerodynamic.
In fact, more shipyards should be in space, like orbital stations, and very few of them on the planet surface.
Only some small ships would ever go to the surface. And people would move from the big ships to the planet using shuttles.
And another thing. Even the biggest ship in the game, the Korath World-Ship, can only carry 1500 people. The Enterprise in Star Trek carries much more people. The biggest real life human luxury cruiser ship carries 9000 people. A USA big aircraft carrier has a crew of 3000 people.
Massive ships could be added to the game. Ships so big that cannot land on a planet and with capacity for a lot of people.

**Comment by Amazinite** [comment]
Well we don't really have any measurements on the ships in game aside from mass, so one could say that they just aren't as big as you think.

**Comment by Bladewood** [comment]
How large were the hangars that Southbound Shipyards used to build Dreadnoughts?

**Comment by retrue** [comment]
@Amazinite Royal 

> Caribbean's newest ship, Harmony of the Seas, debuts Friday on its pre-inaugural sailing out of Southampton, England.
> Weighing 226,963 gross registered tons with a passenger capacity of 5,479 guests at double occupancy (it fits 6,780 guests total) and 2,100 crew members, Harmony is now the world's largest cruise ship. 
That is, 6780 passengers plus 2100 crewmen = 8880.

**Comment by Amazinite** [comment]
Damn Wikipedia, call it passenger capacity.

**Comment by BorkBorkGoesTheCode** [comment]
>Next year we will see more alien races. Why not alien ships with very strange shapes?
 In space there is NOT friction. No need for a ship to be aerodynamic.
 In fact, more shipyards should be in space, like orbital stations, and very few of them on the planet surface.
 Only some small ships would ever go to the surface. And people would move from the big ships to the planet using shuttles.
 And another thing. Even the biggest ship in the game, the Korath World-Ship, can only carry 1500 people. The Enterprise in Star Trek carries much more people. The biggest real life human luxury cruiser ship carries 9000 people. A USA big aircraft carrier has a crew of 3000 people.
 Massive ships could be added to the game. Ships so big that cannot land on a planet and with capacity for a lot of people.

The only issue I can forsee is a need to minimize bulk to reduce the risk of asteroid/missile collision.

**Comment by Lineth** [comment]
But the risk of asteroid collision is basically nonexistent.. Asteroids don't form thickets like in Hollywood.

**Comment by endless-sky** [comment]
Of the examples you gave, probably only the Millennium Falcon and maybe the Enterprise would "work" from a top-down perspective. If you want it to be immediately clear to the viewer what direction a concept space ship is pointing in, the easiest way is to shape the ship like an arrow (i.e. a narrow isosceles triangle, pointing forward). That gives it the same silhouette as most aircraft.

It's not impossible to work around that, but it's also not particularly easy.

**Comment by gunqqer** [comment]
Yup imma make a plugin with literal squares as ships. Who needs talent when you got... something.

**Comment by kilobyte** [comment]
> In space there is NOT friction. No need for a ship to be aerodynamic.

Except that all non-carried ships in the game do land on planets, not just occasionally but every at most a few days.

**Comment by retrue** [comment]
> Except that all non-carried ships in the game do land on planets, not just occasionally but every at most a few days.

That is just what I mean. It shouldn't be that way. Like I said, the most logical would be that only smaller ships and shuttles would be adequated to enter the atmosphere, resist that friction, and when leaving, spend that crazy amount of energy going back to space from the surface of a planet.
So, what I suggest, instead of changing the behaviour of all current ships, is to add, in the future, some ships that behave that way.

**Comment by kilobyte** [comment]
That would require changing a lot of text and dialogs in quite a bit of the story.

**Comment by Amazinite** [comment]
>Like I said, the most logical would be that only smaller ships and shuttles would be adequated to enter the atmosphere, resist that friction, and when leaving, spend that crazy amount of energy going back to space from the surface of a planet.

It's already explained in lore how people get around this.

>2360: Invention of "repulsor" engines that work only within a gravity well, but make taking off from or landing on planets much easier.

**Comment by Pointedstick** [comment]
Can you guys take the unrelated discussion about landing on planets somewhere else?

**Comment by Pointedstick** [comment]
@endless-sky
The issue with making facings easy to see could be resolved with a little (optional?) HUD direction arrow, which seems like it would be a big win if it enables more ship designs.

**Comment by kilobyte** [comment]
@Pointedstick: shape of ships is quite strongly related to being able to land on planets.

And a HUD arrow is an awkward solution to a problem current ship sprites don't have.

**Comment by jafdy** [comment]
I think this is a case of ease of use over range of art stiles. 
Have you tried making ships that aren't just pointed. It might help if you provide some top down concept.

**Comment by kilobyte** [comment]
Here's some examples from MoO2, also a 2D top-view game: [1](https://smuchadissertation.files.wordpress.com/2013/10/blue.png), [2](https://smuchadissertation.files.wordpress.com/2013/10/green.png).  In that game, though, orientation isn't that vital, it's mostly shield arc strengths that matters.

In a lot of "non-phallic" designs it's not obvious which is the front and which is the rear; for some Doom Stars like the one on [1], orientation isn't obvious at all without the engine glow (not shown on the images I linked to).

**Comment by nylki** [comment]
Escape Velocity Nova had some interesting non-phallic vessel shapes. Maybe there can be drawn inspiration for future designs?

![http://www.ambrosiasw.com/assets/images/galleries_products/evn/survival02.jpg](http://www.ambrosiasw.com/assets/images/galleries_products/evn/survival02.jpg)

![http://joshuawoehlke.com/wp-content/uploads/2015/11/evnovascreenshot.jpg](http://joshuawoehlke.com/wp-content/uploads/2015/11/evnovascreenshot.jpg)

![http://users.tpg.com.au/adsl4vhb/img/Arachnid3.JPG](http://users.tpg.com.au/adsl4vhb/img/Arachnid3.JPG)

![http://i.imgur.com/WOxjp.png](http://i.imgur.com/WOxjp.png)

![http://vignette3.wikia.nocookie.net/evn/images/6/66/Raven.png/revision/latest?cb=20111220081157](http://vignette3.wikia.nocookie.net/evn/images/6/66/Raven.png/revision/latest?cb=20111220081157)

**Comment by jafdy** [comment]
@nylki 2.5D has been noed. See Creatingships in the wiki. As for different ship shapes . . . some one needs to come up with the model.

**Comment by Pointedstick** [comment]
I opened this more for Michael than other content creators since he makes 99% of the ships in the game. The game's standard ships have a noticeable phallic bias, and the EVN screenshots show that this really doesn't have to be the case--even if rendered top-down. There are more ways to make a ship than a pointy tube with two engine pods on the back.

More EVN shots showing common and distinctly awesome but non-super-phallic ships:

![tlie5](https://cloud.githubusercontent.com/assets/1097249/20240338/393742a2-a8d3-11e6-91ff-e34a14e151ae.png)
![6przk](https://cloud.githubusercontent.com/assets/1097249/20240339/39691a98-a8d3-11e6-951d-b6f942e4ffcb.png)
![lio7l](https://cloud.githubusercontent.com/assets/1097249/20240343/396bc310-a8d3-11e6-8faf-90a0c8183b6e.png)
![pq3qd](https://cloud.githubusercontent.com/assets/1097249/20240342/396922cc-a8d3-11e6-9893-d38f056a4394.png)
<img width="523" alt="screen shot 2016-11-12 at 12 21 26 pm" src="https://cloud.githubusercontent.com/assets/1097249/20240340/396926e6-a8d3-11e6-846c-5e99cd57eb6e.png">
![lgcbul png](https://cloud.githubusercontent.com/assets/1097249/20240341/3968f93c-a8d3-11e6-87c9-81325787da02.jpeg)
![ja6af](https://cloud.githubusercontent.com/assets/1097249/20240348/509df5da-a8d3-11e6-9701-262269bb22ac.png)
![fgmpk](https://cloud.githubusercontent.com/assets/1097249/20240451/cc8ea2b4-a8d5-11e6-9ab0-fbc0463eaa78.png)
![zqk4p](https://cloud.githubusercontent.com/assets/1097249/20240453/ccbd664e-a8d5-11e6-9cb8-efce835d319d.png)
![bi9i0](https://cloud.githubusercontent.com/assets/1097249/20240454/ccbe0054-a8d5-11e6-9c33-5d908660f9ce.png)
![ja6af](https://cloud.githubusercontent.com/assets/1097249/20240455/ccbe75f2-a8d5-11e6-8ffc-1511008dc6e1.png)
![7i1s2hh](https://cloud.githubusercontent.com/assets/1097249/20240457/ccbf509e-a8d5-11e6-86db-97372e3850e1.png)
![bxfqln2](https://cloud.githubusercontent.com/assets/1097249/20240456/ccbf3686-a8d5-11e6-9c05-a590ade403e7.png)
![opk0i](https://cloud.githubusercontent.com/assets/1097249/20240452/ccb051a2-a8d5-11e6-8fc7-6103de5eb51e.png)

**Comment by Bladewood** [comment]
@Pointedstick Would this be acceptable by your standards?
![sovereign](https://cloud.githubusercontent.com/assets/16506683/20242795/82b4b60e-a909-11e6-8bb1-790c8979041b.jpg)
I tend to draw weird things when I'm bored.

**Comment by Pointedstick** [comment]
Pretty cool! You're a good artist. Looks kind of like an Arfecta. Instead of a single pointy front, what about if there were two, or three with the center one jutting out in front of the others?

**Comment by Bladewood** [comment]
It's supposed to look a bit like an Arfecta, actually; it was my take on a Pug ship. Your comment implied I was successful, so yay.

**Comment by Admiral-Danforth** [comment]
photodynamics matter

**Comment by Bladewood** [comment]
http://galaxyonfire.wikia.com/wiki/Void#Gallery
http://vignette2.wikia.nocookie.net/galaxyonfire/images/2/21/Void_HD.jpg/revision/latest/scale-to-width-down/200?cb=20130301213045
