### ISSUE TITLE
Ships with active cooling and insufficient levels of regular cooling cannot pass the "checklist"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1815]
Playing around with cooling modules.
Had an armageddon core and 3 cooling modules installed.
Expected the cooling modules to be sufficient.
They were not:
> By the time you reach the end of the checklist, it has grown uncomfortably warm.
...
You are going to have to either install cooling systems, or trade out some components for lower-heat alternatives.

**Comment by Lineth** [comment]
Might be intentional. Active cooling might be to counter heat generated by engines or weapons, but you still need regular cooling to keep your ship usable in a baseline.

**Comment by endless-sky** [comment]
See if 534ddc4 fixes this for you.

**Comment by DingusShingleton** [comment]
@Lineth Which makes sense. When I have a ship that is outfitted with repeaters (to use an extreme example) I'm forced to run its idle heat in the negative thousands. This seems like a very inefficient use of space, considering that much of the time, all that extra cooling goes to waste. Active cooling is the obvious answer. Much higher heat/mass ratio that passive cooling, but with the added cost of energy. Love it.

**Comment by Bladewood** [comment]
yay, it works

**Comment by Bladewood** [comment]
Actually, I'm not sure if this was a good idea, and I'm currently slamming my head into a nearby wall for it. Currently, cooling modules seem rather overpowered to me because of how much cooling they can provide in so little outfit space, and with so little energy drain to barely offset the benefits. Now that I've thought about @Lineth's and @DingusShingleton's inputs on the issue, I think their idea was correct and can balance this issue. Currently, I've come up with another proposal:

1. Undo https://github.com/endless-sky/endless-sky/commit/534ddc4dab35c60a3046f56fefa63f7863df0777 or do something else, such that this becomes true again:
> Active cooling might be to counter heat generated by engines or weapons, but you still need regular cooling to keep your ship usable in a baseline.

2. Under the energy and heat columns, add a row dedicated to active cooling. The energy column would list the amount of energy drained by active cooling, while the heat column would list the active cooling actually provided. (Both values would always be negative.)

**Comment by DingusShingleton** [comment]
What if the energy usage also ramps up with the cooling?

(If that's already how it works, ignore me.... haven't had a chance compile this version yet)

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
