### ISSUE TITLE
[bug/content] Oathkeeper ship in Alphas on Poisonwood mission can become hostile

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1816]
http://steamcommunity.com/sharedfiles/filedetails/?id=795750846

It was also hostile while escorting the freighters back from... wherever it was... and I almost disabled and killed it before landing. This could be a problem if people don't notice that it is an Oathkeeper ship.

Edit: Additional problem in this mission, you can complete this mission while being friendly with pirates and taking no part in the battle, perhaps switch ship government to Alpha?

EDIT: Added a change that should fix this to #1505.

Title edit: haha, I said quest.

**Comment by jafdy** [comment]
The pirates have the `kill` tag. You have to kill them to finish the mission.

**Comment by toilethinges** [comment]
@jafdy but you can watch as your two Falcons and the Cruiser kill the pirates, they don't need help.

**Comment by jafdy** [comment]
I don't see any problem with this.

**Comment by toilethinges** [comment]
To elaborate, your escorts can attack and kill your mission escort, the N.S. Peacemaker, and kill it, failing the mission. The only way to prevent it is to mess with your save files, or outrun it (somehow) and kill stuff for reputation. 

(I don't even know how I got negative reputation, as well, because I've never attacked any Oathkeepers.)

**Comment by jafdy** [comment]
That's an easy fix. Have the mission set `reputation oathkeeper: >?100` that way unless you kill merchants/militia on the way back from big sky(?) it will be friendly.

**Comment by endless-sky** [comment]
If the only way this can happen is if the player is attacking merchants or militia, then I see no reason to change it; if you're doing that then you have no reason to assume that even the Free Worlds will stay friendly, so it's not surprising that Free Worlds missions would break.
