### ISSUE TITLE
FW escort mission fail

### ISSUE THREAD

**Issue by miguliw** [endless-sky/endless-sky#1817]
I was doing a free worlds guest where i had to escort a transport fleet to tarazed and back. (Guest was something about building an university.) After leaving tarazed, i was supposed to bring the escorts back to winter, but after few jumps i didn't see the next guest marker on the map anymore. I think one of my escorts got destroyed and the mission failed. How can i restart the mission or fix this problem? I don't have the pre-mission save files anymore.

Here is my current save file

[mig william.txt](https://github.com/endless-sky/endless-sky/files/584259/mig.william.txt)

Thank you in advance!

**Comment by Amazinite** [comment]
GitHub is for bug reports and feature requests. Questions like this are better asked on the Steam forums or Google Group.

**Comment by Amazinite** [comment]
I see the thread on Steam. You should close this now.
