### ISSUE TITLE
[Content] save file names

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#1818]
This feels like a topic that has been moved to the back (for good reason, it isn't the most needed) but I still want to put it in the light for a bit

When you make a new save of your game (not a new character) you have two options; to make it the current in game date, or for a custom name.

It would be nice if you could have a custom template so you could have it be more custom to what you want.

"<date>, save number <save #>, (notes)"
For example "3016-11-10, save number 15, free worlds start"
(the note would be addable when you are saving it)

**Comment by endless-sky** [comment]
Technically, you could do this manually, e.g. call your first save "00 free worlds start" and just use the next number each time you do a snapshot.

**Comment by Amazinite** [comment]
This isn't really worth the dev effort to implement since, as MZ says, you can just type out the save files yourself.
