### ISSUE TITLE
NPC Afterburner behavior

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1819]
When an NPC has an afterburner that does not use the `"afterburner fuel"` attribute, it will use it 100% of the time during combat, regardless of how much energy is consumed or heat is produced. 

So obviously the afterburner mechanic is made on the idea of the `"afterburner fuel"` attribute also being used along side it and the NPC conserving fuel, but this makes it somewhat annoying when creating an afterburner that instead of using fuel consumes large amounts of energy and produces a lot of heat. The NPCs end up either running themselves out of energy to be destroyed or overheating themselves to also be destroyed.

Requested having the NPCs also take energy and heat into account when using their afterburners. (Maybe something like don't use the afterburner if below 25% energy or above 75% heat.)

**Comment by jafdy** [comment]
Wouldn't the energy mess up with perpetual combat designs and one the only have super capacitors for energy storage (to fire projectile weapons).

**Comment by Amazinite** [comment]
What do you mean by that?

**Comment by jafdy** [comment]
If I have 150 energy storage and if I have a gun that uses 125 energy per shot then every time that gun is fired the ship would stop using the afterburner. This would happen even if you had more energy production then you could possibly need.

And what would the AI do with ships without energy storage. You would work out energy proportion with current-energy divided by total-storage. If you have no storage then you would get a divide by 0 error.

**Comment by KiLEdEnNis** [comment]
> then you would get a divide by 0 error.

I can already see escorts disappearing :P

**Comment by Amazinite** [comment]
> I can already see escorts disappearing :P

Actually, the game would crash. 

>  This would happen even if you had more energy production then you could possibly need.

What I requested in OP is just a suggestion. If the 25% energy capacity thing doesn't work, other things can be done. 

> And what would the AI do with ships without energy storage.

Do any NPC ships even exist like that? At that point it's a player-fault kind of thing.

**Comment by tehhowch** [comment]
This is addressed now, courtesy of #3063
