### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Szunti** [endless-sky/endless-sky#182]
Just compiled 8aac457.

Never played before, I think it's because the recent file is not created yet.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9037c615c4 in fclose@@GLIBC_2.2.5 () from /usr/lib/libc.so.6
#1  0x0000000000466aa8 in Files::Read(std::string const&) ()
#2  0x0000000000500bcd in PlayerInfo::LoadRecent() ()
#3  0x000000000040bed1 in main ()
```

**Comment by endless-sky** [comment]
Check and see if this is fixed in commit 844915d.

**Comment by Szunti** [comment]
It fixes the immediate segfault.

**Comment by clort81** [comment]
Would be nice if debian package maintainer would wake up on this one, 10 years on...

**Comment by TomGoodIdea** [comment]
> Would be nice if debian package maintainer would wake up on this one, 10 years on...

The debian package isn't currently maintained by us, so if you have any problems with the package, report it on the Debian side.

If you experience crashes on master, please open a new issue.
