### ISSUE TITLE
Firebird description historical issue

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#1820]
The description of the Firebird says: "Firebirds fought on both sides of the Alpha Wars nearly half a millennium ago," but the historical timeline shows the Alpha Wars to have started in 2450 and to have been over by 2470, slightly over half a millennium before the player starts the game.

**Comment by Admiral-Danforth** [comment]
Just change it to around and it will be fine.

**Comment by jafdy** [comment]
@warp-core could you close this as there is a PR open for it.
