### ISSUE TITLE
minor issue with southern and northern merchants 

### ISSUE THREAD

**Issue by Phil-Morley** [endless-sky/endless-sky#1821]
pretty minor but Yed Prior has northern merchants 
even more minor is that Regulus is near the edge of north south but has only southern merchants and pirates (Merak and Phecda further south have a mix of the two)

**Comment by Bladewood** [comment]
And pirate bactrians can appear in the South.

**Comment by Phil-Morley** [comment]
also
system Kugel	fleet "Small Syndicate" 80200, but maybe they are supposed to very rare :) unlike 
system Eteron	fleet "Large Republic" 400

**Comment by KiLEdEnNis** [comment]
@Bladewood wait that's actually added?

**Comment by endless-sky** [comment]
Fixed in eb03b2d.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
