### ISSUE TITLE
Add how to create licenses to the wiki page

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#1822]
There is nothing in the Wiki about licenses, how to create them, ... even though you can specify them using the property `licenses`.

Same for the outfits, nothing is mentioned about creating licenses at all.

Shouldn't this be included/added to the Wiki so that users can know how to create licenses without going through the data?

**Comment by Wrzlprnft** [comment]
Yup, it should be. Although, please change the title to something like "wiki addition:licenses?" Or add a simple (wiki) at the end or whatever, since it is really misleading

**Comment by Amazinite** [comment]
Documentation: creating licenses.

**Comment by endless-sky** [comment]
Added to the [creating ships](https://github.com/endless-sky/endless-sky/wiki/CreatingShips) page.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
