### ISSUE TITLE
Weapon range problem (affecting AI behaviour)

### ISSUE THREAD

**Issue by Elyssaen** [endless-sky/endless-sky#1826]
I'm having some trouble with some 'clever' submunition chains: the AI can't work out the range of some of these weapons.

```
double Weapon::TotalLifetime() const
{
	if(totalLifetime < 0.)
	{
		totalLifetime = 0.;
		for(const auto &it : submunitions)
			totalLifetime = max(totalLifetime, it.first->TotalLifetime());
		totalLifetime += lifetime;
	}
	return totalLifetime;
}

double Weapon::Range() const
{
	return Velocity() * TotalLifetime();
}
```

I think there are two problems with what this does:

1. The "random lifetime" attribute isn't supported.
2. TotalLifetime()'s calculation is otherwise logical, but Velocity is only based on the first munition. If it's slow and a submunition is fast, the AI won't know how to fire the weapon.

I can see 2 probably doesn't matter for the Thunderhead: it shows 3200 instead of 4000, which isn't important, and getting to 4000 would require the submunition be aware of the parent velocity. It does matter for a few weapons I'm trying to create, as it gives them a very low range in the AI's (and outfitter's) eyes.

[**Edit:** I've improved on the below, and have a post a bit further down where I _think_ I've cracked this, the right way, and have pasted the code changes I think do it. Would appreciate some feedback! I've left the below for reference to my thought process but I've since worked out some of it is wrong. : )] 

What would the consequences be of switching to

```
		totalLifetime += lifetime + 0.5 * randomLifetime;
```
then making the submunitions aware of their true velocity (blind guess: not easy) and having a block like this? 

```
double Weapon::Range() const
{
	if(Range < 0.)
	{
		Range = 0.;
		for(const auto &it : submunitions)
			Range = max(Range, it.first->Range());
		Range += Velocity() * lifetime;
	}
	return Range;
}
```

Alternatively – probably easier and _perhaps_ even better – could we add a "range" attribute to a weapon so you can _tell_ the code to override the basic calculation with a custom range?

If I can get some feedback, I'm happy to try writing whatever change seems best and make a pull request. Some weapons I'm trying to make are broken right now, so if no code changes look like a good idea I'd appreciate some help with the weapons instead. : )

– Elyssaen _(not experienced with C++, but enthusiastic)_

**Comment by Amazinite** [comment]
The way I've gotten around this so far is to have fake submunitions. Range = (parent velocity) x (parent lifetime) + (highest lifetime of any of the submunitions), so creating a fake submunition with a lifetime set to whatever range you want the weapon to fire at remedies the problem. 

But I would be interested in the calculations taking random lifetime and random velocity into effect, using the halfway number so that the range in outfitter is actually right between the minimum possible and maximum possible range.

**Comment by Elyssaen** [comment]
Hey, thank you for the feedback.

It's a neat idea, but how did you then fix the targeting issue it creates? I tried the same idea a few days back (I called them 'tracers' too!), but the automatic targeting of a turret takes into account TotalLifetime to work out a 'rendezvous time', so the false TotalLifetime a tracer creates makes a turret constantly miss unless no-one is moving. See in **Hardpoint.cpp**:

```
steps = steps = outfit->TotalLifetime()
aim = Angle(p + steps * v)
```

Looking at the link, did you only use it on a forward-firing cannon? That'd work, except for me. (Damn.)

I tried another fix back then as well, a _really_ bodgy one. My first munition is a tracer with velocity = TracerSpeed, it decays into a 'reverse tracer' with -2*TracerSpeed, then decays into the first real projectile with velocity = RealSpeed + TracerSpeed. You choose a TracerSpeed = Range/TotalLifetime. But, as horrific as it is, it's even worse because:

1. It destroys the inaccuracy attribute: your first real munition will calculate angular spread based on a silly nominal velocity it doesn't actually have. Can fix _that_ by choosing an inaccuracy value roughly RealSpeed/TracerSpeed times lower than you actually want.
2. Even fake submunitions can collide, since collision takes a projectile as a line segment, not an alpha map of the projectile sprite (understandable). The whole scheme will fall down if a fake submunition collides with anything, because in this bodge the real munitions don't even happen until the fake one is done.

I'm seriously close to creating an arbitrary range override and a "no collision" attribute in my own fork. I _think_ I can do both fairly cleanly, and at least then I can test my weapons!

I'm becoming quite attached to the range override idea, actually. I don't think it's really a 'bodge' at all: for some weapons, there really is no one calculation that can tell the AI the effective range to consider. Giving an override to content creators to put in a more sensible number really helps with fringe cases of homing/turning, acceleration/drag, submunition chains, random velocity/lifetime and even inaccuracy.

(Aside: You ever come across the problem of wanting a "no collision" attribute? I've got it with a second weapon too, that doesn't have the other problems...)

**Comment by Amazinite** [comment]
>Looking at the link, did you only use it on a forward-firing cannon? That'd work, except for me. (Damn.)

Yeah, I've only been using these tracers on guns. I hadn't even thought of the problems it would create on a turret. :/
Well if you can get an actual fix going, that's be great. :+1:

**Comment by Elyssaen** [comment]
Okay, I've got something.

A "range override" attribute doesn't work beyond the Outfitter Panel. Namely, I've found out that AutoFire in **AI.cpp** recalculates the range from Velocity() to handle relative ship velocity. Guess this is the bit that stops EV fans doing a Monty Python – makes sense!

I came back to the conclusion that Velocity() isn't always a good number, and back on board with you that it'd be nice if totalLifetime picked up half randomLifetime.

On a local fork, I then tried a "velocity override" just to see if it would fix the problem, using it in both Weapon::Range() _and_ in AutoFire. It seemed to work perfectly, though I need someone more experienced with the code to review my logic.

Doing it properly, to my mind, involves the randomLifetime bit in the definition of TotalLifetime(), then a solid Range() calculation that includes submunitions and RandomVelocity, and finally a WeightedVelocity() definition to feed into AutoFire.

So... I've done it, and it's fixed my weapon. But, disclaimer, I-Am-Not-A-C++-Programmer, and I really need a code/logic review. What I've changed is described below. If I'm on the right track I'll see if I can tidy up the calculation (Range's new equation could be better), and I'll work out how to submit a pull request.

Edit to **Weapon.h** adding new line 102:

`double WeightedVelocity() const;`

Edit to **Weapon.cpp** from line 248:

```
double Weapon::TotalLifetime() const
{
	if(totalLifetime < 0.)
	{
		totalLifetime = 0.;
		for(const auto &it : submunitions)
			totalLifetime = max(totalLifetime, it.first->TotalLifetime());
		totalLifetime += lifetime + 0.5 * randomLifetime;
	}
	return totalLifetime;
}


// Calculate the range of a weapon to display in the outfitter panel.
// Has to take into account the range of submunitions, which itself has
// to be modified by the parent's velocity multiplied by its lifetime.

double Weapon::Range() const
{
    double range = 0.;

    for(const auto &it : submunitions)
        range = max(range, it.first->Range() + (Velocity() + 0.5 * RandomVelocity())
                    * (it.first->lifetime + 0.5 * it.first->randomLifetime));
    range += (Velocity() + 0.5 * RandomVelocity()) * (lifetime + 0.5 * randomLifetime);

	return range;
}


// Calculate a weighted velocity to inform AI firing decisions.

double Weapon::WeightedVelocity() const
{
	return Range()/TotalLifetime();
}
```

Edit to **AI.cpp** on line 1642:

`        double vp = outfit->WeightedVelocity();`

Hope this is clear and somewhat close to the right way to go about discussing this. : )

**Comment by Elyssaen** [comment]
> Not if you fire the real munition and fake munition at the same time.

I'm not sure you always can. Your Shrapnel Cannon is a great example: the Tracer is fired at the same time as the real munitions, but the top-level weapon is itself a fake munition (velocity 1, lifetime 0/1, no sprite). You absolutely had to have the top-level weapon be a fake munition with that design – it's very similar to one of the two weapons I've been struggling with, which is a cone-shaped [Death Ray](http://tvtropes.org/pmwiki/pmwiki.php/Main/DeathRay) /  [Wave Motion Gun](http://tvtropes.org/pmwiki/pmwiki.php/Main/WaveMotionGun).

If you fire your Shrapnel Cannon while an enemy is right on top of the weapon, they'll eat all 1200 damage without a hit effect. I just tried it out. It doesn't happen too often with the Shrapnel Cannon, but a few other fancy weapons have the problem more. I haven't found a way around it yet, hence toying with the idea of begging for a "no collision" attribute.

**Comment by Amazinite** [comment]
> without a hit effect

That's a simple fix, really. All I'd need to do is put a hit effect on that 1 frame original shot.

**Comment by Elyssaen** [comment]
Yeah, that's probably all it takes for the Shrapnel Cannon. I think I've got a few situations where I don't really want the fake starting munition to be able to collide though, for... reasons. I'll review it, and if I still think "no collision" would be useful I'll raise another issue / make a pull request for it.

**Comment by Elyssaen** [comment]
@Amazinite, I was meaning to ask: how's **323.75** for the calculated range of your Shrapnel Cannon? The tracer workaround you used gives it a range of 200, but my code calculates more on the basis of:

Shrapnel Cannon = 1 Velocity x 0 Lifetime = 0 Range
Shrapnel = (10+1) Velocity x 5 Lifetime = 55 Range
Shrapnel Pellets = (15+5/2+1) Velocity x (1+5/2) Lifetime = 323.75 Range

Shrapnel Cannon + max(Shrapnel,Shrapnel Pellets) = 323.75 Range

I feel like this is the 'right' answer, but it's very different to the range you picked. If I made a pull request for my change to the range calculation, would you still want to override the range to 200 in your plug-in? If so this perhaps make the case that a range override option could even be better than a 'better' range calculation. Or both could be the best solution.

**Comment by Amazinite** [comment]
It would be interesting to have an override of sort so that you could get the NPCs to fire weapons when well within their possible range state. Maybe call it "optimal range" and make that the range at which the NPCs try and fire from, because trying to fire a shotgun at the farthest range possible (324 in this case) isn't going to be very effective.

**Comment by Elyssaen** [comment]
Agreed. Well, I've written code for that too, and can just combine the two together. Do I try to get more feedback here or move on to create a pull request? I don't want to be hasty, but I'm also quite happy to proceed quickly.

(Just a point: 323.75 isn't the farthest range possible, that would be 420. 323.75 uses the half-way values of velocity and lifetime. Still, I can well believe that the weapon is more effective when fired at 200, particularly because of the inaccuracy. I've also been playing about with some non-homing turn and highly inaccurate weapons that are even more in need of an "optimal range" as you put it, even _with_ my range calculation tweak.)

**Comment by Amazinite** [comment]
Well if you already have the code for it done, I think it would make sense to pull the change. Feedback from more people would then likely end up happening over there.
