### ISSUE TITLE
Error while building Endless-Sky on OSX

### ISSUE THREAD

**Issue by sjud** [endless-sky/endless-sky#1827]
The error is:

`source/ImageBuffer.cpp:235:27: error: use of undeclared identifier
      'JCS_EXT_BGRA'
                cinfo.out_color_space = JCS_EXT_BGRA;`

My operating system is Mac OSX El Capitan 10.11.6
What I am trying to do is build it from source using the most recent clone from Github.
I've installed all of the required libraries.

The context of the error is after I use scons in a python2.7 virtual environment it runs through the source files compiling them, until it gets to ImageBuffer.cpp and generates the above error.

Thank you.

**Comment by Pointedstick** [comment]
Are you sure you installed the correct libraries? I hit this too, and needed to install the exact very specific specified version of `libjpegturbo`. You can't install the latest one; it has to be the exact one specified in the compilation instructions.

**Comment by sjud** [comment]
Hmm. I thought I did, but I'll reinstall them and let you know if that works. Thanks.

**Comment by LocalGod79** [comment]
indeed - i did not have an issue compiling the latest build under 10.10.5...

those code references are definitely to JPEG libraries, so as @Pointedstick mentioned, your TurboJPEG library is probably incorrectly installed (either version or location)...

**Comment by sjud** [comment]
Thank you Pointedstick & LocalGod79.

The location was incorrect for the TurboJPEG header files, after I moved them into the appropriate include folder Scons compiled imagebuffer.cpp.

Although now I am getting a new error, I will share it with you in case your willing to point me in the right direction.

```
***build/release/everything.o*** 
build/release/UI.o
build/release/Weapon.o 
build/release/WrappedText.o 
build/release/main.o 
-lSDL2 -lpng -ljpeg -lGL -lGLEW -lopenal -lpthread
ld: library not found for -lGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [endless-sky] Error 1
```

I have the openGL framework in my /System/Library/Frameworks folder and Xcode is updated to the most recent version. I think Scons may not be linking properly because it can't find the appropriate libraries, so I'm currently reading to understand how to edit it's library search path.

Thanks.

**Comment by LocalGod79** [comment]
i'm currently using Xcode 6.4 (which will not function under Sierra) in Yosemite, and i believe M.Z. is using 5...i don't know anything about the changes Apple has made to it in the meantime...

**Comment by Wrzlprnft** [comment]
(to be added right at the end of localgod's comment) ... Because it evolved more into a personal help thread than a official issue.

;)

**Comment by endless-sky** [comment]
The SConscript is really just designed for Linux, and hasn't been tested on other operating systems; if you're compiling on Mac OS X you should just build it in XCode.

**Comment by sjud** [comment]
I built successfully in Xcode.
For posterity incase any other newbs experience the same issue and search in the issues section.
It was throwing the error `ld: framework not found SDL2.framework`
I copied SDL2.framework from /system/library/frameworks and placed a copy in /library/frameworks and it ran fine.
Thanks Endless-Sky and everyone else who offered their advice.
