### ISSUE TITLE
Pug systems can become friendly before completion of storyline

### ISSUE THREAD

**Issue by atyates** [endless-sky/endless-sky#1828]
Made a new account, wanted to capture as many pug ships as possible so I never finalized the end of Freeworlds campaign - for a long time I simply captured pug ships.  Then I figured I would try to conquer the Pug homeworld in Wanderer space, so I proceeded to start harvesting pirates and extremists - stopping infrequently to capture autonomous Korath ships.

Push comes to shove, I'm trying to capture some more Korath ships today (probably like 200 hours on this play through) and I notice that the Pug planets are friendly - but I still haven't finished the Pug storyline - something I don't believe should be possible.

**Comment by KiLEdEnNis** [comment]
they have a negative attitude towards pirates, so that explains it
but I think there should be some option that permanently makes a government have a negative attitude towards the player until a mission changes that (to avoid this)

**Comment by Amazinite** [comment]
Well the Pug start out friendly, become hostile during the campaign, then return to being friendly. Maybe during the length of the Pug part of the campaign they shouldn't have an attitude toward governments not involved in fighting.

**Comment by KiLEdEnNis** [comment]
if you are at war with them, they should get a "tag" that makes them always hostile, until the war ends, & then the tag gets removed

**Comment by Bladewood** [comment]
I believe that the Pug are neutral towards anyone that is not actively trying to kill them, or is not part of their plans in the war.

A repeating mission that triggers every time your reputation with a government falls below (or above) a certain threshold, changing your reputation with the government to a specified value, would work miracles.

**Comment by Amazinite** [comment]
@KiLEdEnNis #1322

**Comment by KiLEdEnNis** [comment]
@Amazinite yeah, that one (thanks)
& what @Bladewood said; having an event trigger when reputation = 0 or higher that sets government back to -1000 could be useful (but you can't "stop" it, so the government can't be friendly)

**Comment by Bladewood** [comment]
I dunno... we could have a faction where you are capped out at 1 or something, and you instantly become their enemy if you slay one of their ships, no matter how much you've helped them in the past.

**Comment by KiLEdEnNis** [comment]
basically, reputation borders
[government]
   reputation x
      boundaries -1000 < x < -1

so reputation will always be between -1000 & -1 (always hostile)
could also open some possibilities for designers

**Comment by tehhowch** [comment]
A simple way to do this would be to alter the government attitudes at the start and end of the pug invasion, from their values of `+.1` & `-.1` to `+.01` and `-.01` (and then back). This would prevent the player from gaining favor with the Pug through any means whilst at war.

**Comment by Amazinite** [comment]
Looks like this was handled some time ago. c3b9e15
