### ISSUE TITLE
[bug/mechanics] Unappreciated* outfits cannot be bought if you do not have the money for the original price

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1829]
*Yes, I know that was a bad joke.

http://steamcommunity.com/sharedfiles/filedetails/?id=803547559

As you can see, I have 15m credits, the cost of the reactor is 5m, but I can't buy it, because I don't have the 20m needed for the original cost. I had to sell other stuff on my ship, buy the reactor, and then repurchase the other stuff to get the reactor on my ship.

**Comment by Amazinite** [comment]
When did you last compile?
#1743

**Comment by toilethinges** [comment]
A while back. Whoops, I never saw that commit. Better recompile...
