### ISSUE TITLE
escorts don't follow after refuelling while trailing [bug]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1831]
e.g. departing from Longjump to Sol doing FW diplomacy, my five Skeins (with Scram Drives) stop to refuel at New Boston, but remain in Rutilicus (with full fuel) until i return to the system to retrieve them.

https://drive.google.com/file/d/0B92_vuqiHabWcmJkWWh2Mi1Fa0U/view?usp=sharing

i believe this link is for a save file demonstrating the bug within the latest build...

**Comment by Bladewood** [comment]
I've experienced this a *lot* today...

**Comment by endless-sky** [comment]
This looks like an unintended consequence of the fix for #1682 / #1684. Commit 23be8e7 should fix this.
