### ISSUE TITLE
[Content] Pug Outfit Concepts

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#1834]
As per: https://endless-sky.github.io/2016/11/21/easy-ways-to-get-involved.html
Would like comments/feedback before coloring/post. If people dig it I'll do a turret as well.

![zapper](https://cloud.githubusercontent.com/assets/22107649/20536504/61a34c2c-b0b7-11e6-9866-1eb0ce23c321.jpg)
![zapper2](https://cloud.githubusercontent.com/assets/22107649/20536507/65d15bcc-b0b7-11e6-8e7e-d2405ef492a5.jpg)
![zapper3](https://cloud.githubusercontent.com/assets/22107649/20536517/67cec5b8-b0b7-11e6-8ec8-6af5d6f08a23.jpg)
![zapper4](https://cloud.githubusercontent.com/assets/22107649/20536521/6a07a976-b0b7-11e6-85d6-c0ad764a8e6a.jpg)

**Comment by Wrzlprnft** [comment]
I like the look of it :)
Though, you have to test the shadow ond size because you may loose some of the visual appeal.

**Comment by jafdy** [comment]
I think it is a bit bigger than would look sensible as a pair on a turret. Other than that it looks nice.

**Comment by comnom** [comment]
> I think it is a bit bigger than would look sensible as a pair on a turret. Other than that it looks nice.

That's fair. Looking at the turret stats it should be a dual-mount rather than just a single too. Maybe I can narrow it up without having to lop off the sides.

**Comment by comnom** [comment]
Na didn't play nice so I chopped off the sides and added a little extra detail to the ring to make up for it. Better/worse? Figure I can angle the pair outward a bit to make the turret more interesting.

![zapper_noside](https://cloud.githubusercontent.com/assets/22107649/20539192/25365850-b0c2-11e6-84ec-017f61ae359c.jpg)
![zapper_noside1](https://cloud.githubusercontent.com/assets/22107649/20539196/2850570c-b0c2-11e6-9732-0583b135d7ef.jpg)

**Comment by Amazinite** [comment]
Looks awesome. I guess you'll try and make the other Pug outfits as well? e.g. Seeker, engines, etc.

**Comment by Bladewood** [comment]
It doesn't seem organic enough to me.

**Comment by Amazinite** [comment]
Well I wouldn't consider the Pug ships organic...

**Comment by comnom** [comment]
> Looks awesome. I guess you'll try and make the other Pug outfits as well? e.g. Seeker, engines, etc.

Dunno yet, if the dev greenlights this one I may take a crack at it. I tried to keep the design a little "loose" (read: generalized) so if someone else wants to jump in it shouldn't be that hard.

> It doesn't seem organic enough to me.

I guess you mean the "roundness" of the Pug ships? I thought about it but a round barrelled gun seemed a little bland is all, so I mixed in some sharper edges with round detail. That style may fit well with engines however.

**Comment by jafdy** [comment]
If you want you can have the gun version lying flat and then have a pair in this orientation on a turret mount. Looks great by the way.

**Comment by Elyssaen** [comment]
Really love this.

Are people's attitudes about gun vs. turret design really conservative? For me, keeping to "a double turret must be two distinct guns next to one another" isn't a necessary constraint. Moving away from that in some considered cases might do more to mark technology as alien than making it very typically 'organic'-looking.

What got me thinking about this is I like both your prototypes, and personally could imagine this:

1. The gun is the second version.
2. The turret is the first (once on a track), so it doubles up by having double the _side prongs_. I'd then elongate the cube or something to suggest a larger internal. The central prong would be the same for the gun and the turret, suggesting it serves more to focus/direct the energy from the side prongs and so didn't need to be doubled up in the turret.

**Comment by comnom** [comment]
@Elyssaen It seems conservative but we're really just all fairly new at this. The tonnage also is indicative of a dual mount. That said I dig the idea, but failed utterly in implementing it. (couldn't get it to mount right)

I appreciate the feedback folks, it's tough jumping into someone else's content like this with little direction and you guys helped alot. The PR is up so we'll see how it goes.

**Comment by Elyssaen** [comment]
Fair enough! What you've done is brilliant, especially as I really don't think it can be easy to do convincingly alien tech.

**Comment by Bladewood** [comment]
It might seem strange, but this was the first thing that came into my head when I tried to think about "non-conservative turret designs":
![nonconservative turrets](https://cloud.githubusercontent.com/assets/16506683/20575118/e72a8d3c-b185-11e6-94e2-e4a741115c82.png)

**Comment by endless-sky** [comment]
That looks really cool and menacing! I like that the design matches the aesthetic of the Pug ships. If you're able to come up with a whole suite of these for the Pug outfits (so they all have a similar aesthetic), that would be awesome. (And, if you just want to do the modeling and have someone else do the rendering and post-processing, I'm sure that would work too.)

I'd be on board with the gun being the three-pronged version and the turret being the five-pronged original.

It's never really explained in game whether the Pug ships are literally organic, or just have lots of curvy and spiky shapes. For example, maybe their hulls are made of something like [nacre](https://en.wikipedia.org/wiki/Nacre), i.e. a strong and somewhat flexible half-organic, half-inorganic material. That doesn't necessarily mean that the ships themselves are "alive" or biological.

**Comment by Wrzlprnft** [comment]
I once tries a very basic pug thruster https://groups.google.com/forum/m/#!search/pug$20thruster/endless-sky/_tC3QC1PH54
I'd love to hand over the models to @comnom to see what he can do with it.

**Comment by comnom** [comment]
> That looks really cool and menacing! I like that the design matches the aesthetic of the Pug ships. If you're able to come up with a whole suite of these for the Pug outfits (so they all have a similar aesthetic), that would be awesome.

Thanks! Yea why not I'll have a go at it, trying match the design of the Pug ships was a nice little test, and more practice won't hurt.

> I'd be on board with the gun being the three-pronged version and the turret being the five-pronged original.

I'll make another attempt at the turret then, since I like the idea as well, and actually prefer the big one anyways.

@Wrzlprnft I'll check that out when I've got a chance, busy today but you can attach 'em here. I'll be changing the title to pug sprites when I can, and use this issue as a working thread for all of it, since I like the input while working on the dev's aliens.

**Comment by KiLEdEnNis** [comment]
maybe Pug ships are like thick alien jello?

**Comment by gunqqer** [comment]
Thick alien jello. 

I want jello now.

On the topic of what Pugs ships are, I think of them like the Wraith ships in SG:A, they are grown like plants using power and still lives after putting thrusters in it.

**Comment by Bladewood** [comment]
Sentient evil killer space plant faction from Reassembly.

**Comment by KiLEdEnNis** [comment]
ships carved out from piles of alien pudding works for me

**Comment by comnom** [comment]
Alright, I've got a single turret I'm fairly satisfied with, so state your preference folks. (The dual-mount is in the PR)

![singleturret](https://cloud.githubusercontent.com/assets/22107649/20641608/7fe0ae36-b3c9-11e6-8386-b86b809b0312.jpg)

**Comment by jafdy** [comment]
Lets vote.
On this post:
Thumbs up for New version.
Thumbs down for Old version.

**Comment by Lineth** [comment]
Five-prong version of the new turret would be best. Looks amazing!

**Comment by Bladewood** [comment]
It looks cool, but the turret has double the stats of a gun, so would it not make sense for it to be a pair of three-pronged zappers?

**Comment by Amazinite** [comment]
Well this version has some extra stuff at the base of the gun. You could say it's an amplifier of some sort, meaning that you wouldn't need two guns.

**Comment by KiLEdEnNis** [comment]
plus, double guns mounted on turrets is ok, but this kind of option shouldn't be ignored

**Comment by Admiral-Danforth** [comment]
The little squares on the "neck" do not match the rest of it.

**Comment by comnom** [comment]
> The little squares on the "neck" do not match the rest of it.

Agreed, in fact most of it doesn't match. Back mounting it was a huge pain but I couldn't come up with a way to side mount it with the prongs in the way. I likely won't even try to salvage it. It's too front heavy, I'm not really a fan of the big ring, so on and so forth.

**Comment by KiLEdEnNis** [comment]
my main problem is that the base is kinda boring & empty, I don't mind the squares
