### ISSUE TITLE
Osprey gets stuck in Lesath on rescue-freighter mission

### ISSUE THREAD

**Issue by MichelleTaylorRG** [endless-sky/endless-sky#1836]
I have a four-ship fleet - Blackbird, Bastion, Osprey, Clipper - and am on the Free Worlds mission to rescue a freight from Lesath.

When I enter the Lesath system, the Osprey immediately picks a direction and starts flying in that direction, not responding to any further orders or following the fleet on jumps.

Attached are two snapshots - 'RogueOsprey' is a snapshot with the Osprey flight in action, 'BeforeLesath' is a snapshot from just before I head to Lesath (recovered by using the 'previous' saves). The issue repeats for me every time I go to Lesath from the BeforeLesath snapshot.

[Juniper Wishberry~BeforeLesath.txt](https://github.com/endless-sky/endless-sky/files/609034/Juniper.Wishberry.BeforeLesath.txt)
[Juniper Wishberry~RogueOsprey.txt](https://github.com/endless-sky/endless-sky/files/609035/Juniper.Wishberry.RogueOsprey.txt)

**Comment by warp-core** [comment]
The problem is that the Osprey has no reactor, only a battery and so cannot generate any energy. It is entirely reliant on the energy stored in its battery from take off but this gets used up by the time you reach Lesath and so it is unable to do anything.

**Comment by KiLEdEnNis** [comment]
maybe having a ship w/o energy generation show a "warning" when leaving the outfitter (to remind the player they have a battery ship and what can go wrong)

**Comment by Bladewood** [comment]
@KiLEdEnNis hey, wasn't there an issue like this before...?

**Comment by KiLEdEnNis** [comment]
@Bladewood there was one about someone complaining about "battery ships", not sure if he suggested an actual warning pop-up

**Comment by toilethinges** [comment]
#1813

**Comment by The-Borg-Captain** [comment]
As far as a warning for battery only ships, most drones fall into that category

**Comment by Amazinite** [comment]
>most drones fall into that category

What?

**Comment by KiLEdEnNis** [comment]
as far as I remember, every drone/fighter has energy generation from outfits, so what are you even saying? because it ain't right

**Comment by The-Borg-Captain** [comment]
Yeah Your right, I'm not sure what I was thinking

**Comment by DingusShingleton** [comment]
Another data point in the "heat stat display is unintuitive" debate. I wonder how many other people are running their ships with 10s of tons of unnecessary cooling

**Comment by KiLEdEnNis** [comment]
a small pop-up tutorial might help new players
- buy ship
- get redirected to outfitter
- text box explains ship stats
- clicking the screen makes the next text box appear & the previous disappear
basically a small powerpoint tutorial, & a "skip" button could help
