### ISSUE TITLE
Reverse Thrusters not being used properly for multiple warp jumps

### ISSUE THREAD

**Issue by stephenross** [endless-sky/endless-sky#1838]
I only have the standard hyperdrive, but I purchased some reverse atomic thrusters for my fleet and noticed that when using some of the stronger forward thrusters that my ship would flip around and slow down that way instead of using the shiny reverse thrusters, but the issue was that it was slower to brake that way and orient properly for a warp jump than it was to use the reverse thrusters. I think that whatever is calculating the time to slow down for both methods is not taking into account the turning time to complete the 180 before breaking begins as I was able to have 2 identical ships set to auto jump and was able to manually stop my flagship and jump before the other was ready because of this flip and stop.

**Comment by Amazinite** [comment]
A bunch of issues on reverse thrusters have been closed before. e.g. #1583

**Comment by stephenross** [comment]
Thanks for the note, though I believe the issue is still valid. I will take a look at the math used on my own and submit a PR if I find something usable.

**Comment by Amazinite** [comment]
I get what you mean, it just seems like it isn't something that MZ want's to work on, given that all of the previous issues on reverse thrusters have been closed by him.
