### ISSUE TITLE
Outfit Space change

### ISSUE THREAD

**Issue by stephenross** [endless-sky/endless-sky#1839]
While looking at some of the items that are available to purchase, I noticed that there are a large number of items that would certainly be internal only (reactors and batteries and whatnot), or would take up some of that space (engines for example), but there are others that would likely reside entirely on the exterior hull like the solar panels and the ramscoop. I understand that it would likely be an enormous undertaking for both change and balance, but I think it might be useful to split up outfit space into interior and exterior, and modify the available outfits accordingly, with only a small number such as engines requiring both types of space (though that seems to already be through the engine capacity for their exterior). This would also be something that would need balance with the hull designs as some might have very little usable outer surface because of lots of small fins or might have tons because of large bulbous or flat sections.

**Comment by Bladewood** [comment]
We've discussed this so many times before...

**Comment by stephenross** [comment]
I just got the game and did not see this mentioned on any of the open requests

**Comment by Amazinite** [comment]
@Bladewood When?

**Comment by Bladewood** [comment]
...oh, I see, I was misreading the issue. I thought it would be something related to boarding...
I'm an idiot.

I think this would add too much complexity.

**Comment by jafdy** [comment]
@Bladewood is probably right. I think this is a moment where you go for game play over realism.

**Comment by KiLEdEnNis** [comment]
@jafdy it might not be unrealistic at all
who says ramscoops, solar panels etc. aren't partially exterior? the outfit space part could be the interior part
the only issue I see is that it may not be worth mentioning to the players

**Comment by endless-sky** [comment]
The capacity limits on ships are really designed for balancing purposes, not realism.

I don't think that making a change like this would make the game more fun to play - if anything, it'd make outfitting a ship a whole lot harder because you have another capacity dimension to worry about.

**Comment by whismerhill** [comment]
I think the main issue with that, is not even about making it harder for players: since depending on player it could be desirable or not.
The main issue is that balancing the ships will have to be redone, that's yet another variable to take into account, seems too much work for too little benefit. One could simplify the workload by using formulaes to convert outfit space into "external outfit space" & "internal outfit space", but then it kinda makes no sense to have both if it's gonna be a purely mathematical split. e.g. it won't add much flavor to the game.

Just my opinion

**Comment by KiLEdEnNis** [comment]
if you have an internal and external border, you have another constraint, and a lot of players would get frustrated and/or confused
keep in mind that it's a free game, both adults and even 12-year-olds play the game, it should be fun for everyone and it shouldn't be made harder to add a little bit of realism
