### ISSUE TITLE
 [build/Files.o] scons: building terminated because of errors. 

### ISSUE THREAD

**Issue by krysopath** [endless-sky/endless-sky#184]
>0 ✓ g@toolbox ~/random/endless-sky $ scons
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>g++ -o build/Files.o -c -std=c++0x -O3 -Wall source/Files.cpp
>source/Files.cpp: In static member function 'static std::string Files::Read(const string&)':
>source/Files.cpp:457:9: error: 'result' was not declared in this scope
>  return result;
>         ^
>source/Files.cpp:458:1: warning: control reaches end of non-void function [-Wreturn-type]
> }
> ^
>scons: *** [build/Files.o] Error 1
>scons: building terminated because of errors.
>2 ✗ g@toolbox ~/random/endless-sky $ echo $?
>2
>0 ✓ g@toolbox ~/random/endless-sky $

I met this error on debian/jessie and have no idea how to proceed from here. Can you help me with some good advice?

All required dependencies are met IMHO

**Comment by endless-sky** [comment]
Just do a new git pull. Commit cabb240 fixes that.

**Comment by krysopath** [comment]
aye, thank you for your advice. which is the best way to help out in this project?
[closing]

**Comment by endless-sky** [comment]
Well, bug reports are definitely helpful. :) Beyond that, you can look at the "help wanted" page:

https://github.com/endless-sky/endless-sky/wiki/HelpWanted

**Comment by krysopath** [comment]
On Tue, 10 Nov 2015 19:59:16 -0800
Endless Sky <notifications@github.com> wrote:

> Well, bug reports are definitely helpful. :) Beyond that, you can look at the "help wanted" page:
> 
> https://github.com/endless-sky/endless-sky/wiki/HelpWanted
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/endless-sky/endless-sky/issues/184#issuecomment-155655009

Actually, I might synthesize some sound fx. The current ones
hurt my ears :>






-- 
krysopath <krysopath@gmail.com>
gpg: 0x924B410DD7A4891D
