### ISSUE TITLE
App hooks for scripting with Python (or similar) scripting

### ISSUE THREAD

**Issue by quantumandan** [endless-sky/endless-sky#1841]
Hi guys, I grew up with Escape Velocity/EVN and have been following the progress and awesome community from afar, but this game is too good not to chime in. 

I love the idea of plugins, and like the old EV games, being an AI guy, would love to inject some magic into the NPCs/turrents/etc, but most of my tools are in python* and tensorflow. Is there any support in the group for an FFI or some kind of hook for languages other than ObjC**?

* I fully acknowledge my bias in favor of python
** ObjC is pretty popular and well known, but for non-performance critical pieces, being able to script in a dynamic language might open up the project to a much wider audience.

**Comment by Wrzlprnft** [comment]
At the moment there is no support.
The idea to have interchangeable ai is quite appealing, but i'd guess at the moment it is too much effort for @endless-sky

It really sounds like a post 1.0.0 finetuning to make the game shine even more :)

What you could do is to look at the game's existing ai behaviour and a) either make suggestions or b) try to figure out whcih patterns the game uses and where a script would have to kick in to provide a base for the following work.

**Comment by endless-sky** [comment]
My concern with scripting languages is that they present a much higher "barrier to entry" for content creators. And once you start relying on scripting for some aspects of the game, it's easy for there to suddenly be more and more things that can *only* be done by scripting.

Also, the task of providing hooks for an AI to look up all the aspects of the current game state would be a lot of work, and that effort could probably be better invested in just improving the in-game AI.

My long-term plan for AI customization is to have a broader range of ship [personalities](https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities) (like the surveillance personality, or the plundering personality) that can be used to customize the behavior of a given NPC. That would give a lot more control over ship behavior without relying on content creators to be able to make AI code in a scripted language run fast enough to not slow things down when there are lots of ships in-system.
