### ISSUE TITLE
Make it so a "person" be a fleet instead of just 1 ship

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1843]

**Comment by endless-sky** [comment]
At the moment, no. But it wouldn't be too hard to change.

**Comment by endless-sky** [comment]
The one complication to this would be how the game would handle it if part of the fleet is destroyed but not the rest: have that "person" continue to show up, but without their full fleet? Pick a new flagship if necessary? Or, have a rule that a "person" stops showing up if any of their ships are destroyed?

**Comment by jafdy** [comment]
Have the "person" continue to show but with the reduced fleet. Maybe add an attribute where the person is only destroyed if the entire fleet is. Or have fighters always come back.

**Comment by toilethinges** [comment]
@jafdy I can just see the massive carrier with regenerating fighters...

**Comment by Wrzlprnft** [comment]
I'd differentiate between two type of person fleets:
A person with a fleet and a fleet as a person.
While a person with a fleet should have a flagship declared and disappear once the flagship is killed, but always show up in the same strength (imagine a pirate gang based around a captain who's filling up the losses), a fleet as person may have flagships, but they reappear.(think of a pirate gang based around a name/myth). Those fleet-as-persons should have other criterias declared like: all ships killed, all ships killed x times, certain conditions met,whatever.

**Comment by Hyratel** [comment]
per WRZ's comment, the change would allow for missions such as
"Bring [NAME] and escorts to [PLANET]" where the flagship is squishy and delicate
or
"bring the [NAMED FLEET] to [planet]

**Comment by jafdy** [comment]
@Hyratel That's creating a mission with a fleet of NPCs. We are talking about persons of the kind that appears in person.txt

**Comment by endless-sky** [comment]
I've implemented this in 1d8c52f.

**Comment by jafdy** [comment]
Just less than a year later, awesome.

**Comment by KiLEdEnNis** [comment]
(just in time for @Amazinite & @tehhowch *hint hint*)
