### ISSUE TITLE
New hotkey: Toggle escort ammo behavior

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#1844]
When I outfit my escorts with missiles, I find that I often want to switch how they use ammo on the fly, to better adapt to a changing battlefield. I know there is reluctance to add new hotkeys, but hear me out. 

For example, I'm hanging out in a system killing pirates, perhaps light warships and smaller, and my escorts are set to use their ammo frugally. All of a sudden, a pirate leviathan warps in. All hands on deck! Time to switch to "always", boys, now is not the time for frugality. Then, having beaten the vile leviathan, I resume my parsimonious usage of expensive ordnance.

These two simple switches require entering the top level menu twice, and a combined total of 11 clicks/button presses. A single hotkey that toggles through "Never", "Frugal", and "Always" would be a great QoL upgrade for folks who want to make use of missiles or rockets (which as I understand it most people do not, so every little bit helps imo).

In fact, this change could entail simply moving this setting up to the "Fleet" section of the menu. I suggest "O" as the default binding, to signify "Escort Ordnance Usage". This way, it removes a passive setting that people might not understand or forget about and replaces it with an interactive one that could say something like "Escorts will now [never, frugally, always] expend their ammo" when pressed.

**Comment by endless-sky** [comment]
I feel like U for "toggle ammo Usage" might make more sense, since the game never refers to ammo as "ordinance."

**Comment by endless-sky** [comment]
Added in commit d6b7c83.

**Comment by DingusShingleton** [comment]
Oh. That's.... a much better option lol. 

Anyway, this is awesome, thanks!
