### ISSUE TITLE
Massive CPU usage occurring while in flight

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1845]
I just compiled the game for the first time in a few weeks and now Endless Sky is running up near and over 100% CPU according to the in game CPU/GPU display. It use to stay under 10% at almost all times, save for large battles. This also appears to only occur while in flight. Sitting on a planet and going through the menus or even opening up the info menu or map while in flight returns the CPU to normal.

In flight (at 107% in game, 30% on task manager)
![high cpu](https://cloud.githubusercontent.com/assets/17688683/20634522/2a8c62b2-b320-11e6-99dd-f93f1186188c.png)

In info menu (game display doesn't update but dropped to 89% before stopping, dropped to 3.5% on task manager)
![info menu](https://cloud.githubusercontent.com/assets/17688683/20634602/9b0cb3e8-b320-11e6-9e54-b32b5621209e.png)

So now even small battles cause serious slow down.

**Comment by endless-sky** [comment]
Is it possible you're running a debug build? Or, that you have a large fleet or lots of escorts trying to pathfind to you? On my computer in flight CPU usage is around 3%, in routine use.

**Comment by Bladewood** [comment]
Same as always on my side, only lagging in big battles against the Navy.
Firebird, no fleet ships, non-debug build.

**Comment by Amazinite** [comment]
It's only my Derecho (as seen from the ship list and no other ships shown in the corner) and I don't even know how to run in debug mode so no.

**Comment by Amazinite** [comment]
It looks like this is save-specific. One of my saves goes over 100%, while another is going over 200%, but when I make a new pilot it's working normal.

**Comment by Amazinite** [comment]
[One of the offending saves.](https://github.com/endless-sky/endless-sky/files/613940/Enigmac.txt)
I do have a bunch of plugins on, but removing them didn't make any difference.

**Comment by Amazinite** [comment]
Nvm, I think I found it. Just need to test this.

**Comment by Amazinite** [comment]
Yup, don't mind me. It just looks like someone's bug in their own plugin was causing massive slow down the longer a save existed.

**Comment by KiLEdEnNis** [comment]
probably one of the updates caused it
