### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1846]
I was looking for some assets to work off of, but I couldn't find them, and eventually noticed that quite a few are missing.

Pond Strider
Flea
Gatling Gun + ammunition and effects 
Railgun + ammunition and effects

These are all from the same PR (I think), so if there's anything else that was pulled in at the same time as the rest of those, it's probably missing as well.

**Comment by Amazinite** [comment]
Also, the "hai arachnid" and "hai mite" blend and xcf files should probably be renamed to "hai solifuge" and "hai violin spider".

**Comment by Amazinite** [comment]
I busted my way into Local's google drive, but I didn't find everything.
[Missing Assets.zip](https://github.com/endless-sky/endless-sky/files/614280/Missing.Assets.zip)

**Comment by endless-sky** [comment]
I was able to track down most of the rest. The only things I'm missing now are:
* The .xcf for the railgun.
* The .xcf and the .blend (if there is one) for the railgun slug.

**Comment by Amazinite** [comment]
I have the icon .xcfs on hand.

**Comment by Bladewood** [comment]
There does not appear to be a `jump drive.blend`, it seems?

**Comment by LocalGod79** [comment]
hmmmm...@Wrzlprnft should have the xcf for the Gatling Gun, and @smestead should have the Rail Gun and Slug xcfs...

**Comment by Wrzlprnft** [comment]
@localgod79 just the icons for the gatling gun. which derpy provided.

**Comment by LocalGod79** [comment]
i think (excepting the Pond Strider), most of the art was created by others for that that pull (#1284), and i was just provided the @2x sprites (which is why most of the .blends and .xcfs are not in my Google Drive)

from what i'm reading, M.Z. is still missing the .xcf for the Rail Gun and Rail Gun Slug - i'll resurrect the email, and remind Matthew...

**Comment by LocalGod79** [comment]
just forwarded Matt's response to my necro'd email thread - M.Z. should have the Rail Gun xcf up soon.  i think the slug may have been a straight up render/resize of the .blend...

**Comment by endless-sky** [comment]
I've uploaded outfit image source files for the jump drive and the railgun slug. That should be the very last of what was missing.
