### ISSUE TITLE
Post-depreciation: Progression in FW campaign is much slower

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1848]
After the depreciation commit, progression became MUCH slower.
In the FW campaign, by the time I unlocked dreadnoughts, I was still piloting a firebird, and I still only had a net worth of about 11 million credits, which is not nearly enough for a dreadnought.
I'm usually in something better than an Osprey by that point.
(I'm partially relying on plundering to earn my funds, of course.)
The most obvious solution that I can see is to increase monetary rewards from missions.

**Comment by endless-sky** [comment]
It's possible the campaign will need some rebalancing to account for the slower progression. Right now it assumes that by the time you're battling the Pug, you're in a capital ship whose un-depreciated price is at least 20M.

But, slowing down the progression is the whole point of depreciation: in my opinion, the most enjoyable part of the game is when you're growing powerful enough that you don't have to just run away from every battle, but you're still weak enough that you need to choose your battles carefully.

**Comment by KiLEdEnNis** [comment]
increasing bounty hunting missions (or maybe even adding missions where you have to capture a ship & get a huge reward) could even it out?

**Comment by retrue** [comment]
Other sources of income in the future like: mining, more types of transport of passengers like massive transport of passengers, de luxe transport or express transport of passengers and goods.

**Comment by MessyMix** [comment]
@KiLEdEnNis bounty hunting is primary income for a lot of post-endgame players, so that would just make the post-endgame even more godmode. I think another buff would be more viable than a bounty hunting reward increases :P

**Comment by KiLEdEnNis** [comment]
@MessyMix ah, just mentioned them because those are the only missions I take (all at once) & when I happen to see a fleet I wipe it & when I land on the planet again & get money
how about adding "important cargo" missions? (stuff people would only let a trusted person transport, and since you are a war hero they ask you)

**Comment by srkunze** [comment]
@KiLEdEnNis I like the "important cargo" mission idea (even though I wouldn't take it since I only do trading as the primary source of income - everything else feels inefficient once a certain cargo volume is reached).

**Comment by retrue** [comment]
For me, the 'important cargo' missions should always go with pirate attacks all the way until destination was reached and the cargo delibered.

**Comment by KiLEdEnNis** [comment]
so "thrilling" dangerous "important cargo" delivery missions
could also be "transport [VIP] to [planet]" (the human equivalent)
