### ISSUE TITLE
AI boarders will steal hand to hand outfits

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#185]
It seems odd that the AI can steal these things when the player can't.  Doesn't matter much though, since being boarded generally means it's time to reload from save anyway.
http://i.imgur.com/k1K4yCv.png

I got the intrusion countermeasures by capturing a previous raider with nerve gas and substantial casualties.  When boarding a raider, the intrusion countermeasures don't show up in the list of things to steal.

**Comment by johndh** [comment]
It looks like they also stole your mass expansions.  I don't know if that's the intended behavior or not, as I'm not sure what they really are, lore-wise.

**Comment by PhoenixRiver** [comment]
Stealing of Mass and Cargo expansions could cause interesting situations if they don't also steal enough outfits/cargo... however 0.8.7 removed stealing of outfits which solves this problem (Mass and Cargo expansions being outfits :)

**Comment by endless-sky** [comment]
As of 0.8.7 the AI just never steals any outfits at all (because way too many players were confused by that), so this issue is "fixed."
