### ISSUE TITLE
Depreciation is unstable in some situations.

### ISSUE THREAD

**Issue by Isaacssv552** [endless-sky/endless-sky#1850]
I recently created a variant of the old cheater plugin which includes all alien and plugin ship/outfits as well. However, when I created a new pilot the depreciation was fluctuating wildly. Not only did this make it hard to tell how much outfits were worth, when I sold an outfit my credit level would sometimes drop to an extremely large (e18) negative number.

**Comment by endless-sky** [comment]
Can you post the plugin and saved game?

**Comment by Isaacssv552** [comment]
https://github.com/Isaacssv552/endless-sky-plugins has the relevant plugin ("Experimental"). The issue occurred on a freshly started new game, I haven't tested any of my save files yet. The removal of the alien outfits/ships from New Boston seemed to help, but I haven't finished testing that yet.

**Comment by Isaacssv552** [comment]
The problem still exists even after limiting New Boston to just the human outfits, just the wanderer outfits, etc. However it disappears when I run in debug mode directly from XCode. Testing on a clean save in debug mode resolves the bugs listed above but causes a new one. When transferring outfits into and out of stock the price is only correct for selling. When selling the depreciation is applied properly, when buying it is not applied at all. Also, when loading a save without depreciation data the depreciation level is either set to 25% or over 100%. The highest I've seen was over 1000%.

**Comment by Amazinite** [comment]
Could this be related to #1775?

**Comment by Isaacssv552** [comment]
Immediately before the worst glitch:
<img width="1277" alt="before" src="https://cloud.githubusercontent.com/assets/5642624/20645193/fb6a3338-b423-11e6-8623-f6dacfa1a784.png">
Immediately after:
<img width="1276" alt="after" src="https://cloud.githubusercontent.com/assets/5642624/20645330/1cb067e2-b429-11e6-9a2e-ce836b2f185d.png">

**Comment by Isaacssv552** [comment]
I'm not sure how it might be related to #1775. I've tried recompiling the entire project, but that doesn't make any difference. I haven't tried selling in bulk, but I have noticed absurd multipliers sometimes appearing. For now I've simply disabled depreciation so I can use the outfitter without constantly having to mod my credits back to sanity.

**Comment by endless-sky** [comment]
One of the files in the "Experimental" plugin is a zip file. Is that meant to be extracted, or ignored?

I've added a check for outfit ages going negative (05f4cc1), but other than that I can't think of what might cause this.

**Comment by Isaacssv552** [comment]
My further testing has revealed that "Experimental" has no effect on the glitch. It was a coincidence that I started using a release build at the same time I made the plugin. I've also noticed it is happens either seemingly at random or after I sell an outfit back and forth a certain number of times.

**Comment by kaylara** [comment]
I have independently reproduced the bug during normal game play with the high-dpi plugins attached. I am running the latest public beta from Steam on Mac OS 10.12.2. I am unclear on HOW to reproduce the bug, and the saved game does not show the high price. When I sell all the ramscoops from all my ships at once, then buy, then sell, it seems to start the high-frequency flickering that others have reported.  Here are a saved game and screenshots of values acting crazy. Let me know if you need any more info!
![screen shot 2017-01-21 at 9 28 53 pm](https://cloud.githubusercontent.com/assets/25284676/22184959/ed1a3e22-e0a1-11e6-80ad-791193f08cc5.png)
![screen shot 2017-01-21 at 1 19 47 pm 2](https://cloud.githubusercontent.com/assets/25284676/22184968/111b570c-e0a2-11e6-8976-f54e5a0dd8bb.png)

[ap k~Wanderer Ramscoop too valuable.txt](https://github.com/endless-sky/endless-sky/files/722170/ap.k.Wanderer.Ramscoop.too.valuable.txt)
