### ISSUE TITLE
Feature/UI Inquiry

### ISSUE THREAD

**Issue by Hecatoncheire** [endless-sky/endless-sky#186]
First off, what a fantastic start to this game; it's managed to suck me in the way recent AAA titles simply haven't. I had a few thoughts on the UI and features though, which I've listed below in rough order of importance.

1) The behavior of the Esc key
I'm used to Escape being contextually sensitive - if you're in a submenu, it brings you one level up, if you're at root, THEN it pops the options screen. I find it a bit disorienting since often times I'll be on the Map, Job, or Shipyard screen, then instinctively hit Esc to return to the spaceport/space, but then I get the Options menu. So I have to hit Esc again to cancel that, sort out what screen I'm on, and hit the appropriate keybind to exit. I feel it'd be a bit more elegant and intuitive to have Esc return you to the landing/spaceport/spaceflight screen if in a submenu, THEN launch the Options panel if pressed from there.

2) "Locking" cargo holds
Playing through with a mixed warship/freighter fleet, I notice that if I'd like to load up my freighters with trade goods but keep my flagship cargo space for stripping outfits from disabled ships, there does not seem to be any easy way to keep space open. The only way I've found is to swap flagships, park it, buy goods, unpark it, reswap it - a rather cumbersome process. If there were some way, perhaps in the Info screen, to "lock" a ship's hold so that mission and/or trade cargo wouldn't clutter it up, that would really make a trading-and-pillaging playstyle much simpler.

3) Shoot to Kill vs. Shoot to Disable
Speaking of pillaging, I find it can be a bit tricky to encourage the fleet to not destroy things outright at times. Often if I'm careful, they're careful, but just as often everything in sight gets vaporized. An option to toggle between Shoot to Kill and Shoot to Disable, perhaps with a Fire at Will to restore default behavior, might be a helpful feature. The current behavior may be what is intended however, so this may simply be wishful thinking.

4) Cargo/Passenger transfer
This one might clutter up the UI and be a bother to implement, so take it more as food for thought. A way to manually transfer goods and passengers ship to ship could potentially be useful from time to time, so if it doesn't distract from more important tasks and can be gracefully wedged into the UI, the ability to micromanage which ship has what might be useful from time to time.

Keep up the good work, and I look forward to how the game develops!

**Comment by endless-sky** [comment]
That Escape key behavior is a common request - commit 51084de changes it to what you described. That will be part of the next release (today, hopefully).

Your ships will not fire on a disabled target, but they don't have the ability to gauge how many shots are in transit and to judge whether those will be enough to disable the target. So, if you don't want to accidentally destroy ships instead of disabling them, equip your ships with only beam weapons, which they can shut off immediately when the target is disabled.

**Comment by Pointedstick** [comment]
Another advantage of laser weapons vs blasters. :)

**Comment by egilburg** [comment]
> 2) "Locking" cargo holds

How about, if you travel with a fleet, all purchases first fill up your fleet ships and only then your flagships, while all sales first sell from your flagship and only then from your fleet ships.

**Comment by endless-sky** [comment]
The Escape key and the issue of not having room for plunder due to mission cargo are fixed in 0.8.5 and 0.8.7 respectively. If you want to reopen your other suggestions as individual issues, feel free to do so.
