### ISSUE TITLE
Bug: Crew Levels

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1860]
If you have enough crew to fill the ships required crew but not man all the turrets it should not affect maneuverability.
for instance if you have a freighter which requires 1 crew in the ship attributes and 2 to man turrets, after a boarding action you have 2 crew left you should be able to maneuver normally but only use one turret.

**Comment by KiLEdEnNis** [comment]
that has been adressed before and it is >not< a bug, there should be a noticeable penalty for having crew members die
please search for similar issues before bringing a new one up
(the ones that don't are here long enough to remember what has been adressed before)

**Comment by Wrzlprnft** [comment]
Also, imagine only your turreters survive and you have to get a damaged ship back. They can't keep the engines from exploding and steer properly at the same time...

**Comment by Elyssaen** [comment]
I get what you're saying, but aside from what's been said already there's also this angle: I'd rather _very_ occasionally not be able to turn than be _completely_ unable to fire. Being a few crew short isn't too bad a malus right now, and you can still finish a fight and land safely. 

It's not too jarring either, as we just imagine that the surviving crew prioritise manning the weapons.

**Comment by Amazinite** [comment]
#1127

**Comment by endless-sky** [comment]
Being short on crew is *supposed* to be annoying, to penalize the player for taking that risk.

**Comment by lheckemann** [comment]
You don't necessarily have to let anyone get killed to be short on crew, it could also happen if you capture another ship without having any extra crew. Of course, that's poor planning and can be penalised just as well :)
