### ISSUE TITLE
#1585 is not fixed

### ISSUE THREAD

**Issue by onnikyla** [endless-sky/endless-sky#1862]
Yesterday I did the mission where you need to give freya an Electron beam. Today, just a few minutes ago I landed on the planet with two Electron turrets installed. The mission completion text showd up and it took one of the turrets.

**Comment by KiLEdEnNis** [comment]
to be sure, are you sure you use the most recent version of Endless Sky? (beta, from source is best)
it shouldn't happen but I'm not sure what it says exactly
both missions should have each other in the "not" part

**Comment by onnikyla** [comment]
I just redownloaded endless sky beta from steam a few days ago so that shouldnt be the problem, ill check the gamefiles.

**Comment by Wrzlprnft** [comment]
If you activated the mission pre 0.9.4 the fix was not applied, due to an active copy from the old mission was stored in your savefile.

**Comment by onnikyla** [comment]
How long ago did 0.9.4 come to steam. I made a new save 3-4 days ago.

**Comment by Wrzlprnft** [comment]
Mmh then this should not be the problem...

**Comment by toilethinges** [comment]
#1812 ?

**Comment by endless-sky** [comment]
87c97c0 should fix this.
