### ISSUE TITLE
Infinite money glitch.

### ISSUE THREAD

**Issue by sjud** [endless-sky/endless-sky#1863]
<img width="541" alt="screen shot 2016-11-29 at 3 05 09 pm" src="https://cloud.githubusercontent.com/assets/23065688/20727006/cc5dc360-b645-11e6-8678-6bcaf2464364.png">

<img width="584" alt="screen shot 2016-11-29 at 3 05 19 pm" src="https://cloud.githubusercontent.com/assets/23065688/20727013/cf391486-b645-11e6-98e1-5cf4b5d8e7e6.png">

Most recent game built.
Sargas on Trinket. 
Selling plasma turrets at 2.5m buying them back for 250k.
I'm on the 'Escort Battleship Mission' for the Rebels.

**Comment by sjud** [comment]
Oops works ok Steam. I'm just going to close this because my Desktop version is probably buggy.

**Comment by KiLEdEnNis** [comment]
btw, I have another one: open save file, add money :3
