### ISSUE TITLE
Mouse Selectable Ships in On-Screen Ship List

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1864]
This List: 
![screen shot 2016-11-29 at 6 05 14 pm](https://cloud.githubusercontent.com/assets/22384290/20734979/71e17810-b662-11e6-9b78-01c77332618f.png)

**Comment by retrue** [comment]
There is a problem. The ships in that list sometimes represents a single ship, other times it is several ships of the same type if your fleet is big.

**Comment by KiLEdEnNis** [comment]
being able to customize which ships show independently & where on the list could be paired with the idea

**Comment by Admiral-Danforth** [comment]
What KiLEdEnNis said would be fine to

**Comment by endless-sky** [comment]
Added in commit 69e289d. (Eventually, this will be a part of being able to select multiple escorts at once to give them group orders.)

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
