### ISSUE TITLE
possible to create (or corrupt?) snapshots so that they cannot be deleted (invalid filename)

### ISSUE THREAD

**Issue by TeoTwawki** [endless-sky/endless-sky#1866]
This happened on the Steam version, no mods or plugins, windows 10 pro 64 bit.
I somehow had a file name that ended in a space and no txt extension. This snapshot showed up in game, but could neither be loaded nor removed. In windows, I could not delete the file - windows would claim the file had moved. It definitely was actually present, and wasn't in a locked state. It is normally impossible to have a filename end in a space like this. I was able to use bash from my git installation to actually delete the file when windows couldn't.

Unfortunately I don't know how exactly this happened. I've spent the last several hrs trying to reproduce it with no luck. Both windows and the game trim off any trailing spaces in snapshot names/files for me when I try to make this happen on purpose.

**Comment by KiLEdEnNis** [comment]
did you edit anything on the save file?
and could you provide ascreenshot of the loading screen

**Comment by TeoTwawki** [comment]
no edits at all. And I need the glitch to happen again to screenshot it, since I used git bash to delete the file.
The file name was `my captain~new ship ` with a trailing space and appeared in the games menu as `news`.

**Comment by KiLEdEnNis** [comment]
not sure then, maybe someone else can figure it out
