### ISSUE TITLE
Nunki doesn't show the right color

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1867]
explained; the sector "Nunki" (where the pirate world Albatross is in) doesn't show the color matching my reputation towards it; it shows light blue when the pirates are hostile to me
playing on my laptop but should be the regular 0.9.4 (or the beta) from Steam

I searched for a similar issue (both open/closed) and couldn't find anything, although I vaguely remember an issue about a pirate world(?)
I think something where the Militia got changed to Free Worlds in Nunki
![endless sky issue](https://cloud.githubusercontent.com/assets/10348657/20751812/3cabd2de-b6fe-11e6-9904-89f23f610ef5.jpg)

**Comment by KiLEdEnNis** [comment]
#1496 & #1505 were the ones I meant, I think something there caused it (but Shaula is normal)

**Comment by Amazinite** [comment]
Does Nunki get a negative `required reputation` at some point?

**Comment by Bladewood** [comment]
It has a `required reputation` equal to -10, yes.

**Comment by KiLEdEnNis** [comment]
so once the reputation goes below -10 you can't land?
is that intentional?

**Comment by jafdy** [comment]
I think so. -10 is the starting relation ship with pirates so it would let you land on some pirate planets before you become friendly with the pirates. (If you want to be a pirate.)

**Comment by KiLEdEnNis** [comment]
seems weird as all I did was kill pirates (a few yet)
close this issue?

**Comment by Bladewood** [comment]
I was wrong.
Bloodsea's required reputation was -10, not Albatross's. (though you could still land on it if you had not attacked pirates yet)
Albatross's required reputation was -20.

**Comment by toilethinges** [comment]
Yeah, close the issue... it's blue because you can land there, even though you have negative reputation with the government.

**Comment by KiLEdEnNis** [comment]
just weird as I attacked a few pirates before

**Comment by Lineth** [comment]
You start with more reputation with the pirates than the minimum, but less than to keep them non-hostile(say you start with -1, but you need to be -10 before you can't land without paying). You can kill several pirates and still land on their worlds, but if you make a habit out of it you'll be restricted.
