### ISSUE TITLE
Mention absurd heat generation rate in Coalition engines

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1869]
Currently, the "considerable amount of heat" line is only in the small Coalition thruster's description, so I think people will be less likely to notice the absurd amount of heat that all of them create at first.

I think this should be changed, such that all of them mention (or at least [shout out? joke about?]) both their efficiency with regards to energy and space and inefficiency with regards to heat, like all the other engines in the game...

**Comment by endless-sky** [comment]
I'm not convinced that this is necessary. The flavor text is really supposed to provide flavor, not necessarily to rehash all the strengths and weaknesses of a given outfit.
