### ISSUE TITLE
Cooling module

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1877]
A liquid nitrogen cooler in a fourth of the space. 348 cooling/ton, with the tiny drawback of -24 energy/second (-4.8 energy/ton), priced at a mere 160000 credits.
For comparison, the large heat shunt has 135 cooling/ton, at 790000 credits.
Just how much heat do those Heliarch weapons make?

**Comment by KiLEdEnNis** [comment]
seems like a near T3 cooling

**Comment by Bladewood** [comment]
Of particular importance in this issue is the pretty darn low price. Two provide 7.4% more cooling than a large heat shunt in less than half the space, for 470000 less credits.

**Comment by KiLEdEnNis** [comment]
didn't MZ say the warships were gonna be T2.5? Korath automatons are around 2, so it doesn't make much sense
like, read the large heat shunt description, then imagine a cooling that's like 3x as efficient

**Comment by jafdy** [comment]
Lets wait until the Heliarch ships and weapons come out.

**Comment by KiLEdEnNis** [comment]
indeed, I just wonder if the cooling will go down
hype o:

**Comment by Bladewood** [comment]
Now we see that most, if not all, of their weapons are incredibly heat-efficient compared to their engines.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/ef18c909e916fbe784a4651080355f3e95b86be9 ahahahahaha!

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
