### ISSUE TITLE
Individual ship pages

### ISSUE THREAD

**Issue by piefail** [endless-sky/endless-sky#188]
I noticed there is a lack of pages of each ship in the game, providing more info on each ship, like its bio and the specific guns and turrets on it

**Comment by endless-sky** [comment]
Do you mean wiki pages? All that information is available in-game in the
shipyard.

**Comment by piefail** [comment]
Yeah, but have a place where one can see the info of ALL ships instead of
having to hopping around the galaxy to see a ship that isn't sold at a
certain location

**Comment by Pointedstick** [comment]
That's already there. Click on the "Shipyard" button while you're in the map view.

**Comment by Pointedstick** [comment]
Although it's true that on the map's shipyard mode, you don't see what outfits the ships have.

**Comment by endless-sky** [comment]
I think the shipyards map shows the most important ship traits; outfits are of secondary importance because they can easily be changed. That map was never meant to be an exhaustive source of information, anyway.
