### ISSUE TITLE
Map zoom level not remembered on Fedora 25

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1881]
I'm running Fedora 25 with GNOME 3.22 and Wayland. The map doesn't remember the zoom level, ever. I can zoom to whatever level I prefer, close the map, and when I re-open it, it's back at the default zoom level. Other preferences and settings are remembered correctly.

**Comment by Bladewood** [comment]
Is... is it supposed to?

**Comment by Pointedstick** [comment]
Perhaps my memory is going, but I recall the map zoom level being remembered in macOS (got rid of that computer, so I can't test this anymore).

**Comment by Amazinite** [comment]
Zoom doesn't save on windows, which I rather like.

**Comment by Pointedstick** [comment]
Or maybe I'm misinterpreting things and the default zoom level was simply to my liking at a higher zoom level. I find that running the game at 100% (default) scaling on a 1080p screen, the default map zoom level is a bit too far out for me. Going up to 150% makes the default map zoom level perfect again (of course, then everything is scaled 150%, which you might not prefer).

**Comment by endless-sky** [comment]
This is addressed in commit cdb1cb8.

**Comment by Pointedstick** [comment]
Confirmed. Thanks!
