### ISSUE TITLE
Korath Engines Wrong Order

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#1887]
Although all races' engine outfits go in the order of "Small Steering, Small Thruster, Large Steering, Large Thruster," Korath engines do not. Instead, they go "Small Steering, Large Steering, Small Thruster, Large Thruster", which seems out of place in the game. The solution to this should be rather easy (will renaming the outfit to "xxx class Thruster/Steering" work? idk), but I don't have the time right now to test it out for myself. Just putting it out there for people to notice.

**Comment by jafdy** [comment]
That should work if you put Korath on the front. eg "Korath planetary class Thruster"

**Comment by Bladewood** [comment]
@jafdy If you are worried about Korath engines being misplaced among those of other races, look at the tyrant engines.

It's okay if they are out of order, right? They are alien engines, and therefore do not have to follow the same naming and ordering schemes.
And look at regular human engines. Atomic engines ignore the ordering that ion and plasma engines follow.

These engines don't all have to be the same.

**Comment by MessyMix** [comment]
@Bladewood True on the human atomics, but they're all escalating in size, similar to any other 

However, up to this point all races, alien or not, go from small to large. The only exception to this are   the Korath. It just irks me that the ordering is different like this, and only for the Korath. I feel that a list of outfits should have a universal (see what I did there?) format, because after all they are all engines.

Also, another point: the OUTFITTERS I am using are in human space. It would actually be more understandable if in alien space, the order of the outfits were different. But at a human outfitter, the human should order the Korath outfits the same way they'd order any other outfit, instead of treating them differently due to their being alien outfits. So I find this inconsistent with the rest of the game. Why would something be one way and something be another? Either order them _all_ small to large (like every other species currently), or steering then thrusters (like the Korath)! It's so irritating to have them all ordered differently. No rational being would do something like that!

**Comment by Bladewood** [comment]
[warning: tired thoughtstream inbound]
Coalition and Pug engines.

We're talking about aliens here. We follow their own orders. It's like how I always pronounce a foreign name (such as the name of a place) in the same [accent? tone? voice?] that its own people would pronounce it.

**Comment by MessyMix** [comment]
@Bladewood 
> "We're not evil xenophobes plotting to standardize everything in the galaxy."

So tell me how the banking system works again? Oh right, it's standardized across the galaxy. No biggie, right? :P

Also, the Pug engines seem (from the .txts) to be in the correct order. Also, I'm not building from source, so the Coalition isn't merged into my 0.9.3 build at the moment. You're right, by the .txt files they aren't in the standard small --> large organization. And perhaps it stands to change! I still believe that all engines should be classified ONE WAY or THE OTHER, for organization's sake.

I agree on how we pronounce foreign name the way it's supposed to be pronounced. But remember that I am in HUMAN space DOWN SOUTH where they've never seen anything to do with Korath before, and they have no clue on how the Korath order their outfits. So THE OUTFITTERS order the engines ACCORDING TO THEIR OWN STANDARDS.

It's not a matter of standardizing across the whole galaxy, it's about how the _individual outfitter_ orders the engines. It's like asking someone to pronounce a name, but they've never ever heard that language before! So how would they know how the word is supposed to be pronounced? If I see alien engines for the first time, I HAVE NO CLUE how the aliens order their own outfits, so I'll just go ahead and put them on the shelf the way I do for everything else, thank you very much. do you see what I'm getting at? It's not a matter of how the aliens order it! It just irks me that a human outfitter will look at Korath engines and say, "oh, what are these? I should order them differently for no reason at all!". That's what I'm trying to say.

BTW I found your language metaphor very insightful. Thank you for that 👍

**Comment by endless-sky** [comment]
My goal with the engines is just to make sure that they're sorted from small to large. I don't think it really matters how the thrusters are sorted relative to the steering. (For example, because of how the plasma names work, they end up interspersed with whatever other types of engines are for sale, but at least they're sorted from small to large.)
