### ISSUE TITLE
Boarding Glitch 

### ISSUE THREAD

**Issue by goldentaco** [endless-sky/endless-sky#1888]
Sometimes when im piloting my Behemoth and try to board a pirate for looting the ship will become uncontrollable, cant warp, land, steer, etc and I have to reload save. Doesnt happen on my Leviathan.

**Comment by jafdy** [comment]
Did you steal the generator?
Did you steal the steering/thrusters/hyperdrive?
If no to both than can you paste a link to your save.

**Comment by KiLEdEnNis** [comment]
I think he means his own ship loses control

**Comment by MessyMix** [comment]
Pirate ship loses control:
You plundered either the generator or the engines. If you can't jump out of the system, the hyperdrive.

Your ship loses control:
You lost too many crew members? Can you please elaborate on HOW your ship lost control?

**Comment by KiLEdEnNis** [comment]
if the pirate ship loses control after you plundered stuff, it's still disabled, and they won't board it until you left the system
so I don't see how one could know that

**Comment by MessyMix** [comment]
@KiLEdEnNis No, you can plunder an outfit and then attempt a capture.

I did this with a Quicksilver once: Stole its engines, then captured it. It wouldn't move, even though I had captured it.

**Comment by KiLEdEnNis** [comment]
I'm not an engineer, but I think ships need engines to move
