### ISSUE TITLE
Unfettered jump drive mission stuck in log

### ISSUE THREAD

**Issue by RockRaider42** [endless-sky/endless-sky#1889]
Unfettered Jump Drive missions don't appear to fail when the Unfettered become hostile again, so an impossible mission remains in the mission log.  I'm not sure if this is a bug or a part of a future extension of the story line.

Could it be made possible to complete the mission to "atone" and be at peace with them again, or else be made so that the mission fails if they're meant to be permanently hostile?

**Comment by SonEasterZombie** [comment]
pretty sure you can just bribe their home world to land and sell the drives.

**Comment by Amazinite** [comment]
You can always abort the mission.

**Comment by RockRaider42** [comment]
When you bribe them and land, the dialog to sell a jump drive doesn't appear.  It looks like the mission can't be completed (and isn't supposed to be started again, if I'm reading the conditions correctly) after the invasion starts, and it seems to me that either the mission should automatically fail then or else it should be able to be completed to become neutral again, at least after the main conflict.  I don't want to just abort the mission if a future update would change the mission's intent.

**Comment by endless-sky** [comment]
Fixed in 2762f57. Note that this won't affect the copy of the mission stored in any of your saved games, only new copies of that mission that are generated going forward.

**Comment by RockRaider42** [comment]
Great, thanks!
