### ISSUE TITLE
Game exits immediately if there are no sound devices

### ISSUE THREAD

**Issue by karlkatzke** [endless-sky/endless-sky#189]
Platform: Windows 8.1

Description: If you have no sound devices that are working properly (e.g. your only sound device is headphones and headphones are unplugged), then you will get a dialog message that says: 

"Endless Sky: Error

Unable to open audio device! (SDL message: "")" 

Expected operation: Even if there are no audio devices, Endless Sky should still open, because the game doesn't depend on audio input or output.

**Comment by endless-sky** [comment]
Test and see if this is fixed in 0.8.7 (download here, or switch to the "beta" branch in the Steam client, in Endless Sky -> Properties -> Betas).

**Comment by endless-sky** [comment]
People have reported that this is fixed for them in 0.8.7, so I'm closing this issue.
