### ISSUE TITLE
Usability: no cue for system search

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#1893]
I had no idea I could search for star systems until I accidentally pressed F while on the map screen. It would be very useful to have some sort of visible cue that this is possible.

**Comment by MessyMix** [comment]
Same condition as you! In fact, I was looking really hard for something, and was about to suggest it online, when the thought to press "Cmd+F" came to mind. And then _voila_!

**Comment by Wrzlprnft** [comment]
2d77d1b

**Comment by endless-sky** [comment]
My general philosophy has been that if something in the UI is nearly universal (like, using the scroll wheel on your mouse to scroll a list) I might mention it in the documentation, but there's no reason to mention it in the in-game help.

Granted, as a Linux user, once or twice a day I'm typing something like "^W" or "/" to do a find, but for 99% of users every program they use will respond to "^F".

**Comment by Pointedstick** [comment]
It's still invisible, though; you need to have some conception that hitting the "f' key is going to have some effect before you even think to try it (I never did, and found out about the feature by reading this issue report).

If there's going to be a search feature, it really ought to have *some* kind of visual UI hint, or better yet: an actual search field somewhere, like most UI programs have when there's a search feature available.

**Comment by lheckemann** [comment]
@Pointedstick exactly.

@endless-sky but the C-F shortcut isn't really universal. There's also F3 for instance, which I think is a lot more common in older Windows/DOS software (I may be wrong, I'm really not an expert); and the most widespread shortcut for searching in the software I use (which of course also doesn't make it universal) is / as you mentioned. I think a neat solution would be having an always-visible search bar in the middle at the top, which when you type in it changes the colour scheme so that matching planets have a white ring and others are grey (or something like that).

(slightly OT: the main use I have for the search feature is finding where my escorts are hanging about relative to me; what would also be nice is some way of displaying this directly on the map.)

**Comment by endless-sky** [comment]
In my opinion it's a matter of giving each UI feature a degree of visibility that roughly corresponds to how useful it is. If every single feature had to have a visible UI widget pointing out its existence, it'd be hard for new players to figure out which widgets are useful to them and which aren't. That's the same reason that the pop-up help just focuses on the important stuff and lets the manual handle the rest: presenting too many options or too much information is as bad as not presenting enough.

And, be realistic: for 99.9% of users, they aren't running DOS or nano or vi, they're using modern GUI applications, in which ^F for find is nearly as universal as ^X for cut and ^V for paste.

**Comment by Elyssaen** [comment]
Totally get your point, Michael, but are you keeping track of how many players say they find it useful and didn't know they could do it? If so, add me to the list! In lurking I've seen this come up a few times in different places, and I really think a lot of players would find a UI feature for this in particular really useful.

**Comment by Pointedstick** [comment]
> In my opinion it's a matter of giving each UI feature a degree of visibility that roughly corresponds to how useful it is.

If a feature in a GUI application is completely invisible doesn't that imply it's close to useless? If so, why include it at all? If you're going to include a feature in a GUI application, it needs to be discoverable. Games don't generally conform to systemwide keyboard shortcuts; having the F key bring up a hidden search box is very nearly the same thing as not having a search feature at all. Furthermore, keyboard shortcuts are learned through some visible UI in the program itself. No such thing exists here.

**Comment by KiLEdEnNis** [comment]
an actual skipable tutorial (instead of a bit of training when you start the game) could help
it would be one of those annoying 4th wall breaking ones like "if you ever have to find a certain planet or system, press Ctrl F"
either that or an original one like "your space map has a search function, simply press Ctrl F on your board computer"

**Comment by Wrzlprnft** [comment]
how about a little triangle V on the middle top of the screen, with a magnifying glass on it. if the player clicks on it, it's the same as pressing f. as well as label the hotkey onto the little pop up.

**Comment by Pointedstick** [comment]
I think there's a really simple solution here: put an actual search box directly under the map UI widget that displays a graphical representation of the star system, and above the plus and minus map zoom buttons. I wonder if I can figure out how to do that...

**Comment by Elyssaen** [comment]
If you can I'm sure as hell pulling it into the copy I play, @Pointedstick. I'd be happy to look at it with you too, though I'm also at the "wonder if I could figure it out" stage right now. : ) I think you're on to something with that location: it nicely implies it can search for a planet as well as a star.

**Comment by Pointedstick** [comment]
So far it looks like graphical changes will be required, to add a sprite for the button or the search field.

**Comment by Elyssaen** [comment]
Hey @Pointedstick, sorry to lose sight of this. Agreed that it'd want a sprite. Do you still want to try it out? I could probably put together a sprite if so, though it might not be for a week... I'm Away-From-iMac right now, and hate image editing on Windows.

**Comment by Pointedstick** [comment]
Go ahead. I'm working on other stuff right now.
