### ISSUE TITLE
Data Files on Linux

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1897]
I freely admit to not being a genius when it comes to Linux, but I do find it interesting that the game saves, mods, and data files are all kept in one location. This would not be a problem normally but it does get to be a pain when I am working on one project or another and end up breaking saves by loading the wrong one.

Is there any way to force the game to only look in its own directory?

**Comment by endless-sky** [comment]
That's explained in the man page and in the output of `$ endess-sky --help`. You can just call the game like this:

```$ endless-sky --config path/to/a/folder```

and for everything that is usually read from `~/.local/share/endless-sky` it will look in `path/to/a/folder` instead. The `--resources` command line option does the same thing for specifying where the game resource directory is.

**Comment by Nechochwen-D** [comment]
Thank you.

Is there any way to tell it to only ever look in its home directory when compiling?

**Comment by endless-sky** [comment]
Not without modifying the code, but you could always just create a shortcut or script that calls `$ endless-sky --resources ./` or something like that.

**Comment by Nechochwen-D** [comment]
I will do that then.

I am working on a launcher for Linux that will be able to grab the latest code from the repository and then use system tools to compile it. My plan is to be able to let people have multiple versions available to play and allow mods to be used without them interfering with other saves.
