### ISSUE TITLE
[Solved] Build Failed

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#1898]
Building terminates due to error:

`source/Music.cpp:17:17: fatal error: mad.h: No such file or directory
 #include <mad.h>
                 ^
compilation terminated.
scons: *** [build/release/Music.o] Error 1
scons: building terminated because of errors.
`

Running Linux, OpenSuse, compiling with Scons.

**Comment by endless-sky** [comment]
You'll need to install libmad. It was added as a dependency recently to support mp3 streaming.

**Comment by Amazinite** [comment]
>To build Endless Sky you probably want the latest XCode version (I used 5.1.1). You also need to install _three_ libraries:

Four now.

**Comment by Pointedstick** [comment]
> You'll need to install libmad. It was added as a dependency recently to support mp3 streaming.

Speaking of that... https://github.com/endless-sky/endless-sky/pull/1899

**Comment by gchapyzh** [comment]
libmad-devel has been downloaded and fixed the issue.

**Comment by Pointedstick** [comment]
You can close the issue, then.
