### ISSUE TITLE
Boarding dialog: combat text can go out of the window

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#19]
As shown in this screenshot:

![endless1](https://cloud.githubusercontent.com/assets/4701338/7262993/22ed7e60-e87e-11e4-87e0-ccb23c80d0d1.jpg)

**Comment by endless-sky** [comment]
This should be fixed in 9a0ef63. The issue was that I was limiting that text to five lines when you clicked "Attack" or "Defend," but not when you initially pressed "Attempt Capture."

**Comment by endless-sky** [comment]
I've tested this, and my commit from a week ago seems to have fixed it.
