### ISSUE TITLE
Re-render ships so that the axis of rotation is tilted 45º away from the camera

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#190]
Right now all the ships are rendered with an axis of rotation that is parallel to the camera. You're looking right down at them. In EV Nova, the ships rotated around an axis that was tilted 45º away from the camera. As a result, when a ship was pointing "north", you would see inside its engines, and when it was pointing "south", its prow was more visible. Observe the perspective effect in this picture:
![Image]
(http://www.ambrosiasw.com/assets/images/galleries_products/evn/survival02.jpg)

I think this was a big visual improvement, and made the game look a bit less cartoony than the predecessor EV games where all the ships were rendered completely top-down, like Endless Sky does. If it wouldn't be too much work, the ships in Endless Sky should be re-rendered to adopt this as well.

**Comment by Frozen-byte** [comment]
Sorry but in my very personal opinion these 45° turned ships look really crappy.
I am very happy with the Top-Down-Angle.
A much nicer way to Improve the graphics is to include small(!!!) not-annoying-animations.
To improve overall-feeling just improve the sound (what is already planned)

**Comment by endless-sky** [comment]
I never liked the way the Nova ships were rendered - it made it way too
hard to figure out exactly what direction your ship was pointed in.

Also, right now each ship uses a single image as its sprite, which has the
advantage that people can create new ships without even having access to a
3D modeling program. In EV, you had to render the sprite at a bunch of
different angles and combine them into a sprite sheet, which makes it
considerably harder to add new ships to the game.

I think what really made the Nova ships stand out was the high-quality
texture mapping and bump mapping, which I know is an area where my sprites
could be improved.

**Comment by Pointedstick** [comment]
Fair enough! The high-quality textures were definitely good, as well as little things like blinky running lights and a mature, muted style rather than the bright colors and simple geometric shapes of the ships in the prior games.

**Comment by Pointedstick** [comment]
Another plus was good sizing. Generally you didn't have carriers launching fighters that were only half their size or other silly things like that. The fighters were tiny, the capital ships were huge, and there was an appropriate sense of scale to everything. I think some of the Endless Sky ships could be better scaled to their roles and in-game masses. A lot of the interceptor type ships seem much too large. And right now I'm flying around in a Hauler which is almost as big as a Republic Carrier!

**Comment by Frozen-byte** [comment]
I have to agree Pointedstick the relative sizes are not very realistic.
At the moment I don't see any other solution to make the game playable (nobody wants to stare at three pixel big fighters) but with the new Zoom feature it is actually possible to have realistic dimensions to the spaceships.

Fighters will become icons if you zoomed too far away - Motherships will fill the entire screen if you are fully zoomed in. That would be awesome!

**Comment by kkuchta** [comment]
+1 for the top-down view.  The 45˚ angle looked nice in screenshots, but as you say– it made it harder to see exactly where you were pointing.

On the topic of ship design, another thing that bugged me about Nova was that the ships didn't seem sufficiently visually differentiated between species.  I mean, in Override, you could tell a Voinian ship from a UE ship from a Emalgha ship just by looking at them.  In Nova, a lot of the ships looked very similar between factions (except for the polaris and vell-os).

Endless sky, admittedly, is mostly about the humans so far, but the alien races that *are* there do a decent job of having a solid visual identity.  Awesome work.  :)

**Comment by Pointedstick** [comment]
Closing.
