### ISSUE TITLE
When > 100 zoom factors are not permitted because the effective resolution would fall below 700 pixels, indicate this to the user when the zoom button is clicked.

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1901]
Fedora 25 + GNOME 3.22 + Wayland

I normally run at 150% zoom and full screen. When I toggle full screen and drop to windowed mode, the zoom factor drops to 100 and can't be raised higher than 100 until I re-enter full screen.

**Comment by endless-sky** [comment]
The zoom factor resets to 100% any time you resize the window to smaller than 700 pixels tall. That's by design, because otherwise some GUI elements would not be visible.

**Comment by Pointedstick** [comment]
That shouldn't be at play here. My display is 1080 pixels tall. Entering windowed mode doesn't result in the window being shorter than 700 pixels tall. It's almost as large as it would be in full screen.

**Comment by DingusShingleton** [comment]
I can't seem to ever change the zoom factor. It's locked at 100 no matter what I do. I have a 4k screen but it's locked whether the res is set to 2160 or 1080. Windows 10, steam build.

**Comment by Pointedstick** [comment]
@DingusShingleton Is that in windowed mode, or full screen? In Fedora Linux as well as macOS, I've been able to change the zoom mode when in full screen, using 2650x1600 and 1920x180 displays. But I can't change the zoom when windowed, even when the window is taller than 700 pixels.

**Comment by DingusShingleton** [comment]
Windowed or fullscreen, it doesn't change in either. Unless I'm missing something. I click on it, press the arrow keys, space bar, return.... nothing changes it.

**Comment by Pointedstick** [comment]
Okay, sounds like a separate Window-specific bug, maybe? That works for me in Linux and macOS.

**Comment by Pointedstick** [comment]
Oh I see. It would be nice if this was visually indicated when you try to click on the control and it does nothing.

**Comment by Pointedstick** [comment]
Created a PR to address this: https://github.com/endless-sky/endless-sky/pull/1906

**Comment by Pointedstick** [comment]
@DingusShingleton, the notification I added in that PR should "resolve" your issue too, in that it'll at least tell you why you can't zoom higher than 100%.

**Comment by DingusShingleton** [comment]
Sweet, thanks,
