### ISSUE TITLE
Window positioned improperly when Alt-tabbing back into Endless Sky when using Wayland instead of X

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1902]
Fedora 25 + GNOME 3.22

If logged into a Wayland session, when I Alt-tab out of Endless Sky and then Alt-tab back, the window doesn't position itself properly. The problem does not occur when logging into an X session.

[Here's a screen recording](http://hommelscitadel.com/wp-content/uploads/2016/12/not_quite_right.webm).

**Comment by endless-sky** [comment]
That might be an issue either with SDL or with Wayland - when you switch into full-screen mode, the game itself has no say on where the window goes because the window is supposed to cover the whole screen.

I'm afraid I probably won't have time to install Wayland just so I can try to reproduce that bug (I'm using Unity over X11 here). But if you're able to find a work-around, I can test it on other systems to make sure it doesn't break them.

**Comment by Pointedstick** [comment]
FYI sooner or later (lately it seems like later…), Ubuntu is going to switch to Mir, whose architectural roots are the same as Wayland.

I can report this to the Freedesktop folks and see what they say about it.

**Comment by Pointedstick** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=99088

**Comment by Pointedstick** [comment]
FWIW, the Wayland folks say the bug is in Endless Sky or GNOME. I guess it could still be SDL, too.

GNOME bug: https://github.com/endless-sky/endless-sky/issues/1902
SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=3548

**Comment by Pointedstick** [comment]
With Unity's demise, Ubuntu 17.10 uses GNOME and Wayland by default and will do so going into the future, joining Fedora in the "Wayland by default" club, so this issue is likely going to crop up more and more.

**Comment by tehhowch** [comment]
Is this still a thing?

**Comment by Pointedstick** [comment]
Nope, this was fixed in https://github.com/endless-sky/endless-sky/commit/429f74f24e5608f571d9418b29043dc332b67f15.

**Comment by MCOfficer** [comment]
Are you sure about that? i can't see that commit having any impact on wayland.

**Comment by Pointedstick** [comment]
Oh jeez, I was thinking of the wrong issue, sorry. However happily I can no longer reproduce the original issue anymore (now with KDE Plasma 5.15 on Manjaro).

**Comment by MCOfficer** [comment]
I guess we're just gonna blame it on wayland's early days, then.
