### ISSUE TITLE
When alt-tabbing out of Endless Sky, do not resize the window or drop to windowed mode 

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1903]
Fedora 25 + GNOME 3.22

I generally run at 150% zoom factor. When I Alt-tab out of Endless sky, the zoom factor is immediately reset to 100. This happens with both Wayland and X.

I didn't see this issue in macOS.

**Comment by Pointedstick** [comment]
May be a duplicate of https://github.com/endless-sky/endless-sky/issues/1901, or else the same root cause.

**Comment by endless-sky** [comment]
The zoom factor resets to 100% any time you resize the window to smaller than 700 pixels tall. That's by design, because otherwise some GUI elements would not be visible.

**Comment by Pointedstick** [comment]
That shouldn't be at play here. My display is 1080 pixels tall. Alt-tabbing shouldn't change the window dimensions.

**Comment by Pointedstick** [comment]
So it sounds like what's happening here is that alt-tabbing somehow resizes the window, at which point the zoom factor resets to 100 because its effective resolution would drop below 700 pixels.

In which case, Alt-tabbing should not resize the window or drop to windowed mode.

**Comment by Pointedstick** [comment]
...Or maybe the game should remember the zoom setting and re-apply it when Alt-tabbing back. I'm not yet having a lot of luck figuring out the game code around this part.
