### ISSUE TITLE
Launcher and Plugin Manager

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1904]
As part of my attempt to learn C I am attempting to build a multipurpose launcher for the game using its own source files as a starting point.

Are you fine with me doing so or would you rather make one on your own?

**Comment by Wrzlprnft** [comment]
i'd say just go ahead and make it.we'll see if it is useable or not, it is a good practice anyway. Though, i think,michael has his own plans with pluhin management.
