### ISSUE TITLE
Odd usage of SDL_GetPrefPath()

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1905]
Looking through the file handling code in the game I noticed that SDL_GetPrefPath() is used in a slightly different way than it is documented to be.

I am simply curious as to why you chose to use it this way.

**Comment by endless-sky** [comment]
GetPrefPath() is designed for grouping multiple different programs written
by the same organization into the same folder. But in this case, there's no
"organization" - or, equivalently, there's an organization that's only ever
going to produce one program. So introducing an extra level of folder
hierarchy would be pointless.

**Comment by Nechochwen-D** [comment]
Once again thank you for your reply.

Is there a better way for to ask questions like this instead of posting them here?

**Comment by endless-sky** [comment]
If it's neither a bug report nor a feature request, it should go in the [forum](https://groups.google.com/forum/#!forum/endless-sky).
