### ISSUE TITLE
New Wanderer missions

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1909]
"Wanderers: Mereti Controller" and "Wanderers: Sestor Controller"
----
Harvested a reasoning node from a Kor Mereti ship.
Tried to harvest a control transceiver from Kor Sestor ships next.
Got utterly rekt by Kor Mereti ships before I could do so.
Reloaded save.

Got the "Wanderers: Mereti Controller" dialogue.
Clicked my way through that.
"Wanderers: Sestor Controller" dialogue.
Clicked my way through that.
End.
And those two missions were cleared.

I don't think that's supposed to happen.

Unrelated (probably), but when I "properly" cleared the missions, the node and transceiver were still in my cargo.

"Wanderers: First Mereti Attack"
----
Disabled the Kor Mereti ships.
(Note: I'm not sure if I had already gotten the disabling dialog before the events below.)
Boarded and captured a Kor Mereti ship.
> As the last of the Kor Mereti raiding party is destroyed, ...

Boarded and captured another ship.
Same message.

I don't think that's supposed to happen.

Also, the Wanderer ships were nameless for some reason.

**Comment by endless-sky** [comment]
Fixed in dd35ef1 and 649db3a.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
