### ISSUE TITLE
Ability to set haze for systems

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1911]
I think it would be cool of you could set different hazes for different systems. Maybe different regions of space could have different colored haze to visually differentiate them or one could give a system thick haze for special reasons (maybe Sayaiban could have a thicker haze to make it look as though it is a cloud of nano bots)

**Comment by KiLEdEnNis** [comment]
and those huge-ass stars could get some haze as if you're in a part of that haze

**Comment by endless-sky** [comment]
Added in 280e510.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
