### ISSUE TITLE
[question/documentation] Map documentation

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1914]
Now that the map editor is a bit out of date (mining update), we either need it to be updated (which has been asked for a lot before, let me find some issue numbers*), or we need some detailed documentation on things, like, for example: https://github.com/endless-sky/endless-sky/blob/master/data/map.txt#L109 , the "belt" line, and what the numbers after mineables actually do, what habitable is, exactly, distance, period, offset, etc.

(insert asterisk here for footnote (Git turns it to bullet point)) #1156

**Comment by KiLEdEnNis** [comment]
what I really wonder is what habitable is, but distance, period & offset don't seem that hard
but still, it should all be documentated

**Comment by Amazinite** [comment]
Distance: Distance from the center of the system. 
Period: In game days it takes to orbit the system center
Offset: Number of degrees moved from the standard position (best example being Ringworlds. Without offsets, they'd all overlap eachother.)
Habitable: The distance at which planets in the system are considered in the habitable zone. (When selecting a system, orbit circles will have different colors. Red = hot. Blue = cold. Green = in Goldilocks zone. Yellow and cyan are in betweens.)

**Comment by Bladewood** [comment]
somewhat relevant: https://github.com/endless-sky/endless-sky-editor/pull/9

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/wiki/MapData
