### ISSUE TITLE
Enhancement: Game Language 

### ISSUE THREAD

**Issue by stillru** [endless-sky/endless-sky#1915]
Now game only in English. How to translate game in other language?
Most of missions just txt files. May be there should be  separate folder with other language files?
When game start - just add language selection. All translation can be done on sites like notabenoid...

I can be maintainer of Russian translation...

**Comment by jafdy** [comment]
#558 #201

**Comment by Wrzlprnft** [comment]
there are 2 problems so far: first: providing a certain quality of translation for the sheer amount of content. second: most UI elements are hard-coded, so those would need to be changed to being read-in too.
due to this sheer amount of work, the non-ascii letter support the game would need for a proper translation has been put low priority.

if you start with translating, though,  nobody will stop you, and well have something to test.

**Comment by stillru** [comment]
UI not a problem... 

Ok. I'll try...

**Comment by KiLEdEnNis** [comment]
I could do Dutch (but it would take a while; translating an entire game is aids)

**Comment by kilobyte** [comment]
Unlike some grammar-heavy games where proper translations are an epic task, Endless Sky should be manageable but it still refers to the player's first and last name in hundreds of places.  That means, in languages with noun cases, there's a fair bit of logic to implement: for example my first name Adam in English can be just "Adam" or "Adam's" (possessive) with the latter having a special case only for words ending with "s", but in Polish it's "Adam"(nom)/"Adama"(gen)/"Adamowi"(dat)/"Adama"(acc)/"Adamem"(ins)/"Adamie"(loc)/"Adamie"(voc).  And the rules used to produce these are quite regular even for real names -- now consider that so many players use the likes of "xXxHitlerBoner420xXx" that'd be notoriously tricky to inflect.  Like most native speakers, I don't know the rules and do it intuitively -- in this case I'd go with dative="xXxHitlerBoner**owi**420xXx" and so on, but it's a mess.

Most programs skip the issue by never using unquoted user-provided strings, but that's not an option for Endless Sky.  On the other hand, with pretty much just first/last name needing handling, it's humanly possible, which can't be said for, eg, translating Crawl I attempted.

**Comment by retrue** [comment]
And other problem commented here is that Endless Sky is gender neutral and most languages are not as gender neutral as English.

**Comment by kilobyte** [comment]
Well, gender is a matter of a single "male/female" choice at character creation -- if translations get in, it would be a trivial cost to pay.  I'm for one not volunteering for translation support code, though.

**Comment by AlbertNewton** [comment]
If anyone ever wanted Latin, I could do that.
