### ISSUE TITLE
Question: Is there a way to mark all the books as opened?

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1916]
One the last changes in the code mark in bold in the file manager all the new books or images that have not been open. That is good and I like it. Little problem here is that almost all my books are in bold, so right now I wouldn't be able to identify newer books just because of the bold, because almost everything is in bold.
Is there any way to mark all the books as open? So only the new books that I copy to the reader since today appear in bold until I open them?

**Comment by Amazinite** [comment]
Tfw you post to the wrong repo. 
Bold those books elsewhere. :3

**Comment by KiLEdEnNis** [comment]
why books? eww ;-;

**Comment by retrue** [comment]
I intended to post on the KOReader repo, a software to read ebooks in Kindle, Kobo and other devices.
[https://github.com/koreader/koreader](url)
