### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1920]
Error in Music.ccp at line 17. 
`|fatal error: mad.h: No such file or directory|`

**Comment by endless-sky** [comment]
I've updated the development library packages on the website to include the new MP3 streaming library; pick whichever one applies to you:

http://endless-sky.github.io/win32-dev.zip
http://endless-sky.github.io/win64-dev.zip

**Comment by Amazinite** [comment]
Thanks. 👍

**Comment by Bladewood** [comment]
danke
