### ISSUE TITLE
When offering jobs/missions, always confirm sale of ordinary commodities to make room

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1926]
Playing with current master.

I was flying a Shuttle and had a mission to deliver 12 tons of something somewhere. On Luna, I bought another 8 tons of some commodity to sell. I went to the spaceport and was inappropriately offered the "Package to Lichen" mission (my hold was full). I accepted, and the result is a cargo hold that says "cargo space free: -2 tons".

![screenshot from 2016-12-24 20-41-42](https://cloud.githubusercontent.com/assets/1097249/21469621/ce84deac-ca19-11e6-810e-8f61c9c735b6.png)

Savegame: http://pastebin.com/HBD5WKdC

**Comment by endless-sky** [comment]
When calculating whether you have space for a mission, ordinary commodities are never counted. Otherwise, spaceport missions would never show up when you're doing cargo runs unless you always sold your cargo, then visited the spaceport, then bought your next load of cargo, which would be a pain.

**Comment by Pointedstick** [comment]
That's true. In this case, it should probably either automatically sell enough ordinary commodities to make room, or prompt you to confirm this. I think it actually does do that in another circumstance, come to think of it.

**Comment by VonZorch** [comment]
It does ask if you want to sell commodities to take a mission from the job board.  It shouldn't be that hard to access that procedure from the spaceport.
