### ISSUE TITLE
Ending a conversation segfaults

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1927]
I'm seeing the game segfault every time I click "Done" to end a conversation. Probably related to https://github.com/endless-sky/endless-sky/commit/181603905497b28c403864258d4bd2935b0fba90.

To see this in action, load up [Donald McGillavry.txt](https://github.com/endless-sky/endless-sky/files/672049/Donald.McGillavry.txt), fly to Echo, and do the Quarg conversation. Happens 100% of the time for me no matter what I choose in the conversation.

**Comment by Pointedstick** [comment]
I've confirmed that reverting past that commit (or forward to current master) fixes it.

Want me to close this issue, or leave it open while you investigate?

**Comment by endless-sky** [comment]
You can close it if you want. I've decided that the change in question really wasn't useful, and I'll just update the documentation to reflect the limits on where you can pop up conversations and dialogs, instead.

**Comment by Pointedstick** [comment]
Cool, closing. In lieu of that change, what I'd really like is https://github.com/endless-sky/endless-sky/issues/1563 and https://github.com/endless-sky/endless-sky/issues/1564.
