### ISSUE TITLE
Marauder Leviathan (Engines) has electron beams

### ISSUE THREAD

**Issue by Phil-Morley** [endless-sky/endless-sky#1929]
Marauder Leviathan (Engines) has electron beams and can appear before they are developed in FW story

**Comment by Amazinite** [comment]
#872

> The electron beams are only available on two of the rare variants in the top tier of the jobs, which require a combat rating that would normally be acquired late in the fw campaign. at 20/15/10% job offer rate (in human space), available at raw c.r. 2980/4000/6000, for a 5/10/20% to spawn a variant with the e-beams. that calculates out to a 1/2.5/4.5% (accumulated) chance on landing that a job is on the board that will spawn a variant with ebeams, once the player has reached each of those c.r. milestones. then they have to disable it, without any of the toys available from the FW arc.
> 
> all of that said, it is possible for a player to do some serious grinding to get their combat rating high enough early enough, and then further grinding to draw the right ships, before those outfits are unlocked through the FW arc - if they put in that much effort (possibly more than just doing the FW story), i feel like they may actually deserve the four 'prototype' e-lasers. (i.e. it's possible that whoever modified the ship, also had enough knowhow to make a weapon similar enough to the e-beam to use the outfit as a universal placeholder.)
> 
> if the boss says so, i'll find an alternate outfit. otherwise: "happy easter!"

**Comment by Phil-Morley** [comment]
cool :)
