### ISSUE TITLE
Please add the "Draw background haze" preference to the GUI

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#1931]
Using version 0.9.4, the game ran slowly.  I edited preferences.txt changing "Draw background haze" from 1 to 0 and now it runs faster.  Could that preference be added to the in-game "Preferences" screen?

**Comment by Bladewood** [comment]
0.9.5 will have a preferences screen split into three tabs. The settings tab has the draw background haze line you are requesting.

**Comment by Amazinite** [comment]
![a3254ecc4ca64747bcf36a4bc9714c56](https://cloud.githubusercontent.com/assets/17688683/21490842/6127cf1e-cbc6-11e6-93fd-7d567ffc343c.png)
![541be76b7f3d471b964906605a7310b7](https://cloud.githubusercontent.com/assets/17688683/21490844/61d68edc-cbc6-11e6-9ad1-46cabc0c86a0.png)

**Comment by jostephd** [comment]
Thanks @Bladewood and @Amazinite!

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
