### ISSUE TITLE
Build Breaking

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#1936]
A build failure appeared since last night:

`scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/release/AI.o -c -std=c++11 -Wall -O3 source/AI.cpp
g++ -o build/release/Armament.o -c -std=c++11 -Wall -O3 source/Armament.cpp
g++ -o build/release/AsteroidField.o -c -std=c++11 -Wall -O3 source/AsteroidField.cpp
g++ -o build/release/BankPanel.o -c -std=c++11 -Wall -O3 source/BankPanel.cpp
g++ -o build/release/BoardingPanel.o -c -std=c++11 -Wall -O3 source/BoardingPanel.cpp
g++ -o build/release/CaptureOdds.o -c -std=c++11 -Wall -O3 source/CaptureOdds.cpp
g++ -o build/release/CargoHold.o -c -std=c++11 -Wall -O3 source/CargoHold.cpp
g++ -o build/release/CollisionSet.o -c -std=c++11 -Wall -O3 source/CollisionSet.cpp
source/CollisionSet.cpp: In member function 'void CollisionSet::Finish()':
source/CollisionSet.cpp:96:58: error: 'partial_sum' was not declared in this scope
  partial_sum(counts.begin(), counts.end(), counts.begin());
                                                          ^
scons: *** [build/release/CollisionSet.o] Error 1
scons: building terminated because of errors.
`

I assume another library is missing that I am unaware of?

**Comment by KiLEdEnNis** [comment]
were you testing the new collision detection system?

**Comment by gchapyzh** [comment]
@KiLEdEnNis Yes, I update and build the game twice a day, morning and evening. Its always fun to see what gets done, make for an interesting read in all the new code, and on good days, even some new textures.

**Comment by KiLEdEnNis** [comment]
to think that 1 tiny missing line can cause the entire game to crash

**Comment by gchapyzh** [comment]
@KiLEdEnNis Not really a game crash, rather the inability to build it, but yes. Quite scary.
