### ISSUE TITLE
Post-Kor Mereti pacification event: Kor Mereti ships still "speak" an unknown language

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1937]

**Comment by Wrzlprnft** [comment]
if i get it right, rek had no time to share her insight in the mereti language yet. or my brain just skipped something important

**Comment by jafdy** [comment]
The Mereti robots talk to you in the storyline at some point.

**Comment by Wrzlprnft** [comment]
i switched efret and mereti -.-
what language are the drones using?

**Comment by Wrzlprnft** [comment]
since it uses the same style the wanderers have, i'd assume the mind uses it on purpose to communicate with you.
normal ships probably still just use their old communication signals.

**Comment by KiLEdEnNis** [comment]
you merge the Mind with them, maybe it should say they learned the Wanderer language that way
but now I think of that, the translator can't translate Wanderer languaghe (weird how all Wanderer ships can speak to you; they all have to know the Hai language)

**Comment by Amazinite** [comment]
Just ran into this. Sucks not being able to ask for help while I'm sitting on the edge of a battle in Mesuket.

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/ee149795c7b33aafba4a481502ed7e91ddee5f2d. The Kor Mereti now use Wanderer hails after becoming friendly, as they believe themselves to be the Wanderers.
