### ISSUE TITLE
Light warships often have barely more weapon hardpoints than light freighters

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#194]
Some of the light freighters:
- Freighter: 3 turrets
- Argosy: 4 guns, 2 turrets
- Hauler: 2 guns, 4 turrets

Some of the light warships:
- Raven: 4 guns
- Mule: 2 guns, 4 turrets
- Osprey: 4 guns, 2 turrets
- Corvette: 4 guns, 2 turrets
- Splinter: 2 guns, 3 turrets
- Firebird: 4 guns, 2 turrets
- Aerie: 2 guns, 3 turrets

I realize that the warships generally have better shields, but their firepower capacity is oddly similar to the freighters. I'm especially thinking of the Hauler variants with their generous weapon space, which I have successfully used for major battles by jamming them full of heavy laser turrets and anti-missile turrets. Turning some of the cargo space into outfit space permitted me to add a huge reactor and cooling systems so that I never ran out of power or even needed batteries, and never overheated.

It might be a good idea to reduce the weapon space on the Hauler and increase the number of weapon hardpoints on many of the light warships to differentiate them a bit more.

**Comment by omagasohe** [comment]
This is actually more realistic than one would think, look at WWII when half the ships built were basically freighters with guns attached. In real life most small warships(frigates, corvettes and destroyers) generally have point defense and a main gun, with mostly missiles for attack.  

In game the difference for a light warship should be in the armor, shields, weapon space and engines.

**Comment by Pointedstick** [comment]
This is fine.
