### ISSUE TITLE
Description for Syndicate target practice job is a little long

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1940]
![b08f63c343ba4d689b12073e1a81e267](https://cloud.githubusercontent.com/assets/17688683/21535501/f2122b18-cd43-11e6-96d7-59575343e575.png)

**Comment by jafdy** [comment]
Only one word too long. What about "scanning it's cargo" instead of "performing a cargo scan".

**Comment by retrue** [comment]
In any case it would be "scanning its cargo". But insteat I would remove the word "that". "Be advised the target ship"

**Comment by Pointedstick** [comment]
My bad; I'll fix it.

**Comment by Pointedstick** [comment]
https://github.com/endless-sky/endless-sky/pull/1941
