### ISSUE TITLE
Some player's manual corrections

### ISSUE THREAD

**Issue by Torro** [endless-sky/endless-sky#1944]
Please review this word diff for the manual, it contains a few corrections and a small change:
n149: ...you cannot disengage [the hyperdrive] until you have reached -your destination-|+the next+ system.

[PlayersManual.md.word.diff.txt](https://github.com/endless-sky/endless-sky/files/677939/PlayersManual.md.word.diff.txt)

**Comment by endless-sky** [comment]
Fixed, except that I don't think the "close in" change is needed. That is, "closing to within weapons range..." is correct English.

**Comment by Torro** [comment]
As you wish.
I opened a question about "close to within" vs "close in to within" here: https://english.stackexchange.com/questions/365903/close-to-within-vs-close-in-to-within.
Would you like me to close this issue?

**Comment by DingusShingleton** [comment]
N.B. that "close in to within" is pronounced with a voiced "s" as in "case closed", not an unvoiced "s" as in "a closer look".

It is indeed correct english

**Comment by Torro** [comment]
Would you like me to implement _..."come withing turret range"_ in a diff as suggested [here](https://english.stackexchange.com/questions/365903/close-to-within-vs-close-in-to-within#comment853598_365903)?

**Comment by endless-sky** [comment]
I still prefer "close," because it's a more precise term. If I say that two opposing fleets "closed with" each other, that communicates their intentions in a way that "came near" does not. That is, "close" hints at a choice to engage in battle, in a way that "come" does not.

**Comment by Torro** [comment]
Okay. Closing this issue.

Happy new year!
