### ISSUE TITLE
Reloading save while cargo is in escorts

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1945]
So I was carrying about 130 tons worth of job cargo in my fleet of 3 ships, most of it being in my escorts. My escorts ended up getting left behind due to no fuel in an uninhabited system when I made it to the job destination, so I decided to reload my save to right after they got lost in the system so that I was closer to them to refuel them, but when I tried to launch, all the job cargo was on my flagship instead of my two escorts, so it told me that launching would fail the job. I then reloaded another previous save (where I was already on the destination planet) and the cargo somehow traveled with my flagship to that save and the job was completed, despite the cargo originally being in my two escorts that were still stranded in an uninhabited system.

I assume the same would occur with passengers.

**Comment by KiLEdEnNis** [comment]
what ships? if they are Quarg it could be some fancy feature

**Comment by Bladewood** [comment]
@KiLEdEnNis No.

**Comment by endless-sky** [comment]
This is the same issue as #1624: right now in the saved game ship cargo lists don't include what mission cargo they are carrying. The difficulty is that there's no unique identifier for a particular instance of a mission.

**Comment by Amazinite** [comment]
I'll close this to keep things less cluttered then.
