### ISSUE TITLE
A number of strange problems I've encountered in the latest commits

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1947]
Was messing around in an Arfecta.
Attacking with its gridfire turrets and landing a hit on anything (including asteroids) will damage yourself. (does not always self-damage in a system with low asteroid density)
Only yourself.
I kept striking a bunch of passing sparrows and they were totally unharmed.
That is, until one of them ended up on top of one of my turret mounts. Then it got rekt.
Also, up until that point, none of the sparrows were provoked. (They were merchant-owned.)

Not sure about the behavior with escort or hostile Arfectas.

----
Entered the map screen.
Screen was centered on my system.
Scrolled out.
Closed map and opened it again.
Screen was centered on a location to the northeast.
Returned to regular scale.
Closed map and opened it again.
Screen was centered on my system.
Scrolled in.
Closed map and opened it again.
Screen was centered on a location to the southwest.

----
[Save included, though I doubt its necessity due to the nature of these problems.](https://github.com/endless-sky/endless-sky/files/679424/Doctor.Hax.txt)

**Comment by TJesionowski** [comment]
I've been having these problems aswell. A useful note however, I compiled at about 9 in the morning on the 27th (december) and I had no problems with that version. So I suppose that gives us a window of commites to look at.

**Comment by Elyssaen** [comment]
I'm just looking into, and writing up an issue, for another map problem that seems to have come in commit cdb1cb881d04b246feee03dff4ec0028f34f6327. If you're looking for a commit to investigate, I'd start there.

**Comment by TJesionowski** [comment]
Good idea.

**Comment by TJesionowski** [comment]
7381bac seems to be where the problem originates...I don't know C++, so I can't find it, but I'll keep looking. (I know C rather well, so there's some overlap, but an issue like this is probably more nuanced than I can guess...)

**Comment by Elyssaen** [comment]
Yep, that will almost certainly be where the first problem originates. Sorry, I was referring to @Bladewood's second problem. Though after a bit more investigating into what cdb1cb8 does, I'm less sure it also causes the second problem here. I'll do some digging into the map problem, since you're looking at the collision one.

**Comment by endless-sky** [comment]
See if e551bfc fixes the Arfecta issue.

**Comment by Bladewood** [comment]
Error while compiling.
`C:\Users\[REDACTED]\Documents\GitHub\endless-sky\endless-sky\source\Engine.cpp|1302|error: 'InBlastRadius' was not declared in this scope|`
`C:\Users\[REDACTED]\Documents\GitHub\endless-sky\endless-sky\source\Engine.cpp|1311|error: 'InBlastRadius' was not declared in this scope|`

**Comment by endless-sky** [comment]
Sorry, I shouldn't try to fix bugs this late at night.

81ac71b should fix the Arfecta bug, and 1969cf6 should fix the map panel.

**Comment by Elyssaen** [comment]
81ac71b seems to work. And damn, I just figured out what was going on there. Messing about I spent ages being confused by what the position of a beam projectile is in the code... think I finally get it.
