### ISSUE TITLE
Map crashes: array out of bound

### ISSUE THREAD

**Issue by Elyssaen** [endless-sky/endless-sky#1948]
cdb1cb881d04b246feee03dff4ec0028f34f6327 (map code clean-up) seems like it introduced a problem when clicking Friendly/Outfitter/Shipyard/(has been visited).

Things go wrong on line 212 of **MapDetailPanel.cpp**, in the Click function.

`SetCommodity(SHOW[(y - it.second + 30) / 20]);`

I'm not sure why the change to this condensed form was needed: it was much easier to read what it was doing before, and to me this is a bit obfuscated.

It's also not giving the right values. The expression advances along the array at the right pace, but it begins at SHOW[3] instead of SHOW[0] because you have an intercept at 2*30/20, not 0.

This can be seen in-game as follows: 

1. Click "Friendly" in the top left of the Map, and a marker will appear over "(has been visited)". It's going to the location set up to be SHOW[3], not SHOW[0].
2. Click "Shipyard" and a marker will appear over "Food" (we're into undefined behaviour).
3. Click "Outfitter" and the game will outright crash in Release mode. Debug mode doesn't crash but draws no marker.

If the code _has_ to be in this new condensed form, this seems to work:

`SetCommodity(SHOW[((y - it.second + 30) / 20) - 3]);`

But also... doing this seems to have involved destroying ListShips() and ListOutfits(), which popped up helpful information. I'd rather have it back the way it was, personally!

**Comment by endless-sky** [comment]
Fixed in 4e84815.

The ListShips() and ListOutfits() were an old, undocumented feature that was added before the outfitter and shipyard maps existed. I don't think they served much purpose once a better way of figuring out what planets sell each item was introduced.

**Comment by Elyssaen** [comment]
Too late at night for me yesterday, I should've seen that the +30 was supposed to be -30 in the first place.

I think those features still had some use, but okay. Can I ask, why the change to this SHOW array anyway? It definitely isn't as clear what it's doing.

**Comment by Elyssaen** [comment]
Okay, based on this being marked as done I take it you don't want to talk about this further. Closing the issue.
