### ISSUE TITLE
Free Worlds mission balance

### ISSUE THREAD

**Issue by eli-lumos** [endless-sky/endless-sky#195]
Hi,

I think there could do for some balancing in the Free World storyline.

I'm referring specifically to the mission where you have to take back the system that the Navy takes over, which has Katya on a moon.

I found it completely impossible to win this mission. I started with a tricked out Argosy, no luck. So I flew over into Republic space to buy a Falcon, the best ship I could afford (and at the time I thought the best ship available to me). Getting through this part of space was a pain because now everyone in the galaxy hates you.

Even with that ship, I failed, and I was also unable to upgrade it how I liked since stuff like Atomic engines is through far too many hostile planets.

Eventually, I created a plugin to make a ship with 9999999 shields. It was the only way I could do this. I would say that maybe I would just need to gather more money and hire a fleet (which is pretty grindy), but since almost all of space becomes off limits, this alone is very difficult.

The 2 missions following this one were overly irritating and difficult, especially with a slower ship (no atomic engines, remember?). Flying through Republic space 12 jumps or so, without being able to land (a bug would not let me land OR bribe), meant I had to keep trying and get lucky to make it through. The trip back was even worse.

I figured these were the finale missions since they were so difficult, but then things slowed down again, AND you start to unlock superior tech after this battle. It just seems so out of place and totally in the wrong location difficulty curve-wise.

Suggestion: 1.5x the fleets on the Free Worlds side, or get rid of the particle cannons for the Republic ships, or both.

Also: look into the bug where you couldn't land in the following mission. And probably don't add any additional mission units that attack you, since this is already difficult enough.

**Comment by endless-sky** [comment]
Are you sure you were not able to land? What should happen is that when you hail the planet, you are automatically granted clearance (the hailing panel will say "Alondo has a brief chat with the spaceport controller and manages to get you permission to land.") If you didn't read the message, you might have just seen that "Offer Bribe" was greyed out and not realized it was because Alondo had already negotiated with them.

Those intro battles are both designed so that even if all you do is run away, the Free Worlds will still win the battle (usually). I've tested them both in a "souped up Argosy," and the only difficult part was getting clear of the planet in the first battle to avoid being the main target.

**Comment by eli-lumos** [comment]
Ah yeah I realized in hindsight that probably I was able to land. Then a suggestion tied to that: change the string from "We don't want your money" to "No need to pay, you're already cleared to land." The former I took as that I was so hated that I couldn't even bribe them. The latter is very clear.

Regardless of being able to refuel, it proved incredibly difficult to avoid getting exploded as I was jumping.

As for the battle balance – the first intro battle worked just as you described. I saw that I didn't really need to do much, just avoid death, and we won. The second battle was completely broken, however. I wonder if there were already a bunch of ships in the system, on top of the mission ships, or something. The very first time I tried it, there was a single Carrier left (if not a carrier then whatever the biggest one is). I almost beat it, but its particle cannons meant I couldn't outgun it in any way. So I tried again. From that time through to the next 15 or 20 times I tried, the Free Worlds fleet was obliterated and there would be 3-5 capital ships and a handful of gunboats left. Every single time.

So I really feel you should add a ton more ships into the second intro battle, and also reduce the fleets hanging around in the republic systems when jumping back from Syndicate space (jumping to it was fine, for whatever reason).

There is a Steam thread about both of these missions being overly difficult, so I'm not the only one:
http://steamcommunity.com/app/404410/discussions/0/496880203074006632/

I think I'm almost done with this storyline (I've met the Pug), and these two missions were the only ones that felt broken and/or insurmountable.
