### ISSUE TITLE
Additional fire mode.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1950]
Could you add a semi-automatic firing option in preferences?  This would be, you need to press the fire key to fire weapons but the system would only fire weapons that could actually hit your selected target.

**Comment by Elyssaen** [comment]
Seconding this. It'd really help when you have a loadout like Ion Cannons and Quarg Skylances, and can't power both at once but can rarely _hit_ with both at once.

**Comment by endless-sky** [comment]
I'm worried that if a new player got into that mode by mistake, they'd be rather confused at why they press the fire key and nothing happens. With full automatic firing, the fire key still overrides it, so there's no such source of confusion.

**Comment by Elyssaen** [comment]
Do you think we could find a way around that confusion? It would be really useful to be able to decide not to burn energy trying to fire a weapon that can't hit, i.e., Quarg Skylances when you're battering someone with Ion Cannons, or Ion Cannons when you're circling around in close and want to hit with Skylances.

**Comment by DingusShingleton** [comment]
Firing mode hotkey? Toggle between "fire everything" and "fire when in range"? Although, that won't help with not firing ion cannons when in skylance range...

Now you are talking about selectable firing groups which is a whole nother can of worms

**Comment by endless-sky** [comment]
If you want to avoid wasting energy, the existing auto-fire mode already does that.

Given how complicated the existing game mechanics, settings, and controls always are, I'm just hesitant to add more complication unless there's a really good use case for it.

**Comment by Tadrix** [comment]
Maybe simply switching between two sets of weapons could work? I.e. at outfitter, if player so chooses, weapon can be dedicated to set 1 or set 2. When pressing fire button, only one of these sets fire. Set could be changed via another button. Or just give players the option to designate a weapon as secondary weapon. These change nothing to those who don't need that option.

**Comment by VonZorch** [comment]
@endless-sky But the autofire mode does not give you the option to stop firing.  This would make boarding missions impossible.  If you carry a mix of weapons with different ranges such as particle cannon and anything else you can easily overheat your ship before you close to say electron beam range.  Running the guns through the existing autofire filter should be a trivial task, no more than a procedure call.
Your problem with confusion is why I asked for it to be in preferences.  Add a tooltip that specifies what the behavior of each mode is.

**Comment by KiLEdEnNis** [comment]
if your ship easily overheats before you get your turrets to fire, you're doing something wrong

**Comment by VonZorch** [comment]
@KiLEdEnNis I don't overheat before my turrets fire, I overheat because the turrets are firing uselessly while I'm attacking an enemy at long range.

**Comment by jafdy** [comment]
That's why most people use auto fire @VonZorch.

**Comment by VonZorch** [comment]
@jafdy Which doesn't give you the option of not firing.

**Comment by Elyssaen** [comment]
There's something I'd like to try my hand at, at some point. It's more complicated than anything I've tried so far, but I think I could get there.

The gist is: enable firing more than one secondary weapon at once. Right now, the AI can do it, but the player can't, and it means you can't really use different secondary weapons effectively. The best solution I can think of would involve a new pane in Player Info allowing you to set up fire groups, so one fire group might contain more than one secondary weapon.

If I try something like this, it _might_ end up being only a little bit more work to make it so primary weapons are included too. Then all primary weapons would by default fire with Space, but you might be able to reconfigure some to fire like secondary weapons.

**Comment by VonZorch** [comment]
Nice idea.  Perhaps put icons for all secondary weapons your ship has on the display and make them checkboxes.

**Comment by Elyssaen** [comment]
I'll make a note to post back here if/when I get to it. We're not talking any time soon though, sadly. Doing it right will take a while, and I'm writing some story stuff right now.

**Comment by Pointedstick** [comment]
>  If you carry a mix of weapons with different ranges such as particle cannon and anything else

Then the current auto-fire behavior will first start firing the particle cannons once a target comes within range of them, and will avoid firing the other guns until the ship is within range of them, too.

I don't see what the actual problem is that's not already solved by using auto-fire.
