### ISSUE TITLE
New fleet order, Rescue

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1953]
Tells fleet to go aid crippled friendly ships.  The AI does it now for NPC ships, but it doesn't for fleet ships.

**Comment by endless-sky** [comment]
Your escorts will repair each other once the battle is over (i.e. once there are no more non-disabled hostile ships in system).

**Comment by KiLEdEnNis** [comment]
to be fair an option that lets them repair any friendly ship could help

**Comment by VonZorch** [comment]
KiLEdEnNis, that is exactly what I wanted.  I apparently wasn't clear.
