### ISSUE TITLE
Additional talk option, Ships

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1957]
Please add an ability to issue threats and ritual grimaces to ships.  perhaps add a modifier such as ctrl-T to respond to the last ship that hailed you.  It would really have no real effect on the game but it makes for good role play.

**Comment by endless-sky** [comment]
The feature already exists, but it's done via voice commands; there's no keyboard command for it. Don't worry, even though no notification shows up on the screen, the ship will definitely hear you and feel intimidated. :)

**Comment by KiLEdEnNis** [comment]
besides, THAT is what makes it roleplaying
