### ISSUE TITLE
Republic Navy Behavior

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1958]
It seems odd to me that the Republic Navy, after the actual shooting in the civil war stops, is patrolling deep in Free Worlds space acting like they are in charge when they are clearly out of their jurisdiction.
Especially the constant scanning, Scanning a military ship in their home space by a foreign navy could easily be taken as a hostile act, and after the war my ships are still in Free World colors and I'm still getting paid.

**Comment by DingusShingleton** [comment]
After the war you are no longer a military officer, the payment you receive is a stipend to honor your huge contribution to the war. But you are a civilian.

**Comment by Amazinite** [comment]
How deep into Free Worlds space? I've only ever seen them around the border systems, and even then it's super rare for them to spawn.

**Comment by endless-sky** [comment]
It seems odd to me that the US routinely has some combination of drones, spy satellites, planes, and cyber-espionage going on in countries we're not technically at war with, but that doesn't stop them from doing it. The Republic is basically the same way: they're big and powerful enough that they don't even have to hide the fact that they're engaged in ongoing surveillance of the Free Worlds, and there's very little that the Free Worlds (even after the armistice) can do about that.

Besides, if you extend maritime law to space, the way it would work is that anything not within some distance of an inhabited planet is "international waters." That is, there could be reasonable arguments for not allowing a government to restrict what ships are allowed in a given star system, but instead only to restrict who can land on their planets.

**Comment by VonZorch** [comment]
I've had it happen is the Pherkad system, and every time I go through Aldhibain or Dschubba there's either a capital ship with 2-3 escorts or several Gunboats and Rainmakers.

**Comment by KiLEdEnNis** [comment]
that's no surveillance fleet, and is a bug then (I've had that issue with Lesath, the empty system right of it, which is fixed)

**Comment by VonZorch** [comment]
I must need to download a new version.  I get them in Lesath.  I didn't mention it, as being empty and near the border, I considered it neutral space.

**Comment by KiLEdEnNis** [comment]
depends on the part in the storyline, I got it after all those systems joined and Lesath was like 4 jumps off of Republic space

**Comment by VonZorch** [comment]
In my game Rastaban and Girtan, just off Lesath, are still Republic
