### ISSUE TITLE
Version 0.85, OS X 10.11: No graphic for Antipode (Matar system)

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#196]
<img width="1280" alt="no graphic" src="https://cloud.githubusercontent.com/assets/1097249/11138720/0ef0bbba-8983-11e5-86bb-534ec42e59d6.png">

**Comment by endless-sky** [comment]
You're sure it's release 0.8.5, not 0.8.4? I thought I had fixed this bug in that version.

Also, if you're running 0.8.5, you should upgrade to 0.8.7 as soon as possible, since 0.8.5 turned out to have a bug that made fighter bays stop working.

**Comment by jafdy** [comment]
How do you get the new versions? And how do you get the editor as well come to think of it?

**Comment by Pointedstick** [comment]
Yes, I'm definitely using 0.8.5:

<img width="307" alt="version" src="https://cloud.githubusercontent.com/assets/1097249/11147369/a5604e04-89d2-11e5-9fd3-5d0059d83c9d.png">

**Comment by Pointedstick** [comment]
OK, I can confirm that it's fixed in 0.8.7. Thanks!
