### ISSUE TITLE
Discretion being the better part of valor.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1960]
Maybe you could add a little risk assessment to the AI.  A lone pirate Sparrow charging a fleet of 45 capital ships, I've had this happen, or a merchant Star Barge with a blaster turret charging a pirate Leviathan, one of my escort missions, is just wrong.
This would also make the bounty missions more challenging.

**Comment by endless-sky** [comment]
Bounty missions would be super annoying if all your bounty does is try to run away from you, especially if it's a fast ship.

The AI already does have risk assessment code - anything but a "heroic" ship will refrain from attacking a stronger force unless it is already within weapons range.
