### ISSUE TITLE
Some technical points

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1961]
Some things from the real world.
Turrets carry much of their mass and thus outfit space outside the ships hull.
Gatling guns are still in use over 150 years after their invention not just for their high rate of fire but also for their ability to deliver that rate for as long as ammunition can be supplied.  They do not have overheating problems as the multiple barrels gives each barrel time to cool between shots.  The reason they are used in bursts is to extend the time before running out of ammo.

**Comment by Elyssaen** [comment]
...some description might be helpful. : )

**Comment by DingusShingleton** [comment]
Air is a mach better thermal conductor than.... nothing. The barrels of a gatling gun are in vaccuum. Thus, overheating is a thing.

**Comment by Elyssaen** [comment]
Heat is a _much_ bigger problem in space, as Dingus says, but this applies to every weapon. Still, I think the Gatling Gun is plausibly a series of coilguns, and the problem here is each coil would get too hot – hence, the Gatling arrangement.

**Comment by endless-sky** [comment]
All the weapons are tuned for balance, not for realism. Turrets are the size they are because it would make no sense for your ship's weapons to be tiny compared to the other outfits.
