### ISSUE TITLE
Tune scanning mechanics (time and range) to make avoiding scans more challenging

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1962]
As far as I can tell right now, if two ships scan you at once then they each independently scan you with their own scan times. Even with pretty weak engines, you're still able to warp out of systems before being scanned with illegal cargo. Maybe when multiple ships scan you at once, their scans should combine and the time should be reduced somewhat (not as much as if one ship had multiple scanners, though).

**Comment by KiLEdEnNis** [comment]
still, it'd be weird if 2 independent scanners scan & speed up because they both scan
instead making better scanners or something? idk

**Comment by Amazinite** [comment]
> it'd be weird if 2 independent scanners scan & speed up because they both scan

Well I imagine that the two ships would communicate with each other that they are both scanning the same ship, and therefore they each scan different parts so that they can get the scan done faster, so I don't see how that's weird.

> instead making better scanners or something? idk

Stacking scanners on the same ship already decreases scan time and increases range, so better scanners wouldn't need to be made.

**Comment by KiLEdEnNis** [comment]
then maybe adding an extra one to the gunboats if they have room? most AI ship variants have empty space

**Comment by DingusShingleton** [comment]
That's what I suggested in the other thread where this came up. I think if some of them had one and some of them had two it would strike the proper balance. But that's alot more work of course.

**Comment by Elyssaen** [comment]
I think I prefer the 'some have two' idea. Your point about them stacking on the same ship makes sense, my main concern is that getting ships talking to each other like that might be a pretty hefty investment of time for something that could be solved a more simple way.

**Comment by Amazinite** [comment]
If we go with the double-up-on-scanners idea, I'll just add that into the PR.

**Comment by DingusShingleton** [comment]
Word. So the only question is how many should have two scanners? Do you think a 50% chance to get fast scanned would set the risk reward at an appropriate level?

**Comment by Amazinite** [comment]
Nice

**Comment by whismerhill** [comment]
a few things on the scanning :  (not sure I should add this there, or make a new issue)
I was unable to escape scanning ships just by trusting & getting very far away from system center, e.g. it seems the pursuing mechanics for scanning go farther than attacking ?
I was trying to stay in system to refuel some of my stranded fleet ....

pressing the "trust" key, made the "fine" window disappear immediately in a few milliseconds.

**Comment by Amazinite** [comment]
Just a heads up, I originally made this issue before I'd realized that ships would never finish scanning, so I will have to revisit the pirate jobs to see if scanning is good as is now.

**Comment by Amazinite** [comment]
So I've been testing the scanning in order to see how it is right now.
I used the Modified Argosy to test this as it's the best ship pirate's sell for cargo (testing this assuming the player is taking pirate jobs).
I hyperspaced through Sirius to Alphard and back, given that these are some of the straightest systems and therefore it takes the longest time to travel through with a normal hyperdrive.

With an acceleration of 170 and turn of 121 (using the biggest atomic engines the Mod Argosy could fit, prioritizing turn over thrust, but keeping all other outfits default), I was unable to run from scans assuming they got on me as soon as I entered the system, or shortly after. I then stripped the Argosy down to the bear minimum, using only a power source (NT-200), a Hyperdrive, a supercapacitor, and the engines. This boosted my stats to 175 turn and 240 acceleration, but even at this speed I would still be scanned if instantly locked on to.

I then switched from trying to go high turn/acceleration to using a Scram Drive (great for straight systems) with the default Mod Argosy engines (60 turn, 112 acceleration), and no matter how fast ships seemed to get a scan lock on me, they were unable to scan me assuming I was just passing through the system, but as soon as you try and come in for a landing, if there is any ship with a scanner nearby then you're getting scanned.

I then tested the Scram Drive in one of its weaker areas: systems with tight angles. With 170 turn and 234 acceleration, I traveled between Vega, Sol, and Altair over and over again, and on tight angles like this you'll get scanned.

So as it is, barring the use of interference plating, the only way you're ever going to be able to avoid scans is if you're using a Scram Drive and the systems you're going through are all pretty straight, or at least there are no wide angled turns. The wider the angle, the faster your ship needs to be.

**Comment by MCOfficer** [comment]
jump drive will work though. but it makes it hard on longer distance since you have to land and gather fuel more often. seems balanced to me.

**Comment by KiLEdEnNis** [comment]
just note that a jump drive isn't as easy to get

**Comment by Amazinite** [comment]
Given that I originally made this issue when scanning was broken and things seem fine now, I'll close this. Avoiding scans is very challenging without interference plating, so someone taking lots of pirate jobs is going to need to spare some outit space for interference plating if they don't want to get fined.
