### ISSUE TITLE
Dead ships can be highlighted

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1963]
![fc4db56e6c63496f9491d4473f8ebdb1](https://cloud.githubusercontent.com/assets/17688683/21579492/aada69f6-cf80-11e6-952b-db57aadfa9f0.png)

The blue square is just the only living one. The rest are dead ships that I can still highlight.

**Comment by endless-sky** [comment]
458b161 should fix that.

**Comment by KiLEdEnNis** [comment]
enjoying the new mode I see
if I knew how to build from source I would too ;-;

**Comment by friagram** [comment]
Dead ships will also continue to be the selected target and shot at if you have locked onto them with a turret and hold shift... If your ship only has turrets, and you are expecting it to de-select the ship and fire straight (so you can kill off some other dead fighters or something quickly).

Not sure why this behavior is there, I don't think the exploding husk can be moved or anything by being shot at.. Though that might be neat. Mabye it does work, like with some of those red kor lasers that push things away. Though, you can't select a dead ship to fire turrets on if it didn't have some hull left before you started firing.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
