### ISSUE TITLE
Post-pacification Kor Mereti and reputation

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1964]
After the Kor Mereti become friendly, it is apparent to me that the only thing that can permanently lower their reputation is an attack on the Wanderers, because of the way reputation works when it comes to automatons. Otherwise, no matter how much they are attacked, they will never become permanently hostile. This also means that splash damage weapons will never turn them hostile either.

**Comment by endless-sky** [comment]
The game counts on killing automata never affecting your reputation, e.g. when you get the surveillance drone hunting mission for the Free Worlds. So, there might need to be a work-around for the Mereti, like adding a ship attribute that increases its effective crew complement for the sake of altering reputation.

**Comment by jafdy** [comment]
Have some way of getting Meriti weapons without killing friendly Meriti before you add that attribute to the ships.

**Comment by KiLEdEnNis** [comment]
reputation lowers per amount of crew killed, that's why robots don't become (more) hostile, and that's why you get a giant reputation boost w/ the Syndicate by killing a couple of World Ships

**Comment by endless-sky** [comment]
I've got a plan for a whole string of side missions where they ask you to fetch exotic plants and animals from around the galaxy, and as you build up a friendship with them they start making their technology available for you to buy. (Although, I'm not sure if they should see their "ships" to you, because those are really their own bodies. They would have to manufacture a different set of ships that are not "inhabited" by a Mereti mind.)

**Comment by KiLEdEnNis** [comment]
> Although, I'm not sure if they should see their "ships" to you, because those are really their own bodies.

why not? some humans do it

**Comment by DingusShingleton** [comment]
While yes some humans sell their bodies (almost all of them depending in your view of labor vs capital), I don't think any of them are selling their bodies *to be lived inside by someone else*

**Comment by DingusShingleton** [comment]
Wait a second, does this mean that if I capture a mereti ship and put a command center in it, I'm living in and controlling a sentient being? o.O

**Comment by KiLEdEnNis** [comment]
sentient? only after the Mind got merged

**Comment by Elyssaen** [comment]
> The game counts on killing automata never affecting your reputation, e.g. when you get the surveillance drone hunting mission for the Free Worlds. So, there might need to be a work-around for the Mereti, like adding a ship attribute that increases its effective crew complement for the sake of altering reputation.

Perhaps some kind of "living ship" attribute, that could also be used for the Archon? Reputation changes could then be based on both crew _and_ the "living ship" attribute, and the Archon could more logically have no bunks or required crew.

If the sapient Mereti fly variant versions of Kor Mereti ships that have the "living ship" attribute, they could sell you the base versions that don't, and say that they're selling you the technology without a Mereti mind inside it, but that you'll need to install a Command Center if you want to fly it yourself.

Also, would you consider having some non-sapient Kor Mereti (" Kor Mereti ") continue to show up? Call me a pest, but from a gameplay perspective it's a little sad that right now you completely lose access to looting Mereti technology. I'd happily write a little PR that gave " Kor Mereti " a rare fleet presence here and there, representing some unconverted automata.

**Comment by DingusShingleton** [comment]
Ok, clearly there is some serious content that I have not done yet lol. But for the record all this sounds totally awesome.

**Comment by Wrzlprnft** [comment]
how about a flag behind the scenes which sets the reputation calculated for a ship the same way as combat rating is?

**Comment by Bladewood** [comment]
@Elyssaen I agree with that last paragraph.

**Comment by jafdy** [comment]
@Wrzlprnft This risk of that is that with higher tiers the reputation fluctuations are much greater. I prefer the "Living Ship" idea better.

**Comment by KiLEdEnNis** [comment]
with the "Living Ship" or in ship stats "living", the value after "living" (for example 20) could represent 20 crew members, so you would lose reputation s if you killed 20 crew members if you destroy that ship
