### ISSUE TITLE
AI prioritizing flotsam over fighting enemies

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1967]
It just seems a little weird to me when I'm fighting a pirate, and every so often, it just dashes off to somewhere and then back to our fight.

**Comment by endless-sky** [comment]
That's to make it so that you can dump cargo to distract pirates.

**Comment by Bladewood** [comment]
Then, I think it should be made more obvious, such as by making their ship icons yellow rather than orange.

**Comment by Bladewood** [comment]
Also, this tends to make it such that every time you destroy a ship when you are fighting a group of pirates, the other pirates will always be "distracted," making it much easier to destroy them in turn.

**Comment by endless-sky** [comment]
I suppose I could tighten the range in which the AI looks for flotsam, so it will generally only pick it up from very close to the ship or asteroid that it is currently attacking.

**Comment by endless-sky** [comment]
See if 8014a2e feels like a good balance to you. I made it so that ships only pick up flotsam that they're either pointed toward, or very close to. That seems to reduce the chance of pirates getting distracted, while still allowing you to dump your own cargo to distract them.

**Comment by Bladewood** [comment]
A bit too large of a range imo.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
