### ISSUE TITLE
Game crashes when Dxtory turns on recording hooks

### ISSUE THREAD

**Issue by utoxin** [endless-sky/endless-sky#1968]
I'm a small-time youtuber, and started recording a new series this weekend. In the process, I discovered that the game crashes when Dxtory hooks in to record. I was able to get around it by using OBS Studio to record instead, but I'd love to see this crash get fixed.

I'm not sure what else I can provide to help you with this issue. Is there a crash log I can upload? I didn't get any visible error messages, the game just crashes as soon as Dxtory hooks into the graphics stack to record.

**Comment by Wrzlprnft** [comment]
as far as i know there is no error log file for engine crashes.
what version of the game are you using?

**Comment by utoxin** [comment]
0.9.4, I think? Running it from steam, with the Beta branch selected.

**Comment by Wrzlprnft** [comment]
“Since Dxtory does not support a very new OpenGL API, so there is that possibility.“

http://forum.exkode.com/index.php?PHPSESSID=3sj3n1u1180tq4l1d52gp8r170&topic=1264.0

looks like it is a compatibility issue on dxtory's end rather than ours. appears to happen to more than just this game.

**Comment by utoxin** [comment]
Thanks for looking into it. I'll pursue it from that end. And you're correct that ES isn't the only game that it's happening for. I hadn't succeeded in finding that thread however. :)

Thanks again! I'm loving the game so far. Huge amounts of nostalgia, since I played every version of EV when they released. :)
