### ISSUE TITLE
Suicidal pirates

### ISSUE THREAD

**Issue by eli-lumos** [endless-sky/endless-sky#197]
It occurs to me, it could be interesting to come up with a plot reason why the pirates are often so suicidal. I'm talking about the times when I fly into a system and a single interceptor tries to kill me. I am flying a Shield Beetle, I've fought in several wars, and have a well-known combat and political reputation.

This guy's not a pirate, he's a psychopath.

So it got me thinking... since the storyline tries to humanize the pirates (which is cool), why are some of them so completely bonkers? Maybe something like the Reavers from Firefly? It might also be good to add some retreat AI to some of the pirates, where they don't even try if you have a sufficiently large ship or a high enough combat reputation.

As you flesh out more of a pirate storyline, this could be a cool element to add.

**Comment by Pointedstick** [comment]
Yeah one thing I liked about EV Nova was that a lot of times Pirates would run away from you, especially if your fleet outnumbered them or if you had a huge powerful ship. Made them seem a little more like people and less like video game enemies.

**Comment by Phezzan** [comment]
I've added this in my fork, but it's a little annoying.
You start winning, target's shields drop... it turns and poof - hyperspace.
You get about 3-5 seconds against weak targets so if you can disable a ship in that time, you get a prize.  
The AI doesn't consider the power of the fleet - only its chosen target - so 'outsmarting' it is basically cheating.

**Comment by eli-lumos** [comment]
Haha that's cool. Yeah, I wasn't even thinking a gameplay change was necessarily required. Maybe a combination of both a gameplay change and a story element.

For example, if we're talking Firefly universe, some attackers may be Reavers (so they behave like suicidal psychopaths), whereas other times it'll be pirates out for the dough, who would run from a warship.

**Comment by endless-sky** [comment]
There's a change in commit b808836 that makes ships less likely to seek out a fight if they are vastly outnumbered. That should address the main issue here.

**Comment by Pointedstick** [comment]
Yes, and I've noticed that pirate ships seem to try to run away if they're about to die. Welcome changes.

**Comment by endless-sky** [comment]
Included in release 0.8.10.
