### ISSUE TITLE
new mineable asteroid sprite type [enhancement]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1973]
use a 3D model of an existing ship (possibly with "damage" modifications), with the camera rotating about it on a "derelict" axis...

appears in remote systems, yields appropriate materials...

originally proposed:
http://steamcommunity.com/app/404410/discussions/2/154645539343705420/

**Comment by Amazinite** [comment]
(invoking the spirit of Kiko)
I'M WORKING ON IT!

**Comment by Amazinite** [comment]
I'll actually try and finish up what I started and create damaged ships sprites. The ships I've used for the debris were small ones. That is, all the interceptors + the two shuttles, the Flivver, and the Star Barge. And I think it would make sense to add in fighter and drone debris as well, unless people find that too unrealistic given how much they supposedly die. :)

**Comment by LocalGod79** [comment]
lol - throw in a Scout, and maybe Arrow - sounds awesome!

**Comment by Amazinite** [comment]
Forgot the Scout was already in there as well, but I'll add the Arrow in with the rest of them. :+1:

**Comment by Amazinite** [comment]
Should these only drop minerals (mainly stuff like iron and aluminum, or whatever else is likely to be in the ships) or should we go the full way and also do the damaged outfits thing?

**Comment by LocalGod79** [comment]
i don't see why not - damaged outfits are not more valuable per ton than other mineables...

**Comment by Amazinite** [comment]
I made [this spreadsheet](https://docs.google.com/spreadsheets/d/1P1D9y6zaXqxeFZFz-9wr-tUVomGQukWR3KtEs2J3aQk) a while back when starting this off that has all outfits with their per ton values. Stuff highlighted yellow is unlocked through the story. The first section is normal value and mass with normal per ton value, and the second one is the damaged section (along with the variables that make damaged outfits have half the cost and 3/4ths the mass). The last set of columns are for outfits I labeled "salvageable," which are installable but less efficient than their normal variants. Assuming we only add small ship debris into the game, most of the more valuable damaged outfits wouldn't need to be used, and therefore the value of most damaged outfits that you can get would be around that of minerals when looking at it per ton.

**Comment by Amazinite** [comment]
[Here](https://github.com/Amazinite/Enigma-Corp/blob/master/data/space%20junk%20-%20minables.txt) is the file I made that has all the space debris stuff in it. The different letters are just different variants.

**Comment by LocalGod79** [comment]
perhaps remove some of the higher value/ton items?

these ships shouldn't be terribly common, would they?  i haven't actually played in a long time, and my initial experiences with asteroid mining were somewhat frustrating...

**Comment by Amazinite** [comment]
Well with just the smaller ship variants, the most valuable things you're going to find are atomic engines (tiny and small sized), which are on the rarest variants and not even a guarantee to drop. Aside from that, the only other outfits that can be dropped from the small ships that are more valuable per ton than ores are jammers, scanners, and super capacitors. Most of the rest of the outfits are below 3000 credits/ton, which is more than most ores, but then there's the fact that these space debris aren't as common as ores, and what drops doesn't drop in as high of a quantity.

**Comment by Amazinite** [comment]
Started working on some damaged ship looks. How's this for the Sparrow?
![damaged sparrow 2x](https://cloud.githubusercontent.com/assets/17688683/21624155/d6ea905c-d1d3-11e6-88f5-9051676345af.png)

I removed a few parts, bent up the wing, rotated some things as if they were loose, then added rust and lightened the paint in Gimp so it looks more aged.

**Comment by Amazinite** [comment]
@2x sprites
![damaged shuttle 2x](https://cloud.githubusercontent.com/assets/17688683/21628263/22828444-d1ec-11e6-946a-a04bb91d3975.png)
![damaged sparrow 2x](https://cloud.githubusercontent.com/assets/17688683/21628269/229ece74-d1ec-11e6-8e1a-267a8ebfb96c.png)
![damaged star barge 2x](https://cloud.githubusercontent.com/assets/17688683/21628264/22978e52-d1ec-11e6-8768-f7e784cb33dc.png)
![damaged wasp 2x](https://cloud.githubusercontent.com/assets/17688683/21628265/22983ea6-d1ec-11e6-94c9-a77d8363e375.png)
![damaged hawk 2x](https://cloud.githubusercontent.com/assets/17688683/21628266/2298b69c-d1ec-11e6-8bb8-47ce17c1216d.png)
![damaged heavy shuttle 2x](https://cloud.githubusercontent.com/assets/17688683/21628268/229cd7e0-d1ec-11e6-8cfd-b0cf8140fcf8.png)
![damaged lance 2x](https://cloud.githubusercontent.com/assets/17688683/21628267/229ad4d6-d1ec-11e6-9107-11fdbd8b7bf6.png)
![damaged scout 2x](https://cloud.githubusercontent.com/assets/17688683/21628270/22a54b50-d1ec-11e6-8cc4-4efb26465fa9.png)

Gonna do the rest tomorrow.

**Comment by Wrzlprnft** [comment]
rotation? as in: do they rotate, or will all of them point upwards?

**Comment by Amazinite** [comment]
That would take a lot more time, but I like the idea. My only fear is that it would take a LOT of separate sprites to make a smooth rotation, because asteroids as is are pretty homogenous around their surface, so the alpha blending still looks pretty good with just a few frames, but an entire rotating ship would need a lot to not looks blurry or bad.

**Comment by LocalGod79** [comment]
this *was* proposed as an additional asteroid sprite - it should "tumble" the same way that asteroids do...

**Comment by Wrzlprnft** [comment]
honestly, if a few are more drifting and less tumbling,that's cool. but the different ships should not point in the same direction(top)

**Comment by KiLEdEnNis** [comment]
how do their hulls bend instead of having holes in it?

**Comment by Amazinite** [comment]
Going to touch up the current 8 sprites when I get home, then do the other 7, then post them all here. If they're all good, I'll do all the animation frames for them.

**Comment by Wrzlprnft** [comment]
if you send me the assets i can do a bit of the rotating, too. a writer's/artists block does not block the ability to do just work ^^

**Comment by Amazinite** [comment]
There's 15 ships total, so one of us could take 7 and the other could take 8. Also, I did the merchant coloring in Gimp. It might be helpful to transfer that over to Blender to cut down on the work each sprite needs. :)

**Comment by Amazinite** [comment]
![damaged ships](https://cloud.githubusercontent.com/assets/17688683/21662843/430082c0-d2aa-11e6-86e0-df5c4116e13e.png)

**Comment by Amazinite** [comment]
@Wrzlprnft @LocalGod79 
Kiko and I have been talking about using the Discord chat more often for easy collaboration between groups. It would be especially helpful compared to Steam because of how Steam doesn't save chat history while Discord does, and file sharing is easy on Discord, as well as the fact that it facilitates easy file sharing straight through the website itself (it maxes out at 8 MB file sharing, though, so some larger .xcf files would need to be shared through Google Drive).

**Comment by Amazinite** [comment]
Something is either up with my game or with Gimp, because every new sprite I make now shows up partly transparent and unatargetable in game, but only the new stuff.

![32404ea9ce394f289adca947da6b45b1](https://cloud.githubusercontent.com/assets/17688683/21663909/249bc108-d2b1-11e6-9f13-1795649be209.png)

**Comment by toilethinges** [comment]
Yeah, the sprites are not damageable for me either, and the frame glitch is happening too. Otherwise, with post processing, will look great!

**Comment by LocalGod79** [comment]
@Amazinite try naming the first 10 sprites "shuttle~00", "shuttle~01", etc...

**Comment by Amazinite** [comment]
That fixes the frames thing, but the sprite is still transparent and unhittable.

**Comment by Amazinite** [comment]
Before I can do anything else right now, I need to figure out why the sprites are showing in game as transparent and then how to fix it.

**Comment by LocalGod79** [comment]
probably has to do with the blending mode you've chosen - is is ~, -, +?

**Comment by LocalGod79** [comment]
are they in a subdirectory `asteroid`?  i don't know - kinda grasping at straws...

**Comment by Amazinite** [comment]
No idea why, but running the images back through Gimp seems to have fixed it. Also, they're in a new `debris` folder.

**Comment by Amazinite** [comment]
Just did the math; 900 sprites to post process, and after sizing out the 2x and normal sized images, I'm going to have a total of 1800 sprites on my hand, and that's just the debris part. Looks like I'm going to be putting in some work this weekend. 

@LocalGod79 @Wrzlprnft If we're going with the concept of having these debris ships drop damaged outfits, could you two work on the sprites for those? I'll make a list of the outfits that need done in he morning, because we only need damaged versions of what the debris can drop.

**Comment by Wrzlprnft** [comment]
i'll happily help there. also. can you do the postprocessing in blender? like, using blenders video editor to make the necessary overlays? i could also work it into the material via texture. because i found a way to automate the picture output.

**Comment by Amazinite** [comment]
```
Weapons:
	Energy Blaster
	Beam Laser
	Heavy Laser
	Proton Gun
	Javelin Pod
	Meteor Missile Launcher
	Sidewinder Missile Launcher
	Heavy Rocket Launcher
	Blaster Turret
	Anti-Missile Turret
	Gatling Gun

Systems:
	Shields (Tiny, Small, Medium)
	Hyperdrive
	Cargo and Outfit Scanner
	Cooling Ducts
	Water Coolant
	Ramscoop
	Small Radar Jammer

Power:
	Fuel Cell (Tiny, Small, Medium)
	Batteries (Tiny, Small)
	Supercapacitor
	NT-200 Nucleovoltaic
	RT-I Radiothermal
	S3 Thermionic
	Dwarf Core

Engines:
	Tiny Plasma Thruster/Steering
	Small Plasma Thruster/Steering
	
	Tiny Ion Engines
	Tiny Ion Thruster/Steering
	Small Ion Thruster/Steering
	Medium Ion Thruster/Steering
	
	Tiny Atomic Thruster/Steering
	Small Atomic Thruster/Steering
	Medium Atomic Thruster
	
	Afterburner
```

**Comment by Amazinite** [comment]
Well then. It looks like the images need to be within the asteroid folder, otherwise they can not be targeted.

**Comment by LocalGod79** [comment]
or ships - otherwise hit masking doesn't take place...

**Comment by KiLEdEnNis** [comment]
how so? you can hit asteroids (or do I just not know what hit masking exactly is?)

**Comment by Amazinite** [comment]
If the images is not in "ship" or "asteroid" it can't be hit, because it has no hit/collision mask to be hit.

**Comment by KiLEdEnNis** [comment]
oh I read that it had to be in ships, not in asteroids, while you can do both

**Comment by Amazinite** [comment]
PRed my current progress.
