### ISSUE TITLE
Feature Request/ Lore question

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1975]
how about we declare pointedstick or a play on words with his real name the inventor of endless sky standarts in terms of hailing standarts? i like to see the little nod to his work.
( don't worry, @endless-sky, you will remain the surpreme leader... eh i mean the terror of the galaxy.... i ... uhh... you get it)

**Comment by KiLEdEnNis** [comment]
"This hail is sponsored by Pointedstick."

**Comment by Elyssaen** [comment]
I'd love to see a random news bulletin-type feature, and there could be a company called Pointedstick Communications, motto "Get your point across", who have a monopoly in ship-to-ship communication protocols.

**Comment by DingusShingleton** [comment]
Yes.

**Comment by Bladewood** [comment]
Would a simple solution be to just give Pointedstick his own Person?

**Comment by Pointedstick** [comment]
Aww thanks guys! I feel like it would be presumptuous to add such a thing myself, but if anyone else did it and MZ didn't object, I certainly wouldn't mind! 😃

I too would love a random news bulletin feature. If somebody coded that up so it appeared in the Spaceport(reminiscent of the old-school EV games) I would add SO MUCH CONTENT to it. Even better would be if it could actually respond to in-game events.

I ruminated about such a feature in https://github.com/endless-sky/endless-sky/issues/1552

**Comment by Pointedstick** [comment]
Also it would be nice to get https://github.com/endless-sky/endless-sky/pull/1754 integrated 😉

**Comment by endless-sky** [comment]
@Pointedstick, if you want to pick what sort of ship you want to fly and what its hails will say, I'd be glad to merge it in.

**Comment by Alkallid** [comment]
You made the Vangaurd too, right?

**Comment by Pointedstick** [comment]
I did.

**Comment by KiLEdEnNis** [comment]
one day (if I manage to make my Blender ships actually look decent from top-down and) if I finally finished my project, I demand a person too :3

**Comment by Wrzlprnft** [comment]
ummm... i am not sure if this is how it works.

@Pointedstick i could try to make a special vanguard image for “pointedstick communications“, but i'll not be able to make fancy hails for it.

**Comment by KiLEdEnNis** [comment]
ooh I can try o:
@Pointedstick just tell me if ya want any specific hails, I'll do them tomorrow (or at least, I'll TRY to do them tomorrow)

**Comment by Wrzlprnft** [comment]
i guess if you deliver, i can't say anything :)

**Comment by Pointedstick** [comment]
I'll have a pull request in soon enough. 😈

**Comment by Amazinite** [comment]
Marauder Vanguard? :3

**Comment by jafdy** [comment]
It would need to have more guns. 7 is not enough.

**Comment by Pointedstick** [comment]
Hah, I was thinking just a normal Vanguard. I don't need a special one. 🙂

**Comment by Pointedstick** [comment]
Speaking of that, I still have the original Vanguard assets, including the Blender and GIMP files. Is there a place I can upload those to make them publicly available?

**Comment by Wrzlprnft** [comment]
if you have sent them to MZ he added them to the assets. 
i'd suggest a 'deluxe' vanguard, some more smooth lines and upped stats.

**Comment by Bladewood** [comment]
Michael has his own Kestrel, and it uses the same sprite as the player version.
To mimic the Kestrel, we could just double the gun ports and turret mounts, a bit like what @KiLEdEnNis is suggesting.

**Comment by Bladewood** [comment]
The gun ports could all be megaphones, maybe? /joke

**Comment by Wrzlprnft** [comment]
i think some sort of logo would be cool

**Comment by Pointedstick** [comment]
https://github.com/endless-sky/endless-sky/pull/1979

**Comment by KiLEdEnNis** [comment]
he actually did 15 guns :P

**Comment by Pointedstick** [comment]
Well, this can be closed now! 😄

**Comment by Wrzlprnft** [comment]
can you send the vanguard assets to wrzlprnft@die-optimisten.net @Pointedstick ?

**Comment by Pointedstick** [comment]
Done!

**Comment by Wrzlprnft** [comment]
@Pointedstick how would you like this vanguard?
![pointedstick_vanguard](https://cloud.githubusercontent.com/assets/15857993/21741207/492f0712-d4cf-11e6-9969-596fc174a586.png)

I gave it a litle smoother look and put the actual proton guns on it, since it will never have something different :) (at least on most of them)
If you don't like the overall look, but a particular detail, ill rework it :)

**Comment by Pointedstick** [comment]
Nice! Note that my personal ship has four rocket launchers instead of two of the proton guns (mine assumed each gun was doubled up with another copy below the visible one).

Feel free to edit me person to add this nifty ship. :)

**Comment by KiLEdEnNis** [comment]
and do not forget to change the engine flare positions

**Comment by Wrzlprnft** [comment]
i can't get my git client to work. i'd mail the files and changes to someone to pr

**Comment by Nechochwen-D** [comment]
I can do it. Just message me through steam.

**Comment by jafdy** [comment]
@Wrzlprnft Pick anyone you like. I expect most of us will make the time needed to do it.
