### ISSUE TITLE
Auto-aim and fire doesn't work / Bunk numbers seem incorrect

### ISSUE THREAD

**Issue by MrChandler** [endless-sky/endless-sky#198]
So today I finally bought my first freighter and some time later even a second one, yay ^^. But I was disappointed to see that both auto-aim and auto-fire do not work for my flagship!! Now i wouldn't really mind playing without auto-fire but it is annoying and somewhat illogical that the turrets on my flagship don't even aim at enemy ships and instead just face towards the front. Both does work for my escort freighter though..
Another thing I've noticed while trying to accept some transport missions to systems close of each other is that the amount of available bunks seems to be bugged/wrong. My two ships each have 7 bunks 4 of which are used for crew members, which means that i should have 6 bunks available for missions. However i can only transport 4 workers/tourists at once.

**Comment by endless-sky** [comment]
Turrets fire are whatever your current target is, so you need to target a ship for them to do anything but fire forward. The easiest way to do that is pressing "R" for "select nearest enemy."

Is it possible you swapped out your anti-missile turrets for blaster turrets? That would increase your required crew, which might explain having only four space.
