### ISSUE TITLE
Can't escape from dialog informing you that a mission will be canceled if you take off due to insufficient passenger capacity

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1980]
Playing with current git master as of right now.

I replaced my ship with a new one that didn't have enough passenger capacity for all the passengers I was carrying at the time and got a message notifying me that I would fail a mission if I took off. But on hitting the Cancel button, the message disappeared for a moment and immediately reappeared. There was no way to escape from the loop except to hit OK and fail a mission.

**Comment by Bladewood** [comment]
Relevant: https://github.com/endless-sky/endless-sky/issues/1624

The only workaround here (that I am aware of) is to fail the mission, and then to reload an earlier save.

**Comment by KiLEdEnNis** [comment]
or press escape & reload? or does it pop up again?

**Comment by endless-sky** [comment]
773785c should fix this.

**Comment by Pointedstick** [comment]
Fixed!
