### ISSUE TITLE
Would it be possible to not have a shortcut for deleting a profile?

### ISSUE THREAD

**Issue by Groaghach** [endless-sky/endless-sky#1981]
After mistakenly deleted profiles over and over again, would it be possible to not have the "D" button to delete a profile in future versions?
And also a way to retrieve deleted profiles?
Thanks for a great game!
/Groaghach

**Comment by Bladewood** [comment]
I didn't even know that the D button would delete profiles...
Regardless, it appears that attempting to do so checks to confirm whether you really want to or not.

**Comment by Groaghach** [comment]
Correct, but when playing along and pressing both "D" and "Enter" a lot throughout the game it hasn't stopped me from deleting multiple profiles. :-(

**Comment by jafdy** [comment]
You might be able to retrieve the files from the recycling bin folder.

**Comment by Groaghach** [comment]
Please let me know how to retrieve the files from the recycling bin?
Using MacOS X, and there are no files in my Trash bin.

**Comment by jafdy** [comment]
Ahh... I'm a windows user, ask someone with a mac. Also I don't know if it is possible just that it is a thing to try.
I would guess the fix would be to not have a shortcut key on the delete button. I still don't quite get how you could accidentally do that. You would need a particular string of 3/4 key presses to get from the menu to being able to delete something.

**Comment by toilethinges** [comment]
@jafdy when you delete a file in game, it doesn't go to your recycling bin anyway.

**Comment by LocalGod79** [comment]
i'm going to throw this out there: in the last two weeks i've deleted two pilots, but have been unable to shortcut abort missions.  seems like deleting pilots should be more difficult than cancelling a mission to free up some cargo/bunk space...

**Comment by gunqqer** [comment]
I also have lost a pilot to deletion. If there is to be a hotkey to delete a pilot (which there shouldn't) it should at least be changed to something else

**Comment by endless-sky** [comment]
You all really need to stop playing the game while drunk, but 4b5a291 will make it so you need to actually click the button rather than using a keyboard shortcut.

**Comment by Bladewood** [comment]
For the record, I'm too young to drink.

**Comment by kikotheexile** [comment]
Never stopped me.

**Comment by gunqqer** [comment]
Also for the recon duchesss I can't drink either

**Comment by LocalGod79** [comment]
my liver is takes the hit for the cause - there are certainly going to be drunk users going forward, and it would be a shame if we didn't play test/accommodate as many possible user bases as possible...

**Comment by gunqqer** [comment]
For science you must test the game while totally drunk localgod!
