### ISSUE TITLE
Black backgrounds treated as transparent in scenes

### ISSUE THREAD

**Issue by kikotheexile** [endless-sky/endless-sky#1985]
It seems that any "Scenes" in conversations that have a black background are treated as transparent. If there is a way around this, I can not find it.

**Comment by KiLEdEnNis** [comment]
maybe not using black backgrounds?

**Comment by Bladewood** [comment]
@KiLEdEnNis Screenshots.

**Comment by kikotheexile** [comment]
Using screenshots to provide a basic tutorial, because the vast majority of the complaints and negative reviews we receive over on Steam are thanks to people not knowing how to UI, how to keybind, how to navigate, or how to spaceport. So I am making a lored out tutorial that is totally optional and actually makes sense in order to slow this or completely stop it. 

The issue is, using screenshots in scenes, black backgrounds make the entire scene read as high opacity. This kinda puts a kink in my hose, if you smell what I'm stepping in.

**Comment by endless-sky** [comment]
Alpha lending isn't done any differently for scenes than for any other sprite. Can you give examples of sprites that are doing this for you? And, can you check that 1. the file name is not specifying additive blending mode (+) and 2. the sprite in question really is opaque?

**Comment by kikotheexile** [comment]
The issue I'm having is with any screenshot taken and converted to a .png that has a black background, using that in a scene. If it's not being treated any differently, then that's good information to have. I'm looking for the mistake in the wrong place. I'll work on trying to figure it out, and if that ends up not happening I will share files below showing what's going on.

**Comment by KiLEdEnNis** [comment]
try giving it a color value of like 10 (black is 0 0 0 white is 255 255 255)

**Comment by kikotheexile** [comment]
Resolved, user/operator error. 

Basically I was just being a moron about how I was editing the photos. Fresh screenshots edited in, of all things, MS paint and reduced in size there worked fine and will make decent enough placeholders.
