### ISSUE TITLE
Inappropriate faction behavior

### ISSUE THREAD

**Issue by friagram** [endless-sky/endless-sky#1986]
Tribute:

It is very odd if you demand tribute from various planets, and they change ownership, because you continue to receive tribute from them. If you take over some republic planets, and they then become part of the free worlds, you continue to get tribute from that planet. This makes even less sense if you end up joining the FW and are taking tribute from FW planets.

A simple mechanic that resets tribute when the government changes would work... As would clearing all tributes for a given government when you become part of that faction.

It is also odd that you can demand tribute from say, some simple syndicate planet, and then leave the system and do it to one or two more friendly planets before the government decides it's had enough of you.

IMO demanding tribute should be an act of war, that immediately sets your reputation to some substantial negative amount, which makes you hostile with similar systems.

Ships and Escorts:

Escorts you get from missions have their own faction, and while you escort them, enemy ships (pirates) that you are friendly with can kill them. This is an inappropriate behavior. There should be a warning that accepting XX mission will flag you hostile by the faction you are protecting your escorts from (pirates).

If you are hostile with various factions (quarg, republic, etc) and are escorting some ships... these hostile factions won't ever kill your escorts if the escorts are not hostile with them. It would be fair if the escorts could at least get disabled, if not directly targeted/destroyed by factions you are in conflict with.

NPC vs NPC cross faction battles:

Boarding a faction to help their ship recover when disabled should flag you as hostile vs that ship's attacker. There should be an override for this, where the "b" key would not automatically board nearest friendly disabled ship to flag you as hostile, or there should be a dialogue to warn you that if X faction sees you doing this (is in range, or the system) will temporarily turn on you.

If I am friendly with both pirates and FW, and I go and help a disabled pirate ship, the FW ships should go and attack me. Likewise, if I help a disabled FW ship, the pirates should turn on me. The current behavior is quite stupid, as you can just run around in a merchant vs pirate battle and continually heal both sides until they obliterate each other.

**Comment by Elyssaen** [comment]
**Tribute:** an odd one. It's clearly from Escape Velocity, and is more about a bit of fun at the end of the game and not really about being realistic.

I get where you're coming from, but it's worth mentioning it wouldn't make the game more _fun_, and it wouldn't be enough to make tribute realistic. If it was me, I'd shelve it for a hypothetical bigger reconsideration of tribute.

Reputation I'd like to see changed a bit to work more as you say, but not just for tribute. You can destroy ships and stay in positive reputation, and actually the only real function of positive reputation is to give you free passes for murder. I'd love to see more of Escape Velocity's reputation rankings (e.g. "Pillar of Society" far above something like "Friendly"), and those rankings mattering for missions more. Then, once there's a fun use for building up a strong reputation, it'd be fair for outright hostilities to drive reputation negative in an instant.

**Escorts:** not sure I agree here. If you're friendly with pirates, you should stay that way until you open fire on them. Do the pirates know you're taking an escort mission? The flip side, I also don't get it: why should the Quarg fire on a merchant ship just because the merchant captain unknowingly offered you a job to escort her?

**Boarding:** agree on this. Actually, I thought it already did, but I must be imagining it.

**Comment by Bladewood** [comment]
> Boarding: agree on this. Actually, I thought it already did, but I must be imagining it. (Just checked, yep, I imagined it!)

Yeah, when I was first plundering the Korath in pirate space, I thought repairing the pirates (whom I had bribed) would eventually make the Syndicate hostile towards me, but it never happened.

**Comment by friagram** [comment]
Well it seems that faction shifts based on enemy ship kills only? The amount depends on crew member count. Why not just have it so that some percent happens when you disable a ship,  again when you board it for the first time, and again when destroyed? Disabling a ship is a hostile action.

It would also make sense for disabled ships to lose crew members each time they get disabled at some rate, thus altering capture odds. This could mess with mechanics allowing high valued ships to be captured more easily. Some ships have counter measures, which is fine. There is a Never Disabled flag, why not just make a Never Capturable (quarg ships)? That just disables the attack button.

if currently you would get 100 points for destroying a ship, why not make it so you get 30 for disabling, and then 70 more for destroying?

Also, boarding could be some amount based on total value plundered for hostile ships. For friendly ships it could be based on the crew count (you are saving them)

**Comment by Elyssaen** [comment]
Disabling and destroying do that already, according to this:

```
	// Default penalties:
	penaltyFor[ShipEvent::ASSIST] = -0.1;
	penaltyFor[ShipEvent::DISABLE] = 0.5;
	penaltyFor[ShipEvent::BOARD] = 0.3;
	penaltyFor[ShipEvent::CAPTURE] = 1.;
	penaltyFor[ShipEvent::DESTROY] = 1.;
	penaltyFor[ShipEvent::ATROCITY] = 10.;
```

and it can be customised for each government by putting "penalty for [event]" and a number in the data file entry for that government.

There's also an `uncapturable` flag already. In my view it should be used sparingly: the Quarg ships _should_ be capturable at some point.

Can't say I agree about disabled ships losing crew members for 'free' when they get disabled... it just seems like it'd completely screw with any attempt to balance capturing, as you say, and I don't think you get anythign out of it to make up for that. The end player just sees a slightly different number of crew and it doesn't mean anything to them: balancing assumptions need to work on the assumption a ship is probably disabled once, so it's just a static shift.

**Comment by friagram** [comment]
That is good then, though the static crew size of ships make some just almost capturable ones slightly out of reach. If the initial disable could knock out a random 1-10% of the crew, it would significantly change the capture odds in some situations.

it is possible iirc to remove everything from a ship and use only the most simple engines/turning to maximize bunks. pretty sure you can do this to capture things like a wardragon, though the odds would be single digit

**Comment by Elyssaen** [comment]
Crew size isn't static: the crew of a ship is anywhere between the required crew and total number of bunks, in a linear distribution. A Skylark might have anything from 122 to 210 crew.

And yep, the best you can do is something like 53 Bunk Rooms on a Bactrian, bringing you to 457 crew. If you come across a minimal crew Skylark you can get a capture chance of 9.8%. You'll only ever see 0.0% against a Wardragon or World-Ship.

**Comment by endless-sky** [comment]
There's no way for the missions to take into account every permutation of planets the player may have captured. So, the story line basically ignored dominated planets.
