### ISSUE TITLE
Escorts can park in uninhabited systems.

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#199]
Pretty easy to reproduce.
Buy a fleet of escorts.  Fly out to some uninhabited system.  Order escorts to halt (hold position).  They stay when you jump out.  You land on a planet somewhere, and you can order them to park.  They go into park just like a legitimately parked ship, you don't have to pay crew salary until you unpark them.
I guess the crew hails a passing ship for a free ride to the nearest system?  And similar when you decide to unpark the ship?

This also works in systems that won't allow you to land.  I've got a hawk parked in an unfriendly system because it was a captured pirate and didn't have the fuel to jump.  I'll cash it in when I have the spare cash to bribe the planet.

**Comment by endless-sky** [comment]
I'm not sure if it makes sense to fix this, or to keep it as a feature (albeit a nonsensical one) just so people are not stuck paying salaries for ships stuck in empty systems.

**Comment by endless-sky** [comment]
For now I'm just going to leave this as-is, because the annoyance of not being able to "park" ships in uninhabited systems would far outweigh the loss of realism by allowing it.
