### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Isaacssv552** [endless-sky/endless-sky#1990]
I get the below error when trying to compile endless sky. It worked fine about 170 commits ago. 

Ld /Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Products/Debug/EndlessSky.app/Contents/MacOS/EndlessSky normal x86_64
    cd /Users/Isaac/endless-sky
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Products/Debug -L/opt/libjpeg-turbo/lib -L/usr/local/lib -F/Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Products/Debug -F/Library/Frameworks -filelist /Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Intermediates/EndlessSky.build/Debug/EndlessSky.build/Objects-normal/x86_64/EndlessSky.LinkFileList -Xlinker -rpath -Xlinker @loader_path/../Frameworks -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Intermediates/EndlessSky.build/Debug/EndlessSky.build/Objects-normal/x86_64/EndlessSky_lto.o -Xlinker -no_deduplicate -stdlib=libc++ -lmad.0.2.1 -framework OpenAL -framework OpenGL -lturbojpeg.0 -lpng14.14 -framework SDL2 -framework Cocoa -Xlinker -dependency_info -Xlinker /Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Intermediates/EndlessSky.build/Debug/EndlessSky.build/Objects-normal/x86_64/EndlessSky_dependency_info.dat -o /Users/Isaac/Library/Developer/Xcode/DerivedData/EndlessSky-ayieevvezfcctfdanvowxhrvdyrt/Build/Products/Debug/EndlessSky.app/Contents/MacOS/EndlessSky

Undefined symbols for architecture x86_64:
  "CollisionSet::Add(Body&)", referenced from:
      Engine::CalculateStep() in Engine.o
  "CollisionSet::Clear(int)", referenced from:
      Engine::CalculateStep() in Engine.o
  "CollisionSet::Finish()", referenced from:
      Engine::CalculateStep() in Engine.o
  "CollisionSet::CollisionSet(int, int)", referenced from:
      Engine::Engine(PlayerInfo&) in Engine.o
  "CollisionSet::Line(Projectile const&, double*) const", referenced from:
      Engine::CalculateStep() in Engine.o
  "CollisionSet::Circle(Point const&, double) const", referenced from:
      Engine::CalculateStep() in Engine.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Amazinite** [comment]
#1920

**Comment by Bladewood** [comment]
@Amazinite That's for Windows. @Isaacssv552 is using a Mac.

**Comment by Amazinite** [comment]
>You probably need to download the library to use the new music system. Check the build instructions, because there's some new bits there.

**Comment by Bladewood** [comment]
Ignoring that, from his log, he apparently has a problem with "Engine.o".

**Comment by Elyssaen** [comment]
Not sure if it's a problem with the Engine file exactly. The problem is every place that CollisionSet.cpp is called: it can't find the references to them, suggesting that CollisionSet isn't being included in the project. Clean down the object files and rebuild? Newbie's advice here, but it's the equivalent of "turn it off and on again" and I'd at least want to be sure it's been tried.

**Comment by Isaacssv552** [comment]
Libmad is already installed. I already tried recompiling from scratch, but I'll try manually removing the object files again.

**Comment by Elyssaen** [comment]
Hmm, is CollisionSet.cpp/CollisionSet.h definitely included in your Xcode project? The second answer [here](http://stackoverflow.com/questions/18408531/xcode-build-failure-undefined-symbols-for-architecture-x86-64) about architectures also might be interesting. Otherwise, I'll have to leave it for those more experienced to help out.

**Comment by Isaacssv552** [comment]
They weren't, the project apparently wasn't updated to include them.

**Comment by Elyssaen** [comment]
Ah. Guess perhaps you need to do that every time? They're added to the Code::Blocks .cbp file but I haven't even checked the procedure for using Xcode. If you add them, and any other files, is everything fine?
