### ISSUE TITLE
Escorts in infinite wormhole loop

### ISSUE THREAD

**Issue by galaxor** [endless-sky/endless-sky#1991]
As I was flying into Hai space, a couple of my ships didn't have enough fuel to make it all the way.  When they got to the wormhole, they decided to stop off to refuel by landing on the wormhole.  They ended up back on the other side of the wormhole, noticing they didn't have enough fuel to make it all the way, so they decided to land on the wormhole to refuel.  Once they were back on my side of the wormhole, they noticed they didn't have enough fuel to continue, so they decided to land on the wormhole to refuel, .....

I flew around and did other things, and no matter what system I was in, I kept seeing that those ships were bouncing between the two sides of the wormhole.  I ended up disowning them.

**Comment by Amazinite** [comment]
Version number?

**Comment by galaxor** [comment]
0.9.4.  The stable release.

**Comment by Amazinite** [comment]
[Already fixed for next update.](https://github.com/endless-sky/endless-sky/blob/master/changelog#L9)
Plz close.

**Comment by galaxor** [comment]
Yaay.

**Comment by Elyssaen** [comment]
Sorry you ended up disowning them though. I had the same problem and went into my save file to give them some extra fuel. Hope you didn't lose anything too important.
