### ISSUE TITLE
Ambient system sounds won't play from a plugin directory.

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#1992]
As per title. I had to move the files to the base games' sounds/ambient directory to get it to play.
```
system Valiit
	pos 223.91 -714.241
	government Valuut
	music "ambient/spacey tune"
```
Also tried
```
system Valiit
	pos 223.91 -714.241
	government Valuut
	music "sounds/ambient/spacey tune"
```
File structure is plugins/myplugin/sounds/ambient/spacey tune.mp3
Win 7 x64

**Comment by endless-sky** [comment]
Fixed in 806d4ce.
