### ISSUE TITLE
"Donate" DLC on steam

### ISSUE THREAD

**Issue by alugarius** [endless-sky/endless-sky#1993]
id Like to donate to the project, it is easier for me and others with DLCs to buy, but also link the source.
The Plugin store could be DLC converted.

**Comment by nylki** [comment]
Regarding donations there has been an answer by @endless-sky 
https://groups.google.com/d/msg/endless-sky/9Gb5Fxl0a_s/9g25vFOTAQAJ

**Comment by Amazinite** [comment]
As @nylki said, it's been brought up before and the answer is no. Please close this.

**Comment by dfrankow** [comment]
For those not in the google group, the message is from Sept 2016, and says:

> The short answer is, I'm trying not to blur the line between Endless Sky just being a rather time-consuming hobby, versus it being a second job. That's important both because my contract for my day job (as a computer programmer) doesn't allow me to have a second paid job on the side, and for tax reasons as well if the donations were large enough.

> The other answer is that honestly, my day job pays quite well and I'm not really in need of more income - in fact, I usually give away about 30-40% of my salary as a way of reducing my taxable income for purposes of legalized tax resistance. So, people "donating" by creating game content or tracking down bugs is much more useful than donations of money.

> What would be cool, somewhere down the road, would be a Kickstarter-like campaign to collect donations to directly pay a really talented artist. (For example, having someone who's good at sci-fi "matte paintings" create a bunch of space station interior "landscapes" to replace the really tacky ones in the game right now.) But, I just don't have the time free to organize something like that.

**Comment by dfrankow** [comment]
@endless-sky You could consider setting up (or getting someone else to set up) a non-profit to take in income. That would avoid the tax implications. But of course, that would take time.
