### ISSUE TITLE
Mission details and depart hotkey

### ISSUE THREAD

**Issue by TakingItCasual** [endless-sky/endless-sky#1995]
I quickly flip through the job board to see what's the most lucrative offer, and am annoyed by the nonstandard placement of the payment details, which slows my browsing down. To further speed things up having the "jumps away" counter somewhere closer to the other details would be nice as well.

Edit2: To further expand the "jumps away" issue, why isn't said counter present when selecting star systems in the general map? It seems that'd be where it's the (2nd) most useful.

Edit3: Another thing that I just thought would be nice: A "jumps remaining" counter in the general HUD based on the destination set in the map.

Edit: ignore this next part...
A minor inconvenience I wanted to tack onto this is that there doesn't seem to be a hotkey for departing a planet/station, which forces me to reach for the mouse when many other things can be done with the solely the keyboard.

**Comment by Amazinite** [comment]
Isn't the depart key D?

**Comment by TakingItCasual** [comment]
Sorry, didn't realize. checked the preferences and didn't see anything for it.

**Comment by DingusShingleton** [comment]
Yes, I've been pining for a better way to view mission rewards as well. Like a column in the mission computer that shows the reward (20k, 18k, 250k). That would allow you to see if there are missions that you want to take at a glance.

**Comment by friagram** [comment]
Missions are just in an unsorted list.
Missions really should be filterable by things like:
- Minimum payout
- only show new missions on current flight path
- only show bounty/passenger/cargo missions by type (checkboxes)
- perhaps turn missions that don't pass the filter to some non-critical color like blue
- perhaps turn non randomly generated missions some critical color like green

**Comment by Amazinite** [comment]
#236 job sorting.
