### ISSUE TITLE
Heliarch Punisher (Interdicting) is missing bombardment turret in outfit list

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1999]
ship "Heliarch Punisher" "Heliarch Punisher (Interdicting)"
		outfits
			"Bombardment Cannon" 4
			"Finisher Pod" 2
			"Finisher Torpedo" 80
			"Heliarch Attractor" 2
			"Heliarch Repulsor"
			
			"Large Reactor Module" 2
			"Large Battery Module"
			"Large Shield Module" 3
			"Large Repair Module" 2
			"Cooling Module" 3
			
			"Large Thrust Module" 2
			"Small Thrust Module" 2
			"Large Steering Module" 2
			"Small Steering Module" 2
			"Hyperdrive"
		
		gun "Bombardment Cannon"
		gun "Bombardment Cannon"
		gun "Bombardment Cannon"
		gun "Bombardment Cannon"
		gun "Finisher Pod"
		gun "Finisher Pod"
		turret "Heliarch Attractor"
		turret "Heliarch Repulsor"
		turret "Heliarch Attractor"
		turret "Bombardment Turret"
The interdicting punisher has a bombardment turret, but this is not listed among its outfits at the top.

**Comment by KiLEdEnNis** [comment]
side note, I personally like to see the Bombardment Cannon/Turret buffed; a little more velocity & damage

**Comment by Amazinite** [comment]
Damage is really fine as is (they aren't as good as a Skylance by any means, but aside from that or Gridfires, they're the best obtainable non-secondary weapon in terms of damage/mass), but they do fly pretty slow.

**Comment by KiLEdEnNis** [comment]
well, at least the velocity (and maybe range a little), and the decay also makes them look weak long range ;-;

**Comment by endless-sky** [comment]
Fixed in b744cf3.

The slow speed is intentional; I want to have as wide a variety of weapons as possible, and there are not any other slow, long range primary weapons. The slowness also balances out the high damage to some degree. And, I really like the visual effect where you get clouds of bombardment projectiles moving in waves at different speeds when a fight with the Heliarchs is going on.

**Comment by KiLEdEnNis** [comment]
I must admit it is satisfying to see, maybe it's not a weak weapon but the "decay" effect makes it look like it's range is shorter than it should
