### ISSUE TITLE
Bug: Mission Breaks

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#2005]
Latest Build:

mission "Wanderers: Sestor: Drones in Alnilam" bugs out, gets offered twice, and never completes.

Edit: Missions seem to constantly repeat on Farpoint over and over again now. Pirate Defence event repeating, pirates attacking 5th time in a row now.

**Comment by KiLEdEnNis** [comment]
I think that pirate defense is meant to be repeatable, try looking in the files

**Comment by gchapyzh** [comment]
Not this many times in a row, on the same planet, every time I land, with such high planetary defence fees.

**Comment by Amazinite** [comment]
>RNGesus

**Comment by gecko-locator** [comment]
I also don't seem to be able to complete "Wanderers: Sestor: Drones in Alnilam" mission. All drones are gone in Alnilam, but no message when landing on Farpoint.

**Comment by gchapyzh** [comment]
RNGesus is dead. Long live the lord of Bugs.

Alnilam did have ONE fleet, and killing that did not complete the mission. Or, more precisely, it was complete from the very beginning if you look at the map marker.

**Comment by Amazinite** [comment]
I had the same problem. Despite the fleets being destroyed, the missions were still listed as "active" in my save and I had to switch them to done to continue.

**Comment by Amazinite** [comment]
I also had a case of `"Wanderers: Mereti Observation"` not completing. I left the system after being told that the scanning was done but it seems to have failed somewhere between when I left and when I landed on the destination planet, because it was never set to done in my save. Does the destruction of the ships that are suppose to be disabled fail the mission?

**Comment by endless-sky** [comment]
acfac65 should fix the bug of the drone'killing mission never completing.

The mission on Farpoint is deferred if you don't ask for a fleet to help you out, rather than being declined, so if you later decide you need backup you can come and ask for it.

**Comment by endless-sky** [comment]
The defense mission getting offered every time is, I think a bug caused by the change to how the "random" condition works - because it now changes every time "random" is queried, the mission gets a chance to be offered over and over until it succeeds the random check.

**Comment by gchapyzh** [comment]
Thanks.

Could you point me at how to re-start the mission line so I can confirm the fix?

**Comment by KiLEdEnNis** [comment]
maybe that's why my save file had issues between Zenith bombing, the invisible Alnitak (Sestor Alt) defense missions and Alnilam defense fleets (only had a tiny one there; a Kar Ik Vot, 1 drone 1 fighter carrier & like 1 Met Par Tek)

**Comment by endless-sky** [comment]
You can restart the mission thread by deleting every condition starting with "Wanderers: Sestor" from the conditions section of your saved game.

**Comment by gchapyzh** [comment]
Thank you @endless-sky !

**Comment by Bladewood** [comment]
I think it should be made more clear to the player that you have to outright destroy the Kor Sestor ships, rather than just disable them.

If you only disable them and land back on Farpoint, the mission is apparently lost.

**Comment by KiLEdEnNis** [comment]
disable should count as kill, maybe add that
