### ISSUE TITLE
Fleet orders are forgotten when you enter a new system

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2008]
In Hevru Hai. Heading to Alnitak. Have two unparked Arfectas in Ka'ch'chrai.
Departed, and immediately told them to hold position. They did so.
And I jumped.
They began to jump as soon as I entered the new system.

They've apparently forgotten their orders to hold position.

**Comment by Elyssaen** [comment]
I was planning to investigate this and post about it just today. Had a brief look but not enough to figure it out. I was wondering if it was intentional, but I'd like to be able to had an escort hold in a system.

**Comment by endless-sky** [comment]
Fixed in 45fef85.

You can select an out-of-system escort by clicking their icon (or, if no escorts are selected, orders go to all of them).

**Comment by Elyssaen** [comment]
Ah, great. I thought I noticed something odd about when I could/couldn't select an escort's icon. I'll check and if I have a question I'll raise an issue about it.
