### ISSUE TITLE
Wanderer: Sestor Search on enter dialog type

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#2011]
it says 'around the anarchist world of <planet>' but because the destination of the mission is Vara K'chrai, `<planet>` is replaced by that and not Zenith. The way I see it, there a few options to fix this:
Replace `<planet>` with 'Zenith'; or replace the mission destination with 'Zenith' but the mission isn't invisible and so that player would know exactly where to go and likely wouldn't land anywhere unless they have to for fuel so they'd miss all the flavor text; or move the 'on enter' dialog into a separate invisible mission that has Zenith as its destination and the same 'to fail' requirement as the current mission.

**Comment by Amazinite** [comment]
Already been done. dd454f0

**Comment by warp-core** [comment]
@Amazinite different missions. Seems this has happened a lot in the recent story.

**Comment by warp-core** [comment]
@Amazinite Ok, I haven't seen all the notes on that commit.

**Comment by KiLEdEnNis** [comment]
I'm not sure why we even use <planet> at all instead of the planet name

**Comment by endless-sky** [comment]
I wrote all the mission dialog first, to make sure I liked how the story line flowed, before actually filling in the planets or creating any of the missions. So, when I was writing it I hadn't yet figured out the names of the particular planets that would be involved.

**Comment by KiLEdEnNis** [comment]
so technically we could just change all names to the actual names? if it's worth doing I could do some
