### ISSUE TITLE
model 8, 256 & 512 missing in google drive

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2014]
and dang the model 128 has 500+ cylinders in the blend

**Comment by endless-sky** [comment]
I just uploaded the missing ones.

**Comment by Nechochwen-D** [comment]
Why don't you just host them here?

**Comment by Amazinite** [comment]
Space reasons.

**Comment by Nechochwen-D** [comment]
How so? I was unaware that GitHub had a maximum repository size.

**Comment by KiLEdEnNis** [comment]
the blends aren't actually in-game, so putting them in the files seems unlogical

**Comment by Nechochwen-D** [comment]
I was thinking of putting them in their own repository.

**Comment by KiLEdEnNis** [comment]
google drive works though, and they're ordered instead of a list (can't explain that much, but I like the google drive lay-out)

**Comment by KiLEdEnNis** [comment]
and holy, 700+ cylinders in the Model 512 blend
I bet it was a pain to make the Kor Mereti (the higher model the worse)
but since the issue is fixed, closed
