### ISSUE TITLE
New landscape images (lots of)

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#2015]
The product of the recently closed contest I ran on the steam forums has given me a lot of good landscape images. I am going to start cutting out some but I wan't to keep @endless-sky in the loop with them, this is his game after all.
[The first pass](https://drive.google.com/open?id=0B0mWx-Fhhhz7SXlIdXB3U2FIU2s) took out foreground objects, people and most duplicates. I am working my way through a second pass.
The contest thread is [here](http://steamcommunity.com/app/404410/discussions/3/340412122420889457/).

**Comment by KiLEdEnNis** [comment]
152 images, I love it (but I think I saw 1 of them; orange sky & lined clouds, around the middle in the list)

**Comment by jafdy** [comment]
The current trimming down has it at 144, still a way to go.

**Comment by jafdy** [comment]
Done the [second pass](https://drive.google.com/open?id=0B0mWx-Fhhhz7Um9QMFJXZW1pUFE). Only a few duplicates to decide between. If there is a preference then let me know. I should be ready to PR this tonight or tomorrow.

**Comment by KiLEdEnNis** [comment]
so you need opinions on the landscapes where you have 2 similar ones of? when I get home I can take a look

**Comment by jafdy** [comment]
[3rd pass](https://drive.google.com/open?id=0B0mWx-Fhhhz7WkxLemZNeGFLbUE) I hope it's the last. Resolved all remaining duplicates and names all the files (@2x) Ill make the PR when GitHub desktop works.

**Comment by toilethinges** [comment]
Do you have the licensing information for them all?

**Comment by jafdy** [comment]
I don't really understand licensing. To the best of my understanding all of the images where taken by the entrees. I put a copyright clause in the contest post saying I would use the CC-BY-4.0 license (same as the game). I can work back to find out who took what picture if needed.

**Comment by KiLEdEnNis** [comment]
if they were all given to you knowing they could be used in-game under that license it's ok

**Comment by jafdy** [comment]
Closing this to keep it on it's PR page.
