### ISSUE TITLE
Coalition "Spectators to <planet>" jobs don't display number of passengers

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2020]
The mission description looks right:
```
description "These <passengers> will pay <payment> for transportation to <planet> in time for the Coalition Games (by <date>)."
```

But it doesn't show up correctly in-game:

![no number](https://cloud.githubusercontent.com/assets/1097249/21972134/7e77f45a-db74-11e6-8fbe-f380c70e57ed.png)

I see the same thing with every one of the spectator jobs in Coalition space.

**Comment by Elyssaen** [comment]
The keyword is doing what it should, `<passengers>` is supposed to just be the word "passenger" or the word "passengers". Should probably be `These <bunks> passengers` though.

**Comment by KiLEdEnNis** [comment]
I love the Coalition Games, take me there

**Comment by Pointedstick** [comment]
Oh, you're right @Elyssaen. Fixing.
