### ISSUE TITLE
Plugin description does not scroll, but go out of the bounds

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#2022]
![2017-01-16-120045_1920x1080_scrot](https://cloud.githubusercontent.com/assets/15857993/21980443/afcc03d8-dbe3-11e6-88b4-d6a92ddab6ca.png)

edit: this is probably just a improvised description for [world-forge](https://github.com/Wrzlprnft/world-forge). just want to prepared for thew update.

**Comment by endless-sky** [comment]
The about text is meant to just be a basic description of the plugin. For now, authors should just make sure the text fits in the box.

**Comment by Pointedstick** [comment]
A scroll view would really be preferable here. Why limit the description to such short text? Besides, when plugin writers inevitably accidentally write something too long, people who see this are going to blame the game, not the plugin writer.

**Comment by KiLEdEnNis** [comment]
or a "prev" & "next" button (I'd prefer that, and you can add menu hotkeys to them)

**Comment by comnom** [comment]
> Why limit the description to such short text?

Why make it longer though? The plugin is already installed, so presumably the user has some idea what's in it. Steam threads, guides, and/or the website they got it from all include long form descriptions before they even click download.

**Comment by Wrzlprnft** [comment]
ill shorten it. but i'd rather have the game cut any excess letter of than out of bounds.

**Comment by Amazinite** [comment]
The same thing happens when you have too many plugins installed. :)

**Comment by Pointedstick** [comment]
...Which is yet another reason why it should be a scroll view. When you let modders and players fill something with content, you assumptions about how much they're likely to put there are likely to be low!

**Comment by Amazinite** [comment]
There's room for 20 plugins. I have 23...

**Comment by KiLEdEnNis** [comment]
I'd like a "prev" & "next" button with hotkeys because it'd look cool, but a scroll button would do too

**Comment by Bladewood** [comment]
http://steamcommunity.com/app/404410/discussions/2/135513549095686720/ can we reconsider this issue

**Comment by endless-sky** [comment]
It's the same as planet descriptions: if you're creating content, it's your job to keep it concise. It's not like asking a mod developer to actually check what their about page looks like is imposing so much of a burden on them. (And, they're probably going to want to check anyway to be sure there aren't any particularly ugly word wraps, etc.)

In the long term I'd like the plugins list to have more flexibility, but it's a really low priority.
