### ISSUE TITLE
Interesting problem with zooming while landing

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2024]
If I land while simultaneously attempting to zoom in or out, planets and ships and asteroids and such remain the same size on landing, but the background haze and the star field continue to zoom.
Or something.

It's a lot easier to see what I mean if you actually attempt it, but here's a picture of the end result for those who are too lazy. (You're not gonna get much out of it, tho.)
![zoomfail](https://cloud.githubusercontent.com/assets/16506683/21993767/81c93e54-dbea-11e6-924c-f64cc5500551.png)
It's not easy to tell, but notice how the ships and such are on a different [scale] compared to the star field than what would be expected.
At that scale, one would expect everything to look like this:
![zoomfail2](https://cloud.githubusercontent.com/assets/16506683/21993935/54a7f8d8-dbeb-11e6-9bdf-52504d854e3b.png)
But in the first picture, the ion thruster flares and the random splinter head are massive. And so are the planets.

**Comment by Bladewood** [comment]
Aaand it turns out there's a similar effect if you scroll while still docked.
That is, you have landed on a planet, and you go to the preferences screen and change the scroll setting, and return to the planet screen.

**Comment by Lineth** [comment]
I kinda like the zoomed out look of the star field.

**Comment by endless-sky** [comment]
This should be fixed by 81b2d4b. It's not a perfect solution, because the zoom is just paused and then continues when you leave the planet, but it's the best way of handling it that I could think of.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
