### ISSUE TITLE
Use the awesome 'random npc shipname' function we have for player ships.

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#2026]
on steam, a discussion popped up about adding the option -ideally by a field labelled “random name“ you can tick or leave it- to use the random shipname generating system already in place for npcs. links may follow if on desktop later.

**Comment by Bladewood** [comment]
would we just use merchant names or something?

**Comment by Waladil** [comment]
Slightly more ideal than a tick-box: A "random" button that generates and writes out a random name without confirming it. So players could hit it, decide whether they like the name, hit it again for a different name, et cetera.

**Comment by endless-sky** [comment]
Added in 2f5bb78, following @Waladil's recommendation: the button fills in a new random name each time you click it, but doesn't close the dialog.

**Comment by Wrzlprnft** [comment]
thanks.
