### ISSUE TITLE
feature request for "special" weapons

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2028]
I got the idea today to add the possibility for a new weapon type, and it should be paired with the possibility of aura weapons
basically; I want to be able to make an aura weapon that affects allied ships (not enemy ships), and the aura weapon could do negative hull, shield, ion or heat damage; some sort of healing aura

what I'd need for that in the code is:
adding aura weapons possibility (the Drak Draining Field, A-M Field etc. need it anyway)
a special weapon attribute that does: not auto-fire on an enemy ship and does auto-fire on allied ships (maybe make it not affect enemy ships at all)

it's hard to explain but is that possible? it could add some very interesting possibilities for hgher tier species and modders
(and if not, just actually implement aura weapons, and a side idea for that: if it would be a laser, an individual beam would shoot at every ship in range)

and since it's so hard to explain, ask whatever questions you have

**Comment by Bladewood** [comment]
We could implement a `"friendly only"` tag, and then aura weapon functionality.

**Comment by KiLEdEnNis** [comment]
that would work, the blast radius thing could not show explosions but add some aura-effects (only downside; they'd start at the turret, not the center of the ship, maybe that could have a fix too like a tag named "centered")

**Comment by Bladewood** [comment]
Perhaps a `"friendly only"` tag would be too limited.
`"target" n`, where 0 represents the standard enemy-only behavior; 1, friendly-only; 2, all.

**Comment by KiLEdEnNis** [comment]
seems fine, and not having that tag makes it 0 by default
the reason I was asking is for my project; I wanted an aura weapon that buffs allies a bit
(only real weapon I have yet: Pestillence Turret; does 0 damage, but does ion, heat, slow and disruption damage)

but with your idea of doing that aura thing, could I add a beam weapon that when hitting an enemy it releases a small aura to affect all enemy ships near?
because with range 0 & blast radius it'd affect all ships, so either the "aura" tag should really be added or we'd need to be able to toggle if an aura affects allies or not

**Comment by Amazinite** [comment]
This has been asked a few times before.

**Comment by KiLEdEnNis** [comment]
I didn't know what to search for exactly though, I tried aura weapons but got nothing

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/issues/1341#issuecomment-234122992

**Comment by KiLEdEnNis** [comment]
yes, I remembered it was brought up somewhere, but I looked at the issue name & thought "nice search result" :P

**Comment by Amazinite** [comment]
It's a triple duplicate...

**Comment by KiLEdEnNis** [comment]
ok, so closing the quadruplicate then

**Comment by Bladewood** [comment]
@Amazinite what about my suggestion here? https://github.com/endless-sky/endless-sky/issues/2028#issuecomment-273496389
Just change `"target"` to some other word because it's not about which ships to target, it's about which ships it can damage at all.
