### ISSUE TITLE
Outfit order on galactic map of outfitters

### ISSUE THREAD

**Issue by PhoenixRiver** [endless-sky/endless-sky#203]
The order of outfits in the list on the galactic map of outfitters has changed from relatively well ordered in 0.8.4 to apparently random (possibly by unique id#) in 0.8.7
Can we get the nice ordering back since the list can get very long and finding e.g. the largest shield generator, can get very hard once you been to a lot of places (even if I don't have a net worth over a couple of million I have visited most of human space... I don't know how much harder finding things might get in the late game though!)

**Comment by Pointedstick** [comment]
Hmm, seems fine to me.

**Comment by PhoenixRiver** [comment]
> Hmm, seems fine to me.

Odd... I'm running Linux - 14.04 Xubuntu, I wonder if it is something
system dependant? If there is no ordering defined then it might depend
on any number of things...

**Comment by Pointedstick** [comment]
Actually, I think you might be right. The ordering seems a bit off for some sections, but not all; the gun and turret sections seem fine.

**Comment by endless-sky** [comment]
This was a side effect of switching away from storing the "catalog" as text, because in some cases multiple items (e.g. the different Kestrel models) could have the same string. (See bug #116.) So, within each category, the items are not alphabetized anymore. I'll see if I can find a good way to restore the alphabetical order without reintroducing that old bug.

**Comment by PhoenixRiver** [comment]
> This was a side effect of switching away from storing the "catalog" as text,
> because in some cases multiple items (e.g. the different Kestrel models)
> could have the same string. (See bug #116.) So, within each category, the
> items are not alphabetized anymore. I'll see if I can find a good way to
> restore the alphabetical order without reintroducing that old bug.

Maybe just a sort on the name string you display before each category
is displayed?

Hardcoding the correct order would seem like a backstep but maybe it
could be sorted once when Endless Sky is first run and then just
stored in memory? (even if that was just a list of catelog numbers -
haven't read code so not sure this'd work...)

I should really look at this myself, sorry, but baby needs me *sigh*

**Comment by endless-sky** [comment]
Fixed in commit 8a35692. I considered whether it would make more sense to sort them by price rather than alphabetically, but an alphabetical listing tends to group "families" of thrusters and ship systems together, which is helpful.

**Comment by PhoenixRiver** [comment]
Thank you :)
