### ISSUE TITLE
About file placing in the windows port

### ISSUE THREAD

**Issue by CH-de** [endless-sky/endless-sky#2030]
Actually saves are stored in `%AppData%\endless-sky\saves` and plugins are loaded from `%AppData%\endless-sky\plugins` or the plugins folder of the applications install directory.
This is coumbersome for the genuine windows user as `/AppData` is a hidden folder.
Some digging in the web brought up [this](https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/) and [that](https://msdn.microsoft.com/en-us/library/system.environment.specialfolder.aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1) from MSDN and also some information on [Wikipedia](https://en.wikipedia.org/wiki/Special_folder#List_of_special_folders).

Wouldn't it better to use `%USERPROFILE%\Saved Games\Endless Sky` instead?

The actual location is fine I think for the other files that resides there (`preferences.txt`, `keys.txt`, …) but could also be `%LocalAppData%\endless-sky`.

How do the other windows users think about it, or am I the only one here?  :wink:

**Comment by jafdy** [comment]
Plugins can be placed next to the data file as well. 
![image](https://cloud.githubusercontent.com/assets/15716454/22083234/031b58be-ddc3-11e6-93dc-30df1291d7fd.png)

**Comment by CH-de** [comment]
Yes, I wrote that in my post already.
> or the plugins folder of the applications install directory.

But `C:\Program Files` is some sort of a special folder in windows. With UAC protection and things like that.
The users should never have to touch something in that folder manually. All content therein should be placed or removed there by installer/uninstaller.
As a developer, think of the application folder as imutable. Never try to write there (from your application), don't expect/require the users to write there. That's how Microsoft sees this.

**Comment by endless-sky** [comment]
The file placement is what is supplied by the SDL library as the default place for user files. That is, any SDL app that uses those functions is going to put things in the same place.

**Comment by CH-de** [comment]
So the best way  for genuine windows users is then to just type or copy the string `%appdata%\endless-sky` in the address bar of a file browser window to get to this hidden folder.
