### ISSUE TITLE
Blindly pressing 'j' to jump occasssionally means you jump out and then into the system you targetted

### ISSUE THREAD

**Issue by PhoenixRiver** [endless-sky/endless-sky#204]
It seems that sometimes if you have a target and you press 'j' for jump you can jump out of the system you targetted on the map and then you have to jump again to get back there (though the target system is still targetted so another 'j' will take you back, if you have enough fuel...) - the direction you travel seems random and whether it happens seems random but might be due to stacked 'j' keystrokes that happen during a jump (so something that might especially happen when quickly trying to escape... a time when you really don't want to be accidentally going somewhere you didn't intend!)

**Comment by endless-sky** [comment]
If you press "J" and you don't have a hyperspace destination selected, you will jump to whatever system is closest to being in the direction you are facing in. That's an intentional behavior as a shortcut both for quick getaways, and for someone who knows what direction they want to go in and does not want to bother with bringing up the map.

**Comment by PhoenixRiver** [comment]
Hello :)

> If you press "J" and you don't have a hyperspace destination selected, you
> will jump to whatever system is closest to being in the direction you are
> facing in. That's an intentional behavior as a shortcut both for quick
> getaways, and for someone who knows what direction they want to go in and
> does not want to bother with bringing up the map.

That makes sense, but then it appears that keypresses made during
jumps are kept and then acted on after the jump has been completed...
that's less than obvious behaviour, especially because changes in
direction and speeding up and slowing down (in terms of keypresses)
are all ignored (possibly because the speed and direction you come out
of a jump are preset and in effect overright those keypresses...
whereas I've yet to work out how to cancel a jump and queued jump
keypresses definitely seemed stored...

P.S. Nice intentional feature which I will likely make more use of now
I know it exists :)

**Comment by endless-sky** [comment]
This behavior is intended, so I'm closing this issue.
