### ISSUE TITLE
Allow systems to play music

### ISSUE THREAD

**Issue by Disiuze** [endless-sky/endless-sky#2040]
Currently, planets can have ambience, which is a great addition.
I think that extending this functionality to systems would be great.

**Comment by KiLEdEnNis** [comment]
in the future it most likely will, it's just on planets to test it for future use
stay tuned :3

**Comment by toilethinges** [comment]
https://github.com/endless-sky/endless-sky/commit/bb3f92238b48603e433532e9710f2123814196d1 Read the name, it is already supported.

**Comment by Disiuze** [comment]
Odd, I'll try again.

**Comment by Disiuze** [comment]
I was using the wrong file format, sorry for the trouble, everyone.
