### ISSUE TITLE
Can hire crew, trade etc on Far'en Lai

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#2041]

**Comment by Amazinite** [comment]
😕 
![a8823fef5e524b22933cb31b4b5196c4](https://cloud.githubusercontent.com/assets/17688683/22167102/52291a02-df32-11e6-9f2c-cdbb0e67f722.png)

**Comment by Quantumshark** [comment]
Must just be me then.

**Comment by Quantumshark** [comment]
Nevermind, it seems to have fixed itself now.
