### ISSUE TITLE
Unstable prices (depreciation-related)

### ISSUE THREAD

**Issue by sargon14** [endless-sky/endless-sky#2042]
The depreciation mechanic doesn't seem to be working for me. I'm not sure entirely what's going on...seems like multiple things. For one, if I start a new game and choose a Shuttle, it immediately depreciates it to 25%, hull and outfits alike.

But this doesn't seem to happen 100% of the time. Sometimes an outfit will sell for the correct value and sometimes not. I just made another new pilot, same conditions, and now it's showing that my shuttle is worth 58% of its max value. It looks like the hull and the battery pack are acting like they're at 25%, but none of the other outfits are.

I can get weirder things to happen, too. I just sold and rebought my shield generator, which went through at full price both times. But as soon as I did that, the value of my _fuel cell_ (not my shield generator!) started flickering rapidly between 100%, 25%, and like -447431000000000% (+/- a few zeroes; a credit value of about -18T).

In my save file, the date is `date 16 11 3013` and the depreciation and purchasing info is as follows:
```
stock
	"X2700 Ion Thruster" -1
	"X2200 Ion Steering" -1
	Hyperdrive -1
	"nGVF-AA Fuel Cell" -1
	"LP036a Battery Pack" -1
"fleet depreciation"
	ship Shuttle
		1100430 1
	outfit "X2700 Ion Thruster"
		1100430 1
	outfit "X2200 Ion Steering"
		1100430 1
	outfit Hyperdrive
		1100430 1
	outfit "nGVF-AA Fuel Cell"
		1100430 1
	outfit "D14-RN Shield Generator"
		1100430 1
	outfit "LP036a Battery Pack"
		1100430 1
"stock depreciation"
```
So yeah. Somehow the game isn't interpreting its own data correctly 100% of the time, and in fact sometimes this problem changes within the span of like, a frame update.

I noticed some other problems that I'll put in a comment under this, because I found them with an old save file, so I can't rule out back-compatibility issues.

**Comment by Amazinite** [comment]
#1850

**Comment by sargon14** [comment]
Whoops, didn't scroll back far enough to see that it had already been posted. Unlike #1850, I'm not running any plugins. I'm on Mac OSX 10.11.5, fwiw. I'm also seeing the same behavior as in #1775.

A third problem, that I don't see an open issue for, is that the depreciation ledger never clears entries for missiles you use up in flight. I have a save file that includes this:
```
"fleet depreciation"
...
	outfit "Thunderhead Missile"
		1105707 266
		1105720 14
		1105790 36
		1105800 200
		1105808 172
		1105829 100
		1105861 100
		1105900 124
```
I don't actually own 1012 missiles in that game, though! It looks like a line got added every time I restocked, but I wasn't selling missiles, so it never cleared the previous entries. Also, when I do sell them, the missiles are consistently selling for more than they're worth, like the laser rifles in #1775.

**Comment by Isaacssv552** [comment]
In #1850 I found that removing plugins didn't help, I just hadn't noticed because I the plugin was the first time I had done any serious buying/selling after upgrading to the new build. Adding a negative check solves the issue with prices becoming negative, but I've kept depreciation disabled in my game because the rest wasn't solved.

**Comment by Amazinite** [comment]
Given that this is a duplicate issue, this should be closed.

**Comment by endless-sky** [comment]
16 Nov 3013 is the day that the game begins on when you start a new game.
So if that's your in-game date and it's *not* a new game, something weird
must have happened.

**Comment by endless-sky** [comment]
I've fixed a bug that was *probably* responsible for this: a0fc3f7. I was never seeing this issue on my own computer, so it's hard to be certain.

**Comment by sargon14** [comment]
Oh hey, that's good! I'd be happy to test it, but I don't think I can build the project myself right now (XCode needs to be updated, but for bizarre external reasons I can't actually do that)...

**Comment by KiLEdEnNis** [comment]
stock ships also have small/varying depreciation on them
I think that is caused by:
- sell a ship
- you want to buy a ship, both have a hyperdrive for example
- all other ships with a hyperdrive (or any outfit you sold) are shown as slightly deprecated
if that's true then it's kinda intentional but confusing
