### ISSUE TITLE
Typo for the weapons in Heliarch Punisher (Scrappy)

### ISSUE THREAD

**Issue by SonEasterZombie** [endless-sky/endless-sky#2043]
Currently the Heliarch Punisher Scrappy variant has 6 bombardment turrets and 4 bombardment cannons, while the Punisher itself has 6 gun slots and 4 turret slots. this results in the ship having negative outfit space remaining.
![screenshot 21](https://cloud.githubusercontent.com/assets/24525074/22169664/8099a178-df3b-11e6-8d93-1299e7406fa0.png)
after Installing some outfit expansions to lessen the negative amount it let the cargo space go negative... Easy fix for this would just be to switch the amounts on turrets vs cannons. it would bring the negative up to 0 and fix the weird cargo deal.
![screenshot 22](https://cloud.githubusercontent.com/assets/24525074/22169696/b9fd9d02-df3b-11e6-9edc-c21ac075e4dd.png)

**Comment by Bladewood** [comment]
Definitely a typo, I'd say.
