### ISSUE TITLE
depreciation problem

### ISSUE THREAD

**Issue by Mark4666** [endless-sky/endless-sky#2045]
I recently began a new save file as a shuttle, did some jobs and got enough to buy a second shuttle, but when I buy the second shuttle it displays both ships (old and new) at their full value, if I sell the new ship the old one returns to its depreciated value and if I sell the old ship the new ship drops to the old ships depreciated value. if I sell an outfit on either ship it affects the value of both ships. both are stock shuttles
[dep pro old shuttle.txt](https://github.com/endless-sky/endless-sky/files/721279/dep.pro.old.shuttle.txt)
[dep pro old shuttle + new shuttle.txt](https://github.com/endless-sky/endless-sky/files/721280/dep.pro.old.shuttle.new.shuttle.txt)
[dep pro old shuttle(no batt) + new shuttle(stock).txt](https://github.com/endless-sky/endless-sky/files/721285/dep.pro.old.shuttle.no.batt.new.shuttle.stock.txt)
[dep pro old shuttle(stock) + new shuttle(no batt).txt](https://github.com/endless-sky/endless-sky/files/721289/dep.pro.old.shuttle.stock.new.shuttle.no.batt.txt)

**Comment by Amazinite** [comment]
That's intended behavior, because the game always sells the least depreciated outfits and ship hulls first.
