### ISSUE TITLE
Scanning sound is too loud

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2047]

**Comment by gunqqer** [comment]
I second this, scared TF outta me when I went to scan a ship to test out how the new scanning works.

**Comment by endless-sky** [comment]
It's about as noisy as most beam weapons, which isn't terribly loud, unless there's some sort of bug on your system - does it sound like a sort of pulsing, whistling noise, or something different?

**Comment by Bladewood** [comment]
I guess the problem isn't the volume, but the pitch.
It's way too high, it hurts my ears.

**Comment by KiLEdEnNis** [comment]
to me it's just annoying
but after having a merchant Sparrow scan me & my 4 escorts for 15 minutes & not being done (scanning merchant may be due to a mod) it gets annoying

**Comment by tehhowch** [comment]
Volume is now decreased by 006238e85b7c9647e011c1d6bebcee40216c81ee, but the sound itself is otherwise unchanged. @Pointedstick @solardawning you two have done sounds recently... here's a low-hanging apple :)

**Comment by Amazinite** [comment]
The volume has been decreased, and the pitch has been lowered. Considering this done.
