### ISSUE TITLE
Cargo Fleets loosing money

### ISSUE THREAD

**Issue by TJesionowski** [endless-sky/endless-sky#2048]
I'm currently using a fleet of 99 stock frieghters. Under the 9.4 economy, a fleet like this would tend to make around 2-10 million credits per run (When I had a profit margin of 4-6 hundred credits per cargo item.) This translates to around 5% of the fleet's cost for every run. 
Now, I'm using the Net Worth info item in the info menu to calculate this, so there may be some flaw there, but under the 9.5 economy, a run with this fleet of 99 frieghters, A bactrian I use to store rare outfits, and my Arfecta which I use for pest control, I have a total cargo capacity of around 15,500. With a profit margin of around 400, and a jump distance of 6 (Though with a total tribute of 33k a day, I don't think salaries are the issue here) I'm LOOSING almost a million credits per run. 

My theory is that this is a side effect of the depreciation. I'm loosing value from depreciation on my fleet faster than I can make it back with trading. As someone who made his ingame fortune on trading, this is a game breaker, because suddenly none of my money-making methods are working on any appreciable scale (if at all). Trading looses money because the money invested in my fleet evaporates. Boarding doesn't work on any largish scale because of death benefits and depreciation. And looting outfits from anyone less than the Quarg barely nets chump change. When I played 9.4, I had a net worth of 2 Billion, now, after buying 100 frieghters, I have a net worth of just over 500 Million, and I just can't make money.

I understand trading is meant to be a slower way of making money. I also understand that the ability to buy and sell entire fleets with no financial penalty was more than a tad unrealistic. But trading's one advantage as a money-making strategy was it's reliability and scalability. A merchant fleet costing X should be able to make some fraction of X consistently, with that fraction depending on the profit margin of the chosen cargo over the chosen route, as well as the ratio between ship cost and ship capacity. 

Initially, missions have the advantage, as they allow for a much higher profit margin for lower fleet values. Later on in the game however, they slowly stop scaling with the size of your fleet. The most I've ever gotten form a mission was 3 Million credits. Trading, on the other hand, has no limit on how much it can net in a flight. 

I could go into all sorts of other mechanics, and how they work, but as far as I know, the only endgame strategy remaining for making money is farming the Quarg. Even before depreciation, the only reason I'd even consider pissing the Quarg off is to upgrade my military capability. Gaining military potential by raiding alien races makes sense, but it shouldn't be the only endgame way to make money.

**Comment by Amazinite** [comment]
Depreciation is the steepest in the first month (losing 25% value) then it slowly lowers to 25% original value over the span of 360 days (the 50% value mark is at about 3 months). So this is really only a problem when you decide to buy dozens of brand new ships at once. They're all going to rapidly lose value in the first month, so your net worth will be difficult to keep at the same level, but after that steepest part ends, you'll start gaining in net worth again, and given that trading goods is probably the best end game method of gaining money, you'll rather quickly increase your net worth to above where it originally was.

**Comment by TJesionowski** [comment]
That appears to be what's happening. I have lots of parked ships in storage on random planets, and that's where most of my net worth was. Also neatly explains the 75% drop in net worth after the update.

**Comment by Pointedstick** [comment]
> When I played 9.4, I had a net worth of 2 Billion, now, after buying 100 frieghters, I have a net worth of just over 500 Million, and I just can't make money.

🤣 Quick, vote for the Space Republicans!

More seriously, the issue is that you're looking at net worth instead of cashflow. Your ships are depreciating assets that you use to generate cashflow. Even if they hypothetically depreciated to zero, their real value is in their ability to make you money by carrying cargo.

**Comment by TJesionowski** [comment]
True enough, I can confirm that I'm once again making money. I just can't liquidate freely anymore.
Strangely enough, this actually makes drones a more viable option, more flexibility in my fleet without having to sell it off.
