### ISSUE TITLE
Rename a few files?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2050]
We now have 7 alien races in the game, and most of them are split into multiple files.
`<alien species> ships`,  `<alien species> outfits`,  `<alien species> missions`, etc.
This makes all of their information pop up together.

And then all the human stuff is spread out if you have the files ordered alphabetically. Maybe we should rename a few of the files to have "human" in it.

`human ships`
`human variants`
`human power`
`human sales`
`human engines`
`human weapons`
`human jobs`

These last few could also be done, but they have data within them that is not entirely human, so maybe the bits of data that pertain to other species (e.g. the Quarg or Pug names in the current names file or the Jump Drive in the current outfits file) could be moved to the specific file for their species.
`human hails`
`human names`
`human fleets`
`human outfits`

**Comment by Amazinite** [comment]
It might also be worth making sure that all effects are either next to the weapon that uses them or all in the effects file, instead of having it like right now where most are in the effects file but others are next to the weapon that uses them.

**Comment by jafdy** [comment]
Would it be possible to go one step further and put folders inside the data folder to keep things sorted?

**Comment by KiLEdEnNis** [comment]
only problem: if you rename files, anyone that updates his/her game would have the old unrenamed files as well, unless they uninstalled or manually removed them
it could even be possible that it'd conflict (which could be solved by keeping the old files in for an update but having them be blank)

**Comment by Bladewood** [comment]
What @KiLEdEnNis is trying to say is: when an update happens, (I think this would only really apply to Steam users), players get all of the new files, but the old, now unused files are retained, rather than deleted.

I'm not sure if that actually happens, because I have not really studied the Steam update system.

**Comment by jafdy** [comment]
No. If that where the case I would still have alien.txt files in my steam directory.

**Comment by KiLEdEnNis** [comment]
I remember some file being renamed & I had the old one too, which I deleted

**Comment by Amazinite** [comment]
I think your mixing up file verification and game updating. 

If you rename a file in your Steam version and then verify the game files, it will readd the file that you renamed but not remove the renamed one. 

But during game updates, if a file is removed, then it is removed. Updating sees it as one file getting removed and another file getting added by a different name, so there will not be any duplicate files under different names.

**Comment by KiLEdEnNis** [comment]
may be me pasting the .zip download in my data files now I remember
so you mean if MZ renames a file & Steam updates, the old file gets removed?

**Comment by Pointedstick** [comment]
Yes.

**Comment by Amazinite** [comment]
9 alien species now. :)

**Comment by Amazinite** [comment]
Seeing as how #2125, an alternative to this, was milestoned, I guess this can just be closed.

**Comment by MCOfficer** [comment]
While we're at it, we might want to organize them into subfolders. Both `data` and `source` have become very confusing by mere size.

**Comment by Amazinite** [comment]
The subfolders idea is what #2125 requested and #2579 tried to implement. The issues with subfolders have been brought up there. (We'd also need to know how we want to create the subfolders if we are to do it.)

**Comment by MCOfficer** [comment]
As far as git is concerned, isn't renaming a file the same as moving it somewhere else? Iirc git can easily merge a file rename a content change to that file.

**Comment by Amazinite** [comment]
Well if it's the case that there'd be no issue, then that's changed in the nearly 3 years since #2579, as that PR had a merge conflict whenever a data file was changed in the master.

**Comment by MCOfficer** [comment]
I created a [test PR](https://github.com/MCOfficer/endless-sky/pull/7) by branching off 0.9.10, renaming a lot of files, and then PRing to my uptodate master. Indeed GitHub is a bit scared, but the if you follow the command line instructions you'll find that git doesn't give a damn and just straight up merges it. it even managed to rebase my changes on master with no merge commit whatsoever.

**Comment by Amazinite** [comment]
I think I'd rather stick to just renaming files for better organization right now, not only because it's the simpler change, but also because feedback on #2579 seemed to lean away from subfolders.

**Comment by Amazinite** [comment]
As far as renaming files goes, here's a proposed change. Prefixed a bunch of files with "human" and prefixed the nanobot file with "korath". 
<details><summary>2500 pixel tall image inside.</summary>

![image](https://user-images.githubusercontent.com/17688683/76192136-73ec5900-61b7-11ea-8a9b-dfbaf8b49006.png)
</details>

**Comment by MCOfficer** [comment]
> I think I'd rather stick to just renaming files for better organization right now, not only because it's the simpler change, but also because feedback on #2579 seemed to lean away from subfolders.

What? I just went through #2579 to be sure, and not only is there a majority *for* subfolders, the two concerns that i noticed (grepping a folder and jumping to files) were rebutted. And that's not even counting the [thumbs ups](https://github.com/endless-sky/endless-sky/issues/2050#issuecomment-274318042)

One thing that a lot of people are missing (or it just wasn't mentioned) is that there are a couple ways to access files:
- From the terminal: It doesn't really matter, prefix or subfolder, you just want to type human[TAB].
- Opening by filename (See VSCode) - same story, really. You type in a the filename and take the first match. A slash instead of a space doesn't throw it off.
- **GUI file lists**. It's important to note that this is presumably the biggest, but more importantly the most "unexperienced" group - as in, it contains most new (potential) contributors. This is the group where you absolutely need subfolders, because even with prefixes, scrolling over almost 100 files cannot be desirable.

So in my opinion, subfolders are definitely the way to go - especially since i'm yet to hear a good argument against them.

**Comment by Amazinite** [comment]
Well there are still some questions to be answered if we want to use subfolders.
* Do we keep the file prefixes if we do use subfolders? e.g. `data/korath/korath weapons.txt` vs `data/korath/weapons.txt`.
* Do we have a `data/general/` folder or not?

#2579 said yes to both questions, but some people said no to one or the other. We need to get a consensus on that.

Even with subfolders, the number of human files is still pretty large, so would we want something like `data/human/jobs/`? Would we want the FW files to be in the human folder or in their own folder in data (`data/human/free worlds/` vs `data/free worlds`)?

**Comment by Zireael07** [comment]
Reorganizing files into subfolders isn't an all-or-nothing case. Having a folder for each faction/race/whatever they're called in ES parlance is a good first step, then contributors would see if additional folders such as general or human subfolders are necessary.

If source is difficult to reorganize, that too can be postponed until some solution is arrived at.

**Comment by Zitchas** [comment]
MCO makessome good points for sub-folders. I think it'd make my life easier to have them, anyway.

As far as that goes, I suggest keeping the prefix, even with subfolders, because even if "korath/korath weapons.txt" is slightly unweildy, I know I frequently end up having multiple files open for comparison, and having, say, two different "outfit.txt" files open (one for remnant, one for korath, etc) gets confusing on the file names. (That, and while NPP++ seems fine with it, I think some editors may take issue with having two files with identical names open simultaneously)

**Comment by Amazinite** [comment]
Great point.

**Comment by tehhowch** [comment]
Big "no" from me on reorganizing source files into subfolders. I've added support for new contributions to be in subfolders, but to avoid instantly conflicting a ton of PRs which are otherwise not conflicted, this should not happen.

**Comment by MCOfficer** [comment]
> Big "no" from me on reorganizing source files into subfolders. I've added support for new contributions to be in subfolders, but to avoid instantly conflicting a ton of PRs which are otherwise not conflicted, this should not happen.
> 
> Same goes for renaming it. This impacts open PRs and even the branches of any fork of this repo where any source code changes have been made.

Is this a "no never", or a "once we have 200 files we might think about it"? if it's the latter, i'd argue that it's better to get through the pain now. It seems like the amount of contributors, PRs and forks will only be rising moving forward, just like the amount of stuff in the data folder...

**Comment by MCOfficer** [comment]
Once again, i did some practical testing. I branched off the current master and changed a **lot** of files, by randomly shuffling lines within them. Then i PRd it back to (a copy) of the `file-organization` branch, simulating what would happen if #4895 had been merged into master.

The result was an [epic amount of merge conflicts](https://github.com/MCOfficer/endless-sky/pull/8), according to github, but once again, merging manually didn't even raise a conflict. There are no conflicts between file *content* and file *location*. The only notable conflicts that would arise are with PRs or branches that themselves add or move files.

**Comment by tehhowch** [comment]
> > Big "no" from me on reorganizing source files into subfolders. I've added support for new contributions to be in subfolders, but to avoid instantly conflicting a ton of PRs which are otherwise not conflicted, this should not happen.
> > Same goes for renaming it. This impacts open PRs and even the branches of any fork of this repo where any source code changes have been made.
> 
> Is this a "never", or a "once we have 200 files we might think about it"? if it's the latter, i'd argue that it's better to get through the pain now. It seems like the number of contributors, PRs and forks will only increase moving forward, just like the amount of stuff in the data folder...

It's more a "don't do it just to do it," especially for a stable release. One thing I didn't test at all when testing Peter's Xcode action with subdirectories was code::blocks compilation (I use vscode with .winmake / scons). I know that configuring CB is already a pain point for a number of contributors, and I'd prefer to avoid making folks reconfigure include paths, etc.

Before we do things like source reorganization, we should probably determine whether we should adopt relative paths to headers (I went this route with the aforementioned testing) from cpp files, or if we should add an include path to the compiler directives that points at `source/` and use paths relative to the source root (projects like Battle for Wesnoth have gone this route).

For files in the source root both are equivalent, but for files in subdirectories this means we would be writing e.g.
```
// File is in folder "source/mySubFolder"
#include "../otherSubfolder/someHeader.h"
#include "sameDirHeader.h"
// vs
#include "otherSubfolder/someHeader.h"
#include "mySubfolder/sameDirHeader.h"
```

**Comment by MCOfficer** [comment]
> It's more a "don't do it just to do it," especially for a stable release. One thing I didn't test at all when testing Peter's Xcode action with subdirectories was code::blocks compilation (I use vscode with .winmake / scons). I know that configuring CB is already a pain point for a number of contributors, and I'd prefer to avoid making folks reconfigure include paths, etc.
> 
> Before we do things like source reorganization, we should probably determine whether we should adopt relative paths to headers (I went this route with the aforementioned testing) from cpp files, or if we should add an include path to the compiler directives that points at `source/` and use paths relative to the source root (projects like Battle for Wesnoth have gone this route).
> 
> For files in the source root both are equivalent, but for files in subdirectories this means we would be writing e.g.
> 
> ```
> // File is in folder "source/mySubFolder"
> #include "../otherSubfolder/someHeader.h"
> #include "sameDirHeader.h"
> // vs
> #include "otherSubfolder/someHeader.h"
> #include "mySubfolder/sameDirHeader.h"
> ```

Oh, my example only applied to datafiles which have no interdependencies. Your argument is perfectly valid for source files.

**Comment by Zitchas** [comment]
Could this be done in pieces?

For instance, I think I'm the only one with PRs involving remnant data files, and I'm fine with dealing with the conflicts involved in this. So instead of re-organizing the entire folder, #4908 could be merged, which only moves those files. As areas are identified that don't have any (or at least minimal / manageable) conflicts are identified, they can be collected into folders when appropriate.
