### ISSUE TITLE
"Drone Hunting" Rebel Mission allows for Dominating Republic Planets while staying "Friendly"

### ISSUE THREAD

**Issue by kaylara** [endless-sky/endless-sky#2051]
Balance issue.

I am in the middle of the Drone Hunting mission in the Rebel plot. I decided to start capturing Republic Capital ships because my rating with the republic always went back to "Friendly". Even without capturing or raiding a drone, jumping out of the system (or landing) reset the rating to "Friendly". I tried dominating a planet, and I can dominate then land... and have my rating reset to "Friendly". 

Attached files show the mission, the dominated planets in one of my games, and a saved game with at least one dominated planet.

[ap k~Dominated Planet during probe mission - rebel.txt](https://github.com/endless-sky/endless-sky/files/722176/ap.k.Dominated.Planet.during.probe.mission.-.rebel.txt)

![screen shot 2017-01-22 at 1 07 11 pm](https://cloud.githubusercontent.com/assets/25284676/22185056/d952eaa4-e0a3-11e6-9620-9eff391ca4c4.png)
![screen shot 2017-01-22 at 1 06 54 pm](https://cloud.githubusercontent.com/assets/25284676/22185057/d9538482-e0a3-11e6-9158-98dbb0272ab5.png)

 I am running Mac OS 10.12.2, Latest public beta from Steam, high dpi plugin.

**Comment by Bladewood** [comment]
This is independent of the Drone Hunting mission, is it not?
It is the nature of the reputation system that causes this.

**Comment by kaylara** [comment]
Thank you, Bladewood! Sorry for my misunderstanding... I will close the ticket.
