### ISSUE TITLE
Bug: It is possible to have more than 100% deprecation 

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2052]
After updating to 0.9.5 (with a lot of active plugins which may have caused it) a lot of my outfits had >100% cost, one having 5805% more selling for ~24 million credits. If you need I can find the save file with it and give a list of plugins.

**Comment by Amazinite** [comment]
Duplicate. #1850

**Comment by Pointedstick** [comment]
Yes, please attach the save file to https://github.com/endless-sky/endless-sky/issues/1850.

**Comment by gunqqer** [comment]
Cleaning out my issues, closing due to being a duplicate I forgot about
