### ISSUE TITLE
Bug: CTD after losing a boarding battle

### ISSUE THREAD

**Issue by Waladil** [endless-sky/endless-sky#2056]
Was trying to capture Pug ships, lost the battle and then lost on defense (For the record, I didn't have to let them counter-attack; I was already planning to reload the game). And the game crashed after the message saying they captured my ship and killed me.

**Comment by KiLEdEnNis** [comment]
when you restarted, did it all work fine again?

**Comment by Waladil** [comment]
Yeah, everything was fine post-reload. Not a major crash, but crashes should still be fixed, no?

**Comment by Amazinite** [comment]
Well if they can't be reproduced or pinpointed then how can they be fixed?

**Comment by Waladil** [comment]
I mean, I haven't done a full attempt to repro. But it seems like it's a civic duty while playing a still-developed game to write a bug report for crashes to desktop, even if the information is a bit scarce?

**Comment by Waladil** [comment]
Okay, I found out EXACTLY how to reproduce the crash. Works for me 100% of the time.
Step 1: Lose a boarding battle against other ship such that the enemy captures your ship and kills you
Step 2: Close boarding window
Step 3: Select any other ship by clicking it with the mouse. Keyboard selection commands will do nothing.
Game will then crash.

Crash only occurs when dying to a boarding battle; if one dies to being destroyed in space combat, clicking other ships with the mouse selects them as normal, and the keyboard commands still do nothing. 

I suspect the crash is caused by IFF confusion or some other effect based on the player's ship changing faction.

Happy now, @Amazinite ?

**Comment by KiLEdEnNis** [comment]
I crashed twice when killing an annoying scanning interceptor w/ 20 Skylances & pressing M, not sure why these crashes happen all of a sudden
I bet it's some 0.9.5 commit, maybe some new AI thing

**Comment by Bladewood** [comment]
Can confirm that it happens.

**Comment by endless-sky** [comment]
This should be fixed by a75608b.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
