### ISSUE TITLE
Bombardment Cannon/Turret inaccuracy

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2057]
![bombardment inaccuracy](https://cloud.githubusercontent.com/assets/10348657/22204640/4a018524-e173-11e6-8553-a9aa07a04219.jpg)
it wasn't easy to clearly screenshot it and it's still quite unclear, so I'll say the 2 issues I saw:
1. it's very inaccurate vs fast ships (missing them for over 5 seconds because it shoots too far ahead of them)
2. with autofire, it sometimes won't even fire on ships that are within half it's range, and sometimes it shoots targets that aren't near yet

I know it's caused by the random velocity & stuff and I don't know how it could even be fixed, so is it gonna stay like this?

**Comment by Amazinite** [comment]
That happens when you use a beam weapon and a projectile weapon at the same time.

**Comment by Amazinite** [comment]
Sorry, thought those heavy lasers were coming from you.

**Comment by endless-sky** [comment]
The slow speed of the bombardment turret is intentional, to differentiate
it from any of the other existing weapons in the game and to balance it out
a bit. If it were faster it'd just be another generic long-range sniping
weapon like the Particle Cannon.

**Comment by Pointedstick** [comment]
Oooooh so we officially have a slow turret?

**Comment by endless-sky** [comment]
I mean the slow projectile speed.

**Comment by endless-sky** [comment]
But turrets with limited rotation speed and independent target tracking are on the to-do list for 0.9.7. (Not 0.9.6, because that'll just be a bug-fix release, and independent tracking will require significant AI changes.)

**Comment by Nechochwen-D** [comment]
I understand that this might be slightly off topic but are turret mounts with limited firing arcs in the books as well?

**Comment by KiLEdEnNis** [comment]
2 things
1. would that rotation speed be set on turrets or the hardpoints (same with arcs, I bet the turn rate is turrets & arc is hardoints)
2. what I meant with this issue is that the Bombardment weapons have some tracking issues, the speed is fine since they are meant for slow shower-fire (and I'm gonna make a not-so-fast projectile turret too that fires a strong shell every 2s :3)

**Comment by DingusShingleton** [comment]
I believe I remember turret firing arcs being brought up at some point but they were deemed a no go for some reason... can't seem to find it in the search. But the idea of capital ships broadsiding their targets is really cool, and it also means that you can add more turret hardpoints in general since fewer will be focusing a single target at a time. Not to mention that in that paradigm, a small agile ship with fast 360 turrets becomes much cooler! Fighters beware.... that's a space superiority warship right there.

 Such changes are gonna require bombad balancing though, as jar jar might say...

**Comment by KiLEdEnNis** [comment]
just enabling players to set an arc to turret hardpoints will keep ships fine but enable more options, maybe making a new hardpoint that just uses a turret slot but constraints the firing angle (as if between a gun & turret)

**Comment by DingusShingleton** [comment]
Well I think firing arcs would be based on the ship, and therefore hardcoded into the hull, no? That weapon layout diagram in the player info screen would look mighty fine with some cool firing arc graphics imo. Perhaps my history with warhammer 40k predisposes me toward firing arcs but dang if I'm not tickled by the idea

**Comment by KiLEdEnNis** [comment]
I mean being able to set the arc, being able to set the arc when creating the ship
it would make bigger ships less effective vs smaller ships which buffs fighters etc. too

**Comment by DingusShingleton** [comment]
Oh yes, when you said players I thought you meant players in the in-game sense. I agree.

**Comment by Nechochwen-D** [comment]
I would have the arc defined in the hardpoint along side an optional multiplier for rotation speed while the weapon itself would have the primary rotation speed value.

**Comment by KiLEdEnNis** [comment]
I feel like making an issue for this now

**Comment by DingusShingleton** [comment]
There have been at least two I think

**Comment by MessyMix** [comment]
The thing about turret arcs is that you can't put AMs effectively on turrets that aren't 360°. Or, at least, that would be frustrating.
Perhaps make AM bypass firing arc limitations.

**Comment by DingusShingleton** [comment]
Another way of looking it is that you have to consider which side of your ship going to be most defended. And if a ship has some wider hardpoints and some narrower, do you go offensive and put AM in the narrow ones or defensive and go vice versa?

**Comment by MessyMix** [comment]
@DingusShingleton Yes. Part of the frustration is the micromanagement we'll have to do. Because ultimately it makes it more _interesting_, but it comes with a level of frustration that needs to be considered.

**Comment by Pointedstick** [comment]
> Perhaps my history with warhammer 40k predisposes me toward firing arcs but dang if I'm not tickled by the idea.

I quite agree. Thin rear armor in particular would be nice, since it's mostly engines back there anyway. Would make sense that they're more vulnerable. And you could have Land-Raider-type ships that were unusually well-defended, to provide an interesting contrast. A video game is in many ways the best venue for an extremely crunchy game. 40k always suffered from the fact that you always had to remember all that stuff yourself, and by 7th edition, the rulebook was looking more like an encyclopedia.

**Comment by endless-sky** [comment]
Commit 7e90d21 improves the turret's accuracy a little bit. Individual bombardment projectiles vary in velocity by about 17%, and that commit makes the targeting AI use the average velocity instead of the minimum velocity when calculating the optimum firing angle.

**Comment by KiLEdEnNis** [comment]
alright, so this issue seems fixed
