### ISSUE TITLE
Overcapacity drones bypass shipyard & depreciation

### ISSUE THREAD

**Issue by Waladil** [endless-sky/endless-sky#2060]
If you have drones that you don't have bays to hold and land on a planet, you'll be prompted to sell them when you take off. However, they get sold at full price (no depreciation reduction) and even if there's no shipyard available.

I understand being able to get money out of them without a shipyard present to prevent people getting ripped off entirely, but they ought to be sold for their depreciated value. 

In related news, I made 9 million credits doing the There Might Be Riots quest where a fleet of drones fight with/around you. Captured like 50 of those little guys, sold them for 200k a pop -- their official value was only 50k each.

**Comment by KiLEdEnNis** [comment]
the only way this could be a bug is if you already owned >all< drones and landed after a ship with capacity got blown up in the same sector
basically for example you have 20 drones and you owned all of them for a while, then a ship that carries some of them got shot down to force you to sell some
did that apply here or did you buy the drones on the planet?

**Comment by Waladil** [comment]
Neither, @KiLEdEnNis . I captured the drones in space, then landed. Drones can be captured much like fighters, but they take no crew to man, so despite the fact there were 50 drones to snag I was able to get all of them without crew issues. 

The bug is that they sold at 100% value, their full non-depreciated cost. It's intentional that excess drones are sold when you take off from a planet, but they're the only thing that sell at full cost, not the newly depreciated costs.

**Comment by SonEasterZombie** [comment]
Does this happen with all fighter/drones or just drones?

**Comment by Bladewood** [comment]
Fighters and drones follow somewhat similar mechanics, so both I'd assume.

**Comment by KiLEdEnNis** [comment]
so you captured them, and they were the only drones you owned, and all were sold for the full price?
that is a bug then
did you check if it would also happened if you sold them in the shipyard instead of autoselling? it may be autosell that ignores depreciation

**Comment by SonEasterZombie** [comment]
that's what he's been saying this whole time...

**Comment by marphod** [comment]
As a sidebar, this also lets you sell the drones on uninhabited planets where the sale makes no sense (e.g. Far'en Lai)

**Comment by endless-sky** [comment]
I believe this was fixed by c021227.
