### ISSUE TITLE
Coalition jobs do not repeat

### ISSUE THREAD

**Issue by mootootwo** [endless-sky/endless-sky#2062]
All of the jobs in the "/data/coalition jobs.txt" are missing the "repeat" flag.  Thus, the player eventually runs out of jobs to perform.

https://github.com/endless-sky/endless-sky/blob/master/data/coalition%20jobs.txt

**Comment by mootootwo** [comment]
I've created a pull request to fix this:  https://github.com/endless-sky/endless-sky/pull/2063

Though I've almost certainly done it incorrectly.  First time making a contribution through Git via trial and error.

**Comment by KiLEdEnNis** [comment]
as long as you used tabs, not spaces, & made no typo's it's fine

**Comment by mootootwo** [comment]
I used tabs.  Since it was tested and works, I assume there are no typos.  

But I seem to have used a different end-of-line character (since it thinks the "job" line was replaced) and I'm worried about that.

Also, even though this is "fine", I'm not sure it is "right".   I think the pull request is for my entire fork (which contains just this one change) and not the individual file change its self.  I suspect that there is a better, more specific / atomic way of submitting changed files.

Are there any tutorials that you would recommend?

**Comment by Bladewood** [comment]
You did it right, don't worry.

> Also, even though this is "fine", I'm not sure it is "right". I think the pull request is for my entire fork (which contains just this one change) and not the individual file change its self. I suspect that there is a better, more specific / atomic way of submitting changed files.

[If you intend to create multiple pull requests, each pushing a different change, you can separate them by utilizing the "branch" system.](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/)

Which I forgot to do in my pull request. dammit.

**Comment by mootootwo** [comment]
Ah, useful, thanks.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
