### ISSUE TITLE
Multiple buttons on the Player Info/Ship Info screens use the same accelerator key (P)

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2064]
![accelerators](https://cloud.githubusercontent.com/assets/1097249/22259324/1931db2e-e222-11e6-9704-68e1d8c07ec3.png)

**Comment by jafdy** [comment]
And previous for that matter.

**Comment by KiLEdEnNis** [comment]
I don't mind the player info one, but park & previous conflicting is annoying
but as far as I know this is the only conflicting hotkey issue

**Comment by Pointedstick** [comment]
FYI the arrow keys work for "Next" and "Previous".

**Comment by KiLEdEnNis** [comment]
ah good to know

**Comment by Pointedstick** [comment]
Confirmed fixed with https://github.com/endless-sky/endless-sky/commit/f61d6ea876d34589e27f8c5c5d7b441136cabd38.
