### ISSUE TITLE
Who completed the second half of the Wanderer storyline without cheating?

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2065]
Thumbs down if you had to edit any game or save files to beat the campaign, thumbs up if you were able to complete it without cheating.

Then post a comment indicating what you had to do to win, one way or another.

**Comment by KiLEdEnNis** [comment]
very old save file: 1 Hurricane 4 Dercho's with 2 Antimatter Cores each, 4 Skylances each, and some battles took VERY long with my fleet and hardly any Wanderer ships left
my fleet wasn't in that much trouble (well, a couple of times: their disruptors are so strong)
but technically that's cheating

**Comment by gunqqer** [comment]
Haven't completed the storyline yet but I probably can do it without cheating. I have 24 (Not cheated, I just have no life) Kor Mereti (?) ships (It was the biggest ship from the one with the disrupters. I alway get the factions mixed up and also the numbers). They have 6 Skylances on them EACH so I probably can take anything they throw at me. If I can't well... shit man

**Comment by KiLEdEnNis** [comment]
well, @Pointedstick should update: without a huge fleet
anyone can beat the Mereti with a big enough fleet

**Comment by Bladewood** [comment]
Arfecta.

Though I did have to edit my reputation with the Quarg.

**Comment by Amazinite** [comment]
1 custom Derecho + 2 captured Kar Ik Vots for the first half.
Same Derecho + 4 stock Derechoes for the second half. 

It really isn't that hard to beat, and I don't see why such a big deal is being made over it. It's just not a single ship campaign.

**Comment by Pointedstick** [comment]
I suppose you guys are right.
