### ISSUE TITLE
Not eligible for loan

### ISSUE THREAD

**Issue by Nomen-Usoris** [endless-sky/endless-sky#2066]
Hello, I recently installed 0.9.5 and so I assume that it's a bug with the new update.  My credit score is 800 and I have a steady income, but I can't withdraw a loan from the bank. If I go there, it reads "You do not qualify for further loans at this time."  I have not taken out a loan since I started the game unless you count the first one to buy your first ship

**Comment by Amazinite** [comment]
Duplicate #2049 
Please close this.
