### ISSUE TITLE
Licences for Outfits

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#2069]
The same way ships have licences now but for outfits.
I feel this is important now because people are asking how to get the Coalition outfits. If they where put behind a licence then people might recognize that they need to do something for it.
I feel like someone brought this up before but I can't find the issue for it.

**Comment by Bladewood** [comment]
Indeed, they did, you just used a different spelling. https://github.com/endless-sky/endless-sky/issues/1395

**Comment by jafdy** [comment]
Thanks.
