### ISSUE TITLE
Wanderer Storyline Typos

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2074]
"You drop of" instead of 'off'.

**Comment by Alkallid** [comment]
I might put any other typos I find here, so i I don't close that's why.

**Comment by Alkallid** [comment]
"the Wanderer war machine is continuing to ramp up with remarkable speed"
Does this imply that "the Wander war machine" is itself a noun, like a concept of their technological advancement? It sounds a bit iffy.

**Comment by endless-sky** [comment]
> **war machine**, _noun_: the military resources of a country organized for waging war.

**Comment by endless-sky** [comment]
Fixed the first typo in 5474f75.

**Comment by Alkallid** [comment]
What does "beach a breath" mean?

**Comment by Alkallid** [comment]
Neeever mind. Breathing a sigh is a thing.

**Comment by endless-sky** [comment]
No, that's a typo (should be "breathes a sigh of relief"). Good catch. Fixed in fe724a0.
