### ISSUE TITLE
First Death Message Typo

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2078]
"The universe can [be] a..."
I actually have no idea where the start messages are, so I can't fix it myself.

**Comment by MessyMix** [comment]
What death message are you talking about? It's not immediately clear from your post.

**Comment by Alkallid** [comment]
When you start a new pilot, there are these nine messages that pop up after something happens. Dying is one of them. There's even a setting for resetting it in the other tab in preferences.

**Comment by MessyMix** [comment]
@Alkallid just found it. Will fix.

**Comment by MessyMix** [comment]
#2079

**Comment by Bladewood** [comment]
I did not know there were death messages until I read this issue.

That explains why it says
`Reactivate first-time help   9 / 11`

...Wait. What.

**Comment by MessyMix** [comment]
For me it says 9/9... weird?

**Comment by Amazinite** [comment]
Two new help messages got moved from the source code to the text files in a recent commit, so that's why Bladewood's says 11.

**Comment by Bladewood** [comment]
Huh, so that's what caused it. https://github.com/endless-sky/endless-sky/commit/64a6b0b9c47743a68dffb161aabb2d800e09eb49

**Comment by MessyMix** [comment]
90a892620d8d3570fbbb975fa70e68dc636edc18

**Comment by KiLEdEnNis** [comment]
if only pressing it would reset it to 0, but then pressing it again would put it at 11/11 (or whatever later)
I pressed it wondering what it was & I couldn't turn it off
