### ISSUE TITLE
[bug/content] Mention Hai to Coalition before discovering Hai

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#2082]
In the mission on Ring of Friendship, you tell the Heliarchs/Coalition about the Hai, but you can do this before you have met the Hai.

**Comment by KiLEdEnNis** [comment]
and it's not even that "hard" or "rare" for this to happen
you could just do the FW campaign & decide you're going South first

**Comment by Lineth** [comment]
This reminds me, it is also possible to encounter the Deneb pug before the free worlds section where they come up. Should there be a first contact mission for such an occasion? maybe mention it when they invade? Or just have the pug not be there at all until they start the invasion?

**Comment by Bladewood** [comment]
Well, in that case, you're not even supposed to get a jump drive so early on in the game, or so Michael would say.

**Comment by Lineth** [comment]
Well, you can get them from the Korath exile pirates with a strong fleet/lucky break. A long shot, but I just thought it'd be a nice touch. Not sure on how to go about it though.

**Comment by KiLEdEnNis** [comment]
having a second fourth wall break then
Pug be like "how did you get here? you're not supposed to have a jump drive yet"
and the Pug apparently have knowledge from the future, so it wouldn't even be a fourth wall break, just the Pug misreading the future

**Comment by toilethinges** [comment]
@Lineth a strong fleet? Never. ;)

All you actually need is any ship that's slightly maneuverable and has 20+ cargo. Go to Durax, bribe pirates, wait. Let them disable a Raider (may take a while, they destroy them a lot) and take the Jump Drive. I used a Quicksilver with a cargo expansion.

Anyway, this wouldn't be too hard. Just a branch with has "Hai: First Contact: done" and another without.

**Comment by Bladewood** [comment]
@KiLEdEnNis the pug would probably be prepared for every eventuality.

**Comment by KiLEdEnNis** [comment]
then if you land in Deneb
"A group of pale yellow [describe Pug] approach you. "Well well, the human acquired a jump drive and was eager to explore." then some other stuff

**Comment by Lineth** [comment]
Aren't pug blue? Their  ships are a orangeish-yellow but I recall that the pug have long spindly limbs, short barrel bodies and off-blue skin, like their blood.

I wonder if there's artwork of the alien races physical forms anywhere.

Utterly irrelevant, I know.

**Comment by jafdy** [comment]
>small group of the pale-skinned, delicate aliens. The Pug are oddly proportioned, with long arms and legs but short, barrel-shaped torsos and large heads, and although they only have two legs, their gait is vaguely insectoid.

From FW Pug 3.

**Comment by KiLEdEnNis** [comment]
I thought they were light yellow (ike yellow-whiteish) with blue blood
if MZ approves I could write the branch o:

**Comment by MessyMix** [comment]
#2087

**Comment by endless-sky** [comment]
I created concept art for the Hai but never got around to the other species. :)

![dangerous](https://cloud.githubusercontent.com/assets/11450262/22531510/401571e0-e8af-11e6-945b-16bfc50a458c.png)

**Comment by Bladewood** [comment]
LOL

**Comment by Amazinite** [comment]
Golden. 👌

**Comment by Lineth** [comment]
yes

**Comment by endless-sky** [comment]
Fixed by merging #2087.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
