### ISSUE TITLE
Better fine, and overall illegality, system

### ISSUE THREAD

**Issue by Mcgode** [endless-sky/endless-sky#2084]
I find it interesting to have a fine mechanic for some items such as Nerve Gas (I don't remember if there are others) but I find it quite limited. Right now, it seems like it is an all-or-none feature, governments will either fine you or not for any items in the 'illegal' category of outfits.

I think it would be a great addition to have some kind of 'laws'. By that I mean that  a specific government should be able to prohibit some items, or a category of potentially illegal items. For instance, the Korath could be ok with something like nerve gas, which is illegal in human space, but forbid any kind of AI-controlled stuff, something that humans wouldn't necessarily prohibit. 

In my opinion, even though it may not have a big impact on the game as it is now, this could be a nice feature to have in plugins, whether you make some new 'illegal' stuff or you create a new alien race with different morals.

**Comment by jafdy** [comment]
#1429

**Comment by Mcgode** [comment]
Yup, did not look into closed issues :p
