### ISSUE TITLE
Widen the background of system names in map

### ISSUE THREAD

**Issue by Mcgode** [endless-sky/endless-sky#2085]
I'm currently working on a new race with a new galaxy and I've run into this issue:
![kaynz screenshot](https://cloud.githubusercontent.com/assets/8111506/22478176/2fe14cac-e7e9-11e6-8c4c-31b073529e6c.png)
(by the way, the map is still a WIP)
I'd like to know if a fix is doable, and conceivable, and if not, then I'll just have to find another name, probably killing the symbolic sense :/

**Comment by KiLEdEnNis** [comment]
not sure if the widening is gonna happen, it's a very long name

**Comment by DingusShingleton** [comment]
"Ashes of Golden Ages" would fit.... certainly not perfect but it's something  ¯\_(ツ)_/¯

**Comment by Amazinite** [comment]
"Gamma Cassiopeiae" is the official max length on names that fit in the UI.

**Comment by jafdy** [comment]
It would be easy enough to fix but it is unlikely to happen on account of the UI already fits all familiar names and there will always be a name that is just one bit longer that won't fit.
"Ashes of a Golden Age" would probably fit.

**Comment by Mcgode** [comment]
Ok, thanks for the replies ;)

**Comment by Bladewood** [comment]
Golden Ashes?
