### ISSUE TITLE
[wiki]build instructions precision  for path on windows.

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#2088]
hi, just to ease others shall they try the same as me since the original sentence left me pondering where that path was stored for a long time, until I found out through a random forum post that the cbp project file was a simple editable text file.

**replace**
`If you don't want to have to edit the paths in the Code::Blocks file, unpack the "dev64" folder directly into C:\. `
**with**
`If you don't want to have to edit the paths in the Code::Blocks project file (cbp), unpack the "dev64" folder directly into C:\. `

**replace**
`C:\Program Files\mingw64\x86_64-w64-mingw32\lib\ you will have to adjust the paths in the Code::Blocks file`
**with**
`C:\Program Files\mingw64\x86_64-w64-mingw32\lib\ you will have to adjust the paths in the Code::Blocks project file (cbp)`

**Comment by endless-sky** [comment]
Editing the file through Code::Blocks is actually preferable to editing it in a text file - it avoids the risk of messing up the file and leaving it unreadable.

**Comment by whismerhill** [comment]
In this case, I don't know how to reformulate the sentences, cause at this moment I am still unable to find all paths in question from inside codeblocks itself :o 
and believe me, I searched. editing the cbp files directly has been the most simple for me so far, and I wish I had known that earlier, so as not to waste as much time scratching my head :p 

thanks for answering anyway.

**Comment by whismerhill** [comment]
@endless-sky 
found out where you have to find those
let's just say, it's not obvious from first glance when you don't know the software and I found nothing while searching on the web either (probably because I didn't know where to look)

> in C::B, those path can be found in : endless sky project properties, build options, linker. or else the cbp file is editable.
I suggest inserting this sentence somewhere in the wiki. It should make things simpler for others.
If you still don't agree then I'll close this.
