### ISSUE TITLE
Corporate Espionage doesn't reset after save revert

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2090]
Whenever I take on a corporate espionage mission and then revert to an earlier save, the target ship doesn't warp in as it's supposed to. It's happened twice to me so far; can anyone else confirm?

**Comment by endless-sky** [comment]
A ship's destination isn't saved in the saved game file, so if it's "entering" but not set to follow the player, it may decide when you reload the game to go somewhere else.

**Comment by endless-sky** [comment]
Commit 0fe8ba7 fixes this - it has all ships store their destination, if chosen, in the saved game.

**Comment by MessyMix** [comment]
@endless-sky thank you so much. Such a legend. :D
