### ISSUE TITLE
Steam hotfix for Coalition jobs

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#2091]
People have noticed that they are broken and they are a good late game way of making money if they repeat.

**Comment by Pointedstick** [comment]
Broken in what way? Why shouldn't jobs repeat?

**Comment by Wrzlprnft** [comment]
broken in terms of: the keyword is missing in all of the jobs in the version which was released on steam. so, every job just occurs once

**Comment by jafdy** [comment]
@endless-sky If you can yes/no a hotfix that would be great. 
If no then we can put up an "unofficial" fix.

**Comment by MessyMix** [comment]
@Pointedstick they're just saying that coalition jobs _don't_ repeat in beta or standard builds, and that players are getting agitated over it.
