### ISSUE TITLE
"Wanderers: Alpha Surveillance J" Has No Description

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2094]
^

**Comment by MessyMix** [comment]
@Alkallid, I'll fix it. It doesn't seem to have a name OR a description. Can you confirm / tell me what name shows up in the missions board? I want to know if it shows "Alpha Surveillance J" or is invisible, which may be intended.

**Comment by Alkallid** [comment]
It has a name, but I can't access my computer right now. It also had a destination tag.

**Comment by MessyMix** [comment]
Okay. Well it doesn't have a `<name>` tag given by the data. I think it might revert to the mission name itself. I added a proper name and description for the mission. #2097

**Comment by endless-sky** [comment]
Fixed by merging #2097.
