### ISSUE TITLE
Different application of licenses

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#2096]
What if instead of applying the license to the ship or outfit itself each government had a list of what ships required what licenses as well as reciprocity with other governments and exemptions therefrom.

I personally like the idea of the Republic requiring onerous licenses of the captains, getting back to some of the lore behind the Free Worlds defecting. On the other hand I can see the reasoning behind not doing so as it would entail a greater level of management and the Steamies would likely blow their lids.

If people like the idea I'll try putting together a PR for it.

**Comment by jafdy** [comment]
#275 3rd comment

**Comment by Amazinite** [comment]
Yeah, as Jafdy pointed out, this already use to be a thing and was removed.
