### ISSUE TITLE
Low crew mechanics too punishing?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2099]
As I understand, ship's crew is made of two components: flight crew (as defined by hull) + gunners (one for each offensive turret equipped). So it is nonsense for the ship to jerk when flight crew is intact and gunner's are missing (I imagine gunners are more proficient at fighting, so they would go before pilots and their death's would be more likely, or, if our crew are jacks of all trades, there is no reason for turret seat to not be empty, when the ship tries to maneuver), hence, this proposal:

if currentCrew >= flightCrew + gunners, ship operates normally
if currentCrew < flightCrew + gunners, then:

if currentCrew <= flightCrew, disable automatic firing.
If player thrusts or turns ship, then all available hands fill flightCrew positins ATM. Ship moves erratically, when some flightCrew positions are still empty. Leftovers (if applicable) man closest turrets to the current target. The other turrets are silent.
If player fires manually (by holding Fire button), then priorities shift to turrets, All possible turrets are manned (if there are not enough gunners, some farthest ones will still not fire, and it means that for the moment control over ship's movement is lost altogether), and leftovers are relegated to flightCrew (which results in erratic movement).

Also, when the ship is moving erratically because of low crew, it wouldn't sporadically stop turning because of it if it's already turning. It would sporadically fail to stop to turn (because momentum).

**Comment by KiLEdEnNis** [comment]
brought up several times before
death mechanics are meant to give players who have dead crew a disadvantage, balance over realism
please check for duplicates next time

**Comment by Tadrix** [comment]
As it is now, the players are punished for fitting some more turrets instead of more ships + anti-missiles on turret mounts. It isn't logical at all. I wouldn't bring this up if erratics started just when crew drops below flightCrew (as ship circling around planet and unsuccessfully trying to land doesn't add anything to gameplay and instead just pisses off players). If it was brought up several times, it was for a reason. I hope someone will do it some more.

Now, I understand that understaffed ship cannot operate normally, even if just gunners are absent, so I wrote of a way to make it work. Probably someone could think of something better.

However, it seems to me that you didn't take your time to read and think of possible improvements, instead thinking of this as just another whining about current mechanics and quickly asserting that nothing needs to be changed.

**Comment by Amazinite** [comment]
Pretty much what I asked for in #1127.

**Comment by KiLEdEnNis** [comment]
in a ship w/ like 30+ crew, an extra turret hardly punishes players though

**Comment by Tadrix** [comment]
Exactly, but in smaller ones it do.

See, I'm seeing a trend in which experienced players think the game is too easy and try to make it harder. And I agree that it should be challenging. But these measures hurt those who are just beginning their journey through the galaxy. It shouldn't be this way.

**Comment by KiLEdEnNis** [comment]
I doubt new players will actually try and capture pirate ships, but even then they'll see they'll lose crew
simply put: MZ wanted it as a disadvantage for boarding and he wants to keep it like that

**Comment by jafdy** [comment]
If you want the easy way to make credits then you have the option of trading. Trading was a staple for me when I first played and is a staple for me now, after well over a year.

**Comment by Tadrix** [comment]
Why they shouldn't try? If I'm a newbie, flying a (for example) Bounder, and I'm seeing a lot of disabled pirate ships, it could occur to me to take some more people on board and try to get more ships.

Also, storywise, there are two serious flaws:
1) There isn't any way to, for example, arrest pirates and turn them to authorities. Or tow their ship to the nearest landable planet in the same system, if there is one. The only choice is kill them, or… kill them. Or watch someone else kill them. Pirates sometimes rave about being at the mercy of such a wimp, except, there's no mercy. Not even of a fair trial. But ok, it's just a game.
2) There's this narrative about asking my crew to do more than they signed for. This is BS. Yep, it would be a strong point for minimum crew (flight crew and gunners), but usually there's an _extra_ crew. What else I would hire them for? They are basically marines. I'd be content to pay them double, or even quintuple if I'd be spared from hearing about asking too much. They are there to board ships. I'm paying for it. There isn't any other reason to carry extra crew. Period.

**Comment by jafdy** [comment]
#1127 Don't change the subject. 
There are other threads that talk about you new attitude on this.

**Comment by Tadrix** [comment]
That was fast.

There no really "new" attitude, I understand that game creator's stance on some issues is different than mine, that's all.
