### ISSUE TITLE
No way to get rid of a captured drone

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#21]
If you capture a drone in a system without a shipyard, there is no way to get rid of it.  The Republic will keep fining you over and over.

As the messages during boarding talk about fighting humans, I guess drones should simply be uncaptureable.  It's unobvious how to do that drone hunting mission already.

**Comment by endless-sky** [comment]
I've modified the boarding panel to not let you capture a drone or fighter unless a ship in your fleet has a bay free to hold it (4a35478). If you want to dismiss the drone from your fleet, the easy way to do that is to target it (with Shift + &lt;next target key&gt;) and shoot at it until it's dead. :)

**Comment by endless-sky** [comment]
With the modification to the boarding panel, I've tested and verified that it won't let you capture a drone that you cannot hold.
