### ISSUE TITLE
0.8.7 on OS X 10.11: save game title can escape the bounds of the text box

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#210]
<img width="358" alt="too long" src="https://cloud.githubusercontent.com/assets/1097249/11171985/ab222198-8bba-11e5-8008-ea7673d80612.png">

**Comment by endless-sky** [comment]
This can actually happen in various other places too, including when you enter the snapshot name in the dialog field in the first place. So, I should probably figure out a more general way to deal with text overflow, even though fixing this one particular instance is rather simple.

**Comment by endless-sky** [comment]
Fixed in a0f1064. Eventually I should do a more thorough overhaul of the load / save UI code, though, because it's pretty messy.

**Comment by Pointedstick** [comment]
Confirmed. Thanks!
