### ISSUE TITLE
Feature Request: Tractor beams which automatically pull floatsam to ship; increase floatsam longevity

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2102]
For now, if asteroid was faster, than heavier ship may not manage to get in time there when chunks disappear (which they IMO shouldn't do — but I understand that there are limits how many objects game can track at once). It would be nice if dropped cargo / asteroid shards would exist a little longer, and if there was something like tiny tractor beam especially for these. Also, it would be awesome if it would be possible to give flagship's cargo to other ship in space (kind of like boarding works, but the other way round, perhaps bound to other button). Also, it would be an awesome possibility for some missions (meet up unobserved in uninhabited system, pass some cargo).
Key bindings: It would be nice to be able to UNselect a ship without need to scroll through all of them, and to be able to select an asteroid (even if just with a mouse). Or probably I'm just a dummie — but it's no fun accidentally killing an escort or allied ship, or pressing frantically "next ship" while an asteroid flies by.

**Comment by KiLEdEnNis** [comment]
a hotkey to let escorts collect flotsam would be useful, but a tractor beam isn't gonna happen, it probably can't even be coded to pull flotsam and nothing else

**Comment by jafdy** [comment]
>possible to give flagship's cargo to other ship in space

Point you back side at them and dump the stuff.

**Comment by DingusShingleton** [comment]
I actually did that... I made a small mining ship/mining laser plugin and posted up in a system with bountiful neodymium. The profit was real. Inevitably a few units would go flying into oblivion but I was able to get the vast majority into my escorts hold. Pretty fun stuff.

**Comment by Tadrix** [comment]
Sounds nice. Any chances it gets included in the game?

**Comment by jafdy** [comment]
@Tadrix he's saying that he is dumping cargo at his escorts.

**Comment by Tadrix** [comment]
@jafdy Oh, ok. Now I feel dumb. I understood that he made a working tractor beam for pulling floatsam towards his ship (what this feature request was about).
