### ISSUE TITLE
Coalition typos

### ISSUE THREAD

**Issue by ldsgsm** [endless-sky/endless-sky#2106]
On New Finding, the description text for the planet includes the phrase "making it difficult for soil to accumulated" which is not correct English.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/blob/master/data/map.txt#L24327
> Due to complex atmospheric currents and swiftly changing seasons, the surface of New Finding is constantly scoured by powerful winds, making it difficult for soil to accumulate except in sheltered canyons and gorges. Each of these patches of greenery stands like an island amid a sea of bare rock. Over time, where the forests are able to take hold and grow, they spread outward and begin to turn more of the rock into habitable soil. On the exposed slopes, rock slides are a constant danger.

Are you using a release build?

**Comment by ldsgsm** [comment]
I just opted in for beta on Steam, when 0.9.5 came out. Looks like someone
solved the problem at some point though.

**Comment by endless-sky** [comment]
This was fixed in d240148.
