### ISSUE TITLE
Name/Description not showing up on Alpha Surveillance J

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#2108]
[Michael Zahniser.txt](https://github.com/endless-sky/endless-sky/files/752651/Michael.Zahniser.txt)

Haha, funny, my name is Michael Zahniser. In the save file, that is.

Anyway, there should be a name and description, but in the save file and in game there aren't. I'm not sure why, but I've been having similar issues, such as missions not failing/disappearing until a day or two after they should be gone.

**Comment by Lineth** [comment]
ITT: MZ has a split personality.

**Comment by toilethinges** [comment]
Well, I just looked in my data files, and somehow when I downloaded the data files those lines got removed. :/

**Comment by toilethinges** [comment]
Nevermind, that was actually a commit from Messymix that I didn't have in my compilation.

**Comment by Alkallid** [comment]
Heheh, get ninja'd by several days.
