### ISSUE TITLE
When jumping into a system on a mission, escorts don't always enter the same way you do

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#2109]
Normally when jumping into a system, you and your fleet will enter "centered" on the major planet in that system. If you have a mission to land on a different planet, you will enter "centered" on that planet, but your escorts will still be "centered" on the usual planet. This is easiest to see when jumping into Sol with a mission for Mars.

This is a pretty minor bug, though I can imagine situations where it would be important; e.g. a player flying a heavy freighter, with interceptors for escorts, jumping into a system and being caught far from his/her protection...

**Comment by Alkallid** [comment]
I don't know how related this is, but sometimes when taking off right after reloading when escorts are in-system but still on "hyperdrive cooldown" they will seem to warp in from random directions.

**Comment by endless-sky** [comment]
Fixed in 7a38ab5.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
