### ISSUE TITLE
Add missions that are triggered by the player having extra jump drives to sell

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#211]
During the Pug storyline, I fond myself easily able to board disabled Pug ships and steal their Jump Drives. In the context of Jump Drive technology being highly coveted and the units themselves being rare and precious, it seems odd that I would be able to obtain a large number of them without being able to use this to radically alter the galactic balance of power. Nobody from the Republic navy or Free Worlds militia seemed interested in fitting my cargo hold full of Jump Drives to their flagships. Once I discovered the Hai renegades, it was especially awkward after they asked for Jump Drive technology and the only response was, "Sorry, Humans don't know it." I could easily have said, "Well, I happen to have half a dozen in my cargo hold right now! I bet you could jump a flotilla of Shield Beetles a bit south and conquer the Korath! What do you want for them?"

Maybe you shouldn't be able to steal Jump Drives. In fact, maybe it should be explained why you're permitted to keep yours!

**Comment by naehc** [comment]
Jump drives aren't restricted to story missions by any means; the simple way to get one is from one of the Korath raiders that relatively often visit the eastern edges of Syndicate/Pirate space (of course you need a decent ship/fleet to disable one of those, but it doesn't rely on mission progress). Then once you have one, going to Korath systems to make a full fleet jump-capable makes it even simpler (no navy or pirates to interfere there). 

Anyway, removing the ability to loot them would be a major gameplay change, and as I see them mainly as a convenience feature which makes long distance travel quicker in exchange for much higher fuel use, an unwelcome change at that. There's also the EV Nova precedent of the Multi-Jump Organ, which I even think was more powerful, given how many jumps it let you effectively skip. Finally, I'd like to see any (navy/free worlds authorities) try to take away my hard-won jump drives! ;)

**Comment by Pointedstick** [comment]
Yes, I think it would be really cool if missions could respond to your plundered alien tech. I kept expecting that to happen, in fact. I specifically looted a bunch of weapons from the Pug ships with the expectation that someone's techs would want the alien weapons (the precedent of being interested in unfamiliar weapons having been set in the Free World mission where you need to plunder Electron Beams from a Republic ship) but alas nobody was interested except for the outfitters I eventually sold them to.

**Comment by endless-sky** [comment]
The Unfettered will now offer to buy jump drives from you, and offer their friendship and some jobs and information in return, in addition to money. It'll take a whole new mission string to actually have that alter the balance of power in that sector, but it's at least a start.

**Comment by Pointedstick** [comment]
Perfect! Just what I was looking for.
