### ISSUE TITLE
[bug] You can hail wormholes

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#2110]
The name says it all, but if you're not so sure...

... http://prntscr.com/e4mt75

Edit: THE PUG HAVE SPOKEN

**Comment by Bladewood** [comment]
seems legit

**Comment by Pointedstick** [comment]
I wonder what kind of defense fleet the wormhole has. 😝

**Comment by toilethinges** [comment]
@Pointedstick that was one of the first things I tried. ;)

**Comment by endless-sky** [comment]
Fixed in a377fd8.

**Comment by endless-sky** [comment]
Actually, better yet, who else has ideas for a good message? It could be randomized each time you hail the wormhole, sort of like the unit acknowledgement speech Easter egg in Warcraft...

"The gaping hole in the fabric of the universe does not respond to your hail."
"Hailing a wormhole is as pointless as spitting into the ocean."
"The wormhole spins on in silence, oblivious to your efforts at communication."
"Like most wormholes, this one does not appear to be very talkative."
"You shout into the abyss, but the abyss does not so much as whisper back."

**Comment by Pointedstick** [comment]
"The wormhole appears to be ignoring your hails."

**Comment by Amazinite** [comment]
"Despite your many efforts to communicate, the wormhole does not say a word in response."
"You think that you hear the wormhole say something, but it is nothing more than the normal static of the cosmos."
"[The wormhole says something in a language that you do not understand... The language of silence]."

**Comment by KiLEdEnNis** [comment]
feminist wormhole
"don't you dare going through me or I'll sue you for sexual harassment"
too bad that'll get people to complain

**Comment by Bladewood** [comment]
*slow applaud*

**Comment by Bladewood** [comment]
Wait, should the message have parentheses around it?

Like with that one asteroid that we glue ion engines onto.

**Comment by whismerhill** [comment]
"As you hail the galactic anomaly, your crew looks at you as if horns grew on your head"

**Comment by Nechochwen-D** [comment]
"Upon hailing the wormhole you seem to receive replies from several sources"

**Comment by jafdy** [comment]
"You hail the wormhole. Maybe a ship on the other side thinks it's being hailed by the wormhole."

**Comment by KiLEdEnNis** [comment]
@jafdy that one's really good
please MZ, add that one

**Comment by Wrzlprnft** [comment]
“oh.nice to meet you. i guess the star in (whatever system sad archie was in) feels lonley too. you should talk to him“.... while you go through the answer several times, you realize this must have been a prank by a ship on the other side/ a passing by spaceship.

**Comment by Bladewood** [comment]
I think we can close this.
