### ISSUE TITLE
Suggestion: Robotic systems (or balanced androids)

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2115]
A proposition: Androids that take space and consume power.

Concept:
If ship is to be outfitted with androids, it first needs recharging and maintenance station. This station takes outfit space (8–20?) and generates heat. Moreover, each android not only lowers crew requirement by one, but additionally lowers bunk space by two (for storage) and constantly consumes power (perhaps 3/s per one unit?)

An alternative (applicable only to light and bigger ships, not small ones like interceptors):
Systems (one per ship or specific outfit) which take space (around 5 per unit) which consume power and generate heat. Examples:
Advanced Autopilot Computer (−2 crew, one per ship, perhaps 7–8 outfit space), Advanced Engine Control (−1 crew, one per ship, 5–6 outfit space), Automated Turret Control (−1 crew, one per offensive turret, 5 outfit space), Automated Storage System (−1 crew, one per ship, −10 cargo space, less heat and energy losses than for others).
That last one could have description like: "This state-of-the-art robotic cargo loading system will automatically weight and fill your hold in the best possible way to retain ship's balance, freeing crane's human operator for other tasks."

**Comment by Amazinite** [comment]
#1100 
Dead topic.

**Comment by Tadrix** [comment]
Sorry. Didn't search by "androids"
