### ISSUE TITLE
Escort Icons Not Going Green

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2116]
No matter what type of drive they're using, escort icons aren't going green for me anymore. The yellow icon does show, however. I'm running the standard beta, not compiling.

**Comment by toilethinges** [comment]
The icons only appear as green when you select them, now. They will simply turn white when they're ready to jump.

**Comment by Alkallid** [comment]
Oooooh.

**Comment by Alkallid** [comment]
Wait, but could it be made so that if none are selected, then any ship will go green? If you have a considerable fleet of different sizes, you wouldn't really want to shift select all of them to make sure they're ready.

**Comment by endless-sky** [comment]
The colors were changed to be a bit more logical. Escorts show up as green in your targeting display, so now that you can multi-select escort icons, green is the only color that makes sense to indicate the escorts that are selected.

It's pretty standard in UIs to use yellow for warnings and red for errors; the escort icons now turn yellow if the ship is able to jump but not ready, and red if the ship is unable to jump. When the icon turns back to white, it means there's nothing impeding the ship, i.e. it's ready to jump.
