### ISSUE TITLE
[Improvement]space navigation : player "capital" ship color/outline/direction ?....

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#2117]
when controlling 40+ ships, it becomes a real mess to see your own ship direction & whatnot
particularly with the new zoom feature, which albeit a definite improvement for watching whole fleet movements, makes your ship even harder to track down on the screen.

I suggest one of the following to alleviate that issue : 

1. custom ship colors (albeit might conflict with free worlds / story / historical coherency colors)
2. ship customization ??? (no idea which form it could take though)
3. ship different shadowing ???
4. differently colored HP-shield bars / or custom colored HP-shield bars
5. ship outline
6. "compass" (not as a regular compass, since there is no gravity but I suppose you get the meaning ?)
7. and last but not least : semi-transparent directional arrows that appear dynamically when lots of your ships are stacked (would be on top of your ship)
8. possibly make any/some choice optional.

-note: may need one or more of those above.

Discuss.

**Comment by Wrzlprnft** [comment]
i guess you include the ring hp and shield overlay as not sufficient in that statement?
i guess they may need indeed a little adaptation to the new zoom

**Comment by jafdy** [comment]
If it helps your own ships is always drawn on top.

**Comment by whismerhill** [comment]
@Wrzlprnft 
I'll let you decide if it is sufficient : http://steamcommunity.com/id/whispershill/screenshot/87094544885271301

notes: this screen was taken not during combat. In combat while there is possibly less ships, remains the fact that it's IN combat therefore you have other things to worry about than trying to decrypt the image to see where's your ship.  At least it's my experience that I'm sometime using "guard" (because otherwise my fleet tends to disperse too much) and then sometimes it becomes difficult to know my heading direction.

feel free to discuss ^^

**Comment by Amazinite** [comment]
Don't play with the HUD. Makes it easy to spot yourself. :)

**Comment by whismerhill** [comment]
@Amazinite 
not sure I understand, you mean I should zoom back in ?

**Comment by DingusShingleton** [comment]
They mean turn off the circular health indicators

**Comment by KiLEdEnNis** [comment]
I can't even play WITH the circle things, they're so big & ugly to me

**Comment by whismerhill** [comment]
indeed turning off the circular indicators makes it easier to spot yourself, however I find them rather useful otherwise to keep track of individual fleet members HP. I'd even go as far as say it's essential for large fleet battles, as long as your ships can't fully handle any amount of punishment  (example: I'll often hide a damage ship inside my cluster of unarmed ) The other icons don't keep track of individual ships HP once your fleet is big enough.

**Comment by KiLEdEnNis** [comment]
left bottom is all I need, and it makes the view better & less cluttered

**Comment by Alkallid** [comment]
Make the flagship icon in the top-right face the same direction as you instead of staying static all the time?

**Comment by KiLEdEnNis** [comment]
could be a good idea indeed

**Comment by themightygrunt** [comment]
There's circular health indicators? 😮

**Comment by KiLEdEnNis** [comment]
yes and they're ugly big circles around your ship

**Comment by Bladewood** [comment]
@themightygrunt preferences, settings, "show status overlays" on

**Comment by themightygrunt** [comment]
Gotcha, it'd probably just hinder me at this point, I'm so used to using the lower left things c:

**Comment by endless-sky** [comment]
Well, now that settings are on a separate preferences page and there's plenty of space to add more of them, I guess there's not reason *not* to make this an option. Added in b9946d2:

![highlight](https://cloud.githubusercontent.com/assets/11450262/22839298/d30e945c-ef96-11e6-8416-b3b974ae6bf0.jpg)

![pref](https://cloud.githubusercontent.com/assets/11450262/22839305/d6ecae74-ef96-11e6-8d04-e3a2bc96f0ac.jpg)

**Comment by Wrzlprnft** [comment]
great addition :)

**Comment by whismerhill** [comment]
good idea.
compiled the latest commit & got that : 
http://prntscr.com/e8rqi4

**Comment by Amazinite** [comment]
Lol, looks like the outline zoomed in while everything else zoomed out.

**Comment by whismerhill** [comment]
yeh it doesn't change with zoom level ^^

**Comment by Rakete1111** [comment]
@whismerhill You should open an issue for that.

**Comment by Bladewood** [comment]
Ha, it's kind of like this article. https://what-if.xkcd.com/136/
[Arachnophobes, express the utmost caution.]

**Comment by whismerhill** [comment]
@Rakete1111 
thanks for the tip, I just did, I'm still unfamiliar with github workflow

**Comment by whismerhill** [comment]
so I played a bit with the new outline & hp/shields overlay both enabled

the new outline definetely helps a lot, to the point that I think this issue might be closed.
so I'll just go ahead & close it, feel free to reopen it or ask for it if deemed necessary.
