### ISSUE TITLE
[Idea] changeable swizzle to disguise ship

### ISSUE THREAD

**Issue by SonEasterZombie** [endless-sky/endless-sky#2118]
So basically you could give your fleet a custom paint job in order to temporarily fool an aggressive faction that you are friendly. For example, painting your ship blue in order to make the republic think you are a merchant (until they scan you or until you interact with a planet) during the FW campaign. This could also solve #2117

**Comment by Bladewood** [comment]
It's dishonest.

**Comment by SonEasterZombie** [comment]
It could be an option for the syndicate branch, or just be something you can do in pirate worlds that would decrease relations with whoever caught you.

**Comment by MessyMix** [comment]
@SonEasterZombie Pirate story is for Kiko. As for the Syndicate branch, well, I can't really disclose any plans.... ;)

**Comment by Amazinite** [comment]
If there is a need for the player to pose as another faction than the stories will enable that, but to change your ship color at will probably won't happen.

**Comment by VonZorch** [comment]
It would however, be nice to have your ships in personal colors before officially joining the Free Worlds and after the war is over.

**Comment by gunqqer** [comment]
If you want your own color get World Forge and use the painter planet. I doubt there will ever be any more ways of doing so (I think the business man mod also does this but I'm not sure)
