### ISSUE TITLE
Suggestion: Make "You are being scanned by the Republic ship "Drone Name"" collapsible, if possible

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2119]
It's ok (and could stay as it is) when Republic Gunships are scanning. Now, Republic Surveillance drones, on the other hand…

The problem: There could be dozen or more drones, all congregated around my fleet. Status lines on the bottom of the screen are mostly useful (inform about death benefit pay, profit made by trading, gunship scanning, landing messages, hails etc.). But there's no way of reading this helpful info when drones keep scanning around 20 times per second (by virtue of their numbers), because then all I see is "You are being scanned by the Republic ship "Whatever."" Moreover, drones aren't really ships. Of course, notification of a scan is useful, just not tens of times per second.

I imagine this could be fixed by either showing "You are being scanned by the Republic drone "Drone Name".", which, if immediately after that would appear another such message, would instead become "You are being scanned by a Republic drone. (n)", where n is number of such messages in a row (before one of another type pops up), starting with 2, or, if it isn't possible to change already displayed lines, then just showing "Republic drones are scanning you." and then the game would shut up about drones for either 5 seconds, or next day (in-game), whichever comes sooner.

**Comment by Amazinite** [comment]
The message spam has already been taken care of. 3c65efa
