### ISSUE TITLE
In the mission "FW Reconciliation 2B" Danforth refers to Stormhold as being to the west of Farpoint

### ISSUE THREAD

**Issue by craigmccauley** [endless-sky/endless-sky#212]
As you can see from the map, Stormhold is more South-East than West.

![image](https://cloud.githubusercontent.com/assets/7706831/11202738/a03f77e6-8ca8-11e5-8f94-a0d2e0ffaf44.png)

**Comment by endless-sky** [comment]
For some reason I always get east and west mixed up. :) Fixed in 2ec8e36.

**Comment by akien-mga** [comment]
I'm not sure "east" and "west" make any sense in a context of interstellar navigation though, as they are relative to a planet's poles, but I don't know what would be better. At least it's an understandable concept for us humans having this map before us :)
