### ISSUE TITLE
Opening Map Crashes Game While Enemies On Screen (Potential Skylance bug)

### ISSUE THREAD

**Issue by themightygrunt** [endless-sky/endless-sky#2120]
Hi, fairly new to this Github thing, so bear with me.
[Spoilers? i don't know why people who don't want spoilers are reading the  Github, but whatever i guess]
So i've finally aquired some Quarg gear, and went to New India to equip it on a couple ships.

2 Skylances and a Quantum shield to be precise.

So after equiping 2 Ships, a Model 512, and an Alliance Battleship (I Have SU installed), i went to test it on some random Merchants that happened to be in the System.

After being satisfied with the results, i went to hit the Map to GTFO.

And then the game Crashed. 

Now, i've never had the game crash before. So i was mildly irritated that whenever i opened the map during Combat now, the game just insta-crashes. 

So i began narrowing down the causes, and my list fell upon the Quarg gear.

so i sold all my Quarg gear, and low and behold, the bug went away.

I Highly advise that the Skylance+Quantum code be looked at, because that appears to be the issue.
for now i guess i'll have to stick to lowly Sunbeams, rest in pieces powerful Ion Damage :(

**Comment by Amazinite** [comment]
Question: do you have any plugins installed? The "code" for the Skylance and Quantum Shield Generator shouldn't be causing any crashes.

**Comment by KiLEdEnNis** [comment]
I also crash when I press M when in combat (and a few times while on planet), 20 Skylances on 5 ships & some Quantum gens (even Antimatter Cores due to old save file)
my plugins: my own WIP, world forge, enclave (although I don't really do anything w/ it) & Eternals

**Comment by Amazinite** [comment]
Plugins and map crashes seem to go well together.

**Comment by KiLEdEnNis** [comment]
I'll test w/o plugins, brb

**Comment by Amazinite** [comment]
Also just realized you also posted this on Steam; only report bugs in one spot, the best usually being Steam if you aren't exactly sure on the cause. Close this and we can talk on Steam.

**Comment by KiLEdEnNis** [comment]
I confirmed it: I did NOT crash when I removed my plugins, but did crash with the 4 I mentioned installed, gonna look if it's a specific one

**Comment by themightygrunt** [comment]
@Amazinite sure, i guess SU didn't like Quarg gear >.>

**Comment by KiLEdEnNis** [comment]
what I saw
world forge & eternals cause the map crash, enclave & my WIP one don't
not even sure why, I thought it was caused by plugins that added systems but enclave does so
maybe plugins that have INHABITED systems in direct vision radius cause it?

but gl on Steam

**Comment by KiLEdEnNis** [comment]
last post: a stock Punisher crashed my game so it's not just the Skylances

**Comment by Wrzlprnft** [comment]
i tested alongside kiledennis and mightygrunt, with a freshly compiled version, and did not experience any said crashes.

**Comment by KiLEdEnNis** [comment]
I think mightygrunt has an Nvidea graphics card & I have an Nvidea GeForce 750
but the game doesn't crash with enemies in-system: in a pirate system there's no crash
I think it's caused by a large amount of systems changing color when you anger them, because I told mighty to bribe pirates & press M, no crash, then shoot them, no crash
