### ISSUE TITLE
Destroy Dialog Loops?

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2122]
After doing the mission where you defend Farpoint instead of bombing Zenith, every single time you capture one of the drones, the 'Somehow, you killed them all' message pops up.

Unrelated, but the mission to bomb Zenith afterwards doesn't fail until you land.

**Comment by Amazinite** [comment]
@the second part #1938

**Comment by endless-sky** [comment]
This should be fixed by ab8293b.
