### ISSUE TITLE
Bug(?): Drones making repairs to ships

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2123]
Recently I witnessed surveillance probe making repairs to a disabled gunship. Are drones intended to be capable of that?

**Comment by KiLEdEnNis** [comment]
Korath Automaton ships can repair each other too
not sure if it's intended or a balance over realism case or just something that wasn't changed yet

**Comment by MessyMix** [comment]
@KiLEdEnNis but Korath Automata aren't classed as drones. Yes, they are drones. But they're highly intelligent and I think they could repair themselves (iirc only the Mereti do repairs, though). Surveillance drones imo shouldn't be able to repair, say, a cruiser.

**Comment by KiLEdEnNis** [comment]
well, all automatons besides like Kor Automata (who could use their hull repair drones to repair) shouldn't be able to repair
& instant repairing seems weird but fun above realism

**Comment by MessyMix** [comment]
I would just say that everything that is classified as a drone should not be able to repair. Korath Automata aren't, so they are exempt.

**Comment by KiLEdEnNis** [comment]
for now all ships that are classified as drones yes
but later if there are robot ships like interceptors that don't have their own mind (basically like a drone but they have the stats of an interceptor) they shouldn't be able to either

**Comment by Alkallid** [comment]
Why not a new ship tag, like 'automata' or 'never disabled'?

**Comment by Nechochwen-D** [comment]
@Alkallid I second this.

**Comment by Amazinite** [comment]
"no assist"?

**Comment by endless-sky** [comment]
Addressed in 857740e.
