### ISSUE TITLE
Bug: NPC ship infinitely landing / taking off

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2124]
I was flying around Albaldah system, mining and occasionally teaching pirates some manners, when I saw a merchant ship (seems to be Hauler II) which is stuck permanently landing and immediately taking off, round and round. Come to think this wasn't the first time I'm seeing something like that.

**Comment by KiLEdEnNis** [comment]
do you have any plugins?

**Comment by Amazinite** [comment]
Duplicate #1290

**Comment by Tadrix** [comment]
Nope, no plugins. Vanilla.
