### ISSUE TITLE
Improve File Organization (Major)

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2125]
It's no lie that Endless Sky's data folder is messy. We stumble across the occasional human txt, and then come across the existing alien files clumped by their name, and then see all the miscellaneous stuff scattered across all the files. I talked to @Wrzlprnft about this, and what you read is a result of our conversation.

I know Derpy / @Amazinite has already brought this up (#2050: Rename a few files?), which seems like a solid solution. He suggests that all human files should be named "human xxx", i.e. `human outfits.txt` instead of simply `outfits.txt`. I think that at the very least, this should be implemented. I +1'd this proposal.

However, I feel that even such a solution will be temporary. As more arcs line up, and as more species (potentially) are added, even the renamed files will begin to stack and clutter. You see, we've got individual txts for even regional specific jobs in human space, and the number of files will only grow.

Thus a rework of the current organization is needed. The most effective way to do this is by sorting text files into **folders**. Yes, I know, it might need a big source overhaul, but this will have to happen sooner or later. Otherwise, if the game keeps on expanding, it will get messy(mix?) real fast! It will be hard and arduous to do something like this. But if it keeps getting bigger, then it will only get harder and more arduous to pull it off. As John Lewis said, "If not us, then who? If not now, then when?" I feel like this change needs to happen. @Amazinite has already indicated that a re-organization needs to happen. And I think that if it is to happen, it should be thorough.

So how do we do something like this? I propose that we create subfolders for each species. I have created a mock folder that y'all can take a look at (at the bottom of the post). My current file paths are:

Under:
`/data/general/` (13 files):
- `commodities.txt`
- `conversations.txt`
- `deprecated outfits.txt`
- `effects.txt`
- `governments.txt`
- `harvesting.txt`
- `help.txt`
- `interfaces.txt`
- `landing messages.txt`
- `map.txt`
- `persons.txt`
- `start.txt`
- `tooltips.txt`

`/data/human/` (26 files. Starting to see why we need subfolders now?):
- `deep jobs.txt`
- `engines.txt`
- `events.txt`
- `fleets.txt`
- `free worlds checkmate.txt`
- `free worlds epilogue.txt`
- `free worlds intro.txt`
- `free worlds middle.txt`
- `free worlds reconciliation.txt`
- `free worlds side plots.txt`
- `free worlds start.txt`
- `hails.txt`
- `intro missions.txt`
- `jobs.txt`
- `kestrel.txt`
- `marauders.txt`
- `names.txt`
- `outfits.txt`
- `paradise world jobs.txt`
- `power.txt`
- `sales.txt`
- `ships.txt`
- `syndicate world jobs.txt`
- `transport missions.txt`
- `variants.txt`
- `weapons.txt`

`/data/korath/` (6 items):
- `korath missions.txt`
- `korath outfits.txt`
- `korath ships.txt`
- `korath weapons.txt`
- `korath.txt`
- `nanobots.txt`

`/data/coalition/` (6 items):
- `coalition jobs.txt`
- `coalition missions.txt`
- `coalition outfits.txt`
- `coalition ships.txt`
- `coalition weapons.txt`
- `coalition.txt`

etc. etc.

So you get the idea. I think this will make for a greatly improved organization of text files in data folder. Find a full folder here: https://drive.google.com/drive/folders/0ByesYdUQUPlFYXRyejdiU2hGTnc
(link doesn't work, copy-paste)
What do you guys think?

**Comment by KiLEdEnNis** [comment]
if sub folders in the data folder work that'll be great, nice job

**Comment by Nechochwen-D** [comment]
There seems to be no prohibition against using folders and sub-folders in data/.

**Comment by Bladewood** [comment]
had considered this before, too lazy to bring it up.

But now that someone's actually put it into action, excellent.

**Comment by MessyMix** [comment]
Yes! @Nechochwen-D, I don't think subfolders are prohibited, but it will affect the source, which will need to be re-pathed.

**Comment by KiLEdEnNis** [comment]
making a new folder per species (+ updating the source) can enable plugin makers to add their stuff in a data subfolder without issues
maybe make a couple of human subfolders though for FW story, maybe ships & outfits, and for future DSF, Syndicate, Republic
although too many subfolders might get annoying and I know why; I reorganized my project yesterday, to find a blend I have to go to Endless Sky > ships > [species name] > military / civilian > basics, carriers, freighters or whatever > [shipname], gonna change that :I

**Comment by whismerhill** [comment]
the question is : Does endless sky support subfolders already ?
if yes, then it's easy to do a pull request for reorganization I think so that M.Z. can concentrate on harder tasks
if no, then it will have to be implemented in the programming to begin with, and I'm not familiar enough with it to do such a thing

**Comment by KiLEdEnNis** [comment]
that's basically what I said :P

**Comment by endless-sky** [comment]
The game does support data in subfolders, but whether or not that would actually make the files easier to navigate is a bit of a matter of opinion. (Personally, I find having them all in one folder to be more convenient, but then again, I'm mostly browsing the files through the command line.)

**Comment by DingusShingleton** [comment]
So maybe a more rigid prefix standard would be the best of both worlds? IE each would-be folder just becomes the prefix for all files that would be included in such. That way, when you organize alphabetically it's laid out nice and neat, but it's all still easily accessible without digging through subfolders.

**Comment by MessyMix** [comment]
@DingusShingleton, I've definitely thought of this option. However, when we have specialized text files for even things like `paradise world jobs.txt`, adding a "human" wouldn't help. Trust me, it'll get messy.

**Comment by KiLEdEnNis** [comment]
what I did to keep my project folder organized (only ships atm yet): add a 3-number code in front of every ships' folder:
1st: 0 = military 1 = civilian
2nd: per class (standard, carriers & special or transport, mixed & freighters)
3rd: individual ship

we can order the files or folders like that, it may seem ugly in the data files but it's organized

**Comment by Amazinite** [comment]
Instead of organizing files into folders by faction, how about organizing a few files by purpose?
e.g. a folder for jobs, a folder for missions (where inside of that folder things are broken down by campaign if applicable), a folder for outfits and/or ships, etc. Anything that isn't exactly sortable then would simply not be in an extra folder beyond `/data/`

example:
`/data/jobs/`
* `coalition.txt`
* `deep.txt`
* `hai.txt`
* `human.txt` (generic, currently the one just titled `jobs.txt`)
* `wanderer.txt`
* etc.
