### ISSUE TITLE
Relative trade prices show in empty system

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2126]
If you are in a system, open the map and click on another system, you'll see the relative trade prices of the selected system.

However, if you are in an empty system, you'll also see those relative trade prices! That's weird, because as the system is supposed to be empty, there should be no prices available to compare to.
I don't know how to fix this though, but I have some ideas:
- Remove the trading panel altogether
- Show the actual prices instead of the relative prices
- Don't show the prices altogether, without hiding the panel.

**Comment by KiLEdEnNis** [comment]
you mean like this?
![trade panel](https://cloud.githubusercontent.com/assets/10348657/22793072/0860e81a-eeef-11e6-8b61-d691a74ddabb.jpg)

**Comment by Rakete1111** [comment]
No, I mean this (the other way around)
![trade_relative](https://cloud.githubusercontent.com/assets/8321423/22795639/b1147a46-eef7-11e6-8a37-21c12fa72621.png)

**Comment by KiLEdEnNis** [comment]
oh the + or - when you look at an inhabited system while in an uninhabited system? I think that's a bug

**Comment by endless-sky** [comment]
Fixed in 8a8acc0.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
