### ISSUE TITLE
Add "cancel" option to New Pilot screen

### ISSUE THREAD

**Issue by fingolfin** [endless-sky/endless-sky#2127]
If one accidentally triggers "New Pilot" (say, by being on the main screen, and pressing "Shift-N"), then there is no way to cancel that. You are forced to create a pilot and then delete it.

This wouldn't be so bad, but what just really annoyed me is that this also meant that all progress I made since the last savegame was lost. In this case, one of my escort ships got disabled, andI  wanted to look at the "Preferences..." to lookup the keyboard hotkey to select it (I am still relatively new to the game).
This, as well as several kills and disabled ships (loot!) were all lost because of this accident...

**Comment by KiLEdEnNis** [comment]
seems do-able and a good idea, although I doubt someone would accidently click it, maybe pressing the N button by accident (hotkey)
but you can only make a new pilot after you landed and saved (a.k.a. went to save menu), so I doubt your save got deleted

**Comment by Bladewood** [comment]
I've accidentally created a new pilot many times while playing around with snapshots...

> conversation "intro"
	scene "scene/lobby"
	`The bank's architecture is what you would have called "futuristic" back when you dreamed that the future would be less squalid than the present: story above story of curves and spires and balconies, all in gleaming metal. A doorman stands by each of the heavy glass doors. You are wearing your very best clothes, but you feel shabby next to them.`
	choice
		`(Enter the bank to start your adventure.)`
		goto start
		`(Leave and come back tomorrow.)`
	`	Perhaps you don't have to leave your home right away.`
	`	You decide to go home, maybe to get some better clothes first...`
		die
	label start
	`	The loan broker's office is equally intimidating. Large computer monitors fill the walls, with stock quotes and other information spilling down them almost too fast to read. You occasionally glimpse the names of places that you have only seen in movies: Aldebaran. Tarazed. Earth.`
	`	...`

GITHUB
Y U NO INDENT PROPERLY

**Comment by fingolfin** [comment]
@KiLEdEnNis As I wrote: What got lost was data that was not yet saved, i.e. since the last save. I never claimed that my save got deleted. And you can go at any time to the main menu by pressing the escape key, not just when you are landed.

**Comment by KiLEdEnNis** [comment]
if ya press Esc you first have to press Load/Save, but my bad misread it a bit

**Comment by fingolfin** [comment]
Again: I pressed "esc" to get to the main menu. Then, as I wrote, I accidentalyy pressed "Shift-N" (which does the same as just "N"). That immediately opens the "New Pilot" dialog, even without going to "Load/Save" first (which one may or may not consider a bug of its own).

**Comment by KiLEdEnNis** [comment]
ah just tested and that happens indeed, which is a bug

**Comment by endless-sky** [comment]
It seems like the easiest solution is to just not have the "New Pilot" keyboard shortcut work from the main menu if a pilot is loaded.

**Comment by endless-sky** [comment]
Fixed in 2c2e029.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
