### ISSUE TITLE
Possible typo: coalition missions.txt, line 31

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2128]
>Once to the Heliarch you have become known, in many ways to our society, contribute you may.

Should it say "Heliarchs" instead of "Heliarch"?
"Heliarch" seems to only be used to refer to an individual agent, or as part of the term "Heliarch government," or some related phrases. Everywhere else, "Heliarchs" is used when referring in plural form.

**Comment by manitscold123** [comment]
Remind me what Heliarch is. I believe it is one of the three Coalition Species, right? Anyways, from there, when you think about it, the Heliarch, in this case, Heliarch refers to the species Heliarch, as you refer to the Hai, or to the Wanderer. So you are referring to the entire species "Heliarch". 

Or was Heliarch the main board...

**Comment by jafdy** [comment]
It's the group that rules the coalition. Operating as an army, government and supplying mediators and interpreters. It is made up of members from all 3 species.

**Comment by Bladewood** [comment]
@manitscold123 We would call the Wanderers' species as a whole "Wanderers," not "Wanderer."

**Comment by Amazinite** [comment]
Heliarch is a title, and referring to them as a whole it should be Heliarchs. Although, I question if that's just part of their speech pattern to say Heliarch instead of Heliarchs.

**Comment by KiLEdEnNis** [comment]
it feels good without the s, but we'll wait for MZ

**Comment by MessyMix** [comment]
It does feel good without the "s". In fact, I would love it if "heliarch" referred to the whole. "The Heliarch" > "The Heliarchs" imo.

Having said that, it appears that the in-game term for the plural of Heliarch is Heliarchs. :(

**Comment by endless-sky** [comment]
Yup, that's a typo. Fixed in fbf1f5f.

**Comment by Bladewood** [comment]
Consider "Hierarchy" (e.g. the Ur-Quan Hierarchy of Battle Thralls, or something like that).

**Comment by Bladewood** [comment]
Thought:
The Saryds are centaurs (emphasized by the first contact mission), so they must be greek! https://en.wikipedia.org/wiki/Centaur
Helios "sun" and -arch "ruler" would combine to make Heliarch, "sun ruler" or something like that.
[I have no idea what I'm doing]

**Comment by endless-sky** [comment]
That's the basic idea, yes. Hence the golden circlets they wear, the obsession with solar power, and the pride they take in the ringworlds they captured (which are, among other things, a tool for capturing a huge amount of solar power from a star). Not that the Heliarchs actually know anything about how the ringworlds work or what secrets they carry, of course.

**Comment by Bladewood** [comment]
oh my god I'm right yay

**Comment by endless-sky** [comment]
Originally I was actually going to have Coalition citizens refer to the Heliarchs both as "the Heliarchs" and as "the Sun-Lords" depending on how formal the tone of the conversation was. But I was worried that players wouldn't realize that the two names referred to the same thing.
