### ISSUE TITLE
Finisher torpedo explosion sound should be way more impressive

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2130]
Given the weapon's stats and the visual impressiveness of the explosion it produces, I'm pretty underwhelmed by the explosion sound, which feels way too small.

**Comment by Bladewood** [comment]
Along with that, let's have it make a cool sound when it become an active finisher!

**Comment by Lineth** [comment]
I'm now picturing the torpedoes to make the Mortal Kombat "FINISH HIM." voice when launched.

**Comment by Amazinite** [comment]
New sound for the Bubble Gun too?

**Comment by KiLEdEnNis** [comment]
bubble gun description
"my bubbles don't only make ships wet ( ͡° ͜ʖ ͡°)"

**Comment by Pointedstick** [comment]
Oops, I forgot to use the new Torpedo hit sound for Finishers with https://github.com/endless-sky/endless-sky/pull/3869.

Will fix.

**Comment by Amazinite** [comment]
The Finisher creates both the torpedo sound effect (as of #7089) and the small explosion sound effect. @Pointedstick Would you consider this done, or does the Finisher explosion still need more oomph to it?

**Comment by Pointedstick** [comment]
Yeah, this is fine now. Thanks for following up!
