### ISSUE TITLE
No tourism in hai space

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#2132]
In one of the early conversations with the hai, they say they go on vacation on the most unpredictable worlds. However, no planets in hai space have `attributes tourism`.

**Comment by KiLEdEnNis** [comment]
> When Hai go on vacation, we visit the stormiest world, to find unpredictability and change.

basically their stormy worlds

but there aren't Hai tourism jobs are there?

**Comment by ph2000bis** [comment]
No, and that's my point. I think there should be, as we know that there is tourism there should be jobs for it.

**Comment by KiLEdEnNis** [comment]
if I remember someone was working on Hai jobs, not sure
at the moment the Hai use regular human jobs

**Comment by Amazinite** [comment]
#1928
