### ISSUE TITLE
Better shield generators should raise max shield value

### ISSUE THREAD

**Issue by lnxworx** [endless-sky/endless-sky#2133]
A better shield generator or multiple shield generators should, in theory, raise the maximum shield value for ships.  I know the concern will be in creating a ship that will have defenses that cannot be be breached.  However, I think that applied across the board to players and npc's this would balance out.  Additional shield generators, would provide a percentage of increase to total shield dependent on model. As it stands now, I could buy a behemoth for example, remove all the cargo space and load up on as many shield generators that my outfit space will allow as long I have the power generation necessary.  While this may not raise my total shield maximum, my recharge rate could be so fast as to make it very difficult to breach my defense.

I also think, though I haven't paid close enough attention to this to know if it's implemented, shield recharging should impact energy draw during a battle.  If my shield is getting pounded it should require more energy to recharge it, drawing from the overall power available.  This would directly impact choices of power components, weapons systems, ship models etc throughout the game and help prevent creating overpowered ships. (i.e not only do more shield generators take up outfit space and energy draw, but may also require addition batteries, fuel cells or generators for shield generation during battle.)

Thanks for a great game.  My boys and I love playing it and strategizing.

**Comment by Wrzlprnft** [comment]
Maximum shield capacity is one of the few things which keeps ship hulls unique. Therefore, as similar suggestions have shown in the past, it's unlikely to be changeable with outfits.
In my personal opinion, i'd rather not change that, because, while a system with interchangeable max shields may be balanced in itself, someone would have to balance all the existing content for it. if you want it for yourself, you can make a plugin, though.

if i recall correctly, there are different kinds of shield generators, some of which actuall draw more power while regenerating.

**Comment by Pointedstick** [comment]
I believe raising the actual max shield value is something that doesn't exist by design, so you can't turn a freighter into a heavy warship (for example). High recharge rate can't protect you against a fleet pounding on you, or a ton of incoming missiles.

Shield regenerating already does draw energy. Some of the bigger alien generators have significant power needs, so it's non-trivial and you do indeed need to make sure you've got enough energy to recharge shields while firing all your weapons and engines.

**Comment by Amazinite** [comment]
> Although most pilots today think of energy shields as purely for protection in combat, they were originally designed as a defense against cosmic radiation. Later, they were strengthened enough to deflect micro-asteroids and other space debris. These early shield generators created a spherical ring around the ship, generally at some distance away from the hull because a powerful enough impact could distort the field and bend it inward.
> 
> That was back in the early days of interstellar travel. Today's integrated shield matrices are an order of magnitude more powerful and efficient, in part because they are custom-fitted to the shape of a ship rather than extending far outside it. But because the emitters that maintain the shield matrix are integrated into the hull, you cannot increase the strength by swapping in a different generator; the only way to significantly boost your shield strength is to buy a stronger ship.
> 
> Instead, modern shield generators serve only to recharge the matrix, which is still a very useful function, especially if you are able to gain a brief respite from combat. Some shield generators, in fact, are so powerful that they can keep shields at full strength even when under constant fire from an energy blaster. Recharging shields takes energy, but typically much less energy than your other systems will draw.

**Comment by Wrzlprnft** [comment]
... so,how many people answered at the same time with basically different but overlapping answers? it's an interesting topic, for sure.

**Comment by Bladewood** [comment]
If anything, better shield generators (some of them, I mean, not all) should _decrease_ your maximum shield strength, sacrificing raw power for much faster regeneration.

**Comment by KiLEdEnNis** [comment]
maybe a reinforced hull plating: decreasing shield by 600, adding 400 hull or so
and then something that removes like 400 hull for 600 shields, and both would be like 2 outfit space

**Comment by lnxworx** [comment]
Great discussion.  My kids and I have been talking about Endless Sky all
day.  Keep up the good work.

**Comment by KiLEdEnNis** [comment]
ooh parents & children talking about ES o:
if only my parents cared about Smite, ES or whatever ;-;

**Comment by DingusShingleton** [comment]
I actually was toying with the idea of an outfit that did just that @Bladewood. A small shield generator with high regeneration that decreased maximum shield. It was a vain attempt to make a genny for fighters that would give them obscene (relatively) amounts of regen. I ran into the classic problem of something that's strong for a small ship being OP for a large ship. I couldn't figure a way to limit it using only things that were already in the game.

**Comment by geojak** [comment]
Could ne balanced by reducing a percentage of the maximum shield while granting a flat recharge rate.

Biigger ships would have much higher losses in shield making it only attractive to fighters.

Guess this functionally is not implemented. Yet!

**Comment by Bladewood** [comment]
Percentages would be a nice way to nerf them for higher ships, but they haven't been implemented :(

**Comment by KiLEdEnNis** [comment]
seems too dangerous tbh

**Comment by Pointedstick** [comment]
> ooh parents & children talking about ES o:

My whole family is into the game at this point! It's a keeper.
