### ISSUE TITLE
If you prepare to jump off a system while your ships are gathering around you, they won't prepare to jump

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2135]
If you have other ships (your ships, not escorts, with them it works fine) and you press 'G' to gather them around you, and then long press 'J' down to prepare to jump, then the other ships won't prepare to jump, and instead will just fly through you over and over again.

If I remember correctly, this didn't use to be the case, so it's probably a bug.

(Not the best image, but my 2 other Bactrians don't stop to prepare to jump, they just fly to me)
![jump_bug](https://cloud.githubusercontent.com/assets/8321423/22860529/f57a5aec-f100-11e6-9f6b-6c59cf5e303b.png)

**Comment by KiLEdEnNis** [comment]
it IS a bug, I think one of the bugs from the new AI system (maybe paired with the new tactical functions like zooming)
what I sometimes have is that my 4 escorts do prepare to jump & stop moving, but the first jump (Jump Drives) they have a small delay

**Comment by Pointedstick** [comment]
Oh look, yet another fleet of Bactrians. \*ahem\* https://github.com/endless-sky/endless-sky/pull/2076

**Comment by endless-sky** [comment]
This should be fixed by 6aafae1.

**Comment by KiLEdEnNis** [comment]
that fix is so they ignore orders and will jump along unless they have to hold

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
