### ISSUE TITLE
Escort ships automatically fully refuel if you land even if in different (uninhabited) system

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2136]
If one of my escorts is out of fuel in an uninhabited system, I can jump to the next one without the escort, land and depart, and the escort will magically have full tank and will jump to me. The escort doesn't have to be in an uninhabited system, it happens everywhere. Although I noticed when the escort was in an uninhabited system, as everywhere else the escort can land to refuel, so it's not a problem.

This only happens with escorts though, not with the ships that I have.

**Comment by KiLEdEnNis** [comment]
if I remember correctly that was to avoid escorts getting stuck in a random system and to avoid players having to go all the way back to refuel it
I had a captured ship that didn't get fuel after landing so that should show it's intentional

**Comment by Amazinite** [comment]
What uninhabited system have you had this occur in, because I've had dozens of times where I needed to go back for escorts and they didn't auto refuel. Do your escorts have Ramscoops? Is it next to a friendly system? Do friendly ships go through this uninhabited system?

**Comment by Rakete1111** [comment]
@KiLEdEnNis That would make sense.

@Amazinite No, I don't. However, they were friendly, as in, just above the Rift/in the Dirt Belt, so there were not pirates and the systems were full of merchants.
That might be the case, you're right. 
Probably isn't a bug then if it didn't occur to you.

**Comment by jafdy** [comment]
The last line in the OP is confusing me. It this with mission NPCs and not ships that you own but don't fly or all ships but your flag ship?

**Comment by Rakete1111** [comment]
@jafdy I mean mission ships, i.e. ships that I don't own. But they all have to be flying, not be parked somewhere.

**Comment by w0ntoan** [comment]
I'd write that "feature" off as them standing next to the sun and getting that microramscoop refueling for an entire day, since land/depart takes a "day".

**Comment by KiLEdEnNis** [comment]
realistically departing doesn't take a whole day though, probably not even an hour, but that's some balance thing too

**Comment by endless-sky** [comment]
This is intentional to reduce the situations where mission NPCs end up stranded, because you don't have as much control over them as you do over your own escorts. (For example, you can't park them or tell them to hold position.)

**Comment by KiLEdEnNis** [comment]
> if I remember correctly that was to avoid escorts getting stuck in a random system and to avoid players having to go all the way back to refuel it

ooh I'm smart
