### ISSUE TITLE
LP576a battery efficiency

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2137]
LP036a = 1000 capacity / 10 tons = 100 capacity / ton
LP072a = 2200 capacity / 20 tons = 110 capacity / ton
LP144a = 4800 capacity / 40 tons = 120 capacity / ton
LP288a = 10400 capacity / 80 tons = 130 capacity / ton
LP576a = 23000 capacity / 160 tons = 143.75 capacity / ton

As you can see, the LP576a breaks the pattern, with an extra 3.75 capacity / ton, when it should just have 140 capacity / ton, or 22400 capacity / 160 tons.

**Comment by Amazinite** [comment]
REEEEEEEEEE CONFORMITY

**Comment by KiLEdEnNis** [comment]
or make it larger than 160 tons so it fits 140/ton to annoy Bladewood ( ͡° ͜ʖ ͡°)

**Comment by Bladewood** [comment]
@KiLEdEnNis The battery numbering is 36 * 2^x.
The battery tonnage is 10 * 2^x.

Your proposal would break one or both of those patterns.

**Comment by jafdy** [comment]
I don't think the 160 ton battery is used much. It is one of the largest single power sources in the game (And Largest in human space). Dose it matter?

**Comment by Bladewood** [comment]
23000 is an ugly number (23 is a prime).
It annoys me.

**Comment by jafdy** [comment]
23 is a beautiful number. It's Prime. 23000 is worse though. 2^3*5^3*23

**Comment by Bladewood** [comment]
I think you meant to write 2^3 * 5^3 * 23.
Because 2^35^323 is a gargantuan number.

**Comment by jafdy** [comment]
That is what I meant but markdown italicized the 5 instead.

**Comment by Pointedstick** [comment]
In fact, no ship in the game uses the LP576a battery. Its ridiculous size means that no player ship ever will, either--you'd just put another reactor on your ship, plus the .necessary cooling.

Does this thing even need to exist at all?

**Comment by Bladewood** [comment]
tiny, small, medium, large, huge.
576 -> huge.

**Comment by KiLEdEnNis** [comment]
I don't even really use anything besides the 036 or supercapacitor until I get like a systems core or Wanderer generator with built-in capacity; I want enough regen so I'm not outta power in combat

**Comment by endless-sky** [comment]
I feel like, if you're going to use that big of a battery, you deserve a bit of bonus battery power. Also, note that in general the goal is for efficiencies in a series of outfits to follow an exponential curve, not a linear one.
