### ISSUE TITLE
New scanner type: "combat scan" that shows the target's heat, energy, and fuel

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2138]
I'd really like to be able to see my target ship's energy and heat bars--maybe fuel too if you merge the fuel damage attribute (https://github.com/endless-sky/endless-sky/pull/2003). This would allow players to fine-tune their ship's armament based on the unique vulnerabilities of the types of ships they're fighting. If you could see that your enemy's ships were very vulnerable to heat, you'd load up on flamethrowers, plasma cannons, or sunbeams. If they had low energy storage, you'd equip some ion cannons.

It strikes me that this is the perfect opportunity for a new scan type ("combat scan"?), and a new scanner: "the combat scanner" or something like that. Or maybe we could make that the "military scanner" and combine the outfit and cargo scanners into a "civilian scanner." The Republic drone surveillance pod would of course do them all.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/1115

**Comment by Pointedstick** [comment]
Yep, seems like a duplicate. Hope it gets done.

**Comment by KiLEdEnNis** [comment]
(psst, battle scanner o:)
