### ISSUE TITLE
Possible bug: Escort ship not following orders

### ISSUE THREAD

**Issue by naehc** [endless-sky/endless-sky#214]
I recently added a fourth Shield Beetle to my fleet; unfortunately this one turned out to be a rogue with an apparent death wish. Example: I go to a Pirate system to force tribute, and as I usually do, travel some distance from the system center before making the demand, giving the fleet the order to gather around the flagship. All the ships follow the order as usual, except for this one SB; which instead plants itself close to the Pirate planet, just lazily rotating or moving a short distance before returning to its first spot, despite taking constant fire from all the pirate ships in the system, who target it because of its position. No matter what orders I try to give (Hold Position/Gather/Target specific ship), it doesn't respond. With that behaviour and precarious location, the ship's almost worse than useless, since it gets blown up within a minute unless I have the whole fleet make an Alamo-style stand alongside it... which, when I tried it, meant losing two 12 million Mules rather than 1 40 million Shield Beetle; bit of a lose-lose situation. ;) Anyway, it's kind of mystifying, and since I haven't seen any weird AI behaviour in Endless Sky until now, it might be hard to reproduce... I've made a snapshot, just in case uploading the save might be useful.

**Comment by endless-sky** [comment]
This might be caused by the ship not properly recognizing that your flagship is its parent. If so, my recent commits 99b3ca8 and 6de5252 should fix it. (Or, just saving and reloading the game ought to have the same effect of properly reparenting all the ships in your fleet.)

**Comment by naehc** [comment]
Yeah, the issue seems to have resolved itself after some in-game time had passed (I did try save/reloading at the time of the problem, without it making a difference); wound up parking the ship on a planet for a week or two, and after having it rejoin the fleet I've seen no more of the rogue behaviour.

**Comment by endless-sky** [comment]
The bugs that can occur when your first ship is not your flagship ought to be fixed in 0.8.8.

**Comment by naehc** [comment]
Indeed, as far as I know/have seen this is no longer a problem; closing the issue.
