### ISSUE TITLE
During Free Worlds storyline, Republic ships in Arneb aren't Oathkeeers

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#2142]
This time around, instead of doing my Grand Domination Tour either before or after completing the Free Worlds storyline, I started it in the middle of it. Most of the space around Farpoint has Oathkeeper ships—which is convenient, since I'm still weak enough that Republic fleets are a serious threat. But, on my Tour, I discovered that the ones that (rarely) show up in Arneb are not Oathkeepers.

**Comment by KiLEdEnNis** [comment]
"Oathkeeers" triggers me
apart from that it's indeed a "bug"

**Comment by Bladewood** [comment]
Oathkeepers are dedicated to patrolling the far north.
Nothing is stopping the rest of the Navy from patrolling it.

**Comment by KiLEdEnNis** [comment]
then why do we never see any regular Republic fleets in that area?

**Comment by Amazinite** [comment]
Why would they send fleets that far when they know the Oathkeepers have a handle on things? OP did say rarely, so do Oathkeepers fleets spawn more normally that straight up Republic fleets?

**Comment by KiLEdEnNis** [comment]
I think he means the rare case Navy ships enter the system at all

**Comment by Bladewood** [comment]
Republic Navy patrol ships have a very small chance of appearing in the Far North.
Oathkeepers are much more common.

**Comment by KiLEdEnNis** [comment]
Republic ships still appear in every system, just way less there? if not, make it either they appear way less frequently or they never appear

**Comment by SolraBizna** [comment]
> "Oathkeeers"

Sorry, my keyboard sucks :(

Non-Oathkeepers showing up occasionally makes sense. In fact, maybe that should be a little more common than it is. (>95% of the Far North ships suddenly consisting solely of Oathkeepers is a little strange.) But I sat in Arneb for over an hour, and both of the Navy fleets I saw during that time were regular Republic ships. I know that two samples isn't enough for a statistically sound sample, but Navy ships showing up there is _really_ rare...

**Comment by endless-sky** [comment]
It's not unreasonable to think that any Republic fleet intentionally invading the anarchist systems, instead of just patrolling local Republic systems, would be flying generic Republic colors. In any case, it doesn't seem like enough of an issue to be worth changing.
