### ISSUE TITLE
improving making fleets (variants in variants)

### ISSUE THREAD

**Issue by Lorantine** [endless-sky/endless-sky#2143]
![variants in variants](https://cloud.githubusercontent.com/assets/10348657/22950674/bcf71856-f306-11e6-836c-79b94fa15520.jpg)
edit:
if the "variants" in variants are called "ship" and randomly picks one of the next lines, it'd be relatively clear, easy to use and a great addition (making an empty line with "" would work the same as a piece of a hail that's empty: you'd have a chance to see a specific ship & the chance none from that tree appear as it picked the empty one)

# 2 JULY 2018 EDIT

this screenshot is an example of something I want, it doesn't have to be exactly this (if it can be made easier or more efficient)
![image](https://user-images.githubusercontent.com/10348657/42161571-bd236d08-7dfb-11e8-95bb-f78cbffef298.png)

## to explain with the screenshot below:
![image](https://user-images.githubusercontent.com/10348657/42161585-c85a87ce-7dfb-11e8-9fa3-cd0fb423c61f.png)

the 1-4 specifies between how many ships there may exist, here between 1 and 4, if nothing is specified it would be defaulted to 1

the 4 numbers after specify the chance there's X amount of these ships in the fleet, so a very big chance there's either 1 or 2, small chance of 3 or 4, if nothing is specified, all options have the same chance (to use this at all you need to set how between how many ships there can appear, so you'll never fill this in without the other first)

option simply says: here's the ship options I can pick, if there's only 1 ship to be spawned it picks a ship from this once, if it has to pick 4 ships it looks 4 times

here, Light Warship has a 3/5 chance to be picked, Other Light Warship has a 2/5 chance to be picked
ideally this can be made so that if there's only 1 option, you can leave this keyword out, or maybe this keyword doesn't have to be added at all, or maybe you make 2 options, each with their own ships?

**Comment by KiLEdEnNis** [comment]
eh, the spaces won't work, so it's very hard to understand

**Comment by Wrzlprnft** [comment]
try `
around to make it code

**Comment by KiLEdEnNis** [comment]
it'll go back to being on 1 line, so can't

**Comment by Amazinite** [comment]
So what are you trying to accomplish? Creating a fleet with 27 different combinations?

fleet
_variant
__"shuttle a"
_variant
__"shuttle b"
_variant
__"shuttle c"
fleet
_variant
__"clipper a"
_variant
__"clipper b"
_variant
__"clipper c"
fleet
_variant
__"sparrow a"
_variant
__"sparrow b"
_variant
__"sparrow c"

**Comment by KiLEdEnNis** [comment]
the 27 combinations was an example of what I want to be possible
and what you said, not sure exactly

basically, the current system, but you can make a ship variant IN a fleet variant
hard to explain without a huge word wall

**Comment by Amazinite** [comment]
I get what you mean, but I'm asking whether you want this for the purpose of mission npcs or for random fleet spawns.

**Comment by KiLEdEnNis** [comment]
random fleets, like fleets.txt

**Comment by KiLEdEnNis** [comment]
updated the main post (just added something below, easy to see what part)
that's basically a test version of something I want; it'll make fleet creation a lot easier (to do, to understand may be a bit... hard), and one could make a LOT of fleet variety in very few lines, meaning we could save somewhere like 80% of current fleet lines
