### ISSUE TITLE
new ship outline scale locked to default zoom level

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#2144]
http://prntscr.com/e8rqi4
I don't think this is intended, however it really makes it clear to see your capital ship direction even in the hardest of conditions :p

**Comment by KiLEdEnNis** [comment]
unless really zoomed in of course :P

**Comment by whismerhill** [comment]
the hardest of conditions is: with a large fleet & zoomed out + ship hp/shields overlays
I know it was mentioned by several how they don't like the ship hp/shields overlays and I kinda agree they make battles a bit of a mess. however I find them invaluable to save ship when faced against tough odds
because when you have a stack of 20 ships on the bottom left corner, you don't see individual ships hp/shields anymore.

With new fleet orders I have already saved a bunch of ships by selecting an individual escort & move it inside my stack of unarmed transports (or on the other side of threats), same with captures.

**Comment by KiLEdEnNis** [comment]
me; 1 Hurricane & 4 Derecho's, nearly always gather around the Hurricane
so I don't really have experience with that mess, I have 4 escorts to take care of & they all have 2 Antimatter Cores from before they were removed

**Comment by whismerhill** [comment]
that's because you didn't restart with 0.9.5 and also because you have knowledge of the game.
I expect a lot of people to avoid devaluation by using what you capture/steal instead of buying, and since upgrading is much costlier, I expect people to go for larger fleets as an alternative.

**Comment by Amazinite** [comment]
A little slow to the draw on that one. He fixed it six hour before you opened this issue. 4f88a16

**Comment by whismerhill** [comment]
@Amazinite 
I only created an issue when someone mentioned I should  ;)
closing.

**Comment by Amazinite** [comment]
And they mentioned you should before it was fixed. :3

**Comment by whismerhill** [comment]
*shrugs*
