### ISSUE TITLE
[Idea] Merchant ships will trade with you

### ISSUE THREAD

**Issue by PJTheGuy** [endless-sky/endless-sky#2145]
Got this idea from an old flash game I played (Flash Trek Broken Mirror) and thought it would go well here.
Maybe merchant ships could have cargo scanners, and hail you if you are carrying a cargo that they "want" and will pay you a random amount for each ton of it. Somewhat inflated from normal, of course, as they really want what you have. Then, they will be selling a certain cargo for some amount per ton (maybe below normal prices, as they want to get it off their hands) and you can choose to buy from them as well. Possibly other governments would buy and sell from you, as long as they aren't hostile, or locked behind a language barrier.

**Comment by KiLEdEnNis** [comment]
it wouldn't really make sense to trade commodities in mid-space
