### ISSUE TITLE
Coalition missions are a bit too good?

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2148]
I don't think it's intended, but Coalition missions are *way* to good to be true. Firstly, they pay *a lot*, I once saw a mission that gave 2.85M credits! Secondly, almost none of them have a time limit. This means that I can accept a lot of them, without worrying that I won't make it there in time. This is really lucrative.

I just made 70M+ credits just by doing those missions for ~40 min. Other missions in different parts of the galaxy don't give as much money. I would say they really need to be reduced in some way, right now, it doesn't make sense to do any other mission except for Coalition ones.

**Comment by jafdy** [comment]
Call it a bonus for having a large ship/fleet and a jump drive. That said the do pay a lot while human and Hai jobs just don't scale.

**Comment by Bladewood** [comment]
Plenty of them have time limits, don't they?

**Comment by Rakete1111** [comment]
@Bladewood Yes, true, but just 20% of them. Also, the 1M+ missions don't have a time limit, only the ~200K ones

**Comment by Amazinite** [comment]
Well right now, there's only one set of other missions in the game, and those are the human ones that get reused in Hai and Wanderer space... And that one Unfettered one that few people know about. 
And those jobs might pay a lot, but what are the sizes? I do see some multi-million credit jobs but they're usually 200+ ton cargo jobs.

**Comment by jafdy** [comment]
I suspect that part of the reason is that coalition jobs are longer ranged and that they count distance by using a hyperdrive. Add that to the fact they are already large jobs and you are bound to get big payouts.

**Comment by endless-sky** [comment]
The goal is to have jobs scale depending on how advanced the society is that's offering them. Anyone who is in Coalition space probably has either a large ship or a fleet, so there's no point in offering tiny mission there.

Also note that the payoffs per unit of cargo or passenger per ton are the same as in human space, it's just that the missions are larger.
