### ISSUE TITLE
TMBR can offer on pirate planets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2149]
"Eventually, the spaceport police arrive and disperse the crowd."
I hadn't realized that pirate planets had huge crowds of fans who love TMBR, or spaceport police for that matter.

**Comment by Bladewood** [comment]
The first one, I can understand; the second one, I do not.

In that case, I'd expect the pirates to just capture the band and keep them for themselves, or to sell them into slavery, or for ransom, or something.

**Comment by Lineth** [comment]
I think his point is that it should not be offered on pirate worlds at all.

**Comment by KiLEdEnNis** [comment]
doesn't it have the tag to be on Syndicate worlds?

**Comment by Bladewood** [comment]
[That's the second TMBR mission.](https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt#L697)
[The first one can appear anywhere, and ends up with you landing on Wayfarer.](https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt#L653)

**Comment by endless-sky** [comment]
Fixed in a59a65b.

**Comment by Amazinite** [comment]
>Closing this because 

0.9.6 
>is released now.
