### ISSUE TITLE
Allies trying to land on dominated pirate planet but can't

### ISSUE THREAD

**Issue by w0ntoan** [endless-sky/endless-sky#2150]
While jumping through a dominated pirate planet, I landed for fuel, then quickly jumped out. The allied ships kept trying to land on the planet but could not, and did not follow until I jumped back to them and they got distracted by shooting at pirates and forgot about trying to land.

It seems like the allies do not have permission to land, even though I do. I know some missions change the status of the planet to allow landing, but I guess this doesn't apply to dominated planets?

**Comment by endless-sky** [comment]
Can you clarify whether you mean allies (i.e. mission NPCs following you) or escorts (ships you own)?

**Comment by w0ntoan** [comment]
mission NPCs

**Comment by w0ntoan** [comment]
sorry for double posting, but I made a video.
https://youtu.be/IUNyfx-BAdA

**Comment by endless-sky** [comment]
This should be fixed by 86fe296.

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
