### ISSUE TITLE
Test Dummy returns Hostile Hail

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2151]
Test Dummy missions return hostile hails when I hail after engaging. As of right now, they seem to be the default pirate hails, but `governments.txt` doesn't seem to specify a hail.

**Comment by KiLEdEnNis** [comment]
I think it's just the hails that every disabled ship uses if you understand their language, could it be that?

**Comment by Amazinite** [comment]
Hostile hails, not disabled.

**Comment by KiLEdEnNis** [comment]
oh like that

**Comment by MessyMix** [comment]
Yes, disabled hostile pirate hails. And note that especially with the Syndicate testing jobs, they are supposed to be robotic.

**Comment by SonEasterZombie** [comment]
Perhaps it's just the sassy ships AI automatically responding?

**Comment by MessyMix** [comment]
For reference: #372 #373

**Comment by MessyMix** [comment]
![image](https://cloud.githubusercontent.com/assets/20450076/23333787/e6f07af6-fb5f-11e6-9ea5-81b90d66c1f1.png)

**Comment by MessyMix** [comment]
@endless-sky since I know you're online right now, and since I don't do C++, do you think you could pull a quick fix a la https://github.com/endless-sky/endless-sky/pull/373/files?

**Comment by Amazinite** [comment]
I think this would work.

```
if(gov->GetName() == "Derelict" || gov->GetName() == "Test Dummy")
	{
		message = "There is no response to your hail";
	}
```

**Comment by MessyMix** [comment]
If the two "|"s work as an "or", then it should work. I might try that. But then there are other instances that #373 fixes, such as the interface.Info, that may not apply to Test Dummy "hostile vs. friendly".

**Comment by Wrzlprnft** [comment]
“|“ is “or“ 
“||“ is “or, and don't check the rest of the statement  if the part before it is true“
since there are “side effects“ which can change values in such a check

**Comment by Nechochwen-D** [comment]
@Wrzlprnft you have that wrong.
"|" is the bitwise operation OR.
"||" is the logical operator or and evaluates to true if either side of the statement is true.

In fact @Amazinite actually got it right.

**Comment by Pointedstick** [comment]
As of now, these ships don't say anything if you hail them, which is better than before. But I think maybe they should say something a little more appropriate...

**Comment by tehhowch** [comment]
Needs a new milestone :+1:
 (only downside of closing via commit reference)

**Comment by Amazinite** [comment]
> Needs a new milestone
Got it. 😎
