### ISSUE TITLE
Random segmentation faults (maybe in Planet::GetSystem())

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2152]
Lately I have been getting some seg faults at random times, but they mostly occur when my fleet is in the process of jumping.

Running the game in gdb, it seg faults in `Planet::GetSystem()`:

```
Thread 20 "endless-sky" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa3fff700 (LWP 13585)]
0x0000000000530370 in Planet::GetSystem() const ()
```

However, if I recompile the game without optimizations and enable debug mode, then gdb reports that the fault happened in `stl_vector.h`:

```
Thread 19 "endless-sky" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcfa1f700 (LWP 14081)]
0x000000000041fbc8 in std::vector<System const*, std::allocator<System const*> >::end (
    this=0x1a0) at /usr/include/c++/6.3.1/bits/stl_vector.h:576
576	      { return const_iterator(this->_M_impl._M_finish); }
```

I don't know if it's a bug in the standard library or not, so just in case, I'm posting it here.

**Comment by endless-sky** [comment]
See if 56595ba fixes it for you. That's the only place I can see in recent code changes where the Planet::GetSystem() function is being used.

**Comment by Rakete1111** [comment]
That seems to have fixed it, thanks :)
