### ISSUE TITLE
Outfit attributes page is misleading (contains old information)

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2153]
On [this](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits#outfit-attributes) paragraph in the Wiki, it says:

> [...] For example, **if you install two of the same scanner, your scanning range doubles**. If you install two shield generators, your shield regeneration doubles.

The line that I made bold is the problem. Since 0.9.5, this is not the case anymore (from the same page):

> `cargo scan power`: the cargo scanning range is 100 times the square root of this number. **This means you need four scanners to get twice the range of one scanner**.

**Comment by endless-sky** [comment]
Fixed.
