### ISSUE TITLE
Death benefits

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2154]
Yeah, I know this has been brought up countless times, and I myself kind of am used to these (and I'm not really believing someone will support my proposition, since people here tend to strongly believe in need of such drastic countermeasures), but here's the thing: I've been reading several discussions about Endless Sky, and many people sincerely hate these and devise various workarounds. Even TVtropes has a line mentioning, that:
> The amount scales in proportion to the captured ship's value, so you'll never have to pay more than the ship is worth, but it only takes a few casualties before your slice of the pie becomes razor-thin.

with a link to "Video Game Cruelty Punishment". The question stands whether it's more merciful to just board and kill them or take their engines and reactor and leave stranded, but not in this issue. Also, if player pays his fleet large salaries, he still has the potential to go out with losses.

I'm proposing an alternative formula to calculate death benefits:
[ship's value] * [enemy's casualties] / ([player's casualties] + [enemy's casualties])

This could still do the job without being so ridiculously punishing.

This could nicely pair up with proposition to be able to retain specialist marines with higher salary whose job is to risk their lives boarding ships.

**Comment by Rakete1111** [comment]
Just a heads-up: death benefits have been removed completely now ([a1fd15a](https://github.com/endless-sky/endless-sky/commit/a1fd15a26e1c696d376f0e7c16ce99b0605db408)), the change will come in 0.9.6. Also, with your formula, it seems that it is better to let the enemy kill off a lot of your own crew, to save costs. That's a bit counter-intuitive.

**Comment by Wrzlprnft** [comment]
yup.they are gone. i'd wait till 0.9.7 or another unstable to introduce another take.

**Comment by Amazinite** [comment]
A little slow to the draw on this one.

**Comment by Tadrix** [comment]
@Rakete1111 Thanks for head-up. This will make new depreciation system much more bearable. Mind you, it will still suck to be a beginner (time needed to get a better ship, since the first one won't sell for the same price), but it's for another topic.
BTW, try the formula. It sucks to let the enemy kill off a lot of own crew. An example:

Ship's worth: 10
Enemy crew: 12 (if player wins, we know they all will be dead)

Player's Casualties | Death Benefits | More Punishing*
:---:| --- | --- |
0 | 0 | 0
1 | 0,769230769 | 1,428571429
2 | 1,428571429 | 2,5
3 | 2 | 3,333333333
4 | 2,5 | 4
5 | 2,941176471 | 4,545454545
6 | 3,333333333 | 5
7 | 3,684210526 | 5,384615385
8 | 4 | 5,714285714
9 | 4,285714286 | 6
10 | 4,545454545 | 6,25
11 | 4,782608696 | 6,470588235
12 | 5 | 6,666666667
13 | 5,2 | 6,842105263
14 | 5,384615385 | 7
15 | 5,555555556 | 7,142857143

With every crew member dead the Death Benefits rise, so it can't be profitable to just let them die.
* More punishing death benefit version would be obtained by doubling player's casualties value before using proposed formula. Tweak multipliers as needed for balance.

@Wrzlprnft Any ideas as to what it will look like?

@Amazinite Still, if devs are going to introduce another take, this could still be relevant.
