### ISSUE TITLE
Bugged ship outlines

### ISSUE THREAD

**Issue by Lineth** [endless-sky/endless-sky#2155]
![In Space](http://i.imgur.com/JTR3wQV.jpg)

![Front End](http://i.imgur.com/Q1GBqFg.jpg)
Not sure what's causing it. I do not have the high DPI plugin installed. Fresh install on my laptop.

**Comment by Amazinite** [comment]
That's the same link twice.

**Comment by Lineth** [comment]
Fixed.

**Comment by KiLEdEnNis** [comment]
hot ( ͡° ͜ʖ ͡°)

**Comment by Bladewood** [comment]
Someone make a ship out of those outlines.

**Comment by endless-sky** [comment]
Do any other sprites appear weird on your system? Also, what graphics card or iGPU are you using? And on what OS?

**Comment by Lineth** [comment]
So far the outlines in the HUD and frontend are the only thing bugged. OS is Win7; graphics is just an integrated gpu chip.

**Comment by Lineth** [comment]
Found it. Needed to update my drivers.
