### ISSUE TITLE
Dominated planets joining Republic or Free Worlds

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2157]
As in FW missions for Albatross and Bloodsea. I saw a question how to un-dominate a planet, because a person felt bad for continuing extortion after these planets joined player's side, and got advised to edit a save file.

Let's make planets reset their tribute/dominated status when they change governments. It sounds reasonable that, for example, if Republican Navy starts to patrol that system they would have none of that and such "agreements" wouldn't be honored… at least, until racketeer in question shows up and takes a shot at reminding planet's population who's the boss.

**Comment by Wrzlprnft** [comment]
similar to #2010 ?

**Comment by Amazinite** [comment]
I would suggest you try and keep up with the commits and new features coming in the next update. It sounds like you're using a set version instead of compiling your own from source, because this is the third issue you've posted (the other two being #2154 and #2119) that has already been resolved in some way per a recent commit to the master that hasn't been released.

**Comment by KiLEdEnNis** [comment]
I don't build from source but I've been around since around issue 1000 or so, the advantage of being around for long is that you start to know what has been addressed and what isn't ( ͡~ ͜ʖ ͡o)

**Comment by Tadrix** [comment]
@Wrzlprnft Not exactly, nope. Issue you mention is closely related to what I described, yes, but my proposition wasn't about giving player option to "free" a planet, it was about automatically freeing it after it changed governments. As I said, new government wouldn't abide such extortion, especially, if its navy is so much better than previous government's one. I'd add that even better would be, if the first time player returns to the system he lost, he's met with overwhelming force (not necessarily hostile, though, just there to make sure no one tries to ask for tribute again). It would be one time event, but the planet's security would change depending on new government's war capabilities. In other words, I proposed to handle this more realistically, especially because such addition wouldn't hurt gameplay at all. For those who insist on dominating all planets this could be a challenge to defeat it again, with its new defense fleet.

@Amazinite You are right, I'm not compiling from source. Looking at frequency of commits, I wouldn't do it anytime soon, seeing as at this stage I'm a player and not a developer. If there indeed is a completed feature list for the new version, it would be nice if you could point at it.

@KiLEdEnNis Yeah, it's called experience. :)

**Comment by Amazinite** [comment]
[The changelog](https://github.com/endless-sky/endless-sky/blob/master/changelog) was updated four days ago with what's coming in v0.9.6, but it's usually only updated before a new version is released or if it's been a few months since the last changelog update. Aside from that you'd need to just [read the recent commits.](https://github.com/endless-sky/endless-sky/commits/master)

**Comment by Wrzlprnft** [comment]
i was refferring to the same issue, not the se solution, and wondering if we need this, if we have the other. dominaters gonna dominate it anyway again

**Comment by jafdy** [comment]
A planet could be "un-dominated" in an event if you so wished. The defense fleets could also be changed if you wished. 
If you want this you can try it your self but anything to do with dominating planets is low priority unless it's a bug.

**Comment by whismerhill** [comment]
@Amazinite 
I had a look at the recent commits & changelog, there is the commit that allows to "undominate" so to speak but it's not what he's talking about or did I miss something else ?

@jafdy 
seems like exactly what he's talking about

**Comment by whismerhill** [comment]
for the record, I just had dominated seginus & alphecca prior to FW "liberation" of those planets, and yeah I think it would be nice to remove the dominated status, Otherwise it's a bit weird : 
-leaders of the "liberated" world : "hi Free Worlds representative, ho and look who's here, the pirate who demands us for money every day to not exterminate us, sure sure let's comply to whatever" ...  hahaha

**Comment by Tadrix** [comment]
Exactly what I was talking about.

It's strange how they believe in better future with Free Worlds when one of their extortionists (FW representatives) stands right there and collects daily payment. One of worlds agrees to join when pirate lord is out. Why they don't mention the player?

**Comment by KiLEdEnNis** [comment]
since tribute is just an extra feature (you can even dominate FW worlds when being a part of them), I don't really see a fix
ya can already [relinquish? cancel?] tributes

**Comment by Tadrix** [comment]
As I earlier said, I propose game automatically cancels domination status for planets at the moment they change governments. If player still wants to dominate them, they can feel free to damage their reputation with the new government. AFAIK, now old government still holds grudge, but new one doesn't, which is strange.

**Comment by KiLEdEnNis** [comment]
they dominated the planet itself, not the planet under that government
it would be annoying if a large amount of dominated systems changed governments & became undominated
& while ya are at it ya should mention the defense fleets that should change when the government does
won't happen either, although... maybe it will if dominating becomes more than a side feature

**Comment by whismerhill** [comment]
@KiLEdEnNis 
and when you dominate a planet, who do you think gives you the money ?
the planet itself ? no, its representative, aka the local government ...

**Comment by KiLEdEnNis** [comment]
yes, and if the "government" would change, it's still the same people paying you, but under a different flag

**Comment by Bladewood** [comment]
Here's what I understand of his posts: The planet itself makes the money, it just belongs to different factions. That state of belonging does not affect the planet's money-making process.

**Comment by whismerhill** [comment]
@KiLEdEnNis 
actually, depends, can be the same people or not
in the case of FW, at least the current "leader" seems the same, however there could be some changes behind that, if I were them I would at least reevaluate whether or not you keep paying tribute.
in the case of pirate to syndicate, the "leader" changes obviously...

**Comment by KiLEdEnNis** [comment]
the planet has its leaders, and they answer to the government, even when captured by another government they stay leader of the planet

if tribute becomes more than a side-feature, the fleets and even tribute payments would probably change
if not, then it stays a side feature

**Comment by jafdy** [comment]
@Tadrix I am going to refer you to my first comment. Events and missions can remove the tribute from a planet.

**Comment by Tadrix** [comment]
Ok, then, should I edit FW campaign missions to include such events for pirate worlds?

**Comment by whismerhill** [comment]
@Tadrix 
also when I don't remember which pirate world becomes syndicate might be algenib or somewhere around that.

**Comment by endless-sky** [comment]
Tribute is intentionally treated as its own mini-game separate from the mission strings, because having the story line take dominated planets into account would be way too much work. And, I suspect players would be very annoyed if they'd gone to the effort of capturing lots of planets only to lose that tribute just because their governments changed.

**Comment by Tadrix** [comment]
It's not like the whole galaxy changes. Could at least these events be incorporated in pirate planet liberation missions? Because it's absurd when player is tasked with dealing with one pirate overlord who's draining planetary budgets dry and then they suddenly become friends, when player himself/herself does exactly the same. I don't even think this event is necessary when someone (like Men) becomes Independent, but it surely would be logical to occur when planet permanently changes affiliation to/from Free Worlds ↔ Republic, except when such change is short-lived (like when for one mission it is occupied by Republic only to be reclaimed by Free Worlds — changes wouldn't have time to take place).

**Comment by KiLEdEnNis** [comment]
@Tadrix 

> And, I suspect players would be very annoyed if they'd gone to the effort of capturing lots of planets only to lose that tribute just because their governments changed.

**Comment by Tadrix** [comment]
Ok then, is it possible for the mission to require the player to relinquish domination over the planet? Like: "They're not joining FW if we don't get rid of those racketeers who are sapping them dry. This includes you, you mean asshole! Now, play nice and stop extorting them."
Because otherwise, if pirates get punished but player's extortion is acceptable it either shows that campaign's events make no sense or otherwise Free Worlds is a tyranny.

**Comment by Amazinite** [comment]
`not "tribute: <planet>" > 0`?

**Comment by Amazinite** [comment]
>otherwise Free Worlds is a tyranny.

How isn't it already? :)
