### ISSUE TITLE
Cycling through systems with the jump button while a planet is selected

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2158]
If you select a planet on the map panel then press J (or whatever your jump button is) to cycle through the systems, the name on the panel does not update.

Selecting a planet
![aa3e3063b04b42348d580a6015e1aa4c](https://cloud.githubusercontent.com/assets/17688683/23096366/02d4cbe0-f5e9-11e6-86e9-5d61ec844a60.png)

Cycling
![f5264bb019a940d995886cef59d67e47](https://cloud.githubusercontent.com/assets/17688683/23096370/0c1d366a-f5e9-11e6-81ff-0350663ce71f.png)

The name remains "???"

**Comment by endless-sky** [comment]
Fixed in f29cebb.

**Comment by Amazinite** [comment]
>Closing this because 

0.9.6 
>is released now.
