### ISSUE TITLE
Can see shipyard and outfit contents in unexplored systems

### ISSUE THREAD

**Issue by kaylara** [endless-sky/endless-sky#2159]
I can see shipyard and outfit contents in unexplored systems to some extent (I haven't probed this much). I can certainly see whether or not unexplored systems have a shipyard or outfit sellers.

Easy to reproduce:
> Start a new game
> Exit planet
> Enter Map
> Click on system to to the East or South that is unexplored.
> Click on outfits

I've attached screen shots as well from both a moderately played game and a new game. I have not attached a pilot as anyone should be able to reproduce. 

![screen shot 2017-02-19 at 5 51 15 am](https://cloud.githubusercontent.com/assets/25284676/23102092/2f8aed34-f668-11e6-81a4-7174cea2cff9.png)
![screen shot 2017-02-19 at 5 51 09 am](https://cloud.githubusercontent.com/assets/25284676/23102094/2f8ca8d6-f668-11e6-874e-981cb427a0ec.png)
![screen shot 2017-02-19 at 5 50 53 am](https://cloud.githubusercontent.com/assets/25284676/23102095/2f8d2a86-f668-11e6-8e76-a569648675e3.png)
![screen shot 2017-02-19 at 5 50 41 am](https://cloud.githubusercontent.com/assets/25284676/23102093/2f8c82f2-f668-11e6-89b4-df5e95280f87.png)
![screen shot 2017-02-09 at 12 02 54 am](https://cloud.githubusercontent.com/assets/25284676/23102096/2f91dee6-f668-11e6-9f01-880fae1f1b54.png)

**Comment by Amazinite** [comment]
Nice find.

**Comment by endless-sky** [comment]
Fixed in 0a964f6. Thanks!

**Comment by whismerhill** [comment]
close ?

**Comment by KiLEdEnNis** [comment]
it's fixed & the version that fixe it is released, so yes
