### ISSUE TITLE
720p resolution cuts off the bottom of some buttons 

### ISSUE THREAD

**Issue by kaylara** [endless-sky/endless-sky#2160]
Cosmetic issue. Long story short, I use my computer from across the room with a TV as a display for my 2011 iMac running . In order to be able to read the text, I need my resolution at 720p. At this resolution, some buttons are cut off. See screen shots compared 720p and 1080p for the Hire/Fire buttons
720p:
![720p hire fire](https://cloud.githubusercontent.com/assets/25284676/23104714/ba01a3b0-f698-11e6-9d80-57bf60922e03.png)

1080p:
![1080p hire fire](https://cloud.githubusercontent.com/assets/25284676/23104723/caf95690-f698-11e6-85ca-f9e91cae1136.png)

At this resolution in full-screen, I can play just fine and it's a cosmetic issue.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/issues/1778#issuecomment-256499849
>The game was designed for a minimum resolution of 1024 x 768. If your screen is smaller than that, some things won't fit.
