### ISSUE TITLE
Page-down scrolls too far in "player info" tab

### ISSUE THREAD

**Issue by kaylara** [endless-sky/endless-sky#2161]
Because of depreciation, it's often not worth it to sell ships. Instead, I keep them in case I want to do more FOO later on. This means I have a very large number of ships.

When I press a "page down" on my iMac 2011 running 10.12.3, regardless of resolution, some ships get skipped. When I scroll with the scroll wheel, I have more fine control.

Note that "Vai Yo Eh" is the last ship in this list:
![topofplayerinfoscreen](https://cloud.githubusercontent.com/assets/25284676/23104804/3ef3e5c8-f69a-11e6-9a75-266dbaff2995.png)

I hit "page-down" once on my keyboard, and see these ships. Note in particular "Gut Fury" is the top ship. I would expect "Vai Yo Eh" to be immediately above "Gut Fury":
![page down once](https://cloud.githubusercontent.com/assets/25284676/23104806/4f336e2c-f69a-11e6-8def-8494f3203ae7.png)

Now I scroll up slowly, and see that page down skipped all the ships from "Du e Loh" to "Mordred's Naga":
![wheel scroll up](https://cloud.githubusercontent.com/assets/25284676/23104818/928e7720-f69a-11e6-97c7-66490f5d3698.png)

This happens at both 1080p resolution and 720p resolution, so I do not think it is related to the button cut off issue from [issue2160](https://github.com/endless-sky/endless-sky/issues/2160):.

**Comment by endless-sky** [comment]
Fixed in 3669839.

**Comment by MCOfficer** [comment]
closed?
