### ISSUE TITLE
How did Kor Sestor drones have access to a jump drive?

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2164]
In the Wanderer story, at some point there is a Kor Sestor fleet rushing through the Eye, and your job is to find the fleet. The thing is, I looked in *every* single planet accessible to them, to no avail. After examining the mission file, I found out that they fled to Alnilam.

But, how is this possible? There is not a single hyperspace link between the Wanderers and human space, so they would have to use a jump drive to get there. Did they get one from the still-alive Korath faction?

**Comment by Bladewood** [comment]
It's the Alphas that are using the drives.
They're using the same trick as the Unfettered to move their drives: one at a time.

**Comment by Rakete1111** [comment]
@Bladewood That would make sense. Then I probably would expect that they are equipped with jump drives, not hyper drives.

**Comment by Bladewood** [comment]
They have only a few jump drives; they move a few jump drive ships at a time, refit all of their ships except for one with hyperdrives, send the sole jump-capable ship back with all of the jump drives, refit the hyperdrive ships on that end with jump drives, repeat.

**Comment by KiLEdEnNis** [comment]
@Bladewood the trick is "2+ at a time, 1 needs to carry the Jump Drives back"

I figured out the Alphas have Jump Drives & are ferrying the Sestor ships to human space, but it should be stated more clearly in the base game, even if it just got mentioned that the Alphas had a few Jump Drives

**Comment by jafdy** [comment]
Perhaps the mission text should mention that some of the ships that left before your fleet took off where using jump drives.

**Comment by KiLEdEnNis** [comment]
or they merely transported them but didn't use them yet

**Comment by jafdy** [comment]
Yes, but it gives a clue as to where they went.
