### ISSUE TITLE
[Balance] Hai Jump Drive Mission and the Shuttle

### ISSUE THREAD

**Issue by Hadron1776** [endless-sky/endless-sky#2167]
The Hai Jump drive mission pays 5 million credits for a jump drive - and is available right from the start. The  
Shuttle has 20 tons of cargo space - exactly enough to fit a jump drive. On top of that, while the Unfettered will crush a shuttle, they are ridiculously easy to bribe, so in my games, I would go straight for the Durax system (pirates fighting korath raiders) to get a jump drive, then bee-line for Unfettered space. Despite being massively outgunned, I can turn in my drive for 5m credits in maybe 1-2 in-game weeks. 
This instantly pays off my mortgage. It is repeatable and can allow one to jump straight from shuttlecraft to bactrian with no middle step.

Is this intentional?

Possible solutions are:
 -Reduce the payout of this "mission"
 -Reduce shuttle cargo capacity by 1
 -Gate the mission behind something
 -Increase the bribe fraction of the Unfettered ships and/or planets

**Comment by jafdy** [comment]
"You can" is the key here. In practice most people won't as they are taking a lot of a risk. Also most new players won't yet know they can do this. 
That said it may be an idea to reduce the payments in line with deprecation.

**Comment by Amazinite** [comment]
I don't really see a problem in this. This requires
1) Knowledge of the Korath Raiders,
2) Knowledge of the Unfettered jump drive mission,
3) Waiting a while in Durax for a Raider, and
4) Hoping the pirates don't obliterate the Raider,
so no new player is going to be able to do this right off the bat and it's only going to be older players who already know a bunch of ways to get easy cash like this.

But the payout of that mission hasn't been changed for depreciation, so I wouldn't be against lowering its payout.

**Comment by endless-sky** [comment]
Changed the payoff in 83d852d.

**Comment by Bladewood** [comment]
But... that's identical to the regular jump drive price...

**Comment by KiLEdEnNis** [comment]
"One million credits" > "One and a quarter million credits"
it just sounds better

**Comment by endless-sky** [comment]
Closing because 0.9.6 is released.
