### ISSUE TITLE
Domination & Government Change interactions

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#2168]
Domination is apparently independent of government changes, it shouldn't be completely so
during some quests the government of some planets do change, yet they continue to pay you tribute & be (dominated)
if the government change is temporary that's alright in my book, however if it's permanent, then domination should be removed at least on a case by case basis : 
(example : I think at least one system goes from pirate to "rogue syndicate" or something, it seems to me that such a powerful faction wouldn't pay "tributes" to "pirates/players" particularly with only a second hand experience of the power of the player's fleet)

discuss.

**Comment by KiLEdEnNis** [comment]
I assume you saw it was a duplicate & closed?

**Comment by whismerhill** [comment]
y
