### ISSUE TITLE
New Ship Outline color customization request

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#2169]
So I played a fair bit with the new outline & hp/shields overlay both enabled
The new outline definitely helps a lot.
If I had one little last request regarding that question, it would be the ability to customize the color of the outline (just like in Terraria one can customize cursor color)
Reason being that while the green outline helps a lot and falls in line with current gfx "choices" it's a bit too similar, and if I was able to customize it, I'd choose something blue/purple maybe. Also for a slightly more discreet outline that still helps, black could be good as well as some grays I suppose.

Discuss.

**Comment by KiLEdEnNis** [comment]
either pick the color or it matches whatever swizzle you have (which probably isn't a good idea yet because all ya can have legit is blue & green)

**Comment by endless-sky** [comment]
I've made it customizable via plugins in commit b03bc5d. Given that right now the game doesn't have a built-in color picker, it'd be a pain to do more than that.
