### ISSUE TITLE
Troop carriers mentioned in FW missions

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2171]
Free Worlds storyline mentions troop carriers and some other interesting ship types which aren't in the game.  Are there any plans to introduce those?

**Comment by KiLEdEnNis** [comment]
can you give the examples of which you are speaking?

**Comment by Amazinite** [comment]
Any ship with high crew capacity is a troop carrier. The Navy Cruiser is considered a troop carrier.

**Comment by Tadrix** [comment]
@KiLEdEnNis I had at least two, although there's only one I currently remember — [aforementioned Free Worlds troop carriers](https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20start.txt) (mission "Liberate Kornephoros", line 132):
> The last of the Navy vessels in orbit has been subdued. As you land, you find that several Free Worlds troop transports have already set down in the spaceport and corralled the remaining Navy officers into a small circle. You would estimate that there are several hundred Navy prisoners. Another transport lands, carrying more prisoners: the Navy troops who had been guarding the mines on Clink.

**Comment by toilethinges** [comment]
The Free Worlds use Blackbirds as troop carriers, I believe. They don't have a dedicated military troopship, though.

**Comment by MessyMix** [comment]
While I think that the game is referring to actual ships carrying crew (or retrofitted warships / freighters used for personnel logistics), perhaps a dedicated Navy transport ship (a la Bactrian) isn't a bad idea.

**Comment by kaylara** [comment]
I think the engine capacity, cargo capacity, outfit capacity, and hull/shields for a troop carrier should be very limited. This agrees conceptually with its purpose (carry troops after warships have cleared an area) and limits its ability to be a warship like the Bactrian.

The player could use it as a boarding ship, but only at high risk of dying and with frustratingly slow performance.

**Comment by MessyMix** [comment]
@kaylara, I completely agree. I was saying that the ship's ability to transport crew should be similar to that of the Bactrian, but it should not perform as well in other departments. What you said is _exactly_ what I had in mind.

**Comment by TJesionowski** [comment]
We desperately need something to outperform the Bactrian in the crew department.

**Comment by Bladewood** [comment]
*world-ship*

**Comment by jafdy** [comment]
No, we just need to weaken the Bactrian.

**Comment by KiLEdEnNis** [comment]
tbh in those battles where ya return the future Oathkeepers in max. 4 Blackbirds:
they have max. 23 PoW's per ship, having up to 92 captured Navy crew
I think a mission mentions there are hundreds of them though

**Comment by Tadrix** [comment]
> The mining outpost on Clink is swarming with Navy officers; you would guess that they in fact outnumber the miners. You are not sure how you are going to get in there and contact Katya without the Navy noticing.

> The last of the Navy vessels in orbit has been subdued. As you land, you find that several Free Worlds troop transports have already set down in the spaceport and corralled the remaining Navy officers into a small circle. You would estimate that there are several hundred Navy prisoners. Another transport lands, carrying more prisoners: the Navy troops who had been guarding the mines on Clink.

These both suggest that troop transports aren't Tarazed Blackbirds, and are, in fact, HUGE.

**Comment by MCOfficer** [comment]
to be fair, a troop transport does usually not offer near as much comfort and personal space as a passenger shuttle. considering that every bunk could be refitted to hold up to 4 soldiers, modified blackbirds could indeed carry such amounts.

**Comment by Amazinite** [comment]
>These both suggest that troop transports aren't Tarazed Blackbirds, and are, in fact, huge.

How does this suggest that it *isn't* a Blackbird, or that they're huge? And huge how? Huge in size or huge in space? 

I'd like to point out that the game writing seems to avoid directly mentioning ship model names. It's usually stuff like "troop carrier" or "freighter" (lower case), never Blackbird or Freighter.

**Comment by Bladewood** [comment]
There could just be a *lot* of them.

**Comment by Tadrix** [comment]
@Amazinite Mission mentions that there's single troop transport bringing Navy personnel from Clink. Another mission mentions that there's more Navy than miners on Clink. Clink is a colony. A Blackbird can transport at most 23 passengers/prisoners in stock configuration (or 25 if unarmed, w/o turrets, or 43 if unarmed and all cargo space and outfit space modded with bunks). Somehow I doubt a colony would mean less than half a hundred people. More like three or five times that number, even if all actual mining gets done by robots.

**Comment by KiLEdEnNis** [comment]
several is a low amount, like 3-6 or so

**Comment by jafdy** [comment]
If the Navy moved some forces out after you visit but before you invade then there could be as few as a dozen people there. Also the Navy won't try to fight on the ground so in all likelihood you wouldn't need very many people to cover the entire group. Maybe 20ish per 100.

**Comment by Amazinite** [comment]
Several is more than a few but less than a dozen.

**Comment by Bladewood** [comment]
https://duckduckgo.com/?q=how+much+is+several&t=ffab&ia=definition
Not this argument...

**Comment by Tadrix** [comment]
@KiLEdEnNis I thought so.

@jafdy Would they? I think I saw a descriptions like this:
> The mining outpost is swarming with Navy guards; they seem to have turned this moon into a temporary base of operations. The mine has been shut down, and no one is being allowed in or out of the mining outpost. It is not clear whether the miners are prisoners, or merely under a very tight watch.

> 	There are hundreds of Navy officers patrolling this small spaceport, looking for any signs of local resistance.

Nah, it doesn't look like they would abandon the planet just before the invasion…

**Comment by jafdy** [comment]
The people where on Clink looking for Katya. It's a perfectly reasonable assumption that many would have left in the 4+ days since you visited.

**Comment by endless-sky** [comment]
The reason there are hundreds of Navy soldiers on those planets is that their ships are garrisoned there. Once the battle begins in earnest, they're going to have every ship in the air, and there will be only a skeleton crew left on the ground.
