### ISSUE TITLE
[balance] Liberate Kornephos too hard

### ISSUE THREAD

**Issue by ldsgsm** [endless-sky/endless-sky#2173]
I started playing through Endless Sky with a fresh game in 0.9.6. I deliberately avoided farming in Hai space for powerful ships, or scavenging for Korath ships in Syndicate space, because I wanted to see how the game felt when played in the "obvious" linear fashion of "Earn money, buy quality human ships, work through the Free Worlds Story Line."

I am currently at around ~2.5 million credits with a clipper, and am supposed to be liberating Kornephos. Unfortunately, my clipper dies almost instantly against the Republic's army, and said army has essentially destroyed the Free Worlds militia. It is certainly possible for me to go out and spend some time earning more money to get a more powerful ship, or to acquire a fleet for myself, but I am not sure that it ought to be necessary, for someone completing the main storyline while passively wandering the galaxy, to take a bunch of time off to upgrade his ship.

**Comment by Amazinite** [comment]
Given that there are people that have beaten the campaign in a Clipper, I think it's safe to say that this is more of a personal issue. If you're looking for fighting tips, I'd check the forums instead of coming here and saying it's a balance issue.

**Comment by ldsgsm** [comment]
Okay. If this is the difficulty the campaign is supposed to be at, I don't
want to complain about my own incompetence.

**Comment by MessyMix** [comment]
@ldsgsm, it can be very difficult. In fact, I spent the majority of my first hours reverting save after save. It _is_ doable in a Clipper; I did it in a Clipper. Having said that, it was extremely difficult, and required me to skirt around the entire battle. I stayed with a Clipper until well into fw middle, but if you plan on doing something like that, just be prepared to run from every battle you see, and hope the rest of the FW fleets can take care of any threat. So I completely understand where you're coming from, and it is not a matter of your own incompetence. Or at least, it's not entirely down to your incompetence. Keep your chin up. It's hard, but it's doable. I know you're supposed to start the FW line with an Agorsy-like ship, so a Clipper isn't exactly sufficient, but you can make it work.

**Comment by ldsgsm** [comment]
My first time through, I did it with a shield beetle, which was much easier.

If an agorsy is adequate for the FW mission, though, then the campaign is
very well-paced, and I entirely withdraw my previous objections--playing
the game through "naturally" as I said, I could buy an agorsy right now,
and have a little left over to refurbish it, but that is all. I withdraw my
concerns.

**Comment by ldsgsm** [comment]
(For the record, I did stay at the outskirts of the battle, successfully, and the entire Free Worlds fleet died)

**Comment by kikotheexile** [comment]
you can beat that mission with a single clipper, you just need to participate in the battle - but not rush head long into it and get yourself killed. 

By this stage in the game, you should at the very least have a medium warship along the lines of a bastion, or a heavily armed freighter like a behemoth.

**Comment by kikotheexile** [comment]
its not an issue of balance but an issue of you not upgrading. I mean, imagine playing an MMO and using level 1 gear for level 15 content out of, say, 50 actual levels. Can you do it? Sure. Will it be easy? No.

**Comment by KiLEdEnNis** [comment]
the game has to be fun for bad/new players in ships that they can get in time, but it also has to be challenging for experienced players
sometimes it can help if new players do bad, they may be like "what if I try ~" (or rage quit & leave a negative review)

**Comment by ldsgsm** [comment]
And that is my concern. I am an enfranchised player (though I do not claim
to be a skilled one), and I was doing reasonably profitable things without
going out of my way to break the game. I *don't* have money for a bactrian,
and I am not especially close, either (that is, I was at least 2 mil away
from it). I am not complaining because I am unable to get that money, but
becauae it worries me that I do not have it naturally when the game expects
me to.

**Comment by ldsgsm** [comment]
If really struggling on this campaign at this point is in line with MZ's vision, then okay--it is certainly possible to get past. I was just providing a data point in case it was not.

**Comment by KiLEdEnNis** [comment]
it's meant to not be so easy that you can speed through the campaign
if in the future enemies get more ships the more/better ships the player has or the higher the combat rating is, it could "balance" it for both newbies & experienced players

**Comment by MessyMix** [comment]
@kikotheexile you're supposed to start in an Agorsy, and Liberate Kornephoros is at the beginning of `free worlds start.txt`, so you're not supposed to be in a Bastion or a Heavy Freighter.

**Comment by kikotheexile** [comment]
@MessyMix please don't nit-pick for the point of arguing with me, here. We have a discord and private messages for that. 

Just for the record:
I did say that it can be beaten with a Clipper (read: the sister ship of the Argosy which costs half as much as said argosy and has far less total HP than said argosy)  but that you *should* have a medium warship or heavy freighter that are combat ready. Not that the game was intended to be played that way. 

This is because I do agree that, for brand new players that discovered the story immediately, these first two battles are a bit on the difficult side. The republic brings an entire battle fleet and splits it between two systems, and a bunch of random merchants have to beat them back. The under dog syndrome is real.

**Comment by MessyMix** [comment]
>for brand new players that have discovered the story immediately, these first two battles are a bit on the difficult side. The republic brings an entire battle fleet and splits it between the two systems

And that's what I love about ES. The first time they all warped in, I just awed at all their massive ships and equipment. It was glorious. And I did not intend to argue with you.

**Comment by Jorlem** [comment]
Would it be possible/reasonable to add a secondary confirmation to the part of the storyline where you join the FW militia, depending on ship strength? Basically, if you are using a ship that is less powerful than what the game expects the player to have, have a character remark that the player must be very brave to be willing to go into battle in that ship, or ask if they are sure they want to risk their life in such a fragile ship.

That would give new players a warning that they might want back off and get better prepared before proceeding, while experienced players could just click yes, or would never see it because they are in a ship that is at least as strong as the game expects.

Alternatively, within the event where you get the letter with the offer to join the militia, if you have a ship weaker than the game expects, the letter could include an additional section where the sender offers to pull some strings to get the player a one-time discount to buy an Argosy from one of the FW shipyards.  I have no idea if it is possible to do that through the normal interface, and if it isn't, perhaps the sale could be done via an event that triggers upon entering the shipyard.

**Comment by KiLEdEnNis** [comment]
@Jorlem that seems like a good idea: 1 branch if you want to be a "support" & 1 if you want to be a "soldier"

**Comment by MessyMix** [comment]
@KiLEdEnNis, I don't think that's what @Jorlem had in mind (with the "support" and "soldier" stuff). It would require the writing of a completely new branch altogether. I think what Jorlem was saying was that you can choose to postpone the FW branch if you feel your ship is not strong enough.

**Comment by Amazinite** [comment]
The player already has that choice. As long as there is no deadline, just don't complete the mission.

**Comment by KiLEdEnNis** [comment]
I meant a side branch to stay off the fighting a bit in the start (at least from big battles)

**Comment by jafdy** [comment]
What about a check to see if the player has a warship of some kind. If not then enlarge the size of the FW fleet a bit to make it easier.

**Comment by Bladewood** [comment]
Unrealistic.

**Comment by jafdy** [comment]
One falcon? Or one bastion. It's to save those people flying shuttles. 
I only bring it up as it's an alternative to other fix.

**Comment by KiLEdEnNis** [comment]
@jafdy I thought of the check for a warship, but what if the player has like an Argosy, Clipper, or a retrofitted heavy freighter?

**Comment by Jorlem** [comment]
@Amazinite Yeah, I know that the choice is there, what I'm proposing is that, if the game detects that the player's ship is weaker than expected, there be a secondary confirmation choice after the player initially selects yes, with the dialogue hinting to the player that their ship might not be strong enough for what is coming. Selecting to delay from the confirmation choice would have the same result as selecting to delay from the initial choice. No need for an entire separate branch, just one extra choice. 

As for making the determination, either for this or the suggestion of buffing the FW fleet for the early missions, would it be possible to look at the sum of the player's ship's shield and hull values, alongside the total damage per second output of the player's ship's primary weapons, and use those values to determine what happens? For example, if the early missions are meant to be done with an Argosy, as was stated earlier, compare those values on a stock Argosy to the player's ship. If either of them are less than the stock Argosy, trigger the "are you sure" confirmation choice. For the battles, if the player's ship's shield+hull is below the Argosy's value, add in some boost to the FW fleet. If the player's ship's primary DPS is below the Argosy, trigger a different boost to the FW fleets. That way, if both values are below the Argosy, then both boosts will trigger, and the size of that battle should be enough to clue the player in to the fact that they need a better ship.

**Comment by jafdy** [comment]
Fleet value would be an easier measure to use.

**Comment by Jorlem** [comment]
Easier, but less useful in my opinion.  Someone who has a few smaller ships in their fleet could easily pass value thresholds, without giving any actually useful information on how combat ready the fleet is, and these checks I'm suggesting would be to determine if a new player could reasonably survive what is going to happen.  Just having an expensive fleet doesn't mean much if they are all easily destroyed by the Republic's warships, and even if the fleet survives, if the player's ship is destroyed, none of the rest matter,

For example, let's say someone tries to start that part of the chain while flying a Bounder, with a Freighter with a few fuel pods as an escort. The fleet value is greater than that of an Argosy, but the Argosy can take far more of a beating than either of them, and put together they only have 100 more "HP" than the Argosy. And as ships become disabled at about 25% remaining hull, splitting that "HP" over two or more ships means that they'll become disabled faster than the single Argosy would.

**Comment by Nechochwen-D** [comment]
@Jorlem It would indeed be possible to tally those values.
