### ISSUE TITLE
[Bug?] Random fleets in Men system after it becoming Independent

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2175]
The pattern is as follows: When player arrives in the system (at least confirmed when taking off of Thule or Smuggler's Den), there can be or arrive some pirate ships. After dispatching those there are no more — all traffic after that is considered "allies", even if being same color as pirates. And there will be no hostiles until next such time, which leads me to think initial ones is a bug and not by design (otherwise there would spawn some random hostile pirates afterwards too, right?). It's almost as if switch "spawn hostile/spawn friendly" flips several seconds too late.

**Comment by KiLEdEnNis** [comment]
I think pirates still rarely spawn:
`	system Men
		government Independent
		fleet "Small Independent" 400
		fleet "Large Independent" 600
		fleet "Small Southern Merchants" 2000
		fleet "Large Southern Merchants" 4000
		fleet "Small Southern Pirates" 2500
		fleet "Large Southern Pirates" 5000
		fleet "Large Free Worlds" 1500`

**Comment by Tadrix** [comment]
@KiLEdEnNis Hmm, could be a coincidence then. When I went away and came back some time later I saw similar mix you just showed. But when Men just converted it was like I described, several times. Still, probably just coincided. I didn't take snapshot at that point to try again.

**Comment by Amazinite** [comment]
>all traffic after that is considered "allies", even if being same color as pirates
The Independent government uses pirate colors.

**Comment by Tadrix** [comment]
@Amazinite Not the case. Real pirates still spawn and attack.

**Comment by Amazinite** [comment]
I know, but you said "allies" in quotes then stated how they had pirate colors, as if they were actually pirates and it messed up. I was point out that the Independent government uses the same swizzle as pirates, so their ships look the same, but they have different attitudes.

**Comment by Amazinite** [comment]
```
government "Independent"
	swizzle 6
	color .78 .36 .36
	
government "Pirate"
	swizzle 6
	color .78 0 0
```

**Comment by Tadrix** [comment]
Sorry, didn't meant that as a bug. Story-wise at this stage they are still pirates, but in disguise, and rather neutral than friendly. Technically, as far as game's mechanics is concerned, they are allies, right.

But I suspected a bug, because every time I took off from Thule just after diplomatic mission (when government changes to Independent), there's always hostiles coming from Smuggler's Den, and sometimes coming from outside also, and afterwards it's mostly allies. Could be some strange RNG going on my machine, but this seemed too persistent to be random.

**Comment by Amazinite** [comment]
After missions? You sure they aren't just mission NPCs?

**Comment by Bladewood** [comment]
Relevant: https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20start.txt#L1494

**Comment by Tadrix** [comment]
Yes, and there's nothing about pirates spawning in Men system, right?

**Comment by endless-sky** [comment]
Is it possible that you have freighters in your fleet? To keep the player from being able to amass a large fleet of defenseless Star Barges, pirate fleets will sometimes spawn even in "safe" systems, with a probability that is dependent on how many freighters you have in your fleet.

**Comment by Tadrix** [comment]
Yes, there were about 10 heavy freighters (2 Hauler III and 8 Deep Rivers, if I recall correctly) and probably 10 more Argosies (used as escorts / light warships by giving large part of cargo space to outfits) and I was accustomed to pirates spawning every now and then (their ships would be customarily confiscated and sold at nearest shipyard) — but this was happening at random. This time it was persistent — there were almost always some pirates taking off from now-friendly Smuggler's Den.

**Comment by Amazinite** [comment]
The more freighters in your fleet = the higher chance of random pirate spawns trying to steal your freighter cargo.

**Comment by Tadrix** [comment]
Yeah, I'm concerned mainly about "Hostiles taking off from friendly station (which should be hostile to them)" part.

Also, funny, how pirates hope to take on some freighters, when count of heavy warships escorting them is several times bigger — but I'm not complaining. :)

**Comment by KiLEdEnNis** [comment]
you can land on hostile places too: bribe them
or maybe they were still there when the station changed to neutral
and the other thing is an AI thing, but if only the "winning side" would attack and the other side would flee, there'd be no battles at all

**Comment by Tadrix** [comment]
Nah, as I said, it was right after Men system became neutral (friendly). If the game sets it as such moments after taking off, then, of course, situation is understandable.

About AI: If both sides are comparable, than yes, of course, this is understandable. But at that point I amassed some 40 Hai Shield Beetles, 26 Vanguards, 20 Kestrels and some less significant ships (including a Lionheart Bactrian flagship). To attack this fleet with some Sparrows and a pair of slightly bigger ships was an obvious suicide. They were just feeding themselves to the war machine. As I said, I didn't complain, but seems to me that AI would do better to differentiate between just uneven fight and overwhelming enemy forces. Since I felt that even depreciation couldn't stop me at that stage, I just deleted said character and made a new pilot.

**Comment by KiLEdEnNis** [comment]
if I remember, the AI avoids battle if they are outnumbered unless they're already in a certain range & can't get away anyway

**Comment by endless-sky** [comment]
"Independent" means "we're really still pirates, but for now we're refraining from piracy to avoid getting in trouble." So, they're quite willing to let pirate ships land on their stations.

**Comment by Tadrix** [comment]
Ok, I presume then that pirate ships taking off those stations are a normal occurrence. In that case, isn't a bug, so I'll close this.

**Comment by KiLEdEnNis** [comment]
wasn't the agreement that the stations would NOT support piracy and thus only let them land if they're not actual pirates?
I get that some leftover ones are leaving, but not landing
