### ISSUE TITLE
[Request] More Quarg missions

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#2176]
i feel like the quarg are still way to mysterious and.. "unknown" right now. we got some missions (at least basic ones) for a lot of species, but when i first encoutered to quearg, i was kinda disappointed. the first alien civilisation i get to see, and theres nothing more than an informative talk? unless this quarg thingy isn't part of the "late game" story including the drak etc., i feel like they deserve a bit more attention.
i would give it a shot myself, but i am no native speaker and therefor probably not qualified to write in the style of the other missions. also, i know i can't force creativity (nor can i force contributors to contribute). so, take your time. i appreciate the work you put into this already.

**Comment by Amazinite** [comment]
No need to request something like this, as story is always planned. Right now, the story focus is on the Wanderers, but next it will likely be on the Coalition which involves the Quarg. And the Quarg are suppose to be mysterious :)

**Comment by MCOfficer** [comment]
good to hear that, i love the plot that is slowly building in the wanderer storyline, along all the cross-references. should i close this or keep it open in case anyone else has this question?

**Comment by Amazinite** [comment]
I'd close it.

**Comment by gunqqer** [comment]
Don't trust the Coalition! They lie! Archons > Pug!

**Comment by Bladewood** [comment]
relevant http://steamcommunity.com/app/404410/tradingforum/135508833657847658/
(yes self-advertisement, you can't stop me)

**Comment by MCOfficer** [comment]
closed to prevent further self-advertisement ;)

**Comment by Bladewood** [comment]
dammit.
