### ISSUE TITLE
Different handling of licenses

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2177]
The first license player gets — the "Pilot's License" — is shown in Outfitter (installed: 1) and in player info Other licenses (Wanderer licenses, Militia Carrier License) are shown only in player info. Does Pilot's License belong to Outfitter anymore?

**Comment by MessyMix** [comment]
Or perhaps the other licenses belong in the outfitter. I would love to see my nice Milita Carrier License in there.

**Comment by Tadrix** [comment]
Or this.

**Comment by Bladewood** [comment]
Good luck making interesting descriptions for them?

**Comment by Wrzlprnft** [comment]
the pilot's license is kind of a relic. the other licenses do not have an outfit for them.

**Comment by MCOfficer** [comment]
well, either remove it or add the other ones from the outfitter.

**Comment by SonEasterZombie** [comment]
Decisions, Decisions

**Comment by Pointedstick** [comment]
This is done; can you close the issue @Tadrix?
