### ISSUE TITLE
Missions during ceasefire in FW campaign (which shouldn't be)?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2178]
Don't know if this has been addressed, but it's peculiar how planets in Republic space don't hesitate to offer jobs to ship flying colors of organization they are in war with. If anything else, they should doubt that mission will be completed (passengers will be safe, cargo won't be destroyed, etc.), especially when destination also is in Republic space.

Meanwhile, anarchistic pirate systems refuse to give any missions (for example, to deliver something illegal to another pirate system).

Or, there aren't any courier missions to deliver something to the other side while safe passage lasts either (these should be timed and better payed than usual rush missions). So, no one trusts player to bring people in or out of Republic space, or send some message to the loved ones on the other side, or something like that, but usual delivery missions? No problem, this ship wouldn't be target of the whole goddamned Navy soon. Your cargo is totally safe. No need to find someone not currently at war with Republic instead. :)

**Comment by Amazinite** [comment]
Well jobs (excluding bounty hunting ones) aren't given by governments, they're given by corporations and civilians, and posted on a public job board that anyone can look at. *shrugs*
As for no pirate jobs. #1935

**Comment by Tadrix** [comment]
@Amazinite Look, I mean no offense, but lately it looks like you are enjoying arguing to everything I write just for arguments sake. I'm just a player who enjoys M.Z.'s amazing storytelling. Currently I'm coming to GitHub only because of Endless Sky, to report if I see something that probably shouldn't be. I'm not here to criticize, but only to try to help or at least to leave some feedback. If it's not welcome here, I can cease doing this. Should I?

Your argument makes no sense. Imagine yourself leaving such job ad. Then, next day, some pilot, having answered your ad, comes over to collect your valuable cargo, and you get to know his ship has a giant green target painted all over her. Also, you probably don't know how he got here, but you certainly know that en route and at destination there surely will be some Navy patrols eager to blast his ship and your valuable cargo out of the sky. Now, would you entrust this mission to him, as a private corporation or civilian? Or would you politely tell him to, please, come back when you will not be at war and then try to find someone else, preferably, flying as independent merchant?
Or, imagine your country at active all-out war with country X, as in, massive sea battles going somewhere, with thousands of casualties. You are at the port, trying to hitch a ride to your country's port N. Then country's X warship by the name _X.N.S. Unscrupulous_ comes to the port. No one fires at it, yet you can't ignore understandable increased attention she gets from the port authorities. Then your communicator lights up; apparently her captain has read too your job ad and expresses willingness to bring you to port N. While you are reading this, some salvage ships come in, bringing with them tattered remains of once proud warship. This time it was pirates, they say. This was a pirate ship your Navy successfully destroyed. Still, it serves as a reminder that hostilities are far from over, and, in fact, being here, you already saw a wave of reinforcements departing to conflict lines. Would you set your foot on _X.N.S. Unscrupulous_?

**Comment by jafdy** [comment]
It can be done with the current system. It would be quite time consuming so no one has done it yet. If you feel so strongly you can do it your self and make the PR.

**Comment by Tadrix** [comment]
"Feel strongly" would be too much. I just explained why this is contrary to common sense.

I could write up some missions (but someone would need to check the writing b/c English is a foreign language to me (a fourth language actually, not even second), but I have no idea how to make it so regular missions aren't offered due to safe passage, or that these are offered instead. Any ideas on that?

**Comment by jafdy** [comment]
You would need extra conditions in the start of all the jobs.

**Comment by Tadrix** [comment]
Including ordinary ones? Sheesh. If there were more such different conditions to be introduced (for example, peace, war, truce, safe passage, famine…) I imagine this would quickly become unmanageable? Or, only the new ones (safe passage ones)?

**Comment by MCOfficer** [comment]
i think, for the sake of staying realistic, tadrix' argument is more than valid - this does indeed make no sense. as far as i know most cargo deliveries are managed by shipping companies (as mentioned in "a wolf, a goat and a cabbage") who guarantee for a safe delivery. giving such cargo to a ship that is already in danger as soon as it lifts off is like hiring a single sparrow to escort 3 heavy freighters.

(now, assuming that there is a method for the job board that is being called every time you dock somewhere,) why not add a simple condition called "isHostile" in this method itself? i'm not c++ coder, so i can't be sure, but if works just _a bit similiar_ to java, this should be possible.

**Comment by Amazinite** [comment]
>Your argument makes no sense.

I'm just going to stop here, because you're assuming that I'm even trying to argue you on this point. Take a chill pill.

**Comment by MessyMix** [comment]
@Tadrix, I have to stay with @Amazinite's second comment on this issue. Like you, I read too far into his comment, assuming he was disputing what you were saying. However, upon reading it again, it is evident that Amazinite was only pointing out that cargo missions aren't given by governments, and instead by corporations.

He has good reason to point this out, too: you mentioned that it was
>peculiar how planets in Republic space don't hesitate to offer jobs to ships flying colors of organization they are in war with.

All @Amazinite did was point out that they aren't given by planetary governments, and that they were instead given by the shipping corporations.

I don't think he meant to dispute your claim at all that jobs should not be offered, so perhaps your intuition that he is arguing everything you say for argument's sake is mistaken and is a very strong reaction indeed.

In other news, I agree with what you are saying. But still, you're very argumentative with @Amazinite, which I don't think is warranted by his comment.

**Comment by Amazinite** [comment]
Just going to say what this would take to make happen.
Right now, it's impossible to do with the current job set up.
1) All of human space use the same jobs
2) Hai space and Wanderer space use human jobs (although MZ is looking to change that in the future, and #1928 and #2046 attempt to address that)
3) Making jobs not offer during the war right now (since all the human jobs are the same) means that the player is forced to either do boring trade runs or be pushed into having to plunder/capture for cash, which could be frustrating for many.

Now lets assume 2 gets address so that we don't need to worry about screwing up other races.
If you wanted to make it so that during the war you could only take jobs from FW space (and in the future only from the section of space you are sided with), we'd need to make 2 extra versions of every job and limit where each offers (one set for FW space, one set for Syndicate space, and one set for Republic space). Aside from escort jobs, which are already location specific, and a few region specific jobs made by @Pointedstick, all the other jobs are generic and can offer in any region of human space, so tripling the amount of job data for generic jobs in order to have each region only offer its own types of jobs could get real cluttered real quick. It's possible, but it's messy(mix).

**Comment by MCOfficer** [comment]
@Amazinite i can't see how you can make profit by doing republic jobs during war - only few jobs award you more than 200k credits, but that's one of the lowest bribes you can possibly pay. unless you have a bunch of missions terminating at the same planet, you'd always lose money.
however, i'm no dev, nor do i want to edit every mission there currently is. so if you say it's too much work, i guess i'll leave that issue for now - it's only a tiny detail, after all.

**Comment by KiLEdEnNis** [comment]
if governments where you have a negative reputation towards get their obs filtered by another random value (like 20, meaning that only 1/5th the jobs get offered there), it should be more realistic but not so annoying that you never get jobs

**Comment by Amazinite** [comment]
> i can't see how you can make profit by doing republic jobs during war

Jobs in FW space, not Republic space.

**Comment by Tadrix** [comment]
@Amazinite @MessyMix I stand corrected. I probably overreacted because I was under impression Amazinite very often has something against things I bring up. Could be just my impression though. In that case, I apologize.

Now, about generic jobs and impossibility to set this up, I have a thought but I'm not a dev, so I'm going to ask it as a question here: In the case jobs are tied to a government, would it be possible to define an invisible government for republic space, like "Republic" "Republic (SafePassage)" or rather "Republic" "Republic (Wartime)", which doesn't offer jobs? Then it would be relatively easy to define jobs with source government "Republic (Wartime)" and destination "Free Worlds" for things such as deliver a letter or a parcel to the relative, or event transport passengers which are disillusioned with Republic?

**Comment by Amazinite** [comment]
> i might be wrong here, but i thought bribes are connected to the net worth in someway.

Yeah.

>Now, about generic jobs and impossibility to set this up, I have a thought but I'm not a dev, so I'm going to ask it as a question here: In the case jobs are tied to a government, would it be possible to define an invisible government for republic space, like "Republic" "Republic (SafePassage)" or rather "Republic" "Republic (Wartime)", which doesn't offer jobs? Then it would be relatively easy to define jobs with source government "Republic (Wartime)" and destination "Free Worlds" for things such as deliver a letter or a parcel to the relative, or event transport passengers which are disillusioned with Republic?

That really sounds like it would over complicate things to me. If you wanted jobs that only offered during the war, you'd want something along the lines of
```
source
_government Republic
destination
_government "Free World"
to offer
_has "war begins"
_not "main plot completed"
```
(Underscores as tabs.) This would make it such that the job would only offer between the time of the war beginning and the war ending, and would offer in Republic space going to Free World territory.

**Comment by endless-sky** [comment]
There might be ways to suppress those missions while you're in the story line, but it would be incredibly messy, and every time that new story lines were added that could cause the player to get in trouble with other factions, all the jobs would have to be updated to take those into account, too. That really isn't worth it for the sake of a very minor improvement in realism.
