### ISSUE TITLE
Strange game behavior when objectives completed and game reloaded

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2179]
Specifically, Electron Beam mission. I already have one salvaged from Marauder vessels on my ship. So I get the mission (which doesn't give me option to give that outfit — and anyway I'd rather not to) and then decide to reload snapshot taken during conversation with Freya at the time this mission was given. Normally this would load and initialize that conversation from the beginning. This time it loads and I get a completed mission instead of initial conversation.

**Comment by Bladewood** [comment]
relevant: https://github.com/endless-sky/endless-sky/issues/1909

**Comment by jafdy** [comment]
The conversation is the end of the last mission. This was recorded as finished thus when you reloaded it was finished. If you are so desperate for you electron beams back then you can just try stealing them.

**Comment by Bladewood** [comment]
Not the point of this issue.
> Normally this would load and initialize that conversation from the beginning. This time it loads and I get a completed mission instead of initial conversation.

This is.

**Comment by Tadrix** [comment]
I've no problem stealing them again and I suspected something like that, but it's not like the game should behave.

**Comment by jafdy** [comment]
"Should" is a word to be very careful with. I think the game "Should" be played with out stopping of reloading the save. But that would be ridicules.

**Comment by Tadrix** [comment]
Good luck eschewing life, bio, sleep etc., this game has enough content to be immersed several days non-stop. :) The problem is, saving at this spot screws continuity (player saves at beginning of mission, after loading gets end of mission, at the same in-game date).

**Comment by endless-sky** [comment]
I suspect that your snapshot was actually saved *after* the mission was offered. Otherwise this wouldn't happen.

**Comment by Tadrix** [comment]
Can't check on it, because those saves are already deleted. I'll try to reproduce it on next play-through. Closing issue now, will reopen when able to reproduce the sequence of events.
