### ISSUE TITLE
Feature request: reputation titles

### ISSUE THREAD

**Issue by naehc** [endless-sky/endless-sky#218]
I always liked how the EV games would display your reputation value/level with the various governments as reputation "titles", ranging from e.g. Pillar of Society to Public Enemy at the extremes. In Endless Sky currently, the in-game map does show whether a government is hostile or not through colouring, but to see the levels of goodwill/hostility accrued (for lack of better words) you have to open the save file in a text editor. In terms of practical, gamey use, it's good to know whether e.g. my reputation with the Quarg is high enough to (probably) let me plunder one of their ships without turning them properly hostile. ;) 

This is of course a minor thing, so perhaps only worth doing if the effort involved would be minor as well.

**Comment by gchapyzh** [comment]
For example, the amount of goods sold/bought, amount of ships captured or destroyed, or the space traveled. 
Also, the amount of ships you own and your alliance.

An example of myself:
Independent War Admiral 'Triggerhappy'
    Feared Warlord

Or a merchant:
Republic Merchant Admiral 'Floofy'
    Pillar of Sociery

**Comment by warp-core** [comment]
I'd like to add a category to the logbook for this, probably with the ability to hide governments from it with a token in the government definition in the data files.
Any thoughts?

**Comment by ziproot** [comment]
See my comment [in warp core's PR](https://github.com/endless-sky/endless-sky/pull/6873#issuecomment-1475451491). The map is not nearly as useful as titles.

**Comment by Zitchas** [comment]
Likewise, I find the reputation map to be virtually useless. Either they like me enough to land, or they don't. Mechanically speaking, anything beyond blue (can land), orange (not shooting, but no landing), and red (no landing and they shoot at me) is about all that really matters.

From a story perspective, though, having actual titles (although descriptors might be a better term) based on reputation levels (even better if it is faction-specific descriptors) is much more beneficial than a map color gradient.

Basic example:

"Welcome to our spaceport, First Last <title>"

Early game:
"Welcome to our spaceport, First Last the welcome merchant."

Friendly laste game:
"Welcome to our spaceport, First last the pillar of society."

Even better if we tie it into branches:
"Welcome! We are always thrilled to have such a pillar of society visit our spaceport!" /
"Please make your visit quick, we dislike having petty criminals stay here." (if slightly negative)
