### ISSUE TITLE
[Question] Ramscoop's description

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2181]
It [says](https://github.com/endless-sky/endless-sky/blob/master/data/outfits.txt#L150):
> Although you can install more than one ramscoop, additional ramscoops on a single ship are not as effective as the first.

Is this true? And, if so, how does it work?

**Comment by Amazinite** [comment]
```
double scale = .2 + 1.8 / (.001 * position.Length() + 1);
fuel += .03 * scale * (sqrt(attributes.Get("ramscoop")) + .05 * scale);
```
The square root function means that you need to quadruple your Ramscoop attribute to double your fuel per second.

**Comment by KiLEdEnNis** [comment]
so a catalytic ramscoop is only about 2,5x as good as the regular one? (besides larger space)

**Comment by DingusShingleton** [comment]
Ramscoop 8 is twice as much fuel as ramscoop 2

**Comment by Tadrix** [comment]
Ok, let's see…
Ramscoop r = 1; collection = x; mass = 10 t
Catalytic Ramscoop r = 7; collection = 2,6x; mass = 16 t
Wanderer Ramscoop r = 4; collection = 2x; mass = 7 t
2 Wanderer Ramscoops r = 8; collection = 2,8x; mass = 14 t
If player can get Wanderer Ramscoops, Catalytic one will be worse option — even as the only one. Thanks.
