### ISSUE TITLE
Treat outfits like commodities with fluctuating prices

### ISSUE THREAD

**Issue by lnxworx** [endless-sky/endless-sky#2183]
Rather than having a fixed price for outfits, fluctuate prices for outfits from system to system.   Prices could be based on the assumption of supply and demand.  Perhaps there has been a run on atomic engines lately and as a result the price of atomic engines has tripled...etc.  

Additional systems where outfits are available but have to be ordered for a fee could be added as well.

Example:  My current outfit of weapons is not working for me.  What I really need is to swap this plasma gun for a particle cannon.  Rather than flying all over the galaxy to the outfitter that sells particle cannons, I can go to XYZ system and order one but for a fee and based on currently available stock.  Fees can change from outfitter to outfitter with those being the farthest out costing a lot more.

This could be applied to all outfits or a subset of outfits.  Outfitters can still have a base selection at a fixed price but would be a smaller selection.  Though if you really want to balance out captains becoming ridiculously wealthy too fast, I would apply it to all outfits, requiring careful management of funds.

In addition a delivery wait period would be cool, but I don't know how you would pull that off since one could just jump to a closer system or the system where the outfit is sold by default.

**Comment by Amazinite** [comment]
#928 duplicate issue.

**Comment by KiLEdEnNis** [comment]
and it would seem annoying: "where the hell is this outfit the cheapest... oh fuck, across the universe .-."
next day "I don't feel like playing this game, the outfit price change takes so much time"

or in short: it'd just be very annoying

**Comment by lnxworx** [comment]
Thanks for the feedback.  I am not sure it would be annoying since one of the main mechanics is based on trading commodities.  Would give you the option of traiding weapon and becoming a gun runner as I mentioned in #2182

**Comment by Wrzlprnft** [comment]
on the other hand, there are people complaining that, if you loose smaller ships like fighters, it is already a pain tp re-fit the new ones, since the outfits are scattered. now imagine there is a price difference on top of that.

it is a neat idea, but i think the drawbacks in the current iteration are larger.

i'd say if you work on the idea to overcome the drawbacks(ship insurance?whatever) it is in the realm of the add-able though.

**Comment by jafdy** [comment]
This is a duplicate issue. As me and Local discussed in length at the top of #928 it is hard to make it competitive with commodity trading and still meaningful. And as I point out further down HtoH outfits mess this up completely.
