### ISSUE TITLE
Alternative application of "death benefits"

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#2186]
While I will admit that the way "death benefits" were handled in the game was rather clunky it did give the impression that there was a penalty to needlessly throwing the lives of your crew away and I feel that it does still have a place in the game.

As anyone who has played the game for any length of time will tell you, the majority of crew killed are not as a result of boarding but rather as a result of your ships being blown to smithereens. This, as yet, caries no penalty.

I would propose that "death benefits" be put back into the game but be set at a certain number of days of pay and that the game track how many crew have died recently en order to generate a multiplier to be applied to the crew salary so that it will go up in response to high numbers of crew death.

If implemented appropriately I believe such a measure could extend the period that it is impractical to have more than one ship and allow for some nerfing of the current depreciation system.

**Comment by KiLEdEnNis** [comment]
if you sign up as a crew member you know the risk of getting blown up
boarding wasn't something in your contract, and if you died in hand-to-hand combat (unless defending the ship), the contract would be broken, resulting in you having to pay a fine to the family
at least that's what I think it was

**Comment by jafdy** [comment]
It was a balancing mechanic. It is no longer needed so it has been removed.

Clearly you now write your crew contracts to include the instance where you ask them to board a ship for you.

**Comment by KiLEdEnNis** [comment]
basically, job description: "operating the ship you are assigned to, at the risk and possibility of having the ship blow up or having to defend or attack a ship in hand to hand combat"

**Comment by Nechochwen-D** [comment]
True but if it is instead used in the same way life insurance is IRL I think that it could still be included to add flavor without being overbearing.

**Comment by zwparchman** [comment]
Loss of crew to an exploding ship does carry a heavy penalty. You lose a ship.

**Comment by MessyMix** [comment]
imo, capping still needs balancing. Even though depreciation exists, I can cap without penalty, so that's a free several million bucks per pirate ship I come across. Not balanced.

**Comment by Nechochwen-D** [comment]
Yes and unless you want to rely on the tender mercies of the Republic (or any other faction) as they attack pirates you will need to have a fleet of your own to capture more ships. This invariably leads to some of your own ships getting destroyed at times.

**Comment by DingusShingleton** [comment]
Capping is 25% as profitable as it was before depreciation... so there's that.

**Comment by DingusShingleton** [comment]
I had a proposal that would have fixed both capping and plundering but it didn't get much traction: profit sharing. I posted an early concept of it in #1650, and then later made a more fleshed out version. But by then depreciation was in full effect and I figured what's the point. I suppose it could still have value for balancing capping though.

**Comment by MessyMix** [comment]
@Nechochwen-D: any player mid-late game will have a fleet that is impervious to pirates.

I'm running a fleet that is full of _at least_ T1 heavies; it's probably around 20 ships strong. If I want some free money, I load up the nerve gas, I get full of crew, and I stick on top of a pirate planet for 10 minutes or so, boarding all heavy warships I see (falcons and levis). Free profit right there.

The thing is, now I can go around and cap ships and _keep them_ without penalty. Previously, I could sell ships at a profit, but to keep them would be to incur death benefits. Now, I can keep every ship I capture and run free, and if I want to sell the ships, I can sell them for a great deal. That's unbalanced. DBs (lessened and obviously adjusted for depreciation) will keep balance in check.

**Comment by zwparchman** [comment]
Maybe what is needed to offset the removal of death benefits is a higher cost to hire crew. As has been said by another person here, there is only one reason to hire extra crew.

**Comment by MessyMix** [comment]
Perhaps. Still, there must be a mechanic to balance boarding and capturing. Here's my logic:

245 crew, nerve gas, I'm bound to capture any ship I come across. And since there's no penalty for capping, I _will_ go out of my way to capture ships, and keep the ones I like / sell the ones I don't like. It's not that it's any more profitable; it's just that keeping a captured ship is not costly at all (and at the expense of all my crew members, too!), and it puts me in a capture-everything-spree mindset.

**Comment by Nechochwen-D** [comment]
@MessyMix fair enough.

However, take that fleet of T1 ships against the Hai (Unfettered), Quarg, Kor Automata or any other higher tier and you will loose ships. Death benefits in the form of six months pay, and increased crew salaries (capped at around 250) as your body count climbs, will balance out the "free" profit from capping pirates.

To be clear I was thinking before about the early "firefly" mode and not the later game.
