### ISSUE TITLE
recieving mission cargo in space makes other cargo invisible on the cargo list

### ISSUE THREAD

**Issue by Kryes-Omega** [endless-sky/endless-sky#2188]
This may be rather low priority, but I thought I would mention it. I was working on assisting cargo missions when I noticed that when you receive cargo from a mission while you are in space, such as assisting or boarding, it will remove other cargo you have on board from the 'cargo' list on the ship info screen, but keep it on your ship.

**Comment by tehhowch** [comment]
Interesting bug.
Looks like boarding missions that are not designed to be declined are not currently supported - missions offer even if you do not have space for their cargo or passengers, which can give you negative capacities.
I've fixed that issue, and added support for blocked messages to be displayed if the boarding/assisting mission was chosen to offer but cannot be accepted. For boarding/assisting missions, it does not *currently* make a lot of sense to have blocked messages - the NPC will be either boarded for plundering or assisted and no longer disabled, so it doesn't make much sense to hint to the player that they can get a mission by "returning" to this ship, but by receiving a blocked message the player learns that a new mission is possible if the player boards other similar ships with more available space/bunks.

Still working on the cargo "offset" issue raised here

**Comment by tehhowch** [comment]
Should be addressed by the merging of #3005
