### ISSUE TITLE
Big batch of Enhancements & MORE!

### ISSUE THREAD

**Issue by manitscold123** [endless-sky/endless-sky#2199]
I don't know if this is a thing already, but I find that my flagship usually does not have a lot of cargo space and that it would be great if I could have an escort board.

This is an enhancement, and essentially it just lets you store more things, w/o having to sacrifice needed outfit space (gotta fit dem 6 flamethrowers YO) what could happen is when an escort boards a ship, you can pull up another menu, like you are radioing the escort, and tell them to do this and that.

something else I think would be cool is to have a way to land w/o wasting an entire day. This would reduce the money spent on crew. B/c, when I have my Bactrian w/ like, let's say 100 cargo. I want to board a Korath Raider, with a 30 Jump Drive, and weapons, etc, I want to be able to make many small trips

I also think the Friendly AI is a bit ruthless, and that they murder without a second thought. Like, Pirates murdering after plundering I get, but like, peaceful little birds stopping me from getting robot toys is just a bit savage eh?

Other things you can do is to board working escorts, and just transfer outfits from your ship to theirs

Also, I find that the Jump Drive should not take as long, but that might just be me. 

NEED TO BE ABLE TO BUILD BASES.

Like I said earlier, I have no idea if these have been stated before, I wouldn't know, I don't look through all 295 issues. ( and frankly, IDC ) 💯  :) :1st_place_medal:

**Comment by jafdy** [comment]
BIG BATCH OF duplicates . . . 
Escorts board; #2185 
AI; #172 
Bases; #754

**Comment by sbeden** [comment]
+1 as to the ability to add Base (s), as they are both not used sectors and places where it would make sense (not sure but I've a loose remembrance about this being added by a mod ?).

About the AI, at last an option to set until when the pc ships should attack (for some time now they destroy ships most of the time).

**Comment by KiLEdEnNis** [comment]
a thing I can see being added is transferring cargo to an escort, but ya can just dump your cargo & get escorts to pick them up anyway

**Comment by Amazinite** [comment]
>Like I said earlier, I have no idea if these have been stated before, I wouldn't know, I don't look through all 295 issues. ( and frankly, IDC ) :100: :) :1st_place_medal:

If you really don't care then you probably shouldn't be making issues.

**Comment by whismerhill** [comment]
I have made the mistake in the past to post issues already existing though I try to close them
in any case, you don't need to check out the whole lot of 295 issues
a bit of searching though ...

**Comment by Bladewood** [comment]
It's not just the 295 (293 now) you see. There is a total of 1704 issues.
Search for an issue with the search bar at the very top of the site (the one next to "This repository").

**Comment by DingusShingleton** [comment]
> Like I said earlier, I have no idea if these have been stated before, I wouldn't know, I don't look through all 295 issues. ( and frankly, IDC ) 💯 :) :1st_place_medal:)

Really swell way to integrate yourself with the community there

**Comment by KiLEdEnNis** [comment]
search keywords like boarding, escort, AI, transfer, bases
and if not sure, ask if it's been brought up
next time try & sound more mature, especially the last line gets people to "dislike" you

**Comment by DingusShingleton** [comment]
Yeah, because what it means is "I didn't feel like wasting my time so I figured I would waste all of yours, now code these ideas for me thanks toodles!"

**Comment by KiLEdEnNis** [comment]
ya are still welcome on GitHub, just change the attitude please, and try and search for duplicates a bit
