### ISSUE TITLE
Bug: Fined for having illegal outfits by "The Uninhabited"

### ISSUE THREAD

**Issue by naehc** [endless-sky/endless-sky#220]
See linked screenshot: http://i.imgur.com/wYkKP4u.jpg . Should the Planet entry for Ruin perhaps have 'security 0', like Pirate planets do, to avoid this kind of thing? Assuming that this isn't intended behaviour, that is. ;)

**Comment by endless-sky** [comment]
Fixed in 524975a.

**Comment by naehc** [comment]
Confirmed, no longer an issue once that change is made to pug.txt.
