### ISSUE TITLE
Bank Loans broken by depreciation.

### ISSUE THREAD

**Issue by Startome** [endless-sky/endless-sky#2202]
Hey all, this was a previous discussion located here: 
http://steamcommunity.com/app/404410/discussions/1/143387886723545521/
and
http://steamcommunity.com/app/404410/discussions/0/135510393195205022/

I work for a commercial transport business, and have had exposure to the banking and loan side of things.
Where I don't know or can't get into the nitty gritty details, I do have associates that can. So if I can help at all please let me know.

Also, based on my post on steam and experience mentioned there. I suggest a new equation something like:
((assetvalue/2)-outstanding loans) + average100dayincome = Available Loan

The reason behind this:
When a commercial company requests a working capital (cash) loan from a bank (which is what the one I work for is doing right now), the bank requires double the collateral to be available based on the cash they offer. That covers their risk. 
Hence the dividing the asset value (Ships and outfits) by 2, to reflect the actions of actual banks.

That being said, banks also will not offer you a loan unless they consider you D/I (Debt to Income) Ratio to be low enough. So If you have too many debts compared to the risk they want to take on giving you a loan, they simply won't offer you one.

Now some banks, if you can find a good one, will take your past company trends into account, though many of them are pretty much straight collateral and D/I. This is why I think the average 100 day income has a pretty solid place in this equation. It would allow someone to still get themselves too deep in loans, which obviously really happens, but also allow the banks some level of realism and "protection" from loss.

If the equation yields a negative result, then obviously the bank would consider you too high risk and not offer you a loan.

**Comment by Amazinite** [comment]
Duplicate. #2066 #2049

**Comment by Wrzlprnft** [comment]
i think this is more about setting up a slightly more complex loan calculation than in place,which will also prevail future features

**Comment by KiLEdEnNis** [comment]
the extended depreciation makes it less of an issue though; ya have an income & lose a bit of net worth
but an "overhaul" for loans seems good too, and maybe we can do something about being able to get a huge loan because you managed to cap a ship & sold it for a big spike

**Comment by Startome** [comment]
Moving this to preexisting topic, please comment there.
