### ISSUE TITLE
Not strictly a bug, but…

### ISSUE THREAD

**Issue by Fleurghber** [endless-sky/endless-sky#2203]
Appearance aside, is there (or should there be) any functional difference between the three varieties of Korath World-Ship?

**Comment by KiLEdEnNis** [comment]
it's for flavor
like the Deep River variants (but they differ in cargo space & hull cost & speed, so can't compare them that much)

**Comment by KiLEdEnNis** [comment]
oh, I forgot to actually answer .-.
ty @Amazinite

**Comment by MCOfficer** [comment]
just a wild & crazy idea that doesn't belong here (again):
you could make something up like "there are 3 different prevailing familys, and the colors represent that these ships belong to this or that family". just in case you need story material. yes, i stole this from star wars.

**Comment by KiLEdEnNis** [comment]
same color, different looks

**Comment by MCOfficer** [comment]
aaah, whatever. i should read before i think.

**Comment by endless-sky** [comment]
The idea is that each world-ship is custom-built according to a somewhat random design, maybe also adding bits to it over time. So I wanted enough variants that they wouldn't all look identical.

**Comment by MessyMix** [comment]
HE'S BACK
