### ISSUE TITLE
Pug government fining on abandoned planet. 

### ISSUE THREAD

**Issue by panda4130** [endless-sky/endless-sky#2204]
When doing the missions where you fight and drive back the pug, it seems that although there are no pug on the planets they still fine you for your illegal cargo, this happened to me upon landing on Shiver.

**Comment by jafdy** [comment]
Some one is there to fine you. The event just hasn't changed the government yet.

**Comment by KiLEdEnNis** [comment]
the punishment of having nerve gas

**Comment by VonZorch** [comment]
Which brings up the point that you should be able to eject illegal outfits from ships you capture.

**Comment by KiLEdEnNis** [comment]
I don't think AI ships carry illegal stuff at the moment

**Comment by VonZorch** [comment]
I ended up with nerve gas after capturing a pirate ship.  Fortunately I was going to a pirate world and was able to sell it before the nosy Republic Navy goons scanned me.

**Comment by KiLEdEnNis** [comment]
that's a plugin, but I do get the point though

**Comment by endless-sky** [comment]
Fixed in a269ac3.
