### ISSUE TITLE
Penalties for missing deadlines, aborting missions and stranding passengers

### ISSUE THREAD

**Issue by Mortecha** [endless-sky/endless-sky#2205]
It would be a nice little game play mechanic where if you fail to deliver goods on time, you would be held accountable as a form of compensation to the affected party. This would give these missions more of a sense of priority and challenge. 

This should also apply to aborting trade and passenger runs as the player is essentially unloading the cargo or people and leaving it/them at the spaceport. This would make the decision to abort missions more strategic.

**Comment by jafdy** [comment]
```on fail
	payment -1000
```

**Comment by MCOfficer** [comment]
i like this. mabye set the penalty depending on how far away it is from the actual destination (only 20% of the reward penalty if it's one jump away, 100% if it's on the other end of the galaxy)?

**Comment by SamKeightley** [comment]
> on fail
> 	payment -1000

I don't think $1000 is a value that has any substantial impact, like priority challenge points etc. The value should also change depending on the reward of the mission, like a certain percentage of it. 

> i like this. mabye set the penalty depending on how far away it is from the actual destination (only 20% of the reward penalty if it's one jump away, 100% if it's on the other end of the galaxy)?

Beat me too it:)

**Comment by jafdy** [comment]
That would be harder @MCOfficer as the game won't detect the difference between you and the destination. Also Jump drive only routes break this anyway.

@SamKeightley A percentage of the mission payment would be possible, you just need to replace my 1000 by the same string but with a different constant.

**Comment by SamKeightley** [comment]
Ok, so this is one way of solving it.

Would there be any resistance from the devs to the idea of having missions currently in the game behave in this way?

**Comment by jafdy** [comment]
MZ (our Dev) is having a much earned brake so we can't ask him. None of the rest of the community have dropped in (and they do know about it) so no ones actively opposed to it.

**Comment by Amazinite** [comment]
>Would there be any resistance from the devs to the idea of having missions currently in the game behave in this way?

I'm pretty sure that this topic has come up before, and the response was that MZ doesn't want you to be punished if you need to abort a job. The punishment is pretty much already the fact that you just don't get cash.

**Comment by Nechochwen-D** [comment]
And frankly regular missions only give flavor to the game. There is almost no one active on here who uses them as their primary source of income.

**Comment by SamKeightley** [comment]
> I'm pretty sure that this topic has come up before, and the response was that MZ doesn't want you to be punished if you need to abort a job. The punishment is pretty much already the fact that you just don't get cash.

It would make for a more immersive and challenging experience. The punishments don't have to be game breaking or overly difficult so fail to see how it would be an issue. 

> And frankly regular missions only give flavor to the game. There is almost no one active on here who uses them as their primary source of income.

If that is the case then I don't see why you would be against the idea. Personally I have been using them as the predominant factor in determining where to go. It gets especially nice when you can chain them together. You then trade normal commodities with any remaining space you have.

**Comment by Nechochwen-D** [comment]
I never meant to imply that I was against it, merely that it is a rather low priority considering that there are other far more lucrative (boarding/capping/looting) sources of income that _need_ to be balanced.

I personally use them in much the same way as you.

**Comment by whismerhill** [comment]
Missions after a while are only a side income, putting penalties on them would only make them cumbersome.
IMHO, if harsher penalties were put in place then missions income would need to be reevaluated.

Also to consider, it's very easy to missclick & accept a job you didn't intend to in the mass of jobs available. Also happened to me to accept a job then notice that its icon is blinking, which means I missed the fact that it was timebased.

Anyway, just my small player opinion on this matter.

**Comment by DingusShingleton** [comment]
Another thing I just thoguht of... If i abandon a transport mission while I'm in space.... did I just shove those poor people out of the airlock? In that situation, I can't help but think that at LEAST there should be a penalty for forcing innocent people to die by the cold vacuum of space.

**Comment by KiLEdEnNis** [comment]
I think they just vanish
you shouldn't be able to abort stuff mid-flight
(take transport mission in Wanderer space, fly to Coalition space, abort)

**Comment by Amazinite** [comment]
If you abort a job mid-flight, you keep the passengers and cargo until you next land.

**Comment by DingusShingleton** [comment]
Edited. But on that note.... a la the pirate missions, like selling passengers into slavery, it would be cool if you *could* space a couple of rich passengers... after pilfering all their valuables of course. Another way to play the dark side, as it were...

**Comment by jafdy** [comment]
I will only add this to rush and escort mission to start with. Of coarse it might just mess the payment up and prove impossible.

**Comment by jafdy** [comment]
It messes up the payment text replacement. That means I have to hard code values in to the description text. This means that only escort missions can be reworked to include this.
[jobs.txt](https://github.com/endless-sky/endless-sky/files/818121/jobs.txt)
This file is set up to be plugin compatible. It will let you test out the effect. The values are set at 20% of the payment.

**Comment by SamKeightley** [comment]
> Missions after a while are only a side income, putting penalties on them would only make them cumbersome.
> IMHO, if harsher penalties were put in place then missions income would need to be reevaluated.
> 
> Also to consider, it's very easy to missclick & accept a job you didn't intend to in the mass of jobs available. Also happened to me to accept a job then notice that its icon is blinking, which means I missed the fact that it was timebased.
> 
> Anyway, just my small player opinion on this matter.

Was thinking about miss clicks and the like upon accepting a job. I think there should be no penalty for aborting a mission on the planet or station that the mission was started on, and only prior to the player leaving the planet. After that point you should face penalties for aborting them. 

As for spacing passengers. Hmm, more harsh penalties for being a murderous space tyrant?? Otherwise a more lenient penalty for aborting the mission on a planet. The same could be said for spacing cargo, since spacing something basically guarantees that it will never be retrieved by the owners, but if it's sitting in a space port it will.

**Comment by jafdy** [comment]
The file I uploaded is all the missions that can be done. Any mission with variable payment and a <payment> text replacement runs into difficulties as it uses the negative payment. 
The game also can't detect where a mission is aborted/failed so any solution that allows aborting before departure would be messy.

**Comment by Lineth** [comment]
Maybe a submission string to open up more lucrative cargo freight missions for a major trade conglomerate? Would make missions more attractive as an income source and give a nod to the occasional comment/implication from merchants that large corporations control all the really good sources of non-pirate not bounty-hunter missions.

**Comment by MessyMix** [comment]
@Lineth: I'm on it. Good idea.

**Comment by lheckemann** [comment]
> As for spacing passengers. Hmm, more harsh penalties for being a murderous space tyrant??

I think stuff like that should carry fairly harsh *reputation* penalties, so you essentially become a wanted criminal (and end up getting attacked by merchant/republic ships) if you murder passengers repeatedly.

**Comment by KiLEdEnNis** [comment]
@lheckemann  I think that was meant as a joke

**Comment by lheckemann** [comment]
@KiLEdEnNis Regardless of whether it was a joke or not, I think it would be a nice addition.

**Comment by KiLEdEnNis** [comment]
the addition that if ya abort a transport mission ya send the people ya transport into space, killing them, and that makes governments hate you? not really tbh
it'd be a funny addition in a way but that's it

**Comment by Bladewood** [comment]
murder is illegal

**Comment by Amazinite** [comment]
>If you abort a job mid-flight, you keep the passengers and cargo until you next land.

This is how it works right now, so are you suggesting we do start throwing our passengers out the airlock?

**Comment by lheckemann** [comment]
Who knows, some players might have a murderous streak. And then loot their passenger's suitcases for valuables.

**Comment by DingusShingleton** [comment]
If I can be sold bold as to quote myself from earlier in the thread:
>But on that note.... a la the pirate missions, like selling passengers into slavery, it would be cool if you could space a couple of rich passengers... after pilfering all their valuables of course. Another way to play the dark side, as it were...

Maybe it's that I recently started watching the expanse, but I think this is a cool addition. Many players don't go for the goody two shoes approach and like I said, the pirate missions add a whole new dimension to player choice in the game. This would just be one more layer, once appropriate repercussions and balances have been established.

**Comment by MessyMix** [comment]
>Maybe it's that I recently started watching the expanse

<3 THE EXPANSE

But @DingusShingleton, I think it would be too complicated for the scope of Endless Sky to space passengers after looting them.

HOWEVER, a solution. For VIP missions into slavery on a pirate world, you get extra moneys.

**Comment by KiLEdEnNis** [comment]
@MessyMix sending passengers so pirate worlds as slaves is one of the thingies that'll be in the pirate jobs

**Comment by MessyMix** [comment]
@KiLEdEnNis I realize that, but I'm just saying. More reward for slavery of VIP missions.

**Comment by lheckemann** [comment]
There could also be missions that are split into two mutually exclusive choices — like the prisoner transport in the FW campaign where you decide where to take them.

**Comment by KiLEdEnNis** [comment]
3rd option: sell the Navy personnel on Greenrock

**Comment by Tadrix** [comment]
−13 karma plus no hope for truce once Republic learns of this

**Comment by KiLEdEnNis** [comment]
mine was a joke, why actually elaborate on it
and -13 karma, ya can get like 5 karma total so

**Comment by endless-sky** [comment]
New game play mechanics generally aren't added just for the sake of realism: there has to be a good argument that it would make the game more fun or more interesting, as well. I don't think that would be the case here.

Also, if a mission failed when the player has zero credits (not unusual if they've got a mortgage and salaries to pay) either their credits would go negative, or the penalty would have to be imposed in the form of a fine, either of which would be a rather messy solution.

**Comment by VonZorch** [comment]
From what I see this can be done by putting an on fail with penalties.
No game mechanics need changed.
Imposing penalties for failure is not a bad idea.

**Comment by KiLEdEnNis** [comment]
maybe make some new tag that when you succeed a lot you get a lot of offers, if you fail a lot of missions you get less offers? doesn't directly give a fail penalty but if ya do it a lot ya get less of those jobs

**Comment by MCOfficer** [comment]
maybe you could use one's reputation for the merchant "government" for this ^

**Comment by KiLEdEnNis** [comment]
that'd mean if you kill a lot of pirates yet you fail a lot you keep getting a lot of jobs
it should rather store some succes rate, then the lowest success rate gives you only like 1/3rd the missions, and it could slowly "regenerate" over time when not doing missions

**Comment by skerit** [comment]
Whenever I click "Abort" I fantasize that somewhere some NPC is getting a little dialog box saying

    Excuse me, Captain. I took on a rush delivery to <planet>, but my ship needs repairs ...

Or something. So should penalties ever be implemented, handing over jobs should be possible (because in-universe, they already kinda are)

**Comment by tehhowch** [comment]
What would that look like to the player? A random chance to lose money several days after they abort the job?

This is a single player game (with no likelihood of becoming a multiplayer environment). So random chance is all that can be used to control the "offer" and "completion" of those "on abort while landed" transfer jobs you propose.


As mentioned previously by MZ, not getting paid for a job that consumes your cargo and bunk space is already a penalty.

**Comment by jjhankins** [comment]
I think he means a class of missions where some other captain comes up to you and wants to hand over a job.

**Comment by tehhowch** [comment]
That already happens

**Comment by skerit** [comment]
@tehhowch I think you misunderstood. The game indeed already offers you jobs other "captains" are unable to do. If penalties do happen, it would make sense if the player could do the same, the other way around. I'm not at all talking about implementing multiplayer or anything.

**Comment by tehhowch** [comment]
@skerit No, that is exactly what I understood you to be talking about.

There is no difference between penalizing the player for aborting a mission (penalizing = removing money), or for giving the job to "some other captain" who will certainly not do the mission without being paid (= removing money from the player). Odds are you wouldn't pay that captain unless they complete the job, and maybe they don't complete it. Thus:
> a random chance to lose money several days after they abort the mission

Adding penalties beyond the current existing penalty of not making money from used space / bunks is not likely.

**Comment by jschiav** [comment]
I think a penalty makes sense precisely because the missions are mostly flavor.

People aren't doing missions as primary income, meaning that the penalty isn't going to typically make much of a difference either. But it does make the immersion just a tad bit more real. I think that's worthwhile.

**Comment by jafdy** [comment]
People do use missions as primary income. Or am I not a person?

**Comment by KiLEdEnNis** [comment]
they generally do
usually players take some freight or transport mission and fill up on commodities to get money, if you punish missions in some way you'd screw over quite a bit of players for little return
I personally do escort & bounty missions, more to capture/plunder, but it's still mission income in a way, but early on I run freight/transport missions as well

**Comment by jschiav** [comment]
Fair enough, my mistake. If the penalty were small enough (like 10%), I think the trade-off might still be worth it; I find it extremely strange that you can accept as many missions as you like and abort just as many with no consequence at all. But that's just me.

**Comment by KiLEdEnNis** [comment]
I don't like the idea of such penalties at all, if someoe wants to cancel a mission they should be able to do so, even if it's a bit unrealistic

**Comment by DingusShingleton** [comment]
Rather than penalizing unreliability, how about the inverse? Reward reliability by giving a bonus for completing consecutive missions. It makes sense, since employers would want to award contracts to captains with good reputations and would be willing to pay extra for such a one.

So, let's say each time you complete a mission, you get a +1% bonus on future missions, up to, say 10%? Then, each time you fail/abandon, it either reduces it by a set number, or resets it completely (depending on how harsh you want to be, I mean, hey, even Han gets boarded sometimes).

You could lower the default payments a bit to split the difference and maintain balance, but this way there would be a modest, but meaningful consequence to playing fast and loose with your employer's time and money while also making a mission-heavy playstyle feel even better, seeing that bonus cash rack up.

Or just leave it the way it is cause that's fine too.

Also, sup y'all

**Comment by gunqqer** [comment]
I like that, instead of "punshing" you nerf everything and give "bonuses." Maybe at a point for failing jobs you start getting less or something simmilar

**Comment by DingusShingleton** [comment]
Well I think the most important design philosophy of this game is always gameplay>realism. The whole point of this topic was to add an element of realism, but the problem was doing so without needlessly hurting gameplay. Adding a new bonus makes the game more fun, and gating that bonus adds the realism. There is really no point to ever punishing the player for abandoning missions. It's not something that people will generally do for no reason. That is to say, they will only do it when they have to. Losing a percent or two of mission income temporarily will sting a tiny bit, but really won't add up to much and it will maintain the realism, *enough*. If anything, this would boost mission income over time. And give mission-primary pilots that little dopamine boost for a long string of missions accomplished.

**Comment by DingusShingleton** [comment]
I'm reminded of the practice of selling something for e.g. $19.99 instead of $20. It's a difference of 0.05%, but its effect on behavior is probably orders of magnitude greater. In this case, the raw numbers wouldn't be all that different, but I could see it having an outsize effect on how people perceive missions. Just a hunch tho, I could be wrong

**Comment by jnawk** [comment]
I came here looking to find out what happens to the cargo if you fail a rush delivery mission, but I guess it just gets unloaded at the next port?  It'd be interesting (or perhaps unfair?) if it ended up in your hold as commodities you could sell.

**Comment by beccabunny** [comment]
This way though you could just accept a job, abort it and gain money by selling the cargo without having done literally anything

**Comment by jnawk** [comment]
Well, I said fail, thinking fail and abort were separate concepts.

**Comment by Mortecha** [comment]
I still think there should be some penalty for both failing and aborting missions. You keep the cargo if you fail to deliver it in time but have to pay damages which exceed the profit margin you get for selling them yourself (Think clients commodity transport insurance policies or something). 

Would be nice if sometime down the road, reputation comes into play limiting certain clients trust in you this offering less rewarding and less frequent jobs for you down the road.

**Comment by Amazinite** [comment]
While as mentioned we won't be adding penalties for failing or aborting jobs, with v0.9.13 it is now possible to differentiate between failing and aborting a job as Pointedstick described, so if you want you can now reasonably create such penalties.
