### ISSUE TITLE
Flagship Display Addition Request

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2210]
Have the ship outline in the flagship display (upper right corner) point the same way it does in the main display.  During a large engagement, especially when around a planet, the flagship on the main display can be completely covered by weapons fire.

**Comment by MessyMix** [comment]
Good idea. It's already implemented in the target display, so it shouldn't be new code.

**Comment by Bladewood** [comment]
Duplicate. https://github.com/endless-sky/endless-sky/issues/1236

**Comment by VonZorch** [comment]
Sorry, I missed that, and I spent several hours looking for similar requests.

**Comment by Bladewood** [comment]
k

**Comment by KiLEdEnNis** [comment]
any reason for reopening?

**Comment by VonZorch** [comment]
Yes, to mention that in a large furball of a battle all the ships near the center of the screen are obscured by weapons fire.  The highlighting and drawing the flagship last can still leave an invisible ship.
Apparently my post immediately after reopening got lost.
