### ISSUE TITLE
Alternate Target Selection Method

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2211]
Select a target by clicking in the radar screen (upper left corner).  It may not be very important but I frequently want to know who that idiot is on the other side of the system.  Referring here to a ship in my fleet.
This would also be useful for missile duels against a distant ship.

**Comment by Tadrix** [comment]
And, while at it, would be nice to be able to select a planet this way as well instead if flying towards it, manually selecting, bribing and praying ship will be able to land before silly pirates will blast it out of the sky (morons are frequently using up their missiles, forfeiting any chance of actually disabling and plundering instead of destroying their target)

**Comment by Bladewood** [comment]
Pretty sure this is a duplicate. When I go home, I'll try to find the Steam thread for it.

**Comment by jafdy** [comment]
#1748

**Comment by Bladewood** [comment]
Damn, he beat me to it.

**Comment by jafdy** [comment]
It was a pain to find the right key words for that one.

**Comment by VonZorch** [comment]
I spent several hours doing broad searches and looking through issues before posting.
It would still be useful when there is a pure missile ship in an enemy fleet.  You could click on it and engage in a missile duel while your escorts deal with closer enemies.
If not then a modifier key such as <ctrl> that would select the next enemy  instead of the nearest enemy.  I'm using ~ to select the nearest enemy so in my case <ctrl>~would cycle through enemy ships.  I know you can use select next ship but if there are many friendly ships that can take too long to be useful.

**Comment by DingusShingleton** [comment]
I knew it had been suggested before but I couldn't find it either.

Anyway I think targeting with the minimap is a bandaid for the targeting system which is not particularly fleshed out. The single use-case of targeting a distant missile boat hardly seems pressing enough to add a whole new method of targeting... I should think that revamping the existing targeting system to be more fluid and feature rich would be time more well spent.

**Comment by jafdy** [comment]
This is an out and out duplicate. Please close.
