### ISSUE TITLE
FW "Prisoner Parole" mission, "F.S. Starry Warrior" becomes "R.N.S. Starry Warrior"

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2212]
[Here](https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20start.txt#L181) and [here](https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20start.txt#L221).

**Comment by KiLEdEnNis** [comment]
lolk
nice find :P

**Comment by MessyMix** [comment]
You have already opened a pull request; you do not need an extra Issue for it.
Please close this issue.
