### ISSUE TITLE
Should Pirates have Nerve Gas?

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2218]
Should a limited number of Pirate ships get Nerve Gas? It would be a great flavor addition for the game, and would make it harder (though still very possible) to board the occasional Pirate ship. Right now, iirc no pirate ship uses Nerve Gas, which kind of defies the point of selling Nerve Gas at all on Pirate planets (if no-one is buying it)...

I can PR this if people agree. What do you guys think?

**Comment by Lineth** [comment]
I don't think pirate ships ever attempt to capture vessels. It would actually make a neat gameplay feature if they did. This would help with that.

I'd personally say go ahead. Mostly for flavor, being as nerve gas is pretty mediocre as a capture defense.

**Comment by Bladewood** [comment]
Isn't nerve gas on par with laser rifles as a defensive weapon?

**Comment by MessyMix** [comment]
@Lineth: Exactly what I had in mind. I don't want Pirate ships to be impossible to capture, but every now and then, pirate ships should have some nerve gas on board (especially the bigger ones). And, as @Bladewood has pointed out, it might make the Security Station a viable outfit.

And also, I don't think every crew member will have them on board. Only a limited amount.

**Comment by Lineth** [comment]
Lowering the security station's weight to one ton (or even a half-ton or quarter-ton if the engine supports it, which I doubt.) would go a long way towards making it worthwhile.

**Comment by Bladewood** [comment]
It does support rational numbers (yes, I've tested it), but we should stick to integers for the sake of gameplay.

**Comment by endless-sky** [comment]
If pirate ships had nerve gas, you could end up being fined without even realizing you had a ship in your fleet with an illegal outfit, just because you were plundering pirates.

**Comment by Bladewood** [comment]
Can we at least give them laser rifles or fragmentation grenades?

**Comment by MessyMix** [comment]
It seems odd that human ships don't have hand-to-hand, especially the ships that you would most expect. I like @Bladewood's suggestion. :D

**Comment by KiLEdEnNis** [comment]
I can make a PR adding some H2H weapons to ships (others can do it too), but I prefer waiting to start doing it until I know if 2271 gets added or denied

**Comment by MessyMix** [comment]
>I can PR this if people agree. What do you guys think?

@KiLEdEnNis, that's enough line buffing from you this month. My turn >:D

**Comment by KiLEdEnNis** [comment]
( ͡°, _ʖ ͡°,)
assuming mine gets merged at all (if it doesn't I bet I'll have to separate the variants.txt & re-do the ammo thing in the PR but have the alphabetical order stuff in a separate PR)

**Comment by Amazinite** [comment]
(Or you could just have done that in the first place; one PR for one feature.)

**Comment by KiLEdEnNis** [comment]
shhh...

**Comment by DingusShingleton** [comment]
Really though @endless-sky, if a player is plundering pirates to make money, isn't it kind on them to realize that... you know... pirates. Illegal stuff. Caveat emptor.

I mean, if the nerve gas were only placed on the biggest pirate capital ships it would mean that the capturing player had a decent net worth, such that one single fine probably wouldn't break their bank, and if anything would be like a "Oh yeah. Duh" moment for them.

But also, it doesn't matter at all.

**Comment by Tadrix** [comment]
How about adding nerve gas to pirate heavy warships, laser rifles and frag. grenades to pirate medium and light warships, and just laser rifles to interceptors?

(In similar vein: How about adding laser rifles and frag. grenades to Rep, Syndicate and FW heavy warships and laser rifles to medium and light warships? So far I've only seen 20 frags on Rep cruisers, which doesn't sound serious.)

**Comment by KiLEdEnNis** [comment]
just gonna throw the idea here
Marauder ships using Nerve Gas

**Comment by Tadrix** [comment]
Nice.

Marauder interceptors would do well with frags and rifles though.
(Rationale: Larger ships are more suitable to board others, they would risk getting caught with illegal items. Not interceptors, though, to whom boarding is more of a side job to warrant such risk; there would be too much nerve gas flying around otherwise.)

**Comment by KiLEdEnNis** [comment]
like 1 nerve gas can do too so doesn't matter
Marauders would board what they can, & regular pirate Sparrows board FW Falcons too

**Comment by Tadrix** [comment]
> Sparrows board FW Falcons too

I doubt it. Plunder — sure. Attempt capture (which is where h2h becomes useful)? No way.

**Comment by MessyMix** [comment]
@KiLEdEnNis about marauder ships, that's what I was tryna hint at it by saying "especially the bigger ones". I think we can play around with fleets.txt to see what we can do with the big pirate and marauder ships. You know, if I'm a pirate and I buy a big shiny Levi to plunder, prolly gonna put some nerve on that, too, amirite? Also, what @Tadrix said seems to support my idea.

**Comment by VonZorch** [comment]
Marauder and Republic Navy ships do carry H2H outfits.
@Tadrix I would reverse the order for ships to carry nerve gas.  It's a bigger boost for small ships than for large ones.  Also looking at it from the perspective of a pirate captain, on a small ship I know my crew and can pretty well trust them to not do something real stupid while with a large pirate crew you certainly have some unstable morons who could very easily wipe out your crew in a snit if you had nerve gas.
I actually did capture a pirate ship with nerve gas once.  It was version 9.4 I think or maybe 8.11, and I was attacking one of the pirate worlds for tribute.

**Comment by Amazinite** [comment]
A single, once used Cruiser variant uses H2H outfits.

**Comment by Bladewood** [comment]
What about the Giftbringer?

**Comment by KiLEdEnNis** [comment]
that's an Alpha Navy ship, not a Republic Navy ship

**Comment by VonZorch** [comment]
@Amazinite  I just did the FW scanning missions, every cruiser had frag grenades and laser rifles.

**Comment by KiLEdEnNis** [comment]
that's the Cruiser (Heavy) variant, it's hardly used at all; most Cruisers are the default scanner ones & later ya get the Mark II's

for starters, I'd say give military ships (or warships in general) some H2H? especially the Navy

**Comment by Amazinite** [comment]
@VonZorch Exactly, thrice used. Two of the times are in scanning missions and the third is when you're liberating Kornephoros or something, but other than those three it's never used.

**Comment by Pointedstick** [comment]
> I don't think pirate ships ever attempt to capture vessels. It would actually make a neat gameplay feature if they did. This would help with that.

https://github.com/endless-sky/endless-sky/issues/4019

**Comment by Amazinite** [comment]
> It seems odd that human ships don't have hand-to-hand, especially the ships that you would most expect. 

Well most ships have H2H weapons now. But as mentioned, nerve gas on a captured pirate ship would be more annoying than anything. The Marauder Fury does have a single nerve gas outfit, though.
