### ISSUE TITLE
Propositions: Changes in crew salaries and maintenance costs

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2219]
**Salaries:** Consider that each ship which isn't piloted by player needs its captain. Now take into account that said captain needs his own Pilot's License (somehow I can't imagine unparked or left behind ships successfully convincing, for example, Navy authorities: "But, but… our employer has a Pilot's License. It's the same for us, right? Oh, (s)he's several systems away by now." Consider also that this license costs 50K. 50000 for ship captain's license, while player pays them 100/d? If this license would need to be refreshed annually, it wouldn't be worth it (a crew member earns 36500/y).
**Suggestion: One crew member per player's escort ship (excluding flagship) earns 200/d.**
**More elaborate version:** interceptor's (or transport's) captain earns 600/d, light warship's, light freighter's and Tarazed Blackbird's captain earns 700/d, medium warship's captain earns 800/d, heavy warship's, heavy freighter's and Star Queen's captain earns 1000/d. If we want to favor traders (because plundering pays better) then we can set (any) freighter captain's salary to 300/d, since his job is to just get cargo from A to B.
The point is, personal Pilot's Licenses should pay themselves off in year's time for pilots employed by the player, otherwise they wouldn't be motivated to obtain said license and join his/her crew (because only way to actually pay off that license would be being an independent merchant).

**Maintenance:** Yes, I'm aware that this has been brought up before, and that M.Z. had unfavorable opinion of it in the past (but absence of which, I may add, made androids so unbalanced they needed to be removed from the game). This is the same way Kor Sestor and Kor Mereti warships are unbalanced. With any luck, capture them and — yay! — no more upkeep.
**Suggestion: Maintenance costs 0,025% ship's total full (undepreciated) value per day.** Not especially hurting new players (should be about 100/d), but will scale nicely with big fleets with fancy outfits (e.g. using Quarg stuff).
**More elaborate version:** Give the player choice to not pay for maintenance. Downside? Greatly accelerated 
depreciation. And if already at bottom, then affected ship starts to malfunction (like it's understaffed), its speed gradually drops, weapons inaccuracy gradually increases, and so on, until repairs are maid (meaning, pay what's unpaid and then some more for neglect). Of course, pirates maintain their ships poorly, so depreciation could even be set to longer time period without hurting balance IMO.

**Comment by MessyMix** [comment]
Too much complication for too little reward. In fact, it will really detract from the simple feel of the game. I mean, the game could also be three-dimensional, hyper-realistic, and have ridiculous graphics, but then at that point the game would be Star Citizen and that wouldn't be cool.

I feel like it would just be such a hassle for any player to manage salaries or upkeep like that. Where would it go? "Hire Crew" tab? "Bank" tab? How can we display it to the player? How can we make it easy to manage? There are too many questions that this addition raises, imo, to make it a viable addition to the game.

**Comment by Tadrix** [comment]
Yeah, I expected criticism.

If source code changes would be insane it probably wouldn't be worth it.
As for other points:

> In fact, it will really detract from the simple feel of the game.

Like depreciation just did? It made the game less of a sandbox for new players and more of a debt-payer's nightmare, like some of us already have in real life. Now player no longer is like "hey, I payed off my debt and have 100K extra, let's sell of this shuttlecraft, I can have a heavy shuttle instead. Nope, now it goes like this:
Do I pay focus on paying off my debt, or rather try to upgrade to better ship while this one isn't depreciated too much?
Is it even worth upgrading, or better to save up and get something a lot more expensive?
Etc.

There's no room for experimentation anymore. Every mistake will cost. This is kind of crap we deal with in real life, it isn't fun, and it doesn't seem a good idea to emulate that in the game which isn't accountant's simulator. Being sandbox was one of ES's strong points, second only to amazing story. In my opinion, of course.

> Where would it go? "Hire Crew" tab? "Bank" tab? How can we display it to the player? How can we make it easy to manage?

Captains: Hire Crew
bunks
captains
required crew
extra crew

Maintenance: Bank
Mortgage (or nothing, or fines, or whatever)
Crew Salaries
Maintenance [on/off] — this last one goes where usually [pay extra] is. If the fleet is neglected, [make repairs] when in spaceport with shipyard or at least outfitter instead. No need to burden player with need to manage every single ship. The fleet is either maintained, or not. Also, parked ships shouldn't invoke maintenance costs (rather it could be a fixed payment for a parking spot — but I'm not saying "should be").

**Comment by jafdy** [comment]
There is a PR that would allow you to turn depreciation off.

This is a duplicate, you said it your self.

**Comment by Tadrix** [comment]
About that… I thought captured ships still were depreciated to a fixed value and it was untweakable. But that's off-topic. Also, chances are, new players don't know about this PR and could be frustrated, while depreciation is mainly for those who are accustomed to the game, so now it all happens the other way around. Perhaps, if game had a selector
Easy (no depreciation)
Normal (slower depreciation to 45%–50%)
Hard (full depreciation)
Hardcore (full depreciation, perma-death)
this would solve everyone's problems with these things. Back when Death Benefits still were in the game, I would suggest same approach:
Easy (DB fixed amount for every casualty, perhaps around 150K)
Normal (DB as I proposed in #2154 )
Hard (DB as they were)
Hardcore (DB as they were, perma-death)

**Comment by jafdy** [comment]
I have already asked for the depreciation change options to be put in the settings menu . . .

**Comment by Tadrix** [comment]
I think I saw your post somewhere, but now I can't find it. Could you point me to it?

**Comment by KiLEdEnNis** [comment]
go to the issues list, remove the option to only search open ones and type "depreciation"

**Comment by Pointedstick** [comment]
A better way to impose these costs would be per-ship fees for landing, fuel, hull repair, shield recharge, etc. But I can't imagine that will be very popular...

**Comment by jafdy** [comment]
@Tadrix It's in #2200 where else would you expect it to be?
@Pointedstick Yeh, that has been noed before. (In the issues about adding maintenance.)

**Comment by Tadrix** [comment]
@Pointedstick Yeah, that would be overkill… although hull repair actually sounds like something that would also somewhat help balance capturing, perhaps at the cost of
[hull's cost] * [hull points repaired] / (3 * [max hull points]
for example.

@jafdy Ah, yes, an issue where funny people regarded my posts as nuisances. Almost forgot.
Then again, to someone who remembers all that's ever been in this rep someone who doesn't probably looks like this. Or someone whose opinion differs. Oh, well. :)

**Comment by endless-sky** [comment]
This really doesn't seem like something that would make the game more fun or interesting. Making repairs and refueling free was a conscious decision. And, I already get enough complaints about mortgages and salaries without adding even more ongoing costs.
