### ISSUE TITLE
0.8.7: Wrong flagship selected after "park all"

### ISSUE THREAD

**Issue by ItsNickBarry** [endless-sky/endless-sky#222]
At the outfitter, I dragged my flagship out of the first slot.  I then left the outfitter, and clicked "park all" on the player info screen.

All ships at my current location are now parked, including the ship which was left in the first slot a the outfitter, the intended replacement flagship.  A ship in a distant system has been selected as my replacement flagship.

I cannot leave the current system because all of my ships are parked.  If I unpark a ship in the current system, I can control it, but it otherwise behaves like an escort ship; I can park it, but I cannot park the distant flagship.  If I unpark any other ships in the current system, they head for the distant flagship.

**Comment by ItsNickBarry** [comment]
This seems to have happened because my flagship at the time was not in the first slot of the player info list.

If the flagship is in the first slot of the player info list, I can reproduce the issue by dragging it to a different position, so that a distant ship takes the first slot.  There seems to be a check to prevent dragging a different ship *into* the first slot, but no check to prevent dragging the flagship *out* of the first slot.

**Comment by endless-sky** [comment]
I think this was fixed by commits 99b3ca8 and 6de5252. If you're not building from source you'll have to wait for the 0.8.8 release to see if it works for you. But in the meantime, you might be able to fix this by dragging a different ship into the first slot in the player info panel.
