### ISSUE TITLE
Player's journal / Captain's log

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2222]
Having played a while and being something of a completionist, it occurred to me that a journal would be very handy for tracking information player's given and missions he's completed (note that it would be something different than missions screen in starmap, which is useful in its own right).

I imagine it as something having 5 tabs:
**Current missions**: Basically same info as active missions on the map, only without map, but arranged in a table: Name, Source, (Requirements,) Waypoints, Destination, and clicking on it, description in the bottom panel, nothing really new here.
**Completed missions**: Only visible and non-repeatable missions which are done listed. (This would be great when loading an old save.) Nice touch would be to list quest strings together as one, than, when selected, in the bottom or side panel show them all together, but it's probably not feasible as missions in data files currently aren't identified as belonging to a string — or maybe we could do it for missions with the same visible name.
**Failed missions**: As in active. Only visible and non-repeatable missions which are failed listed. (Also useful from time to time — and if someone complains that he's not offered a mission, this is a way to check if it's possible at all — just ask the player if something is listed under failed missions.)
**Information**: Here could go stuff from completed invisible missions, for example, "Ulrich told me of his meditation near a cloudy star along the Rim, about fallen civilization. To him it felt real, so There Might Be Riots started to speak against the war." Well, that's a crappy example, but I meant things that the player could read if (s)he took a break from the game, forgot some details and needed to immerse himself/herself in it again.
**Notes**: An empty page. Allow player write in it whatever desired.

**Comment by jafdy** [comment]
#494 This is basically a duplicate. A better thought out duplicate but still a duplicate.

**Comment by DingusShingleton** [comment]
IMO something like this is a must-include for a 1.0 release of this game. The fact that there is basically no record of any information given to the player at any point is a serious roadblock for many new players I think, and not playing even for a couple days can be enough to lose track of the storyline. Lost storyline = frustrated players = so long ES. Just my 2 credits

**Comment by KiLEdEnNis** [comment]
next time type some keywords in the red circled part, if ya see an issue come up, we'd rather have you comment on them than making a duplicate
thanks in advance
![duplicate search](https://cloud.githubusercontent.com/assets/10348657/23587487/8eb45bc4-01ad-11e7-84c9-f6d94724263c.jpg)

**Comment by Tadrix** [comment]
Maybe I'm just bad at searching, but my keywords didn't return anything useful, certainly not "log" or "journal", nor "diary". What did I overlook this time?
