### ISSUE TITLE
37 t of spacecraft hulls

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2224]
![shulls](https://cloud.githubusercontent.com/assets/17566547/23594846/e3e15854-0225-11e7-8cee-96e0a9d49511.png)
Was it one half of Republic combat drone?

**Comment by Amazinite** [comment]
What is the point of this issue?

**Comment by Tadrix** [comment]
Suggestion to change this generic cargo to something more suitable, for example, "spacecraft parts". "Spacecraft hulls" (as well as monolith blocks and other such things) would be good for bulk missions.

Is this possible, or are these missions currently picking cargo descriptions from the same list?

**Comment by Amazinite** [comment]
All cargo jobs select a random cargo from [this list.](https://github.com/endless-sky/endless-sky/blob/master/data/commodities.txt) I don't really see how spacecraft hulls is a problem though.

**Comment by Tadrix** [comment]
Yep, I just checked that all missions specify random cargo.

From gameplay perspective there is no problem. But I laughed when I saw it. We know how heavy spaceships (or their hulls) are, it's their mass. They all are much heavier than 37 t. And, since they are plural, it's really entertaining to think of how they are cramming multiple hulls in the standard cargo hold of, say, Star Barge or Bounder. So it's more like immersion problem.

How about making two lists, second one for bulk missions, move large objects there and maybe even adding some more (or even making exotic list for another type of delivery flavor mission)? A mission to transport a large alien monolith to laboratory in Deep would be refreshing.

**Comment by Amazinite** [comment]
Hull doesn't necessarily mean that you're transporting an entire ship. You could just be transporting the plating or framework of a ship. I really see no reason why this issue should remain open.

**Comment by Tadrix** [comment]
Well, if you put it this way, I see the reason.
When I last checked, hull meant fuselage or the frame or body of a ship, not just some part of it. If these were parts, they would be called bulkheads, plating, etc.

**Comment by MessyMix** [comment]
I can do the second one.

To be honest, though, I don't see the problem with transporting spacecraft hulls. Boxwing is 45; take away the engine casing and strip it down to a bare minimum, you hit the 37. Spacecraft hulls can refer to the plating on the fuselage and body, so I guess that could be any mass, really. I don't see the point of making an issue about this.

**Comment by Tadrix** [comment]
Heh, sounds convincing.

I'm still having opinion that cargo lists would be better if they at least differentiated between large unit size and small unit size, but that's probably something I could look into myself, given enough spare time. So I'm closing this for now.

**Comment by MessyMix** [comment]
@Tadrix I would be all for an immersion fix, but just realize that for small things like this, I doubt MZ will put in time to do it (it's time consuming yet small). I, and I'm sure others and you would, too, prefer that MZ spend his time either creating more content or fixing larger issues. So if you're willing to do this yourself, I'll give it my full support.

**Comment by Amazinite** [comment]
What makes a cargo job bulk isn't what you're carrying, it's the size in tons of what you're carrying, so I don't see why normal and bulk mission types should have different commodities that you transport.

**Comment by KiLEdEnNis** [comment]
> But I laughed when I saw it.

these things make the game fun though
![colonize](https://cloud.githubusercontent.com/assets/10348657/23607353/ed8e0124-0264-11e7-83d0-86170c0c9a7f.jpg)

**Comment by Tadrix** [comment]
@Amazinite Well, somehow if someone says "that many tons of hulls" you'd expect more then one hull. Also, hulls are usually assembled in shipyards as a whole item for structural integrity, so half a hull wouldn't make much sense.

@KiLEdEnNis Exactly, and game shows us how — each ship consists of hull (with shield emitters, but otherwise just empty cargo, crew, outfit, ammunition and engine compartments, and carries with it parameters such as hull, shields, drag, weapon mounts etc.) and outfits, which make it work (to anthropomorphize — like your skin and your internal organs). So we have a reasonably good idea how much a hull weights.

That being said, I admit that I royally screwed up this time. By mistake I was looking at ship mass, not at hull mass.
Lightest hulls of human ships:
Surveillance Drone — 15 t
Barb, Dagger, Combat Drone — 20 t
Lance — 30 t
Flivver, Finch — 40 t
Boxwing — 45 t
Sparrow — 50 t
Wasp — 60 t
So one surveillance drone hull and one 20 t hull would have fitted perfectly.
Seems that Flivver has the potential to be fighter. Its stats are pretty good for that role.
And probably Wasp also has the potential to be converted, just like Tarazed did this to Sparrow.

**Comment by KiLEdEnNis** [comment]
again; compare it to body kits of cars, it might just be the exterior parts

**Comment by MessyMix** [comment]
@KiLEdEnNis I wouldn't call decoration / external parts a "hull", but regardless I think that this discussion has gone on way too long over a closed issue. It's fine the way it is.
