### ISSUE TITLE
Wanted: an inexpensive, maneuverable, flexible ship that can be customized in any direction

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#223]
Endless Sky has *great* ships overall. However, I frequently find myself wishing for a ship type that seems to be missing: something like EVN's Starbridge or Valkyrie, EVO's Arada, or EV: The Frozen Heart's Wanderer. Basically a ship that's fast, maneuverable, and somewhat but not extremely expandable in any direction, and not so expensive that by the time you get the money for it, you already have better options.

A number of ships are close to what I'm looking for, but none of them quite fit the bill.

The Blackbird has too few weapon hardpoints and is a bit too expensive. The Clipper is too slow, has no turret hardpoints, and its shields are too weak. The Raven has no turret hardpoints and its cargo space is too small. The Corvette is too expensive to buy and crew and its cargo space is too small. The Mule is too slow, too expensive, and too ugly (there, I said it!).

Something that was sort of a combination of all of these ships would exactly what I'm looking for. The Blackbird is the closest and with a couple of gun hardpoints it would be just perfect…

**Comment by endless-sky** [comment]
Here's a new ship model I've been playing around with. I added a ship definition that gives it enough capacity to sport a pair of particle cannons, like a Quicksilver, or to have a turreted weapon, but not both at the same time. With atomic engines it's quite speedy, and at 2M credits it would work well as an early ship upgrade. Thoughts?

![headhunter](https://cloud.githubusercontent.com/assets/11450262/11319980/05220238-9059-11e5-8f4e-b41c8cc510f1.png)

https://drive.google.com/file/d/0B9aK8dG39P29MXNDUm4zSDMxYUk/view?usp=sharing

**Comment by Pointedstick** [comment]
Yeah, that's pretty close. Seems a bit like a lighter, more maneuverable civilian version of the Gunboat. I'd prefer 10 more tons of weapon space or an additional gun hardpoint, but that could work.

**Comment by gchapyzh** [comment]
Yes, I like that. Maybe a way to turn weapon space into cargo?

**Comment by Pointedstick** [comment]
Your new Modified Argosy ship also fits the bill, especially with some fatty Atomic engines. I'm gonna call this completed and close it out. Thanks!

**Comment by Pointedstick** [comment]
I really, really, like the Headhunter. Armed with a pair of Proton Cannons, it's super fun to play with.

**Comment by gchapyzh** [comment]
I am guilty of creating a fleet of gunboats from Headhunters: A plasma turret and atomic engines = best gunboat out there.
