### ISSUE TITLE
Endless Sky crashes if audio drivers are not working

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2231]
A long time ago, I had this problem. https://github.com/endless-sky/endless-sky/issues/1923#issuecomment-269578733
The problem was that my speakers weren't plugged in, meaning I had no sound systems that the game could connect to. And so the game crashed every time I loaded a save.
Unfortunately, the post faded into obscurity.

And now, the problem seems to have risen from the shadows, attacking an innocent user, the one who opened https://github.com/endless-sky/endless-sky/issues/2228. Apparently, he cannot fix the issue himself, as his operating system and his applications are being assholes.

It seems too close (imo) to be a coincidence.
And in the second case, because he cannot repair the problem, he is stuck with previous builds.
We must resolve this issue.

**Comment by kikotheexile** [comment]
This issue *may* also be related, but i cannot confirm on that front and have not yet made an issue for this. 

http://steamcommunity.com/app/404410/discussions/1/135510669591459683/

**Comment by jafdy** [comment]
I have had a sound related crash before. I just turn my computer off and on again when it happens.

**Comment by Tadrix** [comment]
Hmm… could be related: Sometimes (rather often) when my computer (running w7) goes to sleep with Endless Sky open, upon waking up sound that comes out is jittery (not only ES). I was fixing it by stopping audio services and restarting them.

**Comment by MessyMix** [comment]
Does this happen when ES is not running?

**Comment by Tadrix** [comment]
Usually no. Was happening a long time ago with another game, but I managed to fix the problem by reinstalling video and sound drivers.

**Comment by Wrzlprnft** [comment]
this sounds like our sound system needs a few nullpointerchecks or so.
when you open your laptop,could it be that ES comes faster to life than your sound services? hnmm

**Comment by Tadrix** [comment]
I'm using a desktop computer, not a laptop. No idea what gets awakened by windows first. Should be services, but I wouldn't be surprised by anything.

**Comment by whismerhill** [comment]
ok so
I wanted to dig in a bit this issue:
so first try I launched MusicBee, changed from directsound to WASAPI (which renders everything else silent, since WASAPI doesn't handle multiple inputs (at least in this implementation), unlike directsound), 
then started a song, & launched endless sky, sure enough heard no sound coming from endless sky (official 0.9.6) still it didn't crash and I even launched my game without issues.

next test incoming

**Comment by whismerhill** [comment]
next test : I disabled both audio drivers directly from device management (because there's nvidia audio which I don't use, + the real sound card)
started endless sky and , it crashed at the end of starting up

**Comment by Zireael07** [comment]
I have several audio "devices" on my system and probably the fact that I have a real sound card plus some audio/driver magic thingys protected me from the crash (real sound card disabled but the others enabled).

However the game should show an error message instead of crashing outright.

**Comment by whismerhill** [comment]
@Zireael07 
actually it should just run, if it were to behave like other games, where no sound doesn't prevent them from running just fine.

it would be a step in the right direction toward the robustness of Endless Sky, IF MZ is interested by that.

**Comment by Bladewood** [comment]
@whismerhill I agree with the just running part.

Changed the title. Better?

What do you mean? http://imgur.com/a/9utrs

**Comment by whismerhill** [comment]
yeah I think title is better :) at least in my humble opinion. 
and well I was wondering, cause USB speakers include the audio driver (since they are connected in USB and not a sound card) so if there is no sound cards and it's only USB speakers, then if they are disconnected there is basically no audio driver, which would explain the behavior.

As it is, it seems like an optical or mini-jack to me, maybe the audio driver kinda "disables himself" when no output is connected.

Nevermind. ^^

**Comment by comnom** [comment]
If Audio::Init() returns with a null device, the music threads never get created. This causes issues in Audio::Step(), Engine::EnterSystem(), and PlayerInfo::Land(). Adding a null check to Audio::PlayMusic() prevents the crash, but I'm not sure that's the best way to fix it.

**Comment by MCOfficer** [comment]
it depends a bit on the style guide, but something like
`
    if (!foo) {
        printf("Error");
        return;
    }`
should do. though i'm not that familiar with c++, so i'll leave that to the experts.

**Comment by endless-sky** [comment]
78af4e6 should fix this.

**Comment by Bladewood** [comment]
yay, it works
