### ISSUE TITLE
illegal drugs are profitable even if you get scanned and fined

### ISSUE THREAD

**Issue by whaleberg** [endless-sky/endless-sky#2232]
I was scanned while carrying illegal drugs and fined 40k.  However, the drugs weren't confiscated and ended up being worth 100k+ when delivered.  

It seems weird that:

1.  the fine was so much less than the mission reward 
2.  my illegal cargo wasn't confiscated.
3.  I could still complete the mission succesfully.  

I'm playing version 0.9.6.

**Comment by Pointedstick** [comment]
Strongly agree.

**Comment by Tadrix** [comment]
To conficsate they would need to disable offending ship and remove the cargo. Until then they have no hard evidence (remember FW intro mission with unmarked surgical equipment?).

Perhaps to make things interesting, they could hail player and demand him to stop, or just turn hostile until the player jumps out. Maybe some ships could even pursue the player across multiple systems.

It wouldn't be worth it if mission just failed upon scan, since Republic deploys surveillance drones and it's sufficiently hard to avoid a scan when systems are oversaturated with them.

**Comment by Bladewood** [comment]
I thought I heard players talking about having the choices of

1. Getting fined and dropping your illegal cargo; the scanning ship moves on with its life.

2. Getting fined and not dropping your cargo, forcing the scanning ship to pursue and attack you.

**Comment by Amazinite** [comment]
One problem that I see right now is that the payment is able to vary depending on the size and distance, but fines are always a set amount, so in some cases the fine may be larger than the payment and others it could be lower on the same mission.

Although, I kind of get why someone would pay you more for the drugs than you get fined for them: if you're gaining profit running drugs then you might just keep doing it for whoever you're doing it for. 

On the topic of not getting scanned, I did a post on this on a related issue a while back. You want at least 2 interference plating, a Scram Drive, enough fuel to do the mission in one trip, and powerful steering.

**Comment by KiLEdEnNis** [comment]
still, a fine lowers the profit
if a fine becomes a % of the mission reward it'd seem weird: they don't know the reward
making it scale on amount mass seems very logical: like get fined (example) 5k per ton
if you 1 ton or 100 tons of drugs, the 2nd gets you in a lot more trouble

**Comment by Tadrix** [comment]
Right now these missions have fines which are at or over 50% of reward. One mission with 40K fine and 80K reward, one mission with 50K fine and 100K payment, one mission with 70K fine and 120K reward. Seems to me that was intended like this.

**Comment by KiLEdEnNis** [comment]
but it SHOULD depend on amount of cargo: both the payment and the fine

**Comment by Tadrix** [comment]
Just to nitpick: Drugs probably aren't the same substance every time, so their worth per ton can be variable too. Then less more valuable cargo or more cargo of the cheap variety will net the same. Besides, it's possible player gets payed per delivery, not per amount delivered. What concerns me more is that there's no way to know how many tons of cargo it will be this time until after player has accepted the job.

**Comment by KiLEdEnNis** [comment]
they're drugs in your cargo, unless you sneakily sniff some, I doubt you're gonna know what it is, which is why I left it out

**Comment by gunqqer** [comment]
You hear noises in your hold. You go to check on it. There is a republic officer testing your drugs. On himself. 

"Hmm... I feel a bit dizzy from this one. Must be the new synth stuff"

**Comment by KiLEdEnNis** [comment]
@MessyMix ya should actually made @gunqqer his idea for a flavor mission
now back on topic

**Comment by MessyMix** [comment]
@KiLEdEnNis hmmm. will do ;)
