### ISSUE TITLE
Pirate Raiders in system Deneb

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#2242]
self - explanatory, BEFORE there is any "lane" access to it.

**Comment by Wrzlprnft** [comment]
so before you should be there?

i'd bet those are tricks by the pug!

**Comment by MessyMix** [comment]
To be fair, you can legitimately reach Deneb before the end of the FW campaign, so you can't really say the player _shouldn't_ be there, only that it is _unlikely_ that a first-timer would know to acquire JDrives and reach Deneb, and Pirates aren't supposed to be there. I'd say it qualifies as a bug...

**Comment by KiLEdEnNis** [comment]
wasn't there an idea to give the Pug a message for if the player lands before the events?
but if ya warp in & a Pug fleet warps & ya make the right Jump ya can see them in human space
anyway @MessyMix wouldn't you say it's a pug, not a bug? (sorry)

**Comment by Amazinite** [comment]
I'm pretty sure pirate raiders don't trigger on Pug planets, so they must be triggering while you're in human space but spawning in nearby systems without hyperlinks.

**Comment by Lineth** [comment]
@KiLEdEnNis Yeah, I was the one to bring it up. I noticed the Pug worlds were restricted when warping in before the campaign event, but I don't know if that was changed after I brought it up or if it was always like that.

**Comment by Amazinite** [comment]
Try getting this to occur by landing on a planet like Shangri-la and then jumping into Korath space to see if there are any pirate raiders.

**Comment by whismerhill** [comment]
well actually my very first run I had a few shield beetles, was hanging around syndicate & its pirates, and I got agressed by a korath raider.
I was like : 
haaaaaaaaaaa nooooo something strange, it must be power...
ful ?
or not ? (got disabled by my fleet of shield beetles with their power drainage weapons)
and then I boarded it & stole some of its outfits... that's how I got my first jump drive without any spoilers whatsoever

**Comment by Lineth** [comment]
That's pretty much what happened to me, except I was spamming plasmas instead. Korath and heat damage don't mix.

**Comment by MCOfficer** [comment]
thing is: if you have too much time and don't stumble into the FW missions by accident, you might end up farming in the pirate systems near the korath space. and as soons as you plunder your first raider, you will probably explore the galaxy first and then look for the FW missions.
long story short: i got my jump drive way before the FW campaign, too, it's more than possible. so it's not that unlikely that players will come to deneb before the should do so.

**Comment by KiLEdEnNis** [comment]
@whismerhill you did have a fleet of shield beetles before the FW story gave ya a Jump Drive
considering the FW campaign is designed for a ship like an Argosy, Osprey, Falcon etc.
so kinda your "fault"

**Comment by MessyMix** [comment]
@KiLEdEnNis I wouldn't blame @whismerhill. It's not like it's his fault that he is better than what the game is expecting.

**Comment by whismerhill** [comment]
@KiLEdEnNis 
hahaha well I explored, and found the wormhole before I found the FW storyline ^^ (in my first playthrough)

anyway not complaining, I was just pointing out how stuff can happen. ^^

**Comment by DingusShingleton** [comment]
The fact that there is only one major story line in one corner of the galaxy is a major cause of this effect. If a new player happens to avoid the free worlds, there is no other story line that will grab them before they go off gallivanting through the wormhole etc. I would wager that once more of the galaxy is covered by storylines, that will be a much rarer occurrence.

**Comment by KiLEdEnNis** [comment]
we have human story & 2/3rd Wanderer, w/ Republic, Syndicate etc. WIP, so in some time that'll be fixed

**Comment by jafdy** [comment]
Good job we are not at 1.0.0 yet.

**Comment by tehhowch** [comment]
@whismerhill you wouldn't happen to have had any plugins installed when you observed this, would you?

My guess is one of them updated some system fleet definitions assuming you had already completed FW storyline.
I say this because mission instantiation specifically does not consider systems that require wormhole travel or jump travel to reach, and no pirate variants have a Jump Drive with which to follow you / flee and reach Deneb.
