### ISSUE TITLE
Finisher Torpedo will not fire unless equipped upon buy or installed from other ship.

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#2243]
Changing firing key does not work.
Only work if already equipped to ship or installed from other ship that they were already equipped. 
On 0.9.6

**Comment by Bladewood** [comment]
Show an example of it not working?

**Comment by Amazinite** [comment]
>Only work if already equipped to ship

So the weapons only fire if they're equipped? Sounds normal to me.

**Comment by KiLEdEnNis** [comment]
if it's not working and it should, check if you plugged it in

**Comment by toilethinges** [comment]
And if it is plugged in, unplug it and wait ten seconds before plugging it back in.

**Comment by endless-sky** [comment]
I can't reproduce this. Is it possible you bought a Typhoon storage tube instead of a Typhoon launcher? Or that you don't have any batteries and your instantaneous energy production is not enough to fire them?

**Comment by KiLEdEnNis** [comment]
either I'm confused or you meant Finisher Pod instead of Typhoon Launcher?
