### ISSUE TITLE
Blocked from mission while satisfying requirements

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2247]
![blocked](https://cloud.githubusercontent.com/assets/17566547/23827447/4feb190a-06bc-11e7-8dd3-7c266620975a.png)

Possibly related: #2227 
[Red Six.txt](https://github.com/endless-sky/endless-sky/files/836178/Red.Six.txt)
No plugins.

**Comment by jafdy** [comment]
Almost certainly related. Please close this.

**Comment by MessyMix** [comment]
@Tadrix I think @jafdy is trying to say, post it in #2227 and don't open a new issue for it.

**Comment by Tadrix** [comment]
@MessyMix Thanks, will do.
