### ISSUE TITLE
Error with mass-selling ships

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2249]
![dc1f79aa65ac4b66b54631792d391831](https://cloud.githubusercontent.com/assets/17688683/23828812/a7ffa536-06ab-11e7-8ce0-a343c4314449.png)

When mass-selling ships, longer names end up pushing the dialog box off the screen.

**Comment by tehhowch** [comment]
Some possible fixes (in no particular order)
1) Avoid printing newline between ships being sold
2) Increase Dialog's WIDTH from 250
3) Allow Dialog to have a dynamic width (or at least a constructor method for list displays like the one pictured, in which the dialog width is keyed to the longest list element, and the list is left-aligned
4) Limit the length of ship names
5) Truncate list elements after a length (e.g. replace the last N characters with "...")

Of these I think 2) is the simplest but 3) is the "best" / a close relative of the "best" solution, and I don't like 4) but it has its merits. 5) Is a little trickier than 2), but better than 4)
Option 1) is similarly as simple as 2), but removes some of the clarity conveyed by placing list elements on their own line.

**Comment by jafdy** [comment]
2. won't fix it really, you just need an even longer name. Same with 1. to some degree.

**Comment by Amazinite** [comment]
This has pretty much already been fixed because of how you won't have ships named `<pilot name> <ship model> <number>` anymore, which could cause some pretty long ship names (and I shrunk the name of the ship that caused this), but I would think that 3 would be the best option in the long run.

**Comment by tehhowch** [comment]
If you create a default name that fills the visible positions in the "Enter Ship Name" pop-up, and buy many of that, selling them will recreate this. It is admittedly harder to encounter naturally, but still readily reproducible.

**Comment by Amazinite** [comment]
Yeah, that's why I said "pretty much," but not exactly fixed. Not many people are going to be naming their ship something super long.

**Comment by tehhowch** [comment]
Truncating a string is already supported (Font::Truncate & Font::TruncateFront)... which would be preferred for long ship names? Truncating the front or the end of the string? For mass-bought ships with just a number differentiating, I think the ending is more important, but "in general", I think the front of the string is most important.
I could write a Font::TruncateMiddle to clip on the inside...

**Comment by Amazinite** [comment]
@Amazinite added this to the 0.9.7 (done) milestone
