### ISSUE TITLE
Rectangular selection offset after changing to a different window

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2250]
To reproduce:

1. Be in space.
2. Switch to another window without using the mouse (e.g. alt-tab)
3. Move the mouse to a different position.
4. Switch back to ES.
5. Start a click-and-drag selection (without moving the mouse before clicking); its position will be at the old position of the mouse rather than the new one.

**Comment by KiLEdEnNis** [comment]
not sure what to say to this, it's not really a bug (in my opinion at least) as it's caused by alt tabbing away from the game, and I don't really know if it can be fixed

**Comment by lheckemann** [comment]
I don't see how it's not a bug — surely that's not the behaviour you'd expect? It certainly is an edge case, but it's a bug nonetheless.

It should probably be fixable by using the position reported in the MouseButtonEvent fired when the mouse button is first pressed down rather than (what I presume is currently the case) keeping track of the cursor position on MouseMotionEvents. If not, I guess it's an SDL bug.

**Comment by KiLEdEnNis** [comment]
the game wouldn't expect you to click for dragging, alt tab, move the mouse and alt tab back either; why would one do that? and if ya did, just redrag, so I doubt it'll get a fix, if even possible

**Comment by Wrzlprnft** [comment]
it is a bug.

**Comment by lheckemann** [comment]
>the game wouldn't expect you

Bugs aren't about what the software (game) expects, they're about what the user (player) expects.

**Comment by zwparchman** [comment]
What OS? This is not reproducible under linux.

**Comment by lheckemann** [comment]
NixOS (linux), with i3wm. Might depend on that...

**Comment by zwparchman** [comment]
Ubuntu with xfce here. Maybe you should  try another window manager temporarily.

I have sdl2 version 2.0.4. What do you have?

**Comment by lheckemann** [comment]
SDL 2.0.5; can reproduce in enlightenment and xfce as well as i3.

**Comment by lheckemann** [comment]
This also occurs if you start dragging inside the window, go out of the window, and come back into it at a different position.

**Comment by zwparchman** [comment]
This bug is not reproducible with SDL2.0.4, but is with SDL2.0.5. I'm still investigating.

**Comment by zwparchman** [comment]
When a mouse motion event comes in from SDL it contains the relative x and y motion. In SDL2.0.4 this has a large magnitude reflecting the distance the mouse has moved since the last motion event. In SDL2.0.5 it will have a small magnitude, likely reflecting the mouse motion since the mouse has entered the screen and the event loop was called. 

This is a known bug in SDL2 https://bugzilla.libsdl.org/show_bug.cgi?id=2728. The patch there does not work for me.

Given it's negligible gameplay effects I suggest ignoring it when/if  it is fixed.

**Comment by lheckemann** [comment]
It's also ancient, wow. Good job finding it though! I guess this can be closed as "not a bug in ES".
