### ISSUE TITLE
Zooming out too much?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2252]
Problem is, if player zooms out as far as game would allow, [this effect](https://github.com/endless-sky/endless-sky/wiki/TiledAsteroids) becomes apparent on the opposite edges of the screen. Either tiles should be larger, or the game shouldn't allow to zoom the view so far as for view-port's max. dimension to exceed 4096 pixels worth of "playground".

![zoom](https://cloud.githubusercontent.com/assets/17566547/23831698/74bd266a-072f-11e7-8e86-23715701e6d8.png)

**Comment by MessyMix** [comment]
Good issue, good catch.

**Comment by Bladewood** [comment]
It took me a while to figure out that you were talking about the looping asteroid tiles, not the red lines, which you intentionally added.

**Comment by KiLEdEnNis** [comment]
before I even clicked "this effect" I already knew what he was talking about
anyway I'm not sure if expanding that field would be easy (& I noticed this thing a while ago, didn't bother), so not sure if it's worth fixing

**Comment by Wrzlprnft** [comment]
Kile, please keep “no opinion“ opinions away from github ;)

i'd say this has to be fixed.

**Comment by endless-sky** [comment]
Given that asteroids are always in motion, it's actually pretty hard to spot the tiling unless you're looking at a static screenshot. (That is, in the time it takes to glance from one side of the screen to the other, they've changed positions slightly.)

Increasing the tile size would mean increasing the number of asteroids that must be tracked, which doesn't seem worth it for a minor cosmetic issue.

**Comment by Tadrix** [comment]
I first spotted them in motion, so it isn't pretty hard… and I'm usually absent-minded and tend to not pay attention to details.

How about restricting maximum zoom-out to longest side = side of one tile?

**Comment by endless-sky** [comment]
Telling the player that they aren't allowed to zoom all the way out just because they have a large monitor would be far more annoying than having the tiling be visible in some situations.

**Comment by Tadrix** [comment]
Why should game tell them anything? Adjust scale's maximum as needed. It's only fair if maximum zoom-out provides the same view for everyone. Besides, once one sees this, it's hard to un-see it

**Comment by KiLEdEnNis** [comment]
adjust zooming, so taking away the outzoomed option for everyone so a small part of the player base that has the monitors AND that zoom out all the way don't see the tile?
just, no, stop

**Comment by Wrzlprnft** [comment]
actually, the game could fetch the maximum screen resolution, combine that with the outzoomed view, and if the overlap is like a third of the screen, switch to a larger tile mode. so we would have normal and large mode.

though, someone would need to implement that, and if MZ doesn't feel the need, i'd say we file this as Quality of life thing, until someone does it.

**Comment by Tadrix** [comment]
@KiLEdEnNis Nah, once again you missed the point, which isn't especially strange taking into account your posts confuse others too. And I'm tired to read your attempts to bicker with me. I meant something contrary to what you just described.

Take player's monitor's largest dimension. Allow the player to zoom out until this largest dimension equals 4096 px of playground. If it is 1600, then zoom out to ×2,56 (4096/1600), if it is 1920, then zoom out to approx. ×2,1. if it is 2560, then zoom out to ×1,6. In the end, they all will see the same part of the playground. If this game had a multiplayer option, I'd even say that this restriction is needed for balance as to avoid giving advantage to players with larger monitors.

@Wrzlprnft @endless-sky Is there a way to make this asteroid tile change its dimensions depending on screen size? Presumably people who have larger resolution also have better hardware to deal with it.

**Comment by Wrzlprnft** [comment]
i assume it's hardcoded. maybe we can find someone placing those values in the preferences text file, so if people encounter the problem, they can change it.

**Comment by KiLEdEnNis** [comment]
> Adjust scale's maximum as needed.

like, at least explain what you mean then

> And I'm tired to read your attempts to bicker with me.

lolk, I'd argue but nah

**Comment by Tadrix** [comment]
No real need.

Explanation: No need to show in settings view zoom factors which cannot be supported (with all the restrictions). If there's no such option, no need to warn about anything. Just show them max. factor which can be supported, even if it is something as unusual as 160, for example, instead of 200.

**Comment by KiLEdEnNis** [comment]
the only clean way to me would be to enlarge the field a bit though, it's not really a big issue, and no issue at all to most people, so making the largest zoom factor smaller has a bigger drawback than what he have now
and I remember MZ picked zoom factors like 70% &... 140%? on purpose
70% is 0,7, 0,7^2 = about 0,5x (so half the size, 50% gives 0,25x), 140% is 1,4 = about x2 & 2 gives the x4 size (if ya don't follow tell me)
if we change 200% to 160% we get a sloppy x2,5, and a x3 doesn't seem much better either, but that ain't my terrain, ask MZ

**Comment by jafdy** [comment]
The zoom factors are based around root2. 1.4 is roughly 2^1/2, .7 is roughly 2^-1/2 exta.

**Comment by Tadrix** [comment]
Understood.

What I proposed was make last (maximum) zoom factor variable, either 200, or
100 * sqrt(4096 (side of the tile) / [display resolution's largest dimension])
whichever is smaller, and hide all that are larger than this. Then it will give player the option to zoom out precisely to the point where largest dimension equals length of side of the tile.

And yes, I know it will somewhat limit zooming out, but it, first, makes maximum visible space somewhat consistent across screens, second, hides peculiarity of tiled asteroids, and third, would continue to work nicely if asteroid tile's dimensions got increased (which would deal with this problem in its own way).

**Comment by jafdy** [comment]
What about leaving things "as is" and letting people who find the tiling disturbing just don't zoom out that far.

**Comment by Tadrix** [comment]
Would work too if there was a possibility to set a custom zoom factor. For me, for example, to avoid this, it would be 178. I'm stuck using 140 or 200 right now. How about not hiding larger factors (to allow people use them if they really want), but to make available variable "best for this resolution" setting? People (myself included) could use that on all devices, and would get a consistent experience across all of them.

**Comment by KiLEdEnNis** [comment]
just got an idea, idk how hard it is
instead of enlarging the tiles, look at it like this:
say all tiles face upwards, but what if we made every 2x2 tile be rotated:
![tiles](https://cloud.githubusercontent.com/assets/10348657/24210486/941477b4-0f29-11e7-995f-579a610e4225.jpg)
personally I'm with jafdy: not worth changing, but this seems to be the easiest "proper" fix

**Comment by Tadrix** [comment]
"Crosshair" area would look really weird. Try it out for yourself.

**Comment by KiLEdEnNis** [comment]
ye now I think of it, you could see the same asteroid 4x next to each other

**Comment by KiLEdEnNis** [comment]
if it's:
1 2
2 1
tiled instead? the top-down doesn't seem an issue, and this could do

**Comment by endless-sky** [comment]
If someone had a 4K monitor, avoiding tiling would require quadrupling the tile size, meaning 16 times more asteroids would need to be tracked. And when monitors with even larger resolutions come out, it would have to be expanded even further. It doesn't seem worth the performance hit just for the sake of a cosmetic improvement.

**Comment by KiLEdEnNis** [comment]
future 64K monitors would require this to be fixed though... :3
