### ISSUE TITLE
feature request: all-in-one docking assistance

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2255]
I find that if I am disabled, but also out of fuel, I have to first ask an NPC to repair my ship, and then ask again to get fuel. This seems a bit redundant. Could NPCs be programmed to take care of both needs at once?

**Comment by KiLEdEnNis** [comment]
1 thing to note
if the AI ship doesn't have enough fuel, it should mention it needs to keep its fuel but it will repair the ship
something like "We'll patch your ship up, but if we give you fuel we can't make it to the next system."

**Comment by endless-sky** [comment]
NPCs already ought to volunteer to do both if they're able. What's probably happening is that the first ship you hailed happened to not have enough fuel available, so all they did was patch you up.
