### ISSUE TITLE
full launchers' mass exceeding outfit space

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2257]
I was editing variants to give them the ammo storages, and found it weird that the Tracker storage was over half the size of the launcher & stores half the trackers:
I noticed the Hai Tracker Pod has 19 outfit space and 14 mass, fully loaded with 56 .3 mass trackers it has 31.8 mass and 19 outfit space

to fix this in a decent way, we'd have to reduce the tracker mass from .3 to .2 and the pod mass from 15 to 7.8 (EDITED SIDE NOTE: the tracker storage would need more mass if the trackers become lighter)
and I made the title like that because other launchers have this:
- the Korath Piercer Launcher has 1 extra piercer, so the launcher needs .3 less mass; from 18 to 17.7
- the Korath Minelayer, the 17 .7 mass mines are 11.9, the launcher's size is 48, the mass 36, +.1 mass to the minelayer rounds that up too

I think that's all, if it's worth changing I can do it later today

**Comment by Amazinite** [comment]
One word: Aliens.

**Comment by KiLEdEnNis** [comment]
explain the Finisher Torpedoes, Thunderhead Launchers and Railgun then

**Comment by Amazinite** [comment]
Some aliens like their outfit space to equal their mass.

**Comment by Amazinite** [comment]
Talk to Local about the railgun.

**Comment by KiLEdEnNis** [comment]
it's weird how the tracker pod is way off while the Hai are very similar to the humans, and the Wanderers/Heliarch do have theirs right, and the Korath being .1 or .3 off shows it was rounded down me (those 2 were side issues, the tracker pod is the main issue)

**Comment by endless-sky** [comment]
That's probably a typo or math error from back when I adjusted the projectile masses. I re-adjusted the masses in commit e747e45.

**Comment by KiLEdEnNis** [comment]
so if the ~.3 etc. mass differences are gonna stay, this issue's main thing got solved & it's fixed
closing
