### ISSUE TITLE
Depreciation on New Equipment

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2258]
I just upgraded from a Star Barge to a Freighter.  Both ships have a D14-RN shield generator.  My new ship has a sells for 37%.
Is this a bug?  Or are outfits common to both old and new ships removed from the old and installed in the new, if so does that reduce the price of the new ship?

**Comment by VonZorch** [comment]
Either way there is a real problem.
I went back to an older save, bought my new ship, upgraded the Freighter's shield generator, then went back and sold the Star Barge for about 60,000Cr more than I got when I sold it first.

**Comment by jafdy** [comment]
It's intended behavior. You will always sell the newest outfit.

**Comment by DingusShingleton** [comment]
Either way you are selling both D14-RNs and getting the same total amount for both... I'm not the hugest fan of the game doing these behind the scenes swaps, but in this case I don't understand the sequence of events. 

> upgraded the Freighter's shield generator, then went back and sold the Star Barge for about 60,000Cr more

So you bought the freighter, bought a new genny for it, and sold the D14? That would sell the newest one (freshly purchased from the stock freighter) and leave the old one you already had on your star barge untouched, thus not increasing the value of said star barge. I must be missing something.

**Comment by VonZorch** [comment]
I was wrong on the amount of price change.  
To clarify the situation I 
A. landed on Luna, sold goods and got a loan then
went to the shipyard, sold Star Barge for @154K
bought new Freighter
went to outfitter to upgrade new Freighter, found it had the old D14-RN installed.

loaded the previous 1 save then
B. landed on Luna, sold goods and got a loan then
went to outfitter, sold old cargo expansion and hyperdrive from Star Barge
went to shipyard, bought a new Freighter
went to outfitter, sold new D14-RN, bought a D23, sold scramdrive and bought the used hyperdrive
then installed the used cargo expansion and a bunk room
went to ship yard , sold the Star Barge for @177K.

Something is clearly wrong here.

**Comment by Amazinite** [comment]
It's selling the most valuable stuff first and retaining the most depreciated stuff. The reason your new Freighter had the old D14-RN was because the old one was still in the outfitter and therefore was transfered to your ship. You actually got a discount on the Freighter because of that.

This is all intended behavior. There are no credits being lost or generated out of thin air. Your networth before and after all these transactions should be remaining the same.

**Comment by KiLEdEnNis** [comment]
basically if ya have all outfits from a heavy warship & all are worth 25%, the heavy warship's outfits only are 25%
it's quite useful; ya get small discounts if ya share outfits

**Comment by VonZorch** [comment]
Ok, I guess we're done here.
