### ISSUE TITLE
Feature request: new mission offer condition: player money

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#226]
I'd like to request a feature to have a mission offer condition based on the amount of money the player has. This could be used to, for example, offer players loan shark missions if they get into debt or only let them get other missions once they become rich.

**Comment by endless-sky** [comment]
Done (commit 0ea3a3e, condition variable "net worth"). It's limited to +-2B, however, because condition variables use 32-bit integers. So, if you have more than 2B credits, the variable will equal 2,000,000,000.

**Comment by Pointedstick** [comment]
Excellent!

**Comment by endless-sky** [comment]
This "net worth" feature is available in the 0.8.8 release.

**Comment by Pointedstick** [comment]
Wonderful.
