### ISSUE TITLE
allow sorting of missions based on destination, reward, or deadline

### ISSUE THREAD

**Issue by karkatic** [endless-sky/endless-sky#2260]
shameless plug for https://github.com/endless-sky/endless-sky/pull/2200

**Comment by Amazinite** [comment]
#236 duplicate

**Comment by Wrzlprnft** [comment]
to be honest... why? is this a forum, where stuff gets lost? 83 people are watching and getting another notification, it's more known that MZ is on vacation for now 16 days now, and the pull requests allow for discussions.
if you want to bring attention to it, just comment on your pull request. please try to keep this on the point, it's a versioning tool after all.

**Comment by karkatic** [comment]
because i'm new to git and github, and i now have 3 distinct "check-ins" under the same pull request, and i want new eyes on the new commits, but based on the default sorting in the webpage it's not apparent that there are new outstanding changes to be reviewed.

**Comment by KiLEdEnNis** [comment]
@karkatic https://github.com/endless-sky/endless-sky/wiki/CreatingIssues

**Comment by Amazinite** [comment]
This is a duplicate, which means it should be closed. And this isn't a forum, it's a development platform. You don't advertise PRs with issues.

**Comment by Amazinite** [comment]
>based on the default sorting in the webpage it's not apparent that there are new outstanding changes to be reviewed

That is what notifications are for, which, as Wrzl said, 83 people get every time a comment is made or a commit is pushed on a PR.
