### ISSUE TITLE
Defer reactor check in outfitter

### ISSUE THREAD

**Issue by ggeorgovassilis** [endless-sky/endless-sky#2261]
Upgrading a reactor is currently difficult because of a check that idle consumption doesn't exceed energy generation. This requires installing _first_ the new reactor, _then_ selling the old one. The only workaround is to first make room in the ship by selling most outfit, installing the new reactor, selling the old one, buy outfit back. The energy budget check should be deferred to the moment when exiting the outfitter.

reported against 0.9.6

**Comment by jafdy** [comment]
related #1879 #1896

**Comment by KiLEdEnNis** [comment]
ya have a Syndicate or Hai regenerator?

**Comment by MessyMix** [comment]
@KiLEdEnNis yes, that's what he's talking about.

And yes, the check should wait until leaving the outfitter.

**Comment by KiLEdEnNis** [comment]
for now just sell the regenerators instead of selling the rest & buying a reactor

**Comment by Bladewood** [comment]
I think he already knows how to work around it.
The point of this issue is that he wants to be able to *skip* that step.

**Comment by KiLEdEnNis** [comment]
@Bladewood 
> This requires installing first the new reactor, then selling the old one. The only workaround is to first make room in the ship by selling most outfit, installing the new reactor, selling the old one, buy outfit back.

that's y I said that

**Comment by endless-sky** [comment]
If the check were deferred until leaving the outfitter, it would be possible to quit the game while in the outfitter and reload it to have a ship with negative energy generation. Which, in turn, would mean that there would need to be a check for negative energy generation performed every time the player tries to depart the planet.

Given that only a handful of outfits consume idle energy, a better solution might just be to change how those shield generators work.

**Comment by ggeorgovassilis** [comment]
@endless-sky I'm not familiar with the game mechanics, but negative energy output doesn't sound like a problem to me. My reasoning: let's say there are no energy checks in the outfitter or anywhere else and a ship leaves orbit with a negative energy budget. It'll just sit in space, unable to move. I'll notice, load the game again and fix the problem.
The notion of a negative energy budget sounds a bit odd, stored energy should probably be floored at 0 Joule (unless negative energy is necessary to implement the hai ion cannon effects [fermat-like-note-in-the-margin: I have an idea how to implement the ion canon drain effect lag without negative energy and without extra code]).

**Comment by VonZorch** [comment]
Move the power and engine checks to Depart and if they fail do not launch.
I frequently pull parts off of captured ships at the outfitter if I'm not sure if I will want to sell the ships or not.  It would be nice to be able to leave the outfitter and sell the gutted hulks at the shipyard without buying power plants and engines for them.

**Comment by KiLEdEnNis** [comment]
press escape twice, save/load, go to shipyard & sell the empty hulls
that circumvents the checks

**Comment by VonZorch** [comment]
Thanks, that works.

**Comment by Elyssaen** [comment]
@endless-sky, I've had a PR up fixing this exact issue since 4 months before this issue went up, and almost half a year ago now. The fix doesn't run into the problem you've mentioned. Can you merge it, or at the very least discuss the PR? It is up to date, no merge conflicts.

**Comment by endless-sky** [comment]
Addressed by merging in b5ecaaec.
