### ISSUE TITLE
Add "Fleet: Kollect" option

### ISSUE THREAD

**Issue by ArsRelic** [endless-sky/endless-sky#2264]
I was looking at the open project and didn't see this in there.

Playing around with mining, but the starter fighter has tiny cargo.  Adding a freighter to the fleet didn't help because it didn't scoop up the ore once the asteroid is destroyed.  Add to that the pretty erratic following movement of the freighter it made it very difficult to catch anything with it.  Pretty frustrating when you have extra ships that just wander around you when you try to mine.  It wouldn't bother me if all my escorts went after the same ore/flotsam, as long as they go after it.

I did spell Kollect incorrectly because it looks like 'k' is not being used.

Since I compile from source I took a look and it appears the functionality to make this work is actually in place.

The basic logic would be...

if escort has no free cargo space
-normal follow flagship
else
if escort has free cargo space
-check for ore/flotsam nearby
--if it exists try to get it

...

As I said above, I wouldn't care if all the escorts I had tried to get the same debris piece as long as they at least try to get it.

**Comment by jafdy** [comment]
I don't think we need a key for this. Just have it automatic or not at all.

**Comment by Wrzlprnft** [comment]
isn't better AI concerning mining planned? this feels like a duplicate, at least it was discussed somewhere before.

**Comment by KiLEdEnNis** [comment]
also, it doesn't have to be a command, just a preference like ammo usage by escorts (like; chase all ore/ore you mined/never)

**Comment by VonZorch** [comment]
However it's implemented, it sounds like a good idea to me.  I was planning on requesting this myself.

**Comment by eternal-sorrow** [comment]
This is needed very much. Collecting the floating items with the flagship is painful. Would be nice if I mined the asteroids and escorts collected the resources.
