### ISSUE TITLE
Ships freeze in midspace (fixed)

### ISSUE THREAD

**Issue by KalelNimrott** [endless-sky/endless-sky#2267]
I'm using six Mule (but it really doesn't matter what ships are in my fleets) and from time to time, the ones that I do not control directly, freeze in midspace. They stop following or even moving at all. Mine and all other npc ships do not suffer from this.

**Comment by KalelNimrott** [comment]
Fixed, sorry for the trouble

**Comment by KiLEdEnNis** [comment]
if you're sure it doesn't happen again, you can close it
also, is this the same problem as #2251 ? it probably is, in which case this is a duplicate, meaning close this issue
