### ISSUE TITLE
Syndicate test ships have crew

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2268]
In spite of the mission saying that it's a robotic ship, it has crew.

**Comment by KiLEdEnNis** [comment]
that's because if you'd board it and it's an automaton ship you'd have a free ship
making in never disabled fixes the issue in both cases

**Comment by lheckemann** [comment]
No, because disabling the ship is also part of the mission. See
https://github.com/endless-sky/endless-sky/blob/v0.9.6/data/syndicate%20world%20jobs.txt#L170

**Comment by Bladewood** [comment]
make it `uncapturable`?

**Comment by MessyMix** [comment]
My proposition: self district just like the Kor automata.

**Comment by KiLEdEnNis** [comment]
oh uncapturable was a thing as well? do that and make it an automaton as well

**Comment by MessyMix** [comment]
Related to fix at once: #2151

**Comment by Pointedstick** [comment]
Good catch, will fix shortly: self-destruct + automaton.

**Comment by lheckemann** [comment]
Fixed in #2902. Thanks!
