### ISSUE TITLE
Too easy to make money selling plundered high-value outfits / some things should not be lootable

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#227]
During a number of missions in the Free Worlds string, there are major fleet battles that inevitably result in a bunch of disabled Republic ships. If you have a ship with a large enough cargo hold (like a Mule, Bactrian, or Dreadnought) It's easy-peasy to get rich *fast* boarding these disabled ships and selling their reactors. A couple Armageddon Cores from disabled Republic Carriers and your money woes are gone forever! Not that I don't like financial freedom, but this feels too easy. I didn't even have to disable the ships myself most of the time; the fleet I warped in with often did most of the work.

**Comment by Phezzan** [comment]
IMHO the crew shouldn't let you take those things without a fight.

My solution: a flag on generators, engines, guns and other things (outfits) you'd expect them to hold onto in a fight.

I have written this. ("secure" in the outfit definition)
Let me know if you need me to clean it up and do a proper pull request.

**Comment by Man-animal** [comment]
I think it would be simpler to just make reactors unlootable or less valuable at the high end.
Guns, shields, etc. all tend to have much lower values already, they don't really need a looting nerf.

Also, the ships that can get away with plundering reactors are also the ships that tend to have enough crew to easily win fights anyways.  So it seems like a needless hit to anything that *isn't* a Bactrian or similar, and those are powerful enough already.

**Comment by Pointedstick** [comment]
Yeah, looting a reactor also has sort of macabre overtones. I mean, if you take a disabled ship's reactor, you're pretty much killing everyone in  it, right? I'd assume the reactor is powering the life support systems. Maybe just no lootable reactors.

**Comment by Oeleo** [comment]
Yes it's a lot of profit, but maybe not too much, did you try to ask a tribute of a republic planet during the war ? Even with about 450 millions money of boat it's hard to fight the fleet that they send.

**Comment by Wrzlprnft** [comment]
My idea is: you don't have to fight the crew, but you need engineers, which you pay, when you like to take something from an enemy ship, that is not like cargo oder ammunition easily removeable
So you loose crew places and you have to pay, which makes plundering more expensive, but probably only for high-valued, but good in the enemy ship integrated stuff like energ cores

**Comment by Oeleo** [comment]
Edit : I agree with the title because I didn't tried the Quarg : with ~8 Bactrian you can disable one of their ship without lose one, and after that you use their stuff you to farm it. Seriously you can make 1.000.000.000 of moneys in one hour.

**Comment by guillochon** [comment]
My feeling is that "external" outfits (guns, shields, engines, etc) should be lootable without a fight if the ship is disabled, as in principle you can strip the ship of the external systems while the crew helplessly watches from inside. The "internal" outfits (reactor, battery, cooling) should not be lootable without a fight, perhaps one "round" of fighting per system you wish to loot (and with scaled-down death benefits).

**Comment by Pointedstick** [comment]
So "reactor farming" is being repeatedly brought up as an easy way to make a ridiculous amount of money. I like the idea that @guillochon had that "internal" outfits would need a fight to be plundered. Or maybe certain things like reactors should simply not be plunderable.

**Comment by Pointedstick** [comment]
Another candidate for things that should not be lootable: mass expansions.

**Comment by gchapyzh** [comment]
Lootable items: Weapons, engines, cargo. Everything else should be accessible after a bit of combat. For example you want to take the reactor, there will be an 'Attack' were you have to fight a portion of the crew before you can loot the reactor.

**Comment by Pointedstick** [comment]
@Phezzan Fell free to communicate with the lead dev and do a pull request.

**Comment by airtroop392** [comment]
Not sure about cargo. How did the game justify its taking of engines and weapons and stuff? Something along the lines of "when you board, you can take stuff on the outside of the ship?" Wouldn't cargo be internally stored?

**Comment by gchapyzh** [comment]
The crew of the ship is likely boarded up in the bridge/reactor, trigger-fingers itching to shoot anything that moves. Taking engines and weapons and cargo?

Weapons: take a screwdriver, some really big pliers and a torch. The edges will need some polishing when you sell the weapons, but they should still work.

Engines: tie a very big cable to the engine, loosen the screws and struts, and then give a little tug with your own ship. Again, you will need to polish the edges and connectors and tubes, but it will run.

Cargo: blow up the cargo door and catch whatever flies out into space.

**Comment by airtroop392** [comment]
I suppose that makes sense.

**Comment by gchapyzh** [comment]
The reactor, however, would take time to excavate (ya know, blow a hole through the ship to pull the reactor out, etc...) and it would likely be defended since its deep inside the ship.

**Comment by gchapyzh** [comment]
Perhaps salvaged equipment should have it's own broken-looking picture, be a bit smaller then a popper outfit, and would sell at a percent of the price (50%)?

They would be by-able, too, so if you are low on money, you can fly a ship with cheaper but less reliable salvaged equipment.

**Comment by jmhorjus** [comment]
https://github.com/endless-sky/endless-sky/pull/852 addresses this issue to a significant extent (~50% reduction in profitability of reactor farming and interceptor capping).

**Comment by lehgogh** [comment]
Perhaps reactors may need to be custom-made to fit that specific ship, thus making it unlootable. (Why buy an usuable reactor?)

**Comment by Gkramme** [comment]
This has been partially implemented

**Comment by jmhorjus** [comment]
Yes the unplunderable attribute is now supported.

**Comment by Gkramme** [comment]
#1033 may adress this issue

**Comment by endless-sky** [comment]
Depreciation makes this much less of an issue.
