### ISSUE TITLE
adjust firing force max speed to factor reload [mechanics]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#2270]
i'm trying to rebalance the Railgun into something more practical: which involved giving it substantial firing force - if used as a (reverse) thruster, however: ship has no speed limit...

**Comment by jafdy** [comment]
https://github.com/endless-sky/endless-sky/commit/b20b7ff3522d97e145e19f8be9a2347995568542

**Comment by LocalGod79** [comment]
<shrugs> my build is up to date, and the Pond Strider (drag 3.6) firing three Rail Guns with reload 60 and firing force 480 make this ship go stupid-fast if the primary thrusters are not used...

**Comment by jafdy** [comment]
Take it up with MZ.

**Comment by Bladewood** [comment]
very high max speed != infinite max speed

**Comment by LocalGod79** [comment]
i tried reducing the force and increasing the frequency, and as near as i can tell, velocity is only limited by the ammo capacity - effects with velocity scale are useful for more than just making things look good...

**Comment by LocalGod79** [comment]
ftr; i'd be happy to rebalance the recoil on the gamut of existing weapons based on their previous per-frame recoil values under a by-reload system.

**Comment by endless-sky** [comment]
Drag only applies when you are thrusting, so that ships can "coast" when no thrust is being applied. That means, for example, that you can reach the same max speed (eventually) by firing a thruster for only 1/60th of every second that you can by firing the thruster continuously. That's essentially what you're doing, but using a "thruster" with several times as much power as the largest engine.

Note that aside from various repulsor weapons (which are *supposed* to act like thrusters) the highest firing force any existing weapon has is 40. You're using a value twelve times that amount.

**Comment by LocalGod79** [comment]
hmmmm...as i see it, the rail gun requires a firing force roughly equivalent to the tiniest engines available (if it's going to work they way it was originally intended) - but unless it fires *every* frame, it creates a reverse thruster that is capable of a much higher speed than engines (and becomes open to abuse by players).

i'm making efforts to balance its use in larger ships with a large recoil in mind (mostly with heat, though lacklustre damage and limited ammo are playing into the equation as well), but having even 40 firing force (every 5 frames, instead of 8 firing force every frame) in a 7ton weapon makes for unreasonable reverse speeds in small ships...

**Comment by KiLEdEnNis** [comment]
sounds like you made frontal Afterburners of some sort (Beforeburners?)
smaller firing force seems fine, maybe just make it high-damage & low RoF

**Comment by LocalGod79** [comment]
@KiLEdEnNis retroburners.

in fact, the Rail Gun description is being altered to reflect the "retro thrust" quality of the weapon, but reducing the rate of fire means increasing the firing force (to maintain counter-thrust to tiny engines), which exacerbates the issue (as small ships will get massive bursts of reverse thrust, probably combined with low drag figures).
