### ISSUE TITLE
Colony missions to space stations

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2273]
I don't think it's entirely appropriate for people to want to join a "colony" on a space station.
![2017-03-17-161146_391x60_scrot](https://cloud.githubusercontent.com/assets/341954/24052180/73797a82-0b2c-11e7-92c1-be3af6b171b2.png)

**Comment by KiLEdEnNis** [comment]
#1409

**Comment by lheckemann** [comment]
Whoops, sorry!
