### ISSUE TITLE
Make the mining personality deploy fighters and drones

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2274]
Right now, fleets with the mining personality (or it might just be a side effect of human miners also having timid) will hold on to their fighters and drones until they're in combat. Suggested making them deploy their fighters and drones to help in mining asteroids (and picking them up if they have any cargo).

As a side note, it would also be cool if drones and fighters would transfer cargo that they picked up to the mothership whenever they get full.

**Comment by zwparchman** [comment]
How should that be weighed against filling the mothership's cargo bay? Just fill it up? Don't drop cargo if the mothership can't hold it? I like the idea in general though.

**Comment by LocalGod79** [comment]
i think that drones giving their cargo to their mothership might conflict with existing coding if their mothership is the player's flag...

**Comment by endless-sky** [comment]
I'm pretty sure the only fighter or drone that comes with cargo space is the Boxwing, so this would have very limited usefulness.

**Comment by KiLEdEnNis** [comment]
future fighters could have some cargo too

**Comment by tehhowch** [comment]
As @LocalGod79 mentions, cargo transfer from carried to carrier is complicated by the situation where the carrier is the player's flagship. This is, however, the only case I see where the child->parent transfer would be unwanted, as it prevents the player from controlling what is in their cargo: 

Imagine if the player has a Bactrian, Carrier, or Aerie, with Boxwing fighters, and is doing some cargo + mining runs from A->B: 
1. The player buys `totalCargoSpace - flagshipCargoSpace` in commodities before takeoff
2. Then launches fighters while mining to benefit from improved mobility
3. Then recalls the fighters to jump to the next system after destroying all the high-value asteroids.

The game previously stored all the commodity cargo on the player's escorts, upon takeoff, but simple `carry->transfer` code would move the Boxwing's commodities into the flagship's cargo, possibly filling it up, and also leaving the largely uncontrollable boxwings with empty holds and no way to instruct to harvest mining flotsam.


All other cases do not impact the player, but allow for neat AI behavior, such as nimble mining fighters which hunt down minerals for a lumbering carrier ship, and also increase the likelihood that critical mission cargo is not stored on weak fighters with cargo space, but on their more durable carrier.

**Comment by tehhowch** [comment]
Updating @zwparchman 's #1971 over the next day or so to better cover situational docking (cargo full, low health, ammo) and relaunching.
WIP branch https://github.com/endless-sky/endless-sky/compare/master...tehhowch:SituationalFighterDocking 
and in-place pull update: https://github.com/zwparchman/endless-sky/pull/1

**Comment by tehhowch** [comment]
As an update: #1971 adds cargo transfer from AI fighter/drone to AI carrier. Player-owned fighters/drones will avoid transferring cargo to their carriers to avoid the situation LocalGod and I mentioned above.
Between #1971 and the merged 2726, I think all parts of this issue are resolved. The behavior of Boxwings or other unarmed, cargo-space-having carried ships in AI mining operations is fixed by the open pull #3064
