### ISSUE TITLE
Landing on the Ring of Friendship before a Coalition planet first

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2278]
Doing what is described in the issue title doesn't trigger any mission. Because the Heliarch ringworlds can be bribed (intentional?), you can land on the ringworlds without landing on a Coalition planet, but doing so doesn't trigger any mission and you have to leave to land on a Coalition planet first, which just ends up pointing you back to the ringworlds.

**Comment by whismerhill** [comment]
doesn't sound like an issue to me.

**Comment by Lineth** [comment]
#2279 :3

**Comment by endless-sky** [comment]
Fixed (2ab0555) by making it so you can't bribe the ringworlds, so you can't land on one of them before getting the first contact mission.
