### ISSUE TITLE
0.8.7: If player has both hyperdrive and jump drive, Syndicate replaces hyperdrive anyway

### ISSUE THREAD

**Issue by ItsNickBarry** [endless-sky/endless-sky#228]
If the player has both a hyperdrive and a jump drive, he or she ends up with 0 hyperdrives and 2 jump drives.  Two messages appear: one indicating that the hyperdrive has been replaced, and one indicating that the player already has a jump drive.

**Comment by ItsNickBarry** [comment]
This also causes two identical "Investigate the Pug" missions to appear on the map.

**Comment by endless-sky** [comment]
I fixed the bug of two missions being offered in commit c398819.

**Comment by endless-sky** [comment]
And, commit 0bb25d0 will make it so that the Jump Drive mission is offered rather than the Hyperdrive mission, if you have both.
