### ISSUE TITLE
Toggle/Separate Boarding of Friendly Ships

### ISSUE THREAD

**Issue by kennethdhau** [endless-sky/endless-sky#2281]
At the moment, it's really problematic trying to board an enemy ship when some surveillance drone hogs the boarding AI's targeting.  It'd be great if boarding different types of NPCs were separated or the behavior toggleable.

**Comment by Bladewood** [comment]
For your particular issue (tiny, puny, worthless ships vs the bigger ones), we have this old issue. https://github.com/endless-sky/endless-sky/issues/1229

**Comment by MessyMix** [comment]
#814 which is implemented now, so a workaround would be to zoom out very far and select what you are trying to board.

**Comment by whismerhill** [comment]
I'm not sure how that could be improved ?
you can already select your target ship & board it.
what are you suggesting ?

**Comment by kennethdhau** [comment]
I'll try again later, but it would re-target a nearby friendly ship instead of board the enemy one.

**Comment by Nechochwen-D** [comment]
If the ship you are targeting is disabled and boardable you will move to board it. Otherwise you will move to board the nearest ship.

it should not be much of a problem to add another key to board the nearest enemy ship. I will see what I can do to add this.

**Comment by jafdy** [comment]
SHIFT+B

**Comment by Tadrix** [comment]
I'd suggest that Shift+B is for disabled escorts and then friendlies, and B is for hostiles (to mimic N and Shift+N)

**Comment by jafdy** [comment]
@Tadrix That's what it dose.

**Comment by KiLEdEnNis** [comment]
like, it LITERALLY does that for a long time

**Comment by Tadrix** [comment]
Word "literally" is overused. And no, it doesn't. But no worries, I'll help you:

What indeed exists for a long time, is:
B — board selected (or nearest boardable) ship
Shift+B — board disabled escort

What I suggested them to do:
B — board selected (or nearest boardable hostile) ship
Shift+B — board disabled escort, if none, board disabled ally

Also, I suggest that there would be an option to "select next hostile ship", to give player the possibility to cycle through hostile ships only. And a key to clear a selection.

**Comment by Wrzlprnft** [comment]
isn't r select nearest hostile not disabled ship?

**Comment by KiLEdEnNis** [comment]
> Word "literally" is overused. And no, it doesn't.

it does, maybe besides shift B boarding allied ships

**Comment by KiLEdEnNis** [comment]
> (to parallel N and Shift+N)

shift N doesn't target allied ships either so it IS parallel
get your comments right then, I'd expect that from someone that argues all the time

**Comment by Bladewood** [comment]
> B — board selected (or nearest boardable hostile) ship

pretty sure that's what B already does. It prioritized disabled hostiles over friendlies in need of assistance.

**Comment by Amazinite** [comment]
@KiLEdEnNis @Tadrix I know that you're both in the Discord; if you want to bicker over small things then do so there. GitHub is for more civil arguments than "get it right."

**Comment by Tadrix** [comment]
@Wrzlprnft 
> isn't r select nearest hostile not disabled ship?

Yes it is. What I suggested is a way to cycle through _all_ of them (included disabled ones, kind of like N does with all of ships)

@Bladewood 
> Shift-N then N if you do.

Thanks.

**Comment by Amazinite** [comment]
As noted, shift+B will only select your ships that have been disabled. As of #6346, just B will select ships based off of your boarding priority preference. If your preference is set to select by value, then stray drones won't be an issue if there's something bigger to board.
