### ISSUE TITLE
Departing after Alondo rushes out to "get papers signed" on New Tibet prevents you from landing

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2282]
In `FW Northern 1`, you take a bunch of ships to Seginus, Alphecca, and finally Alioth to convert them to the Free Worlds.
As the last step, you land on New Tibet in Alioth, where Alondo promptly rushes out to "get these papers signed before they [the government] change their minds."

By then, you're expected to go to the spaceport, where you have a short conversation with Alondo. After that, New Tibet, Clark, and New Holland are Free Worlds territory, and you can land freely.
But, if you depart from New Tibet instead, you do not have docking permissions; the worlds and the systems are still Republic-controlled.
This is because the `fw northern expansion` event is not triggered in `FW Northern 1`'s `on complete`, but instead in `FW Northern 2`'s `on offer`.

I found it to be an oddity.

**Comment by endless-sky** [comment]
Fixed in d41f2f7.
