### ISSUE TITLE
"FW Pug 3C": Skipping ahead to Markab causes NPC escorts to get stuck in uninhabited space

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2284]
In `FW Pug 3C` (in-game, `Escort to Hephaestus`), you are provided a set of escorts- some dreadnoughts, cruisers, and carriers- that you must escort to Hephaestus so that they can be outfitted with jump drives to fight the Pug.

What bugs me so deeply is that whenever I try to hop along directly to Markab (my jump path may or may not include Pug systems), skipping all of the other systems that you would have to enter (with a hyperdrive) to get there, the two provided carriers will inevitably get stuck somewhere around Cardax with no fuel.

Save provided for your convenience.
[Eta Carinae.txt](https://github.com/endless-sky/endless-sky/files/860066/Eta.Carinae.txt)

**Comment by KiLEdEnNis** [comment]
I recognize it w/o looking at all, giving them ramscoops won't work though, we'd need to make a new set of variants to not change all

**Comment by jafdy** [comment]
Changing all of them would be much of a problem, it might seem odd but it would have little overall effect.

**Comment by jafdy** [comment]
They are mission ships so you could just redefine them in the mission.

**Comment by endless-sky** [comment]
I'm not sure if there's any good general solution for this. Un-escorted mission escorts that need to travel through significant amounts of empty space are likely to run out of fuel. The reasonable solution is to escort them at least partway to make sure they refuel before entering the empty space.

**Comment by Bladewood** [comment]
What confuses me is why they do not land and refuel independently.

**Comment by tehhowch** [comment]
How recently have you checked their behavior? We've added lots of refueling updates since this issue was originally opened, and my "Unifying" PR #3123 will only extend the logic further (covering ships which use MoveIndependent as a part of their travel orders, instead of just MoveEscort, e.g. `personality uninterested` or escorts following Move-To orders).
