### ISSUE TITLE
Undocumented blending mode on the shuttle sprite

### ISSUE THREAD

**Issue by Kryes-Omega** [endless-sky/endless-sky#2285]
In a recent conversation involving blending modes, it came up that the "=" designated blending mode used on the shuttle sprite is not documented in the BlendingModes wiki page. If the mystery could be solved, it would be appreciated.

**Comment by endless-sky** [comment]
Fixed. The wiki page previously did mention that you could use premultiplied images, but didn't mention that you use '=' to mark them.

**Comment by Kryes-Omega** [comment]
Thanks!
