### ISSUE TITLE
Heat-based generator (negative active energy?)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2286]
https://groups.google.com/forum/#!category-topic/endless-sky/feature-requests/4qyKSJtq79w
> I am making an Add-on for the game, and one of the ideas i had with this new active cooling system was to make one that works as a thermoelectric generator, **cooling very little, requiring other cooling systems to supplement it, but that produces more energy the hotter the ship is.** i intended to achieve that by making it so the " active energy" is negative, but the game does not accept that. Sadly i have no idea how to code, so if anyone is a contributor to the game i suggest making a change to make it possible to produce energy this way, even if just as a modding resource.

**Comment by Wrzlprnft** [comment]
i like the idea.

**Comment by MCOfficer** [comment]
it might be overpowered, but physically speaking, it makes sense.

however, steam of course won't work without gravity, so you would have to use something like thermocouples, using the hull itself as cool and the reacor cooling as hot temperature supply.
https://en.wikipedia.org/wiki/Thermoelectric_generator

**Comment by KiLEdEnNis** [comment]
something that generates more energy the hotter ya run does give a choice about how much cooling ya want
although would it be on raw heat or %?

**Comment by MCOfficer** [comment]
considering that technology will maybe be much better than it is now, i'd go with ~50% (maybe set by what "level" the generator is? like, thermogenerator mark 1 has 10%, mark IV has 50%).
thought that's ruled by the guys doing the balancing.

**Comment by KiLEdEnNis** [comment]
seems too delicate to keep it balanced (just like the Pug)

**Comment by tehhowch** [comment]
A `"thermoenergetic conversion"` would operate on the difference between the ships current heat, and the heat being generated. (No guarantee that every ship uses electricity 😋)

Tracking the ship's heat between frames wouldnt be tough - just setting a `previousHeat` at the end of Ship::Move and then checking the difference on the next call would be one way.

**Comment by Knightroad** [comment]
I tried to do this myself, ran into the same issue. Searched online to see if anyone else figured it out. <Eagerly following thread to figure how to do this myself>

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/e287f8d599129847466003cc363c36a49724c6c7 has allowed for cooling energy to be negative, which should now create energy with increased heat.
