### ISSUE TITLE
Terraforming Rand 3: Imprecise instructions, capturable asteroid

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2287]
[Apparently target asteroid is capturable.](https://steamcommunity.com/app/404410/discussions/0/496880203074501166/)

One more problem — mission instructions:
> You just need to board it, install a small ion thruster, and wait for it to land on the planet, then return here.

Wait for it to land on the planet bit is confusing. On my first play-through I did exactly that and was puzzled when this target asteroid just majestically floated past the planet.

**Comment by KiLEdEnNis** [comment]
you can also destroy the asteroid

**Comment by Bladewood** [comment]
I once went to acquire real ion engine outfits (by boarding surveillance drones) to install them into the asteroid. It was quite a bit of work to resist the urge to sell them on planets before I got there.

And then I learned that it was completely pointless.

**Comment by Tadrix** [comment]
Yep, this too.

What I recommend:
1. Require the player to have 20 t of cargo space free (for X1050 Ion Engines) and fill it with cargo "Ion Thruster".
2. Reword that Amy's last phrase like this:
> You just need to board it, install a small ion thruster we provided, and return here.
