### ISSUE TITLE
Player Info panel not showing actual crew number for under-staffed escorts

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2288]
I am being flooded with "moving erratically notices" for different ships in my fleet after farming a lot of pirate ships. I have double checked and all my ships apart from my flagship have sufficient crews. It seems you are falsely notified about lacking crew in other ships in your fleet if your flagship is understaffed.

**Comment by KiLEdEnNis** [comment]
I only ever have those messages when I capped a ship, & only my flagship and that ship give the messages, and only when they ARE understaffed
do you have escorts that have more required crew than max crew?

**Comment by jafdy** [comment]
You can find your self with under staffed escorts if you don't have enough crew to man both ships properly.

**Comment by Bladewood** [comment]
I think he's already landed and re-crewed his vessels.

**Comment by wambat1** [comment]
This is occurring before landing only, but I think I have found what is going on. The bug is in the layer info window, which is showing captured ships as having their minimum required crews, when in fact they do not. The only time you are shown the actual crew count, and can see they are understaffed, is in the ship capture window once you have won the boarding action.

**Comment by KiLEdEnNis** [comment]
yea I saw that yesterday, went from 2 freighters to a Falcon, capped ships, the I screen showed my required & max crew, not how much I had, so didn't see how much crew I was missing

**Comment by endless-sky** [comment]
Fixed in 52a101f.
