### ISSUE TITLE
When scanned with interference plating

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2290]
If your interference plating blocks the scan, the message at the bottom will still tell you that `The <government> <ship> suceeded in scanning your [outfits || cargo]` even if they never actually suceeded.

**Comment by KiLEdEnNis** [comment]
so it shows the message when the scan is done, fail or succeed?

**Comment by Amazinite** [comment]
When the scan is done, even if they don't successfully scan your cargo or outfits, it says they did.

**Comment by LocalGod79** [comment]
`The <government> <ship> completed their scan of your [outfits || cargo]`?

**Comment by Bladewood** [comment]
We can count "completion" as being the same thing as "success."

**Comment by Bladewood** [comment]
Wait.
We can think of interference plating as not strictly "blocking" the scan, as in stopping it, but instead as shielding parts of your ship from the scan.
And then it generates the illusion over on the scanning ship's side that they have scanned everything available on your ship, and they leave.

**Comment by gunqqer** [comment]
Well if that is how the plating works (which it might) a message saying they scanned your ship but did not see any illegal cargo would be nice

**Comment by endless-sky** [comment]
Fixed in 152a805 (using @LocalGod79's suggestion).
