### ISSUE TITLE
Hailing a planet or ship with autopilot on disengages autopilot

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2292]
When say landing on a planet you do have cleared the you may want to hail to then bribe them. After you do so instead of continuing on your landing autopilot will disengage. I don the know if this is intended or not but would be nice if it wasnt a thing.

**Comment by endless-sky** [comment]
I can't reproduce this. If I start landing, then hail a planet or ship, my ship continues landing on autopilot when I close the hail dialog.
