### ISSUE TITLE
escort swizzles (captured ships) change when YOU land

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2295]
so I capped a pirate Bastion w/ my Falcon, & was a bit under required crew, so by the time I nearly landed, some random pirate Fury found it hilarious to jump in and just disable the Bastion & I couldn't stop landing in time

anyway, I took off, and the Bastion had changed swizzles, so all swizzles change when YOU land, not the escorts
if its crew can repaint the ship mid-flight they might as well patch themselves up (:P)

worth a fix or not? didn't see duplicates

**Comment by Tadrix** [comment]
I can confirm. Have been seeing this all the time.

**Comment by gunqqer** [comment]
Also can confirm, this happens with all of your escorts

**Comment by LocalGod79** [comment]
in fact, escorts not flying escort colours is kind of buggy in certain situations; e.g. captured fighters cannot be recalled to recently captured carriers.

**Comment by zwparchman** [comment]
In the FW campaign you paint new colors on your ship. I doubt you would repaint a captured ship in space.

**Comment by endless-sky** [comment]
The game's current mechanics here are simple, and nearly correct: a ship's color is set when it is first placed "into play" in space.

Addressing this issue would require instead setting the ship's color when it is loaded from a file, when it is with you on a planet, and a variety of other cases. For a very minor change in realism, that added complexity isn't worthwhile.
