### ISSUE TITLE
[Feature] Citadel

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2297]
Just a thought:
For ships which we want to allow the player to plunder, but absolutely not to capture,
[Citadel](https://en.wikipedia.org/wiki/Safe_room#Citadel_on_ships).
Unplunderable outfit, could replace current Quarg "Intrusion Countermeasures"

**Comment by Wrzlprnft** [comment]
i kind of imagine the bridge of the ships in the current lore to be somewhat like this, which allows the player to plunder, nut he has to actually attack. though, the bridge is rarely hidden.

though, with the power of just destroying the disabled ship, a citadel as described here would need to be an escape pod on top.

you are suggesting this as an outfit?

**Comment by Tadrix** [comment]
As an unobtainable outfit for ships which aren't meant to be obtainable by the player for now, at least this was my idea at the start. It wouldn't be an escape pod, just impenetrable shell for a crew and control systems. Lorewise they still rely on someone of their faction to show up. An indicator of distress signal sent could be a nice addition (it could do nothing gameplay-wise, or it could activate somewhat random hidden timer; after that time, overwhelming reinforcements would show up in that system; could be a pain to implement though). 
It would replace "Intrusion Countermeasures" in ridiculous amounts and large crew sizes for Quarg ships, and then "Intrusion Countermeasures" could be purely Korath outfit, with a price of 90K (for example).

Escape pod, however, could be sold to the player. This would add the possibility to escape during shipboard battle (and take, for example, up to 7 other crew with the player and forsaking remaining crew) if someone attempted to capture player's ship (then attackers would instantly win, but this escape pod could be picked up by escort, making it a temporary flagship — maybe even providing player with an option to choose his/her rescuer by selecting and pressing B, or, if no escorts, then contacting friendlies and asking for rescue). This seemed to be too complex to be feasible before, but, as I read suggestions to make hostiles capture player's ships, this starts to look like a good idea, an alternative to "You have died, now reload."

**Comment by Amazinite** [comment]
I'm not sure why an entirely new outfit would be neccessary. If we didn't want the Quarg ships to be captured but still be plundered, we'd just put the `uncapturable` tag on them. It would have the same effect without needing to create a new outfit and new attributes.

**Comment by Tadrix** [comment]
Indeed.

> This can be used to mark things that are not really "ships," e.g. a derelict hulk that you can plunder but that cannot be repaired to fly on its own.

Maybe I'm mistaken but this seemed to imply that primary use wouldn't involve actual ships, and various comments in commits suggested that for now Quarg ships _are_ intended to be uncapturable, without explicitly forbidding to try. But in the end first variant of my citadel proposition seems redundant.

However, the concept of such protection makes sense in pirate-infested space regions.

What about that last part?
> EDIT: Just thought of another variant of a citadel usable by the player: It prevents possibility to capture ship in which it is installed, but balances it by taking up 20 outfit space and preventing a certain percentage of ship's crew from participating in boarding actions (so they take up bunks and receive salaries, but aren't present in h2h combat) to discourage using such a ship for risk-free capturing.
