### ISSUE TITLE
Rim Archaeology 4B mistake(???)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2299]
so this mission has a Marauder Arrow to escort, but 2 things:
1. killing it doesn't fail the mission
2. you have the 2 passengers in your own ship (which is partially a mistake in #1072 but the mission suggested you'd have to carry them in your ship)

**Comment by Tadrix** [comment]
AFAIK you're not supposed to escort them. They just follow you, spy on you, and eventually sic the pirates on you (in mission 5A)

**Comment by KiLEdEnNis** [comment]
oh ya mean like the Deep Archaeology?
that 1 is obvious, I never understood the Arrow here though, since it doesn't show up attacking the planet
making 2 strings where 1 has the Arrow if ya didn't kill it & 1 that doesn't have the Arrow when ya did kill it may reduce confusion
