### ISSUE TITLE
Capturing ships with docked fighters/drones

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2300]
God knows how, but I managed to capture a Tek Far 71 - Lek carrier that still had several Far Lek 14 drones on it. I'm guessing this is because it was somehow disabled before it could deploy all of its drones.

So I managed to capture it.

It continued to carry its drones.

Is this intentional? Should the drones have been forcibly deployed instead? Or should they have been captured along with the carrier? It's apparent that they kept their Kor Sestor allegiance. (They did not appear on the escort list in the corner, nor on the player info screen. Also, the drones disappeared from the carrier when I landed on a world.)

**Comment by jafdy** [comment]
They would also be Sestor if you had launched them. I think this is a duplicate.

**Comment by KiLEdEnNis** [comment]
reminds me of an issue I made where enemy fighters & drones try and dock in your ship, it's similar

**Comment by gunqqer** [comment]
Capturing enemy drones/fighters and carriers needs some work. Honestly drones and fighters need work in general to make them more useful but that's another issue...

**Comment by KiLEdEnNis** [comment]
Sestor fighters are fine, human ones are the shit ones

**Comment by Bladewood** [comment]
Let's not bring this conversation off-topic, please. The fighter/drone situation has been discussed many times before.

**Comment by DingusShingleton** [comment]
That poor, poor horse.

**Comment by endless-sky** [comment]
I've made it so fighters will flee from a disabled mothership in commit 6f09079. That will have the side effect of making it nearly impossible for this to happen.

What was causing this most often in the past was that if a ship is fleeing because it's nearly dead, its fighters try to return to it.

**Comment by endless-sky** [comment]
The code now also covers the very unlikely event where fighters are captured along with a ship (83506ed), so I'm considering this to have been fully addressed.
