### ISSUE TITLE
Feature Request: Outfits to re-purpose extra crew space

### ISSUE THREAD

**Issue by BlaiseDarkrider** [endless-sky/endless-sky#2302]
First, I would like to say I have been enjoying the game since I started playing and hope to see it thrive as content is added and revised.

Endless Sky already has outfit mechanics to change cargo space into outfit space and vice versa. It also has two Bunk Room outfits to gain extra crew space. 

I think setting up a "Cargo Closet" and a "Machine Room" outfit, which sacrifice 2 crew space for either 10 cargo space or 10 outfit space respectfully, might add another dimension of customization to the ships that have excess crew space to spare.

**Comment by Bladewood** [comment]
I'm certain that crew space -> outfit/cargo space has been discussed before.
And it has been rejected.

**Comment by gunqqer** [comment]
The Bactrian is already OP enough, if all extra bunks were turned into space.... whew 

If you really want this learn how to make plugins and make an outfit to do it

**Comment by Tadrix** [comment]
> "Cargo Closet" and a "Machine Room" outfit, which sacrifice 2 crew space for either 10 cargo space or 10 outfit space respectfully

Too good to be balanced.
Probably it would be logical to somehow represent that you can put your cargo in unused bunk rooms (without tearing down walls and consequently suffering from reduced cargo space gain), but it would be of little gain. If anything, the only thing bunk space should convert directly to is cargo space (not outfit space), and at an approximate rate 8 (or less) cargo for 3 bunks.

**Comment by gunqqer** [comment]
Yeah if you did that I'd be waaaay to happy. I could make more Bactrian builds that are even more OP than before. Something like this would be neigh impossible to balance

**Comment by KiLEdEnNis** [comment]
@gunqqer new outfits expansions instead of mass expansions, the Bactrian got nerfed along due to barely being able to stack a lot of outfits expansions
still I'm against stuff that converts bunks to stuff (although it would make transports better, it seems weird & OP on big extra bunk warships)

**Comment by DingusShingleton** [comment]
Make these bunk conversions have a brutal "cooling inefficiency" score, and it's all good in the hood. If they each counted as 2 outfits expansions.... yikes

**Comment by Amazinite** [comment]
Makes sense too; you probably need to move a lot of the interior structure to get any useful cargo space out of bunk rooms given how compact they probably are, so it would hurt the cooling more.
