### ISSUE TITLE
Wormholes and destination plotting

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2304]
While traveling to Hai space, I noticed an inconsistency between where my flagship entered the system to and where my escorts entered to.

![28c1a25a90dc40c898903d8c67638d45](https://cloud.githubusercontent.com/assets/17688683/24326159/943b5486-117e-11e7-8bae-d396d88adffe.png)

While I entered the system at its center, my escorts entered right on top of the wormhole.

After a bit of testing, here's what I found out. This only happens when you...
-  ~~entering the system via jump drive (? Not entirely sure, because sometimes this seems to happen while hyperdriving into the system but not as consistently as jump driving in)~~ are not holding the jump key to wait for everyone
   - Only ships that enter after your flagship and not along side it will end up near the wormhole
- are actually going through the wormhole. i.e. you have chosen a destination planet that is beyond the wormhole, but interestingly not if the wormhole itself is the destination

This is nothing gamebreaking, but just something I found out of the ordinary.

**Comment by KiLEdEnNis** [comment]
I remember a similar issue about escorts not jumping in the same place when ya jump to a system
knowing you I doubt it's a duplicate but might wanna check

**Comment by Amazinite** [comment]
I know which one you're talking about, but I recall that being fixed. They're probably related though.

**Comment by Amazinite** [comment]
It was #2109

**Comment by Amazinite** [comment]
Just tested it with the latest build and this still happens.

**Comment by endless-sky** [comment]
7183d11 should fix this.
