### ISSUE TITLE
Wanderer Mind mission: Can land on station after the battle begins, but not after the mission is completed

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2306]
[Eta Carinae.txt](https://github.com/endless-sky/endless-sky/files/870558/Eta.Carinae.txt)
I can land on the station.
But, in the conversation before the battle begins, it says something about the Kor Mereti sealing up the station, and after the mission is completed, the station is restricted.

I'll assume we are not meant to land on the station after the Mind is integrated. In that case, the problem here is that I can land on it in the time between the start and the end of the mission.

**Comment by endless-sky** [comment]
Fixed in 14600e9.
