### ISSUE TITLE
How do the Wanderers deploy Flycatchers?

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2309]
Flycatchers seem to be deployed in several Wanderer systems, even though no Wanderer ship has bays for them.

That seems weird. How can the Wanderers deploy them if not one of their ship has space for them?

Related: #1730

**Comment by Tadrix** [comment]
> Flycatcher drones are used by the Wanderers to keep their star systems safe.

I guess they just take off the planet?

```python
fleet "Wanderer Flycatchers"
	government "Wanderer"
	names "wanderer"
	personality
		swarming
		heroic
	variant
		"Flycatcher" 5
	variant
		"Flycatcher" 4
	variant
		"Flycatcher" 3
	variant
		"Flycatcher" 2
```

No carrier.

So they are just like satellites, never leaving their system.

**Comment by Rakete1111** [comment]
If they take off a planet and act as satellites, then they should never be buy-able by the player, as you cannot take off without selling them.

**Comment by Tadrix** [comment]
Wanderers may have infrastructure in place (in orbit or on planets) which is controlling, directing and supporting those drones. The player, on the other hand, need carriers for it.

**Comment by DingusShingleton** [comment]
Why not add an orbiting carrier that has no engines which can serve as a platform for Flycatchers? It could use the asteroid mechanics but have a station sprite, maybe a couple AMs and a boatload of drone bays.

**Comment by Amazinite** [comment]
>If they take off a planet and act as satellites, then they should never be buy-able by the player, as you cannot take off without selling them.

Why would that be the case? They're in the fighter category, meaning that the player is still able to carry them should he/she have bay space.

**Comment by KiLEdEnNis** [comment]
@Amazinite and should he/she waste them on semi-useless Flycatchers

**Comment by Rakete1111** [comment]
Oh, I see what you all mean. I'm closing this for now.
