### ISSUE TITLE
When fleet is "gathering", escorts cannot be boarded

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2310]
It seems that trying to board one of my escorts (to refuel it) is not possible when the fleet is set to gather around the flagship, as it continues to circle the flagship rather than holding still to allow boarding.

**Comment by KiLEdEnNis** [comment]
playing on 0.9.6 Steam beta, I do have the issue: my Marauder Falcon keeps circling, but I could board it w/ my Cruiser since my ship isn't slow either

**Comment by endless-sky** [comment]
Fixed in b4bccc4.
