### ISSUE TITLE
Escorts holding position no longer target enemy ships

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2311]
Apologies if this is deliberate, I couldn't find any previous discussion about this.

In 0.9.4, escorts told to hold a position would still rotate to target and shoot at enemy ships. This no longer happens in 0.9.6.

**Comment by KiLEdEnNis** [comment]
they still do fire, just not rotate?
an issue with holding position & then firing is if the escorts have weapons w/ firing force

**Comment by lheckemann** [comment]
Yes, they don't rotate to target the ships. That's the issue I'm describing, they do still shoot. As for the firing force, it should be pretty easy to compensate for that as it goes exactly in the opposite direction from the thrusters. They also already compensate when they are hit with weapons that cause movement, so I don't think that should be a major concern.

**Comment by KiLEdEnNis** [comment]
imagine an escort w/ a Heliarch Attractor or Repulsor, it may cause some issues
but it's not that relevant I guess

**Comment by Bladewood** [comment]
I do see this as a problem; it makes it hard to develop a [fortified, defensible] position.

https://github.com/endless-sky/endless-sky/issues/2147

**Comment by endless-sky** [comment]
Fixed in b912436.
