### ISSUE TITLE
AI targeting change request

### ISSUE THREAD

**Issue by zwparchman** [endless-sky/endless-sky#2313]
The current AI prioritizes weakened ships This is the right thing from an effectivness point of view, but I find it rather annoying. Unless you send a ship far out of combat any ships coming into the sector will target the same ship over and over until it is dead. This makes combat more annoying and costly. It is also weird that a ship will fly through multiple heavy warships to attack a fighter just because it took some stray laser fire.

**Comment by tehhowch** [comment]
For reference: the [weakened prioritization / healthy deprioritization](https://github.com/endless-sky/endless-sky/blob/97c1fae2e1a9ecec2d14cf44b34101f37e763b05/source/AI.cpp#L903) is fairly strong, but not as strong as the disabled-ship deprioritization
```
// Focus on nearly dead ships.
range += 500. * (it->Shields() + it->Hull());
```
At worst, this moves the apparent target position back 1000 units for full strength ships (Shields = 1 & Hull = 1). A disabled ship is moved away by 5000 units, unarmed by 1000, and the ship's previous target /parent's target is moved 500 closer.

With AI overhaul coming up shortly, the target selection mechanics are due for a revisit. A simple change that would address this specific issue would be to reduce the health-based adjustment to be comparable in magnitude to the adjustment that comes from the future position weighting. 
There is likely room for an additional weighting factor based on the current facings of the ship's turrets, and its ability to turn them all to engage the target (if using `focused` turrets). The current code does not consider the ships current facing - i.e. where its hardpoints can fire - or its ability to bring them to bear when choosing a ship target either, and adjustments here may be both frustrating (smarter opponents) and helpful (smarter escorts) to the player.
