### ISSUE TITLE
Hitting the landing key while jumping

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2314]
If you hit the landing key while jumping, the location of a landable planet in the system you are jumping to will appear in the system you are jumping from
![f4515b1016be4b7cbfd5ce831cbf1972](https://cloud.githubusercontent.com/assets/17688683/24332204/9ffdd810-1210-11e7-9579-78ee9cb3966c.png)

**Comment by endless-sky** [comment]
This seems to only happen if the planet in question is also your autopilot destination.

**Comment by endless-sky** [comment]
Fixed in 2d998a1.
