### ISSUE TITLE
Sheragi dig site outcome offered on Hope (uninhabited planet)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2317]
in short, the message with the results of the dig site got offered on an uninhabited system
![sheragi dig site hope](https://cloud.githubusercontent.com/assets/10348657/24333780/a8401968-125e-11e7-909b-391744fbc046.jpg)
didn't know Hope already had a spaceport

**Comment by Bladewood** [comment]
> Kile Dennis

k

Hope does get a sort of spaceport in Ursa Polaris, right?

**Comment by KiLEdEnNis** [comment]
I don't have UP
btw using KiLEdEnNis as first name & a " " as last messes it up

**Comment by Tadrix** [comment]
Hmm. Are mission filters like `attributes !uninhabited` or `attributes not uninhabited` or `attributes != uninhabited` possible? This would solve that problem.

**Comment by KiLEdEnNis** [comment]
making those messages not appear on uninhabited planets or planets w/o spaceports should do

**Comment by tehhowch** [comment]
@Tadrix right now, no. attributes are not handled in the same way as conditions
The way this could be solved without a code update would be to add the following to the missions that should not be offered on uninhabited systems:
`attributes "dirt belt" "human tourism" "near earth" core deep factory farming fishing forest frontier manufacturing medical military mining moon north oil paradise pirate religious research rich rim shipping	south station textiles tourism urban volcanic`

An attribute negation mechanic would certainly be more elegant and future-proof than this

**Comment by Amazinite** [comment]
You'd only need the regional attributes (dirt belt, near earth, core, etc) because every planet that you could land on would have a regional attribute, so the rest of those attributes are redundant.

**Comment by tehhowch** [comment]
I suppose it may be better as two `attribute` tokens - one for the region, and the other essentially saying "have some qualifying attribute" - making the assumption that uninhabited human planets have no other attributes

**Comment by endless-sky** [comment]
Addressed in #3106.
