### ISSUE TITLE
Using tribute to "cheat" battles

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2318]
So I'm once again coming close to the end of the Wanderer campaign and I'm at the point where the massive Kor Sestor fleet attacks Farpoint. Instead of bombing Zenith, I decided to take out the Sestor fleet. I immediately realized that my 7 automata ships, 10 Raiders, and single Derecho wasn't going to cut it, so I parked my fleet and decided to instead take a different route; what if I could simply tribute Farpoint and essentially give myself reinforcements? Well, it works, and given how tribute works, all I need to do is leave the system and come back to retribute and get an entire new batch of Navy ships to use as cannon fodder. After tributing about a dozen times, the Navy was finaly able to take down the Sestor fleet, and entirely without me at that fact since I needed to stay cloaked the entire time.

A situation like this is probably not the only situation where this could be done. I imagine that while fighting on the side of the Navy or the Syndicate in the future, fighting on home field would give you a really good advantage by just tributing your own planet then either bribing your own planetary fleet or skidding your way past the system boundry and letting the battle play out. This can't be done right now for the FW story though because FW worlds have militia defence fleets, which aren't enemies to the Navy or Syndicate.

I think a way to fix this would be to have an event trigger at the beginning of the battle that disables the planet's defence fleet, similar to how system fleets are changed for a battle to assist the player's side.

**Comment by endless-sky** [comment]
I suppose this could be fixed by making demanding tribute always reduce your reputation with a government to below 0. Then you wouldn't do it for frivolous reasons.

**Comment by Amazinite** [comment]
Have fun everyone who pads their Syndicate rep by killing Korath ships then dominates all of Syndicate space while keeping them friendly.

**Comment by Bladewood** [comment]
Make demanding tribute an atrocity?

**Comment by Amazinite** [comment]
Makes sense to me.

**Comment by endless-sky** [comment]
Fixed by making it an atrocity to successfully dominate a planet (089bc1c). Simply demanding tribute still just provokes the government, because someone might do it by mistake or just to see what will happen.

**Comment by KiLEdEnNis** [comment]
maybe make it that you can't bribe tribute fleets (and their entire government when doing a tribite)

**Comment by Bladewood** [comment]
... So, wait, if I demand tribute from the world to attempt OP's scenario, I just have to never talk to the world to keep my reputation?

**Comment by tehhowch** [comment]
Perhaps tribute cannot be invoked if there are hostiles (to the planet government) in system? `"We've no time for this nonsense"`

**Comment by endless-sky** [comment]
Oops, I guess that doesn't really address the original problem.

**Comment by tehhowch** [comment]
It's still a great add - really makes it clear that tribute is for end-game.
`"Oops, angered this entire civilization"`
😨

**Comment by Amazinite** [comment]
@endless-sky Yup. :|

**Comment by endless-sky** [comment]
Well, I guess that's what auto-saves are for. Plus, in most situations you would quickly discover that planets are not letting you land even after you leave the system; the only problem would be if someone demands tribute on a Syndicate world, say, then jumps to a Republic system and doesn't realize the entire Syndicate is mad at them.

Changed in commit 7675eb7. It'll only reduce your reputation to -1, so in the worst case you just need to go off and kill some pirates to prove you're an okay sort of person who just made a silly mistake.
