### ISSUE TITLE
Anti-missiles try to shoot at enemies

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2319]
Sometimes while an enemy ship flies close by, AM will try to shoot at it until that enemy is out of range.

While it would be nice addition for the AMs to behave this way when no missiles are nearby (and deal some moderate damage), currently AFAIK it has no effect, and so they shouldn't waste energy and increase heat by doing so.

**Comment by Bladewood** [comment]
I've never experienced this before. Do you have a save that can (somehow) consistently replicate this?

As an aside, I've always wanted a turret that doubled as an anti-missile and as an offensive weapon, similar to the weapons on Chmmr zapsats in Star Control 2. Unfortunately, it is not possible to recreate such a device in Endless Sky.

**Comment by Amazinite** [comment]
Are you sure that the ships that are getting close just aren't firing missiles? I'm not seeing this occur.

**Comment by gunqqer** [comment]
I can't replicate this but as a new feature it might be good

**Comment by Tadrix** [comment]
I saw it about 3–4 times (definitely not every time, and most often it happened when the enemy was a small ship, like drone of fighter), and no, currently I can't (since I no longer have these saves and I don't know how consistent they would be).
> Are you sure that the ships that are getting close just aren't firing missiles?

I was thinking of it, but I didn't see missiles and AMs were going crazy, like shooting down a missile which just wouldn't die. I can add that I was playing 0.9.4 at that time (I'm making this issue, because I didn't notice any commits which changed how AMs work) and used Hai, Korath and Quarg AMs, mostly Hai.

**Comment by gunqqer** [comment]
It would be good for anti missiles to get an update. Beam weapons should have a very low anti missile (so like, 1 antimissle) and anti missiles should deal very low amounts of damage based on their level of anti missile.

**Comment by Tadrix** [comment]
Nay, it wouldn't work this way. Consider a beam weapon like you would consider a weapon firing 60 times in a second. "1 antimissle" means no missile will ever be destroyed (because missiles have larger strength), and missile could be destroyed (for example, anti-missile 20 and missile strength 20), it wouldn't stand a chance (because on average laser turret would destroy it 3 times per second). So adding anti-missile properties to lasers is a bad idea.

Doing it the other way round, however, would work nicely. Just give beam laser turrets's damage to anti-missile, and heavy laser turret's damage to heavy anti-missile. AM fires for 1 frame (1/60th of a second), then reloads. LAM fires 7,5 times per second, HAM fires 10 times per second. So, using laser turret's and heavy laser turret's damage they would deal:
Anti-missile: 15 dps to shields, 19,5 dps to hull;
Heavy anti-missile: 36 dps to shields, 48 dps to hull.
Not very much, seems to work very well.

**Comment by KiLEdEnNis** [comment]
did those ships use any secondary weapon at all? (even gatling guns)

**Comment by DingusShingleton** [comment]
If anything, I would say that an AM should have comparitively massive hull damage relative to their shield damage. After all, they would be designed for maximum armor penetration since missiles don't have shields. On that note.... shielded missiles O.O

**Comment by KiLEdEnNis** [comment]
if a launcher could spawn & shoot ships (& not in the way like my Bow mod) that blow up on impact, maybe

**Comment by gunqqer** [comment]
If AMs do get any sort of damage hull damage should be 3-4x more than shield

**Comment by MessyMix** [comment]
Side question: do gats attract AM? If so, then maybe that was what had happened.

**Comment by Tadrix** [comment]
@KiLEdEnNis Maybe, didn't pay attention. I think it weren't always pirates with gatlings who were triggering AMs to fire like the world is ending (but also fighters, drones (incl. alien)), but I can't be sure now.

In any case, AMs trying to counter Gatling guns would be strange in its own right, but I'm kind of seeing why could it happen. AM's see bullets as missiles, right?

**Comment by Wrzlprnft** [comment]
yes, AM shoots at the gatling gun fire.
it's part of why the gatling gun is so strong, equip something like typhoons on the carrier, and you can sneak them by because the AM is busy with the gatling fire (in theory).

**Comment by Tadrix** [comment]
Closing this one, will reopen if it becomes clear that AMs are targeting ships themselves and not gatling bullets.
