### ISSUE TITLE
Add bunk rooms to alien outfitters

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2320]
(The following may or may not apply to the Coalition, the Hai, etc.)

Wanderers now have their own unique jobs.
That is fine.
Those jobs tend to have absurd requirements, such as 300+ passenger capacity, larger than that of even a bactrian.
That is also fine. (Maybe.)

The problem here is that it is difficult to raise your passenger capacity in Wanderer space. Wanderer ships are relatively expensive, so you can't just buy more of them, and you cannot maximize crew capacity on your own ships, because there are no bunk rooms available in the outfitters.
Also, the Wanderers do not have dedicated transports, only freighters. (Ignoring Deep River Transports, because those are just repurposed freighters, and they cannot be obtained without attacking the Wanderers during certain missions.)

You can always go to human space, of course, but that takes too much time.

I think we should add bunk rooms to Wanderer outfitters (and other races' outfitters as well, if they too have such absurd requirements).

**Comment by gunqqer** [comment]
Yes bunks need to be added to alien outfitters. A lot of things should be added to alien outfitters, basic stuff, but that's another topic.

**Comment by Tadrix** [comment]
The (lore-wise) problem is that aliens most likely produce _their_ version of bunks. For larger races they would be enormous (giving less bunk space per outfit space), for smaller (like Hai), on the contrary, smaller (givin perhaps 5 per 20 t outfit space, but you couldn't comfortably accommodate human passengers and crew with them).

Human bunks should be added to Hai outfitters. After all, humans live in their space for a century now.

In the case of Wanderers, maybe just let player purchase Deep River Transports?

**Comment by Amazinite** [comment]
>The (lore-wise) problem is that aliens most likely produce their version of bunks.

*In walks the Hyperdrive*

**Comment by Tadrix** [comment]
> _In walks the Hyperdrive_

Explain, pls?

**Comment by Amazinite** [comment]
All the races use the same Hyperdrive design.

**Comment by Tadrix** [comment]
You mean, same outfitter picture. Hyperdrive's function doesn't rely on user anatomy, so they all are producing variations of more or less the same.

**Comment by Bladewood** [comment]
Oh, no, not this again...

**Comment by Amazinite** [comment]
>You mean, same outfitter picture. Hyperdrive's function doesn't rely on user anatomy, so they all are producing variations of more or less the same.

Then why wouldn't the same be true for bunks? You can only fit so many people (beings?) in a single space, and all of the sentient species in the game are described as being around the same size, so I don't see what bunk rooms from different species would need to have different designs and functionalitites, just as the Hyperdrive is now.

**Comment by Tadrix** [comment]
In any case, how about adding bunks to Hai outfitters and adding Deep River Transports to Wanderer shipyards? There's no reason for them to not be sold anyway.

**Comment by Bladewood** [comment]
People, let's not forget that the Kor Efreti sell generic bunk rooms.

A description of the Korath is given in the now-removed Korath First Contact mission on Far'en Lai.

**Comment by Amazinite** [comment]
>A description of the Korath is given in the now-removed Korath First Contact mission on Far'en Lai.

For reference

>They are short, stocky, and somewhat reptilian in appearance, and both have a crest of red and brown feathers running along the top of their heads and hanging down their backs. Their clothes are a brightly colored patchwork material. They do not seem to be armed...

**Comment by Tadrix** [comment]
Yup, I was originally going to add that Korath Basics should get bunks too, but they already have these (and a bunk is included in a Command Center outfit too, so this is consistent).

In any case, Wanderers design their ships to have a small crew, so they didn't see the need for extra bunks. And when they needed, they rebuilt Deep Rivers (instead of using Mass Expansions and Bunks). This suggests they usually don't use such modifications.

**Comment by Bladewood** [comment]
*Ahem.*
The difference between the deep river and the deep river transport is like that of the argosy and its modified version. Notice how the modified argosy has much less cargo capacity, even though it has no mass expansions. Consider all of the Marauder ship variants as well.
Besides, the deep river transport was designed exclusively for the purpose of transporting refugees from planets experiencing war.

**Comment by Tadrix** [comment]
> Besides, the deep river transport was designed exclusively for the purpose of transporting refugees from planets experiencing war.

So after Wanderers stopped losing their planets to war, there suddenly were many unneeded Deep River Transports. I don't see any reason for them not be sold at this point.

**Comment by Amazinite** [comment]
The Deep River Transport practically is just a Deep River with a bunch of hidden mass expansions and bunk rooms.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/24337765/2ca59b24-126e-11e7-8652-5363f0680e35.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/24337766/2ca5a7a4-126e-11e7-8172-ce332b34b0c5.png)

**Comment by Tadrix** [comment]
It is not — take a look at mass, speed, acceleration, turrets, cost… and differences will be much more apparent if modifications will affect hull integrity, so it seems that Wanderers rebuilt those ships instead of showing outfits into them.

At least that's the only reason I can think of why M.Z. would make these "expansions" and "bunks" hidden.

**Comment by Amazinite** [comment]
> so it seems that Wanderers rebuilt those ships instead of showing outfits into them.

That is what they did, but the two ships don't look the same because mass expanders are not perfect converters. Using mass expansions on an existing ship is making it do something it isn't suppose to, but creating that ship from the start to do that thing is more efficienct. They're still the same ship with essentially the same amount of space, so the Deep River Transport really is just a Deep River with mass expansions and bunks, but because the Deep River Transport was made that way it suffers none of the downsides that adding mass expansions or bunks gives.

**Comment by Tadrix** [comment]
Yep, but my point is: It's always faster to try to mod an existing ship with ready conversion kits (outfits, in other words), then building a new, dedicated ship. If they needed transports in a hurry, and they had bunk outfits at their disposal, they would just shove expansions and bunk rooms in and use them, at least in the beginning. They modified existing _design_ instead and built new ships. This suggests they do not have such outfits even for themselves, so they can't sell them either.

**Comment by endless-sky** [comment]
Fixed in 5181022.
