### ISSUE TITLE
Feature request: Guard command key combo

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2321]
Use key combination for right click guard function; example: alt+right click.

I am finding I want to position certain ships inside a group of stationary ships, but it is devilishly difficult to do so due to the game assuming the guard command when you click anywhere near another ship of your fleet. Lets make right click only for the hold command, and use a key+right click for the guard command.

**Comment by Bladewood** [comment]
I'm not sure if I agree with your particular resolution, but I have experienced a similar problem, so +1.

**Comment by endless-sky** [comment]
Unfortunately, double-click is currently the shortcut for boarding a ship.

**Comment by wambat1** [comment]
Ok, I don't think double-click would be necessary in this case.

**Comment by tehhowch** [comment]
The recent (compared to this issue) change from Gather to KeepStation for the right-clicking of friendly ships essentially accomplishes this request IMO.
