### ISSUE TITLE
Feature request: Shortcut for selecting all of one ship type

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2322]
"some key" + double click (or whatever) = select all of that ship type. For use in Player Info, Shipyard and Outfitter screens.

**Comment by KiLEdEnNis** [comment]
or double clicking a ship?

**Comment by gunqqer** [comment]
Would "all type  of one ship" select just the hull type or everything having the same outfits?

**Comment by wambat1** [comment]
hull type

**Comment by Wrzlprnft** [comment]
i'd prefer same outfits.

**Comment by Bladewood** [comment]
Hull type would be better imo, because I do not use very standardized designs. (Not on my latest save, at least.)

**Comment by jafdy** [comment]
Unless you have lots of different kinds of ships you could always put the sets of ships on the number keys.
