### ISSUE TITLE
Autopilot reverse thruster simple fix

### ISSUE THREAD

**Issue by DerbinKlamz** [endless-sky/endless-sky#2324]
So, for anyone who's having issues with reverse thrusters, the answer is simple: use weaker steering and engines. I'm not sure if the inconvenience is due to both or just one of them, but if the AI recognizes that it can stop faster by turning around (which wastes more time than it saves) then it will not use reverse thrusters. I believe it is just steering, nut please correct me if i am wrong. I find reverse thrusters most useful for jumping quickly from one system to the next, otherwise, I have not considered combat or anything other than jumping. Feedback welcomed

**Comment by toilethinges** [comment]
This is not the right place for this kind of post. Better posted on the Google group ( https://groups.google.com/forum/#!categories/endless-sky ) or the Steam forums ( http://steamcommunity.com/app/404410/discussions/ ).

**Comment by Amazinite** [comment]
>(Please close this issue.)
