### ISSUE TITLE
Deep Republic fleets use Navy hails; they probably shouldn't

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2326]
Edrick describes the Deep as having been able to retain the ability to police itself when it joined the Republic, and therefore the Deep Republic ships are not part of the Navy (hence why they're all prefixed D.S.S for Deep Security Ship and not R.N.S for Republic Navy Ship), so I don't really think it makes sense for Deep Republic ships to be advertising joining the Navy and talking like they're in the Navy ("The Navy is here to protect and serve!").

I get that this occurs because the D.S.S and R.N.S ships are under the same in-game government and therefore share the same hails as per governments.txt, so to change this would require the Deep, or at least their ships, be made their own government akin to the Syndicate being part of the Republic but also its own government. I'd be willing to throw in some hails and do some changes to the FW events to accommodate the new government if we want to go through with this and it isn't considered too much for the sake of hails.

**Comment by toilethinges** [comment]
...per-fleet hails?

**Comment by Amazinite** [comment]
Could work too.

**Comment by Tadrix** [comment]
Not necessarily. You would need just one more line for a fleet: to specify which list of hails should a fleet use. If no such line, use respective government's default hails.

**Comment by gunqqer** [comment]
So an override hail that is only used if specified? I like that. Add some spice to fleets of pirates

**Comment by endless-sky** [comment]
Hails used to be per-fleet, but the issue with that is that then every single ship needs to remember what hails it uses (because once a ship is created, it doesn't know what fleet definition it came from). For something that's really just for flavor, the complexity it added just wasn't worth it.

**Comment by KiLEdEnNis** [comment]
maybe do the " Republic " think for the Deep & make them friendly to each other so the behaviour doesn't change
that or make them their own "Deep Sky" government

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/f78dc58eef97c48dd4499b6185922b00539e1424
https://github.com/endless-sky/endless-sky/commit/590d6eddef588db4e87f838eb63407b66a882f01
👌
