### ISSUE TITLE
Anti-missiles shouldn't react to Gatling gun fire

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2328]
What it says on the tin; I don't know about gameplay, but realism here goes out of the window. Shouldn't gatling be in guns section?

**Comment by Amazinite** [comment]
>Shouldn't gatling be in guns section?

They require ammo, so no. And if you're going to open a new issue then you might as well close the other one.

**Comment by Tadrix** [comment]
By convention infinite ammo is only for weapons which consume pure energy, right? This makes sense.

Then question remains only about AMs reacting to something they shouldn't.

**Comment by MessyMix** [comment]
>realism here goes out of the window
Okay, hang on. AM targets anything physical that it could possibly shoot down. I don't know how AM works in game, but it seems to be a laser of some sort that ablates any physical projectile.

You can shoot at a missile, because it's made out of metal or some other _thing_. Can you AM a heavy laser? No. Can you AM a plasma cannon? 'prolly not (what good would shooting a laser beam at plasma be?). Can you AM a proton gun? _no_, because protons are smaller than the wavelength of light, which is why we can't see them even with the strongest microscope, and probably a whole host of other reasons. Why can we see protons in-game, then? Well, apart from some scientific reason that could probably be lored into the game (some nuclear version of the photoelectric effect / quantized energy states, I would assume), for gameplay's sake, primarily. The same holds true for a particle cannon.

I can shoot a bullet with an accurate vaporizing laser; it will shrek the bullet. AM works on bullets, end of story.

**Comment by Tadrix** [comment]
> Can you do so for a plasma bolt? 'prolly not (what good would shooting a laser beam at plasma be?).

https://en.wikipedia.org/wiki/Plasma_(physics)#Filamentation
I'm not a scientist, but if I understand correctly, by using laser you can make this plasma bolt ineffective by shaping it into filament away from yourself.

> Also, balance and gameplay—their intention was so that you could multiply the effect of missiles by having you distract enemy AM systems with bullets.

It would be weird (not to say unrealistic). In our time we have [CIWS](https://en.wikipedia.org/wiki/Close-in_weapon_system), which react to missile, but don't react to bullets. Remember, to destroy the missile you need to detect that missile. It probably is much better detectable with a radar then a bullet. Even if radars could detect incoming bullets and AM could react to them, it wouldn't bother. By design. It is anti-missile, after all, its task is to destroy missiles (and not cheap bullets spammed to overwhelm the system).

Gatling gun is a very old weapon, while anti-missiles were improved for centuries. You're basically saying that engineers at Lovelace Labs are idiots. This isn't "gameplay over realism" situation. This is "immersion breaking" situation. If their sophisticated self-defense systems can be defeated by some punks with outdated weaponry, well, you shouldn't buy anything from those morons then.

If the game needs something to defeat AMs with, much more plausible solution would be decoy rockets.

**Comment by MessyMix** [comment]
>Over a millennia later, this modern incarnation of the gatling gun sees action in the stars, a testament to its fundamentally robust design.

>Gatling gun is a very old weapon, while anti-missiles were improved for centuries.

You didn't _really_ expect crew to be hand-cranking a rotary barrel machine gun in space, did you!?

**Comment by Tadrix** [comment]
You are aware that Gatling-type cannon is a term for a [rotary cannon](https://en.wikipedia.org/wiki/Rotary_cannon), right? Good luck cranking by hand a Minigun, a Vulcan or a GAU-8 on a contemporary fighter jet? This reduction to absurdity isn't even funny. Or I'm just tired tonight, I don't know. >< Anyway, you wrote it yourself, it's a millennia old design. Defeating AMs. Seriously? Shit, Lovelace has a problem.

**Comment by MessyMix** [comment]
![image](https://cloud.githubusercontent.com/assets/20450076/24432783/6a4a4bca-13f2-11e7-8dea-3527f4ef2b80.png)

**Comment by Tadrix** [comment]
Ok, according to you, they _are_ cranking it. And, judging by outfitter images, they are using same ammunition with casings (by 31st century they would use caseless for a long time). So, yep, it's an old design defeating Lovelace AMs. For which they keep trying to invent better missiles to counter their AMs. Nobody will buy those, I suppose. Gatling will do the trick. :D And these AMs are no good anyway, systems from their time didn't become useless because of them.

As I said: Lovelace has a problem.

Only way this wouldn't be absurd if Gatlings from 31st century would be radically different, but then they:
1. Wouldn't be named Gatlings;
2. Wouldn't look like the old Gatlings;
3. And their description wouldn't mention that this robust design is ancient.

If it looks like a duck, swims like a duck, and quacks like a duck, and you say it isn't a duck, then I don't know what it is.

**Comment by Amazinite** [comment]
>it's an old design

An old concept, not an old design. Same as missiles.

**Comment by MessyMix** [comment]
I feel like you're missing the forest for the trees.

They _aren't_ cranking it in space. It is a MODERN INCARNATION of a millennia-old design. My point was that 19th century gatlings weren't defeating constantly improving AMs. 31ST century gatlings are defeating AMs! The rotary barrel is the design that remains. The firing mechanism is prolly completely reformed, and the housing made out of better materials.

1. They are named gatlings
2. They look like old gatlings
3. Their description mentions that the robust design is ancient.

Guess what? We still use knives in the 21st century! They've been around for millennia, but they've gotten better! (gats) They can now defeat steel plate armor! But plate armor has evolved, and now stab vests are a thing! (AM improving) Oh wait, we now have better blades, made out of better materials! (gats).

Old concept, new incarnation.

**Comment by Tadrix** [comment]
Right.

> They _aren't_ cranking it in space.

I didn't imply they were. Guess you didn't get my sarcasm.

Ok, blades and armor you're talking about is hi-tec and expensive thing. You don't have such knife in your kitchen. Most of us most definitely don't have such items in our possession. And this kind of protection also isn't something you are seeing in the streets very often.

So the position you are defending is something opposite. You're portraying a world where all armed people use these expensive hi-tec knives, and all protected people use stab vests which protect against those knives. Meanwhile, thugs in back alleys are using ordinary shivs, which for some reason are able to punch through those ultramodern stab vests. This situation is seen everywhere, every day (remember all those pirate encounters?). Meanwhile, people _still keep buying those same compromised stab vests_ and corporations try to invent better blades, like nothing's happening.

Geez.

**Comment by MessyMix** [comment]
No, the stab vests aren't compromised, but they are softened such that higher-tech weaponry _can_ surpass the vests.

This has become a conversation fit for Discord. I feel like every similar thread devolves into some form of bickering and/or arguing about the smallest of issues that really aren't pressing problems.

**Comment by gunqqer** [comment]
Yeah this whole talk isn't mostly useless so I'll try to sum up what I think from ither's ideas

So from what I gather the Gatling gun is a 20th century weapon updated minimally to be effective on a ship but not much more and not updated much. The Lovelace Antimissile is worked on tirelessly every single day with tests as fast as possible. Which means that antimissile is far superior Tech-wise to the Gatling so it is reasonable to assume that AM could ignore bullets.

**Comment by jafdy** [comment]
>https://en.wikipedia.org/wiki/Plasma_(physics)#Filamentation
I'm not a scientist, but if I understand correctly

You don't understand correctly. The effect is present at atmospheric pressure (not a vacuum), in a laser the effect is focusing it.

>I actually think this gameplay mechanic is nice

Then stop trying to change it!

**Comment by Wrzlprnft** [comment]
if it breaks immersion for you, we need to come up with a plausible explanation and put it inside a side mission.

i personally see it more of a feature of Lovelace work: they even can detect bullets (which are probably a quite bit more hefty than the imagery suggests, the main difference is that they do not explode). so they can advertise that if a fighter breals through your close range defence (which turrets are supposed to be i guess), their AM can even help there!

**Comment by gunqqer** [comment]
Shooting a missile will make it go boom easily. Shooting a bullet.... you're just shooting depleted uranium and tracer rounds. It would make sense that Lovelace labs could make something that can see the difference between a bullet and a missile. Unless missiles are much smaller than I thought and bullets are self propelled... which they aren't.

**Comment by Tadrix** [comment]
> which are probably a quite bit more hefty than the imagery suggests

@Wrzlprnft Nice explanation, but you mean, like javelins? Javelin is 20 times more massive than Gatling bullet. (For unguided slug size of a missile Gatling guns have insane ammo capacity.)

Next time survivors of a fight are angry about anti-missiles going for Gatling burst and ignoring that big, fat torpedo ominously closing in, customers will ask Lovelace to make their AMs prioritize their targets (besides, how AMs are able to determine which way bullets are going? they do not home like missiles do). One more thing — AMT has a ROF of 450 rpm, a HAMT has ROF of 600 rpm, while Gatling gun has ROF of 1200 rpm. It is obvious that one Gatling renders two AMs useless while potentially dealing less dps than most missiles. If I'd be a starship captain, I would turn off bullet-seeking capability in my AMs until it would be clear that my enemy doesn't have missiles and would rely on my shields instead to protect me from bullets. And, if I couldn't do that, I'd write a letter to Lovelace asking to, please, stop making their AMs useless against pirates.

> Then stop trying to change it!

@jafdy Sadly, for now I perceive it doing a lot more harm than good for play experience. Seriously, I'd like for each of us to get what we want, but AM distraction thing should be done by something which is not a weapon used primarily by pirates and not navies. Otherwise engineers at Lovelace indeed seem to be idiots unable to make basic calculations and making their customer even more vulnerable.

AM isn't just distracted. It becomes a liability and a weakness you can't turn off. Here's the basic math:
To try to neutralize 4 bullets, it must shoot a minimum of 4 times, wasting 40 energy and producing 20 heat.
Meanwhile, to regenerate 3 * 4 = 12 damage shields sustained from these bullets they need just 12 energy, using most ineffective and cheapest human shields possible.
If my ship can use this energy to, you know, run away or maybe shoot at pirates, I rather not let AMs sap it to destroy bullets. The pirates always will have more there they come from.

In other words, once Gatlings are involved I can just as well ask an ally to shoot my AM off my ship and try my luck fighting without it, it's so bad. In-universe, it's a big problem.

**Comment by endless-sky** [comment]
Fixed by making gatling bullets not count as "missiles" (7babf3a). That also fixes the fact that they create a huge cloud on radar that makes it hard to see where the *real* missiles are.

**Comment by KiLEdEnNis** [comment]
doesn't that make them a lot worse to use though? they did disable AM's a bit

**Comment by gunqqer** [comment]
Gatling guns were never really good to begin with. I've tried to use them and even with a very early ship it just doesn't do much. Most projectile based weapons (either missile shot or non continuous) really are meh to me due to the fact they have travel time. A turret variant of the Gatling gun would be nice and help make it be used more but... eh
