### ISSUE TITLE
Fighters and drones seem to be trying to board disabled carriers

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2329]
I've been noticing this a lot lately, especially when fighting Korath Raiders. I'll disable the Raider, then the Chaser(s) will look like it's either trying to repair or board the Raider (without actually being able to do anything), causing my escorts to fire at and destroy the Raider while trying to hit the Chaser. Only then does the Chaser start acting normal again, after the Raider starts exploding. I noticed this a few times with Sestor carriers as well.

**Comment by gunqqer** [comment]
Oh i just realised that drone can't repair (or shouldn't be able to) but the chasers go for the raider... huh yeahi can confirm this happens

**Comment by lheckemann** [comment]
Aren't the Chasers fighters, not drones, and as such are and should be able to repair ships? I've seen Lances repair their Carrier motherships as well as Chasers repairing Raiders.

**Comment by Amazinite** [comment]
That was before one of the recent commits that restricts drones and fighters from repairing.

**Comment by lheckemann** [comment]
857740ebd02d2d7090862ad85b763fc6cd5499c6 for reference

**Comment by endless-sky** [comment]
Fixed in 6f09079, and also made it possible for fighters to flee from a disabled mothership.

**Comment by Bladewood** [comment]
Okay, that handles the absurd scenario where I capture a carrier with docked fighters/drones.

**Comment by endless-sky** [comment]
I think I may also make it so that if you *do* succeed in capturing a carrier before all the drones escape from it, you capture the drones as well. But that would be nearly impossible, now.
