### ISSUE TITLE
Scanning has no effect

### ISSUE THREAD

**Issue by hallister** [endless-sky/endless-sky#2330]
I'm currently attempting to complete the FW Recon Mission 2 and installed an outfit scanner in a Bounder and starting scanning. I get the "Attempting to scan..." but a successful scan never occurs. In order to test if it's the mission itself or some sort of bug with scanning, I installed 5 outfit scanners and attempted to scan multiple ships (ranging from shuttles on up) and all I ever receive is the "Attempting to scan..." message.

**Comment by Amazinite** [comment]
Hold the scan key. 

>(Please close this issue.)

**Comment by hallister** [comment]
Thanks lol. Never saw this anywhere.

**Comment by Bladewood** [comment]
It's a recent addition. Scanning takes time now.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/blob/master/changelog#L134
