### ISSUE TITLE
Auto aim + fire can track cloaked targets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2331]
Title says it all. If you have auto aim and auto fire enabled, then your ship will point toward the location of a ship that is cloaked if you targeted them before they cloaked.

**Comment by Bladewood** [comment]
it's neat.

**Comment by Bladewood** [comment]
it's neat.

**Comment by jafdy** [comment]
It's a bug. @Bladewood

**Comment by Bladewood** [comment]
I am aware.

I just wanted to note that it was neat.

**Comment by gunqqer** [comment]
That that is interesting. Currently it doesn't matter as much because there are only 3 enemy ships that have them but this should be fixed if cloaking is ever used more extensively

**Comment by endless-sky** [comment]
Fixed in 3cf5f95.
