### ISSUE TITLE
shouldn't ammo storage take up weapon capacity? [balance]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#2332]
it seems like you might have trouble shooting ammo that is located in the storage rack next to the fusion reactor...

**Comment by gunqqer** [comment]
Ammo storage takes up a lot of space, many tons of space. It isn't not unreasonable to think that space is used for an ammo line to the gun

**Comment by LocalGod79** [comment]
you're missing the point - all ammo based weapons occupy hard points.  if the AR120 Reverse Thruster takes up weapon space because it needs to be located at the front of the ship, it stands to reason that ammo storage would follow the same rules...

**Comment by Tadrix** [comment]
Ammo storage could occupy weapon space = (its outfit space / 2) rounded up. It would acknowledge both that storage itself doesn't need to take up weapon space, but ammo delivery lines do.

**Comment by KiLEdEnNis** [comment]
instead maybe make a longer reload after launchers are empty? where they'd fill up the launcher w/ the storages, when the launchers are empty, repeat
I'd prefer this over the weapon space thing, it'd make storages shit

also

> isn't not unreasonable

**Comment by gunqqer** [comment]
Currently weapons that require ammo are at the bottom of my list of being used (other than finishers which are OP). If putting more ammo took weapon space that would make me never use them because I could have enough ammo. Having a short reload time when the main launcher runs out may be good but I think it is fine as it is.

**Comment by LocalGod79** [comment]
@gunqqer currently, weapons that use ammo are more outfit space/energy/heat efficient than their counterparts (often by a wide margin), and if you choose to avoid them (for whatever reasons) that's your choice.  you're not alone - ammo costs credits, and you have to visit outfitters who will automatically sell you reloads they carry - inconvenience balance points to their combat efficiency that many can't be bothered with.  sounds a bit like fighters/drones...

that said, ammo capacity is a balance point within secondary weapons, and these outfits don't generate any heat or reduce the cooling efficiency of the ship (so ~~mass~~ outfit expansion nerf loses some of its potency)

i'm not arguing with you - i'm trying to explain why they're not "fine as it is".

@Tadrix's suggestion of a partial weapon capacity occupancy seems reasonable. perhaps generating a very tiny bit of heat (feeding/loading mechanisms?) might keep massive outfit expansioned combat ships from becoming a thing again...

**Comment by KiLEdEnNis** [comment]
heat or weapon capacity seems very weird to me, and I repropose my idea of a longer reload to "refill" the launchers

**Comment by Amazinite** [comment]
I think if anything, an energy requirement makes more sense than heat generation. I'd be fine with having ammo storage use up weapon space, but it would probably be less than the outfit space.

**Comment by gunqqer** [comment]
I'd be fine with it requiring some extra energy, but I would want it to only use ammo when 'reloading'. Reloading would be when the main launcher runs out of ammo and ammo from the other storages is used

**Comment by Amazinite** [comment]
In that case, there'd need to be some sort of UI indicator that your weapon has run out of ammo and is spending time restocking from storage.

**Comment by KiLEdEnNis** [comment]
add a small "segmented bar" (like the hyperspace fuel) next to each icon? although, might as well just use 1 full bar since weapons have like 40+ ammo & having a bar w/ 40+ stripes isn't gonna work

anyway do we agree the longer reload thing seems like a good fix? (idm energy usage but seems weird to me)

**Comment by DingusShingleton** [comment]
Each bar is 1 full reload

**Comment by Amazinite** [comment]
>idm energy usage but seems weird to me

Energy to make loaders work.

**Comment by KiLEdEnNis** [comment]
but the storages are the storages, not the loaders, if it's done automatically I'd say the launcher has autoloaders instead

**Comment by Amazinite** [comment]
They still end energy to get the ammo from the storage to the actual weapon.

**Comment by jafdy** [comment]
What about having the launcher hold an amount of ammo and the storage restocks the launcher at half the rate that the shots are fired. It would avoid the clip type things (and there will be no demands for a reload key).
If only one storage per launcher is used then there should be no effect but more then that and there will be a slow down in the firing rate for continues fire.

**Comment by gunqqer** [comment]
+1 Jaffa, I like that. Avoids needing more UI elements (except some sort of reload for any weapon that shoots less than 1 time a second would be nice and if we had a reload bar like that for all weps restocking the ammo would be another's bar but let's save that for another issue) and balances the realism. Some base energy requirement to 'restock' should be implemented along side it.

Now back to UI... would the number in the launcher and the number in storage both be displayed or what?

**Comment by jafdy** [comment]
Would need to be a bar as a number could flicker if you had continuous reloading.

**Comment by LocalGod79** [comment]
on the subject of new ui elements: chart junk.  no, thank you.

who wants to code storage rack reloading to M.Z.'s satisfaction?  and energy requirements?  so i have to sell *another* outfit before i can swap my power?

let's keep it simple (and use the tools already available to us in a way that is going to inconvenience players the least) - some weapons capacity, and a little bit of that new cooling inefficiency? (it's location could compromise/require additional cooling in key areas - e.g. the guns)

**Comment by Tadrix** [comment]
I too think that slower reloading is a good idea (contrary to _more_ cooling inefficiency).
Ammo storage could start loading the moment launcher isn't full, and do it until the launcher is full again (or there's no ammo to load); during this it would consume minimal amounts of energy and generate some heat. To load one projectile it would take 2,3× of time it takes to shoot one.

**Comment by Amazinite** [comment]
>and a little bit of that new cooling inefficiency?

I feel like people are going to start going too crazy over this attribute now. Honestly, you could make the location argument about a lot of outfits, but that doesn't mean that a lot of outfits should have the attribute. If no energy requirement, then just a weapon capacity requirement seems fine to me.

**Comment by gunqqer** [comment]
yeah I don't like cooling inefficiency as it is, I don't like missiles/ammo required weapons, if you mix the two it makes missiles even more unattractive. Honestly it is fine as it is and the only thing I would agree with doing is make it create minimal heat and/or use minimal energy. Any more than that and every ship with missiles and ammo storage would require a complete rework (There are ships with ammo storage, right?)

**Comment by Amazinite** [comment]
No ships spawn with them, but it could be a concern for players who have them.

**Comment by KiLEdEnNis** [comment]
> Any more than that and every ship with missiles and ammo storage would require a complete rework (There are ships with ammo storage, right?)

I did make a PR, got no feedback from MZ & closed it
so no, at least not yet, until someone else bothers doing it, I'm not gonna update my PR if it's not gonna get merged anyway

**Comment by endless-sky** [comment]
The only reason to make ammo storage take up weapon space would be if it seems to be over-powered as it is. I'm not sure that's the case right now, because the launcher's rate of fire still limits how much damage you can do.

**Comment by gunqqer** [comment]
Currently I don't think ammo cap ups are over powered. Really, because I dislike missiles in general having cap up makes them possible (but not likely) options for me to use. It's just annoying to have to go to Wanderer space and buy more ammo, or need to find and kill a coalition (or what ever they are called) war ship that hasn't fires all of it's missiles. Technically that last part isn't intended because I'm not supposed to have their weapons...

**Comment by KiLEdEnNis** [comment]
@gunqqer side note: Finishers have no storage pod (yet)?

**Comment by gunqqer** [comment]
Made a small plugin with them. No texture or anything and not the best balance but the best I cared for

**Comment by VonZorch** [comment]
Suggestion on this.  Automatically reload any launchers from ammo in cargo or storage racks, crates and what have you on landing or during hyper jumps.  Ammo in cargo should probably only reload when on a planet.
The storage units would be placed near the weapons they serve and include the transfer equipment needed, but it would all be manual and need much of your crew, can't be done in combat.
Add magazine extensions that do take up weapons space.  These add directly to the launchers ammo capacity.
