### ISSUE TITLE
Wanderers not patching up each other

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#2335]
i've seen this at multiple points in the wanderer storyline: as soon as a space battle is over, the disabled wanderer ships don't get patched up by anyone but the player (if he chooses to do so), even though there is the "normal" traffic of wanderer ships that travel in and out of the system.
this also happens to non-mechanical ships (tempest etc.), and it has probably nothing to do with fleet mechanics, since wanderer ships from the same defense fleet that have been patched up stay close to the player instead of helping their fellow warriors.

**Comment by jafdy** [comment]
Could the flycatchers be blocking boarding attempts? That is to say they are trying to repair the ship but can't thus preventing other ships from trying.

**Comment by Amazinite** [comment]
Maybe, because I have seen Wanderer ships repair eachother.

**Comment by MCOfficer** [comment]
possibly, but i happened yesterday evening/this morning, and the for #2174   is 7 days ago.
(yes, i play the source code, not 0.9.6 stable)

**Comment by Bladewood** [comment]
It's happened to me before; the last time was not too long ago.
Not sure if it still happens after https://github.com/endless-sky/endless-sky/commit/857740ebd02d2d7090862ad85b763fc6cd5499c6.

**Comment by endless-sky** [comment]
I suspect this was because of the flycatchers, so it should be fixed now.

**Comment by MCOfficer** [comment]
couldn't confirm anymore, i guess i was behind with my source code.
