### ISSUE TITLE
Surveillance personality drones in systems w/ no planets

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2337]
This isn't really a problem with vanilla as far as I know so it isn't the most important of things to fix, but if a system has no planets and only a star and drones with the surveillance personality are deployed and left in the system, the drones will just scan whatever ship they need to then completely shut themselves down, drifting forever outward. I think the best change would be to have them move around within a certain distance to the system center instead of flying off into infinity.

**Comment by jafdy** [comment]
Scan the star?

**Comment by Bladewood** [comment]
> You fire up your ships [sic] sensors and collect the data that the Wanderers asked for on this system's sun.

**Comment by endless-sky** [comment]
Fixed in ae2554f.
