### ISSUE TITLE
Crashing when there is no ship in your fleet

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2338]
I have a ship.
It is the only ship in my fleet.
I sell it.
*crash*
I create a new pilot.
I enter my name and click `[done]`.
*crash*
I reload a ship-less save on my current pilot. (Don't ask.)
*crash*

Started between https://github.com/endless-sky/endless-sky/commit/9b6ebec4dee47f462c30fb5873f3ed9226c491e9 and https://github.com/endless-sky/endless-sky/commit/3cf5f958c4fada5fd942d703b817998b52851979.

**Comment by endless-sky** [comment]
Oops. Fixed in 8c475b6.
