### ISSUE TITLE
Feature Request: Megaships

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#234]
I want to request a new type of ship that I believe would open quite a few new story lines. I am thinking of a massive ship, something very immobile, covered in weapons and powerful shields, and with large amounts of fighter bays. There would be two types of these ships, the Carrier and the Destroyer.

The Carrier would be the larger of the two, with less weapons, more shields, and large amounts of fighter bays. This would act as a defensive platform, something you would find in Sol or around the free worlds capital (if there is one). 

The Destroyer would be smaller, faster, with less fighter bays but with a great amount of weapons and shields. These would be found leading fleets into battle, rather then defending planets.

I think it would open some quite interesting lines. For example, either the Free Worlds or the Republic would ask you to fire a missile at the opponents flagship in system so and so, or to scan it's outfits, or to find it's position and heading. Or the Free Worlds could ask you to lead an attack group against a lonely damaged Destroyer. These might be sold for great amounts of money and in singular places, but would act as great story leaders. 

(Also, imagine two fleets lead by destroyers meeting.)
(Alien Flagships?)

**Comment by Wrzlprnft** [comment]
This remembers me of the world ships of the Korath


Pointedstick commented 13 days ago

"Another plus was good sizing. Generally you didn't have carriers launching fighters that were only half their size or other silly things like that. The fighters were tiny, the capital ships were huge, and there was an appropriate sense of scale to everything. I think some of the Endless Sky ships could be better scaled to their roles and in-game masses. A lot of the interceptor type ships seem much too large. And right now I'm flying around in a Hauler which is almost as big as a Republic Carrier!"

https://github.com/endless-sky/endless-sky/issues/190

**Comment by Oeleo** [comment]
I'm so for it, yes the game need a really big expensive and slow aircraft carrier to be prefect, That's why I like the style of the beautiful republic carrier.

**Comment by airtroop392** [comment]
This would sound cool and I think it could work if the ships were scaled properly. Your field of vision in ES is locked, so you can't zoom out or zoom in, you're stuck with that one perspective and the only thing that can help you is the radar, which isn't useful at times. If a giant ship just sneaks into your peripheral, it's going to take up a lot of space and it's going to make things confusing.

**Comment by gchapyzh** [comment]
In the next update scaling should come out. #268 Is something very similar: this could be a flagship too. Or a mega-ship. I shall rename this to 'Megaships'.

**Comment by Oeleo** [comment]
+1 that's far more attractive

**Comment by gchapyzh** [comment]
So, so far:
Mobile Shipyard: a massive, mobile, well defended station. Source of missions; Place to repair in hostile/uninhabited territory.
Destroyer: Ship that leads fleets. Great destructive power. Simple really: shoot the target.
Carrier: Relies on Anti-Missile turrets, shield and fighters / drones: Should variate: If no enemy: Small fighter patrol and a lot of surveillance drones. If enemy: All the fighters deployed, No surveillance drones.

**Comment by Oeleo** [comment]
Yes and that could be an endgame objective :
-Acquire your own megaship; but the requirements need to be huge : insanely expensive, missions to complete, combat rating, reputation...
-Destroy the Megaship of the government <name>
And it will make the capital system feel more special, when you're new you know that this system is important.

**Comment by gchapyzh** [comment]
Imagine the feeling when you just start the game when you enter Sol for the first time and you see these massive ships defending earth.

**Comment by lumbar527** [comment]
> Mobile Shipyard: a massive, mobile, well defended station. Source of missions; Place to repair in hostile/uninhabited territory.

Could be defined as a planet and have a) massive defense fleet, b) fleets in the system that contain invisible ships with turrets.

**Comment by Saugia** [comment]
Please don't necro.
