### ISSUE TITLE
Projectile tracking: torpedoes may "flee" ship

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2341]
This is hard to reproduce, but occasionally torpedoes will turn in the wrong direction and end up travelling away from the targeted ship if said ship is following them at a slightly higher speed, i.e. the ship would eventually catch up to them. I think it would make more sense for them to turn around in this situation.

It's tended to occur when I'm being attacked by advanced republic ships with the typhoon torpedoes.

EDIT: Can be reproduced quite easily by chasing a ship that is equipped with a typhoon torpedo launcher and is flying away from you.

**Comment by gunqqer** [comment]
I think this is intended. Some missile's tracking system isn't perfect. Check your local outfitter for missile weapons and in the stats you'll see something like "radar tracking 90%" or "optical tracking 50%" etc.

**Comment by lheckemann** [comment]
No, I believe that causes the tracking to deactivate part of the time. In this case, the tracking is actually causing the projectile to go in the completely wrong direction, which I'm pretty sure shouldn't be happening.

**Comment by Amazinite** [comment]
This is based off of the homing attribute, not the tracking attribute.

**Comment by jafdy** [comment]
It is trying to reach the intercept point. It is just choosing the further away of the 2 points.

**Comment by Bladewood** [comment]
It is the homing attribute. I only ever see this with typhoon torpedoes, which are slow with excellent homing. It never happens with their lesser cousins.

**Comment by Lineth** [comment]
Maybe you're just so tough torpedoes are afraid of you. :DDDDDD

**Comment by endless-sky** [comment]
It's happening because level 4 homing actually just uses an approximation rather than a mercilessly accurate tracking algorithm. But maybe I should add a level 5 homing that uses something [more exact](https://en.wikipedia.org/wiki/Proportional_navigation).

**Comment by KiLEdEnNis** [comment]
@endless-sky that Pug ammo-less missile thing has tracking 5 (I bet for some reason), just saying in case that needs to be changed along

**Comment by Bladewood** [comment]
ooh, moar homing levels

**Comment by gunqqer** [comment]
More homing levels... I wonder how well the new level will handle rediculusly high speeds

**Comment by endless-sky** [comment]
Fixed in ab33f19.
