### ISSUE TITLE
[Request] Quest Reminder when Mission deferred

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#2342]
only tested with the "Assist the FW" Mission, when you need to gather the "secret cargo" from Wazn.

approach the mission with less than 2 bunks, and you will get a dialogue telling you to return with more bunks. you can return and continue the mission, but the quest disappears from the mission menu, and reappears as soon as you take the cargo with you.

version 0.9.6 stable.

**Comment by Amazinite** [comment]
This is just how quests work. This part of the "quest" is two missions. Upon landing, the first mission becomes completed and removed from your mission log. The second mission then gives you a blocked message for not having enough bunks. Since the first mission is gone and the second mission can't be offered, there is nothing in your missions log.

**Comment by MCOfficer** [comment]
it might be intended, but it is not very helpful.
on my current savegame, i did this in a fury, and i still had the archaeologist from the deep mission on board, so i had quite a long way to travel before i could reapproach Wazn. I seriously feared to forget what planet this mission was on. so why not restart the first part if the second one can not be started?

**Comment by gunqqer** [comment]
so you want for a marker to appear on a planet if you defer a mission (that you get on *only* that planet)?

**Comment by MCOfficer** [comment]
it would be quite useful. also when you want to continue a campaign but don't know at which spaceport you should meet.

**Comment by Wrzlprnft** [comment]
I think this might be solved with the pilots logbook

**Comment by gunqqer** [comment]
Has pilots logbook been implemented yet or is is just an idea for now?

**Comment by Amazinite** [comment]
#494

**Comment by gunqqer** [comment]
So it's just an idea and all issue on it are closed

**Comment by Wrzlprnft** [comment]
https://github.com/endless-sky/endless-sky/issues/907

**Comment by MCOfficer** [comment]
as far as i'm concerned, this has been resolved with the implementation of the captains log.
