### ISSUE TITLE
Invisible mission destinations are shown when no other mission is available

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2343]
If you have an invisible mission and there are no others available (easiest way to get this is to just launch and go into your map) when you click on a system with the missions tab selected in the bottom right the destination of the invisible mission will be shown. It is shown with just the normal blue circle missions have. It also shows if all the requirements are met for the mission to be completed.

**Comment by endless-sky** [comment]
Fixed in 7a1447c.
