### ISSUE TITLE
documentation (wiki) on missions -> npc assist

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2350]
As of today (3rd april) the wiki documentation for creating missions contains the following paragraphs / quotes:

Teaser:
**Missing / incomplete part:** "npc assist" works perfect but is completely missing in the documentation.

Quotes:
> npc (save | kill | board | disable | "scan cargo" | "scan outfits" | evade | accompany)...
---------------------------
> # Non-Player Characters (NPCs) #
> 
> NPCs are ships that are associated with the mission in some way. This includes friendly ships the player must protect, and hostile ships the player must fight off or destroy:
> 
> npc (save | kill | board | disable | "scan cargo" | "scan outfits" | evade | accompany)...
> 
---------------------------
> Each "npc" tag may have one or more tags following it, specifying what the player must do with the given NPC:
> 
>     save: The mission fails if the given NPC is destroyed.
>     kill: To complete the mission, the given NPC must be dead.
>     board: To complete the mission, the player must board the given NPC. If the ship is destroyed before being boarded, the mission fails.
>     disable: To complete the mission, the player must disable the given NPC.
>     "scan cargo": To complete the mission, the player must scan the given NPC's cargo. If the NPC is destroyed before being scanned, the mission fails.
>     "scan outfits": Same, but the player must use an outfit scanner instead of a cargo scanner.
>     evade: you cannot complete the mission if any members of this NPC are in the same system as you.
>     accompany: you can only complete the mission if all members of this NPC are in the same system as you.
> 

Short text description:
"npc save board" does not work when the player shall board a friendly ship (any friendly government like neutral, merchant, derelict, ...)
"npc save assist" works but is not documented to exist at all.

Long text description:
I was struggling in the 2nd chapter of my side plot.
In my side plot, I placed a derelict ship / wreckage in a separate system.
In the first mission the player has to scan the (derelict) ship - easy task with npc save "scan outfits"
In the second mission the player shall bring a team of engineers onboard to download the computer log files.
First I was looking for the boarding missions (Ideally assisting, otherwise boarding). According to the documentation that's the wrong way because the target (source in terms of the assisting mission) would be a npc ship belonging to an active mission
Hence I was focusing on the npc options. Since the ship belongs to a neutral / friendly government, npc save board does not work for obvious reasons. You cannot board friendly ships. I needed over 1 hour of various testing (restarting the game all the time when changing plugin files... and getting back to that mission) to realise that it would work if I assigned the ship to a hostile government (Korath, Pirates, ...) but then the players ship also fires on the target ship --- hey, save that ship! dont destroy it! --- and the player also could take away some of the still left outfits --- which I dont want either.
I finally tested npc save assist, despite completely missing in the documentation. Luckily, the game right away accepted it and did exactly what I wanted.

Since I did not find any examples for boarding missions in the current official game data I hereby supply my current 2nd mission:

```
mission "Marsian technology: Metropolis wreckage 2"
	priority
	name "Board the wreckage"
	description "Bring two engineers and a computer expert to the ancient wreckage and attempt to download its log files."
	blocked `One of the scientists checks your ship and says: We have a mission for you but you need a Jump Drive, three free bunks and seven tons of cargo storage. Please return when you are ready.`
	passengers 3
	cargo "Computer equipment" 7
	to offer
		has "Marsian technology: Metropolis wreckage 1: done"
	source "Marsian Home"
	destination "Marsian Home"
	on offer
		require "Jump Drive" 1
		conversation
			`You meet the scientist in the spaceport and he offers you a drink.`
			`"Thank you again for all your assistance, Captain <last>! We have checked the scans you did and agree with you that this ship is only a wreckage right now. We will not risk sending a full expedition team over there without having more information.`
			`But we have a team of three volunteers, a computer expert and two engineers, who are optimistic to be able to download its computer log files if you bring them onboard. They have already a little experience working in space suits. Would you fly again to the ship and bring the team safely back to us afterwards?`
			choice
				`	"Sure, I'd be glad to help."`
					accept
				`	"I will do it under one condition: I take only responsibility for the safe passage but not for what happens there."`
					accept
				`	"Sorry, but I cannot guarantee for their safety aboard of an alien ship. I must decline."`
					decline
	on complete
		payment 240000
		conversation
			`"Thank you for bringing them back alive, Captain <last>! They already sent us a copy of the last log files after returning to your ship so we could immediately start analysing it. [...]`
	npc save assist
		government Derelict
		personality derelict timid disables staying uninterested
		system "Ancient Metropolis ship"
		ship "Metropolis (wreckage)" "Ancient Metropolis wreckage"
		dialog "You succeed in opening one of the airlocks and board the wreckage. The team unloads some computer components and supercapacitors. After about four hours the team returns with two data crystals. Time to head back to <planet>."

```

**Comment by endless-sky** [comment]
Fixed.

**Comment by EndrosG** [comment]
Confirmed and closed.
