### ISSUE TITLE
request: additional text replacement in missions

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2351]
Teaser: Add a `<tons number>` placeholder.
**Edit**: And allow usage of placeholders in apply sections (conditions), i.e. on any parts of the `on complete` and not only in descriptive texts such as dialogs and conversations.

Relates to: `<tons>` and `<bunks>` placeholders.

Short reasoning:
`<bunks>` provides a pure number, while `<tons>` provides a number followed by a word.
Thus, `<bunks>` can be used for numeric operations while `<tons>` cant be used for numeric operations.

Long reasoning:
I was inspired by the current coalition jobs to create a set of jobs aiming to deliver a total of (xxx) tons of (supplies) to (some destination), similar to the supplies and volunteers for the ring worlds in the coalition, but not with a "Coalition Jobs"++ on complete but with some "ringworld workers" += `<bunks>` and "ringworld supplies" += `<tons number>`
And since cargo (tons) is usually flexible / random, one cant hardcode it in the += operation. If I would use fixed cargo sizes I could workaround, but fixed cargo sizes aint "nice". :-/

Of course I had some different usage in mind, different from the coalition plot. I want to create some deeper player interaction by events based upon sufficient supplies. But that doesnt matter ;-)

**Comment by KiLEdEnNis** [comment]
I'm lost
what are you requesting?

**Comment by EndrosG** [comment]
`<bunks>` is a pure number like `15`, but `<tons>` is a text like `15 tons`. I would like to have a pure number for the cargo as well. `<tons>` is more the equivalent to `<fare>` and there is no cargo equivalent to `<bunks>`.

Reference quote from wiki
```
# Text replacements #

Certain characteristics of a mission, such as the cargo or the destination planet, may be chosen at random. In order to refer to those randomly chosen elements in descriptive text, you can use the following placeholders:

    <commodity> = name of commodity being carried
    <tons> = "1 ton" or "N tons"
    <cargo> = "<tons> of <commodity>"
    <bunks> = the number of passengers
    <passengers> = "passenger" or "passengers"
    <fare> = "a passenger" or "N passengers"
```

**Comment by KiLEdEnNis** [comment]
why would you need a pure number for cargo? it IS in tons

**Comment by Wrzlprnft** [comment]
that's for sure a creative use of those replacements, but i assumed those are strings anyway? does that even work with the passenger number yet?

**Comment by tehhowch** [comment]
the actual int values are in the mission's public CargoSize() property: 
https://github.com/endless-sky/endless-sky/blob/846d7c88d29781862f2c4a78935ee7ed33436a14/source/Mission.h#L73
But, I don't think that's exposed or able to be stored for use by some logic gate for use when determining missions to offer / events to trigger.

To achieve your goal I think you need to use some logic combinations with missions of varied sizes. Rather than something watching and summing completions for you, you have to make your missions and quantity ranges, and then determine the approximate ranges of completed transfers for various combinations of completed missions. So maybe "disketteworld transfer" 1-5 are all 40-60 items, while transfer 6-10 are 100-300. If your goal is 450 items transferred, you'd make the build event trigger from a mission that is only offered if you have completed either 3 of the 5 transfer 6-10, 1 of the 6-10 and 5 of the 1-5, etc.

That's how I understand the current custom missions mechanisms... Some of the plug-in makers probably have a better understanding.

**Comment by EndrosG** [comment]
@Wrzlprnft : It does not work with the `<bunks>` yet. Sadly.
I've just tried various alternatives and failed to get anything to work as desired.
**Final result**: It is not part of a conversation / descriptive text.

@tehhowch : I am currently writing on my own plugin (started it last year with 1st chapter, continued this year after a break, working on 2nd chapter right now).
failures (the game refuses to start at all):
```
	destination Mars
	on complete
		"Mars: gold rush jobs" ++
		"Mars: workers" += "<bunks>"
		payment
```

```
	on complete
		"Mars: workers" += <bunks>
```

```
	on complete
		"Mars: workers" = "<day>"
```
(day is a pure number too, even if not the desired one)

**working:**
```
	destination Mars
	on complete
		"Mars: gold rush jobs" ++
		"Mars: workers" += 5
```
Thats the hard coding way for narrow ranged cargo sizes. But it does not work very well for the random large bulk numbers which may result from
```
	passengers 5 5 .2
```

not functionally working, but at least not crashing [this quote is from my plugin jobs.txt]:
```
	destination Mars
	on complete
		"Mars: gold rush jobs" ++
		"<planet>: workers" = "127"
		payment
		dialog "You drop off the <bunks> workers on the <planet> and collect your payment of <payment>."
```
this is translated to [this quote is from the savegame.txt]:
```
	destination Mars
	on complete
		dialog
			"You drop off the 4 workers on the Mars and collect your payment of 6,000 credits."
		payment 6000
		"Mars: gold rush jobs" += 1
		"<planet>: workers" = 127
```
It recognizes the "127" as number (127 without quotes). It ignores the `<planet>` tag on the left side. It looks like nothing gets replaced in those lines at all.

If I would have read the documentation carefully, I might have not tried at all... :-/
Looking at the code, I was hoping it would be achieved.
https://github.com/endless-sky/endless-sky/blob/3ba054cef4154777c5c89c4bbca9d3ddcdf46c30/source/Mission.cpp#L992
But the documentation clearly says:
```
# Text replacements #

Certain characteristics of a mission, such as the cargo or the destination planet, may be chosen at random. In order to refer to those randomly chosen elements in descriptive text, you can use the following placeholders:
[...]
These placeholders will be substituted in any text in the following places:

    the mission name
    the mission description
    dialog messages contained in the mission
    conversations contained in the mission
```
So... Bad luck for me, this is neither a description, nor a dialog, nor a conversation.
----------
The resulting "creative try" didnt succeed either.
I tried to encapsulate the set part into a conversation using the apply mechanism. I had again all the same issues with the game not starting at all.
```
mission "XX Gold rush on Mars: Workers [0]"
	job
	repeat
	name "XX Workers to <planet>"
	description "Transport this crew of <bunks> workers to <planet>. Payment will be <payment>."
	passengers 2 2 .5
	to offer
		has "Go to Mars: offered"
	source
		government Republic "Free Worlds" Syndicate Neutral
	destination Mars
	on complete
		"Mars: gold rush jobs" ++
		"<planet>: workers" = "123"
		payment
#		dialog "You drop off the workers on the <planet> and collect your payment of <payment>."
		conversation
			`As you return to the researchers you see one of them just doing some paperwork.`
			apply
				"<planet>: workers" += 257
			`You drop off the <bunks> workers on the <planet> and collect your payment of <payment>.`
				decline
```
is translated into (savegame.txt):
```
"available job" "XX Gold rush on Mars: Workers [0]"
	name "XX Workers to Mars"
	description "Transport this crew of 4 workers to Mars. Payment will be 6,000 credits."
	passengers 4
	job
	repeat 0
	to offer
		"Go to Mars: offered" != 0
	destination Mars
	on complete
		conversation
			label 0
			"As you return to the researchers you see one of them just doing some paperwork."
				goto 1
			label 1
			apply 2
				"<planet>: workers" += 257
			label 2
			"You drop off the 4 workers on the Mars and collect your payment of 6,000 credits."
				decline
		payment 6000
		"Mars: gold rush jobs" += 1
		"<planet>: workers" = 123
```
I.e. no replacements in any `apply` section. Though the apply section is within/inside a conversation, it is not part of the conversation.

**Comment by EndrosG** [comment]
@endless-sky : this is still open since you did not pay any attention to #2456.

I really would like to see a bit more communication of yours. Holding back to say more.

**Comment by endless-sky** [comment]
@EndrosG, because the game needs to be backwards-compatible, it's nearly impossible to remove a new feature or change how it's implemented once it's been added. (For example, I think the new add / remove syntax is much better than the old "clear" syntax it replaces, but the game will now have to continue to support "clear" forever.) So, for anything that introduces new mechanics in the data files that will need to be supported in perpetuity, I generally wait until I'm completely sure that a particular approach is the best one. That means it's not uncommon for a feature to be suggested and to not show up in the game until 6 months later, because that's preferable to letting the code pile up tons of technical debt.

**Comment by Elyssaen** [comment]
Please do keep this in mind though! Whether it's called `<tons number>` or not, this could be really useful.

The iconic example that comes to mind is EV Override's construction of Paaren Station. Contributing to the construction of a new station (one with immense strategic importance) was really fun, but EVO's engine simply made it a matter of doing N random missions in a row. That sort of objective would be a lot more engaging if milestones were based on getting X tons of Industrial Goods to the station, encouraging you to invest in a freight fleet if you want to speed up construction.

`<tons number>` might not be the best name, and maybe it wouldn't from _scratch_ be the best implementation. But it's parallel to `<bunks>`, which has to be supported forever now, so in that context in makes sense.

**Comment by flaviojs** [comment]
The `<tons number>` placeholder is `<ton>` with a different formatter, so maybe embed the intended format in the placeholder?

The format could be something generic like `<name[:formatter[:arguments]]>`. For example, your `<tons number>` could be equivalent to `<tons:number>` and `<tons>` could be equivalent to `<tons:plural:"a ton":"# tons">` (as default formatter).

For flexibility, it might be better to let the formatter interpret the arguments so it can handle ':' as it wishes.
