### ISSUE TITLE
All ships "available" in unexplored system's shipyards

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#2353]
in the shipyards tab of the map interface, all ships are highlighted ("available") when an unexplored system is selected.
![auswahl_021](https://cloud.githubusercontent.com/assets/22377202/24660184/2ba74db6-194f-11e7-944f-16437fab2f3b.png)

**Comment by gunqqer** [comment]
This was before it would show you the exact ones and also I feel there was or wasn't, which you weren't supposed to know because you haven't explored them

**Comment by MCOfficer** [comment]
i know i'm not supposed to, but then they should all be displayed as not available.
btw i saw this on the latest source code (from ~3 hours before the issue was created)

**Comment by Bladewood** [comment]
I want that cursor.

**Comment by MCOfficer** [comment]
kde desktop environment, breeze dark theme. not offtopic at all ;)

**Comment by endless-sky** [comment]
I'd say this is just a matter of opinion. I would say that greying out a ship specifically communicates, "this is not available here," and therefore there's no reason to grey it out if you don't know whether it's available.

**Comment by MCOfficer** [comment]
ok. it's your choice after all, and it's a tiny tiny detail anyways  ¯\_(ツ)_/¯
