### ISSUE TITLE
documentation (wiki) on ship personalities -> appeasing, harvests, mining

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2354]
Please update the documentation of ship personalities.
In the fleet definition file I found at least 3 new personality attributes which are not yet documented.
these are:
1. appeasing -- used in: fleet "Small Southern Merchants", and others
2. harvests -- used in: fleet "pirate raid", and others
3. mining -- used in: fleet "Human Miners"
4. escort -- used in many missions, e.g. mission "Pleasure cruise security"
----------
Second thing regarding this article: It starts with `Each ship in the game can have a variety of "personality" flags that control its behavior. `
Really **each** ship? What is the syntax for the player ships?
I am afraid you mean just any NPC ship. :-(

**Comment by jafdy** [comment]
They could. Player escorts use the "ESCORT" flag to control their behavior.

**Comment by EndrosG** [comment]
not sure if I understood your comment.
First, I thought you were saying that I could control the behavior of my own secondary ships (all owned by me, except for the flag ship) by editing the savegame manually. That's what would be possible if the personality tag could be used as child tag beneath a ship tag... And what could be used to have escort ships perform asteroid mining.

Then I remembered that in mission files a personality `escort` is used, e.g.
```
	npc accompany save
		government Merchant
		personality escort timid
```
This, once again, describes a personality of an npc, not of a players ship.

But at least this brings me to add a fourth undocumented personality style (escort) to my original post.

**Comment by KiLEdEnNis** [comment]
appeasing: dumps cargo when threatened & low health
harvests: collects cargo & like any flotsam
mining: shoots mineable asteroids to destroy them, paired w/ harvests, these mining ships also collect the ores
escort: follows the player ship as part of the fleet

& about:

> Second thing regarding this article: It starts with  Each ship in the game can have a variety of "personality" flags that control its behavior. 
 Really each ship? What is the syntax for the player ships?

the PLAYER controls its ship, of course it doesn't apply to it

**Comment by endless-sky** [comment]
Fixed.
