### ISSUE TITLE
request: cargo distribution amongst escorts when departing

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2355]
proposed label: mechanics

**Teaser**: change the way how cargo is distributed amongst the players fleet when departing from a planet/spaceport.

Example fleet:
```
ship Hawk
	name "Flagship"
ship Sparrow
	name "Escort 01"
ship Sparrow
	name "Escort 02"
ship "Star Barge"
	name "Freighter"
```
Reordered fleet:
```
ship Hawk
	name "Flagship"
ship "Star Barge"
	name "Freighter"
ship Sparrow
	name "Escort 01"
ship Sparrow
	name "Escort 02"
```

As far as I observed, currently the game distributes cargo first amongst secondary ships before loading anything on the flagship. This allows the player to plunder hostile ships, mine asteroids, or board hostile ships with additional crew (while passengers are on the secondary ships).
For some reasons of beauty I tend to sort the ships in my fleet in certain patterns. This can mean that I have all fighting ships sorted in front of the cargo ships like in the example fleet given above.
Both fleets use the same default ships and have a total cargo capacity of: 30 + 15 + 15 + 55 tons.

Assume you depart from (origin) with a total payload of 35 tones of luxury goods (i.e. valuable cargo!). That is not much for your fleet size but you intend to mine some nearby asteroids and thus dont mind.

----------
In the example fleet configuration the game loads 15 tons each on both of the sparrows and 5 tons on the barge. I.e. the fleets cargo distribution could be described as 0/30 + 15/15 + 15/15 + 5/55.
You escort ships are intented to be lightweight and maneuverable and shall protect your freighter which is intended to carry your valuable cargo.
Having the cargo onboard of the interceptors makes them slower (acceleration and turning, not max. speed) while the designated freighter is almost empty.

Now if you go out and mine the asteroids, the still fast sparrows cant pick up any materials because they are full while the freighter is too slow to collect any asteroid payload.

----------
Now compare with the reordered fleet. The game loads all 35 tons on the freighter and the cargo hold of the sparrows stays empty. They can assist you in the mining process (picking up some payload).
And/Or they have better turn and acceleration rates and thus have better combat performance when protecting the freighter. Also, the valuable cargo isnt lost as easily since a sparrow is easier to destroy than a heavier ship. (originally I wanted to use a freighter with 150 tons cargo space but then downscaled to a simpler / cheaper fleet setup for reasons of simplicity)

----------------------------------------
**Feasible option (1):**
Load/spread cargo equally amongst all secondary ships. Proportional wise, i.e. in the above example split 35 tons amongst 15 + 15 + 55 = 85 tons, i.e. sparrow gets 15 * 35/85, and the barge gets 55 * 35/85 tons.
Pro:
* easy approach, probably easier to code than (2)
* all ships have some free space and can assist in the mining
Contra:
* the lightweight interceptor escorts still carry cargo while there is no need for this

**Feasible option (2):**
Prioritize large ships over small ships. Prioritize heavy freighters > light freighters > transports > *warships > interceptors > fighters > drones.
Fill any heavy freighters first, then fill light freighters, then fill transports. Fill fighters (including the new boxwing) and drones last.
Pro:
* all cargo stays on a few freighters, which are to be protected by the armed escorts.
* the escorts have maximum capacity for plundering / harvesting / mining.
* reasonable / realistic pattern for convoys.
Contra:
* eventually relies upon the currently static classification system of freighters and warships which might become dynamic in the future (i.e. defined in data files)
* classification would become functional and questionable --- the heavy warship Bactrian (currently having 530 tons of cargo space) might be a preferred cargo holder in a mixed convoy because of its stronger shielding (and hull) compared to 4 standard freighters or 10 barges.

**Feasible option (3):**
Equally distribute the remaining free space. I.e. start loading on the ships with the largest cargo space first but dont fill them completely.
The above 35 tons would still be loaded entirely on the barge because it still has 20 tons remaining which is more than the 15 tons of each sparrow.
But a payload of 55 tons would be split up amongst the 3 ships: 45 tons on the barge, leaving 55-45=10 tons free, and 5 tons on each sparrow, leaving 15-5=10 tons free too, i.e. all secondary ships would have the same spare capacity (the flagship would still stay empty).
Pro & Contra: not yet fully clear to me.

----------------------------------------
Side note, only semi-related to main topic: Having mentioned the boxwing leads to interesting questions of payload distribution in carrier based fleets when fighters and/or drones get involved in plundering / harvests / mining.
Fighters and drones are currently unable to unload their cargo into the carrier when being recalled.
Tested with 0.9.6, a carrier flagship, a heavy freighter and a fleet of fighters which all might be considered tier 3 or 4 upon what I've read the last 24 hours.

**Comment by jafdy** [comment]
I don't think this maters enough at the moment as it is quite hard for small fleets to use escorts to pick stuff up. This is besides the valuable coding time it would take up.

**Comment by EndrosG** [comment]
It can/will become more relevant once mining is implemented into the AI of users escorts. You will then want your interceptors/fighters/drones to collect the minerals since because of their better turning and acceleration values.

**Comment by jafdy** [comment]
Oddly I find it easier with larger ships. I just sort of side swipe the area.

**Comment by Tadrix** [comment]
> Pro & Contra: not yet fully clear to me.

* Every ship has cargo space available to pick up asteroid chunks;
* Smaller ships like fighters and interceptors are less likely to be slowed by cargo.

**Comment by Jorlem** [comment]
I think that if there was an option to manually reallocate cargo among ships in your fleet, it wouldn't be nearly as annoying.  Also, we wouldn't need to complete every ongoing mission before we can park part of the fleet.

**Comment by jafdy** [comment]
Cargo and passengers are distributed when you take off. @Jorlem

**Comment by KiLEdEnNis** [comment]
about the cargo, not sure how relevant it is
I plundered some raiders & stored the systems cores, large heat shunts & jump drives in a Bulk Freighter & a couple of escorts had some cargo space as well (like my temporarily refitted Carrier to have 115 space)
the Carrier stored the 4... jump drives? I had & a large heat shunt (104/115), while it could store 3 LHS' & 2 jump drives (112/115)
in short: there's no smart "optimalization" for cargo outfits (which is cargo so seems on topic to me)
