### ISSUE TITLE
bug? fighters fail to land on carrier at certain speeds

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2356]
I currently play with 0.9.6 (steam version).
My fighters fail to land on my carrier while I "slowly" drift through space.
Slowly means: constant speed far below max speed, no accelerations, some asteroids seem to be moving as fast as my carrier.

At the end of writing this issue I came to the conclusion that the fighters (and drones) lack the `homing 4` capability (i.e. the code already in the game exists). Their landing algorithm seems to assume a fixed/static position of the carrier.

**Edit:** Applies to situations when your flagship is the carrier because the autopilot does not stop the flagship. If flagship has no bays but an escort is the carrier, then the carrier comes to a full stop (which is still no landing on the fly as a `homing 4` would allow for).

----------
**long story** (can be omitted, just apply the `homing 4` algorithm to fighters/drones when being recalled)

I checked two savegames from different epoches and encountered in both the same issue.
I first checked in my current save with the latest ships. I tried with different carrier ships of different sprite sizes (largest tested carrier sprite: 1024 x 1024).
Then I loaded a one year old save (unchanged file from 30th april 2016) where I had the previous generation of ships (one tier lower). Same behaviour.

In all tests the fighters correctly launch from their bays (on the newest ship I used the left and right tags for some bays, this works fine for the launch procedure :+1: )
The fighters are able to fly around my carrier. The fighters are able to catch up with the carrier from distance with much higher speed when they feel so.
But when I recall them, they build a swarm behind the carrier (behind in terms of moving direction, not in terms of rotational direction) and fail to land in from behind unless I come almost to a stop.

In the older savegame I had a vanilla shield beetle escorting me. I once asked it to hold position and then gather around me again and it was at least twice as fast as my carrier, i.e. my carrier was moving slower than 250 speed. The fighters have a max speed of 1k with almost 300 acceleration (1086.7 / 289.6 / 167.4). Compared to the shield beetle (558.4 / 188.6 / 78.7) they are almost twice as fast and have better acceleration and turning, but still, they dont land. They stay close behind the carrier. The faster the carrier moves, the greater the distance is at which they stay. The slower the carrier moves, the closer they move behind the carrier. 

I all tests I had to move slower than the asteroids around me in order for the fighters to successfully land. Otherwise the fighters fail to land even if their max speed is 5-10x of the current speed.

During a long running test I finally had my speed definetively below 100 (still with the old save game, i.e. with the fast fighter around 1086 max speed).
The fast fighters were able to land while a slower fighter class with 589 / 195.7 / 87 was still unable to safely land on the carrier while the carrier's speed was below 100.  Carrier speed was approx. 70-90 (or slower?), a modified deep river with a max speed of 126 (126 / 69.1 / 65.3) was noticably faster then the carrier!

When the carrier stops, the fighters can land from any direction. They dont intend to land from behind then. That makes me thinking that the fighters dont have a `homing` mechanism when trying to land. It looks like they try to fly to a position a carrier has right now instead of plotting an intercept course like `homing 4` would do for any missiles.

**Comment by tehhowch** [comment]
Based on the code, this is intended behavior - you MUST stop to allow your fighters/drones to reboard:
https://github.com/endless-sky/endless-sky/blob/8ca29236741d9d689ee494ea73cdc0126f74dd4c/source/AI.cpp#L573

Note the velocity check.

**Comment by EndrosG** [comment]
Thanks for the direct link. I had found that part of the code myself while writing this issue (using the search, still learning to use github) and I did and still do read it different.
```
if(mustRecall || isStranded)
		{
			// Stopping to let fighters board or to be refueled takes priority
			// even over following orders from the player.

```
To me it says, that this is the current state of the code, yes, but not that it is ultimatively intended to be that way that a STOP is required.
> 			// Stopping to let fighters board or to be refueled takes priority
says that letting fighters board has absolute priority over all other orders, including orders from the player.
Stopping is just what happens currently when following this priority. One could easily change it to have two separate condition checks, or allow for `homing 4` in general.
I assume (but dont know, really) that this was coded before the code of the `homing 4` algorithm was written and could be easily modified to allow for recalling (and refuelling) on the fly.
Code of `homing 4`: https://github.com/endless-sky/endless-sky/blob/master/source/Projectile.cpp#L155

Looking from a different perspective: If STOPping would be ultimatively intended, why the autopilot then doesnt stop the users carrier (eventually being the flagship) in order to allow the fighters being recalled?

**Comment by endless-sky** [comment]
Right now, boarding can only be done when at a standstill. Whether that should be changed is something of a balance / mechanics question.

Missile homing is different because the missile just has to collide with its target; it doesn't need to come to a stop directly over its target.

**Comment by EndrosG** [comment]
Do fighters have to come to a stop over their carrier when landing? I'd say they have to come to a relative stop.

I.e. I would eventually separate the mustRecall and the isStranded condition and apply parts of the missile homing in the isRecall section to allow fighters to home the carrier as if they were a missile, eventually with some smooth speed adjustment/reduction on the final landing (while a missile wants to hit with max velocity).
For the boarding (entering) it sounds reasonable to have it at a standstill. For refuelling, we have already used air-to-air-refuelling as well as water-based refuelling on the move in the 20th century. Why cant we refuel spaceships in 31st century while moving?

**Comment by tehhowch** [comment]
> Looking from a different perspective: If STOPping would be ultimatively intended, why the autopilot then doesnt stop the users carrier (eventually being the flagship) in order to allow the fighters being recalled?

It's up to the player to decide if moving their flagship is more important than allowing any fighters to board its bays. In a combat scenario, this "plz slow down" behavior can help shield the flagship from any pursuers' incoming projectiles. In a post-combat scenario, only those flagships with Scram Drives can abandon their deployed units while executing a group jump.

For future updates, if fighter AI gets reevaluated, this board-at-speed functionality could be relegated to specific new models, with lore indicating the advancements in manuevering and relative positioning technologies. Or perhaps, board-at-speed becomes possible in a fighter that has a reverse thrust outfit. (lest it collide with its carrier's docking bay walls).

>For refuelling, we have already used air-to-air-refuelling as well as water-based refuelling on the move in the 20th century. Why cant we refuel spaceships in 31st century while moving?

Running out of fuel in a system currently provides some level of vulnerability to hostile action. Needing to stay put long enough for a NPC/escort to approach and assist generally means players will consider making sure each ship can have enough fuel for the journey, rather than designate one escort as the ship with no offensive weapons (no targeting from hostiles!), tip-top engines, and the rest of the outfit space as Fuel Pods while the rest of the fleet arms to the teeth.
Plus, I'm sure that NPC would rather not try to refuel me as I dogfight with pirates/aliens

**Comment by EndrosG** [comment]
@endless-sky commented on 4 Jan in #1971 (which was not yet merged)
> I think for this to be effective, the fighters also need better code for docking with a moving target (which is something I expect to add to the AI at some point, but haven't done yet).

Yeah, MZ wants better docking for fighters :-)
Now we only have to do it, lol

**Comment by EndrosG** [comment]
I'd say I improved the docking. :-)
It's not the all-in-one pull, but it works and is an improvement, imho.
