### ISSUE TITLE
enhancement: dynamic waypoint selection && content: mark shipyards and uninhabited systems in map.txt

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2359]
Teaser:
1. modify game code to allow for dynamic waypoints 
2. change the way uninhabited systems are defined (unify government assignments in map.txt)
3. introduce a new shipyard attribute to planets and assign it to every existing shipyard - this may include adjusting events

Background:
1. Currently, source, destination and stopover planets can be selected dynamically by the game by applying filters. Waypoint systems have to be named explicitely and cant be selected dynamically by filters.
2. Right now (0.9.6) the only systems with `government Uninhabited` are located in the Korath territory being part of the wanderers middle campaign. All other uninh. systems, i.e. in human space, in hai space, in old wanderer space, and in coalition space, have an assigned government according to the surrounding region. Examples include: Nocte (Republic, 1 jump from Vega), Procyon (Republic, between Sirius and Pollux), Torbab (Coalition, 1 jump from Speloog) -- `Prakacha'a` even stays Wanderer territory, I will create a separate issue for that (edit: #2360).
3. Right now (0.9.6) there is no consistant way for selecting planets with shipyards as source or destination. This can be achieved (without changing the code) by giving them all a specific attribute (in map.txt, or in event definitions upon change).

Job and mission variety could be enhanced if
1. Waypoints could be selected dynamically through filters, this could lead to alternate versions of missions like ("Transport scientists", "Escort science vessel" - both currently defined in `deep jobs.txt`)
2. With dynamic waypoints it becomes interesting to select/filter uninhabited systems
3. Being able to filter shipyards or training facilities [referring to `Belug's Plunge` in Coalition space] I have a set of jobs in mind :-)

**Comment by Wrzlprnft** [comment]
to point 2. the sea in front of shores is kinda unihabtied too, though, it is, up to a certan distance, territory of the government.

**Comment by EndrosG** [comment]
If it will stay intended that those systems officially belong to the territory of the regional government, could you think of a different, easy to realize way (given the ability to select waypoints through filters) how to let the game select an uninhabited system (nearby...)?

**Comment by Bladewood** [comment]
Fun fact: The systems beyond the Pug wormhole are of the Uninhabited government.

**Comment by gunqqer** [comment]
but the wormhole to end of the rainbow closes? doesn't it? It does for me at least

**Comment by EndrosG** [comment]
though your question is OffTopic, for me it didnt close. `events.txt` has the event "pug flee" which creates the object "Pug Wormhole". This is the wormhole to "Over the Rainbow". The files in my version 0.9.6 (steam) do not have any other references to "Pug Wormhole" nor do they have any other event modifying the object list of system Deneb (also checked system "Deneb" with double quotes).
Saying this, my map currently has 3 active bi-directional wormholes.

**Comment by KiLEdEnNis** [comment]
Deneb wormhole doesn't disappear (you could get escorts stuck there when it closes)

**Comment by Bladewood** [comment]
It used to close, but not anymore.

**Comment by gunqqer** [comment]
Huh when did this happen? And is there any way to reopen it (through save file editing) on a save before the update that made it not close?

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/cd6856391b56950a9f1ea1599b60d25e120c92a0 a long, long time ago... in a galaxy far, far away...

**Comment by gunqqer** [comment]
And idea on how to manually reopen the wormhole via save file editing?

**Comment by EndrosG** [comment]
In the hope to finally end this completely OffTopic branch and to return to main topic:
Your savegame has a `changes` section. In this you should find a node with:

```
	system Deneb
[...]
		object "Pug Wormhole"
			sprite planet/wormhole
			distance 2320.29
			period 1788.2712
```
(in my savegame, the phrase "pug worm" exists exactly once, making this a good search text)
This node created it. Your savegame with the closed wormhole must have a later node with a new object list for system Deneb.
Find this (or these) node(s) and either remove the object list as in cd68563 (link in previous comment from @Bladewood ) or add the `		object "Pug Wormhole"` node with sprite, distance and period again in the last object list of system Deneb.

**Comment by EndrosG** [comment]
point 3 - marking shipyards - is now addressed in pull #2449, i.e. if 2449 gets merged it can be removed from this wish list

**Comment by tehhowch** [comment]
Waypoints are selectable already with LocationFilters, but without system attributes ( #3143 ) only matches to government, systems, and distance are possible.
With #3144 waypoints would have access to the full gamut of LocationFilter customization.

**Comment by endless-sky** [comment]
Basic system attributes were added in e1c1a55.
