### ISSUE TITLE
content: mistake in wanderers middle?

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2360]
The uninhabited system `Prakacha'a` still belongs to Wanderer government after Hai occupied all surrounding systems, even after the Kor automata (Kor Sestor and Kor Mereti) have been neutralized.
Sitenode: In #2359 I suggest changing uninhabited systems generally to government uninhabited instead of assigning them to factions. 

Screenshot attached.

![endless_sky_v0_9_6__20170405__map_after_finishing_wanderers_middle](https://cloud.githubusercontent.com/assets/26883037/24714261/49c6e520-1a28-11e7-96c3-547870799b51.jpg)

**Comment by Wrzlprnft** [comment]
the sea in front of shores is kinda unihabtied too, though, it is, up to a certan distance, territory of the government.

**Comment by EndrosG** [comment]
@Wrzlprnft : Though I like your comment about the 12-mile-zone, I would prefer having it in issue #2359. If it will stay intended that those systems officially belong to the territory of the regional government, could you think of a different, easy to realize way (given the ability to select waypoints through filters) how to let the game select an uninhabited system (nearby...)?

**Comment by endless-sky** [comment]
Fixed in 58b1b9f.
