### ISSUE TITLE
Unable to buy Starmap with no ship sellected

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2361]
Perhaps intended, but seems a little odd.

**Comment by gunqqer** [comment]
Can't buy anything with out a ship. Outfitters locked because nothing can be install because you don't have a ship

**Comment by wambat1** [comment]
Not not ships in fleet, just no ship selected. Just as if you wanted to load outfits into your cargo.

**Comment by KiLEdEnNis** [comment]
oddly specific, at this point I wonder if it's worth a fix lol

**Comment by jafdy** [comment]
You can't buy a map into cargo because; What are you going to do with it? Seriously though, it is still the same map as it was. But that would be hard to code and just a little bit useless. 

Simply, not worth changing in any major way.

**Comment by endless-sky** [comment]
I'm able to buy a map when no ship is selected; are you sure there's not something else going on, like that you already have a map or that your cargo space free is negative?

**Comment by wambat1** [comment]
I had not considered the cargo space. Too late for me to check now, but that may have been a factor. 

    On Wednesday, April 5, 2017 7:53 PM, Endless Sky <notifications@github.com> wrote:
 

 I'm able to buy a map when no ship is selected; are you sure there's not something else going on, like that you already have a map or that your cargo space free is negative?—
