### ISSUE TITLE
bug: ship prices for variants

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2363]
I defined a variant of the shuttle by supplying a full `attributes` list and a description only, i.e. outfits etc. are taken from main class. Basically it looks good.
But after I changed the `cost` parameter and restarted the game, the price of neither shuttles changed. Neither of the new variant nor of the original (which should not happen anyways).
Instead, the percentage value in the brackets gets "strange".

Screenshots attached, variant definition including shipyard extension supplied.

```
ship "Shuttle" "Shuttle (damaged)"
	attributes
		category "Transport"
		"cost" 90000
		"shields" 400
		"hull" 480
		"required crew" 1
		"bunks" 6
		"mass" 63
		"drag" 1.7
		"heat dissipation" .7
		"fuel capacity" 120
		"cargo space" 20
		"outfit space" 114
		"weapon capacity" 10
		"engine capacity" 54
		weapon
			"blast radius" 12
			"shield damage" 120
			"hull damage" 60
			"hit force" 180
	description "This old rusty shuttle has a damaged hull, damaged fuel tanks and some other damages. The remaining fuel capacity is very low, requiring it to refuel after every jump. But it can still fly, even through hyperspace."

shipyard "Basic Ships"
	"Shuttle (damaged)"
```
![endless_sky_v0_9_6__20170405__shipyard_wrong_price_for_variant](https://cloud.githubusercontent.com/assets/26883037/24726596/46a93cc8-1a53-11e7-963a-a496d2fb8086.png)

**Comment by Bladewood** [comment]
Would it be [out of place, off-topic] to say that I've also noticed problems when it comes to editing price tags in save files?

**Comment by EndrosG** [comment]
I would answer with no. It probably has the same origin.
By the way, I checked the shipyard display on the map screen and in the left column it shows the correct prices... Since these are always the 100% prices.

Btw.: it would be nice to see the name of the variant within the game. Having four "Shuttle" versions (including original one) looks ... [put some word of your fantasy here]

![endless_sky_v0_9_6__20170406__shipyard map _wrong_price_for_variant](https://cloud.githubusercontent.com/assets/26883037/24730953/203125ce-1a67-11e7-9bb6-d9a5b2dc3b1d.jpg)

**Comment by Amazinite** [comment]
Wouldn't be good for things like the Kestrel. Just put something in the variant's description.

**Comment by EndrosG** [comment]
I did as shown in the first screenshot. ;-)

**Comment by endless-sky** [comment]
Variants are really intended for creating different outfit loadouts of the same ship. If you want the hull to have different attributes, you should give it a different model name, instead of just a variant.

Depreciation calculations assume that the base chassis of every ship with the same model name is interchangeable with any other ship with the same model name. Creating variants with different base prices messes with those calculations.

**Comment by DingusShingleton** [comment]
Would it be feasible to use a modified sprite for a variant? IE mark II cruisers get a slight aesthetic update? (Kind of like each new model year of a car)

**Comment by EndrosG** [comment]
@endless-sky : please dont get me wrong, I dont want to be picky or alike. But the Kestrel is the best example for a ship with different hull attributes among variants. While I chose "more shields" when doing this mission last year, the original version is still "defined". Both have different hull attributes, but at least they share the same price / hull cost.
And there is another unique version which tends to fly around whereever it wants. You even know the captain of the latter one: MZ!

```
person "Michael Zahniser"
	government "Author"
	personality
		plunders
[...]
	ship Kestrel Kestrel
		"never disabled"
		attributes
			category "Heavy Warship"
			"cost" 50000000
			"shields" 40000
			"hull" 40000
```
That definition defines the ship belonging to the Kestrel class with the name Kestrel, correct? ;-) Otherwise it would not have a sprite assigned since this particular ship does not have a sprite tag while the Pointedstick uses a different sprite.
(Sidenote: Interestingly, `Cap'n Pester` is the only one of the `never disabled` ships using any sort of `Hand to Hand` outfit, namely `"Intrusion Countermeasures" 160`)

**But I got your point and will define the rusty shuttle as different model then.**

**Comment by EndrosG** [comment]
**But more importantly than the Kestrel which is not used a lot in the game, the Marauder ships dont follow that rule**
And I already happend to capture a few of them as they are part of general existing fleet types and thus "appear in numbers"... So, while stock pricing arguments might not apply as they are not available in shipyards, your depreciation argument applies! @endless-sky 
```
ship "Marauder Arrow"
		"cost" 1320000
ship "Marauder Arrow" "Marauder Arrow (Engines)"
		"cost" 1500000
[...]
ship "Marauder Bounder"
		"cost" 1250000
ship "Marauder Bounder" "Marauder Bounder (Engines)"
		"cost" 1400000
[...]
```

**Comment by Amazinite** [comment]
But you never see those in the shipyard panels...
