### ISSUE TITLE
content issue: fighters in FW Syndicate Capture 1 / 1B

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2364]
Since I dont have learned yet how to work with that pull request system (I did the tutorial last night, but... I dont fully understand it yet, I feel sorry), I open another issue and somebody else, if you agree, will do the proper changes then.

File in question: `free worlds reconciliation.txt`

Missions in question:
- mission "FW Embassy 1C"
- mission "FW Syndicate Capture 1"
- mission "FW Syndicate Capture 1B"

Total number of issues: 3

**Question / issue 1:**
The personality of the Gibraltar changes during the campaign.
In FW Emb 1C we start with:
```
	npc accompany save
		personality escort heroic
		ship "Dreadnought" "F.S. Gibraltar"
```
In FW Synd Capt 1 the `escort` flag is removed:
```
	npc accompany save
		personality heroic
		ship "Dreadnought" "F.S. Gibraltar"
```
In FW Synd Capt 1B the `escort` flag is missing too, but obviously just because it is missing in the previous mission. The npc flags `accompany save` have been removed by purpose, that is clear.
--> Is there any particular reason for removing the `escort` personality from the Gibraltar while the newly added escorts from Navy (Cruiser) and Deep (Aerie and Bactrian) have the `escort` flag?

**Issue / question 2:**
We depart from Earth with 4 npc escorts, some of them having **empty** bays.
These bays are technically speaking still empty when arriving the destination of FW Synd Capt 1, i.e. when landing on Nimbus.
After we successfully landed on Nimbus, we are offered FW Synd Capt 1B and the Aerie launches its two fighters. As soon as Alex Soylent is on our ship and we received the last message from the Oathkeeper captain (technically: on accept), we have 5 Daggers (2 on the Aerie, 3 on the Bactrian) and 4 Combat Drones (on the Cruiser Mk II).

We are deep in syndicate territory and out of nowhere 5 Daggers and 4 Drones appear.
I would assume that those fighters and drones were already on the ships when we left Earth, i.e. we have them already in FW Synd Capt 1.
The question here is, if it makes that particular mission (FW Synd Capt 1) easier or harder, if those ships were added to FW Synd Capt 1. Easier as we have more firepower, harder as we need to save more ships. With no official active npc enemy, it sounds easier in the first moment. But there are always the random fleets.

**Question 3:**
Is there a specific reason, why the Navy Cruiser and the two Deep ships stay in orbit (personality: waiting) while the Dreadnought ("Gibraltar") is landing with us? Or is it just because it did land on Earth and thus started from Earth (instead of waiting in orbit) and then cant change its personality on the fly and not land no nimbus?
This could be achieved with some lore on Earth saying something like the Gibraltar already started and is waiting together with the other ships in orbit. Because otherwise there is a minor gap in the story that the ships from Deep are landing on Mars while the Navy ship lands on Luna, but all three (together with their fighters, or not...) are waiting in orbit when the player departs.
I.e. I suggest some minor changes to the `on offer` conversation of FW Synd Capt 1 - or deploy the npc's on the respective planets.

**Thanks for paying attention**

**Comment by jafdy** [comment]
1: I don't thing it makes any difference. 
2: Saving the fighters would make it much harder. If you didn't have to save the fighters then you could have reappearing fighters instead.
3: I don't thing I see where you are going.

**Comment by Amazinite** [comment]
If a single ship within a fleet that is marked save/accompany dies, you fail the mission.

**Comment by EndrosG** [comment]
That's why I said, that in general it makes it harder but I am not sure for the particular situation of FW Synd Cap 1. Last time I played it was early 2016, not 2017. And my 2nd pilot just started the last days and is currently also involved in various testings and has just been offered Pact Recon 1...
I dont remember how many enemies I met while flying from Earth to Nimbus and thus what's the "real" risk of loosing one of the fighters / drones is.

**Comment by endless-sky** [comment]
There's literally no way for the player to know that those ships are not carrying fighters, without looking at the data files. The idea is that they're holding off on launching them until the real battle starts. (And, as others have said, it would be annoying if you failed that mission every time a drone got swatted out of the air en route.)

**Comment by endless-sky** [comment]
The only thing here that's definitely an issue is the missing "escort" tags, and that's fixed in fc1372a.

**Comment by KiLEdEnNis** [comment]
scanning shows fighters & drones too (at least it did, and I haven't seen anything that changed is)
so if you scan one of those ships you see they have no fighters/drones

**Comment by jafdy** [comment]
The only way to "fix" this would be to prevent the fighters from launching. The code time required is not worth it.

**Comment by EndrosG** [comment]
Added PR #2374 and issue #2375.
I accept that the fighter inconsistency will not be solved for now.
