### ISSUE TITLE
Unable to enter values in "dump cargo" player menu

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#2365]
Not sure if anyone else has noticed this but occasionally I am unable to put specific numbers in the "dump cargo" menu box, I can delete the highlighted number, but none of my number keys will enter anything.

**Comment by jafdy** [comment]
Unless you are using the numpad it is probably something to do with groups being assigned to number keys now.

**Comment by SirStigII** [comment]
I tried both sets of numbers and had the same results...

**Comment by KiLEdEnNis** [comment]
I don't have this issue (at least never saw it)
what system ya have & from where do you play the game? (I use Windows 10 & play through Steam)

**Comment by SirStigII** [comment]
I'm on win10 and steam, it is possible it is an external source that is somehow interfering. I'll try and take some more detailed notes when it happens to see if there is a pattern. I can close this until that time if it would be better. I have played on my work win7 laptop and I *don't recall* it happening there so it must be my specific setup.
