### ISSUE TITLE
Hard to read text on very big screens

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#2368]
It may just be a problem with having an exceptionally large/detailed screen. Also reported that the "Main Zoom Factor" wasn't doing anything. 
Edit: Screen size 1920x1080. Is a TV screen.

http://steamcommunity.com/app/404410/discussions/2/135513549095484964/?tscn=1491509235

**Comment by endless-sky** [comment]
In the Steam thread, the user says their screen is only 1026 pixels tall. At that resolution, no UI zoom larger than 100% is possible. (And, in 0.9.7, there will be a dialog (2f439d8) explaining that.)
