### ISSUE TITLE
Feature Request: notes attached to particular systems

### ISSUE THREAD

**Issue by Highrs** [endless-sky/endless-sky#237]
I think it would be nice if you could bookmark systems, like "ALIEN SEEN HERE" or "AVOID AT ALL COST".

I would also like to see the positioning of my ships on the map. Maybe when I tell my fleet to stay or leave a ship behind, I could look at the map and see where these ships are.

I realize this is already shown in the game screen, under the fleet ships, but some mapping would be nice.

**Comment by endless-sky** [comment]
I've been thinking about adding a "logbook" capability, which could have entries written by players and others that are automatically added as you progress through the story line or discover new things. Once I have time to sit down and work on that, I'll see if I can also add a way to attach notes to particular star systems.

**Comment by gchapyzh** [comment]
@endless-sky Thats my idea pretty much, yes. Would be great to have that implemented.

**Comment by Dr-Terrible** [comment]
:+1:

**Comment by airtroop392** [comment]
Can affirm. It is incredibly annoying to lose a great trade route because, in your infinite wisdom, you just forgot what the two planets were called.

**Comment by gchapyzh** [comment]
This will be a greater issue with more systems.

**Comment by tehhowch** [comment]
Mods can do this for those who play them, through the use of the `special logs` log entry:

`log "Systems" "<system>" "Some text about the system."`
`log "Planets" "<planet>" "Some text about the planet."`

However, there is not yet a way for the player to create or delete a log entry. Conceivably this is possible, but the player should probably not be able to delete logs created by missions / events. This might call for a "Journal" version of the logbook. which calls several functions to set the section ("Systems", "Planets", etc), header ("<system>", "<planet>"), and entry.

**Comment by endless-sky** [comment]
The main reason there isn't support for player-created logbook entries is that that would require a full-fledged text editor, as opposed to just support for typing in a word or two in a dialog.

As for this particular issue, the game already stores all the most useful information about each system, so this would have limited usefulness.

**Comment by Amazinite** [comment]
Closing this issue given that, as endless-sky noted, this would require much more text editing capabilities than the game currently provides and, as tehhowch noted, missions are already capable of logging anything that might be useful enough for the player to need to remember. Overall this just doesn't seem like it would be something that's worth the effort.
