### ISSUE TITLE
Scrolling on Player Info Screen

### ISSUE THREAD

**Issue by Karazura** [endless-sky/endless-sky#2370]
One of three things is happening;
1. I'm unable to scroll on the player info screen in game due to a bug. 
2. I'm unable to scroll because it's not a feature.
3. I can't scroll because I'm too stupid to figure it out. 

Regardless of the reason I'd like help because my fleet is too large to fit on that screen and I need to scroll to be able to manually choose the ones I want to have parked and active. If it's not a feature I would like to recommend it get added.

**Comment by Wrzlprnft** [comment]
tried the arrow keys?
though, if 2 of three cases (2. and 3.) do make your issue something i wouldn't post here (there was an issue about a scrolling panel, so you could have fpund out about it or posted there), i'd say please spare github from this kind of issue. go to the google group, if you want quality help, but may take a day or two, or go to the steam forums, which is faster, but the answer might not nail it, at least the first few. or join the discord, for a more chat-like experience in getting answers.

**Comment by endless-sky** [comment]
Have you tried Page Up / Down or the scroll wheel? Both of them should work.

**Comment by tehhowch** [comment]
I had an instance where my touchpad driver failed to handle scroll events, and was unable move the [i] button's ship list. Best I could do to park ships was use Previous and Next. Regular arrow keys do not work, as attempting to set the selection opens the Ship Info tab, while the list of ships is on the Player Info tab.
However, purchasing several dozen randomly-named Star Barges shows that PageUp/PageDown does scroll through. It appeared to not miss any ships in the paging, but this may depend on screen resolutions - the bottom shown ship became the 2nd from top after a PageDown, and the top shown became 2nd from bottom after a PageUp.

**Comment by endless-sky** [comment]
I've added support for the up and down keys in the fleet listing as a part of refactoring the Info Panel, in commit 3555842.
