### ISSUE TITLE
bug / mechanics: escorts departing from "wrong" planets

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2375]
As the title says, the game is currently unable to let escorts depart from different planets.

Scenario:
You once parked a ship on Mars.
Later, when you are on Earth, you unpark the ship.
When you launch from Earth, the other ship should launch from Mars, but it will be displayed as launching from Earth as well.

Applies to ships owned by the user and to escorts of all kind (?) from missions.

Found it while trying to work on question 3 of #2364. I wanted the Deep ships to launch from Mars and the Navy ship to launch from Luna, as the `on offer` conversation suggests.

Savegame for testing attached.
[Testing Tester~TEST FW Synd Cap 1 takeoff.txt](https://github.com/endless-sky/endless-sky/files/907428/Testing.Tester.TEST.FW.Synd.Cap.1.takeoff.txt)

Edit: Testing mission definition file attached too.
[testing_mission_fw_synd_cap_1.txt](https://github.com/endless-sky/endless-sky/files/907434/testing_mission_fw_synd_cap_1.txt)

**Comment by Bladewood** [comment]
Relevant: You can access outfitters for a ship on a different planet, as long as the both of you are in the same system.

**Comment by gunqqer** [comment]
Doesn't seem to unreasonable for the ships escorting you to do a quick planet hop to you

**Comment by endless-sky** [comment]
I don't see much point in fixing this. Especially because if taken to its logical conclusion, you wouldn't be able to outfit those parked ships either, even though you can outfit ships that were holding position in system (and not disabled) when you landed. This is another case of game play trumping realism.

**Comment by tehhowch** [comment]
I think addressing wrong-planet departure is addressable without impacting gameplay experience negatively. I'll look into that in the next week.

**Comment by tehhowch** [comment]
A ship that had a planet when the player landed will now remember and use that planet when the player next takes off, thanks to #4111
