### ISSUE TITLE
Feature request: maps at Heliarch outfitters

### ISSUE THREAD

**Issue by ggeorgovassilis** [endless-sky/endless-sky#2376]
Since the Heliarch coalition will allow us to carry out jobs for them and even grant us access to their shipyards, it's reasonable that they should offer space maps at outfitters.

**Comment by tehhowch** [comment]
#2373 
If you're building on your own, from your endless-sky git directory:
1) If you forked Endless Sky and have this repository as "upstream":
    `git fetch upstream`
    `git rebase upstream/master`
2) If you followed the install instructions on the wiki (e.g. this repo is 'origin'): 
    `git fetch origin`
    `git rebase origin/master`

and then `scons` to build using the new source code you just downloaded.

If you use Steam as the installer, then it will be in your next release.

**Comment by Amazinite** [comment]
>(Please close this issue)

**Comment by Bladewood** [comment]
In other words, it's already done. https://github.com/endless-sky/endless-sky/commit/98ea18e2161ae3169e3c3533ad66fb456111a857
