### ISSUE TITLE
With jumpdrive equipped, all escort ships jump immediately to random systems and stay there

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#238]

**Comment by thenerdfreak** [comment]
Weird thing fixed it, i decided to follow one of the ships around with a hyper drive and as soon as i entered the system it was in, it switched to my main ship and all other ships appeared beside it, I don't know what caused this, but another glitch i've been having is: saving after you press the "park All button" directly after choosing a new flagship makes the save file and crew count think you still have to original flagship as your current flagship, the save shows the original flagship's silhouette and often your crew numbers drop into negatives because it randomly subtracts crew with every jump

**Comment by endless-sky** [comment]
There's a bug in 0.8.7 and previous versions if the first ship in your list (which is usually expected to be the flagship) is parked, disabled or absent. What happens is that the game picks a different "flagship" for you - the first ship in your list that is suitable as a flagship - but some of your escorts still think the first ship is their flagship, or may think they have no flagship at all and are free to wander wherever they want.

**Comment by thenerdfreak** [comment]
So if i upgrade from the steam version will i keep progress? The bug happens every time i try to leave a planet because i have transport ships parked in every corner (i really hate slow transit)

**Comment by Wrzlprnft** [comment]
A friend of mine had another bug connected to this one:
He had diabled a ship, stolen the engine, but then, just to test it out, he captured it.
Well, sh#t happens, but from there on it was just hanging around there
but: it became later ingame his flagship without him knowing, and as he tried to capture new ships, the process fought with the non-existent crew of the disabled one, and killed the crew on his now-capturing ship

**Comment by gchapyzh** [comment]
@Wrzlprnft I second that, something very similar happened to me too.

**Comment by endless-sky** [comment]
This bug ought to be fixed in 0.8.8.

**Comment by endless-sky** [comment]
This issue is fixed in 0.8.8, and 0.8.8 is now the default on Steam, so I'm closing this issue.
