### ISSUE TITLE
bug: reordering weapons on the fly / in space

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2380]
I did a bit of search but didnt find a related bug post yet. So here we go...

In the ShipInfo panel, you can change the weapon assignment of hardpoints IN SPACE, during flight.
I.e. you can even in the middle of a major battle swap the location of an anti-missile turret with a sunbeam turret, just as example.

Also: While you cant swap weapons anymore for *dead* ships, you can still dump cargo from dead ships. It says that you jettisoned xxxx credits worth of cargo.
If the ship is still in the process of exploding, the cargo is really jettisoned in boxes into space.
If the ship does not exist anymore, the cargo luckily does not appear, so you cant recover it from nirvana.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/0cb87eccdeefa0277618f899d404ab137219afeb aw, what? I didn't think of this as a bug.

**Comment by themightygrunt** [comment]
._. but dumping cargo from exploding ships make sense

**Comment by EndrosG** [comment]
nice, that commit came fast...
so I can close this now.

**Comment by Bladewood** [comment]
I disagree with the closing of this issue! I want that back! *pouting*

**Comment by Nechochwen-D** [comment]
@Bladewood you can always put it back in your local version.

**Comment by tehhowch** [comment]
Is there any way to tooltip / message the player that this is something they can do... but not while in space?

**Comment by EndrosG** [comment]
okay, you really want to continue discussing -> reopen
