### ISSUE TITLE
Should Outfits Expansion be Outfit Expansion?

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2381]
Title says it all.

**Comment by gunqqer** [comment]
forgive me if I'm just being stupid, but... I dun get it. Can you elaborate more?

**Comment by MessyMix** [comment]
Plural --> Singular

**Comment by endless-sky** [comment]
To me "Outfit Expansion" would sound like something that expands an outfit, whereas "Outfits Expansion" is something that makes space for more outfits.

It could also have been "Outfit Space Expansion," but I decided against that because the "Cargo Expansion" isn't called "Cargo Space Expansion."
