### ISSUE TITLE
Outstanding Crew Salaries (Back Pay) Not Visible in Bank

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2387]
If you're in the habit of not paying crew any money, whenever you do have money, you dole out back pay (upon launching from the planet). However, this pending debit isn't ever shown anywhere, and the only way you know you have it is because you keep paying all the credits you've got after launching from a planet. Makes trying to amend your relationship a little difficult, because you can't easily find out how much you owe them.

**Comment by SirStigII** [comment]
Yeah, I have noticed this as well, it was confusing as heck the first time I got low enough it happened.

**Comment by endless-sky** [comment]
Fixed in ea15d81:

![salaries](https://cloud.githubusercontent.com/assets/11450262/25065908/e942ec88-21e5-11e7-9400-dfe172976d16.jpg)

Also made it so the "Pay All" button pays off back salaries if there's enough credits left over after paying your mortgages.

**Comment by KiLEdEnNis** [comment]
do ya just pay the salaries ya owe or also some extra because you were behind? (realism thing, interest is a punishment though)
