### ISSUE TITLE
request: Log of all player quest/story interaction

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#2389]
It would be great to be able to see all the dialog the player has ever interacted with in some sort of log file. Many times I have accidentally responded to a prompt before fully reading a paragraph, and have wanted to go back and see exactly what was said. This would be especially useful if someone picks up the game after not having played it for a while.

**Comment by Nechochwen-D** [comment]
This has been brought up before.

The fact is if someone is really desperate to see what they missed they can look in the data file.

**Comment by guillochon** [comment]
Link to where it was brought up before?

Also seems silly to make people dig into datafiles for a feature that's pretty common in RPGs...

**Comment by guillochon** [comment]
Ah I see it, closing this.

**Comment by MessyMix** [comment]
lol, search b4 making a new post pls

**Comment by guillochon** [comment]
It was at the bottom of the search results. Was that comment really necessary?

**Comment by MessyMix** [comment]
Yes, to encourage you to get into the habit of it.

![image](https://cloud.githubusercontent.com/assets/20450076/24841707/21f3c4ea-1d58-11e7-9087-b1857dd9ba3c.png)
Also, "bottom of the search results". Even a super basic search would have shown it very close to the top.
Furthermore, it's rare that I quote @KiLEdEnNis, but he says something that you should keep in mind.

https://github.com/endless-sky/endless-sky/issues/2222#issuecomment-284226858

So, yes, I thought that my comment was warranted.

**Comment by guillochon** [comment]
That's not even the issue I found, I found the one that's currently open.

Anyway, this is idiotic. I closed the issue after finding the relevant issue. The snark is not necessary and is not helpful nor wanted.

**Comment by MessyMix** [comment]
Okay. We can calm down enough that we don't have to go around calling things idiotic, now, do we? I'll remove all my posts, and perhaps this one will be more "helpful", even though it carries the exact same message as the others.

It's better for the sake of orderliness that we don't have many duplicates lying around, no?
Furthermore, a simple search would have turned up several hits, right?
So perhaps next time it would be better if you'd made that search.

That's all I have to say. Yes, you did the best thing after realizing the situation, but it would be best if it didn't happen in the first place.

Kile's comment is still sound advice. https://github.com/endless-sky/endless-sky/issues/2222#issuecomment-284226858
