### ISSUE TITLE
Feature Request: Racing missions

### ISSUE THREAD

**Issue by egilburg** [endless-sky/endless-sky#239]
Breathe new life into pure speed- and agility-oriented fighters and transports, especially towards lategame when otherwise you focus on heavy ships.

Mechanics
---

1. Accept a racing mission specifying starting system and planet. Depending on mission, some may require a buy-in.

2. Travel to destiation, visit station bar, confirm you want to begin mission, pay the buy-in if applicable.

3. Upon leaving, the race starts immediately. A bunch of nav buoys appear in the sector, you must touch each one before moving on to next one. If game engine permits, the next target is pointed with off-screen arrow when applicable.

4. Other AI racers will compete with you. At low tiers these may be random ships, at higher tiers these will be dedicated speedsters like the Flivver.

5. Final destination will be a station (same or different one from where you took the mission). Land on it to finish the race.

6. First 1-2-3 places get a (decreasing) prize, money or otherwise (see below for Prize suggestions).

7. Leaving the sector, landing on a different station than finish one, or landing on any station before touching all the buoys in the correct order, forfeits the race, as is attacking other ships (except below variation of no-rules races).

Variations
---

1. By default, races are peaceful and attacking other ships makes you lose the mission. In pirate and other rogue sectors, no-rules races would exist, and attacking others (with normal weapons, EMPs, or even the Korath grabbers) would be allowed (of course, you could be attacked as well).

2. Some races may have "anti-buoys" which you would be penalized if touching, they could form a line or curve for you to stay within. In rogue sectors, these could be replaced with mines that damage or disable you if you cross them.

3. I see races as being single-system, although perhaps multi-system races could work as well (but then they are less different from normal timed delivery missions).

4. A variation (and reward for having a fast ship) would be a "chase down smuggler" mission offered by authorities, similar to attacking pirates, except the smuggler will try to flee and generally have a fast ship. So going in with a ship like Bactrian will simply not catch up to him, as he'll flee both within and between systems, and if you are too late and he escapes to a certain station, you lose the mission. So your best bet would be to personally have a fast ship that can catch and kill/disable the smuggler before the enemy has a chance to jump.

Prizes
---

1. A top-league race championship could feature race-built Flivvers or a custom race ship better than anything you can buy yourself, and winning the race would grant you this ship as a prize.

2. Winning a no-rules race could be one of the entrace criteria for a future pirate storyline, such as attracting the attention of a smuggler lord who is on the lookout for fast, ruthless mercenaries.

Open questions
---

1. If you have a fleet, what would it do when you start a race? Perhaps its forced to stay behind in the starting base, perhaps it follows you as usual (and defends you in no-rules races from competitors), or perhaps it actively tries to win the race as well, and a win from any of your escorts counts as your own.

**Comment by Wrzlprnft** [comment]
I like the idea, really.
If there are no-rules races over more than one system, kinda police ships could appear (navy,free world,syndicate) trying to disable the participants

cough "[...]It’s the ship that made the Kessel run in less than 12 parsecs." cough

**Comment by Pointedstick** [comment]
Ooh, I like this. Would add some much-needed variety to the basic jobs.

**Comment by gchapyzh** [comment]
+1 I love it.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
