### ISSUE TITLE
Cannot make groups for tactical and strategic organization of fleets

### ISSUE THREAD

**Issue by quantumandan** [endless-sky/endless-sky#2393]
Apologies if this has been addressed (I've been so impressed with the activity of the community, but I'm working off a STEAM build with custom key bindings, so perhaps the issue is with my setup), but I saw recently in a changelog that said a player could use cmd+(a number) to assign and access combat groups. I love how faithful endless sky is to escape velocity but I love even more the way the community has taken the original concept and begun perfecting it. For those of us that use the non-default keyboard layout, how does one go about setting and accessing subgroups of one's fleet?

**Comment by MessyMix** [comment]
AFAIK, there is no way (as of right now) to rebind the shortcuts in the game, only the main controls. It is lucky that I stayed off the number keys long enough that fleet commands were implemented so I didn't have to rebind all my controls.

Some helpful links, maybe: #13 (unconventional keyboard) #2208 (UI/Interface hotkeys configuration) #2291 (switching control profiles). Hope this helps.

**Comment by quantumandan** [comment]
Thank you so much for your detailed response. I've been browsing the source code for where the functionality might be (unfortunately, I don't remember the particular changelog and therefore the correct commit, that mentioned holding cmd + a number after selecting a group of escorts), so perhaps this remains an undocumented feature or is only available in a different branch. Sorry to impose on you, but would you kindly point me to where this functionality might be -- I'd like to contribute with further suggestions or even a patch, but being an old python guy, its taking me a hot minute to understand objc project structure and best practices.

**Comment by tehhowch** [comment]
on my windows keyboard, i use Ctrl + 1-9 for binding escorts into groups. Shift + boundNumber will add that group to the current selection, or if already selected, deselect them.

in the source, this behavior is closely associated with the keyword SelectGroup

**Comment by quantumandan** [comment]
@tehhowch thank! I had left-cmd overriden on the OSx version, turns out ctrl was the correct modifier to press all along.

**Comment by MessyMix** [comment]
Ah. Looks like I misunderstood your question. I thought you were requesting a feature to rebind the fleet selection keys. Sorry! :P

**Comment by quantumandan** [comment]
@MessyMix no worries, keep up the awesome work!
