### ISSUE TITLE
balance Kor Sestor vs Kor Mereti (review)

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2394]
Today I focused a bit on comparing the two automata factions of the Kor, the Kor Sestor and the Kor Mereti. Before writing this, I found #1046 via search as only hit upon three different search querys.

I feel like sharing my results here even though not everything belongs into an "issue".
**Summary**:
- "Light Warships" excellent
- "Heavy Warships" should eventually be improved by adding 1 small heat shunt to the Model 512.

While the Sestor use drones and fighters and have 3 ships with carrying ability, the Mereti dont use those at all. Thus, a ship by ship comparison was not too easy.
From Sestor shipyard, only the MPT 53 (Light Warship) and the KIV 349 (Capital Ship) were left.
Luckily, there are some equivalents on the Mereti side, the M32 and the M512.

-----

*Light Warships*

The MPT53 hull is a bit more expensive than the M32. It is slightly weaker in total hitpoints, much faster (drag 5.7 vs. 9.0) but roughly 15% heavier (worse turning). Both ships come with some 200+ weapon capacity and 110 engine capacity which looks pretty equal, but the Sestor MPT53 has +130 tons of outfit space. I first wondered, why and for what.
I did a dozen (12) 1 vs. 1 battles between the two in Sol system. The Mereti once survived with 35% hull, in all other cases the Sestor won (remaining hull between 24% and 67%). Including the loss (counting as -35%), the Sestor ship had an average hull of 37% at the end of the 12 battles.
Having both tagged with the escort personality, I could clearly see that the Sestor ship was lacking energy (resulting in short breaks) but stayed pretty cool while the Mereti ship had problems with its heat but stayed at full energy most of the time. *That is, both ships have a specific weakness, which is good in terms of balance.*
Adding both into my own fleet as real escorts, showed a major difference in the final price tag. At 25% depreciated value, it's 9.9m for the Sestor ship and 7.8m for the Mereti ship. Okay, the "superior" ship really costs more, +2.1m. The Sestor ship has, despite the more expensive hull (+430k), a larger system core (+640k), much more cooling (+550k) and more expenses on the power systems (+350k). That explains the 90% of the price difference.

Just for test purposes only, I removed one of the three large heat shunts and reduced the medium system core to the small one, which the Mereti ship has too.  -740k, i.e. 9.8m -> 9.1m. Again, a series of 12 battles. This time, the Mereti ship clearly won. 4 : 8 - While it started with 3 : 3, pretty evenly matched battles (each one), with rather low health remaining on the winner most times, it then turned quickly to 3 : 5 and finally 4 : 8, for the Mereti ship, which was still cheaper. The best Mereti victory was with 67% health, the best Sestor victory with a approx. 40%. The sestor ship now clearly lacked cooling and overheated too often, resulting it to temporarily not fire. The lower battery capacity of the smaller system core was imho not the problem, snice that is a one-term-effect, but the heat was.
That large heat shunt is 24 tons, the small one 7 tons. Sadly, the M32 Mereti ship has only 6 tons left, so it cant hold another one in its default configuration. Otherwise, it would probably clearly win in the default setting.
Swapping out the candle class generator (23 tons power system) for a second small heat shunt (7 tons), resulting in -320k cr (still at 25%), immediately changed the balance. Minimal energy shortages at the beginning of each battle (move+turn+fire), but no outages after a few seconds and no more overheating, just high heat levels. Starting with 1:2 in favor of the Meteri, they went to 4:4 and finished with 8:4 in favor of the Sestor, with 2 major victories for the Mereti and one for the Sestor (67%+ hull left) - most of the Sestor victories were pretty close with some 25%. I dont have a precise average but would guess for some 5%-8%, taking each loss with minus what the other one had left into account. It looked pretty equal many in total, some clear victories for the Mereti ship (may be if the mines were hit very often?), many close victories for the Sestor - that evens out.

All in all, the two ships are pretty close. In their stock configuration, the 9.8 million Sestor credits clearly win against the 7.8 million Mereti credits, but just "minor" changes result in big differences.
The small Mereti ship could do better if the cooling would be improved at the cost of either the additional generator (the candle class) or by downgrading the thruster to Lunar class which eventually would even be the "better" swapout. But then, despite it's pretty equal total hitpoints, weapon capacity and engine capacity, it is still the cheaper ship with less hardpoints (1+3) vs. (3+6, the Sestor ship uses smaller weapons).
The Sestor ship clearly lacks energy. Given full energy, it would reach a much higher DPS value than the Mereti ship, and thus generates much more heat when firing. Removing already 1 of the large heat shunts brings it into trouble in terms of overheating, resulting in many lost battles.

-----

*Heavy Warships*

The other possible comparison is between their capital ships, the KIV 349 and the M512.
The difference in hull price (+900k) and total hitpoints (+2k = 122.6k - 120.6k) is much slower, outfit space varies only by +60, weapon capacity and engine capacity almost the same again (440 and 160-170). That is, on the paper both ships are much closer together than the two Light Warships from the first comparison. -- Depreciated stock value: 23.3m for the Sestor ship, 22.5m for the Mereti ship (+780k).
Once again, i did a dozen 1 vs. 1 battles between the two in Sol system. The Model 512 did not win a single battle - a clear 11:0. There was one battle evened out, with both ships being disabled at the same time. 20% Sestor hull, 19% Mereti hull, so still in favor of the Sestor ship. In 3 out of 12 battles the Sestor ship even had some shields at the moment the Mereti ship got disabled. The biggest victory was 46% hull and 10% shields on the Sestor ship. Average outcome: 34% Sestor hull, 1.5% shields.
This time, the Mereti ship did not stay at full energy. But it never really run into heavy energy shortages. The Sestor ship took advantage from its Anti-Missile turret, taking out a few mines. But again, the Sestor ship really lacked energy, resulting in interrupted weapon fire.
Both ships were running pretty hot, but only the M512 suffered from overheating again. First overheating at about 54-55% shields, then at 28-29%, then at 3-4% shields - I closely monitored 3 battles only for that, all 3 were within a narrow range for all 3 overheat outages.
*That is, both ships have a specific weakness, which is good in terms of balance. And they share the same weakness with their Light Warships, so it seems to be consistent.*
What I really dont like in the first moment, is that the two capital ships are so close in pure numbers but the Mereti ship did not win a single battle in the first dozen. Only in the 11th battle the Sestor ship was at least disabled, but the Mereti ship had less hull points (in %) left.

In the second dozen, the Sestor ship again won 11x, but lost 1x. So after 24 battles with default configurations, it's 22:1.

Interestingly, the Sestor ship has 15 outfit space free, the Mereti ship has 24 outfit space free.
It looks fair enough then, to add another small heat shunt to the M512 (+7 tons, +45k credits at 25%), resulting in 17 outfit space free. Sounds fair? Lets see, another 12 runs.
1. battle: Overheatings at 27% shields, 75% hull and 30% hull - the last one lasted too long. Lost. 33% Sestor hull
2. battle: Overheatings at 29% sh, 85% hull. Victory, 60% Mereti hull.
3. battle: Similar overheatings, victory, 31% Mereti hull.
Looks promising. But still, each overheat period costs either 8% shields or 12% hull strength
4.+ losses with 36%, 24%, 36%, 32%, 24% Sestor hull.
9th+: victory, 53% Mereti hull. -> loss, 26% Sestor hull -> victory, 43% Mereti hull -> loss, 37% Sestor hull
That's 8:4 with an average of 5% Sestor hull (+61% / 12). -- That result is exactly the same as when I swapped out the secondary generator on the M32 for a second small heat shunt. Again 8:4 with an average of again 5%.

Despite the dozen being full I thought like: Please, give me 3 more, ok? 13th+: victory, 41% Mereti hull -> loss, 27% Sestor hull -> victory, 23% Mereti hull
That's now 9:6 with an average of 1% Sestor hull (+16% / 15). Those additional 3 battles changed the resulting score...
After the first 3-4 battles it looked promising, but after 5 losses in a row I though like "dang... can I slightly improve the cooling? just a little bit more? there is plenty of outfit space left" But then, beginning with the 9th battle, the Mereti ship was in favor again. It looked so promising that I went for additional 3 battles, ending at 15. Each victory was followed by a loss though, but the surviving Mereti ship was in a better shape than the surviving Sestor ship, each time. Just with another overheat to happen in the next 1-2 seconds in a real battle.

As both ships are very close in terms of pricing, total hitpoints, etc., I really suggest giving the M512 another small heat shunt which will even put the remaining (free) outfit space closer together.

-----

I know that a fleet consists not only of one ship.
I did a 5 vs. 5 run with the stock configuration. For scoring, I did not sum up the remaining hull percentages but instead did count the number of active ships and the number of disabled ships of the winning party, where a score of 2.1M indicates 2 active and 1 disabled Mereti ships, surviving all final explosions.
In sets of 6 battles:
- 2.1M, 2.1S, 1.2S, 4.1S, 3.0M, 2.0M = 7.4S - 7.1M
- 2.0S, 2.2M, 3.2S, 3.2S, 2.1S, 3.1S = 13.6S - 2.2M
I.e. 8:4 wins with 7.4+13.6 - 7.1-2.2 = 11.7 Sestor survivors ahead = one active and a half disabled on average
- 1.4S, 1.3S, 2.1M, 3.2S, 3.2S, 2.1M (1fc) = 8.11S - 4.2M (1M fully charged with 96% shields, nice)
- 2.2S, 5.0S, 4.1S, 3.0M, 3.2M, 2.1M = 11.3S - 8.3M
I.e. 7:5 in the 2nd dozen with 7.9 Sestor survivors, making a total of 15:9 after 24 battles with 18.16 = 0.75 active + 0.75 derelict survivers on average. Or: after 120 sestor ships engaged 120 mereti ships, a total of 34 sestor ships was left, which is roughly 30%

As this already took a lot of time (several hours), I did not run any tests with the slightly modified M512 in the 5vs5 setting.

-----

*Conclusion*
The Sestor ships offer generally more hardpoints and have a higher DPS equipped, which they just cant deliver due to energy shortages, while the Mereti ships have lower DPS values, no drones or fighters, and constantly suffer from overheating.
For both ship classes, which can be directly compared because of not having any bays and having similar hit points, weapon capacity (and engine capacity) and more or less similar price tags, the Sestor ship wins 11 out of 12 battles with an average of 35% Sestor hull remaining.
While this seems okay for the Light Warship because the Mereti ship costs 20% less than the Sestor ship, it looks inappropriate for their capital ships. In both cases, a small outfit change evens the chances pretty much out. While the Sestor ship still wins more battles than the Mereti ship, the latter one survive in a better (relative) condition. Relative, because the Mereti ships have roughly only half of the hull points of the Sestor ships - but compensate with stronger shields. Actually, this is a strength of the Mereti, since shields recharge faster than the hulls are repaired.
Lore-wise, as both factions are pretty much evened out (so equal, that the other aliens lost their hope that either side would win) I would prefer having their capital ships being closer together, just by adding that one small heat shunt.

Attachments:
- a data file with two cinematic missions: watch a fight
- two savegames, one for each of the cinematic missions, in a changed sol system (almost no asteroids, no republic fleets, no merchant fleets...) -- you launch immediately after loading -> you should immediately cloak since both automata ships are already in the system!
- an additional 5 vs 5 savegame
- a screenshot from both ships being disabled in the 11th heavy warship battle

[cinematic_mission_kor_sestor_vs_kor_mereti.txt](https://github.com/endless-sky/endless-sky/files/911445/cinematic_mission_kor_sestor_vs_kor_mereti.txt)
[Testing Tester~Watch Kor Sestor KPT 53 vs Kor Mereti M32.txt](https://github.com/endless-sky/endless-sky/files/911447/Testing.Tester.Watch.Kor.Sestor.KPT.53.vs.Kor.Mereti.M32.txt)
[Testing Tester~Watch Kor Sestor KIV 349 vs Kor Mereti M512.txt](https://github.com/endless-sky/endless-sky/files/911446/Testing.Tester.Watch.Kor.Sestor.KIV.349.vs.Kor.Mereti.M512.txt)
[Testing Tester~5 vs 5.txt](https://github.com/endless-sky/endless-sky/files/911615/Testing.Tester.txt)

![endless_sky_v0_9_6__20170410__kor_kiv349_vs_m512_both_disabled](https://cloud.githubusercontent.com/assets/26883037/24882454/64db0806-1e41-11e7-9d29-0291ceaaeb72.jpg)

**Comment by Bladewood** [comment]
can I just point to this https://github.com/endless-sky/endless-sky/issues/1628
k
k bye

**Comment by EndrosG** [comment]
That says, if I had taken 20+ Light Warships on each side, the Mereti would have almost always won because of the piercing, correct?

I wonder if we could use the "swarming" intelligence to prevent 20 mereti ships to take out the sestor ships one by one. I.e. limiting the number of ships which attack an enemy at once.
The most obvious problem of this idea are different ship classes. Having, e.g. 6 fighter or drones attack a capital ship differs from 6 light warships attacking another light warship, which again differs from e.g. 6 capital ships attacking one medium warship.
The second issue is to find some reasoning for that.

So, using a different approach to limit the piercing effect, like the one(s) mentioned in #1628, sounds better than my thumb idea.
That is interesting to work on, but different from this post.

**Comment by gunqqer** [comment]
Yo this is really really cool. Next you should have them fight my outfitted 349s... the ones with 6 skylances 2 blue suns and a nanotech (plus a lot of other outfits)

**Comment by EndrosG** [comment]
Hmm, why dont you do it yourself? I attached all files I used. The mission file and ready to use savegames which do not require anything else. That is, I did prepare an (imho) acceptable test environment for almost any SvS or FvF battle.
Would be nice if you shared your results. I bet your 349s are even stronger than the vanilla ones and thus the Mereti will fail even harder in that testbed.

**Comment by KiLEdEnNis** [comment]
what's this issue about exactly? I don't feel like reading several paragraphs for it

**Comment by EndrosG** [comment]
If you are interested, please try reading at least the first six lines which include a summary. I dont feel like copy pasting the summary again. :-P

**Comment by jafdy** [comment]
I don't see the point of this. First off it is far too long for a bunch of people developing a game in their spare time to go through properly. Secondly the balance works as is, in the short time I looked at it I found no argument as to why there should be any change.

**Comment by Wrzlprnft** [comment]
i thinl this is too much based on different ship classes fighting within. if i stay in the system they two fight in, it seems like no side can get an advantage and collect enough leftover ships on the long run

**Comment by gunqqer** [comment]
I would test it myself but my crappy computer couldn't handle that much. And yes that is a lot for my computer

**Comment by Elyssaen** [comment]
The summary, as I understand it, is that the Model 512 has more unused outfit space than the Kar Ik Vot 349, and using the difference on an additional Small Heat Shunt (a trivial, logical tweak) brings the two in line in a one-on-one.

This makes sense to me. Maybe it's not the most important tweak imaginable, but it's fine nonetheless. And trying it out in Mesuket, it... well honestly, it makes no difference either way. The Model 512 is just too rare for Mesuket (or any in-game fleet presence) to ever give a good view of one-on-one balance.

Lastly, I for one appreciate a well-researched post. : )
