### ISSUE TITLE
mechanics/enhancement: unable to restore energy via 'request assistance'

### ISSUE THREAD

**Issue by nkrul** [endless-sky/endless-sky#2400]
Energy seems to not be included in the 'request assistance' or 'boarding' options.
This includes trying to help escorts.

If you don't have a generator to replenish your power reserves, you can end up stuck and requiring a reload.

Given that assistance can restore hull & control and donate fuel, shouldn't energy be on the list?

**Comment by MessyMix** [comment]
Not that I'm against your suggestion, but seriously...

Do you really want to be boarding your escorts every time you try to move!? Get a generator! It doesn't take that much space, and it's literally _essential_ for actual gameplay.

I'm almost certain that the game intends for you to either have a really high battery capacity, or at least a basic generator. It's futile trying to fly your ship(s) with no generation, especially when you get to the actual game content (i.e. battles, long-distance trading, storyline).

If you know C++, you can go ahead and code it yourself and see what the developer thinks. If not, my guess is that you're going to have to enlist the help of a programmer. My guess is that the developer won't go out of his way to create a feature that will only really cater to the super-early game (or super late-end players who are min-maxxing their freight ships, and at that point you're just _asking_ to get stuck :P).

**Comment by KiLEdEnNis** [comment]
I remember an issue where this got addressed; basically I compared it to cars: getting fuel into one is quite easy, reloading the battery isn't
having no generator is like having your ship be 1 heat off of overheating or having no thrusters besides an afterburner; it's just a dumb idea in general

**Comment by nkrul** [comment]
Chill - I installed a generator. I'll submit a patch against this issue.
I raised this because it allows you (or escorts) to get stuck, which I consider to be an error condition. If there are 'helpful' ships around, then you shouldn't be stuck.

**Comment by Amazinite** [comment]
Duplicate. #1813

**Comment by endless-sky** [comment]
There are plenty of cases where a ship can get stuck due to the player doing something silly. (For example, yanking out a ship's engines and then capturing it.)

Running out of fuel is a really common occurrence for new players, and it makes sense for other ships to help you out. Running out of energy, on the other hand, is impossible unless you've modified your ship in ill-advised ways.
