### ISSUE TITLE
minor: inappropriate hail (mechanics?)

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2403]
Testbed: I am surrounded by "Navy surveillance" fleets only.
The cruisers and gunboats answer on the hails -- the crewless drones dont. The latter is fine.

Sometimes they tell me the Navy would be there to help me, but then they refuse to help me, because they are too busy.
Yeah, they are busy scanning me -- all of them, permanently :-D

**Proposal**
Modify (HailPanel.cpp, Line 243)
>			else if(ship->GetPersonality().IsSurveillance())
>				message = "Sorry, I'm too busy to help you right now.";

into something like (20% chance that the ship will help, 80% chance it refuses for now, better answer):
>			else if(ship->GetPersonality().IsSurveillance() && Random::Real() > 0.2)
>				message = "Sorry, I'm too busy to help you right now. Please try again later.";

What do you think?

[Testing Tester~non-smart refuelling in Sirius system (2).txt](https://github.com/endless-sky/endless-sky/files/919888/Testing.Tester.non-smart.refuelling.in.Sirius.system.2.txt)
![endless_sky_v0_9_6__20170413__personality_surveillance_does_not_help](https://cloud.githubusercontent.com/assets/26883037/25008919/5a129c1a-2065-11e7-9c42-f81a58186da1.jpg)

**Comment by KiLEdEnNis** [comment]
he didn't say he does his job well...

**Comment by MessyMix** [comment]
"The Navy is here to [...] help you" ≠ "I will personally help you at this very moment".

I don't see the problem here.

**Comment by Amazinite** [comment]
Change help to assist if this is really necessary?

**Comment by EndrosG** [comment]
@Amazinite : the current code explicitely says, that ships with personality `surveillance` will not assist under any circumstances. My proposal is just to give it at least a chance. I.e. instead of them refusing the request in 100%, let them just refuse in may be 80%...

**Comment by Amazinite** [comment]
Then what is to stop people from just repeatedly hailing surveillance ships, esentially meaning that you're going to get an assist from then every time anyways.

**Comment by Bladewood** [comment]
Same problem applies to hailing a ship you've just bribed.

**Comment by KiLEdEnNis** [comment]
don't surveillance ships deny requests to avoid people cheating by asking them to help, which means they aren't getting scanned?

**Comment by tehhowch** [comment]
Simple: surveillance personality remembers if they've scanned you yet, today, in this system. If not, then they will be happy to help - after they scan you. :+1:

**Comment by EndrosG** [comment]
@tehhowch after they *successfully* scan you ;-)

**Comment by Bladewood** [comment]
How would they know if they were *really* successful?
