### ISSUE TITLE
Militia hail: "cannot" vs "can not"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2409]
https://github.com/endless-sky/endless-sky/blob/master/data/hails.txt#L1193
> We can not be defeated

~~If you wish to get into an argument, I will start and finish it like so:
"Can not" implies that you have the option of not doing so.
"Cannot" implies that you are unable to do so.~~

**Comment by Amazinite** [comment]
https://en.oxforddictionaries.com/usage/cannot-or-can-not

Same meanings, so the second part of what you said is wrong and irrelavent. It's right as is, and using cannot is right as well, but at this point it's a matter of using whatever word comparing thing that MZ does and seeing which one really is more used, and him deciding it something to change.

**Comment by Bladewood** [comment]
Fine.
But as that page notes, "cannot" is more common than "can not".
I still think it should be changed.

relevant: https://english.stackexchange.com/questions/4510/why-is-cannot-spelled-as-one-word

**Comment by endless-sky** [comment]
I think it depends on where the emphasis goes: are they saying, "We can *not* be defeated," or "We *cannot* be defeated"? To me "cannot" seems like the better option, but it's not technically an error to use "can not" if you're trying to emphasize the "not."

**Comment by tehhowch** [comment]
cannot

or, remove ambiguity and change it to `will not` :+1:

**Comment by Bladewood** [comment]
that should be its own ending word thing in the phrase instead

**Comment by endless-sky** [comment]
Fixed by merging #2410.
