### ISSUE TITLE
asking for some advise regarding blender models... realism/perfectionism

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2411]
I downloaded the ships assets from the Google Drive.
Right now I want to ask for some advise on realism and rendering

**Realism**
First I took a look at the star barge and the freighter, because I am interested in creating a modifyed version of one of these.
Before I downloaded the assets, I always wondered, why the Star Barge has 2 visible rows of containers with 50 tons cargo space = 25 tons per container row and the Freighter has 7 visible rows with 150 tons. 6 rows would result in 150 tons...
After I had the assets and opened them, I saw their full 3D model. The Barge has 1 container at the bottom, resulting in a total of 5 containers, i.e. 10 tons cargo space per container. The Freighter has 7 containers at the bottom, resulting in a total of 21 containers (still having "only" 150 tons cargo space).

So I wonder if there is any guideline to follow when scaling up models which share the same type of caro hold. My perfectionism would say: the Freighter should have only 5 rows of containers (3 per row), or it should have 210 tons. But that's my ****** perfectionism which is not always the best advisor.

**Rendering**
Is there any best practise on how do you decide upon the scale of the final PNG? Since different assets use different camera zoom, I am lacking a fixed size reference.
So... when I have to alter the zoom, how do I really know how far I should downsize the final image in the post-processing?

**Comment by Wrzlprnft** [comment]
as hard as it sounds, since there will always be just a 2D perspective, not all models may make satisfy your perfectionism.
though, for the size, i'd recommend just scaling them, test if it feels right ingame. if you want to stick to numbers, feel free to do so, but that's a bit of extra work.

**Comment by KiLEdEnNis** [comment]
visuals is to look good, stats is for balance, you don't have to balance a ship based on the visuals, or change the ship looks because of the stats
example: my Freighter line for my Derogam project (on my profile), you should compare those in 3D...

**Comment by Wrzlprnft** [comment]
it's not thaaat unrelated, and from previous issues i can see of how much of a perfectionist you (endrosG) are.
if you want, you can adapt existing ships to fitting numbers(cargo etc) if MZ approves.

**Comment by endless-sky** [comment]
The best way to set a ship's size is to figure out what you want its stats to be, then pick some existing ships with similar stats and make sure the sprite is the same size as them.

Or, you can take the alternative route: adjusting the sprite size until it shows the right amount of detail, and then deciding how powerful the ship ought to be and how much space it should have based on the sprite...

![point defenses](https://cloud.githubusercontent.com/assets/11450262/25065436/1b1c5134-21de-11e7-8927-473aa46efde5.jpg)

**Comment by KiLEdEnNis** [comment]
is that a sneaky preview of something you're working on?

**Comment by endless-sky** [comment]
Of course. :)

**Comment by Wrzlprnft** [comment]
you're a hell of a tease...
my first thought was a skylark remodel, but ill look forward to be proven wrong

back on topic:
there is also the kor sestor largest ship, the 349, the commit which made it smaller, and changed stats. could inspire.

**Comment by Bladewood** [comment]
oh my god that thing looks awesome

**Comment by endless-sky** [comment]
![starling side view](https://cloud.githubusercontent.com/assets/11450262/25068355/b2817f86-222e-11e7-9a3b-d51ee0c206b7.jpg)

Called the "Starling," for obvious reasons.

**Comment by Pointedstick** [comment]
These perspective-rendered ship graphics reeeeeeeeally need to make it into the shipyard view, somehow. They're amazing. I always loved that feature of EV Nova. The pre-rendered ship depictions were _incredibly_ awesome.

**Comment by MessyMix** [comment]
@Pointedstick, that's an amazing suggestion.

Here are 2 things I can think of right now: 
1. Have a pre-rendered image show up in the empty space every time you view details of any ship.
![image](https://cloud.githubusercontent.com/assets/20450076/25156245/723b2fc2-2467-11e7-98a0-ea733ce89aa8.png)

2. Have a preview button somewhere that will load a picture of the pre-render. (Best to for it to be a high-res image, though).

**Comment by EndrosG** [comment]
There is one downside... Currently a big part of the texturing is done in GIMP as part of the post-processing.
You'd need to somehow apply those layers which you usually apply in GIMP already in the 3D rendering process.
Otherwise the 3D rendered image often wont look as good as the 2D top view.

Here an example of my extended Hauler freighters:
![hauler iv a37x atomic](https://cloud.githubusercontent.com/assets/26883037/25157511/2c855dbe-24a2-11e7-8147-b3ad281251cf.png)
![hauler vi blend 3d front view](https://cloud.githubusercontent.com/assets/26883037/25157519/36129d92-24a2-11e7-8d0c-54d41ecde7c6.png)

I still have to do the post-processing for the latter version (in 2d, of course).

**Comment by EndrosG** [comment]
Oh, and I finished my first own ship model. 90% from the scratch, only took some parts from the Dreadnought for the Cockpit.
I'll upload some pictures tomorrow when I make the first commit of that plugin ("Eireen") in my repo.

**Comment by endless-sky** [comment]
Having separate ship images for the shipyard was discussed a long time ago.

In EV, if you wanted to create a new ship, you needed to create four separate images:
* The ship sprite itself (typically rendered at 36 different angles and assembled into a 6x6 grid).
* A shipyard image, showing a side view of the ship.
* An image to show when hailing the ship, showing a front view as if facing it.
* A line drawing to be shown in the targeting display when the ship is targeted.

That did allow for some cool shipyard images, but it also meant that the barrier to entry for someone wanting to make a new ship was *much* higher. The nice thing about how ES works is that you can even draw a ship by hand if you want, and never worry about having to draw different views of it.

**Comment by Pointedstick** [comment]
> The nice thing about how ES works is that you can even draw a ship by hand if you want, and never worry about having to draw different views of it.

Does anybody do that? _Will_ anybody do that? In theory this is a nice feature, but in practice, wouldn't anyone who wants to add a new ship be able to provide a cool perspective image of the ship as well?

**Comment by MessyMix** [comment]
I mean, you could hand-draw a perspective view of the ship, too, if you're already hand-drawing the sprite.

**Comment by EndrosG** [comment]
@Pointedstick 
two things:
first, I miss the .xcf GIMP file for your Pointedstick Vanguard in the Google Drive folder. Or better said: when I downloaded the entire folder as .zip, it was the only file with 0 bytes. :-/

second, in reply to your comment:
You know we mostly use GIMP to add the textures to the rendered images.
Rendering some 3d view is not the issue, once you have the model. But having them in the same look (texture-wise), is where I fail right now.

This is my current ship, which I mentioned above / yesterday...
Today I did two versions of finishing with GIMP and I hereby ask which looks better - left or right side.
And how would you apply the textures to the 3d renderings? I will use at least one of those 3d renderings in a "mission", so this question has some relevance to me.

![nosy i gimpy](https://cloud.githubusercontent.com/assets/26883037/25188859/bec30a02-2527-11e7-91b8-c26db26822f0.png)

![nosy i blend 3d](https://cloud.githubusercontent.com/assets/26883037/25188884/d1b980e6-2527-11e7-86bd-44ab9d09fd9a.png)
![nosy i blend rear 3d](https://cloud.githubusercontent.com/assets/26883037/25188883/d1b3b896-2527-11e7-9741-a0ed94e7cfed.png)
![nosy i blend side](https://cloud.githubusercontent.com/assets/26883037/25188885/d1bdc750-2527-11e7-8a34-f39b754a2c3f.png)

**Comment by Pointedstick** [comment]
Whoever maintains that folder of art assets (@endless-sky?) here are the missing files:

[Vanguard heavy warship.zip](https://github.com/endless-sky/endless-sky/files/935787/Vanguard.heavy.warship.zip)

**Comment by Wrzlprnft** [comment]
ill check the captain nate vanguard assets as soon as i can.

**Comment by Wrzlprnft** [comment]
and to the topic:
getting the textures into blender is a step up...
most importantly people will tend to use the cycles render engine for that, since it's nodes allow more flexibility with that... and currently, using the blender internal render engine is part why the blender stuff is rather easy

**Comment by EndrosG** [comment]
@Pointedstick : I meant the "Pointedstick Vanguard", not the standard vanguard.
But I just saw, that the files for the original vanguard were not included in my download at all. I didnt even miss it yet, lol.

@Wrzlprnft : Generally I would be interested to have textures already at the blender level (for my new ships), but I dont have all those textures and not yet the experience with blender. In the past decades, when I sometimes worked with PovRay and/or Cinema4D, I always tried to keep post processing at a minimum, and to include as much as possible into the model itself.

-----

> I'll upload some pictures tomorrow when I make the first commit of that plugin ("Eireen") in my repo.

I did that upload of the current state of my Eireen plot. It's all in the [Eireen subfolder](https://github.com/EndrosG/ES-Plugins/tree/master/Eireen) of my plugin repo.
I did not have the time yet to playtest it. Writing the first main conversation (mission: First Contact) took me two days. I bet some of you could help me improving grammar and wording.

**Comment by Elyssaen** [comment]
Hey @EndrosG, so I stuck those two renders into my game side-by-side. At first I thought the ship was a little big:

![endros_compared1](https://cloud.githubusercontent.com/assets/23544894/25879218/4d15a016-3528-11e7-9bff-10d182901efe.JPG)

but I figure this was probably the @2x version, so reconfigured it:

![endros_compared2](https://cloud.githubusercontent.com/assets/23544894/25879223/5fed9018-3528-11e7-88b1-0ac2f777ed16.JPG)

At the smaller size, I really like the design. It could still maybe do with a _little_ more detail, but I'm not sure... I'm generally not a good person to give advice on art, as I might have a view on what I like and don't like, but I don't know enough to know how to express it.

I definitely prefer the darker textured render. The first is reminiscent of Escape Velocity Classic's Luxury Liners, but the second is more in keeping with human designs.

(The non-standard ships above are from Phil's Flavours, which I always run in my game... if anything the ships are a little underpowered, but they make nice background and are very pretty.)

**Comment by EndrosG** [comment]
tyvm for the feedback on the nosy ships.
So, including you, I now got *two* feedbacks, both saying they like the dark version more.
Accepted.
