### ISSUE TITLE
Banking Problem

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2414]
With a credit score of 800 I got a large loan to buy and upgrade a new ship.  I'm using a radical repayment method that has me paying every thing over the costs to get to the next port.  Occasionally I need to take out another loan to cover costs.  When I do that I keep over paying on the earliest loan.  Any subsequent loans reduce my credit rating, which is not unreasonable, but the automatic payments increase the loan balances.  For instance, on a 1MCr loan the payment is 2000 after a 1 jump trip instead of a balance of 996,000 it's 1.004MCr, there was sufficient cash on hand to make payment on all loans and pay the crew.

**Comment by endless-sky** [comment]
The game advances one day every time you take off from a planet, in addition to every time you jump to a new system. Could that be your problem? Or, could it be that you had additional back salaries to pay?

Or, if you think that there's a bug, could you post a saved game that demonstrates it?

**Comment by VonZorch** [comment]
Additional time taken into account.  Not possible for back salaries, I make sure that there is cash on hand to cover all expenses to the next port.  I don't have any of those, I reverted to a save before I noticed the bug.  I'll fork off a run to get a save.

**Comment by VonZorch** [comment]
Never mind, I just remembered I got caught running drugs and went over budget.
