### ISSUE TITLE
ship->description vs. mission->description : bug?

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2417]
While writing some workaround upon a thing I commented in issue #1564, I was trying to use a mission description with two separate lines.

Example:
```
mission "some mission"
	name "some name"
	description "Eireen reminded you to make your payment of 11.9M credits within 7 days."
	description "IMPORTANT: You need to have the money available when upon LANDING."
```
This did not work as expected. My expectation was derived from the way, descriptions are assembled in ship definitions.

A quick look into the code confirmed, that Mission::Load(const handles "description"(s) much simpler than Ship::Load(const
I would already be happy if I could use some line separator, but 
```
	description "Eireen reminded you to make your payment of 11.9M credits within 7 days.\nIMPORTANT: You need to have the money available when upon LANDING."
```
did not solve it either.

I would go ahead and open a submit a pull request, if I had a better feeling of how @endless-sky would change it. If he is not even assigning `unlikely` or `wontfix` to this matter.

I know that space is limited in the mission description box. All I wanted to do was separating the real description from a technical hint (upon game mechanics) regarding negative payments...

**Comment by endless-sky** [comment]
I'd recommend just putting the note in parentheses. (It's a short enough amount of text that just setting it apart in that way will provide enough visual distinction.)
