### ISSUE TITLE
Have turret orientations appear on hail screens

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2423]
That is, whenever you hail a ship, it should also display its turrets with their current facings like it does in regular gameplay.

Because it's pretty. And so we can get a better view of a ship's arsenal or something...

**Comment by KiLEdEnNis** [comment]
it can help in combat as well; look at what the enemy ship is shooting at or at what it can shoot
example; ya are flying a nimble ship & press R to target a big ship outside of visual range, you may want to know its turret orientation: is it facing near you or the opposite side? (assuming other small ships are attacking it, or else attacking that big ship seems rather dumb)

**Comment by gunqqer** [comment]
Question: Is this due to the changes of turrets having rotational speed? I just want to clarify and make sure I am not going crazy (which I still might be)

**Comment by MessyMix** [comment]
@gunqqer: that's still coming. It's in anticipation of the rotation speed, but it's not yet implemented.

**Comment by EndrosG** [comment]
This is not the primary topic of this issue, but partly belongs here so I dont open a new one.
**suggestion for enhancement** : allow for over / under / inside(?) for hardpoints too, the same way it works with bays. "under" is straight forward. "inside" would disable the optics for that specific hardpoint.

**Comment by MessyMix** [comment]
What would "under" (straight forward) do? What is it supposed to look like? It sure won't look like the turret is under the ship, though..

**Comment by EndrosG** [comment]
Why not? Draw the sprite of the weapon below the ship as with the fighters.
That is, they wont be visible in all cases, but some content creators might want to have not all turret mounts on the upper side. Combat wise it does not matter if a turret is "over" or "under", since the game is 2D.
But the models are somewhat meant to be 3D or to at least give a 3D feeling. And putting all weapons on the upper side feels a bit strange to me.
Most front guns are placed "under" in the models. I know... gun != turret

**Comment by MessyMix** [comment]
yes, but why straight forward!?

**Comment by jafdy** [comment]
"Straight forward" as in "what it sounds like", not as in "always point forward".

**Comment by Bladewood** [comment]
from now on, use "straightforward", not "straight forward" when you're talking about this.

they may look similar, but they have entirely different connotations.

**Comment by Bladewood** [comment]
I assume this is fixed by https://github.com/endless-sky/endless-sky/commit/8d95726fb158536b754eabc99f2cab5a05553cee.
