### ISSUE TITLE
FW Militia is part of Republic Planet's Defensive Fleets

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#2428]
Just came across this, most Dirt Belt or South Planet have a Militia Fleet as defensive Fleet. So if you're dominating Republic Planets, your FW reputation will drop dramatically.
Now, i know the definition of the word "Militia" (and it makes sense for those planets to have a local Militia as the Navy is Mainly about the Paradise Planets), but it should be _local_ or _independant_ Militia, not official FW Military - or is this lored somehow?

**Comment by lheckemann** [comment]
Duplicate of #1289

**Comment by MCOfficer** [comment]
good catch, i wonder why i didn't find this.

but it still doesn't explain why attacking _local_ militia lowers your FW Reputation.

**Comment by Bladewood** [comment]
[warning: just woke up]
How does that not explain it?
This would piss off the Free Worlds to several levels. You're attacking innocent worlds and the volunteer guardians who rose up to defend them, not unlike the Free Worlds themselves.

**Comment by Wrzlprnft** [comment]
further, unlike the republic, a good chunk of the fw were local militia before

**Comment by MCOfficer** [comment]
ok, you have my vote. lorewise, at least.
