### ISSUE TITLE
Expand pug storyline

### ISSUE THREAD

**Issue by kjack1111** [endless-sky/endless-sky#243]
I used the map editor to get a travel route to deneb, and what i found was strange. PUGS. like, dog pugs, or alien pugs? They need more storyline! more Missions! more EVERYTHING!

IF im missing somthing here, then close this issue, lawl.

**Comment by thenerdfreak** [comment]
The pugs come up in the main story, but sadly they don't appear after that (look and capture all the ships you can; they can be useful for the jumpdrives and unique weapons)

**Comment by kjack1111** [comment]
I actually have no time for the main story line lel. spoil awaaaay.

**Comment by endless-sky** [comment]
If you want a story and missions connected to the Pug, you'll need to play through the main story from the start.
