### ISSUE TITLE
Odd message when scanning an escort

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2434]
I scanned one of my escorts, and received the message "The Escort ship Bertha succeeded in scanning your outfits." (Bertha is the name of my flagship).

**Comment by EndrosG** [comment]
Logic explanation: You receive a message whenever any of your escorts is being scanned - no matter who scanned it.

**Comment by lheckemann** [comment]
Of course, but having your flagship referred to as “The Escort ship <name>” is weird.

**Comment by EndrosG** [comment]
Escort is the government, like the Republic ship.... But I understand your point.

**Comment by lheckemann** [comment]
I fully understand how this happens, but my point is that it shouldn't.

**Comment by EndrosG** [comment]
that should fix it.
