### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#2439]
Throughout the game I have been having random crashes, sometimes in combat, sometimes post-combat flying around to capture ships, and sometimes even in mission dialogue on planets. I haven't been able to pinpoint the cause, although it often happens mid battle or post battle, with the planet crashes usually those that append a space battle. it doesn't always happen, but depending on how long the battle takes it can happen sequentially after I have reloaded. I'll reinstall the game tonight and double check if it still happens.

**Comment by EndrosG** [comment]
just a few standard questions, which may help us tracking down your issue:
1. Which game version do you run? - Examples: Steam release v0.9.6; a pre-compiled download; self compiled from source
2. Which operating system do you use? - Examples: Windows, Linux, MacOS + version
3. Do you have also problems with other games/software? - In issue #2385 most likely the user has a problem with his installed OS, because he also has trouble with other software too.
4. Do you have any mods / plugins installed? I.e. any content extensions or just the default data files which came with the game?
5. Did you check the errors.txt file?

**Comment by SirStigII** [comment]
1. Steam 0.9.6
2. Win10
3. No
4. Not until last night, still happened after I added the mod
5. No, I'll check that tonight, and upload the pilot file. I did edit the pilot file to redo the kestrel mission, so I might have messed it up when I did that... I can't honestly say it was happening before, but I _think_ it was...

**Comment by EndrosG** [comment]
The better question would be, if it happened already before you installed/added the mod.

*My steam version was always a bit sensitive to my own attempts to add new content. I tried to be creative and wanted to do things which were not meant to be done this way and thus didnt work.* ;-)

Back to your issue:
- Did/does it crash *only* in the kestrel conversations which you eventually messed up? Or also on other jobs/missions?
- Did/does it crash *only* in/after battles somewhat related to the kestrel?
- Which mod is it? (eventually with link to the source) - just in case the problem relates to the content of that mod.

If you manage to reproduce a crashing situation with one of your savegames, the precise information would be helpful, together with the savegame of course.

**Comment by SirStigII** [comment]
- It happened before I added the mod (UP), I just noticed it happening with the mod as well.
- The kestrel does not seem to be involved, as I don't have any in my fleet, and MZ can't be showing up _that_ often
- Ursula Polaris, but as I said it was happening previous to downloading that.

**Comment by SirStigII** [comment]
[Tiff Heron.txt](https://github.com/endless-sky/endless-sky/files/948509/Tiff.Heron.txt)

**Comment by SirStigII** [comment]
[Tiff Heron.txt](https://github.com/endless-sky/endless-sky/files/948668/Tiff.Heron.txt)
Literally happened just now on the way to wanderer home base

**Comment by jafdy** [comment]
It's nothing in your save file. If you want to check you can make a new pilot and see if you still get crashes.

**Comment by SirStigII** [comment]
[errors.txt](https://github.com/endless-sky/endless-sky/files/949126/errors.txt)
Could it be related to this?

**Comment by jafdy** [comment]
Probability. Crashing at random would be explained if a random fleet was generated using the invalid ships. Try removing all data files and reinstalling them, if your using steam then you can just validate the files.

**Comment by EndrosG** [comment]
"IPSRnD" relates to your plugin / mod.

**Comment by SirStigII** [comment]
I did validate the local files already, but maybe a reinstall might be in order.

**Comment by SirStigII** [comment]
So it definitely happen on my personal computer, but not my work laptop. Work laptop is win7 64bit with integrated gfx, personal is win 10, gtx 770. All drivers up to date. All installations done identically.

**Comment by SirStigII** [comment]
Well as an update it still happens randomly, only on my home desktop, on both steam version and compiled version, with brand new pilot files. I'm going to just live with it for now, but at some point I'll do a fresh windows install with just steam and ES.
