### ISSUE TITLE
Random speeding up and slowing down of the game

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#244]
It's literally almost as if I have cheat engine halving the speed of the game, then it jumps to normal speed every few minutes or so, no idea what's causing it

**Comment by endless-sky** [comment]
Is this on Windows? And are you running version 0.8.7, or the latest code built from source? Does the problem go away if you play a video in the background (youtube, say)?

**Comment by thenerdfreak** [comment]
Windows 8 ( 16 GB ram, decent graphics card ) Steam version (because don't know if GitHub version will drop the progress) and actually it momentarily does for some reason

**Comment by endless-sky** [comment]
On Windows, by default when the OS has nothing to do it will put the CPU into "idle" mode for 1/64th of a second at a time. That "interrupt rate" limits how accurately a game can control the frame rate. Some applications (like video players) reduce the interrupt rate to 1/1000th of a second, which lets you time frame rates more accurately but also eats up about 25% more power (which matters to laptop users). Up to and including version 0.8.7 I'd been trying to avoid messing with the interrupt rate for the sake of being nice to laptop users, but in 0.8.8 (which I'll hopefully release tomorrow) I've switched to just requesting the higher interrupt rate, like a video player does.

The interrupt rate is a system-wide setting, so if you play youtube in the background and it requests a higher rate, that affects all the other programs on your computer - including Endless Sky, in this case.

**Comment by thenerdfreak** [comment]
Probably an issue due entirely to ignorance on my part, but I SVN'd the github version and I can't seem to find where to run the game at (will play again tomorrow since that fix is being released)

**Comment by endless-sky** [comment]
Check and see if the frame rate bug is fixed in 0.8.8.

As for downloading the game through SVN, that gives you access to the source code. The [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions) explain what you need to do to compile the program.

**Comment by endless-sky** [comment]
This issue is fixed in 0.8.8, and 0.8.8 is now the default on Steam, so I'm closing this issue.
