### ISSUE TITLE
intended? no weapon section within the attribute section of ships in savegames

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2440]
As far as I can see from my existing savegames, no single ship definition has a `weapon` child within the `attribute` child of a ship definition.
Neither the player ships, nor the NPCs in active or available missions or jobs.
I got confused because I did not find any hints in the wiki article related to ships and variants, nor did the search for issues provide good results because I was lacking good search keywords. (`ship weapon variants` gave me only irrelevant results).

Looking at Ship.cpp, Line 260+, the `explosionWeapon` stats are always taken from the base class.

**Two questions** arise from that.
1. Is it intended that `variants` can't have different weapon values then?
2. Would you prefer content creators to *not specify* a `weapon` child within the `attribute` child?

It would be nice to have some sort of summary about using variants vs. new ship definitions. I know your comment in issue #2363 ("bug: ship prices for variants") and just read it again.

As a content creator, I always look for examples in existing data and seeing the weapon child in the variants with attribute nodes, let's me think (in the first place) that I could modify that in variants. I am going the hard way to find out the limitations, I guess.

----

I have checked the following files: kestrel.txt, marauders.txt, wanderer ships.txt, korath ships.txt, hai ships.txt, coalition ships.txt and the variants.txt
The first three (kestrel, marauders, wanderers) define variants with different attributes but always identical weapon stats (identical with the base ship). And they always explicitely define the weapon stats for a variant.
The latter ones (korath, hai, coalition, human variants) use only variants with different outfits, but same base attributes.
Pug and Quarg dont use variants as far as I could see.

So the current existing data is fine & save. I bet others have checked that before me. :-)

**Comment by KiLEdEnNis** [comment]
the ship you have is a base ship like the stock variant, the death weapon doesn't change, so why would it have to be in the save file
and variants are just the same ship w/ a different outfit setup, it'd make no sense if they had different death weapons, if ya want to make death weapons vary, make multiple ship types like the Deep River

**Comment by Bladewood** [comment]
I do remember talking to Michael about something like this. He said it was intentional.

**Comment by EndrosG** [comment]
@Bladewood : thanks, I really didnt find it with the search.
@KiLEdEnNis : following your argument, one could easily say that mentioning the base attributes (cargo space, outfit space, etc.) is irrelevant too, since these dont change during a ships lifetime. If you alter the current stats by outfits, like Cargo Expansion etc., the base stats still stay the same. The only thing is, that these vary amongst variants and the game currently does not remember which variant a ship originally was.

**Comment by endless-sky** [comment]
The basic explanation is that every projectile in the game (even the invisible projectile created by a dying ship's explosion) needs a link to the weapon that created it. But in the case of a dying ship, the ship is already deleted, so it has to link back to the "weapon" definition in the ship's prototype, instead.

Fixed in e22e3c5.

**Comment by EndrosG** [comment]
@endless-sky : one possible alternative would have been to make the game aware of the variant and have those prototypes as well with the weapon definition, being able to link back to it.
We have other "issues" too which would benefit from a variant-awareness.
But at least the data is more clear (and clean) now, thanks. :+1:
