### ISSUE TITLE
New to Github, and I've got a bit of a stupid question...

### ISSUE THREAD

**Issue by AustinKnauss** [endless-sky/endless-sky#2441]
I started playing the game on steam, and then downloaded it here on GitHub, because I wanted to edit a few ships and things like that. How do I start the game though? I've already made my changes...
If this post isn't allowed, just remove it.

**Comment by tehhowch** [comment]
If you change source files (*.cpp, *.h), then you need to recompile, and then launch the new executable.
 https://github.com/endless-sky/endless-sky/wiki/BuildInstructions

If you just modify text files (*.txt), then you can use the plugin method
https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins

**Comment by KiLEdEnNis** [comment]
just add the stuff you make in your plugins folder: AppData > Roaming > endless-sky > plugins

**Comment by AustinKnauss** [comment]
All I did was edit the start. No mortgage, and an outrageous amount of credits.. I just don't know how to run the game now. I've never used GitHub, and I'm fairly new to writing code.

**Comment by tehhowch** [comment]
If you edited a .txt file, then you do not need to recompile the source. Launch the game as normal, with your edited .txt files in the appropriate places as though you made a plugin. See the plugin link above.

If you edited a .cpp or .h file, then you need to recompile the source. See the build link above.

If you downloaded source and never built it, then you need to compile the source. See the build link above.

**Comment by Bladewood** [comment]
Here is my guess:
He played the game.
He then came to GitHub and downloaded the source files for the game.
He edited start.txt in the downloaded source files.

You don't have to do this.
Just go find the game files in your Steam directory.
Edit start.txt there.

**Comment by AustinKnauss** [comment]
@Bladewood Sounds about right... Thanks for the answer though.

**Comment by MessyMix** [comment]
do you know where your steam game files are?

**Comment by AustinKnauss** [comment]
Yeah. I've got it under control now.

**Comment by Bladewood** [comment]
In that case, you can close this issue now.
For future reference, any subjects like this should go on [the Steam forums](http://steamcommunity.com/app/404410/discussions/0/), the [Google Groups forums](https://groups.google.com/forum/#!forum/endless-sky), or some other place (try the [subreddit](https://www.reddit.com/r/gamindustri/)), but not here.

**Comment by AustinKnauss** [comment]
Thanks for the help. Sorry about wasting your time.

**Comment by MessyMix** [comment]
I'm sure everyone here is willing to help you. Don't worry about it. :D

**Comment by MCOfficer** [comment]
@Bladewood nice subreddit you got there :smirk:

**Comment by Bladewood** [comment]
@MCOfficer SHT, WRONG ONE
