### ISSUE TITLE
Uninstall outfits

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2443]
The problem: When a ship has an outfit installed, and the player has more of the same outfits in cargo, and player wants that outfit uninstalled, (s)he first has to sell all outfits in cargo, then uninstall said outfit, then re-buy them all back. If outfitter happens to sell those same outfits, then player can't just sell all and buy back all, (s)he needs to keep track of how many exactly of them (s)he had.

1. Player should be able to uninstall outfits directly to cargo;
2. Player should be able to sell ship's outfits without touching outfits in cargo.

The second point could be solved by letting game sell player's outfits in cargo only when no ship is selected. If a ship is selected, then first outfits to go are those installed on a ship.

The first point most likely would need an additional button.

**Comment by KiLEdEnNis** [comment]
it's either first sell cargo or first uninstall stuff, & a lot of players don't know you can unselect all ships to buy & sell from the cargo hold
so either way there'll be some problems

**Comment by Jorlem** [comment]
Couldn't that be helped by adding a "Cargo" button to the Outfitter interface, perhaps above where the ship icons are displayed? That button could do the same exact thing as deselecting all ships does now, it could even just be a "deselect all ships" button labeled "Cargo", but it would be obvious to players that the functionality exists.

Then, as the interface when a ship is selected wouldn't need to pull double duty, having a ship selected could be made to uninstall first without confusion.

**Comment by EndrosG** [comment]
Similar idea here: I thought of having a separate "cargo ship" in the first place, in front of the flag ship. That is actually even pretty close to how the game internally handles the `cargo` when you are landed.

**Comment by Tadrix** [comment]
@KiLEdEnNis I'd suggest first uninstall then. If player doesn't yet know that un-selecting all ships allows to buy outfits to cargo, then (s)he will not have any outfits in cargo, so the question "how to sell outfits in cargo" will not arise. For other it's intuitive enough:

Currently if you want to install, you select a ship.
If you want to have that in cargo, you don't have ships selected.

It would be logical that the same would work the other way round:

If you want to take outfit off the ship and sell, select that ship.
If you want to sell outfits from cargo, you don't have any ships selected.

Installing from cargo should still work as it works presently.

Actually, if second point would be implemented, then first one wouldn't be so necessary then.

**Comment by KiLEdEnNis** [comment]
just got an idea, may not be added but would fix this
now we have Buy, Sell, and Leave
we could make the box where those 3 buttons are a little higher, and make an (Install? and) Uninstall button
the install one may be useless, but an uninstall one could sell to cargo

**Comment by Bladewood** [comment]
ftr, this is a duplicate I think, I'll try to find the first one

**Comment by EndrosG** [comment]
Tadrix commented a day ago • edited
> If player doesn't yet know that un-selecting all ships allows to buy outfits to cargo, then (s)he will not have any outfits in cargo, so the question "how to sell outfits in cargo" will not arise. For other it's intuitive enough:

Not totally correct. You get outfits into cargo by boarding hostile ships and taking their stuff. Recommended if you cant capture them.

**Comment by Tadrix** [comment]
You are right.

Well, these players would just sell ship's outfits first and then those in cargo. Then buy back what they need, probably even benefiting them more, since they would buy the most depreciated outfits. And if someone would find this to be annoying, that someone would find out about selling cargo soon enough, kind of like people find out about cargo.

There should really be a tip about selling/buying to/from cargo, displayed when the player visits outfitter for the first time.

**Comment by EndrosG** [comment]
What do you think of a cargo hold button at the size of a ship outline?
I.e. if you have e.g. 5 ships, you would have 6 items displayed on the right side. Cargo (first), followed by flagship and the others.
Someone would need to make a sprite for that, of course.

**Comment by jafdy** [comment]
I quite like that idea actually (although your explanation isn't the best).

**Comment by MessyMix** [comment]
@EndrosG I don't get what you're trying to say. Could you repeat it more clearly?

**Comment by Jorlem** [comment]
@MessyMix Here's a quick edit I made of a screenshot to convey the basic idea of what we've been describing. 

http://i.imgur.com/lx0PG3J.jpg

The button above the ships labeled "Cargo"  would open the cargo hold instead of one of the ships, and would allow for buying and selling directly to and from cargo instead of selling the outfits on your ship first.

**Comment by EndrosG** [comment]
Actually, my idea is slightly different: put the `cargo` button just where the first ship is right now, i.e. the first ship would start in row 1, column 2 then.
Make it in terms of the UI a virutal ship. Internally (iirc) it is pretty much like a ship already. Having it as virtual ship would have the conceptual advantage, that it should also be possible to select a set of regular ships and the cargo (i.e. include it in multi-select).

![endless_sky_v0_9_6__20170426__cargo_hold_as_virtual_ship](https://cloud.githubusercontent.com/assets/26883037/25438674/87773a96-2a9a-11e7-9043-dcf712a6ec59.jpg)

**Comment by Tadrix** [comment]
> it should also be possible to select a set of regular ships and the cargo (i.e. include it in multi-select)

Why? What for?

I, for one, don't like the idea of making cargo similar to other ships. It's a fictional, non-existent entity which the game uses for summary. I can imagine first-timer's confusion, when (s)he is told to buy their first ship, and they see one already, and, after buying, there are two of them. Besides, that messes up ability to estimate your fleet's size at a glance.

I like MessyMix's idea, only that I'd correct Jorlem's example by placing cargo button above "Your ships" caption (cargo is not a ship) and making it half a ship square high and wide as all four ship squares in a row.

**Comment by jafdy** [comment]
I'm with Tadrix on the placement of the button.

**Comment by EndrosG** [comment]
That would be fine for me too, and I wont argue against it. Just made clear that my idea was slightly different. ;-)

**Comment by Jorlem** [comment]
That works for me as well.  :)

**Comment by Bladewood** [comment]
Pretty neat idea.

**Comment by endless-sky** [comment]
This was addressed in 1f35704, which was my fix for #2182:

![outfitter](https://cloud.githubusercontent.com/assets/11450262/25687166/186f42c6-3042-11e7-852b-89dea7987cb7.jpg)

**Comment by StokedIndustries** [comment]
Came here via google search looking for a way to uninstall a currently installed outfit on a ship but save it in cargo so I can apply it to another ship. Main reason is so I don't have to sell it at a depreciated price then rebuy at full price. Does the fix cover this? My current version is 0.9.6 (anyone know if it self updates or I have to grab the latest on master?)

**Comment by Amazinite** [comment]
Sell the outfit, unselect all your ships in the outfitter (ctrl+click on any highlighted ships) then rebuy it and it'll go to cargo.

**Comment by tehhowch** [comment]
Bit # 1 of the OP is addressed in #2806, which provides a single-key option for moving an installed outfit to cargo. 
That PR essentially resolves bit # 2 as well, since the player can then sell the just-removed outfit.
