### ISSUE TITLE
feature: max. ships preference

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2445]
For those who want to limit themselves, include a preference to cap a ship count in the fleet (allowing to capture more, but prompting to sell supernumeraries kind of like fighters without carriers, and not letting to buy over max), or active ship count in the fleet, (checked at "depart"). Preference values could be some of these (including flagship):
1 (for solo play), 7 (EV-like, iirc), 19, 31, 43, 55, 67, 79, 91, 103, 115, 127, ∞ (as far as computer specs allow). Make, for example, a "91" value default. This would minimize complains about game lagging, when someone takes a 500-ship fleet for a walk because they think that game should be played like that.

**Comment by jafdy** [comment]
But why? If you want to play with a limit then you don't need the game to tell you to play with that limit. As for the large fleet thing; if most people will realize that fleets that make the computer lag are probably too big without needing a default limit set.

**Comment by Bladewood** [comment]
duplicate.

sourcing...

**Comment by gunqqer** [comment]
This is kind of like the suggestion to lock save files to prevent cheating. You have to control yourself and self limit. The only way something like this would ever be implemented would probably a mod that increases the difficulty but nothing official

**Comment by KiLEdEnNis** [comment]
@gunqqer locking a save file to avoid cheating? eww
people would edit it through a plugin then, and locking the save files makes it harder to test stuff for modders

the point is, the game should not limit the player more than necessary, if a player wants a huge fleet, let him/her have a huge fleet
unabling players to do so will annoy a lot of players and will most likely drive some people to quit the game

**Comment by gunqqer** [comment]
Yeah someone requested save file locking a while ago on google groups I think. We don't even have different levels of difficulty yet so if you want a challenge it is going to have to be self imposed

**Comment by EndrosG** [comment]
locking player files is issue #2401 - but the reason was that somebody started the game twice without noticing.

**Comment by EndrosG** [comment]
Regarding SelfImposedChallenge, as linked by @Bladewood :
Restricting yourself to not using any warships but only interceptors (and thus eventually no heavy freighters either) is harder than playing with one (big) ship.
Engaging a Leviathan (or alike, eventually levi + firebird or so) with 1 clipper (or raven) + 12 interceptors + some star barges resulted in losses over and over again for me.
Interceptors just die too easy. But are easy to capture in most cases, so you can aquire lots of them if you want. [I prefer to sell them]

**Comment by Bladewood** [comment]
Your point being?

**Comment by gunqqer** [comment]
There was a different locking player files thing on google group. Guy thought it was too easy for him to cheat and wanted someone else to stop him. Everyone said that he needs to learn how to just not edit his save file. I cheat all the time but I really don't care if I do I just don't like the really early game. The fun thing about endless sky is you can play how you want and it doesn't effect anyone else

**Comment by EndrosG** [comment]
@Bladewood: I could imagine many other ways to self impose a challenge, parallel to max. ships. Like restricting yourself to small ships.
But I doubt that any sort of restrictions that I imagine would be implemented. - Explicitely not talking about the one being proposed here.

**Comment by KiLEdEnNis** [comment]
leave it at this: let the players decide what they do themselves, don't restrict them in unnecessary ways
if they want a giant fleet that crashes their PC or whatever let them do it

**Comment by MessyMix** [comment]
Here's what I have to say: I don't see why this is facing such opposition; after all, the game will not restrict the player, but there will be a preference for people to self-restrict.

As long as Tadrix isn't asking MZ to code this feature (i.e. if someone ends up writing the code for this), I actually _support_ including this option. More flexibility can't hurt.

One problem that will have to be addressed is switching between saves. What if, in one save, I want to cap the fleet at 7 ships, but in another I want it to be infinite? That will be something that we have to look at if this will be implemented.

I would also suggest putting infinite ships as the maximum, because if someone is trying to build a game-breakingly large fleet, then he/she'd be confused if the game tells him/her that "you can't buy more than 91 ships". Lol, that'd be funny, perplexing, and ambiguous. So, imo: by default, infinite ships. Use can change to his/her liking.

**Comment by Bladewood** [comment]
I guess this is like that (somewhat) recent Minecraft lock-difficulty option.

**Comment by KiLEdEnNis** [comment]
("recent")

**Comment by Tadrix** [comment]
> This is kind of like the suggestion to lock save files to prevent cheating.

It isn't even remotely like that. 

One of the reasons I wrote of challenges was, it currently is really easy to lose count of player's ships — they aren't numbered, and if more then some thirty of them then the task of constantly keeping track is getting daunting if the player keeps capturing, buying and selling. In info it will be a long damn list (which needs to be scrolled — by mouse wheel), in yards/outfitters it is large and messy cluster of icons (which needs to be scrolled — by mouse wheel). There's no way to collapse similar ships.

With a preference, this problem would be solved.

Ship types don't have such problems (player just needs to check his/her **new** ships, not _all_ of them).

**Comment by jafdy** [comment]
If the number of ships you allow is small enough to be a challenge then it is small enough to count. If you allow 40 ships (10 lines of 4) you will be able to wipe out most fleets you come across and it is still quite easy to count.

This is very much like asking saves to be locked, you want to hard-code something to prevent you getting too powerful. While it may not be quite as pointless it comes with more problems and still takes code time.

It is also necessary to consider if the player wanted to keep that newly captured ship, so auto selling won't work.

**Comment by EndrosG** [comment]
@Tadrix: I wasnt sure before, i.e. until I read you last comment. But.... now it really sounds more and more that implementing some more *information* would already *almost* solve your issue.
If we display the number of ships owned by the player ingame, separated between "active" and "parked", it would become easier to selfimpose the challenge of limiting yourself to e.g. 91 ships, correct?

**Comment by Tadrix** [comment]
Yes, it would totally solve that.

But in that case, some more informative statistics would be nice. For example:
Your ships: 7 active, 24 parked, 31 total
By type: 7 heavy warships, 2 heavy freighters, 5 medium warships, 10 light warships, no light freighters, 7 transports

Perhaps even hull models, e. g. 6 Blackbirds

**Comment by EndrosG** [comment]
You have my support on this. I could imagine some tables with "per category" information and having this for *ship count*, *crew totals*, and *networth* - probably as separate tables.

category | active | parked | total
------------|---------|----------|-------
transport | 2 | 7 | 9
interceptor | 0 | 1 | 1
heavy warship | 5 | 20 | 25
fighter | 20 | 10 | 30

But I wont code that for you. Despite other things, I am in the middle of heavily rewriting chapter 1 of my main plugin (to make use of some newer features already merged) and right now it is in an unplayable status, i.e. I dont play ES actively this week :-(
