### ISSUE TITLE
two more enhancements for writing missions

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2447]
I have two more things which I would like to be able when writing missions.

**First**
Use `decline` directly inside `on offer`

```
	on offer
		set "set some condition"
		"increment some condition" ++
		decline
```

does not work but prompts a warning:
Unrecognized condition expression:
  "available mission" "TEST JOB DECLINE"
    on offer
      decline

A mission without conversation or dialog (in the on offer) will always get accepted.
The only work around I currently have is to use `fail "this missions name"` which will fail the mission soon after it was accepted. Soon, but not immediately.

---------------------------
**Second**
Decide inside the `on offer`, if really a conversation should be displayed or not.
```
	on offer
		set "set some condition"
		"increment some condition" ++
		conversation
			branch newsletter hide
				has "newsletter subscription"

			label newsletter
			`	You receive a newsletter because you subscribed to it.`
				decline

			label hide
				decline
```
While this does not result in errors or warnings, it still opens an empty conversation which only has a [done] inside.
I would like the user to be able to opt out from certain message spam.

My only work around right now is to separate it into two missions (one which modifies the conditions and one which displays the newsletter), but that is not as elegant and it aint nice with not being able to decline the mission which only modifies the conditions in the first place.

-------------

Both wishes are not covered by issues #1563, #1564, or #2351

**Comment by jafdy** [comment]
If the second request is filled then the first request is obsolete as there will already be a shorter workaround.

I don't quite get why having an invisible mission active of a short time is a problem.

**Comment by Elyssaen** [comment]
I can see the use of the second. The first, I think I agree with @jafdy: not only is having an invisible mission briefly active not a problem, it seems like it'd be a useful diagnostic tool. The player won't notice any difference, but in some circumstances they'll be some useful information in the player's save file.

**Comment by Elyssaen** [comment]
By the way, I'll delete this comment shortly but... @EndrosG, did you get my email? Don't have Facebook, so thought that'd be a good way to get in touch.

**Comment by endless-sky** [comment]
This doesn't sound like something that would have broad enough usefulness that it would be necessary to add direct game support instead of just using the existing work-arounds.
