### ISSUE TITLE
Mission Overwrites

### ISSUE THREAD

**Issue by PJTheGuy** [endless-sky/endless-sky#2448]
I was making a simple plugin that added a few ships from other plugins into fleets (Just for myself, for fun), and so the first mission I tried editing was the "Defend Sabik" mission. I took the mission, put it in a text file (the whole thing, including the base fleets), and added a few ships while deleting a few others. Then I went to test the mission.

It didn't replace the default mission ships; it took the base fleets, and added my mission ones, essentially duplicating them. The mission suddenly had about 7 Cruisers over Sabik.
Absolutely terrifying when you're flying an Osprey.
This isn't as much of a problem for large battles, but what if you just want to replace one ship with another, such as replace Danforth's Cruiser with a Carrier in one of the escort missions? 

I conclusion, I think that missions should be overwritten if a mission with the same name is put in a mod.

**Comment by KiLEdEnNis** [comment]
you made a second mission that spawns another wave
editing story missions requires doing so in the data files, adding a plugin and deleting the original, or (best imo) make a plugin one, and make the previous mission in the data files refer to that mission instead (easily undone by changing 2 lines)

this addition can be useful, but very low prioroty

**Comment by jafdy** [comment]
You can "disable" a mission by putting a never in the conditions. You then create a parallel mission that will replace the old one giving it the same starting conditions as the original. At the end of this mission you make it set the original mission to complete.

**Comment by Bladewood** [comment]
relevant: https://github.com/endless-sky/endless-sky/issues/1764

**Comment by PJTheGuy** [comment]
@KiLEdEnNis @jafdy I see, I didn't think about that. I'm an idiot. I was just hoping for a way to modify story missions without modifying the game's base files. Makes it where I don't have to modify the base files after every update!

**Comment by KiLEdEnNis** [comment]
no problem, everyone starts new :P 
and not wanting to modify the base game is actually a good thing, but for overwrites you have to, a good thing is making a backup of the data files, so you have an unedited version (but every update the edited text file changes you need to manually redo the override)

**Comment by endless-sky** [comment]
Missions really aren't intended to be override-able like this. Probably the best thing would be for the game to just report an error and ignore the new mission data if a file tries to redefine a mission.
