### ISSUE TITLE
(Idea) A reskin of this game to an ocean, all the planets would become islands, systems become isles, jump routes become currents, aliens become foreigners (still kinda aliens) and to make it mystical the jumpdrive makes a whirlpool drag you down and bring you up somewhere else. Would be cool and attract people not into the whole "space" thing. Would require someone dedicated to actually making all those reskins :p Any Potco fans?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#245]

**Comment by Pointedstick** [comment]
Sounds like a good total conversion mod opportunity, but this is a space game at its core.

**Comment by gchapyzh** [comment]
And the core dynamics become completely different core mechanics... :)
This seems unreasonably difficult, much rather I would wright a separate game on a smaller language and it would serve the purpose just as well.

**Comment by johndh** [comment]
The thought had occurred to me before, but I think it would need a bit more than a reskin.  The physics would need to be modified, collisions would need to happen, etc.  Airships would be easier, I think.  Either way, there could be a lot of interesting possibilities added to the game, like weather, currents, ramming, submarines...

**Comment by endless-sky** [comment]
This sounds like a request for a completely different game. You're welcome to try modifying the code of the data files to make it work, but it's not something I'm likely to work on.
