### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#2454]
[Windows.docx](https://github.com/endless-sky/endless-sky/files/961793/Windows.docx)
After having some trouble getting the compiler set up I rewrote the windows section to be a bit more detailed and up to date. it's not perfect, but I've tested it on two 64-bit systems so I know that part at least is accurate.

**Comment by endless-sky** [comment]
What files do you think are missing from the dev64.zip file? As far as I can tell, all the required libraries are there.

I would probably recommend just copying the DLLs to somewhere that's on your system's library search path (like the windows system folder) rather than into wherever the program is being built.

You won't find the .a files (libmingw32.a and libopengl32.a) in the steam release; those are static library files.

And, I'm worried about recommending the sjlj compiler version because that's the one that *didn't* work for 32-bit builds when I tested it.

**Comment by SirStigII** [comment]
So how do I link the .dll files? I can get it to work if I put them in the debug folder, but I can't figure out how to do it in codeblocks

**Comment by SirStigII** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26936987/25646728/6a349806-2f78-11e7-92ee-a7c7f18eaaf3.png)

**Comment by SirStigII** [comment]
it required the C:\Program Files\mingw64\x86_64-w64-mingw32\lib\libstdc++-6.dll, the dev64 one was the problem.

**Comment by 22144418** [comment]
I tried to apply a quantum key stone into my flagship, but to no avail. any reasons? Plus, if I were to add in a remnant ship, it becomes invisible and unable to do anything but drift to nowhere.

also, what's a hai solifuge? looks like the new bactrain... there's a bunch I've never seen before, such as the hai flea, hai pond strider, hai violin spider, marauder fury (I've done hundreds of bounty missions (to the point where the missions log requires scrolling to see each and every one of them), but this never came up.), autumn leaf (it's probably from the wanderer missions that I for some odd reason could not progress after testing speaking device to the wanderers), derecho (looks like wanderer, but not quite), tek far 109 (might just be me, but it never showed up from anywhere from the outskirts of the kor meriti or a few systems past it; even tried quick jumping to various kor sestor reigons, but I never saw it.), and the flycatcher (looks like the wanderer interceptor, and, again, it probably appears in the wanderer missions. and I also have no idea what a hallucination is.
for outfits: rails (they hardly look alien), repeaters, slicer guns (thought they only used turrets and s weapons...?)  sunbeam turrets, typhoons, wanderer antimissile, heat sink, and other equipment  (most likely from their large warships, but I don't know), stack core, fuel cell hai, androids (no friggin clue), catalytic ramscoop (cant register in my head), and this tiny atomic engines hai, supposedly from the hai ships I never seen.

I cant find any remnant planets, and I thing its something I missed. cant tell...

**Comment by Wrzlprnft** [comment]
umm, i am not sure why this comment is here and what you are trying to say: it is just a bunch of content you either missed (sestor and wanderer ships, hallucination), content that is not yet utilized (hai pond strider) or content that is not released via a stable version(keystone, remnants).
oh, and deprecated removed content too (androids).

neither of this really belongs in the wiki, except their mechanics, or maybe that ship table (which is never really ment to be up to date). further, if you do not compile the newest version of the game, you'll probably won't be able to follow along really.

sorry, i am really confused by this comment

**Comment by 22144418** [comment]
thanks for telling me about the the incomplete stuff, I didn't know about that at all. but none of this stuff is presently available on the meta? like, for example my starling that I hacked as my flagship became invisible and uncontrollable and that the objects, like the quantum key stone, thrasher cannon, and point defence turret, all currently are unusable as of right now?


that's all there is to ask. I pretty much edited all the files for a long time to ensure that, and I really didn't follow about some stuff. sorry if this pissed you off.

**Comment by SirStigII** [comment]
We are just confused what any of this has to do with the compiling on windows wiki, which is what I opened this about...

**Comment by Bladewood** [comment]
http://steamcommunity.com/app/404410/discussions/0/143388511225984433/?ctp=6#c1327844097123022664 this is probably my fault here.

**Comment by SirStigII** [comment]
I knew why he was looking at this thread, but this thread was about compiling, not any actual content

**Comment by jafdy** [comment]
People don't like to read. This is a bit of a problem for us seeing as ES has text based stores.
