### ISSUE TITLE
Problems with animated sprites

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2457]
Before anyone asks: Yes, I've been playing with the Void Sprites that were released only a few hours ago (at the time of this post).
And I've noticed two problems. In particular, problems with features relating to their animations.

1. The ship animation is not smooth in the target indicators. (That is, the circle on the far left; also, the flagship indicator in the corner.)

2. The flagship highlight is not animated.

**Comment by endless-sky** [comment]
Fixed the flagship highlight in d588cc7.

Having outline drawing interpolate between sprite frames would take a lot more work, so that's going on the low-priority list.

**Comment by KiLEdEnNis** [comment]
maybe using the center sprite as the 1 in the ship indicator is enough: the 1 where the tail is in the center

**Comment by endless-sky** [comment]
As of 007c4d5, the outline shader will interpolate between frames, solving the first issue. (The Void Sprites will still flicker a little bit in parts of their bodies that move a lot between animation frames, but the target image no longer moves in jerky steps.)
