### ISSUE TITLE
Content bug? prison colony on planet Clink not resolved

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2458]
I thought about altering `planet Clink` and `system Kornephoros` the following way:

```
system Kornephoros
[add]	minables neodymium 16 19.9863

planet Clink
[change]	attributes south moon mining

```
The neodymium minables would fit perfectly to the lore description of clink about the rare earth minerals.

But then I got aware that Clink does not have a spaceport and wasn't sure whether the "south" attribute is missing for exactly that reason. I still think it should be added.
I then checked the `events.txt` and found 3 events related to planet Clink. The events "capture of Kornephoros" and "recapture of Kornephoros" look fine, but I am concerned about `event "fw prison on Clink"`.
**The prison colony which can be established there during the `free worlds middle.txt` champaign never gets resolved.** In my opinion there should be some sort of "release prisoners from Clink" event when the main plot is over. It doesnt look nice if years after the main plot has been completed that prison still exists with Navy personell being imprisoned.

**Comment by endless-sky** [comment]
Fixed in 14dc548.
