### ISSUE TITLE
grammar question on writing conversations

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2460]
Eventually a simple question, but I still have it.

I've seen a few variants of the following grammar construct in the data files (these are from `transport missions.txt`):
```
[first example]
`	"Thank you," he says. You help them to load their meteorological equipment onto your ship.`
[second example]
`	"Thank you, Captain," he says, shaking your hand. You bring him aboard your ship and show him to one of the empty bunks.`
```
"He" finishes his sentense with a comma. Shouldn't it be like "Thank you." he says. Or something like this?
There is no further conversation part and thus this grammar construct looks odd to me.

Any comments?

**Comment by endless-sky** [comment]
Just google for "grammar rules for punctuating dialogue."

**Comment by EndrosG** [comment]
Thanks, that really helped! :+1: 
The difference between periods and question marks confused me before but now it is more clear to me.

I didn't know until know that there are differences between American and British writing here too. I am not a native english speaker and wasnt even sure about proper search tags for google this time.
