### ISSUE TITLE
Outfitter bug

### ISSUE THREAD

**Issue by 123jackkcaj321** [endless-sky/endless-sky#2462]
I went to the planet sunracer in the mirfak system and went to the outfitter to reload my ships but now it won't let me leave because it says that I need a better generator or battery even though I did not add anything that adds energy requirements help

**Comment by Bladewood** [comment]
GitHub is not the place for posting petty problems. Go to the Steam or Google forums for that.
But, nonetheless, I will try to help.

Attach your save file. It is found in `C:\Users\yourusername\AppData\Roaming\endless-sky\saves\` on Windows. I believe similar counterparts for Mac and Linux can be found by exploring [here](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins).

**Comment by endless-sky** [comment]
Do you have more than one ship?

Is it possible that you captured a ship after removing its generator?

**Comment by 123jackkcaj321** [comment]
Thank you I fixed it it was a ship I captured
