### ISSUE TITLE
intented? inconsistent? different sorting of shipyard lists

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2463]
I have a set of ship definitions with a generic prefix to achieve a certain order which would not be achieved by the names. CS 1 Hamlet, CS 2 Village, CS 3 Town, CS 4 City....
I tried to hide the sort name by making these variants of base classes with shorter names.
> ship "Hamlet" "CS 1 Hamlet"
> ship "Village" "CS 2 Village"

In the planets shipyard, everything worked as desired. The name of the base class gets displayed (that's how it works for all variant stuff, we know...), and ships were sorted by the name of the variant (I assumed so because of other ship definitions I made for some tests in the past).

But in the vertical list on the map panel, ships are sorted by the name of the base class, and not by the name of the variant.
That's a little bit confusing. I would expect both listings to use the same sort() mechanism.

![endless_sky_v0_9_6__20170430__shipyard_different_sort](https://cloud.githubusercontent.com/assets/26883037/25559940/0d269a2a-2d47-11e7-8618-9ca4da2dc2cc.jpg)

**Comment by endless-sky** [comment]
Given that variants aren't generally supposed to be for sale, I don't think this is worth addressing.
