### ISSUE TITLE
Viewing the ship info panel when no (pilotable) ship is available

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2468]
I've been playing around with things. I have a single Kar Ik Vot 349 in my fleet. And no flagship.
Two phenomenon follow from attempting to click on the Ship Info tab at the top of my fleet, depending on whether or not if I have already loaded another pilot.

- If another pilot was already loaded, I am given the screen that would have belonged to one of the ships in my other pilot's fleet. The name and the sprite are retained, but everything else is empty.

- Otherwise, the game crashes.

Neither of these are really desirable.

**Comment by endless-sky** [comment]
Should be fixed in 1a11f72.
