### ISSUE TITLE
idea: Use the radio chat thing for somthing

### ISSUE THREAD

**Issue by kjack1111** [endless-sky/endless-sky#247]
I dont know. Prehaps set up a IRC chat and hook the radio up to the IRC? having a basic AI so when you say somthing, a random ship would talk back? i dont know, do somthing with it. i hate potential features going to waist like that.

**Comment by gchapyzh** [comment]
1) Asking government ships for escort
2) Asking for pirate positions
3) Asking for a two way temporary treaty (when both fleets are in no mood to fight)
4) Asking for news 
5) Receiving messages in space directly and acquiring quests (emergency escort)

**Comment by kjack1111** [comment]
i like your ideas, especially for )6. maybe get fined for transmitting false cords?

**Comment by gchapyzh** [comment]
@kjack1111  You cant really transmit false data, you just send your sensor logs to them? Or you could do it on the map by hand but do you rally want to?

**Comment by kjack1111** [comment]
@gchapyzh That is what i meant, lol. but sensor logs work well.

**Comment by airtroop392** [comment]
I'd like to see something on the scale of ARMA, which is basically what @gchapyzh described earlier.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
