### ISSUE TITLE
Boarding probability changes

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#2470]
When I board a disabled ship, it gives me the estimate for my chance of capture and expected casualties.  Once I initiate "Attempt Capture", the percentage changes.  In particular, it tends to go from 75% to 100% pretty often.  I'm using a Corvette with full crew, all armed with Frag Grenades and a big stash of Laser Rifles (more rifles than crew).

**Comment by Elyssaen** [comment]
This is intentional. If it goes from 75% to 100% when you attempt capture, the ship has a 25% of self-destructing. You've cleared that, and so the capture chance is now higher.

**Comment by KiLEdEnNis** [comment]
@Elyssaen not even sure what you're saying about self destructing, only like the Korath automatons do that

it goes from 75% to 100% because at first in 75% of the scenarios would you win; there is a chance the first attack goes bad and the chances drop, but if the first attack went well, you have a higher probability to capture the ship

**Comment by MessyMix** [comment]
@KiLEdEnNis this isn't even the first attack, and also marauders self destruct.

This is a matter of self destructing, because the player hasn't even attacked yet, and the chances went up. (note that what happens is "attempt capture", not "attack").

As @Elyssaen said, the problem here is because there is a chance that the ship self-destructs upon boarding and again upon capturing, so when you bypass this probability (25% in this case), you end up with your true capture probability.

**Comment by Bladewood** [comment]
Uh...
I don't think this has anything to do with self-destruction rates.

**Comment by MessyMix** [comment]
@Bladewood Uh... I think it does.

Let me demonstrate. I just jumped into a Mereti system, aggravated them, and boarded a ship.

before clicking attempt capture:
<img width="1440" alt="screen shot 2017-05-01 at 4 56 02 pm" src="https://cloud.githubusercontent.com/assets/20450076/25594577/293325e6-2e8f-11e7-9146-5cbefb68a96b.png">

after clicking attempt capture:
<img width="1440" alt="screen shot 2017-05-01 at 4 56 06 pm" src="https://cloud.githubusercontent.com/assets/20450076/25594586/36090de4-2e8f-11e7-8964-856314335802.png">

is this not the situation that the OP is describing?

**Comment by Elyssaen** [comment]
Went from 75% success to 100%, and he's in a Corvette... he was probably boarding a Marauder Arrow, Marauder Bounder, Marauder Quicksilver. 25% self destruct chance, he'll easily have a 100% chance once he's cleared that, so it will go from 75 before hitting Attempt Capture, to 100 after.

Could be another Marauder ship, just guessing those as they have small crew numbers so the 100% against his Corvette isn't surprising. Could be a Firebird, Manta, Splinter, etc.

Don't think it's an automaton.

**Comment by MessyMix** [comment]
@Elyssaen I don't think it's an automaton either, I just used the example to demonstrate what the problem was. Like you, I noted in my first post that Marauders are also self-destructing, and that was what I believed to be the case.

**Comment by Elyssaen** [comment]
@MessyMix, sorry, didn't mean to suggest I was disagreeing with you. I was a bit distracted at the time of the message. Shouldn't really post while on the phone to someone, not fair on anybody!

**Comment by KiLEdEnNis** [comment]
well, I never noticed the self destruct chances in this, so learned something new

**Comment by johndh** [comment]
This sounds like it mirrors my situation.  I've definitely noticed it with marauders.  Not sure if I've seen it with any other ships or not.  While it's technically correct, it seems a little misleading, in that if I see I have a 75% chance of capture that tends to indicate a different situation than the current one.

**Comment by MessyMix** [comment]
The 75% capture chance represents the chance that you can actually successfully capture the ship. If, 25% of the time the ship will automatically self-destruct, then you can only board 75% of the time. This can allow you to asses whether it is worth trying to board a ship or not: Say you find a nice ship, and it's chance of capture is 3%. Knowing this, you could make the decision to loot all the ship's outfits (including engines and hyperdrive), and leave it for dead. This might earn you some money, whereas boarding (and failing) won't. This just lets you make educated guesses / calculations as to the best course of action.

**Comment by johndh** [comment]
@MessyMix right, and that's what I mean by it being technically correct.  If I try to board this ship, I have a 75% chance of walking away with a new ship.  However, given that the percentage usually just stands for the chance of a boarding success vs. a boarding failure, I think the way it is now is counter-intuitive.

Two examples:
In situation A, the ship has a 25% chance of self-destructing if I Attempt Capture, but if it doesn't self-destruct then I have a 100% chance of capturing it.
In situation B, the ship has a 0% chance of self-destructing, but a 25% of repelling my attack.
In both A and B, the outcome is the same 75% of the time, but what's contained in the 25% is very different.  In A, a failure means I walk away empty-handed but none the worse for wear.  In B, I limp away with a lot of dead crew and 40 tons worth of loot.

I think adding a line that says "self-destruct odds" or similar would make the situation more clear.

**Comment by Elyssaen** [comment]
I think I remember @endless-sky agrees with you, @johndh. I remember the commit suggested it was something of a placeholder / recognised as imperfect. Another aspect is that you shouldn't really know the chance of the ship self-destructing at all, meaning "Warning: self-destruct may occur" might be more suitable than "self-destruct chance: 25%".

Though that said, it could've been left off entirely and just start at 100% as normal. He was probably worried that'd be confusing in itself: why did my sure thing just blow up?

One last option, one that opens up more questions, would be if you didn't see your capture chance at all until you initiated boarding. Or their crew or attack/defence. That way, there's no problem. But it also means you take a risk: you initiate capture 'blind', giving them a chance to capture _you_ if you realise you don't fancy your odds.

**Comment by jafdy** [comment]
If you press Defend after Attempt Capture without pressing Attack you will always disengage successfully.

**Comment by Elyssaen** [comment]
Aww, I was rather hoping that solution would entail some risk. I'd never done it, and assumed they had an opportunity to attack. Oh well, no risk it is. : )

**Comment by jafdy** [comment]
It was set like that after someone pressed A instead of D after looting a ship.

**Comment by MessyMix** [comment]
I think @jafdy raises a great point that mitigates @johndh problem. In this case, I don't think a new line will be necessary for self destruct odds.
