### ISSUE TITLE
Add a way to assign fighters to different motherships

### ISSUE THREAD

**Issue by PJTheGuy** [endless-sky/endless-sky#2472]
I looked for another issue pertaining to this, and didn't find one. I didn't see a way to do this in the game, either. So, onward!
As the title says, I think there should be a way to assign certain fighters to certain ships in your fleet.

**Comment by MessyMix** [comment]
the fighter highest on your ship list is assigned to the carrier highest on your ship list.

But I see what you're getting at, and I think it's a great idea, if you could specify the mothership for a fighter. Perhaps drag them under the ship that you want when looking at your ship list?

**Comment by PJTheGuy** [comment]
That would be a great way to do it. Sometimes I don't want a fighter on my flagship, so it would be nice to choose where the fighters were put. Dragging them under the carrier you want would be a great way to make it easier to do.
