### ISSUE TITLE
Captured Fighter AI

### ISSUE THREAD

**Issue by PJTheGuy** [endless-sky/endless-sky#2476]
Sometimes, when I capture a fighter, it will either 
A) Go to the system star and try to "refuel"; this might be fixed by relaunching, or it persists and you have to disown the fighter.
B) Kamikaze into the nearest hostile ship and attack it, only to be promptly destroyed or disabled.
C) Actually dock with a carrier, as it should.

This was done with all my fighters docked, and they were not launched at all during testing. This was done in the Korath Exile systems, with their Chasers.

**Comment by KiLEdEnNis** [comment]
it should only attack if you don't have the command for fighters to dock on

**Comment by PJTheGuy** [comment]
@KiLEdEnNis I have it where all the fighters are docked to the carriers, and I have tried to deploy and recall the fighters to fix the problem. It doesn't work, unfortunately.

**Comment by KiLEdEnNis** [comment]
full carrier?

**Comment by PJTheGuy** [comment]
@KiLEdEnNis Nope. At the time of testing, I had a Kor automata carrier with only 7 of the 9 fighter spots filled, and another ship with 2 empty fighter bays. It shouldn't have a problem finding a ship to dock to.

**Comment by jafdy** [comment]
It would be most helpful if you can find a way to reproduce it.

**Comment by tehhowch** [comment]
I can reproduce this. Capture any fighter while its parent ship is still alive, and it will attempt to dock with its original parent ship. Once you give it an order, then it realizes its new ownership and will dock with your carriers.

**Comment by tehhowch** [comment]
I think this was fixed by https://github.com/endless-sky/endless-sky/commit/af9e646bedeac86e3e164065291087590b5f6d6c, in addition to e8a629e11c6d7c2593ae588de7b455d4d009d2d9
