### ISSUE TITLE
Ship with hyperdrive and scram drive will always use 1.5x fuel

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2477]
Even if the ship comes to a complete halt before jumping, it will still use 1.5 units of fuel rather than 1. I'd expect it to use less if the time is taken to slow the ship down and the normal hyperdrive can be used.

**Comment by EndrosG** [comment]
I can confirm this. I lately looked into the code and the code strictly prefers a scram drive over a hyperdrive.
Even if you do a full stop with proper rotation, e.g. by long-pressing the J button and waiting until all ships are aligned, the code simply does not care about.

**Comment by KiLEdEnNis** [comment]
I've had it like half a year ago and never really bothered, so I can confirm too

**Comment by endless-sky** [comment]
Given that there's no easy way for the AI to figure out whether you want to try to come to a complete stop vs. using the scram drive, it's not intended for both outfits to be installed at the same time. Therefore, I don't think this is worth addressing.

**Comment by tehhowch** [comment]
On first thought it should be possible to check if the Hyperdrive requirements are satisfied, and if not, to default to the scram drive.
For ai decisions, one could check if the ship in question has the slowest stopping time out of it's escorts and/or parent, and if so, to prefer scram driving. It's definitely a complex decision though, so probably not worth your time at this moment. An enterprising contributor (@kiledennis ?) could certainly try it out and share with us any solution they come up with.

**Comment by KiLEdEnNis** [comment]
once I find time I'll continue self-tutoring some C++ to finish my "frugal carrier" stuff, but I'm fine with trying this after
