### ISSUE TITLE
Too easy to destroy a fleet by moving just beyond the invisible edge in a system

### ISSUE THREAD

**Issue by schrauger** [endless-sky/endless-sky#248]
I quickly found that the best way to escape a large fleet is to move beyond a certain distance from the center of a system. Attacking ships will chase you, then turn around at the edge. They'll keep turning back and forth.

Once any missiles and torpedoes are exhausted, you simply fly to a spot just beyond this invisible border. They keep turning around, you can just fire lasers/beams with no repercussions. Aside from turrets, you never have to worry about getting hit; by the time their weapons are in range, they are already turning around to fly closer to the center.

I'm not sure having them chase you indefinitely would be better. But perhaps they should keep chasing you while they are close, and only give up when you are far away.

**Comment by endless-sky** [comment]
This is changed in commit 7e36045. Give release 0.8.8 a try in a few hours when I'm done with it, and it should fix this issue by having ships just ignore you if you leave that invisible boundary.

The initial behavior was to prevent "kiting" - a player drifting away from an enemy ship at their maximum speed while pummeling them with long-range weapon fire.

**Comment by Oeleo** [comment]
I have the same problem in 0.8.8, so to not cheat I had to do some circles around Sol.

**Comment by schrauger** [comment]
> The initial behavior was to prevent "kiting" - a player drifting away from an enemy ship at their maximum speed while pummelling them with long-range weapon fire.

This seems like a valid strategy to me. In fact, small enemy fighters will do this to me all the time. If their primary weapon is missiles, they'll zoom away and fire. As soon as I start to get close, they turn around and run away, still firing. I can't ever hit them until they willingly come close to me (generally when they exhaust their missiles and come to attack with lasers).

**Comment by endless-sky** [comment]
The change in 0.8.8 led to new ways of abusing the "invisible fence," but in commit b8c5e58 I've made some more AI tweaks that I think are a good balance: the AI will keep firing on you even when you cross that line, but it is much harder to trick the AI into repeatedly bouncing across the line so you can pummel it while it retreats.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this. It may not be a perfect fix for the invisible fence, but it is at least better, and it will need more testing before I decide if it needs further tweaking.
