### ISSUE TITLE
Clarity when going for a cargo scan (when you also have an outfit scanner)

### ISSUE THREAD

**Issue by Elyssaen** [endless-sky/endless-sky#2480]
I'm writing a mission that involves performing cargo scans, and want to check whether people feel the current scanning method could make things confusing if you also have an outfit scanner.

Here's what often happens when you scan your target:

![outfit_scan](https://cloud.githubusercontent.com/assets/23544894/25758228/8fb5b958-31c5-11e7-8869-44cedb534702.PNG)

Clicking out of it, getting a bit closer and scanning a bit more, you get:

![cargo_scan](https://cloud.githubusercontent.com/assets/23544894/25758235/970a470a-31c5-11e7-960a-df461597af1b.PNG)

(and any dialog box or conversation associated with succeeding at a `npc "scan cargo"` objective)

Is this potentially confusing for players? I'm worried that players with both scanners, trying to complete an `npc "scan cargo"` mission, might complete the first scan, think there's no cargo to find, and move on. (They _could_ know better, and at first I shrugged it off and figured they probably should, but they _might_ not figure it out immediately.)

If it could be confusing, what would everyone suggest doing? Missions could try to write in "By the way, remember if you have an outfit scanner that you might need to get a little closer for a cargo scan", but that's a little clunky. There's probably a better way.

**Comment by tehhowch** [comment]
I buy a 2nd cargo scanner to up the range and decrease the time-to-scan... that way it beats the outfit scanner 👍

**Comment by Elyssaen** [comment]
@tehhowch, that's a cool trick and I might do it myself, as even when you know what's going on it's a little bit fiddly to have to scan twice. Though I might just hack my copies to equalise time and range completely.

Do you think how things are could confuse new players doing a cargo scan job?

**Comment by endless-sky** [comment]
In c221153 I've added indicator circles that are drawn around your target to show the completion fraction of the cargo and outfit scans. So, if you don't see two solid circles lock in around it, you know the target has not been fully scanned:

![scan](https://cloud.githubusercontent.com/assets/11450262/25769375/987dbe1c-31e5-11e7-848f-b7a3098abee1.jpg)

**Comment by Elyssaen** [comment]
Ah, I wasn't expecting a response like that! I wasn't sure people would even find it confusing, and if they did I thought perhaps I should just write missions that warn about it. But thank you, that's pretty amazing.

Think there might be a small bug in it but I'll recheck and raise a different issue if so.
