### ISSUE TITLE
Jumps along hyperspace links trigger hyperdrive accelerations

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2482]
If systems are connected directly by links, and your jump-drive-only fleet is traveling along said link, your ships will use the hyperdrive animations (with jump drive alignments).
In other words, your ships accelerate in any number of directions and arrive in the next system with significant velocity.
Expected jump behavior occurs when not following a hyperspace link.

**Comment by tehhowch** [comment]
git bisect says the commit that introduced this started was c795aae88358a06afafda9d604539e2e5124f7aa

**Comment by Bladewood** [comment]
damn, someone beat me to this.

**Comment by tehhowch** [comment]
i believe the issue is with https://github.com/endless-sky/endless-sky/blob/c795aae88358a06afafda9d604539e2e5124f7aa/source/Ship.cpp#L1051

I think it needs a check for "does this ship have a hyperdrive that can be used?"

**Comment by tehhowch** [comment]
I found the solution in Ship.cpp 's IsReadyToJump function, which declares `bool isJump = !attributes.Get("hyperdrive") || !currentSystem->Links().count(targetSystem);`

Testing in-game after recompiling shows this change will fix the issue.
ps: i reallllly want to trim the trailing whitespace

**Comment by endless-sky** [comment]
Fixed in 3698235.

**Comment by Bladewood** [comment]
help, it's still making the hyperdrive sound.

**Comment by tehhowch** [comment]
I confirm as well... but only for the flagship. Escorts use the the expected jump sounds

**Comment by tehhowch** [comment]
@Bladewood fixed with #2505
