### ISSUE TITLE
Issue with the Remnant systems (undiscovered wormholes)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2486]
(This assumes you have not explored Remnant space yet.)
Enter Cardea, the Remnant system farthest to the left.
Press J (or whatever key you've set to jump) to cycle between the available systems on the map.
Selecting Insitor will create a purple line between Cardea and the system, rather than the yellow/green/red in normal behavior.
Affirming that you want to jump there with the jump key will instead autopilot you into the wormhole that brings you to Cardea.

edit: forgot to provide a save 
[Epsilon Carinae~3033-05-19.txt](https://github.com/endless-sky/endless-sky/files/981134/Epsilon.Carinae.3033-05-19.txt)

**Comment by endless-sky** [comment]
Fixed in 83baa08, 476f453, and 9bc7b4a. (Turns out that multi-stop wormholes introduce a *lot* of special cases.)
