### ISSUE TITLE
Attempting to land on a planet without a required attribute

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2487]
In Nenia, without a world selected, tapping L (or whatever key you have set to land) produces its expected result: "There are no planets in this system that you can land on."

I tried to land on Nasqueron.
First, I tried tapping L.
Nothing happened.
Then, I clicked on the planet, and the 4 blue dots appeared, and at the bottom of the screen, it said "Landing on Nasqueron."
Auto-pilot tried to bring me to land, but it failed. (How to describe the failure is beyond me.)
Then, I tried rapidly clicking on the planet and tapping L.

*crash*

**Comment by endless-sky** [comment]
Should be fixed in b0d3392.

**Comment by Bladewood** [comment]
Something else I've noticed:
Navigating on the map to Cardea, via the Terminus wormhole, removing your keystone, and then jumping to Terminus, relying on autopilot to bring you to Cardea, creates some very similar behavior. (Minus the crashing. And the clicking.)

**Comment by tehhowch** [comment]
The sneaky player behavior should be fixed by #2601
