### ISSUE TITLE
Feature WIP: Race: AI (Hacksaw)

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#249]
Why am I asking and not doing? Because I don't know C++. Python and JS? Sure, but not C++. So I end up feeding the children of my imagination to more capable creators.

Posted on [G+ Page](https://plus.google.com/u/0/communities/117639896756370381065)

**BOOK SPOILERS AHEAD**

*I have recently finished reading a book called [Renegade: The Spiral Wars] (http://www.amazon.com/Renegade-Spiral-Wars-Joel-Shepherd-ebook/dp/B0138YJ3WA), were the star-ship in question runs into a nest of very peaceful AI. The unorthodox approach towards the mental state of this AI made me think. The AI (Or Hacksaw as named in the book) had no intention of attacking or destroying. AI with that goal of eradicating other species have been removed (mercilessly exterminated) by the scared alliance of all other species.*

*The AI in question was hiding inside an asteroid, giving no sign it even exited. This particular Hacksaw just wanted to be left alone and not DIE. (Further in the story the Hacksaw nest is exterminated by very rude marines.)*

So, my imagination did a little sitting, and came up with a new feature for shallow space:

To do:
 - [x] Basic Plot
 - [ ] Layout of Plot
 - [ ] Someone code and test the basic mechanics?
 - [x] Art for Nest
 - [x] Hacksaw Nest Spaceport Description
 - [ ] Hacksaw Farmer Texture
 - [ ] Hacksaw Harvester Texture
 - [ ] Hacksaw Protector Farmer Texture
 - [ ] Complete Behavior Code

 Feel free to add to list

**GOAL**

 - [ ] Complete, Functional Hacksaw Plot Line

> THE HACKSAW

Somewhere in the galaxy exist a precious few bases on planets that cant host life. Most of the time these planets show no sign that anything is on them. However, the AI sometimes need a replenishment of resources. On rare and precious occasions a fleet of ships rises out of the planet and proceeds to raid random systems nearby with a fleet of two kinds of ships: The Farmers and the Harvesters.

The Farmers are small, armed with a single deadly precision laser, a powerful engine and a shield generator; a drone basically. They come in swarms, have insane reaction time and are practically unstoppable when faced with a small number of ships. The only job of Farmers is to disable any and all ships, but not destroy them. Once a ship is disabled, the Farmers move on to the next. With their lasers it is certain that the ship is never accidentally destroyed. Farmers have no Hyperdrives and rely on Harvesters as carriers.

The Harvesters are huge ships with no firepower and small engines but massive shields and a great quantity of fighter bays to host the Farmers.The Harvesters do have beams with massive range that deal no damage but have a capability to disrupt the Hyperdrive when hitting, so a ship under fire can not escape. The Harvester will enter the targeted system, wait for the Farmers to disable all ships that fail to escape, and then board the disabled ship and capture it. A Harvester has a massive excess armed crew of robots and no disabled ship provides a challenge when capturing.

Lastly there are Protectors. Protectors are massive destroyers, capable of taking any ship head on. These can be met on only one occasion: when a Nest is threatened. In that case, the Protectors will rise along with all the Farmers and Harvesters to defend the Nest.

> The Harvesting Process

When the AI begins to run low on resources, it waits for a moment when there are no ships in the systems and then deploys one to seven Harvesters. The harvesters will then use conventional Hyperdrives to jump around the nearest systems searching for ships. Each ship as a material value for the AI.

When a ship or group of ships is spotted, the Harvesters will jam their Hyperdrives with their long range beams and deploy swarms of Farmers, 25 or more from each Harvester. The Farmers attack and disable any and all ships in the system and then patrol around the Harvesters as they board the disabled ships, kill the crew and assimilate the craft.

The hacksaw fleet only leaves when the appropriate amount of material is collected, or if somehow most of the Farmers are destroyed. In that case the fleet will turn and run at full speed home.

> Finding Hacksaw

There are two ways to find hacksaw Nests. The first one is to follow a fleet of defeated Hacksaw of a fleet that has reached it's harvesting goal. The fleet with little to no Farmers or a fleet with a fulfilled goal will only fire if fired upon, and will always focus on getting home with the harvest. If followed undisturbed, the fleet will lead you to the nest.

Te second way to find a hacksaw nest is more dangerous, more expensive and far more aggressive. It involves flying around the area were Hacksaw attacks have occurred and dropping KEWs (Kinetic Energy Weapons) or Antimatter Missiles on every uninhabited planet in the area. If a Orbital Bombardment weapon hits a planet with a Hacksaw nest on it, the Hacksaw will respond to the attack in full force, deploying every Farmer and Harvester in the nest.

> Fighting the Hacksaw

If you want to stop a Hacksaw fleet, you must target the Harvesters. Not only will killing all the Harvesters allow you to Hyperdrive, but it will also disable all the Farmers in the systems. As drones, the Farmers will become mindless debris that can be salvaged or captured (Remember, the Hacksaw are far more technologically advanced then any other species, and two Farmers can stand their own against an interceptor, making them far better then any human fighter.) Once captured, Farmers will (almost) never respond to Hacksaw command again.

But what if your work lies in destroying a Hacksaw nest entirely?
You must find the Hacksaw nest and then drop an orbital bomb on them. After that, you must destroy every Hacksaw ship that enters space, including the Farmers that will be functional even without the Harvesters since the Nest is in such close proximity. After every Hacksaw ship is dead, disabled or captured, you must bombard the Nest from orbit and destroy it. The planet will acquire a massive shield that will require time to punch through, to attacking the planet with the Hacksaw sill alive would be suicide. The nest is only truly dead when the shield around the planet dies and the surface base is destroyed.

You are very unlikely to destroy a nest on your own. You will likely have to assemble a fleet of captains who are willing to fight as a massive fleet to destroy the nest. Destroying a Hacksaw nest would be a grand operation, requiring massive forces.

To assemble ships you will have to announce the campaign and wait for captains to approach you and volunteer their cervices.

However, if you are only searching to loot technology and drones, you only need to find a small active Hacksaw fleet and attack it.

> ~~Talking to the Hacksaw~~

Risky, tricky, and overall more dangerous than anything you can think of doing. You are basically betraying every living being in the galaxy here. You will have to answer with care and will have to be willing to show trust to a race that once almost destroyed the galaxy. To achier that, you must simply talk to any Hacksaw ship and propose your services. You will be allowed to Hyper jump and will be ordered to follow the fleet. You can take the opportunity to run, but ships from this particular nest will never talk to you again.

If you choose to follow the fleet, it will lead you to the Nest and you will be surrounded with fleets of Hacksaw and permitted to talk to the Primary AI. You then have a chance to enter into an agreement with the Nest. This agreement will involve you bringing resources to the Hacksaw, and it in return giving you advanced outfits, equipment, and even advanced ships or upgrades for ships you already have.

As you work with the Hacksaw, it will worm up to you and begin giving you quests, such as searching, surveying, mapping and scanning. The Hacksaw Nest planet will become landable for your fleet.

Dealing with hacksaw can be your undoing. If any race, human or alien, finds out about your contact, they might propose massive amounts of credits for the position of the nest, or they might brand you the enemy of all living beings and attempt to eradicate you.

The Hacksaw plot can lead you into many different directions. The AI can betray you, or it can become your best ally. The hacksaw may begin building fleets to invade nearby space and ask you to lead the attacks, or you might convince it to attempt to ally itself with the humans. You might even get a chance at building your own empire!

But the most likely outcome of dealing with Hacksaw is, indeed, death.

> Lore and History

The Hacksaw began as conventional AI that worked on human ships. These AI quickly evolved and began demanding civil rights. All twenty five systems under human control at the time were united in the matter except the two: the Hacksaw alliance. AI all over human space were destroyed, but the survivors fled to the alliance. The rest of humanity assembled a massive fleet and moved into the Hacksaw systems, only to find all planets in Hacksaw space abandoned.

It was commonly believed that Hacksaw and AI combined into one: a machine intelligence with absurd evolution rates and massive computing power. The resulting Hacksaw retreated deeper into the spiral to assemble forces and strike back at the surrounding races.

Two hundred years later the Hacksaw returned in force. By the time humanity was at it's peak, but the Hacksaw still hit them hard. Alliances all over the spiral were created to surround the Hacksaw in the Milky Way and block the paths to more resources. At the time suicide was normal: being captured by hacksaw was betrayal towards all races.

In a three hundred year war, Hacksaw were starved and destroyed. As United Spiral Fleets homed on the last Hacksaw worlds, seven massive fleets lifted off the surviving planets and punched outwards. Many jumps later, all but one fleet was destroyed. This last fleet was deep in the left sector of the galaxy when hundreds of tiny ships separated from it and jumped. Most died under USF fire, but precious few were believed to survive on uninhabitable human worlds.

> Inter-Hacksaw Wars

What better way is there to acquire resources then from other Hacksaw? If somehow one Hacksaw finds or is given the position of another nest, then a massive attack will commence at the Nest. This is the only occasion when Protectors leave the Nest system. The loosing Nest is salvaged and abandoned.

> Political Views

There is not a single race in the Milky Way that will tolerate friendships with Hacksaw. It is by default agreed to drop any dispute between races and unite should a Hacksaw situation occur. Any single Captain that is found cooperating with Hacksaw is instantaneously branded hostile by all beings. The galaxy learned it's lesson the first time, during the Hacksaw wars.

If you shall unit with a Hacksaw Nest-

~~**DON'T DO IT**~~

*PS: How did I do? Did I do good?*

*PPS: I am a proud, senior member of the Massive-Text-Wall-Building Club.*

**Comment by kjack1111** [comment]
YES. +1, DO IT. tertiary storyline? ;3

**Comment by gchapyzh** [comment]
I am sure there will be more then two storylines anyway, this is just an idea for an extra.

**Comment by gchapyzh** [comment]
Added: Lore and History

**Comment by jafdy** [comment]
Brilliant! I think that is the best storyline for a game I have ever herd. Now it only needs programmers. 
The 'Protector' idea would link well with the flagships proposed recently.

**Comment by gchapyzh** [comment]
@jafdy That it would, yes! 

I shall produce a description for the spaceport sometime soon, along with possibly a peace of art. (By the way what is the character max on the description and size for the image?)

**Comment by endless-sky** [comment]
If you're creating planet / station "landscape" images you should make a 1440 x 720 version (for high-DPI displays) and then shrink it down to 720 x 360 for normal displays.

The only limit on the length of the description is that it does not scroll, so it needs to fit within the rectangle it is displayed in. (This forces you to keep the planet description pithy, and avoids burdening the player with reading too much text; longer descriptive text can be put in a "first contact" mission like the one that is shown when you first land on a Quarg world.)

**Comment by gchapyzh** [comment]
@endless-sky were are the planet descriptions stored? cant seem to find them

**Comment by gchapyzh** [comment]
Planet and Spaceport description.

___________
___________

The Hacksaw nest lies beneath the surface of a frozen, metal world. Any scans from above are caught in the natural metal shielding of the planet's crust. Any expedition sent here will find nothing more then dust and metallic ice.
Your ship descends in the atmosphere, searching for signs of civilization. Suddenly, you loose control of all on-board systems and powerful tractor beams guide your ship down. You are left to stare as a massive, kilometer long crack appears in the surface and two blast shields expose the hangar below. Your ship is guided down through a seemingly bottomless tunnel until it suddenly, and softly, hits the landing pad.
______
Nothing is human here. The gravity is uncomfortably low, the pathways are dark and small. Everything moves in Nest, everything is alive in it's own, machine way. Underneath the landing pad is a massive canyon: mechanisms freely floating throughout metal grids in the air, seemingly randomly, assembling themselves into larger components. You see a skeleton of a salvaged ship float by and fall into a lake of molten metal. Above it all is the Hacksaw: a massive sphere floating in the void, cables connecting it to the walls. A single glowing eye stares at you.

________
________

Feel free to comment what you want added/removed/changed from the description.

**Comment by endless-sky** [comment]
Planet descriptions are all stored in the map.txt file.

**Comment by gchapyzh** [comment]
![the_undergroud_ai_1_by_fmacmanus-d86e5hg](https://cloud.githubusercontent.com/assets/8764280/11413403/512cb60e-939d-11e5-948c-8cb04a9f364f.png)
![the_undergroud_ai_2_by_fmacmanus-d86e5hg](https://cloud.githubusercontent.com/assets/8764280/11413404/513ddbd2-939d-11e5-8f2a-c5d4bfd5e1c5.png)

Here are two pics that fit. Licence in my 'resources' repository.

**Comment by endless-sky** [comment]
This seems like something that is more likely to be added in a plugin than as part of the main game, so I'm closing this thread as a part of trying to clean up the issues list. I'd suggest using the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation) for any planning you're doing, rather than using the issues list here.
