### ISSUE TITLE
Escorts don't seem to be able to jump

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2490]
I'm playing on the latest commit, and my ships don't seem to be able to jump, even if they have enough fuel. They are stuck in the Terminus system, killing bounty hunters. I tried to board one of them, but it didn't change anything. Only my flagship is able to jump around (it is also the only one with a Quantum Keystone.)

This is me holding down the jump key:

![escort_no_jump](https://cloud.githubusercontent.com/assets/8321423/25781295/5ca0c912-3338-11e7-8337-d3347d78b93f.png)

Reloading the save fixes this though, the escorts jumped to me immediately.

**Comment by tehhowch** [comment]
I can confirm: attempting to use a locked wormhole disables escort pathfinding: escorts are "stuck" landing on the wormhole.
To replicate: Flagship has keystone, escorts do not.
From Tania Australis, plot a course to Umbral / Tarazed. The route will use the Terminus Wormhole.
Your escorts will wait in Terminus while you are out of linked space.  Even after returning to linked space (Umbral/Tarazed) the escorts will remain in Terminus, (the shortest route from Terminus to the player is via the (locked) wormhole). But, even after entering a system which has the shortest route to Terminus as not using the locked wormhole (e.g. Boral), the escorts remain in Terminus.
Returning to Terminus will reveal all your escorts "doing the landing dance" on the wormhole. If you then jump to a neighbor system, your escorts will **still** not jump with you - they all believe they have no fuel (despite having full fuel), and attempt to refuel each other. Indeed, if you press Shift+B, your flagship will attempt to board and refuel an escort. 


All ships have Jump Drives and no Hyperdrive/Scram Drives. Issuing fleet commands has no impact. I have not tried to replicate with ships that do not have Jump Drives.

**Comment by tehhowch** [comment]
I have a fix, PR shortly
