### ISSUE TITLE
Asking a disabled ship for help results in the wrong message

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2491]
If a friendly ship is disabled, and your flagship is too, hailing them will result in the message "Sorry, we can't help you, because our ship is disabled". Asking them for help then (the button can still be clicked, or the H key used) will result in the message "You don't seem to be in need of repairs or fuel assistance" even though you clearly are.

**Comment by endless-sky** [comment]
Good catch. Commit b64ffff should fix this.
