### ISSUE TITLE
Opening the map while hyperjumping will freeze the game

### ISSUE THREAD

**Issue by dje4321** [endless-sky/endless-sky#2493]
OS: Fedora 25 x86_64
Repeatability : Yes
Doing a jump from Sirius to Sol and checking the map will freeze the game

I jump from Martini from system pollux to sol with 2 missions active on system Caph
Delivery to reunion
Transport workers to reunion

Cargo:
Clothing #11

opening the map during the jump from the sirius system to sol and trying to check missions will freeze the game

**Comment by jafdy** [comment]
Could you provide a video or something? I have made that jump spamming map and I didn't get anything. Also check if it happens with other paths or with jump drives too.

**Comment by dje4321** [comment]
@jafdy sorry i really cant. lost the save when i was trying to debug it further
might try and recreate the save file though
