### ISSUE TITLE
endless sky fails to display save files

### ISSUE THREAD

**Issue by Mark4666** [endless-sky/endless-sky#2499]
I started up my game yesterday and began playing as I normally would by clicking on enter ship. everything worked perfectly until my ship was destroyed. upon clicking on the load/save button I was confronted by two empty panels and the words no pilot loaded. I checked my saves folder and the save file was still there ES just wasn't displaying it, however the delete option was available and showed the normal delete dialogue with the name of the save file but clicking OK does not delete the file. I've since tried new save files, deleting my saves folder, deleting the entire es folder in appdata/roaming, reinstalling the entire game and even reinstalling steam but nothing seems to fix it.

**Comment by Mark4666** [comment]
the same error occurs when trying to load when on a planet or floating in space.

**Comment by Mark4666** [comment]
recently re-tested bug now only occurs if loading when starting a file before leaving starting planet.

**Comment by Elyssaen** [comment]
Could the problem be that the program isn't being allowed access to AppData\Roaming? Could you try a) running Endless Sky as an administrator, and b) checking any other games you have that refer to save files in AppData\Roaming?

**Comment by KiLEdEnNis** [comment]
if it's that AppData doesn't show up, I once discovered how to change that

**Comment by endless-sky** [comment]
It sounds like something is wrong in your system's configuration, which is keeping the game from reading the files.

As for deleting files, some anti-virus software may prevent files from being deleted by "locking" them while it scans them.
