### ISSUE TITLE
It's easy to fail rush job deadlines early on

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#25]
Before you've done much exploring, it's easy to take on a rush job thinking that you can easily get to the destination on time, but to get lost along the way and fail to meet the deadline. This is particularly true with destinations in the Rim or the Deep where they may look nearby but where you can't reach them by a straight path.

I'm not sure how to avoid this: warning the player about taking rush jobs to unmapped systems, or having rush jobs not be available for the first few months of game time, or making it possible to buy larger maps, or starting the player off with a wide local map, or maybe just having the rush job descriptions mention how far away the destination is.

**Comment by jozef-mitro** [comment]
Only display rush jobs where the destination is already explored system? Not sure how hard it would be to implement. I haven't had a look at the code yet. Basically you would have to have support for displaying jobs or making them invisible based on some global game data (e.g. what systems are explored).

**Comment by endless-sky** [comment]
That would be easy to do, but in a lot of cases you *want* to accept missions that go somewhere you have not explored yet (either because you think it's worth the risk, or because you've played before so you know how to get to that system even though your current player has not mapped it).

I personally feel like the big red warning message ("You have not yet mapped a route to this system") is sufficient, but some testers have mentioned that getting lost early on and failing rush missions was really annoying.

**Comment by akien-mga** [comment]
> I personally feel like the big red warning message ("You have not yet mapped a route to this system") is sufficient, but some testers have mentioned that getting lost early on and failing rush missions was really annoying.

I think it's enough to, for me getting lost early on is part of the fun :-D And failing a mission is not a big deal, as you just lose the contract, but you don't lose reputation or anything else.

**Comment by endless-sky** [comment]
Given that the penalty for failing a rush job is not so great (all that happens is you don't get paid), I think leaving this as it is, is fine. I think this was really more a question of whether it's okay that the route from one system to another is not always easy to find, but I think exploring the galaxy would get really boring if there was always a straight path between any two points without any possible dead ends or wrong turns.
