### ISSUE TITLE
No way to run the github version 

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#250]
self explanatory, searched every folder and can't find an .exe or anything that'll run

**Comment by kjack1111** [comment]
You have to compile the game, and no, i will not tell you how to do it.

**Comment by thenerdfreak** [comment]
*googles how to compile a game* *watches 10 minutes of videos* well that got me no where fast

**Comment by ItsNickBarry** [comment]
There's a file in the repository called `readme-developer.txt` which you should read.

**Comment by thenerdfreak** [comment]
That told me what to download and where, but nothing on how to use it

**Comment by ItsNickBarry** [comment]
I assume that Code::Blocks can create a file which you can run.  I don't use Windows, so I can't tell you any more than that.

**Comment by Pointedstick** [comment]
If you don't know how to compile code, We're probably not the right people to teach you. It's like asking how to fly a plane. But you don't even need to compile the game from source for most changes you might  want to make. Just edit the .txt files in the data folder and you'll be changing the data driving the game live, no need to re-compile anything.

**Comment by thenerdfreak** [comment]
I heavily edited and re-balanced a lot of things in my txt files for the steam download :p just gonna use steam beta

**Comment by endless-sky** [comment]
See the [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions) if you want to build the code from source. But if all you are doing is modding the game data, you can just use the existing executables and change the data files.
