### ISSUE TITLE
syndicate ships should have plunder personality

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2500]
Copied from discord:

@Cata - today 01:51 CEST
I'm kinda surprised they don't have any Plunder ships. They're all about money and, for many of them, they're clearly holding money over the law.

@tehhowch - today 02:04 CEST
(knowing nothing about the Syndicate storyline): it wouldn't surprise me if the Syndicate has close ties with some pirate factions... those ionic afterburners, atomic engines, and regenerators sure didn't come from some pirate stronghold...

@Endros - today 13:06 CEST
@Cata : what makes a ship a plunder ship? you mentioned the Syndicate would not have plunder ships

@Cata - today 13:22 CEST
A ship with the plunder personality. Like the pirates.

@Endros - today 13:23 CEST
so your point is, that they dont have a fleet defined with the plunder personality?
because in vanilla game, single ships / ship types dont have personalities, they are always assigned in the context of either fleet or npc
and whom should they plunder? only two enemies in question: pirates and korath

@Cata - today 13:23 CEST
That's what I meant, yes.
They could plunder the player if the player breaks the law.

@Endros - today 13:24 CEST
Still, plundering the pirates sounds good

@Cata - today 13:26 CEST
At the point where the player can be plundered, they're pretty much dead anyway

@Endros - today 13:26 CEST
If the player breaks the law in syndicate space, she/he is either strong enough to handle those syndicate fleets, or will reload after losing some ships or will avoid battles
**exactly, so plundering the player does not sound relevant
plundering pirates or korath sounds more relevant to me**

@Cata - today 13:27 CEST
That's true, but doesn't the plunder personality target all enemies of the fleet anyway?

@Endros - today 13:28 CEST
yes, cata

@Endros - today 13:31 CEST
@Cata: do you mind if I copy + paste that to an GitHub issue?

@Cata - today 13:32 CEST
Go ahead

**Comment by Elyssaen** [comment]
Unless there's some lore I don't know (or none of us know yet), I think this idea makes sense. Maybe it shouldn't be _every_ Syndicate ship, but it'd be great to see at least some do it.

**Comment by strollcata** [comment]
In particular, I think the fleets of Quicksilvers that often jump into fights with pirates would probably be good candidates.

**Comment by endless-sky** [comment]
If the Syndicate ships were set up to plunder pirates, that would mean they would leave a lot of disabled pirate ships around for the player to plunder for free. (The Free Worlds already do that, to some degree, but that was necessary to make it so they don't go out of their way to outright kill Republic ships.) That would make it so that just hanging out in a Syndicate system robbing ship graveyards would be as lucrative as fighting pirates yourself.

**Comment by strollcata** [comment]
If I remember correctly, plunder fleets kill the player after looting them. Do they not do that to NPC ships?

**Comment by jafdy** [comment]
They do but they only start plundering after all enemies are dead/disabled. This is ample time for a player to get there and loot the ship.

**Comment by strollcata** [comment]
Oh, that is a problem then.

**Comment by KiLEdEnNis** [comment]
to fix that FW thing ya can make them only disable the Republic government?

**Comment by EndrosG** [comment]
Personality does not care about governments right now. I.e. without additional coding most probably not.

**Comment by egilburg** [comment]
I think plunder personality ships (or at least a subset of them) should have an "aggresive plunderer" trait, remembering which ships they personally disabled, and becoming aggressive towards players who try to to plunder such ships.

**Comment by strollcata** [comment]
That's not a bad idea.

**Comment by KiLEdEnNis** [comment]
it is if ya consider how ya implement it
if you also disabled a lot of ships and just randomly board, the Syndicate would suddenly become hostile
and what makes them "think" the player deserves to plunder? merely shooting that pirate ship once (even after being disabled?, and what if ya kill it) etc.
