### ISSUE TITLE
content question on Albatross ship (remnant)

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2501]
@endless-sky : Why do the remnant ships have numbers as comments in their first lines, and more importantly, why do two of the ships share the same number (656)?
> ship "Albatross" # 656
> ship "Albatross" "Albatross (Heavy)" # 656

**Comment by KiLEdEnNis** [comment]
patience, we'll see if it matters

**Comment by Wrzlprnft** [comment]
could those be some line numbers left over by copy and paste?

**Comment by jafdy** [comment]
Could be total or outfit mass.

**Comment by KiLEdEnNis** [comment]
@jafdy I think you're actually right; it's how much outfit space is used
seems very smart, makes editing variants way easier

**Comment by endless-sky** [comment]
Yes, it's just outfit space used.
