### ISSUE TITLE
Landing/jumping doesn't reset reload counters

### ISSUE THREAD

**Issue by Elyssaen** [endless-sky/endless-sky#2502]
This was first raised on [Google Groups](https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/uBRBpQPSmNA), but if you have a weapon with a lengthy reload, you might notice that the reload counter doesn't reset when you land or jump. A whole day has passed, but that's zero frames as far as the reload counter is concerned.

I might try my hand at a PR that changes this, but I should focus on a few other things first.

One idea going about on the [Discord](https://discord.gg/amWzZ6E) is that rather than reset the counter entirely, it might be more proper to advance it by 60x60x60x24 frames, i.e., a day.

**Comment by EndrosG** [comment]
I really support the +1 day concept rather than resetting the counters.
In my opinion, this will be cleaner (less code duplication) and easier to code at the same time. And it's rational.

**Comment by Nechochwen-D** [comment]
It would also introduce a universal clock definition that could allow for the day to advance as play goes on. (though I think that 24min is to long)

**Comment by tehhowch** [comment]
advancing the reload counters by 1 day's worth of frames every time you advance the game's date by 1 (e.g. enter a system, either by jump or takeoff) wouldn't introduce a universal clock definition... it just uses the existing one

**Comment by Elyssaen** [comment]
PR up: https://github.com/endless-sky/endless-sky/pull/2510

**Comment by endless-sky** [comment]
Went ahead and just changed it so that a day passing resets all reload counters, for simplicity. (3751911)
