### ISSUE TITLE
Hostile Fleets on borders enter from friendly space too frequently

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2507]
In 3c7dd835de19b9cde3d3b5b84940e982e91c812f hostile fleets were made to enter from systems that they are aligned with more often than those they are at war with. However, the weighting is too low to be effective if the systems are not equally numerous.
```
if(isWelcomeHere || neighbor->GetGovernment()->IsEnemy(government))
     linkVector.push_back(neighbor);
 else
    linkVector.insert(linkVector.end(), 4, neighbor);
```
The value of 4 means that hostile-to-these-locals systems receive 4 entries while friendly-to-these-locals systems receive 1 entry.
For the system of Wah Ki, the existing value of 4 means that Unfettered fleets are almost equally likely to come from Wah Yoot (the only hostile-to-the-locals system) vs normal Hai space: 1\*4 entries from Wah Yoot, and 3 entries from Bore Fah, Bote Asu, and Zuba Zub --> **42.8%** chance to come from what should be a "friendly" system).
Increasing the hostile system weight to 8 makes this 8/11, or only 27% chance to come from a friendly system.
For the current Wanderer-Unfettered border world of Ap'arak:
weight=4: 2\*4 vs 1 -> 11% chance to come from a friendly world
weight=8: 2\*8 vs 1 -> 6% chance to come from a friendly world

Other systems having only one hostile neighbor and many friendly neighbors will have a similar result to the Hai/Unfettered Hai border.

I propose the weighting factor is increased by some factor (2, 4, ...), or that the "behind enemy lines" frequency is designed to be independent of the number of each kind of neighbor (e.g. 10%).

**Comment by Elyssaen** [comment]
So full disclosure, @tehhowch and I were talking on Discord and... yep, I think I concur. 3c7dd83 was a great tweak, but I feel like the 4:1 ratio isn't quite enough on any frontier where the majority of systems are _friendly_ and it's just a single one hostile.

And geometrically, that's actually more common. Vindemiatrix/Alioth is a good example. On both sides, one link is hostile and three are non-hostile. Cebalrai/Rasalhague has something similar, and of course Wah Ki/Wah Yoot. Ap'arak is the exception that's already working well, but that kind of border is unusual.

So raising it to 8 makes sense to me, based on the numbers given here.

**Comment by tehhowch** [comment]
I've written two solutions to this:
1 simply increases the weighting factor for hostile systems: https://github.com/endless-sky/endless-sky/compare/master...tehhowch:fix_HostileFleetEnter

The other uses a fixed probability of a fleet entering the current system from a system that is friendly to the fleet (currently 85%). So 85% of the time, Unfettered fleets would arrive in Wah Ki from Wah Yoot, and 15% of the time they would arrive from 1 of the 3 bordering Hai systems: https://github.com/endless-sky/endless-sky/compare/master...tehhowch:fixedHostileFrequency

**Comment by endless-sky** [comment]
Adjusted in c693809.
