### ISSUE TITLE
Torpedoes don't seem like they do enough damage and are too easy to use against non-capital-ships

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#251]
Torpedoes are billed as anti-capital-ship weapons, but they do so little damage that you'll need to hit with like 25 of them to destroy the average light warship or even an Argosy. That seems like waaaaay too much ordnance for those types of ships. For heavy warships you'll need more like 70-100 hits. Their battle role would feel more correct if they did much more damage but were slower and easier to dodge. This would refine their role into capital ship killers and differentiate them from the Meteor and Sidewinder missiles better, and also allow for some fancy piloting; putting a torpedo launcher on a fast ship and manually flying it into position to fire the thing which was always fun in the EV games.

**Comment by gchapyzh** [comment]
Seconded. Give missiles more damage and make it so it takes a few hits to disable them. Make them slow, too.

**Comment by thenerdfreak** [comment]
Missiles hardly need more damage, considering the AI is set to spam as many as it can at whatever enters the system, and most of them have either tracking, huge range, or an explosive radius and high damage. If anything just make them easier to dodge, even the slowest ones will keep coming unless you ram it into an asteroid

**Comment by endless-sky** [comment]
Missiles already do more damage per second than [guns of comparable size](https://github.com/endless-sky/endless-sky/wiki/TableOfWeapons), and have the added advantage of extremely long range. That makes me hesitant to make them even more powerful. Also, slower, higher-damage torpedoes already exist: the Typhoon Torpedoes.

**Comment by Pointedstick** [comment]
To be honest, I've never felt like any of the missiles in the game were quite right. None of them feel like they do enough damage per shot (damage per shot seems like a better metric than damage per second for these; DPS implies spamming missiles, which is expensive and burns through all your missile ammo quickly; and not something the player will be likely to do). Most battles in Endless Sky seem to take place at extremely short range, so the range advantage of missile weapons only primarily matters for coward-personality pirates that run away from you shooting missiles, and that's easy to defeat; just get out of range of the missiles, wait for them to run out of ammo, and then pop 'em. And missile launchers use valuable gun hardpoints. As a result I find myself using primary weapons exclusively instead of any missile weapons at all and not really worrying about the missiles fired at me. Piloting a small ship, I can dodge them easily enough, and as a large ship, the combination of a heavy anti-missile turret and lots of shields does the trick.

In order to make missile weapons more fun, more viable for the player, more dangerous, and more in-line with a game universe that prominently features anti-missile defenses, the following changes would make sense to me:
- Make the Meteor missile even cheaper and increase the number of missiles that can be carried per launcher; increase the viability and cost-effectiveness of spamming these
- Substantially increase the damage of the Sidewinder missile, and perhaps make it a bit more expensive to compensate
- Make the standard Torpedo into essentially the current Typhoon Torpedo and have it do even more damage
- Make the Typhoon Torpedo into something more distinct from its parent weapon. Maybe a cluster or flak torpedo that's better against the lighter ships typically used by the Free Worlds at that point in the story arc?
- Make the Javelin and Heavy Rocket do more damage

**Comment by thenerdfreak** [comment]
- Meteor is already extremely cheap and you have enough missiles to take down a light warship using an interceptor
- the whole point of sidewinders is to be harder to destroy by anti-missile turrets, faster than meteor, and do slightly less damage
-no. many reasons why not to
-there already is a rocket that does the whole flak thing, heavy rocket has an explosive radius, best for fighting groups of small interceptors/fighters/drone
-javelin is literally made to be spammed, -heavy rocket isn't meant for use against big ships anyway, it's meant to take down small interceptors with its big explosive radius

**Comment by Pointedstick** [comment]
To take down a Manta (for example) with Meteors requires 81 missiles fired from at least three launchers (to hold enough ammo), for a per-kill cost of 40,500 credits assuming every single missile hits. That's a huge number of missiles, and with three launchers, you probably can't fit any non-missile guns at all. Something about that just seems, I dunno, *wrong.*

**Comment by gchapyzh** [comment]
Give all Meteor missiles the properties and damage of a nuclear missile.

Seriously, however, missiles do need to get buffed. Perhaps give missiles more damage but less fire rate.

**Comment by Oeleo** [comment]
Yes i like this idea, more damage and less fire rate = less lag when there are >100 ships which fight together, and like that it will increase the interest of dodging it.

**Comment by Pointedstick** [comment]
One problem is how quickly Torpedoes turn. If Torpedoes had a much lower turn value, they would have a much more difficult time tracking non-capital-ships, and then perhaps they could do more damage to compensate. A value of 0.7 for the turn and 5 for the velocity makes their unwieldiness very dramatic and provides a good differentiation from Meteors and Sidewinders, and I feel that this could justify an increase in damage even outside of the proposed radar/jamming changes proposed in #346.

**Comment by endless-sky** [comment]
Torpedoes will be rebalanced once missile jamming is added (#346). That will make it possible for them to be powerful anti-capital-ship weapons, while also making them easier for small fast ships to evade. So, I'm going to consider this to be replaced by idea #346.
