### ISSUE TITLE
call for help: tricky `to offer`

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2514]
I am trying to setup a non-linear mission chain. Sadly, the non-linearity requires some comparisons to be made which I currently fail to implement. *I hope for some help from @endless-sky but everybody else is welcome too*

What I need to test is something like
```
to offer
	"reputation: Navy Intelligence" >= "reputation: Republic" + 100
```
(*just with other player conditions, not the reputation ones, but that's not important*)
and I dont see a way to get that working within one mission because in the `to offer` I can't just introduce a temporary variable like this:
```
to offer
	"testvalue" = "reputation: Republic"
	"testvalue" += 100
	"reputation: Navy Intelligence" >= "testvalue"
	clear "testvalue"
```
because in `to offer` you can't do such apply conditions

I can write it all in a very predefined linear fashion. In a linear mission chain, in my case the `testvalue` can be filled with static numbers, which increase from mission to mission (by different numbers, sometimes +10, sometimes +30, or +50, or ...)
But writing it as linear chain is not what I want. I want to allow the player to meet the conditions for e.g. mission 3 before the conditions for e.g. mission 2 (which are logically independent)

So... any ideas how to combine test conditions and apply conditions?

- The missions in question do **not** have an on offer conversation, but only actions (apply conditions, triggering events, etc.)
- I could live with putting some stuff into an invisible `on offer` conversation and doing all the test and apply maths there, and using defer if it doesnt turn out in the end, **but** we dont have **invisible** conversations *and* outside a conversation I can't perform neither test conditions nor `defer` within the `on offer` mission action.

**Comment by EndrosG** [comment]
from all the various approaches I have gone through so far, the cleanest one seems to be to extend `Conditionset::TokenValue(...)`.

<details><summary>What did I consider so far?</summary>

- allow nested computations, i.e. (A+B) <= (C+D) -- which includes A <= (C+D) and (A+B) <= C
  - the most promising solution so far
- introduce an `apply` statement to the `on *` ConditionSet mechanics... tricky, really tricky, and not very "nice" or "clean".
- introduce some sort of `before offer` ConditionSet similar to `to offer | fail | complete` as pure ConditionSet, but with an ::Apply() handler used.
  - that would end up in a very simple enhancement of Mission::CanOffer(...)
```
+	beforeOffer.Substitute(subs).Apply(player.Conditions());
	if(!toOffer.Substitute(subs).Test(player.Conditions()))
		return false;
```
- a few more thoughts... like using invisible (hidden) missions with either `priority`, (none), or `minor` attribute as some sort of `cronjob` to set `testvalue` variables upon landing.
  - risk of messing up other plots to get offered at all.
  - using `minor` is not desirable because the missions to make use of the `testvalue(s)` are regular ones, not minors.

</details>

-----------

`ConditionSet::TokenValue(...)` is the nice thing that takes care of converting any playerCondition (or the special keyword "random") into a number and is used by both, `ConditionSet::Test` (twice, left and right side) and `ConditionSet::Apply` (once, right side).

Upon my current believe it would be the cleanest approach to start at `ConditionSet::TokenValue(...)` and implement there a bracket feature which is triggered by a "(...)" string as 2nd parameter (&strValue) and causes the content within the brackets to be evaluated (::Test'ed) as (nested) ConditionSet. That means, I would re-write the condition first mentioned in the initial post as:
```
	"reputation: Navy Intelligence" >= "('reputation: Republic' + 100)"
```
<details><summary>Explanation of that syntax</summary>

+ I think that the entire bracket construct needs to be put into quotation marks to be noticed by the `DataFile::Load()` function as one single DataNode.token
+ The content of the bracket needs some forms of quotation too (nested quotation), in order to recognize the (usually) three tokens inside the brackets.
+ The TokenValue() function needs to split the bracket construct into the (usually) three tokens, convert them into a ConditionSet and then ::Test this set.
+ Splitting the bracket construct into the correct set of Tokens seems - at least to me as a non C++ professional - to be the most tricky part because of nested quotations. Theoretically, the content creator could even nest two or more brackets into some `(A+B) <= (((C+D) + (E+F)) + (G+H))` formula, if we would have a nice way of identifying the tokens inside the brackets. It all depends on that clean splitting, because the ConditionSet::Test would call again ::TokenValue() on each Token and thus another nested bracket would be possible **if** quotation rules can be handled.

+ Running `ConditionSet::Test` on a regular `"reputation: Republic" += 100` condition (which is usually an apply-condition, not a test-condition!) would return A+B, i.e. the correct sum.
  + So running `ConditionSet::Test` on any nested bracket seems the correct approach for both, ::Test and ::Apply conditions / expressions.
+ ideally, we would introduce
```
			{"+", [](int a, int b) { return a + b; }},
			{"-", [](int a, int b) { return a - b; }},
			{"*", [](int a, int b) { return a * b; }},
```
but the existing `+=`, `-=` and `*=` would already do the trick, it would just look wrong from the mathematical point of view.

</details>

**Comment by tehhowch** [comment]
This should be handled by #3128, which extends the ConditionSet::Expression class to identify which binary functions are testable, versus actionable.
In short, ConditionSet::Test creates a clone of the input conditions list, and then calls Apply on this clone, and then performs Test on the clone. Only on the first iteration of ConditionSet::Test is the Apply action performed (since `Test()` is recursively called on the `and` and `or` nodes).

The desired check in the OP could then be done as:
```
to offer
    "current_Republic_rep" = "reputation: Republic"
    "current_Republic_rep" += 100
    "reputation: Navy Intelligence" >= "current_Republic_rep"
```
(it could also be done without the intermediate variable, but using an intermediate variable explicitly conveys that the original Republic reputation is not modified, even to those that do not understand the mechanics of the condition evaluation).

The next step after #3128 is to implement some sort of "unrolling" of sides of unknown length into ConditionSet::Expressions. For example, ConditionSet load & add methods could see
```
to offer
	"reputation: Navy Intelligence" >= "reputation: Republic" + 100
```
and deconstruct that into 2 apply expressions (100 + rep:Repub & var2test = value) plus 1 test expression.
As @EndrosG points out above, some extension to the DataNode class may be needed/desired to help it "tokenize" the user's writings into valid conditionset expressions, e.g. supply missing parentheses.

**Comment by tehhowch** [comment]
#3128 now supports this perfectly:
```
to offer
    "reputation: Navy Intelligence" >= "reputation: Republic" + 100
```
in addition to including support for parentheses.
I didn't extend DataNode to do it, so parentheses have to be separated by spaces, i.e. `2 * ( 5 + "reputation: Republic" ) - "reputation: Empire" <= 0`, or they will get grouped into the token they are touching (e.g. `2 * (5 + "reputation: Republic")` parses into `2, '*', '(5', '+', '"reputation:', 'Republic")'`).
