### ISSUE TITLE
Bug 0.8.8 missile's fighters

### ISSUE THREAD

**Issue by Oeleo** [endless-sky/endless-sky#252]
The fighters (daggers) don't want to use missile lunchers like before, it doesn't work with "normal" and sidewinder missiles, they don't shoot it, except one, I don't know which one but only one fighter can shoot it. I'm on windows 8.1 and I had already this fighters in my bactarians before the update

**Comment by endless-sky** [comment]
The AI has been changed to not waste missiles if your "team" is much stronger than the enemies you are fighting, in response to a request that a lot of people have made (#76).

**Comment by Oeleo** [comment]
Oh ok good that was what you talked about.

**Comment by brick96** [comment]
Glad I saw this, I was wondering why they weren't shooting (launching?) missiles

**Comment by endless-sky** [comment]
As of commit 39e28db, you can control this behavior in the preferences panel (setting escorts to fire missiles always, frugally, or never).
