### ISSUE TITLE
Compiles with runtime errors when recent version of libpng is installed.

### ISSUE THREAD

**Issue by Isaacssv552** [endless-sky/endless-sky#2522]
I have both libpng 1.6.29 and 1.4.13 installed, the latter specifically for Endless Sky. Previously, Endless Sky compiled correctly using 1.4.13. However, when compiling the most recent version of ES libpng 1.4.13 causes the game to hang on launch, displaying only a blank screen and a bunch of libpng errors in the command prompt. Switching the libpng framework in the XCode project from 1.4.13 to 1.6.29 solves the issue.

**Comment by endless-sky** [comment]
I can't duplicate this - the latest code builds and runs fine for me. What are the error messages you are seeing?
