### ISSUE TITLE
Hangs on startup

### ISSUE THREAD

**Issue by purplerider** [endless-sky/endless-sky#2523]
![why](https://cloud.githubusercontent.com/assets/28691680/26037313/aca3c262-38be-11e7-85e4-481b76152c81.png)

I am running Ubuntu 16.04 LTS and when I attempt to launch endless sky Steam will say that it is running. However, it only pins a cpu core to 100% and slowly starts filling RAM until it gets full then swaps and repeats.

**Comment by tehhowch** [comment]
Are you in the beta release channel or only stable? 
Also, share some system specs (i see 8 cores and 16 gb ram, but gpu type/driver may be helpful)
I am 16.04 as well, but build from source on a Dell Inspiron 14 7437, and have no issues launching the game

**Comment by endless-sky** [comment]
Have you tried launching the game outside of Steam?

`$ ~/.local/share/Steam/steamapps/common/Endless\ Sky/endless-sky`

Also, are you running 32-bit or 64-bit Linux? And, 32-bit or 64-bit Steam?

`$ file ~/.local/share/Steam/steamapps/common/Endless\ Sky/endless-sky`
> /home/michael/.local/share/Steam/steamapps/common/Endless Sky/endless-sky: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=bcdcbf249b0671d3cda9275f737c7851fe0093bd, not stripped

If you could launch the game in gdb and then interrupt it (`^C`) and find out what function it's hung up in, that might help. If only one core is active that probably means it's happening while it is still trying to parse the data files, before it starts loading images. It might help to have Steam verify the install to make sure you don't have corrupted files.

**Comment by purplerider** [comment]
I am in the stable release channel. I have a Xeon E3-1240 V5, 16gb ram, and a RX470 with the amdgpu-pro 16.60-379184 driver. Is there anything else that may be helpful?

**Comment by purplerider** [comment]
Alright I have 64 bit linux. When I try to launch from command line I get:

`pie@adam-MS-7998:/media/MoreSpace/SteamLibrary/steamapps/common/Endless Sky$ ./endless-sky
./endless-sky: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
`

**Comment by endless-sky** [comment]
Try installing the libsdl2-2.0-0 package if it's not already on your computer. The SDL library ought to be part of the Steam install, but maybe it's not for some reason.

Also, can you post the full output of this command?

`$ ldd $ ~/.local/share/Steam/steamapps/common/Endless\ Sky/endless-sky`

That will tell you where all the libraries that Endless Sky depends on are being loaded from (or if any are missing).

**Comment by purplerider** [comment]
I installed libsdl2-2.0-0 and got a different error: 
`pie@adam-MS-7998:/media/MoreSpace/SteamLibrary/steamapps/common/Endless Sky$ ./endless-sky
./endless-sky: error while loading shared libraries: libGLEW.so.1.10: cannot open shared object file: No such file or directory`
I will try to install libraries until it works.

**Comment by purplerider** [comment]
So... trying to install libGLEW.so.1.10 resulted in:
`pie@adam-MS-7998:~$ sudo apt install libGLEW.so.1.10
[sudo] password for pie: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libGLEW.so.1.10
E: Couldn't find any package by glob 'libGLEW.so.1.10'
E: Couldn't find any package by regex 'libGLEW.so.1.10'
`

**Comment by Rakete1111** [comment]
@purplerider `libGLEW.so.1.10` is a shared library, it has (almost) nothing to do without how the package that provides it is called. The package is called `libglew-dev`. If you don't know the package name of a library, googling it should reveal it in most cases.

**Comment by purplerider** [comment]
@Rakete1111 Thanks!

**Comment by tehhowch** [comment]
@purplerider just in case: https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#linux

**Comment by endless-sky** [comment]
I'd suggest installing directly from the [PPA](https://launchpad.net/~mzahniser/+archive/ubuntu/endless-sky) instead of through Steam. The package on the PPA ought to be linked to the right versions of the libraries, and it will automatically pull in all the right dependencies.

I suspect that either your Steam runtime is somehow missing some of the standard libraries, or Steam changed what packages are part of the default install and now some of the ones Endless Sky depends on are not included.

**Comment by purplerider** [comment]
Alright. I'll try it through the ppa. Thanks everyone for the help.
