### ISSUE TITLE
Add support for multiple fleet types when specifying tribute fleets

### ISSUE THREAD

**Issue by Disiuze** [endless-sky/endless-sky#2524]
Currently, tribute only supports spawning one fleet type. I learned this the hard way when I had to [remove the merchant fleets from Greenwater](https://github.com/Disiuze/TributePlus/commit/a32a9b93969525396d89dacd8ba037e96c4307e3) in TributePlus, a plugin which allows the player to capture most planets. By allowing planets to have multiple types of defence fleets, planets such as Greenwater have could both Hai and Merchant defence fleets.

I know tribute is extra content for the bored player, but this seems like it wouldn't be too hard to add.

**Comment by Elyssaen** [comment]
Could be kind of useful, though I guess it's only a nice-to-have. Code-wise, it'd take a little bit of reorganising, but it's achievable.

It's one of these things that I'd guess MZ won't personally place as high enough priority (he's got plenty of other more important stuff), but there are a few people around who'd happily code it up and PR it for fun. I'm one of them, but will only do it if the idea has some measure of support. Another forgotten PR won't do anyone any good. : )

**Comment by KiLEdEnNis** [comment]
the only thing it'd add is multiple governments defending a planet, but it seems a good idea and a bit realistic
ya tribute a planet, so the local militia, maybe some republic ships, and a couple of merchants defend

**Comment by endless-sky** [comment]
This seems like a really low priority, especially given that if you really wanted to you could just create custom fleets that combine the different fleets you want to include.

**Comment by tehhowch** [comment]
I think the only not possible bit with a combined fleet is use of multiple governments, e.g. Efret and Quarg ships would defend their stations in automata space, but the tribute action can only apply `atrocity` to one of them.
To work around that, one could create a combined government solely for this purpose (with the `attitude toward` values), but that gets really unwieldy and ends up with weird government names when you target the defending ships as well.
