### ISSUE TITLE
Custom hostile disabled hails for different (mainly alien) governments

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2526]
I noticed that the Heliarch seem very fond of Shakespeare. I'm not sure if specifying `"hostile disabled"` hails for a government is supported right now, but I think it would be worth supporting it and providing some of the alien races with their own hostile disabled hails that give us a little more insight into their own cultures, because I doubt that calling someone a "fobbing dizzy-eyed codpiece" is a universal insult across the galaxy.

**Comment by Elyssaen** [comment]
Good idea. I might be up for writing some Wanderer ones, and I'd be very willing to code up the needed feature if that'd be helpful.

**Comment by Elyssaen** [comment]
Code feature is ready: https://github.com/Elyssaen/endless-sky/pull/15

Working on Wanderer dialogue next. The Wanderers don't have a hostile hail either, so I'll do that too.

Here's the format:

```
government "Wanderer"
	...
	"friendly hail" "wanderer untranslated"
	"hostile hail" "wanderer untranslated"
	"hostile disabled hail" "wanderer untranslated"
```

(They only start untranslated, don't worry. I'll be writing the translated ones that are triggered by an event in wanderers start.txt.)

**Comment by Elyssaen** [comment]
Done some hostile and hostile disabled Wanderer hails, check here: https://github.com/Elyssaen/endless-sky/pull/16.

**Comment by Elyssaen** [comment]
As well as the code PR #2555 I've also put up a PR for my Wanderer hails, #2556. @Amazinite, you should write some too!

**Comment by Amazinite** [comment]
Seeing as how the functionality of changing hostile disabled hails for governments is now available, I'll put this on my to-do list.

**Comment by Pointedstick** [comment]
Implement now, thanks a lot @Amazinite. I'll add some more later.
