### ISSUE TITLE
Should Ammunition be obtainable from exploding ships?

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2528]
I feel that adding ammunition as a flotsam object makes it easier for a player to consider using secondary weapons, especially rare ones. This will not allow players to refuel in-flight, as ammunition in your cargo hold cannot be loaded without landing, but will allow players to delay the trip back to (specific outfitter/system), in which the sole purpose of the trip is to refill ammunition stores. For rarer ammunition (e.g. only plunderable from hostile opponents), this adds a small increase to the "refill rate", as you are able to obtain a small amount of the ammunition while battling the opponent and not just when boarding a disabled opponent. 

This increase in the loot rate can be controlled by having a low probability for ammunition to be spawned as flotsam (with regular 25% of quantity if selected), or by simply having a low quantity. I feel this rate increase alleviates player frustration and the "grinding" needed. Additionally, looting an ammunition type which you cannot fire may inspire you to consider using that weapon, simply because you know that you can obtain ammunition for it without needing to find where it is sold and buy it in bulk.

(Yes, this issue is a plug for #2498 , which was coded without first polling the community for discussion, and will likely not be merged unless the community agrees on its merits. There the rate increase is limited by reducing the expected ammunition flotsam amount to only 5% of the destroyed ship's total, rather than the 25% for items in its cargo hold.)

**Comment by Elyssaen** [comment]
I tried this out and really enjoyed it. ES could really do with a bit more encouragement to use missiles, and this seems like a good step in that direction.

Was also relieved that it doesn't work on Nuclear Missiles. : )

**Comment by strollcata** [comment]
This could be a fun mechanic, but an issue arises when you can kill an enemy ship solely with missiles. Theoretically, you could have an infinite-ammo weapon with higher damage and efficiency than regular weapons, allowing you to put out more damage than you should be able to at a given tech tier. Also, I know this is a game and not a simulator, but having missiles not explode with the ship doesn't make much sense. Thirdly, tying back in to the first issue, the cost of firing these weapons is significantly decreased, which is a major problem given that cost is part of their balancing. It could work, but you'd need to be extremely careful when implementing it.

**Comment by KiLEdEnNis** [comment]
ammo could explode, maybe make a tag that makes like 20% of the missiles "disappear" as it exploded if ya want realism
if ya just like the gameplay over realism keep it

**Comment by tehhowch** [comment]
The idea of ammo in the flotsam stems from gameplay rather than added realism - if we are going for 'realism' then flotsam from explosions should only rarely yield intact cargo/outfits, and instead we should get damaged items that are nearly worthless.
The player can take the game-logic leap of "Well, the ship was carrying a lot of these... it kinda makes sense at least a *few* survived the ship exploding."
From a "realism" standpoint it is rather unlikely that anything with some sort of chemical reactant would survive an explosion, especially if it is human in origin (aka how to sink a WW2 battleship)

Ammo in flotsam = explosions give some missiles = slightly less trekking across the galaxy for (ammunition) = more fun

Especially if that ammunition is for a Korath Piercer or Minelayer.

**Comment by tehhowch** [comment]
Closed as #2498 was merged today
