### ISSUE TITLE
Custom *friendly* disabled hails for different governments 

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2531]
This is not the same as #2526.
But given the fact that [`boarding missions.txt`](https://github.com/endless-sky/endless-sky/tree/master/data/boarding%20missions.txt) currently features two assisting missions, namely for Merchants and for Hai, we should also be able to let them have different disabled hails.

**Comment by Elyssaen** [comment]
Potentially useful, sure. There are a few other hard-coded dialogue returns in the same area of the code that could potentially be brought out.

My only problem with you posting this issue right now is that shortly before you did, I completed/published a feature (Elyssaen#15) to answer #2526. I was planning to post a PR once @Amazinite had had a look.

This PR kind of muddies the waters: do you want me to abort my feature? A feature doing friendly disabled hail messages would definitely conflict.

**Comment by tehhowch** [comment]
If Endros has a commit or two that add these, just merge his branch into yours, resolve the conflicts, and voila, a joint author PR that overhauls the disabled hails.

**Comment by EndrosG** [comment]
I dont see why both conflict, @Elyssaen.
First of all, we have of course to answer the question, what the friendlyDisabledHail is used for exactly.
Is it:
- "we cant help you because we are disabled"
- "we are disabled, please help us"
- "you are disabled(!) and wish our help?"

I would say, it is the second one.
Then, the patch seems pretty easy.
I did the coding just now and I hope I did it correctly - I am not at home right now, not sitting a big monitor or anything else, just having a browser here.
I did not yet edit data/hails.txt, because for my part (friendlyDisabledHail), we also need to add some "friendly disabled" phrases to the hails.txt file, because these dont exist yet at all.
Could you please do that?

I created the Pull-Request into your feature/HostileDisabledHail branch.

**Comment by Elyssaen** [comment]
My thinking was:

- If we merge them into one feature before PR, it's then one PR doing two things. MZ usually prefers one-PR-one-task.
- If they both proceed as two independent features, they _would_ generate a merge conflict MZ would have to resolve.

If you both feel strongly that this we should PR both together, then okay, let's try. I'll merge your changes into a new branch with a better name. I've also given you a collaborator invite in case you ever want to skip the middle man, though tell me beforehand if you're going to use it because I rebase a _lot_ at the moment.

**Comment by Elyssaen** [comment]
As requested: https://github.com/Elyssaen/endless-sky/pull/21

Really want to squash the commit history, but don't want to erase your contribution, so please advise.

**Comment by tehhowch** [comment]
Left my feedback on Elyssaen#21.

You could maybe squash down to 1:1, but keeping history should be fine, as it isn't like you have 40+ commits in it.

**Comment by EndrosG** [comment]
I dont know how to edit multiple files in one commit in the browser frontend of GitHub... Each file save results in one commit for me, if I use the browser frontend of GitHub. And that was the only thing available to me this morning.
Do whatever you want however you want, as long as we both get credited somewhen in the changelog.txt for that thing, it should be all fine.

**Comment by jafdy** [comment]
Put it in a separate branch PR it to your self and crush the PR commits on merge.
