### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2532]
I'm using the latest commit but when I try to compile I get "source/ImageBuffer.cpp:17:17: fatal error: png.h: No such file or directory
 #include <png.h>"
Not being a C++ programmer, I'm not going to try to tweak the code and remove calls to png.h.

**Comment by stinkray** [comment]
Did you install libpng-dev or a similar package that would provide png headers from your package manager?

**Comment by Elyssaen** [comment]
Maybe this? https://github.com/endless-sky/endless-sky/pull/2519

**Comment by VonZorch** [comment]
@stinkray Yes.
@Elyssaen No and no.  I should have mentioned I'm trying for a Linux compile.  I have been using the windows 64bit under Wine, It's kinda buggy and slow.

**Comment by VonZorch** [comment]
@stinkray Oops, I must have misread something, as I actually didn't have it installed.  I had libpng.16-16 already installed and skipped right over libpng-dev.  I do feel stupid.
Just finished a successful compile.
Thanks for your assistance.
