### ISSUE TITLE
Feature Request: Admiral Mode

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2533]
This would be the AI controlling your ship in battle while you are managing your fleet.
It would be toggled with a hotkey and automatically turned off when a control input (manuvering, fire weapons etc) is made.

**Comment by Elyssaen** [comment]
This is... interesting. I haven't done much fleet command stuff myself, but is there really enough to it at the moment that you'd want to do this? This is getting into RTS territory, I guess. That could be cool, but can you currently focus the fire of selected ships on one target? And switch between selections with hotkeys? I genuinely don't know, but I know I'd want both of those before I started imagining playing this like an RTS.

**Comment by tehhowch** [comment]
Yes, if you have escorts grouped to multiple number keys, you can toggle targets with R, tell the escort group to attack it with F, and then use a different number key to select a different escort group, and repeat.

I'm not sure how your ship should behave when you are selecting different targets, as you will already fire fixed guns straight ahead with autofire enabled

**Comment by VonZorch** [comment]
Behavior would be like an escort ship, head for the nearest enemy and try to kill it instead of drifting aimlessly.

**Comment by EndrosG** [comment]
Are battles even long enough for this to be "worthy"? Not talking against it, just wondering how long a battle should be to make such an admiral mode really interesting.

**Comment by VonZorch** [comment]
In the Hai and Wanderer storylines some of them are huge and thus long.
Playing 0.9.4 I had multiple occasions where in one battle just when it looks like the battle is over, except for a little mopping up, a new Unfettered Hai fleet jumps in or lifts off.  That's multiple times in one battle.
That happens sometimes in the FW storyline too with Republic fleets.

**Comment by endless-sky** [comment]
As I've said elsewhere, the missions and gameplay in ES are geared toward pilots with a single ship or a handful of escorts, not a giant fleet. (Once you have a fleet that big, you've basically "won" anyway.) So, developing the stuff for controlling large fleets is not a high priority.

**Comment by KiLEdEnNis** [comment]
I think a simple switch to that mode is most of what is needed; the switch would switch flagship controls to those of escorts
simply said giving orders to your flagship would work like autopilot, as if you would order an escort, although if the flagship dies you still die, and using a movement key would cancel that autopilot so one could quickly switch in need

**Comment by VonZorch** [comment]
@KiLEdEnNis Yes, exactly.

**Comment by tehhowch** [comment]
Just for kicks I added another condition to [AI::Step::298](https://github.com/endless-sky/endless-sky/blob/9ce737231d6e4031c490c50ae7d5fba487290e9a/source/AI.cpp#L298), resulting in 
`if(it.get() == flagship && keyHeld.Has(AutopilotCancelKeys()))`

And viola, AI controlled flagship.
However, this means it totally ignores your travel plan, and (as a computer) can react really fast, so it will happily jump and land of its own free will

**Comment by VonZorch** [comment]
I don't see a need for a whole-fleet autopilot and as the admiral mode would only be used in combat, travel plan etc aren't important.
The only control needed would be a hot key to enter/exit.  Ideally exiting when any ship control is used.
