### ISSUE TITLE
Safe passage does not apply to escorts with "Free Worlds" government

### ISSUE THREAD

**Issue by stinkray** [endless-sky/endless-sky#2534]
Related Commit: b5c6229838bd5d1bb769e6c034460b6d9639dac9 
By changing the government of the escorts in these missions from Escort to Free Worlds leads to the Free Worlds prisoner transport convoy and the Navy garrison over Kaus Borealis seeing each other as hostile parties, leading to the ultimate decimation of the fleet and failure of the mission. 
Either this commit should be reverted, or there needs to be some changes to how safe passage is managed.

**Comment by gchapyzh** [comment]
Can confirm said issue. Landing in the target world does not complete the mission either.

**Comment by endless-sky** [comment]
Reverted in 31d97c7.

**Comment by gchapyzh** [comment]
That fixed it. Thanks!
