### ISSUE TITLE
WIP: Quad Javelin Pod Turret

### ISSUE THREAD

**Issue by Highrs** [endless-sky/endless-sky#2535]
The Quad Javelin Pod Turret is something I have wanted for a while now, so I decided to go ahead and try to make it myself.

![image](https://cloud.githubusercontent.com/assets/8764280/26278847/018afbbc-3d59-11e7-938e-e4a26115ae84.png)
( Temporary texture)

ToDo list for me:

- [x] Texture
- [x] Hardpoint Texture
- [ ] Balance
- [ ] The scrip behind the turret
- [ ] Locations where these could be found

Several things to consider:
- The Turret should have a mode, or a version of said turret, where it fires off its entire payload in one burst, with one exceptionally long reload ( like a hwacha? ). Sorry anti-missiles.
- Tracking on this thing may be an issue, since missile turrets don't exist yet.
- The size of this monster will have to be much larger than just 4 javelin pods, what with the complexity of reload mechanisms needed for it.

Suggestions and feedback would be appreciated.

**Comment by Elyssaen** [comment]
Hey, interestingly, this exact idea has come up before! See https://github.com/endless-sky/endless-sky/issues/1790.

@Isaacssv552 and @Pointedstick both were into it. I think Isaac actually made something it here: https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/qoBwc77VLoA

**Comment by gchapyzh** [comment]
In fact, this idea was in my head since #1939 
I think human weapons need to have super-variants for late game ships. Eg - where a human turret would be too small and too weak to be on any good on a Hurricane, THIS
![image](https://cloud.githubusercontent.com/assets/8764280/26279628/a3839758-3d6d-11e7-8a40-5ba8b060f0bf.png)
would be a more appropriate fit. ( Just made that for a later thing i'll be trying to make )

**Comment by Elyssaen** [comment]
I don't know, there are a few considerations here. Mainly: human weapons are tier 1, your Hurricane is tier 2. Unless/until humans advance in technology it's reasonable that you're going to want more advanced weapons on your Hurricane than humans can offer.

Extremely large human weapons still aren't going to offer the DPS/ton of higher tier technology, after all. And in general I'd be careful making _too_ many new weapons extremely large, because it moves all the smaller ships more and more toward redundancy.

**Comment by gchapyzh** [comment]
Keep in mind that most of human space has no access to alien weapons, but what with the new aliens being discovered left and right (or, up and down), it would make sense for them to start building bigger ships, if not more techy once. ( Bigger ship for that purpose and line of logic is something I am working on too )

These weapons are also a shortcut to not having 10 hardpoints, but instead fewer once with larger weapons.
( you think that Heavy Laser battery should have another layer of lasers on top? :P )

**Comment by gchapyzh** [comment]
To be clear, I have no plans to make many weapons like this. Only a few that a larger human ship would need to stand a chance against alien scum!

**Comment by jafdy** [comment]
Humans know of just 4 aliens. The Hai, Korath, Quarg and Pug. 3 of witch where already known and the last of them was discovered and then defeated.

**Comment by gchapyzh** [comment]
And the player discovered the Wanderer, Collective, and the Korath machines. That has to force humans to improve their ships at some point.

**Comment by EndrosG** [comment]
@gchapyzh : if you really want to go into bigger ships, I can give you a soft "warning" about the effects.
You might want to check out the G1 ship series from my [Marsian Ancestors](https://github.com/EndrosG/ES-Plugins/tree/master/Marsian%20Ancestors) plugin.
In that plugin, you find different generations of ships all being based on the same base technology (a pretty much tier 1 technology) but being scaled up just by large scaled industry.
These ships become stronger and stronger, still using tier 1 technology, but finally in the G4 they can beat an Archon (okay, the G4 ships use some tier 2 technologies, but I think those could be replaced by tier 1 stuff without harming too much).

**Comment by EndrosG** [comment]
My Triple Electron Turret (being a triple version of the electron turret, i.e. with 6 beams) there delivers lots of damage at a high turret size (in the configuratio of april 2016: 160 tons, but subject to change towards 180-200 tons, I think).

One of the *relevant* effects of scaling up ships is, that you get more and more usable outfit space which you can use for shield generators.
And with the increase of engine size / space - just adjusting to the size of the ships - the player even gets the option to dedicate even more space (in larger scales) to shield generators just by cutting down the engines by 10-20%. Having a high rate of shield charging though changes the survivability of your ship a lot.

Really, take a look at the G1, G2 and may be G3 ships of my Marsian Ancestors plugin (there is an `unlock all.txt` data file which you can easily adjust) - and also have a look at the Nosy freighter class in the [Eireen](https://github.com/EndrosG/ES-Plugins/tree/master/Eireen) plugin in the same repo. That's kind of a next generation freighter series with large capacities but still low combat abilities... Well, 8 turrets in the 3-stage version is not really low, but you will see. *The Eireen data files currently contain only Nosy I-III, while my excel sheet includes also IV-VI*

**Comment by Elyssaen** [comment]
Ah, you said "to be any good **on** a Hurricane", and I took that to mean you wanted human weapons to be competitive to use on an alien ship. But if you mean you want human weapons to be competitive to use **against** an alien ship, I get you.

I guess we're talking after the main campaign, and perhaps even after `wanderers middle.txt` where humans come into conflict with the Kor Sestor. That's where the real pressure would start for humans to be able to better defend themselves.

Bigger weapons would deserve higher efficiency, so would be more effective, and as a stopgap I can see a place for them. I just wouldn't go _wild_: it's in keeping that humans would also try to steal better technology (and this is something for MZ to decide), and gameplay-wise it's probably not ideal for weapons to just creep up and up in size. (I still fly a Blackbird...)

**Comment by gchapyzh** [comment]
Really, looking at the Laser Battery above, I don't see any ship except for the largest monsters out there using them, so over-using these two weapons should not become an issue. After all, a smaller sunbeam turret is likely more deadly and less power demanding than a 6 barreled laser turret. ( Unless I am mis-estimating and that is not the case ) 

@EndrosG , those ships are amazingly gigantic! What's the story behind them?
Yes I see what you mean, but since weapons will only upscale in size, and not in in tech level for this ship, there is no reason to keep building bigger and bigger ships until more powerful tech levels are reached by humans. Those would just be murdered by much smaller and more powerful ships, size and number of lasers be damned.

**Comment by gchapyzh** [comment]
![image](https://cloud.githubusercontent.com/assets/8764280/26291531/b643448c-3e63-11e7-9c24-694afdcc9e67.png)
Updated texture on this to look more original and
![image](https://cloud.githubusercontent.com/assets/8764280/26291545/c7e47382-3e63-11e7-857b-5a7281e4f2a6.png)
the hardpoint texture made.

**Comment by tehhowch** [comment]
The base is pretty obviously the Heavy Anti-Missile...

**Comment by gchapyzh** [comment]
@tehhowch it was the largest base I could find, and I don't see a good way to make it any different without ruining the looks.

Maybe I can make it part of the description that this was a makeshift weapon built by the pirates, using javelin pods and a heavy anti-missile base.

**Comment by EndrosG** [comment]
> Yes I see what you mean, but since weapons will only upscale in size, and not in in tech level for this ship, there is no reason to keep building bigger and bigger ships until more powerful tech levels are reached by humans. Those would just be murdered by much smaller and more powerful ships, size and number of lasers be damned.

Why? If weapons upscale in size, some people will ask for ships being big enough to hold half a dozen of them, i.e. for ships with bigger hardpoints.
These ships will come with a bigger hull then (which also results in higher shield values) with a higher mass, thus eventually requiring a larger engine space, and of course, we need a bit more outfit space to keep up with the energy demands.
This all can be done with the existing outfits, i.e. without any technological progress.

And why would those stronger ships be murdered by smaller ones? And even if so, why would this be a problem? As far as I know, It is a fundamental base statement of this games tier concept, that a light (or medium) warship of the next tier should roughly equal a heavy warship of the previous tier.
But if you create much stronger human (tier 1) heavy warships by upscaling weapon hardpoints (without changes in efficiency) - in combination with the other upscalings which may result in additional shield generators - these ships will eventually be able to beat tier 2 light warships and challenge tier 2 medium warships. This is, in times of danger, still a way to go. And it is a quick way while technological progress is usually slower.

**Comment by Pointedstick** [comment]
I love it! IMHO, this monster it should fire the Javelins in stream mode rather than burst.

**Comment by Elyssaen** [comment]
@EndrosG, I think you know I don't quite see things the same way as you on this. I think you're wrong to assume there are no barriers to making a larger ship. The lack of _gameplay_ barriers doesn't mean there aren't _in-universe_ barriers. 

1. Human T1 material technology might not be able to create a chassis larger than a Bactrian's that can withstand the stresses that appropriately-sized engines will put on it.
2. T1 human technology might not be able to create a stable shield stronger than around 21,400, no matter how much it scales things up. Or perhaps it can't create a stable shield that's _too large_.
3. Shield generators might not actually stack endlessly in a linear fashion – it could be just a gameplay approximation because realistic-sized ships exist in a regime where that's pretty much true.

There are good gameplay reasons for we don't see ships ten times bigger than Korath World-Ships, and gameplay reasons should be enough, but there could potentially be great _logical_ reasons too. It's why I'm really, really not sold on the idea of these super-gigantic ships.

**Comment by Amazinite** [comment]
There's also a question of efficiency. Larger weapons are usually less efficient than their smaller variants (in terms of DPS per ton, guns are better than turrets). Following that trend, a bigger turret would require more supporting structure and be even less efficient than its smaller version, which is already less efficient than the gun. So in the end, there's no point in making massive turrets or ships, as they are going to become increasingly more inefficient. Using a larger number of smaller ships and weapons is preferable to having to produce bigger and more inefficient ships and weapons.

**Comment by MessyMix** [comment]
If this does happen, though, and you make it fire in "burst" (technically it's only one weapon, but you get my point), it'll absolutely demolish any anti-missile defenses that the target might have... I doubt T3 pug antimissile can kill all of them quickly enough to stop them from reaching a ship. :D

**Comment by gchapyzh** [comment]
@MessyMix yep. This exactly is why I like the idea - something to apply damage to the aliens!

**Comment by gchapyzh** [comment]
I am having some trouble implementing the script for this - trying to figure out how to make a secondary turret, a turret that fires... missiles....

**Comment by Bladewood** [comment]
to note, "Quad Javelin Pod Turret" is too long for an outfit name.
```
outfit "Javelin Turret"
	category "Secondary Weapons"
	cost "TBD"
	thumbnail "outfit/javelin turret"
	"mass" "TBD"
	"outfit space" -"TBD"
	"weapon capacity" -"TBD"
	"turret mounts" -1
	"javelin capacity" 800
	weapon
		sprite "projectile/javelin"
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 1
		"velocity" 10
		"lifetime" 60
		"reload" 20
		"firing energy" .2
		"firing heat" 12
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2
	description "TBD"
```

**Comment by Pointedstick** [comment]
"Quad Javelin Turret"

**Comment by Bladewood** [comment]
compare to bombardment and thrasher turrets.

**Comment by gchapyzh** [comment]
...wait. Will this just... work?!

*violently testing*

**Comment by gchapyzh** [comment]
Ideas on how the 'hardpoint offset' works?

**Comment by Bladewood** [comment]
```
outfit "Quarg Skylance"
	thumbnail "outfit/skylance"
	weapon
		"hardpoint sprite" "hardpoint/skylance"
		"hardpoint offset" 9.
```

Controls how far from the turret mount the projectile is fired. Thus an offset of 9 would put the skylance beam 9 units(?) away from the turret mount.

**Comment by gchapyzh** [comment]
Corrected issue.

I can't seem to find the 'fire rate' variable anywhere?

**Comment by Bladewood** [comment]
`"reload"`
where rate of fire = 60/reload.

**Comment by gchapyzh** [comment]
![image](https://cloud.githubusercontent.com/assets/8764280/26331788/a60f9ecc-3f07-11e7-9b60-2864feb42f96.png)

![image](https://cloud.githubusercontent.com/assets/8764280/26331877/3b153c98-3f08-11e7-8c13-5d46019bcd30.png)


```
outfit "Javelin Turret"
	category "Secondary Weapons"
	cost 100000
	thumbnail "outfit/javelin turret"
	"mass" 20
	"outfit space" -50
	"weapon capacity" -50
	"turret mounts" -1
	"javelin capacity" 800
	weapon
		sprite "projectile/javelin"
		"hardpoint sprite" "hardpoint/javelin"
		"hardpoint offset" 8.
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 1
		"velocity" 10
		"lifetime" 60
		"reload" 5
		"firing energy" .2
		"firing heat" 12
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2
	description "A pirate original"	
```

Well, it works!

Things to consider: 
- It costs 120k credits for three complete reloads. 
- Three of these are _fatal_.
- Tree of these, maybe even four if I remove the anti-missile, fit on a mule, and _murder_ gunboats.

For some reason, the thumbnail in the outfitter does not show up, and I can't figure out what I'm doing wrong.

**Comment by Bladewood** [comment]
Did you make sure that the sprite file is actually titled "javelin turret.png"?

**Comment by gchapyzh** [comment]
![image](https://cloud.githubusercontent.com/assets/8764280/26332067/4f00512e-3f09-11e7-937a-be0e9b37e985.png)
**_DAMN THE BORDERS AND FIRE THE MISSILES_**

**Comment by tehhowch** [comment]
If it is a pirate outfit, it should have noticeably poorer heat/energy efficiency relative to the original outfit (see Blaster vs Modified Blaster)

OG Javelin has 
```
	weapon
		sprite "projectile/javelin"
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 1
		"velocity" 10
		"lifetime" 60
		"reload" 20
		"firing energy" .2
		"firing heat" 12
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2
```

Yours should probably have something like
```
	weapon
		sprite "projectile/javelin"
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 2
		"velocity" 10
		"lifetime" 60
		"reload" 5
		"firing energy" .3
		"firing heat" 20
		"shield damage" 48
		"hull damage" 26
		"hit force" 4
		"missile strength" 1
```
e.g. poorer aiming (giant bulky turret!), 50% more energy to fire, +66% more heat per shot, and 50% weaker strength, with slightly lower hitforce. Possibly also reduce the shield & hull damage per shot, based on the magnitude of the other changes you make.

**Comment by gchapyzh** [comment]
I don't see why the missiles would deal less damage and hit force - its still the same missiles. The energy and heat should go up, I agree, and the inaccuracy also makes sense, though I am afraid this may become an oversized shotgun of sorts.

**Comment by tehhowch** [comment]
As I said, those are just thoughts. Heat, Energy, and Inaccuracy are almost required to be worse for a pirate outfit, but the rest depend on your balance strategy. Perhaps this quad launcher fires its Javelins out 20% faster (vel=12 & life=50) because of lower armor content (strength 1).

**Comment by gchapyzh** [comment]
*nod nod* I like that. Any other ideas / suggestions?

**Comment by tehhowch** [comment]
Test it as the equipment on some pirate/marauder variants instead of heavy laser turrets, etc.
If these new pirates are able to decimate republic forces, it probably needs additional balancing.

**Comment by Bladewood** [comment]
I agree with the inaccuracy, but I'm not so sure about heat and energy.

**Comment by gchapyzh** [comment]
Its more difficult to cool, as well as turn a larger, more tight pack of tubes. I can see it happening to a certain degree.

**Comment by gchapyzh** [comment]
Back from a harsh week, and continuing to finish up what I started.

```
outfit "Javelin Turret"
	category "Secondary Weapons"
	cost 100000
	thumbnail "outfit/javelin turret"
	"mass" 20
	"outfit space" -50
	"weapon capacity" -50
	"turret mounts" -1
	"javelin capacity" 800
	weapon
		sprite "projectile/javelin"
		"hardpoint sprite" "hardpoint/javelin turret"
		"hardpoint offset" 8.
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 3
		"velocity" 10
		"lifetime" 60
		"reload" 5
		"firing energy" .3
		"firing heat" 14
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2
	description "Designed by a renegade Republic engineer, and now produced on all pirate worlds, this monstrosity is a set of four welded together Javelin Pods, installed, ironically, on a heavy anti-missile turret base. The turret lacks the accuracy of the pod, but dashes out a lot more damage per weapon point, and can fire in all directions. Due to its high reload cost and large size, this turret is often used by the richest of pirates, to attack the most guarded of convoys. Famous for it's ability to overwhelm even the strongest anti-missile systems."
```

The weapon is sold on all pirate worlds: Alcyone, Almach, Algenib, Glenah, Men, Graffias, Antares, Nuki.

Things I wish to accomplish now:
- Perfect the balance of this turret
- Create a type B, or the 'Hwacha' variant - one that fires off all 60 Javelins at once, and then reloads for a long time.
- Figure out if its appropriate to try and implement this into the full game at all.

**Comment by Elyssaen** [comment]
Great reference to Hwachas but... 60 at once? That... is... umm... I haven't looked into it at all, but how would the balance of such a weapon work out?

**Comment by gchapyzh** [comment]
If you look at the texture, you will see 60 missile tips ( 6 * 5 * 2 ). Thats why I said 6 at once.
To balance it, I would give it a longer net reload, worse accuracy, maybe even a slight difference in javelin travel speed ( if thats possible ). You would deal less net damage that way, but over a very short amount of time, overwhelming superior anti-missile systems. And it would be nothing but a waste of ammuntion against smaller ships.

**Comment by Amazinite** [comment]
.04 ammo mass * 800 capacity = 32, so the outfit space needs to be 32 more than the mass (yours is only 30 more).
4 mass * 4 pods = 16 mass for 4 pods
12 outfit space * 4 pods = 48 outfit space for 4 pods
This makes the turret base is only 4 tons, and at the same time it only takes up 2 outfit space.
So lets give the turret base some actual mass
(4 + 1 mass per pod) * 4 pods + 15 ton base = 35 mass
(12 + 1 mass per pod) * 4 pods + 15 ton base = 67 outfit space
The +1 mass per pod is because of all those supports and extra plating you've added to the sprite. With a 15 ton base, the numbers look good to me, but I actually think using a 20 ton base would be the best. That puts the numbers at 40 mass and 72 outfit space. Either seems balanced to me, though.

**Comment by gchapyzh** [comment]
I set it to 72 outfit space. A roary missile launcher would have insanely complext reloading systems, so it fits.
35 Mass accepted, I did not account for the anti-missile base when calculating both of those.
Thanks!

**Comment by Bladewood** [comment]
Dear god, you want to make another gatling gun...

I would suggest this instead for a description:
> Designed by a renegade Republic engineer and now produced on all pirate worlds, this monstrosity is a set of four Javelin Pods welded together and, ironically, installed on a heavy anti-missile turret base. The turret lacks the accuracy of the pod, but dishes out a lot more damage per weapon point, and can fire in all directions. Due to its high reload cost and large size, this turret is often used by only the richest of pirates to attack the most well-defended of convoys, and it is famous for it's ability to overwhelm even the strongest anti-missile systems.

Also, 72 outfit space is concerning; to me, one of the most interesting points of the Plasma Turret was that it was literally the largest turret in human space. If an even larger turret is produced earlier, that nullifies the effect.

**Comment by gchapyzh** [comment]
Gatling rocket shotgun?

Thanks for the edits, my lacking, second-language English is lacking sometimes.
The Plasma Turret is a 'modern' weapon, using fancy plasma weapon tech, not primitive rockets. On top of that, the Javeling Turret, as I am making it, will appear in the game AFTER the war, to go along with the weapons and ship built to explore alien civilizations. ( all still in the planning, so as of now, the Javelin Turret will exist just as a new, pirate, after-war weapon )

**Comment by Amazinite** [comment]
I'd limit this to a few pirate planets in certain regions and not just be all pirate planets.

**Comment by gchapyzh** [comment]
@Amazinite Syndicate pirates? Or the Free Worlds?

**Comment by Amazinite** [comment]
I'm thinking more the Far North pirates. This is a powerful weapon and the Far North pirates are the hardest to get to. They might not have any javelin pods sold nearby, so that could result in this being a little more expensive than expected (I'd expect this to normally cost 150,000, but you could make it something like 225,000 instead).

**Comment by EndrosG** [comment]
@Bladewood : it is larger than a plasma turret, yes, but it also uses ammo, while the plasma turret does not use ammo. So the plasma turret is still the largest primary weapon

**Comment by stinkray** [comment]
Don't turrets normally weigh (weight of unit * amount of units) + 10 for the base? I don't want to waste page listing followers and exceptions to this rule, but I feel like you can make this unit a fair bit heavier than it is now. 58 would be weight following this rule: barely less than the plasma turret.

**Comment by Amazinite** [comment]
>Don't turrets normally weigh (weight of unit * amount of units) + 10 for the base?

No. There are 15 turrets in the game that also have gun versions, and only 2 of them have bases that weigh 10 tons.

**Comment by tehhowch** [comment]
How's this coming? 
With pirate jobs in the main game, it would make sense if there was some equipment reward for tanking your government rep so much. This could be fantastic behind a pirate license (perhaps call it something else in mission text): without becoming pirate aligned, they would not sell it to you, so the normal player can only plunder the outfit from the rare large northern pirates variant that spawns it.

**Comment by gchapyzh** [comment]
![image](https://user-images.githubusercontent.com/8764280/28180995-b3eda256-680f-11e7-8126-a809bff7e53e.png)

```

outfit "Javelin Turret"
	category "Secondary Weapons"
	cost 100000
	thumbnail "outfit/javelin turret"
	"mass" 40
	"outfit space" -72
	"weapon capacity" -72
	"turret mounts" -1
	"javelin capacity" 800
	weapon
		sprite "projectile/javelin"
		"hardpoint sprite" "hardpoint/javelin"
		"hardpoint offset" 8.
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 1
		"velocity" 10
		"lifetime" 60
		"reload" 5
		"firing energy" .2
		"firing heat" 12
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2
	description "Designed by a renegade Republic engineer and now produced on all pirate worlds, this monstrosity is a set of four Javelin Pods welded together and, ironically, installed on a heavy anti-missile turret base. The turret lacks the accuracy of the pod, but dishes out a lot more damage per weapon point, and can fire in all directions. Due to its high reload cost and large size, this turret is used by only the richest of pirates to attack the most well-defended of convoys, and it is famous for it's ability to overwhelm even the strongest anti-missile systems. A true pirate masterpiece."	

```

This is it. Practically the entire thing, minus the 'sold' locations and any events that come with it. I am distracted by other things right now, so anyone interested in finishing this is welcome to do so. Basically all that needs doing is
- Adding locations where this is sold
- Setting when this weapon will become available in this game
- Adding any events related to this weapon
- Adding the weapon to the game

If anyone DOES decide to continue this for me, please keep us updated. If not, I will simply get to it when I have the time.

**Comment by endless-sky** [comment]
Turret sizes are typically (size of the gun form) * (number of guns) + (5 - 10 T to represent the turret hardware itself). Since a Javelin Pod is 12 T, a quad turret should probably be more like 55 T.

Also, it's a bit too obvious that the image is cobbled together from other outfit images rather than being a fresh render (especially because of the lack of shadows). And, the image is too large for a 1x image (which should be less than 180 pixels wide) but too small for a 2x image.

**Comment by gchapyzh** [comment]
@endless-sky Thanks for the feedback! 55 mass does sound better.

I lack the skill and the programs to properly render an outfit, so I had to work with existing textures to make do. Really not sure how to improve upon what I already have, beyond manually trying to add shadows and textures.

**Comment by tehhowch** [comment]
re: rendering, there are those on the Discord's `content-creating` channel that have crazy abilities. You may be able to recruit someone if you ask nicely :+1:

**Comment by jafdy** [comment]
I could do it if I wasn't doing lights already, someone will be able to do something good for it.

**Comment by gchapyzh** [comment]
Not sure where said channel is, but I really would appreciate the help. I want to see this happen!

**Comment by tehhowch** [comment]
https://discord.gg/UfaMn should get you in.

With art possibly resolved, all that remains is a unique mission string (or two, or zero).
If you only want pirate ships to have this outfit, and the player can only get it by plundering them, then you need to
1) Create a few ship variants with this. Take a peek at variants.txt and marauders.txt to see what needs to be done. I certainly think you'll want variants for the Falcon, and Leviathan, but it's possible that some workable builds can be made for smaller ships.
2) Create a mission which spawns normal pirates plus 1-2 of your new variants. A rare bounty hunting mission could work nicely.
Optional
3a) Add your variants to the relevant `fleets.txt` definitions (Large Northern Pirates, Large Southern Pirates) with an appropriately small weight (probably 1), either directly
3b) or indirectly, as a pirate response to the release of the FW Plasma Turret (events.txt)

If the player is to be able to purchase these turrets directly, then you should probably have a mission string of Pirate quests that require certain reputation levels or plot advancements or (your choice of thing). You would then create an event which adds the outfit to the desired Pirate outfitters (for help, look at the event that deals with the Plasma Turret), or have the outfit displayed all the time (edit sales.txt for the relevant Pirate outfitter), but locked behind the "Certified Privateer License" (or other good name), and your mission string gives that license (see FW missions or the wiki for assistance).

**Comment by tehhowch** [comment]
I remember seeing a really neat sprite for this on Discord a month or so ago.. how's the mission development coming along?

**Comment by gchapyzh** [comment]
Its on pause due to outside reasons. Heres the **_amazing_** sprite tho: 
![javelin_turret_vertical](https://user-images.githubusercontent.com/8764280/33466801-1e944b88-d605-11e7-9457-119541f0b789.png)

**Comment by Pointedstick** [comment]
I MUST HAVE THIS

**Comment by Amazinite** [comment]
Thicc base. Would use.

**Comment by gchapyzh** [comment]
If anyone wants to snatch this and finish the balancing on this, feel free to. The data is a few posts above, just needs to be heavier and something something balanced. If not, I will get to it in the upcoming weeks.

**Comment by Amazinite** [comment]
If you make it a weapon exclusive to Marauder ships (at least currently), like mentioned in #3319, then a story wouldn't be necessary to implement it into the game. :)
A story could always be added later for the purpose of being able to buy it.

**Comment by Amazinite** [comment]
>If anyone wants to snatch this and finish the balancing on this, feel free to. 
```
outfit "Quad Javelin Turret"
	category "Secondary Weapons"
	cost 110000
	thumbnail "outfit/javelin turret"
	"mass" 26
	"outfit space" -58
	"weapon capacity" -58
	"turret mounts" -1
	"javelin capacity" 800
	weapon
		sprite "projectile/javelin"
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 1
		"velocity" 10
		"lifetime" 60
		"reload" 5
		"firing energy" .2
		"firing heat" 12
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2
```
?

**Comment by Pointedstick** [comment]
I'll finish the sprite.

**Comment by gchapyzh** [comment]
Thats the one, at least for the 'rapid fire' version. I have not figured out how to have this thing fire in volleys. If you DO figure it out, I am thinking 4 volleys 15 each, just so its not 60 missiles going out at once. Make sure to keep the accuracy way down for spread reasons.

**Comment by tehhowch** [comment]
@Kryes-Omega did the sprite afaik

**Comment by gchapyzh** [comment]
![javelin turret vertical_tex_res 2x](https://user-images.githubusercontent.com/8764280/33467075-dd9d256c-d606-11e7-85fe-b5c2e056c145.png)
![javelin turret vertical_tex_res](https://user-images.githubusercontent.com/8764280/33467076-ddb3fae4-d606-11e7-8bdc-da7e6a7e136e.png)
![javelin turret vertical top-down_tex_res 2x](https://user-images.githubusercontent.com/8764280/33467077-ddca23e6-d606-11e7-9ff7-8176d04dfeef.png)
![javelin turret gullwing top-down_tex_res](https://user-images.githubusercontent.com/8764280/33467078-dde06a3e-d606-11e7-8047-6a7face83c80.png)
![javelin turret gullwing top-down_tex_res 2x](https://user-images.githubusercontent.com/8764280/33467079-ddf67554-d606-11e7-916b-73b6337c6eaf.png)
![javelin turret gullwing_tex_res](https://user-images.githubusercontent.com/8764280/33467080-de16534c-d606-11e7-9276-89d9e40a96e2.png)
![javelin turret gullwing_tex_res 2x](https://user-images.githubusercontent.com/8764280/33467081-de32c2a2-d606-11e7-82e2-d6b011a71792.png)
![javelin turret vertical top-down_tex_res](https://user-images.githubusercontent.com/8764280/33467082-de475168-d606-11e7-82f3-7197aaaa372f.png)

**Comment by gchapyzh** [comment]
Full credit to @Kryes-Omega . This stuff is amazing

**Comment by Pointedstick** [comment]
Well there ya have it. Those look ready to go.

**Comment by Amazinite** [comment]
> I have not figured out how to have this thing fire in volleys. If you DO figure it out, I am thinking 4 volleys 15 each, 

Something like this?
```
outfit "Quad Javelin Turret"
	category "Secondary Weapons"
	cost 110000
	thumbnail "outfit/javelin turret"
	"mass" 26
	"outfit space" -58
	"weapon capacity" -58
	"turret mounts" -1
	"javelin capacity" 800
	weapon
		sprite "projectile/javelin"
		sound "javelin"
		ammo "Javelin"
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"submunition" "javelin volley" 15
		"inaccuracy" 1
		"velocity" 10
		"lifetime" 1
		"reload" 75
		"burst reload" 10
		"burst count" 4
		"firing energy" .2
		"firing heat" 12

outfit "javelin volley"
	weapon
		sprite "projectile/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 8
		"lifetime" 59
		"shield damage" 48
		"hull damage" 26
		"hit force" 5
		"missile strength" 2

```

This would fire 4 volleys of 15 missiles each within the span of half a second, then take 5 minutes to fully reload (75 seconds per volley)

**Comment by Amazinite** [comment]
Here's a quick plugin with the two versions of the javelin turret.
[javelin turret.zip](https://github.com/endless-sky/endless-sky/files/1524446/javelin.turret.zip)
You'll need to change what outfitter they're offered on if you aren't using World Forge.

**Comment by Lineth** [comment]
Maybe a combo of marauder-only and mission unlock. Make so that is is purchasable from advanced pirate outfitters after a mission or something, or if you aren't comfortable helping pirates, it would be used on some marauder variants if you'd prefer are more _kinetic_ way of acquiring the weapon.

**Comment by tehhowch** [comment]
My suggestions are here: https://github.com/endless-sky/endless-sky/issues/2535#issuecomment-315393319

**Comment by geojak** [comment]
[variants.txt](https://github.com/endless-sky/endless-sky/files/1635965/variants.txt)

made some varaints of the firebird, mule, bactrian and leviathan

**Comment by Tadrix** [comment]
> This would fire 4 (highly inaccurate) volleys of 15 missiles each within the span of half a second, then take 5 seconds to fully reload (75 frames per volley). If you want the time between volleys to change then we'd increase the burst reload value.

How about making it a Double Javelin Turret instead of Quad and firing 3 volleys of 2 missiles (6 total) and then reload, in total around 2 times faster than a single Javelin Pod would do it, and edit outfit space and mass accordingly? The current version seems to be a little over the top.

**Comment by tehhowch** [comment]
I am fine with the current firing solution - this is top-of-the-line Pirate content, it being absurd seems ok.

**Comment by Tadrix** [comment]
Except pirates using this would obliterate their mark long before they got to plunder it. This could work, however, if they would use their missiles frugally (as a last resort).

But if they do this, wouldn't it be more practical to just use those 60 t of weapon space to install something more suitable for plundering, for example, heavy laser turrets?

It's so outrageous it's fun, so I won't continue this.
Just one more thing: rename it to "[Macross Missile Massacre](http://tvtropes.org/pmwiki/pmwiki.php/Main/MacrossMissileMassacre)", or "MMM Javelin Missile Turret", or, if this is 100% pirate outfit, "Javelin Massacre Turret", or something along these lines, will you? :)

**Comment by Pointedstick** [comment]
+1,000 for "Javelin Massacre Turret"

**Comment by WildLynxDev** [comment]
Ain't Ammo clause makes turret to behave like secondary weapon, and never fire automatically?
I was trying to create Gatling turret and run into two issues:
1. Ammo selector becomes active.
2. Turrets never fire on their own, only when Secondary Weapon Key is pressed.

**Comment by KiLEdEnNis** [comment]
all secondary weapons can only be fired through the special firing key, since their ammo is limited
as for your `I wish that #3`, that's quite irrelevant to this issue, similar things have been brought up before
I don't remember if ammo-based AM was functional in the current source build, but it'd be nice to see some aliens use something like that

before you create a separate issue, search if there are similar issues (both open and closed), and if there are, look if the idea was no'd, or if it's still "maybe"
if the issue is open, you can usually just put your ideas in there

**Comment by tehhowch** [comment]
Sprite is done, story is not. Attributes should probably be reworked based on the current javelin data. My vote is it goes in as an outfit on a single rare pirate variant (i.e. some "Mk 2" level Leviathan) or even a Pirate person-ship.

a mission for pirate/independent affiliated players can be included later, to enable this outfit's purchase on some core pirate stronghold.

**Comment by Amazinite** [comment]
I have this on a list of outfits to make unique to Marauder ships, but I haven’t gotten around to all that quite yet.

**Comment by Pointedstick** [comment]
I can't wait until there are unique Marauder-only outfits.

**Comment by unjown** [comment]
maybe we can add this to an campaign in  FW, maybe in the part where you have to choose between cloak or nuke

**Comment by gchapyzh** [comment]
> maybe we can add this to an campaign in  FW, maybe in the part where you have to choose between cloak or nuke

"Quick, we only have time to arm you with one of these three tools! We have the perfect stealth system at the oldest living aliens in the galaxy can't penetrate, the ultimate anti-ship weapon capable of destroying fleets in one blow, or the hawacha."

"T- the hawacha?"

*Gasp* "You deranged monster..."

I'll have to consult @beccabunny on discord tomorrow, see if a modern model  and texture can be made into existence with the help of golden hands.

**Comment by Pointedstick** [comment]
Is there anything blocking this?

**Comment by Amazinite** [comment]
You can now fine Javelin turrets on select pirate worlds. \:)
