### ISSUE TITLE
Plugin script requires tabs, spaces do not work

### ISSUE THREAD

**Issue by Ranakastrasz** [endless-sky/endless-sky#2536]
> outfit "Engine Conversion"
>      category "Systems"
>      cost 25000
>      thumbnail "outfit/blue screwdriver"
>      "outfit space" -1
>      "weapon capacity" -5
>      "engine capacity" 5
>      "shields" -25 
>      "hull" -25
>      "unplunderable" 1
>      description "Modern ships are highly customizable, but the hull itself isn't nearly as flexable. It is possible to modify it, allowing additional weapon or engine capacity, but this results in a disruption to the shield grid and hull integrity. This is however, ill-advised"

Using notepad++, I automatically have tabs replaced with spaces. However, the parser does not allow this, as if I have spaces in-front of an entry, it is ignored.

**Comment by tehhowch** [comment]
Yes, this project uses tabs, not spaces. Configure notepad++ to not automatically replace tabs with spaces and then your issue is solved

**Comment by endless-sky** [comment]
Technically speaking, you can use spaces for indentation, but what you can't do is mix spaces and tabs in the same file. And, the parser can also get confused if you aren't consistent in how many spaces you use for indentation. So, the recommended approach is to just only use tabs.
