### ISSUE TITLE
enhancement: allow orders from ship info window

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#2539]
I think controlling a large fleet would be more user friendly if assigning control groups and giving orders could be done through the ship info window, rather than having to cycle through or find the desired ship in space.  This would also be helped by the ability to select multiple ships in the info window while in space, like you can while parked (I'll open a separate issue for that if you prefer).

**Comment by endless-sky** [comment]
Most of the fleet command stuff is still very much in the experimental phase. As an Escape Velocity clone, the game's missions and gameplay are geared toward a single ship or a ship with a handful of escorts, not toward massive fleets.

**Comment by endless-sky** [comment]
Control groups can (as of 0.9.8) be assigned in the fleet list.
