### ISSUE TITLE
Use different shapes for different objects in the radar view

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#254]
Because everything is a circle, the radar view is a bit visually muddy. Using different shapes to indicate different objects would help a lot. Example: planets and space stations would remain circles, ships would be acute isosceles triangles with the pointiest angle indicating facing, and missiles would be lines. With this, hostile missiles could be orange or red lines and friendly missiles could be blue lines.

**Comment by endless-sky** [comment]
Here's a quick mock-up of what that would look like (drawing ships using the same shape used for targeting pointers). I'm not sure if I like it or if the shapes make it seem too irregular.

![radar](https://cloud.githubusercontent.com/assets/11450262/11411008/1bdeb054-939a-11e5-9a26-a144aa52aa35.png)

**Comment by Pointedstick** [comment]
The triangles would look better of they were solid, rather than tapering off with a gradient on the rear, I think. They'd look sharper and contract more with the background. Ultimately, that's what I think is needed for the radar: more contrast so you can tell things apart at a glance.

**Comment by Tufton** [comment]
I like that mockup but I agree with Pointed re: the contrast.  Having various icon shapes, colors, etc would make the minimap much more useful in combat (especially being able to differentiate fighters, drones, missiles, projectiles, etc.).

**Comment by gchapyzh** [comment]
Make the map bigger?

**Comment by wkoot** [comment]
Radar blips wouldn't usually show direction, unless the objects are scanned in several iterations. And then you would still assume that it's a ship and not an asteroid.
Why not only show triangles for friendly ships; i.e. auto-comms for radar system. Or make it available as an outfitter.

**Comment by endless-sky** [comment]
I've experimented with different ways of doing this, but having the ships be anything but round dots makes the radar display much harder to read, in my opinion, especially when ships are overlapping. I'm open to suggestions, though.

**Comment by wkoot** [comment]
Perhaps it only works when zooming the radar view, i.e. when there isn't a lot of clutter?
