### ISSUE TITLE
Debian 0.9.6 package

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#2542]
Will 0.9.6 be uploaded to Debian?  [The release announcement](https://github.com/endless-sky/endless-sky/releases/tag/v0.9.6) links to https://mentors.debian.net/package/endless-sky, but that page doesn't have 0.9.6 packages.

**Comment by endless-sky** [comment]
The Mentors upload tends to be rather flaky - it kept timing out when I was doing the release, so I gave up on it. I just succeeded in uploading the files now, though.

**Comment by jostephd** [comment]
Thanks!
