### ISSUE TITLE
Joining the Free Worlds should fail FW Bounty missions

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2544]
https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20intro.txt#L1579
> As you walk through the spaceport, a woman in a militia uniform approaches you. "Are you Captain `<last>`?" she asks. You nod. "I'm the commander of the local militia," she says. "There's a pirate fleet that has attacked freighters in this sector several times in the last few months, but now it seems they've moved outside of Free space. I'd like to strike at them before they return and do more damage here, but right now the Free Worlds Council won't allow militia ships to be used for preemptive attacks."

And then we join the Free Worlds.

[Alpha Cygni.txt](https://github.com/endless-sky/endless-sky/files/1020557/Alpha.Cygni.txt)
Mission is still present.

**Comment by endless-sky** [comment]
I'm not convinced that that's a problem: she says that *militia* ships aren't allowed to be used for this mission. That's because they want to conserve ships for fighting the Republic, not because they don't want anyone affiliated with the Free Worlds fighting pirates.

**Comment by Bladewood** [comment]
Huh. I was under the impression that "militia" was being used as a synonym of "Free Worlds".
