### ISSUE TITLE
Missile Factory outfit that can manufacture missiles if you have certain commodities

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#255]
In order to make spamming missiles more attractive and cost-effective for the player (and more effective for NPC ships), I propose a "Missile Factory" outfit that can produce missiles for the ship it's installed on if that ship's cargo hold has metal and electronics in it. The cost per missile should be lower than buying the missiles if you buy these materials at low prices. It should probably require some energy to operate, and maybe a small amount of hyperspace fuel too (for the explosive!).

**Comment by Tufton** [comment]
I don't know about requiring materials in your cargo hold, but I like the idea of a missile generator that uses an appropriate amount of energy/heat/fuel to make it balanced.  Having to land and reload is certainly a viable balancing aspect but personally that keeps me away from missile weapons in most games I play.

**Comment by Pointedstick** [comment]
Yeah, me too. Especially when there are really good guns available (particle cannon, plasma turret, etc) and the missiles favor quantity over quality. If I need to hit with hundreds of projectiles to take down an enemy, I want to be able to shoot those projectiles for free!
