### ISSUE TITLE
Pronouns in ship names

### ISSUE THREAD

**Issue by strollcata** [endless-sky/endless-sky#2553]
Several Discord users, including myself, have been discussing how to solve issues where mission dialogue refers to your flagship as 'your The Ship Name'. As of writing this, a solution was proposed by Yrol Denjeah a few minutes ago, namely removing the pronouns in front of ship names throughout mission dialogue.

Using Elyssaen's example from Discord, the current system means that a ship with an adjective name is always grammatically odd-looking: a ship named 'Invincible' or 'The Invincible' would be written as 'your Invincible' or 'your The Invincible' respectively, which look quite odd.

With Yrol's suggestion, a ship named 'Invincible' or 'The Invincible' would simply be read as they are: for example, 'is Invincible repaired?' and 'is The Invincible repaired?'. Though it's a fairly minor change, I think it could help out a lot with readability.

**Comment by Elyssaen** [comment]
Hey, I'm not quite sure what the Discord conversation actually concluded. "simply be read as they are" would seem to suggest doing nothing, or do I misunderstand?

The one option I don't think can work reliably is any code that tries to remove a preceding "your" bit. A substitution could be made, but it will choke on text like `your precious <ship>`, `your mighty <ship>`, etc. And it will have to get increasingly more complicated to then know not to do anything to `your ship, <ship>`.

**Comment by strollcata** [comment]
@Elyssaen As far as I know, no code changes should be necessary. Rather, the ship names can be left alone if the pronouns are removed from dialogue.

**Comment by Amazinite** [comment]
> As far as I know, no code changes should be necessary.

So are you talking about pronouns that the player has put into the ship name themself or pronouns that preceed `<ship>` in conversations? If it's the former than this will need code changes because the game needs to be able to recognize pronouns and remove them from the ship name. If it's the latter then the bigger problem is when the ship name already has a pronoun in it, because you coud end up with `your ship, the The Invincible.`

**Comment by strollcata** [comment]
@Amazinite I'm talking about removing pronouns preceding the ship name entirely from the written dialogue. That way, your ship is referred to as '<Ship Name>', and situations where the player's ship is called 'the <The Ship Name>' or 'your <The Ship Name>' won't come up. If I remember correctly, there is no dialogue in the base game where the player's ship is spoken of as 'your <adjective> <Ship Name>', so concerns like Elyssaen's won't come up either.

**Comment by Elyssaen** [comment]
> You find Tomek walking among the fleet, conversing with captains and assessing the damage they have suffered. When he sees you he says, "Captain <last>! How is your `<ship>` holding together?"

> - "She took a bit of a pounding, but I've patched her up."
> - "Just fine. It'd take more than a few cruisers to destroy the `<ship>`."

From Liberate Kornephoros. So your suggestion is that it's safer to rewrite this as "How is `<ship>` holding together?" and "It'd take more than a few cruisers to destroy `<ship>`"?

**Comment by strollcata** [comment]
Exactly. This means that no code changes are required. Someone has to go through all the vanilla mission text, but I'm more than willing to do that if this is thought to be a good idea.

**Comment by Elyssaen** [comment]
Got it. I'm on the fence, I think. I really like `your <ship>` the `the <ship>`, at least... when they work. Your suggestion is 'safer' but I can't bring myself to love it. At least, I haven't yet.

The task wouldn't be too bad, by the way. It only occurs five times in the game, over these four files:

1. free worlds intro.txt, line 27.
2. free worlds middle.txt, line 1494.
3. free worlds start.txt, lines 25 and 28.
4. intro.txt, line 363.

That's every use of `<ship>` outside of flight check. Every one uses either a 'the' or 'your' prefix: the flight check text (conversations.txt) doesn't use a prefix.

**Comment by endless-sky** [comment]
It seems like this completely depends on whether the player chooses to put "The," etc. in the ship name, which isn't something the game can control. (That is, if this change were made, it would make the text sound awkward for players who follow the example of the in-game ships and *don't* include a "The.")
