### ISSUE TITLE
Collect-and-return mission consumes cargo capacity

### ISSUE THREAD

**Issue by TeamX76** [endless-sky/endless-sky#2554]
This may be a bug, because it seems it would not be intended by game logic.
Took a mission from Pollux to collect 22 tons of furniture for a gathering from Alheka and return it to Pollux, my cargohold showed 22 items in my hold after taking the mission until I returned to Pollux to drop off.

This doesnt seem right. As it would make sense to be able to make use of your hold on-route to the pickup destination, instead it just seems like the Captain ear-marked that space.

**Comment by Bladewood** [comment]
It's implied that that is just "reserved" space, similar to the space on the Pookie mission.

If it's not labeled as such, though, there is a problem.

**Comment by tehhowch** [comment]
See #2404

**Comment by VonZorch** [comment]
It's not really a problem, you're being paid for the cargo space being reserved  on the out leg of the trip.
For instance if the pickup point is 3 jumps away you get paid for 6 jumps.
