### ISSUE TITLE
Additional hit effects for when a ship is hit while its shields are up and when its shields are down.

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#256]
It would be a cool visual for a ship that is struck while its shields are up to briefly display a shield effect. EVN-style "shield bubbles"  would look out of place in this universe given the lore that shields are custom-tailored to the shape of a ship's hull, so perhaps instead, the effect could be a colored translucent overlay in the shape of the ship.

By the same token, when a ship is struck while its shields are down, doing hull damage, little gray and orange debris particles could shoot out of the hit site to show that parts of the hull are being blasted away, like in the old-skool Ambrosia game Ares, if you've played it. Gaitori weapons would do this, and little particles would fly out when their shots connected. It looked really cool.

**Comment by Pointedstick** [comment]
Nah, I think the current hit effects are probably fine.

**Comment by Pointedstick** [comment]
Actually, I changed my mind. I think this would be nice.

**Comment by Amazinite** [comment]
A week shy of 2 years.

**Comment by AdamKauffman** [comment]
@Pointedstick This seems to clash with the "Show status overlays" Setting. When I imagined this effect I thought it would be like a circle around the ship, which the status overlay is. What if the hit effect was to flash the status overlay of the ship being hit? That would look like a shield and also provide information about the hit. Might be easier to implement as well.

**Comment by Pointedstick** [comment]
The point of this is to look cool, to visualize the shields. The status overlay is something different; it's purely informational. I can see how they'd clash. The crudest solution would be to disable shield bubble display while overlaps are on, which is okay because they're off by default. The more elegant solution would be re-draw the status overlays so that they don't interfere with the shield bubble display, which could yield the secondary benefit that they wouldn't obscure the ships themselves anymore.

**Comment by Zitchas** [comment]
I like the sounds of that. Either way would be good, although having the status stuff a little farther out would probably be good.

**Comment by Amazinite** [comment]
Something that's been discussed a fair bit in the Discord as of late is also the ability to have "bubble shields," i.e. shields that are projected around the ship instead of being right up against the hull as they're explained as being now. It's a different issue, but I'd say it could tie into this idea of a "shield hit effect" for ships, also having a "shield effect" that appears when the shields are active, be that a light glow around the outline of the ship, or a bubble that appears around it.

**Comment by Amazinite** [comment]
This is basically duplicated by #2568. Although that issue is newer, it also has more discussion on it. In such cases for old duplicate issues, we've kept the issue open with more discussion, so I'll be closing this one.
