### ISSUE TITLE
OpenGl Version

### ISSUE THREAD

**Issue by Meresmata** [endless-sky/endless-sky#2562]
Hi,

  when I start endless sky (downloaded or compiled) on my laptop, I get the error message:

> Unable to create OpenGL context! Check if your system supports OpenGL 3.0. (SDL message: "Could not create GL context: GLXBadFBConfig")

I think the reason should be that the laptop is much to old. Therefore I'd like to ask to if it is get a version of the game working with older devices.

Thanks a lot!

**Comment by MCOfficer** [comment]
can you point us to your graphic driver version? as usual, check if there are newer version available. also look for proprietary drivers.

**Comment by Meresmata** [comment]
Hi,

 i just run 

> glxinfo | grep "OpenGL version"


it gave the result of:

> OpenGL version string: 1.4 Mesa 12.0.6

That did not left wondering because I am using a nearly decade old system using 

> Intel(R) Atom(TM) CPU N270   @ 1.60GHz

But that should be good enough for a 2D game, right?

**Comment by MCOfficer** [comment]
>      But that should be good enough for a 2D game, right?

as stated in your error, ES needs at least OpenGL 3.0. a 2D game could probably be done for version 1.4 aswell, opengl 1.4 is old. like, very, very old, almost obsolete. 


i was asking specifically for your graphic drivers, though. 
`cat /var/log/Xorg.0.log | grep -A 5 'LoadModule: "glx"'`
should give you what you need. for example, my output for this command is 
'[    31.135] (II) LoadModule: "glx"
[    31.136] (II) Loading /usr/lib/x86_64-linux-gnu/xorg/extra-modules/libglx.so
[    31.190] (II) Module glx: vendor="NVIDIA Corporation"
[    31.190]    compiled for 4.0.2, module version = 1.0.0
[    31.190]    Module class: X.Org Server Extension
[    31.190] (II) NVIDIA GLX Module  375.39  Tue Jan 31 19:37:12 PST 2017'

also, knowing your graphic device (integrated chipset? graphics card?) could be helpful.

**Comment by Amazinite** [comment]
@endless-sky has stated that the reason for using OpenGL 3.0 is to make sure that everything works across all supported platforms.

**Comment by Meresmata** [comment]
Hi, 

 thanks for answering as far as Is know onboard graphics is used. The output you asked for is:

> [    75.797] (II) LoadModule: "glx"
[    76.022] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    78.254] (II) Module glx: vendor="X.Org Foundation"
[    78.254] 	compiled for 1.18.4, module version = 1.0.0
[    78.254] 	ABI class: X.Org Server Extension, version 9.0
[    78.255] (==) AIGLX enabled

Well the system is quite old but not so old that no 2D games can't be played, as Wesnoth run very smooth. ;)

**Comment by tehhowch** [comment]
Perhaps, but this 2d game requires opengl 3.0 support

**Comment by MCOfficer** [comment]
i assume you are using built-in graphics. if this is not the case (and you have an actual graphics card), try to get a decent proprietary driver for it, which may give you the ability to run OpenGL 3 games. for instance, with a nvidia card i would either get the  'nvidida-<version>' (in my case 'nvidia-375') package from the repo or directly download the latest version from nvidia.com .

however, if this is already the best driver you can get for that hardware, we can't help you any farther - sorry, but playing ES is impossible like this.

**Comment by endless-sky** [comment]
The game makes use of OpenGL shaders and other extensions that aren't available until OpenGL 3. So, even if it could be ported to an earlier OpenGL version there would be a lot of issues, and that just wouldn't be worth it for the very small, and shrinking, number of people who still have such old systems.

**Comment by Meresmata** [comment]
Very unfortunately.

**Comment by asl97** [comment]
@Meresmata I am assuming you are using linux, in which case, you can try mesa software renderer:
```
MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 ./endless-sky
```

If that doesn't work properly, it probably means your gpu ain't playing nicely with the software render, in which case you can try using only software rendering, although it will probably lag too much:
```
LIBGL_ALWAYS_SOFTWARE=1 MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 ./endless-sky
```

You can read more about different environment variables on https://mesa3d.org/envvars.html

**Comment by MCOfficer** [comment]
[SolraBizna](https://www.reddit.com/user/SolraBizna) made a patch for OpenGL 2.1 and is currently looking for testers, this may work for 1.9 aswell.
https://redd.it/6umft1

**Comment by Meresmata** [comment]
@asl97 Thank you very much.

Your first Tips, helped to open the program, but characters weren't shown. So I tried the second tip. That worked as discribed. It worked, but was i bit to slow... ( felt like factor 2 to 3). 

@MCOfficer just downloaded endless-sky from Solra-Birna's repro and compiled... Ended with the same error message as the normal version.

**Comment by gunqqer** [comment]
Quick question: what OS are you using. The OS X binary is working for OpenGL 2.1 from solra-birna is working (It just be slightly slower to update as I am compiling it on XCode for him because he doesn't have a Mac anymore.)

**Comment by asl97** [comment]
@gunqqer His system support OpenGL 1.4 which is really old, older than OpenGL 2.1. So it isn't unexpected that it didn't work.

Although, afaik, there isn't a GPU that only supports OpenGL 1.4 on linux,  even the second generation GPU supports OpenGL 2.1 while the first generation supports OpenGL 1.1.

**Comment by luskynavy** [comment]
@SolraBizna, I have done the same work the last 2 days, making it work for an old notebook with open gl 2.1
So I also changed the shaders (in->attributes, out->varying and texture->texture2D).
But should the "glBindVertexArray(vao);" be changed too ? It's  open gl 3.0.
I replaced it for the bind with an for each shader, by example for OutlineShader::Draw:

	//glBindVertexArray(vao);
	glPushClientAttrib(GL_CLIENT_VERTEX_ARRAY_BIT);
	glBindBuffer(GL_ARRAY_BUFFER, vbo);

	glEnableVertexAttribArray(shader.Attrib("vert"));
	glVertexAttribPointer(shader.Attrib("vert"), 2, GL_FLOAT, 
		GL_FALSE, 4 * sizeof(GLfloat), nullptr);

	glEnableVertexAttribArray(shader.Attrib("vertTexCoord"));
	glVertexAttribPointer(shader.Attrib("vertTexCoord"), 2, GL_FLOAT, GL_TRUE,
		4 * sizeof(GLfloat), (const GLvoid*)(2 * sizeof(GLfloat)));
  

and for the unbind: 

	//glBindVertexArray(0);
	glPopClientAttrib();


glUniform1ui is 3.0 too, it become glUniform1i:

	//glUniform1ui(shader.Uniform("tex"), 0);
	glUniform1i(shader.Uniform("tex"), 0);

Fragment shader of OutlineShader has to be redone a little, using off.y causes weird result, so off.x is used instead (maybe problem with negative texcoords) like that:

	//"      float asw = texture(tex, d + vec2(tc.x + off.x, tc.y + off.y)).a;\n"
	"      float asw = texture2D(tex, d + vec2(tc.x + off.x, tc.y + off.x)).a;\n"

Results are pretty good, it goes from 10 fps with mesa3d in soft to topped 60 fps with my version.
Can't say if there is a drop in framerate compared to glBindVertexArray, it's maxed to 60 fps even with SDL_GL_SetSwapInterval(0).

Tested on a p8400 with gma45 and virtualbox vm for open gl 2.1.
And also i7 with  Intel® HD Graphics 4600 for open gl > 2.1.

**Comment by Meresmata** [comment]
@asl97 

Hi I checked the graphics cards... Its a Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphics Controller by Intel.

**Comment by asl97** [comment]
@Meresmata Well, I did some more research and it seem they decided to drop OpenGL 2 on gen 2 and gen 3.

https://www.phoronix.com/scan.php?page=news_item&px=Mesa-i915-OpenGL-2-Drop

@luskynavy By 'mesa3d in soft', did you mean 'LIBGL_ALWAYS_SOFTWARE=1'?

Full software rendering will always be slow, it is expected.

If I ain't wrong, my first suggestion to get endless sky running uses the gpu for the supported features and fallback to soft rendering when it doesn't, the performance should be similar if endless sky doesn't try to use unsupported features.

**Comment by luskynavy** [comment]
@Meresmata yes I have used mesa3d for windows, this version, full software https://fdossena.com/?p=mesa/index.frag. That was the easy way to make it work but slow.

It's full gpu when recompiled for open gl 2.1 and run great with no visual difference.

**Comment by SolraBizna** [comment]
Sorry for the slow response. Millions of people descending on Idaho to see the eclipse killed my Internet. (It didn't help that I was one of them... >_>)

If you compiled my repo, make sure you compiled from the `gl21` branch. If you're on Mesa on Linux, you should have been able to play with that. The main GL3 features Endless Sky uses were ubiquitous extensions pre-3, and Mesa tends to expose the core entry points for promoted extensions even when "presenting" an older OpenGL version.

**Comment by Meresmata** [comment]
Hi,

 I tried the same with the gl21 branch with the same negative result...

**Comment by luskynavy** [comment]
I made my fork too for open gl 2.1.
Certified to work....on my machines.
Prebuilt win32 releases for 0.9.6 and 0.9.8 are available here : https://github.com/luskynavy/endless-sky/releases.
Modified code is in this branch https://github.com/luskynavy/endless-sky/tree/opengl2.1.
