### ISSUE TITLE
Too many pirates?

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#2564]
I don't know if this is me but lately, I've been encountering *way* too many pirates in Human systems (like Republic/Free Worlds). 98% of systems that I jump to have at least 5 pirates, even if the systems are supposed to be heavily protected by the Navy and should keep them out. Also, the Navy isn't there as much as it used to, which is a weird coincidence. I only see 1 or 2 Navy ships per system.

Did someone else notice this too? I'm on the latest commit and at the beginning of the Free Worlds campaign.

**Comment by Elyssaen** [comment]
If you're encountering more pirates than you're used to, are you flying a fleet with more freighters than before? You might be attracting them.

**Comment by Rakete1111** [comment]
@Elyssaen Yes, actually I have. But can this really result in that much pirates appearing? I find it a bit excessive :)

**Comment by EndrosG** [comment]
Yes, you attract the pirates. It can get even worse, trust me. ;-)

**Comment by endless-sky** [comment]
In 0.9.7, how many pirates your fleet attracts will depend on how much cargo space you have vs. how much damage your ships can do, but for now it's just dependent on how many freighters are in your fleet. It's intended as a way of keeping exponential Star Barges from being the easiest way to earn money.

**Comment by Capri205** [comment]
The game is seriously fucked up if you want to just be a trader. So many pirates. Takes 10 attempts to jump a few systems to trade.
