### ISSUE TITLE
bug with AI::FindTarget (AI does not target disabled ships properly)

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2565]
@Elyssaen noted on Discord, that the AI did not attack some disabled ships even if the supposed attacker has `personality heroic vindictive`.
I created a testfile to reproduce it, using a slightly different setup than @Elyssaen.
[Testing Tester.txt](https://github.com/endless-sky/endless-sky/files/1033823/Testing.Tester.txt)

I could trace the problem down to
```
// Pick a new target for the given ship.
shared_ptr<Ship> AI::FindTarget(const Ship &ship) const
{
	[...]
			// If your personality it to disable ships rather than destroy them,
			// never target disabled ships.
			if(it->IsDisabled() && !person.Plunders()
					&& (person.Disables() || (!person.IsNemesis() && it != oldTarget)))
				continue;
```
Disabling that if() condition by adding ` && 1 == 2` helped in the testcase but obviously is not a general solution.

1. The (pirate) ship in question is disabled
2. The supposed (republic) attacker is not set to plunder
3. The supposed (republic) attacker is not set to disable nor is set nemesis
and
4. The (pirate) ship in question has not been the target of the supposed (republic) attacker before
i.e. we have an
```
if (true && true && (false || (true && true))
	continue;
```
situation here. My guess is that the last part regarding the nemesis personality is "wrong".

**Comment by EndrosG** [comment]
Additional comment on how this situation might happen in normal circumstances:

RNS Alpha targets Pirate One
RNS Bravo targets Pirate Two
Pirate One and Pirate Two both target RNS Alpha

RNS Alpha disables Pirate One
Pirate Two disables RNS Alpha
Pirate Two destroys RNS Alpha
RNS Bravo disables & destroys Pirate Two
RNS Bravo will not target Pirate One (because Pirate One is disabled && is not the oldTarget && RNS Bravo does not plunder or disable only)

P.S. I wont create a PR on that after my recent merge success rate of the last 4 weeks.

**Comment by Elyssaen** [comment]
I think we have a different outlook here. I did note it, but I didn't think it was a bug.

Vindictive is an unusual (and rarely used) personality, and I used to think it caused an AI to seek out and destroy disabled ships. It doesn't: it just has them [continue firing after the target is dead](https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities). Heroic means a ship has no range limit when seeking a fight.

No personality seems to actively seek out and destroy disabled ships. I didn't think this was a _bug_, but I thought it'd be useful, so I made one: [murderous](https://github.com/Elyssaen/endless-sky/tree/feature/MurderousPersonality).

I guess if there is a 'bug' here it's the oddity that, if they _just so happen_ to fly close to a disabled hostile, and _just so happen_ to point directly at it, then and only then will they fire. It can look a little jarring when you see them doing a little surveillance patrol, taking a pot shot on some ship as they turn, then continuing on, taking a pot shot, etc.

**Comment by EndrosG** [comment]
I agree with you that the bug either is,
1. that it does not pickup that target, or,
2. that it fires on that ship without targetting it -- when pointing towards it and being in range

**Comment by endless-sky** [comment]
This behavior is intentional. It makes it so that if the player has disabled some pirate ships (but not gotten around to looting them yet) and a Navy ship jumps into the system, it will fight any active pirates but won't seek out and destroy those disabled ships that the player has been piling up to be plundered.
