### ISSUE TITLE
Idea/Possible PR: Parallax scrolling backgrounds.

### ISSUE THREAD

**Issue by sigmareaver** [endless-sky/endless-sky#2567]
# Introduction
Per the contributions document, I am creating this issue for discussion of the possible implementation of this feature.

The best example I can offer you for this is a video: https://youtu.be/pJ_zhIeMcQE?t=1m57s
You may need to put the video on 1080p and go full screen in order to see the background.

There are layers of backgrounds, adding visual depth to the scene. Each layer scrolls at a different rate, with the fastest scrolling layer being the stars nearest to the foreground, and the slowest scrolling layers representing the most distant stars from the foreground.
# Implementation
2-4 layers consisting of 1 quad (2 polygons) each.
Each layer is either:
1. Transparent with the scene being filled in as black,
2.  or the farthest back layer is not transparent with a black background.

Using UV coordinates to generate the scrolling effect, each layer's scroll speed is adjusted to what feels right to the average person. The texture on each layer should be seamless and wrapped.

**Comment by Elyssaen** [comment]
Not a bad idea, in principle. This was how it worked in Escape Velocity.

The starfield probably shouldn't move at all though. : )

**Comment by sigmareaver** [comment]
Well, if you're aiming for realism.... yeah.

**Comment by jafdy** [comment]
In both realism and gameplay perspectives this is worthless. You seem to already know about the realism part and it is not worth anything in terms of gameplay.
It would be a purely aesthetic change. While I wouldn't be too bothered by it I don't think I would like it.

**Comment by endless-sky** [comment]
The star field's main mechanical purpose is to give the player a sense of their current speed. If it didn't move at the same rate as planets, judging your speed would be considerably more difficult.

**Comment by gchapyzh** [comment]
Hmmm
In larger battles, or if there are a lot of disabled ships, or if a lot of ships were destroyed in the system recently, the background should have faint burning ships, ruins, something like that.

**Comment by sigmareaver** [comment]
I think that realism is irrelevant in this argument, because the current background isn't realistic at all. To resolve the mechanical purpose of the star field, you can use space dust as a measure of your ship's true speed (this has been done in numerous space games), or simply keep the nearest layer of stars at the same "speed depth" as the planets. Space dust should be minimalist (not too dense, and a dark to mid grey color with some transparency) so as to not be a distraction to the player.

Finally, do not underestimate the power of aesthetics. Polishing the graphics will definitely have an impact on community growth. Providing quality visuals helps to lure new players.

Well, that is about all I can say about this idea. Of course, providing a graphics quality setting that disables the parallax may be desirable.

**Comment by Elyssaen** [comment]
I was pondering the space dust approach not so long ago. I can't quite be sure it'd look good, but by the sound of it you've seen it work before. Could you point me to a game that does it?

I never found it difficult to judge my speed in EV games, which I think had one layer of stars be static. And that's even in spite of EV's starfield being very sparse in comparison. So for me it's more a question of realism (which I care about disproportionately to ES's vision) and appearance.

What I always imagined looking great was space dust for showing your relative motion (if it'd work), and the starfield being static-ish. Ish as in static in a system, but shifted between systems, and with visible nebulae.

**Comment by endless-sky** [comment]
If you're going for realism, nebulae are never "visible" as anything more than a nearly-black smudge.

I'm not at all convinced that space dust or a parallax-scrolling background would look better than the current background. I suspect it would just look tacky, instead. And the current view is perfectly "realistic" assuming the camera is stationary and is far enough away from the player's ship (i.e. the camera is rotating to track you rather than moving).

**Comment by Elyssaen** [comment]
> If you're going for realism, nebulae are never "visible" as anything more than a nearly-black smudge.

It's what I imagine looking great. I like realism to a point, but only when it plays well and looks good. We don't need a conversation on the physics of it. : )

**Comment by endless-sky** [comment]
NAEV has parallax-scrolling "nebulae" in the background, and in my opinion they look really tacky. (It doesn't help that they're so bright and colorful that they make it hard to see the actual ships and projectiles.)

**Comment by Amazinite** [comment]
Speaking of things that look great, loving the artwork. 👌
