### ISSUE TITLE
Pilot/save focus should remain in the same column between operations

### ISSUE THREAD

**Issue by dragonmaus** [endless-sky/endless-sky#2570]
When working on the save files (adding/removing), the "focus" always switches to the `Pilot` column after each operation. Usually, this is just annoying, but I just accidentally deleted a pilot whom I had put many hours into since my last backup because I was trying to delete a snapshot, so it's evolved to frustrating.

A lesser, but strongly related, issue is that there is no indication of *which* column is selected.

**Comment by endless-sky** [comment]
There is no "focus" there. The "Delete" button under the list of pilots deletes pilots, and the "Remove" button under the list of snapshots removes individual snapshots.

**Comment by dragonmaus** [comment]
Ah, sorry, I forgot to mention that I was using hotkeys.
Though further checking reveals that the hotkey I wanted was 'R' and not 'D', so the fault for that is all mine.

It's still a bit of an annoyance to have to arrow-key back to the saves column each time I do anything (so I can use the arrow keys to move up and down the list), but not as severe as I was imagining.

**Comment by endless-sky** [comment]
In the next release, those hotkeys are going to be disabled anyway, in response to issue #1981.

**Comment by endless-sky** [comment]
For what it's worth, I also made a change so that the up/down arrow focus stays in the snapshots list. (cfa82db)

**Comment by dragonmaus** [comment]
Oh excellent, thanks!
