### ISSUE TITLE
Give systems the same treatment that fleets and planets just got

### ISSUE THREAD

**Issue by TheUnfetteredOne** [endless-sky/endless-sky#2572]
This is, have the ability to add/remove singular objects, minables, fleets, or whatever it may be instead of having to redo all of them.

**Comment by Elyssaen** [comment]
To add to this, would MZ be happy for one of us to do it?

**Comment by TheUnfetteredOne** [comment]
Oops, never mind. It looks like this has already been done. https://github.com/endless-sky/endless-sky/commit/9d8f06b8b37a1dca536e3727270a6a69b7743751
