### ISSUE TITLE
ability to change transparancy value on haze

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2578]
to explain the title: add the ability to define how transparent a haze is

example: say you have 3 "corners" of space, connected through hyperlinks, and you want to give all 3 corners a different color of haze, ya want a smooth transition without making like 200 more haze images
instead ya can give the haze a lower transparancy the closer the system gets to the center, so ya'd see that every corner has a different haze color, but there's no clear border

since there are only 2 actual hazes in the base game, it may not be that useful outside of plugins, so it's not really high priority, but any plans of adding it at some point?
and is it even possible since the haze pictures themselves are colored over a black background?

**Comment by endless-sky** [comment]
Given the limits of how small a difference from system to system would be noticeable, I think just having a dozen or so different colors would be a fine work-around to this.
