### ISSUE TITLE
Issuing MoveTo order prevents (selected) out-of-system escorts from following the Player

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2580]
**To Reproduce:** Move to a new system and issue a MOVE_TO order.

**Expected behavior:** (selected) escorts follow the player and upon entering the player's system, follow the MOVE_TO order.

**Observed behavior:** If the (selected) escorts are in the player's system, they execute the MOVE_TO order. If the (selected) escorts are not in the player's system, they stop following the player and remain in their current system(s).

fb175d6917fc1aaf010bfaef46b0ebd6218edb56 was added with the goal of preventing escorts in the progress of executing / having already executed a MOVE_TO from following the player. It just also happens to make a _new_ MOVE_TO order have priority over the _existing_ FOLLOW behavior.

**Comment by tehhowch** [comment]
I see two ways to fix this:
1) Only issue MOVE_TO to escorts that are in-system ([completed](https://github.com/endless-sky/endless-sky/compare/master...tehhowch:MoveTo_OnlyFor_InSystem_Escorts?expand=1))
2) New MOVE_TO orders get interpreted as "in the player's system", e.g. any selected escorts not in system will first follow, and then MOVE_TO. Escorts with existing MOVE_TO should then stop following (e.g. HOLD_POSITION).

I have a working solution (b2f26ea), but it doesn't quite feel right as any new fleet members who enter your system don't have the order to go to the specified location. I am working on a proper fix that works in the mannerism of 2.

**Comment by Elyssaen** [comment]
Wasn't sure at first, but you've convinced me that 2 is the better way. If you've got a stream of ships coming into your system and you give a MOVE_TO command, you shouldn't have to do it over and over again until they're all in the system.

**Comment by tehhowch** [comment]
Ok, I've pushed my solution that works in manner 2)
1) Implements a function to convert between HOLD_POSITION and MOVE_TO orders when near the requested position. 
This results in ships returning to a specified position if you land and then launch again (current behavior is they will park where they leave the planet instead of where they were originally told to go)
2) Revert fb175d6 as it causes the issue identified in the first post to exist
3) Solve #2382 by converting MOVE_TO orders issued before jumping into HOLD_POSITION orders.


After merging this fix, some common situations will be handled as follows:
1) Case 1
Jump to new system
Order fleet (which may or may not be in-system) to move to a position in this system
Result: Fleet will jump to your system and move to the specified position

2) Case 2
Order fleet to move to a position in the current system.
Jump to new system.
Result: Fleet will remain in whichever system they were in when you began jumping.

3) Case 3
Create multi-system travel plan
Begin executing travel plan
Mid-plan, order fleet to move to a specified position in the current system (not the final system)
Result: Fleet will stop jumping with you, but they will not go to the specified position in the specified system. This is essentially case 2 again.

**Comment by endless-sky** [comment]
Case 4:
Order an escort that is not in the current system to "move to" a location.
Jump to a different system before that escort arrives.
Result: the escort ought to go to the system you were in when you issued the order, then hold position.

**Comment by tehhowch** [comment]
I agree that is the best behavior, and like the idea to include a target system for MOVE_TO orders that was brought up in 2584

**Comment by tehhowch** [comment]
This issue will be completely solved by #2589 , which includes a system reference when issuing a MOVE_TO command. If some intuitive UI implementation for sending a system & position reference without the player being in that system is determined, the implementation in #2589 should be ready for it with minimal changes.
