### ISSUE TITLE
Wanderer middle: drone army -> drone fleet

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2581]
line 3072:
> "Could the stolen equipment make it possible for them to build a **drone army** of their own?"

We're in space.
[And space is an ocean.](http://tvtropes.org/pmwiki/pmwiki.php/Main/SpaceIsAnOcean)
So we should use naval terminology and turn it into "drone fleet".

**Comment by endless-sky** [comment]
Fixed in 595ed52. Thanks!
