### ISSUE TITLE
Eyes or Ijs?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2585]
I've noticed that missions seem to go back and forth between calling our friendly neighborhood vigilante nuclear power plant inspector "Eyes" or "Ijs." For most of the intro he is refered to as Eyes (most of the time it says Mr. Eyes, but there are part where it drops the mister and just says Eyes), but in places like the Conservatory sideplot missions he is refered to as Ijs. And then there's "FW Katya 3" where at the beginning he is called Eyes and at the end it says Ijs. 

Is the back and forth fine or should this be standardized?

Edit: It looks like whenever he is called "Eyes" it should be preceeded by "Mr.", but as said, this isn't always the case.

**Comment by tehhowch** [comment]
Name vs nickname.. defer to MZ.

Gut feeling is that we should use the nickname only if we take mission sets that improve our relationship with him

**Comment by endless-sky** [comment]
They're both technically correct. "Eyes" is his nickname that applies particularly to his nuclear inspection work, so it is used for him when you're trying to hunt down the atmospheric nuclear signature. Once he switches to academic work he's mostly referred to by his real name.

**Comment by Amazinite** [comment]
What about situations like FW Katya 3 where it switches part way through? Or FW Conservatory 1 where it calls him Ijs throughout the conveersation but Mr. Eyes in the descriptions?

**Comment by Lineth** [comment]
The impression that example is that the two are interchangeable. Which gels with the (I'm pretty sure it's a) fact that vocally they're pronounced the same.

**Comment by koflerdavid** [comment]
It seems in fact to be a Dutch spelling. Whether it's actually used as a name, I don't know. The literal meaning is "ice". All of those words sound pretty similar to "eyes", especially for non-native speakers of English. If you ask me, the name would be fitting for a sniper...
