### ISSUE TITLE
Logbook, Missions, and Done buttons not appearing properly on the Info screen

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2587]
I can only see the Park All button. (Properly.)
Tested on a new save as well. (Because from what I can tell the Logbook system is not backwards-compatible.)

![logbookfail](https://cloud.githubusercontent.com/assets/16506683/26655107/5b90e9a6-4627-11e7-80e3-d66bf4e9172a.png)

**Comment by Elyssaen** [comment]
It's supposed to be greyed out if you don't have any logbook entries yet. But on a new save you should get one pretty much immediately in the intro missions.

**Comment by Bladewood** [comment]
I tried that, and that was how I had expected it to work.
It didn't work.

**Comment by Bladewood** [comment]
Nevermind, I'm an idiot. I hadn't yet compiled the latest build.
