### ISSUE TITLE
Navy Mark II ships appearing in Free space

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2588]
Midway into the storyline.
After building with some commit, Navy mark II ships began appearing in Free Worlds territory.
This immediately alarmed me: Before the commit, only mark I ships appeared in Free space; mark II ships were restricted to Republic space.

The mark II ships are a lot more difficult to take down than their predecessors.

[Alpha Cygni.txt](https://github.com/endless-sky/endless-sky/files/1043219/Alpha.Cygni.txt)
If it matters, I am specifically at the point where you take on the task of freeing Albatross from their pirate warlord. It's very difficult to get past the mark II ships.

**Comment by MessyMix** [comment]
Maybe I'm misreading what you wrote, but it seems that you just played to the point in the story where the Navy starts fielding Mk. II ships. You have the event "navy using mk ii ships", so..

**Comment by Bladewood** [comment]
Up until today, however, I did not encounter mark II ships in Free space. Even if I had that event.

**Comment by Bladewood** [comment]
I'm so confused.

**Comment by tehhowch** [comment]
This was from the issue that was just fixed in 6a077d4f471861567f7e81e85c5c567e259bcdc3

**Comment by Bladewood** [comment]
...oh wow.
