### ISSUE TITLE
PR: Refactor Code Blocks project build targets

### ISSUE THREAD

**Issue by sigmareaver** [endless-sky/endless-sky#2590]
This is a PR to alter the Code Blocks project file. I am submitting this PR because of issues I encountered while trying to setup the dev environment, and this will make it a lot easier on new developers.

The changes:
1. Remove paths from included libs. Pathing is not needed with search paths.
2. Add a Win64 build target.
2.1. Change search path from C:\dev32\include to C:\dev64\include
2.2. Change search path from C:\dev32\lib to C:\dev64\lib
3. Update readme-developer.txt to reflect these changes. May also want to clarify that libstdc++-6.dll needs to be taken from the version of mingw used to compile the binary. I ran into this hurdle. I tried to use the version that came with the steam release, but it doesn't match my mingw compiler and therefore does not work with my dev binary, due to differences in name mangling.

This will make it easier to setup a new dev environment.

**Comment by endless-sky** [comment]
It seems to me that everyone who sets up a build environment ends up doing it slightly differently. That is, switching it to whatever made it easier for you will probably make it harder for someone else. And, I prefer to keep it set up in a way that works on my Windows build system. (I don't do any of the development on Windows, and building each new release would be more time-consuming if every time, I had to modify the CodeBlocks files back to something that works on my Windows computer.)

**Comment by endless-sky** [comment]
Also, note that the "Release" build is a Win64 build; there's no need to add a new one.
