### ISSUE TITLE
No landing message for planets that require an attribute to land

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2595]
Normally when you try and land on a planet that you can not land on, you get a landing message that is something like "this planet is too hot," "this planet is too cold," "this planet is uninhabited," "this is a star!" etc. But when trying to land on a planet that you can land on assuming you have the right attribute, but you don't have that attribute, then you get no landing message and hitting land only tells you that there are no landable planets in this system, as if you were hitting the land key over empty space.

**Comment by tehhowch** [comment]
Right now those messages are preloaded for each stellar object when the system loads, and there isn't a check to see if a particular stellar object has an attributes list that contains the keyword "requires"

A fix would need to add both a string and that check
a possible string: "You are not sure why, but you cannot land here."

**Comment by tehhowch** [comment]
I'm also not sure it needs to say more? The message is "There are no planets in this system that you can land on." It's 100% correct as-is. The attentive player will definitely note that "hmm, stuff is landing here, but the game says I can't land here" and perhaps seek to find out why.

**Comment by Amazinite** [comment]
Yes, it's 100% correct, but if that's the case then we could just remove all landing messages. The fact that there is no landing message in this case when there is expected to be one seems inconsistent. It also doesn't tell us why we can't land, while a landing message does.

**Comment by tehhowch** [comment]
Here's a message and check for an inaccessible landable.
![image](https://cloud.githubusercontent.com/assets/20871346/26747134/738b2f10-47b9-11e7-9fb5-ba67b3a31c99.png)

So this?

Thoughts on a better message?

**Comment by TheUnfetteredOne** [comment]
Aren't we suppose to avoid stuff like "you don't know why" since it assumes something about the player? I think this would be better: 
"Your ship is not equipped to land here."

**Comment by Amazinite** [comment]
I think I'd prefer to have the landing message be what it normally is. e.g. If you don't have gaslining and you're trying to land on Slylandro then it just says "You cannot land on a gas giant" like usual.

**Comment by Elyssaen** [comment]
Agreed with @Amazinite. I guess the red wormholes need something new though?

**Comment by jafdy** [comment]
>You pass through this cloud of energy like it is a . . . cloud of energy.

>It looks like a wormhole, it gives off the energy readings of a wormhole but it does not act at all like a wormhole.

**Comment by Bladewood** [comment]
> This spacial anomaly resembles a wormhole, and it should behave like so, but it is just too dangerous to explore it without something to stabilize your travel.

**Comment by Elyssaen** [comment]
> This precious artifact attunes a ship's quantum oscillations in a way that allows it to travel through certain otherwise impassible wormholes in the Ember Waste

This is all I think we've got right now, but I could be mistaken.

**Comment by Amazinite** [comment]
Wormholes already have a landing message; no need to make a new one just for the red wormholes.

**Comment by Elyssaen** [comment]
What's the landing message, and does it tell you that you can't land on it...?

**Comment by Amazinite** [comment]
[Find out for yourself.](https://github.com/Amazinite/endless-sky/blob/endless-sky/data/landing%20messages.txt)

**Comment by Elyssaen** [comment]
I was only on a mobile device. Back about now. Thank you though. : )

**Comment by tehhowch** [comment]
Should be fixed in #2601

**Comment by endless-sky** [comment]
Fixed in 72cea97.
