### ISSUE TITLE
Prevent key bindings being changed to number keys

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#2597]
http://steamcommunity.com/app/404410/discussions/1/1291817837620309985/

Someone tried to bind firing keys to numbers and that caused targets to be deselected (because of the RTS style controls).

**Comment by KiLEdEnNis** [comment]
before the numbers did anything I assigned the "select ammo" key to it, didn't work after the fleet control update
what if keybindings ARE numbers before the fix you're asking though?

**Comment by endless-sky** [comment]
Fixed in 30aa6fb. If someone is binding commands to those keys, they probably aren't using them for their default purpose, anyway.
