### ISSUE TITLE
Planet labels not always moving out of the way

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#2598]
http://steamcommunity.com/app/404410/discussions/1/1291817837626587938/

Through random luck and chance someone has a planetary satellite that has obscured the planets name. My best guess is that the distance from the "surface" to the satellite is to small for the detection to spot.

**Comment by Bladewood** [comment]
duplicate

I shall seek out the original

**Comment by jafdy** [comment]
Yes I saw that one, I read it more or less as the screen shot [in there] showed, it was the arcs being obscured.

Thinking carefully about it I think the simplest change is to put the label in a position that is more than say, 20 degrees, from the vector to any child object.

**Comment by Amazinite** [comment]
Whether it was the arc being obscured or not in that issue, this still applies
>I'm pretty sure they're intended to not overlap at normal zoom, but [at different] zoom levels [no overlapping] isn't guaranteed. Same as the map. Zoom out to just before the labels get removed and a bunch of stuff overlaps.

And the guy on Steam does say that it's only certain zoom levels.
