### ISSUE TITLE
Random turret tracking makes mining with turrets impossible

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2599]
Something that was brought up on the Discord. Since turrets will randomly turn and point all over the place when out of combat, it makes it extremely difficult to mine asteroids with turrets unless the asteroid is right on top of your hardpoint.

**Comment by Bladewood** [comment]
Change it to `focused` turret tracking in preferences.

Problems like this are why the Model 8 exists for the Kor Mereti, I think.

**Comment by KiLEdEnNis** [comment]
turrets should face front if not in combat (if there are hostile systems in the system they can turn to them, or just when in firing range, whichever seems better)

**Comment by Amazinite** [comment]
@Bladewood That doesn't do anything.

**Comment by Elyssaen** [comment]
Focused doesn't make any difference, my gunners are still all goddamn drunk. I can't find out how to jettison them, either. Need feature to kill your own crew for being absolutely useless.

**Comment by Bladewood** [comment]
@Amazinite Oh, I was thinking about targeting, nevermind that post then.

@KiLEdEnNis, it's actually a sweeping motion.

**Comment by Amazinite** [comment]
Maybe targetting asteroids needs to become a thing (especially because I like the random turret sweeping. I can make light shows if I have a bunch of laser turrets).

**Comment by Elyssaen** [comment]
I'm with @KiLEdEnNis though. I know it's only been about an hour, but so far I really can't get my head around the random turret movement out of combat.

![met par tek](https://cloud.githubusercontent.com/assets/23544894/26757680/30cdefe2-48bc-11e7-9681-b66c92a634ac.png)

**Comment by Bladewood** [comment]
I just said, it's not (completely) random, it's a sweeping motion ;(

As for what purpose it would serve out of combat, I have no clue. In-lore it's probably explained by the turret users scanning the area for hostiles.
But then we come to problems with stuff like the Korath...

**Comment by Amazinite** [comment]
Alright @Bladewood, we understand that the turrets do not warp into random positions in space time.

**Comment by sigmareaver** [comment]
I'll promote a different solution: a new key that locks/unlocks turrets at will to/from facing forwards, which could subsequently double for the focus fire mode.

**Comment by jafdy** [comment]
Locks the turrets to the mouse? That would make mining easier with turrets.

**Comment by tehhowch** [comment]
What keymap are you using that you'd be able to fire, steer, and aim via cursor? Lol

On a laptop with a track pad, good luck 😂

**Comment by jafdy** [comment]
I map all the keys that I can under my left hand so I can click targets with my right hand.

**Comment by endless-sky** [comment]
As of 16faf29, turrets in focused fire mode now point forward when no target is present. The behaviors are now as follows:

**Focused:** If no enemy is nearby, point forward. If a target is selected, point at it. If no target is selected and an enemy ship is present, point at it (as a convenience for when you don't want to bother to target an enemy).

**Opportunistic:** If no enemy is present, sweep the sky. If a target is selected and no other enemies are in range, point at that target even if it is out of range. If targets are present within weapons range, aim at whichever one is closest to the turret's current facing direction.

**Comment by KiLEdEnNis** [comment]
so if an enemy is near you can't really mine? which isn't much of a problem, but it may annoy some people

**Comment by endless-sky** [comment]
Remember that turrets are generally operated by a crew member. You can try to tell them that firing on a defenseless asteroid is more important than firing on the ship that is attacking you, but they're unlikely to listen to you...

**Comment by Pointedstick** [comment]
FWIW, I really, _really_ like the "sweeping the sky" behavior.

**Comment by KiLEdEnNis** [comment]
I meant like if an enemy is like 10s flight away and engaged in battle and you're flying an OP T3 ship for example, that might be annoying

**Comment by koflerdavid** [comment]
I am almost fine with the sweepingbehaviour. In a system with lots of asteorids (for example Zaurak), the sweeping behaviour and having a fleet nearby is a nice synergy. (349's have quite some cargo space. Were they intended as player ships?)

**Comment by tehhowch** [comment]
@KiLEdEnNis turrets will only lock targets that are 1.5x max_turret_range away. So if you have grabstrikes, at worst you're looking at all targets within 1500px triggering your turret's preemptive lock.
Flagships with the velocity to make 1500px require 10s of flight are not exactly able to mine and harvest asteroids...

**Comment by Amazinite** [comment]
My 100th closed issue. Hmm.
