### ISSUE TITLE
Unevaluted variable in text of mission "Smuggler's Den: Payment"

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#26]
I got a non-evaluated ```<payment>``` variable in the event text for the "Smuggler's Den: Payment" mission (the text contained "\<payment\>" in plain text instead of 35000).

I don't see what would be wrong with the data though: https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt#L219

**Comment by endless-sky** [comment]
I think it's because the payment is being given "on offer," whereas everywhere else it's "on complete." The code was written to assume that you never get a payment in an offer, but I can fix that pretty easily.

**Comment by endless-sky** [comment]
This should be fixed in 5159ddb. Previously, the <payment> value was only initialized if a payment was offered in the "on complete" action in the mission; now it is initialized if any action offers a payment.
