### ISSUE TITLE
Ships should dock at space stations instead of shrinking as if to land on them

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#260]
The animation for ships shrinking as they land works for planets, but doesn't seem to make as much visual sense for space stations. Instead, it would be cool if ships would pull alongside them and extend a docking tube.

**Comment by endless-sky** [comment]
Although the scales are not consistent between different planetary objects, the intention is that as with moons and planets, the space stations are small only because they are "farther away." That is, even a tiny space station is bigger than the biggest ship, in real world units.

**Comment by Pointedstick** [comment]
Nah.
