### ISSUE TITLE
No visible turret turn attribute in outfitter

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2600]
Right now there's no stat in the outfitter that displays the turn rate of a turret, so there's no way to compare turrets in how fast they turn without looking at the data, which a lot of people won't do.

**Comment by Bladewood** [comment]
I think it's supposed to be implied by the mass of the turret and stuff.

**Comment by Amazinite** [comment]
Turrets in order of how fast they turn compared to their mass (last column). 
![6819d08eb6e64461a68232995138e035](https://cloud.githubusercontent.com/assets/17688683/26757712/002ec000-4894-11e7-9651-e585080bae7a.png)
As you can see, it's not always easy to assume turn rate from mass. 18 ton modified blaster turret is slower than the 22 ton laser turret, and the 43 ton Bombardment Turret is faster than the 35 ton Korath Disruptor.

**Comment by gunqqer** [comment]
With this new way of turret turning speed it will feel like I'm playing World of tanks blitz even more. When trying to hit something you turn the ship and turret to hit them. This will be an interesting update to say the least. 

More on topic it would be very nice to have the turning speed in the outfitter

**Comment by Elyssaen** [comment]
@Amazinite: problem with the right-hand measure in your first column is that the hypothesis here is that Deg/Sec goes down as Mass goes up. If you want to see how good that hypothesis is, you want to see how constant the 'constant' is: Deg/Sec = constant / Mass, so constant = (Deg/Sec) * Mass. [sqrt(Mass) is a little better, arguably.]

Key check is that the Blaster Turret and Plasma Turret want to be close together on the sorted list, as they're a good example of the hypothesis working.

![image](https://cloud.githubusercontent.com/assets/23544894/26758469/18427360-48d7-11e7-8d1f-caaacb2427d4.png)

Then the key findings read off easily:

1. 7000-10,000 is the normal range.
2. Higher tier weapons have better values: the T3 Pug are, as usual, not even playing fair.
3. Beam weapons are better than pulsed weapons.
4. The Bombardment Turret and Banisher are particularly good.

Anyway, on-topic: maybe players can just find out from experience, but I personally prefer having plenty of information at hand. It's relevant early for Blasters vs Lasers, and it's something I'd like to know about the Plasma Turret in particular, if I were playing as a new player in 0.9.7.

**Comment by Amazinite** [comment]
It wasn't a question of balance, it was a question of how mass affects turning rate. @Bladewood said that it's assumed from the mass, and I showed him how you can't really assume the turn rate from the mass because less mass doesn't always mean faster turning (the best example probably being the one you pointed out, that the heavier Laser Turret turns faster than the Blaster Turret).

**Comment by Elyssaen** [comment]
Hm, wasn't saying it was a question of balance. I was trying to give you a chart that more easily demonstrated your point! Your first chart scaled the wrong way, and your second didn't relate Deg/Sec to Mass.

**Comment by endless-sky** [comment]
Added in 01a2f95.

**Comment by MessyMix** [comment]
close? :3
