### ISSUE TITLE
Outfitter enhancement: Change ship color outline based on installed / not installed status of selected outfit

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2607]
If you select multiple ships, you will see various for-sale outfits switch to "installed: 0 - N".
I propose that when you select such an outfit - where not all ships have it installed - the ships that do have it installed obtain a differently colored outline. A first choice: green

I could also understand always doing this behavior (e.g. even if all ships have it, all outlines become \<color\>) to avoid the "same action different results" possibility of confusion.

This condition-dependent coloring could be extended to highlight ships in red if they do not have it installed and also do not have the space to install it.

Current game behavior:
![image](https://user-images.githubusercontent.com/20871346/26944629-e1901ed2-4c4e-11e7-9473-2f32b567a25a.png)

Proposition:
![screenshot from 2017-06-08 13-31-49](https://user-images.githubusercontent.com/20871346/26945315-f9d1de98-4c50-11e7-99fc-752797b588d0.png)

**Comment by KiLEdEnNis** [comment]
what if some ships have none of the outfits, some have 1 or 2 and some have like 6? although that's a possible "next step", this shows which ships have the outfit which is good

**Comment by tehhowch** [comment]
Using color to indicate how many is certainly possible (see commodities on map), but more convoluted. Possoble 3 color schemes: 
1) green = has at least 1 installed , white = zero installed, and red = no room / can't install.
2) green = zero and can install, red = zero and can't install, and white = has at least 1 installed

**Comment by Elyssaen** [comment]
Prefer your first scheme, as it keeps the white default in the default case. But definitely a nice idea.

**Comment by endless-sky** [comment]
In commit cf9ff67, I've got what I think is a more intuitive and less intrusive approach to this: when you hover over the "buy" or "sell" button, highlighting which ships the buy or sell will apply to. Because the highlight is in response to hovering over the button, its meaning is immediately clear (unlike the icons proposed here), and it provides an easily discoverable way to check which ships have a given outfit.

**Comment by tehhowch** [comment]
Awesome
