### ISSUE TITLE
Interference plating doesn't seem particularly balanced

### ISSUE THREAD

**Issue by fcfort** [endless-sky/endless-sky#261]
While the exponential decaying utility of interference plating is a good mechanic, overall I think interference plating is a bit too weak in its current form. You need a very, very large amount of interference plating to avoid what is quite a large fine (up to 1M per failed scan in which you hold Nerve Gas for instance). And since any given ship can scan you (multiple times even?), it is very hard to avoid getting caught even with a 100 tons dedicated to interference plating.

Perhaps it could be balanced out with some sort of factor that is dependent upon the amount of illegal cargo you're carrying, like holding 1 Nerve Gas is a much lower offense than holding 100 Nerve Gas? Or perhaps just increasing the benefit of each layer of plating? Or reducing its tonnage?

**Comment by Phezzan** [comment]
I'm wrestling with this too.

I want to prevent every scan-capable ship in the system from scanning you. Don't they trust each other to do a scan?
There's no way your interference plating will save you if you have to pass 5-10 scans per system, and it's actually much better to have a scram drive and get away before they get close.

I'm also wrestling with the problem of which ship the illegal cargo is loaded onto.... it's not always my flagship (with the plating...)

**Comment by thenerdfreak** [comment]
tbh you might think it's op but i just went to the files and changed the number that decides you getting caught to like 10 million or something so 1 plate always works, i get that it's a game mechanic, but when the only way you can capture some of the alien ships is with a ton of nerve gas, it gets really annoying to get fined every time you jump back to sell the parts

**Comment by Oeleo** [comment]
By the way, someone succeed of taking a world ship in 0.8.7/8 ?

**Comment by thenerdfreak** [comment]
You've been able to take worldships for a while, you just can't get them out of the systems they're in because they have no jumpdrive

**Comment by gchapyzh** [comment]
@thenerdfreak  Can you put a hyper-drive on them?

**Comment by thenerdfreak** [comment]
worldships are in korath territory, but they already have hyperdrives, just not jumpdrives needed to get them into human space

**Comment by gchapyzh** [comment]
So... you can capture one, but you cant keep one?!

**Comment by Oeleo** [comment]
But... can you actually ? Because even with ~444 bunks and nerve gas, against a ship with ~1550 defense ( have ~1650) it never works (snif).

**Comment by gchapyzh** [comment]
All the nerve gas, all the bunks, all the grenades, all the rifles. No weapons on your Bactrian, turn everything into space for bunks. No shields either. Let the fleet disable it, and then board with all the forces. How many people is that?

**Comment by Oeleo** [comment]
Oh maybe that I think that I hadn't the maximum of normal grenades and rifles because I thought that only the best weapon would be use (but I did the rest). Thanks I'll try this again.

**Comment by thenerdfreak** [comment]
Not all world ships have the same crew, i've found some that had less crew than my souped up bactrian

**Comment by thenerdfreak** [comment]
only the best weapon counts

**Comment by gchapyzh** [comment]
Really? SO if I have one crew with a rifle, bomb and gas, only the gas
bonus will act?

On Thu, Nov 26, 2015 at 12:09 PM, thenerdfreak <notifications@github.com>
wrote:

> only the best weapon counts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/endless-sky/endless-sky/issues/261#issuecomment-159988243>
> .
>



-- 
*OPERATOR*
*Logix Tec Corporations*

**Comment by endless-sky** [comment]
That's right. Crew members only have two hands, after all.

**Comment by gchapyzh** [comment]
So. that's a rifle per hand, plus a gas bomb in the teeth.

On Thu, Nov 26, 2015 at 6:31 PM, Endless Sky <notifications@github.com>
wrote:

> That's right. Crew members only have two hands, after all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/endless-sky/endless-sky/issues/261#issuecomment-160029518>
> .
>



-- 
*OPERATOR*
*Logix Tec Corporations*

**Comment by endless-sky** [comment]
It's really just a matter of balance. If crew members could use any number of weapons at the same time, first of all that would mean they could also wield, say, ten laser rifles per person. If you don't allow wielding multiple weapons of the same type but do allow different types, then suddenly it becomes almost impossible to add a new type of hand to hand weapon because it will stack with all the other existing ones instead of being an alternative to them.

**Comment by gchapyzh** [comment]
We could be smart: There would be multiple types of firearms, (Pistol | Flamethrower), and multiple types of explosives (Grenades | Nerve gas). The only the best of the weapons in each type are used.

**Comment by endless-sky** [comment]
But, if that were allowed, all the hand to hand weapons would need to be reduced in strength to maintain the current difficulty of capturing ships, so the only real difference would be that to get the same effect, you'd need to have multiple kinds of hand to hand weapons installed on your ship.

**Comment by gchapyzh** [comment]
​That, or you could keep the damage from weapons, but give everyone the improvement. So, now both AI and players will have an armory of improved weapons.

**Comment by Oeleo** [comment]
I comfirm In Beta they have far more than your ship : something beetween 550 and 1100

**Comment by gchapyzh** [comment]
I wish I could board simultaneously with multiple ships....

You got 1100 defense?  I GOT 1100 BACTRIAMS WITH NERVE GASS

**Comment by johndh** [comment]
It makes sense to me that having a variety of weaponry would be beneficial.  We don't see soldiers nowadays going into battle with JUST a rifle or JUST a grenade.  They usually have a variety of armaments.  Maybe the bonuses shouldn't stack directly, but be multiplicative?  Or maybe the highest bonus counts fully, plus half the bonus of the second weapon.  With either of those solutions, each weapon maintains its current level of usefulness on its own, while slightly raising the limit of how powerful boarding can be for those who really want to put the extra money into it.

Alternatively, there could be different equipment types, so a crew member gets a bonus from the best primary weapon (rifle or defense station), the best grenade (grenade or nerve gas), and the best body armor or personal shield, or something like that.  I'm not sure if that level of complexity is desirable for other players, but I think it would be welcome for those of us for whom boarding is the main way we do things.

**Comment by Oeleo** [comment]
gchapyzh maybe that a system could make that not too cheaty ? Something like 
**initial attack power+log(y)x50** y being the numbers of the other crew in your fleet, so for exemple you have 2000 extra crews in your fleet it makes :
Initial attack power + log(2000)x50 = Initial attack power + 165
The advantage is that it decrease with the number of extra crew, for exemple log(10000)x50 = 200
-If you are really rich, you can theoritically take any ship, but you have to have thousands of ships, so it's not really possible.
-That it's a bit realistic  because when you have a lot of crew who attack simultaneously in a limited space, that's harder to organize so they are less effective than in smaller group. Of course that's a little weird because kill 100000 people to take one boat, well that's not really ethical. But with a limit somewhere, for exemple no more than the number of the crew in the flagship can be killed this can be a good system, because with a huge number you can have less man kills (your crews, of course...) if your attack power become high enough so in fact you will save lifes (lol). Of course this will add extra penalty in money for each extra crew killed outside of your flagship, with the same system than in game, but in addition.

**Comment by gchapyzh** [comment]
@Oeleo 

(R1) + (R2)/X + (B1)

R1: First best ranking ranged weapon (Ex: rifle)
R2: Second best ranking ranged weapon (Ex: Pistol)
X: Percent of your force that is alive
B1: First best ranking grenade (Ex: Nerve Gas)

This way, when your forces are lower in number, their attack/defense goes up a small amount if they have a second ranged weapon. That way the tide of the battle bight turn if only one side has secondary weapons.

**Comment by brendanjones** [comment]
While I'll agree interference plating is a bit weak, we could also tweak how fines are applied for nerve gas.

At the moment there's a flat fine of $1 million. How about making the fine per unit of nerve gas, instead? Maybe $25K per unit?

A Bactrian with 300 crew would take a $7.5million fine o.O But anyone with a Bactrian can probably afford that.

**Comment by thenerdfreak** [comment]
Tbh I think it is less than interference plating is too weak, and more of the fact that every Republic ship that you're in a system with scans you five times before jumping. You're basically set up to fail. Maybe after ONE ship scans you, the others don't?

**Comment by brendanjones** [comment]
> Tbh I think it is less than interference plating is too weak, and more of the fact that every Republic ship that you're in a system with scans you five times before jumping. You're basically set up to fail. Maybe after ONE ship scans you, the others don't?
> - thenerdfreak

Agreed. It's not logical that every ship scans you separately. How efficient is this navy when they've got 5 ships doing the same job? (hint: not very)

...and implement my tweak of nerve gas fine implementation so that small-time early-game use of nerve gas is viable ;)

**Comment by endless-sky** [comment]
I think the right solution to this is to make scans less frequent (#310) rather than making interference plating more powerful.
