### ISSUE TITLE
<shift> key not working

### ISSUE THREAD

**Issue by LePilot** [endless-sky/endless-sky#2610]
I attempted to hail a planet, but the <shift> key didn't do anything. I tried right and left shift, but none of the listed effects happened.

**Comment by tehhowch** [comment]
To clarify, you pressed both "Shift" **and** the hail key "T"? In a system with a landable planet?

For future reference: if you are attempting to indicate the presence of a bug in a program, you should ALWAYS include information about 1) your system, and 2) the version number of the program. Those 2 things are relevant to every possible instance of bug reporting in any field of tech anywhere. In this instance, "system" means "What operating system are you using, and what mechanical hardware that is relevant to playing games are you using" Especially important when dealing with a bug related to processing of command inputs would be if anything input-related is not standard, such as using a user-modded keyboard or playing via hotkey macros.
Also relevant to Endless Sky and perceived bugs: what plugins - if any - have you installed, and are you playing a version obtained from Steam, a distributed binary downloaded from this GitHub repository, or a self-compiled binary made from the source code available in this GitHub repository (in which case you should specify the latest commit in your build).

**Comment by endless-sky** [comment]
Do you have the planet selected as your landing destination? That is, does "Landing on: Planet Name" appear next to the radar, and are there target crosshairs around the planet?
