### ISSUE TITLE
Game consistently crashes

### ISSUE THREAD

**Issue by 123abchelpineedausername** [endless-sky/endless-sky#2611]
I cant play for more than 5 minutes until crashing
1. Effects any character, even new ones
2. Unmodded version of Endless Sky
3. 0.9.6 Steam version 
4. macOS Sierra Version 10.12.5
5. I played for 400+ hours before the crashing started
6. I have uninstalled and reinstalled the game on Steam
Errors.txt:
[errors copy.txt](https://github.com/endless-sky/endless-sky/files/1065884/errors.copy.txt)
Save File:
[Nudnuii Maiarone copy.txt](https://github.com/endless-sky/endless-sky/files/1065888/Nudnuii.Maiarone.copy.txt)

**Comment by endless-sky** [comment]
It looks like somehow your map file (and possibly other files as well) has gotten corrupted. In Steam you can use the "Verify integrity of game files" option to fix whatever is broken.

**Comment by 123abchelpineedausername** [comment]
I have done that already, the problem still exists.

**Comment by tehhowch** [comment]
Did you or another user add/remove anything on your system recently?

**Comment by 123abchelpineedausername** [comment]
No

**Comment by jafdy** [comment]
It might be worth uninstalling and reinstalling. It looks like it is a problem with the all the mineables so I'm guessing that the .exe is the problem.

**Comment by 123abchelpineedausername** [comment]
Im on a mac, so I can't uninstall and reinstall. However I can access the files as seen and replace any that need fixing, so assuming that the prediction that the map file is corrupted, should I replace it with a fresh copy from Github?

**Comment by jafdy** [comment]
Give it a go. Do macs use the equivalent of a .exe or a binary (machine code) file? If they do then replace that a well.

**Comment by 123abchelpineedausername** [comment]
all the code accessible to me is a .txt file, so don't know how it compares

**Comment by 123abchelpineedausername** [comment]
Replacing the map file did not work.
Any other files that may help if replaced?

**Comment by 123abchelpineedausername** [comment]
I do believe it is fixed. It appears to be the map because after I replaced it with a fresh version from GitHub I checked integrity through steam and it detected a corrupted file and fixed, which appears to have fixed the problem. Thank you very much for you help in solving this 4+ month old issue.
