### ISSUE TITLE
Mission posting accept automatically selects the next mission but it forgets to update the map.

### ISSUE THREAD

**Issue by neil-edelman** [endless-sky/endless-sky#2619]
Also, when you first go to the screen, it doesn't select the map properly.

**Comment by tehhowch** [comment]
Can you clarify what you are trying to say? Pictures and or screenshots would be very helpful, and video is naturally even more helpful when trying to convey an issue that happens with the game's response to your action.

**Comment by endless-sky** [comment]
If you're talking about the fact that the map doesn't re-center when a different mission is selected automatically rather than through a deliberate player action, that's intentional. People were finding it confusing that the map would jump around every time they clicked "accept."
