### ISSUE TITLE
Failed to build under linux

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#262]
Building in Code::Blocks V13.12 under OpenSuse 13.2 and getting this error.

![image](https://cloud.githubusercontent.com/assets/8764280/11412974/6faf27b0-9398-11e5-9c1a-79f8d0b90342.png)

**Comment by Pointedstick** [comment]
You're missing the listed static libraries that the code links against. Install them and try again.

**Comment by gchapyzh** [comment]
Does the game require Wine to run on Linux?

**Comment by endless-sky** [comment]
The Code::Blocks project is only for Windows. On Linux, use scons from the command line.

See the readme-developer.txt or the [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions) on the wiki for more information.

**Comment by gchapyzh** [comment]
Scons and all the libraries I installed for Code::Blocks worked. Got a functional ES. Thanks!
