### ISSUE TITLE
Quantum Keystones

### ISSUE THREAD

**Issue by Hadron1776** [endless-sky/endless-sky#2620]
So far, there are two quantum keystones in the game. One version is in Hai space, the other is in the new Ember Wastes region. So far, so good. Here's the issue: Both versions have "quantum keystone: 1", i.e. they're the same thing. 
However, one costs 12,000 credits and the other costs 240,000 credits. Is this intentional? I've noticed that the expensive keystone also requires a remnant license; however, since you pretty much need the keystone to get to Remnant space in the first place, I really don't see the point.

**Comment by Amazinite** [comment]
It's to represent how each group sees the keystone (or key stone) differently. The Hai value it little since they don't know its true use, while the Remnant value it highly since they know what it actually does.

**Comment by ldsgsm** [comment]
I strongly support having the keystones being costed differently and having different descriptions for the reasons Amazinite outlined--however, it does make me uncomfortable that they literally have different names "Keystone" vs "Key Stone".

I understand this is probably a workaround to allow the game to treat them differently, but is it possible to tag them in a way the player cannot see?

**Comment by tehhowch** [comment]
Key Stone and Keystone are not likely to change for previously stated reasons.

However, the Hai outfit could be changed to just "Keystone," "Decorative Keystone," "Ancient Keystone," or something that doesn't place the two outfits immediately and forever adjacent to each other. That would probably prevent further influx of duplicate issues and still convey the game lore of "known purpose" vs "folk artifact"

**Comment by ldsgsm** [comment]
That sounds great to me.

**Comment by endless-sky** [comment]
The different names are intentional. The point is to make it clear that the Remnant still knows that the stones are a key that unlocks something, but that the Hai have forgotten their purpose. Thus, "key stone," i.e. a stone that is a key to something, has been corrupted to "keystone," which is the word for the stone that is placed in the top of an arch when it is completed.

**Comment by ldsgsm** [comment]
That makes sense. I still think "Decorative Key Stone" or "Lucky Keystone"
or something would be better.

**Comment by KiLEdEnNis** [comment]
I really don't
but there's an actual outfit image for the Key Stone, so it's more clear to tell them apart

**Comment by tehhowch** [comment]
@KiLEdEnNis Both the Hai and Remnant outfits have the same outfit image. If the player has one in their selected ship, and is browsing an outfitter that has the other for sale, they are currently always shown next to each other. This leads to people first thinking that there is some mistake in the game ("it's an open source game, looks like someone made a typo"), and only later (after being told it is not a mistake), understanding the difference between the two outfits.

If the Hai outfit is bastardized even more - by dropping "Quantum" in lieu of some other descriptor - then this side-by-side comparison is not continually made.

**Comment by Lineth** [comment]
"Decorative stone" would work. Maybe bring back the old outfit image for the Hai stone to further differentiate them.

**Comment by tehhowch** [comment]
I don't believe that the outfit image needs changing, as it is literally lored as the same thing, but the Hai have lost the knowledge of what it is, while Remnant has not. The appearance of the object should not depend on the level of understanding.

**Comment by Lineth** [comment]
I was going on the conceit that was was specifically cut/fitted for starship use and the other was not, as they don't really know what it's for.

**Comment by MessyMix** [comment]
Maybe the Remnant one could be placed upon a pedestal or mount (it being very precious), and the Hai one just the crystal (luck charm, after all).

**Comment by ldsgsm** [comment]
I like that they have the same outfit image, for whatever that is worth. It
is good for them to be similar--so long as they are not so similar that the
differences look like mistakes.

**Comment by Bladewood** [comment]
The Remnant merchant did note that the Hai key stone looked different than that of their own.
The key stone has had two different sprites. Maybe we could use one sprite for the Hai key stone, and the other for the Remnant key stone.

**Comment by ldsgsm** [comment]
Even if we do change the sprites, I still think that a shift in the name
would be valuable. It is the almost-same spelling that makes it look like a
mistake. I understood as soon as I saw them both that they were understood
differently but were essentially the same item--but it still read like a
typo or a game design hack.

**Comment by KiLEdEnNis** [comment]
@tehhowch https://github.com/endless-sky/endless-sky/blob/master/images/outfit/keystone.png

**Comment by Bladewood** [comment]
What @ldsgsm means is that Michael decided to *integrate that into the plot*, i.e. declaring a bug to be a feature.

**Comment by Amazinite** [comment]
>declaring a bug to be a feature.

Implying that it was a bug in the first place.

**Comment by ldsgsm** [comment]
I see and respect that Michael was trying to use a programming constraint as a way to communicate that these two cultures have the same item, but view it in very different ways. However, his (deliberate) implementation does not achieve that effect for me--the description does, and the way the people react to the key stones does, but the slight difference in names (however deliberate) falls in the uncanny valley for me. I see the goal; I see why this was expected to accomplish it. I still think we should change the name.

**Comment by Amazinite** [comment]
I'd say that if anything, just drop "Quantum" from the Hai variant.

**Comment by ldsgsm** [comment]
I like the idea of a different adjective in front of "Key Stone" (or "Keystone"), but that'd be an acceptable solution from my perspective.

**Comment by KiLEdEnNis** [comment]
I think that since the Key Stone has a different sprite now it really isn't a problem anymore, I get confusion if both share the same sprite but they got their own now

**Comment by Amazinite** [comment]
@KiLEdEnNis 
![screenshot_5](https://user-images.githubusercontent.com/17688683/29244848-21c4563c-7f92-11e7-8c2f-b7ef1d60dd30.png)

**Comment by KiLEdEnNis** [comment]
oh Keystone got changed too?
hmm...

**Comment by ldsgsm** [comment]
The problem is not mixing them up, it is feeling as though the writers of the game made a mistake. Different sprites helps but doesn't really fix that, anyway.

**Comment by KiLEdEnNis** [comment]
it does feel like a mistake, but the Hai made the mistake, not MZ lol

**Comment by ldsgsm** [comment]
That's how it is, but it isn't how it feels.

**Comment by ldsgsm** [comment]
So... is there any chance of MZ renaming the Hai version of the quantum key stone? I still like having the graphic be the same.

**Comment by KiLEdEnNis** [comment]
by now if he did we'd have to:
- deprecate the current Hai Keystone (deprecated outfits are outfits that are unobtainable but not deleted from the game to not break the save files)
- all missions that have a Hai Keystone as requirement would need that deprecated and the new Hai Keystone as potential requirements
so I doubt it's gonna happen, however I think the sprites should be slightly different since lore-wise they ARE different and in a Remnant mission it's even stated they look a bit different
if they look similar but not the same the confusion may go, and changing sprites doesn't harm save files as long as the new image is saved under the same name

**Comment by tehhowch** [comment]
The outfit details are not stored in the save. A new image for an existing
outfit can have any name.

**Comment by KiLEdEnNis** [comment]
for ships they are, I'll edit my comment to specify that
