### ISSUE TITLE
Space Port based missions should be impossible in Pug occupied FW

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2623]
In the "What happened to Rand?" mission I landed on Rand and entered the space port. I was then offered one of the popup quests about some business trip. This is should not be possible because it is possible that these quests may be impossible.

**Comment by Amazinite** [comment]
Well that mission is [minor](https://github.com/endless-sky/endless-sky/blob/1abd93dc85d3a38d7b40f4df50092d404617442c/data/transport%20missions.txt#L1666), so I don't know why it'd offer over a main mission.

**Comment by Bladewood** [comment]
relevant: https://github.com/endless-sky/endless-sky/issues/2296 https://github.com/endless-sky/endless-sky/issues/1330

**Comment by 123abchelpineedausername** [comment]
Also this may be logical, but still applies. After liberating the first Pug world you are able to get hunting down pirate quests.

**Comment by endless-sky** [comment]
Addressed in #3106.
