### ISSUE TITLE
hotkey/keyboard shortcut

### ISSUE THREAD

**Issue by Labna** [endless-sky/endless-sky#2628]
# keys :
## Global :
    I : info / list of ship
    M : Map in pots mod
    J : Jump (hold to wait)
    L : Land (repeat to switch destination)
    Escape : main menu
    hold ALT to show hotkey
    
## In Space :
    right-click : gather all/selected ship
    click and drag : select in area

## Planet Interface :
    T : trading
    O : Outfitter
    P : Space Port
    S : Shipyard
    D : Depart
    H : Hire crew
    J : Open map in mission mode
    L : text of landing
    B : Bank
    
### Trading mode :
      Shift + B : Buy all
      Shift + S : Sell all
      enter [+ Shift][+ Ctrl | SUPER][+ ALT] : buy [x5][x20][x500] (mixable: x100,x2500,x10000,x50000) (!!on some system Alt + enter = fullscreen)
      Delete [+ Shift][+ Ctrl | SUPER][+ ALT] : sell [x5][x20][x500]
      up/down : change trad item

## Map Interface:
    S : Shipyard
    I : Mission
    O : OutFitters
    P : Port
    D : Done
    F : search (planet/ship/oufitter)
    
### Ports and mission mode :
      J/tab : select planet around the actual
      Shift + tab : the selection became the actual
    
### Port mode :
      up/down : change trad item
    
### Mission mode :
      A : accept/abort mission
      up/down : change mission
      left/right : current/available mission

## Outfitter Interface :
    L/D/escape : leave
    B/I [+ Shift][+ Ctrl | SUPER][+ ALT] : Buy [x5][x20][x500]
    S : Sell

## Shipyard Interface :
    L/D/escape : leave
    B/I [+ Shift][+ Ctrl | SUPER][+ ALT] : Buy [x5][x20][x500]
    S : Sell

- - - - - - - - - - - - - - - - - - - - - - - - - -

I made this because I don't find anywhere a description of keys (not in the settings)
I heard about using 1 to 0 keys to manage ships, but doesn't seem to work.
**The biggest missing of hotkey is the possibility to switch the selected ship in the shipyard/oufitter trading interface**

**Comment by Amazinite** [comment]
Github is for feature requests and bug reports. If you're wanting to ask a question or give tips and tricks like this, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky).

**Comment by gunqqer** [comment]
We still should have this in the wiki if it's not being that not all keybindings are shown in preferences. I figured everything out by trial and error which is fine for me but not everyone likes that

**Comment by dufferzafar** [comment]
> The biggest missing of hotkey is the possibility to switch the selected ship in the shipyard/oufitter trading interface

Currently (v0.9.7) this is done by first clicking a ship (in the shipyard/outfitter) and then pressing Left/Right arrow keys. I feel there should be a key to switch ships that doesn't require clicking one of them first. Maybe Ctrl+Left/Right?

**Comment by jafdy** [comment]
Ctrl is multi select. Also the first ship is selected by default you only need to move your mouse over to the right to start using arrow key scrolls.

**Comment by tehhowch** [comment]
I only works as an install key now, e.g. you must have the outfit in cargo.

**Comment by endless-sky** [comment]
I've added most of these to the player's manual, aside from the button hotkeys.
