### ISSUE TITLE
Feature request: missions that cost money to accept

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#263]
This could be used to, for example, create a "mission" that consisted of a piloting class whose reward was a small permanent increase in the turning ability of your flagship, or a bribe to someone for information, or similar things.

(In case it wasn't obvious, I'm writing some missions)

**Comment by endless-sky** [comment]
This can be done by having a negative "payment" in the "on accept" clause. The mission will not be offered if the "payment" would result in you having negative credits.

**Comment by Pointedstick** [comment]
Ah, perfect!
