### ISSUE TITLE
question - republic hostile

### ISSUE THREAD

**Issue by nictaylr** [endless-sky/endless-sky#2636]
i have question ( i new to game )

i start the free worlds campaign, but this make trade hard because i no longer safely pass through republic without be attack. i want to know if i finish campaign will republic be friendly again? spoiler is ok, i want to understand i should go back to before or continue in campaign, thanks much!

**Comment by Amazinite** [comment]
Github is for feature requests and bug reports. If you're wanting to ask a question, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky), or see if the answer is on the [wiki.](https://github.com/endless-sky/endless-sky/wiki)

Please close this.

**Comment by Elyssaen** [comment]
<details><summary>Spoiler</summary>Yes.</details>
