### ISSUE TITLE
You can have hyperspace based quest while Pug have taken over the planet.

### ISSUE THREAD

**Issue by 123abchelpineedausername** [endless-sky/endless-sky#2637]
This is the contingency string. The mission is "Escort convoy from Rand" this should be impossible based on the fact that there is no hyperspace links anymore.

**Comment by Bladewood** [comment]
This is basically the same thing as https://github.com/endless-sky/endless-sky/issues/2296, https://github.com/endless-sky/endless-sky/issues/1330, and https://github.com/endless-sky/endless-sky/issues/2623...

**Comment by Amazinite** [comment]
Tfw you pretty much duplicate your own issue.

**Comment by jafdy** [comment]
I don't even know what branch he is talking about.

**Comment by Bladewood** [comment]
Checkmate.

**Comment by endless-sky** [comment]
Closing this as a duplicate.

**Comment by tehhowch** [comment]
That mission string offers pretty far in advance of the Pug invasion. The issue, perhaps, is that the stresses on the player are wildly different for Reconcilation & Checkmate:
Reconciliation - offers when the player is given a 30 - day forced break
Checkmate - offers the alongside the 1st mission of the Checkmate string. Battles kick off immediately when the 1st mission is completed. These battles do move the player right next to Rand / Zeta Aquilae, and the player is given a really nice opportunity to "double down" on escorts by doing both the Nuke Supply convoy from Rasalhague to Shaula and the Stack Core convoy to Pherkad at the same time

I'm considering adding a "to fail" to the FW and FWC Stack Core 1 that references the "fwc pug invasion" event. If the "go to rand" intro mission is allowed to fail, then setting a flag when Rand is reconnected could be used for a "resume" mission.
An alternate solution is to add an appropriate `deadline` tag to the Checkmate start, to helpfully suggest to the player that they should stop by Rand while scoping out Kaus Borealis during the first mission.
