### ISSUE TITLE
Endless Sky should hint large icons to Linux window managers with the _NET_WM_ICON_NAME property to ensure that large icons are displayed when appropriate

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2645]
Endless sky provides nice huge icons. But most Linux window managers won't see and display them properly without some hints, leading to ugliness, like the following screenshot of my KDE Plasma Large Icons Task Switcher:

![not a high-res icon](https://user-images.githubusercontent.com/1097249/27257850-8c22ebde-53a4-11e7-8ab2-5095fe7d25ad.png)

Endless Sky has an upscaled 48x48 icon instead of a nice large icon like all the other programs. This is because it apparently needs to hint that information using the _NET_WM_ICON_NAME property.

For more information and context, see:
- https://github.com/gnumdk/lollypop/issues/1092
- https://bugs.kde.org/show_bug.cgi?id=351055
- https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html

**Comment by MessyMix** [comment]
Maybe relevant? #2095.

**Comment by Pointedstick** [comment]
The top-down icon I'm seeing is just what the small 48x48 version looks like. Once the necessary proposed code changes are implemented, the nicer high-res 3/4 view version should show up there.

**Comment by tehhowch** [comment]
That's better than what a `scons` source build on ubuntu 16.04 gives:
![image](https://user-images.githubusercontent.com/20871346/27258295-fb6a9ca4-53bc-11e7-9bca-ff421fd462dd.png)

**Comment by Nechochwen-D** [comment]
@tehhowch `sudo scons install` will install all images including the icons.

**Comment by tehhowch** [comment]
TIL.
so. much. better.

**Comment by endless-sky** [comment]
See if 99d9bcd fixes this for you. (If not, I'll probably revert that change, because I worry that any code that messes with X11 so directly could mess up other Linux desktop environments or keep the code from even building.)

**Comment by Pointedstick** [comment]
Doesn't change anything for me. That kind of low-level X11 code scares me too, since I can see the fragility and it's certainly not going to be forward-compatible with Wayland.

Installing all the game content to / with `sudo scons install` likewise doesn't change anything, though I can verify that it does install a nice large icon in /usr/local/share/icons/hicolor/256x256/apps/endless-sky.png. If only that icon were used...

There must be a better solution. Maybe it's SDL's job to provide this hint?

**Comment by Pointedstick** [comment]
FWIW, this gets fixed automatically with Wayland, because the Wayland window manager spec requires the use of icons from applications' Desktop files, rather than trusting windows to provide their own icons via _NET_WM_ICON_NAME.
