### ISSUE TITLE
Trove isn't a moon

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2651]
[Trove](https://github.com/endless-sky/endless-sky/blob/master/data/map.txt#L26880) is a landable object described to be a moon and has a moon attribute, but [it isn't a moon of any planet](https://github.com/endless-sky/endless-sky/blob/master/data/map.txt#L11021). It's just a really small planet.

**Comment by endless-sky** [comment]
Fixed in 0e2c590.
