### ISSUE TITLE
Development Version

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2660]
Is there a possibility of creating a game development version that can reload edited data files?  Map.txt or outfit.txt for example.
This would be selected files not all at once.

**Comment by Bladewood** [comment]
Just make backups of the files.

**Comment by tehhowch** [comment]
@Bladewood i think VonZorch means "The game is running, and i changed something in the data files. Without closing and relaunching the game, how can i give it new information?"

**Comment by VonZorch** [comment]
Yes, exactly.  It would save significant time when creating and testing new content.  Especially when, like me, you have only a vague, at best, knowledge of the game mechanics.
I once spent about 4 hours deciding that something I was trying to do with a new outfit wasn't going to work.  Most of the delay was closing and restarting the game.

**Comment by tehhowch** [comment]
It would probably be easier to allow the player to edit attributes in-game, rather than try to load a specific file.

Something could maybe be done using the -d command line flag to have the backtick expose a prompt for data entry, but I haven't done anything like that so you'll need someone better.

My game starts up within about 10 seconds (laptop hdd on battery...), so try playing without the steam cruft in the  meantime

**Comment by VonZorch** [comment]
Loading takes me about  5 to 10 seconds with the freshly compiled latest commit on Debian Linux.

**Comment by endless-sky** [comment]
If you've got the high-DPI plugin installed, you can speed up the load time significantly by removing / disabling it while testing. (On my computer, loading takes less than a second, but I've got an SSD.)

Reloading the data files would be relatively simple, but I think players would then expect graphics to reload as well, and would get confused when they don't. (Or if they do, you might as well just restart the game.)

**Comment by VonZorch** [comment]
I'm not using the high-DPI plugin, just a somewhat elderly laptop.

I must not have clear, what I'm asking about isn't a modification to the normal game most players use but a separate version for use by content creators.
It should also be able to reload graphics and specify non-standard locations for data and save files.

**Comment by endless-sky** [comment]
Specifying non-standard locations for the game resources and save files is already a command line option:

```
    -h, --help: print this help message.
    -v, --version: print version information.
    -s, --ships: print table of ship statistics.
    -w, --weapons: print table of weapon statistics.
    -t, --talk: read and display a conversation from STDIN.
    -r, --resources <path>: load resources from given directory.
    -c, --config <path>: save user's files to given directory.
    -d, --debug: turn on debugging features (e.g. caps lock slow motion).
```

**Comment by VonZorch** [comment]
Thanks for the information.  Is there somewhere I can get a detailed list if debugging features?

**Comment by tehhowch** [comment]
Right now debug mode simply tells you which file is getting parsed during the startup process, and turns caps lock into slow-motion mode instead of accelerated mode.

**Comment by VonZorch** [comment]
Thanks.
