### ISSUE TITLE
Luxury Transport

### ISSUE THREAD

**Issue by TurkeyMcMac** [endless-sky/endless-sky#2661]
I think it would be interesting if there were outfits one could add to a ship so that it would attract richer passengers with higher expectations and more money to spend.

**Comment by tehhowch** [comment]
You can already make missions that will only offer if you have specific outfits in your fleet. This means you could make a mission and then a variant of it that pays more money, requires more available space, and has a farther destination than the base variant, and only offers if you have a specific outfit.

**Comment by MessyMix** [comment]
@tehhowch and has bigger and badder bounty hunters. :)

**Comment by jafdy** [comment]
Something like this exists with quantum keystones (or is it quantum key stones) in Hai space.
