### ISSUE TITLE
Electron Beam Balance Issues

### ISSUE THREAD

**Issue by LanadJer** [endless-sky/endless-sky#2662]
Right now, it looks like the Electron Beam is essentially the Bactrian of weapons. Anyone who's seen my [spreadsheets](https://drive.google.com/open?id=0B-tBvnBBsyPIc1BadXREOUQ4VHc) will probably have discovered that it's incredibly efficient in terms of energy usage and heat production, capable of dealing huge amounts of both shield and hull damage while fitting in a relatively small package. **And it's manufactured by the Deep**. According to [this](http://imgur.com/zRUAC3C) (weapons in order of efficiency offset by Large Reactor Modules and Large Heat Shunts), the Electron Beam is the second most efficient fixed firing weapon and the fourth most efficient turreted weapon in the game.

The only weapons that consistently outperform the Electron Beams have their own set of issues.

- The Quarg Skylance is the rightfully the most powerful weapon available, it is somewhat difficult to obtain and lowers your relationships with the Quarg.

- The Bombardment Cannon and Turret has the same issue as the Skylance and despite being incredibly efficient, it is very small and outfitting an entire ship with it will leave much of the outfit space unusued.
- 
- The Pug Gridfire Turret is rare and seems like more of a gimmick than anything else due to the shield piercing ability, essentially being worse than the Skylance in every way.
- 
- The Wanderer Sunbeam, which seems like it should be far more effective than the Electron beam has a lower overall efficiency due the low hull damage and incredibly high energy requirements.

The Electron Beam doesn't suffer from any of these issues. It can be easily bought instead of being looted from difficult enemies. The issue with Bombardment turrets does not apply either, as every ship (spare the Wanderer ships), have enough weapon hardpoints to be completely outfitted with Electron Beam and Turrets. Right now, it doesn't seem like there's any point using any other weapons.

Just wanted to point this out, since I don't think I've seen anyone complain about this issue, no suggestions for actual balance changes from me.

**Comment by TheUnfetteredOne** [comment]
The spreadsheets just show a bunch of errors for me. "#ERR!" next to all the weapons.

**Comment by Startome** [comment]
Yeah I got a failed to open as well. However that being said. I've seen some seriously complicated primary weapon spreadsheets and the electronic beam is intentionally balanced to be one of the higher grade T1 weapons. Can you reply with the precise numbers you feel show this misbalance, or a screenshot of the spreadsheet?

**Comment by Hadron1776** [comment]
![weapon outfits](https://user-images.githubusercontent.com/24595528/27414010-e9356440-56bb-11e7-9434-667a715860dd.jpg)
![turret outfits](https://user-images.githubusercontent.com/24595528/27414013-ee7077ba-56bb-11e7-8228-4e870f81653d.jpg)

**Comment by Startome** [comment]
This way of looking at balancing weapons leaves out well over half the factors that matter. 
https://drive.google.com/file/d/0B4dH3myjjPqdcUI5NW9RQ2NCYWM/view?usp=drivesdk
There is a link that takes almost all the factors into account.

**Comment by Hadron1776** [comment]
The picture on the first page of that link is so _tiny_ and I can't read it...

**Comment by Startome** [comment]
It's a google drive link. Those are designed to.be zoomed and manipulated any way neccessary if using a capable program to view it. (So far any Internet browser I've tried has worked, what are you using?)

**Comment by Bladewood** [comment]
I personally don't see anything wrong with electron beams, other than [this...](https://github.com/endless-sky/endless-sky/issues/1607)

**Comment by Startome** [comment]
The prices could use tweaking I agree, however it seems fairly minor to me as far as balancing issues, and comparing to the bactrian, are concerned. I just really feel like this entire issue is being argued from part of a picture, not the whole.

**Comment by TheUnfetteredOne** [comment]
How are you measuring "efficiency"? We can't fix a problem when we don't know where the problem apparently exists.

**Comment by LanadJer** [comment]
If you can at all, try downloading it and opening it from a desktop app. There's a lot there that you can't see from the image. I've fixed the image resolutions, should be available [here](http://imgur.com/a/iMwKe).
This is not based purely on damage per outfit space, it takes into account much more. Efficiency is calculated by adding up the outfit space required to offset heat produced and energy required based on already calculated efficiency, which produces a more accurate representation of how much outfit space it actually requires, and then calculates the damage per ton of outfit space. What I've done is better explained [here](http://steamcommunity.com/sharedfiles/filedetails/?id=879815070).

**Comment by tehhowch** [comment]
I don't see any measure of the range of the weapon, applied hitforce, ion damage, heat damage, slowing damage, or disruption damage. If my guns are longer-range, and keep you from getting close enough to use yours...

While you can argue that an outfit is the best, when you ignore large parts of that outfit, your argument is not very strong.

**Comment by LanadJer** [comment]
That's why minimum offset exist in the spreadsheet. It's a calculation of how much outfit space is required by your target to offset the damage you deal. This actually does take into account heat and ion damage. While you are absolutely right in that range and movement disruption is important, the sheer damage capabilities of the electron beam is ridiculously high. 

Have you looked at the spreadsheet formulae/guide? There's some information there that you might find helpful.

**Comment by TheUnfetteredOne** [comment]
Gonna copy paste what I said elsewhere.
<hr/>
The thing is, in a battle of a ship using Sunbeams vs a ship using Electrons, the Sunbeams are going to win, even if the Electrons take up less energy and heat for the same damage output as the Sunbeams. It's not that Electrons are "OP" by damage, they're "OP" by how little energy an heat they require to run, and not overly OP in that sense either (since like you pointed out, there are weapons that rank higher in efficiency for your equations).
<hr/>
Something I will point out, using Derpy's sheets, we can see the following:
Beam Laser: 0.22 energy/dmg and 0.52 heat/dmg
Heavy Laser: 0.24 energy/dmg and 0.52 heat/dmg
Electron Beam: 0.22 energy/dmg and 0.38 energy/dmg 

If we want the Electron Beam to follow the pattern of the Heavy and Beam Lasers (same heat/dmg and slightly increased energy/dmg) instead of becoming straight up better than the Heavy Laser, then it needs to take 106 energy/second and produce 212 heat/second.

**Comment by LanadJer** [comment]
With this change, the electron beams are 0.39 less efficient overall per ton, with a 6.1% decrease in efficiency.

**Comment by endless-sky** [comment]
I'm not sure how you're defining "efficiency." In general, most ships have more shields than hull strength, so shield damage is more important than hull damage. Sunbeams do 12.7 damage per second per ton, compared to 8.3 for Electron Beams. For the turrets the difference is even larger: dual sunbeams do 10.4 and single sunbeams do 9.4 shield damage per second per ton, compared to 6.4 for an Electron Turret.

**Comment by Amazinite** [comment]
The Electron Beam has a shield/hull ratio of 0.74, while the Sunbeam has a shield/hull ratio of 2.40.
Given that almost all ships have a shield/hull ratio above 1 (with very few exeptions*), the Sunbeam is ultimately better than an Electron Beam in terms of burning down a ship's hitpoints, so I think the Electron Beam is warranted in being highly energy and heat efficient.

\* exceptions include: the Shuttle, Nest, Roost, and Skein, all Sestor ships\*\*, Star Barge, the Bulk Freighter, all 3 Haulers, all Arach ships, all drones, and the Boxwing.

\*\* The only exception to this is the Tek Far 109

**Comment by Lineth** [comment]
I generally get plasma weapons anyway for the reasons outlined by @endless-sky  and @Amazinite  above. Less efficient, yeah, but thy do more shield damage and the heat damage is all but mandatory for T1 ships to take on Korath ships with any reliability.

**Comment by LanadJer** [comment]
If you don't know how efficiency is defined, you haven't been looking. The formula is here once again.
Overall Efficiency = (Hull Damage + Shield Damage)/(Mass + (Heat Produced/Cooling Efficiency) + (Power Required/Power Generation Efficiency))*2

Additionally, 
Shield Efficiency = Shield Damage/(Mass + (Heat Produced/Cooling Efficiency) + (Power Required/Power Generation Efficiency))
Hull Efficiency = Hull Damage/(Mass + (Heat Produced/Cooling Efficiency) + (Power Required/Power Generation Efficiency))

The point about the shield/hull ratio is correct, a weapon would generally be more powerful with more shield damage than hull damage. However, the shield damage efficiency (see formula) of the Sunbeam is 6.72, which is slightly higher than Electron Beam's 5.78, while the hull damage efficiency of the Sunbeam is a mere 2.80, compared to 7.78 from the Electron Beam.

If we scale down a Sunbeam to the size of an Electron beam, taking into account efficiency, the damage would be 234/84. Looking at it this way, it's not difficult to see which one would be more effective in combat. Also confirmed in experiment, where 8 Sunbeams can kill a stock bactrian in 24.75 seconds, the Electron Beam takes 17.30. These are only the preliminary tests, more coming soon (hopefully).

**Comment by Amazinite** [comment]
>If we scale down a Sunbeam to the size of an Electron beam... the damage would be 234/84.

You sure about that?
Sunbeam: 34 tons
Electron Beam: 21 tons
34/21 = ~1.62
A Sunbeam has 432 shield DPS and 180 hull DPS.
432/1.62 = 266.67 downsized shield DPS
180/1.62 = 111.11 downsized hull DPS

>Also confirmed in experiment, where 8 Sunbeams can kill a stock bactrian in 24.75 seconds, the Electron Beam takes 17.30. These are only the preliminary tests, more coming soon (hopefully).

No need to confirm in experiment because you can confirm in math.
```
Bactrian: 
	17,500 shield
	8,600 hull
	
Sunbeam:
	432 shield DPS (40.5 sec)
	180 hull DPS (47.8 sec)
	Combined total of 88.3 seconds for one Sunbeam to kill a Bactrian

Electron:
	174 shield DPS (100.6 sec)
	234 hull DPS (36.75 sec)
	Combined total of 137.55 seconds for one Electron Beam to kill a Bactrian

A Sunbeam kills a Bactrian about 1.56 times quicker than an Electron Beam.
```
So I don't know where you're getting your numbers from.
