### ISSUE TITLE
Visiting Danforth on Farpoint text doesn't change based on checkmate branch

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#2663]
Played through the checkmate branch recently, was surprised when Danforth says this:
![screenshot from 2017-06-21 22-34-36](https://user-images.githubusercontent.com/20472439/27413563-8c6e0d9a-56d2-11e7-8a4d-6f703f8df5ab.png)
![screenshot from 2017-06-21 22-34-27](https://user-images.githubusercontent.com/20472439/27413564-8c6ede8c-56d2-11e7-894a-1fe6cb557312.png)

Danforth shouldn't know about the Syndicate's involvement with nukes if you've taken the checkmate line, and the player only has a vague idea/hints about their exact involvement based on what the defector said he mad before they turned him over.

**Comment by MessyMix** [comment]
#2665 good catch.

**Comment by Amazinite** [comment]
On the topic of epilogue, it might be worth giving Tomek an epilogue mission for Checkmate players (and maybe even for Reconciliation players so we can know that he isn't under perpetual house arrest).

**Comment by jlnxr** [comment]
I agree with that- seems odd that the situation that leads the Senate to reinstate him- the battle over Thule, and the escalation of the war, albeit against a different enemy- happens in both story lines and yet in the reconciliation one he is just left rotting away in house arrest as far as the player is concerned.

**Comment by Amazinite** [comment]
Finished in 8123622 by having Danforth not mention the Syndicate at the beginning of the epilogue, and near the end instead of talking about Raven finding the extremists, he talks about the nukes that the Free Worlds still have.
