### ISSUE TITLE
Landed NPCs do not repair hull or shields

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2667]
When an NPC lands (e.g. a mission escort, or your own player-owned escort), the only thing it gains more of is fuel.

Should they also stay landed until they have fully repaired their hulls and shields if they have been damaged (to say, `Hull() + Shields()/2 = health = 0.6`?)

This could also be made an NPC personality, such that if they are sufficiently damaged they will choose to retreat and land on an accessible planet. (`replenishing`? `repairing`? `retreating`?)

**Comment by jafdy** [comment]
Giving a land-when-damaged personality could be a great enhancement for the tribute fleets as well as defending fleets in some story mission.

**Comment by tehhowch** [comment]
I can pretty easily implement both, but we'd need a nice and forward-compatible `personality` keyword.

 - `repairing` or `repairs`
Probably not this, as if there is ever a supporting class of ships, this keyword would imply that this ship will opt to repair its allies
 - `replenishing`
Maybe. It wouldn't be immediately intuitive if you saw this on an NPC definition what exactly gets "replenished".
 - `resupplying`
Like `replenishing`, not obvious what the "supply" is that is being referenced. Could be interpreted as a ship that boards allies and gives ammunition outfits.
 - `retreating` or `retreats`
A good candidate, but doesn't intuitively convey what it would mean to 'retreat', as some could expect that to mean it jumps out of the system if heavily damaged / outnumbered. Depending on what `fleeing` is supposed to mean, vs what it actually does ( #2658 ), there can be some confusion / expectation overlap.
 - `regrouping` or `regroups`
Another good candidate, but could be expected to mean that it attacks only in groups (which is kind of like `timid`).
 - `landing`
Another good candidate, and accurately portrays what the NPC would do. Doesn't imply `why` the NPC would land, though.

**Comment by Pallington** [comment]
`refitlanding` or `repairlanding`?

**Comment by tehhowch** [comment]
Here's the list of current personalities for comparison with naming:
https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities

`refitlanding` and `repairlanding` don't fit the existing schema, but it is OK to redefine the schema.

**Comment by tehhowch** [comment]
Experimenting with some possible recharge formulas on all in-game variants except Archons, Hallucination, Timer Ship, and Nanobots (don't see these things landing ...)
Fuel recharge is calculated as `capacity - 99`, as it gains 1 per frame, period.
Hull repair time is calculated as that needed to go from the variant's `MinimumHull+1` to full hull.
Shield repair time is calculated as that needed to go from 0 to full shields.
Plots indicate the limiting time, e.g. if shield time > hull time, that variant is counted among the shield series, and won't take off until its shields are fully charged, even if its hull is fully repaired. Thus these plots portray the maximum time a non-player escort would be landed. Player escorts would almost certainly land for less time than equivalent tier NPCs, since the player often has much higher recharge values.

<details><summary> gain per frame = 1 + 3 * < generation > + < max capacity > / < mass ></summary>

Average Hull Repair Time: 8.8 seconds (std.dev 6.8)
Average Shield Repair Time: 9.1 seconds (std.dev 5.8)
Solifuge escort [36 | 282]: 16 sec hull, 17 sec shields

![image](https://user-images.githubusercontent.com/20871346/27494544-f0dbf520-5813-11e7-83df-f7a98c7bf6e0.png)
</details>
<details><summary> gain per frame = 1 + 1 * < generation > + < max capacity > / < mass ></summary>

Average Hull Repair Time: 9 seconds (std.dev 7.1)
Average Shield Repair Time: 11 seconds (std.dev 7.5)
Solifuge escort [36 | 282]: 18.6 sec hull, 23 sec shields

![image](https://user-images.githubusercontent.com/20871346/27496385-59ccaed8-581b-11e7-8eb6-64507fc81811.png)
</details>

<details><summary> gain per frame = 1 + 10 * < generation ></summary>

Average Hull Repair Time: 77 seconds (std.dev 140)
Average Shield Repair Time: 14 seconds (std.dev 9.7) 
Solifuge escort [36 | 282]: 21 sec hull, 13 sec shields

![image](https://user-images.githubusercontent.com/20871346/27494612-4d78c90c-5814-11e7-9406-ccd1dd115445.png)
</details>
<details><summary> gain per frame = 2 + 10 * < generation ></summary>

Average Hull Repair Time: 42 seconds (std.dev 70.5)
Average Shield Repair Time: 12.4 seconds (std.dev 8.6) 
Solifuge escort [36 | 282]: 18.3 sec hull, 12.9 sec shields

![image](https://user-images.githubusercontent.com/20871346/27496163-80f10938-581a-11e7-9907-332231335ab7.png)
</details>

Feel free to download the spreadsheet and futz about with different formulas: https://drive.google.com/file/d/0B2jPxN6TDvXPMWlMLUIyY3B6LUE/view?usp=sharing

**Comment by Pallington** [comment]
schema being 1 word only, huh?
The issue is that 1 word is a lot too generic without some serious dictionary raiding to give a suitable word.
`damagecontrol`?

**Comment by tehhowch** [comment]
Here's a branch that has an example retreating personality (at .75 health it stops targeting and assisting, and tries to either land, or jump away)
https://github.com/endless-sky/endless-sky/compare/master...tehhowch:NPCsRepairOnLand?expand=1

**Comment by tehhowch** [comment]
If we decide that ships should repair and recharge fuel while landed at a spaceport, it would make sense to have a fleet order that could force a ship to land. This would also allow the player to tell ships to (try to) refuel, independently of the AI logic behind refueling.

**Comment by tehhowch** [comment]
Came across #367 , which brings up some balance points about regen of health and shields at planets:
1) it's already "cheating" for the AI to refuel as fast as it does while only taking a few seconds
2) If you've subjugated/bribed the local planet, you can heal captured ships with a greatly lowered risk of losing them

In that light:
 - Player escorts only recharge what they can naturally recharge (e.g. only those with hull regen repair hull), and only at their natural rate (or maybe tiny increase of +1 per frame, since they have landed after all)
 - NPCs with the defender personality happily retreat to land when hurt (player is required to pursue and destroy, not simply sit on the boundary), and repair both shields and hull at an accelerated rate
 - NPCs with the aforementioned new personality would also retreat to land when hurt, and repair both shields and hull at an accelerated rate.

These additions would have the effect of increasing the difficulty of the tribute mechanic (more satisfying/challenging fights for end-game / i-beat-the-game players), making new missions / jobs possible (via the new personality & behavior), and increasing the tactical choices available to the player (via a fleet order to make an escort land, plus slow recovery of shields/hull).
The first two can be separated from the changes to the player's escorts (a simple ship->IsYours() check before the repair functions are called).

**Comment by Musaran2** [comment]
>  but we'd need a nice and forward-compatible personality keyword

pit_stop ?

**Comment by petervdmeer** [comment]
> I can pretty easily implement both, but we'd need a nice and forward-compatible `personality` keyword.

A bit late, but here some additional suggestions: reviving, resting, recouping, recovering, restoring

**Comment by Tadrix** [comment]
`returning`?

I'm not sure if increased regeneration compared to player's ships is a good thing. Invokes the AI being a cheating bastard, which might be important if the player doesn't have a giant fleet of doom. I'd advocate for a level playing field.

**Comment by Amazinite** [comment]
I don't think that this is a mechanic that we need. This would essentially be a means for ships with these personalities to have overpowered shield regen/hull repair on standby if you are fighting ships with this personality in a system where they can land. The same would true of your own allies when fighting in a friendly system. Essentially, this would just throw the shield regen/hull repair balance of combat out of whack.
