### ISSUE TITLE
Ship flashing between disabled and normal

### ISSUE THREAD

**Issue by 123abchelpineedausername** [endless-sky/endless-sky#2673]
Sometimes a ship escort or other will flash between disabled and normal. It does not seem to actually affect how the ship works, but just appears in the icon.

**Comment by Hadron1776** [comment]
Is the ship overheated? Ships will flash now if they're overheated...

**Comment by Amazinite** [comment]
It's overheating. Add some cooling outfits or reduce the number of heat generating outfits.
Please close this issue.

**Comment by 123abchelpineedausername** [comment]
Ok just found it confusing because the ships did not act overheated and that it happened to Navy ships fighting the Pug.
