### ISSUE TITLE
Outfits unabled to be uninstalled don't show depreciation

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2674]
On my ship I have installed an outfits expansion. I have 13 spare outfit space, meaning I can't get rid of the outfits expansions. The outfits expansion currently shows no depreciation.
![screenshot_233](https://user-images.githubusercontent.com/17688683/27513685-01a05c54-593e-11e7-8b6c-0eca76452385.png)
But as soon as I make enough space, the expansion now shows how depreciated it is.
![screenshot_1](https://user-images.githubusercontent.com/17688683/27513688-0e1451d4-593e-11e7-9532-7e27baf986ae.png)
I then checked to see if it was more than just the outfits expansion, and this is the case on the Arfecta's cloaking device as well.
![screenshot_3](https://user-images.githubusercontent.com/17688683/27513701-809ea06a-593e-11e7-92ab-a35a527dcca4.png)
Is this intended behavior?

**Comment by 123abchelpineedausername** [comment]
In my opinion the cloaking device in the Arfecta shouldn't show depreciation due to the fact that it is impossible to remove and sell independently, but expansions should because you can actually remove them.

**Comment by Bladewood** [comment]
The Cloaking Device is exempt from depreciation, and Michael is aware of it.
https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/eKeOvErGhFQ mm, but this is the only source I have, I don't know where the one that specifically mentions the Arfecta's cloaking device is.

**Comment by Bladewood** [comment]
Last I read, it was intentional on the Arfecta's cloaking device.

**Comment by tehhowch** [comment]
https://github.com/endless-sky/endless-sky/commit/e278ffa5d7c79ea3b1d79ef58cc60017f89dad07

Seems intentional. If you can't possibly sell it, why does it matter what it is worth?

**Comment by Amazinite** [comment]
Because like with the outfits expansion, it's sellable, just not in that moment. It's kind of annoying to go through the hassle of removing other outfits just to check how much my oufits expansion is currently worth.

Seeing as how it is intentional I'll just close this.
