### ISSUE TITLE
Outfitter and repair ship

### ISSUE THREAD

**Issue by minecraft2048** [endless-sky/endless-sky#268]
So basically a ship that is 10x larger than Bactrian, 10x heavier than Bactrian, 30x more expensive than Bactrian, 2x more weapons than Bactrian, but any ships that dock with that can refuel, repair and install most outfits

**Comment by gchapyzh** [comment]
Maybe have it as a non-playable ship, with weapons just for defense, but good shielding. You would probably find these wandering around outer systems with large fleets. Could be an interesting set of quests: Find the Megaship. Find so and so on the Megaship. Get these resources to the Megaship. Protect the Megaship!

**Comment by Wrzlprnft** [comment]
Call it the Arch, and send it in the not-yet developed part of tha galaxy, as a backup for humanity.
Storyline: protect it from the Drak and others, once they discover it.

**Comment by gchapyzh** [comment]
Gift from pug? TO STOP THE HACKSAW?

**Comment by Wrzlprnft** [comment]
Lol.
there's enough space for all that, just write it :)

**Comment by gchapyzh** [comment]
:disappointed_relieved: BUT I CANT CODE ON C++

**Comment by Wrzlprnft** [comment]
Me neither, well not good enough that i would try to contribute something... but..
there's a map editor, and missions...
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions
they are in plaintext. (plaintext here referring to the file format, it's written "they way the game understands it")
The programm just imports all the missions and stories.

**Comment by airtroop392** [comment]
AI War has something similar- they have the train from the original Transformers series fly through the universe and mess with your bases, and it's practically invincible. Other than the fact that it's a train and that it actually harms the player, it's pretty spot on to what you're suggesting- it roams around the universe and it does things like support the enemy's fortifications.

**Comment by jafdy** [comment]
Perhaps do it like the top comment but with no weapons at all and very very very very slow.

**Comment by gchapyzh** [comment]
@jafdy  Heaving no weapons at all makes the ship very vulnerable to missiles. A certain defensive armament is necessary. A battery on one side, a battery on the other.

**Comment by jafdy** [comment]
That was the point.
If it wasn't vulnerable then everyone would want one.

**Comment by GoldenDalek** [comment]
So it would be like a moving space station...

**Comment by jafdy** [comment]
exactly!

**Comment by endless-sky** [comment]
I'm closing this thread as a part of cleaning up the issues list to focus on threads that are active and higher priority.
