### ISSUE TITLE
Don't spawn raids if reputation with the raid fleet government is positive

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2682]
Currently I'm using two dozen freighters to space truck around the galaxy selling commodities like the good merchant that I am, and as expected, every system I enter has a massive pirate fleet that clears the system of other merchants or of the local militia and/or Navy fleet. The thing is, I boarded two Korath Raiders early on in my career just to get pirates friendly with me so I didn't have to deal with pirates trying to steal my credits. This means that the pirate raids don't attack me, and only stand to increase my CPU usage and thus slow down my game. 

Requested that raids don't spawn if the player's reputation with the government of the fleet of said raid is positive. This is because 1) without those pirates being destroyed by the player's fleet, they only act as an annoyance and a drain on CPU usage, and 2) the whole reason for raids to show up is to attack the huge freighter convoy they hear about, but when they show up they aren't attacking it, so in lore it doesn't really make sense for them to show up in the first place.

~~Or screw me over and switch raid fleets to bounty hunters.~~

**Comment by tehhowch** [comment]
Sorry... Bounty Hunters make sense, especially if you have no available "normal" negative-rep opponents.

But anti-trader spawned fleets is a key early-game balancing point that I don't believe considered positive rep, so I'm going to leave any resolution on this to MZ.

**Comment by Amazinite** [comment]
Yeah, while writing the issue I thought of how changing the government of the current only raid fleet to bounty hunters would also technically fix the issue I'm having, so I threw it in at the end. It isn't ideal for a space trucker, but I'd say it's the more correct fix in terms of gameplay balancing. Even then, I could still just make my way to Hai space and avoid pirate raiders all together,

**Comment by jafdy** [comment]
Change raids to ` Pirate `. Or give pirates a 0.05 rep with Korath.

**Comment by Amazinite** [comment]
>Or give pirates a 0.05 rep with Korath.

Alright, now we've gone too far.

**Comment by endless-sky** [comment]
Fixed in 252345b.

**Comment by Amazinite** [comment]
Awesome.
