### ISSUE TITLE
Plot holes in FW Intro

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2685]
I've noticed two errors in the Free Worlds intro where the game assumes that you've met certain characters before, and there are no branches in place to change conversation based on who you've actually met or not. I'm going to lay out some information just so you can see what I mean.
<hr/>

**Pact Recon**: Introduces you to Freya
**FW Escort**: Introduces you to Tomek
**FW Escort Second Chance**: Introduces you to Alondo early, and assumes you've met both Katya and JJ
**FW Recon**: Introduces you to JJ
**FW Bounty**: No character introductions
**FW Katya**: Introduces you to Katya.
<hr/>

**Pact Recon** can only be done before the war.
**FW Escort** requires that you've helped the Free Worlds in one other occasion (this could have been by doing the FW Katya string or by doing FW Recon or Bounty).
**FW Escort Second Chance** offers if you fail FW Escort at any point and have helped the Free Worlds on two previous occasions.
**FW Recon** requires that "event: initial deployment 4" have been triggered.
**FW Bounty** requires that the player have a combat rating above 200.
**FW Katya** only requires a random value to trigger.
<hr/>

**FW Commitment** requires an `assisted free worlds` value of 3 or greater, and that FW Katya is done. Each of the above mission strings mentioned that is prefixed with FW increases your `assisted free worlds` condition when done. This means that you can have up to 4 of that condition. Thus, the player is able to not do one of the three minor FW intro strings and still get the commitment.
<hr/>

**Rescue Katya 1**, which you get after choosing sides, assumes you've met all of the council members (Freya, Tomek, JJ, and Katya), excluding Alondo. 
<hr/>

Here's where the holes exist:
1) Since only 2 of the 3 minor intro strings need to be completed for the player to reach FW Rescue Katya 1, the player may have never met Tomek or JJ
2) Given that Freya can only be met before the war, the player may have never met her if they hadn't been around the Rim and South enough.
3) The player could have met Alondo before, assuming they were given FW Escort Second Chance, but Rescue Katya 1 always assumes that the player has never met Alondo.
4) On the topic of FW Escort Second Chance, it assumes that the two times you help the Free Worlds before were FW Katya and FW Recon, which may not exactly be the case. The player could have reached this point doing FW Katya and FW Bounty or FW Bounty and FW Recon, meaning they'd never have met either Katya or JJ. 

So the missions in question here are FW Escort Second Chance and Rescue Katya 1. This could be fixed by doing the following.
1) Making FW Commitment offer when you have 4 `assisted free world`s. Probably not the best option since it's purposeful that you can fail/not do one of the intro strings.
2) Having FW Escort Second Chance either only offer when you've finished the FW Recon and FW Katya strings or have a conversation branch that checks which of the two characters you haven't met before and excludes them from being mentioned
3) Having branches present in Rescue Katya 1 that check to see if FW Escort Second Chance was offered and if Pact Recon was done, and changing the introductions of Alondo and Freya accordingly.
4) If number 1 isn't done, then we would need to have additional branches in Rescue Katya 1 to check if Tomek or JJ were not met before, and change how they are introduced.
<hr/>

I went over this a few times with some other people just to make sure I'm not going crazy on this, because this seems like a few pretty big holes that would be noticed before. I think I've nailed down why this hasn't been brought up before though:
1) FW Bounty probably isn't that common to get since it requires the player to fight a lot early on, so plot holes 1 and 4 probably aren't common either.
2) I doubt many people fail FW Escort then get offered the second chance so plot hole 3 is likely uncommon as well.
3) Plot hole 2 is very subtle (players might not notice that a new character was thrown into the mix with no introduction aside from Freya's name being mention in FW Commitment), so I doubt many have noticed it, let alone cared to bring it up.

I only just noticed this today because I did a playthrough where I flew around making millions before joining the Free Worlds. I had done FW Katya, FW Recon, and FW Escort, but not Pact Recon or FW Bounty. I noticed that Freya got no special introduction like Alondo did since I didn't meet her, then surfed through the file some more and found the other issues.

Edit: This also makes it seem like FW Bounty and FW Escort Second Chance were written and added after everything else was done.

Double edit: Just surfed the commits and it looks like they were.

**Comment by endless-sky** [comment]
Commit 9328984 should address this, mostly by glossing over which members of the council you have or have not met instead of specifically stating that you have not met Alondo yet.
