### ISSUE TITLE
"Wanderers: Alpha Surveillance A": mention in conversation that you have to go to Hai-home

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2686]
https://github.com/endless-sky/endless-sky/blob/master/data/wanderers%20start.txt#L690
I've been a little worried about this for a while.
http://steamcommunity.com/app/404410/discussions/0/312265782623446022/#c2592234299560122285
The problem here is that it is never explicitly mentioned to the player in the conversation at Vara K'chrai, or anywhere else other than the mission description, that he has to go to Hai-home for additional information and to continue the storyline.

**Comment by endless-sky** [comment]
Fixed in 89622c9.
