### ISSUE TITLE
Loss of salary when disobeying Senate never reinstated until much later

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2687]
In FW Start if the player decides to disobey the Senate, their salary is cleared. They are then left without work for the next 50 days until `event "navy occupying the south"` is triggered and they are asked to work for the Free Worlds again. Aside from the fact that no one really makes any mention of you having been suspended from the Free Worlds but they need you now (a topic for another time), you are never given back your salary when you start working for the Free Worlds again. 

Only upon finishing "FW Northern 3" maybe a third of the way into FW Middle is the player given a salary back, and it is the increased salary of 2,500. So from the end of FW Start to a third of the way through FW Middle, the player could possibly be doing work for the Free Worlds with no salary if they had disobeyed the Senate. This doesn't exactly seem intentional. I would at least expect the player to return to doing Free Worlds work at a lower salary than before.

Edit: putting `"salary: Free Worlds" = 800` in the `on accept` of "FW Diplomacy 1B" and having Alondo mention it to you if you have `"fw pirates: disobeyed senate"` would make sense.

**Comment by endless-sky** [comment]
The loss of salary is intentional. You don't get it back until you've contributed enough, and shown yourself to be useful enough, that they decide to reinstate your salary.

**Comment by Amazinite** [comment]
Alright.
