### ISSUE TITLE
"1 tons of outfits" in cargo

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2688]
On the trading panel it says I have "1 tons of outfits" in my cargo
![screenshot_239](https://user-images.githubusercontent.com/17688683/27766096-228b4302-5e93-11e7-9dee-4fc396b71c49.png)
Aside from the fact that it says "1 tons" instead of "1 ton," I actually have 0.4 tons of outfits in cargo.
![screenshot_1](https://user-images.githubusercontent.com/17688683/27766102-36d326cc-5e93-11e7-8ba7-fd7bdba29cea.png)
It seems like it says 1 tons because it should be saying 0.4 tons, but it's rounding up to the nearest whole number.

**Comment by endless-sky** [comment]
Fixed in 7f5e95e.
