### ISSUE TITLE
With multiple illegal jobs, you can only get fined for one at a time

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2689]
Say you have 10 pirate jobs, all with fines attached to them if you get scanned. Right now, if you do manage to get scanned, you will only get fined for one of the jobs and the other 9 jobs will not result in the player being fined.

It would make more sense that you get fined for all 10 at the same time, but seeing as how that could cause dialog box clutter (having to hit cancel or ok 10 times to get rid of all the boxes), the dialog box should probably combine all the fines and display what you've been fined in a single dialog box. Then there's a question of what should be done with illegal messages (e.g. for stealth missions with special messages when you get fined). Should those appear in multiple boxes, or should only one of them appear as what shows up in the dialog box?

**Comment by tehhowch** [comment]
Given the time @Hardon1776 spent with the fine system, maybe he will make a PR to address this.

I certainly agree that you should be fined for each different illegal mission cargo /substance you are carrying. I also agree this dialog should only appear once.

The dialog box can have two sections, with the top mentioning the fines, and the bottom mentioning the number of missions that failed due to the scan.
Perhaps we should create a mission fail dialog snippet specifically designed for failed illegal mission scan dialog concatenation, and this snippet can be displayed to better convey which mission failed. (An `on scan` condition?)

**Comment by tehhowch** [comment]
I did a little reviewing, and it seems this is already done?
[Politics.cpp:226](https://github.com/endless-sky/endless-sky/blob/c451d28a227163448ad30539284d1554660492e9/source/Politics.cpp#L226)
```
if(!scan || (scan & ShipEvent::SCAN_CARGO))
{
	int64_t fine = ship->Cargo().IllegalCargoFine();
	if((fine > maxFine && maxFine >= 0) || fine < 0)
	{
		maxFine = fine;
		reason = " for carrying illegal cargo.";

		for(const Mission &mission : player.Missions())
		{
			// Append the illegalCargoMessage from each applicable mission, if available
			string illegalCargoMessage = mission.IllegalCargoMessage();
			if(!illegalCargoMessage.empty())
			{
				reason = ".\n\t";
				reason.append(illegalCargoMessage);
			}
			// Fail any missions with illegal cargo and "Stealth" set
			if(mission.IllegalCargoFine() > 0 && mission.FailIfDiscovered())
				player.FailMission(mission);
		}
	}
}
```

**Comment by Hadron1776** [comment]
Notice this:
`if((fine > maxFine && maxFine >= 0) || fine < 0)`
...That would mean that only the most severe fine would be imposed on you. My fine scaling PR addresses this by simply adding up all the fines.

**Comment by tehhowch** [comment]
@Hadron1776 that line is always successful if you have illegal things in cargo, as maxFine was set to 0 before entering this code block (and scan interference has already checked and failed to hide your items).
Cargo is also checked before outfits so you can't avoid failed stealth missions by also equipped or carrying nerve gas.

**Comment by Amazinite** [comment]
I only had 1 ship carrying all the illegal cargo and no interference plating.

**Comment by Hadron1776** [comment]
@tehhowch Yes, then maxFine is immediately set to the current "fine" value afterward. So it would always be successful on the first pass, anyway.

**Comment by Amazinite** [comment]
I just tested it and it does look like that only the highest fine gets applied, but interestingly all jobs that were fail-on-scan were failed.

**Comment by tehhowch** [comment]
That sounds like correct behavior based on the code posted above. Can you share screenshots of what the message looks like, vs what you feel it should?

**Comment by Amazinite** [comment]
The message that shows is that of the highest fined job. As for what I think it should be like, I don't know. Having multiple fail-on-scan missions have displaying all of their scan messages at once seems like it would be very cluttered. 

My main concern is that you don't get fined for all illegal jobs. The way I made pirate jobs more enticing was to give them higher pays, balanced by the fines which can make them profitless if you get scanned. Under the current system if you take jobs in bulk, then you're completely negating how pirate jobs were balanced and they just become blatantly better than doing legal jobs. That's why my main concern is fines not stacking.

**Comment by EnterTheMasses** [comment]
// Fail any missions with illegal cargo and "Stealth" set
			if(mission.IllegalCargoFine() > 0 && mission.FailIfDiscovered())
				player.FailMission(mission);

does this mean that the mission fails only if you have the mission set to illegal and stealth?
ive been having issues trying to get the mission to fail using only stealth and not illegal.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/c9b66ab7fcbdba7fe1cba00f99bfbd83f46a6e14
