### ISSUE TITLE
Looked in the "build instructions" and can't find out how to link with Blocks:  

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#269]
It gives the error "Can't find compiler executable in your configured..."

**Comment by gchapyzh** [comment]
Tell me in order what you did and were it broke please

**Comment by gchapyzh** [comment]
By the way, I suggest Scans if you are on Linux. Worked flawlessly for me.

**Comment by thenerdfreak** [comment]
step 1 - downloaded everything it told me to (right revisions and such) step two- opened blocks: Step three- chose proper folder for MinGW- step 4- closed the thing where i chose that folder and it gave that error. Running Windows 8 , 64 bit

**Comment by gchapyzh** [comment]
Download Scons, through console go to your endless sky folder, and run scons. then run endless sky.

**Comment by thenerdfreak** [comment]
what is a console? (windows)

**Comment by thenerdfreak** [comment]
and that's the problem, there is no executable in the endless sky folder

**Comment by endless-sky** [comment]
It sounds like you didn't enter the right path in the compiler settings. Make sure that whatever path you entered, it contains a folder named "bin" that contains all the executable files that are listed, with the exact names that are listed.

**Comment by thenerdfreak** [comment]
this is the folder I suppose you're talking about, but i c/p'd the link to it and it's giving the same error http://i1133.photobucket.com/albums/m581/thenerdfreak1/New%20Bitmap%20Image_zpsctpq2hnp.png

**Comment by endless-sky** [comment]
Can you post a screenshot of your compiler settings? Also, you shouldn't copy the path to the "bin" folder; instead, copy the path to the folder containing the "bin" folder.

**Comment by thenerdfreak** [comment]
http://i1133.photobucket.com/albums/m581/thenerdfreak1/Untitled_zps1nyswx05.png
http://i1133.photobucket.com/albums/m581/thenerdfreak1/New%20Bitmap%20Image_zpszovtqd8i.png 
normally it would say endless sky under the workshop icon but i was just showing the error i was getting

**Comment by endless-sky** [comment]
Sorry, I mean the "toolchain executables" tab, where you specified the path to the executables.

**Comment by thenerdfreak** [comment]
Perhaps I downloaded the wrong thing or something? I did everything it said and still getting that error
http://i1133.photobucket.com/albums/m581/thenerdfreak1/New%20Bitmap%20Image_zpsxdlcuulg.png
