### ISSUE TITLE
Question: Death of Nguyen and Wanderers: Alpha Surveillance

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2690]
During "Wanderers: Alpha Surveillance I" if the Navy assisted in liberating Poisonwood, this is said:
> He pauses to pull out a data pad from his desk and call up a file on it. "Recently," says Danforth, "an officer of mine assisted in taking down an Alpha enclave, like you have done." He's looking specifically at Elias as he says that. "A month later he was somehow assassinated, right here in my Naval base. Here's a photo of him." Danforth slides the data pad across the desk. It's showing a photo of Commander Nguyen, and to your surprise Elias stifles a cry of dismay when he sees who it is. Danforth says, "I can't pretend you would be safe here. I think the safest thing for both of you would be to leave human space for a while."

But, if the player's karma was too low then the Navy did not assist in liberating Poisonwood, and this is said instead:
> He pauses to pull out a data pad from his desk and call up a file on it. "Recently," says Danforth, "an officer of mine assisted in taking down an Alpha enclave, like you have done." He's looking specifically at Elias as he says that. "A month later he was somehow assassinated, right here in my Naval base. Here's a photo of him." Danforth slides the data pad across the desk. It's showing a man you do not recognize, but Elias stifles a cry of dismay when he sees who it is. Danforth says, "I can't pretend you would be safe here. I think the safest thing for both of you would be to leave human space for a while."

Presumably, Commander Nguyen is the one in the picture on both occasions. This means that despite not joining in on the liberation of Poisonwood, Nguyen still partook in taking down an Alpha enclave somewhere and died because of it. We don't hear about this at any point in the FW story, so my question is is this suppose to be a plot hole that we fill in with the Navy campaign? Is it destiny that Nguyen must die during the main campaign?

**Comment by Bladewood** [comment]
Yes.

**Comment by endless-sky** [comment]
It could easily have happened "off camera" somewhere.

The publicly stated purpose of the Oathkeepers is to defend the North from piracy, but their actual purpose is almost entirely focused on threats that the Navy really doesn't want the public knowing about (like Alphas and aliens).

**Comment by Bladewood** [comment]
...
Huh.
I was actually convinced that the former was the truth. wow.

**Comment by Amazinite** [comment]
@Bladewood Sounds like someone hasn't played the Wanderer campaign. :)

**Comment by Bladewood** [comment]
I hate you too.

**Comment by Amazinite** [comment]
Thanks for the info, I'll send this where it needs to go.
