### ISSUE TITLE
"FWC Pug 2" refers to the aliens as the Pug before anyone gives you their name

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2693]
In "FWC Pug 1B," despite having just fought the Pug, no one has any idea what they are or what their name is. Yet, when you land on Shiver and get "FWC Pug 2," your character somehow knows that they are called the Pug. I get that the player saw their name from the government of the ships fought in 'FWC Pug 1," but seeing as how no one else who fought them seemed to know what they were called, it kind of seems weird that the player immediately would.

To note, the log from "FWC Pug 1B" doesn't even call them the Pug either.

**Comment by tehhowch** [comment]
So an argument for a '???' or 'Unknown' government? With everyone only learning about the Pug name after making contact with those on the occupied planets?

I can agree to that.

**Comment by Hadron1776** [comment]
Maybe I can make a PR for when you don't know the name of a government... : )

**Comment by Amazinite** [comment]
>Maybe I can make a PR for when you don't know the name of a government... : )

I believe that @Elyssaen has talked about this in the past.

**Comment by endless-sky** [comment]
In this case, it seems to me that knowing the name of an alien faction when you see their ships, even though that's a bit unrealistic, is a lot simpler than having them all start out unidentified until you somehow learn what they call themselves.

**Comment by Elyssaen** [comment]
It's just a shame you draw attention to it with the unidentified Kestrel. : )

And yeah, @Amazinite, I've mused in the past about default unidentified names (`Unidentified Vessel`, `Unidentified Organism`), with conditions to indicate which ships/species you can identify. I never came to a very strong view on it in Endless Sky... but I like to muse about total conversions, and it's one of the features that might be particularly cool for a TC that took a slightly different approach to its setting.

**Comment by Amazinite** [comment]
To fix the issue is really just a matter of changing "Pug" to "alien" up until the planet-dweller tells you about the "Pug Protectorate." It just comes off as odd that the name seems to pop into the player's head out of no where when just previously when you fought the Pug, the player still calls them just "aliens" in the logs.
