### ISSUE TITLE
Raven doesn't catch one of Sawyer's lies

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2694]
In "FW Defend New Tibet"

>"Why would the Syndicate attack the Republic?"
>"I'm not sure," says Sawyer, "but the Syndicate's profits have more than doubled since this war began. Maybe they knew they would benefit from it more than anyone."`

But later on during the hearing in "FW Reconciliation 2"
>One of them, an older man, asks, "What possible reason would the Syndicate have to launch such an attack?"
>Sawyer says, "They have complex mathematical models of the galactic economy, and those models predicted a coming recession, the worst in centuries. This war forestalled that recession. From the perspective of someone who values economic growth above all else, war was a better alternative than recession."

I thought he didn't know why. :)

**Comment by Startome** [comment]
Haha oops

**Comment by endless-sky** [comment]
Fixed in 94e0c17.
