### ISSUE TITLE
FW Reconciliation bad karma: Navy never pulls out of certain systems

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2696]
During the Reconciliation branch if the player has good karma, then `event "navy out of rastaban"` is triggered very early on, which gives Delta Sagitarri and Rastaban back to the Free Worlds, as well as making Girtab neutral again and reducing the Navy presence in Lesath and Alpha Arae. But if the player has bad karma, this event is never triggered and the end game map ends up looking like this:
![screenshot_1](https://user-images.githubusercontent.com/17688683/27777931-34b7b216-5f85-11e7-8df9-8710e689f610.png)
Despite the fact that Dancer and New Portland wanted to be part of the Free Worlds and Girtab was neutral, the Republic does not convert these systems back to their previous governments. Especially given the former fact of Dancer and New Portland having asked to be in the Free Worlds, I think that this would stir some diplomatic conflict if the Navy never pulled out of these systems.
Suggested that "FW Syndicate Extremists 1C" trigger the "navy out of rastaban" event.

edit: Or change the conditions of the "FW Navy Out Of Rastaban" mission so that it is able to trigger later on in the story should the player have low karma.

**Comment by Amazinite** [comment]
I'm done going through the Free Worlds campaign with three magnifying glasses in front of my face the entire time; this is the last issue I noticed off about the events of the campaign.

**Comment by Bladewood** [comment]
I think this one is intentional.

**Comment by Amazinite** [comment]
This is through Reconciliation, so the Free Worlds are trusted due to their help during the Pug invasion. And again, Dancer and New Portland willingly agreed to be part of the Free Worlds, but were conquered by the Navy during the war when the FW militia was spread thin. For the war to be over and those worlds not to be returned to the Free Worlds seems odd.

**Comment by endless-sky** [comment]
That's intentional - if the Free Worlds have gained a reputation for being bloodthirsty, there's no reason that the Republic is going to grant any concessions to them. Remember that from the Republic's perspective, those worlds never had the right to secede in the first place.

**Comment by Amazinite** [comment]
I don't get why the Free Worlds wouldn't try to get these worlds back when they're in Parliament and the Free Worlds is being made an official government in the eyes of the Republic, but alright.
