### ISSUE TITLE
Uppercase vs lowercase Navy ship names

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2698]
Should Navy ship names (Cruiser, Carrier, Gunboat, Frigate) be capitalized or lowercased? They are generic names for a class of naval ship, but in game there is only a single model of ship called a Cruiser or Carrier, so I'd assume they should be uppercased. Yet I find them being lowercased in game, as in "FW Southern Recon 1B" where Gunboat is lowercased. But then there are examples of them being uppercased, like in "FW Southern Battle 1" where Cruiser is uppercased. And then there is this where Carrier is lowercased in the first instance and uppercased in the second.
![screenshot_3](https://user-images.githubusercontent.com/17688683/27790200-83ac7dec-5fbd-11e7-8516-5378736f633e.png)

This should probably be standardized.

**Comment by endless-sky** [comment]
It really depends on whether it's being used as a proper noun - the name of that particular model of ship - or a generic noun for that type of ship. So in general it should be lower case. But in the example above, it's capitalized to make it clear that what Danforth is glad about is that the Alphas have lost a Navy Carrier (i.e. a powerful capital ship) not just that they've lost a carrier (i.e. the ability to carry some fighters around).

**Comment by Pointedstick** [comment]
That distinction is pretty subtle. Also, the same word is also being used to refer to the same vessel in both cases, so I think it makes sense to be consistent there.

**Comment by jafdy** [comment]
How about just changing the name of the ship.

**Comment by Amazinite** [comment]
I think the generic-proper noun distinction works with the Carrier since there are multiple different carrier ships in the game, but what about the rest? What class of ships are refered to as gunboats or cruisers or frigates? I think of FW Southern Recon 1B, where you're specifically asked to steal an electron beam from a "Navy gunboat," not a "Navy Gunboat." Seeing as it's used as a generic noun, it would then suggest that there is more than one type of gunboat that the Navy uses.

**Comment by Amazinite** [comment]
I guess the answer to my question(s) is "no."

**Comment by MessyMix** [comment]
Late to the party, but ref #1460
