### ISSUE TITLE
Story Sorting

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#270]
Is there any overview about the story?
Like a diagramm or something.
Because, the more story-elements are added by several people, it might become confusing.
I don't know if there are any better tools, but what came first in my mind was a kind of control-flow-chart
<img width="655" alt="storynstuff" src="https://cloud.githubusercontent.com/assets/15857993/11429581/44b2dbfa-947a-11e5-918c-842427ab7eb8.png">
PS: yeah i know there might be a few mistakes, that's just hastily made to express my kind of idea

**Comment by endless-sky** [comment]
I've avoided putting a detailed outline in the wiki, to avoid having too many spoilers. But, I posted a complete outline of the Free Worlds story lines in this thread:

https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/8I9lHLo051s
