### ISSUE TITLE
Crucible-Class Steering description typo

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2701]
https://github.com/endless-sky/endless-sky/blob/master/data/remnant%20outfits.txt#L322
> This steering system is tiny enough to fit even an interceptor, but the Remnant mostly use them to provide an extra bit of maneuverability for their larger ships

Needs a period at the end.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/87bae82c230a4042d83899b75edc1c3db58ffadb#commitcomment-22224460

**Comment by Bladewood** [comment]
Oh.

Well, that one got buried under a lot of commits, so I think it's still worth making an issue for it.

**Comment by Amazinite** [comment]
I'm put it there so I can see who gets attribution for the typo fix.

**Comment by Bladewood** [comment]
I forgot about that one :|

**Comment by endless-sky** [comment]
Fixed in ffbb00f.
