### ISSUE TITLE
Event Delay in Missions

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2709]
Would it be too difficult to change the event delay to use a range?
The current syntax is 'event Whatever 25'.
Proposed syntax to allow 'event Whatever 20 30', which would have Whatever happen randomly 20 to 30 days later.
Similar to the way cargo and passengers have a range.

**Comment by endless-sky** [comment]
Added in 1ce173d.

**Comment by VonZorch** [comment]
Thank you sir.
