### ISSUE TITLE
Mirfak and Algenib both exist as individual systems, even though it refers to the same star.

### ISSUE THREAD

**Issue by LanadJer** [endless-sky/endless-sky#2710]
Mirfak and Algenib refers to the same star, suggest changing one of them.
Suggest stars in the same constellation: Atik/Menkhib, Miram

"The star (Alpha Persei) also bore the traditional names Mirfak and Algenib..."
Source: https://en.wikipedia.org/wiki/Alpha_Persei

**Comment by jafdy** [comment]
Obvious issue: This will break any mods that change that system.

**Comment by endless-sky** [comment]
Algenib is another name for [Gamma Pegasi](https://en.wikipedia.org/wiki/Gamma_Pegasi). From the same paragraph you quoted in the Alpha Persei article:

>  In 2016, the International Astronomical Union organized a Working Group on Star Names (WGSN) to catalog and standardize proper names for stars. The WGSN's first bulletin of July 2016 included a table of the first two batches of names approved by the WGSN; which included Mirfak for this star (Gamma Pegasi was given the name Algenib).

**Comment by LanadJer** [comment]
Acknowledged, the chart I was using had the stars sorted by constellation, which is why I missed this piece of information. Should have looked further.
