### ISSUE TITLE
Long-range AI doesn't use reverse thrusters

### ISSUE THREAD

**Issue by McNutty145** [endless-sky/endless-sky#2716]
I haven't had a chance to confirm this behavior in-game and won't be able to for a while, but I was reading the AI.cpp file and I think I discovered a minor bug. An AI-controlled ship with long-range weapons will maintain a minimum distance from its target by fully turning around and using forward thrust. This occurs even if reverse thrusters are installed, which unnecessarily wastes time taking weapons off-target when it could keep firing while reversing.

I could also be reading it wrong. Relevant code is in AI.cpp lines 1518-1527.

**Comment by tehhowch** [comment]
If the reverse thrusters are weak compared to the primary thrusters, this may result in the target catching the missile boat when the target could be kept at bay via turn + thrust + turn back.

I've got a thought, though.

**Comment by endless-sky** [comment]
It's kind of a moot point because there aren't any ship variants in the game that use reverse thrusters. Reverse thrusters are basically just included as a crutch for players who can't figure out how to control a ship without one.

**Comment by tehhowch** [comment]
(yet)

Any mods that use reversing variants would certainly benefit

**Comment by Amazinite** [comment]
>Reverse thrusters are basically just included as a crutch for players who can't figure out how to control a ship without one.

Slow down, what? 
You don't start out with reverse thrusters, and reverse thrusters aren't exactly cheap, so how is it that a player is going to struggle at the beginning of their playthrough trying to control their ship but then somehow get to the point where they both discover and have the credits to purchase reverse thrusters for their ship? Said player then needs a ship with the weapon space to fit the reverse thrusters, and none of the starter ships can do that, which means said player would also have had to play long enough to upgrade their ship. 
I'm really just confused at how a player could get to that point not knowing how to fly well, then find reverse thrusters and consider them far better to use.

**Comment by Startome** [comment]
I'm reading this as him meaning that players who have played for an extended period of time and just simply cannot get the hang of flying, can get this crutch when the time comes. Not early players, just mid gamers who still can't get the hang of it. While I don't agree with him, as I think it can have strategic uses as well, I do read that as the original intent of the outfit.

**Comment by Amazinite** [comment]
There are quite a few (closed) issues about reverse thrusters not being used in this situation or that situation, etc. etc. (#1170, #1377, #1583, #1838) I'd say this is practically a duplicate given that the general response on the topic of reverse thrusters has always been it's not something worth working on given how limited reverse thruster use currently is.

**Comment by McNutty145** [comment]
The difference is that those issues only refer to optimizing autopilot jump alignment. In this case, a larger ship armed with forward-facing non-homing long-range guns would become completely useless as soon as a faster ship started to fly in its face. Like I said, I haven't had a chance to test, but I imagine this would allow a fleet to cripple the long-range firepower of the enemy by sending small flights of fighters after them.

**Comment by Startome** [comment]
Isn't... that the whole point of Fleet diversity, naval strategy, varying builds.... you know... strategy?

**Comment by McNutty145** [comment]
Ideally yes, but there's a difference between using ships that counter other ships through their properties (speed, maneuverability, short-range weapons) and just derping the AI with a cheese strategy.

**Comment by Startome** [comment]
How is making use of a fighters speed and numbers to counter a slower heavier enemy a cheese strategy?

**Comment by McNutty145** [comment]
It would be a counter if they just danced around the bigger ship, avoiding all damage while slowly whittling it down. It's cheese when the larger ship is completely incapable of firing back or contributing to the fight in any way because the AI is forced to face away from the fight. There might be an argument to allow it anyway to better simulate this strategy because the AI fighters don't know how to dodge. It would be similar to how missile ships set their range to 0 after running out of ammo because chasing them would be annoying otherwise: not realistic, but good for gameplay.

**Comment by tehhowch** [comment]
Most large ships with long-range weaponry also have turrets holding short-range weaponry, meaning they will not enter this command loop which says "run away". Generally, only small, fast ships get armed with 100% long-range weapons (e.g. missile launchers), and the weapons they get can be fired with nearly equal effectiveness while facing away from their opponent.

The "long-range" weapons in `master`:
```
Drak Turret
Pug Gridfire Turret
Korath Detainer
Drak Distancer
Korath Mine Submunition
Railgun
Pug Seeker
Typhoon Launcher
Thunderhead Launcher
Korath Minelayer
Korath Piercer Launcher
Torpedo Launcher
Nuclear Missile
Finisher Pod
Meteor Missile Launcher
Sidewinder Missile Launcher
Hai Tracker Pod
Drak Antimatter Cannon
```

**Comment by McNutty145** [comment]
I guess it is something of an edge case. Probably not worth spending the time on.
