### ISSUE TITLE
Hyperdrive and Jump Drive tooltips are obsolete now

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2718]
Just something I thought I'd point out. Given that the attributes show as `Allows you to make hyperjumps` and `Lets you jump to any nearby system` now, the tooltips will never been seen.

**Comment by Amazinite** [comment]
Likewise with installable and unplunderable.

**Comment by Bladewood** [comment]
invading this issue.
`cooling inefficiency` and `quantum keystone` don't have descriptions.

**Comment by Amazinite** [comment]
If you're talking about `quantum keystone` then `gaslining` has no tooltip either, but I think those two can be left out since they're used as access attributes and not something like `cooling inefficiency` which actually affects your ship.

**Comment by endless-sky** [comment]
Fixed in 7ced625. For the attributes like "installable" that automatically get translated into a sentence explaining what they do, I don't think a tooltip is needed.

**Comment by Amazinite** [comment]
>Likewise with installable and unplunderable.

As in likewise that they exist but are obsolete.
