### ISSUE TITLE
Need a conversation/mission endpoint that combines the behavior of the "flee" and "defer"

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#272]
I'd like a conversation/mission that immediately boots you off the planet, but does not mark the mission as having been offered the way the "flee" endpoint does. So you would be booted off the planet but the mission could be offered again.

**Comment by frameworld** [comment]
Maybe you can make 2 missions that re-enable each other?

**Comment by endless-sky** [comment]
This can be done by manually clearing the "offered" condition:

```
...
apply
    "My Mission Name: offered" --
`You run for your ship, shouting, "Nope, nope, nope!"`
    flee
````

**Comment by Pointedstick** [comment]
Ah, that works, excellent!
