### ISSUE TITLE
A planet sprite for Zenith after it has been bombed

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2724]
If the player bombs Zenith, this is what the explosion is described as being: `The light of the explosion is many times brighter than this system's sun. And unless your sensors are lying to you, there is now a crater near <origin>'s south pole that goes all the way down to the mantle.` Unless that crater somehow went straight down instead of exploding outward, that should probably be a noticable from space, and thus the planet sprite should show it. A flash that big would probably also scorch a good amount of land outside of the crater as well.

I've been experimenting with the ocean7 and lava5 sprites to try and make some sort of visible damage on the planet. After showing a few people what I'd done, these two sprites came out as being considered the best.
![bombed_zenith 1](https://user-images.githubusercontent.com/17688683/27942504-6c08915e-62a5-11e7-87ce-49fccbc802ad.png)
![bombed_zenith_2](https://user-images.githubusercontent.com/17688683/27942505-6cd08f60-62a5-11e7-908e-ffaee24a5732.png)

It was suggested that the first sprite be what Zenith looks like after the bomb has been dropped since it looks brighter, then a few weeks later it would change to the second, dimmer sprite as the lava cools and repairs the crust. Should that be the case that the sprite changes, or should only one of the sprites be used? And if only one is used, which one? Whichever method is chosen, I'll PR it.

**Comment by tehhowch** [comment]
Events to change the sprite. Use 'em both.

**Comment by Amazinite** [comment]
Wow, I wake up to 10 thumbs up.

**Comment by gunqqer** [comment]
I say make it look like a cookie with a bite mark. Because, cookies

but really I say go with the changing sprite after a few weeks after changing as you drop de bomb

**Comment by Amazinite** [comment]
So 13 thumbs up but only one person saying which sprite they prefer (or if they want both). :)

**Comment by gunqqer** [comment]
I don't know wheather to take it is a compliment or no so I just will. Thanks.

It is a really good idea you had.

**Comment by jafdy** [comment]
I have nothing to add to what has already been said, so I didn't add to it.

**Comment by gunqqer** [comment]
Well there are three sugestions: Do nothing, add a new sprite, add a new sprite then after a week or two change the spirte again.

**Comment by jafdy** [comment]
Seeing as you have failed to notice I am effectively agreeing with the only significant comment on this so far (the first one) I shall say it explicitly: I agree with @tehhowch's proposal of using both sprites.

**Comment by Amazinite** [comment]
Such agreement is usually expressed with a thumbs up on that comment. 15 thumbs up on the main post doesn't help me when I ask two questions. :)

**Comment by gunqqer** [comment]
It's like when someone asks "Chicken or Beef (Or nothing)?" and you answer "Yes!!"

**Comment by MessyMix** [comment]
Both. Event switch.

**Comment by KiLEdEnNis** [comment]
(do that cookie bite idea for 1 day somewhere in between like an easter egg)

**Comment by MessyMix** [comment]
On april fools: zenith turns into a bitten cookie :)

**Comment by gunqqer** [comment]
Does that mean we'll start doing in game april fools? Hmm, I guess this is going to be a thing now

**Comment by Bladewood** [comment]
We already have one in the form of a [mission](https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt#L1856), so why not?

**Comment by gunqqer** [comment]
The reason why I said that is because we had the goat fox and whatever
thing. So, what could we do next? Maybe an Drak appears in the system your
at on April first?

**Comment by endless-sky** [comment]
I like the idea, but if Zenith's atmosphere is as thick as Earth's, the entire visible portion of it will be less than a pixel thick in that image. The same would hold true for the planet's crust - in the thickest parts it might be as much as 1.5 pixels thick, but if the crust cracked it would immediately fill back in with magma. You wouldn't be able to see a "bite" taken out of the planet - you'd just see an enormous glowing crater. The biosphere of a planet is incredibly thin compared to its diameter. (And, if that much of the planet *was* removed, all the atmosphere would flow into the hole and everyone on the surface would suffocate.)

**Comment by Bladewood** [comment]
[obligatory xkcd](https://what-if.xkcd.com/153/)

**Comment by KiLEdEnNis** [comment]
what have I done...

**Comment by endless-sky** [comment]
Added in d1617f6, but with some new sprites that I think are a bit more realistic:

![zenith](https://user-images.githubusercontent.com/11450262/28978650-c13778fe-7914-11e7-85fc-00765f060a3f.jpg)
