### ISSUE TITLE
Allow specifying a multiplier for deadlines, in addition to payments

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#273]
Basically, in the mission/job description, payment and deadline can only be a fixed number. I would love to be able to set it as a range, for more variance.

Also goes to payment and deadline values without parameters - A multiplier to the original value would also help adding variation (This probably need another field specifier)

**Comment by endless-sky** [comment]
I've added support (a7f1a70) for specifying the payment "multiplier" as well as the base payment, using this equation:

payment = base + multiplier * (jumps + 1) * (cargo + 10 * passengers)

That doesn't support random payment amounts, but you can get a similar effect by creating several variants of a job with different base payouts.

**Comment by luiges90** [comment]
it looks good :smile: 
though it seems nothing changed to the deadline though. 

(Basically, I would like to give all passenger missions have a deadline of 4 x jumps (for example) so that player won't bring tourists around for nothing and without penalty)

**Comment by endless-sky** [comment]
I've added support for deadlines in (base + multiplier * jumps) form in commit 1bf5333. I've also updated the "creating missions" wiki page accordingly.

**Comment by luiges90** [comment]
:+1:

**Comment by endless-sky** [comment]
Included in release 0.8.10.
