### ISSUE TITLE
(Spoiler) No credit for scanning a certain ship type before being asked to

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#2733]
On the `Remnant: Void Sprites 1` mission, after doing the regular pass through the system so the Cargo McGuffin could do its job, I went and bought an outfit scanner for some investigation of my own. My scans failed to reveal anything interesting, which was cool. But then I turned in the mission, and got a mission to... scan the aliens with an outfit scanner.

Ideally, I'd like to have been able to say "I scanned them already, I got nothing". But I'm not sure how that could be implemented within Endless Sky's mission system. Having the ships belong to a separate "scan with outfit scanner" ghost mission, maybe?

**Comment by endless-sky** [comment]
For the amount of complexity that would add, just for the sake of one particular mission, it really doesn't seem worthwhile.

**Comment by SolraBizna** [comment]
I tend to agree. (I certainly didn't want to write the PR myself. :) )

I'm closing this.
