### ISSUE TITLE
Option to make the cursor disappear while piloting the ship

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2736]
I just introduced Endless Sky to a friend who's fallen in love with it, but he's irritated by how the cursor remains visible while the ship is in flight. He'd like the ability to make the cursor disappear after a few seconds of not moving it.

**Comment by KiLEdEnNis** [comment]
put it to the far right so you can only see a 1 pixel thick short black line
although the option would be nice (if added, make it a preference maybe?)

**Comment by tehhowch** [comment]
The game shouldn't move the player's cursor, only hide the icon if it doesn't move.

**Comment by KiLEdEnNis** [comment]
neither one of us said anything like that?

**Comment by tehhowch** [comment]
>put it to the far right

You said that.
(I now realize you meant that the **player** can put it to the far right, but the context of this issue is what the **game** can do to hide the cursor. I'm sure Pointed's friend is aware that he can move the cursor)

**Comment by endless-sky** [comment]
I suppose it would be reasonable to hide the cursor if:

1. you're in full-screen mode, and
2. you haven't moved it in the last 10 seconds or so.

**Comment by Pointedstick** [comment]
Exactly!

**Comment by endless-sky** [comment]
Easy enough. Added in commit e051914.

**Comment by Pointedstick** [comment]
Okay, that works, but the cursor disappears in places it shouldn't: the main menu, the map, while landed, etc. It's only useful to have the cursor hide while piloting your ship; while navigating a mouse-based UI, it's just annoying and unnecessary.

**Comment by endless-sky** [comment]
37fe0ad should fix that.

**Comment by Pointedstick** [comment]
Perfect. Thanks!
