### ISSUE TITLE
Make timelapse key (default capslock) configurable

### ISSUE THREAD

**Issue by nylki** [endless-sky/endless-sky#2738]
Currently the 3x speed key is bound to caps-lock. It would be useful to have it configurable.

**Comment by Pointedstick** [comment]
Indeed. People sometimes re-map their caps lock keys to something more useful.

**Comment by lelutin** [comment]
I for one would like to have this since I configure caps-lock to be a second Escape key (which means I can't use the time lapse feature of the game. I'd like to for example remap that function to Tab
