### ISSUE TITLE
Allow disown to be set to a key

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2739]
Id make it set to nothing at the start to avoid any incidents but make able to be set to something.

**Comment by jafdy** [comment]
The intention is for you to use disown in very extreme circumstances therefor MZ is not going to do anything about it.

**Comment by Rob59er** [comment]
A man can hope for an easy way to get rid of 1000 stuck beserkers

**Comment by tehhowch** [comment]
Enter the save file edit.
or, get a bunch of Bounty Hunters on your tail, and jump to the relevant systems :)

**Comment by KiLEdEnNis** [comment]
how the hell did 1k Berserkers get stuck and why do you have 1k Berserkers in the first place

**Comment by Bladewood** [comment]
What you would want is the ability to disown multiple ships at a time (in the Player Info screen), rather than rapid-fire clicking Disown.

**Comment by Rob59er** [comment]
I use them to conquer planets... with nukes.
The sad part is how many times this happens
And to address Bladewood I was implying that as well.

**Comment by jafdy** [comment]
you can now select multiple ships so it may be possible or you could just wait until they refuel and then sell them.

**Comment by tehhowch** [comment]
You could always select multiple ships; the recent commit made `dragging` multiple ships possible too

**Comment by Bladewood** [comment]
Selecting multiple ships doesn't help, because the Disown button can only be accessed from an individual ship's Ship Info screen, not from the Player Info screen.

**Comment by toilethinges** [comment]
> I use them to conquer planets... with nukes.

Use more nukes and shoot them at areas of high concentration.

**Comment by endless-sky** [comment]
As with other requests involving very large ships: this game is an Escape Velocity clone, and the core game mechanics are designed assuming the player has a single ship or a small group of escorts, not a fleet of 1000 ships. Big fleets are supported, but UI changes that are only for the sake of managing fleets that size are very low priority.

**Comment by Musaran2** [comment]
No need fort extra-large fleets to easily leave many ships behind :
- Fighters/Drones parked by mistake.
- Fighters/Drones left behind when jumping.
- Small ships disabled upon, uh, tactical retreats.

They can't rejoin, they can't be remotely sold, they are not attacked in our absence, they are often not worth fetching, but they still obstruct ship list(s) and cost salary.
That leaves Disown.

The problem is mainly here : 
>the Disown button can only be accessed from an individual ship's Ship Info screen

Move it to ship list(s) like Sell/Park etc so we can multi-select and Disown.
