### ISSUE TITLE
Placement of mission cargo/passengers in the player's fleet

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2746]
A player on the Discord was attempting to bomb Zenith by flying into the system cloaked and landing on the planet while leaving their escorts holding position in a different system. This led to quite a bit of confusion when the player recieved no conversation for the next mission and no pop-up dialog explaining why. The player could not have parked their ships without landing again because the previous mission forces the player to launch.

Another player expressed having the same issue in the past during the Checkmate campaign when they had to bring cargo out of Pug occupied space, only to find out half an hour later that it was in their non-jump drive equipped escort the entire time.

Suggested that mission cargo be placed in the flagship first before it is placed in escorts as to avoid such situations where the player does not have their escorts in the destination system, either through leaving them behind or being unable to bring them.

**Comment by tehhowch** [comment]
I'm thinking this should be a preference setting, because the majority of times I want my escorts holding that cargo.

This is already done for passengers, so configuring it for cargo will not be too bad. (I also had that issue with Checkmate)

**Comment by tehhowch** [comment]
![image](https://user-images.githubusercontent.com/20871346/28123214-00eca91a-66e6-11e7-8140-7ff94bef6c23.png)

Do note that this will include bog-standard mission cargo, such as that 148 tons of paper towels you said you'd deliver to Dancer.

**Comment by jlnxr** [comment]
I've run into this problem, although I've also run into situations where I want to keep passengers and cargo off my flagship, to make room for plundering and the largest boarding party possible. I think the ideal solution would be to put things on the flagship first, but have some mechanism for moving things from ship to ship as you see fit. That way  I if it's a surprise launch, it's  a on the flagship, but you aren't stuck with that for your fish head/paper towel/ industrial waste jobs. Not sure if that would be easily possible though

**Comment by tehhowch** [comment]
@jlnxr #2747 would do exactly that for cargo, if the player turns on that preference.
Any cargo from a one-time-only mission (e.g. not repeatable jobs), a mission with `autosave` (dangerous jobs, perhaps), that is illegal, or a mission that is `stealth` would get placed on your flagship instead of escorts (until you have no room). After your escorts run out of room, then what's left gets put on your flagship (normal behavior)

**Comment by Amazinite** [comment]
#4315/#4342 effectively solve the problem of this issue by making it so that the player knows that the cargo/passengers are on a different ship.
