### ISSUE TITLE
(Spoiler) "FW Alphas 1.1" Oathkeeper escort has a bone to pick with me

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#2753]
As soon as the war started, I dominated all of Free Worlds and Republic space. My Oathkeepers reputation went down whenever I attacked Militia defense fleets, which is fine. But now, on the `FW Alphas 1.1` mission, I'm trading fire with an Oathkeeper ship marked as my escort... and they never leave the source system because they still think they're fighting me. (Which makes the mission unfinishable.)

I'm going to go grind pirates until I have positive reputation with Oathkeepers and see if I can coax that ship out of that state.

(I took a snapshot, which I can upload if it will help.)

Edit: Some combination of landing and taking off and loading snapshots unbroke the Oathkeeper cruiser. It still wants me dead, but I was able to convince it to go to the destination system, and have now completed the mission.

**Comment by tehhowch** [comment]
GitHub is 100% spoilers - no need to mark it.

Escorts - even hostile escorts - will happily pathfind to your system unless they are marked as `staying` or `uninterested`. If also tagged `coward`, they may initially pathfind with you until sufficiently damaged, at which point they will act `uninterested` until you next reload the game.
The `Navy (Oathkeeper)` escort "N.S. Peacemaker" is only `escort heroic`, so its pathfinding to you should not be an issue. What version of ES are you playing? (Steam / selfcompiled commit)?

**Comment by Bladewood** [comment]
You kind of deserve it for killing thousands of militia crewmen.

**Comment by SolraBizna** [comment]
> GitHub is 100% spoilers - no need to mark it.

Noted.

> You kind of deserve it for killing thousands of militia crewmen.

I absolutely do. :)

> Regarding your negative rep with Oathkeepers - you will definitely want to raise that.

Fortunately, it was nothing that murdering a few hundred pirates couldn't fix. God bless video game morality.

> What version of ES are you playing? (Steam / selfcompiled commit)?

It was a self-compile of my `gl21` branch, which was up to date as of just before the commit that already fixed this bug: 42dbd30a65baf0ca30de1456e63620c888634849. (I tested it against my snapshot, and it does indeed fix it.) It also predated 830d7578594e3fc1679339c4e366f41041342407, which significantly improves the UI implications of such situations. That's what I get for not doing a `git pull` before reporting.

Closing this bug.

**Comment by tehhowch** [comment]
42dbd30 should have had nothing to do with this issue - that bit only got entered for NPCs with the `vindictive` personality, and the NS Peacemaker is `escort heroic`, meaning the only AI differences are that it will target you for weapons fire no matter where you are in the system. Perhaps you meant 89259410371ab124580751c98fd1e332b35e6a58 (though I'm not sure how you could leave the system in an untargetable state without the cloaking device, unless you happened to flee to beyond the constrainment boundary and then jump).

**Comment by SolraBizna** [comment]
I assumed the Peacemaker inherited `vindictive` somehow. (I don't know how personalities work.)

> I'm not sure how you could leave the system in an untargetable state without the cloaking device, unless you happened to flee to beyond the constrainment boundary and then jump

Each time it got stuck, I jumped within a few seconds of taking off. So I definitely wasn't far from the system center.
