### ISSUE TITLE
Enhancement Request: Controls on what cargo my fleet will pick up

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2755]
I've found myself spacing low value cargo, while farming, in order to make room for more high value cargo, only for another ship in my fleet to pick it back up.  (i farm in places without an outfitters/spaceport, so when i land it redistributes the cargo to my escorts)

Alternatively, the ability to dump cargo while planetside on an uninhabited planet would also fix my issue.

**Comment by tehhowch** [comment]
You can tell them to dump cargo while in space.

**Comment by marphod** [comment]
"they only pick up what they run into"  which is frequently what a different escort just dumped.  

I've got a fleet of 28 ships, plus anything I commandeer.  It is hard to avoid accidental overlaps.

**Comment by AdamMil** [comment]
Perhaps an item can be flagged as unwanted after you dump it, in which case escorts won't pick it up automatically? (The flagship could still do so.)

**Comment by tehhowch** [comment]
No ship can pick up what it dropped. It would be possible to extend that behavior to ships of the same government.

**Comment by marphod** [comment]
That would work for the pc; not sure it makes sense in the context of other governments.

**Comment by endless-sky** [comment]
Some players like being able to dump cargo from their flagship into their escorts (by hovering right above them while dumping). So making all your escorts not pick up dumped cargo would mess them up.

Your use case sounds like something that very few people would need. It only applies if you have so many ships that stuff dumped by one will get picked up by another, *and* you're in a situation where you can't just fly off alone to dump it, *and* you can't just go to an inhabited world to sell your cargo when you've filled it up.
