### ISSUE TITLE
low priority: Nest ship description misleading

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2756]
"Access to the fighters from within the ship is so inconvenient that most pilots opt to just stay aboard their fighters when in flight. "

This may only be me, but I took this to mean that, in general, fighter crews had general access to the carrier in flight, and therefore could participate in boarding parties.  Thus, I was disappointed when my Transport-converted boxwings could not add to my Bactrian's crew compliment for boarding.

**Comment by KiLEdEnNis** [comment]
I don't really see a problem; a description is for some flavor
plus, the Bactrian is still OP in my opinion and it still remains as 1 of the best capture ships, extra crew from Boxwings aren't even needed

**Comment by marphod** [comment]
That the Bactrian is overpowered, or at least needs some modifications to be better balanced, notwithstading, the description implies that the crew of a fighter can get to the carrier on any carrier craft, be it the Bactrian, mule, Nest, Skein, navy Carrier, Korath Raider, or one of the ships that can only be gotten after the main plot completion.

(and the crew is necessary, if you want a shot at getting a korath worldship.  by my calculations, you could get up to about a 5% chance with:
1) a fully crewed bactrian if it were kitted for transport, including the extra 51 from 3 boxwings
2) lasers, grenades, and nerve gas for all crew
3) one of the worldships with a crew compliment of low-mid 800

not that i had plans for a personal mission that I called get-marphod-a-korath-worldship

Without the extra 51, the odds are less than 1%)

**Comment by jafdy** [comment]
You only use the best H2H thing you have, you don't use all 3.
