### ISSUE TITLE
Enhancement: Make ramscoops and solar panels perform differently depending on the type of star system

### ISSUE THREAD

**Issue by Jeremy-E-Johnson** [endless-sky/endless-sky#2759]
Currently the amount of fuel gained with a ramscoop only depends on your ramscoop value and proximity to the center of the system. The same is true of solar panels. I propose that this be modified to take into account the number of stars in a system and their type. (note that #2508 is somewhat relevant)

I see there being three major decisions to be made in the implementation:

- What exactly does this modification effect?
- What are the values for the different star types?
- What is the schema for dealing with multiple stars in a single system?

Handling each respectively:

Currently there is a value called "scale" which depends linearly on a ship's distance from the center of the system that determines how effective solar panels and ramscoops are. 
`double scale = .2 + 1.8 / (.001 * position.Length() + 1);`
This could be modified directly to depend on the system, in which case it is useful as a value that describes how much the stars of the system are effecting a ship.
Or modifiers can be implemented separately for ramscoops and solar panels. This has the added value that stars do not have to emit light in direct correlation to how much gas they emit. (I see this being most notable in the supernova systems where the stars are small but there are plenty of gas clouds)

I have no clue how to appropriately choose values for star types, but further research into actual stellar emissions may provide a good starting place. They would probably be centered on making ramscoops and solar panels work pretty much the same as they do now in single star systems where the star is similar to Sol.

Dealing with multiple stars can be handled in a couple ways. We could just add their modifiers, but I feel like this may be a bit much. My gut tells me that a binary star system with two stars like Sol should probably have a modifier more like 1.5 than 2.
The only thing that comes to mind is to order the stars by their modifiers and from largest to smallest sum up the values times 1/n where n represents where in the ordered list the modifier resided. (for example [1, 3., .2] -> 3 + 1*(1/2) + .2*(1/3) )

**Comment by MessyMix** [comment]
I thought this was a duplicate, but turns out they didn't PR this.

It was addressed in https://github.com/endless-sky/endless-sky/issues/2508#issuecomment-300492186. This, and see @Elyssaen's comment.

**Comment by Elyssaen** [comment]
Hey. That issue (#2508) led to a PR (#2618), but it's about scaling the heat generated by solar collectors. @Jeremy-E-Johnson's idea has been talked about too, but I think MZ would suggest it's a little too 'simulationist' and doesn't really add much fun. 

(Note that PR #2618 hasn't had any attention either: if we can't answer the question "How does this make the game more fun?", it's not likely to be a high priority.)

**Comment by Bladewood** [comment]
*cough* [over the rainbow](https://github.com/endless-sky/endless-sky/issues/1281) *cough*

**Comment by endless-sky** [comment]
It's hard to decide if this would be a cool feature or an annoying one. Getting stranded in a system with very little fuel or power available could be really frustrating. But stopping and refueling specifically in systems with high solar wind could add an interesting game mechanic. And it could also be cool that solar-powered ships are much stronger or weaker depending on what system they're in.

If this were added, the power multiplier would probably have to have a rather limited range, say between 0.5x for the dimmest stars and 2x for the brightest multi-star systems. The fuel multiplier, on the other hand, could have a much broader range. (And, things like W-R stars and nova remnants could provide very little power but lots of fuel.)

**Comment by jafdy** [comment]
Having solar powered ships underperform in some systems would make an already awkward outfit even more difficult to use, and as you pointed out we don't want people to get stranded in a system.
I would say that the best way to go is to have the current values as a base-line and then some systems can out perform that. The idea of "stopover systems" for fuel I think is well worth expanding on, as a large multiplier with a sprite to make it more obvious.

**Comment by Jeremy-E-Johnson** [comment]
Okay, then I am going to start trying to implement this with some placeholder numbers as modifiers that can be tweaked going forward, and some hard coded minimums so that ships don't become stranded. Speaking of which, from a style perspective, is it preferable for these numbers to be enumerated in the code, or for there to be some new data text file to store them?

**Comment by endless-sky** [comment]
I guess the cleanest way to do it would be a mapping from stellar object sprites to solar power and solar wind values, the same way that the "landing message" mapping works right now. The other possibility would be to require the solar wind and solar power values to be specified for every system in the map, the way the habitable zone is right now.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/1181 I found this...
