### ISSUE TITLE
Game State oddities After Main Campaign (mostly low priority stuff)

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2760]
I was looking through my save file, vis-a-vis mission and event files and noticed a few things:
1) My reputation with the Deep never got reset after reconciliation (not that that seems to have any in-game repercussions, at least not given the current missions/universe state --it is at -1003) (low priority)
2) I never got the new Syndicate Tech added to inventories (only can get them off of marauders), despite there seeming to be no way to avoid triggering the relevant event & the event isn't in my save file.  I did get the Deep Worlds tech added to relevant inventories/save file, which is the immediately preceding command in events.txt (moderate priority, but i don't have a repo case as it is so far removed from my current game state))
3)There is a reputation listed for " Kor Mereti " [sic] (-1000) as well as "Kor Mereti" (9.9) (low)

**Comment by tehhowch** [comment]
That's all perfectly fine.
1. Deep is used for the Ravens in the Archaeology mission string, not the ships of the Deep region of space.
2. " Kor Mereti " is used for drones which should be hostile to you in certain mission strings, just like Deep.
3. You chose the Reconciliation branch, which is FW+Republic+Deep vs Syndicate. Why should they want to give you tech since you sided against them? If you want their tech, give them the defector.

**Comment by Bladewood** [comment]
By playing the Checkmate route, you also gain access to the new Navy equipment (at the end of the campaign).

**Comment by Amazinite** [comment]
Please close this issue.

**Comment by marphod** [comment]
i'm not convinced having 2 separate relationships whose only difference in spelling is whitespace is a good idea, but closing

**Comment by MessyMix** [comment]
Why not? It allows the faction to appear hostile, but killing ships of the fake faction won't affect your actual reputation with the real faction. Very useful for missions where you don't want reputations constantly moving around. IMO it's an ingenious method! :D

**Comment by jafdy** [comment]
Or where you want ships of the same faction to be fighting each other.

**Comment by marphod** [comment]
Then make a way of having a government use a distinct display name from the internal name. There already is a way to do that with other objects (ships display the base model name, even if instantiated from a customized instance; don't know if the customized instance is an independent ship created by copying the base and overwriting, or if it effectively subclasses the base ship model -- that's an implementation detail )

This also could make faction reputations easier -- the 'oathkeepers' would not need to be fully defined, but defined by how it differs from the base republic.  Same with a potential future 'intelligence' faction, Tarazed/Wayfarer could remain part of the republic with a custom rep set rather than setting it to 'neutral'. The pirate factions could all be pirates, but actual care about different things, etc.

(depending on implementations, it could also make the freeze-reputations enhancement request easier, and make it trivial for things like actions during a cease-fire having long lasting effects without affecting the ceasefire, or to have an event cache or restore the original rep rather than setting it to a fixed value)

**Comment by tehhowch** [comment]
You are welcome to code up and PR your solution to the simple method of
controlling NPC relationships that is currently in use.

In general a player should never have to open their save file, so the
implementation that yields displayed faction names and desired inter- and
intra- faction behaviors is of fairly low importance. As they say, there
are bigger fish to fry, and that's especially true for MZ.

**Comment by Bladewood** [comment]
Just so you know, the "customized instance" you are talking about is called a variant.
