### ISSUE TITLE
Giftbringer overheats easily

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#2762]
Giftbringer hasn't been altered to account for cooling inefficiency of outfit expansions, and will rapidly overheat itself if it is persuaded to both thrust and fire.

**Comment by Bladewood** [comment]
But the Giftbringer mostly relies on its fighters and drones.

**Comment by endless-sky** [comment]
Fixed in da7717d, by switching it to using Tracker Pods and slightly less powerful engines. It's probably better for it to have long-term bombardment weapons, anyway.

**Comment by Pointedstick** [comment]
Note that giving it long-range homing weapons significantly increases the difficulty of the battle: you can no longer fly away and deal with just the fighters, and then bombard Giftbringer to death. It's already a very tough fight for a single non-cheating ship at that point in the storyline.

**Comment by Lineth** [comment]
Eh, the last time I fought it mano-y-mano I kinda dunked on it with a Bactrian with decent engines and shields, a cloak and plasma turrets. Picked off the fighters in a merry chase and finished off Giftbringer by stun-locking it with heat damage. A Dreadnought would likely work even better, being a dedicated combat ship that has plasma turrets by default. The trackers will likely be overkill though. Maybe replace two of them with guns?

**Comment by SolraBizna** [comment]
I see Giftbringer (and the surrounding trips through Sestor space) as a wakeup call. Up to that point in the plot, you can get by with a lightly-armed, fast ship. After the mission with Giftbringer, you are going to *need* a powerful ship, or a fleet. Several of the missions immediately after that one involve large fleets of hostile Shield Beetles, many of which are going to be armed with Trackers. Arming Giftbringer with Trackers seems like it would encourage the player to get decent anti-missile protection, which would put them in a better position for the next few battles.

**Comment by Pointedstick** [comment]
That's a great point!
