### ISSUE TITLE
crash on startup with no audio device (Windows)

### ISSUE THREAD

**Issue by AdamMil** [endless-sky/endless-sky#2776]
If there's no audio device connected to the computer (e.g. if I don't have my headphones plugged in), the game will crash on startup after loading the main menu. This happens in Windows.

**Comment by Bladewood** [comment]
This was reported a long time ago, and has been resolved, though it has not yet been released as a public build.
https://github.com/endless-sky/endless-sky/issues/2231

**Comment by AdamMil** [comment]
Thanks. Sorry about the duplicate. I built the latest version from source and confirmed that it did not crash.
