### ISSUE TITLE
Need <current planet> and <current system> text replacements

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#278]
That way you can write text like this:

> "Great," Amanda replies. "I had a feeling you thought so, the way you were getting into it. Listen, the reason why I'm asking is because I noticed your captain's outfit and we need someone trustworthy to pick up a friend who's on `<destination>` *(this works)*. The ship we came here on has developed engine trouble and the mechanics are saying the repairs will take three days, so it won't be able to pick him up in time for a meeting with the planetary governor here on `<current planet>` *(this does not work)* in a week. Can you make it?"

If this was a mission with a specific fixed planet where it's offered, I would just write the name of the current planet out, but it's a randomly-offered mission so I need a way to programmatically access the name of the current planet.

**Comment by endless-sky** [comment]
The planet where the mission is offered is `<origin>`. (See the [mission creation](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#text-replacements) documentation.)

**Comment by Pointedstick** [comment]
Ah, perfect. Must have missed that!
