### ISSUE TITLE
Landscape images mountain22 through 25 are their 2x versions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2780]
![screenshot_1](https://user-images.githubusercontent.com/17688683/28380950-2531f11c-6c87-11e7-8dd9-d49084aa0f8e.png)
Pay no attention to the work-in-progress planet description.

**Comment by jafdy** [comment]
Crap, I hope I didn't put the normal ones in the high dpi plugin.

**Comment by Amazinite** [comment]
You didn't. The normal ones just look like they were never resized.

**Comment by jafdy** [comment]
Got the fix out.

**Comment by endless-sky** [comment]
Fixed by merging in #2784.
