### ISSUE TITLE
A question on contributing alien species

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2782]
The help wanted page says that "each species should have a different set of ships and weapons, a region of space that they inhabit, and a story line to go with them."

How much of a story line should they have when looking to merge? Should it be a completely fleshed out story line or is an introduction (similar to how the Remnant are currently) enough/a bare minumum?

**Comment by Elyssaen** [comment]
I'd also like to know: is a region of space _absolutely_ necessary? The Trin @comnom and I've been working on are looking to have unique tech, art and plenty of story, but their lore is that their territory is long gone.

**Comment by endless-sky** [comment]
First contact missions are the bare minimum to start out with. Eventually, each species in the game should be involved in a more major story line, but that doesn't have to happen right away. For example, the Coalition doesn't have a story yet, and the Wanderer story still isn't done 1.5 years after they were added.

**Comment by VonZorch** [comment]
An alien species doesn't necessarily need any actual real estate,  They could be 'The People of the Ships'.

**Comment by endless-sky** [comment]
The thing is, what the game really needs in terms of new species is something to fill out and populate the rest of the galaxy. So, a species that only inhabits the existing star systems won't meet the goal of creating new locations for players to explore.
