### ISSUE TITLE
Missions Not Completing

### ISSUE THREAD

**Issue by andyspurgeon** [endless-sky/endless-sky#2783]
I started a new game recently and had an issue where two missions did not complete. They were simple cargo runs (a delivery to Earth and a rush delivery to Shiver in Altair). I landed on the planets, but instead of received the message about mission completion/reward, nothing happened. Took off, landed again, still nothing.

I quit the game, restarted, and both missions completed on my next landing.

Not sure if this is a known issue (I looked quickly but didn't see any open issues that looked similar). Since I quit and restarted, I don't have a save game file or anything to share. I'll be sure to grab those, if I see a recurrence.

I built from source myself using the most recent commit (ca5c3324b7462460d3dcd0ee957b1bd62832b43a), but I haven't made any source changes.

**Comment by Amazinite** [comment]
Did you have escorts and were they located in another system at the time? If yes then the cargo was in your escorts.

**Comment by andyspurgeon** [comment]
Hmmm... I'm early game with two star barges. I don't *think* the other ship was in another system, but I can't confirm (because of the restart). If I see a recurrence, I will check for sure.

**Comment by tehhowch** [comment]
Almost certainly, your escort was not in your system. By default, cargo loads into your escorts first and your flagship last, and mission/job cargo is loaded before trade commodities are.
So if your flagship is more manueverable, on a longer route you may land before a sluggish freighter arrives in your destination system.

**Comment by Amazinite** [comment]
As for reloading your save causing the job to complete: #1945

**Comment by andyspurgeon** [comment]
Okay, it looks like I experienced a mix of "you left your other ship behind, idiot" and the issue Amazinite referenced. I close this to reduce the clutter.
