### ISSUE TITLE
Minor Error in FW Hope Recon 1C

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2785]
The FW Hope Recon 1C mission gives the normal crew of a Gunboat as seven while with the required turret gunner it is actually eight,
I have corrected this in the attached file.  I tried to create a pull request for it but couldn't figure out how to get past the compare page.
[free worlds start.txt](https://github.com/endless-sky/endless-sky/files/1164051/free.worlds.start.txt)

**Comment by tehhowch** [comment]
I think if you make the change to the file here in the repo, it will prompt you to open it up as a PR? Haven't really tried editing files in others' repos from the website.

I can PR it for you if you wish.

**Comment by KiLEdEnNis** [comment]
#1410 my last reply shows that it's not really fixable:
there would be 8 crew members in the snow, but if ya kill them & the Gunboat takes off, they'd have another 8 crew, but a Gunboat only has 14 bunks
only fixes are giving it a bunk, giving Gunboats more bunks (both weird) or retyping it as "if you'd pick these crew members off the few remaining ones could probably not get the Gunboat off the ground"

**Comment by VonZorch** [comment]
@KiLEdEnNis  Since there are actually only 12 bunks on a gunboat they are already hot racking.  But I will create a variant gunboat with a bunk room and further rewrite the mission.
@tehhowch  Hold off until I get the corrections made, that should be about 10 minutes.

**Comment by VonZorch** [comment]
@tehhowch Not letting me edit in the repo.  Please open a PR for me, the requisite files are of course attached.
[free worlds start.txt](https://github.com/endless-sky/endless-sky/files/1166499/free.worlds.start.txt)
[variants.txt](https://github.com/endless-sky/endless-sky/files/1166498/variants.txt)

**Comment by tehhowch** [comment]
Ah, you need to first 'fork' ES and then you are able to become a contributor 👍 

After forking, you'd [upload those files](https://help.github.com/articles/adding-a-file-to-a-repository/) and place them into a new branch, ("AltFWHopeRecon1C" would be fitting), then you are able to initiate the PR. GitHub has some nice docs on this.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by VonZorch** [comment]
Thanks for the advice.

**Comment by endless-sky** [comment]
This really doesn't seem to be worth changing.
