### ISSUE TITLE
Setting to slow down the game during combat

### ISSUE THREAD

**Issue by AdamMil** [endless-sky/endless-sky#2792]
I'm glad a button was added to speed up the game, since it implies that there's the ability to change the game speed. Personally I felt like combat is too fast. When I was trying to start in a Sparrow, the only way I could really match up to an equally equipped AI Sparrow was to use auto-aim since the AI can aim perfectly and fire from the maximum weapon range, but I'm not so perfect... or maybe sell my guns and switch to missiles.

Since I restarted with a freighter and now have a good fleet, I'd still like to slow down combat sometimes to help other ships. If trader X calls for help while under attack by pirates, it takes time to find the ship on the map and start moving over there to help them. They're generally dead before I even know who to fight. A way to slow down the game might help, or perhaps a way to pause the game and scroll around the map...

I was wondering if people thought it'd be useful to have a game setting called Combat Speed, which changes the game speed when player ships are under attack. (It would combine multiplicatively with Caps Lock so combat can be sped up if needed.)

**Comment by Bladewood** [comment]
We've discussed this before. Michael does not seem to like the idea. https://github.com/endless-sky/endless-sky/issues/865 https://github.com/endless-sky/endless-sky/issues/1590

**Comment by MessyMix** [comment]
IIRC running ES in debug mode (not sure how) will make the capslock a "slow time" button.

**Comment by tehhowch** [comment]
@MessyMix  is correct. This requires starting Endless Sky with the `-d` command-line flag. One can edit their application shortcuts to do this on Windows (change the target from `.....EndlessSky.exe` to `..... EndlessSky.exe -d`), or run the .exe from the command line, in which case they would add ` -d` to the command.

**Comment by VonZorch** [comment]
@tehhowch  The same thing can be done to Linux program launcher.

**Comment by tehhowch** [comment]
Generally I launch from the command line when playing linux, so launcher target modification is not necessary. 👼 

(but you are certainly correct)

**Comment by endlesssteve** [comment]
An interesting point.
I assume the AI pilot is considered to be using auto and slowing the game wont help your freighter get to the battle quickly enough. Some other situations might be different. I'll try the option mentioned and see how it goes.
In principle if you can change your save file and the data files for the game why not the speed?

**Comment by KiLEdEnNis** [comment]
if you really wanna slow down a battle I suggest having a fleet of 500 warships, assuming you don't have a good PC

if one can slow a battle down, the challenge is basically gone; a fun part of a battle is that you usually have to act quickly, think fast, while if you have the time to sit back and watch everything happen that's gone
plus when the game speeds up w/ caps lock it skips drawing frames (I think that saved CPU/GPU usage?) while if it slows down it has to draw extra frames and animations may look really bad

**Comment by gunqqer** [comment]
500 warships? 50 slows my computer to a crawl, even more if there's a ton of asteroids and missiles.  Guess you have a different defenition of not a good PC.

**Comment by endlesssteve** [comment]
Woow  That"s slow!

It"ll take a week for the freighter to reach the pirates.

**Comment by gunqqer** [comment]
yeah, I'm saving up so I have better than a GeForce 8600.

**Comment by KiLEdEnNis** [comment]
this is off-topic, but make sure you know the graphics card is the problem and not your processor; if it is the graphics card your fps should drop but the game shouldn't lag much

**Comment by endlesssteve** [comment]
I meant the -d option to run the game with caps lock as slow instead of speed up.

Way too slow, no fun at all. may be slowing the game more is not such a good idea.

**Comment by tehhowch** [comment]
As mentioned before, the game will happily slow things down for you if combat "gets real" :grin:

Another easy way is to use a lot of effects-based weapons with integrated graphics.

The request to make the game use a `game steps / sec` setting described in preferences.txt is a decent suggestion. The value would default to 60, and could be clamped to reasonable bounds: e.g. 15 - 600, for 0.25x : 10x speed control. As for 'pause & pan', I think that might fall into the "MZ doesn't develop UI manipulations that are really only desired for large fleet management" / "feature creep" department.

**Comment by jafdy** [comment]
Sounds good, although I don't see the point of the lower bound, if people want 1 fps then go for it. 0 fps would also be a pause effectively, although without the pan. Only problem is that it is going to need some kind of keyboard button.

**Comment by VonZorch** [comment]
Do this old school trick, use a variable delay between frames.
Pseudo code here.
sub draw stuff
  get time
  draw everything
  wait until time + x
end sub
This way the game runs at the same real time speed whether there is one ship or many.
 While a very slow battle isn't much fun, jumping in with a single ship and getting vaporized before you can see what's in system isn't any fun either.

**Comment by int-ua** [comment]
Was this closed just because maintainers didn't have time to implement it? Any rationale for closing?

Reasons to have slower speed option are explained in great detail in these videos by Extra Credits (a YouTube channel about game design and more):
[Accessibility - The Curb Cut Effect](https://www.youtube.com/watch?v=PJoax1Z1x4Y)
[Depth vs Complexity - Why More Features Don't Make a Better Game at 3:27](https://youtu.be/jVL4st0blGU?t=207)

In short: I'm mostly playing this game for story. A slowdown or pause even without ability to change things would've been beneficial. At current state the space UX is mostly frustrating at the start, especially taking into account that only a small part of interface is explained and you are left wondering what do the meters mean as time whizzes by causing anxiety and irritation.

Also, looks like AppImage does not recognize the `-d` key. Is it supposed to work with AppImage?

**Comment by Amazinite** [comment]
Should move any such conversation over to #4818.

**Comment by int-ua** [comment]
Thank you, missed it for some reason. I'll move the comment.
