### ISSUE TITLE
Should AI plunder outfits?

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2793]
Currently they only plunder cargo, even if they have the room to take outfits.

Yes, this means a player could end up with a ship that needs to be scrapped, if their escort was plundered while they were playing coward out beyond the constrainment boundary.
Yes, this means a player who blindly captures ships without looking at their outfits could cap a ship that can no longer fly.
But it sure as heck makes more sense than going to board a ship that pirates or Remnant have worked over multiple times, and finding that it still has thousands of credits (even millions) worth of tech on board.

**Comment by Bladewood** [comment]
**Yes.**

**Comment by tehhowch** [comment]
A lot of the nice methods are locked up in BoardingPanel (e.g. the class "Plunder" is a private class used only by BoardingPanel, and there is simply no reason for AI ships to use BoardingPanel.
Plunder could be moved into its own class (probably best, but more complex), or the AI can simply try a few times (random:;int(10)) to take randomly-selected outfits from the ship, and then fill up on commodities.

AI plundering outfits will result in a lot more "that AI ship looks broken even after I repaired it", so a related improvement would be to instruct the Plunder personality ships to fire upon the ship they just boarded if they leave it and still have cargo space open (eg. the ship didn't have anything they could take, which is a pretty good sign that it perhaps is crippled beyond repair).

This change would also make "fetch quests" that appear on boarding disabled NPCs possible, e.g. "Bring me a hyperdrive, or thrusters, or a battery,, and I'll repay you greatly."
That would need some more complicated changes (e.g. other PR) as it would require instantiating a persistent derelict NPC variant from a random non-special NPC. But would be awesome.

**Comment by Rob59er** [comment]
Hmmm If you could make it vary it would fit the lore very well.
Pirates: Take most expensive/essentials (engines/hyperdrive/generators) due to A. they need to make a getaway and can't be too weighed down and B. it fits their character to take the loot and then kill you quickly
Remnant: All of it

**Comment by tehhowch** [comment]
>Pirates: Take most expensive/essentials (engines/hyperdrive/generators) due to A. they need to make a getaway and can't be too weighed down and B. it fits their character to take the loot and then kill you quickly
Remnant: All of it

Could be done with a GetGovernment()->GetName() == "Pirate" check, but that is in no way portable. Better would be to use new personalities to define the type of plunder sought. Also, better as an extension (e.g. 2nd PR).

**Comment by endless-sky** [comment]
They used to plunder outfits, and there were a *lot* of confused players who had things stolen from their ships and didn't understand why they were suddenly unable to move, say, once they got repaired. (And occasionally, confused people capturing ships that had previously been plundered only to discover that the ships were no longer flyable.)

**Comment by tehhowch** [comment]
I wonder if a ship should become uncapturable if it would fail the pre-flight checks normally called when leaving the outfitter? Or alternately, showing the ShipInfoPanel for the boarded target alongside the current BoardingPanel, so one can more easily observe that there are no thrusters, no power, (etc) without knowing every outfit in the game by name.

The impetus for the issue was that the initial Remnant defense mission essentially hands the player a few Jump Drives in the form of disabled Raiders. So perhaps a simpler fix is to spawn the Hyperdrive variant for that mission (or a no-drive variant).

**Comment by jafdy** [comment]
How about pirates only steal weapons. I have never heard of a ship the required weapons to work.

**Comment by Hadron1776** [comment]
> The impetus for the issue was that the initial Remnant defense mission essentially hands the player a few Jump Drives in the form of disabled Raiders. So perhaps a simpler fix is to spawn the Hyperdrive variant for that mission (or a no-drive variant).

I think a Hyperdrive variant would be a better choice of the two. Having a no-drive = "well, how did they get here?"

**Comment by tehhowch** [comment]
>I think a Hyperdrive variant would be a better choice of the two. Having a no-drive = "well, how did they get here?"

well clearly, 👽 "Pug Magic" 👽 

>How about pirates only steal weapons. I have never heard of a ship the required weapons to work.
That could be done

**Comment by VonZorch** [comment]
<blockquote>How about pirates only steal weapons. I have never heard of a ship the required weapons to work.</blockquote>
And jump drives, pirates would find them way too useful to leave behind.

**Comment by jafdy** [comment]
@VonZorch That could leave a player stranded without a drive. I was trying to find a simple rule that would never break a ship.

**Comment by nylki** [comment]
> They used to plunder outfits, and there were a lot of confused players who had things stolen from their ships and didn't understand why they were suddenly unable to move, say, once they got repaired. (And occasionally, confused people capturing ships that had previously been plundered only to discover that the ships were no longer flyable.)

Perhaps a message indicating what (which cargo and outfits) were stolen after a plunder would help to alleviate such confusion.

**Comment by VonZorch** [comment]
@jafdy Ok, I didn't think of that, but I always keep my hyper drive when I install a jump drive to retain the ability to make several jumps.

**Comment by Pointedstick** [comment]
@endless-sky 
 > They used to plunder outfits, and there were a lot of confused players who had things stolen from their ships and didn't understand why they were suddenly unable to move, say, once they got repaired. 

That seems easy enough to fix. When pirates steal something from you, display a dialog box saying that! It *should* be a big deal that gets your attention, and not something you would easily miss.

**Comment by tehhowch** [comment]
We could develop a list of banned attributes, e.g. pirates won't take an outfit if taking the outfit would reduce those attributes to 0 / negative. This would be kind-of consistent with loan-shark behavior, wherein you are still left able to function - but barely - because otherwise you can't make them more money.

Then pirates could steal a jump drive if the ship has a hyperdrive too, along with any weapons, batteries, cooling, *extra* engines, etc. So if you cap a plundered ship, it would be guaranteed to be mobile (but probably not very nimble).

**Comment by MessyMix** [comment]
:(
