### ISSUE TITLE
Using timewarp (caps lock) on menu screen causes credits to move at 3x speed

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2797]
When looking at the credits and turning on/off speed warp the credits scroll is effected by it.

**Comment by Bladewood** [comment]
Huh. Did not know you could do that.

I think this is pretty neat.

**Comment by gunqqer** [comment]
I don't know whether this needs to be fixed or not. If anyone has any strong thoughts, please, voice them

**Comment by Hadron1776** [comment]
Capslock speeds up the game engine by making all panels skip frames. So it would affect the game as a whole.

**Comment by solardawning** [comment]
It doesn't seem like a bug to me.

**Comment by gunqqer** [comment]
It is something that was probably unintended though

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/2174#issuecomment-289178543

**Comment by gunqqer** [comment]
@Bladewood I'm confused, how does drone AI relate to this?

**Comment by Bladewood** [comment]
See His comment:
> [It] was never intended behavior in the first place. I just didn't bother to fix it before now because it was sort of humorous.

**Comment by gunqqer** [comment]
aaaaaahhhhh that makes logicyness

**Comment by AdamMil** [comment]
I noticed it, but it doesn't seem like a problem.

**Comment by gunqqer** [comment]
Closing because isn't really an issue, doesn't need to be fixed, and I'm going through my issues to close em
