### ISSUE TITLE
East-side of the galaxy

### ISSUE THREAD

**Issue by kjack1111** [endless-sky/endless-sky#280]
Has anyone seen the un-populated right side of the galaxy? I plan to do a MASSIVE map overhaul of the right-side, and here is my plan

- [ ] Make a map (Will be done not tomorrow, but the day after tomorrow, possibly tomorrow if all goes well) Priority: 8000
- [x] Spaceport descriptions Priority: 3
- [x] Planetary descriptions Priority: 3
- [ ] missions (I need help with this one) Priority: 0
- [ ] storyline (I cant do this. someone do this pl0x) Priority: 0
- [ ] art. Priority: 9000
- [x] anything else i think of

Now lets get to the plot no?

# Good guys

### Aresians
Having downed replication technology, aresians have spread across the eastern side of the galaxy. everything is so dastardly cheap (Inside the 20's) that the republic has put a embargo on there goods to prevent people from getting to wealthy, to fast.

### Mobians
Inhabiting only 1 system, the Mobians are attempting to recover from a massive civil war, known as MWW (Mobian World War) that almost drove them to death.

### Equestrians
Once a united, glorious empire ranging from deneb (No, they didnt enslave the pug. infact, there from the same bloody star system) to generon, It is now split between the lunanesse and the Equestrians, The equestrian democracy revived from a occupied territory after a joint operation between the Mobians, Aresians, And the (somewhat) Neutral Kerbals.

### Icyans (Joke race 1)

After a peace treaty was broken between the icyans and the qwittys, The icyans sided with the alliance (good guys), and Started more readily using kawaii-ium power, weapons, and more. The 2nd of 2 races that can legally use kawaii-ium bombs. 

###### Swizzle: Cyan, black, white.

# Neutral

### Lambians (Joke race 2)
Located in deneb II, and ONLY in deneb II. They are incredibly isolated, and not much is known about them. Sometimes, merchants transport into republican space, looking to sell valuable T0-T3 kawaii-ium

### Cowians (Joke race 3)
Again, not much known about them, but we do know they are semi-hostile (The stink-eye look hostile, not im-going-to-shoot-you-out-of-the-sky hostile), and they have a 5-star system empire.

### Robians
Once part of the Bad guys side, when the alliance fleet reached there homeworld (Generon II), They bribed the alliance to not bother them as long as there neutral, and the bribe succeed, but they still are still not getting humanitarian aid, and they wont as long as the war persists.

###### Swizzle: Red, Black, Blue

# Bad guys

### Lunanesse
Leading the resistance, The lananesse want nothing but universal domination, and will stop at nothing, NOTHING to get it, even driving its own people to Extinction.

### Zalgonians
Not much is known about this reclusive race, incept they are highly dangerous. If you enter there territory, you must get out as soon as possible.

### Qwittyians (Joke race 4)
The Qwittyians are Relativly unknown, but we do know its the 1st of 2 races that can legally use kawaii-ium bombs.

**Comment by gchapyzh** [comment]
SO, I am not sure, but I think the DEV is working on that side right now. I hope your plan does not interfere with his.

Would be nice if different factions on the east side of the galaxy were fighting, so you would have to choose carefully who to team yourself up with.

**Comment by kjack1111** [comment]
Ooooh yeah, there fighting.

Aresians, mobians, equestrians VS lunanese, robians, zalgonians.

Yep, 6 races with more to come.

P.S: he is working on south side of galaxy right now lawl.

**Comment by endless-sky** [comment]
My plan for the rest of the galaxy was for it to be split into various territories, ranging from the size of Hai space to much larger or smaller, with a different alien species in each. Each species could be created by a different person, and would have unique technology and missions, but most of them would be much more advanced than humans. The idea is that once nothing in human space is a threat to you, you can begin exploring beyond human space and find new challenges there.

**Comment by thenerdfreak** [comment]
^^^^ this would make the game interesting again. Majorly. I play with my quarg-outfitted ships for hours blowing up things but that would be a ton more fun, exploring a whole galaxy

**Comment by kjack1111** [comment]
Added alot more, gona add more later today

**Comment by kjack1111** [comment]
[map.txt](https://github.com/endless-sky/endless-sky/files/46419/map.txt)
The new and improved map. Added robians and Aresians, However aresian space is uninhabited? If someone can help with that, that will be greeeat.

**Comment by Oeleo** [comment]
**@thenerdfreak** I agree, be master of the world isn't fun long

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!

**Comment by Saugia** [comment]
Please do not necro old issues.
