### ISSUE TITLE
Parked Flagship should not hide buttons, and should auto-unpark

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2801]
Currently, if you switch your flagship to a parked ship, and then sell your original flagship, you end up with this screen:

![image](https://user-images.githubusercontent.com/20450076/28483273-01966f20-6e9f-11e7-9d21-5c66f67857f3.png)

It's really confusing and it looked very much like a bug to me, since some functions of the planet were hidden. It would be great if a flagship auto-unparks once you assign it, otherwise you can't access anything, which looks like a bug. Any other solutions are welcome too. :)

**Comment by Bladewood** [comment]
The same thing happens if you end up without a flagship in any way.
It even happens at the start of the game, if you refuse to purchase a ship.

**Comment by Hadron1776** [comment]
I think this issue is when you _have_ a potential flagship, but it's parked...

**Comment by MessyMix** [comment]
My opinion: the potential flagship should auto unpark once you assign it, because otherwise you can't do anything on the ground.

**Comment by AdamMil** [comment]
Yes, I think when you select a new flagship it should unpark.

**Comment by endless-sky** [comment]
This is the intended behavior. Choosing whether or not to unpark a ship (and if so, which ship to unpark) should be the player's choice, not something the game chooses for you.

For example, a common situation where this could occur is when the player is upgrading to a new flagship but needs to get a loan. So, they sell their old ship, then visit the bank, then return to the shipyard.

**Comment by MessyMix** [comment]
It would be a lot better if it didn't seem like a bug, especially since the game crashes at exactly this point—when rearranging the ships via the info panel. Perhaps give the full UI, but "block" the player from functions, with a dialogue that says you need to unpark the ship first.

Side note: why can you access the outfitter without a ship?
