### ISSUE TITLE
How to start the main quest line?

### ISSUE THREAD

**Issue by tnnf** [endless-sky/endless-sky#2804]
Hello,

I've been playing for a bit and managed to get a few ships (12 Mules and 4 Bactrians right now), but I have no idea where to go from here. I've read that there's an actual story line. How do I start that?

Also, how do pirate hunting missions work? I can't seem to actually find the pirates.

**Comment by Bladewood** [comment]
Please do not post petty issues like this on GitHub. Go to the [Google](https://groups.google.com/forum/#!forum/endless-sky) or [Steam](http://steamcommunity.com/app/404410/discussions/) forums instead, or try the [subreddit](https://www.reddit.com/r/endlesssky/).

There is one implemented campaign in human space right now. Go spam the spaceport button on Free Worlds planets.

Pirate bounties are always one-to-two jumps away from the system in which they are offered.

**Comment by Hadron1776** [comment]
> Please close this issue

😄

**Comment by Amazinite** [comment]
>Please do not post petty issues like this on GitHub.

To word that a little more nicely:

The ES Github is for feature requests and bug reports. If you're wanting to ask a question, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky), or see if the answer is on the [wiki.](https://github.com/endless-sky/endless-sky/wiki)

**Comment by KiLEdEnNis** [comment]
(small tip: hang around Kornephoros, Sabik and Aldhibain and spam spaceport buttons, do whatever the Free Worlds ask)
