### ISSUE TITLE
"Remnant: Void Sprites 3" typo: who -> whom

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2808]
> He begins singing you a song about the Archons. The song says that the Archons are servants of the mysterious Drak, **who** no one has seen but **who** the Quarg claim to speak to and take orders from.

Since it is [apparently important here](https://github.com/endless-sky/endless-sky/search?q=whom&type=Code&utf8=%E2%9C%93).

**Comment by Amazinite** [comment]
Whom'st've

**Comment by endless-sky** [comment]
Fixed in 274a7de.

Although honestly I think "whom" will have died out from common English usage within the next 50 years or so.

**Comment by tehhowch** [comment]
Not if this game has anything to say about it :laughing:

**Comment by Bladewood** [comment]
Of course it will, but it's fun to be a pedant.
