### ISSUE TITLE
dropping out of time warp when attacked

### ISSUE THREAD

**Issue by AdamMil** [endless-sky/endless-sky#2809]
What do people think about the game dropping out of time warp (Caps Lock) when attacked (using the same criteria that are used to sound the warning alarm currently)? On one hand, with time compression the pirates can be on you in less than a second and that can be bad. On the other hand, later in the game pirates are attacking you all the time but most of their attacks are impotent. (Perhaps it'd be nice if the alarm only sounded and the game only dropped out of time warp when the incoming pirates were actually a threat to the fleet. Maybe a function to calculate fleet power already exists...)

**Comment by Bladewood** [comment]
It's been mentioned before.

**Comment by tehhowch** [comment]
https://github.com/endless-sky/endless-sky/pull/2245#issuecomment-287433674

At 3x, it's not so needed. If the proposed 8x or higher had happened, then I would have pressed for it.

**Comment by endless-sky** [comment]
There are plenty of cases where the player would want to keep fast-forward on, even if there's a hostile ship incoming. For example, it might just be one pirate they want to ignore. Or, they may have a slow graphics card and they're using fast-forward to compensate for a decrease in frame rate in a big battle.

**Comment by Bladewood** [comment]
nitpick, that last part does not apply to me: I have a problem with CPU usage, not GPU. (was better before the creator's update. should move to linux...)
