### ISSUE TITLE
If you select a ship then land and change it to your flagship your new flagship will have the 4 dots around it

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2814]
It looks like [this](https://i.imgur.com/vqT1BCm.png)

**Comment by solardawning** [comment]
Looks like the target selection. Try pressing 1 to clear target?

**Comment by gunqqer** [comment]
Nope, only loading a save un-selects it (or selecting another ship)

**Comment by Jeremy-E-Johnson** [comment]
I have tried to recreate this bug, but i'm having some issues. I'll highlight my method and if there is some difference please let me know.

I first select an escort as my target. Then I land on a planet with a shipyard and change flagship inside the shipyard screen by dragging and dropping. Then when I depart, my new flagship has the targeting dots around it, but i am able to remove them by clicking on just about anything or by pressing the 1 key.

Also, if you could let us know what build you are using, (the steam one or some compiled source code) that would be helpful as well.

**Comment by gunqqer** [comment]
I am using the latest steam build

**Comment by Amazinite** [comment]
Switched my flagship from my Bactrian to one of my Albatrosses.
![screenshot_1](https://user-images.githubusercontent.com/17688683/28590041-b17a9e78-714e-11e7-9f2b-d854094fbcc1.png)

**Comment by endless-sky** [comment]
Fixed in ade229c.

**Comment by gunqqer** [comment]
Leaving Issue open until 0.9.8  comes out so others who notices this (and look for it, like they should) will notice it

**Comment by KyroFirehammer** [comment]
Can we all agree that the albatross looks awesome

**Comment by gunqqer** [comment]
Closing this because 0.9.8 is being relased in like a day and if I don't do this now I'll forget
