### ISSUE TITLE
Remnant: Key Stones assumes you've learned the history of the Hai

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2817]
>You tell him about the Hai: that they once had a vast empire that included part of human space, but that was almost a hundred thousand years ago.

The player could have gone to Hai space, bought a keystone, then be offered this mission without meeting the Unfettered and learning that the Hai were once a vast empire a hundred thousand years ago.

**Comment by endless-sky** [comment]
Fixed in 9ad1db5.
