### ISSUE TITLE
Visual Enchancements

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#282]
I am suggesting improving visual effects for weapons, engines, shields and warping.

> Weapons

Firing should create a light (flash for blasters) the color of the weapon at the firing ship, and a red flash at the ship that is hit. Also, some sort of small light effect at the beam/shot itself.

Missiles should also get a light effect.

> Engines

Ion: Should Create a simple blue beam behind the ship, that fades away when the engines are off. Not too much light, not too flashy.

Plasma: Creates a rather powerful red-orange light; no trail. Grows with engine size, so your Heavy Warship gets a massive light behind it.

Atomic: White, but leaves a glowing trail behind the ship that dissipates with time.

> Shields

Creates a blue glow around the ship when hit. Simple.

> Warping

Entering and exiting hyperspace happens with a sizable flash. You do not see them moving to the exit point, they just blink into existence, leafing a large glow behind them and speeding into the system. Maybe have the glow that is created when jumping stick around, so a ship can scan the hyper-jump point and figure out were the ship jumped.

> Turning and Reverse Thusters

Should create glow but not trail.

> Wreckage

Ships of certain size and greater should break up in 2+ parts (larger ships get more parts, like heavy warships are blown into something like three). Each separate part would act like a disabled ship (vanish on landing etc.) Each large section can be boarded and looted, and each outfit/cargo would have a certain chance of surviving. 

Anyone out there willing to make and implement this?

**Comment by endless-sky** [comment]
The brightness of different sprites has been tuned rather carefully to make sure that the most important things are the most eye-catching. That's why the engine flares are rather dim, for example, and afterburners are brighter.

Some weapons actually already have flashes that appear when they fire (meteors, sidewinders, torpedoes, trackers). Also, all weapons have an effect that is shown when it hits a ship, although for some missiles that effect is just an ordinary explosion. For example, particle bolts flash yellow and proton shots flash red.

**Comment by gchapyzh** [comment]
@endless-sky Its all ever so dull... A powerful flash of a Plasma engine on a capital ship would surely get your attention where its needed! A wall of missiles racing at you should be bright enough so your peripheral vision freaks out and yell "OH NO MISSILE COMING BETTER BOOST SIDEWAYS!"

Still, all the other stuff is good, no?

Also:

> Wreckage
Ships of certain size and greater should break up in 2+ parts (larger ships get more parts, like heavy warships are blown into something like three). Each separate part would act like a disabled ship (vanish on landing etc.) Each large section can be boarded and looted, and each outfit/cargo would have a certain chance of surviving.

**Comment by endless-sky** [comment]
Most of these effects already exist, to some degree. Ships breaking into wreckage would be a cool idea, but it would mean that either a bunch of wreckage sprites have to be drawn by hand, or the game needs some sort of algorithm for splitting a sprite into chunks and altering the image to look "damaged."
