### ISSUE TITLE
Stranded ships with task-based personalities (Mine, Swarm...) ignore assisting ships

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2823]
For example, after The Eye opens to Korath space, there are numerous Earth Shapers flitting about and inspecting the new lands. If you wait long enough in system, an Earth Shaper will end up out of fuel, and be an eligible boarding target. However, despite requesting refueling from other AI ships, it will continue to perform its primary task - surveillance of atmospheres - until one of the many ships trailing it manages to catch up.

This behavior occurs because various behavior checks ([Swarming](https://github.com/endless-sky/endless-sky/blob/6a55cd55c55c7c8d41ac3f02be8d2186d8b52869/source/AI.cpp#L409), [Mining](https://github.com/endless-sky/endless-sky/blob/6a55cd55c55c7c8d41ac3f02be8d2186d8b52869/source/AI.cpp#L472), [Harvesting](https://github.com/endless-sky/endless-sky/blob/6a55cd55c55c7c8d41ac3f02be8d2186d8b52869/source/AI.cpp#L467), [Surveillance](https://github.com/endless-sky/endless-sky/blob/6a55cd55c55c7c8d41ac3f02be8d2186d8b52869/source/AI.cpp#L448), and [assisting others](https://github.com/endless-sky/endless-sky/blob/6a55cd55c55c7c8d41ac3f02be8d2186d8b52869/source/AI.cpp#L587)) occur before the bit responsible for telling the ship to [hold still](https://github.com/endless-sky/endless-sky/blob/6a55cd55c55c7c8d41ac3f02be8d2186d8b52869/source/AI.cpp#L604)

This can be solved by adding a `!isStranded` check in the respective `if()` conditions, but I'm also curious if there are behaviors where this doesn't make sense to fix. (Note that this `isStranded` flag only gets set `true` if the ship is jump-capable and currently lacks the fuel to jump and has someone in their system that has said `sure, i'll come board you`).

A second and related question - if a ship determines that someone has already signed up to assist it, should it stop asking others? Currently, it ignores this tidbit of information and will continue to ask new ships for help (one per frame, max).

**Comment by tehhowch** [comment]
The ignored assistance is fixed by #2828, which reorders the logic path in the ship iteration of AI::Step, and also adds "am i stranded with someone coming to help me" conditions to the personality behaviors that have priority over normal movement and navigation blocks.
#2828 does not address limiting the number of ships which are asked for assistance.

**Comment by endless-sky** [comment]
Fixed by merging #2828.
