### ISSUE TITLE
Have all galaxy labels despite never visited them

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2826]
Related to my last galaxy label one, but this time I have them without ever visiting them at all(the bugfix for that may fix this I don't know).
![screen shot 2017-07-25 at 9 44 40 pm](https://user-images.githubusercontent.com/29336153/28602295-dc893e92-7182-11e7-93a8-57ec9cf0283f.png)
![screen shot 2017-07-25 at 9 44 35 pm](https://user-images.githubusercontent.com/29336153/28602296-dc8c36c4-7182-11e7-9910-6cde0ffd897a.png)
![screen shot 2017-07-25 at 9 44 29 pm](https://user-images.githubusercontent.com/29336153/28602297-dc8ff250-7182-11e7-9f9d-e8efe5f4725f.png)

**Comment by Rob59er** [comment]
and it's gone I don't even know what this game does at this point

**Comment by Bladewood** [comment]
uh... did you happen to reload (restart?) the game?

**Comment by Rob59er** [comment]
no they just disappeared after a couple jumps
