### ISSUE TITLE
Very minor suggested edit (rename "Reverse Thruster")

### ISSUE THREAD

**Issue by PhoenixRiver** [endless-sky/endless-sky#283]
This is really minor but can I suggest (for the sake of the outfit orderings and having the atomic "Reverse Thruster" next to the other Atomic Thrusters) that the "Reverse Thruster" be renamed either "A120 Reverse Thruster" - since it has the same power as the "A120 Atomic Thruster" - or "A110 Reverse Thruster" - so it comes as the first atomic thruster and is harder to confuse with the A120 - or else "A90 Reverse Thruster" - so it comes at the end of the list of atomic thrusters to definitely avoid confusion with the A120 as well as being less far from its current position (and so confusing current players less :)

**Comment by endless-sky** [comment]
Unfortunately, I can't change the name without messing up every player who has one installed (although I could add one with the other name and just leave the old one in place as a legacy item, I suppose).

**Comment by PhoenixRiver** [comment]
It might be worth doing... might it be possible to convert those sold
to the outfitter but then bought back into the new one? That would
mean that over time they would be moved to the new version... but I
guess better would be a conversion routine for all save files - at
least then you could remove it after a while since it would have
backdated the fix... a little ricky messing with saves of course!

**Comment by dplepage** [comment]
@endless-sky Couldn't you add a `displayName` to `Outfit` like you did for `Mission`? Then you could rename outfits at will without touching save files at all.

**Comment by endless-sky** [comment]
I've renamed it to "AR120 Reverse Thruster." The plain "Reverse Thruster" outfit is still in the game data for players who already own one, but now only the "AR120" is on sale. (The two have identical attributes.) Commit: abb6c1a.

**Comment by Wrzlprnft** [comment]
Is it possible to place references in the data-.txt-files? because that way the information is redundant

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
