### ISSUE TITLE
Fleet not following through jump 

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2830]
This is probably not reproducible, but it has happened to me as three different pilots in 0.9.6

After making a few jumps back and forth from 2 systems, some of my fleet got stuck and would not follow.  I tried explicitly setting and unsetting 'h'old position, using 'g'ather, etc.  Ships had fuel and the capability to jump. and i tried landing and taking off, without change.  I could even reload the most recent pilot instance and even waited more than half an hour at one point.   However, if after landing, i quit the game & reloaded, the ships jumped just fine. 

I've tried reloading a prior save and reproducing, but can't seem to do it on demand.

As it has happened multiple times, i figured it was worth mentioning, even if i can't tell you how to reproduce.

**Comment by Bladewood** [comment]
This may happen if your ships gain enough fuel (via ramscoop or ship refueling or something else) for a jump when they are in a different system.

**Comment by tehhowch** [comment]
If you can reproduce in 0.9.7, let us know. There have been several changes to parent - escort behavior.
Likely the issue was with the ships having a specified target system and not knowing how to route to it.

**Comment by endless-sky** [comment]
Was one of the systems uninhabited? Ships won't follow into a system where they can't refuel if they only have one jump of fuel left.

**Comment by marphod** [comment]
Just happened again, without jumping back and forth.  Flying from Ap'arak to Wah Ki (distance 4 jumps, 500 fuel as all my ships have both jump drives and hyperdrives).  All my fleet has 600+ fuel capacity. 

I briefly aborted autopilot in Wah Yoot, but restarted the jump before all my ships had arrived in Yoot.

Most of the fleet made it to Wah Ki (15ish of 20ish), but some stopped in Wah Yoot and would not jump to Wah Ki until I restarted the executable.  Wah Yoot is currently hostile, but as the ships had fuel and were leaving, not entering a hostile system, that shouldn't matter. Still 0.9.6 .

**Comment by tehhowch** [comment]
@marphod now that you have 0.9.7, can you reproduce this issue? I'd prefer if you used the latest `master`, but if you can't confirm with 0.9.7 then this issue can be closed.

**Comment by marphod** [comment]
The problem is that it was intermittent at best.

I've not seen it on 0.9.7 yet.  I've also not been aborting flight paths or doubling back a lot in 0.9.7 .  I'll try to explicitly test that tomorrow.  Er, later today. When did it get to be 2am? =)

**Comment by marphod** [comment]
I've not been able to replicate on 0.9.7; closing under the assumption that this was fixed with version update.

**Comment by jonnybot0** [comment]
I've just had a very similar experience to this in 0.9.8 (1).

Basically, some of my fleet won't make the jump from the Deneb system to anywhere else. When I hold down the jump key, they're surrounded in red. They had made the jump _to_ Deneb just fine, and they've recently refueled. I've not updated their outfits.

I've attached my save file, along with a few of the previous saves. The ships that seem unable to jump are:
Nergal's Nightmare (Bastion)
Hopeful Calypso (Bastion)
F. S. Bruce (Falcon)
Queen of Hatred (Vanguard)
Reign of Babi (Protector)
Thunder Ravenna (Falcon)
T. T. Zion (Osprey)
Bloody Poison (Osprey)
Rover of Ragnarok (Firebird)

I can't account for what's different, or why they would be unable to jump.

[Guy Smiley.txt](https://github.com/endless-sky/endless-sky/files/1609794/Guy.Smiley.txt)
[Guy Smiley~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/1609795/Guy.Smiley.previous-1.txt)
[Guy Smiley~~previous-2.txt](https://github.com/endless-sky/endless-sky/files/1609796/Guy.Smiley.previous-2.txt)

**Comment by jonnybot0** [comment]
Also, I've yet to find a way to rectify the issue.

**Comment by tehhowch** [comment]
Fixed in v0.9.9
See issue #3012

**Comment by jonnybot0** [comment]
Hm, okay, good to know. Guess I'll just wait for that release then. Thanks!

**Comment by tehhowch** [comment]
In the meantime, you can rescue your ships by removing their "destination system" from your save file . (It is stored so that mission ships which should travel in a certain direction do so even if you restart the game.)

**Comment by moeffju** [comment]
I think I had this happen in 0.9.14. Escort mission, the escorted freighters just got stuck in a system and wouldn't move, not even inside the system. I tried jumping in and out, the only thing that fixed it in the end was landing on a planet in that system.
