### ISSUE TITLE
Enhancement Request: data/save file version numbers

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2831]
Given how clean the code looks, from my brief examination, and the obvious design throughout, that the files aren't versioned surprises me.  Odds are high that at some point, there is going to be an incompatible change made, and it would be nice to be able to detect and handle it gracefully if someone is using an old plugin or save file, or there is an error or conflict when updating an install.  

(it also means you wouldn't need to ask what version their save file is from to repro bugs)

**Comment by tehhowch** [comment]
There are very few, if any changes made to save file reading and writing that make old syntax invalid.

That is to say, a code change which breaks backwards compatibility will almost certainly not merge unless it was both conceived and implemented by MZ.

In other words, any save file from any older version of the game should load just fine in the current version of the game. The reverse is, naturally not true, but only those who are hopping between beta and stable will notice, and anyone who participates in beta content should know enough to keep a backup save.

Regarding writing of the game's version into the save - game version bumps are rather infrequent, and I don't see much value in including `version 0.9.7` in every save file.

**Comment by endless-sky** [comment]
Changes that would break backward compatibility aren't allowed, so there's no reason to version the saved games.

If someone's posting a save, asking them to also specify their software version isn't too difficult.

**Comment by gunqqer** [comment]
There's a reason why we have depricated.txt so backwards compatibility is always 100% which is awesome!

**Comment by marphod** [comment]
Uhm, gunqqer, that's something entirely different.  deprecated.txt is about content -- it holds items that were in the game but are no longer. 

File format is about how the data is stored. you can store your resume in a file.  deprecated.txt would have all the elements of your  resume that you trim off at some point -- lack of specific relevance, or a job that was 20 years ago, or you high school information after you graduate college.  File format is storing it as a pdf or ms word or open office file. 

File versioning means that you can change the way things work under the hood without things breaking.

Say that currently, when you define a missile-style weapon in the data files, you MUST define how much damage it can do.  If you don't, it is an error. (i don't know if this is true or not, it is just an example)

There is an enhancement request that would allow missile-style weapons to use different types of munitions.  One way to implement this would be change the definition of missile weapons so they MAY NOT include damage, but must list what ammunition it can use, and the missiles must define the damage.

if this is done, then reading in an old data file that used to be fine would break -- if there is a missile style weapon in my save file for some reason, there would be an error on load.

If you version the files, you can detect that, and parse it based on what was legal at the time the file was created.

If there really will never be any breaking changes, then you don't need to version files.  I am, however, skeptical.  I've run into plenty of projects where we've figured out there was a better way to do something but it would require an incompatible change. When the protocol/format/interface was versioned (well), it has been trivia.  When it hasn't, i've done insane leaps to kludge it, or had to leave the prior, often wrong, way in.

**Comment by gunqqer** [comment]
The point I was trying to get across  is that we want backwards compatibility and would rather not break peoples saves to change the game how we want it to be. If we did that we'd have to make the game a lot bigger keeping everything from older versions and use more processing power to always be going back and forth. If we ever get no backwards compatibility on an update that update would probably be a massive update that changes how everything (code wise) works. Other than that I can't support breaking old saves

**Comment by endless-sky** [comment]
If a change were ever introduced that made previous saved games incompatible, a version number could be introduced at that point. Saved games could then be identified based on whether or not they contain a version number. So, there's no need to preemptively introduce one just on the off chance that it might one day be needed.
