### ISSUE TITLE
Inhabited planet with no spaceport showing as restricted on the map

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2832]
So I'm working on a mission where the Fourth Spaceport on Lodestone has an unfortunate incident involving the nearby volcano.
![screenshot_1](https://user-images.githubusercontent.com/17688683/28649910-37462d40-7246-11e7-848b-35f056e6fd73.png)
The planet has no spaceport but is considered inhabited. On the map the system shows as restricted.
![screenshot_3](https://user-images.githubusercontent.com/17688683/28649912-3870705e-7246-11e7-99ad-9353b792adf9.png)
But if I enter the system, the planet will let me land without requiring a bribe.
![screenshot_4](https://user-images.githubusercontent.com/17688683/28649913-3937a4d0-7246-11e7-9a07-4e877a24aadc.png)

**Comment by Bladewood** [comment]
I believe the reason had something to do with being able to refuel.

**Comment by Amazinite** [comment]
It seems odd that in most cases a yellow system on the map means you need to bribe to refuel, but in the single case in the game where this could occur (the Wanderer spaceport getting ganked by the Sestor) yellow means there's an inhabited planet that you can't refuel on.

**Comment by tehhowch** [comment]
MapPanel::DrawSystems() is what handles this stuff

**Comment by Amazinite** [comment]
Yup, it's fixed.
