### ISSUE TITLE
Enhancement Suggestion: Add Swizzle Selector to Player Info/Ship Panel

### ISSUE THREAD

**Issue by solardawning** [endless-sky/endless-sky#2833]
Suggestion:

Now that support for individual swizzles on ships exists, a swizzle selector could be added to the Ship Panel.
There's room to put button pips as a selector underneath the Energy/Heat information, without modifying anything else in Ship Info.

Ideally, swizzles would be unlocked by gameplay events.
I'd suggest the following conditions for unlocking access to the selector, and specific swizzles:

- Default - removes customSwizzle for that ship, so it will use the swizzle of the Escort government
- Merchant - unlocked at conclusion of Free Worlds Campaign _(Allows player to change back to Merchant if they want to)_
- Free Worlds - unlocked at conclusion of Free Worlds Campaign _(At this point, the player may switch between Free Worlds and Merchant at will on individual ships)_
- Pirate - unlocked after completion of some number of illegal/Pirate jobs

**Comment by Bladewood** [comment]
too much freedom?

**Comment by Amazinite** [comment]
Merchant and Free Worlds would only make sense to be freely changeable after the war.

**Comment by Amazinite** [comment]
If this were to become a thing, swizzle changing would make sense to be disabled during the war after you choose sides (so a player couldn;t change to the pirate swizzle during the war).

**Comment by tehhowch** [comment]
While there is indeed room on the ShipInfoPanel, there isn't a nice visual feedback there - only the outline of the ship is shown, and the interior is only black:
![image](https://user-images.githubusercontent.com/20871346/28651658-bd5ec5ac-7248-11e7-9ab4-58054a24dcdb.png)
Changing to display the sprite will make distinguishing hardpoints a bit more difficult, but also will make the hardpoint sprites more visible (and also highlight ships where the positions don't match up to specified hardpoint locations)
