### ISSUE TITLE
Enhancement Request: get ES building on Windows using scons under cygwin

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2834]
at least, I assume it isn't working yet, as there is nothing about it in the wiki.

I can give it a shot; its the sort of thing I've done before, although I'm rusty.

**Comment by tehhowch** [comment]
if you have the ability to use a GNU makefile, try using a GNU make equivalent with the .winmake file from my pull #2786, e.g. `make -f .winmake release`

**Comment by marphod** [comment]
A GNU make equivalent, like GNU make? =)



My personal preference is to have the exact same build procedure for all platforms; if done right, that means less work and fewer opportunity for platform-specific bugs above the platform-specific API layer.

**Comment by tehhowch** [comment]
The "work" for alternative OS beyond linux is "get the programs that are needed and configure them", which is not something that can be automated away - the user gets to tell MinGW where to be installed to, and which version should be installed, where to save the dev64.zip / dev32.zip assets, etc. MZ has done the harder parts, building and packaging exportable resources (dev64.zip), creating the project files that will convert the source files into the executable, etc. (and done so for freely available IDEs CodeBlocks and XCode).
If #2786 merges, there will at least be a simple instruction set included in the distributed ES repo.

**Comment by marphod** [comment]
Cygwin sets up a directory structure that mirrors linux, runs bash within it, and presents a uniform build environment.  Assuming that all the libraries/build resources are available for cygwin, which they usually are, the build instructions need not be any harder than linux.  'install cygwin, these are  the package dependencies, this is the url for source control, have at it.  we use git and scons.'

**Comment by endless-sky** [comment]
Setting up Cygwin and building in the command line would probably be a lot harder for most people than installing and working with Code::Blocks is.

**Comment by marphod** [comment]
Never said that cygwin would deprecate code::blocks.  just making it another option.

**Comment by marphod** [comment]
For what it is worth, I'm compiling on cygwin fine, with only adding an include path to scons (and that may be due to me selecting the wrong package, trying to fix that now).. 

I needed to do some tuning of what packages need to be installed (name changes from linux, & somethings you wouldn't need to explicitly install on linux like zlib) 

Now to get everything linking

**Comment by marphod** [comment]
linked fine, won't start:
`AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
Unable to query monitor resolution! (SDL message: "Video subsystem has not been initialized")`

i'll look into it more later.
