### ISSUE TITLE
Notably slower/higher CPU load (but playable after dropkicking my laptop): 0.9.7 v 0.9.6 (Windows64 bit)

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2835]
Updated to 0.9.7, and the game is nearly unplayable f i encounter more than a handful of hostile ships,

My system is a rather modest  windows laptop (Celeron N3050@1.6 GHz, 4G RAM, integrated graphics), but 0.9.6 was playable.  large combats had a slowdown, which was annoying but live-able.  the internal CPU monitor would spike to 90-120% (I assume that 100% is 1 core fully utilized, but i'm not sure) and GPU would spike to the 70-80% range (normal was 40% CPU and 30% GPU).  Only Performance option were hyperspace flash and showing the cpu/gpu status.  

with 0.9.7, the baseline is 70-80% cpu and 40% gpu. and the game feels sluggish. Modest fleet combats (one kor mereti, my fleet of 25) become ridiculously slow, (effectively sub-20 fps, choppy, some delays in sound, running at what feels like 1/3rd speed) and reported CPU of over 600% (i'm not sure what that  even means on a dual-core system) and 180% GPU, even when most of the ships were off-screen.   Turning on time warp returned to only slightly slower than the new normal, but was in single-digit Fps.  For what it is worth, speed slightly improved, i think, with 'focused' turrets rather than independent.  Turning off the minimap or labels did not appear to change anything.

Background apps and os activity did not change between runs.

What stats/debug logs can i generate to help?

**Comment by tehhowch** [comment]
CPU / GPU time indicate how many 60ths of a second is needed to compute / draw 1 frame. so 100% utilization means you need 1 frame to calculate or draw 1 frame. If you are playing self-compiled, please be sure you are not running a debug exe. Expected x64 Windows 10 EndlessSky.exe sizes are in the ballpark of 1700 - 2100 kB, while a debug build will be in the 120 MB range. (`scons` output for me on linux gives a 2.4 MB binary and 46 MB debug binary).

You may obtain some improvements by changing/adding a compiler flag, `-march=native` to the build, but by and large without improvements to the game engine your choices are limited.

You can test out my changes in #2788 to see if they improve performance, but I think for such small lists there will not be much improvement.

**Comment by MCOfficer** [comment]
if you want to go really deep into troubleshooting, try to compile source code from different times after the 0.9.6 release. for example, start by compiling the source code from 4 weeks after 0.9.6, if it runs stable, skip another 4 weeks and compile again, until you can narrow it down to the commit that seems to make the difference (if it's only one commit).

obviously that will be a lot of work, but in case this is not just you, we would need that kind of intel. the game should run smooth on a pc like yours.

**Comment by tehhowch** [comment]
An easier "try many commits" approach is to use the `git bisect` command. You'll want to back up your current save, in order to restore it after you finish using `git bisect`

example:
```
git pull upstream master
scons
./endless-sky
(observe bug / poor behavior)
git bisect start
git bisect bad
git checkout v0.9.6
scons
./endless-sky
(duplicate test flight to observe behavior, choose 'good' or 'bad' as necessary)
git bisect good
```
Once you've found a good commit and a bad commit, git will then automatically check out commits for you, and once you build and test that specific binary, use `git bisect good` or `git bisect bad` as appropriate to get the next commit to test.

**Comment by marphod** [comment]
I am running from the binary distribution.

After a few reboots, reinstalling my video driver and removing/reinstalling the last OS update, things are back to reasonable.  Slower by far than 0.9.6, by around 10-15%, but the average is playable and fleets only go to 100-150%.  

(I hate windows.  But too many tools and games I use are windows based and this laptop would not do well running them in a VM.  Gah.)

**Comment by Bladewood** [comment]
Blame the Creator's Update!

**Comment by endless-sky** [comment]
This is almost certainly due to the limited turn speeds for turrets (and the opportunistic tracking). Previously, turrets never had to do calculations to see whether they were pointed at something, because they could point wherever they wanted - so all they had to do was a range check, which is much more efficient.

The code probably need another round of optimization, now. I just keep putting it off because I'm planning to overhaul the AI at some point anyway.

**Comment by marphod** [comment]
On the optimization front, if it would help to run a debug version and/or attach a profiler and collect data for you, let me know.

**Comment by tehhowch** [comment]
@marphod there are debug and profile modes in the SConstruct file
`scons mode=debug`
and
`scons mode=profile`

for GDB and gprof compile flags, respectively.

**Comment by tehhowch** [comment]
Frame calculation times during combat in asteroid-heavy systems should be a lot lower now due to the extension of CollisionSet to asteroids. Turret-turn code is still heavy for large numbers of in-system ships though.
