### ISSUE TITLE
New transport ship for end game use

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2838]
Ok so we all know that the bact is OP but I think an interesting idea to balance it a bit would be to add a new transport ship to allow for a variety to ships ex: someone could use it to capture ships after large battles or mabie being a viable option to use for capping world ships or even a skylark I personally think it would be cool to have it be from the coalition as a expensive collaborative ship from the 3 series that could have great crew bunks and decent cargo but have low usage for offence to keep the challenge of the capping of skylark and the like 

Any feedback would be appreciated to pottentaly make this ship into the game

**Comment by tehhowch** [comment]
>Ok so we all know that the bact is OP but I think an interesting idea to balance it a bit would be to add a new transport ship to allow for a variety to ships ex: someone could use it to capture ships after large battles or mabie being a viable option to use for capping world ships or even a skylark I personally think it would be cool to have it be from the coalition as a expensive collaborative ship from the 3 series that could have great crew bunks and decent cargo but have low usage for offence to keep the challenge of the capping of skylark and the like
>
>Any feedback would be appreciated to pottentaly make this ship into the game

You should use punctuation marks when communicating ideas.

Capturing Korath World-Ships is not likely to be a part of the main game (you can easily do this with plugins). Developing content explicitly related to existing Quarg content is also not likely as the current Quarg content is a placeholder. When the plot has matured further, Quarg content will be revisited.
The current capturing mechanics are already too skewed in the player's favor, and I highly doubt any changes will be made that make it easier to capture high-tier content.

**Comment by KyroFirehammer** [comment]
It's possible using the eye personnel have almost done it twice but I lack quarg tech and the quart kill it to fast

**Comment by KyroFirehammer** [comment]
QUARG STUPID AUTOCORRECT

**Comment by KyroFirehammer** [comment]
It would also give a nice purpose for the coalition other than their repair modules

**Comment by MessyMix** [comment]
1. You can edit. So don't post corrections.
2. Please stop with the spamming. Post once, coherently. Otherwise 97 people's mailboxes overflow.
3. I have no idea what you're saying.
>It's possible using the eye personnel have almost done it twice but I lack quarg tech and the quarg kill it to fast

Like what even is that supposed to mean!? What's possible? What is the eye personnel? The quarg kill what too fast?

4. Coalition already has purpose. Their freighters are excellent, the Spire is great. And Heliarch are epic. :)

**Comment by Amazinite** [comment]
This doesn't really feel like a post fit for Github. You should ask for stuff like this over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky).

**Comment by Pointedstick** [comment]
I feel like seasoned contributors like @Amazinite should have the power to close other people's issues to help keep Michael from having to deal with this kind of spam.

**Comment by tehhowch** [comment]
@Pointedstick it's possible to do by granting the ["collaborator" role](https://help.github.com/articles/permission-levels-for-a-user-account-repository/), but this also gives a lot of other permissions. 
I'm not saying those permissions would get abused, but that possibility exists. I'm sure MZ sleeps a little better at night knowing that he is the only one who can add code to the base game, either directly (push) or via Pull Request.
If collaborators are added, it's worth noting that only MZ has the ability to add new collaborators. There are also steps one can take to limit the ability of collaborators to merge PRs, such as requiring MZ to review one before it gets merged (see protected branches).

(I support this request)

**Comment by Amazinite** [comment]
>I feel like seasoned contributors like @Amazinite should have the power to close other people's issues to help keep Michael from having to deal with this kind of spam.

I don't want that power, nor do I really think there's a need to give it out.

**Comment by endless-sky** [comment]
Actually, now that outfit expansions are nerfed, technically there's no reason not to let players capture World-Ships. I'm considering reducing their required crew so that you can get lucky and find one that's capturable, and also adding World-Ship bounty missions in Remnant space so that there's a way to capture them without attacking the Kor Efret.

**Comment by Bladewood** [comment]
ohgod

**Comment by gunqqer** [comment]
Oh damn vanilla world ship capping, almost time to scrap my best skylance rifles!

**Comment by Amazinite** [comment]
World-Ship bounties? Sure.
More easily capturable World-Ships? [No](https://youtu.be/umDr0mPuyQc?t=3s).
While on the topic of outfits expansions and the World-Ship, maybe un-nerf the cargo space?

**Comment by solardawning** [comment]
Yes, a world ship in player hands would let them capture Quarg ships... but I don't think that's a big deal anymore, either.

There's already a better ship that the player can* capture in unlimited number.

Consider: Quarg ships have 4 turret ports, zero gun ports, limited engine and cargo space, and extremely high crew requirements. (High cost to operate).

Heliarch capital ships, on the other hand... are just as tough, are faster, use less crew, and have more gun/turret ports and a lot more outfit space to play with.


*yes, capturing Heliarch ships requires using a 'trick' to earn Heliarch reputation, namely bringing Quarg ships (as mission escorts) into Coalition space, letting them fight, and then boarding and repairing disabled ships to earn reputation.

**Comment by KyroFirehammer** [comment]
Not to make the Worlds Easter but to give a better option whether visually or in some other way to put less of a felling of the next being the best at everything aliens should have ships better than the fact in ways other than combat or the deep river

**Comment by KyroFirehammer** [comment]
I don't see why a ship like this isn't when I first saw coalition transport  ships I thought they would but nope

**Comment by KyroFirehammer** [comment]
On a side note it would be interesting to see potentially to go along with the wanderers part 2 to have a few kor missions to allow for purchase of the minelayers and ammo and potentially some small ships like their fighters and such

**Comment by KyroFirehammer** [comment]
At a price of course much larger than most due to their "limited supply" or something fore lore purposes

**Comment by KyroFirehammer** [comment]
For

**Comment by KyroFirehammer** [comment]
On thorough rereading of the first post I realised my autocorrect kept rewriting what I was saying

**Comment by Hadron1776** [comment]
> - You can edit. So don't post corrections.
> - Please stop with the spamming. Post once, coherently. Otherwise 97 people's mailboxes overflow.

**Comment by KyroFirehammer** [comment]
Oh sorry about that

**Comment by MessyMix** [comment]
@solardawning, the problem with capturing Quarg ships is that the Quarg aren't a completed species, as we haven't entered T3 territory in terms of the storyline yet. So letting the player experience uncompleted / placeholder content will make us run into the same problems as, well, demanding tribute: people will complain that it's incomplete ("where are all the outfit sprites!?" "why is it a heavy warship when it's worse than the medium Arfecta?" "XXX is unbalanced, pls fix", etc.). So that's why, IMO, Quarg stuff should be left exclusively until the race is complete.

Please, please, do not let us capture Worldships. :)

**Comment by KiLEdEnNis** [comment]
(you can turn off mail notifications but not everyone wants to)

**Comment by KyroFirehammer** [comment]
Little late I just about have one. I've capped and it's saved but event gotten through wormhole yet

**Comment by Pointedstick** [comment]
> Little late I just about have one. I've capped and it's saved but event gotten through wormhole yet

# Nothing you're posting makes any sense. Please take this discussion to the [Steam forum](http://steamcommunity.com/app/404410/discussions/0/) or [Google group](https://groups.google.com/forum/#!forum/endless-sky) and close the issue.

**Comment by KyroFirehammer** [comment]
Ok guess nobody likes my ideas........

**Comment by Pointedstick** [comment]
Your ideas may be brilliant, but none of us can tell what they are because of your inability to write comprehensible English. Work on your communication skills and you won't run into resistance like this.
