### ISSUE TITLE
Another very minor issue (Javelin Pod)

### ISSUE THREAD

**Issue by PhoenixRiver** [endless-sky/endless-sky#284]
So I was checking out the missiles available and was slightly confused for a moment because out of the Human and Hai missile launchers (I've only met these two's outfitters so far) the "Javelin Pod" is only one to have its capacity listed above its mass (the others show their mass and then their capacity)... the main reason I mention this is because it seemed odd and maybe possibly indicative of a bigger issue? Or maybe it's just one of those things like typos! :)

Hope this helps :)

**Comment by endless-sky** [comment]
That just happens because the outfit attributes are displayed in alphabetical order, and "javelin" happens to be the only missile name that comes before "mass."

**Comment by PhoenixRiver** [comment]
Ah! Sorry, didn't notice! Well that explains it :)
