### ISSUE TITLE
Unable to select wormhole not on jump path

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2840]
http://steamcommunity.com/app/404410/discussions/1/1471966894867277108/

To reproduce
1) Go to Cardea
2) Map a route that would lead you through one of the wormholes
3) Try to select the other wormhole

It would be expected that the wormhole you click on would be selected, but instead the game rapidly switches to selecting the wormhole on your jump path.

**Comment by tehhowch** [comment]
Interestingly enough, you can hover over the "wrong" wormhole and then rapidly press L... you will start going to land on the "right" wormhole, but if you are fast enough, you will start shrinking (and rapidly accelerate too!), and travel through the "wrong" wormhole (ending up in its proper destination).

This has to do with the opening bits of AI::MovePlayer(), as it checks only that you have a travel plan defined, with no regard for if you have selected a TargetStellar that does not coincide with it.

There are no planets in the base game that define a wormhole that you can make travel plans through, and also have a planet you can land on, but I imagine this bug would prevent you from landing on said planet as well.

**Comment by tehhowch** [comment]
(almost ready with a fix... just checking for unintended bugs)

**Comment by tehhowch** [comment]
Fixed by #2845
