### ISSUE TITLE
Wanderer plot confusion (some spoilers)

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2841]
After 'Wanderers: Sestor: Quarg Help 2' I was confused, when the Quarg didn't accompany me to the Alpha base.

Checking the plot file, that looks intentional, but it was unclear from the dialog that Danforth was sending the pc to get Quarg to defend farpoint -- i though he was sending me to get a strike force to assist with the attack. I'd like some stronger dialog clue to that distinction.

**Comment by gunqqer** [comment]
````	He leaves to try to find help, and returns about fifteen minutes later. "I've got four Quarg ships who volunteered to help," he says. "That may not seem like a lot, but their ships pack quite a punch. Good luck, captain."`
			`	You thank him for his assistance, and hurry to fire up your ship and return to human space. Hopefully Danforth's base has not already been overrun in your absence.````

So this is the dialog you're talking about (I think.) The last sentance is what I suspect is what tells you that they are there to defend. 

````	Sadly, you shake your head. "They have dozens of capital ships," you say. "That was probably just the vanguard of their fleet."`
			`	Danforth sighs. "I got a taste of how powerful these Korath ships are during our attack on the previous Alpha base," he says. "I'm not sure I can stand up against a whole fleet of them. Our only hope may be the Quarg. They have a ringworld in Hai space. In fact, isn't that where we left your friend Elias?" You nod. "You should go there immediately," says Danforth. "Hopefully, you will be able to bring back help in time."````

That is "Wanderers: Sestor: Quarg Help 1" where you get sent to get quarg to help. The dialog implies that the only way for the base on Farpoint and it's fleet can survive is by getting quarg help. It wouldn't make sense to get the quarg only to attack somewhere else. (Also the quarg would never agree to help attack somewhere, they'd only defend)

**Comment by Rob59er** [comment]
I honestly find it perfectly clear.

**Comment by KyroFirehammer** [comment]
Makes sense to me
