### ISSUE TITLE
Drive toggle feature

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2842]
As I am currently playing the game I am noticing on my deep river (which has a jump) that where i am running missions that it would be nice to have the ability to instal both a jump and hyper drive on it to almost have an  "economy mode" similar to ones on certain cars to save on fuel (or in the case of a warship to jump in with the fleet into a large battle and not be instantly swarmed before the rest get there). This would also be handy for scram drives if not leaving somewhere being chased by pirates in early game

**Comment by Bladewood** [comment]
... You can?

iirc, if you have both a hyper and jump drive, it uses the most fuel-efficient method to get there.

**Comment by KyroFirehammer** [comment]
Nope as it currently stands jump overrides hyper (but it might be that my jump was on before my hyper

**Comment by Amazinite** [comment]
Are you sure you have both a jump drive and hyperdrive installed? Currently your ship will use the most efficient drive. i.e. it's not going to use a jump drive to cross a hyperlink.

**Comment by Hadron1776** [comment]
@KyroFirehammer Jump overrides hyper _only_ when there's no hyperspace link to your destination.

**Comment by KyroFirehammer** [comment]
Ok see nevermind I just retorted and it worked idk if it was an error bit unless anything new comes up I'm going to close this then

**Comment by Pointedstick** [comment]
So please close the issue.

**Comment by KyroFirehammer** [comment]
Closed
