### ISSUE TITLE
Missions are not cleared when planet changes government.

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#2843]
Specifically, I accepted several missions to Varu K'est before the Unfettered took it.  Now they control it, so I can't land to complete the missions.

Should the game automatically abort the missions when the government of a planet changes like that?

**Comment by endless-sky** [comment]
It'd be way too complicated to hard-code all the situations where that should happen, since there are plenty of other times when a planet changing owners should not cancel missions (e.g. a Republic planet converting to the Free Worlds).

**Comment by Amazinite** [comment]
Missions can already fail when they become impossible through something like destroying a ship that had cargo you were suppose to steal, right? This seems like a situation where missions should fail if the destination planet is unbribable and no clearance is given.

**Comment by tehhowch** [comment]
Would it be instead possible to extend the GameEvent to handle missions?
I'm imagining a syntax such as 
```
mission fail
    destination "<insert planet name>"
```
In addition to destination, `source` would make sense.

**Comment by endless-sky** [comment]
The trouble is, there are situations where the player would want to hold onto one of those missions until the planet becomes accessible again (e.g. if you get an archaeology follow-up mission halfway through the Free Worlds story). It's much safer to just let the player manually abort those missions than to assume you know which missions should be aborted. (And, I think that missions silently and automatically being aborted, but only under certain conditions, would be more confusing to the player than just having them abort them by hand.)

**Comment by tehhowch** [comment]
What would happen if a mod were to define an event that destroys/removes a
planet, and the player has missions to that planet?
As I understand it, the modder would need to redefine the system to remove
the relevant stellar object. What would happen if the player opened their
job list and selected an existing mission to that planet after it's
"destruction"? Normally the map view will recenter to the system containing
the planet.

Even if it is not used by the base game, the ability to revoke all missions
for a specific planet/system/government seems like a useful modders tool.

**Comment by kyzentun** [comment]
I should have said this sooner, I agree with endless-sky on this.  The likelihood of the system clearing the wrong missions and causing some hard to diagnose problem is too high.  For example, a case where the story gives the player an invisible mission to mark them for a later one.

Mission failing GameEvents would probably also require having mission categories, so that the event wouldn't accidentally clear story critical missions.
