### ISSUE TITLE
Not all plunder shows as "in stock"

### ISSUE THREAD

**Issue by spazstatic** [endless-sky/endless-sky#2849]
I picked up outfits from a disabled ship and among other things, there was a RT-I Radiothermal and a Supercapacitor. When I next landed and checked the outfitters, not all looted outfits show as "in stock". In the attached image you can see that I have the option to install the super cap, but no quantity is listed in stock like for the generator.

As a side note, why can't I sell looted outfits from the outfitters if say, I wanted to keep one or two of them for later use but sell the rest? As far as I'm aware you can only sell all in the commodity exchange.

version 0.9.7, windows 10, steam install (beta branch selected)

![capture](https://user-images.githubusercontent.com/30455085/28746503-35e0c10e-7453-11e7-99d7-52df488c0875.PNG)

**Comment by tehhowch** [comment]
This is updated for 0.9.8, which returns to the "old" behavior of the outfitter, where cargo outfits are not shown as 'in stock', and hitting the sell key removes first from cargo, and then after all that outfit is gone from cargo, the selected ship.

I also have a PR that would allow you to remove directly to cargo, with the applied 0.9.8 changes ( #2806 ), via the `r` or `u` keys (remove, uninstall, unequip).

**Comment by spazstatic** [comment]
Sounds great! I thought I remembered being able to sell individual outfits when I first started, but steam news showed the 0.9.7 beta available the day after I started playing so I switched to that.

Will the button change from "sell" to "uninstall/store" with this change? Will this allow you to buy outfits directly to cargo so you could round up all the desired equipment for a ship before buying the ship, or will you have to buy to equip, then move to cargo (potentially problematic if you're in a ship without the required hardpoints on the way to a larger one, example being wanting to buy some turrets)

**Comment by tehhowch** [comment]
You can already buy directly to cargo - deselect all ships or select the checkbox in the lower left of the outfitter screen.
#2806  would not change any visuals, only extend the available actions.

**Comment by spazstatic** [comment]
Mind blown. I had completely missed that. By informing me, you just made the game that much better! Guess this is closed then. Thanks for all your help!

**Comment by Amazinite** [comment]
Duplicate of #2787

**Comment by Amazinite** [comment]
>Guess this is closed then.

Then close it. :)

**Comment by spazstatic** [comment]
I apparently misclicked cause I thought I hit close and comment. Whoopsie.
