### ISSUE TITLE
Fleet AI not landing on "secondary" planets...

### ISSUE THREAD

**Issue by PhoenixRiver** [endless-sky/endless-sky#285]
So... apologies for all the minor fixes I'm submitting, I really should sort out my git and try to fix some of these (though this one is probably beyond me for a while).
I am flying with my fleet of freighters who can't jump as far as me... they auto-land to refuel and then we go on whithout me needing to land... except now I'm in Hai space and I don't have authority to land on the homeworld - so neither does my fleet it seems and try as they might they just can't land... neither on Mirrorlake because the homeworld is the first choice? So they don't appear to filter places they can't land and so can't land without me landing on Mirrorlake (the moon and second choice) - even though I can press "L" and it auto lands me there (and not the homeworld).
It wouldn't be so much trouble for me but I fly a slow bruiser that protects my herd of lighter freighters (filled with cargo) and manouvering to land is a pain so them heading ahead, landing and then coming and joining me for the rest of the trip is handy! :)

**Comment by endless-sky** [comment]
This should be fixed in commit 2c5d35a.

**Comment by PhoenixRiver** [comment]
Thank you :)

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
