### ISSUE TITLE
Large Battery Module description has some inconsistency

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#2853]
The description for the large battery module states: "This battery pack stores enough power to allow a Heliarch ship to continue maneuvering even when its solar panels are only producing a fraction of their peak output." But Heliarch ships don't use solar panels. Was this meant to say 'Coalition' instead of 'Heliarch' or was it meant to say something about how it allows them to last longer in a firefight, especially against ion damage since Skylances deal ion damage?

**Comment by Bladewood** [comment]
It probably refers to Heliarch civilian ships. (That is, government-associated, but not combat-ready.)

**Comment by warp-core** [comment]
@Bladewood like in the same way the bombardment cannon description does? Although, that reference seems to be related to the early days of the Coalition when they were in direct conflict against the Quarg. That one also explicitly stated 'Heliarch Civilian'.

**Comment by Bladewood** [comment]
Maybe.

**Comment by endless-sky** [comment]
It's just a typo. Fixed in 3490406.
