### ISSUE TITLE
Drak agrro potential error

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2857]
So earlier today I read something about the "reminant" and after one of the final quests their was something that lowered your rep with the desk by 1000 points. Is this an error intentional or Iam  i misreading it.

**Comment by tehhowch** [comment]
It is not an error.

**Comment by Bladewood** [comment]
```
government " Drak "
	"player reputation" -1000
```
Note the spaces. This is distinct from `"Drak"`.

**Comment by KyroFirehammer** [comment]
Oh so its supposed to be a seprate government than the drak but still appear to have the drak tag

**Comment by KyroFirehammer** [comment]
In a side note I currently only have the "official updates" ,how would one go about opting in to the "beta branch" for lack of better terms

**Comment by gunqqer** [comment]
It is called the beta branch. On steam right click on endless sky in your library -> properties -> Betas -> select the pulldown and click 'beta -'

**Comment by Amazinite** [comment]
Please close this issue.

**Comment by KyroFirehammer** [comment]
Just waiting on the answer on the beta I'll clue it now

**Comment by jafdy** [comment]
There isn't a constantly updating steam version. If you want the latest commits you need to self compile.
