### ISSUE TITLE
Space Port Button Sometimes Unclickable

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#286]
This wasn't easily reproducible for me, but maybe 1-2% of the time the Space Port button will not actually be clickable, even though a given planet/station does in fact have a Space Port. When this occurs, taking off and then immediately landing again would make the button work. This is in the OS X version of the game, 0.8.8. Not a major issue, but something to be aware of.

**Comment by endless-sky** [comment]
I don't think I've seen that happen before.

Does it remain accessible through the keyboard shortcut ("P")?

**Comment by sanjayatio** [comment]
Might not be the exact same thing, but...
I experienced something like this after the upgrade from 0.8.5 to 0.8.7 (and 0.8.8).
Hanging during hyperspace, can't leave outfitter screen etc.
Finally realized the problem: the screen became stale.
The mitigation is quite simple - switch to windowed then back to full screen.
* dropped a comment about this in steam -- under that 0.8.8 news.
quite easy to reproduce by frequently switching tabs.

**Comment by endless-sky** [comment]
Any luck in finding ways to reproduce it, or in checking to see if it still happens in 0.8.9?

**Comment by sanjayatio** [comment]
I suppose you asked the original poster.
For me: haven't tried the 0.8.9 but never encountered any issue after compiling based on commit a30b396 (using O3 and -march=corei7).

**Comment by endless-sky** [comment]
I think the change of not pausing when the window is minimized might have fixed this. Reopen the issue if you've seen it happen on 0.8.9 or 0.8.10.
