### ISSUE TITLE
Deadline/Description conflict in Wanderer Invasive Species missions

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2860]
`description ``These <bunks> Wanderers need to get to <stopovers> with their <cargo> by <date> to contain an invasive plant species. Return the Wanderers to <origin> with the animals for a payment of <payment>.` 

Except, the deadline/date isn't for getting to the stopover, but for the entire mission.

Hey, look.  invasive species 2 also is inconsistent on if you're containing plants or animals.

**Comment by tehhowch** [comment]
Yep, this was something I missed when I updated the Wanderer jobs a few months back.

A better syntax would be `need to return from <stopovers> with ....`

**Comment by marphod** [comment]
I mean, the other option includes updating thecode to allow a deadline to be associated with a stopover or waypoint, not just the mission completion.

**Comment by tehhowch** [comment]
The PR that changes wording to be true will merge long before the PR that changes the code to make the incorrect wording correct :)

**Comment by Amazinite** [comment]
`These <bunks> Wanderers need to get to <stopovers> with their <cargo> to contain an invasive plant species. Return the Wanderers to <origin> with the animals by <date> for a payment of <payment>.`?

**Comment by Amazinite** [comment]
#2863
