### ISSUE TITLE
FIrst Contact: Remnant log entry should be in the on decline

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2866]
The information in the log is learned after you take the blood test, but should the player run then they wouldn't have learned the information which is written in the faction log on the Remnant. To avoid this, the log should be moved from the `on offer` to the `on decline`.

**Comment by Hadron1776** [comment]
> but should the player run then they wouldn't have learned the information which is written in the faction log on the Remnant.

Seeing as "the player runs" triggers `accept`, I don't think this would solve the problem. I thought `on offer` blocks were triggered immediately when the mission is offered, anyway?

**Comment by Amazinite** [comment]
>Seeing as "the player runs" triggers accept, I don't think this would solve the problem. I thought on offer blocks were triggered immediately when the mission is offered, anyway?

Running triggers `accept`. Accepting the blood test and learning the history of the Remnant triggers `decline`. As such, the log should be in the `on decline` and not the `on offer`, as placing it in the `on offer` will create the log whether you actually learn the history of the Remnant or not.

**Comment by Hadron1776** [comment]
Oh, ok. I think I misread your OP then :)

**Comment by tehhowch** [comment]
There should probably be an `on accept` log for a hostile Remnant faction if the `on offer` log becomes the `on decline` log.
