### ISSUE TITLE
In the new update (9.7) occaisionally astroids turn up as ships that you cant click on

### ISSUE THREAD

**Issue by JarlErak1** [endless-sky/endless-sky#2868]

**Comment by MessyMix** [comment]
I cannot confirm. Can you show us screenshots, a save file, and steps to reproduce the issue? Also, are you running any mods? I haven't experienced this behavior as of 0.9.7.

**Comment by gunqqer** [comment]
Typical Amazinite, always breaking the game with his plugins

**Comment by Amazinite** [comment]
It's not even breaking the game, it's just adding minables that look like old ships. Worked on adding the concept to the main game in #1996 but Wrzl didn't have enough time to create damaged looking outfits and I eventually lost interest in the idea.

**Comment by gunqqer** [comment]
So yeah- Close this issue please
