### ISSUE TITLE
Feature request: hotkey for active missions, change pilot hotkey

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#287]
Currently to access active mission info, one either opens up the pilot info via "i" or the map via "m" and then clicks on the missions button. Escape Velocity had a button that would specifically open up the list of active missions, this was by default mapped to "i," with the pilot info being (logically) mapped to "p." I think this is a more sensible behavior. It would also just be great to be able to jump directly into the mission information rather than having to click around to find it.

**Comment by endless-sky** [comment]
I'm a bit hesitant to add even more different hotkeys that the player must memorize, and it seems like you will want to call up the map (to plan hyperspace routes) more often than you call up the missions, so I don't want to have the map default to the missions page.

Note that the "i" key is the shortcut for the "missions" button, to distinguish it from "m" for map, so you can press "mi" to view your missions.
