### ISSUE TITLE
Bug: ability to sell disabled ships

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2870]
I've 3 disabled ships in orbit of a planet with a shipyard.  The order of ships in my inventory is
- a bunch of ships i'm keeping
- active ship in current system (that i want to sell
- the three disabled ships in current system
- another active ship in current system (that i want to sell

In the shipyard dialog, if I select the first ship i want to sell and then shift-click on the last one, when I try to sell, all five ships are listed in the sell dialog (and the sale price includes all 5 ships) rather than only the undisabled ships

**Comment by tehhowch** [comment]
And if you try to sell them?

**Comment by marphod** [comment]
They get sold.

**Comment by tehhowch** [comment]
Ah, you did not mention that the disabled ships are not shown in the panel (because they are not shown due to being disabled).

Looks like a range(a, b) sell instead of a for-each-selected sell issue.

**Comment by endless-sky** [comment]
Fixed by merging #2871.
