### ISSUE TITLE
Enhancement request: Select planet to land on using star map

### ISSUE THREAD

**Issue by lifeyouristhis** [endless-sky/endless-sky#2877]
As in title. Make the planet selected on star map [M] be selected for landing.

**Comment by tehhowch** [comment]
Already done.

Select the planet in the orbit scene, and you will autopilot to that planet when you enter the system.

If you mean something else, be more specific.

**Comment by lifeyouristhis** [comment]
Then only partially done. 
That should also work **while being in** that system. Toggling through using "L"  key works badly with frameskip on.
Consider this when there will be nothing more important.

**Comment by endless-sky** [comment]
Added in 6370ada.
