### ISSUE TITLE
Clicking to Land Causes the Game to Crash

### ISSUE THREAD

**Issue by LeningradmorelikeLeninisrad** [endless-sky/endless-sky#2888]
Fairly self-explanatory. At first I thought it was because I was trying to land while jumping, but a bit later I noticed that without realizing it I've developed the habit of using my mouse to land instead of pressing L, and it's the clicking to land that each crash shared.

**Comment by Bladewood** [comment]
Seems to work fine for me. Can you tell us more about your setup, e.g. operating system and hardware specs and game version?

**Comment by MCOfficer** [comment]
Janaszar (not on github) couldnt reproduce it either.

**Comment by Rob59er** [comment]
Never had it happen

**Comment by KiLEdEnNis** [comment]
same here, tried wormholes even
any plugins etc?

**Comment by LeningradmorelikeLeninisrad** [comment]
I've just fixed it, the problem was that I had a ship in my fleet which was from a slightly buggy plugin. Parking it did the trick. (Just to be clear, it didn't take me seven hours to figure this out, I just haven't been home since I posted this)

**Comment by gunqqer** [comment]
If the problem is fixed and only due to an outdated/buggy plugin please close this issue

**Comment by endless-sky** [comment]
It'd still be useful to know what the buggy ship and plugin was, if you can post your saved game, because even if a plugin is buggy ideally it shouldn't crash the game outright.
