### ISSUE TITLE
Some way to convey a player's fleet attraction to them

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2889]
Either by showing the player's fleet cargo and DPS in their info panel or just straight up showing their attraction, there should be something in game to convey to the player that their fleet is attracting pirate raids, and some sort of information on what exactly pirate raids are and how they appear.

**Comment by gunqqer** [comment]
It could just be me being stupid but that title doesn't really convay what you said in the body.

**Comment by tehhowch** [comment]
Rather than hard numbers for the chance to spawn a raid fleet, we probably
want text categories based on the value... "Unlikely .... Possible...
Likely.... Very likely... Near-certain"

**Comment by Hadron1776** [comment]
> Rather than hard numbers for the chance to spawn a raid fleet, we probably
want text categories based on the value... "Unlikely .... Possible...
Likely.... Very likely... Near-certain"

Just a nitpick: "Unlikely" coming before "possible"?

**Comment by Bladewood** [comment]
How about this, then:
> Nigh Impossible -> Unlikely -> Likely -> Very Likely -> Near Certain

**Comment by gunqqer** [comment]
Nigh Impossible -> Very Unlikely -> Unlikely -> Possible -> Likely -> Very Likely -> Near Certain

-> You're screwed, go home, don't try it.

**Comment by tehhowch** [comment]
>Just a nitpick: "Unlikely" coming before "possible"?
We can just drop possible :)

**Comment by endless-sky** [comment]
Your fleet's attractiveness to pirates is already indicated via a user interface when pirate ships shoot things at you if they find you attractive.

If I did add a fleet rating, it'd be more interesting if it was along the liens of a combat rating, something like:
* not worth the risk
* slim pickings
* juicy target
* easy prey
* pirate bonanza

**Comment by gunqqer** [comment]
as always MZ comes up with much better stuff than we do.

**Comment by Amazinite** [comment]
>Your fleet's attractiveness to pirates is already indicated via a user interface when pirate ships shoot things at you if they find you attractive.

The only reason I ask for something like this is because there are a couple of people on Steam (who I told this to) asking for some sort of reasoning given to the player as to why they are attracting so many pirates and something telling them how they could fix it. i.e. making the idea of pirate raid attraction visible in text instead of just in the fact that you spawn pirate raids.

**Comment by marphod** [comment]
Juicy target before easy prey?  I'd assume the other order, but it is ambiguous.

I wonder: could the level of attraction could be clued by the hails from the pirates? I don't know how easy it is to make their hails customizable based on player stats.

**Comment by jafdy** [comment]
Could there also be phrases for very unattractive war fleets, something like; "They would be mad to try"

**Comment by KyroFirehammer** [comment]
Final tier "pray to RNGesus "

**Comment by Bladewood** [comment]
@KyroFirehammer not happening (not in the official game, at least), because Endless Sky has very high standards in terms of content quality, and "RNGesus"... doesn't quite live up to that standard.

**Comment by ghoulavenger** [comment]
Hehe, I get the feeling my risk would be Pirate Bonanza. Running 100 armed deep rivers guarded by 52 well armed hurricanes and I see massive pirate fleets while in human space, never lose anything though.

**Comment by Amazinite** [comment]
>Hehe, I get the feeling my risk would be Pirate Bonanza. Running 100 armed deep rivers guarded by 52 well armed hurricanes

Well you'd only be "pirate bonanza" if you didn't have the Hurricanes lowering your fleet attraction.

**Comment by tehhowch** [comment]
With #3087 merged, this is now visible in the Player Info menu:
![image](https://user-images.githubusercontent.com/20871346/31346568-246f72f2-acdf-11e7-93da-3b5838138cf6.png)

And you will be informed if those ships attacking your fleet are specifically interested in you:
![image](https://user-images.githubusercontent.com/20871346/31346619-4db19852-acdf-11e7-9611-452b46edd08d.png)

**Comment by Amazinite** [comment]
I don't believe that "Pirate" should be capitalized, but given that I assume that it is pulling the government name for that (`<government> raiding party`) and we *would* want say a "Korath raiding party" to be capitalized, I guess it's fine.
