### ISSUE TITLE
Feature Request: Blueprints

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#289]
Blueprints would be a really cool way to introduce experimental ships, and since the game is constantly growing and changing, it wouldn't really matter if they were used later in the game. I personally have over 7 different saves, 2 I've beaten storyline in , 4 that glitched due to me failing a mission, and 1 that I just started (gonna try to do the entire storyline in a souped up Headhunter)

An example of how this works: You could be killing pirates, and you get a pop up (like the events that happen such as the alpha wars thing) saying that the pirate ship had a blueprint on board, or you could be carrying cargo, and a pop up saying you found the blueprint stashed away in one of the shipping containers, you could find them exploring, etc. It just would be a really neat way to introduce new ships/ maybe even new weapons or outfits

**Comment by airtroop392** [comment]
What would the blueprints do, exactly? You hand them in at dock and you get access to a certain type of ship/weapon/some sort of item? Or is this something along the lines of, you get a blueprint, now DIY?

**Comment by thenerdfreak** [comment]
Well, one take on it is you would have already had to have finished the (SPOILER DON'T LOOK AHEAD IF YOU DON'T WANT SPOILED) Free World's story line up until you meet the engineer in the Rim that makes stuff, you could hand them to him and he would "test them" and produce them, like the plasma turret and the dreadnaught, as well as the flame thrower.

Another take is you could "DIY" using materials bought/looted from the merchants (we need a REAL use for these anyways)

**Comment by thenerdfreak** [comment]
And with this, I also request storage facilities. I currently (on my save i just wreck everything with) have 3-4 ships dedicated to holding jumpdrives, it would be nice to have a spacestation or something you could build/unlock that would hold your resources, extra outfits, etc.

**Comment by airtroop392** [comment]
OK, well that makes sense. As to your second post, yeah, there really needs to be some sort of storage medium in the game, perhaps another tab in dock which would allow you to store your equipment anywhere, and get it back anytime, any place... sort of like the Cloud, except for materiel. I suppose that yes, stuff could just be dropped off at planets, but then comes the question; how do we remember that we put stuff on a certain planet?

**Comment by gchapyzh** [comment]
Then go to Rust, or another experimental lab, and have the ship made.

**Comment by thenerdfreak** [comment]
That's why I was thinking space station. You could pick the planet you wanted it to be at, so You'd remember it (I.E all of my docked ships are at Sol, because it's decently central and easy to remember)

or you could go with the whole "cloud" thing, since FTL travel is already a thing in this time period anyways

**Comment by gchapyzh** [comment]
![battery_blueprint_s](https://cloud.githubusercontent.com/assets/8764280/11450240/59e2a67c-954c-11e5-926c-5cf1f31f4db3.png)
![engine_blueprint_s](https://cloud.githubusercontent.com/assets/8764280/11450243/59e34398-954c-11e5-839a-42163474999f.png)
![powersource_blueprint_s](https://cloud.githubusercontent.com/assets/8764280/11450242/59e323ae-954c-11e5-85f5-4474a95dd00c.png)
![ship_blueprint_s](https://cloud.githubusercontent.com/assets/8764280/11450239/59e20ea6-954c-11e5-8b2f-359e0894b884.png)
![weapon_blueprint_s](https://cloud.githubusercontent.com/assets/8764280/11450241/59e31a12-954c-11e5-88f9-3e43be53e963.png)

:smile: 

This is 960*720 PX
I got a 2828*2121 PX on my comp if you need it

**Comment by thenerdfreak** [comment]
yeah kinda like that, and a silhouette of the weapon/ ship with the blueprints you already have collected coloured in
for example, if the gunship required 4 blueprints and you had 1, 1/4 of the gunship would be coloured in

**Comment by gchapyzh** [comment]
@thenerdfreak You want me to create a set of blueprints for a weapon with the numbers and colors?

**Comment by thenerdfreak** [comment]
http://i1133.photobucket.com/albums/m581/thenerdfreak1/gunboat_zpsizrfdptr.png  
If you want to , you can probably give a better example than that ^

**Comment by gchapyzh** [comment]
@thenerdfreak shure, I can make a full set for a gunboat.

**Comment by gchapyzh** [comment]
![blueprintsgb](https://cloud.githubusercontent.com/assets/8764280/11450433/84c1508e-9554-11e5-8f9e-04eddf0eba16.png)
![blueprintssp](https://cloud.githubusercontent.com/assets/8764280/11450434/84c31270-9554-11e5-98d4-f236d8e64d90.png)

Sorry, these are the big ones. Red is for medium rarity, green is for common.

**Comment by thenerdfreak** [comment]
Yes ^ exactly what I had in mind The ADV versions would have slightly better base stats and maybe a little bit more cargo/outfits space

**Comment by airtroop392** [comment]
In order for the "swizzling" to work (colors on ships change according to faction), ship images have to be mostly the same color with a few highlights (most ships are gray with orange-reddish highlights), so I'm not entirely sure what you mean. Are you suggesting that there be just one color scheme? I guess that would work fine, if that is what you mean.

**Comment by thenerdfreak** [comment]
no, not swizzling colours, the colours on the Blueprint
like how those are red for medium ( the aura) it could be purple for like legendary or unique

**Comment by airtroop392** [comment]
Oh, ok.
