### ISSUE TITLE
Usage of SDL_Image

### ISSUE THREAD

**Issue by kingmooselord** [endless-sky/endless-sky#2893]
So I've been trying to compile ES with purely VS2017/MSVC and have mostly gotten it working. I was mainly curious on the usage of libpng/libjpeg directly over the SDL_Image wrapper considering it is an SDL2 project.

Would porting to using SDL_Image (even if just for #ifdef _WIN32/_MSC_VER) be acceptable?

Granted, ImageBuffer class is fairly simple as-is and perhaps SDL_Image would be unnecessary overkill just for simpler compiling on MSVC.

Just figured I'd ask in any case. 

https://www.libsdl.org/projects/SDL_image/

**Comment by endless-sky** [comment]
SDL_image pulls in a *ton* of dependencies to other image libraries (TIFF, WEBP, etc.). Also, it loads things into SDL surfaces, which is not particularly useful here.

**Comment by kingmooselord** [comment]
Fair enough. Just figured I'd ask. It's one of those "easier to build, but more dependencies and another layer of indirection in the code". 

Should be easy enough to get a working VS2017 solution without it.

**Comment by tehhowch** [comment]
I have a build that uses the Clang/C2 compiler that I revisit occasionally.
Still working on getting it to link, but I have everything compiling.
Didn't run into any issues compiling when using the prebuilt dev64
resources.

**Comment by kingmooselord** [comment]
Got everything to compile and run ;)
