### ISSUE TITLE
Acgeron scanning

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2894]
Should we be able to scan the acgeron outfits because it doesn't really work in the mission for the void sprites

**Comment by KyroFirehammer** [comment]
I'M SORRY my auto correct auto corrected "acheron" in the title and I can't edit it :(

**Comment by gunqqer** [comment]
You can edit posts and post titles, also you can edit... posts instead of replying. Please do that nexttime, fix it now, and delete the reply

**Comment by Bladewood** [comment]
There is nothing in the game called an "acgeron".
If you're talking about the Archons, then it should be working fine. You're not supposed to be able to scan them. (It returns the same message as the Void Sprites.)

**Comment by Amazinite** [comment]
Please close this issue.

**Comment by TheUnfetteredOne** [comment]
Edit your posts.

**Comment by Pointedstick** [comment]
Even better, use a real computer instead of a toy intended for media consumption.

**Comment by KyroFirehammer** [comment]
Hey don't be rude my pc doesnt have good internet it takes forever to do anything so I use my phone for github
