### ISSUE TITLE
I think I found an issue with message lag

### ISSUE THREAD

**Issue by Hadron1776** [endless-sky/endless-sky#2895]
I died in a game, so I started a new game. I buy a ship and depart from the planet; and the messages from the _previous save_ are now stuck on the main panel until I restart the game:
![stuck messages](https://user-images.githubusercontent.com/24595528/29000119-49d5c688-7a1f-11e7-9946-5cbcd25e6995.jpg)

This doesn't seem to happen when reloading a saved game, only when starting a new game immediately after getting blown up.

I'm on Windows 10.

**Comment by Hadron1776** [comment]
Closed because I can't seem to duplicate this. Whatever.

**Comment by endless-sky** [comment]
It looks like that can happen if you create a new player directly from the main menu instead of from the Load / Save... panel, because I forgot to reset the messages in that case. Commit c6c2ce9 fixes that.
