### ISSUE TITLE
Make it possible to dump non mission-related cargo when boarding a ship

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#29]
As always, this is only a suggestion and I leave it up to you to see if/how you want to implement this.
I've often found myself boarding pirate ships with a full hold, and therefore not being able to salvage anything from the boarded ship (provided I don't want to capture it). It would be nice to be able to dump some "lesser" cargo into space to make place for valuable outfits.

**Comment by Oeleo** [comment]
Yes I thought the same thing, when you have a beautiful reactor that you can't loot because you have 130 kg of clothes...grrr.

**Comment by endless-sky** [comment]
This is (finally) possible: 519c5cd. When you are viewing ship info in the info panel, and you are not landed, it now has a "Dump Cargo" button.You can select a particular commodity to dump, or click the button with no commodities selected to dump all regular commodities in the ship. It does not allow you to dump mission cargo or plundered outfits, although maybe I should add support for the latter.

Pressing the "INFO" key while in the boarding panel will bring up the ship info page for your flagship, allowing you to dump cargo if you want.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
