### ISSUE TITLE
Feature request: Visual indication of when system/planet/moon/station has been visited by player

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#290]
Currently, the only way to be sure that a player has never visited a system is to never buy the "local map" item, as the new systems added by the local map visually look the same as systems that have actually been visited by the player. I suggest a visual distinction between these two cases on the map, perhaps by using a different shape or symbol size to indicate when a system is known but has never been visited by the player (i.e. it was revealed by a local map or a mission rather than visitation).

Additionally, there is no information about whether a player has ever landed on a particular planet/moon/station in a given system, in principle this information could be added to the "ports" inset in the lower right. With hundreds of systems in the game, it can be impossible to tell if the player has ever landed in a particular place.

**Comment by airtroop392** [comment]
Why not just add a new tab altogether which would contain this information, and sort visited sectors/unvisited sectors by color, and then in the sector overview section (the cutaway of the sector which appears upon clicking it), the same concept would be applied to show which planets/stations you have visited within the sector?

**Comment by guillochon** [comment]
Yes this would be a nice solution, and would be in line with the other means of displaying information on the map screen.

**Comment by thenerdfreak** [comment]
It wouldn't be too far to go, as the player's save file keeps up with all the systems visited already (or at least the ones you have trade/relationship knowledge of i.e through maps)

**Comment by guillochon** [comment]
I have a pull request that implements a visual indication of when all planets in a system have been visited: https://github.com/endless-sky/endless-sky/pull/345

**Comment by endless-sky** [comment]
This is implemented in commit 4f0b23a.

**Comment by endless-sky** [comment]
Included in release 0.8.10.
