### ISSUE TITLE
<payment> tag always chooses a negative payment, if one is present

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2900]
I'm trying to modify the Syndicate Target Practice missions to include a fine if you blow up the ship, to resolve issue https://github.com/endless-sky/endless-sky/issues/2890:

```
	on fail
		dialog "You have destroyed the robotic target ship instead of disabling it. An angry Syndicate official hails you, chews you out, and imposes a fine of 250,000 credits."
		payment -250000
		"reputation: Syndicate" --
	on complete
		payment 150000
		dialog "You transmit the scan results to a team of eager engineers and collect your payment of <payment>."
```

However, in-game, the penalty "payment" is always chosen for the <payment> tag in the description:

![wrong payment](https://user-images.githubusercontent.com/1097249/29006321-b931e8be-7aaa-11e7-9075-a0b44e712aac.png)

This still happens if I re-order the blocks so that the one with the penalty payment is last, or if I change the penalty payment so that its absolute value is less than the real payment.

**Comment by lifeyouristhis** [comment]
Missions can have only one "Payment" option I think so game takes first occurrence and ignores latter.

**Comment by Pointedstick** [comment]
Actually, it shows the negative payment in the description even if the positive payment is first, and the negative payment also works fine in-game: If you fail, the penalty is imposed as expected. It's just the description that doesn't choose the right one to display.

I don't know if I'm taking advantage of a bug or a hidden feature, but the negative payment/penalty feels right, and IMHO should be supported *somehow*.

**Comment by lifeyouristhis** [comment]
Also aborting a mission counts as a failing.

**Comment by endless-sky** [comment]
As of commits a1f626b and 305e757:
* In general, `<payment>` stands for the `on complete` payment of a mission.
* Inside a mission action (i.e. `on <type>`) that defines a payment, `<payment>` refers to that amount.

That means that you could have a failure dialog that says, `"The Syndicate fines you <payment>"`, and a completion dialog that says, `"The Syndicate pays you <payment>"`, and both will work correctly.

**Comment by Pointedstick** [comment]
Fantastic, thank you so much!
