### ISSUE TITLE
suggestion: starfield shouldn't zoom out

### ISSUE THREAD

**Issue by PLUUZ** [endless-sky/endless-sky#2903]
Great game! One thing that might improve gameplay-- when you zoom out, the starfield should not zoom out.  Why?

At max zoom:
-Stars become like a sort of static noise
-Makes it harder for people to notice sprites due to distracting noise
-Due to antialiasing/dithering/whatever, the stars do a distracting twinkling thing on both displays I tried (laptop and big external)
-Starfield at max zoom has more stars than we expect for this kind of game, like we're looking through Hubble telescope deep field, which sort of throws you for a second.

I don't want some parallax thing with like 5 layers that move infinitesimally. I suggest the starfield to behave just as it does now, so you can judge your speed by it, but to not get zoomed out with the rest of the game.

**Comment by lifeyouristhis** [comment]
They aren't exactly behaving like a stars. They are all identical, move as you move and resemble twinkling space dust. Nonetheless I'd speak against changing them, because game looks pretty static and they do a good job creating an illusion of motion.

However I'd want to ask for linking their number to frame rate, because their extreme speed motion effect (mainly hyperdrive) causes frame drops.

**Comment by solardawning** [comment]
Yes, the reason why the current zoom behavior looks so weird is because the stars actually shouldn't zoom out like that- they're extremely distant objects, so perspective would dictate that zooming out by any reasonable factor will not cause them to appear differently.

**Comment by endless-sky** [comment]
It depends on whether the zoom is an optical zoom (increasing / decreasing the magnification of the camera) or a physical zoom (moving the camera closer to the ship).

In any case, the real point of the stars is to allow you to judge your rate of motion, and for that they need to be moving at the same speed as your ship.
