### ISSUE TITLE
Is this intended? Balance discussion on Remnant ships (Mass & Drag)

### ISSUE THREAD

**Issue by solardawning** [endless-sky/endless-sky#2907]
Hallo,

The mass and drag of the Remnant ships seems off-kilter compared to similar ships, and don't fit so clearly into a progression curve after the player already has access to Hai ships.

In particular:
The Albatross appears to be a lighter ship than the Shield Beetle, with an elegant design, less cargo space, and fewer crew bunks. 
It also has ~150 less outfit space, less weapon tonnage, and slightly less engine space.
The regenerative hull is very interesting, comparable to a built-in Large Systems Core (more efficient on energy use, but without the battery storage.)

It's base mass, however, is 40 higher than a Shield Beetle (690 vs 650), and it's drag is significantly higher at 10.6 (vs 8.8).

As a result, the Albatross is slightly more durable, but has less usable tonnage and is significantly slower, making it less useful as a general warship.

The Starling also has slightly more drag (at 4.2) than one would expect for a small scoutship- compare to the Lightning Bug's 3.8. Or compare to human medium and light warships, like the Aerie (4.1), Navy Gunboat (3.1), Headhunter (2.6), Quicksilver (2.7), Raven (3.7), etc...
One would also expect it to have more fuel than the Albatross, to fit it's role as a cloaking scoutship.

Suggestions:
Albatross - Either cement the Albatross as a warship upgrade over the Shield Beetle by reducing drag below 10 and increasing the outfit space by around 100, or (and I think more interesting), reduce base mass and drag to below that of the Shield Beetle, so that it is a comparable hull that is lighter armed but faster.

Starling - Increase Fuel from 600 to 900, reduce drag to 3.8

**Comment by Amazinite** [comment]
On the topic of the Starling, I think the increased fuel makes sense, but I wouldn't touch the drag. A scout ship doesn't need to be fast if it can be invisible, which the Starling can do.

No opinion on the Albatross. I don't really think it needs to be a direct Shield Beetle upgrade.

**Comment by solardawning** [comment]
Right, I agree that the Albatross doesn't need to be a direct shield beetle upgrade- but I'd at least expect it to be different (given that the player must have visited the Hai before they can access the Albatross)- right now it's all of: slower, heavier, and less tonnage.
It'd be more interesting if it could remain less tonnage, but be faster than a Shield Beetle.

**Comment by Bladewood** [comment]
Just a note: the Starling has faster cloaking, and its cloak is more fuel efficient, but it drains more energy.

**Comment by kingmooselord** [comment]
The Albatross did feel a lot slower to pilot than it's sleek design had portrayed. On the other hand isn't it mostly a "sniper" platform for defense? Then it wouldn't need to be as fast under that role.

I'm all for buffing the one of the most stylish looking ships though ;)

**Comment by Lineth** [comment]
I am of the opinion that the Albatross needs a little love. I like the idea of it being a sort of brawler/artillery ship build to defend systems. But just giving more outfit&weapon space (not too much, mind) would work.

**Comment by KiLEdEnNis** [comment]
from what I get you compare the Albatross, a South-East humanish species' ship, to thje Shield Beetle, a North-East squirrel folk, and both have about nothing in common (apart from Key( )stones)
you can't really compare the mass, drag, outfit space etc. of 2 ships of 2 species that'aren't even related; different species work differently

I do get the idea of buffing the Albatross to make it a bit more of a warship, but you get FREE shield/hull repair, and not just a little bit (312/90) which already justifies like 100 "missing" outfit space:
312 shield 90 hull regen, that drains 348 energy max (REALLY efficient) and takes no heat
I kinda think the Albatross is underrated

**Comment by solardawning** [comment]
There is a very simple reason to compare it to the Shield Beetle.

By the time a player can access the Albatross, they already have access to the Shield Beetle.
The Shield Beetle can fill every role in the player's fleet better than the Albatross. (It is significantly faster, has almost identical required crew but more bunks, has more cargo space, and has much more outfit space- more than enough to make up for the Albatrosses' built-in regen.)

Thus the Albatross is not useful as a player ship, unless you value aesthetics more than function.

**Comment by KiLEdEnNis** [comment]
that ya can access one alien species at the time of another is a dumb reason to straight compare the ships though; why would ya base aliens' tech based on when they get encountered

**Comment by solardawning** [comment]
I can't tell if you're trolling or not.
That's a basic tenet of game design. It's called a progression curve. This game, too, has one.

**Comment by Amazinite** [comment]
There is a progression curve, but once you progress to the next step, not everything needs to be better than the stuff you saw before. The Starling and some Remnant weapons are upgrades from what you could get in Hai or human space, but the Hai and even the rest of humanity have better generators or engines. As such, I don't really find it odd that the Albatross isn't exactly an upgrade over the Shield Beetle. 

Also, the extra shield regen and hull repair on the Albatross is worth like 91 tons (using the size of a Large System Core) to 116 tons (using the shield or hull/mass of Dark Storm Shielding and Large Repair Modules).

**Comment by gunqqer** [comment]
Every race should have it's own sort of speciality. Like how the Wanderes combine two things (engines also cool, reactors also have storage) and the korath have very head inefficient stuff but very strong, etc. The remnant seems like it's shtich is stuff that is built into ships (cloaking, regen). There always should be an argument to why you should use one race's outfits and ships against another of the same tier.

**Comment by KyroFirehammer** [comment]
Remnant should be better because it's harder to get to them. The hai you can get to in a bouncer where ad the remnant require a dreadnought or better to even think about getting to them an albatross should be comparable to a raider or an insanely tricked hai shield beetle

**Comment by tehhowch** [comment]
It does not require a Dreadnought to reach the Remnant.
Use your Bounder, get a Quantum Keystone, go to Terminus, land on the Ember Threshold. Yes, you have to dodge pirates to do this... but... you're in a Bounder: avoiding pirates is **easy**. Once through, you have only rare Korath Raider spawns to worry about, and again: Bounder. 
Voila, you have reached Remnant space without a warship.

**Comment by solardawning** [comment]
Yes. You can't buy an Albatross though until you have enough Jump Drive-equipped warships to take out two Korath Raiders. ;)
I find it easiest to do with a pair of Shield Beetles, since you can easily capture them with with either a mule or Blackbird with extra bunks at Cloudfire.
And that is the trouble with the Albatross.

**Comment by KyroFirehammer** [comment]
Just read and BAM death by raider instantly and that's after dogeing 4 marauder fllets and dying 6 times. Theoretically you could do it but you'd have to get a 100% perfect dice roll like at least 6 times (and I was using the best alien outfits possible) (small systems core atomic engines a generator [furnace class] and heavy laser turret [couldn't fit any better])

**Comment by Hadron1776** [comment]
> Yes. You can't buy an Albatross though until you have enough Jump Drive-equipped warships to take out two Korath Raiders. ;)

Three Korath Raiders and a Worldship, IIRC

**Comment by solardawning** [comment]
The individual raiders and the worldship aren't as challenging as the mission where you need to go to a jump-only section of space, and fight two raiders simultaneously, so that is the one that is the hard gate on fleet strength (and jump capability).

**Comment by endless-sky** [comment]
It does sound reasonable to buff the speed of the Remnant ships. Done in f6325b1.

**Comment by TheD-nigh** [comment]
Dear solardawning, 
Have you been playing the beta? As I can see in the game, you don't need a jump drive to reach the 2 Korath ships. There's a wormhole from Convector to Coluber. I mean the whole Remmant space is a maze with one wormhole next to another but it's all connected. You should check it out

**Comment by Amazinite** [comment]
@TheD-nigh That wormhole was added after Solar made that comment.
