### ISSUE TITLE
More Trinket Outfits

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2908]
By trinket outfits, I mean stuff like the Quantum Keystone. Right now it's really an oddity. It's the only outfit in the game that seems to serve no purpose once you first find it, but unlocks access to secret things such as new jobs and most importantly easy access into the Ember Waste. Since it sticks out like a sore thumb, maybe it would be worth adding other trinket outfits that you could install, mainly in human space so that the player doesn't find the Quantum Keystone to be an oddity. These trinkets would of course have a purpose... mostly. They could unlock jobs similar to the Quantum Keystone in Hai space or even spaceport missions on more superstitious worlds. 

Maybe one or two could be worthless just for the heck of it, but the addition of such trinkets would 1) make the Quantum Keystone less odd once it is found and 2) make it more interesting to those who actually figure out that the trinkets that they have been installing in human space allow them to do new things, and thus they would be interested in finding the purpose of the Quantum Keystone. And I think most importantly, 3) it would allow us to build lore around new topics that would previously be kind of difficult to explore without being very clunky at the start (e.g. maybe the player has a religous trinket on their ship and is approached by a group of preachers who wish to be transported in a "holy ship." I don't exactly see how they would find your ship holy otherwise 😄).

Some trinkets could have very explicit uses (e.g. someone literally points it out after you land, hinting to the player that such trinkets may trigger missions) and others implicit ones (strange jobs that you weren't getting before the trinket was installed but that don't neccessarily say that the trinket is the cause of them). Overall, I think it would make for a much more interesting universe.

**Comment by solardawning** [comment]
Absolutely. This is simple enough content that it just needs someone to do the legwork making those missions. =)

**Comment by Amazinite** [comment]
Yeah, I've placed it on my (long) to-do list of things to PR. Just wanting to get feedback on the general idea.

**Comment by tehhowch** [comment]
This is a more general version of #2661 and is something that should be worked towards :+1:

**Comment by jlnxr** [comment]
Idea for trinket: a set of scientific scanners that serve no obvious in game purpose, but would allow you to be offered specific scouting/research missions. But exactly a religious article trinket, but a way to have an odd no obvious purpose outfit be valuable with cool missions. 

Ex. "While walking through the spaceport you're stopped by a man you've never seen before. 'I noticed your ship has a set of <whatever> scanners. I was hoping to find someone with that equipment to head to <destination> and take some <whatever> readings. I'd be able to pay you <payment>'"

**Comment by tehhowch** [comment]
@jlnxr All the mechanics for this (trinket outfits) exists - all that needs doing is content creation. Feel free to write up your mission and PR it - we will happily support its merging (with feedback, of course)

Resources to help with creating the outfit, and writing the missions exist on the [wiki](https://github.com/endless-sky/endless-sky/wiki), and if you're a better writer than artist, there are some very skilled folks available in the [Endless Sky Discord channel](https://discord.gg/fjxqYmp) 'content-creating'

**Comment by KyroFirehammer** [comment]
It's got my vote

**Comment by endless-sky** [comment]
Another idea: outfits like "Fancy Bathroom" and "Mini-Bar" that make your ship attractive to high-paying passengers. (The Star Queen could come with them by default.)

**Comment by Amazinite** [comment]
So, who wants to model a fancy bathroom? :)

**Comment by Amazinite** [comment]
Here's a collection of my ideas for random trinkets so far:
* Regional religious trinkets
  * Attracts religious figures in the form of jobs and spaceport missions
* Fancy Bathroom and Mini-Bar (default on Star Queen)
  * Attracts fancy passengers in the form of jobs and spaceport missions
* Regional good luck charms
  * Some might do absolutely nothing while others might actually make you lucky in some way (increased chance of getting offered certain high-paying jobs?)
  * One regional charm might be a meteorite: "While meteorites can be easily obtained today by causing a small asteroid to hurtle into the nearest atmosphere, they are still considered a good luck charm by many in the Dirt Belt."
  * Another might simply be an Earth rock or Moon rock; just something from humanity's home system.
* Scrap metal (sold on very few planets and completely useless; it's just scrap metal)
  * "This scrap metal is said to have come from the ship of the great <insert hero's name here>, who was killed during the Second Alpha War. <name>'s deeds were so great that the entire galaxy was said to be in mourning over his death, and possession of anything that was once connected to him is considered good luck."
    * Who wants to make it one of Hanover's aliases? I think that would be a hilarious mind-blow for anyone who connects the dots after doing that part of the Wanderer storyline.
* Exotic Statue
  *  A beautiful statue placed on the front of your ship. Triggers spaceport missions (for better or for worse 😄).
* Exotic Stone
  * A stone found on a specific Dirt Belt planet that bares a striking resemblance to the Quantum Stone. Could have a connection, or it could be complete coincidence. Triggers spaceport missions.

And that's just stuff for human space. It would be interesting to give each alien race their own trinkets as well, especially the Hai and the species of the Coalition right now.

**Comment by gunqqer** [comment]
Oh dang, Amazinite, you put a lot of effort into that. I like those idea.

**Comment by solardawning** [comment]
I'd sum up 'Fancy Bathroom and Mini-Bar' as "Luxury Accommodations".

**Comment by KyroFirehammer** [comment]
Id add a language translator that allowed you to take Effretti missions 

AND A HULA DANCER DANG IT :P

**Comment by jafdy** [comment]
Insted of badges you could just use a mission as a condition, you can't loose that.

**Comment by Startome** [comment]
You could give these trinkets 0 weight,  and a unique positive value,  so they can't be sold.  That way the player can see what they have,  like licenses,  but the list is out of the way

**Comment by Pointedstick** [comment]
Here's the Boba Fett version: [the Brig](https://github.com/endless-sky/endless-sky/pull/3347).

Working on "Luxury Accommodations" now. :slightly_smiling_face:

**Comment by tehhowch** [comment]
I think @comnom or someone else on discord had been doing the golden bathroom... Can't recall.

**Comment by Pointedstick** [comment]
It's not _actually_ going to be a golden bathroom; just something that looks nicer and more private than bunk beds. :slightly_smiling_face:

**Comment by KiLEdEnNis** [comment]
sleeping in a golden tub sounds nicer than a bunk bed to me though

**Comment by Zitchas** [comment]
Trinket outfits would be good. Interesting Issue. I'd love to have a whole pile of different 1 and 2 sized outfits.

**Comment by yafflehk** [comment]
I'm using a room design tool called Sweethome 3d, just because I'd used it before and it's free :) Its under the Gnu General Public License, so free to use for personal or commercial purposes, which I hope makes this usable in the game.

**Comment by Zitchas** [comment]
Looks good. We don't have any restrictions on what software is used to make the content, just so long as the images are compatible with the game license. That being said, we strongly prefer that the files used to make the image (usually a .blend and a .xcf) are added to the main asset repository to facilitate people using them to improve and/or make new assets in the future.

**Comment by yafflehk** [comment]
Ionic Shielding. The oldest and least effective shield available in human space, it provides the barest protection from the rigors of space travel and almost no protection from actual weapons fire. I think it should be super cheap and obviously a useless antique available only at weird backwoods outfitters and maybe as a default shield on a cheap old ship. The secret is it protects against ion storms and ionic based weapons that the average player will only encounter in the late game.

**Comment by SpearDane** [comment]
I could make a trinket. I've introduced some religious stones into my 'The Deep' PRs. The second one actually rewards the player with a stone that acts as a small heatsink in the ship. But I could probably create another small quest that gives the player the ability to get a stone that doesn't appear to have any effect. A weightless cosmetic stone, which could result in surprise future missions firing. 

Or I could have the stone-trinket as something purchasable at a few worlds as a tourist item.

**Comment by Amazinite** [comment]
We now have a fair few trinket outfits in the game: keystones, brigs, luxury accommodations, the mug, Pookie, the Tear of Skade. While we could still add more, I'd consider this issue complete, as the keystones no longer stick out like a sore thumb.
