### ISSUE TITLE
Allow missions to require an attribute to trigger

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2911]
In a similar fashion to how planets can require an attribute to land, it should be possible to have missions trigger based off of a ship's attributes. This would then allow us to create specific jobs for specific ships by giving those ships built-in attributes that trigger special jobs, solving old issues like #1751 and  #536 by allowing us to give certain transport ships a `"luxury"` attribute that would allow luxury transport missions to offer.

**Comment by MCOfficer** [comment]
since you mentioned luxury transports as example, i'm just gonna leave #2661 here. either way, to me, this sounds like a useful addition with no big downsides.

**Comment by Amazinite** [comment]
This would also allow those wealthy Hai jobs to offer regardless of which version of the stone you have on, instead of only offering when you have a stone from Hai space; I'm sure they won't be able to tell the difference. :)

**Comment by Elyssaen** [comment]
Would PR https://github.com/endless-sky/endless-sky/pull/2616 satisfy this requirement?

**Comment by Amazinite** [comment]
Effectively, yes.

**Comment by lifeyouristhis** [comment]
```
mission "Escort (Tiny, Northern, Dangerous Origin)"
	to offer
		random < 40
		"combat rating" < 6
		or
			"combat rating" > 0
			has "ships: Interceptor"
```
I think it's already in-game.

**Comment by Amazinite** [comment]
That's for a specific ship category, not for an attribute.

**Comment by KyroFirehammer** [comment]
To go along with your trinkets idea the luxury tab could be added with a luxury outfit

**Comment by warp-core** [comment]
[dfa9c8a](https://github.com/endless-sky/endless-sky/commit/dfa9c8a9d8d36d0d67560675f3eb06febe921f5d)

**Comment by Amazinite** [comment]
Closing since #7797 allows the player's flagship to be checked, which is mainly what I wanted out of this issue.
