### ISSUE TITLE
Void Sprites and help

### ISSUE THREAD

**Issue by ConfusingDalek** [endless-sky/endless-sky#2914]
Void Sprites will give the generic "you do not seem to be in need of repairs or fuel" message when asked for help, if you don't. If you have no fuel, they say they can't give you any because then they "can't make it to the next system." I know this is probably pretty low-priority, but I figure it should be reported anyway.

**Comment by Hadron1776** [comment]
Void Sprites won't be able to give you any fuel because they only have 1 fuel capacity.

**Comment by tehhowch** [comment]
I think this is rectified by giving the void sprites a language

Then you will get the standard "says something in a voice you do not understand" message

**Comment by Hadron1776** [comment]
`mute` personality instead?

**Comment by tehhowch** [comment]
Yes, mute works as well (just as i was about to edit that in my reply :+1: )

**Comment by Hadron1776** [comment]
I just saw the void sprite fleet def already had `mute`
That's why I deleted my comment

**Comment by endless-sky** [comment]
Fixed by making the NPC void sprites mute (8f308c5).
