### ISSUE TITLE
Escorts with Cloaking should use it defensively.

### ISSUE THREAD

**Issue by solardawning** [endless-sky/endless-sky#2916]
With the addition of the Starling, this has become more relevant. AI ships with the Cloak trait will use it defensively to escape combat when heavily damaged. However, Escort ships with Cloak will only use it exactly when instructed to by the player, and doing so toggles on/off cloak for all ships in the players' fleet.

You'd expect that the crew of your escorts would additionally use their cloak of their own volition when heavily damaged- just like the AI does.
Just because they're on your payroll shouldn't make them suicidal. ;)

**Comment by gunqqer** [comment]
Yeah cloaking needs a revamp. Before the remnant we had 4 cloaks max with out cheating, and now we have a whole buyable ship that can have cloaking. Ship AI for escorts may be coming soon or atleast will need to be talked about with all these new features we are getting. +1 to this entire discusion

**Comment by Lineth** [comment]
Nothing to really add other than I would like to see this. It would help a lot in making a pack of Starlings an appealing fleet build.

**Comment by gunqqer** [comment]
but if we do something like that you'd need an option to turn it on and off, which then people would want more fleet personality customization

**Comment by geojak** [comment]
Cloaking has undergone quite some changes recently. Is this issue still relevant?

**Comment by Zitchas** [comment]
Yes, I think it is still relevant. Since this was started we have had gulls added to the mix, and will likely have more. Having good AI for cloak usage would be valuable.

**Comment by TomGoodIdea** [comment]
https://github.com/endless-sky/endless-sky/commit/6df393946b79112eb2a84e32486bc486ee9fe2b3
