### ISSUE TITLE
If a hostile mission target is in system, the hostile ship siren plays on loop.

### ISSUE THREAD

**Issue by ConfusingDalek** [endless-sky/endless-sky#2918]
Pretty much what the title says. Also, I have the hostile ship siren enabled in the options. 
Edit: I am on the steam beta.

**Comment by Hadron1776** [comment]
I believe this was fixed for 0.9.8 with commit ca9542c ?

**Comment by ConfusingDalek** [comment]
Oh. Lemme edit to update that I'm on the steam beta.

**Comment by Hadron1776** [comment]
Next release then :)

**Comment by ConfusingDalek** [comment]
I guess I should close this issue, then, huh? Yeah.
