### ISSUE TITLE
Suggestion: hold fire button for escorts.

### ISSUE THREAD

**Issue by ConfusingDalek** [endless-sky/endless-sky#2919]
When going out and capturing enemy ships with the help of escorts, even using beam weapons exclusively, it can be a bit hard to get them to not kill your target (especially in the case of korath raiders: since they try to jump away, they call back their fighters, making the escorts attack the raider even when it is disabled while trying to hit the fighter behind the meat shield). A button that makes your escorts hold their fire, similar to the focus fire button, would be useful.

**Comment by Amazinite** [comment]
#645

**Comment by ConfusingDalek** [comment]
So it's in the game? What is it then?

**Comment by Amazinite** [comment]
This is a duplicate is what.

**Comment by ConfusingDalek** [comment]
Oh, so you're telling me to close it? Alrighty then. It really would be nice if this was implemented at any point, though.
