### ISSUE TITLE
Idea: ground operations

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#292]
Demanding tribute is good and well, but it doesn't seem extreme enough- there should be a higher risk, higher reward option available to the player, which would bring the planet under his or her control. Something akin to say, a full out annexation of the planet. In order to do so, you need a spaceship and you need ground forces, so here is what I am proposing.
-New option to "annex" or "take over" planet instead of demanding tribute
-Added "infantry" type crewmen, or maybe just use crew from entire fleet
-Added vehicles, etc., which would only be used on ground for obvious reasons-- would serve in the same vein as the laser rifles, frag grenades, nerve gas
-"Annexed" status for planets, annexed planets give more credits per day, all ships in that sector are friendly/subservient, dialog to match
-Possibly ability to use the defense fleet of the annexed planet? Unsure about this last one.

EDIT:
-Added "troopships", would carry troops en masse
-Possibility of adding in troops instead of crew- would serve same purpose except troops do not count towards the required crew (have no formal training in the operation of a spaceship, only good with guns) and would cost less than regular crew (perhaps 50 creds/day) and would be able to be carried on all ships. Used heavily in combat, in stark contrast to the crewmen, who are both adept at combat and at the operation of a spaceship, but due to their dual role are not masters of either, troopers are far more effective on the ground but less effective in the corridors of a spaceship (presumably crewmen would know the inner workings of ships and be able to navigate the space easier, better at boarding). In order to take over a planet, you deploy troops and crew- many troops required to do so, and an incursion with only crewmen would lead to certain death. 
-Two stages of annexation: destroy planetary defense force, then go to ground and deploy troops
-Addition of a tactical map which would present the battlefields of the planet to you- the player keeps his army as one and attacks different enemy positions, taking key facilities (possib. cities?) until he/she reaches the capital, taking the planet in a final confrontation with the land based defense forces
-"Facilities" would come in the form of special buildings or locations which would either provide attack or defense bonuses to the owner, in all of their battles
-Take capital = win
-Option to gift planet to faction of choice, allied ships spawn from the planet and patrol the area
-If multiple planets in sector, player must take all before sector belongs to him/her or a faction
-Player receives a large influx of credits for taking a planet, presumably would represent the looting of the planet's coffers/treasury, and would receive large amount of credits per day due to your conquering of the planet

And that concludes this wall of text.

**Comment by gchapyzh** [comment]
Have special outfit modules that take up massive space - Hangars. You would have to remove weapons and other armaments from Large Warships (Or have special 'troopship' transports with no weapons, just space for hangars) and fill the hangars up with units of your choice. Some would be good with defense, others with attack. You would destroy ships in orbit, land, take over the capital, and then balance out your units how you like, after which you can leave. The planet can start producing ships for defense.

**Comment by gchapyzh** [comment]
Even better: Tactical menu: 

[Interplanetary](http://store.steampowered.com/app/278910/) style mapping, but on a flat map. Each planet would have a capital and certain buildings, like power generators, orbital defenses, spaceport etc. Attacking a planet would be a huge deal, especially if you are attacking planets with outfitters (even worse with shipyards.) After capturing the capital you could then claim the planet/station for either yourself or a faction.

Mission: Lead an invasion fleet to <Planet> and claim it for the Free Worlds.

**Comment by airtroop392** [comment]
Added in some additional ideas.

**Comment by thenerdfreak** [comment]
This would actually be very fun, it would be like a strategy game within a strategy game. By taking over the power generators you could completely disable automatic weaponry defenses around the capital, making it much easier. Would take a while to code I think, and it probably isn't high priority, but I would like to see this in the future. +1

**Comment by Oeleo** [comment]
+1 too it seems so fun, maybe that to begin a system to take planet like a ship, but with population that isn't reset when you quit the system (population would just increase again slowly) could be good ?
