### ISSUE TITLE
CreatingShips page is outdated and inaccurate

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2920]
https://github.com/endless-sky/endless-sky/wiki/CreatingShips
Specifically, the end of the `#data` section.
> * `"blast radius"` (Typical value value: (shields + hull) * .01)
> * `"shield damage"` (Typical value value: (shields + hull) * .10)
> * `"hull damage"` (Typical value value: (shields + hull) * .05)
> * `"hit force"` (Typical value value: (shields + hull) * .15)

Besides the duplicate `value` part which is already a problem in itself, the values that this section recommends are reasonable for human ships, but are way off for the higher tier ships. For example, by this, we'd find that a Kar Ik Vot 349 (with 57200 shields and 65400 hull) has
```
"blast radius" 1226
"shield damage" 12260
"hull damage" 6130
"hit force" 18390
```
which is twice as much as its existing explosion values:
```
"blast radius" 450
"shield damage" 6400
"hull damage" 3200
"hit force" 9600
```
A similar phenomenon occurs with ships like the Hurricane, and it's even more distorted with a Punisher:
```
"blast radius" 1930
"shield damage" 19300
"hull damage" 9650
"hit force" 28950
```
versus
```
"blast radius" 400
"shield damage" 4800
"hull damage" 2400
"hit force" 6000
```
It can't be that you're just dividing the results by their tier numbers, because it's still a bit off...

----

Other than that, I'd like to mention that the outfit ordering list on the page does not include hull regenerators, and I'd also like to know how the outfit ordering handles hybrid outfits like the systems cores.

**Comment by tehhowch** [comment]
GitHub wiki's really need to support PRs... we'd have this stuff fixed up in a heartbeat.

**Comment by gunqqer** [comment]
yeah the wiki needs updation. The OS X compiling section could be a bit clearer

**Comment by Rob59er** [comment]
Just to address Gunquuers thing even though it is off topic: the main thing that needs addressed is making the last part into a framework. The rest as far as i can tell is fine.

**Comment by gunqqer** [comment]
Slightly off topic but with compiling on OS X installing libpng and libmad with Homebrew is much easier than doing it yourself.

**Comment by endless-sky** [comment]
I've added a note mentioning that higher-tier ships should have less damaging explosions relative to their hull and shield strength. There's no exact formula for it; it's really just a judgment call for each species.

**Comment by Bladewood** [comment]
There's still duplicate "value"s...
![creatingshipduplicate](https://user-images.githubusercontent.com/16506683/29985599-a93eb724-8f2d-11e7-9b9e-e9abea836140.png)
