### ISSUE TITLE
Wanderer not appearing in logbook

### ISSUE THREAD

**Issue by ldsgsm** [endless-sky/endless-sky#2921]
I visited Wanderer space and established contact with a Hai translator (although I haven't done anything else there yet), and I visited the pug in that region of space, but neither the pug nor the wanderers are showing up in my logbook.

**Comment by Bladewood** [comment]
The Wanderer part of the logbook doesn't appear unless you have met the Hai, or went to the Hai and back after you land on Vara K'chrai.
The logbook section for the Pug in Wanderer space requires you to have completed the storyline; to have landed on Pug Iyik (before the Unfettered invasion); and to have established friendly relations with the Wanderers (at that point, you unlock their outfits), in that order.

**Comment by ldsgsm** [comment]
I did meet with the Hai, but I am not surprised about the pug.
