### ISSUE TITLE
Feature Idea: custom fragment shaders for each sprite

### ISSUE THREAD

**Issue by nylki** [endless-sky/endless-sky#2925]
Right now each sprite (ship, projectile etc) uses a single vertex- and fragment shader: `SpriteShader`. The `SpriteShader` applies eg. motion blur. It would be cool if you could additionally supply one or more custom fragment shaders for each sprite. This would allow some interesting weapon effects otherwise impossible.

So when you create a new weapon `abcWeapon` and it's projectile texture `abcWeapon-0.png`, you could also supply a fragment shader `abcWeapon.frag` which would be loaded dynamically like the textured and added by in the chain after `SpriteShader`, so motion blur etc. would not be touched.

Such a fragment shader could have uniforms like *direction*, *distanceFromShip*, *timeSinceFired*, so the shader could change in effect depending on those, eg. fade or pulse slower when it travels through space for a longer time.

**Comment by Amazinite** [comment]
>so the shader could change in effect depending on those, eg. fade or pulse slower when it travels through space for a longer time.

You can already do stuff like that by having multiple frames on the projectile effect. In what way would this be different?

**Comment by nylki** [comment]
@Amazinite True, multiple frames work in many situations. 

But with custom shaders (that get appropriate uniforms), you could draw sprites differently depending on the actual range between projectile and your flagship. You could have smooth dynamic time-based effects, even when all sprites are used up: eg. slowly fade or pulse in-out a missile projectile several times a second. You could even create different effects based on the current rotation of the projectile.

**Comment by Amazinite** [comment]
>But with custom shaders, you could draw sprites differently depending on the actual range between projectile and your flagship to name just one example.

That can already effectively be done by changing the frame rate on the projectile; assuming it isn't a homing weapon that can turn around and get closer to your ship, it's just going to be flying away from your ship as time goes on, i.e. increase its distance.

>You could have smooth dynamic time-based effects, even when all sprites are used up: e.g. slowly fade or pulse in-out a missile projectile over a duration of several seconds or minutes. 

Projectiles can repeat their frames, so I'm not sure what you mean about having all sprites used up. And as for "time-based effects," that again just sounds like a matter of fiddling with the frame rates and delay times between frames and repeats.

**Comment by nylki** [comment]
> Projectiles can repeat their frames

>  so I'm not sure what you mean about having all sprites used up

The former is what I meant by "sprites used up". Instead of repeating sprites I find the possibility intruiging tohave projectiles (and other sprites) that don't repeat, eg. constantly changing color/shape/opacity based on random functions, directions, time etc.

Additionally you would be able to get smooth transitions.

Does that make more sense to you? To illustrate my point, Imagine the ability to have a projectile that can look like this fragment shader: https://www.shadertoy.com/view/XsXXDn
Combine this with things like direction (for torpedoes eg.) to change distortion, that would make it possible to create some fascinating projectiles.

**Comment by KiLEdEnNis** [comment]
> The former is what I meant by "sprites used up". Instead of repeating sprites I find the possibility intruiging to have projectiles (and other sprites) that don't repeat their frame.

then just make an animation that lasts as long as said weapons' lifetime (partially by fiddling with the frame rate)

**Comment by kingmooselord** [comment]
I see nylki's point. A shader would allow infinite possibilities and cooler effects that would be a pain to animate by pure spritework. Even the best of animations you can spot the loop if you've seen it enough times. Would make lasers less boring too.

**Comment by nylki** [comment]
> then just make an animation that lasts as long as said weapons' lifetime (partially by fiddling with the frame rate)
First that would take a big amount of memory usage. Second that covers covers only the time-based effects, not dynamic ones, like direction of ships/weapons, distance to planets/suns, or other fancy stuff.

**Comment by endless-sky** [comment]
This doesn't seem like a terribly useful idea, but feel free to play around with it and see if you can come up with anything cool-looking. (In general, the game data is designed to be things that anyone could figure out how to create with a little bit of effort, so just using sprites creates a much lower barrier to entry than expecting people to learn to program shaders.)

**Comment by SolraBizna** [comment]
Writing shaders that wouldn't break on random peoples' hardware (e.g. mine) would be difficult, especially if the variety of uniforms is so great that "bank account lasers" are possible.
