### ISSUE TITLE
Should Quantum Keystones really take up a whole ton?

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2926]
They must be pretty huge, for that weight.

**Comment by Amazinite** [comment]
Or just really dense; at a high density, one ton of stuff doesn't actually take up all that much space.

**Comment by KiLEdEnNis** [comment]
1 outfit space though

**Comment by marphod** [comment]
There is very rarely a distinction in ES between volume and mass.  Secondary weapons/ammo and bunks are the only things iirc.  

For reference, 1 metric ton is 1000kg; 1 gram of water is 1cc (1x1x1cm). 1 kg is a cube of water 10x10x10cm.  1 metric ton of water is a cube of water 1m on a side.  Rock is more dense than water (which is why it sinks).  At twice the density of water, it'd be a cube around 79cm a side.

**Comment by gunqqer** [comment]
I feel like a keystone would be a small trinkit, fuzzy dice on your review mirror, hula dancer on your dash, etc. I don't know weather the keystone should have size/mass or not.

**Comment by Pointedstick** [comment]
> I feel like a keystone would be a small trinkit, fuzzy dice on your review mirror, hula dancer on your dash, etc.

That's how I've always pictured it too, not like a huge statue  or a giant radome on the prow.

**Comment by Amazinite** [comment]
>description "This chunk of rock from the mountains on the Hai homeworld is apparently nothing more than a good luck charm, but the Hai have decorated their ships with them since the height of their empire. More superstitious Hai claim that the stones somehow reduce the nausea induced by hyperspace jumps by making travel between star systems easier."

"[D]ecorated their ships" sounds like an exterior modification to me.

**Comment by Bladewood** [comment]
Presumably, it's also how the Remnant noticed the player's keystone and noted the differences between it and their own.

**Comment by gunqqer** [comment]
So would it be like a figurehead or prow head thingy? If it's on the outside it should only add mass, not take up outfit space

**Comment by Lineth** [comment]
I still support differentiating the Hai and Remnant Keystones more. Aesthetically, at least (it would make sense too, considering how the two races see it).

**Comment by Amazinite** [comment]
>If it's on the outside it should only add mass, not take up outfit space

Turrets.

**Comment by gunqqer** [comment]
turrets have space dedicated to them (and can't just be glued on). They have hard points. They have stuff on the inside. Glueing something to the side and installing a turreted gun are two different things.

**Comment by Amazinite** [comment]
If the argument is that things on the outside of your ship shouldn't take up outfit space then that means that turrets would have more mass than outfit space, as a majority of what makes up a turret is on the outside. I'm pretty sure interference plating is installed on the outside of a ship too.

**Comment by gunqqer** [comment]
interference plating is on the inside lining it. Think of it this way: turrets need to be connected and need to have many things being transfered (heat, power, crew, etc). The keystone just sorta sits there on the outside

**Comment by marphod** [comment]
And cargo should be volume limited, not mass limited.  And there shouldn't be a max speed in a vacuum, And disabled ships shouldn't come to a stop outside of interacting with a major gravity well.  And ejected cargo shouldn't go poof.  Radar jammers and solar panels should use no outfit space as all they really are are externals.  If you're not landing in a gravity well (travel station to station), you should be able to lash cargo to the hull.  Atomic engines shouldn't have a constant rate of acceleration, but be a series of bursts.  
Nuclear weapons shouldn't be surprising as that's how atomic engines theoretically work.

This is another game simplification.  I don't have an issue with it.

**Comment by MessyMix** [comment]
@marphod, that was beautifully put. I agree entirely. It'll be too confusing to have separate metrics for volume and mass, and right now it gets a little confusing ("space" vs  "tons" aren't exactly differentiated), but I'm okay with that simplification.

(But, you're not 100% correct on the atomic engines. Nuclear Pulse Propulsion has the highest efficiency and thrust of all nuclear engines, but NPP isn't the only kind of nuclear propulsion. See NERVA and nuclear thermal rockets: you *do* end up with a constant acceleration, and in a much more conventional manner.)

**Comment by gunqqer** [comment]
(Offtopic but nuclear engines are fun in kerbal space program on long range probes before you get ion tech)

The one major difference between the keystone and the other outfits you mentioned, marphod, is that those outfits need to be connected through more than lashing a rope. Do I really care if we have it take up space? Eh, I would prefer it to be "size" less mostly because it fucks with my current ship setups... But does it really matter? I don't think so, it's more of a lore argument 

(Something we all need to remember is when arguing over stuff is it a lore thing or a gameplay thing. You don't need to not argue because one or the other just keep note)

**Comment by Pointedstick** [comment]
FWIW, I wasn't trying to start a hard sci-fi debate about mass vs volume or internal vs external outfits. Just wondering whether it was intentional that Quantum Keystones are huge-ish, when I'd always envisioned them as pretty small.

**Comment by Lineth** [comment]
They're probably just moderately big and really dense.

**Comment by KyroFirehammer** [comment]
Or it could be like the "pilots licence" where it's there but takes no outfit space. Even with that said I think it would be cool if it were to take up space that it would add some cool ascetic design to the colored parts of the ship there were more keystones with different colors (such as on the very tips of the winhs it sorta blended the colors of the basic color of the ship [like the FW green or merchant blue] and that of the keystone [similar to how the Alpha ships have a purple base with a red tip effect to them])

**Comment by MessyMix** [comment]
those are actually legitimate ideas that could be considered. I like them,
although we need to keep in mind the difficulty with coming up with these
graphics. Good job! :)

**Comment by gunqqer** [comment]
It will be also really difficult if we go down the route of being able to add things to the outside of ships (aethstetcily). It would mean every ship already made would have to be changed to be able to have places from them to be put (new hardpoints) and all new ships will also have to have these hardpoints.

**Comment by Pointedstick** [comment]
Yeah but it would be sooooo coool. Like how great the turret graphics look.

**Comment by gunqqer** [comment]
I agree it would be cool, but is it worth the work and if we add a ton of tiny details we will need a way tourn them all off for bad computers

**Comment by MessyMix** [comment]
Depends how much work it is. If it's hard on the computers, a preference wouldn't be a bad idea.

**Comment by KyroFirehammer** [comment]
Yeah a toggle feature on it would be great or perhaps if there were multiple designs that the toggle would also cycle through them.

**Comment by SolraBizna** [comment]
(My two favorite exotic forms of space propulsion are [open cycle gas cores](http://www.projectrho.com/public_html/rocket/enginelist.php#id--Nuclear_Thermal--Gas_Core--Open_Cycle) and anything involving [fission fragments as propellant](http://www.projectrho.com/public_html/rocket/enginelist.php#id--Nuclear_Thermal--Fission_Fragment--Fission_Fragment). Er, wait, this is off-topic...)

From a game balance perspective, I like the choice between "become able to visit the Waste without a Jump Drive" and "use that last ton of space for something else". One ton seems to be around the right number to make that choice an interesting one. More would mean it usually wouldn't be worth the space, and less would bring up the evils of fractional outfit space.

**Comment by gunqqer** [comment]
Oh, totaly, the only outfit that can have fractional outfit space is and should only be ammo.

**Comment by KiLEdEnNis** [comment]
*fractional mass, nothing should have fractional outfit space

**Comment by Bladewood** [comment]
It's not that it's impossible or doesn't work properly in-game, but, yeah, actually doing something like that in real content is pure evil.

**Comment by KyroFirehammer** [comment]
Or where it takes no outfit space and adds some mass ( like nerve gas almost)

**Comment by Pointedstick** [comment]
This falls under the umbrella of a "Trinket Outfit", and I think one ton is acceptable now. I can imagine it being a huge impressive statue-type thing you put in your ship's passenger quarters.
