### ISSUE TITLE
Aesthetics: Multiple Barrel Weapondry

### ISSUE THREAD

**Issue by kingmooselord** [endless-sky/endless-sky#2927]
So, this is a fairly minor thing, but for some reason it makes a lot of the weapons feel lamer to me. Say we have a quad blaster turret or a dual laser turret and the images show guns on both sides of a rotating mount.

However the actual firing pattern in game is a single exit point. I feel like it would be neat if we could designate offsets for each barrel on a weapon that a projectile either exits at random or sequentially.

Something like a rocket pad firing all of its rockets with a slight left to right deviation, blaster turrets alternating between left and right, laser turrets firing two beams rather than one, etc. Just a bit more flair and life to the weapons.

**Comment by solardawning** [comment]
Laser turrets (and other beam weaponry with multiple per turret) do fire two beams. Because they're 'continuous' weapons, they can't fire faster- so they deal double damage and use a different fire effect, which shows two beams side by side rather than one.

No comment on the rest. Could be cool, not sure it's worth the trouble. You'd have to be zoomed pretty far in to notice.

**Comment by gunqqer** [comment]
yeah it's a cool idea but I don't know if it's worth doing. Something neat I assure you and a good detail but we don't need to add a ton of small details most won't see or appriciate

**Comment by SolraBizna** [comment]
In a real Gatling gun, each barrel fires at the same point in the rotation. No reason an energy weapon should have to work that way, though; and the rocket pod example is a good one as well.

> yeah it's a cool idea but I don't know if it's worth doing. Something neat I assure you and a good detail but we don't need to add a ton of small details most won't see or appriciate

Fortunately, it's Open Source. Someone unrelated to the project could easily adopt this idea and spend a day or two tinkering on it. As for small details...when turret graphics were added recently, I definitely noticed and appreciated it. (And then [took a silly screenshot](https://bunker.tejat.net/googly_kestrel.png).)

**Comment by gunqqer** [comment]
That's something I hope everyone remembers: If they have a sugestion they can always try to make it themselfs. Learn how to use git, how to code with C++. If you make a PR instead of an issue (so you have working code that we can play) we can have a good discution on it and test it out ourselfs.

**Comment by kingmooselord** [comment]
Well, I actually asked since I could easily code/implement it but wanted to see the reception of the idea. The thing is, even if it is open source, if the community or lead dev doesn't care for the idea many people won't bother implementing it if it isn't absolutely critical for their own use. Gotta test the waters ya know?

It was just something I noticed/thought of while trying to refactor the AI to not be silly. Small details, or polish as some would call it, are what can make or break a game to many people.

**Comment by endless-sky** [comment]
Given how small the hardpoint sprites are and how hard it would be to even notice the effect unless you were watching in slow-motion and 200% zoom, this just doesn't seem worth it.
