### ISSUE TITLE
Planet Eye?

### ISSUE THREAD

**Issue by banditizer** [endless-sky/endless-sky#2929]
while doing a wonder quest line i tried going through the eye to the new sector and i just hang at "planet eye" all the planet landing is there trade, bank and   but no shipyard      cant transport through it with the wonderer ships i need.  how to finish the quest now?

**Comment by KiLEdEnNis** [comment]
did ya use the Steam version? built from source? edited game files? I remember this issue being fixed #2794

**Comment by gunqqer** [comment]
I'm pretty sure the updated steam version fixed it, but if you had this problem before the fix you'll have to revert to an ealier save or edit your save file manualy

**Comment by Amazinite** [comment]
Duplicate of #2794, please close this issue.

**Comment by banditizer** [comment]
Okay i saved my game data and reinstalled the game (after completely purging the old one) same thing happens instead of going through the eye it just lands on a fictitious planet    if this is an old bug why is it happening now?

**Comment by jafdy** [comment]
The error is in the save file. The event that created it is now stuck in there, you will need to revert to an earlier save or edit the file.

**Comment by tehhowch** [comment]
https://groups.google.com/d/msg/endless-sky/54pD5G50vwg/_3lm6h_wBAAJ
https://steamcommunity.com/app/404410/discussions/1/1471966894879637838/

**Comment by banditizer** [comment]
THANK YOU VERY MUCH  tehhowch.  that help me save my progress its nice to know that those in the knowing will help us clueless newbies with problems   again thank you
