### ISSUE TITLE
Feature request: hotkey to clear current target

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#293]
This is a simple one: It would be great if there were a hotkey to clear current ship being targeted and revert to "no target". Perhaps the "delete" key could be assigned to this function.

**Comment by thenerdfreak** [comment]
If you are referring to clearing it so you can hail the planet, there IS a hot key specifically to hail the planet

**Comment by guillochon** [comment]
That is one practical reason for clearing the present target, but there are other reasons to do so, such as not inadvertently firing upon a friendly ship. It can also be quite distracting to continue to target a ship that has left your system that you're not interested in anymore.

**Comment by gchapyzh** [comment]
Its sometimes annoying having this one escaped pirate boat stuck on your radar.

**Comment by guillochon** [comment]
FYI I have created a pull request to add this feature to the game, https://github.com/endless-sky/endless-sky/pull/300

**Comment by endless-sky** [comment]
Pressing the "Select next ship" key already clears your target selection if your currently selected target has left the system, so basically the only situation where this would be useful is to avoid firing on a friendly ship. But, if there are any hostile ships in the system at all, you can just press "Select nearest hostile ship" instead, and if no hostile ships are present there is no reason you would be firing weapons. So, this really does not seem like a useful enough feature to merit its own key command.

**Comment by jafdy** [comment]
A feature request and a implementation are weighted differently. The PR may simply have found an insufficient solution while the issue may contain a perfectly reasonable idea.

**Comment by AdamKauffman** [comment]
Good find @Amazinite ! Would it be prudent to add "FIXES #293" to PR #4366 ?

**Comment by tatami4** [comment]
This could be closed, as #5661 added ship deselect by clicking anywhere.
