### ISSUE TITLE
Minor bug: Aescolanus shows wormhole link to Cardea before it is visited

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2934]
If I go to Cardea and take the wormhole train all the way to Aescolanus, it displays a link to Cardea, even though I hadn't "landed" on the wormhole in Aescolanus yet, and thus would not have known where it would have lead to.

**Comment by tehhowch** [comment]
Currently the game will show you a wormhole link so long as you have visited both endpoints, and not only if you have *used* both endpoints.
https://github.com/endless-sky/endless-sky/blob/97c1fae2e1a9ecec2d14cf44b34101f37e763b05/source/MapPanel.cpp#L639

One can handwave this as your ship's sensors recognizing the particular spectrum of cosmic radiation that emanates from the wormhole.
We could tack a "wormhole use tracker" onto the player, which would store the utilized endpoints of a given wormhole, and only draw the link between consecutive endpoints, but this is a QOL change that I will leave to MZ.

**Comment by endless-sky** [comment]
It'd be really complicated to fix this - the game would have to track what links you've traveled, not just what systems you've visited. Given that there's only one multi-stop wormhole in the game so far, it doesn't seem worth it.
