### ISSUE TITLE
Worlds end

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2935]
After trashing the pug and them mysteriously vanishing from deneb where is a wormhole leading to two systems the final one being what appears to be a quarg ringworld but as they stand are pointless other than being entirely unsettling.
With the addition of the quantum keystones it would be very interesting to see this place be used because it appears that someone (or something) had killed everyone there and left without a trace. The planet with the gas pumps seems to be a large meet point long sense abandoned this could be a collapsed wormhole that on the other side could contain new species the pug homelands and potentially the origin of the wanderers ,quarg ,and possibly even the drak 

Thoughts on how this place can be built upon and not just some random spooky dead end, through a wormhole where some aliens disappeared into.

**Comment by gunqqer** [comment]
Not really a place for this. Discutions like this are more for google groups/subreddit/steam forums/discord. Please close this issue and take it somewhere more appropriate. (Also, commas have a space *after* not before)

**Comment by tehhowch** [comment]
The systems' sole purpose **is** to be unsettling.

Please close this issue.

**Comment by Amazinite** [comment]
The ES Github is for feature requests and bug reports. Discussions like this are more suited for [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or the [Google Group](https://groups.google.com/forum/#!forum/endless-sky),

**Comment by KyroFirehammer** [comment]
Ok I'll end this but I want to out the idea up on the table
