### ISSUE TITLE
Bug: switching landing sites still refers to first landing site

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#294]
If you are in a system with multiple landing sites, you will see the following message when pressing the "l" key to land (for this example I'm in the Tarazed system):

> "You can land on more than one planet in this system. Landing on Wayfarer"

If you press "l" again, you switch landing sites (say, to Echo), however no new log message is produced, this continues to be the case until the original message "fades" after 30 seconds or so. I think the game should show a new log message when one switches landing targets, something like

> "Now landing on Echo"

to give a visual indication that the landing target has indeed changed.

**Comment by jafdy** [comment]
Check the top left by the radar. the box tells you what the autopilot is up to.

**Comment by guillochon** [comment]
I have created a pull request to fix this issue, https://github.com/endless-sky/endless-sky/pull/307.
