### ISSUE TITLE
[0.9.6] Power check ignores solar

### ISSUE THREAD

**Issue by Musaran2** [endless-sky/endless-sky#2942]
When leaving outfitter and checking that energy generation is enough for propulsion, solar generators are ignored.
(KP-6   Photovoltaic Panel, KP-6 Photovoltaic Array, Small   Collector Module, Large Collector Module)

Not amount of them seems enough, even more than compensating for the maximum 1/5 power reduction.

The probable cause is that it checks only for `energy generation`, not `solar collection`.

Workarounds :
- Install any energy capacity, it shuts the check.
- Force exit with escape and reload, and it works as expected.

**Comment by MessyMix** [comment]
0.9.6? That wasn't a typo, was it? If it was fixed in 0.9.8, you really can't be complaining that it was a bug on a previous build...

refs #1879 #1896 if this issue is persistent

**Comment by tehhowch** [comment]
By `worst 1/5 power loss` I hope you mean 1/5 effective power, because you lose 4/5 of the power generation, not 1/5. If you are thinking that only 20% of solar collection is lost at large distances, you are doing your calculations incorrectly: only 20% of the stated power is available.

**Comment by endless-sky** [comment]
I think the redone flight checks in abf8b78 should address this.
