### ISSUE TITLE
Enhancement Suggestions: installed outfits and ships unfit to fly

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#2944]
The short story, 4 suggestions:

1. ~~_(visual)_ show visual hints for outfits that are installed in the selected ship(s) in the Outfitter, maybe filled-in versions of "outfitter selected+.png" and "outfitter unselected+.png" or maybe change the color and/or width of the lines~~ (the frustration it's trying to solve has already been handled by the "installed only" view);
2. _(restriction)_ allow the player to leave the Outfitter when a ship is unfit to fly (making it possible to fully strip outfits from a ship and sell the empty hull in the Shipyard another day) and instead prevent unfit ships from departing the planet (unfit ships must be parked, the current conversations appear when you try to depart);
3. _(visual)_ show visual hints for ships that are unfit to fly, maybe a red ```!``` on the corner of the ship icon in the Shipyard/Outfitter (top right corner below "Your Ships:") and a red line in the "Player Info" tab;
4. _(information)_ list why the ship is unfit to fly in the details (in the Outfitter/Shipyard ship details and in the "Ship Info" tab that is next to "Player Info").

--

The long story:

I'm a newish player playing v0.9.6 in steam. I started a new pilot to try out mining while carrying people around. After upgrading my Shuttle to a Scout, I tried capturing disabled pirate ships and found it very profitable! From then on I always had a full crew on takeoff and captured what I could before landing and parking the captured ships. I got lucky in "The Deep" and captured a Corvette that was fast, had range (4 particle cannons) and had more crew bunks.

The corvette has served me very well, but I've had to pass up on capturing some big ships. Having fragmentation grenades and swapping 2 particle cannons for 12 crew bunks is not enough to capture a Falcon or a Leviathan. When I got the "Pirate Reconnaissance" mission to visit the 4 pirate systems in "The South" my combat rating was almost enough to demand tribute from Bloodsea in Antares, so I decided to try it out, but first I wanted to upgrade my ship and recycle the parked ships.

After arriving at my target shipyard system, I land, unpark all ships, depart from the planet, wait for everything to arrive, and land again (there were 126 ships in the save file). The shipyard is straightforward, but the outfitter is frustrating with many ships:

- it's hard to see what is installed on a ship with a glance because other text can appear over the outfit ("in stock" or "in cargo"), which means I have to stop and actually read the text (**see suggestion 1**);
- after selling off all the outfits of a ship I can't leave the outfitter because the ship is unfit to fly, and I have to fix 1 ship problem at a time (**see suggestions 2, 3, 4**);
- other frustrations have already been reported (like #2607) or the suggestion is too much of a hassle (like filtering/searching).

**Comment by ghoulavenger** [comment]
If your intent is to sell a ship, you would be better off just selling the ship first. All the outfits that were on the ship will be available for purchase at the outfitter afterward for the same price you would have received if you sold the stripped outfits first, so there is no money loss for repurchasing the old outfits. Depreciated outfits are also given precedence in the case that you're buying outfits that they normally sell. Just make sure you handle all of your outfit repurchasing before you launch (because outfitters reset after you do).

**Comment by tehhowch** [comment]
0.9.6? You should have 0.9.8. this will also bring an "installed only" view where you can view only the outfits installed on the selected ships.

For 3: https://github.com/endless-sky/endless-sky/pull/2675 (which you appear to have seen). Right now it won't merge unless there is an amazing and unprecedented outpouring of demand as-is - I need to rework it to convey the information in a manner more consistent with the design UI.

For the flight worthy checks, they could indeed be moved to takeoff, but this poses a different problem: now you have twice as many screens to flip through to get the same information, and you won't know there is an issue until you are trying to take off, rather than when you are trying to leave the outfitter.

**Comment by gunqqer** [comment]
When you leave the outfitter maybe it gives you a message saying ship X won't be able to take off because Y then giving you the option to stay in the outfitter or leave (which you could turn off in settings ofc)

**Comment by ghoulavenger** [comment]
>For the flight worthy checks, they could indeed be moved to takeoff, but this poses a different problem: now you have twice as many screens to flip through to get the same information, and you won't know there is an issue until you are trying to take off, rather than when you are trying to leave the outfitter.

Funny, I thought that might be more of a way to discourage people to use ships as storage units. We still do, but if we could strip out the power that'd allow quite a few more outfits. Still think that there should be an armoury or something where you can deposit outfits you might want to use for a later date -- not all outfits can be bought so the outfitters aren't very appropriate, and aren't persistent either.

**Comment by flaviojs** [comment]
@tehhowch

> 0.9.6? You should have 0.9.8. this will also bring an "installed only" view where you can view only the outfits installed on the selected ships.

I not using the "beta" branch, so it's 0.9.6 for me. Sounds like the frustration that suggestion 1 is trying to solve has already been handled. :)

> For the flight worthy checks, they could indeed be moved to takeoff, but this poses a different problem: now you have twice as many screens to flip through to get the same information, and you won't know there is an issue until you are trying to take off, rather than when you are trying to leave the outfitter.

I don't see how you would need to flip though more screens with suggestions 2, 3 and 4... If I want to leave the problematic ships parked, I get the needed (visual) information in the "Player Info" tab, which is where I have to go to park the ship. If I want to fix the problems I can enter the Outfitter, see the problematic ships by looking at the ship icons, select a problematic ship, see all of it's problems in the ship details and buy the required outfits, which is way less work than what I have to do now (when there are multiple problems).

When I foolishly started recycling the ships by stripping all the outfits of the smaller ships (to improve bigger ships and then try to assemble some smaller ships from the leftovers) I ended up having to spend more than 1 hour trying to leave the outfitter... I have no idea how many times I had to press the leave button and read the message describing the problem (only 1 problem of 1 ship is reported each time), but it was very frustrating... >.<

@ghoulavenger

> Funny, I thought that might be more of a way to discourage people to use ships as storage units. We still do, but if we could strip out the power that'd allow quite a few more outfits. Still think that there should be an armoury or something where you can deposit outfits you might want to use for a later date -- not all outfits can be bought and the outfitters don't store outfits indefinitely, so aren't very appropriate to this purpose.

Using ships as outfit storage is something I'd consider for mid-game and end-game, since there isn't a single location where I can buy or order everything I need. I can't even buy the outfit as cargo and transport it to my target location, unless I get lucky and manage to plunder it.

I have to travel a lot before I get the ship hull I want with the outfits I want, risking losing millions in each battle until it's complete. Instead of that I plan to "abuse" captured ships, leaving them parked until I manage to install the outfits to make them compatible with my play style (or until I capture better ships).

**Comment by tehhowch** [comment]
0.9.8 is the latest stable release.

You can easily buy into cargo even on 0.9.6, by deselecting all ships. The common selection modifier keys Shift and Ctrl work in the manner that one expects them to work.

There are mods available which allow the player to (eventually) access a location with all the (base game) content available in one place.

**Comment by Amazinite** [comment]
>I not using the "beta" branch, so it's 0.9.6 for me. 

Part of being on Github is the assumption that you're playing as up to date as possible, be that either using the newest release (regardless of whether it is considered in beta on Steam or not) or compiling from source like many of us do. If you're one or two updates behind then stuff like this where you ask for a feature that is already present in a newer update or mention a bug that is already fixed is bound to happen all the time.

If you don't want to opt into the beta out of fear of breaking your game and there is a current beta available, I would suggest you try and stick to Steam's bug report and feature request subforums for Endless Sky.

**Comment by gunqqer** [comment]
Anyways the game is pretty stable even using the "unstable" updates. If you save often you'll be fine and only need to revert or edit your game once in a while. This is just me but I've seen only 1 bug that required a save revert and it could have been just fixed my editing my save.

**Comment by flaviojs** [comment]
@tehhowch

> You can easily buy into cargo even on 0.9.6, by deselecting all ships. The common selection modifier keys Shift and Ctrl work in the manner that one expects them to work.

By reading the first-time help I knew about buying in bulk with ctrl and/or shift, but did not know about  buying to cargo by deselecting ships with ctrl+click. I'll submit a separate bug report for that to be mentioned in the first-time help.

I'm glad to know about it, thanks. :)

@Amazinite

> If you don't want to opt into the beta out of fear of breaking your game and there is a current beta available, I would suggest you try and stick to Steam's bug report and feature request subforums for Endless Sky.

I tried 0.9.8 and suggestions 2, 3 and 4 still apply, but they are less frustrating now that I know how to move outfits to cargo (sell outfit, deselect ship and buy it back to cargo). ^^

**Comment by tehhowch** [comment]
What's remaining on this issue? From the summary list in the OP i think 2 and 3 are resolved, while the 4th is not (PlayerInfo/ShipInfo panel do not display the warning/error icons or tooltips).

**Comment by endless-sky** [comment]
I don't see any compelling reason to add the warnings and errors to the fleet / ship info panels. Unless it's a ship that you plundered before capturing it, the only time ship mis-configurations will be introduced is in the outfitter, and that's where you're going to go to address them or to figure out what ship has an issue, as well.

**Comment by tehhowch** [comment]
It's possible the player chooses to park the offending ship while on the planet that can fix it, and then unpark it from another system. Indicators on the relevant PlayerInfo/ShipInfo panel would quickly explain the reason why the ship is failing to rendezvous with the player.

**Comment by hellminister** [comment]
how can we send the order and hire the crew for a ship thats park in a very far system then the one we are in?

**Comment by KiLEdEnNis** [comment]
@hellminister a bit hard to understand, but fortunately I understood
you can't hire extra crew on escort ships as it has no use, so you can't hire extra crew for an escort that's parked in another system

**Comment by hellminister** [comment]
@KiLEdEnNis my meaning was more along the lines of why can we unpark a ship that is in a different system considering the time it would take for the order to get to that system and that theres no crew on those ships

**Comment by jafdy** [comment]
We have FTL communications. We definitely have FTL communications.

**Comment by KiLEdEnNis** [comment]
and if you mean when you park ships on uninhabited or alien planets; it'd be extremely annoying if you had to bring in extra crew from human space to man the ships; gameplay over minor realism
