### ISSUE TITLE
Remnant outfitters don't sell supercapacitors despite using them.

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2952]
The Gascraft uses supercapacitors yet the outfitters in Remnant space don't sell them. They should sell them or just give them an integrated battery.

**Comment by Amazinite** [comment]
Essentially a duplicate of #1213
Gascraft are old ships (which aren't normally sold), so it makes sense that they would also have old technology that isn't normally sold.

**Comment by Amazinite** [comment]
Fixed by #3761 by making the Gascraft's batteries built in (as opposed to making space for a crystal capacitor that would allow for easy installation of a cloaking device, ref: https://github.com/endless-sky/endless-sky/pull/3535#issuecomment-357287254).
