### ISSUE TITLE
Should Remnant space's raid fleet be the Korath?

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2964]
Lore says that Korath occasionally raid their system. This is set via the fleet definitions for their systems. 

However, the Remnant government has no raid fleet defined, so a player is free to run a trade-only fleet amongst the (currently added) Remnant worlds. Based on the worlds available now, setting the Remnant government's `raid fleet` to be `Korath Raid` (Raider + 2 Chasers) is pretty sensible, but if the Remnant worlds get expanded significantly, this may no longer make sense as the new worlds could be pretty far from Korath-accessible space.

I'd like to hear feedback on this proposed change

**Comment by Bladewood** [comment]
Problem with your pull request is that these Korath have jump drives.
Which makes farming them *far* easier.

**Comment by tehhowch** [comment]
Indeed, the Remnant fleets would engage the raiding Korath ships alongside your own. To use the existing Raider (Hyperdrive) variant would need a new fleet as well (since you can't define a fleet directly in the raid fleet specifier).
