### ISSUE TITLE
Fighter related enhancements 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#297]
Firstly fighters are week meaning that in a big battle you will lose as many to exploding ships as weapon fire. 
Secondly a new class of fighter. The heavy fighter. Put them on the largest warships. They could literally be an interceptor with the hyperdrive uninstalled.
Thirdly an outfit that would change fighter bays into perhaps 2 drone bays if you so wished.

**Comment by airtroop392** [comment]
Unfortunately, it's not just fighters- once you have a ship like the Bactrian, you can disable Sparrows in literally half a second with the base loadout. <a href="https://www.dropbox.com/s/2nccp21fl3h6x3l/endless-sky-pipmod.rar?dl=1">Pipmod</a> attempted revamping some of the combat mechanics, and, in addition, added the Sparrow as a fighter. It does work a lot better than the Dagger (the most expensive and effective fighter in base game) and is actually exactly what you describe, it's the base sparrow with no hyperdrive. However, in a big battle, you are just as likely to lose these as you are Daggers- big ships with many turret hardpoints (and almost every single ship has lasers) destroy interceptors easily, and turning the Sparrow into a fighter doesn't make an exception of it.

**Comment by endless-sky** [comment]
The whole point of fighters is to be weak weapon platforms that can do a lot of damage only if there are large numbers of them. A fighter that is strong as an interceptor would be completely unbalanced.
