### ISSUE TITLE
Turret mount hardpoint sprites - bases

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2970]
![heavy anti-missile 2x](https://user-images.githubusercontent.com/16506683/29738313-77bcd39c-89ed-11e7-8d37-4aa2e64c84fd.png)
![dual sunbeam turret 2x](https://user-images.githubusercontent.com/16506683/29738315-7ccc525e-89ed-11e7-9670-b4a553d55c84.png)
They tend to look weird with the turret bases.
![sillyturrets1](https://user-images.githubusercontent.com/16506683/29738326-df62fdfa-89ed-11e7-8d77-c65386475204.png)
![sillyturrets2](https://user-images.githubusercontent.com/16506683/29738327-e08bcb3a-89ed-11e7-9797-c956b64a91bd.png)

Also, @rob59er brought up the issue that the regular Anti-Missile Turret is basically invisible...

**Comment by Rob59er** [comment]
https://drive.google.com/drive/folders/0B9khRJPmS75hWWpvOUItSG9qYTQ?usp=sharing collection of messed up/weird examples of turret sprites.

**Comment by KiLEdEnNis** [comment]
to make it look way better
something to not let the turret base move along would require rendering the base independently and have that drawn below the rotating turret and not rotate itself
to cover turret mounts, something similar with size difference in engine flares could do, on bigger ships the same turrets look bigger yes but at least they cover the base

**Comment by Bladewood** [comment]
independent base and turrets: yes, that was what I was hoping for.

**Comment by tehhowch** [comment]
One thing to remember is that the bases will render by default pointing away from the center of the sprite

**Comment by endless-sky** [comment]
In my opinion the only real issue is the anti-missiles - the base being way too light-colored on one, and nonexistent on the other. So, the solution might just be to rework those two sprites.

**Comment by Pointedstick** [comment]
@endless-sky agreed. Smaller bases would help, as would tweaking the hardpoint locations on ships like the Kestrel that currently have the hardpoints on the outer edge of the hull.

**Comment by Tadrix** [comment]
How about not including bases in hardpoint images at all? They would be embedded into the hull anyway. As it is now, they look "glued" on the hull, instead of being part of the ship.

**Comment by KiLEdEnNis** [comment]
it's not unreasonable to think the turret base gets mounted on top of a hardpoint, meaning the base is visible too

**Comment by Tadrix** [comment]
Looks weird to me (in which I concur with Bladewood), but it could be pertaining to taste.

**Comment by KiLEdEnNis** [comment]
having the base drawn on top but not rotate along would require another picture of each turret to be drawn, and I'm not sure how well the code can handle multiple drawn layers
but it would look a lot better

**Comment by Amazinite** [comment]
#4250 at least changed the anti-missile turrets. Should this be considered v0.9.9 (done) and be closed?

**Comment by quyykk** [comment]
yeah
