### ISSUE TITLE
"FW Katya Alt 2: ready" event not triggering

### ISSUE THREAD

**Issue by mootootwo** [endless-sky/endless-sky#2980]
The Alt 2: ready event is not triggering after the specified 21 days.

Declined "FW Katya 1" and have the appropriate log entry.  Completed all other available FW missions and have "assisted free worlds" 3.  Well over 21 days have elapsed.

Checked autosave file -- it matches with "FW Katya 1: offered" (not done) and "assisted free worlds" (only 1, not 3).  Has log entry for decline Katya 1, and no Alt 2: Ready event.

**Comment by tehhowch** [comment]
That would be because the event does not actually exist in the datafiles.

**Comment by endless-sky** [comment]
Fixed by merging #2981.

**Comment by JakubFojtik** [comment]
This is still not fixed as of today on Steam version. I had to manually add the line:
	"event: FW Katya Alt 2: ready"
into my save file then got the quest immediately.
Maybe it's because the event is used before it is declared?

**Comment by Amazinite** [comment]
>on Steam version

That's because the Steam version doesn't contain the fix.

**Comment by JakubFojtik** [comment]
Wow i would have thought a fix almost 2 years old would definitely be there.
What is the reason it's missing? Or is it explained somewhere already?

**Comment by tehhowch** [comment]
@JakubFojtik The version of the game on Steam has not changed since August 2017. There are no newer releases than v0.9.8. When there is a more recent release that contains the code changes made since v0.9.8, then Steam will receive that release, and in that will be the fix for this and many other issues, new content, and so on.
