### ISSUE TITLE
Plural forms missing for some ships

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2986]
The Albatross needs a `plural` line, otherwise you can get
> Enter a name for your new Albatrosss! [sic]

Also, we got into an argument on whether the plural form of Summer/Autumn Leaf was Leaves or Leafs...

**Comment by Rob59er** [comment]
To sum up the argument: Neither came out on top, both seemed to have been used in English.

**Comment by tehhowch** [comment]
As it is a proper noun, it gets to forgo plural rules in a kind of choose-your-own-ending adventure.

I would say that it is Summer/Autumn Leafs, just as it is the Toronto Maple Leafs, and not the Toronto Maple Leaves.

**Comment by Bladewood** [comment]
I argue in favor of other existing ship designs, like Modified Argosies and Marauder Furies.

**Comment by lifeyouristhis** [comment]
Since we are talking about ships: I've noticed there is a difference in "required crew" of Marauder Leviathan and it's variants.

**Comment by Bladewood** [comment]
Should the plural of `Gascraft` just be `Gascraft`, or `Gascrafts`? https://english.stackexchange.com/questions/255727/why-is-the-plural-of-aircraft-not-aircrafts

**Comment by MessyMix** [comment]
Gascraft. Sounds much more natural.
"All **Gascraft** should stay away from indigenous lifeforms" vs. "All **Gascrafts** should stay away from indigenous lifeforms"

**Comment by Bladewood** [comment]
It doesn't really sound very natural to me. It sounds weird, not being plural in the same way as other words.

**Comment by tehhowch** [comment]
-craft is generally both singular and plural, but can take an s ending as well.

As a proper noun, Gascraft should probably take an s when plural.

**Comment by MessyMix** [comment]
*cracks grammar knuckles*

For one, “craft” is both singular and plural, but normally takes an –s ending only if “craft” is being referred to as to mean a skill or a trade, i.e. “woodcrafts”, according to an English professor at WSU. (https://brians.wsu.edu/2016/05/31/crafts/)

Let’s not forget that the name “Gascraft” etymologically derives from compounding “gas” and “craft”, and despite the fact that “Gascraft” is a proper noun, it should retain the same pluralization as “craft”. Consider the word “Starfish.” The term “Starfish” refers to the species, so it’s a proper noun, just as a “German Shepherd” is a proper noun (http://grammar.yourdictionary.com/capitalization/capitalization-of-animal-names.html). “Starfish” is a compound of the words “star” and “fish”, and retains the same singular-plural property of “fish.” That’s one of the reasons why I think Gascraft’s plural should stay as Gascraft. 

Plus. When you refer to more than one AT-12 Guardsman trainer planes, you’d probably say “Guardsmen” and not “Guardsmans”, which shows that there are exceptions to the rule of “add –s to pluralize a proper noun. Also, the plural form of Beechcraft—proper noun—is still Beechcraft. I think the same deal should hold with Gascraft.

**Comment by Bladewood** [comment]
[I win.](https://github.com/endless-sky/endless-sky/commit/18bacbc4f9a269cab5ceed1349097b616cf0d29e)

I think that's about it, so I'll close this now.
