### ISSUE TITLE
Can't thrust and turn at the same time.

### ISSUE THREAD

**Issue by ddwwcruz** [endless-sky/endless-sky#2987]
If the thrust button is pressed the turn buttons don't work. Apparently happens when autopilot is engaged as well.

System: Ubuntu 16.04

**Comment by Proont** [comment]
Have you changed the default outfits?  The most likely cause is that you don't have enough energy to use both your thrusters and steering at the same time.  Upgrade your power source, add a battery, or downgrade your engines.

If you're using a stock ship then I don't know.

**Comment by Amazinite** [comment]
If your power generation is too low and you have no batteries, you will not be able to do some things simultaneously (e.g. thrust and turn or fire weapons, thrust, and turn). Most non-continuous weapons also require a battery to fire as their per-frame energy requirement exceeds the generation of most power generators.

**Comment by endlesssteve** [comment]
Check the energy status of your ship while accelerating and turning. It"s the silver/grey bar with the lightening symbol. It goes down when you use energy. If it's empty when your accelerating then there is nothing left to turn with as mentioned by the others. I though this simple visual check might help.

**Comment by ddwwcruz** [comment]
It's the energy. Thanks guys.
