### ISSUE TITLE
Enhancement: Improved missile defense

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#299]
Pirates, merchants, and military alike are unlikely to have less than 2 missile launchers installed on any ship. Most pirate Argosies have 2 or more Meteor launchers. On the Bactrian, which comes with 2 <b>heavy</b> anti missile turrets, which are woefully short ranged, a stream of Javelin missiles are easily destroyed, but Meteor missiles and Sidewinder missiles become almost impossible to destroy due to the large influx of missiles. This problem would be easily solved by adding in by adding in a new tier of missile defense which would be more effective than the other two tiers.

**Comment by Oeleo** [comment]
There are already better anti missile turrets on korath ships and really good anti missile turrets on Quarg ships (i'm not sure that I have understand so sorry if i'm off the subject). But I agree that heavy  anti missiles turrets are already little effective so the normal version...

**Comment by naehc** [comment]
There's the Pug anti-missile system as well, which is also a step up from the two "human" turrets.

**Comment by airtroop392** [comment]
I get what you guys are saying, but I don't think I worded my intentions correctly- I guess what I'm getting at here is that there is no single effective "basic" buy turret, rather there is alien technology which does a lot better and is extremely hard to find. In that case, there should be a new "basic" turret available for purchase which is more effective than the standard turrets (hesitant about changing the other missile turrets because I'm afraid it'll mess with save files in some shape way or form).

**Comment by Oeleo** [comment]
Yes I agree for that, as I said heavy anti missile turret are little effective, if you don't move in the same way as the missile you will rarely destroy it. Ps : **SPOIL**
Spoil
Spoil
But while waiting, alien technology are not so rare, you just need to know where they live

**Comment by Pointedstick** [comment]
I find that a single heavy anti-missile turret works great against meteors as long as I'm running away from them so each missile is exposed to the anti-missile lasers multiple times. Easily 90% of them are destroyed. With two heavy anti-missile turrets,, a ship is virtually immune to missiles if you fly it this way. Are you flying your ship towards the missiles or something? Cuz that's not gonna work. But really, in a Bactrian, what are you worried about? You have 17000 shields!

I do think the non-heavy anti-missile turret is underpowered and mostly a waste of space.

**Comment by airtroop392** [comment]
Normally, I don't care about missiles hitting my ship, but down in the south, missile equipped Argosies overpower my defenses and have disabled me multiple times- and the anti missile defense on my ship has done almost nothing to stop them. And, of course I try to fly away, but missile speed > ship's speed, and missile health > damage of anti missile turret shot- it takes like 2 to take down a meteor missile, and meteor missiles can be fired by the AI in rapid succession, and as they have unlimited stores hidden away in their ship, I can't really do much about them except install more missile defenses, but seriously, 2 heavy missile turrets should be more than enough to stave off missiles.

**Comment by gchapyzh** [comment]
Perhaps a laser battery for anti-missile defense? A singe turret that fires a laser so many times per sec, but hits are guaranteed. The cost is massive energy and heat requirements.

**Comment by airtroop392** [comment]
That would make sense- that way only extremely heavy ships would be able to equip them and prevent abuse by smaller cargo/warships.

**Comment by Oeleo** [comment]
a little rectification, they stop to shoot after ~2 minutes.

**Comment by endless-sky** [comment]
If you're getting destroyed by meteor missiles in a Bactrian, you're probably not very good at dodging. Unless you ship is very slow, you can evade meteor missiles by flying *towards* them at an angle - basically, tacking back and forth to approach an enemy while dodging their missiles.

**Comment by Pointedstick** [comment]
Are we playing the same game? I equip all my turret-capable ships with a single heavy anti-missile turret and find them to be superb at destroying incoming meteor missiles as long as I do my part as the pilot.

**Comment by airtroop392** [comment]
Most of the time, the anti missile defense actually works fine (there's maybe a couple that get through, but I brought this issue up after in a recent playthrough, my ship was destroyed by two Argosies with missile launchers and a Falcon with torpedoes, my ship being able to avoid the Falcon's lasers for the most part, but being hit by multiple missiles and the occasional torpedo. Refer to this poorly constructed image: ![image](https://cloud.githubusercontent.com/assets/16041937/11454471/442054d8-95fb-11e5-98f5-64c7540b8901.png). However, if I turned in the other direction, the Argosies ran away, continuing to fire their missiles, which would have reached my ship faster because of my change in velocity. Illustrated here, in this shitty sub-ACME diagram: ![image](https://cloud.githubusercontent.com/assets/16041937/11454547/9c2cefea-95fd-11e5-93fc-d903db3e1f4d.png).
By the way, I'm using the 500 series Atomic thrusters, but I am carrying a couple hundred tons of mission cargo, so I am being slowed down a tad bit, but I'm not a turtle. Okay, sure, if I wasn't weighed down by the cargo, I could probably escape the missiles- but that's not the point, the point is that missile defenses are not nearly as effective enough as they should be.

**Comment by Man-animal** [comment]
I don't agree either.  It takes a LOT of sustained missile fire to overwhelm the two heavy AM turrets on a Bactrian, and between that and the heavy shields on it you have plenty of time to escape if necessary.

**Comment by Oeleo** [comment]
@airtroop392 In the situation that you shew, you could flee the argosys and destroy the falcon with your turrets while fleeing (theoritically you have better stuff than a normal ship, at least several good normal D-67 or D-94 shields, so you're better in 1v1). You continued to flee until the argosy have no ammos, after that they will come to attack you with their other weapons and you can kill them easily.

**Comment by airtroop392** [comment]
OK, I'll just drop this. Apparently no one else has a problem with missile defense, and more likely than not it's just my own playing style, and I don't even know it. I'll try to test the missile defenses again and see how they fare, and if I find anything I'll endeavor to record and share the footage. For now, issue is closed.
