### ISSUE TITLE
making tehhowch a person in-game

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#2991]
I asked @Amazinite on the Discord who said I should make an issue about this to see what the others think

so why I am proposing to make @tehhowch a person in-game? he's been doing lots of coding for the base game, some of them big enhancements, I feel like all this work deserves a reward

so if ya agree w/ making him a person in-game, thumbs up, if ya don't agree (for whatever reason) thumbs down
(and I get my own vote too)

**Comment by tehhowch** [comment]
I appreciate the nomination and recognition, but I'm sure there is better stuff for us to spend our time on. Plenty of stories are left to be written. I'd suggest the next persons go to those who write the Syndicate and Republic stories, or contribute a new civilization to the base game - much more visible and important milestones for the game than a few tweaks here and there.

**Comment by KiLEdEnNis** [comment]
Pointed got one with a lot of hails; it's because ya just did so much
ya don't have to do much more besides picking a ship, outfitting it and creating some hails, and if you wanty a modified ship one of us can make it for ya

**Comment by Amazinite** [comment]
@tehhowch You're in 3rd place for number of commits added to the game, 10 behind Pointed and 18 ahead of Wrzl, and they already have their own in-game persons. As long as you aren't against it, I support the idea.

**Comment by KiLEdEnNis** [comment]
adding that a lot of the commits are good quality-of-life or even big impactful coding changes (you basically coded 2/3rd of the recent coding), I, and apparently quite some others, feel like this is deserved

**Comment by jafdy** [comment]
This basically gives you permission to create your own person when you are ready. (MZ willing)

**Comment by MCOfficer** [comment]
count this comment as thumbs up. sorry, i can't use any emojis in mobile :/

**Comment by KiLEdEnNis** [comment]
@tehhowch so it's a definite no? if so just know that if you want to later on, the "community" already agreed to

**Comment by KyroFirehammer** [comment]
100% agree also @amazinite should get one as well (if  they dont already [I don't really pay attention to the names of them :p])

**Comment by KiLEdEnNis** [comment]
if ya agreed ya could have thumbs up'd, as for saying Amazinite should get 1, that's not related to this issue?

**Comment by KyroFirehammer** [comment]
I was merely stating that I thought they both deserved a author ship

**Comment by KiLEdEnNis** [comment]
they do, but let's leave this topic w/ Tehh deciding if he wants a person or not, once he answers I'll close the issue, and if he wants to in the future he already has this issue to refer to

**Comment by Amazinite** [comment]
@KyroFirehammer 
>also @Amazinite should get one as well

From #1979

>@Amazinite After all the work you've done, you'll need to make your own Person ship... and arm it accordingly!

>@Pointedstick lol, not yet. :)

Still not feeling it.

**Comment by endless-sky** [comment]
I'd certainly not be opposed to it, if @tehhowch wants to propose a ship and some hails.

**Comment by Amazinite** [comment]
Given all these recently merged PRs now launching @tehhowch to the #1 contributor of commits aside from MZ, @tehhowch absolutely needs to be an in-game person. :)

Or are you going to do something cheesy like make us wait and have your 100th commit be the PR that adds your person?

**Comment by tehhowch** [comment]
Hmm I didn't even think of that 😂

As of earlier today I still have a net removal of code lines so it's not
incorrect to say I haven't added to the game 😎.

I have a few more things in mind that I'd like to accomplish before I make
a pull, but I have put together something.

**Comment by endless-sky** [comment]
Plus, if we add a person for you in 0.9.9, the changelog can just say, vaguely, "Added a few new special 'persons'" and not spoil the surprise that one of those is [Serenity](https://github.com/endless-sky/endless-sky/commit/56c880a16d276c6a621c1f0d82151249e426628f). Because certain Firefly fans are going to start weeping the first time they unexpectedly see that thing go flying by.

**Comment by jafdy** [comment]
Perhaps he should get a coding credit as well.

**Comment by tehhowch** [comment]
In credits.txt? Ludicrous. There's plenty of credits given already - every commit says who authored or changed which lines and when.
I see credits.txt as identifying contributions without which the game would be unrecognizable. With regard to programming, that is IMO only MZ. Q: "Who wrote ES?" A: "Michael Zahniser"

If you're really burning to put my tag somewhere, open a PR to credits.txt and make a new section, "Esteemed Contributors". But don't forget your own names when adding to it.

**Comment by KiLEdEnNis** [comment]
I wouldn't mind having Tehh in credits.txt, since his recent coding changes have a great positive impact on the base game
he's basically coding-MZ junior by now, so why not

**Comment by KiLEdEnNis** [comment]
closing because it's added
