### ISSUE TITLE
shader compilation failed

### ISSUE THREAD

**Issue by Daniel5t5game** [endless-sky/endless-sky#2992]
I can't open the game. it says "shader compilation failed". I have Windows 7 ultimate and i tryed everything but it still doesen't work. help me this is my favourite game.

**Comment by tehhowch** [comment]
Can you share a bit more about the system you are playing on? Shaders are very hardware-related, so including both the model and driver version used for your graphics adapter would go a long way

**Comment by Daniel5t5game** [comment]
I have a mother board  tipe: gigabite GA-MA770T-UD3P 2GB RAM. With WINDOWS
10 it was working well, but now I have windows 7 and it shows me that error
when I start the game even when I reinstalled it. I don't really know what
happend the only difference is the computer operating system.

Il 2 set 2017 16:53, "tehhowch" <notifications@github.com> ha scritto:

Can you share a bit more about the system you are playing on? Shaders are
very hardware-related, so including both the model and driver version used
for your graphics adapter would go a long way

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/endless-sky/endless-sky/issues/2992#issuecomment-326748876>,
or mute the thread

**Comment by nylki** [comment]
@Daniel5t5game Does that error or others happen with other games after you changed your running system?

**Comment by Daniel5t5game** [comment]
Unfortunately only with this game..

Il 6 set 2017 14:13, "Tom Brewe" <notifications@github.com> ha scritto:

**Comment by jafdy** [comment]
That product code refers to a stick of ram (produced by gigabyte). I'm also quite glad you have a motherboard, although you seem to be lacking a CPU and GPU/integrated graphics. 
Knowing about your GPU would be quite helpful.

**Comment by Daniel5t5game** [comment]
Processor: AMD Athlon(tm) II X2 245 Processor 2.90 GHz
System at 64 bit
Ram 2.00 GB

That's all I can find..

Il 6 set 2017 16:56, "jafdy" <notifications@github.com> ha scritto:

**Comment by jafdy** [comment]
So integrated graphics on a processor so old that even AMD can't tell me anything about it.

**Comment by Daniel5t5game** [comment]
Well, knowing that one time it was working, it's possible to play older
versions? Maybe I could play anyways..

Il 6 set 2017 18:02, "jafdy" <notifications@github.com> ha scritto:

**Comment by tehhowch** [comment]
You can download older releases from the blog page. It sounds like your issue was caused by an OS-level change (downgrading from Win10 to Win7), so I don't expect changing the Endless Sky version to help you much.

**Comment by Daniel5t5game** [comment]
Ok thanks for everything 👍 up to now your assistance is the best and the
fastest with the answers 💪. I'll see if other versions will work or I'll
probally change my operative system.. Thanks again!

Il 6 set 2017 19:08, "tehhowch" <notifications@github.com> ha scritto:
