### ISSUE TITLE
Doesn't run on Linux

### ISSUE THREAD

**Issue by qubodup** [endless-sky/endless-sky#3]
In git 5d2844933f7045506becfd4eb01cd09e60652107 on Arch Linux 64 bit ES compiles but doesn't run.

<pre>Starting program: /home/qubodup/src/git/endless-sky/endless-sky 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1451700 (LWP 8978)]
[New Thread 0x7ffff1c52700 (LWP 8977)]
[New Thread 0x7ffff2453700 (LWP 8976)]
[New Thread 0x7ffff2c54700 (LWP 8975)]
bt
[New Thread 0x7fffebccd700 (LWP 8980)]

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff2c54700 (LWP 8975)]
0x000000000047fe3d in (anonymous namespace)::ReadPNG(std::string const&) ()
(gdb) bt
#0  0x000000000047fe3d in (anonymous namespace)::ReadPNG(std::string const&) ()
#1  0x00000000004804e3 in ImageBuffer::Read(std::string const&) ()
#2  0x0000000000504d78 in SpriteQueue::operator()() ()
#3  0x00007ffff6a35df0 in execute_native_thread_routine () from /usr/lib/libstdc++.so.6
#4  0x00007ffff6c91374 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff61a527d in clone () from /usr/lib/libc.so.6</pre>

Installed packages:
<pre>$ sudo pacman -Q | grep -e gcc -e scons -e libpng -e libjpeg -e mesa -e glew -e openal
gcc-libs-multilib 4.9.2-4
gcc-multilib 4.9.2-4
gcc-objc 4.9.2-4
glew 1.12.0-1
lib32-gcc-libs 4.9.2-4
lib32-glew 1.12.0-1
lib32-libjpeg-turbo 1.4.0-1
lib32-libpng 1.6.16-1
lib32-libpng12 1.2.52-1
lib32-mesa 10.5.3-1
lib32-mesa-libgl 10.5.3-1
lib32-openal 1.16.0-1
libjpeg-turbo 1.4.0-1
libpng 1.6.16-1
libpng12 1.2.52-1
mesa 10.5.3-1
mesa-demos 8.2.0-4
mesa-libgl 10.5.3-1
openal 1.16.0-1
scons 2.3.4-1</pre>

**Comment by endless-sky** [comment]
What CPU do you have? If it is a relatively old processor, it might not support SSE 4.1 instructions. In the SConstruct file, try replacing "-msse4.1" with "-march=native".

**Comment by qubodup** [comment]
Hi, my CPU is an AMD Phenom(tm) 9550
Support: MMX, SSE, SSE2, SSE3, SSE4a, Enhanced 3DNow!, NX bit, AMD64, Cool'n'Quiet, AMD-V
with your change it works.

No idea how to automate testing for support of sse4.1 though.

**Comment by endless-sky** [comment]
Well, I guess targeting SSE 4.1 was a bit too aggressive - it looks like
AMD only started supporting that in 2011 (Bulldozer). I think I can easily
change it to only requiring SSE 3, which has been supported in all new
processors since 2005.

**Comment by endless-sky** [comment]
Switched to only requiring SSE 3 instructions, after verifying that I don't actually use any SSE 4.1 instructions in the code. I believe that should fix this issue.

**Comment by akien-mga** [comment]
Fixed by c9bf6882, for the sake of completeness :-)
