### ISSUE TITLE
Changing illumination direction?

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#3002]
While working on the Remnant ships, I played around with the ship illumination and found that part of why ES ships tend to look flat and cartoony is because they are rendered with the illumination coming from nearly overhead. I've created a [plugin](https://endless-sky.github.io/dark-ships-plugin.zip) with the ships re-rendered with the light coming in at a sharper angle, and I'm interested in what others think of the results.

For example, here are the Kor Sestor ships using the current sprites:

![before](https://user-images.githubusercontent.com/11450262/30006476-490750aa-90c7-11e7-8f64-319fb8015987.jpg)

Here's what they would look like with a sharper illumination angle:

![after](https://user-images.githubusercontent.com/11450262/30006480-575ab3f4-90c7-11e7-8e43-29373d4e0dcf.jpg)

And, here's a big fleet of human ships, using the plugin:

![fleet](https://user-images.githubusercontent.com/11450262/30006509-dd52d93c-90c7-11e7-9bde-8f0b86057487.jpg)

The exact illumination angle and the strength of the "fill lights" added to keep the shadows from being pure black might need some tweaking, but I wanted to get more feedback before putting too much more time into this.

**Comment by Lineth** [comment]
Yes please.

**Comment by Bladewood** [comment]
OH GOD.

**Comment by Bladewood** [comment]
Uh, link broken.

**Comment by Rob59er** [comment]
Should make this a DLC

**Comment by endless-sky** [comment]
Fixed the link. Sorry about that.

**Comment by Kryes-Omega** [comment]
The ships definitely look a lot more 3D, the shadows are really nice on the Sestor ships, but my concern would be that the ships would become _too_ dark, and some of the shadows would blend the ship with the black of space.

**Comment by tehhowch** [comment]
@comnom @Elyssaen 
Care to share the before/after for the Trin assets with these possible changes? I know the existing sun angle had caused some rather prominent reflections on some of the larger ships.

Personally, I'm for any changes that remove "cartoony" and replace it with "gritty" or "realistic."

The last cartoony bit is of course the issue of statically rendered shadows, and a discussion on changing the default graphics would be remiss without questioning if/how we could add support for, but not require, dynamic renders of the ship shadows and lighting (e.g. 595 plus more).

**Comment by comnom** [comment]
I think it helps the Sestor ships; I'm not quite sold on the human ones. I think because they have so many fins in the screenshot, the shadows end up over harsh on those. Not sure how blender internal does ambient lighting, but in cycles all you'd need to do is use a lighter background or adjust the strength if you don't want to fiddle with fill lamps:
![capture](https://user-images.githubusercontent.com/22107649/30007906-d13d235e-90e6-11e7-8db7-970d9d537ff1.PNG)

I'm not too keen on rerendering all my own plugin ships to match, nor having Elyssaen rerender the Trin ships since my toaster would take hours. (to say nothing of all the other plugins out there, some of which are no longer maintained but still functional)

That's one of the big reasons I'm against things like 595, along with raising the barrier on new creators, but a lighting adjustment and rerender isn't all that bad honestly. Just drudge work.

That said, do I think it looks better? Yeah it does. Am I eager to redo a bunch of stuff? Na. Would it kill me? Na.

@tehhowch I would rerender a couple to see, but they take too long. I've actually switched to using something called filmic blender which eliminates most of the glare on glossy materials, just havent decided if I wanted to redo the Trin ships to take advantage of it.

**Comment by endless-sky** [comment]
Part of the issue with the human ships is that many of them have the fins made really tall so they'd cast a decent shadow with the previous, nearly-overhead lighting. So, doing this right would involve tweaking the models a bit.

Since this was just a "rough sketch" to give an idea of how it would look, I didn't do quite enough fine-tuning on some of the human ships. In particular, the first half of the alphabet probably needs more fill lighting. And, I think I should make the sun brighter and at slightly less of an angle to avoid the muddy grey look that some of the ships end up with.

**Comment by Amazinite** [comment]
I see that (nonminable) asteroids are included in the plugin as well; excluding the large metal asteroid, I think the asteroids look fine with the new lighting. As for the ships included in the plugin, the only one that I found overly dark is the Dreadnought. Some ships though (e.g. Modified Argosy and Vanguard) look AMAZING with this new lighting.

**Comment by Lineth** [comment]
Yeah they do. It does highlight how dated some of the human ships look though (The rainmaker stood out a fair bit on this to me). Bot overall this is a fantastic change.

**Comment by MessyMix** [comment]
@comnom, if you're worried about render times, we can all SheepIt together. I'm sure the whole Discord (+more) will be willing to help, amirite? :)

While we're at it, do we know of any content creators that are NOT using blender to generate their sprites (apart from Phil, who eventually started Blendering anyways)? Relevant to 595.

**Comment by jafdy** [comment]
The sestor fighters look a bit odd as they don't cast a shadow, it is most noticeable when docked on the right.

I think this is a good time to reconsider dynamic lighting, that would easily make 3Dness stand out and it would make running lights work better on all ships.
While I agree that it moves the bar higher for new content creators I think it would be a worthwhile investment especially if a good way of doing the normal maps (or what ever other method is used) can be found.

**Comment by KiLEdEnNis** [comment]
the 349 really shows how good this feature will be if done right, maybe a lot of ships will need individual attention, but if done right the ships should look way better and a lot more 3D, this feature really needs to happen

**Comment by Pointedstick** [comment]
To be honest, I'm not sold. Changing the shadow angle like this just makes the static lighting more obvious and visually awkward _in actual play with moving and rotating ships_. IMHO the real solution is on-the-fly normal mapped dynamic lighting, as was proposed in https://github.com/endless-sky/endless-sky/issues/595

That would have enabled fantastic lighting:

![Bactrian](https://cloud.githubusercontent.com/assets/107468/12117435/bcdfaa1c-b38e-11e5-8b80-d8834820e5d9.gif)

![Wardragon](https://cloud.githubusercontent.com/assets/107468/12189599/4897b48c-b58d-11e5-8d01-786fcb598a4f.gif)

![Maboro](https://cloud.githubusercontent.com/assets/107468/12189556/dba2e554-b58c-11e5-9fdb-b088d48f243b.gif)

And if you're going to require a re-do/re-render of all ship graphics anyway, why not do it that way, and get full dynamic lighting?

**Comment by endless-sky** [comment]
My personal opinion was that #595 looks ugly for a lot of ships (particularly the Bactrian example above) because it doesn't allow one part of the ship to cast a shadow on other parts. It also means you can't manually add shadows and highlights to simulate chrome-like materials. At any particular rotation the ships end up looking really "flat":

![shadow comparison](https://user-images.githubusercontent.com/11450262/30029168-1de55108-9156-11e7-9613-5ed6e5245e81.jpg)

Does anyone think that the version on the left there looks better than the version on the right?

**Comment by endless-sky** [comment]
I'm still experimenting to find the ideal settings, but the best I've found so far is:

- Change the sun angle from 0 / 30 / 45 to 0 / 70 / 50.
- Change the sun energy from 1.0 to 1.5.
- Turn on ambient occlusion (multiply) at strength 1.0.
- Add "fill lights" with a *very slight* blueish tinge wherever areas of the ship would be totally black. (Make sure these are set to cast ray shadows.)

In the process I've also been tweaking some of the models, in particular to add bevels to everything so that edges look less artificial and catch the light in interesting ways.

**Comment by Pointedstick** [comment]
@endless-sky 

I maintain that the Bactrian on the left looks better _as an actual sprite used in the game_. Such bold lighting looks really weird when it doesn't actually change as the ship rotates.

The _cast shadows_ on the Bactrian on the right look better, but the shadowing in general is too bold and harsh, especially if it's static.

**Comment by tehhowch** [comment]
The difference between dynamic lighting and dynamic shadowing is indeed rather large, and you are correct that at any one angle with an off-screen light source, the better-looking ship is going to be the one that has true shadows and not dynamic lighting.

As soon as there are multiple ships though, the uniformity of sense - the shading on every ship shows that the light source is in that single direction - can win out, especially when the preshadowed ships are in a variety of facings and each indicates a different position of the light source.

I do agree that the prerendered shadowed sprite allows for much greater control over the apparent material composition of the ship.

**Comment by Pointedstick** [comment]
That's exactly it. You can't judge this from a single pre-rendered frame, even if it looks great. In game, where everything is moving, the bolder the static lighting, the weirder everything looks.

**Comment by KiLEdEnNis** [comment]
but that change would be a lot more work, and it would be hard for newer modders, adding that it'll probably increase CPU usage becausse the shadows have to be calculated, and ships would look ugly from certain angles

this "static" thing does look fake when you see ships face in different directions, but it does the job with better 3D-ish looks

unless someone can make something that easily does this for ship builders, and even then it's hoping it looks better

to me static vs dynamic is basically quality looks vs realism

**Comment by tehhowch** [comment]
@dplepage did call out that 595 was not true dynamic shadows, and that such accuracy would probably relegate us to using an existing graphics engine rather than trying to composite our own solution for `sprite + normal map + height map + internal lighting = lit & shaded ship`.

@KiLEdEnNis He did also post several tools that would convert `.blend` into the normal map, and the internal lighting layers.

**Comment by KiLEdEnNis** [comment]
can't someone try to combine this new feature with dynamic shadows? just a couple of ships to show if merging that quality with the realism would look good
if it does, ES would really improve visually

**Comment by ph2000bis** [comment]
I think this is a significant improvement and one that holds up even with many ships facing multiple directions (looking a the sestor fleet) Perhaps once you reduce the fins, the ships will be lighter.

I don't know if it's possible to have light sources rendered that are located on the ship itself: that would give coherent shadows regardless of the orientation of the ship

**Comment by endless-sky** [comment]
As far as I know #595 never progressed to the point of an actual in-game demo, so it's really hard to say whether or not it would have looked good. But I have seen other games that used normal maps for ship lighting, and the effect was rather artificial-looking.

I've also tried modifying the asteroid code so that they are always drawn with their lit side facing the sun, and honestly unless I was specifically looking for it I couldn't even notice the difference. The human visual system primarily uses shadows as a way to determine the shape of things, not to extrapolate where the light is coming from.

**Comment by KiLEdEnNis** [comment]
for now this change is good enough; I really love the looks (especially on the Sestor; the human ships, if lowering the fins doesn't do it, could be a little bit brighter), and it really makes ships look 3D

once ya look at the new Sestor & human ships, once you look back all you see is flat 2D ships

**Comment by endless-sky** [comment]
As an additional comparison, here's the "dynamic" Bactrian, the Bactrian from the plugin above (70&deg; illumination) and a "remastered" version with 65&deg; illumination, higher sun energy, more fill light, and the manual shadow layer redone:

![shadow comparison](https://user-images.githubusercontent.com/11450262/30032965-7f060b84-9166-11e7-8b3f-d77cf4df2933.jpg)

I agree that a lot of the ships in the plugin have too dark shadows and a slightly muddy grey appearance, but I think the tweaks I suggested above can fix most of that.

**Comment by KiLEdEnNis** [comment]
the one on the right can use a tad darker shadows, but it's already a lot better

**Comment by comnom** [comment]
The far right bactrian is by far the best looking. The fills lights cut the ugly pure black right out, and the brighter sun allows the gradiant of grey tones on various sections to really stand out, which makes the grunge more noticable shipwide as well. I've got no complaints.

On the 595 debate: I've stated my opinion on it before, but it basically boils down to what tehhowch pointed out. That is, without a full suite of true dynamic lighting (not just shading) I think the ships look worse not better.

**Comment by KiLEdEnNis** [comment]
I can't seem to get the blue "fill lights" their properties right: I end up with a dark blue shade

what color numbers did you use (between 0 and 1) for red, green and blue, and how much energy did you make the points? @endless-sky 

if I know that I know everything I need to know to do what you did to my plugin, and I can tell others if they need to

**Comment by endless-sky** [comment]
I'm using a blue very close to white - say, about .75, .83, 1.00. The energy depends on the scale of each individual model, but I'm putting them a good distance away so they create wide illumination instead of a hot spot.

**Comment by MessyMix** [comment]
The only reason 595 hasn't progressed to a game-demo level is because you never let it.

![image](https://user-images.githubusercontent.com/20450076/30035473-82f0cdd0-9178-11e7-89fb-197fc4a8bd67.png)
![image](https://user-images.githubusercontent.com/20450076/30035512-f5983404-9178-11e7-81b4-e7139b57311a.png)

But I sense that we're not going to see dynamic shading until we get full dynamic lighting. Which I'm looking forward to.

**Comment by KiLEdEnNis** [comment]
thanks for the help, I'm in love with this shading mode, and modders that want to can try it on their own ships

![nekis predator](https://user-images.githubusercontent.com/10348657/30037192-f4bff5ea-91b8-11e7-96c8-832aa00d249d.png)

so I think this is gonna be a thing? due to the generally positive feedback and the fact that once we saw this the older versions suddenly looked very 2D

**Comment by endless-sky** [comment]
Here's a few more examples of ships with less-severe illumination, but still coming in from a significant angle (65&deg; instead of the 25&deg; currently used in the game):

![fleet2](https://user-images.githubusercontent.com/11450262/30037208-bb812ccc-9186-11e7-820f-2ccbc68e1221.jpg)

I think that fixes the issue of shadowed ship edges blending in with the background (although of course, it will look a bit different on each person's monitor). Compare that to the original plugin version:

![fleet](https://user-images.githubusercontent.com/11450262/30037221-d6b19040-9186-11e7-93dc-26c38a41b6e5.jpg)

**Comment by Amazinite** [comment]
The Dreadnought is much better with this most recent example.

**Comment by KiLEdEnNis** [comment]
there's no way to make all edges perfectly clear from the background, but this new lighter shading looks really good (better on some ships than others though), I'm a little bit worried about doing it with the Pug and Wanderers, but the Coalition/Heliarch should look good with them, and I think the Hai would also look better with it

**Comment by Pointedstick** [comment]
All right you got me, that looks pretty sweet.

**Comment by dplepage** [comment]
I haven't thought about this project since I stopped working on #595, but this thread showed up in my inbox as soon as somebody @'d me, so consider me gotten in touch with.

It's been a long time since I've worked with shaders (the mockups on the PR were just rendered in python), but I can see about getting a PR up to demonstrate the dynamic lighting in-game.

**Comment by Nechochwen-D** [comment]
@endless-sky you should really look at cycles instead of BI especially with 2.79 coming out which incorporates a new shader called principled. I would also recommend looking at using [Filmic Blender](https://github.com/sobotka/filmic-blender) to help get rid of your issues with being over exposed at high light levels.

**Comment by czartrak** [comment]
This mod is really cool, I would love to see this merged

**Comment by KyroFirehammer** [comment]
Agreed however the human ships seem a little bit dark a lighter shadowing might help that

**Comment by KiLEdEnNis** [comment]
it's the top 1 in MZ's last comment in case ya didn't know
if ya look there, the Dreadnought & Bactrian don't have very dark shadows, lighter shadows will basically make them non-visible

**Comment by endless-sky** [comment]
I've updated the [plugin](https://endless-sky.github.io/dark-ships-plugin.zip) so that all the sample ships are rendered with 65&deg; illumination instead of 70&deg and with more fill lighting. Here are some more screenshots:

![sestor](https://user-images.githubusercontent.com/11450262/30243303-a2ad4068-9574-11e7-850c-2efef5da3ba0.jpg)
![navy](https://user-images.githubusercontent.com/11450262/30243304-a60a3266-9574-11e7-9302-5d3161cb671e.jpg)
![remnant](https://user-images.githubusercontent.com/11450262/30243307-a87183f6-9574-11e7-88da-2483e05b6684.jpg)

**Comment by KiLEdEnNis** [comment]
is it gonna stay as a plugin or eventually gonna be added to the base game?

**Comment by Bladewood** [comment]
Beautiful.

**Comment by endless-sky** [comment]
It will go in the game eventually, I just want to make sure there are no show-stopping complaints about it before I redo the graphics for the other 60% of the ships.

**Comment by Pointedstick** [comment]
That is much better that what we have today, definitely.

Still would really like to see full dynamic lighting and shadowing someday.

**Comment by jafdy** [comment]
It will be a while until the next release so I would hold off on it (as it seems to be an overall improvement) and explore full dynamic lighting and shadows as well. Put this into the next release if dynamic isn't ready in time.

**Comment by KiLEdEnNis** [comment]
the only ships I wonder about if they will work:
Wanderers and Hai a little
Quarg ships (quite a bit)
and of course the Raider; it's not even made from Blender
(also don't forget Marauder and Author ships, not sure if ya have the Marauder blends but I think someone can get them)

**Comment by jafdy** [comment]
I have the marauders and pointed's.

**Comment by KiLEdEnNis** [comment]
if MZ wants it, I can use his "new template" to do the Marauders & Pointed's Vanguard for him; saves him some work
@endless-sky want me to do the Marauders & Pointed's Vanguard for you?

**Comment by endless-sky** [comment]
@KiLEdEnNis Sure, that'd definitely be helpful. The only tricky part is the number, position, and intensity of the fill lights - I didn't have a particular pixel value or anything that I was shooting for, so it's just a subjective judgment.

I found it fastest to just work with the existing .blend files in a pipeline where I opened each file, adjusted the sun angle and intensity, checked that ambient occlusion was on, then added a fill light and duplicated it as needed. Occasionally a model will need adjustment, e.g. to bevel a surface so it will catch light in more interesting ways, to flatten a vertical fin that's now casting too big a shadow, or to tweak the specular intensity on a material that catches the new sun a bit too brightly.

**Comment by KiLEdEnNis** [comment]
I can look at existing ships from your plugin if I need to, once I'm done I'll put all files in Google Drive and put the link here, if you have any feedback after that I'll update them, but I think I'll do fine

**Comment by KiLEdEnNis** [comment]
first one in @2x format, does this seem good? if so, I'll have a ship to compare the rest to in GIMP (like a template)

![pointedstick_vanguard 2x](https://user-images.githubusercontent.com/10348657/30251699-829c5e7a-9665-11e7-93cf-520dd1cca40d.png)

**Comment by tehhowch** [comment]
I'm curious as to the height of the turret mount that it casts such a long shadow... never thought of the vanguard as a "shark".. more of a MCRN Corvette to me.

I agree that the fill lighting from the SW corner of the sprite could use a little buffing, (see the "remastered" bac in the above post).

**Comment by KiLEdEnNis** [comment]
I don't see that much difference, so I think if I redo the shading in GIMP it'll look good
![z test](https://user-images.githubusercontent.com/10348657/30251800-55604e6a-9667-11e7-9e7d-af6be7ea97f2.png)

**Comment by endless-sky** [comment]
One trick might be to use the "threshold" tool in GIMP to look for how many areas of the ship itself are very dark, say less than 10 intensity levels. Here's the first 2x image you posted side by side with my dark version of the ordinary Vanguarg, with the areas under 10 grey values highlighted in red:

![threshold](https://user-images.githubusercontent.com/11450262/30252712-6db6e6c6-9645-11e7-9a33-4c130f81f649.jpg)

Large parts of the engine section, plus one corner of the "head" of the ship, are in danger of blending in completely with the background. So, it might need a bit more fill lighting there unless what is causing it is the shadow layer in GIMP. (Note that I ended up redoing the shadow layer for the majority of the ships to look better with the new illumination angle.)

**Comment by KiLEdEnNis** [comment]
that picture was with the shadow on 100% alpha, I toned it down, but I'll redo the shadow and I'll use that trick, thanks

**Comment by endless-sky** [comment]
A few more factions done:

![mereti](https://user-images.githubusercontent.com/11450262/30253731-2fb1f078-9659-11e7-8515-963a54f7b122.jpg)
![wanderers](https://user-images.githubusercontent.com/11450262/30253732-314b25d0-9659-11e7-8856-5079644db441.jpg)

**Comment by Lineth** [comment]
😍

can we has soon please

**Comment by KiLEdEnNis** [comment]
I think I got the shading right?

![pointedstick_vanguard 2x](https://user-images.githubusercontent.com/10348657/30277268-93413f00-9707-11e7-999f-494db09fffe2.png)

this is the threshold (on 10, all black is under that threshold)
![threshold test](https://user-images.githubusercontent.com/10348657/30277269-935a3a82-9707-11e7-9f52-fc2c77beae7e.png)

if it's still too dark just reply & tell me, if not I'll use this one as a template for the rest, and I'll do the threshold test for all ships

**Comment by KiLEdEnNis** [comment]
1 more comment, I hope I don't have to make any more comments until I'm done

I ran into a big problem with the Marauder Fury (I checked the other Marauder ships, they should be fine)

the problem: this is 1 layer in GIMP, the base layer w/o post-processing
![mfury 1 layer](https://user-images.githubusercontent.com/10348657/30278699-6c1e7d9e-970b-11e7-9bec-e488106a08b7.png)

this is the render, as you can see, quite some differences
![modified fury render](https://user-images.githubusercontent.com/10348657/30278708-773d51be-970b-11e7-85f6-d701aade9135.png)

it's impossible to update the Marauder Fury without changing the armor patches, hoping I can even find some good new layer for the armor patches, so how should I approach that @endless-sky ??

**Comment by jafdy** [comment]
@Wrzlprnft did that one for himself, if he can't supply the layer just find one that is similar, it's quite a small sprite so I doubt anyone will notice the difference.

**Comment by KiLEdEnNis** [comment]
it took over an hour, BUT:
I figured it was some kind of texture, and it had a piece of the image name in the texture map on those objects, I tracked it on google and found the creators' devianart (he basically had 2 textures and only 1 matched), I saved that image and applied it, and got the metal layers ON the Fury
as in I'm a wizard and the MFury can stay the same

![mfury 2](https://user-images.githubusercontent.com/10348657/30287928-32432c2a-9727-11e7-940f-59f9dfafeca6.png)

**Comment by KiLEdEnNis** [comment]
quick update; I'm about halfway; Pointed Vanguard, MFury, MArrow, MBounder, MFalcon & MFirebird (S, E & W versions, and @2x) all done, with saved GIMP & Blend files too

all that's left is the MLeviathan, MManta, MQuicksilver, MRaven & MSplinter, I'll probably have everything done Sunday, but have some irl stuff to do, I think in any case I'll be done next Tuesday (did the Falcon & Firebird today, took over an hour due to some messy work, but 2 at a day is do-able)

**Comment by endless-sky** [comment]
I've got all but 12 ships done out of all the rest, so I should wrap it up in around the same time frame.

![hai](https://user-images.githubusercontent.com/11450262/30464628-929742ca-99a0-11e7-94e4-9c798d9af41b.jpg)

**Comment by Lineth** [comment]
With the plugin I noticed that if you zoom in enough it reverts to the original. Bug? Or is that the x2 vs normal sized version?

**Comment by jafdy** [comment]
That's the 2x images coming in.

**Comment by endless-sky** [comment]
If you have the high-DPI plugin loaded too, just rename the dark ships one to something that comes after "high-dpi" alphabetically.

**Comment by KiLEdEnNis** [comment]
spent over 2 hours finishing the last 4 Marauders
https://drive.google.com/drive/u/0/folders/0B5-qbs9LtB26ZGRnaTlVLXlaMlk

**Comment by KiLEdEnNis** [comment]
@endless-sky just got the mail to grant ya access to the drive (gave ya full access)
if there's anything that should be changed, ya can do it yourself or tell me what to change, whichever ya want

**Comment by Lineth** [comment]
On this subject, is a remodel of the Korath Raider in the works? It looks really, really flat. I dunno how much the illumination change affected this however.

**Comment by KiLEdEnNis** [comment]
it has been remade in Blender for the new lighting, the tubes look a bit meh but it's quite good

**Comment by KyroFirehammer** [comment]
Hey on that topic in creating a few ships when this does hit main game will I have to make any changes of im creating them in blender

**Comment by tehhowch** [comment]
@KyroFirehammer yes. 
The sprite rendering process does not alter the physical geometry of your ship(s), but you may find that different angles of various objects in your .blend provide better visual characteristics. At minimum, you will need to change the positions of the Sun and other Lamps and re-render the output sprite.

**Comment by KiLEdEnNis** [comment]
@KyroFirehammer save this somewhere:
how to do the new shading
- change the sun rotation from 0 / 30 / 45 to 0 / 65 / 50
- increase sun energy from 1 to 1.5
- ambient occlusion on "multiply" at strength 1 (it should already be like that)
- add 1 or 2 blue "fill lights" to make the shadows non-black, coloring: .75 / .83 / 1
put those "fill lights" at a good height (say Z: 12-20), and mess around with the energy, but around .4-.5 should work

**Comment by KyroFirehammer** [comment]
Sweet thanks 
I'm creating a remnant freighter that is supposed to be based off of a syndacate bulk freighter, but has been meshed with thir Kim designs (I'm thinking it may have 2 fighter bays but idk if that would make it too OP because it can hold up reasonably well and can hold a fairly large amount of cargo) it's supposed to be their ship they use to plunder ships disabled by the rest of the fleet. 
Any suggestions are wecome (I'll be making a OR for it soon)

**Comment by KiLEdEnNis** [comment]
in any case, don't discuss that in this place; either a new issue (not recommended) or something like the Discord or Steam

**Comment by AzureNyoki** [comment]
As it stands, there's an issue with the new lighting system. The use of a bluish light, most noticeable on the shadowed areas of the ship, means that when swizzling is applied those areas can also have their hue shifted. For instance, the osprey in the images below, swizzled for free worlds, syndicate, and republic colors. 
![screenshot_2017-11-05_17-28-01](https://user-images.githubusercontent.com/31363287/32420882-e4e6ab00-c278-11e7-952f-c21f06118e59.png)
![screenshot_2017-11-05_17-28-13](https://user-images.githubusercontent.com/31363287/32420883-e6aee538-c278-11e7-8fe7-2249d7d51693.png)
![screenshot_2017-11-05_17-36-27](https://user-images.githubusercontent.com/31363287/32420885-eaa10932-c278-11e7-8096-ef8957e22d99.png)
The Republic one seems to have no issues since the eye is adjusted to interpreting slightly blue or yellow lights as "natural", but other cases such as the green-purple combo of the other ones are far more noticeable, especially when ships of different factions meet. To prevent issues with the swizzling system, the lighting used when creating the ship sprites should be neutral (white), or as close as possible.
