### ISSUE TITLE
Near death escort behavior

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3004]
When an escort is "near death" it follows my movements and ignores everything else. Which is the same behavior "healthy" escorts have when they don't have orders and there are no enemies around.

This behavior is paramount to suicide mid-battle since they are priority targets but just stand there waiting for damage, making it very hard to protect them.

I think they should actively try to stay near my ship while recovering (circle me?) and either run or face the enemy when they are hit (up to a certain distance from me).

I tried messing with the AI but failed to understand how to change their behavior when they are near death (too many behaviors are mixed in together).

**Comment by MessyMix** [comment]
So, instead of behaving like escorts with no active orders, they behave
like they have the "gather" command, unless they are too far / already
engaged, in which case they attack? Do I "gather" your meaning? (God, that
was bad.)

**Comment by flaviojs** [comment]
All I require is that they actively stay close to me (to defend them) so that's one possibility. I would have to test it mid-battle to see if it's appropriate. Gathering would probably be so-so since when I tell my escorts to gather they keep shooting past me. I imagine circling around me might be better, like when someone is scanning me.

As for when they are hit, the minimum I want is for them to face towards an enemy so the guns can shoot at it. Ideally the escort should run away from the enemy or hunt it while near me.

**Comment by flaviojs** [comment]
Hmm, another alternative is for escorts to not to have any special "near death" behavior and be suicidal like the local police. When I board them they go right back into the fight, not even waiting for shields to recover.

At least escorts would be fighting back instead of just being a siting duck...

**Comment by jafdy** [comment]
What if your ship was not a combat ship, perhaps they should gather round a combat ship instead. 
It sounds like you want escorts to behave like you would, unfortunately that is not likely to be a simple set of rules.

**Comment by flaviojs** [comment]
My ship is not a combat ship, but it has better shields and shield regen so I can be a wall.

You hint at an interesting point there, the ideal behavior of the escorts depends on what kind of ship and strategy you have... maybe being able to set individual ship personalities is enough, I'll try it out.

**Comment by ghoulavenger** [comment]
I have to admit, when I read this I thought for certain you were referring to captured ships. I don't recall any of my other ships ever behaving in that manner. If you are referring to captured ships, I thought this was a balancing metric, since the ships don't have captains but rather provisional crew.

**Comment by flaviojs** [comment]
Captured ships have the same behavior as normal escorts, they will rejoin the fight (until they are hit) if the ship's minimum hull is 50% and the shield recovers to 100%, and will otherwise behave like sitting ducks. Try letting one of your escorts get disabled by pirates, board it and you'll see it behaving just like captured ships.

Even with a provisional crew, I think they would try to run away while taking fire... unless they have a death wish.

**Comment by flaviojs** [comment]
Setting the personality of individual ship didn't help, the behaviors are too npc specific. First I'll have to figure out exactly where the escorts are deciding to "do nothing"...

**Comment by tehhowch** [comment]
"do nothing" is a bug - the ship should always be told what to do on every frame

The default behavior is KeepStation, which instructs the ship to match its target's position and velocity as best it can.

**Comment by KyroFirehammer** [comment]
Possibly have it to where they flee the combat zone infill they hit over 70%sheilds or something

**Comment by flaviojs** [comment]
@tehhowch
Thanks for pointing out KeepStation. By following it backwards I found that mid-battle escorts would need to have no target to "do nothing", which led me to the root of the problem. :)

Now that they are fighting back, they destroy most of their attackers instead of dying meaningless deaths.

**Comment by endless-sky** [comment]
This should be fixed by merging in #3008.

**Comment by tehhowch** [comment]
#3008 was a step forward (the ship will target opponents and fight back), but stopped short I think. Very injured escorts act as though they are not, happily pursuing opponents to their own death rather than 
>actively try to stay near my ship while recovering (circle me?) and either run or face the enemy when they are hit (up to a certain distance from me).


I've opened #3369 to add the above behavior
