### ISSUE TITLE
Ships can be configured to negative outfit space free

### ISSUE THREAD

**Issue by NathanZook** [endless-sky/endless-sky#3006]
Built from source at 52fb1ee6f8ba68c2fd9735d955d01dcdb3b4cde7 on Mint Linux.

I was wanting to adjust my Blackbird's build out, and observed that I have -11 outfit space free.  Cargo space is 60, bunks is 40, 1 Hyperdrive, Cargo Scanner, 3 Bunk Rooms, 1 Outfit Scanner.

What I expect happened is as follows:  When I sold my Bounder, I immediately repurchased some of my discounted upgrades.  This process must have corrupted somehow.  AFAIR, I did not attempt an impossible build.  It appears that my outfits expansion was dropped somehow after I completed my update.

**Comment by KyroFirehammer** [comment]
Did you install an outfit expansion then end up returning somehow to when there were mass expansions

**Comment by jafdy** [comment]
The change in outfit/cargo space is the same for both, besides, the mass expansions are still in the game data.

**Comment by KyroFirehammer** [comment]
Other way around @jafdy I meant you get an outfit expansion then revert to a build before outfit expansions were added.

**Comment by jafdy** [comment]
@NathanZook Could you put your save in pastebin or something. That will let us check if this is your save or not.

**Comment by NathanZook** [comment]
Will do.  I noticed some odd error messages were popping up on startup.  I started loading older games to see if/when they went away.  Wouldn't you know, they go away when I load an image where the outfits expansion is still showing...

./endless-sky 
Unrecognized outfit in Blackbird "Nevermore"
Unrecognized outfit in Archon "Sleeping Dragon"
Unrecognized outfit in Archon "Watchful Gravetender"
Unrecognized outfit in Archon "Kasiliri's Folly"
Unrecognized outfit in Archon "Sword of Eden"
Unrecognized outfit in Archon "Snows of Far Door Nai"
Unrecognized outfit in Scout "Sand of the Anchor"
Warning: effect "" is referred to, but never defined.
Warning: government "Derelict" is referred to, but never defined.
Warning: outfit "" is referred to, but never defined.
Warning: system "" is referred to, but never defined.
Warning: effect "" is referred to, but never defined.
Warning: outfit "" is referred to, but never defined.

Save from 3015-8-1.  This is good.  https://pastebin.com/H8tUWShz
Save from 3015-8-21.  This is corrupt.  https://pastebin.com/Y9MqAeg9

**Comment by NathanZook** [comment]
@KyroFirehammer I'm not sure what you mean about "going back".  Given the good save, it seems likely that the corruption happened well after buying the ship.  One thing--the save has a corporate espionage mission available but not selected.  I find I need to reload several times in order to get the scan in on those.  Given this data, I now suspect that the game load mechanism as the culprit.

**Comment by endless-sky** [comment]
Is it possible that one time, instead of running your source build you ran a copy of the game that came from somewhere else (e.g. Steam or the Debian repositories)? If you did that, any outfits and effects that did not exist back in that version would get "corrupted" because the game wouldn't know what they are.

In general, the game is forward compatible (you can run a saved game from an older version on a later version) but the opposite can't be guaranteed.

**Comment by endless-sky** [comment]
In particular, it looks like you must have loaded your pilot in version 0.8.11 or earlier of the game, because the Drak ships were added in 0.9.0. That would make sense because 0.8.11 was, until recently, the latest version in the Debian repositories.

**Comment by NathanZook** [comment]
I cannot rule that possibility out.  I have not uninstalled the Mint version.  The error messages are all from the version I built--I still have the window open. ;)

**Comment by NathanZook** [comment]
So...  New ticket:  Save files need to be versioned.  :D

**Comment by endless-sky** [comment]
Versioned save files wouldn't fix this, unless the game were changed so that it refused to load a saved game created by a later version of the program. And that would cause a whole new set of problems, e.g. for anyone who wants to try out an unstable release and then reverts to the stable one.

**Comment by jafdy** [comment]
It would let people looking at the save file know what versions it was loaded on.
Say you started on 0.8.11  and played every release until 0.9.7 and then went back to 0.9.6 it would say:
`0.8.11 0.9.0 0.9.1 0.9.2 0.9.3 0.9.4 0.9.5 0.9.6 0.9.7 0.9.6`
This might let us spot problems that occur from moving back and unless you switch version number a lot then is is still quite a light inclusion. You could even remove it later without effecting compatibility.

**Comment by NathanZook** [comment]
There are things that can be done with the save file format that would make it resilient against certain classes of upgrades, such as adding a new item which has not actually entered play.  But from a debug standpoint, this is all good.
