### ISSUE TITLE
The automatic landing feature is counterintuitive for new players

### ISSUE THREAD

**Issue by abenkovskii** [endless-sky/endless-sky#3009]
I fund it surprising that sometimes my flagship would automatically land after jumping into a system without requiring me to press L. Eventually I did notice the pattern: selecting a planet on the star map before jumping into the system causes you to automatically land. I like this feature but I wish it was presented in a more obvious way.

**Comment by Bladewood** [comment]
To note, this functionality was added relatively recently.

**Comment by Amazinite** [comment]
The map tutorial for new players has been expanded to describe this behavior.
