### ISSUE TITLE
Feature request: achievements system

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#301]
This could either utilize the Steam system, or be its own internal system that doesn't reply upon Steam. This is something the original Escape Velocity lacked but is a common feature for many games, and gives the player more things to do. Would be fun just to think of interesting achievements to include in the game!

**Comment by ItsNickBarry** [comment]
In my opinion, achievement systems are distracting, and turn what might be a cinematic experience into something more like an arcade game.  This would be especially true for Endless Sky, which relies fairly heavily on the player's imagination.  There are, of course, a few benefits which come with an achievement system, but I think all of these can also be found within the pre-existing mission system.

Consider two possible approaches:

Steam:
> You've earned an achievement: Ace Pilot (destroy 1000 pirate ships). [And, by the way, you've been playing for five hours today.  Remember when you were younger, and your back didn't hurt so much?  Where did your ambition go?  That's the human condition, I guess.  Hey, I bet you can't get 2000.]

Republic Navy officer on Farpoint:
> Hey, I recognize you!  You've taken down, what, a thousand pirate ships?  They fear your name even this far north.  On behalf of the Navy, and quite possibly all of human space, I thank you for you for your service.

**Comment by guillochon** [comment]
Certainly a valid criticism. Although there are not very many missions like the one you described in the game quite yet. Would be great to have maybe "commendations" or something that are awarded by the in-game entities like the Republic, Syndicate, etc. (think Medal of Honor, Purple Heart, Silver Star)

**Comment by ItsNickBarry** [comment]
Yes, that would be a nice addition.  One benefit of achievements that I did not address is the ability to revisit them after the fact.  A bunch of medals would look great on the player info screen.

**Comment by guillochon** [comment]
Obvious would have to find a freely-available image, but something like this on the player info screen would be great: 

![image](https://cloud.githubusercontent.com/assets/4998058/11514040/86e1eec6-9844-11e5-8428-1046a2ee1f33.png)

**Comment by Tufton** [comment]
Although I too generally have a distaste for achievements (thanks xbox!), I
think the best way to implement this would be to have certain achievements
give you cosmetic options for your ship or maybe titles or something.
Otherwise it's just meaningless fluff.

**Comment by ItsNickBarry** [comment]
These achievements could be required for unique conversation options, or for certain missions to be offered.   They could also be used to keep track of more important mechanics, such as one's rank within certain factions, implicitly linking them to the titles you mentioned.

What cosmetic ship options do you have in mind?  One issue is that ships are generally disposable, while achievements are not.

**Comment by Tufton** [comment]
I mean I guess it would be like a little logo or a custom color or
something, nothing crazy.  I guess if you like, "Kill 1000 pirate ships"
and you get a little skull and crossbones icon that you can put on your
ship or something.  Nothing crazy.  Maybe a custom engine exhaust with
sparkles? custom glass coloring (instead of dark grey)...you know,
whatever.  Personally I'd still rather not have them at all, but if we are
going to they should have *some* purpose

**Comment by Tufton** [comment]
and i mean you could apply the skull to any ship, it wouldnt be a one time
use thing

**Comment by guillochon** [comment]
Just an FYI, I have created a pull request for a commendations system: https://github.com/endless-sky/endless-sky/pull/350
