### ISSUE TITLE
Can sell disabled ships by scrolling past the end

### ISSUE THREAD

**Issue by abenkovskii** [endless-sky/endless-sky#3014]
v0.9.8
Linux
I know a similar issue https://github.com/endless-sky/endless-sky/issues/2870 was already fixed but I can reproduce this one in v0.9.8.

To reproduce:
1. Disable a ship you own in a system with a shipyard
1. Land
1. Enter shipyard
1. Click on one of your ships in the top right
1. Scroll through your ships using keyboard arrow keys until you select the disabled ship
1. Sell the ship
1. Profit

Expected:
Can't sell disabled ships

Actual:
Disabled ships are not visible in the shipyard but you can still select them using arrow keys

**Comment by tehhowch** [comment]
Should be fixed by #3015 

(good find)

**Comment by endless-sky** [comment]
Fixed by merging #3015.
