### ISSUE TITLE
Escorts travel through unexplored systems

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3016]
I captured a ship and jumped to an unexplored system (with jump drive). That system didn't have any connection with known systems or their linked systems.

Since there is no known hyperspace connection shown in the map, I was expecting the new escort to be stranded. Instead, I saw it happily traversing unexplored systems as if it knew about them, not even revealing them to me when he "discovers" them.

What is the correct behavior escorts should have in this situation?

**Comment by Bladewood** [comment]
I think there was another (ancient) issue about this, but I can't find it.

**Comment by tehhowch** [comment]
I think the escorts using systems unknown to the player should probably be avoided. This would be an `IsYours` check in DistanceMap, and then probably a HasSeen requirement in the routes' systems

**Comment by Amazinite** [comment]
Would this only apply to the escort government or would it apply to all escorts? I'd prefer the former as the latter could become a nuisance with missions.

**Comment by tehhowch** [comment]
IsYours means exactly what you think it does. :)

`personality escort` is generally what is used for mission NPCs that tag
along with you. There are a few FW missions that directly use the Escort
government, but these aren't exactly using unknown paths or destinations.

**Comment by flaviojs** [comment]
Fixed by #3020.

**Comment by endless-sky** [comment]
This is intentional, because the small loss of realism involved in an escort's captain knowing about a system you don't know about seems less important than allowing escorts to pick the shortest path to come to you. (For example, because you just unparked them or told them to stop holding position.)

It would also add complexity if player escorts had different rules for following their parent ships than all other escorts do.

**Comment by flaviojs** [comment]
Hmm, then I suppose this is a ```wontfix``` and should be closed? The alternative of having your escorts discover the system/wormhole for you would complicate events that would trigger if you discovered a system or wormhole yourself.
