### ISSUE TITLE
escorts waste all energy and are stuck

### ISSUE THREAD

**Issue by alphalupus** [endless-sky/endless-sky#3017]
[sts uiu~scouts stuck.txt](https://github.com/endless-sky/endless-sky/files/1287620/sts.uiu.scouts.stuck.txt)
i started a trip to arculus through terminus and when i arrived to terminus i changed my mind.
two of my scout escorts got stuck in terminus by wasting all of their energy trying to get to the wormhole and then constantly wasting the newly generated energy on tiny bursts of thrust(i think) resulting in them not regenerating any energy and being stuck hurtling through space.
tried telling them to hold position and gather on me when i was close to them and still no energy regeneration.

**Comment by jafdy** [comment]
Do they have generators that are not solar panels?

**Comment by Amazinite** [comment]
Looking at your save file, you seem to be attempting to use medium fuel cells in combination with atomic engines. Atomic engines are energy eaters, and fuel cells are the worst of the worst in terms of energy generation, so having energy issues is expected.

Are you on v0.9.8 or are you compiling from source? In the current master, ships which are low on energy will still be able to thrust and turn, albeit at a fraction of the normal power, which should lessen the severity of situations like this.

**Comment by alphalupus** [comment]
i'm playing through steam so i think it is v0.9.8 and yet they are still stuck.
if they don't move then even the lowly fuel cells should recharge the batteries eventually  yet it doesn't happen.

**Comment by Amazinite** [comment]
>I'm playing through steam

So this issue should be closed. The mentioned commit fixes this. I'm playing your save file right now on the latest build and witnessing no such problems.
