### ISSUE TITLE
Crash caused by attribute restricted planets and missions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3021]
If your flagship is unable to land on a planet that requires an attribute to land and that planet is a stopover (like in `"Remnant: Void Sprites 3"`), then the game will crash upon attempting to land. 

Unsure if the same would occur if the planet was a mission destination.

**Comment by tehhowch** [comment]
Got a handy save to share, for testing?

From memory, I'll guess the planet gets selected when you enter the system because it is a mission destination, and there is a missing check for the can land before doing the selection.

**Comment by Amazinite** [comment]
[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/1288969/Test.Pilot.txt)

**Comment by endless-sky** [comment]
See if 39b78bf fixes this.

**Comment by tehhowch** [comment]
I think IsAccessible should be preferred over CanLand - Canland is politically influenced as well, and bribes are a thing.

**Comment by Amazinite** [comment]
>See if 39b78bf fixes this.

Yup, no crash now.

**Comment by tehhowch** [comment]
#3024 is also tested to not crash
