### ISSUE TITLE
0.9.8 reordering ships causes crash

### ISSUE THREAD

**Issue by aonilsson** [endless-sky/endless-sky#3027]
in Mac OS 10.12.6, no plugins:

I have a dozen or so ships, and reordering them in the "I" (player info) screen causes an immediate crash. I can reorder them fine in the outfitter screen.

**Comment by Amazinite** [comment]
Duplicate of #2796

**Comment by Bladewood** [comment]
Duplicate of https://github.com/endless-sky/endless-sky/issues/2796

**Comment by gunqqer** [comment]
btw issue has been resolved, it no longer crashes (tested by myself on 10.11.5) 

Please close this issue.
