### ISSUE TITLE
Quantum key stone is doubled in outfit list, due to different spellings

### ISSUE THREAD

**Issue by MuhammadNCheema** [endless-sky/endless-sky#3028]
![screen shot 2017-09-05 at 3 33 46 pm](https://user-images.githubusercontent.com/26357616/30246709-22bd66ce-961b-11e7-98c6-cbfa7ab00a45.png)

**Comment by abenkovskii** [comment]
I'm pretty sure this is intentional. They sell for different prices and have different descriptions. One is sold in Hai space as a "good luck charm". Another is sold by remnant and they are well aware of it's true purpose.

**Comment by abenkovskii** [comment]
May be the one Hai sell should be renamed to "Hai good luck charm" to avoid confusion.

**Comment by abenkovskii** [comment]
Also you need a remnant license to buy the remnant key stone and no license for the hai one.

**Comment by abenkovskii** [comment]
Or you could rename quantum key stone to "Remnant Quantum Keystone"

**Comment by tehhowch** [comment]
https://github.com/endless-sky/endless-sky/issues/2922
https://github.com/endless-sky/endless-sky/issues/2620
