### ISSUE TITLE
Notify the player when he gets a new license

### ISSUE THREAD

**Issue by abenkovskii** [endless-sky/endless-sky#3030]
How was I supposed to know I had the Militia Carrier License all along? They gave it to me when I joined the Free Worlds but it wasn't mentioned in the dialogue and didn't show up in the outfitter (https://github.com/endless-sky/endless-sky/issues/2177). I suggest there should be a pop up message for each license the player gets except for the pilot's license.

**Comment by Amazinite** [comment]
So would this be some sort of pop-up dialog whenever you get a license or should we just put something like "you now have license to purchase our carriers" in the dialog after you join the Free Worlds, similar to how the Wanderers tell you that they'll now allow you to buy outfits or certain ships?

**Comment by KiLEdEnNis** [comment]
the latter one seems realistic, and logical; you join the FW, it's logical they notify you get a license to buy the type F carriers

**Comment by tehhowch** [comment]
I think it should be a case by case basis,  so the onus is on the license giver to pop a conversation (probably with a `scene` too) that mentions the player can buy the ships.

**Comment by abenkovskii** [comment]
IMHO as long as it's not too annoying the more obvious the notification is the better even if it's a bit redundant. It's too easy to miss a line in a big block of text. I think adding a dedicated single-choice "choice" block with a scene and a short message (e.g.  "You have been granted a Remnant license. You are now allowed to buy all remnant ships and outfits") would do. I'll try making one tomorrow.

**Comment by KiLEdEnNis** [comment]
"bla bla bla" the Remnant guy gestures

choice
"thank you"

"as you are about to leave, another Remnant fuck tells you you earned their trust, and gives you a license to buy Remnant tech"

basically that?

**Comment by Lineth** [comment]
Presumably a bit more elegant than that, but I presume so, yes. :P

**Comment by endless-sky** [comment]
Addressed by #3068.
