### ISSUE TITLE
Syndicate Target Practice Scan Does Not Move Mission Forward

### ISSUE THREAD

**Issue by CptJkeene** [endless-sky/endless-sky#3032]
According to Steam I'm 105 hours in and this is the first real bug I've found, so well done! I have not seen this bug elsewhere on GitHub. The issue is currently happening to me so if you cannot re-produce I'm happy to post whatever you need.

Problem: 
I accepted the syndicate target practice mission in Mirfak and found the ship in Bellatrix. I disabled the ship and boarded it, failing the mission. Realizing what I did I loaded my character on Mirfak and jumped back into Bellatrix, disabled the ship, scanned it, then landed on Bluestone (in Bellatrix) where I got the message that I either didn't disable or scan the ship and I need to go back to space and finish the mission. I've taken off and scanned the ship several times and see the equipment list, but when I land back on Bluestone it get the same incomplete mission message.

I'll test around some more and report if anything changes. Thanks!

**Comment by abenkovskii** [comment]
@CptJkeene if you see the equipment list you might be using the wrong scanner. The mission description reads: "... collect test data for Syndicate engineers by scanning its **cargo** ..."

**Comment by CptJkeene** [comment]
Hey, thanks. You know I thought about that but I wasn't aware there was another way to scan the ship. It's an outfit I'm missing for my ship, isn't it.

**Comment by tehhowch** [comment]
Yep, you should buy a `Cargo Scanner` to pair with your `Outfit Scanner` :+1: 
You'll observe a second scan circle when scanning.

**Comment by CptJkeene** [comment]
Idiocy confirmed. Mission passed. Thanks, guys.
