### ISSUE TITLE
Remnant Keystones mission only taking flagship's keystone if escorts are out of system

### ISSUE THREAD

**Issue by Hadron1776** [endless-sky/endless-sky#3034]
If I buy 50 Quantum Keystones to my cargo hold for the Remnant keystones mission and turn it in normally, the keystones get removed from cargo. _However_, if the keystones are bought into an escort's cargo hold, and that escort is outside the system when you turn in the mission, you will be paid the 6 million credits, but only the keystones from the ships that are in the system will be taken.

1. Have at least one ship (other than your flagship) with space to hold 50 Quantum Keystones
2. Install Quantum Keystones on both ships
3. Accept Remnant Keystones mission
4. Buy 50 Quantum Keystones to cargo. The keystones should go to the escort's cargo hold. 
5. Have your escort hold position just outside Arculus
6. Turn in the mission

Expected result: I get paid 6 million credits and 50 Quantum Keystones are taken from my cargo hold

The result I got: I still got paid 6 million credits, but only the keystone that was installed on my flagship got taken away.

**Comment by tehhowch** [comment]
While #3036 will solve this issue, it will not also fix problems with boarding or assisting missions which gift outfits.  #3005 's latest commit (a6b157322be0e959d50b571a5a70b351a98c0599) will both fix this and fix outfit gifting by boarding/assisting missions.

**Comment by endless-sky** [comment]
Fixed by merging #3036; #3005 is a much bigger change so I'll have to look at that separately.
