### ISSUE TITLE
Mission outfits: Should they be 'gifted' to or from Escorts?

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3037]
#3034 and #3036 indicated to me that I had not updated assisting and boarding missions (#3005) to account for outfit gifts / removals.
I wasn't able to find a reference to where the reasoning behind not removing an outfit from a player-owned escort in order to fulfill a mission was detailed. https://github.com/endless-sky/endless-sky/commit/408a2b85a4e3a51c921c6b2297746f3d576c20e8#diff-d927ce0729d9d492c919a80fd54a29caL146 indicates that it was resolved at some point, and perhaps that resolution was an executive decision by @endless-sky . I made an initial request for clarification [here](https://github.com/endless-sky/endless-sky/pull/2496#issuecomment-299952766), albeit not directly or very visibly.

Please share your opinions on being able to complete missions by removing outfits from ships which are not only the flagship.

**Comment by jafdy** [comment]
It would make sense, except for boarding missions of coarse.

**Comment by endless-sky** [comment]
Some missions that take outfits (e.g. the jump drive installation missions in the FW plot line) assume that the outfits are being taken from, and installed into, your flagship. Those missions would get messed up if the mechanics were changed to allow taking outfits from escorts.

The only way to fix that would be to make it possible for some missions to specify that the outfits can be taken from escorts instead of from the flagship, but I think it would still be rather confusing because there would be no way to control *which* ships the outfits are taken from if you have more than enough.

**Comment by tehhowch** [comment]
Do I understand the Shop/PlayerInfo Panel correctly? I think the order that the gift code would step through the ships would be that same display order - check the flagship, then the 1st escort, etc... If so that seems consistent enough for players to understand and plan around (and would be mentioned in the Player Manual, as well as the Creating Missions wiki page.
We'd likely want to report the names of the escorts that the gifting was done for, so that the player can update accordingly - this notification may warrant the more direct approach of a pushed Dialog rather than just via Messages::Add. 

I could also see gifted outfits always going to cargo (i.e. require the player to decide how to use them), while removed outfits come first from cargo, then the flagship, then escorts by ranking order.

This does fall into the business of "sensible gifting", wherein a content creator doing critical outfit adds/subtractions on planets without Outfitters is discouraged.

**Comment by endless-sky** [comment]
Consider how confusing it would be in FW Pug 2C if, say, a scram drive was removed from one of the player's escorts (leaving it without any jump capability at all) and then a jump drive was added to the flagship (leaving it with both a hyperdrive and a jump drive). In other words, existing missions depend on the fact that giving and taking of outfits can only involve the flagship, so if that mechanic was expanded it would still have to default to the current behavior.
