### ISSUE TITLE
Revamped tribute system

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#304]
ATM, planets will only surrender once their <i><b>entire</i></b> defense fleet is destroyed, regardless of the number of ships remaining in the player's fleet. For example, a player can have 50+ warships and the planet will not surrender until their fleet is destroyed, even if they have 1 or 2 ships left. This doesn't make a whole lot of sense, because by the time you've worn their fleet down thin they're essentially just throwing whatever they have left at you until they all die. Instead, when the size of the defense fleet is smaller than a certain percentile (or, is smaller in relation to the player's fleet), the planet should allow the player to hail it and allow the player to collect his or her tribute. Would there be any complications in turning the remaining ships friendly?

**Comment by gchapyzh** [comment]
Crazy how they throw their tiny fleet at me and wont surrender until they all die.

**Comment by Oeleo** [comment]
Taking tribute is already so easy, when there are a few ship left, you can just send fighters and they will finish the work.

**Comment by gchapyzh** [comment]
Increase in planetary defense fleets and difficulty of taking tribute?

**Comment by airtroop392** [comment]
@Oeleo, my points still stand.

**Comment by Oeleo** [comment]
Yes with a realistic point of view I agree, I just gave you a way to finish the last ships easily while waiting

**Comment by endless-sky** [comment]
I don't really see a need to change how tribute works. The very fact that you can demand tribute at all is unrealistic, and because it's a relatively minor part of the game I don't want to make it more complicated than it needs to be. (Checking the defense fleet status every time a ship dies rather than only when you demand tribute would complicate things significantly.)
