### ISSUE TITLE
Did you forget to include the font copyright into the copyright file?

### ISSUE THREAD

**Issue by abenkovskii** [endless-sky/endless-sky#3046]
I'm sorry if I'm wrong but it appears that the font files used by the game ([images/font/ubuntu14r.png](
https://github.com/endless-sky/endless-sky/blob/master/images/font/ubuntu14r.png) and [images/font/ubuntu18r.png](https://github.com/endless-sky/endless-sky/blob/master/images/font/ubuntu18r.png)) are based on the [Ubuntu Font Family](http://font.ubuntu.com/). I'm mostly judging by the file names but I examined the file contents and to me it does look like a mix of Ubuntu Regular and Ubuntu Regular Italic prerendered to specific heights. Of course I'm not a font expert. If this is true shouldn't the [copyright](https://github.com/endless-sky/endless-sky/blob/master/copyright) file indicate that?

**Comment by endless-sky** [comment]
Technically speaking, a bitmap rendered from a font is not covered by the same copyright as the font itself. If it were, then any time anyone shares an image with text in it they'd have to credit the creator of the font.

The copyright file actually serves something of a legal role, in cataloging all copyright holders for all assets used in the game and the licenses they have released those assets under. So, I wouldn't want that file to erroneously give the impression that the assets included the Ubuntu font itself.

**Comment by abenkovskii** [comment]
Ok. I'm sorry.
