### ISSUE TITLE
Modified weapons

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#3051]
In game currently there are modified weapons, and numerous mentions if them, but the only ones  are the modified blaster turret and gun. What I'm suggesting is several other modified weapons (and potentially other outfits) such as:

A modified laser turret / Modded heavy laser turret 
Modified quad blaster turret 
Modified plasma cannon
Also if we would open it up to outfits 
Modified scanners (they show cost of item along with the regular info)
Modified engines (all human types but significantly more expencive and heat intensive [modified atomic engines appear late FW campaign])
Modified capacitors (add heat snd cost an aditional outfit space but hold more than a regular )

**Comment by Amazinite** [comment]
Human space is saturated with ships and outfits as is. No point in making tons more modified stuff.

**Comment by Bladewood** [comment]
On that note, I've been planning to develop a plugin (eventually; give it a few centuries or so) based around the idea of modified outfits. This would go hand-in-hand with the Marauder ships.

**Comment by Amazinite** [comment]
>On that note, I've been planning to develop a plugin (eventually; give it a few centuries or so) based around the idea of modified outfits. This would go hand-in-hand with the Marauder ships.

Outfits only obtainable through Marauder ships is the only way I'd find more modified outfits justified.

**Comment by jafdy** [comment]
I would find something involving Smugglers Den good as well. Although the "nasty" options could do with some kind of reward.

**Comment by KyroFirehammer** [comment]
I agree that getting these (with the exception of the scanners) should only be via the marauder ships such as bounties and bounty hunters

**Comment by endless-sky** [comment]
In my opinion, it feels a little unoriginal when a game has a bunch of slightly-modified versions of an item - it's just a cheap way of making it feel like there's more variety. I'd much rather see content creators work on completely new species or unique and different outfits. And, as @Amazinite said, there are already plenty of ship and outfit varieties in human space; the bigger need is more ships and outfits for everyone else.

**Comment by KyroFirehammer** [comment]
Hmmmm the new weapons could be a remnant weapon (implying that they sole some) and the unfettered could possibly develop better versions of their current weapon tech in the wanderer campaign
