### ISSUE TITLE
FW campaign balance issues?

### ISSUE THREAD

**Issue by Lineth** [endless-sky/endless-sky#3067]
So I'm replaying the free worlds campaign and two ares really stand out as an issue from a stand point. Not that they're just challenging: they're entirely luck-based and frustrating to the level of forcing me to cheat to break through it.

- **The Electron beam mission.** Finding the gunboat is not the problem. The near-infinitely spawning navy ships that show up right afterwards, however, is. This is also an issue with any FW that demands that you cross hostile Republic territory. I can understand dangerous, but again. It's just dumb luck whter or not there's going to be a half-dozen cruisers in the system.

- **The escape section of the capture the Syndicate exec mission.** Simple enough. I get nuked the moment I enter the system. I don't get the chance to react at all.

Is it just me? I seriously think these mission need a little looking at.

I don't know about the first one, as that ties into how the reinforcement system works (which I personally think needs an overhaul). The latter is easier. Either less nukes or spawn the ships further out.

EDIT: For the record, I do in fact have a scram drive. It helps, but not enough to overcome the fact the frustration (the bad kind) of getting insta-gibbed by the RNG. I got past the nuke mission as they finally spawn far enough out that I wasn't instantly killed, but it took a dozen tries.

**Comment by jafdy** [comment]
For the electron beam mission there is a system that spawns lone gunships.

For the escape you are trying to leave the system at full speed and not trying to get away from the nukes at high speed.

Both these missions can be done in a lone dreadnought.

**Comment by endlesssteve** [comment]
For the electron beam mission I had an issue open because of failed electron turret support so I did it dozens of times testing different mission files. I never had problems. For this mission you need to be fast. Perhaps your ship is too slow or not powerful enough to disable the gunship quickly. I had a flame thrower on my ship to help with this.

Generally with spawning I have to agree with you. It's random and if the wrong ships appear in the wrong place you are dead. However getting the game to adjust the spawned ships based on your ship sounds complicated and a lot of work to me. Perhaps the odd reload is not the end of the world.

**Comment by Lineth** [comment]
Like I said, the lone gunship was not the issue. Found and disabled it no problem. The dozen or so navy ships that jump in nigh-immediately afterwards is.

As for the nukes: I just said: I had literally no time to react. I was killed before I regained control. I eventually got past both after getting very lucky. 

As a whole, I do think the FW campaign could use a bit of a looking-at.

**Comment by tehhowch** [comment]
There is a system that has only Gunboats, and only for that mission. It will not have any other type of ship that is able to spawn and jump in.
Any ships that spawned while you were in a different system can of course randomly path to your system, but they only have a small window to do so (1000 game steps).

Regarding nukespam, it's possible  https://github.com/endless-sky/endless-sky/pull/3052 will have an effect by dividing the ships into smaller functioning units. Adjusting when ships get targeted while hyperspacing could also have a significant effect, as well as adjusting the hyperspace exit point.

**Comment by endlesssteve** [comment]
Just out of curiosity what ship and which engines?

**Comment by endless-sky** [comment]
In the gunship mission, the mission text gives you a hint of a system where you can find lone gunships with no chance of other Navy ships jumping in: `Steal an Electron Beam from a Navy gunboat and return it to <planet> for Freya to look at. She thought your best bet for finding lone gunboats might be the Wei or Alnasl systems.`

The nuke mission is *supposed* to be annoying and unfair. That's the whole point of it. Just remember that the best way to dodge missiles is to [fly towards them](https://youtu.be/DlJmlsw_yY8).

**Comment by MessyMix** [comment]
MZ. You're a literal beast. No wonder people say AM turrets aren't useful... 😆

**Comment by Startome** [comment]
Honestly I like the missions as they are, and the reasons they are this way.
