### ISSUE TITLE
Remnant balance

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3069]
The Thermoelectric Cooler (T.E.C.) is underpowered.

Compare to the Cooling Module (C.M), which is equally priced and quite a bit more energy taxing, but still far more potent because of its space efficiency.
Compare also to the Small Heat Shunt, which is ~~slightly less~~ [actually more] space efficient[,] ~~but~~ is clear of any energy drain and is only *marginally* more expensive than a single T.E.C.

We have a few different options here.

1. Decrease the price of the T.E.C, for the reasons with pricing outlined above.
2. Give the T.E.C. more cooling.

Of course, you could also increase the pricing on the other coolers or nerf their cooling, but that'll create bigger problems with balancing.
I assume the reason the T.E.C. has its current attributes is so a user can get only a little extra bit of cooling when ordinary C.M.s would be a bit overkill or would drain too much energy, but right now it's too weak for any real purposes.

**Comment by KiLEdEnNis** [comment]
imo the cooling could go from 420 to say 480, and from 160k credits to 140k credits
or at least something around that (or keep 420 cooling for the meme and make it like 100k credits at most)

**Comment by Startome** [comment]
The only solutions I personally see for all this would be to lower the price a little on the TEC, or make it a hair less energy consuming.  Three coalition is mainly handy for it's good price and good efficiency for certain outfits.

**Comment by endless-sky** [comment]
Addressed in 92e2215 by reducing the price to 100k. I prefer not to have it be in the same tier as Korath or Coalition tech. At that price it's still a bit expensive, except for the fact that its small size makes it useful for ships with limited free space.

**Comment by KiLEdEnNis** [comment]
the Remnant are around human tech after all, and they may have derived their cooling from Coalition, so if they are a bit stronger than humans but not as strong as T2+ species it makes sense

**Comment by Bladewood** [comment]
> This cooler is actually just one of the power-generating elements of a Millennium Cell, but wired so it can run in reverse: consuming electricity in order to transfer heat from a ship's systems to its exterior.

Nothing in there hints at it being based on Coalition technology.

**Comment by KiLEdEnNis** [comment]
"may have"
since it's active cooling, it's possible they used the technology for their Millennium Cell too

**Comment by Bladewood** [comment]
```
"Breeder Reactor"
"Water Coolant System"
"Cooling Ducts"
```
is strictly superior to a single `"Epoch Cell"`, including price.

Someone did bring up the fair point of how outfits expansions can nullify cooling, but that's still only once you hit 4+ expansions.

**Comment by Amazinite** [comment]
>"Breeder Reactor" + "Water Coolant System" + "Cooling Ducts" is strictly superior to a single `"Epoch Cell"`

And?

**Comment by endless-sky** [comment]
You're right, they're significantly overpriced, given that they're meant to be Tier 1.2ish radiothermals, not a direct competition for any of the nuclear reactors. I've reduced the prices by about a third in ee758ef.
