### ISSUE TITLE
Has shipyard and has outfitter source and destination filters

### ISSUE THREAD

**Issue by TheUnfetteredOne** [endless-sky/endless-sky#3072]
I'm wanting to write a mission that only offers on a planet with a shipyard, but I don't want to have to write down the names of every single planet with a shipyard. This would be even worse when making missions with a source or destination that only has an outfitter. Having source and destination filters based on the presence of a shipyard or outfitter would be a huge help.

**Comment by tehhowch** [comment]
@endrosg made a pull that did this (and others): https://github.com/endless-sky/endless-sky/pull/2449

It could be included in the LocationFillter code as well

**Comment by endless-sky** [comment]
In commit 11a30e0 I've made it so that "spaceport", "shipyard", and "outfitter" attributes are now added to planets automatically as appropriate. That also means that those attributes are now reserved - if you add one manually to a planet that it doesn't apply to, it will be removed.
