### ISSUE TITLE
[bug] Hallucinations can be capped

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#3073]
I get the mission and successfully cap them, they're permanently disabled, but are part of my fleet.
![screen shot 2017-09-23 at 2 21 07 pm](https://user-images.githubusercontent.com/29336153/30776416-a3670fe6-a06b-11e7-9393-d3e7cca43bf7.png) and they aren't removed from my fleet after the mission is finished.
![screen shot 2017-09-23 at 2 21 50 pm](https://user-images.githubusercontent.com/29336153/30776427-c5e0f046-a06b-11e7-8ba9-8262d529bc84.png)

**Comment by Amazinite** [comment]
[Really?](https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt?utf8=%E2%9C%93#L1368)

**Comment by gunqqer** [comment]
Can confirm, last time I got that mission and I capped them and they're still in my fleet

**Comment by Amazinite** [comment]
Maybe y'all should just stop doing drugs.

**Comment by gunqqer** [comment]
*Grumble Grumble*.... but if I was doing them *grumble grumble* they'd be gone

**Comment by abenkovskii** [comment]
BTW AFAIK you are not supposed to be able to capture them because they are supposed to be impossible to disable. There was a bug that made them always be disabled. I fixed it https://github.com/endless-sky/endless-sky/pull/3048.
