### ISSUE TITLE
mechanics - mechanism request for avoiding instant death on takeoff

### ISSUE THREAD

**Issue by endlesssteve** [endless-sky/endless-sky#3077]
In the early game you sometimes leave a planet and come face to face with a powerful pirate ship that destroys you before you can even think. Having to reload the game after this spoils the feel a little bit and I think it could be made better.

There are several missions where there is an alarm of an incoming pirate attack so ground control know what's in the system. Why then do they let ships take off blind? 
Based on this logic I think it can be argued that some mechanism should be provided to allow players to avoid dangerous takeoffs if they wish.

Not being an expert on the game code I'm not going to request a specific change as I don't know the impact and work involved. I will however give some ideas/suggestions.

The most simple idea I have is to extend the time while the image of your ship expands to full size and normal flying/ combat starts. If the player presses L during this period the take off is aborted and the player goes back to the planet screen without combat starting. The story explanation of this is the player has picked up the other ships on scanners or is warned by traffic control.
In game play a player with a weak ship could be ready to press L and have a second to view the area of the planet and the radar before flying into the middle of a pirate fleet.

Other ideas are:
Radar preview with abort option.
Warning on screen with an abort option.

I have this situation myself and have seen it mentioned in many issues and comments. It normally gets mixed up in balance discussions but I don't believe it is a balance issue. Some times the bad guys will have bigger ships the player just needs a reasonable chance to run and fight another day.

**Comment by jafdy** [comment]
If you where to run 60 or so frames before the takeoff animation starts then pirates will start off by shooting something else (if available), it would also make it look like ships where part way through doing something when you arrived.

**Comment by tehhowch** [comment]
The game preps 5 seconds worth of fleets when you depart from a planet.

The issue is generally compounded when the player has missions that spawn pirates, particularly if they are `nemesis heroic` as they will beeline for the player and escorts no matter the other ships in the way.

A future update that adds a hint of the players likelihood to spawn raid fleets will help with the opposite issue, wherein the player shuns combat so much it becomes inevitable.

**Comment by endlesssteve** [comment]
@tehhowch 
I wasn't saying there was anything wrong with the spawning. 

I think dealing with this as a balance issue is a mistake.

I think a weak player needs more of a chance to runaway and I think there is a good explanation of why this should be possible in the game world for the takeoff from planet case.

The 50 frames doesn't seem to give enough time to try and land again.

**Comment by Bladewood** [comment]
And what is the difference between this and just reloading your save and departing again?

**Comment by jafdy** [comment]
Feels better.

**Comment by endlesssteve** [comment]
Yes, it feels better. 
This is not as trivial as it sounds because we only play Endless Sky because it feels good.

**Comment by ghoulavenger** [comment]
It feels better, I can agree with that, but more important, it takes some of the unfairness of the game out. If people want to play ironman, things like this stop them from really doing it and progressing. Granted, I think this is just the tip of the iceberg if we're talking about unfair deaths which would make ironman a much more realistic possibility.

**Comment by endlesssteve** [comment]
@ghoulavenger 
Yes there are other situations. I thought it best to pick the one situation I thought I could argue a fairly simple and effective fix for and raise a specific issue to focus just on that one thing.

I've seen other issues get bogged down in the general balance discussion and not get any where.

Some people have problems when coming out of hyperspace but I really couldn't think of a good fix that fitted with the rest of the game mechanics.

**Comment by endless-sky** [comment]
My impression from reading Steam threads is that the people who complain about being one-shotted by pirates are probably all just really bad pilots who don't know how to dodge, or else are vastly exaggerating how often it happens to them.

I just made a new pilot, bought a Star Barge, went to one of the more dangerous southern systems (Sargas), and took off from the planet 50 times to see how often I would die. Pirates were present probably about 25% of the time. Two times (4%) the pirates managed to disable me; the rest of the times I successfully fled. I was never outright destroyed; I could've bribed them or just waited for reinforcements to arrive.

To me it doesn't seem at all unreasonable if 4% of the time, a player who picked the slowest, most vulnerable ship and is hanging out in the most pirate-infested part of the galaxy gets disabled.

**Comment by tehhowch** [comment]
My caveats are 
1) The pilots may have missions which spawn pirates and they may have landed with those pirates in system. 
2) The pilots may have unsafely increased their cargo space.

These can both result extra and persistent pirates. Yes, these are directly attributed to players not knowing that mission X spawns pirates that will attack you, and that too much cargo = bad thing, but the blanket solution to "help i'm getting constantly killed by pirates" cannot be "abort all your missions" or "spend your money on Sparrows". The former because too many story missions get aborted already, and the latter because habitually-killed pilots are probably not doing too well in the money sense, so telling them to buy an easily vaporized Interceptor isn't exactly sound.

Beyond adding an attraction-level indicator discussed elsewhere, and the escape pod mechanic, I don't think there is much that can be done to save pilots from themselves, though.

**Comment by endless-sky** [comment]
The only missions available to beginning players that spawn pirates are escort missions. If you take one of those, you know from the mission description to expect pirates. And, you won't be offered one of those missions anyway unless you're either flying a Sparrow or have gained a combat rating.

And, it's literally impossible to boost a single Star Barge's cargo to the point where it would attract pirates - you'd have to install 7 cargo expansions, and a Star Barge only has 130 outfit space. The minimum a player would need to have to start attracting raids is 3 stock Star Barges, or 2 Star Barges with 2 cargo expansions each.

**Comment by endlesssteve** [comment]
@endless-sky . 
1  With all due respect you are not a very good subject for such tests.
You are a good pilot with lots of experience and a full knowledge of game mechanics and map.
A new player has none of these advantages.
2  The difference between disabled and destroyed is pure luck. Mainly down to what weapons the pirate ships have. So every 25 planets the best player in the game gets to live or die on the flip of a coin. How more often for a new player? How many times to you take off before you get your second ship?
3 If you guys have not implemented the escape pods in 2 years your not going to do it. Maybe look for a simpler way to at least reduce the problem. To be honest I'd rather we got new content and aliens rather than escape pods too.
4 Compared to the other great suff in the game this is pretty minor but some new players don't get through this to find the great stuff. They get wiped out 2 or 3 times and give up. 
5 If you honestly don't see this as a problem I'll close the issue.

**Comment by tehhowch** [comment]
For a game with no paid developers, in which every added piece of content has to be ultimately approved by a single person who has a full-time job and life, of which Endless Sky is only a hobby, saying "if you haven't done `X` in `Y` amount of time you're not going to do it" is incredibly rude.

This game engine's development is not about rushed deployment of new features. It's about deploying sensible and robust implementations and improvements of features that advance the game in accordance with MZ's vision. If you don't like MZ's vision, the green `Fork` button will let you develop in accordance with your own.

**Comment by endlesssteve** [comment]
@tehhowch . 
I'm very sorry I did not intend to be rude. My intention was to be realistic. I appreciate there are no paid developers and was trying to think of a simpler way of resolving the frustration that could be done quickly ( and possibly even by me.)

Thinking about all the comments on this I have a variation on the request to try and limit the work needed and impact on non new players.

Change the players starting ship to have a lower % of damage to the hull before being disabled but a higher total hull points.

advantages:
Other flagships are not changed.
No new graphics or game mechanics.
Player is still disabled with the same damage.
Player is not indestructible and can still die.
Reduces chances of death through pure bad luck as the hull should in most cases be able to absorb the remaining missiles/shots after the ship is disabled.

Work: 
3 new ship files needed.
The start of the game needs to be changed to use one of the new ships. ( may be this is also possible via a plugin?)

**Comment by endless-sky** [comment]
Admittedly it's been a few decades since the days when I played a lot of video games, but back then it was pretty much assumed that if you're playing a new game, you're going to die a lot at first until you get the hang of it. That was actually part of the fun of playing a new game, that you would see yourself gradually developing skill and learning the tricks of the game over time.

Endless Sky is patterned after a game from that era (Escape Velocity) and strives to give players that experience of feeling that the more they work at understanding the game or mastering the controls, the more it pays off for them. To me the worst sorts of games are the ones that are so mindless that you don't need to do that.

**Comment by endlesssteve** [comment]
Ok. It's not a bug it's a feature.

As promised I'll close the issue. ( though I still may make the plugin ; )  )

**Comment by tehhowch** [comment]
You should look into the "stronger hulls" mod, as it will probably result
in the tankiness you desire.


(Endless Sky = Dark Souls confirmed :rofl: )

**Comment by endlesssteve** [comment]
I'm afraid you really didn't understand the point of the request. A bit sad really.
I desire to make the game better and solve a problem that new players have reported and doesn't seem to be being dealt with.
Tanky I can do in 5 minutes with my save file. Add a few zeros, cut and paste what you want from the other data files etc.

I do however have one question you could help me with. Where is the code that sets the level at which a ship is disabled? There are a lot of .cpp files to look through.

Thanks

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/blob/760f4d932ffec88962f4b7bb599b752994970437/source/Ship.cpp#L2591

MinimumHull is the disable threshold.

**Comment by endlesssteve** [comment]
Is that a parameter in the ship file?

**Comment by Amazinite** [comment]
```
double maximumHull = attributes.Get("hull");
return max(.20 * maximumHull, min(.50 * maximumHull, 400.));
```
It's based off of the ship's hull.

**Comment by endlesssteve** [comment]
Mmm  don't quite see how that last line comes to the final figure.  but don't worry I can google it from here.

Thanks for the free C++ tutorial.

**Comment by endlesssteve** [comment]
I really am interested in the C++ syntax and I found that max and min are functions and after that it's pretty obvious. Now I can play with it.

**Comment by sivael** [comment]
What could be a good option is takeoff would be done in two stages - you go to the main map and before your ship appears from the planet you can monitor the surroundings. Basically "turn on sensors, keep within the atmosphere" Not available in missions that force you into the air.
Solves the issue in an immersive and simple way.
