### ISSUE TITLE
Custom Ship Creation Bug, probably

### ISSUE THREAD

**Issue by CruaverVoidDrake** [endless-sky/endless-sky#3078]
Simply put one of the ships I made is having trouble in the balancing issue. Simply put, it's immune from being hit, weapons pass right through it and enemy ships don't use energy weapons against them. This immunity seems to be a bug in the code since all my other custom ships don't seem to have this issue. I believe it happens when a ship has internal space, gaps that make the missiles think they missed whether it's at the center or on the sides.

**Comment by Amazinite** [comment]
The border around the ship's image isn't big enough, meaning that the game is unable to give it a collision mask and therefore it can not be hit.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/wiki/CollisionDetection

**Comment by CruaverVoidDrake** [comment]
Then how come the little icon in the center is showing a very clear border?

**Comment by CruaverVoidDrake** [comment]
![screen shot 2017-09-25 at 12 17 13 pm](https://user-images.githubusercontent.com/7862176/30826442-7ed99640-a1eb-11e7-80b5-8b25f8ef3977.png)
This is a screenshot of both the ships that can't be hit by projectiles and an alternative that is twice the size without the hole. Since both have a clear outline I do not understand what would cause the projectiles to not impact the sides.

**Comment by Amazinite** [comment]
Use this https://endless-sky.github.io/ship_builder.html
Put the image in.
Check the collision mask box.
If the red outline doesn't go the whole way around the ship then you need to increase the size of the image **border**, not the size of the image.

**Comment by CruaverVoidDrake** [comment]
I used that when building all my ships because turret placement sucks. But, I must admit I never used the collision mask box. Now that I do I see that the system found an erent pixel which it was putting all the collision around. Solves the whole issue by cleaning it up.
