### ISSUE TITLE
Idea: Upon damage, apply condition to ship

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#308]
When a ship experiences heavy or moderate damage, apply a status effect to the ship, i.e., a Bactrian is hit with multiple torpedoes, as a result, power to engines is reduced/becomes erratic, or shield matrices are damaged, so total shield charge reduces, etc.

**Comment by gchapyzh** [comment]
Some weapons already have effects like that, should not be hard to add them to torpedoes. But that effect should only happen when shields are down.

**Comment by airtroop392** [comment]
Yeah, I know some of the weapons in game have similar effects- but those are temporary, and last only a few moments- assuming you were damaged badly enough, you would have a chance of getting one of these status effects, and they would only be cleared once you repair yourself at dock.

**Comment by endless-sky** [comment]
There may be new damage types in the future that have an effect similar to this, but if your shields are down you're in big enough trouble anyway without also losing some of your ship's effectiveness as well.
