### ISSUE TITLE
Wormhole travel sends the flagship to the wrong coordinates

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3083]
The wormhole's position advances by one day when the player changes position, but the flagship's position is set by the previous spot of the wormhole.

To reproduce, turn a moon of a planet near the system center into a wormhole and enter the system via it.

**Comment by tehhowch** [comment]
The finnicky bit is that you can't currently write
`ship->Position() = object->Position()`
since the Position information is returned as a constant value - e.g. read-only:
https://github.com/endless-sky/endless-sky/blob/a5a5cfec95eb2623167a8e703533aba45cf2fd12/source/Body.cpp#L134-L138

Existing methods which modify a ship's position call a member function of that class (e.g. `Ship->Place( newPos ....)`), within which the privately kept variable (only the Ship class can manipulate it) is changed directly (rather than accessed publicly via `Position()`). Unfortunately, Ship->Place() does a host of additional things that are not desired in this use case:
https://github.com/endless-sky/endless-sky/blob/a5a5cfec95eb2623167a8e703533aba45cf2fd12/source/Ship.cpp#L539-L565

This suggests to me that the only way to fix this bug is to either:
1) add a StellarObject method that returns its position on the next day, 
gate the wormhole position update on if this ship is the player flagship
if so use the TomorrowPosition() method
else use the existing Position() method
2) add a Body method `SetPosition` and call this from Engine::EnterSystem()
3) add a boolean argument to Ship::Place that defaults to performing the extra bits, but allows not performing them, then call this method from Engine::EnterSystem()  

I'm choosing method 3.

**Comment by endless-sky** [comment]
Fixed by merging #3085.
