### ISSUE TITLE
Suggestion: dynamic economy for trade goods

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#309]
Currently, the sky's the limit when it comes to profits possible over a trade route: even ridiculous trade routes in which a million tons of luxury goods are transferred from one world to another every few days are possible. I think that each planet should have a maximum "reserve" of goods of each type, with a fixed quantity being produced for every day of game time. The production should be tied to the price of the good: If a lot of the good is available, the price should be low; if the good is in short supply, the price would be high.

This could be further tied into a consumption rate assigned to each world: Some worlds may produce zero food, for instance, but still consume 1,000 tons per day, these worlds would pay a lot for food as their reserves ran out.

I think this would be a nice natural way of introducing some basic market economics into the system, and introduces the ability to have "events" in which goods are suddenly created or destroyed on a world (for instance, a flood may wipe out half a planet's food supply and production). It might even be used to control the routes being used by the AI: if a lucrative route suddenly appears due to an event, the AI merchants would flock to those routes.

**Comment by gchapyzh** [comment]
No, you should rename this to 'Dynamic Economy'. Each planet has a certain consumption/production, certain stock, certain storage amount... the market changes constantly, with crashes and rises in prices, etc.

**Comment by Pointedstick** [comment]
I like this idea. In particular, to prevent abusing trade routes like this, perhaps every time the player makes a commodity sale, that would lower the price slightly. In effect, the player is helping equilibrate the price. Over time you'd have to find new trade routes.

**Comment by Oeleo** [comment]
I'm for this but it will lower the utility of trading when looting is so useful, so we need make looting harder/less lucrative before, because trading, after the "beginning part" become useful again when you have thousands of space available, so that's sad to remove the utility of trading knowing that this is alredy little lucrative.

**Comment by thenerdfreak** [comment]
I disagree. The entire point of trading routes is to make money, making it harder on merchants (HARDER THAN IT ALREADY IS LOL) would just be spitting on that idea. Let them play how they wanna play

**Comment by Pointedstick** [comment]
Being a merchant captain is **ridiculously** easy. An hour or two with a basic starting Star Barge and you'll have a paid off mortgage and a million credits in the bank.

Not that it needs to be made harder, of course. But more dynamism makes a game *interesting.*

**Comment by airtroop392** [comment]
I can concur with @Pointstick. At a certain point, merchant convoys become a better way to make a living than piracy- and if you have enough ships, you can earn millions of credits if you find a sweet and short route..

**Comment by gchapyzh** [comment]
With all honesty, I have never tried trading, except when I carry ~50 tons of some good if I have spare space. Otherwise I just disable and sell a few Navy ships to make a million or two.

**Comment by airtroop392** [comment]
Yeah, I was the same way for a <b><i>long</b><i> time. I would spend hours looting/boarding pirate ships down in the deep south to make a living, which was certainly more exciting (and at the same time, more frustrating and time consuming) than being a merchant mariner.

**Comment by Pointedstick** [comment]
Huh, do you start the game with a sparrow and disable pirate ships? I never managed to make that work because the sparrow is such a wimpy piece of crap against anything armed. Pretty much the only thing you could disable with it is an unarmed merchant ship. Interesting how differently people can play the same game.

**Comment by airtroop392** [comment]
Oh, no, I started off with a Shuttle, moved up to a Heavy Shuttle, then a Hauler, and then a Mule, which is when I went nuts with the piracy stuff. I can't even imagine anyone winning a 1v1 with the Sparrow, even against another Sparrow.

**Comment by Oeleo** [comment]
That's what I thought, maybe that the best ship to begin is the  shuttle, because you can have 6 crew, you just have to wait that someone disable a little pirate ship and BOOM 20 hours won

**Comment by thenerdfreak** [comment]
It takes you hours to be able to capture a pirate? it takes me 5 mins, just capture another small interceptor and sell it and you're set for the next tier

**Comment by Oeleo** [comment]
No it took me hours to won money while trading, I don't remember how many but that's really when I began to steal pirate ships that my money jumped, and even more when I discovered the old-school well known *reactor-farming*

**Comment by airtroop392** [comment]
It takes me hours to capture a <i>lot</i> of pirates. I normally like to hang around one of the unhabitable pirate sectors and disable 5-10, and then take them all at once. Repeat that for 20 hours in rapid succession.

**Comment by Oeleo** [comment]
So now you can try the *reactor-farming* but beware ! The game will suddenly seem easy...

**Comment by Pointedstick** [comment]
That's tracked in issue #227.

**Comment by gchapyzh** [comment]
I wish enemy fleets would respond in proportion to the threat you pose. If you attack a Republic world with five sparrows, the response wont be big, but if you come with ten heavy warships, all nearby fleets, and in need further ones away will warp to attack you.

**Comment by airtroop392** [comment]
Might be getting off topic here, I think the system is pretty great the way it is- larger, more significant planets have larger and more powerful defenses, whereas worlds which aren't nearly as important have almost no defense- can you imagine encountering a fleet the size of the one defending Earth in any of the Free Worlds sectors?

**Comment by thenerdfreak** [comment]
lol i crap you not, one of the pirate world's fleets is like four fury's and a splinter (i think, i was destroying them so fast that's all i had time to see before they surrendered

**Comment by Oeleo** [comment]
Yes because when you take tribute of planets there are a lot of ships which attack you, many more that what you can see the rest of the time, so it seems coherent that if you seem to be too dangerous they send you their reserve fleet.

**Comment by guillochon** [comment]
All: I have submitted a pull request for a system of dynamic trade: https://github.com/endless-sky/endless-sky/pull/330. You can read all the gory details in the pull request itself, but the short summary is that commodities are initially finite (although systems produce, consume, and trade them), and that prices adjust based upon the amount of commodity in a given system. Lots of food in your system? The price will be low. Shortage of medical supplies? The price will be high!

Let me know what you guys think. I'm interested to have people give it a try.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
