### ISSUE TITLE
Typo in drak dialouge when entering the nanobot system

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#3091]
After you go through a bit of dialouge it talks anout its voice and 3 words are missing spaces between them

Also there is a tribute battle missing in FW/republic space but I'm AFK and cannot remember the name of the system

**Comment by jafdy** [comment]
```
		conversation
			`A voice says, "This system is off limits. You should leave."`
			`	After a second, you realize that the voice did not come from your communications equipment. In fact, now that you think about it, you're not sure if it was an audible voice, or just something in your head.`
			choice
				`	(Ignore it.)`
				`	"Why should I leave?"`
					goto why
				`	"You can't tell me what to do."`
					goto why
			`	"You should leave." The thought repeats itself, insistently. Either you're going crazy, or a creature is communicating with you telepathically.`
			choice
				`	"Why should I leave?"`
				`	"You can't tell me what to do."`
			label why
			`	You feel as if a vast and patient creature has just heaved an immense sigh. "Human, you would do well not to ignore the warning of an Archon. I am here to warn off those who might be harmed by the swarm intelligence that infests this system. If you remain here long your ship will be digested by the swarm."`
			`	You recall that "Archon" is what Drak ships are called.`
			choice
				`	"What do you mean, 'digested'?"`
				`	"What is a 'swarm intelligence'?"`
					goto swarm
			`	"I mean that your ship will be broken down into its component parts." You notice, as the voice says this, that your shields are registering small energy bursts, as if they are being struck by invisible weapons.`
			`	"What is this swarm?" you ask.`
			label swarm
			`	"Self-replicating miniature robots," the voice replies. "A weapon created by the Korath, the last of their great abominations. If you wish to feed your ship to the swarm, I will not stop you, but they already possess enough raw material here without your assistance." The voice's tone, inasmuch as a disembodied imaginary voice can be said to have a tone, is sardonic.`
			choice
				`	"Okay, okay, I'll get out of here."`
					goto end
				`	"Wait, I have more questions."`
			`	"Yes?"`
			`	You ask, "Why don't you just destroy the swarm, if it is so dangerous?"`
			`	The voice says, "Because if the Korath manage to drive themselves extinct, this intelligence will be their last and greatest surviving creation, and we will preserve it as a living memorial to them. Please do not interfere here." When the voice speaks the phrase, "drive themselves extinct," the words are accompanied by an emotion that you cannot put a name to.`
			`	Also, the empty space around your ship is beginning to light up with small sparks, like an angry swarm of fireflies.`
			choice
				`	"Well, it's an honor to meet you. I'll be leaving now."`
					goto end
				`	"Why do you care if they go extinct?"`
			`	"Our directive is to enforce peace and prevent extinction," says the voice. As before, the words "prevent extinction" echo loud in your mind as if underlined by a nameless emotion. "Now, enough questions," says the voice.`
			label end
			`	The presence inside your head seems to fall away, and you are left talking to thin air.`
				decline
```
Where is it? Simply saying it's somewhere is not very useful. (You also misspelt "about".)

Tribute is filler content for late game players, nothing going to be added purely on your say-so.

**Comment by tehhowch** [comment]
I'm going to assume that you are talking about the word `inasmuch`.
Did you try looking it up?

PS: monks or other pacifists aren't going to respond to threats.

**Comment by KiLEdEnNis** [comment]
for future reference
if I see a word I don't know (or I think it has a typo), I google translate it, or look it up, so should you
I actually LIKE doing this; I learn new English words from Endless Sky; learning through a fun game is fun too

**Comment by Wrzlprnft** [comment]
Rant incoming. Hilariously exaggerated to actually transfer _my_ point.

Are you fucking kidding me?
This feels like a slap in the face of everybody working on this halfway seriously.
Of course, one can mistake this for just another forum to load of their bullshit, but most of them listen and learn. The issue tracker is supposed to be a cooked down, efficient board of errors and solutions, not a "oh **I** do this that don't know this so it must be a mistake".
Okay, i had to look up that word too. One could see that as a mistake, okay.
But god dammit _track down the exact spot_ so we can quickly asses the situation, we might not be able to track down the error like in this case.

So, rant end. i am not against you, and i appreciate your enthusiasm, but please try to adapt to the workflow so we can make something great with this game.

**Comment by KyroFirehammer** [comment]
Well I was planning on figuring it out and fixing it and yes I was talking about the "isasmuch" 
AND this is what I got 
in·as·much
ˌinəzˈməCH/Submit
adverb
to the extent that; insofar as.
"these provisions apply only in·as·much as trade between Member States is affected"
considering that; since (used to specify the respect in which a statement is true).
"it was not really a still life in·as·much as all the objects were in motion

If you really want get technical there should be hignphons in between them

You guys also need to calm down 
Let's say I was wrong on that, no now benefits from being yelled at for a simple misconception.
I am not an English professor, no ones going to die if there's a gammar error or just a simple mistake.

Also even if there are monks on the planet, other people would defend their world it logically makes sense for there to be a fight. There are many small moons and planetoids that are mining facilities that lore wise run by drones and they have tribute fights, a planet with a somewhat small population ,in comparison to the billions on earth and other large planets, would still want to defend themselves

**Comment by tehhowch** [comment]
My earlier response was a suggestion to, instead of assuming that a word you do not recognize is an error in the game, first perform some research on the word, phrase, or subject. If your research determines that the word, phrase, or subject does not exist, or the true usage of the word, phrase, or subject does not match the usage found in the game, only then should you raise an issue stating that there is a typo or other possible error. Research (especially for typos) generally means consulting a dictionary and not simply looking at Google's search summary:
![image](https://user-images.githubusercontent.com/20871346/31026029-6d3afdee-a50a-11e7-8c35-2360ce4fb172.png)

Merriam-Webster (literally the first search result) does not indicate hyphenation for `inasmuch as`:
https://www.merriam-webster.com/dictionary/inasmuch%20as
The lack of hyphenation is even evident without clicking the link to go to the website
____________
There is indeed a possible benefit here from correcting you: in order for you to learn from a mistake, you must recognize that it is a mistake. It is good that you recognize you are not an English professor - hopefully you will no longer automatically assume a word you do not know is wrong, and will instead look it up before instantly assuming it is not a word and thus is an error that needs addressing.
_____________
You should close this issue.

**Comment by Amazinite** [comment]
@ the tribute discussion: this is a duplicate issue of #1406

**Comment by Wrzlprnft** [comment]
> You guys also need to calm down
> Let's say I was wrong on that, no now benefits from being yelled at for a simple misconception.
> I am not an English professor, no ones going to die if there's a gammar error or just a simple mistake.

yeah, but that is **not** why i tried to yell at you. _it is the point that you made a post_, which contains an error where you did not even look up what or where it exactly was, nor if it actually is an error, and a duplicate post added to it.

there is no benefit for anyone when you keep spamming the issue tracker with pointless posts, being it not even halfway finished ideas or duplicates or not researched stuff like this.

the point of the github issue tracker is not to be a forum for every single detail, it is to be an efficient way of developing the game, bringing up issues and refined feature requests for actual argumentation and consideration.

for questions and discussions and smalltalk and helping to develop an idea, we prefer to stick to the other forums, or mainly discord, so the issue tracker does not get clouded with pointless things.

**short: github issue tracker is about facts.**

**Comment by jafdy** [comment]
Anyway, can you close this now?
