### ISSUE TITLE
Possible revised "health" calculation

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3092]
Current health system is very simplistic: `Health = Hull() + .5 * Shields()`
Hull() and Shields() are both 0 .. 1, meaning health is 0 .. 1.5.
The issue is that these functions and this representation do not convey how close a ship is to being destroyed, and if a ship has no shields, it starts with a health of 1, so the game thinks it is already rather damaged.

I propose the following:
1. a function which computes absolute pooled health:
```
 	// Calculate the absolute health of this ship, on a scale of 0 .. 1,
	// with the shield:hull importance ratio set by `shieldWeight`, default
	// 1:1. At 0, the ship is destroyed. At 1, the ship is undamaged.
	double Health(const Ship &ship, double shieldWeight = 1.)
	{
		double maxShields = shieldWeight * ship.Attributes().Get("shields");
		double maxHull = ship.Attributes().Get("hull");
		return (ship.Shields() * maxShields + ship.Hull() * maxHull)
				/ (maxShields + maxHull);
	}
```
This function is better - an undamaged ship always has health = 1, even if it doesn't have shields, but it still doesn't address awareness: if the ship has health = 0.5, is the next hit going to disable it? Or is it still quite far from the point at which it gets disabled?

2. a function which estimates the health at which a ship gets disabled:
```
	// Estimate the health at which this ship will become disabled, if it
	// takes damage in proportional with its current shield%-hull% ratio.
	// This accounts for direct hull damage effects rather than assuming
	// the shields will be ~0 before the hull takes damage.
	double DisabledHealth(const Ship &ship, double shieldWeight = 1.)
	{
		if(ship.IsDisabled())
			return Health(ship, shieldWeight);
		
		double maxShields = shieldWeight * ship.Attributes().Get("shields");
		double maxHull = ship.Attributes().Get("hull");
		// Estimated Health @ minHull =
		// (minHull + minHull * currentShields / currentHull) / (maxHull + maxShields)
		//  = minHull * (1 + currentShields / currentHull) / (maxHull + maxShields)
		double norm = 1. + (ship.Shields() * maxShields) / (ship.Hull() * maxHull);
		double minHealth = norm * ship.MinimumHull() / (maxHull + maxShields);
		
		return minHealth;
	}
```
A simple check would be to simply use the minimum hull and then divide by the total HP capacity, but this fails to be accurate if the ship exits combat and fully recharges its shield. Thus, I choose to use the current ratio of shield and hull, and scale that ratio by the hull value at which the ship is disabled.

3. To help with using these functions:
```
	// Calculate the relative health of this ship i.e. compare its health
	// against when it will become disabled. Returns negative if the ship
	// is already disabled (jumping to -.5 .. -.8, depending on size).
	double HealthRemaining(const Ship &ship, double shieldWeight = 1.)
	{
		if(ship.IsDisabled())
			return ship.Hull() - 1.;
		
		return Health(ship, shieldWeight) - DisabledHealth(ship, shieldWeight);
	}
```
This last function is what would be called by the AI class when making decisions, possibly with a check against the above Health(), since HealthRemaining will depend on the raw shield and hull attributes, both current and maximum. Example decisions:
"If this ship can take 25% more damage, it should keep fighting"
"This ship has only 10% usable health remaining! If it isn't heroic, it should flee!"

Using a shield weight of 1:
For an undamaged Shuttle, it has HealthRemaining = .5
For a Shuttle with 0 Shields and full Hull, it has Health = .55 and HealthRemaining = .27
For a Shuttle with full shields and 301 hull, it has Health = .72 and HealthRemaining = .0024
For an undamaged Bactrian, it has HealthRemaining = .8
For a Bactrian with 0 shields and full hull, it has Health = .33 and HealthRemaining = .26
For a Bactrian with full shields and 1721 hull, it has Health = .74 and HealthRemaining = .0004

Before I finalize a PR, I'd like to see if folks can find issues with the functions or common cases which are not adequately addressed.

**Comment by flaviojs** [comment]
Considering the example decisions, this looks overcomplicated.

HealthRemaining is what would be used to make the decisions, but it looks like it costs a lot... last time I checked floating point timings, divisions were the slowest and additions/subtractions were the fastest.
In floating point operations, for normal ships (has shields, has hull, is not disabled, can be disabled), I'm counting a total of 7 divisions, 7 multiplications, and 4 additions/subtractions.

I suggest moving HealthRemaining to Ship and simplifying it:
```
// How much health is available before the ship is disabled or dead,
// as a fraction between 0 and 1.
double Ship::RemainingHealth(bool toDisable)
{
	double maxHealth = attributes.Get("hull") + attributes.Get("shields");
	double minHealth = toDisable ? MinimumHull() : 0.;
	double health = hull + shields;
	return max(0., (health - minHealth) / (maxHealth - minHealth));
}
```
In floating point operations, this costs 1 division, 1 multiplication (0 if it's to die), and 4 additions/subtractions. If you still want to add shield:hull ratio it's 2 more multiplications.

**Comment by endlesssteve** [comment]
Silly question. Why should ships with no shields be a significant use case?
Also possibly ships with no shields would be a bit careful.

**Comment by jafdy** [comment]
To represent a faction that has not yet developed shields and instead use hull and hull repair.

**Comment by tehhowch** [comment]
In general I believe the behavior of a ship should not depend on how its hitpoints are distributed, but rather solely on its `personality`. Currently, ships with a large bias towards hull behave differently than ships without such bias, such as fleeing from battle after taking a single point of hull damage.

@flaviojs thanks for the feedback. I didn't elaborate extensively on the decisions that current health status can inform, partially because time, and partially because I feel it should inform many of a ship's decisions, especially when paired with certain `personality` traits.

**Comment by endless-sky** [comment]
I agree with @flaviojs that nearly all code would only end up using HealthRemaining(), so there's no need for the other functions. I also don't think any code would end up needing to know the health remaining until death, since once you're disabled you're as good as dead anyway.

My concern about combining hull and shields into a single fraction is that if a ship is taking disruption damage, it should flee even if its shields are relatively full. If hull and shields are combined, the weaker a ship's hull is compared to its shields, the more unconcerned it would be about hull damage.

How about something like this?

```
min(
    (shields + hull - minHull) / (maxShields + maxHull - minHull),
    (hull - minHull) / (maxHull - minHull))
```

That would mean that if a ship has a very weak hull and relies mostly on its shields, it'll begin thinking about fleeing before it even starts to take hull damage. And, a ship whose hull is near the disabled point will think about fleeing even if it has full shields. For a ship with minimal shields, the health calculation would be almost entirely based on hull.

**Comment by endless-sky** [comment]
The new Ship::Health() value uses the idea of "pooled health," but with the difference that it is measured relative to the disabled point, not the destroyed point. That avoids the issue where a ship can think it has a lot of health left when in fact it's close to disabled.
