### ISSUE TITLE
Drag-selecting escorts when being offered an in-flight conversation

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3093]
Moments before attempting to drag-select an escort, I assisted a Hai ship and was offered the job for helping a Hai ship. After exiting the conversation, the selection box that had been created before entering the conversation stuck on my screen until I attempted to drag-select escorts again.
![ei1nzbn5t0giy9o3ky6nyq](https://user-images.githubusercontent.com/17688683/31041084-cf4b86cc-a55d-11e7-8b54-62cae779853f.png)

**Comment by tehhowch** [comment]
Fixed in #3094
