### ISSUE TITLE
Reputation gain/loss after capturing a Republic world.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#3095]
Taking off from Tundra I had the following reps
"Free Worlds" 64153.46
Republic -3338.65
After taking New Boston
"Free Worlds" 55.55
Republic -3834.2
Losing about 500 rep from the Republic is reasonable, but losing 64,000 from the Free Worlds seems wrong.
I'm using the master file downloaded on Oct 1 at @ 1AM CST.

**Comment by tehhowch** [comment]
Tribute is an atrocity event. Atrocities make factions with a strong positive view of the offended faction (their attitude toward is >=.05) lose all regard for you (your rep resets to `min(0, current)`)

**Comment by Amazinite** [comment]
7675eb7

**Comment by VonZorch** [comment]
I should have mentioned it in my first post but this is in the Free Worlds storyline, during the shooting war phase.
Should the Free  Worlds really object to me taking the war to the Republic?

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/678

**Comment by Wrzlprnft** [comment]
i think the general point is that it's still capturing planets. which is only halfheartedly supported due to being a placeholder for ultra endgame content?

**Comment by ghoulavenger** [comment]
if you assume a campaign for tier 2, and tier 3 civilizations, then it is true, there is no ultra end game content yet (since wanderers campaign is an incomplete two part campaign at tier 2). But I think that the fighting drone fleets are far more difficult than dominating worlds and probably just as rewarding (not very). I suppose you could look at them as something for bored bloodthirsty players to do though.

**Comment by endless-sky** [comment]
New Boston is defended by a Militia fleet, not by the Navy. The Free Worlds don't approve of you killing Militia ships.

**Comment by KyroFirehammer** [comment]
Another point that needs to be addressed why are militia fleets used for planets such as ingot and new Boston where (if you take reconciliation) ate in republic control. If you capture a planet in the checkmate (I would  imagine you do in checkmate but I haven't played it yet) branch it should not determine what type of defence fleet that planet has if you did not choose that path.


Also, this is just an idea and I'm not even sure it's possible but,
A new feature where you start off with one planet (let's say Avalon for example) and you then could invade other systems and take them over, they then would have the faction changed to yours (Your oun personal faction) and possibly in the start planet unlock like a shipyard or something. 
Again it's just a random thought but it would be super cool.... (and if it's possible is totally be will it to help with it, but I'd it's impossible if if you guys hate it that's cool I have done 0 research on it [which i usially do before posing an idea]) :D

**Comment by Startome** [comment]
I've made a pretty solid concept for a total war mod. Will pursue it later

**Comment by PlanetLP** [comment]
…
this has been proposed often, and been shut down even more.

**Comment by tehhowch** [comment]
@KyroFirehammer https://www.google.com/search?q=militia

As for "capturing planets" that is 
1) unrelated to the issue of reputation change from tribute (this issue)
2) addressed in other issues already

**Comment by Startome** [comment]
It will be a plugin, not Pr ed. Let's get back on topic. Only said that to try and end that train of thought.

**Comment by KyroFirehammer** [comment]
Hmmmm..... a possible solution to the Navy/militia problem could be initialy start those planets as having a republuc defence fleet, then at a certain point in the campaign if the system is taken over by the Free Worlds then have the defence fleet changed to a militia.

(Also sorry for causing it to go off topic [but it could be a viable challenge with actual good rewards thus answering at least part of the problem, but it would be up to MZ decide......])

**Comment by Wrzlprnft** [comment]
Kyro, there is a difference between the free worlds government and local militia.

and the own faction thing is indeed a duplicate once more. short summary: no, this is not a strategy/business/simulation game. not a 4x game.

**Comment by KyroFirehammer** [comment]
Although that may be true, but the FW shouldn't become hostile for attacking something well into republic space. Another possible fix could be to have a " militia " tag for the ones that are in republic space that way the FW isn't mad at you for attacking a republic world (or just not as mad at you as they are if you attack one of their worlds)

Also it's fine if nobody likes the idea It was just a random thought that won't be pursued further.

**Comment by Amazinite** [comment]
Think of it this way; before the Free Worlds was the Free Worlds, it was a collection of militia defending southern worlds. They understand what it's like to be a militia defending a planet (mainly because in many ways they still are). In their eyes, you attacking a world defended by militia makes you a pirate, because it was pirates that did the same thing to their world when they were still militia.
The Free World's problem is with the Republic Parliament, and by extension the Navy since the Parliament has control over the Navy. Going out of your way to attack civilian targets (the militia are nothing more then armed civilians) is going to get you hated by everyone, even you own side.

**Comment by Lineth** [comment]
And dominating worlds is itself pretty piratical. It makes sense that if you're the kind of person to do that sort of thing the Free Worlds is not going to approve (as Amazinite said).

**Comment by ThrawnCA** [comment]
It seems like a double standard that the Free Worlds and Republic can violently capture planets back and forth from each other and still say, "Oh, they're good people, let's respect them and try to avoid hurting them while we're literally at war with them," but if the player simply muscles through to land and transact business without paying extortionate fees, on a world that they're *already officially at war with*, that is apparently an unconscionable act that even their own side will utterly disavow them for on the spot.

Seriously? A complete hostile takeover is acceptable and understandable, but simply demanding unrestricted landing rights and trade is beyond the pale? For *all* parties?

**Comment by ThrawnCA** [comment]
This was particularly jarring when I first encountered it, immediately after retaking Kornepheros, when the whole of Republic space turned red. So, I've literally just finished an exchange where each side thought it was fine to violently conquer a planet, with the specific stated motive for recapturing it being that the Free Worlds can't afford to have their movements restricted. And I've been given the Syndicate diplomacy mission, where it's been made clear that the Free Worlds still considers the Navy to be good people, to the point where even though they'll attack me on sight, Tomek would rather I avoided a fight.

And yet, when I then decide that I'm not okay with access to Republic worlds being restricted, and forcibly restore it, the Free Worlds immediately hate me. Even though I just finished doing something comparable to that, or even more comprehensive, at their direction. Which was the whole reason I lost that access in the first place. I've just finished tanking tens of thousands of reputation with the Republic for the sake of the Free Worlds' war, but as soon as I try to actually fight that war, they turn on me.

At that point it felt very much like they, not me, were the traitors.

**Comment by warp-core** [comment]
The Navy didn't actually take Kornephoros violently. We are told that they didn't even have to fire a shot.
Their attack on Sabik was, granted, less peaceful.
However, when you travel to meet the Syndicate, you are travelling through their space. It seems reasonable that Tomek is not interested in encouraging the Navy to conduct another large scale attack on the FW so he asks that you don't attack them. From their perspective, you are a rebel or terrorist. Why wouldn't they attack you in space they control?
Also, note that Navy ships entering FW space are attacked by FW ships.

**Comment by ThrawnCA** [comment]
> However, when you travel to meet the Syndicate, you are travelling through their space. It seems reasonable that Tomek is not interested in encouraging the Navy to conduct another large scale attack on the FW so he asks that you don't attack them.

Oh, I don't have a problem with Tomek encouraging non-violence. What I have a problem with is the fact that if the player then follows the example set by both sides, and conquers a planet held by the enemy, then both sides instantly hate the player.

If it were some kind of disciplinary action on the Free Worlds end for going outside orders, like the kind of thing that happens on the Checkmate branch, that would be much more understandable. But instant negative reputation and attacking the player on sight, just for aggressively prosecuting the war the player was hired for - that doesn't seem right.

**Comment by ThrawnCA** [comment]
Incidentally, the fact that some Republic worlds are guarded by Militia forces, others by Republic forces, makes the Free Worlds a bit schizophrenic if you set out to conquer them all. Every time you destroy Republic ships, your FW reputation climbs, but if you destroy Militia ships, it crashes again - but you don't get any indication in advance of which ships will defend a Republic world. So your FW reputation just goes up and down like a yoyo.

Perhaps Republic worlds should be considered acceptable targets during the war regardless of their defenders? Is it feasible for Free Worlds Militia and Republic Militia to be treated as separate factions?
