### ISSUE TITLE
Allow different personalities for a fleet's carried ships

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3098]
Currently, `fighters` is used solely to indicate the naming phrase for a fleet's carried ships.
I propose it is modified to support child nodes of its own, that allow setting specific personalities for carried ships in the group. These would override the fleet's personality if given, but only for the carried ships.

The current behavior means that fighters in a fleet have the same personality as the rest of the fleet, but generally a wildly different mobility set. This often means that the player shoots down any fighters long before the carrier ships and/or support escorts come into range.

To achieve more logical behavior (fighters stick near their parent ship until their parent ship is in combat), a mission-writer needs to use a separate NPC block containing only fighters, and give them the `timid` personality. For randomly placed NPCs, this cannot be done (as there is no way to tell one NPC block to use the same system chosen via LocationFilter for a different NPC block) except for origin and destination NPCs.

Current:
```
npc
    government Republic
    personality heroic
    fleet
        names "republic capital"
        variant
            Cruiser
npc
    government Republic
    personality timid
    fleet
        fighters "republic fighter"
        variant
            "Combat Drone" 4
```
Proposed
```
npc
    government Republic
    personality heroic
    fleet
        names "republic capital"
        fighters <name phrase is still supported>
            names <can also be here>
            personality timid
        variant
            Cruiser
            "Combat Drone" 4
```

Overriding the `fighters` token is one method. Does anyone have alternate methods of achieving this goal? Another method is to always make fighters `timid` (or perhaps each government has a specific carried ship personality, to allow some differentiation between organizations), but that would remove a creator's ability to tune ship behavior.

**Comment by toilethinges** [comment]
Is #1147 relevant at all? I can't tell what I meant by the edit, but it seems to me that this is what I was trying to say.

**Comment by tehhowch** [comment]
Indeed it is. Didn't see it when i searched for 'personality' and 'fighter personality'... thxs Github.

Closing as a duplicate of #1147
(will move my post there)
