### ISSUE TITLE
New space station image

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3103]
Don't have time to put together a PR right now, but I came across a CC image that seems like it would be perfect for a space station in Endless Sky: https://en.wikipedia.org/wiki/National_Ignition_Facility#/media/File:Preamplifier_at_the_National_Ignition_Facility.jpg

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Preamplifier_at_the_National_Ignition_Facility.jpg/1280px-Preamplifier_at_the_National_Ignition_Facility.jpg)

**Comment by endless-sky** [comment]
Usually I don't add images from a new author unless there are at least 2 or 3 from the same person. Otherwise, the credits list would very quickly get unwieldy...

**Comment by jafdy** [comment]
We do need more space station images . . .

**Comment by KiLEdEnNis** [comment]
"Usually"
make an exception then, this looks great

**Comment by Lineth** [comment]
Would fit perfectly with the Quarg imo.

**Comment by Pointedstick** [comment]
There's also a lot of cool stuff to pick through if you search for "Z Machine", too:

https://duckduckgo.com/?q=z+machine&t=canonical&iar=images&iax=1&ia=images&iai=http%3A%2F%2Fnews.utexas.edu%2Fsites%2Fnews.utexas.edu%2Ffiles%2Fknow%2Fimages%2F2012%2Fwhite_dwarf%2Fz_machine_painting_2.jpg
