### ISSUE TITLE
Start Conditions

### ISSUE THREAD

**Issue by Darcman99** [endless-sky/endless-sky#3109]
To my understanding, writing starting conditions does not support setting a ship to start with. I know the workaround is to simply start the user on a planet and supply them with enough credits to buy a ship, but what about if you want it to only be available once and that is the ship players start with. 

I have noticed a few members of the community working on the functionality for missions to supply the player with ships, that would be another possible solution. I'm sure content creators would appreciate this feature if they are perhaps making a(nother) cheater plugin, or the like.

**Comment by jafdy** [comment]
You can make an event that clears the planet of the ship as soon as they take off.

**Comment by Darcman99** [comment]
The feature i'm describing would benefit myself in my plugin as i would assume it would benefit others. Until that feature is implemented, which i'm confident won't be implemented in the long term, i'll use that alternative solution you suggested.

**Comment by endless-sky** [comment]
I've added support for this in ec54d19. If the start conditions give the player a ship, new games will start out on the planet instead of in the shipyard.

**Comment by tehhowch** [comment]
@Bladewood 
```
start ...
    ...
    ship "Sparrow" "Rusty Bucket"
```

**Comment by tehhowch** [comment]
@kikotheexile see above
ec54d1972802535c4d3cefd38c00102b1d72c7b0
