### ISSUE TITLE
Visit Conditions

### ISSUE THREAD

**Issue by Darcman99** [endless-sky/endless-sky#3110]
There are several missions that alter the save file to 'unvisit' a system on the map but there is no functionality to 'visit' a system though a mission, to be able to view the system on the map as though the player had been there before.

**Comment by KiLEdEnNis** [comment]
are you asking for this functionality or asking why it is like this?
unvisit is for if something big happens in a system, the player doesn't know what happened there (like the Pug invasion), which makes sense

**Comment by tehhowch** [comment]
A `visit` keyword would allow for events to convey more information about distant systems - perhaps the player is given surveillance data from one government about the territory of another.

**Comment by Amazinite** [comment]
My immediate thought for the use of a `visit` condition in game would be to `visit "Pug Iyik"` after a set amount of time in which the player has not yet found the hidden Pug system in Wanderer space when they are suppose to find out more about the Eye, as some people do not even think of looking around for a hidden system until they're given a hint on the Steam forums.

**Comment by tehhowch** [comment]
Fully supported as of #3118

**Comment by tehhowch** [comment]
@endless-sky the wiki page for CreatingEvents has no mention of either the new `visit`, or the older `unvisit` functionality. - it should probably get an update before 0.9.9 is released next year.

**Comment by mdsmestad** [comment]
@tehhowch Yes please

**Comment by tehhowch** [comment]
The events page references `visit/unvisit` as of Jan 2018, and I'll be updating it with a generic syntax example.
