### ISSUE TITLE
Orbits name area is too small

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3113]
#1714 is back:
 746bc21 reduced the amount of space in which the system and planet names can be printed, causing some planet and station names to overflow:
![image](https://user-images.githubusercontent.com/20871346/31471639-5bdf95f6-aeaf-11e7-9edc-2ae6c3853096.png)

Looks like the SVG asset used for the new orbit + key was the one from the original art and not the one from https://github.com/endless-sky/endless-sky/commit/67980b72c4758abcfd8f24cf4ea231d255c95456

**Comment by tehhowch** [comment]
As of 4c2396d209a63
![image](https://user-images.githubusercontent.com/20871346/31477521-06f96c38-aed2-11e7-8ead-38e584ccc9f7.png)

**Comment by endless-sky** [comment]
Fixed in 0c78ae0, leaving lots of extra space this time:

![sidebar](https://user-images.githubusercontent.com/11450262/31569383-9dc832f8-b048-11e7-8d9d-154c91138174.jpg)

I think I like it better than the awkward angled bump on the old one, anyway.

**Comment by tehhowch** [comment]
I concur, that is nicer yet
