### ISSUE TITLE
Station name capitalization in descriptions

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3126]
Huginn Station: `Huginn and Muninn stations, [...]`
Spaceport: `Huginn Station ...`

Muninn Station: `Muninn station, [...] and in addition Muninn station is [...]`

Leviathan Station: `Leviathan station [...]`

Arachne Station: `Arachne Station [...]`

Smuggler's Den: `Smuggler's Den was formerly known as Grendel Station, [...]`

Charybdis Station: `Charybdis station [...]`

Triton Station: `Triton Station ...`

Oberon Station: `Oberon station [...]`

Fenrir Station:  `Fenrir Station [...]`

Apparently, the rest of the (human) stations do not mention their full name at all.

**Comment by endless-sky** [comment]
Fixed by merging #3127.
