### ISSUE TITLE
planet "Pug Wormhole" is referred to, but never defined

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3137]
When I run endless-sky from the console I get:
```Warning: planet "Pug Wormhole" is referred to, but never defined.```

**Comment by Wrzlprnft** [comment]
#404

**Comment by tehhowch** [comment]
I don't get this message on my testing save, but I do get it on a new save that hasn't yet done the story.

**Comment by Amazinite** [comment]
It's because the wormhole exists in the Pug galaxy but nowhere else., so @Wrzlprnft, there's no way for the system to actually tell that it's a wormhole until it's actually linked to Deneb.

**Comment by tehhowch** [comment]
We could add a pug wormhole planet entry, and then a suitable cutoff for link distance that prevents drawing wormholes if their links are more than, say, 2 galaxys long

**Comment by tehhowch** [comment]
| Link | Distance |
|--|--:|
| Aescolanus - Cardea | 240.9 |
| Cardea - Terminus | 1746 |
| Cardea - Insitor | 142.5 |
| Coluber - Convector | 550.4 |
| Deneb - OtR | 27869 |
| Edusa - Peragenor | 421.2 |
| Insitor - Segesta | 395.1 |
| Sabriset - Sko-karak | 1529.8 |
| Segesta - Aescolanus | 303.5 |
| Ultima Thule - Waypoint | 764.7 |

I think the longest in-galaxy wormhole would be `Lone Cloud` to `Ka'pru`, at ~2180. So, 2500 would be a reasonable value (or smaller, if it is desired to not display some of these longer, in-galaxy wormholes.

**Comment by tehhowch** [comment]
The reason the warning doesn't appear once it is linked is because:
https://github.com/endless-sky/endless-sky/blob/ef0a6043001928244214fcf89e51c745c4c2c7e8/source/Planet.cpp#L196-L202
(e.g. when it exists only in `Over the Rainbow`, it doesn't meet the criteria for a wormhole - more than one system - so its name is empty. Once it is a wormhole, the name check returns ??? so it will pass the reference check even without a `planet` definition.

**Comment by tehhowch** [comment]
#3138 updates the check for planets - an undefined planet has no name and no system (e.g. typos in mission definitions or game events)
This keeps the ability to create a wormhole with no `planet` definition in order to keep it undrawn (e.g. #404)

**Comment by Wrzlprnft** [comment]
i could now say that my statement included tehhowch's solution, but i disn't think of that.

That said, i am against automatic draw or cut off of wormhole links.

**Comment by tehhowch** [comment]
With #3138 this is fixed, and the drawing control is handled separately.

So give all your planets true definitions., Even if they're just wormholes. If you want them to be drawn too, include `description ""`

**Comment by endless-sky** [comment]
Since the warning message was introduced after the 0.9.8 release (and thus is only present in code straight from GitHub), I'll go ahead and close this.
