### ISSUE TITLE
Offering ship category condition for assisting/boarding missions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3139]
Missions offered by assisting or boarding ships are currently only present in the form of the assisting missions that decline on offer. The amount of support for actually creating good assisting/boarding missions is lacking, #1663 and #2188 being examples of missing/broken features for such missions.

While brainstorming for possible assisting/boarding missions to create, an idea popped into my head: the ability to have assisting and boarding missions offer based off of the category of the ship you are assisting/boarding. For example, a boarding mission could exist in which a small pirate ship (interceptor or light warship) is used as a decoy, and upon boarding a large pirate fleet is triggered. On the opposite end of things, larger pirate ships (medium or heavy warships) may be carrying important cargo such as treasure maps or a large amount of credits which a smaller ship would likely not be carrying.

This, in addition to the system attributes mentioned in #526 and the above two mentioned issues, would allow for an interesting number of assisting/boarding missions to be created, and possibly even add variety to the current jobs by increasing the payout by the category of ship you saved (as the pilot of a Bulk Freighter will likely have more credits on hand to thank you with than that of a Star Barge).

**Comment by tehhowch** [comment]
#3005 should resolve #1663 and #2188 (one of the test missions that prove it does involves triggering hostile fleets when you board one of their faction :+1: )

It sounds like you are looking to extend the `source` tag so it could be something like
```
source
    government "Pirate"
    class "Heavy Warship" "Medium Warship"
on offer
    payment -100000
    conversation
        `As soon as you dock with the <origin>, your life support systems fail. Even though you pay the ship's captain <payment>, he refuses to deactivate the virus.`
            die
```
sounds good to me :+1: 


(regarding payment scale, you can do that simply, by using a different mission, once you have the source filter enhancement)
What you'll probably also want is to be able to set characteristics of the npc ship on which the mission spawns... but that's for a different issue.

**Comment by tehhowch** [comment]
#3140 should address this issue nicely, by adding support to filter on the ship's category, installed or carried outfits, and attributes.
