### ISSUE TITLE
System Attributes

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3143]
Like planet attributes.
Definable in the map

It makes sense to generate some automatic attributes though, based on the stellarobjects and planets it contains. I'm thinking
 - `"galactic phenomena"`
   - `>=4` stars, any wormhole sprite, or star has the `nova` or `wr` sprite
 - `"ternary star"`
 - `"binary star"`
 - `"no star"`
 - `"inhabited"` & `"uninhabited"`
 - `"high moon density"`
   - more than 4 moons per planet on average
 - `"high minable density"`
    - calculated by `total minable asteroids > 60`
 - `"nexus"`
   - System has 6 or more links to other systems
 - `"wormhole"`
   - the system has an accessible wormhole (which doesn't have to use the wormhole sprites)

What other automatic attributes make sense?

These automatic attributes, plus those of the planets it contains (so a system could be both wealthy and poor), plus those defined on the map, would be accessible to LocationFilters (to help make better missions without hard-coding destinations).
Refs #526

**Comment by MCOfficer** [comment]
> "no star"

??


i like it a lot, will fix quite some problems content creators stumbled upon.

**Comment by tehhowch** [comment]
Yeah, no reason to assume that a system has a star... Maybe it's a black hole :) that'd be interesting

**Comment by Amazinite** [comment]
`"high asteroid density"` > some amount of asteroids and minables
`"high planet density"` > some amount of planets

Those are the only two automatic attributes I can think of that I would think should be simple to do given that you've already done. 

Change nexus to >= 4 or 5 links? How many systems in game right now have >= 6 links?

**Comment by tehhowch** [comment]
Using map.txt systems only, and a regular expression `\d\n(\tlink [\"A-z '-\d]+\n){#}`:

| Minimum Links | Number of Systems |
|:---:|:---:|
| 1 | 344 |
| 2 | 262 |
| 3 | 186 | 
| 4 | 99 |
| 5 | 26 |
| 6 | 8 |
| 7 | 1 |

The base map's nexus systems, at 6+, would be
 - Sol Arach (7)
 - Alniyat
 - Gupta
 - Kaliptari
 - Lesath
 - Ruchbah
 - Similisti
 - Sol

After completing the main plot the numbers shift a little due to the addition of Deneb.

**Comment by Amazinite** [comment]
`crossroads` == or >= 4
`hub`== or >= 5
`nexus` >= 6
?

**Comment by tehhowch** [comment]
After Deneb links, considering all systems:

Minimum Links | Count Systems
:--: |:--:
0 | 377
1 | 367
2 | 276
3 | 194
4 | 105
5 | 30
6 | 9
7 | 1


Minimum Stars | Count Systems
:--: | :--:
0 | 377
1 | 377
2 | 126
3 | 1
4 | 1
5 | 0


Minimum Moons | Count Systems
:--: | :--:
0 | 377
1 | 311
2 | 219
3 | 159
4 | 87
5 | 40
6 | 12
7 | 4
8 | 0


Minimum Stations | Count Systems
:--: | :--:
0 | 377
1 | 45
2 | 2
3 | 0


Minimum Planets | Count Systems
:--: | :--:
0 | 377
1 | 377
2 | 376
3 | 373
4 | 338
5 | 170
6 | 26
10 | 7
13 | 5
18 | 4
29 | 3
36 | 2
52 | 1

The planet counts are distorted because of how ringworlds are made for the game to display them:
Quaru (52 planets), Ekuarik (36), Ki War Ek (29), Hevru Hai (18), Dokdobaru (13), and Enif & World's End (10). The rest of the base systems have at most 6 planet StellarObjects.


Minimum Moons / Planet | Count Systems
:--: | :--:
0 | 377
0.25 | 255
0.5 | 189
0.75 | 139
1 | 79
1.25 | 41
1.5 | 17
1.75 | 7
2 | 5
2.25 | 1
2.3 | 1
2.4 | 0
The 7 highest are (in descending order): Si'yak'ku, 11 Autumn Above, Lolami, Regulus, Alkaid, Alnilam, and Markarb.

I'll update #3144 based on this information shortly

**Comment by jafdy** [comment]
What about just testing against these conditions. So something like 
```
stars = 2
links <=3
```
would be a system with 2 stars and 1, 2, or 3 links.

**Comment by tehhowch** [comment]
Right now that wouldn't really work, as that's a ConditionSet and not a LocationFilter. It would certainly allow for more specific filtering capability, and is certainly something that would be possible to do (i.e. store a ConditionSet object in the LocationFilter):
```
waypoint
    conditions
        links <= 3
        stars == 2
    attributes north
    near Sol 100
```
Some care needs to be taken though, as a LocationFilter does not declare if it is for planets or systems - in general the same filter can and will get called to match to both types of location. So `conditions` may not be descriptive enough - there are conceivably some conditions that should not be applied to a system but should be to a planet, and vice versa.

**Comment by tehhowch** [comment]
Based on the histogram in 317b495a7217784bb490637564e1ff57e22c0193, I'm thinking "high luminosity" for systems in which the solar power is > 1.5, and "high solar wind" for systems in which the solar wind is > 1.5. Each should match to ~20-25% of the current systems (based on pure eyeballing).
Thoughts?

**Comment by endless-sky** [comment]
In e1c1a55 I've added support for system attributes, including the one auto-attribute that there's an indisputable need for ("uninhabited"). It might make sense to add more auto-attributes in the future, but I would rather add the bare minimum and then add more things as needed rather than getting locked into supporting a ton of auto-attributes in perpetuity.
