### ISSUE TITLE
Outfitter is broken

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3147]
Click on any outfit.
You'll get weird information, and some of it is missing entirely.
![whatthehelloutfitter1](https://user-images.githubusercontent.com/16506683/31854496-53bf7b32-b668-11e7-974d-1959cef5cfb7.png)
![whatthehelloutfitter2](https://user-images.githubusercontent.com/16506683/31854497-54fd54f6-b668-11e7-85cd-d4b74392a193.png)
![whatthehelloutfitter3](https://user-images.githubusercontent.com/16506683/31854499-56c3a7ae-b668-11e7-9a87-5879785648eb.png)

Think this is due to https://github.com/endless-sky/endless-sky/commit/595d2e8557489ae4549e42e3eb42a5ac7eecd04d, since it was working the commit before, and that one seems to be the most significant change.

Edit: huh, it looks like the broken outfitter text randomizes on startup or something.
Edit^2: tooltips don't work.

**Comment by tehhowch** [comment]
The first two columns are fine, but the 3rd panel is indeed goofed.

The problem occurs in OutfitInfoDisplay::UpdateAttributes
It is iterating over the result of `outfit.Attributes()` which is indeed a Dictionary object added in 595d2e8, and the iterator is `pair<const char *, double>`
For a Meteor Missile, one of the `it` values is:
![image](https://user-images.githubusercontent.com/20871346/31862800-9bba6090-b709-11e7-8130-f09538a41034.png)
The issue occurs when we reach line 195, and we combine this value with `':'` and then copy it into the attribute labels container (`vector<string>` type). This generally results in some very interesting text being accessed.

**Comment by tehhowch** [comment]
This should be ready for a milestone as it was fixed in #3150

**Comment by endless-sky** [comment]
Since the bug was introduced after the 0.9.8 release (and thus is only present in code straight from GitHub), I'll go ahead and close this.
