### ISSUE TITLE
Feature Request: Limited turret turning angle

### ISSUE THREAD

**Issue by 1010todd** [endless-sky/endless-sky#3148]
Hello, I would like to ask for a feature: limited turret turning angle, from the game a turret can turn and fire at any angle it wants but turrets shouldn't be firing at an angle like this V.(The part I circled in red)
![20171022182752_1](https://user-images.githubusercontent.com/19187937/31861469-ecfb6d20-b757-11e7-9415-3ad986f39962.jpg)
That part supposes to be higher than the mount as I see here.
![ice_screenshot_ -](https://user-images.githubusercontent.com/19187937/31861481-1cda8c60-b758-11e7-9bf8-90771c27b8fa.png)

My main problem isn't just the ones above, but I also want to make special turret mount that the turret shouldn't be facing this way
![weird_turret](https://user-images.githubusercontent.com/19187937/31861495-59ea83e4-b758-11e7-868c-bcb66198e5c7.png)
I wanted that gun to stay on the curved parts but don't go inside the hull.
This feature allows more variety of ship designs so that we could have ships with turret mount something like this!
![default](https://user-images.githubusercontent.com/19187937/31861508-a83f5448-b758-11e7-8766-b6070a8d06ee.jpg)
This will also allow players to use more pilot skills as they can attack enemy ship on a blind spot where less of the ship's turret can fire at!
I can already imagine more ship design that could use this feature to make them looks better we could even make ships that need to face their starboard against the enemy to be able to use their weapons more effectively similar to these warships!
![default](https://user-images.githubusercontent.com/19187937/31861555-83b5d0c4-b759-11e7-8846-8632ff0ec827.jpg)
![ijn_kitakami_torpedo_cruiser-49317](https://user-images.githubusercontent.com/19187937/31861605-92787ad4-b75a-11e7-9967-4c421da6a7f6.jpg)

From my idea the turret that are limited in firing angle would be like
`turret [x] [y] [first angle] [second angle]`
So typing in like this
`turret 2 8 0 90`
would result in turret that can only fire at this degree
![90degree](https://user-images.githubusercontent.com/19187937/31861981-8b3eb3fe-b760-11e7-8760-19bb03449d6a.png)
Here some example what it would be like using my idea of angle limiting.
![degree](https://user-images.githubusercontent.com/19187937/31861982-93663c5a-b760-11e7-8755-2368f77f9cc6.png)
So in the picture above I've also demonstrated what if only one number is defined after turret position numbers, it could be either any angle other than 0 to that number or from that number to 360/359.
So each ship would have their own firing angle defined, the ones that aren't limited don't have to define those numbers.

From this, firing angle would be limited if the specific turret hardpoint has the angle defined and if you move the turret to another mount it won't be limited anymore, so with this idea I think it won't need to change the engine as much as what people said in issue #3053 right?

Thanks!

**Comment by jafdy** [comment]
#3053 duplicate.
It would require a big change in the way the AI works.

**Comment by KiLEdEnNis** [comment]
from what I remember, this was gonna happen at some point, and if it is, it's just low priority (like a 1.0.0 milestone)

**Comment by jafdy** [comment]
or #2237 duplicate

**Comment by CodeDraken** [comment]
It would be a cool feature. Subcategories of ships would make the game more interesting
i.e 
* Heavy Warship
  - battleships / galleons - heavy weaponry on sides of ships
...

**Comment by Bladewood** [comment]
There probably won't be any explicit subcategories, beyond small mentions in ship descriptions.
https://github.com/endless-sky/endless-sky/issues/2166
