### ISSUE TITLE
[bug] turrets stop rotating when out of range(?)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#3149]
first of all, checked for duplicates and commits since I just run the latest Steam beta version, but I haven't seen any issue/commit that would have fixed this

basically how to "duplicate" it (and explains what happens):
- I have an escort hold position, and fire at it with turrets
- I basically fly right to it until I pass through it and it's behind me, then rotate back to the escort
- my turrets don't rotate, they just freeze and shoot at a certain direction, which I screenshotted

![temp5](https://user-images.githubusercontent.com/10348657/31862134-a247957e-b739-11e7-8e15-8ec536f40a2d.png)
I also recorded this bug on plays.tv (basically my only way to record something): http://plays.tv/video/59ec97a15cf63aeccb/endless-sky-turrets-freezing

as you can see, they basically shoot backwards, and I am 100% sure they aren't rotating at all
if I move closer, or basically stay close (not even sure)

again: latest Steam beta, I couldn't find anything that could have fixed it but I may have missed it

**Comment by endless-sky** [comment]
Does this only apply to shooting at your escorts?

**Comment by KiLEdEnNis** [comment]
no, it's a bit harder to test on AI ships, but when I shot a random Merchant Bulk Freighter and moved away a bit, the same issue happened

**Comment by endless-sky** [comment]
Are you using opportunistic firing, or focused? I still can't seem to duplicate this.

**Comment by KiLEdEnNis** [comment]
I'll look later today when I get home (in about... 8 hours), but I think focused (when I got swarmed by the Republic, my turrets still froze facing a certain direction)
when I know for sure I'll just edit it in this reply

**Comment by KiLEdEnNis** [comment]
focused fire, but opportunistic gives this too
since it can't be duplicated, I'll leave this open until next Steam update (if only I knew how to build from source)
if the next release "fixes" this for me I'll close it then

**Comment by tehhowch** [comment]
I've definitely seen this before, particularly when I was testing my ship list PR and had issued the board command for the current target, and was also holding the fire command - the ship would lock its turrets in a given direction (lasers too), even as the ship rotated to prepare for boarding. In that case it was with a hostile ship rather than an escort.

**Comment by KiLEdEnNis** [comment]
I think that's not the same bug:
yours happens with ALL turrets when boarding a (hostile?) ship, which makes me think here that turrets don't listen to commands while the ship is doing so
while mine happens with (currently only seen) non-lasers, maybe it's some targetting bug here; lasers just fire directly, projectiles have to calculate & predict

**Comment by KiLEdEnNis** [comment]
I just tried building from source after months and I finally succeeded, and thus could test if this bug was still happening

it turns out this bug still happens, in both focused and opportunistic firing modes, but I found some new info
beam turrets works fine for me, only projectile turrets causes this bug:
projectile turrets stop tracking their target out of range (they won't turn anymore), until you get back in range, while beam turrets keep tracking their targets even if ya move out of range

here's an example:
![temp16](https://user-images.githubusercontent.com/10348657/35772007-c9fbe1d4-0936-11e8-9266-a7ae12e3457d.png)

here I have:
a Sunbeam, Slicer, Disruptor and Banisher as beam weaponry
a Quad Blaster, Plasma, Bombardment and Proton Turret as projectile weaponry
all beam weapons keep tracking their target even if out of range, all projectile weapons stop tracking their target, when I move in, the longest-range turret starts tracking first, then 2nd longest etc. since I come closer

so short conclusion: only projectile weapons stop tracking their targets when out of range
ya did mention ya can't reproduce it though, and I remember ya said ya have no Windows 10 device, while I tested and experienced this all on Windows 10 only

I doubt the bug only occurs on certain Operating Systems, but could others test this?

**Comment by jostephd** [comment]
I can reproduce this on linux with current git.

1. Install a projectile turret in the flagship
2. Depart
3. Order escorts to hold position
4. Select an escort
5. Fly toward the escort, open fire
6. After passing the escort, steer the flagship 180 degrees so it faces the escort again. Keep firing.

After the 180, beam weapons rotate to fire toward the escort but projectile weapons are locked in the same direction relative to flagship, they are shooting over the flagship's stern.

**Comment by jostephd** [comment]
You don't even have to steer. Just fly towards the escort, and after you pass it keep flying in a straight line and keep your flagship pointed in the direction of flight. After you get out of range of the escort, the beam turrets will fire at the escort (over the flagship's stern) but the projectile turrets will be stuck in some intermediate angle, and will stay at that angle relative to the flagship even as the flagship steers.

**Comment by KiLEdEnNis** [comment]
also to clarify, this does not only happen to escorts that hold position, it also happens when enemy ships are out of range

**Comment by tehhowch** [comment]
Should be resolved with #3630
