### ISSUE TITLE
Steam Forum Post Deleted…

### ISSUE THREAD

**Issue by CruaverVoidDrake** [endless-sky/endless-sky#3154]
I don't know where I complain about this, but my very in depth mod of stargate ships in Endless Sky got deleted without my consent or notification. I wasn't even told it was being deleted, otherwise I would have fought to keep it or back it up.

So I want to know is, why was it deleted?
It was a perfectly good mod.

**Comment by CruaverVoidDrake** [comment]
Nvm, didn't even realize that it was a trade forum and things get deleted without a bump…

**Comment by tehhowch** [comment]
This isn't a GitHub issue. Very likely it was deleted by Steam itself, since that Mods forum is actually a bastardization of the trade forums

**Comment by jafdy** [comment]
Was it in the Mod subfourum?

**Comment by CruaverVoidDrake** [comment]
Ya, my own fault for not even knowing they get deleted automatically.

**Comment by jafdy** [comment]
This has got to be the shortest time an issue has been open for.
