### ISSUE TITLE
Planet->GetGovernment() crashes the game if the planet is not in a system

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3155]
Planets with spaceports that do not have a government set, and do not have a system set (for example, The Eye, pre-Wanderer story) will crash the game if they are reached in a LocationFilter test. Existing wormhole checks will fail for these systems since they are not yet wormholes (they have 1 or 0 systems, and `IsWormhole` checks if the planet is in multiple systems). They also escape the normal protections because they have been given a spaceport (to encourage their selection by NPCs making travel choices).

<details><summary>background</summary>

While testing some changes to ConditionSet on a new save, I would get occasional crashes upon landing. One occurred while I had gdb running the game, and so I was able to get the stacktrace:
![image](https://user-images.githubusercontent.com/20871346/31916762-eb78d0c4-b819-11e7-9508-01eb5cdfc2f3.png)
The particular mission being instantiated is `"Humanitarian 1,"` which has a fairly simple destination filter:
```
government "Pirate"
distance 2 10
```
Since there are no attribute restrictions, `LocationFilter::Matches` reached the government comparison, and attempted to use `nullptr`.
</details>

Possible fixes:
 - `Mission::PickPlanet()`: Add `!it.second.GetSystem()` to line 1078 or 1080
https://github.com/endless-sky/endless-sky/blob/fc785a18f37f3a1ac6a39bdd84d916d67268c4ba/source/Mission.cpp#L1075-L1084
 - `Planet::GetGovernment()`: Replace `GetSystem()->GetGovernment()` with `(GetSystem() ? GetSystem()->GetGovernment() : nullptr)`
https://github.com/endless-sky/endless-sky/blob/fc785a18f37f3a1ac6a39bdd84d916d67268c4ba/source/Planet.cpp#L327-L331

**Comment by endless-sky** [comment]
Fixed by merging #3157 and also making the other change in ccaee69 for good measure.
