### ISSUE TITLE
Source or Destination: near <government> filter

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3156]
Similar to the `near <system>` source and destination filter, only instead of a specific system that the source or destination must be a distance from, it is a specific government.
Example use case: a job or repeating mission which is designed to have a destination in FW space which is at most 2 systems away from a Republic system, but does not need changed due to the increase in FW territory over story events.

Additionally, should #3144 be added, perhaps `near <system attribute>` would be a useful source and destination filter as well.

**Comment by tehhowch** [comment]
As I mentioned on Discord, I don't think the `near` keyword is a good fit for this, as that will require complicating the LocationFilter::LoadChild method (requiring several new comparisons to the size of the DataNode, and if arguments are numeric)

Perhaps a better construct would be a keyword `neighbor`. One implementation could be:
 - only 1 argument is allowed
 - a match is any system for which at least one of the systems accessible by system->links has the argument as its government.
  - Note that this includes all non-isolated systems of the specified government, so to filter to only systems of different government that have a hyperspace border would require using a `not government <argument>` filter as well.

This construct could be abstracted to support
 - `neighbor government <government>`
 - `neighbor attribute <system attribute>`

Use of the keyword `not` with the above construct would match any system that has no links to a system with the specified government, and could include isolated systems of the named government (so combination with a `not government <argument>` filter is again recommended if the intent is to select only non-argument systems).

**Comment by tehhowch** [comment]
Even better might be to make `neighbor` load a nested LocationFilter that must be true for (or `not` true for each) neighbor. Then support for additional properties with the neighbor criteria is automatic.

**Comment by endless-sky** [comment]
This would make the location filters significantly more complicated, for very little benefit - you could get nearly the same effect by just making missions that have Republic sources, FW destinations, and a minimum and maximum distance between them.

**Comment by Amazinite** [comment]
The problem is that the jobs are suppose to have FW sources and destinations, but the destination needs to be near the Republic-FW border, which changes throughout the story, and the source of a job can not shift based off of conditions.

**Comment by tehhowch** [comment]
@endless-sky I don't particularly feel that neighbor matching is much more complex than the ability to specify what a system or planet must not be.
I applied the logic from the notFilter implementation in #3173, and if we are smart about the order of checking filters, we can avoid "expensive" checks bring done on many possible matches (i.e. first match based on qualities of the actual picked thing, like government or attributes or distance, then check the nested LocationFilters for `not`and `neighbor` compliance).

**Comment by endless-sky** [comment]
The "neighbor" filter provides a reasonable way of doing this.
