### ISSUE TITLE
cargo mission payment calc across a wormhole

### ISSUE THREAD

**Issue by jjhankins** [endless-sky/endless-sky#3163]
The payment calc for a cargo mission across a wormhole seems (based on my experiments) to be:

abs(base + multiplier * -1 * tons)

(or maybe it's only shown as positive via <payment>, and the actual payment is sometimes negative?)

I don't claim to know what the best solution for calculating jumps across a wormhole is, but -1 is pretty hard to work with from a mission-designing standpoint. The actual number of jumps in the path would be nice, but even 1 would be easier to work with than -1.

**Comment by tehhowch** [comment]
Set up waypoints on each end of the wormhole and you'll get a better result.
As it is, for non-traversable routes (jump drives or wormhole usage), the number of days required is returned as -1. This waypoint mechanic should give you 1 less than the true jump number, as the wormhole step will be -1 while the other 2 routes will indicate hyperspace lane usage.

The number of days in the route is used by the DistanceMap class to sort and select the best route, so lying and returning 1 is not possible.
We could, however, use an `abs` call when calculating payment.

**Comment by Amazinite** [comment]
Relavent: #1918

**Comment by jjhankins** [comment]
Setting waypoints doesn't work, at least not quite that way.

with `payment 20000 1000` (chosen to make the numbers easy) and waypoints on either side of the wormhole I've got a few missions:

8 tons x 4 days = 4k
22 tons x 6 days = 46k
22 tons x 5 days = 46k
12 tons x 6 days = 16k
7 tons x 6 days = 1k

I haven't figure out from that exactly what calculation is happening, but it's not what you suggest.

**Comment by jjhankins** [comment]
I'm especially confused how the same tonnage but two different distances were given the same payout.

**Comment by tehhowch** [comment]
You can determine the exact payment by inspecting the save file.
Route payment is source ton(closest waypoint-stopover) to (next closest ...) to ... to destination. If you have out-and-back across a wormhole then you're indeed going to get some fun math when adding waypoints and stopovers too

**Comment by jjhankins** [comment]
All those examples were from the same originating system, so the only variable was the distance on the other side of the wormhole. I tried it again, setting the cargo amount and duplicating the mission, and got six versions of the mission all with the same cargo and payment amount, but different destinations. So I have no idea what's going on. If I do this mission I'll need to make it a flat rate, at least for now.

**Comment by NomadicVolcano** [comment]
Please try #5085 and see if it solves your problem. It adds a `"use wormholes"` attribute to missions, which will enable wormholes in distance calculations for stopovers, waypoints, payments, and destination.
