### ISSUE TITLE
Question: What do the colors on the map represent?

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#317]
When I go into the Shipyard or Outfitters tabs and I select an item I want to look for, there are more than 3 shades of status indicators (orange, blue, and light blue). What does the third shade represent, if orange and blue represent have in stock/does not have in stock? Is that supposed to represent the industrial/technological state of that system?

**Comment by Pointedstick** [comment]
Blue appears to be "no outfitter/shipyard." Turquoise is "there's an outfitter/shipyard here." And orange is "this planet sells the thing you currently have selected."

It could be a bit clearer, I agree. A dynamic map legend might help new players make sense of what all the map colors mean.

**Comment by airtroop392** [comment]
Looking back, I can see that this was addressed in #288. That's all, I guess- this has been identified as a problem and my question has been answered. Thanks!
