### ISSUE TITLE
Out of character jobs

### ISSUE THREAD

**Issue by Bartthetroll** [endless-sky/endless-sky#3170]
When on Pilot in the Elnath system, which is the testing planet for Lovelace Labs, am getting missions to transport farmers and mill-workers, which is out of character for the planet. While I am not disputing the fact that in some universe somehow some farmers or mill workers were working on a planet owned by an arms producer devoted to perfecting weapons systems, it just doesn't make much sense. Not sure of potential fixes, maybe creating classes of planets with jobs offered dependent upon class.

**Comment by Bartthetroll** [comment]
Also getting a job to rush deliver pineapples from Farpoint

**Comment by Amazinite** [comment]
The delivery of pineapples from Farpoint has no reasonable work around. Pineapples is being pulled from the list of food from commodities.txt, and delivery jobs are available on all non-pirate human planets.

As for the farmers and mill-workers, those missions say that the family is looking to find work on `<destination>`, not that they were working on the origin planet. Additionally, the description for Pilot states that the planet is used by Lovelace for weapons testing, but that does not mean that the entire planet is used for this purpose, and there are undoubtedly inhabited regions of the planet far from the spaceport and weapons testing region owned by Lovelace that may very likely have farms and mills.
