### ISSUE TITLE
Github code structure.

### ISSUE THREAD

**Issue by louis123456** [endless-sky/endless-sky#3178]
I have a suggestion to organize the Github code a bit more. Why don't you create a 'next' branch for the future version (eg. 1.0 or keep it master) and one for the current version on steam.

**Comment by Amazinite** [comment]
Unnecessary; Github already saves previous versions. Go to [releases](https://github.com/endless-sky/endless-sky/releases), and on the left side below the version tag there's a [commit hash](https://github.com/endless-sky/endless-sky/commit/97c1fae2e1a9ecec2d14cf44b34101f37e763b05). If you click that, there's a button on the top right that says [browse files](https://github.com/endless-sky/endless-sky/tree/97c1fae2e1a9ecec2d14cf44b34101f37e763b05), which leads you to a version of the repository at that commit (i.e. at that release).

**Comment by tehhowch** [comment]
The churn here is not so great that tracking development would require many branches. As a 1 dev environment, there are not many different tasks being simultaneously pursued such that multiple central branches are required beyond those used in the pr system.

In the early development, multiple branches we're used. As the game has matured, those needs have diminished.
