### ISSUE TITLE
Espionage mission after "missing" the initial scan

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3179]
I picked up an espionage mission while doing other missions, probably because it was in the path to my final destination:

```
mission "Corporate espionage"
	name "Corporate espionage"
	description "The Serenity Empress is about to enter this system. Locate it and make detailed scans of its cargo, which are of considerable interest to a team of Syndicate researchers on Bluestone in the Bellatrix system; proceed there for 50,000 credits after retrieving the data."
	job
	repeat 0
	to offer
		random < 10
	destination Bluestone
	npc
		succeed 2
		government Merchant
		personality
			confusion 10
			entering
			fleeing
			target
			uninterested
		dialog
			"You manage to make the requested scans of the Serenity Empress's cargo. Time to head to Bluestone."
		ship Bounder
			name "Serenity Empress"
			sprite ship/bounder
			attributes
				category Transport
				cost 1140000
				bunks 17
				"cargo space" 40
				drag 3.7
				"engine capacity" 110
				"fuel capacity" 900
				"heat dissipation" 0.8
				hull 700
				mass 130
				"outfit space" 220
				"required crew" 1
				shields 2200
				"turret mounts" 2
				"weapon capacity" 50
			outfits
				Hyperdrive
				"LP036a Battery Pack"
				"D14-RN Shield Generator"
				"X3700 Ion Thruster"
				"X3200 Ion Steering"
				"nGVF-CC Fuel Cell"
				"Blaster Turret" 2
			cargo
				commodities
					"Heavy Metals" 4
					Industrial 2
					Medical 34
			crew 4
			fuel 900
			shields 2200
			hull 700
			position 1360.243 213.6807
			engine -12 44 1
			engine 12 44 1
			turret -37 4 "Blaster Turret"
			turret 37 4 "Blaster Turret"
			explode "tiny explosion" 10
			explode "small explosion" 20
			explode "medium explosion" 15
			"final explode" "final explosion small" 1
			system Vindemiatrix
	on complete
		dialog
			`You transmit your scans and receive a hearty congratulations, as well as 50,000 credits. "This will save us months!" you hear someone say in the background as you close the audio link.`
		payment 50000
```

I have no idea what "this system" was and there is no other indication in the map, so I went to Bellatrix system (destination) and waited for the ship there, eventually giving up.
I inspected the save file while doing other missions and the ship appears to be jumping and landing randomly.

**What should happen after the player "misses" the initial scan?** 

Option 1: show a map indicator in the system the target ship is in

Option 2: make the ship repeat a fixed route (between planet A and planet B)

Option 3 (by @tehhowch): fail the mission when the ship lands

**Comment by tehhowch** [comment]
With features from #2990, corporate espionage missions would be failed when the target ship lands (and it would also spend a little extra time in its waypoint systems so it isn't such a ridiculously difficult job).
Corporate espionage also led me to make #2658

**Comment by Bladewood** [comment]
"this system" refers to the system in which the job was offered.

**Comment by tehhowch** [comment]
@Bladewood indeed it does, but after that first launch, it's easy to lose track of which system "this system" is. But given how `fleeing uninterested` works, knowing the system that this offered in won't matter at all - the NPC goes on a mostly-random walk and can end up anywhere.

**Comment by tehhowch** [comment]
With #2990 the npc block of a "fixed" Corporate Espionage mission would be something like:
```
npc "scan cargo"
    government Merchant
    personality fleeing uninterested entering target
    waypoint
        1st
            distance 1 1
        2nd
            distance 2 2
        3rd
            not government Syndicate
            distance 5
    fleet
        names "civilian"
        variant
            "Scout"
        variant
            "Bounder"
    dialog "You manage to make the requested scans of the <npc>'s cargo before it lands. Time to head to <planet>."
```
The above would make the scan target have 3 randomly chosen waypoints - the first being a neighbor system of the mission origin, the 2nd being 2 jumps from the 1st waypoint, and the final waypoint being up to 5 jumps from the 2nd waypoint, and of any non-Syndicate government. While the ship has unvisited waypoints, it won't land permanently. Once it has visited all its waypoints (and surveyed each of them), then its next landing will fail the mission (unless the player has scanned it by then).

**Comment by daerogami** [comment]
> "this system" refers to the system in which the job was offered.

How do I find out what system this is if I forgot where I picked it up? It's only showing the 'turn-in' destination.

**Comment by Amazinite** [comment]
In #7141, these jobs were given a deadline so that if you miss the ship, the job will eventually fail itself.
