### ISSUE TITLE
A button to choice a way without jump driving

### ISSUE THREAD

**Issue by Oeleo** [endless-sky/endless-sky#318]
When you don't have jump drive device on all your ships,  or when you're escorted someone, you can't go to a point A to a point B following a road with an hyperdrive if your flagship has a jumpdrive (it will automatically choose the jumpdrive road). If there was a way, for example that when you press shit on your map you can choose a way following the hyperdrive when you have a jump drive device it will be helpful. Because now you have to go to the map all the 1 or 2 planets to don't take shorcut, and lose the rest of your fleet or the ships that you escort.

**Comment by thenerdfreak** [comment]
Just hang around the planet you wanna land on, the ships will actually get there faster than if you were following them, and since the recent update, they'll even refuel on the way

**Comment by Oeleo** [comment]
Oh yes they will but that's just some sort of RP or I don't know why but I prefer to follow them step by step, for exemple when you're ecorting a ship I found that a bit "cheaty" to make that because the pirates don't attack them if you're not on the same system. And when you go somewhere for a battle which begin when you enter on the system it would be useful to.

**Comment by Oeleo** [comment]
And it would not be a real problem if the way chosen with the jump drive took not shorcut often without reason.
![2015-11-29_00001](https://cloud.githubusercontent.com/assets/15967612/11455663/d6d4ef0a-9669-11e5-8818-43dc7f25616d.jpg)
![2015-11-29_00002](https://cloud.githubusercontent.com/assets/15967612/11455664/d763584e-9669-11e5-8544-219dc1a356ed.jpg)

**Comment by endless-sky** [comment]
Pressing Shift on the map to select a jump route manually already works.

**Comment by Oeleo** [comment]
Yes I can use it to do this system by system faster, well that's enough, I didn't know it worked.
 Thank you !

**Comment by airtroop392** [comment]
Close issue?

**Comment by Oeleo** [comment]
I consider that it is the admin who can choose if an issue needs to be closed or not, but it seems to work differently on this forum so... yes.

**Comment by endless-sky** [comment]
If you're the original poster of an issue, usually you mark it closed once you're satisfied that it really is resolved, rather than having the "admin" decide unilaterally that your issue was resolved when you don't really think it has been.

For actual bug reports, I also tend to leave the issue open until the next release has gone public, so that anyone who has the same issue will find the existing thread rather than starting a new one.

**Comment by Oeleo** [comment]
Ok I respect that, as I said that's just unusual for me, but I suppose that the freedom that we have here is because there are no problem yet with this system, which is a good thing :+1:.
