### ISSUE TITLE
This game is awesome!!!! Any chances for an Xbox One version for my kids?

### ISSUE THREAD

**Issue by andreaspada** [endless-sky/endless-sky#3181]
Title is pretty self explanatory: this game is simply awesome. It's a joy to play with, and both my kids - 11 and 6 years old - love to play it, with or without me around.
Is it possible, and feasible, to dream for an Xbox One version? They play most on the console, as they still are too young to have their pc, which I and my wife works on, so not much spare time available...

I'll happily pay for that, or I'll back an initiative for that.

Congratulations for the awesome game!

**Comment by tehhowch** [comment]
Endless Sky is a 1-(unpaid)-dev, hobby-time-only production. I don't think anyone in the community has looked into the requirements for a console port (though some have looked at a mobile port in the past).

There's a lot of work involved in any sort of port, so I wouldn't expect anything in any kind of sense of the word "soon". In my opinion, the game will need to reach 1.0 (easily 1-2+ years away) yet before ports are even considered.

That said, anyone in the world is welcome to develop a port that works with consoles, subject (of course :smile: ) to the code license and art licenses.

**Comment by Amazinite** [comment]
>I'll happily pay for that, or I'll back an initiative for that.

About that:

>The short answer is, I'm trying not to blur the line between Endless Sky just being a rather time-consuming hobby, versus it being a second job. That's important both because my contract for my day job (as a computer programmer) doesn't allow me to have a second paid job on the side, and for tax reasons as well if the donations were large enough.
>
>The other answer is that honestly, my day job pays quite well and I'm not really in need of more income - in fact, I usually give away about 30-40% of my salary as a way of reducing my taxable income for purposes of legalized tax resistance. So, people "donating" by creating game content or tracking down bugs is much more useful than donations of money.

That's a quote from the dev on gaining money of any source from Endless Sky.

**Comment by jafdy** [comment]
Consoles have a strict quality check before you can get a game on a console. They test them to ensure they are bug free and run to the expected standered on the console. While that obviously isn't going to be a problem, the issue is that they expect a finished game (we are still developing) and they expect the developer to pay for the test. And then there is production and distribution of the game, that is not a cheep endeavor as disk can only be manufactured in bulk.
It is not as simple as someone saying "Hey, lets put this on console!". If you want to back a console port then good for you but expect it to cost you in time effort and large sums of money.

**Comment by andreaspada** [comment]
@tehhowch, thanks for your clear reply. I understand that the game is still under development, and possibly not mature enough for a console port - although, I'm not convinced in regard...

The main reason to think in a xbox one port is that there's a tremendous lack for games like Endless Sky. The contemporary game industry is quite boring, there are many similar games, but there are almost no old school games out there. Such "old school" games are refreshingly, and very educative for young players.

@Amazinite, thanks for your reply too. To me, which I live in a very poor and problematic country - although I'm Italian, I'm living in Brazil - the idea that there's someone which earn too much, and which have to donate a considerable amount of its earn to not be charged too much in taxes, sounds like a very crazy science fiction film. I would love to live in such planet, and I'm sure almost every real-life human I know would love too. Anyway, it's great to know that the future of this game is not constrained by money issues, at least not directly... 

@jafdy, I totally understand what you mean. As I wrote to @tehhowch, I feel that there's a lack of such interesting and refreshingly games in the console world. In a strictly educative, pedagogy view, I would personally support a port for xbox one just to provide young players means to play in a relaxed and interesting environment, such as Endless Sky. I personally do not have any means to do it by myself, unfortunately but, if someone think that it's something worth investing some time, I'll be one of the guy which will try to help. I can translate in four languages, for example, and being a musician and composer, I could work on soundtracks and sound effect. I saw that is not too hard to write content and new storylines, so this is something I could do too.
Not alone, however.

But guys, thank you all for your fast reply! I truly admire and respect the work already done on Endless Sky! 

See you around Exodus...

**Comment by KiLEdEnNis** [comment]
> the idea that there's someone which earn too much, and which have to donate a considerable amount of its earn to not be charged too much in taxes, sounds like a very crazy science fiction film.

in rich countries ya earn more, but stuff costs more & ya get drowned in all kinds of taxes, it's not as good as it sounds

anyway, I think the question got answered: there's no plan to create an Xbox One version in the near-future, perhaps one day Endless Sky may appear on such platforms though, who knows

and feel free to help the game out if you'd like:
- coding improvements (like Tehhowch does a lot)
- editing (missions, stories etc.)
- graphics (better images for something)
- even sound effects

or make your own plugin (big or small, as long as the quality is good it doesn't matter)

**Comment by andreaspada** [comment]
@KiLEdEnNis , just to let you know: in rich countries stuff DO NOT cost more. It's the contrary. Our currency is a mess, whatever happen in the world is sufficient to drop its value. We simply do not earn as good as richest country and we have to spend much more money for the very same thing.
And, in regard taxes, I'm sorry but I have to say that you are wrong again: here in Brazil, for example, we have 60% custom duty on importation (which you have to pay on the price on the object you are importing as well as on the shipment fee, which can be quite high). And it's not just that: you have to pay also 13% ICMS (something like the VAT), both on shipment AND object price, plus many other internal taxes, for a total of 100% to 120% applied taxes on your goods. Sounds good to you?

We have many taxes applied on earned income, of course. And, if you think that we have some return on those taxes, no we haven't. We have NO public education - usable, I mean - NO public health, NO safety policies at all and ANYTHING like properly maintenance and cleanness on street, cities and so on...

So, I feel perfectly right to express my admiration in regard such a different reality.

But, yes, I'll continue to enjoy Endless Sky as it's current is. And, possibly, I'll help in extending in somewhat.

All the best!

**Comment by jafdy** [comment]
If you are clever you might be able to build/buy a simple PC that can plug into a TV. If you use sufficiently old parts it should be possible to get below £150. I have no idea what that will come to for you after tax, but it is food for thought.

**Comment by endlesssteve** [comment]
Why not get a used PC/laptop and put Ubuntu on it? Many people are using this and the installation is well documented. 
You should be able to avoid the tax and save some perfectly good hardware from the scrap heap.

**Comment by Nechochwen-D** [comment]
You can use your Xbox controller with Steam.

**Comment by Amazinite** [comment]
@endlesssteve @Nechochwen-D 

>as they still are too young to have their pc, ***which I and my wife works on,*** so not much spare time available...

**Comment by endlesssteve** [comment]
@Amazinite 
Incase I was not clear.  Get an old pc/laptop and install Ubuntu. This is cheaper than building from new parts. ( possibly even free). This is a variation of the suggestion from jafdy. My 8year old has been using an old XP laptop without internet as a kind of games machine for several years.
@andreaspada 
Both Ubuntu and the endless-sky for Ubuntu set up are well documented in the web and it is not at all difficult. ( I even find it fun but I'm a bit weird!)
