### ISSUE TITLE
Bug: Carried ships can only launch once per game load

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3183]
Pretty sure this is a result of the change to ship removal, but haven't run the gamut tracing it yet:

To reproduce:
1) Take off from a planet
2) Deploy fightercraft
3) Recall fightercraft
4) Deploy again.

The 2nd launch results in a bunch of invisible fighters that are unable to return to the carrier. This persists until the game is loaded again - it is not fixed by landing and launching, or by jumping.
In action: https://youtu.be/JLxoGypxNc8

**Comment by tehhowch** [comment]
git bisect testing confirms that ef0a604 was the start of this bug.

**Comment by tehhowch** [comment]
Fixed in #3184 by setting the `shouldBeRemoved` Body variable to false when launching a ship.

**Comment by endless-sky** [comment]
Fixed by merging #3184.
