### ISSUE TITLE
Debris sprites

### ISSUE THREAD

**Issue by Brick63** [endless-sky/endless-sky#3190]
I am designing ship Debris and was wondering if the idea would be to have Each ship have its own unique sprites or if generic ones would be better
currently im doing the unique for each ship approach and would like some clarity before getting too far into it
this is what I've done for the cruiser 
![cruiserdebrisfull](https://user-images.githubusercontent.com/32852156/32303200-84b51818-bf3d-11e7-9e6a-0eab2f39bc02.png)
as you can tell this will be very time consuming to do i have ~10 ships done so i would like clarity whenever is possible

**Comment by Amazinite** [comment]
Relevant: #990

**Comment by Brick63** [comment]
![skylarkdebrisfull](https://user-images.githubusercontent.com/32852156/32303986-78e8f2ac-bf42-11e7-9e22-5b611e41165d.png)
![saryd sojournerdebrisfull](https://user-images.githubusercontent.com/32852156/32303991-7cee7d54-bf42-11e7-8f36-161061fbfc32.png)
![kimek spiredebrisfull](https://user-images.githubusercontent.com/32852156/32303998-87727ff0-bf42-11e7-9d98-7d38c562fd50.png)
![hurricanedebrisfull](https://user-images.githubusercontent.com/32852156/32304005-8c90ae80-bf42-11e7-8349-25e45e0c6ede.png)
![heliarch punisherdebrisfull](https://user-images.githubusercontent.com/32852156/32304022-97aa4a6a-bf42-11e7-8616-a1279098cc93.png)
![arach hulkdebrisfull](https://user-images.githubusercontent.com/32852156/32304027-9bc04a32-bf42-11e7-93ed-232caa8ed2f3.png)
![berserkerdebrisfull](https://user-images.githubusercontent.com/32852156/32304031-a06f0a28-bf42-11e7-86b5-4e164068ba16.png)

**Comment by Brick63** [comment]
the ones i have made full pictures for

**Comment by endless-sky** [comment]
One basic principle of the game is to make the barrier for creating new content as low as possible. If every person creating a new ship also had to create sprites for that ship being destroyed, it would make adding new ships a whole lot harder.

On top of that, having ships always break apart in exactly the same way would end up looking tacky very quickly.

Early on, I experimented with having bits of flaming debris come out of exploding ships, but couldn't come up with anything that didn't look tacky. It's hard to be sure without seeing these sprites in action, but I suspect they'd suffer from the same problem.

**Comment by Brick63** [comment]
yeah that is one thing ive been told, ill experiment with some generic race debris in the morning and see if i can do a large enough group of each to keep it interesting allowing for creators to use the premade pools for each race

**Comment by tehhowch** [comment]
The thought was to give varied angles, offsets, and spins to the debris sections in the final explosion. Each debris piece would be a separate sprite, with the sprite's filename having a padded angle at the end, just before the blending mode specifier. 
Based on the angle associated with the sprite, a small random offset from the ship's center would be used to place the effect. A random noise angle would be added to this "encoded" angle, and then based on some properties of the ship (mass, weapon hitforce, etc) and the sprite (radius, height to width ratio, etc), a sensible velocity magnitude can be randomly chosen, along with a spin rate. If a lot of debris sprites are associated with each ship, an additional randomization would involve picking only some of the debris to spawn. 

i.e. berserker015.png would be the debris section of a berserker that should move away from the ship's center at 15deg from the ship's facing.

**Comment by Brick63** [comment]
here are some generic ones i made for the humans 

![human006-0 2x](https://user-images.githubusercontent.com/32852156/32326031-c1300112-bfa7-11e7-9850-0b244e4ee6af.png)
![human157-0 2x](https://user-images.githubusercontent.com/32852156/32326038-c66fffc4-bfa7-11e7-9003-fe41af24074b.png)
![human185-0 2x](https://user-images.githubusercontent.com/32852156/32326043-c96de056-bfa7-11e7-97dc-f4a1932210c7.png)
these would be easy to do and i can get it done quicker plus it allows for people to add to the pool if they so desire which could be a good starting point, im thinking of doing ~15 per race and then building it up from there

**Comment by endlesssteve** [comment]
I"m not sure that a space ship would just fall into nice pieces like this. Without an atmosphere and possibly no chemical explosion most of the ship or at least some of it would vaporize. It would be better if you got some of the bits randomly.
How about giving sprites to the outfits left after the final explosion rather than the plain little grey lumps?
Isn't this also going to get really messy in a major battle?
A shame this wasn't discused earlier before so much work had been done, the art work is very good.

**Comment by tehhowch** [comment]
@endlesssteve From my comment above:

> If a lot of debris sprites are associated with each ship, an additional randomization would involve picking only some of the debris to spawn.

You'll also note that this is not a PR. Issues are for exactly this purpose: discussion of ways to go about a task, especially when there are multiple. I'm also of the opinion that a major battle *should* be messy. We will have to see how things come together, and even then I'm sure there is a lot that can be tweaked beyond that.

**Comment by endlesssteve** [comment]
@tehhowch  Sorry you are right. Lesson No 12 don't comment on forums first thing in the morning!
I didn't say there should not be a discussion. Possibly my Northern British English. I simply wanted to say it would be a terrible waste of some good art work and Brick63s valuable time if this didn't get used.

I can stick my head in a bucket of water if you like.

Should I stick my head in a bucket of water?

Life ........

**Comment by jafdy** [comment]
Having 1 or 2 recognizable bits and a small collection of generic parts could work out quite nicely. Most of the ship is vaporized and there should be enough different combinations to avoid looking tacky.

**Comment by KiLEdEnNis** [comment]
I think as long as the "recognizable bits" aren't too big that could work
but a similar idea is to just make generic parts per species, the bigger the ship the more generic parts are spawned, without making recognizable parts to save a lot of work and to not set the "bar" to creating custom ships much higher

**Comment by montaropdf** [comment]
Hello,

Thanks to @beccabunny, I discover this issue when posting mine. If I read correctly, the problem you see with debris and wreckage, is the potential heavy work involved to create a ship and its wrecked version.

So why not designing ships in such a way that the game can alter it upon suffering damages and being destroyed.

I would like to point the game star sector which do a pretty good job in this regards.

Here is an example of ship completely burnt and considered destroyed: https://fractalsoftworks.com/wp-content/uploads/2021/03/screenshot687.jpg

When it comes to breaking a ship, why not simply cut the sprite in pieces like a piece of paper cut by scissors? It is not realistic but it does the job and that does not require for the sprite creator to have to deal with creating additional sprites.
