### ISSUE TITLE
Pilot Name

### ISSUE THREAD

**Issue by GoldenDalek** [endless-sky/endless-sky#3193]
When creating a pilot, the pilot's name is allowed to be empty. This creates issues when exiting to main menu, where the enter ship option is not displayed.

**Comment by tehhowch** [comment]
You can't make a blank character name - you must enter something in each box.

**Comment by GoldenDalek** [comment]
If you type a name, then quit the game straight away on the next dialog, it saves your pilot name as blank, but still creates a save.

**Comment by KiLEdEnNis** [comment]
I tried replicating this but for me it just saves the name
can you try to record it?

**Comment by GoldenDalek** [comment]
https://youtu.be/MGSrWuL0d4s

**Comment by KiLEdEnNis** [comment]
if you press "Load / Save..." there you still see the new file, the only small issue is that if you didn't press done it doesn't load the new save yet
I'm not sure if that's worth "fixing" though

**Comment by Amazinite** [comment]
Yeah, the pilot was never actually loaded so there is no file in `recent.txt` for it to link.

**Comment by GoldenDalek** [comment]
The actual problem is that even during the game, if you press escape, then the enter ship button is not available.

**Comment by tehhowch** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/c74ca06dd41f3d3ca6305f856ce63985db028fe9
