### ISSUE TITLE
More late game ship variety

### ISSUE THREAD

**Issue by Brick63** [endless-sky/endless-sky#3194]
the game needs more transports in it as late game it seems they are severely lacking there are some races that should have better ones yet fall short and others that don't have any at all.
an example the wanderers why don't they have a good transport since they so clearly need one. it seems like a nomadic species would like the idea of having large transports instead of fleets of tiny ships so i made one to test the waters and it turned out well. 
![pathfinder](https://user-images.githubusercontent.com/32852156/32374857-c571b166-c075-11e7-9b5b-22d1903f72ce.png)
i feel like the game should allow for transports that can still be useful in the late game but at this point the only good late game transport is the worldship which makes players who like to do transport missions fall behind those who like to do cargo(deep river) and those who like to fight(hurricane).

**Comment by Amazinite** [comment]
The Wanderer campaign could certainly use for a transport; a situation could arise where the Wanderers need to get the rest of their people out of the systems in soon-to-be Unfettered space as fast as possible, and a transport with a high speed, high fuel, and a bunk capacity comparable to or larger than that of the Deep River Transport could be developed.

As for the ship, it looks nice. A little too dark for my eyes though (comparison between the Hurricane and transport below). 
5 turrets and 0 guns, it looks like? Or are the guns just not visible?

![image](https://user-images.githubusercontent.com/17688683/32375126-d8548096-c076-11e7-9202-e1b4dc2260dc.png) ![image](https://user-images.githubusercontent.com/17688683/32375130-dc3abe96-c076-11e7-880f-d38dc0699bb5.png)

**Comment by Brick63** [comment]
no guns as its not meant for combat it will be able to hold its own but its mainly for moving people safely and quickly

**Comment by jafdy** [comment]
5 turrets is probably a bit much, these things are allowed to be escorted by warships as needed. 
The back of the sprite is quite flat.
Overall I like the concept.

**Comment by tehhowch** [comment]
Compensating some turret mounts with drone bays would address a number of issues with the current Wanderer Flycatcher situation.

The ship doesn't appear to catch the light like the Hurricane does - seems a bit dark, like the materials are different.

**Comment by Brick63** [comment]
![pathfinder 2x](https://user-images.githubusercontent.com/32852156/32380223-ed1bb058-c085-11e7-9303-6a9963fcaf2b.png)
yeah it was a bit dark so i made it lighter and ill take a look at the blender model to see what i can do

**Comment by Brick63** [comment]
also i was planning on having like 3-4 of the turrets be anti missile

**Comment by jafdy** [comment]
It's less about what you plan and what the player will do with it when they get hold of one. Cutting it down to 2 or 3 turrets and putting drone bays (flycatchers) in instead seems like a better way to go.

**Comment by Brick63** [comment]
true plus the flycathers have antimissle already so that would be good

**Comment by Amazinite** [comment]
@jafdy 
>It's less about what you plan and what the player will do with it when they get hold of one.

Low comparative weapon space is an equally viable change: the ship could have the 5 turret spots but low weapon space so they can't all be filled with heavy weapons.

**Comment by Brick63** [comment]
im trying it with 3 turrets and 2 bays

**Comment by Brick63** [comment]
heres the new @2x version(no texture)

![pathfinder 2x](https://user-images.githubusercontent.com/32852156/32380964-de92b016-c087-11e7-993c-5660aa94b7e2.png)

**Comment by Brick63** [comment]
here's a hai transport i'm working on as well since this isnt just about wanderers its about all races
![hai centipede 2x](https://user-images.githubusercontent.com/32852156/32396503-dadeb21a-c0bb-11e7-97e0-def78ed8af4a.png)

**Comment by Bladewood** [comment]
I've said this before elsewhere, but not every species needs dedicated transports. They might have multipurpose tools, like how the Summer Leaf is often used as a transport even though it is classified as a light warship.
Besides the possibility that some species (perhaps not in-game yet, but one day) genuinely have little need to actually move people around, this will further contribute to distinguishing species from each other, all the cool things and what not.

**Comment by ghoulavenger** [comment]
@Bladewood I don't really agree with that. From a storytelling perspective there is nothing wrong with what you're suggesting, and it's even implemented well in the Wanderer line (they didn't start making warships before they needed them). The problem comes from the gameplay, if all the transports are tier 1 ships, then you're locking them into tier 1 ships if they wish to use transports, which heavily discourages using transports. So at best I would say something more like, at least one tier 2 transport needs to exist -- and if theres only one choice, then the game is prescribing how to play.

By the way, the Wanderers actually DO have a pretty good transport in the game files. They have a modified deep river specific to the purpose, I'm pretty sure theres just no ability to capture or buy it.

**Comment by Amazinite** [comment]
>By the way, the Wanderers actually DO have a pretty good transport in the game files. They have a modified deep river specific to the purpose, I'm pretty sure theres just no ability to capture or buy it.

Yup, no way to buy one and capturing one requires breaking the story since they only appear in missions where you must defend them. The Deep River has its problems though, and wouldn't be useful in the following scenario that I mentioned above:
>The Wanderer campaign could certainly use for a transport; a situation could arise where the Wanderers need to get the rest of their people out of the systems in soon-to-be Unfettered space as fast as possible, and a transport with a high speed, high fuel, and a bunk capacity comparable to or larger than that of the Deep River Transport could be developed.

The Deep River Transport does have considerable bunk space, but it is VERY slow and has a low fuel capacity. Not exactly the type of ship you want to be flying during a get-out-fast scenario.

As for not giving some species transport ships, @Bladewood, while I don't see the Hai as needing one, I also don't see an issue with adding one. The Hai have one of the lowest ship diversities at the start of the game (only 4 ships), so I don't see the harm in adding a transport into the mix; perhaps it could be similar to the Star Queen, only useful.

**Comment by KiLEdEnNis** [comment]
Wanderer transport: not sure about the 5 engine exhausts, and on the drone bays where 2 turrets used to be, some green object doesn't align with the yellow-goldish bay
I also think the "bridge" is a bit small
apart from that I like it

as for the Hai one, I personally love it, just around the middle there are small red "triangles" on the sides; they asymmetric, apart from that it looks great

I don't think any other species need a dedicated transport, but if you make some stats for these 2 you can look for a merge, then we can rewrite the Wanderer story a little to replace the Deep River transport (and dialogues along with it)

**Comment by Amazinite** [comment]
>then we can rewrite the Wanderer story a little to replace the Deep River transport (and dialogues along with it)

I provided some stats for the ship to Brick on the Discord, and I don't see such a ship acting as a replacement for the Deep River Transport. The Deep River Transport was a simple way of getting people off the worlds being invaded. They didn't exactly have much time to develop a new ship. The stats I provided to Brick work better for the situation I mentioned (i.e. the Wanderers have time to develop and end up using the swift "Riptide", as we've named it so far, in order to get the rest of their people into Kor space ASAP instead of using the slow Deep River Transports).

**Comment by jafdy** [comment]
Riptide perhaps isn't a great name. To me that sounds like some kind of fast warship.

**Comment by jjhankins** [comment]
From a story perspective, I think you need something to justify > tier 1 transports - like the Wanderer need to evacuate, or the Korath nomadic culture. At least with humans, one of the things you pay for as you go up the transport scale is privacy and comfort, which means that capacity and quality are inversely related. The exception would be military transport, but then you're really talking about a variant on a warship, not a civilian transport.

**Comment by Brick63** [comment]
i agree not all races will have need of a pure transport but you have to think about it on a gameplay level whenever you add a stronger race you need to add ships so that the player can make money however they please(bounties,trade,transport) instead of forcing them to go to one or the other to keep up with the tech level of the area they are in.

**Comment by Amazinite** [comment]
>Riptide perhaps isn't a great name. To me that sounds like some kind of fast warship.

Wanderer wartime-ships are named after storms. (Tempest, Derecho, Hurricane)
Their major freighter has a water related name. (Deep River)
They've converted the Deep River into a transport ship. (Deep River Transport)
A riptide is a fast water current which pulls away from the beach.
The Riptide is a fast transport ship which pulls the Wanderers away from danger. Its name is also water related, just like the Deep River Transport.
Any questions?

**Comment by Brick63** [comment]
nah i came to the same reasoning after thinking for half an hour so its good

**Comment by Bladewood** [comment]
That does NOT look like a fast ship. It's all bulky and stuff.

**Comment by Brick63** [comment]
it has engines its fast compared to the deep river

**Comment by KiLEdEnNis** [comment]
5 engines and the smoother shape would make it relatively fast

**Comment by Amazinite** [comment]
>That does NOT look like a fast ship. It's all bulky and stuff.

It's space. Aerodynamics don't matter.
Also, as mentioned, 5 engines.

**Comment by Brick63** [comment]
now this can be used for more than just transports

**Comment by Brick63** [comment]
to start off the discussion of what races need more ships the Hai they don't have many so i made them a transport. still they have very few ships so i made them a Medium Freighter 

![hai grasshopper 2x](https://user-images.githubusercontent.com/32852156/32418231-d4d58906-c233-11e7-84c3-d73c511705ae.png)

while they have the aphid and water bug they don't have any middle ground so by adding a MF it gives the Hai more Variety.

**Comment by Amazinite** [comment]
That looks like it would fit better as an interceptor to me. I would also argue that the Water Bug *is* a medium freighter, and what they're missing is a true heavy freighter:

Ship | Cargo
-----|-----
Deep River | 1140
Bulk Freighter | 600
Hulk | 541
Behemoth | 490
Hauler III | 390
Spindle | 280
Sojourner | 260
Hauler II | 260
Water Bug | 197
Traveler | 137

The Water Bug has the 2nd lowest cargo space among the purchasable heavy freighters.

**Comment by Brick63** [comment]
well going with the Grasshopper being an intercepter what do you feel would make for a true Hai HF

**Comment by Amazinite** [comment]
No idea. I'd say choose one of these names:
[Cicada](https://www.google.com/search?safe=active&q=Cicada&stick=H4sIAAAAAAAAAONgFuLUz9U3MExJLy9T4gAx08yLy7Uss5Ot9JMy83Py0yv184vSE_Myi3Pjk3MSi4sz0zKTE0sy8_OscvLLU4sUUAWLHzEWcQu8_HFPWCpz0pqT1xiTucg3S0iNi801rySzpFJIhotXCuFSDQYpbi4ElwcAjru_m8cAAAA&npsic=-274&sa=X&ved=0ahUKEwiIhKqgnKjXAhXPciYKHSg1DHoQ-BYILw)
[Nepidae](https://www.google.com/search?safe=active&q=Nepidae&stick=H4sIAAAAAAAAAONgFuLUz9U3MExJLy9TAjPNswuLDbQss5Ot9JMy83Py0yv184vSE_Myi3Pjk3MSi4sz0zKTE0sy8_OscvLLU4sUUAWLHzEWcQu8_HFPWCpz0pqT1xiTucg3S0iNi801rySzpFJIhotXCuFUDQYpbi4ElwcAanXM6sgAAAA&npsic=-839&sa=X&ved=0ahUKEwiIhKqgnKjXAhXPciYKHSg1DHoQ-BYITQ)
[Geocoris](https://www.google.com/search?safe=active&q=Geocoris&stick=H4sIAAAAAAAAAONgFuLUz9U3MExJLy9TAjPNzUyTzLQss5Ot9JMy83Py0yv184vSE_Myi3Pjk3MSi4sz0zKTE0sy8_OscvLLU4sUUAWLHzEWcQu8_HFPWCpz0pqT1xiTucg3S0iNi801rySzpFJIhotXCuFUDQYpbi4ElwcA41ri9sgAAAA&npsic=-1481&sa=X&ved=0ahUKEwiIhKqgnKjXAhXPciYKHSg1DHoQ-BYIWQ)

**Comment by Brick63** [comment]
maybe the Titan beetle strongest jaws in the world

**Comment by Amazinite** [comment]
That sounds more like a warship to me.

**Comment by Brick63** [comment]
yeah i agree maybe the Dung beetle(not really)

**Comment by Brick63** [comment]
gonna try the geo ones

**Comment by Brick63** [comment]
heres is the geocoris
![hai geocoris 2x](https://user-images.githubusercontent.com/32852156/32419328-2ff86850-c246-11e7-943f-da1fcce8140a.png)

**Comment by KiLEdEnNis** [comment]
check if it's symmetric because I swear I see a lot of asymmetric objects all over (first of all the "spike" things that stick out all over)

**Comment by Brick63** [comment]
ill fix it sooner or later

**Comment by Brick63** [comment]
just checked everything is the same
must be the shadows

**Comment by Brick63** [comment]
okay made the exiles a new warship
![breaker 2x](https://user-images.githubusercontent.com/32852156/32443154-0f6ee948-c2cc-11e7-9c08-86a1e7bcb6c3.png)

**Comment by jafdy** [comment]
That's very red so will look a bit odd once swizzled.

**Comment by Brick63** [comment]
actually it looks fine i tried it myself

**Comment by Brick63** [comment]
![peregrine 2x](https://user-images.githubusercontent.com/32852156/32470955-e7e2fb78-c328-11e7-843e-6b29dbf92142.png)

new remnant ship

**Comment by Brick63** [comment]
Another ship for the remnant
![pelican 2x](https://user-images.githubusercontent.com/32852156/32501922-5586cbb8-c3a7-11e7-9a14-1a7c4032a468.png)
please feel free to leave feedback on the ships so far

**Comment by Wrzlprnft** [comment]
you know my stance on those, but what really holds them back is the symmetry errors.

besides: form follows function, and the function is not given: what are those supposed to be?

**Comment by Brick63** [comment]
the Peregrine would be a Medium warship and the Pelican Medium or heavy freighter

**Comment by Amazinite** [comment]
>the Peregrine would be a Medium warship and the Pelican Medium or heavy freighter
also

And which is which? You haven't attached names to the images.

**Comment by Brick63** [comment]
they have them now

**Comment by Brick63** [comment]
Here is my newest and in my opinion best remnant ship i made yet Called The Vulture
![vulture 2x](https://user-images.githubusercontent.com/32852156/32578644-f7591018-c4ab-11e7-8fa4-78713ebf2004.png)
Planning on it being a Heavy Warship that is better than the albatross and lore wise is used in their raiding fleets

**Comment by jafdy** [comment]
Those wings don't look symmetrical.

**Comment by KiLEdEnNis** [comment]
it's because of the shadows, put a couple of dim points above them around Z: 12-16 w/ strength like .15-.2, it should make the wings look more symmetrical without making it bright & ruining shadows

**Comment by Brick63** [comment]
Hmm ill look at he model in the morning

**Comment by Brick63** [comment]
![vulture 2x](https://user-images.githubusercontent.com/32852156/32607993-c2e85d70-c528-11e7-9a59-fca0de3380de.png)
Fixed the symmetry

**Comment by PJTheGuy** [comment]
I have to say, some of the other factions are kinda lacking in (good?) ships, in my personal opinion. Almost all the Hai ships are underwhelming except for the shield beetle (of course), the Wanderers, when you first get their license, you generally can get much better ships except for the Deep River, all of the Coalition ships are in the same boat as the Wanderers except for their freighters to an extent, and the Remnant only has the Albatross. The Starling would be good, but by the time you get to the Remnant, it's obsolete. The Cloaking Device integrated really doesn't make up for it past the Free Worlds storyline, when you would most likely want one the most.

Granted, we don't want to have all of the species be like humans, with dozens upon dozens of different ships, but it would be nice to have a larger selection instead of Bactrians, Deep Rivers, Albatrosses, and Shield Beetles to buy in the mid-game.

**Comment by Brick63** [comment]
thanks, what i'm planning on doing is PRing the ones i deem worthy of being added then the ones that are rejected/ don't make the cut ill put in a ship pack for people to use if they want

**Comment by jafdy** [comment]
The Peregrine is a bit dark, I had to turn my screen up to painfully bright levels to see anything on the left side of the body.

**Comment by Brick63** [comment]
i see what you mean ill work on that

**Comment by Brick63** [comment]
New Peregrine
![peregrine 2x](https://user-images.githubusercontent.com/32852156/32784707-8e6911c2-c91d-11e7-967c-775ed4d1be58.png)

New Vulture
![vulture 2x](https://user-images.githubusercontent.com/32852156/32784732-a05a57a6-c91d-11e7-8d99-f12234eddfc4.png)

**Comment by Brick63** [comment]
realized that others may want to share ideas here

**Comment by SirStigII** [comment]
I like all of these designs to be honest, they all look excellent.

**Comment by KiLEdEnNis** [comment]
the main question is, does MZ want this level of ship variety for the Remnant? (although I'd say apart from the Gascraft they should have at least 5 different ships)

**Comment by Lineth** [comment]
I'm 100% sure he has more ships in mind for the Remnant, but I do agree they need more ships, specifically civilian ones. Tough ones, but unmistakably non-combat (or non-scouting for the Starling or w/e it's called).

**Comment by Brick63** [comment]
the Hai ships are in #3314

**Comment by Brick63** [comment]
Closing this as it hasn't been used in almost a year

**Comment by KiLEdEnNis** [comment]
more Wanderer ships could work for the last bit of storyline, but that requires coordination with whoever makes that part of the story (likely MZ), plus that flat-ass transport should have some depth & general shapes in it, not a soft-cornered triangle

short version: if you edit/update them they could be added (although editing into the existing parts would be hard)

**Comment by Zitchas** [comment]
lol @Brick63 Closing this triggered attention.

I've been under the impression that there has always been some resistance to "letting" any ship exist that has better capturing capabilities than the Bactrian, in order to ensure that the World Ship and certain other ships remain almost impossible to capture.

**Comment by SirStigII** [comment]
![sketch-1542041076677](https://user-images.githubusercontent.com/26936987/48362038-fadeff00-e65f-11e8-9ae5-9c71cd744845.png)

**Comment by SirStigII** [comment]
![sketch-1542041076677 2](https://user-images.githubusercontent.com/26936987/48362113-2bbf3400-e660-11e8-83c4-c9a0bac83791.png)
