### ISSUE TITLE
Hardpoint order - innermost or outermost first?

### ISSUE THREAD

**Issue by ReimeiSky** [endless-sky/endless-sky#3198]
There is an inconsistency with ships with several hardpoints with the same Y-coordinate but different X-coordinates.
To demonstrate:
```
ship "Deep River"
	gun -56 -217
	gun 56 -217
	gun -40 -217
	gun 40 -217
	gun -18 -217
	gun 18 -217
```
But,
```
ship "Manta"
	gun -21 -35 "Particle Cannon"
	gun 21 -35 "Particle Cannon"
	gun -27 -35 "Particle Cannon"
	gun 27 -35 "Particle Cannon"
	gun -66 -32 "Meteor Missile Launcher"
	gun 66 -32 "Meteor Missile Launcher"
```
(The last two guns are not part of the issue; the problem is with the other four.)

So do the innermost gun ports go first, or is it outermost first?

Outermost: Deep River, Rainmaker, Maboro, Traveler.
Innermost: Manta, Vanguard.

I vote for innermost first.

**Comment by warp-core** [comment]
I vote for outermost first.

**Comment by flaviojs** [comment]
Does the order influence which gun port is filled first? If yes, without manual gun placement:

* outermost first: higher chance of hitting someone with one of the guns?
* innermost first: faster disable of what is in front of you due to concentrated hits?

Since we have auto-aim, I'd say innermost first is better. For missiles, outermost first might be better.
But ultimately, nothing beats trying out each ship with only two guns/missile launchers and see which positions are more useful. =P

**Comment by KiLEdEnNis** [comment]
guns listed first are autofilled first if you buy a weapon @flaviojs

**Comment by endless-sky** [comment]
Note that the outermost-first ships are ones that use tracking weapons, and the innermost-first ones use primary weapons in those slots (by default). In general, primary weapons are most effective when they're close to the center line of the ship.

**Comment by Bladewood** [comment]
If you're referring to my post, then my issue was not the ordering of weapons, it was the ordering of the hardpoints themselves.

**Comment by KiLEdEnNis** [comment]
I think it should be innermost-first
basically: it goes from front>back, in>out

**Comment by tehhowch** [comment]
It's a style issue. Using an approach similar to outline making / image drawing (start at top left: move right, advance line, repeat) seems sensible to me.

**Comment by KiLEdEnNis** [comment]
then if you have 6 guns in a row on the same line and you'd sell stock guns & buy say 2 new guns, the game would put them in the 2 most left gun ports because they are listed first

**Comment by tehhowch** [comment]
I should have been more specific, and indicated processing in pairs (as is seen in the OP). Without pair processing, yes, you are correct that the added weapons would fill from the left first and not symmetrically.

**Comment by warp-core** [comment]
In: #2086, #2856, #3712, and #8998, I used the system:
- front to back,
- outside to inside,
- left to right.
That is, first sort by increasing y values.
Then, for hardpoints with the same y value, sort by decreasing magnitude of the x value.
Then, for hardpoints with the same y value and x values of equal magnitude (symmetrical pairs) the left one goes first.
There is an exception to this last part for ships with multiple hardpoints in the same locations, such as teh Carrier:
```
	gun -17.5 -176.5 "Particle Cannon"
	gun 17.5 -176.5 "Particle Cannon"
	gun -17.5 -176.5 "Meteor Missile Launcher"
	gun 17.5 -176.5 "Meteor Missile Launcher"
	gun -26 -167.5 "Particle Cannon"
	gun 26 -167.5 "Particle Cannon"
	gun -26 -167.5 "Meteor Missile Launcher"
	gun 26 -167.5 "Meteor Missile Launcher"
```
Here, the co-located hardpoints are not listed together, but instead split into separate pairs.
