### ISSUE TITLE
Keyboard shortcut for moving ships up or down in the fleet listing

### ISSUE THREAD

**Issue by muglyObserver** [endless-sky/endless-sky#3202]
It would help to keep a large fleet organized if you could use a keyboard shortcut to move ships up and down in the list.  So you could highlight a ship of interest and press (for example) Shift+UpArrow to move it up, and hold the keys down to move long distances, rather than drag up, page up, drag up, page up, drag up, page up, etc.

An alternate approach would be to have the list automaticly scroll when you hit the top or bottom of the screen while dragging a ship with the mouse.

**Comment by tehhowch** [comment]
I'd go with Control or Alt and not Shift - Shift is often used as a selection extender, so having it reorder ships in this menu but expand the selection in the Shipyard and Outfitter would be counterintuitive.

In the Atom editor, Control and an up or down arrow key moves the selected lines of text up or down, as appropriate.
An automatic scroll zone while dragging would be nice too.

**Comment by tehhowch** [comment]
#3229 uses simultaneous Ctrl + Shift and the Up or Down arrow key to move the selected ships up or down one row.
I didn't attempt to implement the scrolling zone.

**Comment by muglyObserver** [comment]
Thank you tehhowch.  This sounds like what I was looking for.  Perhaps I can look into updating the docs.

**Comment by endless-sky** [comment]
Fixed by merging #3229.
