### ISSUE TITLE
Show ship name on hover in the Shipyard and Outfitter screens

### ISSUE THREAD

**Issue by muglyObserver** [endless-sky/endless-sky#3203]
When you have a large fleet on-planet, the right hand side of the Shipyard and Outfitter screens will fill with thumbnails showing your ships and push the details of the selected ship off the bottom of the screen.  When you select a ship by clicking on it's thumbnail, you need to scroll to the bottom to find out if you clicked on the right one.

It would be helpful if a ship name was displayed while hovering the mouse over it's thumbnail, or if a line at the bottom was reserved for displaying the selected ship name.

**Comment by jafdy** [comment]
If I have enough ships that I need help to keep track of them then I don't have the foggiest clue what their names are.
While I can't see any disadvantages in this I can't think of a situation is would help either.

**Comment by endlesssteve** [comment]
I think this would be useful when swapping outfits between your ships. I tend to play keep what you catch and rearrange the outfits quite a lot. I also tend to number ships in large fleets rather than name them.

It's not really a big deal but then I don't think it's a big change.

Just my opinion. If you don't agree just ignore it. No need for detailed analysis of my stupidity.

**Comment by muglyObserver** [comment]
endlesssteve, no stupidity detected.  :-)
 My usage is similar to yours except I tend to raid ships for valuable parts and then sell them to finance my evil plans.

**Comment by hellminister** [comment]
i wonder if placing the ships in a column beside (on the right side i think) of the info panel with its own scrolling wouldnt help this

I also wonder if it wouldnt be possible to have the possibility to customize those interfaces also, similar to the interfaces.txt file

**Comment by endlesssteve** [comment]
@muglyObserver   Thanks. but that comment wasn't really meant for you. There are some overly critical members here. Sorry I didn't write it more clearly.
