### ISSUE TITLE
fighters gets unloaded when landing on a planet and the carrier is in another system

### ISSUE THREAD

**Issue by hellminister** [endless-sky/endless-sky#3204]
When landing on a system and a carrier is in another system, the fighters starts unloaded when departing the planet.  This is a problem when the fighters in questions are relying on solar panel and a small battery (boxwing maximized for cargo....) because they are usually unable to regain their carrier and starts drifting away in space rapidly becoming irrecuperable.  playing version 0.9.8

**Comment by tehhowch** [comment]
Already fixed in a source build. This was fixed by https://github.com/endless-sky/endless-sky/pull/3001

**Comment by hellminister** [comment]
ok, thanks
i did a search but didnt find it, i used the wrong keywords as usual

**Comment by KiLEdEnNis** [comment]
I'm not sure if you only searched for issues or also pull requests, but as long as you make some effort it's fine, no problem

**Comment by tehhowch** [comment]
There was no corresponding GitHub issue reference for #3001, so not finding it when searching is certainly more likely than finding it, due to lack of a keyword cross-section.
