### ISSUE TITLE
Mereti models

### ISSUE THREAD

**Issue by Kryes-Omega** [endless-sky/endless-sky#3207]
I looked on the google drive, and saw that the blend files for the Kor Mereti ships, except for the model 8, are all just the blender startup file. Are the original models lost, or was this just a mistake?

**Comment by KiLEdEnNis** [comment]
I had the 256 and 512 files from months and months ago, so if something happened to them, it happened last few months
I bet it happened after the mass reshading of all ships

**Comment by endless-sky** [comment]
I've uploaded new copies. Sometimes Google Drive uploads stall and report that the files were uploaded even when they weren't.

**Comment by Kryes-Omega** [comment]
Nice, thanks
