### ISSUE TITLE
Feature idea: save squads

### ISSUE THREAD

**Issue by ZufengW** [endless-sky/endless-sky#3210]
Some RTS games have a way to save a subset of your allies as a squad for easier selection in the future. For example: When in space, pressing shift+1 could save your current selected allies as a squad in slot 1. Pressing 1 again would select those ships again. Then you can give orders to them.
This makes it easier to group together parts of your fleet for certain roles.
- Any destroyed/sold/etc. ships are removed from the squad automatically
- The same ship can be in any number of squads
- Pressing the assign key (shift+1) in the Ship Info could toggle membership of a squad for that ship
- There could be another panel somewhere (e.g. in Player Info) for viewing your current squads

**Comment by hellminister** [comment]
Assign group hotkey to selected escorts | Control / Command + number key
-- | --
Select group of escorts | number key
 
from the players manual

**Comment by Brick63** [comment]
as stated it is already a feature but it could be explained better like most of the current features
