### ISSUE TITLE
Behemoth

### ISSUE THREAD

**Issue by CMSgtCodeFox** [endless-sky/endless-sky#3211]
I believe that the behemoth should be reclassed as a light warship instead of being a heavy freighter.

**Comment by Brick63** [comment]
What is your reasoning and basis for this

**Comment by Amazinite** [comment]
How about no.
Behemoth cargo: 490,
Highest human light warship cargo: 60 (Modified Argosy)
Behemoth hit points: 13.9k
Strongest human light warship: 7.2k (Gunboat)

**Comment by KiLEdEnNis** [comment]
that it can function like a decent warship doesn't make it 1; it's a heavy freighter with good fighting capabilities
there are 3 main "types" of ships: warships, freighters and transporters, some ships are more of a mix between them, and the Behemoth happens to be 1 of them
and if you'd even classify it as a warship, I'd pick medium over light

**Comment by Brick63** [comment]
while it does seem to be more of a warship its a freighter because of many reasons the main one being the cargo hold which is bigger than any warship i can think of and its a heavy because it can hold its own in a battle but it isn't warship matterial

**Comment by endlesssteve** [comment]
May be if you filled the cargo space with helium and put a few guns on it could be a light warship.

otherwise it is very definitively heavy. Even the name is a bit of a give away.
