### ISSUE TITLE
Crash at startup on Lubuntu 17.10

### ISSUE THREAD

**Issue by Stereoprism** [endless-sky/endless-sky#3213]
Downloaded through the Software repository. Starting endless sky from the start menu does nothing. Running it from the terminal spouts out this:

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Endless Sky requires OpenGL version 3.0 or higher.
Your OpenGL version is 2.1 Mesa 17.4.0-devel, GLSL version 1.20.
Please update your graphics drivers.

I'm running a Dell Studio 1558 laptop. Intel integrated graphics. Managed to update opengl to 2.1 but have no idea how to push it further.

Thankful for any ideas or help!

**Comment by warp-core** [comment]
I suspect it's not possible to update the graphics driver to one that supports OpenGL 3 for that laptop. A model number for the processor would help in confirming whether or not the hardware is capable of supporting OpenGL 3.
If it isn't someone does have a branch that has been modified to run on OpenGL 2 but it hasn't been tested on many setups and you'll also have to compile it yourself.

**Comment by MCOfficer** [comment]
endless sky needs OpenGL 3 to run. however, there is a [fork](https://github.com/luskynavy/endless-sky/tree/opengl2.1) that is OpenGL2-compatible, although it hasn't been updated for some months.

**Comment by Stereoprism** [comment]
Model # PP39L

I have like no experience compiling but to have Endless Sky on my laptop I might be willing to do so!

**Comment by warp-core** [comment]
If you're on Linux I don't think it's a massively complicated process. You can find it in the readme-developer file.

**Comment by Stereoprism** [comment]
Worked! Thanks for everything. Wish I could get the most recent but eh. This works for now.

**Comment by tehhowch** [comment]
If you learn a bit of `git` it shouldn't be tough to do. 

You'd start with a local git repository that is t your working, opengl2 branch of ES. Then you'd add a "remote" that points to this repo, and every so often, execute the command `git pull upstream master`, where 'upstream' is the name of the remote that refers to this repo (you control the names of your personal remotes). There may be some "merge conflicts" that result from that command (indicating a file you changed was changed by someone else in this repo), in which case you'd need to edit the conflicted file to say which edit is correct (sometimes both are, but git is cautious and thus defers to you).
