### ISSUE TITLE
Content creating: setting costs

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3214]
It seems to me that one of the most difficult parts in balancing outfits/ships is calculating price tags for them.
A lot of gameplay testing and thinking and calculations can lead to solutions for weapon energy drain and damage and reactor power, but such a relation is not at all clear when it comes to price tags.

Obviously, it gets more and more expensive as you move up the tiers - but by precisely how much? How do we calculate it? Is it linear or does it grow exponentially?

As an example of what I've come up with in the meantime (which is probably completely wrong, all things considered), I've developed this:
```
M = mass_weapon + mass_energy + mass_cooling
mass_energy = firingEnergy / energyGeneration * mass_generator // energyGeneration and mass_generator will depend on your weapon's tier, using generators from that tier to convert firingEnergy to mass.
mass_cooling = (firingEnergy / energyGeneration * heatGeneration_generator + firingHeat) / cooling * mass_cooling // Similarly for cooling, using generators to convert firingEnergy to heat, summing that with firingHeat, and then converting that into mass with a cooling outfit from that tier.
D = shieldDamage + hullDamage / 3 + heatDamage / 25 // The scale factor of 1/3 is due to the fact that the majority of ships have a 3:1 shield:hull ratio. I have no idea why the 1/25 factor is there, it just seems to work.
O = D / M * range / 100 // Purely efficiency.
X = O * mass_weapon // To take into account the actual mass of the weapon.
cost = KX // K is an arbitrary scale factor. Compare with similarly sized weapons from that tier.
```

**Comment by KiLEdEnNis** [comment]
if ya want to do it properly, just calculate cost-efficiency
basically make some chart w/ tech of the same level, then divide energy, heat, space etc. by the cost & use math to make the results fit in the chart
if it's not on the top or bottom of the list it should be fine
