### ISSUE TITLE
Modulus operator for conditions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3217]
I'm currently working on regional jobs for the regions of space that Pointedstick missed, and one of my ideas involves a job that happens every X amount of years. Using a modulus operator, it would look something like the following:
```
to offer
     year % 7 == 0
```
The above would make this job offer every 7 years on years that are a multiple of 7. Such an operator would be helpful for making other jobs that only offer every few years instead of being relegated to only being able to make jobs offer during certain times of every year.

**Comment by tehhowch** [comment]
Yeah, this can be done pretty easily with #3128 
I'll push a commit soon with it
