### ISSUE TITLE
Spacedock missions dont check available space

### ISSUE THREAD

**Issue by dje4321** [endless-sky/endless-sky#3218]
When accepting a spacedock mission it will not check to see if you have enough room in the bunks or the cargo hold causing you to hold more items then the ship should allow. This causes available cargo space to go into the negatives.

version 0.9.8 (installed via steam)

![screenshot from 2017-11-10 22-33-42](https://user-images.githubusercontent.com/10913120/32686288-d50ad6f0-c667-11e7-8a04-65c8048b03f4.png)

**Comment by Amazinite** [comment]
Duplicate of #16?

**Comment by dje4321** [comment]
dont think so as that is taking jobs from the job board instead of the spacedock

**Comment by Amazinite** [comment]
>Well, I think I agree with sodium70mg that you shouldn't be allowed to exceed your limit by taking on ordinary "jobs," because that is rather confusing. This feature was really just intended for special missions.

Special missions being what you call spacedock missions. It's the same issue, and intended.

**Comment by dje4321** [comment]
there is no message that pops up when i try and depart. 

after closer inspection it just seems to sell off random cargo

**Comment by Amazinite** [comment]
So what is the issue then?

**Comment by dje4321** [comment]
dont think there is one. Thanks for letting me know what was going on. Didnt think that was supposed to happen so i thought i should report it :D

**Comment by tehhowch** [comment]
Missions don't care if you have commodities, because they're commodities. As above, you won't be able to launch with negative space - b commodities will be sold until you are able to take off
