### ISSUE TITLE
Comparing two ships goes well off the screen

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3219]
![1gki_kcxrrmx3y_qlpbkyq](https://user-images.githubusercontent.com/17688683/32686978-8c875300-c67f-11e7-9aec-63ddeea9c92b.png)

Suggested fix: instead of having the comparison look like this:
![current](https://user-images.githubusercontent.com/17688683/32687004-0c60e7d0-c680-11e7-87c0-ffb89ff55fae.png)
make it look like this:
![proposed](https://user-images.githubusercontent.com/17688683/32687003-0b6b3d94-c680-11e7-8589-987efc923331.png)

**Comment by hellminister** [comment]
that thing at the top is for the next update?  i agree that the bottom option is better, less scrolling and easier to compare attributes line by line

**Comment by tehhowch** [comment]
No, it's in the game for quite a long time. Map-> Shipyard panel -> click one ship -> shift click a second

**Comment by hellminister** [comment]
ok... didnt notice that in the players manual... :|

Still, the bottom option would be better for comparaison :)

**Comment by endless-sky** [comment]
After playing with a few options, here's what I think would look the best, while also making efficient use of space:

![compare](https://user-images.githubusercontent.com/11450262/32929330-487dbb4a-cb25-11e7-946b-272796d07316.jpg)

**Comment by endless-sky** [comment]
I've made this adjustment in eb96f6f.
