### ISSUE TITLE
FW Diplomacy 1B - need to bribe Earth to land

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#322]
During mission FW Diplomacy 1B you need to offer bribe to Earth in order to land.
I'd expect Alondo to talk to the dignitaries and clear you to launch, just like earlier missions

**Comment by gchapyzh** [comment]
The corruption is real.
Maybe also add a feature where if your combat rating is below, say, seven, you will be permitted on hostile Republic planets.

**Comment by thenerdfreak** [comment]
there are a lot of missions where i had to pay a planet 4 million plus to land and continue the mission

**Comment by gchapyzh** [comment]
@thenerdfreak that definitely has to go. I don't want to have to pause a mission and collect money just to complete the darn thing.

**Comment by thenerdfreak** [comment]
The bribe you pay is based on your current money I think, considering it costed 1 million to bribe the same planet before the mission, and it now costs even more after the mission

**Comment by endless-sky** [comment]
@wkoot, is it possible that your two weeks of safe passage had expired before you tried to land on Earth? (For example, because you did not take the most direct route there and back?) Or, were the Republic ships still friendly, and yet Earth was not letting you land?

**Comment by wkoot** [comment]
The safe passage did not expire; Mars and Luna were actually not hostile, neither were republic ships

**Comment by endless-sky** [comment]
Ah. Looks like the safe passage event was giving you a reputation of 1, but you need 2 or higher to land. Fixed in 5303c82.

**Comment by wkoot** [comment]
Cool. This doesn't interfere with any other fw safe passages?

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
