### ISSUE TITLE
"illegal" and "stealth" attribute should work for passengers, too

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3223]
Right now "stealth" only works for cargo, so if you want to have an illegal passenger mission that will fail when you get scanned, you need to give the passengers one ton of dummy cargo as a workaround, so that you can apply illegal and stealth to the cargo (this workaround is used [in some pirate missions](https://github.com/endless-sky/endless-sky/blob/master/data/pirate%20jobs.txt#L1080)) . "stealth" should work for passengers, too, without needing to give the mission any cargo.

I tried to make the obvious-seeming code change in mission.cpp:

```
diff --git a/source/Mission.cpp b/source/Mission.cpp
index b5bcb959..09ecb333 100644
--- a/source/Mission.cpp
+++ b/source/Mission.cpp
@@ -123,6 +123,20 @@ void Mission::Load(const DataNode &node)
                                passengerLimit = child.Value(2);
                        if(child.Size() >= 4)
                                passengerProb = child.Value(3);
+                       for(const DataNode &grand : child)
+                       {
+                               if(grand.Token(0) == "illegal" && grand.Size() == 2)
+                                       illegalCargoFine = grand.Value(1);
+                               else if(grand.Token(0) == "illegal" && grand.Size() == 3)
+                               {
+                                       illegalCargoFine = grand.Value(1);
+                                       illegalCargoMessage = grand.Token(2);
+                               }
+                               else if(grand.Token(0) == "stealth")
+                                       failIfDiscovered = true;
+                               else
+                                       grand.PrintTrace("Skipping unrecognized attribute:");
+                       }
                }
                else if(child.Token(0) == "invisible")
                        isVisible = false;

```

Then I created and ran a mission that had the following in it:
```
passengers 1
		illegal 75000 `Your passenger turns out to be a wanted criminal, and he is hauled off in chains as you vehemently protest that you knew nothing of his shady history. The authorities threaten you with jail time, and you quickly contact a lawyer. Through a combination of fines, bribes, and attorney's fees (the breakdown is not entirely clear to you) you wind up 75000 poorer.`
		stealth
```

But I was repeatedly scanned (outfits and cargo) and never suffered the consequences. This probably requires a deeper code change.

**Comment by tehhowch** [comment]
Government Fine doesnt look at bunks, only cargo. Change there as well and that should do it

**Comment by Pointedstick** [comment]
I'm afraid I'll need a more detailed hint than that. :stuck_out_tongue:

**Comment by tehhowch** [comment]
I should have said to modify the CargoHold::illegalcargo method. It doesn't check mission passengers.

That's what I get for off the cuff method mentions 😋

**Comment by Amazinite** [comment]
I had this problem with certain pirate jobs, so I just attached 1 ton of illegal cargo alongside the passengers.

**Comment by Pointedstick** [comment]
Ah, a much more fruitful hint! That was an easier change than I thought: https://github.com/endless-sky/endless-sky/pull/3226
