### ISSUE TITLE
New NPC behavior option: disables, boards, then leaves without destroying

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3224]
I'm trying to write some missions where you transport wanted people, and it would be nice if I could make the mission fail when boarded. But I can't seem to get an NPC to board you without destroying you:

- With "disables", they will disable you but won't board
- With "plunders", they will disable and board you, then destroy you, and then leave
- With "disables" and "plunders", they will disable you but won't board

I'd like a condition that makes them disable you, then board you, then leave **without** destroying you.

See also https://github.com/endless-sky/endless-sky/issues/3225

**Comment by MessyMix** [comment]
It wouldn't hurt to have an extra personality, but I don't really see where you could use this to fit your purpose of transporting wanted people: if the Republic (or really any govt. against whom you are transporting wanted people) board you, they are bound to confiscate / destroy your ship after arresting the people, and yourself.

**Comment by KiLEdEnNis** [comment]
there's innocent crew on your ship, and a Republic ship that boards ya may not have the room to arrest all your crew members if they even have to
and if ya help a criminal by letting him/her live in your house & ya get arrested when the government finds out they don't destroy your house either

**Comment by Pointedstick** [comment]
Actually in the mission I'm writing, the boarders are bounty hunters, not the Republic. So it's conceivable that they would only take the wanted men you're carrying.

**Comment by jafdy** [comment]
I will point out that most houses don't have large guns...

**Comment by KiLEdEnNis** [comment]
I don't think bounty hunters would actually destroy your ship though, maybe some would but I don't think they should destroy the player

and jafdy; if they'd arrest you too, ya can't really use those large guns on them

basically I don't think the player should be destroyed - along with its crew - for helping a criminal while they may not even know it

**Comment by MessyMix** [comment]
I don't know; bounty hunters would probably run away with your ship and sell it somewhere for a hefty sum. But that's beside the point. New personalities can't hurt.

**Comment by tatami4** [comment]
With #5667 if you use `disables` + `boards`, the ship will disable enemies, board them and will not kill them once boarded.

**Comment by Amazinite** [comment]
Hmm. Hadn't seen/recalled this issue.

**Comment by Pointedstick** [comment]
This was more of a feature request than a bug report. :)

**Comment by Amazinite** [comment]
Well I'd say that disables + plunders was bugged, and fixing that makes the combination of those two personalities achieved the desired effect for this issue. :)

**Comment by Pointedstick** [comment]
Ah indeed!
