### ISSUE TITLE
possibility to have outfits change images of other sprites when equiped

### ISSUE THREAD

**Issue by hellminister** [endless-sky/endless-sky#3227]
is it possible to make an outfit that can change the image used for a sprite?

For example having a scanner that modifies or change the image of the sprites type targetted by that scanner

**Comment by tehhowch** [comment]
Sprite changing would not be my first choice. For a minables scanner, I have mentioned previously that one method would be to draw the "scan circles" for a short period of time for minables that were within a certain distance of the ship at the time of activation. Besides minables I'm not sure what else would benefit from "highlighting".

Some sort of camouflaging outfit that alters how your ship appears after a few seconds of activation could be neat, but selecting the ship to camouflage as would be hard to do well.

**Comment by hellminister** [comment]
i agree with you

i made a plug-in that changes the minable sprite with the same but has a colored square around it
made it available on steam forum

i wanted to be able to make an outfit for it that could activate the effect though
i dont think i can add a circle or anything with the modding capability of the game

**Comment by tehhowch** [comment]
Correct. Adding a minables scanner will require changes to the game's source code.

**Comment by tehhowch** [comment]
Minables scanner is now in-game.

**Comment by tehhowch** [comment]
Photo in action:
![image](https://user-images.githubusercontent.com/20871346/33049733-0d3be14c-ce27-11e7-9dba-b539b747565d.png)

**Comment by hellminister** [comment]
nice
