### ISSUE TITLE
Reclassification of 'Caph' to republic in the end game

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#323]
Since Caph has that space station, attacking the system enrages the Republic, so an easy fix would just be to transfer Caph to the republic. Even Republic ships emerged from the planet to attack when I demanded tribute

**Comment by endless-sky** [comment]
I switched the defense fleets to the Syndicate instead (fd6dcd2), since I'm not sure if any of the missions depended on Caph being a Syndicate world.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
