### ISSUE TITLE
2794 doesn't seem to have fixed the planet eye problem.

### ISSUE THREAD

**Issue by endlesssteve** [endless-sky/endless-sky#3233]
I"m playing the wanderer mission and the eye has just appeared. However it is a planet with jobs etc.
I checked for existing issues and there are two the main one being 2794. It says fixed in 9.8 but I'm playing 9.8 from the Ubuntu ppp and the bug is still present.

**Comment by tehhowch** [comment]
To clarify: you are saying that if you start a new game and play through it, the event which adds The Eye creates a planet instead of a wormhole?

**Comment by endlesssteve** [comment]
I'm afraid all my saves have the planet eye. I tried to go back and check it myself but they don't go back far enough. One thing I remember doing is that the eye actually first appeared after repeated visits to the system show the first anomaly. Although not labeled as the eye it is obviously a wormhole so I tried to go through it (land)  but I actually landed on it. May be this puts something in the save file that causes problems. I'll check my save and see if there is anything suspicious.

**Comment by endlesssteve** [comment]
I have the autosave triggered by the Ap'arak3 mission below.
I've searched for eye and the following are the only relevant entries.

# What you've done:
mission "Wanderers Ap'arak 3"
	name "Report to Vara K'chrai"
	description "Return to the Wanderer capital on Vara K'chrai in the Ka'ch'chrai system."
	autosave
	landing
	to offer
		"Wanderers Ap'arak 2: done" != 0
	destination "Vara K'chrai"
	on complete
		conversation
			label 0
			"A few minutes after you land on Vara K'chrai, a sudden uproar passes through the Wanderers in the spaceport. It's hard to be sure, but you think they sound excited, not frightened. Ships start taking off, more and more of them until the spaceport is almost deserted, and no one who is left seems at all interested in talking with you or explaining what is going on. You're probably going to have to return to your ship and see for yourself what all the fuss is about."
				decline
		event "wanderers: derecho mass production" 16
		event "wanderers: spera anatrusk colony" 40
		event "wanderers: the eye opens" 0
.
.
.
.

"event: wanderers: tempest mass production"
	"event: wanderers: the eye begins to open"
	"event: wanderers: truce timer"

I don't see anything strange.

**Comment by endlesssteve** [comment]
1. Yes this is a complete new start in 9.8 and my pilot can only land on the eye and is unable to pass through.
2.The only mod to the game is a trial plugin with a modified ship. Can"t see how this could possibly cause this. I have not used the ship in this whole game.
3.I'm using the standard Ubuntu version from the ppp published on github.

save file from before the eye is fully there.

[Rookie Fullman~autosave.txt](https://github.com/endless-sky/endless-sky/files/1485058/Rookie.Fullman.autosave.txt)

Save file with pilot on the eye.

[Rookie Fullman.txt](https://github.com/endless-sky/endless-sky/files/1485059/Rookie.Fullman.txt)

**Comment by tehhowch** [comment]
If it works from the GitHub compile, then there is no issue except perhaps the PPA is out of date.

**Comment by tehhowch** [comment]
I just tested the steam version, and the event works just fine there, which means #2794 was properly resolved.

**Comment by endlesssteve** [comment]
As far as I can see 2794 should have been part of the first 9.8. Michaels ppa has the official 9.8 so it can't be just out of date. I do however accept that this only seems to be a problem with the ppa version.

Should I leave this open or alert Michael via the google groups thread?

Out of interest what makes a planet a planet and a wormhole a wormhole?

**Comment by endlesssteve** [comment]
Having checked through the other issues I can see the changes from 1fcfd4b are not included in system.cpp in the version from the ppa.

**Comment by MessyMix** [comment]
Nice. Glad to hear it's been resolved; close? Thanks.

**Comment by tehhowch** [comment]
Close it when MZ updates his PPA and posts here indicating it's been done.
