### ISSUE TITLE
whole number values above 1. in a color node cause oddities

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#3236]
Edit: Issue was as per title. Decimal values display normally. Values above 1. cause the issue.

The UI commits got me curious about doing an alien UI mod, so I just did a quickie color change to see what all was customizable in terms of colors, and found some oddities. Notably the font is bolder, and not smooth at all when its colored.

It's most noticable here because we have the offwhite for the credits to compare to, but its the same throughout.

![1653331910](https://user-images.githubusercontent.com/22107649/32996178-9ada908c-cd4d-11e7-9274-b066eb2cdae1.jpg)
![1717131910](https://user-images.githubusercontent.com/22107649/32996182-9cd99ca2-cd4d-11e7-8420-1e071b0e5cca.jpg)

**Comment by KiLEdEnNis** [comment]
could it be that recoloring letters doesn't take the alpha (transparency) into consideration (which means the less visible outlines of the letters take the full color change too)?

**Comment by comnom** [comment]
Actually the issue is that it accepts whole number values and I should have used decimal values. Whoops
