### ISSUE TITLE
Build failing on OS X "Apple Mach-O linker (ID) error"

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#3237]
Recently I decided I would  compile the game myself again. I've done this before, and it's worked perfectly fine (after getting all the libraries, which took way to long). But, now that I've pulled from this repo and tried to build it on XCode it fails. The over all error (as I see it) is "Apple Mach-O linker (ID) error." The full text is 
`
Undefined symbols for architecture x86_64:
  "Dictionary::operator[](char const*)", referenced from:
      Outfit::Add(Outfit const&, int) in Outfit.o
      Outfit::Add(char const*, double) in Outfit.o
      Outfit::Reset(char const*, double) in Outfit.o
  "Dictionary::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Outfit::Load(DataNode const&) in Outfit.o
  "Visual::Move()", referenced from:
      Engine::CalculateStep() in Engine.o
  "Visual::Visual(Effect const&, Point, Point, Angle, Point)", referenced from:
      Flotsam::Move(std::__1::vector<Visual, std::__1::allocator<Visual> >&) in Flotsam.o
      void std::__1::vector<Visual, std::__1::allocator<Visual> >::__emplace_back_slow_path<Effect const&, Point&, Point&, Angle&>(Effect const&&&, Point&&&, Point&&&, Angle&&&) in Flotsam.o
      Projectile::Move(std::__1::vector<Visual, std::__1::allocator<Visual> >&, std::__1::vector<Projectile, std::__1::allocator<Projectile> >&) in Projectile.o
      Projectile::Explode(std::__1::vector<Visual, std::__1::allocator<Visual> >&, double, Point) in Projectile.o
      void std::__1::vector<Visual, std::__1::allocator<Visual> >::__emplace_back_slow_path<Effect const&, Point&, Point&, Angle&>(Effect const&&&, Point&&&, Point&&&, Angle&&&) in Projectile.o
      void std::__1::vector<Visual, std::__1::allocator<Visual> >::__emplace_back_slow_path<Effect const&, Point, Point&, Angle&, Point&>(Effect const&&&, Point&&, Point&&&, Angle&&&, Point&&&) in Projectile.o
      (anonymous namespace)::CreateEffects(std::__1::map<Effect const*, int, std::__1::less<Effect const*>, std::__1::allocator<std::__1::pair<Effect const* const, int> > > const&, Point, Point, Angle, std::__1::vector<Visual, std::__1::allocator<Visual> >&) in Hardpoint.o
      ...
  "Dictionary::Get(char const*) const", referenced from:
      Outfit::Load(DataNode const&) in Outfit.o
      Outfit::Get(char const*) const in Outfit.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

No idea what is going on or if it's just me breaking something so any help would be nice

**Comment by tehhowch** [comment]
You need to add some files to the XCode project, likely the
```
Dictionary.*
Visual.*
```
files.
PR the change back to the repo, btw.

**Comment by gunqqer** [comment]
Not very good at all of this, what does that mean?

**Comment by tehhowch** [comment]
It means that when the Dictionary class was created, two files were added to the source folder, `Dictionary.cpp` and `Dictionary.h` which describe how the class functions. The XCode project file has not been updated to include those files, and thus when you attempt to build the game, XCode is trying to find where the definition of `Dictionary::Get` is, but can't (because it's in a file that XCode hasn't yet been told to care about). Same for the `Visual` class.

**Comment by gunqqer** [comment]
How do I fix this?

**Comment by tehhowch** [comment]
Never used XCode, so use the internet to find a guide. "Adding files to an XCode project" should be a good start

**Comment by gunqqer** [comment]
Ok, problem fixed by going to the file list tab in XCode, right clicking on the "source" folder, select "add files to endless sky..." then navigate to the folder that has the game's source code in it and selecting everything in it (You can do this because everything that is already reconized by xcode is un-selectable).

**Comment by MessyMix** [comment]
Thanks for posting your solution. It's so aggravating when issues on forums
I assume are solved IRL but the solution is never made known.

**Comment by tehhowch** [comment]
Now one of you PR the fix so everyone gets it :)

**Comment by gunqqer** [comment]
I've had that problem many times, Messy, and I don't want anyone else to have that problem. (Also, if you happen to be from the future and this helped you, yay!)

**Comment by tehhowch** [comment]
edit the file in the EndlessSky.xcodeproj file here on the repo (this will create an up-to-date branch on your repo, e.g. `patch-1`), and paste in the lines from your own, now-fixed file. The web interface should walk you through the rest. To verify you only make the desired changes, make sure you Preview the before you confirm the edit (and use a nice commit name, like `Add Dictionary.* and Visual.* files to the XCode project`).

**Comment by gunqqer** [comment]
#3238 This should be it, but idk
