### ISSUE TITLE
Feature request: Show navigation path on HUD

### ISSUE THREAD

**Issue by timbennett** [endless-sky/endless-sky#3239]
Suggestion: Modify the HUD to display the list of systems on the player's current navigational path. Use text colour to communicate player standing and status icons to denote mission deliveries. 

Example interface:

![endless-sky-navigation-suggestion-2](https://user-images.githubusercontent.com/1192790/33003457-f55c32b0-ce0e-11e7-99a2-3e60533e0362.jpg)

- The player is in Rutilicus
- The player has four jumps plotted, in order: Cebalrai, Rasalhague, Zeta Aquilae, Orvala
- The ship has enough fuel to reach Rasalhague (yellow reactor icon)
- Rasalhague is friendly (blue text) while Zeta Aquilae is hostile (red text)
- The user has a mission terminating in Orvala (blue dot)

**Comment by timbennett** [comment]
Quick comparison with Eve Online, the inspiration for this request:

![eve-online-nav-example](https://user-images.githubusercontent.com/1192790/33003539-61e7c016-ce0f-11e7-810c-eeb2d7e211e0.png)

**Comment by KiLEdEnNis** [comment]
the base concept is nice, but I think the colors should be a bit darker to not stand out, and the fuel/mission icon should change to something more clear
and even then new players would be confused without any info of what that is

**Comment by timbennett** [comment]
The mockup is just a quick example, the main purpose is to communicate route information. And since this list wouldn't show up unless the player had set a route, I think its purpose would be fairly clear from context (for instance, I'd consider the heat gauge more confusing and less relevant to new players).

**Comment by KiLEdEnNis** [comment]
we'll see what others think about the visual part, if it uses understandable icons (like some oil drop for the fuel) it should be easy enough to learn

**Comment by Bladewood** [comment]
What if I had like fifteen jumps planned?

**Comment by timbennett** [comment]
@Bladewood I'd suggest ellipsis, with the omitted jumps popping out as you get closer. 

For example:

```
Menkent
Vega
Sol
... 5 jumps ...
Tejat
Phurad
Canopus (destination)
```

One jump later:
```
Vega
Sol
Sirius
... 3 jumps ...
Miaplacidus
Tejat
Phurad
Canopus (destination)
```

**Comment by jafdy** [comment]
This is going to be very dependent on implementation, as KiLEdEnNis said, using the correct icons will be very important.

**Comment by Amazinite** [comment]
An interesting idea, but I don't think it's necessary. All this information can be quickly gathered by just hitting the map key, viewing your jump path, then closing the map. Endless Sky doesn't have the massive number of systems that EVE has, so the relevant information can be gathered quickly in ES. Also, in ES we can't set a jump path with a waypoint (planet that we land on) in the middle of it; landing points are always at the end of jump paths, and we need to make a new jump path once we launch.

If anything is shown, I think it should only be systems of interest. EVE only shows the name of the current and destination system. We already have the current system shown, as well as the system we are about to enter, so really the only systems I would think are necessary to show are systems with mission destinations, the final destination of the jump path, and possibly the system that you'll run out of fuel in. I don't see showing hostile systems as necessary as there are generally only a small number of hostile systems in ES, and any systems that are hostile are usually on the edge of space (pirate systems or Unfettered Hai) in which case they'll always be the end of a jump path, or they are large regions of space (Sestor and Mereti systems), in which case every system is hostile. There are no practical situations where one would be entering and exiting hostile territory multiple times in a single jump path.

**Comment by endless-sky** [comment]
I feel like this would just clutter up the interface. Also note that the game nearly always uses greyscale text - multi-colored text, especially bright colors, often looks tacky.
