### ISSUE TITLE
Fix: No fines from planets you have subjugated

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#324]
I take the time to destroy their fleet, crush the lives of hundreds of pilots and thousands of crew members, and they have to nerve to charge me 1 M for having nerve gas when I land on their planet to refuel.

**Comment by endless-sky** [comment]
Fixed (2866bcf).

**Comment by thenerdfreak** [comment]
Can confirm that this is fixed, visited every planet under my Green spell and none fined me (but some passing ships from those systems did)

**Comment by thenerdfreak** [comment]
maybe a thing to where once you've dominated 3/4 of that faction, they no longer fine you in general?

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
