### ISSUE TITLE
Excess weapon check in Ship::Load() doesn't remove excess

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#3244]
The check for excess "equipped" weapons in Ship::Load() [(Line 246)](https://github.com/endless-sky/endless-sky/blob/c1b0481b2ae8e581f73bdb7ab54aa5f8f64dda82/source/Ship.cpp#L246) potentially calls Armament::Add() before the outfits have been loaded.

My test case (the marauder manta prior to: https://github.com/endless-sky/endless-sky/commit/888c5c08b232aaa30d9ad57a5d425a1bf597c861 ) showed Armament::Add() returned due to a null pointer for the outfit. 

My gut says to move it to Ship::FinishLoading(), but Ill leave that to someone else in case theres a cleaner way to do it.

**Comment by tehhowch** [comment]
My gut reaction says that it shouldn't need to wait until then, because the act of loading stuff is supposed to make the pointers exist:
```
GameData::Outfits().Get("outfitname")
```
returns a valid pointer for that outfit even if that outfit is in plugin "zzzzzzzzzZTOP"

**Comment by comnom** [comment]
Ah, misread what was going on then. Before the outfit is loaded the outfit->IsWeapon() in Armament::Add must return false instead of the valid pointer check.

**Comment by tehhowch** [comment]
But, you are correct - the check for outfit is valid upon first calling of `GameData::Outfits().Get(...)`, but `outfit->IsWeapon()` sure isn't guaranteed. The 'docstring' for Armament::Add certainly indicates it should not be called from Ship::Load, but rather FinishLoading() as you suggest.

I would change the existing call to print a DataNode trace flagging the excess, and then reimplement it in FinishLoading

**Comment by endless-sky** [comment]
This should be fixed by 182c544.
