### ISSUE TITLE
Compile Error: undefined reference to 'Visual::Move'

### ISSUE THREAD

**Issue by Lineth** [endless-sky/endless-sky#3245]
Compiler does not seem to work. Would post more, but Codeblocks has a nasty habit of freezing rather than allowing me to get any pertinent information.

EDIT:
`undefined reference to 'Visual::Move()'`
`In function void __gnu_cxx::newallocator<Visual>::construct<Visual, Effect const& Point& Angle&>(Visual*, Effect const&, Point&, Point&, Angle&)':`

**Comment by endless-sky** [comment]
What OS are you on?

Is it possible you're not using the latest version of the CodeBlocks project, e.g. because you had made local changes to it and git was not able to merge it automatically?

**Comment by Lineth** [comment]
I installed Codeblocks today on my new PC. Windows 10. Same with MinGW.

**Comment by endless-sky** [comment]
Does it compile if you add `#include "Point.h"` to the top of `Visual.h`? That's the only possible issue I can think of.

**Comment by Lineth** [comment]
Nope.

**Comment by Lineth** [comment]
I should point out that a slightly older build did compile successfully on this system; one from early to mid October.

**Comment by endless-sky** [comment]
Again, have you checked whether your CodeBlocks *project file* (i.e. `EndlessSky.cbp`) is up to date? It sounds to me like you have an outdated project file that just isn't compiling `Visual.cpp`.

**Comment by Lineth** [comment]
Ah, sorry, misunderstood the question (being tired from work will do that I guess.) Seems to work now. Had to delete my old repo and remake it (helps that they 'changed Github desktop for your convenience' and now it's all messed up).
