### ISSUE TITLE
Request: add “medium freighter” category

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3249]
(Hopefully this is the correct place to post, I'm new to endless-sky.)

Currently warships are grouped under “light”, “medium”, or “heavy”, but freighters can only be either “light” or “heavy”, because “medium” does not exist. This leads to weird things, e.g. the Nest, Roost, and Skein are all medium warships, but for their freighter counterparts, the hauler is light and the hauler ii and hauler iii are heavy. Therefore I think a “medium frighter” category should be added.

After looking at the available ships in human space it seems the criterion is the empty mass (i.e. hull plus outfits):
light: <500
medium: 500-1000
heavy: >1000

So what I suggest is:
* `source/Ship.cpp`: 
  * insert at line 49: `"Medium Freighter",`
* `data/hai ships.txt`: 
  * change Water Bug category to "Medium Freighter"
* `data/ships.txt`:
  * change Argosy category to "Medium Freighter"
  * change Bastion mass to 540 and outfit space to 450
  * change Hauler category to "Medium Freighter"
  * change Hauler II category to "Medium Freighter"
  * change Hauler III category to "Medium Freighter"
  * change Modified Argosy category to "Medium Warship"

(If I had commit access I could push these changes myself.)

**Comment by jafdy** [comment]
You can create a pull request.

Why are you changing the Bastion? 
The categories used are fairly arbitrary, especially for non-warships. Although this is an easy change, it feels unnecessary.
(Someone will request the freighter to be made a med is this is accepted.)

**Comment by tehhowch** [comment]
Adding a category just to add a category seems a bit strange. What does this offer?
PS only MZ has commit access - everyone else who wants to submit changes goes through the Pull Request review process, no matter how seasoned of a contributor they are.

**Comment by Nescio0** [comment]
Thank you for your quick replies!
How does the “Pull Request review process” work?

**Comment by jafdy** [comment]
You make a fork of the repository, make a branch on that fork, make changes to that branch and click the pull request button. It then opens a pull request that looks a lot like an issue where we ~~shred~~ examine your ideas and MZ might accept them.

**Comment by gunqqer** [comment]
With changes like this, the community discusses and when MK feels like giving his input, he does, and if he want to merge it, he does. There isn't really a formal process. With bug fixes sometimes he'll look over it and just merge it.

**Comment by tehhowch** [comment]
Browse [this](https://github.com/endless-sky/endless-sky/pulls) and check out some that have many conversation posts. You'll see a back-and-forth where changes are discussed/reviewed, addressed, and justification is provided if needed.
To figure out GitHub, use the internet :grin: Here's a starting link: https://www.atlassian.com/git/tutorials/advanced-overview

**Comment by Nescio0** [comment]
And I've created a pull request, let's continue the discussion over there.
> To figure out GitHub
I'm used to command line `git`, but github isn't that difficult to figure out.

**Comment by jafdy** [comment]
Close this then.

**Comment by tehhowch** [comment]
The discussion behind the change can (should) go in the issue rather than the PR, as the PR can end up not being a good implementation (i.e. better off closed). The general "subjective change" process is Issue -> PR. 
Bugfixes generally don't get an issue unless there are many ways to address it, or someone encountered a maybe-bug/crash before coders recognized a bug exists.
