### ISSUE TITLE
Mechanic: ships breaking up into wreckage you can salvage

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#325]
> Functional Ship

A functional ship can not be boarded or salvaged. However, it can be disabled.

>Disabled

A disabled ship can not move or fire back. 

A engines, weapons and cargo can be looted from the ship without engaging in combat.

Other outfits can be salvaged after some combat with the disabled ship's crew.

The disabled ship can be captured after all enemy crew is killed, or if they surrender.

>Destroyed

If a disabled ship is destroyed, one of the two things happen:

Small ships explode and leave nothing behind. 

Large ships explode into 2 - 3 large chunks. 

Each chunk can be boarded and salvaged. 

No crew survive on the wreckage.

Each item that was on the ship has a 30% chance of surviving on one of the chunks.

The wreckage is very optimized, meaning it is stationary, have no animations and does not make any actions, like asteroids. This allows large amounts of shipwrecks in a system.

Shipwrecks do not despawn, but are very easy to destroy if targeted, and most are quickly worked over by scavengers.

An empty wreak explodes.

**Comment by airtroop392** [comment]
Would be very problematic for the developer, and, by extension, modders, if they had to create 3 different .pngs to represent chunks of their broken up ship in order for the boarding mechanics to properly work.

**Comment by gchapyzh** [comment]
I don't think its very hard. Take the existing ship and turn it into multiple chunks with scorched edges (FTL did the same thing)

**Comment by airtroop392** [comment]
I only ever played FTL on my iPad, so I'm not sure how the PC version handled the destruction of modded, user created ships, but FTL had an art <i>team</i> working on it, whereas Endless Sky just has Michael Zahniser and a couple of people who make pull requests on Github. BTW, this is a close up of a destroyed ship in FTL. 
![image](https://cloud.githubusercontent.com/assets/16041937/11461175/cb6cb604-96cb-11e5-9399-37aa6f89a3c6.png)
They drew detail in between the fragments to show the extent of the damage, and I suppose the dev could easily replicate this by tearing up his ships, but modders would also have to do this, otherwise their fragments would be invisible. Seriously though, can anyone else weigh in here? Is this possible to recreate without needing to separate ship images into three separate .pngs to be shown once the ship explodes?

**Comment by gchapyzh** [comment]
The break-up feature would not have to be necessary. If a modder is lazy, they can just remove the feature from their ship, making it like a small ship: no explosion.

**Comment by Oeleo** [comment]
I don't know if it is possible to do that, but I like the idea. I think that it's the better idea that I rode to replace the actual looting. I wait to see what the creator will think of that.

**Comment by DreamWaker** [comment]
airtroop, simple fix, if no "wreckage" chunks are added to a mod, it uses "default" chunks...

Also, different parts should have different chances to survive the explosion... Could be an added variable (SurvivalChance)

Lastly, Parts of the hulls should be salvageable as well, for the raw metal! (this could also introduce a new system, that allows you to turn ScrapHull into ScrapMetal, and get more value out of blown up hulls.)

**Comment by MCOfficer** [comment]
agreed on the last point. but ships breaking in parts would be an absolute hell for any dev and artist, plus slowing down the implementation of new ships drastically.

**Comment by DreamWaker** [comment]
Not really, as its been stated, they can either "pick apart" the ships (cut the image apart in an image editor) or let the game use some "default" chunks, similar to the general space junk now, only burned and metallic in base look. Its simple enough that even the players themselves could do so!

**Comment by JPaulMora** [comment]
I really like this concept, but I agree it would need a lot of work in new images. Maybe we could use the cargo packages with a different color to represent they are outfits, alternatively make them look like "metallic garbage" and have 3 or 4 variations.

**Comment by Darcman99** [comment]
Personally, i would like to see this as downloadable content (free of course, just like the game itself), to both tag this as a feature much like High DPI that users aren't forced to use, but have the option to if they think they're computer can handle it, also tagging this mechanic as downloadable content for the game could put less pressure on content creators as they won't see it as an essential game feature, just an option.
