### ISSUE TITLE
Wanderer eugenics - only mentioned once, in a logbook entry

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3255]
> Ektasi Rek is the first Wanderer in millennia to undergo the Molt, changing into a completely different species with new capabilities. As more Wanderers go through the Molt, the Wanderers as a whole will have to decide which of these mutations represents the best way for their species to survive and flourish in Korath space.

[While I like the idea of the Wanderers having to decide on the best form for their species](https://steamcommunity.com/app/404410/discussions/0/154643795213214980/?ctp=4#c1474222595301331948), it bothers me that this is only mentioned a single time in the game, and especially only in a logbook entry, written by the player character. I'd think it'd be better if it would either not be mentioned at all (until part 3, at least); or if it at least got a little more attention, beyond the logbook—as in an actual conversation with them, around that point in the story.

(On an unrelated note, it annoys me that that link does not work if I do not explicitly add `https://` to the beginning of it.)

**Comment by endless-sky** [comment]
That's basically what the remaining third of the Wanderer campaign will be about.

And, it's not a eugenics program - as with Rek, the Molt tends to increase whatever abilities a Wanderer is currently most making use of. So, if the Wanderers decide to focus more on diplomacy, when individuals molt they're more likely to gain communication skills and more trusting and peaceful dispositions; if they decide to focus on military strength and warfare, they'll grow larger, stronger, and more courageous.

**Comment by KiLEdEnNis** [comment]
on a semi-related note, any idea around when the 3rd part of their story will be done?

**Comment by Brick63** [comment]
That does raise a question about which one they will choose and if it will be fully based on the present or if they will also think of the future as well
