### ISSUE TITLE
Unintended(?) effect in boarding combat

### ISSUE THREAD

**Issue by Jonathan-Richards** [endless-sky/endless-sky#3256]
Currently boarding combat is primarily determined by the ratio between your power and your opponent's power. Though each ship has both an attack power and a defense power, only one is used per round of combat. The power you use is determined by whether you attack or defend. The power your opponent uses is determined by whether their estimated capture odds are greater than 50% **assuming you defend every round**.

This means that if your defense is significantly lower than your attack, you can "trick" your opponent into attacking. Late game ships tend to have a lot of free defense boosts, so their attack is much lower than their defense. This leads to a weird situation where you are much more likely to win an attack if you remove any defensive bonuses your ship has. This is especially noticeable in bactrian vs world ship fights, where a bactrian with defenses will only kill a few hundred enemies while a bactrian with no defenses will regularly kill all but 20 or so.

It could be argued that this makes sense, as neither defenses come into play if you both decide to attack, but it narratively implies that first thing the enemy captain thinks when you bust the airlocks and start flooding his ship with nerve gas is "Ah, their defenses are low, we can just take their ship" and then he keeps getting confused as to why his crew never makes it to your ship through all the nerve gas.

I'd suggest that attack power should always go up against defense power in the combat calculations. We can keep the ability for both sides to attack at once, it would just mean that fights could involve all 4 powers at once instead of being limited to 2. This would make the enemy's decision making more rational, as they wouldn't repeatedly weaken themselves by attacking despite utterly losing to your counterattack every time.

This would make capturing higher end ships much more difficult. I haven't looked at bactrian vs raider fights, but it might have an impact there.

**Comment by endlesssteve** [comment]
The Bactrian beats the raider every time without any sort of trick.
So this only impacts the Worldship capture. Some players do have a Worldship capture fixation.
Why spoil their day?

**Comment by endless-sky** [comment]
The idea behind the boarding combat mechanic is that both ships decide *simultaneously* whether they're going to attack or defend. That is, it's not that you decide whether you're attacking, and then the AI ship decides how to respond. So, the AI has to make a decision without knowledge of what you are going to do.

**Comment by Jonathan-Richards** [comment]
I get that it is a blind, simultaneous decision. It actually leads to a pretty interesting game-theory problem.

The issue is that the decision is only interesting for the AI, and the game doesn't make an attempt to make that decision in an intelligent manner.

My suggestion still keeps it as a blind, simultaneous decision, but (I think) makes the combat mechanics much more intuitive.

**Comment by KiLEdEnNis** [comment]
the player can predict what the AI is going to choose though, I think adding a small random factor to the AI's decision making would make it more... interesting at least (because right now every AI captain would do the exact same in every situation)
a more complex idea, in addition to adding a small random factor, is making certain governments more prone to attacking (pirates, unfettered) while others would likely defend (merchant)

**Comment by tehhowch** [comment]
That government-level distinction can be somewhat controlled with the government-specific combat attack/defense values.

**Comment by KiLEdEnNis** [comment]
that's just the strength, I mean their actual decision to attack or defend (say merchants will defend a lot while pirates may be reckless and attack)
