### ISSUE TITLE
Question: When boarding, how does the game handle different types of hand to hand weapons?

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#326]
Let's say I have 50 crewmen, and I buy 40 units of nerve gas, 10 units of grenades, and 10 rifles. Would the game automatically select the nerve gas and the grenades for my crewmen to use, or is it handled differently?

**Comment by gchapyzh** [comment]
Each crewmen can carry one weapon. The game automatically gives crewmen the best weapons. In your case, 40 crewmen will have nerve gas, and ten will have grenades.

**Comment by airtroop392** [comment]
Just needed confirmation, thanks. By the way, which data file is this feature in?

**Comment by gchapyzh** [comment]
No idea. Anyone know?

**Comment by airtroop392** [comment]
Well, no idea where it is, but for now, I guess I'm going to close the issue.

**Comment by dplepage** [comment]
The computation of crew power happens in the [`Make` method of CaptureOdds.cpp](https://github.com/endless-sky/endless-sky/blob/master/source/CaptureOdds.cpp#L136).

The [`Calculate` method](https://github.com/endless-sky/endless-sky/blob/master/source/CaptureOdds.cpp#L89) precomputes the capture odds and expected casualties for all possible outcomes, based on the crew power vectors computed in `Make`.
