### ISSUE TITLE
Game crashes repeatedly

### ISSUE THREAD

**Issue by Tyro1953** [endless-sky/endless-sky#3285]
Crashes every 10 to 30  minutes. I get this  error code in windows.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	EndlessSky.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	nvoglv64.DLL
  Fault Module Version:	23.21.13.8831
  Fault Module Timestamp:	5a0b4363
  Exception Code:	40000015
  Exception Offset:	000000000104165f
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	4105
  Additional Information 1:	b24a
  Additional Information 2:	b24a8231b06fb065e11a3bce8a23aa47
  Additional Information 3:	bada
  Additional Information 4:	bada2180eb66d7ca92659ae991790b94

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

I've got a i7-3820 with 16gig of ram.
The video is a Nvidia GTX 660ti with 2gig onboard and 388.13 driver.

Everyone I've chatted to seems to blame Nvidia without any concrete reasons or suggestions.
Anyone have any hints about my next move?

**Comment by tehhowch** [comment]
Are you playing the Steam version? Self-compiled? Downloaded precompiled binary?

**Comment by KiLEdEnNis** [comment]
as far as I know he plays the base Steam version

**Comment by warp-core** [comment]
Someone on the Steam forums a while ago had a similar issue.
http://steamcommunity.com/app/404410/discussions/1/1474222595306157398/
I don't really have anything to contribute other than that link.

**Comment by Wrzlprnft** [comment]
the module name, nvoglv64.dll, is a nvidia thing as far as i know. a quick google search has only brought up the advice to update the drivers, even in the nvidia forums themselves.

you can try to rollback to an older driver or update to a newer one.

**Comment by Tyro1953** [comment]
Thanks for the comments so far. Yes It's the base steam version.
yes I've tried updating. As for the rollback I started with a very old driver ( about a 2years old) and then the crashes started.
I've read warp-core's link and I contributed the zoom theory.....I was just having a good day. It still crashes.
Does a new 1050ti 4gig sound like a reasonable plan?

**Comment by KiLEdEnNis** [comment]
as far as I know ya don't have to get a new graphics card if ya planned that, just update your drivers
although I've never done that so I don't know much more than this

**Comment by Wrzlprnft** [comment]
I want to be totally honest here: yes, there's the chance it will work. but, no guarantee in any way. so, unless you “need an excuse“ to buy a new graphics card anyway, i wouldn't do it just to solve this problem. the game uses OpenGL, and it is up to nvidia to support it :/

**Comment by comnom** [comment]
In your Event Viewer->Windows Logs->System is there by chance a warning/error about a TDR being detected before the crash?

**Comment by Tyro1953** [comment]
ok...checked the event viewer...no TDR.
Only errors were nvidia driver stopping and recovering.
LOL finally lost my patience and bought the damn 1051ti.
Been good for about 2 hours so far. Appears like an intermittent with the 660ti.
Have no idea how to prove that except by time passing.

**Comment by Tyro1953** [comment]
PS: thanks to all for the time and effort.

**Comment by KiLEdEnNis** [comment]
np, whether the new graphics card fixes it or not, tell us on here

**Comment by Tyro1953** [comment]
OK...it's been 2 days and a few hours on the game. It appears the whole problem was the card.
It didn't fail on other applications (including games and Heaven Benchmark ),but couldn't handle the game.
Data transfer for multiple elements?? 
Don't know ,just glad things work. 
Thanks to everyone again. Appreciate the help.

**Comment by KiLEdEnNis** [comment]
so the problem has been resolved? (and I think ya can close this issue if that's the case)
