### ISSUE TITLE
GL_INVALID_OPERATION in glUniform1

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3292]
As I tried to investigate #3291 further, it started printing this error:
```
Mesa: User error: GL_INVALID_OPERATION in glUniform1("tex"@4 is sampler, not uint)
```

For the error to appear I need to enable MESA_DEBUG: `MESA_DEBUG=1 ./endless-sky`
I tracked the error to this line:
https://github.com/endless-sky/endless-sky/blob/bf24759ffd687fc6d74c80062629aad1b1a8ba9f/source/Font.cpp#L471

Since there are two fonts and it only errored for size 14, I tried loading size 18 first and the error appeared for size 18 only. This means the error might be hiding other similar errors.

**Comment by tehhowch** [comment]
I can confirm, I receive this error as well when running `MESA_DEBUG=1 ./endless-sky`

```
glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.3 (Core Profile) Mesa 17.0.7
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.7
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.0.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by flaviojs** [comment]
By reading [this](https://www.khronos.org/opengl/wiki/Sampler_(GLSL)#Binding_textures_to_samplers) I can understand the purpose of the line is to bind the sampler "tex" to texture unit 0 (GL_TEXTURE0).

Changing to `glUniform1i` produces the same error, which means either this is a bug in Mesa3D or there is an alternate way of binding that deprecated this way.

**Comment by flaviojs** [comment]
After reading the Mesa3D source, changing to `glUniform1i` is the correct fix.
The error didn't go away when I changed the Font line because the same error happens here:
 https://github.com/endless-sky/endless-sky/blob/bf24759ffd687fc6d74c80062629aad1b1a8ba9f/source/OutlineShader.cpp#L120

**Comment by tehhowch** [comment]
Do I smell a pr fix? :+1:
