### ISSUE TITLE
Game volume/sounds is/are still REALLY loud

### ISSUE THREAD

**Issue by Lineth** [endless-sky/endless-sky#3299]
So am I the only one who thinks the game effects are near deafeningly noisy? When I first started up the game on my new PC, I fired the lasers on the sparrow for some good old uranium mining to get that loan paid off and it nearly blew my ears out (no it didn't, bit you get my point). For the record, both my speakers and my system sound are set at 50% volume and absolutely everything else I play or listen to is at a sensible volume.

I mean, I have most games set at anywhere between 35 to maxed volume depending on how loud they are, and this one I have at what I guess to be about 5% and it's STILL louder than most. Though it could just be that the laser sounds are REALLY grating. Or both.

**Comment by jafdy** [comment]
Laser sounds are quite grating. As long as it's possible to turn it down far enough (you can use the mixer to get even lower) then this is really a non-issue. If the relative volume of the sounds was out of wack then that would be a problem.

**Comment by endlesssteve** [comment]
I play silent. It is space after all.  I thought there were volume settings in the settings screen? May be the default is too high.

**Comment by KiLEdEnNis** [comment]
I play the game with the sound bar at around 10% and that works fine, to me that full 100% is indeed too loud

**Comment by solardawning** [comment]
I too have to play with the game volume set to 10% or lower.

**Comment by gunqqer** [comment]
When I do play with sound, which is rare, I have it pretty low. Guess it's not just me then

**Comment by endless-sky** [comment]
Addressed in eb5ceb4 by making the volume 4 times lower.

**Comment by KiLEdEnNis** [comment]
*addressed in 006238e
