### ISSUE TITLE
Automatic snapshot lost my hyperdrive

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#33]
After loading the most recent snapshot of my game (i.e. the automatic snapshot done when I left the last station I was landed on), it looks like my ship's hyperdrive disappeared. I don't see it listed in my ship's info, and I can't jump to a new system because I don't have a hyperdrive.

As I'm on a system without outfitter, that's pretty blocking :)

No idea what triggers the bug, but here is the corresponding save file if it might help:
http://remi.verschelde.fr/files/misc/Akuus%20Sargenn.txt

**Comment by akien-mga** [comment]
Might be relevant: I updated my git repo from 60ea22e to 8d8d499 *while* playing, though I did not recompile so the only the data changes should be relevant.

**Comment by endless-sky** [comment]
That's really weird. The data files all get parsed right when the game starts up, so modifying them while you are playing should not make a difference.

**Comment by akien-mga** [comment]
Yes I don't know what happened, I was quite surprised. My only clue is that "Hyperdrive" is the only outfit that is not listed with double quotes in the save file, so maybe it was not parsed properly somehow? It's the very first time I run into this issue though, so it's hard to tell what would be the bug.

**Comment by endless-sky** [comment]
Unfortunately, every time you quit the game it re-saves whatever player file is loaded, so that saved game file you have now may not include whatever corruption was originally introduced.

The data file writer skips using quotes if they aren't necessary (because a name has no spaces in it). But, the reading and writing of data files has been pretty thoroughly tested, so I'm not sure where a bug could crop up. I could try writing a program to repeatedly load and save player files just to see if there are intermittent bugs.

**Comment by akien-mga** [comment]
Note that I did not quit the game actually, I was unhappy with how my bounty hunting was going, so I went to the main menu, the load/save menu and reloaded the automatic snapshot, and the one I've uploaded is this same snapshot.

**Comment by kilobyte** [comment]
It happened to me, too.  I lost most of the ship's outfits: Jump Drive, 2 Korath Warders, Korath Heat Shunt, ramscoop, a bunch of fuel pods, and probably more I don't remember.
Save file: https://angband.pl/tmp/corrupted_outfits.txt

**Comment by kilobyte** [comment]
I don't have a recent save, but comparing an elder one, this is what I think I am missing:
```
                "Laser Rifle" 100
                "Fragmentation Grenades" 100
                "Jump Drive"
                "Korath Warder" 2
                "Korath Heat Shunt"
                "Ramscoop"
                "Fuel Pod" 5
```

**Comment by endless-sky** [comment]
Was it the same situation akien-mga saw, where this happened when you reloaded the game through the Load / Save panel?

**Comment by kilobyte** [comment]
Yeah.

**Comment by endless-sky** [comment]
When you reload your game, do you click on the "Load / Save..." button, or
do you use the keyboard shortcuts (e.g. "Esc L E D" to quickly Load, Enter
Ship, and Depart)? I've found a possible explanation, but it would only be
possible if you reload your game within a fraction of a second of when you
call up the main menu, i.e. while the game engine is still doing
calculations in the background for the last frame.

**Comment by kilobyte** [comment]
I don't remember which way I used (I use the mouse sometimes, keyboard shortcuts sometimes), but I'm pretty certain I did not hurry that much.  The only times this would be possible for me is when I'm retrying some hard mission -- here at the time I lazily mapped parts of the galaxy after doing some Korath farming.

**Comment by endless-sky** [comment]
The only thing I can think of that might cause this is some sort of race condition between the graphics thread and the "engine" thread. So, I went through and tightened up thread safety everywhere I could (a4cdd68). But unfortunately this seems like such an intermittent error that it's hard to prove that that fixed it.

**Comment by knope** [comment]
this happened to my ship as well.  (Star barge) i was about 1 planet away from my mission goal when pirates killed me.  I reloaded my snapshot, and found the hyperdrive was missing.  (then i found i could manually edit my save file... so i attempted to add the Hyperdrive back in... how ever, the game loads the save file and removes it. (i'm editing the files with the game not running. any other changes seem to stick... however the game just doesn't want me to have a hyperdrive for some reason.  (i'm testing this on version 0.8.4)

ship "Star Barge"
...
    outfits
        "D94-YV Shield Generator"
        "nGVF-BB Fuel Cell"
        "LP036a Battery Pack"
        "Chipmunk Plasma Thruster"
        "Chipmunk Plasma Steering
...
    position 555.12619 -101.0842
...
    system "Kaus Borealis"
...

the terribly upsetting thing is this planet doesn't even have a proper Outfiter... i suppose i could add one ... and probably will... i've already completed several missions and am thoroughly enjoying the progress.   either way thanks for the game.
 :)

**Comment by endless-sky** [comment]
No one has reported this bug in months, so I'm relatively confident that it was just a result of the bug where the effect of being plundered did not become apparent until you reload your game.
