### ISSUE TITLE
Scanner ranges

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3302]
Should scanners measure from the center of the player's flagship, or from the exterior?

This applies to:
 - Tactical Scans
 - Asteroid Scanning
 - Cargo Scans
 - Outfit Scans
 - future scans

Currently, the distance is measured from center to center, for both ships, while the effective distance (mask to mask) can be considerably shorter or even overlapping.
For comparison, weapons (which also have an associated range check) know where on the ship they are located, and check if they will hit the outline of the targeted ship, and not just the center.

Proposal: alter the scanning range checks from `center-to-center` to `mask-to-mask`, or `mask-to-center`, range checks. I think `mask-to-center` is the most sensible, as one probably needs to scan more than just the edge of a ship to learn what is in its cargo hold, etc.

Thoughts?

**Comment by KiLEdEnNis** [comment]
when reading this, before I read your proposal I thought about mask-to-center for the exact same reason as you stated, and this is about as realistic as we can make it, so I agree

**Comment by Amazinite** [comment]
So instead of the scan range being in a circle around your ship, it's in a ship-shaped mass around your ship? Sounds like that would be fun to look at if our scan range was visible.

Honestly, I think that center-to-center is fine. The scanner is only on one part of your ship, not on every part. Sure, that part might not be the exact center (and I'm not proposing that we make scanner slots for ships, or cause scanners to take up turret space), but the center is still a single point where the scan is emanating from, instead of the scanner somehow being omnipresent across the entire hull of your ship.

**Comment by gunqqer** [comment]
Now if we want to get complicated, it could be from your center to greater than like 40-50% of the target ship so not the entire ship has to be in range, but some of it.

I feel like that'd be too complicated

**Comment by tehhowch** [comment]
>So instead of the scan range being in a circle around your ship, it's in a ship-shaped mass around your ship?
Yep, basically anything within `X` of your ship's outline, rather than within `X` of the center of your ship. An overlay indicating scan range could be neat, but as you mention would probably necessitate defining a scanner point.

> if we want to get complicated, it could be from your center to greater than like 40-50% of the target ship so not the entire ship has to be in range, but some of it.
>
>I feel like that'd be too complicated

And I agree. For the most part, measuring to the target's center will mean that 40-50% of it is covered by scannable area.

**Comment by jafdy** [comment]
It wouldn't be ship-shaped, think of a long thin ship (1D for the arguments sake), every point that is within range of the edge of this sprite would form an area with two semicircular ends (centered on the ends of our line-ship) with a large rectangular block in the middle. 
So a scanner equipped Carrier would not have a Carrier shaped scan area (funny as that would be) instead it would get mostly a circle with a few slightly misshapen bit around the edge. It would only start being Carrier shaped when the scan range is really short, and up till then, size would just be a slight range buff.

Personally I see nothing wrong with either approach, I just need to ask, is this really going to help.

**Comment by tehhowch** [comment]
Changing to an "external" scan origin brings the visual observation of distance in line with the displayed distance. If your ship's bow is touching the target ship, your range to target should probably not say "150" - it should say something on the order of 0.

It's conceivable that - even for a centrally located scanner - the software that runs it knows the bounds of your ship, and reports the distance from your ship to the target, not from the scanner to the target.

**Comment by jafdy** [comment]
Ooo, I forgot about that commit. In terms of distance displayed it should probably be `mask to mask` so that when two ships appear to touch then the game says distance is 0. As I said before, it is quite minor the difference when your not dealing with very short ranges.

**Comment by tehhowch** [comment]
`mask-to-mask` also wasn't chosen because it isn't really possible at the moment.
The current method used, Mask::Range, checks every point on the outline for the range to the desired point. `mask-to-mask` requires checking the distance between every point in this mask and every point on the other mask -- I'm gonna try to avoid adding o(n^2) methods to this game :grin:

**Comment by jafdy** [comment]
You might be able to cheat and look at the bits of the mask along the line joining center to center. Mathematically that is a very good way to simplify the problem, I have no idea what it would take to code.

**Comment by tehhowch** [comment]
True, only half the points in the outline need to be checked to account for protrusions. Gets a little funky for ships like this one: ![image](http://starwarsblog.starwars.com/wp-content/uploads/2015/05/Saakak.jpg)

I think the method would need to look at all points between the outermost points that are intersected by the plane which has a surface normal that points from center_1 to center_2, choosing the inspection direction such that the points are on the positive side of that plane.

I did speak a little too soon, as an existing method kinda does exist in `Mask::Radius`. However, using it to compute an offset for the `center-to-center` range (i.e. subtracting each mask's radius from the distance) won't give the correct result for long & skinny ships (of which ES has many, #1814) when they are facing the same direction, as it returns the maximum distance from its center. However, it is a cached quantity computed during game load, and thus is O(1) for any mask.

**Comment by endless-sky** [comment]
This doesn't seem like a worthwhile change to me. Center-to-center distance is a pretty simple concept that should make sense to people. And scanners that have a circular range - even if the point in the ship that the circle is centered on is limited to always being the ship's rotational center - make a lot more sense than scanners with an irregularly shaped scan area. In particular, an irregular area would mean that a stationary ship would be able to change its scanner range just by rotating in place, rather thn by moving closer to the target.
