### ISSUE TITLE
S-270 and S-970 still present

### ISSUE THREAD

**Issue by jmickiewicz** [endless-sky/endless-sky#3308]
These two shield generators seem to have been replaced in Hai space, but are still present on bounty pirates and some opposition during the Free Words story. 

The performance difference is minor enough that I can't believe it is an intentional balance issue, but the S-*70 seem situationally slightly better so I'm tempted to farm pirates which is obnoxious.

**Comment by Amazinite** [comment]
The S-270 and S-970 shield generators are unlocked by doing the Checkmate branch of the FW campaign, and it is intentional that they can be found on certain Marauder ships.
