### ISSUE TITLE
Kestrel shows up before it's unlocked

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#331]
I just started a new pilot yesterday and I haven't even really started the campaign, but I've seen kestrels flying around.  They shouldn't be around until I've completed the mission to unlock them, right?

**Comment by airtroop392** [comment]
Was the ship named Michael Zahniser? The author put in himself as a ship pilot, and he flies around in a Kestrel. I don't believe there should be any other Kestrels supposed to be flying around.

**Comment by johndh** [comment]
@airtroop392 I'll keep an eye out next time I see it.

**Comment by thenerdfreak** [comment]
I seen the kestrel named Michael Zahniser too. killed it because I wanted the ship. My quarg outfits instantly vaporized it
