### ISSUE TITLE
How much is a credit worth in dollars

### ISSUE THREAD

**Issue by Brick63** [endless-sky/endless-sky#3310]
1 mass of platinum = 10000 CR and assuming 1 mass = 1 ton(metric first then US). 
the current price of 1 kilo of platinum is $30,620.35
1 ton = 1000 kilos
so that means that 1 CR = $3062.04(metric)
or 1 CR = $2777.83(us)
i also did gold and the price was nearly double that of platinum so i would appreciate some clarification

**Comment by tehhowch** [comment]
I don't think we can apply our currency to 1,000 years into the future, given that our currency's worth is essentially arbitrary, and because space has a different resource distribution that earth does. What's the number going to be used for?

**Comment by Brick63** [comment]
nothing really but it would be good to know as it would put several things into perspective, also i agree that these may not fully apply to 1000 years from now but with current numbers it makes it seem like the average crew member gets paid hundreds of thousands of dollars a day

**Comment by Bladewood** [comment]
Some things are to be left to the player's imagination.

**Comment by KiLEdEnNis** [comment]
can ya please just keep it at "the old currencies got removed and we now use credits which can't be compared to the old currencies"?

**Comment by Nechochwen-D** [comment]
Everyone uses cryptocurrencies.

**Comment by Amazinite** [comment]
>i would appreciate some clarification

How about this: #1139

**Comment by Brick63** [comment]
okay
