### ISSUE TITLE
Republic Reputation 1 persists after "start of hostilities"

### ISSUE THREAD

**Issue by mootootwo** [endless-sky/endless-sky#3317]
There is an odd gap between "FW Prisoner Parole 1" and "FW Prisoner Parole 2" where Event "start of hostilities" triggers after 7 days (correctly) but you still have a positive Republic reputation until completing "FW Prisoner Parole 2"

I believe this is because the reputation changes that occur with "Start of Hostilities" is defined in the missions "Defend Sabik" and "FW Prisoner Parole 1".

I suggest moving that reputation change into the event, if possible, so that the republic will become properly hostile to you after the cease-fire expires.

If "Defend Sabik" and "FW Prisoner Parole 2" do need to have different levels of reputation change (current is -10 and -1000) then the -10 could be encoded in the event and the -1000 could remain at the end of "FW Prisoner Parole 2" -- or two events could be created.

**Comment by mootootwo** [comment]
The upshot of this is that you can fly around republic space with impunity, and indefinitely, until you go back to Deep to complete "FW Prisoner Parole 2".

**Comment by tehhowch** [comment]
>with impunity

They'll still punish you if you do something wrong, so 'with impunity' is not correct.

**Comment by tehhowch** [comment]
The`start of hostilities` event refers only to the relationship between the Free Worlds and the Republic so bundling a player rep change into it should not be done - other storylines may use this same event and probably should not have the associated player rep change, even though the Free Worlds should be at war with the Republic.

Per https://github.com/endless-sky/endless-sky/issues/264#issuecomment-159800618 we can infer that if you are not being an enemy you get a bit of leeway. 

Currently your mission escorts are of the Escort government, so they won't incur the hostilities either (even though they probably should be Free Worlds). I believe this was changed and then reverted previously.

**Comment by mootootwo** [comment]
I'm not sure why it is assumed to be different from player rep -- player rep was set to negative as soon as they join FW and they are still in the FW when hostilities resume.  

Rep is again set negative (even MORE negative) after the player lands, but they have not done anything to further anger the republic.

Part of the dramatic arc on the mission chain is the race against the clock -- or at least a tight deadline with no room for dawdling.  Instead I can meander up to the Deep and buy some atomic engines.  Seems unintended.

Based on the comment you linked, it is reasonable to assume that the -10 and -1000 rep changes are intentional and should be preserved, so that it is easier to regain your good graces before the hostage exchange, but I think the resumed hostilities deadline should still apply to you and your escorts.

**Comment by tehhowch** [comment]
I've opened #3318 which addresses the ability of the player to gallivant about after delivering the POWs to New Tibet.

**Comment by mootootwo** [comment]
I've opened #3322 as an alternate solution.  See what you think?

**Comment by endless-sky** [comment]
Addressed by merging #3322.
