### ISSUE TITLE
Bug: Wrong hotkey for "Install"

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#332]
On the outfitter panel, when you inspect an outfit you have in cargo, the "buy" button turns into an "install" button. Pressing ALT underlines the "I" in install, but "I" does nothing - the button is still triggered by "B".

**Comment by endless-sky** [comment]
I've added "i" as an alternative hotkey in the shops (commit 5c56db2).

**Comment by dplepage** [comment]
Thanks! I'm unclear on the issue workflow for this repo - am I allowed to close this issue, or is someone else expected to do that? (also, are things like that documented somewhere?)

**Comment by endless-sky** [comment]
If you think your issue has been dealt with, you can go ahead and close it.
I usually don't close an issue that someone else created unless it's been
idle for a few weeks, just to make sure I'm not declaring the issue fixed
when the originator does not think it is.

And yes, I suppose I should add a note somewhere that explains that.

**Comment by dplepage** [comment]
Thanks!
