### ISSUE TITLE
Aid shipment to Unfettered

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3320]
The Hai jobs to deliver aid to Unfettered planets in Hai space are quite profitable; however, when the Unfettered have gained planets in Wanderer space as well, the majority of aid deliveries is directed towards there. Unfortunately the reward is neglible: 5,000 to 7,000 per shipment, probably because there is no direct route. Maybe the payment calculations could take jump connections into account?

**Comment by tehhowch** [comment]
duplicate issue:
related:
https://github.com/endless-sky/endless-sky/issues/3163
https://github.com/endless-sky/endless-sky/issues/1918

**Comment by Amazinite** [comment]
Those jobs were never suppose to have destinations in occupied Wanderer systems, anyway. See #3324 for the fix.

**Comment by endless-sky** [comment]
Addressed by merging #3324.
