### ISSUE TITLE
Outfitter/Shipyard side-panel

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3326]
It would be nice if the ship icons in the outfitter and shipyard side panel on the right would become automatically smaller if you have a large number of ships. E.g. if you have more than fifty, display ten ships per row, instead of four.
Attached a screenshot; because of my 100 deep rivers I can no longer select a ship and simultaneously view its stats:
![screenshot from 2017-12-01 22-13-52](https://user-images.githubusercontent.com/21634324/33504085-5e9c87d6-d6e6-11e7-950e-6d9dadf5585d.png)

**Comment by KiLEdEnNis** [comment]
I don't think putting 10 ships in 1 row is gonna make it better though; it'll get very cluttered & messy and a lot of people might not want this
my only problem is that the ship stats are in the same big column as all the ships, so ya HAVE to scroll to see the ship stats: they should be separated, so no matter how many ships ya have, ya can always easily see the stats of one
(maybe later on we could also add some button on the ship list that enlarges it (or even opens a small menu like the I screen), so ya can see a lot more ships at once, which basically gives ya what ya are asking for as well)

**Comment by jafdy** [comment]
I suppose you could put 6 in a row, but any more than that and it will likely start to get on people nerves. Also, as the main focus is on single ship or small fleets, things for very large fleets are likely to be low priority.

**Comment by KiLEdEnNis** [comment]
I wouldn't really go for 6 ships per row either, it just makes the problem start at a higher amount
I think my solutions should make bigger fleet players happy, and it doesn't really change anything for small fleet players, and it works no matter how big the fleet is

**Comment by tehhowch** [comment]
Relevant: https://github.com/endless-sky/endless-sky/issues/500

There's no reason to consider only solutions which preserve the current layout. Those in the community with "art skills" can consider making single-image mockups of the layout to see which poll better, and when some good ideas are found, recruit someone who can implement the code.

**Comment by Amazinite** [comment]
How about something like this? Your ships are listed on the right side in rows of 3. To the left of that is where the stats display.
![example](https://user-images.githubusercontent.com/17688683/33512837-a626ddf4-d704-11e7-9c41-f76f148ec6b8.png)

The Buy | Sell | Leave buttons are a little close together and create a substantial amount of empty space in that corner, but otherwise I think something like this could work out.

**Comment by Nescio0** [comment]
Separating the ship details and putting it in a separate panel to the left (or right) of the fleet panel would work for me. In that case I'd prefer to keep the width of the buy|sell|leave panel unchanged, and put it below the ship details, but not below the fleet overview.

Independently, I'd also prefer five ships per row by default, instead of three, four, or six, because Shift multiplies by 5 and because 5, 10, 15, 20 is better compatible with our decimal system than 4, 8, 12, 16. I have no opinion on how large each ship icon exactly has to be (shrinking icon sizes and widening the panel width are both viable options).

**Comment by jafdy** [comment]
This will make it harder for people with smaller screens as well, It could push the shipyard down to just 1 or 2 columns.

**Comment by tehhowch** [comment]
Maybe two-image mockups then, at 1024x768 and 1920x1080 :grin:

Its definitely possible to scale the tiled outfit or ship image on the left, but the text cannot be so freely resized, so keep that in mind.
A second caveat is that both the Shipyard and outfitter share the same fleet display section. An ideal solution will work for both.

**Comment by Nescio0** [comment]
It means sacrificing one shipyard column or two outfitter columns, yes. I don't know how this will work out on small screens (is 1024×768 a small screen?), it also depends on the zoom factor. 960×540 at 50% zoom is equivalent to 1920×1080 at 100% zoom or 3840×2160 at 200% zoom.

**Comment by tehhowch** [comment]
I consider 1024 x 768 to be the minimum supported effective resolution, and even it has some clipping in the Map panel so a more true "minimum" effective is ~1080 x 768. The game will outright reject screens smaller than 640 x 480, and forces UI zoom of 100% if the vertical height is less than 700 px.

**Comment by jafdy** [comment]
Yeah, having that large empty box would be strange if you have a fleet smaller than 20 or 30 ships (so most people most of the time).

**Comment by AdamKauffman** [comment]
For the shipyard screen I would make a whole new screen for selling ships and remove the current ship list from the buying page. The selling page would show a ship detail, like seen in the "Ship Info" Panel, with ship selection on the right. You could see full details of the selected ship you are about to sell. On the buying screen you would have more room to show details of the ship you are about to buy.

**Comment by Amazinite** [comment]
This issue has been duplicated by #5143, which includes a pretty good solution and mockup. For the sake of cleaning up issues, I'm going to close this one and leave that one open.
