### ISSUE TITLE
[Suggestion] Improve Outfitter UI using colored text

### ISSUE THREAD

**Issue by TheDujin** [endless-sky/endless-sky#3338]
Hi there,

When managing ship equipment in Outfitter, it gets annoying trying to differentiate between "installed", "in stock", and "in cargo" modules:
![image](https://user-images.githubusercontent.com/12126984/33520139-b70821fe-d769-11e7-8f28-3df9df2a1085.png)
When multiple ships are being managed, or when a big ship with a lot of modules are being managed, it becomes hard to tell what's installed and what's not. A simple improvement would be to color the text (kind of like "git status" colors its text). For example, "installed" could be colored green, "in stock/not sold here" could be colored yellow, and "in cargo" could be colored white.

**Comment by jafdy** [comment]
In general bright colours are avoided so as to avoid a tacky looking ui. With a bit of practice you will learn how to read the numbers accurately without needing to refer back to the text every time, and it's something you will pick up without effort.

**Comment by tehhowch** [comment]
While it only would apply to the selected module, something like #2675 could be of some assistance. (Feel free to chime in on that PR if you have any suggestions relevant to it.)

**Comment by TheDujin** [comment]
Oh okay. Will close this.
