### ISSUE TITLE
support weapons

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#334]
This game is amazing but after the few weeks Ive noticed something missing: support weapons. An idea I have for is a shield lender (name not final). It siphons your shield and sends it to an ally, but it's not 100% and some is lost in the process and cost a fair bit of energy. On the other hand, pirates may modify this into a shield siphoner. Requiring more energy and alot less efficient.

**Comment by thenerdfreak** [comment]
Prolly just be best to wait until other aliens are released and add this as a laser-type weapon. Does moderate damage and has a %shieldsteal

**Comment by endless-sky** [comment]
It would take a lot of work to get the AI to support this, and the end result would make it way too easy to have an indestructible flagship just by having a fleet of escorts giving you shield boosts. It *is* possible to make weapons that heal their target, but adding such weapons to the main game is not something I'm going to work on right now.
