### ISSUE TITLE
"require <outfit>" needs to be in an "on" block; should be able to put it in "to offer" instead

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3341]
This feels weird:

```
to offer
		random < 50
on offer
		require "Brig"
```

I feel like this would intuitively make more sense:

```
to offer
		random < 50
		require "Brig"
```

It would also let you do something like this, which currently isn't possible:
```
to offer
	or
		and
			require not "Brig"
			random < 75
		and
			require "Brig"
			random < 10
```

**Comment by VonZorch** [comment]
Fully agree, it should be testable in a branch statement too.

**Comment by Amazinite** [comment]
Looks like this is actually a duplicate of #2494.
