### ISSUE TITLE
Escort mission bug (Give me the money!)

### ISSUE THREAD

**Issue by DrBlight** [endless-sky/endless-sky#3349]
So I've noticed a bug in the escort missions (I'm playing with the game compiled from git master). Sometimes I'll land on the planet with the escorted ship in tow, only to be told that I left it behind! I'll take off again and make sure it's there orbiting the planet with me, but no amount of taking off and landing will make it recognize the ship. Even the mission marker will be darkened.

This only happens some of the time, so I did some experimenting and I believe it's triggered whenever the escort ship has been disabled and repaired more than once. The only solution is to abort the mission.
![escortbug-map](https://user-images.githubusercontent.com/33576732/33528995-0575b0dc-d827-11e7-8a08-ec80756c1130.png)
![escortbug-message](https://user-images.githubusercontent.com/33576732/33529008-4a9f1432-d827-11e7-901e-af85e2d56d68.png)
![escortbug-ship](https://user-images.githubusercontent.com/33576732/33529009-4e8b7658-d827-11e7-9e15-47dfc27b034f.png)

**Comment by Amazinite** [comment]
I've experienced this only once before but I hadn't investigated deeper. I do recall that the one time it occurred, I had taken 3 escort jobs and one of my escorts was disabled.

**Comment by tehhowch** [comment]
This is likely related to https://github.com/endless-sky/endless-sky/pull/2859

I thought I had made the needed adjustments for this situation but perhaps not.

**Comment by tehhowch** [comment]
Reproduced this issue in an Escort mission in which an NPC repaired the mission NPC I was escorting.
Will see about a fix.

**Comment by tehhowch** [comment]
This is the issue:
https://github.com/endless-sky/endless-sky/blob/224e62f563a55fc57e20b2e851a945836378bd0f/source/Ship.cpp#L1472

The generation of ShipEvent::BOARD and ShipEvent::ASSIST occurs here:
https://github.com/endless-sky/endless-sky/blob/224e62f563a55fc57e20b2e851a945836378bd0f/source/Engine.cpp#L1324-L1330

So if the ship that does the repairing belongs to anyone other than the player's government, then no ShipEvent is even created.

**Comment by tehhowch** [comment]
Should be addressed by #3357

**Comment by DrBlight** [comment]
Thanks!
