### ISSUE TITLE
"Occupy Zeta Aquilae" fails if any ship in my fleet dies

### ISSUE THREAD

**Issue by bluss** [endless-sky/endless-sky#3354]
This is a mission that has 2 passengers, and it seems like if any ship is destroyed in the fleet (doesn't matter which), the mission is failed. I expect that some ships can be lost.

Additional note: It's really easy to miss the mission failure information during a big battle, or maybe  you don't notice it at all until afterwards -- and then there's no way (?) to even see the explanation again.

It's really an awesome game, so thanks a lot for making it.

game version: v0.9.8-246-g31933cb3 (commit 31933cb3)

**Comment by tehhowch** [comment]
There are quite a few ships in that convoy
https://github.com/endless-sky/endless-sky/blob/8a87be12c9cc72af240d47ecab199eeb6d00ad4b/data/free%20worlds%20middle.txt#L1734-L1765
None of them are labeled `save` so they can be freely destroyed without causing the mission to fail

Regarding the mission failure info - please open as a separate issue and request something like an "Alert panel" in which "important" messages such as mission failed, ship captured, ship destroyed, etc are kept, and possibly viewable from the Player Info Panel, much like the logbook can be viewed.

**Comment by tehhowch** [comment]
Can you provide your save file for this mission?

**Comment by bluss** [comment]
Sorry I should be clear. I mean parts of my regular fleet (my ships) are dying, and it doesn't matter which ship, the mission fails. I've already worked around it and the save is posted at the following link; just jump into the Z. Aquilae system and let any ship die to see the failure. https://gist.github.com/bluss/6587944bf49386a12ba1f4ea70e85ad6

**Comment by tehhowch** [comment]
Replicated with your save and the current master, 224e62f563

**Comment by tehhowch** [comment]
Traced to this commit: https://github.com/endless-sky/endless-sky/commit/8e0d8167403de689132a08406b9d7f3211beebf4

Essentially my thought is that your mission passengers are getting copied to your escorts, or the Cargo reference returned by your destroyed ship points to one in which the mission passengers are still held. Thus, the mission is failed as the game thinks the passengers died.

**Comment by tehhowch** [comment]
Fixed with #3367

**Comment by bluss** [comment]
Cool, nice work
