### ISSUE TITLE
Grammatical Error in Wanderer Capital description

### ISSUE THREAD

**Issue by themightygrunt** [endless-sky/endless-sky#3355]
"The **streets in Wanderer capital city** seem to be mostly reserved for cargo vehicles; the Wanderers themselves fly from one building to another instead, and the skyscrapers have balconies dozens of stories above the ground where visitors can land or take off. The air traffic seems utterly chaotic, but somehow they avoid colliding with each other in midair, and certain columns of airspace have been reserved for ships taking off and landing so that flying Wanderers will not get caught in the backwash from the ship engines."
(Vara K'chrai spaceport description)

Should be "The streets in the Wanderer capital city"

**Comment by endless-sky** [comment]
Fixed in 2d2ca55.

**Comment by themightygrunt** [comment]
\o/
