### ISSUE TITLE
restocking ships where ammo is unavailable

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#336]
After doing some missions in hai space, and acquiring a hawk, I decided to park all ships and go and retrieve a fuel for my new hawk. When visiting an outfitter to buy a pod it asked me to refill my ammo. I had no launchers on my ship or or any any guns. Returning, I found they were refilled.
They only had meteors and sidwinders

**Comment by endless-sky** [comment]
Are you running 0.8.7? This should be fixed in 0.8.8.

**Comment by brick96** [comment]
Closing due to steam not updating

**Comment by brick96** [comment]
Unrelated note: I had to opt in for the beta to update to 0.8.8. Opting out reverts back to 0.8.7
