### ISSUE TITLE
Feature request: A key combination that dispays the missions on the maps directly

### ISSUE THREAD

**Issue by bluss** [endless-sky/endless-sky#3362]
It would be great with a key combination that dispays the missions on the maps directly, which doesn't exist (unless I'm missing something?)

Since M is already for the map, Shift + M could open the map in the missions view. With intention of checking the status of active missions (including checking *if* there are any active missions).

**Comment by tehhowch** [comment]
M then I does this, as does I then M.
Two keys in those cases, as well as your proposal.

**Comment by bluss** [comment]
That's good, we need to start with what there already is. I believe this is not documented and I had evidently not found it.

For example here: https://github.com/endless-sky/endless-sky/wiki/PlayersManual#key-bindings-and-shortcuts

**Comment by jafdy** [comment]
You can also press M and then click the missions button in the lower right corner.

**Comment by tehhowch** [comment]
If you hold down the Alt button on menus, the keyboard shortcut for any available buttons is underlined :+1:
With the Map panel open, I is the keyboard shortcut for the Missions pane, (and S for Shipyards, O for Outfitters, P for 'ports' e.g. the 'normal' map mode.
With the Player Info Panel open, both I and M are shortcuts to the Missions button (I'd actually like to make M open the 'normal' map mode and have 'i' be the shortcut to the map's mission mode, but that's an idea for a different issue).

(There are a lot of wiki updates we'd like to make, but we can't PR to the wiki unfortunately.)

**Comment by bluss** [comment]
From my side, please go ahead an close this issue if you want -- there is a shortcut (M, I) that I didn't know.
