### ISSUE TITLE
Weapon projectile sprites and jump drive jump particles not appearing on OSX

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#3365]
Weapons fire, they hit, do damage, etc, but you cannot see them. I am on the master branch with the recent commit (6fb4f5e) that just let the game compile on OSX. Projectiles and their hit sprites do not show, nor does the jump drive purple particles.

**Comment by BookOwl** [comment]
Same thing is happening to me on OSX 10.11.6 with a build compiled from the latest commit

**Comment by tehhowch** [comment]
(Share graphics details and drivers)

**Comment by gunqqer** [comment]
I am using the default OS X graphics drivers, but when I get home I can test with NIVIDIA ones, although I do not know if they've updated

**Comment by BookOwl** [comment]
[Here is a screen recording of the bug](https://www.youtube.com/watch?v=68U_k0eMdSk)
I'm running Intel Iris Graphics 6100 1536 MB with default drivers on my Macbook Pro running OSX 10.11.6

**Comment by gunqqer** [comment]
I can also post a video if you want, but it will be a solid 2-3 fps, screen recordings destroy my computer 

I have a GeForce 8600M GT 256MB

**Comment by endless-sky** [comment]
If you run the game from the command line, are there any messages? It sounds like the new batch-mode OpenGL shader is not working, for some reason.

**Comment by endless-sky** [comment]
It looks like handing `glVertexAttribPointer()` a pointer to an array in main memory is supported by some OpenGL drivers but not others. See if commit 406c34e fixes this for you.

**Comment by gunqqer** [comment]
Just tested it, seems like it fixed it but I'll wait until I get confirmation from another user to close the issue
