### ISSUE TITLE
Capitalization of cardinal directions and areas of space

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#3374]
After reading the text for the founding of the Oathkeepers:

> 	`When you land on <origin>, it seems that everyone in the spaceport is talking about a recent news story: the Navy has just announced the formation of a new regiment, called the Oathkeepers. This regiment is staffed mostly by prisoners you paroled from Kornephoros, who want to honor their oath to take no further part in the conflict against the Free Worlds. They will be headquartered on Farpoint, in the far north, to defend that region of space against pirate incursions.`
			`	Furthermore, the leader of the Oathkeepers will be Admiral Danforth, an elderly admiral who is something of a folk hero and is spoken of with admiration and respect even here in Free space. Although he was not one of the paroled prisoners, he has become an outspoken advocate for a diplomatic solution to the Free Worlds conflict.`
			`	It's heartening news, but you also can't help noticing how many people in the spaceport are talking now about how the Navy really is full of "decent" and "honorable" people, and it's a shame that the Free Worlds had to fight them. By responding to your generous gesture with one of their own, the Navy has won a definite political victory, and given that they needed to defend the North anyway, it is a victory that cost them very little.`

I became a bit confused on what the capitalization rules were. On the one hand, 'far north' is left undercase despite feeling to me at least like an actual region, while 'the North' seems to be in the same situation but is capitalized (and not even on 'the').

I know for sure that there are other places where this occurs, and while I can't come up with them off the top of my head, how should the cases be for future referencing?

**Comment by Nescio0** [comment]
A simple `grep` shows "North " is used in four mission descriptions, and "north " in a few dozen. 
In general usage it's uncapitalized if it's used as a direction and capitalized if it's part of a name. You're right it appears ES does not do this consistently.

**Comment by endless-sky** [comment]
In general, "North" should be capitalized when referring to the region of space. In a few cases, it's ambiguous whether the speaker is referring to the direction or the region of space, but I don't see any cases where the capitalization is definitely incorrect.
