### ISSUE TITLE
Mission enemies clumping and not actively attacking or fleeing

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#3377]
I'm experiencing this in the FW missions where you are suppossed to patrol systems for republic ships. It has happened in the wanderer missions too, a reload somtimes helps. They basically act as if I am their "owner" and will drift into formation around me even. I am in the current git build. It is an old save, but the wanderer missions was a new file.

**Comment by tehhowch** [comment]
Specific missions & your save file let us check which personality traits, if any, are causing this (and verify a fix is working). New PRs merged today (though nothing that modified ship AI), so be sure to share the commit on which your build is based.

**Comment by SirStigII** [comment]
Yeah I posted this and then saw there were more commits, I'll test it again tonight and upload my pilot file.

**Comment by SirStigII** [comment]
[Jake Brake~3021-12-27.txt](https://github.com/endless-sky/endless-sky/files/1550209/Jake.Brake.3021-12-27.txt)
found an instance where the enemy fleet isn't attacking.

**Comment by tehhowch** [comment]
I jumped in and the Republic ships in the mission's system attacked straightaway... not sure I see any issues there

**Comment by SirStigII** [comment]
hmm interesting, must be something on my end. they just sit facing northwest
