### ISSUE TITLE
Unable to jump - J key selects the next system rather than beginning travel.

### ISSUE THREAD

**Issue by nfriedly** [endless-sky/endless-sky#3382]
Hey, I'm new here and maybe I'm not getting something, but when I do this:

> To set a hyperspace target, press the map key (‘M’ by default) to call up the map, and click on your destination. If it is connected to the current system by known hyperspace links, the shortest known path to that system will be displayed. Otherwise, you will need to explore in that direction by traveling along known links until you find your way to your destination.
> ...
> Once you have set a hyperspace route, press the hyperspace key (‘J’ by default) to begin travel. 

It doesn't begin travel, it just selects the next system.

Before I press J:
![screen shot 2017-12-08 at 10 02 57 am](https://user-images.githubusercontent.com/114976/33771435-039e47e8-dbff-11e7-8496-8128ec3d961e.png)

After I press J:
![screen shot 2017-12-08 at 10 03 07 am](https://user-images.githubusercontent.com/114976/33771442-09a652ca-dbff-11e7-9af6-a2a2e835c711.png)

Am I missing something, or is this a bug?

**Comment by Amazinite** [comment]
You have to exit the map and press J in order to jump. Hitting J while the map is open selects your jump destination.

**Comment by nfriedly** [comment]
Aah. OK. Thanks.

**Comment by tehhowch** [comment]
On the map screen, you can build a travel plan with J (rotate around the the current system), Shift+J (advance to the next leg of the journey), and backspace (remove the current leg of the journey).
Or if you've already got your hand on the mouse, just click your desired destination system :wink:
Shift-click to build a specific route rather than minimum distance.
Then close the map and press j to start your journey!

**Comment by nfriedly** [comment]
Yep, I just missed the "close the map first" part. It looks like it is [in the help text](https://github.com/endless-sky/endless-sky/blob/fba0c75fcddea4034622131122a2ab438d4f6f12/data/help.txt#L43) but just not in [the wiki](https://github.com/endless-sky/endless-sky/wiki/PlayersManual#interstellar-travel) - so perhaps someone can update that?

**Comment by tehhowch** [comment]
Only @endless-sky  can do wiki updates, unfortunately. So check back in on it over the weekend, and feel free to close this once the update happens.

Cheers & welcome to the game!
(For game chat, we have a Discord community, and use the game's Steam forums or Google Groups, reserving the GitHub issue system for bug reports, (well-formulated) feature requests, and discussions on *how* a particular feature might best be implemented).
