### ISSUE TITLE
Make commodity prices slowly return to default values

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3391]
Player isn't the only one driving economy; at some time abundant supplies will be exhausted, and a factory which sold out its production will create new goods; the change could be as little as 1/day. Point is, if player abandoned a trade route for several months (or even years), its prices would most likely be back to normal when fleet returns, assuming no extraordinary events.

**Comment by ghoulavenger** [comment]
I don't know about ever going to default, but commodity prices are always in a state of change. I think the game therefore more than adequately does what you're asking for. The only exception to this rule is if you drain the economy to the point that it hits its absolute minimum and maximum value -- and it is possible to do that, but it requires either a huge fleet or a lot of patience.

**Comment by Tadrix** [comment]
Oh. If that's so, then there's no issue. Hopefully prices do not stray too far on their own (because it would be weird if the price for commodity, which by description is produced there, would randomly skyrocket and stay up).
