### ISSUE TITLE
DSS Anderson is following me around with no associated mission

### ISSUE THREAD

**Issue by ToxicFrog** [endless-sky/endless-sky#3392]
A little while ago the _Anderson_ joined my fleet for the "destroy Republic listening posts" mission that hits Seginus, Alpheca, and Alioth. I did that mission, and it's gone from my mission list, but the _Anderson_ is still part of my fleet. If I return to Rastaban/Dancer, I get this message:

> "You have reached Dancer, but you can't complete this mission until the the DSS Anderson has visited Bluestone in the Bellatrix system with you and then joined you here."

If it's destroyed (which has happened a few times), I get a "mission failed" message, but there's no indication of which mission and my mission list doesn't change.

If I look at the map, there is in fact a "mission waypoint" marker on the Bellatrix system, but with no associated mission text I have no idea why it wants me to go there.

**Comment by KiLEdEnNis** [comment]
can ya find the mission name and maybe post your save file?

**Comment by ToxicFrog** [comment]
As I said, there's no associated mission in my log, but looking at data/ it looks like this is either "Pleasure Cruise Security" from `paradise world jobs.txt` or "Escort Science Vessel" from `deep jobs.txt`. The ship is a Bounder, so I think that means it has to be "Escort Science Vessel".

Looking at the save file confirms this, and if I quit and restart the game an "Escort Science Vessel" mission shows up in my mission list and can be aborted.

I have no recollection of accepting that mission, but it's entirely possible I did by accident while accepting a bunch of pirate-hunting missions, so if there is a bug here it's that the mission didn't seem to show up in the list; if I can reproduce that I'll reopen this.

**Comment by tehhowch** [comment]
This is likely from the ship getting disabled and then repaired by a non-player ship, which was recently fixed. See https://github.com/endless-sky/endless-sky/pull/3357 and its referenced issues.

**Comment by VonZorch** [comment]
I had something similar happen.  I don't remember the name of the ship, D.S.S something, it was a Scout.  I searched my save file and it wasn't in there, either by name or ship type.

**Comment by jafdy** [comment]
This fix isn't in the latest release version so unless you are self compiling or using the nightlies you won't have got it yet.
