### ISSUE TITLE
Idea: Sidemission to find lost human colonialization ship

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#3396]
The idea is based on this sentence from the Historical Timeline:
>A privately owned colony fleet begins traveling out from Sol looking for a place to settle far from Earth, and eventually founds the colony of Valhalla.

It would start with a private treasure hunter/university professor/official deep explorer that read the logs from this or a similiar expedition that lost a ship on it's journey. The player and said explorer would then head out to find the remains of the lost ship. 

There is nothing technological to gain from this mission, just a glance at what is mentioned in the Timeline but only briefly hinted towards in the actual game. It's only an idea, i have no clue what kinda steps the player has to make (pickup cargo here, deliver the explorer there) and where the ship can eventually be found. It should probably be crashed on a planet/moon's surface, so that it's at least kinda hidden.

**Comment by Bladewood** [comment]
This is something more suited for the [forum](https://groups.google.com/forum/#!forum/endless-sky).

**Comment by MCOfficer** [comment]
well, it's sort of a feature request... you're right, it doesn't 100% belong here. i'll leave it to MZ if i should "move" it. also, noted for future suggestions.

**Comment by endless-sky** [comment]
This should probably either be discussed in the forum (if you're trying to recruit someone else to do it) or submitted as a PR (if you end up doing it yourself).
