### ISSUE TITLE
Remnant Defense 2 logbook entry, weird sense of time

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3397]
Mission text:
> They explain to you (in song, of course; the explanation takes the form of an epic ballad) that these raids have been taking place for nearly a century.

Logbook:
> Recently, Korath ships have begun raiding Remnant worlds.

A (nearly) century is hardly recently for a human lifespan.

**Comment by KiLEdEnNis** [comment]
recently is a vague concept of time, and the Remnant have been in the Ember Waste for over 500 years?
it's perfectly fine to use recently, it's just a longer "recently"

**Comment by jafdy** [comment]
When you put Human civilization in perspective then things like the USA are actually quite recent. So is the concept of agriculture (farming, in case you didn't know). If you had been in uninterrupted peace for 400 years then that dramatic change to a state of war would always seem to be resent.

**Comment by Bladewood** [comment]
The point is that the onset of the Korath invasion is recent, relative to the arrival of the Remnant in the Waste.

**Comment by Tadrix** [comment]
From a historical POV definitely, but seems strange from ordinary human's POV. If WW2 never ended, would we at this time and age think of its beginning as a recent event?

"I was born recently" — is it really your everyday thinking?

Century is more than average human's lifespan. If all you saw in your life is war, for you it isn't recent, it was there since you can remember. There would be a lot of recent things (player's arrival, for example), but not this.

**Comment by Bladewood** [comment]
When we're talking about the history of a society, *yes*, we would. You are right that it is nonsensical from an everyday human perspective, but this is *not* an everyday perspective.
In the scope of modern human history, I'd call WWII a recent event, given that it was less than a century ago.
In an everyday conversation, I wouldn't say that my birth is recent, but I'm certainly much younger than most people you hear about on the news.

**Comment by Tadrix** [comment]
A [logbook](https://en.wikipedia.org/wiki/Logbook) isn't an everyday perspective? The thing should be filled in at least daily. Somehow I doubt it's a history book, or that merchant ship captains have the mindsets of historians. Also, log entries should be reasonably precise. Why use ambiguous "recent" (see, we here argue about subjective meanings, ergo historians wouldn't find such vague source especially helpful), when we could mention that it's a century (and not two centuries, or three decades, or yesteryear).

**Comment by endless-sky** [comment]
In terms of interstellar civilizations, a hundred years *is* recent. Note that the Remnant acts like the Alpha War is still going on, and that was 500+ years ago.

The fact that different factions have different concepts of "recent" is intentional. For example, to the Pug, a disagreement with the Archons that happened 100,000 years ago is still a "recent" event over which the Archons are still sulking.

**Comment by KiLEdEnNis** [comment]
I'll also add this for good measure (saved it for a reason) 
![time](https://user-images.githubusercontent.com/10348657/34063395-1efae6f6-e1f2-11e7-83a4-be7942cc36e5.png)

**Comment by Tadrix** [comment]
> The fact that different factions have different concepts of "recent" is intentional.

No doubt. And Remnants have all rights to consider raids recent.

Logbook, on the other hand, is maintained by player flagship's captain (its events portrayed as seen from his viewpoint), which means he's a (former) Republican who was born on New Boston in Rutilicus system. This, I presume, means he has similar concept of "recent" to ordinary humans'.

Speaking of which, if some alien told me there was a recent event some century ago, I would forgo confusing "recent" and just write down "century".

**Comment by MessyMix** [comment]
I'd actually agree with Tadrix on this one, conditionally. For a captain's logbook—if it is actually a logbook—would not consider "recent" to be from the Remnant POV, unless explicitly stated. Like, if I were keeping a diary, I would not speak from the POV of the Remnant. Now, if MZ tells us that the logbook isn't really a logbook, or at least that we're not going to try to disguise the fact that the logbook is more of a information center than a logbook, then that's a different story. Still, for clarity's sake, I'd change "recently" into something more explicit.

**Comment by Amazinite** [comment]
>A (nearly) century is hardly recently for a human lifespan.

I'd say that we don't know what the average human lifespan is in game, meaning that the

>concept of "recent" to ordinary humans'.

may be different in game a thousand years in the future than in real life right now. 

Also, the logbook *is* written by the captain, but it may be that the player is speaking in more of a historical sense then a personal sense. Notably, this isn't a normal log, but a faction log on the Remnant, and to me that sounds like the exact place that someone would write in a historical sense where "recently" is appropriate and not a personal sense.

Changing "recently" to a century though would be beneficial, as I wouldn't want to look back on my logs and wonder what exactly I meant by recently, and saying roughly a century is far more descriptive.
