### ISSUE TITLE
Typo in the Javelin Storage Crate description

### ISSUE THREAD

**Issue by UnciaPrima** [endless-sky/endless-sky#3399]
It should read Javelin instead of Javlein. I have no idea how to pull request this though

UP.

**Comment by KiLEdEnNis** [comment]
#3400 did it for ya, good catch

**Comment by tehhowch** [comment]
You can keep this open until that PR gets merged and this gets milestoned, if you wish.

**Comment by UnciaPrima** [comment]
Okay, i’lol keep this open then, thank you to both of you
