### ISSUE TITLE
Allow any outfit to draw power or produce heat constantly

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3402]
Right now energy and heat are always tied to the operation of specific functions: `shield energy`, `thrusting heat`, and so on. But there's no way to apply a constant background energy drain or heat production to arbitrary outfits. This would allow significant flexibility in the creation of interesting and novel outfits.

For example, I could imagine that radar jammers might constantly draw a small amount of power, and I could create a "radar-absorbant plating" outfit that used no power but was larger in mass compared to jammers that are small but use power. Right now I can't do that.

**Comment by Bladewood** [comment]
Um...

See the S-#70 regenerators...

**Comment by KiLEdEnNis** [comment]
"energy consumption" and "heat generation"?
adding that I made an early concept of a ramscoop using these 2 as seen here
![nekis ramscoop early concept](https://user-images.githubusercontent.com/10348657/33909844-336080d6-df8d-11e7-8863-8c38e3c3cb81.png)

**Comment by Bladewood** [comment]
To explain more clearly, as @KiLEdEnNis said elsewhere (which you can't see), it basically already exists:

To drain energy, use `"energy consumption"`. To regenerate energy, use `"energy generation"`.
To produce heat, use `"heat generation"`. To drain heat, use `"cooling"`. (Note that cooling is affected by cooling inefficiency, but to do otherwise would break balance, anyway.)

**Comment by gunqqer** [comment]
so if a negative heat generation was to be used, it'd bypass cooling inefficiency?

**Comment by Bladewood** [comment]
Sure, but you wouldn't be able to go into the negatives.

**Comment by Pointedstick** [comment]
Whoops! how embarrassing. I didn't see `energy consumption` on https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits, which is perhaps why I though it didn't exist.
