### ISSUE TITLE
Bug or feature? Odd random missions

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3403]
Not sure if we could/should fix this (perhaps regard it as an easter egg?), but here goes:
![18t-sheep](https://user-images.githubusercontent.com/17566547/33919494-a0a2636a-dfc1-11e7-9a5b-461bfc723329.png)
I probably shouldn't ask what they are going to do with the herd of some two hundred sheep on that cramped, overpopulated station…

Perhaps some limitations of tons of cargo or passenger count for missions ending on space stations would be useful, although here it's more of a cargo type problem.

**Comment by Bladewood** [comment]
[Believe](https://github.com/endless-sky/endless-sky/issues/1409) [me](https://github.com/endless-sky/endless-sky/issues/2273), [this](http://steamcommunity.com/sharedfiles/filedetails/?id=675822571) [is](http://steamcommunity.com/sharedfiles/filedetails/?id=700810715) [not](http://steamcommunity.com/sharedfiles/filedetails/?id=553088398) [a](http://steamcommunity.com/sharedfiles/filedetails/?id=580593723) [bug](http://steamcommunity.com/sharedfiles/filedetails/?id=545058331). [Really, it should be](http://steamcommunity.com/sharedfiles/filedetails/?id=888060631) [*kept* for the](http://steamcommunity.com/sharedfiles/filedetails/?id=1228881347) [pure humor.](http://steamcommunity.com/sharedfiles/filedetails/?id=610420921) (Who pays attention to mission descriptions, anyway?)

**Comment by Pointedstick** [comment]
> (Who pays attention to mission descriptions, anyway?)

I do, because things like the above are hilarious.

**Comment by tehhowch** [comment]
(close this issue)

**Comment by KiLEdEnNis** [comment]
next time ya check for duplicates, search closed issues too ty

**Comment by endless-sky** [comment]
The technical term for the 18 tons of sheep that is being delivered in this case is "mutton." Fresh, tasty mutton.
