### ISSUE TITLE
Request: Higher mission rewards when flying through hostile systems

### ISSUE THREAD

**Issue by xyzatesz** [endless-sky/endless-sky#3407]
As I've seen, mission rewards are the same for the same mission from system A to system B, no matter how hostile the systems you fly through are. In other words, flying to the other end of the galaxy will not give me more credits when I'm enemy with the Republic, compared to when I'm not.

So my request is that when a mission wants me to travel through a significant number of hostile systems (especially when the planet I got the mission from is also an enemy of those systems), the mission reward should be higher.

**Comment by tehhowch** [comment]
This could be done pretty easily, by referencing the danger level (strength of hostile fleets) of systems on the minimum-jump route.
The question remains, however, of how much more a mission like this should pay.

**Comment by Startome** [comment]
@xyzatesz keep in mind,  there are captains all over the galaxy that aren't enemies of the faction who's space you are traveling through.  So why offer hazard pay to you when half the captains will do the job without needing it?

Like many things in the universe,  if one person won't do it,  another probably will.  And if nobody is willing to take an offer,  then it goes untaken :)

**Comment by Tadrix** [comment]
@Startome Right, but this is true only where there are neutral factions to the conflict and no common enemies. For example, you shouldn't be rewarded for flying through Republic space while part of the Free Worlds, because Merchant faction can move through both factions' spaces unscathed. In contrast, if you need to move through heavily pirate-infested system, danger fee would apply, because pirates are common enemies and there's no one safe from them who could take up the job.

**Comment by tehhowch** [comment]
There's no current "nice" way to do that level of elaborate checking. 
As I read it, you are asking essentially this:
```
Compute route to destination system 
    (currently minimum jumps -> tiebreak via fuel use -> tiebreak via danger to player)
For each fleet in the offering system
    If not hostile to planet
        Insert government into map<gov, double>
For each government in map
    For each system on route
        Increment double in map by system's danger to that government
Compare double values in map to players danger level
If <compare criteria> is met, increase payment by <value>
```
Care to share some possible criteria, and the corresponding increase?

My thoughts:
 - if any have danger level less than player, no increase
 - if average player danger level is below `<threshold>`, no increase
   - threshold could be danger level of current system

**Comment by xyzatesz** [comment]
@Startome You are right, I didn't look at this from that viewpoint. I'm not so sure about this now...
@Tadrix Yeah, though are there any routes where you need to move through many pirate-infested systems? (I can't say that I'm advanced in the game, might very well be routes like that that I haven't yet uncovered).

**Comment by tehhowch** [comment]
@xyzatesz there are no Pirate systems through which the player takes jobs in the base game. If the player allies themselves with the Pirates, though, then a considerable number of jobs could be considered as passing through hostile space.

**Comment by Tadrix** [comment]
Well, that last one shouldn't reward players. Unless it's a pirate who's giving them such mission (because pirates couldn't do it better themselves, unlike Merchants).

**Comment by tehhowch** [comment]
From my pseudocode above:
```
For each fleet in the offering system
    If not hostile to planet
        Insert government into map<gov, double>
```

**Comment by jafdy** [comment]
It seems that when setting the jobs, people will know what kind of systems the player will be flying through. So, based on that they can give a higher payout to jobs through dangerous space.

**Comment by endless-sky** [comment]
There are already escort missions, etc. that give higher payouts in exchange for more danger. But it doesn't make sense for the job board to offer more money just because the player has made enemies in human space.
