### ISSUE TITLE
Game suggestion / map editor request: Rogue planets

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3409]
[Rogue planet](https://en.wikipedia.org/wiki/Rogue_planet) is an orphan planet. Certainly not habitable, but could function as a mining outpost if terrestrial, or have its refueling station if gas giant.

**Comment by tehhowch** [comment]
Please give a more detailed example, including data code you expect any such implementation to have, because what i'm envisioning is a system that gets moved every day on some horrendously large cycle, containing only a single planet.

**Comment by Tadrix** [comment]
Nothing like that. Rogue planets orbit center of the galaxy just like stars do. It would be like a usual stationary star system, but with a planet in its center (which, obviously, doesn't generate power via solar panels, and no fuel via ramscoops either if it's not a gas giant, so it would be slightly more dangerous to get stranded there if the system is uninhabited). This planet can have usual satellites (its moons) or refueling stations.

**Comment by tehhowch** [comment]
So what stops you from doing this with the current map editor? That doesn't sound like any kind of different functionality.

**Comment by Tadrix** [comment]
Essentially it's just a "star" system with a planet instead of a star.

Since I can't compile my own binary at this time, I use what is available. Can you in the current version:
1. Turn off "star's" fuel generation;
2. Turn off "star's" solar energy generation;
3. Let player land on the "star" and give it planet's properties (shipyard, outfitters, jobs, that sort of thing)? For terrestrial rogue planets that should be possible.

The last one at least is possible by editing data files and placing a planet in the center of the system, don't know about the current map editor. I didn't find a way to accomplish the first two objectives though.

If a terrestrial rogue planet was ejected while some civilization lived on it, there could be some great archaeology missions associated with it.

**Comment by tehhowch** [comment]
in v0.9.9 you're going to have very poor regen/power if you system doesn't contain something with a wind and luminosity value (see data/stars.txt)

**Comment by solardawning** [comment]
Yes, Tadrix, you can do all of this right now. :)

**Comment by Amazinite** [comment]
I have a lot of things planned that I want to get added to the game, and this is one of them. A while back I started some beginning work on a new alien civilization (only did system and planet names and locations, along with planet descriptions and some ship/outfit ideas), and one of their "systems" that you can jump to is a rogue planet. The only thing that would actually need to be done right now is make graphics for a rogue planet, as all current graphics for planets have light coming from one angle as if a star is nearby, but that wouldn't be the case for this rogue planet and its moons.

**Comment by tehhowch** [comment]
@amazinite I'm sure @comnom has something suitable in the plethora of variants he has been making for https://github.com/endless-sky/endless-sky/pull/2606

**Comment by Tadrix** [comment]
Yep, rogue planets and their moons wouldn't have shadows. They could be somewhat illuminated if their location would be near galactic core or some other place with plenty of starlight.

comnom's assets are awesome, but they are lit from one side.

**Comment by tehhowch** [comment]
You should close this issue. (Note also I said comnom probably has some raw assets from his work, i.e. before doing the side lighting.)

They aren't planned, so you aren't going to see base game planet sprites that meet this unlit criteria unless you recruit someone to develop and PR them.
