### ISSUE TITLE
Something isn't right with "Transport executive" passenger mission payouts

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3410]
Transport executive vs. transport workers, miners, families or tourists. Executive missions are timed, yet payout is the same or worse than for a single worker, farmer or tourist. I wonder how they ever get to their destinations in time, because if I have more lucrative missions lined up (of which there are plenty), it's not worth it taking executive's mission. Which is probably broken, because a timed mission should pay better.

An example
Alpha Hydri → Alnair, busy executive, timed: 12 900
Alpha Hydri → Phact, passenger, not timed: 13 500

**Comment by Pointedstick** [comment]
The payment calculations are done a bit differently; most jobs pay less per jump, but add a larger lump sum on top. The executive jobs are the opposite, but you don't see the advantage of a higher per-jump payment with very short distances. I'll tweak it a bit.

**Comment by Pointedstick** [comment]
Fixed in https://github.com/endless-sky/endless-sky/pull/3359
