### ISSUE TITLE
Flickering background stars

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3414]
Perhaps old news but didn't see such an issue. When zoomed out far enough, version 0.9.8., stars flicker whenever my ship moves. This was not present at 0.9.6, or at least not so pronounced (just checked).

I'm playing vanilla 0.9.8. with high DPS and (renamed) dark ships plugins.

**Comment by jafdy** [comment]
What's your screen resolution? My guess is that the stars are becoming smaller than a pixel so keep alternating between displayed and not displayed (just a guess).

**Comment by KiLEdEnNis** [comment]
what Jafdy says is true; they're <1 pixel big so they keep appearing when about in the center of a screen pixel, then vanishing because they're in-between screen pixels, and there's not really a fix besides making the stars bigger (a bad one) or somehow forcing stars to at least be a 1x1 pixel which will very likely look tacky

**Comment by Tadrix** [comment]
1280×1024.

The thing is, I understand _why_ this is happening, but when I test on earlier builds (0.9.6 and before) this isn't so pronounced. I didn't have any problems earlier when zooming out. At 0.9,6 only maximal distance flickers. Now it's even more visible. Meanwhile, I did upgrade some parts of my computer, but not video adapter and not monitor, so I'm guessing some changes to the way things are rendered were made?

**Comment by KiLEdEnNis** [comment]
if you can retry on 0.9.6 to find out we would know if it was your hardware or some change

**Comment by Tadrix** [comment]
Retried. I honestly can't tell now, because it seems that flickering severityy depends on angle the ship is flying (and it is worse while turning mid-flight, until ship's trajectory is straight again), and I don't know how to reproduce precisely same angle to test.

**Comment by KiLEdEnNis** [comment]
if the ship would be flying exactly up, down, left or right the stars would only move to 1 side too, but if the ship flies a bit more to a corner, those stars would disappear between multiple pixels, so the severity would indeed be affected by the angle

also, I tested it fully zoomed out yesterday on a 1920x1080 screen and I have the same issue (at very low speed it's kinda beautiful, but when turning looks a bit bad
but when one would have a ship that has a max speed of 5.000 the stars would look weird and stretched too, there's not really a fix at all

**Comment by endless-sky** [comment]
Nothing has [changed](https://github.com/endless-sky/endless-sky/commits/master/source/StarField.cpp) in how the star field is rendered since 0.9.6, so I don't see how the stars could look different for you in those two releases.

**Comment by Tadrix** [comment]
> low speed it's kinda beautiful

++, but anything beyond that…

> Nothing has changed

Ok, so it's me then.

I'm closing this, but it would be nice to have better rendering. I'm sure there is plentiful of other issues on that topic though.

**Comment by endless-sky** [comment]
If you're building from source, see if 256895a fixes this issue for you. It's tough to strike a balance between having the stars small enough that they still look "sharp" at low zooms, but large enough that they don't flicker due to being less than a pixel wide. But I think that change is a good compromise.
