### ISSUE TITLE
extra missiles

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#342]
Tired of running out of missiles? Try the new extra missiles outfit! For some outfit and weapon space you can have 30 more meteors or 45 extra sidwinders.

**Comment by Pointedstick** [comment]
Where is this?

**Comment by airtroop392** [comment]
I'm almost positive the OP is pitching an improvement for the game, not shamelessly advertising his own mods.

**Comment by brick96** [comment]
I have hardly any knowledge if coding. I just presented an idea for an outfit in different way than usual

**Comment by Tufton** [comment]
You may want to check the content creation or feature request section in
the Google Group, it is more of a forum-style way to share ideas, designs,
and completed mods than doing a pull request.
