### ISSUE TITLE
Drone chatter

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3421]
Drones no longer can be hailed, but they still leave messages like "help us destroy this pirate ship" and "thank you for assistance, captain".

**Comment by tehhowch** [comment]
"Drones"
"no longer"
Specificity!
When could they, previously?
Who / what exactly *is* `they`?

**Comment by Alkallid** [comment]
Do you mean that pressing 'T' doesn't bring up a response, but after a battle, the lower-left communications chatter is attributed to them?

**Comment by tehhowch** [comment]
Who's to say that `automatons` are not preprogrammed with combat courtesy responses? If I were their creator I'd certainly wish they broadcast for assistance instead of getting blown to bits by pirates.

These particular messages appear because they are not actually hails - they are "grudge" responses.

**Comment by Tadrix** [comment]
> When could they, previously?

Now, when you hail a drone, you'll get message that you receive no answer. Where's combat courtesy? They could at least say `"This is Republic drone <name>. Please contact my mothership for assistance."`

> Who / what exactly is they?

In my example, drone by the name something "eleven". There were no fighters, but there were cruisers with combat drones, so I must conclude it was a drone and not a fighter.

**Comment by tehhowch** [comment]
From your initial post it was not clear if you meant Mereti, Sestor, or something else. #3422 will prevent any uncrewed ship from also sending the "grudge" messages you mentioned in OP.

**Comment by Pointedstick** [comment]
> Now, when you hail a drone, you'll get message that you receive no answer. Where's combat courtesy? They could at least say "This is Republic drone <name>. Please contact my mothership for assistance."

I rather like that idea.
