### ISSUE TITLE
Extra Spaces in Wanderer Hails

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#3423]
![screen shot 2017-12-15 at 4 01 55 pm](https://user-images.githubusercontent.com/16172407/34064881-8b18c11e-e1b1-11e7-8c68-e1836dc5c849.png)

I looked at the hail list but I haven't enough knowledge about them to spot where the extra space is.

**Comment by KiLEdEnNis** [comment]
what happened: 
![wanderer hails](https://user-images.githubusercontent.com/10348657/34065259-77a77d4c-e200-11e7-9b91-fb18d1c171fc.png)

this screenshot shows the changes in #3284 which fixed this

**Comment by Alkallid** [comment]
Huh. I didn't see the emtpy word.

**Comment by KiLEdEnNis** [comment]
did you look at the current code? of course you couldn't find it as said PR fixed the issue

**Comment by Alkallid** [comment]
I was sure that I checked the latest commits...
