### ISSUE TITLE
Human turret comparison and request

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3430]
Yesterday's https://github.com/endless-sky/endless-sky/commit/beb7f03836f37e173134e9e9f510494393924bb7 improved blaster range and https://github.com/endless-sky/endless-sky/commit/6da2d5083f77d6f6b23c8b2b766216d5ffd7a29e changed turret turn rates. These changes result into the following human anti-ship turret values:

```
                         price,mass,energy,heat|shield,hull,heat,range,rotate
Blaster Turret          : .10 , 15 ,  96 , 300 |  96 ,  60 ,    , 510 , 222
Modified Blaster Turret : .17 , 18 , 108 , 420 | 120 ,  80 ,    , 480 , 210
Laser Turret            : .14 , 22 ,  60 , 144 | 120 , 156 ,    , 300 , 240
Quad Blaster Turret     : .23 , 25 , 192 , 600 | 192 , 120 ,    , 510 , 192
Single Proton Turret    : .26 , 34 , 113 , 450 | 189 , 158 ,    , 624 , 120
Heavy Laser Turret      : .32 , 40 , 120 , 252 | 204 , 288 ,    , 400 , 132
*Octet Blaster Turret*  :     , 45 , 384 ,1200 | 384 , 240 ,    , 510 , 
Electron Turret         : .72 , 54 , 180 , 324 | 288 , 396 ,    , 450 ,  84
Plasma Turret           : .52 , 60 , 200 ,1200 | 420 , 167 ,2267, 480 ,  72
*Double Proton Turret*  :     , 66 , 225 , 900 | 372 , 315,     , 624 ,    
```

Although I still think a heat reduction for blasters and a price increase for lasers would be nice, that is not the topic of this issue, nor is the high turn rate of the Laser Turret (shouldn't a higher mass mean a lower rotation?).

The Quad Blaster Turret might now be considered a highly inefficient alternative to the Laser Turret, but is nowhere near the Heavy Laser Turret. Introducing a turret with eight blasters would fill this niche; the expected values are in the table above; it could be considered a Human Thrasher Turret, although it's certainly worse. It could be used occasionally on ships with excessive heat capacity.
(I don't think more modified blaster turrets (cf. #3319) are necessary; they are pirate outfits for small ships. Nor would adding turrets with six or twelve ordinary blasters be a good idea; however, one with eight would be nice to have.)

Furthermore, the Proton Turret is unique amongst human turrets, because it only has one gun (the QBT has four, all others two). Having a turret with two proton guns would be an interesting alternative to the Electron and Plasma Turrets (see table for values).

Would anybody be able and willing to create sprites for the proposed blaster and plasma turrets?

**Comment by jafdy** [comment]
I don't think an octa blaster turret would look very good, it also looks very close to the values for the plasma turret. I'm not sure about a dual proton turret as the electron and plasma turrets are already huge and that would be bigger.
Either way I don't think there needs to be even more weapons to chose from.

**Comment by Nescio0** [comment]
> I don't think an octa blaster turret would look very good, it also looks very close to the values for the plasma turret.

It would be smaller and it would lack the plasma's characteristic heat damage, which makes a huge difference. More importantly, the plasma turret isn't immediately available, it has to be unlocked first. Until you've made significant progress with the FW campaign, there are no alternatives to the Heavy Laser Turret (the QBT is similar to the beam laser turret); a Octa Blaster Turret would fill that early game niche.

>  the electron and plasma turrets are already huge and that would be bigger.

Large, yes, but I wouldn't call them huge; they are much smaller than the Dual Sunbeam Turret.

> Either way I don't think there needs to be even more weapons to chose from.

Having more items and more choices makes the game more interesting.

**Comment by comnom** [comment]
> Having more items and more choices makes the game more interesting.

You're not wrong here. But the push for new content is, and should be, focused on extending the current "end game" with new alien species (which come with new items) and storylines.

This is also why new human ships get shot down, and it's ill advised to add new systems to human space.

Irrespective of how many T1 items there are, the fact is that a player will still pass their usefulness in the same amount of time as they progress through the current storyline, and into the alien faction storylines.

So you may see a few items get added here and there, mostly as balancers, but it's not priority.

**Comment by ghoulavenger** [comment]
In general I have no qualms with adding additional weapons. I do think that you have some strange ideas about balance though. The problem with heavy lasers is not that they have no competition, just look at the Hai weapons, and they're available from the start. Would it be nice if there were some more interesting human options? Maybe, but why does it have to be blasters, those are supposed to be economy weapons, if you're springing for the best, then you should be buying something else of quality. 

Ironically this is why the plasma turret is introduced, to fill that niche, yet you discount it entirely by saying it requires an unlock. Granted, this isn't an end all be all solution, but I don't see how an economy blaster is supposed to directly compete with a refined top of the line heavy laser. 

Now don't get me wrong, I'm not saying heavy lasers should reign supreme until the electron beam comes around, but it doesn't make sense for the economy weapon to be its direct competitor. Weapons need their own niche more than anything else, and blasters have theirs on smaller ships, especially if they get additional gun mounts to help people take advantage of their small size.

> >  the electron and plasma turrets are already huge and that would be bigger.

> Large, yes, but I wouldn't call them huge; they are much smaller than the Dual Sunbeam Turret.

I think you're missing the point here. The plasma turrets are supposed to be revolutionary with their size. You're allowed to comment that it is impractical for the arming mounts of most ship designs (e.g. people are expected to use guns). This is a pretty big lore change, and might even suggest that larger ships would lose gun mounts and gain weapon space for these huge turrets instead (considering guns themselves are far less useful on ships that aren't manueverable, it wouldn't be that bad really). The only ship right now I can see fitting for that lore wise would be the dreadnaught, which also doesn't come around until the plasma turrets introduction anyway (e.g. it's pretty revolutionary too).

**Comment by Nescio0** [comment]
No, I do get your point. However, I'm not talking about balance, nor about competition (blasters are too inefficient to compete with lasers), and yes, individual players can easily get Hai outfits and weapons immediately. When I write “alternative” it doesn't have to be efficient or interesting; even a poor choice is at a choice.
Octa Blaster Turrets are a suggestion for the pre-campaign, human space default ship weapons. 

> blasters have theirs on smaller ships
Let's have a look at the largest available human default ships:
* Bactrian and Behemoth have Heavy Laser Turrets
* Falcon, Leviathan, Protector have Quad Blaster Turrets
* Vanguard has neither

If we ignore their heat, QBTs could be an alternative to ordinary laser turrets, but not really to heavy laser turrets. These heavy warships are large enough to support OBTs or HLTs, yet half of them are equipped with QBTs.

> I think you're missing the point here. The plasma turrets are supposed to be revolutionary with their size.

If lore is your concern, then we could suggest Syndicate developped the Double Proton Turret as an answer to the South's Plasma Turret. I'm certainly not opposed to having the DPT unlocked later in a campaign.

**Comment by jafdy** [comment]
The Syndicate is never really at war with the Free Worlds.

**Comment by Nescio0** [comment]
> The Syndicate is never really at war with the Free Worlds.

I didn't claim they were, did I? However, some regional competition is already the case:
```
          Deep    , South , Syndicate
power   : NT-200  , S3 Th., RT-I
engines : atomic  , plasma, ionic
weapons : electron, plasma, proton
```

**Comment by tehhowch** [comment]
If you're adding content for the base game you **need** to consider lore and balance, not just competition.
While possibly appropriate for the Syndicate to develop a large turret of its own in its storyline, there's no reason to - before the storyline is written - force its writers to use that weapon.

(That the Vanguard doesn't use a quad blaster is easily understood - they have 7 longer ranged cannons, good turn rate, and a single turret mount, and their primary opponents are meteor- and javelin-happy pirates.)

**Comment by Pointedstick** [comment]
Not sure this makes sense; even my modified quad blaster turret was rejected, so I don't see any chance that an octo-blaster turret would fare any better. Such a thing would also look fairly ridiculous. If anything, it would be a thing I'd expect from pirates, not the Syndicate. Possibilities for introduction via missions could work but yeah before then, I don't see this happening.

Besides, Blasters really aren't so terrible anymore. The range improvements in particular give the Quad Blaster turret a real reason to exist vs Laser Turrets that are larger and have lower range, and the Proton Turret which is larger and does a tad less damage.
