### ISSUE TITLE
"Scoped" color variables in interfaces

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#3435]
Pretty self explainatory. It'd make the interface more modular without each label or string having to be defined in the interface. It would still need to pull from the interface colors rather than hardcoded colors, but @tehhowch seems to be working through that bit.

For example:
The boarding panel pulls "faint" "dim" "medium" and "bright from interfaces.txt for the parts that aren't defined in the interface. Knowing this I can override those, but doing so changes everywhere that uses those colors (alot of places in this case).

Scoping would make it a bit more like css, where I can style all ```<p>``` elements, then override it locally as needed ```.myclass p {}```.

So we'd have:
```
color "bright" .75 .75 .75 0.
```

Then:
```
interface "boarding"
	color "bright" .75 .75 .75 0.
```

And pull the "local" color if it's there, or fallback to the "global". Would likely require storing a color set or some other container for each interface, and I don't know what kind of overhead that will bring as more things become interfaces.

**Comment by tehhowch** [comment]
If I were to implement it, my first thought would be to go for the Has/Get ternary:
`const Color &bright = interface->HasColor("bright") ?  *interface->GetColor("bright") : *GameData::Colors().Get("bright");`

**Comment by endless-sky** [comment]
The whole purpose of having global colors defined is to achieve consistency across all the user interfaces. It would become a maintenance nightmare if slightly different colors were defined for each interface, so in practice this would be something that would never be done in the stock code, only in plugins.

But if you're writing a plugin and overriding an interface anyway, you could just use your own color names in that interface. The only thing that wouldn't achieve would be letting you change the colors that are used in the C++ code. But the only way those could be changed is if every time the game code selects a color, it selects it through a particular named interface. Which, in turn, would add a lot of complexity (new interfaces having to be defined just as placeholders for color definitions).

That doesn't really make sense to me unless someone comes up with a really good example of a case where it's necessary and where just overriding an interface definition can't achieve the same thing.

**Comment by comnom** [comment]
The idea was brought about because of things that aren't (yet?) defined in the interface. I don't have a slew of examples as I'm just working on a hud right now, but I was considering what to do about the following:

In the boarding panel I can override most of the strings, but not the outfits list or the combat results strings:
![boardingafter](https://user-images.githubusercontent.com/22107649/34185187-f37a456e-e4f1-11e7-8186-1086fa8905db.png)

In the hails panel I can override the "header" string, but not the actual text:
![talkafter](https://user-images.githubusercontent.com/22107649/34185199-0361f5b2-e4f2-11e7-8454-b5922b060299.png)

(Both cases are just to make the text full opacity so the yellow doesnt bleed into the text)

So really I was just spitballing an idea that could be used in place of defining all that in the interface, but if that's the preferred method I don't really mind. I just figured it may get a bit tedious if we want "full" customizability for every interface.
