### ISSUE TITLE
Spaces in save file names

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [endless-sky/endless-sky#3438]
Is there any reason the save game files have spaces in them instead of an '_' or similar? Just asking because spaces in filenames can be a nightmare sometimes.

**Comment by jafdy** [comment]
The save display shows the file name so having `_` would make the file name in that display show with a `_`.

**Comment by EmergencyTemporalShift** [comment]
Clearly it takes off the file extension in the display, so some processing is already involved.

**Comment by tehhowch** [comment]
They have spaces in them, because they are allowed to have spaces in them, and no special care is needed for Endless Sky to handle spaces in file names. Plenty of non-save files have spaces in their names as well, both images and data.

**Comment by Amazinite** [comment]
What exactly is the issue here? What is the problem with spaces in file names?

**Comment by Pointedstick** [comment]
Only lousy software has trouble with spaces. Solution: don't use lousy software--or report bugs and submit patches if your lousy software is FOSS and you can't bear to part with it.
