### ISSUE TITLE
Mission String Idea: Unique, powerful ship

### ISSUE THREAD

**Issue by Fzzr** [endless-sky/endless-sky#3445]
This came from a passionate discussion in the Discord, including many different opinions and ideas. 

The basic premise is: Could we have a mission string for which the reward is a unique, powerful ship. When I say unique, I mean a unique model, distinct stats, and maybe other special characteristics.

The initial inspiration for this was the [Unrelenting](http://evn.wikia.com/wiki/Unrelenting) from EV Nova. To me, what makes the Unrelenting special beyond your average powerful ship is how the game makes you feel attached to it. It's deeply connected to the storyline, earning it feels like a real achievement, and you get it at just the right time for you to feel immediately rewarded for using it.

Endless Sky already has a ship that goes halfway there: The Kestrel. The idea that got thrown around in Discord was to create a special Kestrel with a slightly different, unique model. It would have upgraded stats (no details as yet) and notably, contain some amount of alien tech. The important thing is that it would be _completely_ unique. None will be sold or built, and it should not be possible to kludge together a statistically identical or near-identical ship.

As for the making you work for it part, we discussed a wide range of possible questlines, but most of them revolve around the Alphas somehow getting their hands on (or building) a prototype next-generation Kestrel incorporating alien technology. The player would need to track them, prevent them from obtaining any more, and finally destroy _or capture_ the stolen ship. The "or capture" part is important: this ship is unique. You don't get given one at the end of the quest, you can only get it by boarding and capturing it after defeating it in battle.

Whenever the questline happens, the result should be something at least as strong as anything else you can obtain at the time (in a first time take-it-as-it-comes playthrough, anyway). In principle, the best time would be right before the final push in the FW campaign, so that the player has a shiny new flagship for the finale. That might break up the flow, so any other ideas are welcome. Another suggestion was to tie it in with the postgame Alpha group, such as them using scavenged tech and the Kestrel blueprints to create a "perfect" ship that cannot be replicated... symbolically similar to the creation of the Alphas themselves.

These are just a few of the ideas thrown around. The key question that needs answering first is whether the result, a unique, powerful ship, makes sense from a balance and game design perspective. It will not be the most powerful ship in the game, just better in significant ways than what else is available at the time. It will be truly unique, so it doesn't become the obvious thing to use to populate a death fleet.

Is there a place in Endless Sky for an "Alpha Kestrel"?

**Comment by solardawning** [comment]
There's a couple ships that I consider halfway to this, already. I'd actually start by modding those into unique ships.

1: The Alpha Carrier 'Giftbringer'.
You have one shot to capture it, at a momentous point in the storyline. It's a heavily modified carrier, packed with Kor Sestor tech.

2: Engine-variant Marauder Falcon 'Oxyrinchus'.
This ship is only seen during the Archaeology questline, after all of There Might Be Riots, speaking with the archon they tell you about, and discovering the existence of buried Sheragi ruins on Zug.
The archaeologist you're working with tells you that this ship belongs to his rival.

Both would be excellent candidates for being modded into truly unique variants.

**Comment by Fzzr** [comment]
My first idea was actually to have it be based on a Carrier until someone pointed out that Giftbringer is already that. I hadn't thought of Oxyrinchus. The idea of unique appearance is totally divisible from the larger idea here. Modding temporarily aside, do you think unique models would make sense to eventually include in the main game?

**Comment by jafdy** [comment]
The big issue here is keeping it relevant, if you want to to be balanced at the end of the human storyline then it will become irrelevant as a warship during the Wanderer story and become a liability in a potential T3 story. Or you can make it T2, then it will need to be acquired later on or be horrendously overpowered. 
People have toyed with the idea of "growing ships" to make a unique ship that can stay relevant but there are a whole host of technical issues with that. Finally, having a single no-brainer ship is very bad for balance.

**Comment by KyroFirehammer** [comment]
Hmmm.... a possible way to make this possible would be to incorperate almost an upgrade feature where it takes your current ship saves the outfits attached and cargo, then removes the base ship and replaces it with the new upgraded version, and then puts the outfits and cargo back. 
This could also be an interesting mechanic for upgrading standard ships to the marauder varyant (which would only be an available upgrade on pirate worlds), the coalition arach hills gaining and losing pods, and the Kor Mereti "lifecycle", but in order to balance this, in my opinion, the cost would need to be exorbanant particularly for t2 (and 3 ships potentialy) and require a certan mission or event  to be completed (such as having the mereti become friendly or having certain storyline events be completed)

**Comment by solardawning** [comment]
The idea that it needs to be perpetually upgradable or always useful strikes me as a red herring.
There's enough appeal to the idea of just collecting unique ships (and using them for a while), even if you eventually outgrow them. Heck, I make sure to capture Every. Single. One. of the mission-spawned named ships. The Free Worlds bounty ships? That pirate lord you need to kill when getting the pirate planets to defect to the Free Worlds? Giftbringer? All of them. And I park them.

It'd be cool enough to just give them minor shield/hull/cargo/outfit space/tonnage tweaks.

What if Giftbringer had more fuel and cargo space? Now it's a great flagship for a while.

What if Oxyrinchus had 50 more outfit space and required 20 fewer crew? Cool reward for that huge questline.

It'd be enough to just make a couple little tweaks like those, and have these mission reward (if you capture them) ships seeded around the game. Little things where, if you find them and notice, you think 'that's neat'.

**Comment by KyroFirehammer** [comment]
If someone would send me a link to a guide on how to program this kind of stuff, I'm pretty shure I could put something together to get a little upgrade system ready enough to put it more solidly on the table. If @endless-sky doesn't have any problems with this sort of thing, I believe that this could lead to some pretty interesting PRs in the future (and it could help humans keep up with some aliens and almost start making the Arfecta feel less out of place) and would all around add more depth and logic to many existing ships and factions. (and while your at it if someone could send new a crash course guide on how exactly PRs work, I would be ever thankful because I would like to actually submit new code instead of only bringing suggestions to the table)

**Comment by Fzzr** [comment]
I agree with solardawning: I actually don't care too much about keeping it relevant indefinitely. It should just last a bit longer than your average newly available ship. For good balance reasons things like the Kestrel and Dreadnought, when introduced, are good options but generally just a bit ahead of or behind other things available at the time. A unique ship should be able to push that balance a bit for the sake of the reward, because it doesn't need to guard against being used to overwhelm a whole tech level. If you can do the appropriate questline at the time it first becomes available, you _deserve_ to have a flagship that's a half-tier ahead of what you would otherwise have. You shouldn't also have something that's Just The Best for the rest of the game.

**Comment by KyroFirehammer** [comment]
I wasn't thinking of a "best at everything ship", but more of a way to keep certain ships, such as the Kestrel, in your fleet without them becoming a major liability. In essence, a way for someone to use a ship, and have the ability to keep its stats on par with the opposing ships that you face in alien terriotories. For example if someone were to take a Kestrel and upgrade it to be similar to a t2 ship, it would have an upgrade to it's hull and shields ( possibly a small upgrade to the outfits to have it be able to use some weapons of that teir as well but I don't want another bactrian problem) to where it could, in a 1v1 scenario, have a chance against a t2 heavy warship (in essence you take a t1 ship and make it a t2 ship after gaining access to t2 tech and spending a large amount of money)

**Comment by Fzzr** [comment]
To give another EV Nova example, what you're describing sounds a lot like the [Mod Starbridge](http://evn.wikia.com/wiki/Modified_Starbridge). The Starbridge is a generally available pretty good ship, but there's also the Modified Starbridge, which is presented in the game as the thing to get for hotshots and elite pilots. You can turn a regular starbridge into a mod starbridge by buying a special upgrade package. That one also adds gun ports and changes the in-game model.

The obvious way to create a ship with unique stats without needing to add a way to modify a single instance of a ship is to create an entirely new ship class and swap them out. I have no idea how one would replace an existing player ship with one of a different class using the existing outfits, though.

**Comment by KyroFirehammer** [comment]
*reads above comment* 
You just said what I was trying to say but better.
However, I wasn't planning on changing the gunports or turrets because on most ships they are fine as is but they will probably need an outfit space upgrade to be able to hold high end turrets and guns such as the sunbeams

**Comment by Fzzr** [comment]
If you're doing a general capabilities change without changing gun ports, appearance, etc. then it seems like it could be done with a "hidden" outfit that works like the cargo and outfit space modifiers do today. Unlike those it would be irreversible. It ought to change the base price of the ship, though... I don't think an outfit can do that today.

**Comment by KyroFirehammer** [comment]
*GASP*
I've got it! If we (or me) just create a new variable call it something like 'upgrades available" and put it at a set number, then we can add an item that basically adds x amount of shields y ammount of outfits and z ammount of hull in exchange for 1 upgrade  slot (ships would only have 1) . We vould call it something like "wanderer upgrade unit" that would not be purchaseable after getting the wanderer licence and could cost something like 25,000,000.

**Comment by Fzzr** [comment]
That's a much bigger change that probably deserves a totally separate discussion, since it would apply to potentially all ships. I was thinking about a way to do the unique ship thing without a visible change like the to ships in general.

**Comment by solardawning** [comment]
Fzzr, just change the ship stats you want to change in the mission, where the ship spawn is defined.

**Comment by Fzzr** [comment]
Is it possible to change sprite that way as well? If so, that pretty much covers everything implementation-wise with no new engine features. Not sure what I was thinking 🤦‍♂️.

**Comment by solardawning** [comment]
I'd say give it a try. If it doesn't work, then make a 'variant' for the ship first, and put the different art file there.
No new features needed either way.

**Comment by jafdy** [comment]
You can give variants a different sprite but you can't change the sprite with an outfit.

**Comment by solardawning** [comment]
We're not talking about outfits or upgradable ships, though. The question was just 'can we make some mission ships be be unique variants'.
Yes, yes we can. :)

**Comment by Fzzr** [comment]
Question answered enough for me anyway, thanks for input everyone
