### ISSUE TITLE
Ship spacing

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#3446]
I've noticed playing through the game that my escorts, regardless of fleet size, keep winding up in a tightly packed group. This has led to some issued in large battles where, for instance, one of my ships or an enemy ship is destroyed and the blast damage wounds or, in the case of small ships such as fighters, are destroyes a large portion of my fleet. I'm suggesting that the AI have a protocol to both space themselves out from other ships (unless a "guard" command is added in which the ship would then closely guard the target ship) and tells the ship to avoid exploding wrecks (with the exception of fighters, which should not avoid ally ships because it would mess with docking and utilizing larger ships as meat shields) . It would probably be something like this: if (ship) is  not a fighter and within (distance) from (ally ship) move away from ally ship. It would be the same for exploding wrecks except for fighters would also try to avoid them.

**Comment by tehhowch** [comment]
Spacing is already done. See AI::DoScatter.

Threat avoidance is something that will be added eventually.

**Comment by KyroFirehammer** [comment]
How recent was that because my build could possibly be slightly outdated, but it's great to hear it's being added because it's annoying how anything smaller than a cruiser gets melted by blasts from dying ships, and not having to have my ships constantly overlapping each other does make it easier to issue commands.

**Comment by tehhowch** [comment]
AI::DoScatter has been in the game for a long time - it was added in 8285885a61e482c70ede3c1b1d651dc1ad3f0baa
