### ISSUE TITLE
Custom disable threshold value

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3448]
The following is a graph of the current disable point for a ship's hull. The X axis is the amount of hull and the Y axis is the hull remaining at which the ship is disabled.
![screen shot 2017-12-20 at 2 03 15 pm](https://user-images.githubusercontent.com/17688683/34223778-8f32994c-e58e-11e7-9887-b35b284e713d.png)

The following graph has hull on the X axis and on the Y axis is the % of hull left at the point of being disabled.
![screen shot 2017-12-20 at 2 16 20 pm](https://user-images.githubusercontent.com/17688683/34224287-6266af5a-e590-11e7-9f19-53496e7b310f.png)

These values are true across almost all ships, the only exceptions being ships that are never disabled. Aside from the fact that I find it odd that all species have their ships disable at the same % hull left beyond a certain point (and up into T2, practically all ships have enough hull that the 20% disable point kicks in right away), I think that being able to fine tune when a ship disables would be beneficial to plugin makers.  (For example, one could technically make a ship more powerful by lowering the point at which it disables instead of increasing its hull, and it would especially help for fine tuning as currently a plugin maker must, for the most part, raise the hull of a ship by 5 points to raise the disable threshold by 1 point.)

One or both of the following attributes would help. The naming can change as it's the functionality that is desired.
* `"disabled at"` = hull left when disabled (doesn't take into account the ship's hull being increased or decreased by an outfit)
* `"disable threshold"` = % of hull left when disabled (takes into account any hull that is gained or lost through outfits)

**Comment by Hadron1776** [comment]
If I had to pick, `"disable threshold"` would be the way to go. 

Getting disabled at 96% hull because of outfits would suck.

**Comment by KiLEdEnNis** [comment]
not really sure what ya all said but I'm for a custom disabled value, more modding freedom
