### ISSUE TITLE
ES really doesn't like it when resuming from sleep in Windows

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#3450]
http://steamcommunity.com/app/404410/discussions/1/1621724915770305701/?tscn=1513862721
The Steam thread has all the information I have with regards to this.

**Comment by tehhowch** [comment]
I attempted to reproduce on ubuntu 16.04 by launching ES (in both `mode=debug` and not, both in and not in full-screen) and then entering sleep mode. I did not notice any graphical oddities or jitter when resuming the game.

Thus to me this seems like a Windows-specific issue. Perhaps @Pointedstick can comment on how a different window manager performs.

**Comment by comnom** [comment]
Are we talking about regular sleep (S1-S3), hybrid sleep (S1-S3 and a hibernation file), or hibernate (S4)? These are all related but different concepts, and on Windows resuming works differently for hibernate. In the case of a laptop, so does the sleep process; specifically, drivers and applications aren't notified of the power state change if the battery is critical.

Followed tehhowch's lead and tried to reproduce, and no issues for me resuming from sleep or hibernate on Win 7 x64.

**Comment by comnom** [comment]
I'm have no idea what that post is saying, but I doubt it's an issue with the game either. Just being thorough.

**Comment by endless-sky** [comment]
If this is a Windows issue, there's not much that can be done to fix it. (There's no way for the game to distinguish a real screen resolution change that the user intended to make from a spurious change brought about by sleep mode.)
