### ISSUE TITLE
Bank on pirate planets

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3452]
Am I the only one who's thinking that it's strange that branch banks are available on pirate worlds, or that banks would even be allowed to deal with pirates? Or that human banks are available on alien worlds?

It probably would be too bad an idea to separate banking organizations, but I propose making banks unavailable on lawless worlds (Pirates, Unfettered Hai, anything Korath, etc.).

By the way, why anarchists are automatically counted as pirates? For example, planet "Freedom", inhabitants of which are willing to trade, and its spaceport description also says that it is frequented by merchants (which would try their best to stay away from pirates). I'd say they're Independents.

**Comment by KiLEdEnNis** [comment]
gameplay > realism case to me

**Comment by Zireael07** [comment]
I see no problems with banks on pirate planets. They could deal in an ES equivalent of bitcoins, after all.

**Comment by Amazinite** [comment]
It's not like pirate worlds are completely isolated from the outside world. Also: https://github.com/endless-sky/endless-sky/issues/667

>By the way, why anarchists are automatically counted as pirates? For example, planet "Freedom"

The inhabitant might be mostly anarchists, but the major players in the region are pirates, hence the world is a pirate world.

**Comment by Tadrix** [comment]
Republic banks? Since Reps are eager to control everything, seems highly unlikely. And seeing relations between Reps and pirates (kill on sight orders), it is also highly unlikely Republic would allow its banks have branches on lawless worlds. Also, since credit chips also exist (cash equivalent), banks would be robbed pretty often.

Also, #667 is irrelevant, I'm not arguing for separation of banks, but for depriving lawless worlds of them.

**Comment by Amazinite** [comment]
>Republic banks?

If that's the argument to be made against having banks on pirate worlds, I'd think that would create a massive plot hole with the Republic not just freezing the funds of anyone working with the Free Worlds. Perhaps all the banks are private and not owned by the Republic. As far as I know, we don't have any information in the game that out right states either scenario to be true.

>Also, since credit chips also exist (cash equivalent), banks would be robbed pretty often.

I also consider it unrealistic that we can land on pirate worlds all we want and never get robbed or shot. Banks on pirate worlds probably have lots of security, if you're looking for a logical reason for their existence. But in the end, as Kile said, this is just a gameplay over realism scenario. You could rationalize all you want as to why pirate planets shouldn't have banks, but at the end of the day it doesn't add anything to the game, and if anything it harms the player, or at least players who do pirate playthroughs. (It also harms the prospect of a pirate storyline, an idea that has been tossed around often, as a pirate player would be forced to bribe their way onto a planet to even access their loans and fines, giving them little reason to even play a pirate storyline if it's just a struggle to handle.)

**Comment by KiLEdEnNis** [comment]
> gameplay > realism case to me

yes?

**Comment by Kryes-Omega** [comment]
For one thing, legitimate banks are by no means the only way to get money, you might find loan sharks or pirate organizations willing to loan money on pirate worlds. 
And who is to say money has to be payed physically? Even now, most payments are done electronically. If the Republic can fine you in space I don't see why it would be a stretch to say you could pay off a loan on an inhabited planet, no matter the government.

**Comment by Bladewood** [comment]
It is a fact that [at least Greenrock has a bank.](https://github.com/endless-sky/all-content-plugin/blob/master/data/cheater%20plugin.txt)

**Comment by Tadrix** [comment]
> I also consider it unrealistic that we can land on pirate worlds all we want and never get robbed or shot.

Then perhaps it should change. I saw some proposed missions in which mercenaries try to take over player's ship. Some "adventures" could also happen on lawless worlds.

> It is a fact that at least Greenrock has a bank.

I've always assumed Greenrock is place player lays low after the robbery. Pirate bank wouldn't be so futuristic and shiny.

As for loan sharks, yes, it crossed my mind, but their interest would be exorbitantly high and missing a payment would have severe consequences, never mind any "credit ratings". Their clientele are those who can't get a loan in normal bank.

Which, by the way, could be a good thing in itself — when determining maximum amount of money which can be borrowed, usual banks would look only at reliable income, such as trade. Loan sharks wouldn't mind considering plundering and boarding reliable income, but loans would be at much higher % then at the banks.

**Comment by KiLEdEnNis** [comment]
> I also consider it unrealistic that we can land on pirate worlds all we want and never get robbed or shot.

> Then perhaps it should change. I saw some proposed missions in which mercenaries try to take over player's ship. Some "adventures" could also happen on lawless worlds.

that wasn't his point, he meant that that's unrealistic too but it's like this for gameplay reasons, it shouldn't change

**Comment by Kryes-Omega** [comment]
Copy and pasting most of this from the discord:

Pirate planets are not just empty hangouts for bandits. They are simply under the rule of what our governments see as pirates. Its the same deal, if we go to an unfettered planet we can still use their banks, even though they could be seen as thieves and pirates by certain standards. We accept their currency, do we not? Look at Bloodsea for example, in the campaign we see they are their own civilization that is labeled as a pirate world. If they don't use the Republic system, they must have their own. If we accept alien currencies with no problem, then local "pirate" currencies should be no different.
 
Even if some planets aren't developed enough for their own economy, I don't think 3 or 4 planets justify making a new feature. If we overhauled the ES economy and split the monetary systems, I think it would be changing the way banks work, but not removing them entirely, because like I said, nothing is stopping you from finding a loan shark on one of those backwater economy-less hives of scum and villainy, and surely you can pay your loans electronically, so there is no need to remove them. Making a new feature just because a few human pirate planets don't seem developed enough is too much effort for very little reward to the lore _or_ gameplay.

**Comment by Tadrix** [comment]
Fair enough.
