### ISSUE TITLE
Appstream IDs differ between appdata.xml file and Flatpak metadata

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3453]
Endless Sky's Appstream ID on Flathub is `io.github.EndlessSky.endless-sky` (https://github.com/flathub/io.github.EndlessSky.endless-sky/blob/master/io.github.EndlessSky.endless-sky.json#L2)

But Endless Sky's AppStream file uses a different AppStream ID: `endless-sky.desktop` (https://github.com/endless-sky/endless-sky/blob/master/endless-sky.appdata.xml#L3)

This causes problems: if the same app has different AppStream IDs in different distribution channels, then it'll confusingly show up as different apps in clients that can display content from multiple sources, such as GNOME Software and KDE Discover. Here's what it looks like in KDE discover:

![two endless skies](https://user-images.githubusercontent.com/1097249/34277638-e886cff6-e663-11e7-94e8-f0bb5458ef00.png)

The top one is the Flathub version, the bottom one is provided by my distro's packages.

If you unify the AppStream IDs (ideally standardizing on a reverse-DNS style such as `io.github.EndlessSky.endless-sky`), then Discover and GNOME Software (and similar apps) can perform de-duplication correctly, marking both as the same app and offering the user the choice of which version they want to install.

(also, ideally the description text, icon, and screenshots can be standardized between the Flatpak metadata and the appstream file).

**Comment by endless-sky** [comment]
Wouldn't `io.github.endless-sky.EndlessSky` be the correct identifier, if using the backward URL format?

@Barthalion, it looks like you are maintaining the flatpack - do you want to weigh in on this?

**Comment by Pointedstick** [comment]
Unfortunately dashes are not supported anywhere except the last element of the string (for more into, see https://github.com/flathub/org.filezillaproject.Filezilla/pull/1). So I'm afraid it has to be `io.github.EndlessSky.endless-sky`. That's what Flathub uses and that's what I'm recommending we do in my PR: https://github.com/endless-sky/endless-sky/pull/3455
