### ISSUE TITLE
Scanning republic Ships should be "hostile"

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#3457]
There is that one Free worlds mission that require's it, but it seems to me that Republic wouldn't want you to scan there vessels

**Comment by Bladewood** [comment]
It's the same reason why all those people on New Wales aren't in prison yet.

**Comment by KiLEdEnNis** [comment]
if scanning the Republic was a crime, scanning civilians would be too because of privacy stuff and at that point scanning itself would be near-illegal and shouldn't be sold at all
so as Bladewood says; gawking at ships isn't a crime

**Comment by Tadrix** [comment]
++ Besides, if Navy would be so averse to their ships being scanned, they would use interference plating.

**Comment by Pointedstick** [comment]
Doesn't make sense for multiple reasons:
- Game lore: Scanning is never mentioned as crime-worthy or considered a crime in other contexts
- Metagame: the mission in question is typically offered when the player is flying a small ship that couldn't possibly stand up to a hostile Republic Navy Cruiser (especially the heavy variant)

0% chance of being done, please close the issue.

**Comment by tehhowch** [comment]
If #3528 is added, one could make missions that offer in response to scanning a ship. In those missions, rep changes could be performed, among other things.

**Comment by Pointedstick** [comment]
Closing since as requested, this won't be done. With https://github.com/endless-sky/endless-sky/issues/3528, things like this could be added conditionally for missions that would benefit from the behavior.
