### ISSUE TITLE
Documentation (wiki) on ship personalities could make it which ships they apply to

### ISSUE THREAD

**Issue by tukoz** [endless-sky/endless-sky#3470]
Hi, following #2354, seems to me [ShipPersonalities (wiki)](https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities) should make it clear ship personnalities are for NPCs only, e.g. :

    (-) Each ship in the game can have a variety of "personality" flags that control its behavior.
    (+) Each [NPC](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#npcs) ship in the game can have a variety of "personality" flags that control its behavior.

Eventualy adding a KISS citation ;) such as (from afore-mentionned issue with a plural added to "ship"):

> the PLAYER controls its ships, of course it doesn't apply to it.

**Comment by endless-sky** [comment]
That's actually not true - ships spawned as part of ordinary fleets have a personality as well, defined in the fleet specification.

**Comment by tehhowch** [comment]
Your question is not very clear or understandable.. please rephrase it. (If English is not your native tongue, including the question or suggestion in your primary language, along with your English translation, will help us.)

**Comment by KiLEdEnNis** [comment]
the only confusing part is what he said about AI
but he basically asks confirmation if one can choose between "escorts fire never|frugal|always" in some settings (in-game preferences?)
