### ISSUE TITLE
libpng warning

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3474]
A few minutes ago I updated the game to the most recent version (`git pull`, `scons`). When I start Endless Sky, however, I get 24 times the following warning:

```
libpng warning: iCCP: known incorrect sRGB profile
```

I've never had this before. Maybe it has something to do with the latest commit, dc43cd6e836ab7cabd45fefc1147b87a4a3c3411 ?

**Comment by endless-sky** [comment]
See if commit e0b453a fixes that.

**Comment by Nescio0** [comment]
Yeah, it's solved now, there no longer is a warning upon running the game.
