### ISSUE TITLE
Gray vs grey

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3476]
Both are used.
"Gray" is only used twice, both in ship names (probably written by @Pointedstick). Everywhere else, "grey" is used.
Should probably fix that.

**Comment by czartrak** [comment]
change every instance to the word "Graey"
it's nice and neutral
problem solved

**Comment by KiLEdEnNis** [comment]
I think the game mainly uses American English, but this stuff happens every now and then and could be a problem if some contributors don't know/realize the game uses American English
maybe it could be stated clearly somewhere?

**Comment by Pointedstick** [comment]
Yeah, probably my bad. I'll standardize on Grey.

**Comment by tehhowch** [comment]
Imo nothing wrong with grey or gray. If you're going for American English then gray is the one to promote.

**Comment by KiLEdEnNis** [comment]
I have no problem with either one, but for a game I'd stick to only 1 of them, at least in conversations
ship names may be less important as they represent individuals making up their ship names, and some may prefer grey and others gray, but it may look like a mistake to some people

**Comment by Wrzlprnft** [comment]
i'd leave it as is, and add flavor news and space-chat-lines abput it

**Comment by KiLEdEnNis** [comment]
a news line for that new spaceport system: `Another riot started by linguists arguing over the words "grey" and "gray".`

**Comment by Amazinite** [comment]
Unless we consider it canon that at some point between now and 3013, all instances of English being used have been standardized to modern American English, I see no problem in both gray and grey being used in ship names, but outside of that it should be standardized (which it appears to be already).
