### ISSUE TITLE
Mass in the latest commit is absolutely broken

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3480]
In the latest commit, owned ships' masses are initially treated normally.
But once you reload your save, the ships' base masses no longer count toward the total mass. That is, only their outfits count toward the mass.
This means that a Punisher, for example, moves twice as fast after reloading.

On that note, hit force is also very weird right now. A heavy rocket and even a meteor missile have far more knockback than a particle cannon, while something like a finisher barely pushes ships around at all.

Also, as @comnom noted, outfit masses aren't even displayed in the outfitter...

**Comment by Hacklin** [comment]
Confirmed.

The ship's 'mass' attribute is not being saved.
Therefore, when you reload, a ship's hull mass is zero.

Note:
If you remove all outfits from a ship with a hull mass of zero,
the ship's 'acceleration' and 'turning' values in the outfitter are '0 / -nan'  ;-)

**Comment by endless-sky** [comment]
Fixed by merging #3481.
