### ISSUE TITLE
Feature request: Send selected escort to a location in current star system

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3484]
Either let mark a rally point (game would remember the last one, at least before the player jumps away), and then pressing a key would for selected escorts mean "go to the rally point ASAP", or make right-click on a radar mean "go there and stay (hold position there)".

Currently we have the option to keep them close or order them to stay, but not to send away.

Instances where it would be useful:

1. In battle, player notices that one of the escorts will soon be disabled. He orders them to retreat (instead of leading them out of combat himself, which detracts from the fight).
2. In battle, player expects more enemies to come from somewhere, so (s)he preemptively sends a welcoming committee while finishing previous ones.

EDIT: Or probably better not literally hold position, but rather _gather_ around this rally point (as if it were flagship and they were gathering around it). Next command to these ships would zero them in on a flagship again.

**Comment by tehhowch** [comment]
This is already largely possible: Right click, and selected escorts go to the designated position. If they get pushed away from it, they return to it. If you want to send them farther away, activate the clickable radar and use that.
When I finish up 3070 and its related pull, you'll be able to use the orbits scene for this purpose too (with any system).

What we don't currently have is an instruction to swarm about a given point.. so just tell your escort group to follow one ship and then order that escort to hold position somewhere.

**Comment by Tadrix** [comment]
I wanted to send them farther away. It seems like clickable radar isn't in the last stable version, so I didn't know it already existed.

**Comment by tehhowch** [comment]
Yep, #2679 didn't make it into v0.9.8 but has been in `master` since mid-October
