### ISSUE TITLE
Possible bug: Ship freezes while holding position after gathering order

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3485]
What it says on the tin. It's kinda silly they take side attacks and do nothing to respond (if equipped with forward guns).

**Comment by tehhowch** [comment]
Escorts should absolutely turn about while holding position - they do this for me as of v0.9.5 I think (probably earlier).

**Comment by Tadrix** [comment]
Indeed, they do now that I checked.
Reason I brought this up is I saw a few of my heavy freighters (which were coming to me with _gather_ command) being attacked and issued _hold position_ command instead. They froze and didn't return fire until they got disabled. v0.9.8. on w7. It's also possible they got disabled a little earlier than I noticed and still moved due to inertia.

**Comment by tehhowch** [comment]
Disabled ships coast to a stop, so that's my guess.
