### ISSUE TITLE
Display ramscoop in ship info

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3487]
It would be nice if ramscoop values would be displayed in the ship panel and info screens, perhaps on the same line as fuel, e.g.: `ramscoop / fuel capacity : 4 / 600` (cf. hull repair). Some ships have ramscoop values of their own and currently the only way to figure this out is by looking directly into the data files (e.g. the Kar Ik Vot 349 I seized turned out to have a ramscoop of 3).

**Comment by endless-sky** [comment]
The fuel line already shows `current / maximum` fuel if you're in flight, so I can't really add ramscoop as a third value.

**Comment by Nescio0** [comment]
How about displaying ramscoop on a new line then?

**Comment by Nescio0** [comment]
Although it's not the most important stat, it's not unimportant either. And currently there is no way to look up the actual ramscoop values in game, despite the fact that about fifteen ships have an integrated ramscoop. The Starling's integrated cloaking is at least mentioned in its description.

**Comment by KiLEdEnNis** [comment]
I get that ya want to be able to see it in-game without looking in the data files, but like jafdy said it's not really an important stat and I've never had any desire to look at it

**Comment by DingusShingleton** [comment]
Funny, I asked about this very thing almost exactly 2 years ago. #624. The only practical reason I had was to be able to compare afterburner usage to ramscoop generation. But yeah, not super important.

**Comment by Zitchas** [comment]
I, too, would like to have this information available somewhere. 

Personally, the ideal would be in the player info box alongside the max fuel, but at least having an info line in the Shipyard listing its ramscoop value would be useful.

Given the choice between knowing what my current ramscoop value is and knowing how much fuel I currently have, I would pick the ramscoop. After all, my current fuel is very often identical to my max fuel. But especially with the ability to frequently change ships based on what I'm doing, knowing whether or not the ship I am currently in has any (significant) fuel generating abilities is quite important.

**Comment by ChamEV** [comment]
I would like to add this, the only issue with this is space required and wording.  There are 4 possible variations required for the 3 attributes,

in flight:
fuel / gain / capacity: x/y/z
fuel / capacity: x / z
landed:
fuel gain / capacity: y/z
fuel capacity: z

With this wording, the first one runs out of space in some cases:
![image](https://user-images.githubusercontent.com/51398924/60752938-d504c280-9f80-11e9-9c5c-76721ebc556a.png)

So I'm looking for suggestions of better wording/synonyms that make sense and are compact.

The other option I'm looking at is when in flight, not showing regen at all which would solve the space issue.  It would be a slight incongruence with the landed version, but I think it may be better in 99% of cases.  When you're landed all you care about seeing is regen rate and capacity.  When in flight it's useful to know how much fuel a specific ship, typically escorts have.  You generally don't go to the ship info panel to check your own fuel as it's right there on the right.

When done I'll add tooltips for each option that explain each value shown, specifically shown how the regen value is calculated (average or max regen of ramscoop value for example).  This will also clearly show what effect stacking ramscoops has on a ship.

**Comment by Amazinite** [comment]
Closing in favor of just tracking all such issues of "I have X attribute to display" in #4215.
