### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#3488]
I have a 16K screen and the 200% zoom factor is **_really_** not enough to make the game UI comfortable _at all_. Increasing zoom factor further possible?

**Comment by tehhowch** [comment]
It requires a source change, currently. You'd also want better sprites for... everything :grin:, as even with the High-DPI plugin I think you'll find things a bit pixel-y at too high of a UI zoom.

So while the first is addressable, I don't know that you're going to see the second part addressed anytime soon (e.g. an @4x or @8x resolution would require a lot of rendering and texturing (and massive size inflation of the associated plugin repo))

**Comment by KiLEdEnNis** [comment]
can ya give us a screenshot or 2 of your game at the default & max zoom range? so we get a better idea of how it looks

**Comment by MCOfficer** [comment]
in case anyone thinks about it:
i tried upscaling of ES models with the AI from waifu2x.me (yes, that's actually the only free provider) some weeks ago, but the AI is trained for photos and doesn't work well with the clean edges of ship models:
![ffecc5ed9a98792f521ca28ce462833f_2_-1_photo](https://user-images.githubusercontent.com/22377202/34563034-36de5ae6-f151-11e7-916f-7dd966f78cd3.png)

**Comment by endless-sky** [comment]
First of all, do 16k screens even exist yet?

What OS are you using? I'm assuming you're using a high-dpi display, because a non-high-DPI screen with 16k resolution would be about 10 feet wide. The SDL graphics library used by Endless Sky ought to detect your operating system's high-DPI UI scaling settings and apply them automatically. If it's not doing that, that's really an issue with SDL.

**Comment by jafdy** [comment]
As far as I know the largest screen in existence right now is 5k, windows doesn't support more than 4k so if you have a 16k screen then A) your screen(s) cost more than the our computers and B) you have a computer that likely costs over $5000. So, unless your screen as actually over 10 feet and you walk right up to it then you should probably just have it treated as a 4k screen.

**Comment by gchapyzh** [comment]
![image](https://user-images.githubusercontent.com/8764280/34585228-aeb15c9c-f153-11e7-8ebb-9a60bfb27acd.png)

<details>
  <summary>Click to expand</summary>
  And this is as far as I think this joke should go. It started out as an issue about scaling a little over 200% for a 4k screen, but I figured this would make a funny thing to scare and confuse people with.

BTW that really IS a 16k screenshot created with a sim server that actually shows how the game would behave on a 16k screen. One day in the future, this will have to be covered :P

PS: And yes, my rather powerful desktop did have a jet-turbine-sounding-experience trying to handle a supposed 16k screen.
</details>

**Comment by endless-sky** [comment]
This does raise a related question, though - I've never actually tested Endless Sky on a Windows system with UI scaling applied. I think that without the game being marked "DPI aware," Windows won't actually give it a high-DPI rendering context. Is anyone using a high DPI screen on Windows?
