### ISSUE TITLE
Let Quarg sell some outfits?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3490]
For those who aren't belligerent enough to simply farm them, let Quarg sell some of their tech which they deem to be peaceful and not going in contrary with their directives (i. e. not selling Jump Drives, weaponry or Antimatter Cores (which in their opinion would only be useful to powering said weaponry))? Something rudimentary like this:
``` cython
outfitter "Quarg"
	"Nanotech Battery"
	"Medium Graviton Thruster"
	"Medium Graviton Steering"
	"Cargo Expansion"
	"Local Map"
```
Suddenly battery running ships would be a whole lot more feasible.

**Comment by jafdy** [comment]
It might happen in an upcoming Coalition-Quarg storyline. But not before.

**Comment by warp-core** [comment]
It doesn't really make sense for the Quarg to sell their outfits to the player. Only the Hai and Kor Efret are willing to trade without requiring the player to do *something* for them beforehand. Why would the Quarg, a species significantly more advanced than those mentioned above, decide that the player or just humanity in general should be allowed to use their technology?
It doesn't seem too absurd for the engine technology to be such that elements of it could be applied to make weapons more advanced than anything humanity currently possesses and the batteries allow for a ship to be filled with weapons and be able to run them continuously for significantly longer than they could be with an ordinary human battery.

**Comment by Nescio0** [comment]
Why would the Quarg want to sell anything at all? What would they gain? Presumably they're too busy with doing important Quarg things and completely uninterested in dealing with inferior beings.

**Comment by Amazinite** [comment]
>Only the Hai and Kor Efret are willing to trade without requiring the player to do something for them beforehand.

Notably, the Kor Efret don't even sell Korath technology beyond the command center, and the Hai only sell stuff to the player because they've been selling to humans in general for centuries.

**Comment by Bladewood** [comment]
Quarg != Heliarchs/Coalition.

**Comment by KiLEdEnNis** [comment]
adding that the Quarg will be reworked at one point (more outfits, ships, rebalances etc.), probably partially for a Coalition-Quarg storyline
this means we'd be giving players access to (OP) (likely to deprecate/rebalance) tech, for free even, which seems very illogical to me

so as Jafdy said:
> It might happen in an upcoming Coalition-Quarg storyline. But not before.

**Comment by Tadrix** [comment]
@Nescio0 Well, Quarg trade in commodities (indeed, all of them), so you could say they sell something.
