### ISSUE TITLE
Error in bombed-Zenith sprites

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3496]
Before:
![ocean7](https://user-images.githubusercontent.com/16506683/34590915-bfde4a00-f187-11e7-8208-b2d89efe90ff.png)
After:
![zenith hot](https://user-images.githubusercontent.com/16506683/34590918-c33c23d4-f187-11e7-9ce4-44cd4747042e.png)
After^2:
![zenith cold](https://user-images.githubusercontent.com/16506683/34590919-c46f9556-f187-11e7-96a2-2d04949ce286.png)
The bombed sprites have artifacts at their bottoms.

**Comment by MCOfficer** [comment]
nice catch, i hope you mean the black/red-ish bar and nothing else...

![1](https://user-images.githubusercontent.com/22377202/34605869-7af8ff94-f20d-11e7-9821-b760894e44a7.png)
![2](https://user-images.githubusercontent.com/22377202/34605870-7b1308bc-f20d-11e7-8edc-e0d936ca7bf2.png)

**Comment by endless-sky** [comment]
Fixed in fd5aa94.
