### ISSUE TITLE
Quantum Keystones / Quantum Key Stones, add additional function?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3497]
Hai description says: `More superstitious Hai claim that the stones somehow reduce the nausea induced by hyperspace jumps by making travel between star systems easier.`
So maybe we could make indeed jumps easier, by giving a small discount to fuel cost (to be not immediately noticeable), say 20%, making the drive consume 0,8 of the usual price. Players would discover they can make 1–2 additional jumps. (Or if this is too much, than less.) For this to work, keystone effects shouldn't stack (otherwise it would be 5 stones = infinite jumps).

This isn't very important but could be a nice touch.

**Comment by tehhowch** [comment]
They already have a second function.

**Comment by solardawning** [comment]
Hai superstition is based in fact- something they likely knew long, long ago, but have since forgotten the details.

It would spoil the fun to make it too obvious what they do!

**Comment by Tadrix** [comment]
I know what they really do besides being decorative.

A "genre-savvy" player will deduce that they do _something_ based on assumption that outfitters wouldn't sell a completely useless item. What I'm proposing is a double bottom — we don't show that stones save fuel, so player could have impression that that's the whole secret. But they are more likely to have these equipped when stumbling upon a real secret.

**Comment by jafdy** [comment]
Why would they save fuel? Hai don't throw up hyperspace fuel so if anything it should save you cleaning costs. Also, what you are asking for requires a code change for a very questionable function.

**Comment by KiLEdEnNis** [comment]
it's mostly a flavor & lore outfit, and these do have 1 function; access to the unstable wormholes
if you really want to talk about useless 1-ton outfits, one should mention the Reasoning Node & Control Transceiver

anyway I don't think the Key Stone & Keystone need anything else
