### ISSUE TITLE
Jump minimap, show all discovered connections

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3498]
This could be considered low priority, but it was bugging me for some (rather long) time.

When jumping, mini-map at the top shows origin and destination systems along with connected neighboring systems. It would be logical and more recognizable if connections between neighboring systems (if at least one of them is explored, so this connection is visible on the galaxy map) would be shown also.

**Comment by tehhowch** [comment]
I think I hear what you're saying, but show a photo and remove the doubt for us

**Comment by Tadrix** [comment]
![minimap](https://user-images.githubusercontent.com/17566547/34595328-c0a0beb6-f1df-11e7-8a55-a1d1a6eebace.png)

**Comment by KiLEdEnNis** [comment]
so basically once a player made a Jump Drive only jump, they'll see a small "connection line"? partially nice but it could clutter the map a lot w/ even more lines, and those jump lines would cross normal hyperspace lines as well
if this happens, I want a preference to turn this off, and less obvious lines so it's clear yet doesn't stand out

**Comment by endless-sky** [comment]
If all the neighbor lines were drawn, there would be a lot of them, and many of them would intersect. In my opinion, that would look cluttered and confusing.

Right now, the map shows your current system's "neighborhood" with a circle drawn around the system. That might be a less confusing option. But I still think it'd look cluttered. The mini-map is just intended to show you the current neighborhood you're in, and the shape of the hyperlink connections is part of what makes that neighborhood recognizable.

**Comment by Tadrix** [comment]
Not jump lanes, only hyperspace lanes. I shouldn't use different color on the second image. The idea is to show all hyperspace connections between shown systems, if they are discovered and visible on the galaxy map. I've marked connections between Io Mann and Wah Oh systems, and connections between Heia Due and Io Lowe systems, because they are marked on the mini-map and connected via ordinary hyperspace lane.

Apparently I have trouble getting my point across. >< These yellow lines should be usual white lines. Gotta remember not to make issue posts when sleepy.

**Comment by mdsmestad** [comment]
@Tadrix I have to agree with MZ on this one, this has the potential to make the map look cluttered

**Comment by Tadrix** [comment]
@endless-sky @mdsmestad As I said one post earlier, I didn't propose to draw jump lines, only hyperspace lines — in other words, those that are currently visible on map.

I find it confusing that systems which are shown to be connected on the galaxy map aren't connected on the mini-map.

**Comment by jafdy** [comment]
Perhaps put the hyperlanes on the second order systems (the ones that you're not jumping between) in as lines that fade out.

**Comment by endless-sky** [comment]
This is really just a question of how far out you "cut off" the mini-map. The behavior you're suggesting (draw the endpoints, all their hyperlinks, and links between their hyperlink endpoints) isn't necessarily any better that the current behavior (draw the endpoints and all their hyperlinks), just different.
