### ISSUE TITLE
Free Worlds Escort, empty Freighters

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3503]
These ships are supposed to carry `weapons and ship outfits that will be used to build new ships for the Free Worlds`.

![emptyfreight](https://user-images.githubusercontent.com/17566547/34636280-7d8b7324-f2a6-11e7-8927-f48bde3f226a.png)

**Comment by chickendelight** [comment]
Is this before or after they go to tarazed?

**Comment by Tadrix** [comment]
Right after, on the way back.

But before Tarazed these freighters shouldn't be empty either, because on arrival `The merchant captains sell their trade goods`…

**Comment by tehhowch** [comment]
Easy fix, give the ships cargo in the mission description.

**Comment by Tadrix** [comment]
Perhaps [wiki entry](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions) is outdated, but I don't see a way to give cargo to NPCs.

**Comment by Fzzr** [comment]
It can definitely be done, see https://github.com/endless-sky/endless-sky/blob/master/data/fleets.txt#L14. I don't know if that applies to mission npc fleets though. Give it a shot!

**Comment by Tadrix** [comment]
Should work, I guess, but what these numbers behind cargo mean?

I'm guessing trade goods on the way to Tarazed would most likely be Luxury Goods (which would explain pirate activity as well). One can sell them at a good price there. But on the way back cargo needs to be warship outfits.

**Comment by Fzzr** [comment]
I'm told that's the number of different commodities that will be randomly added. I don't know how or if it's possible to specify exact contents, alas.

**Comment by tehhowch** [comment]
Outfits can currently be specified for NPC fleets (see #417 ), though this is not yet possible for specific ships. Per my comment in 417 I'd like to see a good discussion and consensus on the syntax to support before adding the feature.
