### ISSUE TITLE
Mac build fails since news system was added

### ISSUE THREAD

**Issue by Fzzr** [endless-sky/endless-sky#3508]
Endless Sky no longer builds for macOS with Xcode 9. Investigation says the responsible commit was dc43cd6e836ab7cabd45fefc1147b87a4a3c3411, which added the news system.

Environment info:
macOS High Sierra 10.13.2
Xcode Version 9.1 (9B55)

Build performed with no alterations to Endless Sky source. Environment set up per https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#mac-os-x other than using the most recent version of Xcode. bbef21984b45b764bf553e8b2dfc102d9a5ffc51 builds and runs as expected with no warnings.

Error output is as follows:
```Undefined symbols for architecture x86_64:
  "News::Load(DataNode const&)", referenced from:
      GameData::LoadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in GameData.o
      GameData::Change(DataNode const&) in GameData.o
  "News::Name() const", referenced from:
      SpaceportPanel::UpdateNews() in SpaceportPanel.o
  "News::Matches(Planet const*) const", referenced from:
      GameData::PickNews(Planet const*) in GameData.o
  "News::Message() const", referenced from:
      SpaceportPanel::UpdateNews() in SpaceportPanel.o
  "News::Portrait() const", referenced from:
      SpaceportPanel::UpdateNews() in SpaceportPanel.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Let me know if any other information is needed.

**Comment by tehhowch** [comment]
Needs to be added to the XCode project, most likely.

**Comment by Fzzr** [comment]
Got it. Submitted PR to fix.
