### ISSUE TITLE
Pirates should spawn based on carried cargo value instead of fleet's cargo space

### ISSUE THREAD

**Issue by Staferfield** [endless-sky/endless-sky#3511]
So the thing is, I was always plagued with pirates everywhere I go after I got a large fleet running. It's very annoying especially when I depart from planet and they just spawn above my head bombarding my ships without being able to fight back for some seconds. 

I always thought it depend on how many escort I have (when I park my fleet they're all gone) and perhaps my net worth. But then I got fed up with them and did some test. I found out that it's mostly based on my fleet's total cargo space.

Note: those two dreadnought are from FW mission, too lazy to finish it before posting this

This one with a total of 10k empty cargo space
![no cargo](https://user-images.githubusercontent.com/25031487/34649846-2d3ce25e-f3fa-11e7-816c-6348d3d234b2.jpg)

This one with 10k of luxury goods, nothing much changes except different variant
![with cargo](https://user-images.githubusercontent.com/25031487/34649891-c480b41a-f3fa-11e7-9943-efda3ca07c0c.jpg)

And wherever I go (in human space), this happen
![cargo space travel](https://user-images.githubusercontent.com/25031487/34649913-6bf924de-f3fb-11e7-9ca0-98fb8a97af5c.jpg)

When I park my fleet, my bactrian have 450 cargo space
![parked](https://user-images.githubusercontent.com/25031487/34649963-2f50527c-f3fc-11e7-9311-2077356448a3.jpg)
When I keep some around
![20180107213725_1](https://user-images.githubusercontent.com/25031487/34650023-216e9f3c-f3fd-11e7-84f2-e11b04f38f0f.jpg)

And this is what happen when I turn those 10k cargo space into outfit space, everything is eerily quiet
![outfit expansion](https://user-images.githubusercontent.com/25031487/34650046-81b006e2-f3fd-11e7-8124-4d66d9dda9ea.jpg)

Just for the heck of it, I also try to fly a ship with 1M cargo space
![storage ship](https://user-images.githubusercontent.com/25031487/34650091-3f13e302-f3fe-11e7-826c-c496daa68e05.jpg)

So my suggestion is, why not use cargo worth to measure wether or not you're a valuable target for pirates? Won't this also stop people from plundering too much? I mean those pirates are attacking those heavily guarded merchant for measly cheap commodities, while I'm wandering alone with a reactor worth for 5M and nobody came?

If not, then at least check how many cargo space is used instead of just total cargo space?

**Comment by Hadron1776** [comment]
It would help if you got more warships.
Arming your freighters helps with pirate attraction, but I think warships are far more efficient at that.

**Comment by KiLEdEnNis** [comment]
> Pirates should spawn based on carried cargo value instead of fleet's cargo space

pirates wouldn't really know how much cargo one has beforehand, they just see several big-ass freighters and ambush them

**Comment by Nescio0** [comment]
If you open up your fleet overview (press I) you can see some ratings at the left. The values are global, based upon all your active ships everywhere. There won't be pirates if your fleet's firepower exceeds its cargo capacity. 
I personally happen to like those suicidal pirate fleets because they allow me to rehabilitate my reputation (which I needed after demanding tribute from all human planets). However, if you don't want those constant pirate encounters, things you can do are:
* leave human space to avoid pirates
* park freighters to lower your fleet's cargo capacity
* acquire more heavily armed warships to increase your fleet's firepower

Also, hostile ships prefer to target armed ships over unarmed ones. And unarmed ships won't suicidally attack, obviously. So if you equip your freighters with anti-missile turrets only, they're more likely to survive.

Because there are only pirates

**Comment by Staferfield** [comment]
@Hadron1776
Nah, I don't need warships actually. Wherever my behemoth go, many ships burned in flames. On my previous playthrough I used only warship to do FW mission, but at some point I actually ran out of money because of crew salaries.

@KiLEdEnNis 
Ah, before I continue I'd have to say that english is not my native language. I rarely speak nor write in english, only reading mostly. 
> pirates wouldn't really know how much cargo one has beforehand

How come? When the pirates is on the rise, the navy mostly guarded paradise worlds, the gap between the poor and the rich is so tall? Some merchants could have sold information about valuable targets to pirates just for additional money, even the navy could have done the same about the ships they scanned.

Also, is the tittle misleading? In case anyone misunderstood, what I hope is the game to consider wether or not I'm actually carrying cargo. Currently it doesn't matter as long as my cargo capacity is high, even when I'm carrying nothing at all. Either I have to park my fleets, reduce cargo capacity with outfits expansion, change them to any ships with lower cargo capacity, or just go to the Hai (or even the Wanderer) where I can actually make more profit than in human space.

Even better would have to make the game consider about my cargo worth, so basically less pirates if I carry food and more if I carry more valuable cargo like luxury goods.

@Nescio0 
Ah that's nice to know, I didn't know if combat rating affect the number of pirates. Right now I have combat rating of 10 (fearsome scrapper), how much is the cargo limit then? Around 3000?

> I personally happen to like those suicidal pirate fleets because they allow me to rehabilitate my reputation

Yeah, I don't mind suicidal pirate actually, but when they shows up everywhere? it's getting repetitive and annoying sometimes. Perhaps make them shows up on the planed visited and not the one I just departed?

Clarification: In case anyone didn't understand about the pirates that I'm talking about, it's the ones that's waiting to rob me at the center of the system because of high cargo capacity, not the ones that jumped in from another system.

And then when I'm writing this, I actually realized another things. What about crew and bunks? It turns out transporting people with 12 Star Queen is actually very very much safer than being space trucker with 6 behemoth.

In the end, I'm just giving suggestion and opinion anyway. If my writing sounds forceful etc, please forgive me.

**Comment by KiLEdEnNis** [comment]
> > pirates wouldn't really know how much cargo one has beforehand

> How come? When the pirates is on the rise, the navy mostly guarded paradise worlds, the gap between the poor and the rich is so tall? Some merchants could have sold information about valuable targets to pirates just for additional money, even the navy could have done the same about the ships they scanned.

how would other merchants know how much cargo YOU have at all? and are you claiming the Navy could even sell such information to pirates? the first is unlikely and the second is just a straight no

so I'll repeat: the pirates just see several big-ass freighters, there's nearly 0 chance they would know beforehand (your explanation could be true in <1% of the cases)

**Comment by Nescio0** [comment]
>  I didn't know if combat rating affect the number of pirates. 

No, it doesn't. Only cargo capacity and fire power do. E.g.:
![screenshot from 2018-01-07 23-09-03](https://user-images.githubusercontent.com/21634324/34654717-eec5d5de-f3ff-11e7-9d0e-ada981f2819f.png)
means lots of pirates and:
![screenshot from 2018-01-07 23-05-15](https://user-images.githubusercontent.com/21634324/34654816-ff260718-f400-11e7-9576-970b0fdef13a.png)

implies no pirates.

So if your fleet has more weapons and less cargo capacity, those pirates will disappear.

> And then when I'm writing this, I actually realized another things. What about crew and bunks? It turns out transporting people with 12 Star Queen is actually very very much safer than being space trucker with 6 behemoth.

Irrelevant.

> In the end, I'm just giving suggestion and opinion anyway. If my writing sounds forceful etc, please forgive me.

No need to apologize; we understand your suggestion. There are just several reasons why it is not really as good an idea as it might seem at first glance.

**Comment by jafdy** [comment]
That feature is not in the current release version.

**Comment by Staferfield** [comment]
@KiLEdEnNis 
> they just see several big-ass freighters and ambush them

> so I'll repeat: the pirates just see several big-ass freighters, there's nearly 0 chance they would know beforehand (your explanation could be true in <1% of the cases)

Yet they know wether my ship have cargo capacity or not :frowning: See second screenshot from bottom.

Kinda irrelevant, but there's a ship (not in game yet) called "Class C Freighter" with this description
> The Class C "Freighter" is a stealth warship designed by the Syndicate for baiting pirates with the offer of a seemingly helpless, ordinary bulk freighter. Inside, its cargo space has all been converted into drone bays, allowing it to carry a dozen combat drones.

It kinda bugged me that they won't actually do their job at baiting pirates, because they only have 20 cargo space.

@Nescio0 
As @jafdy said, it's not in the current released build (0.9.8). It's useful addition to the game though.

> And then when I'm writing this, I actually realized another things. What about crew and bunks? It turns out transporting people with 12 Star Queen is actually very very much safer than being space trucker with 6 behemoth.
> Irrelevant.

Indeed, it's irrelevant. I just want to mention that I could do numerous transport mission in defenseless ships without ever worrying about pirates at all. Is this fine?

**Comment by jafdy** [comment]
The whole point of this is to prevent the exponential star barge strategy. And in that sense it works.
