### ISSUE TITLE
Off-center UI in planet view

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3512]
![offcenter](https://user-images.githubusercontent.com/17566547/34652393-d0204eda-f3e5-11e7-9951-375d16731a47.png)
One can see that it's off to the left. Is this how it was intended?

**Comment by jafdy** [comment]
What's your screen resolution?

**Comment by Fzzr** [comment]
Also, what's your view zoom factor? I see similar behavior when mine is above 100%.
<img width="1546" alt="screen shot 2018-01-07 at 11 01 37 am" src="https://user-images.githubusercontent.com/1037883/34652966-2991643c-f39a-11e7-8202-03f42ce5a4fe.png">

**Comment by Tadrix** [comment]
Zoom factor: 100/100
Resolution: 1280×1024

But it isn't isolated to me: [All](http://blog.homoeoteleuton.com/wp-content/uploads/2015/08/EndlessSkyScreenshot1.png) [these](http://i1-mac.softpedia-static.com/screenshots/Endless-Sky_15.jpg) [pictures](http://www.trishtech.com/wp/wp-content/uploads/2017/10/endless-sky-1.jpg) [on](http://images.akamai.steamusercontent.com/ugc/144507538377120994/6E577C0086BE8B6AD627F68AF8DFAE6E2573395E/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|1024:*) [Internet](https://endless-sky.github.io/images/screenshots/trading.jpg) confirm this.

**Comment by endless-sky** [comment]
It's so that at very small resolutions, the UI info on the right hand side (your ship's status, location, etc.) will be visible. When you're landed, the targeting and radar info is much less important.

**Comment by Tadrix** [comment]
Is there a way for the detect those small resolutions and act accordingly (to center when there's an opportunity to do so)?
For example (pseudocode):
if screenWidth > smallScrThreshold ⇒ center planetUIblock
  else ⇒ planetUIblock.Xmax = screenWidth - rightUIblock.width - planetUIblock.width
etc.

Because as now it looks a little weird (we are used to it, but nonetheless).

**Comment by tehhowch** [comment]
In theory you can move it in your local game by modifying the relevant data/interfaces.txt entry. It's entirely possible there are a number of entries that need to be altered to do this properly though - I haven't tried myself.

**Comment by comnom** [comment]
> It's entirely possible there are a number of entries that need to be altered to do this properly though

Several yes (everything is shifted 60 from center), but the planet/spaceport descriptions aren't in the interface definition unfortunately. I added a box definition to my local copy for it (it bugged me too). I'll pr it when I'm at my machine next if there's interest and nobody gets to it first.

**Comment by Tadrix** [comment]
>  you can move it in your local game

I consider it a UI problem and not my personal problem. In theory I could solve it for just myself until the next version of Endless Sky is released :), but it would be nice if we solved it for everyone — by offsetting planet panels only when they threaten to block ship stats.

**Comment by tehhowch** [comment]
If you do your modification in a plugin's data/interfaces.txt, that modification is yours until you remove that modification. I don't understand why folks modify files within the base game's folders that get altered each release version - that's just asking for hassle and errors from undefined references :grin:

**Comment by comnom** [comment]
> but it would be nice if we solved it for everyone

Which a moddable interface does. The only thing it lacks is a box (well a wrapped text, but that's not in yet) element for the description, then everyone gets to have their cake and eat it too with minimal source code changes.

The dev gets the offset UI, and you get to change it. If you're nice I'll even drop a link to the plugin when it's possible. ;)

**Comment by comnom** [comment]
Scratch that bit about only needing a box. Now that I'm back on that copy, I realize that I was working through the other panels as well (trade, banking, etc), which all need to be touched on for moddable positioning.

I still maintain that a moddable interface is better than special scaling for this one offset interface, but it's going to be more involved than I let on.

**Comment by TheGiraffe3** [comment]
This has been fixed now, correct? I haven’t ever seen this problem.

**Comment by Saugia** [comment]
I don't believe I have seen this behavior recently, so yes I will close this. Should the issue arise, feel free to open a new one (or whomever may run into this).
