### ISSUE TITLE
Sand cell not for sale

### ISSUE THREAD

**Issue by speedstyle** [endless-sky/endless-sky#3519]
The Hai's Sand Cells are not for sale, even on their homeworld. Is this intentional? They are balanced (or at least balanced as much as other Hai technology), so there is no reason not to sell them.

**Comment by tehhowch** [comment]
There are other things that exist in game and are not for sale. This is intentional at this point in time (they will be reworked or included in future content updates).

**Comment by Bladewood** [comment]
In this particular situation, it's basically just for lore; the Sand Cells were specifically designed for the Fleas.

**Comment by Amazinite** [comment]
The Pond Strider, Sand Cell, Flea, Railgun, and "Baellie" Atomic Engines are all not for sale yet. They were designed to be created by the Hai as a counter to the new Unfettered Solifuge, but that part of the story has not been written yet.

**Comment by speedstyle** [comment]
(To be honest I added this because I found myself wanting to buy one, and unable to, rather than because I had particularly thought it through in terms of the game as a whole)

**Comment by KiLEdEnNis** [comment]
ya could always just edit one in if ya really want it that badly, ya can even deduct the price of one from your credit balance to make it less cheating
or just add them to an outfitter
