### ISSUE TITLE
trade UI tooltips

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3521]
when mousing over (or selecting with keyboard ?)
display profit or amount worth as a tooltip ? -further modified by CTRL, ALT, SHIFT quantity modifiers

**Comment by Hadron1776** [comment]
You can already see the profit per unit of commodiity in the trade UI
...just multiply that by the amount you're selling : )

**Comment by KiLEdEnNis** [comment]
> ...just multiply that by the amount you're selling : )

this also teaches the people from these days to do some actual calculating & using their brains, which is good since a lot of people grab their phones for something like 43 + 28 these days & eventually forget how to think at all
"dumbifying" the game this hard would be a no for me & I hope for the rest too

**Comment by whismerhill** [comment]
Generally speaking, while playing, I never calculate cause it's not necessary to know the exact amounts by any means
hence why showing them seems useful to me.
and yes I do calculate by head (it's just faster) but when it's 2 AM and I'm tired, I don't always want that. ;)

Just my opinion though

**Comment by Hadron1776** [comment]
>  not necessary to know the exact amounts by any means
> hence why showing them seems useful to me.

Well, which is it?

**Comment by whismerhill** [comment]
Lol ni catch, though they don't really contradict each other: it's not necessary to know the exact amounts but showing them would be a nice addition as far as I'm concerned. also made updates to the post

**Comment by KiLEdEnNis** [comment]
> I never calculate cause it's not necessary to know the exact amounts by any means.

> but let's be realistic here, endless sky is not hard to make money with by any means.

if one doesn't need to know the exact values why bother to implement it then?

**Comment by Brick63** [comment]
something that hasn't been brought up yet is that it shows your profits from sales when you take off

**Comment by jafdy** [comment]
It has to be put somewhere. that's kind of a big problem when even you don't sound convinced it's a good idea.

**Comment by whismerhill** [comment]
@KiLEdEnNis 
you're right I guess, depends on how you see it. it's not "needed" it would be a nice bonus just like you could use toilets in DUKE3D, (first game to implement it, and been that way ever since for most games !)

@Brick63 
yeah about that. yes that's good but I never see those for two reasons : 
-1 when taking off the game goes back to real time & there's plenty other stuff to do
-2 there's plenty other chatter & stuff going on
-3 the timing is just not right. when taking off whatever I had to do on the planet is ended  and the next objective is in sight

anyway that's my point of view

**Comment by jafdy** [comment]
I would call using a toilet an easter egg, not a feature.
