### ISSUE TITLE
Show discounted outfits checkbox

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3522]
pretty much the title
would go along with those other checkboxes  ("show outfits for sale"...)

Alternatively highlight item borders that have used outfits or something

edit : or both => a checkbox that highlights instead of filtering

the reason is that : 
 - currently if there's outfits I wanna keep from ships I will sell, I need to first strip them of outfits & put them on my ships in cargo & then sell the ships. 
 - if such a thing as showing discounted outfits existed, I could just directly sell a bunch of ships then check out whatever is discounted at a glance without having to check for EACH & every item sold by the outfitter. It would just be much faster.

there's plenty other example usage scenarios where you wanna keep discounted outfits and this could get handy.

**Comment by tehhowch** [comment]
Is this not already possible? Simply uncheck the "show for sale" box.

**Comment by whismerhill** [comment]
nope with "show outfits for sale" unchecked, it will show items on the selected ship & that's all

"show used outfits" would either filter out or highlight items which are not 100% price (that you sold)

**Comment by Hadron1776** [comment]
(You can select multiple ships)

**Comment by tehhowch** [comment]
Note that "used" has multiple meanings. I interpreted it as those outfits that are being used i.e. are installed on a ship.
It appears @whismerhill actually means "used" as "sold for less than full price" which is not its definition.

A better post title is "Button to show discounted outfits"

**Comment by whismerhill** [comment]
hooooo facepalm

**Comment by Brick63** [comment]
For what reason should this be implemented

**Comment by ghoulavenger** [comment]
@Brick63 why not? When you sell ships or components to the outfitter, you have discounted outfits available for purchase that do not appear that way, they just show up as normal outfits (although it might show that it is discounted in its price section). It simplifies grabbing loose outfits from captured ships significantly (selling ships will strip the outfits and put them for sale in the outfitter). Not to mention if you're just swapping outfits around it could make it easier to just see the outfits you're looking for.

I don't see it as a high priority but I don't see a reason for it not to be implemented either.

**Comment by Brick63** [comment]
okay my question was more inquisitive than anything and i was looking more for whismers reasoning but not to discount others

**Comment by whismerhill** [comment]
the reason is that : 
 - currently if there's outfits I wanna keep from ships I will sell, I need to first strip them of outfits & put them on my ships in cargo & then sell the ships. 
 - if such a thing as showing discounted outfits existed, I could just directly sell a bunch of ships then check out whatever is discounted at a glance without having to check for EACH & every item sold by the outfitter. It would just be much faster.

there's plenty other example usage scenarios where you wanna keep discounted outfits and this could get handy.

**Comment by Brick63** [comment]
okay should probably include that in the issue in the first place in the future

**Comment by whismerhill** [comment]
thought it was obvious but ok

**Comment by ghoulavenger** [comment]
@whismerhill It's not entirely obvious to people that don't scavenge for parts from pirate ships. Usually it's pretty obvious with other races what parts don't come from the outfitter they are selling to. And not everyone scavenges pirates for parts because you can just buy most of them (which makes the early pirate looting key scavenging time). Exceptions do happen, like ionic afterburners on marauder vessels if you didn't go checkmate branch -- but again thats also pretty obvious since you wouldn't be able to buy the ionic afterburner.

**Comment by tehhowch** [comment]
This would be addressed by #3556 
But, there is no guarantee that pull will be merged.
