### ISSUE TITLE
Durax and other galactic cul-de-sacs

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3524]
There's nothing. No inhabited planets, no caravans passing through. In case of Durax especially, where the only exit is a pirate system.
1. What are pirates doing there? It's not that they'll have a chance to plunder someone (there are no merchants in this system). Meanwhile, I burned several pirate Falcons and many Splinters, which shouldn't really be there.
2. What are Syndicate ships doing there? They just passed an entire pirate systems just to visit? (Where such dead ends aren't covered by pirate systems, patrolling is still welcome.)
3. What are Korath doing there? There's no one to raid. They should move on to Alcyone or Zaurak. As a transit point it's fine, though.

For what they are, these systems receive way too much traffic (with the possible exception of Korath, since this is their transit point),

**Comment by Amazinite** [comment]
1. The pirates are there because the Korath are there
2. /shrug
3. The Korath are there because the pirates are there

As for dead-ends in general (and other systems one would never need to visit after discovering them), I've actually taken notice of them and plan to include them in later content of some sort. I even have a list:
* Boral (central Dirt Belt)
* Kugel (between Core and Paradise Worlds)
* Sadr (near Tarazed)
* Umbral (near Tarazed)
* Lolami (northern Dirt Belt)
* Regulus (western Near Earth)
* Ipsing (central Dirt Belt)
* Naper, Hintar, and Orvala (eastern Dirt Belt)
* Gamma Cassiopeiae (Core)
* Unagi, Tortor, Gorvi, Danoa, Sospi (Far North)
* Nocte (Near Earth)

**Comment by Hadron1776** [comment]
@Tadrix Durax is a case where the only reason one party is there is because the other is.

**Comment by Tadrix** [comment]
> The pirates are there because the Korath are there / The Korath are there because the pirates are there
> Durax is a case where the only reason one party is there is because the other is.

This could devolve into the chicken and egg question, but I'd like to point out that before Korath started raids nobody had any business there and there was no pirates (so Korath obviously didn't have any business there); and that it is difficult to intercept a Korath Raider equipped with a jump drive between jumps, so what pirates wanted to do seems to be an exercise in futility. And, judging by the lack of Korath outfits on pirate ships, they didn't succeed at all. At the rate they are losing their ships there, one could conclude they should stay away from that system. Is common sense an alien concept to pirates?

I get Korath taking their due if it's presented on a silver platter, but pirates there seem to have a death wish (more than the others).

> (and other systems one would never need to visit after discovering them)

Slightly offtopic, but is something planned for Quarg systems (such as the trio southeast of Tarazed)? They too are just sitting there. As an example, Albert Foster's Early Adventures with the Quarg could be a blast. :)

**Comment by whismerhill** [comment]
pirates in general do stupid stuff the whole game. 3 clippers attacking 3 bulk freighters & their escorts for example (they lose)

**Comment by Tadrix** [comment]
One could wonder, where do they get all these ships in that case…

**Comment by KiLEdEnNis** [comment]
> One could wonder, where do they get all these ships in that case…

anarchist shipyards, humans that get a ship & later go into piracy, whatever
how is that helpful at all though? pirates were initially made to have some sort of enemy to fight, not for full realism

**Comment by Wrzlprnft** [comment]
if there is no lore answer yet, don't aim to eliminate the irregularity, but make a flavor story about it. it is an opportunity.

**Comment by solardawning** [comment]
Secret pirate asteroid base slave market in Durax! You heard it first here!

**Comment by chickendelight** [comment]
Secret bases on every "uninhabited" system!

**Comment by solardawning** [comment]
Actually, there's a good seed idea for a new feature.
The planets that are currently unlandable/uninteractable? What if players could scan them?

Normally scanning an uninhabited planet you haven't yet scanned would just generate an item in your cargo hold representing that scan data, which you can sell.

Then some planets could have hidden bases, which are revealed on scanning, making the planets landable. Or, in the case of some... launch a fleet to attack you.

**Comment by Tadrix** [comment]
This would be especially good in cases where such a dead end you just checked and jumped out of spawns some hyperdrive-equipped pirate who catches up and tries to take part in your killing, plundering and generally minding your own business routine. With @solardawning 's suggestion the answer to this would be "you never know".

**Comment by tehhowch** [comment]
Earth Shapers use atmospheric scanners already.

Open a feature request (or change the intent of this issue) for a new mission location, "scan", which would match against targetable objects (i.e. not random stellarobjects, only ships and defined planets) and support such in-space mission creation.
(Adding scanning of the untargetable stellarobjects is possible but probably would be best served as an extension rather than an initial feature, since it might require supporting the automatic generation of a serializable planet definition, in order to maintain a reference to the initiating object.)

**Comment by endless-sky** [comment]
I used to live across the street from a large church parking lot that used to have to have cars drive into it, and groups of teenagers hang out in it, late at night when the church was definitely not open. Eventually people figured out that there were drug deals going on and the police started sending a squad car every once in a while to just circle around the lot and encourage folks to move along somewhere else.

That is to say, I can think of many reasons that pirates might want to hang out in uninhabited systems. They could be exchanging contraband, or repairing their ships, or just laying low for a while.

**Comment by KiLEdEnNis** [comment]
> That is to say, I can think of many reasons that pirates might want to hang out in uninhabited systems. They could be exchanging contraband, or repairing their ships, or just laying low for a while.

that's fine, but at some point it may be worth to make those Pirate ships board each other & actually trade some commodities, to make it realistic

**Comment by tehhowch** [comment]
@KiLEdEnNis #3381

**Comment by Tadrix** [comment]
That's a great explanation!

Pirates would be drug dealing teenagers, Syndicate forces would be the police squad car (albeit in Durax's case it's like they need to drive through a really nasty neighborhood named Alcyone just to get there), and the Korath are these thugs with baseball bats who on slow nights come over to roughen up teenage junkies just for grabs and also for a little fun.
