### ISSUE TITLE
Interrupted jumping of planned route with a fleet

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#354]
Often when jumping a planned route with a fleet (i.e. in an escort mission), you might want to belay jumping. If you want to blast some pesky pirates for instance.
However, if you hold the jump key until the board is green you can't manoeuvre any more. It's kindof harsh to interrupt your auto-planned-jumps by steering every time you enter a sector.
What about an option (preference toggle) to acknowledge continued jump, for instance by tapping the jump button once more? Or another jump button to jump to the next system in a plotted course, but not automatically continue jumping?

**Comment by endless-sky** [comment]
If you have not started jumping yet, steering in either direction will stop you from jumping. So, for example, if you are coming out of hyperspace and you want to cancel your next planned jump you can just hold down one of the steering keys.

**Comment by wkoot** [comment]
Yeah that's what I'm doing now :)

**Comment by endless-sky** [comment]
Ships won't prep to jump if the flagship is not prepping to jump. There's no way for them to read your mind (or at elast there won't be until some sort of comprehensive fleet control UI is added).
