### ISSUE TITLE
shortcut key "i" for install will buy outfits too

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3544]
seems like an issue to me or at least not desirable
ALT+u will uninstall up to 500 outfits & put them in cargo just fine
ALT+i will first install outfits up until there is none at which point it'll buy the rest

doesn't sound desirable to me when you can use "b" or the button to buy instead for the exact same effect
example usage : 
-get into an outfitter that sells rifles
-transfer 150 rifles from previous capital ship to new capital ship
-using ALT+u & then ALT+i will put 500 rifles on your new capital ship, 150 of which are old ones.

**Comment by tehhowch** [comment]
`i` only works if you don't have to buy the outfit (e.g. it is in cargo), while b always works (and just pulls from cargo first). There could be an issue where the loop called by `i` doesn't stop once you are out of cargo outfits - you are suggesting it not ever buy outfits, i.e. stop at 150/500 requested?

**Comment by whismerhill** [comment]
yes exactly. since as you said pressing "i" will not buy outfits if none are in cargo

**Comment by tehhowch** [comment]
Addressed in #3553

**Comment by tehhowch** [comment]
Don't close this until it's been merged and milestoned.

**Comment by tehhowch** [comment]
Resolved by efd11f1e37f6168ca43e5cd7b504e7bc68fc906f
