### ISSUE TITLE
shortcut key "u" will sell if there's not enough cargo space available

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3546]
not sure if it's intended behavior, or desirable

in my humble opinion it should not do anything
because consistency with other actions : 
 - buying without enough outfit space aborts action  (and shoots a msgbox) (doesn't put it in cargo for example)
 - selling without items to sell aborts action (and shoots a msgbox)
 - and so on

**Comment by tehhowch** [comment]
It is explicitly intended. You are unable to leave the planet with negative cargo space. See the comments on the original pull.
