### ISSUE TITLE
Unfettered should pay more for Jump Drives

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3547]
After selling them some drives, Unfettered start to offer tribute missions which are very profitable, for example:
![tribute](https://user-images.githubusercontent.com/17566547/34918963-930e7d08-f964-11e7-9220-ce7eff8ea1a8.png)
This mission entails flying through several friendly systems w/o pirates, loading cargo, flying back, unloading cargo.

By comparison, farming Jump Drives requires flying to far east in human space or to Korath territory and fighting with Korath, yet it would pay only a million per drive.

Also: `Once again, they swap your jump drive for a hyperdrive, and pay you far more than you could sell a jump drive for anywhere else.`

If, theoretically, one could just buy jump drives (as could be the case in the future), than this wouldn't be profitable at all. Unfettered are in dire need of these drives, they would pay well.

I'm proposing ~to reinstate previous payments of five million. If there would be too much opposition to that, plan B would be~ rising payments to at least two million credits.

**Comment by KiLEdEnNis** [comment]
[intentional](https://github.com/endless-sky/endless-sky/commit/83d852d1dbed04db753405fedefabdc6fb9ffce1) [close this issue](https://github.com/endless-sky/endless-sky/issues/2167)
why? because imagine if one farms say 5 of these and goes to Unfettered space, easy 25M credits in mere minutes irl

**Comment by Wrzlprnft** [comment]
Lorewise: there seems to be no black market for jump drives. the human space probably would tryhave to lock you down (given that we are not talking about game breaking fleets and amounts of jump drives), other aliens either scared of the quarg, or not interested, to proud, or not shady enough (yet. looking at you, wanderers)

as in: you have nowhere else to turn those into credits. and you are not the only one selling jump drives to them.

until there is more to the late wanderer post eye unfettered hai interaction, i'd leave this as 

flavor story not built upon more than there is yet.

and consider price changes as thw story goes on.

**Comment by Tadrix** [comment]
> intentional

Every change is intentional, it doesn't mean that it couldn't be changed again.
Bladewood had a point:

> It could have been 1.25M credits...

That's why my plan B was to turn it into 2 millions. It isn't that large compared to 5M, sounds ok, yet is larger than Jump Drive's nominal price.

> Lorewise: there seems to be no black market for jump drives

Lorewise: Judging by the fact Unfettered mentioned other humans selling Jump Drives to them, there could be a black market.

**Comment by Wrzlprnft** [comment]
i think that referred quite specifically to the alphas as specified in the story.
archon-korath, quarg in fw story... there are enough hints that jump drives are still a big thing, and if there were enough for a proper black market, i doubt that this would go unnoticed for long.

but again, this is up to more story to come.

**Comment by MessyMix** [comment]
>other humans

= alphas

so probably no regular jump drive black market.

**Comment by Wrzlprnft** [comment]
(afterthought: a change for a changes sake since this is a rather arbitrary value in a story not yet full built upon. leave it open for when the time comes, but i'm out :) )

**Comment by Nescio0** [comment]
The Unfettered already pay four times as much as anybody else, so why should they pay even more?

**Comment by whismerhill** [comment]
I think you need to see it more globally
if you got an additional jump drive what does it mean ?
 - it probably means you either captured or looted a korath ship right ? hence you probably got nice items & increased your fleet value OR you sold the ship/items for a lot of money already

so the way to see this is that it's a nice bonus on top of the rest.
well that's my opinion anyway.
as an individual transaction it's not so good, but with the rest it's fine imho.

**Comment by Amazinite** [comment]
I'd look at this as a ton-for-ton transaction. 1 mil for a 20 ton Jump Drive is more than the nearly 2 mil you're being paid for the 134 tons of supplies shown in the example. And farming Jump Drives from the Korath isn't the only way to get them. Personally, during the time in the Wanderer campaign when the Unfettered are sending Water Bugs into Wanderer space to collect tribute, I'll steal Jump Drives from the Water Bugs and give them right back to the Hai, a one-jump transaction that ends up being far better than taking the jobs that the Unfettered offer.

**Comment by Tadrix** [comment]
@Amazinite Great, but add to it distances covered and real time involved.

> I'll steal Jump Drives from the Water Bugs and give them right back to the Hai

Isn't this an entirely different problem? Sounds like something that shouldn't be doable to me.

**Comment by whismerhill** [comment]
@Tadrix 
it's getting a bit subtle here but if they don't check serial numbers of product (if such a thing exist in a form or another) and if there's no survivors, how would they know those jump drives are them to begin with ?

also you could have simply "retrieved" the goods before they were in the hands in the enemy

and finally I don't know much about lore, but they seem like bloody fanatics who wouldn't care to me.

**Comment by Lineth** [comment]
The unfettered would probably shrug it off as 'those idiots being too weak to protect themselves like proper Hai anyway' or something.

**Comment by accursedCursive** [comment]
@Wrzlprnft Your lore argument is interesting, but I wish there was a way to support it in actual gameplay.
There would need to be a way to make things illegal for specific governments.
The way I'd suggest implementing it would be to define the illegality of outfits as part of the government, instead of as part of the outfit. Obviously the outfit would no longer inherently show that it's illegal, but that's what descriptions are for.

One thing I wanted to do in my mod was to have the Syndicate illegalise EMP Cluster Missiles (a Lovelace weapon), because of how many Broadswords get captured by pirates after being hit by them.

**Comment by Tadrix** [comment]
This isn't the right issue to discuss illegality of outfits.
… Your mod again?

That's it. I closing this.

**Comment by accursedCursive** [comment]
*you're
Assuming you're saying that I'm a mod, given that I apparently have the ability to close threads just by posting in them.

**Comment by MCOfficer** [comment]
since we've arrived at the lowest level possible, which is correcting other's grammar... *your

**Comment by jafdy** [comment]
Mod is also short for "Modification", I assume that this "EMP Cluster Missiles" didn't slip into the base game while I wasn't looking . . . 
(Also "you're" is short for "you are" while "your" is possessive. The comment was about the mod that is yours, not about who you are.)
