### ISSUE TITLE
Ships with fighters slowly increase mass

### ISSUE THREAD

**Issue by PJMack** [endless-sky/endless-sky#3548]
My ships with fighters slowly increase mass.  I first noticed this when my lead ship (Bactrian) became abnormally sluggish and upon looking at the info, realized that the mass without cargo was over 5000 tons.  Once I closed Endless Sky and opened it again, the mass reset to 1700 tons, but began increasing over time.  I notice similar problems with my Tek Far 78 - Osk.  My fighters are Lances (Stock configuration) plus a few stolen Korath Chasers (unmodified).  Parking the fighters on Sol stopped the mass from increasing.  I am using a build from github, and can narrow the problem down to a change within the past month.

**Comment by KiLEdEnNis** [comment]
[this](https://github.com/endless-sky/endless-sky/commit/24cab842a9f3a66c1b5fb862e1139707c9dd2ee4) most likely caused this then

**Comment by Rob59er** [comment]
have seen this happen as well, let a baccy drift alone for a while with three finches and the mass increased.

**Comment by tehhowch** [comment]
The mass changes in flight? Or after each planet you leave?

**Comment by tehhowch** [comment]
Fixed in #3551

**Comment by endless-sky** [comment]
Fixed by merging #3551.
