### ISSUE TITLE
Expand side panel in shops - Option - proposition #2

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3549]
New proposition for #3533 
I'll be working on this. so this is just to get people's opinions
( e.g. I'm not asking anyone to implement the feature. )
Therefore this will serve to see if I should start working on that at all
something like this : 

![](https://image.prntscr.com/image/ufKzhxRsRhq701VHlmRQqg.png)

First : there's be an option in the preferences to disable this altogether
2nd: if enabled, for low number of ships in fleet, a single column will appear (as shown in the picture
3rd : as fleet ships amount increases a 2nd, 3rd, and eventually 4th column will appear dynamically.

Advantage : 
 - it's compatible with 1024x768 ! yeah
 - it keeps more space in the outfitter for outfits
 - less "empty dull looking gray"
 - basic idea is to go from 1 to 4 columns, however for smaller screens it might auto-limit itself to say ... 2 or 3 columns so as to keep enough space for outfits in the outfitter (rule will be : total side bar width < resolution width / 4 )
 - it will remove a column once there is at least 5 ships less than the amount needed that made it switch to one more column before.

sidenotes: I haven't programmed this yet, so there could be adjustments depending on how it works out.

 👎  **if you don't like,** 👍  **if you like, and something else if you're neutral**

Thank you very much.

**Comment by jostephd** [comment]
Brainstorming: How about keeping the panel as it is (ship thumbnails first in four columns, ship details below), but whenever you double-click on a thumbnail, the panel scrolls to the ship details view, and whenever you double-click on the ship's name/image in the ship details view, the panel scrolls back to the thumbnails?

I'm leaving single-clicking alone so as not to interfere with selecting ships for buying/selling outfits.

**Comment by whismerhill** [comment]
@jafdy 
good point, just need to give it a bit of leeway, e.g. it doesn't switch back and forth on just one ship difference, but will need like 5+ of them to remove a column

@jostephd 
that is another possibility. I don't mind this, though it seems really similar to the old PR #3533 which the lead developer wasn't so thrilled about

**Comment by KiLEdEnNis** [comment]
either way I'm for a fix of the current "problem", especially since it's not only big fleets that create this problem:
imagine if a player uses fighters, they show up as a ship too; imagine if ya have 2 fully loaded 109's, it'd counts as 34 ships total, becoming a big clutter in the outfitter

I like this change a bit less than my idea of locking the ship details panel as I proposed in 3533, but this change seems good as well

**Comment by whismerhill** [comment]
that's a valid point @KiLEdEnNis  carriers definitely need to be considered

**Comment by Nescio0** [comment]
(Also have a look at the discussion of #3326.)
Suggested alternatives I'm aware of:
* shrink ship icons if fleet size increases (rejected)
* separate fleet overview and put it to the right of ship's details (suggested by Amazinite in #3326; proposed in #3533)
* have a dynamic fleet overview to the right of ship's details (this issue)
* vertically locking ship's details (KiLEdEnNis' suggestion)

Another idea is to have the ship details' panel locked on top, below it the fleet overview with scroll bar which only affects the ship list, and the buy/sell/leave panel at the bottom. This would be a lesser change and at least save some annoying scrolling.
