### ISSUE TITLE
Plotting course should not pick hostile systems if same distance

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#355]
In the middle of Free Worlds line (mission "FW Northern 2") you need to go from Alioth (New Tibet) to Rastaban (Dancer).
The default plot picks going through Kaus Borealis instead of Eber. I guess it's a preference between potentially meeting pirates or navy..

**Comment by brick96** [comment]
Hold shift to pick manually pick a route

**Comment by endless-sky** [comment]
I think those would both technically be Republic systems, and thus hostile, at that point in the story.

I *could* make the pathfinding take into account the relative fleet strengths in each system or something like that to break a tie, but that seems like a lot of added complexity for very little benefit.

**Comment by wkoot** [comment]
The funny thing is that when I had to go back again, the route plotted was "all safe"; it went south through Sargas (same amount of jumps).
@endless-sky You are indeed correct that Eber is also Republic controlled at this point, I did not check as it was displayed grey instead of red (Alnasl, Eber and Alpha Arae are all Republic controlled).

**Comment by frameworld** [comment]
@endless-sky 
Each link can have a distance. Just increase the distance for the path-finder from 4 to 4.1..4.9 with floating numbers accounting for enemies.

As a hobby, I am about to design an path-finding algorithm using polygon-delimited-volumes and passages between them in 4D space using multiple resources/ratings (fuel, time, danger).

**Comment by endless-sky** [comment]
Added in commit f63d139.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
