### ISSUE TITLE
An alternative race tiering system

### ISSUE THREAD

**Issue by accursedCursive** [endless-sky/endless-sky#3552]
I've found a tiering system that works extremely well: It reflects the history of a race, makes it easier to write the story of that race both forwards and backwards in time, and gives better hints for balancing outfits and ships than just "Race A should be X times more powerful than Race B".
It's also rather similar to the current tiering system.

The tiering system rates civilisations based on how exotic their technology is, and how efficient it is:
![politics](https://user-images.githubusercontent.com/9290794/34923813-12a0089e-fa04-11e7-9148-fdea3a455232.png)
I based the data in here off of a mixture of lore and guesswork.

This data is immensely useful when balancing, I use it when modding.
If you keep this image upright, you get the tier of a race and the cost of their technology.
If you rotate this image 15 degrees clockwise, you get the lethality of a race. (2*exotic + efficiency)
If you rotate this image 15 degrees counterclockwise, you get the survivability of a race. (exotic + 2*efficiency)

This creates some interesting relationships between races.
In the image below, downward-sloping inverted-colour names represent the lethality of a race, and upwards-sloping represents the survivability.
![combat](https://user-images.githubusercontent.com/9290794/34924259-3bffba6a-fa07-11e7-8806-b39594a5ad9b.png)
This image is painful to look at, but it says a lot of interesting things if you accept it as canon, for example:
-Drak penalise races that are lethal enough to harm Archon
-Relatively peaceful races are, for technological reasons, not liable to break out into war with each other or themselves; war and combat is slow paced enough that attacking your attacker isn't the only way to survive
-Quarg and Pug would be both very liable to take losses when fighting Korath drones (which they are both easily capable of), which means despite being inferior when fighting Pug, Quarg would be better than Pug at fighting Korath drones as Pug can't sustain their losses due to their high tier
-The Quarg losing the war with the Coalition was not inferiority, it was the economic burden on the Quarg as well as being appalled at the loss of life on both sides (mostly on the Coalition side)

Overall, this does a much better job of explaining galactic politics and civilisation development than just saying "Race A is better than Race B in every way but chooses not to be a bully".

**Comment by Tadrix** [comment]
Tiers aren't really used in-game (except the name of one outfit), they are (mostly) unofficially used by developers as a convenient way to describe power levels of sentient species. As such, it will not change.

> mixture of lore and guesswork

Post it on Google Groups or Steam Community then.

Since you don't seem to have a problem with how the game itself works or propositions for in-game content, please, close this issue.

**Comment by Startome** [comment]
Also, I hate to point it out after all the work you just did. But there is a spreadsheet system in place that already effectively compares the races, the teir system isnt supposed to be exact. Just a general guide

**Comment by MCOfficer** [comment]
i'm having a hard time to accept something as canon that is partly based on assumptions. if you make such a diagram, you should for example mention that the pug's tier is unknown (they seem to posess technology not even the drak have mastered) and that all we can't know for sure why the quarg retreated from coalition space.

also, as mentioned above, this isn't really an issue.

**Comment by jafdy** [comment]
The tier system is a way of comparing the strength of different factions and to aid in making a smooth progression curve. It's not a political diagram. 
It is an important concept to developing new content and adding a second dimension is just going to get in the way.

**Comment by endless-sky** [comment]
This is really better suited for the forum or some other context. This issue list if for tracking bugs and proposed features, not generic game lore.
