### ISSUE TITLE
logbook - adding when you finished repaying your initial loan

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3558]
the logbook is pretty cool, gives some life to this game.
would be nice if the date at which  you finally had no more debts was written in it.

of course a player may get a new loan to repay the initial loan which wouldn't really count.
hence the condition : 
 - if no loan and positive money balance and has at least 1 ship in fleet which can take off planet
 - then write "repaid initial loan tidbit" in logbook
 - the check could maybe be made when repaying any loan

**Comment by tehhowch** [comment]
#2737 

please close this issue
