### ISSUE TITLE
checkbox "show outfits for sale" & cargo

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3560]
disabling this checkbox should not remove outfits in cargo from visibility

reason : 
 - by definition, cargo is not sold by the outfitter
 - also practically unchecking this checkbox would allow simple fleet outfits tranfers (through install/uninstall)

**Comment by endless-sky** [comment]
In other words, show outfits in cargo even when "show outfits in cargo" is turned off? I don't think that would necessarily be an improvement over the current behavior.

Common tasks that players want to perform include:
* Buy or sell outfits for a ship (sale = true, cargo = false)
* See all outfits installed in the selected ship(s) (sale = false, cargo = false)
* See all outfits that are in cargo (sale = false, cargo = true)
* Buy or sell items directly to cargo (sale = true, cargo = true)

Your proposed change would mean there's no longer a way to view just the outfits installed in the selected ship(s). So the question is whether having a view that shows all outfits in the selected ships combined with all outfits in cargo is more useful than that, and I don't think it is.

**Comment by whismerhill** [comment]
- "show outfits in cargo" =  false & "show outfits for sale"= true.  you still see outfits in cargo 
 - "show outfits in cargo" should actually be renamed to "show only outfits in cargo" because it's what it does.

you're right, you would view : 
"just the outfits installed" + "outfits in cargo".
but if there's no outfits in cargo then you're back to the  : 
"just the outfits installed" view. 

the reasoning behind this is practical : 
 - it's faster & easier to transfer items from ship to ship through "install" & "uninstall" when "show outfits for sale" is false rather than browsing the whole store & using "buy" & "sell"

in the end though it's your choice.
