### ISSUE TITLE
Bad "best destination" on jump

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3561]
I have two missions that involve Tejat:
 - bring tourists to Vail in Tejat
 - pick up contract laborers from Arabia in Ascella and deliver them to Calda in Tejat

I took off in Phurad and jumped to Tejat, the message says I have missions that require landing on Calda and Vail, and my ship is headed for Calda (the "best destination").

Since I haven't picked up the contract laborers I would expect Vail to be the best destination, not Calda. I'm also unsure about the message mentioning landing on Calda, since doing so will do nothing right now.

**Comment by tehhowch** [comment]
This is handled in ai::moveplayer, if you care to address it. Probably needs a check to cancomplete.

**Comment by flaviojs** [comment]
Since I'm unsure about the message, I won't address this.

**Comment by tehhowch** [comment]
Done in #3562

**Comment by endless-sky** [comment]
Addressed by merging #3562.
