### ISSUE TITLE
Use a space for a thousands separator

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3566]
Related: #3565

Replace commas with thin spaces to avoid ambiguity, because a comma is used as a decimal separator in many countries.

[From the Wikipedia](https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping):

> Since 2003, the use of spaces as separators (for example: 20&thinsp;000 and 1&thinsp;000&thinsp;000 for "twenty thousand" and "one million") has been officially endorsed by SI/ISO 31-0 standard, as well as by the International Bureau of Weights and Measures and the International Union of Pure and Applied Chemistry (IUPAC), the American Medical Association's widely followed _AMA Manual of Style_, and the Metrication Board, among others.

**Comment by tehhowch** [comment]
The game generally prefers scientific notation over long numbers, but this doesn't kick in until the 7th (million+) digit, so this would only see use for the thousands separator.
I feel we'd get a lot more "where's the comma?" than "i thought this was a different number" comments (since I haven't seen a "i thought this was a different number" outside of #3565 

That said, I'm not opposed to it. Metric system should have definitely won the final holdout by 3013 (I hope) and the YYYY-MM-DD vs MM-DD-YY(YY) vs DD-MM-YYYY battle should have been fought and succumbed to the strength of YYYY-MM-DD as well, so adopting another ISO standard shouldn't be too much of a stretch.

**Comment by Bladewood** [comment]
I would totally agree with this issue personally, as well as with @tehhowch's statements, but we have to consider that this is a game, and a game has players, who may be completely unfamiliar with, confused by, and even resistant to whatever official systems we throw in.

**Comment by Tadrix** [comment]
> Also, American standards.

AFAIK US is the only one country with customary units left, and has > 3 times less population than the rest of the civilized (speaking English at least as a foreign language and gaming) world, so this change would probably benefit at least 70% of players. Even in US there are folks advocating for the metric system.

> even resistant to whatever official systems we throw in

There are games which let players change systems / units via settings. The best approach would be auto-setting it for the first time according to OS settings, if applicable.

**Comment by whismerhill** [comment]
tbh, as a french user I'm fine with separators as they are
it's just the combination as they were mentioned in #3565

**Comment by Tadrix** [comment]
> and YYYY-MM-DD should be adopted as well (by 3013)

Or maybe, akin to modern military usage and similar to NASA's expeditions, [ordinal dates](https://en.wikipedia.org/wiki/Ordinal_date) ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Ordinal_dates)) will be used. But this is beside the point.

The point being that usually people use either [.] or [,] for a decimal point (or a decimal comma), and [,] and [&nbsp;] for a thousands separator, so it seems to me that the best way to avoid confusion and make (almost) everyone happy is to use [.] for a decimal point and [&thinsp;] (thin space) for a thousands separator.

I remember there being an exception that 4-digit numbers (1000 to 9999) should be written without a separator at all, but I don't remember if this was part of a standard.

**Comment by KiLEdEnNis** [comment]
I personally use . as separator and , to start decimals (I think it's like that in Europe in general, but not sure), having this the other way around in-game is mildly annoying and may be confusing
and having it my way would in return be confusing for those that like it this way, not to mention tht suddenly turning around would cause confusion as well
so I'm for a way to make it clear for both sides as well

**Comment by Bladewood** [comment]
@Tadrix https://github.com/endless-sky/endless-sky/pull/2644

**Comment by ghoulavenger** [comment]
I think most of the stuff in sci-fi tends to be metric, so there isn't a real need to use anything American or Imperial whatsoever. But I feel the real important part is just to be consistent in which style you use more than which separator you use. Considering that the separators for numbers are generally handled by the game interally and not by an individual author, they should be consistent for the most part (static descriptions being the only possible exception), so there doesn't need to be any changes.

That being said, considering that this game is set to be in a far off future, any system of measurement can be used, including ones that are entirely invented.

**Comment by nylki** [comment]
Btw. here is a map showing decimal character usage around the world:
![http://brilliantmaps.com/decimals/](http://brilliantmaps.com/wp-content/uploads/DecimalSeparator.png)

**Comment by MessyMix** [comment]
I personally don't see any reason to change it, because either way you'll alienate a good portion of the world.

Realize that a surprisingly high percentage of the world, that is India and China (the world's two most populous countries), both use period separators, as does the US.

While I can see where you're coming from with this change, I do _not_ agree that it is at all necessary or even beneficial towards the game, because you're trading the favors of one segment of the community for another.

No from me.

**Comment by Tadrix** [comment]
I'd like to remind you both that this issue isn't about the decimal separator (it can be a period or a comma, current one is probably fine) but about the thousands separator, which should be a thin space as per ISO standards, to make numbers unambiguous to the most of the world.

> Spaces should be used as a thousands separator (1000000) in contrast to commas or periods (1,000,000 or 1.000.000) to reduce confusion resulting from the variation between these forms in different countries.
([Source](https://en.wikipedia.org/wiki/International_System_of_Units#General_rules))

These standards exist to make numbers comprehensible to everyone.

**Comment by Nescio0** [comment]
12345 difficult to read
12 345 international standards
12,345 common in English speaking world
12.345 common in continental Europe
12·345 very rare
12'345 optional in C++
12_345 optional in python
12~345 LaTeX

I don't really care which one is used, as long as it's done consistently.

**Comment by Tadrix** [comment]
2345 is fine though.

> 12·345 very rare

This could be mistaken for a decimal point.

> 12'345 optional in C++

This wouldn't be so bad, but AFAIK there aren't any standards which use it. In this issue I was proposing to use recognized standards to make numbers understandable to everyone instead of reinventing the wheel or clinging to old ways like the US is.

**Comment by Nescio0** [comment]
The interpunct was used centuries before the introduction of any other separator. Nowadays it can be confusing; I tend to associate it with the multiplication dot.

Although I'm unaware of any officially government sanctioned standards, I remember having (probably two decades ago) Japanese pocket calculators and a Canadian text book using the apostrophe to separate thousands. Our German kitchen scales still does use the apostrophe, probably to avoid the comma-or-dot discussion.

> In this issue I was proposing to use recognized standards to make numbers understandable to everyone instead of reinventing the wheel or clinging to old ways like the US is.

Keeping the comma is fine by me. Switching to a non-breaking space is fine by me. Choosing any other sign is fine by me. Adding an option allowing players to customize the thousands separator is fine by me. As long as it's done consistently I don't really care.

**Comment by endless-sky** [comment]
If the game is eventually localized to other languages, it'd make sense for that localization to include the digit separators. But in the meantime, the proper question to ask is not, "what is the standard across all languages," but "what is the standard in English-language publications?" And based on the map above, it seems like commas are pretty universal there.

**Comment by Tadrix** [comment]
It could be the map above isn't all. [Here](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html) overwhelming countries use spaces, including publications in English in Canada.

AFAIK _AMA Manual of Style_ is American, and _Metrication Board_ was British. [Here](https://academia.stackexchange.com/a/26634) they also recommend spaces.

So it looks more like a choice between traditional measurements and numbers displays (separate with commas, use inches, feet, miles and other US customary units) or modern standard abiding and future-minded measurements and number displays (separate with spaces, use metric).

And by the way English nowadays is used by people from all over the world. To quote:

> 2,500 was two and a half for me until I moved to the US.

**Comment by accursedCursive** [comment]
If your outfit prices are so large that you need separators to easily read the numbers, you're doing something wrong.
Why would Graviton Thrusters be 20000000 (painful to read, isn't it?), when they're a straight downgrade to Atomic Thrusters?
Here's a comparison...

A520 Atomic Thruster:
"cost" 1120000
"mass" 82
"thrust" 81.9
"thrusting energy" 8.3

Medium Graviton Thruster:
"cost" 20000000
"mass" 70
"thrust" 80
"thrusting energy" 20

Unless your ship generates a virtually unlimited supply energy without outfits (Quarg and Pug ships), the massive amount of extra power/batteries required to run a Graviton Thruster means that at the end of the day the Atomic Thruster takes up less space.
So much less space in fact, that it would still take up less space if you adding some cooling to compensate for the additional heat production.
Atomic Thruster is therefore unquestionably better unless someone got too lazy to try and give a ship energy production that meets energy requirements and instead just gave it completely overkill energy production.

I'm a bit off-topic here, but my point is that the fact that you're arguing about separators is a sign that you're setting alien outfit prices way too high.
Graviton Thruster is hardly worth 1m, let alone 20m.

**Comment by Wrzlprnft** [comment]
a bit off topic?... a bit???
and for that bullcrap i do receive a notification?
1st: hard offtopic. This is not a Forum, this is a issue tracker.
2nd: wether to adjust the price or the values and why they were chosen initially completely ignored. those are not made by a random number generator
3rd: it's quarg stuff. you know, that race that is quite provisoric since it was added, and closely tied into any coalition story. MZ is going to -if he ever has the time- revise that stuff.

**Comment by Nescio0** [comment]
Off-topic:

outfit "Thruster (Planetary Class)"
	"cost" 1216000
	"mass" 69
	"thrust" 80.0
	"thrusting energy" 8.9
	"thrusting heat" 22.7
	description "The Quarg, who do all things efficiently, view the Korath propulsion systems with particular distaste."

On topic: high prices are not at all a problem; millions are abbreviated to m and billions to b. The thousands separator is only used in game for things worth more than a thousand but less than a million. This specific issue is on whether to replace the comma with a non-breaking space.

**Comment by Tadrix** [comment]
On abbreviations: I'd abbreviate billions as G instead of B, partly because they are also called milliards, differences between [short and long scales](https://en.wikipedia.org/wiki/Long_and_short_scales) start to kick in, etc. 10<sup>9</sup> would be best. But that's an entire different can of worms, let's return to thousands separators.

> to replace the comma with a non-breaking space

This, or a thin space, both are recommended. If our lines aren't in the danger of breaking, I'd say thin spaced numbers look better and would be more understandable.

**Comment by KiLEdEnNis** [comment]
for the record, scientific notation is a no since not everyone understands that at all

the options now are:
- leave as is
- use a small space as separator
and that's up to MZ

**Comment by tehhowch** [comment]
Is a small space even ASCII? If not, we can't do it until we have Unicode support, as the text wrapper would consider separating across lines mid-number, in addition to spacing it out more as a part of justifying, centering, or right-aligning.

**Comment by accursedCursive** [comment]
The text wrapper needs to be changed anyway.
It's amusing, the lengths it will go to make sure that ever,y line ends at the same point.
It .............. spaces ............... text ............... like ............... this ................ to ................ do ................ it.
Also, despite turning a large portion of the shop window into blank space when you click on something, the description of an item only uses a narrow column.
All the problems with text formatting would be solved if descriptions were wide instead of tall; justification would be more subtle, reading long descriptions would be less painful, and long descriptions wouldn't cause the shop to scroll.

**Comment by Tadrix** [comment]
Description width and text justification is outside the scope of this issue. While you might have a point, this isn't the right place to raise it.

**Comment by Pointedstick** [comment]
We'll stay with commas for the thousands separator for now given the un-localized text. The proper way to resolve this is to localize the text, which would resolve this for each user's preferred locale.

**Comment by m-f-h** [comment]
> 12'345 optional in C++

also used in Switzerland and occasionally in Germany

> 12~345 LaTeX

It would rather be `12\,345` in LaTeX.
