### ISSUE TITLE
Double gun ports

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3582]
The vast majority of ships have each weapon located on a different location. However, the Argosy, Bastion, Carrier, Falcon, Frigate, and Modified Argosy all have two gun ports on top of each other, e.g.:
```
	gun -16 -176 "Particle Cannon"
	gun 16 -176 "Particle Cannon"
	gun -16 -176 "Meteor Missile Launcher"
	gun 16 -176 "Meteor Missile Launcher"
	gun -25 -166 "Particle Cannon"
	gun 25 -166 "Particle Cannon"
	gun -25 -166 "Meteor Missile Launcher"
	gun 25 -166 "Meteor Missile Launcher"
```
thus meteors are launched from the same location as particle cannons fire. I guess it's a leftover from a time they had fewer gun slots. Anyway, although it's not terribly important, it would be nice if eventually someone could have a look at the sprites and change the gun locations to ensure each weapon is on a different spot.

**Comment by solardawning** [comment]
Is it really a problem, though? I'm not sure we need the standard that all ports are distinct in 2D/horizontal space. The ships themselves are top-down screen captures of 3D models, and it is sensible for some gun ports to be stacked vertically, even if that looks like the guns have the same location from a top-down view.

From a gameplay perspective, I'm not sure it has any significant impact to the player. Does it make the game experience worse? If yes, how so?

**Comment by tehhowch** [comment]
... the ships are 3d ya know. The do have different Z elements for those gun ports.

**Comment by Tadrix** [comment]
Gun slots: [Like this.](https://woodylwg.deviantart.com/art/T-65B-X-Wing-Fighter-143432129) Or one on the top and another one on the bottom of the hull.
