### ISSUE TITLE
Feedback on audio volume?

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#359]
For those of you building the program from source: if you set the volume to 100% in the preferences, are the sound effects too loud or too soft compared to how loud other programs are on your computer when they are set to 100% volume? (I tried to balance it so 100% volume is similar to what my mp3 player on Linux calls 100% volume, but there may be differences depending on the OS because I've had some people complain about audio being way too soft.)

**Comment by Pointedstick** [comment]
Still too soft, OS X.

**Comment by luiges90** [comment]
Far too soft for me, I have to crank the volume from usual 15 to 100 in order to hear sounds from ES. Windows 10.

**Comment by dplepage** [comment]
On my machine (OS X) the default volume setting is a little quiet, but cranking it up to 100% makes it roughly the same as 100% volume in my other apps.

**Comment by endless-sky** [comment]
I've checked in a change (3dee579) that explicitly sets all the various OpenAL parameters, just in case the defaults are different on one OS than on another. I also made 50% volume the equivalent of what 100% volume used to be, so that someone on a system that is too quiet has more room to crank up the game's volume level. Please give it a try and see if the volume levels are improved.

**Comment by Pointedstick** [comment]
Perfect now!

**Comment by Pointedstick** [comment]
Laser sounds are still too soft, though. They get drowned out by any other weapons that are currently firing.

**Comment by frameworld** [comment]
Agree, but this was a topic more about endless-sky vs your music player, not weapon vs weapon.

Is there an easy way to vote for specific game-sounds to be louder/softer?
Maybe adding -xx or +xx to the sound-files name?

**Comment by endless-sky** [comment]
I meant for the lasers sounds to be a bit softer than other weapons to reflect the fact that they're a more "efficient" weapon - i.e. in the real world, the less noise a machine makes, the less energy it is probably wasting as heat. But, I may have overdone it. I can boost the volume on those two sounds a bit.

**Comment by frameworld** [comment]
@endless-sky actually you can also use the opposite logic:
The more efficient something is, the more dangerous it is.

And the more dangerous it is, the louder the warning-sounds (no sound in space, so it must come from the user-interface).

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
