### ISSUE TITLE
Ships suddenly stopping

### ISSUE THREAD

**Issue by Taose** [endless-sky/endless-sky#3593]
A little confused. I'm taking a fleet through for a mission, simple "special escort" mission from Io Lowe to Betelgeuse. I go to Heia Due, land to refuel and then hop over to Waypoint where my ships five of my Bactrians at least, decide they want to stop responding. 

They either stop there or in Ultima Thule, I've also had them stop in the system after. I've been unable to go any further with them as they just freeze. 

I've tried "H" and "G", I've tried doing it after a restart, saving snapshots and doing it from a new planet but no joy. Any ideas?

Edit:

Further testing seems to indicate then when going through the (or attempting to go through) it is de-syncing somewhere as it's now always happening when trying to go through. 

Edit:

I aborted the mission and it's still happening. 

Edit

I did a git pull 2018 01 20 ... but I still have the issue and now the game doesn't like loading as quickly appearing to freeze on button presses for a few moments. (Never mind) Anyway, I can tell you that it's definitely something to do with the wormhole. On going through 5 ships stopped following me and refuse all commands, can't get them to move at all.

**Comment by KiLEdEnNis** [comment]
what version are ya using, Steam version? built from source?
and do you have the means to record this behaviour for us?

**Comment by Taose** [comment]
Built from source. I grabbed the git as I'm on linux, using git clone and followed build instructions on the wiki. So currently, it's at the latest master build. 

As of means of recording very little I'm afraid. 

What I do have is clear details of what happens. I jump to Waypoint and all the ships follow just fine. The ships then all "auto land" on the wormhole (doesn't matter if I kick it out and land using the L key). All ships bar five will jump through. Now, as to whether some of those five get through appears to be a roll of the dice. However whether they get through or whether they are left behind the result is the same. 

The ships stop being able to move. They continue with the same velocity they had, but are unable to change speed or course. They do not respond to "h" or "g", they do not respond to right click even if I click them directly and then right click near me.  This doesn't matter whether I land on a planet and take off or whether I restart, it doesn't matter if I try from an earlier save point. (I'm going to test that more extensively in a moment)

They still register as escorts, their scramdrives are pretty much full, they've taken no damage.

**Comment by jafdy** [comment]
It sounds like they are overheating or ran out of energy.

**Comment by Taose** [comment]
Energy is full, heat is zero for those five ships.

**Comment by Taose** [comment]
Turns out... energy. I'm not sure why they're draining so fast as they all have the same equipment. Thanks I'll sort this out myself.

**Comment by chickendelight** [comment]
Are your ships using solar for energy?

**Comment by Bladewood** [comment]
Use batteries.

**Comment by tehhowch** [comment]
I was originally thinking they were getting bad target systems but yeah.. energy will do it.
If you hold J in their system and their icons turn red despite having full fuel, that's an issue with an unreachable target system (solved by one of my open PRs).
For recording, obs is pretty workable even on crap hardware. I have a laptop with onboard hd 4400 and am able to record and play.

**Comment by tehhowch** [comment]
1. If you plunder their stuff, then capture, that's 100% on you.
2. Possible. File an issue for it. Note that it can only happen if you have no generator on the ship, and no base variants use such a vulnerable rigging.
3. Make the ships follow other ships. left click the to-be-follower, right click the to-be-followee
