### ISSUE TITLE
Ships piling up on top of the sun in new system

### ISSUE THREAD

**Issue by X-27** [endless-sky/endless-sky#3597]
I'm creating a plugin which has a few new systems. From what I've found so far, I can modify any of the currently existing systems and the ships will behave the same. (For example, in the system Ipsing, more and more navy surveillance drones keep appearing and driving between the various planets - this behavior persists regardless of what I modify about that system. In addition to that, the fleets that I specify should spawn in do not).  However, if I try to make a completely new system, the specified fleets do indeed spawn in -but all the ships that spawn in seem to fly directly on top of the sun before jumping away. With a lot of ships, this behavior looks *really weird.* How can I make ships spawn and jump in/out normally, in a new system?  (note, I'm modifying the plugin's data files directly, instead of using the map editor).

**Comment by Amazinite** [comment]
>I'm creating a plugin which has a few new systems.

The ES Github is for feature requests and bug reports. If you're wanting to ask a question, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky), or see if the answer is on the [wiki.](https://github.com/endless-sky/endless-sky/wiki) There's also the option of the [unofficial Discord server](https://discord.gg/u6KepgG), which has been thrown around a bit lately. Questions about plugins would go in the `#content-creating` room. Please close this issue.

**Comment by X-27** [comment]
This kinda does seem to be a bug since I can't find anything in the data files that would be causing this - but I shall check those other sites as well!

**Comment by Amazinite** [comment]
It's a matter of the [fleet personalities](https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities), not the system itself.

**Comment by X-27** [comment]
When I made an identical copy of the Polaris system, (named Polaris2) I had the same Syndicate ships spawning, except for whatever reason, they would pile on top of the sun before jumping out. In the original Polaris, they jump in, fly around, and land normally.

**Comment by Amazinite** [comment]
Again, please close this issue and take it to a different location where we can discuss it further and over 100 people won't get email notifications about it every time one of us posts.

**Comment by tehhowch** [comment]
If there are no landable planets, ships jump in to the center. They will also have nothing to do (unless they are `personality swarming` or `personality surveillance` or `personality staying`), and thus the only thing they *can* do is jump away.
Relevant #3381
