### ISSUE TITLE
Hallucinated ships can be captured

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#36]
Drug-induced fake ships can be captured.  That will put a crew member aboard, and you can even choose such a fake ship to be your flagship.  Using the jump drive and infinite fuel, this allows for instantaneous travel across the galaxy.

**Comment by akien-mga** [comment]
I knew it! Bug hunters are doing drugs!

**Comment by endless-sky** [comment]
And, it's a good thing too, because this is the second bug that the more amoral beta testers have found in the drug missions. :)

I guess I'll have to add a "never disabled" ship attribute that makes its "disabled" hull level equal zero so that it is always killed outright rather than disabled.

**Comment by endless-sky** [comment]
This should be fixed in commit e561046. The hallucinations can no longer be disabled, and no longer run away once you damage them either.
