### ISSUE TITLE
Show the viewport on the radar

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#3605]
When I see a ship's blip on the radar, I'm never sure how far the ship is from me. I thought it would be easier to get a sense of how far things on the radar are if the boundary of the viewport were displayed subtly on the radar.

**Comment by tehhowch** [comment]
I don't think adding the full box would be done, but corner markers could be possible. As of right now the radar scale is immutable, so the distance is always the same - just as learning what the proposed viewport markers represent, the player can learn the distance relative to their ship.

**Comment by tehhowch** [comment]
This actually turned out kinda neat:
![zoomed out](https://user-images.githubusercontent.com/20871346/35361179-fc099874-0125-11e8-913f-a5dd200d270c.png)

**Comment by jostephd** [comment]
That was fast, thanks!

**Comment by endless-sky** [comment]
I'm really not convinced that this would be useful to most players. Because the radar scale is fixed, you learn pretty fast how to tell how close an object on the radar is. And in most cases what you're really interested in is how quickly the object is moving toward you or away from you (e.g. how long it will be until that missile hits you).

**Comment by jafdy** [comment]
Up until recently I still thought the scale was logarithmic, and the distance to the edge was quite a bit further. So, I've been at this a while and never got the hang of the scale it's quite likely that there are others out there that haven't either.

**Comment by jostephd** [comment]
The corner marks also help in getting a quick estimate of the distance in terms of screen-heights / screen-widths, which is a larger unit than "ship length" or "Heavy Laser range" or "three seconds at maximum forward speed" and so more amenable to estimates. Essentially, the corner marks are a point of reference that gives a sense of scale. The existing concentric circles don't serve that purpose well because there is no easy way for a player to learn what distance in the playfield they correspond to.

**Comment by Janaszar** [comment]
Just a thought, but what if the viewport had the ranges of the equipped weapons?  Maybe just a general "can hit within this" circle.

**Comment by tehhowch** [comment]
There are a lot of variables that need to be addressed if showing weapon ranges, to the point that I would think it to be useless in practice. Just install a Tactical Scanner and you can get a nice range estimate to your target.

**Comment by Pointedstick** [comment]
I would really like this. I feel like it would essentially add a scale to the radar display, which is otherwise a bit hard to understand.

**Comment by jostephd** [comment]
#3607 has been merged, this can be added to the `0.9.9 (done)` milestone.
