### ISSUE TITLE
Full with fuel escort gets stuck asking for refueling after travelling through wormhole off-screen

### ISSUE THREAD

**Issue by starkythefox** [endless-sky/endless-sky#3608]
**Version:** Compiled, at https://github.com/endless-sky/endless-sky/commit/e0d1780db0f6e13590d5ba7281106a5c197bf91b

**Steps to reproduce:**
1. Have your fleet in a system with a wormhole nearby.
2. Have a slow escort on the system with the other end of the wormhole or a system nearby it.
3. Plan a route to the next system after the wormhole.
4. Depart and autopilot to the system.

As it is a race between your flagship and the escort it may be hard to trigger the bug. In my case, I'm using the Ka'ch'chrai as the initial system, the Eye, Sabriset as the escort system, and Kaliptari as the destination system.

**What should happen:**
The escort will either:

* steer and/or brake on the other end of the wormhole when your flagship exists it and follow you.
* cross each other through the wormhole but will follow you afterward.
* go through the wormhole off-screen as you go to the next system but will join after going back through the wormhole

**What happens instead:**
If lucky, it happens as it's said in the first two cases.

If unlucky, the escort goes through the wormhole off-screen as you jump to the next system, leaving it stuck in the side of the wormhole you came from.
Going back to reach the stuck escort, you may see it move to a certain point where it just holds its position, stuck in a loop where it asks for refueling.
Trying to assist it or any of your escorts or allied ships does nothing most likely due to being full in fuel, nor does pressing G or H.

To make it move again, you must hold the J key or try to land on the wormhole as an escort/allied ship is refueling it.

**Video proof:**
https://youtu.be/nk7aet78hcw

**Save file:**
[Starky Foxxer.txt](https://github.com/endless-sky/endless-sky/files/1665052/Starky.Foxxer.txt)

**Comment by Fzzr** [comment]
I have also reproduced this.

Video: https://imgur.com/fQLOFsf
Save: https://pastebin.com/VehjZzCA

OS: macOS Mojave 10.14.2
Build: Self-Built
Commit: edb535f
