### ISSUE TITLE
refuel by capturing ships

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#361]
Not sure if its a bug, or an intended feature, but capturing a ship refuels your own without taking any for your new ship.
Both ships have 100% fuel.

**Comment by thenerdfreak** [comment]
No. both ships do not have 100% fuel, you get all that ship has/you need (if you don't capture) or all you need/ all but 1 jump/hyperspace's run worth (if you do capture)

**Comment by brick96** [comment]
I forgot look at the captured ship's fuel
