### ISSUE TITLE
Outfitter misaligns decimal places

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#3611]
The Hai Plasma Rifle is displayed as follows:

![decimal-point](https://user-images.githubusercontent.com/24784687/35447445-aa00f2bc-02af-11e8-8f2b-aae6605fa1c5.png)

This is easily misread as ".7 attack, .1 defense" or "7 attack, 1 defense".

Possible fixes:

- Always display a leading zero on fractions:

```
attack:  0.7
defense:   1
```

- Align all decimal points vertically:

```
attack:   .7
defense: 1.
```
(with leading/trailing zeroes according to MZ's taste)

- Scale all numbers by 10 to avoid decimals:

```
attack:   7
defense: 10
```

**Comment by Brick63** [comment]
the only problem i can see is outfits like the bio-defenses at 250 causing issues but that's about it

**Comment by KiLEdEnNis** [comment]
I'd like 0.7 and 1.0 but the unnecessary zeroes may not be appreciated by everyone

**Comment by endless-sky** [comment]
This seems highly subjective - some people will prefer .7, and some will prefer 0.7.

**Comment by Hacklin** [comment]
@endless-sky: Sorry no, most people use 0.7.

In natural languages and in C/C++ printed output  there is always at least one digit to the left of the decimal separator (= '.' | ',').
C/C++ allows zero digits to the left of the decimal point to be omitted in literal floating-point numbers.
Not all computer languages allow this.
Most natural languages disallow this or at least frown upon this, because the point (or comma) could be misinterpreted.

Guess you've been programming in C++ for too long ;-)

**Comment by KiLEdEnNis** [comment]
it's partially just a matter of preference, but 0.7 does make it more clear than .7, so it should reduce possible confusion

**Comment by Hacklin** [comment]
std::cout << .7 << std::endl;

**Comment by Tadrix** [comment]
0.7 would certainly be better.

> When the integral part of a numeral is zero, it may occur, typically in computing, that the integer part is not written (for example .1234, instead of 0.1234). In normal writing, this is generally avoided because of the risk of confusion between the decimal mark and other punctuation.

**Comment by jafdy** [comment]
0.7 does seem like a good idea. I and the people I work with would use .7 in our own day to day work so 0.7 is not entirely normal.

**Comment by jostephd** [comment]
Let's leave it to MZ to decide which leading and trailing zeroes to show. The crux of this issue isn't the insignificant zeroes but that showing the units digit above the tenths digit is confusing (I think we all agree on that?).

**Comment by Hacklin** [comment]
Confusing? No.

Aligning numbers on the decimal separator would make the numbers easier to compare; easier to spot differences.
However, most values represent different things and therefore can't be be compared to one another.

Aligning the numbers thus would increase the required horizontal screen space to represent them.
How would you align numbers like 23.4M and 0.33333 ?

**Comment by jostephd** [comment]
Re 24.3M/0.3, what about pairs like 23.4M and 24.3k. The first idea that comes to mind is color-code them according to order of magnitude (floor(log(x)/log(1000))

I agree with you that always printing the leading zero (as in your PR) would be a good solution.

**Comment by Hacklin** [comment]
Color-coding numbers like this will look a bit tacky and crowded.

Please note that color-coding suggestions that are unnecessary or look tacky, have been shot down repeatedly in the past.  If you want any color-coding change, you must prove that it's needed and that it looks good/fresh/modern.  Proving that the color-coding makes things easier to distinguish, just isn't enough.
Sorry, but IMHO this color-coding suggestion has no change of success.

**Comment by jostephd** [comment]
Thank you for the background but I think you're putting the cart before the horses. No one has suggested a color scheme so you can't be sure it will be tacky. I don't know how to design a "good/fresh/modern" color scheme, but then again, I haven't seen yet an outfit that requires coloring. I'd be happy to punt the question of color-coding, #3613 is enough for me.
