### ISSUE TITLE
Anyone know what's wrong with this ship code?

### ISSUE THREAD

**Issue by accursedCursive** [endless-sky/endless-sky#3616]
I implemented a "border" system tag into my fork of Endless Sky, which is a numerical value that affects:

- AI wander range (MAX_DISTANCE_FROM_CENTER+border)
- Distribution of ships that are already there when you enter a system
- Distance from the system centre that jumping ships appear

It's also intended to calculate if the hyperspace path of a ship comes within the system border at any point, and if so shorten the path so that the ship exits hyperspace at the border.
This doesn't make a difference at all though, and occasionally crashes the game (error code 0x000etc.05).
The relevant code is lines 1070-1084 of https://github.com/accursedCursive/endless-sky/blob/master/source/Ship.cpp
The borderRadius of the system is acquired on line 1052.

The purpose of this is so that in combat-heavy systems, the border size can be increased so that ships entering the system (e.g. the player) aren't blown up in 2 nanoseconds due to there being 10 ships right where they enter.

**Comment by MCOfficer** [comment]
i mean... i like the effort you're putting in. still someone has to say it:

this is no issue with the vanilla game, therefor doesn't really belong on github. MZ or someone else might help you here, but nevertheless it's the wrong place to ask.
i can't really tell you a better place though, apart from the discord, where you can ask fellow programmers directly, without having to use the vanilla game's issue tracker.

**Comment by accursedCursive** [comment]
This would be tonnes easier if the hyperspace code actually made sense.
You can really tell the difference in code quality between hyperspace code and new code; what kind of madman uses a structure like this?:

-Code completely separate to hyperspace, but part of the same function
-Definition of constants relevant to hyperspace with useless names, you have to read the code to figure out what they do (HYPER_C, A, and D appear to stand for count, acceleration, and distance).
-Code that is performed once when a counter reaches 100
-Code that is also performed once when a counter reaches 100, but with obfuscation as to how it detects the counter reached 100
-Code that is repeated 100 times despite only needing to be run once, when the counter reaches 100
-More code completely separate to hyperspace

Mixed somewhere in there are the only two bits of code that actually need to run repeatedly instead of at the end of the count.
I should add that instead of the hyperdrive and the jump drive code being separate, as they have nothing in common except a few lines (and some code from the hyperdrive that runs for the jump drive despite not doing anything), they're mixed together and so when you look at the hyperdrive code you're actually looking at two completely separate scripts, repeatedly switched between by checking if the ship is using a hyperdrive or not.

Also, it turns out that my modified hyperdrive code isn't what's causing my game to crash.

**Comment by accursedCursive** [comment]
I found the crash cause, it was from my change to AI wander range.
Every few minutes or so a ship would check the system border size at the wrong part of a jump and crash the game, so I made it make sure it was in a system.

I still have no idea why my code doesn't affect where the ship ends up though.

**Comment by Wrzlprnft** [comment]
Are we now supposed to applaud? Supposed to care? If you keep ignoring our offers, hell, the rules, and what should we do?
This is spam at this point.

**Comment by jafdy** [comment]
If you think you can improve the code, then improve it and send us a PR . . . or is that too much like hard work?

**Comment by geojak** [comment]
I think a further away entry into systems would benefit the game to ease the problem of too fast dying without any chance for the player to react. And also the problem of too much traffic in remote space.

Don't let them push you down, if they don't want to help you develop a full fleshed out pull request

**Comment by Wrzlprnft** [comment]
we do not have any problem with helping him on his repo. as well as this is not about the initial discussion, which we already had, and came to the conclusion a implementation would be best.
i try not to operate on a personal level, so i am always open to help somebody if i can (probably mainly blender) but this is an issue tracker.

**Comment by MCOfficer** [comment]
excuse me, but if a veteran programmer codes something, and then someone who just learns c++ tells me it's total bullshit... i'm not exactly tempted to believe you. maybe you are the one who's wrong.

you had the chance for a objective, productive discussion here. but as soon as you don't understand the code, you blame someone else - and even worse, share that rant in this (potentially) objective, productive discussion. you do realize that you'll have a hard time getting help like this, do you? you really need to work on your attitude.

**Comment by Wrzlprnft** [comment]
Even a veteran's code isn't save from being garbage. It works, and a rewrite is in most cases a rather annyoing task for the person which initially wrote it.

If it could use a round of optimization, i recommend just going ahead and do it, though. I can't, so i don't judge.

**Comment by Amazinite** [comment]
>This would be tonnes easier if the hyperspace code actually made sense.
>You can really tell the difference in code quality between hyperspace code and new code; what kind of madman uses a structure like this?:

You yourself have stated that you aren't very knowledgable in C++:

>[//This section is pseudocode due to my lack of C++ knowledge](https://github.com/endless-sky/endless-sky/issues/3609#issuecomment-360932229)

and you're even having trouble here and asking for help in the wrong place, so I fail to see how you can constantly pass judgement on the state of the game's code, saying it makes no sense, that it's "hackish," that was made by a "madman" and someone who isn't a "competent programmer."

**Comment by kikotheexile** [comment]
Although it is possible for a veteran acrobat to fall to their death durring a show, it is much more likely that the newcommer will be the one who makes the mistake.

The same concept applies to the circus of code.

It is less likely that MZ is bad at code and more likely that you are using bloatcode to simplify things that would indeed just lead to compound issues.

Once again, mz is just a bro who works on this game for funsies. This isn't his job, and we dont want to make this his job. Thats part of the reason why Amazinite is working on the syndicate story and why i am working on the republic story - to keep the dudes hobby more fun than stress.

Insulting him for providing a free source of entertainment for us in his free time is, in general, counterproductive.

If you have code fixes, make and pr them. Dont just insult people. We discussed this.

**Comment by accursedCursive** [comment]
I've managed to keep the hyperspace code behaviour the same while rearranging and reprogramming it, though one problem I've had is that g++ itself starts has errors if I try add "const" to the following things in the header:
int HYPERSPACE_STEPS;
double HYPERSPACE_ACCELERATION;
double HYPERSPACE_DISTANCE;

I've moved them to the header so they can be set at the beginning of the jump, which makes more sense and would make things easier if more kinds of hyperdrives were introduced in the future.

**Comment by Hadron1776** [comment]
>I should probably not make them constants in case someone tries making them attribute-dependent in the future. If they didn't check the header, they wouldn't see that they're constants, and then that could lead to some odd bugs.

I would think that most people _would_ check the header...

(Also, if you're going to keep talking exclusively about your own branch, maybe this would be better if you PR'd that branch here. Just saying)
