### ISSUE TITLE
[Feature request] Auto visit spaceport and auto buy map options

### ISSUE THREAD

**Issue by clintonmead** [endless-sky/endless-sky#3620]
First of all, love the game, got a Bactrian and played through a good part of the Free Worlds war (didn't finish it though). Anyway now I've got the mechanics I'm thinking of doing a entire playthrough after the next release.

Enough about me, there's just two things I noticed I was doing upon landing everytime.

1. Checking the starport.
2. Buying the local map if I didn't have it complete already (as it's so cheap). 

I would like to add two options, namely "auto buy local map" and "auto check starport". So the first thing that will happen on landing is buying the local map if it's available in outfitting and your version is not complete, and then checking the starport. 

Of course these should be in preferences, and by default off, because there may be reasons why players don't want to do this.

I might get around with doing this myself at some point, by submitting a PR, but I'm not sure when I'll have the time to do that (I'd have to understand the code base a bit first) so I thought I'd drop it here for now incase you want to include it in your next release.

**Comment by KiLEdEnNis** [comment]
it doesn't seem worth it to clutter the preferences with 2 options like this:
with the upcoming new spaceport system (the portraits which quite some people apparently dislike, including me)  it's not a good idea to do this at all
same reason for auto-buying a certain outfit upon landing; not worth to add new preferences for a tiny bit of automation

**Comment by jafdy** [comment]
So this will come under the heading "too much automation" additionally any option that is disabled by default is unlikely to be added. In short, don't get your hopes up. Then again, you never know.

**Comment by clintonmead** [comment]
In any case I’ll submit a PR sometime and if the devs don’t want to put it in mainline I’ll just offer it as a fork.

I was just inquiring because if the devs were interested I’d write it sooner but if they’re not I’ll just fork off the next release and anyone who is interested can use my fork.

**Comment by KiLEdEnNis** [comment]
personally I'd wait for the *dev (singular, one man) to tell me if this feature would be worth it, but feel free to create it if ya want

**Comment by clintonmead** [comment]
Indeed that’s what I meant KiLEdEnMis.

If the dev is interested I’ll try to get it in the main source otherwise sooner rather than later I’ll just write patch on the new version and host the fork on my own GitHub for whoever wants the feature to be able to use it.

**Comment by tehhowch** [comment]
As I mention in your PR, moving the map info check into outfitter (to be like the refill ammo check) would be fine by me, and would let you only offer the option if the outfitter has a map, too (and reference the strength of the map as well).

The spaceport auto-check is unlikely; we are attempting a natural remedy with the current "news" mechanic and more spaceport missions.

**Comment by endless-sky** [comment]
There's no logical reason that the player would be able to know a mission is waiting for them in the spaceport without actually going there. The idea of a "spaceport mission indicator" has been raised before, but I don't think it makes any sense.

As for auto-buying a map, that could get rather costly because every time you're in a system where the map would show you even one new system, you'd end up buying it automatically.

Similarly, auto-visiting spaceports could get you into a lot of trouble if you're in the middle of something else (say, a rush job) and suddenly get a storyline mission that you can't turn down without dropping out of that story. So again, in practice even if the option were available most people would revert to manually deciding when to visit the spaceport.

**Comment by ghoulavenger** [comment]
> As for auto-buying a map, that could get rather costly because every time you're in a system where the map would show you even one new system, you'd end up buying it automatically.

Considering the radius of local maps this is probably not as common as you might imagine. The point is valid, but seems like a very uncommon scenario (like it might happen a few times a playthrough, which for the price of a local map is negligible). That being said, I honestly don't care either way about the option -- I prioritize buying local maps anyway.

I would like to see the spaceport stuff improved, but I'm not sure this request is the right course of action (to me it seems more like it should show up on the jobs board if it were to show anywhere at all, and maybe some spaceport missions should start on the jobs board but not all of them -- under the table dealings and coincidental things shouldn't show up on the jobs board), and isn't there something already in the works to improve the spaceport?
