### ISSUE TITLE
Bug: Enemies stop fighting when you get too far from the system center

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#363]
It makes sense that a defense fleet will stop chasing you if you get too far from their planet, but the weird thing is that they stop firing at you when this happens, *even if you're still in range and shooting them*. The effect is very bizarre - I cross some invisible line, and suddenly all the ships turn yellow on my map and stop firing at me, and I can just stop right there and shoot down a bunch of them without getting any return fire. I've destroyed fleets much larger than my own just by flying back and forth across this line.

Any of the following behaviors would ameliorate the problem:
 1. They keep pursuing as long as I'm close enough to them, no matter how far I am from the system center
 1. They immediately resume pursuit any time I fire on one of them
 1. They shoot me when I'm in range even if they're turning around to return to the center
 1. They don't turn around in-place, but swing out in a circle, so that at least they don't come to stop where I can shoot down a bunch of them without effort

**Comment by brick96** [comment]
Its intended to prevent kiting
See #248

**Comment by dplepage** [comment]
I understand that the goal was to prevent kiting, but that patch introduced a new and even less believable interaction - the entire fleet starts ignoring me and then stops and turns around while I'm actively destroying them. They don't even attempt to defend themselves. I've been in several situations where I was able to fly my modest warship right into the middle of a group of cruisers and rip two of them apart while none of them fired a single shot at me.

I think the best solution would be the third of my proposals above - they stop pursuing, but keep firing their lasers when the target is in range.

**Comment by dplepage** [comment]
b8c5e58302b1d074f5092572f558e2f4fb488a1d fixed this - thanks!
