### ISSUE TITLE
Switching from window to fullscreen fails when mouse not over the window

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#3631]
When the game is windowed and the mouse cursor is not over the window, pressing `"Toggle fullscreen"` (F11) doesn't switch to fullscreen. It works fine when the mouse cursor is over the window.

**Comment by KiLEdEnNis** [comment]
I can't seem to reproduce this when I tested it with the game built from source
what version of the game are ya running and on what OS?

**Comment by jostephd** [comment]
Git aa148774cfd6fb71a18f442e764efa8cd149cff7 on linux.

**Comment by KiLEdEnNis** [comment]
mine is on Windows 10
I can imagine something like this to be specific to certain OS' but if it's not easy to fix then it's not worth fixing at all
it's just a mini annoyance that just a few people would experience

**Comment by Hacklin** [comment]
I cannot reproduce this on openSUSE Leap 42.3 with KDE/Plasma 5 with ES release and debug builds from git master.

**Comment by jostephd** [comment]
Thanks. The `SDL_KEYDOWN` event is received twice, that leads to `SDL_SetWindowFullscreen` being called twice. I added a simple guard to filter out the second call (d2dde60) - it's not a real fix but is good enough for me. Feel free to close this.

**Comment by Hacklin** [comment]
Looks like an SDL2 issue.
https://bugzilla.libsdl.org/show_bug.cgi?id=3287

**Comment by jostephd** [comment]
Thanks for all your help debugging this, @Hacklin ! I use sdl 2.0.5 which is vulnerable to that issue.

**Comment by jostephd** [comment]
Fixed by https://github.com/endless-sky/endless-sky/commit/f385735096d29de94ca64112bea750049ef62722
