### ISSUE TITLE
[Spoilers] Complete list of current missions

### ISSUE THREAD

**Issue by Taose** [endless-sky/endless-sky#3632]
Right, I'm unsure if there's any content left for me to play. I've found myself helping to terraform planets in the drone system, about three done. Is there anything left? Did I fail a mission without realizing? 

Do we have a complete list of missions that I can look through?

Is it possible to make it clearer in the game data whether a mission has been "offered" "completed" "failed" "aborted"?

**Comment by jafdy** [comment]
This is a bug tracker not a forum. For help go to the google groups, steam forums or discord.
The list of missions done is kept in your save file.

**Comment by Taose** [comment]
Didn't read the entire issue.

**Comment by jafdy** [comment]
You can dislike me all you want, this is the wrong place for it, end of story.

**Comment by KiLEdEnNis** [comment]
GitHub is for feature requests, bug reports and pull requests (adding content or fixes to the game)
questions like yours, which have nothing to do with creating or improving the game, are like Jafdy said for the Steam forums, google groups, Discord or even the reddit

please close this issue

**Comment by Amazinite** [comment]
#1385 
Please close this issue.

>Is it possible to make it clearer in the game data whether a mission has been "offered" "completed" "failed" "aborted"?

How more clear can it be made?
`"<mission>: offered"` means it was offered.
`"<mission>: active"` means you're currently doing the mission.
`"<mission>: done"` means you completed it.
If offered but not active or done, the mission was failed, aborted, or declined, and there's no necessity to make a distinction between failed, aborted, or declined in the game.

**Comment by Taose** [comment]
Yeesh, then you wonder why volunteers are few and far between. It was a simple query that could be answered by a link to the planning documentation. I gather no one has a coherent list?

If I were after what other players knew I'd be asking there but I didn't want hints or tips I wanted developer information. Well done all for being professional, welcoming and insightful.

**Comment by tehhowch** [comment]
All missions are in the game files in the data directory. So far we have been good about labeling the relevant texts with "* jobs" or "* missions".

As are as a more condensed list, no. You could amend the source code to allow printing the contents of GameData::Missions if given a specific command line argument.

**Comment by Taose** [comment]
How it should be done. Thanks.

**Comment by kikotheexile** [comment]
FTR no one was being mean here, although it easily could have come across that way. This just isn't the right place to ask such questions. There are four other platforms perfectly suited to handling this question, but the github isn't one one of said four.  

Feel free to still hit up the four community platforms. You will often come across many of the same active community members and they will be more likely to answer your questions rather than just tell you "wrong place" and be blunt.
