### ISSUE TITLE
Inactive finisher is treated as not having hit force

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3634]
I thought that something was wrong when I noticed that the *inactive* finisher barely pushed around pirate interceptors at all as compared to ordinary torpedoes, and then I realized that something was definitely wrong when I saw that the *active* finisher threw them across the system.

**Comment by tehhowch** [comment]
It doesn't have hit force.

Submunition damage is packaged into its parent projectile, but this is not true for hit force.

I can see arguments both for and against this being done - some projectile stages are fast moving, while some are not.

**Comment by Bladewood** [comment]
I don't see why we couldn't just make it behave like damage and subtract it from the parent projectile, like with Korath minelayers.
In any case, I find it very weird that the finisher would at any point inflict no hit force at all, given that the inactive state still deals a huge amount of damage.

**Comment by KiLEdEnNis** [comment]
giving it at least half the parent's his force seems good to me

**Comment by endless-sky** [comment]
This should be fixed by 66fafea.
