### ISSUE TITLE
"offset" tag doesn't work for various objects(?)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#3640]
so first some backstory
in 0.9.8 the map works fine, but with a source build, stars overlap as seen in this recent screenshot from @MCOfficer (when he pinpointed the apparent source of this bug), and moons align perfectly with planets (third screenshot)
![temp18](https://user-images.githubusercontent.com/10348657/36075898-40ff8230-0f55-11e8-8b09-8a9f66ffc77c.png)
and this one I just took in Cardea, where the stars literally overlap
![temp19](https://user-images.githubusercontent.com/10348657/36075956-fe0a02a6-0f55-11e8-90f7-48225c0455ae.png)

the cause is probably the "offset" tag not working for objects (so if one has 2 stars with the same distance/period, and 1 has an offset, the game disregards it), although ringworlds seem unaffected and not all stellar objects seem affected either
what I also noticed is that planets with moons may have some of their moons exactly above them, as seen in a plugin system: the inner 2 moons align perfectly, and this is also the case for various base game systems
![temp20](https://user-images.githubusercontent.com/10348657/36075985-7c357584-0f56-11e8-9040-e61a81269e4d.png)

further info we have on this bug:
- it's apparently Windows-only, tested by MCOfficer after @flaviojs pointed out this bug did not happen on Linux, we do not know if it also happens on mac as we have no one to test this
- it was tracked down by MCOfficer that 1c6e6a6 is the cause of this bug; a source build from right before this commit was made did not have this bug
- making the stars landable (@warp-core his idea) or changing the sprites etc. does not affect this at all

so a short summary; the commit I linked above seems to have caused offset being ignored for various stellar objects on Windows but not Linux

**Comment by warp-core** [comment]
@flaviojs was able to identify the specific code that caused the issue and has the solution.
Line 67 of Angle.cpp, changing `lround` to `llround` seems to fix the issue. He'll PR it when he wakes up.
