### ISSUE TITLE
Internet radio

### ISSUE THREAD

**Issue by louis123456** [endless-sky/endless-sky#3648]
The creator of Endless-sky said he listens to his own music when he plays games. What about internet radio station support.

**Comment by tehhowch** [comment]
Built in to the game? Really?

Unlike game music, internet radio streams would be entirely unrelated to the game. Just use your current method of listening.
Close this issue.

**Comment by jafdy** [comment]
Already done, you need to alt-tab out of the external camera view, use the station browser to find your favourite radio station (it's nicknamed Google), then you start the stream and alt-tab back to the external view.
It's no simple job to find these stations, not to mention that they can be location specific, as such we felt this was the best way to implement it.
