### ISSUE TITLE
Heat sinks barely working

### ISSUE THREAD

**Issue by AylexMorhaven** [endless-sky/endless-sky#3649]
I've had a glitch with heat sinks barely doing a fraction of their specified level.

Example: Korath heatsink with 3240pts of cooling only reducing heat 70 pts.

Have not been able to figure out a cause for this issue.

**Comment by Amazinite** [comment]
You have outfits expansions installed. Outfits expansions have a cooling inefficiency attribute that reduces how much cooling you get from cooling outfits.

Please close this issue.

**Comment by AylexMorhaven** [comment]
Thank you for the info.

**Comment by AylexMorhaven** [comment]
okay, Uninstalled all plug ins and deleted them.  Uninstalled and reinstalled Endless Sky via Steam.  and still getting the cooling inefficiency issue

**Comment by AylexMorhaven** [comment]
So I went into the outfit data itself and this is what I found.
it appears the cooling numbers maybe off. 
"Cooling Ducts"
	plural "Cooling Ducts"
	category "Systems"
	cost 10000
	thumbnail "outfit/cooling ducts"
	"mass" 5
	"outfit space" -5
	"cooling" 5
	description "When trying to cram as many high-powered outfits as possible into a ship, occasionally you reach the point where it is sporadically overheating and shutting down. In that case, you may need to install one of these."

outfit "Water Coolant System"
	category "Systems"
	cost 25000
	thumbnail "outfit/water cooling"
	"mass" 10
	"outfit space" -10
	"cooling" 12
	description "This system is a step up from ordinary cooling ducts; it circulates water in between an external radiator and your ship's hottest internal components to keep them from overheating.

**Comment by Brick63** [comment]
If you are experiencing cooling inefficiency and have any number of outfit expansions it will to some degree affect your cooling, it would help if you posted the ships outfits

**Comment by AylexMorhaven** [comment]
Found the issue.

When I uninstalled the Steam version, it had left remnant files and kept using corrupted files.  Deleted all files I could find and then reinstalled.  it appears to have taken care of the issue.

**Comment by MessyMix** [comment]
Erm, I don't know if it's a problem of corrupted files, because cooling inefficiency isn't a "bug" or an "issue"—it's a balancing feature built into the game. It's supposed to happen. If you managed to get rid of cooling inefficiency, I think we have a bigger problem...

**Comment by AylexMorhaven** [comment]
It was something to do with the files due to the fact that the cooling inefficiency details were not showing on the outfit expansions aspect.  Now those cooling inefficiency numbers are showing.  Thank you for the pointers on how to isolate the issue I was facing.  
Issue corrected.  THis thread can now close

**Comment by Amazinite** [comment]
You have to close it.

**Comment by AylexMorhaven** [comment]
Close

**Comment by Bladewood** [comment]
> it appears the cooling numbers maybe off.

Those numbers are per-frame, not per-second. The game runs at sixty frames per second, so for most attributes you just multiply them by sixty to get the value displayed in-game.

See the `cooling inefficiency` attribute on the [CreatingOutfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits) page:
> `cooling inefficiency`: the higher this attribute is, the less effective your cooling systems are. Both active cooling and regular cooling will be multiplied by 2 + 2 / (1 + exp(i / -2)) - 4 / (1 + exp(i / -4)), which forms the S-curve shown below.
> ![cooling inefficiency](https://camo.githubusercontent.com/2535196aa0a64033f151958e4990285ba835249d/687474703a2f2f656e646c6573732d736b792e6769746875622e696f2f696d616765732f696e656666696369656e63792e706e67)

Outfits expansions are full of them, and they'll ruin your cooling if you have too many of them.
