### ISSUE TITLE
Spaceport Missions Flagged on Job Board

### ISSUE THREAD

**Issue by jschiav** [endless-sky/endless-sky#3651]
One thing I actually hated in EVN and still find frustrating now is how missions offered in the spaceport are easily missed and have to be accepted right away or be lost forever. This is particularly egregious with plot missions, and it frequently causes new players to miss out on there even being a storyline at all due to having accidentally "postponed" a mission earlier (this was common in EVN, and, from a glance at Steam discussions, still happens all the time in Endless Sky). It's also a really easy mistake even for veterans to make.

While I still very much support the idea of the spaceport being the hub for storyline progression, I think it would be very helpful if missions were always ultimately accepted through the job board. The way I might see this working is that upon getting a prompt in the spaceport, it adds a unique mission to the job board that you can then accept, preferably with a noticeable flag like "Event" or "Special Contact". (In EVN, I seem to remember the Tutorial even highlighting this one time, where Jame- I mean, *cough* Gary tells you to pick up his mission from the Mission Computer... before the game promptly ditches that sensible mechanic for almost every other story mission.)

Ideally, the mission would be visible from any station thereafter, but could only be accepted at the right starting location. This might be challenging, since it could lead to job board clutter after multiple special mission prompts. An easier alternative might be to record all special mission offers in the player's logbook, reminding them that a mission is waiting for them at its location, so that a player has a place to find them without combing the save files.

**Comment by jafdy** [comment]
This would require a code change.

It would also mean that you need to visit 2 panels to accept a mission, and there will be people complaining that it's immersion braking.
A better solution would be to rewrite the decline options for spaceport missions to make them more obvious.

**Comment by tehhowch** [comment]
"I don't want to work for the Free Worlds anymore" is pretty transparent already.
