### ISSUE TITLE
Guns stop firing while moving forward and turning left at the same time.

### ISSUE THREAD

**Issue by Joshthejew** [endless-sky/endless-sky#3654]
Hi everyone, just started playing this game a couple days ago so sorry if this is either a known issue or is actually supposed to happen but I haven't been able to find anything on it from just searching. So I've had a few ships and the problem happens with all of them. My energy and heat are all in check so it's not the ship shutting down. Every time I try and turn left while also pushing forward and shooting at the same time, my guns stop working, but when I am turning right in the same situation, the guns continue to fire. Please let me know if this is already a known issue, if there is a fix for it, or if this is supposed to happen!

**Comment by Janaszar** [comment]
Only thing I can think of is that your keyboard/computer is unable to process the multiple key inputs.  But since you say it doesn't happen when you turn right, I'm hesitant to say that's exactly it.
Are you playing the Steam 0.9.8 Release, or the current GitHub/compiled yourself release?  I just tried the Steam version, and everything worked fine.

**Comment by Joshthejew** [comment]
I'm using the current GitHub, didn't know the game was on steam. If I get it on steam do you know how I can transfer my files so that I don't have to start over again by any chance?

**Comment by tehhowch** [comment]
Never go backwards in versions. You'll lose data, possibly crash your game.
You shouldn't need to do anything special to transfer a save, as both versions would write it in the same location.

**Comment by Joshthejew** [comment]
Oh man... so tried the steam version, had the same problem, so I tried plugging my desktop keyboard into my laptop and now it works... thanks for the help though!!

**Comment by Pointedstick** [comment]
I have the same issue on my laptop; it's a keyboard hardware problem. Please close this issue.
