### ISSUE TITLE
Autoaim homing fail

### ISSUE THREAD

**Issue by CruaverVoidDrake** [endless-sky/endless-sky#3656]
I'm not sure if I'm doing something wrong, but a mod I made that fires homing projectiles is for some reason unable to home in on targets when it's set to autofire. This seems like a bit of a design flaw, however I have tested it on escort ships and it works perfectly fine.

**Comment by Bladewood** [comment]
To note, there's a distinction between "auto-aim" and "auto-fire". Auto-aim turns your ship when your selected target flies in front of you. Auto-fire actually automatically fires on targets that are either in front of you, are in range of your turrets, or that you have selected.

Show your weapon's code. If it is how you described it, then it should be no different than using a Pug seeker or Korath grab-strike.

**Comment by jafdy** [comment]
Try some sanity checks, try targeting the ship, try a gun and turret version.

**Comment by CruaverVoidDrake** [comment]
Not sure what you mean by sanity checks, I have to target an actual ship for autofire on my own ship to seek out the target. The weapon on escort ships is just fine seeking out target ships, but on my own autofire it just behaves like I was firing in that direction. Which as stated by Bladewood is more of a problem with "auto-aim" not targeting hostile ships. Most likely originally intended for gun type weapons.

I'm not use to the formatting of github so please bear with me. This is the code for the weapon itself:

outfit "City Drone Launcher"
	category "Secondary Weapons"
	cost 1000000
	thumbnail "outfit/torpedo launcher"
	"mass" 150
	"outfit space" -500
	"weapon capacity" -500
	"turret mounts" -1
	"drone capacity" 5000
	weapon
		sprite "projectile/torpedo"
			"frame rate" 2
			"random start frame"
		sound "dronefire"
		"stream"
		"fire effect" "photorp fire"
		"hit effect" "photorp hit"
		"inaccuracy" 5
		"velocity" 10
		"random velocity" 25
		"lifetime" 300
		"reload" 5
		"firing energy" 500
		"firing heat" 25
		"acceleration" .8
		"drag" .1
		"turn" 4
		"homing" 3
		"radar tracking" 1
		"shield damage" 0
		"hull damage" 200
		"hit force" 1
		"piercing" 1
	description "Unlike the drone launchers of Aurora class ships these have an infinite supply as they can be manufactured inside the city."

**Comment by jafdy** [comment]
So the problem is that the turret is not selecting its own targets.
You can use triple backticks to add blocks of code (```).

Oh yeah and auto aim has nothing to do with turrets, it only applies to guns (by turning the entire ship).

**Comment by tehhowch** [comment]
Homing projectiles require you to have targeted a ship. There is no current functionality that enables projectiles to acquire targets after being launched. Such a modification would confer a performance penalty if implemented, and it would be especially noticable if not done *very* carefully.
