### ISSUE TITLE
Feedback on which new sound effects you like

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#366]
If you'd like to give feedback on what sound effects still need work, you can use [this form](http://endless-sky.github.io/sounds.html) to compile a list of which effects you particularly like or dislike. That will tell me which ones I should focus on improving. Thanks!

**Comment by gchapyzh** [comment]
Shall we post here?

afterburner~.wav	-1
anti-missile.wav	-1
atomic huge~.wav	1
atomic large~.wav	1
atomic medium~.wav	1
atomic small~.wav	1
atomic tiny~.wav	1
banisher~.wav	1
blaster.wav	-1
electron beam~.wav	1
explosion huge.wav	1
explosion large.wav	1
explosion medium.wav	-1
explosion nuke.wav	1
explosion small.wav	1
explosion tiny.wav	-1
fire-lance~.wav	1
flamethrower~.wav	1
heavy anti-missile.wav	-1
heavy laser~.wav	1
hyperdrive.wav	1
ion huge~.wav	1
ionic afterburner~.wav	1
ion impact.wav	-1
ion large~.wav	1
ion medium~.wav	-1
ion small~.wav	-1
ion tiny~.wav	-1
ion.wav	1
jump drive.wav	1
landing.wav	1
laser~.wav	1
meteor.wav	1
mod blaster.wav	-1
nuke.wav	1
particle.wav	1
plasma huge~.wav	1
plasma large~.wav	1
plasma medium~.wav	1
plasma small~.wav	-1
plasma tiny~.wav	-1
plasma.wav	1
proton.wav	1
pug anti-missile.wav	1
pulse.wav	-1
quarg anti-missile.wav	-1
rocket.wav	1
seeker.wav	-1
sidewinder.wav	1
torpedo.wav	1
tracker.wav	1
typhoon.wav	1
warder.wav	1
zapper~.wav	1

**Comment by Pointedstick** [comment]
anti-missile.wav	-1
blaster.wav	-1
electron beam~.wav	1
heavy anti-missile.wav	-1
heavy laser~.wav	1
hyperdrive.wav	1
jump drive.wav	1
landing.wav	1
laser~.wav	1
meteor.wav	1
mod blaster.wav	-1
particle.wav	-1
plasma.wav	1
proton.wav	1
rocket.wav	1
sidewinder.wav	-1
torpedo.wav	1
typhoon.wav	1

**Comment by frameworld** [comment]
Nice vote side. But I miss a undecided-option
afterburner~.wav	-1
anti-missile.wav	1
banisher~.wav	1
blaster.wav	1
electron beam~.wav	1
explosion nuke.wav	1
fire-lance~.wav	-1
flamethrower~.wav	-1
grab-strike.wav	1
heavy anti-missile.wav	1
heavy laser~.wav	1
hyperdrive.wav	1
ion huge~.wav	1
ionic afterburner~.wav	1
ion impact.wav	-1
ion large~.wav	1
ion medium~.wav	1
ion small~.wav	1
ion tiny~.wav	1
ion.wav	1
javelin.wav	1
jump drive.wav	-1
landing.wav	-1
laser~.wav	1
meteor.wav	1
mod blaster.wav	1
nuke.wav	1
particle.wav	1
plasma huge~.wav	1
plasma large~.wav	1
plasma medium~.wav	1
plasma small~.wav	1
plasma tiny~.wav	1
plasma.wav	1
proton.wav	-1
pug anti-missile.wav	1
pulse.wav	1
quarg anti-missile.wav	1
rocket.wav	1
seeker.wav	1
sidewinder.wav	1
takeoff.wav	-1
torpedo.wav	1
tracker.wav	1
typhoon.wav	1
warder.wav	1
zapper~.wav	-1
But some sounds which I like get annoying when they are overlayed by a lot of or some others (mission fights).

**Comment by tankhunterking** [comment]
atomic huge~.wav	-1
atomic large~.wav	-1
atomic medium~.wav	-1
atomic small~.wav	-1
atomic tiny~.wav	-1
banisher~.wav	-1
blaster.wav	-1
electron beam~.wav	1
explosion huge.wav	1
explosion large.wav	1
explosion medium.wav	1
explosion nuke.wav	1
explosion small.wav	1
explosion tiny.wav	1
fire-lance~.wav	-1
flamethrower~.wav	-1
heavy anti-missile.wav	1
hyperdrive.wav	1
ionic afterburner~.wav	-1
ion impact.wav	-1
ion large~.wav	1
ion medium~.wav	1
ion small~.wav	-1
ion tiny~.wav	-1
javelin.wav	-1
jump drive.wav	1
landing.wav	1
laser~.wav	-1
meteor.wav	-1
mod blaster.wav	1
nuke.wav	-1
particle.wav	1
plasma huge~.wav	-1
plasma large~.wav	1
plasma medium~.wav	-1
plasma small~.wav	-1
plasma tiny~.wav	-1
plasma.wav	-1
proton.wav	1
pug anti-missile.wav	-1
pulse.wav	1
quarg anti-missile.wav	-1
rocket.wav	-1
seeker.wav	-1
sidewinder.wav	1
takeoff.wav	-1
torpedo.wav	1
tracker.wav	-1
typhoon.wav	1
warder.wav	-1
zapper~.wav	-1

**Comment by endless-sky** [comment]
For the record, here's the feedback I've received so far, here and in the forum:

![sound poll](https://cloud.githubusercontent.com/assets/11450262/12280898/9589cfc0-b95f-11e5-95af-5dd4010caea6.png)
