### ISSUE TITLE
[Any Destination] 

### ISSUE THREAD

**Issue by CT5555** [endless-sky/endless-sky#3660]
Greetings, my question would be whether it's possible to make a mission where any destination (notwithstanding of it's traits) is acceptable. I'm trying to add an invisible mission that will add outfits to the ship and I don't want to longlist all of the existing governments. Plus it will not be compatible with the governments from the other mods.

**Comment by tehhowch** [comment]
This is not a "help-me-do-X" forum. Use the [Google Group](https://groups.google.com/forum/#!forum/endless-sky) or [Discord Server](https://discord.gg/u6KepgG) for assistance in content creation. Use GitHub Issues to file bug reports or feature requests.

Per [the wiki](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#source-and-destination-filters), you only have to specify a destination if the mission is being given by a ship (during boarding / assisting).

Please close this "issue." If you have further questions on this or other topics, direct them to the appropriate forum.
