### ISSUE TITLE
Not really an issue- Wanting to contribute with writing.

### ISSUE THREAD

**Issue by HNESauce** [endless-sky/endless-sky#3662]
Hello folks. I'm HearNoEvil, but call me Ben. I picked up Endless Sky a few weeks back, because I used to love EV and EVN, and I fell in love with this game very quickly. After inquiring via steam discussions as to how I could contribute, and talking with Kiko middle of last week, he pointed me to here, and to discord, on which I will post a link to this just after posting it.

So, after considering for a few days, I'd really like to contribute here. That said, my coding skills are sub-sub-par, though looking at the code a bit I feel like I can probably pick it up with significant practice, and my art skills are non-existent, so I think where I can contribute the most good is developing or helping story-lines along.

I've played through the FW campaign twice now, and am about to pick up and begin working through the current Wanderer campaign for the 2nd time, and I think I have a feel for where the story is going and how it will get there. That said, it is something I plan to do a 3rd time, taking notes, to make sure I'm capturing the 'feel' of the campaigns, and hopefully, transfer that over.

As far as I understand, there has been significant work on the Syndicate campaign, and iIrc I think I saw something about a bit of work done on the Republic line; I do not want to step on anyone's toes here, I simply want to contribute, so in that spirit, I would like to request access to those campaigns to-date, to, again, make sure I can understand the feel of them, but if I'm bothering anyone by touching their work, no worries, I'll just excuse myself from that campaign.

I already have a few ideas bouncing around in my head for long-term plot, and several specifics for Republic and Syndicate lines, but again, I'd rather work with those developing these paths, than forge ahead on my own.

I have a couple of weeks with significant free time, so I'm ready to throw myself, body and soul, into contributing here.

Contact me via steam, HearNoEvil, discord via Cyriaca#7338, or respond to this, which I will check regularly over the next couple days as I finish play-through's 2 and 3, before I begin actually working on anything, so I sincerely hope those working on current lines are willing and able to contact me.

Thanks for your time, and I look forward to contributing.

**Comment by tehhowch** [comment]
Please close this issue, and re-open in a more suitable context. GitHub Issues are for bug reports and feature requests.

I suggest the Google Group: https://groups.google.com/forum/#!forum/endless-sky
