### ISSUE TITLE
Repair Gun

### ISSUE THREAD

**Issue by Prorated-giblets** [endless-sky/endless-sky#3666]
I was coming up with designs for a support ship today. It's main focus is anti missile, (so larger ships can focus on firepower) and thought it would be neat if it had the ability to repair other ships. The way I think It might work is to create a gun that has a negative hull damage. I tested this out and it works. (I repaired a cargo freighter while it was being attacked by pirates.) The issue I imagine with this is programming the AI handle these weapons. It needs to know to target ally's only with the repair weapon. Going this far, repairing ships in battle could be a way to improve your relationship with a faction. I know there is a repair outfit already, but I think allowing ships to repair each other in battle would be a useful feature.

**Comment by jafdy** [comment]
#334
#748
#861

**Comment by Prorated-giblets** [comment]
Ok......hear me out. What if it's a secondary weapon with a limited amount of ammo? That solves two problems. It allows ships to use it as an alternative fire mode, and forces the player use it sparingly. The ammo might be very expensive and only available in certain systems.

**Comment by jafdy** [comment]
That's very nice . . . but the AI support is still needed and that it part of those issues.

**Comment by Prorated-giblets** [comment]
Alright, I guess I'll look at the source code myself if you're going to be a smart ass.

**Comment by Wrzlprnft** [comment]
you have to keep in mind,that we have no dev team here which takes all the ideas and decides wether to give them a shot. if you make a suggestion here, especially which involves actuall programming(less programmers than content creators on here), it's either “convince somebody“ or “do it yourself“(even if it is just a crude prototype to highlight and test the gameplay benefits). Yet, noone commented here to do so.

jafdy probably tried to acknowledge the fact that, while being a duplicate issue, you have thought about it and gave the idea your own spin, but also tried to add, that you might have still some convincing to do(use cases, drawbacks, maybe some concrete implementation suggestions, you know, clear all the unclear decisions).

**Comment by jafdy** [comment]
Perhaps I was a bit blunt, I'm like that. The exact way a repair weapon works is quite easy as the systems are already in place but regardless of your preferred implementation you will always run up to that same AI issue.
