### ISSUE TITLE
Make Ship Icons Right-Clickable

### ISSUE THREAD

**Issue by jschiav** [endless-sky/endless-sky#3674]
I think it'd be very useful to be able to right click a ship icon in the bottom left to give a move-to order to whatever ships you have selected (or have the entire fleet gather at that ship's location if no ships are specifically selected). 

It could also be context-sensitive, so that if the ship being right-clicked is disabled, your selected escorts would attempt to repair it, or if it's out of fuel they could give surplus fuel (if any of them have any to spare). Basically, right-clicking the icon would be be like right-clicking the ship in space.

The functionality of left-clicking the icon to select the ship is already implemented, so this would just be about adding a right-click event.

**Comment by tehhowch** [comment]
And when the icon is a stack and not a single ship? When selected ships are a part of the clicked stack?

**Comment by jschiav** [comment]
Well, it wouldn't be ideal, but you could default to the top ship in the stack or to the ship that is the most damaged (like how the stack shows the bar for the ship that has the least of that bar).

**Comment by jschiav** [comment]
Ideally, the stack would expand when mousing over it, so you could both see individual ships and select them. But I imagine that would take a great deal of time/effort to implement, which is why I didn't mention it.

Good point on whether the ships are in/out of system. I think the right-clicked ship should default to the top ship IN the system, if there are ships both inside and out. However, if the ship right-clicked is definitely outside the system, the selected ships should try to warp to that system.

This actually would add a great deal of functionality to escorts, now that I think about it.

**Comment by jschiav** [comment]
Just out of curiosity... but why? Is this not a good idea?

**Comment by tehhowch** [comment]
My guess is that it is something that will largely be useful only to large-fleet playstyles, or has too many subtleties to be useful rather than confusing or counterintuitive to most players.

 If you can PR a sensible implementation, that will be your best bet for seeing this feature in the base game. If you can't write it yourself, you'll need to sway someone who can, or do what I did and learn it as you go. (I personally have too many pending PRs to go write even more ;) )
