### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by MikeDred** [endless-sky/endless-sky#3675]
The crashes happen between 1 hour and 5 minutes apart. (mostly about 10 minutes apart)
During any part of the game, including if I'm in the trade screen and leave the room. 
I monitored my resources and the only thing I noticed was my GPU spike to 100% 
It happens in windowed mode and full screen too. 
I'm a steam player version 0.9.8 
I7-4770K processor 
16GB ram
Windows 10 pro 64-bit (with all updates)
NVIDIA GeForce 770 graphics

**Comment by MCOfficer** [comment]
do you get any error message when it crashes? what nvidia driver version are you using?

if you can, please run endless sky from the commandline with the `-d` flag: `endlesssky.exe -d`. the last message in the console after the crash might be an error message.

**Comment by MikeDred** [comment]
NVIDIA 391.35 (I keep it updated)
The only error message is the "there was a problem" and I click to close it. 
I have tried restarting the game and windows... closing all background apps. nothing helps.

**Comment by MikeDred** [comment]
Sorry, forgot to say, yes, I'll run from command now and let you know.

**Comment by MikeDred** [comment]
Windows message "a problem caused Endlesssky to stop working"
Nothing popped up in the CMD prompt. 
Is there another way to find error messages?

**Comment by MCOfficer** [comment]
there might be afile called `error.txt` in your ES folder

**Comment by jafdy** [comment]
That only gives errors for .txt file syntax on startup. A crash in the trade window couldn't be caused by something that would showup there.

**Comment by MikeDred** [comment]
no txt file. 
This time it worked for 2 hours. Then crashed after a jump into a system. 
Seemed like a windows error.

**Comment by Wrzlprnft** [comment]
how does your audio system and drivers look like? (weird question, but the past (and personal experience within the last 2 weeks and a 760) have shown that using other audio drivers than the nvidia ones coming with the graphics drivers cause random application graphic freezes for me)

**Comment by MikeDred** [comment]
I shut off the sound, played and it crashed in 12 minutes. :(

**Comment by MikeDred** [comment]
I turned on the CPU/GPU monitor in-game. When it crashed just now, the GPU % was not a number, it was a colorful smudge.

**Comment by tehhowch** [comment]
Using which build? MCO 's forum build? A self build? Or the downloaded pre-built 0.9.8 binary from the release blog post? (Ideally you could try with all of these and indicate which works and which doesn't)

**Comment by MikeDred** [comment]
Played through steam, game crashes.
Using the source code om my computer it's rock solid!
Thanks!

**Comment by MikeDred** [comment]
Yes, the forum instructions. I downloaded the same version, 0.9.8
I can certainly experiment and see if any of the others give me issues.

**Comment by MCOfficer** [comment]
just to be sure - you downloaded the .exe from my server, you didn't compile the code yourself. right?

**Comment by MikeDred** [comment]
Correct, I grabbed only what the forum said to and got the latest stable endlesssky.exe 
No compiling here. (so not source code... just pre-compiled files) sorry for the confusion.
Happy to report not a single crash when I host the game. But if I play from Steam... crash!

**Comment by Wrzlprnft** [comment]
There are some shenanigans with a library this game uses and steam does not ship or does ship with it or ... i actually don't know, but it has been the cause of some crashes on some Linux Distributions, maybe it's a similar thing here.

**Comment by MikeDred** [comment]
Should I close the thread? We have not fixed or found the issue with my steam version but the downloaded files work perfectly. SO it's a workaround that made me happy. J

**Comment by gunqqer** [comment]
I say keep it open; if you still crash on steam it isn't fixed. You just have a temporary fix to the problem (having someone compile it for you)

**Comment by MikeDred** [comment]
Okay, will do, thanks

 

FYI, I love the sick "author" ships that rip through systems like ninja ghosts. J

**Comment by tehhowch** [comment]
Can you verify if you experience the same issue playing the precompiled v0.9.9 release?

**Comment by Amazinite** [comment]
We're a ways out from v0.9.9 now. Any news on this?

**Comment by Amazinite** [comment]
With v0.9.11 being released soon and no response from OP (or anyone else) on this issue reemerging, I think we're safe to close this.
