### ISSUE TITLE
Flycatcher

### ISSUE THREAD

**Issue by Knightroad** [endless-sky/endless-sky#3676]
Why do the Wanderers have the Flycatcher, but no ships that can carry drones? The only ways to use this is to A, buy a human Carrier/Cruiser, which are laughably out classed by this point. Or B, _try_ and capture a Korath drone carrier, which is far more trouble than it's worth.

**Comment by Janaszar** [comment]
There have been a few ideas for Wanderer Drone Carriers, #1730 has a nice design.
But I believe they were introduced more as a "lore" ship (Wanderers using the drones as cheap and no-risk anti-missile) than to be used as a proper drone by the player.

**Comment by Knightroad** [comment]
That's unfortunate. When I first saw them, I loved the idea. A way to help against missiles that's not a waste of space(like the radar jammers).
