### ISSUE TITLE
Hostile Oathkeeper Escort

### ISSUE THREAD

**Issue by azurehelm** [endless-sky/endless-sky#3678]
During the "Liberate Poisonwood" mission, the Oathkeeper Cruiser that spawns as a mission escort spawned hostile to me. Not a game-breaking issue, but does make the mission more interesting to have an enemy that I need to avoid attacking.

**Comment by KiLEdEnNis** [comment]
making a new branch like that? no

the options are:
- the Oathkeeper ship doesn't spawn if your rep is below 0 (the other branch plays instead)
- the Oathkeeper rep is set to 1 if it's below 1 (unlikely)
- the ship gets the escort personality, which is weird

**Comment by toilethinges** [comment]
#1816 #2753 (a few more as well)
