### ISSUE TITLE
how to translate things?

### ISSUE THREAD

**Issue by bmorel** [endless-sky/endless-sky#3680]
Hello.
I just discovered this game (and am still learning the ropes), and I think that translations may help it. So, is there is any way to contribute or to start translations?

**Comment by tehhowch** [comment]
This is a topic currently best suited to the Google Groups thread: https://groups.google.com/forum/#!category-topic/endless-sky/MB9kNWqWyho

Or to the existing GitHub Issues
https://github.com/endless-sky/endless-sky/issues/201
https://github.com/endless-sky/endless-sky/issues/558
[and kinda this one](https://github.com/endless-sky/endless-sky/issues/1090)

Please close this issue.
