### ISSUE TITLE
Angle-view ship thumbnails in the shipyard

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#3682]
I'm trying to brainstorm ideas for "experimental" additions to the game that could easily be added in unstable releases to get player feedback, then removed later on if people don't like them. (Like the news system.) One idea that has been floating around for a while, and that existed in Escape Velocity, is special thumbnail images of ships just for the shipyard. Here's a mock-up of what that might look like:

![shipyard mockup](https://user-images.githubusercontent.com/11450262/38460337-cb2ebe66-3a85-11e8-89c1-73b8be6dabba.jpg)

The disadvantages would be:
- More work for content creators.
- Some ship models are only designed to look good from the top down.
- More images to load and more memory usage.

On the other hand, for most models it'd only take 5-10 minutes to render and post-process a shipyard thumbnail. The shipyard would fall back to using the main sprite for any ship that doesn't have a separate thumbnail sprite.

**Comment by jafdy** [comment]
It's a nice idea and I see no reason not to have the capability. 
Some ships (like the mule) might need a slight rework to make it look decent.

**Comment by Brick63** [comment]
Personally I feel that this could work as an optional feature that can be turned on and off.

**Comment by KiLEdEnNis** [comment]
as Kiko said before, the human ships are getting reworked by some of us (kryes omega, wrzl & me), so they're not really a problem as we aim for good models, not just top-down views
as for alien ships, I can't really imagine any alien species where this would look bad (maybe a couple Hai ships)
it could look bad on the current Quarg ships too, which aren't for sale anyway & if I remember, Brick and maybe some others were working on better Quarg ships

that plus the upsides it gives would make the shipyards look a lot better, and making it a toggle feature (making a toggle button both IN the shipyard and in preferences) would fix basically every downside apart from the "more memory to load"

**Comment by kikotheexile** [comment]
Yup, this just basically just motivates the team to *want* to rework the ships so their flattering angles are used. 

Advertisements, actual shipyard images, and scenes to be included in story missions will go a long way to help player immersion and add polish to the game. People are going to love it, and it will be fun to work on. The only downside is that it will slightly raise the difficulty of ship modding/art.

**Comment by KiLEdEnNis** [comment]
to be honest, if a modder can make a ship and post-process it, they can easily do this as well, it's just a matter of repositioning the camera, rendering, and post-processing a bit

**Comment by jafdy** [comment]
Some people do make/import ships in 2D. So they can't just "reposition the camera".

**Comment by Amazinite** [comment]
Took a quick poll on the Discord server for this idea. After an hour, it seems like this is an overwhelmingly supported idea.
![screen shot 2018-04-07 at 6 19 31 pm](https://user-images.githubusercontent.com/17688683/38460850-7498da86-3a90-11e8-9396-b55a8f43e6e2.png)

And while on the topic of experimental additions designed for feedback, here's the results of the poll on the current iteration of the news system that I took back in January. (Granted, I did word this one very differently than the new shipyard view poll.)
![screen shot 2018-04-07 at 6 20 31 pm](https://user-images.githubusercontent.com/17688683/38460851-75e40c80-3a90-11e8-800e-416e2d462470.png)
![screen shot 2018-04-07 at 6 20 41 pm](https://user-images.githubusercontent.com/17688683/38460852-78063326-3a90-11e8-968c-52d1290d4335.png)

**Comment by Muffindrake** [comment]
Do ship previews need to have a single fixed perspective across the board?

I was previously unaware of the Sparrow's back wing and I'm sure there are many more interesting details that I missed. Instead of showing always that perspective, the _best_ perspective could be shown for each ship.

Another possibility would be showing multiple angles of each ship in some way, perhaps a slideshow that starts when they are selected in the shipyard.

**Comment by Amazinite** [comment]
I'd say that ships should all have the same angle, but selecting a ship to preview the stats on it could cause the ship's image to start rotating to show off more of the ship.

**Comment by Wrzlprnft** [comment]
one could set up a blender template to automatically render the needed images from let's say 45 degree angles.

**Comment by warp-core** [comment]
It occurred to me that this would remove any way for the player to tell how the ship will actually look in gameplay but an option in the shipyard panel to switch between top down and isometric(?) view, like Kile suggested earlier, would fix that.
Also, I imagine at least some new players might expect the game to not be 2D after looking in the shipyard if the hadn't read the description or looked at the videos and screenshots on the Steam page. Though, I suppose there aren't going to be many people who won't read at least the beginning of the description before starting a game and I don't imagine many people are going to go out of their way to accommodate those kinds of people.

**Comment by Amazinite** [comment]
>It occurred to me that this would remove any way for the player to tell how the ship will actually look in gameplay but an option in the shipyard panel to switch between top down and isometric(?) view, like Kile suggested earlier, would fix that.

I think the simplest solution, instead of a toggle, would be to have the image above the stats on the right (where you currently see a shuttle in the example image) would be top down. I really don't see the necessity for a toggle option.

**Comment by KiLEdEnNis** [comment]
so either:
- toggle
- have the ships in the shipyard be 3D, but have the owned ship on the right panel (like in MZ's mock-up) be 2D

**Comment by solardawning** [comment]
I've always felt like there were missed opportunities to show what the ships really 'looked like'. As someone who hasn't looked through the models, and was familiar with the top-down perspective only, this image has already changed my mind on some ships that I didn't think looked good. (Aerie, Corvette, Headhunter...)
I'd love to see this in the game. It makes the ships feel more detailed, and gives them a sense of personality. Right now a player could be forgiven for thinking that the ships were only 2d sprites, not pictures of a three dimensional model.

**Comment by Zitchas** [comment]
I know this would radically increase the workload on graphics people, but having someway to pull up a panel specifically for the selected ship that has a picture of the ship "in action" would be awesome. Doesn't have to necessarily be combat, but just some living environment, ideally with something to give a sense of scale (like a ladder/boarding ramp, shuttle, doorway, etc.)

**Comment by Amazinite** [comment]
After over 36 hours, the poll is 80 up, 14 down. I think it's safe to say that a lot of people would like to see this idea become reality next update.

**Comment by manitscold123** [comment]
Also, keep in mind that artistically speaking, when you angle to the side you need to make it longer, due to perspective.

Also, on a more personal note, I feel that when the ship itself looks longer and sleeker (put it through a wind tunnel), it'll look better... *sexier*, if you will.

Essentially what I'm saying is that a few of the side model may need to be reworked to make them sleeker.

**Comment by KiLEdEnNis** [comment]
> Also, keep in mind that artistically speaking, when you angle to the side you need to make it longer, due to perspective.

not really, most ships in the mock-up look fine
I tried it with 4 reworked Tarazed ships, which is some project, it's most of what we have yet, but the 3D models will look good from all sides for such purposes, and they looked fine too
so your concern isn't necessary, although appreciated

**Comment by KiLEdEnNis** [comment]
after asking the project leader @kikotheexile , he said I should post said mock-up here
the ships, NONE of which are done yet (especially the Hawk)
A1: Finch
A2: Sparrow
A3: Hawk
A4: Blackbird
they aren't post-processed either, and maybe not aligned perfectly, it's just for the idea

this is what the new angle thing would look like on new ships
![image](https://user-images.githubusercontent.com/10348657/38601300-560e9072-3d67-11e8-8266-8d0ce77f2de6.png)

**Comment by gunqqer** [comment]
After PPing those mock-ups should look good

**Comment by KiLEdEnNis** [comment]
@endless-sky I'd love to hear what you think, even if the ships are unfinished

while the Tarazed ships are mine, everyone on the team is working hard to get this level of quality for the human ships

**Comment by endless-sky** [comment]
To me, those look more cartoonish than the original models, at least for those particular ships - mostly because of all the rounded edges and smooth shading. For comparison (again, not yet post-processed):

![thumbnail size comparison](https://user-images.githubusercontent.com/11450262/38745988-39af16a0-3f14-11e8-8496-e2e8f2d945d3.jpg)

**Comment by Amazinite** [comment]
I feel like the Barbs could do with some model work, and the two Hai ships + the Earth Shaper look really flat. The rest of those ships look fine to me at this angle.

**Comment by KiLEdEnNis** [comment]
the top-down shouldn't be an issue as far as I saw when I tested it yet, so that'd narrow it more to the 3D renders
I understand the concern of "too cartoonish", especially for my version of the Hawk, and while I think good post-processing should avoid this, I'll keep this in mind when we'd make our angled thumbnails
Kiko wanted every shipyard to look distinctive, with a style within each shipyard, and Tarazed happens to be a very smoothish theme while others will get a more cubic style (and thus look more realistic)
this means that the concern would probably be true for only a few shipyards, so we could make another mockup sometime later if one of the others finishes some of their ships, and in the meantime I'll try to make mine as realistic as possible

as for the models (the shapes), a lot of the current ships would need some good fixing to look in 3D, although that's already getting fixed by us for the human ships, we can get around to alien ships later on

thanks for the feedback though, it's very useful

**Comment by comnom** [comment]
If implemented, will the thumbnails also be used in MapShipyardPanel? If it hasn't been considered yet, I'd like to speak in favor of it.

I've got a quickie demo branch [here](https://github.com/endless-sky/endless-sky/compare/master...comnom:shipthumbs) that I've been using to test in game, and I think it adds some much needed negative space separating the ships on the left hand sidebar:
![mapshipyardss](https://user-images.githubusercontent.com/22107649/38747985-ac51abf4-3f1a-11e8-9d7e-aef645ac049d.jpg)

What you've got so far looks great though. I think this will do wonders for small ships. Their detail and even shape gets obscured alot since they need to be scaled relative to the larger ships. The thumbnails provide an artistic outlet to show them off at a better size.

**Comment by KiLEdEnNis** [comment]
that ship comparing thing has been in the source build for several months, and while it's nice to see people enjoy other peoples' content, it's not really relevant

**Comment by comnom** [comment]
> I like having the two ships being compared side-by-side like that.

> that ship comparing thing has been in the source build for several months

Yea, the point was the spacing of the ships (and current lack thereof) on the left hand sidebar. Appreciate the kind words though.

**Comment by Amazinite** [comment]
Speaking of other areas where this thumbnail view might be used, how about in the hail panel? That way we can get this angle for ships that can not be seen in shipyards. (I'd love to stare down an Archon.)
![screen_shot_2018-04-14_at_10 52 53_pm](https://user-images.githubusercontent.com/17688683/38778966-810a33e6-408f-11e8-8068-ab2c7a40e6b7.png)

**Comment by KiLEdEnNis** [comment]
if I remember, the ship IN that view is rotated the same way as it is in-flight, which has an actual use (not that big), and I'm a bit less inclined to have the 3D view here
although it could look good, we can always try
(also, you had to pick the picture with a Sparrow captain saying that, did you?)

**Comment by Amazinite** [comment]
>if I remember, the ship IN that view is rotated the same way as it is in-flight, which has an actual use (not that big)

The direction a ship is pointing can already been seen live under the map when you select a ship, so hailing a ship isn't required to see where it's going.

>The hail panel view also shows the ship's current hardpoints' direction, which otherwise must be viewed in-flight.

If a ship is not already close enough to see on screen, what is the use of knowing the direction its turrets are pointed?

**Comment by comnom** [comment]
> Speaking of other areas where this thumbnail view might be used, how about in the hail panel?

Aesthetically I like the idea, but as kile and tehhowch noted there are gameplay concerns. They don't concern me really, as like amazinite I don't see much use in knowing ship/turret orientation in that screen, but there it is all the same.

**Comment by Bladewood** [comment]
I took a look at the new sprites in-game.
My first impression is that the ships look much more awesome, but they're a bit too big (though this is probably just because I'm used to much smaller sprites in the shipyard).
This is especially evidenced by this shot:
![bigalbatross](https://user-images.githubusercontent.com/16506683/40866164-314444fe-65ca-11e8-8f9e-a2235c86b7e4.png)
Yes, it actually goes off-screen.

**Comment by endless-sky** [comment]
In terms of size, the outfit images are arranged in a 180x180 pixel boxes, and the largest ones fill nearly 50% of that box. Ships are in 250x250 pixel boxes; the current Bactrian sprite fills about 40% of that box. So, the ship sprites are not any bigger than the biggest outfit sprites.

The difference is that ships are sorted by size, so you end up with lots of very large sprites side by side, whereas outfits are sorted by category. Of course, without the cheater plugin most shipyards will only have a handful of very large ships, so the effect is less noticeable.

The challenge with the thumbnail sizes was to be able to convey the relative sizes for the ships while having a much smaller size range to work with (around 100 to 250 pixels, whereas the ship sprites themselves range from 60 to 700 pixels tall). Especially for something like the Albatross or the Deep River, it would be hard to fit them into a 250x250 box without making them appear much smaller than other ships that are actually larger in-game.

For reference, here's my size chart of all the thumbnails sorted from smallest to largest:

![thumbnail size comparison](https://user-images.githubusercontent.com/11450262/40877569-1c797076-6651-11e8-857a-ad98a310ee3c.jpg)

**Comment by jafdy** [comment]
If a ship is very long then I think it is fine having it overflow the normal box slightly, because the long ships are longer and thinner than the large outfits. This does also help emphasise the size of the ship.

**Comment by Brick63** [comment]
the template for the thumbnails seems to be missing from the drive

**Comment by Amazinite** [comment]
The ship thumbnails are pasted above the text in the shipyard, so if there is a thumbnail big enough then it could obscure the name of the ship. 
![download](https://user-images.githubusercontent.com/17688683/40879922-24a8b098-6676-11e8-9ede-48ba2f8f0ffb.png)

**Comment by johndh** [comment]
For really long ships, would it look better to make the angle more head-on to fit the whole ship within the thumbnail?

**Comment by Pointedstick** [comment]
Just want to mention that I LOVE this new style for ships in the Shipyard. It's absolutely fantastic.

**Comment by Pointedstick** [comment]
This was done in 0.9.9; closing as there's nothing left to do here. Any residual concerns should go in https://github.com/endless-sky/endless-sky/issues/4312
