### ISSUE TITLE
opengl 3.0 to 2.0

### ISSUE THREAD

**Issue by SHADOWELITE7** [endless-sky/endless-sky#3685]
I played this game on my desktop, my desktop broke and saving up to fix it. I installed ``Endless sky`` on steam on my other computer but it gave me this.
![image](https://user-images.githubusercontent.com/33847580/38469865-69d54dac-3b29-11e8-8e34-9227f5a21714.png)

can there be a graphics enhancement because my current computer only supports up to OpenGL 2.0

**Comment by Amazinite** [comment]
>The game makes use of OpenGL shaders and other extensions that aren't available until OpenGL 3. So, even if it could be ported to an earlier OpenGL version there would be a lot of issues, and that just wouldn't be worth it for the very small, and shrinking, number of people who still have such old systems. [[Source](https://github.com/endless-sky/endless-sky/issues/2562#issuecomment-304690530)]

Try this: https://github.com/endless-sky/endless-sky/pull/1559
