### ISSUE TITLE
Universality of credits

### ISSUE THREAD

**Issue by amilliner** [endless-sky/endless-sky#3687]
Playing through some of the more exotic questlines, with multiple alien races (each of whom have a unique technological distinctiveness), it struck me that credits are remarkably universal. Everybody uses/accepts them - even the Wanderers, who (as I understand it) have had zero contact with humans until the player shows up. Even so, every species and their (metaphorical) dog is willing to accept them on face value, with rigid adherence to their value.

Whilst mechanically this makes the game much less of a headache for all involved, it would be cool to get some kind of ingame acknowledgement or explanation of how this works or came to be, as part of the lore, even if it were only a sentence or two here or there.

**Comment by Amazinite** [comment]
>Just think of it as the same as "gold" in most RPGs; it just represents items of value that can be traded. Or, it could just be that there's an exchange rate between any two currencies and you exchange them automatically. It's one of those cases where realism is not the goal, necessarily... [#667]
