### ISSUE TITLE
The Protector has too high a crew requirement

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#369]
It's the lightest of the heavy warships, but it has a very high crew requirement that makes it very expensive to operate for players who don't yet have a hundred gazillion credits. I think a number in the mid-30s would be more appropriate.

**Comment by endless-sky** [comment]
I reduced the crew requirement by 6, so with 6 turrets it will be 36: 0450664.

**Comment by Pointedstick** [comment]
Excellent!
