### ISSUE TITLE
Escorts not powering up when out of power

### ISSUE THREAD

**Issue by zappyguy** [endless-sky/endless-sky#3690]
Have a series of Hauler III's that keep losing power and not powering back up. They have surplus power when idle and I cannot disable them while piloting them, but if they run out of power as an escort they will permanently power down and freeze in space.

An important note; the other third and older Hauler III fleet has System Cores (medium) as their shield generator and they do not suffer the same fate as their Hai protected counterparts.

My suspicion was that the Hai Diamond Generator and Crystal Capacitors were drawing more power than could be regenerated when the ship ran out but was unable to trigger this while piloting the vessels.

The ships are kitted with:
Turrets: 
1x Heavy Laser Turret
1x Chameleon Anti-Missile
2x Laser Turrets

Systems:
- Hyperdrive
- Quantum Keystone
- Fuel Pod
- Hai Diamond Regenerator
- Ramscoop

Power:
2x Crystal Capacitors
1x Millennium Cell

Engines:
- AR120 Reverse Thrust
- A375 Atomic Steering
- Forge-Class Thruster

**Comment by zappyguy** [comment]
Post post update.
I played around with this a little more and found that repeatedly telling the vessels to halt and un-halt will cause them to stop long enough to regenerate a little power and eventually accumulate enough braking force to stop and properly regenerate their power reserves.

**Comment by manitscold123** [comment]
This is *technically* your fault, as not having enough power to power your ship is completely up to the player. 
Your ships should **always** generate excess power even while in movement, or else something like this may very well happen again.

Perhaps you want to add a new launch failure screen?

On a more player based note, you should *probably* not give your freighters such expensive shield generators. The best course of action for this is to probably just give up on your Hai tech, and stick to whatever humans sell you. Of course, human freighters do suck so the cool kids all use Arach/Wander/Korath. Different shield generators don't actually make your shields stronger, they just regen shields faster.

**Comment by zappyguy** [comment]
I a feature where the ships freeze for 5 seconds when their power reserves are exhaust is what I am aiming at.
What is odd is that; when I run out of power, I can still move turn and shoot, albeit intermittently. But as escorts they freeze completely and if I do not press the "halt" command key every so often while frozen they will -permanently- remain that way.
As for my taste in shield generators, I'm a very impatient captain. I don't like waiting for freighter shields to regenerate, nor do I want to land and spend 2 days wages (67,000¢) just for a freighter with a flesh wound.

**Comment by ghoulavenger** [comment]
The very least power generation your ship should have is enough to operate the forward thrusters (not necessarily all the engines, since you're very unlikely to use both the thrusters and steering constantly) and still charge the battery. Any less and you will run into this problem when your battery power drains.

I do sympathize with your desire to have it feel better, but consider either upgrading your power generation or downgrading your thrusters.

**Comment by tehhowch** [comment]
In v0.9.9 fractional thrust is applied based on existing power. I expect this will resolve the issue.
