### ISSUE TITLE
Pug Gridfire Turret Not Functioning

### ISSUE THREAD

**Issue by manitscold123** [endless-sky/endless-sky#3691]
This is an on-off problem for me, so I'm somewhat confused.

For me, the gridfire turret works sporadically. Sometimes, it works, sometimes it doesn't this makes me somewhat triggered, as when it doesn't work, most of my ship's armament is already dead.

What I'm saying is that sometimes, the gridfire will fire, and it will actually hit it's target, but sometimes it'll do nothing and I'll be sad.

![screen shot 2018-04-09 at 11 14 37 pm](https://user-images.githubusercontent.com/20450688/38539246-2088815e-3c4c-11e8-894e-7b063fad46bf.png)
Bear in mind that I have auto-fire on for this, so in theory the gunship should be the ship getting hit.

However, sometimes the gridfire will actually do it's job, and I'll annihilate the Republic Fleet chasing me. 

![screen shot 2018-04-09 at 11 11 05 pm](https://user-images.githubusercontent.com/20450688/38540082-8414b992-3c4f-11e8-9c85-ad7302db06af.png)
Here again, you can see me (manually) targetting a frigate for me to eviscerate w/ gridfire, but even though the turret fires, the ship itself is not getting hit.

As of yet, I'm not sure if the gridfire works or not for the AI. I wouldn't know lol last time I had to fight an Arfecta was for the campaign and lol I parked my entire fleet on Vega before the Pug cut the hyperspace route (by accident, of course) so I kinda... rekt the Arfecta with the power of like 30 Shield Beetles and Bactrians ;)

**Comment by jafdy** [comment]
Are you playing with any mods? Because you are not meant to fight an Arfecta at any point in the main campaign.

Have you go enough energy to fire the weapon? And are you on a self-compiled or steam version of the build.

**Comment by tehhowch** [comment]
Indeed, the fridge requires you to **target** the ship - not just aim at it. You haven't shown this in your screenshots. If you are not targeting either

 1) no ship *at all*
or
 2) the ship you are trying to blow up,

then the Gridfire turret (and any other `phasing` weapons) will not damage the ship it is firing upon. As Bladewood mentions, if you are targeting a ship, the Gridfire can only damage that ship - `opportunistic` does not work well with `phasing` weapons.

**Comment by manitscold123** [comment]
To the first one, I don't have any mods. I'm pretty sure at the end of the human campaign, the pug sends an Arfecta after you, and you kinda have to kill it.

I'm using the steam version, my firing is on focused.

I'm not sure what the difference is between **targetting** and **aiming**

**Comment by Bladewood** [comment]
> To the first one, I don't have any mods. I'm pretty sure at the end of the human campaign, the pug sends an Arfecta after you, and you kinda have to kill it.

They don't. It only appears a total of three times in the game: two in the middle of the Wanderer campaign; and one in Pug Iyik if you annoy them enough.
> I'm not sure what the difference is between targetting and aiming
> 
> In the second screenshot you can see the four dots surrounding the Frigate, which is pretty sure what I think you mean by targetting.

You are indeed targeting it in the second shot.
The difference between "targeting" and "aiming" is that the latter only involves turning the ship or its turrets to face another ship, while the former requires you to select a ship.

**Comment by manitscold123** [comment]
Ok, after changing the auto-aiming to opportunistic, then back to focused, then to opportunistic and focused, I got the gridfire to work, correctly and hopefully permanently.

However, I still do feel that opportunistic aiming needs a little bit of work, as many times, it won't even fire, even when there is an overly large flotilla of navy ships after me, with the flotilla large enough to drop my frames down to 30 and to kick up my large fans. Perhaps it's only opportunistic aiming with gridfire turrets.

**Comment by warp-core** [comment]
It is known that opportunistic doesn't work well or at all with Gridfire Turrets, as @Amazinite said, and that is why the Navy ships after you aren't being attacked. You have to actually target one and only the targeted ship will be hit by the Gridfire (though the weapon does have a blast radius and so will damage ships near to the one being targeted).

Your issue with the Gridfire not working at all is, at best, unconfirmed at the moment.
This issue should stay closed.

(Further, the fact that your computer isn't capable of handling the number of Navy ships you've decided to fight and run the game at full speed has no effect on the choices the AI in the game make when it comes to combat.)
