### ISSUE TITLE
Overflow in dump cargo dialog

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#3692]
https://steamcommunity.com/app/404410/discussions/0/1696043806574246615/
User gets a crash at 1B cargo dump values. I don't think it make sense to use larger values but avoiding a crash seems like a good idea.

**Comment by Muffindrake** [comment]
#0  0x00007ffff5af8f00 in raise () from /lib64/libc.so.6
    #1  0x00007ffff5afaa57 in abort () from /lib64/libc.so.6
    #2  0x00007ffff64960b5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
    #3  0x00007ffff6493c66 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
    #4  0x00007ffff6493cb1 in std::terminate() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
    #5  0x00007ffff6493ef4 in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
    #6  0x00007ffff64be84f in std::__throw_out_of_range(char const*) () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
    #7  0x00005555555717d5 in __gnu_cxx::__stoa<long, int, char, int> (__convf=0x7ffff5afe520 <strtoq>, __name=0x5555558203a1 "stoi", 
    __str=0x555555b5ae80 "10000000000", __idx=0x0, __base#0=10)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/ext/string_conversions.h:86
    #8  0x0000555555571530 in std::__cxx11::stoi (__str="10000000000", __idx=0x0, __base=10)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/basic_string.h:6361
    #9  0x0000555555571367 in Dialog::DoCallback (this=0x555555b5ad70) at source/Dialog.cpp:295
    #10 0x0000555555570e76 in Dialog::KeyDown (this=0x555555b5ad70, key=13, mod=0, command=...) at source/Dialog.cpp:217
    #11 0x00005555555d8c07 in UI::Handle (this=0x7fffffffd4a0, event=...) at source/UI.cpp:84
    #12 0x00005555557bb190 in main (argc=1, argv=0x7fffffffdef8) at source/main.cpp:286

An uncaught exception in stoi(). Oh dear.

**Comment by endless-sky** [comment]
Fixed in 2068740.
