### ISSUE TITLE
Pug Gridfire Damages Self after closing Boarding Panel

### ISSUE THREAD

**Issue by manitscold123** [endless-sky/endless-sky#3696]
After you board a disabled ship, you can exit the boarding screen, at which point you will fire upon the ship and destroy it.

Because the Pug Gridfire does damage based on position of sprites (or something like that), after you exit the boarding screen your ship will fire upon the ship you were just boarding, dealing damage to yourself, because you were positioned right upon the disabled ship, because you just boarded it. Sadly, most captains aren't actually suicidal, so doing so would seem counterproductive.

Firing upon yourself with the already broken-af gridfires will damage both the hull and the shields, and, for many ships, may even destroy yourself. For example, shooting yourself in a shield beetle, after exiting the board screen on a carrier will take out quite a bit of your health bar. Ouch.

All I'm saying is that for gameplay and non-stupidity, you probably shouldn't shoot yourself with your own tier 3 weapons, especially since the damage here actually goes through your shields lol.

**If someone ok's it I'll add a PR where I just add a conditional, so that you don't run the code to shoot the enemy ship if your weapon is like gridfire or something.** Sadly enough, I'm pretty inept when it comes to writing C++ (and also reading C++ for the most part), but I can probably handle *one tiny conditional, right?* 👍

**Comment by manitscold123** [comment]
May I also add that it is mechanically simple to *accidently* disable yourself due to gridfire? Like, no joke, I just did it like three times in a row...

Twice against Korath, and then again against the Unfettered. Maybe it's just cuz I suck, but jeez this is just beyond.

**Comment by KiLEdEnNis** [comment]
once one leaves the boarding panel, if they have autofire on, they automatically  destroy the ship they just boarded
your issue would apply to any non-secondary weapon with splash damage
I personally think autofire shouldn't destroy a ship once finished boarding, and that would fix this

**Comment by Zitchas** [comment]
I agree. I don't use autofire most of the time, but even when I do, I rarely want to destroy the ship I just boarded. I'm interested in the loot, not blowing them up. If a player really wants to destroy a ship, it isn't that hard to shoot it.

**Comment by KiLEdEnNis** [comment]
if one wants to destroy it after; they still have it selected, hold space bar
right now one has to quickly deselect it

**Comment by manitscold123** [comment]
So is it okay to just remove the *auto-fire destroy a ship after cancelling boarding code?*

Though lol I'm not interested in the loot lol I'm more interested in the ship itself.

**Comment by tehhowch** [comment]
It's not clear what version of the game you are playing. Are you playing the Steam build? A build downloaded from the v0.9.8 release blog post? Self compiled? There have been a LOT of tweaks to the AI since v0.9.8 was released in August.

**Comment by manitscold123** [comment]
I am... using the Steam build.
