### ISSUE TITLE
Log for missions done

### ISSUE THREAD

**Issue by MikeDred** [endless-sky/endless-sky#3699]
When I check the log for completed missions, I do not see any from the remnant area. 
I finished 4 missions there: 
Surveyed the 2 gas giants.
got 50 "things" brought back and was paid. 
Defended the planet from attack.
Found and destroyed the big ship that was harassing them and got paid. (This one came up a second time as normal mission too)
I still can't buy a license to purchase gear from outfitter there.

**Comment by tehhowch** [comment]
Your post is not a bug report nor a feature request nor a well-formulated proposal for changes to make to the game. That is, your post is better suited for an actual *forum*, as opposed to an Issue Tracker. I suggest **closing this** and reopening it in a pertinent location such as the [Google Group](oups.google.com/forum/#!categories/endless-sky/general-discussion) or [Steam Discussion forum](amcommunity.com/app/404410/discussions/0/).

**Comment by MikeDred** [comment]
Didn't realize the log was not part of the game. My bad. I thought it may be related to why I didn't get the license. I'll close this. apologies.
