### ISSUE TITLE
No feedback that cloaking device couldn't be installed

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#37]
If you don't have 10 free outfit space (and almost always, you won't), it will land in your cargo instead.  There's no feedback that this happened and you need to install it manually (after squeezing some free space somehow).

This problem doesn't apply to the jump drive, as that replaces a hyperdrive that's at least as big, rather than being an addition.

**Comment by endless-sky** [comment]
A message is shown in the message bar on the bottom of the screen, but I agree that that is not obvious enough. I'll change it to a warning dialog.

**Comment by endless-sky** [comment]
A warning message should now be shown in a dialog if a mission tries to install an outfit in your ship and there is no space for it except in your cargo bay (as of commit 18be2ee).
