### ISSUE TITLE
Game Forces You to Sell Extra Fighters/Drones on Abandoned Planets

### ISSUE THREAD

**Issue by manitscold123** [endless-sky/endless-sky#3706]
In the Wei system, there is an abandoned planet called Hope. If you have any fighters w/o their respective carriers, the game will force you to sell the fighters/drones, and you WILL get money. However, this makes very little sense, as you can't sell ships to icebergs or whatever is one Hope.

![screen shot 2018-04-14 at 11 29 41 pm](https://user-images.githubusercontent.com/20450688/38775650-b546990e-403c-11e8-8bc3-9f9f767a1485.png)

This is an incredibly low priority bug (if you would consider it a bug in the first place), so um... yeah. You could probably add an ```abandoned``` tag to a planet, and from there the game won't force you to do anything you normally wouldn't be able to, on an abandoned planet.

**Comment by jafdy** [comment]
This has been brought up before, I'm too lazy to find the relevant issue.

**Comment by Wrzlprnft** [comment]
eieiei jafdy, calm down.

the question in this case is what's the expected behaviour, and what's the consistent behaviour. when this issue was already here at some point, i assume what you see was a decision in favor of consistent behaviour for fighters and drones regardless of surroundings. currently on mobile, i may check and edit this later on

**Comment by KiLEdEnNis** [comment]
the "solution" is park and get a carrier for them
although having to sell on every landable object ever does seem unrealistic

**Comment by Amazinite** [comment]
>You could probably add an `abandoned` tag to a planet

How would that be any different than the `uninhabited` tag that already exists and is already on all uninhabited planets?

**Comment by MessyMix** [comment]
#950

**Comment by manitscold123** [comment]
Oh, yeah. I read #950, and it's kindof relevant. 

@KiLEdEnNis, I understand your solution, but what I'm saying is that the sell dialogue shouldn't pop up. It would make more sense if, instead of pulling up the pop-up window, the game auto-parks the fighters for you or something when you depart, or something like that.

> How would that be any different than the uninhabited tag that already exists and is already on all uninhabited planets?

I saw the uninhabited tag. But, the tag applies to the system the planet is in, not the planet itself. I'm 99% sure there are inhabited systems with uninhabited planets somewhere in the game, so if you land on an uninhabited planet in a system with inhabited planets, it would be somewhat confusing. There's Covert and Mutiny in the Gienah system, Mutiny is uninhabited and Covert is a Pirate planet, but if you land on Mutiny the game will force you to sell fighters w/o a carrier (like if your carriers get blown up by pirates or whatnot), and you'll have to sell the fighters... which makes no sense.

**Comment by Amazinite** [comment]
>I saw the uninhabited tag. But, the tag applies to the system the planet is in, not the planet itself.

Watcher, Revelation, Mystery, Hope, Far'en Lai, Diligent Hand, and Ceaseless Toil are all planets with an uninhabited attribute. Not all uninhabited planets in the game have the attribute, but the uninhabited attribute is something that applies to planets and not the entire system.

**Comment by petervdmeer** [comment]
This issue should also be solved by #4388 (together with the linked issue #3764).
