### ISSUE TITLE
Individual Cloak?

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#3711]
I have no idea if this has been taked about before, but a way to cloak individual ships seems like something that should be already in the game. I often find this an issue when my flagship, which has weaker shields than my arfecta escorts, needs to disengage from the fight and replenish it hull strength and shields, however it currently does little good because my arfectas also disengage causing unnesdisary loss of my supporting missleboats, supporting battleships and carriers. A simple fix would be simmply a keybind that only cloaks your flagship. I haven't tried this yet, but it would also be nice to be able to select a specific escort and command it to cloak, just like with holding position. I'm pretty sure it would just need an added event for the key being pressed, but other than like 20 mins of coding there shouldn't be any unforseen problems with the fix. 

Thanks in advance for any help and /or corrections if I'm just oblivious and it is already being implemented or has been already put into the game.

**Comment by Amazinite** [comment]
Effectively a duplicate of #2916, which points out the all-or-nothing nature of cloaking.

**Comment by KyroFirehammer** [comment]
Oh, ok then!  I guess great minds think alike.  Thanks for the heads up
