### ISSUE TITLE
Add a Mining Command for your fleet

### ISSUE THREAD

**Issue by OverYrPaygrade** [endless-sky/endless-sky#3713]
I want to expand upon the little-used mining mechanic by allowing us to order our fleet to seek out and mine asteroids.

This allows us to bring an additional reason to employ fleets that aren't necessarily for combat, and gets us to actually use our collective cargo space while in space.

I know there's some kind of code implemented for the A.I to mine asteroids, hopefully that could be reused for this situation as well.

**Comment by MessyMix** [comment]
#2405 
#2264 
#2886

MZ's verdict: 
In general I want to avoid mechanics that encourage the player to make money in ways that don't involve any player action at all, e.g. taking a mining fleet into an asteroid-rich system and then grabbing a cup of coffee while your escorts do all the work.
--
