### ISSUE TITLE
Timmy the talking asteroid

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#372]
<img width="702" alt="screen shot 2015-12-04 at 3 46 42 pm" src="https://cloud.githubusercontent.com/assets/1097249/11603334/42fdd498-9a9e-11e5-954b-eae85acfc211.png">

Perhaps there should be an "unhailable" flag that could be given to certain ships, such as the Target Asteroid in the Terraforming Rand mission string.

**Comment by brick96** [comment]
Lol dats funny
