### ISSUE TITLE
The Bus Factor of this project is kinda low

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#3723]
Disclaimer: this is just thinking about worst case scenarios. 

While i think MZ does great work and makes (in almost all) cases great decisions, the way this project is set up, the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) (as in: how many persons can disappear before the project comes to a halt due to technical or knowledge loss) is quite low at... well 1. 

this is not a push for decision-making power for the community, nor a "what will happen if MZ loses interest", this is more of a reminder that, while we of course can make a fork and basically make that the main project, there seems to be no backup plan when looking at e.g. managing steam uploads and such.

the topic of lifting organizational pressure of MZ so the creativity get's not hindered by paperwork is an entire different issue.

**Comment by Amazinite** [comment]
Related: https://github.com/endless-sky/endless-sky/issues/3637#issuecomment-364621355 and the two comments after it.

**Comment by endless-sky** [comment]
I've been trying to work on a comprehensive design document for the C++ code, but that's been sort of a back-burner project. That would help both with on-boarding new contributors and with preserving the "institutional memory" of why certain design decisions were made.

Steam uploads are a relatively small part of the total workload; a new release including release notices and Linux packages and so on usually only takes a few hours. But, I suppose I could look into what it would take to grant a second Steam account full access just as a backup.

**Comment by Wrzlprnft** [comment]
In general, i'd just try to avoid a situation like [void linux has currently](https://voidlinux.eu/news/2018/05/serious-issues.html): the main and central person holding the permissions and such disappeared.
now, they are at a point where they either try and take over the project (which feels a bit ...meh) or they'll have to fork it and would loose everything that comes with the brand, basically.

in our case, i'm talking about github websites (website and wiki), commit permission, as well as the other channels: repos the game is part of, steam(publishing a release including notes as well as e.g. the guide section).

As said, this is just some worst case speculation. I personally would not know an elegant way to solve it.

**Comment by geojak** [comment]
Is this issue still relevant with the community much more directly involved now.

**Comment by Pointedstick** [comment]
Probably not.

**Comment by Zitchas** [comment]
It isn't really relevant in terms of the codebase and development - but still very much so in terms of the Steam (and possibly Linux as well) distribution.

**Comment by MCOfficer** [comment]
I'd rather not close this. There are a bunch of areas where the community is pretty much waiting on MZ instead of being able to do things.

- The asset directory. #4272 #4571 #4620 
- Steam. #4953 #3378 #5005 
- Any kind of official distribution, really. #147 #4630

Just to name a few.

**Comment by Amazinite** [comment]
Progress has been made, but we're not done yet. :)
@Pointedstick

**Comment by Pointedstick** [comment]
Fair enough!

**Comment by Zitchas** [comment]
With the first community-managed steam release (0.9.14), as well as the transformation of Endless-Sky from being an individual to being an organization and related changes; I think this can be closed at this point.

Concur? @Pointedstick @Amazinite

**Comment by warp-core** [comment]
Derpy said, during his stream today, that he thinks this can be closed after two successful Steam releases in relatively close succession by the community.

**Comment by Pointedstick** [comment]
Absolutely agree.

**Comment by Wrzlprnft** [comment]
The original concern of mine is indeed sufficiently adressed, i agree.
