### ISSUE TITLE
The game is too quiet, even at 100% volume

### ISSUE THREAD

**Issue by CyberShadow** [endless-sky/endless-sky#3725]
It seems like even at maximum volume, even the loudest sounds in the game are at a fraction of the volume of other games and applications.

I noticed that the max volume was lowered in https://github.com/endless-sky/endless-sky/commit/006238e85b7c9647e011c1d6bebcee40216c81ee . What do you think about lowering the *default* volume instead, and allow players to increase it as they see fit?

**Comment by jafdy** [comment]
Max volume for me is deafening, even on the laptop speakers.

**Comment by CyberShadow** [comment]
Could it be a platform issue? This is on Arch Linux.

**Comment by CyberShadow** [comment]
BTW, by "deafening", do you mean that sounds are played louder than the recorded samples, or at 100% volume? I.e. if you use a sound player to play the sound files directly, are they at the same volume as in the game (with both the game and the player at 100% volume)?

**Comment by Amazinite** [comment]
#2537

**Comment by CyberShadow** [comment]
A thought just occurred to me: the volume slider probably scales the volume linearly (meaning, each sound sample is directly multiplied by the slider's value), but we generally measure volume logarithmically (in decibels, not sound energy). If that's so, then making the slider affect volume logarithmically would fix the silly situation where the default volume setting is at the 12.5% position on the slider.

That doesn't impede #3726, but would enhance it...
