### ISSUE TITLE
Ships (from escort missions) get stuck in a land/depart loop when you leave them behind.

### ISSUE THREAD

**Issue by Cerebrate-Daggoth** [endless-sky/endless-sky#3730]
No idea if it's a mod bug (as i have many installed) or if it's something to do with the base game. What happens exactly is my flagship (which is faster than the escort ships) leaves behind the escort ships. Usually one would just wait til the ships came on their own. What ends up happening is they get stuck on a land/takeoff loop. The only way I've gotten around it is by changing the locations in the save file.

**Comment by tehhowch** [comment]
And? If your goal is to file a bug report, you'll want to provide reproduction instructions. This includes, but is not limited to:

 - game version
 - computer info
 - installed mod list
 - links to custom added content (e.g. a pastebin of any outfits, ships, etc you use that are not in a published mod)
 - a save file demonstrating the issue

**Comment by Cerebrate-Daggoth** [comment]
ah ok. sorry, new to this whole thing. i'll get those things up when work permits it.
