### ISSUE TITLE
"Find Alphas" mission disappears 

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#3740]
Ran into a very strange problem with my checkmate save today when finally going to do the Wanderers missions. After heading to Host and defeating (capturing) the Giftbringer, I was met the standard "You've beaten the carrier, blah blah, time to go back to the Quarg". However, as soon as I land anywhere, be it Avalon, Warfeed, Hai-home, or even going straight to the ringworld on ramscooped fuel, the mission disappears, and I'm not offered the next one. I was able to reproduce it a number of times (i.e. killed the Giftbringer multiple times and same issue. 

![screenshot from 2018-05-16 17-44-37](https://user-images.githubusercontent.com/20472439/40143803-ce791942-5932-11e8-9fb2-ed2d62a49bf0.png)
![screenshot from 2018-05-16 17-47-18](https://user-images.githubusercontent.com/20472439/40143801-ce48cd46-5932-11e8-9366-9744d07fd224.png)
![screenshot from 2018-05-16 17-50-02](https://user-images.githubusercontent.com/20472439/40143799-ce0b480e-5932-11e8-89ff-1e2baefb9eea.png)
![screenshot from 2018-05-16 17-50-27](https://user-images.githubusercontent.com/20472439/40143797-cdcb2be8-5932-11e8-9892-55c1afab36a9.png)

[Rowan Tarabar Check\stage.txt](https://github.com/endless-sky/endless-sky/files/2010855/Rowan.Tarabar.Check.stage.txt)
[Rowan Tarabar Check\stage~Testforbug.txt](https://github.com/endless-sky/endless-sky/files/2010856/Rowan.Tarabar.Check.stage.Testforbug.txt)

There's the saves on either side (before killing Giftbringer and immediately after). Aside from the names of the save I don't believe any of the content in the save has been edited, although I started that one a while ago so can't say for 100%. Vanilla, no plugins. This is 0.9.8, but the save was started (I think) on 0.9.6 a while back.

**Comment by tatami4** [comment]
I found the cause of this. Mission passenger was in a drone (since the flagship didn't have free bunks) and that drone was killed, so the mission failed.

**Comment by tatami4** [comment]
Related: #3361.
This should be closed since it is not a bug.
@Amazinite
