### ISSUE TITLE
More variety of what appears in the news system

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3742]
Currently, the "news" system only shows the faces of people you bump into in the spaceport, but a spaceport has much more to offer than just random people to chat with. One could see billboards, store fronts, fliers, advertisements on the sides of ships, etc., things that could really spice up what one sees in the spaceport. (Whether you see a hologram, a normal television screen, or a billboard with papers on it could change depending on the wealth of the planet you're on.) The advantage to this is that we could model our own images that would appear instead of needing to find a very large variety of faces. Such models could also be reasonably used with multiple news blurbs, as it's more believable to see the same advertisement multiple times on different planets than to see the exact same face. In the end, we would end up needing less faces for the same amount of variety in the spaceport.

Examples:

A quick mock-up I made using a billboard from Eve: Online. Imagine seeing a similar billboard in the spacpeort, but instead the image is of a Bulk Freighter on a landing pad with an advertisement like "Smart captains know cargo space is key. Smart captains choose the Syndicate Bulk Freighter!" (Straight from Syndicate hails, but more could be said.)
The billboard hangs off the side of the news box to represent how the billboard is bigger and more noticeable than the normal faces one sees. This also gives more space to work with instead of being confined to a 120x120 pixel square. And personally, the aesthetic of the billboard hanging off to the left doesn't look that bad to me.
![buc2ckpyrticl04dwtitqw](https://user-images.githubusercontent.com/17688683/40150814-f2fcbad2-5949-11e8-953d-27934528a7b5.png)

A "holoscreen" that @Wrzlprnft made. The screen angle and the image on the screen can be changed. "Breaking news! Strange alien ships seen harassing merchants in the Paradise Planets and Far North! The Navy promises that this will be taken care of by the end of the month."
![billboard](https://user-images.githubusercontent.com/17688683/40150828-02cf7670-594a-11e8-8109-ee8e3bf945cb.png)

**Comment by Darcman99** [comment]
Hey, this looks great! (maybe Dylan can add _Cargo Bargo!_)

**Comment by Amazinite** [comment]
The news blurbs are suppose to be partly humorous, and the seemingly calm news report juxtaposed with the actual severity of the situation may hit on that. And given that the Sestor fleets are only in 11 systems, the player could manage to defeat them all within a month when accounting for travel times. This *is* just an example, though, an example that could be one of many possible news blurbs one could see.

**Comment by jlnxr** [comment]
Hmm, hadn't thought of it that way, could be Republic propoganda, I like it! 

(Only semi related) hopefully there will (eventually) be more content about the human reaction to the Kor Sestor/Alpha invasion in general

**Comment by Wrzlprnft** [comment]
The way the template works, is, that it doesn't matter which image you take, it puts it on that holo-screen. on top, the camera has restraints in place, which keeps it in a fixed distance. so, i quickly whipped together a few other examples.
![billboard](https://user-images.githubusercontent.com/15857993/40270067-6ee04620-5b87-11e8-82f2-da5588011eff.png)
![billboard1](https://user-images.githubusercontent.com/15857993/40270069-70972b5a-5b87-11e8-9bc0-676d9857b1c1.png)
![billboard2](https://user-images.githubusercontent.com/15857993/40270070-72475560-5b87-11e8-972d-f79a11ae4646.png)

quick note: there is transparence to the images, and they are made to be light enough in the rather dark background they'd be set ingame.

**Comment by AlbertNewton** [comment]
I just found this issue. I have been independently working on something very much like this. I've not got much yet, but when I have a good amount of content I'll be sure to upload it here.

**Comment by AlbertNewton** [comment]
OK, turns out I forgot about doing that >:c
Sorry. I found myself stepping away from amateur ES modding for a bit, but I hope to be back now.

**Comment by Amazinite** [comment]
Given that we've removed the portraits from the base game and the variety of the types of news you can see has already increased thanks to contributions, I'll just close this.
