### ISSUE TITLE
Reloading save during conversation duplicates mission action

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3746]
If the player exits the game while in the middle of a conversation within a mission that also gives new log entries alongside the conversation, the game will duplicate the log entry or entries for that mission upon reentering the game and continuing the conversation.

To reproduce: start a new pilot, begin your conversation with James, quit the game before finishing your conversation, reenter the game, finish the conversation, check your log book.

This was after initiating the conversation three times.
![download](https://user-images.githubusercontent.com/17688683/40286892-d975c58c-5c77-11e8-86e6-fea343c552bd.png)
(I also have three of the same entry for the first pirate, Syndicate, and Republic faction logs.)

Credit to @Tadrix for spotting this.

Edit: and as per @comnom's comment, this appears to work with any condition that is changed in an on offer as long as a conversation is included. I assume that this will also work with dialog boxes and in on completes.

**Comment by comnom** [comment]
It's a consequence of the logs being added in the `on offer`. 

Out of suspicion, I checked to see if the same is true of modifying conditions, and it is. (I made a nonsensical condition in the above mission's on offer `+= 1`, and quitting/restarting mid conversation incremented it each time.)

**Comment by tehhowch** [comment]
The reason for the repeats is that the mission's state is only changed by the conversation callback, while the  rest of the actions are performed in the same call to `MissionAction::Do` that created the conversation.
We could try to shoehorn a boolean in that prevents the rest of the MissionAction from occurring, but probably the best approach is to defer the actions until after the callback has completed.

**Comment by tehhowch** [comment]
A third approach may be simpler yet - change when the game saves data: if a conversation or dialog is on top, don't save. This would be more extensible to non-offer actions, and work for dialogs too.

**Comment by Amazinite** [comment]
Checked `on offer`, `on complete`, and for `branch`es and `apply`s in the following files for anything that might cause an issue.

- [x] coalition missions: no such case
- [x] deep missions: no such case (although I think I did try to use the same technique as in #4493 for `conversation "deep: remnant"`, but I was able to write that conversation without needing it since prior missions exist that can be checked during the branches. If the #4493 technique were possible though, the branching in this conversation could probably be simplified.)
- [x] drak missions: no such case
- [ ] FW checkmate:
- [ ] FW epilogue:
- [ ] FW intro:
- [ ] FW middle:
- [ ] FW reconciliation:
- [ ] FW side plots:
- [ ] FW start:
- [x] hai missions: no such case
- [x] intro missions: no such case
- [x] korath missions: no such case
- [x] quarg missions: no such case
- [x] remnant missions: no such case
- [ ] transport missions:
- [ ] wanderer middle:
- [ ] wanderer start:

**Comment by NomadicVolcano** [comment]
Could this be solved by having the game store the UUID and mission action of the mission whose conversation is currently being displayed? Then, upon loading, you make sure you don't apply any mission actions for that mission.

PR #5070 adds UUIDs, plus other things. The UUIDs could be pulled out to another PR.

**Comment by NomadicVolcano** [comment]
Actually, you need UUIDs for conversations as well, and the index of the current node being processed.

It's easy to add UUIDs to anything, so that's not a problem.

**Comment by NomadicVolcano** [comment]
Draft PR #5082 fixes this problem, but it needs a lot more testing.

Every possible on-planet mission target has to be tested with conversations and dialogs. I've only tested "on accept" and "on offer"

**Comment by NomadicVolcano** [comment]
Please test PR #5082 and see if it fixes your problem. I've tested it thoroughly, and I have not seen mission actions run twice. It'll save and load mid-conversation, restoring to the point you were at in the conversation, so conversation "apply" blocks are not run twice either.

**Comment by Amazinite** [comment]
How about any time the player hits a mission action with a conversation, we branch off of their save file (PlayerInfo). Any changes that are applied by the mission action and conversation are applied to this branch. Should the player quit while the conversation is active, then the original save file is what becomes saved such that no changes from the mission action and conversation actually get saved. While the player is in the conversation, the branched save file is used so that conversations can still apply and then use conditions within the same conversation. Should the player finish the conversation, then the branch with all the changes is used and the old save is tossed out.

Alternatively, instead of having a duplicated PlayerInfo, we just have some sort of object that holds the changes applied to the player by the mission action and conversation. If the player quits during the conversation, the player is saved as normal, but all the changes are tossed out. Should the conversation have a branch, then the PlayerInfo PLUS the changes is checked (but the changes are not actually yet applied to the player). Once the conversation is over, the tracked changes are actually applied to the player.

**Comment by tehhowch** [comment]
> Alternatively, instead of having a duplicated PlayerInfo, we just have some sort of object that holds the changes applied to the player by the mission action and conversation. If the player quits during the conversation, the player is saved as normal, but all the changes are tossed out. Should the conversation have a branch, then the PlayerInfo PLUS the changes is checked (but the changes are not actually yet applied to the player). Once the conversation is over, the tracked changes are actually applied to the player.

This is the approach i recommended here: https://github.com/endless-sky/endless-sky/pull/5082#issuecomment-653083669
Implementing it requires the above refactoring to defer applying the  missionaction until after the conversation resolves.

> (This may just be "don't save during conversations" with extra steps, though. Whatever the case, I'd prefer an approach that doesn't make currently possible things impossible, such as the previously mentioned allowing missions to change a condition then immediately use it in the conversation.)

It is likely that we can support certain auto conditions (like determining that a particular mission is being offered) within an action's conversation, but I don't think it is consistent to allow parts of a missionaction to be completed and parts deferred.
