### ISSUE TITLE
No Creating Planets/Systems Page in the Wiki

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#3751]
...or not one that I can find at least.

It's a relatively minor set of data to learn about but it is a missing piece from a fairly comprehensive guide.

**Comment by gunqqer** [comment]
The wiki really need an overhaul in general, most of the info is a tad old

**Comment by MCOfficer** [comment]
just gonna throw in the possibility of opening the wiki to contributors.

**Comment by endless-sky** [comment]
Unfortunately, there's no way to make PRs to a GitHub wiki, or to give someone access to modify the wiki without also giving them full access to modify the main repository.

**Comment by tehhowch** [comment]
I think the workaround is to make a wiki repo, or publish the wiki via GitHub pages from this one. I'd vote for a separate repo, as it seems though it would promote better organization: the Contributing, Issue/PR templates, Readme, etc. can be tailored for the repo's purpose (and people can choose to avoid being notified about 1 kind of thing while focusing on the other).

**Comment by KiLEdEnNis** [comment]
or one could make an issue where they say like "I wrote stuff for this wiki page", and you copy-paste it in said wiki page
not ideal but it works

**Comment by OrdoFlammae** [comment]
Maybe we could begin to move the wiki into the endless-sky website itself. That would allow us to make commits to the wiki, and it should be easy enough to manage.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/wiki/MapData
