### ISSUE TITLE
Escorts refueling for no reason

### ISSUE THREAD

**Issue by SpellingSword** [endless-sky/endless-sky#3756]
Sometimes(annoyingly often), my escorts decide to refuel despite having more than enough fuel to make a jump. As far as I can tell, it only happens if I leave them behind, IT.E. when I jump ahead of my fleet. I am not jumping to an empty or hostile system. 

If it helps, this is happening with a fleet of 7 leviathans, all equipped with cataclysmic ramscoops(making this particularly annoying).

**Comment by KiLEdEnNis** [comment]
ships refuel when they still have some fuel left if the next system(s?) don't have any planets to refuel
is that what's happening here?

**Comment by SpellingSword** [comment]
> I am not jumping to an empty or hostile system.

.........

No, the next system may be the end destination and they STILL sometimes do it.

**Comment by Amazinite** [comment]
Do your ships have both hyperdrives and jump drives installed? If yes, then this may be a duplicate of #1238.

**Comment by SpellingSword** [comment]
Nope, just scram drives.

**Comment by endless-sky** [comment]
#3123 may have fixed this.

**Comment by FatmanUK** [comment]
I have this issue. Non-Steam (it's from my distro's main repo), default game, no mods, version 0.9.8. I have snapshots if they would be useful.

**Comment by jafdy** [comment]
If you are using the 0.9.8 release then #3123 won't be included yet.

**Comment by FatmanUK** [comment]
Thanks jafdy. Good to know.

**Comment by tehhowch** [comment]
Please reproduce with the latest official release

**Comment by IsocratesGrey** [comment]
Reviewed this on 0.10.2, the bug no longer happens. Recommend we close this as solved. @Amazinite
