### ISSUE TITLE
Inconsistent rules on fighters

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#3764]
Related: #950, #3706

It seems that fighters without a carrier are allowed, but only if they're not in the same system as the flagship. To reproduce:

1. Obtain more fighters than your ships can carry
2. Try departing your current planet; you will be prompted to sell the fighters. Don't sell them.
3. Park the fighters and jump to another system, then land on one of its planets.
4. Unpark the fighters and depart. The fighters will be kicking about in the system where you left them.

The problem being the inconsistency between cases 2 and 4 — the location of the flagship shouldn't affect whether you're allowed to have "orphan" fighters or not! So I'd consider this issue solved if either

1. You're allowed to leave a planet with as many fighters as you want, and the only issue you'll have is transporting them from system to system (in-universe, fighters have the antigravity field stuff or whatever that's required to land on and take off from planets). This would be a simpler solution, and could be worked around with creative combinations of deployment/recall and hyperspace jumps ("ferry" batches of fighters from system to system). This is practically already the case, with the exception of fighters that are in the same system as the flagship.
2. You can't have more fighters than fighter bays (in-universe, fighters can't land or take off independently). This would be a little more complex, since (unless someone can think of a way around this?) it would require distinguishing between ships that are floating about in a system and ships that have landed on a planet — it doesn't make sense to be able to take a fighter to the local outfitter if it's floating through space and can't land on its own!

As you may be able to tell, I favour solution 1. But I'd be glad to hear any input!

**Comment by jlnxr** [comment]
I agree strongly with this. The Wanderers literally have a drone that exists without a carrier in various systems to defend them. But if a player wanted to do the same to another system? Not allowed, you can't take off unless you can carry them, at least not from the same system. 

I'd also like to be able to fly a fighter, for kicks, (boxwing with a hyperdrive anyone?) But currently you can't take off in a fighter yourself, even if you're installed a hyperdrive in it.

**Comment by KiLEdEnNis** [comment]
there's not really a reason for those rules to exist at all, and they're even a bit unrealistic; if a ship has a hyperdrive and fuel, it can hyperspace, so why not for carried ships

**Comment by Zitchas** [comment]
I also favour option 1, but it should also applies to drones.

This also allows greater flexibility, since, after all, this is a game that revolves around outfitting ships - it is entirely possible someone sticks a hyperdrive and fuel tank on a fighter or drone; and there is no reason why this shouldn't be possible, either. 

So the solution is basically "remove the check that forces people to sell fighters/drones when they leave the planet." A warning would be fine, but they shouldn't be forced.
