### ISSUE TITLE
Make important hail messages (e.g. mission failed) more distinct from random hails

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#3769]
https://steamcommunity.com/app/404410/discussions/0/1697175413678039614/

Perhaps place such hails in a separate location or give them bigger text so that they're more noticeable than the randomized hails that don't actually give the player any majorly important info. "You failed a mission" should be more noticeable than "My cargo hold smells!" and the like.

**Comment by tehhowch** [comment]
Your search-fu is rusty: https://github.com/endless-sky/endless-sky/issues/3361

**Comment by Amazinite** [comment]
I tend not to even search at this point because I can recall most of the topics that have been discussed in issues, but I guess I'm not perfect. Thanks. :)
