### ISSUE TITLE
I want to know why in less than a second I get killed.

### ISSUE THREAD

**Issue by FireWolf74** [endless-sky/endless-sky#3770]
I want to know why in less than a second I get killed.But with the same number of force it takes forever to kill ships.  
I think I know why.  No matter what it is hard for non coders to complete missions.

https://drive.google.com/open?id=12fyZQBpVxzO21rA4JIRLzpH8uQEMj6Si

**Comment by MCOfficer** [comment]
the video seems to be broken. ffmpeg:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001cb099d2520] moov atom not found
Downloads\Peek 2018-06-10 20-15.mp4: Invalid data found when processing input
```

**Comment by Janaszar** [comment]
Seeing as the link/video doesn't work, would you mind writing out which fight or setup you are having trouble with?

**Comment by KiLEdEnNis** [comment]
> I want to know why in less than a second I get killed.

I have seen this issue before; usually one dies in less than a second if the enemies' DPS exceeds your ship health
if it's not in 1 second but still very fast, consider that either the enemy does a lot of damage or your ship lacks the ability to tank a lot

happy to help

**Comment by jafdy** [comment]
Most likely you have picked a particularly untanky ship so you die a lot quicker than another ship of your size. But as everyone else has stated, you haven't given us much to work with.

**Comment by endless-sky** [comment]
It's quite possible that you're just really bad at flying your ship (or that you've got a ship that's too slow to dodge enemies). In any case, this is not a bug, so it would be better suited to the forum than to the bug tracker.
