### ISSUE TITLE
Capturing Bloodsea- some Free Worlds plot inconsistantices. 

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#3772]
While this game is well polished in general, there's a few rough points in some of the less-traveled routes. One is dominating Bloodsea for Tomek vs for the Council. 

In "FW Pirates 3.1" You can ignore the Senate's orders and attack Bloodsea instead of going to Thule, the Senate apparently having authority here. If you succeed in completing the mission, Tomek is placed under house arrest and you are sent to the Senate, where you are practically laughed at for trying to occupy a world. And you are suspended and loss salary for a whole before getting another mission for no follow up on your disobedience. 

In "FW Bloodsea 1.2" and "FW Bloodsea 1.2A" you can instead chose, without consulting the Senate, to do _the exact same thing_ and yet... this time it works. You can now occupy Bloodsea.

This is not logically possible. To make matters worse, a player who might follow Tomek into attacking Bloodsea in the beginning is likely to chose occupying them later on vs the spaceport based on playing style/brutuality. 

Suggestions: 

-Remove the option to occupy Bloodsea later on 
Or

-Have an explaination for why the Free Worlds will now occupy the planet, such as, before Poisonwood they opposed threatening obital bombardment, but they are now no longer above that.

**Comment by jafdy** [comment]
At that point it is seen as "The only option", it also doesn't work so well, rather than occupying it you are simply not giving any other option but to stop with pirates. In the end bloodsea goes independent.

**Comment by jafdy** [comment]
At that point it is seen as "The only option", it also doesn't work so well, rather than occupying it you are simply not giving any other option but to stop with pirates. In the end bloodsea goes independent.

**Comment by Amazinite** [comment]
From FW Bloodsea 1
> "The Senate has authorized a diplomatic mission to Bloodsea," he says. "It's the smallest of the pirate worlds, and we're going to see what we need to offer them to get them to join the Free Worlds. The official settlements there only amount to a few thousand people, so it shouldn't be too hard to convince them that joining us is better than resisting us."
>
> (Player choice) "Wait, didn't things go south rather quickly the last time we attempted this?"
>
> Alondo grins. "Yes, but the **Free Worlds is in a much stronger position now,** and the pirate worlds know it's only a matter of time before they are forced to become civilized. And, the incident on Poisonwood proved that we can't afford to fight a war on two fronts. We need to eliminate the pirate threat, and a diplomatic solution with them is the only sort that will last. So, let's get going!"

The difference between FW Pirates 3.1 and FW Bloodsea 1.2 is that the objective of the former was to eventually subjugate Greenrock (a planet that the FW never actually manages to switch to independent or FW throughout the entire campaign), while in the latter situation it's only to subjugate Bloodsea (the weakest pirate world). There's also the fact that in the former case you go straight to attacking before trying diplomacy, while in the latter case you have already completed the diplomatic mission approved by the Senate by speaking with the people of Bloodsea. At that point, as a member of the Council, you have the say on whether or not to agree to the deal that they give you, and since the rest of the Council seems like they'd back you up as opposed to one Council member going rogue (Tomek), it's something that the Senate could be fine with,

From FW Bloodsea 1.1
> You thank them and return to your ship. Alondo asks, "What do you think?"
>
> (Player choice) "They're asking a lot. Why don't we just invade them?"
>
> "That's certainly the simpler option," he says, "especially because I can almost guarantee that when we show up on their doorstep with everything they asked for, some local warlord will attack our ships, steal our supplies, enslave our workers, and build himself a nice cozy island fortress."
>
> "So, we attack them?" you ask.
>
> "You're on council now," he says. "I'll leave it up to you. Option one is, we bring them the supplies and workers, in merchant ships, but use very heavily armed merchant ships in case they double cross us. Option two is, we go to Dancer and see if JJ can lend us an invasion fleet."

**Comment by Amazinite** [comment]
Surprised this issue never got labeled.
I would've included this in #4671 had it been labeled, but the other day I remembered the issue mentioned here, created a branch to fix it, then found this issue after finishing the branch
#4694 should address this now.

**Comment by Amazinite** [comment]
#4694 has been merged, so this should be addressed. You are now given an explanation as to why it's permissible to invade Bloodsea now when it wasn't before.
