### ISSUE TITLE
Wanderer ramscoop in an Alpha Carrier?

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#3773]
While capping the Giftbringer with my Bactrian, I noticed immediately that it has a Wanderer ramscoop, which makes me wonder: how the heck did they get that ramscoop without a license? The Wanderers didn't met the Alphas physically yet.

**Comment by lheckemann** [comment]
They've been interacting with the Unfettered Hai, who in turn have been interacting with (fighting) the Wanderers, and presumably were able at some point to capture some of their outfits as well.

**Comment by temtemy** [comment]
Hmm, makes sense. If that's the case, some of the outfits should be in the Unfettered outfitters too.

**Comment by lheckemann** [comment]
I disagree. From a metagame perspective it removes the incentive to help the Wanderers. Plot-wise this can be justified by capturing a Wanderer ship being a fairly rare occurrence so the Unfettered would keep them to themselves jealously. Or share them with very very close allies.

**Comment by temtemy** [comment]
That's why I said some. They can show but restrict selling them to others, by a license.

**Comment by lheckemann** [comment]
This doesn't fit with existing mechanics (licences are per outfit, not per outfitter; there's no mechanism AFAIK to have a specific amount of outfits available at an outfitter either), and doesn't actually make the game any better. -1 from me.

**Comment by Wrzlprnft** [comment]
In general story overrides gameplay rules.
Given that you wonder why they have it probably is proof that it worked: the power/connections level of the alphas are not entirely clear.

Given that the player probably will not be able to buy wanderer stuff, so i'd not tease them with showing it in the outfitter

**Comment by KiLEdEnNis** [comment]
> Hmm, makes sense. If that's the case, some of the outfits should be in the Unfettered outfitters too.

selling that in outfitters would mean available for basically anyone (with a license), while the Wanderer tech is kept secret, to be used only by, for example, the Alphas
just like how the Syndicate doesn't sell their alien (Korath) tech (most mentioned only, but also includes jump drives & a cloaking device) in outfitters

there's enough reasons not to sell the enemies' tech in a war, so you can... close this issue or something since your question has been answered

**Comment by Amazinite** [comment]
The ES Github is for feature requests and bug reports. Discussions like this should be happening on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky). Please close this issue.
