### ISSUE TITLE
bug, Laptop build, sdl2 touchpad error on start

### ISSUE THREAD

**Issue by AleksDark** [endless-sky/endless-sky#3778]
When building this game on Debian laptop, the scons build succeeds, but starting the game fails with error message: "Unable to find the resource directories! (SDL message: "Unknown touch device")
".

The deb repo version works nicely.

**Comment by temtemy** [comment]
Have you configured endless-sky to use the game's resources (the data and images folders)? The game resources are found in /usr/share/games/endless-sky (atleast in my build). Try starting the game with ``endless-sky -r /usr/share/games/endless-sky)``.

**Comment by MCOfficer** [comment]
"Unkown touch device" was fixed in libSDL v2.0.4:
https://hg.libsdl.org/SDL/rev/7fc4a8be47a8

**Comment by endless-sky** [comment]
I'm closing this because it seems to be an SDL issue, not an issue with the game itself.
