### ISSUE TITLE
Add larger icons (up to 1024x1024) for Mac OS X

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#378]
I think this complaint is in regards to lack of icons at all the required resolutions, but it appears every time Endless Sky is built. Just thought I'd let everyone know, it doesn't seem to break anything.

![image](https://cloud.githubusercontent.com/assets/4998058/11608724/80e61ddc-9b3f-11e5-823d-473eeb750ddd.png)

**Comment by endless-sky** [comment]
Yes, OS X wants you to provide a 1024x1024 pixel icon for every program, and I just think that's excessive. :)

**Comment by guillochon** [comment]
Perhaps, but it is the official OS X guideline for icon design. Also just looks better on a Retina display. If a 1024x1024 image already exists I don't see the harm in including it.

**Comment by dplepage** [comment]
FWIW, OS X does let you enlarge finder icons pretty far, and at full size it's clear which programs packed 1024x1024 icons and which didn't.

![icons](https://cloud.githubusercontent.com/assets/107468/11609185/aa9179f2-9b4d-11e5-961a-b04f0cd0fc93.jpg)

**Comment by endless-sky** [comment]
I haven't done this yet because I don't have anything larger than 256x256 graphics for the existing icon, so it would require redoing the icon from scratch. It's on my to-do list, but it's low priority.

**Comment by guillochon** [comment]
Might be good to add a low-priority label for things like these.

**Comment by endless-sky** [comment]
This is addressed (finally) in commit b025063.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
