### ISSUE TITLE
"dogging"

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#3780]
From the mission "FW Rand 1":
``When you land on Dancer, Freya has just received some exciting news. "It turns out taking out Bartlett had some unexpected side effects," she says. "Bartlett has been dogging the systems on the northwestern fringe of the Dirt Belt for years, and had a lot of enemies.``

I just noticed that word right now. I thought "dogging" is a misspelling of "dodging", but after researching about "dogging", I understood now what that word means. I think it would be better if that word be changed into "following closely" or similar, since not all players are native English speakers (and I am one of those players). And probably to keep this game "family-friendly" (a minor might be surprised when they saw what that word means, and I don't think you would want a British parent would ban their child from playing this game because of that word).

**Comment by Amazinite** [comment]
The best replacement would probably be harassing. 
And as for those wondering about the "family-friendly" part, apparently dogging is British slang for having sex in public. Exhibitionism, one could say.

**Comment by MCOfficer** [comment]
+1 because i really had no idea what it meant.

**Comment by jafdy** [comment]
If it is British slang then it is a rarer dialect. That is not one I have ever come across, my understanding was that it meant something along the lines of harassing.

**Comment by jostephd** [comment]
https://en.wiktionary.org/wiki/dog#Verb gives both the author-intended meaning (2) and the non-family-friendly meaning (4). https://www.thefreedictionary.com/dog gives meanings such as "haunt", "harry", and "plauge".

It seems the family-friendly/intended sense is the established one.

**Comment by Nescio0** [comment]
There is a difference between the *verb* to dog, dogging, dogged (follow (someone) closely and persistently) and the mass *noun* dogging (the practice of watching or engaging in exhibitionist sexual activity in a public place.) Both from the context and the grammar it's clear the former is used here, not the latter, so there is no need to change it.

**Comment by MessyMix** [comment]
I too think there isn't really that much of a need to change it, although there's really no harm done in "harassing".

**Comment by Lineth** [comment]
Eh, I prefer rarer/stranger word choices if it's dialogue. Characters shouldn't always speak like a game tutorial. The meaning in not hard at all to guess from context in this scenario anyway.

**Comment by Vilhelm16** [comment]
I don’t have an opinion on whether it should be changed or not but if you
want to change it some of your options include:

-tormenting
-assailing
-ravaging
-beleaguering
-provoking
-raiding
-hassling

Take your pick. We could use lots of different words here.
