### ISSUE TITLE
Korath and Hai rifle assets missing

### ISSUE THREAD

**Issue by Brick63** [endless-sky/endless-sky#3784]
ive noticed that the assets for the Korath and Hai rifles are missing from the drive, and was wondering if i needed to post them again?

Assets:
[rifle assets.zip](https://github.com/endless-sky/endless-sky/files/2108547/rifle.assets.zip)

**Comment by KiLEdEnNis** [comment]
why not post them in case they are indeed missing? it saves the time between someone confirming this/asking for them & you posting them

**Comment by Brick63** [comment]
added them

**Comment by endless-sky** [comment]
I've uploaded them to the drive.
