### ISSUE TITLE
Feature Request: More Detailed Radar

### ISSUE THREAD

**Issue by Cerebrate-Daggoth** [endless-sky/endless-sky#3793]
For the radar, I was thinking make disabled ships on the radar white or something. Something to distinguish them from planets/stars. Perhaps different colors for friendlies or a color mixer for radar colors? (sorry if there needs to be more info or something or other)

**Comment by tehhowch** [comment]
The radar already shows disabled ships - it shows them as "inactive" (dull grey) because they sure aren't about to come fight you (or help you). White is used as a special color - for example, special mission targets will blink between white and their default color, which may be blue (friendly), yellow (hostile), orange (hostile and targeting you), green (an escort of yours (owned or from a mission). These colors are found in the `data/interfaces` file.

**Comment by Zitchas** [comment]
Generally speaking the colours are good, but personally I find it hard to differentiate between disabled ships and planets that cannot be visited.

**Comment by Cerebrate-Daggoth** [comment]
true to both, but yeah, i find it hard to distinguish disabled ships from
planets/stars. perhaps faded colors for disabled ships?

**Comment by tehhowch** [comment]
Planets are drawn as a ring with ring width of 1, while ships are drawn filled-in:
https://github.com/endless-sky/endless-sky/blob/ffd15a7453c7cc48b5c70ed7a8bbd3beb4f7e1cb/source/Engine.cpp#L1828-L1834
vs
https://github.com/endless-sky/endless-sky/blob/ffd15a7453c7cc48b5c70ed7a8bbd3beb4f7e1cb/source/Engine.cpp#L1860-L1864

How small is your radar vs your screen resolution? Consider increasing the UI zoom (and installing the High-DPI plugin to maintain quality) to help distinguish between the various radar objects.

One simple change could be to slow-blink disabled ships with their original status. Blending the disabled and other colors would require a larger change (but isn't infeasible). Note that there is no requirement that the `"radar inactive"` color is grey, so if we implement blending we could potentially ruin certain user-defined color schemes.

Another change could be to change the scale factor used to represent stellar objects in-system.

**Comment by Cerebrate-Daggoth** [comment]
my screen resolution is 1280 by 1024, but i can't adjust the ui zoom. my
screen's brightness is also weird,(the brights are too bright and the darks
are too dark.) maybe that might be a contributing factor? not really sure
tho, i'm not a graphics person.

**Comment by endless-sky** [comment]
Have you tried adjusting your screen's brightness and contrast? This sounds like an issue with your monitor, not with the game itself.

**Comment by Cerebrate-Daggoth** [comment]
many times but to no avail sadly

**Comment by Cerebrate-Daggoth** [comment]
since the issue appears to be just my monitor, perhaps a custom ui zoom for
each chunk of the HUD? varying between 200% to none at all maybe? then you
could have a button to reset everything to 100%/ standard view.

On Wed, Jul 4, 2018 at 5:25 PM, Dennis van Anrooij <notifications@github.com

**Comment by Pointedstick** [comment]
That doesn't seem like a very elegant solution, to be honest. It's not clear that there's a problem in Endless Sky here at all. Adjusting the scale for the whole game seems sufficient, and if the colors aren't visible enough on your screen, you might try calibrating it. A lot of screens come with a really terrible out-of-the-box color calibration.
