### ISSUE TITLE
Bay converters?

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#3795]
I'm not shure if this has been brought up before, but an outfit that could convert fighter bays to drone bays (And possibly vice versa) would make a lot of sense. From what I can gather, it could take an available fighter bay, get it's x, y coordinates and then change it to a drone bay. These should probably give off heat and require energy, but In my opinion should not take much outfit space because the bay it already there it just needs to be repurposed to hold drones (or fighters if that wouldn't be too busted). Am I missing something as to why these wouldn't work or could these legitimately work in the game?

**Comment by Bladewood** [comment]
Fighters -> drones, maybe, but definitely not drones -> fighters. Note that fighters tend to have twice the firepower of drones, so that would make carrier ships with such a capacity far too powerful (relative to other carriers).

**Comment by KiLEdEnNis** [comment]
doing that would make various carriers way less unique (they'd just be generic carriers, imagine being able to change outfit space to weapon capacity etc, this would also make ships way less unique)
adding that drone bays can generally be smaller, and require no pilot, so where one would place a drone or fighter bay varies
aslo what Bladewood said

**Comment by KyroFirehammer** [comment]
I thought drone to fighter might be broken, but I thought they would be worth the mention. I'm not shure what you were trying to reference with the boxwing origin and the other one dealing with adding bays. We have already seen from the Kor Sestor that drones can be held externally, it would, in my opinion, increase the versatility and viability of carriers, as someone in theory could use drones which, while slightly weaker than fighters, cut down on crew costs. This could also open up the ability for some civilian-grade human drones, and Free worlds/ syndacate drones in the future. In the current code all that eould need to be done is to have the outfit remove  the fighter space and replace it with a drone space in the same x, y coordinates

**Comment by KiLEdEnNis** [comment]
> We have already seen from the Kor Sestor that drones can be held externally

don't compare alien tech w/ human tech?

> it would, in my opinion, increase the versatility and viability of carriers

it would indeed increase the versatility to the point every carrier is basically the same as all others, it's so fun when you have 5 ship hulls that have nothing to differentiate themselves from the rest whatsoever
and viability has nothing to do with this

basically, we don't want to make every ship 100% customizable, restrictions keep ships unique, so you choose what you want when buying a ship
do you want this or do you want that, not just buy whatever your heart desires & outfit it until you have the same

close this issue tyvm

**Comment by Pointedstick** [comment]
Seems unlikely, sorry.

**Comment by petervdmeer** [comment]
If we like to have this feature, then we could look into the "Boxwing route". The Boxwing is a fighter that effectively transforms a fighter-bay into an (auxilary) storage bay.

The current data-files syntax allows content-creators to create a fighter with a drone-bay. So if you create a fighter that is not much more than a minimal ship with a drone-bay, then that fighter effectively transforms a fighter bay into a drone bay.

I don't expect the current version of the code to work properly with multiple layers of docking though, but if it indeed doesn't work then we might just want to fix that.
