### ISSUE TITLE
Missing Hire/Fire Crew buttons

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#3796]
Somehow my hire crew and fire crew buttons are missing. Has anyone had a similar problem and been able to repair this, it's happening on all of my saves and it persisted even after reopening the game. Plz help!

I have no plugins or mods installed

**Comment by endless-sky** [comment]
Can you post a screenshot?

**Comment by Wrzlprnft** [comment]
fullscreen or windowed?

**Comment by MCOfficer** [comment]
can you try with a fresh install? i bet that solves the issue.

**Comment by Amazinite** [comment]
>can you try with a fresh install? i bet that solves the issue.

Sounds to me like his screen res is just too low. It may be that he increased the UI zoom but doesn't have a monitor big enough to handle the increase.

**Comment by jafdy** [comment]
If that were the case then some other buttons would be missing as well. Although we can't really tell until we have a screen shot.

**Comment by KyroFirehammer** [comment]
![screenshot for es](https://user-images.githubusercontent.com/30506535/41801380-cedcb0f4-763f-11e8-8848-5fd9eda663ee.PNG) 

I also have a bit of footage with it in shown in it if you guys would like to see that as well

**Comment by Bladewood** [comment]
It's definitely the resolution. Either you have a tiny screen, or your window is just too small to see everything.

**Comment by KyroFirehammer** [comment]
Fixed it! It was my OBS causing a zoom in and when I reset it it reframed itself 

Thanks for the help!
