### ISSUE TITLE
Occupy Zeta Aquilae Will Not Complete

### ISSUE THREAD

**Issue by CaptainKraft** [endless-sky/endless-sky#3797]
I flew to Zeta Aquilae, my escort started fighting, I landed on Rand, and the mission didn't complete.

I went back into space, and all the enemy ships were gone aside from a few disable ships. I landed again, and nothing happened. I took off, destroyed the disabled ships, then landed again.

Nothing I do seems to affect the mission, and there is nothing in the Logbook.

Here is the save file: 
[Deekz Kraft.txt](https://github.com/endless-sky/endless-sky/files/2129595/Deekz.Kraft.txt)

Edit: Loading a previous save, yet still after the bug showed up, I took off and there were Republic ships that I destroyed. Then, when I landed, the mission completed.

**Comment by jafdy** [comment]
It because of the keyword used in the mission definition. 
The way to fix this would be to add a new keyword that requires ships to be disabled or destroyed.

**Comment by temtemy** [comment]
@CaptainKraft The `evade` keyword means the npc should be out of the system, disabled, destroyed, or captured. I can't understand why this happens to you. Maybe you can tell us what version are you using? (0.9.8, Steam, master branch)

**Comment by Amazinite** [comment]
All FW missions now have on visit dialogs if they didn't before, so you should now get a message if you somehow missed one of the ships. And given the description of reloading the save and then there are more ships, I imagine this might have been the issue where fighters that were still docked when the carrier was destroyed weren't considered dead.
