### ISSUE TITLE
Ramscoops not working?

### ISSUE THREAD

**Issue by DireHo** [endless-sky/endless-sky#3798]
Tried the regular, catalytic and wanderer ramscoops, none seem to be working.
Attaching save file for good measure

[DyingCrow x.txt](https://github.com/endless-sky/endless-sky/files/2131871/DyingCrow.x.txt)

**Comment by temtemy** [comment]
What version are you using? Steam? 0.9.8? (if so, self-build or packaged?) Master branch?

**Comment by KiLEdEnNis** [comment]
stay near the center star of a system, if it doesn't work at all; did you edit your data?

**Comment by temtemy** [comment]
Yeah, try staying near the star. You can also see if the ramscoop works if there's a difference in fuel via Player Info. Ramscoops should still work even when very far from the system's star, since the minimum efficiency of ramscoops is 25% (the efficiency decreases as you go farther from the star, until 25%).

Maybe you have installed a mod, screwing up the ramscoops. Or directly edited the data as KiLEd said

**Comment by MCOfficer** [comment]
install a flamethrower, it's ammo count reflects your fuel gauge, so you can precisely track when you loose/gain fuel. also try 3x speed (capslock), ramscoops are not that fast

**Comment by KiLEdEnNis** [comment]
Catalytics are reasonably fast, shouldn't take more than 10s for a fuel bar at decent distance from the star

something else, did you by any chance create a ship with a large amount of fuel, or install a large amount of fuel pods? maybe you don't see the ramscoop working since it's just a fraction of your fuel bar?

**Comment by DireHo** [comment]
Sorry for late reply, i was using master branch (in a folder separate from the steam install, but with same save). I did some save file editing at some point, to correct some... silly mistakes. But everything was working fine with the steam install. 
I actually noticed this with wanderer ramscoops, on a ship with 1,000 fuel. then checked on the others and none seemed to be working. 
Ill give it another try. Judging by the feedback here, maybe i messed up something when i set up the master branch. First time :)

**Comment by DireHo** [comment]
Re-downloaded everything fresh (following instructions in https://steamcommunity.com/app/404410/discussions/0/1700542332319963311/), loaded up save, ramscoops still dont work, at least not with current save. Ill try starting a new game, and see what happens. Maybe theres some save compatibility issue with steam version?

**Comment by MCOfficer** [comment]
there may be compatibility issues, but nothing of that should have any effect on ramscoops

**Comment by DireHo** [comment]
I found out what the issue is. The animated stars plugin, which works with the steam version. I guess ramscoops dont like custom sprites :(

**Comment by gunqqer** [comment]
Now that the cause of the issue has been found and corrected (In this case, the problem was on the user's end) please close this issue

**Comment by MCOfficer** [comment]
yep, that plugins is broken since some time. unfortunately, we don't have a central plugin repository yet (only codedraken's, which hasn't been updated for years). somewhat related, #707

**Comment by Amazinite** [comment]
The animated stars plugin is from before the addition of https://github.com/endless-sky/endless-sky/commit/317b495a7217784bb490637564e1ff57e22c0193. You should be able to fix it by adding the animated stars to your [stars.txt](https://github.com/endless-sky/endless-sky/blob/master/data/stars.txt). I forget if the folder location is different (i.e. you'd rename the `"star/"` portion of the file) or if the naming is different (i.e. change what's after the `/`). Either way, please close this issue, as this repository is not intended for discussing issues with a specific plugin.

**Comment by DireHo** [comment]
"You should be able to fix it by adding the animated stars to your stars.txt. "
Added as suggested and saved in the plugin data folder, that appears to have done the trick :) Tks, i wanted to give Enclave a go, and it uses animated stars.
