### ISSUE TITLE
Possibility of including an already compiled .exe file for windows users who can't compile 

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#380]
I want to try the new things as soon as they come out, and compiling just won't work, even after following all the steps

**Comment by endless-sky** [comment]
I do all my development on Linux box - the only time I do Windows builds are when I'm doing an official release. And anyways, it would be way too time consuming to post binaries for every OS every time a change gets made on GitHub.

**Comment by sanjayatio** [comment]
Installation steps (for windows - please refer to readme-developer.txt):
- get the source codes 
- install mingw-w64
- install code::block
   - set the compiler/linker accordingly -- Settings - Compiler
      - I merely changed a bit under Toolchain executables (mandatory for me), Compiler settings and Search directories.
- download the development libraries (headers, static libs and dlls)
- open EndlessSky.cbp, find the linker nodes and adjust all paths accordingly.
   - there are 2 nodes, one for Win32, the other for 64bit
- change the build target (Debug / Release / Win32)
- build --> will only give you an exe.
- copy the whole working game into another folder
- overwrite the exe with your new one
- overwrite the contents (data, images, sounds folders) from source
