### ISSUE TITLE
Uninhabited planets can fine you for illegal outfits

### ISSUE THREAD

**Issue by jonnybot0** [endless-sky/endless-sky#3807]
During the Remnant Gascraft mission, it's possible for the uninhabited gas giants to fine you if you have an escort possessing illegal outfits.
<img width="1552" alt="screen shot 2018-06-30 at 4 37 00 pm" src="https://user-images.githubusercontent.com/3723592/42129248-3b942434-7c85-11e8-9c43-608a59611c28.png">

**Comment by Bladewood** [comment]
Relevant: #2059.

**Comment by Amazinite** [comment]
Instead of continually fixing this every time MZ adds a new uninhabited planet and doesn’t give it `security 0` (e.g. #2821), perhaps uninhabited planets should be changed in the code to inherently be unable to fine the player.
