### ISSUE TITLE
Hephaestus is a Dirt Belt world?

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#3809]
![syndicate_dirt_belt](https://user-images.githubusercontent.com/32586497/42131395-d5c1ced6-7d33-11e8-8090-8fbc46466dc7.png)

**Comment by KiLEdEnNis** [comment]
maybe that Syndicate guy also feels bad for the Free Worlds
I don't really see a problem tbh, besides maybe it being unintentional

**Comment by temtemy** [comment]
Well it seems that the `clearance` tag always applies to the destination, and "fixing" it will not be trivial probably. So I'm gonna close this issue. I opened this issue just in case someone wonders.
