### ISSUE TITLE
Some attributes are not described on the CreatingOutfits page

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3811]
Or maybe you'd want them on CreatingShips, too, I don't know.

**Comment by endless-sky** [comment]
Added to the outfits page.

**Comment by Bladewood** [comment]
I don't think I find this solution satisfying, because the resistances are all spread out, unlike the actual damages, which are all grouped together at the very end of the article.

`safe` and `phasing` are also missing from the wiki.
Please mention any others if you find that they are missing.

**Comment by tehhowch** [comment]
I think I updated that page to be current, at least as of the start of this week. @Bladewood feel free to close if you agree.

**Comment by Pointedstick** [comment]
Looks good to me now, thanks!
