### ISSUE TITLE
"The Navy is here to shield and serve you."

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#3815]
![navy star queen](https://user-images.githubusercontent.com/32586497/42212624-3a70720e-7ee9-11e8-8f44-6f1f81b0c9ac.png)

**Comment by temtemy** [comment]
I'm sure those ambassadors represent the Parliament, not the Navy

**Comment by KiLEdEnNis** [comment]
making a special new fleet type just to take those few hails out isn't worth the trouble
adding that it says "The Navy is here to shield and serve you.", it doesn't say that ship itself is the Navy or if its also there to do that

**Comment by temtemy** [comment]
Okay, that makes sense :)
