### ISSUE TITLE
Can't get my fleet back after parking it

### ISSUE THREAD

**Issue by Afoklala** [endless-sky/endless-sky#3817]
Hi,
I'm doing the science mission for the Remnants. In order to land on the gas giants, I had to buy a Gascraft and make it my flagship. I parked the remainder of my fleet before flying to Nenia to land on the gas giants. After coming back, I can't get my fleet back. I unparked it, moved my previous flagship to the top, but they all remain greyed out. In Shipyard and Outfitters, only the Gascraft is displayed. Trading tells me I have just 8 units of cargo space. In Hire Crew, I have 681 bunks, so somehow the program knows there are more ships somewhere. When I sell the Gascraft, I cannot do anything anymore. I'm including my latest savegame.
[Follykosi Afoklala.txt](https://github.com/endless-sky/endless-sky/files/2167504/Follykosi.Afoklala.txt)

**Comment by Amazinite** [comment]
You’re on the wrong planet. Go to the planet where your fleet is parked. 
Please close this issue.

**Comment by Afoklala** [comment]
Duh, that's stupid of me. Sorry.
