### ISSUE TITLE
Is Militia the same thing as free worlds? Why does killing Korath ships cause the Quarg to hate you? 

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#382]

**Comment by Pointedstick** [comment]
Militia become the Free Worlds. This should probably be a forum thread, not a Github issue.

**Comment by thenerdfreak** [comment]
No, I've began freeworlds missions and there are still Militia. I thought the same thing so I avoided attacking them, now I find that they have no correlation

**Comment by thenerdfreak** [comment]
so possible bug?

**Comment by endless-sky** [comment]
"Militia" means they are employed by a single planet to defend that planet. Some militia members join the Free Worlds, and they use the same colors, but they're not meant to be identical to each other.

And, attacking the Quarg should have no effect on your reputation with the Korath and vice versa. The only thing that will make the Quarg dislike you is attacking merchants.

**Comment by thenerdfreak** [comment]
Odd, I created a whole new save before my computer crashed and the only thing I'd attacked was a bunch of Korath and Pirate ships. The bad thing is I can find literally no way to chill the Quarg out, and they fry my weakling ships every time I go near that area XD

**Comment by Alkallid** [comment]
The militia are there for when you, e.g. do a spaceport mission of defending a planet.
