### ISSUE TITLE
Centering the mission system in mission selection UI is disorienting

### ISSUE THREAD

**Issue by thomasballinger** [endless-sky/endless-sky#3830]
Centering the target system when a mission confuses me because each time I need to find where I am again. I don't have a good suggestions, to know my current location could remain centered we'd need to know if the mission system is visible, which seems hard.

**Comment by endless-sky** [comment]
I think I've got a reasonable solution for this in ee883a4 - making the map motion animate over a third of a second instead of happening instantly.
