### ISSUE TITLE
Government map legend government panel potential issues

### ISSUE THREAD

**Issue by thomasballinger** [endless-sky/endless-sky#3833]
The code says 

https://github.com/endless-sky/endless-sky/blob/79152f11d6dd4629dd2324331e98fd9a391f1690/source/MapDetailPanel.cpp#L356-L357

but the current implementation of this is confusing to me as a player:

* The legend can list "Uninhabited" twice
* I see "Coalition" although I can't find any systems with this government

Maybe the Nodes in closeGovernments needs more data, whether the player knows what government that system has, or can actually see this system, or should otherwise be constructed differently?

**Comment by jafdy** [comment]
"Uninhabited" is both a government and a state of a planet, it appears twice to show both an uninhabited systems and the uninhabited planets in that system. At least I think that is what you are referring to.

The Coalition is a real government, I won't spoil it for you.

**Comment by endless-sky** [comment]
Both these things should be fixed in e574ba5.
