### ISSUE TITLE
Escorted freighters do not land.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#3839]
When doing the Free Worlds Freighter convoy and recovery from Lesath missions some times the escorted ship will not land to refuel and repair when I do.
Is this a bug or intentional?
I'm using the master from 7 July, running on Debian 9.

**Comment by jafdy** [comment]
If they are in the same system then they will land automatically when you do.

**Comment by VonZorch** [comment]
Sorry I wasn't clear.  They had all jumped in system with me.  The first time I landed on Trinket with none of them damaged and they did not refuel.

**Comment by Amazinite** [comment]
Well this is almost 3 years old, still unconfirmed, and I haven't heard of anyone else running into this, so I'm just going to close this one.
