### ISSUE TITLE
This game literally destroyed my PC (and how)

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#384]
I was in the sheratan system departing and reloading the game trying to get Korath ships to spawn, an I departed and went to reload and none of my saves showed up, immediately after my computer blue screened and won't come back on. Don't know if it is replicatable or not and don't recommend trying. GG pc

**Comment by Pointedstick** [comment]
Sorry to hear that, but there's nothing actionable here.

**Comment by thenerdfreak** [comment]
I was just putting it out; constantly opening and closing a save causes some kind of hard drive corruption, I had to reinsert my hard drive and reinstall Windows ( still installing atm)

**Comment by Pointedstick** [comment]
Tentative solution: stop using Windows! ;)

**Comment by thenerdfreak** [comment]
I'd rather use Windows than Apple (never tried Linux) because a broken window can be fixed, but a rotten apple means you have to buy a whole new Apple

**Comment by endless-sky** [comment]
It'd be hard to tell for sure whether that was actually a problem with the game, or just an unrelated issue with your computer that cropped up at the same time (possibly aggravated by the game causing it to run at higher than normal temperatures, say, or using up too much memory). The amount of file IO the game does once the graphics are loaded is pretty minimal, and the code for that is all simple enough that it's unlikely that it could, say, save a file to the wrong path and overwrite the system files. (Besides, aren't the system files write protected?)

**Comment by thenerdfreak** [comment]
Since I literally am getting a new computer soon anyway, I'm gonna try to replicate the glitch and see if it happens frequently, and see if I can figure out exactly what triggers it if I can replicate it (It could actually destroy someone's computer if it was the game) So far all that I know is i was spam reloading the game to try to get the rare encounters with Korath in the Core systems and it bluescreened at the same time that all my save files disappeared, It's highly likely that it over-heated since I've literally had a Planetside 2 10 hour marathon on max graphics and it didn't overheat. Might have just been that time of the year for my Windows.

**Comment by luiges90** [comment]
You might consider running a RealTemp to check your CPU temperatures to ensure that :stuck_out_tongue:

**Comment by endless-sky** [comment]
Given that no one else has reported file corruption or major crashes like this, this is probably an unrelated issue with your PC that happened to crop up while you were playing the game. In any case, it's not something that can be replicated, so there's no reason to keep it in the issues list.

**Comment by thenerdfreak** [comment]
I now believe it was due to me running a relatively new graphics card on age-old drivers. After my pc ate itself i figured how how to get the drivers directly from the maker's website. Hasn't even lagged or bothered me since
