### ISSUE TITLE
Add On Launch to Mission List

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#3840]
Would it be possible to add launch to the (job | landing | assisting | boarding) list?  Maybe jump too.

**Comment by endless-sky** [comment]
To clarify, you're saying you want to be able to create missions that are offered when the player clicks the "depart" button, or the moment the player jumps between systems? That seems like it'd be really annoying. And, would it cancel the departure in case the player has to change something in response to the newly offered mission?

If what you're asking for, instead, is actions *within* a mission that can trigger a dialog or event when you leave a planet or jump, that's what the "on enter" action already does.

**Comment by VonZorch** [comment]
"On enter" is exactly what I need.  Unfortunately it wasn't included in the writing missions tutorial.
The things I an trying to accomplish will all be invisible.

**Comment by endless-sky** [comment]
What tutorial are you referring to? It's included in the [official documentation](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions) on the wiki.
