### ISSUE TITLE
Joystick Support

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#3846]
Is there any chance of adding ship control by joystick?

**Comment by KiLEdEnNis** [comment]
I'm nearly sure this will be a no due to the various difficulties to add this feature for the tiny amount of people who would even use it
it's simply not worth it

**Comment by warp-core** [comment]
If Steam supports Joysticks, then you could configure one to be usable through Steam but I don't think it does. It is possible to use a controller via Steam though, if you're interested.

**Comment by MCOfficer** [comment]
there are lots of ways to bind joystick inputs to keyboard inputs, but that will only ever be binary (either on or off), which kind of defeats the purpose of the joystick's main feature (axes with gradial input)
