### ISSUE TITLE
Issue: Ability to abort a mission in flight.

### ISSUE THREAD

**Issue by TheMarksman-ES** [endless-sky/endless-sky#3847]
So this issue was raised in discord when we were on the topic of carrying passengers during the FW campaign. It then turned to a point where we joked about aborting a mission mid-flight and causing the person to be sucked out of the ship through the airlock. Needless to say, we found out that that was possible.

My suggestion would be to remove the ability to abort any mission while you are in flight, as aborting a mission while you are flying would probably be a bad idea for the civilian.

(Side note: Imagine tossing civilians out for the pirates.
"You here for the transfer?"
"Ya, i got the goods, how much this time?")

**Comment by TheMarksman-ES** [comment]
Do you? I might have made a mistake somewhere

**Comment by Amazinite** [comment]
I just doubled checked in the master and it looks like this isn't actually the case for aborting missions, but it is for failing missions. K.

**Comment by TheMarksman-ES** [comment]
So eh, can anyone check to see if they have the same issue?

**Comment by endless-sky** [comment]
This seems to be yet another case of realism vs. enjoyable game play. I think it would be rather annoying if you couldn't abort missions mid-flight, and instead had to remember to abort them the next time you were on  planet. And adding that restriction wouldn't make the game more interesting or more fun to play.
