### ISSUE TITLE
Create "box of extra ammo" outfits for EMP and finishers

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#3848]
https://github.com/endless-sky/endless-sky/pull/3818#issuecomment-402849302

**Comment by Nescio0** [comment]
The Railgun doesn't have an ammunition storage outfit either.

**Comment by TheMarksman-ES** [comment]
Is it just me, or is a certain someone necroing chat.

**Comment by Amazinite** [comment]
#5010 gets half of this finished.

**Comment by Amazinite** [comment]
#5241 gets the other half done. We still need railgun storage, but that can be handled in #4494.
