### ISSUE TITLE
Demanding Tribute from Pirate Worlds

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#3854]
Conquering a pirate world should improve your reputation with pirates.  Bring able to impresses them with your strength and ruthlessness.

**Comment by MCOfficer** [comment]
Hm. You can make that argument, but then again, we know that the pirates aren't always happy with their current overlords, either - not to mention that they are very proud of their freedom.

**Comment by gunqqer** [comment]
Currently (as far as I know) Tribute is a placeholder for endgame content. So depending on how tribute is implemented in the future this could work.

**Comment by KiLEdEnNis** [comment]
binding special tribute rules to a hardcoded(?) government for what purpose?
doesn't seem logical nor worth it

**Comment by DingusShingleton** [comment]
"placeholder"

**Comment by VonZorch** [comment]
Never mind then.
