### ISSUE TITLE
Soft Escort Limits

### ISSUE THREAD

**Issue by Darcman99** [endless-sky/endless-sky#3857]
Currently there is no upper limit to how many ships you can own and that bothers me. Obviously it's nice having the freedom to expand your fleet however much you desire but this just encourages the player to fly them around everywhere as escorts and I feel that really takes away a part of the experience. What if we had a way that we could still have both, no upper limit to fleet sizes but still limit the amount of regular escorts?

My proposal is that planets are given a new attribute that defines how many landing pads are available, and that value dictates simply how many can land. Players with less escorts than this value are clear to land, but if the player exceeds this value the planet will outright refuse to let the player and their escorts land.

With the soft escort limit this brings forth an aspect of play that often is ignored, managing groups of ships that fill different roles. For example a player may have a long distance fleet equipped with Jump Drives and ramscoops that is able to travel anywhere but is less combat oriented than other groups of ships. This soft escort limit means the player may need to decide between an exploratory group of ships or a harder hitting group of ships that aren't equiped for long distance travel, even ships designed to deal more unique damage (Heat, Ion, etc.) than shield and hull damage.

P.S. Won't be able to respond to any comments for a short while.

**Comment by Variance-Moment** [comment]
What about fighters and drones? How would you handle parking them? (From what you said on discord, fighters are only limited by carriers)

**Comment by Cerebrate-Daggoth** [comment]
I get where you're coming from, but I think that it limits itself in a way
seeing as how you need to pay crew salaries which can get quite pricey the
more ships you have.

**Comment by Darcman99** [comment]
I guess it could become a pretty harsh things to avoid, even if the player told via a dialog when they start to come close to one of the limits.

> I get where you're coming from, but I think that it limits itself in a way
seeing as how you need to pay crew salaries which can get quite pricey the
more ships you have.
Generally once the player reaches endgame they start making more than enough money to counter crew costs, essentially so much so that becomes just a minor annoyance rather than a barrier. I do see where you're coming from though.

Thank you for the feedback, even if it turned out to not be very well received, the idea's still out there.

**Comment by KiLEdEnNis** [comment]
the older argument was that if players want big fleets, let them have it, if people want a challenge, let them fly only a few
no need to add some rule for it

**Comment by jostephd** [comment]
> I get where you're coming from, but I think that it limits itself in a way seeing as how you need to pay crew salaries which can get quite pricey the more ships you have.

And depreciation.
