### ISSUE TITLE
Typo spoted

### ISSUE THREAD

**Issue by TheMarksman-ES** [endless-sky/endless-sky#3859]
![](https://cdn.discordapp.com/attachments/308902312741568512/470756146936807474/IMG_20180723_085623.jpg)

`... using him the "pacify" the...`
It should be `To "Pacify" the`

**Comment by TheMarksman-ES** [comment]
And yes, My screenshot button is broken, so I had to take a picture.
And this is in the log book.

**Comment by toilethinges** [comment]
https://github.com/endless-sky/endless-sky/blob/76a7b419422408dfa01031e963b2105906ef474b/data/free%20worlds%20intro.txt#L1851 looks right?

already fixed https://github.com/endless-sky/endless-sky/commit/57b01d08eec4dee9aaf09bb98eda254afa201a30#diff-9aa63feb581389f133863301083c1961

**Comment by TheMarksman-ES** [comment]
Ah, ok then.
