### ISSUE TITLE
Asteroid Belts. 

### ISSUE THREAD

**Issue by RedLucidity** [endless-sky/endless-sky#3865]
it occurred to me that you could implement asteroid belts similar to the Quarg rings using the existing asteroid sprites image as part of the ring design and a random placement following the planetary paths in the endless sky editor. 
with various size astroids being able to be random sized or placed within the ring. then those could be asteroid mines  stations. or other landing locations. Similar to the Ring but more selectable for placement.
This could give more variety of in system mission types and play. Perhaps the first ship a player gets isn't hyperspace capable as they didn't want to take a loan so they start off working as a mines cargo hauler for the syndicate delivering to the local space port getting a salary but not the value of the trade goods. Or they start off as an escaped criminal looking to make their way off a mining belt by capturing the cargo hauler and laying low until his crew of 5 can capture more haulers in an attempt to overrun a more combat accessible ship or one with a hyperdrive to get out of system, etc.

**Comment by Amazinite** [comment]
This doesn't sound like a good idea to me, simply because it would be adding a third type of asteroid to the game. You'd have asteroids that fly around randomly and can't be destroyed, asteroids that fly in circles around the system center and can be destroyed, and asteroids that remain static upon entering the system and can't be hit. Some new players seem to already struggle with the non-mineable/mineable asteroid distinction at first, and adding a third type of asteroid wouldn't help. That isn't to say that large asteroid landing locations shouldn't be a thing in the future, just that we shouldn't be making entire static asteroid belts akin to a ringworld.

**Comment by Pointedstick** [comment]
The idea of a donut-shaped asteroid belt would open up an interesting tactical consideration: it would be a zone through which you could not reliably fire missiles. So missile-armed combatants on one side of the belt would have to fly through it to engage targets on the other side their missiles, negating some of their range advantage. I think this would be a way more interesting way to limit the power of missiles in certain systems than we currently have with asteroid-rich systems like Kornephoros.

That said: wishlist, low priority, non-necessary, etc.

**Comment by jafdy** [comment]
I would quite like to reform the random asteroids into rings as well (leaving mineables in eccentric orbits). Missiles would need to be relooked at though.
It would give a way for a ship to "hide" from another by using the belt to avoid some fire.

**Comment by tehhowch** [comment]
We could implement a polar symmetry of sorts, but without appropriate animations to wrap an asteroid back towards the median of the belt, it could look wonky. Collision calculations will probably be fun too

**Comment by endless-sky** [comment]
A large numbers of asteroids all moving in circular orbits is very motion-sickness-inducing, especially if you zoom the view out. Large numbers of stationary asteroids that serve only as a backdrop would be really confusing (unless they were obviously darker and smaller, or something like that). A stationary asteroid belt that blocks missiles, in place of the current asteroid field, might work, but all the system maps would have to be re-worked so the asteroids wouldn't overlap the planets.
