### ISSUE TITLE
Question: Multiple CPUs, limitations?

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#387]
Just a simple question, will the game engine allow the use of multiple CPUs?

**Comment by endless-sky** [comment]
The game engine uses one CPU core for the engine itself (AI, ship movement, projectiles, etc.), one core for drawing, and can use additional cores for things like loading and decoding graphics and sounds.

Early on I considered having the engine calculations multithreaded, but they have to happen in a certain order - e.g. all AI calculations need to be done before any ship movement, which in turn has to happen before collision detection. So, multithreading those calculations would be difficult.

**Comment by jafdy** [comment]
So that's why the game thinks my core is running at 700%
