### ISSUE TITLE
PlayersRequest.

### ISSUE THREAD

**Issue by UserPlayer** [endless-sky/endless-sky#3873]
Hi all,

It would be nice to have the ability to choose a/one non inhabited world to create your home base/hub where you can store ships, cargo, missions and gathered equipment for future use.

Further more it would be nice to see what ships have gone missing/were destroyed after landing on a world. Seeing a whole bunch of missions failed/scrolling by followed up by multiple scans that wipe the text area clean doesn't help if one can't look back or 'scroll up'.

At times the price of resources isn't displayed right. It shows profit :xxx instead of low or high without having any resources of that kind in cargo.

Hope this enhances game play.
Fred

ps, Any thoughts to make this multiple user/interweb based? ;-)

**Comment by MCOfficer** [comment]
Since this issue is prone to becoming a clusterfuck of different suggestions, questions and fixes, please consider opening one issue for each suggestion/bug. That makes it much easier to deal with them individually.

> Any thoughts to make this multiple user/interweb based? ;-)
#149

**Comment by UserPlayer** [comment]
This is what you call game related feedback. You use it, fine, You don't, fine also.

Not to mention that I am not that far into the game and already have found in the eye jumping issues.
Maybe you split them out in small digestible parts.
