### ISSUE TITLE
Missing ships report.

### ISSUE THREAD

**Issue by UserPlayer** [endless-sky/endless-sky#3875]
Hi all,

It would be nice to see what ships have gone missing/were destroyed after landing on a world. Seeing a whole bunch of missions failed/scrolling by followed up by multiple scans that wipe the text area clean doesn't help if one can't look back or 'scroll up'.

**Comment by DingusShingleton** [comment]
I was just thinking that it when a ship dies, its entry in your information list turns red, but as soon as you leave the system or land it goes away. By simply having a column in the list with an [X] and only removing the entry when it's clicked, it would solve this problem. There could be an [X] at the column header that would clear all red entries.

**Comment by Bladewood** [comment]
Duplicate. https://github.com/endless-sky/endless-sky/issues/3361 https://github.com/endless-sky/endless-sky/issues/3418
