### ISSUE TITLE
[Suggestion/Feature Request] Outfit warehousing

### ISSUE THREAD

**Issue by charmparticle** [endless-sky/endless-sky#3879]
When I have some outfits in my cargo hold, I would like the option of storing them on a planet when I land, much the same way I would park a ship. This would allow me more flexibility and ease of use in configuring my fleet with a bunch of stolen tech. Perhaps the implementation could be to just add x amount of y outfit to the outfitter of that planet.

**Comment by Amazinite** [comment]
#724 #754 #2199 #3974
