### ISSUE TITLE
Game runs super fast (low tick rate?) under some condition (unsure of cause)

### ISSUE THREAD

**Issue by Ipiano** [endless-sky/endless-sky#3886]
I left the game running with my ship docked at a planet and went to do some house work for a while. About an hour later I came back and undocked my ship; at that point, everything was moving extra fast, my ship, and other ships; it almost felt like the game was in a 2x speed or fast-forward mode. I'm unsure what caused this, and I've never seen it before.

I know this isn't particularly helpful to fix the issue, but I wanted devs to be aware of it in case it comes up again or they see something that might be related.

Windows 10
Intel i5-3230M
Intel HD 4000 Integrated Graphics
Stable Branch 0.9.8 run through Steam

**Comment by nerdfact0r** [comment]
Did you press caps lock? That's the speed key?

**Comment by Ipiano** [comment]
That is likely it; I didn't know that the caps-lock key did that function.
