### ISSUE TITLE
Make water cooler available in more places

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#389]
The Water Coolant System is only sold in Syndicate, only listed in `Syndicate Advanced` in `sales.txt`

However, the Liquid Nitrogen Cooler is sold not just in the south but some places in the north too (I would argue the Merak system is on the north side), listed in both `Kraz Basics` and `Kraz Advanced` in `sales.txt`

Liquid Nitrogen is a more effective cooler than Water, so I would like to ask/check if it is actually intended? :confused:

**Comment by frameworld** [comment]
Still, liquid nitro is not scalable. Any cooling below 15 cargo space and you have to visit syndicate space.

**Comment by luiges90** [comment]
... or get multiple cooling ducts if you _really_ need it urgently

**Comment by endless-sky** [comment]
In commit a29cb00 I've made water cooling a "common" outfit, available in more advanced outfitters throughout human space.

**Comment by luiges90** [comment]
:+1:

**Comment by endless-sky** [comment]
Included in release 0.8.10.
