### ISSUE TITLE
Campaign

### ISSUE THREAD

**Issue by chimera8888** [endless-sky/endless-sky#3890]
Please add a way to find out what planet i have to visit to continue with the campaign!

I finished a small part of the FW campaign and then i went on to make more money and visit some systems but when i came back to continue the campaign i couldn't find which planet i had to go to for it.
I visited almost every system on my map and clicked on all space ports but nothing happened.

I am now stuck with an incomplete campaign and don't know how to progress.

Please make primary and secondary missions (not jobs) available anywhere regarding what system or planet you're on (like a transmission or something telling me to go on a certain planet to begin a new mission).

Thank you!

**Comment by MCOfficer** [comment]
usually such locations are logged in the captain's log (57bb6b5999d4193160e944403400f8e2a6a2c5b0).

if you require individual help, check the [steam forums](https://steamcommunity.com/app/404410/discussions/), [google groups](https://groups.google.com/forum/#!forum/endless-sky) or the [discord server](https://discord.gg/ZeuASSx).

**Comment by jostephd** [comment]
While the campaign is ongoing, if you go to the Job Board, you will see at the top right a campaign mission in the list of active missions. Selecting that mission will show you its description which will tell you where to go.

This is true at all times except (1) before doing the first Katya mission (the female officer who pulls a gun at you), (2) after losing a critical mission (should be accompanied by a dialog that tells you that you need to load an earlier save), (3) at several points during the storyline when you're told that you're on your own for a while and will be contacted when you're needed.

Please close this issue. See @MCOfficer's post for where to continue discussion.
