### ISSUE TITLE
You get repeatedly fined on game reload

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#39]
When landing with something illegal, you're likely to get fined.  The game is saved, but the next time you reload, the fine triggers again, **and** the game is saved again.  If for whatever reason you reload once more, you get hit by the same fine yet again... (this doesn't work every time as there's a chance to avoid a fine).

I see code specifically to avoid this (Politics::Reset()), but for some reason it doesn't work.

**Comment by endless-sky** [comment]
I just checked in a change that should fix this (03a9a08).
