### ISSUE TITLE
Arfecta cannot unequip cloaking device

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3908]
Out of sheer boredom I captured one of the two Arfectas guarding Wanderer space. When I went to an outfitter to re-equip my new ship (the turrets are great, the engines are not), I noticed it's impossible to unequip its cloaking device:
![screenshot from 2018-08-24 09-48-14](https://user-images.githubusercontent.com/21634324/44572625-b2acf080-a784-11e8-8f7f-35f1372717da.png)

Although I understand the Arfecta has a negative attribute to allow it to be cloaked indefinitely, an outfit that cannot be removed runs counter to the concept of outfits.
Different solutions to this minor problem/issue/bug include:
* remove cloaking device and internalize Arfecta cloaking (cf. Archon (Cloaked))
* replace the cloaking device with a new Pug cloaking device that does not consume any fuel
* replace the (negative) `"cloaking fuel" -.2` with a (positive) `"fuel generation" .2` (requires #3870 to be implemented)

**Comment by Amazinite** [comment]
The unequipable nature of the Arfecta’s cloak is for player choice. The cloaking device *can* be removed, just not without destroying (I.e. selling) the Arfecta in the process. https://github.com/endless-sky/endless-sky/issues/1344#issuecomment-234128902

Please close this issue.

**Comment by tehhowch** [comment]
Also #3669
