### ISSUE TITLE
Radar jamming is essentially worthless

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3912]
Consider the following exercises:

### Large ship
1. Install two Large Radar Jammers on a large ship with no anti-missile turrets, giving it a `radar jamming` value of 20 in exchange for 28 tons of space.
2. Install Sidewinder Missile Launchers on your ship.
3. Point your ship away from that ship and fire missiles continuously. Then do it again while pointed at the ship.

Observation: When pointed away, 90% of the missiles turn around, head towards the ship, and impact it. When pointed at the ship, about 99% of the missiles hit it.

### Small ship
1. Install one (or even two) Small Radar Jammers on an Interceptor-class ship, giving it a `radar jamming` value of 2 or 4 in exchange for 4 or 8 tons of space (quite precious on a ship that size).
2. Install Sidewinder Missile Launchers on your ship.
3. Point your ship away from that ship and fire missiles continuously. Then do it again while pointed at the ship.

Observation: When pointed away, 95% of the missiles turn around, head towards the ship, and impact it. When pointed at the ship, about 99% of the missiles hit it. The other ship's high speed and maneuverability make essentially no difference.

### For fun
Increase the `radar jamming` values of both jammers by a factor of 5 and try again! You still get almost exactly the same results, especially for the case where you're pointing at the target ship.

## Conclusions
- For common values of `radar jamming` (2-20), radar jammers are virtually worthless because they are not effective: almost none of the missiles fired at them will miss--even when the firing ship is pointing away from the target ship! Even with absurdly high `radar jamming` values, most of them still find their mark. There seems to be either something wrong with how the jamming is calculated, or else radar jammers need their `radar jamming` values increased practically by a factor of 10.
- Radar jamming is almost **literally** worthless when the firing ship is already pointed at the target ship. It simply doesn't matter, because the missile is already going the right direction. This would be alleviated somewhat with #1865.
- On a large ship, It is not space-effective to install radar jammers instead of some type of anti-missile turret, if there is a free turret hardpoint. If there is no empty hardpoint, filling that space with more shield generators would probably be more useful if defense is the goal.
- On a small ship, it is not worth sacrificing anything to make room for radar jammers because low values such as 2 or 4 are is not effective _at all_.

**Comment by DingusShingleton** [comment]
What happens in the small ship if you don't just fly in a straight line?

**Comment by Zitchas** [comment]
Currently, when a missile is jammed, it just stops steering and flies in a straight line. Which explains the rather high hit percentage of missiles fired directly at a target (basically, radar jamming is only useful if the target is dodging). I have no idea why such a high percentage of missiles fired *away* from it would still impact, though.

(Side note: Not relevant here because you used Sidewinders (which are radar based weapons), but the jammers only jam radar. So they'd be useless against meteors, which use infrared.

**Comment by Pointedstick** [comment]
> Currently, when a missile is jammed, it just stops steering and flies in a straight line.

Right, which would be addressed by #1865.

> basically, radar jamming is only useful if the target is dodging)

...Which makes it strange that Radar Jammers take up such a large amount of space. Even if they were actually effective even in small ship that's dodging, the high space usage would still be tough to swallow unless the small one was reasonably effective all by itself.


> What happens in the small ship if you don't just fly in a straight line?

> I have no idea why such a high percentage of missiles fired away from it would still impact, though.

The missiles don't actually enter a jammed state for common values of `radar jamming` (e.g. 2-20), so they hit their target even if it's dodging or in the opposite direction.

**Comment by Tadrix** [comment]
> values increased practically by a factor of 10

Or increase it by a factor of 5, halve the space they are taking (2 t and 7 t), and make them accordingly cheaper.

**Comment by jafdy** [comment]
Making the frequency of the jamming effect be related to both size and `radar jamming` so that smaller ships need less jammers to get the same effect. This isn't a solution on its own but it could be part of a overall change to the jamming equation.

**Comment by Pointedstick** [comment]
There really does seem to be something wrong with the algorithm. Increasing a ship's `radar jamming` to 400 still doesn't seem to have that significant of an effect: when firing Sidewinders while facing the wrong direction such that they'll need to turn around and maneuver, approximately 60% of them still turn around and end up successfully striking the target.

**Comment by Nescio0** [comment]
```
void Projectile::CheckLock(const Ship &target)
{
	double base = hasLock ? 1. : .5;
	hasLock = false;
	
	// For each tracking type, calculate the probability that a lock will be
	// lost in a given five-second period. Then, since this check is done every
	// second, test against the fifth root of that probability.
	if(weapon->Tracking())
		hasLock |= Check(weapon->Tracking(), base);
	
	// Optical tracking is about 15% for interceptors and 75% for medium warships.
	if(weapon->OpticalTracking())
	{
		double weight = target.Mass() * target.Mass();
		double probability = weapon->OpticalTracking() * weight / (200000. + weight);
		hasLock |= Check(probability, base);
	}
	
	// Infrared tracking is 10% when heat is zero and 100% when heat is full.
	if(weapon->InfraredTracking())
	{
		double probability = weapon->InfraredTracking() * min(1., target.Heat() + .1);
		hasLock |= Check(probability, base);
	}
	
	// Radar tracking depends on whether the target ship has jamming capabilities.
	// Jamming of 1 is enough to increase your chance of dodging to 50%.
	if(weapon->RadarTracking())
	{
		double probability = weapon->RadarTracking() / (1. + target.Attributes().Get("radar jamming"));
		hasLock |= Check(probability, base);
	}
}
```

Maybe the problem isn't that `radar jamming` is too weak, but that tracking (all types) is too good. Meteors tend to be quite effective against cold targets and torpedoes can track small ships. Perhaps the checking time is too long? Projectile lifetimes are typically between 1 s and 10 s.

**Comment by Nescio0** [comment]
sidewinder (turn 4°/frame, 240°/s):
```
target radar jamming              :     0 ,     2 ,     4 ,    10 ,    20 , 10000
probability to keep lock after 5 s: 0.900 , 0.300 , 0.200 , 0.082 , 0.043 , 0.00009
probability to keep lock after 1 s: 0.979 , 0.786 , 0.725 , 0.606 , 0.533 , 0.155
```
meteor (turn 1.35°/frame, 81°/s):
```
target heat level                 :    0% ,   20% ,   50% ,   80% ,   90% or higher
probability to keep lock after 5 s: 0.080 , 0.240 , 0.480 , 0.720 , 0.800
probability to keep lock after 1 s: 0.603 , 0.752 , 0.863 , 0.936 , 0.956
```
torpedo (turn 1.5°/frame, 90°/s):
```
target total mass                 :   200 ,   400 ,   800 ,  1600 ,  3200
probability to keep lock after 5 s: 0.133 , 0.356 , 0.610 , 0.742 , 0.785
probability to keep lock after 1 s: 0.668 , 0.813 , 0.906 , 0.942 , 0.953
```

**Comment by Nescio0** [comment]
```
namespace {
	// Given the probability of losing a lock in five tries, check randomly
	// whether it should be lost on this try.
	inline bool Check(double probability, double base)
	{
		return (Random::Real() < base * pow(probability, .2));
	}
}
```

```
void Projectile::CheckLock(const Ship &target)
{
	double base = hasLock ? 1. : .5;
	hasLock = false;
	
	// For each tracking type, calculate the probability that a lock will be
	// lost in a given five-second period. Then, since this check is done every
	// second, test against the fifth root of that probability.
	if(weapon->Tracking())
		hasLock |= Check(weapon->Tracking(), base);
	
	// Optical tracking is about 15% for interceptors and 75% for medium warships.
	if(weapon->OpticalTracking())
	{
		double weight = target.Mass() * target.Mass();
		double probability = weapon->OpticalTracking() * weight / (200000. + weight);
		hasLock |= Check(probability, base);
	}
	
	// Infrared tracking is 10% when heat is zero and 100% when heat is full.
	if(weapon->InfraredTracking())
	{
		double probability = weapon->InfraredTracking() * min(1., target.Heat() + .1);
		hasLock |= Check(probability, base);
	}
	
	// Radar tracking depends on whether the target ship has jamming capabilities.
	// Jamming of 1 is enough to increase your chance of dodging to 50%.
	if(weapon->RadarTracking())
	{
		double probability = weapon->RadarTracking() / (1. + target.Attributes().Get("radar jamming"));
		hasLock |= Check(probability, base);
	}
}
```

Maybe the problem isn't that `radar jamming` is too weak, but that tracking (all types) is too good. Meteors tend to be quite effective against cold targets and torpedoes can track small ships. Perhaps the checking time is too long? Projectile lifetimes are typically between 1 s and 10 s.

sidewinder (turn 4°/frame, 240°/s):
```
target radar jamming              :     0 ,     2 ,     4 ,    10 ,    20 , 10000
probability to keep lock after 5 s: 0.900 , 0.300 , 0.200 , 0.082 , 0.043 , 0.00009
probability to keep lock after 1 s: 0.979 , 0.786 , 0.725 , 0.606 , 0.533 , 0.155
```
meteor (turn 1.35°/frame, 81°/s):
```
target heat level                 :    0% ,   20% ,   50% ,   80% ,   90% or higher
probability to keep lock after 5 s: 0.080 , 0.240 , 0.480 , 0.720 , 0.800
probability to keep lock after 1 s: 0.603 , 0.752 , 0.863 , 0.936 , 0.956
```
torpedo (turn 1.5°/frame, 90°/s):
```
target total mass                 :   200 ,   400 ,   800 ,  1600 ,  3200
probability to keep lock after 5 s: 0.133 , 0.356 , 0.610 , 0.742 , 0.785
probability to keep lock after 1 s: 0.668 , 0.813 , 0.906 , 0.942 , 0.953
```

**Comment by endless-sky** [comment]
The real test is to put a jammer on your *own* ship and see how much less damage it takes when actively dodging, compared to when it has no jammer. If missile tracking were tuned so that a ship that is taking no evasive action can still often avoid being hit, missiles would be essentially useless against a player with decent dodging skills.

**Comment by Pointedstick** [comment]
> If missile tracking were tuned so that a ship that is taking no evasive action can still often avoid being hit, missiles would be essentially useless against a player with decent dodging skills.

1. I think jamming (not tracking) needs to be changed so that non-dodging ships can avoid being hit by some missiles
2. Isn't this actually desirable? Shouldn't we want player skill to make a significant difference?
3. When facing missile-armed enemies, the player is usually facing an enormous weight of missile fire, e.g. when fighting the Republic and Hai. The only time when you're really able to easily dodge is when facing off against single or small number of missile-armed pirates.

I don't understand the notion that a ship should have to "dodge" to avoid being hit with any sidewinder missiles if they have a radar jammer installed. Conceptually, this simply doesn't make sense to me, because the jammers that are actually effective for improving your sidewinder missile dodging ability are so large that it's impractical to fit them onto a ship that's small and maneuverable enough to be able to dodge.

From a realism perspective, modern warships employ extensive anti-missile electronic warfare suites to complement their anti-missile turret analogues. I don't see why they would give this up a thousand years in the future but keep the point-defense weaponry.

**Comment by finite-galaxy** [comment]
https://github.com/finite-galaxy/finite-galaxy/commit/6b7c41381bdb68696ea0281d6177ba5f08f07447 might be helpful.

**Comment by MCOfficer** [comment]
With all due respect to your work:

Almost all your comments in this repository have contained a link to your fork. Of course it's possible that I missed some (*cough cough*, GitHub search needs work), but the point remains:
If you want to make a suggestion, you could as well write "Why not increase the jamming frequency?" - but instead you chose to send a link.

I want you to realize that such behavior basically invites people to accuse you of advertising. I don't claim to know your intentions - i can't possibly know if you actually are advertising - but it does look like it, and eventually this will be what people think of you.
Thus, it'd be better to change this kind of behavior, even if there are no base motives behind it.

**Comment by finite-galaxy** [comment]
Fair point, I'll keep it in mind.

#4082 is indeed some kind of advertisement, which I made clear in its title.

Here I was merely trying to help: this issue has been open for months and it appears nobody worked on solving it. I provided a link to show exactly what to change; writing it all out in a post is more time-consuming and more likely to contain typos.

**Comment by Wrzlprnft** [comment]
To make it feeling less clickbaity i suggest including the commit message.
