### ISSUE TITLE
wiki - Incorrect directory for plugins

### ISSUE THREAD

**Issue by grawlinson** [endless-sky/endless-sky#3914]
[This](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins) particular page displays the incorrect directory for plugins on Linux.

`/usr/share/endless-sky/plugins/` should actually be `/usr/share/games/endless-sky/plugins/`

**Comment by Nescio0** [comment]
Are you sure? Which distribution are you using? My operating system is Fedora 28 and I have both `~/.local/share/endless-sky/` and `/usr/share/endless-sky/` directories, but not `/usr/share/games/endless-sky/`.

**Comment by grawlinson** [comment]
Yes, I'm using Arch Linux and v0.9.8 of ES.

I remember taking a look through the source code, and the directory is hardcoded to `share/games/endless-sky`.

The following files mention that particular string:

- SConstruct
- endless-sky.6
- source/Files.cpp

**Comment by MCOfficer** [comment]
you were probably looking at this bit:
```
#if defined __linux__ || defined __FreeBSD__ || defined __DragonFly__
	// Special case, for Linux: the resource files are not in the same place as
	// the executable, but are under the same prefix (/usr or /usr/local).
	static const string LOCAL_PATH = "/usr/local/";
	static const string STANDARD_PATH = "/usr/";
	static const string RESOURCE_PATH = "share/games/endless-sky/";
	if(!resources.compare(0, LOCAL_PATH.length(), LOCAL_PATH))
		resources = LOCAL_PATH + RESOURCE_PATH;
	else if(!resources.compare(0, STANDARD_PATH.length(), STANDARD_PATH))
		resources = STANDARD_PATH + RESOURCE_PATH;
```
but that's just ES determining where to get resource files from if it runs from the command line, as stated in endless-sky.6:

> When run from the command line, if a resource directory is not specified, the program will check to see if the current directory contains directories named "data" and "images" and files named "keys.txt" and "credits.txt"; if so it will read resources from the current directory. Otherwise it will use /usr/local/share/games/endless\-sky if it exists, or /usr/share/games/endless\-sky/ otherwise.


the actual creation of the plugin directory happens a few lines further down:
```
	// Create the "plugins" directory if it does not yet exist, so that it is
	// clear to the user where plugins should go.
	{
		char *str = SDL_GetPrefPath("endless-sky", "plugins");
		if(str != nullptr)
			SDL_free(str);
	}
```

this uses an SDL function to get the "best possible" config directory, which, i assume, depends on the OS' preferences. for example, the `.local` folder was originally only available on gnome.


conclusion: the actual plugin path (and thus what should be stated in the wiki) can differ between distributions.

**Comment by grawlinson** [comment]
That's strange that SDL returns `/use/share/games/endless-sky` for me. That's where I'm having to install all the plugins.

The fact that the directory varies is a bit troublesome.

**Comment by KiLEdEnNis** [comment]
MCO:
> \*slaps roof of word wall\* conclusion: the actual plugin/save path (and thus what should be stated in the wiki) is not hardcoded and can differ between distributions.

Nescio:
> I guess the hard-coded path is a fall-back option that is only used in case the GNU/Linux distribution does not provide one.

it ain't hard coded, Nescio, just saying

**Comment by endless-sky** [comment]
I've updated the wiki page to fix the path and clarify that manually-installed or created plugins should generally always go in the SDL preferences path, not the "hard-coded" path.
