### ISSUE TITLE
Marauder Arrows circle without engaging

### ISSUE THREAD

**Issue by damerell** [endless-sky/endless-sky#3915]
I've noticed that often when I take a bounty mission against marauders, the enemy includes an Arrow which circles me at high speed without actually engaging. I can fight it only by getting into its path in advance and shooting, at which point it breaks off and fights; but of course I can leave it until I have dispatched its compatriots.
I speculate these ships may have dubious outfits that mean they can't steer hard enough to approach a target easily.

**Comment by tehhowch** [comment]
As with any bug report, you need to strive to report details about your configuration. This game has two versions - the latest published release (e.g. the game on Steam), and the latest published commit (i.e. you built from source or downloaded the nightly build. At the current moment, there is a significant difference between the two.

**Comment by damerell** [comment]
Fair point. This is the 0.9.8 stable release downloaded from https://github.com/endless-sky/endless-sky/releases

data/marauders.txt doesn't seem to have changed much since that release.

**Comment by KiLEdEnNis** [comment]
![image](https://user-images.githubusercontent.com/10348657/44908248-13a36e00-ad1b-11e8-834e-7141def7fb70.png)
exhibit A
this boy can fit 0,893s of flying around before having no power in it

**Comment by Pointedstick** [comment]
The issue as described here has been essentially fixed by changes to the game engine in git master, as confirmed by taking some of these bounty missions and fighting Marauder Arrows. Still, their default loadout is somewhat ridiculous and could bear some adjustment.

**Comment by Amazinite** [comment]
It seems like the Marauder Arrow (Engines) is working properly now. Despite draining its energy to zero, the new fractional thrust gives the ship enough energy generation to spare to fire its lasers. I wouldn't be surprised if it's unable to use its AM turret while flying and firing its lasers, though.
