### ISSUE TITLE
Enemy ships can lose more crew than they actually have.

### ISSUE THREAD

**Issue by AlbertNewton** [endless-sky/endless-sky#3916]
When I capture Pirate ships, I often notice that, for example, I killed 14 crew from the enemy ship and therefore captured it, when the ship originally only had 11 crew. Also, I forgot to add a description, so this is it.

**Comment by jafdy** [comment]
I think what has happened is the you have assumed that all AI ships have the minimum crew, this isn't the case. Ships have an random amount of crew between min and max.

**Comment by Pointedstick** [comment]
Can't confirm and no additional information from reporter; closing. @AlbertNewton, please re-open the issue and add the requested screenshots if you can reproduce it. Thanks!

**Comment by Amazinite** [comment]
(Psst, I don’t think people can reopen issues we close.)

**Comment by Pointedstick** [comment]
Ah, my brain is operating with KDE's Bugzilla permissions model, not Github's. :)

Well, well and make noise if you think it should be re-opened!

**Comment by Pointedstick** [comment]
Great, thanks!
