### ISSUE TITLE
No character limit on names

### ISSUE THREAD

**Issue by TechnoNinja64** [endless-sky/endless-sky#3917]
This isn't much of a problem other than having ridiculously long and funny names. When you insert a name there is no limit to the amount of characters you can have (or at least if there is it's a bit large), leading to text running out of the box it's supposed to be in and going across and out of the screen

**Comment by DingusShingleton** [comment]
"Should I Post This Issue"
By dingusshingleton

Q: Do I say in the body of the text that it's not an issue? 

A: Yes

I should not post this issue.

Fin

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/1191#issuecomment-223782156

**Comment by jostephd** [comment]
@Bladewood I think the OP's point isn't to forbid long names, I think his point is the graphical glitch when doing that.

**Comment by tehhowch** [comment]
And the point raised is that if you know it is broken and unexpected but do it anyway.. do not be surprised when it is broken and not displayed correctly. What do you and the OP propose be done instead?

**Comment by jostephd** [comment]
Fix the textbox widget to behave like textbox widgets in other apps when its contents is wider than itself. It's a low-priority GUI bug since that widget isn't used anywhere in mainline other than the start dialog.

**Comment by czartrak** [comment]
Super long names are actually prevented. I tried once, and the game refused to keep a save file for it

**Comment by TechnoNinja64** [comment]
I've realised that other places also have this problem such as plugin descriptions, this could be fixed by making it "scrolling" (for the lack of a better word). As suggested making the textbox extend downwards or indicating that there are letters after (...) would fix this problem.

**Comment by Amazinite** [comment]
Ref: #2022

**Comment by TechnoNinja64** [comment]
@czartrak you can still save, only you have to do so manually by pressing "add snapshot." Although no autosaves will be made.

**Comment by TechnoNinja64** [comment]
https://drive.google.com/open?id=1d15jj_m544pwwWfRP2T9OCDHMMUiEBv2
Here are some screenshots I took

**Comment by tehhowch** [comment]
9eed145c should address the save file issue and the appearance of the name while entering it. The inability of `WrappedText` to break mid-word is a known defect from day 1 of Endless Sky on GitHub:
https://github.com/endless-sky/endless-sky/blob/cab74fd31f1984d2e9010b93849c2db2a09bc468/WrappedText.cpp#L234-L238

Given that we have folks working on new rendering & font inputs, I won't be trying to amend `WrappedText` anytime soon.
