### ISSUE TITLE
Game runs at varying speeds depending on the refresh rate set in monitor properties.

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#3918]
https://www.youtube.com/watch?v=7h2nESNU2Qo&list=PLIY8RUg5lX-JenE8U53kdDvPiIzRpJ9C-
Shows tests done with a stock shuttle at the start of the game at:
60Hz, 50Hz (both are progressive), 30Hz and 25Hz (interlaced) which output 60 and 50 'half-frames' respectively and 65Hz (progressive).
The shuttle should take approximately 3.6s (3.56...) to complete a single rotation and it does ath 60Hz or 30HZ (interlaced) but takes longer at 50Hz and 25Hz (interlaced).
I can't quite tell if the game runs faster at 65Hz, it's such a small difference that any increased speed would be difficult to detect and I don't have access to a monitor that will allow me to run a significantly higher refresh rate like 120Hz or 144Hz to get a more obvious result.

CPU: AMD Phenom II 1090T.
GPU: Radeon HD 5850 running Radeon Software 16.2.1
OS: Windows 10 v1607

I should be able to test this on Windows 7 soon. Any additional tests on Linux or OSX would be great.

**Comment by MessyMix** [comment]
Just checked it out for ya -- nothing on a 144 Hz monitor.

I have an in-game frame counter, and it's capped at 60 fps. That's probably why you don't pick up any difference between 65 and 60 Hz.

**Comment by endless-sky** [comment]
My understanding is that monitors with a refresh rate of less than 60 FPS are extremely rare these days, and have not been manufactured or sold in quite some time. So it doesn't seem worthwhile to make substantial changes to the game just to support monitors with lower frame rates.

**Comment by MessyMix** [comment]
I actually like it better this way. It means that when the game lags (FPS
lag spikes), the game doesn't 'skip' frames, instead just slowing down the
action so we don't actually miss anything.

**Comment by Zitchas** [comment]
EVE-ONLINE actually formalized lag in the form of a "Time dilation effect" that slowed down battles when they started getting close to the capacity of the server to handle, and marketed it fairly successfully as a feature to make mega-battles more enjoyable. I haven't played EVE, but I certainly enjoyed the videos that have resulted from that feature. (Being able to enjoy the battle in slower motion is really nice to do. Makes things less frantic and more enjoyable)
