### ISSUE TITLE
Negative reputation with uninhabited causes eye to deny passage

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#3919]
This was reported in the [QnA Thread on reddit](https://www.reddit.com/r/endlesssky/comments/91qi6l/qna_megathread_stagnation_edition/e57igp4/?context=8), using v0.9.8 from steam.

**Summary:**
ArK047 was unable to land on the eye, receiving the "authorities refuse to let you land" message. After correcting the reputation with the uninhabited government, everything was back to normal.
He was able to reproduce it by setting the reputation to negative again.

> I just went back and changed my relation with uninhabited government to negative again. The Eye refuses to let me land, the Hai wormhole is ok, the Remnant wormholes are ok, and the Pug wormhole is ok as well. The only thing that was changed is my relation to uninhabited.

This might be related to #2794 and #3233, but he pointed out some differences:

> After reading your links to the issues, I'm not sure if what I had experienced is the same problem.
> 1. The wormhole icon on the radar was the colour of wormholes and not planets. It also wasn't the orange colour that restricted/hostile planets have.
> 2. When I hailed it, I would get responses from the wormhole response list ("unable to send hail: this unfathomable void is not inhabited")
> 3. Wanderer fleets I had to escort between the two regions would path through the wormhole once I had made my way through Hai space via Jumps.

He is running one plug-in, which might be responsible for the negative reputation.
> I'm running one plugin that I wrote for practice. It adds only a ship, some outfits, a system and government to sell it, and a wormhole to get to it. This wormhole also works fine.

The pilot experiencing this issue was created in v0.9.8, pilots from earlier versions didn't have this problem.

**Comment by KiLEdEnNis** [comment]
> The pilot experiencing this issue was created in v0.9.8, pilots from earlier versions didn't have this problem.

isn't that because the Eye got a spaceport so AI could land on it?

**Comment by endless-sky** [comment]
I don't believe there's any way in the base game to change your reputation with the "Uninhabited" government. So this is arguably a plugin issue, not an issue with the game itself.

Even if the "Uninhabited" government was changed so that no player actions affect your reputation with it, there would be no way to prevent plugins from changing it back or from creating mission events which alter your "Uninhabited" reputation directly.

**Comment by TechnoNinja64** [comment]
Would it be possible to make the reputation of uninhabited positive each time you land/leave or even jump to avoid this from happening?

**Comment by KiLEdEnNis** [comment]
you mean everytime one departs and lands it checks for a certain government name? sounds like an unnecessary check for a mini detail for modders

**Comment by KiLEdEnNis** [comment]
basically if someone wants to mess up the game mechanics somehow they're gonna find a way, no need to fool-proof the game for such things

but the original issue was so that the Eye can still be landed on, which maybe should be fixed? (basically make wormholes not check for rep)

**Comment by TechnoNinja64** [comment]
Yes, that's probably a better solution

**Comment by Tadrix** [comment]
> (basically make wormholes not check for rep)

You don't want to do this.

Currently it's possible to make a controlled gate: a wormhole with a different sprite, a jump gate belonging to some high-tier species that activates only for friendly ships. Easy enough to make, it just needs to belong to a certain government. With your proposed change it would be impossible to achieve that.
