### ISSUE TITLE
Suggestion: What if fighters & drones are defeated instead of destroyed?

### ISSUE THREAD

**Issue by solardawning** [endless-sky/endless-sky#3920]
What if fighters never enter a disable state and cannot be destroyed as long as they have a carrier bay to retreat to?

**Think about what the gameplay would be like if:**
When a fighter or drone reaches 'disable' level of hull or lower, the game checks to see if there is a valid docking bay they could retreat to.

If yes, then this fighter/drone is not disabled or destroyed (even if hull = 0). Instead, it immediately enters a 'retreat' behavior, which has much of the functionality that Cloaking used to:
- no longer targetable
- cannot attack 
- attacks pass through them
The fighter/drone then retreats directly back to a valid carrier bay and docks.

On docking, they can not launch again unless they are fully repaired (either by hull repair outfits or landing). In other words; only fighters and drones at maximum hull can deploy.

**What if there's no available docking bay?**
Then they behave just like they do now. They never enter the retreat state, and can be disabled, boarded, or destroyed.

**Why do this?**
Currently, a fighter is just a manned missile. They fire once, and explode shortly after. They are ammunition that behaves like a ship.
Fighters and drones could be used as a meaningful choice if they functioned less like ammunition, and more like an extension of the carrier ship that could not be destroyed as long as their carrier is still alive.

This would create engaging gameplay in both combat and ship customization.
Carrier combat would be more interesting and intuitive; strike craft would retreat to the carrier, and taking out the carrier removes the threat. For the player, this means that strike craft become able to be used in regular gameplay.

Restocking fighters is costly and time-intensive, especially if you want to give them different outfit configurations than stock. Making fun ship configurations is the meat of the game; the endless customization and trying new strategies is what keeps it fresh and fun. When it comes to fighters, it's simply not feasible to do that for something that you can only get one use out of.

**Comment by Wrzlprnft** [comment]
i like the auto-retreat idea, though i don't like the plain invincibility.
maybe they get some sort of hit counter instead -added to not being targetable anymore-, so the player get's rewarded for some out of combat carriers or having tankier ships in the mix catching a lot of shots

**Comment by solardawning** [comment]
The big problem isn't stray shots, though; it's that exploding ships kill fighters. Any solution needs to prevent all fighters all dying instantly because they were near an exploding capital ship.

**Comment by Amazinite** [comment]
Duplicate of #906.

**Comment by jostephd** [comment]
> Restocking fighters is costly and time-intensive, especially if you want to give them different outfit configurations than stock. Making fun ship configurations is the meat of the game; the endless customization and trying new strategies is what keeps it fresh and fun. When it comes to fighters, it's simply not feasible to do that for something that you can only get one use out of.

#3921

**Comment by Amazinite** [comment]
This issue:
>What if fighters never enter a disable state and cannot be destroyed as long as they have a carrier bay to retreat to? ... When a fighter or drone reaches 'disable' level of hull or lower... attacks pass through them

#906
>As soon as fighters are disabled, all shots should pass through them and they should take no damage unless it's indirect

Both are proposing fighter/drone invincibility upon reaching the disabled state.

**Comment by Pointedstick** [comment]
> **Why do this?**
> Currently, a fighter is just a manned missile. They fire once, and explode shortly after. They are ammunition that behaves like a ship.

LOL

Auto-retreat would be a welcome addition. Instead of making them invincible when retreating, perhaps adding a new "crippled" state might give them a bit more time to escape.

**Comment by Thk54** [comment]
What about a more momentary invulnerability upon entering this crippled (where I assume they can still move just not shoot) state for the fight to move elsewhere before trying to get back to the carrier while damageable.
But I must say the real issue with fighters is that while the credit cost may be immaterial to the player the time IRL time cost of buying and outfitting new ones is many times greater than the cost of landing on a random planet to repair your fleet of non-expendable ships.
Remaking a fighter basically involves all the time and effort of making a new non-expendable craft albeit with a smaller shopping list and no possible jump-drive.

**Comment by DingusShingleton** [comment]
I once conceived of the idea of fighter insurance. You pay a per fighter fee based on the total value of the fighter. If it gets destroyed, the insurance company delivers a brand new one to you with the exact same outfits. I didn't really flesh it out enough to deal with alien outfits, how long it takes, when and where it gets delivered, etc. But it would be pretty sweet, cause right now the only really effective way to use fighters is to keep them stock lest you go insane refitting new ones the way you like. But I like my fighters to be more fun than that, eg heavy rocket dive bombers. But they.... tend to kill themselves with their own rocket. Like, all the time. Not fun.

**Comment by samrocketman** [comment]
I aggressively use fleet controls with fighters. F to focus fire fights (to launch some weapons) and G to  bring them back.  Or if I want to bring only the fighters back I use D to undeploy them which causes them to abort their bombing run and come back.

I think using fighters requires fleet controls to be on point and it's definitely a difficult skill.  That being said.  I really like fighters in how they are currently.

**Comment by Saugia** [comment]
See: https://github.com/endless-sky/endless-sky/pull/8989#issuecomment-1627817233
