### ISSUE TITLE
Syndicate intro mission: Meet a Syndicate captain at the space port, get a voucher for some Syndicate outfit

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#3928]
Split from https://github.com/endless-sky/endless-sky/issues/3921#issuecomment-419081398

> OT: Maybe if you go to a spaceport in Sol before you visited Syndicate space you should have some interaction with Syndicate captains? "Here's a 15% voucher for a Proton Gun [_marks Hephaestus on the map_]", "Would you like to do a cargo run for my boss on Millrace".

**Comment by AlbertNewton** [comment]
And how would these 'vouchers' work? It would require some change to the code, possibly substantial.

**Comment by jostephd** [comment]
On the contrary, I don't think it would require _any_ code changes at all. It'd just be a mission with a negative payoff that grants an outfit. Both things are possible:

https://github.com/endless-sky/endless-sky/blob/560155a9b84ffae7801edb19da0a23bdfe6a6686/data/wanderers%20start.txt#L227-L228

https://github.com/endless-sky/endless-sky/blob/560155a9b84ffae7801edb19da0a23bdfe6a6686/data/free%20worlds%20reconciliation.txt#L1250-L1251

**Comment by AlbertNewton** [comment]
Oh, well what I meant was it would be as hard to get vouchers added into the game as things separate to missions, like outfits, so that one could merely receive the discount when they bought the outfit normally, from an outfitter. Also, with this method of doing it, the player could immediately sell back the Proton Gun and make a profit.

**Comment by jostephd** [comment]
> Oh, well what I meant was it would be as hard to get vouchers added into the game as things separate to missions, like outfits

That hasn't been proposed, and doesn't seem to be required. Implementing vouchers won't require C++ changes.

> the player could immediately sell back the Proton Gun and make a profit.

Fair enough. Perhaps the discounted Proton Gun should be offered to the player upon completing some Syndicate mission? Say, the player goes to Sol, turns east, and gets some easy/intro Syndicate  mission at one of the spaceports; upon completing the mission, the voucher is offered to the player as part of the rewards.

**Comment by Zitchas** [comment]
"We'll give you a discounted proton gun, and just take the manufacturing price off your paycheque. It'll amount to getting it with a 15% discount!"

**Comment by jostephd** [comment]
That does seem like something the Syndicate would do, isn't it? That's what real world shops do today, "Buy three cans and get a newspaper for free!" (You can't get the newspaper's cost as a discount instead) The Syndicate would do the same thing and for the same reasons.
