### ISSUE TITLE
Feature Request: Walls

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#393]
How hard would it be to implement objects in a system that you could collide with? I'm interested in scenarios like a "system" representing the interior of an enormous alien artifact, which would have a fixed  layout of walls, or a "system" representing the interior of a wormhole that you had to actually fly through to get from one end of the wormhole to the other.

At a glance, it seems like collision detection wouldn't be too hard as long as the walls were limited to fairly simple collections of lines, since we're already doing lots of line-line intersection tests extremely quickly; the only part that initially appears difficult would be teaching the ship AIs to navigate through these things (though if the walls were fixed, pathing data could be baked into the map via waypoints).

**Comment by frameworld** [comment]
Waypoints -I tell from experience in SpringRTS- are a bad idea.

Instead use polygons as rooms and passages between rooms.
* Passages are dynamic way-points between upper and lower end of a passage.
* Polygons need to to be convex (no inside-angle > 180°)

**Comment by endless-sky** [comment]
This would be a big change to the way the game works, so I will probably not add it.

**Comment by dplepage** [comment]
That's fair.
