### ISSUE TITLE
document system requirements

### ISSUE THREAD

**Issue by matkoniecz** [endless-sky/endless-sky#3939]
Documenting system requirements would be helpful, especially for people with older computers.

I tried for example `system requirements site:endless-sky.github.io` and `system requirements site:github.com/endless-sky` searches.

**Comment by Amazinite** [comment]
From the [Steam game page](https://store.steampowered.com/app/404410/Endless_Sky/):
```
MINIMUM:
Memory: 350 MB RAM
Graphics: OpenGL 3.0
Storage: 65 MB available space

RECOMMENDED:
Memory: 750 MB RAM
Graphics: OpenGL 3.3
Storage: 170 MB available space
```
That's it.

**Comment by matkoniecz** [comment]
Then it would be even better idea to document it, with such specs it is worth mentioning in readme that it has almost nonexisting requirements.

At least for some it would be an important and useful information. For example my typically worry isthat  I was unsure whatever my computer is able to run given game.

**Comment by jafdy** [comment]
I typed `endless sky system requirements` into google and it came up with the minimum specs in a box, I didn't even need to click through to a webpage.

**Comment by gunqqer** [comment]
Even if it is easy-ish to find, we have a README for a reason. It should contain that info, or link to it (as in put it in the wiki near the top) This is pretty basic info for a game

**Comment by tehhowch** [comment]
Done in 5f538c1ad06876a3e89cb49302fb86f6b90b4cf0 and 411c1d3557995b69d247b25808730dd53039bd1d
