### ISSUE TITLE
Trigger for Free Worlds Missions?

### ISSUE THREAD

**Issue by zifix** [endless-sky/endless-sky#394]
Hi guys,
I have seen an event about a bombing on Geminus, but the story didn't seem to proceed. So I digged through the missions in
https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20intro.txt
I think I should be able to see "FW Recon 0" and "FW Katya 1" now, but haven't encountered these missions so far. Can somebody please explain the requirements to me?
Thanks in advance.

**Comment by ItsNickBarry** [comment]
Visit some spaceports on Free Worlds planets.  It will be triggered eventually.

**Comment by Wrzlprnft** [comment]
And do not try the karate move ;)

**Comment by jafdy** [comment]
I think that Katya triggers on skymoot. Recon is on one of the systems near deep.

**Comment by zifix** [comment]
Found it. Thanks!
