### ISSUE TITLE
Wanderers: Sestor Search: Human Spaceport can be got on Farpoint, giving confused dialogue

### ISSUE THREAD

**Issue by damerell** [endless-sky/endless-sky#3943]
I am playing a trunk build from the 4th September.

This spaceport encounter's dialogue references an attack happening at Farpoint, but it can be got on Farpoint. The dialogue is then confused; the NPC captain describes how they jumped away from Farpoint rather than land, and is at pains to tell you it's in the Atlinak system although you probably know that if you're already there.

**Comment by TechnoNinja64** [comment]
I'll assume you're talking about the captain that hired a leviathan, that got torn to shreds. The captain was going to land on Farpoint and got attacked by a Sestor fleet.

I don't see any reason why he wouldn't be at Farpoint, after all, he was attempting to get there. Logically the moment he found out the Sestor left, he would have rushed to Farpoint to complete his rush delivery. He takes pains to tell you the Sestor came from above the Alnitak system, not that they're still there.

I'm afraid your English isn't the best either, so I may have misunderstood some of the things you explained.

**Comment by damerell** [comment]
I have no idea why you say my English is "not the best". I have spoken English all my life and what I wrote is perfectly grammatical and idiomatic. Frankly, that is both insulting and absurd, and faintly ironic given that the expression "not the best" is rather clunky. You also omitted a comma before "either", a semicolon before "after all", and a comma after "Logically"; and should have no comma before "that got torn", and a capital letter on "Leviathan".

I don't know why you have to "assume" what I'm talking about. I provided the mission name in the issue.

I do not think the captain's dialogue reflects the possibility that they returned to Altinak after fleeing to Saiph. They have to be extremely foolhardy to return (in a still-damaged ship) to somewhere they just got nearly killed by unidentified aliens (the Navy logs are only mentioned in one fork of the dialogue tree and it would seem optimistic in any event to suppose that that was an absolute guarantee of safety, especially since the player has never been able to use the Navy to peek into adjacent systems). 

Also, they would refer to Altinak as "here" and probably remark on the fact that the aliens seem to be gone.

**Comment by kikotheexile** [comment]
1: I don't see the problem. 
2: That kind of banter is better suited to private messages. Not ideal for github where we at least pretend to be robotic and professional. 
3: What change would you suggest, assuming it hasn't already been changed in the newest version of the game?

**Comment by TechnoNinja64** [comment]
I was very tired when I wrote that comment, with the addition of my horrible communication skills. Rereading it now shows that I must've imagined errors, misread it or/and  I did not realise that was insulting, any insult was completely unintentional, I'm sorry. I've removed that part from the comment.


> so I guess they turned around after scouting out the Alnitak system
He says this, so why shouldn't he return to Alnitak and finish his rush delivery?
> but now I'm in debt to all my crew because I didn't meet a rush delivery deadline
This seems to say that he did finish the delivery, but finish it late.

**Comment by damerell** [comment]
The change I propose (and when last I looked the pertinent file had not changed in 4 months, so I do not think it has already been made) is that this encounter should not be able to happen on Farpoint itself.

I do not think the captain's dialogue is remotely consistent with them having returned to Altinak for reasons discussed above.

**Comment by DingusShingleton** [comment]
I also found this mission extremely confusing, dialogue on farpoint notwithstanding. The fact that the fleet jumps without displaying jump drive capability is extremely misleading.

**Comment by MessyMix** [comment]
> I also found this mission extremely confusing, dialogue on farpoint notwithstanding. The fact that the fleet jumps without displaying jump drive capability is extremely misleading.

@DingusShingleton the mission to find the Sestor? Or this conversation? And what fleet are you referring to?

**Comment by jafdy** [comment]
The sestor fleet that makes it across a JD gap without obviously having jump drives.

**Comment by DingusShingleton** [comment]
Yes, what jafdy said. Sorry should have been more specific.

**Comment by MessyMix** [comment]
Yeah, it's confusing, but IIRC it's to prevent the player from easily farming JDrives.

**Comment by jafdy** [comment]
"Easily", from a large fleet of T2 war ships?

**Comment by DingusShingleton** [comment]
Funnily enough on that note, once I finally located the fleet, the pop up message did not make it clear that I wasn't supposed to attack it... and it obliterated me over and over again. So I went and farmed shield beetles for like an hour until I was able to defeat it... only to realize that I wasn't meant to beat it in the first place. Thankfully it didn't break the mission chain or anything, but it was a bit awkward when they said "Ok, now it's time to beat that last fleet up at Altinak!" and I was like... ok... i'll do that...

Anyway, I'm not a clever man

**Comment by damerell** [comment]
I also was caught like that; I went and peeked in the data file controlling the mission, rather than farming shield beetles, but also initially expected I was meant to fight.

**Comment by jafdy** [comment]
That in part will be from the standard set by the game, unless explicitly stated the player is nearly always expected to fight any mission ships.

**Comment by Amazinite** [comment]
I've reworded parts of this conversation to hopefully make it make more sense should you get it on Farpoint. 0702ab5
I didn't want to simply restrict this mission from offering on Farpoint, because then the most likely place that the player will land in human space has no hint of where the Sestor might be (or we'd have to write an entirely new conversation just for Farpoint, which sounds a bit overkill to me). As such, I've added dialog where the Captain says that he still had to complete the delivery, but missing the deadline means he missed out on a bonus. This means that it's conceivable that you could find him on Farpoint, and he's only just returned to deliver the cargo.
Unfortunately, we can't check the source of the mission to change "Farpoint" to "here," so he'll still refer to Farpoint by name even if you are on Farpoint.
