### ISSUE TITLE
View wormhole routes on map once traversed

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#395]
Perhaps a dashed line between the two systems ( and only for those routes in the main Galaxy). Can code up myself if there's interest.

**Comment by endless-sky** [comment]
That could get pretty ugly once there are more wormholes in the galaxy, especially if some of them span very large distances.

**Comment by guillochon** [comment]
What if the paths rendered under all other display info?

**Comment by Wrzlprnft** [comment]
Maybe display it only when you click on a system containing a wormhole.

**Comment by frameworld** [comment]
A wormhole should at least have a blue vector pointing in the direction it leads to.
(the vector being a line 1/3 the size of the normal lanes)

**Comment by jafdy** [comment]
if you can get jump planing to use wormholes that would be massively helpful. Failing that marking systems with them in would be nice

**Comment by guillochon** [comment]
OK, here's my PR to implement this into the game. It also gives the player the ability to automatically path over wormhole links, which is extremely useful! https://github.com/endless-sky/endless-sky/pull/398

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
