### ISSUE TITLE
Plug-in Public Wiki Section

### ISSUE THREAD

**Issue by tmbutterworth** [endless-sky/endless-sky#3952]
Would it be possible to create a public Wiki page where plug-in creators can advertise their plug-in's: Name, Short Description, URL. Making it publicly modifiable would all the plug-in creators to do the work and not create additional overhead.

**Comment by jafdy** [comment]
https://opengamemods-group.github.io/ES-Mod-Share/
Or https://www.moddb.com/games/endless-sky/mods
Or https://steamcommunity.com/app/404410/tradingforum/

**Comment by tmbutterworth** [comment]
Sadly GitHub Wiki is either collaborators only or public. There is no way to make a single page public.

**Comment by MCOfficer** [comment]
related: #707 (cause it requires a central plug-in repo)
