### ISSUE TITLE
Game broken on load

### ISSUE THREAD

**Issue by Jaco5** [endless-sky/endless-sky#3955]
Endless sky loads, and is apparently running in the background, but the display window does not update unless I tab out and back. 

In example: I click new pilot, apparently nothing happens. I tab out to check the internet, tab back, and the window shows a frozen shot of the create new pilot text where you enter pilot name.

**Comment by Drl-Omniar** [comment]
this is the same problem that i had on my Pc Tablet, i think its the graphics card.(memory overload?) or its the disk drive.

**Comment by MessyMix** [comment]
Some things that would help would be to state the build version (0.9.8 or github build), the OS used, the PC components, etc.

**Comment by Jaco5** [comment]
Latest github

**Comment by tehhowch** [comment]
Please reproduce with the latest official release.

**Comment by Pointedstick** [comment]
Thanks!
