### ISSUE TITLE
Danforth using a Cruiser. Should use a carrier.

### ISSUE THREAD

**Issue by TheMarksman-ES** [endless-sky/endless-sky#3971]
> fgntToday

 at 08:34
ay so, why does Danforth use a Cruiser and not a Carrier?

> fgntToday

 at 08:36
always bothered me tbh, he is an admiral yet he does not use the Republic's most powerful ship as a flagship

Don't mind me, just Ctrl C Ctrl V somebody arguing for a carrier

**Comment by Philemon120** [comment]
I don't see why it matters? They're pretty similar and danforth's ship only shows up in a couple of missions.

**Comment by TechnoNinja64** [comment]
The only two things I could find where the default Cruiser is better than the default Carrier is in cost and turn.
Maybe Danforth didn't have a Carrier in port at that moment?
Or he just prefers the cruiser to it? (As in he got attached to his ship)

**Comment by TheMarksman-ES** [comment]
> ship "Cruiser (Jump)" "N.S. Peacemaker"
Seems like it.

**Comment by KiLEdEnNis** [comment]
if I remember, the Cruiser is a bit faster, and neither is really much better than the other, so it's more of "which one do I want to use"

**Comment by Amazinite** [comment]
So any actual argument as to why this should be changed? Does this need to be an issue?
The Cruiser and Carrier are both capital ships; they serve different purposes, even if the Carrier is bigger.

**Comment by TheMarksman-ES** [comment]
For the record, I don't like the idea that Danforth should use a carrier. If he's a cruiser captain, it'd make no sense to make him use a carrier.

**Comment by TheMarksman-ES** [comment]
It'd also be a waste of lives every time you send out your fighters. What Danforth needs is a troop transport cum heavy warship. Not a fighter carrying mobile space station.

**Comment by Amazinite** [comment]
Well it’s your issue. The close button is right there.

**Comment by TheMarksman-ES** [comment]
It's not mine? It's fgnt.
But honestly, I don't quite care, so ya.
