### ISSUE TITLE
Ramming Weapons

### ISSUE THREAD

**Issue by AlbertNewton** [endless-sky/endless-sky#3975]
I had an idea a few days ago for a new class of weapon for Endless Sky, or maybe just a general mechanic.
Ramming weapons should exist.
By which I mean, maybe an outfit to attach, it probably wouldn't even need a port or mount, that would deal damage to both ships if activated and ships collide.
Or maybe it could be a general feature (but of course you would have to target and use a keyboard key to ram) and these outfits would increase the damage to the rammed ship but not the rammer. Damage should increase with relative speed.

If this is a bad idea, don't hesitate to tell me. I just think that maybe it could work.

**Comment by KiLEdEnNis** [comment]
not gonna bother with why it should or shouldn't exist

how to make one, however (for AI, at least, a player can shoot it at random, messing up realism), with current mechanics:
- make a 1-frame mini-range weapon with some hit effects
- give it: hit force, negative firing force
- make it use no energy and generate no heat

but ramming may mess up some game mechanics, so likely not worth it

**Comment by AlbertNewton** [comment]
I know that there is already something similar to a ramming weapon. The Void Sprites have a (sadly unattainable) weapon they use to mine asteroids called the "Mouthparts?" It has almost 0 range and its effect does look like something is being eaten.

**Comment by Pointedstick** [comment]
A suicide drone is basically a missile, no? ;-)

**Comment by jafdy** [comment]
Longer life and can be recalled if not used.

**Comment by Amazinite** [comment]
I’d also expect a several ton drone to pack more of a punch than a fraction of a ton missile.

**Comment by KiLEdEnNis** [comment]
~make a drone carrier that can carry 20 of them, use them all at once~

**Comment by endless-sky** [comment]
> A suicide drone is basically a missile, no? ;-)

A missile you have to shoot down, rather than one your anti-missiles could deal with. And, it could carry other weapons as well. Aside from mechanics, it would just be a difference that could give an interesting flavor to a particular alien species.

**Comment by gunqqer** [comment]
I tried to do a sort of this in a plugin I created. It was like the drone weapon from SG:A. Main problem was the AI had no idea how to deal with a weapon of so small ranage and no matter how much I tweaked the engine speeds of turning and everything I'd always miss getting close enough. Another problem was it's damage but that'd be fixed by having it just explode on contact rather than using weapons. But yeah it would be an awesome type of weapon for an (ancient) alien spiecies. Maybe one that'd focus on single ships rather than fleets (hense the need for ship sized missile)

**Comment by amtgeography** [comment]
I once tweaked a Korath repulsor beam to have a massively increased effect (and size) and put one on a Vanguard. It basically let me push ships around like the hammerhead frigates in Homeworld, which had potential as a counter to one big ship hiding among a bunch of others. Dash in, shove it out of formation, pound on it while its escorts tried to chase.

Niche application, but could have its place in a fleet with the right doctrine.

**Comment by Zitchas** [comment]
That's the kind of weapon (aka niche maneuverability and isolation type weapons) that I want for the Remnant.

**Comment by AlbertNewton** [comment]
Almost all of the game's weapons are not kinetic weapons; with the exceptions of missiles, they use some kind of particle blast, or a Pug-derived laser beam. We know that shields were originally meant for fending off radiation, and only later were able to defend against solid objects, so ramming weapons might be more effective against shields than hull, maybe even having some element of piercing. Also, Zitchas, I did have another idea for a quirky Remnant weapon system, but it's not directly related to this issue, so I'll see if I can catch you on Discord.

**Comment by Amazinite** [comment]
Mouthparts?

**Comment by tehhowch** [comment]
To me, a very-low range weapon is not quite all that a "ramming" weapon should be.

I think some defining characteristics of ramming weapons are a scaling of the damage dealt with the momentum of the equipping ship, both ships experiencing a relevant impact force, and directionality requirements for the impact to occur.

Implementing this in a satisfying manner isn't a priority at the moment, though.

**Comment by Amazinite** [comment]
Well at that point it sounds like you're just implementing the ability for ships to collide with one another then attaching whether that actually happens to a weapon, and colliding ships would be quite outside the realm of the current game.
