### ISSUE TITLE
Massive CPU Spike when Taking Off

### ISSUE THREAD

**Issue by robot-rover** [endless-sky/endless-sky#3989]
I just noticed this a few days ago. This issue happens intermittently. Sometimes, when I take off from a planet, my CPU usage will spike up to over 1000% percent, and my framerate will drop to ~1 fps. The game usually recovers within 10-15 seconds, and then it is back to normal. Normally I get a solid 60 fps and only about 10% CPU usage. I'm not sure what is causing this, but I've experienced it even with no escorts and only 2 other ships in the system.

**Comment by KiLEdEnNis** [comment]
do you know if this happens in asteroid-heavy systems? my guess is it's maybe caused by the game loading a lot of data

**Comment by tehhowch** [comment]
How many missions do you have? Some plugins are bad about creating repeating missions with NPCs, which can result in heavy CPU use even when your in-flight squadron is very limited. Consider posting a copy of your save that can reproduce your issue (and note any plugins you may have).

As Kile mentions, sharing system details can also be helpful.

**Comment by robot-rover** [comment]
I am currently using a3eff7c, but I also observed the lag when I switched to the v0.9.8 release. I am running this on Linux.
I did a bit more testing, it seems that how much the CPU usage spikes is dependent on the system I take off in. For example, if I take off from Mekislepti or Chimitarp, the CPU usage spikes up to about 1000%, but even after it calms down, it will stay at ~50%, even when I jump to another system. If I jumped to Feroteri, it would stay abnormally high. If I landed at Feroteri, and then took off again it would go back to a typical 10%. I observed this happening over multiple trials. While it is true that the two systems that I tested that had high usage had more asteroids. I don't think that is the issue. First, if I took off from Feroteri, and the jumpped to one of them, my cpu wouldn't spike. Second, I monitored the disk usage with `iotop`, and I didn't see a spike in it during a spike. 
I am using quite a few plugins, so that could definitely be causing it. I tried removing the plugins, but then load my save crashes the game (duh!). I will have to do some monkeying around with my save to see if I can rip out the plugin parts and see if the issue persists. 
Finally, here is my current save file: https://gist.github.com/robot-rover/62966e82309022b469154b211f03dcce

**Comment by MCOfficer** [comment]
tehh had the right idea: the mission "Hydra at Host" has spawned over two thousand ships. it's also the reason your savefile is abnormally large (almost 5MB).

**Comment by Amazinite** [comment]
[Even I had this problem with the same plugin.](#1845) I suggest quarantining Project Olympus.

**Comment by robot-rover** [comment]
> tehh had the right idea: the mission "Hydra at Host" has spawned over two thousand ships. it's also the reason your savefile is abnormally large (almost 5MB).

This was the issue. I stripped all of those missions out of my save (size now measured in kilobytes) and uninstalled the coresponding mod. Game runs silky smooth now. Thanks guys!

**Comment by tehhowch** [comment]
Given you can compile source and have a save that would benefit, try merging #2788 into your build and playing with the offending missions and NPCs present (ditch the plugin that would create even more of the mission though). I would expect there to be improvement, but not sure how much.
