### ISSUE TITLE
Idea: Shutdown button

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#399]
It'd be cool if you could hit a button to power down your ship, which would behave pretty much just like being disabled except without any hull damage - your shields go down, your engines and weapons go offline, etc.

In fights, this would cause pursuers to treat you like a disabled ship, so they'd go after other targets if need be; out of fights, e.g. republic ships might demand that you power down so they can board and search your ship (and confiscate illegal goods/outfits).

With some of the changes discussed in #352 and #346, powering down could also stop some homing missiles and even some enemy ships from being able to track you (with the downside that you'd be shieldless when you brought your engines back online if they happened across you anyway).

**Comment by frameworld** [comment]
It feels dumb.
If your hull is hot from weapon impacts and heat from cooling systems redirected there, why should it suddenly be cold?

What happens if you accidentally hit the key?

**Comment by dplepage** [comment]
True, it shouldn't be instantaneous - your heat should dissipate over time while you're powered off. So it would not be useful in the middle of a fight to suddenly stop missiles from tracking you, but it would be useful if, say, you had just detected that an enemy fleet was warping in and you didn't want them to engage you.

**Comment by brendanjones** [comment]
But then if it was a pirate fleet, they'd just board you. I'll agree with frameworld, this feels a bit silly.

There actually is already a way to make your ship invisible to missiles and any other fire, for that matter - the cloaking device. It's not exactly widely available, but with more storylines added in the future it could be obtainable by other means than the Freeworlds storyline.

**Comment by Wrzlprnft** [comment]
I don't think that it is really useful in the actual state of the game, but maybe later on, to doge the effect of an slow moving ship disabling emp, or if some pirate-nerds hack your ship to board it easier and so on and so forth.
I wouldn't recommend to make it really kinda poor-mans-cloaking device, or only effective in a long range up to a distance where somebodey could detect anything... e.g. lifeforms or something like that.
it could work like the invisible board-line of system, but reverse: "if your ship is deactivated, they will ignore you until they are too close to you(pirates)/ you are to close to the center(defence fleets)"
Indeed it could be used to create more tension while the republic boards your ship, storyline or maybe on regular patrols, however

**Comment by anonybosch** [comment]
@dplepage When you say...
<i>It'd be cool if <b>you</b> could hit a button to power down your ship, which would behave pretty much just like being disabled except without any hull damage - <b>your</b> shields go down, <b>your</b> engines and weapons go offline, etc.</i>

Do you mean your entire fleet? Because the game doesn't distinguish between your flagship and your escorts.

**Comment by dplepage** [comment]
I wasn't really thinking much about the fleet version of it (I don't have much of a fleet, and find fleet management somewhat boring myself), but I imagine they'd shut down too (e.g. the same way all ships with cloaking cloak when you do). That said, I agree that this enhancement in general wouldn't add much to the game as it currently stands, so I'm going to close this issue.
