### ISSUE TITLE
Pug outfits lack a description

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#40]
Pug ships can be captured in only a few missions, and such capture causes quite large casualties, but is still perfectly possible.  Your crew has typically mere +1.3 fragmentation grenades vs +250 pug biodefenses, but on the other hand a Dreadnought's 89 crew is more than enough to overpower a Zibruka's 4 ("nec Hercules contra plures").

Thus, Pug gear can end up in the player's hands, and needs to be described.

A related issue: instead of reusing the graphics for human gear, you may want to draw generic "alien weapon", "alien power plant", "alien thruster", "alien steering" and use that for all such outfits.  While they're not as likely to be seen (not sure how many players do the "Korath hunting" pasttime), seeing a mundane laser or ion thruster seems out of place.

**Comment by endless-sky** [comment]
I've added descriptions for the Pug outfits (commit a69a5d6), but I'll leave this open until I get around to creating outfit graphics for them, too. Each outfit graphic can take me about an hour of work, so it might be a while before I have time for that, though.

**Comment by kilobyte** [comment]
Typo: "speicies".

**Comment by endless-sky** [comment]
In 3b12f3d I added a generic outfit thumbnail to be used for any outfit that is alien technology and cannot be purchased, but that you might acquire by plundering an alien ship. In the long run I want to come up with thumbnails for all the alien outfits, but this new icon at least seems preferable to confusing the player by reusing the image for an ordinary human item.
