### ISSUE TITLE
Idea: Plunder part of an outfit

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4001]
> Suppose I have a flagship with 60 tons of cargo space and a fighter with 20 tons of space.
> I shouldn't be able to steal a 70-ton outfit, because then I'd have to cut it up into 60- and 10-ton parts, which is impermissible.

Actually, leaving the fighters/drones aside for a moment, it's always annoyed me to board a ship and find it has a 100T generator that I don't have room for, and a bunch of smaller outfits worth much less per ton. I mean the `Bastion (Heavy)` and its Fusion Reactor. That variant's worth, assuming a cargo hold full of Luxury Goods, is 34% empty hull, 48% Fusion Reactor (100T), 17% all other outfits combined (361T), 2% cargo.

Would it fly to allow plundering only part of an outfit? For example, if I board a Bastion (Heavy) and don't have 100T available, I'd plunder 50T of the generator and sell them for a lower per ton price than the whole generator. The 100T generator sells for 1.25M (fully depreciated), so 50T of it could sell for, say, (50/100)^2 * 1.25M = 312k? That's a convex function, the more tonnage the player plunders the higher the price per ton is. The player would still need to plunder almost all the tonnage in order to get most of the value (plundering 71% of the tonnage would sell for 50% of the value).

In `Bastion (Heavy)` the reactor is so much more expensive per ton than any other outfit or cargo on board that even after depreciation and the discount from the last paragraph, it's still a better plunder. Plundering 50% of the reactor's tonnage gives a sell price over 6k/ton, a better sell price than any outfit on the stock _Carrier_ other than its generator and Large Radar Jammer (14T, 8.75k/ton).

I searched github but didn't find previous issues about this. If this is too much of a buff feel free to close this issue.

**Comment by Nescio0** [comment]
A different idea would be to make all energy generators (the most valuable part) unplunderable, because if a ship has no energy, its life support systems fail, thus allowing your reactors to be taken is equivalent to certain death.
Or perhaps make all installed outfits unplunderable; so if you board a ship, you can immediately steal its cargo, including outfits in cargo, but if you want the outfits, you have to capture the ship and land it on a planet with an outfitter to strip it.

**Comment by Nescio0** [comment]
A different idea would be to make all energy generators (the most valuable part) unplunderable, because if a ship has no energy, its life support systems fail, thus allowing your reactors to be taken is equivalent to certain death.
Or perhaps make all installed outfits unplunderable; so if you board a ship, you can immediately steal its cargo, including outfits in cargo, but if you want the ship's installed outfits, you have to capture the ship and land it on a planet with an outfitter to strip it.

**Comment by jafdy** [comment]
Purely from a technical standpoint this would be a pain to implement. How would you represent this option in interface? What would it look like when you are on a planet? Could you dump part of an outfit? How would that work? What about if the player plunder half a reactor then another half before selling the first half? How would you represent that? 
From a balence standpoint it is better, in the sense that it is no worse than what we have before, apart from the extra options we now need to consider. 
From a usability view this will be a nightmare, all the questions above still apply but now you need to make it clear to people what that button does when they don't know what the option to split an outfit exists.

Don't be discouraged, you haven't had much practice of thinking about new features yet but if you can create a good set of mechanisms for this then it will be considered.

**Comment by jostephd** [comment]
> How would you represent this option in interface?

Let's take a `Bastion (Heavy)` as an example. If the flagship has >=100T free cargo, the list of plunderables will start with `Fusion Reactor: 1.250M / 100T`, like now. If the flagship has <100T free cargo, instead of making the `Fusion Reactor` line gray, that line would be removed from the list of plunderables and a `Fusion Reactor (parts): 312k / 50T` line added instead, at the correct place (the list is sorted by price per ton). The price and tons in that line would depend on how much free cargo space the flagship has at that moment. Whenever the player plunders an outfit or jettisons something from the flagship (it's possible to do so while boarded), the list of plunderables would update accordingly, usually the price and tons on the `Fusion Reactor (parts)` line will change, but if the player jettisons a 100T item, the `Fusion Reactor (parts)` line would be removed and the `Fusion Reactor: 1.250M / 100T` line added back, since the flagship's free cargo will be >100T then.

If the player selects `Fusion Reactor (parts)` as the item to plunder, an outfit by that name will be added to the flagship's cargo hold. That outfit won't have any of the attributes of a generator outfit. It wouldn't produce power or generate heat. It will have only mass and a price, like the harvested metals outfits.

Do you think this will be clear?

> What would it look like when you are on a planet?
> 

The player will be able to sell the `Fusion Reactor (parts)` outfit in the same places he can sell harvested metals in: the trading screen and the outfitter (if the planet has one).

> Could you dump part of an outfit? How would that work?
> 

That's a good question. The simplest option to implement would be to treat the `Fusion Reactor (parts)` outfit like any other captured outfit and allow it to be jettisoned only in its entirety. Alternatively, the player could be allowed to jettison parts of the `Fusion Reactor (parts)` outfit, but the price per ton of the remainder will need to be recomputed after jettisoning, because the sale price function is convex/non-linear. (Otherwise it will be more profitable to plunder 50T and jettison 20T than to plunder 30T to begin with.)

Secondly, suppose the player plunders a entire Fusion Reactor the regular way, should it be possible to jettison half of the reactor in-flight and convert the `Fusion Reactor` in cargo to a `Fusion Reactor (parts)`?

> What about if the player plunder half a reactor then another half before selling the first half? How would you represent that? 
> 

Two instances of the `Fusion Reactor (parts)` outfit in cargo.

> From a balence standpoint it is better, in the sense that it is no worse than what we have before, apart from the extra options we now need to consider. 
> 

Yes, this would take some C++ to implement, but would reduce the difference between flagships that have a >=100T cargo hold and flagships that have a <=99T cargo hold.

> Don't be discouraged, you haven't had much practice of thinking about new features yet but if you can create a good set of mechanisms for this then it will be considered. 

I'm not discouraged, I'm glad to brainstorm the mechanics, thank you.

**Comment by Brick63** [comment]
Breaking a nuclear reactor tends to end very badly

**Comment by tehhowch** [comment]
From an implementation standpoint, doing this for all items would require dynamic outfit creation.

Probably I would not make this a default option that can be applied to any outfit, only to "opt-in" outfits that define a "salvage" node. Said node is a nested outfit definition with sprite definitions, and optional name and cost. Mass would be automatically set based on the number of parts, automatically flagged as not installable. Automatic cost would be probably 15% of the parent price, distributed over the number of parts:

```html
outfit <name>
    ...
    salvage [[<othername>] <# parts>]
        sprite ...
        [cost #]
```

In BoardingPanel we could use an icon for any outfits too large to plunder as-is, and provide a tooltip that explains "this item will be salvaged for parts if you plunder it now. Free up space first if you wish to remove it intact."

Then for kicks we do a random success roll and the player gets from 0 to N parts.

**Comment by jostephd** [comment]
@Brick63 Things that weigh 100T tend to be made of smaller parts. The parts can disassembled and sold independently. For example, the computer I type this on has a motherboard, a CPU, a graphics card, and some RAM chips. If you hit the computer case with a hammer until you had pieces about 10% of the mass of the whole assembly the pieces would be worth next to nothing, but if you took a screwdriver and took the parts apart you'd be able to recover most of the market value of the assembled computer.

**Comment by Amazinite** [comment]
I think that making it so that you can break outfits that are bigger than your current cargo space down into smaller one adds unnecessary complexity to the game, and would also lend to making boarding more powerful when boarding isn't a gameplay mechanic that needs made more powerful. The stated issue is as follows:

> it's always annoyed me to board a ship and find it has a 100T generator that I don't have room for, and a bunch of smaller outfits worth much less per ton.

That's really just the name of the game when it comes to plundering. If you want to loot a larger outfit, then bring enough cargo space to loot the larger outfit.
