### ISSUE TITLE
Amending behavior of `require` in Mission Actions (on ____)

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#4002]
In #3005 I alter the behavior of `require <outfit> 0` to perform an exhaustive check of every ship in the players fleet that is not destroyed. To give more control to mission creators, it is probably useful to define an argument for this line and the regular `outfit <outfit> <#>` that specifies *where* the outfit should be looked for. Perhaps a mission being written should only check the flagship. Perhaps a mission should only check escorts, or cargo. Currently, there is no way to instruct the game where to search, and so installed outfits can only be taken from your flagship, and given outfits are only installed onto (or placed in the cargo of) your flagship (c.f. #3037 ). With a location specification, this default behavior could be overridden.

<details><summary>c.f. discord with @Amazinite  and @zitchas</summary>

Zitchas: Is there anyway to differentiate between the three?
There's basically three separate places an outfit could be:
 a) installed in flagship
 b) installed elsewhere in the fleet
 c) in cargo

For mission purposes, knowing how to differentiate between those would be very useful.
I've already got a few missions that use that mechanic. My descriptions assume that it is actually installed.

-------------

Amazinite: Yeah, I think the suggested changes to require make sense then. But as Zitchas noted, discriminating between a player's flagship, fleet, and cargo would be nice, although that could be a separate PR.
Such ability to discriminate could also mean offering if an outfit is on the flagship but not on any escorts. E.g. someone takes notice of your flagship having a keystone but your escorts not.

-------------

Me: to me i recognize the following definitive locations:
1. PLAYER
exhaustive check. Maybe it's installed on your flagship, or your combat escort. Maybe it's installed on a parked superfreighter. Maybe it's in your flagship cargo bay. Maybe your escort just scooped it up after you jettisoned it.
Wherever it is, you have it. (Your accountant knows about this item).
2. CARGO
only checks available cargo space. Always includes the flagship's cargo. If you're boarding, that's the only cargo - your escorts didn't board this ship, you did. If you're landed, then it includes anything that any escort that landed with you brought. Any out of system ships? Too bad, they're not around. (no ships have individual cargo space while landed)

There are also ambiguous locations:
3. FLAGSHIP
only checks the flagship. Always includes the flagship's outfits. If you're boarding, it also means your flagship's cargo. If you're landed, your flagship has no cargo (it was pooled with cargo from your other escorts that landed). Maybe this also includes the pooled cargo when landed. (This is very close to the existing behavior)
4. INSTALLED
never checks cargo. always checks your flagship's outfits. but, which escorts to check, and when? If in space, check only in-system ships? or all in flight ships? parked? If landed, check only in-system ships? parked too?
</details>

Of note is that there are two locations for mission spawn: 
1. in flight, as you board another ship
Each unparked ship has individual assigned cargo space
2. landing on a planet
Any ships that landed with you have no cargo space. Any ships in flight (e.g. out-of-system or disabled) have cargo space.

So: what keywords make sense? What places should they search? Can we come up with keywords and locations that do not become confusing when applied to both in-flight and landing missions?

**Comment by Amazinite** [comment]
Well we should look at what we could possibly check

Ships:
* Flagship
* Escorts in system
* Escorts out of system
* Escorts parked

Outfit locations on a ship:
* Cargo
* Installed

So there's 7 possible places of where an outfit could be (as parked + cargo isn't a valid location).

My thoughts:

Keyword | Behavior landed | Behavior in space
---------|--------------|-----------
None | Check everything (current behavior) | " "
Cargo | Check the cargo across the fleet in the system | Check flagship's cargo
Installed | Check installed across the fleet in the system | Check flagship's installed
Flagship | Only check flagship's installed outfits | Check flagship's outfits and cargo
Fleet | Check the installed outfits and cargo of any escort anywhere (i.e. in system + out system + parked) | " "
Escort | Check the installed outfits and cargo of escorts in system | " "
Parked | Check the installed outfits on parked ships | " "

**Comment by tehhowch** [comment]
What's the difference between `Fleet` and `Escort` in your table? And how would disabled ships fit in to your checks? Is a disabled in-system ship counted as in-system, or out-of-system? Currently, the game makes the check for can-this-complete using the "if you landed right now" clause, so disabled and out-of-system are effectively equivalent. I can certainly understand arguments regarding offering a mission treating them as in-system though, because there is nothing explicitly stopping you from repairing them right after the mission offers.

**Comment by Amazinite** [comment]
`Fleet` includes out of system escorts and parked ships; it;s everything in your "fleet."
`Escort` only checks in system escorts, excluding ships that are out of system or parked on other planets.
`System` is essentially `Escort` + `Flagship`

**Comment by Amazinite** [comment]
I know it doesn’t cover every possible combination of places one could look, but I tried to cover the ones I thought would be most useful.

**Comment by tehhowch** [comment]
one possible implementation would be similar to NPC success / failure / actions tracking, and Commands, i.e. a bitfield and flags. Each entry in the require map would be tied to a "location" bitfield, and when evaluating if the outfit requirement is satisfied, the implementation can test if the  field includes the given flag, and if so, perform the correct check.

This type of implementation would allow specifying the intersection (i.e. ORing) of flags, so you could require something in a parked ship or the flagship or the fleet, etc.

**Comment by Amazinite** [comment]
On the syntax end of things, how about allowing `require` and similar keywords to have children that specify where to check?
Examples:

Check for at least 2 jump drives in the flagship's cargo.
```
require "Jump Drive" 2
	flagship
		cargo
```
Check for no electron beams in ANY escort
```
require "Electron Beam" 0
	escorts
```
Check for 50 Quantum Keystones in the cargo of present ships
```
require "Quantum Keystone" 50
	flagship
		cargo
	escorts
		cargo
			present
```

The following is an exhaustive check displaying all possible locations (with some redundancy).
```
require "Heavy Laser"
	flagship
		cargo
		installed
	escorts
		cargo
			present
			absent
		installed
			present
			absent
			parked
```

* If no children are listed, do current behavior.
* `flagship`: The player's flagship. If no children are listed, check both installed and cargo.
	* `installed`: Check only installed.
	* `cargo`: Check only cargo.
* `escorts`: The player's escorts. If no children are listed, check both the installed and cargo of all escorts.
	* `installed`: Check only installed. If no children are listed, check all escort installed.
		* `present`: Check those escorts in the flagship's system. 
		* `absent`: Check those escorts out of the flagship's system. 
		* `parked`: Check those escorts that are parked. Have parked ships be their own category entirely (e.g. in system parked ships aren't check with `present`) or have parked ships show up as present or absent and have an additional keyword for ignoring parked ships?
	* `cargo`: Check only cargo. If no children are listed, check all escort cargo.
		* `present`: Check those escorts in the flagship's system.
		* `absent`: Check those escorts out of the flagship's system. 

If children of children (of children) isn't desired, then an alternative could be the following:
```
# An exhaustive, redundant search with only a single level of indentation, and using 
# the idea that parked ships count in present and absent alone, meaning that 
# parked/unparked keywords are necessary.
require "Heavy Laser"
	flagship
	flagship installed
	flagship cargo
	escorts
	escorts installed
	escorts installed present
	escorts installed absent
	escorts installed present parked
	escorts installed absent parked
	escorts installed present unparked
	escorts installed absent unparked
	escorts cargo
	escorts cargo present
	escorts cargo absent
```

The benefit that this has over the single keyword idea that I mentioned earlier is that it's exhaustive and allows for checking any combination of possible locations.

**Comment by Amazinite** [comment]
I've created a branch that does some of the work for my proposed implementation that should hopefully better show what I'm getting at if I didn't explain it well enough. https://github.com/Amazinite/endless-sky/commit/6fa3f9d91c466f09eb8b50e8b31161d03c152a7e

**Comment by Amazinite** [comment]
I'm mainly thinking of this in relation to `require`, but how should `outfit` work?  If the mission wants to put an outfit in an escort, what escort is chosen?

I have my branch *mostly* working in relation to `require`, with the only kink seeming to be that the `escorts` keyword also checks the flagship.

**Comment by Darklocq** [comment]
Definitely need to be able to exclude one's ships that are out of the system or parked somewhere. It would be immersion breaking for some patrol to come up and scan your actual fleet, right in front of it, and magically detect something that is parsecs away.  But by the same token, one might want to enable some mission as long as the player has access (even if inconvenient access) to some optional widget they picked up in a previous storyline.  So, being able to include parked and left-behind ships might also be of use.
