### ISSUE TITLE
Catac. Ramscoop available for purchase before it comes up in the story-line

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#401]
Directly after the second captured Navy transport mission (where you liberate the planet wanting to be Free Worlds) i noticed it was available in the Deep, but haven't gotten the story line yet

**Comment by endless-sky** [comment]
The idea was that that's just natural technological progress: someone in the Deep just invented it, and it's for sale now. Unlike some of the Free Worlds technologies, you're not actually helping to invent it, you're just stealing someone else's invention.

**Comment by thenerdfreak** [comment]
True, I inferred that since it came up in the story line it wouldn't be released until it makes sense to the story line (Dreadnoughts for example)
