### ISSUE TITLE
Some outfits are available via shipyard but not via outfitter

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4011]
**Is your feature request related to a problem? Please describe.**
During the early game I often go to Zug for its shipyard and outfitter and find that I need a Heavy Anti-Missile Turret for one of my escorts. Zug doesn't sell anti-missile turrets, so as a workaround I take a 1M credits loan, buy a Hauler, strip its anti-missile, sell the Hauler back and repay the loan. That's tedious.

(I think once I did the same trick but in addition to taking/repaying a loan I also sold a bunch of expensive outfits, and possibly a hull or two, and then bought them back.)

**Describe the solution you'd like**
If a planet has a shipyard that sells ship X, which the player can buy (has the necessary licenses and funds), the planet's outfitter should have in stock every outfit that's installed in ship X's stock setup.

Perhaps also allow buying an empty hull in order to fill it with cheaper or plundered outfits (ref #4010).

**Comment by Amazinite** [comment]
Duplicate of #1213.

**Comment by Zitchas** [comment]
Think of it like the buying a pre-built computer. Lots of places sell the whole unit together while never even considering having the individual parts for sale. The fact that ships (like computers) come as pre-built units is annoying to those of us that customize them, but are incredibly convenient for corporations and regular buyers who don't really care about customization. Or like cars, where the most option people get at the ~~shipyard~~ car lot is whether to buy the regular version or the sport edition. Despite the fact that there are hundreds or thousands of parts that could be swapped out.

From the point of view of someone who knows what they are doing, knows what they want, and is going to be modding it, it is very annoying. Realistically, though, it is what works best for 99% of normal buyers.

**Comment by jostephd** [comment]
@Zitchas I know how real-world shops work, but I don't understand why it's relevant. When designing a game's UI the question is what do 99% _of the players_ want, and on that, I'll quote [the manual](https://github.com/endless-sky/endless-sky/wiki/PlayersManual):

> Most of the strategy lies in how you outfit your ship.

So I think most players aren't your "regular buyers who don't really care about customization" types.

**Comment by Zitchas** [comment]
That's true, most players *aren't* regular buyers.

That being said, I consider this "discrepancy" to be part of the fun & challenge of the game: Learning where to buy the ships I want, and where I have to go to get them outfitted the way I want. It is a nod to realism that the two often aren't the same place, and honestly, it helps me enjoy the ship I end up with more knowing that I had to put some work into getting it the way I like.

On the same note, figuring out that I can "sneak" a copy of a particular item via buying a ship is another trick that I consider to be a rewarding element of gameplay; especially when said outfit is one that I don't normally have access to for some reason (The only planet that provides them is hostile to me, for instance, or it is locked behind a license.). I think doing that ranks right up there with capturing and salvaging for outfits.

**Comment by jostephd** [comment]
That's a good point. :+1: 

The way it feels to me, on the other hand, is that the UI is making me jump through hoops: go to bank, take loan, type amount, go to shipyard, buy ship, go to outfitter, scroll to outfit, sell it, go back to shipyard, sell ship, go back to bank, pay loan... That's a 12-step process of which 11 steps could be removed.

**Comment by Pointedstick** [comment]
The same thing has been observed regarding commodities: go to map, see which commodity will fetch the best price, close map, go to Trading screen, buy commodity, etc. It would be so much faster if the game could simply be told to automatically buy the most profitable commodity for a location you mark on the map. But that would essentially eliminate the whole game mechanic. It's the same here. I think the current UI is fine.

**Comment by jostephd** [comment]
I see your point. I'll close this issue then. Thanks everyone for the discussion.

**Comment by Pointedstick** [comment]
Thanks for your understanding!
