### ISSUE TITLE
For Consideration: Ship specific Attributes (Gameplay/Depth enhancement)

### ISSUE THREAD

**Issue by kikotheexile** [endless-sky/endless-sky#4016]
__Intro:__
This will come across as a feature request, but it isn't quite one. As I have been working on other projects, I have come up with an idea for Endless Sky. One I am willing to put some of the work into myself. That being said, I would also be more than willing to let someone else do this. So I will share all of my thoughts here, and let people pick and choose what they think will be good additions.

__Concept:__
Ship specific attributes which trigger landing missions based upon what ship you happen to be flying as your current flagship.

__Argument for Enhancement (How would it make the game more fun?)__ 
A regular complaint of the game is that it is kinda a big, empty universe. You can fly around in an Arfecta, and no one so much as bats an eye. The only times when you are ever noticed for having alien tech are when you have a jump drive, and even then that is only for core-story specific lines of text. This would further ground players into the universe, and would offer a bit more content while at it.

It is also an insanely easy addition to make to the game, and is very low cost for data. The biggest issues for it is just the sheer amount of content that *could* be written for it, but that is a problem for another time.

__Current thoughts/plans/ideas:__
Luxury Attribute: This already exists, however it could be a built in feature of the Star Queen. 
Fast Attribute: An attribute that triggers some specific missions that involve blockade running. These would be jobs and spaceport missions that could be offered during the war. This could be applied to both ships and outfits. 
Shipyard Name Attribute: This would list what shipyard the ship was purchased from, and much like in the real world, some people would react positively or negatively to the ship you are flying
Outfit Manufacturer Attribute: Same as above, but for outfits

Alien Ship: An attribute all Non-human ships have, with the exception of the tier 1 pug, and hai.
Alien Outfit: An attribute all Non-human *visible* outfits would have. I don't think many people would comment on the fact you had a hai power core, but a lot of people would notice dual sunbeam turrets
Alien Species name: This would be used to trigger specific mini-arcs involving human and/or other species and their questions about exactly where you got this ship from. 

I am considering also other attributes, such as "Easy target" attributes which would have people tell you that the ship you are flying looks like it would attract a lot of pirates. This wouldn't so much be an arc, but something to tell the player that they may need an escort. And so on. 

*__Thank you for your time!__*

**Comment by Janaszar** [comment]
For "Easy Target", I would think it would be better instead to have that run off of your Pirate Raid attributes; DPS/Cargo Capacity (or, was it the other way around?).

As for Alien Ship/Outfit, I would say either have Alien-specific keywords (Pug, Hai, Wanderer, Korath...), or ship-specific keywords.  I tend to want ship-specific keywords, as that would open up more detailed conversation options, like "Hey, look at this guy using a Star Barge vs the Pug!".

Outfit/Shipyard... I can only see this being used for those little quotes while flying or similar things.  Would probably push this as a late idea.  Though, would be useful just for the data on each part.

Fast: Except for the fact that you can't actually blockade anyone, ok.  If there was some way to force people to run away outside a zone you couldn't hyperjump from, that would make more sense.  As of right now, seems limited to just Roleplaying/Lore.

**Comment by kikotheexile** [comment]
> Fast: Except for the fact that you can't actually blockade anyone, ok. If there was some way to force people to run away outside a zone you couldn't hyperjump from, that would make more sense. As of right now, seems limited to just Roleplaying/Lore.

Scram drives, lightweight hulls, the largest turning engines. "fast in, fast out" of the system. Blockade running is actually already a part of the current game, and you use it to acquire the catalytic ramscoop early game.

**Comment by kikotheexile** [comment]
Similar Issues per @tehhowch 
#2616 
#4002

**Comment by Zitchas** [comment]
As a mission writer, I really like the idea of having attributes like these that can be checked for and referenced in missions. 

The only one of the things mentioned that I'm dubious about is the "Fast" one, as it is perfectly possible to make a fast ship actually quite slow, and likewise some slow ships can be made fairly fast if one really tries. Basically, as we all know, it comes down to what the player has equipped. For something like speed related attributes I'd love to just be able to write a test directly against Top Speed, Acceleration, or Turn Speed. (specifically, ship specific tests would be against the player's flagship only. Otherwise it'd be thrown all out of wack because they have some fighter parked on a planet somewhere)

**Comment by Amazinite** [comment]
Pretty much a duplicate of #2911, my dude.

**Comment by Pointedstick** [comment]
Close as dupe?

**Comment by kikotheexile** [comment]
@Amazinite @Pointedstick  similar but not duplicate. 

The problem here is breath and scope. Stopping at luxury, or stopping at any point would be counter productive. 

Maintaining this obviously can't and shouldn't be handled strictly by collaborators, and shouldn't stop short at any point. Hence why I opened a new issue. If it were a dupe, i would have commented in one of the 18,000,000 similar issues. 

The concept is obviously a popular one, and the issue has been opened for me to reference as I PR changes, as well as for people to argue with me on.

**Comment by Amazinite** [comment]
The request is for missions to be triggered by ship attributes. That's what #2911 asks. You just listed more examples of how it could be used. It looks like a dupe, it smells like a dupe, I think it's a dupe.

**Comment by kikotheexile** [comment]
Whatever.
