### ISSUE TITLE
Need a way to differentiate aborting a mission from failing it

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#4018]
The `Syndicate target practice` jobs fine you if you destroy the ship instead of disabling it, implemented with a negative payment in the `on fail` block.

But this also triggers if you abort the mission, which isn't appropriate. We need some way of allowing you to abort a mission without it technically counting as having failed.

**Comment by jafdy** [comment]
An `on abort` block that would default to `on fail` block if absent?

**Comment by Joeppie** [comment]
It should probably also be noted that the 'target practice' mission pays for example  20.000 credits for success, whereas capturing the ship and selling it nets me 110.000+ credits. (This was on the Steam version)

**Comment by Amazinite** [comment]
The ship now self destructs when you try to capture it.

**Comment by Joeppie** [comment]
@Amazinite Indeed! I just tried a similar mission, nasty self-destruct mechanisms!. Then again, of course the syndicate needs to protect its technological advancements from snooping privateers.

**Comment by Fzzr** [comment]
This came up again, with another couple of related suggestions:
1. Add new flags to the save file based on failing or aborting missions, `: failed` and `: aborted`
2. Add the ability to `complete` one mission from another
3. Add the ability to `abort` a mission (that one or another) from within a conversation etc.

Basically, promote `abort` and `fail` to have the same capabilities as `complete`.

cc: @Zitchas
