### ISSUE TITLE
New race: Scavengers

### ISSUE THREAD

**Issue by ThatAtom** [endless-sky/endless-sky#4020]
I had this idea of a new group that are made up of humans and all types of aliens who turned against their species. They could own a couple of systems. And to survive they scavenge for ships/outfits/commodities. In their shipyards/outfitters there could be a randomly selected ship/outfit that they have in the shipyard/outfitters (because they scavenged for the outfit/ship). But there will be a limited number of outfits/ships stock that they have, to make it fair. This seems a bit unbalanced and I don't think it will get into the game but tell me what you think.

**Comment by Amazinite** [comment]
See #429, #482, and #1656. Discussion about creating new faction should occur somewhere else like on a forum, not on the GitHub issues page that is for tracking bugs and feature requests.

Also, I think you kinda just described the exiled Korath except with more diversity.
