### ISSUE TITLE
Show government name of a planet when different from system's government

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4022]
**Describe the bug**
When a planet's government is different from the system's government, the map screen doesn't indicate that.

**To Reproduce**
1. Go to the map screen
2. Click on Tarazed
3. Observe that there's no indication that Echo belongs to the Quarg

**Expected behavior**
The indication would be useful, especially if events changed a planet's government while the player is in another system.

**Screenshots**
![screenshot_2018-11-21_04-26-16](https://user-images.githubusercontent.com/24784687/48818967-9d287200-ed45-11e8-943d-32b177e3044f.png)

**System (please complete the following information):**
Current master

**Additional context**
Was previously submitted as PR #3768. That PR was closed for UI reasons, but the problem hasn't been fixed, so I'm resubmitting (with @Pointedstick 's blessing) in the hope that another solution will be found.

**Comment by Amazinite** [comment]
I don’t necessarily see how this is a problem. The fact that a landable object has a different government than the system isn’t massively important information that we’re missing out on with the current UI.

**Comment by MCOfficer** [comment]
Unless I missed something and the "Friendly" isn't reliable, there's no misinformation here, so it's not a huge problem. Still, I don't see anything going against it either, except perhaps the UI getting too crowded.

**Comment by Tadrix** [comment]
The window might be too small for this, but putting the name of differing government in parentheses after relations might work. In Echo's case, `Friendly (Quarg)`.

**Comment by endless-sky** [comment]
I really don't see the point of this. The government of a planet *is* shown when you're flying past it, and whether or not you can land on a planet (i.e. the "friendly" status) is generally the only information you're interested in.

**Comment by jostephd** [comment]
For whatever they're worth, the counter-arguments are:

- The presence of the label "Republic" under "Tarazed" implies that all planets in that system are owned by the Republic. It's not just _missing_ information, it's (implied) _wrong_ information
- Help orient the player. A new player might not remember what Echo's government was. ("I remember there was this system with both Quarg and Human planets that had a good shipyard...")
- Events may change a government when the player is in another system
- A mission might use `government` filters in stopover or destination, though none of the missions in mainline do this. (The "Visit the Quarg" missions use `destination Lagrange`.)

I don't mean to be argumentative, just to make my case. If you still think this should be closed, go ahead and do so without further ado, I won't be offended. (I _am_ frustrated, however, since this wouldn't the first sensible proposal to be shot down.)

@Tadrix That was discussed on #3768.

**Comment by tehhowch** [comment]
As i mentioned in #3768, a tooltip may be the simplest way to show this "extra" information about the given planetoids in the system.

**Comment by Amazinite** [comment]
>The presence of the label "Republic" under "Tarazed" implies that all planets in that system are owned by the Republic. It's not just missing information, it's (implied) wrong information

To me, that implies that the system itself is governed by the Republic, not necessarily that all planets within it are aligned as such.

> A new player might not remember what Echo's government was.

For what reason would this need to be known?

>Events may change a government when the player is in another system

In all likelihood, if a planet's government is changed to something other than the system *and* this is something the player *needs* to know, a mission would let them know.

I think a tooltip would be a great solution to this, but I still don't see why it's necessary.

**Comment by Nescio0** [comment]
Let's take a step back and ask ourselves a different but related question: does it make sense for *systems* to have a government?

**Comment by jostephd** [comment]
@Nescio0 The government of a system is used by Fleet::Enter to choose which system a fleet will jump from:

https://github.com/endless-sky/endless-sky/blob/fb0ab47540be60fa4c5bf0b4390dfbb5630cde81/source/Fleet.cpp#L163-L178

and by raiding parties:

https://github.com/endless-sky/endless-sky/blob/fb0ab47540be60fa4c5bf0b4390dfbb5630cde81/source/Engine.cpp#L1105-L1119

and by LocationFilters:

https://github.com/endless-sky/endless-sky/blob/fb0ab47540be60fa4c5bf0b4390dfbb5630cde81/source/LocationFilter.cpp#L270-L277

**Comment by jostephd** [comment]
Merging @Hurleveur's #6355 / #2230 would open new ways to solve this, e.g., by adding a line `Quarg outpost` above the Friendly/Shipyard/Outfitter lines.
