### ISSUE TITLE
Added 152 mission payloads...

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#403]
... to enhance the variety of trade missions. I've enlarged almost all the categories, some more than others, based on my real world experiences. I'm out of my depth on Heavy Metals, so I left those alone.

This is my first post here -- hopefully, if you approve, my first contribution to the game.
[expanded_commodities.txt](https://github.com/endless-sky/endless-sky/files/53798/expanded_commodities.txt)

(I think this should be marked as Enhancement but I'm not sure how to do that.)

**Comment by Wrzlprnft** [comment]
i think only @endless-sky himself can add labels.
You should open maybe a pull request, since it is a finished idea
In case you don't know how to do that:
Github basics: https://www.youtube.com/watch?v=0fKg7e37bQE
Pull requests and stuff: https://www.youtube.com/watch?v=oFYyTZwMyAg
I think these are quite good videos, about pull requests, watch the second one, in case you get confused (as i got while watching it the 1st time) watch the 1st one too

**Comment by anonybosch** [comment]
I appreciate the timely reply. Tried watching both vids but they started giving me a headache. It would take me years to understand and even longer to learn to write in gibberish. (No offense meant to you code jockies for whom this dead simple.) 
I've spent my life building things in 3D, often with my bare hands. I've never in my life had a job that entailed sitting at a desk, working from a keyboard. Hell, I've hardly ever even worked indoors. 

Appearances to the contrary, I can hardly type, or read quickly. These limitations do however make me an excellent proofreader. (More on that later once this file is approved or rejected.)

Having worked in the building trades (among many other metiers), I've encountered my fair share of architects, for whom I was their engineer, and was tasked with implementing their designs.

In all humility, please consider me the architect and the above file my blueprint. Now, hopefully, it's up to you code engineers to make it happen.

**Comment by guillochon** [comment]
@anonybosch You don't have to download anything to just modify a text file, you can do it directly from GitHub's website. Go to the file directly (https://github.com/endless-sky/endless-sky/blob/master/data/commodities.txt) and click the pencil icon in the upper right, it will create a fork of the repository for you. Then, paste in your new commodities.txt and save. It will be submitted as a pull request which @endless-sky can implement if he so chooses.

**Comment by Wrzlprnft** [comment]
I honestly didn't think of that easy version :/
It seems to happen more often in my life that i don't see easy solutions

**Comment by anonybosch** [comment]
Thank you, guillochon. I'll attempt that in a new tab so I can read your instructions several times.

**Comment by anonybosch** [comment]
Oh! Wait. It's been done. Thank you, Dev.

**Comment by guillochon** [comment]
@anonybosch I don't think that it has been done, there's no commit or pull request with your changes. All  that has happened so far is that @endless-sky tagged your issue.

**Comment by Wrzlprnft** [comment]
Step 1: Click on @guillochon's link
<img width="882" alt="step1" src="https://cloud.githubusercontent.com/assets/15857993/11628887/11f4dabe-9cf5-11e5-983d-185f56d872d6.png">
Step 2: Click on the little pencil
<img width="917" alt="step2" src="https://cloud.githubusercontent.com/assets/15857993/11628886/11f47452-9cf5-11e5-9ed6-fd91d49b725f.png">
Step 3: replace the text in there with the commodities you wrote
<img width="897" alt="step3" src="https://cloud.githubusercontent.com/assets/15857993/11628890/11f8a4f0-9cf5-11e5-9f4b-3372818664ad.png">
Step 4: give it a title and optional a description
<img width="846" alt="step4" src="https://cloud.githubusercontent.com/assets/15857993/11628889/11f62b3a-9cf5-11e5-8e8e-d22bb0e26589.png">
Step 5: Commit the suggested change
<img width="846" alt="step5" src="https://cloud.githubusercontent.com/assets/15857993/11628888/11f6245a-9cf5-11e5-8bfa-ae850dbb9854.png">

**Comment by anonybosch** [comment]
What if I don't want to remove the changes already made, (the pink text)? They're pretty good and can only further enhance the variety of goodies to be shipped.

**Comment by Wrzlprnft** [comment]
then don't replace it, just add the stuff you made

**Comment by anonybosch** [comment]
But I'm leery of creating the pull request because it says 152 additions and 110 deletions. I'm not going to delete those if I create the pull request, am I?

**Comment by guillochon** [comment]
It's called a pull *request*, not a pull demand. :-)

You can continue to make edits to it before it is merged if you accidentally mess something up, so you shouldn't worry too much about that. It is ultimately up to @endless-sky to merge, he will only do so if the PR is in working order.

**Comment by anonybosch** [comment]
OK. Thanks. I'll try it.

**Comment by Pointedstick** [comment]
The deletions are probably the commodities I already added: https://github.com/endless-sky/endless-sky/pull/335. I bet your pull request was based off of the latest released version that didn't include those changes, not the current state of the world (which does includes my changes).

**Comment by Pointedstick** [comment]
There are a couple of typos:
shitaki -> shittake
extention -> extension
oxigen -> oxygen
telescpoes -> telescopes
colomators -> collimators
And Tungsten is really more of a heavy metal (I already added it there in my changes). And some are maybe a bit esoteric and difficult to imagine what they might be, like xylene, dacron, assorted shimstock, and monel.

Other than that, I like these changes!

**Comment by anonybosch** [comment]
Thanks for catching my typos. I was very tired, and spent a long time assembling my list. Should have gone to bed sooner.

I'm glad the above left some wonderment. That was the idea. Imagine the player's first-time puzzlement hauling monel. Perhaps it might encourage the occasional player to crack open a Google and learn something. But also imagine the player who knows that monel is a very expensive metal, that initially appears to be stainless steel, and is used among other things, to build sailboats because of its high anti-corrosion qualities, and cracks a smile. "Wow! Somebody's building a very cool boat, maybe."
Dacron is a synthetic fiber used to make sails... today. Who knows what there will be then to replace it, but the rest of the list is mostly anachronistic, why don't we just play along.
Xylene is an epoxy solvent. (I misspelled it.) So much for being a great proofreader, huh.
Shimstock is a generic term used by machinists, steamfitters and boilermakers for material used to level heavy machinery that needs to bear perfectly on the pad where it's being installed so as to reduce vibration to tolerable limits.

**Comment by guillochon** [comment]
Hey all, since @anonybosch was having some trouble, and also because he used an older version of commodities.txt to start with, I've gone ahead and merged his changes manually via this PR: https://github.com/endless-sky/endless-sky/pull/410

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
