### ISSUE TITLE
Coalition Small & Large Ramscoop Module

### ISSUE THREAD

**Issue by 10010101001** [endless-sky/endless-sky#4044]
This tries to fix how the Wanderer ramscoop is objectively the best ramscoop in the game. It adds the Small Ramscoop Module:
![smallramscoop](https://user-images.githubusercontent.com/44052322/49284094-aa80f180-f4e7-11e8-96f7-bfce62215401.png)

outfit "Small Ramscoop Module"
	category "Systems"
	licenses
		"Coalition"
	cost 120000
	thumbnail "outfit/small ramscoop"
	"mass" 2
	"outfit space" -2
	"ramscoop" 1
	description "This ramscoop is extremely compact and is used to function as a back up in case a Coalition ship gets stranded in an empty system."

And the Large Ramscoop Module:

outfit "Large Ramscoop Module"
	category "Systems"
	licenses
		"Coalition"
	cost 480000
	thumbnail "outfit/large ramscoop"
	"mass" 6
	"outfit space" -6
	"ramscoop" 4
	"energy consumption" 6
	description "This is a larger ramscoop design. Instead of passively collecting fuel, this ramscoop instead use electromagnets to attract the solar fuel. As a result, it is much more space-efficient."

**Comment by Nescio0** [comment]
* Why is it a problem the Wanderer ramscoop is currently the best?
* Does every species need to have a ramscoop?
* How does this improve the game?
* Why did you post this as an issue and not a pull request?
* Where are the thumbnails?

**Comment by jafdy** [comment]
When ramscoops have 2 main numbers, `ramscoop` and `mass`, there isn't a whole lot to differentiate them. Adding another ramscoop doesn't really add much in terms of choice, there will always be a best choice for nearly every build, and it is unlikely to be a toss up in the remaining cases anyway. (Not to mention that the Coalition is a particularly bad choice of source.)

**Comment by Pointedstick** [comment]
You could have a ramscoop that has a constant energy draw or heat output I suppose. Or we could add new `ramscoop energy` etc. stats.

But yeah, @1001010100, if you're serious about this, it needs to be in the form of a PR, not an issue. And that sprite could use a bit of texturing, and coloration, and griminess.

**Comment by Brick63** [comment]
It needs paint

**Comment by 10010101001** [comment]
> You could have a ramscoop that has a constant energy draw or heat output I suppose. Or we could add new `ramscoop energy` etc. stats.
> 
> But yeah, @1001010100, if you're serious about this, it needs to be in the form of a PR, not an issue. And that sprite could use a bit of texturing, and coloration, and griminess.
The Large ramscoop does have a constant energy draw.
Also, I don't have permission to create a PR.
