### ISSUE TITLE
WIP: New main story line. The Duchy

### ISSUE THREAD

**Issue by Isaac-P** [endless-sky/endless-sky#4048]
I'm working on creating a new human faction as a new main plot line.
The basics are that a formally independent planet used to make money as mercenaries (think the Grey Geese from EV) by having the biggest ships pre-republic. But with the increase in shield and engine tech their big heavy slow ships were destroyed during the wars and they were left near bankrupt and haven't built or even upgraded a ship in 200 years and is currently just another asteroid mining colony.
However the old shipyard is still floating in space, hidden inside a large asteroid and it contains the drydocked 350 year old super dreadnought "The Iron Duke" which is armed with a massive railgun that can crack a moon like an egg (but steers like a drunk cow riding a 3 wheeled shopping trolley).

The player helps the new faction by initially doing trade and supply jobs to help build the economy and then helps to supply tech and resources to upgrade old ships and build new designs and gains access to some of the new ship and outfit designs (The super dreadnought will probably only be available for certain missions as it's not like anyone would really let you go joyriding in their flagship regardless of how much they liked you).
There will be a plot split where the new faction must decide of they will remain with the republic or regain their previous independence.

I am having problems finding resources and information in the wiki for lore and how to build certain things, like a list of planet attributes, and how can I build a weapon into a ship so it can't be uninstalled and/or sold?

Or even of this post is in the right spot?

**Comment by jafdy** [comment]
For this kind of discussion is best suited to the [discord](https://discord.gg/ZeuASSx), [google groups](https://groups.google.com/forum/#!categories/endless-sky) or [steam](https://steamcommunity.com/app/404410/discussions/).
GitHub is the active development environment and so is for bug report, fleshed out feature request or (better yet) fully featured stories.

**Comment by Pointedstick** [comment]
Yep, please take it one of those venues. The issue tracker is for bugs and feature requests, not content brainstorming.

**Comment by Zitchas** [comment]
That being said, the github wiki has a lot of the technical information you'll need

https://github.com/endless-sky/endless-sky/wiki/CreatingMissions

There is very little in the way of formal lore (let along a lore wiki. It'd be nice, but hasn't happened yet)
