### ISSUE TITLE
Planet and Star proportioning

### ISSUE THREAD

**Issue by TechnoNinja64** [endless-sky/endless-sky#4049]
I came across the while messing around and trying to find the size of a pixel, that depending on what method you use, the results can vary.. Quite a lot

> Size of a pixel
70km (Diameter earth as point of reference)
154,916km (Astronomical unit as point of reference)
15,456km (Diameter of sun as point reference)

Then as it turns out, Jupiter is larger than the sun

...And the sparrow is 12,393,280 km or 5,600 km on one side.
(Yes, I know the ships are on a higher Z level than the planets)

My idea is to make the planets and stars a bit more proportional to each other
(At least make the stars larger than gas planets)
Make the sun proportional to Earth and the size of the planets in the solar system, and such.
The ships can be left alone, since if they are further away from the planets and stars.
The proportions of orbits could also be improved.

But this could bring another whole problem, of the stars being too large, and ships being able to fly 'in' a star might not look very good, navigating to planets further out would presumably take much longer.

This would also add a large amount of work, since changing nearly every system would take quite a long time.

Since this is a game, I doubt it needs this feature, but putting it out there, in case it does.

**Comment by DingusShingleton** [comment]
Well keep in mind also that the Stars and planets can also be on different z levels. There's no reason to think that they are all on the same exact plane

**Comment by Amazinite** [comment]
If ever we change the scale of systems a la what was suggested in #4039 then I wouldn’t see an issue with scaling planets and stars more proportionally, but even right now the planets aren’t scaled proportionally to one another and the size of planets and stars isn’t important to gameplay, so I don’t see this as being something we’d need to do.

**Comment by Nescio0** [comment]
Proportionality is not going to work when astronomical distances are involved. 
E.g. the Earth's mean radius is 6371 km. The average distance from the Sun to Earth is 1 AU, about 150 million km, over 23 million Earth radii. The Sun's mean radius is about a hundred Earth radii, but so-called red giants (not uncommon) can have radii over a hundred times the Sun's, thus more than ten thousand Earth radii. Red super-giants such as Betelgeuse can be ten times as large. And so on.

**Comment by MCOfficer** [comment]
the way i see ES's systems is that the sun is far, far in the background, and the planets are close the plane that is my screen - similar to a sinkhole, with the sun in the middle. that also explains why you're not being roasted alive when hovering over the sun.

ofc that model doesn't hold upon a closer examination, but as Nescio said, making systems proportional would be insanity - so i guess this is, once again, a "fun over realism".

**Comment by TechnoNinja64** [comment]
I agree, I'm just more putting the idea out there. Since if you take how every system orbits, the stars must be quite far from the planets... Which, would stuff up orbit completely (If it was in real life of course).
If you were to "expand" The Layers, you would see something like, ships high up, with asteroids, a few thousand km later there would be the planets, then a few million km later the stars. Making the Planets orbit around nothing?
