### ISSUE TITLE
Typos (2)

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#405]
Conversation on Big Sky/Sarin with "Young man":

Reply 3.) "Do your really think..." change to > "Do you really think..."

Planet description: Han: "Settlers have build farming..." change "build" to "built"

**Comment by Wrzlprnft** [comment]
Haven't found the other one yet

**Comment by Wrzlprnft** [comment]
Fixed in #406

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
