### ISSUE TITLE
Shady Passenger Transport 2 -- can complete mission after getting caught

### ISSUE THREAD

**Issue by DrBlight** [endless-sky/endless-sky#4057]
**Describe the bug**
I picked up two shady guys in Syndicate space, then was caught by the Syndicate when I landed on a world. I paid off my 150k credit fine, then continued on my way. When I landed on the destination world, the shady guys got off my ship, paid me my 100k, and left! Weren't they supposed to be arrested?

**To Reproduce**
1. Accept "Shady Passenger Transport 2" mission
2. Land somewhere and get caught and fined by the authorities
3. Pay off fine in full before leaving the planet
4. Land on the original destination world and receive a completion of the mission with payment

**Expected behavior**
The mission should have disappeared completely as soon as the shady passengers are arrested and the fine is implemented.

**System (please complete the following information):**
 - OS: Kubuntu 18.04
 - Game Source: self-compiled
 - Version: current git master as of today

**Link to save file**
[Delaney Truffault.txt](https://github.com/endless-sky/endless-sky/files/2661085/Delaney.Truffault.txt)

**Comment by Amazinite** [comment]
The save file you linked doesn't currently have the mission active. Are you sure it wasn't shady passenger transport 1, as it seems that that mission is currently missing the `stealth` tag required to actually make it fail with you get scanned.

@Pointedstick
