### ISSUE TITLE
Shady passenger transport 3 - double cross (bribed them but didn't lose credits)

### ISSUE THREAD

**Issue by DrBlight** [endless-sky/endless-sky#4058]
**Describe the bug**
I let a bunch of gangsters hitch a ride on my ship, and they tried to steal it. I successfully bribed my way out of the problem, but no credits were removed from my total.

**To Reproduce**
1. Complete shady passenger jobs until you get the job to transport a large group of them.
2. They'll try to take over your ship in a special event. Bribe them until they agree to leave.
3. No money is lost! Profit???

**Expected behavior**
I had over 10 million credits and agreed to give them eight. I thought the money would disappear from my total, but it did not.

**System (please complete the following information):**
 - OS: Kubuntu 18.04
 - Game Source: self-compiled
 - Version: current git master as of today

**Link to save file**
[Delaney Truffault.txt](https://github.com/endless-sky/endless-sky/files/2661109/Delaney.Truffault.txt)

**Comment by Amazinite** [comment]
I see the issue; the negative payment should be in an `on fail` block, not an `on defer` block, as `on defer` is never actually triggered given that conversation endpoints don't do anything in the `on enter` block other than simply end the conversation. Although that then ties into the issue of #4018 where there's no way to distinguish between failing a mission (in this case failing by bribing the mercenaries) and aborting a mission (which hopefully shouldn't be much of a problem for this mission for the time being seeing as how the mission is failed by bribing them *right* when you launch from the planet, meaning the only time to abort the mission is directly after taking it from the job board).

@Pointedstick
