### ISSUE TITLE
Helping spaceships do not recharge your batteries

### ISSUE THREAD

**Issue by ghost** [endless-sky/endless-sky#4065]
I am trying to optimize my Star Barge.
I have noticed that most of the time I do not need a fuel cell - the battery provides enough energy for travel between planets.
However if I do run out of power mid-flight then I am left completely stranded in space with no-one to help me.
I do not think this should be the case.

**Comment by Pointedstick** [comment]
+1 on recharging batteries when assisted, if empty.

As a workaround, you can mount a 3-ton solar panel, which will slowly recharge your drained batteries.

**Comment by Nescio0** [comment]
> That being said, 200 energy would probably be a fairly reasonable amount.

Not all ships have equally powerful energy generators. So instead of a fixed amount of energy, perhaps grant e.g. 1 second worth of energy generated by the rescue ship?

**Comment by TheGiraffe3** [comment]
Will this be implemented, or should it be closed?

**Comment by tibetiroka** [comment]
I don't see any reason to close this issue.

I might actually implement this.

**Comment by TheGiraffe3** [comment]
Trying to cut down on the number of open issues.
