### ISSUE TITLE
Post FW quests with chatacters

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#4066]
Just an idea i had a while back, but it would be cool to have some small-ish quests to do  sith some of the characters from the FW campaign. These could range from slightly higher paying cargo/transport with some lire on what tgey were up to after the war yo auashing a pirate insurgence on the behalf of the FW., or even ynlocking dome new tech or expanding tge selection of weapons and other outfits sold in FW space.

Thoughts? These could also tie into the events of the wanderer storyline and the storylines of the navy or syndaxate once those come out.

**Comment by Pointedstick** [comment]
This kind of stream-of-consciousness idea is better expressed in the form of a post on a forum or Discord, or a pull request (hint hint :) ).
