### ISSUE TITLE
"You paid 1 credits"

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4068]
![image](https://user-images.githubusercontent.com/17688683/50038017-ba6bfb80-ffe6-11e8-91b2-5db4f6e604a9.png)

Should be "1 credit".

**Comment by tehhowch** [comment]
So the desired strings are like:
```
"You paid 1 credit in mortgage payments and 1,234 in fines."
"You paid 1 credit in fines."
```
or are we also wanting to insert the plural `credits` before fines:
```
"You paid 1 credit in mortgage payments and 1,234 credits in fines."
```
Current behavior is for `credits` to only appear once in the payment message.

(Crew salaries can only be 0 or >= 100 credits)

**Comment by tehhowch** [comment]
Fixed by https://github.com/endless-sky/endless-sky/commit/888da5bb4547c05bdeb8df08ffaf645dea6b403e
