### ISSUE TITLE
In mission "Hai Honeymoon", Anaya addresses you as "he."

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#4076]
**Describe the bug**
In mission "Hai Honeymoon", Anaya addresses you as "he."

>                        `       "At least he's trying, Touhar," the woman says.`

**Expected behavior**
"You" should be gender neutral.

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/1d723e2ee30c79a2127e855a83384b801c7e92cf.

**Comment by oo13** [comment]
Thanks!
