### ISSUE TITLE
Sparrow start with new missile changes

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4077]
**Describe the bug**
In `Intro [1 Interceptor]`, it may be too easy for new players to get killed by Meteors.

**To Reproduce**
1. Start a new game
2. Buy a Sparrow
3. Accept the initial James mission in New Boston, do one jump northwest, land, go to the spaceport, accept the next James mission (escorting two Freigthers)
4. Try to complete it

The mission's Fury can fairly easily disable or even kill the player at this point. I was able to hide in the Freighter's anti-missile radius, disable the pirates with allies' help, loot the the pirates, and complete the mission... or at least, I _almost_ completed the mission, but after I completed the final jump I was killed by another Meteor Fury. That one must have been a pirate from the random ambient fleets, because I'd already disabled the two enemies spawned by the mission:

https://github.com/endless-sky/endless-sky/blob/1d723e2ee30c79a2127e855a83384b801c7e92cf/data/intro%20missions.txt#L327-L331

**Expected behavior**
I think the mission might be too hard for new players... but then again, the Interceptor start isn't supposed to be easy, so I don't know if any changes are needed at all. Maybe it's fine as is, or maybe it should be rebalanced. I'm not sure, so I opened this issue to ask. I asked on Discord before asking here.

**System (please complete the following information):**
 - OS: Linux
 - Game Source: self-compiled
 - Version: 560155a9b84ffae7801edb19da0a23bdfe6a6686

**Comment by Ferociousfeind** [comment]
This should from now on be the only way people are allowed to PR tweaks.

**Comment by Nescio0** [comment]
When I chose a Sparrow, I first sold all weapons and installed additional fuel pods instead. (If a ship is unarmed, hostile ships prefer to target other ships first.) The intro missions and later escort jobs are quite easy if you simply ignore everything, send your flagship to the destination system as quickly as possible, drift away, wait for all escorts to arrive, and only then order to land.

**Comment by Wrzlprnft** [comment]
Though, Nescio, i don't think that's your average new player experience.

**Comment by jostephd** [comment]
New players are unlikely to play Nescio's strategy because James explicitly warns the player not to do that:

https://github.com/endless-sky/endless-sky/blob/22e26cc2c5fa700401a9c42db5f1710cbcd76fea/data/intro%20missions.txt#L340

The fact that it works at all is arguably a [bug](#715).

**Comment by Pointedstick** [comment]
On first glance, we could perhaps make one of the ships an exclusively gun-armed variant, or substitute a ship with only short-range missiles like Javelins, such as Berserker.

Do you have any suggestions?

**Comment by Amazinite** [comment]
I might simply be speaking for a position of greater experience/skill, but I haven’t found fighting against meteor missiles very difficult when I’m in a small ship. It’s mainly a matter of getting a handle on dodging the missiles, which isn’t too difficult with their low turn radii. 

>I was able to hide in the Freighter's anti-missile radius

That sounds like a solid strategy to dealing with missiles early on when you yourself don’t have any AM defenses, but as you said, it wasn’t specifically the mission NPCs that got you, but a random fleet. I think that concerns all small ships more than it does just the Sparrow start. If anything, the Sparrow is the best equipped to deal with such a scenario compared to the other two starter ships given its speed. 

When it comes to tweaking the changes that we’re made to missiles, I’m wondering if we should wait until v0.9.9 is out and we have a large pool of people to get feedback from. v0.9.9 will be considered unstable after all, so no shame in balance being a little off.

**Comment by Quantumshark** [comment]
As far as I'm aware, this is no longer an issue.
Between the changes to missiles since this issue was opened, and the mass rebalance, which made the sparrow (and other small ships) considerably faster, meteors no longer pose a credible threat to a stock Sparrow.
