### ISSUE TITLE
Add Buy/Sell buttons to the commodities in map view

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#408]
Having to go to the map from trading, then back out to buy/sell is a bit inefficient.

All that needs to be done is to add [buy] and [sell] next to each commodity listed in map view. A simple fix that makes the early game grind just that little bit easier.

This is just an idea, I leave it up to others to implement, since I can't.

**Comment by brick96** [comment]
Agreed. Also I noticed selecting a commodity in the trade window highlights it in the map, but not vice versa

**Comment by Wrzlprnft** [comment]
I would prefer not to, because then the feeling to really land on a planet and have access to the market gets lost

**Comment by anonybosch** [comment]
Buy/Sell buttons would lead to "how much"? Then, I think, it gets complicated.

But once you get used to where and what the existing buttons do, it becomes clear that the map is quite complicated and very functional. (You can't tell what the price spreads are from the trading floor. But you can make your evaluations on the map, and return to place your buy/sell orders.)

**Comment by brendanjones** [comment]
> I would prefer not to, because then the feeling to really land on a planet and have access to the market gets lost, but that's just my opinion
> - Wrzlprnft 

You'd still have to land on the planet to buy/sell, so how would the feeling of having access to the market be lost? It'd be just like missions - you have to land to get missions, and clicking on the Jobs menu takes you to the map - you have to land to trade, and clicking on the Trading button takes you to the map.

> Buy/Sell buttons would lead to "how much"? Then, I think, it gets complicated.
> - anonybosch

Complicated aesthetically, or...? 

Excuse my quick copy+paste job, but here's essentially what it would look like:

![screen shot 2015-12-08 at 10 28 57 am](https://cloud.githubusercontent.com/assets/16049594/11652243/f81d6fa0-9d96-11e5-9dc1-8b0b783b93ca.png)

I'll agree the trading buttons stick out into the map quite a bit, but it's no worse than the Missions overlay on the map. Compare:

![screen shot 2015-12-08 at 10 33 44 am](https://cloud.githubusercontent.com/assets/16049594/11652316/45803f70-9d97-11e5-8b7b-673c0cf1f4b7.png)

**Comment by anonybosch** [comment]
Brendan, I only meant complicated in the sense that you'd still have to use all the keystroke shortcuts to execute a trade. Unless I'm mistaken, there might be ambient sounds accompanying the various panels on the planetside of the game. If that's the case, then going from scene to scene (trade/job/spaceport/hiring(?) would liven up the drudgery of the trading aspect. No? 
(Shipyard/Outfitter sounds too, but I digress.)

How about... a [Trade] button at the bottom of the map that would take you directly back to the Trade "room" panel? That would be helpful. As it stands, leaving the map is accomplished by using the [Done] button, or the D or M keys. But these 2 escapes only take you directly to the main planet window. A [Trade] button would take you directly to the trading floor.

**Comment by brendanjones** [comment]
Sure, this change wouldn't fix needing to use the keyboard shortcuts, no.

> But these 2 escapes only take you directly to the main planet window. 

Actually, if you were already in the Trading window, then go to map, then select Done, you will go back to the Trading, not the main window.

You're right about the ambient sounds livening things up a bit by making it feel like you're 'exploring' a planet when you move from from area to another. Maybe you could play the trading ambient sound in the map window? Not that that sounds like good implementation to me...

**Comment by anonybosch** [comment]
If sound was added to the map window, I'd like it to be similar to the hushed murmurs one might expect in a CIC (Combat Information Center), or a shipboard chart room.
-----Actually, if you were already in the Trading window, then go to map, then select Done, you will go back to the Trading, not the main window.
That must have slipped past me.

**Comment by endless-sky** [comment]
Rather than making the map sidebar much wider to accommodate all the buttons from the trading panel, an alternative might just be to allow the map to support the buy and sell keyboard shortcuts plus the modifier keys. (It would still need to be expanded to show the amount in your hold, though.)

**Comment by brendanjones** [comment]
Good idea. Another implementation could be to have the trading box collapsed by default so it looks like this (then when you click 'expand', it looks like the pic I posted above). This saves map space, and there's less complexity on the map for new players to come to grips with, but the functionality is there for anyone who wants it. Could be a game preference to have the trading box expanded by default, for those players who like the feature on the map:

![screen shot 2015-12-09 at 11 08 42 am](https://cloud.githubusercontent.com/assets/16049594/11683244/f03bbf2a-9e69-11e5-8e37-d6e3d864e335.png)

**Comment by frameworld** [comment]
what if you could select a route and buy/sell just the best commodities for that route directly?

If it would be a horizontal bar at top or bottom, it wouldn't take up too much space if you would just buy/sell the best one.

**Comment by brendanjones** [comment]
> what if you could select a route and buy/sell just the best commodities for that route directly?

That makes trading even more brainless than it already is. You should have to expend a little bit of effort in working out what is most profitable for yourself, I think.

**Comment by frameworld** [comment]
True, but I would rather have to think about routes than to have to check which element of a list is the highest every time.
The interesting part are things that don't repeat or where you couldn't just write a code-gadget for it out of your mind.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
