### ISSUE TITLE
Reactors consume fuel

### ISSUE THREAD

**Issue by 10010101001** [endless-sky/endless-sky#4080]
Small reactors (60 > ) consume 5 fuel per second
Medium reactors (60-120) consume 10
Large reactors (120 < ) consume 15
Fuel cells consume 0.5-2 fuel per second depending on size.
This will stop reactors from being the go-to power generator and instead encourages people to use both fuel cells, reactors and solar power.

**Comment by jafdy** [comment]
This would be an almost guaranteed way to get many people (new and experienced) stranded, it would also require a complete overhaul of the current fuel mechanics as fuel would now be used for more than just jumping (and the occasional afterburner or flamethrower).
Also, nuclear reactors are refuelled about every 1 to 1.5 years (the current world record is 739 days). Although this takes a month we can safely enough assume that in 1000 years time reactors will A) last longer between refuelling and B) be refuelled quicker.
I guess I'll talk about fuel cells now. Fuel cells are probably the hydrogen-oxygen sort, maybe some other kind but I doubt they use the `nuclear fusion reaction powerful enough to level an entire city` type of fuel. Or maybe that's just me.

**Comment by Pointedstick** [comment]
As mentioned, this idea is not necessarily realistic. These days, naval nuclear reactors are designed with their entire lifetime's supply of fuel built in; they never need to be refueled. Once they reach the end of their fuel capacity, the whole ship is scrapped and replaced with a new one.

While the idea itself is interesting, it would require a *lot* of other changes and testing. Not sure it's worth doing, sorry!
