### ISSUE TITLE
Laser Turret sprite is incorrect

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#4081]
Let's compare the laser turret and heavy laser turret images:

* projectiles:
![2x laser 0](https://user-images.githubusercontent.com/21634324/50153841-df52be00-02c7-11e9-9785-e0eab9d50698.png)
![2x heavy laser 0](https://user-images.githubusercontent.com/21634324/50153851-e2e64500-02c7-11e9-873c-316906c7f10d.png)
* hardpoints:
![laser turret](https://user-images.githubusercontent.com/21634324/50153871-f396bb00-02c7-11e9-92ee-7b1e61555cb8.png)
![heavy laser turret](https://user-images.githubusercontent.com/21634324/50153881-f8f40580-02c7-11e9-9698-d43325d43d93.png)
* outfit thumbnails:
![laser turret](https://user-images.githubusercontent.com/21634324/50153900-0c9f6c00-02c8-11e9-94fb-1ad4fa1a1003.png)
![heavy laser turret](https://user-images.githubusercontent.com/21634324/50153906-132de380-02c8-11e9-98d8-01f9cd046069.png)

As you can see the beam laser and heavy laser turret's projectiles are two parallel beams and the hardpoints of both clearly show the two cannons parallel to each other. The beam laser turret's outfit sprite, however, has the cannons mounted on top of each other, similar to the blaster turret. It ought to be parallel, similar to the heavy laser turret. It would be nice if someone could create a correct sprite.

**Comment by Brick63** [comment]
should be fixed in #4090
