### ISSUE TITLE
Losing control of the lead ship

### ISSUE THREAD

**Issue by Electrox18** [endless-sky/endless-sky#4096]
I put some better engines on my ship and when I departed from the outfitter, I lost total control of my ship and couldn't hyperspace, pilot it or land.
 OS: macOS Mojave 10.14
Steam
Version 0.9.8

**Comment by tehhowch** [comment]
Provide your save file and a list of installed mods. Sounds like you ran out of power.

**Comment by Pointedstick** [comment]
Also, very likely already fixed by fractional thrust in git master.

**Comment by Amazinite** [comment]
Closing because of a lack of information from OP.
