### ISSUE TITLE
Art upgrade/sidegrade for (human) ships

### ISSUE THREAD

**Issue by 8b8** [endless-sky/endless-sky#4097]
### tlwr: 

Created procedural cycles [texture](https://www.dropbox.com/s/706igoxckent3p5/_materials_human.blend?dl=0) for (human) ships + script to automatically [apply and render](https://www.dropbox.com/s/fxo59vwzkaa4rty/render.py?dl=0) most (human) [ships](https://www.dropbox.com/s/4nousr6ubb03cwb/render_all.py?dl=0). Please share your opinion on the [assets](https://www.dropbox.com/sh/a6k29u7wv3aea9j/AAC2_2FBFdI7Gt5u9Xn0hckSa?dl=0).

### Goals

The idea is to improve the visuals for ships in general, beginning with the human ships. They were presumably created first, and are a reminder how far the quality of the artwork has progressed. 

The two largest problems are imho, the hard edge, low-poly look they get from the lack of subdivisions as well as the lack of good materials on the 3d-models themselves.

### Work done so far

To improve this, I created a new procedural texture that adds a rivet/plating kind of surface detail without needing any new, real geometry. I also added a bevel and a subdivision surface modifier to make the edges "rounder". For the final touch I set up the compositing to add a little dirt to the crevices using the ambient occlusion pass.

On the bactrian this looks as follows (without manual postprocessing):
![bactrian](https://user-images.githubusercontent.com/27152901/50404343-079a5b00-07a7-11e9-8439-5da2737de7b9.png)
compared to the current in game model
![bactrian](https://user-images.githubusercontent.com/27152901/50404519-4af5c900-07a9-11e9-80e9-0b33289aecf5.png)

proposed 
![protector](https://user-images.githubusercontent.com/27152901/50405145-cdce5200-07b0-11e9-8177-7e5681afef56.png)

vs. in game
![protector](https://user-images.githubusercontent.com/27152901/50405146-d030ac00-07b0-11e9-9a34-ed7193e165e8.png)

These textures also look ok when rendered perspecitvely #3682
![berserkerpersp](https://user-images.githubusercontent.com/27152901/50404551-93ad8200-07a9-11e9-85c8-c29ffd5d3f08.png)

To do this automatically for each ship I created two small python scripts: [one](https://www.dropbox.com/s/fxo59vwzkaa4rty/render.py?dl=0) to be called with blender to make all the temporary adjustments and render the results, and [one](https://www.dropbox.com/s/4nousr6ubb03cwb/render_all.py?dl=) to do this for all (human) [ships](https://www.dropbox.com/sh/a6k29u7wv3aea9j/AAC2_2FBFdI7Gt5u9Xn0hckSa?dl=0). 

### Problems and future tasks

The largest issue here is the object level scaling of the different spaceship parts in the blender model. The texture is dependent on this scale and there is no easy way to reliably adjust this. Eventually I would really like to permanently change the blend files.

To improve and differentiate the human ships I would like to create material presets based on the shipyard they come from lore wise. Syndicate ships being sleek and clean, republic ships being plated and robust, dirt-belt ships being grimy and cluttered. Pirate ships being super cluttered and dirty. 

Also I would like to create a set of objects that can be emitted from the ship surface with the particle system to create clutter. The general direction (without the dirt) is 
![untitled4](https://user-images.githubusercontent.com/27152901/50404499-ef2b4000-07a8-11e9-8180-6ebc726bffd2.png)
The lights could be used as an in game indicator for ship status (lights on: keep firing, lights off: start boarding).

In general the drawbacks  are a substantial increase in render times due to the use of cycles, and the lack of post processing makes small individual final adjustments impossible. However it makes it easier to create a consistent "look" because the material can be controlled easily.

**Comment by Zitchas** [comment]
I like the looks of this. And creating an automated tool for doing it sounds useful too.

**Comment by Pointedstick** [comment]
Whooa, that looks excellent!!!

**Comment by DingusShingleton** [comment]
Yeah this looks totally awesome. That high res final bactrian is giving me spaceballs vibes where the ship just keeps on going XD. 

If there was a way to toggle off the resource intensive aspect for people with humbler systems I think this would be a must have

**Comment by Zitchas** [comment]
ES doesn't render anything in-game: All the ships are static images, so their relative complexity/simplicity doesn't have any impact on a player's system.  The absolute size of the image does, however.

**Comment by jafdy** [comment]
Lighting for ships is something I was working on a while back but my conclusion was that more code support would be needed before I could make it effective. Your idea of lights would take even more code support.

**Comment by 8b8** [comment]
Thank you for your positive feedback.

@jafdy If I understand you correctly you mean #3002. In this specific case I was simply thinking of 2 different sprites: one for a functional ship one for a disabled ship.

**Comment by tehhowch** [comment]
Support for sprites shown when disabled (or destroyed) might not be too difficult to add - one hard part is to provide clear and useful syntax.

E.g.

```
sprite "ship/aerie"
  disabled "ship/aerie (dark)"
  destroyed "ship/aerie (pieces)"
```

The mechanics of sprite selection would need a bit of double-checking (currently `Body` manages sprites for everything but only `Ship`s can be disabled); I haven't investigated this in-depth at the moment.

**Comment by jafdy** [comment]
Running lights, it was about a year and a half ago.

**Comment by Kryes-Omega** [comment]
I like the concept, my only concern is the glossiness of the ships. The bright reflections dont seem consistent with the grunge.

**Comment by Kryes-Omega** [comment]
Sorry for the double post, github won't let me edit on mobile.
If you're already using a procedural texture for the riveting/plates, I don't see why you don't just add a roughness map too.

**Comment by DingusShingleton** [comment]
(open in a browser and enable desktop mode to edit on mobile)

**Comment by 8b8** [comment]
@Kryes-Omega 
I understand what you mean and I honestly forgot about that. Probably because I wanted to match the existing assets at close as possible and set the reflection in a way not to be able to tell the difference when you zoom out far enough. Tweaking these parameters was kind of tedious. I should probably experiment with a roughness map, or (at the cost of an even bigger increase in render time) use the ambient occlusion node in provided by cycles or using the direct glossy lights pass.

The glossiness is somewhat difficult and my thoughts are as follows:
Most starship references from Star Treck, Star Wars, Galactica have very matte material (naboo cruiser being the exception). This is understandable, given the hassle to set up lighting with glossy materials, where the hdri would be mostly black, as they would reflect mostly black stuff. This makes those refernces look somewhat bland, however they make up for that by having lots of interesting surface geometry and texture detail (naboo cruiser being the exception). Given the fixed lighting, not having to reflect the (in game) background and the lack of intricate surface geometry, I thought that the general glossyness was a good decision in the original assets (comparing upper most and lower most bactrian).

@jady 
thanks for the reference.

**Comment by Naf5000** [comment]
I agree with Kryes-Omega: These ships are too glossy. But I think the material presets you've come up with might fix that; Your mock-up Bactrian redesign with the running lights looks considerably better than both the current sprite and your initial retextured one. You're definitely on to something good here, and there in particular.

**Comment by Nescio0** [comment]
(Somewhat related but separate comment.)

Currently every sprite has its own sun at a fixed angle. The advantage of this is that ship sprites look nice when viewing them individually. However, it also makes some symmetrical ships look asymmetrical (e.g. Star Queen, Vanguard), and when ships are moving around in space, it's a bit weird to observe their shadows rotating when the ships change direction.

Ideally lighting ought to be removed from the sprites. Realistically, about all light comes from the star(s) in the system's centre, and shadows should be generated based on there. However, I suppose that's quite complicated to code.

**Comment by 8b8** [comment]
I put the render scripts in a new repo under https://github.com/8b8/endless-sky_render

As per request I rerendered with less glossyness



![bactrian](https://user-images.githubusercontent.com/27152901/51558764-94a50280-1e80-11e9-855d-1ab7c4de40a6.png)
![protector](https://user-images.githubusercontent.com/27152901/51558778-9bcc1080-1e80-11e9-8c3a-9958df23cb98.png)


https://www.dropbox.com/sh/u917on9jqienmmw/AAAkDC7UOLywvMR9rT0qI1xEa?dl=0
https://www.dropbox.com/sh/vez282bi2s05mmf/AAB2gx9vL2qN13-gUt0w9yZka?dl=0

**Comment by 8b8** [comment]
Added images with light animation like the shuttle to a new branch https://github.com/8b8/endless-sky/tree/art_update_human_ships

When looking at the lights statically they might not look cool but in the animation they work quite well. However, several models still need fine tuning. 
[https://www.dropbox.com/s/tj7m6c930l33dm4/lights.gif?dl=1](animation)

Probably good:

![headhunter 0](https://user-images.githubusercontent.com/27152901/51785245-3ebcad00-2155-11e9-809d-b08be77fb928.png)
![headhunter 1](https://user-images.githubusercontent.com/27152901/51785246-3ebcad00-2155-11e9-86d4-3f496b747cb0.png)
![headhunter 2](https://user-images.githubusercontent.com/27152901/51785247-3ebcad00-2155-11e9-841c-c288894fb351.png)

meh:

![argosy 0](https://user-images.githubusercontent.com/27152901/51785258-5eec6c00-2155-11e9-859a-56e17d068078.png)
![argosy 1](https://user-images.githubusercontent.com/27152901/51785259-5eec6c00-2155-11e9-9d91-66e848034a5a.png)
![argosy 2](https://user-images.githubusercontent.com/27152901/51785260-5f850280-2155-11e9-8a67-98c6597b5f2a.png)

needs work:

![arrow 0](https://user-images.githubusercontent.com/27152901/51785272-90fdce00-2155-11e9-8ab5-5aab94960d84.png)
![arrow 1](https://user-images.githubusercontent.com/27152901/51785273-90fdce00-2155-11e9-9bc6-4bfa0ad8fff4.png)
![arrow 2](https://user-images.githubusercontent.com/27152901/51785274-90fdce00-2155-11e9-95f4-f983f17d4684.png)

**Comment by sivael** [comment]
Light animation doesn't look of IMO, I prefer the static images.
What I would love however is something else, and with an automated renderer it could be done quite easily:
I would want to render the ships 9 times:
once, unlit( with no direct lighting, just environment lighting)
and 8 times with different light directions.
Then, I would like to subtract the base render from each lit render to have a set of 8 directional lightmaps.

You would put them in a single texture so that the center texture is the unlit ship which You can then postprocess manually if You so desire, and 8 directionally lit lightmaps which would be used to light the ships from different directions.

This would enable dynamic lighting and multilighing, self shadowing etc... very cheaply, while retaining the ability to postprocess the ship manually.

You could even do something like this:
You render each ship You currently have, then you ditch the new unlit version and use the current post-processed one by creating a diff for lighting of the current lighting setup to create the post-processed unlit version.

Very cheap to implement, shader is simple and no multitexturing is involved.

Would it be possible to enhance Your solution to include this?

**Comment by 8b8** [comment]
Cool suggestion! I rendered all ships in 10° steps of sun rotation [rendered_ships](https://www.dropbox.com/s/8jq6vd23ge1qrc3/rendered_rotate.tar.xz?dl=0). (unfortunately some were still on the frame with the lights on)

For the gifs i linearly interpolated between two nearest frames to get 3.6° steps and rotated the images of the ships accordingly.

Preview
![fury](https://user-images.githubusercontent.com/27152901/52673808-0ae9d180-2f22-11e9-803d-aaba2a5aa4d4.gif)
![headhunter](https://user-images.githubusercontent.com/27152901/52673850-27860980-2f22-11e9-917a-6a67266edd12.gif)

![manta](https://user-images.githubusercontent.com/27152901/52673895-42f11480-2f22-11e9-8a44-3807ec7d4d18.gif)
![behemoth](https://user-images.githubusercontent.com/27152901/52674000-96fbf900-2f22-11e9-924a-07233dd34176.gif)

**Comment by sivael** [comment]
Yeah, something like that :)
And in a shader it's relatively simple and would look at least decent even with 8 frames of lighting.

**Comment by Zitchas** [comment]
Those shadows look really nice! I would very much like to see ES have support for this, although it does go directly against MZ's original decision to ditch the EV style system (which, if I recalled correctly, did the same thing except with 64 rendered images and no interpolation)

**Comment by jafdy** [comment]
@Zitchas EV has a sprite sheet system where ships could only be drawn at angles given on the sprite sheet. Our sprites can be rotated to any position so will always point in the direction it is actually facing, as long as the lighting doesn't interfere with that (it changes the look of the sprite to match the approximate lighting direction keeping the ship pointed in the exact right direction).

2 questions: 1) could this be set up to allow multiple suns to light a ship from multiple directions?
2) how well can this be set up for modders to use, as in as user friendly as possible.

**Comment by sivael** [comment]
The solution would actually have just one sprite that's not rotated.
That would be the main sprite You can postprocess.
then there would be the directional diff lighting sprites that "surround" the main sprite and interpolate the lighting only. This would make the ship face the proper direction always, allow for sprite post-processing and allow for multiple lights (like multiple sun directions)
![light](https://user-images.githubusercontent.com/1681879/52715103-df0b3200-2f9b-11e9-8ed8-c396aee5b320.png)

**Comment by MCOfficer** [comment]
even if these images are saved as single channel-mask, it would increase the ship images' combined size from 8MB to roughly 130MB, and that doesn't even consider hdpi.

also #595

**Comment by sivael** [comment]
8 to 130? more like 8 to 72. but indeed that might be too much. We could alternatively store them in smaller resolution ima*ges. Alternatively we could store those lighting values in single channel which means just 4 sprites which is 32M per ship

**Comment by MCOfficer** [comment]
sorry, but how do you get 72 *without* single-channel? my calculation was

current sprite size * amount of angles * amount of used channels / 4 

i suppose we could drop down to 32 or even 16 angles thanks to drizzling, but everything below seems ludicrous (16 angles already means over 20 degrees between diff images).
And if we're very cunning, we could mirror diffs for symmetrical ships, saving half the space for those... that'd bring it down to something along the lines of 20-40MB (very much a ballpark estimate).

I don't expect much savings from saving multiple diffs on different channels, as opposed using one image per diff.

**Comment by sivael** [comment]
Different way:

1. You have one (1) image that contains the base colors of the sprite.
2. You have eight (8) images that contain the additive lighting relative to rotation and light direction.
3. You interpolate lighting only, and simply rotate the sprite as we do now. So with 1 RGBA for full unlit sprite and 2 RGBA for 8 lighting channels assuming textures aren't compressed.

**Comment by Zitchas** [comment]
@jafdy Thanks for the explanation. I thought this was reverting to the EV system, albeit with a higher number of frames (and thus directions). 

So this is using the current ES system, and the various frames are used to provide variable shadows. I like it!

**Comment by Amazinite** [comment]
If we're going down this line of thinking, does that mean that each frame of animated ships would also have 8 or however many extra images associated with it? Will the Shuttle go from 3 images to 27 or more?

**Comment by sivael** [comment]
2 lighting sprites per ship base tile but then we could have animated base sprite and emissive anuimation overlay. Lots of options but they complicate things a lot if we do animated ones. I'd simply go for lit sprites and then consider whether animted make sense.
We could also do animated subsprites like flashing lights etc... separately - in definition files, not in rendering.

**Comment by 8b8** [comment]
Not all the ships look as impressive when rotating, I uploaded all gifs  [here](https://www.dropbox.com/sh/3s384h44ye8srz6/AACtHemEXmzaqRwwXnYkTfM3a?dl=0)

As sivael pointed out, this mostly needs the luminance/greyscale channels to work. How well it looks depends on how sharp the shadows should be. The softer the shadows the better the interpolation works. I don't think 8 directions is enough given the current hardness of the shadow.

Also there needs to be a factor that reduces saturation when the luminance goes over a certain threshold to account for reflections.

There might be a way to compress the sprites to a video file for transport and expanding the single frames into sprites at launch/install (alpha can be calculated from rotating a single image).

Any "light" animations (shuttle lights) should be able to be superimposed on the image.

I can not estimate if and how much this will add to the game. I rendered the sprites so that they are available for experimentation so someone can find out :).

### But: 

The system right now allows for geometric animations (even they are only used on the void sprites). Using geometric animations, different occlusion will require squared frame numbers. E.g. in a few of the blend files there were a simulations set up to fragment ships (FTL style). Implementing adaptive lighting will make geometric destruction animations really hard. I also thought about adding surface animations, once the general look of the textures and compositing is nailed down. (Moving pistons, hatches, dishes etc)

I always thought the biggest strength of the game is worldbuilding and storytelling as well as the enormous talent to keep things simple while still being resourceful within these limitations. There is still a lot that can be done without adding directional lighting: 
All the suns have the same brightness and hue (Color temperature?) and there is no light falloff from the center of the system (r**2-law). I think adding custom hue to different systems as well as a light falloff (maybe in combination with running lights) will add a lot of visual flair, contributing to the core strenghts of worldbuilding and storytelling, at far lower cost. 

I don't see how directional lighting allows for more possibilities in worldbuilding and storytelling.

**Comment by sivael** [comment]
Counterintuitively 8 directions is enough, as most of the time players will not see the difference between 8 and 16 directions. But all things come with a cost.

You are essentially correct and the same effect could be used by setting up a single point light and adding normals to ships with a much simpler algorithm.

And while You are correct that storytelling is much more important here, I wouldn't discount the ability to upgrade graphics as it could add a lot to the overall experience.

**Comment by 8b8** [comment]
I think there is a misunderstanding. I don't mean normal maps. The light falloff and the color temperature would be simply a colormap operation on the current sprites. Basically a different white balancing and brightness for different systems (If so desired).

**Comment by jafdy** [comment]
#2728 did light fall off, it doesn't really work well in the context of a game.

**Comment by Naf5000** [comment]
Just my two cents, but it may not be necessary to have lighting track the sun(s) in a system; EV: Nova had all ships (and, indeed, every object in space) illuminated from the same angle relative to the camera regardless of the position of light sources. This seems a more workable solution than having completely dynamic lighting, as it avoids the hassle of dealing with multiple stars entirely and means the game doesn't have to keep track of how lighting changes depending on a ship's position in the system. And it certainly isn't _more_ immersion-breaking than having every ship illuminated from a different angle relative to **everything**, as is the case currently.

**Comment by Pointedstick** [comment]
This PR is a great example of how something that's too big with too many distinct changes can end up unmerged, with none of them having gotten in. :(

I think it would make a lot of sense to split it up into smaller ones. For example I would still really like to see the human ships gain a subtle "ship plating" texture. If that was done on its own, without changing any geometry or lighting, I think it would have a strong chance of getting in.

**Comment by LocalGod79** [comment]
I just wanted to raise #595 again - with the contribution of new high res, stunning ships by @beccabunny , adding jpg normal maps is starting to make a lot of sense, adding nominal image load for incredibly enhanced visuals...

**Comment by Darcman99** [comment]
Raising #595 again would be a godsend, the dynamic lighting is a monumental improvement on graphics of the game for what I see to be a very minor downside. The possible issues with lag was discussed over there and the opinion is that the bulk of the lag in the game thus far is because of ship AIs and the like, so that seems like a moot point.

As for the 2D images in the game, they've already been discussed too, they can be loaded alongside the maps as static if there are no maps for it. Additionally a setting to disable maps and render just the static images is just as relevant as other potential issues.

**Comment by pouar** [comment]
dropbox links are dead

**Comment by Amazinite** [comment]
Becca has done work and is continuing to do work to improve the older graphics in the game. So to this specific issue, I don't see the need to completely change the process by which ships are detailed and redo a bunch of older ships. If anyone wants to use this process for their own ships and PR those to the game then I don't have a problem with it so long as all the assets are readily available, but as an issue this doesn't seem like something that needs tracked.
