### ISSUE TITLE
Mission Doesn't Complete

### ISSUE THREAD

**Issue by Electrox18** [endless-sky/endless-sky#4098]
I just landed on Tundra with Freya, but the mission to return from Pug space  and land on Tundra doesn't complete. Once I land, nothing happens, even after coming from a different system or launching and landing again.
macOs mojave 10.14
Steam
Version 0.9.8

**Comment by jafdy** [comment]
Can you provide a save file.

**Comment by Electrox18** [comment]
I don't know how to find it

**Comment by Electrox18** [comment]
got it
[TJ Junior.txt](https://github.com/endless-sky/endless-sky/files/2710905/TJ.Junior.txt)

**Comment by Electrox18** [comment]
never mind, just got advice from a friend to try selling off my other ships and buying them again later, it worked
