### ISSUE TITLE
credit for beta testers

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#41]
@akien-mga and @kilobyte: you've both given me a lot of really helpful feedback, and in the next release I'd like to add you to the game credits as beta testers. If that's okay with you, would you prefer to be listed by your GitHub name, by your real name, or something else?

**Comment by kilobyte** [comment]
I'm fine with either.  If you prefer real name, mine is Adam Borowski.

**Comment by akien-mga** [comment]
Hi @endless-sky, thanks for adding us to the credits :)
You can go with my real name, Rémi Verschelde.

**Comment by akien-mga** [comment]
I see some nice additions in the master branch btw, I'm looking forward to play-testing that :)

**Comment by endless-sky** [comment]
Added beta tester credits in b96ccd7.

**Comment by endless-sky** [comment]
@speeder, I'd like to add you to the beta testing credits. If that's okay with you, let me know if you'd rather be listed by your real name or your Github name. Thanks!

**Comment by speeder** [comment]
Oh, thanks! Please list me as "Maurício Gomes"
