### ISSUE TITLE
Ships with scanners ignore marked personality

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4109]
**Describe the bug**
If a ship has outfit or cargo scanning abilities, it will target `marked` ships, and if it is hostile to said ship then it will then attack it.

**To Reproduce**
An example:
1. Have #3761's content, which gives Remnant ships outfit scanners
2. Attempt to do a bounty to hunt down a marked Raider
3. See how Remnant ships will attack the Raider, counter to the marked personality

Similarly, one could make a mission with a marked pirate in a system that the Navy show up, and the Navy will attack the pirate.

**Expected behavior**
Ships that have the marked personality should not be attacked by any ship other than the player's.

**System:**
- OS: Windows 10 Home, Version 10.0.17134 Build 17134
 - Game Source: Self-compiled
 - Version: Most up to date as of this issue (https://github.com/endless-sky/endless-sky/commit/275795c005ce21cd9208dab4e5ebdf8566d4cc98)

**Additional context**
@tehhowch tracked down the cause of this one.

**Comment by tehhowch** [comment]
Rather than add the "your ship or not marked" test to every place involving a ship's target and firing, boarding, or scanning, I've resolved this by preventing hostile targets from being chosen for scanning.
