### ISSUE TITLE
Test Dummies should disable, not kill

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4115]
It seems odd to me that the guy you meet on Tarazed doesn't want you to blow up his Kestrel, but it will happily shoot you out of the sky. The same can be said for Syndicate dummy ships.

**Comment by tehhowch** [comment]
I agree re: the Kestrel - but the Syndicate? Your death just proves that their ship is good enough -- and now they don't have to pay you.

**Comment by Amazinite** [comment]
Well they might not need to pay you, but they’d then need to answer to the Republic why they’re killing law abiding citizens.

**Comment by tehhowch** [comment]
Would they though? "Oops, another day, another industrial accident."

In terms of gameplay, adding `disables` to the personality (for both the Kestrel and the Syndicate test ships may result in something that is basically like death - you get disabled, then hail for repairs, and the second you get repaired, the test ship disables you again (or some pirates finish you off).

**Comment by Fzzr** [comment]
I could imagine a case for being able to fail a mission due to being disabled. That would open up things like "duels" where you can bet and lose money due to being disabled, and allow for interesting dialogue branches depending on the results of testing missions.

**Comment by jostephd** [comment]
> What captain is going to take such a job if they’ve heard of many other captains and crew dying at the hands of Syndicate drones?

Two kinds of people: those who love risks, and those who are desperate for money and are forced to take risks. I'm sure there are people who migrate to Syndicate worlds, run into debt, and when they have exhausted all easier options, rent a ship and start doing high-risk missions (freight to planets that neighbor pirate worlds, etc) because the payoffs are bigger. Some of them probably emigrate to the near-core pirate worlds in order to escape their Syndicate creditors (like Joe and Maria but in reverse).

**Comment by Amazinite** [comment]
There are a lot more high paying jobs than the dummy tests, especially ones that are far less dangerous.

**Comment by jostephd** [comment]
> There are a lot more high paying jobs than the dummy tests, especially ones that are far less dangerous.

That sounds like a balance problem. Risky jobs should pay more than non-risky jobs.

> And risk taking is why we have escort and bounty jobs.

Are we talking gameplay arguments or lore arguments? Lore-wise the Syndicate probably does hire people for risky things. Suppose pirates hijack a Syndicate freighter, I wouldn't be surprised to see the Syndicate say something like "whoever brings us the cargo first gets a million credits", as in _2 Fast 2 Furious_, and if some pilot stole the cargo from the pirates and then was himself boarded, disabled, or even killed _en route_ to delivering the cargo to the Syndicate, they'd say it's not their problem, it's just a private captain who couldn't defend himself.
