### ISSUE TITLE
Truncation of decimals causes issues

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4117]
Ref: https://github.com/endless-sky/endless-sky/commit/b219799a44cfd4f9c6f19d1bf0d5358c7a6ccbe6, #3877

The current UI behavior of truncating numbers off at tenths leads to stats displaying strangely. As mentioned in the comments to the commit that did this, outfits like gatling gun ammo or javelins show as having zero mass. Additionally, this truncation gives the appearance of inconsistency in the displaying of whole numbers, as some whole numbers may appear like `576`, while other times they appear like `576.0`.
(Image courtesy of @Tadrix. The left side is with decimal truncation, the right side is without.)
![comparison](https://media.discordapp.net/attachments/285540320823869441/532185354447486976/unknown.png)

An alternative, as suggested previously, would be to use significant figures as opposed to truncation, but strictly using sig figs means that something like the Hai's huge battery would display its capacity at 77,780 instead of 77,777. What I propose is that any number equal to or larger than 1000 (four digits sans the decimal places) that also has a decimal part to it would be truncated to remove the decimals. Three digit whole numbers would only show to the tenths place. Two and one digit whole numbers would then only show their decimal part to the hundredths place. And to avoid inconsistencies as to how numbers show (e.g. 500 on the dot versus 500.04 showing as 500.0), all numbers could show their decimal places, even if it is only zero.

Table of examples of what I'm suggesting:

Full number | Displayed
--------------|------------
0.0540 | 0.05
0.1 | 0.10
0.101 | 0.10
1 | 1.00
1.502 | 1.50
12 | 12.0
12.04 | 12.0
632 | 632.0
632.58 | 632.6
1052 | 1052
1052.6734 | 1053
25862 | 25862
15235.6753 | 15236

**Comment by Tadrix** [comment]
Personally, I'd prefer if:
Speed, acceleration, turning were displayed like they were in 0.9,8.
Energy and heat were displayed rounded up to (one or) two digits behind the decimal point, without placeholder zeros.
So:
5 displayed as 5
2.1 displayed as 2.1
3.367 displayed as 3.37

**Comment by Amazinite** [comment]
Whatever fixes the current issues.

As for stacking values though, there is the energy and heat columns. And I wouldn't consider trailing zeros in all instances to be confusing. What's confusing is when you sometimes see trailing zeros and sometimes don't. Trailing zeros in all cases might as well be the same thing as trailing zeros in no cases.

**Comment by Nescio0** [comment]
Finite Galaxy solved this (https://github.com/finite-galaxy/finite-galaxy/commit/f0c05462e96a3d431a98d1a04cdca8aafb6875a2) without adding trailing zeroes.
* Format::Number can have up to three decimals, if necessary
* A new Format::Round function is introduced to round a decimal number to the nearest integer; it is used for the movement values and in the fuel/energy/heat table

![screenshot from 2019-01-11 15-49-57](https://user-images.githubusercontent.com/21634324/51076597-c2c55e00-169a-11e9-9c28-ccce2ca5224f.png)
