### ISSUE TITLE
Guns ignore non-directly targeted disabled ships

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#412]
I oftentimes find myself killing korath raiders because my escorts are trying to take down their fighters. Of course, a simple way to fix this would be to aim for fighters first, but other circumstances would be easier/better with this implemented as well

**Comment by thenerdfreak** [comment]
I meant the shots go through the ships, since it already ignores them if they're disabled for escorts

**Comment by brick96** [comment]
Thats what makes it hard for mass capturings of ships. Draw them away form the disabled ships so you or escorts dont finish them

**Comment by endless-sky** [comment]
As with many other suggestions for ways to make plundering ships easier, I don't see a need for this. Plundering is already way too lucrative, so I think it's a good thing that there are so many ways it can go wrong.
