### ISSUE TITLE
A fleet jump command is desperately needed

### ISSUE THREAD

**Issue by hrs111111** [endless-sky/endless-sky#4124]
This is essentially reopening https://github.com/endless-sky/endless-sky/issues/1026

Problem:
Manually long pressing J for multiple seconds, and manually waiting until all ships align to release J, in every system is very tiring, and takes much fun out of the game. A player should instead be able to autopilot to the destination system as long as no threats spawn on the route.

Solution:
Have a key/command that you can press just once to do automatic fleet jumps until the fleet reaches the destination system. A fleet jump is a jump where all ships wait until the slowest ship has aligned and is ready and able to jump, and then jumps together as a single group.

**Comment by MCOfficer** [comment]
If it wasn't on the other end of the keyboard, i'd make a case for shift-j or ctrl-j. Otherwise: K?

**Comment by jafdy** [comment]
This falls under the umbrella of too much automation. Very simply it would allow you to walk away from the game and when you return it has got to the next planet without any input from you.

**Comment by hrs111111** [comment]
Why would it be a bad thing? Anything that is not engaging to the player should be automated away!
(Isn't it the same principle when pressing J to use autopilot when you have only one ship.)

**Comment by hrs111111** [comment]
As a counter point, currently a player has to hold down J for 5 - 10 seconds at each jump, which is very taxing. At the very least, holding J down can be replaced with a single key press.

Secondly, https://github.com/endless-sky/endless-sky/pull/2648 changes that would have been merged in except for merge conflicts and minor issues, If I understand correctly.

**Comment by Pointedstick** [comment]
> This falls under the umbrella of too much automation. Very simply it would allow you to walk away from the game and when you return it has got to the next planet without any input from you.

That's exactly what we already have when you're in a single ship: open map, click on planet, close map, hit `J`, go get a cup of coffee. I don't see why this should be acceptable when you're alone, but unacceptable when you have a fleet.

**Comment by jafdy** [comment]
I don't think it is. I liked the old way where you at the very least needed to be there for the last system.

**Comment by Pointedstick** [comment]
The point is, there's no logical reason for it to be inconsistent between single ship vs fleet. If we want to reduce the automation factor, it should be a purposeful design decision, not the side effect of a bug or oversight.

**Comment by AlbertNewton** [comment]
Taking a while to cross the galaxy only really happens if you're in a slow ship with a normal hyperdrive. And even still, unless you have huge fuel capacity you're going to need to manually land and take off again. Not much chance of a coffee there, Pointedstick.

**Comment by endless-sky** [comment]
Also, if your finger gets tired, you can fast-forward.

Adding a whole new command for this (and, having to include that command in the keyboard controls list, etc.) seems like way too much added complexity for a use case that very few players will care about.

**Comment by Zireael07** [comment]
Just my $0.01, I don't think that very few players would care about having a fleet jump command - most people do get a big fleet at some point.

**Comment by Zitchas** [comment]
That's true, however many of us (like myself) prefer to have my fleet trailing behind me most of the time. I can dodge pirates/enemies a lot better as a solo ship.  This is especially true when I'm escorting merchants or have a lot of freighters in my fleet. It is generally only when I am feeling grandiose or when I know I'm jumping into certain specific combat situations do I want my whole fleet arriving with me.

Even then, I'd rather arrive, burn up the majority of the opposition's missiles dodging via dodging and anti-missile fire, and only *then* have my fleet arrive.

**Comment by pyorokun7** [comment]
This is not consistent. Right now, if a ship in my fleet runs out of fuel, it will automatically land if there is a planet, refuel, launch and continue the trip to your current location.

Are you telling me that THAT automation makes sense, but not an option where I can ensure that my fleet will jump together if I want it to?

**Comment by petervdmeer** [comment]
Fixed by merge of #5686 .
