### ISSUE TITLE
Request: have killing Korath make you more friendly with Quarg

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#413]
Would give a not-so-easy way to make up for mass murdering those 2000 ships worth of merchants to the Quarg, who would otherwise destroy you on sight

**Comment by brendanjones** [comment]
It should probably work both ways, then, i.e. killing Quargs makes the Korath more friendly towards you, also.

**Comment by Wrzlprnft** [comment]
Are the Quarg and the Korath enemies?

**Comment by thenerdfreak** [comment]
The Quarg are a peace-loving (albeit arrogant) species, and the Korath are interstellar space pirates. I think the Korath wouldn't approve of that :p

**Comment by Wrzlprnft** [comment]
the Korath already have been punished as it seems
and as i understood, the quarg just don't care as long as you do not attack them or work against the drak
I just see no reason in the actual state of the game, 

but there is no right or wrong, and it is annoying that the quarg will hate the player sooner or later

**Comment by thenerdfreak** [comment]
And super annoying that there is no way to reverse that hate, like you can pirates, (easily if you never attacked them to begin with, 1 korath mothership turns them blue) and every other human faction

**Comment by endless-sky** [comment]
Killing pirates earns you positive reputation with the Quarg.

**Comment by thenerdfreak** [comment]
How is the reputation calculated? Through number of ships, or number of minimum crew?

**Comment by endless-sky** [comment]
Minimum crew. So, destroying a large ship nets you a much larger change in
reputation.

**Comment by Tufton** [comment]
Is combat rating calculated the same way?

**Comment by thenerdfreak** [comment]
Yes

**Comment by Wrzlprnft** [comment]
I was hunting down korath world ships to get my reputation and ranking up.
Nut somehow i like that the most loot-profitable alien species does not love you for looting the second loot-profitable alien species....

**Comment by frameworld** [comment]
OK, if I understand it right, Bactrian adds 70 combat rating while a Shield beetle adds about half?

Do the treats grow bigger the better your rating? Maybe that's a reason to not have just Bactrian (which are good as a flag-ship but add a lot of minimum crew too)

**Comment by brendanjones** [comment]
> endless-sky: Killing pirates earns you positive reputation with the Quarg. 

> thenerdfreak: and the Korath are interstellar space pirates

So if the Korath are pirates, then killing them should grant you positive reputation with every faction with which you gain positive action for killing pirates. Including the Quarg. Right?

**Comment by thenerdfreak** [comment]
While they ARE pirates, they are not classified as pirates, All human factions (save for quests) INCLUDING pirates become friendly from killing just a few korath world ships

**Comment by Wrzlprnft** [comment]
>government "Quarg"	
>	"player reputation" 1
>	"attitude toward"
>		"Merchant" .1
>	**	"Pirate" -.1**

>government "Korath"
>	"player reputation" -10

>government "Pirate"
>      "player reputation" -10
>	"attitude toward"
>		"Merchant" -.1
>		"Syndicate" -.1
>		"Korath" -.1
>		"Author" -.1

**Comment by thenerdfreak** [comment]
weird, their gov't is pirate but they are still attacked by and still attack pirates

**Comment by endless-sky** [comment]
Given that the Quarg are a (mostly) peaceful species, and the Korath are not entirely evil, I don't think I'm going to make the Quarg hostile toward them.
