### ISSUE TITLE
Missing hotkey for command ship hold position.

### ISSUE THREAD

**Issue by B3bomber** [endless-sky/endless-sky#4135]
**Issue**
I have no control over my command ship when it comes to ceasing all movement.

AI can do it, my escorts can do it, dead ships can do it (especially when hit by a force imparting type weapon that sends them flying), and there's even a hotkey assigned for making escorts hold position (h).

**Related Issue Links**
400+ to search through, no thanks.

**Describe the solution you'd like**
Shift+h == hold position for command ship.

**Comment by Fzzr** [comment]
This duplicates #2815, which was declined.

**Comment by B3bomber** [comment]
I'd say something about that further but it's obviously a waste of my time.

**Comment by Amazinite** [comment]
Reopening this, because I think that `shift + <escort hold position key>` is the best solution to the problem, and this is a topic that comes back up every so often, so clearly there's a demand for the feature.

**Comment by tehhowch** [comment]
Automating a one-time stop of the flagship is one thing, automating its continuous return to a fixed position is another. You can now order the flagship to stop, much like you can order it to land or jump, but if your flagship is pushed once already stopped, then you will need to indicate that you want to stop again.
