### ISSUE TITLE
Request: Different colors for Bounty mission "flags": Red/Open - Grey/Closed

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#414]
I don't know the nomenclature for the little pips arrayed around systems that indicate missions, so I'm calling them "flags" for now.

As it stands we have 2 mission panels and 3 colors for missions.

On the left we have open missions - regular freight, bulk, passengers, rush, and as the game progresses, bounty missions.

As missions are accepted/rejected/ignored a list is generated on the right. This list is sequential, and sorted into open/closed for bounties, dull grey type for open, bright white type for closed; hence a bounty is waiting to be collected somewhere. Clicking on one of these listings shows the system where the bounty is located, either to be completed, or payment collected.

Now, on the map, we have 3 colors for the various states of missions:
Orange/Yellow? for open missions - those not accepted yet.
Bright Blue for missions accepted. (Flashing Blue for rush but those are immaterial for now.)
Dull Blue for open bounty missions, (live pirates.)
Again Bright Blue for closed bounty missions, (dead pirates.)

Eventually the map becomes a sea of blue flags, some bright, some dull, some flashing. (And of course, some orange.)

What I propose, and I've discussed this with several players to gauge their reactions, (which were favorable), is to allot 2 new colors for bounties.

Example: Bounty mission comes up on the new missions list, gets accepted, and the "flag" next to the system appears in Red. (Currently dull blue)
Rationale: This is a mission I've accepted but it isn't one I need to land on or use as a waypoint on my multi-jump course. It's there, it means "Beware, Pirates!", but it also signifies that it's not a system in which I have to deliver cargo.
(On the Current Missions list on the right, this mission would remain dull grey. No need for change there.)

Once a pirate is "terminated with prejudice", the red flag turns Grey* and indicates A.) the pirate menace is resolved, and B.) there is a bounty awaiting collection. 
*(or perhaps White, given the overall dark nature of the map)

These changes would clearly divide the map into commerce and warfare, and greatly improve the readability of the map "at-a-glance."

Comments, rebuttals, suggestions cheerfully encouraged. Thank you.

**Comment by Wrzlprnft** [comment]
Good idea.
I'm not sure how many different colors we should introduce though (in future), at the end, it might get even more confusing

**Comment by endless-sky** [comment]
Read through #72 if you're interested to know how the mission pointer
colors ended up as they are.

Again, this comes down to a question of how things can be kept as simple as
possible to avoid confusing people. Everywhere in the UI, dimming out a
color means "inactive" and brightening it means "active." That's very
standard, the same as greying out menu items that are inactive in just
about any modern GUI program. So, it will be easy for someone to figure out
that a dim yellow pointer means "you don't have space for this" and a dim
blue pointer means "you can't complete this mission yet." Switching to
having red mean "you can't complete this mission" and grey mean "you can
complete it" but only in the case of bounty missions seems really likely to
cause confusion.

**Comment by Wrzlprnft** [comment]
i do like the system we already have, any improvement should be a real improvement

**Comment by jafdy** [comment]
Then what about using dim/bright red pointers for bounty. any player that has bounty missions available will not be a very new player any more.

**Comment by anonybosch** [comment]
Confusion? How about "all the accepted missions are blue" confusion?
I'm not suggesting adding a rainbow of colors for all the various missions. The present methodology works adequately without adding any more complexity. Nor am I suggesting making any changes to the available/accepted job boards.

But pirate hunting is combat missions.
Bright red/dull red (much better idea, jafdy) distinguishes them as combat missions. Bright red (the universal color for danger) for the live dangerous pirates/infested systems, and dull red for the dead pirates and bounties.

So there it is. Commercial missions in peaceful blue. Combat missions in dangerous red.

**Comment by endless-sky** [comment]
What would you do with story line missions? Have them be blue or red depending on whether or not they are dangerous? And what about escort missions? Or planetary defense? It seems like if you try to draw a line between "combat" and "commercial" missions, there will be a lot in the middle.

And, I'm not clear on what benefit there would actually be to that, anyways. Right now, a bright blue pointer always means, "you can go here to collect a mission reward." So the only advantage to having a separate color would be to indicate what systems have a bounty hiding nearby, and that could probably better be shown in a different way.

**Comment by jafdy** [comment]
I think they can be classified as 
blue:anything that you don't need to kill stuff for (transport/escort)
red:anything you do need to kill stuff for (bounty/defense)

**Comment by Wrzlprnft** [comment]
but in escort missions you might have to fight some pirates

**Comment by anonybosch** [comment]
I've come to the conclusion that this was an ill-conceived idea that would only complicate the game, even if it could be implemented without creating more confusion.

As the saying goes, "A fool's bolt is soon shot."
Feel free to delete the issue. I don't know how to.

**Comment by jafdy** [comment]
Need is the key word. In escort missions you can just run away.

**Comment by Wrzlprnft** [comment]
I do atleast disable every ship that attacks me, just because i can though
