### ISSUE TITLE
'Select nearest hostile ship' key should not select disabled ships

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#415]
They're no longer hostile, so they shouldn't be selected. Also, selecting the nearest hostile ship when there are no longer any hostile ships should clear your selection.

**Comment by anonybosch** [comment]
Why not? It makes selecting a disabled ship quick and simple. The other choice is N for next ship and that just goes through the entire retinue of ships within the radar's range. Very messy way to do things.

**Comment by endless-sky** [comment]
I think some people probably rely on being able to use that key to select a nearby disabled enemy, so changing its behavior might not be a good idea.

**Comment by Pointedstick** [comment]
Yeah I like the current behavior.

**Comment by brick96** [comment]
B automatically selects the nearest disabled ship

**Comment by anonybosch** [comment]
@brick96 True but B doesn't discriminate between friendly/foe. And cycling B causes the flagship to move this way and that way until you finally arrive at the ship you actually want to board. 
Imo, R should stay the way it is so it cycles through hostiles - abled and disabled.

**Comment by brendanjones** [comment]
As Brick96 said - pressing B selects the nearest disabled ship. Do you guys use R (nearest hostile...is R the default? I may have changed it to R since I changed a few keys to match EV default keys that I'm familiar with :p no way to return keys to default for me to check. ) for this? 

The only advantage to pressing R is that pressing B also sends you to board the ship you select, whereas R just selects it. But generally when I'm selecting a disabled ship I mean to board it, so it's actually an advantage.

R is for selecting/fighting active ships and selecting disabled ships, B is for selecting/boarding disabled ships. It seems strange to me to include the selecting of disabled ships function to the same key as the fighting active ships function.

> And cycling B causes the flagship to move this way and that way until you finally arrive at the ship you actually want to board. 

Pressing B just selects your closest disabled ship. Pressing B again does not select another disabled ship unless you've moved closer to a different disabled ship than the one you had selected. Only if you change target should your ship move about.

**Comment by brendanjones** [comment]
Also, using R to select disabled ships doesn't work unless there are no active hostiles. What do you guys do when you want to board a ship while there are still active hostiles in the system? You must have to press N, and that's definitely inefficient.

**Comment by Impurethinker** [comment]
What about those people who are in a hurry and have no desire to board anything? I'm running a trader fleet and try zipping through as fast as possible but if a hostile gets in the way, hitting 'R' then tab until they die and keep hitting 'R' to cycle through all the hostiles to blow them up sounds more reasonable than changing the nature of what the R key does in the middle of a fight. It works fine as it is. If you want another bindable key to cycle though disabled hostiles only then okay.

**Comment by johndh** [comment]
I like the current function, as it follows the progress of the fight.  At first you want to take out active enemies one by one, which R does, and then you want to start looting/capturing their fallen, which R continues to do.  B will select the nearest disabled enemy if your current selection isn't able to be boarded (i.e. it's not a disabled ship or low on fuel).  If you want to select a particular ship, you can click on it if you're close enough.  If anything, my complaint would be that B keeps selecting disabled friendly Republic probes (sensor drones? whatever they're called) when there are disabled enemies around.  I would think the proper priorities would be 1) disabled escorts, 2) disabled enemies, 3) disabled friendlies, 4) escorts low on fuel, 5) friendlies low on fuel.

**Comment by brendanjones** [comment]
> What about those people who are in a hurry and have no desire to board anything?

Huh? Then isn't my change better? If all you want to do is defend yourself from attack, then your selection clearing when there's no-one left to attack you is better than your selection flicking to a disabled ship who's no longer a threat to you.

> If anything, my complaint would be that B keeps selecting disabled friendly Republic probes (sensor drones? whatever they're called) when there are disabled enemies around. I would think the proper priorities would be 1) disabled escorts, 2) disabled enemies, 3) disabled friendlies, 4) escorts low on fuel, 5) friendlies low on fuel.

Sure, I'd agree with that, though I'd personally switch 1 & 2 since I generally board my disabled escorts last because they're expensive to lose, yet they normally don't get attacked while they're disabled so that's actually the safest state for them to be in until I'm ready to jump out of the system with them in tow.

This would fix your issue of 
> At first you want to take out active enemies one by one, which R does, and then you want to start looting/capturing their fallen, which R continues to do.

Then R is for fighting, and B is for boarding.

**Comment by endless-sky** [comment]
There's enough disagreement on this that I think it makes the most sense to just leave it as it is, and as players have come to expect.
