### ISSUE TITLE
Short freeze when acquiring a first target on GNU/Linux.

### ISSUE THREAD

**Issue by Soviet-Glider** [endless-sky/endless-sky#4152]
Hello, I have a little bug to report. With the GitHub version when I have no target and I make a target acquisition by selecting with mouse click or using `r` or `n` the game, sometimes, temporary freeze (some seconds) and continue normally after, and then I can cycle target without freezing. I have not this problems with the stable version. By the way I use GNU/Linux, with Intel HD for graphical acceleration.

**Comment by Soviet-Glider** [comment]
I have no issue with the Ubuntu official repository version of Endless Sky 0.9.8-1, and for the GitHub version I can't remember if I download it with `git clone` or direct master.zip download so I'm not sure what can be done with `git bisect` trough I'm not really versed in git. I don't run a git mirror, at least I believe...

`lscpu` give me :
```Architecture :                          x86_64
Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
Boutisme :                              Little Endian
Processeur(s) :                         4
Liste de processeur(s) en ligne :       0-3
Thread(s) par cœur :                    1
Cœur(s) par socket :                    4
Socket(s) :                             1
Nœud(s) NUMA :                          1
Identifiant constructeur :              GenuineIntel
Famille de processeur :                 6
Modèle :                                55
Nom de modèle :                         Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
Révision :                              8
Vitesse du processeur en MHz :          2001.331
Vitesse maximale du processeur en MHz : 1999,2000
Vitesse minimale du processeur en MHz : 1332,8000
BogoMIPS :                              3998.40
Virtualisation :                        VT-x
Cache L1d :                             24K
Cache L1i :                             32K
Cache L2 :                              1024K
Nœud NUMA 0 de processeur(s) :          0-3
Drapaux :                               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm arat```
Kernel version :
```4.15.0-43-generic #46-Ubuntu SMP```
xUbuntu (xfce) Ubuntu 18.04.1 LTS.
`glxinfo | grep 'version'` give me :
```server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.20
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
The bug is producible with a fresh start new pilot, no plugin installed. The bug only happen when they is `no target` but it's not happen in each case of `no target`, and after a first target acquired, the game can quickly switch between multiple  target without freeze or lag.

**Comment by tehhowch** [comment]
I wonder if you can determine information about how / if the delay returns--jumping into a new system, landing & taking off, and/or (sorry) waiting 5 / 10 minutes.

The code governing the response to those NEAREST and TARGET keyboard commands hasn't really changed in 4 years: https://github.com/endless-sky/endless-sky/blame/master/source/AI.cpp#L3024 

The code for handling mouse clicks has more recently changed, but you mention an issue with the keys so the actual issue may be in drawing the selected-ship pointers or other information associated with the targeting display (such as the outline details).

**Comment by tehhowch** [comment]
There is a new official release; please see if you see the same issue for it w.r.t v0.9.8 and a source build.

**Comment by Amazinite** [comment]
Hello?
