### ISSUE TITLE
Your ship should always display on top of escorts

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#416]
Try having a fleet of 30 Bactrians and see which way your ship is pointing. You can't, they're always on top of your ship.

**Comment by anonybosch** [comment]
Absolutely! I suggested/mentioned this at the Steam forum but it never got any traction. The only way I can tell which way I'm facing under a pile of escorts is to fire my cannons and trace back to where the flashes are coming from.

**Comment by guillochon** [comment]
Submitted https://github.com/endless-sky/endless-sky/pull/419 to reverse ship drawing order.

**Comment by brendanjones** [comment]
Thanks guillochon for doing the hard yards :+1:

**Comment by endless-sky** [comment]
Fixed in commit 29d2ff4, which also places your flagship on top of NPCs and any random ships in the system.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
