### ISSUE TITLE
NPC Fleet

### ISSUE THREAD

**Issue by Knightroad** [endless-sky/endless-sky#4163]
I feel kind of dumb. I'm trying to make an NPC fleet for something I'm working on.  There is one part of the fleets document that I'm not sure about.

`fleet "Small Southern Merchants"
	government "Merchant"
	names "civilian"
	cargo 3
	personality
		confusion 40
		timid frugal appeasing`

What does cargo 3 mean? Is that how many tons it carries at one time? Or how valuable the cargo is? Or something else?

**Comment by Amazinite** [comment]
GIthub is for tracking issues with the game, not asking for help on creating plugins or the like. Check the [wiki](https://github.com/endless-sky/endless-sky/wiki) for questions like this, or go to the Google forums, Steam forums, or Discord server.
