### ISSUE TITLE
Should the news shown in spaceports only refresh on landing?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4165]
Currently, clicking the spaceport button repeatedly will show you various news messages. Given the limited number of portraits and messages though, it's not uncommon to have the same image pop up with the same message and title, or even more oddly to have the same image pop up for supposedly two totally different people with different titles giving you different messages.

Suggested changing this so that the news that you get is generated on landing and only that one message will ever show up whenever you click on the spaceport until you depart. This removes the potential scenario of oddly having the same message twice or the same image twice in a row, let alone being able to flip through all the possible messages on one landing by just sitting there and reading. This would not only remove those scenarios, but also incentivize traveling and hitting the spaceport button every time you land to see what message you get on that landing.

**Comment by tehhowch** [comment]
a9feb0e0 moves the news selection to when the planet panel is created (i.e. the player has just landed or reloaded their save).

We could also put a timer on it, e.g. it only changes every 5 minutes, by using a `step` counter much like the MissionPanel uses for blinking the deadline pointers.

**Comment by MCOfficer** [comment]
Do you mean 5 minutes during which the player is on the planet, or 5 minutes regardless of how often they take off and land?
I don't really see a use-case for the former, and... actually i don't see a use-case for either of them.

**Comment by Wrzlprnft** [comment]
Spontanous, not that well thought out idea: how about an arbitrary yet to be found number of clicks that's not the spaceport button? Premise: Players who spend thought time on a planet spend inlore time, going through the outfitter, going through the commodity prices on the map and such could encounter new news due to the character spending time and walking around.

**Comment by Amazinite** [comment]
I'd rather not have the news update at any point for any reason after landing. If the news only updates on landing, and spaceport missions are only offered the first time you click the spaceport button, then having some way to have news update after say a certain amount of time or a certain number of actions is taken may improperly imply that the chance to get offered a spaceport mission has also refreshed.,

**Comment by endless-sky** [comment]
Arguably, if you think it makes sense that every time the player "returns" to the spaceport they run into the same person saying the same thing, the current behavior (they run into multiple people, but occasionally the same one twice) isn't any less logical.

And, being able to cycle through messages if you feel like it just feels more fun than always getting the same one, especially if there are funny ones. It's the equivalent of how in Warcraft II, every time you clicked on a unit they'd say something slightly different, and get more annoyed the more you clicked - it was fun to pester them just to hear all those messages.

**Comment by Ferociousfeind** [comment]
In the same vein, you could make the argument for having ships retain one hail for the day no matter how many times you pestered them, which would make finding humorous hails a bit harder than talking to them repeatedly.

**Comment by Amazinite** [comment]
My argument in the OP was mainly a matter of the current scale. Given the number of hails, it’s EXTREMELY uncommon to get the exact same hail twice in a row from two different ships. Given the amount of news, it is not uncommon at all to have supposedly two totally different people tell you the exact same thing, or seemingly the same person suddenly switch titles because the image is the same but the news entry is not. I find the scenario of having a low amount of news and portraits while being able to see as much news as you want on one landing rather immersion breaking in that regard.

**Comment by tehhowch** [comment]
Setting a delay that blocks updating news each time it updates wouldn't be difficult. Something like 180 frames, and also decrementing it each time the key is pressed, would allow seeing multiple snippets without devolving into the original stream-of-insanity behavior.

Alternately just requiring the key to be pressed--not held--via a boolean toggle could work.

**Comment by AlbertNewton** [comment]
And if we could in some way prevent the same portrait(in cases where more than one portrait could be used by the `news` item), name, or news type being repeated(unless, again, it was the only option available or there were only very few `news` items valid for the planet/station) that would solve the problem of "Turning round a corner and bumping into the same guy you talked to back there."

**Comment by tehhowch** [comment]
@AlbertNewton as of dea4cf78ab7e8950534fa422413672b63103f1ae once a name is used for a portrait, that same portrait will have that same name again.

As of 94346d8905ec516b9a5fad2683f9ca0e5ab5f11f I've basically reverted the earlier commit https://github.com/endless-sky/endless-sky/commit/a9feb0e0dc0b2b796075c41292d21256b0fc3d27 that made news only update once per day, and now one must actually re-press the button to see additional news -- holding it down will only count once.

I considered tracking which messages have been displayed already, but the simpler solution to a repeated message is more content.
