### ISSUE TITLE
Allow ships to have random outfits in cargo, in addition to commodities

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#417]
It makes sense to the game, since that's where the Syndicate found the cloaking device.

**Comment by Wrzlprnft** [comment]
Since the syndicate only found one single cloaking device i guess the korath have looted it somewhere else. if there are more alien species around the core, i would agree that the kortath carry random outfits... but for now... *raises shoulders*

**Comment by thenerdfreak** [comment]
But if you've noticed, they only managed to take down 7 korath raiders, whereas the player is able to mass murder them. A 1/7 chance of alien tech would be fine and a tribute to the missions :p

**Comment by endless-sky** [comment]
This could be implemented pretty easily: right now each fleet specifies the number of random commodity types it carries. It could also be able to specify an "outfitter" sales list to pull random outfit cargo from, along with a probability of one of those outfits being picked.

The only issue is that right now, cargo and outfits are all in one list, so the player would not even notice that it is plunder in the enemy's hold rather than an installed outfit.

**Comment by thenerdfreak** [comment]
Maybe add some indication as to what is installed on the enemy, like the item being highlighted?

**Comment by Wrzlprnft** [comment]
Maybe add a seperating line between the installed outfits and the stuff which is in the cargo space?

**Comment by tehhowch** [comment]
The boarding panel is sorted by price per ton, so it wouldn't really be sensible to remove that functionality and display two sections (outfits vs cargo). In https://github.com/endless-sky/endless-sky/commit/80593fc9c734e178ef9989a2b0697775637e92f5 we got the ability to plunder outfits from cargo, and in #2518 we got the ability to see that these are carried outfits, not installed. Per the above comment, all that's really left is allowing these to be defined in `fleet` and/or `npc` blocks

**Comment by Amazinite** [comment]
Ref: #4050, #4062

**Comment by tehhowch** [comment]
Outfits will now happily be carried by NPCs created by `fleet`s--be it random NPCs or mission NPCs.
b8286faf98e782a42aec0d59d43119f266c5e03a
7fdf365adcce93c0e2430002d85f75ef7c5de95c

```
fleet "only commodities in cargo"
    commodities "Food"
    ...

fleet "only outfits in cargo"
    outfitters "Ammo North" "Ammo South"
    ...

fleet "specific outfits and commodities in cargo"
    commodities "Food" "Heavy Metals"
    outfitters "Basic Weapons" "Nuke"
    ...

fleet "location-aware outfits and commodities in cargo"
    ...

fleet "no cargo"
    cargo 0
    ...

npc
    ...
    fleet "location-aware outfits and commodities in cargo" # Stock fleets
    fleet
        # & custom fleets too
        outfitters "Ammo North"
        ...
```

The default number of different items is (and has been) 3, i.e. `cargo 3`. The NPC behavior is not new. Not yet added is the ability to specify a non-fleet-definition mission NPC's cargo, e.g. #4050 . That has some possible ambiguities in implementation better suited to a well-discussed issue / pull. For example, should there be only a finite quantity? Should there be an associated npc success criteria (e.g. `npc "plunder cargo"`)? What keyword is appropriate - same as for `fleet`, e.g. `cargo <int>`, `commodities <values>...`, and `outfitters <values>...`, or something else? a new node with children?
