### ISSUE TITLE
FW Southern Recon 1B: Alnasl is too unintuitive

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#4172]
In FW Southern Recon 1B, the player is tasked with stealing an electron beam/turret off of a gunboat. Freya recommends either Wei or Alnasl.
On my first several playthroughs, it *never* occurred to me that trying Alnasl would have any improvement. I had always painstakingly farmed Wei, hoping that RNG would spawn a small fleet that I could sweep through and steal a beam from, or perhaps that I could lead away into Kornephoros for the Free Worlds to pick them off. (Yes, I know fleets don't actually follow the player.)

This problem has appeared on the Steam forums and on the server too many times for me to count. If Alnasl is intended to be the real solution, I think that it should be made more obvious somehow.

**Comment by Lineth** [comment]
This mission is one of the few I've unabashedly cheated past. I've near lost count of the times I actually disabled a gunboat only to have half the Republic jump in on me.

**Comment by endless-sky** [comment]
It doesn't seem unreasonable to me to expect a player to be able to say, "Hey, this system is awfully high-traffic, maybe I should look elsewhere." Freya isn't psychic; like everyone else in the game, she's working with incomplete knowledge, and you need to take what she says with a grain of salt. To me, that feels better than spoon-feeding the player directions about how exactly they should complete the mission.

**Comment by Amazinite** [comment]
One of the problems isn't just that Alnasl is where players should be going when they're given two possible systems, it's that you have to pass through Wei to get to Alnasl in the first place, and Wei can have large Navy fleets that are pretty much impossible to deal with on your own in the type of ship you're expected to have at the time. Perhaps the `"gunboats in Alnasl"` event should also reduce the frequency of larger Navy fleets in Wei to make it easier to not only get to Alnasl, but also brute-force it and get your Electron Beam in Wei.

**Comment by pyorokun7** [comment]
Having completed this mission last night, I wouldn't mind this addressed somehow.

After failing some 10-15 times to kill a lone Gunboat in Wei and survive long enough to jump back, I figured that I could try in Alnasl... then I needed at least 10 attempts to go PAST Wei / that no fleet followed me in Alnasl / there wasn't a too big fleet in Alnasl, so I could finally loot my Electron Beam.

I didn't even try to get more than one, I just wanted to complete the mission.

Probably the mission I have reloaded the most so far, forced or not. One thing is to try to get a perfect victory (not lose ships in a battle or something like that) and other having to pray that the RNG would allow me to finish a mission.

**Comment by Chrozayis** [comment]
I recently did this mission and had some thoughts.
1. I really wish a character suggested afterburners. I wasn't able to complete the scouting mission prior to this mission without them either. (The hostile republic-space missions even earlier in the story I did in a corvette with atomic thrusters and no afterburners. Alas, I lost all my corvettes when I accepted too may simultaneous bounty hunting missions.)
2. The main reason I was reluctant to go hunting in Alnasl is the difficulty in carrying the 4 jumps of fuel to get there and back, plus another 300-400 for the afterburners. The other reason was the first time I did get to Alnasl safely and get a beam safely I got ambushed in Wei on the way back. It seemed safer to stick with Wei where I knew safety was right next door.

**Comment by Amazinite** [comment]
How about a hint mission akin to the spaceport hints for tracking down the Sestor or the stolen Star Queen in the Deep missions? Perhaps landing on Deep in Kornephoros could result in an FW captain informing you that FW scouting parties or FW sympathizers in the Dirt Belt have found that Navy ships are patrolling Wei, but that Alnasl seems quieter, and/or landing on Hope would provide some sort of information like "You scan the ships entering and exiting the system. Many of the Navy ships are armed with these new Electron Beams, but they are appearing in fleets to big to take on alone. You notice though that almost all Navy traffic is to and from Alioth and Seginus, while only lone Gunboats are traveling to and from Alnasl."

**Comment by Amazinite** [comment]
With the combination of giving hints to go to Alnasl (#4777) and making it more forgiving if you decide to stick with Wei (#4636), I'd say that this is resolved.
