### ISSUE TITLE
Text substitution from condition variables

### ISSUE THREAD

**Issue by Janaszar** [endless-sky/endless-sky#4173]
As https://github.com/endless-sky/endless-sky/pull/4164 will be allowing developers to use the Phrase system to select "random" choices of values for names, sentences, and the like in developing missions, there needs to be a way to have certain phrase values stored and recalled.  For example, having randomly picked names, cargos, and the like would only work if your initial and on complete messages used the same words; "Alice asks you to deliver Bon-Bons to Charlie" leading to "David accepts the Eclairs from Fiona" doesn't make sense.

As such, I would like it if the save/load method of storing and recalling numeric variables, such as Reputation, be extended to account for strings.
Alternatives, like resetting the RNG seed or "freezing" it somehow, may reduce the available combinations that could be encountered, depending on how "Random" the RNG used is.

**Comment by tehhowch** [comment]
The current supported text replacements are detailed in the wiki: https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#replacement

Note that the transported item is already replaceable. It's my opinion that missions involving named characters that the player should care about are probably supposed to be mission strings using conversations, and if the player isn't supposed to care about the name then generic nouns are preferred to avoid "noise."

Related: https://github.com/endless-sky/endless-sky/issues/2351
https://github.com/endless-sky/endless-sky/pull/2456
https://github.com/endless-sky/endless-sky/pull/3384#issuecomment-350551608
https://github.com/endless-sky/endless-sky/pull/2456#issuecomment-354668281

**Comment by Janaszar** [comment]
Yup, know those replacements.

The main reason I would want such a change is to support "free floating" mini-campaigns.  For instance, if you get a certain rep condition (say <1000 Republic, >1000 FW), you could trigger a mission chain where some FW sympathizers in Republic space offer you a mini-chain of sending supplies.  But if your rep is reversed, then it could be some FW-based Republic spies sending info home, but all using the same mission base.  Seeing #2456 & #3384, I would say that that sort of functionality should also be included.
This way, we can code a baseline mission, write up a few dozen alternative phrases/names/options, and essentially add a ton of "new" missions everywhere.
