### ISSUE TITLE
Using keyboard keys to move in a long list of accepted missions should scroll the list to show the selected mission

### ISSUE THREAD

**Issue by protoshaper** [endless-sky/endless-sky#4174]
**Describe the bug**
As a player with more than 50 current missions, I want the list of current missions to scroll to the mission highlighted on the list even when I am browsing the list with keyboard up and down keys, so that I can see the items around it.

**To Reproduce**
Case A:
1. Accept more missions that can be simultaneously shown on the list of current missions. (With my screen resolution, this is at least 50 missions.)
2. Go to the map screen ('m')
3. Click on the 'Missions' button. The first current mission on visible the list of current missions, but the last mission is not visible.
4. Select the first mission. The mission's details appear at the middle of the screen.
5. Press the up arrow key to move to the last mission on the list.
6. Last mission's details appear at the middle of the screen, but the selected mission is not visible on the list of current missions.

Alternatively (Case B):
5b. Press the down arrow key to move past the end of the visible part of the current missions list.

**Expected behavior**
When navigating to a non-visible item of a list using keyboard, I would expect the list to scroll to show the selected item. This should apply both for moving past the beginning (or end) of the list (Case A) and for moving past the visible end (or beginning) of the list (Case B).

**System (please complete the following information):**
 - OS: Windows 10 pro, 10.0.0.17763 Build 17763
 - Screen resolution: 1600x900, game running in non-fullscreen mode (window is maximized)
 - Game Source: https://github.com/endless-sky/endless-sky/releases
 - Version: 0.9.8

**Comment by Amazinite** [comment]
Given that we’ve added quite a few new jobs since v0.9.8, causing the jobs board to sometimes overflow into the map key, it would be nice if the jobs board could do this as well; limit the size of the jobs and active missions list, then allow it to scroll, using small arrows to indicate that it can be scrolled in that direction.

**Comment by tehhowch** [comment]
The quickest fix to this is to simply update the `acceptedScroll` or `availableScroll` values when the selected mission changes. A better solution is to update the way MissionPanel is laid out, and read information from the "mission" interface specification. Part of that specification would be the size and position of the mission lists. Behavior of the lists with too much content would ultimately be similar to that encountered when you board a ship with many installed outfits.
