### ISSUE TITLE
option to allow engine flares above a ship's sprite

### ISSUE THREAD

**Issue by Variance-Moment** [endless-sky/endless-sky#4181]
**Is your feature request related to a problem? Please describe.**
Currently you only have the option to place engine flares above a ship's sprite. This could cause problems if certain engine exhausts are ex: above a wing but not outside of it.

**Related Issue Links**
I haven't found any open related issues to this.

**Describe the solution you'd like**
Add an option to have the engine hardpoints display an engine flare above the ship's sprite, similar to how drones and fighters have an over and under option.

**Describe alternatives you've considered**
Designing ships with engine exhausts only outside the ship's main frame

**Additional context**
![proposal example](https://user-images.githubusercontent.com/34966837/52382298-7c5ce800-2a29-11e9-8eb4-36f4806dc7bf.png)

**Comment by toilethinges** [comment]
#1185

**Comment by Pointedstick** [comment]
No need to keep two open; closing in favor of https://github.com/endless-sky/endless-sky/issues/1185.
