### ISSUE TITLE
Raised std::out_of_range at departure

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#4185]
**Describe the bug**
bd071c3 raises std::out_of_range at departure.

**To Reproduce**
1. Load this save file: [savefile.zip](https://github.com/endless-sky/endless-sky/files/2855754/savefile.zip)
2. Click on 'Depart'.

**Screenshots**
> terminate called after throwing an instance of 'std::out_of_range'
>  what():  map::at

**System:**
 - OS: Debian/GNU Linux Testing
 - Game Source: Github
 - Version: commit hash  bd071c3

**Additional context**
I have the mission "Wanderers Ap'arak 3: Pug" in the save file.
Pug ship "Hork Ekekek Ptui" try to AI::DoCloak() and then raises std::out_of_range in AI::GetShipsList().

**Comment by tehhowch** [comment]
Thanks for the bug report. Should have a fix up once I can get to a machine.

Bad assumption that cloaking only happens when the player is in system. If the player isn't, then no caching of ships is done for the Pug govt, and voila, `std::out_of_range`. Not sure how this didn't pop up in testing.

**Comment by tehhowch** [comment]
Should be addressed by 7882e00cd382

**Comment by oo13** [comment]
Thank you for quick response!
I confirmed the problem is fixed.
