### ISSUE TITLE
Add tooltips to preferences

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4195]
Okay, so this is really minor, but...

**Describe the bug**
According to @tehhowch on https://github.com/endless-sky/endless-sky/issues/4193#issuecomment-466087008,
> The auto-aim preference refers to aiming your _ship_, not your turrets, to maximize your chance of forward-facing weaponry hitting your target

**To Reproduce**
The "Settings" tab of the "Preferences" screen calls that setting `Automatic aiming`.

**Expected behavior**
The word "aim" means to set the direction of a _weapon_ (such as a turret), not of a ship.

[Wiktionary](https://en.wiktionary.org/wiki/aim) defines "aim" as:
> The pointing of a weapon, as a gun, a dart, or an arrow, or object, in the line of direction with the object intended to be struck

Ships are steered or turned or have their course changed, not aimed.

**System (please complete the following information):**
 - OS: Linux (not that it matters)
 - Game Source: self-compiled
 - Version: commit hash f89a239c73c1c27c7858e51aafe949f60a956328

**Additional context**
I suggest to rename the UI string to match the behavior it controls. The UI string and the preferences.txt data file string are both `Automatic firing`, of course we can't change the preferences.txt string arbitrarily, we have to support existing preferences files.

While we're making changes anyway, maybe change the values from on/off to something more descriptive, or add a tooltip or something. For example, "Automatic turning = turn to face hostile ships / turn manually".

**Comment by jafdy** [comment]
If your weapon is spinal mounted, then how do you aim it? Obviously you do this by ripping it out of your ship keeping long cables attached for power and then you can fire it sideways . . . or you could just turn your ship, you know, the classic way of aiming spinal weapons.
Further a "change of course" doesn't make as much sense when you can fly sideways, something you can't do in the sea.
Although I will agree, something a bit clearer would be a good idea. Perhaps `Automatic *gun* aiming` or `Fixed weapon assist`.

**Comment by Pointedstick** [comment]
"Automatic Aiming" can only possibly refer to turning your ship, since if it applied to turrets, that would imply that you can turn off turret auto-aim which makes no sense.

It may be possible to tweak the string to make this super 100% clear, but I'm not sure there's necessarily anything wrong with the current string.

**Comment by Amazinite** [comment]
If a tool tip is added, then the name doesn't need to change, it can just be further clarified by the tool tip.
