### ISSUE TITLE
Jump drive effect can significantly bog down the game

### ISSUE THREAD

**Issue by omagasohe** [endless-sky/endless-sky#420]
My hapless merchant fleet consists of a lot of ships, 24 bactrians, with jump drives, that actually took sometime to get, Jumping with that many ships makes the game almost look like a stop motion film until the effect goes away. 

At some point I assume jump drives will be purchasable. This would be a progression to the game, start in human area, then see the galaxy after gaining tech. Once you can buy it, you'll added to everything you can buy. You get in to areas where every ship bouncing in the system uses it. imagine a heavy traffic system would be like iron forge was in the early versions of WOW, unplayable. 

Since this is a basic UI game, and not a high end FPS, I'd imagine you'd want to be friendly to mid to lower level graphic cards. and add an option for simpler graphics. I don't have a high end gamming rig, but can play most FPS with low graphic settings.

**Comment by jafdy** [comment]
I have noticed this as well although it did take 200 ships before it became annoying. I thing a simpler effect would help.

**Comment by Wrzlprnft** [comment]
"The game in which you are not limited by ingame money!
the only limit is the budget for your graphic card!"

**Comment by brendanjones** [comment]
I, too, experience frame-rate slowdown after 20 Bactrians with jump drives. Surprising, since a 512mb graphics card aint so bad...
For those of us who aren't as technically inclined, would someone mind posting the text to copy+paste into the data file to simplify that effect?

**Comment by endless-sky** [comment]
```
effect "jump drive"
	"lifetime" 0
```

**Comment by thenerdfreak** [comment]
@Wrzlprnft speaking of zoom, how do I change the zoom to something like, say 50, instead of 100? I have a large monitor and 1 bactrian takes up a large portion of my screen, even at 1600x900

**Comment by Wrzlprnft** [comment]
i don't think it's possible yet

**Comment by brendanjones** [comment]
> effect "jump drive"
    "lifetime" 0

Thanks Endless, much appreciated.

**Comment by omagasohe** [comment]
And you all are awesome. thanks for that.
Personally I still recommend a "setting" for simplified graphics in the 1.0 release.  This being a beta modifying your game is more than acceptable, even encouraged. 

I'll have to say that this is one of the games that plays the best. Even with hundreds of things zooming around it plays fantastic. so much that this stood out like a neon sign in pitch black.

**Comment by Wrzlprnft** [comment]
Since there is already a high-resolution plugin, a low-res plugin is just some work somebody has to do

**Comment by omagasohe** [comment]
When I get home, and can make sure it works I'll start one, that was my intention anyway since this almost breaks the game for me, and changing the data folder is inviting pain later on. 


    On Thursday, December 10, 2015 7:27 AM, Wrzlprnft <notifications@github.com> wrote:
 

 Since there is already a high-resolution plugin, a low-res plugin is just some work somebody has to do—

**Comment by endless-sky** [comment]
I'm not certain, but I would bet that the slow-down is not due to your
graphics card / integrated graphics having too much work to do, but due to
the bottleneck of how quickly OpenGL commands can be issued. There are ways
to issue OpenGL commands in large batches rather than individually, so it
should be quite possible to optimize the graphics code enough that this
would no longer be an issue. I just haven't been looking into it previously
because on my system (integrated graphics on a second-generation i3) it was
working fine, and I figured most people would be running something faster
than that.

**Comment by brendanjones** [comment]
heh...so my computer is just a bit funny in the head. I'm running a 2011 Macbook Pro with an i7, you'd think it would be OK.

**Comment by omagasohe** [comment]
My computer is a $300 low end dual core system with a 5400 radon card with dual monitors. I can play a lot of games if the graphic are tweaked to the low end. I'm usually doing school work or working on code, I've never wanted played with C++, but I'm starting to get that itch...

**Comment by omagasohe** [comment]
https://sites.google.com/site/omagaswastedspace/endless_sky
There is a plug in for a lo-res version of the jump drive created with the above advice. Plug-in is preferable because it's save over version changes.

There is still a noticable effect so you at least see something happening. I like it better than before,.

**Comment by endless-sky** [comment]
0.8.9 includes a change to the graphics code to no longer send draw commands to the GPU for sprites that are entirely off screen. That might help this issue, a little bit. Otherwise, the only solution is to do a more thorough optimization of the OpenGL code, which will be a low priority for me because it is already fast enough for most people who do not have absurd fleets. :)

**Comment by omagasohe** [comment]
That will do fine for now, the data file "fix" works, I posted it as a plug-in so if others have issues it'll be possible to fix.  


    On Wednesday, December 9, 2015 3:53 AM, jafdy <notifications@github.com> wrote:
 

 I have noticed this as well although it did take 200 ships before it became annoying. I thing a simpler effect would help.—

**Comment by endless-sky** [comment]
Eventually I'll get around to optimizing the OpenGL code (or, maybe someone who's actually a game programmer will join the project and help out with that), but for now I'm closing this because the given work-around plus the small graphics optimizations in 0.8.9 are good enough for most people.
