### ISSUE TITLE
Hai Mission: Expanding Business [1] does not check for the presence of mission ships at destination

### ISSUE THREAD

**Issue by isarek** [endless-sky/endless-sky#4201]
**Describe the bug**
Quest progresses on landing at destinations without the freighters or star queen present in the system.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build: `http://mcofficer.me:8080/job/endless-sky-win64/<build number>/`)

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by jafdy** [comment]
What game version is this on?

**Comment by Fzzr** [comment]
@isarek please test with #4202. It looks like it would happen with all Expanding Business NPCs.

**Comment by isarek** [comment]
This is on current nightly. Will try that and report back.

**Comment by Amazinite** [comment]
For the record, you're suppose to actually fill out the template, not leave it blank. :)

**Comment by isarek** [comment]
Will do so in the future. Kinda thought it was just one of those placeholder/example texts and I guess I really wasn't paying. First time actually posting on GitHub, so I'll learn I'm sure.
