### ISSUE TITLE
Should "Marauder <ship>" be "Modified <ship>"?

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#4205]
We have the Modified Argosy. And we have Marauder ships which are basically the same thing. It almost feels like the word Marauder should be replaced with Modified for these ships, both for consistency, and also because should they ever be offered for sale, this would be logical since you can already buy a Modified Argosy.

Thoughts?

**Comment by Nescio0** [comment]
Don't forget the Marauder Fury and Modified Osprey (`persons.txt`).

**Comment by Amazinite** [comment]
I'd say no. While Marauder ships are modified ships, Marauder is a specific title that is important to the lore of those ships. If ship is labeled modified, then that means that any old Joe Schmo could've made some changes to it. But if it's labeled Marauder, then it's been specifically changed by Marauding Max K. 

The Modified Argosy isn't a straight upgrade to the Argosy, but instead a ship with tradeoffs. The Mod Argosy actually has less health than the Argosy, a symptom of whoever modified it simply trying to fit all they can into the ship by removing hull. They have the same engine space, but the Mod Argosy has higher drag and is therefore slower. The Modified Argosy also has less heat dissipation and half the cargo. The only two places where the Modified Argosy gains are in its 26% extra outfit space and 56% extra weapon space, but it loses out on a lot just to gain that.

Marauder ships on the other hand are clearly expertly modified. I'll use the Leviathan as an example, but the Marauder ships all have similar changes done to them, some even having more changes done than usual, such as adding turret or gun hardpoints. The Marauder Leviathans have about 11% more health than the normal version. (All Marauder ships have at least 10% extra HP, some even more.)  The Marauder Leviathans don't lose out in heat dissipation or drag like the Modified Argosy does, having the same heat diss. and drag as the Leviathan. The Marauder Leviathans also have half the cargo space, but in return they gain 10% extra outfit space, 10% extra weapon space, and 17% extra engine space. And that isn't even mentioning the two other Marauder Leviathans, with the weapons instead gaining 25% extra weapon space over the standard version and the engines gaining 83.3% more engine space over the standard. The only place aside from cargo space that the Marauder Leviathans lose out in is increased hull mass.

So there's a clear different in a ship being modified and a ship having the title of Marauder.

The Modified Osprey is an uncapturable person ship, so I wouldn't use it as an example of why something needs changes.

**Comment by Pointedstick** [comment]
> I'd say no. While Marauder ships are modified ships, Marauder is a specific title that is important to the lore of those ships. If a ship is labeled modified, then that means that any old Joe Schmo could've made some changes to it. But if it's labeled Marauder, then it's been specifically changed by Marauding Max K.

To be fair, none of that lore is actually exposed to players while playing the game, so if that's important, it probably should be. :)

**Comment by Amazinite** [comment]
Well really all the lore in game that can be seen right now is through Marauding Max K's hails, since the ship descriptions can't be read.

**Comment by Pointedstick** [comment]
Right. :) So we need more.

**Comment by Zitchas** [comment]
This is hopefully something that will be revealed to the player in pirate missions, or through the Marauder variants being made available for purchase in relevant shipyards. I personally hope that they will be made purchasable. I like the idea of giving players the option to buy customized versions of ships.

**Comment by Pointedstick** [comment]
>  I personally hope that they will be made purchasable. I like the idea of giving players the option to buy customized versions of ships.

Me too!

**Comment by Zitchas** [comment]
EVN had both used and upgraded versions of ships for sale, and one of the first plug-ins I ever used was the one that made all the ship variants available for sale. (subject to the same availability, plot, and licensing restrictions as the base ship).

I personally found the idea of buying a cheap used heavy shuttle to be a really good "first step" up the ship upgrade ladder before I could really afford anything better. Especially during the "merchant" parts of my playthroughs I enjoyed upgrading to used ships at the first available opportunity. 

I know loans are supposed to enable the same sort of thing, but I personally dislike having constant payments hanging over my head and would rather a used vehicle instead of extra debt. The loan system is great if I really need to get a top end combat ship that is just out of my price range, but for everything non-combat related I'd rather skip the loan and take a used ship instead.
