### ISSUE TITLE
Overflow in the misstion "Expanding Business [1]."

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#4206]
**Describe the bug**
The mission "Expanding Business [1]" has the following condition:
> "net worth" >= 4000000000

If "net worth" is less than 0x8000000, the condition always results true in 32bit-int architectures, including 64bit MS-Windows, MacOS, and almost Linux.

**Expected behavior**
If "net worth" is less than 4000000000, the conversation doesn't branch "rich."

**System:**
 - OS: x86_64 Debian GNU/Linux testing
 - Game Source: Github
 - Version: commit hash 3433ecc

**Comment by tehhowch** [comment]
Probably resolving this requires switching `ConditionSet` and the `PlayerInfo::Conditions` map from `int` to `int64_t`, to match that used by the Account class.

**Comment by tehhowch** [comment]
A quick check indicates that this is the only offending condition currently in the core game. It does seem a little unnecessary to change the storage structure for the entire `PlayerInfo::Conditions` map for just this one mission conversation branch, but I can't argue that there are probably plenty of folks wanting to test certain things -- especially monetary -- in excess of 2b.

I'll resolve this by adding a bounds check to the `ConditionSet` constructor (preventing signed integer overflow), and updating the references to the map.

**Comment by tehhowch** [comment]
Fixed by 2c98103f349734342c5601e01e0c10480f92b6f8 and 5855abc699d80efdd9606c5eaba969a53ad2178c
