### ISSUE TITLE
[suggestion] Flak weapons

### ISSUE THREAD

**Issue by egilburg** [endless-sky/endless-sky#421]
Shotgun-style projectiles, a fixed number of pellets travelling in an arc from the source. The closer you are to the enemy, the more pellets will land and therefore the higher the damage. 

- At point-blank range a flak barrage would do heavy damage to a warship if you aim and time it right (most useful in gun configuration as you control angle and timing of all guns firing at once).
- At midrange, flak would be useful as defense from fighters and missiles (most useful in turret configuration as you have wider area of coverage and ability to engage multiple targets).
- Not a long-range weapon.

Could come in different "gauges", e.g. a 6-gauge flak would have less pellets but more damage per pellet (and also a bit longer range and narrower arc of fire) - optimal for heavy barrage or defense against midrange threats; while a 12 or 24 gauge would have more, smaller pellets each doing less damage, optimal against small craft and missile defense.

**Comment by endless-sky** [comment]
The proton gun works this way - each shot splinters into three projectiles,
so it is more effective up close or vs. large targets.

**Comment by Pointedstick** [comment]
Proton guns, the under-appreciated wonder weapons.

**Comment by jafdy** [comment]
You would need to be careful if this is implemented as it could create significant slowdown in larger battles.

**Comment by endless-sky** [comment]
In 0.8.10 I'm planning to add support for missiles that break into submunitions when they get close to their target. That will allow, for example, missiles that split apart to overwhelm anti-missile turrets, and others that burst apart to create clouds of projectiles suitable for damaging clumped-up enemy fleets.

**Comment by endless-sky** [comment]
I've added support for a "split range" weapon attribute in 91baaa1. This makes projectiles split into their submunitions once they get within that range of their target. (See the Thunderhead Launcher in wanderers.txt for an example.)

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
