### ISSUE TITLE
Quarg Thrusters sometimes produce no thrust

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#422]

**Comment by endless-sky** [comment]
Are you sure you have enough energy to drive them?

**Comment by thenerdfreak** [comment]
Energy goes down fast but even when energy is at half way the thrust seems to "stutter" and basically the thrust tail becomes aesthetic

**Comment by thenerdfreak** [comment]
I reset my game and now it looks like the energy goes down instantly instead of slowly before, dunno what caused energy to be weird like that, but issue isn't an issue anymore #QuantumBatteries
