### ISSUE TITLE
Allow weapons to consume more than one unit of ammo per shot

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4223]
Currently, the `ammo` attribute is defined as
>if specified, an outfit which provides ammunition for this weapon. Each time it is fired, **one outfit of that type** is removed from your ship.

Suggested that a number following the name of the ammo type allow the weapon to consume that number of outfits of ammo upon being fired.

E.g. The following would consume four outfits of gatling gun ammo each time the weapon is fired.
```
ammo "Gatling Gun Ammo" 4
```

**Comment by jafdy** [comment]
Out of curiosity, what kind of thing are you expecting this to be used for?

**Comment by Amazinite** [comment]
I would typically expect this to be used when various weapons have a shared ammo type. Using the example already specified of Gatling gun ammo, a Gatling gun turret with two Gatling guns may fire two Gatling gun submunitions at once instead of having a doubled fire rate, meaning that the turret must consume two Gatling gun ammo at the same time. Given that Gatling gun ammo already exists, it makes more sense for such a weapon to consume two of it at once than to create a new ammo type just for the turret.

**Comment by ghoulavenger** [comment]
Just to play devil's advocate, couldn't the same effect be had just by increasing the fire rate (twice as many guns, so fire twice as many shots)? I'm not saying that it's a bad idea, but I don't feel like it's overly necessary if all you want to do is use shared ammo types. The proposed change feels more to me like you'd want to be able to change the behavior of an individual weapon (like using more energy to overcharge a laser which could be done with variants, like the modified blaster).

**Comment by Amazinite** [comment]
Fire rate can only be increased so much. Once you hit the cap, you can simulate higher fire rates through the use of submunitions, but that’s when you run into the scenario where you need to be consuming more than one ammo per shot, as each shot is actually firing more than one projectile.

**Comment by Amazinite** [comment]
An example I used elsewhere is that the inclusion of this mechanic could allow for more novel weapons, such as a set of aliens weapons that all use the same ammunition, but they require different amounts of the ammunition per shot. Simply saying “just increase the fire rate” means that the more powerful weapons that use more of this ammunition can only increase in fire rate to increase in power and ammo usage, but allowing the use of more ammo per shot means that we could design a weapon that uses say 5 ammo per second by firing 5 times a second, while another weapon may consume 30 ammo per second by firing once every 2 seconds and consuming 60 ammo per shot. That is a more interesting scenario than simply upping the fire rate every time.
