### ISSUE TITLE
Flagship to not drift forever after a jump

### ISSUE THREAD

**Issue by pyorokun7** [endless-sky/endless-sky#4228]
Somewhat related to #4124, there are some moments when I just want to move my fleet somewhere else, but I don't want to hold J at each step to ensure that all ships will arrive at the same time.

Why would I want to arrive in-system with all my ships? Because if I select the planet, but there are slower ships in my fleet, then some or most of my fleet will be in the system and reload fuel/repair/reload automatically when my flagship when my ship lands. BUT the slower ones won't, so I will have to manually land again just so my fleet is on top status.

A solution I do sometimes is to make my flagship either the slowest or one of the slower ones, to ensure that the whole fleet is in-system when I land. This is kind of inefficient and limitative, sometimes you want your flagship to be the absolute best.

Other times, I just set the system destination, but no the planet, so I will arrive... and then drift endlessly if I get distracted. Sometimes I drift so much that it is faster to jump out of system and back than to let the ship fly back to the planet and land.

So if a jump fleet command isn't available, perhaps an option where the flagship won't drift forever after a jump? If I want to fly to the end of the system, that is fine, just not right out of a jump

**Comment by jafdy** [comment]
Or you could stop one system early and then jump the last one when you are ready.

**Comment by Amazinite** [comment]
Is this not basically asking for #1706, #2815?

**Comment by xzcvczx** [comment]
if not anything like braking what about going into an orbit around the sun

**Comment by Pointedstick** [comment]
I feel like a Fleet Jump command is the bennet approach, if we want to do anything for this.
