### ISSUE TITLE
Jump button cycles systems instead of jumping

### ISSUE THREAD

**Issue by credman0** [endless-sky/endless-sky#4229]
**Describe the bug**
When I press "J" with a system selected on the map, it instead cycles through systems the same behavior as if I had pressed tab

**To Reproduce**
1. Leave the planet
2. Press "M"
3. Select a system
4. Press "J"

**Expected behavior**
Should jump to the selected system

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Source: self-compiled
 - Version: Commit b73d640aa3285b794c179086f7cff454234b14ad

**Additional context**
I tried remapping the jump key (to space) but it still had the same problem. I did have a hyperdrive installed.

**Comment by credman0** [comment]
I just tried installing the game through Lutris, and had the same problem again.

**Comment by MCOfficer** [comment]
this is intended behavior (see #2158), but imo we can have a discussion about whether it's useful or not

**Comment by credman0** [comment]
Then I don't understand how to actually initiate a jump maybe? Because I tried several things and I can't leave the starting planet.

**Comment by MCOfficer** [comment]
you select a system on the map, then exit the map (`M` again), *then* press J. If you don't select a system, ES will automatically pick one.

on a side note, isn't the lutris version outdated (0.9.7)? not that it matters in this case

**Comment by credman0** [comment]
Ok thanks a bunch it does work. For what it's worth, I don't think that was explained well in game.

**Comment by MCOfficer** [comment]
yes, we have a smorgasbord of issues about giving new players a better introduction (
#2946, #1893, #3513 just to name a few)
