### ISSUE TITLE
save

### ISSUE THREAD

**Issue by yahsboymatt** [endless-sky/endless-sky#4233]
Please add "Delete Confirmation" pop-up, or allow backing up saved game.
  
Twice mid-game after many hours after landing a wrong key press or mouse pad enable causes the whole character save tree to be deleted with no confirmation!  Trying to get to map and instantly give the 'new character' creation screen.

quit disheartening.

**Comment by tehhowch** [comment]
Care to provide more details? Specifically, details of your game's version, keys pressed, computer system information, etc? 

There are already confirmation dialogs when deleting pilot files, as of at least version 0.9.7: https://github.com/endless-sky/endless-sky/commit/4b5a2917036003821a1bd2cac4c14d96c76131f1

**Comment by jostephd** [comment]
Pressing that "Delete" button brings up an OK/Cancel dialog where OK is the default, so if you accidentally press delete and then accidentally press enter then _all saves of your pilot_ will be deleted. Maybe that's too few failsafes? We could make that dialog require the user to type "yes" or the pilot's name for extra confirmation... but it would be best to get that extra info from @yahsboymatt.

**Comment by jafdy** [comment]
This is consistent with them number of prompts across the games industry. The only change I can see happening is you being forced to use the mouse for each button.
While it is tempting to add extra failsafes to something there is such a thing as too much and using repository level confirmation is probably that step to far.

**Comment by Zireael07** [comment]
Maybe cancel should be the default?

**Comment by jostephd** [comment]
@jafdy I don't know many games that provide a button for deleting not only your latest savefile but also all the ones preceding it. I think the amount of failsafes currently coded is appropriate for deleting a _single_ savefile but not for deleting an entire pilot _including all its history_.

**Comment by yahsboymatt** [comment]
Ok, sorry been unavailable for a few days.  I thought I was submitting a suggestion regarding enhancement, not bug report.

However, here goes;
    OS Deepin, (fresh install) the repositories are changed to Stable Debian (patched current)
    Endless sky version is 0.8.11 (Clean install from repo, no updating, no tweaking.)

During game play I purchased a couple scouts to work on fleet movement.  I then tried it with fighters, which failed.  Movement of my 'capitol' ship was limited to one sector at a time.  I sold the 'fleet' and my ship's movement was still limited to a single sector.  I created a new account afterwards, during viewing the settings menu my saves deleted.  I'm guessing Endless-sky was corrupted on install.  

Afterwards I installed endless-sky on my main partition which runs MX Linux 18 (patched current) and it works flawlessly.  This instance is also set to stable repositories.

If you'd like a compressed copy of the assumed corrupted /usr/share/games/endless-sky directory dropped to a Google Drive account it is doable.

Again, please excuse the lag in replying.  Please close this thread.

Matt

**Comment by MCOfficer** [comment]
that explains it, 0.8.11 is over 2 years old, it probably didn't have such safety features.

Since you're on linux, you can [build from source](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions) with relatively low effort to get the latest version.

**Comment by Pointedstick** [comment]
Yep. We're hoping to get a new release out soon, but even so, the version available on Debian-based distros is always going to be ancient.
