### ISSUE TITLE
Expedition to Hope mission doesn't check for free cargo space

### ISSUE THREAD

**Issue by Recovery0ne** [endless-sky/endless-sky#4235]
Version 0.9.8
Expedition to Hope mission doesn't appear to check for free space in your ship.
Shuttle with 20 tons of cargo full.
Get mission to take equipment to Hope.
Shuttle now has -4 tons of cargo.
Also, when you complete the delivery, it changes the shuttle to +4 tons free / 16 tons in use.

Apologies if this is a duplicate, I looked though the issues and didn't see anything recent on this topic.

**Comment by tehhowch** [comment]
What was the cargo? Commodities? Those were sold off automatically when you departed, without warning, because they are just commodities.

You will only get a "would you still like to leave" prompt when you would be selling outfits or failing a mission due to space constraints.

**Comment by Recovery0ne** [comment]
Cargo was food, even when flying in space about the ship thought it had -4 cargo via the info panel. Other missions I've seen it automatically sell to make from from the job board. This was a spaceport encounter.
I can attempt a new game and screenshot if you wish.

**Comment by tehhowch** [comment]
A reproduction on v0.9.8 is not useful - if you reproduce, please do so with a source compile / MCO nightly build.

**Comment by Recovery0ne** [comment]
Hey, sorry not versed with building stuff for Windows. If I may ask,  M*C*O's script here, https://steamcommunity.com/app/404410/discussions/0/1700542332319963311/ is that what you are referring to?

Thank you for the assistance.

**Comment by Recovery0ne** [comment]
Ha, well, guess MCO's script worked. I just reran the mission and upon taking off, said sold 4 tons of food.
Sorry for being a pain in the rear.
