### ISSUE TITLE
[Feature] AppImage binary

### ISSUE THREAD

**Issue by koutoftimer** [endless-sky/endless-sky#4236]
**Problem:** repositories of supported GNU\Linux distributions didn't have latest release version available.

**Solution:** [AppImage][appimage].

**Examples:** 
* [build script][build-script] from random repository 
* [cmake example][cmake-example] from official docs
* [build script][build-script-appimage] from official docs

[appimage]: https://appimage.org/
[build-script]: https://github.com/koutoftimer/sqrc/tree/master/c%2B%2B
[cmake-example]: https://docs.appimage.org/packaging-guide/from-source/native-binaries.html#cmake
[build-script-appimage]: https://docs.appimage.org/packaging-guide/from-source/native-binaries.html#using-cmake-and-make-install

**Comment by Pointedstick** [comment]
+1, this makes a lot of sense. I happen to know and work with all of the AppImage developers so I can direct any technical questions accordingly. :)

**Comment by MCOfficer** [comment]
Just stumbled over this issue, it's been resolved a while ago: #4918

**Comment by tehhowch** [comment]
Closing resolved, @koutoftimer please comment if this is not accurate.
