### ISSUE TITLE
Projectile that is not destroyed when it damages ships

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#424]
Maybe a decently powerful railgun or something that could penetrate multiple ships

**Comment by endless-sky** [comment]
Right now, the only way a projectile can damage multiple ships is if it has a blast radius. Making a projectile that could pass through one ship (damaging it) and then go on to damage another would mean every projectile would need to remember what ships it has already hit so that it cannot damage a single ship twice. That's doable, but maybe not worth adding support for unless there's a big demand for it.

**Comment by luiges90** [comment]
what about having the projectile damages any ship that is overlapping with it every frame, and will not get destroyed upon hitting any ship?

(Yes large ship will take more damage that way, but this is one simple way of doing similar effect the OP mentioned)

**Comment by brick96** [comment]
It makes sense that a bigger ship would take more damage since the shot would go through alot more of the ship

**Comment by jafdy** [comment]
Nice idea but I thing I would be inclined to put it as a main gun and use it as an artillery weapon.

**Comment by thenerdfreak** [comment]
I was thinking more of a huge beam cannon that fired a single shot that instantly pierced all ships it went through (no need for modifications to the engine if it was instant right?) and then had a recharge time

**Comment by Tufton** [comment]
>
> I was thinking more of a huge beam cannon that fired a single shot that
> instantly pierced all ships it went through (no need for modifications to
> the engine if it was instant right?) and then had a recharge time


Lux Ult

**Comment by fcfort** [comment]
How does this piercing rail gun make sense within the game? Does it only pierce if shields are down? Is it going right through all the shields and hull of every ship it pierces? Does it destroy every ship it pierces? How is it not destroying all these ships when it leaves holes in all of them?

**Comment by thenerdfreak** [comment]
@fcfort I was thinking ignored shields but did decent hull damage, and imparts a lot of heats (Think particles moving through the ship, not something blasting a big hole in it)

**Comment by Pointedstick** [comment]
That would be a ridiculously unbalanced no-brainer of a weapon.

**Comment by thenerdfreak** [comment]
It's downside would be extremely slow fire rate and moderately low accuracy

**Comment by thenerdfreak** [comment]
And to further nerf it, 120 pts of weapon space :p

**Comment by brick96** [comment]
A big weapon, on a big ship, perfect for large targets but weak against smaller ships. The particle cannons are alot like rail guns now that I think about it

**Comment by frameworld** [comment]
> @endless-sky > Right now, the only way a projectile can damage multiple ships is if it has a blast radius. Making a projectile that could pass through one ship (damaging it) and then go on to damage another would mean every projectile would need to remember what ships it has already hit so that it cannot damage a single ship twice. That's doable, but maybe not worth adding support for unless there's a big demand for it.

Well, you can let the projectile remember the last 2 targets. Should be sufficient if a ship can't catch it.

**Comment by anonybosch** [comment]
120 tons of slow-fire, moderately-accurate goodness for battles that last on average 20 seconds?

Put me down for a dozen... to start.

**Comment by erprice** [comment]
I can see some very interesting combat and story elements here. I like the idea of a ship with a single large gun for use against very large ships, but useless against smaller ships. However you will need to be very careful about balancing it.

There are lots of knobs you could turn:
 - damage scales with the size of the target
 - gun is forward firing but ship is slow to turn, making targeting difficult
 - takes up multiple gun slots (useful to limit what ships it can be installed on)
 - consumes an excessive amount of weapon space
 - consumes excessive power, draining your battery after each shot
 - generates a lot of heat, further restricting your rate of fire

Taking up several gun slots could be graphically represented by merging several beams into a single beam like the death star superlaser.

If it's still too imbalanced for player use, make it a one-time alien superweapon that takes up a story arc.  E.G. your side has a fleet of warships decimated in the initial encounter, so a second fleet of smaller, nimbler ships is assembled to destroy the menace. Maybe a watered down version becomes available to the player some time after the mission is completed. Or the same gun is made available but player options for installing it are very limited.

**Comment by frameworld** [comment]
I would like an unique extremely powerful weapon slot on your ship.

Some ships are built around cargo, others around engines and again others around some sort of super-weapon? Nice!

**Comment by thenerdfreak** [comment]
I agree maybe make it a 1-time weapon, so you can't just obliterate everything with a fleet of them. Death star beam sounds nice :p

**Comment by brick96** [comment]
a HUGE energy drain, making it so it requires a large (or several large) batteries
