### ISSUE TITLE
Why story choices should make clear how big their consequences are.

### ISSUE THREAD

**Issue by frameworld** [endless-sky/endless-sky#426]
In the real life, you an not replay with another choice (at least until somebody invents a time-machine).
* Thus you make choices as good as you can and learn from errors.

In a game however, you want to explore all alternative time-lines.
* Some developers call this replay-value.

But nothing is more frustrating than not knowing which choices matter. You end up save-loading.

Because of this, I think choices should make clear whether they are:
* crucial (you can die, get a wanted criminal or something alike)
* intermediate or long-term (you will see the consequence in the same dialogue vs your storyline will alter)
* or optional (doesn't make much of a difference after the dialogue)

A choice is not
* optional when possible result-branches dry out.
* crucial if it succeeds or fails a quest.
* intermediate if it does not alter other quests in any way.
* long-term if it alters other quests in a way no easy math can predict.

I don't say the right choices should be made clear. Just that occasions where it makes a difference should be highlighted.
* Because it reduces save-loading and frustration.

Also, I think this deserves it's own wiki entry or paragraph, because it is not an obvious knowledge.

**Comment by endless-sky** [comment]
When you're being asked to make a big decision, the conversation text usually says something like, "You can tell this is going to be an important decision..."

But, it wouldn't make any sense to me to require that every conversation include a note explaining whether or not your choices are important. In real life, no one pops up and says, "Hey, this choice could change your life!" You just have to figure that out yourself.

**Comment by anonybosch** [comment]
anonybosch added the <b>aw, poor baby</b> label just now.

**Comment by frameworld** [comment]
In the real world you can extract information from the sound of somebody's voice.
* Not in this game

For me it's a huge difference as the sound of a voice and the time somebody takes to answer give a lot of clues.

It is hard for me who has not much participated in social life to get something that is obvious to you without a look at somebody's face, moves or the sound of a voice.

It is also hard to get an idea how familiar you are with a character, because IRL I would not meet just 1 person every week when being a spaceship-captain.
How many meetings make you be a "bit/early friend" of someone which doesn't take every word you say as final, but tell you his thoughts before you both come to a conclusion?


If you want to evade language barriers and make this game open to anyone, please consider what I wrote in the OP.

There are peoples which really need more information about a situation before feeling comfortable making serious decisions. And comfortable is what a player should feel, or not? At least in most situations when the storyline doesn't demand otherwise.

**Comment by endless-sky** [comment]
For a lot of people, that uncomfortable feeling of knowing that anything
you do might have unforeseen consequences, is part of what makes role
playing games so fun and engaging. (And for anyone else, there's save /
reload.)

**Comment by omagasohe** [comment]
I vote with endless. The fun is finding out that you should have kicked the sweet innocent girl's butt because later on in the game she came back as a super powerful zombie that wipes the floor with you... 

You know, life is kinda like that, you'll never know when that little decision will impact your whole life. When I was in my late teens I biked everywhere, one day crossing a large street that I crossed frequently, I decided to stop at the edge of the road instead of crossing to the median like I did almost every time. A guy had a heart attack while driving and took out the light pole i'd have been resting against. 

Stuff happens. Sometimes there isn't any warning.
