### ISSUE TITLE
Will fuel ever have a cost?

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#427]
Just curious if we intend to ever have fuel cost something for the player.

**Comment by brick96** [comment]
i dont think so as the fuel comes from pretty much anywhere:harvested from gas giants or solar winds. though it would add some value to ramscoops.

**Comment by endless-sky** [comment]
In Escape Velocity (the game I patterned Endless Sky after) fuel had a cost, but it was cheap enough that the cost never really played a role in the game except in rare cases where you somehow manage to spend your very last credit and then find you don't have enough money for fuel. It didn't really add anything to the game, and in addition you had to remember to click the refuel button every time you landed. So, I decided to just make fuel free.

**Comment by Tufton** [comment]
^  this guy gets it
