### ISSUE TITLE
Endless Sky crashes in Ubuntu 18.08.2

### ISSUE THREAD

**Issue by willye08** [endless-sky/endless-sky#4275]
**Describe the bug**
Running Endless Sky 0.9.8 in Ubuntu 18.04.2. At random times during game, usually in a map view the game will stop responding and then after waiting 30-60 seconds will just either quit on it's own or generate a text box with the Endless Sky logo that says it has stopped responding and gives an option to either "Force Quit" or "wait"
**To Reproduce**
1. Go to 'Endless Sky...'
2. Click on 'Just begin play....'
3. problem will occur when in a map view
4. No error generated.

**Expected behavior**
Game/system stops responding until program "exits" then response is returned to system

**Screenshots**

**System (please complete the following information):**
 - OS:Ubuntu 18.04.2 LTS
 - Game Source: either Steam version or installed from Ubuntu installer
 - Version:  "0.9.8" 

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by tehhowch** [comment]
Does this persist in a source build? Map related code has changed considerably since v0.9.8.

**Comment by willye08** [comment]
I’ve not done that. I just installed the package from the repository.


Sent from my iPad

**Comment by tehhowch** [comment]
Please also share some hardware information regarding your graphics capabilities.

Have you added any plugins?

-----
Instructions on building from source are available in the README (and for Linux is rather straightforward when compared to osx/Win).

**Comment by tehhowch** [comment]
There is a new official release; please reproduce and update your report with additional details.
