### ISSUE TITLE
Suggestions for depreciation on outfits and ships: make it time-based

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#428]
Right now the game has zero depreciation for outfits and ships, which is nice because it allows you to try things out without any penalty and prevents you from winding up without enough money to buy engines or a reactor. But it also makes amassing money really easy and results in a ship "upgrade path" that's more linear than it might otherwise be. The EV games, by contrast, had extremely harsh depreciation rules; as soon as you bought something, selling it immediately gave you back only half the purchase price!

I suggest something between these: time-based depreciation. In the first day, or week, or month even, there can be zero depreciation. After that, ships and outfits start depreciating by some percentage of their original value, eventually settling on a stable long-term sale price that's some fraction of their original price.

This would preserve players' ability to easily test different combinations penalty-free and keep the safety valve against running out of the money you need to buy your ship engines or a reactor, but tone down the extreme sale prices on potentially very old goods that contributes to letting players get very rich very quickly.

Looted outfits could also start at the lowest possible depreciation level. This would maintain selling looted outfits as a viable moneymaking strategy, but tone down its effectiveness without fundamentally altering it.

**Comment by brick96** [comment]
#312

**Comment by Pointedstick** [comment]
This is refinement of the concept proposed there that addresses all the concerns.

**Comment by endless-sky** [comment]
That sounds like a reasonable enough idea. Implementing it correctly would be a little tricky; I guess each ship would have a list of (outfit, age) pairs, and when you sell an outfit it checks the "newest" pair in the list to get the price.

**Comment by Pointedstick** [comment]
And once the age-tracking plumbing you describe is in place, that would open the door for cool features like degraded function for depreciated things, faster depreciation and degradation for things that are used more often, superior things that depreciate and degrade more slowly, outfits that reduce depreciation and degradation, paying to repair depreciated things to recover functionality and value without having to replace them, etc.

**Comment by johndh** [comment]
I like the idea of used and plundered outfits selling for less, but the idea of them actually losing effectiveness over time and needing to be replaced sounds like a massive hassle, especially since some outfits are only available in particular places.  I don't want to go all the way to The Deep to replace my atomic engines, and then go somewhere else to replace my reactors, somewhere else to replace my weapons, etc.

**Comment by frameworld** [comment]
I agree with jondh.

When I look at games like X3-Reunion, big ships here do not feel as big.
In X3, it would not be a problem to have the weapon from a small ship stored in a big ship's/station's cargo-space for later usage.

Before this is implemented, it should be 1. optional(hardcore mode) or 2. there should be a home-base without that penalty but no initial items or automatic restock.

**Comment by Pointedstick** [comment]
Degradation doesn't have to go along with depreciation. It's just an idea for a feature that depreciation would enable.

**Comment by jmhorjus** [comment]
This is implemented in https://github.com/endless-sky/endless-sky/pull/852.
