### ISSUE TITLE
Alien Idea

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#429]
An idea would be aliens that inhabit planets around stars slightly to the south of the Free Worlds.
Their main ships would be large, slow, cumbersome ships with many figther bays that sent out fighters instead of used their armaments against you (they could still have high-tech anti missile turrets and even high-tech missiles to fire at you from a distance) Their ships would need a relatively high crew count (~200) since they would need to be massive. Perhaps they could be peaceful originally, but some part of the post-Civil War war with the Alphas caused humans to invade their space looking for resources (with the newly acquired Jump Drives) and attempting to take their ships for use against the Alphas.

**Comment by Wrzlprnft** [comment]
reminds me of Bees. huge ships, honeycomb like fighter bays... i am working at the moment on an alien race in that region, at least on an alien planet, but i would like to make something like that

**Comment by thenerdfreak** [comment]
Considering I have zero coding skills... you see :p

**Comment by thenerdfreak** [comment]
and yes I like the honeycomb shape/ bee idea. Maybe a bee related name?

**Comment by Wrzlprnft** [comment]
Well, the most work intensive thing is making 3d Modells for the new outfits and ships
those are the one i am currently working on, it's a water/ice based alien specias
http://imgur.com/a/cwRR6
from top to the bottom: a ramscoop, a tiny shield generator, steering, thruster, ice cannon
and they will not be much stronger than the already exisitng stuff
Maybe the balancing might take some time too
To the name: take bees and put it into google translator, and change the language until you find something that sounds cool, try latin and old greek an such ones

**Comment by thenerdfreak** [comment]
I put the latin name :p and An idea for your alien species would be that they literally can't have heat or their ship melts :p

**Comment by Wrzlprnft** [comment]
well, since the thrusters and reactors gonna be quite heat efficient(they don't burn things), that should be not the problem :D 
but honestly, i just started monday, and i have not a clear idea how they will end up, i am just making piece by piece, and once i have everything to equip one ship, i'll try how the ideas and the code harmony

**Comment by Wrzlprnft** [comment]
that's the prototype ship i am using, but since it was the first thing i made with blender, it is pretty ugly, and will be probably completely remodelled
there's also a own projectile- and impact- and thruster-(which is just a poorly placeholder) effect.
<img width="693" alt="prototype" src="https://cloud.githubusercontent.com/assets/15857993/11733106/9d25f76e-9faa-11e5-8622-afb7ef925341.png">

**Comment by thenerdfreak** [comment]
How do you use blender? I want to make a ship but have no idea what it is tha tyou make it with

**Comment by Wrzlprnft** [comment]
i watched some videos,
basically, you add objects like planes, cubes, spheres, lines, circles.
then you manipulate them (Rotating, scaling, moving single edges and so on and so forth) until it has the shape you want
then you add a light source and the textures you want, render the image, save it
those are the basic steps.
i just recommend just watching tutorial videos.
if you do not find understandable videos or do not understand blender, i can make a special video, where i try to focus on stuff you might need for your purposes.

**Comment by thenerdfreak** [comment]
Where do i get blender tho

**Comment by Wrzlprnft** [comment]
http://www.blender.org/

**Comment by Wrzlprnft** [comment]
i started with this video
https://www.youtube.com/watch?v=y__uzGKmxt8
if you want to make stuff like the @endless-sky did, you might need to use a different render method though

**Comment by Wrzlprnft** [comment]
i just finished the next outfit thumbnail, this is going to be a small energy core
![small ice core](https://cloud.githubusercontent.com/assets/15857993/11733372/f9654ed8-9fac-11e5-93a7-6b86a1214b07.png)

**Comment by Wrzlprnft** [comment]
if you want to make a ship looking similar to the ones which already exist, you could use a graphic editing programm like gimp or paint.net to cut all the ships apart and assemble out of the parts a new one fitting your imagination

**Comment by frameworld** [comment]
@Wrzlprnft : I like http://imgur.com/a/cwRR6
But if it is hard work, you use the program wrong. The most difficult part should be to come up with design-ideas.

1. make a sketch.
2. get an idea of the proportions.
3. if curves, circles, etc are a problem, try to have a look at bezier-curves on wikipedia. Use relative positions
Then you just need to duplicate vertices of a tube and input a relative offset/rotation to the previous position.
It is a long work, if done manually, but this way it is at least not difficult.

Gimp has nice tools for paths which use bezier-curves, maybe Blender has it too?

**Comment by Wrzlprnft** [comment]
oh it becomes easier and easier, remember i used blender the 1st time on monday.
i have umpteenth design ideas though
(shift d, strg r z 90 ;))
yes, mostly i do the spirals by designing a bath and the relate a bezier circle as bevel object

**Comment by thenerdfreak** [comment]
My basic Idea for the Drone/Fighter: the Halictidae
![bee fighter](https://cloud.githubusercontent.com/assets/15973422/11744029/24def5ee-9fd2-11e5-99bd-1d1191815c00.PNG)

**Comment by Wrzlprnft** [comment]
Shall i try to model it?

**Comment by thenerdfreak** [comment]
If you wish, I have school, after school I'll put out a general picture of an "Alveare" (hive) ship that is to house these "sweatbees"

**Comment by Wrzlprnft** [comment]
I am at university in a boring as hell lecture about microprogramming, so... yeah :D

**Comment by Wrzlprnft** [comment]
![the halictidae](https://cloud.githubusercontent.com/assets/15857993/11744768/942e2b2c-a013-11e5-86fd-67e6714e65f7.png)

**Comment by Wrzlprnft** [comment]
Not very sophisticated yet, but that should be pretty much the basic shape?

**Comment by frameworld** [comment]
If the grey parts are landing-areas, they could be honey-comb like (hexagon-cells).

Green reminds me more of a grass-hopper than a bee - if that's the intention, it needs more bee-like details.

**Comment by thenerdfreak** [comment]
google a sweat bee, I went for the whole green shiny thing. And the grey areas are meant to look like the wings, they can be where the "thrusters" go. This is meant to be a small figther. About to sketch out a carrier when I get home from where I'm at (with the boo)

**Comment by thenerdfreak** [comment]
Something to this effect; but probably more appropriately portrayed (mine looks like a 3 year old drew it)
![bee queen](https://cloud.githubusercontent.com/assets/15973422/11759010/3fe87854-a038-11e5-85c5-7d78d1b61fd5.png)

**Comment by Wrzlprnft** [comment]
I just copyed the style the image has, i can probably make them way look more like wings
and they can be animated in the game too
i am gonna build the alveare, too, and then i'll try what i can do to make it look better

**Comment by Wrzlprnft** [comment]
My internet is down this weekend as it seems, beside my phones, and that's not enough to play smite or something like that with my friends, so i am gonna work on the game more than usual :)

**Comment by Wrzlprnft** [comment]
![the halictidae2](https://cloud.githubusercontent.com/assets/15857993/11762180/4c847ee4-a0df-11e5-9b57-9dab325ea64e.png)

**Comment by Wrzlprnft** [comment]
![the halictidae2](https://cloud.githubusercontent.com/assets/15857993/11762234/b72edad2-a0df-11e5-8304-af9a1c6e875f.png)

**Comment by Wrzlprnft** [comment]
![the halictidae3](https://cloud.githubusercontent.com/assets/15857993/11762268/ade3ae20-a0e0-11e5-9bf6-d81b10da0686.png)

**Comment by Wrzlprnft** [comment]
how do you liek them @thenerdfreak

**Comment by thenerdfreak** [comment]
I like the way the Halictidae is turning out, I'm gonna label the one i'm in the process of making, because I realize how confusing it must be to just see a hexagon in a random place and be like "what is that " lol

**Comment by Wrzlprnft** [comment]
Am i allowed to try the carrier too? or do you want to try it first, and just in case you just don't get a model which suits your idea it's my turn?

**Comment by thenerdfreak** [comment]
I'm in the process of drawing out the carrier right now, I left off a few specific, necessary details

**Comment by thenerdfreak** [comment]
![bee queen attempt 2](https://cloud.githubusercontent.com/assets/15973422/11762324/5cdd3952-a0a8-11e5-8a35-a2c761a1a8df.png)

**Comment by Wrzlprnft** [comment]
Oh, nice :)
Shall i model this?

**Comment by thenerdfreak** [comment]
Anything I post on here is free for anyone to attempt, because I tried my hand at modeling and it looked like a hexagon with noodles coming out of it

**Comment by Wrzlprnft** [comment]
i like noodels.
But okay, once the hyperdrive is rendered, ill try it :)
how about the video?

**Comment by thenerdfreak** [comment]
nah it's fine, I have school until next tuesday, after then I have two weeks to learn. I'll prolly learn over the holidays

**Comment by Wrzlprnft** [comment]
I only need to fit in the colors

and maybe i fill the honeycombs not just with a yellow texture, but maybe with a honey simulation

<img width="610" alt="alveare" src="https://cloud.githubusercontent.com/assets/15857993/11762585/7020222a-a0eb-11e5-97ef-8c8c9dd27827.png">

**Comment by thenerdfreak** [comment]
Wouldn't that be kinda hard to render on the actual game? and looks exactly like I had in mind, even the tiny little head xD (It's gonna be a pretty sizeable ship)

**Comment by Wrzlprnft** [comment]
mmh, in the actual game, you woulnd't do the simulation.
you'll just feed the game with more than one picture for the ship, which the game displays one after another

**Comment by thenerdfreak** [comment]
wouldn't that mean lag for people who have potatoes as CPU's?

**Comment by Wrzlprnft** [comment]
it's the same way as thrusters work

**Comment by thenerdfreak** [comment]
never knew thrusters worked like that

**Comment by Wrzlprnft** [comment]
@thenerdfreak i had to replace the green with yellow, becaus i found no fitting shade of green

![alveare](https://cloud.githubusercontent.com/assets/15857993/11762734/2618292e-a0f1-11e5-9ebe-bae2fb5f4124.png)

**Comment by thenerdfreak** [comment]
Looks better that way either way, didn't mean to put green xD (i'm almost colorblind )

**Comment by thenerdfreak** [comment]
Imma be gone for a while , I have to  be in a half-time show with the other poolies

**Comment by mdsmestad** [comment]
I don't know the wings look kinda silly..So does the bee stripe pattern, I like the honeycomb look, that makes sense but not he other bee refferences..You should make the ship grey or possibly dull brown for that alien vibe

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
