### ISSUE TITLE
Drop dynamic premultiply

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#4290]
Currently ES does a premultiply on images that are not in the premultiplied alpha format:

```c++
// Special case: if the image is already in premultiplied alpha format,
// there is no need to apply premultiplication here.
if(path[pos] != '=')
{
	int additive = (path[pos] == '+') ? 2 : (path[pos] == '~') ? 1 : 0;
	if(isPNG || (isJPG && additive == 2))
		Premultiply(*this, frame, additive);
}
```

This is a not-so-small performance issue. Look (got this with perf):

```
   4.67%  endless-sky  endless-sky              [.] (anonymous namespace)::Premultiply
   3.36%  endless-sky  libz.so.1.2.11           [.] inflate
   1.11%  endless-sky  endless-sky              [.] (anonymous namespace)::Search
   1.00%  endless-sky  libc-2.29.so             [.] __strcmp_avx2
   0.91%  endless-sky  libz.so.1.2.11           [.] adler32_z
   0.77%  endless-sky  libc-2.29.so             [.] __memmove_avx_unaligned_erms
 ```

And this is one of the things that is pretty easy to avoid: Just require that people make their images with that format.

What do you think?

On an unrelated note: Who/What is calling inflate?

**Comment by jafdy** [comment]
This would have issues for other content creators who can't necessarily premultiply images, so the function would need to be left in. So what you really want is for as many base game images as possible to be premultiplied.

**Comment by Rakete1111** [comment]
I know nothing about image stuff but is it hard to premultiply images? But otherwise yes, that's a good idea.

**Comment by endless-sky** [comment]
In general, I'd like there to be as low a barrier to entry as possible for content creators. PNGs with premultiplied alpha can't be saved, or even read, by any image-editing program - they have to be created with a special [command line tool](https://github.com/endless-sky/endless-sky-tools/blob/master/blend.cpp). If opened in a normal image editor, the additive parts of the image won't be visible, and may even be discarded.

Also, note that on most systems the bottleneck in loading the game will be disk speed, not CPU time. That is, even if every PNG were premultiplied it would not speed things up at all unless all the image files are already in the disk cache. (And in that case, loading the game takes less than a second anyway, so it's a moot point.)

**Comment by Rakete1111** [comment]
Thanks for clarifying!
