### ISSUE TITLE
Shield generator outfit graphics swapped

### ISSUE THREAD

**Issue by piannucci** [endless-sky/endless-sky#4301]
**Describe the bug**
D67-TM and D94-YV graphics are swapped.

**Expected behavior**
More powerful shield generators have more... spiky... visuals.

**Screenshots**
<img width="604" alt="image" src="https://user-images.githubusercontent.com/552810/58454635-b3443000-80e4-11e9-8956-7b0b9cf5dcca.png">

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Game Source: Steam
 - Version: 0.9.9

**Comment by jafdy** [comment]
Both the images and the data calling those images have not been changed since they were first introduced over 5 years ago.

**Comment by piannucci** [comment]
Okay, my bad.  I guess the spikes are supposed to look bigger rather than more numerous?

**Comment by MCOfficer** [comment]
now that you say it, it does indeed miss a bit of continuity. although one can probably lore that out in the description, or in their own headcanon respectively.
