### ISSUE TITLE
Mission cargo gets loaded on escorts with zero cargo space

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4305]
**Describe the bug**
If the player has an escort in their fleet with no cargo space, then mission cargo will be loaded onto that ship.

**To Reproduce**
1. Get a fleet with various ships, at least one having zero cargo space (e.g. by installing outfits expansions).
2. Accept a bunch of cargo jobs from the jobs board.
3. Launch, and go to your info page to observe the cargo in your ships.
4. Notice that the ship that should have no cargo since it has no space does have cargo.

**Expected behavior**
Ships with zero cargo space should not be able to load cargo.

<details><summary>Screenshots</summary>

A Corvette with 0 space but 30 cargo.
![image](https://user-images.githubusercontent.com/17688683/58523760-a7fc0d80-8193-11e9-84cc-ef35ad6f68f1.png)
The other two Corvettes in this fleet, which do have cargo space, one even having 35 free space.
![image](https://user-images.githubusercontent.com/17688683/58523797-c3ffaf00-8193-11e9-831c-54bf8d0e3da5.png)
![image](https://user-images.githubusercontent.com/17688683/58523844-f14c5d00-8193-11e9-8091-25f4ef4aa018.png)

</details>

**System:**
- OS: Windows 10 Home, Version 10.0.17134 Build 17134
 - Game Source: Steam
 - Version: v0.9.9

**Additional context**
Brought up by someone on Steam.
https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/#c1644290458823880898

**Comment by tehhowch** [comment]
A cursory glance at PlayerInfo#TakeOff says we're missing a call to set the size of the escort cargo holds based on their current `"cargo space"` attribute. Would need to dig more to determine where the call originally was and why/when it was removed.

**Comment by tehhowch** [comment]
Bug appeared in 8e0d8167403de689132a08406b9d7f3211beebf4

Specifically, `if(to.size)` should be `if(to.size >= 0)`
