### ISSUE TITLE
Auto-testers / game-logic regression testers

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4308]
**Is your feature request related to a problem? Please describe.**
I only found manual test-procedures for testing new Endless Sky features. Automatic testers for game-logic will probably help speed up feature development and help to avoid (regression) bugs.

**Related Issue Links**
Features/issues #861, #1624, #3639, #4101, #4305, #4307 and #4283 are examples that can benefit from automated testing.

**Describe the solution you'd like**
For basic test-data, I would like to re-use game-data loading and save-game loading functions
- Game-data loading can provide loading of a simple test-environment (for example a system with just 2 starts and 2 types of ships)
- Game-data loading can also provide "test-missions" with exactly the right content for a specific test.
- Save-game-data can provide a starting-state for tests (determines which ships a "test-player" has at start of the testing and which missions are active).

Besides this we would also need the ability to verify conditions (asserts) and we would need a way to move the test forward.

Moving the test forward is normally done by explicit test-steps and most test-systems use a level just below the GUI (so not a list of key-presses, but explicit calls to things like outfitter actions and commodity buy/sell actions). The idea there is that minor GUI changes should not affect game-logic-testcases.

**Describe alternatives you've considered**
An alternative for explicit test-steps that is possible within Endless Sky is to build some sort of "automatic mission resolver" and use mission data-files (with some small additions) to fully describe test-cases.

**Additional context**
Here is an example of how tests can look if we choose to use explicit test-steps in seperate test-files:

file: tests/auto-test/cargo_outfit_overload.txt

	test "Cargo: Simple commodoties transport"
		status "Active"
		game-data ./two_star_system
		starting-save ./two_star_two_barges
		test-sequence
			assert on-planet "First Star" "First Planet"
			assert in-cargo commodities "Electronics" 0
			commodities buy "Electronics" 100
			assert in-cargo commodities "Electronics" 100
			set-destination "Second Star" "Second Planet"
			depart
			assert on-planet "Second Star" "Second Planet"
			assert in-cargo commodoties "Electronics" 100
			commodities sell "Electronics" 100
			assert in-cargo commodoties "Electronics" 0

	test "Cargo: Outfit not fitting in single cargo-hold"
		status "Known Failure"
		bug-id "None yet"
		game-data ./two_star_system
		starting-save ./two_star_two_barges
		test-sequence
			assert on-planet "First Star" "First Planet"
			outfits buy-to-cargo "Large System Core" OK
			assert in-cargo outfits "Large System Core" 1
			set-destination "Second Star" "Second Planet"
			depart
			assert on-planet "Second Star" "Second Planet"
			assert in-cargo "Large System Core" 1

I might have some time to implement some of the testing-framework for those game-logic tests, but it is quite some work to implement this, so I would like to hear your opinion before spending time on this. Please let me know if you think this is useful or not. And let me know if you see better ways of testing that I didn't consider yet.

**Comment by tehhowch** [comment]
Adding unit and integration tests is something I too would like to do for the game, so feel free to embark on the process. No one has configured testing frameworks yet since as you state, they're a fair bit of work to get off the ground and as Endless Sky is only a hobby for all involved, it's hard to justify effort that doesn't promptly lead to more content and/or wanted features. 

I'm fine with needing to directly write and manipulate the game classes in tests rather than being able to use "natural language" as a test specification.

Feel free to share the frameworks you're thinking of working in; ideally we would pick one that can be used with Qt applications without much difference in flow (i.e. the ES map editor). License compatibility is required, however. All source needed for testing, including perhaps precompiled binaries, will be publicly released.

**Comment by petervdmeer** [comment]
Not much yet (it compiles and not much else), but I made a beginning of adding auto-testers (integration tests) in branch:
https://github.com/petervdmeer/endless-sky/tree/auto_tester

For unit-tests it is also okay for me to directly write and manipulate game classes, but the type of tests that I'm looking into are more like "integration tests".
What I noticed is that the mechanism for conditions in missions is quite powerful. I'm checking if I can integrate that mechanism also into "asserts" and into "teststeps/conditions to wait for". If that succeeds, then we have exactly the same natural language for the auto-test-code as we have for writing missions (and it saves quite some work, since we just re-use all the condition parsing that is already in place for missions conditions).

The test-code I worked on is very Endless-Sky specific. Test-conditions would be similar to mission conditions and flying the ship around is preferably done using one of the AI-personalities set to the flagship (i.e. if you want a test where the flagship fights off some other ships, then set the flagship personality during testing to "heroic").

I don't expect the test-framework it to be useful for the ES map editor, since it is very specific and embedded in the game itself.

License compatibility is no problem. Everything I have written so far actually only uses .cpp and .h and data-files from Endless Sky itself.

**Comment by tehhowch** [comment]
Just a warning that `ConditionSet` will be changing in v0.9.11. Feel free to review the PR responsible: https://github.com/endless-sky/endless-sky/pull/3128

**Comment by petervdmeer** [comment]
@tehhowch: Do you think a feature design/rfc will also help for progressing with this feature request?

**Comment by petervdmeer** [comment]
Here is a set of improvements that would make the test-framework more useful (I might make those improvements myself when I have time, but for now just adding them to this ticket so that those improvements are not forgotten):
- (High priority) Always require the `--config` parameter when any integration test is run. We don't want any active player data to be modified (or deleted) when some player just wants to run integration tests. This item was already briefly mentioned on [discord](https://discord.com/channels/251118043411775489/285540320823869441/922163174751481906). 
- (Medium priority) Ensure that the `saves` directory automatically gets created when an integration test gets started.
- (Medium priority) Split a `run_test.sh` script off from the `run_tests.sh` script, to allow any player to easily run a specific test.
- (Low priority) Embed the `preferences setting` from the run_tests.sh script as embedded data and load through the game (to remove the need for a separate script to handle the preferences setting).

**Comment by petervdmeer** [comment]
Another good improvement to add is the ability to load custom test-data. Hurleveur also noticed a need for adding such custom test-data while working on https://github.com/endless-sky/endless-sky/pull/6404.

There are a number of ways to provide such custom test-data:
- as plugin that gets installed before the test starts.
- as an "indepdendent universe" (a fully separate set of data-files only used for testing).
- by extending the "test-data" keyword to load the additional data in-game.

The most flexible and reliable option seems to be to provide completely separate sets of data-files each with the relevant tests embedded inside them. PR #6404 could then for example just define an unique universe with custom sell prices, without impacting the original game data-files.

**Comment by petervdmeer** [comment]
Closing this ticket; we by now have a large set of unit-tests and integration tests.
