### ISSUE TITLE
[suggestion] Cargo contributes to ship's weight

### ISSUE THREAD

**Issue by egilburg** [endless-sky/endless-sky#431]
Cargo should have weight (based on cargo type and quantity). More cargo = ship accelerates slower.

It would make it an option for cargo freighters to jettison cargo as a means of escaping pirates. Also freighters could be re-balanced for more powerful engines, so they move faster when empty but as fast (or slower) than they used to when full.

**Comment by thenerdfreak** [comment]
Already does? dunnit

**Comment by egilburg** [comment]
Really? Gotta double check it, I always thought it didn't :O

**Comment by thenerdfreak** [comment]
lemme post a screenie

**Comment by thenerdfreak** [comment]
![capture](https://cloud.githubusercontent.com/assets/15973422/11733026/73afbe78-9f6f-11e5-90c8-e15d48e4283c.PNG)

**Comment by egilburg** [comment]
Thanks! Closing this.
