### ISSUE TITLE
Escorts do not replenish crew when refueling

### ISSUE THREAD

**Issue by piannucci** [endless-sky/endless-sky#4320]
**Describe the bug**
When a freshly-captured escort with insufficient crew lands to refuel while following the pilot, it still has insufficient crew when it takes off.

**Expected behavior**
Escorts never take off from inhabited planets with less than full crew.

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.3 (18D109)
 - Game Source: Steam
 - Version: 0.9.9

**Comment by tehhowch** [comment]
Ref https://github.com/endless-sky/endless-sky/issues/367#issuecomment-162529426

**Comment by petervdmeer** [comment]
Closing issue; escorts only hire (new) crew when the player is landed and the escort is landed on the same planet. The linked issues give a good reason why escorts can refuel while the player is in flight, but I don't see any reason why we would add crew replenishment or repairing on top of refueling any time soon.
