### ISSUE TITLE
Un-plunderable outfits can be ejected by exploding ships

### ISSUE THREAD

**Issue by piannucci** [endless-sky/endless-sky#4321]
**Describe the bug**
Ships can eject unplunderable outfits upon destruction, like cargo expansions.

**Expected behavior**
Unplunderable outfits are not ejected.

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.3 (18D109)
 - Game Source: Steam
 - Version: 0.9.9

**Comment by Amazinite** [comment]
Are you sure those unplunderable outfits weren't in the ship's cargo? To my understanding, the only installed outfits that get ejected are ammo.

**Comment by piannucci** [comment]
I don't know; I haven't source-dived.  Still seems unexpected.  What does it mean to have a cargo expansion in your cargo bay?  Do they come as a kit?  They're illustrated as screwdrivers, which makes me expect that they are special services provided at the outfitter.  It might make sense to flag such outfits as ineligible to be loaded into cargo.  I suppose this is quite distinct from un-plunderability.

**Comment by tehhowch** [comment]
There isn't much in the way of rejection criteria on carried outfits yet. I have plans to eventually bias the selection based on cost and size. It should be easy to add rejection criteria for carried outfits, and can probably be done in such a way that mods can adjust it, too (e.g. a sequence of `ConditionSets`).

**Comment by tehhowch** [comment]
With 9a9e73d, you should no longer see Cargo Expansions, Outfit Expansions, * Bunk Rooms, or Control Centers in cargo. Things like Luxury Accomodations, Brigs, or Security Stations, which do not modify bunks or add either outfit space or cargo space, will still have a chance to be transported by NPCs in their cargo holds. It is expected and a solid `wontfix` that anything transported as cargo has a chance to be ejected as flotsam, even if it is unplunderable, as unpluderable applies only to installed outfits.
