### ISSUE TITLE
Spaceport news feedback

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4325]
This issue is just a collection of the feedback I've seen and gotten about spaceport news.

[Here](https://github.com/endless-sky/endless-sky/issues/3682#issuecomment-379503390) is the link to the comment where I mentioned having done a poll on this feature. The following is an image of a new set of polls that I did after the release of the update (posted 5/30/19 and stayed open for about 50 hours), with the first question being the same as the previous poll. At least from the Discord server among those that responded to the poll, the opinion seems to be rather split, with a sizable number of people not being sure on the images.
![image](https://user-images.githubusercontent.com/17688683/58753010-77172380-8486-11e9-99eb-28fd43b27b70.png)

The second question shows that while opinions on the images are mixed, the news system itself is popular. 

With the third question about alien images, although the poll showed positive, I got a sizable number of people giving written feedback about how they feel that the inclusion of alien images would ruin the immersion of imagining what the aliens look like for yourself. Some said that the inclusion of images of people in general was somewhat immersion breaking when every other interaction with someone else in the game, aside from the small number of images we get for Barmy Edward, is done through text alone.

I think the I worded the fourth question poorly. Not really sure what to make of it in hindsight.

The last question gets at the idea of #3742; if we don't have images of people, we could have images of inanimate objects. I received some feedback saying that it would probably be best to mix the two, though.

<hr/>

I opened a [Steam thread asking for feedback](https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/), including on the portraits. Here are some quotes from that thread.

<details><summary>Quotes from Steam</summary>

>The spaceport news system adds a lot of immersion, but I'm not sure how many messages there are and if they will get stale over time. [[source](https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/#c165329702604)]

>I personally feel mixed on the news tab addition, mostly the faces, but I could not articulate why well enough. I didn't mind the inclusion of a picture for the Kraz Engineer. [[source](https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/#c1653297026048427754)]

>j͏ust don't add pi͏ctures for the aliens. it͏ is better left to th͏e imagination. [[source](https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/#c1653297026050051225)]

>>Should the images be removed, but the news system be kept in place?
>
>Honestly this is one of the changes that I hate, but I didn't expect to hate.
Idk why but seeing realistic faces in a game about spaceships, where human interaction is done by text only really breaks my immersion. [[source](https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/?ctp=2#c1644290549102415642)]

</details>

After I had posted the polls from the image above, some discussion ensued related to them. Here are some excerpts from that discussion.

<details><summary>Quotes from Discord</summary>

![image](https://user-images.githubusercontent.com/17688683/58753157-52707b00-8489-11e9-9c62-49f6c816719d.png)

![image](https://user-images.githubusercontent.com/17688683/58753164-7338d080-8489-11e9-95c0-017a519a8014.png)

![image](https://user-images.githubusercontent.com/17688683/58753173-80ee5600-8489-11e9-8aa9-2dbec3fe0453.png)

![image](https://user-images.githubusercontent.com/17688683/58753186-a713f600-8489-11e9-8ddd-7c2580862122.png)

![image](https://user-images.githubusercontent.com/17688683/58753201-bbf08980-8489-11e9-871c-74225efb4a82.png)

![image](https://user-images.githubusercontent.com/17688683/58753212-cf9bf000-8489-11e9-8fcf-ead7d3b96aed.png)

![image](https://user-images.githubusercontent.com/17688683/58753222-e93d3780-8489-11e9-9d75-9fc390991b29.png)

![image](https://user-images.githubusercontent.com/17688683/58753228-ff4af800-8489-11e9-8c83-11b9e11bb08a.png)

![image](https://user-images.githubusercontent.com/17688683/58753233-0f62d780-848a-11e9-9624-e12cff9ea54b.png)

</details>

**Comment by hellminister** [comment]
Just a question about this system, can missions display news\info in there?

for exemples, hints of what type of technology is interesting to bring back, or that a certain pirate was seen in a certain system, etc.

**Comment by Amazinite** [comment]
We should probably take action on this feedback for v0.9.13. The general sentiment seemed to be to remove the portraits but keep the news.

**Comment by Zitchas** [comment]
Agreed. The pictures don't really add much, and frequently detract. The news / comments themselves, though... Those we need to expand.

**Comment by Amazinite** [comment]
Well with the ability to add/remove news from showing up, such interactions with news are possible now. 095f8da

We're still lacking a generalized event system though; all events right now are specific, giving us no way to easily create an event such as some random cluster of systems having some random commodity drop by some random amount for some random amount of time. I referenced [this idea](https://github.com/endless-sky/endless-sky/issues/1552#issuecomment-246232974) some time back now (before the spaceport news was even a thing in fact).

**Comment by Zitchas** [comment]
Seems prophetic. :)

We could probably manage it using invisible missions that trigger an event to lower/raise the price, with a timer, and then when it "fails" it removes the original event.

Cumbersome, but doable.

**Comment by tehhowch** [comment]
As far as the UI changes - dropping portraits is as easy as removing the portrait point in the interface definition text file. Probably though we are wanting to do more with the default UI than have a mostly empty box covering the landscape photo.

It would be possible to lay out the text to down the full box width if a news item didn't specify a portrait, but that could be jarring if cycling through a mix of items with and items without.

**Comment by Amazinite** [comment]
What about moving an optional portrait to the right side of the box? That way whether there is or is not a portrait, the text always starts at the same point? (Ref: #3742)

**Comment by tehhowch** [comment]
You can test that out without recompiling right now by modifying the interface. Not sure without looking how oversized images would be handled

**Comment by MCOfficer** [comment]
Unless *somebody* creates better portraits, the consequence is the same though.

**Comment by ravenshining** [comment]
Not necessarily, it could have been just a matter of weeding out the more offensive ones, like the masked man heading up the poll and the unedited squirrel.  I always hated those particular ones myself.

**Comment by Amazinite** [comment]
Well the squirrel and other “alien” images were never in use. In any case, one of the points I made as to why we should have removed the portraits is that having them created a requirement for them. As soon as I removed the portraits from the news, we got a number of new PRs creating news messages that simply weren’t possible before, either because they were for alien factions that we simply didn’t have images for or because they weren’t even messages that made sense to have portraits for, or at least not portraits of people. So clearly the removal of the portraits has moved us into a more favorable position in terms of content, and given that, you'll be hard pressed to convince me that we should readd portraits, not even bringing into question any other issues with them.

**Comment by ravenshining** [comment]
Well, you simultaneously removed the portraits *and* made it possible to have non-portrait news items, so of course there would have been more things made.  If there were a period where the portraits were still in place, but it was possible to have news items without them, then you might be able to make that claim.

Even still, I can appreciate the power of assumption that would have been in place in such a situation, it would have been awkward to introduce a non-portrait news item amidst all the the portrait ones.  And in that sense, I think it may have been a good idea for them to be *temporarily* absent - once we get more non-image items, we could bring images back so it's not more awkward for something to not have one, and better yet, bring in non-portrait images with them.

I don't get the same sense of sentiment, though that could be confirmation bias, on both our parts.
