### ISSUE TITLE
Navy prisoner mission does not allow returning prisoners to New Iceland (after battle for Rastaban)

### ISSUE THREAD

**Issue by jpretori** [endless-sky/endless-sky#4330]
**Describe the bug**
After battling the navy for Rastaban, trouncing them and then taking prisoners, I am given the option of returning the navy prisoners to New Iceland (in Kaus Borealis), or Clink (in Kornepherous).  Supposedly:
 - Returning the prisoners to New Iceland is a good faith gesture, and leaves the Free Worlds trusting the honor of the Navy leadership to free Katya in exchange for the Navy personnel.
 - Taking them to Clink is the more cynical move, keeping hold of the prisoners until Katya is actually made available.

I chose to return them to New Iceland.  When I landed on New Iceland, the mission was marked as completed, but the "return prisoners to Clink" mission remained available, and nothing else seemed to change.

Eventually I took my fleet to Clink, and suddenly the narrative continues.

So it looks like returning the prisoners to New Iceland does nothing.

**To Reproduce**
1. Defeat the navy at Rastaban
2. Observe the presence of two "prisoner returm" missions: one to Clink, the other to New Iceland.
3. Make use of the safe passage to return the prisoners to New Iceland
4. PROBLEM 1: No story narrative appears when landing on New Iceland
5. PROBLEM 2: Observe the "return prisoners to Clink" mission remains availble to accomplish
6. Return the fleet to Clink
7. PROBLEM 3: Observe that now suddenly the story narrative continues.

**Expected behavior**
When landing on New Iceland after winning the battle for Rastaban, I expected:
 - Both prisoner return missions to be removed from the mission map
 - The story narrative to continue in a way that makes it seem uniquely different to how it would have been had I returned the prisoners to Clink

**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Game Source: Ubuntu repositories
 - Version: 0.9.8

**Link to save file**
Sorry, I've continued playing quite a bit after this event.  Not sure the save file is much use.
[Johan Pretorius.txt](https://github.com/endless-sky/endless-sky/files/3245160/Johan.Pretorius.txt)

**Comment by Amazinite** [comment]
>Version: 0.9.8

Can you reproduce this in v0.9.9?

**Comment by jafdy** [comment]
There is no change in these missions offering data since they were added. It seems more likely that you narrowly missed the deadline, this is backed up by your save that shows the returned mission being offered but not done.

**Comment by jpretori** [comment]
> > Version: 0.9.8
> 
> Can you reproduce this in v0.9.9?

I haven't tried - but will, tonight.  May require some cheating to get to a sensible state just before the battle of Rastaban, so it's a valid test.  Any idea on how to do that?  I guess a start is just scrolling back through all the snapshots I've got to see if one of them will work.


> There is no change in these missions offering data since they were added. It seems more likely that you narrowly missed the deadline, this is backed up by your save that shows the returned mission being offered but not done.

I (vaguely) remember doing the prisoner delivery run using my Blackbirds.  I used to keep a few of those around, they're kitted out for quickly traveling long distances (scram drive + fuel pods gets me 6 jumps).  Unfortunately they're a bit fragile, and replacing Blackbirds on a continual rotation gets expensive.

I may be mis-remembering though... trying to reproduce the issue on both versions should tell us one way or the other.

**Comment by jpretori** [comment]
Actually, that makes me wonder.  How many prisoners?  Would it necesarily have complained if I took off with too little bunk space for the prisoners?  It might have just left them all in Rastaban, with me none the wiser... and therefore somewhat uselessly running off to New Iceland as fast as possible with no prisoners aboard.

**Comment by jafdy** [comment]
It is an escort mission, there are no extra people on board your ship.

**Comment by jpretori** [comment]
> It seems more likely that you narrowly missed the deadline

You were right.  I went back to an earlier save (I had one right after the battle), and this time made sure to do it all by Blackbird, so well within the timeframe - and this time it seems to work just fine.

It does meam I missed the notification about failing the mission, but I've seen some other issues dealing with the UX of mission failure messages so I'll just go ahead and close this one.

Thanks!

**Comment by jafdy** [comment]
There isn't any failure message on those two mission as one of them will fail anyway.
