### ISSUE TITLE
Mission trigger "daily"

### ISSUE THREAD

**Issue by RPBCACUEAIIBH** [endless-sky/endless-sky#4335]
**Is your feature request related to a problem? Please describe.**
(not problem related)

**Related Issue Links**
(not that I know of)

**Describe the solution you'd like**
Would be great to trigger a mission daily for daily fees, or daily deterioration, etc.
This would allow hiring escorts that are payed daily, parasite damage, radiation damage, etc. so that if you have the fuel to fly around, but no place to land, you can get in trouble...
(This can get even more interesting if and when switching from the jump-based calendar to a frame-based calendar.)

**Describe alternatives you've considered**
An alternative would be triggering on enter to any system, but that's not gonna get better with frame based calendar.

**Additional context**
(none... just an idea for improvement)

**Comment by jafdy** [comment]
A time based calendar is not going to happen, it has been discussed before. So it sounds like you have your solution.

**Comment by tehhowch** [comment]
Adjust/set a negative salary in an `apply` node. Make sure you account for multiple missions using said salary, and the mission being failed or aborted.

**Comment by RPBCACUEAIIBH** [comment]
Yeah I figured I can do that...
