### ISSUE TITLE
Clear an outfit from the ship.

### ISSUE THREAD

**Issue by RPBCACUEAIIBH** [endless-sky/endless-sky#4336]
**Is your feature request related to a problem? Please describe.**
(Not problem related)

**Related Issue Links**
Related to my previous feature request: #4335

**Describe the solution you'd like**
This feature would allow parasite removal mission, parasite/radiation damage repair, etc.
Permanent ship damage can be an outfit that adds negative hull points, without a category(just like submunitions)

**Describe alternatives you've considered**
An alternative would be getting the amount of that outfit, and removing that much with outfit "outfit name" -[amount]

**Additional context**
(none. Just an idea...)

**Comment by jafdy** [comment]
```    on (offer | complete | accept | decline | defer | fail | visit | stopover | enter [<system>])
            ...
        outfit <outfit> [<number>]```
Is this what you are looking for?

**Comment by RPBCACUEAIIBH** [comment]
> ```
>     on (offer | complete | accept | decline | defer | fail | visit | stopover | enter [<system>])
>             ...
>         outfit <outfit> [<number>]
> ```
> 
> Is this what you are looking for?
> (Edits for code formatting)

yes but currently there is no way I know to get the exact number of outfits onboard and feed that in with a negative value... therefore it may or may not remove all of it.

**Comment by jafdy** [comment]
Unless it is a purchasable/removable outfit you could just track the number of missions that have given that outfit.

**Comment by RPBCACUEAIIBH** [comment]
Ok. Thanks! Never mind then...
