### ISSUE TITLE
Mystery retrieval job description doesn't state destination planet

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4337]
**Describe the bug**
Once you accepted a "Mystery retrieval" job at a star system that has multiple planets, the job board doesn't tell you which planet on that system you need to go back to.

**Expected behavior**
The job board should say what planet the pilot needs to land at (the `<destination>`). If you have other jobs that require landing in that star system, and have taken a job with a tight deadline, it can be important to know in advance how many planets in that star system you'll need to land on, because every landing costs a day.

Also, it's probably not obvious to a novice player that once you get to the destination star system, pressing L will by default land at the correct planet.

**System (please complete the following information):**
 - Version: 0.9.9

**Additional context**
https://github.com/endless-sky/endless-sky/blob/948b949deab70a05a1029e1a2e4be99c32fd8e44/data/deep%20jobs.txt#L161-L164

**Comment by Tadrix** [comment]
Technically, every *take-off* costs a day, not landing. While you're at the job board, it doesn't matter, tbh, it's understood that you should return to the planet you are on currently. The problem arises when you forget where have you got that job. Which is a question of whether the job's author intended it to be this way and whether it was a good idea.

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/9e848f29a91083bdbe565944aa019a32bedcf099 by using the same language as the FW Scout Run jobs, which also has a destination that is its source.
