### ISSUE TITLE
ship/outfit license bug

### ISSUE THREAD

**Issue by RPBCACUEAIIBH** [endless-sky/endless-sky#4343]
**Describe the bug**
1. New License I made can be sold while other licenses can't. I simply copied an existing license outfit re-named it, and changed the description...
2. If I sell it and buy it back, the sell button gets greyed out and I can't sell it again. (as it should work I guess.)

**To Reproduce**
1. Make a new license in a plugin
2. Make a mission to get that license
3. Get the license accepting that mission (take off and landing doesn't change the behavior)
4. Go to the outfitter and try to sell it. (it can be sold for me, and that's the problem...)
5. Buy it back, and try to sell it again (I can buy it back, but I can't sell it again)
(it does the same thing again and again should be easy to re-create...)

**Expected behavior**
I shouldn't be able to sell it at all, since the other licenses can not be sold...

**Screenshots**
https://drive.google.com/open?id=1mKqUHfsnStBSTvTjiqMBAVTugnFFmrSm

**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Game Source: ppa:mzahniser/endless-sky
 - Version: 0.9.9

**Additional context**
Not sure if it makes any difference in licensing(I think it shouldn't), but anyway it happened on a new planet in a new system in the Origin galaxy (using the world forge plugin to work on mine)

**Comment by jafdy** [comment]
Licenses are added by events, the pilots licenses is a special case.

**Comment by RPBCACUEAIIBH** [comment]
Missions seem to set not events them like tis: set "license: Wanderer"
but that doesn't work for the license I've created, adding it as an outfit works, but then you can sell it...

**Comment by RPBCACUEAIIBH** [comment]
Never mind... found the problem...
I've tried to set it like so: set "license: Mark of K.B. License" (Did not add the license)
I've also tried: outfit "Mark of K.B. License" 1 (Added the outfit but can be sold)
now I tried this: set "license: Mark of K.B." (Works)
