### ISSUE TITLE
Mission triggered autosaves

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#4344]
I have noticed than many newer players have find themselves stuck on missions and have run around doing stuff so can't get back to before said mission (sometimes losing part of a fleet they need).

A triggerable autosave that either doesn't get removed or takes a lot longer to remove than the standard autosaves. 

The obvious keyword would be `autosave`, an extension would be to allow multiple "lines" of saves that can operate separately by appending a name to the keyword.

**Comment by RPBCACUEAIIBH** [comment]
Doesn't seem like a good idea, cause if missions can create new save files, and you play for a while, you can easily stack up lots of save files... That also uses up more space...(few KB is not much granted, but if you have hundreds of it, it can get large...) Just save it manually before you do something you would regret...

**Comment by Zireael07** [comment]
Most modern games have an autosave function, and with modern disk sizes, space isn't an issue (and those savefiles are often MBs big, not a few KBs)

**Comment by RPBCACUEAIIBH** [comment]
> Most modern games have an autosave function, and with modern disk sizes, space isn't an issue (and those savefiles are often MBs big, not a few KBs)

Well yes. but not every mission seems to create a separate autosave file... that would be a bad design when you may have hundreds of missions...
I'd suggest autosaving only at milestones not with every mission, that may solve @jafdy 's problem.

**Comment by RPBCACUEAIIBH** [comment]
...or adding an save icon to the conversation and dialog screens so that you don't have to exit to main menu to save the game.

**Comment by Fzzr** [comment]
Are you proposing something different from this? https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20intro.txt#L1252-L1257

I believe the current behavior is only to keep the most recent autosave.

**Comment by RPBCACUEAIIBH** [comment]
Well the most recent is not always the one you want to keep. For example you may wanna go back to an earlier save then the autosave, if the mission you're about to accept also saves after you accept it... or if you do another story in the mean time, etc. So yes would be good to have a save button that you can press before you press accept, and it should be another save file, not to be overwritten by the autosave...

**Comment by Fzzr** [comment]
Sounds like a `checkpoint` is what's wanted, with the intention of only being used at really big points before a string of missions (like right after choosing sides, right before the lead-up to the checkmate/reconciliation switch, right before scouting/capturing Pug space, etc.)

**Comment by RPBCACUEAIIBH** [comment]
not really... an in game quick save option so that you don't have to leave the game to save it. a button that you can click on, or a key to save the game any time without going to the main menu, and specifying a name.

**Comment by jafdy** [comment]
The intention is only to have it happen for some missions anyway, if it happened for every job then it would be a bit silly. I was also thinking of new players who tend not to manually save. My intention is that it would be a second set of three autosaves that would be replaced as more autosaving missions are triggered. 
Although the functionality is mostly there so . . . close (really need to get the documentation sorted).
