### ISSUE TITLE
Event not giving error when planet's name is wrong...

### ISSUE THREAD

**Issue by RPBCACUEAIIBH** [endless-sky/endless-sky#4345]
**Describe the bug**
I wrote a planet's name wrong in an event and it didn't gave me an error, and I pulled my hair out for hours trying to find out why the event didn't add my new outfits...

**Expected behavior**
A mission would give me an error, an event should also do the same...

**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Game Source: ppa:mzahniser/endless-sky
 - Version: 0.9.9

**Comment by tehhowch** [comment]
You can create planets in an event. You cannot create planets in a mission. Thus it is an error to reference a planet that does not exist from a mission, but it is not an error to do so from an event.

**Comment by RPBCACUEAIIBH** [comment]
I see... Thanks! Never mind then I'll have to pay extra attention then...
