### ISSUE TITLE
Developing a New Ship Variant

### ISSUE THREAD

**Issue by Fleurghber** [endless-sky/endless-sky#4348]
I'm attempting to develop a new variant from an empty Kestrel, but I can't work out how to eliminate the default outfits.  Is there a standard procedure, and if so, has it already been covered?

**Comment by Amazinite** [comment]
Issues are for reporting bugs or requesting features, not asking how to do something in/with the game.

Please refer to the wiki if you have questions about modding the game. https://github.com/endless-sky/endless-sky/wiki/CreatingShips#variants

**Comment by Fleurghber** [comment]
I did, but I couldn’t find the relevant paragraph on the page.  It showed how to add outfits, but not how to remove those already there.

**Comment by Amazinite** [comment]
Outfits listed under variants aren't added to the base ship's outfits, it's a whole new list of outfits that that variant has.
