### ISSUE TITLE
Request: Easier way to select disabled escorts

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#435]
I have a fleet with well over a hundred escorts and there's no easy way to select a given escort for boarding if I'm not near enough to click on it (and how can I even tell where it is without selecting it first?).  The B key only does it in the exceedingly rare case that there aren't any disabled enemies to board.  There are a few alternative solutions I can imagine, in order of what I think as a player would be most intuitive and useful:

1) Select a ship in the player info window to target it
2) When cycling through escorts, have disabled escorts go first, followed by out-of-fuel second, then any other escorts third (since there's little reason to cycle through this list looking at healthy ships).
3) B could be for boarding enemies and shift+B could board friendlies
4) A hotkey for selecting disabled and out-of-fuel escorts

**Comment by Pointedstick** [comment]
How about making the icons in the bottom left clickable?

**Comment by johndh** [comment]
Those icons currently show a very small fraction of my fleet.  I don't know if it varies by screen resolution or what, but mine only fits eight icons but I have way more than eight types of ship, so this would not really address the problem I'm having unless disabled ships took priority in the icons.

**Comment by frameworld** [comment]
If it only shows 8 ships, your huge fleet isn't supposed to be :p 

Cycling through more than 20 ships is already annoying. A target list (just like missions, but sorted) would be a good choice to add.
"X3-Reunion" sorts it by enemies first, then yours, then neutral for example.

But it feels cheaty to travel with such a huge number of ships that they don'T fit into the shipyard selection without scrolling.

**Comment by endless-sky** [comment]
I've added option #3 (Shift + B) in commit 7029878. Also note that you can double-click a ship to board it, but I assume that by "select a ship" you meant the escort icon, not the ship itself.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
