### ISSUE TITLE
Feature Request: Hire All/Fire All Crew Buttons

### ISSUE THREAD

**Issue by sbweber** [endless-sky/endless-sky#4350]
After buying a Hai Centipede for use as an assault boarding platform, I had to click the Hire button in the Hire Crew menu 94 times in a row to fill all bunks with additional crew. I find that in practice, I want my ship to either have full crew for boarding, or minimum crew for cost savings.

I suggest adding additional buttons in the Hire Crew menu to Hire All and Fire All possible crew members. It would also be convenient to have a popup in that menu asking if you'd like to refill crew members like the popup in the Outfitter asking if you want to refill ammo, but that may be more difficult (crew members probably aren't considered to be ammo, even though extra crew beyond the minimum are just ammo for boarding in practice).

**Comment by Amazinite** [comment]
You can press ctrl, alt, shift, or any combination of those buttons to purchase/sell/hire/fire multiple outfits/ships/crew at once.

**Comment by sbweber** [comment]
Thank you for the quick response. I failed to find this information in-game. I see there's an automatic crew re-hire in the main menu in Preferences -> Settings that I previously missed as well. Can this information be added to one of the Preferences menus? It doesn't need to be rebindable like the main controls. I'm suggesting there because it's where I found other controls, and since the modifier keys weren't listed, I had no indication this was an existing feature.

**Comment by jafdy** [comment]
It currently needs stumbling across but it is available on every screen where you might buy something. We should probably add it to one of the help popups you get when you first play.

**Comment by Amazinite** [comment]
It already is in the help pop ups when you enter the trading tab and outfitter.

>As in the trading panel, you can hold down Shift or Control to buy 5 or 20 of an outfit at once, or both keys to buy 100

**Comment by sbweber** [comment]
Oh, excellent! I missed the contents of of the help popups because I loaded an early game save from the last time I tried the game, back in 2017. I had to re-familiarize myself with some of the controls by checking the preferences menu. This is probably a rare enough use case to not worry about.
