### ISSUE TITLE
Non-heavy anti-missile turrets are pretty worthless

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#436]
They can barely kill single meteor missiles! I find that if I don't have the space for a heavy anti-missile turret, I don't even bother with the non-heavy version because it doesn't seem to actually do very much against most incoming projectiles.

**Comment by frameworld** [comment]
Turrets are more effective when you run away or are pushed away - they don't help very much if you don't.

I don't use the heavy versions either, some aliens have better tech which is actually worthwhile.

**Comment by Pointedstick** [comment]
The non-heavy ones, especially. Heavy anti-missile turrets do work decently well even if you're not running away from the missile at full speed. Even doing that, regular anti-missile turrets are spotty. And If I envision a ship that has a free turret slot that isn't better used for weapons that's fast enough to nearly outrun missiles to allow the turret to work, I don't come up with a lot of ships. The Headhunter, Arrow, or Bounder, maybe?

**Comment by frameworld** [comment]
The thing is, instead of installing a heavy anti-missile system, I could install a half Korath shield regenerator which helps regardless of the weapon which is used against me.

**Comment by Pointedstick** [comment]
Implicit here is the idea that you're using a small to medium sized human ship and have not yet gained the capability to capture outfits from powerful aliens.  :) If you're already at that level, there's no reason why you don't have ships capable at least of using heavy anti-missile turrets instead.

The point I'm trying to make is that there is currently almost no plausible use case where a non-heavy anti-missile turret makes any sense.

**Comment by endless-sky** [comment]
What I find the small anti-missile most useful for is if I have a ship that is not quite able to outrun missiles, the small anti-missile is enough to nibble away at a cloud of missiles before it gets close to damage me. They're also good for eliminating weak missiles (like javelins). But I agree that the short range plus lower power makes it much less attractive than heavy anti-missiles.

How much stronger (or longer range) do you think it would need to be, to be worthwhile? (Keeping in mind that the heavy anti-missile is *supposed* to be twice as good, because it is twice as big.)

**Comment by anonybosch** [comment]
Worthless? Dispersed throughout a fleet of small ships that don't sufficient weapon space for the heavy turrets, they provide an adequate anti-missle umbrella.

**Comment by Pointedstick** [comment]
@endless-sky I feel like the hard counter to the light turret should be the Sidewinder missile. Currently, even the basic Meteor seems like a reasonable counter for it; far too many get past a light turret. I think a light turret should take down a large fraction of incoming Meteors fired one or two at a time, but you should need a heavy turret to have a chance at taking down Sidewinders, Torpedoes, and larger barrages of Meteors. This would also differentiate Sidewinders from Meteors. Currently, I don't see a lot of advantages to the Sidewinder when you take into account the higher price, lower damage, and higher launcher size. If I want a missile weapon that gets past anti-missile defenses and I'm willing to pay more, I'll usually choose a torpedo, even on small ships (one torpedo launcher seems better than two Meteor launchers and is barely bigger). This gets back to Torpedoes needing to be better differentiated as anti-capital-ship weapons, but that's #251.

**Comment by guillochon** [comment]
I think all the anti-missile tech needs a little bit of a boost. Perhaps 50% longer range for everything.

**Comment by endless-sky** [comment]
Maybe I should boost the light anti-missile range up from 100 to 150 and leave its other attributes the same. I think the heavy anti-missile is already quite good enough.

**Comment by endless-sky** [comment]
I've increased the range in commit 88c7a8a. That should be enough to make the small anti-missile a bit more useful while still keeping it much weaker than the large variant.

**Comment by frameworld** [comment]
The radius defines only the burst, not the strength at defending against a constant stream.
Burst is the damage dealt in the time the missile-stream need to cross the distance while losing missiles.

Against faster missiles this has less effect. I am interested into how much it actually matters vs different salvo-sizes and missile-types.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
