### ISSUE TITLE
News: ships disappearing north of Syndicate space.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#4361]
**Describe the bug**
The 	"I keep hearing rumors about ships disappearing north of Syndicate space. It's probably a bunch of hot air, but either way, I'm staying away from there!" news display shouldn't show in Hai space.

**To Reproduce**
Click the Spaceport button any where in Hai space, eventually it will happen.

**Expected behavior**
That message never shows in Hai Space

**Screenshots**
![Hai Message](https://user-images.githubusercontent.com/16924073/59404882-f6053980-8d6d-11e9-81ee-10e8e4ee271d.png)

**System (please complete the following information):**
 - OS: Debian 10
 - Game Source: nightly as of 1 Jun 2019
 - Version: as of 1 Jun 2019

Easily fixed by removing the line from the news "human merchant anywhere" block. I've done it for my game.  Modified file attached.
[news.txt](https://github.com/endless-sky/endless-sky/files/3284283/news.txt)

**Comment by MCOfficer** [comment]
> The "I keep hearing rumors about ships disappearing north of Syndicate space. It's probably a bunch of hot air, but either way, I'm staying away from there!" news display shouldn't show in Hai space.

Someone has to ask it, why not?

**Comment by Zitchas** [comment]
While the news item is probably intending to be a hint leading players towards discovering the wormhole to Hai space, it is equally possible that it is referring to pirate attacks or superstition about a relatively uninhabited chunk of space.

**Comment by MCOfficer** [comment]
i was thinking it meant the pirate space around alcyone. the wormhole is technically north of syndicate space, but there's republic space in between.

**Comment by Zitchas** [comment]
That's a good interpretation too. Regardless of whether mine or yours is the intended interpretation, they both fit, and I'm not seeing anything that would make either of these wrong for merchants in Hai space.

From what I can tell, human merchants in Hai space tend to be adventuresome explorers/travelers, otherwise they would never have made it there, even if they do prefer the safety of Hai space once they find it. Wouldn't such people trade advice on particularly dangerous systems or where they avoid traveling?

**Comment by jafdy** [comment]
I read that line as being about the korath...

**Comment by Pointedstick** [comment]
FWIW when I wrote that line, it was definitely intended to be a hint regarding the wormhole to Hai space. However the alternative interpretations also seem valid so I'd be hesitant to remove it from the assortment of news available in Hai space. Better to keep the mystery alive IMO. :wink:
