### ISSUE TITLE
Increase DAILY_DEPRECIATION value to decrease speed of depreciation

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4368]
https://github.com/endless-sky/endless-sky/commit/1d0fe945249e518c1420af62cb9ee03e216d6815 increased the time it takes to reach 25% depreciation, but it didn't touch the daily depreciation value. This means that the time it takes to reach 50% depreciation went from 84 days to... 99. The impact of tripling the max age of outfits and ship hulls wasn't actually all that large. Suggested that we increase DAILY_DEPRECIATION from 0.99 to 0.997. This means that instead of taking 99 days to reach 50% depreciation, items take 264 days to reach this point, which is more of a tripling of the original 84 than tripling the max age was.

Depreciation model | Days to reach 90% | Days to reach 75% | Days to reach 50% | Days to reach 30% | Days to reach 25% from 30%
----|---|---|---|---|---
360 max age, .99 daily depreciation (old) | 12 | 32 | 84 | 194 | 166 (46.1% of the time)
1000 max, .99 daily (current) | 13 | 37 | 99 | 242 | 758 (75.8% of the time)
1000 max, .997 daily (the suggestion) | 36 | 100 | 264 | 599 | 401 (40.1% of the time)
1000 max, .998 daily (alternative) | 48 | 132 | 341 | 719 | 181 ( 18.1% of the time)
1000 max, .999 daily (alternative) | 71 | 193 | 468 | 845 | 155 (15.5% of the time)

.997 daily deprecation about triples the times from the old model.
.998 daily makes it take about a year to reach 50% depreciation.
.999 daily about doubles the time from the .997 suggestion, about sextuples (6x) it from the old model.

**Comment by Zitchas** [comment]
That seems like a solid improvement. 

I think one downside to the depreciation is that it punishes players that play the game slowly and explore, and rewards players that are buying new ships in quick succession.  This change will improve that considerably. 

As a side benefit, it will make missions like the gascraft mission where it says the player will be able to sell it back to the shipyard promptly and get almost all their money back much more truthful.

**Comment by Amazinite** [comment]
Captured ship depreciation is always set to FULL_DEPRECIATION, which under this suggestion is still 25%.

**Comment by Zitchas** [comment]
Sounds very  beneficial to me, then.

**Comment by Janaszar** [comment]
What if there was a period of "no questions asked returns"?  Such as, first week you see no depreciation, then it starts being counted?
With the current formula, you can change that second `1000` to a value lower than the first `1000`, and as long as the Depreciation % is bound to be <=1, you end up with a few days at 100% resell, then depreciation takes hold normally.
For instance, for the 0.998 setting (which I find to be the least objectionable in my opinion), changing the formula to `.25 + (1 - .25) * .998^X * (1000-X)/997` gives you about 7 days where you can return the ship/outfit for full price.

I feel that this helps new players test out ships/outfits without worrying about losing money/net worth.

**Comment by Amazinite** [comment]
That equation means that depreciation starts out above 100%, as the depreciate() method doesn't have a check to make sure the depreciation is between 100% and 25%. Have fun buying a bunch of stuff, departing and relanding, then selling it above its original value. I think a more sensible solution would be to have a GRACE_PERIOD constant. Then the depreciate method would look something like this.

```
double Depreciation::Depreciate(int age) const
{
	if(age <= GRACE_PERIOD)
		return 1.;
	if(age >= MAX_AGE + GRACE_PERIOD)
		return FULL_DEPRECIATION;
	
	double daily = pow(DAILY_DEPRECIATION, age - GRACE_PERIOD);
	double linear = static_cast<double>(MAX_AGE - (age - GRACE_PERIOD)) / MAX_AGE;
	return FULL_DEPRECIATION + (1. - FULL_DEPRECIATION) * daily * linear;
}
```

**Comment by Zitchas** [comment]
And then the Grace_Period is a variable that can be set to whatever is determined to be appropriate? Sounds good.
