### ISSUE TITLE
Why use <SDL2/SDL.h> instead of <SDL.h> with the right include path?

### ISSUE THREAD

**Issue by damccull** [endless-sky/endless-sky#4375]
Hello,

I was trying to build this on Windows using Visual Studio (I prefer it over the one you provide a project for) and using the SDL2 nuget packages that exist. The issue I'm running into is that these nuget packages place the header files directly into the "include" directory instead of a subdirectory (include/SDL2). So the references in your code to `#include <SDL2/SDL.h>` won't work easily because it's trying to use the wrong directory and, as far as I can tell at least, the / is a linux path separator while Windows wants a \. 

Is this how SDL recommends to make the references? I'm just curious because several places on the internet dealing with this issue in Windows say to use `#include <SDL.h>` and provide the include directory as a compiler option. I'm not necessarily asking you to change the way you do everything. I'm not a professional C++ dev like yourself, so I'm likely missing something. I'm just curious why this library seems to defy the standard for everything else I've seen in my short time in C++.

Thanks for the help.

**Comment by Amazinite** [comment]
Ref: https://github.com/endless-sky/endless-sky/pull/3785#issuecomment-397914844, https://github.com/endless-sky/endless-sky/pull/2896#issuecomment-336547064

Things compile just fine using CodeBlocks as suggested, so any change to make things work for Visual Studio would need to keep things working for CodeBlocks.

**Comment by jostephd** [comment]
There's also an SDL1 library that also provides an SDL.h file. If the code used `#include <SDL.h>`, it might find the SDL.h from SDL1 instead of the one from SDL2, if both SDL and SDL2 were in the include path.

Windows accepts `/` as a path separator in most places so you can just move your SDL header files to a directory called foo/bar/SDL2 and put foo/bar on your include path and everything should just work.

**Comment by damccull** [comment]
Alright. Thanks, @Amazinite and @jostephd. I'll look into what I'm doing wrong with that info.
