### ISSUE TITLE
Extremely high drag causes unusual speed behaviour 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#4379]
With a high enough drag, thrusting opposite to current motion causes extremely high speeds to occur. 

This is reproducible (and easily viewable) with a bastion with 5000 drag otherwise stock.

0.9.9 steam version, win 10 1803 

Thanks to Xyma.FLIF on discord for spotting this.

**Comment by Amazinite** [comment]
Post a save with various ships that exhibit this behavior?

**Comment by jafdy** [comment]
[  Testing.txt](https://github.com/endless-sky/endless-sky/files/3302881/Testing.txt)
This one will work (don't mind the extra tests ongoing in it).

**Comment by Zitchas** [comment]
That seems... Odd. Is it repeatable in 0.9.12?

**Comment by bobrobbow** [comment]
Yeah, I can repro with the attached save.

**Comment by Zitchas** [comment]
Just tested it on my 0.9.13 self-compiled build, and yeah, it causes extremely high speeds to occur. It isn't actually crashing, although it feels like it. At least on my system, it appears to be maxing out the GPU and reducing the frames per second to something in excess of a minute per frame, at which point Windows thinks it is not responding, although it is.... kind of.

**Comment by bobrobbow** [comment]
The question would be, is a high-drag craft, producing higher than intended thrust when thrusting opposite to current velocity vector? at lower drags the effect would perhaps be nowhere near this noticeable obviously, but still...
