### ISSUE TITLE
Typos (27 in 7 files)

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#438]
It's a single "typo" I keep encountering again and again... "Anyways/anyways". This is inconsistent with the tone of the various characters, all of whom present as highly educated and fluent in standard English. If it's meant to be used as slang, it's unsupported by any other iterations of slang or jargon such as various SF writers employ to imply lexical evolution.

"Anyways/anyways" change to "Anyway/anyway"

Free Worlds (FW) Checkmate: (3)
FW Intro (3)
FW Middle (7)
FW Side Plots (2)
FW Start (5)
Intro Missions (6)
Transport Missions (1)

**Comment by Wrzlprnft** [comment]
Created a pull request with your proposed changes.
(I've made a mistake, that's why there are so many references, but i corrected it)

**Comment by endless-sky** [comment]
Fixed in 8341605.

**Comment by endless-sky** [comment]
0.8.9 is now release, so I'm closing this.
