### ISSUE TITLE
Graphical Artifacts while other programs are open alongside Endless Sky

### ISSUE THREAD

**Issue by Buzzyboyish** [endless-sky/endless-sky#4381]
**Describe the bug**
Visual Artifacts with other programs open alongside endless sky. 

**To Reproduce**
1. Open Endless Sky and another program that is using up a significant amount of RAM.
2. Open save and jump twice to any system after undocking.
3. Wait 20 to 30 Seconds after flying around.
3a. Steps 2 and 3 are specifics of 'just play the game'
4. Open Starmap
5. See Hyperlane connections flicker and white block/lines appear. General Graphical Artifacts.

**Expected behavior**
No visual artifacts with another program open.

**Screenshots**
https://www.youtube.com/watch?v=f_Nky3xsn3Q

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
Windows 10 Pro 1809 build 17763.557
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
Github
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build: `http://mcofficer.me:8080/job/endless-sky-win64/<build number>/`)
Game Version 0.9.9

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]
Direct Upload
[Bug Report.txt](https://github.com/endless-sky/endless-sky/files/3302476/Bug.Report.txt)

**Additional context**
I do have the NVidia overlay on.
Tested other games to see if it was a system problem but they all work without issue in this regard.
Does not occur if endless sky and the overlay are the only programs open.

**Comment by MCOfficer** [comment]
can't reproduce this here. this sounds a lot like some video driver issue, does it occur with the overlay off? are your graphics drivers uptodate?

**Comment by Buzzyboyish** [comment]
Drivers are the latest (430.86). And after testing with overlay off it still occurs. Another note is that it doesn't seem to happen if the map is moved around, but only when it is stationary.

**Comment by Buzzyboyish** [comment]
I updated to Win 10 Pro 1903, which didn't fix it. After that I changed some NVidia 3d setting and finally changed application-specific settings for endless sky. I only changed texture filtering to high and the default quality setting to prefer quality, and that fixed whatever the issue was.
