### ISSUE TITLE
It's not clear when when space is being reserved for passengers/cargto picked up later

### ISSUE THREAD

**Issue by kaylara** [endless-sky/endless-sky#4385]
When I accept the Unfettered Hai Tribute missions from the Unfettered systems (Wah Yoot, Ehma Ti, Hi Yahr), the cargo space required for the missions is automatically deducted from my available cargo space. However, the missions says I need to go to X planet to pick up the tribute. No additional cargo space is used when I pick up the tribute.
It would make more sense to have these missions only take up cargo space when I pick up the tribute from the normal Hai.

**Comment by Amazinite** [comment]
The cargo space is used upon accepting the job because the space is being reserved for when you actually pick it up

**Comment by Pointedstick** [comment]
Seems like a legit UI issue. I've seen several people confused when space is reserved for cargo or passengers picked up later. After explaining this, they understand perfectly, but the game never provides that explanation; it had to come from a person. Seems like the game could be clearer about this.

**Comment by Amazinite** [comment]
What exactly could we do, though? Do we need to tack on “Cargo space will be reserved once you accept this job.” to every such job, most likely causing the description to overflow from the box and requiring us to change up the rest of the description?
This seems like a non-issue to me.

**Comment by kaylara** [comment]
Maybe we could _NOT_ reserve the space, and capacity is checked when you arrive at the pick up location. If this isn't a major modification, it might make more sense. I can tell 20 people I'm going to pick them up at the mall, and it's only when I arrive with my ForTwo that 19 of them become annoyed.

**Comment by jafdy** [comment]
That is a fairly major modification, the current engine doesn't allow that.
