### ISSUE TITLE
Remnant miss spaceport news or portraits?

### ISSUE THREAD

**Issue by tmoftdead** [endless-sky/endless-sky#4395]
**Is your feature request related to a problem? Please describe.**
Remnant have no spaceport news system in their planets,They are supposed to be a human

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those (I couldn't find any )
**Describe the solution you'd like**
A solution would be adding them spaceport news. it is described how they look like at least. We could use different portraits there. (Maybe even a signs?)
**Describe alternatives you've considered**
Add a text that says: "no one seems to speak with you." to humor the player. 

**Additional context**
It is simple, just that the deep have portraits even after narly 2 millenia of isolation and still have photos but the remnant departed more recently and don't

**Comment by Amazinite** [comment]
Ref: https://github.com/endless-sky/endless-sky/issues/3389, https://github.com/endless-sky/endless-sky/pull/3683#issuecomment-399760704, #4325

Spaceport news, and especially the portraits, is an experimental change that isn't fully implemented. See how not all obtainable ships even have thumbnails in v0.9.9 (#4377). The portraits are likely to be removed anyways.

**Comment by tmoftdead** [comment]
Understood. I just hope to see their portraits if not removed. Ü

**Comment by Zitchas** [comment]
As Amazinite said, the news system isn't fully implemented, and the portraits themselves don't seem to be terribly popular anyway. 

That being said, there will probably be news added for the Remnant planets at some point.

Just a note regarding lore: While the Deep may have been isolated for many centuries, at the present day in-game, the Deep has been reasonably well integrated back into normal human society. They still have their own culture and local government, but they are part of the regular trade & transportation network and are represented in the Republic.

**Comment by Amazinite** [comment]
Spaceport portraits have been removed as of v0.9.13 so this issue is no longer valid.
