### ISSUE TITLE
Ships that create wormholes or carry other ships through hyperspace

### ISSUE THREAD

**Issue by IFailAtGaming** [endless-sky/endless-sky#440]
Would such a mechanic be possible, note possible, not planned, be it something like in oolite, where a ship  travels using a wormhole and said wormhole lingers and can be used by other ships, or some sort of carrier to carry large ships, would it be possible to add in?

**Comment by endless-sky** [comment]
Meaning, the player hitching a ride, or your ship hitching a ride? There's already support for carriers, but I'm not clear on what you're actually asking here.

**Comment by IFailAtGaming** [comment]
Player and AI, i know about the fighter carriers, but i'm talking about large ships (up to a point, i mean something that can carry a bactrian would be insane). 
Also my apologies for the slow response i wasn't paying attention

**Comment by IFailAtGaming** [comment]
I'd love a reply from @endless-sky , as i don't even have any knowledge of which engine this game uses, so i certainly don't know it's capabilities, i'm even willing to throw up a quick crappier than average drawing to explain

**Comment by endless-sky** [comment]
I'm really not sure what this would add to the game. Anything larger than a fighter has a hyperdrive of some sort anyway.

**Comment by IFailAtGaming** [comment]
It's just an idea mostly. It mostly came up because I'm making a mod for personal use based on a race I particularly like, and canonically they use carriers. So I wondered if the game could do large ship carriers/temporary "landables" (which was how I would see the wormholes working). For vanila its true that it wouldn't be very useful, but that's why I asked if it was possible, and not whether it would be added.

**Comment by bobafetthotmail** [comment]
I looked at the source (/source/ships.h). The game defines what can land on a carrier by calling a function that checks for ship type, so you can either clone that and change it to have your own "jump carrier" function that will be valid only for your "jump carriers" (so carriers will still work as in vanilla).

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
