### ISSUE TITLE
Paradise Fortune 4 choice reversal.

### ISSUE THREAD

**Issue by ChamEV** [endless-sky/endless-sky#4405]
In Paradise Fortune 4, the options are reversed.  When you agree with her cause, alondo shouldn't be contacting the navy, and when you say "I'll hand her over" alondo should be contacting the navy for you.

```
		`	"Alright, I'll hand her over."`
			goto end
		`	"Sorry, Alondo, but I agree with her cause."`
	
	apply
		set "navy contacted"
	`	"I understand. Please, just don't drag the Free Worlds into this."`
```
---
```
	branch navy
		has "navy contacted"
	`	You fold the note and slip it into the backpack so that you can show it to the Navy to explain why Diana is not with you. You contact the Navy's crime report hotline and tell them that you have the stolen credits. A few minutes later, they respond telling you that a fleet is waiting on <destination> to retrieve the credits.`
		accept
	
	label navy
	apply
		clear "navy contacted"
	`	You fold the note and slip it into the backpack so that you can show it to the Navy to explain why Diana is not with you. Alondo sends you a message, telling you that the Navy says they are waiting on <destination> for the credits.`
		accept
```

may be related: https://github.com/endless-sky/endless-sky/issues/4282

**Comment by jafdy** [comment]
The simplest way to fix this is probably make the two responses lead to a section with either Alondo's line or the apply then onto the current end label.

**Comment by Amazinite** [comment]
I think that the original intention was that Alondo calls the Navy if you say you aren't going to hand her over, but you call them if you say you will hand her over. I've swapped the situations though and made explicit when Alondo is contacting the Republic. https://github.com/endless-sky/endless-sky/commit/dd26f1db99c79f359ba1009778bec591bc8311e6
