### ISSUE TITLE
Shield and Hull Recharge multiplier proposal and RFC v0.9.11+

### ISSUE THREAD

**Issue by ChamEV** [endless-sky/endless-sky#4407]
## Shield and Hull Recharge multiplier ##
The primary purpose of **Shield recharge multiplier** and **Hull repair multiplier** is not to easily create overpowered regeneration, but to allow outfits to reduce the regeneration so that stacking multiple outfits will not work.

Consider a small shield regeneration outfit, 5 tons, 100 shield regeneration/sec.  Normally that'd be very overpowered.  But combine it with **Shield recharge multiplier** of -.3, that is recharging 70% of normal rate with 1, and 40% of normal rate with 2.  Now you have an outfit that can be put on a fighter that is not attractive in any number for larger ships.

Quantity | Shield multiplier | Shield Regen / second
---------| ---------| ------------
1 | 0.7 | 70
2 | 0.4 | 80
3 | 0.1 | 30

**Comment by Pointedstick** [comment]
Makes sense, but this might be rather difficult to communicate to the player in the UI.

**Comment by ChamEV** [comment]
I have a few ideas regarding that.

* First any time this is applied, the end result will instantly be apparent in on the `shields charge/max: x / y` line with x changing.
* Usage of "increased" and "decreased" as descriptors as these are stacked additively before being multiplied.  Borrowing from [path of exile's terminology](https://pathofexile.gamepedia.com/Stat#more_vs_increased)
* There is a general need for a complete stats page now that ships are coming equiped with built in ramscoops and cloaking among other things.  This would fit in there.

**Comment by Amazinite** [comment]
So would that mean that 4 generators with a -.3 multiplier would yield 0 shield regen? And how would this interact when mixed with shield generators that don't have a multiplier? Does this multiplier effect ALL shield generation on a ship?

**Comment by jafdy** [comment]
I should probably be a multiplicative penalty, so -.3 would become (-.3)^n

**Comment by Amazinite** [comment]
I think a better vanilla use of such an attribute, instead of making shield generators supposedly only attractive to smaller ships, would be to give smaller ships an intrinsic positive multiplier.

**Comment by jafdy** [comment]
So, I know you were worried about a can of worms, but if you want to make it work for every attribute, rather then give it a name you could use operator symbols. So for adding you use `<attribute> +<num>` or just `<attribute> <num>`, for multiply you use `<attribute> *<num>` (the same could then be used for `/` and `-` is there already in effect.
It just leaves the question of what order do you apply the operations.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/9ea5c2f58b755edf81475032998bf7db788394a2
