### ISSUE TITLE
[Spoilers] Remnant mission made artificially difficult by low fuel on gas craft

### ISSUE THREAD

**Issue by jpretori** [endless-sky/endless-sky#4409]
**Is your feature request related to a problem? Please describe.**
The "land on void sprite planets"  from Remnant space is needlessly frustrating.

A combination of factors cause it. The upshot of this combination of factors, is that it takes a very long time to finish the mission, and it's quite risky - I got ambushed by Korath raiders and blown apart.  The factors are:
 - Low fuel reserves on gas craft
 - Must have jumpdrive on gas craft, as there's no hyperspace path to the void sprite system - so it eats 200 fuel per jump, limiting the craft's range to 4 jumps
 - It has a ramscoop, but it is extremely slow, taking a really long time to fill the tanks back up to 200 fuel.

I could drag one of my fleet ships with me to refuel along the way, but it is difficult (maybe impossible?) to keep the Archon from destroying the companion ship, thus making the return journey equally hazardous and frustrating.

I guess I could take my whole fleet with, and try to destroy the archon, but I have little confidence of that succeeding - that thing is toting some serious guns, so I assume its shielding is equally impressive.  And anyway, I have no appetite for annoying the Drak any more than I appear to already be doing, by disturbing the void sprites.

**Related Issue Links**
None that I'm aware of

**Describe the solution you'd like**
I'd like a way (even a sneaky one) to have this mission be less frustrating.  Here's one idea: This craft is made to land on gas giants, right?  Well, maybe when I try to land on gas giants along the way to the void sprites, instead of just saying "can't land on gas giants", it could scoop up hyperspace fuel from the outer atmosphere, thus rapidly refiling the hyperspace fuel tanks to full.  Some players won't think of this, so maybe the mission description could hint at the possibility (or just state it outright).  Maybe even just flying around close to gas giants can have the same effect.
This could maybe be an outfit that I can install on other ships once I have a remnant license?  But it doesn't need to be, to be effective for making this mission less frustrating.

**Describe alternatives you've considered**
 - Change hyperspace pathing so I can get there and back in the gascraft without needing a jump drive. (Don't like this because it seems like such a dull solution, and besides it requires losing the "scattered clumps of systems" feel of the ember waste, which would be a shame)
 - Add a wormhole that cuts down the number of jumps so the gascraft can manage it (don't like this because it seems too close to cheating)
 - Add fuel reserves to the gascraft.  (you'd have to make it much bigger for this to have a serious effect on the problem.  I don't think the ship will feel realistic anymore)
 - Give the gascraft a catalytic ramscoop (ship would have to be bigger, again I'm not sure it will still feel realistic)
 - Make it so that the gascraft can hitch a ride on one of my bigger ships.  (maybe, but this is inconsistent with how any of the other ships work)
 - Gascraft can hitch a ride on a Remnant escort ship, which then waits for me in the adjacent system (much better than the last one, but a very expensive solution for the person giving the mission.  The main problem with this, is it requires the player to lose autonomy during this journey, which doesn't happen anywhere else during the game as far as I can tell, so this would break one of the core consistent things about the game, which I think would be a bad idea)

**Additional context**
n/a

**Comment by beccabunny** [comment]
You can already arrive there with in a hyperderive; wormholes connect various systems in a way that you could even get from a remnant planet to human space with a hyperdrive. It is very hard with a jump drive since you are not supposed to do it with a jump drive, that's why the gascraft has a Keystone installed.

**Comment by MCOfficer** [comment]
I did this mission a couple of times, and the easiest way seems to be to make a stopover on human space so you can reload from there. I also did it from remnant space without too much frustration - at least not over the fuel, but rather over my inability to dodge.

Considering that the ember waste fills your fuel pods so damn fast that you can almost scoop on the way, i don't see the fuel being a big blocker.

**Comment by Zitchas** [comment]
1) There is a path for the player to get from the Remnant systems to Nenia and back using a combination of regular hyperjumps and wormholes.

2) While in the Ember Waste Ramscoops are quite a bit more effective. 

3) The Ember Waste is intended to be a dangerous and isolated, and the Korath are part of that danger. Making the trip on a jump drive is going to feel more adventuresome, but also more dangerous.

That being said, being able to hitch a ride on a larger ship in a bay of some kind would be neat. Possibly a bit complicated to program, though.

As far as the gas giants go, I'm currently working on making more of the gas giants visitable. I don't know about refueling, but even being able to land (and thus save) would make things easier.

**Comment by Tadrix** [comment]
> I could drag one of my fleet ships with me to refuel along the way, but it is difficult (maybe impossible?) to keep the Archon from destroying the companion ship, thus making the return journey equally hazardous and frustrating.

On this: You, of course, are aware, that the **H**old position fleet command exists? Just don't drag this companion into Nenia and it'll be alright. Let them wait for you in the adjacent system.

**Comment by jpretori** [comment]
> > I could drag one of my fleet ships with me to refuel along the way, but it is difficult (maybe impossible?) to keep the Archon from destroying the companion ship, thus making the return journey equally hazardous and frustrating.
> 
> On this: You, of course, are aware, that the **H**old position fleet command exists? Just don't drag this companion into Nenia and it'll be alright. Let them wait for you in the adjacent system.

Ah!! So _that_ is what "H"old is for.  I didn't realise that, no... but this is definitely worth a try.  Thanks!

Several people mentioned that wormholes connect up in a way that makes the trip do-able with a normal hyperdrive and a keystone.  I guess I haven't discovered those wormholes yet, I guess they only show up on the map once you've flown through them once... I did find myself a little puzzled by what appears to be a "one-way" wormhole if I look at my galaxy map, I guess I only flew through that one in one direction, then continued exploring in a way that ended up with me returning to human space via another route.  I'll go back and take another look.

As far as player frustration goes though, how much of a corner case have I played myself into - if it seems reasonable to conclude that more people are running into this same thing, maybe it's worth building some kind of "safety" mechanism in that warns the player that they might be missing a trick if they try to equip the gascraft with a jumpdrive.

**Comment by Amazinite** [comment]
Well the easiest way to reach Remnant space is by using the wormholes, so it's somewhat assumed that a player doing the Remnant missions will know about them.

**Comment by Pointedstick** [comment]
I don't think any changes are needed here. The wormholes allow a clear path when you have Quantum Keystones installed, and a ramscoop should recharge fuel while in the Ember Wastes pretty quickly, especially when only consuming 100 units of fuel per jump.

**Comment by jafdy** [comment]
A better solution might be to add a mission before this one that encourages the player to use the wormhole.

**Comment by MCOfficer** [comment]
> 
> 
> A better solution might be to add a mission before this one that encourages the player to use the wormhole.

If i recall correctly, some deep missions reference this wormhole, although they never explicitly tell you to go through.

**Comment by jpretori** [comment]
I don't remember seeing any references to wormholes of any kind - in fact it was a (very pleasant!) huge surprise when I discovered a weird looking thing in Ultima Thule that would let me "land"... and ended up spitting me out in Hai space.  So I probably just missed the references.

I would be strongly in favour of a mission that happens before this one, that leads the player to discover the wormholes that make the Nenia mission reasonable.

**Comment by Amazinite** [comment]
>If i recall correctly, some deep missions reference this wormhole, although they never explicitly tell you to go through.

The Deep: Remnant missions actually do make it known to the player that the Quantum Keystones allow access through the wormholes, and the player is gifted one and told to explore the Ember Waste. While the player isn't required to use the wormholes, as they technically could just hike it across the galaxy and enter the Waste with a JD, it does at least let the player know about the wormholes and how to use them.

**Comment by jafdy** [comment]
I was thinking of a remnant mission that would ask the player to go and look at the wormhole and is required to get this mission. Perhaps the player could be asked to "scan" the wormhole by going to both sides of it, the obvious suggestion is to use the wormhole to do that but it would introduce the wormhole to players who stumbled into the wastes using a jump drive.

**Comment by Zitchas** [comment]
Sure, I could do that. It'd be fairly straight forward sort of mission to add.
