### ISSUE TITLE
Pirates & Bounties, Revisited.

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#441]
It may seem that I'm obsessed with bounties but this thought just popped into my noggin while I'm proofreading map.txt. (I'll post when I've finished.)

Bounty hunting is a lucrative pastime, a public service, and loads of fun. The way the game is structured now, the player upon reaching a certain level of fearsomosity begins to see pirate hunting missions. The player accepts the mission(s). In due course the pirate expires either through the player's efforts, or without any effort at all. The player still gets the bounty. The player still gets the bounty.

This leads to the player taking the bounty, not caring how or where the mission is accomplished, and only having to land on the planet that issued the "contract" to collect the bounty. <i>Imo, the player isn't actually on a "mission" but has elected to become a contract killer, a hitman, a thug with a license. But that's part of the fun of the game, isn't it?</i>

So, what if taking the mission meant having to actually terminate the pirate? What if, instead of having to land and collect the bounty; on termination of the pirate, the planet deposited the bounty into the player's account at The Bank? The Bank, after all, has complete power throughout the galaxy to deduct salaries, collect mortgage payments, death benefit payments, and myriad other functions.

This change in gameplay would put pirate hunting into an active mode instead of passively receiving bounties as they pile up from system to system through no effort of the player - in effect, free money. It would also introduce an element of chance. The player kills the pirate / gets the bounty. Other forces kill the pirate / the player misses out. Better luck next time.

(This just occurred to me as I type.)  The present system of bright-blue/dull-blue flags for pirate missions could be simplified with a single red flag indicating where the pirate mission originates. On completion of the mission, the red flag disappears the way freight/passenger missions do now when they're completed. Incidentally, there shouldn't be any confusion on the player's part because pirate/bounty missions occur only after the player has achieved notoriety, and the moment the first pirate mission is accepted the red flag appears at the system that issued the mission.

**Comment by endless-sky** [comment]
Right now, because your bounty hunting targets are ordinary pirates, they can get killed by non-player ships. I suppose I could give them a different government that none of the other governments attack, to keep that from happening.

**Comment by anonybosch** [comment]
But if you did that pirates would run amok and the only force in the game keeping them in check would be the player. (I think) that would get totally out of control and overwhelm the other, more pressing, aspects of the game and the campaign.

My feeling is that the player should have to hunt and capture/plunder/kill the pirate to collect the bounty. Hunting could be a significant source of income, but like trading, you'd have to work for it. As the game progresses, the fleets get bigger. It gets more difficult to be a pirate simply because there are more ships about, all intent on reducing the pirate menace. 

The player can specifically elect to do his/her civic duty (for a price) and reap the reward. It's in all ships' interest to protect themselves and attack pirates on sight. The player happens to get there first, or makes the kill, then the player gets the reward. If not, the bounty is vacated but the player still has the incentive to continue accepting missions because there <b>are</b> rewards to be earned.

I might not be expressing my idea very well. It just seems unbalanced that the bounty dynamic is free money.

**Comment by Pointedstick** [comment]
Basically, the pirates should have some intelligence to them. There's little reason a mid-tier pirate ship would find itself in the middle of a system currently protected by a bunch of Republic warships, yet the random spawns lead to that kind of situation all the time and you get the credit despite doing no work. And for pirates you do get dead to rights all on your own, when you come gunning for them, they're totally suicidal and fight to the death even if you're obviously much more powerful. They should try to run away in that situation, and you really should have to hunt them!

**Comment by frameworld** [comment]
When a pirate is killed, spawn bounty-containers (invincible, de spawn when you leave the sector).

They take 0 cargo space. They are part of the enemy ship's hull and proof that you participated.
The fastest ship that leaves the sector with one of these gets the bounty.

**Comment by anonybosch** [comment]
Excellent ideas, <b>but</b>, more elaborate than I'd envisioned, though Pointedstick, you do bring up an inconsistency about pirate behavior. You fellows see my avatar? That's a Sloop of War. One of my ancestors plied the Caribbean plundering and selling the goodies in Barataria, Louisiana. Yes, him. He wasn't suicidal.

Getting back to the game... 
1.) The pirates are suicidal (though they should be plunderers, not kamikazes). Let's just say we stick with that for now.
2.) The player gets the bounty if and when the player makes the kill.
3.) Should the player so choose, he/she can become more actively engaged by having a unique signifier (red flag). This encourages the bounty-motivated player to take particular notice of pirate activity.
The bounties now become A.) a matter of chance, and/or B.) the result of purpose and skill.

@frameworld, the last thing I'd want to do is spawn more clutter. Currently when a pirate expires the notification is instantaneous. Let's leave it that way. Having the bounty directly-deposited would, incidentally, reduce the flag clutter and obviate the need to appear at system-X to collect.

**Comment by jafdy** [comment]
You will need to consider how you will count a "kill" or bounty hunting will simply be annoying as the AIs will repetitively steal your kills and prevent you collecting your bounty.

**Comment by anonybosch** [comment]
OK. Fair point. How's this? Once the player targets the pirate, others leave off attacking. Is that even feasible, Dev?

**Comment by endless-sky** [comment]
That would mean that if a starting player is running away from a pirate, they would have to avoid targeting it because as soon as they do, the Navy / Militia will no longer help them fight off the pirates. Probably not a good idea.

**Comment by anonybosch** [comment]
<i>You will need to consider how you will count a "kill" or bounty hunting will simply be annoying as the AIs will repetitively steal your kills and prevent you collecting your bounty.</i>

At the very least, target the pirate while in-system, and if the pirate then expires because of overwhelming crossfire, you get the bounty. The AI already adds kills made by the player to the player's stats to increase combat rating. The AI already acknowledges the kill by awarding the bounty.

<i>That would mean that if a starting player is running away from a pirate, they would have to avoid targeting it because as soon as they do, the Navy / Militia will no longer help them fight off the pirates. Probably not a good idea.</i>

Attack and retreat simultaneously? Is that even possible? The starting player doesn't encounter bounty missions. By the time bounties come into play the player perforce has a fleet. Interceptor-class pirates don't rate bounties. Light-warship class pirates get "bountied". (I haven't taken note if pirates fly heavy warships as well, but if they do, add them to what I propose below.)

So that simplifies who shoots at what. All interceptors are always open-season by all ships.

Bountied Pirate
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;target yes/no
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if yes then all others stop firing
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if no then all others continue firing
Pirate destroyed
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if targeted then bounty awarded
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if not targeted then no bounty. (moot point)
