### ISSUE TITLE
Headhunter generates error due to gun placement

### ISSUE THREAD

**Issue by anon119** [endless-sky/endless-sky#4413]
In 0.9.9, I occasionally see the following type of warning in errors.txt:
Headhunter "Cackles of Secor": outfit "Heavy Laser" equipped but not included in outfit list.
I only see these for the Headhunter, and I believe I have traced the cause of the error back to the fact that the Headhunter recently had 2 gun ports added.  Because the new gun ports were added before the two that are equipped with the heavy lasers in the default ship, I think that the variants are placing alternate guns into the two empty spots first and, because not all variants use all 4 gun ports, leaving the two heavy lasers hanging out as equipped.

I am pretty sure this can be solved by either moving the heavy lasers into the first 2 gun ports, or reordering the gun ports so that the empty ones are not first.  I have done a couple of tests of this and it seems to make the warnings go away.

**Comment by Tadrix** [comment]
Sounds like a game's bug to me. Such behaviour isn't documented, and certainly wasn't intended.

**Comment by tehhowch** [comment]
Please provide a save file and a list of all plugins

**Comment by anon119** [comment]
After a few hours of trying to isolate the cause of the warning, I have determined the following:
1. I can always trigger the warning in a brand-new stock game by simply adding a headhunter as a second ship to the save file, and changing the heavy lasers to something else.  But this is appropriate, and if I try the same thing with a Raven or some other ship, I also see the error.  So this is desirable behavior.
2. Spawning a Headhunter in a system alone does not cause the error.  In fact, spawning hundreds of them in a new game in Ruticulus seems not to.  Which explains why I have spent several hours trying to pin down the exact cause of the warning and cannot do it.
3. I suspect at this point, but have not been able to intentionally create a situation to verify, that the warning is inappropriately triggered when a non-player Headhunter (without heavy lasers) is disabled or otherwise present in a system in a way that means the player can interact with it (board/capture).  It may be that the Headhunter also has to be either friendly or hostile to the player, I am not sure.  Note that I have never boarded/captured a Headhunter during a period when I (after the fact) see the warning having been logged.  And on one or two occassions I have seen the warning appear as soon as I loaded a game, but if I then reload the same game the warning is not present.  So an alternative possibility is that it has something to do with a Headhunter variant being spawned right at the start of a game load?
4. I have seen the warning without any plugins or save gave mods, and no save game that I have can reproducibly it.  So I do not have a useful file to provide you for testing.

I apologize that this is probably not at all helpful for isolating the cause.  What I can say with certainty is that I never saw this in 0.9.8, and that I only ever see it as a random, rare warning with the Headhunter.  Hence my initial supposition that it is something to do with the gun arrangement on the Headhunter, which in 0.9.9 is unique among stock ships (default guns loaded into not the first available spots, and some variants do not use those default guns).

**Comment by anon119** [comment]
Update: by posting a watch file on errors.txt to get notified at the time of change, it appears that the error is logged upon loading a saved game while currently in a system that contains a computer-controlled headhunter variant that lacks heavy lasers.  I am not yet sure if it is any of the variants or only some, because naturally the notice happens at the same time all information about ships in the system is lost.  Knowing this, I will attempt to create saved game scenario that can reliably trigger the warning, but it may take me a few days to find time to do so.

**Comment by tehhowch** [comment]
Sounds like a mission NPC is perhaps not getting instantiatiated properly. You can copy that save and the one before to a different folder before your next landing.

**Comment by anon119** [comment]
I have yet to isolate a save file that can trigger the error reproducibly; even if I go back one save once I see the warning, I cannot make it happen again with any consistency (and I actually overwrote the latest pre-warning file I had been using in the process of cycling through saves).  I now suspect it has something to do with a headhunter appearing in the available mission data in the save game file.  However, it is not triggered by the actual presence of a headhunter in the save game file, but I think by whatever code causes the available missions to populate with ships, possibly linked to the timing of loading a game/generating those missions.  And the headhunter is a relatively rare ship, so it does not often populate in a random job.  I will keep trying to pin it down, and keep better track of the save game files when I next see it.

**Comment by anon119** [comment]
[hhtest.txt](https://github.com/endless-sky/endless-sky/files/3377188/hhtest.txt)
I got a reproducible trigger.  I do not think this is the only way to do it, but at least this gives a clear example.  To trigger:
1. Use the attached file as a new plugin.
2. Start a new pilot.
3. Decline the starting mission.
4. Quit.
5. Save the current save game file.
6. Start Endless Sky again.

At this point the test mission will automatically populate the current pilot save game, and you can compare the two save game files to see that the headhunter for the test mission has been added.  Errors.txt will also include the warning that I have reported.  What seems to have happened in this example is that redefining the outfits for the headhunter (but keeping them identical to the stock) has resulted in the NPC headhunter being equipped with 4 heavy lasers even though only 2 are present in the outfits.

**Comment by Tadrix** [comment]
Can confirm. This generates the following error:
`Headhunter "ship's name": outfit "Heavy Laser" equipped but not included in outfit list.`

**Comment by tehhowch** [comment]
Fixed by #6216
