### ISSUE TITLE
Mission target system draw error on map

### ISSUE THREAD

**Issue by alex-osborn** [endless-sky/endless-sky#4415]
**Describe the bug**
There is a draw error with the system highlight circle that appears when viewing a mission on the map that targets a specific system. The circle isn't clipped correctly behind higher UI elements.

**To Reproduce**
1. Have an active mission with a system target. Example: Deep Archaeology, take wood fiber samples
2. Open the map on the missions tab
3. Select the mission
4. Scroll the map so that the target system is partially obscured by other UI elements

**Expected behavior**
The highlight should not be clipped

**Screenshots**
![Screen Shot 2019-07-02 at 11 30 44 PM](https://user-images.githubusercontent.com/880420/60751161-4d14cc00-a005-11e9-84bb-a0885f8de664.png)

**System (please complete the following information):**
 - OS: OSX
 - Game Source: Download
 - Version: 0.9.9

**Comment by ChamEV** [comment]
Had a similar issue when designing system trade price comparisons.  Just needed to draw in the correct order.

https://github.com/endless-sky/endless-sky/pull/4416
