### ISSUE TITLE
In which direction should the outfit-picture for hyperdrives point?

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#442]
I've made a hyperdrive-picture for an alien race, but i am not sure in which direction it should point.
Found nothing in https://github.com/endless-sky/endless-sky/wiki/creatingoutfits, and the already existing hyperdive-picture has no real direction.
![aqua hyperdrive](https://cloud.githubusercontent.com/assets/15857993/11762483/357dbcac-a0e8-11e5-99e3-c1600ffec4ed.png)

**Comment by endless-sky** [comment]
I guess it should point along the same axis as the engines.

Are you using the templates to make sure that the camera settings and illumination match the existing outfits? The templates are included in the asset files [here](https://drive.google.com/open?id=0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk).

**Comment by Wrzlprnft** [comment]
Nope, i am not using it, because i use cycles render to create that chrome effekt.
I do plan to put more ffort into the alignment and illumination once that stuff is really going ingame, but for now, i need just content to complete the idea and make it ready for a pull request

**Comment by Wrzlprnft** [comment]
And in my opinion it looks pretty and pretty different from what you've made, and i remember you said something about nique styles through different people.

I understand it will annoy the eye if it looks too different though, so don't worry, the perfectionistic part of me must not allow that (e.g. i cutaway the ice cannon in this picture because ingame it looks really afwul and will be changend soon)

![2015-12-12_00001](https://cloud.githubusercontent.com/assets/15857993/11762711/1d484ed8-a0f0-11e5-89a3-9c83d6f8920c.jpg)

**Comment by endless-sky** [comment]
Yes, I'm not saying that the graphics need to match the existing ones exactly. But, small things like switching from perspective to orthographic projection, or making the main light source come from the same direction, might make the graphics fit in better without changing their appearance significantly.

**Comment by Wrzlprnft** [comment]
probably i just need to redo the light sources, because as i tried the template, everything was black

**Comment by Wrzlprnft** [comment]
Yeah, i can use the template, but have to tweak the light sources

**Comment by guillochon** [comment]
I like this style and think with slight adjustment it could be used for Quarg outfits, which currently lack graphics.

**Comment by Wrzlprnft** [comment]
Oh well i was more thinking of an water/ice based alien race more in the south/west
but... why not? if the dev agrees

**Comment by Wrzlprnft** [comment]
Of course i would make the things which are at the moment tiny like the shield generator or the core make look more sophisticated an massive

**Comment by frameworld** [comment]
> @guillochon > I like this style and think with slight adjustment it could be used for Quarg outfits, which currently lack graphics.
I thought quark uses not-right-angles and have almost no curves on their ships?
This equipment pictures doesn't really fit to what I imagine when reading that in the missions/first-contact or station text. Make a random mace out of pipes and try to see a pattern in it - then derive a picture from it ;).

**Comment by Wrzlprnft** [comment]
Indeed, no curves

**Comment by anonybosch** [comment]
@Wrzlprnft  Beautiful artwork for the next alien race to be discovered. "Huzzah!"

**Comment by Wrzlprnft** [comment]
Thx :)
i think i will continue working on "my" alien race :)

**Comment by guillochon** [comment]
I see now that you had some cool glass ship designs that go along with this. I've changed my mind, it would be great to have these be a new alien race with in the game.

**Comment by Wrzlprnft** [comment]
I do have a system with planets and stuff already too.
The descriptions are not finished yet though

**Comment by Wrzlprnft** [comment]
@endless-sky: all images reworked with using the template.

![2015-12-13_00001](https://cloud.githubusercontent.com/assets/15857993/11768464/c926a514-a1cd-11e5-925c-a228e357ca0e.jpg)
