### ISSUE TITLE
Selling excess fighters can trigger silent cargo loss

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4427]
**Describe the bug**
Cargo is loaded into cargo-carrying fighters (Boxwings) before any fighters are sold for which the player doesn't have a carrier. This can cause cargo to silently disappear from the game.

This issue was found while I was looking at the PlayerInfo::TakeOff() function and I verified that the issue exists by manually replaying the reproduction scenario below.

**To Reproduce**
1. Make sure none of your ships can carry fighters and drones
2. Make sure your flagship cannot carry cargo (or only a little bit)
3. Buy some Boxwings
4. Park all ships except your flagship and boxwings
5. Get your available cargo space full with cargo (any cargo will do)
6. Take off, see a message about your boxwings getting sold
7. Notice that much of the cargo is silently gone.

**Expected behavior**
* An explicit message for all cargo that is lost.
* Missions to fail for lost mission cargo.
* The value of the cargo lost payed back to the player (for commodities and outfits).

**Screenshots**
Not applicable

**System (please complete the following information):**
 - OS: Debian Linux, but this is not relevant, the relevant code is in the function PlayerInfo::TakeOff and applies to all platforms
 - Game Source: self-compiled
 - Version: master at commit hash 1490d03a7908c18b342e36992da1091346f755e4

**Link to save file**
None yet, but I can create a save file if required.

**Additional context**
This bugreport is not related to my PR #4388, but please do consider #4388 as a possible bugfix for this issue.

**Comment by Tadrix** [comment]
> **Expected behavior**
>     * An explicit message for all cargo that is lost.
>     * Missions to fail for lost mission cargo.
>     * The value of the cargo lost payed back to the player (for commodities and outfits).

Tbh I'd expect a warning prior to taking off, so the player can reconsider without loading the game.

**Comment by petervdmeer** [comment]
> Tbh I'd expect a warning prior to taking off, so the player can reconsider without loading the game.

Yes, the warning about fighters getting sold is currently already there. If we want to keep that code as-is, then that warning needs to be extended with a warning for cargo if the fighter sale drops cargo space below the size of the cargo.

**Comment by tehhowch** [comment]
A solution that does not alter current game behavior is to first load ships into their carriers and then load cargo and passengers. Given this bug existed prior to 0.9.9, I'm not compelled to implement a behavior change or this bugfix before 0.9.10.

**Comment by petervdmeer** [comment]
> Given this bug existed prior to 0.9.9, I'm not compelled to implement a behavior change or this bugfix before 0.9.10.

For regular cargo I understand your position. But can I change your mind by arguing that this bug also affects mission cargo and might lead to inconsistent game-states where some mission-data still refers to cargo-items that are no longer in the regular cargo locations?

**Comment by jafdy** [comment]
He is saying that it will be dealt with but later, it isn't in any way game breaking or a major change.
