### ISSUE TITLE
Pirate Missions

### ISSUE THREAD

**Issue by masterpierround** [endless-sky/endless-sky#443]
One thing I would like to see is for jobs/missions to be added to pirate worlds. These missions could range from illegal drug shipments to assassinations of rival pirates, or even contract killings of Republic/Free Worlds/Syndicate ships. I was thinking that these could be extraordinarily lucrative jobs, but as you do more of them, it increases the chances of a mission being a "trap". When a mission is a "trap", you arrive to do whatever you were told, only to find that a Pirate fleet is waiting for you. Running could have some negative effect (less chance to be offered pirate jobs, monetary penalty, combat rating loss, I don't know what specifically) and defeating the pirate fleet, then returning to the source planet gives you a huge payment (the person who tried to trap you gets scared and gives you a ton of money to not kill them.)

**Comment by omagasohe** [comment]
I'm currently working on some of these. I'm working it as a plug in and maybe a pull request if i get them working right and people like it, the formatting is pretty precise and I'm not it appears.  I have 2, already worked out slave trading and smuggling, Still trying to figure out "find and board merchant" and I'd imagine turning bounty missions into assassinate rival would be fairly trivial.

I like the "it's a trap" aspect, except you get nothing when you return, the mission ends when the primary ship is toast. 

We do need an illegal passenger flag for the missions.

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
