### ISSUE TITLE
Proposal for creating ship formations using lines

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4438]
**Is your feature request related to a problem? Please describe.**
This is a proposal for specifying formations for ships (as discussed in #302 and others) by lines that are moved, rotated, extended and repeated.

My intention is that this proposal is sufficiently simple for:
- players to use (in an in-game graphical editor)
- scenario writers to use in missions (directly or through editor).
- developers to implement

The mechanism should also be sufficiently powerful to handle the most common formations that players and writers would want to define.

**Describe the solution you'd like**
The basic structure of a definition of a formation in the data-files would look like:
```
formation <name>:
	line <x> <y> <slots> <direction>
		spacing <nr>
		repeat <deltaX> <deltaY>
			increase <nr>
	line <x2> <y2> <slots2> <direction2>
		spacing <nr2>
```

Meaning of the keywords:
- `formation <name>`: Begins a new definition for a formation with name `<name>`.
- `line <x> <y> <slots> <direction>`: Begins a line at position x,y for a line with `<slots>` positions for ships. The very first ship in the line is at exactly x,y, the line stretches into the direction of `<direction>` with ships `<spacing>` distance apart. The last ship in the line is at `<slot> * <spacing>` distance from the first.
- `spacing <nr>`: The amount of space between ships on a line.
- `extend <nr>`: **(to be removed keyword)** The amount of slots to extend the line with if the formation needs to grow.
- `repeat <deltaX> <deltaY>`: The location where to repeat the line if the formation needs to grow (relative to x,y of previous repeated line).
- `increase <nr>`: The amount of extra slots to add to the line on each grow step.

Some examples:
```	
# Horizontal line formation, growing from left outwards.
formation "H-Line"
	line 0 0 1 90
		spacing 100
		extend 1

formation "Square"
	# Only specify a single top left position.
	# Expands to the right due to direction 90 and extend 1.
	# Expands to below with the repeat section. The repeat section also
	# gets the effect from extend 1, so the shape will remain a square.
	# To get a diamond formation, change the rotation to 135.
	line 0 0 1 90
		spacing 100
		extend 1
		repeat 100 0

formation "Triangle"
	# Specify only the top element and repeating lines 1 bigger every increment.
	# Each repeated line is half of the spacing to the left of the previous one.
	# The lines in the triangle all get filled from the left. If it is desired to
	# alternate the filling between left and right, then specify the first 2 lines
	# First from right to left, second from left to right and repeat both lines
	# alternating (and with increases of 2).
	line 0 0 1 90
		spacing 100 
		repeat -50 100
			increase 1
```
			
Here the Square and Triangle in pictures. Black is the initial line. Blue is the first repeat of the line(s), red is the second repeat of the line(s).
Arrows indicate extentions of a line when doing an extend/repeat step. Dashes are part of the line present in the extend/repeat step.
![formations](https://user-images.githubusercontent.com/35403542/61498329-23738180-a9c3-11e9-8b13-4e8d474c155f.png)

Here a more complex example (for a formation to protect something in the middle):

```
formation "Outer Rectangle"
	# Top line, extending upward for large formations
	line -100 -300 3 90
		spacing 100
		repeat -100 -100
			increase 2
	# Left side
	line -200 300 7 0
		spacing 100
		repeat -100 100
			increase 2
	# Bottom, left out the repeat here for better showing the mechanism in the picture.
	line 100 300 3 270
		spacing 100
	# Right side
	line 200 -300 7 180
		spacing 100
		repeat 100 -100
			increase 2
```
			
And also this formation in a picture (again: Black is the initial line. Blue is the first repeat of the line(s), red is the second repeat of the line(s)):
![formations2](https://user-images.githubusercontent.com/35403542/61498334-28d0cc00-a9c3-11e9-897a-a1eeb87c6322.png)

Formations don't need to stick with just 90 degree angles on the lines. Here is a formation with 45 degree angles:
```
formation "Vee"
	# The leg going to "back left"
	line 0 0 2 225
		spacing 80
		extend 1
	# The leg going to "back right"
	line 56.5 56.5 2 135
		spacing 80
		extend 1
```

**Describe alternatives you've considered**
This idea is partially inspired by the formation description as proposed by @tehhowch in #4418.

I have also looked at #302 and it's duplicates for inspiration.

In an earlier proposal I considered to use advanced mathematical formulae that immediately give x-coordinates and y-coordinates based on the position-number, but that quickly got to very advanced mathematics for even the most simple formations.

**Additional context**
Some other things to consider for formations of ships:
- Ship types in formations (my expectation is that we can create a formation per ship-type, transports in a line-formation in the middle, "Outer rectangle" of sparrows around them)
-- Formation spacing based on ship sizes (I expect that we will use a multiplier based on the size of the largest ship, to be added as keyword later.)
- How to deal with ships getting killed in a formation (moving later ships to earlier positions seems the most sensible).
- I personally would like to also use (parts of) circles as formation elements. For this I would want to add an "Arc" element similar to the line, but with an angle and radius. But let's first discuss the Line based formations and discuss adding Arc in a different feature request.
- When to stay in formation and when to break (I would expect this to be handled by the personalities set for ships).
- Ships in a formation will sync based on the movement vector of the reference/lead ship (not the facing vector of the reference/lead ship). I tested this in #4418 and it seems to work quite well with current station keeping.
- Please note that this proposal only specifies the data-format. This is only part of the puzzle to get to working formations, some more feature-requests and PR will be needed for example to map ships to formation position-numbers.

**What is expected of you, reader of this feature request**
Please provide review feedback on this proposal. For example:
- Do you consider this data-format for creating formations easy to use?
-- Do you see improvements to make the data-format simpler or more powerful?
- Can your favorite formations be implemented using this data-format?
- Do you see fundamental issues with this data-format that would prevent you from using formations as you would like?

**Comment by ChamEV** [comment]
As far as interface to adding formations goes, I suggest checking this out: https://youtu.be/5GZkYxbLw8Q?t=638 specifically at that timestamp, has units selected, then he right clicks and drags to create a line, and all the units move to equally spaced points on that line.  It feels really natural.  You can check out zero-k on steam as it has this feature as well if you want to play with it.  Notably this line can be as curvy as the user wants to make it, or doubling back or whatever it doesn't care.

The trick with formations will be making the interface not be overwhelming to the player, nor the content creator.  I think you are right to save the data on a line, have the units equally spaced along it may be preferable in some cases than moving up to pre defined positions along it, but it may be hard to adjust to losing ships in some formations.

Presumably formation definitions are top level, allowing you define all the common formations at once, and let content creators use them by just specifying which formation a fleet or mission ships are using.

**Comment by Tadrix** [comment]
I'm not sure that the rectangular grid is a good idea, especially for formations like "circle". Hexagonal grid might be a better solution.

Formations we might have a use for:
Delta (for up to medium ships)
Broad (a line, for medium ships and larger)
Inverted wedge (for up to medium ships, should be in a parabolic shape, useful for surrounding the enemy)
Circle (kind of what we have if order the fleet to gather, only without the swarming, useful for them to defend each other)

**Comment by petervdmeer** [comment]
@Tadrix The grid is not rectangular, only the first and last drawn examples look like a grid. You can set coordinates for the start of the line(s) any way you like. With this proposal you could even already calculate the locations for a circle by hand and build it by line-segments of length 1 (or 2).

If you would want a hex-grid formation, then this is the specification to use:
```
formation "Hex-field"
	# Field with each line alternating 0.5 from each previous line.
	line 0 0 2 90
		extend 2
		spacing 100 
		repeat 0 200
	line 50 100 2 90
		extend 2
		spacing 100
		repeat 0 200
```

**Comment by petervdmeer** [comment]
Here is an example for if you already want to specify a simple circle with 8 positions now (without support for arcs). I might be a very little bit off on the diagonal parts:

```
formation "Simple 8-Pos Circle"
	line -200 0 2 90
		spacing 400
	line 0 -200 2 180
		spacing 400
	line -140 140 2 45
		spacing 400
	line -140 -140 2 225
		spacing 400
```

**Comment by petervdmeer** [comment]
Updated/simplified/corrected some of the formation descriptions in the initial text.

**Comment by petervdmeer** [comment]
I've done some testing and the `extend` keyword gives very chaotic position behavior when ships get added or removed from formations. Formations also work fine without `extend`, so I plan to remove the `extend` keyword.

**Comment by petervdmeer** [comment]
I implemented some of this. Here is a movie to test how this works: https://youtu.be/W0RrTRSSqGs

**Comment by petervdmeer** [comment]
Moved this proposal/specification to an feature design/rfc document in https://github.com/EndlessSkyCommunity/endless-sky/pull/52
