### ISSUE TITLE
Missing Quarg outfit descriptions; able to extract tribute from Quarg planet 

### ISSUE THREAD

**Issue by kaylara** [endless-sky/endless-sky#4439]
This is vaguely related to https://github.com/endless-sky/endless-sky/issues/986 .

Two things I noticed in my current play-through of 0.9.9:
1.) Some Quarg outfits don't have descriptions:

- The Quarg Anti-Missile. Proposed description: "The Quarg Anti-Missile is one of the most powerful defense systems anywhere in the known universe, capable of defending against almost any threats."

- Nanotech Battery. Proposed description: "Quarg engineers have a deep knowledge of energy and energy manipulation. Their Nanotech Battery is centuries beyond the understanding of either Hai or Human practitioners. 

- Medium Graviton Thrusters. Proposed description: "Gravitons come out of the thrusters at the speed of light, providing a powerful anti-gravity thrust. While the mechanism of graviton generation is unclear, it generates less heat than the equivalent atomic engines."

- Medium Graviton Steering. Proposed description: "Similar to the Graviton Thrusters, Graviton Steering shoots gravitons at the speed of light, providing a powerful anti-gravity thrust. These matched pairs of ejectors allow for rapid ship rotation."

- Quantum Shield Generator. Proposed description: "The Quarg have tapped into a high-efficiency superconductor to efficiently recharge shields without generating any heat. Amazing technology, but it weighs tons."

Sorry if I missed any others.

2.) The Quarg planet Humanika in the Sadalmelik system allows me to demand tribute. I expect this is a minor oversight, as no other alien worlds allow tribute that I can see.

**Comment by Amazinite** [comment]
Humanika is a human planet. It just so happens to be in Quarg territory. Hence why you can demand tribute from it, but the Quarg defend it.

**Comment by kaylara** [comment]
Thanks, @Amazinite! Sorry I missed the human ownership.

**Comment by kaylara** [comment]
@Amazinite Any objection to me trying to update the Quarg outfit descriptions?

**Comment by Amazinite** [comment]
Have at it if you want, but whatever is written will probably change once I (or someone else) get back around to finishing #3665.
