### ISSUE TITLE
No landing image

### ISSUE THREAD

**Issue by tmoftdead** [endless-sky/endless-sky#4447]
**Describe the bug**
I landed on freedom on steam 9.9 beta, It doesn't have an image

**To Reproduce**
Steps how I reproduced the behavior:
1. Go to 'Freedom'
2. Click land
3. See error

**Expected behavior**
Seeing freedom's landing image

**Screenshots, save and error file**
![no landing image](https://user-images.githubusercontent.com/52049166/62125676-75c37500-b2d6-11e9-97ef-ff933b1706d0.PNG)
error file is empty
[Taylor Stuart.txt](https://github.com/endless-sky/endless-sky/files/3446575/Taylor.Stuart.txt)

**System (please complete the following information):**
 - OS: Windows 10 
 - Game Source: Steam beta
 - Version: 9.9

**Additional context**
I switched from github beta to steam beta, If that does help.
Edit: I closed the game and opened it. Got the right response after opening the save but I think it isn't resolved yet.

**Comment by MCOfficer** [comment]
> I switched from github beta to steam beta, If that does help.
what exactly do you mean by GitHub beta, and how did you make the switch?

> Edit: I closed the game and opened it. Got the right response after opening the save but I think it isn't resolved yet.
so the second time it worked, but the first time it didn't?

**Comment by tmoftdead** [comment]
my save was in 9.9 that I downloaded from github, I deleted the files and opted into beta in steam to play in 9.9. 
 no, I landed on the planet and saw this. After I closed endless sky to report this bug. When I opened the game back again, it wasn't transparent like this.

**Comment by Amazinite** [comment]
#209/#156 popping back up?

**Comment by tmoftdead** [comment]
I think so.

**Comment by tehhowch** [comment]
Can you comment on your system hardware? Specifically, your hard drive and memory: e.g. "ST500LT032", 8 GB RAM
![image](https://user-images.githubusercontent.com/20871346/62837584-c3c16c80-bc36-11e9-9669-e15459e1c810.png)
![image](https://user-images.githubusercontent.com/20871346/62837627-23b81300-bc37-11e9-8814-1e3dfde5d8c7.png)

Can you also comment on what you were doing in-game? E.g. were you doing a lot of cargo runs, was Caps Lock speedup enabled, etc.

**Comment by tmoftdead** [comment]
![Capture](https://user-images.githubusercontent.com/52049166/63221110-c7a44000-c19c-11e9-8291-cd52bc72881e.PNG)
![Capture2](https://user-images.githubusercontent.com/52049166/63221112-ca069a00-c19c-11e9-86fe-72a0227ba4ca.PNG)
Caps lock speedup was enabled. I was doing cargo runs but parked my ships before this bug. I was trying to boost up my money supply.

**Comment by quyykk** [comment]
This is probably fixed now. If anybody else encounters this bug, create a new issue.
