### ISSUE TITLE
Add a way to transfer cargo to/from escorts in-flight

### ISSUE THREAD

**Issue by mouseas** [endless-sky/endless-sky#4450]
**Is your feature request related to a problem? Please describe.**
When I'm plundering ships with the help of my fleet, I find it frustrating that I'm limited to my own cargo hold while my fleet members' holds are left empty. In order to free up space in my hold, I either have to dump cargo (which is then lost), or I have to land somewhere (which redistributes cargo to escorts, but makes all the disabled ships disappear).

**Related Issue Links**
#4208 is semi-related. Being able to transfer cargo to an escort would get you halfway to solving #4208 - then you'd just need to be able to install them as outfits

**Describe the solution you'd like**
I'd like to be able to board/dock with an escort and transfer cargo back and forth between my flagship and the targeted escort mid-flight.

**Describe alternatives you've considered**
An alternative would be a command to escorts (Shift-F?) to plunder the targeted disabled ship; escorts would then take turns boarding the ship and filling their holds with the plunder, picking the most valuable options first. 

**Additional related features worth considering**
- transfer crew members between escorts & flagship, e.g. to replenish crew on under-crewed ships
- switch ships mid-flight
    - escape pods
        - if your ship is destroyed, your escort could come pick your pod up; you'd then take over command of their ship
        - pick up escape pods from friendly ships and return them to port for a "rescue fee" and/or faction friendliness points
        - pick up escape pods from escorts (and possibly friendly/allied ships) to replenish lost crew
- put cargo into disabled ships
    - no longer have to leave "board ship" screen, dump cargo, then re-board in order to make room in your hold
    - possible mission objective to plant evidence or surveillance equipment in an enemy ship

**Comment by jafdy** [comment]
#4100
