### ISSUE TITLE
Wiki should include directives for engine flare sizes

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#4451]
While working to update Marauding Max, I was reminded that M.Z. suggested flare size consistency practices in a comment on commit: https://github.com/endless-sky/endless-sky/commit/436d345cb9a2b9a1a9990574ab16013d8155923d

While the wiki mentions that sizes can be specified, the guideline is missing.

**Comment by Amazinite** [comment]
How's this sound?

>`"engine"`: the (x, y) coordinates... flares than others. *It is suggested that the sum of the squares of the zoom factors be roughly equal to 2 so that the total area of the engine flares is the same across ships. (Example: A ship with three engines could have an engine with a zoom factor of 1 and two with zoom factors of 0.7, as 1^2 + 0.7^2 + 0.7^2 is roughly 2.)*

**Comment by LocalGod79** [comment]
I think that M.Z.'s examples of multiple engine configurations is really strong, but this would be sufficient - someone with a proposal would likely seek guidance on discord or elsewhere as well.
