### ISSUE TITLE
The German (and French) game title translation is silly: weltraumspiel = space game

### ISSUE THREAD

**Issue by rugk** [endless-sky/endless-sky#4453]
The appstream metadata is AFAIK what is used to display the name of an app in GNOME Software, independent of the source for the app.

Now, in German it says "Weltraumspiel" as **the title** of the game! That basically translates to "space game".
IMHO game titles should be left unchanged.

As I suspect you maintain the appstream metadata here, I open an issue here. Please direct me to the correct direction, if I am wrong.

![image](https://user-images.githubusercontent.com/11966684/62479719-5e8cf780-b7ae-11e9-9a04-6d54fa9bb1d5.png)

**Comment by tehhowch** [comment]
The relevant edits can indeed be made here, by modifying the appdata.xml file: https://github.com/endless-sky/endless-sky/blob/master/endless-sky.appdata.xml

If you wish, you may open a PR from your fork to do so; otherwise a maintainer will do so before the next release.

**Comment by rugk** [comment]
Okay, also looked at the French translation and and according to my translation tool (DeepL) it also means "space game". So I'll change it, too.

**Comment by rugk** [comment]
Thanks, done.
