### ISSUE TITLE
Turret rotation issue on Linux ppc64le

### ISSUE THREAD

**Issue by sdennie** [endless-sky/endless-sky#4456]
When playing 0.9.9 on Linux ppc64le (Ubuntu 18.04), turrets only rotate in the positive direction.  Specifically, in AI::AimTurrets, a negative value sent into Command::SetAim causes the turrets to stop rotating until the shortest path to target becomes positive again.  Surprisingly, the fix for this is to define Command::aim[32] as int8_t instead of char.

That seemed unlikely so, I investigated a bit further.  Here is a simple program that represents the meat of Command::SetAim and Command::Aim

```c++
#include <iostream>
#include <cmath>

using namespace std;

int main()
{
    double amount = -0.1;
    char foo;
    int8_t bar;

    foo = round(127. * max(-1., min(1., amount)));
    bar = round(127. * max(-1., min(1., amount)));

    std::cout << "foo: " << (int)foo << "  bar: " << (int)bar << std::endl;
    std::cout << "foo: " << foo / 127. << "  bar: " << bar / 127. << std::endl;

    return 0;
}
```

One would expect foo and bar to print the same values and, on amd64, they do:
```
$ g++ -O3 foo.cpp
$ ./a.out
foo: -13  bar: -13
foo: -0.102362  bar: -0.102362
```

However, on ppc64le they do not:
```
$ g++ -O3 foo.cpp
$ ./a.out
foo: 0  bar: -13
foo: 0  bar: -0.102362
```

Since foo never goes negative, turrets stop rotating once the target moves to a position where they need to rotate in the negative direction.  I'm not quite sure why there is a difference between int8_t and char in this case.  Maybe a subtle difference in the round function.  However, other than this issue, the game plays flawlessly on ppc64le.

This may be hard to reproduce without access to a ppc64le machine so, hopefully I've included enough information.  Let me know if you need more.

**Comment by AdamKauffman** [comment]
Maybe a char is compiled to be unsigned by default on ppc64le. To test this you could either compile it with an explicit flag like `-fsigned-char` to ensure the char is signed or you could change the definition in the code to `signed char foo;`

I prefer the latter because it shows intent. You intend to have negative numbers in that char.

**Comment by tehhowch** [comment]
Default `char` on ppc is unsigned from what I've read, so feel free to open a PR changing it to a signed representation. I don't see any other places where we're using `char` when a signed int is more appropriate.

I'll get to this myself in the next day or so if no one else has

**Comment by sdennie** [comment]
Yes, chars default to unsigned on ppc64le.  I'm new to the platform and so that hadn't occurred to me as the problem.  I've created a pull request to make the aim array explicitly signed.
