### ISSUE TITLE
Meteor Missile says that the capacity is 35, but can only buy up to 30

### ISSUE THREAD

**Issue by pyorokun7** [endless-sky/endless-sky#4459]
**Describe the bug**
Meteor missile description incorrectly says that the Meteor Launcher has a capacity of 35 missiles, while the correct capacity is 30

**To Reproduce**
1. Buy a Meteor Missile Launcher
2. Attemp to buy more than 30 Meteor Missiles

**Expected behavior**
That I should be able to buy up to 35 missiles.

**Screenshots**
![image](https://user-images.githubusercontent.com/8069514/62643112-d8d38e00-b90c-11e9-914f-f041c69c9e9b.png)
![image](https://user-images.githubusercontent.com/8069514/62643129-e6891380-b90c-11e9-9ef7-ccd410c3e789.png)

**System (please complete the following information):**
 - OS: Windows 10 Home
 - Game Source: Download from github
 - Version: 0.9.9

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**
Probably the capacity shouldn't be described in the missile, only in the launcher, to avoid having to update the description of the missile if the capacity is changed

**Comment by MCOfficer** [comment]
already fixed, will be part of 0.9.9: fdeab958e946d9422f344d25f25612b1b019e4ec

**Comment by beccabunny** [comment]
*0.9.10

**Comment by pyorokun7** [comment]
Ah, thanks, I didn't think to check if there was a commit for this. Only checked the issues
