### ISSUE TITLE
Captured a ship with more than maximum crew

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#446]
![screenshot from 2015-12-12 19 51 06](https://cloud.githubusercontent.com/assets/692397/11764734/e82eea58-a109-11e5-8229-c7dcb5fce55d.jpg)

Just captured this pirate vanguard and noticed that it had 46 crew and 45 bunks.  I haven't messed with the bunk space or anything, just swapped out the weapons and shields.

**Comment by endless-sky** [comment]
Oops. I recently modified the outfitter to automatically add crew if you add an outfit (like a heavy laser turret) that requires crew. But, that was making your ship go above the maximum crew. Fixed in 4267d56.

**Comment by endless-sky** [comment]
0.8.9 is now release, so I'm closing this.
