### ISSUE TITLE
Rename "North", "South", etc. to directions appliable to a galaxy

### ISSUE THREAD

**Issue by FranchuFranchu** [endless-sky/endless-sky#4460]
**Is your feature request related to a problem? Please describe.**
I feel rather annoyed by the fact that the game calls different directions of the galaxy "north", "south", "east", "west", in missions and region names, when there is actually no up or down in space, neither north or south.

**Related Issue Links**
None

**Describe the solution you'd like**
The game's strings should be changed. I've thought maybe we could have a polar system, such as "corewise", "rimwise", "spinwise" (the direction the galaxy is spinning), and "counterspinwise".

**Describe alternatives you've considered**
Some other names could be:

- Clockwise for spinwise, and counterclockwise for counterspinwise. The early space explorators might have compared the Galaxy with a clock, where the clock hand(s) are the spiral arms of the Milky Way.
- We could also have the directions named relative to constelations and visible objects from the Earth:
- "Saggitarius" for corewise
- "Perseus" for rimwise
 

**Additional context**
None

**Comment by Amazinite** [comment]
>I feel rather annoyed by the fact that the game calls different directions of the galaxy "north", "south", "east", "west", in missions and region names, when there is actually no up or down in space, neither north or south.

This discussion has popped up on Steam before. https://steamcommunity.com/app/404410/discussions/0/1736594593595718075/

See: https://en.wikipedia.org/wiki/Galactic_coordinate_system
Said simply, "north," "south," "east," and "west" are simply references to somewhere in space, and so long as those references are defined then it's possible to use them. 
On Earth, north refers to in the direction of the north pole, south refers to in the direction of the south pole, east refers to toward the rotation of the Earth, and west refers to opposite the rotation of the Earth. In space, those words are redefined to refer to various regions of the galaxy. 
It's notable that only the humans in game use cardinal directions; all instances of aliens using cardinal directions are when they're speaking to a human (e.g. the Hai telling you where to watch out for the Unfettered, the Quarg telling you to watch out for the Korath). And these directions seems to be defined by human space, not by the galaxy as a whole (see "Far North" not actually being that far north in terms of the galaxy map).

**Comment by MCOfficer** [comment]
> See: [en.wikipedia.org/wiki/Galactic_coordinate_system](https://en.wikipedia.org/wiki/Galactic_coordinate_system)
> Said simply, "north," "south," "east," and "west" are simply references to somewhere in space, and so long as those references are defined then it's possible to use them.

and one more thing: they're the only universally understandable references we have, since "up" and "down" are even more ambiguous when looking at a map of space. i suppose we could use "corebound or rimbound in some occasions, but in many cases, that's ambiguous as well.

**Comment by Zitchas** [comment]
I definitely like the idea of using the terms more appropriate to a spinning disk rather than N/E/S/W.

**Comment by SNova42** [comment]
I’d say the cardinal directions system is already very practical and suitable. The galaxy is mapped onto a 2D map, and is, in reality, mostly planar. It is then trivial to define a center (Earth) and an arbitrary object as North. The rest follows.

‘Coreward’, ‘Rimward’, ‘Spinwise’, and ‘Counterspinwise’ may seem to be more apt for a spinning galaxy, but in practice such a system based on polar coordinates poses many problems. Perhaps most notably, ‘Rimward’ is rather meaningless when describing absolute positions. How are we supposed to differentiate places like the Deep and the Rim? Specifying degrees ‘Spinwise’ / ‘Counterspinwise’? You’d still need to define an arbitrary ‘zero degree’ direction. With the cardinal directions, you can simply say the Deep is in the West, and the Rim is to the South-Southwest.

**Comment by MCOfficer** [comment]
thinking about it, i see no reason to have a dominant way of references. some may tell you to travel spinwise while others call it west... makes for a realistic galaxy, since we ourselves have split opinions, it seems

**Comment by jafdy** [comment]
Probably because it is looked at on a flat map, and that the galaxy spins so slowly that it might as well be stationary to the average person (225-250 million years for sol). If you started life on a planet you would be used to this cardinal system so even though it would be quite reference-less in space it would still be more natural than to name half your system after an effect that doesn't really do much in the human lifetime. Plus polars are annoying for most people to work with at the best of time.
Having some "I must be correct" type of scientist use them could be an interesting addition.

**Comment by Bladewood** [comment]
A big problem with this is that it completely invalidates the name "Southbound Shipyards," which is a pretty cool and dastardly pun.

**Comment by Pointedstick** [comment]
This seems like an example of sacrificing comprehensibility for hard sci-fi realism in a way that's not actually a net improvement.

**Comment by Zitchas** [comment]
I think MCO had a good point a while back: Why should everyone use the same terms and references? Let's leave humanity with the terms they use now, and other groups can adopt alternative ways of describing directions in the galaxy. Might help differentiate groups, too.

**Comment by AlbertNewton** [comment]
As a subtle reference to Terry Pratchett's Discworld novels, we could have North and South be referred to by someone as Hubward and Rimward. Turnwise is also fairly self-explanatory, though Widdershins is a little more obscure.
