### ISSUE TITLE
spaceport news mixing up roles and messages

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4463]
people with different professions in spaceport (e.g. scientist, merchant, loan breaker etc.) may sometimes say something that is more sensible for other profession 

To Reproduce:
1. land on a planet/station/whatever
2. press letter p on keyboard repeatedly
3. pay close attention to the profession and message: the bug seems to happen at random

the person with a given profession would present a corresponding message

![Screenshot 2019-08-10 at 17 36 18](https://user-images.githubusercontent.com/45012410/62823891-cc626600-bb96-11e9-900c-c612336a2d0f.png)
in a screenshot attached, a scientist is presenting a message that would be more corresponding of a loan breaker

 - OS: macOSX 10.14.3 (Mojave)
 - Game Source: GitHub .dmg image download
 - Version: 0.9.9(unstable)

here is a link to my savefile, in case it is case-specific: https://pastebin.com/3QiaqWdV

**Comment by MCOfficer** [comment]
i can't find anything to prove it, but i believe this was addressed already. can somebody confirm?

**Comment by oo13** [comment]
I reproduce it.

In SpaceportPanel::UpdateNews(), news->Message() returns a wrong message, because the function replaces "name" of the profession, but not replaces "news" when its portrait was already shown as another profession in a same spaceport.

It should cache the message, or create an additional method in GameData.

**Comment by downRightCoder256** [comment]
> I reproduce it.
> 
> In SpaceportPanel::UpdateNews(), news->Message() returns a wrong message, because the function replaces "name" of the profession, but not replaces "news" when its portrait was already shown as another profession in a same spaceport.
> 
> It should cache the message, or create an additional method in GameData.

thanks for backing me! now I'm sure im not going crazy.

I really do enjoy this game, an the idea of the project as a whole, though I do not have much more time to enjoy it other than a game. ill try to see how can I contribute to it when I Finnish my school

**Comment by tehhowch** [comment]
It's related to my commit that was intended to avoid showing different professions for the same portrait on the same planet & day. The simplest solution is likely to revert that commit, and then we are back to having an "inconsistency".

Another option would be to check if the `News` instance is the same as that which provided the original portrait (e.g. same profession and set of content), and if not, either show no news popup, or retry for a different portrait.

**Comment by tehhowch** [comment]
Given that it's not a serious bug, and it can be solved with content changes or code changes, I'm tagging as `0.9.x` rather than a release blocker

**Comment by NomadicVolcano** [comment]
Could you please try PR #5072 and see if it fixes the bug?

It fixed it in my tests.
