### ISSUE TITLE
Always select the first available mission when clicking a new system

### ISSUE THREAD

**Issue by alextd** [endless-sky/endless-sky#4464]
(I'm moving my unfinished [Pull Request](https://github.com/endless-sky/endless-sky/pull/4414) to an issue for someone else to finish)

**Is your feature request related to a problem? Please describe.**
When I am on the mission screen and I click a system, I want to select a new available mission, not a mission I'm already on. Which mission gets highlighted right now is unintuitive and seemingly inconsistent.

**Related Issue Links**
I actually coded up a quick fix and made a [Pull Request](https://github.com/endless-sky/endless-sky/pull/4414), but it would introduce another problem - resetting the mission to the first when you select a system without missions. I didn't get a project set up to compile so I didn't put effort to completing this.

**Describe the solution you'd like**
Always select the first available mission when clicking a new system. (But make sure it doesn't change the selection when selecting a system with no missions

**Comment by warp-core** [comment]
Added by #6896.
