### ISSUE TITLE
Caps lock for game speed broken

### ISSUE THREAD

**Issue by mountainofcheezo** [endless-sky/endless-sky#4465]
Caps lock not working to change game speed on Mac OS X once updated to 0.9.9

Only works if I close out of game and then press caps lock and then reopen game, game will open in high speed but will not change on command.

**Comment by DiamonRaph** [comment]
For other people's Infomation. He said that his Caps Lock does work for everything else.

**Comment by MCOfficer** [comment]
and here's me, not finding the correct issue again... but i swear i've heard of something similar before, where (on OSX) capslock would only work & not work depending on ES's focus. 
i think we were speculating about a potential SDL2 bug. rings a bell? @tehhowch

**Comment by mountainofcheezo** [comment]
Seems to work now after updating my os. Sorry about that. mysterious.
