### ISSUE TITLE
carriers not showing fighters on hail image

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4466]
carrier with visible fighters will not display them on their hail icons

1. when in space, select one of the carriers with visible fighters on them (e.g. nest, roost, sklein...)
2.hail it (press T)

if the carrier if carrying any fighters, they should appear on the icon, but they don't

**Screenshots**
![Screenshot 2019-08-11 at 16 08 54](https://user-images.githubusercontent.com/45012410/62840094-6f99a500-bc95-11e9-9c9d-033df968c2a0.png)
![Screenshot 2019-08-11 at 23 54 41](https://user-images.githubusercontent.com/45012410/62840098-77594980-bc95-11e9-99c8-878943642503.png)
![Screenshot 2019-08-11 at 23 54 34](https://user-images.githubusercontent.com/45012410/62840103-80e2b180-bc95-11e9-85e4-f522b1cd0c17.png)

 - OS: MacOSX 10.14.3 (Mojave)
 - Game Source: GitHub .dmg disk image
 - Version: 0.9.9 unstable

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

NOTE: I have only tested this bug with Nest, Roost and Sklein. AFAIK there are only two more ships with visible fighters: Tek Far 71 - Lek and Tek Far 78 -Osk, and though tf71-l actually carries drones, im pretty sure this would occur with it too.

**Comment by MCOfficer** [comment]
this is "intended" (known) behavior, since the hail only renders the ship's sprite, not its children. still, i can see how can be desirable from a user's perspective. +1, but be aware that this'll likely become an effort/benefit thing.
