### ISSUE TITLE
Conflicting crew counts

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#447]
![screenshot from 2015-12-12 19 55 26](https://cloud.githubusercontent.com/assets/692397/11764753/875b5a8a-a10a-11e5-8ca6-5ee34911826a.jpg)
![screenshot from 2015-12-12 19 55 35](https://cloud.githubusercontent.com/assets/692397/11764752/875a843e-a10a-11e5-94eb-a9d9c224c2a7.jpg)
![screenshot from 2015-12-12 19 57 56](https://cloud.githubusercontent.com/assets/692397/11764760/01fa4ae4-a10b-11e5-9870-32270925c754.jpg)
The player info window says my carrier has 114 crew, while the screen for the ship itself shows 140 crew.  When I set it as my flag ship and park all escorts, I pay 13900 in salary, indicating that 140 is the correct number.  Boarding also shows 140.

**Comment by guillochon** [comment]
Improved the crew count display in the InfoPanel screen in https://github.com/endless-sky/endless-sky/pull/448.

**Comment by brick96** [comment]
Did you capture the ship? You might not have had enough crew to pilot both ships and landing hired the minimum crew

**Comment by endless-sky** [comment]
When a ship is not your flagship, it behaves as if it only has the minimum crew (since extra crew on anything but your flagship are useless), but internally it remembers how many crew it had so that if you switch it to your flagship again, you won't have to re-hire those crew.

The bug is that in the info panel I wasn't taking that into account.

**Comment by endless-sky** [comment]
Commit 23483a3 switches back to showing required crew instead of actual in the ship info, which I think is preferable because especially in the outfitter, knowing how changes you make are affecting required crew is more important than knowing the actual crew count.

**Comment by endless-sky** [comment]
0.8.9 is now release, so I'm closing this.
