### ISSUE TITLE
Subpoenaed to appear at court on Earth: made it in time, warrant was still issued  

### ISSUE THREAD

**Issue by ggeorgovassilis** [endless-sky/endless-sky#4481]
**Describe the bug**
The subpoena for landing on an asteroid was handed to me _while_ visiting Earth, expired immediately and didn't leave me a chance to appear in court. This affects 0.9.9

**To Reproduce**
Steps to reproduce the behavior (hard to reproduce because subpoena is handed to you randomly):
1. Do the mission that requires landing on an asteroid
2. Visit Sol
3. Land on Earth
4. Observe that you're handed a subpoena and the mission "travel to Earth" appears in the mission log
5. When you leave Earth, the mission has expired and you're at war with the Republic

**Expected behavior**
The mission doesn't expire immediatelly

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build: `http://mcofficer.me:8080/job/endless-sky-win64/<build number>/`)

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by Amazinite** [comment]
Already been reported and fixed. 994292509d4c7d22f92a8eb242a6bd36d71a7805 52d5a63fb3eed7f8c67df0246faea97c157f4d81 a0322e99409ab4ee01b9364bad4d0cf29460b094
