### ISSUE TITLE
Overload individual cargo-holds if total cargo space should fit

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4483]
**Is your feature request related to a problem? Please describe.**
Related to #2754. When a piece of cargo doesn't fit in a cargo hold late during loading (because total cargo space is sufficient, but individual cargo holds are too small for a large item), then such cargo will be sold in the current implementation.

**Related Issue Links**
@tehhowch already reduced the change of overloads occurring by #2757, but it can still happen, for example if we have an outfit of size 90 and 2 star-barges with cargo-space 50 to carry such outfits.

**Describe the solution you'd like**
This change-request is to change the loading algorithm to still load the piece of cargo anyway into any player-ship even if it strictly does not have sufficient space left.

A message will be sent during/after departure about the overload:
`Some of your ships were loaded outside their design specifications due to large cargo items.`

Or in case of passengers (but that is unlikely in the current implementation):
`Some of your ships were overbooked due to too large passenger groups.`

Each ship that has been overloaded will get an overloaded attribute set to the amount of cargo with which the ship was overloaded.
When the player lands with a group of ships, then the overload attributes from all ships will be summarized and copied to the common cargo-storage. The amount of "cargo allowed for take-off" would be the cargo-space plus the amount of overload.
This will solve situations where players land with a partial fleet and would be unable to take off if the underloaded ships were in a different system during landing.
The overload attribute will be reduced if the player has sufficient cargo space (or if the player sells items).

Overload is only calculated on departure and landing. (Selling ships can still lead to insuffcient cargo space at takeoff as is now.)

Overloading and overbooking attributes can also be updated in-flight, if passengers and cargo transferred in-flight would lead to a overbooking situation.

**Describe alternatives you've considered**
- Leaving the excess cargo on the planet (planetary cargo storage, #4443)
- Storing the excess cargo in the player information (instead of in a ship, transporting the cargo silently outside ships)

**Comment by jafdy** [comment]
How would this add to the player experience. And how would this avoid the obvious problem of loading an outfit heavier than your ship into your cargo hold.
Also, the fleet left behind problem only happens when you load a save and is a known issue.

**Comment by petervdmeer** [comment]
> How would this add to the player experience.

The benefit for the player is that if the game says that 100 tons of cargo-space is available (in the outfitters section or in the jobs section), that the player then can use the full 100 tons of cargo space. Even if the individual ships might only have 50 tons of cargo space each and one item to be loaded is 90 tons.

> And how would this avoid the obvious problem of loading an outfit heavier than your ship into your cargo hold.

Fun/game-play over realism. In the example above (with two star-barges) one star-barge would be loaded with 90 tons of cargo (40 more than would fit according to spec, but the game-engine can handle 90 tons of cargo in such star-barge just fine) and the other star-barge would be loaded with 10 tons of cargo (instead of 50).

> Also, the fleet left behind problem only happens when you load a save and is a known issue.

No, this is also an issue in the example above if the star-barge with 90 tons of cargo lands with the player while the star-barge with 10 tons of cargo was still in a previous system.

**Comment by jafdy** [comment]
>This will solve situations where players land with a partial fleet and would be unable to take off if the underloaded ships were in a different system during landing.

You advertise this as fixing a problem then tell me that the problem is fixes isn't a problem in the current game. Don't claim it fixes a problem that isn't a problem in the current game, that's just bad form.

OK, so if you are allowed to pack 90 tones of cargo into a starbarge, then why can't you at least fill up the hold of the other starbarge. There is no point in leaving it mostly empty, and for that matter, why can't you over fill everything.

Imagine it as a pair of rowing boats and a car, (lets say the car weighs 1 ton and the boats can carry 1/2 tons each). Combined the boats can clearly carry the car, so you would load the car onto one boat and leave the other one empty to compensate. Taking your proposal at face value would imply when you launch these boats you will be fine, common sense would suggest otherwise.

**Comment by petervdmeer** [comment]
> You advertise this as fixing a problem then tell me that the problem is fixes isn't a problem in the current game. Don't claim it fixes a problem that isn't a problem in the current game, that's just bad form.

Sorry if my earlier description wasn't clear, I do want to solve a problem that is in the current game. This is a picture of the problem that I want to have fixed:
![cargo_overload](https://user-images.githubusercontent.com/35403542/63330862-d9b8e680-c334-11e9-8983-12c3901222b5.png)

The game currently allows me to buy the boulder reactor into cargo, but when I take off, then the boulder reactor automatically gets sold (without even a warning in advance).

> OK, so if you are allowed to pack 90 tones of cargo into a starbarge, then why can't you at least fill up the hold of the other starbarge. There is no point in leaving it mostly empty, and for that matter, why can't you over fill everything.

Overfilling is not a goal in itself, it is a proposed solution for large cargo-items that fit in the cargo space according to the outfitter-panel, but that turn out not to be fitting in a cargo-hold during loading.

> Imagine it as a pair of rowing boats and a car, (lets say the car weighs 1 ton and the boats can carry 1/2 tons each). Combined the boats can clearly carry the car, so you would load the car onto one boat and leave the other one empty to compensate. Taking your proposal at face value would imply when you launch these boats you will be fine, common sense would suggest otherwise.

True. That why I said "fun/game-play over realism".
If we want to fix this with more realism, then that would require a large amount of code-changes and it would probably introduce quite a bit of additional micro-management.

**Comment by beccabunny** [comment]
Personally, I think that a warning before departing would be enough, something akin to the current excessive drones/fighters (not a great example since it will probably be removed soon, but I couldn't find a better one), except saying something like "if you depart now, [n] outfit/s in your cargo will be sold as it is/ they are too large to fit in any of your ships' cargo hold, for a total of [credits] credits"

**Comment by tehhowch** [comment]
I'd rather add a "can fit in hold" check when buying an item to cargo. If buying that item would result in some item not packing, then a confirmation popup is displayed with the message and reason, and the warning icon is shown near the free/total cargo space indicator.

**Comment by petervdmeer** [comment]
Such a check would be very nice, but I would expect such check to also warn if the player tries to do something like putting 5 outfits of 26 tons each into 4 star barges.

**Comment by Sandwichs-del** [comment]
@tehhowch I like being able to temporarily over-fill the cargo hold (https://github.com/endless-sky/endless-sky/pull/5363), but a warning icon next to cargo space and and a through take-off check would be still nice.

**Comment by petervdmeer** [comment]
The main issue (of outfits getting sold without warning) has been addressed by [storing excess outfits in planetary storage](#7646) and by [providing proper warnings when outfits are to be sold](#7645).
I consider those solutions good enough to close this issue.
