### ISSUE TITLE
Illegal Cargo fined and confiscated twice

### ISSUE THREAD

**Issue by Person-93** [endless-sky/endless-sky#4488]
**Describe the bug**
I was carrying illegal drugs, I got the popup about being fined and the drugs confiscated. I jumped to another system. I was scanned again. I got another popup about being fined and having the drugs confiscated.

**To Reproduce**
1. Accept a mission to carry illegal drugs
2. Get scanned.
3. Let a day pass (not sure if this is necessary, but I am including it because that is what happened.
4. Get scanned again.

**Expected behavior**
I expect the drugs to only be confiscated once. How can they be confiscated twice? That doesn't seem to make much sense.

**System (please complete the following information):**
 - OS: Linux
 - Game Source: self-compiled
 - Version: 0.9.9

**Comment by jafdy** [comment]
Because you managed to keep some of them from being taken?
So what will be happening is that the mission cargo stays on your ship until you land, even if you have failed the mission for whatever reason. This allows you to be scanned and have the illegal item text come up more than once.

**Comment by Amazinite** [comment]
Are you sure the illegal goods were confiscated? Not all illegal jobs result in the confiscation of your goods if you’re fined, only a fine.

**Comment by Person-93** [comment]
@Amazinite @AdamKauffman the popup said that the goods were confiscated.

**Comment by Amazinite** [comment]
Being scanned with a stealth mission is causing the mission to fail (the destination marker and mission name grey out to show that they can't be completed now), but since https://github.com/endless-sky/endless-sky/issues/1938 is the case and missions don't get removed until landing, the cargo can be scanned multiple times.

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/c9b66ab7fcbdba7fe1cba00f99bfbd83f46a6e14.
