### ISSUE TITLE
Militia names are unused

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#449]
In names.txt, there are names listed for militia ships using the I.M.S. prefix, but in-game militia are all named F.S. something.

**Comment by thenerdfreak** [comment]
F.S stands for Free Ship I think. and yeah, I noticed this too

**Comment by endless-sky** [comment]
Fixed in 890b69a.

**Comment by endless-sky** [comment]
0.8.9 is now release, so I'm closing this.
