### ISSUE TITLE
MacOS 10.15 Catalina Support

### ISSUE THREAD

**Issue by kmdavis** [endless-sky/endless-sky#4498]
**Describe the bug**
Currently, if you launch the game on MacOS 10.15 (Beta), you get the following error:
> Unable to create config directory!

Both in a dialog, and also as the one and only line of output in errors.txt

**To Reproduce**
1. Install Endless-sky on Steam
2. Update OSX to 10.15
3. Launch Endless-sky from Steam

**Expected behavior**
The game should launch

**Screenshots**
<img width="426" alt="Screen Shot 2019-08-27 at 10 41 01 PM" src="https://user-images.githubusercontent.com/132806/63824152-c8b33b00-c91b-11e9-9380-499a1cfb6610.png">

**System (please complete the following information):**
 - OS: MacOS 10.15 Beta (19A536g) Catalina
 - Game Source: Steam
 - Version: 0.9.9

**Comment by kmdavis** [comment]
I can uninstall it, but I'm not sure I can RE-install it; Steam itself needs some TLC w.r.t. Catalina support; Store pages kinda... crash immediately after load
<img width="424" alt="Screen Shot 2019-08-28 at 10 32 11 PM" src="https://user-images.githubusercontent.com/132806/63908173-d16f4400-c9e3-11e9-9680-9360f700ea21.png">
But I agree that it's almost certainly a permissions issue; one new systemwide behavior I've noticed since updating is that I get prompted to grant permissions to do this and access that constantly.

**Comment by tehhowch** [comment]
Is ES the only game for which you have had these permissions issues? If Steam is having trouble with the new OS, I'm not surprised that things it installed also have trouble.

Are you willing to do a self-install? There are prebuilt binaries hosted by @MCOfficer (see the Steam forum for the link to nighties), and there is the trusty "compiled it myself" approach (see the developer readme for instructions). I'm curious if the permissions issues persist in these cases.

**Comment by Fzzr** [comment]
Steam was also a 32-bit app until recently, you might was to re-install it just to be 100% sure it's up to date.

**Comment by kmdavis** [comment]
Yeah, I had to reinstall Steam on Day 1; it couldn't even launch itself or self update

**Comment by kmdavis** [comment]
New Catalina Preview update today, and it fixed it. On launch of Endless Sky, STEAM asked for permissions to access by iCloud Drive, and the game launched successfully
