### ISSUE TITLE
Idea: Strafing

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#450]
a button that, instead of turning you, lets you strafe. AI support as well, could be useful for when you have your sights locked on a target, in which case strafing would make you circle the target in a consistent way.

**Comment by frameworld** [comment]
I would prefer a tractor-ray which pushes/pulls ships into formation (your other issue).

If you have these and ships facing different directions, strafing is possible too.

**Comment by endless-sky** [comment]
Strafing is already relatively easy - you just need to figure out the proper turning radius for your ship and approach your target so that you pass by it at that exact distance. You can even calculate what the proper distance is for a given speed, in pixels, using the centripetal acceleration equation: a = v^2 / r, so r = v^2 / a.

**Comment by jafdy** [comment]
Clearly endless (like me) can do physics equations in his head but I don't think that most people can do that. Although there is very little practical reason to build a ship that can thrust sideways so I think it would be best if we stick to forward thrust and occasionally some revers thrust.

**Comment by frameworld** [comment]
In Robocraft I built combat hovers that can fire **sidewards** just to get the ability to strafe.

**Comment by masterpierround** [comment]
There's no need to actually do the physics equation. For example, I know how much I have to slow down to take a turn in my car, purely from doing it over and over. I don't have to know all the numbers and exactly calculate my speed, I can judge it based on experience. In the same way, practice spinning around a planet or something (I did it while waiting for Korath Raiders to show up) and you will eventually master the art of turning around a target with precision.

**Comment by endless-sky** [comment]
Because of how inertia works in the game, strafing is already relatively easy. And, sideways thrusters would presumably have to use up some of your engine space, thus making your ship less maneuverable in other ways, so I don't think they would be very popular.
