### ISSUE TITLE
Idea: Air Brake

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#451]
a key that lets you come to a complete stop by applying just enough force to counteract your current inertia. AI support as well. Would help with keeping formations for attack and defense strategies.

**Comment by frameworld** [comment]
I would prefer a tractor-ray which pushes/pulls ships into formation.

If you have these and ships facing different directions, strafing is possible too (your other issue).

**Comment by endless-sky** [comment]
Reverse thrusters basically do this.

**Comment by frameworld** [comment]
Not really. There is no big version of them for bigger ships. You also need a lot of steering which makes your ships slow.

**Comment by thenerdfreak** [comment]
Reverse thrusters only cancel out forward momentum, I'm talking about something that would let you and your escorts come to a 100% complete stop (so you and your escorts don't just float off into space)

**Comment by anonybosch** [comment]
@thenerdfreak  The Gather command (G) does this pretty effectively.

**Comment by jafdy** [comment]
Yes I can see the use of that but it would be more useful as a fleet command than an outfit. Also it can't be an air brake as there is no air in space.

**Comment by frameworld** [comment]
Sun-wind-brake :p 
Space-trash/particles brake ^^

**Comment by thenerdfreak** [comment]
I know there is no air but that is what it would be compared to

**Comment by thenerdfreak** [comment]
and the G Gather function doesn't allow you to keep a formation, it just makes the ships flop around near your ship: If i wanted to set up an ambush on the other side of a system by leading a larger ship to my waiting ships, it currently would be impossible without modding in the game

**Comment by Wrzlprnft** [comment]
how about H holding position?

**Comment by jafdy** [comment]
We have that but it is more like an 'almost stop but keep drifting' button.

**Comment by thenerdfreak** [comment]
yeah ^ as in, ships float away from their original position

**Comment by omagasohe** [comment]
expecially when leaving the planet, big o'l expanding ring of drifting ships, each one on it's own course.

**Comment by endless-sky** [comment]
It's already possible to (almost) stop your ship by just thrusting in the opposite direction to your current heading. I don't see a need for a separate braking function on top of that - for your own ship, it's easy enough to hold one position actively, and the "hold position" for other ships will eventually be adjusted to allow active correction when they drift away, as well.
