### ISSUE TITLE
Heat, Energy, and Fuel drain attributes for Resistance

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4517]
**Is your feature request related to a problem? Please describe.**
It was described in #2719 how the current resistance attributes are very similar to hull repair and shield generation in how they allow for a ship to shrug off a small amount of damage, but after the damage has reached a certain threshold then it will start having an effect. It's notable though how currently the resistance outfits are lacking in certain properties, such as the ability to alter the heat, energy, and fuel of the ship when active.

**Related Issue Links**
#2719

**Describe the solution you'd like**
Add `ion resistance heat`, `ion resistance energy`, `ion resistance fuel`, and similar attributes for disruption and slowing resistance.

**Additional context**
It's notable that the current implementation of the resistance attributes does NOT check to see if the ship is disabled before applying them. This seems to imply that resistance attributes are some sort of ability intrinsic to the hull or shields of the ship that doesn't require any energy to power. 

https://github.com/endless-sky/endless-sky/blob/e594c2e88b5586533af21f03086755d98a4f5dc2/source/Ship.cpp#L1626-L1631

Adding the suggested attributes would mean that a ship needs to not be disabled in order for them to be active, but I can see an argument for still having some way for resistance to apply to a disabled ship. 

In order to both keep the current mechanic and implement the suggested mechanic, what if resistance that doesn't drain energy, heat, or fuel will apply if disabled, but if the resistance comes with any of those attributes, it doesn't work when disabled? The one issue with this would be if a ship comes standard with resistance that has no drain, but then the player installs an outfit with resistance and drain, meaning the ship's stock resistance would no longer work when disabled, so it may just be better for resistance to never work when disabled.

**Comment by Zitchas** [comment]
Would it be possible to have values as well as an attribute, so the values act as per normal, and the attribute is limited to a few states. 

Ex. 
0 = always disabled (this ship or any ship with this outfit can never have this type of resistance, 
1 = this resistance is always active regardless of whether the ship is active or disabled, 
2 = this resistance is only active when the ship is active, 
3 = this resistance is only active while the ship is disabled, etc. 

I could see having a second or third range of these variables that specify that said outfit/ship will/will never override said attribute when another source of said resistance is provided. Basically, a priority system for determining which has priority.

**Comment by Amazinite** [comment]
>I could see having a second or third range of these variables that specify that said outfit/ship will/will never override said attribute when another source of said resistance is provided. Basically, a priority system for determining which has priority.

It seems to me that this would require a big change in the code, as right now attributes don't care what outfit they're coming from, the attributes just get pooled together then applied to the ship.

**Comment by Zitchas** [comment]
I wasn't so much thinking for the resistance itself, but more whether or not they work while disabled or active (or both, or neither).
