### ISSUE TITLE
Moving crew members to ship (feature request)

### ISSUE THREAD

**Issue by tmoftdead** [endless-sky/endless-sky#4518]
**Is your feature request related to a problem? Please describe.**
Not a problem, but if another ship of mine has extra crew, why dont they share the crew? This could improve boarding too.

**Related Issue Links**
None.

**Describe the solution **
Make the other ships belonging to the player share crew.

**Describe alternatives you've considered**
This could be dismissed or crew can be shared.

**Additional context**
For example : Ship A has 10 required crew and has 4 crew left. Maybe Ship B (owned escort ship) gives the extra 6 crew if it has them so the ship can move or continue trying to capture the ship it lost its crew to.

**Comment by Amazinite** [comment]
This and https://github.com/endless-sky/endless-sky/issues/2185 lead to the same issues. Allowing the transfer of crew trivializes the capture mechanics.

**Comment by tmoftdead** [comment]
As I said, this may be dismissed after the new remnant void sprite missions can tear down even the largest of ship crews. I had a need to adress this because you can add crew to escort ships but then can do nothing with it.

**Comment by jafdy** [comment]
Wait a moment. You can add crew to escorts now?

**Comment by tmoftdead** [comment]
oh, you can add crew to the original ship and switch to another ship from the fleet page.

**Comment by tehhowch** [comment]
And do these extra escort crewmembers follow you into space?

**Comment by quyykk** [comment]
As mentioned by derpy, this trivializes the current boarding mechanics.
