### ISSUE TITLE
An idea which could replace minimaps

### ISSUE THREAD

**Issue by frameworld** [endless-sky/endless-sky#452]
![mini-map](https://cloud.githubusercontent.com/assets/875554/11765529/911c5c4e-a15b-11e5-9a6f-28012c8260a1.jpg)
Left in the picture is what we have now.
* main window
* small mini-map

I have never seen any game that reduces the main-window size and draws the mini-map around it (as seen Right in the picture)

Imagine 8 points which mark the corners of the mini-map and visible area ON the mini-map.
Then you
* stretch the outer 4 points to the window edges
* vertically or horizontally shrink the triangles to magnify the inner area (visible area) defined by the inner 4 points
* or use h|v shrink the 4 border rectangles and h+v shrink the edges.

**Comment by anonybosch** [comment]
What mini-map?

**Comment by endless-sky** [comment]
What would happen when a ship is very close to the player? Wouldn't it jump around the edge of the screen very quickly? Also, the most important thing the radar communicates is distance, not direction, and distance would be much harder to judge if the radar were stretched out like that.

**Comment by frameworld** [comment]
For me, direction is also a key point.
And distance is easy to guess if you see the two borders (v or h) at 100% radar distance.

Perhaps it's not a good idea for everybody, but I miss it (implemented it in my own game that had similar thrust-mechanisms for a Shellcore-Command-style game in JS instead of Flash before I discovered your project).

**Comment by Pointedstick** [comment]
I like the current minimap just fine.

**Comment by DingusShingleton** [comment]
Although I would love it if the ship icon in the targeting HUD would rotate based on the direction your target is facing.

**Comment by endless-sky** [comment]
@DingusShingleton, I like that idea. You should post it as a separate
feature request (i.e. as a new issue).

**Comment by endless-sky** [comment]
It doesn't sound like this idea has much support, so I'm closing it.

**Comment by DingusShingleton** [comment]
Oh wow, I totally missed you response @endless-sky. Thanks for including it anyway! I saw it in the patch notes and was like, wait a minute... Cool!
