### ISSUE TITLE
Planet+Mission UI improvement

### ISSUE THREAD

**Issue by frameworld** [endless-sky/endless-sky#453]
Planets and missions lack personality - they need images, cheap, randomized images.

Would it be difficult to make some Person-images variable? alter
* hair colours
* cloth colours
* position of dark skin-cells
* accessories
* background/foreground hair-style
* face-style, stature
* size : some planets would have smaller peoples.
* T-shirts with messages.

And for planets:
* Add a few peoples to the space-port. Show space-port next to the landscape.

I am pretty sure that if the basic system is out with an example, soon peoples (including me, as long as the learning-curve is not too step) will make variations.

What needs to be supported for this to be possible:
* Defined, named attachment-points on parts (similar as with turrets)
 * where two pieces will match together.
 * and a default set of names to keep it consistent over mods and help peoples with english not as their native language.

Some pieces would either need a standard-scale as orientation for their design or multiple attachment parts.
* goggles: eye←→glass.middle x2, ear←→frame.end x2
* throat: may need 4 points and a beezer-curve to scale it between body and head (pixel-sheering).

But i would consider this advanced and not strictly necessary.

**Comment by anonybosch** [comment]
Huh? You suggesting adding cartoon characters to the game? We're still trying to get ambient background sounds added to the various panels.

**Comment by jafdy** [comment]
I like the personality as it is. Every planet already has its own personalty you just have to read the text and imagine it.

**Comment by frameworld** [comment]
@anonybosch 
Not cartoon characters.
Characters in Latest-Final-Fantasy quality, but just 2D and not animated in that quality if animated at all.
And I am better at drawing than at making good music (music for a game, not for myself)

@jafdy 
Text alone is boring. Boring for some at least.

**Comment by jafdy** [comment]
Yes and so is a 2D space.

**Comment by frameworld** [comment]
2D space is not as interesting, but easier to handle and faster to render.
→ It is not about boring or not.

I think my suggestion requires a different reasoning

**Comment by anonybosch** [comment]
The beauty of the simplicity of the game is that it gives free reign to your imagination.

**Comment by endless-sky** [comment]
I do hope to eventually have "portrait" pictures for all the main
characters in the story line. But, as with the landscape photos, I think
that just using real photos of real people would be simpler and better than
trying to create artificial faces. (The only complication being collecting
model releases from each person, and figuring out how that affects the
licensing of the art assets.)

**Comment by anonybosch** [comment]
Please don't, Michael. It would diminish the mysteries of just who these people are. Portraits would forever reduce the characters "someone's" idea/ideal. 

If you want to add a bit more pizzazz visually, why not add images of plausible spaceports when the Spaceport button is used?

**Comment by frameworld** [comment]
@anonybosch : how would you like silhouettes of characters?

I think once the story-line has multiple branches, portraits are also good, but may lack custom emotions for each in-between-choices-paragraph.

Just avoid special accessories like big ear-rings, cybernetic implants, etc (not everyone's taste).
* Keep it natural with 1-2 personal details which don't dominate the portrait.
* Keep accessories limited to a selected few.

The whole point in this request is to have situations more recognizable, not to define the characters in-and-out.

**Comment by anonybosch** [comment]
@frameworld  I suppose silhouettes would add something, while still leaving a lot for the player's imagination. More background somehow worked into the conversations would flesh out the characters too. e.g. Someone at the forum called Katya an old bag. I took umbrage and extemporaneously gave Katya some back story.
<quote>
Notice that those other people aren't around to tell the tale? Katya Reynolds is neither old nor a bag. She majored in anthropology before her political awakening, and then went to become one of the youngest tenured professors in Civics and Economics in recent memory. She keeps quite fit, mountain climbing when she can find the time, and long-distance ocean swimming. It's been rumored that while on a summer dig in Belarus on Earth, she discovered a cache of Spetsnaz training manuals. Whether there's any truth to that, she doesn't share but with close personal friends.

Kat, (we're quite close,) is proficient in not only karate, but ju-jitsu and tai kwon do. And she gives a mean shiatsu massage. (Like I said, we're quite close.)

You're lucky she had a use for you or she'd have cleaned your clock.
</quote> 

Notice that this K some personality without adding a body of face. <i>How something like this could be incorporated into the game, I have no idea.</i> But details like these still let the player imagine his/her "own" remarkable woman.

**Comment by frameworld** [comment]
Was there not a mission/dialogue where it said Katya optimized the production management of FW-Dreadnoughts? If I recall correctly, anthropology is not needed.

We can easily pull-out serious AIs technology.

Attribute : sub-attributes to increase with Attribute * factor and can be measured in days or hours.
* private : personalityPriv 1 d, sport 4 h ...
* public : personalityPub 1 d, job 8 h ...
* meeting : personalityPriv 1 h, sport 1 h ...

Code-hooks:
* meeting increase whenever you meet one.
* private increases when you give "friendly" answers or the meeting is private
* public increases when you give "polite" answers or the meeting is serious

Circular dependencies are resolved by:
follow-connection on-change and values change if a higher percentage is applied (overwrite lower percentages).
* This comes to an end in (less than n*m) n=key-words(private:*), m=average-sub-words(*:sport,…).

Each knowledge has dependencies
* private
 * defaults meeting, …
 * requires 10 h – from total
 * uses 1 h – used up time, doesn't subtract from total
* something-else
 * requires 5 h

Note: Knowledge with different requirements (private, something-else) may unlock earlier than others and consume private time. But only if you have something-else.
* This may alter in which order you access knowledge
* Or if you access it at all (e.g: if private time has a limit you can't go over because somebody meets their love or dies)
* By using second dependencies or not and by balancing them, you can alter how much this matters.

And because you access different knowledge, other things may change as well.
* Not only knowledge is important, but the order in which it is accessed.

**Comment by jafdy** [comment]
Text descriptions are good as it makes the game read more like a book. If you start putting portraits in then people will stop imagining as much and will expect more and more pictures every were. Just focus on improving existing graphics for now.
