### ISSUE TITLE
Add new weapon attributes

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4532]
**Please describe your feature request.**
This request is to add new weapon attributes that allow the creation of more different types of weapons.

New attributes that damage the firing ship:
- `firing hull` The amount of hull lost (by the firing ship) when firing this weapon.
- `firing shields` The amount of shield lost (by the firing ship) when firing this weapon
- `firing ion` The amount of ionisation that happens (on the firing ship) when firing this weapon
- `firing slowing` The amount of slowing that happens (on the firing ship) when firing this weapon
- `firing disruption` The amount of shield disruption that happens (on the firing ship) when firing this weapon

Those attributes allow for stronger (super) weapons that have a downside of damage to the firing ship.

New attributes that potentially disable the firing ship:
- `firing drain` Allow the weapon to fire if insufficient energy is available. This variable sets the maximum negative amount of energy allowed when firing this weapon.
This attribute would allow for the creation of super-weapons that can be fired, but that will disable the ship for some time after firing because energy would need to be recharged before propulsion, shields and non-draining weapons would work again.
Firing drains from all weapons get added, so if 4 instances of a draining weapon are installed, then the maximum amount of drain is 4 times as big as listed for a single weapon.

New attributes to disable enemy ships:
- `energy damage` The amount of energy removed from the target ship when hit. This differs from ionization damage in that it removes stored energy without the ionisation effect.

**Related Issue Links**
There are quite some changes to weapons currently ongoing (disabling weapon attributes, damage resistance), but I didn't see any effort to implement the attributes listed here.

**Comment by Amazinite** [comment]
> New attributes that damage the firing ship:

With all my recent PRs I knew it was only a matter of time before someone asked for this.

> New attributes that potentially disable the firing ship:

It seems to me that this same effect could be gained with a high firing ionization. 

> `energy damage` The amount of energy removed from the target ship when hit. This differs from ionization damage in that it removes stored energy.

Ionization already removes stored energy, it just doesn't take a large chunk at once. (Just threw my flagship into an Unfettered system with no shields, no weapons, and didn't move while taking ion cannon fire to make sure.)

**Comment by petervdmeer** [comment]
> With all my recent PRs I knew it was only a matter of time before someone asked for this.

I had this list of new attributes already on my computer for a longer time (as part of a different PR), but your recent updates were indeed a trigger to create this change request already.

**Comment by Amazinite** [comment]
For the record, I'm all for this issue (and I'd even say that `energy damage` is an alright addition as it'd still differ from ionization in that it's an instant, one time drain of energy as opposed to a sap of energy over time as it decays).

But, when I was working on #4525, which is something I recall being asked about on the Steam forums a number of times (i.e. "can you multiply stats by a number instead of just adding and subtracting from them?" usually w.r.t. shield generation), one of the thing I thought of was "this is opening Pandora's Box." That is to say, where do we *not* create such a stat. Why not give nearly every stat a modifier of some sort? 

Applying that thought to this issue, if we add firing ionization, firing slowing, etc., then what about shield ionization, hull slowing, etc.? I'm fine with having these stats stop at just firing, as with being fine with stopping multipliers at just shields and hull, but what's the argument against creating similar stats wherever possible other than sanity?

**Comment by petervdmeer** [comment]
From a code-point of view we could try to generalize the instant cost/damage items:
- if a weapon-impact can cause ion damage, then firing a weapon, shield-recharging, hull-repair and propulsion can also cause ion damage.
- if a weapon-impact can cause cloak disruption (#4404), then firing a weapon, shield-recharging, hull-repair and propulsion can also cause cloak disruption.
- if an outfit can cause cooling, then a weapon impact can also cause cooling (we might want to generalize/combine this with heat/heating)

The code would then apply a damage/cost to ships for anything that happens (regardless if it is weapon firing, weapon impact, hull-repair or propulsion).
The generalized code should be quite readable and maintainable (if we do it right), but game performance might become an issue if we have too many stats to track.

Not all combinations will make sense (for example the "disabling" damage from #3599 doesn't make much sense for shield-recharge, hull-repair or propulsion), but we would also get a lot of new sensible combinations like:
- huge thrusters (Korath Stellar?) giving a small amount of hull damage when they are used.
- hull repair systems doing some damage to shields.
- super thruster that generate a huge amount of thrust, but also cause slowing damage which limits the amount of time the maximum thrust/speed is possible (similar to the Gattling Gun, a lot of damage, but not continuously)

I don't know enough yet about the multipliers to comment on them.

**Comment by Amazinite** [comment]
Looks like this one should be closed.
