### ISSUE TITLE
String interpolation for phrases in hail messages

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#4533]
### Background

The `hails.txt` file is structured in such a way that one can combine words and phrases for randomly generated strings. For instance, we might have this:

```
phrase "planet"
 	word
 	 	"Earth"
 	 	"Luna"
 	 	"Mars"

phrase "friendly civilian"
 	word
 	 	"I'm going to "
 	 	"Looking forward to visiting "
 	 	"Heading over to "
 	phrase
 	 	"planet"
 	word
 	 	" after I finish this job."
 	 	" once I raise enough credits."
 	 	"!"
```

And this will generate hail messages like

> I'm going to Earth after I finish this job.
> Looking forward to visiting Luna once I raise enough credits.
> Heading over to Mars!

### Problem

Consider [this section](https://github.com/endless-sky/endless-sky/blob/eee43a1b54fba48d9777168d484b9a0732beebc1/data/hails.txt#L1910) of `hails.txt`:

 	word
		"buy drugs from"
		"sell drugs to"
		"sell slaves to"

Say I created a new phrase called `contraband` that included both "slaves" and "drugs". Because I need to say either "buy from" or "sell to", I can't use that new phrase in this situation. For instance, if I had

 	word
		"buy "
		"sell "
 	phrase
		"contraband"
	word
		" from"
		" to"

…then I might wind up with nonsensical phrases like

> buy drugs to
> sell slaves from

### Feature Request

I would like to be able to reference a phrase from within a word through [string interpolation](https://en.wikipedia.org/wiki/String_interpolation) (or something with equivalent functionality). The syntax might look like this:

 	word
		"buy $contraband from"
		"sell $contraband to"

…where `$contraband` is a reference to the phrase with the same name. This would ensure that we can provide more variety of hail messages for complex phrases like this, and avoid artificially limiting what can be said. 

This would also allow for phrases to be optional. Consider this section [this one](https://github.com/endless-sky/endless-sky/blob/eee43a1b54fba48d9777168d484b9a0732beebc1/data/hails.txt#L1796):

	word
		"selling drugs"
		"selling slaves"
		"plundering merchants"
		"fetching bounties"

With string interpolation, this could become:

 	word
		"buying $contraband"
		"selling $contraband"
		"plundering merchants"
		"fetching bounties"

Thus giving greater variety to the type of messages that can be generated.

### Considerations

We will need to decide what to do if a phrase is referenced that doesn't exist. I presume the solution would be to either display the variable name in the message, or replace it with empty string.

To my knowledge, it's not possible to reference player names or similar variables in hail messages. Implementing this feature should be done in such a way as to allow for that functionality in the future.

**Comment by tehhowch** [comment]
I would tend towards a JavaScript template literal--`"buy ${contraband} from"`--rather than the bare `$` as it is less likely to be an accidental sequence, but otherwise it's a seemingly good approach to resolving the branching paths that occasionally occur.

Certain player-specific substitutions are possible, or at least can be made possible, by using the mission-style substitution syntax `<keyword>`. These runtime substitutions would only occur after the rest of the phrase was generated. (I don't recall without checking if there is a call to Format::Substitute in the random hail generation method.)

**Comment by jafdy** [comment]
```
phrase buy
    word
        "buy"
    phrase
        contraband
    word
        "from"
```
would also work (also for the other use cases you named), although it is a bit clunky.

**Comment by oo13** [comment]
FYI.
In [this comment](https://github.com/endless-sky/endless-sky/issues/558#issuecomment-487903300), I made a suggestion that phrase nodes should have the capability of handling a relationship of phrases and words.

This proposal is easier to understand than my suggestion (2), but needs to create a new phrase "sinister names or bad outcomes".
```
phrase "sinister names or bad outcomes"
	phrase
		"sinister names"
		"bad outcomes"

phrase pirate
	word
		"${pirate adjectives that don't work as titles} ${sinister names or bad outcomes}"
		"${pirate adjectives that work as titles} ${sinister names or bad outcomes}"
		"${sinister names or bad outcomes} ${pirate adjectives that don't work before singular nouns}
```

Of course, we can implement both functions.

**Comment by Thunderforge** [comment]
> `I would tend towards a JavaScript template literal--`"buy ${contraband} from"`--rather than the bare `$` as it is less likely to be an accidental sequence

@tehhowch I'd be fine with that.

> ```
> phrase buy
>     word
>         "buy"
>     phrase
>         contraband
>     word
>         "from"
> ```
> 
> 
> would also work (also for the other use cases you named), although it is ~a bit~ very clunky.

@jafdy It does work for `buy X from`, but not for `sell X to`. To get both to work you'd have to duplicate the block.

```
phrase buy
    word
        "buy"
    phrase
        contraband
    word
        "from"
phrase sell
    word
        "sell"
    phrase
        contraband
    word
        "to"
```
…which is *even more* clunky! With my proposal, we could vastly simplify this.

```
phrase "buy and sell"
    word
        "buy ${contraband} from"
        "sell ${contraband} to"
```

@oo13 Your proposal could work, although I'd be concerned about any accidental combinations. If someone created a phrase `friendly` and another called `pirates`, then `friendly pirates` (i.e. hails given from members of the pirate faction that are non-hostile) would not behave as intended. Still, if there's value, I could see it being worth implemented, although implementing this feature would mitigate the need for it.

```
phrase pirate
	word
		"${pirate adjectives that don't work as titles} ${sinister names}"
		"${pirate adjectives that don't work as titles} ${bad outcomes}"
		"${pirate adjectives that work as titles} ${sinister names}"
		"${pirate adjectives that work as titles} ${bad outcomes}"
		"${sinister names} ${pirate adjectives that don't work before singular nouns}
		"${bad outcomes} ${pirate adjectives that don't work before singular nouns}
```

**Comment by jafdy** [comment]
I was simply stating that it could be done in the current code, not that that was in any way a nice way of doing it, merely that it could be done. Why? Because your FR made it sound like it couldn't be done, you should have stated that this approach does work to begin with. 
Please don't respond, there was no need for a response to my last comment.

**Comment by tehhowch** [comment]
You can now interpolate within a `word` child node using `${phrase name}` syntax, and you can globally replace within the current working phrase text with a `replace` node:

```
  word
    "buying ${contraband} from"
    "selling ${drugs} to"
  replace
    "law enforcement" "narcs"
  word
    ...
```

The replacement operation would be applied only to the generated text that occurred before the replace node.

**Comment by tehhowch** [comment]
Closing as I consider the implementation of player variable substitution a separate issue (one which can be performed by the caller of `Phrase::Get`
