### ISSUE TITLE
Suggestion: allow repeatable routes

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#454]
This is a feature I believe was in the escape velocity games, when you shift clicked on your system of origin after drawing a travel path, it would automatically repeat itself. That is to say, if you kept jumping you would repeatedly traverse the path.  This is of course was extremely useful if you were conducting trade over the same route repeatedly.

I'm not sure of the way that escape velocity went about it was the best way, perhaps we could have a button to "repeat route" instead.

**Comment by frameworld** [comment]
A → B
shift (B → A)
shift (A → B)
shift (B → A)
shift (A → B)

**Comment by Wrzlprnft** [comment]
mmh how do you want to connect this to land, trade, and fllet behaviour? because if the fleet just follows the flagship, which might be faster, they could never reach the destination

**Comment by frameworld** [comment]
Good point.
I just told about the best current available tool we have.

**Comment by endless-sky** [comment]
I think shift-clicking is already good enough for this - it lets you queue up several repeats of the route all at once. (Plus, repeating a route over and over will become much less common once there's a dynamic economy that responds to players with huge cargo fleets.)
