### ISSUE TITLE
Use the new steam assets

### ISSUE THREAD

**Issue by ghost** [endless-sky/endless-sky#4541]
Currently the steam box art looks like this on the new design
![image](https://user-images.githubusercontent.com/7173984/65080157-ac307e80-d96e-11e9-8ded-8099a385b33b.png)
the box art on youtube looks like this:
![image](https://user-images.githubusercontent.com/7173984/65080405-3d075a00-d96f-11e9-9dec-c671d3f7116b.png)

**Comment by Amazinite** [comment]
This was done with today's release. 
![image](https://user-images.githubusercontent.com/17688683/75190656-c1c88200-571e-11ea-924e-8232e3c4ced1.png)
