### ISSUE TITLE
Bug on mission alien invasion

### ISSUE THREAD

**Issue by bayukael** [endless-sky/endless-sky#4552]
[Kael Lewis.txt](https://github.com/endless-sky/endless-sky/files/3653567/Kael.Lewis.txt)

I experienced a bug when doing the mission "Defend Oblivion" from pug. My fleet won't help me. They don't open fire at the pug ships. Only the ships that I own that help me firing the pugs down.

**Comment by Amazinite** [comment]
Should already be fixed by 0f734f9.
