### ISSUE TITLE
OS X Steam 0.9.10 release broken

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#4558]
People on OS X using Steam, opted into the beta branch have had an issue since the 0.9.10 update was pushed. After updating, upon attempting to start the game, users are presented with the following error:
`An error occurred while updating Endless Sky (missing executable) :
/Users/<user>/Library/Application Support/Steam/steamapps/Common/Endless Sky/EndlessSky.app/Contents/MacOS/EndlessSky`
(Discovered by @Hyugat
@endless-sky

**Comment by Amazinite** [comment]
Reports of this from Steam. https://steamcommunity.com/app/404410/discussions/1/1631916406858106034/

**Comment by warp-core** [comment]
Update: https://steamcommunity.com/app/404410/discussions/0/1631916406861002350/?tscn=1569848385#c1631916406864113730
Apparently, the name that Steam has for the executable to run to start the game is not the same as the name of the executable that is there.
It is attempting to start `EndlessSky.app` when the filename is `Endless Sky.app`.

**Comment by Fzzr** [comment]
This appears to be fixed, the executable name in the steam version of Endless Sky is now `EndlessSky.app` again.
