### ISSUE TITLE
Have missiles clear their targets if the target is captured and is no longer an enemy

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#456]
I jumped into a system with pirates in it and took my fight to the edge of the system like a good pirate hunter. The navy tried to pursue but was too slow. I disabled the pirate captured the leviathan but before I could the navy fired some torpedoes. On my way to capture another ship, the leviathan was disabled.

**Comment by endless-sky** [comment]
I'm not sure if this is really worth fixing, or if it is just part of the risks you take on when capturing a ship. I suppose the fix would be to have missiles check their targets regularly to make sure the target is still an enemy.

**Comment by endless-sky** [comment]
This is fixed in commit baa091e. Missiles will now clear their target if the target is captured by a different government.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
