### ISSUE TITLE
Add preference to disable "on visit" for repeated missions

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#4565]
**Is your feature request related to a problem? Please describe.**
Seems #4315 and #4342 may have overlooked some UX behaviors: https://steamcommunity.com/app/404410/discussions/0/1631916887483823523/

**Related Issue Links**
Haven't searched for the comment itself but I believe MZ had mentioned that many missions did not have on visit dialogs to avoid being spammy.

**Describe the solution you'd like**
We should add a preference that prevents displaying the "on visit" dialog for a mission you have completed before. As an implementation note, we can reference the mission name in the player's `Conditions` map, and look at the number done, the number active, or even write a new condition, e.g. `"<name>: visit message shown"`

**Describe alternatives you've considered**
 - We could revert these two PRs but that's overkill 😉

These would reduce the annoyance but not eliminate it:
 - We could define a "stacked visit message" and show that when more than one mission having the same identifier has a visit message to display, rather than each mission's message
 - We could implement a "job offer filter" that reduces the offer chances of missions having the same identifier and destination when a given number of that mission are already active (e.g. if you have 5+ of the same mission with the same destination, your offer chance for another one exactly like it decreases 10% for each extra active mission. So at 5 of the same, you have `regular*.9` chance of getting another, then at 6 of the same kind it becomes `regular*.9*.9`, and so on).

**Comment by Amazinite** [comment]
I'd say do something akin to the `You failed X other mission(s)` from #4526, having a message that reads  something like `You have X other incomplete mission(s) at this destination.`

**Comment by tehhowch** [comment]
Closing as the "stacked visit message" was implemented in #4592, which should effectively eliminate the bad UX. Reducing the offer rate for missions the player has a lot of is not a bad idea, but is fundamentally one that can be done in its own issue + PR.
