### ISSUE TITLE
Jump drive jumps classified as hyperspace

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#457]
The top navigation pane still says "Hyperspace:" when you're using the Jump Drive.

**Comment by Wrzlprnft** [comment]
Isn't the jump drive still hyperspace but just not along the Hyperspace Links?

**Comment by wkoot** [comment]
Yeah I guess so. But the animation is very different. Otherwise something like "Hyperspace Jump" ?

**Comment by frameworld** [comment]
So much hype about it :D 
Scram-Drive neither has "hyper" in it's name (only in it's description).

**Comment by endless-sky** [comment]
It's all hyperspace travel, just different ways of accomplishing it. I don't think changing the label when the player has a jump drive would really add anything to the game.
