### ISSUE TITLE
Random crashes when flying around in human space

### ISSUE THREAD

**Issue by The-Ionizer** [endless-sky/endless-sky#4575]
**Describe the bug**
Endless Sky sometimes crashes when I'm flying around in human space, usually during a hyperspace jump, but sometimes shortly after the jump is completed.

**To Reproduce**
1. Jump around in human space.
2. Hope for the best/worst, I havn't found a way to consistently reproduce the bug.

**Expected behavior**
No sudden crashes when jumping between systems.

**System (please complete the following information):**
 - OS: Windows 10 Education, version 1809 build 17763.437
 - Game Source: Nightly, through MCO's .bat script for updating to latest version, created by the script at https://gist.githubusercontent.com/MCOfficer/96f02a3e91c043d25ed74b3d26cb2d61/raw/InstallNightly.bat
 - Version: encountered the bug both after updating for commit 0b396dd7cb670146670777194aa54df018461420 and for commit c6ce77b0184a3aa6331c4d25b029dc7913830b3b

**Link to save file**
[first last.zip](https://github.com/endless-sky/endless-sky/files/3693477/first.last.zip)

**Additional context**
I have only encountered the bug when using the Hyperdrive, haven't tested if there is any difference when using a Scram Drive or Jumpdrive.
I didn't get any error messages or a popup about Windows trying to find the cause of the crash, the effect of the bug does is Endless Sky freezing and closing itself.

**Comment by tehhowch** [comment]
I don't think that script compiles the game. Looks like you got build # 210, which does not include the fix I pushed earlier.

**Comment by tehhowch** [comment]
The latest build from an hour ago includes the fix I pushed earlier today. Please let us know if that resolved the issue.

**Comment by The-Ionizer** [comment]
I've jumped around for about an hour with the latest build, and I haven't encountered the bug again, so the problem seems to be resolved
