### ISSUE TITLE
The Mule is way too good.

### ISSUE THREAD

**Issue by Hyugat** [endless-sky/endless-sky#4579]
Issue #1598 mentions how the Mule is a bit too good, however, seeing as how that was 3 years ago, I think it's worth readdressing.

The Mule is just too good compared to the other medium warships and has not enough disadvantages to outweigh its massive advantages. It is a jack of all trades, but not a master of none as one should be. 

The Mule has: the most cargo out of any human medium warship, the **most bunks** among any human medium warship aside from the frigate (which requires a license), a relatively low amount of required crew, less health than only the bastion and frigate (one requires a license, the other has large crew costs and moves at a snail's pace), tied with the osprey for most fuel, and comes with a ramscoop, and the **highest weapons space of any human medium warship**.  So, the mule is the champion of: capturing, cargo, distance, and weaponry, and fails in no category at all. 

This is a big problem for game balance. I and others on the Discord have seen the blatant problems with this ship. Sure, it's more expensive, but not by a significant enough margin to warrant all of its overwhelming advantages.

I propose we find ways to nerf the mule, and the ways I suggest we first go about doing that are to nerf the weapons space, and to up the crew requirement. If that's not enough, we can reduce the amount of bunks as well. A nerf to the shielding or cargo may also be warranted, but my two first proposed changes are in my opinion, the most important. 

I find it ridiculous that this ship can be the best in weapons, and the best in so many other categories, and is a ship that gives the player no reason NOT to use it, yet it still sits in the same spot in the game. Sure it's slightly more expensive, but the price difference between it and, say, a balanced ship like the Corvette, is not nearly enough. Do-everything ships should be average in all categories, or have a clear weakness, this ship has none of those traits.

**Comment by MCOfficer** [comment]
This is the Baccy all over again, isn't it?

**Comment by Zitchas** [comment]
I think much of the problem may stem from the fact that we have very few jack-of-all-trades ships, and the two pre-eminent ones (mule and baccy) are more like "master-of-all-trades." If there were a variety of them to pick from, great. But with only one medium and one heavy, (and none in the alien and/or higher tiers) they just feel too good. Like picking anything else is just making the game harder for ourselves.

**Comment by Hyugat** [comment]
The Bactrian requires a license and an extensive questline to be completed, the Mule does not.

**Comment by MCOfficer** [comment]
> 
> 
> The Bactrian requires a license and an extensive questline to be completed, the Mule does not.

i was referring to the baccy's extensive history of OP-ness, which was only solved through adding that license.

anyways, back on topic. since i don't see the mule getting a license as well, some slighter nerfs might go a long way.

**Comment by Hyugat** [comment]
Just another thing to note, in terms of outfit space, the mule is tied with the osprey and roost for third best out of the standard human ships (450). It is only eclipsed by the bastion and skein, which have notable weaknesses to balance them out. It is also among the better ships in terms of engine space.

**Comment by tukoz** [comment]
I'd like to add a feedback if possible. For I find the Mule is a good transport ship that can withstand a few hits before going bye bye.  
But in 2.5k hours IG each times I used the Mule as a flagship, I quickly reverted to either the Corvette or the Star Queen: the Corvette has a much higher life expectancy (vs Mule's top speed of 500 / 50 with atomic engines) and similar crew size; the Star Queen triple crew number allows for a much bigger captures rate (and bigger ship size). I've found my 4 turrets Mules die to pirates' Levis', Falcons, Firebirds, Corvettes, and every Marauder around way too often to do otherwise.

How much I affectionate the Mule, replacing them with better transport and escorts is one of my top priorities as soon as I get access to a jump drive.

**Comment by Amazinite** [comment]
#4581 knocked the Mule down quite a bit and brought up the Bastion as somewhat of a combat replacement. The Mule now boasts decent weapon space and outfit space, the highest cargo space among the medium warships, and considerable bunk space, but it isn't tied at best or way better than the next best in so many measures now.
