### ISSUE TITLE
Ships stuck in a loop after failing to go through wormhole after wanderer Eye mission

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#4582]
**Describe the bug**
Most of my ships are bugged to be following each other back and forth in Sko'Karak, I am unable to break them from this trance, parking and unparking doesn't work, g, h, quitting game, etc doesn't work. They are able to be "b" boarded but it doesn't do anything. Literally most of my fleet unrecoverable

**To Reproduce**
1. Go to Sko'Karak (or likely any wormhole)
2. Attempt to go through the wormhole while some escorts are off screen
3. escorts on screen will continue as normal
4. Escorts off screen permanently stuck

**Expected behavior**
all escorts to eventually make it through the wormhole

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 Home 10.0.18362 Build 18362
 - Game Source: Steam Beta
 - Version: 9.10(beta)

**Link to save file**
[Jason Clark.txt](https://github.com/endless-sky/endless-sky/files/3698497/Jason.Clark.txt)

**Additional context**
Any way to break them out of this trance? it overwrote all of my saves after landing on various planets before I realized this had happened? I can probably just edit them off world using the save file but that seems tedious if it keeps happening

**Comment by tukoz** [comment]
I had something quite similar on two occurences, in Way Point and now in Cardea. Both time as *some* of my ships had a jump drive and other did not (eventually *some* having a keystone; still unsure on that one).  
To get my ships out of this trance (perfect word : o) I had to come back to where they stood, tell them to escort and go through the wormhole: one would eventually follow. I then ordered it to stand up on the other side, and I'd do another run 'till all finally passed the wormhole.

**Comment by WCDThor** [comment]
I'm currently having this problem as well. The ships are stuck in Cardea. I tried to baby them back to the wormhole, and even had three Author ships helping in addition to my 3 working escorts, they then stopped following me and kept re-boarding each other. I spent a good hour on this to no avail. Asked for help in Steam forums, hoping someone gets back to me there, but thought I'd add this here.

If you need clarification please let me know, really tired at the moment and about to go to bed.
