### ISSUE TITLE
Feature request: flare sprite scaling in engine outfit attributes

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#4585]
some time ago, the ability was added for ships engine definitions to scale flare sprites to accommodate multiple engine hardpoints with different sized flares by applying a multiplier to the hardpoint definition within a ship's attributes.

perhaps a similar technique could be applied to the attributes of engine outfits such that only the largest flare is an actual sprite, while smaller variants of the engine scale the large sprite down (which may then be scaled again for the reference feature).

specifically in reference to #4551, this feature would eliminate the need for the creation of two more engine flares (for Basrem and Baellie - that's 4 more files, ~1kb each).

the main benefit of this feature would be the elimination of roughly half of all current and future engine flare graphics assets - cutting distribution bloat, as well as launch time (especially for hdd driven storage - small files have a performance toll).

at the moment, this only amounts to ~200kb of data in some 48 files, but stands to improve over time as more engine flare styles are created.

this technique could potentially be applied to other effects as well, potentially offering more depth to explosions - mostly just adding the appearance of more sprites without actually adding those assets.  this may be a different feature request, so this is really just a footnote.

**Comment by Amazinite** [comment]
Syntax wise I have two ideas for this. 
Either have this be a number after flare sprite, which would only work for flare sprites and would be a logical extension of how only the flare sprites can be scaled via the engine hardpoint of a ship:
```
outfit `"Basrem" Atomic Thruster`
	...
	"flare sprite" "effect/atomic flare/tiny" 0.5
		"frame rate" 14
```
Or create a new attribute of sprites called scale, so all sprites that can be animated could use it (which includes ships, effects, and projectiles):
```
outfit `"Basrem" Atomic Thruster`
	...
	"flare sprite" "effect/atomic flare/tiny"
		"frame rate" 14
		"scale" 0.5
```

**Comment by jafdy** [comment]
I would go for option 2, although it would be harder with projectiles and more or less pointless with ships it would be an easy way to enhance effects (by reusing the same effect at different sizes).

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/compare/master...Amazinite:sprite-scale
I have a branch that uses the `scale` keyword as a child of a sprite, but it currently only works with flare sprites despite being able to be listed under any sprite. Looks like having this work with other sprites is a little more involved.

**Comment by Bladewood** [comment]
Is this a wholly optional feature? I think there are some cases where one might desire a difference between the smaller and larger engine sizes. For example, the large Coalition flare actually contains (to my eyes) a bit more blue and white than the small flare. I'd also be interested in engines that have a hue shift from tiny to huge.

**Comment by Bladewood** [comment]
We did mention cutting out half of the sprites. I'm just asking to be careful about what we choose to keep.

**Comment by LocalGod79** [comment]
> We did mention cutting out half of the sprites. I'm just asking to be careful about what we choose to keep.

good catch - did you notice any other major differences?  i did notice that the korath huge has an extra frame...not sure if that was intentional.  all others seem to be straight scaling (the atomics look like their frames are rearranged in each size)...
