### ISSUE TITLE
Korath freighters running around in circles

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#459]
During the FW Pug line, I used my Jump Drive to explore Korath space.
There are several freighters between Kor Men, Kor En'lakfar and Kor Fel'tar.
They don't have jump drivers so they're stuck and keep going in circles.
They do have loads of goods for trading on board though

**Comment by Wrzlprnft** [comment]
You probably met their world ships, and those are their homes.
I seems they are not meant to travel elsewhere (yet)

**Comment by frameworld** [comment]
Last I checked, world-ships have Hyper-drives (not scram or jump drives tough).

**Comment by wkoot** [comment]
Yes they had hypers. But they were also carrying goods like 600 electronics or something.
Perhaps they should only carry food otherwise? Unless the Korath eat electronics :-)

**Comment by wkoot** [comment]
Did the world ships get different gfx? Because these aren't the ones I saw earlier (went to check if it was indeed world ships).

**Comment by endless-sky** [comment]
Yes, in 0.8.9 they have new graphics (because the old ones were *really* embarrassingly tacky) and also there are three different variants with slightly different shapes, to support the idea that these are ancient, custom-built space habitats.
