### ISSUE TITLE
Operating costs for active automated ships

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4591]
**Is your feature request related to a problem? Please describe.**
Ships with crew have crew costs every day that the ship is active.
Automated ships currently have no such daily costs for being active.

Capturing automated ships is near the end of the current game, so this is not much of an issue at this moment. But if we want to add more storyline, then we might want to create some form of daily operating costs for automated ships as well.

**Related Issue Links**
Cloaking is another issue which needs to be addressed when we want more storyline in the main game (and also for more storyline from plugins), but that is handled in other issues like:
- https://github.com/endless-sky/endless-sky/issues/3825
- https://github.com/endless-sky/endless-sky/issues/4119
- https://github.com/endless-sky/endless-sky/issues/4121

There is also an issue called "A fix to the problem of (too much) money" (https://github.com/endless-sky/endless-sky/issues/486) which sounds kinda relevant.

**Describe the solution you'd like**
Some ideas that I have:
- Require "remote operators" for automated ships.
  - This can be very basic, like some persons somewhere on some unspecified planet.
  - This can also be explicit, like command centers (or automation support) on active non-automated ships.
    - Possibly with the requirement that the command center is within 1 jump of the automated ship.
- Require "local operators" for automated ships (basically not allowing the player to have ships fully automated).
  - Downside of this option is that automated ships owned by the player will be weaker than their full automatic counterparts, since the player will need to add commandcenters and bunks.

**Describe alternatives you've considered**
I didn't really consider other alternatives yet, but I hope that this feature request triggers a discussion which results in more alternatives (and better options than that I considered).

**Comment by Amazinite** [comment]
Seems like something that could be solved by having #4284, allowing ships/outfits to cost you without actually needing crew.

**Comment by petervdmeer** [comment]
> Seems like something that could be solved by having #4284, allowing ships/outfits to cost you without actually needing crew.

That is already a better solution than my proposals above.

**Comment by Amazinite** [comment]
#4596 has added the functionality of operating costs, but I don't think that it should be used on the automaton ships, or at least not right now. Capturing automata is basically the end game right now. Maybe after more alien factions are added and there's more choice around T2 outside of buying Wanderer ships or capturing automata, then it might make sense to give operating costs to these ships as a balancing factor. The whole point of the automata is that they don't cost you anything daily, though, so if ever operating costs are added, the cost should be less than the crew salaries of ships of similar size.

**Comment by petervdmeer** [comment]
Closing this balancing request; Amazinite implemented the operating costs feature that allows this type of balancing to be done.
