### ISSUE TITLE
Nicer formations turn behaviour

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4603]
**Is your feature request related to a problem? Please describe.**
The positions in a formation as implemented in #4471 exclusively depend on the position and movement direction of the lead ship.
If the lead ships movement direction changes 180 degrees (because the lead ship is reversing course), then all ships in the formation will immediately fly to their new positions exactly on the other side of the lead ship, causing the formation to collapse towards the lead-ship and then expand from the lead-ship again.

Collapsing and re-expanding can be undesired for protective formations that are around one or more targets to be protected. If the formation is used to screen for missiles, then a single missile just after collapsing the formation can do damage to a large number of formation members (including the protected ships in the middle of the formation).

**Related Issue Links**
Related to the formations proposal in #4438 and the implementation of it in #4471.

**Describe the solution you'd like**
This change-request suggests the following to make the turn behavior of the formation nicer:
- Let the formation itself have some memory of its heading and turn the formation at the turn-speed of the lead-ship, some default minimum turn-speed value, or at a speed based on the maximum speed of the outer formation members.
This will result in the formation staying more intact, but increases the time to align the formation to a new movement direction of the lead-ship.

- If the heading of the lead-ship doesn't match it's movement direction, then let the formation still use the movement direction as base heading, but apply 1/3rd of the movement-heading difference of the lead-ship (with a maximum of 30 degrees) as heading-delta for the formation to move to. This allows the formation to already apply some turning while the lead-ship is preparing a course change, but also keeps the formation mostly pointed in the movement direction.

**Describe alternatives you've considered**
Some other options/thoughts I considered:
- Formations that are `transverse symmetric` and `longitudinal symmetric` like a square or box formation with the lead-ship in the middle might not need any adjustment at all after a 180 degrees turn; just automatically mirror the formation over the transverse and longitudinal axises to get the same formation again.
- Formations that are only `longitudinal symmetric` but not `transverse symetric`, like a `delta (regular triangle)` formation with the lead-ship in the center could also use mirroring, but the formation would then still collapse and re-form over the non-symmetric transverse axis.
- Some formations (like the `delta (regular triangle)`, square, box, hexagon, octagon, n-gon) also have `rotational symmetry`. For example the previous `delta (regular triangle)` formation around the lead-ship is `rotationally symmetric over 120 degrees`, so when a lead-ship changes 180 degrees course, then the formation would only need to turn 60 degrees instead of 180 degrees to become the same formation again.
- Knowing a formations symmetry can also be beneficial for formations in fleets (to allow half of the fleets using a formation to use it mirrored).

**Additional context**
This change request is aimed at gathering feedback. Please provide any feedback you have. Some points you might want to consider:
- Do you see the current behavior on 180 degree turns as undesirable?
- Do you want to keep the option to have the current 180 degrees turn behavior? (And if so, then why?)
- Do you like the idea of the formation turning at some slower speed (and if so, then which speed do you consider most appropriate)?
- Would you like symmetry to be used with automatic mirroring and automatic rotation to limit the amount of formation turning?
- Do you see something I missed?

**Comment by Zitchas** [comment]
I'm not sure about the specifics, but it sounds good. I haven't tried out the base formations yet, though, so I can't comment on the details.

**Comment by petervdmeer** [comment]
Moved this specification to an feature design/rfc document in https://github.com/EndlessSkyCommunity/endless-sky/pull/52
