### ISSUE TITLE
Fixing OP nature of capping ships and gargantum players fleets via dynamic crew salary.

### ISSUE THREAD

**Issue by Cat-Lady** [endless-sky/endless-sky#4604]
**Is your feature request related to a problem? Please describe.**
Boarding - while fun and entertaining activity - quickly collapses into 1st most profitable, basically 0-risk and 0-challenge money maker. At the same time, it quickly collapses into situation where player amassed fleet that is bigger and more powerful than any other force in human space, or (a little bit later) in universe.

Cost of maintaining such gargantuan flotilla is laughable 100 credits per crew member, and crew members are unlimited, characterless and totally expendable.

Hoever, trying to make game compensate for playing amassing such indestructible fleets is hard work, with many possible problems and edge cases. Instead, I propose the following as low-hanging fruit (as in - relatively easy to implement) solution:

**Describe the solution you'd like**
**1.** Crew daily salary should increase based on the crew losses (be it during boarding, due to boarded ship getting blown up before you land it safely, due to your escort dying with crew on board - whatever, anything that makes you have less total crew, that isn't firing peacefully on planet, manually or via taking jobs)

**2**. The increase of cost should slowly decay with the time (in-game days) passing.

As a result, losing large number of crew in short timeframe would increase crew salary to - possibly - prohibitive costs, forcing player to adapt. Taking less "bloodbath'y" approach for a time would allow the "reputation" as careless leader to fade, decreasing the cost.
 
Such approach ensures that the early game isn't affected much (having ship/ships with less crew means that increase in daily crew salary isn't hurting that much, and having less crew members means less of them have chance to die), but during mid and late game, careless play could - and should - create a situation where elevated crew costs are higher than gains from capped  and sold stuff.
As an ultimate result, late game player would need to take proactive steps - like, reducing fleet size and focusing on effectiveness - to avoid going "bankrupt".

**Additional context**
This change requires relatively minimal changes to game per se, while creating big and productive changes in the game world. While other steps - like, creating more dynamically changed economy - could be taken with time, I believe that the proposed change is pure definition of "low hanging fruit" in game development - an effective fix to glaring issue, that doesn't require much work to implement (compared to other solutions).

Furthermore, I believe that proposed solution would play very nicely with future, possible enhancements - for example, any change that would allow enemy ships to initiate boarding (during player's plundering attempts or otherwise) would indirectly affect chances of getting crew loses during high reward situations, creating a positive synergy of high risk/high reward opportunities.

**Side note:**
The past proposition of static "death benefits" might seem like similar idea, but in my opinion dynamically and infinitely increasing cost of crewing ships is better and more scalable approach. It is also lore friendly - it is natural that captain having reputation of walking bloodbath for his crew would need to pay more to convince people to join (and said people would expect to be paid more due to high death expectancy and will to have bigger share in the profits due to risk involved).

**Comment by Pointedstick** [comment]
+1 for imposing costs on crew loss. As you point out, we did used to have a "death benefits" mechanic in the past that was was removed after ship and outfit deprecation was implemented. I think that was just fine, though your proposal is interesting too. We'd need to put some work into quantifying it though.

**Comment by petervdmeer** [comment]
In general I like the idea. But I do have some questions on how to implement this:
- How would the player be notified of the salary increase?
  - Should there be an explicit message: "Each crewmen is now asking for a higher salary of <...> credits per day due to the high risk of dying while serving you." ?
  - Or would the salary increase just silently be applied?
- Would this salary increase only apply for "new hires", or also for existing crew?
  - In case of "new hires" you should also consider automatic hiring (for ships with incomplete crew).
- Would this increase only be applied while the player is landed on a planet?
  - Or also during jumps in space (when the player does not have the option of parking ships)?

**Comment by petervdmeer** [comment]
Also see the discussion on #1650 for arguments in favor and against the change proposed here. Punishing players for taking up difficult challenges seems to be the biggest argument against this proposal.

**Comment by Cat-Lady** [comment]
Thank you for all comments/insights!

**How would the player be notified of the salary increase?**
I thought about a player "rank": - similar to combat rating - that would give a numerical and "in-lore" description of player leadership reputation. Something around the scale from "favorite captain of the crew" to "bloodbathing maniac" (actual titles up for some more careful consideration ;) ) The difference would be that it can go both up and down, obviously.

for the sake of simplicity, I would make all crew daily salary - for hired both before, and after - to rise/fall. After all, crew seems to be on day-to-day contracts, able to be fired on very short notice and replaced without excuses.

**Punishing players for taking up difficult challenges seems to be the biggest argument against this proposal.**

I think that as it stands now, the ratio between risk and gain is really turned upside down. High gain activities - like, getting expensive ships for free - should also be high risk one. Without some mechanics like the one proposed, it quickly goes downhill to situation of player effortlessly gaining most powerful fleet in human space/galaxy, which doesn't look like "difficult challenge" at all.

OTOH, the mechanic incentives careful play, making actually having and successfully maintaining strong fleet a rewarding challenge.

**Comment by diggorygray** [comment]
I like the idea of the rank or reputation determining the cost of your crew.

I've got some further complications to the idea which might be worth exploring?

You could have the idea of a low risk rating, where crew are happy to a certain point.
It might be that beyond a certain ranking of risk you start getting certain 'missions' or notifications.
Such as crew deserting your ship or demanding more pay when you land.

On the other hand this might be overly complex.
You could instead,simply have a crew insurance line under salaries at the bank that reflects your crew deaths per year or month.

Trouble is this doesn't reflect well alien or pirate crews.
Maybe your pilots license mandates crew insurance and if you ditch it you don't pay at the risk of getting caught without insurance and a license.
That might work well for pirate players.

Just some ideas :)

**Comment by Cat-Lady** [comment]
Closing as part of housecleaning.
