### ISSUE TITLE
Formation editing UI

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4606]
**Is your feature request related to a problem? Please describe.**
The formation flying functionality needs some UI components to allow formation editing. This PR contains a proposal of how such an UI could look like. As with the other proposals; please provide feedback if you have relevant feedback.

**Related Issue Links**
Related to the formations proposal in #4438 and the implementation of it in #4471.

**Describe the solution you'd like**
Here is 5 mock-up screens of how the formation editor could look like.

Screen 1: Player is building a formation. The Headhunter marks the center of the formation (would normally be the players lead-ship), the sparrows mark the formation positions. The info screen on the right provides text-controls that gives information and allows some text-based editing.
 Player clicks on a point (indicated by the white/black cursor) to start a new piece of a formation.
![formation_ui_01_click_add](https://user-images.githubusercontent.com/35403542/67123954-d5546100-f1f1-11e9-90c7-09deb93ff068.png)

Screen 2: New formation position is registered. Player moves the mouse a little bit outside the center to get an arrow to extend the new formation position to a line-segment with more than one position.
![formation_ui_02_extend_line](https://user-images.githubusercontent.com/35403542/67123962-d8e7e800-f1f1-11e9-8924-f56a480e8e47.png)

Screen 3: Formation line segment created after clicking. Formation line segment has now 2 positions and the extension control stays at the end of the line to allow the player to make the line segment even longer.
![formation_ui_03_extended](https://user-images.githubusercontent.com/35403542/67123977-deddc900-f1f1-11e9-9916-d71fd6d6f2ba.png)

Screen 4: Player moves the cursor a bit further away from the line that is being edited to get the "repeat control" and presses the repeat control to let this line repeat to allow the formation to automatically grow by repeating the currently selected line.
![formation_ui_04_duplicate_line](https://user-images.githubusercontent.com/35403542/67124016-ed2be500-f1f1-11e9-965e-25f8f11385c7.png)

Screen 5: 
The repeated lines are now also shown, with each repetition being more faded away than the first one.
![formation_ui_05_duplicated](https://user-images.githubusercontent.com/35403542/67124059-02087880-f1f2-11e9-9eca-6f71c128b64a.png)

**Describe alternatives you've considered**
I considered letting players input complex mathematical formulae to let them create formations, but I expect the current proposal to be easier to use for most users.

**Additional context**
I didn't include here:
- the list of formations that allows the player to select which formation to edit. Such a list is similar to a list of savegames or a list of player ships, so I don't think it's needed to discuss that here.
- scrollbars, but I do expect those to be needed when the formation becomes bigger than the players screen. (Should not be difficult to add.)
- visualization of how the formation changes when ships get added or removed. Such visualization can be added quite easily by just removing the first ship in the formation and then letting the other ships move to 1 position earlier in the formation. (Such promotion is visible in the movie linked from #4471).
- correct colors. This is a generic proposal of how the screen looks, but I expect that we will use better colors and better fading in the final UI.
- miniature preview of how the formation will look like (on the radar screen). This might be nice to add.

**Comment by Pointedstick** [comment]
I think rather than building a complex editor, we should start out with some pre-made formations and see if that's enough. I'm thinking about:
- **Linebreaker:** Heaviest capital ships in the front), everything else behind them in a wedge shape
- **Circle:** Capital ships in the center with smaller ships forming a circular picket around them
- **Swarm:** Capital ships in the center, while smaller craft have free rein to move around as they deem fit within a circle
- **Scouting:** Capital ships in the back, with lighter ships forming a wide line in front of them and retreating when heavily damaged
- **Line of Battle:** All ships form up randomly into a one-dimensional line
- **Block:** All ships clump randomly into a square or rectangle
- **Squadrons:** The fleet divides into multiple identical Linebreaker groups, each composed of one capital ship and several smaller ships
- **Random:** the status quo

These are based loosely on my amateur understanding of historical naval and modern aerial formations, with some tweaks for Endless Sky (e.g. typically naval vessels don't use formations that might be _n_ deep to minimize the risk of friendly fire, but that's not generally a concern in Endless Sky)

**Comment by petervdmeer** [comment]
> I think rather than building a complex editor, we should start out with some pre-made formations and see if that's enough.

Creating pre-made formations is already done. PR #4471 contains some pre-made formations:
- Delta (tailing the lead-ship)
- Wedge (in front of the lead-ship)
- Hexagon (around the lead-ship)
- Vee (formation used by birds and some early airplane fighter pilots due to good visibility)

CR #4438 contains on top of that examples of:
- Horizontal line (besides lead-ship)
- Square/Diamond
- Hex field (similar to block formation)
- Circle (simplified, complex circles are currently not fully supported)

And the movie linked from #4471 contains (besides the Delta-tailing formation) 4 straight line formations in different directions.

I do agree with you that the basic UI to select which ship participates in which formation is desired earlier than a full formation editor, but such UI is basically just a list of ships with behind them the selected formation. It is not a complex UI, just something to build once #4471 gets merged.

**Comment by Amazinite** [comment]
I get the sense that an in-game formation editor is getting into the territory of feature creep, because as mentioned a number of times before...
>The game is mainly intended to be played with a single ship or a small fleet... [source](https://github.com/endless-sky/endless-sky/issues/3862#issuecomment-417748136)

so having features like this that are really only helpful for massive fleets (what could small fleets need outside of the aforementioned basic formations?) is a bit much.

**Comment by petervdmeer** [comment]
@Pointedstick, @Amazinite; Thanks. Good to know that that this feature is out of scope for ES before I spent any time on implementing it.

**Comment by petervdmeer** [comment]
As discussed on Discord; this is out of scope for within the game itself. But once we get formations in the game, then we can still use the proposal here for an editor outside the game (for content creators).

**Comment by Zitchas** [comment]
I'll be a dissenting voice on this: While I don't think it should be a priority, I think that this is something that a lot of people could like and use. 

In regards to feature creep, quoting MZ:

> This is a classic example of "feature creep." If you want to play XCom, play XCom. If you want to play FTL, play FTL. If you want to play a 4x game, play a 4x game. But all those are well beyond the scope of a space trading and combat game, which is all ES is intended to be.

Adding ways to guide the organization of your fleet seems perfectly on-target for a "space trading and combat game." Admittedly, it sounds like a luxury feature, not an essential. I wouldn't want MZ and Tehhowch and the other Devs focusing a lot of time on this. But if someone is willing to put in the work to get it working, I think this would be awesome. 

I don't know about most players, but I consider having a fleet more or less essential for completing a fair number of the campaign combat missions. It'd be *really* nice to have some more control over said fleet. I know it's *possible* without a fleet, I've done it. But a lot of it is beyond my desired difficulty level about half the time.

That being said, I fully agree that getting the default formation patterns into the game and working is definitely the priority. And as far as that goes - if this is created as a stand-alone editor, it should work for those of us who want it. (and for us content creators)

**Comment by Pointedstick** [comment]
I say let's get the basic formations into the game first and see if we need to go deeper. It may be that the pre-made formations are just fine! And if we find that they aren't, at that point in time we'll have a more complete understanding of what's needed for an advanced formation creation UI.

**Comment by petervdmeer** [comment]
> I say let's get the basic formations into the game first and see if we need to go deeper. It may be that the pre-made formations are just fine! And if we find that they aren't, at that point in time we'll have a more complete understanding of what's needed for an advanced formation creation UI.

PR #4471 now works for Linux, Windows and MacOS. It looks ready for merging to me. Let's wait for it to be reviewed (and merged once it is okay) and then see where we are when others than me can experiment with it.
