### ISSUE TITLE
Sharing shield generation (possible new outfit)

### ISSUE THREAD

**Issue by DynV** [endless-sky/endless-sky#4615]
**Is your feature request related to a problem? Please describe.**
I keep wondering why I can't share my flagship shield generation instead of having to wait for enough of the fleet shield to be high enough to hyperspace jump (I'm not going into another system in which I may be in need of shields without it being decent; ie: >= 1/2 full and rest >= 3/4).

**Describe the solution you'd like**
I'd like to share my flagship shield generation, I'm assuming the 2 ships would have to be close to do that.

Perhaps there can be an outfit for that (I'm thinking in their "reality" it would add features to attune to the other shield frequency or(and) forcing off a security measures or perhaps even it would have to make the generator mobile (it could quickly be put in large pieces small enough to go through the dock)). There could be consequences for doing so; ie: a delay that if not met would loose the generation until it's completed, either in different segments or from start to finish without interruption. If there's both outfits and consequences, it could be that the better the outfit, the less consequences there is, the better ones could even require a crew (like Luxury Accommodations).

**Comment by petervdmeer** [comment]
It is possible for weapons to have positive instead of negative shield damage, but I'm not sure if we already allow weapons to reduce shields on the host ship when firing. If that last one is also possible, then it is possible to create a turret that adds shield in other ships at the expense of the firing ship.

The AI currently cannot handle this type of (healing) weapons.

**Comment by tehhowch** [comment]
Related: https://github.com/endless-sky/endless-sky/issues/334#issuecomment-169534329

There are no plans to support outfit attributes extending beyond the ship which has the outfit installed. The closest thing would be area-of-effect / "aura" weapons.

(There are a fair number of other issues regarding weapons which allies might use to heal other friendlies. Use the issue search / thread links to find them.)
