### ISSUE TITLE
Timer Ship not expiring

### ISSUE THREAD

**Issue by siber-cat1** [endless-sky/endless-sky#4616]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
1. Finish the "There Might Be Riots" quest line, which starts the hidden "Sad Archie" quest

**Expected behavior**
Timer Ship expires after staying in the system for a length of time, allowing the quest to progress

**System (please complete the following information):**
 - OS: Gentoo Linux 5.2.5
 - Game Source: Steam release
 - Version: 0.9.10

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**
I only noticed there was a continuation quest due to this ship conflicting/assisting another "Target Dummy" ship in the same system because I added the Ursa Polaris plugin (specifically mission OS23). If the Timer Ship expires as expected, other content can use the system for things without risk of a conflict.

I worked around the problem by changing the sign of "hull repair rate" in my game save, so that it would decay after a certain amount of time.

**Comment by tehhowch** [comment]
How long did you wait without moving? If you keep moving around in the system, the timer ship usually stops firing until it's done chasing you.

Related: https://github.com/endless-sky/endless-sky/issues/4271

**Comment by Zitchas** [comment]
It'd be good if we could introduce a timer function instead of using these "timer ships." It is bad enough that people need to hang around for a pre-determined length of time, even more so requiring them to hang around without moving somewhere without any real reason for doing so.

**Comment by tehhowch** [comment]
This mission tells you to hang around without moving. 

Other issues exist for discussion of alternative mechanics, e.g. https://github.com/endless-sky/endless-sky/issues/4475

**Comment by siber-cat1** [comment]
Yeah, a second playthrough confirmed that the issue was in my understanding of the quest (and the AI limitations). When I parked to just chill in the system, I did so outside hostile ship range.
