### ISSUE TITLE
Support for appending descriptions during events

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#462]
Instead of overwriting descriptions/spaceport texts (i.e. in event "capture of Kornephoros"), appending to the existing text would be convenient.
This would make it easier to add text for occupational events, such as the Pug invasion.
Removing this temporary text again might be difficult in case of multiple events, perhaps just resetting to default and reapplying the extension of currently active events?

**Comment by endless-sky** [comment]
Very often, changing a planet description involves changing the existing text instead of just appending something to the end of it. That does make it harder in the cases when just appending would work, but at least in the existing code those are the minority.

**Comment by frameworld** [comment]
Example Description Suggestion:

Description
* Default
 * text or "" (empty)
* FW Pug
 * text or "" (empty)

New sections can be appended, same-named sections re-set when newly declared (by a mission, etc).

**Comment by wkoot** [comment]
What about a message like "You recently liberated this planet, people passing by wave at you" (say, for 3 months)?
Or an informative message if you're the military governor in a sector? In a pirate sector it could say that cutthroats are waiting for you around every corner ;)

**Comment by endless-sky** [comment]
I'd rather not make changes to the data file mechanics that will make existing missions, events, etc. stop working. Requiring you to copy the whole description of the planet in order to edit it is really not such a big deal; the only problem is if a typo or something is fixed in the original but not in the copies.
