### ISSUE TITLE
Status of the asset directory: Issues and Ideas

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#4620]
Apart from pushing me to do #4571, @Cat-Lady also inspired me to have a look at alternative ways of hosting the asset directory. We are in agreement that the current method (google drive) is less than optimal, as it is completely detached from the rest of the game's ecosystem (Github). The only link is MZ updating it, but as you can see in #4272, at the moment that only happens a couple of times a year.

Based on these issues, we have some requirements to possible alternatives (spoilers: there is no way to fulfill them all):
- We'd love for it to be on Github, so we can integrate it into the PR workflow the way the hdpi plugin already is.
- We want to avoid a low bus factor, e.g. MZ being the only person able to update them.
- We want it to be free! (Unless there are volunteers to pay for it? :P )

## Github + git-lfs

Based on these conditions, a GitHub repo (no matter how huge it would be) immediately comes to mind. Unfortunately, GitHub [reserves the right](https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota#file-and-repository-size-limitations) to write "a polite email from GitHub Support requesting that you reduce the size of the repository" in case your repo exceeds 1GB.
The assets without old ships and outfits are approximately 5GB, and as is the nature of git repos, they are still growing in size. So I decided to contact GitHub support to see if they are willing to make an exception for us:
<details>

> M\*C\*O, Oct 3, 12:14 PM UTC
> 
> Hello,
> 
> I'm part of the development team around Endless Sky, an open-source game hosted on your platform. We are currently storing all our assets on a google drive, which makes for awkward PR requirements ("we merged this, so one dev now needs to update the drive" ). Since this is both confusing (to contributors) and annoying (to us), we thought about hosting the assets on GitHub, too.
> 
> We know it's technically possible, thanks to the disk quota article (see below). However, we would like some insurance that we will not be asked to reduce the asset's size right after moving them to Github.  To clarify: the assets currently have a raw size of 6.4GB. Even with version control keeping all changes, I do not expect them to grow any bigger than 20GB in the next few years.
> Would a Repository of that size be acceptable for you?
> 
> Thanks in Advance,
> M\*C\*O
> 
> Resources:
> The Disk Quote article from your support page: https://help.github.com/en/articles/what-is-my-disk-quota
> Endless Sky's Repository: https://github.com/endless-sky/endless-sky
> One of the reasons for my request: https://github.com/endless-sky/endless-sky/issues/4272
> The assets in their current form: https://drive.google.com/drive/u/0/folders/0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk
> My Personal asset mirror, which also tracks size: https://endlesssky.mcofficer.me/assets/

> Mattamorphic, Oct 3, 12:26 PM UTC
> 
> Hi M\*C\*O,
> 
> Thanks for writing in and I hope you are having a great day where you are.
> 
> We currently only allow you to upload 100mb files, and have a 1GB base repository, however we do provide you with the option to use Git LFS: https://help.github.com/articles/about-git-large-file-storage
> 
> I'd recommend reading through the documentation and seeing if this would suit your requirements.
> 
> Thanks
> Matt Barber

> M\*C\*O, Oct 4, 10:16 AM UTC
> 
> Hello Matt,
> 
> thanks for your quick reply. It seems that i misunderstood git-lfs - while it is advertised as solution for *really* large files, it also looks promising for our usecase, which is thousands of files with a couple MB at max.
> Just to make sure i read you correctly: when you say "1GB base repository", that excludes those files versioned with git-lfs, only their pointer files, right? For example, i've set up a test repository with the aforementioned assets, in total about 5-6GB of data. Would this pass your 1GB requirement?
> https://github.com/MCOfficer/lfs-assets-test
> 
> Thanks again,
> 
> M\*C\*O

> Matt Rose, Oct 8, 12:56 PM UTC
> 
> Hi M\*C\*O,
> 
> Other Matt here!
> 
> 
> "1GB base repository" does indeed exclude the LFS objects. Our 1GB limit is a soft limit. In practice, you can have repositories quite a bit bigger than this. We don't give hard limits as our infrastructure team evaluate the strain the repository is putting on our servers, and this can be affected by many factors such as the internal structure, rate of pushes, etc.
> 
> You _might_ be ok just storing all your assets in the regular repository, but I can't guarantee that.
> 
> Hearing about your use case in more detail, I'm not sure LFS is going to be the way to go - I advise that you read up about how bandwidth works with LFS: 
> 
> https://help.github.com/en/articles/about-storage-and-bandwidth-usage
> 
> Right now your LFS on the test repo has been disabled because you've got almost 6GB uploaded into storage. You'll need to purchase a data pack to get LFS re-enabled.
> 
> Keep in mind also that bandwidth is used by people working on forks of your repositories, if any, or if they clone fresh copies for themselves. You would be responsible for buying data packs to cover the entire fork network's usage, and I see that your main repo has 500 forks!
> 
> If the files in LFS are going to be updated a lot, your storage use will expand rapidly as we'll store a copy of each version of the file, and everyone working on the file will use its full size in bandwidth to download the updated version.
> 
> You might want to look into self hosting your own instance of LFS?
> 
> https://github.com/git-lfs/git-lfs/wiki/Implementations
> 
> If there is anything else I can help you with, please let me know!
> 
> Cheers,
> 
> Matt R

> M\*C\*O, Oct 8, 19:18 PM UTC
> 
> Hello Other Matt ;) ,
> 
> thanks for your explanation. You're right, i feel like LFS is not absolutely necessary for us - it's only viable as a way to get around limits, such as the base repository size. Unfortunately (well not really), there are a lot of people working on ES, so i can't quite estimate the amount of bandwidth we'd need. And on top of that, a paid solution isn't really what community-driven projects are looking for.
> 
> I appreciate the link about LFS alternatives, it made me realize i already have a self-hosted service capable of git-lfs. But it will be hard to convince the community of hosting a core part of the development process on one contributor's server. And after all, half of the argument against google drive is that it is yet another third-party service - one that is more reliable than my server, i might add.
> 
> It seems that for now, there is no good, painless solution to our problem. I may investigate this further and present the results to the community, but other than that nothing will happen for the time being. Thank you for your advice!
> 
> M\*C\*O

</details>

Let me summarize that for you.

GitHub does not want to (or the support staff is not authorized to) make an exception for us. They did, however, point me towards another way of hosting large amounts of data on GitHub: [git-lfs](https://git-lfs.github.com/). 

git-lfs essentially replaces big files with pointer files. If you're familiar with c++, yes, it's exactly what you think it is - if not, [GitHub support has a nice explanation](https://help.github.com/en/github/managing-large-files/about-git-large-file-storage).
How would this help us? Well, the aforementioned 1GB per repository do not include the files that the pointer files point to. That way, you can bypass the repository limit even though the repo technically has loads of data in it.
Of course, storing large amounts of data doesn't come for free. GitHub gives you 1GB of storage space and 1GB of of bandwidth for free each month, anything above requires the purchase of a data pack (5$, gives you 50GB bandwidth & storage in one pack for one month). Your bandwidth is also used when *a user clones your repo* of even *clones a fork*. That would potentially be quite expensive for MZ, and if he ever pays up too late, the assets are pretty much inaccessible.

## Self-Hosting

Another option that was mentioned was self-hosting a git-lfs capable repository (or a git repository, for that matter, since git-lfs is only useful to us to bypass the 1GB repo size). I could host that on my server without problems, but I feel uneasy hosting what is supposed to be a vital part of development on an old dedicated server that may crash at any moment. Not to mention the bus factor. At least google drive is reliable since cloud hosting services have tons of redundancy.

## Taking the risk

I mentioned that when your repo exceeds 1GB in size, GitHub *may* send you a polite E-Mail. Or they may not, we don't know for sure. Quote Matt R:
> You _might_ be ok just storing all your assets in the regular repository, but I can't guarantee that.

We could take the risk of creating a 5GB repository. I don't know what the consequences of such an E-Mail would be, and if they would leave us enough time to pivot back to another system, but it is a possibility.

## The classic anti-bus-factor

The last idea is to simply ask @endless-sky to give others access to the google drive folder. It's probably the least satisfying, but it's worth mentioning.

---

To conclude, the research has been done. In case you have any other ideas, I'd love to hear them, but I have kinda given up on this. There is no perfect solution. I just wanted to document my findings and give people the opportunity to discuss.

**Comment by Cat-Lady** [comment]
Thank you for looking into the issue, @MCOfficer. Thats some killer research!

From my experience with FOSS games hosting assets on github ([1], [2], [3] for minor examples), none of them even got that "polite e-mail" for passing the 1Gb boundary. It seems to be a relic from old times, or at worst, a way for Github to have rule to react when something is generating tons of traffic (cause it is their real issue with big repos, not the storage space).

In any case, in the ancient times when Github repos were limited to few gigabytes top and you could really see request to tone it down, it wasn't an instant block - it is a message that you can safely answer with "OK, give us a week, and we will move it out" and switch to plan B.

Not that I think - mind you - that ES assets would create such traffic, as for it to be a problem ever surfacing. In any case, I think the best approach would be:

1. Host the assets on the separate GitHub repo, with proper access set up for team members, eliminating the "slowbus" factor.

2. Have a backup Google Drive setup, with similarly sane number of people having write access too. Not used, until *unlikely* case of a need to move out from GitHub occurs. Alternatively, the content could just be mirrored to the Google Drive everytime they appear on GitHub, and the google driver itself listed as mirror - minimally more work to do, but gaining higher redundancy.

Cheers,
/CatLady

[1] - https://github.com/ZeroK-RTS
[2] - https://github.com/Warzone2100
[3] - https://github.com/supertuxkart

**Comment by petervdmeer** [comment]
Some more (free) options to consider if Github doesn't work out:
- Gitlab, http://gitlab.com also uses Git and Git-LFS. The default/free repositories seem to have a storage limit of 10GB, but open-source projects can also apply for a free Gold and Ultimate plan. I'm not sure how much storage you can use then, but I think they would be happy to talk to you.
- Sourceforge, https://sourceforge.net/p/forge/documentation/Disk%20Quotas/ also supports Git (and probably also git LFS). The site doesn't list a hard limit, but SF used to be managed quite badly with projects being replaced by commercial crapware. I do have the impression that they changed to a new owner and cleaned up their act.
- Atlassian Bitbucket https://confluence.atlassian.com/bitbucket/what-kind-of-limits-do-you-have-on-repository-file-size-273877699.html is not really a good alternative, since it has a 1Gb soft-limit and 2Gb hard-limit and is very explicit about not being a file hosting service. But just wanted to mention it here to save you some time looking into their position.

**Comment by Cat-Lady** [comment]
So, is there any decision made/being made, or any chance for the issue to become resolved in near future?

**Comment by MCOfficer** [comment]
> 
> 
> So, is there any decision made/being made, or any chance for the issue to become resolved in near future?

oh... you will learn to be patient while working at this project..

**Comment by Cat-Lady** [comment]
It's OK - I know how volunteer/FOSS projects work.

That said, this is a rather easy decision and trivial thing to implement, either way - so I assume that there must be something sensible blocking progress, not a "let's train Zen mentality" reason ;)

This is precisely why I am asking. After all, we want to improve things when possible, not learn to accept them if they are broken, right?

**Comment by MCOfficer** [comment]
For the time being, we're maintaining an unofficial asset repository over at ESC:
https://github.com/EndlessSkyCommunity/endless-sky-assets

**Comment by throwaway1037** [comment]
Here's an idea: how about ES self-hosts an instance of SourceHut, or switches to sr.ht? It is free software, and if self-hosted, there will be no arbitrary limitations on file size.

**Comment by MCOfficer** [comment]
I don't want to pollute this issue by discussing my philosophy regarding software. Let's keep that to somewhere else.
