### ISSUE TITLE
[Content] Making a Storyline.

### ISSUE THREAD

**Issue by TheOperator19** [endless-sky/endless-sky#4623]
Hello, ive been playing Endless sky for quite a while and i love the game, so Im interested in making a new storyline for Endless Sky. Can i do this, or no? I was thinking of making a storyline where the player helps an alien faction at its attempt to be a space-faring species.

**Comment by Zitchas** [comment]
Welcome to the Endless Sky github. Yes, you can do that. Endless Sky is - as you can probably see - an open source game with considerable input from the community. Getting stories and content merged into the base game is a fairly long process, so I would encourage you to build your missions and content into a plug-in first, and then see about merging it into the base game once everything has been ironed out.

Given that Github is not really the best environment for asking questions or having discussions, I would like to invite you to the Endless Sky discord, where most of the content creators discuss what they are doing, ask questions, etc. The address is: https://discord.gg/ZeuASSx

**Comment by Pointedstick** [comment]
Yep, all of that. :smile:  ^^
