### ISSUE TITLE
Accepting Spaceport Defenses can result in negative cargo space

### ISSUE THREAD

**Issue by cberner** [endless-sky/endless-sky#4624]
**Describe the bug**
Accepting the Spaceport Defenses mission while your cargo is full results in negative cargo space

**To Reproduce**
1. Go to Sabik and get the Spaceport Defenses mission, while your cargo is full
2. See that your cargo space is negative

**Expected behavior**
You should be forced to sell ordinary cargo when accepting the mission

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Game Source: Steam
 - Version: 0.9.10

**Comment by jafdy** [comment]
Did you doing anything else around this time such as reloading a save with escorts out of system?

**Comment by cberner** [comment]
Nope. I just accepted the mission while my cargo was full. I did have
escorts, but all of them were parked (some on the planet and some on
another one)

**Comment by tehhowch** [comment]
The core game's spaceport defense missions do not have associated cargo. Can you provide screenshots, a save file (i.e. a copy of the file after you get launched), and information about any installed plugins?

**Comment by cberner** [comment]
Unfortunately, I've already played past that mission, so I don't have screenshots or a good save file. I don't have any plugins installed.

Are you sure there's no associated cargo? I remember being at -75 cargo, and that matches the value in this file (https://github.com/endless-sky/endless-sky/blob/e14b51b82e66dd671002f08f2ba4037dbaaecd77/data/transport%20missions.txt#L3157). I don't know anything about the codebase, but that looks like the mission description

**Comment by Amazinite** [comment]
If you have ordinary cargo and then accept a mission that has cargo, the excess ordinary cargo will be sold on launch.
There are a number of scenarios while landed that you can get negative cargo space, but never will you launch with that negative cargo space. Either the excess cargo will be sold off, or if the excess cargo is mission cargo then you'll receive a prompt saying that launching will fail missions.

**Comment by tehhowch** [comment]
> Unfortunately, I've already played past that mission, so I don't have screenshots or a good save file. I don't have any plugins installed.
> 
> Are you sure there's no associated cargo? I remember being at -75 cargo, and that matches the value in [this file](https://github.com/endless-sky/endless-sky/blob/e14b51b82e66dd671002f08f2ba4037dbaaecd77/data/transport%20missions.txt#L3157)
> 
> I don't know anything about the codebase, but that looks like the mission description

Ah, I misunderstood which mission you were referring to--there are a number of missions that offer from various spaceports, in which you mount a defense of the system. Accepting these results in a forced launch, and I was thinking that this was when you were seeing the negative cargo space.

As mentioned above, it is normal behavior for commodities purchased in the Trade panel to be ignored until you take off.

**Comment by cberner** [comment]
Ah I see. I was just confused because other missions pop up a dialog saying
you need to sell "ordinary cargo"

**Comment by feyone** [comment]
I have a similar problem. My fleet now has -20 tons cargo, meaning I autofail the Remnant gas giant mission because the ship has a max of 20 tons cargo. I don't how this happened.
On a related note - I got caught and fined (on Betelguese) with Nerve gas - fair cop and the nerve gas vanished (odd - I assume confiscated) but ever since then I get randomly fimed 1M credits for nerve gas I don't actually have - getting very expensive.

**Comment by jafdy** [comment]
Can you post your save file with the relevant issue.

**Comment by feyone** [comment]
I am unsure of how to do this - it runs off Steam
 - I have scanned the local files but can't find anything resembling a savegame file

**Comment by feyone** [comment]
More on the Gas giant mission issue - I bypassed it by flying in with 4 gas ships (32 tons cargo total)
landed on both gas giants and got away with only 2 "decoys" killed, only to find the mission (along with an unrelated remnant mission) had vanished. having spent 2 weeks solid grinding through the missions to get a Bactrian, to have this sabotage the whole thing is very annoying.

**Comment by tehhowch** [comment]
@feyone that sounds like a different issue, likely #1945 #1624

**Comment by Zitchas** [comment]
If you are on Windows, then your save should be located at:
`C:\Users\YourUserName\AppData\Roaming\endless-sky\saves`

The GitHub release, nightly builds, and Steam version all use the same AppData location for storing saves, plug-ins, configuration files, etc. (I'm not familiar with Linux or MacOS versions, though. I don't know where it uses for those)

edit: For the benefit of those who aren't aware of it; the AppData folder is a hidden folder that has to be revealed in the view settings. That being said, you should be able to just copy that location into window explorer's location bar, substitute your own user name in, and hit enter.

**Comment by feyone** [comment]
Ahh, yes, I found it - I will know for future reference.
Foolishly I went back to a snapshot from 4-5 days ago, and didn't save the problematic file at the time
I don't have the recurring $1M credit fine as yet because I haven't bought the nerve gas.
- It's still odd how it vanished about the 2nd time I was fined. Thanks for your help.
I will make more regular snapshots in case the issue recurs.

**Comment by tehhowch** [comment]
Seems this original reported issue/question is resolved. Any further discussion about a mission failed on reload due to negative space should take place in the dedicated issue for that topic.
