### ISSUE TITLE
Have Outfits Expansion with less heat issues

### ISSUE THREAD

**Issue by DynV** [endless-sky/endless-sky#4625]
**Is your feature request related to a problem? Please describe.**
Using more than a few Outfits Expansion can cause quite a problem with heat.

My strategy was to change ship and use multiple Outfits Expansion in it which would have been better overall... that is before I realized the important issue that cause with heat (I may load a previous save to revert the ship switch).

**Describe the solution you'd like**
I'd like there to be an additional Outfits Expansion type that affect heat less. Perhaps the other type could cost more or provide less outfit space (I'd prefer it to cost more but I'm not sure my vote count).

**Describe alternatives you've considered**
Perhaps there could be an outfit specialized to deal with plain Outfits Expansion instead ; ie: some kind of special cooling or brackets for Outfits Expansion to be installed in places that affect heat less.

**Comment by Amazinite** [comment]
The cooling inefficiency of outfits expansions is their entire balancing point, so it makes little sense to make a better version of the outfits expansion without completely breaking ship balance (#2184).
Instead of making a better outfits expansion or making an outfit that counteracts cooling inefficiency, it would make more sense to create a separate outfit that converts cargo space to outfit space with a different downside. Assuming I'm crazy enough to do it, one such outfit might make it into the game.
```
outfit "Precision Expansion"
	category "Systems"
	cost 150000
	thumbnail "outfit/blue screwdriver"
	"mass" 24
	"outfit space" 12
	"cargo space" -36
	unplunderable 1
	description "An outfits expansion system which converts cargo space into outfit space in a more precise manner, allowing for cooling systems to work properly at the cost of converting less space."
```

**Comment by DynV** [comment]
😲 that's both considerably more expensive and spatially less effective; although the cost might be reasonable considering there's no heat effect at all. To apply this, I add that to the save file? Is it all, or something else need to be done (ie: load it in custom mode).

Perhaps there can be 3 models: Precision Expansion, the original, and something in the middle. Although if there can only be 2, I prefer this no heat effect at all than the compromised one.

**Comment by Zitchas** [comment]
Personally, I'd love to go the EV route and have an option that didn't have a heat penalty and was quite efficient - but was permanent. No uninstalling it. So one would permanently lose some flexibility with the ship (and gain a bit of heat penalty - although not as much)

**Comment by tehhowch** [comment]
My opinion: unlikely

**Comment by MCOfficer** [comment]
> 
> 
> My opinion: unlikely

I think we are more-or-less in agreement that outfit explansions will not be buffed. @Amazinite 's idea seems possible, though.

**Comment by DynV** [comment]
I'm still wondering how to implement @Amazinite Precision Expansion. Also I assume I'll have to add it to some outfitters in order to buy them and have them installed; perhaps even add it somewhere so I might occasionally find them on other ships (so I can plunder them).

**Comment by Zitchas** [comment]
For more detailed instructions, here's the wiki entry on making a plugin:
https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins

The short version, though, is copy his text into a text file, then put that file into a folder called `data`, then that folder into a folder called whatever you'd like to call this plug-in, then stick that folder in your plug-in folder.

**Comment by Cat-Lady** [comment]
Given that this feature is exactly what stops big cargo freighters form becoming better all-around warships than any warship itself, I hope it never goes away.

**Comment by Amazinite** [comment]
You should have the means to make your own version of this through a plugin, but it isn't likely to happen in vanilla, so I'll close this issue.
