### ISSUE TITLE
more effect customization options

### ISSUE THREAD

**Issue by rymeilema** [endless-sky/endless-sky#4631]
add features that=
1 - give ships the ability to have an attribute that overrides weapons's hit effects
example:
ship "Heavy Skylark"
	sprite "ship/hskylark"
		"frame rate" 30
	thumbnail "thumbnail/hskylark"
	attributes
		category "Heavy Warship"
		"cost" 10325000
		"hit effect" "shieldhit"
the end result is that the ship calls for effect "shieldhit" whenever it gets hit by a projectile, and other ships can use different effects

2 - give hit effects an option to not be affected by the momentum of the projectile or the ship hit by a projectile, having instead a fixed position that updates every frame to the ship's origin

this allows hit effects like these (https://www.youtube.com/watch?v=JrwiNQc4oE0) to not look weird when the ship is slowing down or speeding up

3 - add a new sprite attribute that plays an idle effect so things like these (http://prntscr.com/pr5afe) aren't necessary

this could open a different way of making better or different animations for ships, separating lights, shadows and other visual effects from the base ship sprite

**Comment by Amazinite** [comment]
> 1 - give ships the ability to have an attribute that overrides weapons's hit effects

So basically a duplicate of #2568?

> this allows hit effects like these (https://www.youtube.com/watch?v=JrwiNQc4oE0) to not look weird when the ship is slowing down or speeding up

Could you show an example of it looking weird? Nothing looks out of the ordinary in that video.

> 3 - add a new sprite attribute that plays an idle effect so things like these (http://prntscr.com/pr5afe) aren't necessary

So like overlapping two sprites so that you only have one ship sprite by X number of sprites for the effect?

(Please 1. split multiple requests into multiple issues and 2. use the feature request template going forward.)

**Comment by rymeilema** [comment]
adding to it sounds better, i agree
it looks weird when the ship that's getting hit turns fast or changes speed fast, i'll record another video to properly show it
overlapping two sprites, yes, but now that i think about it probably isn't such a good idea - doesn't fit well with the game imo

apologies for the bad format, won't make the same mistake again
