### ISSUE TITLE
AI (auto land) gets confused with reverse thrusters

### ISSUE THREAD

**Issue by fizzfaldt** [endless-sky/endless-sky#4640]
**Describe the bug**
I installed 3 sets of reverse thrusters, such that it's stronger than my forward thrusters.
When I try to land on a planet, it does this weird hopping around.  Instead of just slowing down when reaching the planet (or the old turn around and use forward thrust to slow down) it does some weird hybrid and takes a lot longer to actually land (it starts orbiting the planet almost and firing the forward thrust intermittently).  It seems like it's confused.

**To Reproduce**
Note: I heavy modified the ship I'm flying in, so it's possible what I put in it generated some bugs.  Will attach a save file.
Load this save, leave the planet, go far away.  Then try to land again.

**Expected behavior**
I expect it to choose between reverse thrust or turn+forward thrust and land perfectly.  It shouldn't start orbiting around the planet.

**System (please complete the following information):**
 - OS:
```
$ cat /etc/lsb-release: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
$ uname -a:
Linux buk 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 - Game Source: Steam beta
 - Version: 0.9.10 beta

**Link to save file**

**Additional context**
It's possible that the heavily-faked sparrow ship is causing the problem.
[Fighty McFighterson.txt](https://github.com/endless-sky/endless-sky/files/3802658/Fighty.McFighterson.txt)

**Comment by Amazinite** [comment]
Yeah. Reverse engines are undersupported right now. #1583 #1838 #2716

**Comment by tatami4** [comment]
I cannot reproduce this with this save and the ship I modified. I think this should be closed, because it appears to be fixed.
@Amazinite
