### ISSUE TITLE
Replace the Militia Carrier license with a general Militia license and lock the Dreadnought with it

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4648]
**Is your feature request related to a problem? Please describe.**
The Dreadnought currently has no license to acquire it. The Dreadnought should still be created during the Navy and Syndicate campaigns though, but the lack of a license means that anyone could buy the Dreadnought when presumably it should only be the Free Worlds that can purchase it, akin to the Navy ships requiring Navy licenses.

**Describe the solution you'd like**
Replace the Militia Carrier license (which currently only locks the Skein) with a general Militia license that locks the Dreadnought and the Skein.

**Describe alternatives you've considered**
Alternatively, going through the other campaigns could simply result in the Dreadnought never being for sale, yet still existing in fleets.

**Comment by jafdy** [comment]
This can be implemented now with no negative side effects. Only players with a licence already has the dreadnought unlocked. Even the events doesn't need changing.

**Comment by Naminson** [comment]
It might be a good idea to make the Skien be under a militia license, and the dreadnought need a militia license and some other kind of license, since that's how the navy capital ships work right now.

**Comment by Amazinite** [comment]
The FW Militia isn't structured the same way as the Navy, so I don't necessarily see why they'd follow the same license structure.
