### ISSUE TITLE
Typo in ship description for Petrel

### ISSUE THREAD

**Issue by TBBunnyWoar** [endless-sky/endless-sky#4650]
There are 2 "an" after each other in the ship description for the Petrel.

![Screenshot (838)](https://user-images.githubusercontent.com/48247366/68410996-f58c9580-0189-11ea-9052-d603e5de2006.png)

**Comment by Zitchas** [comment]
Thanks for spotting that. I appreciate having people flag these for us.

**Comment by tehhowch** [comment]
Fixed by #4651
