### ISSUE TITLE
Syndicate outposts with outfitters in Korath Exiles space

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4653]
**Is your feature request related to a problem? Please describe.**
Capturing Mereti type ships from Korath Exiles near the end-game is possible, but the player will not be able to move them out of Korath Exile space, since Mereti type ships don't have a Jump-drive, they only have a Hyperdrive.
(I finally captured my first 512, only to learn that I could not bring it elsewhere.)

**Related Issue Links**
#2039 might be a little bit related.

**Describe the solution you'd like**
I would like to see some missions where the Syndicate asks you to setup or help a covert outpost in Korath Exile space for them. Far'en Lai seems to be a great place for the Syndicate to put such an outpost, since the Korath don't go there and the Syndicate does not seem to be the type of organization that believes the fairy tale around the planet.

The motives for the syndicate to setup such an outpost could be that the syndicate uses the outpost to coordinate their "alien technology acquisition" activities (which is actually similar to what the player does when farming Korath Exiles).

The outpost should eventually have an outfitter to allow the player to refit captured Mereti type with a jumpdrive.

System Kor Fel'tar, Kor En'lakfar or Kor Men could also use such an outpost.

**Describe alternatives you've considered**
I considered writing those missions myself, but I didn't really have inspiration beyond the text I already wrote in this feature request.

**Additional context**
The Syndicate did get Jump-drives and a Cloaking device from alien origin earlier in the story-line, so setting up an outpost for "acquiring alien technology more easily" does seem in line with other/earlier Syndicate activities.

**Comment by jafdy** [comment]
Why?

**Comment by Zitchas** [comment]
The main point seems to be to act as a base for the player to facilitate stealing automata and outfitting them with JD to get out of the automata systems.

**Comment by petervdmeer** [comment]
Exactly, similar to how the Kor Efret facilitate stealing automata and outfitting them with JD earlier in the game when the two automata fractions are battling eachother.

**Comment by jafdy** [comment]
Perhaps we should consider the fact that there is more story to come for both the Wanderers and the Korath. We are part way through that story that may well end up giving such access or making it unnecessary.

**Comment by petervdmeer** [comment]
That is a good argument and makes #2039 more related.

I'll just close this request for now; can always reopen it if this still is an issue later.
