### ISSUE TITLE
<combat rating> text replacement

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4658]
**Is your feature request related to a problem? Please describe.**
The player's combat rating is rarely recognized in game. Titles exist for various levels, but they aren't used anywhere outside of the player info menu.

**Describe the solution you'd like**
Add a `<combat rating>` text replacement that replaces to become the player's current combat rating title. This allow the player to actually be referred to by their title.

Not all the combat rating titles would fit into a sentence in the same way, so I'd expect the mission to use branches or to limit the offering of the mission based off of the player's combat rating in order to have the text still make sense with the text replacement.

**Comment by tehhowch** [comment]
One thing to remember is that the combat ratings can be changed by plugins, so there is no guarantee that combat ratings can be substituted into conversations / text, even if all the base game ratings would work.

Probably such an enhancement would necessitate updating the way ratings (and other user-definable elements) are declared, to allow also specifying how each rating is incorporated into a sentence (which will generally be localization-dependent, e.g. https://github.com/endless-sky/endless-sky/issues/558#issuecomment-487903300)

**Comment by Amazinite** [comment]
This can be effectively done using custom text substitutions if anyone would like to. #6356
