### ISSUE TITLE
Dumping to pick up, for fleet members

### ISSUE THREAD

**Issue by DynV** [endless-sky/endless-sky#4660]
**Is your feature request related to a problem? Please describe.**
I have to wonder how much free space to leave so the fleet members may be able to pick things up. Maybe I missed it but I never saw a fleet member pick something up (ie: 5 tons of metal) while there was no free cargo space.

Since my crew cost is considerable, I try to squeeze any money I can, which include trading (trying to choose the commodities which the difference between the buying and selling point will yield the most profit). Another good way to make money is if I know I'll get into multiple combats, I'm hoping some of my fleet members will pick things up; however as mentioned in the previous paragraph, I don't think they will do so without free cargo space thus have to wonder the likelihood of getting into combat and its extent.

**Describe the solution you'd like**
I'd like it if the fleet members would know the cost of what's in their cargo and what's available to be picked up and if there's a good chance the latter would be more profitable, that the commodity type in the cargo be dumped.

If this enhancement is considered, I think for the fleet members closest to the commodities available for picking, some communication of the likely profit increase should be shared, then a combination of the highest profit--**and**--the time left for picking, as I noticed there's like < 15 secs to do so, that a choice be made and only the quantity to be picked be dumped.

If this enhancement is considered, perhaps an average of the surrounding systems price for that commodity can be compiled in order to make the comparison to the cost of what's in the cargo considered to be dumped (in order to make place for the picking).

**Describe alternatives you've considered**
When the process of figuring which ships could pick a commodity available to be picked (when the ship it was in got destroyed), perhaps the choice can be done manually; that is there be a popup with the list of the ships considered, much like the Player Info / Ship Info window (default shortcut key 'i'), but only for the related ships, which would allow for dumping and in the listing there can be 2 columns related to cargo, one showing the amount free and the other an input for how much to pick. Oh! And also a column for the estimated time to pick the commodity, and somewhere in the window overall info, the estimated time left for the commodity to be picked; ie: Overall section: 13 secs, Ship listing section related column: ship 1 row 6 (secs), ship 2 row 10, ship 3 12 (so the player may want to think hard before assigning commodity to pick for ship 3).

**Comment by tehhowch** [comment]
- yes, a ship must have free cargo space to collect flotsam & jetsam in-flight
 - Your fleet will never dump its cargo except at your explicit command (use the info menu, select the ship, then highlight the cargo to jettison).
 - your fleet will never go chasing after anything you jettison from your flagship (you are still able to jettison something into their path of flight)

Making your escorts automatically earn you money is not planned.
