### ISSUE TITLE
Terraforming 6: Not enough time when offered in Sol.

### ISSUE THREAD

**Issue by DutchTrader** [endless-sky/endless-sky#4675]
**Describe the bug**
On transportmissions.txt supplied with Endless Sky v0.9.9. One of the missions is Terraforming 6, summoned to Earth to answer for dropping an asteroid on Rand. You get some time to reach Earth. However, if the mission is offered on Luna or Mars in the Sol System, you're expected to arrive on Earth on the same day as the mission is offered. Since taking off to make the short trip to Earth takes one day, that's impossible.

**To Reproduce**
1. Follow the Terraforming Missions until Terraforming 5 (included).
2. Travel direct to Sol.
3. Land on Mars or Luna.
4. If Terraforming 6 is not offered, repeat landing on Mars or Luna until it is.
5. Comply and travel to Earth.
6. Receive the message that you did not arrive in time and are not a criminal of the Republic.

**Expected behavior**
Given a deadline of one or (preferably) two days, so that the mission can be completed.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Ubunto 18.04
 - Game Source: Repository.
 - Version: 0.9.9 stable.

**Link to save file**
N/A

**Additional context**
Workaround: Avoid Sol until the mission is offered.

**Comment by jafdy** [comment]
The relevant section of Terraforming 6 is
```
	source
		government "Republic"
		attributes "spaceport"
		not attributes "deep"
		not system "Sol"
	destination "Earth"
	deadline
	deadline 2
```
So it would appear that it can't be offered in Sol, and even if it was you would get two days to do the mission.

**Comment by beccabunny** [comment]
It has already been solved more than a month ago, use the latest version (0.9.10)
