### ISSUE TITLE
Content: Change Navy Generals to Admirals.

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#468]
Throughout time and space commanders of navies have been known as Admirals, yet they're referred to as generals in the game. 
Coming from a long line of seafarers, I've noticed this mistaken nomenclature in numerous conversations. And I'm almost certain I'm not the only player with saltwater in his veins who's noticed it.

**Comment by Thunderforge** [comment]
There was a rank of [General Admiral](https://en.wikipedia.org/wiki/General_admiral) in some navies, but I would expect the rank of Admiral to be used in Endless Skies if for no other reason than because that's the rank that sci-fi tends to use for space militaries (e.g. Star Wars, Star Trek)

**Comment by frameworld** [comment]
But I can say it adds a lot of confusion to peoples who are not experienced with military ranks and don't speak english as their first language.

It really doesn't matter, as long as it is either consistent or you can access a rank-manual-dialogue by clicking on a word.

**Comment by Thunderforge** [comment]
Why was this issue closed? It seemed like a pretty reasonable request.

**Comment by anonybosch** [comment]
The suggestion didn't seem to be getting any traction. Since it's a matter of semantics, and it's the Dev's game, I thought it best to clean up the interminable list of open issues.
