### ISSUE TITLE
Whitelist for negative attributes

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4682]
**Is your feature request related to a problem? Please describe.**
As of right now, the game prevents the player from installing/selling outfits if ANY attribute will become negative. It may be the case though that we want certain attributes to be able to go negative. Examples of such attributes would be those from #4525, which have been intentionally designed to allow negative values with differing effects.
![image](https://user-images.githubusercontent.com/17688683/69455153-c5222b00-0d35-11ea-8047-430aa72b9175.png)

**Related Issue Links**
#1128 The negative attribute warning has plagued me for some time now.
#4528 The ability for `attribute` to check negative attributes was mentioned here, but negative attributes are actually rare because of this issue, leading to the only examples of negative attributes being those set on ship hulls (e.g. the Arfecta).

**Describe the solution you'd like**
Create some sort of whitelist for attributes that dictates whether they can be negative or not. This whitelist would preferably be in the game data so that plugin makers can add to it if they have some attribute that they want to allow the player to have a negative value of.

**Describe alternatives you've considered**
We could also do the reverse and create a blacklist of attributes that we don't want to be negative. This blacklist would include cargo, outfit, weapon, engine space, gun ports, turrets, etc. All the stuff on ships that we don't want to have be negative. I could more reasonably see this being only in the source code, but a blacklist would likely have issues dealing with ammo capacity values.

**Comment by petervdmeer** [comment]
I'm not convinced by the `shield generation multiplier` example you link to. If the `shield generation multiplier` would be negative, then you would actually lose shield every second, and you would lose more shields when you have more shield generators installed. Technically this would work, but it is not really intuitively. For hulls it might even be more problematic (ships automatically dying).

I do like the current implementation that no single value ever goes below zero. Anybody creating new attributes can consider this and do whatever is needed to make the attributes work (in case of shield generation, do something like split it into two keywords, `shield generation boost` and `shield generation limiting`).

If we do really need to implement this, then I would prefer a whitelist over a blacklist, the default option should be that values don't go below zero.

**Comment by Amazinite** [comment]
Negative shield generation values have zero effect on a ship (as the DoRepair function in Ship.cpp does nothing if the generation is at or below zero). And in the example of multipliers, multipliers affect stats by `stat * (1 + multiplier)`, meaning that values between -1 and 0 don’t cause negative values of the stat, but reduced values.

**Comment by petervdmeer** [comment]
Okay, I wasn't aware that negative values where automatically ignored.
