### ISSUE TITLE
support for additional hardpoint types 

### ISSUE THREAD

**Issue by finite-galaxy** [endless-sky/endless-sky#4684]
Currently Endless Sky's code uses booleans for weapon, i.e. something is either a gun or a turret. This hard-coding limits possibilities. 
For instance, I'd like to have separate slots for guns and for missile launchers (e.g. Dagger two guns, Rainmaker four missiles and two guns, Dreadnought four guns and five turrets) and it's not inconceivable a plug-in creator might want to have different types of turret mounts (e.g. small, medium, large).

What ought to be done is de-hardcode these boolean weapon types and change the code to use a list, similar to `const vector<string> Ship::CATEGORIES` (Ship.cpp line 91 onwards), though ideally it ought to be in a data file, to make it customizable (see #3502).

Somewhat related: #3900.

A similar problem exists for carried ships, i.e. either a drone or a fighter, which prevents the addition of e.g. bombers or shuttle bays. See #4610, #4391, #4033, #3795, amongst others.

**Comment by tehhowch** [comment]
A simple change that would make this possible would be to allow a Hardpoint to require or forbid a keyword attribute on the outfit or the base weapon.

For compatibility purposes, it probably makes sense to only enforce these attribute checks if at least one Hardpoint in the Armament has this specialization.

Whoever attempts this will need to consider serialization and the variant definition system w.r.t. hardpoint respecification

**Comment by tehhowch** [comment]
I'm marking this as unlikely since I will not be working on this anytime soon. If someone does it themselves and opens a PR, that's a different story.  There are a number of more important features to be implemented before this, that would benefit this, such as changes to the order in which things get instantiated and processed.
