### ISSUE TITLE
"armament deterrence" should factor in special damage types

### ISSUE THREAD

**Issue by Derekcz** [endless-sky/endless-sky#4686]
**Is your feature request related to a problem? Please describe.**
Right now, the "armament deterrence" of individual weapons is calculated only using their hull and shield damage. This can lead to situations such as stock Dreadnought and stock Model 512 both having the same "armament deterrence" value due to the 512's Disruptors not being factored in properly.

**Describe the solution you'd like**
The formula shouldn't be just "(hull dmg + shield dmg) * 0.12", but instead should also count in damage types that can offset low DPS of a weapon, like "disruption damage", "heat damage", "ion damage", "slowing damage", etc...  

EDIT: I also realize that some damage types should affect the value more than others, for example heat damage would likely have to have a much smaller impact. This could be solved by having simple multipliers next to the damage types;  
( hull damage + shield damage + heat damage * 0.2 + ...  )
In case of disruption damage, it could use hull damage as its own multiplier so that disruption damage by itself would not be that threatening unless combined with proper hull damage;
( ... + disruption damage * hull damage * 0.1 + ... )

(I'm just making the multipliers up, I'm aware that proper play testing and balancing would be necessary, but you get the point...)

**Describe alternatives you've considered**
A possible alternative to properly estimate the armament of a ship would simply be looking at how much weapon capacity is used up, although that wouldn't be a fair solution towards weapons with good damage/outfit ratio.

**Additional context**
While the current formula works just fine to calculate pirate attractiveness, I think the "armament deterrence" attribute could be very useful as mission and/or job condition, because unlike combat rating it represents the actual strength of a fleet (but right now it doesn't do justice to Korath weapons).  
It could also be used to make interesting branches in conversations.

**Comment by Zitchas** [comment]
I get what you are trying to solve, and it makes sense, kind of.

However, theoretically this "deterrence" is handwaved as some kind of long range scan or based on the visual appearance of your ships at a distance. Basically a "That fleet has a lot of weaponry sticking off it, maybe we should skip that one."

In practice, I find it very dubious that generic pirates would have any clue whatsoever about what a disrupter is or whether or not they should be more afraid of it than, say, a heavy laser. Getting precise info such as disruption, heat, or other specialty damages is the sort of thing that I wouldn't expect anyone to know about a target ship without having first done a detailed outfit and/or tactical scan of the ship, and I'm not even sure that really should be sufficient. 

I would much prefer replacing the current dps total system with an alternative such as looking at how many tons of weaponry there is in the fleet; or how many weapon ports are utilized. To a pirate that isn't aware of wanderer tech, 1 turret looks less threatening than 3 turrets, even if that 1 is a sunbeam.

The more I think about it, the more I like simplifying this to the last option: Straight up weapon counts. No differentiation between what the weapons are, just look at how many the fleet has. To me, no other amount of information really makes sense for the pirates to have. 

If we had some kind of cohesive "Free Trader" pirates, like EVN had, then maybe I could see them having an information network with advanced scanners and other nifty stuff that would support them being able to get advanced intel on fleets across the sector. And even that I doubt would be able to differentiate the capabilities of advanced alien tech.But our current pirates, no. Our current pirates are basically lone bandits.

Returning to the original premise, I'm not sure that it makes sense to fix it anyway: Assuming that the pirates actually did manage to get a detailed scan of every ship in the player's fleet, how likely are they to understand the nuances of how all the weaponry works anyway? In game lore, we only have a single instance of any faction actually getting detailed mechanical information from scans, and that's the faction that has devoted several centuries to perfecting the art of stealing alien tech.

Given that disruption (and on the same token, ionization and slowing) are effects that no human weapon possess, it seems really unlikely that a pirate is going to be able to look at a scan and go "Oh look, that weapon is going pierce right through my shields. I need to stay away from that." What is far more likely is that they look at it and go "Oh look, they have an alien turret. Doesn't look very big or impressive." And if they are an engineer of some kind and scanners give a lot more info: "Huh, doesn't have much power in the main barrel - that won't do much damage. Not sure what this other stuff does, but at least it won't do much damage."

Situations like that lead to the enemy undervaluing weaponry that focuses on specials of various kind. Given how overpowering some of those can be, the current tacit boost to the old-fashioned straight-up damage weapons might not be a bad thing anyway. Gives the player a reason to stick with some of the older tech.

"Do I pick the big obvious gun that will scare pirates, or the small unobtrusive gun that will actually be more useful in a fight?" Not a bad question to have players asking, honestly.

**Comment by NomadicVolcano** [comment]
Another option is to have an "intimidation" stat for outfits and ships which overrides any internal calculations.  By default, you'd still use damage total for outfits and a boost of 0 for the ship itself.  If "intimidation" is specified in the outfit or ship definition, it replaces any calculations.  The work to rebalance the game would be easier than the other two suggestions since you only need to rebalance outfits and ships that have an intimidation trait.

For example, marauder ships may have a boost to intimidation due to the psychological impact of their social status.  The huge Ion Cannon would have a high intimidation due to its size.  Potentially we could even have outfits whose sole purpose is to improve intimidation.

**Comment by warp-core** [comment]
#8827 updated the deterrence calculation to consider the other damage types as well.
