### ISSUE TITLE
Engine line with smaller versions more efficient than larger versions.

### ISSUE THREAD

**Issue by AmkG** [endless-sky/endless-sky#4688]
**Is your feature request related to a problem? Please describe.**
Nope.

**Related Issue Links**
I believe not.

**Describe the solution you'd like**
Small thrusters/steering that are more efficient than large thrusters/steering, with a twist to keep them balanced.

It's a common pattern in Endless Sky that larger engines are more space, power, and heat-efficient than smaller engines.

This makes sense, since if the smaller engines were more efficient, you'd just use multiple of the smaller engine to move your big capital ship around, instead of switching to the larger engines.

What I would like to propose is to abuse `"cooling inefficiency"` so that we can have space, energy, and heat efficient small engines, that might be more efficient than e.g. `"Thrusters (Stellar Class)"`, but whose larger versions have lower space-efficiency until they are below atomic engines.

Because of `"cooling inefficiency"`, you'd still use the larger versions of that engine line on your capital ships (or replace them with other races' engines), because otherwise you'd limit your capital ships to not having Outfit Expansions, or maybe trade off having a few of the small engines and populate the rest of your engine space with a large alien one, getting the space advantage of the small engines to effectively trade it off as an outfits expansion.  For example if you might fit in an Outfits Expansion and an A250 Thrusters at 34 space, instead you might just use Efficient Small Alien Thruster at 19 space with the same energy, heat, and thrust (or even mildly lower thrust, or mildly higher heat), which frees up 15 outfit space *and* 15 engine space *and* without a drop in your cargo space, but like the Outfits Expansion you can't go fill your Bactrian with five of these to get a minmaxed flagship, your heat will cook you.

A ship with limited engine space might fill it with a few of these engines, foregoing the ability to trade off cargo space for outfit space, and getting a nice engine boost.

**Describe alternatives you've considered**
* More thruster/steering types for alien races.
* Bog-standard boring "bigger engines more efficient".

**Additional context**
Not much.

Lore-wise, maybe the Remnant would be interested in such engines; presumably they prefer small ships that can cloak versus large capital ships, thus might develop a small engine that is efficient while small, but can't scale up well.

Lore-wise, maybe the engines actually grab onto the fabric of space-time, and requires that long cables connected to the engines run along the entire length of the ship to act as "grab points"; overall you don't need much space inside the ship for the engine, but the long cables outside the ship hinder heat dissipation, and it doesn't scale well to larger sizes because more space-time fabric has to be grabbed to handle the big ships, so big ships either have to suffer the heat dissipation or use fewer "grab cables" at less efficiency.

**Comment by AmkG** [comment]
I believe this is `content` rather than `balance`? I'm not complaining some existing engines are OP, I'm wondering if instead it would be OP or not to have a new line of engines as I proposed.

**Comment by Zitchas** [comment]
I'm interested in the possibilities of this, but I'm not sure about balance. It is an interesting concept, though.

The Remnant *would* be interested in such things, and I'm already building the story out in directions of them developing unusual and/or dimensional-related tech.

**Comment by AmkG** [comment]
Thank you for the interest.  Here is what I have been playing with:

	outfit "Grabline Magnanimous Engines"
		category "Engines"
		"cost" 9250000
		"mass" 181
		"outfit space" -181
		"engine capacity" -181
		"turn" 3040
		"turning energy" 5.2
		"turning heat" 14.4
		"thrust" 119.4
		"thrusting energy" 11.0
		"thrusting heat" 24.3
		"cooling inefficiency" 1.5
		"heat dissipation" -.015
		"flare sprite" "effect/ion flare/huge"
			"frame rate" 0.8
		"flare sound" "ion huge"
		description "By combining grablines between both thrusters and steering, this engine keeps cooling inefficiency down, but overall the large grabline engines are not as efficient as atomic engines."

	outfit "Grabline Middling Thruster"
		category "Engines"
		"cost" 812000
		"mass" 41
		"outfit space" -41
		"engine capacity" -41
		"thrust" 47.5
		"thrusting energy" 5.1
		"thrusting heat" 10.5
		"flare sprite" "effect/atomic flare/medium"
			"frame rate" 12
		"flare sound" "atomic medium"
		"cooling inefficiency" 1.1
		"heat dissipation" -.011
		description "Grabline thrusters bind their movements to the fabric of space-time via long cables along your ship, but appear to be less efficient at larger sizes, while still having the con of reducing ship cooling."

	outfit "Grabline Middling Steering"
		category "Engines"
		"cost" 770000
		"mass" 26
		"outfit space" -26
		"engine capacity" -26
		"turn" 1189
		"turning energy" 2.5
		"turning heat" 6.6
		"cooling inefficiency" 1.1
		"heat dissipation" -.011
		description "Grabline steering connects to a fundamental layer of reality via long cables along your ship, but appear to be less efficient at scale, while retaining the loss of heat dissipation."

	outfit "Grabline Mini Thruster"
		category "Engines"
		"cost" 542000
		"mass" 21
		"outfit space" -21
		"engine capacity" -21
		"thrust" 27.2
		"thrusting energy" 3.1
		"thrusting heat" 6.3
		"cooling inefficiency" 1.0
		"heat dissipation" -.01
		"flare sprite" "effect/atomic flare/small"
			"frame rate" 13
		"flare sound" "atomic small"
		description "Grabline thrusters 'grab' onto the fabric of reality to provide thrust, requiring little space within the ship. However, long 'grabline' cables need to be laid out over the ship's exterior, which cumulatively reduce the ability of your ship to dissipate heat."

	outfit "Grabline Mini Steering"
		category "Engines"
		"cost" 491000
		"mass" 13
		"outfit space" -13
		"engine capacity" -13
		"turn" 686
		"turning energy" 1.5
		"turning heat" 3.9
		"cooling inefficiency" 1.0
		"heat dissipation" -.01
		description "Grabline steering 'grabs' onto local space-time in order to turn your ship, but requires long 'grabline' cables to be laid over the ships hull, reducing the ability of your ship to dissipate heat."

Another thing I have in the above is the "combined" engines, i.e. steering+thrust.  Other engine lines have this at the *smallest* engine sizes (Remnant and Human Ions), but in the above, the largest "Magnanimous" engines are combined instead of the smallest, another interesting inversion.

I also intend to create "Median" and "Maxi" engines, with the top-line "Magnanimous" as combined engines.  This gives 5 total engine levels in this line.

Another possible "host" for this engine line would be the Coalition Resistance, if you feel it won't quite fit with the Remnant.  The Coalition is about modular outfits that you just install multiple of if you need more of them, instead of developing larger levels, and this kind of engine line "pushes" against this strain of Coalition thinking (you can't safely add multiple Grabline Mini Thrusters unless you are willing to drown in heat), so possibly thematically appropriate.

**Comment by Amazinite** [comment]
Well if this isn't balance suggestion and instead just a description of an idea of what can be done, then I'd say that this shouldn't be an issue and is something more fit for discussion on a forum or the Discord server.
