### ISSUE TITLE
Steam should list Endless Sky as "Free", not "Free to Play"

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#469]
[Endless Sky on Steam](http://store.steampowered.com/app/404410/) is listed as "Free to Play", for instance in the price. 

![Endless Sky Free to Play](https://cloud.githubusercontent.com/assets/6200170/11826584/f36f4cca-a34b-11e5-9ed5-cb7ec2eeea65.png)

This makes it seem like the game has microtransactions in it, rather than being 100% free. [The Steam support article for "Free to Play" games](https://support.steampowered.com/kb_article.php?ref=8795-TIDH-0077) says the following:

> Free to play games are available to download for free and can be played without a subscription or a credit card. Your Steam wallet *allows you to purchase items and content in-game to customize your gameplay.*

The italicized part (emphasis mine) does not apply to Endless Sky, thus it is not truly a "Free to Play" game.

Endless Sky should be reclassified as a "Free" game instead so that potential players are not misled into thinking that this game has microtransactions.

**Comment by anonybosch** [comment]
Does Steam have a "Free" category?

**Comment by ItsNickBarry** [comment]
Yes

**Comment by Tufton** [comment]
How does this get changed? Would Michael have to petition valve?  Could we
do it?

**Comment by endless-sky** [comment]
I originally asked them to label it "Free," and specifically said that I meant "free" and not "free to play," but they made it "Free to Play" instead and I never followed up on that...

**Comment by Thunderforge** [comment]
I think it would be worth following up with them on this.

**Comment by guillochon** [comment]
I would too. "Free to play" has a very negative connotation which definitely does not apply to this game.

**Comment by endless-sky** [comment]
This is now fixed on Steam.

**Comment by Thunderforge** [comment]
It looks like Endless Sky itself is indeed marked as Free now (thanks for that!) but the [Endless Sky High DPI DLC](http://store.steampowered.com/app/404800/) is still marked as Free to Play. Will that be fixed too?
