### ISSUE TITLE
Log entry for "Remnant: Technology Available" has different point-of-view

### ISSUE THREAD

**Issue by AmkG** [endless-sky/endless-sky#4695]
**Describe the bug**
The log entry for "Remnant: Technology Available" has a different point-of-view compared to other log entries:

https://github.com/endless-sky/endless-sky/blob/deda255028f20fabb6ae814cf55f0eb1c2b0c3e1/data/remnant%20missions.txt#L579

For example:

https://github.com/endless-sky/endless-sky/blob/deda255028f20fabb6ae814cf55f0eb1c2b0c3e1/data/remnant%20missions.txt#L648

**To Reproduce**

1. Complete Remnant missions until you have been offered Remnant license.
2.  Look at logbook for the entry.

**Expected behavior**
The log entry should be from point-of-view of player, starting with a verb phrase with the player/writer as the implied subject.

> Considered a valuable friend of the Remnant after prefects have reached a consensus.  Was given permission to purchase their ships and technology.

**Screenshots**

**System (please complete the following information):**
 - OS: Debian 9
 - Game Source: self-compiled
 - Version: deda255028f20fabb6ae814cf55f0eb1c2b0c3e1

**Link to save file**
inapplicable

**Additional context**
inapplicable

**Comment by Amazinite** [comment]
Fixed by merging #4706.
