### ISSUE TITLE
Reconciliation branch gives Jump Drive even if you have Jump Drive, if you *also* have Hyperdrive

### ISSUE THREAD

**Issue by AmkG** [endless-sky/endless-sky#4696]
**Describe the bug**
When player has a Hyperdrive *and* Jump Drive installed when the Syndicate offers one of its precious 7 jump drives, the Syndicate will replace the Hyperdrive without noticing you *already* have a Jump Drive.

**To Reproduce**
1. Load this file: [Howard Raphelion.txt](https://github.com/endless-sky/endless-sky/files/3914555/Howard.Raphelion.txt)
2. Go to Haephastus in the Markab system.
3. See error.

**Expected behavior**
It would make significantly more sense for the engineers to not install an extra Jump Drive completely if you have *any* Jump Drive at all.  I am not that familiar with syntax but maybe the "FW Pug 2C: Hyperdrive" and "FW Pug 2C: Scram Drive" should have `require "Jump Drive" 0` conditions?

This did not seem to happen at 0.8.10 and 0.9.8, incidentally; I usually put both a Jump Drive and a Hyperdrive in all my ships, and have never reached this point in the campaign without a Jump Drive already stolen from a Korath, and I remember that previously if I had a Jump Drive the engineers would not replace my Hyperdrive with a Jump Drive.

**Screenshots**
Inapplicable.

**System (please complete the following information):**
 - OS: Debian 9
 - Game Source: self-compiled
 - Version: deda255028f20fabb6ae814cf55f0eb1c2b0c3e1

**Link to save file**
[Howard Raphelion.txt](https://github.com/endless-sky/endless-sky/files/3914555/Howard.Raphelion.txt)

**Additional context**
Inapplicable.

**Comment by Amazinite** [comment]
There's somewhat of a fix for this in #4310, but if the player has more than one ship and an escort has a jump drive, #4310 will act as though the player's flagship has the jump drive, which isn't exactly correct.

**Comment by AmkG** [comment]
I'd argue that even if it's your *escort* which has a Jump Drive and not your flag, then the engineers would still prefer not to give you the Jump Drive; maybe some kind of change in wording can be used to imply *any* ship in your fleet rather than "your ship" which implies "your **flag**ship".

**Comment by Amazinite** [comment]
We could easily merge #4310 for now, which would work for the a player in one ship (which is the "canon" way to play), then later on update the missions when #4002 is resolved/#4561 is merged.

**Comment by Amazinite** [comment]
This has been fixed by https://github.com/endless-sky/endless-sky/commit/4c31a1654513d675f1d2936d5ac14ed41d2ca8f1, which forces the order in which the mission occur as to check for a jump drive first.
