### ISSUE TITLE
Flotsam tractor beam

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4699]
**Is your feature request related to a problem? Please describe.**
Flotsams can often move at speeds that make it difficult for the player to capture. This is especially an issue when mining, where a good portion of the minables can be lost due to decaying flotsams. This also makes it nearly impossible to mine fast moving asteroids, as even if you destroy it, the resulting flotsams will be moving so fast and in different directions as to make it impossible to grab them all unless you were already right on top of the asteroid when it was destroyed.

**Related Issue Links**
#2102

**Describe the solution you'd like**
Add a tractor beam outfit/mechanic that attracts flotsams.
* Should this take up a turret slot or no? (I'd say no.)
* Where should the effect come from, if any effect is created by the tractor beam and it doesn't take up a turret? (I'd say just have the effect come from the ship's underside.)

This would involve an attribute `"tractor beam"` that, akin to anti-missile, would dictate that the weapon is used to attract flotsams. Perhaps have a number that dictates the number of flotsams that can be attracted at once? Or the number could dictate the pull velocity (instead of using hit force). In this way, a tractor beam could use lifetime, velocity, firing energy, etc. like any weapon.

**Describe alternatives you've considered**
We could also just increase flotsam lifetime so that players have more time to pick up flotsams before they disappear, and/or reduce the max speed of flotsams.

**Comment by beccabunny** [comment]
>Should this take up a turret slot or no? (I'd say no.)

I'd say yes, with the effect coming from it

**Comment by Amazinite** [comment]
The reason I say no is that the ships that would benefit the most from this are those that are mining, which are typically interceptors without turret.

**Comment by beccabunny** [comment]
In my opinion, the effect would look very weird this way (but still better than no effect at all). That said, you make a good point

**Comment by beccabunny** [comment]
Perhaps freighters, which are mostly turret based (or at least have some turrets), could be used in the miners' fleet? With this addition, I think it would male sense

**Comment by Amazinite** [comment]
I guess this would allow a way for the player's escorts to help in mining in some way. An early miner could use an interceptor for mining and a Star Barge for collecting the flotsams.

**Comment by Amazinite** [comment]
Given a ship like the Model 512, the disembodied tractor beam turret isn't going to fly, so I guess it'll just be a normal weapon, taking up turret space.

**Comment by Zitchas** [comment]
Oh, I'd say it still has possibilities - we just need something like a "default emission point."

Personally, something like a flotsam collector doesn't need a turret point. Or perhaps more accurately, I think that the base version doesn't need a turret point. A larger, longer range version, however, would perhaps be appropriate for a turret hardpoint. 

Likewise, if it is sufficiently controllable to haul around targets like a real tractor beam (which is something that I very much think would be appropriate for the Remnant); that merits taking up a turret slot, I think.

As a side note, the idea of making a focused beam version of this that takes up a gun slot but has a range similar to, say, a laser canon, would be rather interesting. The ship would still need to aim and use the thing, but would have much better range.

**Comment by beccabunny** [comment]
I think there could be two different types of floatsam tractor beam, Focused and Area:
-the Focused version would be a turret which takes up a turret slot, attracts one floatsam at a time, is generally faster and better ranged than Area. Can either attract floasam if it isn't being used by the player, or attract ships if it is being used by the player (attraction depending on mass of the objective, one turret will likely have little effect on something like a Carrier)
    *Side notes:*
    -this option could probably by turned down in the preferences, if one player wants to use it for floatsam while using other weapons
    -this likely should never be used by the AI to fight, since the ships that will use it hardly want to attract their enemies more than they want to take the floatsam; the only exception could be the Remnant, so this could perhaps be handled by having it used or not used to fight depending on the personalities
    -this one could have a laser-ish effect and a hardpoint for the turret
*Possible sprite:*
![tractor beam](https://user-images.githubusercontent.com/45330165/70166627-6cec1100-16c5-11ea-8e14-169fd9bbd7fd.png)

-the Area version would be a device which doesn't take up any turret slot, attracts every floatsam in range and is generally much slower and worse ranged than the Focused. Can only attract floatsam and is never controlled by the player
   * Side notes:*
    -this could have a continous energy drain, acting like a passive effect
    -it could have no visible effect, attracting stuff to the position 0,0 no matter the ship (this way the point about the 512 and similar having a hole is avoided) at least until something like #4700 is PRed and merged.
*Possible sprite:*
![tractor station](https://user-images.githubusercontent.com/45330165/70166667-81c8a480-16c5-11ea-886a-1c4c8342c5a0.png)

**Comment by petervdmeer** [comment]
We already have weapons with a negative hit force (effectively pulling things towards the direction of where a beam or projectile came from). My preference would be to make flotsam target-able and to implement this feature through regular weapons.

One thing to consider is if we would only want to apply hit forces to flotsam, or if we would also want to destroy flotsam when it takes damage.
Beccabunny's new sprites would be very nice for two new weapons that perform traction without damage.

The AI-code required for the flotsam-tracting-with-regular-weapons would be simpler than the AI for #4691.

**Comment by petervdmeer** [comment]
Collecting flotsam by exploding weapons just behind the flotsam (to have the explosion force push the flotsam towards the collecting ship) would also be cool, but that would require quite a bit more coding.

**Comment by Amazinite** [comment]
I'm thinking about this more like `"anti-missile"`. i.e. `"tractor beam"` weapons only target flotsams, and the flotsams can only be targeted by `"tractor beam"` weapons.

**Comment by Zitchas** [comment]
Given Petervdmeer's suggestion, I think it would work quite well to have flotsam given mass, velocity, etc. And then make it targetable using the weapon mechanics.

That being said, I do like the idea of having basically a "magnetic field" that pulls in flotsam from everywhere. 

The solution, to me, would be to allow for some kind of "opportunistic" firing mode whereby flotsam collection turrets automatically fire at any flotsam in range. That, combined with either a ray or an invisible projectile, could give a magnetic aura effect.

As such, the issue raised in #4714 could be relevant too.

**Comment by Amazinite** [comment]
>And then make it targetable using the weapon mechanics.
You'd still need some way for the game to differentiate between weapons that are suppose to and able to collect flotsams and those that can't though. And I imagine it'd be much easier on the player if such weapons auto-targeted flotsams instead of requiring that the player click on the small, short-lived, often fast moving flotsams first.

**Comment by Zitchas** [comment]
True.

Inspiration, for what it's worth: EVN had AAA turrets that autofired on missiles and fighters only. Also had attributes that specified that weapons could/could not affect missiles.

I agree that it would be much easier on the player if they either a) didn't have to manually target, and/or b) if it was an aura that affected everything nearby. I'd actually like having an aura that I manually controlled. (I don't care about picking up loot from some generic pirate. Definitely do want to pick up the loot from the Korath)

**Comment by petervdmeer** [comment]
I agree that if we add this, then it should be automatically targeting, just like anti-missile. And if we use regular weapons for this, then they shouldn't fire on flotsam if there are enemies nearby.

Automatically determining which weapons can tractor flotsam could be relatively simple:
- any weapon with negative hit-force (if we don't model in damage on flotsam)
- or any weapon with negative hit-force and damage below the hull-strength of the flotsam (if we do allow damage/destroying of flotsam).

**Comment by petervdmeer** [comment]
One other thing to consider is how easy we want collecting flotsam to be.
Flying around in an interceptor, shooting some asteroid and then moving fast and precise enough to collect the flotsam is part of the fun of asteroid mining. If we add some device that makes it too easy to just collect the flotsam, then that would actually take some of this fun away from the game.

**Comment by Zitchas** [comment]
I think it would be better to have at "does this affect flotsam: True/false" attribute. Keeps things much more straight forward, rather than have people wondering why their plug-in xyz weapon that has a attraction built into it is automatically firing on space-garbage. Give the content creators control over whether something does or does not affect it is almost always preferable over having things automatically change behaviour.

**Comment by Amazinite** [comment]
>Automatically determining which weapons can tractor flotsam could be relatively simple:
>any weapon with negative hit-force

But then we run into the issue of weapons being balanced for ship combat versus outfits balanced for flotsam grabbing. Unless we give flotsams ship-levels of mass and drag, which seems unrealistic given that I believe that flotsams typically max out at 5 tons (unless it's a whole outfit), something like a Grab-strike is going to cause flotsams to fly at insane speeds toward the player. 

I really don't see just using weapons with negative hit force as a good idea. The type of tractor beam used for attracting flotsams is likely going to be useless against ships given the size difference. If we want to get into the realm of multipurpose weapons (e.g. anti-missile and anti-fighter turrets, which I believe has been brought up as an issue before and was mentioned by Zitchas here, or in this case flotsam collection and anti-ship weapons), then I feel like that's a separate issue.

**Comment by petervdmeer** [comment]
We could implement the application of hit-force against flotsam without giving the flotsam mass and drag. The only thing we really need is a conversion factor of how much velocity change a single unit of hit-force gives to flotsam.

I do agree with Zitchas that some configurability is also desired, maybe we could make this conversion factor a variable on the weapon (conversion factor 0=> no hitforce applied to flotsam, conversion factor 1=> same velocity change on flotsam as that the hit force would do to a ship of 1000 tons)?

This way you could still create a mostly flotsam only weapon (low hit force, high conversion factor) and you could create the combined weapons (regular hit-force, medium conversion factor) and you could create weapons without flotsam collection by giving the weapon no hit-force or a conversion factor of 0.

I consider it a nice touch if the tractor beam weapons that I installed to fight against ships also do something with flotsam. Maybe not much and not very effectively, but just something to show that both ships and flotsam live in the same universe.

**Comment by Amazinite** [comment]
I've created a potential implementation of this over on #6050 while working on improving the mining experience.

**Comment by ravenshining** [comment]
@arkhne 's comments on #6050 brought an idea I've mulled over up to the surface.  Not a tractor beam, but more on topic here than in the economy test discussion:

An alternative to - or, perhaps, a lower-tier version of - tractor beams might be some sort of expandable collection apparatus - like, arms that extend to collect flotsam when desired.  Easiest way to do this that I imagine would be
- have these arms take up a gun or turret slot, preferably as a secondary
- count the outline of its (or all) hardpoint sprite(s) as part of the ship's hitbox
- add firing animations for weapon hardpoints
- "firing" the arms causes them to play their "opening" animation, enabling the player to more easily catch flotsam
- if coupled with a mining laser and given a slow closing animation, it could be given to AI miners for them to use without additional AI code

I'm sure creators could come up with a number of other applications for such mechanics, too.

**Comment by Amazinite** [comment]
I know the "arms that grab flotsams" idea has been talked about before, but I think it'd be much more difficult to implement than what I have over on #6050. Having a hardpoint firing animation plus hardpoints counting toward a ship's collision mask doesn't seem trivial to me, and going even further to have that be a secondary weapon seems a little hacky to me. (I imagine the AI would handle it fine, but it feels clunky for the player to use.) And in any case, the change I made already doesn't require additional AI code since tractor beams function autonomously, just like anti-missile. Mining/harvesting ships will still fly toward flotsams, but a tractor beam could either be pulling a flotsam toward the ship even faster or even be pulling a separate flotsam toward the ship. The tractor beam idea also has the added benefit of allowing a player's escorts to partake in mining.

**Comment by Zitchas** [comment]
Well, as far as extending things go, 1010todd on the discord posted this video of something that they developped. This is more projected firing points, but shows the sort of things we can do with ES.
https://user-images.githubusercontent.com/32169904/121829388-9a812580-cc7f-11eb-96ba-fabda465b738.mp4

**Comment by QuantumTux** [comment]
I suggest, as a starting point, that this functionality is added to the Asteroid Scanner outfit instead of creating a new outfit.

**Comment by bene-dictator** [comment]
Oh yeah, we forgot to close this when we added the functionality in #9398 and the outfit in #9621.

> I suggest, as a starting point, that this functionality is added to the Asteroid Scanner outfit instead of creating a new outfit.

Too late.
