### ISSUE TITLE
IF/ELSE IF evaluations for mission scripting conditions?

### ISSUE THREAD

**Issue by Expack3** [endless-sky/endless-sky#47]
I'm currently building a series of pre-war Republic cargo missions, and the first one starts by obtaining the PC's first civilian contract with the Republic Navy. I am planning on having the act of actually learning about the contract be split into two possibilities:

1. While in the spaceport of a Republic world, the player learns of a contract opportunity with one of the Navy's engineering squads on Chiron.
2. The player, not having heard of the opportunity already, learns of the opportunity from a sponsored hail while landing on Chiron.

What I want to be able to do is have the mission representing the player actually acquiring the contract have an "if/else if" evaluation in the "to offer" section. If the player accepted the contract in possibility 1, then the mission is offered; otherwise, the player has a random chance of being offered the mission. Furthermore, there would be different dialogue via branching so the player can actually decline the mission if this is their first time hearing of the contract opportunity. 

Does the mission scripting language support this kind of logic? The mission scripting documentation seems to say it doesn't.

**Comment by endless-sky** [comment]
I'm hoping eventually to allow arbitrary conditional expressions, but in the meantime, the easiest way to do this would be to have two different copies of the mission that is offered on Chiron, i.e.:

```bash
mission "Expack3 Navy 0"
    name "Visit Chiron"
    description "Meet up with ... on Chiron if you want to work for the Navy."
    source
        government Republic
        # Don't offer this mission on Chiron itself:
        near Chiron 1 100
    destination Chiron
    to offer
        random > 10
    on offer
        conversation
            ...

mission "Expack3 Navy 1A"
    landing
    name "Cargo for the Navy"
    description "..."
    source Chiron
    to offer
        has "Expack3 Navy 0: done"
    on offer
        conversation
            `Do you want to contact ...?`
            choice
                "    (Yes.)"
                    goto ...
                "    (Not right now.)"
                    defer
            ...
    on complete
        set "Expack3 did first mission"

mission "Expack3 Navy 1B"
    name "Cargo for the Navy"
    description "..."
    source Chiron
    to offer
        random > 10
        not "Expack3 Navy 0: done"
    on offer
        conversation
            `You receive a completely unexpected message from ...`
            ...
            choice
                "    (Accept the mission.)"
                    accept
                "    (Not right now.)"
            # Remember that you know this contact is here. This means that the
            # next time you land here, "Expack3 Navy 1A" will be offered.
            apply
                set "Expack3 Navy 0: offered"
                set "Expack3 Navy 0: done"
            `    You tell ... that you will contact them later.`
                defer
    on complete
        set "Expack3 did first mission"

mission "Expack3 Navy 2"
    to offer
        has "Expack3 did first mission"
        ...
    ...
```

Having two variants of the mission may seem messy, but since you were going to need two variants on the conversation anyways, it sort of makes sense. (Note that in cases where you do need to branch in a conversation based on conditions, the "branch" command allows that.)

**Comment by endless-sky** [comment]
I've added support (ca02eca) for hierarchical "and" / "or" expressions in mission conditions. The syntax looks like this:

```bash
to offer
    or
        has "Expack3 Navy 0: done"
        random < 10
```

This allows you to construct any arbitrary logical expression, including anything you could do with if / else. It's not quite as "user friendly" as a full programming language, but writing a parser for C-style logical expressions would have been much more difficult.
