### ISSUE TITLE
Idea: outfits that consume cargo (e.g. to repair your hull)

### ISSUE THREAD

**Issue by sanjayatio** [endless-sky/endless-sky#470]
There's an unused "hull repair rate" attribute for outfit.
Rather than an outfit, I think it makes more sense to implement it as a secondary weapon: repair consumes a limited number of alloy pellets.
A drone or a fighter would be the ideal users.

Unlikely to implement because of its impact on AI and weapon mechanics?

**Comment by Tufton** [comment]
This is why it's not good to have stuff split between here and forums.  Try
this, plugin and images attached:

outfit "Hull Repair Nano-Bots"
category "Systems"
cost 400000
thumbnail "outfit/medium fuel cell"
"mass" 40
"outfit space" -40
"shield generation" -.4
"hull repair rate" .6
"energy generation" -1
description "In a galaxy full of shields, armor repair has become more and
more marginalized.  However, for those that still cling to the old ways,
Tufton Robotics recently released an armor maintenance outfit for use on
space combat vessels, city maintenance crews, and your family hovercar.
The armor repair bots draw energy from any shield systems equipped on the
vessel, as well as placing a mild drain on any energy generation systems.
Most captains find the shied drain to be too inefficient for use on
shield-based vessels."

On Tue, Dec 15, 2015 at 6:41 PM, Sanjaya <notifications@github.com> wrote:

> There's an unused "hull repair rate" attribute for outfit.
> Rather than an outfit, I think it makes more sense to implement it as a
> secondary weapon: repair consumes a limited number of alloy pellets.
> A drone or a fighter would be the ideal users.
>
> Unlikely to implement because of its impact on AI and weapon mechanics?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/endless-sky/endless-sky/issues/470>.
>

# Copyright (c) 2015 by Christian Rhodes
#
# Endless Sky is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# Endless Sky is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.


shipyard "Lionheart Basics"
	"Scout"
	"Dagger"
	"Flivver"
	"Headhunter"
	"Raven"
	"Mule"
	"Monolith"
	"Tactical Assault Fighter"
	"Imperial Ironclad Battleship"
	"Imperial Ironclad Carrier"

shipyard "Lionheart Advanced"
	"Aerie"
	"Corvette"
	"Bactrian"
	"Monolith"	
	"Tactical Assault Fighter"
	"Imperial Ironclad Battleship"
	"Imperial Ironclad Carrier"
	
shipyard "Hai Intermediate"
	"Mite"
	"Aphid"
	"Lightning Bug"
	"Water Bug"

shipyard "Hai Advanced"
	"Mite"
	"Aphid"
	"Lightning Bug"
	"Water Bug"
	"Shield Beetle"
	"Arachnid"

outfitter "Deep Sky Advanced"
	"Ramscoop"
	"LP144a Battery Pack"
	"Beam Laser"
	"Laser Turret"
	"Heavy Laser"
	"M50-400 Slug"
	"Torpedo"
	"Hedgehog Ion Mine"
	"Hedgehog Ion Mine Launcher"
	"Hull Repair Nano-Bots"
	"D23-QP Shield Generator"
	"D41-HY Shield Generator"
	"LP288a Battery Pack"
	"LP576a Battery Pack"
	"nGVF-CC Fuel Cell"
	"nGVF-DD Fuel Cell"
	"NT-200 Nucleovoltaic"
	"Torpedo Launcher"
	"400mm Railgun"
	"Bighorn Energy Ram"
	"Plasma Gatling"
	"Tractor Beam Turret"
	"Heavy Laser Turret"
	"D67-TM Shield Generator"
	"D94-YV Shield Generator"
	"Security Station"
	"A120 Atomic Thruster"
	"A125 Atomic Steering"
	"A250 Atomic Thruster"
	"A255 Atomic Steering"
	"A370 Atomic Thruster"
	"A375 Atomic Steering"
	"A520 Atomic Thruster"
	"A525 Atomic Steering"
	"A860 Atomic Thruster"
	"A865 Atomic Steering"
	"Reverse Thruster"
	"Polaric Slide Thrusters"
	"Dwarf Core"

fleet "Large Hai"
	government "Hai"
	names "hai"
	cargo 3
	personality
		disables
	variant 2
		"Shield Beetle"
		"Lightning Bug (Pulse)" 2
		"Arachnid"
		"Mite" 7
	variant 2
		"Shield Beetle (Tracker)"
		"Lightning Bug" 2
	variant 1
		"Shield Beetle"
		"Lightning Bug (Pulse)"
		"Aphid" 4
	variant 1
		"Shield Beetle (Tracker)"
		"Lightning Bug"
		"Aphid (Anti-Missile)" 4
		"Arachnid"
		"Mite" 7
	variant 3
		"Shield Beetle"
		"Lightning Bug (Pulse)"
		"Water Bug"
		"Water Bug (Pulse)"
	variant 3
		"Shield Beetle"
		"Water Bug"
		"Water Bug (Pulse)"
	variant 3
		"Shield Beetle (Tracker)"
		"Lightning Bug" 2
		"Water Bug"
	variant 3
		"Shield Beetle (Tracker)"
		"Water Bug" 3
		"Arachnid"
		"Mite" 7

outfit "M50-400 Slug"
	category "Ammunition"
	cost 1000
	thumbnail "outfit/unknown"
	"torpedo capacity" -1
	description "400mm Railgun Slug"

outfit "400mm Railgun"
	category "Guns"
	cost 2490000
	thumbnail "outfit/pulse cannon"
	"mass" 60
	"outfit space" -60
	"weapon capacity" -60
	"gun ports" -1
	"drag" 1
	"torpedo capacity" 50
	weapon
		sprite "projectile/tracker"
			"frame rate" 18
			"random start frame"
		sound "torpedo"
		icon "icon/tracker"
		ammo "M50-400 Slug"
		"die effect" "tiny explosion"
		"hit effect" "large explosion"
		"inaccuracy" 3
		"velocity" 30
		"lifetime" 130
		"reload" 100
		"firing energy" 480
		"firing heat" 20
		"turn" 0
		"homing" 0
		"firing force" 80
		"shield damage" 700
		"hull damage" 800
		"hit force" 450
		"missile strength" 500
	description "The 400mm Railgun is a modern marvel.  Using advanced Neodynium-alloy electromagnets, the Railgun hurls an M50-400 depleted Uranium slug at near relativistic speeds almost 4000 kilometers towards the intended target using quantum computer-enhanced targeting algorithms.  The size of these guns necessitates a long reload time, while the electromagnets consume a significant amount of a ship's energy with every shot fired.""

outfit "Plasma Gatling"
	category "Guns"
	cost 410000
	thumbnail "outfit/unknown"
	"mass" 40
	"outfit space" -40
	"weapon capacity" -40
	"gun ports" -1
	"heat generation" 15
	weapon
		sprite "projectile/grab-strike"
			"frame rate" 25
			"random start frame"
		sound "particle"
		"hit effect" "grab-strike impact"
		"die effect" "grab-strike impact"
		"inaccuracy" 13
		"velocity" 7
		"acceleration" -.05
		"lifetime" 90
		"reload" 5
		"firing energy" 10
		"firing heat" 180
		"turn" 0
		"homing" 0
		"firing force" 0
		"shield damage" 45
		"hull damage" 20
		"heat damage" 55
		"hit force" 0
		"missile strength" 0
	description "The Plasma Gatling is designed to eviscerate your enemies with a hail of superheated plasma singularities.  As a trade-off, the integrated particle hyperaccelerator puts a significant strain on your ship's cooling systems."

ship "Monolith"
	sprite "ship/monolith"
	attributes
		category "Heavy Warship"
		"cost" 68000000
		"shields" 78400
		"hull" 48300
		"required crew" 459
		"bunks" 889
		"mass" 4110
		"drag" 49.7
		"energy generation" -24.5
		"heat dissipation" .25
		"heat generation" 3
		"fuel capacity" 900
		"cargo space" 720
		"outfit space" 1560
		"weapon capacity" 480
		"engine capacity" 300
		weapon
			"blast radius" 800
			"shield damage" 8000
			"hull damage" 2000
			"hit force" 11000
	outfits
		"Particle Cannon" 2
		"Heavy Anti-Missile Turret" 4
		"Plasma Turret" 4
		"Armageddon Core" 2
		"LP576a Battery Pack" 2
		"D94-YV Shield Generator" 4
		"Liquid Helium Cooler" 1
		"A860 Atomic Thruster"
		"A865 Atomic Steering"
		"Scram Drive"
		"Ionic Afterburner"
		
	engine -34 284
	engine 34 284
	gun -60 -126 "Particle Cannon"
	gun 60 -126 "Particle Cannon"
	turret 0 50 "Plasma Turret"
	turret 0 -60 "Plasma Turret"
	turret 0 -120 "Plasma Turret"
	turret 0 120 "Plasma Turret"
	turret 0 15 "Heavy Anti-Missile Turret"
	turret 0 -114 "Heavy Anti-Missile Turret"
	turret 0 157 "Heavy Anti-Missile Turret"
	turret 0 103 "Heavy Anti-Missile Turret"
	fighter -25 -166 
	fighter 25 -166 
	fighter -16 -176 
	fighter 16 -176 
	fighter -37 -65
	fighter 37 -65
	fighter -46 40
	fighter 46 40
	fighter -72 -46
	fighter 72 -46
	explode "tiny explosion" 50
	explode "small explosion" 45
	explode "medium explosion" 50
	explode "big explosion" 40
	explode "huge explosion" 35
	description "The Monolith, the culmination of nearly a century of tireless research and construction. Rebuilt from the frame up using the colossal burnt out husk of an ancient unknown vessel found drifting along the outskirts of the Deep, the Monolith is the largest human spacefaring vessel ever constructed.  Nothing is known about the origins of the ancient ship, except a single panel bearing an alien script that almost appears to read "ACP"."

ship "Tactical Assault Fighter"
	sprite "ship/taf"
	attributes
		category "Fighter"
		"cost" 1900000
		"shields" 2000
		"hull" 1400
		"required crew" 1
		"bunks" 3
		"mass" 200
		"drag" 1.6
		"heat dissipation" .9
		"fuel capacity" 0
		"cargo space" 0
		"outfit space" 175
		"weapon capacity" 50
		"engine capacity" 60
		weapon
			"blast radius" 24
			"shield damage" 240
			"hull damage" 120
			"hit force" 360
	outfits
		"Energy Blaster" 3
		"Anti-Missile Turret" 1
		
		"nGVF-CC Fuel Cell"
		"LP036a Battery Pack"
		"D14-RN Shield Generator"
		
		"X2700 Ion Thruster"
		"X2200 Ion Steering"
		
	engine -17 35
	engine 17 35
	gun -10 -26
	gun 10 -26
	gun -16 -20
	turret 16 -20
	explode "tiny explosion" 10
	explode "small explosion" 20
	description "The Tactical Assault Fighter is a specially designed Fighter/Interceptor for deployment in Capital-class fighter bays.  With speed, defenses, and armament equivalent to a hyperspace capable Interceptor-class starship, the TAF is a powerful complement to any fleet and a stalwart protector of the lumbering Capital-class behemoths.""

outfit "Tractor Beam Turret"
	category "Turrets"
	cost 1050000
	thumbnail "outfit/electron turret"
	"mass" 60
	"outfit space" -60
	"weapon capacity" -60
	"turret mounts" -1
	"required crew" 1
	weapon
		sprite "projectile/2x electron"
			"frame rate" 60
		sound "heavy_laser"
		"hit effect" "electron impact"
		"inaccuracy" 3
		"velocity" 450
		"lifetime" 1
		"reload" 1
		"firing energy" 8.0
		"firing heat" 5.2
		"shield damage" 1.0
		"hull damage" .5
		"hit force" -40
	description "TRACTOR PLACEHOLDER"

outfit "Bighorn Energy Ram"
	category "Guns"
	cost 4050000
	thumbnail "outfit/unknown"
	"mass" 90
	"outfit space" -90
	"weapon capacity" -90
	"gun ports" -2
	"required crew" 1
	weapon
		sprite "projectile/ram"
			"frame rate" 1
		sound "laser"
		"hit effect" "beam laser impact"
		"inaccuracy" 0
		"velocity" 90
		"lifetime" 1
		"reload" 1
		"firing energy" 25.0
		"firing heat" 10.2
		"firing force" 10
		"shield damage" 200.0
		"hull damage" 200
		"hit force" 160
	description "The Bighorn Energy Ram is the largest energy-based mass displacement device on the market.  Originally designed to be mounted at the head of deep-core planet mining drills, the Bighorn has been haphazardly adapted for ship to ship combat. However, due to its mass it cannot be mounted on anything smaller than a Light Warship.  Requires 2 gun slots to accomodate the Modular Oppositional Underslung Nuclear Transipositors or M.O.U.N.T, for short.  Keeping the Bighorn ignited requires a massive amount of energy, so the wielder only has a small window to strike his intended target.  Try to make it count."

ship "Imperial Ironclad Battleship"
	sprite "ship/imperialbattleship"
	attributes
		category "Heavy Warship"
		"cost" 8500000
		"hull" 38700
		"required crew" 114
		"bunks" 172
		"mass" 4940
		"drag" 28.8
		"heat dissipation" .3
		"fuel capacity" 900
		"cargo space" 50
		"outfit space" 800
		"weapon capacity" 300
		"engine capacity" 292
		"energy generation" -.4
		"shield generation" .8
		"shield damage" 1000
		"hull repair rate" 1.6
		"heat generation" 5
		"energy capacity" 3000
		weapon
			"blast radius" 300
			"shield damage" 1200
			"hull damage" 600
			"hit force" 1800
	outfits
		"Quad Blaster Turret" 3
		"Heavy Laser" 2
		"Heavy Anti-Missile Turret" 2
		"LP288a Battery Pack"
		"Fission Reactor" 2
		"Hyperdrive"
		"Afterburner"
		"Tyrant Plasma Thruster"
		"Orca Plasma Steering"

	engine -11 68
	engine 11 68
	gun -20 -150 "Heavy Laser"
	gun 20 -150 "Heavy Laser"
	turret -10 -150 "Quad Blaster Turret"
	turret 10 -150 "Quad Blaster Turret"
	turret 0 -50 "Quad Blaster Turret"
	turret -15 -35 "Heavy Anti-Missile Turret"
	turret 15 -35 "Heavy Anti-Missile Turret"
	explode "small explosion" 25
	explode "medium explosion" 30
	explode "big explosion" 20
	explode "huge explosion" 10
	description "An ancient warship that last saw active service as the flagship of the Imperium of Mankind's main battle fleet in the first human Hyperspace Wars.At this point in human history, shields had not yet been invented, so this battleship relied on thick ablative Nano-Mesh(tm) armor plating to survive the primitive blasts of early human space weaponry.  Modern iterations of this ship include a unique on-board army of repair nano-bots that constantly maintain the vessel's armor.  As an unfortunate side effect of its dated design, the ironclad's subsystems produce an interfering gluon particle wave emission that renders the battleship incapable of utilizing any sort of energy shield, modern or otherwise"

outfit "Hull Repair Nano-Bots"
	category "Systems"
	cost 400000
	thumbnail "outfit/medium fuel cell"
	"mass" 40
	"outfit space" -40
	"shield generation" -.4
	"hull repair rate" .6
	"energy generation" -1
	description "In a galaxy full of shields, armor repair has become more and more marginalized.  However, for those that still cling to the old ways, Tufton Robotics recently released an armor maintenance outfit for use on space combat vessels, city maintenance crews, and your family hovercar.  The armor repair bots draw energy from any shield systems equipped on the vessel, as well as placing a mild drain on any energy generation systems.  Most captains find the shied drain to be too inefficient for use on shield-based vessels."

ship "Imperial Ironclad Carrier"
	sprite "ship/imperial"
	attributes
		category "Heavy Warship"
		"cost" 6500000
		"hull" 29700
		"required crew" 129
		"bunks" 199
		"mass" 2540
		"drag" 20.8
		"heat dissipation" .3
		"fuel capacity" 700
		"cargo space" 100
		"outfit space" 720
		"weapon capacity" 230
		"engine capacity" 238
		"energy generation" -.4
		"shield generation" .8
		"shield damage" 1000
		"hull repair rate" 1.2
		"heat generation" 5
		"energy capacity" 3000
		weapon
			"blast radius" 300
			"shield damage" 1200
			"hull damage" 600
			"hit force" 1800
	outfits
		"Heavy Anti-Missile Turret" 2
		"Laser Turret" 2
		"Fission Reactor"
		"LP288a Battery Pack"
		"Water Coolant System" 2
		"Afterburner"
		"Orca Plasma Thruster"
		"Tyrant Plasma Steering"
		"Hyperdrive"
		
	engine -35 200
	engine 35 200
	turret -16 -176 "Laser Turret"
	turret 16 -176 "Laser Turret"
	turret 0 157 "Heavy Anti-Missile Turret"
	turret 0 103 "Heavy Anti-Missile Turret"
	fighter -37 -65
	fighter 37 -65
	fighter -46 40
	fighter 46 40
	fighter -72 -46
	fighter 72 -46
	fighter -101 57
	fighter 101 57
	fighter -74 57
	fighter 74 57
	explode "tiny explosion" 20
	explode "small explosion" 45
	explode "medium explosion" 50
	explode "big explosion" 40
	explode "huge explosion" 10
	description "An ancient warship that last saw active service as a mobile fighter platform for the Imperium of Mankind's main battle fleet in the first human Hyperspace Wars. At this point in human history, shields had not yet been invented, so this battleship relied on thick ablative Nano-Mesh(tm) armor plating to survive.  Modern iterations of this ship include a unique on-board army of repair nano-bots that constantly maintain the vessel's armor.  As an unfortunate side effect of its dated design, the ironclad's subsystems produce an interfering gluon particle wave emission that renders the carrier incapable of utilizing any sort of energy shield, modern or otherwise.  Designed to remain in the back lines and influence the course of a battle through fighter superiority, the Imperial Carrier sports less armor and fewer weapons than its battleship bretheren."

outfit "Hedgehog Ion Mine"
	category "Ammunition"
	cost 1400
	thumbnail "outfit/medium shield"
	"torpedo capacity" -1
	description "Hedgehog Ion Mines are ammunition for the Hedgehog Ion Mine Launcher."

outfit "Hedgehog Ion Mine Launcher"
	category "Secondary Weapons"
	cost 110000
	thumbnail "outfit/torpedo launcher"
	"mass" 50
	"outfit space" -50
	"weapon capacity" -50
	"gun ports" -1
	"torpedo capacity" 30
	weapon
		sprite "projectile/seeker"
			"frame rate" 16
			"random start frame"
		sound "torpedo"
		ammo "Hedgehog Ion Mine"
		icon "icon/torpedo"
		"fire effect" "torpedo fire"
		"hit effect" "big explosion"
		"die effect" "tiny explosion"
		"inaccuracy" 4
		"velocity" -10
		"acceleration" 1
		"lifetime" 800
		"reload" 120
		"firing energy" 2
		"firing heat" 45
		"drag" .2
		"turn" 20
		"homing" 2
		"ion damage" 6
		"shield damage" 280
		"hull damage" 340
		"hit force" 100
		"missile strength" 25
	description "Hedgehog Ion Mines are powerful tools to "dissuade" any pursuers from continuing the chase."

outfit "Polaric Slide Thrusters"
	category "Engines"
	"cost" 10000000
	thumbnail "outfit/unknown"
	"mass" 170
	"outfit space" -130
	"engine capacity" -100
	"weapon capacity" -30
	"drag" 30
	"thrust" 210
	"thrusting energy" 20
	"thrusting heat" 25
	"reverse thrust" 170
	"reverse thrusting energy" 20
	"reverse thrusting heat" 25
	"flare sprite" "effect/medium graviton flare"
	description "The Polaric Slide Thruster may appear to be a normal engine, but it is in fact moving the fabric of spacetime itself around your vessel through means unknown"

^Need some way to remove momentum

ship "Mite"
	sprite "ship/hai mite"
	attributes
		category "Fighter"
		"cost" 29000
		"shields" 1200
		"hull" 200
		"required crew" 1
		"bunks" 1
		"mass" 45
		"drag" 2.13
		"heat dissipation" .9
		"outfit space" 137
		"weapon capacity" 26
		"engine capacity" 38
		weapon
			"blast radius" 12
			"shield damage" 120
			"hull damage" 60
			"hit force" 180
	outfits
		"Water Coolant System"
		"Pulse Cannon" 2
		"RT-I Radiothermal"
		"Supercapacitor" 3
		"S-270 Regenerator"
		"A120 Atomic Thruster"
		"A125 Atomic Steering"
		
	engine -15 30
	engine 15 30
	gun -14 -10 "Pulse Cannon"
	gun 14 -10 "Pulse Cannon"
	explode "tiny explosion" 15
	explode "small explosion" 5
	description "The Mite is a point defense fighter developed by the Hai for protecting conveys and large warships."

ship "Arachnid"
	sprite "ship/hai arachnid"
	attributes
		category "Heavy Warship"
		"cost" 15200000
		"shields" 33400
		"hull" 7300
		"required crew" 151
		"bunks" 238
		"mass" 1110
		"drag" 21
		"heat dissipation" .4
		"fuel capacity" 700
		"cargo space" 150
		"outfit space" 720
		"weapon capacity" 250
		"engine capacity" 160
		weapon
			"blast radius" 400
			"shield damage" 3500
			"hull damage" 1800
			"hit force" 5000
	outfits
		"Pulse Cannon" 2
		"Hai Tracker Pod" 4
		"Hai Tracker" 224
		"Pulse Turret" 2
		"Heavy Anti-Missile Turret" 2
		
		"Fusion Reactor"
		"Fission Reactor"
		"LP288a Battery Pack"
		"S-970 Regenerator"
		"Cooling Ducts" 4
		
		"A520 Atomic Thruster"
		"A525 Atomic Steering"
		"Hyperdrive"
		
	engine -44 125
	engine 44 125
	gun -16 -176 "Pulse Cannon"
	gun 16 -176 "Pulse Cannon"
	gun -25 -166 "Hai Tracker Pod"
	gun 25 -166 "Hai Tracker Pod"
	gun -16 -176 "Hai Tracker Pod"
	gun 16 -176 "Hai Tracker Pod"
	turret 0 15 "Pulse Turret"
	turret 0 -114 "Pulse Turret"
	turret 0 157 "Heavy Anti-Missile Turret"
	turret 0 103 "Heavy Anti-Missile Turret"
	fighter -37 -65
	fighter 37 -65
	fighter -46 40
	fighter 46 40
	fighter -72 -46
	fighter 72 -46
	fighter -101 57
	explode "tiny explosion" 20
	explode "small explosion" 45
	explode "medium explosion" 50
	explode "big explosion" 40
	explode "huge explosion" 15
	description "The Arachnid is a Hai Carrier designed to keep Hai freighter convoys protected from massed small ship attacks that would ordinarily overwhelm the slower or smaller Hai vessels.

**Comment by sanjayatio** [comment]
I've read about yours before posting mine.
Maybe I should rephrase my first sentence to:
There's an unused "hull repair rate" attribute for outfit **in the core game**.

Switching gear to comment on yours:
Ships have more shield than hull, and with the shield regen easily exceed 100 your shield tax is negligible.
Meanwhile, the outfit space totally exclude small ships; putting a wider margin between ships with spaces to spare and the compact ones.
Imho it should also produce a lot of heat during operation.

**Back to my idea: forget about it** -- the ammo will require lots of changes in game mechanics.
There's a new config to manage how a ship spend its ammo.
However, in the context of repair, ships are not equal. User will expect more control for this feature.

Before closing the curtain, picture this:
- one of your shield beetle is in a dire state
- you give your "fighters" and repair drones the command to "attack" it.
- they swarm around the beetle (say because the welder has a maximum range of 100).
- suddenly a pirate jump in and shoot it down.
- when the beetle blows, it takes the swarm with it.

**Comment by bobafetthotmail** [comment]
"Back to my idea: forget about it -- the ammo will require lots of changes in game mechanics."

Missiles have ammo. Also using missiles would take care of the issue you pictured.
You aren't sending killable and expensive drones but "ship-fixing missiles" with nanobots and magic unicorns that on contact fix the hull by a specified amount. If the ship gets nuked, you have lost some missiles, not the ship fixing teams.

What is an open question (since I didn't have time to look at it for now) is if the game handles a secondary weapon that shoots on friendlies without enraging them, a weapon that bypasses shields and deals negative hull damage (so it can cure hull instead of damaging it), and if that can be done by AI ships on their own too or if I need to do that manually from my flagship.

**Comment by endless-sky** [comment]
I don't see enough of a need for this to warrant a game engine change. There's other ways to make hull-repair outfits "costly" - e.g. having them consume a lot of energy - without also needing to consume ammunition or cargo.
