### ISSUE TITLE
Gun mentioned in Intro mission for shuttle craft

### ISSUE THREAD

**Issue by diggorygray** [endless-sky/endless-sky#4707]
In the Intro mission "Intro [2 Transport]", removing the gun on your ship is mentioned.
But the stock shuttle has now gun.

Text from "intro missions.txt" :

"Great," he says. "This is Chuck, and Sarah, and their son Carl. Let's help them carry their luggage to your ship." As you begin walking back, slightly ahead of them, James whispers to you, "Tourists are always a good way to make money. They're on vacation, so they don't mind paying a bit extra. But no point in your cargo space going to waste, so take a look at the job board and see if there are any delivery missions we can run at the same time. **And if you want to be a little safer should we come across any pirates, sell off your gun.** It might seem counterintuitive, but being unarmed makes you less of a target to pirates if there are others in the system that they could be defending themselves against."`

**To Reproduce**
1. Start a new pilot, choosing a shuttle craft
2. Accept the intro missions.
3. When reaching the point of the transport family from 'New China' you'll see the gun refance.

**Expected behavior**
Either no mention of a gun, or mention not arming a small ships with guns or the stock armament of a shuttle to include a blaster.
 
**Screenshots**

**System (please complete the following information):**
 - OS: Mint Linux 19.2
 - Game Source: self-compiled
 - Version: commit hash 409c9af

**Comment by Zitchas** [comment]
Just to clarify, you are pointing out that the stock shuttle currently does not have a gun, and thus it does not make sense that James tells you to sell your gun, right?

So we should either:
a) give the shuttle a blaster again,
b) change the dialogue so that James is recommending that you do not buy a gun, or
c) remove that part of the dialogue entirely.

Personally, A or B would be much better than C.

**Comment by diggorygray** [comment]
That is the issue in a nutshell :).

**Comment by diggorygray** [comment]
Yes option C removes some of the richness of the game.

**Comment by Zitchas** [comment]
OK, we now have two PRs for fixing this. One for option A, one for option B. I'll close whichever of the two isn't accepted.

**Comment by diggorygray** [comment]
Great, thanks.

**Comment by Zitchas** [comment]
Your welcome. Thanks for filing an issue for it.
