### ISSUE TITLE
Can't turn when moving at a certain speed forward

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#471]

**Comment by endless-sky** [comment]
Can you explain what you mean by this? Do you mean you cannot accelerate sideway, or do you mean that your ship literally will not turn? Are you sure that your ship has enough energy production to turn and thrust simultaneously, and that you are not holding down any keys that ghost your turn keys?

**Comment by thenerdfreak** [comment]
For example, my clipper has atomic thrusters and plasma turning, it will go straight and it will turn, but not at the same time (even when I set it to land, it looks like the thrusters are flipping on and off rapidly)

**Comment by thenerdfreak** [comment]
I can go straight forward and fire lasers and rockets at the same time (computer is updating so can't really say for energy use) and it doesn't make me run out of power

**Comment by endless-sky** [comment]
Well, wait and check your energy use and the ghosting, but flickering engines is a sure sign of not enough energy production.

**Comment by thenerdfreak** [comment]
I actually have TOO much power, as moving forward and firing lasers doesn't even affect the energy consumption, nor does turning and firing lasers. I simply can not turn, want me to paste my ships info from the save file?

**Comment by endless-sky** [comment]
Sure, go ahead and paste the ship info.

**Comment by thenerdfreak** [comment]
ship Clipper
	name Mindsludge
	sprite ship/clipper
	attributes
		category "Light Freighter"
		bunks 9
		"cargo space" 70
		cost 900000
		drag 3.7
		"engine capacity" 80
		"fuel capacity" 500
		"gun ports" 4
		"heat dissipation" 0.8
		hull 800
		mass 150
		"outfit space" 260
		"required crew" 3
		shields 2700
		"weapon capacity" 60
	outfits
		"Impala Plasma Steering"
		"A250 Atomic Thruster"
		"Mass Expansion" 3
		"RT-I Radiothermal"
		"Bunk Room" 5
		"D23-QP Shield Generator"
		"Laser Rifle" 25
		"Beam Laser" 2
		"Heavy Rocket Launcher" 2
		"Heavy Rocket" 40
	crew 27
	fuel 500
	shields 2700
	hull 800
	position 343.85171 -287.3587
	engine -20 45
	engine 20 45
	gun -12 -7 "Beam Laser"
	gun 12 -7 "Beam Laser"
	gun -23 -19 "Heavy Rocket Launcher"
	gun 23 -19 "Heavy Rocket Launcher"
	explode "medium explosion" 10
	explode "tiny explosion" 15
	explode "small explosion" 20

**Comment by endless-sky** [comment]
Take a look at the energy use table for your ship - turning and thrusting
simultaneously would take 282 energy per second, and you only produce 264.

Your lasers, on the other hand, only take 30 energy per second each, and
the rockets take basically no energy, so you can fire all of them and the
thrusters continuously (186 + 2 * 30 + 2 * .3 = 246.6 < 264).

**Comment by thenerdfreak** [comment]
Ah, thought the energy bar would show every usage?

**Comment by endless-sky** [comment]
Not if you have no batteries. The energy bar shows your stored energy as a
percent of your capacity; if your energy capacity is 0, it always shows
100%.

**Comment by thenerdfreak** [comment]
ah, maybe ships themselves should  store very little energy so that you can tell when you're running out?

**Comment by thenerdfreak** [comment]
Or maybe the generators should have a small % of storage

**Comment by erprice** [comment]
If you want a tiny amount of energy, buy a 2 ton supercapacitor. I think the best solution would be to make it visually obvious that you have no stored energy.

It's hard to gray out the energy bar since it is already gray. Perhaps some cross-hatching would do the trick.
