### ISSUE TITLE
Don't skip important mission popups when holding return

### ISSUE THREAD

**Issue by SubstandardZeal** [endless-sky/endless-sky#4718]
**Problem:** When I land on a station with a lot of outstanding missions, there are a lot of dialogue boxes to click through. I like to hold return to skip through them as fast as possible.

However, there are sometimes story/important mission dialogues (the big ones on the left-hand side of the screen) which popup after skipping the regular mission dialogues. If I am holding return, the game skips right through the dialogue without letting me view them.

**Solution:** I suggest the game not allow these important dialogues to be skipped (while holding return) without an additional press of the return key. This would give the player time to notice the new important dialogue and if they still wish to skip through *every* mission in the game, they may quickly press and hold return again.

Alternatively perhaps an easy way to review or re-issue these dialogues would work.

**Comment by jafdy** [comment]
The large boxes use the conversation keyword rather than the dialog keyword, I see no reason to not make the change although I do not know how hard it would be.

**Comment by Amazinite** [comment]
I think a better solution would be to collapse payment dialogs into a single box as to avoid the need to ever hold return in the first place, which was mentioned in #4592.

**Comment by tehhowch** [comment]
@SubstandardZeal with #4592 merged, please re-visit this topic and determine if it is ready to be closed.

**Comment by Amazinite** [comment]
#4592 only condensed on visit dialogs, whereas OP’s problem would be better fixed by condensing on complete dialogs.

**Comment by tehhowch** [comment]
Probably the simplest fix is to require a new press in the Conversation Panel in order to select a choice or close the panel
