### ISSUE TITLE
No witness, No effect

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#472]
When you destroy/ capture a ship in a system that has no other allies/ ships of the same nation/faction as that ship in the system, your reputation shouldn't really have any negative actions towards it, as nobody seen you commit the crime

**Comment by thenerdfreak** [comment]
And the "distress signal" scenario can't really be played in this situation, as their distress beacons would have to be super-hightech to be able to go from one galaxy to another, even through hyperlinks, more expensive than a hyperdrive most likely

**Comment by brick96** [comment]
We can communicate through hyper links. Example: the start of the pug story where you try to talk with someone from rand but are cut off, trying to get there is impossible without a jumpdrive

**Comment by thenerdfreak** [comment]
Then the free worlds missions where you have to collect information based on pirate movements and report them back to the planet are unnecessary, since why can't you just call them up at tell them. Note that all messages you receive are when you LAND, meaning the communication device is on the PLANET, not the ship

**Comment by Tufton** [comment]
Also in most sci fi communication can be achieved at faster than light
speeds.  Frankly if you can shoot a gigantic spaceship hurtling through
space and time at beyond relativistic speed, you could easily do the same
with a series of 1s and 0s (or dots and dashes if that feels more familiar)

As for the FW mission, if you want to argue hard science semantics, you
could just say the pirate fleet movement data was too large of a file to
transmit over whatever communication method exists OR that it was too
sensitive to not be delivered in person.  NSA spying on us and all that.

But the final and most important point, is that really it's just the most
convenient for gameplay purposes.  Otherwise you could basically run amok
with little to no repercussions (which are pretty light as is)

**Comment by frameworld** [comment]
Perhaps, if you don't own the communicators, you may only send a bit now and then without it getting noticed.
That is one and the only good explanation of why a transmission is limited such harshly when you can have internet-phones between governments all the time.

**Comment by johndh** [comment]
Most of the time it seems like there either isn't FTL communication in ES or there's a good reason not to use it.  Some missions have you traveling for over a week just to meet with somebody in person.  Banking seems to occur instantly across the universe, but that seems to just be an abstraction.  Thus, the incident @brick96 refers to seems out of place.  If FTL communication exists, why isn't it used?  Perhaps encryption hasn't kept up with code breaking technology, or maybe the equipment takes up so much space or draws so much power that it can't be practically set up on a normal ship.  Regardless, some kind of in-universe mention would be nice, or else a retcon.

**Comment by sanjayatio** [comment]
Did you do the early FW recon missions?
Rather, have you ever heard about a black box in planes?
Your ship logs (a.k.a black box) is the witness.

**Comment by thenerdfreak** [comment]
But if you capture the ship, YOU HAVE the witness :p so how will the other people have it. And johndh pretty much smartified what I said. The equipment would be too big to fit on a ship, since only planets seem to be communicating with each other outside of a system

**Comment by sanjayatio** [comment]
Consider: 
You go overseas and a immigration officer would check your passport.
You enter a space port, the immigration officer scans your ship logs.
Check that FW recon mission as a reference - people can harvest info about every ship you encountered. Shooting on one (&/ being shot) is more than just an encounter.

However, in the end of the day, this is a game; everything doesn't have to make sense (for everyone).

**Comment by endless-sky** [comment]
The game isn't too consistent on how difficult system-to-system communication is, but the cases where only one ship of a given government is in a system are rare enough that it doesn't make sense to complicate the game engine just to make those ships unable to report your attack on them.
