### ISSUE TITLE
Allow missions to override navigation and in-flight controls.

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4720]
**Is your feature request related to a problem? Please describe.**
This is a request to allow missions to control navigation and to control the players spaceship in flight.

Examples of missions that could benefit from this:
- "Your hyperdrive suddenly went out of control" type of stories could use this to make the players ship makes some hyperspace jumps before returning (in-flight) controls to the player
- A mission like "Shady passenger transport 3 - double cross" could use this to let the hijackers fly the players ship to their desired destination
- The intro missions might use this to let James fly the ship instead of the player (if the player wants to have a demo on how to fly).

**Related Issue Links**
PR #4715 allows for more easy adding of new types of flight-control-inputs; one possible new control-input would be to have missions provide control inputs.
PR #4370 requires this type of in-flight controls override for automatic tests; it would probably use the same syntax as the feature described in this feature request.

**Describe the solution you'd like**
A mission can already trigger a launch of the players ship. We could add a section under launch (or under a different keyword) that contains instructions for:
- navigation (set destination system, set destination planet)
- setting (AI) behaviours on the entity controlling the players spaceship
- directly controlling the player spaceship using basic command inputs (turn left/right/jump/land)
- directly controlling the player spaceship using higher-level commands (turn to ... angle, kill enemies, ...)

Controls inputs could only be given until the next landing, on landing a next mission could trigger though (with possibly new automated controls). If the inputs result in the ship just flying around in some system, then controls are returned to the player at that point.

An On-Enter mission trigger would not trigger until the automated controls are done (and might not trigger at all if the end-result of the flight is landing).

**Describe alternatives you've considered**
Just implementing a subset of this feature ("only navigation and AI behaviour controls" or "only basic direct controls") could already be valuable for some game-content.

**Additional context**
Automatic control of the players ship can be tricky; I would expect mission writers to only use this type of override when the starting, intermediate and end-systems are well known. A mission writer wouldn't want to accidentally send a player through unknown hostile territory.

Please do provide feedback if you have any relevant feedback. Is this a feature which you would like to use in stories that you write? If so, then which controls would you like to have?

**Comment by Zitchas** [comment]
Hmmm... As content creators we'd have to be very careful with this. I could see players getting very frustrated with this.

That being said, especially for navy missions, having the mission take control of hyperspace navigation and hyperjumping might make for a very immersive experience. Player controls ship actions, the admiral in charge of the fleet controls where and when we hyperjump. 

More "hired escort" type escort missions would also be possible for this. Current escort missions are more along the lines of " the player is hired to lead a caravan of merchants to xyz". If the mission takes control of navigation, then we could have missions where the player has been hired to follow the target ship around and protect them, instead of being given leadership over the group.

Could be very useful.

**Comment by petervdmeer** [comment]
I'm closing this ticket: teleport and allowing time to pass in missions could achieve almost the same as overriding the controls, but there is a bit of randomness during flight (eg Bounty Hunters suddenly attacking), so teleport and passing of time in missions is more reliable.

**Comment by TheGiraffe3** [comment]
Wait, you can teleport and make time pass?

**Comment by petervdmeer** [comment]
> Wait, you can teleport and make time pass?

Not yet, #6018 is still open. But I know that some people already tried to work on that.

**Comment by Saugia** [comment]
https://github.com/endless-sky/endless-sky/pull/7348 is the most recent attempt I believe.
