### ISSUE TITLE
No ambient sounds play in 0.9.10 installed on OS X from steam

### ISSUE THREAD

**Issue by dfrankow** [endless-sky/endless-sky#4722]
**Describe the bug**
No music or ambient sound for any play screen.

**To Reproduce**
1. Install Endless Sky from Steam.
2. Start play. There are is no music or ambient sound on the start screen, in a solar system, on a planet. There is a "thruster" noise when hyperjumping, so audio is not broken for me.

**Expected behavior**
I expect each of those screens to have ambient music of some sort.

**System (please complete the following information):**
 - OS: OS X 10.14.6
 - Game Source: Steam
 - Version: 0.9.10 (beta)

**Additional context**
Chatted about this here: https://github.com/endless-sky/endless-sky/issues/3594#issuecomment-568553863.

Someone said: 

- Ambient sounds are currently only used on stations. 6d91347
- All systems and planets are able to play music. bb3f922

**Comment by Amazinite** [comment]
> There are is no music or ambient sound on the start screen, in a solar system, on a planet. 

Because those simply aren't implemented yet. There's no reason to have a separate issue from #3594.
