### ISSUE TITLE
Ships with scanners will build up over time in busy systems

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4723]
**Describe the bug**
If a ship has a scanner, it will attempt to scan any ship that has not yet been scanned by its government before it does anything else. In high traffic systems where new ships are always entering, this causes ships with scanners to always be trying to scan a ship. As time goes on and more ships with scanners enter the system, they built up to large numbers.

**To Reproduce**
1. Enter Sol and wait for a while.
2. Observe how the number of Gunboats increases over time and they rarely leave.

**Expected behavior**
Ships with scanners should either not attempt to scan a ship that an ally is also attempting to scan, or ships with scanners should only scan a limited number of ships, at which point they then no longer scan any ships in the system.

**Screenshots**
Here's an image of nearly 20 Gunboats in Sol with less than 15 other ships, after having waited in Sol for 5 to 10 minutes.
![image](https://media.discordapp.net/attachments/536900466655887360/659438947092398130/unknown.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Self-compiled
 - Version: Up to date as of this issue (6d775e5).

**Comment by warp-core** [comment]
#7229 might be able to help with this.

**Comment by Amazinite** [comment]
#9714 adds a time and scan count limit to ships with scanners so that they eventually quit scanning and leave the system.
