### ISSUE TITLE
"Returning Home" presumes the player ship to be non-Hai

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4726]
**Describe the bug**
In the mission Returning Home, Elliot says that "your ship looks newer than most of the ships that humans fly around here", which doesn't make much sense if the player is using a non-human ship (considering the mission is offered in Hai space, it is quite likely)

**To Reproduce**
1. Buy a Hai ship
2. Spam spaceport on a Hai planet until the mission Returning Home is offered

**Expected behavior**
The mission shouldn't mention the player's current ship

**Screenshots**
![Screenshot (677)](https://user-images.githubusercontent.com/45330165/71577115-29819880-2af3-11ea-96cb-9097801f107d.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github
 - Version: 0.9.10

**Comment by Zitchas** [comment]
Just to nitpick a little, an alien ship *can* look newer than other ships. It is somewhat odd that they'd comment on it looking newer instead of looking alien, but still possible.

That being said, someday I hope we'll be able to use ship conditions to create branches to differentiate between different factions/types of ships and make things like this more interesting. Considering that the ship is basically the companion character to the player...

**Comment by beccabunny** [comment]
Yes, but if you have a new Hai ship, the current text would tell you that Elliot could presume you came from outside of Hai space because you have new Hai ship...

**Comment by tukoz** [comment]
I always presumed Elliot said that because he's not too much in that (i.e. ships), and that ship *looks* like a new model to him.

**Comment by Amazinite** [comment]
What do you think it could be changed to in order to get the same effect? Elliot needs some way to just know that you aren't from around Hai space. I'd figure that the player's ship would be the biggest identifier, but as noted, that's an issue if the player has a Hai ship.

**Comment by beccabunny** [comment]
Maybe the initial part of the mission could describe the player as in awe of something in the spaceport, like the buildings or the Hai efficency at doing something, that the people who lived there for more time don't even notice anymore, and Elliot could say to have noticed that

**Comment by NomadicVolcano** [comment]
> Maybe the initial part of the mission could describe the player as in awe of something in the spaceport, like the buildings or the Hai efficency at doing something, that the people who lived there for more time don't even notice anymore, and Elliot could say to have noticed that

I would like to second this idea.  Human ships in Hai space are quite common.  Tourists tend to stand out due to their lack of knowledge of local customs, unfamiliarity with their surroundings, or their uncommon appearance.

**Comment by Amazinite** [comment]
How about changing that line to 
> "Outside of Hai space. You don't look quite like most humans who live here, unless there's some new fashion trend going on that I don't about."

**Comment by Amazinite** [comment]
4bbf6a4

**Comment by tehhowch** [comment]
> that I don't about.
😅
