### ISSUE TITLE
Scanning "ring" not showing correctly

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4729]
**Describe the bug**
The ring that should appear when scanning a ship doesn't show at the correct size, instead it seems to make a circle (its blinks randomly in red or yellow) with a very small radius around a pixel in the centre of the ship. This happens for the cargo scanners, the outfit scanners and for both at the same time.
**To Reproduce**
1. Install an an outfit or cargo scanner
2. Scan another ship

**Expected behavior**
The ring shoud have the appropriate size depending on the ship scanned

**Screenshots**
![Screenshot (678)](https://user-images.githubusercontent.com/45330165/71618775-73d14b00-2bc1-11ea-9b64-fdf25452d1dd.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github
 - Version: Current nightly

**Comment by tehhowch** [comment]
Probably related to https://github.com/endless-sky/endless-sky/pull/4513

**Comment by petervdmeer** [comment]
> Probably related to #4513

I did a short test to verify this:
- Game compiled from commit d18ea95 (last commit before merge of #4513) shows scanning ring(s) correctly.
- Game compiled from commit 68775bb (the commit merging #4513) has the small/invisible rings as described in this bugreport.

So it looks very likely that this is related to #4513.

**Comment by Amazinite** [comment]
Oops. Should be fixed after merging #4731.
