### ISSUE TITLE
Fleet "Hold position" interferes with ships traveling in other systems

### ISSUE THREAD

**Issue by ltmauve** [endless-sky/endless-sky#473]
So, if you tell your fleets to hold position, ships in other systems traveling to you stop traveling as well.

**Comment by brick96** [comment]
You are telling your entire fleet to stop. There stop and follow no in between. Yet

**Comment by endless-sky** [comment]
That's by design. It's often useful, for example, to use "hold position" to have an injured (or recently captured) fleet lag behind you as you jump, in case there are pirates in your destination system.

**Comment by thenerdfreak** [comment]
^ and you then line up with the planet and press G, they'll jump to your system and as soon as the damaged ship turns from blue to white, land on the planet. I've used this many times and it would be a shame to lose this functionality. I would, however, look forward to a way to tell specific ships in a fleet to stop, follow me, etc. using a menu like the shipyard's (where you can select all, every ship in a row, a few specific ones, or just one)

**Comment by brick96** [comment]
Hold is also helpful when capturing when your fleet is just too strong to take prisoners

**Comment by ltmauve** [comment]
So basically, it's not getting changed unless we get better fleet management in general?
Alright.
