### ISSUE TITLE
Ibis leaks

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4733]
(Dunno if this is a bug or a feature request, honestly)
**Is your feature request related to a problem? Please describe.**
Currently, no Remnant ship except the new Ibis @Zitchas added has leaks in addition to the explosions.

**Related Issue Links**
https://github.com/endless-sky/endless-sky/pull/4546

**Describe the solution you'd like**
The Ibis shouldn't have leaks, like normal Remamnant ships

**Describe alternatives you've considered**
Give every Remnant ship leaks

**Comment by beccabunny** [comment]
The relative PR is  #4734

**Comment by Zitchas** [comment]
I'm kind of partial to the alternative solution, namely, giving all Remnant ships leaks. That being said, they should ideally be unique to the Remnant instead of simply using the human leak image.

**Comment by Amazinite** [comment]
Well for consistency's sake, I've merged Becca's PR removing the leaks from the Ibis. In the future if we want the Remnant to have unique leaks, that can all be done at once.
