### ISSUE TITLE
Landing immediately after take-off gives correct output, but doesn't get executed

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4736]
**Describe the bug**
Landing immediately after take-off gives correct "Landing on planet ..." output, but the landing doesn't get executed.

**To Reproduce**
1. Click depart on a planet (with spaceport and fully fueled ship).
2. Immediately press "Land" as soon as the main flight-screen appears.
3. Notice that the "Landing on planet ..." message appears correctly.
4. Note that the ship is not landing.

**Expected behavior**
I would expect either the landing to be executed as requested (which seems to make most sense), or the output message to be something different (like: "Cannot start landing while taking off.").

**Screenshots**
Here is a screenshot just after the issue happened, you can see the "Landing on planet ..." message, but the ship is not turning for landing.
![ignored_landing_during_takeoff](https://user-images.githubusercontent.com/35403542/71780633-43285180-2fc5-11ea-85a0-2549aed2b8f7.png)

**System (please complete the following information):**
 - OS: Debian Linux
 - Game Source: self-compiled
 - Version: recent master (75dabfe71e5891d47edd6ffda5544d0b5060b5e2)

**Link to save file**
N/A. Can be reproduced on on nearly any take-off.

**Additional context**
I haven't fully investigated the issue, but I think it is related to this code in Ship.cpp on line 1310:
```
else if(fuel >= attributes.Get("fuel capacity")
	|| !landingPlanet || !landingPlanet->HasSpaceport())
{
	zoom = min(1.f, zoom + .02f);
	SetTargetStellar(nullptr);
	landingPlanet = nullptr;
}		
```
This code appears to be executed continuously during take-off (until zoom is 1.0f) and appears to continuously clear the TargetStellar, even if the player just sets a new one for landing. After clearing TargetStellar, then the autopilot for landing automatically gets aborted (silently) in AI.cpp.

**Impact**
This issue will have little to no impact on normal/regular gameplay. There are very few situations where a player wants to take-off and then immediately wants to land again.
Players that encounter this issue might not even notice the issue; when a landing fails due to this issue, then pressing land again (a little bit later) results in a successful landing being executed.

Impact on fully automated tests (like the tests in #4370) and scripted flights (as proposed in #4720) is also minimal, since this automation/scripting should be able to work around this issue by waiting until zoom is 1.0f before giving commands.

**Comment by tehhowch** [comment]
I'd say this is resolvable alongside #4480 : when transiting to/from a planet (zoom != 1), it should not be possible to do much.

On the other hand, I could see it as desirable from the user that the land order be executed once possible (i.e. the transit is complete), as iirc that is the behavior for setting a jump target. One solution in this manner is to use the AI::Orders mechanism with a LAND_ON order as in #2990
