### ISSUE TITLE
ship editor

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#474]
Maybe not a feature in game but for something like the map editor, but for ships.
https://groups.google.com/forum/m/#!category-topic/endless-sky/GzOikL2goAA
Not initially my idea but I nice idea to quickly make a new ship. Import an png, add attributes, outfits, and where it can be sold as well as mapping mounts for guns and turrets

**Comment by Wrzlprnft** [comment]
well i am not sure if the dev wants a ship construction kit, but i could write a java program where you just have to add in the gaps for the values, maybe the mapping too. The result could be a plugin folder or something like that.
Making a pull request with that here wont be so easy, tha's something you have to do yourself

**Comment by endless-sky** [comment]
I've got a tool for setting hardpoints (gun, turret, and engine locations) on the ship sprite. I'll clean it up and post it online tomorrow if I have time.

**Comment by Wrzlprnft** [comment]
If there really is a ship editor, we could set up some ratios a ship has to have, together with templates of ship types this would limit the amount of unbalanced ships coming out of that....

**Comment by omagasohe** [comment]
The only issue I see is the slippery slope of the Dev's time being wasted building new editors when it's not particularly hard to do as is. The man already devotes his free time to making one of the most epic games ever, The community should be able to provide a suitable editor. I'd offer, but C# isn't the cross platform solution the community should have, but we all need hobbies =P

**Comment by endless-sky** [comment]
Here's a tool that lets you load a ship sprite, define the hardpoints for guns, turrets, and engines, and test out the color swizzling and the collision mask:

http://endless-sky.github.io/ship_builder.html

For setting the rest of the ship's characteristics, my recommendation is to create a new pilot and edit the saved game to get a ton of money and access to all the outfits in the game:

```bash
changes
	planet "New Boston"
		shipyard "Tarazed Basics"
		shipyard "Tarazed Advanced"
		shipyard "Southbound Basics"
		shipyard "Southbound Advanced"
		shipyard "Lionheart Basics"
		shipyard "Lionheart Advanced"
		shipyard "Betelgeuse Basics"
		shipyard "Betelgeuse Advanced"
		shipyard "Navy Basics"
		shipyard "Navy Advanced"
		shipyard "Megaparsec Basics"
		shipyard "Megaparsec Advanced"
		shipyard "Syndicate Basics"
		shipyard "Syndicate Advanced"
		shipyard "Alien Ships"
		outfitter "Common Outfits"
		outfitter "Deep Sky Advanced"
		outfitter "Lovelace Advanced"
		outfitter "Delta V Advanced"
		outfitter "Syndicate Advanced"
		outfitter "Kraz Advanced"
		outfitter "Pirate Outfits"
		outfitter "Special Outfits"
```

Then, you can just edit your new ship definition directly in that pilot file, and when you're satisfied with the attributes and outfits, you can copy it out of the pilot file into a plugin.

**Comment by omagasohe** [comment]
Brilliant, simply brilliant.

**Comment by johnca** [comment]
Who has access to the wiki? (I'm hoping someone other than Michael.) Updating the ship creation page with this would be great.
