### ISSUE TITLE
Blank outfits when lance fighter is only ship

### ISSUE THREAD

**Issue by diggorygray** [endless-sky/endless-sky#4740]
**Describe the bug**
When Lance fighter is only ship (i.e. sold a only ship and bought lance) there are no outfits shown in the outfitter.

**To Reproduce**
1. Go to planet which sells the Lance (haven't tested with other fighter types).
2. Sell current ship (and any escorts).
3. Buy lance.
4. Check outfitters,

**Expected behavior**
List of outfits as normal.

**Screenshots**
![Screenshot at 2020-01-12 02-39-02](https://user-images.githubusercontent.com/11949270/72213322-d8a37400-34e4-11ea-9d37-1c33f6af09a1.png)

**System (please complete the following information):**
 - OS: Mint Linux 19
 - Game Source: Complied 
 - Version:  commit 49a387d

**Comment by diggorygray** [comment]
I should clarify, that when I say blank outfits, I mean it appears the lance is an empty shell.
Not that there are no outfits in the outfitters.

**Comment by beccabunny** [comment]
You didn't select the Lance... it is selected automatically only if it is your flagship, but since you can't have a fighter as flagship, nothing is selected

**Comment by downRightCoder256** [comment]
imho player should be able to set fighters as flagships. it would probably require some AI modifications, but it should be manageable. there are even practical applications for it, either as a neat way to switch up ships real-time, as a fast mining ship or as an improvised escape pod

**Comment by diggorygray** [comment]
Yes thanks, I see I was confused - as the normal UI operation is to have a ship selected.

If the desire is to have fighters restricted to that role, maybe that should be indicated more clearly in the shipyard or somewhere?

It could be that they can appear in a bracket with a carrier ship?

If there is no carrier on that planet, then that should be highlighted.
Just like if you sell your flagship engines you get a warning to say you can't steer or takeoff.
Maybe you can have an exclamation above the fighter to say 'this ship has no mothership/carrier and can't leave the planet/station'.

**Comment by diggorygray** [comment]
I like the idea that a fighter could be used as a flagship if retrofitted, but I don't want to rock the boat if this is by design not to be the case.

I suppose you could have a reto-fit outfit if balance is needed to loose a ton or two?

**Comment by diggorygray** [comment]
> 
> 
> I like the idea that a fighter could be used as a flagship if retrofitted, but I don't want to rock the boat if this is by design not to be the case.
> 
> I suppose you could have a reto-fit outfit if balance is needed to loose a ton or two?

Ok that wasn't a very well worded reply, sorry.

What I meant to say was...

I agree with downRightCoder256, being able to use a fighter as flagship would seem a good idea.

However it seems like this is a deliberate choice not to allow a fighter to be used as a flagship?
Maybe it would cause a problem with balance or introduce unneeded complexity?

The outfit idea I had, I didn't expand upon properly, was to address the issue of balance between fighters and equivalent ships at the same cost.
If you did allow fighters to be used as flagships and this caused a balance issue, then a 'retrofit a fighter to standalone ship' kit outfit could both re-balance the spec of a fighter and allow it to become a standard ship.
The kit could add or decrease the spec of the fighter as required to get it to be comparable to a standard ship.
This does of course increase the complexity of fighters a lot, so is probably not worth it.

I think my main issue is making fighters either usable as standard ships or flag up the difference in the ship yard to avoid confusion (e.g. "no carrier dock" or "no mothership"? warning).

**Comment by tehhowch** [comment]
The case of having an uncarried ship is being expanded in #4388

**Comment by diggorygray** [comment]
Looks like that thread answers all my questions and suggestions!
Thanks tehhowch :)
