### ISSUE TITLE
Continous Modifiers in Weapons

### ISSUE THREAD

**Issue by Maryn-s** [endless-sky/endless-sky#4742]
**Is your feature request related to a problem? Please describe.**
It's not an obvious problem in the base game. But it does limit the possibilities of the type of content that can be created.

There are very limited ways of creating continuous modifiers. What I mean by *modifiers* are things like damage, hit force, etc. done by weapons.

**Related Issue Links**
I may have seen an issue opened up months or years ago that addresses this issue **partially**. However, I can't find anything through the search feature.

**Describe the solution you'd like**
There are a few possible ways I've thought of approaching this. I want to lay them out to show the benefits and downsides of each.

- Solution A: Allow projectiles to continue living on after hitting an object.
  - Benefits: Lets a projectile hit multiple targets linearly. Gives the possibility of creating "*bleeding*" effects like constant shield damage or heat damage, or even buffs for ally ships.
  - Downsides: Obviously you'd want to also limit the amount of times it hits **one** object, and create something like a counter. To allow the projectile to create things like continuous area effects you'd have to also add in the ability to override the counter or/and add in your own values, ex: `counter 30` would limit the amount of times the same object gets hit to 30.

- Solution B: Allow projectiles to apply a constant effect for <amount of frames> to an object.
  - Benefits: It's easier to implement than *Solution A*. There are examples of such effects already in the game like ion damage, slowing damage, etc.
  - Downsides: You may have to add in an option for certain modifiers like Shield Damage, etc. to apply or override the effect for each modifier to allow for finer tweaking. It all depends how complex you want it to be. Another downside is that it's not a real solution for things like continuous area effects as the projectile will have already died and applied its modifiers to the objects that were within the blast radius, but none that enter after the trigger.

- Solution C: Implement both A & B
  - Benefits: Gives more options for creating continuous modifiers.
  - Downsides: Requires more additions and changes.

- Solution D: Implement a different solution that isn't shown here.

**Describe alternatives you've considered**
I first thought of this when I was creating an area damage weapon that lasted for a number of frames. I used submunitions to create a pseudo continuous effect, but the longer I made the effect last the more submunitions I had to create which quickly became hundreds of lines. It also meant that when a target object collided with the submunition's projectile it would instantly stop the area effect. This is not a good way of implementing this since it quickly pollutes and clutters the text files. The ability to have a constant rate reduces clutter and prevents small errors from having to duplicate frames.

**Additional context**
I only thought of this issue while trying to make area modifiers that lasted for more than one frame and decided to expand this feature to encompass all modifiers.

**Comment by Amazinite** [comment]
So if I understand this right, what you want are damage effects akin to ion, slowing, and disruption damage (which all start high with the initial impact then bleed over time), but for other damage types?

**Comment by Pathless-Visions** [comment]
> So if I understand this right, what you want are damage effects akin to ion, slowing, and disruption damage (which all start high with the initial impact then bleed over time), but for other damage types, possibly with the ability to have the damage emanate from the point of impact (e.g. for hit force)?

Yeah. Emanating from point of impact would allow for stuff like area effects.
ex: Making a radiating bomb that explodes and causes damage for a number of frames to objects that enter its radius.

I was thinking that both implementations could use the same thing, but maybe it'd be better to expand bleeding damage to other damage types and create a separate set or properties for stuff like area damage/radiating zones (zones that radiate damage for a number of frames)

**Comment by tehhowch** [comment]
Related: #4116

**Comment by warp-core** [comment]
#6276

**Comment by Maryn-s** [comment]
> #6276

It seems that `penetration count` solves almost about everything related to this issue, so I will go ahead and close this. (Unless I'm missing something, in which case someone can reopen it)

In order to not hijack this thread I have opened a separate issue that addresses aoe field weapons more specific to resolving a small kink to their full implementation: #10315
