### ISSUE TITLE
crash on new pilot creation

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4750]
Creating a new player causes the game to crash.  This is 100% reproducible.  It is caused by accessing `flagship` when `flagship` is `NULL` in `PlayerInfo.cpp`:

      conditions["flagship crew"] = flagship->Crew();
      conditions["flagship required crew"] = flagship->RequiredCrew();
      conditions["flagship bunks"] = flagship->Attributes().Get("bunks");

**Comment by NomadicVolcano** [comment]
Proposed fix in in pull request #4751.  Flagship crew, required crew, and bunks are set to 0 if there is no flagship.

**Comment by tehhowch** [comment]
Thanks for the report and the patch!
