### ISSUE TITLE
Ka'het mission asks you to contact Quarg before you meet the Quarg

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4759]
The "First Contact: Ka'het: Quarg 1" mission will ask you to visit the Quarg before you've met them.  It will even tell you the location of a Quarg world to visit, even if you've never been anywhere near that region of space.

**Comment by beccabunny** [comment]
Actually, at first it was the way OP suggested (e.g. mission didn't offer until the player met the quarg), but Derpy suggested to change to to have a branch in the mission and make it offer no matter what. As for having lagrange as destination, that was the only way I could find to make the mission chain work (ref. the "fail only happens after the player lands again" issue). An option could be to make the mission invisible, but then there is no reminder for the player to actually visit the Quarg ring and ask them about it. Tehh suggested that a way to ping the player about it would be to use a recurring mission and an event timer, that displays a conversation on offer and then declines itself, like the "war begins" text. Maybe it would be easier to revert it back to the way it was at the beginning (no mission at all until you meet the quarg), dunno

**Comment by Amazinite** [comment]
According to the first contact mission for the Quarg, the player character at least knows of the existence and location of the Quarg and what a ringworld is before meeting them. “You had seen pictures and videos of the Quarg before, but this is your first time in a spaceport that is owned by them.”
What the player reads if they visit the abandoned ringworld before or after meeting the Quarg already changes according to that condition.

**Comment by NomadicVolcano** [comment]
The player doesn't even know the location of Earth.  Why would they know the exact location of a Quarg colony?

**Comment by Zitchas** [comment]
Know the exact location of one? No. Know that they exist? Yes, I'm fairly sure that is common knowledge.

**Comment by NomadicVolcano** [comment]
My suggestion is to allow the player to land on any Quarg colony, but not tell them where the colonies are.  The destination of the mission is the same as the source: Querii'ka.  The mission is displayed as a greyed-out blue tick so the player knows they have to go somewhere else to finish the mission.

See #4761 to try this out.

There is one bug to fix: the mission doesn't vanish from your mission board until after the next landing.

Other than that, I would say this is the ideal solution.

**Comment by Amazinite** [comment]
>My suggestion is to allow the player to land on any Quarg colony, but not tell them where the colonies are.

This was my original suggestion but Becca had an issue with it, that being exactly this:

>There is one bug to fix: the mission doesn't vanish from your mission board until after the next landing.

#1938

**Comment by NomadicVolcano** [comment]
I'm working on adding a "refresh" flag to missions.  It will cause failure and completion conditions for that mission to be rechecked, even when you're not landed on the planet in question.

You don't want to "refresh" all missions automatically because the information sent into "on complete" and "on fail" will be wrong if you're on the wrong planet (or no planet).  If the "refresh" flag has to be set explicitly, then the content creator can make sure their "refresh" missions are written to handle that correctly.

**Comment by oo13** [comment]
> The player doesn't even know the location of Earth. Why would they know the exact location of a Quarg colony?

@NomadicVolcano FYI, "you" know the location of Earth from the start.
![initial](https://user-images.githubusercontent.com/22392249/73130055-bfe2a480-4034-11ea-9a91-6a6aea2254d3.jpg)

**Comment by NomadicVolcano** [comment]
No.  That was random chance.  You happened to get a cargo mission on Earth.

**Comment by NomadicVolcano** [comment]
> > The player doesn't even know the location of Earth. Why would they know the exact location of a Quarg colony?
> 
> @NomadicVolcano FYI, "you" know the location of Earth from the start.

No. That was random chance. You happened to get a cargo mission on Earth.  If you leave the planet and land again (and there is no Earth mission), then the Sol system will vanish.

You'll never get a cargo mission to a Quarg world.

**Comment by NomadicVolcano** [comment]
Please try the change in draft pull request #4761 and let me know if it works for you.

It will work as I said before: you will have an incomplete mission at Querii'ka until you visit the Quarg and ask about the ringworld.  Any planet with the "quarg" attribute will work, and you won't be told where they are.  Due to ASCII and std::set cleverness, the conversation about Ka'het space will happen after the Quarg first contact.  (A comment in `data/ka'het missions.txt` explains it.)  The mission will vanish after the conversation due to the bug fix in pull request #4764 which I've already merged into #4761.

As a necessary consequence, when you've finished the conversation, "First Contact: Ka'het: Quarg 1" is failed instead of completed or differed.  Remember that when conditioning on having knowledge of the Ka'het.
