### ISSUE TITLE
automatically check coding standards in pull requests

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4760]
Endless Sky has a coding standard for its C++ code, and many aspects of the standard can be checked automatically.  If we add a code quality check to the GitHub automatic checks, it would save time in the back-and-forth between developers iterating on code quality of commits.  This is a common approach in software projects that have widely-distributed developers.

**Clarification**: there is a coding style checker, but it is not comprehensive, and the result is not reported automatically to the user like the build checks are.  It also does not block the pull request if there are blatant errors like indentation spaces instead of tabs.

**Comment by NomadicVolcano** [comment]
Relevant link:

https://github.com/endless-sky/endless-sky/actions?query=workflow%3A%22Check+coding+style%22

**Comment by tehhowch** [comment]
Closing this as the style checker is in active development: #4411
