### ISSUE TITLE
Create a "display name" for governments

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4767]
**Is your feature request related to a problem? Please describe.**
In order to have governments that need to look the same but have a different data, both the Mereti Mind mission and the new Ka'het faction use "Ka'het" and " Ka'het " since the game recognises them as different factions. However, in game they don't look exactly the same since, when you select a ship or a planet, the arrows around the government name are placed depending on the presence of the spaces at the border, becoming like this:
![Screenshot (1059)](https://user-images.githubusercontent.com/45330165/73140140-b6c5f780-4075-11ea-8a39-4dd364465aad.png)
while it would be more fitting if it looked like this, the government without the spaces:
![Screenshot (1060)](https://user-images.githubusercontent.com/45330165/73140164-03a9ce00-4076-11ea-9b94-c5a57a1c4788.png)

**Related Issue Links**
None I could find

**Describe the solution you'd like**
When showing the government "arrows", ignore the eventual spaces if they are at the beginning or at the end of the name. This would also allow to create more similar governments (arriving at a maximum of 4) without visual differences, by doing "Ka'het " and " Ka'het"

**Comment by tehhowch** [comment]
Probably the most useful implementation is to add an optional "display name" class member to `Government`, which would allow naming a government pretty much whatever you want and have it appear to the player as whatever you want.

Content creators would still need to use the internal name e.g. in location filters, NPC definitions, and the like.

**Comment by beccabunny** [comment]
That would work well indeed
