### ISSUE TITLE
Selecting Systems on the Job Board

### ISSUE THREAD

**Issue by zig158** [endless-sky/endless-sky#477]
Version 0.8.9 (beta)
I am unable to select systems by clicking on them when zoomed in or out on the Job Board. I am zooming with the scroll wheel. When I return the the default zoom level I am able to select systems as normal.
My guess is that the system select click location is not being updated to correspond with the systems new location on the map.

**Comment by endless-sky** [comment]
You're right, it wasn't taking the zoom factor into account when figuring out where you clicked. Fixed in 9011bc3.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
