### ISSUE TITLE
Wiki does not mention kills by "Escort" government ships boost combat rating

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4775]
If a ship of the "Escort" government disables an enemy, the player's combat rating is boosted.  I see no mention of that in the wiki.

Apparently github has no way to do wiki pull requests.  If someone can inform me of how I should request Endless Sky wiki changes, I'll do it.

**Comment by Amazinite** [comment]
Seeing as how we have #4511 (there's enough stuff missing from the wiki that funneling it all to a single issue makes sense), I'd suggest just posting any missing wiki info there. I will note though the following information from the Player Conditions page:
> `"combat rating"` is your current combat rating (based on the strength of all the ships **your fleet** has disabled).

**Comment by NomadicVolcano** [comment]
When I make an npc of the "Escort" government, its kills count towards the player's combat rating.  The wiki does not tell me that npcs of the "Escort" government are the player's ships.

**Comment by NomadicVolcano** [comment]
I put it in the log for #4511 and I'll close this ticket.
