### ISSUE TITLE
Diphda remains cut off from neighboring systems

### ISSUE THREAD

**Issue by FixItYondu** [endless-sky/endless-sky#4776]
**Describe the bug**
After finishing the Free Worlds campaign, the hyperspace links from Diphda to Acamar and Ankaa are not reattached. 

**To Reproduce**
Not sure exactly how it happened, so I don't really know how to reproduce it.

**Expected behavior**
I expected the links to reattach just like the rest of the systems did after finishing the campaign, but that seems to have not happened for some reason. 

**Screenshots**
<img width="387" alt="Screen Shot 2020-01-29 at 2 11 20 PM" src="https://user-images.githubusercontent.com/29680828/73389588-7eefc780-42a2-11ea-9cf3-53c35d9703bc.png">
As you can see, the links from Diphda to Acamar and Ankaa are not there, and Diphda appears to be the only system where this has occurred. 

**System (please complete the following information):**

OS: macOS Catalina
Game Source: Nightly
Version: Not sure, but it was the latest version on November 28, 2019. 

**Link to save file**
[https://drive.google.com/file/d/1J97VughQiIJNSiAUiPmkYr08G_DF5RN0/view?usp=sharing]

**Additional context**
N/A. 

**Impact** 
This issue is somewhat annoying, but it has no real gameplay effect. I'd like to know exactly what happened, however, since this is a really strange issue that I've never run across and might happen to others if it is a bug.

**Comment by beccabunny** [comment]
Any plugins?

**Comment by Amazinite** [comment]
The links restore over time. Checking your save file, you have the following:
```
11 11 3017
...
event
	date 24 11 3017
	"event: pug link restoration 3" = 1
	link Diphda Ankaa
	link Fomalhaut Markab
	link Rasalhague Ascella
event
	date 9 12 3017
	"event: pug link restoration 4" = 1
	link "Delta Capricorni" Scheat
	link Caph Eteron
	link Diphda Acamar
```
So there are two more restorations that you haven't reached yet.

**Comment by FixItYondu** [comment]
Huh, I'd never noticed that. I remembered it happening instantly in previous playthroughs, but that might just be my faulty memory. Thanks for the help!
