### ISSUE TITLE
Scale stations like we scale ships

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4779]
**Is your feature request related to a problem? Please describe.**
Currently, ships and some other images across the game are twice the in-game size, in order to keep the sprite sharp; the same is not true for planets and stars, which is fine because they don't have many sharp angles anyway so there is no real difference; on the other hand, due to the way they are coded, this makes it so that stations are not scaled as well, which makes most of them look kinda blurry at max zoom

**Related Issue Links**
None I could find

**Describe the solution you'd like**
If possible, make the game scale the sprites inside a "station" folder and move the current sprites there

**Describe alternatives you've considered**
I am not familiar with the code, so I don't know which would be the most feasible option:
-the option above, or
-create a new "station" keyword, which works the same as "object" but scales the image it refers to
-create a new "scaled sprite" keyword, which works the same as "sprite" but scales the image ti refers to
-create a new "resize" attribute, child of "object", that if used resizes the image that "sprite" refers to

**Comment by petervdmeer** [comment]
Issue https://github.com/endless-sky/endless-sky/issues/4585 and PR https://github.com/endless-sky/endless-sky/pull/4588 look somewhat related (but then for different sprites). I would expect a similar approach to planets as would be done here (and as is done for existing ships).

**Comment by beccabunny** [comment]
Those issues, on ther other hand, are more about "being able to resize existing sprites without modifying images", while this tries to fix the visual distinction between the resolution of ships and stations with the same DPI

**Comment by tehhowch** [comment]
It would be very easy to scale stations differently than stars or planets (we would just set the `zoom` to 1 instead of 2 as is done currently, on a conditional basis).

More pressing questions are: should we do this by default? Should we allow setting a custom zoom on a per-object basis? Both?

**Comment by beccabunny** [comment]
@tehhowch if possible, my preferred option would be having ES read a list of "planet" sprites that need scaling, similarly to the special landing messages feature. Otherwise, the "resize" attribute, child of "object", would be good too. About the custom zoom, I don't see much point, since planets and stars are already small enough that they would very hardly need being even smaller. And anyways, the "resize" feature could later be expanded to read a number next to it (like "resize 0.1") to set the zoom

**Comment by Amazinite** [comment]
Note that #4588 works for scaling all sprites, so I believe you could give a scale factor to a larger station sprite but it would retain a higher resolution than if the sprite was already that size.

**Comment by Amazinite** [comment]
The bottom station is a 200x200 image at 0.5x scale. The top station is 100x100 image.
![image](https://user-images.githubusercontent.com/17688683/147840235-24f94092-c4da-4271-a550-0c6698479645.png)
So scaled down images do turn out higher quality.
