### ISSUE TITLE
Blue Waypoint marker not pointing to the correct location on the Job Board

### ISSUE THREAD

**Issue by zig158** [endless-sky/endless-sky#478]
Version 0.8.9 (beta)
The blue Waypoint marker is not positioned correctly at some zoom levels. It should be pointing at the Menkent system, but seems to move independently of the system when zoomed in, or zoomed out more than one level.
This issue is likely related to issue #477

**Comment by endless-sky** [comment]
Fixed in commit 9011bc3.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
