### ISSUE TITLE
Add an NPC personality that gives the ship to the player

### ISSUE THREAD

**Issue by Gods-Righthand** [endless-sky/endless-sky#4780]
**Is your feature request related to a problem? Please describe.**
A feature that make it possible to give ships to a player in a mission without having to board or some other complicated method.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those.
Not that I was able to find.

**Describe the solution you'd like**
My idea after some discussion with @NomadicVolcano is to have a NPC with a personality `gift` that when used, creates a ship in any system for the player. So they can do whatever they want, sell, park and give commands to it.

**Describe alternatives you've considered**
I also had the thought of putting it under `MissionAction` where outfits are handled.

**Comment by Amazinite** [comment]
Is this differentiated in any way from #4399?

**Comment by Gods-Righthand** [comment]
Not really although my idea of implementing it is different than what Fzzr was doing. 
Is there any reason to leave this issue open, or shall I close it since it's a duplicate?

**Comment by MCOfficer** [comment]
> 
> 
> Not really although my idea of implementing it is different than what Fzzr was doing.
> Is there any reason to leave this issue open, or shall I close it since it's a duplicate?

If it adresses the same *problem*, move your *implementation* suggestion to #4399. If you think that this is a different problem, leave it open.
