### ISSUE TITLE
Could you add a setting to set the save file location?

### ISSUE THREAD

**Issue by PhlegethonAcheron** [endless-sky/endless-sky#4789]
This simple QOL change would make it significantly easier and more convenient to take the game to whatever computer I am using at the time. The game itself is super convenient to run off a USB drive, , and I LOVE the lack of an installer, but it is mildly annoying to go to `%appdata%` every time I log off a computer. There is always the chance I will forget to do that transfer. Last block on Friday before a long weekend, after a chill block of nothing for 70 minutes but games and rendering a Blender animation, I will 100% forget to grab the save file. 
An entry added to the README, with instructions on how to make that change myself would be appreciated in any future versions, too. I would make the change myself, but I really don't know where to start doing that.
[This issue is kind of similar to what I am requesting, but not quite.](https://github.com/endless-sky/endless-sky/issues/3079)

**Comment by MCOfficer** [comment]
> This simple QOL change would make it significantly easier and more convenient to take the game to whatever computer I am using at the time. The game itself is super convenient to run off a USB drive, , and I LOVE the lack of an installer, but it is mildly annoying to go to `%appdata%` every time I log off a computer.

For the time being, you can work around this by [linking](https://en.wikipedia.org/wiki/Symbolic_link) the saves directory to a directory on your USB Stick or whatever. Though that will break in some way if the Stick is not plugged in.

Another Alternative is to use some Sync Client to upload the saves to your cloud.

> An entry added to the README, with instructions on how to make that change myself would be appreciated in any future versions, too. I would make the change myself, but I really don't know where to start doing that.

Traditionally, most larger software projects have either a section of the README or a file called [CONTRIBUTING.md](https://github.com/endless-sky/endless-sky/blob/master/CONTRIBUTING.md) that contains instructions. See also the Wiki ([Contributing content to the base game](https://github.com/endless-sky/endless-sky/wiki#contributing-content-to-the-base-game), [
Compiling or modifying the source code](https://github.com/endless-sky/endless-sky/wiki#compiling-or-modifying-the-source-code)

**Comment by tehhowch** [comment]
Use the `-c` / `--config` command line option with the desired path. This is documented in the man page

https://github.com/endless-sky/endless-sky/blob/be12c48851bd1f0fef135708f0c233ef438a233f/endless-sky.6#L41-L42

And also the command line help:
https://github.com/endless-sky/endless-sky/blob/be12c48851bd1f0fef135708f0c233ef438a233f/source/main.cpp#L416

Supporting a GUI override is not a development priority but a PR doing so would be welcomed.
