### ISSUE TITLE
Add ability to review on-screen message history.

### ISSUE THREAD

**Issue by WildLynxDev** [endless-sky/endless-sky#4794]
Problem:
Mission failed! 
When, how? It was before I landed at the previous system or after? Dam it!

Also:
That Merchant captain said something witty, but it scrolled up before I could read it completely.

Solution:
Store all messages at temporary file, clear it on savegame load and game start, add keyboard controls for scrolling messages back [Page Up], forth [PgDown] and to the last [End].

**Comment by jafdy** [comment]
Mission failed messages should be solvable by adding a dialog on landing.

**Comment by Amazinite** [comment]
Ref: #3361

**Comment by Zireael07** [comment]
Most games with many messages (RPGs, roguelikes) have a 'message/log history' screen where you can scroll back at your leisure. This often, but not always overlaps with storing the log in a file, as mentioned by OP.

**Comment by tehhowch** [comment]
Discussion should be redirected to the original issue for duplicates.

**Comment by WildLynxDev** [comment]
Mission failure is only a one of the reasons. Sometimes random passing ships leave comments and they scroll up too fast to read, especially if you trying to dodge missiles at the some time.
