### ISSUE TITLE
Negative cargo used by "Rescue miners 1"

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#48]
In my current game (save file at http://angband.pl/tmp/neg_cargo.txt), the mission "Rescue miners 1" takes a highly negative amount of cargo space.  As long as I don't complete that mission, I can take effectively infinite loot.

**Comment by endless-sky** [comment]
Good catch. In the mission data I'd put the name of the cargo in the "amount of cargo" place and vice versa (d15ee80).
