### ISSUE TITLE
Quarg and Neutral systems give you a contraband fine

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#480]
When entering a system with a neutral goverment, with illegal controband, they game gives you a dialogue that goes like..The Neutral fines you xx money illegal contraband. Same with the Quarg, who should not fine you for carrying illegal human contraband.

**Comment by thenerdfreak** [comment]
I agree it just SOUNDS weird. also weird is that angering one neutral makes the others, all the way across the galaxy, mad as well

**Comment by mdsmestad** [comment]
I know right...needs to be adressed

**Comment by Thunderforge** [comment]
I think the solution would be to indicate which contraband a faction cares about, rather than having a faction not care about any sort of contraband. For instance, a peace-loving alien species might not care that you are transporting spice, but would that you are carrying weapons.

**Comment by mdsmestad** [comment]
Well as the lore is right now, the only thing the quarg should fine you one
is have intrusive countermeasures stolen from korath ships

**Comment by Thunderforge** [comment]
I was more thinking about the bigger picture should future aliens be added, or more interesting cargo for existing factions (e.g. Faction A doesn't like contraband cargo X, but Faction B is happy to have it).

**Comment by thenerdfreak** [comment]
@Thunderforge you can Conquer all of Human space by the time the other aliens are available to you, so that really won't matter

**Comment by endless-sky** [comment]
I don't think this is necessarily a problem. The Quarg would certainly object to you carrying cruel weapons, and it's reasonable to think that the local government of a "neutral" system would object, too.
