### ISSUE TITLE
Wiki has wrong plugin folder paths for Mac OS X

### ISSUE THREAD

**Issue by shoelzer** [endless-sky/endless-sky#4804]
The Wiki has a page about creating plugins here:
https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins

On that page the plugin folder paths for Mac OS X are wrong. The correct paths are:

* Contents/Resources/plugins/ (within the application bundle)
* ~/Library/Application Support/endless-sky/plugins

The corrections are that "Contents" has an "s" and "Application Support" has a space between words.

I tried to edit the Wiki myself but can't figure out how.

**Comment by downRightCoder256** [comment]
@Amazinite

**Comment by tehhowch** [comment]
Thanks, will update soon. Direct wiki edits are limited to those with commit access.

**Comment by tehhowch** [comment]
FIxed
