### ISSUE TITLE
Korath Exiles have Mereti ships in their fleet after salvaging factory parts from Kor Sestor

### ISSUE THREAD

**Issue by DmitrySukhv** [endless-sky/endless-sky#4807]
**Describe the bug**
After the 'Wanderers: Sestor: Final' mission, Korath Exiles got a Sestor and Mereti ships in their fleet, though they have only salvaged Sestor factory, not Mereti one.

**To Reproduce**
1. Complete the mission 'Wanderers: Sestor: Final'
2. Go to the Korath Exiles
3. Wait to see Mereti ships

**Expected behavior**
Mereti ships must be unavailable to Exiles because they have never salvaged their factory. Maybe it's worth to increase the diversity (and number) of Sestor Exile ships to compensate that.

**System (please complete the following information):**
 - OS: Ubuntu Linux
 - Game Source: self-compiled
 - Version: 0.9.10

**Comment by Amazinite** [comment]
From "Wanderers: Sestor: Final" just after the Exiles have left with the Sestor parts.
> Meto Pa'aret says, "**The Mereti [contacted, communicated with] me and said that one of their stations was [raided, infiltrated] by the Korath exiles, and some of their [machinery, equipment] was stolen**. The Mereti did not [fight, attack] the exiles because they thought they were [friends, allies]. Captain <last>, can you bring Rek to visit the [exiles, outcasts] and learn what their plans are?"

**Comment by DmitrySukhv** [comment]
Wow, that's a pity I didn't remember it. Looks like the time to close the issue. Thanks @Amazinite
