### ISSUE TITLE
Real-space shooting

### ISSUE THREAD

**Issue by DmitrySukhv** [endless-sky/endless-sky#4809]
**Is your feature request related to a problem? Please describe.**
As we know, the outer space is void. In order to bring some 'real sci-fi spirit' and rationality and fun in the game, I suggest a kind of 'hardcore mode', an unbalanced way of gaming, namely 'The real space shooting' settings option, in which:
- All weapons have significantly larger (minimum 10x) range. Gravitational weapons (like Korath Grab-Strike) is an exception.
- I assume that missiles have depletable fuel and do self-destruct after fuel is depleted (like now), so no change to the missiles.
- Beam weapons are intended to burn a holes, melt or cut the hulls; with distance, it will be harder to maintain a steady point of contact. So their efficiency against hulls should be decreasing while shield damage should not.
- Perhaps there's a need to adjust inaccuracy of beam weapons to make them less effective on such a great distances, so ships *will* "try and shoot 'em" but with little success.
- Projectile weapons should be effective at that ranges too; however, due to their large travel times,
- it is advisable for all ships to use engagement range described in #4772 in order to increase the effectiveness of their attack.

**Related Issue Links**
#4772 

**Describe the solution you'd like**
1. Make an option in main menu for the mode. Let it be fully optional and let the saves be compatible so user could switch it on andd off any time.
2. Increase all weapons' range to 10x from the current ones, with exception for gravitational weapons of Korath.
3. Make beam weapons' hull damage decrease with the range.
4. Introduce engagement range from #4772 so ships could automatically try to take optimal positions to fire at.

Korath Exiles and Kor Mereti and all projectile weapons will be weakened with this; maybe they deserve to be mode powerful, or their travel speed to be greater.

**Comment by Zitchas** [comment]
As an option, I like it. It could also be implemented as a plugin, which might prove to be popular. I'd certainly take a look at using it.

As far as that goes, you can take a look at EVN's railguns for an example of similar gameplay and how having weapons with near-infinite range can affect combat. (All railguns in EVN had a "max range" that was long enough that ships could shoot at each other from beyond even the mini-map range.  If I recall correctly, they lost power over time, so by the time they approached their max range, they dealt very little damage. The smaller railguns were laughable at extreme ranges, but the big 400mm railguns were quite effective. The Aurorans used them extensively, particularly on their carriers. )

Anyway, while I like the idea, I suspect that the developper time required to implement a preference that does a modification of all range and engagement data at load time means this won't happen soon, and not really be a priority. Thus I recommend that you implement it as a plug-in, which could be included in the plug-in list on https://github.com/EndlessSkyCommunity/awesome-endless-sky , and give people pretty much the same impact as could be achieved through changing the base game like this.

**Comment by MCOfficer** [comment]
I am opposed to this for a number of reasons. Firstly, it would be imprudent to focus on a second big kind of gameplay experience when the "default" already has a large todolist. 

Secondly, it would be very hard to maintain - we are talking about changes at numerous points in the code and existing functionality/features. We'd have to test everything, including balance, in both the default and this mode.. If a feature results in a constant "did you check if this works/is good with feature X", it's likely not worth the trouble.

**Comment by DmitrySukhv** [comment]
@MCOfficer not very much of maintain really, and not great deal of a change... It's simply a range increase with several exceptions and beam-weapon dimming. As a measure of balance one can tweak projectile weapons too. That's all, basicly.

**Comment by MCOfficer** [comment]
> 
> 
> @MCOfficer not very much of maintain really, and not great deal of a change... It's simply a range increase with several exceptions and beam-weapon dimming. As a measure of balance one can tweak projectile weapons too. That's all, basicly.

I thought i had read some kind of physics change there, my bad. The point about balance and content changes still stands, though. Without significant code logic changes, this might be well suited for a plug-in, where the plug-in author commits themselves to the maintenance (rather than giving it to the base game maintainers).

**Comment by Zitchas** [comment]
"a measure of balance" is something that already causes problems. This would mean a second layer of balance issues. 

Like I said, this is better as a plug-in where one or two people who are particularly interested in this can maintain it; rather than part of the base game where any balancing or fixes has to go through  a weeks or months long PR-review-commit cycle, and possibly cause problems for other aspects of the game. It certainly *could* become part of the game, but only after having demonstrated that it has reached a well balanced state.

**Comment by DmitrySukhv** [comment]
BTW, usage of drones and fighters (which is widely discussed here) will be even more deadly with that mod... because it's hard to hit fast and maneuverable target from a long distance (GasCraft and Archon issue) with both projectile and beam weapons, while drones will be able to (at least) reduce shields of the target with their weak weapons from afar. That will make drones and fighters great again. )

**Comment by DmitrySukhv** [comment]
@Zitchas I agree that it must be plugin before anything else. Personally, I have no idea how to make one though... hope anyone will help to lay the foundation to this work, and then I will take it over. I myself itching to see this mod in action)

> "a measure of balance" is something that already causes problems.

I'm speaking about very light balance here, something like 'generally increase projectile travel rate by 3 times', or 'generally increase projectile damage by 2 times'. Shouldn't be a problem.

**Comment by Amazinite** [comment]
> Personally, I have no idea how to make [plugins] though...

https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins

**Comment by Amazinite** [comment]
In so far as we'd add different "modes" to the game, the only one that seems to make sense would be a perma-death mode (ref: #362), as that implies no changes to the balance to the game, only resulting in pilots being deleted after death. We haven't even gotten around to adding that to the game though yet, so I don't see it being likely that we'd go down the route of adding modes that change the balance of the game. As mentioned, this seems far more appropriate for a plugin.

**Comment by DmitrySukhv** [comment]
I've created plugin with increased "velocity" parameter for ALL primary weapons, 10x. That was a mess :) All shots became hardly visible due to the nature they rendered. Though the performance increased, somehow.

Plans: change the duration of slow projectiles instead of velocity; for beam (continuous) weapons rescale the sprites to make them 10x longer.

**Comment by Zitchas** [comment]
I would recommend playing around with the `lifetime` attribute instead. 10x the lifetime will get the same increase in duration/max range, but without being a mess in terms the speed of the shots.

**Comment by downRightCoder256** [comment]
in terms of realism, a change to the game i would see as plausible is to remove the sounds of engines of other ships in space, sounds of other ships firing in space, sounds of other ships dying in space... essentially only leaving sounds that happen on and in the flagship, since sound cannot travel through the void of space. although i would like to see this feature coming, at least not until an addition of proper ambiance music in space (#3594), since it would make the game quite boring

**Comment by Zitchas** [comment]
While yes, that would make things more realistic, I run with the head-cannon that the sound effects are actually generated by my control room situational awareness systems as a way of using auditory inputs to help me keep track of what's going on around me. Therefor, doesn't break any rules of physics or whatnot (aside from my targeting computer being omniscient about what's going on around me).
