### ISSUE TITLE
Fleet no longer arrives in unison.

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#481]
Fleet is 20 Bacs - near as possible - identical in mass. Fleet departs planet. Hold-J to jump together. Fleet jumps in unison, clustered together. Fleet arrives after jump with flagship in one place, clustered escorts halfway across the system.

This phenomenon is, however, inconsistent. Sometimes the (same) fleet arrives clustered, sometimes it doesn't. <i> This is especially irksome when jumping into hostile territory.</i>

Any ideas?

**Comment by endless-sky** [comment]
It's a consequence of the flagship now being the "top" ship (i.e. the last
ship drawn). That means that the escort AI chooses its action before the
flagship does, so it doesn't know the flagship is jumping until the next
frame.

**Comment by anonybosch** [comment]
Is it an "either-or"? If it is, tactics will need to be  re-developed. (sic) 

"ab" is pondering the implications of getting what he wished for (flagship always on top.)

**Comment by anonybosch** [comment]
By the by, a mention in the changelog for typos, along with wertzelwhatever et al, would certainly be an egoboost for a sad and lonely sidelinemodder. [smiley]

**Comment by anonybosch** [comment]
Given my druthers, I'd elect for unimproving this facet of the update.

**Comment by brick96** [comment]
Ive seen this before I dont think its from the redraw. Ive seen it most often in systems with multi-landings, usually when a station has missions but the default planet does not, thus the flag ship jumping to the station while the escorts jump closer to the default planet

**Comment by jafdy** [comment]
brick is right this is precisely the effect I found.

**Comment by anonybosch** [comment]
Hmmm. Pretty sure I'd have noticed if it had happened before. Now I'll make note of which systems this happens in.

**Comment by endless-sky** [comment]
This should be fixed by commit b5f3a95.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
