### ISSUE TITLE
Typo "soptover"

### ISSUE THREAD

**Issue by otsohelos** [endless-sky/endless-sky#4811]
**Describe the bug**
Typo: line 1404 says "soptovers", should say "stopovers".

**Comment by MCOfficer** [comment]
Thanks! Please mention the filename next time, or just open a PR yourself ;)

**Comment by otsohelos** [comment]
Oops, thought I linked to it. :) Sorry!

**Comment by tehhowch** [comment]
PR #4812 was merged
