### ISSUE TITLE
Bug with "Contact the exiles" Wanderers mission

### ISSUE THREAD

**Issue by trunksbomb** [endless-sky/endless-sky#4819]
**Describe the bug**
Just took on the "Contact the exiles" mission. Immediately upon departing Setar Fort, the mission is marked completed on the map ("Active job; go here to complete"). If I land on Setar Fort, I get a message saying an "escort carrying Rek hasn't entered the system yet". The mission accept dialog prior indicated that Rek is on my ship and we are supposed to head to Korath Exile space to make contact.

**To Reproduce**
1. Accept the "Contact the exiles" mission
2. Travel to Setar Fort and speak with Rek, he indicates he will be boarding your ship
3. Depart the planet and land on the planet again.
4. Receive message about Rek being on an escort ship.

**Expected behavior**
I would expect the mission to not already be marked complete, and to see some indication as to what part of Korath Exile space I should head to.

System (please complete the following information):
OS: Windows 10 Pro, version 1903 build 18362.657
Game Source: Steam
Version: 0.9.10

**Link to save file**
https://hastebin.com/owasokobij.cpp (I deleted all my fleet ships from save because file length was too large for Hastebin)

**Comment by beccabunny** [comment]
The wrong on visit dialog was already fixed my @Amazinite a few months ago, after 0.9.10

**Comment by trunksbomb** [comment]
Looking through `wanderers middle.txt` I see the updated text but shouldn't the mission also be marked incomplete? Or was that fixed, too?

**Comment by beccabunny** [comment]
It was fixed in #4766 afaik

**Comment by trunksbomb** [comment]
Gotcha, thanks. I did a search for the mission title and didn't see it mentioned but I see now that it was fixed as a more broad bugfix in the mentioned PR.
