### ISSUE TITLE
Stowing mission cargo in carried fighters makes marker think mission is unable to be complete

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#4824]
**Describe the bug**
If some of your fighters are carrying mission cargo, even if the carrying ship is in the same system as you, the mission marker will be faded. This bug does not affect the mission's ability to complete. If the fighters are deployed, the bug goes away.

**To Reproduce**
1. Have a carrier and some ships that can carry cargo.
2. Accept a cargo mission.
3. Take off.
4. Check if the mission cargo is in the fighters.
5. Go to the map and look at the mission marker.

**Expected behavior**
The mission marker should light up if the fighter's carrier is in the same system as you.

**System (please complete the following information):**
 - OS: [Windows 10]
 - Game Source: [self-compiled]
 - Version: [commit hash f0251da]

**Link to save file**
[Strix Vell~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/4212176/Strix.Vell.previous-1.txt)

**Additional Context**
#1521 and the other issues posted there are likely related to this issue.

**Comment by tehhowch** [comment]
Carried ships have no system, which is why the game doesn't think you can compete the mission until you deploy them.

(You can ensure that cargo gets loaded into a fighter by placing that fighter second in your ship list.)
