### ISSUE TITLE
Provide automated official nightly builds

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#4829]
**Is your feature request related to a problem? Please describe.**
During "the Hiatus" (0.9.8 - 0.9.9, see #3637) there was a growing need of nightly builds to test out the bleeding edge, especially from windows users, where compiling is rather difficult for the uninitiated. I somewhat filled that gap with unofficial nightlies, but that's not quite the same as official ones.

**Describe the solution you'd like**
With Github Actions being public, we can now run CIs & CDs without being dependant on a third party platform (other than github, which we depend on anyways). I would like to create a CD similar to [cd.yaml](https://github.com/endless-sky/endless-sky/blob/master/.github/workflows/cd.yaml), except that it runs on every new commit on `master`.

Those builds would then be released to a pre-release tag `continuous` (see for example [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy/releases)).

**Describe alternatives you've considered**
Should this be rejected, i will continue to serve nightly builds myself - but it will never be as clean and efficient as with Github Actions, since i only have one platform at my disposal, whereas GitHub has all 3 supported ones.

**Additional context**
In case it isn't clear enough, i'd like to do this myself, since I'm already doing the CI changes and this is my best chance to contribute. Furthermore, i've already layed the foundation - a Linux CD has been merged this week and will run with 0.9.11, and some months ago i managed to build a [couple other nightlies](https://github.com/MCOfficer/endless-sky-actions/actions/runs/26740484) on an experimental fork.

**Comment by Zitchas** [comment]
This would be awesome. Both from a usage point of view and reputational. MCO's nightly builds have been extremely useful, but are likewise slightly dubious for new users: Downloading unsigned executables from unknown people on the web is kind of discouraged for good reason. Having these served from the main endless-sky github location would add a layer of respectability to the process, which could help get more people onto the bleeding edge of development of material for the game.

**Comment by tehhowch** [comment]
As long as the stable release remains visible/first, I'm fine with CD to the same tag on commits to master.

How will this work for forks? Can we make this action "opt-in"?

**Comment by MCOfficer** [comment]
There may be a sofisticated way that prevents the action from running in the first place, the same way we only make it trigger on certain branches:
```
on:
  push:
    branches:
      - master
```

If that doesn't work, we just check the repo name in the first build step, and abort with a nice message if it doesn't match `endless-sky/endless-sky`.

**Comment by MCOfficer** [comment]
I encountered some problems, so i'm currently considering doing it without releases, at least for the time being. One could still download artifacts from the Actions page.

I also noticed that this may collide with the "hand-built" releases @endless-sky  provides, so i'd like the hear his opinion on the topic as well.

**Comment by Amazinite** [comment]
Did #4861 accomplish this?

**Comment by MCOfficer** [comment]
The scope of this issue was to have public Nightly builds for everyone. Currently builds are awkwardly hidden away in the actions tab, and to download them you need a GitHub account.

**Comment by MCOfficer** [comment]
:tada: https://github.com/endless-sky/endless-sky/releases/tag/continuous
