### ISSUE TITLE
Trouble starting free worlds campaign

### ISSUE THREAD

**Issue by cool833** [endless-sky/endless-sky#483]
this game is awesome and ive played for a while.
i started a new game with the latest patch (0.8.9) and all was well and good
but then i tried to start the free worlds campaign on deep and the message wouldn't come up
im unsure if im doing something wrong or if its a bug
i have a combat ranking of 3, a fire bird warship, the bombings of Geminus have happened, im going into the spaceport at deep in kornephoros.
im not a computer whiz so im not sure whats wrong
sorry if this is an inconvenience
i haven't received any missions from the space port since the tutorial

**Comment by thenerdfreak** [comment]
Try other southern planets, I think which oen it happens on is random (I might be wrong)

**Comment by cool833** [comment]
ill try, it always happens on deep for me

**Comment by cool833** [comment]
you were right , i has the dumb
