### ISSUE TITLE
FW Blackbirds kept after mission

### ISSUE THREAD

**Issue by FixItYondu** [endless-sky/endless-sky#4833]
**Describe the bug**
After you fight the Navy in Rastaban and take prisoners, you are given the choice of either keeping them or returning them. If you return the prisoners and then land without the Blackbirds in the system, you will still talk to Alondo and Freya and begin the Southern Break. This gives the player 5 free Blackbirds without having done anything at all to earn them. 

**To Reproduce**
1. Land on New Iceland (Kaus Borealis) with the Blackbirds in the system. 
2. Leave New Iceland and then land on Dancer (Rastaban) without the Blackbirds in the system. 
3. You should get a small dialog box that says you have left the ships behind, but once you click OK you will still be able to continue with the dialog for starting the Southern Break and leave the planet with 5 Blackbirds now following you around. 

**Expected behavior**
I would expect the mission to start the Southern Break would not begin until the mission to release the prisoners is finished. 

**System (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Game Source: self-compiled
 - Version: [commit hash d939a6f]

**Link to save file**
[Sheev Palpatine.txt](https://github.com/endless-sky/endless-sky/files/4226098/Sheev.Palpatine.txt)

**Comment by Amazinite** [comment]
Fixed in e6a7154.
