### ISSUE TITLE
Friendly ships manually targeted with Heavy Rockets should become hostile

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4836]
**Describe the bug**
Targeting friendly ships (not escorts) with Heavy Rockets doesn't make them hostile

**To Reproduce**
1. Take off
2. Left-click a friendly AI ship (not an escort)
3. Fire Heavy Rockets at it and hit it
4. Observe that it doesn't become hostile

**Expected behavior**
The ship should become hostile, same as if you shot it with any other weapon

**System (please complete the following information):**
 - Game Source: self-compiled
 - Version: current master

**Additional context**
I see https://github.com/endless-sky/endless-sky/issues/1341#issuecomment-234122992 but I think that issue is not the same as this one. #1341 and #821 are about splash damage. I'm not asking to change _that_, only to change what happens when I specifically target (left click) the friendly AI ship in order to be able to hit it in the first place.

Discussed on discord, @Zitchas said:
> So basically, have the AI do a check: If hit by AoE, check to see if targeted. If being targeted, treat as hit by normal directed fire weapon.

And by the way: Try doing this in a Vanguard with HRLs mounted in all gunports...

**Comment by downRightCoder256** [comment]
> And by the way: Try doing this in a Vanguard with HRLs mounted in all gunports...

try doing this in a kestrel with extra gun ports (spoilers: 18 gun ports !). tears through quarg ships like a hungry child through pancakes

**Comment by downRightCoder256** [comment]
i would suggest fixing this issue by adding something like "target" tag to munition? im not quite familiar with the core game code yet

**Comment by McloughlinGuy** [comment]
Hitting ships with nukes doesn’t make them hostile, either.

**Comment by Amazinite** [comment]
This occurs with any blast radius weapon.
