### ISSUE TITLE
In latest stable, missions aren't clearing when you land in the target port

### ISSUE THREAD

**Issue by djr255** [endless-sky/endless-sky#484]
I'm probably getting the terminology wrong, but I'm noticing that on some missions, the reward doesn't appear the first time I land at the location specified as the mission's target port.  Usually it shows after I exit the port and land there again.

This is a bug

**Comment by endless-sky** [comment]
Is it possible that these are escort missions and that the ships you are escorting have not yet arrived in system?

**Comment by djr255** [comment]
Could be.  It might be nice to provide a message that that is the case if so.  Thanks for your quick response.

**Comment by brick96** [comment]
It does tell you if you left your escort behind though

**Comment by endless-sky** [comment]
This could also happen if you have multiple ships in your fleet and the one carrying the mission cargo has not yet arrived in system.
