### ISSUE TITLE
Wanderer storyline Korath Exile peacemaking quest

### ISSUE THREAD

**Issue by Unagiflum** [endless-sky/endless-sky#4840]
**Describe the bug**
Near the end of the Wanderer campaign there's a mission where you take Rek (Wanderer leader) to Korath Exile space in order to make peace with them. The blue arrow (at the starting Kor Efret system, Sevrelect) is bold to start with, indicating you should return there to complete the  quest. 

Additionally, if you return there before visiting that planet in Korath Exile space, the mission text tells you that Rek's ship did not make it back yet and you should go find it. However, Rek is a passenger on your flagship when the quest starts.

**To Reproduce**
1. Go through the late Wanderer storyline to the point you're about to deal with the Kor Sestor drones
2. Start the Korath Exile reconciliation quest from Sevrelect, where Rek is.
3. Return to the Kor Efreti planet in Sevrelect without completing the quest.

**Expected behavior**
1. The blue flag on Sevrelect should be dim until you've visited the Korath Exile planet
2. If you return without visiting the planet, the mission text should tell you to keep looking, maybe give a hint to look in Korath Exile space.

**Screenshots**
I apologize: I'm past that point in the story line and can't currently reproduce the bug. I didn't think to submit this until later.

**System (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Source: Steam
 - Version: 0.9.9

**Link to save file**
Sorry, I don't have a relevant one any more.

**Additional context**
N/A

**Comment by Amazinite** [comment]
d719f66 fixed the visit message and #4766 fixed the color of the marker.
