### ISSUE TITLE
Game crashes on launch Windows 8.1 64 bit

### ISSUE THREAD

**Issue by xahldera** [endless-sky/endless-sky#4845]
**Describe the bug**
The game crashes to desktop after launching.

**To Reproduce**
1. Install game, either via github zip or Steam.
2. Attempt to launch game through Steam or directly via executable.
3. Game displays white window/screen and crashes to desktop if affected. Generic Windows "Program has stopped working" error message window appears with options to report to Microsoft and close program

**Expected behavior**

**System (please complete the following information):**
 - OS: Windows 8.1 Pro [Version 6.3.9600]
 - Game Source: Steam and zip from Github
 - Version: 0.9.11 Beta

**Link to save file**
N/A, Game does not open far enough to load a save file.

**Additional context**
The previous version of the game, 0.9.10, works with no issues.
The problem occurs regardless of state of install i.e. whether plugins and previous save files exist or not.
The error seems to reference AMD/ATI graphics drivers. A clean install of those was attempted with no change.
Below is the full contents of the error window:
> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	EndlessSky.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	5e53f5e8
>   Fault Module Name:	atio6axx.dll
>   Fault Module Version:	22.19.171.1024
>   Fault Module Timestamp:	595c11d4
>   Exception Code:	c0000005
>   Exception Offset:	0000000000e87d30
>   OS Version:	6.3.9600.2.0.0.256.103
>   Locale ID:	2057
>   Additional Information 1:	0976
>   Additional Information 2:	097634c2587303e7aaad3784ed7b4c23
>   Additional Information 3:	1ce8
>   Additional Information 4:	1ce84d9b45f84849dc1dbd8d60604796
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=280262
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\WINDOWS\system32\en-GB\erofflps.txt

**Comment by tehhowch** [comment]
If you are able to, would you mind building from source? Specifically, try checking out https://github.com/endless-sky/endless-sky/commit/cd07338252d6effa129c43e254632a0c6bdf7fd5 and building it.

**Comment by xahldera** [comment]
> 
> 
> If you are able to, would you mind building from source? Specifically, try checking out [cd07338](https://github.com/endless-sky/endless-sky/commit/cd07338252d6effa129c43e254632a0c6bdf7fd5) and building it.
> 
> A general how-to is on [the wiki](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#windows)

No promises as I don't have the required tools. I do however have other PCs and this one is capable of dual booting to Win10 so I will try to test the game there as well.

**Comment by tehhowch** [comment]
I actually have a .zip artifact from the commit before the one I linked: https://ci.appveyor.com/project/tehhowch/endless-sky-e505w/builds/30766963/artifacts

Please try with that one, and then also with this one:

**Comment by xahldera** [comment]
The commit in the first link works with no problems. The second one crashes with the same problem I detailed above. Error details below.

>   Problem Event Name:	APPCRASH
>   Application Name:	EndlessSky.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	5e550b3b
>   Fault Module Name:	atio6axx.dll
>   Fault Module Version:	22.19.171.1024
>   Fault Module Timestamp:	595c11d4
>   Exception Code:	c0000005
>   Exception Offset:	0000000000e87d30
>   OS Version:	6.3.9600.2.0.0.256.103
>   Locale ID:	2057
>   Additional Information 1:	4687
>   Additional Information 2:	4687da025f134688b736d12237ed2353
>   Additional Information 3:	bef6
>   Additional Information 4:	bef6c1b5c02a949716e71a9e066d4864

**Comment by MCOfficer** [comment]
cc @AdamKauffman (#4472 seems to be responsible)

**Comment by xahldera** [comment]
If it helps, I have tried running the games on Windows 10 64 Bit Pro (Forgot to check build number) and it seemed to launch OK there.

**Comment by tehhowch** [comment]
> (#4472 seems to be responsible)

This was my thought as well when OP was able to execute the parse test just fine.
It's interesting that Win8 fails but Win10 does not.


> The commit in the first link works with no problems. The second one crashes with the same problem I detailed above. Error details below.
> 
> > Problem Event Name:	APPCRASH
> > Application Name:	EndlessSky.exe
> > Application Version:	0.0.0.0
> > Application Timestamp:	5e550b3b
> > Fault Module Name:	atio6axx.dll
> > Fault Module Version:	22.19.171.1024
> > Fault Module Timestamp:	595c11d4
> > Exception Code:	c0000005
> > Exception Offset:	0000000000e87d30
> > OS Version:	6.3.9600.2.0.0.256.103
> > Locale ID:	2057
> > Additional Information 1:	4687
> > Additional Information 2:	4687da025f134688b736d12237ed2353
> > Additional Information 3:	bef6
> > Additional Information 4:	bef6c1b5c02a949716e71a9e066d4864

Thanks - that the second link fails for you means the issue is not from the Steam runtime, so we can fix it without requiring @endless-sky to do the tests.

**Comment by tehhowch** [comment]
> If it helps, I have tried running the games on Windows 10 64 Bit Pro (Forgot to check build number) and it seemed to launch OK there.

Are these two OS using the same hardware? Knowing more about the respective video capabilities should help identify the source of the issue.

**Comment by xahldera** [comment]
> 
> 
> > If it helps, I have tried running the games on Windows 10 64 Bit Pro (Forgot to check build number) and it seemed to launch OK there.
> 
> Are these two OS using the same hardware? Knowing more about the respective video capabilities should help identify the source of the issue.

Yes. Same motherboard, RAM and GPUs. The system is dual booting from two separate boot drives. GPUs are 2 AMD R9 280X's in Crossfire array but doesn't seem to make any difference if Endless Sky is run in a window or full screen. AMD has not updated the Win8.1 drivers for some time while the Win10 drivers seem to still be getting updates.

**Comment by AdamKauffman** [comment]
I don't have a Win8 system handy to verify and debug. I wonder if it's the adaptive vsync that triggers and exception in the ATI driver. That's the only change I can think of that would effect the graphics. Now I wish I had a setting for that so we could quickly flip it off for testing. Alas, I haven't dug in to adding settings yet.

**Comment by tehhowch** [comment]
I'd rather they not update the driver so we can test changes. We should probably be querying for the swap_tear extension support before assuming it can be used.

**Comment by xahldera** [comment]
@AdamKauffman I believe the last time I did that it caused some PC and GPU issues so I will avoid that for now.

@tehhowch The Win8.1 installation will remain as is as far as I can maintain it. In the meantime I will continue running the current stable release to play and will look into installing the tools to build from source myself.

**Comment by xahldera** [comment]
Tried to follow the instructions to build from source. Getting this despite having made sure the dependencies for the two required files are set.
```

||=== Build: Release in EndlessSky (compiler: GNU GCC Compiler) ===|
\Program Files\mingw64\x86_64-w64-mingw32\lib\libmingw32.a||No such file or directory|
\Program Files\mingw64\x86_64-w64-mingw32\lib\libopengl32.a||No such file or directory|
||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 40 second(s)) ===|

```

**Comment by AdamKauffman** [comment]
@xahldera You have to edit your linker settings as seen here:
https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#development-libraries

**Comment by xahldera** [comment]
> 
> 
> @xahldera You have to edit your linker settings as seen here:
> https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#development-libraries

Done that. Still nothing. I'll double check it later in case I configured linker settings incorrectly. But frankly, I would not put it past there being something wrong deep within my Windows 8.1 install.

**Comment by xahldera** [comment]
OK I have tried building from source on the Win10 boot drive, same PC. It runs fine there. Try to run the compiled binary on the Win8.1 installation and still getting the same error.

 ```
Problem Event Name:	APPCRASH
  Application Name:	EndlessSky.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5e7106c8
  Fault Module Name:	atio6axx.dll
  Fault Module Version:	22.19.171.1024
  Fault Module Timestamp:	595c11d4
  Exception Code:	c0000005
  Exception Offset:	0000000000e87d30
  OS Version:	6.3.9600.2.0.0.256.103
  Locale ID:	2057
  Additional Information 1:	0b65
  Additional Information 2:	0b65233d69231c65a0eef71195f3fbf6
  Additional Information 3:	14ee
  Additional Information 4:	14ee42118d6ce41ce705c32b493150a7

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-GB\erofflps.txt

```
If you need any further details let me know.

**Comment by xahldera** [comment]
New update. Used a workaround to install more up to date drivers from AMD intended for Windows 10 and oddly Windows 7. Beta now works. Seems the bug lies in AMD's approved drivers for Windows 8.1 for my GPU. For those who might be having issues, details can be found here: https://community.amd.com/thread/246796

**Comment by Zitchas** [comment]
Good work tracking down where the bug was. I'm glad you got it working.

**Comment by tehhowch** [comment]
> Good work tracking down where the bug was. I'm glad you got it working.
> 
> Does that mean that this bug is no longer relevant, or is it feasible to figure out a way to fix it so that the buggy 8.1 drivers are irrelevant? (I'm not a coder, so I'm not sure if that's even possible within the scope of the engine.)

The bug is relevant. The simplest fix is to roll back the relevant code that caused the issue (setting adaptive vsync when the system drivers do not support it), and then reimplement the feature correctly, including a runtime-adjustable preference setting. It is our responsibility to not release code that crashes when doing minimally expected things such as launching the game.

**Comment by tehhowch** [comment]
@xahldera if possible, please test the latest commit using the original drivers. Our CD pipeline should put a .zip file [here](https://github.com/endless-sky/endless-sky/releases/tag/continuous) that you can use, to avoid needing to recompile locally.

**Comment by xahldera** [comment]
> 
> 
> @xahldera if possible, please test the latest commit using the original drivers. Our CD pipeline should put a .zip file [here](https://github.com/endless-sky/endless-sky/releases/tag/continuous) that you can use, to avoid needing to recompile locally.

I'll give it a shot but trying to install the new drivers in the first place was such an annoying process that rolling back may take some effort.

**Comment by xahldera** [comment]
OK that latest commit seems to be working. Bizarrely the current beta also now seems to work. I am now concerned I may have lead everyone on a wild goose chase. This is strange as when I previously uninstalled and reinstalled the current drivers the game definitely was not running.

![Untitled](https://user-images.githubusercontent.com/61440486/79670544-c27c1280-81bb-11ea-823f-b7a94c2f44c6.png)

**Comment by tehhowch** [comment]
Well, glad it is resolved then.

(One last thing to check would be whether you can toggle through the states in the vsync setting added in #5000 - a "PR build" is available here: https://ci.appveyor.com/project/tehhowch/endless-sky/builds/32275771/artifacts )

**Comment by xahldera** [comment]
OK I spoke too soon. The current beta on Steam no longer works. The PR build crashes if I try to change anything in the settings menu.

**Comment by tehhowch** [comment]
Excellent news, then.

(On that PR build, if you open your `preferences.txt` file, set the "vsync" value to `0`, and then launch the game, you should be able to toggle from "off" to "on" in Settings menu. Clicking "on" will attempt to enable "adaptive" mode, and then if that fails, "off", so that tells me we've at least fixed the critical issue.)
