### ISSUE TITLE
Missing Steam executable (MacOS)

### ISSUE THREAD

**Issue by UnciaPrima** [endless-sky/endless-sky#4847]
Hello everyone

I've just installed 0.9.11 beta on Steam, and I believe there's an issue with the executable path. Has to do with naming ("Endless Sky" instead of "EndlessSky").

I think the issue existed before but it has apparently reappeared.
I have no idea how to fix this, but I just wanted to point this out.

Thank you for reading
U-P

**Comment by MCOfficer** [comment]
This has been reported by another user on reddit:
https://www.reddit.com/r/endlesssky/comments/f97qha/an_issue/

We already had this problem with 0.9.10: https://steamcommunity.com/app/404410/discussions/0/1631916406861002350/

**Comment by tehhowch** [comment]
Yes, this happened in a previous release as well: https://github.com/endless-sky/endless-sky/issues/4558

I've notified MZ, so it will get resolved one way or another.

**Comment by UnciaPrima** [comment]
Thank you.
For now, I've been able to temporarily fix this by renaming folders inside the SteamApps folder to match the Steam executable path.

**Comment by tehhowch** [comment]
Should be fixed
