### ISSUE TITLE
Editing the game data to reduce pirate fleets

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#485]
Can you please help? My B-i-l wants fewer pirates. He's of the opinion that there are just way too many pirates to make sense. (I'll leave his reasoning for another discussion.)
So, his question is: How to reduce the number in map.txt? He tried to reduce i.e. "Small Northern Pirates" 1000 to ...Pirates" 100, only to be completely swamped by hundreds of pirates coming out of the woodworks. Then, when he tried changing from ...Pirates" 100 to 10000, the game broke. 
The first instance reduced the numbers by one order of magnitude. The second change, attempting to undo the previous change, increased the numbers by two orders of magnitude.

Is there a way to jimmy the numbers without braking the game? (Neither of us understands what's involved with calculating the "proper" pirate ratio or spawnage.)

I apologize for asking a personal question but we're both dummies.

Edit: I'll close this issue when answered, and/or, if anyone feels this is an inappropriate question.

**Comment by brick96** [comment]
Yoy could remove the pirates bu deleting that line and the numbers are in frames I.e. 1 pirate fleet spawn per 1000 frames/60 per second= about 1 fleet every 16 seconds.
Why does that sound so quick?

**Comment by anonybosch** [comment]
@brick96 Thanks for replying but I still don't understand. He doesn't want to delete the pirates. He wants to reduce the number of pirates that propagate. He's (otherwise) quite happily playing a trading game. He hasn't started the war storyline. He's not particularly interested in the storyline. He's also something of a military historian. He wants to continue playing, trading, with the occasional pirate interference - not pirate mania. It's his contention, and with this I agree, that were there ever as many pirates (as there are in the game), during the heyday of the Dutch/British/Portuguese Indies Trading Companies, there would have never been any maritime commerce.  

Now, anyone, some nuts-and-bolts, please.

	fleet "Small Southern Merchants" 400
	fleet "Large Southern Merchants" 1000
	fleet "Small Militia" 800
	fleet "Large Militia" 1500
	fleet "Small Southern Pirates" 4000
	fleet "Large Southern Pirates" 9000

Higher numbers mean more? Fewer? What?
Lower numbers mean more? Fewer? What?

**Comment by endless-sky** [comment]
The numbers are the average time (in frames) in between arrivals of fleets of that type.

But, if you're trying to focus on trading, a better option is to be aware of what systems tend to have lots of pirates, and avoid those systems. For example, the Deep and the Paradise sectors are relatively safe, and there are no pirates at all in Hai space.

**Comment by anonybosch** [comment]
> "The numbers are the average time (in frames) in between arrivals of fleets of that type."

fleet "Small Southern Pirates" 4000 <i> A lower number would generate fleets sooner?</i> Yes/No
fleet "Large Southern Pirates" 9000 <i>A higher number would generate fleets less often?</i> Yes/No

What are the upper and lower bounds of those numbers?

What constitutes a fleet? How many ships?

Does "Small...Pirates" mean small ships or a small <b>number</b> of ships?
Does "Large...Pirates" mean large ships or a large <b>number</b> of ships?

If "Small...Pirates" (etc.) means a small number of ships per fleet, where (????.txt) and how do theses fleets themselves get reduced in size?

**Comment by brick96** [comment]
Does your friend have alot of freighters? Pirates love freighters. The more freighters, the more pirates.
A larger number mean MORE time between arrivals as a smaller number mean LESS time between arrivals.
What determines fleets is here: https://github.com/endless-sky/endless-sky/blob/890b69a926fb42926827f04184ef6fb920ac8bcf/data/fleets.txt
How exactly it determines what ships are part of a fleet I dont know but I think its random from a handful of variants. The boundaries of the numbers I dont know.

**Comment by luiges90** [comment]
"Small ... Pirates" is the _size_ of the pirate fleet.
"Small ... Pirates 1000" will spawn more frequently than "Small ... Pirates 10000"

**Comment by frameworld** [comment]
Good to know. Why not in seconds, but frames? (adds another difficulty level for understanding)

It would be nice to have one example of all configuration possibilities for what they mean. In the file, not an arbitrary place.

And I hope it is not completely random, else multiple fleets could spawn at once. I'd like to know the upper limits (all fleets defined that can possibly spawn?)

**Comment by anonybosch** [comment]
Thank you, one and all. Reducing the iterations of pirates in fleets.txt achieved the effect my Brother-in-law hoping for - fewer pirates scampering around while he blithely trades his way across the galaxy. He hasn't reduced the frequency (in map.txt), feeling that the mere lowered incidence of piratical NPCs is manageable for his desired game ambitions.

Again, thank you.

**Comment by bobafetthotmail** [comment]
That's a good starting point for a "game difficulty" setting.
