### ISSUE TITLE
Tweak disable threshold formula.

### ISSUE THREAD

**Issue by MasterOfGrey** [endless-sky/endless-sky#4851]
In the early game I find it particularly frustrating that medium warships in particular are quite hard to capture and prone to being annihilated by any passing shot.

Obviously since [#3448](https://github.com/endless-sky/endless-sky/issues/3448) the formula has either been made smoother, or #3448 wasn't entirely correct, and we now have:

=FLOOR(HullMax*MAX(0.15,MIN(0.45,10/SQRT(HullMax))),1)

This is in theory fair, but the amount of hull remaining, while scaling somewhat logically by ship size, does not scale very well with the amount of damage that's likely to be incoming at the point of being disabled.

It also seems to me a tad odd that heavy human warships are capable of holding out as long as much more advanced alien warships (relatively).

I propose tweaking the inflection point slightly with this version:

=FLOOR(HullMax*MAX(0.15,MIN(0.45,14/SQRT(HullMax))),1)

The distinction is subtle, but this means the curve for remaining hull points actually doesn't flatten out and hit the 15% fixed slope until about the same max hull value as the Bactrian (technically slightly more than it). This would mean that all T1 human ships sit somewhere on the curve, making medium warships a little more likely to survive battle in a disabled state, without significantly impacting the survival rates of things like Leviathans or other craft on the small/big ends of the scales (there is some impact but it's minor), and also thematically suits the idea that there's a certain threshold of engineering that Humanity is only just approaching, to be able to keep functioning in such advanced damaged states.

**Comment by Amazinite** [comment]
I'd take it.
