### ISSUE TITLE
Cannot turn, fire, and accelerate at the same time.

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4853]
Cannot turn, fire, and accelerate at the same time.

1. Load a game that has a ship with weapons (or start a new game with a Sparrow)
2. Leave the planet
3. Hold down the buttons to turn left, accelerate, and fire.
4. Which actions you do depends on the order in which you press the buttons.

**Expected behavior**
Ship should turn, fire, and accelerate when all three buttons are pressed.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Game Source: github, self-compiled
 - Version: commit hash 6dea115d

**Comment by NomadicVolcano** [comment]
I have tried this on three computes, and it only happens on one of them. I'm going to experiment with keyboards and system settings; I suspect this issue has nothing to do with Endless Sky.

**Comment by NomadicVolcano** [comment]
I just tried running an ubuntu 18.04.4 virtual machine within the 18.04.4 machine that encountered the bug. Endless Sky runs fine within the virtual machine.

I'm going to conclude that either I'm hallucinating, or something weird is wrong with my computer.

**Comment by tehhowch** [comment]
Duplicate of https://github.com/endless-sky/endless-sky/issues/3654
