### ISSUE TITLE
Using Done or Depart key deploys fights

### ISSUE THREAD

**Issue by gregorydgraham** [endless-sky/endless-sky#4858]
I have noticed that using the "D" key to depart a planet or complete a capture will cause fighters to be deployed.  While irksome after capturing, this is extremely annoying after departing a planet.  Often I complete my business on the planet, open the map, choose a destination, and type "mdj", causing my ships to deploy fighters then jump out of the system leaving their fighters behind.

**To Reproduce**
1: Have a ship with fighters
2: land on a planet
3: Open the map and choose a course
4: type "mdj" to close the map, depart the planet, and jump out of the system
5: return to original system to retrieve fighters.

Alternatively
1: Have a ship with undeployed fighters and a flagship with nerve gas(optional)
2: Disable a Korath Chaser 
3: Board the Chaser and type "cad" to attempt capture, attack, and "done" the dialog.
4: Watch all the fighters deploy

**Expected behavior**

1: Have a ship with fighters
2: land on a planet
3: Open the map and choose a course
4: type "mdj" to close the map, depart the planet, and jump out of the system
5: note that fighters are still in their bays.

Alternatively
1: Have a ship with undeployed fighters and a flagship with nerve gas(optional)
2: Disable a Korath Chaser 
3: Board the Chaser and type "cad" to attempt capture, attack, and "done" the dialog.
4: note that fighters are still in their bays.

**System:**
 - OS: Mac OS Catalina 10.15.3
 - Game Source: Github binary
 - Version: 0.9.11

**Comment by tehhowch** [comment]
Thanks filing an issue! We noticed a report of this on Steam and will be resolving this via #4857

**Comment by tehhowch** [comment]
#4857 is merged
