### ISSUE TITLE
Typo in Ask The Quarg text

### ISSUE THREAD

**Issue by gregorydgraham** [endless-sky/endless-sky#4859]
Asking the Quarg about the Builders results in the Quarg describing them as "a flourish and thoughtful empire".  Correct grammar would be a "flourishing and thoughtful empire".

While I'm here, "thoughtful" is a bit of a strange description for an empire.  Perhaps it should be "considerate", "advanced", "enlightened", "scientific", or "philosophical"?

cf: ka'het missions.txt line 129

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/2a0d1a24cda34a6f09dd70421231db01339ca057, among some errors that others spotted.
