### ISSUE TITLE
World descriptions explain the Builders before the player knows of the Builders

### ISSUE THREAD

**Issue by gregorydgraham** [endless-sky/endless-sky#4860]
Flying through the Graveyard for the first time, I was presented with an elaborate description of the Builders, their history, and their creations: the Ka'het.

The initial world descriptions should be mysterious and intriguing, provoking the player to ask the Remnant and Quarg about the missing civilization.  Once the player has asked the Quarg descriptions become the current text.

Mac OS Catalina, Github, 0.9.11

**Comment by Amazinite** [comment]
Redoing the planet descriptions in the Graveyard is on my to-do list. I just didn't think that the descriptions being a little off was enough to block the addition of a new faction. (Ref: #4716)
In all likelihood though, the descriptions won't change based off of whether you've talked to the Remnant or Quarg about the Ka'het/Builders.

It is notable though that without having ever spoken to anybody about the Korath, the descriptions of some Korath worlds do speak about what the planet was like before, giving information that the player shouldn't really be able to know. (How do I know that the climate recently shifted?)
![image](https://user-images.githubusercontent.com/17688683/75600617-56184900-5a7f-11ea-8518-3ed38097b3d8.png)

**Comment by gregorydgraham** [comment]
There is also precedent for changing world descriptions if my memory of the Wanderers storyline is correct.

**Comment by Amazinite** [comment]
A number of planets do in fact change their description in the Wanderer campaign when the government changes (e.g. Wanderer to Unfettered, uninhabited to Wanderer), but that's a much different scenario to "You found out where these ruins are from, so now you suddenly know a bunch more about each planet you visit."

**Comment by DmitrySukhv** [comment]
Maybe it is assumed that the player is familiar with the science of planetology (especially after getting know Ijs Springborn and after completing 'asteroid terraforming' missions), being able to get tragic history of the Graveyard by first-glance. It's not so strange for a spaceman to be an expert in after-war planetology, I think.

**Comment by gregorydgraham** [comment]
I've made a simple plugin to try out some less revealing descriptions, hopefully to enable storytelling opportunities and encourage the player to seek out Remnant and Quarg knowledge.  

[expanded-kahet-missions.txt](https://github.com/endless-sky/endless-sky/files/4346830/expanded-kahet-missions.txt)

Land on Buccaneer Bay to forget about the Builders, then visit the planets to view the new descriptions (or just read them in the data file).

Landing on Covert is supposed to revert the descriptions but I don't think its working right.

Eventually, I'd like to take Remnant scientists around the graveyard and reveal the Builders story as it currently is.

Is this any good?
