### ISSUE TITLE
Target Reticle leaks information for out-of-system targets

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#4869]
**Describe the bug**
Reported by [Lyra](https://discordapp.com/channels/251118043411775489/536900466655887360/683703315061932122) on Discord:
When a ship is selected and no longer in the system, the game leaks state changes that the player probably shouldn't know about. For example, if the player disables a ship and then jumps away, that ship may get repaired by its allies while the player is out of system. The ship sprite will reflect the change from disabled to active.

**To Reproduce**
1. Disable a mission ship in a system in which it has allies
2. Jump away
3. Wait

**Expected behavior**
When the player and target no longer share a system, the target reticle *always* displays only the last known information about the target.

**Screenshots**
n/a

**System (please complete the following information):**
https://github.com/endless-sky/endless-sky/commit/c36beaaa0e5366bbcb3ff32681a1d6b041457be8

**Link to save file**
n/a

**Additional context**
My preferred solution is to persist the targeted ship/asteroid information as an Engine class member, and only update it when switching targets, or when the player shares a system with target (or the target is an owned escort), and the target is targetable (in scanner range, not cloaked, etc).
This specific case is due to the line `int targetType = RadarType(*target, step);`, as RadarType doesn't know the target is out of system.

**Comment by petervdmeer** [comment]
PR #10474 seems to fix this issue.
