### ISSUE TITLE
fuel pods dont update map

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#487]
I try to make all ships have atleast 4 jumps. After buying 2 to make my newly acquired protector refitted with a scram drive, the map said an escort would run out after 2. Remaining jumps corrects after departing.

**Comment by brick96** [comment]
Looks like the fuel remaining dosent get updated when buying pod, but gets refueled just before departing

**Comment by endless-sky** [comment]
Should be fixed in commit 7dd127e.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
