### ISSUE TITLE
Fighters and drones offer to repair you despite being unable to

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4875]
**Describe the bug**
Despite the fact that fighters and drones are unable to repair your ship, hailing them will still result in them offering the patch you up.

**To Reproduce**
1. Become disabled.
2. Hail a fighter.

**Expected behavior**
Fighters and drones don't offer to repair the player because they can't. Perhaps they mention something about asking their carrier instead. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17688683/75744231-aee71c00-5ce1-11ea-87bd-289cfbcfc064.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: self-compiled
 - Version: Latest commit as of posting (https://github.com/endless-sky/endless-sky/commit/9dce1147cd44fc75191e78401e3f90306b04dade)

**Comment by tehhowch** [comment]
Related: https://steamcommunity.com/app/404410/discussions/2/1697221074199193196/#c1741139831457534814

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/f90de64e894e9b39026b3d819bcc8ad5da649afe
