### ISSUE TITLE
Pathing error

### ISSUE THREAD

**Issue by ghost** [endless-sky/endless-sky#4877]
I found some strange behaviour in the latest release (0.9.11), which I am pretty sure must be a bug. After going through the wormhole to the Terminus system I jumped to a new system. From there I got an error in red text pop up after trying to jump back to Terminus, which went along the lines of "no valid path found". It is the first and only time that I have seen this message and had to reload the save to avoid this. I tried reproducing it under different conditions, but it didn't happen again. Maybe it had something to do with a mission I was on? I had just accepted "Remnant: Tech Retrieval" when it occurred. Sorry I can't offer more than this.

**Comment by tehhowch** [comment]
Please use the issue templates when filing issues. They include sections that request information, and if that information is not applicable to your case you can write "n/a" and then we know without asking if you have this information available.

 - Did you use the map screen to plan your jumps more than one step in advance?
 - Do you have a save file or snapshot which can be used to reproduce this issue? (Even just your current save can be helpful, e.g. to use a ship similarly outfitted.)
 - Do you have any plugins installed?

**Comment by Amazinite** [comment]
Ghost account.
