### ISSUE TITLE
[Wanderer Campaign] Kor Sestor Fighter Spam

### ISSUE THREAD

**Issue by FixItYondu** [endless-sky/endless-sky#4878]
**Is your feature request related to a problem? Please describe.**
During the mission "Wanderers: Sestor Attack", I noticed that it was nearly impossible to complete in a single ship due to a large amount of Sestor fighters and the very limited Wanderer presence in the system. The mission basically requires you to have a fleet of at least T2 ships and, even with a powerful fleet, you would take heavy losses. I felt that this was pretty imbalanced since the game was designed to do in one (obtainable) ship and the massive amount of fighters present in the system denies you the ability to complete the mission with several ships, let alone one. 

**Describe the solution you'd like**
I feel that the best solution to this issue is to increase the number of Wanderer ships in the system so that the fight becomes fairer. Currently, the Wanderer ships can fight off the first Sestor fleet (albeit with heavy losses) but get immediately swamped when the second Sestor fleet jumps in. 

**Describe alternatives you've considered**
I considered the solution of removing some Sestor carriers, but I felt that that would make the fight easier as it is designed to be difficult but doable. I think that adding some more Wanderer ships would make the fight easier but still challenging.

**Comment by Amazinite** [comment]
Dupe of https://github.com/endless-sky/endless-sky/issues/3332.

**Comment by FixItYondu** [comment]
Closing because this is a duplicate.
