### ISSUE TITLE
Lore behind new "Wanderer" alien species?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#488]
Noticed new alien species in code, and most of the names for weapons/ships seem very peaceful and natural. almost as if their weapons use sun energy and rainbows. Is this the "grow your own spaceship" kinda species people have been "wandering" about?

**Comment by endless-sky** [comment]
You'll find out when I'm done with them. :)

Also, please don't use the issues list for stuff that is not a bug or a feature request. That's what the [forum](https://groups.google.com/forum/#!forum/endless-sky) is for.

**Comment by thenerdfreak** [comment]
Didn't know there was a forum, thanks!
