### ISSUE TITLE
Buying additional restricted Outfits when selling some without license

### ISSUE THREAD

**Issue by shnwnd** [endless-sky/endless-sky#4883]
**Describe the bug**
Able to install a restricted outfit onto a ship, then purchase more of that **restricted** outfit from show outfits in cargo.

I am playing Remnant space, I don't have a Remnant license. I'm taking bounty missions. The Korath bounties in this area sometimes have Remnant Outfits in their cargo. Capturing that cargo and then installing that outfit, allows me to purchase more of that outfit into my cargo.

**To Reproduce**
1. Go to Hai Space board an unfettered ship take their hai crystal
2. Go to an outfitter
3. Install the hai crystal
4. Switch to 'Show outfits in cargo'
5. Buy a fresh hai crystal

**Expected behavior**
Selling any cargo should put it into a player re-purchase-able stock. Buying cargo should deplete this stock first, then if a license allows, more can be purchased from planet stock.

**System (please complete the following information):**
OS: Chromebook 81.0.4044.31 (Official Build) beta (64-bit)
Game Source: self-compiled
Version: commit hash 330ebab

**Link to save file**
https://hastebin.com/raw/ojipokobol
1. Load save [l]
2. Look at outfitter [o]
3. Try to buy "Crystal Capacitor" [b] (denied)
4. Leave outfitter [d]
5. Depart [d]
6. Board CheatedKorRaider [b]
7. Take both "Crystal Capacitor"s [t]
8. Land on Aventine [l]
9. Look at outfitter [o]
10. Install 1 "Crystal Capacitor" onto "Cheaty Freighter" [b]
11. Switch to 'Show outfits in cargo'
12. Buy 1 "Crystal Capacitor" [b] (bug)
13. Buy 20 "Crystal Capacitor"s [ctrl+b] (lots of bug)

**Comment by tehhowch** [comment]
Nice find! I don't believe this was introduced in 0.9.11 (but confirmation would be nice, if you are able).

**Comment by shnwnd** [comment]
I compiled 0.9.11 and can confirm it still is a bug for that tagged version. Hastebin has lost the save, so here it is recreated as a gist. https://gist.github.com/shnwnd/ea07dfcf3ad6d32f2013505d698b64d6
