### ISSUE TITLE
outfitter and shipyards menus highlight ships based on player info panel

### ISSUE THREAD

**Issue by downRightCoder256** [endless-sky/endless-sky#4887]
Description:
highlighting ships in shipyards and outfitters is not based on the ship listings as shown on present panels, but rather based on the player information menu. this can lead to player making unintended changes, such as selling ships and/or outfits that are currently not in the system.

To Reproduce:
   1. place the attached savefile into game saves/ folder and open game
   2. go to outfitter 
   3. highlight all the ships available

Expected behavior:
   of all the installed weapons on your ships, there should be exactly:
      0-1 X Beam Laser
      0-6 X Ion Cannon
      0-2 X Particle Cannon
      0-2 X Thrasher Cannon
      0-2 X Bullfrog Anti-Missile
      0-2 X Heavy Laser Turret
      0-1 X Javelin Pod
Actual behavoir:
   in addition o all of the listed above, the will also be listed:
      0-4 X Proton Gun
      0-2 X Meteor Missile Launcher
   Keep in mind that none of the ships currently landed on planet has any of these, but if you go
   player info screen, you will notice that, there is also a Manta (alongside a couple of other
   ships, they are irrelevant in this case) in Cebalrai system, with additional weaponry listed
   above.

System:
 - OS: MacOS 10.13.6 "High Sierra"
 - Game Source: Github0
 - Version: 0.9.11

**Link to save file**
[Brew Admen.txt](https://github.com/endless-sky/endless-sky/files/4293984/Brew.Admen.txt)

**Comment by tehhowch** [comment]
What's the current GitHub hash you are playing from? An issue with shipyard/outfitter selection was fixed recently.

**Comment by downRightCoder256** [comment]
could you link the PR, please? im using 8adf866

**Comment by beccabunny** [comment]
It was fixed in https://github.com/endless-sky/endless-sky/commit/6dea115d923dbfd7fd635d2a969d3624617a96c3 , some days after the release

**Comment by downRightCoder256** [comment]
that seems to does it. sorry to bother you guys, but i just cant keep my game up to date until i figure out how to compile it :(
