### ISSUE TITLE
carriers to recharge drone and fighter batteries while docked

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4888]
**Is your feature request related to a problem? Please describe**
although currently carriers will recharge drones and fighters (further referred just as “fighters”) shield and hull, they wont recharge the fighters batteries, making fighter build featuring only batteries or using solar panels unviable

**Related Issue Links**
motivated after #4885 
#4065 tackles this issue in general

**Describe the solution you'd like**
once docked, carriers will recharge the drones with any spare energy production they can offer.

**Comment by TomGoodIdea** [comment]
https://github.com/endless-sky/endless-sky/commit/f16797cfbcc8860abfed8afc14e98d9acfbb0568
