### ISSUE TITLE
Allow flagship to give fuel to escort ships

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#489]
Say that I have a secondary ship in my fleet that has just run out of fuel. I would like to give it some from my own stash, but there doesn't seem to be a way to.

If I hail my secondary ship, it just says that I don't seem to need fuel or repairs. If I try to board it, nothing happens. If I try to hail another ship and ask for help (hoping that it will help my secondary ship), it just tells me that I don't need repairs or fuel. 

Ultimately, I would like for a way to give fuel from my ship to their ship. A desired improvement beyond that would be to be able to hail a ship and get it to help my secondary ship directly. This would be especially helpful if I have enough for one jump left and I want to have that ship help out my secondary ship directly instead of having to "broker" fuel.

**Comment by thenerdfreak** [comment]
Press B

**Comment by endless-sky** [comment]
Yes, just select your ship and press B to board it. If it's out of fuel, it will hold position to let you board it and transfer some fuel over.

**Comment by natangold** [comment]
<Shift> + <B> auto-repairs the nearest fleet ship.

**Comment by Thunderforge** [comment]
Strange that this didn't work for me. It would be nice if hailing the ship would give a message saying that you can do that.

> "I'm out of fuel. If you can transfer some over, that would be great. I'll make sure that the boarding doors are ready for you."

**Comment by brick96** [comment]
If you have only enough fuel for one jump, it wont let you transfer it. Same if the ship you are askng only has one jump left

**Comment by Thunderforge** [comment]
I think I probably did have only enough for one jump left, so that explains it. Still, I feel like I should be able to get another ship to give fuel to my escort, or allow me to "broker" fuel by giving my last jump to my escort and then asking another ship for more fuel.

**Comment by brick96** [comment]
Your escorts do ask for fuel when they run out. If worse comes to worse, you can always come back to refuel them

**Comment by endless-sky** [comment]
The right solution is just to pay more attention to your escorts' fuel levels, but I think the existing game mechanics that allow escorts to ask other ships for fuel and allow the player to refuel an escort if the flagship has extra, are sufficient to handle most cases of stranded escorts.
