### ISSUE TITLE
Cannot delete player via keyboard

### ISSUE THREAD

**Issue by downRightCoder256** [endless-sky/endless-sky#4891]
**Is your feature request related to a problem? Please describe.**
One thing that Made engleski sky appeal to mi taste is its "everything should be do-able via keyboard" mentality. Unfortunately, this isn't true in some cases, one of which is deleting player's profile.

**Describe the solution you'd like**
For now, i would request for a function to let player delete a profile by pressing "d", altough i do intend to add a full list of function keys missing in game.

**Comment by Amazinite** [comment]
Such a button use to exist, but has since been intentionally removed as to avoid the accidental deletion of your pilot. #1981

**Comment by downRightCoder256** [comment]
would adding a “are you sure?” popup suffice? or remap it to something like “r” for remove ?

**Comment by downRightCoder256** [comment]
MZ seems to agree with me

> You all really need to stop playing the game while drunk, but 4b5a291 will make it so you need to actually click the button rather than using a keyboard shortcut.

but maybe it could be made for “del” or shift+d to delete it? such combo doesn't appear to be used anywhere else in game

**Comment by tehhowch** [comment]
Feel free to contribute a PR that adds your desired keybind. There was already a confirmation dialog at the time of that issue, so you won't need to do that part

**Comment by downRightCoder256** [comment]
i will see to it later, when i get the hang of the code

**Comment by tehhowch** [comment]
The confirmation dialog was amended to require additional typing (endless-sky#6433), so the keybinding could be readded.
