### ISSUE TITLE
Endless Sky 0.9.11: Rescue Miners 1 and 2 in different systems.

### ISSUE THREAD

**Issue by DutchTrader** [endless-sky/endless-sky#4892]
I'd like to report the following finding on Endless Sky 0.9.11.

Earlier in the game, Rescue Miners 1 fired on Hephaestus, destination Placer. Upon arrival on Placer, Rescue Miners 2 did not fire. However, several weeks later, on completing Terraforming Rand 5, Rescue Miners 2 fired on arrival on Rand.

I've attached the two save games that show Rescue Miners 1 was not active on the last trip before rescue miners 2 fired. Unfortunately, the history of rescue miners 1 was lost.

[DutchTrader~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/4303791/DutchTrader.previous-1.txt)
[DutchTrader~~previous-2.txt](https://github.com/endless-sky/endless-sky/files/4303792/DutchTrader.previous-2.txt)

**Comment by Amazinite** [comment]
When you did arrive on Placer and Rescue Miners 2 didn't offer, did something else offer instead?
My guess is that you had a different mission offer when you landed on Placer, and since Rescue Miners 2 is marked as `minor`, that other mission blocked Rescue Miners 2 from offering.

**Comment by DutchTrader** [comment]
Sorry, no other missions IIRC. Certainly no campaign missions. Also, mission collisions don't seem to be a problem. I sometimes get offered two campaign missions/events on the same visit to the spaceport or landing (also Endless Sky 0.9.11).

**Comment by Amazinite** [comment]
>Also, mission collisions don't seem to be a problem. I sometimes get offered two campaign missions/events on the same visit to the spaceport or landing (also Endless Sky 0.9.11)

That's because neither of those missions had the `minor` tag. It's possible for multiple missions to offer at once, but not if one of the missions has `minor` as Rescue Miners 2 seemed to have.
