### ISSUE TITLE
"FW Plasma Testing 1B" talks about the wrong ship

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#49]
When you complete "FW Plasma Testing 1B" and return to Kraz, the message if you haven't waited for the Walloping Window-Blind says that you need to wait for the Red Nile instead (Red Nile at that moment is an expanding cloud of vapour).

A minor issue, but trivial to fix.  The former is a "npc accompany save", the latter "npc kill", and the <npc> tag doesn't discriminate between them, so the message should hard-code the name of your escort.

**Comment by endless-sky** [comment]
Good catch. Fixed in 5ae0ad8.
