### ISSUE TITLE
Ships can be hailed while you are in the middle of a hyperspace jump

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#490]
When your jump drives kick in and you start zooming really fast away from the system, you are surprisingly able to hail other ships still. This is odd because the inverse is not possible: you can't hail other ships when they are in the middle of the hyperspace jump.

This sometimes leads to odd behavior. For instance, if you are currently using up fuel for your last jump, a ship you hail will offer to fuel you up. If you say yes, they will obviously be unable to catch up to you because about half a second after you end the hail, you arrive in a new system.

Thematically, it feels wrong to be accelerating to lightspeed, but then have a conversation with a ship. And again, it's not possible for other ships to be hailed when they are entering hyperspace. Plus, I'm not sure if there would ever be a case where it would be beneficial. For instance, if you want to pay off pirates, there isn't anything they can do in the last half second because their missiles and whatnot are already away.

So I think that it should be changed so that you cannot hail ships while in the middle of a hyperspace jump. I'm fine allowing that while everyone is turning around and such, but once the drive kicks in, I think that hailing should be disabled.

**Comment by jafdy** [comment]
That makes sense but it feels like filling in the details more than any thing so I would expect it to be part of a full game release (1.0) as it would have no real effect on the game.
However if someone were to program it it would be nice.

**Comment by endless-sky** [comment]
Fixed in 59d573c. It remains possible to hail ships right after you have jumper to a new system and are still decelerating, which may or may not make sense, but matches the current behavior for hailing other ships.

**Comment by Thunderforge** [comment]
I'm fine with being able to hail as you are decelerating. Thanks for fixing this!
