### ISSUE TITLE
dynamic ship heat

### ISSUE THREAD

**Issue by downRightCoder256** [endless-sky/endless-sky#4903]
endless sky currently calculates its heat based on a fixed “heat generation” attribute, associated with each power outfit separately. although this simple enough, is does have its drawbacks. Namely, it can affect the heat efficiency of outfits that have varying power output, most notably, solar panels.

My proposition is to a a “working heat” attribute (name not definite; alternatives include “heat factor”, “outfit heat”, “heat output” and others.), which the game will use to calculate heat outfit will produce in accordance to its heat output. for example, an outfit with “work heat” set to 1.5 would have 75 “heat generation” when producing 50 “power generation”.

**Related Issue Links**
issue opened on suggestion of Zitchas in #4894

**Comment by tehhowch** [comment]
All outfit attributes are pooled at a ship level and are not separable. So if two outfits each add solar generation and only one adds working heat, the working heat is based on the sum total of solar collection from both outfits, not just the one with working heat.

**Comment by downRightCoder256** [comment]
then how this work #4894

**Comment by Amazinite** [comment]
Because the solar heat isn't tied to the solar collection like you're suggesting to tie this to energy generation.

**Comment by downRightCoder256** [comment]
Ah, i think you didnt quite understand what i meant. The working heat attribute would be used to calculate heat generation at any given moment in time. The only real difference between this and solar heat is that in solar heat you pluck distamce to the sun in the formula, and here you use power generation

**Comment by downRightCoder256** [comment]
Oooh, now i understand the problem. Well, since remaking power managment code i quite a job, and i currently own no code capable machines, i guess this will have to wait till summer.
