### ISSUE TITLE
No way to say sorry after friendly fire.

### ISSUE THREAD

**Issue by bobafetthotmail** [endless-sky/endless-sky#491]
It happened at least 4 times now, for some reason I click or doubleclick on the wrong ship during a dogfight and the autoaim shoots at friendly ships (repubblic or syndacate).

Then EVERYONE of that faction goes aggro on me, and EVERY system of that faction becomes enemy.

I can only bribe the ships in the sector to stop attacking me, but there is no way to say sorry.

I mean, I'm not asking a way to erase my criminal records after I blasted away a Navy fleet and plundered merchants for hours. 

Just something that recognizes if I was shooting a few times on a friendly ship for a targeting mistake and allows me to say sorry.

Or a warning after doing friendly fire, that tells me "say sorry NOW and stop it or I'm going to call police" or something.

**Comment by endless-sky** [comment]
Damaging a ship accidentally has no permanent effect on your reputation unless you disable, board, capture, or destroy it. So, your best response is to just leave the system and wait for everyone to cool down.

Also, you could try either targeting ships via the "R" key, or using automatic firing, neither of which will target friendly ships.

**Comment by frameworld** [comment]
But if you accidentally shoot a neutral, your escorts will likely at least disable it before you can jump out.

**Comment by bobafetthotmail** [comment]
I'm on a capital ship (plus escorts) using automatic firing already. I use mouseclick to select targets.
Heavy lasers or Particle cannons (or turrets of the same), no missiles at all (not even installed).

I don't know what happens but it's at least 4 times that I'm in a battle and mysteriously all friendly turn aggro on me, and I have to reload a save since I can't play if half the map hates me.
I'm NOT pressing Tab nor I have secondary weapons. One of my hands is on the arrow keys and one is on the mouse.

One of those times I saw a Star Barge passing through my line of fire and getting damaged/killed, (like if it was an enemy, enemy ships can get damaged if they are caught in between me and an enemy I'm shooting at) other times I did not see anything, but they were large-ish battles and I have other ships in my fleet, not all are on-screen at once.

And no, when every friendly in the sector turns aggro on me, their whole faction goes aggro on me, can be seen in the map and when I jump in their systems.

Also frameworld has a point. Even in case of accidental fire, the average capital insta-kills smaller stuff, if you have a fleet with turrets... they can nuke a whole fleet of smaller stuff before you can react.

**Comment by PhoenixRiver** [comment]
Maybe it would be possible to go to a local world, talk to it and offer to pay reparations for accidentally killing ships friendly to them? You could have a time limit for it and/or they might remember how often you've done it - it might also act as a game mechanic for how assassins get away with killing targets but not suffering the consequences and explain why assassins/reparations are so expensive - have to pay off the locals/family before it doesn't go against you...

**Comment by endless-sky** [comment]
The fix to #506 should eliminate most cases where you might accidentally anger a friendly government. That plus the existing bribe mechanism seem to me to be enough to deal with this.
