### ISSUE TITLE
Depreciated outfit cost rounding error.

### ISSUE THREAD

**Issue by ErdrickXLII** [endless-sky/endless-sky#4912]
**Describe the bug**
Fully depreciated outfits cost more to buy back than what they sold for.

**To Reproduce**
1. Obtain a fully depreciated outfit (either by capture or the outfits given to you by the story.)
2. Sell it to an outfitter (e.g. the cloaking device sells for 300 000.)
3. The price to buy it back has increased slightly (e.g. that cloaking device now costs 300 318.)

**Expected behavior**
Outfits should be able to be bought back for the price you just sold them for...right?

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github download page
 - Version: 0.9.11

**Additional context**
Not sure if it happens with outfits that have been allowed to depreciate naturally.

**Comment by Amazinite** [comment]
I'm gonna take a wild guess and say that #4372 is to blame. That final 318 credits is probably the last 7 days of depreciation. The age of plundered outfits is probably 1000 when it should be 1007 as to account for the grace period.
