### ISSUE TITLE
Sometimes alt-tabbing out and back again in the game results in a crash.

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#492]
It didn't happen to me, but i saw several threads in the steam forums (e.g. http://steamcommunity.com/app/404410/discussions/0/494632768626654997/)
Found no issue in here which points to that issue, so i thought i'll bring it here into focus. If there is already an issue tell me, i'll delete this one

**Comment by endless-sky** [comment]
It might just be the pause-on-minimize "feature," which was removed in 0.8.9. (The game now keeps going even when minimized.) So, I'll see if people keep reporting that once everyone is upgraded to 0.8.9.

**Comment by Wrzlprnft** [comment]
ah ok. Thx for the info, i'll close this then
