### ISSUE TITLE
Being able to purchase property on certain planets

### ISSUE THREAD

**Issue by qwibqwib69** [endless-sky/endless-sky#4922]
In endless sky, you are limited by storage to "parking" and storing in your cargo. However,  you should be able to purchase property and build some minimal things on in like warehouses to store cargo and outfits, and landing pads that are different sizes to store ships depending on their size.(without the need to pay crew)

Of course, this should be a bit expensive depending upon what you put on the land, and for balancing the larger the item put on the land should dictate how much space it takes up an how much it cost. You should only be able to buy property in places you have contributed to (like the FW of you did their campaign, or the deep if you have a license) an shouldn't be able to buy land on hugely populated planets

Some examples of structures you may be able to build( this will take time of course)
- Small landing pad
- Medium landing pad
- Large landing pad
- Small warehouse
 - Warehouse

For more balancing, if you don't put defenses up, and depending on where it is, a pirate attack should be possible, and the land should be shieldable and turrets should be able to be built along with missiles.

**Comment by downRightCoder256** [comment]
maybe this could be made to make player pay certain fee every day for each ton of cargo (or ships, in that case) per day. seems much easier to implement.

**Comment by qwibqwib69** [comment]
Hmm, maybe you have the option to rent or buy

**Comment by downRightCoder256** [comment]
Mell, i don't see quite the need to implement such a feature, since it seems harder to do so anyway. Most players probably wont be keeping most of their cargo in permanent storage anyway. (unless it is 783 jump drives you got by farming the unfettered hai during the ceasefire with the wanderers, you psychopath)

**Comment by qwibqwib69** [comment]
Fair point, it may not be useful now but probably later in developement where something as useful is added

**Comment by downRightCoder256** [comment]
well whatever will it be, it will require a lot of work, because game currently can't even remember which ship holds what cargo. you'd have to make game remember on which planet is what warehouse, an how much does it store... might as well make player be able to fly on the planet.

**Comment by Amazinite** [comment]
Parking is free, and we already have an issue open for outfit storage (#4443), so I see little need to add a mechanic for these systems to be paid instead of free.

**Comment by downRightCoder256** [comment]
> so I see little need to add a mechanic for these systems to be paid instead of free.

umm... realism?

**Comment by beccabunny** [comment]
> umm... realism?

Gameplay > realism in this case imo

**Comment by downRightCoder256** [comment]
eh, sure

close ?

**Comment by ravenshining** [comment]
This seems more like a Gameplay += Realism issue to me.  If players have so many superfluous assets that they're parking spare ships, I think they ought to pay for it to curb the exponential growth the game is prone to succumbing to.

**Comment by Anarchist2** [comment]
Thing is, it's a non-trivial amount of code changes for a change that is easily bypassed through other means (selling, not parking), and hurts people who are parking ships for reasons other than from having too many.
If there is a balance change to stop boarding, it should attack the heart of the problem, not just one of the offshoots.

**Comment by Zitchas** [comment]
For instance, a number of people like storing "one of every ship"; or others (like myself) like to keep around all the ships I've used. Some of my pilots still have their original shuttle parked somewhere...

**Comment by wooty13** [comment]
I have the same core idea, you should be able to buy property, but I have a different view of what specifically that property should be. Here's my take:
- A real estate market that uses the same core interface as the commodity trading system
- You should be able to purchase an amount of land (no structures) that can appreciate or depreciate with time, with the ability to build structures on this land and potentially make money from those
-There should be minimal and varying property taxes
-One building could be a private town. This would grant you an amount of money from the amount of tenants who live there and their spending.
-You could build farms, factories, and other production facilities, which produce goods at a fraction of the price that they go for on the market. Farms would have relatively fixed yields, mines would be more variable
-You could build residential properties, collecting money from those who rent them
-Real estate and rental prices would be determined by several wealth factors of a planet, and there would be a certain chance that you would not be able to sell your property in a given time-frame.

**Comment by tehhowch** [comment]
Buying planetside property is not in the game's scope.
