### ISSUE TITLE
Boarding a ship when attempting to repair one

### ISSUE THREAD

**Issue by sanjayatio** [endless-sky/endless-sky#493]
Hitting "B" on a friendly ship but ...
- 1st case on a30b396; try to repair a Hai ship but suddenly everyone hated me. Since I used the vulture tactic, I definitely didn't open fire once.
- 2nd time occured in a pirate planet, prompted by a boarding window when trying to fix a gunboat. It was crowded, so I'm not sure about friendly fire.
- 3rd time with FW Escort 3 at Alniyat - a tiny pirate sniped the freighter and when I tried to repair it I got a boarding window instead. It's practically an empty space so I don't think there was a friendly fire.
No idea how to reproduce these.

**Comment by frameworld** [comment]
I got same when I double-repaired a neutral.

**Comment by endless-sky** [comment]
It's possible - especially if you click to select targets rather than using the "R" key - that you had previously managed to damage a ship of that particular government without realizing it. Since I haven't heard others reporting this, I'm going to close this report.
