### ISSUE TITLE
FW Escort 1 somewhat misleading

### ISSUE THREAD

**Issue by downRightCoder256** [endless-sky/endless-sky#4935]
**Describe the bug**
when the player gets the "FW Escort 1" the quartermaster asks him to escort convoy "to <planet> and back", implying back on the <origin>, but the destination of FW Escort 1B is always "Longjump" in the Sabik System. Maybe make things clearer by clarifying to "escort to Wayfayer and back on Longjump" ?

**Comment by Amazinite** [comment]
Good catch.

**Comment by Amazinite** [comment]
6d2def9
I changed up the dialog a bit more than just adding "and back to Longjump," as I feel like "back to" still implies we're already at Longjump.

**Comment by downRightCoder256** [comment]
Hm, github seems to hide away the "less of" and "more of" symbols. There are "destination" and "origin" texts in my original issue, but this just makes it appear silly.
