### ISSUE TITLE
zoom-in not working.

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4944]
**Describe the bug**
player cannot zoom in while in space using keyboard buttons

**To Reproduce**
1. get to space
2. press the plus (+) button

**Expected behavior**
screen should zoom in on the ship

**System (please complete the following information):**
 - OS: Linux Ubuntu 19.10 / MacOS 10.15 "Catalina"
 - Game Source: github.com
 - Version: 0.9.11

note: I've been seeing this bug for a while now, so I don't think it was introduced in 0.9.11 . I haven't really considered reporting it until I started reading endless-sky/wiki/PlayersManual#new.

**Comment by Amazinite** [comment]
Works for me on Windows. Ref: #4614?

**Comment by MCOfficer** [comment]
Can reproduce on Manjaro 19.0.2, 0.9.11 (AppImage). I also tried the place where the + would be on a US keyboard layout, and the numpad buttons. Only the standard `-` works as expected.

Since this is a bug on *nix in general (apparently), it's very unlikely to be #4614.

**Comment by downRightCoder256** [comment]
was just about to say that. besides, that issue is specifically about caps locks, which are quite finicky in macos

**Comment by finite-galaxy** [comment]
On my end (Fedora 31), `-` (hyphen) and `=` (equals), the keys to the left of Backspace, work for zooming out and in, but the `+` (plus) and `−` (minus), on the numeric keypad, annoyingly don't.

**Comment by tehhowch** [comment]
@starmlerp Please clarify which "plus (+) button" is being pressed - the one on the standard keyboard, which is shared with the `=` character, or the one on the numpad / 10key ?
Currently there is no support for the 10key for zoom in/out, as noted above.

**Comment by starmlerp** [comment]
i am using macbook air (2015 model), which doesnt have numpad. ive tested it with a usb plugin keyboard, and neither buttons work. also, my plus (+) key is shared with asteriks (*), tough i doubt it has any effect.

**Comment by tehhowch** [comment]
Therein lies the issue: the game lacks support for almost all non-standard  keyboards. You should be able to zoom out using whichever key sends the `=` character.

**Comment by MCOfficer** [comment]
I can't confirm this.

- Open ES with German layout
- use the key directly to the left of the backspace button
![image](https://user-images.githubusercontent.com/22377202/79998873-88608880-84bb-11ea-8d46-d0e3adf17e71.png)
	-> Nothing happens
- Switch to English keyboard layout (no need to close the game)
- use the same button, zoom works.

Tested on the latest continuous build (1d53792d38ad4178595561063c96b61cb1ba942c).

**Comment by tehhowch** [comment]
@MCOfficer that's two separate keys, Shift and 0, to the current panel keyhandler, which is why it didn't work in that layout. (This is also why some uppercase button key definitions in our interfaces.txt file don't get triggered by Shift+{{assigned character key}} . In those cases it is expected behavior that you can't use the keyboard to press those buttons.)
