### ISSUE TITLE
conditional spaceport news

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4945]
**Is your feature request related to a problem? Please describe.**
Currently, spaceport news will only display depending on the government of the planet and the attributes of the speaker. 

This feature request is about adding the possibility of checking for other conditional attributes, such as the players combat reputation, cargo capacity, completed missions etc..

**Related Issue Links**
brought up in #4943
could possibly aid in #4907

**Describe the solution you'd like**
Syntax I would suggest would be similar to the way missions are currently offered. For example:

```
news "human merchant anywhere warning"
	location
		government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent" "Hai"
	name
		word
			"Merchant captain"
        to show
                "combat rating" > 60
	portrait
		portrait/human02
		portrait/...
	message
		word
			"You might want to watch your back, pal. With such a reputation, you are sure to have quite a few bounty hunters chasing you around"
```

the news dialog above would only display if the players combat rating is above 60 (i am not sure if that is the point at which bounty hunters will spawn, but it is irrelevant at this point)

**Comment by downRightCoder256** [comment]
Does anyone know how code highlighting works in github?

**Comment by tehhowch** [comment]
This should be a pretty simple feature we can add in 0.9.13.

**Comment by MCOfficer** [comment]
> Does anyone know how code highlighting works in github?

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by AlbertNewton** [comment]
I used to think that events could change News, but then I checked and as of five months ago they don't seem to.

**Comment by tehhowch** [comment]
@AlbertNewton
