### ISSUE TITLE
Can't buy trade goods using the alt (x500) key any more.

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#495]
The game just switches between fullscreen and window modes. This is when using the enter key to buy. (shift+ctrl+alt+enter)

**Comment by endless-sky** [comment]
Are you using the Enter key to buy? Alt + Enter is a shortcut for "toggle full screen." You could use the space bar or the =/+ key instead; they both also work as a "buy" key.

**Comment by jafdy** [comment]
Ok thanks but I can't help think that a different key would be better. What about alt+f ?

**Comment by brick96** [comment]
B for buy?

**Comment by jafdy** [comment]
B for bank.
