### ISSUE TITLE
Request: Transformations for Land images

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#4954]
**Is your feature request related to a problem? Please describe.**
One problem that has been brought up in the past is the lack of variety in land images. A comparatively small pool of land images and an increasing number of places to land (which will be made much, much worse once moons and other uninhabited planets are opened up for visiting) quickly becomes repetitious, or will lead to the ballooning of the graphics file.

**Related Issue Links**
https://github.com/endless-sky/endless-sky/issues/3465

**Describe the solution you'd like**
The addition of some basic graphical transformations that can be applied to land images. For example, flipping horizontally or vertically, and some basic variations such as darkening or lightening. Some transformations based on the swizzles might be possible too.

The idea is that someone could use these commands to expand the landscape attribute and provide a bit more variability.

`landscape land/enceladus_3 vertical darken` 
would flip the image vertically and apply a darkening effect to the image. Even with just the vertical and horizontal flips, that could make images for gas giants, lunar surfaces, and other things without defined directional cues go much farther, since they could effectively be four different images.

**Alternatives**
Image compositing is another idea that came to mind. If we had a bunch of images of ships in the process of taking off (perhaps identified by faction or territory), we could get a sort of collage with random ships appearing in images on planets. This would significantly increase the perceived variety in the game, and make things more interesting. Of course, this would also be quite difficult. Might have to sort ships by lighting or other technical aspects as well, so they could be matched to appropriate land images.

**Comment by Amazinite** [comment]
> quickly becomes repetitious, or will lead to the ballooning of the graphics file.

On last check, there are only a small number of landscape images that are even repeated in game right now. If repetition becomes an issue, then it should be a matter of finding more landscape images, or even doing these edits of flipping and darkening yourself, not adding post processing functionality to the game's source.

And I really don't think we need to worry about the size of the game. See #4953; we're still measuring the game's size in megabytes, not even close to a single gig, while I imagine that most people have hard drives with storage space measuring in the range of terabytes, if not still some significant fraction of a terabyte (say 0.5 TB).

**Comment by AlbertNewton** [comment]
The idea of having randomly generated ships flying around is an interesting one, but I think it'd be quite difficult to implement. You'd have to have lots of images for different ships with different swizzles flying in different directions with different light intensities from different directions. You'd need a lot of images, and it might be difficult to know where to use which ones.
Or implement a 3d graphics engine. But that'd be even harder.

**Comment by NomadicVolcano** [comment]
Another possibility is to allow image manipulation for ALL images, not specifically land-based ones.

https://wiki.wesnoth.org/ImagePathFunctions
