### ISSUE TITLE
Pug don't fight player if player attacks Wanderers

### ISSUE THREAD

**Issue by leklachu** [endless-sky/endless-sky#4957]
After the Pug Arfectas arrive to defend the Wanderers, if the player attacks the Wanderers the Pug do not become hostile.

**Comment by MCOfficer** [comment]
#4955 ?

**Comment by leklachu** [comment]
Yep. Just split this part off so #4955 can be closed. Its main point was Pug not helping against Hai. That's fixed now, and is the more important because it should happen for everyone; this is lower priority.

**Comment by Amazinite** [comment]
c0b06cd
Included a compatibility mission in this one.
