### ISSUE TITLE
Map texture is mismatching on XUbuntu Bionic on 2005 Nvidia ASUS laptop 

### ISSUE THREAD

**Issue by sijpkes** [endless-sky/endless-sky#4963]
The map textures are being mixed up with other textures on XUbuntu Bionic. The game runs brilliantly otherwise, but the map is very off-putting. I don't know much about video drivers but it could be a legacy driver issue?

I've tested the 0.9.9 release and 0.9.8 release on the XUbuntu Software center. (Image is displaying upside down for some reason, click to view the right way up....)

![20200329_182431](https://user-images.githubusercontent.com/801573/77863316-23739300-726d-11ea-82f1-2002806a7969.jpg)

**Comment by MCOfficer** [comment]
Can you provide details about your driver, specifically the output of `glxinfo -B`?

**Comment by sijpkes** [comment]
@MCOfficer this is the output for the `glxinfo -B` command:

```bash
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NV86 (0x428)
    Version: 19.2.8
    Accelerated: yes
    Video memory: 117MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: nouveau
OpenGL renderer string: NV86
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.3 (Compatibility Profile) Mesa 19.2.8
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by tehhowch** [comment]
If it can install `scons` and the various [build dependencies](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#linux), you could try a source build to see if that helps. If it doesn't, then my guess is that it is a driver issue / memory issue with your card.

**Comment by quyykk** [comment]
Closing this. If anybody else experiences this issue, feel free to create a new issue!
