### ISSUE TITLE
"minor" missing on entry missions, unnecessary on others.

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#4965]
**Describe the bug**
Right now, "Inheritance Redirection" and "Hauler VI cargo prototype 1" are missing the `minor` tag. While this is only a small problem, it does not follow the formatting of a majority of missions. Additionally, "Deep: Mystery Cubes 1" and "Deep: Scientist Rescue Timer" have a `minor` tag despite being landing missions, which cancels it out.

**Expected behavior**
Ideally, "Inheritance Redirection" and "Hauler VI cargo prototype 1" should have `minor` tags added to them, and the `minor` tags on  "Deep: Mystery Cubes 1" and "Deep: Scientist Rescue Timer" be removed.

**Comment by Amazinite** [comment]
> Additionally, "Deep: Mystery Cubes 1" and "Deep: Scientist Rescue Timer" have a minor tag despite being landing missions, which cancels it out.

Ah, yes. The copy-paste error.
