### ISSUE TITLE
Bug: Erroneous negative net value

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#497]
My net value is really just shy of 3B, but for some reason it's showing I'm massively in debt.  I don't owe any money, I've got 100 Leviathans and several other ships, and nearly a billion in liquid credits, so I definitely don't have negative net value.

![screenshot from 2015-12-22 12 42 04](https://cloud.githubusercontent.com/assets/692397/11961960/2844c156-a8aa-11e5-8923-fa787c91b404.jpg)

**Comment by endless-sky** [comment]
It's probably using a 32-bit integer somewhere. Is the displayed value
equal to your net worth minus 2^32?

**Comment by johndh** [comment]
@endless-sky I can't say for 100% certain that it is, but it's at least very close to that amount.  I've only seen it do it this one time.

**Comment by endless-sky** [comment]
Yup, it looks like I was inadvertently cropping the values to 32-bit ints when saving the game. Commit b4e18ee should fix this.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
