### ISSUE TITLE
SDL warning

### ISSUE THREAD

**Issue by finite-galaxy** [endless-sky/endless-sky#4971]
When running Endless Sky I get the following SDL warning:
```
[endless-sky]$ ./endless-sky 
(SDL message: "Negative swap interval unsupported in this GL")
```
This wasn't the case in the past. I don't know what introduced it, or when, but I suspect it might be related to f23745bdfc0ffe298c291ef2b303a2993ec42883.

**Comment by MCOfficer** [comment]
This happens when a driver doesn't support adaptive vsync, and was indeed caused by that commit. possibly related to #4845
