### ISSUE TITLE
Can hire crew on Mereti stations and planets

### ISSUE THREAD

**Issue by diggorygray** [endless-sky/endless-sky#4976]
**Describe the bug**
When landing on a Mereti stations the option to by crew is present.

**To Reproduce**
1. Complete Wanderer story plot to the point of introducing planetary mind to a station.
2. Land on Mereti station or planet and click on 'hire crew'
3. You are able to hire crew from a planet or station, some with no atmosphere.

**Expected behavior**

I'd expect Mereti stations and planets to offer no crew for hire - at least initially..

**Screenshots**
![Screenshot at 2020-04-06 01-04-14](https://user-images.githubusercontent.com/11949270/78513490-0296ca80-77a4-11ea-9bc5-7fe8b58bdce9.png)

**System (please complete the following information):**
 - OS: Mint Linux 19
 - Game Source: self complied
 - Version: "commit hash b2eaab1"

**Comment by diggorygray** [comment]
Is there merit in having a number of likely crew to be hired from a planet/station?
E.g. for some sparsely inhabited stations/planet this could be low but none zero?

**Comment by starmlerp** [comment]
as far as i know, trading, spaceport, bank and crew hiring are all part of a single attribute. this should probably be made as a feature request, rather than a bug report.

**Comment by Amazinite** [comment]
Duplicate of #1722.

**Comment by diggorygray** [comment]
Thanks Amazinite, I hadn't spotted that one (I did try what I thought was an exhaustive search - ho hum).
