### ISSUE TITLE
Killing Korath improves your rep with the Republic

### ISSUE THREAD

**Issue by erprice** [endless-sky/endless-sky#499]
I am following the Free Worlds storyline and I took advantage of a break in the action to farm up some jump drives from the Korath. Now the Republic has gone from hating me to loving me. According to the story, the Korath's very existence is unknown to all but a few powerful Syndicate executives. I think it would make far more sense if the human governments did not view the Korath as enemies, at least until the end of the FW campaign.

**Comment by erprice** [comment]
I just found that changing the various government reputations with the Korath won't work because the Korath raiders in human space won't attack anybody but the player.

So I guess the issue is whether there is a way to selectively disable rep gains from killing a particular government.

**Comment by endless-sky** [comment]
The issue is that:

1. I want Republic ships to attack the Korath if they see them, and
2. I don't want killing Republic ships to make you friendly with the Korath.

Since they only ever appear in Syndicate space, I suppose I could just have the Republic not be hostile towards them, though.

**Comment by thenerdfreak** [comment]
For now, that would suffice since the Korath ONLY go into Syndicate inhabited space, may require changing if and when the Korath Extend their raids, which wouldn't make sense either way

**Comment by endless-sky** [comment]
Well, once the other story lines exist it might need some further changes, but for now I've made only the Syndicate and Merchants be hostile toward the Korath: 97864aa.

**Comment by thenerdfreak** [comment]
What about pirates? Are they just going to ignore the Korath now too?

**Comment by bobafetthotmail** [comment]
Shhh! Shut up you fool! Might finally get a few jump drives if those %&$%£ pirates stop killing my Korath targets before I can board them! (just kidding, no offence intended)

**Comment by thenerdfreak** [comment]
Actually I managed to get the pirates to help me capture my first jumpdrive :P waited till korath was in system and paid them to stop attacking me, they worked fine

**Comment by bobafetthotmail** [comment]
Heh, those in my game are idiots then. 
I know I can pay them to stop attacking me, but that's not what I need (I can mop the floor with them). They keep attacking the Korath ship and destroy it quickly, before I can board it.

If I could pay them to get the $%& out of they system, I gladly would.

**Comment by thenerdfreak** [comment]
You can actually justify the republic liking you for killing Korath. I mean, if some hero dude is flying around killing alien spacepirates with high-tech ships I'd have some respect for them too :P can interfere with the story-line by making republic friendly during key battles, but then again so can killing a bunch of pirates anyway

**Comment by erprice** [comment]
Korath ships have a ton of crew, especially world ships, so it is super easy to quickly improve your republic reputation. And yeah, that messes with the story line. I was actually subjugating Republic planets just to get access to the really good outfits. Now they love me so I can waltz in and buy whatever I want with no trouble.

**Comment by thenerdfreak** [comment]
Some missions auto set them to hate you anyway

**Comment by bobafetthotmail** [comment]
Imho killing repubblic enemies shouldn't erase some kinds of misdeeds like say piracy or acting against them in FW.

I mean, you remain a pirate or a renegade even if you kill off evil aliens.
