### ISSUE TITLE
"View star map" Not Working

### ISSUE THREAD

**Issue by RaphaelBartlett** [endless-sky/endless-sky#4990]
No matter what If I go to the star map the game closes for some unknown reason can I have some help, please?

Steps to reproduce the behaviour:
1. Go to "Enter Ship"/ Where you can choose Trading, Job Board, Bank, Spaceport etc.
2.a Click on "Job Board"
2.b Click "M"/Any key you have changed to

Expected behaviour:
I expect to see the Map of all the systems that I should see

Unexpected behaviour:
But what I get instead is the game window disappear but Steam says that it is running and I am playing it and about a couple seconds later I get this message
![Screen Shot 2020-04-15 at 1 06 15 pm](https://user-images.githubusercontent.com/54761256/79294616-f2a48680-7f19-11ea-9805-8931a015bbc6.png)

System:
 - OS: Mac
 - Game Source: Steam
 - Version: "Master" I think it is 0.9.11

**Comment by Amazinite** [comment]
Do you or did you have any plugins?
Can you provide a save file (as the issue template has a space for)?

**Comment by RaphaelBartlett** [comment]
I used to have the whole Endless Sky code in the plugin folder and I currently have the all content plugin that I ave not touched since a few months ago.

I am on v0.9.10 because I do not have the beta branch.

What do you mean as the save file?
Do you mean the files in the "Saves" Folder

**Comment by beccabunny** [comment]
If you modified the data in such a heavy way, which you did by putting the data where it shouldn't stay, you are likely to have broken it. Plugins in fact can and will corrupt a save file. It seems likely it's not a problem of vanilla

**Comment by RaphaelBartlett** [comment]
Can I fix that problem in any way?

**Comment by beccabunny** [comment]
We can't  tell without the file of your pilot, from the saves folder

**Comment by MCOfficer** [comment]
> If you modified the data in such a heavy way, which you did by putting the data where it shouldn't stay, you are likely to have broken it. Plugins in fact can and will corrupt a save file. It seems likely it's not a problem of vanilla

The base game still shouldn't crash because of invalid data. This just makes it very hard to pin down which data exactly is the problem.

> Do you mean the files in the "Saves" Folder?

Yes, specifically the named like the pilot your experienced the crash with.


For what it's worth, you might jus want to wait for 0.9.12, which is supposed to come out soon™.

**Comment by beccabunny** [comment]
> The base game still shouldn't crash because of invalid data. This just makes it very hard to pin down which data exactly is the problem

Personally, I've had it happen before when installing and removing old and broken plugins, so I'm pretty sure it's due the data having stayed the plugins folder

**Comment by RaphaelBartlett** [comment]
[Completed Test.txt](https://github.com/endless-sky/endless-sky/files/4479803/Completed.Test.txt)

I experienced a problem with this pilot.

**Comment by oo13** [comment]
The save file is corrupted.
```
mission "First Contact: Ka'het: Quarg 1"
        name "Abandoned Ringworld"
        description "Visit the Quarg and ask them about the abandoned ring in th
e middle of Ka'het space."
        landing
        to complete
                "" != 0
        destination ""
```
Planet::GetSystem() returns nullptr and MapPanel::DrawMissions() try to derefernce it, because the destination is empty.

**Comment by tehhowch** [comment]
The crash shares a cause with https://github.com/endless-sky/endless-sky/issues/1874

**Comment by RaphaelBartlett** [comment]
How do I fix the problem I have now?

**Comment by Amazinite** [comment]
Either delete the mission from your save file, or give it a valid destination.

**Comment by RaphaelBartlett** [comment]
Can I close the Issue now?
