### ISSUE TITLE
Potential heat resistance mechanic

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4996]
**Is your feature request related to a problem? Please describe.**
We currently have "resistance" attributes for ion, disruption, and slowing damage. Shield generation and hull repair are effectively resistances to shield and hull damage. There is currently an open PR for a resistance to piercing. The odd one out right now is heat damage having no direct resistance. Cooling is somewhat of a resistance to heat damage, but cooling also impacts the heat from your outfits. Any potential heat resistance attribute would only impact incoming heat damage.

**Related Issue Links**
#4521 The PR for piercing resistance.
#4517/#4520 PRs that expand the existing resistance attributes to be able to consume energy or fuel and produce heat. I imagine that heat resistance would also be able to consume energy or fuel (but not produce heat).
#2719/https://github.com/endless-sky/endless-sky/pull/2719#issuecomment-315463707 The original PR where resistances were changed to where they are now, and a comment from MZ saying how piercing and heat resistance could be added later if there's a consensus on how they should work.

**Describe the solution you'd like**
Heat damage not only increases the heat of the ship being impacted, but also increases a `heatDamageTaken` variable. This is so that we can track the heat that has only come from heat damage.
Each frame, `heat` is reduced by the cooling and heat dissipation of the ship as is done right now. `heatDamageTaken` is then reduced by the amount of heat lost to the usual means. After that, heat resistance is applied to the `heatDamageTaken`, subtracting the resistance from the damage, and whatever the `heatDamageTaken` is reduced by that frame is what `heat` is reduced by. In this way, heat resistance only ever has an impact on the heat that was directly taken by heat damage and works on a per-frame basis akin to all the other resistance or resistance-like attributes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Zitchas** [comment]
Seems logical to me that there might be heat resistance too.

A radiator gets rid of heat, but doesn't affect how much heat a car receives. On the flip side, shiny metallic foil is great for reducing how much heat a car receives, but does nothing for reducing how much heat a car already has. We've already got the former, so this would add the latter.

**Comment by Amazinite** [comment]
Closing as a "resistance" mechanic to heat doesn't make much sense given what other resistance attributes are used for (i.e. status effects).
