### ISSUE TITLE
#bug Certain Human Planets not Tributable

### ISSUE THREAD

**Issue by dragonmilk** [endless-sky/endless-sky#4999]
#bug
**Describe the bug**
After completing all available storyline (I think), I decided to tribute every human system.
I was not able to dominate the free world systems of Girtab and Alioth so far, and will update with others

**To Reproduce**
1. Beat FW Campaign
2. Beat Wanderer Campaign (?)
3. Attempt to tribute every planet in human systems
4. Oon Girtab and Alioth, my tribute demand is met with the alien, "Don't joke about that sort of thing"

**Expected behavior**
Human planets usually tell me the defense fleets will make short of me.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Steam
 - Version: Beta 0.9.11

**Link to save file**
[Danger Duck.txt](https://github.com/endless-sky/endless-sky/files/4496779/Danger.Duck.txt)

**Additional context**
During Wanderer campaign, I had to land on Ap'arak to give the Efret a tour. Problem was I captured the two arfectas there, and they blocked me from their planets. Checking the save file, I did notice wanderer rep was only -0.4 and so I adjusted it to 1.4 to continue, and decreased it back down by 1.8 when I was sufficiently high (I think 29.8 to 28.1) again. Not sure this has anything to do with the bug but thought it was worth mentioning I did tinker with save file temporarily.

**Comment by tehhowch** [comment]
Not a bug. Please read the descriptions of the planets. If you really must demand tribute from them, install plugins that expand the tribute system.

**Comment by dragonmilk** [comment]
By the way, could anyone kindly let me know how the labels are generated? I've tried editing "bug" but not sure what the proper character sequence is, thanks!

**Comment by tehhowch** [comment]
Ref #1406 #3114

**Comment by tehhowch** [comment]
> By the way, could anyone kindly let me know how the labels are generated? I've tried editing "bug" but not sure what the proper character sequence is, thanks!

You do not have permission to set labels in this repository.

**Comment by dragonmilk** [comment]
> 
> 
> Ref #1406 #3114

Got it, thanks so much! The 4 similar issues that popped up before I posted did not reflect those. I just thought it odd that I couldn't land even without bribing - perhaps these planets could let me land as well? Otherwise they are so religious as to not have a defense fleet/can't be demanded tribute from, but not above taking bribes to land.

Thanks again!
