### ISSUE TITLE
Intro quest [1 Transport] (escort to New China) not triggered if not enough passenger space

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#5]
In the main quest, after taking James onboard and landing to New Greenland, he tells the pilot to meet him in the space port for a potential other special job. First time I arrived at this point I had taken some passengers on my shuttle, so the event was not triggered it seems.

There should probably be a mini event with James telling the pilot that he found an interesting job, but that it requires 5 free passenger bunks.

**Comment by endless-sky** [comment]
I've added the capability for missions to specify a message to show if they are "blocked" from being offered, and added messages for all the intro missions.

**Comment by akien-mga** [comment]
I tried the fix with the shuttle 1st intro mission, it works great. Same thing with the freighter 1st mission if the cargo is already full of mission wares. Well done :)

**Comment by dletai** [comment]
The number of required passenger space is wrong. First mission shuttle only has 5 space and James is considered 1, so mission is blocked from the beginning.  Has this been beta tested at all?
The simplest scenario - starting a new game and trying to advance without any other mission - doesn't work.
