### ISSUE TITLE
Segmentation fault on fresh build due to non-existent config files

### ISSUE THREAD

**Issue by jozef-mitro** [endless-sky/endless-sky#50]
I created fresh build on Ubuntu 14.04 (but I assume same would go for other plaforms) and I got segfaults due to recent.txt and keys.txt (the one inside config directory) not existing.

Fixing the recent.txt part is pretty easy. Just check inside PlayerInfo::LoadRecent() if creating ifstream was successful.

Fixing the keys.txt part would either require check before actually trying to load them or modifying, so that it can handle file not existing and either return error value or throw exception?

Btw. installing game from ppa didn't result in segfaults. I assume the config files are already created in those.

**Comment by endless-sky** [comment]
Oops. It looks like that's actually a bug I introduced recently when optimizing the file-loading code. Commit 35febc9 should fix it. (I tested it by deleting those files and found that the segfault goes away with that change.)

**Comment by jozef-mitro** [comment]
I tested it as well. It does fix the issue.
