### ISSUE TITLE
Need confirmation selling dialog box before (automatic) selling outfit in cargo.

### ISSUE THREAD

**Issue by universe-11** [endless-sky/endless-sky#5004]
1. If an outfit is bigger than the ship's cargo size during departure (e.g. two ships' total cargo size is bigger then that outfit), it just automatic sold the outfit and a message show up in the player log.

2. When no room for a cargo mission but the outfit cargo size is the same as cargo mission size, it just automatic sold the outfit and accept the mission.

Is there should be a choice of not selling the outfit?

**Comment by universe-11** [comment]
Find out that it just automatic selling non mission cargos during departure with a log message to fit in each ship's cargo size.

**Comment by MCOfficer** [comment]
Refs #815

**Comment by tehhowch** [comment]
Would probably be addressed by https://github.com/endless-sky/endless-sky/issues/4483#issuecomment-522987954

**Comment by universe-11** [comment]
Make the problem simple.

2 ships:    one ship with 100 cargo space, second ship with 40 cargo space. (total : 140 cargo space)
2 outfits:  one with 60 cargo space, the other with 50 cargo space.
The total cargo space is 140 which suppose to fit with this two cargo. However, the 50 cargo space cannot put in either ship after 60 outfit put in the ship. (the problem is, it will not show up the warning dialog box because the total space is enough. However, when it takeoff, the cargo will auto sold out.)

Yes. #4483 should fix this but at this moment I still can buy the 50 outfit.
Yes. It is easier to check the cargo space for each ship when a new cargo put into the ships because it must check each ship's leftover space instant of total cargo space later.

**Comment by universe-11** [comment]
----------------- patch -------------------
Simulate cargo takeoff, check cargo leftover and then landed before actual takeoff.
Warning message if there is leftover.

in PlayerInfo.h
public:
.....
line 247 (add):
	// simulate player takeoff, check cargo leftover and then landed
	// return cargo leftover size
	int SimCargoTakeoffLand();

in PlayerInfo.cpp
at end of file (add):
// simulate player takeoff, check cargo leftover and then landed
// return cargo leftover size
int PlayerInfo::SimCargoTakeoffLand()
{
	int cargoLeft = 0;

	// simulate takeoff
	for(const shared_ptr<Ship> &ship : ships)
		if(!ship->IsParked() && !ship->IsDisabled())
			if(ship != flagship)
				cargo.TransferAll(ship->Cargo());
	// Load up your flagship last, so that it will have space free for any
	// plunder that you happen to acquire.
	cargo.TransferAll(flagship->Cargo());

	// check cargo leftover
	cargoLeft = cargo.Used();

	// simulate land
	for(const shared_ptr<Ship> &ship : ships)
		if(!ship->IsParked() && !ship->IsDisabled())
				ship->Cargo().TransferAll(cargo);

	return cargoLeft;
}

in PlanetPanel.cpp
		...
		out << " Are you sure you want to continue?";
		GetUI()->Push(new Dialog(this, &PlanetPanel::TakeOff, out.str()));
		return;
	}

line 335 (add):
	// simulate takeoff to test any cargo leftover and landed
	int cargoLeftover = player.SimCargoTakeoffLand();
	if (cargoLeftover)
	{
		ostringstream out;
		out << "Warning: " << cargoLeftover <<  " ton(s) of cargo will sell off if depart " << 
			"because no ship has enough space to hold it.  Are you sure to continue?";
		GetUI()->Push(new Dialog(this, &PlanetPanel::TakeOff, out.str()));
		return;
	}

----- end of add

	// There was no need to ask the player whether we can get rid of anything,
	// so go ahead and take off.
	TakeOff();


------------ testing -------------
Buy big outfits to cargo so no ship can hold it but less than total free cargo space. Try to depart and the warning message should pop up.

**Comment by MCOfficer** [comment]
oh boy, you need [codeblocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks), big time.

**Comment by universe-11** [comment]
@MCOfficer , thanks.

----------------- patch -------------------
Simulate cargo takeoff, check cargo leftover and then landed before actual takeoff.
Warning message if there is leftover.

in PlayerInfo.h
public:
.....
line 247 (add):

```

// simulate player takeoff, check cargo leftover and then landed
// return cargo leftover size
int SimCargoTakeoffLand();

```

in PlayerInfo.cpp
at end of file (add):

```

// simulate player takeoff, check cargo leftover and then landed
// return cargo leftover size
int PlayerInfo::SimCargoTakeoffLand()
{
int cargoLeft = 0;

// simulate takeoff
for(const shared_ptr<Ship> &ship : ships)
	if(!ship->IsParked() && !ship->IsDisabled())
		if(ship != flagship)
			cargo.TransferAll(ship->Cargo());
// Load up your flagship last, so that it will have space free for any
// plunder that you happen to acquire.
cargo.TransferAll(flagship->Cargo());

// check cargo leftover
cargoLeft = cargo.Used();

// simulate land
for(const shared_ptr<Ship> &ship : ships)
	if(!ship->IsParked() && !ship->IsDisabled())
			ship->Cargo().TransferAll(cargo);

return cargoLeft;

}

```

in PlanetPanel.cpp
...
out << " Are you sure you want to continue?";
GetUI()->Push(new Dialog(this, &PlanetPanel::TakeOff, out.str()));
return;
}

line 335 (add):

```

// simulate takeoff to test any cargo leftover and landed
int cargoLeftover = player.SimCargoTakeoffLand();
if (cargoLeftover)
{
ostringstream out;
out << "Warning: " << cargoLeftover << " ton(s) of cargo will sell off if depart " <<
"because no ship has enough space to hold it. Are you sure to continue?";
GetUI()->Push(new Dialog(this, &PlanetPanel::TakeOff, out.str()));
return;
}

```

// There was no need to ask the player whether we can get rid of anything,
// so go ahead and take off.
TakeOff();

------------ testing -------------
Buy big outfits to cargo so no ship can hold it but less than total free cargo space. Try to depart and the warning message should pop up.

**Comment by universe-11** [comment]
```

        // simulate player takeoff, check cargo leftover and then landed
        // return cargo leftover size
        int SimCargoTakeoffLand();

```


```

// simulate player takeoff, check cargo leftover and then landed
// return cargo leftover size
int PlayerInfo::SimCargoTakeoffLand()
{
        int cargoLeft = 0;

        // simulate takeoff
        for(const shared_ptr<Ship> &ship : ships)
                if(!ship->IsParked() && !ship->IsDisabled())
                        if(ship != flagship)
                                cargo.TransferAll(ship->Cargo());
        // Load up your flagship last, so that it will have space free for any
        // plunder that you happen to acquire.
        cargo.TransferAll(flagship->Cargo());

        // check cargo leftover
        cargoLeft = cargo.Used();

        // simulate land
        for(const shared_ptr<Ship> &ship : ships)
        if(!ship->IsParked() && !ship->IsDisabled())
        ship->Cargo().TransferAll(cargo);

        return cargoLeft;
}

```


```

// simulate takeoff to test any cargo leftover and landed
int cargoLeftover = player.SimCargoTakeoffLand();
if (cargoLeftover)
{
        ostringstream out;
        out << "Warning: " << cargoLeftover << " ton(s) of cargo will sell off if depart " <<
                "because no ship has enough space to hold it. Are you sure to continue?";
        GetUI()->Push(new Dialog(this, &PlanetPanel::TakeOff, out.str()));
        return;
}

```

**Comment by universe-11** [comment]
```

// simulate player takeoff, check cargo leftover and then landed
// return cargo leftover size
int PlayerInfo::SimCargoTakeoffLand()
{
        int cargoLeft = 0;

        // simulate takeoff
        for(const shared_ptr<Ship> &ship : ships)
                if(!ship->IsParked() && !ship->IsDisabled())
                        if(ship != flagship)
                                cargo.TransferAll(ship->Cargo());
        // Load up your flagship last, so that it will have space free for any
        // plunder that you happen to acquire.
        cargo.TransferAll(flagship->Cargo());

        // check cargo leftover
        cargoLeft = cargo.Used();

        // simulate land
        for(const shared_ptr<Ship> &ship : ships)
                if(!ship->IsParked() && !ship->IsDisabled())
                        ship->Cargo().TransferAll(cargo);

        return cargoLeft;
}

```

**Comment by warp-core** [comment]
#7645 should address this when it is done.

**Comment by TomGoodIdea** [comment]
has https://github.com/endless-sky/endless-sky/commit/78ffa44abc7717a07dd994b9e569b3b6769f17f9 addressed this completely?
