### ISSUE TITLE
Creating new audio for new weapons is not working

### ISSUE THREAD

**Issue by CTheta** [endless-sky/endless-sky#501]
I am currently creating a massive overhaul mod.
I am stuck on trying to make custom sound effects for my weapons.
I created the .wav file I wanted and set the bitrate to 768kbps, I referenced the .wav file in data/effects.txt and data/weapons.txt, but I cannot hear it in-game at all.
I tried everything. Please help.

**Comment by CTheta** [comment]
I got one of my .wav files to work, but it was downloaded from the internet fresh, while the ones that aren't working are ones that I have exported myself.

**Comment by endless-sky** [comment]
The only supported audio format is RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz. If the file has a different sampling frequency, it won't be used.

**Comment by endless-sky** [comment]
768kbps is 48000 Hz, so 44100 Hz would be 705.6 kbps.

**Comment by CTheta** [comment]
So i need to export a 16-bit .wav file with a bitrate of 705.6 and a sample rate of 44100 Hz.
Is it really that specific?

**Comment by CTheta** [comment]
Another problem is that whenever I export in 16 bit at 44100 Hz, the bitrate is always twice as large as it should be. (1411.2 kbps). so if I want to export in 16 bit at 705.6 kbps, I have to cut the sample rate in half to 22050 Hz.

**Comment by CTheta** [comment]
Here, I'll give you the audio file, you can tell me whats wrong and what I need to do.
[photon torpedo impact.zip](https://github.com/endless-sky/endless-sky/files/71853/photon.torpedo.impact.zip)

**Comment by endless-sky** [comment]
It needs to be mono, not stereo. OpenAL won't do directional audio with anything that's stereo.

**Comment by CTheta** [comment]
I changed it to mono 16-bit PCM. that seemed to work. Thanks for your time! :smile:
