### ISSUE TITLE
Fleet gets lost when Jumping through Aescolanus

### ISSUE THREAD

**Issue by craigmccauley** [endless-sky/endless-sky#5011]
**Describe the bug**
Have a flagship with a Jump Drive, a scram drive, ramscoop and a quantum keystone. Have a fleet of 9 other ships with hyperdrives, ramscoops and quantum keystones.

**To Reproduce**
1. Start from Cinxia
2. Plot a course to Parca
3. Start jumping.
4. When flagship Jump Drives from Aescolanus to Convector many ships in the fleet get stuck in Asecolanus and will not jump elsewhere. 
5. When the flapship returns to Aescolanus some ships are way off radar. Some so far off that they continually spin when given the order to gather. When the flagship is given the order to board one of these ships it travels for >5 minutes with no sign of them.

**Expected behavior**
Fleet ships should wormhole from Aescolanus to Cardea, then hyperjump from Cardea to Antevorta, then hyperjump from Antevorta to Convector.

**Screenshots**
Fleet at Parca
![image](https://user-images.githubusercontent.com/7706831/80069083-a6b89980-8538-11ea-9468-41b20f034f87.png)
Returning to Aescolanus, fleet is off screen.
![image](https://user-images.githubusercontent.com/7706831/80073487-c0111400-853f-11ea-89ad-51ca1b68f1d1.png)

**System (please complete the following information):**
 - OS: Windows 10 Pro N, version 1909 build 18636.752
 - Game Source: Steam
 - Version: 0.9.10

**Link to save file**
[Craig McCauley.txt](https://github.com/endless-sky/endless-sky/files/4520783/Craig.McCauley.txt)

**Additional context**

**Comment by tehhowch** [comment]
Related: #4582 and probably others

**Comment by Beanzilla** [comment]
In version 0.9.12:
You can't get a fleet with hyper drives to Aescolanus it can only be accessed by jump drive.

In Aescolanus with a jump drive:
![endless_sky_issue_5011_2020-06-05_11-57-25](https://user-images.githubusercontent.com/20930999/83897708-eb347900-a723-11ea-9942-1153e1031a77.png)

Seems this bug doesn't quite make sense. (Seems like it's fixed already)

**Comment by beccabunny** [comment]
You need to explore the map better, there are multiple wormholes in the region you can pass through with a Keystone

**Comment by Beanzilla** [comment]
Ah, so that's what I was missing... ok.

thanks.

**Comment by Beanzilla** [comment]
Hmm.. Ok well now after exploring quite a bit it seems the flag ship if with a jump drive will just jump over to it... meanwhile the escorts should... eventually get there via the wormholes.

Flag Ships route (Jump Drive's path):
In Cinxia to Parca (Via directly clicking on destination)
![5011_jump_2020-06-05_12-36-10](https://user-images.githubusercontent.com/20930999/83902376-45383d00-a72a-11ea-9131-6ad5591d7598.png)

But the Escorts route (Hyper Drive's path):
In Cinxia to Parca (Took some time for it to produce the path wanted but eventually it shows it)
![5011_hyper_2020-06-05_12-34-51](https://user-images.githubusercontent.com/20930999/83902485-74e74500-a72a-11ea-9103-aa020ea06838.png)

My Test Cases:
* TO using flag ship with jump drive, seems fine... except the escorts taking the long way.
* FROM using flag ship with jump drive, alright on that.
* TO using flag ship with hyper drive (escorts also hyper), except for getting possibly attacked by Korath all good.
* FROM using flag ship with hyper, all okay.

Without knowing the route @craigmccauley is taking I am not able to reproduce this bug... (Sorry you can blame me taking the direct/shortest path when ploting a course in the map).

**Comment by craigmccauley** [comment]
@Beanzilla I used the exact route as described. While the route is correct, the escort ships don't ever arrive. They get stuck in Asc... Sometimes a few will make it through. I'll try to recreate again.

**Comment by Beanzilla** [comment]
Ah, so it might just be a different version... I am using 0.9.12.

**Comment by Beanzilla** [comment]
Ah ha!
![5011_jump_only_2020-06-05_13-15-57](https://user-images.githubusercontent.com/20930999/83904923-c2fe4780-a72e-11ea-8bf1-50ecd3c4bf84.png)

Bam! I have found it... yeah Jump drive only on flag and escorts only with hyper drives.

**Comment by craigmccauley** [comment]
Yeah, flagship has both jump drive and scram drive.

**Comment by Beanzilla** [comment]
Oh so it does also cause the issue with scram drive as well? (Interesting)

**Comment by oo13** [comment]
I reproduced this issue.

1. The flagship goes to the Aescolanus.
2. The flagship waits for the escorts to appear.
3. The flagship jumps to the Convector.
4. All escorts that have no jump drive get stuck the Aescolanus.

The escorts are set the Cardea system as the target and ship.JumpsRemaining() results 0 because the Aescolanus does not link to theh Cardea.

**Comment by akd-io** [comment]
Hey guys, I hit this error as well.
See https://streamable.com/p6vfpx and https://streamable.com/gxbwus
In the first video, the fleet was found 25k units north of the wormhole.
It seems like they are all trying to refuel the next ship in line, even though they all have enough fuel.
I am not able to get the ships out of this state without reloading an older save.

Save file: https://pastebin.com/uMRmEGga

Repro steps:
- Depart from Arculus.
- Open the map and set the course to Convector if not set already. (Notice flagship will jump from Aescolanus to Convector)
- Short-press J to jump your way to Convector.
- Now, jump between Convector and Aescolanus, waiting for your fleet to arrive before jumping back. Eventually, your fleet should get stuck on Aescolanus.

At least I am able to generate a good number of beautiful stuck-fleet-constellations.

**Comment by tehhowch** [comment]
As a temporary workaround, you should be able to land and then relaunch the game to unstick them. (Note that if they are carrying mission cargo you will trigger the pinned bug, in which case your tactic of loading an older save is recommended.)
