### ISSUE TITLE
Add on-demand automatically generated conditions

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5017]
**Is your feature request related to a problem? Please describe.**
All player-conditions are currently stored in the conditions-map in PlayerInfo and they are updated on pre-defined times.
This works fine for conditions that are explicitly set from missions (since they are set directly in the map the moment they are updated), but it causes some lag and limitations for conditions that are automatically generated (since they need to be generated on planet-landings and on entering-systems before they can be used):
- The lag is because automated conditions only get updated on pre-defined times (for example on entering a system or on landing on a planet).
- The limitation is because all conditions need to be generated up-front (and get saved to active savegames), so having a lot of automatic conditions would cause quite some overhead, especially for conditions that are rarely used and compute-intensive to generate.

**Related Issue Links**
- This comment seems very related: https://github.com/endless-sky/endless-sky/issues/3297#issuecomment-348696133
- The frequency/locations where mission checks are done also affects the lag until some mission starts or gets triggered, but that is not discussed or addressed in this request.
- The auto-testers #4308 and #4370 rely heavily on conditions for asserts and wait-loops (and rely on those being up-to-date without lag).
- #3735 (and #5412) is a specific example of conditions that can be made available through the mechanism discussed here.
- #4915 implemented an example of conditions that are automatically generated.
- #4917 added an additional conditions-update moment to reduce some lag.
- #4798 also needs conditions updated on-the-fly (and it will also need a notion/reference of "local ship" for conditions that are based on the ship for which the attribute applies)
- Mission writers might want to use new automatically generated conditions once they become possible/available.

**Describe the solution you'd like**
This feature-request is about changing automatically generated conditions from generated up-front to generated on-demand.
Effects on the ES source code is that all locations where conditions are used need to retrieve conditions in a different way; they need to retrieve required conditions by name instead of requesting the full map of conditions.

Some conditions will be read-only (like the in-game-day, in-game-month and in-game-year), but other conditions like `"unpaid maintenance"` might also be provided readable and writeable. A class like Accounts might just provide conditions for many strings that start with `"unpaid "`.

Conditions could be provided also for information currently contained in classes like Armament, CargoHold, Engine, Government, Planet, Preferences and Ship by choosing a proper prefix for each piece of information and then implementing the proper  interface on those classes.

**Describe alternatives you've considered**
Performing the conditions-generation more often; this would reduce the lag, but could increase the computational overhead (especially if we also add more auto-generated conditions).
Add a separate system for auto-generated conditions, but the ability to use all types of conditions in a single condition-set is also valuable.

**Alternatives for iterating over conditions**
We need to make some decisions on iterating over conditions as part of implementing this feature. A number of suggestions have already been tried and/or discussed; I made the following table to list them and also scored them (based on personal judgement, scale: 5 = best, 1=worst) to help compare them.

| Method                    | Description/Example                                                                   | Ref   | Compl | Read | Eff | Func | Total |
| ---                       | ---                                                                                   | ---   | ---        | ---         | ---        | ---           | ---   |
| custom/explicit functions | add functions like `int64_t PlayerInfo.GetConditionSum(const string &prefix);`        | #5244 | 3          | 1           | 5          | 5             | 14    |
| get-copy                  | `void PlayerInfo.GetConditions(map<string, int64> &targetMap, const string &prefix)`  | #5244 | 5          | 4           | 4          | 4             | 17    |
| get-return                | `map<string, int64_t> PlayerInfo.GetConditions(const string &prefix)`                 | #5244 | 5          | 5           | 2          | 4             | 16    |
| Lambda-run                | `template <typename A>; void CollapseConditions(const string &prefix, A collapseFun)` | #5384 | 3          | 3           | 4          | 4             | 14    |
| Full forward iterator    | Full forward iterator, requires all values to be generated (and most discarded)       | #5384 | 2          | 5           | 1          | 5             | 13    |
| Key only iterator         | Only provide iterator for keys. Still needs generation of keys                        | #5384 | 3          | 4           | 2          | 5             | 14    |
| Manual only iterator      | Only iterator for manual values. Others data iterates in their own datastructures     | #5384 | 5          | 5           | 5          | 3             | 18    |
| no-auto-conditions        | Don't implement automatic conditions (listed to compare to current situation)         | -     | 5          | 5           | 5          | 0             | 15    |

I compared them using the following criteria:
- *Compl*exity; How complex is the solution, higher value is simpler.
- *Read*ability; How readable and maintainable will the code be that implements the iterable access and the calls towards it.
- *Eff*iciency; How efficient will the code be. Unnecessary calculations, unnecessary access operations and unnecessary copying decreases the score for this one.
- *Func*tionality; How many operations can you perform using this implementation (compared to the alternatives).

**Additional context**
Implementation-wise I would expect this change to introduce some sort of ConditionProvider interface class that allows users of conditions to query for conditions.

Some examples of types of conditions which might become possible (after some other follow-up PRs/changes):
- amount of "Heavy Transport" escorts in the current system
- amount of "GovernmentX" owned ships in the current system
- cargo space free in ship "Power of the People".
- cargo space free in all "GovernmentX", locally present, Argossy type ships.
- crew ship selected by player if the ship is from "GovernmentX"

**Comment by tehhowch** [comment]
Related: https://github.com/endless-sky/endless-sky/issues/4798

**Comment by petervdmeer** [comment]
@tehhowch PR #4798 is about attributes that are conditional. I don't see how those are related to the (player)conditions that are used for things like triggering missions and steering conversations.

**Comment by petervdmeer** [comment]
@tehhowch Sorry, I thought about it a bit more and #4798 also needs on-demand automatically generated conditions. (It however also needs a notion of "local ship" which I didn't consider for this issue/feature request before.)

**Comment by petervdmeer** [comment]
@tehhowch: I added the current information about iterating through conditions to the feature-request text. Do you see other ways of iterating or other considerations that I should add? And how should we proceed with this feature-request?

**Comment by 1010todd** [comment]
Was pointed here about allowing `branch` in conversations to check ship attributes but it not clear to me if the current implementation will also allow that(`branch` checking attributes).

**Comment by petervdmeer** [comment]
Branches check conditions, and the implementation in #5244 is allowing new conditions to be calculated on-demand. Are you considering something like;
```
	branch too_heavy
		"flagship attributes: mass" > 10000
	branch too_weak
		"flagship attributes: hull" < 1000
	branch too_explosive
		"flagship attributes: fuel capacity" > 600

```
?
The implementation in #5244 currently does not contain the `"flagship attributes: "` query, but it should be relatively easy to add this.

**Comment by 1010todd** [comment]
Yes, something just like that. Also for custom attributes and checking the whole fleet if that's not too difficult. For fleet the sum of a value should be enough.

**Comment by petervdmeer** [comment]
@Amazinite @tehhowch 1010todd requested some additional derived conditions which I could add to #5244, but we could also implement them in a follow-up PR and just keep #5244 for getting the mechanism in place. Do you have a preference for combining or separate PRs?

**Comment by Amazinite** [comment]
I'd rather have the functionality first then add new conditions later.

**Comment by petervdmeer** [comment]
Re-opened as reminder to handle the (post-merging) open review-comments on https://github.com/endless-sky/endless-sky/pull/5244 .

**Comment by petervdmeer** [comment]
Closing again; Open comments are either handled or will get follow-up as part of in https://github.com/endless-sky/endless-sky/issues/7217
