### ISSUE TITLE
Hai water bug forced to have 2 anti-missile turret

### ISSUE THREAD

**Issue by LaPimpa** [endless-sky/endless-sky#502]
Noticed when I tried to change turrets to have 2 pulse and 1 heavy a-m. Even if I sell all the turrets I still have 2 a-m equipped.

Bug or balancement?

**Comment by endless-sky** [comment]
That was a bug. The "turret" hardpoints mistakenly had the wrong kind of anti-missile installed: 366b6d0.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
