### ISSUE TITLE
Increase Variety of Ship Names

### ISSUE THREAD

**Issue by dragonmilk** [endless-sky/endless-sky#5024]
**Is your feature request related to a problem? Please describe.**
Having boarded many a ship, I've noticed that names get re-used much sooner than expected. Perhaps a thread can be created to suggest additional names, or those started with existing lists.

**Related Issue Links**
Did not see

**Describe the solution you'd like**
We could start by incorporating the historical [list of pirates](https://en.wikipedia.org/wiki/List_of_pirates) from Wikipedia for hard targets, supplemented wtih ironic lists of [fruits ](https://simple.wikipedia.org/wiki/List_of_fruits)or [flowers ](https://www.all-my-favourite-flower-names.com/list-of-flower-names.html)for softer targets/smaller ships?

**Describe alternatives you've considered**
There are also plenty of random name generators out there like [this](https://www.name-generator.org.uk/), but that may be too random and be distracting

**Additional context**
Purely the in-game text for captured ships.

**Comment by Amazinite** [comment]
There are about 68 thousand possible pirate ship names already, with many historical pirate names already being among those. The most related issue to this would probably be #4570, as you may simply be seeing those names which are more likely to show up.

**Comment by dragonmilk** [comment]
> 
> 
> There are about 68 thousand possible pirate ship names already, with many historical pirate names already being among those. The most related issue to this would probably be #4570, as you may simply be seeing those names which are more likely to show up.
> 
> There are about 915 thousand possible merchant ship names though, so it's not as if there's no room for improvement on pirate ship names.

Oh that's interesting, I swear I see things like "Three Skeleton Key" on everything from a hawk to firebird to leviathan, so that's quite odd that it seem slike I'm seeing like 68 rather than 68 thousand possible pirate ship names. Perhaps it's an algorithm modification then - have the names in bins so it's drawing without replacement, so to speak, until the 68k are exhausted.

**Comment by Amazinite** [comment]
>I swear I see things like "Three Skeleton Key" on everything from a hawk to firebird to leviathan

Looks like that exact name has a 1/90 chance of showing up. #4657 is likely the culprit of that because of how it divided a lot of pirate names into more groups. So this is a matter of #4570 needing to be implemented.

**Comment by tehhowch** [comment]
Rather than introduce weighting to compensate for branch imbalance, the (my) preferred solution is to address the branch imbalance directly.

There's a lot that can be done with phrase interpolation now, so opportunities abound for new hails/names PRs in the coming versions.

**Comment by Amazinite** [comment]
> Rather than introduce weighting to compensate for branch imbalance, the (my) preferred solution is to address the branch imbalance directly.

1/90 for "Three Skeleton Key" versus 1/498,960 for "Shadow Lucifer" is a pretty big imbalance to fix without weightings.

**Comment by Amazinite** [comment]
As outlined by my first reply, we actually have plenty of variety in ship names. It's the weighting of these names that's the issue, which we're tracking in #4570. I have a fix for that issue in the works, so I think it's fair to close this issue now.
