### ISSUE TITLE
To stop excess cargo exist when uninstall or buy outfit into cargo space

### ISSUE THREAD

**Issue by universe-11** [endless-sky/endless-sky#5029]
To prevent excess cargo when takeoff, a check is necessary while buying outfit into cargo space or uninstall it.
A message should display if excess cargo exist and no buy or uninstall action occurred.

For multi-buy or multi-uninstall, only one message will display when excess cargo exist and no further action preformed.

***IMPORTANT***  Need ref's #5004  patch installed

in OutfitterPanel.cpp
        if(!playerShip)
            {
line 310 (add):

```

        // Find out any excess cargo
        // simulate: add this outfit to cargo, takeoff to test any cargo leftover, landed and remove this outfit
        player.Cargo().Add(selectedOutfit);
        int cargoLeftover = player.SimCargoTakeoffLand();
        player.Cargo().Remove(selectedOutfit);
        
        if (cargoLeftover)
        {
            GetUI()->Push(new Dialog(
               "Note: " + Tons(cargoLeftover) + " ton(s) of cargo will sell off if depart "
               "because no ship has enough space to hold it. You must make space for it."));
            return;
        }
        
```

player.Cargo().Add(selectedOutfit);

for(Ship *ship : shipsToOutfit)
{
in line 513 (add):
	
```

    // make sure no excess cargo if uninstall
    if(toCargo)
    {
        // simulate: add this outfit to cargo, takeoff to test any cargo leftover, landed and remove this outfit
        player.Cargo().Add(selectedOutfit);
        int cargoLeftover = player.SimCargoTakeoffLand();
        player.Cargo().Remove(selectedOutfit);
        
        if (cargoLeftover)
        {
             GetUI()->Push(new Dialog(
                   "Note: " + Tons(cargoLeftover) + " ton(s) of cargo will sell off if depart "
                   "because no ship has enough space to hold it. You must make space for it."));
             return;
        }
    }

```

ship->AddOutfit(selectedOutfit, -1);

------------ testing ----------------

Buy (big) outfit to cargo so no ship can hold it but less than total free cargo space.
A message should pop up and no buy action occurred.

Using multi-buy (big) outfits to cargo so no ship can hold it but less than total free cargo space.
Buy will occur until excess cargo reached.
A message should pop up and no further buy action occurred.

Uninstall (big) outfit to cargo so no ship can hold it but less than total free cargo space.
A message should pop up and no uninstall action occurred.

Using multi-uninstall (big) outfits to cargo so no ship can hold it but less than total free cargo space.
Uninstall will occur until excess cargo reached.
A message should pop up and no further uninstall action occurred.

**Comment by tehhowch** [comment]
Please submit patches as PRs

**Comment by Sandwichs-del** [comment]
I actually like being able to temporarily over-fill the cargo hold (https://github.com/endless-sky/endless-sky/pull/5363), but a warning icon next to cargo space and and a through take-off check would be still nice.
