### ISSUE TITLE
Prevent excess cargo (when takeoff) before accpet a mission.

### ISSUE THREAD

**Issue by universe-11** [endless-sky/endless-sky#5030]
A check for excess cargo (i.e. no ship has enough free cargo space to hold it) before player can accept cargo mission.
A message should display if excess cargo exist and cannot accept this mission until space available.

***IMPORTANT***  Need ref's #5004  patch installed

MissionPanel.cpp

<< " tons of ordinary commodities to make room for this mission. Continue?";
GetUI()->Push(new Dialog(this, &MissionPanel::MakeSpaceAndAccept, out.str()));
return;
}
line 753 (add):

```

        // Cargo and bunks space is enough for this mission
        // Need to find out any excess cargo
        // simulate: add this mission, takeoff to test any cargo leftover, landed and remove this mission
        player.Cargo().AddMissionCargo(&toAccept);
        int cargoLeftover = player.SimCargoTakeoffLand();
        player.Cargo().RemoveMissionCargo(&toAccept);

        if (cargoLeftover)
        {
            ostringstream out;
            out << "Note: " << cargoLeftover << " ton(s) of cargo will sell off if depart " <<
                "because no ship has enough space to hold it." <<
                " You must make space for it before accept this mission.";
            GetUI()->Push(new Dialog(out.str()));
            return;
        }

```

---------------- testing -----------------
Accept (big) cargo mission so no ship can hold it but less than total free cargo space.
A message should pop up and no accept action allowed.
The mission should still avaible.

**Comment by tehhowch** [comment]
Please submit patches as PRs
