### ISSUE TITLE
Confussion when an outfit in cargo and "not sold here" label

### ISSUE THREAD

**Issue by universe-11** [endless-sky/endless-sky#5031]
Cannot find "not sold here" label when that kind of outfit in cargo when this outfit not sold in planet.

------------- fix -----------------------

OutfitterPanel.cpp

string message;
if(cargo && stock)
    message = "in cargo: " + to_string(cargo) + ", in stock: " + to_string(stock);
line 175 (add):

```

    else if(cargo && (!outfitter.Has(outfit)))
        message = "cargo: " + to_string(cargo) + " (not sold here)";

```

------------ testing ------------------------
Go to a planet with 2 outfits stored in cargo and no sale available.
There should be "cargo: 2 (not sold here)" label display.
If an outfit sold, the label should be "in cargo: 1, in stock: 1".
If last outfit sold, the label should be "in stock: 2".
If 1 outfit install, the label should be "in stock: 1".
If last outfit install, the label should be "(not sold here)".

**Comment by MCOfficer** [comment]
Issues are for discussion, bugtracking and suggestions, they are *not* the place for contributions. If you want to contribute, please open a PR. If you want to open an issue, please use the issue templates.

And if you ever want to post a patch, please [format it correctly](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks), they are useless like this.

**Comment by tehhowch** [comment]
Please submit patches as PRs
