### ISSUE TITLE
CI/CD: Cancel Action runs for PRs when a new run starts

### ISSUE THREAD

**Issue by MCOfficer** [endless-sky/endless-sky#5033]
**Is your feature request related to a problem? Please describe.**
As of now, every commit is built. This is probably not very resource-friendly, as content PRs can push up to several commits a minute (especially with review suggestions).

**Related Issue Links**
#5021

**Describe the solution you'd like**
When a new run starts, it should cancel current runs.
> Cancel pending / running workflows whenever a new commit is added to a PR, to avoid redundant work. I think this will require using the REST API: developer.github.com/v3/actions there may be some marketplace actions too

There are in fact some marketplace actions .

**Additional context**
> We can add run cancelling as a follow-up [to #5021].

I created this as tracking issue so i don't forget about it.

**Comment by quyykk** [comment]
GitHub now provides this natively https://docs.github.com/en/actions/using-jobs/using-concurrency. Should we still do it?

**Comment by MCOfficer** [comment]
I'd say yes. If ~~Zitchas~~ *arbitrary content creators* address feedback, it can quickly become a commit orgy.
