### ISSUE TITLE
Fast Forward Inputs dropped in the Boarding Panel

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#5038]
**Describe the bug**
When in the boarding panel, fast forward cannot be toggled. This is contrary to every other situation in the game, where if the fast forward button is pressed, it toggles. Additionally, if Caps-Lock is the fast-forward key, then the Caps-Lock is received but not the fast forward, meaning that they can become de-synced, which, while a small issue, can be frustrating if one uses the fast-forward icon to see whether Caps-Lock is on in their game or not.

**To Reproduce**
1. Disable a ship
2. Board it
3. Try to activate/deactivate fast forward

**Expected behavior**
Fast forward should be togglable in the boarding panel, to match with every other situation.

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Self-Compiled
 - Version: b998c77eda52f89579a913aa4e100f52ad9526ef

**Comment by tehhowch** [comment]
Do not use the FF symbol to determine whether Caps Lock is enabled on your system. The FF symbol only tells you if FF mode is enabled or not.

It is indeed intentional that you cannot toggle FF state when not in active flight.

**Comment by NomadicVolcano** [comment]
It is important to be able to toggle FF at critical times, like if you just captured a ship. You may need to react rapidly to keep the ship alive. Also, the claim that you cannot toggle it in active flight is false; you can toggle it anywhere except text fields, boarding and hailing panels.

The boarding and hailing panels should both allow fast-forward, so long as it does not map to a key used by those panels.

PR #5084 fixes this bug by explicitly allowing fast-forward in boarding and hailing panels.

**Comment by NomadicVolcano** [comment]
The new fix, in #5088, is to turn off fast-forward automatically any time another window comes up on top of the main panel.

**Comment by NomadicVolcano** [comment]
> Do not use the FF symbol to determine whether Caps Lock is enabled on your system. The FF symbol only tells you if FF mode is enabled or not.

It would be possible to sync these two by handling caps-lock specially. It is a modifier, so you can check the on-off state just like you would shift and alt. That would require handling caps-lock specially though.

**Comment by Amazinite** [comment]
> **Expected behavior**
> Fast forward should be togglable in the boarding panel, to match with every other situation.

https://github.com/endless-sky/endless-sky/commit/a7aff94f439d48fc5b569451d653b45cf47053bc brings us in the reverse direction and actually turns fast-forward off while the player is not in flight (e.g. landed, in a boarding panel). This is in line with the concern expressed here:

>It is important to be able to toggle FF at critical times, like if you just captured a ship. You may need to react rapidly to keep the ship alive.

By setting FFW off in these critical times, we allow the player more time to react to such scenarios.

>Additionally, if Caps-Lock is the fast-forward key, then the Caps-Lock is received but not the fast forward, meaning that they can become de-synced, which, while a small issue, can be frustrating if one uses the fast-forward icon to see whether Caps-Lock is on in their game or not.

Any concerns over this issue should be moved over to #5177, which talks about getting rid of this desync by either checking the state of caps lock on the player's computer in order to set fast forward, or find a different key to have be fast-forward by default.
