### ISSUE TITLE
AppImage stable doesn't download

### ISSUE THREAD

**Issue by RafaelLinux** [endless-sky/endless-sky#5045]
**Describe the bug**
I tried to download the AppImage files, stable and even unstable, but it's not working.

**To Reproduce**
1. Go to 'https://github.com/endless-sky/endless-sky/releases/tag/v0.9.12'
2. Click on 'endless-sky-amd64-v0.9.12.AppImage'
3. See error ... "SignatureDoesNotMatchThe request signature we calculated does not match the signature you provided ... "

**Expected behavior**
To dowload the file

**System (please complete the following information):**
 - Firefox 75

**Comment by tehhowch** [comment]
Cc @MCOfficer

**Comment by MCOfficer** [comment]
Cannot reproduce. this was likely a temporary issue on github's end, as it has been reported at a number of repos around the same time:
https://github.com/docker/compose/issues/7433
https://github.com/AdoptOpenJDK/openjdk-website/issues/721

If the issue persists, see also https://github.com/borgbackup/borg/issues/2943#issuecomment-323326725.
