### ISSUE TITLE
Reunion is described as a Republic planet, but everything else indicates it's Syndicate-run.

### ISSUE THREAD

**Issue by michel-slm** [endless-sky/endless-sky#5046]
**Describe the bug**
Reunion is described as a Republic planet, but the system itself, Reunion, and Kraken Station in the same system are all coded as syndicate.

**To Reproduce**
Visit the Caph system, land on Reunion. Or check data/maps.txt

**Expected behavior**
The description should be that for a Syndicate world, or the system stats should be updated for that of a Republic world.

**Comment by Amazinite** [comment]
The Syndicate is a part of the Republic, so it is not wrong to for Reunion's description to mention it as being a Republic world.

**Comment by michel-slm** [comment]
Ah, fair enough, thanks! Still catching up on the backstory
