### ISSUE TITLE
Bounty Hunters (that come after you)

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#505]
Perhaps if you attack Merchants for too long, or Syndicate, Free Worlds even, they'll pay bounty hunters to go after you with heavily outfitted ships (Would add immersion and SOME form of higher penalty to piracy

**Comment by Tufton** [comment]
I like this idea.  Honestly, it doesn't even have to be one of the good
factions.  Pirates could hire bounty hunters too.  This could also be a
good mission/storytelling device if you have a strong bounty hunter in a
named ship following you that jumps out of system if you get him low and
don't finish him off.  Complete FW mission, oh noes syndicate has hired an
assassin/bounty hunter, etc etc.

Sort of a twist on pirate assassination missions, where they chase you
instead of the opposite.

**Comment by DingusShingleton** [comment]
Also, you could have one where they attempt to board you, and if they do, they kill your crew and take you prisoner. Then, you go somewhere where you eventually break out and steal a sparrow and have to escape through an enemy fleet. Throw in a nearby black hole that prevents hyperspace jumps from a certain distance and you have a serious blockade run on your hands. Then you get back to friendly space, build up a fleet, and return to get your ship back. That would be alot of fun.

**Comment by johndh** [comment]
This was one of the cool features of SPAZ (Space Pirates And Zombies), and the only way to get some of the best and coolest ships in the game.  The Syndicate seem like the most obvious users of bounty hunters, as they wouldn't have any compunctions about using an unlicensed paramilitary force or a ragtag criminal fleet to do their bidding if it benefits their ledger.  Depending on the location, maybe the offended party could even hire an alien fleet (e.g. Korath or Unfettered) to attack you if things got serious enough.

**Comment by brick96** [comment]
You can make a mission like this. Have the hunters start in a system 2-4 systems away, give them a nemesis personality and they should hunt you down.

**Comment by mrec** [comment]
There's already a "Bounty Hunter" government mentioned in [several places](https://github.com/endless-sky/endless-sky/search?utf8=%E2%9C%93&q=%22Bounty+Hunter%22) in the datafiles, but I've never seen any evidence of it in-game.

**Comment by natangold** [comment]
@mrec They're used in the "Transport VIP" mission.

**Comment by LocalGod79** [comment]
just submitted a pull request for some new ships, jobs, and a 'bounty hunted' mission, offered invisibly on landing 3% of the time, after the player gets their raw combat rating up to 59875

**Comment by LocalGod79** [comment]
Modified Leviathan and Falcon contains three bounty hunting and one bounty hunted missions as limited availability for (very) slightly tweaked ships with fancy sprites

**Comment by Amazinite** [comment]
Since we now have marauders that chase you around after a certain combat rating is reached, should this be closed?

**Comment by LocalGod79** [comment]
i don't think that the Marauders specifically address the issue of players farming Merchants (or any other faction without planets)

**Comment by tehhowch** [comment]
A similar invisible mission to the one about Pug farming could be used:
```
mission "Pug Angry at Being Farmed"
	landing
	invisible
	to offer
		or
			has "Pug Cease Hostilities: offered"
			not "chosen sides"
		"reputation: Pug" < -100
	npc kill
		government Pug
		personality nemesis heroic staying
		system "Pug Iyik"
		ship "Pug Arfecta" "Ayee Eee Eek"
```
The fleets it spawns would need a bit of discussion, but the `to offer` would be pretty simple, e.g.
```
mission "Republic Merchants Angry at the Player"
    landing
    invisible
    repeat
    source
        government Republic
    to offer
        "reputation: Merchant" < -100
        random < 5
    to complete
        "reputation: Merchant" > 1
    npc save
        government "Merchant"
        personality heroic nemesis unconstrained
        fleet "Republic Merchant Bounty Hunters"
    on fail
        "reputation: Merchant" -= 100
```
and so on for Free Worlds, Neutral, Syndicate, and Hai space. 
The fleet could be given some unique phrases related to angry merchants, and should include ships from the relevant government.
Making the these missions require saving the attacking ships, and also causing additional rep penalty beyond disable/board/cap/destroying the bounty hunters for failing the mission can slightly combat the ease with which one can increase rep with merchants. (Perhaps rep vs Korath should be -.01 for Merchants...)

**Comment by DamienThryn** [comment]
I'm working on spinning out some variants of the above.

**Comment by LocalGod79** [comment]
@DamienThryn i think the "Bounty Hunter" government makes a lot more sense than having Marauder "Merchant"s come after the player, fwiw.

this would also have the side effect of potentially confusing/overwhelming the player if they take a lot of "Marauder Hunting" jobs *while* plundering Merchants...

**Comment by Amazinite** [comment]
[The player is now able to be hunted by bounty hunters if they anger the major three governments](https://github.com/endless-sky/endless-sky/blob/master/data/pirate%20jobs.txt#L2614). All three governments become hostile when you attack merchants and you lose rep to them when you disable/destroy merchants, so tangentially the player will be attacked by bounty hunters for attacking merchants too much (as eventually attacking too many merchants will permanently anger a major government). While it isn't a different set of bounty hunters for each government you anger and it isn't directly bounty hunters sent for attacking merchants (which I think is a good thing as to avoid potentially 5 different fleets of bounty hunters chasing the player [Merchant, Republic, FW, Syndicate, and Marauders]), I think that this issue is effectively done.

**Comment by Pointedstick** [comment]
@thenerdfreak, if you're still around, can you close this issue now that the requested feature has been implemented?

**Comment by jmathes** [comment]
This feature, as is, was a mistake. It's possible to get a bounty fleet chasing you without knowing why, when there are no autosaves old enough to un-anger whoever you angered in the first place, when you are too weak to kill them even one at a time. Your feature literally, not figuratively, broke the game.

**Comment by Zitchas** [comment]
Could you elaborate on the situation? Typically the player has killed a fair bit of stuff by the time they start getting hunted.

**Comment by jmathes** [comment]
My fleet is three ships; a Blackbird, a Firebird, and a Star Queen. I've done no combat at all; transport and cargo missions only, with a few escort missions in which I ran away and hoped the escorted freighters could follow. I did a lot of missions for the Free Worlds and a few transporting There Might Be Riots around, which may have angered the Republic or the Syndicate, but which didn't require any combat.

**Comment by jmathes** [comment]
This could be fixed for me by making the act of bribing meaningful. I can pay them off, but they attack again as soon as I jump away. If bribing them made them go away for good, the game would be playable, but not if, as others online suggested, new bounty fleets have a 4% chance of spawning every time I jump worlds.  As is, it seems like my choices are to patch the game myself or quit, which sucks after having spent 16 hours in it.

**Comment by Amazinite** [comment]
Umm, the bounty hunter fleets described here were removed from the game [almost a year and a half ago](https://github.com/endless-sky/endless-sky/commit/485bb361ab31c03d329db62b5d075c0d781cbb2a).

**Comment by jmathes** [comment]
@Amazinite this is weird. It feels like you think you're in a political argument.

A bounty hunter fleet is attacking me and my combat rating is low enough that I haven't been warned about it. It sounds like your understanding of the game makes this impossible, so I guess you have to conclude that I have some reason for lying about this or that your understanding is incomplete or out of date.

**Comment by Zitchas** [comment]
OK, just to clarify, then. What version of the game are you playing? Steam version? Linux distro? 

Also worth noting that the game is under active development, and it has undergone significant changes in the past couple years.

**Comment by Pointedstick** [comment]
What version of the game are you playing? Do you have any plugins?

**Comment by jmathes** [comment]
I'm playing it through steam, yes. I'm not using any plugins or mods.

**Comment by jmathes** [comment]
Maybe this wasn't clear, but you don't have to explain to me what it means for software to be under active development. I've been a software engineer for almost 15 years.

**Comment by MCOfficer** [comment]
> The only remaining bounty hunter mission is the one that you get for having a high combat rating, which you will now be warned about 

Worth noting that this commit is not yet part of the steam version.

> @Amaziniteit sounds like your understanding of the game makes my situation impossible, so I guess you have to conclude that I have some reason for lying about this or that your understanding is incomplete or out of date. No matter which of those you choose, it seems like I should ignore you.

No need to be aggressive about it. Bluntly, yes, this should not be possible. That doesn't necessarily mean you're lying. Either you migrated those missions from an earlier version (once they have spawned, a version update won't despawn them), or you're mistaking another bounty mission for the one described in this mission.

It's hard to tell without more information. If you believe there is a bug, you might want to open an issue. Attaching your save file will go a long way of helping us figure this out.

**Comment by jmathes** [comment]
- There's very likely nothing left over from earlier versions. I installed this game for the first time three days ago.
- There are bounty hunters following me around. It may not be the ones implemented in the patch that closed this issue, but it fits the description.
- I do not think this is likely what I would call a bug. I think it's a balance issue. It's possible to be pursued by a relative-to-the-player overpowered bounty hunter fleet with no recourse.
- I think you're right to have a problem with unhelpful tone, but that you aimed your reprimand at the wrong person. I'm trying to help, and if I hadn't ignored the passive-aggressive comment I was responding to, this issue couldn't have been addressed.


https://gist.github.com/jmathes/53cff63673ce5f2528eb8974ebd981ed

**Comment by jmathes** [comment]
Reading through my savegame (which I consider cheating) seems to reveal that I'm being pursued because of mystery cube transport missions. If that's true, it should be possible to learn that this is the issue without reading my savegame.

**Comment by jmathes** [comment]
Your mentioning of missions being related to the bounty hunters gave me the idea of aborting all my missions to see whether that would get rid of the bounty hunters, and it did. Binary searching for the mission causing them to pursue me was fruitless, but aborting missions by category gave me a clue. It seems like some or all "mystery delivery" missions cause bounty hunters to pursue you. If there was a warning that this would happen or a way of discovering this without reading my savegame file, which I consider cheating, I missed it.

It seems like my original comment is a feature request for a way to identify missions that cause one to be pursued, or for more warning in the description of mystery cube missions.

**Comment by MCOfficer** [comment]
> Your mentioning of missions being related to the bounty hunters gave me the idea of aborting all my missions to see whether that would get rid of the bounty hunters, and it did. Binary searching for the mission causing them to pursue me was fruitless, but aborting missions by category gave me a clue. It seems like some or all "mystery delivery" missions cause bounty hunters to pursue you. If there was a warning that this would happen or a way of discovering this without reading my savegame file, which I consider cheating, I missed it.
> 
> It seems like my original comment is a feature request for a way to identify missions that cause one to be pursued, or for more warning in the description of mystery cube missions.

Glad to hear you found it, and feel free to open an issue for that feature request.

**Comment by jmathes** [comment]
@MCOfficer I'll do you one better:

https://github.com/endless-sky/endless-sky/pull/5721
