### ISSUE TITLE
Hotkey to switch between turret tracking modes

### ISSUE THREAD

**Issue by Jerry-Man** [endless-sky/endless-sky#5051]
**Is your feature request related to a problem? Please describe.**
The ideal turret tracking option seems to be based more on the current situation, rather than playstyle, so I end up frequently going into the prefs to switch between the two.

**Related Issue Links**
https://github.com/endless-sky/endless-sky/issues/4714

**Describe the solution you'd like**
A key in the controls menu that can switch between opportunistic and focused tracking.

**Describe alternatives you've considered**
Being able to individually set tracking mode for each turret as discussed in the thread linked above would also be a good solution.

**Comment by starscollide5** [comment]
Very nice workaround for #4714 !
