### ISSUE TITLE
Ships can jump when disabled if they started jumping before they were disabled

### ISSUE THREAD

**Issue by Rakete1111** [endless-sky/endless-sky#5058]
As the title says, any ship (including your ship) that starts the jump sequence before they are disabled can still jump out. This is especially noticeable if the ship has a jump drive. I don't know whether this is intended or not, but it's annoying when almost disabled Korath raiders manage to jump away like that.

**Steps to reproduce the behavior:**
1. Get a ship with a jump drive
2. Stay still in a pirate system
3. Wait for them to attack you
4. When you're almost disabled jump

**Expected behavior**

IMO if the jump drive animation is still playing, then the jump can't actually complete if the jump drive becomes inoperable (due to being disabled) in mid jump.

 - OS: Linux
 - Game Source: self-compiled
 - Version: 0.9.12 / 7623fae5

**Comment by Amazinite** [comment]
This just seems like part of the mechanics behind jumping (in-lore) to me. That is, we've started the jump, now there's no turning back, even if we get hit in the middle of it. Why exactly would being disabled pull you out of a jump? Is it really just because "it's annoying" that we should change this?

**Comment by Rakete1111** [comment]
> Is it really just because "it's annoying" that we should change this?

No of course not.

> This just seems like part of the mechanics behind jumping (in-lore) to me.

I can't agree. During the jump animation the jump drive is using up the 200 fuel. When it reaches 200 the actual jump happens. So, if the jump drive is disabled it can't actually use any more fuel and the jump should fail.

Also, IMO the jump drive animation is just the preparation for the jump. The actual change in systems is instantaneous. If the preparation for the jump is stopped for whatever reason, then you can't actually jump. At least that's how I see it.

**Comment by starmlerp** [comment]
keep in mind that the same happens with the hyperdrive, although it is harder to recreate

**Comment by Amazinite** [comment]
As mentioned on the PR, I think that the current functionality is preferable to the suggest change. There also seems to be a lack of strong feeling for any change in the current system. As such, I've closed the PR, so I think the issue should be closed as well.
