### ISSUE TITLE
Sunbeam and Pulse weapons incorectly working together.

### ISSUE THREAD

**Issue by Ben-Wise** [endless-sky/endless-sky#5062]
I have encountered a bug where if using Sunbeam weapons (turrets & guns) and Hai pulse weapons (turret & gun) do not work correctly, the pulse projectiles appear "golden" and the sunbeam lasers flicker on screen.

**To Reproduce**
Loading a ship with sunbeam and pulse weapons and firing (small and large ships) will reproduce this on Windows 10.

**Expected behaviour**
Normally (using version 0.9.9 did this) it would be expected that both the Sunbeams and the Pulse weapons would produce normal firing effects.

**System**
 - OS: Windows 10 Home
 - Game Source: GitHub releases 0.9.11 & 0.9.12

**Additional context**
Note: I am using a `home brewed` ship
 that has quite a few turrets, the full fleet has hundreds of weapon outfits installed.

[neb w.txt](https://github.com/endless-sky/endless-sky/files/4622359/neb.w.txt)

**Comment by Amazinite** [comment]
Do you have a video of this happening? Nothing seems out of the ordinary for me. Only two of the ships in the provided save file even mix pulse and sunbeam weaponry (two Kestrels), and they appear fine.

**Comment by Ben-Wise** [comment]
I re-outfitted my ships once I found this bug, I will re-outfit them with the mentioned weapons and get some shots of it happening - I am also using some mods (attached) if that could change anything here.
[mods.zip](https://github.com/endless-sky/endless-sky/files/4622883/mods.zip)

**Comment by Ben-Wise** [comment]
I've got the video of it happening, it's on google drive and I've got the link below.

https://drive.google.com/open?id=1-XDf3HbV45YRwHmaazFL2ou9lPJ2xei4

This may help.

**Comment by Anarchist2** [comment]
Could you try updating your game to the latest version? The version in your video looks particularly old.

**Comment by Ben-Wise** [comment]
I'm using version 0.9.12 (Latest stable release) of the game. However, it worked fine in version 0.9.9 (an unstable release), so I doubt that using the continuous build will help too much here. A theory of mine is that perhaps, with the new builds, it is starting to strain the graphics drivers / hardware (on my computer the game does occasionally freeze) therefore the graphic rendering is incomplete when it is required by the CPU - HOWEVER - I'm not an expert in C languages so I can't really say I'm afraid.

**Comment by tehhowch** [comment]
It's possible you are running low on GPU memory. Please include information about your system's hardware capabilities.

Also, you may benefit from enabling the preference to reduce large graphics.

**Comment by Amazinite** [comment]
We just had a new release. Are you able to replicate this issue in v0.9.13?

**Comment by Ben-Wise** [comment]
Opps... Sorry I kinda forgot about this @Amazinite ... First thing is that as mentioned above by @tehhowch :

> It's possible you are running low on GPU memory. Please include information about your system's hardware capabilities.

Seems to hold true, the old laptop with the problem is gone now and my current computer worked with it fine (even with version 0.9.12). From this I deduce that it's probably system resource constraints rather than coding issues.

Second: I never was able to test version 0.9.13 on the old laptop so I can't say but I suspect that if it is a computer issue there isn't much anyone can do about it.

Lastly: Thanks for making such a great game! I hope you all keep at it and enjoy making it!

**Comment by Amazinite** [comment]
Thanks for the update.
