### ISSUE TITLE
Escort cargo assignment not saved correctly

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#5065]
**Describe the bug**
When an escort is carrying mission cargo, this will not be recorded in the save file and may result in missions becoming impossible to continue after exiting.

**To Reproduce**
1. With at least one escort, take a mission which requires more cargo than the flagship can carry.
2. Go to another planet, and land there before the escort has caught up.
3. Exit and load the save file
4. Attempt to take off — this will only be possible if the mission is abandoned.

**Expected behavior**
The mission cargo was saved as being on the escort ship, so the mission can be continued even after loading the save file.

**System (please complete the following information):**
 - OS: Linux (NixOS)
 - Game Source: Nixpkgs
 - Version: 0.9.12

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by Amazinite** [comment]
#5039 #4969 #4600 #3644 #1980 #1945 #1624

**Comment by NomadicVolcano** [comment]
Please try #5070 and see if it fixes your problem.
