### ISSUE TITLE
Typo in Relic's description

### ISSUE THREAD

**Issue by roadrunner56** [endless-sky/endless-sky#5069]
**Bug**
In the Relic description, 'earth' is not capitalized, 'where' should be 'were', 'opinion' should be 'option', and 'it's' should be 'its'.

**To Reproduce**
1. Land on the planet Relic
2. Read planet description (not the spaceport description, just the main one)
3. See typos

**System**
 - OS: Manjaro Linux 20.0
 - Game Source: Steam
 - Version: 0.9.12

**Additional Context**
This is my first time filing a bug, so if I have done something incorrectly, please let me know.

**Comment by Amazinite** [comment]
Already been fixed the other week by #5043.

> This is my first time filing a bug, so if I have done something incorrectly, please let me know.

It's best to check the game files here on the repository to see if what you've found hasn't already been fixed. :)
https://github.com/endless-sky/endless-sky/blob/449b7fccd86120686b328ce4514eb2c46b609cbe/data/map.txt#L27529-L27534

**Comment by Zitchas** [comment]
Thanks for reporting it, though. We appreciate people taking the time to report things like this.

**Comment by roadrunner56** [comment]
Oops, sorry about that. I'll close the issue then.
