### ISSUE TITLE
"Buy All" or "Pay Off" Buttons for Trade and Bank

### ISSUE THREAD

**Issue by arrbug** [endless-sky/endless-sky#507]
It would be very helpful to have a way to fill up your cargo hold with commodities besides just clicking multiple times, as clicking 200 times for large cargo holds is very cumbersome.  Some sort of "Buy All" button would work, or else a popup for bulk purchasing, kind of like there is in the bank "pay extra" option.  As for the bank it might be nice to have a "pay off" button so that you can pay the amount owed all at once.

**Comment by natangold** [comment]
Are you using the most recent version? Current version has buy all.

**Comment by arrbug** [comment]
I am using 0.8.9 ... is there a newer version than that?

**Comment by DingusShingleton** [comment]
Hold shift to buy 5, 
hold control to buy 20, 
hold shift+control to buy 100, 
hold alt to buy 500, 
hold shift+alt to buy 2,500, 
hold control+alt to buy 10,000, 
hold shift+control+alt to buy 50,000.

Does that help?

**Comment by sanjayatio** [comment]
Change to fullscreen; those buttons you requested are cropped out in windowed mode.

**Comment by arrbug** [comment]
Yes, full screen mode works.  Thank you!
