### ISSUE TITLE
Fails to compile due to breaking changes in gcc 10

### ISSUE THREAD

**Issue by grawlinson** [endless-sky/endless-sky#5075]
**Describe the bug**

Due to [header dependency changes](https://gcc.gnu.org/gcc-10/porting_to.html) in gcc 10+, endless-sky fails to compile.

**To Reproduce**

1. Upgrade gcc version to 10+
2. Compile with `scons`
3. Watch it fail with the following error:

```
source/Panel.h:97:25: error: 'string' in namespace 'std' does not name a type
97 |  bool DoHelp(const std::string &name) const;
   |                         ^~~~~~
source/Panel.h:22:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
21 | #include <SDL2/SDL.h>
+++ |+#include <string>
22 |
```

**System (please complete the following information):**
 - OS: Arch Linux
 - Game Source: self-compiled via [Arch User Repository](https://aur.archlinux.org/packages/endless-sky/).
 - Version: 0.9.12, compiled with gcc 10.1.0-1

**Additional context**

This is fixed via addition of the missing header, as shown in the error message above.

**Comment by tehhowch** [comment]
Thanks for the report!
