### ISSUE TITLE
Endless-Sky Raspberry Pi 4

### ISSUE THREAD

**Issue by Jeeppler** [endless-sky/endless-sky#5076]
I played Endless-Sky on a Raspberry Pi 4 with 4 GB RAM. As OS I used Raspbian (Debian 10). I installed Endless-Sky via package manager. Endless-Sky did not work, because of the lack of OpenGL 3.0. I only had OpenGL 2.1.

**Comment by Jeeppler** [comment]
There seems to be some work in progress to support OpenGL 3.1 on the Raspberry Pi 4 in the future: https://www.cnx-software.com/2020/02/03/raspberry-pi-4-opengl-es-3-1-conformant-vulkan-drivers/

**Comment by Amazinite** [comment]
So how is this an issue with Endless Sky...?

**Comment by Jeeppler** [comment]
@Amazinite It is not really an issue with Endless Sky, but I did not know where else to track it.

**Comment by Amazinite** [comment]
Well "X system does not support Endless Sky due to not meeting the requirements" doesn't seem like an appropriate issue to post here.

**Comment by Jeeppler** [comment]
@Amazinite saying no instead of telling me where a more appropriate place to put an issue like that would be appreciated.

Since, OpenGL 3 is worked on I would keep this issue open until the support is there. The Raspberry Pi 4 hardware seems to support it, but the driver does not.

**Comment by Amazinite** [comment]
Well the most appropriate place to report this would be wherever issues about Raspberry Pis are posted, but I don't know where that is.

> Since, OpenGL 3 is worked on I would keep this issue open

Again, this deals with some system not meeting the requirements for the game, so it's not an issue for us to track.

**Comment by Jeeppler** [comment]
> Well "X system does not support Endless Sky due to not meeting the requirements"

Raspberry Pi is not exactly any system. It is a very popular single board computer with an ARM architecture. I am probably not the only one trying to run Endless-Sky on a Raspberry Pi 4.

**Comment by Jeeppler** [comment]
> Well the most appropriate place to report this would be wherever issues about Raspberry Pis are posted

This is your perspective, totally ignoring the fact that it affects Endless Sky, Raspbian and Raspberry Pis. Basically, in my perspective the most appropriate place would be to post it in an Endless Sky forum. However, Endless Sky does not have a forum or does it?

**Comment by Amazinite** [comment]
>This is your perspective, totally ignoring the fact that it affects Endless Sky

The whole point of the issues page for Endless Sky is to report issues *with Endless Sky.* It is not an issue *with Endless Sky* that Raspberry Pis do not meet the system requirements of the game. That's an issue with the Raspberry Pis.

**Comment by tehhowch** [comment]
The better place to discuss and track this would be on [Steam](https://steamcommunity.com/app/404410/discussions/0/) or [Google Groups](https://groups.google.com/forum/m/#!forum/endless-sky). GitHub issues should be largely used for focused and actionable tasks, such as feature requests and bug reports. 

Also please note that OpenGL ES is not a superset of OpenGL, it is a subset and as such this game may currently or one day use functionality not available in OpenGL ES.

**Comment by SwiftSki** [comment]
is there an older version of endless sky that works with OpenGL 2.1?

**Comment by MCOfficer** [comment]
> 
> 
> is there an older version of endless sky that works with OpenGL 2.1?

No official ones, but there's #1559. Be aware that you're very much on your own with this.

**Comment by Adriankhl** [comment]
From `glxinfo | grep Mesa`:
```
client glx vendor string: Mesa Project and SGI
OpenGL version string: 2.1 Mesa 19.3.2
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.3.2
```

Raspberry pi 4 supports GLES3. This PR (https://github.com/endless-sky/endless-sky/pull/5588) may make this playable on raspberry pi 4, so this can be a valid issue :)
