### ISSUE TITLE
Crew isn't removed when I sell crew bunks

### ISSUE THREAD

**Issue by bobafetthotmail** [endless-sky/endless-sky#508]
As title.
I managed to get -70 or so passenger space (yes, negative space, 70 guys that are kept god-knows-where) by buying a bunch of crew bunks (and cargo --> outfits converter system), hiring crew then selling the bunks.

Can fire the additional crew without issues, cannot hire them again.

**Comment by ItsNickBarry** [comment]
They should be automatically fired when you take off.

**Comment by endless-sky** [comment]
This is necessary in order to let the player reconfigure their ship or their fleet without failing missions just because they temporarily have too little space for the crew or passengers.
