### ISSUE TITLE
Add Nintendo Switch Build

### ISSUE THREAD

**Issue by bfenty** [endless-sky/endless-sky#5092]
Title says it all-I believe that this could be compiled fairly readily for the Nintendo Switch, and would really enjoy playing this game on the platform. It would only run as homebrew, of course, but there is a community that would enjoy this game on the system.

Thank you for considering.

**Comment by Amazinite** [comment]
That's gonna be a no from me. It can be enough of a headache already to make sure everything works on Linux, Windows, and Mac. If anyone wants to port the game to other platforms somehow then they can take a crack at it, but that's not something we're going to deal with here.

Related: #1502

**Comment by MCOfficer** [comment]
You mentioned

>  It would only run as homebrew

I'm not familiar with switch, but i'd assume this means there are "rooted" (or equivalent) machines that use homebrew as package manager. Homebrew can build formulae from source, so assuming there are formulae of all dependencies for the switch, you can at least write one that builds ES.

However, that still leaves open the topic of keybindings. You can probably patch ES to get a rough approximation of mobile controls (see [keys.txt](https://github.com/endless-sky/endless-sky/blob/master/keys.txt) - all you'd need are the SDL2 keycodes for the switch controls), but it will inevitably remain lackluster and probably unsatisfying to play.

I'm opposed to doing any sort of compatibility patch in this repo, for the same reasons #1502 was rejected.

**Comment by MCOfficer** [comment]
Can this be closed?

**Comment by bfenty** [comment]
Thanks for the replies, sorry I've been out of it for a while and missed them. Makes sense, but hey, have not because you ask not.

**Comment by huhwhythis** [comment]
> If anyone wants to port the game to other platforms somehow then they can take a crack at it

It sounds like a fun and productive way for me to get into c++, would y'all mind if I try? emphasis on 'try' though, I still am trying to figure out GitHub

**Comment by MCOfficer** [comment]
So you have chosen... death.

Seriously, this doesn't sound like a good way to start c++, but nobody's stopping you. But mind you, this project does not want to maintain a switch port. Any such port will have to stay unofficial.

**Comment by tehhowch** [comment]
In other words, your registration should be just that: your personal registration, with no suggestion of affiliation.

**Comment by huhwhythis** [comment]
OK, into the mouth of the beast then.

> In other words, your registration should be just that: your personal registration, with no suggestion of affiliation.

would this mean I couldn't go about putting on the eshop?

**Comment by MCOfficer** [comment]
You're asking the wrong people, you really are :D
