### ISSUE TITLE
Typo in transport missions.txt chit -> chip

### ISSUE THREAD

**Issue by craigmccauley** [endless-sky/endless-sky#5105]
**Describe the bug**
Simple typo "chit" should be chip
https://github.com/endless-sky/endless-sky/blob/82f382349370122652b84fffb9359ed41464de57/data/human/transport%20missions.txt#L1702

**To Reproduce**
Do illegal transport missions until you get to the gang transport mission. When they hijack the ship, bargain with them twice. Final text shows chit.

**Expected behavior**
Text should be "credit chip".

**Screenshots**
![image](https://user-images.githubusercontent.com/7706831/82839559-af014d00-9ec7-11ea-9187-f9031040691e.png)

**System (please complete the following information):**
 - OS: Windows 10 Home
 - Game Source: Steam Beta
 - Version: 0.9.12

**Comment by tehhowch** [comment]
Not a typo: https://dictionary.cambridge.org/us/dictionary/english/chit

It could be changed, but it isn't a bug or typo.

**Comment by craigmccauley** [comment]
You (I) learn something new everyday. 
Even if it isn't a typo, I think at least for consistency it should be credit chip as that is how all the other currency transactions in the game work.
https://github.com/endless-sky/endless-sky/search?q=credit+chip&type=Code

**Comment by Zitchas** [comment]
I think I prefer having the "chit." Some variety in the game is a good thing.

**Comment by Amazinite** [comment]
Given that this is narration, I'd say we keep things consistent and just always use "chip." No problem with having a character say "chit," though.

**Comment by Thunderforge** [comment]
> Not a typo: https://dictionary.cambridge.org/us/dictionary/english/chit

According to the entry, the word is "UK old-fashioned". Given that even in our world it's an archaic word that may be unfamiliar to English speakers outside the UK and Commonwealth territories, I find it very unlikely that it would be used in a future when "Earth" is a single, homogenous entity.

Besides, we want Endless Sky to be accessible to English speakers around the world, so I say remove this regional, obsolete word that is only one letter different than our standard term for the item.
