### ISSUE TITLE
Autopilot comquter outfit

### ISSUE THREAD

**Issue by geojak** [endless-sky/endless-sky#5109]
It always bothered me how this games requires zero manually navigation to jump or land. This was actually fun in ev nova,.. For some time until it becomes a repetitive task.

It order to get the best of both worlds, why not introduce a Autopilot bord comquter outfit to enable these. Cost 250.000 and 0 outfit space.

Without this the thruster are not used when pushing j or l and the player needs to manuka put the ship to an halt in order to jump and land. Steering thruster still auto when jumping even without the comquter.

**Comment by Zitchas** [comment]
By "pushing j or l" do you mean boarding and landing?

I somewhat agree to this sentiment. Flying (especially landing and boarding) feel far too automated. In truth, I never really got tired of it in EVN, although now and then (especially when doing bulk commodity runs) I did wish it could be automated.

I note that EVN did the same thing for refueling. Normally you'd have to click "refuel" at every stop, and one could buy an auto-refueller for a couple thousand credits (no space). It was a nice quality of  life thing. Having to pay attention to refueling was a great early-stage thing to learn, and it was equally nice to be able to just automate and forget once I had the wealth to do so.

I'd probably raise the price up a bit to around 5k or so.

**Comment by geojak** [comment]
Already forgot a out the scanner, but fully aggee. These all small things that add to the fun of achieving something.

**Comment by Amazinite** [comment]
While this game takes inspiration from Escape Velocity, it's still not Escape Velocity. I don't see us removing mechanics and readding them as outfits any time soon. This type of idea might tie into the idea of difficulty settings, though; perhaps on higher difficulties, not as much stuff gets automated at first, and you need to upgrade to automate them. (#1386)
