### ISSUE TITLE
Offer version number that can be queried by plug-ins

### ISSUE THREAD

**Issue by pega3** [endless-sky/endless-sky#5117]
**Is your feature request related to a problem? Please describe.**
The game is constantly changing and evolving. Plug-in authors with an interest to keep their plugin compatible to various releases may face the problem that they have to offer adjusted content according to the game version. However, there is currently no way (that I know of) how a plugin can query the version of the game. 

**Describe the solution you'd like**
Offer something (e.g. a condition) that a plugin can query to determine the version of the game which is being run.

**Comment by Zitchas** [comment]
This might also tie in with the idea that has been floating around about having currently in-use plug-ins having their name saved to the pilot file. It'd certainly help a lot with troubleshooting.

That being said, I'm curious as to how the plug-ins will be able to adjust content. Aside from in-conversation branches, there's really not a lot of places that plug-ins can change themselves based on an attribute.

Although that being said, now that I think about it, it might be possible to use invisible missions and events to swap data around based on an attribute...

**Comment by gunqqer** [comment]
well, lua scripting or other scripting for plugins has been spoken about, so if that is implemented it would make this more useful (although by how much, I do not know)

**Comment by Amazinite** [comment]
Given the fact that we keep backwards compatibility in nearly all cases, what use would this be outside of allowing someone to use a plugin in an older version of the game by say preventing missions from offering if they use newer features?

The only compatibility that I’ve seek broken over the years is from plugins that changed the interfaces.txt file, which given its more inflexible syntax isn’t really designed to be changed right now anyways.
