### ISSUE TITLE
Uninhabited words do not execute mission/job code?

### ISSUE THREAD

**Issue by silvan78** [endless-sky/endless-sky#5118]
**Describe the bug**
System Korsmanath, government Uninhabited, no switches such as no_jobs; planet Kasichara Fet.
A test mission:
```
mission "Uninhabited Test Job: Kasichara Fet"
	name "Run Test Job Here"
	job
	repeat
	description "Run test job on planet in Uninhabited system"
	source
		planet "Kasichara Fet"
	on offer
		dialog "Job offered"
	on accept
		dialog "Job accepted."
		fail
```
Job list is empty !

**To Reproduce**
Run test mission.

**Expected behavior**
If mission source, to offer trigger etc. check up, the mission should appear in jobs list.

**System (please complete the following information):**
 - OS: win 10
 - Game Source: steam
 - Version: 9.12

**Link to save file**
https://hastebin.com/akizidoyoj.cpp

**Additional context**
[none]

**Comment by Amazinite** [comment]
Uninhabited planets do not have a trading, bank, hiring crew, or jobs board panel. 

> no switches such as no_jobs

No such switch exists.

**Comment by silvan78** [comment]
There is a trick to bring trade/job/bank/crew boards. Tribute-domination mod adds tribute to all defined planets, and that is enough to have required boards. Yet the mission code is still not running.
```
planet "Kasichara Fet"
	tribute 2
		threshold 1000
		fleet "Rand Defense Fleet" 1
```

**Comment by Amazinite** [comment]
Looks like the game explicitly skips looking for available jobs on planets without a spaceport.
https://github.com/endless-sky/endless-sky/blob/6911eb38fff9f03bc2f3438426c58339895be5d9/source/PlayerInfo.cpp#L2388-L2390

**Comment by silvan78** [comment]
I would prefer to have job option:
If there's no job for this planet, show no job board at all. Omit the "skipJobs" flag and show panel on different condition, something like:
```
 else if(key == 'j' && hasAccess && flagship && planet.hasJobs()) 
 { 
 	GetUI()->Push(new MissionPanel(player)); 
 	return true; 
 } 
```
The Spaceport & Inhabited status are irrelevant for quests unless we consider job board a place for missions commissioned by planet inhabitants. If so then there is no proper placeholder for optional quests not related to spaceport/habitation? As the source code shows, no mission will be generated, at job board, upon landing or any other way. Current state limits mission writing for uninhabited worlds (as no mission would run there), unless we patch all uninhabited planets with some generic spaceport entry.
```
planet "<planet name>"
    spaceport `Your "spaceport" here is just a piece of flat land cleaned by your engine exhaust gases.`
```
The question is if the planet entry is patching with spaceport this way, or the whole planet specification is superseded by new one (one cannot "add spaceport"). In the second case the viable option is user global map.txt patch. It is also bit more elegant solution to tribute-domination, where you actually add fleets! in uninhabited world.

**Comment by Amazinite** [comment]
032c090 
Seeing as how Planet::IsInhabited was added after the skipJobs calculation, I've replaced the HasSpaceport with IsInhabited so that jobs can offer on worlds that are inhabited but don't have a spaceport.

**Comment by tehhowch** [comment]
I don't think an inhabited planet without a spaceport should have an active job board. That planet can still offer landing-based missions, but with no spaceport, I don't see the logic in there being repeatable jobs that involve off-world travel.

**Comment by Zitchas** [comment]
Automated mining station, perhaps?

**Comment by Amazinite** [comment]
> I don't think an inhabited planet without a spaceport should have an active job board. That planet can still offer landing-based missions, but with no spaceport, I don't see the logic in there being repeatable jobs that involve off-world travel.

Well I didn't see the logic in having uninhabited planets be able to fine the player in any instance, but we still allowed for a security value to be given to uninhabited planets and have that result in a fine. :)
