### ISSUE TITLE
Ships can be parked in uninhabited systems

### ISSUE THREAD

**Issue by diggorygray** [endless-sky/endless-sky#5120]
**Describe the bug**
It's possible to 'park' a ship in any system, even those with no planets or stations.

**To Reproduce**
1. Go to an uninhabited system and halt your escort(s).
2. Jump to another system and land.
3. Select 'park all'
4. See that you have parked ships in an uninhabited system.
5. Fly back to the system and your escort(s) have disappeared - after all they are parked... somewhere.

**Expected behavior**
I'd expect a escorts to be unable to be parked in an uninhabited planet.

So either: 
1. They would simply show 'unable to park'.
or 
2. They'd fly to the closest friendly system (if any and park there) if possible.

**Screenshots**
![Screenshot at 2020-06-06 21-05-48](https://user-images.githubusercontent.com/11949270/83953817-8f5d1380-a83b-11ea-93d4-4e85120bfe39.png)

**System (please complete the following information):**
 - OS: [Linux Mint 19.3 (Tricia)]
 - Game Source: [self-compiled]
 - Version: [commit hash a29467d]

**Additional context**
It seems parked ships are assumed to be 'planet side' on on a station (as you don't see they in system if you fly back to the system where they are parked). However there are no checks on if the system has anywhere you can park.

Also if the system has a dockable but uninhabited station/planet, should this allow you to park a ship there?

**Comment by Amazinite** [comment]
Duplicate of #199.

**Comment by diggorygray** [comment]
Hmmm, I see the comment #199.
Maybe make the ship just hang around in the system? shrug.
It's a bit wired when you go back to the system and doesn't make a lot of sense.

Could this be re-visited, as there are quite a few uninhabited systems.
This could be solved by simply maked the ships halt in that system and not switch to parked status.
Not ideal, but better than vanishing.

**Comment by pepoluan** [comment]
If you land on a planet and "unpark" those vanishing ships, will they reappear and hopscotch to your location?

**Comment by diggorygray** [comment]
Yes they act as though parked normally.

**Comment by petervdmeer** [comment]
Related to #4690

**Comment by Zatishko** [comment]
I put this under that's not a bug, it's a feature.

I use it all the time for newly captured ships, or stuck ships, I've run out of patience on for regenerating fuel. Park them until I have time to go back and refuel them. Meanwhile, they're not pulling down crew costs until I unpark them again. 

If there is a problem, they're immune while parked, which isn't a problem as long as player doesn't enter the system. Works either way for me.

**Comment by tatami4** [comment]
If this was removed it would create a problem (at least I think it would):
1. Park some escorts in any system.
2. Go to some system that is not accessible to parked escorts (e.g. due to escorts having no jump drive).
3. Unpark the parked escorts.
4. Escorts try to fly to the flagship.
5. They cannot do it for some reason (step 2).
6. If they are in an uninhabited system, you will not be able to park them again until you somehow make them go to an inhabited system (this might be possible with #2678, but it would be inconvenient).

**Comment by diggorygray** [comment]
@tatami4 Well yes, but you can easily create the same effect by simply having a jump drive on your flagship and jumping to a place escorts with hyperdrives can't follow. They are happy to wait until you return.

**Comment by tatami4** [comment]
> can easily create the same effect by simply having a jump drive on your flagship and jumping to a place escorts with hyperdrives can't follow. They are happy to wait until you return.

Yes, but in that case you are deliberately doing so (and you can still park them). If ships could not be parked in uninhabited systems, you would have to got to them and guide them to an inhabited system, which would be very inconvenient.

**Comment by diggorygray** [comment]
Ok, I guess this opens too big a can of worms.

I had thought that the ships could land in a system that is inhabited, however this falls foul of complexities such as are they friendly, can they jump there, etc...

Possibly the issue could be, park if you could land your flagship in that system.
However in hindsight I can see that this would severely reduce the playability of the game.
So I'll close this...
