### ISSUE TITLE
Content suggestion: amend faction descriptions in log according to story progress

### ISSUE THREAD

**Issue by pega3** [endless-sky/endless-sky#5124]
** The issue **
As was pointed out by Warlord Mike on Discord, currently the faction descriptions in the player's log are more or less static. E.g., even after the FW campaign is over, the text on the FW is still the same as at the beginning of the campaign, suspecting their involvement in the nuclear attack, which at that time the player has clearly disproven.

**Describe the solution you'd like**
For each faction a review should be performed on the text which is added to the player's log and if that text is still fitting throughout the various storylines. If not, amendments to that faction's description should be added to appropriate points in the game. 

Two descriptions come immediately to my mind: 
- Free Worlds (description should be updated latest after the main plot is over)
- Wanderers (description should be updated once the eye has opened and the migration to the new sector commences)

Another debatable update could be done to the Syndicate description, again after the finish of the FW campaign.

**Comment by Amazinite** [comment]
Would you consider this done after your PR #5132?

**Comment by pega3** [comment]
Sorry, I forgot to close the issue. Of course, we should keep an eye on this in the future.
