### ISSUE TITLE
Green broken screen on launch

### ISSUE THREAD

**Issue by Khel** [endless-sky/endless-sky#5130]
**Describe the bug**
Im using a MSI Raider GE63VR and whenever I start the game the screen is totally broken with interlapping black and green bars. You can see in the background the starting interface but it is totally impossible to play.

**To Reproduce**
1. Start the game

**Expected behavior**
Game plays as usual

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/1132958/85231749-17c1e380-b3fa-11ea-9522-258067f2f102.PNG)

**System (please complete the following information):**
 - OS: Windows 10 Home, version 1909
 - Game Source: Tried in Steam and also with the Github download.
 - Version: latest stable version 0.9.12

Has anyone had this problem before? I used to run the game in an Acer laptop without any hassle.

Kind Regards.

**Comment by MCOfficer** [comment]
I've never heard of this problem before, but this sounds a lot like a graphics driver issue. Make sure the driver is uptodate, and try both the version from the manufacturer and from nvidia.

**Comment by Khel** [comment]
Hello,
I tried uninstalling and reinstalling both Intel HD Graphics 630 and Nvidia GeForce GTX 1070 drivers and still have the weird green screen.

Any other options?

**Comment by MCOfficer** [comment]
Oh, i didn't consider the graphics chip. Maybe ES is using the intel graphics instead of your GPU. Can you check that, and if it does, try to force ES to use the GPU?

See https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

**Comment by Khel** [comment]
Hello,
That finally worked :)
Many thanks @MCOfficer 
Regards.

**Comment by tehhowch** [comment]
Seems to still affect some users that don't have multiple gfx cards: https://discord.com/channels/251118043411775489/536900466655887360/728987850015768618

**Comment by MCOfficer** [comment]
Another report: https://www.reddit.com/r/endlesssky/comments/hsu1h1/i_would_like_some_help_to_fix_my_endless_sky/

**Comment by pega3** [comment]
Interestingly, above user was able to run it in a virtualbox linux vm successfully. Windows driver hell?

**Comment by Amazinite** [comment]
We have a report on Steam for someone who has found a fix for this.
https://steamcommunity.com/app/404410/discussions/1/4078523564606698020/?tscn=1595305772

> So it's an Intel UHD graphics issue. After looking at Intel's support site they have a beta driver that will correct it. I downloaded and.....IT WORKS!!!! Check out the forum that has the link to the driver:
https://community.intel.com/t5/Graphics/Intel-HD-630-green-lines-in-OpenGL-apps/td-p/1192516

**Comment by tehhowch** [comment]
Marking wontfix since this is a driver-specific issue.
