### ISSUE TITLE
Possible soft-lock when leaving planet.

### ISSUE THREAD

**Issue by pgooch** [endless-sky/endless-sky#5133]
**Describe the bug**
If you have a ship without steering engines you cannot take off without purchasing some at the outfitter, if this happens on a planet without an outfitter you are unable to leave the planet.

**To Reproduce**
1. Get a ship without steering engines, I'm not sure where mine cam from but I think it might be an escort as I haven't "liberated" any pirate ships recently.
2. Go to a landing location without an outfitter, it happened to me on Charon in the Aldhibain system.
3. Try to leave the planet.
4. Get the message about not having steering engines.

**Expected behavior**
I'm not sure, either it should not care if it's an escort or it should force me to but some, even bad ones, so I can actually leave the planet.

**System (please complete the following information):**
 - OS: OSX 10.15.4
 - Game Source: Github Compiled
 - Version: 0.9.12

**Link to save file**
[Firsty McLastname.txt](https://github.com/endless-sky/endless-sky/files/4822519/Firsty.McLastname.txt)

**Comment by MCOfficer** [comment]
This is generally prevented by no ship ever existing without steering, unless the ship is on a planet with outfitter. I don't think the AI would be able to fly a ship without steering to begin with.

Which begs the question, where the hell did you get this drone from? it has the regular X1700 thrusters, but the X1200 steering is missing.
```
ship "Surveillance Drone"
	name "Beta Eight"
	sprite "ship/surveillance drone"
	thumbnail "thumbnail/surveillance drone"
	attributes
		category Drone
		cost 50000
		mass 15
		automaton 1
		drag 0.53
		"engine capacity" 28
		"heat dissipation" 0.9
		hull 300
		"outfit space" 53
	outfits
		"X1700 Ion Thruster"
		"nGVF-AA Fuel Cell"
	crew 0
	fuel 0
	shields 0
	hull 300
	position 7058.6244 -8832.8694
	engine -5 29 1
	engine 5 29 1
	explode "tiny explosion" 15
	system Aldhibain
	planet "Charon Station"
```

**Comment by pgooch** [comment]
> where the hell did you get this drone from?

That is the surveillance drone from the Free Worlds mission. After taking the scanner components I figured what the hell and took the drone as well. Without a hyperspace drive it can't actually follow the rest of my fleet, so it just sits in the system I stole it in. I just left it there thinking it was no big deal, I was thinking maybe I could find an upgrade like a fighter bay or drone whatever to take it aboard at a later point.

I went ahead and added the "X1200 Ion Steering" into it's outfits and it lets me take off again, with a warning about having a ship that can't leave the system.  It would seem my drone lost it somewhere as I checked the ships definition. It seems to be correct in the [ships data file](https://github.com/endless-sky/endless-sky/blob/master/data/human/ships.txt).

**Comment by MCOfficer** [comment]
Did you at some point install plug-ins that perhaps redefined the X1200? Or launched the game from an experimental branch?

**Comment by pgooch** [comment]
No, all stock. I found the steering motor, in the cargo hold of another ship. I'm not sure how it got there, but maybe before I captured it they pirated it off, or maybe I took it off the drone.

**Comment by pega3** [comment]
Maybe it is treated differently because it is a drone and not a full ship? 
However, even when I bring in a carrier for drones to the system, I cannot take off. 
Obviously, there are two easy workarounds available (park or disown) so that the game can continue, but in theory, that drone should have never landed, but stayed disfunction drifting in space...
Of course, having the ability to install outfits which are in cargo would help here, but that's a CR which has already been submitted. :-)

**Comment by Amazinite** [comment]
My best guess is that you may have simply accidentally removed the steering when looting the surveillance pod, but as mentioned, you have the option to park or disown any ships which you can't fix.
