### ISSUE TITLE
Mapping is messed up.

### ISSUE THREAD

**Issue by pogopossum3** [endless-sky/endless-sky#5139]
Jump count is usually wrong,
Planets with assignments do not always show up on small chart of jumps.

**Comment by tehhowch** [comment]
Please use the report template.

**Comment by pogopossum3** [comment]
Where does one find the report template?

**Comment by tehhowch** [comment]
It should have appeared when you went to create a new issue here on GitHub -- there are two templates, one for a Bug Report and one for a Feature Request. Choosing either option results in the respective template filling the issue text entry form.

**Comment by pogopossum3** [comment]
Here is the screen shot part of the map problem as well as showing the "tail" that occasionally gets left.

________________________________

**Comment by MCOfficer** [comment]
It seems that github swallowed your screenshot.

The issue templates can be found [here](https://raw.githubusercontent.com/endless-sky/endless-sky/master/.github/ISSUE_TEMPLATE/bug_report.md) for bug reports, and [here](https://raw.githubusercontent.com/endless-sky/endless-sky/master/.github/ISSUE_TEMPLATE/feature_request.md) for feature requests.

**Comment by pogopossum3** [comment]
This shows two ptoblems. The inaccurate jump count and the "tail"  on wher you have been and where yiu are going.

________________________________

**Comment by MCOfficer** [comment]
There is no screenshot. Apparently github does not preserve attachments sent via E-Mail. Please send the screenshot again, and provide the information [in the template](https://raw.githubusercontent.com/endless-sky/endless-sky/master/.github/ISSUE_TEMPLATE/bug_report.md).
