### ISSUE TITLE
Where does one find the report template?

### ISSUE THREAD

**Issue by pogopossum3** [endless-sky/endless-sky#5140]
**Is your feature request related to a problem? Please describe.**

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. If you're proposing new UI features, creating a mock-up can really go a long way in conveying your intent.

**Comment by MCOfficer** [comment]
Your post *is* the issue template. It's what comes up when you click the `New issue` button. You just failed to fill it out.
