### ISSUE TITLE
Deep Scientist Rescue 0 Fix

### ISSUE THREAD

**Issue by Ironarcher13** [endless-sky/endless-sky#5144]
**Describe the bug**
Not entering Betelgeuse before/after visiting Arneb causes the "on visit" dialog upon returning to Valhalla. Because of how Jump Drive courses are plotted, it is quite possible to miss this step if you guess that they are somewhere in the pirate colonies.

**To Reproduce**
1.  Leave Valhalla after getting Rescue Scientists 0.
2, Go to the Arneb system while bypassing Betelgeuse.
3. Return to Valhalla.

**Expected behavior**
My expectation was that I'd have found the Star Queen due to the dialog while in Arneb.

**System (please complete the following information):**
 - Game Source: Steam
 - Version: 0.9.12

**Additional context**
This is just a confusingly written part of the mission. It forces an expectation that you will fly through Betelgeuse without giving any actual direction to do so.

Edit: This is no longer a bug issue, rather a potential enhancement. This was a mistake of confusion on my part and doesn't pose an issue with completing the mission, only an annoyance and frustration on the rare occasion someone does this mission for the first time with a jump drive and is unaware of how waypoints work exactly. Other details have been edited accordingly.

**Comment by Amazinite** [comment]
This mission requires that you both enter Arneb to find the Star Queen and fly through Betelgeuse to complete the waypoint objective. The waypoint exists to point the player in the right direction, so I'd rather not remove it. The only other viable solution I can think of without completely reworking the set up of these missions is to have "Deep: Scientist Rescue 1" offer if you have the "found star queen" condition, and fail the previous mission on offer. This runs into #1938, but that's not any real issue in this case.
