### ISSUE TITLE
System ping for missions to mark systems of importance without requiring a waypoint

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5145]
**Is your feature request related to a problem? Please describe.**
A `waypoint` can be used to mark a system of importance for a mission, but using it for this purpose runs into issues.
1) Visiting the waypoint(s) then becomes a necessary objective for the completion of the mission. (See: #5144)
2) Visiting the waypoint(s) removes the tick on the map, which can be an issue if knowing which system was waypointed is important. (See: the Kor Sestor Remnant mission, where the player may accidentally leave stragglers in a system but then forget which systems had Kor Sestor.)

**Related Issue Links**
#4327

**Describe the solution you'd like**
Add a new `ping <system>` keyword for missions that places a marker on the named system. This marker does not disappear if the system is entered and visiting this system is not a necessary objective for completion of the mission. Should we desire, visiting a pinged system may cause the marker to become duller to denote that the system has been visited, but a marker should still remain.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tehhowch** [comment]
If you select an active mission, any visited waypoints or stopovers are already displayed as faint rings (#3567) so there is just a discoverability issue for that scenario.

As far as a way to demarcate optional "hint" system(s), that shouldn't be too difficult to implement. I would avoid any proposal that involves animation / blink since we use that to convey urgency.

**Comment by Eloraam** [comment]
Sounds pretty straightforward.  I've been digging into the mission code for other reasons.  Is there consensus on this one?

**Comment by Amazinite** [comment]
Perhaps mission actions should be able to unping systems. Using the mission structure from #5367 as an example:
```
mission "Visit Sag A*"
	ping "Sag A*" # Sag A* is marked on the map.
	...
	on enter "Sag A*"
		require "Research Laboratory"
		unping "Sag A*" # Unmark Sag A*, but only if this action triggered. That is, the player visited with a lab installed
		...
```

**Comment by thebigh2014** [comment]
Some of the markers can be difficult to differentiate.  I would suggest a slightly different color for a ping.
