### ISSUE TITLE
Trinket sells Nerve Gas, and buying them and landing back later at the same planet will get you fined

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#5147]
**Describe the bug**
Trinket is the only non-pirate planet whose outfitter sells Nerve Gas. You can buy them, but landing back to Trinket again with the Nerve Gas will get you fined. This doesn't make sense, a Republic (soon Free Worlds) planet sells illegal items, and landing back there with the same items they sell gets you a fine.

**To Reproduce**
1. Go to Trinket in the Sargas system
2. Buy a Nerve Gas in their outfitter
3. Depart and land back again.
4. You get fined 1 million credits. If you don't get fined, try again, since the security for Trinket is set to 0.4.

**Expected behavior**
I expected that the planet's authorities won't fine you at all.

**Screenshots**
![Screenshot from 2020-07-04 19-43-13](https://user-images.githubusercontent.com/32586497/86512095-8e66d400-be31-11ea-8d3c-ff2afbce85cf.png)

**System (please complete the following information):**
 - OS: Debian 10.4.0 "Buster" GNU/Linux
 - Game Source: GitHub AppImage
 - Version: 0.9.12

**Link to save file**
N/A

**Additional context**
Removing Nerve Gas from Trinket's outfitter is fine too. If security can't be set to 0 and removing nerve gas is not an option, then I could go with a 0.01 security. But I still prefer the first two options.

**Comment by Zitchas** [comment]
Two thoughts on this:

a) Plenty of illegal things in Real Life are sold in cities where they are illegal and possession thereof will get you fines. Virtually every city in the world, in fact, probably has at least some degree of black market.

b)I don't think it would make sense to eliminate the security rating. But reducing it somewhat might be appropriate. Perhaps down to 0.1 (not 0.01). Even if the authorities are corrupt enough that a black market vendor is *that* easy to find doesn't mean they are going to completely ignore a source of revenue. Just think of it as ongoing bribes to be left alone...

**Comment by Amazinite** [comment]
#388 #1466

**Comment by Pete-2004** [comment]
Plenty of illegal things in Real Life are sold in places where they are illegal, but why take risks and pay the ongoing bribes to the authorities on Trinket when dealing nerve gas is risk free and bribe free two jump away ? Fragmentation grenades would make better sense on Trinket.
Weirder are Albatross and Bloodsea still dealing nerve gas after giving up piracy and join the FW...

**Comment by Amazinite** [comment]
Given that the whole point of Trinket is that it sells outfits that would otherwise require the player entering a pirate system (the risk of Trinket being getting scanned and the risk of a pirate system being getting attacked and needing to bribe to land), I think we should leave the fine (and what Trinket sells) as is.
