### ISSUE TITLE
Tinker tribute after Pug

### ISSUE THREAD

**Issue by Pete-2004** [endless-sky/endless-sky#5149]
**Describe the bug**
After Pug war, Tinker tribute remains at 1. The line
`"tribute:` Tinker" *= `1100`
 is missing in event "pug territory liberated".

**Comment by Zitchas** [comment]
Thank you for reporting the omission. 

Just a pointer for future issues: Please remember to delete whatever stuff from the template that you aren't filling out to avoid confusion. (or ideally, fill it out).

**Comment by Pete-2004** [comment]
OK. I edited my post.

**Comment by tehhowch** [comment]
Note that if you delete most of it, you will be asked to fill it out. Especially relevant are things like the game version you are playing, where you obtained it, and so on.

Closing as fixed in 0.9.13; you will need to release and re-tribute the planet since you already received the event.
