### ISSUE TITLE
hai unfettered lightning bugs have negative outfit space

### ISSUE THREAD

**Issue by brick96** [endless-sky/endless-sky#515]
Unfettered lightning bugs that come with a tracker pod and 2 pulse turrets have -9 outfit space. I recommend switching the LP072a battery pack for LP036a battery pack

**Comment by thenerdfreak** [comment]
Well some things do have negative outfit space, like the Korath Raiders. It's probably because that's a relatively balanced outfit that the owner decided to put in, but not let the player make that outfit (idk why but other ships have negative outfits too in nature)

**Comment by brick96** [comment]
So did they find a way to bend space? If so why cant we XD

**Comment by thenerdfreak** [comment]
they're far more advanced

**Comment by endless-sky** [comment]
Fixed in 42fd2eb.

**Comment by thenerdfreak** [comment]
even the Korath?

**Comment by endless-sky** [comment]
Fixed the Korath and a few others in c10cd5d.

**Comment by thenerdfreak** [comment]
Yey

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
