### ISSUE TITLE
Preventing multiple missions from being offered at the same time

### ISSUE THREAD

**Issue by boegh** [endless-sky/endless-sky#5151]
I have created the following mission file, loaded as a plugin from `~/.local/share/endless-sky/plugins/vip/data/1p.txt`. When I arrive at a planet that meets the source requirements (i.e. Relic in Sirius system or Geyser in Denebola system) and go to the Spaceport I get first presented mission 1A (Anna) and then right after mission 1B (Barth) in one continuous sequence. This behavior is reproducible from the attached savefile if is loaded, then travel to Geyser, land and enter Spaceport. I am not sure if it is a bug, if it is something I have done wrong (I can't find any description of this on the [CreatingMissions page](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions)), or if it is a feature request (sorry for breaking template here).

In the savefile the following is added under conditions:
```
	"1P 1A: active"
	"1P 1A: offered"
	"1P 1B: active"
	"1P 1B: offered"
```

**System (please complete the following information):**
 - OS: Linux lappy 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Game Source: [PPA](https://launchpad.net/~mzahniser/+archive/ubuntu/endless-sky)
 - Version: 0.9.12 (no plugins added other than vip/data/1p.txt)

**Link to save file**
[1p.txt](https://raw.githubusercontent.com/boegh/random/master/endless-sky/1p.txt)
[Savefile](https://raw.githubusercontent.com/boegh/random/master/endless-sky/Henrik%20B.txt)

**Comment by Zitchas** [comment]
Neither mission has any requirements aside from the source planet, so yes, they would both trigger when that source is met. To avoid this, you can either add requirements (for instance, having a random chance added to it.

```
to offer
		random < 30
```

Alternatively, you could give one of them the ```minor``` tag, which would prevent that mission from being triggered at the same time as another mission. (As per the Creating Missions page instructions).

In either case, this is a problem with the way the missions are formatted, and not with the game itself. I would recommend that you close this issue (as bugs on here are just for bugs with either in-game content or the engine itself), and stop by the discord. We have a channel for content-creation where quite a few of us would be happy to help you work on getting these missions working the way you want. And answer questions, etc.
