### ISSUE TITLE
New NPC specification: toggle NPC activation based on conditions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5159]
**Is your feature request related to a problem? Please describe.**
The heart of the issue of #1564 is that causing things to occur based off of conversation choices can be difficult right now, as often times you need to delay the effect to the next landing. (See #4786 or #5007 where missions are forced to delay payment because the player's conversation choices can not immediately affect payment.) While #5157 allows conversations to trigger events and yield payments, it does not allow for an `npc` block to be triggered based off of conversation choices (another request of #1564). Taking the route of adding an `npc` block into a conversation that triggers if reached seems like it would be a difficult undertaking and a messy solution to the problem of needing to delay certain events, but some sort of way to immediately activate an `npc` based off of conversation choices is still desired.

**Related Issue Links**
#1564

**Describe the solution you'd like**
Create a new `conditions` keyword for the `npc` block. This block is a ConditionSet (similar to `to offer`) that if evaluated to true will cause the associated ships to spawn for the mission. If the ConditionSet evaluates to false and the `npc` does not spawn its ships, then the objective associated with the `npc` (e.g. `kill`, `save`, etc.) is ignored.

```
npc kill
	conditions # only spawns if the following conditions are met
		has "made a bad choice"
		random < 50
	government "Pirate"
	ship "Falcon" "Bad Choice"
```

These conditions should be evaluated *after* the `on offer` has finished, meaning that a `conversation` can use the `apply` node to change the conditions that dictate whether the `npc` activates.

**Describe alternatives you've considered**
The only other alternative would be to do a similar thing as #5157 and allow `npc` blocks to be embedded within a conversation (#1564), but as mentioned, I imagine that would be messy and is not the best solution to the problem.

**Additional context**
N/A

**Comment by Amazinite** [comment]
This could also be used to have missions spawn more ships based off of the player's combat rating or net worth, leading to missions that scale with the player (without requiring duplicate or extra missions to handle the scaling).

**Comment by tehhowch** [comment]
Shouldn't be too difficult for someone to implement. I think as far as the keyword goes, `"to spawn"` is the logical choice.

There will be a small amount of fiddling to get the NPC completion logic to work correctly, as the NPC conditions must be checked if the block is empty or was ever found to be true (i.e. a `ConditionSet` might have been true and spawned the ships, but then later became false). It's also worth thinking about how we can optionally require that the NPCs were spawned, e.g. to gate the NPC appearance behind something, but still require the player to trigger it.

Do we need to consider defining similar logic for despawning NPCs? To me that sounds a lot like having the mission to which the NPCs exist be completed/failed.

**Comment by Zitchas** [comment]
This could be interesting. Especially the idea of having additional allies if the combat rating is below a certain amount. I've been thinking of adding a "helper" mission where if the player tries to do the satellite delivery mission for the Remnant and returns to Remnant planets without having completed it, the Remnant send some backup to help them out. This could be a way to fine tune that.

**Comment by Amazinite** [comment]
>Shouldn't be too difficult for someone to implement. I think as far as the keyword goes, `"to spawn"` is the logical choice.

I've been looking through the relevant files to see what would be necessary, and I thought of using `"to spawn"` as well, or maybe `"spawn conditions"`. Just something that makes it more obvious at a glance what the ConditionSet is doing.

>There will be a small amount of fiddling to get the NPC completion logic to work correctly, as the NPC conditions must be checked if the block is empty or was ever found to be true (i.e. a `ConditionSet` might have been true and spawned the ships, but then later became false).

I was thinking of just doing something akin to the damage calculation for weapons. That is, if the damage wasn't calculated in the past, then calculate it. If the damage was calculated in the past, then return what was calculated. In the same way here, the ConditionSet would be evaluated when the NPCs are placed (or not placed if it fails), and any subsequent check of the ConditionSet would refer back to the original result.

>It's also worth thinking about how we can optionally require that the NPCs were spawned, e.g. to gate the NPC appearance behind something, but still require the player to trigger it.

I believe that could be possible by having a conversation that triggers once an NPC's objective is done that has an `apply` node that provides a condition necessary for the completion of the mission. That forces the usage of a conversation, but I don't imagine that would be too much of an issue. Otherwise, perhaps we could create an `"on spawn"` block that applies conditions to the player once the NPCs are placed (where a `to complete` on the mission would then require those conditions).

>Do we need to consider defining similar logic for despawning NPCs?

`"to despawn"`? What would happen to the objective of NPCs that depsawned? And at that point having two keywords starting with "to", perhaps drop the quotes and make it just `to spawn` and `to despawn`, akin to `to offer`, `to fail`, `to complete` for missions.

**Comment by tehhowch** [comment]
> >There will be a small amount of fiddling to get the NPC completion logic to work correctly, as the NPC conditions must be checked if the block is empty or was ever found to be true (i.e. a `ConditionSet` might have been true and spawned the ships, but then later became false).
> 
> I was thinking of just doing something akin to the damage calculation for weapons. That is, if the damage wasn't calculated in the past, then calculate it. If the damage was calculated in the past, then return what was calculated. In the same way here, the ConditionSet would be evaluated when the NPCs are placed (or not placed if it fails), and any subsequent check of the ConditionSet would refer back to the original result.

The issue with that approach is serialization. If the mission is accepted and the NPCs have at some point met the spawn criteria and been placed, but then the player saves and quits, the game must correctly spawn the NPCs even if the spawn criteria are no longer met when evaluated. Probably the simplest manner is to clear the conditionset upon conditional spawn (since by default we shouldn't serialize an empty conditionset).

> >It's also worth thinking about how we can optionally require that the NPCs were spawned, e.g. to gate the NPC appearance behind something, but still require the player to trigger it.
> 
> I believe that could be possible by having a conversation that triggers once an NPC's objective is done that has an `apply` node that provides a condition necessary for the completion of the mission. That forces the usage of a conversation, but I don't imagine that would be too much of an issue. Otherwise, perhaps we could create an `"on spawn"` block that applies conditions to the player once the NPCs are placed (where a `to complete` on the mission would then require those conditions).

If we can achieve it without requiring a serialization keyword, great.

> >Do we need to consider defining similar logic for despawning NPCs?
> 
> `"to despawn"`? What would happen to the objective of NPCs that depsawned?

If we don't need it now and aren't being asked for it now, we shouldn't add it now. Probably there will be considerable opportunity for footguns should folks combine conditional spawns, conditional despawns, "required" spawns, and existing NPC success criteria. If we do add conditional despawning, we can start out by it being a content error to combine despawning with success criteria. Support can then be added later, if needed.

> And at that point having two keywords starting with "to", perhaps drop the quotes and make it just `to spawn` and `to despawn`, akin to `to offer`, `to fail`, `to complete` for missions.

Yes, the intent is to mimic the interface of mission actions.
