### ISSUE TITLE
Loading certain save files causes segmentation fault when opening the map.

### ISSUE THREAD

**Issue by 9d8** [endless-sky/endless-sky#5162]
**Describe the bug**
Loading one of my saves in the build for the latest commit 3d4a0b23 causes the game to segmentation fault whenever the map is opened. This save originated from the AppImage release of 0.9.12 stable and the map loads as intended in that version. 

**To Reproduce**
1. Download my save file
2. Load the save in the compiled 3d4a0b23
3. Press m or open the jobs tab
4. Game crashes

**Expected behavior**
The map should open as normal and the game shouldn't crash.

**System (please complete the following information):**
 - OS: Arch Linux 5.6.15-arch1-1
 - Game Source: self compiled using the ```scons``` command
 - Version: 3d4a0b23

**Link to save file**
https://pastebin.com/MxTPwMTb

**Additional context**
This bug only seems to occur with my main save. I couldn't replicate it with any test saves or less progressed saves that I have. I have not done any manual modifications to my save file nor ran it through unstable versions prior, so I do not think the save itself is corrupt.

**Comment by tehhowch** [comment]
Without looking at the save, it's either due to a missing plugin or some visible mission that references the now-removed Graveyard ringworld.

**Comment by Amazinite** [comment]
> it's either due to a missing plugin

Ref: #1874

> or some visible mission that references the now-removed Graveyard ringworld.

That mission does seem to be in the linked save file.

**Comment by 9d8** [comment]
I had the Quarg Graveyard ringworld quest still active. I went ahead and finished it on the stable release and now my save works on the latest build. Thank you both for your help.

**Comment by tehhowch** [comment]
Reopening this because this will be a bug in a future Steam release, unless we implement some countermeasure, e.g. fail the mission automatically if it is still active.

I don't exactly want us to "removed plugin" ourselves.

**Comment by Amazinite** [comment]
Perhaps, just like how if the player doesn't have a system or planet that they're on it defaults to New Boston, missions with missing systems or planets should default to New Boston. Either that, or autofail the mission.

**Comment by tehhowch** [comment]
I was thinking a combination of patch mission and finally landing https://github.com/endless-sky/endless-sky/pull/3462

The approach there doesn't allow checking suspended missions' failure criteria to avoid cheesing consequences, but I think allowing explicit external failures of suspended missions could be ok as a temporary behavior. After the next stable release we would remove that behavior.
