### ISSUE TITLE
[bug] Off-system Escorts fly away to other systems with only steering Engines

### ISSUE THREAD

**Issue by SkyFire512** [endless-sky/endless-sky#5165]
Unparking off-system escorts that are not equipped with thruster engines does not stop them from jumping to other systems.

1. Park an escort.
2. Sell escorts' thruster engines (so that the ship only has steering engines).
3. Take off and jump to a far away system.
4. Land and unpark escort.
5. Takeoff and wait for escorts to start jumping systems.

Expected behavior:
Game should not let you unpark escorts and takeoff while any off-system escorts fail flight checks (engines, power, heat).

Here is a screenshot: You can see the ship description that it does not have any thruster engines, and in the lower left you can see 4 ships of similar specs.
![image](https://user-images.githubusercontent.com/30810454/87876545-2e0b9100-c9f2-11ea-91c3-75e19f559605.png)

System:
 - OS:Windows 10 Pro 64-bit build 18363
 - Game Source: Steam
 - Version: 0.9.12

Save file:
When you load the save file, once you takeoff, you can immediately see the thruster-less ships on the bottom left jumping systems.
[Ember Serebryakova.txt](https://github.com/endless-sky/endless-sky/files/4943801/Ember.Serebryakova.txt)

Additional info:
When I unparked these ships, I was on Glaze in the Aldhibain system.
Issue looks related to #5133

Temporary fix:
I managed to herd the ships back to a spaceport with an outfitter. 

Apparently, once you take off from a planet, the ships are able to jump ONCE, after which they are unable to come to a stop and continue to float away. However, if you land and takeoff again they will be able to do another jump. You can repeat this until the ships come to a planet with an outfitter. 

If, however, the ships run out of fuel in a system with a habitable planet before they can reach an outfitter, you can go to that system, land (and hence refuel them), park the escorts(because the game wont let you takeoff if the escorts dont have engines), go to another system, and unpark them. Then you can continue to land and takeoff repeatedly to make the thruster-less ships jump.

It can get worse however. If the ships run out of fuel in an uninhabited system, you can not refuel them by landing, and you cannot simply board them either because when you jump into the system, they are drifting off at such a speed that they cannot be boarded. The solution here is to select the escort in question(by clicking on them) and disable them by firing at them. Disabling ships removes any velocity they have so they come a stop. This way you can board them to repair and refuel them.

**Comment by serhatgesoglu** [comment]
It seems that during departure only the ships within the current system are checked (PlayerInfo.cpp:779). 
> if(ship->GetSystem() == system && !ship->IsDisabled() && !ship->IsParked())

Since I am an Endless Sky newbie I should better ask. Why is it necessary to check the system here? As a dirty fix, I removed the first condition and the game now prevents me to depart unless all the unparked ships have thrusters though it needs more testing.
