### ISSUE TITLE
Request: Have Jump Drive range be an Attribute for Systems.

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5167]
**Problem:**
Jump Drives currently have a fixed and fairly large range, which means that parts of the galaxy (such as the Ember Waste) that are set up to be confusing and kind of like a maze must have reduced density because otherwise ships with JD can just skip right across it without worry. This also means that some areas (like the galactic core) are almost forcibly very sparse in systems despite being very dense in stars and thus potential systems.

**Related Issue Links**
https://github.com/endless-sky/endless-sky/issues/788

**Describe the solution you'd like**
I would like the addition of a "Jump Range" attribute that could be placed on systems. This would be an optional value, and if not set it would default to the current jump distance. If set, it would override the Jump Drive range when jumping out from that system.

**Impact**
- This would enable select systems and regions to be denser than the rest of the galaxy without overly promoting JD usage. 
- This could also be used to create some interesting variations on mazes, such as having systems that could be jumped into, but not out of, resulting in systems that the player needs to work their way out of the maze even if they jump in elsewhere. 
- Conversely, it could create "jumping off systems" that have significantly increased range where they could cover large distances but be hard to actually reach.

**Describe alternatives you've considered**
- Having JD distance be tied to a region of space. (which would be nice, but requires defining a new characteristic of thing in the game and more variable confusion.
- Spore had a variable system where the closer one was to the galactic core, the shorter the jump range was. This would solve some of the problems, but doesn't do anything for creating interesting sub-regions. It also introduces a new set of calculations and variables to the map as a whole.

**Comment by Janaszar** [comment]
So, as you may know, I've often toyed with the idea of changing jump-drive distances...

For this, I'd like to know three things regarding the mechanics:
1) Would the `Jump Range` attribute be a multiplier, an addition/subtraction to the value, or perhaps set it to a static value? Or allow for both (Multiplier + Addition/Subtraction or a Static value; if you're going to have a multiplier or addition, I'm going to advocate to include the other just for possible uses down the line)?

2) How would you handle things such as having an "Extended Jump Drive", which gives the player say, 200 jump distance, instead of the current 100?

3) How would you handle the map pathfinding algorithm?  Right now, it's a basic search checking only the distance between neighbors, and the hard-coded jump drive distance, to find a path.  Would you be adjusting the reported distance to the "neighbors", or would you leave it assuming standard distances?  If you adjust it, would it be by changing the reported distances, or would you be changing the jump distance just for that node?

Be interesting to see how this gets lored...  And the Mazes thing has been something I've been thinking about for a while.

**Comment by Amazinite** [comment]
1. I don't see why we couldn't have all three, although ideally we'd only add the one which is the most useful (as to not bloat things), and I only imagine myself using the static value.
2. Not sure what the heart of this question is. While this issue isn't about variable jump distances on outfits, I don't see why different JDs with their own differing ranges would be handled any differently than the standard JD. If the system has a static value, you still have a static value. If the system adds or subtracts, you still add or subtract. If the system multiplies, you still multiply.
3. I don't imagine it'd be much of an issue to update the pathfinding to account for the jump distance changing part way through the travel plan. The only change is that those systems which are considered "neighbors" is different.

**Comment by Zitchas** [comment]
Could be a lot of interesting ways to lore it. My current favorite for the Ember Waste is "Whatever happened here appears to have damaged the fabric of space/time. While it is currently healing, the sheer amount of matter and damage cause instabilities in the Jump Drive system, limiting it to shorter distances."

Having all those variations would  be good. (both additive and multiplicative)

Given MZ's stance on new drives, I suspect we won't see any new drives anytime soon. That being said, I really like the idea of having modifier drives. As in, outfits that we can install that modify the way drives work. Perhaps having a "Jump Drive Tunneling System" that takes up 10 tons of space but multiplies your Jump Distance radius by 1.25 or something. Probably would want that to either be a special plot related outfit or something, 'cause increasing the jump drive distance by much will totally break most of the funnels and path shaping done using system spacing.

**Comment by Janaszar** [comment]
Late, but figured reply for posterity...

To Derpy:
1) Static is most likely the high-use one, but maybe someone wants some major jumping off point for their plugin civilization that then lets you meet some new people if you have some even greater jump drive range.

2) Mainly refers to using the static value change.  +100 range means a lot if you're using a standard jump drive, not so much if you're using, purely for example, a 1000 range one.  Then things such as having a maze to work through become redundant when you can just hop over it.

**Comment by Amazinite** [comment]
#5193 goes the route of only having a static jump distance, as that is much, much simpler to achieve with how I designed that PR compared to multipliers or adding/subtracting. I'd suggest that anyone who would want 
> some major jumping off point for their plugin civilization that then lets you meet some new people if you have some even greater jump drive range

instead make use of the events system for such gating.
