### ISSUE TITLE
(suggestion) Make escorts and enemies more reactive to what happens

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#517]
Currently working on two personal ideas, a Tractor Beam  and a Healing Beam, tractor beam works fine and healing beam is basically an ineffective beam that does nothing, but any escorts i have turn hostile towards the friendly and the friendly itself turns hostile, this makes any future of helping people out using weapons nonexistant :p maybe have them similar to the way the Quarg are (in regards to them not turning hostile till after a certain amount of damage is done) and have the damage required for them to turn hostile to be like 1 shield damage

**Comment by thenerdfreak** [comment]
[Tractor Beam.txt](https://github.com/endless-sky/endless-sky/files/72928/Tractor.Beam.txt)
This is my FunBeam so far xD

**Comment by endless-sky** [comment]
I've modified the provocation code so that "weapons" that heal damage instead of inflicting it will not provoke a hostile response. (74b404b) The AI still won't use them correctly (i.e. it won't use them to heal friendly ships) but at least it's a start.

**Comment by thenerdfreak** [comment]
What about neutral weapons that do no damage, in the case of the tractor beam? Also, healing beams don't really work, the negative number seems to just nullify the damage instead of reversing it

**Comment by thenerdfreak** [comment]
I was thinking of small drones outfitted with healing Nanite Beams whose soul purpose was to heal their mothership

**Comment by thenerdfreak** [comment]
I've managed to get shields to repair using a negative value, but hull damage still doesn't appear in the attributes list, despite me using the basic template of other outfits

**Comment by thenerdfreak** [comment]
I can only manage to get one attribute (shield or hull) to heal at a time, despite moving around the values and making sure spacing is okay, etc. what's going wrong?  "hull damage" -5(tab)(tab)"shield damage" -5(tab)(tab)description

**Comment by thenerdfreak** [comment]
Managed to get everything to work properly, despite "hull damage" needing to go before "fire rate"

**Comment by thenerdfreak** [comment]
Only issue now is, as long as there are shields up, hull won't repair because everything gets directed at shields first

**Comment by endless-sky** [comment]
The new "piercing" attribute will let you create repair beams that work even if a ship's shields are up.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
