### ISSUE TITLE
Remove `using namespace std;`

### ISSUE THREAD

**Issue by tux2603** [endless-sky/endless-sky#5172]
**Is your feature request related to a problem? Please describe.**
Not any particular problem that I'm currently aware of, but it's considered best practice and I was looking to familiarize myself with the code base anyway

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I will go through and remove `using namespace std;` as necessary. This is a self assigned issue

**Describe alternatives you've considered**
To follow best practice and use the `std::` prefix as needed

**Additional context**
I'll check back with a PR (hopefully) soon

**Comment by Amazinite** [comment]
From the [style guide](https://endless-sky.github.io/styleguide/styleguide.xml):

> Each .cpp file should put "using namespace std;" immediately after the #includes.
> Because our class and function names are capitalized, there is no risk of name collision, and it is simply cleaner to not have to use the std:: prefix everywhere.

Unless there's something to be gained from making this change, I don't see it as necessary.

**Comment by tux2603** [comment]
Okay boss :vulcan_salute:
