### ISSUE TITLE
Bug: FW Pug 3 in free worlds reconciliation may trigger before previous mission is completed

### ISSUE THREAD

**Issue by pega3** [endless-sky/endless-sky#5174]
**Describe the bug**
User Lake on Discord reported that he got on the one hand the message that the escort with Alondo on it hasn't entered the system, but on the other hand got already displayed the intro to the next mission. 

Reason is that FW Pug 3 does not refer any of the preceding missions in it's triggering condition, but will always fire when the player lands on Pugglemug with "fw given jump drive"

**To Reproduce**
1. Before entering the FW Pug mission string, have a fully crewed flagship, so that Alondo will be placed on an escort. 
2. Since the jump drive gets only installed on the flag ship, the escort with Alondo will not be able to travel to Pugglemug
3. Land on Pugglemug with your flag ship. You will be displayed both the "on visit" message of the active mission, as the "on offer" text of the subsequent mission.

**Expected behavior**
FW Pug 3 should only trigger when the player lands on Pugglemug, while Alondo is on the ship. 

**To fix**
Add conditions referring the previous mission to the "to offer" section of FW Pug 3

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/bbdaf30f5cac9f78b91b363d9f2cbb8730a3af9d.
