### ISSUE TITLE
If the fast-forward key is bound to caps lock, use the state of caps lock instead of only toggling when pressed

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5177]
**Is your feature request related to a problem? Please describe.**
If the fast-forward key is bound to caps lock, then the state of fast-forward in game and the state of caps lock on the player's computer can become desynced. That is, the game might be in fast forward, but caps lock on the player's computer might be off, and vice versa. This is more of an annoyance than a major issue, but with the merging of #5148, this desync will likely become more apparent to players as the game forces fast-forward off in certain scenarios.

**Related Issue Links**
#5038 and the related PRs that came after it mention the desync between the state of caps lock and fast-forward being an issue.

**Describe the solution you'd like**
If the fast-forward key is bound to caps lock then instead of simply using the caps lock as a key to toggle fast-forward, instead check the state of caps lock on the computer and use that to set fast-forward. If fast-forward is bound to any other key, then use the current toggle behavior.

**Describe alternatives you've considered**
Find a separate key to bind fast-forward to by default that does not change some state on the player's computer.

**Additional context**
In EV Nova, I recall the behavior described here being how fast-forward and caps lock behaved. That is, if you activated fast-forward (and therefore also activated your caps lock), left the game, turned caps lock off, then returned, fast-forward would be off.

**Comment by Amazinite** [comment]
It seems to be the case that people generally would rather the key just be changed. Space bar was a suggested key as that is currently unused in the default control scheme.

**Comment by Jonster5** [comment]
> It seems to be the case that people generally would rather the key just be changed. Space bar was a suggested key as that is currently unused in the default control scheme.

isn't space used for firing the primary weapon?

**Comment by Amazinite** [comment]
The [default primary fire key](https://github.com/endless-sky/endless-sky/wiki/PlayersManual#default-key-bindings) is currently tab.

**Comment by Zitchas** [comment]
I'm not really sure about anyone else, but tab has never worked for me as a "fire primary weapon" key. It's currently the "nearest hostile". I don't think fast-forward being on spacebar really makes any sense. Accelerating the game just doesn't seem like the sort of thing that should be front-and-center deserving of the biggest key on the keyboard.

But yeah, having the game actually sense caps-lock's state and base the fast-forward on that would be nice. Alternatively, in the current "disable fast forward after landing" scheme, it'd be nice if the caps-lock could be deactivated (optionally), but I don't know if we can do that.

**Comment by opusforlife2** [comment]
It's pretty weird that caps lock is used in the game as a key at all. Never seen that before in any game.

Another option for the FF key I've seen in other games is Shift (Left Shift, if you can assign it independent of the other).

**Comment by Hurleveur** [comment]
I personally always tab out to disable my caps lock out of the game without it affecting the speed, changing it to tab makes more sense, I think.
