### ISSUE TITLE
Suggestion: A new production from the fellows on Rust?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#518]
[particle turret.zip](https://github.com/endless-sky/endless-sky/files/72966/particle.turret.zip)

**Comment by thenerdfreak** [comment]
I've managed to come up with this as a plugin: (unzip into plugins obv)
[Particle Turret.zip](https://github.com/endless-sky/endless-sky/files/73042/Particle.Turret.zip)

**Comment by jafdy** [comment]
we already have a particle canon and "particle turret" implies (at lest to me) that it is a turreted particle canon.

**Comment by thenerdfreak** [comment]
what...?^

**Comment by thenerdfreak** [comment]
the whole point of this is to add a PARTICLE TURRET, not re-add the particle cannon

**Comment by thenerdfreak** [comment]
doesn't look perfect, figured out that, due to the way the game handles turrets (simply doubling fire speed of the base gun and leaving everything else alone) I won't need a 2x particle beam. Added a texture to gun (albeit it isn't perfect, hardly distinguishable from any other turret in the outfit screen though) 
[Particle Turret.zip](https://github.com/endless-sky/endless-sky/files/73314/Particle.Turret.zip)

**Comment by Wrzlprnft** [comment]
@jafdy it is exactly a turreted particle cannon

**Comment by thenerdfreak** [comment]
I really don't think English is his first language, he was on at 2:30 central time xD anything you see in the files that needs balanced/changed? I went and looked and apparently they have so much fire force they can be used as a backwards thruster, then again so can the normal particle cannons

**Comment by Wrzlprnft** [comment]
I am not really good at balancing, that's basically the point which prevents me from putting my ideas up here. i figuerd out, if you want to balance something... test it. but not only like "ah it works" but like combine it with all kinds of ships and outfits.
i didn't see anything in particular at the first look though

**Comment by thenerdfreak** [comment]
It's basically the plasma turret of particle beams. I did everything that the plasma turret did to the plasma cannon (doubling the fire rate is basically all I saw)

**Comment by thenerdfreak** [comment]
Finna try it out on a headhunter (because I see it as being a good replacement to the anti missile turret) and post results here.

**Comment by Wrzlprnft** [comment]
Good job, good idea, the step of creation is done, but a turret is a larger and more sophisticated construct than a cannon, so maybe there are mechanics built in to reduce the recoil and volia you have an in game reason to balance it

**Comment by thenerdfreak** [comment]
Yeah the recoil is ridiculous, but it's the same as the weapon version, and has the same pushback  as two cannons

**Comment by Wrzlprnft** [comment]
Oh, and if i remember right, particle cannons aren't stuff of the free worlds, so i wouldn't conect the turrets to rust, but that's something that becomes important after they actually work

**Comment by thenerdfreak** [comment]
yeah, currently I really like Rust so Rust is my testing facility for everything

**Comment by thenerdfreak** [comment]
Works really well as a single gun on the headhunter, really good for taking out small targets and especially those pesky missile furies

**Comment by thenerdfreak** [comment]
(it literally fits perfectly with the weapon capacity)

**Comment by jafdy** [comment]
If you care to look at the time in relation to country other than your own then you may have realized that I could be living in the UK.

**Comment by thenerdfreak** [comment]
I was saying that because of the lack of grammatical structure and relatively very little sense you were making in your comment, as you basically pointed out the given fact that it is particle turret :p

**Comment by jafdy** [comment]
It was the particle turret on Rust bit that got me. Someone who was far more awake than me said it better. And my grammar is very much an English way of putting it as well as being the way I would say it.

**Comment by thenerdfreak** [comment]
I didn't understand that you were talking about it being on Rust, sorry. I assumed you meant it was just a copy of the particle turret by the way you structured your comment "we already have a particle cannon" but back on topic, see any issues that need balancing?

**Comment by jafdy** [comment]
If it's quite literally two particle cannons on a turret then the only risk is the ability to put a huge amount of particle cannons on a single ship. Other than that it should be balanced fairly reasonably. The only other thing is that a particle cannon by the way it has to be designed will inevitably be fairly long and it seems slightly unlikely the you could fit something on a near instant targeting turret.

**Comment by thenerdfreak** [comment]
They did it with the plasma turret and it's the same weight and nearly the same length, with more fire power iirc

**Comment by jafdy** [comment]
All the guns are the same size in the pictures and i guess the push factor would still be less than a banisher. You just need to find a good place to sell it and a good reason to start selling it.

**Comment by endless-sky** [comment]
This would need to be much bigger than the Plasma Turret, since each Particle Cannon is 5T bigger than a Plasma Cannon. It should probably be about 70-72 tons.

Also, since the Plasma Turret is a special weapon available only in the Free Worlds story line, and this is an even more powerful weapon, it would also need to be a story-related weapon and not something anyone can buy. Otherwise the Plasma Turret would not be such an impressive new technology when it becomes available.

**Comment by thenerdfreak** [comment]
Yes, I was talking earlier about making it into a story-line acquired weapon. and I didn't notice that weight difference, outfit space has been updated in my files. currently attempting to write a mission where the same people who developed the Catalytic Ramscoop (those up in the deep) develop this a little after the FW missions end

**Comment by natangold** [comment]
Based on where the particle cannon is available, I’d suggest that the turret should come from either Lovelace Labs or the Navy.

**Comment by thenerdfreak** [comment]
Here is the actual turret at least, finna start on the mission for it (I've all but given up on the healing beam. Got the actual heal, the beam, and the targeting right, but sounds and hit effects won't work. i'll just try again on that tomorrow. 
[Particle Turret.zip](https://github.com/endless-sky/endless-sky/files/73580/Particle.Turret.zip)

**Comment by thenerdfreak** [comment]
Figured i'd try to use a different base for the healing laser, gonna have to re-make everything except for the thumbnail (thankheavens that took 30 mins)

**Comment by endless-sky** [comment]
If you want to add this as the end result of some sort of post-story-line string of special missions, that might work. It's certainly not something that can become available before the plasma turret, though.

For now, since this is just a content change and it's not ready to merge in yet, please move the discussion to the forum, so the issues tracker can stay focused on bugs and feature requests.
