### ISSUE TITLE
Sometimes it's hard to un-hold a fleet

### ISSUE THREAD

**Issue by 7eggert** [endless-sky/endless-sky#5182]
**Describe the bug**
Sometimes when I have commanded the fleet to hold position, pressing "h" will not stop that command unless I press the key several times. However, pressing 'h' once to often will immediately result in the fleet holding position again.

**System (please complete the following information):**
OS: OpenSuse Tumbleweed / Steam on 2020-07-27
Version: 0.9.12

**Comment by Amazinite** [comment]
You might be a fan of #5040.

**Comment by Amazinite** [comment]
Fixed by merging #5040.
