### ISSUE TITLE
images/effect/explosion/pug/large~3.png and 4 files look out of place

### ISSUE THREAD

**Issue by janisozaur** [endless-sky/endless-sky#5186]
The files introduced in https://github.com/endless-sky/endless-sky/pull/3957 are inconsistent.

Version tested: ec110d417e44b7976d201290e152be2bd9b0a55b

`large~[0125678].png` all have dimensions 140x140, but `large~[34].png` are 200x200 and of substantially lower quality.

problematic files:
`large~3.png`: ![](https://github.com/endless-sky/endless-sky/raw/ec110d417e44b7976d201290e152be2bd9b0a55b/images/effect/explosion/pug/large%7E3.png)

`large~4.png`: ![](https://github.com/endless-sky/endless-sky/raw/ec110d417e44b7976d201290e152be2bd9b0a55b/images/effect/explosion/pug/large%7E4.png)

correct file:
`large~2.png`: ![](https://github.com/endless-sky/endless-sky/raw/ec110d417e44b7976d201290e152be2bd9b0a55b/images/effect/explosion/pug/large%7E2.png)

The reason this is particularly problematic is having such animation frames in varying sizes will prevent them from loading:
https://github.com/endless-sky/endless-sky/blob/ec110d417e44b7976d201290e152be2bd9b0a55b/source/ImageBuffer.cpp#L220-L226

1. the buffer gets allocated for frame 0 with 140x140 dimensions
2. new frames are added until frame 3 is reached
3. frame 3 tries to allocate buffer of size 200x200 and exits early

The best solution is to redo the frames 3 and 4 with improved quality and in proper size, if original assets are still available. Failing to do that, resize frames to common size: either 140x140 or 200x200.

**Comment by janisozaur** [comment]
https://github.com/endless-sky/endless-sky-high-dpi/pull/56 seems unaffected, perhaps restoring files from there is enough.

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/4e57ece974a7678b2f8a455909aec4db2cb086f3.
