### ISSUE TITLE
Displaying all available licenses and displaying all not available licenses

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#519]
Maybe an extra Button in the info Screen where it say which licenses are already in the game, available somehow and which are not available at the moment, and information about the licenses which aren't but obvious or mentioned.
Because this navy license...

**Comment by thenerdfreak** [comment]
is literally impossible to get. You'll have to capture those navy ships you want like I did xD

**Comment by Wrzlprnft** [comment]
... Because this navy license threads in the steam forum are driving me nuts.
It's like every week there appears another one.

**Comment by thenerdfreak** [comment]
yeah. Is there a parameter for "has navy license" even? or are they just not purchasable at all the no license exists?

**Comment by Wrzlprnft** [comment]
The license type is in the conditions section in the savefile, but in the outfits.txt there is only the pilot's license.
My point is to display somthing like a list of licenses, the ones you have written white, the ones you don't have grey. if you hover your mouse over it, it displays some information, which tells for the navy license e.g. something like "after the terror attack on geminus the navy froze all applications for the navy license, and nobody knows when this state will change"
So half the players discover this on their own in the game, and can directly answer the (less) questions of the lazy ones in the steam forum.
Once @endless-sky worked out his logbook idea it could be located on it's front page, meanwhile i would just make an extra window, accessable mabye through the information screen

**Comment by endless-sky** [comment]
Eventually, there will be lots of possible licenses offered by alien species that you do not even know about in the beginning of the game. So, giving a list of *all* licenses doesn't make sense. I think the real way this should be solved is by adding a Republic story line, but obviously that will take a while.

**Comment by Wrzlprnft** [comment]
i wouldn't show them or display three questionmarks

**Comment by Wrzlprnft** [comment]
i thought of dumping the alien race i was working on, or pause them at least, to work on parts of a republic storyline, but it is so hard to get an overview of who is working on what, so i am not quite sure what to do
