### ISSUE TITLE
Incorrect warning when landing on Valhalla for "Star Research" mission.

### ISSUE THREAD

**Issue by lucapton** [endless-sky/endless-sky#5195]
**Describe the bug**
When I land at Valhalla, with the mission "Star Research" I get the message "You and on Valhalla, but realize that the scientists and their equipment were on one of your escorts who hasn't entered the system yet. Better depart and wait for them." Thing is, all my escorts are with me. In reality I think the problem is that I haven't gone to Ildaria yet. So really the problem is that the message is just misleading.

**To Reproduce**
1. Get the mission Star Research
2. Land on Valhalla in Epsilon Leonis (you might need escorts)

**Expected behavior**
Tell me to go to the Ildaria system, or even just say nothing.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 Pro, version 1909 build 18363.959
 - Game Source: Steam
 - Version: I don't know. Whatever is currently the default on steam.

**Link to save file**
[save file](https://github.com/endless-sky/endless-sky/files/5009826/Luca_ESsave.txt)

**Additional context**
None

**Comment by Amazinite** [comment]
Merged #5199, which updates the on visit dialog to mention all possible missing objectives.
