### ISSUE TITLE
created weapons have a "magnetic field" like avoidance

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#520]
I'm working more extensively on a heal beam, but the auto target feature won't work with the beam, it seems to aim 45 degrees away from the target and fire at nothing, when i try to align, autotarget moves it back to where it was, and when i get on the other side, it goes 45 degrees in the other direction, almost like my ship and the other ship are magnets with the same charge

**Comment by thenerdfreak** [comment]
I have tried remaking everything from scratch, and nothing seems to work. Here is the file, can someone locate the issue? also can't get the sound to work or the hit effects, and both of those were working earlier 
[Healing Beam.zip](https://github.com/endless-sky/endless-sky/files/73522/Healing.Beam.zip)

**Comment by thenerdfreak** [comment]
By making it be in a turret spot it fixes the issue of it not targeting right (still have no clue why it's doing that)

**Comment by endless-sky** [comment]
Your formatting is rather messed up, and that may be causing problems. You should start with one of the existing weapons, and edit the data in a real text editor designed for programming (like Notepad++), rather than in something like Word or Notepad.

**Comment by thenerdfreak** [comment]
I did exactly that

**Comment by thenerdfreak** [comment]
Re did the whole thing again and it's still having the same issues, tried making another gun port slotted weapon and it does the same thing 
[Healing Beam.txt](https://github.com/endless-sky/endless-sky/files/73611/Healing.Beam.txt)

**Comment by endless-sky** [comment]
The trouble was that auto-aiming gives each individual weapon a weight based on how much damage it does, so a healing weapon ends up with a negative weight - meaning that it makes you aim it *away* from your target rather than towards it. That should be fixed in f5859cf.

**Comment by thenerdfreak** [comment]
Yes I figured this out, i'll close my new issue as well
