### ISSUE TITLE
Unable to land on Elnath, ports in system colored as Quarg instead of Republic

### ISSUE THREAD

**Issue by pyorokun7** [endless-sky/endless-sky#5201]
**Describe the bug**
Some days after the secession of the Free Worlds, but without starting the campaign yet, after buying a ship in Alphard I was doing missions but when attempting to land in Elnath I get the message "The authorities on this planet/station refuse to clear you to land here". They even demand bribes to allow me to land.

Both the station and planet are supposed to be Republic, but when looking at the system in the map, both have a yellow color like the Quarg, instead of the Republic blue.

It is my first visit to the system. I can land on all other Republic systems, so far.

**To Reproduce**

**Expected behavior**
Should be allowed to land in all Republic systems, before starting the FW campaign

**Screenshots**
![image](https://user-images.githubusercontent.com/8069514/89130820-c06d6380-d4cd-11ea-8007-78db3cfb3e34.png)
![image](https://user-images.githubusercontent.com/8069514/89130942-f828db00-d4ce-11ea-956c-e02cace69426.png)
![image](https://user-images.githubusercontent.com/8069514/89131039-a896df00-d4cf-11ea-810f-9c2e0209b363.png)

**System (please complete the following information):**
 - OS: Windows 10 Pro, version 10.0.18363 build 18363
 - Game Source: Steam
 - Version: 0.9.12

**Link to save file**
[Joran Elith.txt](https://github.com/endless-sky/endless-sky/files/5012741/Joran.Elith.txt)

**Additional context**
When scheduling the landing on either planet or station and jumping, I get the message of autolanding, but when the ship arrives to the destination, the landing fails silently, the ship just stays above the planet.

**Comment by Amazinite** [comment]
On the system map, yellow means restricted access. Blue means you can land, and orange/red means hostile.
Restricted access means you are friendly but unable to land. 

> Should be allowed to land in all Republic systems, before starting the FW campaign

It is intended behavior that after the bombings of Geminus and Martini, the reputation required to land on planets within the Paradise Worlds increases. Basically, they've increased the security on these planets because of the bombings. You simply don't have the reputation required to land on the mentioned planets.

**Comment by pyorokun7** [comment]
Hmm, I see it now. I had selected the Government filter, not the System one.

Apologies.
