### ISSUE TITLE
"Discovered Remnant Space" mission and "Remnant Space" label for the Galactic map

### ISSUE THREAD

**Issue by jchamlin** [endless-sky/endless-sky#5208]
**Is your feature request related to a problem? Please describe.**

Right now there is no condition "Discovered Remnant Space" like there is for all other races. Normally that mission triggers the first time you land on an alien government's planet. Also, related, there's also no galaxy label "Remnant Space" applied to their space when it is discovered like the other races have. The Remnant are getting short-changed. And the  player isn't being given important information available on their galactic map like it is for all the other races.

When I was first starting out in ES, when it was hard to keep track of the names of all the different things I was learning, it confused me that there was no label on the map to remind me where Remnant space was, like there is for every other race I had found. The label is not for the Remnant, it is for the player. It is the player's map afterall. I actually had to fall back to someone else's annotated map of the regions that had all the factions labelled.

![ES Map with Factions](https://steamuserimages-a.akamaihd.net/ugc/2434635248999425018/9109567048E570DE330A2D0CED6946C207D85F22/)

But that map also had some spoilers that the galactic map wouldn't have had, which was unfortunate. For a new player, having the map tell them where the Remnant are after they've discovered them is useful. It works that way for all the other races, why not the Remnant? Anyway, now that I'm a veteran player and have the areas memorized (still have a hard time remembering most systems and planet names, but it's gradually coming), so it's not a big deal anymore. I think this only matters for newer players, those that haven't played long enough to discover and memorize everything. If you are a veteran, you probably can't remember what it was like not to know everything in the game.

I would also like to setup a situation that only triggers after the player has discovered all the races. Right now, I have to do something like this:

```
		has "Discovered Coalition Space: offered"
		has "Discovered Hai Space: offered"
		has "Discovered Korath Space: offered"
		has "Discovered Wanderer Space: offered"
		has "First Contact: Remnant: offered"
```

However, when I, or anyone else looks at this code though, the initial instinct because of the inconsistency is, is that a mistake? Or if not, is it intentional? If so, why would they not use the `Discovered Remnant Space: offered` instead? Then they'll go looking, just like I did, and find out it doesn't exist. They might even come here and find this issue at some point.

**Related Issue Links**

I couldn't find any related issues.

**Describe the solution you'd like**

Consistency. It's more professional, and causes less issues down the road.

I think a hidden mission should be added to remnant missions.txt that is just like the other races have. Like this:

```
mission "Discovered Remnant Space"
	landing
	invisible
	source
		government "Remnant"
	on offer
		fail
```

Also, we would probably have to deal with compatibility and also just check for the First Contact to trigger this mission as well. That way, players who have already discovered the Remnant get the mission into their conditions.

As well, the mission could trigger an event to label the Remnant Space. They only have three systems, and right now the Ember Wastes label intrudes into their space, so I think the Ember Wastes label might need a little tweaking to be able to fit in a Remnant Space label.

I can do the work for the missions, but I don't have access to the fonts and the art skills to modify the Ember Wastes label or create the Remnant Space label. If someone could provide those, I can do the rest of the work.

**Describe alternatives you've considered**

Use has "First Contact: Remnant: offered" in my missions. It doesn't look consistent though.

**Additional context**

None

**Comment by Zitchas** [comment]
While I appreciate the fervor for the Remnant, "The Ember Waste" *is* their territory. They don't particularly feel the need to label any particular place after themselves. They see themselves as the last bastion of humanity, the ones who will ensure that humanity survives. So in a very real sense, they consider the whole of human territory as "theirs," Of course, they are practical enough to know that it isn't actually under their control, but it is human space, after all.

Likewise, the trio of obvious Remnant worlds are just that - the obvious ones. So it might be a bit hard to draw a line around exactly where their territory is...

**Comment by jchamlin** [comment]
Maybe at least having the mission "Discovered Remnant Space" then? What harm would that be?

**Comment by Amazinite** [comment]
> I'd like to setup a situation that only triggers after the player has discovered the spaces for all other races. Right now, I have to do something like this:

If for some reason you want consistency in the conditions used, then either use all the first contacts, or use all the events that create the labels in the first place (e.g. `"event: label hai space"`, `"event: label wanderer space"`, etc.). I see zero need for this though as things already work as is.

**Comment by jchamlin** [comment]
There's no equivalent to "Discovered Korath Space" with First Contact attributes. There's a bunch of different ones, would have to check them all with an or clause.

**Comment by jchamlin** [comment]
> > I'd like to setup a situation that only triggers after the player has discovered the spaces for all other races. Right now, I have to do something like this:
> 
> If for some reason you want consistency in the conditions used, then either use all the first contacts, or use all the events that create the labels in the first place (e.g. `"event: label hai space"`, `"event: label wanderer space"`, etc.). I see zero need for this though as things already work as is.

**Comment by jchamlin** [comment]
> While I appreciate the fervor for the Remnant, "The Ember Waste" _is_ their territory. They don't particularly feel the need to label any particular place after themselves.

When I was first starting out in ES, when it was hard to keep track of the names of all the different things I was learning, it confused me that there was no label on the map to remind me where Remnant Space was, like there is for every other race. I actually had to fall back to someone else's annotated map of the regions that had all the factions labelled (but also had some spoilers that the galactic map wouldn't have had). I just think that for a new player, having the map tell them where the Remnant are after they've discovered them would be a nice to have. Either that, or let me, a star captain, make notes on my own map or add my own entries to my ship's log system. :)

**Comment by Zitchas** [comment]
Well, the ability to make custom notes on the map is something I'd really like to have; but that's out of the realm of my ability to code.

There is the "First Contact: Remnant" mission that can be used as such. So long as it has been offered, the player has definitely visited the Remnant.

Unlike most other races, the Remnant are a situation where the user can have a hostile reaction to the first contact. 

`: offered` means that the player has met the Remnant
`: declined` means that the player ha met them and had a friendly first start.
`: completed` means the player initially rejected the blood test but then went on to accept the second chance.
`: failed` means that the player refused the opportunity for a second chance.

the conditions "remnant: declined second chance" is also something that can be tested to show someone met and had a bad first contact with the Remnant.

**Comment by jchamlin** [comment]
> There is the "First Contact: Remnant" mission that can be used as such. So long as it has been offered, the player has definitely visited the Remnant.

Yes, that's what I'm using.

```
		has "Discovered Coalition Space: offered"
		has "Discovered Hai Space: offered"
		has "Discovered Korath Space: offered"
		has "Discovered Wanderer Space: offered"
		has "First Contact: Remnant: offered"
```
When I, or anyone else looks at the code though, the initial instinct because of the inconsistency is going to be, is that a mistake? Or if not, is it intentional? If so, why would they not use the `Discovered Remnant Space: offered` instead? Then they'll go looking, just like I did, and find out it doesn't exist. They might even come here and find this thread at some point. And then wonder why the 10 lines of mission code was never added to ES.

**Comment by Zitchas** [comment]
I kind of suspect that there might have been a change in design philosophy at some point there. I don't really see a problem with adding such a mission - it is simple enough, after all. Just the back and forth between desire for efficiency (we've already got something that does that) with the desire for completeness (every other area has one, why don't the Remnant?).

Something else that will get brought up is the whole "why have a mission that doesn't do anything?" If there's missions or other content that depends on it, that'd be more pursuasive than just for the sake of completeness of the pilot file.

**Comment by Amazinite** [comment]
> When I, or anyone else looks at this code though, the initial instinct because of the inconsistency is going to be, is that a mistake? Or if not, is it intentional? If so, why would they not use the `Discovered Remnant Space: offered` instead?

The "Discovered X Space" missions were all added for their respective factions long after those factions were added to the game in order to give them labels on the map. The reason for a separate mission instead of just triggering the event in the first contact was so that old pilots who had already made first contact would get the map labels. The label for the Ember Waste on the other hand was added the same update that the Remnant were, meaning that there as no need for a separate mission just for the map label.
https://github.com/endless-sky/endless-sky/commit/c993234fc5944223ea24fcf0b69042b7d534ef6e
https://github.com/endless-sky/endless-sky/commit/27dc6213e683a19a98f1019c3bc068f540914f96
