### ISSUE TITLE
Conquering Planets after Demanding Tribute

### ISSUE THREAD

**Issue by Emperor-Aipple** [endless-sky/endless-sky#5216]
Hi,

One of the things which I've always liked about endless sky, is being able to demand tribute from the pirate planets to afford your fleet. What I am suggesting is, once you have successfully demanded tribute from a planet, you can then try to dominate the planet under your name, or faction. This would probably need to be a harder fight at a greater difficulty. Once you have successfully taken a planet, I would think that (saying it is a pirate planet) pirate fleets would no longer spawn and you can buy ships and outfits without a license. This would add another way to play, as being a warlord, taking down factions and taking over the universe. An idea for the shown faction could be the player's name, or something which can be toggled in the player info menu. 

One of the problems of this idea, would be receiving certain missions. These missions would include ones such as Admiral Danforth if you have dominated Farpoint, so I'd recommend having a faction requirement of a planet on mission offers.

**Comment by InfiniteDonuts** [comment]
This is an awesome idea. The first time I played ES, I cheated and gave myself 1000000000000 credits, bought a bunch of Leviathans, and went on a rampage against the Syndicate. I was disappointed because I couldn't take over their planets.

**Comment by Amazinite** [comment]
The tribute mechanic is largely meant as a minigame for people with nothing else to do. There are no plans to expand upon it outside of allowing you to demand tribute from more systems.

**Comment by tehhowch** [comment]
This is not a 4X. If you would like to play a 4X, you will need to either play a different game, or use existing tribute conditions to create your own plugin that does this, with successful missions spawning events that modify the respective planets.
