### ISSUE TITLE
Side mission lacks Payment - Earth Retirement

### ISSUE THREAD

**Issue by JakubFojtik** [endless-sky/endless-sky#5221]
**Describe the bug**
The mission conversation mentions `<payment>,` but none is defined and the text shows "credits with total value of .".

**To Reproduce**
Complete the `human/transport missions.txt` mission **Earth Retirement**

**Additional context**
I tried to add the payment but maybe it can not be added to the conversation so easily.
Maybe the mission would have to be reworked so that accepting payment causes completion and declining payment fails the mission?

**Comment by Amazinite** [comment]
This is intentional. It will be added once #5157 is finalized.

**Comment by JakubFojtik** [comment]
Wow that was quick!
Seems i was right that currently it can't be added easily.
I guess this can be closed if someone is keeping track of the missions that are waiting for that PR.
