### ISSUE TITLE
Mission fail due to load with offsite cargo

### ISSUE THREAD

**Issue by shnwnd** [endless-sky/endless-sky#5224]
Mission fail due to load with offsite cargo

**Describe the bug**
A bug in saving / loading the location of cargo within in a fleet.

**To Reproduce**
1. [L]oad save [1]
2. Have a fleet with very little cargo capacity, every ship has 0 cargo space except for one ship. [2]
3. Have a single cargo ship with some capacity it is a bit slow. [3]
4. Get a mission with a cargo delivery requirement. [4]
5. Go to a planet, outpace the cargo ship [5]
6. [l]and while the cargo ship is out of the system.
7. [Esc]ape to menu (or close game)
8. [L]oad save
9. [D]epart
10. See error "If you take off now you will fail a mission due to not having enough cargo space to hold 15 tons of your mission cargo. Are you sure you want to continue?"

[2] Bounders with 2 `Outfits expansion` s each == 0 cargo space
[3] Scout with `x1200 Ion Steering` and `x1700 Ion Thruster`
[4] specifically `mission "Cargo [2]"`
[5] might be helpful to order the cargo ship to hold position? untested

**Expected behavior**
I expected to depart the planet without errors.
I expected the mission cargo to not magically teleport around when saving/loading.
The mission cargo should have stayed with the cargo ship that was carrying it, even across reloads.
I expected a load game to restore the game to the state it was in when it was saved.

**System (please complete the following information):**
 - OS: Chromebook 84.0.4147.83 (Official Build) beta (64-bit)
 - Game Source: self-compiled
 - Version: commit hash 894f55673efac77391f8c9936f21385adf38da35

**Link to save file**
[1] https://gist.github.com/shnwnd/907d3979d1565738edc490f42ca4f1f0

**Comment by Amazinite** [comment]
#1624
