### ISSUE TITLE
Don't overwrite the save on game load if the player is on a non existant location

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#5227]
**Describe the bug**
Currently, as soon as I open the game, if the player is on a planet that is not defined, it gets automatically teleported to New Boston, which is a nice way to prevent a crash; but, since i'm used to keep at least 2 versions of ES (one the stable release, one continuous release, plus any PR I might be testing thanks to the ES launcher), this often causes me to lose the most recent save whenever I misclick and open a precedent version, where the location I was on is not present.

**To Reproduce**
1. Download a PR that defines a new planet
2. Land on it
3. Close the game
4. Reopen it on vanilla 0.9.12 and close the game without doing anything
5. Reopen the game on the PR version (where the planet exists and is defined)
6. See how you are on New Boston even if the planet you were on exists now.

Alternative, easier way
1. Download a plugin that defines a new planet
2. Land on it
3. Close the game and delete the plugin (or move it out of the endless-sky directory)
4. Reopen ES and close the game without doing anything
5. Reinstall the plugin and reopen ES
6. See how you are on New Boston even if the planet you were on exists now.

**Expected behavior**
The game does not take you to New Boston on game load, but when you actually enter in the pilot.

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github
 - Version: The relevant part is observed on 0.9.12

**Comment by ThrosturX** [comment]
After taking a quick look at the source code, it seems to me that the player is loaded immediately after launch, I haven't quite been able to put my finger on it after such a quick look, but it seem that gamePanels.CanSave() is returning true at the end of GameLoop despite no "in-game" actions having been performed.

**Comment by Amazinite** [comment]
Given that this is related to when to save and not save the game, I'll mention #3746 here.

**Comment by ThrosturX** [comment]
I've tried to reproduce this without success. I downloaded the Enigma Corp plugin, changed my pilot file to move me and my ship to "The Hub" in the "Domov" system and saved it. Then I deleted the plug in, started the game (looks like I'm on New Boston as expected), closed the game, reinstalled the plugin and opened the game again, entered the game and I was still at The Hub.

**Comment by beccabunny** [comment]
Looks like I was wrong, I tested it as well that way and everything works fine. Fair enough for me
