### ISSUE TITLE
No way to choose the current planet as the destination

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#523]
I want to create a mission that is offered on random planets and involves doing something and then returning to that same planet. There doesn't seem to be any way to do this.

<origin> works as a text replacement, but not as a destination.

**Comment by endless-sky** [comment]
If you don't specify a destination, it will be the same as the starting planet. See the code I posted in #407 for an example that will work in 0.8.10 or in the current GitHub code.

Bounty hunting missions are another example of this.

**Comment by Pointedstick** [comment]
Ah, perfect!
