### ISSUE TITLE
Typo in Pincian's description

### ISSUE THREAD

**Issue by roadrunner56** [endless-sky/endless-sky#5237]
**Describe the bug**
When landing on Pincian, the description reads, `Nevertheless, its surface is is pockmarked...`. There is an unnecessary 'is' in the sentence. 
**To Reproduce**

1. Land on Pincian
2. Read description
3. Find typo

**Expected behaviour**
The sentence should read `Nevertheless, its surface is pockmarked...`
**System**
OS: Kubuntu 20.04
Game Source: Continuous Appimage
Version: Commit hash #5235

**Comment by roadrunner56** [comment]
Thanks for making the commit!

**Comment by roadrunner56** [comment]
Should I close this issue once it's merged, or should I close it now?

**Comment by MCOfficer** [comment]
it'll be closed with the PR.
