### ISSUE TITLE
NPCs that have passed their despawn conditions but have yet to despawn won't trigger objective complete conversations/dialogs

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5247]
**Describe the bug / To Reproduce**
Take the following NPC.
```
npc kill
	to despawn
		has "some condition"
	...
	(conversation | dialog)
		`	"You've killed the <npc>."`
```
If the despawn conditions have passed but the NPC has yet to be despawned (i.e. the player has yet to land after the `to despawn` conditions have been met), then killing the NPC will not trigger the conversation or dialog.

**Expected behavior**
The conversation or dialog of an NPC should always trigger once its objective (e.g. kill, disable, scan, board, assist) has been passed while the NPC is still active (i.e. has been spawned or has yet to despawn).

**Screenshots**
N/A

**System:**
 - Version: Latest commit (c30080a).

**Link to save file**
N/A

**Additional context**
This section of NPC.cpp is the culprit. NPC::HasSucceeded will return true if the NPC's despawn conditions have passed without checking the objectives of the NPC. This means that when the objective does pass, even though it is being ignored for the sake of the mission, the conversation or dialog that would normally pop up does not. 
```C++
void NPC::Do(const ShipEvent &event, PlayerInfo &player, UI *ui, bool isVisible)
{
    ...
    // Check if this NPC is already in the succeeded state.
    bool hasSucceeded = HasSucceeded(player.GetSystem());
    bool hasFailed = HasFailed();
    ...
    // Check if the success status has changed. If so, display a message.
    if(HasFailed() && !hasFailed && isVisible)
        Messages::Add("Mission failed.");
    else if(ui && HasSucceeded(player.GetSystem()) && !hasSucceeded)
    {
        // If "completing" this NPC displays a conversation, reference
        // it, to allow the completing event's target to be destroyed.
        if(!conversation.IsEmpty())
            ui->Push(new ConversationPanel(player, conversation, nullptr, ship));
        else if(!dialogText.empty())
            ui->Push(new Dialog(dialogText));
    }
}
```
Solutions that I can think of:
* Allow npc conversations to trigger regardless of the state of the despawn flag. This would require splitting HasSucceeded into two functions. I imagine a function named HasSucceeded would remain that is the exact same as the function right now, but there'd be a new function named SucceededObjectives that only checks the objectives without checking the spawn/despawn conditions. This function would be called by HasSucceeded and replace HasSucceeded in this instance in order for the conversation to show up.
* Only update the despawn flag of NPCs on landing. NPCs only truly despawn once the player has landed, even if the despawn conditions have passed prior to that. This means that the HasSucceeded will only return true if the objectives have actually been completed, allowing the conversation to show. The downside with this though is that the player's conditions could change in flight to cause the despawn conditions to pass, but then change again so that they no longer pass. While currently this causes the NPC to despawn on landing still, it wouldn't if this change was made. The despawn flag is also updated in flight so that the mission marker properly updates to show when the mission can be completed.

**Comment by tehhowch** [comment]
Question: what's the desired behavior of an NPC that will despawn on your next landing, with regards to mission failure?

i.e. if it is `npc save`, and you destroy it after the despawn conditions have evaluated to true, should the mission be failed? (The NPC existed and you destroyed it)
Or, should we ignore it? (The NPC won't exist, so it doesn't matter that you destroyed it)

**Comment by Amazinite** [comment]
From the perspective of using `to (spawn | despawn)` as a way to create alternative objectives, I'd expect `npc save` to be ignored in this scenario. Should a content creator not want it to be ignored, then I think #5248 could be used; have an `on loss` block that fails the mission should the `npc` fail a `save` objective, regardless of the state of the despawn conditions.
