### ISSUE TITLE
Need text replacement for number of passengers (just the number)

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#525]
For cargo, the text replacement <tons> gives you the integer value of the number of tons of cargo carried. But there's no equivalent for the integer value for the number of passengers carried. This makes it impossible to write a passenger mission that refers to your number of passengers by a word other than "passengers"; you have to use the <fare> placeholder to get the number, which includes the word "passengers" in it.

**Comment by endless-sky** [comment]
The `<bunks>` value does what you want. For example:

```
description "This family of <bunks> miners is hoping to find work on <destination>, and they will pay you <payment> to take them there."
```

**Comment by Pointedstick** [comment]
Why can't I ever find these things on my own!?
