### ISSUE TITLE
Let waypoints be random, just like stopovers

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#526]
The docs indicate that waypoints have to be static and hardcoded in the mission description. I'd like to be able to specify random waypoints in much the same was as stopovers. For example, something like this:

> waypoint
>     attributes uninhabited

That would choose a random uninhabited system

> waypoint
>     attributes north

And that would choose a random system in the galactic north

etc.

**Comment by endless-sky** [comment]
At the moment, systems do not have attributes, so this would require adding support for attribute tags on systems, and going through every system in the map and adding those attributes in.

**Comment by Pointedstick** [comment]
It seems like systems could simply inherit attributes from a union of all of the attributes of populated planets in the system, or else just have "uninhabited", plus "weird phenomena" if the system has a wormhole or supernova-ing star or something in it.

**Comment by endless-sky** [comment]
In commit d24fd18 I've added support for random waypoints based on location filters, but I'll still need to think about the best way to allow systems to have searchable "attributes" of their own.

**Comment by tehhowch** [comment]
I support @Pointedstick 's idea of the system inheriting attributes from its contained planets, plus whatever attributes it might have on its own.
To begin with, perhaps only the "automatic" attributes are supported - those from the planets, plus "galactic phenomena" if it contains a wormhole or a specific star type.
As it is, I'm not sure what other attributes would exist or need specifying.

**Comment by Amazinite** [comment]
The only attributes I can think of needing are the government, region, inhabited/uninhabited status, and galactic phenomena as mention above. Or at the very least that would be the baseline for generic attributes that I would expect each system to have.

There may always be special missions though which require a certain system attribute though. Say, for example. "visit these X system, which all contain a gas giant," or some other planet type (ocean, lava, forest, rocky, ice giant, etc), or "visit these X systems which all have Y amount of planets," or possibly even "visit this system with X amount of asteroids (minable, nonminable, or both)." In relation to something that @tehhowch is working on if I'm recalling correctly, a system's fleet activity could even be an attribute of interest.

**Comment by tehhowch** [comment]
i could update #3140 to include pulling attributes from planets into the source system, but i'll open a new pull for that since 3140 is "done" and there are probably a few things to discuss on system attributes that i'd rather not condition 3140 with

**Comment by tehhowch** [comment]
#3144 adds automatic system attribute generation, including sensible planet-system attribute pooling in LocationFilter. I feel it resolves this issue in full.

**Comment by endless-sky** [comment]
Addressed in e1c1a55.
