### ISSUE TITLE
Gunboat on Hope should join Oathkeepers

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#5264]
## Summary

In the FW mission where the player installs radar equipment on Hope and spots a Gunboat doing the same, if the player spares the Gunboat crew, add some dialog that implies the player gets them to join the Oathkeepers, as with the Navy prisoners from the Kornephoros battle a few missions earlier.  This is just to add flavor to the story.

I also took the opportunity to make the pilot's name known to the Navy in-universe (and not just through Navy Intelligence), to help establish the "claim to fame" that justifies the player getting recognized by name in random spaceport side missions.

### Open questions

I think dialog should actually refer to the player's ship as the `F.S. <ship>` at this point, but I didn't make it so because that would probably be inconsistent with uses of `<ship>` in other FW missions.

The dialog doesn't actually use the term "Oathkeepers" since I think it's possible for this mission to take place before the `oathkeepers founded` event. (Actually, if the player does play this mission before the `oathkeepers founded` timer fires, the dialog of the latter could refer back to the dialogs proposed here.)

Gameplay wise, the only outcome of the mission that results in the Gunboat crew being spared (by the player's choice) also lets the crew keep their ship. It might be nice to have a variant where their surrender is accepted but the player destroys the Gunboat itself, brings the captives back to FW territory, and gets scolded by Alondo (and no `karma ++` of course) or praised by Tomek... but this is beyond the scope of this issue. (It would be a perfect use-case for a Brig, though!)

### Options for the choice

The dialog choice leading to this path is currently phrased [`Spare the crew, and chase their ship out of this system`](https://github.com/endless-sky/endless-sky/blob/82487024212a7a1f93fad982048a933fe6d83631/data/human/free%20worlds%20start.txt#L602-L608). With options 2 through 4, "chase their ship" doesn't really work, so the choice could be shortened to `Spare the crew` or changed to `Accept the crew's surrender` (without the "chase" part).

### Options for the dialog

First of all, [the current text](https://github.com/endless-sky/endless-sky/blob/82487024212a7a1f93fad982048a933fe6d83631/data/human/free%20worlds%20start.txt#L619-L623):

:one:

> Most ships are equipped with external speakers for exactly this sort of situation. Speaking through them, you tell the Navy crew below, "Return to your ship and leave this system immediately." They beat a hasty retreat and fire up their engines. You follow their ship into orbit to make sure it truly does leave the system...

:two:

> Most ships are equipped with external speakers for exactly this sort of situation.
> 
> "This is Captain &lt;last&gt; of the &lt;ship&gt;," you announce. "Return to your ship, leave this system immediately, and take no further part in fighting the Free Worlds."
> 
> As you expected, the Navy sailors are happy to accept the terms of surrender. They thank you in hand signals, walk back to their ship, fire up their engines, and take off.
> 
> The Gunboat's weapon systems remain unarmed and inactive, as far as your sensors can tell.
> 
> Your mission on this planet done, you take off too, keeping an eye on the Navy ship. Their captain gave you their word of honor that they would leave this system...

:three:

> Most ships are equipped with external speakers for exactly this sort of situation.
> 
> "Crew of the R.N.S. Susquehanna, this is Captain &lt;last&gt; of the &lt;ship&gt;," you announce. "I accept your surrender. You may return to your ship, leave this system immediately, and take no further part in fighting the Free Worlds."
> 
> As you expected, the Navy sailors are happy to accept these terms. They thank you in hand signals, walk back to their ship, fire up their engines, and take off.
> 
> The Gunboat's weapon systems remain unarmed and inactive, as far as your sensors can tell.
> 
> Your mission on this planet done, you take off too, keeping an eye on the Navy ship. Their captain gave you their word of honor that they would leave this system...

:four:

> Most ships are equipped with external speakers for exactly this sort of situation.
> 
> "Crew of the R.N.S. Susquehanna, this is Captain &lt;last&gt; of the &lt;ship&gt;," you announce. "Will you each give me your word of honor that you will take no further part in fighting the Free Worlds?"
> 
> The Gunboat captain immediately gives you a thumbs-up sign, and the crew follows suit promptly and without any visible hesitation.
> 
> "Thank you," you reply. "You may return to your ship and fly back to Republic space."
> 
> The Navy sailors exchange looks, apparently surprised, but they recover quickly. Their captain salutes you. You return the salute, and then, realizing their captain can't see you, flash the &lt;ship&gt;'s external signal beacon in acknowledgement. The R.N.S. Susquehanna's crew, by now standing at attention, march back to their ship, fire up their engines, and take off.
> 
> Their weapon systems remain unarmed and inactive, as far as your sensors can tell.
> 
> Your mission on this planet done, you take off too, monitoring the Navy ship. They gave you their word of honor that they would leave this system...

I'm not sure whether I like the "realizing the captain can't see you" bit. It might be better to shorten that to just, the Gunboat captain salutes, the player acknowledges the salute with the signal beacon.

**Comment by Amazinite** [comment]
#6451
