### ISSUE TITLE
Issue related to New Species: The Sleepers PR

### ISSUE THREAD

**Issue by AnxiousArchon** [endless-sky/endless-sky#5267]
**Is your feature request related to a problem? Please describe.**
This issue is related to a PR I posted recently and should be linked. From the PR: "Adds three new systems and a new species called the Sleepers (roughly tier 2.5ish) to the east of Korath Automata space with a couple of ships and a set of outfits... I have written a short series of missions which establish communications with the species and explains their backstory a bit."

There are several issues with the proposed content:
1) The images for the ships and their thumbnails are not good at all. They are funtional, but could use some attention from somebody experienced with ship creation.
2) The dialog in the missions introduced with this content is choppy. I wanted to get the flavor/backstory of this species across as concisely as possible. The motivation for the behaviour of the introduced species is based on a lot of real physics, and I perhaps gave that more attention than the flow of the dialog.
3) The content is locked behind both the completion of the main storyline and completion of Act 2 of the Wanderers campaign. The systems themselves are placed at the beginning of the first mission in the proposed content, so this may present issues if the player wants to explore east of the proposed space (nothing at this time, but possibly in the future) but hasn't completed the mentioned mission chains.
4) When jumping around in the added systems the dots representing systems in the little map in the top center of the screen (I don't know what the thing is called in game or in the source code, lol. Please see the Additional Context section for a picture) are not present. I suspect this has to do with the fact that the position of the systems in question are moved from their original location in data/map.txt due to an event, but I'm not sure.
5) The images for the outfits could be better. They are better than the ship images, but I'm still learning how to use Blender and GIMP. If they are deemed not good enough to be implemented into the game, they will need some attention.
6) I have not added any new sounds. I just ripped off the already existing sounds for the added outfits. This is less than ideal.
7) Since the content is locked behind Act 2 of the Wanderers campaign, it assumes Ektasi Rek is on Desi Seledrak and the Kor Mereti are friendly to the player. Of course depending on how Act 3 goes, this may not be the case.

**Related Issue Links**
I don't think this content has been approached before. Forgive me if someone has already had this same idea and it's already been implemented or shot down.

**Describe the solution you'd like**
1) I have placed the Blender and GIMP files for the added ships in a repo (https://github.com/AnxiousArchon/ES_sleeper_blend). Anyone who is up to it could use these as a base for the final ship design. I'm not terribly attached to the ship layouts there, so if you have a brilliant idea that comforms to the species' style, go for it I guess.
2) I'd like the background/flavor/psychology of the added species to stay the same. I tried to used some (loosely) real physics to motivate their pathological desire for efficiency, and their isolationist tendency. I think it adds to things, so I'd like it to stay, but I recognize the dialog isn't great. Please feel free to edit to bring it up to the quality that is needed for implementation into the game.
3) This issue might be a problem or it might not be. It may be desireable to have this content as a bottleneck to the (as of now empty) north eastern part of the galaxy.
4) Honestly don't know on this one, because I'm not sure what exactly is causing the issue.
5) Same as 1).
6) If someone likes making sounds for outfits, there are a decent number here that need attention.
7) This issue might be a problem or it might not be. It depends on how Act 3 of the Wanderers storyline is written.

**Describe alternatives you've considered**
3) Instead of hiding the new systems and placing them when the first mission triggers, the systems could be placed there but remain uninhabited until the first added mission. This may also fix 4). In my mind this is not as good as hiding the systems, because one would have to justify why the aliens were not encountered in potential previous visits to the systems.
7) Instead of establishing a means of communication by consulting Ektasi Rek and getting help from the Kor Mereti, another way could be written into the mission chain. This would avoid the potential for causing problems with the future Act 3 of the Wanderers storyline.

**Additional context**
![context](https://user-images.githubusercontent.com/67398152/91666006-feab7200-eacf-11ea-8df0-098cc5ca753d.png)

**Comment by Zitchas** [comment]
Linking to the related PR: #5266

**Comment by Zitchas** [comment]
Another suggestion: Generally speaking, it is preferred to have content submitted in PRs be close to merge-ready state. We all know this isn't always the case, but it is recommendable to discuss your content and recruit people to help work on it on discord (the Endless Sky discord has a dedicated content-creation channel), and then people can provide help, advice, and feedback there. GitHub tends to be a poor environment for discussions, given that it is a very code-centric thing.
