### ISSUE TITLE
Editing a saved mortgage's term to 0 causes a floating point exception on startup

### ISSUE THREAD

**Issue by Red-57** [endless-sky/endless-sky#5268]
**Describe the bug**
I downloaded endless sky from github using this link https://github.com/endless-sky/endless-sky/releases/download/v0.9.12/endless-sky-macos-0.9.12.dmg but when I opened the game it automatically crashed. this may be a problem with my operating system (Mac OS 10.15.6 Catalina). I also tried to compile the code from scource but when I opened it using xcode the program glitched and wouldn't load, xcode then told me that it couldn't find a pointer to the open routine.

**To Reproduce**
(it may not be able to be reproduced)
1. Download Mac OS 10.15.6 Catalina
2. Download Endless sky for mac (version 9.12)
3. open the game

alternativly
2. Compile endless sky from scource
3. Run in xcode

**Expected behavior**
in theory the game should not crash on opening and it should be able to load

**System:**
 - OS: Mac OS 10.15.6 Catalina
 - Game Source: Github or self compiled
 - Version: 9.12

**Comment by MCOfficer** [comment]
Can you supply us with a crashlog, diagnostics or similar of some sort? Also, does the [Continuous build](https://github.com/endless-sky/endless-sky/releases/tag/continuous) crash for you, too?

**Comment by Red-57** [comment]
I tried the Continuous build but that crashed too. here is the crashlog 


[crash report.pdf](https://github.com/endless-sky/endless-sky/files/5152538/crash.report.pdf)

**Comment by jostephd** [comment]
It's a division by zero here:

https://github.com/endless-sky/endless-sky/blob/76dc1a9f7d6c490718047daf43ae8fd1450e9815/source/Mortgage.cpp#L168-L177

Not sure which of the two divisions it is, though.

Could you post the most recently modified file in your saves directory?

**Comment by Red-57** [comment]
this is the only file in my saves directory.
[test  dummy.txt](https://github.com/endless-sky/endless-sky/files/5162187/test.dummy.txt)

**Comment by Red-57** [comment]
So I realized that if i delete my save file and start a new pilot then it works fine. I edited my save file and for some reason after that endless sky wouldn't open again, so something in the way that I edited the file must have caused the error.

**Comment by Red-57** [comment]
to reproduce the error you have to put the term of your loan at zero.

**Comment by tehhowch** [comment]
Save editing is the fastest and most reliable way to cause bugs.
