### ISSUE TITLE
Tried to build and run in blocks, followed every instruction, failed with 50 errors

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#527]

**Comment by Pointedstick** [comment]
This really isn't the right venue for these kinds of things. It's not the game's fault you need to adjust some things with your setup to compile it. A forum would be a better place to discuss this.

**Comment by thenerdfreak** [comment]
what do you mean need to adjust some things? I adjusted everything, i had to specifically nitpick every .exe and g++ and c++ because they were all named lasdkjflasjdflasjflasdkfjlsdjfsadlfmingin32++ crap instead of the simple name in Blocks

**Comment by thenerdfreak** [comment]
ah just forget it, if I don't understand it from looking up 3 20 minute tutorials i just won't understand it
