### ISSUE TITLE
Archon - Possible Ship description

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5273]
**Is your feature request related to a problem? Please describe.**

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. If you're proposing new UI features, creating a mock-up can really go a long way in conveying your intent.

**Comment by Zitchas** [comment]
While your issue is a touch sparse on details, I am guessing that this issue is flagging the fact that the Archon doesn't have a description?

**Comment by McloughlinGuy** [comment]
> 
> 
> While your issue is a touch sparse on details, I am guessing that this issue is flagging the fact that the Archon doesn't have a description?

Yes that is the issue. Although it isn't that much of a problem, seeing as you most likely won't ever see the Archon in a shipyard.

**Comment by Zitchas** [comment]
That is true - the player should normally never see an Archon in a shipyard. That being said, plenty of people use "All-content" plug-ins of various sorts, and we are attempting to 'normalize' the shipyard and outfitter by ensuring that all ships have thumbnails and descriptions, even if they aren't likely to be seen in normal gameplay.

**Comment by Zitchas** [comment]
As a side note, I created a fix for this issue. If you haven't already, I'd request that you take a look at it and see if it fixes the problem you reported. (If it does, leaving an "approve" review would be the appropriate thing to do. If not, feedback and comments would be appreciated)

(You can review changes by going to the Pull Request by following the link, then click on the green "changed files" button on the upper right hand side. Then after reviewing the changes, click on the green "review" button and pick the appropriate option.)
