### ISSUE TITLE
Aliens in Spaceport

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5276]
I noticed that only humans ever appear when clicking the spaceport button. If you're on a Hai world, shouldn't you be able to talk to Hai as well as humans? Shouldn't you be able to talk to Quarg on Quarg worlds, Wanderers on Wander worlds, and Helriach on Helriach worlds, Korath on Korath worlds, and Remnant on Remnant worlds? I am basically suggesting that people should write some quotes for the alien species, and draw some art for the alien species., so you could talk to all kinds of species at the spaceport. (I'm not including the Pug because it seems like the Pug think they have better things to do than talk with you.)

**Comment by Zitchas** [comment]
In theory, yes. However, we have been unable to agree on 
a) whether we even want visuals for the aliens, and if so, 
b) what exactly they look like.

Right now, the continuous build (which is the future 0.9.13) actually has all the portraits removed from the news, as many of us found them irrelevant at best, distracting at worst. Personally, my imagination gives a better visual for what the aliens look like than we are likely to get from any artist.

On the other hand, we have added a whole bunch of news items, including a bunch of Remnant ones. They'll just display without pictures. 

(worth noting: the Remnant *are* human. Or at least claim to be)
