### ISSUE TITLE
Corprate Espionage Missions Not Working

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5277]
I tried doing a corporate espionage mission, and traveled the system that it said the ship I was supposed to scan would be in. I waited around for like 10 minutes and the ship never came. I looked it up and apparently some other people are having a problem: https://steamcommunity.com/app/404410/discussions/0/1291817837616756355/
Could you guys fix this?

**Comment by Zitchas** [comment]
A few questions for you:
What OS are you on?
What version of ES are you running?
Does this happen if you do the mission again?
Are you using any plug-ins?
Could you upload your pilot file so we can look at data?

**Comment by tehhowch** [comment]
Fill out the templates.

Duplicate of #3179
