### ISSUE TITLE
Pug Arecta Class Change

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5278]
**Is your feature request related to a problem? Please describe.**
The pug Arfecta is classified as a medium warship, even though it is larger than every other medium warship in the game and even bigger than some heavy warships.

**Describe the solution you'd like**
I would like the Pug Arfecta to be changed to a Heavy Warship.

**Additional context**
Look at the picture of the Vanguard next to the Arfecta and you will notice
 that the Arfecta is clearly larger
![pug arfecta](https://user-images.githubusercontent.com/70719891/92184901-62ab9e80-ee20-11ea-97d2-074c88aaa00d.png)
![image](https://user-images.githubusercontent.com/70719891/92184916-6dfeca00-ee20-11ea-9b91-6077f88b606f.png)

**Comment by tehhowch** [comment]
You'd have to know what tier the Pug are to accurately classify any of their ships.

**Comment by Zitchas** [comment]
The classification of a ship as "Heavy/Medium/Light warship" depends on a combination of factors, only one of which is actual size. The relative power level, where it sits on its particular race's set of ships, and relative weaponry all count as well. (as far as we know, this might be a medium warship for a high level Pug)
