### ISSUE TITLE
Quarg Hails

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5281]
**Is your feature request related to a problem? Please describe.**
Whenever I hail the Quarg, they don't say anything, unless I attack them. And when they are disabled they say the same things they said when I started attacking them.

**Describe the solution you'd like**
I would like it if the Quarg could get a few lines they could cycle through when you hail them.

**Comment by Zitchas** [comment]
Thanks for the feedback. As far as Hails go, the Quarg (and many of the alien races) are not as fully developed as mainstream humanity, and thus they don't have the full set of hails, spaceport news, and other details that help to flesh them out into a complete faction.

**Comment by Amazinite** [comment]
This is intentional. https://github.com/endless-sky/endless-sky/pull/2201#issuecomment-299598039
