### ISSUE TITLE
Spaceport Assassin

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5282]
**Is your feature request related to a problem? Please describe.**
I noticed that in some missions you are told to watch out for assassins at the spaceport, yet you never encounter one. 

**Describe the solution you'd like**
I think it would be interesting if you had a random chance (after completing certain missions or gaining a high enough combat rating) to encounter someone in the spaceport who pulls there gun on you, like Katya does in the beginning of the Free Worlds. 

**Additional context**
Through digging through text files, I noticed there is an illegal transport mission where your passengers will turn on you and try to take your ship. I thought if the developers added something like that, maybe they could add something like this, to make the spaceport a little more interesting.

**Comment by Zitchas** [comment]
Good idea. That being said, this is a community driven game where all the new content is being done by members of the community. Why not try your  hand at writing a mission where <first> has a run-in with an assassin? Could make for an interesting bit of flavor for the mid-game when the player is starting to be chased by bounty hunters.

**Comment by McloughlinGuy** [comment]
I wrote the text that will appear, but not the programming, you'll have to do that since I'm not a good programmer. I hope you like it, understand this is my first attempt at writing something for a game, I hope its not bad.

    Wandering through the spaceport, you take a moment to look at the recent news when suddenly you hear the click of a gun being cocked. You turn around only to be greeted with the sight of an assassin aiming a gun straight at your head.

(Shoot first, 50/50 chance of living.)
Surviving: You somehow manage to get your gun before he can paint the wall with your organs. You quickly aim it at his head and pull the trigger. You breathe a sigh of relief as he collapses, and you return to your ship.
Dieing: You make a grab for your gun, but you are interrupted by the noise of his firing. You die.

(Bribe him) “I’ll pay you. Just please don’t kill me!” You say. You hand him a credit chip worth 1 million credits, and return to your ship poorer, but still alive.

(Bribe him not enough money.) You attempt to bribe him, but the amount you offer does not peak his interest. He fires his gun. You die.

**Comment by Zitchas** [comment]
While I appreciate the text, I've got a lot of projects on the go write now. (literally dozens of missions already prepped to write, and a bunch of other stuff to). If you'd like to see this make it into ES, I would recommend taking a look at the wiki and learning how to create a plug-in that adds this mission:

https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions
https://github.com/endless-sky/endless-sky/wiki/WritingConversations

Those three pages should have everything you need to create this mission. Once you have a plug-in working you can share it on the Discord to get some feedback (or help to get it working). If the community likes it, then it could get merged into the game.
