### ISSUE TITLE
New Descriptions For Tier 1 Pug Ships

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5284]
**Is your feature request related to a problem? Please describe.**
The pug tier one warships, Zibruka, Enfolta and Maboro all have very bland desciptions. I think that they deserve better than a short, one sentence description. After all, you can capture them in game.

**Describe the solution you'd like**
I would like new descriptions for these three ships.

**Describe alternatives you've considered**
An alternative is to leave it as it is, but I don't think "This is the smallest/medium/largest pug warship is gonna cut it.

**Comment by Amazinite** [comment]
> After all, you can capture them in game.

But you can't see their descriptions.

**Comment by McloughlinGuy** [comment]
> > After all, you can capture them in game.
> 
> But you can't see their descriptions. #2433

Well, maybe in the future you’ll be able to buy pug ships, maybe as a reward for helping the wanderers, a little thank you from the pug. If that is the case, then maybe then the description should be updates.

**Comment by RicCakes** [comment]
> > > After all, you can capture them in game.
> > 
> > 
> > But you can't see their descriptions. #2433
> 
> Well, maybe in the future you’ll be able to buy pug ships, maybe as a reward for helping the wanderers, a little thank you from the pug. If that is the case, then maybe then the description should be updated. Also, the Arfecta has a good description and it’s near impossible to capture.

Even then, they're pretty much as secretive as the Quarg do. I don't think "they" would allow the Wanderers Pug to give a special human (that the Wanderers Pug just so happen to encounter on their project) access to their technology, albeit the Tier 1 ones.

If they do, then it has to be some galaxy changing reason. I don't think they do these stuff for entertainment. And seeing they're not hostile against the Drak and the Quarg yet, there's no real possible reason for them to allow a human access to their tech.

They must've done this "Heal worlds" thing and encountered a lot of species meddling with their project or whatever, and surely they didn't award them just for helping the Wanderers.

If anything, a reward from the Wanderers directly would be better, and they're already rewarding you with the ugly weapons of war they recovered from their archives... maybe a salary too, to help with crew management.
