### ISSUE TITLE
Disabled Pug Hails

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5285]
**Is your feature request related to a problem? Please describe.**
I noticed that hostile pug say the same things when they are disabled as when they aren't disabled.

**Describe the solution you'd like**
I would like hostile disabled pug to get some unique lines.

**Comment by Amazinite** [comment]
Same deal with the Quarg hostile/hostile disabled hails. Part of this was me being lazy: #4553
> In some instances (Pug, Quarg), the hostile hails and hostile disabled hails are the same. I did this because I felt that the hostile hails fit good enough to also be hostile disabled hails.
