### ISSUE TITLE
Ship Description View

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5289]
**Is your feature request related to a problem? Please describe.**
I noticed that Marauder ships have there own unique descriptions, but you can’t view them in game.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github)
https://github.com/endless-sky/endless-sky/issues/2433

**Describe the solution you'd like**
I would like it so that a ship you own will appear in the shipyard with the caption “not sold here” (like with the outfitter)

**Describe alternatives you've considered**
An alternative is to make it so you can read the ships description by hovering over it with your mouse while in the shipyard.

**Additional context**
What I’m trying to say is so many ships, like the Marauder ships, Pug Arfectas ect. Have such great descriptions, and we shouldn’t let them go to waste.

**Comment by Amazinite** [comment]
You just referenced the issue that you duplicated.
