### ISSUE TITLE
New personality like "waiting", but follows you immediately

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#529]
I'd like an NPC ship personality that starts following you irrespective of which system it starts out in or even if you've ever seen it before. Wherever the ship spawns, it immediately knows where you are and follows you. This could be used to inject some more variety into escort missions, because you could have the pirates spawn in random places and come at you at any point in the mission rather than immediately blipping into existence as soon as you take off from the source planet, which drains all the excitement from the mission because you know you'll be safe after you've killed them.

Does "escort" already do this, even if applied to hostile ships? I couldn't tell from the docs.

**Comment by endless-sky** [comment]
Any NPC that is not "staying" will already do this. If you look at some of the battles in the main story line, that's how I space out the different fleets that arrive to join the battle - by making some of them be several systems away.

The "escort" personality is only to mark the ship as one that should be shown in your escorts list.

**Comment by Pointedstick** [comment]
Ah, I see.
