### ISSUE TITLE
Second Galaxy Pug

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5290]
**Is your feature request related to a problem? Please describe.**
At the end of the free worlds storyline, the Pug flee through a wormhole in Deneb. But I noticed that when you travel through the wormhole into the second galaxy, there are no Pug to be seen.

**Describe the solution you'd like**
I would like a Pug world to appear in the second galaxy. I think it would really make the game a lot more interesting.

**Describe alternatives you've considered**
Maybe if not the Pug, some other aliens species, or maybe even some humans that traveled through the wormhole and begun building a colony when the pug opened it.

**Additional context**
What I’m really saying is that we need to make the second galaxy more interesting.

**Comment by Arachi-Lover** [comment]
Pleiades' purpose is the Pug showing to the player "look what we can *really* do", it's not one to be populated as far as I'm aware

**Comment by LordInsane** [comment]
At least in game the purpose of the wormhole to the Pug Galaxy/Pleiades is ambiguous given the Pug aren't there to say why, but the Pug showing what they can do if they really want is a very plausible interpretation, and though the galaxy might be a bit boring, there's still the Milky Way to fill out before dropping new aliens there, and the Pug from Deneb should *not* be there within the context of current storylines (relevant dialogue here is in Wanderers: Pug Assistance 2, where the Captain can indicate that the Pug (that were) in human space have left so there's no way to bother them, eg. that insofar as the player character is aware where the Pug from Deneb went can not be known at that point in time).

**Comment by Amazinite** [comment]
I'd say almost all of the issues you've been posting are better suited for the Discord server. https://discord.gg/ZeuASSx
