### ISSUE TITLE
Default Hail Key Change

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5293]
**Is your feature request related to a problem? Please describe.**
I think the default hail key should be changed, because when hailing a planet it’s really easy to accidentally demand tribute, seeing as the tribute key and hail key are the same.

**Describe the solution you'd like**
I would like the default hail key to be changed to H

**Describe alternatives you've considered**
An alternative is to change the tribute key, but T for tribute and H for hail works better.

**Additional context**
I’ve died a few times by accidentally demanding tribute, so I made this issue.

**Comment by tehhowch** [comment]
I would rather reassign the tribute shortcut than make pressing T (to "talk") not open the hail screen.

**Comment by McloughlinGuy** [comment]
Okay, whatever works for you. Maybe the tribute key could be D, like demand?

**Comment by Ririshi** [comment]
You wouldn't deploy fighters after pressing T to hail a planet though, would you? D seems like a good idea as you're **D**emanding tribute

**Comment by McloughlinGuy** [comment]
D for Demand works, because you won't deploy your fighters if you press D while hailing a planet. It does close the textbox, but I'm sure that can be fixed. This way it won't happen by accident often, and if it does you will know not to press D while hailing a planet, where when you used T it would happen if you just held it down for too long.

**Comment by petervdmeer** [comment]
If you have demanded tribute in the past, then you have the option to "Relinquish Tribute" in the hail screen. That doesn't seem to match very nicely with the D key.

**Comment by McloughlinGuy** [comment]
You could use R to relinquish tribute

**Comment by warp-core** [comment]
#8875 added a confirmation dialog when demanding tribute.
Does that address this issue?
