### ISSUE TITLE
Bug: Person fleets do not act like fleets

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5294]
**Describe the bug**
When a person has multiple ships defined in order to create a fleet, they act like independent ships that just happen to be arriving roughly together. Sometimes they leave in different directions, and it is quite possible to hyperjump out after one of them and find a single ship from the fleet all by itself.

**To Reproduce**
1. Create a person that has multiple ships (ships with vastly different agility will magnify this)
2. Wait around in game until the person appears.
3. Note that the ships do not arrive altogether, nor do they hyperjump out together, or fly around together.

**Expected behavior**
I expect a person fleet to act like a normal fleet. That is to say, that all the ships cluster around the flagship, and that they arrive and depart with the flagship (no ship in the fleet should arrive before the flagship, nor should any ship in the fleet depart before the flagship). While in-system, the fleet should follow the flagship around.

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: self-compiled from latest nightly.
 - Version: nightly/continuous data as of 67e2c8e (2020-Sep-06)

**Comment by tehhowch** [comment]
Provide the example person definition with which you have an issue. (You can omit the hails)

**Comment by Zitchas** [comment]
```
person "Zitchas"
	government "Author"
	frequency 10000
	personality
		mining harvests unconstrained surveillance opportunistic staying
	system
		attributes "ember waste"
	phrase
		phrase
			"friendly author"
	phrase
		word
			"May the Embers burn bright for you."
			"I am ash in the storm - watch how I soar."
			"Through shadows of wind and fire - we shall prevail."
			"Have you ever watched the clouds drift in the skies of Nasqueron?"
			"Don't mind me - I'm just testing out some stuff."
			"Don't even try - I have the safeties disabled, so I'll go down fighting."
			"Don't worry - they are just prototypes."
	ship "Heron Prototype" "Shadow Wind"
		"never disabled"
	ship "Condor Prototype" "Condor Prototype"
		"never disabled"
	ship "Diomedea Prototype" "Diomedea Prototype"
		"never disabled"
	ship "Jaeger Prototype" "Jaeger Prototype"
		"never disabled"
	ship "Merganser Prototype" "Merganser Prototype"
		"never disabled"
	ship "Peregrine" "Peregrine Prototype"
		"never disabled"
	ship "Skua Prototype" "Skua Prototype"
		"never disabled"
	ship "Vulture Prototype" "Vulture Prototype"
		"never disabled"
```
(file contains the full version with hails)
[remnant persons.txt](https://github.com/endless-sky/endless-sky/files/5179885/remnant.persons.txt)

**Comment by tehhowch** [comment]
Note that the `surveillance` personality does not promote coordinated operations. Every ship with the tag is effectively a busybody and _has_ to scan you, personally, to consider you "ok" to ignore thereafter.

Does this issue persist after removing that personality trait?

**Comment by Zitchas** [comment]
Once I figure out how to compile with this new workspace stuff, I'll recompile my person tester build and re-test this, now that the surveillance has been removed.

**Comment by Amazinite** [comment]
@Zitchas Did you retest this?

**Comment by warp-core** [comment]
Closing because it's been a long time since this was updated and, as far as I can tell, these ships behave as a normal fleet with the same personality would.
