### ISSUE TITLE
Random spaceport quotes being said by the wrong person

### ISSUE THREAD

**Issue by monticore162** [endless-sky/endless-sky#5301]
essentially the random spaceport quotes that come up when you click on the "spaceport" button are being assigned to the wrong type of person.

I've never had this happen on the first click but if I keep clicking on the spaceport button I eventually get things like this:

> retiree: 
"The family I **work** for has an odd fascination with carnivorous plants. I have to keep rotting pile of refuse around just to produce enough flies to feed them all."

this quote is meant to go:

> groundskeeper:
"The family I work for has an odd fascination with carnivorous plants. I have to keep rotting pile of refuse around just to produce enough flies to feed them all."

![20200905130511_1](https://user-images.githubusercontent.com/70926019/92425079-862c6b80-f1c9-11ea-8a46-d685ac6a53ce.jpg)
![20200906211345_1](https://user-images.githubusercontent.com/70926019/92425081-888ec580-f1c9-11ea-8a68-38c7d3f69736.jpg)
![20200906211419_1](https://user-images.githubusercontent.com/70926019/92425084-8af11f80-f1c9-11ea-8b6b-86af51fc1350.jpg)
![20200906211441_1](https://user-images.githubusercontent.com/70926019/92425089-8d537980-f1c9-11ea-8f99-5af14a70a9fb.jpg)
![20200906211445_1](https://user-images.githubusercontent.com/70926019/92425092-904e6a00-f1c9-11ea-8352-149692ba7e45.jpg)
![20200906211448_1](https://user-images.githubusercontent.com/70926019/92425094-92b0c400-f1c9-11ea-8d0d-cee2df431349.jpg)
![20200906211454_1](https://user-images.githubusercontent.com/70926019/92425103-96dce180-f1c9-11ea-9e8f-3b997272d1a3.jpg)
![20200906211756_1](https://user-images.githubusercontent.com/70926019/92425113-9a706880-f1c9-11ea-9d0b-20961ea56d09.jpg)
![20200906211803_1](https://user-images.githubusercontent.com/70926019/92425118-9c3a2c00-f1c9-11ea-9e68-0e8c7645f453.jpg)
![20200906211817_1](https://user-images.githubusercontent.com/70926019/92425120-9e9c8600-f1c9-11ea-8c73-05a70ca6211d.jpg)
![20200906211821_1](https://user-images.githubusercontent.com/70926019/92425124-a52afd80-f1c9-11ea-80e1-043bf77c2a3e.jpg)
![20200906211824_1](https://user-images.githubusercontent.com/70926019/92425126-a6f4c100-f1c9-11ea-9670-3597041f5327.jpg)
![20200906211850_1](https://user-images.githubusercontent.com/70926019/92425129-a9571b00-f1c9-11ea-99ce-717af1a34f01.jpg)

**Comment by tehhowch** [comment]
Thanks for filling a report. Read and fill out the issue templates, please. This is an already reported and resolved issue.
