### ISSUE TITLE
Cloaking Device Arfecta Flaw

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5303]
**Is your feature request related to a problem? Please describe.**
Lets say two Arfectas fought each other. They would lower  eacho others health almost disable each other, cloak, and then repair.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that maybe the fuel consumption should be increased on certain ships like the arfecta, so they can't cloak forever

**Additional context**
 Through testing aided by modifying sales.txt and start.txt to give myself infinite money and access to every ship and outfit in existence, I gave myself an arfecta and fought another arfecta. Every time I lowered its health down to the point where it was almost disabled, it would cloak and repair itself. This is a major balance flaw seeing as people have been able to capture arfectas, and then use the arfectas to grind jump drives from the pug. If they were to fight the arfecta and lose there entire fleet except one ship and manage to capture it, if they fought had previously destroyed a wanderer arfecta but spared the other, the two would be locked in an endless combat unless the wanderers stepped in.

**Comment by tehhowch** [comment]
Arfectas are supposed to be able to cloak at will without cost.

**Comment by McloughlinGuy** [comment]
Okay, then this issue needs no more existence.
