### ISSUE TITLE
Make Turret Sprites show up on ship thumbnails

### ISSUE THREAD

**Issue by Red-57** [endless-sky/endless-sky#5308]
When viewing ships in the outfitter none of the turrets that may be installed show up on the sprite, it would be neat if they could. I know that this would take some large code changes and I have absolutely know idea how that might work.

One way to do it would be to have another command given after the turret placement on the ship, something like `thumbnail location` you would then have to create svg files of a different view and have some sort of scaling factor for the ship so that the turrets are scaled to the size of the ship, (this could be related to the size in pixels of the ship sprite)

Alternatively we could leave as is and that would be fine as this dose not present a pressing problem

![Tiger](https://user-images.githubusercontent.com/70019636/92663109-5ca93800-f2ce-11ea-96c1-49f58546a398.png)
this is one of my mod ships with two plasma turrets
![plasma location](https://user-images.githubusercontent.com/70019636/92663174-85c9c880-f2ce-11ea-86bd-b100db7b28ff.png)
here is the individual plasma turret image

**Comment by Terin** [comment]
The turret hardpoints would need to be translated from a 2d, top-down view to that isometric angle, for one. Probably not too difficult if a script were built for it. But more importantly, the perspective would be completely off. If a ship has turret hardpoints on the front and back, all we could currently do it place the same 2d turret thumbnail at those different spots, when they should be different sizes and even different angles.

It would look really cool, but outside of having the 3d models built into the game, it wouldn't be possible. Sorry.

**Comment by Red-57** [comment]
I am not a coder so I have no idea if what I am suggesting is possible but since the ship thumbnails are all rendered at a camera angle of 45 0 60 why not just render the turrets individually at that angle and convert it to an svg file, then the game engine could scale that file according to the scale of the ship (like 10% bigger if it is approx 250 pixels or something) that way it would be at the right angle and you could have it to scale to the ship.
