### ISSUE TITLE
Wrong text shown in Remnant: Cognizance 1

### ISSUE THREAD

**Issue by tatami4** [endless-sky/endless-sky#5309]
**Describe the bug**
In Remnant: Cognizance 1 the text that should be only shown when landed on the first of the gas giants is instead shown immediately after entering the system.

**To Reproduce**
1. Accept Remnant: Cognizance 1
2. Go to Nenia
3. Read the message that is shown

**Expected behavior**
This line
https://github.com/endless-sky/endless-sky/blob/390d6a044a7db541082757d95deb56e179569eee/data/remnant/remnant%20missions.txt#L2802
should be shown only once you land on the first gas giant, not when entering the system.

**System:**
 - OS: Manjaro
 - Game Source: nightly
 - Version: 390d6a0

**Comment by Zitchas** [comment]
Thanks for reporting this! I'll see about fixing it.

**Comment by Zitchas** [comment]
Currently poking at this. If a Dev looks at this, could you assign this and the other Remnant things to me please? (just to help me keep track of it)
