### ISSUE TITLE
Remnant: Cognizance 12 assumes that the player is using the Puffin

### ISSUE THREAD

**Issue by tatami4** [endless-sky/endless-sky#5310]
**Describe the bug**
In Remnant: Cognizance 12 the Puffin is mentioned several times without accounting for the fact that the player might be using the Penguin to visit the gas giants.

**To Reproduce**
Read this:
https://github.com/endless-sky/endless-sky/blob/390d6a044a7db541082757d95deb56e179569eee/data/remnant/remnant%20missions.txt#L3197
and this
https://github.com/endless-sky/endless-sky/blob/390d6a044a7db541082757d95deb56e179569eee/data/remnant/remnant%20missions.txt#L3205

**Expected behavior**
The text is phrased differently or there are different branches for the Penguin and the Puffin

**System:**
OS: Manjaro
Game Source: nightly
Version: 390d6a0

**Comment by Zitchas** [comment]
It is worth noting that you are given a set of puffins to do this mission, so puffins *will* be involved.

That being said, a branch to differentiate between penguin and puff for the second instance would be good. I'm not sure if we *have* the capability to differentiate between them yet, though.

**Comment by Amazinite** [comment]
Given that the Gascraft was renamed to the Puffin, perhaps we can use the term gascraft to refer to both the Penguin and the Puffin. That way it doesn't matter which ship you actually have.

**Comment by Zitchas** [comment]
Upon reflection, I am less convinced that this is a bug. I can pluralize the second paragraph so that it is clear that they are talking about the group of (predominantly puffins) rather than a singular puffin (which would likely be assumed to be the player's ship), but I don't see the absence of mentioning the penguin to be a problem.

> You arrive at the hidden station on <planet> where Gavriil is waiting to offload the atmospheric gases. His team quickly hooks the Puffins up to ports on the bay walls, and hidden equipment starts pumping its contents into the system. After a few minutes, they disconnect the ships, and you and the Puffins head up to the Pelican to refill your reservoirs and ferry it down to the station.
