### ISSUE TITLE
Vectoring thrust

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#5312]
**Is your feature request related to a problem? Please describe.**
Currently, the game has thrusting, which is just like the real life equivalent, and steering, which (while is not inertial) are basically RCS thrusters. There is also another way to steer in RL: vectoring thrust. This works by rotating the nozzle of a thruster to angle it in a way that, when the engine is turned on, also makes the ship steer to the wanted direction.

**Related Issue Links**
None that I know of.

**Describe the solution you'd like**
An attribute called "vectoring (or vectored) thrust", which works the same as steering but only when the ship is also thrusting forward. While this would mainly give a boost at steering when the ship is moving, it could be used alone to do all necessary movements, so if a ship has only thrust and vectoring thrust it would be still able to depart.

**Additional context**
A plane using vectoring thrust:
![image](https://user-images.githubusercontent.com/45330165/92868973-a2671d00-f402-11ea-918a-944a65c37100.png)
In reality, a rocket using vectoring thrust would have less thrust the moment they are rotating the noozle, but it really doesn't seem worth to add complications like this to the quite simplified ES physics

**Comment by Amazinite** [comment]
You can now add the "gimbal" attribute to flares to give them the appearance of vectored thrust as of #9017, but I'd prefer to not add more movement mechanics to the game. Not only do additional movement mechanics become a difficulty for the AI to handle, but I also don't feel that they actually add much to the game outside of being flashy alternatives to the norm.
