### ISSUE TITLE
Narrator

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5313]
**Is your feature request related to a problem? Please describe.**
I think that the game should have a narrator option, to read out loud the text to people.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I would like the game to add a narrator option, which allows you to not have to do any reading if you don't feel like it.

**Describe alternatives you've considered**
An alternative is for them to not be lazy.

**Additional context**
I think this would improve the experience of the game for lazy people or people who want to hear the character voices. There are plenty of people on discord who would be willing to volunteer.

**Comment by MCOfficer** [comment]
Several concerns:

- The effort of voicing all missions is enormous
- Whoever does it has to always be around to voice later missions, to not break continuity
- I'm not sure how many hours it would be, but a dozen hours of audio are quite large
- Something else which i forgot :x

**Comment by McloughlinGuy** [comment]
This would probably be something to tackle after the games initial release.
