### ISSUE TITLE
feature-request: Dropoff decays for other damage than hull and shields

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5314]
**Is your feature request related to a problem? Please describe.**
Issue #4703 adds a nice feature to allow weapon damage to decrease or increase over range.
I would like this mechanism to also be available for all other damage (like heat damage, hit force, ionisation, etc) on on an enemy ship.

**Related Issue Links**
#4730 is definitely related.

**Describe the solution you'd like**
A possible syntax (using the first two examples from #4703) to implement this:
```
outfit "Electron Beam"
	...
	weapon
		...
		"heat damage" <nr>
			"dropoff" 400 600
				"modifier" 1.25
		
outfit "Particle Cannon"
	...
	weapon
		...
		"hit force" <nr>
			"dropoff" 400 600
				"modifier" 1.25
```

**Describe alternatives you've considered**
The discussion in #4703 lists some alternatives, but I think this is the most balanced syntax.

**Additional context**
If we allow negative modifiers, then this could even be used to invert the hit force in the dropoff range.

**Comment by Amazinite** [comment]
#4703 affects the damage of *all* damage types for a weapon, not just shields and hull. Are you asking for each damage type of a weapon to be able to be scaled independently?
