### ISSUE TITLE
feature-request: Conditional firing costs/effects depending on hitting.

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5315]
**Is your feature request related to a problem? Please describe.**
When I fire a repulser/tractor beam like a Heliarch Attractor or Heliarch Repulsor, then it surprises me to see the "firing force" effect also happen when I miss the intended target (and when I fire with no target selected).
I would expect the firing force to only be applied when the beam actually hits an opponent.

**Related Issue Links**
Issue #5314

**Describe the solution you'd like**
I'm thinking of adding an attribute like "hit fraction" that indicates how much of the property is conditional on hitting a target.

The syntax could look like:
```
outfit "Heliarch Repulsor"
	...
	weapon
		...
		"firing force" 60
			"hit fraction" 1
```

**Describe alternatives you've considered**
- The damage scaling used in #5314 could be used to emulate this if "firing" properties are also scaled (by having very active dropoff at the edge of the range).
- I also considered if this can be used for "energy stealing" or "fuel stealing" weapons. It is probably usable for those as well, but for those it would be nice if the weapon can also depend on the amount of energy or fuel available on the target ship. Maybe a "deal fraction" could be added in the future to support those better as well.

**Additional context**
N/A

**Comment by Amazinite** [comment]
This sounds similar in nature to #2004; do something to the firing ship, but *only* if it actually hit a target.

**Comment by petervdmeer** [comment]
This is indeed very similar to #2004, and I actually like the proposal in #2004 better, so closing this feature-request in favour of #2004.
