### ISSUE TITLE
Quarg Anti-Missile Description

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5316]
**Is your feature request related to a problem? Please describe.**
The Quarg anti-missile outfit has no description! This is a problem because the outfit is obtainable by capturing a quarg ship, and the outfit can be viewed in the outfitter if you have it equipped. 

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I would like the Quarg Anti-Missile to get a description.

**Comment by Swiftrender** [comment]
I made a pr (albeit a bad one) awhile ago that updates all the quarg outfits that don't currently have a description. I think you could still find it on my profile.
Regardless, I'm working on finally figuring out github, and once that happens I'll re-submit the descriptions. 
You weren't the only one to think of this lol

**Comment by Amazinite** [comment]
455209c
