### ISSUE TITLE
Release Cargo Option For Player

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5317]
**Is your feature request related to a problem? Please describe.**
I noticed that merchant ships drop there cargo sometimes when under attack. It seems logical to give the player the option to drop there cargo so that they could escape from pirates.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that a new command should be added to allow the player to get rid of some of there cargo.

**Additional context**
I think that this would be a good think to add in the next update, a small but important feature. You would fail a mission doing this, but at least you would escape.

**Comment by Amazinite** [comment]
Hit i to open the player info page, click on any of your ships to pull up their ship info, and on the right side is a list of your cargo. Clicking cargo lets you eject it.

**Comment by McloughlinGuy** [comment]
huh.
