### ISSUE TITLE
Hardpoint disappear when cloaked

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#5323]
**Describe the bug**
Currently, if a ship is player owned and starts cloaking, it becomes red instead of disappearing. This isn't the same for the hardpoints: instead becoming red as well, they become invisible

**To Reproduce**
1. Have a ship that can cloak and has turrets with hardpoints;
2. Cloak;
3. See the turrets disappear.

**Expected behavior**
The same thing that happens to the ship should also happen to its hardpoints, including the ones that come from guns

**Screenshots**
![Screenshot (679)](https://user-images.githubusercontent.com/45330165/92994619-379a0c80-f4fc-11ea-8c19-20d4ae1dc70e.png)
*Uncloaked ship with hardpoints.*
![Screenshot (678)](https://user-images.githubusercontent.com/45330165/92994624-4385ce80-f4fc-11ea-9ebb-f7d0d78a79da.png)
*That same ship cloaked.*

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github
 - Version: 0.9.12

**Comment by tehhowch** [comment]
This is because the game ignores drawing things that are fully cloaked, and hardpoint sprites didn't exist when cloaking was added. 😁

**Comment by tehhowch** [comment]
I opted to preserve the current behavior re: engine flare sprites since additive sprites aren't suited to be mixed with a swizzled version of themselves (they look really gaudy).
