### ISSUE TITLE
Coalition is mentioned in the Free Worlds intro

### ISSUE THREAD

**Issue by tatami4** [endless-sky/endless-sky#5330]
https://github.com/endless-sky/endless-sky/blob/1778525c8f05cf53ff7e4db1e98d800753d31a53/data/human/free%20worlds%20intro.txt#L793
Maybe it should be "council" and not "coalition"?

**Comment by beccabunny** [comment]
The name is "Coalition of Free Worlds"

**Comment by tatami4** [comment]
Thanks. It appears that this is only mentioned in the log and I didn't think to look there.
