### ISSUE TITLE
Selecting waypoints as waipoints in map

### ISSUE THREAD

**Issue by ph2000** [endless-sky/endless-sky#534]
Some missions, notably re-con missions, require certain systems. These should have priority over other systems.The priority for the route choice should be:
- Length
- Waypoints
- Settled systems

**Comment by endless-sky** [comment]
You can use the shift key to select systems to visit along your route. It's not automatic, but it's still pretty easy to do.

**Comment by ph2000** [comment]
Thanks.
I'm going to see if it's possible to put it in the intro missions.
