### ISSUE TITLE
Prioritise Unffettered Storyline Intro

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5343]
**Is your feature request related to a problem? Please describe.**
I think that the unfettered intro should be a priority, seeing as the unfettered have a license required to buy certain ships they have.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
Since an intro for the Coalition story line is being made, I think that an Unfettered storyline intro should be made a priority for the next update.

**Describe alternatives you've considered**
An alternative would be to wait.

**Additional context**
Maybe we can wait another update, but the Unfettered are getting impatient, and they aren't nice...

**Comment by tehhowch** [comment]
If you want to work on this, or help those who might, use the discord or Google group to collaborate with other authors and content creators.

Posting an issue like this does nothing to prioritize actual story writing.
