### ISSUE TITLE
Beelzebub continued story

### ISSUE THREAD

**Issue by monticore162** [endless-sky/endless-sky#5345]
While I loved the project hawking and scientists rescue mission I think it needs a proper ending.
The part that got me thinking was when you destroy the cosmic devel Beelzebub says this:

> "Well done, Captain. Well done at being a thorn in my side. You will pay for this. One day."

So I'm thinking about writing a story centered around Beelzebub's revenge and then tracking him down and finally killing him.
any suggestions? is this a good idea?

ps. I'm rather new here so I don't really know the procedure for making these things, can someone tell me?

**Comment by MCOfficer** [comment]
> ps. I'm rather new here so I don't really know the procedure for making these things, can someone tell me?

If you're looking for content creating help, the [discord server](https://discord.gg/ZeuASSx) and steam forums are the place to ask.
