### ISSUE TITLE
Line above the selected ship

### ISSUE THREAD

**Issue by tatami4** [endless-sky/endless-sky#5347]
**Describe the bug**
There is a line above the selected ship

**To Reproduce**
1. Go to shipyard
2. Click on any ship
3. See the line above the ship

**Expected behavior**
No line

**Screenshots**
![Screenshot_20200916_204451](https://user-images.githubusercontent.com/54238857/93373819-8b8b5500-f85e-11ea-8388-53f0d6bba262.png)

**System:**
 - OS: Manjaro Linux
 - Game Source: nightly AppImage
 - Version: 133bfe8

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/c28295a156372e54b15eaec472c052c822e8cd6a
