### ISSUE TITLE
Typo in Ka'Het Debris Mission

### ISSUE THREAD

**Issue by arkhne** [endless-sky/endless-sky#5349]
Line 168 of the Ka'Het Missions txt says 

			`	They then say that they have experienced with technology they managed to steal from the Quarg during their war, and that the debris is the remnant of a somewhat common component of Quarg equipment. They also note that what you've found has deteriorated much compared to what they have acquired for themselves, and that it most likely can't even reach a fraction of its optimal cooling output.`

Specifically, 'they have experienced with technology'. This should be changed to either 'they have experimented with technology', or 'they have experience with technology'.

I can make these changes myself in a PR if so desired. It can also wait until after 0.9.13, as it's not really a big deal, it's only one possible outcome of an obscure mission.

**Comment by W1zrad** [comment]
Yup, a quick PR for a fix seems to be the rule for small typos like this one. Feel free to make one.

**Comment by arkhne** [comment]
I'm just trying to honour Derpy's wish for less PRs until 0.9.13

**Comment by Amazinite** [comment]
> I'm just trying to honour Derpy's wish for less PRs until 0.9.13

Well we're still going to be fixing bugs. My request is more about holding off on major new content and mechanics.
