### ISSUE TITLE
More Hand-to-Hand outfits

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5353]
**Is your feature request related to a problem? Please describe.**
There are only 3 hand to hand outfits n human space. I'd think that there would be a whole assortment of weapons to choose from to defend your ship.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that some more weapons should be added, like Guns and knifes and swords ect.

**Additional context**
On a side note, could someone explain to me how much a credit is worth compared to a Dollar or a Euro or a Pound?

**Comment by tehhowch** [comment]
Fill out all parts of the issue templates.
