### ISSUE TITLE
Multiple Gunboats Scanning Player

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5355]
**Is your feature request related to a problem? Please describe.**
Whenever I’m in a republic system, every single Gunboat scans me once. It would make more sense if once one gunboat scanned me the others would leave me alone.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that once one gunboat scans you the others should stop trying to scan you until you move to the next system.

**Describe alternatives you've considered**
An alternative would be to place one gunboat that will try to scan you in every republic system and have all the others stop trying to scan you. This is a more realistic solution, but I am not a coder so I don’t really know.

**Additional context**
I really want to not be scanned by 100 different gunboats every time I enter a system.

**Comment by Zitchas** [comment]
What version of Endless Sky are you playing? There have been numerous issues related to scanning, including specifically mass scanning,

https://github.com/endless-sky/endless-sky/issues/310
https://github.com/endless-sky/endless-sky/issues/1291
https://github.com/endless-sky/endless-sky/issues/2029
https://github.com/endless-sky/endless-sky/pull/3187

Scanning is generally limited to one ship per government - with the exception of ships with the surveillance personality, which will all want to scan you. So yeah, hanging out in a system with Navy Surveillance (or Remnant, for that matter), you are going to get scanned a lot. Most of the time, though, they should be few.
