### ISSUE TITLE
New category: Luxury transport

### ISSUE THREAD

**Issue by ph2000** [endless-sky/endless-sky#536]
A new category of ships, luxury transport, would enable new missions that pay very well along the lines of  an executive wanting transport from a rich planet to another. He needs luxury transport, so a star queen, a flivver or an arrow.
Obviously, this would pay very well and be rush, as well as having a condition along the lines of random < 10

**Comment by natangold** [comment]
Nifty idea, but one potential drawback: Assuming there’s a way to (a) check that the player has an appropriate ship and (b) force the passenger(s) onto that ship (and not some other ship)… what happens if the player ditches the yacht between origin and destination? Alternative suggestion: have the flivver / arrow / star queen be an escort ship, give the mission more distance and/or tighter deadlines than cargo escorts.

**Comment by ph2000** [comment]
to check, you have a 
has "ship luxury transport"

The idea was to give further incentive to get a luxury transport ship, instead of simply a high capacity ship (like the bactratian) with better combat abilities. 
I like your idea, it's much simpler, but I don't know if it's possible coding-wise to force a passenger on a specific ship.
Another way is to force the player to have the luxury ship as the flagship, but I don't know if it can be done in the coding.

**Comment by guillochon** [comment]
I like this idea a lot, +1.

**Comment by bobafetthotmail** [comment]
That would give a reason to use or have luxury transports.

**Comment by Pointedstick** [comment]
Yes, in general, I think that unlocking cool content if you have a less conventional ship type would be a good thing.

**Comment by wraitii** [comment]
Agreed, it only makes sense and it ties in nicely with the (spoilers) free worlds mission where ambassadors refuse to move in anything but a star queen.

**Comment by ph2000** [comment]
Created pull request, #553

**Comment by ph2000** [comment]
to refer to me please use @ph2000bis

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
