### ISSUE TITLE
Hidden License Requirements in shipyard sidebar  as per #5233

### ISSUE THREAD

**Issue by Zatishko** [endless-sky/endless-sky#5369]
**Describe the bug**
Collapsed description hides whether a license is needed when buying a ship or outfit.
See picture of buying Bactrain. Owned Bactrain on the right is a captured pirate Bactrain. On the left is the attempted new purchase.

**To Reproduce**
1. Go to shipyard selling licensed item ship or outfit.
2. Click on 'ship outfit
3. Scroll down. Any ship or outfit requiring license pilot doesn't have will not be allowed as expected,
4. See errorm but no clue as to why unless description is exposed

**Expected behavior**

JKnow to look at descriptions as well as if have money and space to buy ships and outfits.

**Screenshots**
If applicable, add screenshots to help explain your problem. Should be the same for any system.
![Hidden License](https://user-images.githubusercontent.com/68170965/94267810-099bcb80-fef1-11ea-9e29-3484225c69f1.png)
![Revealed License](https://user-images.githubusercontent.com/68170965/94267745-f5f06500-fef0-11ea-986c-d9ecc8c0096e.png)

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build: `http://mcofficer.me:8080/job/endless-sky-win64/<build number>/`)

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by tehhowch** [comment]
I would consider licenses a part of the description. If you hide the description, then you hide non-stat details about the items.

The simplest fix is to draw licenses as not a part of the item description. You would then not be able to hide this information, even if it is ingrained in your brain from hours of play.

Another solution would be to replace the collapsed text with the license requirements if they are not capable of being satisfied. They would continue to be displayed as part of the description if expanded.

A third solution would be to provide a tooltip for the "Buy" button when it is disabled.

**Comment by beccabunny** [comment]
The second solution seems the best for me
