### ISSUE TITLE
<npc> placeholder being filled in with name of pirate ship in mission with two NPCs and the pirate ship listed second

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#537]
I'm writing a mission that has two NPCs: one friendly escort and one pirate. The pirate is listed second. The <npc> placeholder in the mission description is getting auto-filled with the name of the pirate ship instead of the friendly escort ship, even though the pirate ship is listed second and the docs say that the <npc> placeholder should be filled in with the name of the first ship that's defined.

Here's the code for the mission: http://pastebin.com/VZ3TfZWg

Here's how it shows up in my save game file: http://pastebin.com/BrbuAmNp

You can see that the wrong name is being used in the mission description:
>     description "The crew of the science vessel Morning Wolf requests an escort to New Kansas in the Muhlifain system where they plan to study some unusual phenomena. Escort them there and then return them to Memory for 100,000 credits."

"Morning Wolf" is the name of the pirate ship, not the science vessel.

**Comment by endless-sky** [comment]
The `<npc>` name will always be the name of the first ship in the *last* NPC in the list, not the first one.

**Comment by Pointedstick** [comment]
Ahh! Thanks. Might wanna change the wiki to from this:

> \<npc> = the name of the first NPC in the mission description

To something like this:

> \<npc> = the name of the first ship in the last NPC block in the mission description
