### ISSUE TITLE
Ability to sort/filter missions

### ISSUE THREAD

**Issue by mohmad-null** [endless-sky/endless-sky#5372]
It would be nice if you could sort missions, ideally by income. Possibly some filtering too.

Mid-game, it's a complete waste of my time to show me things that pay a few thousand when I have a million or two in the bank. It'd be nice to sort them by value so I don't have to manually go through them all and try and remember which one is the most valuable.

**Comment by tehhowch** [comment]
1. Don't ignore the templates.
2. Following step one would have led you to #236
