### ISSUE TITLE
Colourised text

### ISSUE THREAD

**Issue by mohmad-null** [endless-sky/endless-sky#5373]
It would be great if value text was colourised. For example, all "credits" values could be in yellow. Planet names in Blue, system names in a different blue. Etc etc. I've seen this in a few games and it works really well.

Example:
```
Bob wants <pink>14<pink> tons of pig swill taken to <dark blue>Earth</dark blue> in <light blue>Sol</light blue>. You'll get paid <yellow>1,000</yellow> credits.
```

This would greatly improve both the parsing and comprehension of missions.

Ship Mass (which should really be "Volume", but that's a different ticket), heat, and energy are other obvious candidates that would benefit from it.

Would probably also improve Accessibility if the colours were carefully chosen.

**Comment by MCOfficer** [comment]
Refs #558 and everything linked there.

Afaik SDL2 supports drawing colourised text, so this could be tackled once the overhaul of the font rendering system is compelte.

**Comment by tehhowch** [comment]
Rainbow text does not align with the monochrome UI design currently implemented. If you would like this feature, you will need to implement it yourself. If said implementation can be made opt-in, then feel free to open a PR.

@MCOfficer I don't see this as related to 558 per se, as the requested highlighting here would be provided by the game automatically when parsing text substitutions. It is blocked by the lack of "inline styles" for game text, though.

**Comment by MCOfficer** [comment]
@tehhowch I was under the impression that we are not currently able to draw colored text.

**Comment by tehhowch** [comment]
Currently, each independently positioned block of words can be drawn in a given color. Each different color requires a different call, and a "wrapped" text block can only have a single color.

https://github.com/endless-sky/endless-sky/blob/f67b5de362253c7aa0d6fde99771e4cedade6c18/source/Font.h#L39

Without inline styles, this proposed feature is not possible. Even with inline styles available, I don't think it is a good fit for our UI color scheme, especially w.r.t. text display. Serialization of the formatted text will need considerable thought as well; probably it makes sense to no longer save strings after text substitutions are applied.

**Comment by oo13** [comment]
FYI
Pango supports [a markup language](https://developer.gnome.org/pango/stable/pango-Markup.html), so contents creators can use colored texts.
#4123 enables it.

**Comment by starcatter** [comment]
I'm playing with a modification that draws key mission information in bold, IMO it fits the visual style pretty well. 

<img width="329" alt="text" src="https://user-images.githubusercontent.com/30572485/98711325-239c4b00-2385-11eb-8b59-66b30140a628.png">

There's still some minor bugs in my code though, mainly with properly matching things in parenthesis or quotes. I think using a text rendering library is a better idea, what I did is very simple and still adds quite a bit of code to maintain, a proper implementation would likely be even larger.
