### ISSUE TITLE
Feature Request: Submunitions at an angle.

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5376]
**Is your feature request related to a problem? Please describe.**
I would like to create a weapon where submunitions fire at a precise angle from the direction/path of the parent projectile.
Submunitions currently by default fire at exactly the same direction/path as the parent.

This feature should allow for new types of weapons that steer for intermediate locations besides their intended target, that split very precisely or even weapons that travel around their target and then hit from the other side.

**Related Issue Links**
- [hardpoint offset](https://github.com/endless-sky/endless-sky/issues/3878) mentions a submunition fired at 180 degrees (back at a target that was passed).
- [range override](https://github.com/endless-sky/endless-sky/issues/4478) seems related because submunitions fired at an angle will have a reduced range compared to submunitions travelling in a direct line.
- I had expected to find many other feature requests requesting a feature like this, but I didn't find others.

**Describe the solution you'd like**
I would like to see the keyword `facing` to be usable on submunitions (or some better solution that accomplishes this). And an `offset <x> <y>` keyword added to set an offset relative to the origin munition (to support #3878 as discussed below). An example of the keyword being used:
```
outfit "Left Splitting Mirv"
	weapon
		"submunition" "Mirv Fragment" 1
			facing 266
			offset -10 -6
		"submunition" "Mirv Fragment" 1
			facing 268
			offset -10 -3
		"submunition" "Mirv Fragment" 1
			facing 270
			offset -10 0
		"submunition" "Mirv Fragment" 1
			facing 272
			offset -10 3
		"submunition" "Mirv Fragment" 1
			facing 274
			offset -10 6
```

**Describe alternatives you've considered**
The current alternative used for most submunitions where an effect like this is desired is to give an `inaccuracy` on the submunition itself, but that doesn't give the precission that I like to have.

**Additional context**
I hope the description is already sufficiently clear; please let me know if I should add some more details.

**Comment by Amazinite** [comment]
I know a topic that's come up in the past related to submunitions is the idea of a submunition offset. That is, the submunition is created with some offset from where the parent projectile died. That could be bundled with this idea of changing the angle at which the submunition is created from the parent projectile.

**Comment by petervdmeer** [comment]
Yes, that topic in the past was in ticket #3878. Sounds like a good idea to combine the two when implementing this.

**Comment by petervdmeer** [comment]
I changed the keyword from `angle`to `facing`. Angle sounds very generic and I think facing conveys the meaning better. (Especially if we also want to add a velocity delta somewhere in the future.) I also added an `offset` keyword based on the discussion here.
