### ISSUE TITLE
"Earth Retirement" has no payment

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#5377]
**Describe the bug**
The "Earth Retirement" mission has no payment. This is true whether you refuse their payment or not.

**To Reproduce**
1. Get the "Earth Retirement" mission.
2. Go to Earth.
3. "Before he leaves Charles stops by you, and takes out a large clump of credit chips with a total value of ." In the data, there is a `<payment>` before the period. This is blank in the game because this mission has no payment.
4. No matter which branch you choose, you don't get paid.

**Expected behavior**
"Before he leaves Charles stops by you, and takes out a large clump of credit chips with a total value of (some amount)." and accepting payment leads to getting paid.

**System:**
 - OS: Debian 11 "Bullseye"
 - Game Source: self-compiled
 - Version: commit hash f67b5de362253c7aa0d6fde99771e4cedade6c18 (latest as of this posting)

**Additional context**
I loved that I had the option to do a good deed by refusing payment, but still. :)

The mission description also contains a `<payment>` substitution. I didn't look at ingame, but I assume it shows up blank, just like the other one.

**Comment by Amazinite** [comment]
#5221

**Comment by SolraBizna** [comment]
It's true that this is a duplicate issue. But, the issue it is a duplicate of is closed. Typing "Earth Retirement" into the search box, leaving the default "is:issue is:open" in place, will currently turn up 0 results. Shouldn't #5221 be re-opened until the referenced PR lands, so that this issue doesn't keep being re-reported?
