### ISSUE TITLE
Help needed: MA on open-source game development

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [endless-sky/endless-sky#5378]
Hi there, seems like your discussion forum is dead, the repository is active though.

My name is Julian Schönbächler, I'm a programmer and professional game designer from Switzerland working at [Koboldgames][1], a small Swiss game studio. I am currently doing my Master's degree in Game Design at the [University of the Arts in Zurich][2] and I would kindly ask for your help and hope to reach various open-source game projects from different areas.

> **TL;DR** - In my research work for my MA thesis I focus on open-source game development, its structure and hierarchy as well as the motivation of the people involved in the project. I try to explore how game design processes function on games that are developed in the open and how collaboration on a project might serve an educational purpose. If you got *15min* on your hands to fill out a survey on this topic, I would greatly appreciate it. Thank you! [To the survey...][survey]

I believe I first came into contact with open-source games in my early secondary school days, when I was searching for free games on the internet to play on our old and slow Mac computer. [SuperTuxKart](https://supertuxkart.net/Main_Page) is one of the games that still has a special place in my heart. To this day, it is a free and open-source game that receives a good portion of attention and is in active development. The open-source gaming community was also the place where I took my first steps in my game design career. An environment that provides you with free access to source code and assets, techniques and tutorials. One that actively encourages people to become contributors and joining a community. For me that was the best insight into how game development works and all the aspects it consists of I could ever get. Eventually, even though not really intended, years later I found my way back to the art of design and did my studies in the field of game design.
I am still lurking around in many of the open-source communities I once actively contributed to and maybe I will have time at hand to become more engaged in some of them. But over my whole engineering journey free and open-source software along with its development played a big role in my personal growth.

Design and development of open-source games looks different compared to how it is generally done in the industry. Note that I would like to differentiate between game design and game development. While game development is often used as an umbrella term for all the specialized fields that the creation of a video game requires, design however is focusing onto the ruleset and mechanics as well as the balancing and the motivation design. The open-source games community as I experienced it is often more driven by the development aspect. Combined with other differences e.g. of having no fixed deadlines or compulsory feature requests, the design process is quite interesting and unique. The feedback loop tends to be more direct, the community as a collective can drive a project and participate in shaping the result.
Besides, actively developing on a game project in the open is a whole different experience. The motivation on working on a project in your spare time can range from fun-seeking to the eager of learning new things. I want to explore this kind of development deeper and maybe shape the future of free and open-source game development a little by giving back some design knowledge I have learned back into the communities (eh, every student dreams big, right?).

So for now, I am in the need of data. Because researching something I only halfway understand will not work here. That is why I prepared a survey with questions about _your_ personal experience with open-source game development, the projects you are involved in and the hierarchical structures under which they are developed. It consists of:
- Basic demographic questions
- Questions about your education and background
- Your open-source engagement
- Experienced project structures and hierarchies
- Your personal involvement in open-source game projects

I would be very happy if some of you could take the time (around 15-20 minutes) to fill it out as your experience and knowledge is extremely important. It does not matter if you are one of the projects core developer or a member of the community who mainly contributes to discussions. Consider yourself involved as part of the game project and answer the questions as best as you can, any perspective is relevant. Thank you so much in advance!
You can find the survey here: https://survey.julian-s.ch/limesurvey/index.php/918477

The survey software used is FOSS ([LimeSurvey]) and self-hosted on my personal webspace. Participation in the survey is completely anonymous, answers are encrypted and *no* personal data will be permanently stored in the database. At the end of July 2021, all the data will be cleared and analysis and results published under the GPLv3. **The survey ends on the 15. October 2020.**

That is all from me for now,
Cheers
Julian

[1]: https://koboldgames.ch/
[2]: https://www.zhdk.ch/
[LimeSurvey]: https://github.com/LimeSurvey/LimeSurvey
[survey]: https://survey.julian-s.ch/limesurvey/index.php/918477

**Comment by JulianSchoenbaechler** [comment]
I'll probably close this, as it is really something else than an issue or feature request.

**Comment by Amazinite** [comment]
Looks like the survey link doesn't like me.
![image](https://user-images.githubusercontent.com/17688683/94353671-ca30c480-0041-11eb-8a0d-a9fcb393cf0b.png)

**Comment by MCOfficer** [comment]
Works for me, so either it was fixed or this is something region-dependant. 

Either way, It's not optimal to post this on the issue board, but i suppose with the google forum being dead you don't have much of a choice. If you want to reach even more people, you can ask on our [Discord Server](https://discord.gg/ZeuASSx).
