### ISSUE TITLE
Typo and bug in 'Investigating Kor Efreti Worlds'

### ISSUE THREAD

**Issue by roadrunner56** [endless-sky/endless-sky#5379]
**Describe the bug**
When performing the job 'Investigating Kor Efreti Worlds', the dialog upon landing on a Kor Efreti planet/station states that the Wanderers are there to investigate environmental problems on a Efreti world. However, this mission can have the abandoned station Tefkar Ret as its destination, which does not make sense in the context of the dialog and the larger story. 
In addition, the dialog that pops up when the player lands on a Kor Efreti planet has a typo: 'The Wanderers tour the planet to investigate the _envoronmental_ problems...'.  _envoronmental_ is spelt wrong.

**To Reproduce**
1. Accept a  'Investigating Kor Efreti Worlds' job on a Wanderer planet that has Tefkar Ret as its destination
2. Land on Tefkar Ret
3. Read description, see errors

**Expected behavior**
I expected the mission to only target planets, and not stations, as you cannot terraform a station. I also expected the dialog to be typo-free.

**Screenshots**
![Kor Efret](https://user-images.githubusercontent.com/65418682/94355169-27774680-003f-11eb-98ef-be60007d1487.png)

**System (please complete the following information):**
 - OS: Kubuntu 20.04
 - Game Source: Continuous
 - Version: Commit f67b5de

**Additional context**
I really like the Kor Efreti missions, they flesh out an often-forgotten faction nicely.

**Comment by tehhowch** [comment]
Good eye! Looks like a (very minor) miss in these (very new) missions from @W1zrad -- dynamic stopover filters in 0.9.13 are a small bit more lenient in the landing locations they can select, so pure government filters may not be sufficiently specific.

**Comment by W1zrad** [comment]
Thanks for catching these! This should be easy fixes; I can get to it in an hour or two. Happy to hear you like the missions!
