### ISSUE TITLE
"On visit" doesn't work for stopovers

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#538]
I'm writing a mission where you escort a ship to a stopover and then go somewhere else. The "on visit" tag (to display the "oops, wait for your escort to show up" text) only works when I land on the final destination without the escort. It doesn't fire when I land on the stopover planet without the escort.

**Comment by endless-sky** [comment]
Use "on stopover" - it will trigger when you visit the last of the stopover locations. If you need to have multiple stopover locations and show a dialog at ever single on of them, you'll have to do that as a separate mission.

**Comment by Pointedstick** [comment]
Yes, I am using "on stopover" to display a dialog when you get to the stopover planet. What I want to do is display a *different* dialog when you land on the stopover planet without the ship you're escorting there.

**Comment by endless-sky** [comment]
The stopover counts as completed whether or not any NPC conditions (including "accompany") are met at that moment. NPC conditions only affect whether the mission can be completed. If you're trying to do something that complicated, you may be better off using multiple missions instead of stopovers.

**Comment by Pointedstick** [comment]
Basically resolved with 932ee4e.
