### ISSUE TITLE
Bug: Auto-fire considers disabled enemy ships to be valid target again after boarding them.

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5382]
**Describe the bug**
When exiting the boarding panel while auto-fire is turned on, my ship automatically fires a volley at the disabled ship, usually destroying it. On particularly high-hull enemy ships the disabled ship will sometimes survive the initial volley, and the auto-fire systems seems to then realize that it is disabled and ignores it thereafter. As such, it seems kind of like there is a bug in the intial "undocking" action that briefly makes the turrets consider the ship I boarded to be briefly active again.

**To Reproduce**

0. While "Automatic firing" is "on"
1. Disable a ship
2. Board the ship
3. Exit the boarding screen.
4. Watch auto-firing turrets destroy the ship.

**Expected behavior**
That when I disengage from a boarding a disabled ship; the turrets will ignore the ship. After all, it is disabled. I can very easily press my firing key to order its destruction if I so choose.

**Related Issues**
https://github.com/endless-sky/endless-sky/issues/3696 (Closed so original poster could test in 0.9.9)
https://github.com/endless-sky/endless-sky/pull/3697 (Closed so original poster could test iAI changes in 0.9.9)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: self-compiled
 - Version: commit f67b5de

**Additional context**
The mission `"Remnant: Salvage 4"` requires the player to disable the target Korath ship, and the mission will fail if the player destroys the ship. As such, having auto-fire active means that the player will fail the mission if they board the ship. As such, this bug will now actually cost players half their paycheck in the course of doing a regular mission, if they have auto-fire turned on.

**Alternatives**
1) Have the automatic firing option rotate through several options: Off, Only Active threats, All threats. 
Off is off, All threats is the current behavior, and "Only Active Threats" only fires on non-disabled hostile ships. 
This alternative would enable players to play cold-hearted types who have their turrets automatically blast looted ships as they pull away. I don't see the point, but I could see some people enjoying having their ships automatically "take out the trash" so to speak.
2) Have an "auto-fire" key that toggles auto-fire on and off, perhaps in conjunction with alternative 1, to give a situation similar to escort's expending ammo. Thus players could have auto fire on "only active threats" and then switch to "off" when they are closing in to board to prevent accidental destruction (either post boarding via this bug, or pre-boarding by having another hostile get close enough to trigger weapon fire.)

**Comment by Amazinite** [comment]
An exception for previously boarded disabled ships is explicitly made for AutoFire, so this isn't a bug, but a question of mechanics.
https://github.com/endless-sky/endless-sky/blob/de69e19439655b756c8b0c1e9e98abf7ab71a030/source/AI.cpp#L2907-L2909

**Comment by Zitchas** [comment]
So, if I'm understanding correctly, the mechanics have been specifically set up so that formerly-boarded disabled enemy ships have been specifically included in targets to be shot?

**Comment by Anarchist2** [comment]
More like boarded disabled ships aren't on the no-hit list

**Comment by petervdmeer** [comment]
> An exception for previously boarded disabled ships is explicitly made for AutoFire, so this isn't a bug, but a question of mechanics.

The AutoFire code is used both for NPC ships as well as for the player ship. I can imagine that a plundering NPC should shoot ships that were boarded to prevent that NPC from boarding it again. For player-controlled ships I would prefer to let the player decide when the disabled ship is to be shot at.

Issue https://github.com/endless-sky/endless-sky/issues/871 is also related; if plundering takes time, then players (and NPCs) can be interrupted during plundering, which means that they might want to continue plundering at a later time (without their turrets automatically tearing the target ship apart in the meantime).

**Comment by tehhowch** [comment]
Resolved with #5387
