### ISSUE TITLE
Typo in line 677 of persons.txt

### ISSUE THREAD

**Issue by fulmerw** [endless-sky/endless-sky#5391]
**Describe the bug**
of of the possible response fragments of the person "Local God" has a typo. the line states "open a univeral outfitter." when it should probably say "open a universal outfitter."

**To Reproduce**
1. Go look at the code
2. scroll down to line 677
3. see the typo
4. there is no step 4.

**Expected behavior**
see description.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS:N/A I first saw the typo in the code on my phone.
 - Game Source: Github
 - Version: master branch commit hash 0e90fa1107eb406dd85e3c36fff213d5eaac217c 

**Link to save file**
Not Applicable

**Comment by Amazinite** [comment]
Good eye. Fixed. https://github.com/endless-sky/endless-sky/commit/5827a9a1cfa97fa4159ed945e1d85dff8b8a3993
