### ISSUE TITLE
"You have visited" map key should recognize unvisited planets in uninhabited systems

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5399]
**Is your feature request related to a problem? Please describe.**
The "You have visited" map key (switched to by clicking `(not yet visited)` or `(has been visited)` under a planet menu on the left side when in port mode) currently prioritizes showing a system as uninhabited over showing whether the landable planets in the system have been visited.

![image](https://user-images.githubusercontent.com/17688683/94984552-2f415a00-051b-11eb-9b1f-a4f682ea8eb5.png)
![image](https://user-images.githubusercontent.com/17688683/94984554-35373b00-051b-11eb-904b-d9322857cca7.png)

**Related Issue Links**
N/A

**Describe the solution you'd like**
Only highlight a system as uninhabited if it contains no landable planets. Otherwise, show if you've visited all the landable planets in the system.
Planets that are unlandable due to an attribute requirement should still show as uninhabited.

**Describe alternatives you've considered**
N/A

**Additional context**
Relevant code:
https://github.com/endless-sky/endless-sky/blob/c77348a08ed60db698227c4d14aadf7856059651/source/MapPanel.cpp#L702-L744

**Comment by TheDeathStar3** [comment]
Hi, I am using the 0.9.13 beta version of Endless sky and uninhabited planets are still not marked as visited or not visited for me. I have visited every single planet and system in the game. I tried to download the continuous version on GitHub and use that but that still did not work. Is anyone else having this issue or is it just me? I did use new pilots and just transferred the visiting planets and system statuses across the save files.

**Comment by tehhowch** [comment]
> Hi, I am using the 0.9.13 beta version of Endless sky and uninhabited planets are still not marked as visited or not visited for me. I have visited every single planet and system in the game. I tried to download the continuous version on GitHub and use that but that still did not work. Is anyone else having this issue or is it just me? **I did use new pilots and just transferred the visiting planets and system statuses across the save files.**

Save-editing is not a supported use case. Please verify on a new pilot with no installed plugins and no save file edits.

**Comment by TheDeathStar3** [comment]
I confirm that on a new pilot, with no plugins and no save file edits the uninhabited planets still do not show if they have been visited or not.
![Screen Shot 2021-04-20 at 6 59 48 am](https://user-images.githubusercontent.com/54761256/115305503-c5805900-a1a9-11eb-8421-ee760df38630.png)
