### ISSUE TITLE
Distance to and from stopovers not taken into account for payment calculation

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#540]
The title says it all. This is sometimes easy to work around, but sometimes not, and it really is a bug so you shouldn't have to.

I do love the new stopover functionality, though (in case it wasn't obvious)! Great feature.

**Comment by endless-sky** [comment]
The trouble is, a fully generic solution to this would involve calculating a traveling salesman path between any number of stopover locations and the source and destination systems. I might just settle for an approximation instead, e.g. the longest path from the source to any stopover to the destination.

**Comment by endless-sky** [comment]
Fixed in c1ef2c5, using a greedy algorithm rather than a full traveling salesman path, because that's a good enough approximation.
