### ISSUE TITLE
false/unclear discription in wiki BuildInstructions for linux

### ISSUE THREAD

**Issue by Ag-1407** [endless-sky/endless-sky#5401]
Hi everybody,
the BuildInstructions in the wiki (chapter linux) says:
"You can then just navigate to the source code folder in a terminal and type:

```
$ scons
$ ./endless-sky
``` 
"
but in the the source folder is no SConstruct file:
```
scons: *** No SConstruct file found.
File "/usr/lib/scons/SCons/Script/Main.py", line 940, in _main
```
So, I looked around and found the SConstruct file in the main folder (endless-sky)

**To Reproduce**
1. clone the project
2. go to the project folder and then navigate to the 'source' folder
3. execute `scons`
4. see the error
5. navigate back to the project folder
6. execute `scons` again
7. it works

Link to wiki page:
[BuildInstructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions
)

**Suggested solutions:**
1. change the text in the wiki file from `You can then just navigate to the source code folder in a terminal and type:` to `You can then just navigate to the project code folder in a terminal and type:`
2. delete the line, because the top of the file already says `The game's root directory, where your unzipped/git cloned files reside, will be your starting point for compiling the game.`
3. move the SConstruct file into the source folder

Greetings
Ag

PS: This is my first issue on github, so i hope i have not overlooked some issue about the same problem

**Comment by Rakete1111** [comment]
Also this line:

> The program will run using the "data" and "images" folders that are found in the source code folder itself.

**Comment by tehhowch** [comment]
Should be resolved now

**Comment by Ag-1407** [comment]
same fault in 'readme-developer.txt':
`You can then just navigate to the source code folder in a terminal and type:`

**Comment by tatami4** [comment]
This should be closed as 'readme-developer.txt ' has been updated.
