### ISSUE TITLE
Game does not update internal audio device when changing Windows audio device 

### ISSUE THREAD

**Issue by ryknuth** [endless-sky/endless-sky#5405]
**Description**
Game audio device does not change when Windows changes audio device.

**Reproduce**
- Opened game
- Changed windows audio device from headset to speakers in Windows control panel
- Game audio does not come through speakers

**Comment by tehhowch** [comment]
Don't ignore the templates.

**Comment by Amazinite** [comment]
Hello?

**Comment by quyykk** [comment]
I think we'll just close this.
