### ISSUE TITLE
mass confusion

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#541]
Why have a bug reporting section on the forum if Github is the main reason for that? a lot of the bugs i'm seeing being reported on Google are ones already reported and addressed here. Maybe just make Google for Plugins/ weapon/outfit creation etc. and let Github be the only bug reporting area

**Comment by endless-sky** [comment]
It's mainly for people who don't want to open a GitHub account, the same as why I have a Steam bug reporting forum.

**Comment by thenerdfreak** [comment]
They're either getting it from Steam or Github one, so they're bound to already have an account on one of the other two options
