### ISSUE TITLE
On waypoint MissionAction that triggers on final waypoint visited

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5411]
**Is your feature request related to a problem? Please describe.**
When a mission has a randomized waypoint, it is currently impractical to have a dialog or conversation appear once that waypoint, or all waypoints, has been visited.

**Related Issue Links**
#4978

**Describe the solution you'd like**
Create an `on waypoint` MissionAction that has the exact same behavior as `on stopover`, i.e. triggers after all waypoints have been visited.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Zitchas** [comment]
Thank you for filing this issue.

If/When an `on waypoint` is implemented, it will be useful for adding a "visit complete" message to the Astral job in "Remnant: Expanded Horizons Astral" job; as well as other jobs of the same style that I have planned.

https://github.com/endless-sky/endless-sky/pull/5367
