### ISSUE TITLE
Request: Support multiple specific planet `on stopover` blocks

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5419]
**Is your feature request related to a problem? Please describe.**
Currently, a mission can only have a single `on stopover` block, but can have multiple stopovers. The current behavior is that the `on stopover` triggers on the last stopover planet the player visits.

**Related Issue Links**
I didn't see any issues that obviously referenced this.
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions specifies that we can have multiple stopovers, which I originally interpreted to mean we could have multiple `on stopover` blocks; and I assumed that the listed behaviour of triggering on the last stopover planet visited was the default behavior for when no specific planet is listed.

**Describe the solution you'd like**
My proposed solution is to modify the stopover block such while the generic `on stopover` continues to function as it currently does, we can also use `on stopover planetname`, which the game will recognize as a separate stopover block that will trigger specifically on that planet. 

**Describe alternatives you've considered**
Adding a new block `on landing planetname` that acts exactly like `on enter` does for systems, except for planets.

As well, it would be really useful to be able to specify a number, for example `on stopover 1` which triggers on the first stopover planet visited, or `on stopover 4` which triggers on the 4th stopover planet visited.

**Additional context**
https://github.com/endless-sky/endless-sky/pull/5418 demonstrates how multiple stopovers could be used in a mission. 

Combining this with the recent PR that adds visited systems/planets as a condition could enable branching on stopover dialogs that change to reflect the order they are done or which places have already been visited. Although on second thought, this wouldn't be very useful when the player has already visited those planets in the past. Not sure if a branch could check to see whether this is the first, second, third, etc visit in the stopover set; but it would be useful if we could do so.

**Comment by Amazinite** [comment]
Effectively a duplicate of #4978.

**Comment by Zitchas** [comment]
Yes, it looks like it. Not sure why it didn't come up when I searched.
