### ISSUE TITLE
Graphical artefacts with Intel UHD630 

### ISSUE THREAD

**Issue by GabesDark** [endless-sky/endless-sky#5421]
**What Happens:**
When i Start the game, the game appears sorts of green lines looking like artefacts, which only happens on endless sky not any other game.

**To Reproduce**
1. Just open the game.
2. once the game opens, you will able to see it.

**Expected behavior**
This is my first time playing this game on my brand-new rig, usually it loads without any problems in other computers.

**Screenshots**

![glitched](https://user-images.githubusercontent.com/72561467/95468648-1d194e80-0955-11eb-9e20-a1fcbccfc57f.png)

**System (please complete the following information):**
 - OS: Windows 10 Pro V.2004(not in any insider build)
 - Game Source: Steam/Steam Beta(I Use both)
 - Version: 0.9.12
 - resolution: Primary Screen:1980x1080(FHD)

**My Setup:**
 - Processor: I3-10100
 - Mobo: B460M DS3H
 - RAM: HyperX Fury 2x8Gb 2666mhz
 - GPU: Intel(R) UHD Graphics 630

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**
Probably issues with the graphics driver? or resolution?

**Comment by GabesDark** [comment]
[preferences.txt](https://github.com/endless-sky/endless-sky/files/5348432/preferences.txt)

Forgot to add this, the prefs on the game right now.

**Comment by MCOfficer** [comment]
duplicate of #5130 (contains a fix)

**Comment by GabesDark** [comment]
Issue Fixed with Beta Drivers from intel
Which can be downloaded there: https://downloadcenter.intel.com/download/29913/Intel-Graphics-BETA-Windows-10-DCH-Drivers?product=80939
Game works as the usual.
