### ISSUE TITLE
Remove dedicated variants, use Add Attributes instead

### ISSUE THREAD

**Issue by Janaszar** [endless-sky/endless-sky#5423]
`Barb (Proton)` currently uses the full data definition for a ship.  Most other ships with variants (Modified Argosy is the only one not like that, I think) use the `add attributes` method to define a different version of the ship (see Marauders.txt https://github.com/endless-sky/endless-sky/blob/7c85825e5148cfb5b7d7cd5ce13a34e91d2e8560/data/human/marauders.txt )

Seeing as `add attributes` can also change ship images/thumbnails as well, is there any reason the Modified Argosy couldn't be switched over too?

Proposed solution is to simplify the data in that these two ships get redone using the `add attributes` method, instead of being unique definitions.

The only issue I can think of is that outfit variants might cause issues?  For Barb (Proton), not an issue so far since it has no variants, but the Modified Argosy does have 4 variants, and I'm not sure of the interactions of `ship` with `add attribute` ships without testing.

**Comment by Amazinite** [comment]
The reason for the Modified Argosy being its own ship definition is the same reason why Marauder ships start with their own definition. Variants of variants are also something we want to avoid.

**Comment by Anarchist2** [comment]
As noted on the wiki:

> While it is possible to "chain" the usage of `add attributes`, by referring to a variant instead of a base model ship, e.g. `ship "Arrow (Faster)" "Arrow (Too Fast)"`, doing so will result in incorrect "model name" display when targeting ships, and may result in improperly configured ships due to the order in which the game creates ships. **Thus, you should always refer to a "base model" ship, one that was defined as `ship <name>` and not `ship <base name> <variant name>`.**
