### ISSUE TITLE
The Station Ssl Vida Does not appear

### ISSUE THREAD

**Issue by CrabbyMythology** [endless-sky/endless-sky#5424]
**Describe the bug**
As stated in the title the station Ssl Vida does not appear when you got to the system Postverta. This happened with both a captain that I had before I add the data and after.
![Screen Shot 2020-10-07 at 4 11 41 PM](https://user-images.githubusercontent.com/72316240/95490000-358d6700-095d-11eb-9cd6-87b6557a670f.png)
![Screen Shot 2020-10-08 at 11 56 12 AM](https://user-images.githubusercontent.com/72316240/95490049-4a69fa80-095d-11eb-9581-b2313cace207.png)
![Screen Shot 2020-10-08 at 11 56 12 AM](https://user-images.githubusercontent.com/72316240/95490074-51910880-095d-11eb-9fb3-a17796230059.png)

**To Reproduce**
1. Go to 'Postverta'
2. See error

**Expected behavior**
The expected behavior is that it would exist as it is a requirement for continuing the Remnant storyline.

**Screenshots*

**System (please complete the following information):**
 - OS: [ Mac Something. (sorry but I can't find where this information is located)]
 - Game Source: [Github]
 - Version: [The Continues Build as of October 1, 2020`)

**Link to save file**
[I don't know how to upload this sorry]

**Additional context**
This also happens with the ringworld in Queri.
![Screen Shot 2020-10-08 at 12 05 08 PM](https://user-images.githubusercontent.com/72316240/95491343-142d7a80-095f-11eb-8edb-1c7b9f0f8397.png)

**Comment by CrabbyMythology** [comment]
I forgot to add a screenshot of the ringworld missing.
![Uploading Screen Shot 2020-10-08 at 12.05.08 PM.png…]()

**Comment by Zitchas** [comment]
Thanks for reporting this. A pilot file would be appreciated (just drag the text file that is your pilot file onto the text box). 

Your saves should be located at: ~/Library/ApplicationSupport/endless-sky/saves/

**Comment by CrabbyMythology** [comment]
> Your saves should be located at: ~/Library/ApplicationSupport/endless-sky/saves/
That may be a problem because I didn't put it in application but on the desktop. Does that change anything?

**Comment by Zitchas** [comment]
Sorry, I'm not familiar enough with how MacOS handles things. On Windows, it doesn't matter where the application is - the save will always appear in the same place. I suspect that OSX is the same. Note that the save folder is not inside the application folder, it is located inside a separate folder that holds things that the user changes: Namely, preferences, save files, plugin folder, etc.

**Comment by CrabbyMythology** [comment]
> Sorry, I'm not familiar enough with how MacOS handles things. On Windows, it doesn't matter where the application is - the save will always appear in the same place. I suspect that OSX is the same. Note that the save folder is not inside the application folder, it is located inside a separate folder that holds things that the user changes: Namely, preferences, save files, plugin folder, etc.

I'll keep looking for. I'll update it if I find out might be a while because at school.

**Comment by Zitchas** [comment]
Thank you!

**Comment by Rob59er** [comment]
Did you install the continuous build via the ESLauncher?

**Comment by CrabbyMythology** [comment]
> Did you install the continuous build via the ESLauncher?

No I did not I just add download the continuos build from github.

**Comment by Rob59er** [comment]
Right click on endless-sky and click show package contents.

**Comment by CrabbyMythology** [comment]
> Right click on endless-sky and click show package contents.

Why?

**Comment by Rob59er** [comment]
![Screen Shot 2020-10-10 at 9 38 37 PM](https://user-images.githubusercontent.com/29336153/95669025-fc155100-0b40-11eb-911d-8508375269d0.png)
At the bottom of finder it will show a path similar to the one above, knowing it would help find your saves

**Comment by CrabbyMythology** [comment]
> At the bottom of finder it will show a path similar to the one above, knowing it would help find your saves

Ah. Thanks but  I already look there but maybe I overlooked it the first time.

**Comment by Rob59er** [comment]
Saves are in a different place then the rest of the files

**Comment by CrabbyMythology** [comment]
> Saves are in a different place then the rest of the files

Could you tell me where they are exactly?

**Comment by Rob59er** [comment]
They should be in the path Zitchas wrote earlier, but if you directly installed it to the desktop, frankly I can't be sure.

**Comment by CrabbyMythology** [comment]
> Having the path at the bottom of the screen would help find them, however

How do you do that?

**Comment by Rob59er** [comment]
Finder -> view -> show path bar. Right click endless sky -> show package contents -> take screenshot of path at bottom of finder

**Comment by CrabbyMythology** [comment]
> Finder -> view -> show path bar. Right click endless sky -> show package contents -> take screenshot of path at bottom of finder

Thanks. I'll keep searching.

**Comment by CrabbyMythology** [comment]
I Mange to fix it by installing it again I don't know why or how but it works now.

**Comment by Zitchas** [comment]
Glad to hear it is working now. Please let us know if it happens again or you figure out how to recreate the problem.

**Comment by CrabbyMythology** [comment]
> Glad to hear it is working now. Please let us know if it happens again or you figure out how to recreate the problem.

I will. Should I close the issue?

**Comment by Zitchas** [comment]
Yes. The issue is gone, so no sense keeping it open. Might have been something invisible like being on a slightly older version of the data files or something. By all means re-open it if you recreate the problem, though.
