### ISSUE TITLE
Expand map every update

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#543]
It would be interesting if, on every update:
- Several systems are added at the edges of the map. These systems would either be uninhabited or have one inhabited planet/station (no outfitter/shipyard).
- A couple uninhabited systems with an inhabitable planet become inhabited (no outfitter/shipyard).
- An uninhabited system without an inhabitable planet gains a station.
- etc.

If we were to improve and document the [Endless Sky Map Editor](https://github.com/endless-sky/endless-sky-editor/releases), we could easily get the community to submit candidates for new systems.

**Comment by endless-sky** [comment]
0.8.10 will include at least one new alien species with its own territory, and depending on what others contribute, there should be others coming soon, as well.

**Comment by Thunderforge** [comment]
@lehgogh Contributing a pull request to add planets and systems yourself would make sure this happens.
