### ISSUE TITLE
intro missions.txt: mission "Intro [2 Transport]": Inconsistent usage of verb tense

### ISSUE THREAD

**Issue by Kasijjuf** [endless-sky/endless-sky#5435]
In the "Intro [2 Transport]" mission in the [intro missions.txt](https://github.com/endless-sky/endless-sky/blob/master/data/intro%20missions.txt) file a sentence is written in the past tense when it should instead be in the present tense. The sentence:

"As you made the final landing descent to the surface of Earth, Chuck and Sarah were staring out the window in rapt attention, pointing out landmarks on the planet's surface."

should be changed to

"As you make the final landing descent to the surface of Earth, Chuck and Sarah stare out the window in rapt attention, pointing out landmarks on the planet's surface."

 - OS: Devuan 3.0 Beowulf
 - Game Source: Downloaded from https://mentors.debian.net/debian/pool/main/e/endless-sky/ and compiled locally
 - Version: 0.9.12-1

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/2a1287db14615473b5643f56cdc7dc8d0b280459.
