### ISSUE TITLE
Can we submit new systems within pull requests?

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#544]
I'm not sure if that would get accepted. If not, how would I be able to add systems separately?

**Comment by endless-sky** [comment]
Human space is plenty big enough already, so if you're adding new systems, that will probably involve adding a completely new alien species. The best way is to probably start by creating a plugin with your new systems and aliens, then when the plugin reaches a certain state of polish it can get added to the main game.

Using the map editor, you can add new systems to the base map, save it as a different file (e.g. "modified map.txt"), and then use your favorite diff tool to pull out just the systems you added into a separate file for your plugin. For example on Linux or Mac OS X I would just do this:

`$ diff "modified map.txt" "map.txt" | grep "^<" | cut -b 2- > changes.txt`

**Comment by Thunderforge** [comment]
Perhaps this advice that human space is big enough (which I agree with) should be added to the contributing guide so that others can more easily see it?

**Comment by endless-sky** [comment]
Added a note in the roadmap to clarify how I expect the rest of the galaxy will be populated (i.e. a bunch of distinct "clusters" of systems of various sizes, one for each species, with no ordinary hyperspace links between different clusters.
