### ISSUE TITLE
Default government disabled hails to blank instead of friendly/hostile disabled phrases

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5442]
**Is your feature request related to a problem? Please describe.**
Currently, if a government does not specify any friendly or hostile disabled hails, it defaults to the phrases `"friendly disabled"` and `"hostile disabled"`.
https://github.com/endless-sky/endless-sky/blob/adc048a8e40c56e26e3e5892b77b2c01341a61c9/source/Government.cpp#L134-L138
This means though that if you don't want a new government to use these hails, you **need** to specify your own disabled hails for the government to use. An issue may also arise in the future should a total conversion plugin not define these hails.
Another thing to think about is how this behavior differs from the other hails. Why only fill in the friendly and hostile disabled hails with defaults? Why not other hails?

**Related Issue Links**
#5432 is related in the sense that the default behavior for a government should be what is most likely of a new government being added to the game.
#4549 referenced these default hails in the past and how it caused some strange behavior. We've since given custom hails to alien factions, but I still think this behavior of filling in the defaults should be looked at.
#4078 shows aliens using these default hails when they shouldn't be.

**Describe the solution you'd like**
Do not fill in the friendly and hostile disabled hails with a default value, instead leaving it blank. 

**Describe alternatives you've considered**
N/A

**Additional context**
Toward the concern of total conversion plugins perhaps not defining `"friendly disabled"` and `"hostile disabled"`, any such instance of the source code assuming that something exists in the game data should probably either be removed or otherwise documented as to not cause issues.

Removing these defaults will require that we fill in these hails for those governments that intentionally use them, that being all the human governments.

**Comment by bwright8** [comment]
I am new to the project, but can I work on this issue?

**Comment by Hurleveur** [comment]
> I am new to the project, but can I work on this issue?

Very late response, but sure anyone can work on any issue and make it a PR, thats open source for you!
