### ISSUE TITLE
Give ship command breaks when giving multiple ships of the same type.

### ISSUE THREAD

**Issue by AzureNyoki** [endless-sky/endless-sky#5447]
**Describe the bug**
The give ship command doesn't work to give multiple ships of the same type.
While working on #5444 i tried to make use of it to give the Emerald Sword and 6 Fighters.
When i attempted to give all 7 ships on the same mission, only the emerald sword and the last fighter were given.
When i attempted to give the emerald sword and a fighter on the first mission, and more fighters on different missions, the first fighter that was supposed to be given along with the emerald sword wasn't given.
I've come up with a workaround by using 7 different missions, but something isn't right with the code.

**To Reproduce**

See the linked PR. My first attempt was, on a single mission:

```
on offer

		give ship "Emerald Sword (Fixed)" "Emerald Sword"
		give ship "Demonheart" "Discount Flak Round"
		give ship "Demonheart" "How Do I Steer"
		give ship "Demonheart" "An Implicit Comparison To Fleas"
		give ship "Demonheart" "Punch Biopsy"
		give ship "Demonheart" "Just The Letter H"
		give ship "Demonheart" "I Got The Bees You Need"
```
This resulted in only the "Emerald Sword" and "I Got The Bees You Need" being given. The second attempt was:
mission 1:
```
on offer
		give ship "Emerald Sword (Fixed)" "Emerald Sword"
		give ship "Demonheart" "Discount Flak Round"
```
mission 2:
```
on offer
		give ship "Demonheart" "How Do I Steer"
```
with subsequent missions giving the other ships. This resulted in "Discount Flak Round" not being given.

**Expected behavior**
All ships should be given in a single mission, regardless of being the same type.

**System:**
 - OS: Windows 10 Pro, version 1903 build 18362.1082
 - Game Source: Continuous
 - Version: commit hash 2a1287d

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/5cf1bfc9d660faaff33cee23693f8c20226b195b.
