### ISSUE TITLE
Allow for more wormhole mechanics by defining wormholes separately from normal objects

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5457]
**Is your feature request related to a problem? Please describe.**
Currently, wormholes are simply two or more objects of the same name in separate systems. Wormholes are always two-way, unless you give one of the wormholes no sprite. More than two wormholes of the same name always link to each other in a looping fashion (see the Ember Waste).

There is little control over the behavior of a wormhole, but in order to add new mechanics to wormholes, we would currently need to add those mechanics to all objects as well, or at least the mechanics would need to be a child of object and be ignored if the object is not also a wormhole.

**Related Issue Links**
N/A

**Describe the solution you'd like**
Instead of defining wormholes as objects, define them as wormholes. Wormhole nodes of a system could have attributes that an object could not, while having the same properties that objects have.
```
system <name>
	...
	wormhole "Alpha Wormhole"
		sprite <path>
		distance <x>
		period <x>
		[offset <x>]
		<wormhole properties>
```

**Describe alternatives you've considered**
Instead of having a different root name, perhaps we could create a `wormhole` child of `object`, similar to a `weapon` child of `outfit`, that defines additional wormhole behavior.
```
system <name>
	...
	object "Alpha Wormhole"
		sprite <path>
		distance <x>
		period <x>
		[offset <x>]
		wormhole
			<wormhole properties>
```

**Additional context**
This issue is more about making wormholes a distinct class separate from objects than what exactly we would do with that. 

One suggestion was to have an `exit` keyword that defines which other wormhole a specific wormhole leads to. This would mean that wormholes would no longer share names in order to define themselves as such, and would also allow more control over how multiple interconnected wormholes act. One could perhaps have three wormholes that all lead to a single wormhole, but that single wormhole leads to somewhere entirely different, instead of requiring that interconnected wormholes create a loop. One could also create unidirectional wormholes by omitting any such `exit` keyword. 

Another suggestion was for a `linked` keyword that defines a wormhole as showing a link on the map, as opposed to the current behavior of a wormhole needing a planet with a description in order to show a link.

These are ideas to discuss after any change in the syntax of wormholes as a whole, though, although any such discussion should come shortly after that is done since an attribute like `exit` changes the behavior of how we'd define wormholes.

**Comment by ravenshining** [comment]
A clarification of my `exit` suggestion:

`exit` would be a child attribute of any object in a system, and could specify any object as a destination.  If the destination did not have its own `exit` attribute, that would make the wormhole one-way.  Omitting the `exit` attribute from an object just means that is a normal object and not a wormhole.

Example of a one way link:
```
system Foo
	pos -1024 1024
	object "One-Way Wormhole"
		sprite planet/neptune
		distance 777
		period 42
		exit "Not a Wormhole"

system Bar
	pos 1024 -1024
	object "Not a Wormhole"
		sprite planet/oberon
		distance 77
		period 7```

**Comment by warp-core** [comment]
Does the merging of #6132 complete this?

**Comment by quyykk** [comment]
Pretty sure it does yeah
