### ISSUE TITLE
(personal)  help request

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#548]
need someone to help me diagnose what is wrong with my Code::Blocks

Posted on forum, has stagnated for 13 hours with no replies

Step 1: Downloaded Code::Blocks from the link provided

Step 2: Downloaded Mingw-64 from the link provided

Step 3: Downloaded  win64-dev.zip from the link provided

Step 4: (Everything is finished downloading at this point) I installed Code:Blocks using all recommended features (I didn't untick anything.)

Step 5: I copied mingw64 from x86_64-5.2.0-release-posix_seh-rt_v4rev0.7z into my Program Files folder

Step 6: I started Code:Blocks

Step 7: went to Settings/Compiler/Toolchain executables and tried autodetect- it wasn't having it.

Step 8: Manually linked everything from C compiler to Make program to the files in the mingw64 folder.
(this seemed to work as it gave me no infuriating error in the bottom right. I became hopeful)

Step 9: Found EndlessSky project file in the folder I downloaded (endless sky master) and brought it to Code::Blocks. It had two subfolders; Sources and Headers.

Step 10: Pressed Build- compile current file. This showed up [Nothing to be done (all items are up-to-date).]

Step 10: Pressed Build instead- got 1 black line and 8 red lines telling me things aren't in the dev64 folder that are supposed to be (I forgot to paste them in c:/ pasted them there at this point)

Step 11: pressed Build again, things slowly started to come up in black writing, most with debug\source\(name).

Step 12: Scream in frustration as two red lines come up telling me that I don't have libopeng132.a and libmingw32.a

Step 13: Manually download those online and create a special directory just for them

Step 14: Still gives same error (wtf.jpg)
 
Step 15: Restart Code::Blocks

Step 16: Actually find those two files in the directory I'M TELLING BLOCKS TO LOOK IN

Step 17: Put them in special directory so Blocks can find them

Step 18: Same two errors, feel like giving up at this point

Step 19: Restart Blocks 3 times in a row and scream the whole time (I am losing my mind at this point)

Step 20: Wall of red text telling me about undefined references to a ton of stuff that looks important (this is what was happening last time)

Step 21: Ages of spammed red text with little speckles of black text intermixed

Step 22: Fail with 11255 errors and 128 minutes

**Comment by endless-sky** [comment]
Are all the libraries, etc. unpacked into either C:\dev32 or C:\dev64?

Can you post your .cbp file to show what paths you've changed?

**Comment by thenerdfreak** [comment]
where would I find said .cbp

**Comment by thenerdfreak** [comment]
If you mean .cbp as in the endless sky file I haven't changed anything in it, i've just been trying to compile and build it, but here it is in case it's something I don't understand 
[New Compressed (zipped) Folder.zip](https://github.com/endless-sky/endless-sky/files/74563/New.Compressed.zipped.Folder.zip)

**Comment by thenerdfreak** [comment]
this is an example of one of the errors it spams 
C:\Users\Jason Clark\Desktop\endless-sky-master\source\Account.cpp|200|undefined reference to `__ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc'|

**Comment by endless-sky** [comment]
What version of MinGW are you using? And do the libmingw32.a and libopengl32.a paths in the .cbp file match where those libraries actually exist on your system?

Also, why did you have to manually add things to the dev64 folder? Did you not unpack all the zip file contents into that location?

**Comment by thenerdfreak** [comment]
On the forum, there are links to everything I downloaded, i was extremely specific there

**Comment by thenerdfreak** [comment]
x86_64-5.2.0-release-posix_seh-rt_v4rev0.7z This?

**Comment by endless-sky** [comment]
Do all these patch from your EndlessSky.cbp file exist? If not, you need to change the paths.

```xml
<Compiler>
	<Add option="-std=c++11" />
	<Add option="-Wall" />
	<Add directory="C:/dev64/include" />
</Compiler>
<Linker>
	<Add option="-Wl,--subsystem,windows" />
	<Add option="-lwinmm" />
	<Add library="C:\Program Files\mingw64\x86_64-w64-mingw32\lib\libmingw32.a" />
	<Add library="C:\dev64\lib\libsdl2main.a" />
	<Add library="C:\dev64\lib\libsdl2.dll.a" />
	<Add library="C:\dev64\lib\libpng.dll.a" />
	<Add library="C:\dev64\lib\libturbojpeg.dll.a" />
	<Add library="C:\dev64\lib\libjpeg.dll.a" />
	<Add library="C:\dev64\lib\libopenal32.dll.a" />
	<Add library="C:\dev64\lib\libglew32.dll.a" />
	<Add library="C:\Program Files\mingw64\x86_64-w64-mingw32\lib\libopengl32.a" />
	<Add directory="C:/dev64/lib" />
</Linker>
```

**Comment by thenerdfreak** [comment]
How would I check those?

**Comment by thenerdfreak** [comment]
OH they all link to something called posix-dwarf

**Comment by thenerdfreak** [comment]
I changed all of them to the correct location of the files, and it still spams red everywhere when I press build. a lot of undefined things: 
C:\Users\Jason Clark\Desktop\endless-sky-master\source\AI.cpp|399|undefined reference to `Ship::IsDestroyed() const'|
