### ISSUE TITLE
Please mention that nukes are one-shot

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#55]
In data/weapons.txt, outfit "Nuclear Missile", please mention in its description that it's an one-shot weapon, unlike every other missile system.

**Comment by endless-sky** [comment]
Added a note to the weapon description (6d9acbd).

**Comment by kilobyte** [comment]
Just a matter of wording: perhaps changing "disappear" to "are expended" would be better?

**Comment by endless-sky** [comment]
I changed it (02135ed) to say, "Nuclear missiles are a one-shot weapon: each missile occupies a gun slot, and after it is fired, the slot it was in is left empty."
