### ISSUE TITLE
Proper path for Hit effects?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#550]
I have a pink laser and normal hit effects (laser matches up fine even when renamed) but I can't get the normal laser hit effects to match (gonna get them to match before I edit them to make sure you actually can)

I tried  "hit effects" "(name of the file)"
i tried "hit effects" "effect/(name of the file)"
i even tried "hit effects" "beam (name of the file)"
and  I tried "hit effects" "effect/beam (name of the file)"

can you create new hit effects? 
is this also an issue with the negative damage value?

Also: i noticed the hit effect for the Beam laser is "hit effect" "beam laser impact"
however I can not find "beam laser impact" in any of the image folders" and yet the beam laser still works.

**Comment by endless-sky** [comment]
It's "hit effect" singular, not "effects" plural.

The name has to match an "effect" data entry - for examples you can look at effects.txt. That entry specifies what sprite the effect uses, how long it lasts, what sound it makes, etc.

**Comment by thenerdfreak** [comment]
it's singular in my datafile, i derped (i wrote from memory, didn't c/p) will check on that effects.txt. But why not just have it like the projectile is? is there something weird about it?

**Comment by thenerdfreak** [comment]
Thanks! I got the custom effect to work
