### ISSUE TITLE
issue with cargo

### ISSUE THREAD

**Issue by R512-0** [endless-sky/endless-sky#5506]
I have an issue with the cargo space. I landed on a planet, accepted some missions and got a negative ammount of free cargo space. The ships i have should have enough space. The planet has no outfitter, so it is not possible, that some of the cargo space changed. As far as i know it should also not be possible to accept a mission without enough cargo space. I have no other trading-stuff on the ships. I can not explain why that happend.
Version: 0.9.12: Stable release
SaveFile:
[Name.txt](https://github.com/endless-sky/endless-sky/files/5545028/Name.txt)

**Comment by InfiniteDonuts** [comment]
Did you park one of your ships? If you park them after accepting missions and/or buying cargo, it will create negative cargo space.

**Comment by R512-0** [comment]
> Did you park one of your ships? If you park them after accepting missions and/or buying cargo, it will create negative cargo space.

Ohh. The problem is, that they are in an other star system. But how is this possible. As you described it should not be possible to take of with only one ship keeping the jobs.

**Comment by beccabunny** [comment]
https://github.com/endless-sky/endless-sky/issues/1624
