### ISSUE TITLE
Effects are mirrored in-game

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#5508]
**Describe the bug**
Effects are mirrored ingame. This usually doesn't have much of an impact on gameplay, however, the Void Sprite death effects end up being inaccurate to the image.

**Expected behavior**
Effects should not be mirrored.

**Screenshots**
Note that the left side has the long tentacle:
![image](https://user-images.githubusercontent.com/60202690/99372514-fe22ba80-290b-11eb-8bc9-3c97766bfc1a.png)

Now the right side has the long tentacle:
![image](https://user-images.githubusercontent.com/60202690/99372532-07138c00-290c-11eb-8142-9fa68866af3a.png)

**Comment by oo13** [comment]
This change seems to correct it, but I don't know exactly how a shader works.

```diff
diff --git a/source/BatchDrawList.cpp b/source/BatchDrawList.cpp
index 8a8c66c1..5acc3b70 100644
--- a/source/BatchDrawList.cpp
+++ b/source/BatchDrawList.cpp
@@ -130,15 +130,15 @@ bool BatchDrawList::Add(const Body &body, Point position, float clip)
        Point uh = unit * body.Height();
        
        // Get the "bottom" corner, the one that won't be clipped.
-       Point topLeft = position - (uw + uh);
+       Point topLeft = position - (- uw + uh);
        // Scale the vectors and apply clipping to the "height" of the sprite.
        uw *= 2.;
        uh *= 2.f * clip;
        
        // Calculate the other three corners.
-       Point topRight = topLeft + uw;
+       Point topRight = topLeft - uw;
        Point bottomLeft = topLeft + uh;
-       Point bottomRight = bottomLeft + uw;
+       Point bottomRight = bottomLeft - uw;
        
        // Push two copies of the first and last vertices to mark the break between
        // the sprites.
```
