### ISSUE TITLE
Mobile Outfitter(ship)

### ISSUE THREAD

**Issue by neevok-eu** [endless-sky/endless-sky#5513]
It would be a nice addition to the game if you could buy/make/hire a ship that can function as a mobile Outfitter. Bringing the ship to a system without an outfitter would enable you to temporarily have an outfitter option there.

Perhaps this can be accomplished by creating such a ship yourself or it would be possible to hire such a ship from a government.

Possibly additionally, if this ship would have a docking(landing) option it could have a limited shipyard as well. Selling for instance the 3 starting ships. 

If it has a fighter and a drone bay it could also pick up these ships if they are stranded in a system (and/or for self defense)

In a real universe there would be a market for something like that.

**Comment by Zireael07** [comment]
How would you balance that ship? I can't see it being balanced, except if maybe it was an end-of-questline reward like the cloak?

**Comment by Zitchas** [comment]
Having the ability to do outfitting in space is something that many have requested, but it will require a significant amount of game engine code to enable. It won't be a simple matter of tweaking an outfit or ship.

Definitely, though, it is something that the Korath Exiles definitely would have. Wanderers and Remnant are probably strong candidates for at least being able to benefit/want such a thing too.

**Comment by petervdmeer** [comment]
If we would do this, then I would prefer to have some outfits marked as "in space installable" instead. So you don't bring a mobile outfitter, but you just carry the outfits to install in cargo and install during boarding (similar to how plundering works, but in the opposite direction).

**Comment by Zitchas** [comment]
I'd opt for a three tier system: 
1) Some outfits can be installed / uninstalled in flight.
2) Some outfits can be installed / uninstalled in flight, but only with a special outfit. (Basically, this would be the "Mechanic's Bay" outfit or something like that)
3) Not installable in flight.

Personally, *most* outfits should be in category 2. Particularly big/special outfits are category 3; and only particularly small and/or extremely simple outfits should be type 1. Basically, the only things that should be type 1, in my view, are those outfits that you could reasonably see people pulling around by hand and installing manually.

Although that does bring up idea 4: Virtually everything should be *uninstallable* in flight. If I can pull it out of another ship while I'm boarding it, I certainly should be able to pull it out of my own, right? Perhaps have an alternative pull down menu on the ship info screen where we could choose to disable outfits on our ship, or fully uninstall them. (and of course, reactivate.)

Shutting down and starting up components in flight is a staple of Sci-fi. And could be extremely useful once System Hazards is merged: Fly into a system with, say, high heat. So you quickly pull up your ship info, and start disabling all your non-essential heat-producing things. Perhaps disable all your engines except for a tiny pair of ionics that you've kept installed just as a backup system. Maybe even kill your reactor and just run on battery to prevent heat build-up.

That'd add some fun challenges and decision making to the game!

**Comment by Red-57** [comment]
on a slightly different note, if system hazards do get merged, then there should be a way to disable your outfits without fully uninstalling them. This could be useful if you don't have a mobile outfitter but want to cut away a little more heat. In star wars at least, the crew are always turning their systems on and off and it seems like that wouldn't be that hard.
Another use for the this would be early game pirate farming. you could fool pirates into thinking that you were unarmed and then surprise them with your fully armed medium warships.

**Comment by InfiniteDonuts** [comment]
This would definitely be an Exile thing, probably incorporated into the Worldship (think the Yuuzhan Vong worldships in Star Wars). It would be a practical addition to the game, because... really, if you're skilled with ship repair, why can't you move some outfits around yourself instead of needing an outfitter?

I like the idea of disabling systems, but NOT for farming, it would affect balance too much, pirate ship capping is already powerful as it is. Pirates would have to be able to detect offline weapons.

**Comment by InfiniteDonuts** [comment]
> it could have a limited shipyard as well
Sounds like the Star Forge.

**Comment by Just-Visiting-Earth** [comment]
> I'd opt for a three tier system:

    1. Some outfits can be installed / uninstalled in flight.
    2. Some outfits can be installed / uninstalled in flight, but only with a special outfit. (Basically, this would be the "Mechanic's               Bay" outfit or something like that)
    3. Not installable in flight.




**Category-Item-Suggestions** [List could also be useful regarding a mobile outfitter concept]

**[[[[[[[ List is incomplete. Will finish tomorrow ]]]]]]]]]]]]]]]]]]**

**Category 1**

**Docking points at the hull**
One way to install outfits in flight is to have certain standardised docking ports on the ship hull where e.g. a radar scanner dish can be mounted / un-mounted within minutes. Or external fuel pods that can be connected on the outside.

**Items where in flight installment could make sense this way**; **All Scanners** and **All Jammers**, **fuel pods**, some lower tier weapons (**B. Laser**, **E. Blaster**, **Flamethrower**, **Gatling**,..?), **Missile Launchers** (?), **Quantum Key Stones**, **Armageddon Core** (Just kidding!), x...

**Other Items that probably should be in that category**: First and foremost **Bunk Rooms** and **Luxury Accomodations**! One jump takes a whole day. 'nuff time for a couple handymen to refurbish a broom closet or rip out some wooden fixtures: also **Brigs**, **Photovoltaic Arrays**, **Cargo Expansions**, **Missile Racks**, **Batteries**, **Crystal Capacitator**, **Super Capacitor**, **Surveillance Pod**, ...


**Category 2**

In total it feels like almost anything related to energy and cooling is so sensitive or interwoven with the rest of the ship that it can only be installed in a dock / outfitter. Same goes for System Cores.
Reactor types that most likely seem to be able to be safely installed in flight are **Fuel Cells**, **Radiothermal**, **Nucleovoltaic**, maybe even **Dwarf**  / **Pebble Core**.
For Cooling: **Cooling Ducts**?


**Category 3**
Any weapon systems whose efficiency heavily relays on the ability of calculating slightest angles and trajectories (**Any Big Lasers**, and unguided projectile weapons), **all big cooling installments**, **all big reactors**

**Items, where I'm not sure**
- **Command Center** (What sense does it make anyway, installing it inflight, if flagships can only be switched on the surface?)
- **Interference Plating**. Depends if one unit of IP is coating the whole ship (which seems unlikely. Only 50k to coat a Bactrian?) or if you rather add them like puzzle pieces or stack them on sensible areas. Coating a whole spaceship in flight would call for Category 2 or 3. Just slapping one more Junk of that shiny foil on your ship is a clear Category 1

**Comment by ThrawnCA** [comment]
> Having the ability to do outfitting in space is something that many have requested, but it will require a significant amount of game engine code to enable. It won't be a simple matter of tweaking an outfit or ship.

Would it be simpler to have something - a ship, or perhaps an outfit - that could give an Outfitter interface while _landed_, on a planet that otherwise wouldn't? An interface with nothing for sale by default, and all prices zeroed, but otherwise it could all work the same as usual.
