### ISSUE TITLE
Allow conditions to be saved and accessed across/outside of pilot save files

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5517]
**Is your feature request related to a problem? Please describe.**
Save files are currently all independent from each other, saving their own conditions with no affect on other save files. It might be the case though that we want to have things change depending on if a player has done something in another save file before. For example, perhaps the Drak/Archons or Pug break the 4th wall and know that a player has gone through something X times before in other save files. 

**Related Issue Links**
I originally had this idea in relation to #1519 back when I opened that, but with that issue seemingly being within reach thanks to #5512, I figured I should open an issue on this idea.
The most obvious use of this mechanic in relation to choice starts, at least to me, would be to activate new starts based off of the player’s knowledge from past save files. For example, say the player does a lot of missions in Hai space, unlocking a Hai space start location, as we obviously wouldn’t want a Hai start available to a brand new player. This would otherwise be impossible if we didn’t have a way to access information across save files. 

**Describe the solution you'd like**
Create some sort of “universal save file” that consists of only a list of conditions. This universal save file is either the sum of all conditions across all active save files (with deleted saves not subtracting from the universal file), or we create some keyword for missions to write conditions to this universal save file (which I imagine would be cleaner but would result in achievements not being retroactive).

**Describe alternatives you've considered**
None. 

**Additional context**
Issues on achievements come to mind. While we’ve discussed the problems with having Steam achievements, I don’t see why we couldn’t have in-game achievements that are tracked on the main menu somewhere, e.g. “Complete the main plot”, “Achieve a net worth of 1 billion credits”, stuff like that. If we had some sort of “universal conditions file” that saved certain changes from all save files, then any sort of in-game achievements menu would read from this file to see what the player has accomplished. 

For the sake of plugins not ruining the achievement system, perhaps we could also somehow toggle on/off a file saving conditions to the universal file, e.g. starting a file with an all-content plugin active disables the ability to gain achievements, similar to how game with cheat modes will disable achievement progress when cheats are active. (This behavior would obviously be activated by the all-content plugin and not be something we force on plugins.)

**Comment by petervdmeer** [comment]
Nice idea. Reminds me of the Bones files in Nethack (https://nethackwiki.com/wiki/Bones).

**Comment by tehhowch** [comment]
This more or less ties into associating with a specific "user account." I think we already use OS-user-specific directories via the SDL filesystem calls, but haven't verified the behavior with e.g. a "system install" and multiple users. I'm not sure how we would want to handle this in the presence or lack thereof of a non-os user, e.g. a Steam account.

I'm not interested in adding any achievements to the game, but agree that a way to measure a specific player's "game comprehension and knowledge" could be valuable.

**Comment by Amazinite** [comment]
An idea that I just had that would be reliant on this: an "announcement" root node that displays conversations/dialogs on the main menu at game start. Example of how this could look and be used:
```
announcement "Unlocked Hai Start"
	to announce
		has "First Contact: Hai: offered"
	on announce
		(conversation | dialog)
			`Congrats. For discovering Hai space, you have unlocked the ability to start the game in Hai space.`
```
Would write a "Unlocked Hai Start: announced" or similar condition to the universal file as to not show it again.
Reason for wanting this: displaying "announcements" on the main menu is a simple way of giving 4th wall breaking information to the player without ruining immersion. The alternative would be to have missions that display this same information, which would be odd to get such announcements while in the middle of playing.
