### ISSUE TITLE
Have anti-missiles define how long it will take for the projectile to travel so that the target doesn't die randomly

### ISSUE THREAD

**Issue by Red-57** [endless-sky/endless-sky#5519]
**Is your feature request related to a problem? Please describe.**
If one wanted to make a super over-powered anti-missile system that used ammo to operate and fired a projectile to hit it's target, the target would die on the first frame, and even if the firing effect continued on the target would be dead already.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
If the anti-missile could specify how many frames it would take to travel than you could introduce a more complex effects and weapons, such as anti-missiles that used ammo.

**Describe alternatives you've considered**
the current system of beams is nice but having some anti-missile missiles would be cool

**Comment by Amazinite** [comment]
Spoke about this on Discord. Sounds to me like this idea won't work out as expected, unless there's something I'm still not understanding about it.

**Comment by Red-57** [comment]
Yeah projectiles tracking projectiles would be a hassle, cool, but too complicated.
