### ISSUE TITLE
Possibility to sort the missions in the "Available Missions"-List by type of mission

### ISSUE THREAD

**Issue by Just-Visiting-Earth** [endless-sky/endless-sky#5529]
Sometimes I'm bored or want to try something else and switch my income-source to purely transporting people.
Sometimes I accept every single shuttle-mission and watch how everywhere in the galaxy little flowers of duty start to bloom :)

Anyways... these are the times when it's the most obvious to me that being able to display the missions sorted by their types (cargo, transport, bounty, etc.) would immensely increase the levels of "workflow" possible ingame.

Something like this:

-------------------------------------------------------------------------------------------------
Transportation:
------------------------
Colonists to Hestia
Transport Family to Millrace
Transport Family to Norn
Passenger Transport to Flood
Bring tourists to Earth

Cargo
------------------------
Bulk Delivery to Holland
Delivery to Bourne
Large Rush Delivery to Sunracer
Large Rush Delivery to Maelstrom

Bounty
-------------------------
xxx
xxx
xxx
xxx

[Also maybe faction-specific and storyline-quests]
Mystery
--------------------------
xxx
xxx

Scientists
--------------------------
xxx

-------------------------------------------------------------------------------------------------

Right now, I manage by quickly scanning up and down the lists for certain keywords in the mission title typical for the missions I'm looking for. But it takes "brain capacity" and time that could be better invested somewhere else, if the missions would be somehow sortable.

I'd really appreciate it as a useful improvement if I would have the possibilty to either sort the missions list by the amount of payment it offers or if the payment is shown directly.

In general it feels, that the game would be a really nice economic simulator - with enough depths to have pen and paper besides the laptop, scribbeling down charts and calculations - if there would be easier access to data regarding prices, profits, payments, cargoloads, passenger number. That would probably require a complete re-design of the mission list and a more chart-like approach towards the selection of missions. (but this is not, what this suggestion is mainly about)

It would be a more than enough improvement to be able to look at a mission list with sorted mission types.

Imagining a big and hummingly busy commercial space port hall with a lot of different screens  and mission offers it seems natural that there are different areas for different kind of work. 
A "terminal" for all the pilots from the Transportation-Business, where intergalactic coach drivers sit in couches and drink coffee whilst sharing experiences about passengers. 
Another "Terminal" where you see a lot more bearded Lumberjack-type of guys, friendly insults fill the air, the smell of oil is omnipresent.. this gotta be the cargo job board section! Yeah, there's the bar...
And there's another section, not as big and bright as the others and also not as easily to find. If you're able to stay here longer than five minutes, chances are high that the average person perceives you as a pretty tough guy. Here are the bounty hunters... No matter where you stand here, you always kinda feel observed and can't say with certainty if it's from somewhere in the crowd or from one of the dimly lit corner lounges, where headhunters and mercs alike sit and share intel or plan the next engagement in hushed voices.
It kinda feels to me that our (hopefully spacefaring) succesors would not completely stray away from group building and sorting things by their kind.

Is there a good reason for the lists being like they are, that I just can't see right now?

I searched a bit,whether someone already made a request like this but didn't found anything. Sorry if Re-Post!

[rather a gag than a serious suggestion:]
Probably useless for most but fun for certain play styles would be a button "Accept All" for each section. [maybe acceptance order from most to least people (for e.g. in transport section) or from most to least income]. But that's rather an easter egg, because hitting that button on a few planets in a row will make the task-management pretty chaotic pretty fast.

**Comment by tehhowch** [comment]
We ask that everyone follows the issue templates.

During a search for related issues, one is bound to find https://github.com/endless-sky/endless-sky/issues/236

**Comment by Just-Visiting-Earth** [comment]
But where is it?

**Comment by tehhowch** [comment]
That suggestion is where one would see activity. That it remains open, and has no recent comments, etc, indicates there has been no development activity on it.

This game is developed entirely by volunteers, and unless one volunteers to implement it in a manner compatible with the game's design, then the issue will remain open and the feature not implemented. If we decide it is a feature not worth having, that decision would be documented in that thread and then the issue closed.
