### ISSUE TITLE
Game runs at half-speed on next-gen AMD GPU with built-in kernel driver

### ISSUE THREAD

**Issue by samrocketman** [endless-sky/endless-sky#5531]
# Description

>  **WARNING: screenshots contain spoilers.** 

When GPU stats are enabled, GPU usage is average between 189-200%.  The game runs 50% slower on the newer AMD graphics card when compared to my older Intel graphics card.

~This seems very high for a GPU which was released in the past 12-24 months.  It plays other extreme gfx games on max settings so I am suspicious that it might just be a miscalculation.~

~Otherwise, gameplay seems smooth.  I don't know how to report FPS.~

<details><summary><b>Screenshot of the issue</b> (click to expand)</summary>

---

![Screenshot from 2020-12-04 15-35-09](https://user-images.githubusercontent.com/875669/101212764-4a2d6900-3647-11eb-926e-ffbfeb360a9d.png)

Please note, I have very few ships.

![Screenshot from 2020-12-04 15-40-30](https://user-images.githubusercontent.com/875669/101212850-67623780-3647-11eb-94f7-0a4876b92c4d.png)

</details>

---

# Reproduce

Open the game preferences, enable show cpu/gpu stats, and play normally.  GPU usage is consistently high (189% minimum or higher).  Both in ports and while exploring space.  It's also consistent whether I enable CAPS LOCK or not to speed up gameplay.

I've created several new pilots and games; the problem seems reliably reproducible.

# Expected behavior

I would expect  usage to be <100% (I've seen other users post screenshots with 2-3% GPU usage so I would expect that for a  modern AMD GPU).

# My hardware and environment

* CPU: Intel core i7
* Video card: [AMD Radeon™ RX 5700 XT](https://www.amd.com/en/products/graphics/amd-radeon-rx-5700-xt)
* Ubuntu 18.04.5 LTS
* Linux 5.4.0-53-generic x86_64

<details><summary><b>Additional details</b> (click to expand)</summary>

---

I force `TearFree on` for a smooth video experience.  I'll try turning it off and report my results.

```
xrandr --output DisplayPort-4 --set TearFree on
```

VGA controller and driver information.

```bash
# lspci -vmmk -d ::0300

Slot:	03:00.0
Class:	VGA compatible controller
Vendor:	Advanced Micro Devices, Inc. [AMD/ATI]
Device:	Device 731f
SVendor:	ASRock Incorporation
SDevice:	Device 5103
Rev:	c1
Driver:	amdgpu
Module:	amdgpu
```

</details>

---

# Game Source

Steam with Hi DPI DLC enabled.  I'm not using any other plugins.

* https://store.steampowered.com/app/404410/Endless_Sky/
* https://store.steampowered.com/app/404800/Endless_Sky__High_DPI/

Endless Sky 0.9.12

**Comment by samrocketman** [comment]
There's no change in % GPU  usage when I turn off TearFree.

```
xrandr --output DisplayPort-4 --set TearFree off
```

**Comment by samrocketman** [comment]
Side note; if you like how I formatted this issue I can contribute an update to the issue template.

**Comment by MCOfficer** [comment]
It should be noted that ES's built-in load monitoring isn't super accurate. Is there any other tool that can confirm these observations?

**Comment by samrocketman** [comment]
I'm not sure; if someone has a suggestion I can run it and report results.  I'm comfortable on the CLI.

**Comment by samrocketman** [comment]
# GPU metrics

I found `radeontop` https://github.com/clbr/radeontop

Initially I ran `radeontop` but it couldn't detect my card.  I had top compile it from source.

<details><summary><b>Gritty compiling details</b> (Click to expand)</summary>

---

Well, for completeness I built from source with `make amdgpu=1 xcb=1` from the README and it works.   I'm on Ubuntu 18.04 and the vanilla package from repositories does not work without recompiling `radeontop`.

Here's my development  `Dockerfile` based on my OS... if a user is using another OS then  they should use a different docker  image tailored for them.

```
git clone git@github.com:clbr/radeontop.git
cp Dockerfile radeontop/
cd radeontop/
docker build -t rad .
docker  run -it  --rm -v "$PWD":/home/sam/radeontop rad
```
Which compiles it in the container for my OS (Ubuntu 18.04).  Then, `sudo ./radeontop` works for my AMD Radeon 5700 XT.  Worth noting that I already installed radeontop from the package manager so the runtime prerequisites were already satisfied.  I used Docker to provide a quick compiling environment so that I could easily clean up my system by just deleting the dev container.

<details><summary><b>Source code of my Dockerfile</b> (Click to expand)</summary>

---

```dockerfile
FROM ubuntu:18.04

RUN set -ex; \
DEBIAN_FRONTEND=noninteractive adduser --quiet sam

RUN set -ex; \
apt-get update

RUN set -ex; \
apt-get  install -y sudo; \
echo 'sam ALL=NOPASSWD: ALL' > /etc/sudoers.d/sam

RUN set -ex; \
apt-get install -y git vim

RUN set -ex; \
apt-get install -y make gcc pkgconf libdrm-dev libncurses-dev libpciaccess-dev libxcb1-dev libxcb-dri2-0-dev

USER sam
VOLUME /home/sam/radeontop
WORKDIR /home/sam/radeontop
CMD make amdgpu=1 xcb=1
```

</details>

---

Cleaning up and deleting my dev environment I ran the following commands...

```
docker rmi rad
docker image prune
```

</details>

---

I ran `sudo ./radeontop` and took some screenshots.

# Screenshots

<details><summary><b>Screenshot before running the game</b> (Click to expand)</summary>

---

![Screenshot from 2020-12-04 19-48-37](https://user-images.githubusercontent.com/875669/101229182-08171e00-366d-11eb-835e-179ceb19cd8c.png)

</details>

---

<details><summary><b>From inside of planet port</b> (Click to expand)</summary>

---

![Screenshot from 2020-12-04 19-49-39](https://user-images.githubusercontent.com/875669/101229194-149b7680-366d-11eb-9ee5-aa1cdd7c0c6d.png)

</details>

---

<details><summary><b>Leaving port flying in space</b> (Click to expand)</summary>

---

![Screenshot from 2020-12-04 19-49-56](https://user-images.githubusercontent.com/875669/101229199-1feea200-366d-11eb-8917-b550729fcef9.png)

</details>

---

<details><summary><b>Over 5 minutes flying in space</b> (Click to expand)</summary>

---

![Screenshot from 2020-12-04 20-04-04](https://user-images.githubusercontent.com/875669/101229206-29780a00-366d-11eb-9165-070edc563516.png)

</details>

---

**Comment by Amazinite** [comment]
The CPU/GPU percentages shown are measured in 60ths of a second (the time of one frame) that it takes to calculate/draw a frame, so if you have an in-game GPU percentage over 100%, the game should be running at less than 60 FPS. If you say the game is running smooth though, I’m not sure why it would be reporting such GPU numbers.

**Comment by samrocketman** [comment]
Is there a way for the game to show framerate?  I didn't see an option for it.

**Comment by tehhowch** [comment]
The game doesn't show framerates, only a representation of how long a given frame took to process, as a percentage of the expected frame time. Showing framerate isn't really applicable in the current Endless Sky, since we assume and also cap to 60 fps. If we allowed a flexible flame rate, then showing it would make sense.

(It is a non-trivial change to allow an unlocked frame rate, since the game uses frames as the unit of time.)

For the GPU "load," the game is measuring how long it takes to execute the "tell the GPU to draw this stuff" code* for things that appear in-flight, e.g. ships, projectiles, visual effects, planetary object sprites, and planet labels. That duration is combined with 59 other durations (i.e. 1 second's worth of frames) and then multiplied by 100 to become the % load time. If it took 1/60th of a second to execute the "hey gpu, here's what you should draw" code, then the reported load would be 60 * 1/60 * 100 = 100%.

\* The `Engine::Draw` code that is measured also performs (what should be) [a small amount of image preloading](https://github.com/endless-sky/endless-sky/blob/ca078fab40c5c51b49d13f8183814c36acd002d1/source/Engine.cpp#L999-L1001); this should only be landscape images for your current system and shouldn't result in a persistently elevated measurement.

Given that you're on Ubuntu, you can easily try a [source build](https://github.com/endless-sky/endless-sky/blob/v0.9.12/readme-developer.txt) to see if Steam is the source of the issue. If you might wish to go back to the Steam version, I recommend you check out the v0.9.12 tag before building, as later commits changed how some content is serialized. (You could also exclusively use a different pilot.)

**Comment by samrocketman** [comment]
Then it seems there's an actual rendering issue with newer GPUs.  So it sounds like I'm literally viewing the game at half speed.

Hard to say; could be a kernel driver issue or game engine issue.  It think it makes sense to keep this open until more samples come from other people.

If there's something I can do to help debug I might need a little how-to but am capable of debugging with guidance.

**Comment by samrocketman** [comment]
I tried the latest continuous build and it behaves the same way (~190% GPU/0% CPU).

```
curl -LO https://github.com/endless-sky/endless-sky/releases/download/continuous/endless-sky-x86_64-continuous.tar.gz
mkdir es-cont
cd es-cont/
tar -xzf ../endless-sky-x86_64-continuous.tar.gz
./endless-sky
```

**Comment by samrocketman** [comment]
After trying it out on my Intel machine the game is _definitely_ half speed (much slower) on the AMD machine compared to the Intel machine.

Is the rendering engine doing any kind of detection for how fast a GPU is?  Using caps lock `>>` speed feels normal compared to the Intel machine.  Could the engine detect that GPU % is 200% and attempt to double the frame speed.  The GPU can definitely handle it.  I'm able to play multiple instances of endless sky with no stutter in any of the games.

Playing both continuous and normal ES at the same time... broke my save game but oh well.  Able to show I'm able to play two copies  of endless sky effortlessly.

<details><summary><b>Screenshots</b> (Click to expand)</summary>

---

GPU chugging along at almost no usage.

![Screenshot from 2020-12-07 14-39-47](https://user-images.githubusercontent.com/875669/101397117-480f1880-389a-11eb-8c1e-4c50dc184593.png)

While two copies of ES are playing side by side on the same computer.

![Screenshot from 2020-12-07 14-38-42](https://user-images.githubusercontent.com/875669/101397161-56f5cb00-389a-11eb-9c09-eaa07a3f5023.png)

</details>

---

My GPU shows negligible difference between 2 copies of endless sky running at the same time vs not running anything at all.  So could it likely be a rendering engine issue?

**Comment by samrocketman** [comment]
I tried playing with `void FrameTimer::SetFrameRate(int fps)` values but couldn't get the game to change behavior (game wouldn't slow down or speed up so I have no idea).

**Comment by samrocketman** [comment]
In steam, I'm able to show FPS counter and the FPS counter  shows 30FPS https://linuxhint.com/show_fps_counter_linux_games/

**Comment by samrocketman** [comment]
@tehhowch @MCOfficer @Amazinite 

# Solved

It was my problem (obviously :joy: ).

I ran `xrandr` and behold... my output says 30Hz at 4K resolution.

```
DisplayPort-5 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   3840x2160     29.98*+
   2560x1440     59.95  
   2048x1280     59.99  
   1920x1200     59.88  
   1920x1080     60.00    60.00    50.00    59.94    24.00    23.98  
   1600x1200     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08
```

On my dell monitor, I went to the phsical monitor settings and under `Display` my monitor has a `Response Time` setting (Normal or Fast) which was set to `Normal`.  I changed the hardware setting to `Fast` and ran xrandr again.

```
DisplayPort-1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   3840x2160     60.00*+  29.98  
   2560x1440     59.95  
   2048x1280     59.99  
   1920x1200     59.88  
   1920x1080     60.00    60.00    50.00    59.94    24.00    23.98  
   1600x1200     60.00  
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
```

Which now shows 60Hz (`3840x2160     60.00*+  29.98`).  I ran the game again and Steam showed 60FPS.  The Steam FPS  counter really helped narrowing it down to being a configuration problem on my end.

Apologies for the lengthy replies.

# Summary for this issue

The game expects to run at 60FPS so if your monitor refresh rate is slower, then the game becomes painfully slow.  As an **enhancement**, might be worth for the endless sky to support slower frame rates (30FPS instead of 60) but that's neither here nor there at this point.  Sounds like a lot timing-based changes would have to occur to support slower framerates.

**Comment by Zitchas** [comment]
Thanks for providing the in depth breakdown. I don't fully understand the technical details, but I suspect that having such detail makes it much more useful for our technical people to understand what is going on.

**Comment by samrocketman** [comment]
> Thanks for providing the in depth breakdown. I don't fully understand the technical details, but I suspect that having such detail makes it much more useful for our technical people to understand what is going on.

To put it another way:

The game expects to run at 60FPS.  Both my monitor and graphics card support 60 FPS but I had my monitor configured to run at 30 FPS.  Because of this, the game GPU calculations showed 200% (double what's possible) because the game was running at half speed (30FPS) when all gameplay calculations assumed 60FPS.  The net result was the game appeared to run slowly and the GPU showed up to 200% usage.

After I fixed my monitor misconfiguration the GPU usage stays around 40% or less usage.

**Comment by Amazinite** [comment]
In that case, this is actually a dupe of https://github.com/endless-sky/endless-sky/issues/3918.

**Comment by Zireael07** [comment]
IIRC it should be possible for SDL to query the monitor refresh rate and warn the user if he's not @ 60 fps for some reason?

**Comment by tehhowch** [comment]
I added a warning for a low monitor frame rate in c13300b1401fe90ea2fb5954a6f3515b6edcf1dc
