### ISSUE TITLE
Abort Mission Hotkey

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5534]
**Is your feature request related to a problem? Please describe.**
I noticed that there is no hotkey for aborting a mission, so I decided to suggest adding one.

**Related Issue Links**
Didn't find anything. I looked this time.

**Describe the solution you'd like**
I would like the key A to be used to bring up the menu for aborting a mission when you have in selected, and when you bring up that menu you could press O for okay and C for cancel. Pressing A would accept a mission like normal if you were on the available missions screen, and had an available mission selected, however if you had a current mission selected it would bring up the abort mission screen.

**Describe alternatives you've considered**
An alternative when you bring up the abort mission menu, instead of pressing O you could press A again but O makes more sense.

**Additional context**
You currently can move between selected missions with the up and down arrow keys, and move between current missions and available missions with the left and right arrow keys. I think it should be possible to complete the game without using a mouse.

**Comment by tehhowch** [comment]
This is an explicit decision to prevent accidental mission loss due to over-eager key presses.

**Comment by McloughlinGuy** [comment]
Yes but spamming the A key won't abort the mission it will jsut open the menu so long as the alternative isn't implemented.

**Comment by McloughlinGuy** [comment]
This has absolutely no reason to still be open. It is being closed.
