### ISSUE TITLE
Making dominated ex-pirate planets spawn less pirate fleets

### ISSUE THREAD

**Issue by ph2000** [endless-sky/endless-sky#554]
As you are now in control of that system, there should be less pirate fleets originating from it or (more difficult) the pirate fleets from that planet ignore you.

**Comment by bobafetthotmail** [comment]
Hmmm.... What about using the bribe mechanic?

If you dominated the planet, all pirates in the sector are auto-bribed for free when you jump in.

**Comment by brick96** [comment]
What about the the rest of the galaxy? Would you rather dominate a system and be safe in that system? Or should the government take action against you?

**Comment by johndh** [comment]
@ph2000 I'm not sure that "control" is really the right word.  It seems to me that they're just paying you to not be a pain in the ass anymore.  I don't know about you, but I don't have the millions of troops, artillery, etc., that it would take to actually conquer Earth.

@brick96 I've dominated every inhabited planet, moon, and station in the Republic except for New Tibet (who still won't fight me) and it does seem a little strange that I haven't suffered any consequences.

**Comment by natangold** [comment]
@johndh You're killing too many pirates. "Sure, dude conquered Earth, but thank Allah he keeps the Korath at bay."

**Comment by ph2000** [comment]
Maybe just some of the fleets that come in, fleets that could be "attached" to that system, if not just by saying 1/3 of the fleets in this system are suposed to be based on this system, so instead of having
"Pirate small fleet" 1600
you have 
"Pirate small fleet" 2400
"Pirate small fleet (neutral)" 4800
This would be part of the tribute: "We will pay you ... and our ships won't annoy you and you'll leave us alone"

**Comment by ph2000** [comment]
to refer to me please use @ph2000bis

**Comment by tehhowch** [comment]
This can be achieved by altering the stock fleet composition of a system from having a single particular stock fleet definition, to having multiple stock fleets with periods such that the initial period is met (i.e. 2 fleets with period 2X == 1 fleet with period X.
Then, a mission can be used to activate a GameEvent which uses the `remove fleet` syntax, and requires the player to have the given tribute condition in order to offer.
Example:
<details><summary>original system</summary>

```
system "Test"
    fleet "My Pirates" 400
```
</details>
<details><summary>altered, with mission to reduce spawn rates upon dominating</summary>

```
system "Test"
    fleet "My Pirates" 1600
    fleet "My Pirates" 1600
    fleet "My Pirates" 1600
    fleet "My Pirates" 1600

event "dominated Test's planet"
    system "Test"
        remove fleet "My Pirates"

event "released Test's planet"
    system "Test"
        add fleet "My Pirates" 1600

mission "Dominated Test Planet"
    landing
    destination "Some Planet"
    to offer
        has "tribute: SomePlanetInTestThatYouDominated"
    on offer
        event "dominated Test's planet"
    on accept
        fail

mission "Released Test Planet"
    landing
    destination "Some Planet"
    repeat
    to offer
        has "Dominated Test Planet: offered"
        not "tribute: SomePlanetInTestThatYouDominated"
    on offer
        event "released Test's planet"
        clear "Dominated Test Planet: offered"
    on accept
        fail
```
</details>
