### ISSUE TITLE
[windows] [bug] Game freezes and crashes when firing

### ISSUE THREAD

**Issue by issu-shooter** [endless-sky/endless-sky#5542]
**Describe the bug**
[Edited]Game will lag, freeze then crash when firing. Happened and tested on current windows build recently, Linux build could possibly has the same bug.

**To Reproduce**

[Edited]Steps to reproduce the behavior:
1. Install a weapon (I was using normal blasters, but others also do the job)
2. Depart into space and fire, don't hit anything (like an asteroid)
3. Keep pushing the fire button and the game will lag then freeze. Release the button Immediately then the game will continue like nothing happened. But if you keep pushing the fire button the game will crash. When the game crashes an err window says the game requested Micro$oft C++ runtime to end it

I tried creating a whole new captain, bought a sparrow and immediately launched it for testing. It turned out to have the same result. 

**Expected behavior**
This shouldn't happen:(
If energy production is lower than the requirements, we can either show an err message in the game and tell the player to stop pushing while force stop all power-needing activities, or reduce the gun/engine/shield charger's performance.

**Screenshots**

![IMG_20201211_002750](https://user-images.githubusercontent.com/62288691/101800422-39e62400-3b48-11eb-8e76-883db17c3673.png)

**System (please complete the following information):**
 - OS: Windows 10 Home, version 1909 build 18363.1198
 - Game Source: Steam and Github releases
 - Version: 0.9.12

**Link to save file**
later

**Additional context**
Found real factor

**Comment by Amazinite** [comment]
I'm not experiencing the described behavior of the game lagging out and certainly no issue with it crashing.

**Comment by issu-shooter** [comment]
I think it will happen when too much variables are changing.

And from my observance this usually happens when the battery is drained

**Comment by issu-shooter** [comment]
My computer is a ASUS TUF 7 laptop with AMD Ryzen 7 3759H, 8G DDR4 RAM and a GTX 1660 ti. I don't think this is caused by the hardware's performance.
And although this happened on my windows computer, I used to experience this on my GNU/Linux desktop too. It has much older hardware (AMD A10 6800K 8G DDR3 RAM + GTX 750 ti), but also runs most games fine. 
This bug? can be completely avoided if you use generators only as your ship's power source and the output completely covers the ship's needs.
 Anyway this is most likely to happen if you have a battery (drained), a solar panel and some weapon (that uses power), then you select some moving target and fire at it while keep thrusting.

**Comment by Amazinite** [comment]
There was just a new release. Can you replicate this behavior on v0.9.13? Since you're using Steam, you'll need to opt into the beat branch. Go to your Steam library > right click Endless Sky > Properties > Betas > select beta from the drop down box.

**Comment by issu-shooter** [comment]
Yeah, I have downloaded the beta version, will try it out soon (as long as I am free)

**Comment by issu-shooter** [comment]
Seems like it's fixed, bought a sparrow and everything works fine...? Will try out things further

**Comment by warp-core** [comment]
This doesn't seem to be a problem anymore, and it doesn't seem like there's enough information to be able to reproduce it anyway.
