### ISSUE TITLE
"Inscrutable" on a player ship should block scans from NPCs

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5544]
**Is your feature request related to a problem? Please describe.**
The "inscrutable" attribute on an NPC ship blocks the player from being able to scan the NPC in any way, including outfit, cargo, and tactical scans. This same behavior is not extended to the player through, as player ships with the "inscrutable" attribute are capable of being successfully scanned by NPCs.

**Related Issue Links**
N/A

**Describe the solution you'd like**
If a player ship is scanned and has the "inscrutable" attribute, the scan should always fail for the NPC.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vitalchip** [comment]
Is the intention to simply block fines arising from scans or to actually change the scan behaviour so that instead of "xxx ship completed its scan" to "xxx tried to scan you but failed"?  Does the AI ever make any use of any scanned information?

**Comment by tehhowch** [comment]
> Is the intention to simply block fines arising from scans or to actually change the scan behaviour so that instead of "xxx ship completed its scan" to "xxx tried to scan you but failed"?  Does the AI ever make any use of any scanned information?

The behavior should be the same as for the player scanning an inscrutable target: one learns nothing (and thus cannot fine the target). The player gets a dialog which indicates the scan returned nothing useful (which is naturally different than nothing or failure). This result distinction should be possible for the NPC, too.
