### ISSUE TITLE
Random system extremely far outside of both galaxies

### ISSUE THREAD

**Issue by northeast-eph** [endless-sky/endless-sky#5550]
**Describe the bug**
If a ship is equipped with a jump drive with a high enough range, while visiting some of the outermost Coalition systems or the Pleiades galaxy, a system can be seen indicated on the minimap that exists far outside of the Milky Way or Pleiades galaxies, located at approximately -10000 7000.

**To Reproduce**
1. Add a jump range of 20000 to a jump drive, or create a jump-capable outfit with a jump range of 20000
2. Visit one of the outermost coalition systems such as Four Pillars
3. Check the bottom left of the minimap to see a tick indicating a system in that direction
4. Visit one of the systems in the Pleiades galaxy
5. Check the left of the minimap to see a tick indicating the same system

**Expected behavior**
I would expect that there would be no systems located in that area.

**Screenshots**
![image](https://user-images.githubusercontent.com/64765233/102003273-1a6f0880-3cba-11eb-9964-3c7889be2f20.png)
![image](https://user-images.githubusercontent.com/64765233/102003494-1395c500-3cbd-11eb-8d66-a8df385a9dd4.png)
![image](https://user-images.githubusercontent.com/64765233/102003506-2f996680-3cbd-11eb-9e0f-ef36ba56adb3.png)

**System (please complete the following information):**
 - OS: 1st Machine: Windows 10 Pro Version 2004 Build 19041.630
        2nd Machine: Windows 10 Pro Version 1903 Build 18362.657
 - Game Source: Github
 - Version: Continuous Build 61ef361

**Link to save file**
[Test Save.txt](https://github.com/endless-sky/endless-sky/files/5684233/Test.Save.txt)
Should work with any save, possibly Windows only.

**Additional context**
While experimenting with the new jump range attribute, I noticed a system tick on the minimap that I could not identify while in the Pleiades galaxy. I checked multiple saves on two different machines with the latest continuous build, and found the tick on both. The first machine was a tower with the World Forge, Omnis, Ursa Polaris plugins, and a custom plugin with custom outfits. The second machine was a laptop with no plugins that had never ran the game before on a fresh save file.  The tick for the unknown system appears almost directly to the left of the systems in Pleiades, to the bottom left of the Milky Way galaxy, and directly below the systems from the World Forge plugin, giving an approximate location of -10000 7000. After searching the entire map.txt file, I could not locate any mention of a system anywhere near those coordinates. The system cannot actually be seen or jumped to on the map due to being outside of the system detection range. While this doesn't actually affect gameplay in any way, probably won't be noticed by anyone, and is entirely inconsequential, I still figured I might as well mention it.

**Comment by beccabunny** [comment]
Not a game problem, a plugin added it. Please close the issue

**Comment by northeast-eph** [comment]
I tested on another computer that had never ran the game, with no plugins on a fresh save, and it was still present. It's from the base game, not a plugin.

**Comment by northeast-eph** [comment]
Should I still close this, considering how minor and inconsequential it is with no effect on gameplay?

**Comment by northeast-eph** [comment]
The system I was seeing was Zubenelhakrabi, and I now know that missions don't actually add systems, they just move them from unreachable locations to where they end up.

**Comment by Zitchas** [comment]
Hmmm... And PostaVerta would probably show up like that, too.

I agree that this isn't actually a bug, but it isn't desired behaviour, either. Those systems that get moved are intended to be basically invisible and/or non-existent until revealed by missions.
