### ISSUE TITLE
Feature Request: Allow Min and Max Map Zoom Levels to be Defined in interfaces.txt

### ISSUE THREAD

**Issue by thebigh2014** [endless-sky/endless-sky#5554]
**Is your feature request related to a problem? Please describe.**

- If system density increases, the max zoom level will be insufficient in providing a clean and clear view of all systems (could become a big mess of overlapping systems).
- If there are additions of systems, galaxies, etc. outside of the current main galaxy, it will be difficult to easily navigate the map between such systems, galaxies, etc. with the current min zoom level.
- Defining the min and max levels in interfaces.txt will permit content/plugin creators to increase available zoom levels dynamically.

**Related Issue Links**
Not aware of any.

**Describe the solution you'd like**

- Add a new section to the `data/interfaces.txt` to specify `min zoom` and `max zoom` levels for the `"map"` interface.
- Update the `MapPanel::DrawButtons` and `MapPanel::KeyDown` methods of `source/MapPanel.cpp` to utilize the values in `data/interfaces.txt`

**Describe alternatives you've considered**
There appears to be no other way to increase the min and max values as they are currently hard coded in `source/MapPanel.cpp`

**Additional context**
Not sure what to add...

**Impact**
See the problem description above.

**Comment by Amazinite** [comment]
I know a discussion that has been had in the past was whether we should have a "gamerules" file that allows for easy manipulation of various aspects of the game that are currently hard coded, e.g. being able to change the constants used for depreciation. This would be a separate file from the interface file. Maybe now's the time to get started on that if we want to make the zoom values customizable in the text files.

**Comment by thebigh2014** [comment]
@Amazinite Well I've made PR #5555 with the values in the interfaces.txt file.  If you're thinking of going this other route then I'll be happy to tag along (though keep in mind I'm new to C++ so I can only do simple changes/additions for now).

**Comment by Amazinite** [comment]
The way I'm imagining this is that instead of hijacking the interface class, we have a class similar to preferences, only instead of the preferences being held in a `map<string, bool>`, we'd be storing gamerules in a `map<string, double>`. Wouldn't be too difficult, I imagine. Then the class could be statically accessed like preferences is. 

The text file:
```
gamerules
	# Values that dictate the minimum and maximum zoom levels on the system map.
	"min map zoom" -2
	"max map zoom" 2
```
MapPanel.cpp:L208-L211
```
	if(player.MapZoom() == static_cast<int>(Gamerules::GetValue("max  map zoom")))
		info.SetCondition("max zoom");
	if(player.MapZoom() == static_cast<int>(Gamerules::GetValue("min map zoom")))
		info.SetCondition("min zoom");
```
