### ISSUE TITLE
Some pirate jobs have a too long description

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#5559]
**Describe the bug**
The description of some pirate jobs is too long, see screenshot. Sorry if I skip some steps of the template, but it should be pretty straightforward to get so some are unnecessary.

**Screenshots**
![Screenshot (1377)](https://user-images.githubusercontent.com/45330165/102120100-57fe9d80-3e42-11eb-9dd9-f1cbf5eff281.png)
Ignore the fact it is new systems, the problem is unrelated to them as the text of the description has no replacement other than < payment > which is always 1,000,000.

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github
 - Version: 0.9.12

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/cbd0e7f80e545af67c1bcf1145b985f34b7bfa47 should fix this. Looks like all the assassination jobs were pushing it.
