### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by qawsedrftgzh** [endless-sky/endless-sky#5563]
I think there should be translations for this great game!
When I started playing this game I was afraid of these huge english texts. So I think it is not so difficult to add a translation (in the code with gettext), but huge work to translate a whole game.
I would also be a volunteer, when translating, if this is good idea, to german, because I am german native speaker.

**Comment by MCOfficer** [comment]
Dupes #558 #201 #708 #1090 #1915 #4053

**Comment by qawsedrftgzh** [comment]
Good, is there actually a translation system?

**Comment by MCOfficer** [comment]
No, but there are open issues for it. You can use the Subscribe button to be notified when these issues are addressed.
