### ISSUE TITLE
Outfitters not displaying *all* installed outfits

### ISSUE THREAD

**Issue by TomConlin** [endless-sky/endless-sky#5573]
**Describe the bug**
[A clear and concise description of what the bug is.]

Some outfits in  ships
i.e. jump drives & Ramscoops  at Tarazed
but not others
i.e.  SunBeam, Frags

stopped showing up (today) at Outfitters

after:
(2020 Dec 24 : git pull; scons; ./endless-sky)

Some outfits are no longer __visible__ in ships inventory within the Outfitters screen.  

  - save file shows outfits still exist.
  - ship info screen shows outfits exist in ship
  - outfits function in active ships after they depart Outfitter/Planet

**To Reproduce**

loot stuff; go places.

**Expected behavior**

- Expect to be able to see which outfits a ship has at Outfitters (all outfits it has).
- Expect to be able to transfer outfits between ships. 

**Screenshots**

[this is an accurate picture of the missing outfits]

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build: `http://mcofficer.me:8080/job/endless-sky-win64/<build number>/`)

```
$cat /etc/debian_version 
bullseye/sid


 $ ./endless-sky --version
Endless Sky 0.9.13-alpha
...

$ git log
commit 64ef17cd6992b42ba35a7d99e8dbe21c9a689a61 (HEAD -> master, origin/master, origin/HEAD)
Author: Peter van der Meer <peter.vd.meer@gmail.com>
Date:   Thu Dec 24 23:58:03 2020 +0100
```

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by Terin** [comment]
Please clean up your issue to remove irrelevant sections or formatting, provide screenshots of the outfitter and a place where we can see the actual outfits (like the ship info pages), and/or provide a save file.

**Comment by TomConlin** [comment]
sorry. User Error.
