### ISSUE TITLE
Request: Giving Remnant Engines a Niche

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5579]
**Content (Tweaks)**

## Summary:
Remnant engines are significantly overshadowed by Korath, Deep Atomics, and Hai Atomic engines, all of which the player has easy access to by the time they reach the Remnant. Also overshadowed by the Wanderers, whose performance isn't as good but has other benefits.

This draft PR is for testing out some options for making the Remnant engines better in a way that gives them certain areas where they will be desireable to have, without significantly impacting the "raw power superiority" that the Korath and Atomics currently hold.

In this first iteration, this is accomplished by giving Remnant engines both slow protection and slow resistance. The former reduces how much slow damage they take, and the later speeds up how fast they dissipate it. 

## Problem:
Remnant engines have long been avoided within the player-base due to the fact that by the time the character has access to them, they certainly have access to and are probably used to using Deep and/or Hai atomics. About the same time period that they gain access to Remnant thrusters and steering, they also are exposed to all the Korath stuff, which is basically the top of our engine charts. 

Now, Remnant engines aren't actually bad. In terms of thrust/space, they are fairly high on the chart: They fall behind three steps of Korath stuff, the top two Hai thrusters, and the best Deep thruster. The Smelter is 8th in terms of thrust/space, and the top spot is only about 28% more thrust/space. (and the Remnant thrusters are clustered fairly tightly together in 8, 10, 13, and 35th place. I'm basically ignoring the anvil for this, because it is a combined outfit.)

In terms of total thrust, however, the smelter drops down to 9th, and the distance between it and first expands significantly (first place has basically +100% the thrust of the Smelter). On top of that, the spread of Remnant engines expands a lot, so they now occupy 9th, 19th, 29th, and 32nd. 

So the competition basically boils down to this:
1) If you prioritize acceleration and top speed above all else, then:
- If you have space for it, Korath are the best. (needs a lot of cooling, but again, you have space, right?)
- Next up is Deep and Hai that also need a fair bit of space, but not as much as Korath stuff and much less cooling)
2) If you are making a more general purpose ship, then:
- Wanderer thrusters aren't great in terms of total thrust or their direct space efficiency; but the fact that they *provide* cooling instead of requiring it gives them a strong edge in that regards anyway.
- Using smaller Korath or atomics (due to their high thrust/space) are often useful.

Caveats:
- I don't particularly want to make any large changes to the balance between engines. 
- None of the changes should make the Remnant an "all round best" engine.
- Having a strong utilization case for a limited or specific use and/or situation would be ideal. (In other words, being great at something fairly specific while still being "average" for most other things)

**Related Issue Links**
Particularly relevant is Amazinite's overview of Thrusters provided as part of a "best of" list: https://github.com/endless-sky/endless-sky/issues/2852#issuecomment-318910181
Discussion of Reverse Thrusters: https://github.com/endless-sky/endless-sky/issues/3252
An idea for tweaking Remnant thrusters by making them much more efficient but also giving them cooling inefficiency which makes them problematic to stack: https://github.com/endless-sky/endless-sky/issues/4688

**Describe the solution you'd like**
The Remnant engines to receive some kind of buff sufficient to make them desirable in at least a few specific use cases, probably ones related to either:
a) Use in the Ember Waste's newly implemented hazards environment, or 
b) Long-term flight endurance.

**Describe ideas you've considered**
1. The Remnant value mobility. Better to not be hit than to be able to tank the hit. They are very familiar with weapons that impede mobility, ergo, maybe they have developed their engines to resist that impediment and/or recover from it more quickly?
2. Alternatively, what if Remnant engines were capable of operating in reverse of significant strength? Basically, every engine includes a built in thrust-reversal system.
3. Continuing that line of thought, what if their afterburner - instead of enabling them to leap forward, actually was built to accelerate them backwards? Thus they could fly forward to attack, then leap backwards out of the way of danger. It'd be even more interesting/effective if it applied thrust at right angles to the ship's axis. As in, the 'afterburner' pushed the ship sideways in a strafing motion.
4. A significant hazard in the Ember Waste is the ion storms, and a secondary hazard is heat. (the latter often magnified by the former disabling active heat systems). Now, Wanderers pretty much have a lock on "engines that dissipate heat instead of make it," so what about having engines that can run on radically less energy? The less energy they use, the less likely they are to overload the ship systems during an ion storm, and the less Remnant mobility will impacted. 
5. Other perks? For instance, giving Remnant engines built-in ramscoops, minor amounts of hull and/or shield repair, fuel generation, etc.
6. Giving them emergency motive power? Not sure if it could be implemented on the same outfits, but basically giving Remnant engines a second "thrust" value that is a tiny percentage of its normal value, but doesn't use any energy at all to operate. Thus even when they are completely drained of energy they'd still be able to effectuate a very slow escape.

**Comment by vitalchip** [comment]
I have my own line of Remnant engines, they have built in reverse at around 60% forward thrust and have slowing protection. I add a small amount of mass to cover 'reverser buckets'. People often complain about AI combat and at the same time decry reverse thrust as a niche when in fact it is essential for ships with a heavy forward gun emplacement.

I'd actually like to see this sort of reverser become the game standard but it has to start somewhere..

Slowing protection is a natural fit for the Remnant due to their experience reverse engineering a 'slowing weapon' (Detainer?) into the Inhibitor Cannons.

**Comment by petervdmeer** [comment]
Maybe relevant that we could also have things like 'additional operating costs' in the form of small amounts of hull damage for Korath engines when we update the game-engine for this. Most Korath ships have some form of auto-repair, so it seems fitting for Korath ships and it would be an additional differentiator with the Remnant engines. (https://github.com/endless-sky/endless-sky/issues/4532#issuecomment-531509396)

**Comment by Zitchas** [comment]
True, that is definitely a possibility. I know Amazinite has mentioned wanting to do a general engine rebalance, so I'd prefer to leave changes to multiple engine sets for that; and just focus on something to make the Remnant engines worth using right now. Might also be useful testing out options that might be useful for such a future update.

**Comment by Hejong** [comment]
The Remnant are also scavengers and a scrappy bunch. Whenever an Ion storm rolls in, those Korath raiders are vulnerable. Perhaps their engines operate **better** in Ion Storms, harnessing the storm itself to generate energy / active cool the ship. This would give them a massive leg up against the Korath they plunder.

**Comment by Zitchas** [comment]
That's an interesting idea, but I'm not sure how to implement something where their engines work better when ionized. Hmmm... I'll have to check the CreatingOutfits page - maybe there's some way they could have built-in afterburners that consume ionization?

I'm not sure about having something like that actually implemented at this point in time, but it is a neat idea for the future.

**Comment by vitalchip** [comment]
Negative Ion Resistance Fuel?  So when Ionized your fuel gets topped up for the afterburner.In system this would mean that during an ion storm your afterburner could be used for longer, to get you clear. Add it to the Bellows?

**Comment by Zitchas** [comment]
That I think will definitely need a mechanic change. Right now, the afterburner could be rigged to consume energy, fuel, or heat. Ionization and slow aren't eligible. Neat idea, though.

**Comment by vitalchip** [comment]
Resistance Fuel Cost is in continuous already.

**Comment by Zitchas** [comment]
Hmmm... Somehow I missed that.  I'll have to go take a look.
