### ISSUE TITLE
Don't reset multiple keybinds that are overloaded to a single key

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5582]
**Is your feature request related to a problem? Please describe.**
It is currently possible to overload multiple keybinds to the same key. For the duration of your play session, pressing the overloaded key will cause both commands to be sent. But once the game is closed, the game will reset one of the keybinds to its default to avoid having two keys be overloaded. This is unfortunate, as it can be easier to have multiple commands bound to the same key, such as having both primary and secondary fire on the same key.

**Related Issue Links**
#3972 Having overloading be allowable behavior could make it easier to find setups for other input methods.

**Describe the solution you'd like**
Do not reset keybinds to their default if they are overloaded. We should keep the current UI behavior though where overloaded keybinds get highlighted, although perhaps using yellow instead of red to show that it is a warning, not an error.
![image](https://user-images.githubusercontent.com/17688683/103253602-b6457900-4936-11eb-82aa-921f85a9bd82.png)

**Describe alternatives you've considered**
Nothing.

**Additional context**
N/A

**Comment by yobbo2020** [comment]
This also annoyed me so i made a PR. Although i didn't change the colour of the warning, it at least saves and loads however you set it.
