### ISSUE TITLE
Comptability issue with OS X Homebrew jpeg and jpeg-turbo

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#559]
Currently, if you have the homebrew jpeg library installed (`brew install jpeg`), compiling Endless Sky will throw the following error, even if you also have jpeg-turbo installed:

    ImageBuffer.cpp:213:27: Use of undeclared identifier 'JCS_EXT_BGRA'

The only way to avoid this is to uninstall the Homebrew jpeg package, then the complier seems to correctly use the jpeg-turbo package. Unfortunately, a number of other Homebrew packages depend on the libjpeg package (such as ImageMagick), so uninstalling this is not ideal. Is there a way to get it to use the turbo library even if the regular libjpeg is installed?

**Comment by endless-sky** [comment]
Does homebrew install both libraries in the same directory, or can you control which one is used by altering the search paths?

Otherwise, you could always just use absolute paths, both for the library and the header.

**Comment by guillochon** [comment]
Homebrew installs everything to /usr/local, so the search path would include both of them. It appears that Homebrew does not stage jpeg-turbo's header file into /usr/local/include, it prefers to put jpeg's header file in there (both are named jpeglib.h). So with a homebrew install of libjpeg, the wrong header is included.

What should change is that the XCode project should have the jpeg-turbo /opt/libjpeg-turbo/include added to the search path *before* /usr/local/include, since currently the project points to /opt/libjpeg-turbo/lib/libturbojpeg.0.dylib for the library's location. I've created a PR with this fix, https://github.com/endless-sky/endless-sky/pull/560.

**Comment by endless-sky** [comment]
This was fixed by changing the include paths (#560).
