### ISSUE TITLE
Portraits for Humans at Space Ports are Missing

### ISSUE THREAD

**Issue by Whyareuhere** [endless-sky/endless-sky#5596]
**Describe the bug**
The portraits of humans at space ports are missing. Potentially portraits for other entities (Quarq, etc.) are also missing, but the normal text is displayed.

**To Reproduce**
1. Download latest automated build, run it.
2. Load save or make new pilot
3. Go to "Space Port" button
4. See bug as described above

**Expected behavior**
Portraits should show up along with text

**Screenshots**
![image](https://user-images.githubusercontent.com/51333747/103446442-8f3bbf80-4c34-11eb-9ab1-2f082a72e7e7.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Github
 - Version: latest automated build

**Comment by MCOfficer** [comment]
based on community feedback (#4325), portraits have been removed in #5187.

**Comment by Zitchas** [comment]
Just to expand on MCOfficer's statement a bit:
The ability for news items to have images has been retained, and the images are still in-game in-case any plug-in content used them, but all the in-game news items that used to use them no longer do.

The removal of portraits from the news system has resulted in it being expanded from just random quotes by generic people, to also include spaceport graffiti, incoming threats and launch scheduling for certain alien worlds, and other stuff that didn't fit necessarily with having a face there.

**Comment by ravenshining** [comment]
I don't see how having portraits *prevented* any of those things from being made.  They'd just appear without a face, and that could have inspired people to make art other than faces.

**Comment by LordInsane** [comment]
That might have been easier if ES didn't go with the route of using _photos_. You'd either keep it with photos for some and generated art for others (with the strong risk that the generated art would have been rejected for not being a photo), or as it was photos for some and nothing for others... both being more jarring than consistent generated art or not having to feel obligated to show an image (especially given how, frankly, the usage of real-world images of people was itself rather jarring for some of us).

**Comment by ravenshining** [comment]
That is a vaild concern I'll grant you... but only as it applies to non-human faces, and not one that is insurmountable.  For one, you'd never see the generated art side-by-side with a photo, so if the generated art is decent enough it won't be noticeable - as I think my demonstration using a Wesnoth character in a mock-up on Discord showed.  That said, that level of art for aliens is a high bar - one that could be brought down a bit by some post-processing of the photos to make them less realistic, a technique used in some older mainstream titles.
