### ISSUE TITLE
Idea: Make Hai outfitter more color-consistent by swapping atomic engines

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5598]
**Is your feature request related to a problem? Please describe.**
My issue is that I frequently mix up the Deep and Hai atomics due to the coloration. I don't know exactly why, although I suspect it is because of all the Hai reactors that have liberal amounts of green on them, but based on the image, I always assume that the green atomic engines are the Hai ones, and the blue atomic engines are the human ones. And the names aren't that illuminating either, so I always have to actually go read the descriptions to figure out which one is the human one and which one is the Hai one.

**Related Issue Links**
#5584 Human Graphical Upgrade

**Describe the solution you'd like**
There has been discussion about differentiating the human and Hai engines by having the human engines look more like regular engines (as per the new ones that Becca has made in #5584 ) while the Hai ones retain the alien and kind of strange no-engine looking atomic engines.)

As such, I would like to propose that we go one step farther, and swap the colors so that the Deep is the new engines that Becca has made, except blue. While the Hai engines are the visually distinctive and kind of alien looking ones, except green.

**Describe alternatives you've considered**
I'm not sure how the color discrepancy can be resolved other than changing around the color palette of one of the oufit sets. Either the Hai reactor set should be changed to blue, or the two engine sets should be switched color.

It seems easier to simply swap the two engine sets, since we already have a blue alien looking reactor (the current human atomics) which can become the Hai ones, and since BeccaBunny already has the new models, I suspect it shouldn't be too hard to make them blue instead. 

Example 1: This is the current outfitter of Hai-Home
![Hai Outfitter2](https://user-images.githubusercontent.com/32169904/103481373-cb3b6580-4d97-11eb-9992-cac93a7882d1.png)
Note that at a quick glance, it looks like the engines I have installed on my ship match the locally available reactors. Meanwhile, the locally available engines look like imports (aka, they don't have any connection to the reactors.

Example 2: This is the outfitter of Hai-Home where all the Hai engines have been swizzleimage 4'd to make them green, and BeccaBunny's new Deep engines have been swizzleimage 3'd to make them blue. Note that now the engines installed on my ship stand out clearly as being from somewhere else, while the engines available in the outfitter clearly identify that they are local engines.
![Hai Outfitter (Matching2)](https://user-images.githubusercontent.com/32169904/103481414-21100d80-4d98-11eb-8e03-9f15caef1041.png)

**Note**
I don't consider this to be a major game breaking thing, but it would make things easier on me (and probably other people who prefer to have some visual consistency within their graphical sets.). Since we are revamping all the human graphics anyway, this seems like an ideal time for such a color swap.

**Comment by Zitchas** [comment]
@Anarchist2 While I appreciate the opinion indicator, would you be able to explain why you're not fond of this idea? I made this request because this is honestly a source of confusion for me; and maintaining graphical consistency to aid in identifying related items is a real informational issue that could help people understand the game better. I would like to understand your opinion as to why you think this isn't a beneficial change.

**Comment by Zitchas** [comment]
Update: Added two images to the main comment above using discord's image swizzling tool to swap the colors around. Swizzle 4 for the Hai engines, and swizzle 3 for the Deep engines.

Example 2, which I'll repost in this comment, is a rough example of what I'd like. BeccaBunny is rendering a set of his new engines with a more vibrant blue as an example.

![Hai Outfitter (Matching2)](https://user-images.githubusercontent.com/32169904/103481506-a85d8100-4d98-11eb-96ee-b0fbe91deb1a.png)

**Comment by yobbo2020** [comment]
I personally like the blue Hai engines, and have never had any confusion differentiating which was which between the atomics.

Isn't it a bit boring to just make the Hai the "green" aliens without any colour variety? And in that case shouldn't that blue Bullfrog turret also be recoloured? And then all the green human batteries and power generators should probably be made blue...

**Comment by ira210** [comment]
I like this it feels like the outfitter all fits together

**Comment by ira210** [comment]
with the change suggested i mean

**Comment by Zitchas** [comment]
No, I don't actually want everything to be the same color. What I actually want is for there to be visual queues that indicate that things are part of the same family. This could be common design elements, material styling, color palette, or probably a few things that I haven't thought of. 

The problem is basically that, when the Hai were made, MZ suffered a lack of inspiration and basically made all the Hai stuff slight variations on human stuff. Compare this to, say, Korath, Wanderer, Coalition, or Remnant outfitters, which each have clear style differences that (for the most part) make each of those more easily identifiable. 

Color is basically the easiest thing to change, particularly when we have large blocks of outfits that sit right next to each other in the outfitter.

**Comment by beccabunny** [comment]
> The problem is basically that, when the Hai were made, MZ suffered a lack of inspiration and basically made all the Hai stuff slight variations on human stuff.

MZ didn't make most hai outfits, including the engines

**Comment by Zitchas** [comment]
Hmm, that's true. there's a variety of people in the credits. Still, the main point stands.

**Comment by Plip-Plop** [comment]
I think that instead of making everything of one manufacturer a single color(which would make it bland), a bi-color color scheme could be adopted. That would allow each manufacturer to have a unique color while adding variation to the outfit screen.

**Comment by Zitchas** [comment]
Yes, that could work.

That being said, I'm going to close this for now while the impact of the Restock on outfit families is considered.
