### ISSUE TITLE
Endless Sky has the name "EndlessSky" on OS X

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#561]
On OS X, Endless Sky appears as "EndlessSky":

![EndlessSky in the menu bar](https://cloud.githubusercontent.com/assets/6200170/12061651/678e0810-af51-11e5-8eaf-a5d0e79e4679.png)
![EndlessSky in the dock](https://cloud.githubusercontent.com/assets/6200170/12061652/679365f8-af51-11e5-990a-721915769662.png)

This is contrary to how it appears everywhere else (i.e. GitHub, Steam, the manual) where it is two separated words.

**Comment by endless-sky** [comment]
Unfortunately, Steam will get messed up if the name of the executable file changes, but I could at least see if I can change the name that appears in the menu.

**Comment by Thunderforge** [comment]
Pity that the executable can't be renamed. I'm guessing that results in the dock name? Is there some other way to fix this like you can with the menu bar?

**Comment by tiennou** [comment]
Have a look at `CFBundleDisplayName` & `CFBundleExecutable` [here] (https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html), that should do it :wink:.

**Comment by tehhowch** [comment]
If this is still an issue, @tiennou perhaps you can verify if #3595 resolves the display name on OS X

**Comment by nobodywasishere** [comment]
<img width="315" alt="screen shot 2019-01-24 at 10 52 52 pm" src="https://user-images.githubusercontent.com/32797552/51724326-d2de2580-202a-11e9-8600-9c61199d8bd7.png">

This is still an issue. Running macOS Mojave.

**Comment by nobodywasishere** [comment]
<img width="169" alt="screen shot 2019-01-27 at 11 05 58 pm" src="https://user-images.githubusercontent.com/32797552/51814185-21d4c680-2288-11e9-95d3-419d8c8e1726.png">

I did it! Followed @tiennou 's instructions and now it builds with the correct name. Trying now to push it to my fork
