### ISSUE TITLE
Grab-strike not working 

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#5625]
BUG description:
Pillaged Korath Grab-Strike turrets do not work.

**To Reproduce**
Jan 9, 2021 continuous build. Save-file at end.

[boring background: doing my usual pre-FW storyline power build with Shield Beetles. Parked at Alcyone to begin farming jump drives from Korath in Gamma Cassiopae. Pillaged jump drive, heat shunt and grab strike. Previous two worked fine, grab strike did not. Grab strike worked for Raider. 
FYI, other pillaged weapons, including a Korath Detainer swiped from the Kor Mereti south of Unfettered Hai works just fine. 

**Expected behavior**
No visual or auditory clues to indicate normal operation of grab-strike.
Self-compiled, UBUNTU, AMD 64.

NOTE ON EDITED SAVE-FILE
The ONLY edits done on the savefile was to give the Shield Beetles more remember-able names.

[Moira McArthur~grabstrike not working.txt](https://github.com/endless-sky/endless-sky/files/5793423/Moira.McArthur.grabstrike.not.working.txt)

**Comment by Terin** [comment]
Working for me right out of the gate, also the latest compiled build on Arch Linux. Do you have any plugins, like the high DPI one, that could be causing issues? Or that they're not firing in a direction you're not expecting?

Also, side note: You can rename ships in game by opening the ship info panel, and clicking on their name to rename them.

**Comment by movingpictures** [comment]
a) No other plugins
b) Not firing at all, as best as I can tell. Can't see any grab-strike
missiles, can't hear the typical auditory clue that comes when they are
fired.

c) Who the hell knew? Well, then.

**Comment by Terin** [comment]
All I could say then is try to redownload either the source, or the [Continuous build](https://github.com/endless-sky/endless-sky/releases/tag/continuous) right from here, and see if it continues.

**Comment by movingpictures** [comment]
When I have a moment, I'll strip out all other weapons and see what shakes.
Maybe I'm missing something.

**Comment by vitalchip** [comment]
Spliced your ship Green Socks into my save file and all weapons work.

**Comment by movingpictures** [comment]
Still tying to piece this together, but it seems that for some reason, the normal grab-strike sound wasn't playing I can't replicate now, so ... I'm content with abandoning this.
