### ISSUE TITLE
Vareti'het can be captured

### ISSUE THREAD

**Issue by fakepass** [endless-sky/endless-sky#5630]
**Describe the bug**
Unlike other Ka'het ships, it is possible to capture Vareti'het. (If it's possible to disable them in the first place.)

**To Reproduce**
1. Go to the Graveyard.
2. Wait for a disable-able Vareti'het to show up.
3. Disable it.
4. Capture.

**Expected behavior**
It should be impossible to capture all Ka'het ships, including Vareti'het.

**System (please complete the following information):**
 - OS: Debian linux.
 - Game Source: self-compiled
 - Version: e5d695c0

**Comment by Terin** [comment]
![image](https://user-images.githubusercontent.com/4471575/104287360-f26ef280-547b-11eb-8d2d-ce684cc92dc8.png)
Well would you look at that. At last, we can become slugs
