### ISSUE TITLE
Add "since version XX" in modding documentation in Wiki

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#564]
I was reading https://github.com/endless-sky/endless-sky/wiki/CreatingMissions and if I remember correctly `stopover` as well as 2-parameter `payment` and  `deadline` are available since v0.8.10

As it currently stands, those sticking to binary releases (i.e. v0.8.9) will almost certainly be confused when they try to use these new feature just to find out that it does not work for their versions :confused:

**Comment by endless-sky** [comment]
As of 0.9.0, I'm adding notes in the wiki for new features that aren't supported in earlier versions.
