### ISSUE TITLE
Hold possition fails after landing [ maybe feature,  was not sure ]

### ISSUE THREAD

**Issue by cryptoatropine** [endless-sky/endless-sky#5655]
I was not sure if this should be called a bug . but in either case it will help the game ... and i think an easy fix ... 

The issue is: only an issue for some missions where you need to use one ship, and don't want others following it. 

**To Reproduce**

So you hold position to prevent other ships from following move a system and land,

NOTE:
It is true that you can press hold again once you take off .... but not always fast enough to stop them from jumping once ..   

**Expected behavior**
keep last fleet command. 
if you hold position with fleet, it should hold until other wise told..  

**System (please complete the following information):**
 - Debian - testing [ will be Bullseye ]
 - Game Source:  self-compiled ... used instructions from site to 100% 
 - Version: 9.12

**Link to save file**
NA

**Additional context**
ask if you need more or i did not explain well enough .. i think its straight forward though

**Comment by tatami4** [comment]
I am not sure how to fix this, because currently all orders for all ships are cleared when the player lands. Maybe make the ship remember its orders?

**Comment by cryptoatropine** [comment]
Oh i see now i had not expected that answer... my suggestion which is  probably better tailored  to bash rather than cpp ...  
would be to just save orders on land in a variable  ... and load or apply that variable on take off ..... i don't know however what other implications that may cause, if any ... 
 
I know a bit of CPP but mostly not ... i can make edits if i know what i'm looking for ... or in cases with [ strong || good ]  commenting

**Comment by petervdmeer** [comment]
I feel the first thing to discuss in tickets like this is on what we want the behavior to be, not on how difficult such desired behaviour would be to implement.

None of the options mentioned here seems hard to implement anyway and very old versions of the game did seem to have ships remembering their orders over landing (until this [commit in 2018](https://github.com/endless-sky/endless-sky/commit/9cdebdbf46e8d6bf5c3a47c9445429196bb89242) ). Giving orders through the map is also already supported through #2678, so I guess we can also extend this to be used during landing if we really want to.

One very important aspect is that we want the game to be very accesible for new players and the behavior of ships forgetting their orders on landing seems very logical and discoverable for such new players, while ships remembering orders could actually lead to confusion with new players on why ships "appear to stay stuck" or suddenly move to positions in the current system.

Another thing to consider is that players can already park ships that they don't want to use during missions. The parking mechanism already seems to support many situations where the player wants to fly around with just one ship.

**Comment by cryptoatropine** [comment]
OH now see i didn't even know about parking .... how do i do that ? that sounds like a great solution if that is already working .... 

Also in keeping with your ease of use, perhaps this could be added as a preference option rather than a forced game dynamic .. 
but as i was saying fist off .... i would agree not needed if parking is a thing...

**Comment by cryptoatropine** [comment]
So p is park ? 
	GetUI()->Pop(this);
	else if(!player.Ships().empty() && (key == 'p' || key == SDLK_LEFT || key == SDLK_UP))
	else if(showShip && !player.Ships().empty() && (key == 'p' || key == SDLK_LEFT || key == SDLK_UP))
	{
		if(shipIt == player.Ships().begin())

**Comment by cryptoatropine** [comment]
ahh i see it now in the info screen button park .......   ok   ..... um i have a new request ..... to make that more known in the early game .... perhaps as that guy taked you around in your "training" ....   maybe he could mention about parking ...

**Comment by petervdmeer** [comment]
No problem, thanks for providing feedback on the game.

The latest version game contains this [hint](https://github.com/endless-sky/endless-sky/blob/c66e787df45c34bbc644a6739d8a44ddd3f79594/data/help.txt#L84) that should pop-up once have more than one ship in your fleet. This hint also seems to tell players about parking ships.
