### ISSUE TITLE
Minor typo on Hai  Nanachi quest

### ISSUE THREAD

**Issue by M1F9** [endless-sky/endless-sky#5657]
I'm not entirely sure the proper quest name, just created this Github account to make the programmers aware (if not already) of this minor typo. Looks like someone crossed could and should into "chould".
![EndlessSkyTypo](https://user-images.githubusercontent.com/77767737/105280331-81b09000-5b77-11eb-8943-fe39514eb567.PNG)

**Comment by tehhowch** [comment]
Thanks for the report -- this was fixed a while back, in #5064
