### ISSUE TITLE
link to forum (google groups) says access denied

### ISSUE THREAD

**Issue by Zavindur** [endless-sky/endless-sky#5658]
**Describe the bug**
in the github, under endless sky, under 'contribute' it says : 
"and to post in the discussion forum." where the 'discussion forum is a link to a google group.  That link seems to require access.

**To Reproduce**
Try to go to the 'endless sky forum'

**Expected behavior**
the forum will be displayed

**Screenshots**
not provided 

**System (please complete the following information):**
browser: chrome

**Comment by Zitchas** [comment]
I have had your problem in the past - and I can repeat it if I visit the forum from a browser that isn't logged into google. For example, visiting in a "incognito" or "Private Mode" browser window. 

All I can suggest is logging into google first, then trying to visit the link.

That being said, the vast majority of game development and discussion happens on discord - not on google forums. It can be accessed at: https://discord.gg/ZeuASSx

**Comment by MCOfficer** [comment]
See https://github.com/endless-sky/endless-sky.github.io/issues/23

**Comment by Zavindur** [comment]
thankyou, i see mcofficer link covers this issue, i'll just go on discord then
