### ISSUE TITLE
Can land Fleet on Nesqueron; change ships

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#5663]
Mechanics issue: 
At the mission after defeating the Korath fleet attacking the void sprites, one can land a Penguin on Nasqueron along with a fleet. Can then change into a different vessel to engage Korath, scoop Jump Drives, etc. 

**To Reproduce**
Steps to reproduce the behaviour:
1. After the Korath fleet has been defeated, bring the Penguin as the flagship. Land on Nasqueron.
2. Move a different ship into the flagship position.
3. Take off in a different vessel.

**Expected behaviour**
Seems to me the fleet should be unable to land on the gas giant ... 
Jan 8 nightly build
[Speedy Wilson~To Nasqueron 2.txt](https://github.com/endless-sky/endless-sky/files/5862419/Speedy.Wilson.To.Nasqueron.2.txt)

**Comment by Zitchas** [comment]
Definitely. The fleet should not be able to land on Nasqueron. There appears to be a bug where the fleet follows the lead ship everywhere, even if they normally wouldn't be able to.
