### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile (OS X)

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#567]
This warning appears in the console when running Endless Sky on OS X. It seems that some of the .png files are including a color profile that they shouldn't be (more info [here](http://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile)), and libpng 1.6+ complains when it encounters such files. I tried a couple of the solutions available on the web for stripping color profiles from the .png files within the project, but removing the profiles causes the images in the game to appear corrupted. Not sure how to solve the problem or if it's something that we can just ignore.

**Comment by endless-sky** [comment]
I found two PNGs with the wrong color profile. See if commit 2a72f62 fixes this for you.

**Comment by guillochon** [comment]
Appears to have fixed it, I was using the 2x graphics and I see that you fixed those as well.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
