### ISSUE TITLE
Proton Gun DPS doubled? 

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#5671]
![Screenshot from 2021-01-28 14-06-48](https://user-images.githubusercontent.com/20472439/106142877-52e77a80-6172-11eb-9942-df7d36e7fcfc.png)
It's been a while since I played this game so perhaps this was changed at some point, but a quick search in the pull requests doesn't show how/why. Looks like the damage from the proton gun/turret is doubled. Debian Testing, latest continuous build of game.

**Comment by MCOfficer** [comment]
So... what is the issue? We have issue templates, by the way.

The last change to the proton gun was #3315, the proton turret was added a day later in #3316. That was 3 years ago.

**Comment by jlnxr** [comment]
Sorry if it doesn't follow template. Issue is DPS used to be 189 (as shown in the discussion for #3315) and now, as you can see in the screenshot, it is 378. Unless there was another change I can't find, that's a bug, which would significantly unbalance any ships carrying proton guns

**Comment by beccabunny** [comment]
Seeing how you also have a duplicated description, the issue is likely to be caused by a plugin, not by ES

**Comment by jlnxr** [comment]
Haven't got any installed

**Comment by MCOfficer** [comment]
i checked on 9da2724, both proton gun and proton turret have  25.2 shield damage / shot and 21 hull damage  / shot, which results in 189 shield damage / s and 157.5 hull damage / s. All other values are the same as your screenshot.

**Comment by jlnxr** [comment]
Uninstalled and deleted everything ES related except my saves and re-built from latest source. Problem solved. Still not sure what caused it on my end but clearly not a wider problem. Thanks for helping!
