### ISSUE TITLE
Ability to make NPCs randomly spawn

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#568]
There are several mission types that I think would benefit from a new feature for NPCs that gave them a random chance to appear, rather then currently having to hardcode which system they start in or define some kind or relationship to the system that the mission is given on. You would define a percentage chance to arrive for each NPC that would be tested every time the player warps into a new system. With this, you could have NPC ships randomly appear at any time along the route that the player takes. This is what I was trying to do in merge request #546, but was hampered by the lack of this feature and had to half-ass it by having the pirate ships appear within a random distance of the source planet, which suffers from the noted issue that if the pirate ships spawn in the opposite direction from where you're going, you may never encounter them.

I can think of at least three distinct cases that would be awesome to have:
* NPC spawns and enters current player system
* NPC spawns in system that player is currently warping to, so they're already there when you arrive
* NPC spawns in current player system and takes off from an inhabited planet, if available (otherwise falls back to case 1)

**Comment by brick96** [comment]
Entering makes them warp in when the player does

**Comment by Pointedstick** [comment]
Yes, but there's no ability to make them randomly spawn along the player's route like I'm proposing.

**Comment by thenerdfreak** [comment]
So you propose that, using the time it takes to jump as a buffer period, make ships randomly spawn in systems you're jumping to?

**Comment by Thunderforge** [comment]
There is precedent for this in Escape Velocity Nova. In some of the Rebel missions, you were told that when the Rebellion wanted to contact you, they would send the ship "Prodigal Son" to try and intercept you. I don't recall how it was actually implemented, but I could see something like this being desirable in Endless Sky to make similar missions.

**Comment by Pointedstick** [comment]
Yeah, I could see this being useful for a lot of cool missions.

**Comment by endless-sky** [comment]
It's now possible to use location filters to place NPCs in a random system within some distance of the current system or another one.

**Comment by Pointedstick** [comment]
That doesn't actually address the original request, but oh well.

**Comment by Thunderforge** [comment]
@endless-sky While your commit is a useful feature, it doesn't do what this request was asking for:

> You would define a percentage chance to arrive for each NPC that would be tested every time the player warps into a new system.

The key here is that the random chance happens regardless of where you are. You could be on either end of the galaxy and it could still happen. I compared this earlier to the Rebellion missions and the Prodigal Son ship in Escape Velocity Nova. That ship had a chance of appearing no matter what part of the galaxy you were in.

I suppose *technically* the a ship could appear anywhere by just setting the system distance to 9999, but that seems like a really clunky workaround.
