### ISSUE TITLE
Link from Statina to Egeria is not saved.

### ISSUE THREAD

**Issue by tatami4** [endless-sky/endless-sky#5680]
**Describe the bug**
In the player's save file there is no link from Statina to Egeria even though the player has visited both systems.

**To Reproduce**
don't know, I just saw it when testing one of my PRs (probably happens every time as I have it on two saves)

**Expected behavior**
There is a link from Statina to Egeria.

**System (please complete the following information):**
 - OS: openSUSE Linux
 - Game Source: self-compiled
 - Version: eb1af7d47351fb5bc940664397e85329a1e25ba0

**Link to save file**
[John Brown.txt](https://github.com/endless-sky/endless-sky/files/5903296/John.Brown.txt)
relevant section (from line 12014):
```	
system Statina
	link Postverta
	link Diespiter
```

this one has not visited Statina yet: 
[Stuck.Remnant.txt](https://github.com/endless-sky/endless-sky/files/5903301/Stuck.Remnant.txt)
relevant section (from line 40657):
```	
system Statina
	link Postverta
	link Diespiter
```

**Comment by Zitchas** [comment]
Thanks for reporting this. I have located the problem, and will have a fix posted shortly.
