### ISSUE TITLE
Alternative autopilot to planet selection option.

### ISSUE THREAD

**Issue by MasterOfGrey** [endless-sky/endless-sky#5687]
**Is your feature request related to a problem? Please describe.**
At the moment it is possible, though little known as a feature, to autopilot and land directly to a planet by selecting it on the radar map. Not only is this feature incredibly useful, it's very well-hidden and finnicky to do, which is less than ideal.

**Related Issue Links**
This is an alternative use of the functionality added by [this commit](https://github.com/endless-sky/endless-sky/commit/8483cff796bef7efa5166d23c5c9fde5fc075d2b).

It also would someway go to help with the complaint behind [#4638](https://github.com/endless-sky/endless-sky/issues/4638)

**Describe the solution you'd like**
On the map screen, allow clicking a planet name from the sidebar on the left to perform the same function.

Additionally, then add a delayed tutorial mission that fires when you've done several missions already that explains the behaviour.

**Comment by Amazinite** [comment]
This behavior is already explained in one of the new tutorials. 
> help "map advanced ports"
>	`...`
>	`... Clicking a planet on the orbit map will also tell your auto-pilot to land on that planet after you have arrived at that system at the end of your jump path.`

As for allowing clicking on the planet's name to also set that planet as your destination, I actually thought of that while reviewing the PR that added the new tutorials.

**Comment by MasterOfGrey** [comment]
Ah I missed it's inclusion in the tutorials, but yes being able to click the name in the box feels more intuitive to me than clicking on the "orbit map" (I've always thought minimap or radar map).

After all, you click on the system and the most obvious change is that the sidebar updates. It's where the trade prices are, the presence of shipyards, outfitters and the friendly status of the planets are etc. It's naturally where your eyes go so I think it's logical you should be able to select it there.

**Comment by warp-core** [comment]
Added by #7316.
