### ISSUE TITLE
Plugin Addition

### ISSUE THREAD

**Issue by TheDeathStar3** [endless-sky/endless-sky#5691]
Hi, what is the chance of me making a plugin and then it gets added to the game? What my plugin does is that it expands the pug galaxy and it adds a couple storylines in the pug galaxy.

Sorry, I do realise that this place is for issues not really questions like the one I asked.

**Comment by MCOfficer** [comment]
In general, it depends on the plug-in. However, it's pretty rare for plug-in content to be merged. And Pug-related stuff specifically might mess with upcoming storylines, so maintainers will be extra careful. Some content is better off being a plug-in: It doesn't have the same prestige and playerbase, but it's allowed to develop on its own terms.

> Sorry, I do realise that this place is for issues not really questions like the one I asked.

Let me point you to the right places 😉 : 
- [The Steam Forums](https://steamcommunity.com/app/404410/discussions/)
- [The Community Discord](https://discord.gg/ZeuASSx)
- [The Subreddit](https://www.reddit.com/r/endlesssky/)
- 
Developers are active on steam and discord.

**Comment by TheDeathStar3** [comment]
ok, Is there anything that I can add that expands the galaxy to the actual game that no one else is doing at the moment?

**Comment by Zitchas** [comment]
I'd recommend starting small, then as you learn what is going on, move bigger. We need lots more single mission or mini-mission strings, for instance, for pretty much all the factions.

**Comment by TheDeathStar3** [comment]
ok thanks.
