### ISSUE TITLE
Missing files from provided dev library

### ISSUE THREAD

**Issue by Expack3** [endless-sky/endless-sky#57]
The winapifamily.h file is missing from the provided win64 dev library, as evidenced by searching for it manually and from the following CodeBlocks compile error:
````C:\dev64\include\SDL2\SDL_platform.h|121|fatal error: winapifamily.h: No such file or directory|````
I don't know what other files are missing at this point, though.

**Comment by endless-sky** [comment]
Can you see if replacing `C:\dev64\include\SDL2\SDL_platform.h` with this file fixes it? That's what's suggested on [this page](http://stackoverflow.com/questions/22446008/winapifamily-h-no-such-file-or-directory-when-compiling-sdl-in-codeblocks).

https://hg.libsdl.org/SDL/raw-file/e217ed463f25/include/SDL_platform.h

**Comment by Expack3** [comment]
That did, but now there's a bunch of errors in Audio.cpp, mostly consisting of "x does not name a type" errors for things already included, like mutex and thread. Could it be because mingw-64 isn't in the default (for the project) location, the location of the openal source files as far as the project knows should be reconfigured (looking up how to do that now)? Here's the error log:
````
||=== Build: Debug in EndlessSky (compiler: GNU GCC Compiler) ===|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|70|error: 'mutex' does not name a type|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|76|error: 'thread' does not name a type|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|86|error: 'thread' does not name a type|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|108|error: 'mainThreadID' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|108|error: 'this_thread' has not been declared|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|112|error: 'loadThread' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|112|error: 'thread' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|120|error: 'mutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|120|error: template argument 1 is invalid|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|120|error: 'audioMutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|120|warning: unused variable 'lock' [-Wunused-variable]|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|152|error: 'mutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|152|error: template argument 1 is invalid|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|152|error: 'audioMutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|152|warning: unused variable 'lock' [-Wunused-variable]|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|188|error: 'this_thread' has not been declared|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|188|error: 'mainThreadID' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|192|error: 'mutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|192|error: template argument 1 is invalid|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|192|error: 'audioMutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|192|warning: unused variable 'lock' [-Wunused-variable]|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|204|error: 'this_thread' has not been declared|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|204|error: 'mainThreadID' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|274|error: 'mutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|274|error: template argument 1 is invalid|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|274|error: 'audioMutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|295|error: 'loadThread' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|274|warning: unused variable 'lock' [-Wunused-variable]|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp||In function 'void {anonymous}::Load()':|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|383|error: 'mutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|383|error: template argument 1 is invalid|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|383|error: 'audioMutex' was not declared in this scope|
D:\Expack\Documents\GitHub\endless-sky\source\Audio.cpp|383|warning: unused variable 'lock' [-Wunused-variable]|
||=== Build failed: 27 error(s), 5 warning(s) (0 minute(s), 9 second(s)) ===|
````

**Comment by endless-sky** [comment]
You're probably using a compiler that does not have full C++11 support. I'm pretty sure that to get the Windows build working, I had to download a newer version of g++ from:

http://sourceforge.net/projects/mingwbuilds/

Ideally, you should be using g++ 4.8 or higher. Once you've downloaded the newer compiler, you'll have to change the Code::Blocks settings to tell it which compiler to use.

**Comment by Expack3** [comment]
Already did that using the mingwbuilds from http://mingw-w64.org/doku.php/download/mingw-builds since according to the page you linked to, the project was merged with MinGW-W64 and is now hosted in their repository. I still get the issue, however.

**Comment by endless-sky** [comment]
Did you switch Code::Blocks to use the new compiler? I don't have my Windows machine with me at the moment, so I can't check what it should be set to, but I remember having to manually specify the path to *each* of the tool-chain executables: the g++ compiler, the linker, etc. (4 or 5 different programs) in order to get Code::Blocks to use the right tools.

**Comment by Expack3** [comment]
Had to do that the first time until I figured out the exact folder to point Code::Blocks to in order to get it to auto-add them. Still doesn't work. I also tried forcing the G++ compiler to globally adhere to ISO C++ 11 standards, but that did nothing. Other that switch to the Visual Studio 2013 C++ compiler, I don't know what else to try.

**Comment by endless-sky** [comment]
When you install the compiler from mingw-builds, I think it gives you a choice between a "pthread" build and a "win32-thread" build. The "win32-thread" version does not include the C++11 threading libraries. If you installed that one, installing the "pthread" version should fix this issue. In case that doesn't help, here's some more info:

I'm using Code::Blocks 13.12 and gcc version 4.8.3 on Windows 7. On my system, the compiler was installed in the folder `C:\Program Files\mingw64\`. The `thread` and `mutex` headers are in:

`C:\Program Files\mingw64\x86_64-w64-mingw32\include\c++\`

And, in `C:\Program Files\mingw64\` is a `build-info.txt` file that includes the following info for the 64-bit build:

```
...
version : MinGW-W64-builds-4.2.0
user    : niXman
date    : 07.17.2014- 9:10:53 AM
...
[build data for 32-bit]
...
gcc version 4.8.3 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
```

After installing that, I modified the "Toolchain executables" settings as shown in the attached screenshot. I didn't have to modify any of the other settings (search directories, etc.).

![settings](https://cloud.githubusercontent.com/assets/11450262/8443191/96d35510-1f52-11e5-9e03-be1851ae9bf4.png)

If mingw-builds doesn't work for you even with the pthread version of the compiler, the CodeBlocks Wiki suggests an alternative installer that you might try, from [here](http://tdm-gcc.tdragon.net).

**Comment by Expack3** [comment]
The alternate installer, along with some modified paths to correctly point to the libglew32 and libopengl32 DLLs, allowed the source to compile successfully. Thanks for your help!

**Comment by endless-sky** [comment]
That's good news! I've updated the Windows [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions) and also fixed the SDL_platform.h file in the dev64 download. Let me know if you think anything is missing in the instructions.

**Comment by Expack3** [comment]
The only thing I see missing is the installer link is still pointing to the old project page for mingw-builds. To quote from the old project page:
> Projects joined MinGW-W64, and the new builds will be available on the MinGW-W64(https://sourceforge.net/projects/mingw-w64) site.

**Comment by endless-sky** [comment]
I've updated the build instructions to point to a MinGW-W64 build that uses the right threading library.
