### ISSUE TITLE
Option in outfitter to buy but not install

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#570]
I acquired a jump drive from a Korath. I landed on a planet, but accidentally clicked "Sell All", selling my jump drive. It's still in the outfitter, of course, but I need 20 free space to install it. It would be nice if we could just buy outfits and send them to our cargo.

**Comment by Pointedstick** [comment]
Seconded. I've wanted this feature from time to time as well.

**Comment by thenerdfreak** [comment]
Especially when I have a cargo-outfitted bactrian, and I have to go all the way across the Milky way multiple times to outfit a full fleet when I could just buy another bactrian and park my cargo bactrian at Polaris or something

**Comment by LocalGod79** [comment]
#852 (again)!
