### ISSUE TITLE
Liberate Delta Capricorni — no Pug ships in system, but can not complete mission

### ISSUE THREAD

**Issue by doxologist** [endless-sky/endless-sky#5701]
**Describe the bug**
When no Pug ships remain in Delta Capricorni, I land on Maker but am told there are still Pug ships in the system. I look and there is nothing... just the fleet I came with.

**To Reproduce**
1.Jump from Markab to Delta Capricorni.
2.Blow up all the things.
3.Land on Maker.
4.You need to blow up more things.
5.Depart.
6.There is nothing left to blow up.
<img width="1692" alt="Screen Shot 2021-02-06 at 7 53 19 PM" src="https://user-images.githubusercontent.com/78672642/107136086-27bd0380-68b5-11eb-9708-558aed33a655.png">

**Expected behavior**
When all the Pug ships have been destroyed, I expected to complete the mission or move on to the next thing.
<img width="1680" alt="Screen Shot 2021-02-06 at 7 53 23 PM" src="https://user-images.githubusercontent.com/78672642/107136091-2ee41180-68b5-11eb-8814-5f006415eaf9.png">

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build: `http://mcofficer.me:8080/job/endless-sky-win64/<build number>/`)

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by doxologist** [comment]
I left the system, stole a Jump Drive and put it on another Kestrel that I was using for a little bit... jumped back in and WHAMO! Mission complete.

**Comment by Terin** [comment]
Those missions usually involve bringing a passenger or some cargo to your destination, along with fighting the Pug. They were most likely stranded on a ship out of jump drive range accidentally, and we don't have the ability to specify which thing you're missing if you land on your destination. We'll either need to implement that, or have a more generic message of "Either you didn't blow up all the Pug ships, or your passenger/cargo got left behind." to fix this.
