### ISSUE TITLE
bug: Incorrect warning about failing mission when insufficient crew bunks in escort

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5708]
**Describe the bug**
When both my flagship and my only escort require more crew than that they have bunks, then I get the following warning upon depart; `"If you take off now you will fail a mission due to not having enough bunks available for 1 passenger. Are you sure you want to continue?"`

**To Reproduce**
1. Make sure to have no missions active.
2. Make sure you only have a flagship and one escort.
3. Exit game and modify the flagship and the escort so that they needs more crew than bunks are available.
4. Start the game, load your savegame.
5. Notice the error-message on depart.

**Expected behavior**
A warning that my ship needs more crew than that I have bunks would be nice. I at least didn't expect a message about failing missions when I have no missions at all active.
I would also expect the warning for both my flagship and the escort, not just for 1 of the two ships.

**Screenshots**
If required I can provide some screenshots.

**System (please complete the following information):**
 - OS: Debian Linux
 - Game Source: self-compiled
 - Version: recent master (7890c1f789ea79534ad2f9766f1d4ba37371369b)

**Link to save file**
Savefile [Bobby Bughunter.txt](https://github.com/endless-sky/endless-sky/files/5939883/Bobby.Bughunter.txt) is is attached, just click depart and notice the message.

**Additional context**
I didn't try to reproduce the issue without savegame editting, but I expect that it is also possible to trigger this situation when using weapons or outfits that require a lot of crew on ships that have only a very limited amount of bunks.

**Comment by tatami4** [comment]
I have added the fix to this in #5654. If you don't have enough bunks to house all your required crew, you won't be able to depart with that ship (should it only warn you?).

**Comment by petervdmeer** [comment]
I believe it should only warn. What if I capture some ship (after which both my flagship and the captured ship have insufficient crew) and then land on a planet without spaceport services? I think such planets don't allow me to re-hire crew, so if we don't allow ships with insufficient crew to depart from there, then those ships would be stuck.

Another part of this bug is the warning about failing passenger missions. If the game indeed fails passenger missions while the passenger bunks are available, then that would also be an issue.
I don't know if those situations are testable with unit-tests, if they are, then I suggest to write some unit-tests to cover those scenarios.

**Comment by tatami4** [comment]
> What if I capture some ship (after which both my flagship and the captured ship have insufficient crew) and then land on a planet without spaceport services?

I think you misunderstood me. You will not be able to depart only if some of your ships don't have enough space for required crew (for example, the ship requires 10 crew, but you have only 2 bunks). Present crew count of ship makes no difference.
Relevant code:
```	
else if(attributes.Get("required crew") > attributes.Get("bunks"))
	checks.emplace_back("insufficient bunks!");
```

> Another part of this bug is the warning about failing passenger missions. If the game indeed fails passenger missions while the passenger bunks are available, then that would also be an issue.

The game only writes a message and does not do anything. The part that cancels the missions is unrelated.
