### ISSUE TITLE
Can change flagship to ship parked on different planet/station in same system

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#5718]
Can take a ship from Glaze to Charon Station; then change flagship to one parked on Glaze, and leave from there.
 

**To Reproduce**
Two savefiles attached - "wherami" and "bad departure"
Load wherami - pilot flagship (a Bastion) from Glaze to Charon Station. 
Land.
Unpark the Osprey, move it into the flagship position. "bad departure"
Depart: though Spaceport is Charon, Osprey will depart from Glaze, Bastion will depart from Charon Station

**Expected behavior**
Should be unable to change to a flagship that isn't at Charon Station.

Ubuntu 20.04.1 LTS
Game Source: Feb. 9 continuous build, self-compiled
[Flora Phorm~bad departure.txt](https://github.com/endless-sky/endless-sky/files/5962541/Flora.Phorm.bad.departure.txt)
[Flora Phorm~whereami.txt](https://github.com/endless-sky/endless-sky/files/5962544/Flora.Phorm.whereami.txt)a

This is not system specific; was able to replicate using end-game ships on Hai-home and its moon.
[Vite Timorous.txt](https://github.com/endless-sky/endless-sky/files/5962557/Vite.Timorous.txt)

**Comment by Amazinite** [comment]
Duplicate of #5210.

**Comment by movingpictures** [comment]
Well, dang. I was so proud of myself.
