### ISSUE TITLE
FW Katya 3: drone hunting

### ISSUE THREAD

**Issue by Archophob** [endless-sky/endless-sky#5719]
**Is your feature request related to a problem? Please describe.**

very early in the Free Worlds storyline, Katya wants me to disable a republic surveillance drone and "salvage" the surveillance pod. By that time, i'm still a peaceful Taxi Driver, maybe piloting a bounder doing transport and small cargo missions from the job board. My first pilot outright refused to do it, and i later learned that i completely lost track on the FW story that way. My actual pilot accepted, but then broke the sequence by spending several months in Hai and Remnant space before using a Shield Beetle to catch the drone. The mission might be meant as introduction to boarding and plundering, but it should offer an alternative option for more peaceful pilots.

**Related Issue Links**
In this story:
https://steamcommunity.com/app/404410/discussions/0/412446890545408294/
the protagonist follows most of the FW storyline as intended, but gets the suveillance pod's blueprint from a pirate he happens to know and builds one using the maintenance bots of a Korath Systems Core.

**Describe the solution you'd like**

It would be really nice to have the line 

"I might get the equipment from a 'salvage specialist' on one of the Pirate planets"

added to the existing options
"Fine, i'll do it"
and 
"Count me out"

 This would require the "Surveillance Pod" Equipment to be added to at least one outfitter on a "southern pirates" planet. It would still be the players job to find the outfitter, bribe his way down to the planet, and survive entering and leaving a pirate system. Just like the conventional way, the mission will be completed by returning with a surveillance pod in your cargo.

**Comment by MCOfficer** [comment]
Two things i'd like to point out:

The FW campaign is about fighting. There has to be *some* point where the player is pushed away from being a peaceful taxi driver, and I'd rather have it be in a mission with ships that don't shoot back, and no permanent repercussions.

If you don't feel comfortable with the mission, you can leave it be indefinitely and pick it up whenever you want. Katya and Ijs will happily wait for years in the spaceport cafe. I'm not sure how you managed to break the sequence, but that's not supposed to happen.

**Comment by Amazinite** [comment]
The second mission after joining the Free Worlds involves fighting the Navy to defend Sabik, which is quite the battle. So as MCO says, we need to introduce the player to combat *somewhere* before things really get going. If any alternative is provided, such as getting a pod from a pirate who already stole one, I'd prefer that it also involve combat.

**Comment by Archophob** [comment]
with "sequence breaking" i meant that i actually had Katya and Ijs waiting a few years while i got my Shield Beetles, some Jump Drives, and already helped the wanderers make truce with the unfettered Hai. 

And getting in and out of a pirate system should be enough of a challange if you're still in Taxi Driver mode. Just add some Marauder Ravens to the system with the "salvage outfitter".

The drone hunting mission is different from all later combat missions, as you have to disable the drone all by yourself, making your flagship the prime target for the Navy ships that usually return to the system while you're boarding the drone. All other combat missions can be fought using a fleet of AI-piloted escorts. Sure, most taxi drivers don't have a fleet of combat vessels as escorts, but the game generally allows for this playing style.

And my primary point is: attacking the occupation fleet on the system where Katya got imprisoned feels the right thing to do. Attacking the navy before the war really starts feels just plain wrong - the "Taxi Driver" might not really want to be the person that causes a cold war to turn hot. Even if the Dereliction and Salvage Act of 2976 technically allows it. 2976, i guess my PC was in Kindergarten back then. Given my proposed alternative involves the Pirates, it should fit into the overall story. You later get enough options about how to deal with pirates - some were the more violent options backfire later. 

The most interesting parts of the story are those, where you're not railroaded, but have several options that all lead to progress. Games are about making decisions - should i fill my Heavy Warships with forward-facing Sunbeams or rotating Heavy Laser Turrest? Should i listen to the syndicate whistleblower? Should i try to dominate all the pirate planets? Should i really shoot at a Navy drone, or better try to get the Surveillance Pod from someone else?

**Comment by movingpictures** [comment]
It is possible to capture a surveillance pod without angering the Navy - you just gotta be exceptionally patient and then stupendously quick. Plotting the path out and locking it into the machine first is a key to this.
