### ISSUE TITLE
"The best way to be safe from pirates" hails can run off the screen

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#572]
Sometimes, hails that start with "The best way to be safe from pirates" are so long that they run off the screen, as shown in the attached screenshot:

!["The best way to be safe from pirates" off screen hail](https://cloud.githubusercontent.com/assets/6200170/12073091/7ad2a3f8-b0ce-11e5-9956-c31ff0196311.png)

(Screenshot at 1280x768 resolution)

These messages should be shortened so that they don't run off the screen.

**Comment by endless-sky** [comment]
Merged in your changes. Thanks!
