### ISSUE TITLE
Request: Change default keybinds to WASD-based

### ISSUE THREAD

**Issue by Terin** [endless-sky/endless-sky#5724]
**Is your feature request related to a problem? Please describe.**
The original Escape Velocity released in 1996, before even FPS games had officially adapted WASD as a standardized layout for movement. That layout let you place your hands naturally spread apart, with the left on movement keys with many other keys nearby, and the right on the mouse. Escape Velocity naturally gravitated towards the arrow keys, which were easy to understand, but are poorly placed on most keyboard, with the nearest keys being right control and numpad-0.

It's 25 years later, though, and WASD is a fairly universally understood control scheme, along with the advantages described about. Endless Sky also makes much heavier use of the mouse, both in spaceflight for controlling escorts or initiating auto-piloting, on the map for quickly picking out a destination to plot a route to, or selecting missions in the job board by directly clicking on systems.

The current arrow key scheme either causes you to have both hands on the keyboard, requiring you to take your right hand off to use the mouse when necessary, or a hand on the arrow key and mouse, where your left hand has no useful other keybinds nearby. With WASD as the baseline, we'd have a much more natural starting posture, that might result in less new players with bouncing off the game, or immediately having to dig into settings to rebind them.

**Related Issue Links**
#2291 is a request for keybind profiles. I would also like to see that, but would require a fair amount of code development (which hasn't been picked up on in 4 years), and community consensus on multiple profiles. This request, on the other hand, only requires coming to consensus with one profile, and does not preclude the idea of keybind profiles in the future.

**Describe the solution you'd like**
We should come to a rough consensus on a new set of default keybinds for Endless Sky, with WASD as the baseline for ship movement. For starters, Derpy has shared his keybind profile in the past:
![image](https://user-images.githubusercontent.com/4471575/108040569-16859c80-7003-11eb-8128-5eaadf95eecc.png)
I like a lot of keybinds here, especially moving fast-forward off of Caps Lock and to Tab. However, I consider keys like Q, E, R, and F to be the most ergonomically accessible keys from WASD, and having them default to secondary weapons and afterburners, features that I use very rarely, to not be as ideal. Instead, I think they should be on some of the most common actions a player would use.

These are my current keybinds, for reference:
![image](https://user-images.githubusercontent.com/4471575/108041293-f0acc780-7003-11eb-899f-f97ba12f1d75.png)
In my case, I have the Star Map on Q, hyperspace on E, and Land on F. These are common features I have quick access to, while Tab is used for targeting, as N is a little out of the ways if I'm scanning hostiles or looking for help. They may not make as much intuitive sense as "J for Jump" vs. "E for... Excessive Space Travel?", but the same could be said for E/F being a "Use" key.

Either way, though, I would be happy with most keyboard layouts that used WASD as a baseline. The differences I mention for Derpy and my keybinds are the difference between minor tweaks, and having to mostly rebuild them from the current defaults. What do you think about WASD as a new baseline? Are there any preferences for other keybinds you feel strongly about?

And just to stress, this would only be for new players or players who delete their configs, and would not overwrite your current binds.

**Comment by LukeMarlin** [comment]
What's good with the current setup is that it's more friendly to non-qwerty keyboards.
If the games switches to WASD, any player with a different layout than qwerty will have to start by going to config and change bidings, which is a really poor experience. As far as I know, most well designed games detect that and replace WASD by ZQSD if they notice you are using azerty keyboard for example.

If the change includes that detection and automatically adapt, why not, if it's WASD as default from everyone, it will be a degradation of the experience in my opinion.

**Comment by Archophob** [comment]
There are a lot of games out there that try to force the player to keep the left hand on the keyboard and the right hand on the mouse. I really like ES for being playable keyboard-only in most situations - i'm actually uncomfortable with the capturing system because it forces me to grab the mouse in-flight. The mouse is fine for down-on-planet activities, where no actions are time-critical, but in-flight, i want to keep my fingers on the keyboard. So, instead of getting more keys under the left hand, i'd prefer to have keyboard control on capturing.

The arrow keys are what i always use in old-style space exploration, even in 3d (eg. XbtF) and "S for scan" or "D to deploy fighters & drones" are keys that are easy to remember. So, it really depends on playing style, and if you want less intuitive keys for scanners and drones because you prefer left-handed steering, you already have the option to pick very your own key bindings.

So, from my point of view, no need to change anything in the vanilla game defaults.

**Comment by Terin** [comment]
Don't get me wrong, I'd love for Endless Sky to be fully and easily playable with just a keyboard. It's the straddling the line right now where the default keybinds suggest a game that's fully playable with just a keyboard, but then makes things like plotting jumps or selecting jobs much slower with a keyboard than a mouse. 

A different default key layout would also not preclude playing with just a keyboard, or improvements we could make to a keyboard-only interface. It would just play into the strengths of the game from the jump, rather than players having rework it from the top down. And even though there's no time pressure to swap from keyboard to mouse on planet, you still swap between the two frequently, and having to move your hands around that much can still be a pain, when a WASD-based layout lets you keep them in the place for all situations except typing names.

Something like non-QWERTY layouts breaking the binds definitely is a much bigger issue, though. Seems like SDL does support detecting keycodes/key locations rather than a direct key, so it could be theoretically possible, but that's adding code vs. just changing some keybinds.

> i'm actually uncomfortable with the capturing system because it forces me to grab the mouse in-flight.

Which part? Do you mean specifically picking out a ship to board, or the actual boarding interface? Since you can hold down alt to see what keys are shortcuts for each button.
