### ISSUE TITLE
Zooming in/out with a trackpad pinch cancels autopilot

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5729]
**Describe the bug**
While your autopilot is set, changing your zoom level using a pinching motion on a trackpad disengages autopilot.

**To Reproduce**
1. Set your autopilot to do something (e.g. land, jump).
2. Change your zoom level by pinching on a trackpad.
3. Observe that your autopilot gets canceled.

**Expected behavior**
Zooming in and out should not cancel your autopilot under any circumstances.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: self-compiled
 - Version: Latest commit as of posting (https://github.com/endless-sky/endless-sky/commit/fbb4f19c72c9a4f2907b525da296ee1e4cb96457)

**Link to save file**
N/A

**Additional context**
Zooming in and out using a mouse wheel, the +/- buttons, and even by dragging two fingers in the same direction on the trackpad does not cancel autopilot. It is only the pinching motion/dragging two fingers in opposite directions that causes the game to zoom in or out while also canceling autopilot.

**Comment by Amazinite** [comment]
Relevant bits of code, as I get the "Disengaging autopilot," message.
https://github.com/endless-sky/endless-sky/blob/6b976b147e9f345558ed4c68c908e87c6fb47794/source/AI.cpp#L342-L351

https://github.com/endless-sky/endless-sky/blob/6b976b147e9f345558ed4c68c908e87c6fb47794/source/AI.cpp#L44-L51

**Comment by Amazinite** [comment]
Can't reproduce using a mouse wheel. So might be that this has been an issue for a while, but I've really only recently been using the trackpad often.

**Comment by Amazinite** [comment]
Dragging two fingers down or up the trackpad causes the view to zoom in and out respectively without disengaging autopilot. Using two fingers to pinch or move away from each other also zooms in and out respectively, but does disengage autopilot.

**Comment by Terin** [comment]
Which laptop is this? Seems like it's something in that trackpad firmware that's causing some other kind of input to fire when pinch-zooming/scrolling.

**Comment by Amazinite** [comment]
It's an Asus Vivobook. Turns out it's sending the afterburner command. My afterburner is bound to left control. Changing it another key stops pinch zooming from canceling the afterburner, so that action is being read as a left control input.

**Comment by Amazinite** [comment]
Closing this since I've tracked it down to the trackpad sending a left control input. Seems no different to me than changing volume sending a C input, or keyboard ghosting. That is to say it's not something we should worry about since it's more an issue with the user's computer than the game itself.
