### ISSUE TITLE
Bug: Escorts path through systems with the 'Hidden' tag

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5731]
**Describe the bug**
Systems with the Hidden tag are supposed to effectively non-existant. However, despite the fact that the player can't jump to said systems, the player's escorts *can* do so.

**To Reproduce**
1. Go to Levana with some escorts that have Jump Drives.
2. Tell them to hold position.
3. Return to Arculus
4. Use the Gather command to order the escorts to return.
5. Watch the location of the escorts, and note that they travel through Postverta.

It is worth noting that this also works in reverse.

**Expected behavior**

**Screenshots**
This screenshot is of my escorts flying through Postverta to go from Arculus to Levana.
![Ships in Postverta](https://user-images.githubusercontent.com/32169904/108585923-75e7f300-7308-11eb-89be-9ce7733915f4.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Git-Hub artifacts, continuous
 - Version: continuous as of hash 1eec2a2 (February 12th 2021)

**Additional context**
Originally reported by upvoteotter on the Endless Sky Community discord. Thank you for spotting it!

**Comment by Amazinite** [comment]
#6127 would resolve this.
