### ISSUE TITLE
Bug: Hidden doesn't actually prevent someone from going to a system

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5734]
**Describe the bug**
As originally understood, I believed the `hidden` tag on Postverta was supposed to basically act like an "off" switch that prevents it from being visible or accessible, period.

However, upon reading how it has subsequently been defined in the wiki mapdata page, I have realized that my understanding was erroneous, and it now merely conceals a system from indirect detection and does *not* actually prevent it from being accessed.

**Expected behavior**
What I expected was that, so long as a system has the `hidden` tag, it is hidden from view on the map, hyperlinks to and from it are not shown, arrows on the minimap do not point to it, and it cannot be targeted for any form of hyperjumping.

**Proposed Solutions**
**1.** 
A new system attribute `invisible` is introduced, which acts as an "off" switch that prevents a system from being seen or accessed in any way, and hides any hyperjump or wormhole links connecting to it.

**2.**
The `hidden` attribute is corrected to provide the expected functionality.

**3.**
I PR a fix that severs all the links to Postverta in the starting map, and have those links be re-established by the event that removes the `hidden` tag. As there will be no links to the system, the `hidden` tag will effectively act like an `invisible` tag.

*preference*
Option 1 is the preferred option, as I can see situations where the currently described `hidden` tag could have very interesting uses for encouraging gameplay and rendering exploration via JD more challenging, without actually locking out an area like the `invisible` functionality would.

Option 2 Is reasonable. As an advantage, it already exists in the code and just needs to be adjusted to provide all the intended functionality. As a downside, it loses the usefulness for creating areas that are harder to explore, but can be "revealed" through careful exploration without needing events.

Option 3's main strength is that I can implement it immediately, since that is just a content change, and requires no changes to the mechanics. Thus it does not require any work on the part of the Devs.

**Background**
This bug was revealed through testing for PR #5732 , which itself is a fix for issue #5731 . Testing revealed that - should someone manage to gain access to any of the other systems in the cluster introduced in the Cognizance PR, they could then follow the links to Postverta and access it. This is contrary to the story and the lore, which specifically revolves around the system being completely cut-off from *all* surrounding systems, not just concealed from the currently existing systems. Just to be clear, this is an important plot point that will be a recurring detail in future missions; not just a gating mechanism.

**Conclusion**
If someone is interested in implementing option 1, then that would be great; but in the meantime I will implement option 3 so that Postverta will have the proper behaviour in the upcoming 0.9.13 release without necessitating additional engine changes.

**Comment by warp-core** [comment]
Fixed by #5735.

This behaviour of `hidden` systems still being accessible via hyperlinks doesn't appear to be a bug: the commits involved in adding the functionality make it quite clear that this is intentional.
