### ISSUE TITLE
Navy vessel follows cloaked Starling

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#5739]
**Describe the bug**
At entry point (ish) to F/W missions - when followed by the Navy warship from New Wales/Algorel in a Starling, the Navy vessel still follows even when the Starling is cloaked.

I realize it's pretty unlikely that many will tinker with the Remnant before the F/W missions are done, but hey.

To reproduce: Load the attached savefile, which starts on New Wales after overhearing the Navy officers chatting.
Chart a path back to Glaze.
Launch.
Observe the navy vessel launch.
Cloak.
Jump.
Navy vessel will follow. 
[Tinker Hammer~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/6016630/Tinker.Hammer.previous-1.txt)

**Comment by Zitchas** [comment]
People playing the Remnant storyline before the FW one isn't as unlikely as you might think. Some of us just do the Remnant story and ignore the FW entirely. 

Good spotting!

**Comment by tatami4** [comment]
@Zitchas how would you recommend to solve this? Right now most NPCs (that is, NPCs that do not have a defined system (as far as I understand)) in other systems than the player are treated like player's escorts. There is one way to solve this in a simple way: disallow the NPC to follow player if the player is cloaking. But this creates a problem: "normal" mission NPCs (that is, all except the ones you must evade) also would not follow the player if the player is cloaked. Would this solution be acceptable, or should the NPCs you must evade behave differently from all other NPCs?

**Comment by Zitchas** [comment]
I'm probably not the best one to offer suggestions/solutions for coding/engine problems.

What I'd expect, from a content writer perspective, is that a non-escort ship that is supposed to be tracking/following/surevilling the player should probably jump around randomly whenever the player is cloaked, then as soon as the player decloaks, they start pathfinding from wherever they are to wherever the player is.

**Comment by vitalchip** [comment]
A couple of changes in Ai::MoveEscort should do the job. Your own ships will follow the flagship, cloaked or not (same as now) but NPC ships which have latched onto you as a parent will not follow when your ship cannot be targeted but will pathfind to you if you uncloak in another system.
<img width="1100" alt="cloak follow" src="https://user-images.githubusercontent.com/65342577/108845820-cb0c5900-75d5-11eb-9b9c-281bfdc1668e.png">

**Comment by tatami4** [comment]
Yes, I know it is easy to do this _if_ you apply want to apply it to all NPCs. But I think that friendly NPCs should follow you in the same way as your escorts, since presumably you tell them where you are.

**Comment by vitalchip** [comment]
Yep, that's how I'd do it. I'm not even entirely sold on your own ships following when you're cloaked.

**Comment by petervdmeer** [comment]
We could also try to address the cloaking itself, for example to make cloaks don't work during a jump (hyperspace and jump-space). There are already quite a number of open issue-tickets that discuss on cloaking being too powerful.
For the in-story Syndicate/Nukes mission we could add an arrival distance to compensate for the time the cloak needs to activate after jumping (and it gives the player some work to dodge, but that shouldn't be an issue).

**Comment by Archophob** [comment]
When would you cloak while doing escort missions? It's absolutely okay if any NPC ship following you would also need to see you, friendly or not.

**Comment by movingpictures** [comment]
FYI, for relevance - I find that for whatever reason, the flagship seems to
be targetted more often than other vessels. In high-risk situations I've
found having a starling in the area, cloaked, while various other escort
vessels do the dirty work - to be quite successful.

That said, my original observation appears to have triggered the nugget of
a "is cloaking too powerful" discussion. I think a reasonable tweak might
be that escort vessels cannot follow the flagship if the flagship jumps
while cloaked. It stands to reason - if missiles can't track a cloaked ship
because radar waves/light/infrared signatures simply can't be picked up,
then radio waves (of which radar is a subset) shouldn't be transmissible -
ie: to communicate a forthcoming jump.

I haven't tested the cloaking theory on the Deep storyline that leads to
the Bactrian city-ship licence - where the player's ship is followed - to
see if the same holds true. From the discussions, it seems those tracking
vessels would also be unable to follow the player's ship. (If someone has a
save from that part of a recent game, I'll plug a starling in and check?)

That said, I'm going to suggest another solution that fits in with this
discussion: *make it so that it's not possible to land a ship while
cloaked. *Then at least, there's some plausible "folks were watching for
your ship" element that could be suggested/introduced/whatever.

**Comment by petervdmeer** [comment]
I like the suggestion to not allow a ship to land while it is cloaked.
Cloaked ships cannot use weapons, so if we want to explain de-cloaking during jump (as I suggested earlier), then we could come up with an in-lore explanation like; "Cloaking cannot hide the propulsion effects of the nuclear fusion reaction that happens during a jump" (per the Hyperdrives description).

This also addresses Archophobs concern that ships would need to see you in order to follow you. Cloaking would still be a very valuable in-system feature.

**Comment by PeacefulPotato** [comment]
I also noticed this issue, during the Sheragi missions. I tried to cloak to avoid the ship as the mission requested but the ship just kept following me, even within the system (which is still faster than light by the way, as it takes less than 4 minutes to get from the Sun to Earth, but that's probably there so the game isn't super slow).

**Comment by UnorderedSigh** [comment]
Fix is at #8324
