### ISSUE TITLE
Bug: Autopiloting is disabled traveling through wormholes

### ISSUE THREAD

**Issue by Terin** [endless-sky/endless-sky#5744]
**Describe the bug**
Introduced by #5733 / 26c1490, when setting up a route that travels through wormholes, your autopilot will stop after having landed on a wormhole, requiring you to hit jump/land to continue.

**To Reproduce**
1. Loading a pilot with a Ultima Thule explored/Terminus explored with a quantum keystone.
2. Set a route to a system on the other side.
3. Hit jump to begin the autopilot sequence through that route.
4. Observe the autopilot being disabled after traveling through the wormhole.

**Expected behavior**
The autopilot will continue to move the ship to the next jump/wormhole after traversing the first one.

**System (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Source: Self-compiled
 - Version: 774cd9f

**Link to save file**
Pilot with route set through Terminus
[Wormhole Travel.txt](https://github.com/endless-sky/endless-sky/files/6025599/Wormhole.Travel.txt)

**Comment by tatami4** [comment]
Yep, I need to better test my PRs.

**Comment by Terin** [comment]
It's all good, we've got a couple avenues for a fix already, and the unstable update as a buffer (although we should probably get it out before that cutoff).
