### ISSUE TITLE
Suggested tweaks to the Cargo Auxiliary

### ISSUE THREAD

**Issue by Bardagh** [endless-sky/endless-sky#5746]
**Is your feature request related to a problem? Please describe.**
The cargo-variant Auxiliary only has 450 cargo space, less than a Behemoth (490) or Bulk Freighter (600) despite its greater mass / difficulty of acquisition (aux 820, behemoth 540, bulk freighter 870).

**Describe the solution you'd like**
I suggest the cargo space be increased to somewhere in the vicinity of 560-600. Bulk freighters are much more fragile, cheaper, and much easier to obtain, and Behemoths are *much* smaller and fill a similar role to the Cargo Aux.

I would also suggest the description be changed to read "large numbers of troops or large amounts of cargo transported with a guarantee that they'll reach the destination" instead of "large amounts of troops or cargo transported with a guarantee that they'll reach the destination".

**Comment by Amazinite** [comment]
The suggested change to the description is redundant. The descriptor "large number of" refers to all items in the subsequent list ("troops or cargo"), so we don't need to say it again for each item in the list.

The cargo space on the Auxiliary is purposefully lower than other human freighters. The design purpose of the Auxiliary when used for cargo transport is to have a very tough freighter to transport a substantial amount of cargo. If you want to transport more cargo in a single ship then that's where the Bulk Freighter comes in; it has more cargo at the expense of less defenses. This is in fact the same purpose as the Behemoth or Hauler: a ship that carries less cargo than similarly sized ships (Behemoth being similar to Bulk Freighter and Hauler being similar to Freighter) in exchange for better defenses. The cargo Auxiliary simply takes this idea and goes further with it, having even more defenses and less cargo than the Behemoth.

**Comment by Anarchist2** [comment]
Don't forget about the Aux's fighter bays either. Swapping out the Dropships to stock Boxwings raises cargo up to 770, without even considering Cargo Expansions on the Boxwings.

**Comment by Bardagh** [comment]
> 
> 
> The suggested change to the description is redundant. The descriptor "large number of" refers to all items in the subsequent list ("troops or cargo"), so we don't need to say it again for each item in the list.
> 
> The cargo space on the Auxiliary is purposefully lower than other human freighters. The design purpose of the Auxiliary when used for cargo transport is to have a very tough freighter to transport a substantial amount of cargo. If you want to transport more cargo in a single ship then that's where the Bulk Freighter comes in; it has more cargo at the expense of less defenses. This is in fact the same purpose as the Behemoth or Hauler: a ship that carries less cargo than similarly sized ships (Behemoth being similar to Bulk Freighter and Hauler being similar to Freighter) in exchange for better defenses. The cargo Auxiliary simply takes this idea and goes further with it, having even more defenses and less cargo than the Behemoth.

Countable vs. uncountable or semi-countable, bu that's a fine point I'm not keen to press.

> 
> 
> Don't forget about the Aux's fighter bays either. Swapping out the Dropships to stock Boxwings raises cargo up to 770, without even considering Cargo Expansions on the Boxwings.

Yeah, I realized that after I posted this. I still think it could use a minor cargo buff though.

**Comment by Bardagh** [comment]
> 
> 
> The suggested change to the description is redundant. The descriptor "large number of" refers to all items in the subsequent list ("troops or cargo"), so we don't need to say it again for each item in the list.
> 
> The cargo space on the Auxiliary is purposefully lower than other human freighters. The design purpose of the Auxiliary when used for cargo transport is to have a very tough freighter to transport a substantial amount of cargo. If you want to transport more cargo in a single ship then that's where the Bulk Freighter comes in; it has more cargo at the expense of less defenses. This is in fact the same purpose as the Behemoth or Hauler: a ship that carries less cargo than similarly sized ships (Behemoth being similar to Bulk Freighter and Hauler being similar to Freighter) in exchange for better defenses. The cargo Auxiliary simply takes this idea and goes further with it, having even more defenses and less cargo than the Behemoth.

Countable vs. uncountable or semi-countable, but that's a fine point I'm not keen to press.

I see your point regarding its niche.

> 
> 
> Don't forget about the Aux's fighter bays either. Swapping out the Dropships to stock Boxwings raises cargo up to 770, without even considering Cargo Expansions on the Boxwings.

Yeah, I realized that after I posted this. I still think it could use a minor cargo buff though.
