### ISSUE TITLE
Trigger action when save file is eddited.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#575]
I'd like to see the game react in some way if it detects some sort of sudden change in your save file..particularly if you edit in money. It would be hilarious if you add money to your save file and suddenly bounty hunters are coming after you for counter fitting. More pirates should attack you also.

Maybe the player shouldn't be allowed to at keep the money all, and if they try it there assets are frozen by the bank.

Of course, you can't stop a player from cheating if they really want to, but It would require that they purposely put in a cheater plugin.

**Comment by Thunderforge** [comment]
How will this make the game more fun? If the player is adding money, then it's probably because they are getting bored with the grind of doing missions and paying off loans. Punishing them for trying to get past a boring part, and forcing them to remain there, is probably going to get the player to quit playing.

Besides, it's a single-player game. Nobody but the player is affected if they cheat. So if they think it will be more fun to cheat, I say let them cheat.

**Comment by frameworld** [comment]
Cheaters stick to a game for less time.
Let's get rid of the cheating part of the community! ;)

The easiest way to prevent cheating would be to make the save file binary with a cross-version ZIP-compression of words and values.

**Comment by omagasohe** [comment]
@frameworld Why worry about cheaters? They move on, and there are legitimate reasons that editing save files are a god send, especially when developing plug-ins or testing(mostly mission flags). 

@Thunderforge Agreed!

@mdsmestad Personally I find games that get cute like that annoying. It's a game,

**Comment by frameworld** [comment]
Neither binary nor check-sum would stop me from seeing the content like now.
It's just a bit work for a tool - most peoples don't do that.

**Comment by Thunderforge** [comment]
Also don't forget that you can still "cheat" by writing a plugin with a mission that gives you an astronomical number of credits, or even just adding a few zeroes to the mission rewards of the default missions. 

Heck, I admit I did that myself back with Escape Velocity classic and it didn't stop me from being a fan of the series (and non-cheater for EVO and EVN). Anti-"cheating" measures probably would have made me less interested in the series, and eventually in Endless Sky.

It's a waste of time to add countermeasures like these to a single player game and likely to more inhibit plugin developers and testers than make it more fun for players who are inclined to give themselves more credits.
