### ISSUE TITLE
(Feature Request) Govenment Marking System Revamp

### ISSUE THREAD

**Issue by Plip-Plop** [endless-sky/endless-sky#5750]
# Problem:
Currently, visual ship identification markings are localized to each government by swapping the color channels of specific colors(usually red) to the color or colors of the target government. Since this is government specific, there is very little room for unique ship colorings.

# Extra:
Government definitions would need to include a list of marking types they support. (Figure 3)
Unless otherwise specified, assume that these are acting in the ship definition. 
To grandfather in the old technique, the clause "shipcolor" would be set to one for any ship that is using the new system. (Figure 0)
# Solutions:
## Main Solution:
Define swizzle areas by color for each type of marking. (Figure 1)
### Example:
Exemplar example.
![Swizzled Exemplar](https://user-images.githubusercontent.com/69060286/109361514-48d69b80-7846-11eb-906b-bdbb93546415.png)
>
	coloring
		"light main color" (e2c828,d59517)  # A range of colors is selected to allow for lightness shifts. If a range is used, the lightness of the sprite color is adopted for the final appearance in game.
		"dark main color" (d66de3,6f47e1) "light main color" # the "light main color" defined by the government is the backup color
## Secondary Solutions:
1. Define areas to apply color by defining triangle polygons. (Figure 2) (This is my least favorite solution)
2. Define color modification areas with a svg(Scalable Vector Graphics) file.

# Mockups:
Figure 0:
>
	shipcolor 1
Figure 1:
> 
	coloring
		"light main color" 5fe24a # Hex color code for the color on the sprite that should be swizzled.
		"medium main color"  4ae2ce 888e87 # Second color is backup in case that marking type is undefined.
		"dark main color"  ce4ae2 
		"complementary color"  e24a5f 5a5e59 # If the ship's government uses a bicolor color scheme, this is what would be recolored for the second color.
Figure 2:
>
	coloring
		"light main color"
			(99,6|100,98|188,92) # (Point A x, Point A y|Point B x, Point B y|Point C x, Point C y)
		"medium main color"
			(48,251|125,255|33,92)
			(125,117|125,225|311,92)
		"dark main color"
			(255,330,184,264,332,247)
		"complementary color"
			(131,273|194,345|1,361)
Figure 3:
>
	coloring
		"light main color" f4b546
		"complementary color" 000000

**Comment by Amazinite** [comment]
> Currently, visual ship identification markings are localized to each government by hue-shifting specific colors(usually red) to the color or colors of the target government. Since this is government specific, there is very little room for unique ship colorings.

The game doesn't actually hue shift images, [it swaps the color channels](https://en.wikipedia.org/wiki/Swizzling_(computer_graphics)). Actual hue shifting is something that [has been looked into in the past](https://github.com/endless-sky/endless-sky/pull/3591#issuecomment-403163222), but was deemed too expensive computationally. So going beyond hue shifting to somehow only shift certain parts of an image would I imagine be even more expensive.

**Comment by Plip-Plop** [comment]
Do you change the color once and save the changed image or change the color every time the ship is seen by the player?

**Comment by Amazinite** [comment]
Shaders are drawn each frame right now. That is the main reason behind #2442, as each ship is calculating the sobel filter in the shipyard or outfitter each frame.

**Comment by Plip-Plop** [comment]
I am closing this issue. It seems to me that this is extremely unlikely to be implemented, especially as this PR([#3591](https://github.com/endless-sky/endless-sky/pull/3591)) was closed.
