### ISSUE TITLE
Disappearing Missions

### ISSUE THREAD

**Issue by TheDeathStar3** [endless-sky/endless-sky#5754]
**Describe the bug**
All active missions disappear, does not matter if new ones are accepted.

**To Reproduce**
I do not know what I did.

**Expected behavior**
I can continue the missions and storylines I was doing.

**Screenshots**

**System (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Game Source: Steam
 - Version: 0.9.12

**Link to save file**
[Save File.txt](https://github.com/endless-sky/endless-sky/files/6055506/All.Storylines.txt)

**Additional context**
The last time I edited the save file was a while ago and I have been playing a lot since.
I do have a plugin but I installed that a year ago and I have not touched the plugin since.

I also feel like it is related to https://github.com/endless-sky/endless-sky/issues/3740

**Comment by petervdmeer** [comment]
Looks like the very first keyword of your save game has an additional character (it says `spilot` instead of `pilot`). Could that be the issue?

**Comment by TheDeathStar3** [comment]
That fixed the saving issue. but not the mission issue.

**Comment by tatami4** [comment]
At least for me (after changing `spilot` to `pilot`), if I depart from the planet and land again, the missions reappear.

**Comment by TheDeathStar3** [comment]
A mission about Rand does but that is not where I am up to in the FW Storyline

**Comment by TheDeathStar3** [comment]
If you try to do that with rand mission you get this:
![Screen Shot 2021-03-01 at 5 51 43 pm (2)](https://user-images.githubusercontent.com/54761256/109461877-e6380680-7ab6-11eb-97ea-3c3a6311a03f.png)

**Comment by Amazinite** [comment]
There was just a new release. Can you replicate this behavior on v0.9.13? Since you're using Steam, you'll need to opt into the beat branch. Go to your Steam library > right click Endless Sky > Properties > Betas > select beta from the drop down box.

**Comment by McloughlinGuy** [comment]
I had something else like this happen. Did you switch from continuous to 9.13? Because I am pretty sure this is an unintentional side effect of the switch.
