### ISSUE TITLE
Remnant: Salvage 1 screws up Wanderers start

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#5757]
**Describe the bug**
Currently, Remnant Salvage 1 sets "human cultural data" which later prevents you from getting a translation device in "Human Cultural Archives" during the Wanderer start. Actually, I think the two missions prevent each other from happening, but the remnant mission preventing the Wanderer start is more problematic. 

I can't figure out how to post properly formatted code here but in the game files "wanderers start.txt" and "remnant missions.txt" it should be clear that both "Remnant Salvage 1" and "Human Cultural Archives" have "not "human cultural data"" to offer and "set "human cultural data"" on complete. 

What happens from the players perspective is that they go to Greenwater to get the translation device only for the next part of the mission chain not to offer. 

**To Reproduce**
1. Go do most of the remnant missions up to remnant salvage 1
2. Go visit the wanderers for the first time and begin the mission chain
3. "Human Cultural Archives" will not offer on Greenwater when it is supposed to until "human cultural data" is deleted as a condition from the save file

**Expected behavior**
The mission should offer even if you've done the remnant mission 

**System (please complete the following information):**
 - OS: Linux, continuous build as of a week or two ago

Overall, I think this is an easy bug fix but I've never put together a pull request or anything before so I have no idea how

**Comment by Zitchas** [comment]
Thanks for reporting a problem!

These two missions were changed in continuous to interact with each other, such that the player is only ever sent to get the cultural archives a single time, and they make a copy of it on their ship's computers. 

The way it is supposed to work is that whichever of the two missions you get to first runs as normal. Then whichever of the two you do second will instead have an altered dialog where the player tells the NPC that they already have said data. 

The subsequent missions are supposed to flow from there naturally.

Just looking at the data files; I'm having trouble following that path. We'll have to get @Amazinite 's input on this; he's the one who setup the branching conversation and made these changes.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/78fc7d8678f10008362b2b2e2dc47e9da1b88b33 Looks like I grabbed the wrong condition when I fixed this last time. Should work now.

**Comment by movingpictures** [comment]
Having just done the Remnant cultural data in one of my recent "I'm really trying hard to break the daily build" efforts, I remember that the script for the player reads something like "You think about getting a second, but decide not to" or something. If Zitchas' changes are, in fact, how things operate, then a change to "Given the price you purchase a second copy: you never know when it might come in handy" or something.

**Comment by Amazinite** [comment]
We can deal with the text later, but this bug is fixed now.
