### ISSUE TITLE
Independents hostile before Men becomes Independent

### ISSUE THREAD

**Issue by Archophob** [endless-sky/endless-sky#5758]
**Describe the bug**

The "Independent" faction officially appears when the former pirate System Men becomes independent during the FW campaign. Unfortunately, you can encounter "Independent" ships earlier, if you do the "City-Ship-License / Project Hawking" storyline before choosing sides in the FW campaign. Eliminating those ships in the Deep will make you hostile to the not-yet-founded independent faction in the south.

**To Reproduce**

During the "project Hawking" story, you will be followed by ships flying pirate coulours, but using "independent" FFI. Landing on Midgard, one of them will bombard you, regardless wether you killed them before or not. IF you killed them, however, your reputation with the "independent" will stay negative when later the "independent" will officially be founded.

**Expected behavior**

"Project Hawking" obviously has only to do with the Deep and Belzebub, but is nothing about the Independence of System Men. The Independent Faction of System Men should not care about what you did to those annoying ships in the Deep.

**Additional context**
while using the "independent" faction to have those ships fly "pirate colours" without being identified as actual pirates, might be a nice idea, your reputations with the "Independent" faction should be reset once that faction is officially founded.

**Comment by clifflocked** [comment]
There is another "Independent" faction, "Independent (Killable)". I am fairly certain that this is only used once during Rim Archaeology, when you retrieve the laser excavation equipment. I doubt that the problem would persist if we made the ships "Independent (Killable)". (Also, to my knowledge, the Independent (Killable) faction will lose reputation if you kill their ships. Should this be changed to what happens with the Indigenous Lifeforms, where they never permanently take reputation loses?)

**Comment by Amazinite** [comment]
I decided to take the route of upping the rep of the Independent government.
