### ISSUE TITLE
Quantum keystone mission offered with Puffin

### ISSUE THREAD

**Issue by diggorygray** [endless-sky/endless-sky#5760]
**Describe the bug**
[If in Remnant space you sell your ship for a Puffin, then you are offered a quantum keystone as it is assumed you have none (as the Penguin has one 'built-in'. ]

**To Reproduce**
Steps to reproduce the behaviour:
1. Do the Remnant missions to scan void sprites and gain access to Puffin.
2. Sell your ship & buy the Puffin.
3. Land and take off a few time in Remnant space...
4. Get given a keystone when you don't need one.

Or use the save file below:
1. Take off and land on a populated Remant planet.
2. Keystone is offered..

**Expected behavior**
As the stock Puffin can transverse worm holes you shouldn't need to be offered a keystone.

**System (please complete the following information):**
 - OS: [Mint Linux (based on Ubuntu "Focal")]
 - Game Source: [self-compiled]
 - Version: [commit hash 78fc7d8"]
**Link to save file**
[https://pastebin.com/TLJbdMA9 ]

**Additional context**

**Comment by diggorygray** [comment]
Ok, I'll close this as it's covered by a fix already.
Thanks :)

**Comment by Amazinite** [comment]
Fixed with https://github.com/endless-sky/endless-sky/commit/ab998384084383b5654fe33da597d0866e530962 by reverting the previous change that was made.
