### ISSUE TITLE
Completing Remnant "cultural data" mission prevents Hai mission

### ISSUE THREAD

**Issue by terrabite3** [endless-sky/endless-sky#5762]
**Describe the bug**
The "human cultural data" flag is used by both the Hai and Remnant missions for fetching the library data. Completing the Remnant mission first breaks the Hai misison.

**To Reproduce**
1. Complete the Remnant mission that involves traveling to Alexandria and returning with the library data.
2. Begin the Wanderer mission line. Get the "Wanderers: Translation Machine" mission.
3. Travel to Greenwater as requested.
4. Upon landing on Greenwater, the "Wanderers: Translation Machine" mission is gone and no dialog appears.
5. Removing the "human cultural data" flag from the save file before landing on Greenwater resolves the issue.

**Expected behavior**
The Wanderer mission line can be continued even if the Remnant mission is completed first.

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu
 - Game Source: self-compiled
 - Version: commit hash ec8f3e0080f9ca7c6bc556646a5bee1b05b4e19e

**Comment by Amazinite** [comment]
#5757
