### ISSUE TITLE
Set other ships on a different route.

### ISSUE THREAD

**Issue by TheDeathStar3** [endless-sky/endless-sky#5764]
**Is your feature request related to a problem? Please describe.**
I do not like how some ships (it could be mine or some escorts) decide to go a route they can not go. For example, my flagship can go somewhere because it has a jump drive but my escorts do not have a jump drive

**Describe the solution you'd like**
I would like it if we can choose the ship's route on the map or something. If I wanted one of my ships to go to Sol and my own fleet to go to Alpha Centauri than I can go to the map and tell the ships that I want to go to sol go to sol and I can have my remaining fleet go to Alpha Centauri.

**Describe alternatives you've considered**
Or maybe if I have a destination for my fleet than my escorts focus on getting to the destination instead of following my fleet.

**Additional context**
This is just an idea, I am still pretty happy with what happens in the game.

**Comment by tehhowch** [comment]
In the 0.9.13 release, you can enable a preference in the UI and then while in flight, tell selected escorts to travel to another system when local combat has ended. See # for more details.

In general, it is your escorts' job to protect you, so they will follow you system-by-system until they can't. You may notice that the planned jump route can be several colors on the map; green means everyone can follow without a pause for refueling.

**Comment by TheDeathStar3** [comment]
Ok thanks, Sorry I keep asking questions that seem to already be answered in the new release.
