### ISSUE TITLE
outfit buy/sell with left-click/right-click

### ISSUE THREAD

**Issue by Zavindur** [endless-sky/endless-sky#5771]
**Is your feature request related to a problem? Please describe.**
When I'm customizing ships, I find needing to move the mouse all the way across the screen to click buy or sell adds extra busy work.

**Related Issue Links**
I didn't see any related requests on this.

**Describe the solution you'd like**
When an outfit is already selected.
Any left-clicking on the outfit should function as though the 'buy' button was pressed.
Any right-clicking on the outfit should function as though the 'sell' button was pressed.
The multipliers 'ctrl' 'shift' 'alt' should work the same.
The code change could be to press the buy/sell buttons whenever the player already have an outfit selected that they are clicking.

**Describe alternatives you've considered**
An alternative, could be to make it so when an outfit is selected; the buy/sell buttons appear near the selected outfit;  I feel this isn't practical though because it would require reworking the ui.

**Additional context**
This change shouldn't interrupt with the current game experience. Players that prefer to use the UI Buy/Sell buttons may continue to do so.
Imagine being able to just double-click an outfit you want to install? (1st click to select it; 2nd click to purchase)

**Comment by Amazinite** [comment]
Do you know of the keyboard shortcuts B and S for buy and sell respectively?

**Comment by Zavindur** [comment]
> Do you know of the keyboard shortcuts B and S for buy and sell respectively? Are those not easier than moving your mouse? You can also navigate the currently selected item using the arrow keys, so it’s possible to not need to use the mouse to get what you need from the outfitter or shipyard.

well i was just looking at the code and saw that:
	if(hoverButton == 'b')
		return CanBuy() && ShipCanBuy(ship, selectedOutfit);
	else if(hoverButton == 's')
		return CanSell() && ShipCanSell(ship, selectedOutfit);
than came back here to try to close this; yea, had no idea that b and s were hotkeys.

**Comment by Amazinite** [comment]
Most if not all clickable buttons have keyboard shortcuts. Keyboard shortcuts can be revealed by holding alt, which who’ll underline the letter in any word on a button for the key that activates it.
