### ISSUE TITLE
(Feature request) Adding a button to "Plugins" screen

### ISSUE THREAD

**Issue by Wizardon777** [endless-sky/endless-sky#5778]
I believe it would be nice to add a button that would open the plugins directory directly from the plugins menu in the settings.

Also, the ability to turn off\on installed plugins without removing the plugin from the folder would be appreciated.

Every time I'm adding\removing plugins (in linux particularly), I'm having a tough time finding the folder.

**Comment by Plip-Plop** [comment]
A better plugin screen is on the [Development Roadmap](https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap). Your ideas are pretty standard ideas for plugin screens in games, so they would probably be implemented were anyone to try.

**Comment by tehhowch** [comment]
Closing as duplicate:
#3079 and #1255
