### ISSUE TITLE
hard crash when Rep is 0 and used as condition

### ISSUE THREAD

**Issue by Zavindur** [endless-sky/endless-sky#5780]
**Describe the bug**
When a mission tries to use "reputation: Government" but said reputation is initialized at 0; the game hard crashes (no error, nothing in error log).

**To Reproduce**
this mission will cause the crash if you disable any ship and try to land on planet or travel to another system:
government phCombatPaid
_swizzle 0
_"player reputation" 0
mission "phCombatN"
_invisible
_landing
_repeat
_source
__attributes "spaceport"
_to offer
__"combat rating" - "reputation: phCombatPaid" >= 1
_on offer
__payment 5000
__"reputation: phCombatPaid" = "reputation: phCombatPaid" + 1
__fail
_destination Earth

**Expected behavior**
It seems when the player rep is 1 it then just has the "reputation: Government" with no '1' after words; it's assumed that maybe there is some limitation to government rep variables? I would expect it to be "reputation: Government" 0  but that is not the case

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: nightly
 - Version: latest build as of 3-11-2021
**Link to save file**

**Additional context**
I think I vaguely remember somewhere it saying you can't have 0 rep, but I just read the wiki and didn't see that mentioned, so I'm not sure now.

For a workaround I'll just shift the rep up some so it's not on 0.

**Comment by Zavindur** [comment]
nvm, i have an item that maps 2400 systems, that seems to be involved also

**Comment by tehhowch** [comment]
Underlying issue was #5790 and was resolved in 5dce934e30d70a444e460694bca624c5839f3c96
