### ISSUE TITLE
feature: Allow projectiles to split into subships just like splitting into submunitions

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5782]
**Is your feature request related to a problem? Please describe.**
When looking at the weapons code where projectiles split into sub-munitions, then I wondered why we don't allow projectiles to also split into (drone) ships.
This should allow for the creation of "smarter projectile" weapons and for the creation of "(drone) ship generating weapons".

**Related Issue Links**
#1249 seems somewhat related, except that fighters and drones generated here might not be able to re-dock at their carrier (unless we also add some code for docking and "de-generating", but that would be a different feature request).
Ships that automatically lose hull over time (automatically dying ships) could also be relevant here.

**Describe the solution you'd like**
Add a new keyword `subship <ship name/id>` similar to the `submunition <outfit id>` keyword that is currently available for projectiles.

**Describe alternatives you've considered**
Bays that automatically generate ships would also work as "drone ship generating weapons" and might be more suitable.

**Additional context**
N/A

**Comment by Zitchas** [comment]
Interesting idea. Could be be useful for creating disposable "deploy-able turrets" style drones, too.

**Comment by tehhowch** [comment]
I'm not particularly interested in making projectiles that spawn ships.

**Comment by petervdmeer** [comment]
Closing; there are other improvements more likely and more valuable at this moment.
