### ISSUE TITLE
Buying additional items that are already in storage doesn't confirm credit availability

### ISSUE THREAD

**Issue by Waladil** [endless-sky/endless-sky#5787]
In the most current continuous build (March 13), if you have objects in outfitter storage and have no ship selected, the "buy" button switches to "cargo." When it does so, the game doesn't actually check to see if you have credits available to buy more of that outfit and will let you buy them, putting your credits into the negative. 

Reproduction steps:
1. Have a low credit balance and available cargo space
2. Land at any outfitter
3. Purchase 1 outfit, put it in storage
4. Deselect any ships
5. Purchase additional outfits of the same kind
6. Check credit balance

**Comment by Waladil** [comment]
Note: This requires use of hotkeys specfically. It will not happen if you click buttons with the mouse.

Step by step repro with images:
https://imgur.com/a/tdKNT16

**Comment by petervdmeer** [comment]
Thanks for the good bug-report! Looks like an issue which could have been introduced by me.
