### ISSUE TITLE
empty fleet causes hard crash

### ISSUE THREAD

**Issue by Zavindur** [endless-sky/endless-sky#5790]
**Describe the bug**
when you have a fleet defined but you don't have any ships in the fleet; this can cause the game to hard crash on Fleet::Strength when it attempts to "return sum / total"

**To Reproduce**
I've had this happen when landing on a planet or I think entering a system that had the fleet assigned as well.

**Expected behavior**
The game should spit out in the error log when there is a fleet defined that doesn't have any ships attached to it; I don't think the game engine needs to work around this- but at least having it show up in the error logs as an issue would be enough

**Screenshots**
This is a fleet without a ship defined:
fleet "X133Y252G1"
_government "G1"
_names "civilian"

this is one with a ship
fleet "X133Y252G1"
_government "G1"
_names "civilian"
_variant 1
__"sparrow" 1

**System (please complete the following information):**
did latest nightly build

**Additional context**
thanks to tehhowch who was kind enough to get the stacktrace and interpretation of where it was crashing

**Comment by tehhowch** [comment]
fixed in 5dce934e30d70a444e460694bca624c5839f3c96
