### ISSUE TITLE
Add a separate targeting system specifically for asteroids!

### ISSUE THREAD

**Issue by ZombieChibiXD** [endless-sky/endless-sky#5802]
It's always annoying when I just want to mine and leave things to the Planet guards/Escorts' to take care of the pirates while I mine, but I keep targeting enemies instead of asteroids!

**Describe the solution you'd like**
- A new key! Press [G] to <Target/Cycle to nearest asteroid>
- A dedicated asteroid targeting system! I don't want to mine Silicones when I can be mining Uranium or Yottrite instead!

**Describe alternatives you've considered**
- Clicking on asteroids really, but then what's the use for me to buy a lot of [Asteroid Scanners] to scan Asteroids out of my screen?
-Shooting Asteroids without targeting system...

**Comment by jerith** [comment]
I find it somewhat annoying when I want to target pirates, but there aren't any around and I get an asteroid instead. 😛

A more flexible targeting system that allows cycling through entities of a particular type (asteroids, enemies, allies, escorts, etc.) would be nice, but giving each their own hotkey would probably be troublesome. (For example, [G] is already "order escorts to gather around flagship".)

Perhaps one hotkey for cycling through a target filter and another to cycle through the filtered entities? Then I could hit the filter cycle button until I reached "hostiles" (or @ZombieChibiXD could cycle through to "delicious rocky lumps of loot!") and we could both hit [N] or whatever to select the perfect victim.

**Comment by samrocketman** [comment]
You target asteroids only if you have an asteroid scanning outfit.

After play testers playing my mining PR #6669 it was requested by multiple people I use a separate shortcut so I went with `V`

**Comment by samrocketman** [comment]
#6669 implements this feature

**Comment by samrocketman** [comment]
I added a preference to the mining PR which enables the targeting to prefer highest value asteroids or proximity.

**Comment by warp-core** [comment]
What Sam said.
