### ISSUE TITLE
Escort Fleet Asteroid shards or Dumped Cargo gathering/collecting order!

### ISSUE THREAD

**Issue by ZombieChibiXD** [endless-sky/endless-sky#5803]
Sometimes I use slow and heavily armed ship and mine asteroids, but my agility isn't that great to get the shards in time.
Why not ask my fleets to gather them while I focus more on mining instead?

**Related Issue Links**
#3713 (Almost related, but not really. We're not asking the fleet to "mine" but instead gather what you mine)

**Describe the solution you'd like**
- An order to escort ships! Press [G] to \<Order Escort to gather space debris> or something
- An order for escort ships to follow/gather around an asteroid!
- A new asteroid specific weapon / equipment!

**Describe alternatives you've considered**
- Increase cargo / asteroid shards appearance duration so I can get them in time
- SLOW DOWN THOSE ASTEROIDS!
- OR ADD GRAVITY EFFECTS TO SHIP, because the asteroids seem to rotate around the Sun or something, which is not linear, and I can't turn well...

**Comment by beccabunny** [comment]
Floatsam duration time was greatly increased recently, make sure you use the latest continuous

**Comment by Hector-of-the-Void** [comment]
> Floatsam duration time was greatly increased recently, make sure you use the latest continuous
It also is supposed to slow down, but I havn't tried it out yet.

> A new asteroid specific weapon / equipment!

The outfit "Korath Slicer" is perfect for this, however it is a rather late game weapon. Perhaps a lesser version can be implimented in human space.

**Comment by samrocketman** [comment]
https://github.com/endless-sky/endless-sky/pull/6669 implements this feature

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/879f3fd72db961a417ab21a5889a4e58697e0318 adds support for telling your fleet to mine the asteroid you have selected and tellling them to collect flotsam, and they will automatically collect the flotsam from an asteroid they just mined.
