### ISSUE TITLE
Documentation points to a defunct Google Group

### ISSUE THREAD

**Issue by jp-bennett** [endless-sky/endless-sky#5810]
Hey all, Sorry for semi-abusing a bug report like this. Though technically the Google Group forum is referenced in the Readme and Wiki. It seems to be down. Hence, it really is a bug.

I was hoping to ask if one or two of the devs wanted to come guest on an episode of the FLOSS Weekly podcast, and chat about the history of the game, and open source gaming in general. Hit me up on twitter @jp_bennett or Mastodon @jp_bennett@twit.social.

**Comment by Zitchas** [comment]
Yes, the google groups is unmaintained and unmonitored by most of the active Devs & content creators. 

I would invite you to stop by the discord channel at: https://discord.gg/ZeuASSx
It is quite active, and virtually everyone who is currently working on the game is on there at least now and then. (The discord is run by Amazinite, one of the three active Devs.)

**Comment by Terin** [comment]
This will be resolved by #5704, once the current release(s) are finalized and we continue development.

**Comment by tehhowch** [comment]
The Google Group is in need of some administrative actions that can currently only be done by @endless-sky, to respond to platform-level changes in Google Groups, such as visibility settings and the deprecation of subforums. (In lieu of subforums, Groups provides the option to have Gmail-style topic labels, but an admin must elect to enable them.)

**Comment by Zitchas** [comment]
With #5704 having been merged a while ago, I think this can be closed. The google groups are no longer referred to as the main place to contact people or ask questions, and likewise the reference to it in other places of the wiki have been likewise replaced.

**Comment by Hecter94** [comment]
The wiki link referenced in the OP still points to the defunct google group:
https://github.com/endless-sky/endless-sky/wiki#playing-endless-sky
https://groups.google.com/group/endless-sky

So I don't think this should be closed.

**Comment by MCOfficer** [comment]
Thanks for catching that one.
