### ISSUE TITLE
"Stranded Ship" mission cannot be completed

### ISSUE THREAD

**Issue by pepoluan** [endless-sky/endless-sky#5815]
## Describe the bug
So I visited Hestia in Talita, met with good ol' James again, we fetch his ship "Marius" on Danoa, and went to Alnitak...

But everytime I landed on Farpoint@Alnitak, game complained that I left James behind!

## To Reproduce
1. Start the "Stranded Ship" mission
2. Go to Danoa and board the "Marius"
3. Go to Alnitak, wait for "Marius" to arrive, land on Farpoint

## Expected behavior
Mission should've continued (or ended?) at that point.

## Screenshots

**Prior to landing, as you can see I have "Marius" with me:**
![image](https://user-images.githubusercontent.com/642259/112759580-d9f38a80-901d-11eb-8d14-03d4d8f71e5e.png)

**After landing, game complains that I "left Marius behind":**
![image](https://user-images.githubusercontent.com/642259/112759601-e972d380-901d-11eb-8430-138855ad9b0c.png)

## System (please complete the following information):
 - OS: Windows 10 Pro version 20H2 build 19042.804 with Feature Experience Pack 120.2212.551.0
 - Game Source: Continuous Build
 - Version: ae40b10

## Link to save file
[Pepo Langit.txt](https://github.com/endless-sky/endless-sky/files/6217646/Pepo.Langit.txt)

**Comment by Amazinite** [comment]
This is plugin content from Ursa Polaris. Issues with plugins should be brought up with the plugin creator, not posted on this repository for the vanilla game.
