### ISSUE TITLE
Ability to Hire Escorts

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5816]
**Is your feature request related to a problem? Please describe.**
I noticed that you are offered a ton of jobs for escorting freighters. However, you yourself cannot hire a temporary escort.

**Related Issue Links**
I didn't find anything really similar to this.

**Describe the solution you'd like**
I would like it so that you can hire an escort which will follow you for a certain amount of time. You can select how many days you want your escort to follow you, and also select what type of ship you want it to be (Ranging from Interceptor to Heavy Warship.) The more powerful the ship and the longer the amount of time you want it to follow you affects the price.

**Describe alternatives you've considered**
An alternative to selecting the amount of days would be to have the escort follow you until a certain job is completed. This could also just be another option instead of a complete alternative.

**Additional context**
I think it would be really nice to add this as a new feature for the spaceport button. More features for the spaceport button beyond just randomly being offered missions and having people talk would be nice.

**Comment by beccabunny** [comment]
https://github.com/endless-sky/endless-sky/pull/1208
https://github.com/endless-sky/endless-sky/issues/1184

**Comment by McloughlinGuy** [comment]
This feature exists in side the games files, so I will create a new request alter asking to impliment it.
