### ISSUE TITLE
Custom planet doesn't offer jobs

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#582]
I created a plugin containing the system 'Ryon' with an inhabited planet 'Fortrun'. Everything works, but it doesn't have any avaliable missions. I went through the files, and it should be able to give missions. Other than that, I don't see an issue with it. Does anyone have any suggestions on how to fix it? The file is attached below:
[Endless Sky - Ryon.zip](https://github.com/endless-sky/endless-sky/files/76424/Endless.Sky.-.Ryon.zip)

**Comment by omagasohe** [comment]
Not to comment on your issue, but this place is more for issues with the game as distributed and not with custom add ons, this would be better suited to the forums then here.

**Comment by lehgogh** [comment]
I didn't know that there were forums. I'll go ask there, and someone can lock/delete/solve this issue.

**Comment by endless-sky** [comment]
If you modify a system's "links" section, any existing links are removed. So, you essentially made all the neighboring systems only connect to this one. That results in one-way links that go into those systems, but not out of them. Instead, you should do this:

```bash
system Canopus
	link Phurad
	link Mirzam
	link Alheka
	link Phact
	link Ryon

system "Epsilon Leonis"
	link Gomeisa
	link Aspidiske
	link Adhara
	link Ryon

system Mirzam
	link Canopus
	link Betelgeuse
	link Mebsuta
	link Ryon

system Phurad
	link Tejat
	link Canopus
	link Wazn
	link Ryon
```

**Comment by egilburg** [comment]
>If you modify a system's "links" section, any existing links are removed.

This would make mods rather fragile to any later patches to the game. Perhaps `link` and similar commands should be additive, with matching removal keywords e.g. `unlink` to reverse? It would still cause load-order challenges in case of multiple mods, but at least it would be less fragile to main game (which should be loaded before any mods), and later a mod manager could let players manually set load order of mods if needed.

**Comment by lehgogh** [comment]
It works now. Thanks!
(Also, that does seem pretty fragile. Then again, from what I've heard, Endless Sky isn't going to receive too many more systems in the future.)

**Comment by brick96** [comment]
@egilburg just like when adding items to outfitters or shipyards. I do find it odd though to have to have links going both ways for missions. do one way links prevent jumping in reverse? Say link A to B, could I jump from B to A?

**Comment by lehgogh** [comment]
I would guess so. I didn't try jumping back when it was broken; I just noticed that there weren't jobs and quit the game.
