### ISSUE TITLE
Parking Bug

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5821]
**Describe the bug**
It's a bug involving the park feature which can cause you to be stuck on a planet.

**To Reproduce**
1. Select "Park All"
2. Sell your main ship

**Expected behavior**
You will no longer be able to take off. This can be annoying during the remnant gascraft missions, because after you sell your gascraft if you have a ship parked you will be stuck and have to redo the mission.

**Screenshots**
None.

**System (please complete the following information):**
Windows 10
Steam
I'm stuck in some sort of weird limbo between the continuous build and the current release. Basically, I have tho normal build but the remnant have spaceport quotes and the Emerald Sword exists in the games files. 

**Link to save file**
You really don't need my save file for this.

**Additional context**
No needed context.

**Comment by Vedvod** [comment]
Just so I (or someone with actual power and skills) can understand, can you not just unpark another ship? I get if it's parking all your ships on another planet and then selling, but does this also occur for same planet parking?

**Comment by McloughlinGuy** [comment]
It occurs for both. In fact, same planet parking is how I discovered this bug, while doing the remnant gascraft missions.

**Comment by McloughlinGuy** [comment]
Further experimentation has determined that if you buy a ship after selling your main ship, you will be able to take off again. However, depending on the planet you are on you may not have enough money/the required license to buy another ship and escape from the planet.

**Comment by McloughlinGuy** [comment]
Here is a link to an unlisted youtube video on my channel which demonstrates the bug. (I couldn't get the file to load on GitHub.)
https://www.youtube.com/watch?v=LBy1zumLog4

**Comment by Amazinite** [comment]
As @Vedvod asked, can't you just unpark your ship? From that video I don't see any actual issues. You don't have any unparked ships on that planet, therefore you can't depart. The game also doesn't automatically unpark ships for you.

**Comment by McloughlinGuy** [comment]
No, you cannot unpack your ship.

**Comment by Amazinite** [comment]
I just tested it and I am able to unpark my one parked ship. The "unpark all" button isn't present because you only have one ship. You have to go to the ship's info page (click on it) and use the unpark button from there.

**Comment by tehhowch** [comment]
At best, I could see us adding confirmation for selling your last ship when you have no other parked ships in system and can't buy any ships in the shipyard. Other than that, I don't see anything here that might need addressing.

**Comment by McloughlinGuy** [comment]
I would do that, or make it so that you can't.

**Comment by McloughlinGuy** [comment]
As @Amazinite said you can still unpark it by clicking on it, which I didn't know. You should simply make it so the unpark all button appears regardless of how many ships you have parked. That would adress this issue completely so that it is no longer a problem.
