### ISSUE TITLE
A projectile carries no heat of the ship with it.

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#5822]
**Describe the bug**
The temperature of the ship increases when you shoot a projectile, because the projectile carries no heat from the ship with it, unlike the cargo jettisoned.

**To Reproduce**
1. Install the plugin "test-projectile-heat" and the save file "AAA AAA.txt."
2. Load "AAA AAA" and enter ship.
3. Depart. (Your ship has sufficient active coolings.)
4. Select secondary weapon (Press "W").
5. Fire secondary weapon (Press "Q").
6. Your ship is overheated.
7. Your ship returns the operating condition.

**Expected behavior**
The temperature of the ship would not increase since this secondary weapon has no firing heat.

**System (please complete the following information):**
 - OS: Debian GNU/Linux Testing
 - Game Source: Github
 - Version: 576f7a72678ae0fafe8a24c9494f34c62f51c847

**Link to save file**
- Plugin for testing [test-projectile-heat-plugin.zip](https://github.com/endless-sky/endless-sky/files/6252324/test-projectile-heat-plugin.zip)
- Savefile [AAA AAA.txt](https://github.com/endless-sky/endless-sky/files/6252325/AAA.AAA.txt)

**Additional context**
A ship that depends on active coolings is sensitive to this behavior.

**Comment by tehhowch** [comment]
Right now every `Projectile` instance is massless, and we don't define a concept of "heat" for anything except ships. So it would be a somewhat-large mechanics change to add this functionality.

That said, any non-massless ammunition, e.g. a nuclear missile, could (and probably should) be made to simulate heat removal when removed from the ship.

**Comment by tehhowch** [comment]
> That said, any non-massless ammunition, e.g. a nuclear missile, could (and probably should) be made to simulate heat removal when removed from the ship.

This particular bug is addressed in ddd70625, by having half the removed mass take heat with it, under the assumption that the other half of the mass was probably used in the act of firing, becoming firing heat and/or other indeterminate side effects.

Even with the change, firing the above exaggerated weapon--where the ammo massively outweighs the ship several times over--still results in a thermally disabled ship, the remaining heat level is significantly less than without the change.
