### ISSUE TITLE
Game Should Alert You if You Don't have a Shield Generator Installed

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5827]
**Is your feature request related to a problem? Please describe.**
In one of my playthroughs of the game, I spent a long time without a shield generator, and I wish I had known I didn't have a shield generator so I could have installed one

**Related Issue Links**
No related issues.

**Describe the solution you'd like**
I want you to make it so when you don't have a shield generator installed, that little yellow question mark that appears when you don't have enough energy to fire an installed weapon will appear.

**Describe alternatives you've considered**
You could have it give you a message before you take off, but i like the other option better.

**Additional context**
The yellow question mark is the best question mark, for it is the king of all question marks.

**Comment by beccabunny** [comment]
There is nothing wrong with not using a shield generator though

**Comment by movingpictures** [comment]
Aye In fact, some of the "how to capture pirates in Endless Sky" guides suggest taking out the shields to better cram bunks into whatever ship you're using.

**Comment by McloughlinGuy** [comment]
I agree, in fact I was going to say that in the additional context but chose not to.
