### ISSUE TITLE
Attach system hazard to system object

### ISSUE THREAD

**Issue by ravenshining** [endless-sky/endless-sky#5829]
**Is your feature request related to a problem? Please describe.**

I was looking at placing a neutron star in a system for #5828 , some distance (~2000+) away from the normal star.  Unfortunately, if I want the neutron star to attract ships and deal damage, it must be in the centre - but, if I put it in the centre and have the bright star orbiting the neutron star with planets like moons about the bright star, then all the planets will face the neutron star and not the bright star.

If I could attach or centre a hazard on the neutron star instead of the system itself, then I could place the neutron star wherever I like without messing with planet facings or habitability zones.

**Related Issue Links**

I *thought* I had raised this issue when #4931 was being discussed, but what I did suggest there (attaching hazards to star definitions), while similar, is not exactly what I mean here.

**Describe the solution you'd like**

Attach hazards to objects like this:
```
       object
               hazard "Black Hole Gravity" 1
               hazard "Black Hole Event Horizon" 1
               hazard "Black Hole Accretion Disk" 1
               sprite star/neutron
```

**Describe alternatives you've considered**

- Having the lighting look all wrong by having the system orbit the neutron star instead of the neutron star orbiting the system
- Not having systems with both a star and a hazard widely separated like I want.

**Comment by Zitchas** [comment]
I, too, thought that this was already the case. If it isn't, then I definitely hope that it can be adjusted to enable it.

**Comment by ravenshining** [comment]
Funnily enough, the map editor moves hazards from systems into objects when it saves.  But, it does that for attributes, too, and messes all kinds of stuff up, so that's probably not saying much.

**Comment by tehhowch** [comment]
Should be possible now
