### ISSUE TITLE
I think I found why it wasn't building

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#584]
![2016-01-03 01_20_16-](https://cloud.githubusercontent.com/assets/16502223/12076720/45ef6654-b1b8-11e5-910a-8f842f5681c1.png)
g++.exe was in C:\Program Files\mingw-w64\x86_64-4.8.5-posix-seh-rt_v4-rev0\mingw64\bin
(using the installer provided in the link, using 4.8.5) Maybe you should check the wiki if it's still correct

**Comment by endless-sky** [comment]
So, you're saying you had not set the toolchain executables to the right programs? Or are you saying that there's some sort of problem with the build instructions?

**Comment by ph2000bis** [comment]
I think since When I fed the data from the screenshot here https://github.com/endless-sky/endless-sky/wiki/BuildInstructions into codeblock it failed, and i found it in a different file, the Build instructions are out of date/misleading, or I'm so crap I can't understand the instructions (a different issue)

**Comment by ph2000bis** [comment]
My bad, i'm just crap
