### ISSUE TITLE
Feature Request - RTS elements to control multiple ships.

### ISSUE THREAD

**Issue by taffylim69** [endless-sky/endless-sky#5843]
Sometimes, I tried to think tactically. Command group A to follow me to battle, while group B waiting in ambush. Unfortunately, this is not possible in Endless Sky.

Anyone who've played rts games like red alert usually do Ctrl + # to assign a group, then # to highlight the selected group.

If we could make this possible. Endless Sky would become more immersive. What do you think?

**Comment by McloughlinGuy** [comment]
I don’t know how to use C++ so I have no idea whether or not this is hard to do.

**Comment by tehhowch** [comment]
Duplicate of #3210
