### ISSUE TITLE
Feature Request - Buy your own planet or build a space station

### ISSUE THREAD

**Issue by taffylim69** [endless-sky/endless-sky#5844]
What do you guys think of buying your very own planet. 
You could terraform it, raise population, build economy and tax the population for the glory of your empire?

Of course, new powers comes with new responsibilities. You'll not only have to worry about pirates, but also neighboring planets and ambitious warlords who wants a piece of your land. Diplomacy with leaders becomes very important if you want to survive.

That's why space stations are built, so that you could play tower defense and bring down those who dares to steal your precious planet. Outfit your space station with weapons, build a shipyard and earn money selling ships. Post on the job board to put a price on the pirates attacking you, or even hire pirates to shrink the defense force of neighboring planets.

Being a lone planet also means you have little to no influence against ambitious warlords that surrounds you. Protect your planet by joining a faction - Free Worlds, Republic, Syndicate, or even creating your own. 

PS: warlords and evil robots who wants to assimilate everything increases the stakes and makes the game more exciting.

**Comment by Vedvod** [comment]
This is an interesting idea, I must say, but it might be beyond the scope of Endless Sky, which is a game where you shoot ships and trade goods. I feel that Endless Sky works best as an exploration and experimentation game, and that a colony builder/politics simulator may not fit in. As said for some long ago economy suggestion, "No game can be everything (Unless it's Star Citizen)" or something. Then again, I'm not very good at telling what fits and what doesn't. It might work maybe.

**Comment by taffylim69** [comment]
No biggie. Just sharing, for people interested in working this out - It seems possible because there are already dialogs and factions built into the system.

As for scope, I think it depends if there are enough people interested in making this happen. If people enjoy coding to make this happen, it might work.

**Comment by tehhowch** [comment]
The "Feature Request" issue template is there for a reason; please search for related issues prior to posting. If your idea/request matches an existing one, it is much better to chime in there than duplicate it.

Duplicate issues include: #5216

(There may be more as well.)

**Comment by roadrunner56** [comment]
This seems a bit much for a 'space trading and combat sim'. These kind of mechanics would be more suited to a 4X game like Stellaris.
