### ISSUE TITLE
Feature Request - Don't die if your ship blows up

### ISSUE THREAD

**Issue by taffylim69** [endless-sky/endless-sky#5845]
Dying has little to no consequence, you just load from the last save. It also breaks immersion.
There are multiple ways to address this and increase replay value. 

Here are some possible alternatives to dying:
1. Captured by pirates, get your goods stolen, time skip and start with a new ship. - gives you more reason to deposit your savings in the bank (new feature).
2. One of your fleet ship rescues you. 
3. Your fleet deserts you and you'll have to wait for rescue.
4. Rescued by friendly ships, time skip, land on a nearby planet, hire starship to escort you to a planet that sells ship, buy a new ship.
5. mix them up and also have permadeath, make it random.

**Comment by McloughlinGuy** [comment]
Even if the devs were to consider this, something like it is low on their priorities list. I dying is a penalty in of itself.

**Comment by MCOfficer** [comment]
refs #362

**Comment by tehhowch** [comment]
Please use the issue template.

As MCO linked, there is an outstanding feature request for this.
