### ISSUE TITLE
Ability to hire escorts

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5851]
**Is your feature request related to a problem? Please describe.**
As stated by @jafdy in #1184 the ability to hire escorts is present within the games engine. However there is a somewhat dramatic bug contained within pull request #1208 that @jafdy mentioned.

**Related Issue Links**
#1184 #1208

**Describe the solution you'd like**
If the bug that occurs has been resolved it should be implemented.

**Describe alternatives you've considered**
If the bug has not been resolved, you should get rid of it.

**Additional context**
There's not really much else to say. I can't draft something for this because it probably requires code changes.

**Comment by Terin** [comment]
The bug mentioned is resolved by #5157. Once that's implemented, it'd be possible to more robustly have mercenary jobs.

**Comment by McloughlinGuy** [comment]
Then we should probably implement this feature.

**Comment by McloughlinGuy** [comment]
Okay, so once that’s implemented this could work. So the only thing I can say right now is try to remember this issue once that gets implemented.

**Comment by PeacefulPotato** [comment]
It's implemented.

**Comment by Zireael07** [comment]
@PeacefulPotato: https://github.com/endless-sky/endless-sky/pull/6536 is not merged yet?
