### ISSUE TITLE
Starting scenarios in Alien space?

### ISSUE THREAD

**Issue by TrumanHanson** [endless-sky/endless-sky#5854]
With the new choosing of your starting scenario feature, I was wondering how it works, and if it'd be possible to put in ones where you'd be able to start in certain alien spaces where humans reside, such as the Remnant or Hai space.

**Comment by Zitchas** [comment]
Yes. They allow starts anywhere.

Current plans are to have a start in each major region of human space as normally available starts.

Later on, once we can store pilot-independent data (for example, recording that the player has met the Remnant, the Hai, or others), we plan on having starts where the player begins in some of those alien territories. Hai, Remnant, and Coalition are probably the big three.

**Comment by roadrunner56** [comment]
I'd like to note that this feature is probably a long way off. It'll probably only be implemented after the three main storylines (Free Worlds, Republic, and Syndicate) have been finished, and a few alien ones as well.

**Comment by McloughlinGuy** [comment]
How would this effect with the current story lines in the game?

**Comment by roadrunner56** [comment]
It probably wouldn't, but the main priority right now is getting the two other main storylines done.

**Comment by Zitchas** [comment]
> 
> 
> How would this effect the current story lines in the game?

It wouldn't. At least, not initially. The FW story really doesn't care where the player comes from. There are only a handful of mentions throughout the game of the pilot's origins that would need to be branched. The Remnant, it would affect a bit more, but I already have plans for that.

**Comment by Vedvod** [comment]
What about the TWBT story thing? If the player started in Hai space, that would affect it somewhat, would it not? And if the player started in Hai space, would they start with Hai technology?

**Comment by Zitchas** [comment]
They'd start with a set amount, and how they spend it is up to them. But yeah, I'd assume it would be enough to start with the smallest mission-capable ship.

That's really one of the main reasons, as far as I'm concerned, for the alternate starts. Give players the opportunity to meaningfully make use of things like the Kimek Thorn, Earth Shaper, or Aphid. Ships that - alternate starts aside - really serve no functional purpose for the player other than to be background decor.

**Comment by beccabunny** [comment]
> If you were a Hai, wouldn’t that change a lot of ways people react to you?

You will never be a hai. You could be a human in hai space

**Comment by Amazinite** [comment]
> I was wondering how it works, and if it'd be possible to put in ones where you'd be able to start in certain alien spaces where humans reside, such as the Remnant or Hai space.

Read up on the [creating starts](https://github.com/endless-sky/endless-sky/wiki/Creating-Starts) page on the wiki to find out how to create your own start.

**Comment by Plip-Plop** [comment]
The main reason you cannot be a Hai is that it is impossible to create a start that changes all the text in the game.
