### ISSUE TITLE
0.9.13 beta - Portrait of Spaceport quote of random person is not shown 

### ISSUE THREAD

**Issue by binaryspica** [endless-sky/endless-sky#5855]
**Describe the bug**
As title says. There was random portraits for the persons but it was got removed. Is it intended?

**To Reproduce**
1. Go to any planet
2. Click on Spaceport

**Screenshots**
![a1](https://user-images.githubusercontent.com/47907439/115140221-2c4e2700-a071-11eb-8786-e463da888064.png)

**System (please complete the following information):**
Windows 10
Steam
0.9.13 beta

**Comment by MCOfficer** [comment]
This is intended, see #4325. Note that the functionality still exists for plugins, it's just not part of the game's data files anymore.

**Comment by McloughlinGuy** [comment]
A lot more people are gonna get confused and think this is a bug.

**Comment by Amazinite** [comment]
A lot more people should read the changelog, perhaps.

**Comment by binaryspica** [comment]
I have no idea why it was intended....

> A lot more people should read the changelog, perhaps.

Was it on the log? I had read this but I didn't find one. Although it is sure that I didn't catch it.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/blob/c9a79a3080fc7a52d1123385f5fdafc451fc73f3/changelog#L159

**Comment by binaryspica** [comment]
> https://github.com/endless-sky/endless-sky/blob/c9a79a3080fc7a52d1123385f5fdafc451fc73f3/changelog#L159

I didn't think that you are lying about this. I'd think that it is very hard to catch, and it seems I was right.

**Comment by Amazinite** [comment]
Didn’t think you thought I was lying, just pointing to exactly where it is. And to be fair, this is a big changelog, so I can understand missing something when skimming through.

**Comment by binaryspica** [comment]
Yeah after all checking the section is quite helpful.

**Comment by ravenshining** [comment]
Can't blame someone for thinking it's a bug - I know I spent a week trying to track down what had gone "wrong" with my repos when the commit that removed them dropped.

I think it would look not so bugged out if we shrunk the news box to accommodate for the lack of an image displayed there.

**Comment by tehhowch** [comment]
> Can't blame someone for thinking it's a bug - I know I spent a week trying to track down what had gone "wrong" with my repos when the commit that removed them dropped.
> 
> I think it would look not so bugged out if we shrunk the news box to accommodate for the lack of an image displayed there.

We do wrap the message differently based on portrait presence. If we didn't, then I would agree with your assessment that it looks "bugged out."

**Comment by ravenshining** [comment]
Maybe it's all the empty space. There is a lot of it now, since most of those quotes used to have portraits next to them.  Maybe if the box was also two lines shorter?

**Comment by tehhowch** [comment]
The game supports news with images and news without. I think it would be bad to constantly resize the news box should a user encounter both kinds in the same session.

**Comment by ravenshining** [comment]
Actually, I was thinking of suggesting resizing the box to fit the content - I think that would be the best option - but didn't because I thought that might be more complicated than anyone would consider worth doing.  I think it would look worse to cover up the planet image with so much empty grey box, then to have the box be different sizes sometimes.

That said, I think portraits when reintroduced will look better *beside* the box rather than inside it, as I was making examples for on Discord, so in that situation the box would still benefit from being smaller regardless.

**Comment by binaryspica** [comment]
Anyway is there any way to bring back the portrait? I heard that there is something, but I have really no idea where it is for nothing says for the so called plugins.

**Comment by tehhowch** [comment]
> Actually, I was thinking of suggesting resizing the box to fit the content - I think that would be the best option - but didn't because I thought that might be more complicated than anyone would consider worth doing.  I think it would look worse to cover up the planet image with so much empty grey box, then to have the box be different sizes sometimes.
> 
> That said, I think portraits when reintroduced will look better *beside* the box rather than inside it, as I was making examples for on Discord, so in that situation the box would still benefit from being smaller regardless.

You can accomplish this without code changes. You'll need a new sprite the size of the desired backdrop, and you can modify the "news" interface file to use the same dimensions with & without a portrait. You'd then move the portrait positioning to where you want it displayed.

You would need code changes if you wanted to conditionally render a new "portrait backdrop" when the news item has an image.


> Anyway is there any way to bring back the portrait? I heard that there is something,

You can restore portraits by adding the field to the news definitions: https://github.com/endless-sky/endless-sky/wiki/CreatingNews#definition-syntax

You can do this via a plugin. AFAIK, no one has created one that re-adds the portrait definitions that were removed.

**Comment by LordInsane** [comment]
> > Actually, I was thinking of suggesting resizing the box to fit the content - I think that would be the best option - but didn't because I thought that might be more complicated than anyone would consider worth doing.  I think it would look worse to cover up the planet image with so much empty grey box, then to have the box be different sizes sometimes.
> > That said, I think portraits when reintroduced will look better _beside_ the box rather than inside it, as I was making examples for on Discord, so in that situation the box would still benefit from being smaller regardless.
> 
> You can accomplish this without code changes. You'll need a new sprite the size of the desired backdrop, and you can modify the "news" interface file to use the same dimensions with & without a portrait. You'd then move the portrait positioning to where you want it displayed.
> 
> You would need code changes if you wanted to conditionally render a new "portrait backdrop" when the news item has an image.
> 
> > Anyway is there any way to bring back the portrait? I heard that there is something,
> 
> You can restore portraits by adding the field to the news definitions: https://github.com/endless-sky/endless-sky/wiki/CreatingNews#definition-syntax
> 
> You can do this via a plugin. AFAIK, no one has created one that re-adds the portrait definitions that were removed.

https://github.com/Anarchist2/ES-news-portraits
It can be downloaded via ESLauncher2, too.

**Comment by binaryspica** [comment]
Anyway, it is very disappointed to simply remove it. Why it have to?

**Comment by LordInsane** [comment]
Because generally more people seemed to dislike them than like them, at least in the real-world photo paradigm that ES sticks to, and it was easier to set up things so they're off by default but can be reactivated with a plugin than by having them on by default and deactivated with a plugin.

**Comment by MCOfficer** [comment]
The issue referenced above holds the answer.

**Comment by binaryspica** [comment]
Still it does not answers why it needs to be removed, rather than just have an option to hide it.

Also, after playing beta it makes me to not hit the spaceport and read the quotes. Is it really makes the difference? Yes it does. I didn't really need for the portrait, but its removal makes me to avoid it.

You know, the game is all about text, at least on the port. But the quote with a face makes me to acknowledge it and encourages to focus on it. No more. For now it is nothing but just an added texts above the spaceport description and it is hard to acknowledge that it is the separated one. The theme is already dark so even consider it's on the center of the screen it never catch my attention. Read the quote was fun, although it is usually something we passed by and only read it briefly in the most times. And I feel that I lost the entire text, not just the portrait.

Let be honest. I don't have any 'love' for the portraits. Also the full mask pirate is somewhat weird(although I see him comical a bit). But, simply remove something that was existed through the game is not a good move. Especially for it causes bad side effects and I am suffering this right now. It is really annoying. It makes that the game is no longer the game what I have played, at least on the part.

**Comment by ravenshining** [comment]
I'm in full agreement with you, but "just have an option for it" is easier said than done.

Personally I think this issue could be a great application of #5556 , at least if we can have access to gamerules via the options screen rather than having to mess about with plugins.  Pretty much everyone seems to be loathe to touch the options screen, however, as from what I hear the code's a mess.

I *barely* know what I'm doing at all with C++, but, if it gets portraits back in the game, I'll make it my top priority to smash my brain against the options screen and gamerule.

**Comment by binaryspica** [comment]
> I'm in full agreement with you, but "just have an option for it" is easier said than done.
> 
> Personally I think this issue could be a great application of #5556 , at least if we can have access to gamerules via the options screen rather than having to mess about with plugins. Pretty much everyone seems to be loathe to touch the options screen, however, as from what I hear the code's a mess.
> 
> I _barely_ know what I'm doing at all with C++, but, if it gets portraits back in the game without having to use plugins, I'll make it my top priority to smash my brain against the options screen and gamerules.

Agreed. It is easier said than done, indeed. And the devs are volunteers rather than employers, and even if they are employed it is sure that I am not the boss.

Also I tested some modification to the news texts and it seems works again. Although.... Isn't the portrait shown on the left, rather than right? It seems that I need to touch the interface as well.

**Comment by binaryspica** [comment]
https://drive.google.com/file/d/1Xsp77oumVtkxN7l9E0LWiWjRL92YCxjS/view?usp=sharing

Fellow captains, I just make a fix for this right now. You may download it, and overwrite it on the data and image(if you didn't have any old portrait) folders. 

Although I have no idea how to make a new option, but for now it will allows you to enjoy old quotes.

**Comment by binaryspica** [comment]
https://drive.google.com/file/d/1V6-nV6XcUzpABduklCm3F_CDJkHzS0vZ/view?usp=sharing

Added merchant and farmer quotes on pirate worlds.
