### ISSUE TITLE
Can asteroids be limited to a belt or ring outside the center of the system?

### ISSUE THREAD

**Issue by yafflehk** [endless-sky/endless-sky#5863]
I don't know if this is easy or even worthwhile but the random asteroids everywhere always bugged me. Real solar systems are a bit more organised than that. An asteroid belt would be a nice feature, perhaps co-responding to the pursuit limit. Stations could be in the belt, it would become a place in the system and a dividing line between two parts of a system. Different systems could have different densities and widths of belt, as well as different compositions and so on.
The asteroids would have to orbit if they need to move etc. but all the same asteroid stuff could go on, just in the asteroid belt.

**Comment by tehhowch** [comment]
Please use the issue templates: #3865

Currently, no, only minable asteroids will behave as such. They use entirely different systems.

If a contributor were so inclined, it's possible they could augment the asteroid tiling implementation to support polar rectangles. I feel like this would result in relatively boring asteroid motion (only tangential velocity) without also emulating a 3d "corkscrew" motion about the center of the belt by manipulating sprite zoom.

It's not on any current roadmaps though, and given the comments in #3865, not something I plan to spend time on personally.
