### ISSUE TITLE
Feature Request: New "Roving" Personality

### ISSUE THREAD

**Issue by InfiniteDonuts** [endless-sky/endless-sky#5864]
## Intended Behavior
Roving ships will:
- Wander aimlessly around the system. Previously this could be achieved by using `surveillance`, but this personality is built for the purpose and is unconstrained by celestial bodies, so it can be successfully used even when there are no planets present.
- Randomly hyperspace away, to prevent buildup of roving ships in a system - it should count the number of ships in the system and if that number is above a certain amount, it will leave.
- Stop scooting around and obey their fighting personality (like `heroic`, `forbearing`, etc) when it kicks in, otherwise

## Notes
- Roving should take lowest precedence of non-combat movement goals - ships should only aimlessly wander when they have nothing else to do.

**Comment by Galaucus** [comment]
Is there some way we can define the "randomly hyperspace away" frequency? In order to prevent buildup, escape rate will need to be lower than the spawn rate for the system they're loitering in. Hard-coding it to be lower than the intended implementation (Embershade fleets, currently a 1/4000 spawn rate per frame) would work, but you probably want a more general solution.

**Comment by InfiniteDonuts** [comment]
I can have it count the number of ships in-system and if it goes above a certain number then it leaves (e.g. "This place is too crowded, I'll find somewhere else.")

**Comment by Galaucus** [comment]
On that subject, it would be useful if the same logic could apply to ships without hyperdrives - this way we could have ground based fighter/drone squads patrolling systems, then occasionally returning to base.

**Comment by Zitchas** [comment]
This could also be useful for research vessels.

Note: Could the randomly leaving the system part be something specified somewhere so that we can set it to either hyperjump away or to land (or randomly do either one?)

**Comment by InfiniteDonuts** [comment]
Sure thing

**Comment by tehhowch** [comment]
A direct analog is the mining personality, which will only mine for a specific duration and also only if there are not too many current mining ships.

**Comment by Amazinite** [comment]
This is effectively just the lingering personality from #8125.
