### ISSUE TITLE
new alien sugestion

### ISSUE THREAD

**Issue by cool833** [endless-sky/endless-sky#587]
i had a nice idea that i thought would be a pretty nice story aspect

what if a new alien race was different from humanity in appearance but similar in that they have companies who build tech for them.

as far as i can tell, the current alien races all manufacture their tech through the government and not through separate companies like humans do (e.g syndicate, Lovelace industries, Tarazed corporation)

i thought it would be interesting, i had names for the companies too (Gen-tech corporation, Locomotion industries, Karov industries) i have had a childhood dream about my own alien race and i've always wanted to do something about it but i'm terrible at doing pixel art and am still learning about story writing.

i think it would be interesting to add a more dynamic alien race into the game, or one nearly as dynamic as humanity is

also, will the Drak become an enemy at some point, and if so, will an alien race have tech comparable to theirs and be willing to help, i just really wanted to know because this game is so awesome.

sorry if i'm wasting your time

**Comment by cool833** [comment]
i just have a lot if ideas so i chose one and wrote it down

**Comment by lehgogh** [comment]
I don't know if a new alien race will be accepted, but you can [make it into a plugin](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins). Eventually, a plugin database will be created alongside an in-game plugin selector, so it would be fairly easy to get people to install it if you make it into a plugin.

**Comment by frameworld** [comment]
> i have had a childhood dream about my own alien race and i've always wanted to do something about it but i'm terrible at doing pixel art and am still learning about story writing.

You can use blender or build something in MineCraft and make a screenshot, then make a proper image based on it. ;)
Just find the way that fits you.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
