### ISSUE TITLE
Duplicate news entry

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#5889]
**Describe the bug**
In the news.txt file, there is an entry starting with

> news "reporter"
> 	location
> 		government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent"

on line 638. In the message section, we can see a word defined as 

> "Read my new article! 'Ten Things the Quarg Are Hiding from Us - Number Seven Will Surprise You!'"

and also an other as

> \`Read my new article! 'Ten Things the Quarg Are Hiding from Us - Number Seven Will Surprise You!'\`

(I escaped the \` characters so they wouldn't show as a code block due to markdown.)

As you can see, the actual contents are the same, only the quotation marks are different. From what I know, this would make this message appear twice as often as any other. I don't know if this is intentional or not, but I looked around and didn't see any other news that appeared twice in the same section.

**To Reproduce**
 - Open news.txt (in the human folder)
 - Go to the section starting at line 638
 - See the duplicate entry in message -> word

**Expected behavior**
Every news should appear only once.

**System (please complete the following information):**
 - OS: Windows 10 pro version 20H2 build 19042.928
 - Game Source: Steam
 - Version: 0.9.13

**Comment by Amazinite** [comment]
Good catch. Fixed in 5805812.
