### ISSUE TITLE
Mod Sound Effects not loading

### ISSUE THREAD

**Issue by PositiveAnion** [endless-sky/endless-sky#589]
Any new sound effects in a mods "sounds" folder must be directly put into the games default sounds folder to work. They do not work from the plugins folder.

**Comment by thenerdfreak** [comment]
You must make certain that you're referencing them right (I had this same issue) make sure that the directory for your sound is plugins\(nameofyourpluginfoldergoeshere)\sounds\(sound.wav)

**Comment by endless-sky** [comment]
It works fine for me. Are you sure you have the right plugin structure? That is, as @thenerdfreak said:

* inside one of the [plugins folders](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins) you must create a folder to house your plugin.

* inside *that* folder, you must create folders named `sounds`, `images`, and `data` to house sound files, images, and data files, respectively.

* any sound that is meant to replace one in the base game data must have the exact same name as the sound it is replacing.
