### ISSUE TITLE
"Suggested" waypoints are mandatory

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#59]
In the mission "FW Reconciliation 2B" (and apparently, in the subsequent one as well), two systems on the way are marked for no obvious reason.  I guess, this is done to help people who are trudging along using an obsolete weak-ass mode of travel such as using an ordinary hyperdrive.  If you have a jump drive, you'll skip those systems and go to the target directly.  Too bad, the mission won't complete until you go back and visit every such marked system.

**Comment by endless-sky** [comment]
I took the waypoints out in commit 5f1c5c3. I think the mission text already gives you enough of a hint of which direction you should go in, that the waypoints aren't needed.
