### ISSUE TITLE
Surveillance pods are worthless

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#590]
They do the same thing as an outfit scanner and a cargo scanner, but cost more outfit space. I think they need to have an outfit space reduction or a special feature you can't get with just an outfit scanner and a cargo scanner.

**Comment by lor1113** [comment]
good point, maybe combined with the timed scan idea someone else had they could have a faster scan time

**Comment by lor1113** [comment]
*than other scanners*

**Comment by frameworld** [comment]
I thought they have more scan range or strength (against interference plating)

Atmospheric scanners (3rd type defined on them) is currently of no use.

**Comment by bobafetthotmail** [comment]
Not only that, they even have shorter range. WAT?

From the description they seem to be supposed to go in surveillance drones.
And checking the surveillance drones... yes they use them. I think it might be a good idea to change the stats.

Pasting here the game data:

outfit "Cargo Scanner"
	category "Systems"
	cost 8000
	thumbnail "outfit/cargo scanner"
	"mass" 1
	"outfit space" -1
	"cargo scan" 300
	description "This scanner allows you to scan the cargo holds of the ship you are currently targeting, as long as you are flying close enough to it. Patrol crafts use cargo scanners to detect illegal contraband."

outfit "Outfit Scanner"
	category "Systems"
	cost 24000
	thumbnail "outfit/outfit scanner"
	"mass" 2
	"outfit space" -2
	"outfit scan" 500
	description "This scanner allows you to determine what outfits are installed in the ship you are currently targeting, if you are willing to risk flying close enough to it to get a reading! The Republic Navy uses these scanners to detect when ships are equipped with illegal weaponry."

outfit "Surveillance Pod"
	category "Systems"
	cost 42000
	thumbnail "outfit/outfit scanner"
	"mass" 5
	"outfit space" -5
	"outfit scan" 400
	"cargo scan" 200
	"atmosphere scan" 100
	description "This is Republic military technology, a collection of scanners designed to fit perfectly inside one of their surveillance drones. Since the outputs are fairly standard, you could connect it to your own ship's systems if you want."

**Comment by lor1113** [comment]
I'm going to open a fork to deal with this K?

**Comment by lor1113** [comment]
I'll decrease mass and outfit to 2 and outfit and cargo scan values to standard, as well as increasing range

**Comment by lor1113** [comment]
Fork created and submitted pull request

**Comment by dplepage** [comment]
I believe the important difference that makes it more expensive and larger is this line:
```
"atmosphere scan" 100
```
At the moment, I don't think scanning planets is implemented for the player character, but NPCs with atmospheric scanners (such as the surveillance drones) will scan planets.

**Comment by lor1113** [comment]
no, there is no such code (as far as i can see) attached to this attribute

**Comment by dplepage** [comment]
@lor1113 It's in the AI code, https://github.com/endless-sky/endless-sky/blob/master/source/AI.cpp#L1094

**Comment by endless-sky** [comment]
Surveillance pods are only intended to be a plot device. There's no way to
buy them (so the only way to get them is by robbing Navy drones). That,
plus the fact that people complain about how often surveillance drones scan
them already, makes me not particularly eager to make those scanners even
more powerful.

In terms of plot, as @dplepage noted, the surveillance pods are primarily
an advanced atmospheric scanning system, and the cargo and outfit scanning
is just a minor extra feature.

**Comment by Gkramme** [comment]
I wonder if it could be a way to scan a ship, see how much crew it has, and deliver all the stats to you. In that case, you could be more well prepared for capturing a ship and know if it's worth going across the system for.

**Comment by frameworld** [comment]
Bio-scanners.

If there will be more scanner types for it, Surveillance pods can stay at 5 mass / outfit space.

**Comment by Gkramme** [comment]
Agreed

**Comment by Gkramme** [comment]
Why was this closed?

**Comment by dplepage** [comment]
@Gkramme I assume because it was intentional that surveillance pods are useless - as @endless-sky  said, they're just a plot device, and it makes sense plotwise that they're strictly worse than just having outfit and cargo scanners because the bulk of the surveillance pod is an atmospheric scanner, which as a player you don't have any use for. So there isn't anything to fix here.

**Comment by Gkramme** [comment]
Alright then
