### ISSUE TITLE
Feature request: Add attribute to quarg planets based on region

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#5901]
**Is your feature request related to a problem? Please describe.**
I was trying to create spaceport news for Quarg worlds (in human and hai space), when I ran into an interesting issue. These worlds have the Quarg government, but there is nothing else that distinguishes them from the rest of the worlds, and especially not from other quarg worlds (in Kor Efret space, for example). They have no attribute that tells which region of space they are in.

I've checked some missions and jobs and they filter quarg words by specifying the government and using `near`, for example:

```
mission "Quarg Satellites"
	source
		near "Umbral" 1 3
		government "Quarg"
		not planet "Humanika"
```
		
This specifies every quarg-inhabited planet in human space (Humanika is controlled by Quargs, but not habitable for them).  However, this solution is not open to extensions. If there were quarg worlds away from Tarazed, maybe the ringworld in hai space would be closer than the new world, and thus editing this specification would became a lot harder. Since `or` and `and` cannot be used in location filters, fixing these issues would potentially include manually filtering out (with `not`) every other quarg world - which is a really bad idea.

Other filters such as `neighbour` also doesn't work - for example, Forpelog in the Sadalsuud system is in human space, but isn't directly connected to any systems with human governments.

		
**Related Issue Links**
I didn't find any related issues (as in, filtering quarg worlds based on territory), I have however came accross #5525 which would provide a fix for this issue.

**Describe the solution you'd like**
If quarg planets (potentially every inhabited planet, but that would be pointless in most cases) had an attribute that specifies which territory they are in, specifying and extending filters for these Quarg worlds would become a lot shorter and would also be easier to modify. (Just to clarify, I know some of them have attributes like `south`, but that only hides the issue. In my solution, they would have attributes like `human quarg` or something like it, that would directly identify them anywhere on the map.)

Having such a system would be pointless for most planets, because afaik only the quarg has isolated settlements around the map (and they are controlled by the same faction, unlike the Pug planets.)

**Describe alternatives you've considered**
Adding support for multiple entries in `near` (in an `or` relationship) would also fix this issue. Alternatively, a `near government` or `near attribute` could potentially be used, although it is more likely to break if the quarg worlds are close to multiple races. Adding support for `or` and `and` in location filters would also fix the issue (#5525 ), although it would be slightly less effective in this specific case.

**Comment by Amazinite** [comment]
> Other filters such as `neighbour` also doesn't work - for example, Forpelog in the Sadalsuud system is in human space, but isn't directly connected to any systems with human governments.

The neighbor filter can effectively have a distance. This filter would be able to select any Quarg planet that is either a neighbor or a neighbor of a neighbor (2 away from) any Republic, Neutral, or Free Worlds system.
```
source
	government "Quarg"
	neighbor government "Republic" "Free Worlds" "Neutral"
	neighbor
		neighbor government "Republic" "Free Worlds" "Neutral"
```

**Comment by tibetiroka** [comment]
Oh interesting. O(N) lines for n distance - it works well for short numbers at least.

What's your opinion about the main idea?

**Comment by Amazinite** [comment]
Well we have regional attributes for pirate planets ("south pirate", "north pirate", "core pirate") for differentiating where jobs and missions should offer, so I don't see why we couldn't have regional attributes for Quarg planets.

**Comment by Amazinite** [comment]
Created three regional attributes "human quarg", "hai quarg", and "korath quarg".

**Comment by tibetiroka** [comment]
I don't know if you've read my comment on the commit, but you missed 'Humanika'.

**Comment by tibetiroka** [comment]
True, but it has Quarg government. It is an edge case - if you think it doesn't need the attribute, it's fine. I'm just trying to make sure it is not an accident.
