### ISSUE TITLE
Request: Mission Attribute to suppress "Mission Failed" text

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5909]
**Is your feature request related to a problem? Please describe.**
Within the Endless Sky mission system, it is possible to use the succeed/fail mechanic to differentiate between the player taking different paths. An example of this is in the Remnant mission to locate the Korath fleet, where if they simply locate the fleet and report back it counts as a success, and if they destroy the Korath fleet before reporting back, it counts as a fail. This is used to trigger branching text in the subsequent mission that reflects the player's initiative, and in neither case is it actually, as far as the story or the player is concerned, a failure. That being said, as illustrated by the issue filed about this mission, the fact that the "mission failed" text displays is confusing to some players.

**Related Issue Links**
https://github.com/endless-sky/endless-sky/issues/5908

**Describe the solution you'd like**
A one-word mission attribute, similar to invisible or job, that can be added to the mission parameters to suppress the "mission failed" text from being displayed for the mission it is a part of. 
`silentfail` would be nice and to the point.

**Describe alternatives you've considered**
- Avoiding missions that can have branching results.
- Separating out the part of the mission that can be failed into invisible subsidiary missions with their own triggers, and results that can be tested. I find this undesireable, as using multiple missions simultaneously within the context of a single visible mission introduces more moving parts, and in my experience are harder to setup, harder to test, harder to bugcheck, harder for new content creators to use, easier to break, and ultimately less reliable than having the entire contents of a mission in a single item.

**Comment by waterhouse** [comment]
Suggested name: `silentfail`.  (A naive reading of "suppress fail" would be "don't allow this to fail".)

**Comment by Amazinite** [comment]
Note that silent failure will not solve all the problems with Remnant: Cognizance 4. `on fail` appears on the first landing after the mission has failed, so even if the "mission failed" message didn't appear, you'd still have an issue in being able to get the dialog with Chilia on any planet instead of the intended destination.

**Comment by Zitchas** [comment]
True. But this isn't trying to solve that particular problem. This is specifically just aiming to solve the problem of people being notified that they'd failed something when they *mechanically* have failed something but not *story* failed something.

**Comment by tehhowch** [comment]
The player should always be told about failing a mission _they can see in their mission list_.

If you don't want a player to know if a mission was failed, that mission should be invisible.

**Comment by Zitchas** [comment]
OK, so two changes then:
1) the `silentfail` tag prevents the mission fail message from displaying, AND,
2) we introduce location limiters for the failure dialog that function just like the source and destination location methodology. Then a mission that doesn't specify a fail location can fail anywhere, just like at present, but if it is specified, then it can only fail at the specified location.
