### ISSUE TITLE
NPCs Kill All Boardable Ships

### ISSUE THREAD

**Issue by uchua** [endless-sky/endless-sky#591]
I've put a few dozen hours into the game and have managed to only successfully board a single ship. Every other time, even when in the process of drifting toward the ship to board it, an NPC has felt the need to destroy the ship. This is regardless of whether or not NPCs have been the ones fighting the ship or I have. I'm not sure if this is scripted to happen or what have you, but it seems to make the boarding mechanic useless.

**Comment by lor1113** [comment]
this is scripted, you just have to try and board ships in an area with no NPC's. While boarding pirate ships isn't technically illegal, it is clearly something frowned upon

**Comment by thenerdfreak** [comment]
after playing through the storyline over ten times, I can confirm and affirm that it is a good thing that they blow up those ships. Just avoid Republic and Militia ships (those are the only ones that directly target disabled pirates as far as I can tell. Without this you'd get op fast

**Comment by ItsNickBarry** [comment]
Try to lure the pirates away from the center of a system, and use laser weapons to ensure that you deal only as much damage as is necessary to disable them.

**Comment by endless-sky** [comment]
Boarding ships is quite easy if you do it in a system where the militia / Navy don't visit much (like, most pirate systems) and if you lure your target well away from the system center before disabling it, so you're not right in the middle of all the traffic.

**Comment by sanjayatio** [comment]
i always shake my head reading this kind of message - considering my 1st playthrough (on v.0.8.5).
it's funny how people complain about npc killing their prey considering that i earned my living by stealing from npc's victims.
sure, some npc have the tendency to vaporize a disabled ship, but when there is an active hostile ship, that hostile has the bigger priority.

starting my career as a travel agency, my 1st big upgrade was a blackbird.
with this i became a vulture by:
- going to a system with sizable pirate & navy presence (that oathkeepers base)
- sit at a corner to watch the carnage
- when i see a disabled pirate ship, i quickly dive in, loot, and went back to my corner.
- occasionally (when i judged it safe enough) i would board a ship, run away with that ship tailing, asked that ship to hold its position and i continue my vulturing ways.
  - got a few firebirds this way
- after a while i started killing my own prey - still with a blackbird as the flag ship.
- the next progression is a no brainer - bactrian; retiring the blackbird (and my career as a vulture).
   - how can i loot with a slow flagship? give it some of those korath turrets and push my target away to the side.

i won some, i lose some, but i know there are many occasions where i use the npc to my advantage.
