### ISSUE TITLE
Request: Ability to specify a trigger location for Fail

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#5912]
**Is your feature request related to a problem? Please describe.**
Right now, when a mission fails, it takes place immediately the next time the player lands, no matter where it is. This can cause mission text to display in places that aren't appropriate for it to do so.

**Related Issue Links**
> Note that silent failure will not solve all the problems with Remnant: Cognizance 4. `on fail` appears on the first landing after the mission has failed, so even if the "mission failed" message didn't appear, you'd still have an issue in being able to get the dialog with Chilia on any planet instead of the intended destination.
_Originally posted by @Amazinite in https://github.com/endless-sky/endless-sky/issues/5909#issuecomment-828510733_

**Describe the solution you'd like**
An identical entry to the current `source` and `destination` fields called `fail` wherein we can specify a location (or a filter for a range of locations) using the same methodology as we currently do for other location determining fields. This location (or range thereof) would be the only place that a mission would actually finish, record the fail, and process any actions listed in its `on fail` section.

**Describe alternatives you've considered**
Having to have a visible "cover story" mission along with one or more invisible "failure" missions whenever a mission failure would be inappropriate to happen anywhere in the galaxy. 

**Additional context**
Being able to have a mission go two different directions using the fail criteria can facilitate branching mission structures. However, if we cannot have the same control over where the failure part ends as we do for the success side, then the ability to effectively make use of this is severely limited. 

I suspect that most mission writers (who tend *not* to be code herders) dread the idea of having to have two separate missions to handle each "half" of a mission. That's basically double the work for something that no-one will ever see more than half of.

Furthermore, the more missions that need to run simultaneously, the harder it is to write, test, bug check, and understand. Most importantly, I find that such stacked missions tend to be unreliable and problematic to use.

**Comment by Amazinite** [comment]
> Being able to have a mission go two different directions using the fail criteria can facilitate branching mission structures. However, if we cannot have the same control over where the failure part ends as we do for the success side, then the ability to effectively make use of this is severely limited.

As with #1938 and Nomadic supposedly running into it all the time with his PRs, I imagine that any situation where you're using a failure to branch a mission can be changed to not require the failure without needing to alter the narrative, at least not drastically. In the case of #5909, I've already provided a restructuring of that mission that wouldn't require a mission failure.

**Comment by Pointedstick** [comment]
Yeah, I think it's sensible enough to do this with existing tools.
