### ISSUE TITLE
Intro missions "end" unexpectedly depending on player ship type

### ISSUE THREAD

**Issue by LouisB3** [endless-sky/endless-sky#5917]
**Describe the bug**
The tutorial mission sequence comes to an abrupt and silent halt if the player's ship(s) do not match any of the expected categories.

Specifically, James will not appear in the New Greenland spaceport to offer the second intro mission ("Intro [1 ...]", after completing "Intro [0]") if none of the player's ship(s) are in the following categories:

- Transport
- Light Freighter
- Interceptor

From the player's perspective, they are told to meet James in the spaceport but then he never appears; no explanation appears as to why, and this storyline is never resumed unless they should happen to visit the spaceport on this planet with one of the above ship categories at some point in the future.

While not common, this can occur if the player has accepted the first intro mission, but then ignored or postponed it to do something else, such as capturing pirate ships. Such a player may not actually need a tutorial, but they're left without resolution of this minor storyline (James' retirement, etc.)

**To Reproduce**
1. Start a new game and agree to transport James to New Greenland.
2. Along the way, upgrade your ship to a category not listed above (e.g. a Quicksilver or Headhunter).
3. Drop James off on New Greenland, then head to the spaceport as instructed; he won't meet you there.

**Expected behavior**
The simplest solution would be to expand the offer conditions on the missions to include additional ship categories. This would ensure that the mission storyline can be completed as expected. 

```
mission "Intro [1 Freighter]"
	to offer
		has "Intro [0]: done"
		or
			has "ships: Light Freighter"
			has "ships: Heavy Freighter"
		not "Intro [1 Transport]: offered"
		not "Intro [1 Interceptor]: offered"
```

```
mission "Intro [1 Interceptor]"
	to offer
		has "Intro [0]: done"
		or
			has "ships: Interceptor"
			has "ships: Light Warship"
			has "ships: Medium Warship"
			has "ships: Heavy Warship"
		not "Intro [1 Transport]: offered"
		not "Intro [1 Freighter]: offered"
```

Optionally, dialog could be tweaked for the above missions as well, to acknowledge that the player is piloting an unexpectedly capable ship.

**Screenshots**
~If applicable, add screenshots to help explain your problem.~

**System (please complete the following information):**
 - OS: observed on Windows 10 Home, but probably applies to any OS
 - Game Source: observed on Steam and GitHub distributions
 - Version: observed on 0.9.12, but probably applies to 0.9.13 or any other version

**Link to save file**

- [Save file](https://github.com/endless-sky/endless-sky/files/6400377/Tutorial.Tester.txt)
- [intro missions file with proposed changes](https://github.com/endless-sky/endless-sky/files/6400378/intro.missions.fixed.txt)

**Additional context**
Normally I'd try to implement this fix as a plugin for testing purposes, but it appears that plugins currently still can't override stock missions: #4489

**Comment by Amazinite** [comment]
Well if you're ignoring James to go out on a crazy adventure then returning with much better ships, then maybe James should just leave since you clearly know what you're doing. \:)

**Comment by Vedvod** [comment]
Perhaps if the player is piloting a more capable ship (caught an else statement or equivalent), James mentions that the player is a natural trader/fighter/transporter (depending on if a cargo or passenger or fighter?) and skips ahead to being dropped off at New Hestia (is that the planet? Whatever planet it is that he wants to go to) ? Or perhaps James could mention the player's capability and bring out some harder missions?

**Comment by mylesbartlett72** [comment]
I think James should do the above, but when the ship is changed, not at the spaceport.  Also have a special attribute for the starting ships that is invisible, but gets used for detecting ship changes.
