### ISSUE TITLE
Remnant: Keystone Research - Keystones considered a device

### ISSUE THREAD

**Issue by Ornok** [endless-sky/endless-sky#5924]
In `Remnant: Keystone Research` (R:KR), Aeolus talks about _dismantling_ (R:KR 1) and _building_ (R:KR 5) Hai quantum keystones, implying they are some kind of device. But both Quantum Key Stones and keystones are supposed to be chunks of rocks mined on Viminal and Hai-Home respectively.

**Comment by Zitchas** [comment]
Key Stones / keystones are "devices" in the sense that, say, a diamond ring is a device. Diamonds are mined, but have to go through a significant amount of manufacturing and setting before they turn up in a piece of diamond jewellery. 

My interpretation is that the outfits known as a Key Stones / keystones are the final product, not the raw resource as extracted from the ground. At the very least they have the crystal and the mount; but it is entirely possible they have actual equipment attached to them. For example, a mechanism to project energy through it, something that can passively react to outside energy, lighting (especially the Hai ones - they're good luck charms, and those tend to attract aesthetic modifications).

**Comment by Ornok** [comment]
My bad. I got hung up on the Quantum Keystone definition that discribes it as a "chunk of rock".  I hadn't even noticed the three legs attached to the stone in the outfit picture... Thanks for the clarification.
