### ISSUE TITLE
Dead link - Discussion Forum

### ISSUE THREAD

**Issue by tplive** [endless-sky/endless-sky#5928]
**Describe the bug**
The wiki has a link to "Discussion Forum" pointing to Google Groups which is dead.

**To Reproduce**
1. Go to https://github.com/endless-sky/endless-sky/wiki
2. Click on 'Discussion Forum' (points to https://groups.google.com/group/endless-sky)
3. See error "Content unavailable".

**Expected behavior**
I expected to be taken to the discussion forum. :)

**Screenshots**
N/A

**System (please complete the following information):**
Wiki

**Link to save file**
N/A

**Additional context**
N/A

**Comment by MCOfficer** [comment]
See https://github.com/endless-sky/endless-sky.github.io/issues/23, https://github.com/endless-sky/endless-sky/pull/5743
