### ISSUE TITLE
Ramscoop that generates fuel faster when closer to a star

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#593]
since they're "Wanderers" it really wouldn't make sense for them to stop to refuel CONSTANTLY like other aliens lore-wise, so maybe they have a super ramscoop or something bio-technological that creates fuel

**Comment by lor1113** [comment]
Added these in my own fork, will request merge later

**Comment by lor1113** [comment]
also thinking about adding a wanderers weapon that disables, like ions but much stronger, what do you think?

**Comment by thenerdfreak** [comment]
only if they had the AI to jump out of the system as soon as your ship overheats/runs out of energy, would that be cool.

**Comment by bobafetthotmail** [comment]
they are called "wanderers" for other reasons, they aren't a ships-only race like say Kroath.
Look at their missions for details (obvious spoiler alert).

**Comment by lor1113** [comment]
What about travelling through the Eye, that is a risky journey that would need a lot of fuel

**Comment by lor1113** [comment]
Besides, they still need to make fuel, and in their space there are no harvesting stations or gas giants from which to harvest plasma, nor any mention of how they make fuel

**Comment by frameworld** [comment]
One species could have items fuel regeneration near suns.

High fuel regeneration should come with a low fuel-bar. Perhaps as integrated ship system + outfit-able less efficient extensions?

In StarGate, Wraith ships have to stop once every now and then to recover from FTL because they are biological.

**Comment by natangold** [comment]
> One species could have items fuel regeneration near suns.

"Wind Turbine", fuel gain based on inverse natural logarithm of distance between ship and stellar sprite? Nifty idea, and comes ready-made with the speciesist epithet "star hugger".

**Comment by nylki** [comment]
closed via https://github.com/endless-sky/endless-sky/commit/cd56c91f0aa4450dad1b00c040d28bf4a36a3ddd

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
