### ISSUE TITLE
Addition of "Turn Fuel" and "Thrusting Fuel" attributes

### ISSUE THREAD

**Issue by VaelophisNyx** [endless-sky/endless-sky#5934]
**Is your feature request related to a problem? Please describe.**
Problem is only a lack of attributes of use to plugin developers

**Related Issue Links**
https://discord.com/channels/251118043411775489/431496424992014347/838770238778638377
current discussion of this on the Discord server

**Describe the solution you'd like**
Simply adding these two attributes to allow fuel to be used by thrusting and steering would be all that is needed here.

**Additional context**
I doubt this would be much use in vanilla ship outfits, but, could still be nice to add.

**Comment by Plip-Plop** [comment]
Do you mean hyperdrive fuel?

**Comment by GalacticRuler** [comment]
Indeed, being consistent with other uses of attributes for fuel use.
