### ISSUE TITLE
Swizzle changes don't apply to carried ships

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#5936]
**Describe the bug**
If an event changes the swizzle of the player, after departing the swizzle of normal ships is modified accordingly but not for carried ships (drones and fighters) until those are launched

**To Reproduce**
1. Buy some ships capable of carrying fighters/drones and said fighters/drones
2. Use an event to change your swizzle
3. Depart

**Expected behavior**
Carried ships should change swizzle

**Screenshots**
![Screenshot (619)](https://user-images.githubusercontent.com/45330165/117139141-30d24980-adac-11eb-868e-a99c8a1bfca8.png)
After departing having changed the swizzle from 5 to 0
![Screenshot (620)](https://user-images.githubusercontent.com/45330165/117139143-32037680-adac-11eb-914e-7ae50f126f93.png)
After launching the fighters

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: ESLauncher2
 - Version: lastest nightly

**Comment by movingpictures** [comment]
For the ... unwashed and uninformed .... whatdaheck is a swizzle?

**Comment by tehhowch** [comment]
Possibly related to #1462 or #2295

I'm not positive on the order of events you're having take place; mind throwing a repro save together?

**Comment by beccabunny** [comment]
here you go [tommaso becca.txt](https://github.com/endless-sky/endless-sky/files/6434814/tommaso.becca.txt)

steps I followed to make it:
-started with swizzle 0 since I already had that
-brought 1 roost and 4 finches
-used omnis' mission for simplicity to change my swizzle to 4, which has this code:

```
mission "swizzle 4"
	name `Swizzle- 4`
	description `Changes ships appearance to have a color swizzle of R->B->G->R. E.g. Syndicate; purple.`
	job
	repeat
	source
		government "cheat"
	on accept
		event "swizzle 4"

event "swizzle 4"
	government "Escort"
		swizzle 4```
what happens is:
-departing the roost changes its swizzle to 4 but the fighters are still at 0
-releasing fighters now they too have swizzle 4

**Comment by vitalchip** [comment]
I think this is probably because swizzle gets set during Ship::Place() which wiould usually be when departing the planet but for carried ship it'll be during Ship::Launch()

Could swizzle be set during Ship::FlightCheck() ?

**Comment by tehhowch** [comment]
> I think this is probably because swizzle gets set during Ship::Place() which would usually be when departing the planet but for carried ships it'll be during Ship::Launch()

Yep, which is what is called out in #1462. The fix for that issue was to move the setGovernment function call to after player data is loaded.
 
> Could swizzle be set during Ship::FlightCheck() ?

No, that's not the place for mutating the ship object. The fix is to ensure swizzles are set for ships that are active or carried when the player departs, after the date has updated and related events have processed.

**Comment by unjown** [comment]
did you re land/depart?

**Comment by beccabunny** [comment]
> did you re land/depart?

The steep to reproduce this are in the OP

**Comment by petervdmeer** [comment]
I tested #5936 and it seems to fix the wrong swizzles when a carrier launches from a planet, but I'm afraid that the following behavior is also present:
- if you capture a pirate-owned fighter, dock it and then undock it, then the swizzle changes at launch/undocking.
- if a swizzle-changing event happens during flight, then carried ships will switch to the new swizzle at launch/undocking.

Do you want to handle those as part of this ticket as well?

**Comment by tehhowch** [comment]
@petervdmeer those two issues are also present without #6129, as launching a fighter calls `Ship::Place`, where the swizzle is set.

Probably the manner in which "already spawned" ships are restored to active duty should follow a slightly different path than "ships spawning for the first time," which would include _not_ changing their swizzle until they have a chance to properly land and depart again.

**Comment by petervdmeer** [comment]
> @petervdmeer those two issues are also present without #6129, as launching a fighter calls `Ship::Place`, where the swizzle is set.

Yes, and I didn't mean to suggest that #6129 caused those issues. Just wanted to indicate that there are more Swizzle issues which we might want to look at.

> Probably the manner in which "already spawned" ships are restored to active duty should follow a slightly different path than "ships spawning for the first time," which would include _not_ changing their swizzle until they have a chance to properly land and depart again.

I agree.
