### ISSUE TITLE
Suggestion: Normal Maps for Ships

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#595]
If we rendered normal maps for ships we could do dynamic lighting pretty easily, giving the ships a much more 3D look without requiring dozens of images - you just need an unshaded color image and a normal map, e.g.:
![color](https://cloud.githubusercontent.com/assets/107468/12117497/249061f6-b38f-11e5-86c6-6d6c7641b1f8.png) ![norm](https://cloud.githubusercontent.com/assets/107468/12117498/274fa19a-b38f-11e5-8320-93fa34508f88.png)

And then you can render the ship under any lighting:

![bactlit](https://cloud.githubusercontent.com/assets/107468/12117435/bcdfaa1c-b38e-11e5-8b80-d8834820e5d9.gif)

The main downside of this is that you need a normal map for every ship image, which means you can't just draw a ship in photoshop or whatever and drop it in. It looks like most people are using Blender, though, where it's really easy to render normal maps (it's how I made the one above, and I could probably make a small Blender plugin to automate that if there's interest).

It'd also be pretty easy to include multiple light sources, so that e.g. ships flying in binary/ternary star systems could be lit from multiple directions.

**Comment by frameworld** [comment]
I'd love the possibility.

Have normal-map?
 * Yes? Render in the new way
 * No? Render in the old way

Want consistency?
 * create an old sprite from a new sprite with normal-map and put it into the cache folder.

**Comment by dplepage** [comment]
I suspect it'll look kind of weird to see ships with static lighting flying alongside dynamically-lit ones, but I agree that making it optional is the best way to go, so that plugin authors can still make ships without normal maps. Possibly it should also be something you can disable in the settings.

**Comment by Pointedstick** [comment]
That is reeeeeeeeally sweet. I like it!

**Comment by Gkramme** [comment]
Yes, I was annoyed that the shadows were always pointed in one direcrion, no matter the ship's position relitive to the sun

**Comment by knope** [comment]
+1

**Comment by bobafetthotmail** [comment]
Agree. This is a rather clever trick.

+1 also for the blender plugin to automate this.

Would this increase graphic load or be annoying to keep working in a cross-platform game?

>"It looks like most people are using Blender, "

Afaik, old 2D ship images are being migrated to renderings, and it's mildly recommended in the wiki to use blender, then render it, then post-process it in GIMP for more grit and stuff.

**Comment by dplepage** [comment]
> Would this increase graphic load or be annoying to keep working in a cross-platform game?

I think the increase in graphic load would be minimal - one extra texture per type of ship and a few extra lines in the fragment shader.

**Comment by Pointedstick** [comment]
Of course, there's *shading* and then there's *shadows.* This idea would produce dynamic shading, but eliminate the shadows, inverting the status quo, which has ships with baked-on shadows and no shading dynamism.

**Comment by egilburg** [comment]
Given a normal map, could you emulate shadows by checking the position (and rotation) of our ship relative to the current system's sun?

**Comment by frameworld** [comment]
Yes. that is simple math @egilburg , calculate:
 1. box-size = ship.pos - sun.pos
 2. distance = math.sqrt(x*x+y*y)
 3. vector = box-size{x, y} / distance
 4. angle = inverse-sinus of vector.y or inverse-co-sinus of vector.x
 5. angle = angle + ship.rotation

But in space you have "hard light". There is little to no ambient light shining on shadows.
Sometimes you have a very bright face, then at little different normal/angle, you can have a pitch-black face.

**Comment by dplepage** [comment]
@Pointedstick Yes, the shadows are lost - you can see this in the bactrian example where the top fins no longer look as interesting. For most existing ships this is a pretty small loss, and I think the shading adds more than static shadows would. There are a few (like the Skylark) with larger shadows; I haven't tried normal-mapping those yet (or rather, I did but the Skylark geometry has some weird normals I need to fix). I suspect the shading will still add more than the shadows would.

@egilburg That's how I'm generating the shading, but a normal map doesn't have enough information to compute shadows. In theory we could figure them out from a height map, but that's a lot more complicated to compute because shadowing is non-local (meaning you can't compute the shadow at one pixel without considering the height of other pixels) and at that point we'd probably be better off actually using full 3D models for the ships.

**Comment by frameworld** [comment]
> In theory we could figure them out from a height map, but that's a lot more complicated to compute because shadowing is non-local (meaning you can't compute the shadow at one pixel without considering the height of other pixels)

I always thought bump-maps are high-maps, correct me if I am wrong.

Imagine a graph for f(angle)=(light-strength).
The differential graph shows the "ranges along x" of "greatest changes in the orignial grahp's y" as spikes.
Save the spikes, interpolate values inbetween. (Angle=light-level) for each spike (max 4-8).
GPUs can have 800 processors (enough for all pixels) and it's an uniform task per pixel, thus I guess it should be possible to calculate that on the GPU.

**Comment by dplepage** [comment]
@frameworld So bump-mapping is generally done in one of two ways - either you have a normal map, which indicates the orientation of the surface at each point, or you have a height map, which tells you the height of each point above some base plane. To get the shading right like I did above you need normals; you can approximate these from a heightmap but it involves a lot more computation (you're computing heightmap derivatives at each pixel). Technically you can also approximate the heightmap from the normals by integrating them, but that's also numerically difficult to do accurately.

Anyway, to properly compute the shadows based on a heightmap you basically need to trace rays from your pixels to see whether they hit some other part of the ship before they reach the light. This is doable, but increasingly expensive as the ship image gets larger, because for an nxn image you need to check collisions against O(n) pixels to see if you're going to be in shadow, and you need to do this for every pixel, so suddenly this takes cubic time. It also breaks some of the parallelism that makes GPU processing so fast - ideally, each pixel actually performs computations in lockstep, but in this case different pixels have to check against different numbers of other pixels.

The normal shading I did above allows me to light the Bactrian from literally any direction; if we only allow the lighting to come from a fixed 1D set of directions (e.g., by deciding that only the horizontal direction to the light matters), then we could maybe precompute a 1D shadowing function for each pixel and approximate it by just a few terms. That would allow us to compute shadows on the fly, but it would also involved a lot more texture memory per ship and a lot more work per pixel, and at some point it'd be less work to just throw out all the existing rendering code and use some existing 3D game engine and real 3D models instead.

**Comment by guillochon** [comment]
+1, I'd love to see this.

**Comment by dplepage** [comment]
Oh, the other thing that's lost with my current method (besides shadows) is internal lighting, which I didn't realize many of the alien ships had. For example, an unlit skylark looks like this:
![skylark](https://cloud.githubusercontent.com/assets/107468/12160877/2594948e-b4be-11e5-83e7-79bfd29ad3af.png)
because of the faint glow from its own systems. It wouldn't be too hard to add that, but it does mean another texture per ship (you just add the internal lighting to the external lighting to get the final image).

**Comment by dplepage** [comment]
And while we're on the subject of adding extra textures, it'd also be awesome to have a swizzle bitmask so that you could build a ship whose faction highlights are limited. Right now if you give yourself a pug ship the whole thing'll change color depending on your faction, because the swizzle applies to your entire ship.

So the full shading process at each pixel would be:

1. Read the base color from the flat image
2. Swizzle it if the swizzle mask is 1 to get the local color
3. Compute the vector to the light source
4. Dot this with the normal and multiply that by the swizzled base color
5. Add the self-emission component

**Comment by dplepage** [comment]
I've put together a little bit of tooling around this, which I checked in https://github.com/dplepage/es-normal-ships . It builds flat textures, normal maps, and emission maps from .blend files.

It does handle emissions now, so the skylark output looks like this, with the purple and blue glows preserved:
![spin](https://cloud.githubusercontent.com/assets/107468/12189599/4897b48c-b58d-11e5-8d01-786fcb598a4f.gif)

It has some limitations:
 * It takes its best guess at which lights are emission lights and which are the environment by assuming that any light named "Sun" or "Lamp" is the environment. This seems to be mostly true, but a few ships like the headhunter have other lights in their blendfiles that I'm pretty sure aren't intended to be ship emissions.
 * It only renders the textures present in the blendfile. Most (all?) ships have xcf files where @endless-sky did a lot of extra texturing; all that work would have be transferred to the flat outputs of my tooling before these could be used in production.
 * It obviously won't work with ships that aren't actually modeled in Blender. AFAICT the Korath Raider is the only such ship (it appears to be a bare-bones SVG image with considerably GIMP modification).
 * It also won't work automatically for ships like the deep river, where the blendfile actually shows two ships and some extra components, which were then remixed in GIMP to yield a number of variations on the same ship. It can still be used for such ships, it'll just require more manual intervention to get them ready.

The texturing issue is most pronounced on the pug ships, where the color was entirely added separately. My script therefore produces a grayscale flat map, which renders like this:

![spin](https://cloud.githubusercontent.com/assets/107468/12189541/bd694484-b58c-11e5-951c-64a5d23cee80.gif)

However, it doesn't look like translating the work from the existing xcfs to use the new flat images is very hard, it's just a little time consuming. I did it for the maboro, which yields this:

![color](https://cloud.githubusercontent.com/assets/107468/12189556/dba2e554-b58c-11e5-9fdb-b088d48f243b.gif)

@endless-sky At this point I'm going to stop working on this until you comment on it - if there's a good reason not to switch to normal mapping, I don't want to waste any more effort on it. But if you do want to go this route, I already have normal maps of all the ships except the Korath Raider, and I'd also be willing to help with the shader code to render these properly.

**Comment by Pointedstick** [comment]
This is so, so cool. I hope it makes it in.

**Comment by bobafetthotmail** [comment]
This totally rocks.

Can it be done with asteroids too?

**Comment by wargwargwarg** [comment]
what a cool ideea, and not just ideea, also a working example (well, a gif example is not the actual code, I guess).
Is it being considered?

**Comment by lehgogh** [comment]
Given that many people are already having issues rendering the larger battles, we need to make sure that this won't cause too much lag. Perhaps make it a selectable option in the settings? (static or dynamic lighting)

**Comment by wargwargwarg** [comment]
So you've hit a bottleneck and that's why the graphics are kept at a bare minimum?
I haven't seen more than perhaps 20 ships together at any one time, and on the screen perhaps 15. Where is the limitation coming from? From the huge number of projectiles, each being calculated per frame? From the engine gifs?
Or from the fact that everything is CPU based, and some calculations would be much faster done by the GPU? That's what sprung the video cards in the first place.
Let's face it, everything from 2000 forward has a dedicated GPU or onboard graphics that would run this game effortlessly. Perhaps it is time to switch frame drawing to the video cards...

**Comment by bobafetthotmail** [comment]
The game runs on OpenGL (GPU) already. Without at least 2D acceleration from the GPU, this game would lag like hell on most PCs.

The load issue in larger battles is due to game AI and tracking stuff moving around, game engine things basically.

I think the bigger issue of this idea is that it requires more effort to add content to the game (although not by much), and that it does require some effort to port all current ships to this new system, plus the code to make it work, and at the end this is just (very) cool, but doesn't change much.

**Comment by wargwargwarg** [comment]
This post was an attempt to add a little "something" to the ships. One has to admit, they fly and look like bricks.

At some point, there has to be something that is easy but important enough to merit being implemented.Are there such visual improvements being prepared? If not, then this is a problem.

How about, making the ships bank when turning? Inertia when turning, just like with thrusters (not instant but after a while). Thruster gifs. Breaking apart when blown (2D of course)

**Comment by bobafetthotmail** [comment]
>This post was an attempt to add a little "something" to the ships. One has to admit, they fly and look like bricks.

Indeed :) 

Although flying like a brick is actually realistic for space movement. Pure newtonian movement, no swoosh. 2D isn't realistic, but we can understand that as making a full 3D game is very hard.

>At some point, there has to be something that is easy but important enough to merit being implemented. 

We are still waiting for @endless-sky , the main (only?) dev here to say if he would accept this addition or not. If he says "yes" someone will probably do it.

>How about, making the ships bank when turning?

Does not make any sense. Space movement does not require ships to bank when turning.

The rest are doable, but need a game engine change so it swaps the ship images depending on different conditions.

**Comment by lehgogh** [comment]
If this gets put through, we would need to make sure that:

- it doesn't lag
- there are details on how to replicate this process in the wiki

**Comment by wargwargwarg** [comment]
believe me, bobafetthotmail, I put some 20 hours into understanding the code to make some adjustments. I've failed, abjectly, so, no, don't count on me.

As for banking in space, it does make sense, sort of. 
in 3D you have the thrusters, 2 sets of steering (port and starboard) and 2 sets for up and down. Imagine the ship banked at 45 degrees from the lateral Up down thrusters: the steering resultant to port would be square root of the sum of port steering  at the second power and down at the second power. If those steering engines arte equal, the overall steering in 1.41 times bigger than the port steering would have been.  
Letting aside if the military would use or not this maneuver, it would look NICE!

**Comment by dplepage** [comment]
I haven't had much free time lately, which is why I haven't commented in a few months, but I've written shaders before (I'm a web developer these days, but my graduate degree was in computer graphics). I'm fairly confident that I could put together the shaders needed to render the normal-mapped models, and that the overhead would be pretty minimal (as @bobafetthotmail noted, I'm pretty sure when the game lags it's because of AI logic and collision detection, not sprite rendering).

I think the biggest issue here is the question of how easy it should be to make ships. In the current version, it'd be pretty easy to grab a bunch of ship images from some abandonware space game and drop them in, or even to hand-draw a bunch of ships if you want to remix your own space game with a very different aesthetic.

With the normal maps, you'd have to live with a weird mix of shaded and unshaded objects or spend time flattening and making normal maps for all your images. It also breaks @endless-sky's current pipeline for ship creation, in that you need to be more careful at what step you do your raw image manipulation to add detail (but with better tutorials ship creators might be able to do this directly on their ship models in Blender rather than as a separate image processing step anyway).

As a side note, someone will already need to do something like that if we want normal maps for [the hallucinations](https://github.com/endless-sky/endless-sky/blob/master/images/ship/hallucination-0.png) or any other ships that aren't rendered in Blender.

That said, if we're willing to tell anyone who wants to make their own ships that they should use Blender, then it's pretty easy to render flat-shaded and normal map images. I already [wrote some crude scripts to do this and threw some rough instructions up](https://github.com/dplepage/es-normal-ships).

**Comment by LocalGod79** [comment]
Noooooo!

**Comment by Pointedstick** [comment]
What a shame.

**Comment by LocalGod79** [comment]
indeed - many, many ships have been added to the game, all of which have blender models to accompany them - hybrid solutions for plugin content are possible...:cry:
