### ISSUE TITLE
"Lagrange Ring: Cargo" mentions "the nearby system, Enif" even though it can be offered in Enif

### ISSUE THREAD

**Issue by Ornok** [endless-sky/endless-sky#5952]
In the `on offer` conversation of "Lagrange Ring: Cargo", the Quarg mentions "the nearby system, Enif". This sounds weird when the mission is offered on Lagrange in the Enif System.

Here is the complete sentence:
`Our ringworld, under construction in the nearby system, Enif, is to have a special open section for humans to visit soon.`

The simplest solution would be to exclude Lagrange as a possible source by using `source "Enif" 1 1` instead of  `source "Enif" 1`.
But since it makes sense to get the mission on the Lagrange station, I'd rather keep Enif as a source and rephrase that sentence.

**Comment by movingpictures** [comment]
In the same mission, the language refers to "humane" materials. FYI.
