### ISSUE TITLE
Voronoi diagram assisted Ship-design, Map-design.

### ISSUE THREAD

**Issue by frameworld** [endless-sky/endless-sky#596]
EDIT: Why do I write this here?
 * The issue is, most peoples don't know about this.
 * And it is a really powerful tool everybody should be introduced into.

The math this bases can be used in processing of visual data or even 3D-model-creation (characters).
It's interesting in almost any aspect of biological aesthetics and even used in professional programs for biological calculations.

http://paperjs.org/examples/voronoi/

Just click as fast as you can once on each red cell on that page.
I think the white inbetween makes a good map (Y-splits are systems, –lines are hyper-lanes)

If you spit each multiple times (remember to not always do a split in the same angle), it makes a nice reptilian-type skin.

If the centre of red bubbles is a ship, the red can be it's area-of-influence.
As long as this area is larger than the ship, projectiles inside it can only hit the ship.
If projectiles can only hit ships in near cells, it's an easy way to optimisation in hit-checks (if no better optimisation is in place and there are many entities in a system)

With weighted centre-points, the red bubble can show the area-of-influence of differently-"heavy" visual details.
This is a great way to visualize/measure the density (=bubble-smallness) of visuals in a certain area of a graphic.
Especially if different weight-classes (large, small details) interact less with each other (ignore each other after a certain ratio*distance). This creates overlapping bubbles, perhaps even of different colour (wavelength of light colour in the visual spectrum ←translates–to→ weight).

How it works:
1. You have many centre-points of cells.
2. Each of them is connected to neighbours by invisible lines (creating a triangle-network).
3. If triangles change and 2 triangles' shared border becomes larger than the distance of unconnected points, the border flips between lines through points A–C and B–D in a –A–B–C–D– polygon.

Drawing steps:
4. Draw a rect-angular line half-way through lines connecting points.
5. Cut this line where it intersects with another belonging to one of the two points connected by the line it originates from. The intersection becomes a corner-point of a polygon-bubble in the Voronoi-diagram.

It is very similar to rendering in 3D-games. Graphic shaders can process all the data in low time.

**Comment by Pointedstick** [comment]
You should really make your own game with these ideas. It's very unclear what you're requesting for Endless Sky or how it would be advantageous vs the status quo.

**Comment by frameworld** [comment]
I suggest to expose math to public knowledge/access.

I am still figuring out what I should make.
 * I really want a new way of organising information too.
 * And free-software character plugin which is easy to use with animation code - one which uses collision detection to decide how to animate a model.

The right order is to write the tools to make this quicker first.
 * I am trying to figure out the best boundary between language-support and stupid-code generation-assistant.
 * I also want to go away from getter+setter methods and use "math between variables". If one changes, the link is executed to account for it. Each variable can change only once per cycle, etc.

If I start this without thinking in what order or how something roughly looks like, it ends up in a mess and waste of time.

**Comment by Pointedstick** [comment]
All of that is very interesting!

However, this is the issues page for a space video game. Very few of the issues you open are actionable, relevant, or even comprehensible. This pie-in-the-sky idea might be very well served in a medium that's under your control, but it doesn't seem to fit in very well to a game created by someone else who evidently doesn't share your goals. You wouldn't go to a classic car meet-up and start talking people's ears off about solar panels and electric vehicles, would you?

**Comment by endless-sky** [comment]
I think discussions like this belong in the [forum](https://groups.google.com/forum/#!forum/endless-sky), not in the issue tracker. If people keep using the issue tracker as a general discussion forum, it will make it much harder to sort out the things that actually are bug reports or actionable feature requests.
