### ISSUE TITLE
A weapon that functions like this:

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#599]
https://www.facebook.com/MinionRebels/videos/1752962844931881/

The way the lightning shoots out these little "tracer particles" ( I know more about lightning that I'm gonna put out here, but gonna simplify) and when one "touches" something, the actual strike happens.

Maybe a slow firing weapon that shoots a slow moving spread of spheres, when one touches something, the others disappear and a beam or lightning strike goes to the ship the "tracer particle" touched

**Comment by endless-sky** [comment]
Would this add any new strategic elements to the game, or would it just be to look cool? If it's the latter, I'm not sure if it's worth making a game engine change just to support it.

**Comment by thenerdfreak** [comment]
It could add an almost "mine field" like element to the game, for defending against mass swarms if fighters (maybe a chain lightning effect even?)

**Comment by frameworld** [comment]
But it would be an easy change:
1. It's easy to add a shot-gun.
2. Let projectiles have a second, randomized movement around their relative position.
3. Create a feedback-effect for the launcher.
 * Path-tools already exist (system-map links and current-path overlay).
  *  It would be cool if that can show any path/node like weapon-beam effects (which also has code in place already).

I can see other uses for more abilities.
 * Proximity detonation for non-tracking slow projectiles
 * "magnetic" projectiles going after a target when close.

But I agree with endless, that this is not worth for just 1 edge case for a single weapon type.

**Comment by brick96** [comment]
Id imagine it is doable already. Have the main projectile slow and shot life and submunitions it breaks into be faster and live longer with I large inaccuracy so they would spread
