### ISSUE TITLE
Outfitter should support toggling visibility of stored outfits

### ISSUE THREAD

**Issue by Amacita** [endless-sky/endless-sky#5992]
With the introduction of planetary outfit storage, the outfitter can get a bit cluttered. Sometimes you just want to see what's in your cargo or what's installed on a ship without also seeing every outfit you have stored on a planet.

This feature request proposes that the outfitter should provide clear and independent control over the visibility of outfits that are

1. installed on a ship,
2. for sale,
3. in cargo, and
4. in storage.

The attached patch will add a new checkbox toggle labelled "Show outfits in storage" to lower left of the outfitter page: 

<img width="155" alt="what the new outfitter key looks like" src="https://user-images.githubusercontent.com/84628273/119228275-3df77400-bae0-11eb-9d92-674df076c33f.png">

To toggle the visibility of installed outfits, one selects or deselects ships as usual.

In order to keep the interface feeling intuitive, I had to make the outfitter no longer automatically switch to cargo view mode when you have no ship selected. Instead, whether cargo is displayed depends entirely on whether "In cargo" is toggled. Not only does this change make things more intuitive, but it also allows the user to view only the installed outfits if they so choose, making it easier for users to see exactly what they have on any given ship.

I have coded the necessary changes and played with the resulting build for a few hours. I find the modified interface very intuitive, and I wouldn't want to go back to the old outfitter behaviour.

Here is the modified version of "images/outfitter key.png" that I used: ![outfitter key](https://user-images.githubusercontent.com/84628273/119228434-00dfb180-bae1-11eb-8fb5-fd69cb3b0a2b.png)

Here is a patch with the code changes:

[patch.txt](https://github.com/endless-sky/endless-sky/files/6526496/patch.txt)

**Comment by petervdmeer** [comment]
Looks like a good change. Can you create a Pull Request with the contents of the patch?

**Comment by Amazinite** [comment]
I made note of at some point doing this here: https://github.com/endless-sky/endless-sky/pull/4443#issuecomment-751039251. An implementation of this should probably also allow purchasing directly into storage; see: #6011.

**Comment by petervdmeer** [comment]
> An implementation of this should probably also allow purchasing directly into storage; see: #6011.

Each implementation also has value on its own, so I would personally also be okay with 2 separate PRs (especially since the code-changes are quite a bit different between the two requests; one is about displaying, the other is about the buying logic).
