### ISSUE TITLE
REP COUNTER/PANEL

### ISSUE THREAD

**Issue by unjown** [endless-sky/endless-sky#5998]
**Is your feature request related to a problem? Please describe.**
its not really a problem but a something i want to know easier instead of checking the save file

**Describe the solution you'd like**
add a small collapsable panel either in menu or in game screen that when you expand it it will show the rep of player

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by tehhowch** [comment]
The player's reputation with various factions can be viewed via the map screen, using the "ports" button.

The player is not intended to know their reputation more precisely than can be inferred from the depth of coloration, so no additional UI will be added to support determining reputation.
