### ISSUE TITLE
Feature: display profit in the trading menu

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#6]
For the greedy ones who want to know exactly how many credits they gained by buying equipment at a very low price to sell it on a planet of spoiled rich people for a high price, it would be nice to have the initial buy price of the price difference displayed in the trading menu.

**Comment by endless-sky** [comment]
I can think of two ways to display that information:

1. Add another column ("Profit") that displays, for each commodity you have in your hold, how much profit per unit you would make for selling it (e.g. "+123" or "-45"). If you bought the same commodity on multiple planets the displayed profit would be based on the average purchase price. Adding another column to the trading table might make it look too crowded, though.

2. Whenever you leave the trading panel (either taking off or switching to a different service the planet offers), add a message at the bottom of the screen that summarizes your profits: "You sold 30 tons of food, 10 tons of equipment, and 40 tons of plundered outfits for a profit of 123456 credits."

I'm leaning towards the second option. In either case, cargo you plundered from another ship would have a "purchase price" of zero.

**Comment by akien-mga** [comment]
A third option could be to display the profit directly in the "Price" column, maybe with just the difference between brackets, e.g.:
```
Food        509 (+41)
Clothing    181 (-148)
```
It's quite similar to the first option, but maybe it would make the table less crowded than adding a dedicated column.

The advantage of those first or third options are that you can easily see if the business is worth making, while with the second option you can only see the total output.

On the other hand, most traders would buy stuff when it's on a low or very low price anyway, so it's not that hard to make it sure that you're actually making profit when selling stuff :) And the message at the bottom of the screen would be quite helpful already, and would prevent making the trading screen look too cluttered.

So that's up to you, if you think the second option is better suited, that will be a great addition already :-)

**Comment by endless-sky** [comment]
Note that in the trading panel, you can press the "view map" button ('M' by
default) to view the star map, with each system colored according to the
price of the selected commodity in that system. You can then click on
whatever system you plan to travel to to compare prices (shown on the left
side of the screen), or click on a different commodity name to switch to
coloring based on that commodity's prices. So, unless you're traveling to a
system you have not mapped yet, you can figure out what your rate of return
will be before even buying that commodity.

**Comment by akien-mga** [comment]
Indeed, I just started playing as a freighter and I discovered this very useful feature :-D

**Comment by endless-sky** [comment]
I've uploaded a change where the "(low)", "(high)" etc. marker changes to "(profit: 123)" for commodities that you have in cargo and that would earn you a profit if you sell them. I also added a message shown when you leave the planet that reports how much total profit you earned (if any) for selling commodities. Let me know what you think of that - in particular, whether it's okay for the high / low information to not be displayed if instead an exact profit or loss amount can be reported.

**Comment by akien-mga** [comment]
Great, I'll try that asap.

**Comment by akien-mga** [comment]
It works great for normal transactions: buy stuff in one place, sell it in another place. There seem to be a couple of issues in some more exotic cases, the one I've encountered so far was when part of my cargo was forcefully and automatically sold to make place for mission cargo:
- there was no feedback about the profit from the transaction (maybe I lost money though? I did not check)
- somehow the cost basis for the remaining non-mission goods was altered: I had bought some luxury goods for ~950 credits, then all of them but one were automatically sold to make place for mission cargo, and in another system the trading menu tells me that I can sell my last luxury good for ~1150 and for a profit of 869 credits.

I'll try to debug this more properly :)

**Comment by endless-sky** [comment]
You're right, there was an error in my cost basis calculations (good thing I'm not an accountant for a living!). Try the latest code from Git and see if that fixes it.

**Comment by akien-mga** [comment]
> You're right, there was an error in my cost basis calculations (good thing I'm not an accountant for a living!). Try the latest code from Git and see if that fixes it.

The new commit seems to trigger a floating point exception. I don't have a backtrace yet, but it happened when I clicked "Depart" in a system where an excess cargo transaction had to be done.

Restarting the game with the same save did not trigger the crash a second time though.

**Comment by endless-sky** [comment]
Yes, it looks like a divide-by-zero occurs if you sell all your cargo of a certain type before leaving a planet, and also take on excess cargo of a different type. I checked in yet another change; hopefully this one fixes it.

**Comment by akien-mga** [comment]
I've been playing for a while with the new commit checked in and I haven't experienced any issue so far.

**Comment by akien-mga** [comment]
> Let me know what you think of that - in particular, whether it's okay for the high / low information to not be displayed if instead an exact profit or loss amount can be reported.

I've been playing for quite a few hours (this game is addictive... :-P), and I really like the new feature. The absence of the high / very high information might be a bit disturbing when one is used to it, but IMO the profit information is more valuable. If you feel that the change is right, you can probably consider this issue fixed.

I did notice one time where the "profit" info was not accurate (it told me my profit – loss actually – on medicine would be something like -450 credits, when it should have been something around ±50. I think this happened after I loaded a previous snapshot, so there might be some info lost in the save/load process.

**Comment by endless-sky** [comment]
I've tested saving and reloading, or quitting and restarting the program entirely, and wasn't able to get it to report an incorrect profit amount. Is it possible the game you loaded had been saved before my latest fix to the calculations? (Or, is it possible that you had an escort that was carrying cargo, and that escort was destroyed? If so, that should be fixed by 3b1e01a.

**Comment by akien-mga** [comment]
I've played a lot and couldn't reproduce a negative profit; I'm playing as a bounty hunter currently though, and I don't do as much trading as I used to, selling pirate ships is more profitable :-P
I think I saw something incoherent yesterday that could be related to 3b1e01a, so that's a nice catch. I'll keep an eye open for possible miscalculations, but so far it looks like the feature is pretty robust.

**Comment by endless-sky** [comment]
This seems to be working correctly now, so I'm closing the issue.
