### ISSUE TITLE
"FW Pug 5A" gone

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#60]
I received the briefing for "FW Pug 5A" but the mission doesn't show up on the missions screen and can't be completed.

I then restored the game from the automatic snapshot (before all Pug battles), and the same happened again: the mission briefing came up, but the mission is gone.

Save file: https://angband.pl/tmp/mission_gone.txt

**Comment by kilobyte** [comment]
... and, third time the same.

**Comment by kilobyte** [comment]
And fourth.  Here's a save before a battle, when you win it the bad mission is given (and gone): https://angband.pl/tmp/before_shiver.txt

**Comment by kilobyte** [comment]
It looks like the "conversation" part is shown, but the "choice" is not.

**Comment by endless-sky** [comment]
It looks like commit 55f62cd (which added that choice in order to clarify what you need to do) messed up that conversation. Commit ab10b1a fixes the bug.

**Comment by kilobyte** [comment]
Confirmed: it works now.
