### ISSUE TITLE
Removal of outfits and Emerald Sword sprite

### ISSUE THREAD

**Issue by GOATBananaMan** [endless-sky/endless-sky#6000]
I have been playing this game a ton since I found out about it a few weeks ago and have enjoyed it so far making it through all stories I've come across, even obtaining the endgame ship, The Emerald Sword. I had stopped playing for a few days and came back to some messed up code.
I've done a bit of save editing and such just to see what happened but have always loaded back to make sure I don't mess anything up, but it may be the cause of this issue which only affects my Emerald Sword, it deletes almost all of my outfits and removes the ship sprite and thumbnail making it to where I can't take off, editing the save file doesn't fix anything as when I load it it removes everything I edited and puts in a bunch of blanks in the code. I also tried creating a new pilot and Copy/Pasting edited code into the new file and it still caused the same issue. 
Also I looked it up and saw others have had somewhat similar problems and it went unresolved but it was believed that being plundered by a pirate ship may have caused the issue and can confidently say I haven't been plundered by a pirate ship since I got my first warship but may have lost a few boarding battles against korath world-ships in my attempts to get one.

Here's the code for what I believe it should look like:
[Matthew Augsburger~~previous-2.txt](https://github.com/endless-sky/endless-sky/files/6535180/Matthew.Augsburger.previous-2.txt)

And here's the code for what it outputs after I load a save:
[Matthew Augsburger.txt](https://github.com/endless-sky/endless-sky/files/6535184/Matthew.Augsburger.txt)

I do have a few plugins installed, here's the names of those:
Adamas Project
AES Irm
Boarding Missions
West Iron
Hand-to-Hand Outfits
Mereti (The one that adds a shipyard to Similisti)
The Machines are Taking Over
Tribute-Domination

Sorry for so much text, just wanted to make sure I included everything I could think of that might be causing this issue.

**Comment by Terin** [comment]
Without digging into it yet, out-of-date plugins can be very haunted and break things. Probably worth seeing if disabling any specific plugins would fix things up for you, although your ship might be affected already.
