### ISSUE TITLE
CORE WASTE AND CORE STORM

### ISSUE THREAD

**Issue by unjown** [endless-sky/endless-sky#6001]
**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those 

none

**Describe the solution you'd like**

core waste and area dominated by the korath (or  a new species) 
where core storm passes and heats up the ship 

technically another version of ember storm

**Comment by Amazinite** [comment]
Ideas about new alien factions or regions of space are for Discord, not GitHub.
