### ISSUE TITLE
Faction space color overlay

### ISSUE THREAD

**Issue by unjown** [endless-sky/endless-sky#6004]
**Describe the solution you'd like**
add an color overlay in faction space

**Describe alternatives you've considered**
borders only have color

**Additional context**
[IMAGE](https://star-trek-fleet-command.fandom.com/wiki/Faction_Zones)

**Comment by MCOfficer** [comment]
What do you mean by faction space? are you talking about the map?

**Comment by unjown** [comment]
yes map

**Comment by Amazinite** [comment]
We already have the government color mode for systems when you click on the government of the system at the top left of the UI. That is sufficient enough to know which governments have control over which areas.
