### ISSUE TITLE
Add feature: Autopilot / Intercept course key

### ISSUE THREAD

**Issue by 2phunkey4u** [endless-sky/endless-sky#6005]
IIRC, your ship auto-turns when firing its guns on a target, but, unlike in EV:O, there does not yet seem to be a function that lets your ship automatically fly towards a targeted ship.

Edit: I hope it is clear that this is a feature request ("Add a key that make your ship automatically steer towards / chase after a target ship")

**Comment by unjown** [comment]
press F by default

**Comment by 2phunkey4u** [comment]
> 
> 
> press F by default

IIRC, that just sets your fleet on intercept course, but not your own ship.

**Comment by Ornok** [comment]
I wouldn't use a full auto pilot, but the option to automatically aim at your target without firing could be handy. 
By the way, this has been suggested before but never implemented:
#166
#314
#1258
#4339

**Comment by 2phunkey4u** [comment]
@Ornok 
Yes, now that you mention it, this is actually how I remember it from EV:O: holding that key makes your ship turn to point its nose towards the target, so holding that key + holding forward thrust = intercept course. Not a full-on autopilot, but also fine (and true to EV)

**Comment by warp-core** [comment]
#8508 added a control to make your ship turn towards your target.
