### ISSUE TITLE
Swivel guns

### ISSUE THREAD

**Issue by 2phunkey4u** [endless-sky/endless-sky#6006]
Swivel guns were a cool feature in EV:O as a middle ground between fixed guns and turrets. There were front, side, and rear swivel guns, and they each covered a 90-degree field of fire, at the expense of taking more outfit space compared to fixed guns, IIRC.

**Comment by 1010todd** [comment]
#5459 ?

**Comment by tehhowch** [comment]
Duplicate of #3148

The templates are there for a reason. Use them.
