### ISSUE TITLE
"Escort science vessel" mission

### ISSUE THREAD

**Issue by natangold** [endless-sky/endless-sky#601]
…requires you to transport passengers in addition to guarding an NPC? (I'd fix it, but (a) figured it might have been intentional and (b) don't understand GitHub.)

**Comment by brick96** [comment]
But couldn't they just travel on the npc? Or move the equipment to your ship?

**Comment by bobafetthotmail** [comment]
a) it seems to be intentional
b) at the top bar of the file you find a pencil icon, click on it to modify the file, then compile the title and description of proposed modification and submit. If the developer approves, it will be merged and become permanent.

**Comment by natangold** [comment]
Cool beans. Thanks, @bobafetthotmail.
