### ISSUE TITLE
Change to the flight model - Allow strafing, back thrusting...

### ISSUE THREAD

**Issue by montaropdf** [endless-sky/endless-sky#6014]
**Is your feature request related to a problem? Please describe.**
The current flight model is too rigid, as it does requires to turn and use the main thrusters to change direction. This makes combat and avoiding attacks very difficult if not impossible. 

**Related Issue Links**
Has anyone else had this issue or idea? Not to my knowledge. I have to admit that I spend surely too little time browsing and searching for a similar issue. 

**Describe the solution you'd like**
Considering the default keys mapping, the left and right arrow keys would allow strafing, the up arrow key would still allow going forward with the main thrusters and the down arrow key would allow to go backward. The mouse or another set of keys would allow changing the orientation of the ship.  Strafing impulsion should be less powerful than the main thrusters, of course, and so, coming to an alt or changing the main direction using steering should take more times then changing direction and going full throttle with the main thrusters. 

**Describe alternatives you've considered**
/

**Additional context**
The flight model of a game like [Star Sector](https://fractalsoftworks.com/) has been the starting point of this request and should be considered to evaluate the possibility to integrate such flight model into Endless Sky.

**Comment by Ornok** [comment]
"Back thrusting" is already possible by installing reverse thrusters.
Strafing has been requested before in #450, and I think it is currently part of the Combat Revamp (#5772).

**Comment by Zitchas** [comment]
Just to build on what Ornok said, reverse thrust is already in-game. It isn't terribly common, though. 

Right now, there is one Reverse Thrust outfit that you can buy in some places in Republic space, and the Remnant have it built into *all* their thrusters. This latter change, however, was very recent. If you haven't done much with the Remnant in 0.9.13, you wouldn't have seen it.

Combat Revamp does have strafing implemented. It is kind of limited, as we haven't really figured out how to balance it and what numbers are appropriate, nor has the AI been really taught much about it. But it is there, and works.

**Comment by montaropdf** [comment]
> "Back thrusting" is already possible by installing reverse thrusters.
> Strafing has been requested before in #450, and I think it is currently part of the Combat Revamp (#5772).

Thanks for the references, I just read through the issue, and more importantly, the PR, initiated by @Zitchas, and that seems to be a change that go in the right direction.

For my next thought, I will want to share, I will try not to forget PRs and closed issues.

As you have answered this issue, from my POV, I close it.
