### ISSUE TITLE
Amend Command Center outfit description

### ISSUE THREAD

**Issue by 2phunkey4u** [endless-sky/endless-sky#6016]
**Describe the bug**
The descr of the Command Center says: "more may be necessary if the ship has turrets or other systems that require crew." However, I could one ever buy and install a single one on a captured 349 which was carrying turrets (despite sufficient free outfit space). As a result, the ship, when used as a flagship, would show a crew of -6 and move erratically.

**Expected behavior**
[**_obsolete, see below_**] Be able to outfit any many command centers as necessary or have the command center provide more bunks or have turrets have a crew req of 0 when mounted on automata ships.

**Comment by beccabunny** [comment]
You need bunks

**Comment by 2phunkey4u** [comment]
Okay, that's cool, but should be somehow made more explicit in the Command Center descr text.

**Comment by beccabunny** [comment]
It is. "The command center only **provides a single bunk** for the captain, so more *[bunks]* may be necessary if the ship has turrets or other systems that require crew."

**Comment by 2phunkey4u** [comment]
I have trouble getting into the PR thing, so I just post the amended file here:
[korath outfits.txt](https://github.com/endless-sky/endless-sky/files/6559131/korath.outfits.txt)
(line 204)
