### ISSUE TITLE
Can't land on planets anymore

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#602]
Using Steam
Updated to the 8.10 beta
Game crashes when i try to land
Precisely: directly after the ship disappears

Windows 10 64 bit

haven't figured anything out yet, could also be a mistake made by myself

**Comment by lor1113** [comment]
Have you modded the game files in any way?

**Comment by Wrzlprnft** [comment]
Nope, i am not using mods, nor did i mood this particular pilot

**Comment by Wrzlprnft** [comment]
Ok, i can land with my "Test Dummy"

**Comment by Wrzlprnft** [comment]
just for protokoll: duplicated map in the plugin folder caused the problem
