### ISSUE TITLE
Turret Images should move with the ship.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#603]
I propose making turret's a separate sprite from the ship, and giving them the ability rotate with the firing circle itself..For ships that already have a fixed looked..ex. Quarg and there Skylances..Just keep it at 1 frame. Also, give the turrets a dynamic that tells itself to place your Ship's image over or under the projectile sprite, to give the illusion that the Turret is underneath or on top your vessel. Also this would allow players to add guns in more spots with out having it look strange.

Another thing I would like to see implemented is a a way to make turrets change location for animated ships..imagine pieces of a ship that rotate, with turrets mounted to them. The turrets should move with the rotating elements of the ship, so naturally they would need to change position on the ships sprite.

**Comment by Gkramme** [comment]
That would be nice, but think how much lag that would make. It would also be extremley hard to render.

**Comment by endless-sky** [comment]
Closing this to merge with #843.
