### ISSUE TITLE
Can't buy puffin for mission "Remnant: Return the Samples"

### ISSUE THREAD

**Issue by tjrockefeller** [endless-sky/endless-sky#6034]
**Describe the bug**
I was able to purchase a puffin to complete the mission Void Sprites 3. After that mission, I sold the puffin, and now I'm on mission "Remnant: Return the Samples", but I can't buy a puffin from the planet Viminal.

**To Reproduce**
1. Load attached save file
2. Land on Viminal and see that the Puffin is not available to purchase
3. View mission listing and see that Return the Samples is active.

**Expected behavior**
Being able to purchase a puffin on Viminal to complete the mission "Remnant: Return the Samples"

**Screenshots**
Shipyard on Viminal
![image](https://user-images.githubusercontent.com/13140500/120216762-0cc42580-c1fd-11eb-8276-dc32c90a78fa.png)

**System (please complete the following information):**
 - OS: Windows 10 19041.985
 - Game Source: Steam beta
 - Version: 0.9.13

**Link to save file**
[Tim Phlegm.txt](https://github.com/endless-sky/endless-sky/files/6571235/Tim.Phlegm.txt)

**Additional context**
I checked the save file, and it appears that I have all the appropriate events and planet add shipyard statements needed to be able to purchase the puffin, but it's not showing up in the shipyard.

**Comment by tjrockefeller** [comment]
I noticed an "errors.txt" in the app data folder, and the following line appears in the errors.txt file

>Warning: shipyard "Remnant Puffin" is referred to, but has no ships.

[errors.txt](https://github.com/endless-sky/endless-sky/files/6571285/errors.txt)

**Comment by Amazinite** [comment]
It's there for me. Do you have an plugins that could be changing what that shipyard has?
![image](https://user-images.githubusercontent.com/17688683/120217972-f498da00-c1ed-11eb-9cd6-5a2b42970ab9.png)

**Comment by tjrockefeller** [comment]
I don't have any plugins installed. I guess I will try reinstalling?

**Comment by tjrockefeller** [comment]
Well, I'm not sure how this happened, but somehow my install was reverted to the stable release 0.9.12 I'm pretty sure I was playing the beta version 0.9.13, and I had the puffin when playing on that version, but at some point it rolled back to 0.9.12 which may have still referred to the puffin as the gascraft. After updating back to 0.9.13 I can see the Puffin in the shipyard again.
