### ISSUE TITLE
Glitches in success/order of EW missions

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#6037]
**Describe the bug**
Fairly deep into the EW mission, two errors emerged. 
1) The player is to consult with Plume about the void sprites, but there seems to be no way to trigger the completion of the mission, even after taking Plume to Nesqueron.
2) At the time the player is asked to escort Pelicans to fetch Sprites from Nenia, if the player goes instead to the Pantica system (like, say, to reconnect with a fleet), the dialog stating the void sprites have been delivered. 

FYI, The player can still take a puffin-led fleet to Nesqueron, but switch ships to a flagship after landing on the gas giant. (Reported earlier.)

**To Reproduce**
Load the attached save file, go to Aventine. Note the lingering mission for Plume.

**Expected behaviour**
The player should have to collect the void sprites first.

**System (please complete the following information):**
Ubuntu 20.04.2
Nightly build downloaded May 22.
[May DeForce~3017-01-20-outta order.txt](https://github.com/endless-sky/endless-sky/files/6587910/May.DeForce.3017-01-20-outta.order.txt)

**Additional context**

**Comment by MCOfficer** [comment]
#6036 ? Better close one of those.

**Comment by Ornok** [comment]
>     1. The player is to consult with Plume about the void sprites, but there seems to be no way to trigger the completion of the mission, even after taking Plume to Nesqueron.

This has been reported before. It's now fixed, but you'll have to either edit your save file to remove and reset the mission or wait until you complete the entire Cognizance line to get the first part of "Face to Maw". For more info you can check #5990.


>     2. At the time the player is asked to escort Pelicans to fetch Sprites from Nenia, if the player goes instead to the Pantica system (like, say, to reconnect with a fleet), the dialog stating the void sprites have been delivered.

In "Remnant: Cognizance 18" the two "on enter" dialogues assume the player is visiting Nenia first and then Pantica, but nothing  actually enforces it. The simplest solution would be to split the mission in two.
