### ISSUE TITLE
Enemy ships all over the systems

### ISSUE THREAD

**Issue by taivojo** [endless-sky/endless-sky#6049]
**Describe the bug**
On departing a planet, all space is filled with enemy ships and near impossible to fly anywhere; kind of instant death. Some work-around possible if reloading the save and after the 5th or maybe 8th or 10th attempt, the space looks clear. But jumping to another system creates the same issue and mostly gets the fleet killed. I don't think I have had the chance to jump into a system 3 turns away.

**To Reproduce**
Create a fleet of freighters, make some upgrades (engines, cargo space etc). The effect seems to be cumulative, meaning the count of enemies increases with the count of freighters in the fleet.

**Expected behavior**
Maybe expect not to be attacked overwhelmingly?

**System (please complete the following information):**
 - OS: Ubuntu LTS

**Comment by Amazinite** [comment]
That’s the raid mechanic at play. If you have lots of undefended cargo, pirates will come after you.

**Comment by McloughlinGuy** [comment]
@Amazinite an easy fix would be to offer the raid warning mission without requiring people to click the spaceport button, therefor explaining this to them without the need the need to press the spaceport button, which it seems like a lot of people disregard.
