### ISSUE TITLE
standardizing the text files in the data folder

### ISSUE THREAD

**Issue by bobafetthotmail** [endless-sky/endless-sky#605]
I'm slowly learning how the source works, and I had to look at where various things are placed in the datafiles.

Datafiles are a bit messy, and by looking at commit times it's not really improving over time as data gets added on top.
For example, **sales.txt** isn't the main place for that stuff, but only the oldest one while other races have that data in their own .txt, some aliens have their ships in Alien Ships (Quarg/Kroath) and some have their own file that contains everything of that race (Pug/Hai).

Since the game doesn't seem to really care about the datafile names or where data is declared (if I read the source correctly, all stuff is added to a single big database regardless of its text file name), I propose this new .txt file keeping standard:

-race-name- -data-content- -additional stuff-

So that for example ships.txt becomes **human ships.txt** And the "free worlds -something-.txt" becomes **human mission free worlds -something-.txt**

The current content of Hai.txt would get split into 
**hai government.txt** 
**hai ships.txt**

And so on, the same for the content of Alien Outfits and Alien Ships.

Map.txt gets either split into various 

**general map and planets.txt**
**human map and planets.txt**
**hai map and planets.txt**

and so on.

EDIT: I also volunteer to do this.

**Comment by BuildBruh** [comment]
Do it, and send a pull request? (I'd/am  volunteer to help too)

**Comment by bobafetthotmail** [comment]
not a fan of making stuff and getting a "no thanks", I'll wait.

**Comment by BuildBruh** [comment]
Would you be okay with me continuing on this, then? I'd be more than happy to credit you for the idea and if he responds to this issue/request we can split the remaining work?

**Comment by bobafetthotmail** [comment]
yup, feel free to go ahead.

**Comment by BuildBruh** [comment]
Thanks!

**Comment by endless-sky** [comment]
The map file needs to be a single file for the sake of the map editor.

I'm not against renaming other files, but there are many different naming
schemes you could use, so it's quite possible that the scheme you come up
with doesn't make sense to other people, myself included. :)

**Comment by BuildBruh** [comment]
Would catagorizing the map file by species work? 


Any naming system in particular you perfer for making everthing concise?

**Comment by endless-sky** [comment]
If the order of the elements in the map is changed, then every time it is modified in the editor the order will be lost. Besides, sorting the map alphabetically makes just as much sense - maybe more - than sorting it by species.

Here's a table of what the current data files contain:

![table](https://cloud.githubusercontent.com/assets/11450262/12159968/47dd0354-b4b5-11e5-9600-98fc98393e5e.png)

Suppose we say that all interfaces and colors will always be in the interfaces.txt file; all galaxies, systems, and planets for the main galaxy will be in the map.txt file; persons will be in the persons.txt file; trade will be in the commodities.txt file; and the start conditions will always just be in the start.txt file. That simplifies the table a bit, but there are still 14 data types that we need rules for:

![simpler table](https://cloud.githubusercontent.com/assets/11450262/12159929/d98f0e24-b4b4-11e5-94b4-264e021f2738.png)

Right now the data is mostly broken down like this:

* map data (`galaxy`, `system`, `planet`)
* governments (`government`)
  * ship names (`phrase`)
  * friendly and hostile hails (`phrase`)
  * fleets (`fleet`)
* mission data (`conversation`, `mission`, `event`)
* technology
  * sales (`shipyard`, `outfitter`)
  * ships (`ship`, `fleet`)
    * base ships (`ship`)
    * variants (`ship`)
  * outfits (`outfit`)
    * weapons (`outfit`)
    * power (`outfit`)
    * engines (`outfit`)
  * explosions, weapon firing / impact, and engine flares (`effect`)

But, there are some organizational decisions that haven't been made consistently:

* Should government definitions, sales, ship names, hails, and fleet definitions be in a single file, or in the "base" file for each species?
* Should events be in a separate file or with the missions that trigger them?
* Should effects be put in the same file as the outfits that use them, or in a separate "effects" file?
* What should be done with data elements (e.g. basic jobs, and some outfits sold in Hai space) that are shared between multiple species?

Other things are more obvious - like, the "alien" files should definitely be split out into files for each species.

**Comment by BuildBruh** [comment]
No plans for map data due to the map editor as you explained.

Addressing the lower points you made sequentially:

* Currently at a rough base file for each species, haven't finished digging through the fleet definitions or hails. I believe a base file for each species will lead to easier plugin creation, as it can all be modified simply from there and moved. 

* I have events set to be with missions that trigger them, split again between species (Pirates/unfettered are not included.)
  - At a loss with what to do with free worlds, from previous reading through, it would be interesting to say the least to adopt an organizing system similar to below. 

* I would imagine effects/images would remain the same, hadn't thought of moving them as they have a set path in thumbnails and such
.
* Jobs are in a standalone file due to them being in (what i think to be, unsure of c++ still) arrays and having random distance, offer requirements, etc. Outfits are stored in their 'origin' species outfitter files, but otherwise remain the same.

Should all ships be stored in a single file, then split up with comments, perhaps adding notes underneath the copyright on how the file is organized?  
![Example](http://i.imgur.com/nZoj40l.png)
(files related to first point are noted/organized similarly)

Should all the other files be organized in this scheme?

**Comment by bobafetthotmail** [comment]
>"it's quite possible that the scheme you come up with doesn't make sense to other people, myself included. :)"

That's why I'm here asking feedback before doing the change.
In my idea, the more we can split, the better. The files and their names become navigation aids, so that people doesn't have to scroll through files to look for categories they are looking for.
The general idea is "I need to add/edit an X", look at the file names in data folder, double-click, opened the right file.

Splitting data files is more powerful than simply ordering the entries (which still helps but much less), as it allows to jump instantly to the right part of the "file". A bit like bookmarks, or hyperlinks.

>"The map file needs to be a single file for the sake of the map editor. "

I only ask if it is possible to rename that txt to "map and planets.txt" so it's more apparent where planets are at first glance.
Maybe add this as a comment inside it.
"this file is big because the map editor needs this stuff in a single file"

>"Right now the data is mostly broken down like this:"

The same can be kept with the naming convention, while the government (hails, ship names, fleets) is arbitrary and can also be simply split in different files linked by their race, the others are useful.

**-racename- ships.txt** for the ships
**-racename- ship variants.txt** for the variants

**-racename- outfits.txt** for the general outfits
**-racename- outfits power.txt** for the power generators

And so on.

>"Should government definitions, sales, ship names, hails, and fleet definitions be in a single file, or in the "base" file for each species?"

In my idea, that all gets its own txt, the more we can split, the better.

**hai government.txt
hai sales.txt**
and so on with hails and fleets.

>"Should events be in a separate file or with the missions that trigger them?"

With the mission (or group of missions) that triggers them, but this has to be stated in the file name, like for example
**human mission and event free worlds -something-.txt**

events without missions stay in their own file

>"Should effects be put in the same file as the outfits that use them, or in a separate "effects" file?"

Separate file with race name.
for example:
**quarg outfits.txt
quarg effects.txt**

shared effects can go in 

**shared effects.txt**

or if shared by only a few races

**shared effects quarg and hai.txt**

>"What should be done with data elements (e.g. basic jobs, and some outfits sold in Hai space) that are shared between multiple species?"

instead of race name they get "shared" or something like that, so they are all grouped together and not spread between the racial ones.

For example

**shared jobs.txt
shared outfits generic.txt
shared outfits engines.txt**

and so on.

>"Should all ships be stored in a single file, then split up with comments, perhaps adding notes underneath the copyright on how the file is organized?"

If the ships file of a single species (cough)humans(cough) gets too big you can also split that.

A simple example, not advocating to do this (although I wouldn't turn it down either).
**human ships interceptors.txt
human ships light warships.txt
human ships freighters.txt
human ship passenger transports.txt
human ship heavy warship.txt
human ship carrier fighter drones.txt**

>"Jobs are in a standalone file due to them being in"

Nope. If you look inside jobs.txt, all "jobs" are in fact missions with slightly different options and no conversation entries (and a "job" keyword to tell the game to treat it as a job).

Consider that the game was designed from the ground up to be easily expanded with plugins in plain txt files, everything can be split and parsed without it caring that much.

In fact the only issue here is the map editor, not the game.

**Comment by BuildBruh** [comment]
From what I've come to understand from your posts (please forgive if I misinterpret), `~these would be great ideas if files can be accessed within a folder in data~  They can! As of this new finding (kinda disappointed that I just figured that out honestly...)  I can use the naming system you suggested since it is quite a clear-cut name and declutter the main data folder by splitting it up within 

-Human
  -Government
  -Ships

etc.

**Comment by bobafetthotmail** [comment]
Yup. 
Since your account is new, I'm going to suggest you to use the Github's own syncing program (for windows and mac), so you can pull all the files on your PC, do the modifications, then reupload all changes in a single go.

Changing all this with the github web interface would be a nightmare.

**Comment by BuildBruh** [comment]
Thanks for the tip! Btw, do you know what account network GitHub is on? I've noticed over the years that the basic account information, username, picture, and email, is magically available on sites I've never made an account on before (Made about 2 months after BF3 launched, so 'round december and haven't changed the picture yet.)

**Comment by Wrzlprnft** [comment]
You had a hell lot good thoughts there, but i may point out two things:

- Don't want to have like 20 files opened while comparing or modding

-if you have 50 files in the data folder, it will be a kinda mess too

but that's my personal impression

I would keep the existing order, but...
...take all alien outfits and put it into a the outfits.txt and so on and so forth
... or take all the alien races and put it into one race file like in case of the wanderers
At least as a beginning.

Another question you should think about:
http://poll.lab.io/M7Er12TQRHyDLU6cNgPYYw

**Comment by BuildBruh** [comment]
Im currently using race ->ship/outfit/misc and misc are hails, fleets, variants (or should that go with ships?), etc.

**Comment by endless-sky** [comment]
I've done a bit of cleaning up of the files in recent commits (e.g. moving the Korath stuff into separate files). Beyond that, I think it's better for cleanup to be done as needed, rather than preemptively splitting everything into lots of files.
