### ISSUE TITLE
New “Quiet” Ship personality

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#6052]
**Is your feature request related to a problem? Please describe.**
When attempting to creat hails for void sprites, I discovered that they would start sending out hails, which didn’t make much sense.

**Related Issue Links**
I didn’t find any relevant issues.

**Describe the solution you'd like**
I would like a new ship personality which prevents ships from sending out hails, but will display the hail text if you try to talk to them.

**Describe alternatives you've considered**
I haven’t considered any alternatives.

**Additional context**
This could have other uses as well, making it worth including for other people’s projects..

**Comment by beccabunny** [comment]
` mute: this ship will not talk to you if you hail it (and therefore can't assist you, either). (v. 0.9.7) `
https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities

**Comment by beccabunny** [comment]
If a ship can respond to your hails they can send them out too, why should this not be true?

**Comment by McloughlinGuy** [comment]
For something like the void sprite, it wouldn't make sense for it to talk. I made the text be things like "It shudders slightly when you hail it, but does not respond." This hail does not make sense for it to send out.

**Comment by emptytriangle** [comment]
> 
> 
> For something like the void sprite, it wouldn't make sense for it to talk. I made the text be things like "It shudders slightly when you hail it, but does not respond." This hail does not make sense for it to send out.

how would you know it shuddered

**Comment by Terin** [comment]
You've got that preview window when hailing someone/something, not too difficult to imagine it's a real-time preview of what you're targeting, and you could see those movements.

**Comment by trunksbomb** [comment]
> If a ship can respond to your hails they can send them out too, why should this not be true?

IRL when I'm travelling/shopping/etc I'm most likely not going to initiate conversation with someone else (because I don't care to) but I'm not going to straight up ignore someone that says hello.
