### ISSUE TITLE
Typo in help.txt

### ISSUE THREAD

**Issue by Swiftrender** [endless-sky/endless-sky#6054]
Typo in help "lost 7". 

speck of warmth, insignificant compared to the vasty nothingness

lol vasty

**Comment by Amazinite** [comment]
This is intentional. https://github.com/endless-sky/endless-sky/pull/5103#discussion_r429571612

**Comment by Swiftrender** [comment]
shoot, really? doesn't seem to flow well.

**Comment by MCOfficer** [comment]
Wow, i hadn't even considered that possibility. Without knowing the reference, it feels *very* wrong.

That being said, i'm not exactly proficient in shakesperean english.

**Comment by Zireael07** [comment]
Needs a translator comment if it's intentional, otherwise everyone will treat it as a typo (@MCOfficer, you don't have to know Shakespeare's English to go "uhhh, what?")

**Comment by hellminister** [comment]
https://www.merriam-webster.com/dictionary/vasty
https://www.collinsdictionary.com/dictionary/english/vasty

if it is in the merriam-webster dictionary and the collins dictionary, id say the words actually exists and it is not a typo

**Comment by tehhowch** [comment]
Closed by MCOfficer's PR above
