### ISSUE TITLE
Typo in "Korath Family to Ringworld"

### ISSUE THREAD

**Issue by onkel75** [endless-sky/endless-sky#6057]
**Describe the bug**
After you land on the station the translating Quarg says: "I am inclined to acquiesce his request _happyifully_."
I am quite sure that that is misspelled and I have looked it up, confirming my feeling.

**To Reproduce**
1. do the mission
2. see the typo

**Expected behavior**
The word maybe should be "happily"? (Other corrections are welcome, I couldn't find any else)

**Screenshots**
<do I really need this with a typo?>
![20210608180656_1](https://user-images.githubusercontent.com/85624541/121359537-e0fb1b00-c933-11eb-9baa-851941296b77.jpg)

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS  64-bit
 - Game Source: Steam beta
 - Version: 0.9.13 (beta)

**Additional context**
By the way the Quarg say in "First Contact: Kuwaru Efreti" that the two Korath factions are "too evenly matched" though this is obviously not the case and has been adressed quite often.

**Comment by Anarchist2** [comment]
> By the way the Quarg say in "First Contact: Kuwaru Efreti" that the two Korath factions are "too evenly matched" though this is obviously not the case and has been adressed quite often.

...Addressed where?

**Comment by onkel75** [comment]
Oh, right the wiki said that the Quarg talk sort of weird (I forgot that). But I learned English as in that there isn't a "i" directly after a "y" and since "happyifully" has exactly that it felt wrong to me. So I thought i'd report it.

> ...Adressed where?

Oh, uh I didn't say that that good but I meant the Kor Mereti and the Kor Sestor (Yeah, slicers and disruptors...). For example #5566, #4979, #2394, #1046 . I guess you know what I mean.

**Comment by beccabunny** [comment]
> For example #5566, #4979, #2394, #1046

Those don't really prove your point. The first is unrelated to the balance between the two factions; the second talks about the fact that the 512 is too rare; the third has been closed since a lot people disagreed with the issue and the fourth was resolved more than 5 years ago

**Comment by onkel75** [comment]
uh, well the two korath automata factions still feel unbalanced in-game
with the kor mereti definitely having a big advantage over the kor sestor
with their slicer/disruptor combo. The kor sestor just can't keep up with
that amount of damage the two weapons of the mereti can punch out.

Becca Tommaso ***@***.***> schrieb am Sa., 12. Juni 2021,
12:39:

**Comment by W1zrad** [comment]
The "happifully" typo is intentional (I wrote that mission). It's meant to reflect the poor grasp on human language this Quarg has - Quarg in this station have rarely seen/interacted with humans. There's an earlier mission that this is reflected in, but I can't remember it off the top of my head and I'm not at a computer right now. Hope this helps!

**Comment by onkel75** [comment]
Oh ok (whoops), should I close this Issue?

**Comment by onkel75** [comment]
I'll take that as a Yes.
