### ISSUE TITLE
Adding collectible logs to ships.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#606]
I think it would be a nice feature to be able to harvest ship logs from boarded ships, and be able to read them like books. Say you board a specific ship type in an NPC fleet and It give you a randomized captain name and a randomized ship log for that ship..To keep from getting the same log twice set the game to remove that log from the selection once it's collected. This would give the game a story book element and would allow the player to discover secrets in a new way. Some examples of things you could tell the player are the best trade routes, hints on where to go for new campaigns, in game hints to help the player learn the game (for lower tear ships), areas of interest (like wormholes, or Korath space) ect..

**Comment by Wrzlprnft** [comment]
Good idea, but getting a sufficient amount of logs could take a while

**Comment by lor1113** [comment]
Great idea, they could be randomised using the system the game uses for automated hails and the like.

**Comment by Pointedstick** [comment]
This would be awesome! I would volunteer to write a lot of the content.

**Comment by Gkramme** [comment]
There is not a lot of secrets to be discovered at this time, so I suspect there will not be much content that could be added. But, they could be used to give the backstory more flavor.
