### ISSUE TITLE
Navy ships become "friends' while still fighting FW Militia ships

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#6065]
**Describe the bug**
In the FW storyline, shortly after the battle at Rastaban, the player has the option to either keep or return Navy prisoners.

If the player chooses to return the Navy prisoners, an issue emerges: returning to Rastaban, there is a fairly high frequency of Navy ships that port into Rastaban space. Free Worlds militia ships will attack (and be attacked by) the Navy vessels. The Navy vessels do not attack the player, nor provoke an attack from the player's fleet. They show up as blue on the radar display.

If the player boards a Navy vessel disabled at this point, the action treats the Navy vessel as a "friendly" and the Navy vessel is repaired.
Attacking a Navy vessels turns them into enemies as one would expect.

**To Reproduce**
1.The attached savefile - "not my enemy" is primed for the return from Kaus Borealis. Fly to Rastaban. Linger, watch the FW vessels fight Navy vessels. Note that both forces come up as "friendly."

**Expected behavior**
Would expect Navy vessels to be hostile once the player returns to FW space (Much as earlier in the storyline, when going for the diplomatic mission to Earth, then the Navy Base, if the player takes too long, the cease fire ends and the player's ship can be blown to bits.)
 

**System (please complete the following information):**
 NIghtly build from 22 May; Ubuntu

Save-file
[Plodding Along~3016-12-31-not-my-enemy.txt](https://github.com/endless-sky/endless-sky/files/6641436/Plodding.Along.3016-12-31-not-my-enemy.txt)

**Comment by warp-core** [comment]
You are given 1 week (7 days) of safe passage. I don't see why the Navy should give you less safe passage time than was agreed upon just because you can be back in Free Worlds space in one day fewer than that.
