### ISSUE TITLE
Medical facility/sick bay

### ISSUE THREAD

**Issue by unjown** [endless-sky/endless-sky#6066]
**Describe the solution you'd like**

add Medical facility/sick bay
It is kind of weird because ships don't have any medical facility

**Describe alternatives you've considered**
N/A

**Comment by tehhowch** [comment]
And? What would be the purpose of doing so? Just add an outfit to add an outfit?

(You ignored the intent of the issue template, which asks you to think your idea through _before_ posting it to hundreds of people.)

**Comment by yafflehk** [comment]
Patient transport missions, refugee transport, disaster relief missions, medical evac, organ transport (organ running from pirate worlds) - Just a whole bunch of jobs that you can only do with a sick bay. Also it's fun to have a Star trek thing on your ship.

**Comment by unjown** [comment]
> Patient transport missions, refugee transport, disaster relief missions, medical evac, organ transport (organ running from pirate worlds) - Just a whole bunch of jobs that you can only do with a sick bay. Also it's fun to have a Star trek thing on your ship.

yup that was my intention, both for mission and star trek :rofl:

**Comment by guinimesa** [comment]
A sick bay can also affect combat, ship functionality and other things. If you are in combat, your ship got bombed almost til destroyed then your crew should have suffered. Lore-wise it is logic.
Game-wise it could be prerequisite for missions, work as a multiplier for boarding action (however only 1 can be present) or something else.

**Comment by kestrel1110** [comment]
There's a pretty good plugin that implements this.
[I hope I did this link thing right](https://github.com/SirRailOfGun/ES-Red-Cross)

**Comment by Pointedstick** [comment]
It can be assumed that most ships include basic medical facilities. Larger ships might have more elaborate ones. But if you think it would be important to make this a player option to unlock certain missions, then this is one of those things where it probably makes sense to submit a pull request rather than an issue. :)

**Comment by Amazinite** [comment]
Rel: #2908
