### ISSUE TITLE
Map doesn't indicate systems with multiple places to dominate, but not all are dominated

### ISSUE THREAD

**Issue by bassgoonist** [endless-sky/endless-sky#607]
It would be nice to get an indicator that you can still dominate more places in a system.

**Comment by Wrzlprnft** [comment]
I thought if you demand tribute, all planets/stations in a system are affected

**Comment by bassgoonist** [comment]
I dominated Earth, but couldn't land on Luna or Mars, then I dominated Mars, and Luna, separately, but the map showed green as soon as I dominated Earth.

**Comment by Gkramme** [comment]
Yes, I would like this so I can know when I fully dominate a system. Maybe a parially dominated system could have a lighter shade of green, or maybe be purple?

**Comment by brick96** [comment]
Or only a section of the circle become green

**Comment by bassgoonist** [comment]
"Or only a section of the circle become green"

ooh, I like that one, seems really clear. 1/2 and 1/2, or 1/3, 1/3 and 1/3

**Comment by endless-sky** [comment]
Dominating planets is a small enough part of the game that I'd prefer not to add more lines to the legend just to handle it - it's already confusing enough for new players when they see the "dominated" line and wonder what that is. But maybe I could have two different shades of green, one for "entirely dominated" and one for "partly dominated."

**Comment by guillochon** [comment]
If you want to keep it simple, just don't shade a system as "dominated" unless *all* planets in that system are dominated.

**Comment by endless-sky** [comment]
As of commit 224aa7f I've implemented @guillochon's suggestion: a system is not marked as dominated until you have dominated all inhabited planets. But, if you have dominated at least one planet it always shows up as "friendly" so you at least know that there's a port where you can land. Also, planets in the "orbits" sub-map are now colored green to show which ones are dominated.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
