### ISSUE TITLE
Captured fighters don't dock in free escort bays

### ISSUE THREAD

**Issue by sodium70mg** [endless-sky/endless-sky#6074]
**Describe the bug**
Captured fighters and drones don't seem to recognize that a player's escort has available bays if the bays are at least half occupied already. For example, if the player ship has no bays and the player's escort, a Skein, has 3 of its 6 fighter bays occupied, then any fighter ships that are captured won't be able to dock with the Skein in a reasonable amount of time. It looks like the fighter's `AI::Step` function checks to see if a bay is available and if the check fails then the fighter selects a random ship to escort for a while. If the randomly selected ship is the Skein, then the fighter docks as expected. Until that random selection it's possible to order each non-fighter, non-drone escort to hold position at different spaced out locations and watch the captured fighter periodically fly from ship to ship as it selects them at random even though there are free bays in the fleet.

There's still a delay before the fighter docks even when the Skein has all bays free. This seems to be caused by the captured fighter always starting as an escort of the player ship even when the player ship has no bays.

From looking at the code a bit, I think the issue is in Ship.cpp in the `Ship::CanCarry` method. The `free` value is decremented in a loop based on number of escorts matching the bay category but the occupied bays are already accounted for since they aren't free. This causes the docked escorts to be counted twice. I think the countdown in the loop should start with the total number of matching bays for an accurate count.

**To Reproduce**
1. Pilot a ship with no bays but have a ship such as the Skein with half its bays full as an escort
2. Capture a fighter
3. Wait for the fighter's `AI::Step` function to run
4. Watch the fighter select a ship at random to escort instead of the Skein (though it might get lucky)

**Expected behavior**
Fighters and drones should be able to identify escort ships with available bays even when the bays are nearly full.

**Screenshots**
none

**System (please complete the following information):**
 - OS: Linux 5.12.10-arch1-1 SMP PREEMPT x86_64 GNU/Linux
 - Game Source: Steam beta, self-compiled (both)
 - Version: v0.9.13

**Link to save file**
https://gist.github.com/sodium70mg/7d2b8351eec52650a12f506334ee47af#file-fighter-tester-txt

This file has a decent fleet with beam weapons heading into Kor Ak'Mari which is an easy farming spot for Korath Chasers.  There's a skein escort ready to go and 3 barbs parked on the planet that can be un-parked to take up half the bays for demonstration/comparison purposes.

Of course this could be reproduced anywhere as long as the conditions described apply.

**Additional context**
N/A

**Comment by petervdmeer** [comment]
I believe this issue got solved by #6091. Can you check with the latest master if the issue is indeed solved?

**Comment by sodium70mg** [comment]
Ran through some tests with the latest master and it does appear to have solved the issue.

Thanks!
