### ISSUE TITLE
Unusual cargo on Remnant Bounty Korath Raiders

### ISSUE THREAD

**Issue by ECasielles** [endless-sky/endless-sky#6075]
Hi guys,

I've found that Korath Raiders have an unusual amount of items that maybe should not be there when boarding them during the Remnant Bounty mission in the Cinxia system. These are examples of items and amounts found in several tries:
- 11 Outfit Scanner
- 5 Crystal Capacitor
- 1 Forge-class Steering
- 4 Crucible-class Steering
- 53 Cargo scanner

Steps to reproduce:
1. Go to Caelian in the Cinxia system (Remnant).
2. Accept the 'Remnant Bounty' mission.
3. Depart and fight and board the Korath Raider when it comes.
4. Repeat until you see cargo that's not the usual Korath Raider (except for the Broken Jump Drive).

Expected behavior
Maybe there should not be these item in that amount (53 Cargo scanners) on a Korath Raider and in a repeatable mission.
I've only seen this unusual cargo items in this mission so I suspect this could be a bug.

Here's a snapshot of one of these:
![WeirdKorathCargo](https://user-images.githubusercontent.com/11831114/122098765-879e5a80-ce11-11eb-8c73-7f3b3410f14d.PNG)

System:
 - Windows 10 Home, version 20H2 build 19042.1052
 - Game Source: Steam
 - Game Version: 0.9.13

Thanks,
Enrique

**Comment by tehhowch** [comment]
This is expected, as NPCs are able to carry outfits as cargo just like the player. The outfits carried are randomly selected based on the outfitters found in nearby systems. Could the algorithm be improved to provide smarter quantities? Definitely, but that's not a bug (https://github.com/endless-sky/endless-sky/issues/4321#issuecomment-497908088)

There's at least one similar issue around here (or perhaps reported only on Discord).

**Comment by daveeater** [comment]
Moreover... The Korath Raiders have things in their holds that they acquired by... raiding!   It's _necessary_ that, at least some of the time, a Raider that has been disabled and boarded will have some "loot" that it acquired in raiding.  They wouldn't be there, raiding, if they weren't accumulating non-Korath technology.

**Comment by Zitchas** [comment]
Actually, the Korath aren't that interested in rading for technology. They are already more advanced than pretty much anyone else in their area. Their main need is *resources*. 

It is literally implicit that they almost have a trading relationship with the Remnant: They bring outfits and ships, the Remnant provide resources. They just substitute combat in place of haggling over the trade.

Think of it this way: The Remnant seem very successful against the Korath, and yet the Korath keep coming. This implies that either the Korath are stupidly persistant, or they are actually getting something from all this that they value just as much as (if not more so) than the outfits or ships they loose. As the primary author of the Remnant missions, I don't particularly like the idea of the Korath being stupid, and I'm not really fond of the "persistent to the point of being stupid" either. I find it much more interesting to look at it as a form of trade, so this is the direction I will be developing it.

That being said, some way to alter the cargo contents of Korath to skew the contents to be much more heavily stocked with commodities and less with outfits would be good

**Comment by tehhowch** [comment]
@Zitchas Since its introduction, the mechanic has been skewed 80-20 towards commodities when both are viable.

That said, I updated [the fleets wiki](https://github.com/endless-sky/endless-sky/wiki/CreatingFleets#basic-fleet-characteristics) to better highlight the behavior of the game engine.

If 80/20 isn't good enough, you can propose changes to the fleet definitions to better achieve the desired atmosphere.

**Comment by Zitchas** [comment]
Hmmm... Thanks for pointing that out. The trouble is figuring out which way they were coming. If they are Raiders inbound, then they should just have Korath outfitter stuff and no commodities, and probably be fairly empty. If they are raiders outbound, they should have no outfits, and be full to the brim of commodities.

**Comment by ECasielles** [comment]
Wow! Thanks for the answers!
I tend to enjoy more the sandbox side of the game so maybe that's why I thought this was weird. Nevertheless, seeing that it was actually intended and how you make sense of it makes it actually an awesome feature instead of a bug.
I was afraid some variable shifted its id from a resource to an outfit, turning 114 metals into 114 Outfit Scanners.

I'll be closing this issue then.

Thanks,
Enrique
