### ISSUE TITLE
Planets initially refuse tribute, even if you have dominated systems with significantly stronger defense fleets

### ISSUE THREAD

**Issue by bassgoonist** [endless-sky/endless-sky#608]
This would be a nice flavor, a chance for a planet to capitulate after the initial tribute demand, with the chance being higher the more planets you've dominated/the larger the defense fleets you've destroyed.

**Comment by Gkramme** [comment]
That would make the game too easy then. You could dominate Earth, then the rest of the planets would easily bow down to you.

**Comment by bassgoonist** [comment]
I think there should at least be a chance of this, why waste your ships when you know someone can handily destroy them?

**Comment by Gkramme** [comment]
But that chance would be very small, and should be based on the total firepower/ weapon power

**Comment by endless-sky** [comment]
Dominating planets is *supposed* to be time consuming - it's just in there as an end-game option for players who have a huge fleet and want to blow lots of stuff up. So, having planets surrender might make sense from a real world perspective, but from a game play perspective it does not.

**Comment by guillochon** [comment]
I'd actually like to see a way for the player to *lose* systems they've dominated somehow, perhaps by having a small chance of insurrection per day, e.g. "you better visit this system in X days otherwise these rebels will oust your puppet leaders!"

**Comment by lor1113** [comment]
Interesting mechanic - maybe remaining republic planets could send out fleets to reclaim a planet you have dominated ( if it's a republic planet) and you would have to destroy them before they can get to your planet

**Comment by jamaican117** [comment]
I feel that if you conquer a pirate system in say Syndicate space, there should be less pirate fleets and a mission to cooperate with the Syndicate to make it a Syndicate world. Just my take.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
