### ISSUE TITLE
Allow planets with no spaceport to still restrict landing (i.e. to not be uninhabited)

### ISSUE THREAD

**Issue by bassgoonist** [endless-sky/endless-sky#609]
No other landing site has allowed this so far, so I wasn't sure if it was a bug or intended.

**Comment by BuildBruh** [comment]
Iirc because its automated, no? Its in the world desc

**Comment by bassgoonist** [comment]
But they send a defense fleet and pay you a tribute?

**Comment by BuildBruh** [comment]
My thought process was something akin of youre not threatening the planet yourself, but the republic is defending/paying. (From my experiences, it put up a larger fight than surrounding system/worlds

**Comment by johndh** [comment]
Are you sure you're not getting Huginn and Muninn confused?

**Comment by BuildBruh** [comment]
Most likely if you're bring it up...

**Comment by endless-sky** [comment]
If a planet has no spaceport, currently it counts as "uninhabited" and you are always allowed to land there. So really, there's a need for a way for a planet to not have a spaceport and yet to be treated as inhabited - maybe I should use an "uninhabited" attribute instead.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
