### ISSUE TITLE
Escorts shoot to disable rather than kill

### ISSUE THREAD

**Issue by 3t3rn4lfl4m3** [endless-sky/endless-sky#6094]
**Is your feature request related to a problem? Please describe.**
My escorts keep shooting at enemies till they explode rather stopping once they have been disabled.

**Related Issue Links**
I have searched open issues with keywords 'loot' and 'disable'. There might be something I did not consider that should have been obvious.

https://github.com/endless-sky/endless-sky/issues/5494 possibly, but seems to be more about other factions killing off disabled ships. I hunt in systems where only ships are mine and Korath Exiles specifically to avoid bloodthirsty allies.

**Describe the solution you'd like**
My escorts leave disabled ships intact so I can loot for outfits to, well outfit, my ships and sell for money. Possibly an option to make attempting to board an operational ship not change target to a disabled one.

**Describe alternatives you've considered**
I might replace some weapons with less powerful alternatives and specialize some escorts of inferior firepower for looting. I have a fleet of obsolete, parked Shield Beetles I could strip of ion cannons and pulse turrets.

If the problem is projectiles already fired, I might have to do Free Worlds campaign to progress Wanderer campaign to acquire sunbeam turrets as beam weapons allegedly hit instantenously and therefore should not have many projectiles in flight.

**Additional context**
I have seven Kar-Ik-Vot 349 escorts, stripped of missiles but equipped with Korath repeaters and detainers still. Even for Korath Raiders the time differential between disabled and dead is a fraction of a second. After parking four of my Kar-Ik-Vots, I occasionally manage to order my ship to board a Korath Raider so the escorts stop shooting by repeatedly pressing the boarding key, though escorts shooting at the fighters often hit and finish off the mothership. And boarding key changing target ship to random disabled fighter disrupts me often.

**Comment by Anarchist2** [comment]
As you've already suspected, the problem isn't that escorts shoot to kill, it's the fact that they only stop shooting when the target is disabled, ignoring the damage that in-flight projectiles will do to the ship. There's also the problem that escorts won't take disabled ships that may be in the way when shooting.

Searching `escorts destroy` yielded #5245.
