### ISSUE TITLE
Swizzle assignments: Syndicate Extremists and new pirate campaign factions

### ISSUE THREAD

**Issue by Galaucus** [endless-sky/endless-sky#6105]
Now that #5974  is merged, plenty of new swizzle options have been opened up. 

While working on the pirate campaign a few new factions have arisen:
-[Lightspeed Logistics](https://github.com/Endless-Sky-Pirate-Campaign/endless-sky/wiki/lightspeed-logistics), a Syndicate spin-off company that handles roughly half of the commercial shipping in the Core.
-[Core Mineral Concern](https://github.com/Endless-Sky-Pirate-Campaign/endless-sky/wiki/Core-Mining-Concern) (CMC), the mining cartel that claims Gienah.

Swizzle 1 is currently being used by Syndicate Extremists. I feel that the bright fuchsia would be better suited to Lightspeed. It's similar enough to Syndicate purple to imply connection while still having enough contrast to be visually distinct in busy systems. While these are also necessary for the Syndicate Extremists, any player will be spending much more time looking at Lightspeed ships than they will Syndicate Extremists (seeing as the latter only spawn at the end of a campaign.) Therefore, it seems sensible that priority be given to this new merchant faction for a high-contrast swizzle.
![image](https://user-images.githubusercontent.com/68889791/124533655-97351180-ddc7-11eb-9f57-b565e4413509.png)

This will require the reassignment of Syndicate Extremists to another swizzle. I propose either Swizzle 9 (Black)
![image](https://user-images.githubusercontent.com/68889791/124534082-66a1a780-ddc8-11eb-8926-9c6f37f754b8.png)
or Swizzle 24 (Dark Magenta)
![image](https://user-images.githubusercontent.com/68889791/124535666-5c34dd00-ddcb-11eb-995d-b02523c266a4.png)

While my preference is towards Lightspeed having fuchsia as it helps suggest their closeness to the Syndicate, it wouldn't be a dealbreaker to make them, say, cyan and leave the extremists as-is.

**Comment by Galaucus** [comment]
(Unless there are any objections, my intention is assign Swizzle 1 to Lightspeed and Swizzle 9 to Extremists once the new factions are ready to be merged)

**Comment by Pointedstick** [comment]
Let's do this once that content is ready; until then, there is no issue that needs solving. Once there is, it can be solved in the PR that introduces the issue. :)
