### ISSUE TITLE
F/W storyline tweak - crank senator

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#6108]
Mid F/W campaign, the Player is assigned to transport a senator from Mere to Bourne. The cranky senator wants to be on Bourne "in a week" which the player "knows" can't be done, because the trip requires seven days in hyperspace plus a day chewed up in departure/landing.

But if the player has a jump drive, it can be done in six days. 

Teeny issue, but maybe one of you wizards could tweak the script to allow for Jump-drive-equipped outcomes. Not sure what that would be, mind you. 
Can't seem to upload two save files.... but DIY and verify.
[Speedy Smith~3017-05-19-bitchy-senator.txt](https://github.com/endless-sky/endless-sky/files/6787649

**Comment by movingpictures** [comment]
Second save file.

[Speedy Smith~3017-05-25-end-senator.txt](https://github.com/endless-sky/endless-sky/files/6787696/Speedy.Smith.3017-05-25-end-senator.txt)

**Comment by DeciduousBeard** [comment]
I had noticed that also myself. The simplest fix would be to just change the text to say they want to be there in 5 days, which would be impossible in any situation.

**Comment by Ferociousfeind** [comment]
Could also scoot the source a little further away so that it takes at least 7 days even with a JD, so that you can keep the "need to get there in a week" part, because "I need to be there in five days" reeks of "used to be one full week, but we found we could actually do it faster"

**Comment by Amazinite** [comment]
I was planning on making an invisible mission with a 7 day deadline and having the completion conversation for this mission branch based off of whether the deadlined invisible mission is still active or not (i.e. you used a JD or not).

**Comment by Ferociousfeind** [comment]
oh, that's a clever implementation
