### ISSUE TITLE
Minimal working examples of jobs

### ISSUE THREAD

**Issue by DeciduousBeard** [endless-sky/endless-sky#6119]
**Is your feature request related to a problem? Please describe.**
My sons are working on a plugin for ES at present as a homeschool project, under my direction, and have already produced both maps and ships, but are struggling with missions. When I help them I struggle to make working missions myself, let alone teach them how to do it. Every possible feature a mission may include is documented in extreme detail in the wiki, which is a valuable reference document, but too detailed for an introductory resource. And the existing real missions in the game are all complex in one way or another - the simple "job" missions are repeating and auto-generated so contain a lot of automation code, and the "storyline" missions have large conversations and other complexities. It is difficult to discern the essential minimum elements of a mission from these examples. No doubt there are simple examples in the existing missions but it is difficult to find them.

I would like to give my sons minimal working examples, which they could then add complexity to. As it is, we are having to work backwards from the complex to the simple, which is much more difficult for a beginner.

**Describe the solution you'd like**
1) Are there existing minimal working examples of missions in documentation I have missed?
2) If not, could somebody direct me towards specific very simple missions in the existing codebase or plugins, which constitute minimal working examples, that I have failed to notice?
3) Long-term: The addition of a few minimum working examples to[ the wiki page](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions) would be very helpful for people starting work on the project.

For instance, I would like to see the most minimal working examples of:

- The simplest possible "mission" that does almost nothing but is technically complete.
- A cargo transportation mission, one fixed location to another, no automation of locations / quantities / payments.
- A passenger transport mission, one fixed location to another, no automation of locations / quantities / payments.
- A mission triggered by landing (something as stupid as "land on this planet and get given some credits for no reason").
- Spawning a single NPC, for no real reason (there is no other content in the mission).

These simple examples would be pointless themselves, but constitute foundations which could have additional lines added to them based on "real" missions to flesh them out to become useful.

**Describe alternatives you've considered**
I have attempted to write minimal examples myself for teaching purposes, however as this is my own first time writing such missions I am struggling to trim them down without breaking them. After spending several hours at this I thought I had better ask for help here.

**Comment by Terin** [comment]
The thing that helped crack the code for me was realizing this:
```
mission "Name"
    job
```
was a fully functional job. Not a _good_ one, since it has no description, no reward, no cargo or NPCs. You just lift off and land on the same planet again. But from that, you simply add on more things the more detail you want for the job/mission.

Want the job to go to a different destination? Add a `destination` tag. Want it to pay you? Add an `on complete` and a `payment` underneath it. Want to escort someone? Add an `npc accompany`, and look into the syntax needed to fully add the ship.

This was mostly cleaned from editing the game's datafiles itself, and seeing the minimum I could get away with. Being able to search through them all with something like, VS Code helped a lot. But yeah, the wiki documentation is very much a reference manual, not a tutorial. The "basic" syntax for a mission is 91 lines, when it should probably start with an actual basic example.

We can look into improving that (although editing GitHub wikis are a pain), but in the meantime, I'd say run with my advice, and make good use of the missions already in the game.

**Comment by DeciduousBeard** [comment]
Thankyou, that is exactly what I was looking for!

I quickly turned that into this completely cheaty job:
`mission "Give me money"
	job
	repeat
	on complete
		payment 100000`
And an even more ludicrous one that offers to give you money upon landing on any planet:
`mission "Give me money automatically"
	landing
	repeat
	on offer
		dialog `Do you want free money?`
	on complete
		payment 1000000`
I think that's just what the boys will need to get them going. Absolutely brilliant, thankyou.

**Comment by thomasballinger** [comment]
If your sons were to write a blog post about how to create a simple mission as a more introductory resource, I know I'd appreciate it!

**Comment by DeciduousBeard** [comment]
I don't know if they're up to writing something like that yet, but I'll suggest it to them for later!

What we have found most helpful is to inspect the source code for the base game - either just reading it here, or downloading it. Find the code behind a series of missions that you have already done, so know what they do, and read it. Then try and replicate it.

For instance, the Free Worlds introductory missions are in the below file. These are the missions doing pirate reconnaissance for the Southern Defence Pact, transporting a militia officer, the Katya & Mr Eyes missions and some others. These are a series of relatively simple missions that involve simply visiting a planet or transporting a person, they just have interesting text that creates the story.
https://github.com/endless-sky/endless-sky/blob/master/data/human/free%20worlds%20intro.txt

For example, the below mission is really simple. It simply means you have to go from Harmony to Sinter, and will have two passengers to carry. You will receive this mission if you have done the mission "FW Katya 5C", and have not yet "chosen sides", which is an event. The mission will appear in the spaceport by default (as it does not say "landing" or "job"). There is a short conversation in which you have the option of choosing to accept or decline the mission. The conversation makes the mission sound complicated (because it is telling a complex story), but this one mission itself is actually really simple - just go from one place to another place. Finally, in case you land on the destination planet but don't have your passengers (as they were in a second ship in your fleet that has not yet arrived), there is a short notification that will alert you to this.
```
mission "FW Katya 6"
	name "The Hunt Continues"
	description "Take Katya and Eyes to <destination>."
	source "Harmony"
	destination "Sinter"
	passengers 2
	to offer
		has "FW Katya 5C: done"
	to fail
		has "chosen sides"
	on offer
		conversation
			`You find Katya and Mr. Eyes sitting at a table in the corner of a small cafe, talking in hushed voices and examining a galactic map that is spread out in front of them. Several of the nearby systems are circled. Katya says, "Hello again, Captain. We've picked three planets that we think are our best options. It should only take a few weeks to visit all of them. What do you say?"`
			choice
				`	"Sure, I definitely want to help solve this case!"`
				`	"Sorry, I'm through with helping the Free Worlds. I don't think we have a chance of beating the Navy to the punch."`
					decline
			
			`	"Great!" says Katya. "We'll stop on <planet> first, then swing by Hopper and on to New Iceland. If we still haven't found anything by that point, we'll start working our way up the Rim."`
				accept
	on visit
		dialog `You land on <planet>, but you realize that Katya and Mr. Eyes are on one of your escorts that hasn't entered the system yet. Better depart and wait for it to arrive.`
```

**Comment by Pointedstick** [comment]
I've added some examples in https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#intro, which should be helpful.
