### ISSUE TITLE
Starling cloaks in Remnant Keystone testing missions

### ISSUE THREAD

**Issue by Blue42hand** [endless-sky/endless-sky#6126]
**Describe the bug**
The remnant Starling that the player is supposed to scan in the missions Remnant: Keystone Research 5 and 6 cloaks. The mission can only be completed by waiting for an ion storm to break the cloak.

**To Reproduce**
Do the missions.

**Expected behavior**
Starling doesn't cloak to make it easy to scan. Maybe a personality tag? Or a custom ship that doesn't have inbuilt cloaking?

**Screenshots**

WIndows 10 Continuous build via ESL2. Updated 18 July 2021

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

**Comment by UnorderedSigh** [comment]
Fix is here: https://github.com/endless-sky/endless-sky/pull/8874

**Comment by Zitchas** [comment]
I am curious as to what conditions were causing it to cloak in the first place, as I've never seen it do so. Did it get into a fight with a Korath, or get attacked by the player, or something else?
