### ISSUE TITLE
Feature Request: Domination of a planet removes need for License 

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#613]
If I dominate a planet, I am their supreme overlord. If a ship salesman tells me "You're gonna need a license for that" I'm bound to destroy him immediately.

**Comment by BuildBruh** [comment]
It's only for republic planet, and only for republic air (galaxy?) space. Akin to shooting the messenger for bringing a terms of surrender, damn near useless and in the long run, not worth it (bar the last part, because its a game and what not).

**Comment by thenerdfreak** [comment]
I don't quite understand your meaning

**Comment by BuildBruh** [comment]
![picboys](http://i.imgur.com/sBYPsaD.png)
Merchant captains already don't like it, but in the game, it's enforced by the Republic. No matter how many planets you conquer, they still are Republican planets.

Though, becoming your own superpower... that would be an interesting aspect.

**Comment by thenerdfreak** [comment]
No. I mean the Republic Warships and the Wanderer ships

**Comment by BuildBruh** [comment]
Oh! My bad, I interpreted the license you mentioned as the Pilot's License. Not aware of any mods that add a way to buy a Navy/Wanderer license with a bit of story/context thrown in, but editing it into your save file would be the equivalent of looting a R.N.S captain of his license.

**Comment by thenerdfreak** [comment]
You can loot them of their licenses?

**Comment by thenerdfreak** [comment]
Eh idk.. maybe add a feature where you can loot one and get it made to fit you on some pirate world?

**Comment by endless-sky** [comment]
If you're going to dominate a planet, isn't it a lot easier (usually) to just capture a ship of the type you want, instead? None of the ships that you need a license to buy are impossible to capture.

**Comment by thenerdfreak** [comment]
Yes but dominating a planet inexplicable causes a lot less detriment to your reputation than capturing enough ships for a full blown fleet

**Comment by endless-sky** [comment]
Closing this to focus the issues list on feature requests that are more likely to get implemented.
