### ISSUE TITLE
Mac installer missing from 0.9.14

### ISSUE THREAD

**Issue by DeciduousBeard** [endless-sky/endless-sky#6133]
**Describe the bug**
0.9.14 release notes state "AppImage, x86 MacOS, and Windows packages can be downloaded here directly.". However the assets only include AppImage, Windows and Source files, no MacOS file.

MacOS install files are provided for both 0.9.13 and the Continuous build, so this appears to be an accidental omission.

**To Reproduce**
https://github.com/endless-sky/endless-sky/releases

**Expected behavior**
Mac OS installer provided for 0.9.14 as for all other versions.

**Comment by tehhowch** [comment]
Not a bug. Mac OS support is limited to best-effort. When @endless-sky is able to build for macOS, then the 0.9.14 release artifact will be made available.

The same goes for a Steam release of 0.9.14.


If you have Catalina or Big Sur, you can use the artifact created by GitHub.

**Comment by EricFromCanada** [comment]
See #6121.

**Comment by DeciduousBeard** [comment]
No problem, I fully understand the best-effort support. And sorry if this seems a dumb question, I'm just learning the ropes here and am a little bit lost:

> If you have Catalina or Big Sur, you can use the artifact created by GitHub.

Do you mean just use the installer from the latest continuous build (which does have an auto-generated MacOS build in the assets)? Or do you mean there is a way to access a Github-generated build of the stable 0.9.14 release?

Thanks.

**Comment by MCOfficer** [comment]
> > If you have Catalina or Big Sur, you can use the artifact created by GitHub.
> 
> Do you mean just use the installer from the latest continuous build (which does have an auto-generated MacOS build in the assets)? Or do you mean there is a way to access a Github-generated build of the stable 0.9.14 release?
> 
> Thanks.

Both is an option. We build on every commit, and (if on master) publish the artifacts as continuous release. 

The continuous build is public, but the workflows that run on each commit require a github account to download. You can access them like this:

Go to the commit of your choice - for 0.9.14, that's this button
![image](https://user-images.githubusercontent.com/22377202/126768938-ff4d326e-c662-4a6c-9284-67b0f3e1e6a9.png)
...but you can also do this for any other commit you come across, even on most PRs.


Click this checkmark, then any of the "Details" buttons
![image](https://user-images.githubusercontent.com/22377202/126769078-beca5b7f-6468-454f-936c-77d970b56927.png)

You arrive at an overview of all workflows and their jobs that ran for this commit. Click the CD workflow
![image](https://user-images.githubusercontent.com/22377202/126769368-8002be43-36d8-418a-aaf6-770de1af68c7.png)

And find the artifacts towards the bottom of the page

![image](https://user-images.githubusercontent.com/22377202/126769497-8ff7c087-514e-448b-856e-080e31ab166d.png)

**Comment by DeciduousBeard** [comment]
Thankyou for the detailed explanation, that is really helpful. Found it easily.

**Comment by tehhowch** [comment]
Yes, you may thank @EricFromCanada for his work on making our macOS build action produce a result that is portable to non-"latest" macOS versions.
