### ISSUE TITLE
Except for <esc> keyboard randomly goes numb

### ISSUE THREAD

**Issue by tsingi** [endless-sky/endless-sky#6134]
**Describe the bug**
Twice today key events failed to work except for the \<esc\> key.

**To Reproduce**
Happens in the Outfits screen when trying to unload cargo, both times.

**Expected behavior**
key events register

**System (please complete the following information):**
 - OS: Linux pop-os 5.11.0-7620-generic \# 21\~1624379747\~21.04\~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux
 - Compiled from git pull this morning (July 22)

**Additional context**
This is a fairly new System76 Meerkat that I just took out of the box, it isn't very high power, es complains (rightly) about the frame rate.  I have another one that I usually use that is loaded but I'm diagnosing networking issues on it, which is why I'm using this one.
IT COULD BE ME.  But it's very strange and specific behavior that ONLY the \<esc\> key works when this happens.  Also, desktop level events are handled, I can alt-tab out of the game.

**Comment by tsingi** [comment]
Happened a third time.  In Outfitter, trying to unload cargo to storage.  Restart, problem gone.

**Comment by tehhowch** [comment]
Can you share the output of e.g. `./endless-sky -v`?

We use SDL for keyboard handling, so the version in your system may have an issue.

Additionally, your keyboard/handler may not like certain input combinations. For example, my Windows laptop does not respond to trackpad motion while holding Tab.

Finally, do you have a save file and exact ship+outfit selection to repro with? There may be a slow path that your system is choking on.

**Comment by tsingi** [comment]
Version info, compiled a couple days ago...u
Endless Sky ver. 0.9.14
License GPLv3+: GNU GPL version 3 or later: <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Compiled against SDL v2.0.14
Using SDL v2.0.14

tsingi@pop-os:~/pub/dev/endlessSky/endless-sky$ uname -a
Linux pop-os 5.11.0-7620-generic #21~1626191760~21.04~55de9c3-Ubuntu SMP Tue Jul 20 22:18:55 UTC  x86_64 x86_64 x86_64 GNU/Linux

Following your lead, it seems that <ctrl><shift>U is the culprit.

**Comment by gunqqer** [comment]
^U is typically used as unicode input, e.g. <ctrl><shift>u+221E would give ∞. Hitting escape will cancel the input.

**Comment by tsingi** [comment]
∞

Very good sir.  The only time you ever notice unicode is when it is annoying you.
Mystery solved.
