### ISSUE TITLE
Self Distruct Button

### ISSUE THREAD

**Issue by patomation** [endless-sky/endless-sky#6135]
We need a hot key so I can blow up my ship on demand especially when I'm taking on the Unfettered with a ship with only blaster turrets and no guns. I took out the guns to fit bigger engines so I can go faster. Thoughts?

**Comment by MCOfficer** [comment]
Uuh... why? This is basically a "Game Over" button, why not just ESC?

**Comment by patomation** [comment]
Yeah, sorry about not using the issue template. But It would just be satisfying to take out as many pirates as you can before loading the last save.

**Comment by patomation** [comment]
It could take two keys to press, one for the captain and one for the first officer. Then after that you can press enter. You know, what if you don't want your ship to be taken by pirates?

**Comment by Pointedstick** [comment]
Don't think this makes sense, sorry. :)

**Comment by Zitchas** [comment]
The EV/O/N series all had a self-destruct button... And I never understood the reason why. While the slight RP value would be nice, we've got limited keys and lots of potential new commands. I'd rather not clutter up the command set with a command that I really don't want to accidentally hit. (unlike my spaceship, my keyboard's self destruct key won't have a big red warning sign and a switch cover protecting it...)

I agree with closing this.

**Comment by Pointedstick** [comment]
Yeah, I frustratingly blew myself up by mistake in the middle of doing something else more than once in the classic EV games.
