### ISSUE TITLE
Remeberance Day celebration pasenger delivery not dated(/rush)?

### ISSUE THREAD

**Issue by mirror176** [endless-sky/endless-sky#6143]
Got the task: "Brink 5 passengers to New Sahara in the Phecda system by for the Remembrance Day celebration on February 19th. Payment is 100,000 credits."
Should this task be dated/rush? Getting to a site for a scheduled celebration seems like a candidate unless this task gets thrown around any time and/or its thought the passengers didn't care when they would be there for. "Bring Arthur and his Hai friend, Kiru, to Vinci in the Miaplacidus system for a gaming convention" would also seem like the same kind of idea. Had a cotton sheet delivery for same celebration event also not dated while others to Earth for Earth Day celebration were dated/rush.

**Comment by Pointedstick** [comment]
All "Remembrance Day celebration" jobs have the `deadline` tag, so if this was a bug, it's since been fixed.

**Comment by Pointedstick** [comment]
For the Hai mission in question, see https://github.com/endless-sky/endless-sky/pull/6261
