### ISSUE TITLE
Is 'north' a valid direction on the map?

### ISSUE THREAD

**Issue by mirror176** [endless-sky/endless-sky#6144]
**Describe the bug**
Comments from clicking on 'Spaceport' at stops when not receiving a new mission had discussion about checking out a what may be a collapsed wormhole north of Delta Velorem. Which way should 'north' be. Maps on earth often have it as 'up' but in a galaxy that doesn't make sense if not described.

**Expected behavior**
Describe the direction in another way, such as following the spiral arm, movement relative to center of galaxy, or a coordinate such as 'up=north' be defined somewhere.

**Comment by MCOfficer** [comment]
this has been discussed before. #4460

**Comment by Pointedstick** [comment]
Yes, it is. :) The map is 2D, therefore cardinal directions apply. And the map is of our galaxy which is itself a relatively flat disc, so cardinal directions still apply.
