### ISSUE TITLE
Plundered ammunition does not reload launchers

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#615]
If I have a heavy rocket launcher with no rockets, and I plunder a bunch of rockets from a boarded ship, my launcher isn't reloaded--the rockets are put in the cargo bay, where they're useless to me if I happen to be in a fight for my life at that very moment (e.g. because I'm might be flying a Sparrow made of tissue paper and hypothetically trying to protect my escort from some pirate ships and I may have just ran out of rockets before potentially finding some on a pirate ship I theoretically disabled and boarded)!

I understand this is simply the default behavior of "put plundered stuff into the cargo hull" but perhaps ammunition that can be fired from launchers your ship mounts could be an exception.

**Comment by Gkramme** [comment]
The launchers are supposed to be on the outside of the ship, so they can only be loaded on a planet.

**Comment by lor1113** [comment]
Heres a good idea - a 'missile loader' outfit that can load your launcher from missiles in cargo (one needed per launcher). This could also allow you to stock up on extra missiles and store them in cargo, then load them on during battle (this would require limiting the number of missiles you can hold in some way, however)

**Comment by endless-sky** [comment]
In commit b133754 I've made it so that when you are plundering ammunition, you use it to refill your weapons. I have not made it possible to use ammunition from cargo, though, because that would be completely broken, especially if it ever becomes possible to buy something and put it directly into cargo - it would essentially allow you to hold unlimited ammo.

**Comment by Pointedstick** [comment]
Perfect, thanks! I noticed that, too. I was flying a sparrow with a heavy rocket launcher that has 20 rockets in it and about 500 rockets I'd plundered from other ships. it was awful convenient since I could reload my launchers even when outside the parts of space that sell rockets. I like being able to do this, but maybe missile capacity in cargo shouldn't be unlimited.

**Comment by natangold** [comment]
Would it make sense to give cargo-ammo some nominal weight (say, 0.1 tons per rocket)?

**Comment by lor1113** [comment]
yes, that was my idea

**Comment by endless-sky** [comment]
@Pointedstick, that doesn't worry me much because you still have to land and visit an outfitter in order to transfer some of those rockets over into your outfits. So, it's not like you can unload all 500 in one fight.

**Comment by BuildBruh** [comment]
Does this open up the possibility of boarding a friendly ship and resupplying them on the fly?

Could vastly increase the variation of difficulty from Republic fleets that have freighters and rainmakers/missle gunboats working in tandem. Difficulty, in my opinion, that the republic desperately need early-mid game.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
