### ISSUE TITLE
The top speed of the ships is too low.

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#6166]
**Describe the bug**
The top speed of the ships is too low.

**To Reproduce**
1. Create a new pilot.
2. Buy a shuttle.
3. Depart.
4. Stop. (Shift + Down)
5. Forward. (Up)

**Expected behavior**
The shuttle accelerates to the fair speed.

**System (please complete the following information):**
 - OS: Debian GNU/Linux Testing
 - Game Source: Github
 - Version: eaf966527dd0bd03ae2bc00a33909816163a401d

**Additional context**
There is no trouble with b01a7b651b4268b9971e7888b6a65fd277b1eabb.

**Comment by Zitchas** [comment]
This is confirmed present in latest continuous. It does appear that the "fix" to the formula has, indeed, reduced speeds to 1/60th of what they were previously.
https://github.com/endless-sky/endless-sky/pull/5776
