### ISSUE TITLE
Spacediving description can overflow

### ISSUE THREAD

**Issue by Terin** [endless-sky/endless-sky#6179]
![image](https://user-images.githubusercontent.com/4471575/128813573-69dcaa98-f2a4-478d-bb34-cacd0a39e3a4.png)

Need to find a way to cut this down.

**Comment by Amazinite** [comment]
Perhaps shorten the second sentence to simply `They are wearing special equipment to ensure their survival.`, as the exact specifications of their equipment aren't really necessary. (If we want to go more in-depth with what exactly spacediving entails, that should be a spaceport mission.) If more shortening is needed, I'd suggest changing the first sentence to `Head to <destination> with <bunks> skydivers and drop them from the edge of space.`, simply trimming a few words/characters.

**Comment by Terin** [comment]
Looks like those qualifications are to differentiate between `Spacediving professionals` and `Spacediving amateurs`, so you keep an eye out for the riskier party. Might just be worth cutting it down to "professional" and "amateur" in the description itself, though. @petervdmeer ?

**Comment by petervdmeer** [comment]
Thanks for the report and the suggestions; I applied all of Amazinites suggestions in #6181, but the text was still too long after applying those, so I also applied Terins suggestion of just going for professional and amateur as qualifications in the texts.
