### ISSUE TITLE
Request: Move Markeb

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#618]
Any chance we could move Markeb and Mirzam a tiny bit closer together? It'd be neat if a jump drive allowed you cross that gap.

**Comment by Thunderforge** [comment]
I'm not sure that I'm following why they should be closer together. Why would it be neat?

**Comment by DingusShingleton** [comment]
You could save a lot of time by not having to go all the way around, as jump drives can travel between systems that have no hyperspace link between them

**Comment by endless-sky** [comment]
The Deep is supposed to be a "fortress" of sorts, where they could easily choose to wall themselves off from the rest of the galaxy. If there were a plot reason for adding a back entrance to that fortress, it might be worth it, but I'm not sure I'd want to do it just for travel convenience reasons.

**Comment by egilburg** [comment]
@endless-sky but a jump drive isn't known technology so it would make sense that gaining access to it (which you get done in lategame anyways) would allow you to a backdoor they didn't plan for.

**Comment by dplepage** [comment]
@endless-sky Fair enough. In that case can we move them a little bit further apart? Taking six jumps to get between them would be a lot less frustrating if they weren't just a few pixels shy of one-jump range.

**Comment by endless-sky** [comment]
Closing this to focus the issues list on feature requests that are more likely to get implemented.
