### ISSUE TITLE
[Feature] Method of identifying what version of the game one is running

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#6185]
**Is your feature request related to a problem? Please describe.**
When a player mentions having a problem in the game, or something unusual, etc. we generally need to know what version of the game they are running. This typically turns into a game of twenty questions to identify which method of ditribution they used to get it. This is even more confused by the increasingly large number of people using ESL2, for whom determining the version basically comes down to "how long ago did you last hit the update button?" and then having to look down the commit list and pick a guess as to which ones is most likely.

**Related Issue Links**
I know we've had this discussion on discord, but I can't find any discussions on here right now.

**Describe the solution you'd like**
Every time a fresh commit or PR is made to the Endless Sky Master branch, I would like to have some sort of marker embedded in the game. I have two ideas for this:

1) In the credit file, either next to or immediatley underneath the version info, that it also have the commit hash of the latest commit, so it would look like this:

```
Welcome to Endless Sky!
version 0.9.14 (2fd9f88)
```

2) Somewhere in-game, such as on the preference screen on a line outside the settings box (bottom right corner would be my preference, but the exact location doesn't matter too much) there is a single line that states the current version and latest hash:
`version 0.9.14 (2fd9f88)`

That would be the ideal, although I don't know if we can get the latest hash to include in a commit inside that same hash. Sounds kind of like a circular loop. As such, using subversioning would be an excellent substitute, and be much more understandable to regular users. So the above options would look like this:

```
Welcome to Endless Sky!
version 0.9.14.45
```

or `version 0.9.14.45`

The only caveat is that we might need some kind of index as to which subversions equate to which commits, but that's something that can be managed by code herders and creators. The points is to make it easier for those playing the game to give us feedback by enabling them to easily and concisely tell us exactly what version of the game they are playing.

**Example**
Just now, we had a discussion on Discord about what the latest version of Endless Sky is, and it came up (once again) that there is no way to tell the difference between the last stable release (0.9.14 on GitHub) and the latest continuous, which displays the exact same "0.9.14" despite there being significant changes between the two.

**Comment by MCOfficer** [comment]
The continuous build pipeline and thus all commit/PR pipelines already do this:

```Welcome to Endless Sky!

Built: 2021-08-12 18:59 UTC
Last change by tehhowch:
 feat: add a warning when
 collision mask generation fails

This game is open source.
```

The only other source of non-release versions would be self-compiled.

**Comment by Zitchas** [comment]
Where does it display this? I don't see any of this in my copy.

**Comment by MCOfficer** [comment]
> 
> 
> Where does it display this? I don't see any of this in my copy.

It is part of credits.txt, I just checked that with the latest continuous. So it should show up in the main menu.

**Comment by Zitchas** [comment]
Ah, that will be the confusion then. I exclusively use a Github Desktop maintained folder with an executable downloaded from the automated builds, and I've never seen any of this.

**Comment by MCOfficer** [comment]
> 
> 
> Ah, that will be the confusion then. I exclusively use a Github Desktop maintained folder with an executable downloaded from the automated builds, and I've never seen any of this.

I would count that as "wonky setup", something we can't possibly account for. Yours in particular can't even be accounted for by modifying `credits.txt` at compile-time, because you technically never compile.

That being said, I haven't kept a super-close eyes on all your support channels specifically the more... amateur ones such as Discord and Steam. Knowing what you know now, can you reevaluate if this is actually an issue, or if it was merely caused by lack of knowledge?

**Comment by Amazinite** [comment]
The creation date on the exe file as seen in the file manager should tell you when someone’s game was last updated, whether through the launcher or through being self compiled. That date can then be lined up with the commit history to see what version they have. (If they’re playing on a release then this method won’t work, but they should know what version they’re on in that case.)

In any case though, if someone is having an issue then the first course of action should be to–if they aren’t already up to date–update their game (to the latest release if they don’t use versions between releases or to the latest commit if they do) and then try to replicate the issue again, not jump through hoops trying to figure out exactly what commit of the game they’re playing on just to potentially find out that it’s an old issue.

**Comment by Zitchas** [comment]
If I am understanding it correctly, when the scripts build a release on here, they modify the credit file to display the most recent commit they include.

Which raises the question: Why not instead have the script write the same information directly to the credit file, which would result in that information being universal for all installations, including unusual ones like mine? It would also make it easier for people to just look at github and identify immediately whether or not someone is on the latest version.

**Comment by MCOfficer** [comment]
> 
> 
> If I am understanding it correctly, when the scripts build a release on here, they modify the credit file to display the most recent commit they include.
> 
> Which raises the question: Why not instead have the script write the same information directly to the credit file, which would result in that information being universal for all installations, including unusual ones like mine? It would also make it easier for people to just look at github and identify immediately whether or not someone is on the latest version.

Because that means that for every commit we make, we have another automated commit that updates the credits. We have a similar situation over at endless-sky-plugins, where we regenerate our machine-readable files on every commit, and [the git log is a bit of a mess](https://github.com/EndlessSkyCommunity/endless-sky-plugins/commits/master).

**Comment by petervdmeer** [comment]
If this really becomes an issues, then we could also generate a C++ header file during compilation that contains a string with the version number and the latest commit-id during compilation. We would then be able to embed the version-information at compile time by including this header file (and it would work for every compiled instance).
The tricky thing here is that we support multiple build-systems and we don't want to actually use the wrong info there, so all build-systems that we currently support should be able to generate this file if we go in this direction.

We could even compare the version-information in the header file against a data-file which we generate at the same time and warn the user if the data and the compiled version-information does not match.

**Comment by Zitchas** [comment]
Hmmm, I was envisioning something more along the lines of the change to the changelog. Something fairly simple, such a during the merge/commit process one increments the subversion number by one. 

Although as Petervdmeer points out, there's actually the data-version and the executable-version. Having the build process include a visual field (just outside the frame of the preference panel, for instance) that displays the hash of the commit that it was built on would solve most of this. Enough that I'd call it done, anyway.
