### ISSUE TITLE
What is the "blast force" attribute described in the Hazards Wiki?

### ISSUE THREAD

**Issue by quyykk** [endless-sky/endless-sky#6198]
The [Creating Hazards](https://github.com/endless-sky/endless-sky/wiki/CreatingHazards) wiki mentions this:

> `"blast force"`: Causes the damage from this hazard to decline with range from the system center according to the blast force curve as described in [CreatingOutfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits#weapon-attributes).

But searching for `blast force` inside the whole game folder (data/ and source/) results in 0 results. So this attribute is never read by the game. Is it a typo for some other attribute? Or was it removed as a feature?

Also the only curve I can find in Creating Outfits is the `"cooling inefficiency"` curve, but I doubt it is the one the quote refers to.

**Comment by MCOfficer** [comment]
I believe it's referring to the `blast radius` on CreatingOutfits. Ctrl-F for that, and you'll find a curve.

**Comment by quyykk** [comment]
How did I miss this. thanks

**Comment by MCOfficer** [comment]
Can you reopen this, i think the wiki is still ambiguous and should be adjusted.

**Comment by quyykk** [comment]
Good point. Also another thing I noticed, hazards also use the "relative" damage types, but the wiki doesn't mention this.

**Comment by Amazinite** [comment]
Fixed the typo and replaced listing each damage type with just saying "all damage types" so that we don't need to duplicate every new damage type between two wiki pages.
