### ISSUE TITLE
Abandoned worlds act like people live there

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#62]
Take a world like Hope or Terra Incognita for example.  You can talk to these planets and they will say the same thing as others "You are cleared to land" and "Please don't joke about that sort of thing."  You can also, at least on TI, take out a loan at the bank, visit the job board, and hire crew.

**Comment by endless-sky** [comment]
Fixed the hailing in commit d6a36c2, and the bank, job board, and trading in commit bc7f73e.
