### ISSUE TITLE
Unable to board own fleet escort ship with no fuel 

### ISSUE THREAD

**Issue by wolfgang-WY** [endless-sky/endless-sky#6201]
I boarded a pirated dagger during an escort mission. However when escaping to the destination there's no fuel left, so the ship stuck at cardax (no landing spot).

Some community posts stated boarding the ship (my default button is B)to refuel does not work. Whenever the escort ship is focused, pressing b will highlight another defeated pirate ship to be board.

Pretty annoying as it's draining operation cost, before I realized parked mode eliminate crew cost as workaround

**Comment by Amazinite** [comment]
Daggers are fighters and therefore have no fuel capacity and lack a hyperdrive needed to leave the system on their own. What you need to get the Dagger out of the system is a carrier for it to board.

**Comment by wolfgang-WY** [comment]
Thanks for the answer, is it possible to do it early or mid game with other ship as carrier is expensive? (In this game I am playing as merchant trader with hauler as main earning tool, so having a heavy warship sounds abit overkill)

**Comment by Amazinite** [comment]
Small c carrier, not large C Carrier. There are (at least) five medium warships that can carry fighters: the Aerie, Mule, Nest, Roost, and Skein.

**Comment by wolfgang-WY** [comment]
Thanks for the explanation!
