### ISSUE TITLE
Taking off without escorts (that are still in another system) gives too little cargo space/bunk dialog

### ISSUE THREAD

**Issue by neevok-eu** [endless-sky/endless-sky#6202]
**Describe the bug**
When your escorts lag behind and you land only one (ore some) of your ships on a planet and you then take off, you get a dialog that you do not have enough cargo or bunks to complete a mission, 

**To Reproduce**
1. Go to '...'  Last time this happened was with the gas craft landing in the void sprites system.  left the rest of my fleet in remnant space
2. Click on '....' If you have missions exceeding the cargo and bunks space of the gas craft and leave your other ships in another system and land on the gas planets.
3. Scroll down to '....' after takeoff 
4. See error too little cargo/bunks to complete your mission

**Expected behavior**
you landed with the exact same amount of cargo space/bunks that you have on takeoff, the rest of your fleet is and always was n another system. therefore NOTHING changed while on the planet and the error is nonsensical

**Screenshots**

**System (please complete the following information):** windows 7 64bit 
 - OS: [e.g. Windows 10 Pro, version 1803 build 17134.407]
 - Game Source: [e.g. Steam, Steam beta, self-compiled, nightly]
 - Version: [e.g. "0.9.8" or "commit hash cab74fd3"] (If playing a "nightly", the commit hash is the name of the build:  win64-0.9.14

**Link to save file**
[e.g. hastebin.com, direct upload, GitHub Gist]

**Additional context**

I'm pretty sure this problem is not limited to the system I mentioned, but probably occurs in any similar situation

**Comment by quyykk** [comment]
Thanks for the report! This is a known bug (it's even linked as a pinned issue above the issues list) #1624. There's also a bugfix in the works (#5723), so hopefully this will get fixed sooner rather than later. :)
