### ISSUE TITLE
'To spawn' conditions creating what appears to be invisible fighter/drone carriers

### ISSUE THREAD

**Issue by Ember369** [endless-sky/endless-sky#6208]
**Describe the bug**
When creating a mission with npcs with different 'to spawn' conditions, npc ships (with fighter/drone bays) that shouldn't spawn will affect the AI of the correctly spawned npc fighters/drones in an unexpected manner.

**To Reproduce**
(note: this save file requires Omnis, since the Caster ship was used to auto-kill the enemy cruiser)
1. Load the provided save (which should already have the custom mission loaded)
2. Depart New Boston and notice that there is an enemy Cruiser and 4 Combat drones within the system
3. Only destroy the enemy npc Cruiser (turn off auto-fire to keep combat drones alive)
4. Observe the combat drones dock with an invisible ship

**Expected behavior**
Upon the destruction of the enemy Cruiser, the combat drones should continue to attack the player's Caster, rather than retreating to an invisible Carrier which shouldn't have spawned (but is somehow present and invisible).

**Screenshots**
In the gif below, the destruction of the cruiser causes the enemy combat drones to retreat to what appears to be an invisible carrier to dock.
![Invisible Carrier](https://user-images.githubusercontent.com/59035469/130550538-d62ba39f-afbe-4845-a08d-98641e395336.gif)

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Game Source: Self-compiled
 - Version: commit hash 0a16b07

**Link to save file** (requires Omnis)
[Branch Testing.txt](https://github.com/endless-sky/endless-sky/files/7036107/Branch.Testing.txt)

**Additional context**
This save file uses Omnis (for the Caster) and a custom mission, which I've attached below.
(Note: it is not required to replicate the behaviour since the provided save file above already has the mission loaded)
[branch mission.txt](https://github.com/endless-sky/endless-sky/files/7036223/branch.mission.txt)

• This custom mission uses a conversation branch with two choices, each choice updating a different spawning condition.
When conversation choice 1 is selected, only the 1st npc fleet should spawn (a cruiser and 4 combat drones). When choice 2 is selected instead, only the 2nd fleet should spawn (a carrier, 4 lances and 6 combat drones).
• However, when choice 1 is selected, when the cruiser is destroyed, the 4 combat drones appear to dock with the carrier from the 2nd fleet, despite it not being present.
• If all of the ships from the 1st fleet are destroyed before they invisibly dock, the mission is marked as 'completed', which suggests that the ships from the 2nd fleet aren't mission objectives (which is correct). 

Interestingly, when repeating this experiment with the 2nd npc fleet in a different system to the 1st fleet, this weird drone behaviour does not occur.

Vitalchip on Discord has verified that this behaviour occurs for them too, so it is unlikely that this is an error specific to my version of ES.

**Comment by vitalchip** [comment]
What I observed was the 4 drones heading to the same area of space and vanishing after the cruiser was destroyed. As soon as the Cruiser was destroyed they switched parents from "Mission Cruiser" to "Mission Carrier" (ships named by me in mission files) 


<img width="367" alt="drones" src="https://user-images.githubusercontent.com/65342577/130766098-ba278acd-8d83-4af2-be15-6b1e63a4677c.png">

**Comment by Pilcrow182** [comment]
> So at the very least, unspawned ships shouldn't be considered valid ships to reparent to.

Is there not a way to make `to spawn` *remove* the offending ship from "existence" upon failing its spawn condition? Simply removing it from the list of valid parents doesn't address the underlying issue (that this invisible ship "exists" in the system without being spawned, in the first place), and leaving it that way may eventually cause other problems.

**Comment by tehhowch** [comment]
> > So at the very least, unspawned ships shouldn't be considered valid ships to reparent to.
> 
> Is there not a way to make `to spawn` *remove* the offending ship from "existence" upon failing its spawn condition? Simply removing it from the list of valid parents doesn't address the underlying issue (that this invisible ship "exists" in the system without being spawned, in the first place), and leaving it that way may eventually cause other problems.

An NPC that has not passed its `to spawn` may still pass it later...
