### ISSUE TITLE
Allow the use of space as a digit/thousands separator for bank input

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#6213]
### Problem Description

There are various methods around the world for making large numbers more readable. Typically in the US, large numbers are separated by commas every three digits (e.g. `1,000,000`). Other regions make use of a dot (e.g. `1.000.000`), which is mutually exclusive with the use of a commas given that the dot is used as a decimal point in the US. But there exists a third digit separator that is not mutually exclusive with commas or dots and could therefore also be supported: the space (e.g. `1 000 000`). Having a space in your input in the bank causes the bank to ignore everything after the space in your input, though (e.g. `1 000` is read as `1`).

### Related Issue Links

#6172: Allowed the use of commas as a digit separator for user input in the bank. 
#3566: Discussed replacing the existing uses of commas as thousands separators for displayed numbers (e.g. payment) with spaces. My issue only concerns the acceptance of spaces as thousands separators for user input, though.

### Desired Solution

Allow the use of spaces as a digit/thousands separator. For example, accept `1 000k` as `1,000,000`.

### Alternative Approaches

N/A

### Additional Context

Being honest, I'm kinda just opening this issue to test the new template. Looks fancy.

**Comment by Plip-Plop** [comment]
An option to change the separator, like in OpenTTD, could be nice.
