### ISSUE TITLE
Glitch in Typhoon pod?

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#6215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Typhoon pod actually reloads faster than the Typhoon launcher. I noticed this while playing the Aug. 17 nightly build.
In the Outfitter window, the Typhoon Launcher is listed as having 0.5 shots per second, while the pod is listed as haivng a rate of 1.2 shots per second. 

The human weapons file corroborates this observation. 

### Steps to Reproduce

load the save file - main unit is equipped wiht pod. Fire Typhoons. Re-load, change out to Launcher, note slower fire rate.
[Alter Nate.txt](https://github.com/endless-sky/endless-sky/files/7080398/Alter.Nate.txt)

### Expected Behavior

The pod would be slower than the launcher.

### Operating System

Ubuntu 20.04

### Game Source

Built from source

### Game Version

Aug 17 nightly build

**Comment by tehhowch** [comment]
@Zitchas intentional? Or oversight?

**Comment by Zitchas** [comment]
Oversight, I believe. I'm good with pods having *slightly* faster launch rates, as it gives them something they're actually better at. But over twice as fast is definitely not appropriate. I'll post a fix.

**Comment by Zitchas** [comment]
Upon re-examining all the pods, it looks like we went with the idea that pods are all universally equal to the launcher in terms of launching their built-in capacity, but all average out to be slower than the main launcher over the long term when reloading their built-in capacity is taken into account. This reflects poorer mechanical systems for reloading from racks (pods aren't built for large-volume situations). The Typhoon pod just had an incorrect `Reload` value (this is the value that controls how fast it reloads after the burst is done.), the burst value itself was good.

#6219 makes the very minor (2 character) fix required to bring the Typhoon pod inline with where it should be.

**Comment by movingpictures** [comment]
Yay. I feel like I did something useful at last. :)

**Comment by Zitchas** [comment]
Yes, reporting problems, discrepancies, and stuff like that is very much appreciated. I look at the data so much things blur together sometimes.

Thank you!
