### ISSUE TITLE
Carrier description outdated/incorrect?

### ISSUE THREAD

**Issue by BuildBruh** [endless-sky/endless-sky#622]
"The Carrier is more than just a warship: it is practically a mobile space station, with docking bays for an entire squadron of drones and fighters and enough crew to fill a small village. Designed primarily for engaging enemies from a distance, the Carrier is slightly less well shielded than the Republic Cruiser, but it carries just as heavy a load of weaponry."

Carrier has about a 2K buffer on crusier max shield, and regens faster. IIRC generators just change charge speed, so jump, mkII and the heavy variants are all still weaker than the carrier, shield wise.

![comparison carrier](http://i.imgur.com/ky1ph4H.png)

![comparison cruiser](http://i.imgur.com/Qxl1DWP.png)

**Comment by endless-sky** [comment]
Fixed in e3b4217.
