### ISSUE TITLE
--resources flag behavior is confusing on mac (and linux?)

### ISSUE THREAD

**Issue by thomasballinger** [endless-sky/endless-sky#6220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When endless-sky is started with the `--resources /foo/bar` flag on mac, the resource directory used is `/foo/bar/../Resources/` which causes `/foo/bar/../Resources/` and `/foo/bar/../` to be checked for a `credits.txt` file before `/foo/bar/credits.txt` is checked. This is due to resource finding hacks being applied even for flag-specified resources:

https://github.com/endless-sky/endless-sky/blob/be21998143b7577bf8381d34d55f385d01c8d030/source/Files.cpp#L104-L107

I haven't run into this bug but I was confused when reading the code, and it could manifest if a user had a resources directory with a credits.txt as a sibling.

I believe there are similar issues with linux based on the code, but I haven't tested this:

https://github.com/endless-sky/endless-sky/blob/be21998143b7577bf8381d34d55f385d01c8d030/source/Files.cpp#L94-L103

### Steps to Reproduce

```
$ mkdir -p fakeresources/data fakeresources/images fakeresources/sounds
$ touch fakeresources/credits.txt
$ /Users/tomb/Library/Developer/Xcode/DerivedData/EndlessSky-asymldgrudnqsdclwufttpzdiyop/Build/Products/Debug/Endless\ Sky.app/Contents/MacOS/Endless\ Sky --resources fakeresources/
# game launches, using specified (empty) resources

$ touch credits.txt
$ /Users/tomb/Library/Developer/Xcode/DerivedData/EndlessSky-asymldgrudnqsdclwufttpzdiyop/Build/Products/Debug/Endless\ Sky.app/Contents/MacOS/Endless\ Sky --resources fakeresources/
# Unable to find the resource directories! dialog appears
```

### Expected Behavior

the `../Resources` hack is only used when no `--resources asdf` flag is specified

### Operating System

MacOS Big Sur 11.5.1

### Game Source

Built from source

### Game Version

commit SHA be21998143b7577bf8381d34d55f385d01c8d030

**Comment by quyykk** [comment]
Turns out that the hack that is `../Resources/` is not needed at all. #7929 removed it, so this is now fixed.
