### ISSUE TITLE
Dynamically changing sprites

### ISSUE THREAD

**Issue by Hyugat** [endless-sky/endless-sky#6228]
### Problem Description

One thing I noticed about ships in ES is that no matter what, the sprites seem to always stay the same. Docked fighters can't fold up their wings, and battle-damaged ships will always look the same as ones freshly bought from the shipyard. I've looked around the issues page and I've found only similar suggestions (not the exact same), but its possible I missed something since this definitely seems like it would have been brought up by now.

Anyways, I feel that this would allow for more flexibility (particularly in fighter design) and also allow for more immersion when the player sees their ship get laser burns or holes from taking battle damage. Instead of simply being stopped, disabled ships could truly look like they are no longer capable of functioning.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/4991 similar suggestion

### Desired Solution

What I propose is adding support for content creators to define separate sprites for disabled ships, as well as docked fighters, and maybe other states that I can't think of right now. 

### Alternative Approaches

There could also be support for defining separate sprites at different hull %'s. I'm not sure exactly how well this sort of functionality plays with the engine, but it seems like a good change for the future.

### Additional Context

not sure if using the issue template was what I'm supposed to do, I haven't posted on github in quite a while and I seem to have forgotten how things work exactly.

**Comment by Red-57** [comment]
I think that this would be an awesome addition to the game, it would especially help modders who want to go above and beyond with the emersion. I really can't see this being added to every in-game ship sprite though, it would just be too much work at least not any time soon. I would really like to see this. I can already imagine an added fighter image with the wings folded in/up or a damaged falcon with one of the wing things falling off.

**Comment by tehhowch** [comment]
I don't really see a difference between this issue or the linked issue. If there isn't any real distinguishing factors, this should be closed in favor of the other issue, #4997.

**Comment by Pointedstick** [comment]
I agree, it looks like it's asking for essentially the same thing as https://github.com/endless-sky/endless-sky/issues/4991.
