### ISSUE TITLE
Momentary cuts in sound

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#623]
sound will cut for all objects on screen. May be related to engines making sounds now

**Comment by thenerdfreak** [comment]
Update: it doesn't "cut" so to speak, but yet delays. If I pause it directly when the "cut" occurs, I'll get that sound shortly after I pause

**Comment by endless-sky** [comment]
This may just be related to OpenAL having a limit on how many sounds it can play concurrently.

**Comment by endless-sky** [comment]
No one else has reported this, and I can't reproduce it, so I don't think I can do anything about it right now.
