### ISSUE TITLE
Put ramscoop production/scan interference rating in the stats?

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#624]
Currently there is no way to know what your ramscoops are producing (edit: unless you have just one), as each additional scoop produces less. edit:[It would be nice if ramscoop generation was included in the info screen so you could] balance flamethrower/afterburner fuel usage vs your ramscoops without having to resort to trial and error.

On that same note, a little more information on interference plating would be helpful, ie how the stat functions and what effect your current level has on scans.

**Comment by Gkramme** [comment]
I agree, that would be nice.

**Comment by LocalGod79** [comment]
this becomes especially complicated with #914

**Comment by DingusShingleton** [comment]
Does it? The game pauses when you open the info screen, so it can just report what the rate is at the current moment. Or it could give "Nominal rate (current rate)". Is that so complicated?

**Comment by LocalGod79** [comment]
apologies - i was under the impression that this would be a stat at the outfitters (looking back, i had no reason to think otherwise) - your request now makes much more sense.

+1

**Comment by DingusShingleton** [comment]
Ahh, yes, I can see why it was ambiguous. I was so locked into my train of thought, I didn't even think to make it explicit. I'll update it just for posterity
