### ISSUE TITLE
Flamethrower balance

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#625]
My other suggestion reminded me of my thoughts on the flamethrower. Which are that it is really really jacked. Having some peppered in your fleet makes taking over ships almost trivially easy (even the mighty quarg bow before the flamethrower onslaught). I think the weapon is generally ok, save for one thing: firing heat.

The flamethrower generates 120 FH/s, while dealing a whopping 12,000 HD/s. That's 100 HD for every point of FH! The only other weapons that deal HD are the plasma cannon and the newly added sunbeam, which each weigh in at about 2 HD/FH, quite paltry by comparison. Obviously, those weapons have other strengths which make them quite valuable, but I think the comparison stands. I mean, hell, even a single measly energy blaster generates 175 heat/second
 
I recommend increasing the heat generated by the flamethrower by a couple factors, maybe to like 240 or 360, bringing its HD/FH to about 50 or 33, respectively. This is still vastly superior to any other heat weapon, while still keeping it perfectly viable (as it is a relatively compact weapon for what you get).

**FH=Firing heat    ***HD=Heat damage

**Comment by lor1113** [comment]
I think the flamethrower needs it's own fuel bar. After all, all in game lore says that hyperdrives work on nuclear reactions, and you can't just burn enriched uranium or the like. A better idea would be to simply lower it's heat output - It's too damn high!

**Comment by DingusShingleton** [comment]
I actually like how outrageously high it is, but I think there should just be a high cost associated with it. The kind of weapon pirates would love to strap onto a tiny ship and go crazy with

**Comment by lor1113** [comment]
No - there is no excuse for a weapon being able to produce that much heat and not heat you up. I propose increasing fuel consumption and heat generation, while lowering heat damage

**Comment by endless-sky** [comment]
Closing this to focus the issues list on feature requests that are more likely to get implemented.
