### ISSUE TITLE
Documentation: unified location for information on sprites/bodies

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#6255]
### Problem Description

Information on valid children of `sprite`s is currently spread across multiple wiki pages. Sprite information can be found in [creating effects](https://github.com/endless-sky/endless-sky/wiki/CreatingEffects), [creating ships](https://github.com/endless-sky/endless-sky/wiki/CreatingShips), and the weapons section of [creating outfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits#weapon-attributes). On top of that, I don't feel that it's made clear that (almost) any attribute with "sprite" in the name is capable of taking any sprite child. (The one exception I can think of is that a galaxy's sprite can't have children, as what children of sprite actually refer to is the animation capabilities of a Body, but the sprite that a galaxy has is not a Body.) For example, the outfits page describes the sprite for a weapon and below that how the hardpoint sprite can have the same children as the projectile sprite, but further up the page where flare sprites are described, no such mention of children of a sprite are made.

### Related Issue Links

#4511 tracks any missing documentation, but this isn't a matter of missing information, but scattered information.

### Desired Solution

Instead of having information about sprites be scattered across several pages, create a single page on sprites (a name other than "Creating Sprites" would likely be more appropriate; "Sprite Animation" perhaps?) and make it clear in the description of any sprite attribute that it is able to take children as described on this new sprites page, linking to the sprites page for at least the first mention of sprites on the page.

### Alternative Approaches

n/a

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/wiki/SpriteData
You can view the full diff here: https://github.com/warp-core/endless-sky.wiki-clone/commit/1e26ce9ad5c07e41ee7282e49a454003e4f61286
