### ISSUE TITLE
Anti-Tier 4 Ships

### ISSUE THREAD

**Issue by Mark11110** [endless-sky/endless-sky#6256]
### Problem Description

This is an idea for future plots - Maybe Quarg/Pug/Drak campaign? Maybe for a new alien species who wanted to conquer the whole galaxy or maybe the Alphas coming back with vengeance?
How to defeat a tier 4 ship without breaking balance? weapon/shield/armor system that kills tier 4 but are average against ships below tier 4.

### Related Issue Links

n/a

### Desired Solution

Outfit that when comes into range with enemy Tier 4 level ships, temporarily downgrades their stats: shield/damage/shield regen/ hull/repair rate

example:
"shield penalty limit" 80,000 (limits each ship that comes into range to only have 80,000 or lowershielding)
"tier 4 damage limit penalty" 20 (limits each tier 4 ship that comes into range to only give 20 per second total damage)

something like that.

### Alternative Approaches

Alternative 2
Individual outfilts
1. Shields that can only absorb a certain max damage, if it goes above that, it gets negated.
2. Weapon that absorbs and multiplies tier 4 level damage, but acts normally on Tier 3 and below (Quarg Skylance).
3. Outfit that weakens shield and hull above tier 3 rating
4. Outfit that disables hull repair above tier 3 rating
5. Outfit that weakens shield generation above tier 4 rating

Alternative 3
Damage multiplier that only works against certain ship names.

**Comment by Pointedstick** [comment]
Not really within the scope of an issue report, sorry. :) GitHub is used development activities, submitting bugs, and requesting new features, and discussion must be quite focused. I would recommend the Discord for more free-form, speculative discussion topics like this.
