### ISSUE TITLE
Add "Group Jump" setting

### ISSUE THREAD

**Issue by rpolley** [endless-sky/endless-sky#6264]
### Problem Description

I have a fleet with a mix of fast and slow ships, and don't want the fast ships to get ahead of the slow ships. I end up having to hold j every jump, which defeats the purpose of autopilot.

### Related Issue Links

This was brought up in #302 but the discussion there got bogged down in the "formations" feature there.

### Desired Solution

Add an option in the settings menu to make autopilot only jump to a system when all ships in the fleet can make the jump.

### Alternative Approaches

Not sure of any viable alternative approaches here.

**Comment by Amazinite** [comment]
Duplicate of #4124.

**Comment by petervdmeer** [comment]
Fixed by merge of #5686
