### ISSUE TITLE
Star map information panel overlap 

### ISSUE THREAD

**Issue by asl97** [endless-sky/endless-sky#627]
when the screen resolution isn't big enough, some of those panel would overlap like:
![screenshot](https://cloud.githubusercontent.com/assets/4752645/12204839/b623eedc-b671-11e5-91bd-a56b62632b85.png)

if it even smaller (eg, playing in window mode), part of it (mainly the commodity prices) end up being partly off-screen.

____
it's unplayable at the [minimum supported screen resoution](https://github.com/endless-sky/endless-sky/blob/f77acb85ced1daf620fba2a5785dbe3f4c546d62/source/main.cpp#L112) (lol)
![screenshot_2016-01-09_01-46-24](https://cloud.githubusercontent.com/assets/4752645/12205007/db06dd76-b672-11e5-8143-4164393f7d0c.png)

**Comment by endless-sky** [comment]
I'm not sure if this is worth changing - the UI works well for the monitor resolutions that most people have, and resolutions only keep increasing year after year. And, it's not like this makes the game unplayable.

**Comment by asl97** [comment]
how is this a question, this is a bug report about overlapping UI.

1366 x 768 is still fairly widely use

http://www.w3schools.com/browsers/browsers_display.asp

**Comment by BuildBruh** [comment]
It could strongly be argued that having it scale with the resolution (detected, perhaps?) would be beneficial for plugins that are rather ambitious in their design, which could require reworking of the souce and end up having to download/build the game again.

**Comment by asl97** [comment]
@BuildBruh scaling would be hard, this game seem to use pixel pos and scaling would mess that up.

**Comment by asl97** [comment]
this post will merge into last comment, posting this to bump/notify @endless-sky 

@endless-sky the code change is simple enough, the texture/image is the hard part.

it use alpha for the color change and i suck at using alpha so i wouldn't be posting my edited image since i highly doubt it be use.

```diff
diff --git a/images/ui/map key.png b/images/ui/map key.png
index 8d7d95d..c9473bd 100644
Binary files a/images/ui/map key.png and b/images/ui/map key.png differ
diff --git a/images/ui/map trade.png b/images/ui/map trade.png
index 91f5ed1..e1cfa97 100644
Binary files a/images/ui/map trade.png and b/images/ui/map trade.png differ
diff --git a/source/MapDetailPanel.cpp b/source/MapDetailPanel.cpp
index 06af8b7..a7efc88 100644
--- a/source/MapDetailPanel.cpp
+++ b/source/MapDetailPanel.cpp
@@ -240,13 +240,13 @@ void MapDetailPanel::DoFind(const string &text)
 void MapDetailPanel::DrawKey() const
 {
 	const Sprite *back = SpriteSet::Get("ui/map key");
-	SpriteShader::Draw(back, Screen::BottomLeft() + .5 * Point(back->Width(), -back->Height()));
+	SpriteShader::Draw(back, Screen::BottomLeft() + .5 * Point(back->Width()+320, -back->Height()));
 	
 	Color bright(.6, .6);
 	Color dim(.3, .3);
 	const Font &font = FontSet::Get(14);
 	
-	Point pos(Screen::Left() + 10., Screen::Bottom() - 7. * 20. + 5.);
+	Point pos(Screen::Left() + 200., Screen::Bottom() - 7. * 20. + 5.);
 	Point headerOff(-5., -.5 * font.Height());
 	Point textOff(10., -.5 * font.Height());
 	
@@ -430,13 +430,12 @@ void MapDetailPanel::DrawInfo() const
 			}
 	}
 	
-	uiPoint.Y() += 45.;
-	tradeY = uiPoint.Y() - 95.;
-	
 	// Trade sprite goes from 310 to 540.
 	const Sprite *tradeSprite = SpriteSet::Get("ui/map trade");
+	uiPoint.Y() = Screen::Bottom() + .5 * -tradeSprite->Height();
 	SpriteShader::Draw(tradeSprite, uiPoint);
 	
+	tradeY = uiPoint.Y() - 95;
 	uiPoint.X() -= 90.;
 	uiPoint.Y() -= 97.;
 	for(const Trade::Commodity &commodity : GameData::Commodities())
```
![screenshot_2016-01-09_05-50-42](https://cloud.githubusercontent.com/assets/4752645/12210441/f56ea82a-b694-11e5-84ba-64d99ed96dcf.png)
note: map key.png is expanded to 180x180.

**Comment by omagasohe** [comment]
@asl97 @endless-sky The map isn't friendly to laptops or older monitors. My 17" laptops recommended resolution is 1366 x 768 everything. I generally play windowed, and on my 15"  4:3 secondary monitor it's resolution is 1280x1040. 

Just because new stuff comes out doesn't mean every one buys them, My main monitor I've had since 2008, my secondary was from a thrift store for like $10 that i bought to hook up to an old mac mini that didn't support anything but 4:3, it's more than likely older than my main. Both work well for what I need.  

That being said, I call this low priority, it's playable but ugly. I'll take that over pretty and broke any day.

**Comment by asl97** [comment]
@omagasohe and how is it broken?

**Comment by asl97** [comment]
@endless-sky it been 2 days already and this is obviously not phrase as a question nor is it even a question :|

can you remove that label or change it to ether
unlikely (because you don't like my texture and nobody care enough to make another decent texture) or
wontfix (cause you don't care about 1366x768 users)?

**Comment by Thunderforge** [comment]
@endless-sky 
> I'm not sure if this is worth changing - the UI works well for the monitor resolutions that most people have

According to the W3 statistics that @asl97 presented, 1366x768 is the most commonly used resolution with 33% of marketshare as of January 2015. I see it a lot as a native resolution for laptops and low budget LCD screens. In other words, this *is* the monitor resolution that most people have.

**Comment by db47h** [comment]
Some visually impaired people run the game on a 1920x1080 screen with UI zoom enabled. The resulting "virtual" resolution is 1280x720, so if you ask me, that would be a good minimum resolution ;-)
