### ISSUE TITLE
New Mission Keyword, quiet

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#6272]
### Problem Description

I have been writing a lot of missions that do not need to be saved in the pilot file.  They are things that are never going to be referenced later.

### Related Issue Links

None.

### Desired Solution

Add a "quiet" or "unrecorded" mission keyword that will tell the game to not save "Mission Name:offered/active/done/etc".  It will still need to record conditions set.

### Alternative Approaches

It does work to put clear statements for the missions in the various on blocks, but its messy.

**Comment by tehhowch** [comment]
Those conditions are exactly how the game knows it offered that mission already. Without them, the mission will be eligible to offer again.
