### ISSUE TITLE
Deadline auto-calculation can silently return absurd results

### ISSUE THREAD

**Issue by waterhouse** [endless-sky/endless-sky#6281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As discussed in #6261 and #6280:

Recently, the Hiding in Plain Sight mission was changed to have a deadline, calculated automatically with the bare "deadline" keyword. The calculation depends on the DistanceMap::Days() function, which, unfortunately, will return -1 if it fails to find a route, which, per Amazinite's comment in #6261, will always happen when the route crosses a wormhole, which it does for this mission. The calculation then happily plugs in the -1, yielding a deadline of -2 days in the future (i.e. 2 days in the past).

#6280 will fix the problem for that specific mission, but this probably won't be the only time that someone makes a "deadline" mission that needs to go through a wormhole or jump-drive path.  In fact, it's *not* the only time: see the "Steps to Reproduce" section, there are some Hai<->human missions that specify "deadline 24" and hit the same "distance.Days() returns -1" problem.  Luckily, in those missions, 24 gets added to the negative number (seems you get 24 + -4 = 20), making them "tighter than intended" but not "impossible".

It would be nice to protect against future occurrences (and possibly other present occurrences!) of this misfortune somehow.

### Steps to Reproduce

I had added a dumb printf illustrating the issue:
```
	if(deadlineBase || deadlineMultiplier) {
		result.deadline = player.GetDate() + deadlineBase + deadlineMultiplier * jumps;
		printf("deadlineBase %d deadlineMultiplier %d jumps %d\n", deadlineBase, deadlineMultiplier, jumps);
	}
```
Then, when I used the attached savefile and triggered the Hiding in Plain Sight mission, it showed this:
```
deadlineBase 24 deadlineMultiplier 0 jumps -2
deadlineBase 0 deadlineMultiplier 2 jumps 4
deadlineBase 0 deadlineMultiplier 2 jumps 4
deadlineBase 0 deadlineMultiplier 2 jumps -1
```
The #6280 PR will fix the fourth line.  But the first line looks like it comes from one of these missions:
```
> rg 'deadline 24|^mission' data/hai/hai\ jobs.txt | grep -B1 deadline
mission "Hai Retrieve Human Luxury Goods"
	deadline 24
--
mission "Hai Retrieve Human Food"
	deadline 24
--
mission "Hai Retrieve Human Electronics"
	deadline 24
```
I dunno which one.  (A better printf would include the name.  But all three missions behave the same, anyway.)

### Expected Behavior

I'm not sure if there are any great and easy solutions.  I'll list the approaches that come to mind:

1. Make distance.Days() handle wormholes, so it doesn't return -1 at all.
1a. Or at least the always-usable Hai wormhole.
2. Print warnings when Mission::Instantiate() calls distance.Days() and gets -1, so we at least see error messages and expect someone to fix them.
2a. Ideally cause continuous integration tests to fail if this happens, although I don't know if this depends on the galaxy's state.  I dunno, maybe it's reasonable to do tests on the initial galaxy state, and declare "I want a variable-deadline mission on some systems that aren't initially connected" to be a rare enough use case that we just punt on it, telling writers to manually specify deadlines.
3. For missions that get past any warnings, or where there's a straight path in the initial galaxy but not in a modified galaxy (e.g. during the FW campaign when a bunch of systems are cut off?), perhaps kludge Mission::Instantiate() to use a default deadline of 30 days if distance.Days() returns -1.

### Link to save file

[Miles Edgeworth copy previous.txt](https://github.com/endless-sky/endless-sky/files/7275375/Miles.Edgeworth.copy.previous.txt)

### Operating System

Mac OS Catalina, 10.15.7 (19H15)

### Game Source

Built from source

### Game Version

3cfedcd99151d0ac80efa73cc701ddf970c86a28

**Comment by waterhouse** [comment]
Actually, regarding those 3 missions: They do require going there and back, so for some combinations of Hai and human system, 20 days might _be_ impossible without a jump drive.  (E.g. Io Mann -> Alnitak is 8 days, so that's 16 round trip plus landing, barely enough.)  I never bother with those missions... If the deadline were calculated properly, you'd get more like 60 days; then I suppose you could stack several of them (perhaps that was the original intent), which could make them worthwhile.

**Comment by warp-core** [comment]
Has anyone done any work on this?

**Comment by a-random-lemurian** [comment]
https://github.com/endless-sky/endless-sky/files/8747019/Wormholes-Break-Payments.zip

By the way, here's a sample plugin demonstrating the problem. Adds wormhole in Sol system leading to "Glitchy Payments" with a planet offering a mission to Vega.

**Comment by Zitchas** [comment]
I run into this all the time when I have missions in the Ember Waste that I want to make deadlines, but either have to do so manually or just skip having deadlines. 

One thought on implementation: Any deadline calculation should prioritize the straight-flight-via-HD date calculation over wormholes or JD unless these latter are *required*.

For example, if you have a rush job going from Ingot to Wayfarer, it should calculate the payment based on the 12 HD jumps between the two, and ignore the fact that you might be able to do it in 4 if you have a key stone and a Jump Drive. 

Remembering the experience with EVN and the hypergate network, having jobs pay (and deadline based on) regular HD routes; but being able to shortcut them via the hypergates, made me feel special and made me appreciate the value in having gained access to the hypergates. It would have really cheapened the feeling if they'd started paying for long routes that I could do quickly via hypergate like, well, short route deliveries, because I could do them quickly.

**Comment by tehhowch** [comment]
#1918 and #3163 seem quite relevant.

**Comment by warp-core** [comment]
@Zitchas do you think it'd be better for it to automatically calculate the deadline using wormholes and jump drives if no hyperjump route is found or would you prefer to specify to use them if no hyperjump route is found?
Would you like to be able to specify to consider wormmholes or a jump drive immediately, without checking if a hyperjump route is possible?
