### ISSUE TITLE
Option to switch secondary weapons to sequential fire

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#629]
If I have a Vanguard with seven torpedo launchers, firing seven torpedoes at once can be huge overkill if I'm targeting a small ship. I'd much rather fire them one at a time. Against larger targets, this presents no real penalty vs anti-missile fire since the larger munitions like torpedoes are pretty durable against them. This crops up in smaller ships, too. I'd much rather my Hawk with two Heavy Rocket Launchers fire them sequentially so I can keep up a higher rate of fire.

**Comment by thenerdfreak** [comment]
To switch them to sequential fire, yes, but to make them permanently so, no. It would underpower every missile besides Torpedo and variations of it

**Comment by Pointedstick** [comment]
Yes, like I said, an *option.* A switch. A setting you can change.

**Comment by thenerdfreak** [comment]
I agree, once you get more than three, smaller ships get ko'd pretty quick. Maybe also a feature to make main weapons fire at the same time :p

**Comment by LocalGod79** [comment]
(done) with "stream"/"cluster"

**Comment by lehgogh** [comment]
I think he's referring to a setting in the settings/ship info panel, not for the entire weapon.

**Comment by LocalGod79** [comment]
so there's going to be a user toggle to switch between "stream" and "cluster" for each turret mount and gun port on each ship in the user's fleet?

**Comment by lehgogh** [comment]
@LocalGod79 If you don't want it, you don't need to use it. We should still add it for those who do.

**Comment by LocalGod79** [comment]
i wasn't suggesting that it not be added - just expressing my preference (as others have)

**Comment by Pointedstick** [comment]
What's wrong with this idea?

**Comment by LocalGod79** [comment]
my last point.

**Comment by endless-sky** [comment]
As weapons have evolved, pulse vs. stream mode is actually an important characteristic of the weapon - for example, that Repeaters all fire in a clump. So, it makes more sense to me for that to be an immutable weapon characteristic and not something the user can change to get a different effect than was intended.
