### ISSUE TITLE
Display more information about factions and reputations

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#630]
I had the idea today when watching someone code HTML (It was an unrelated idea, random even) that maybe we can, once we've discovered it through the plot or random encounters, have a chart of which factions dislike which other factions and which factions are allies in game. something like

Pirates: Enemies: Republic, Merchant, Syndicate, Pug, Korath, Free Worlds, Oathkeepers, Deep, Neutral
 Allies: none

Republic: Enemies: Pirate, Korath, (Free Worlds/ Syndicate depending on storyline time period)
Allies: (Free Worlds/Syndicate ^ same situation) Deep, Neutral, 

etc..

Also, something to the effect of a list that tells you your standing with them besides just the map icons like

Pirate: Terrible
Republic: Neutral
Syndicate: Neutral
Free Worlds: Great
Pug: Terrible
Korath: Terrible
Wanderer: Friendly
Hai: Friendly

**Comment by Thunderforge** [comment]
I like the idea, but perhaps it could be better implemented in prose form with a "faction summary" that gets unlocked when you make first contact. E.g.

"The pirates are evil and <blah blah blah>. Regardless of their differences, every faction is united in their belief that they are a scourge that should be killed without mercy."

"The Republic governs many of the first planets humanity colonized <blah blah blah>. Recent tensions have resulted in them being hostile towards the Free Worlds."

This expresses what you are looking for while also providing a concise summary of the factions, which is helpful to those who are picking up the game after a long stint.

**Comment by thenerdfreak** [comment]
No, because I'm actually (legitimately might I add) friendly with pirates on my save. and that doesn't reflect the actual relationships in game, just how it "used to be"

**Comment by Thunderforge** [comment]
Are you wanting this to display a faction's relationship to other factions or your relationship to other factions? My "faction summary" idea would show the former. Regardless of how much the pirates like you, everybody else hates the pirates, which is what the description would display.

**Comment by tehhowch** [comment]
@endless-sky the recently implemented "Special Logs" would be a place to display this inter-faction attitude data, and could be programmatically generated based on the magnitude of the `attitude toward`
0 / absent - not shown
(-0.05, 0) "This faction disapproves of this other faction"
> -.05 "This faction appreciates any help given in opposing this other faction"
etc.

To prevent discovering data about a faction before you have discovered it, the faction relationship would require that you have made contact with both sides of the relationship
