### ISSUE TITLE
[Bug report] Can't buy from outfitter map key

### ISSUE THREAD

**Issue by mdziczkowski** [endless-sky/endless-sky#6307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the outskirt system in the game is there a following issue:

Aven if having enough credits and enough storage in the ship, I'm oftenly unable to buy several things.

This happen also after I edit the "outskirt.txt" file and set the cost to 0

### Steps to Reproduce

1. After landing on a planet, enter the "Job offers" => "Outskirt"
2. Try to buy (for example): "Local map"

### Expected Behavior

Beeing able any time to buy anything from the "Outskirt" when having enough credits and storage

### Operating System

Debian 10 (64-bit)

### Game Source

GitHub Releases

### Game Version

0.9.14

**Comment by Terin** [comment]
Your screen resolution is too small in that case, I think the minimum supported is 1280x720. That covered up button is "Abort", which you can still click if you need to, though.

Not sure what the second screenshot is for. That's the catalog, if you click on that "Local Map" item, it'll show you every system where it is sold (which should be pretty much every system with an outfitter).

**Comment by mdziczkowski** [comment]
about the first screenshoot: if you click it then it will expand ;-)

About the second one: the catalog has this issue that I'm unable to buy (among other) the map

**Comment by Terin** [comment]
> Outfits (and ships) are to be bought from the outfitter (and shipyard), not the map.

> the map is meant to be a handy catalog, but not the actual place you buy things.

You don't buy it there.

**Comment by mdziczkowski** [comment]
Strange. On some planets I could buy there too... strange

**Comment by ixPost** [comment]
> 

When buoyed the Local Map adds too your map more data about the surrounding star systems such as how to get there from where you buoyed it and 12 of the surrounding star systems.

**Comment by ixPost** [comment]
> > 
> 

In other words you must come to a nearby outfitter of that star system too get data about it.

**Comment by Zireael07** [comment]
@mdziczkowski: I fail to see how you see anything "intended" in this behavior, you were told you don't buy things in this menu.
