### ISSUE TITLE
[Feature request] Allow free things

### ISSUE THREAD

**Issue by mdziczkowski** [endless-sky/endless-sky#6308]
### Problem Description

I would like to request that the game would allow that some things could be given for free, for example by:

- removing the "cost" line
- setting the "cost" value to 0 or "free"

### Related Issue Links

n/a

### Desired Solution

As in the "problem description"

### Alternative Approaches

n/a

**Comment by mdziczkowski** [comment]
I tryed that, by setting the cost of 0 for a item called "Local map" and the buying (or getting it) possibility was somehow not  there

**Comment by warp-core** [comment]
Can we see what you've changed? Have you checked the errors file? (I think it should be near your save files.)
Have you tried removing the entry for cost altogether?
