### ISSUE TITLE
"start frame" don't work with lasers.

### ISSUE THREAD

**Issue by 1010todd** [endless-sky/endless-sky#6318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If laser have "start frame" only the frame specified for "start frame" will be used, no animation will play.

### Steps to Reproduce

Install the plugin below, buy the weapon and fire it.

### Expected Behavior

Laser animation works.

### Screenshots

Middle laser don't have "start frame". The two at the side does.
(Video)
https://user-images.githubusercontent.com/19187937/139857446-16fd0244-6822-4c73-ad7a-6be4972236d9.mp4

### Link to save file

Plugin for testing. The weapon is available at "Basic Outfits" "Common Outfits" and "developer" (for AES Omnis Plugin)
"AA Test Lance SF" have "start frame"
[beam.zip](https://github.com/endless-sky/endless-sky/files/7461128/beam.zip)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

d5258c8

**Comment by vitalchip** [comment]
Lasers are a single frame, you've specified which frame you want to start.. so it starts (and ends) on that same frame. Your requested start frame gets actioned every time the weapon fires.

**Comment by 1010todd** [comment]
Then how will you get a burst-fire laser to start at an exact frame everytime? I want a laser that fades out but also not fade in, to me this isn't doable right now. From purely non-code perspective, animations can already be stopped with "frame rate" 0, having "start frame" do the same thing..? Why? It's counter-intuitive, at least for me as non-programmer.

**Comment by vitalchip** [comment]
This case is an artifact of a 1 frame projectile. If the projectile had a longer life then it would start at the frame you specified and would continue through the animation from that point, to the end of the animation or the end of it's life. Each new projectile would start on the same image. With lasers the projectile is at end of life and the next frame starts again at the 'start frame'  The only reason a laser looks like it's an animated beam is if the images are left in step with the engine, then the next projectile displays whatever step it corresponds to.

It's not that start frame is broken, just that it's not 'compatible' with a single frame lifetime. For (your needs it would have to do something like hook back to the hardpoint and check if it fired on the previous frame, if so ( and so this is a continuous fire scenario ) then use start frame + 1 as the next frame. If not ( so this is the first projectile of a burst ) then use start frame. Something like that.

**Comment by Amazinite** [comment]
> I want a laser that fades out but also not fade in, to me this isn't doable right now.

Are you looking for something akin to how the Dragonflame works? That effect is achieved using a firing effect as opposed to a projectile sprite.
