### ISSUE TITLE
Revert Deep/Remnant break commit

### ISSUE THREAD

**Issue by Terin** [endless-sky/endless-sky#6331]
### Problem Description

Commit 7686991 was originally intended as a solution to PR #6191. However, I found it to be an unneeded change, preferring PR #6304 to resolving the original issue, and Zitchas has no opinion on it one way or the other. Additionally, that commit has caused an issue blocking the Deep Surveillance missions from the Remnant to trigger, breaking that mission chain, on top of it breaking the flow of those missions at the time.

### Related Issue Links

#6191, #6304

### Desired Solution

Revert commit 7686991.

### Alternative Approaches

Change the `to offer` conditions of Remnant: Deep Surveillance to appropriately look for what end point @Amazinite wants in the Deep/Remnant missions. I _suspect_ reaching the break point (which is the new Deep: Remnant Research) would be that condition, but it's no longer the definitive end point it was before, so I can't say for sure.

**Comment by dragonmaus** [comment]
The above commit is intended to be a minimum viable fix; if it is appropriate and desired (and correct!), I'll open a pull request later.

**Comment by Amazinite** [comment]
> Commit 7686991 was originally intended as a solution to PR #6191.

No it wasn’t.

**Comment by Terin** [comment]
Got it. In that case, when is Deep Surveillance supposed to take place after? As soon as you hit the break point, or when you see it through (if you can)?

**Comment by Amazinite** [comment]
I think the break point makes sense (so the check for the mission being done should switch to offered), but then it seems like the scenario where you bring Remnant tech to the Deep and *then* tell the Remnant would be very rare (as you must necessarily visit the Remnant worlds to grab the tech that the Deep are asking for, which is also how you’d trigger the Remnant: Deep Surveillance conversation), although that might not necessarily be a bad thing. 

I mentioned to Zitchas that I’ll take a look at it later, likely by the end of the week.

**Comment by Terin** [comment]
Yeah, sounds good. You still have the major branching point beforehand of revealing the Remnant or not, just the more specific cases later on that might become less common.
