### ISSUE TITLE
Geminus

### ISSUE THREAD

**Issue by kevinx231** [endless-sky/endless-sky#634]
I find it really strange that Geminus still has the shipyard destroyed after that one event throughout the entire game when it was clearly stated later in the game that the shipyard got or is mostly rebuilt nearby the old one.

**Comment by LocalGod79** [comment]
@endless-sky 
would this event only trigger if the reconciliation thread is followed (delayed after it's mentioned), or would the event to trigger at the end of the free worlds story regardless of the player's arc choice?

**Comment by endless-sky** [comment]
Fixed in 8c0c3bb.
