### ISSUE TITLE
Unfettered Jump Drive 4

### ISSUE THREAD

**Issue by kevinx231** [endless-sky/endless-sky#635]
Is the unfettered jump drive 4 mission a one off thing or is it suppose to be that you can continue selling jump drives to the unfettered? Because right now after selling the fourth jump drive to the unfettered the mission is no longer available and you can't continue selling jump drives to them.

**Comment by endless-sky** [comment]
Fixed in 7f5f14a.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
