### ISSUE TITLE
Bounty hunters prove to be unavoidable. 

### ISSUE THREAD

**Issue by Chopliver19** [endless-sky/endless-sky#6369]
### Problem Description

Right now I am working on the Militia storyline, but somehow I have a bounty on my head! I am now at Longjump with two weeks to get to Earth and back ( for my mission). But I can't leave this system without dying at the hands of those stinkin' bounty hunters (there's a lot of them). Can't fight them (as I am outnumbered), can't run away from them (they are way faster than me), can't bribe them ( can't get enough money to), and frankly, can't do anything about them!

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/5812

### Desired Solution

I suggest what that other issue suggests, that the Militia/Navy would aid you against bounty hunters. This is funny because I am an officer of the Militia, and I am just watching my fellow captains not even notice I am dying!

### Alternative Approaches

Of course, an alternative solution could be removing bounty hunters from the game completely as there are a lot of problems because of them, this definitely isn't the best solution, and is not desired.

**Comment by Amazinite** [comment]
What version of the game are you on? As of v0.9.13, bounty hunters don't spawn during the campaign. If somehow they have spawned, you can cause them to despawn by killing just one of the bounty hunter ships and then landing or by greatly increasing or decreasing your fleet's armament deterrence; greatly decreasing it is the simpler option and can easily be done by parking all the ships in your fleet, or if you only have a flagship then you can put all your weapons into storage or buy a much smaller ship and park your flagship. Bounty hunters can also be bribed, giving you space to finish the mission before dealing with them.

**Comment by Chopliver19** [comment]
v0.9.12...

**Comment by Chopliver19** [comment]
That might explain why

**Comment by Chopliver19** [comment]
I am also probably the most noobyist player ever, so I only have one other ship that's not even on the same side of the battlefront as me...

**Comment by Chopliver19** [comment]
Is 0.9.13 available for Ubuntu?

**Comment by Chopliver19** [comment]
Or Flatpak?

**Comment by quyykk** [comment]
Look at the Github releases link on the main page (it's on the right). You'll be able to download the latest version, which is 0.9.14 (so even newer yay). Here's a direct link if you're having trouble finding it: https://github.com/endless-sky/endless-sky/releases/tag/v0.9.14

**Comment by Chopliver19** [comment]
Thank you so much! Also, how do I exactly contribute to this game? I think I could be useful in story-telling, plot-making, and what-not.

**Comment by quyykk** [comment]
See the "Contributing" section on the main page. We generally suggest joining the community Discord since issues aren't really supposed to be used for help/questions like we did here. :)

**Comment by Chopliver19** [comment]
Wait, which de I download all the assets?

**Comment by quyykk** [comment]
No, only the one you want/need. In your case since you're on Ubuntu, you want the AppImage one.

**Comment by Chopliver19** [comment]
K, thanks this has been very helpful!
