### ISSUE TITLE
"Sell all" button in trade view sells plundered outfits even if the planet has no outfitter

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#637]
If you have a bunch of plundered outfits in your cargo hold and you land on a planet with no outfitter and go to the trade center, clicking the "Sell all" button sells all your plundered outfits, even though there is no outfitter who would presumably purchase them.

Is this intentional?

**Comment by thenerdfreak** [comment]
Shhhhhhhh.

**Comment by bobafetthotmail** [comment]
It's annoying tho. I sold my first damn jump drive by mistake that way. And I didn't do the free worlds plot, so it came from a %&$&£ Kroath Raider.

**Comment by endless-sky** [comment]
Yes, it's intentional. The reason is that it's really frustrating if you have plunder you want to unload, but need to find a system with an outfitter just to sell it. (Originally I required you to track down a system with an outfitter, but people complained about that.)

**Comment by Pointedstick** [comment]
Ok, just thought I'd ask.
