### ISSUE TITLE
[Content] Fuel pod options

### ISSUE THREAD

**Issue by Taejang** [endless-sky/endless-sky#6388]
### Request Description

Just two ideas for additional fuel pod options.

Pressurized Fuel Pod
- Holds 100 fuel
- 5 tons of mass and outfit space
- Uses energy (to maintain pressure and pump the fuel out)
- Sold in Wanderer space

"True to their name, Wanderers sometimes wander great distances from home. Occasionally this involves traveling through systems where even their improved ramscoops are ineffective. These pods compress and store fuel at high pressure, enabling the pod itself to be much smaller than normal. However, they do require energy to run the fail-safes necessary for what would otherwise be a risky idea and to moderate the flow of fuel from high- to low-pressure when it needs to be used."

External Fuel Pod
- Holds 100 fuel
- 8 tons of mass, 0 outfit tons
- Increases drag
- Reduces max hull
- Cannot be plundered
- Sold in human space (by only one outfitter)

"In the old days of exploration, scout ships needed to travel great distances without refueling. Most of the outfits that enabled this have gone out of use, but <company> has found a niche market that still demands this capability: stealth ships. Such ships are often too small for large internal fuel pods and may need to operate far from a star where ramscoops are most effective. This external fuel pod allows them to go longer without refueling, provided that the speed of travel and hull durability are not major considerations.

Almost all of these sold go to Navy Intelligence vessels, but a few merchant captains find it easier to complete time-sensitive cargo runs with fewer refueling stops, and <company> is only too willing to sell external pods to anyone who wants them."

### Why do we need more fuel options?

For game purposes, these would primarily be for ships using outfits that consume fuel, such as afterburners or cloaks. They would also be handy for ships equipped with scram or jump drives, and as the description says, they may be useful for cargo runs across long distances or when time is an issue.

**Comment by yafflehk** [comment]
It might be fun for the external fuel pod to be a single use item. Make it very cheap and give the option to dump it to get the drag back if you need to escape.

**Comment by Taejang** [comment]
That would be neat. It would be a feature request though, not simple content. Any other outfits you can think of that would justify the effort in adding the feature?

It could be useful for external missile racks, and the fuel pods. I can't think of other use cases.

**Comment by yafflehk** [comment]
I was thinking about WWII fighters using drop tanks to extend their range. The tanks would be dropped as soon as combat started to get back speed and maneuverability. I don't know about other single use gear, Napoleonic warships would jettison everything including guns and water to escape pirates or other enemies...

**Comment by Taejang** [comment]
Created a [PR for this](https://github.com/endless-sky/endless-sky/pull/6395). Needs thumbnails for both outfits.

Also needs review for the "hull" and "drag" properties of the external fuel pod; I'm not sure if I used them correctly.

The option to jettison the external pod is _not_ part of this PR, and requires a [feature request](https://github.com/endless-sky/endless-sky/issues/6396).

**Comment by petervdmeer** [comment]
Closing ticket based on feedback in the associated PR. (Keeping human space simple, and other races nearby not radically different.)
