### ISSUE TITLE
The most powerful Wanderer engine is cheaper than their own missiles.

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#639]
A wanderer thunderhead missile is worth 1800 credits.
A wanderer type 4 radiant steering system is worth 1.1 million credits.
A wander type 4 radiant thruster system is worth 1370 credits.
Definitely a bug.

**Comment by thenerdfreak** [comment]
yeah it's missing 3 0's

**Comment by thenerdfreak** [comment]
But it's fixed in the site's Code so it's already been noticed

**Comment by endless-sky** [comment]
Fixed in b1c4547.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
