### ISSUE TITLE
[enhancement] Automatic Anti-Fighter weapons

### ISSUE THREAD

**Issue by Taejang** [endless-sky/endless-sky#6391]
### Request Description

In EVN, point defense-style weapons automatically fired on missiles _and fighters_ that got too close. In ES, we have anti-missile point defense only. I'd like to expand the anti-fighter options so big ships can fire the "big guns" on "big targets" while fighters are dealt with using automatic defenses.

### Desired Solution

Rather than allow all anti-missile systems to fire on fighters, I'd like to see a separate weapon property/flag implemented: anti-fighter. Some weapon systems may have both properties and attack both missiles and fighters within engagement range, while others may only be capable of targeting one or the other.

This has multiple benefits.

1. Diversification of outfit options. Players can pick up dedicated anti-fighter weapons if they choose, or a hybrid point defense system that can handle both but isn't necessarily great at either, or a dedicated anti-missile system. Or, with enough outfit space, a mix of all!
2. Target priority. Right now, a massive warship either ignores fighters swarming it, hopes to hit them in the crossfire, or has to turn its entire weapon compliment on something 1/20th its size while ignoring greater threats. This would allow a ship like a Cruiser to fire at enemy warships while still defending itself from small craft, which makes a lot of sense thematically, and definitely fits the "rule of cool".
3. Fighter survivability. Right now, fighters get smashed by everything. This would incentivize players/AI to target large ships and let their anti-fighter weapons slowly whittle down harassing enemy craft. Combined with [this idea](https://github.com/endless-sky/endless-sky/issues/6390), fighters wouldn't get slaughtered immediately.

### Additional Thoughts

This would take some significant effort to implement correctly. All existing anti-missile weapon systems would need to be re-evaluated within the new context. Some would need to get the new "anti-fighter" property, while others would not. Descriptions would need to be adjusted across the board.

Then new anti-fighter outfits would need to be added, including all the balancing work necessary.

A decision has to be made regarding how missiles are treated. On the one hand, the existing system could remain- missiles can be treated as their own thing, with hybrid point defense systems carrying both an "anti-missile" variable that controls how well they damage enemy missiles, along with regular damage types that would only apply to fighters.

Conversely, the separation of missiles into their own category could be reworked, making missiles have properties more similar to other flying objects. This is how EVN handled it, if I'm not mistaken. It would simplify some parts of the game code.

That said, I think I would favor leaving missiles alone. Their implementation works just fine, and I don't see a significant benefit in altering it. If anything, letting an outfit do different things to missiles vs fighters is neat, and leaving the anti-missile portion simplistic isn't bad in my mind.

### Mentions

Mentioned [here](https://github.com/endless-sky/endless-sky/issues/6383).
Similar to [this](https://github.com/endless-sky/endless-sky/issues/2979).

**Comment by movingpictures** [comment]
I like this idea. Alternately, certain higher-class systems (thinking the Remnant point defense systems) might be tweaked to do both. I suspect the programmer wonks would be able to add an "anti-fighter" attribute to these systems.

Here's a thought: which would be prioritized - missile or fighters?

**Comment by Hector-of-the-Void** [comment]
Currently it should be possible to build combination weapons affecting both missles and foes. I don't know how the targeting is done, could be worth testing.

**Comment by Zireael07** [comment]
I saw two similar issues marked as duplicate, but duplicate of what?

**Comment by Amazinite** [comment]
#2979
