### ISSUE TITLE
[enhancement] Removable outfit pods

### ISSUE THREAD

**Issue by Taejang** [endless-sky/endless-sky#6396]
### Feature Request Summary

External, removable pods affixed to the outside of a ship creates new possibilities in ship design and combat. A warship could bring extra missiles with it, firing a heavy opening salvo before dumping the empty pods to regain speed and maneuverability. Fighters/drones can be carried externally on ships without hangars (likely without the ability to repair them without landing planet-side). External fuel tanks can be jettisoned after the fuel is consumed by a power-hungry afterburner, cloak, or other outfit. Outfits can be installed directly on the hull without using outfit space, at the cost of increased mass, drag, possible cooling inefficiencies, reduced hull protection, etc.

Discussion of the merits of external fighter bays, fuel tanks, etc are only partially on topic here. This is for the functionality of external, removable-mid-flight outfits, not the specifics of what those outfits might do or whether one outfit or another is good/bad/ugly. Just the capability to make this work in general.

### Related Links

[Mentioned here](https://github.com/endless-sky/endless-sky/issues/6388).

### Desired Implementation

An outfit property "external" that can be applied to such things as external fuel pods, external missile pods, etc.

A "jettison external pods" functionality, complete with key binding, a graphical element (likely similar to jettisoned cargo), possibly a dialog menu to select which pods to jettison.

These "external" outfits will need various balancing considerations (reducing hull strength, introducing heat inefficiencies, perhaps requiring turret mounts to install, etc). That will be up to the outfits themselves though, not the underlying functionality- unless a graphical consideration is needed, such as the jettison action originating at the turret where the external outfit is installed at.

**Comment by Red-57** [comment]
These basically already exist with outfit expansions. you trade cargo space for outfit space with cooling inefficiencies. gaining extra outfit space for free is very overpowered with some of the things that you could gain from that.

**Comment by Taejang** [comment]
> These basically already exist with outfit expansions. you trade cargo space for outfit space with cooling inefficiencies. gaining extra outfit space for free is very overpowered with some of the things that you could gain from that.

Agreed, there have to be drawbacks. All the pods would increase both drag and mass, for starters. I'm thinking we'd have to limit the number a ship could have- a good way to do that is consuming a turret mount per outfit pod.

Missile pods would obviously be an explosive advantage (pun intended), but a short-lived one. One shot and you're done. Missiles aren't good at disabling ships, either, so it'd be difficult to just blow away a huge warship and capture it with a smaller ship, even if you did somehow have the crew to do so.

External fuel pods should reduce hull strength as a means to suggest a stray hit explodes the fuel. This would limit it to merchant craft- no combat craft wants to hurt their hull values, reduce their acceleration, max speed, and turn speed, _and_ lose a turret slot just to get extra fuel. A heavy cargo hauler though? One who is already doing cargo expansions to carry more? That's a use case the external pods fit in.

The biggest drawback I can see isn't an actual drawback, but a design choice. Not just anything can go in the external pods- only outfits designated as "external" are allowed. So it isn't pure outfit space like an outfit expansion. Limiting what can go there means better balance control. For example, no EMP torpedo pods if we don't want them. No nukes, or no bunk rooms, or whatever else we might decide is balance-breaking.

An example for missiles: probably javelins would have an external pod, but not Shard Fabricators (which require connections to a ship's internals), nor Heavy Rockets and Finishers (both too large to effectively mount enough missiles to matter into an external pod). Various lore reasons can be used to explain why one outfit or another doesn't have an external version.

All of that said, I emphasize that I agree, free outfit space cannot be a thing. This would require balancing.

**Comment by Zitchas** [comment]
Worth noting that we *already* have missile pods, torpedo pods, heavy rocket pods, etc. (pretty much every projectile in human space)

**Comment by VonZorch** [comment]
External pods should have their own, low, hull score which is taken before the ships hull and landing does not repair it.  When the pods hull reaches 0 it is destroyed.

**Comment by petervdmeer** [comment]
I'm going to close this issue:
- The capability of mid-flight removable outfits already exists for weapons; ammo outfits get used up during flight (and one of our weapons is it's own ammo; it gets used up once it launches itself).
- Such ammo outfits can also have a huge mass, cooling inefficiencies, generate electricity (some of our current ammunition does this), reduce hull strength, or do any other thing that outfits can do, so it is well possible to have those ammo outfits cause all kinds of nastiness until they are launched.
- Such ammo outfits could also store fuel, effectively resulting in an "jettisonable fuel pod". (But only players would currently know how to use it. The AI only knows when and how to fire a weapon.)
- I feel that jettisonable fuel pods together with fuel generation is not a great combination.
- We also have ships that carry fighters externally, but that is "by ship design". I feel we want to keep fighter bays explicit (and not add them through some sort of generic pod).
- We already have `"outfit space"`, `"weapons space"` and `"engine space"` to balance the outfitting of ships. If a new category "external space" would add something to the game, then we can just add it already.

Please feel free to (re)open an issue if you are creating an outfit that would be really be great in the game, but some support is missing.
