### ISSUE TITLE
Questionable grammar in Wayfarer description

### ISSUE THREAD

**Issue by a-random-lemurian** [endless-sky/endless-sky#6397]
### Problem Description

Description of Wayfarer in `map.txt` has questionable grammar.

```
The Tarazed corporation [...]
```

### Related Issue Links

*None*

### Desired Solution

```
The Tarazed corporation [...]
```

can become

```
The Tarazed Corporation [...]
```

### Alternative Approaches

- Reword the whole sentence

**Comment by a-random-lemurian** [comment]
I have filed a PR at #6401 containing my changes

**Comment by Zitchas** [comment]
The question is: is it referring to Tarazed, which happens to be a corporation, or is corporation part of their name? If the latter, then your pr is correct. If the former, then lower case is correct. Personally, I prefer *not* having it as part of their name.

**Comment by a-random-lemurian** [comment]
> The question is: is it referring to Tarazed, which happens to be a corporation, or is corporation part of their name? If the latter, then your pr is correct. If the former, then lower case is correct. Personally, I prefer _not_ having it as part of their name.
> 
> For an alternate phrasing, which should it be?
> 
>     1. The corporation known as Tarazed.
> 
>     2. The Tarazed Corporation.
> 
> 
> (I'm just differentiating between the two, I'm not suggesting that the description needs to be rephrased to either one of these.)

This is more of an issue of consistency.

Mentions of `Tarazed` as `Tarazed Corporation`:
![image](https://user-images.githubusercontent.com/74448738/145719178-240242d4-20f0-499f-a361-eca929f17d67.png)

**Comment by a-random-lemurian** [comment]
I'm closing this as #6401 has been merged.
