### ISSUE TITLE
Ships that cannot jump away should fight to the death

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#640]
Was shooting a Korath World ship with Particle Cannons and Quad Blaster turrets, as soon as its shields ran completely out, it jetted backwards and literally went too fast to catch up to with atomic thrusters, and has been going and going ever since, all while still pointed directly at me

**Comment by thenerdfreak** [comment]
Found the issue. When a ship without a jumpdrive is in an isolated system with no hyperlinks, It basically gives up on life as soon as its shields go down

**Comment by thenerdfreak** [comment]
Propose pull request #646 to fix this

**Comment by endless-sky** [comment]
The AI issue is fixed in commit 63ef05e: ships will now continue to fight if they have nowhere to flee to.

**Comment by thenerdfreak** [comment]
This should also fix fighters, so two birds in one stone!

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
