### ISSUE TITLE
Republic warship license? What Republic warship license?

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#641]
<img width="251" alt="screen shot 2016-01-08 at 7 07 23 pm" src="https://cloud.githubusercontent.com/assets/1097249/12213725/1bffd86a-b63b-11e5-82ac-3aef6bfe3aff.png">

This should probably say something else until there's such a thing as a Republic warship license.

**Comment by luiges90** [comment]
Ya when I first look at this I thought I cannot buy this ship :sweat_smile:

**Comment by endless-sky** [comment]
Fixed in ddfcb9b. In much earlier versions, there were a bunch of licenses you had to buy to own various classes of ships, but I took them out because they just made things annoying.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
