### ISSUE TITLE
Convertable/Convertible

### ISSUE THREAD

**Issue by Gopherslol** [endless-sky/endless-sky#6417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Apologies if this has already been reported. I am on 0.9.14. I came across a ship saying "I bumped into a convertable car around Earth. Unbelievable what people sent into space back then"
Unless it is a regional spelling that I am unfamiliar with, this should probably be "convertible" rather than "convertable"

### Steps to Reproduce

1. Wait (unless there is a way of triggering ship radio dialogue

### Expected Behavior

Spelling should be convertible, rather than convertable

### Screenshots

Spelling should be changed to convertible

### Operating System

Solus

### Game Source

Other (please describe)

### Game Version

v0.9.14

### Additional Information

Running latest version in Solus repos

**Comment by Gopherslol** [comment]
Just decided to poke around the repo to see if I could just do it myself. It seems that this may already have been done based on line 1672 of data/human/hails.txt. If someone who is more familiar with the inner workings of the game wants to confirm, this can probably be closed

**Comment by MCOfficer** [comment]
Good find, twice. This was indeed fixed in #6354

**Comment by Chopliver19** [comment]
Ha, I saw that dialogue but I didn't catch the error!
