### ISSUE TITLE
Katya/Katerina Name consistency

### ISSUE THREAD

**Issue by Gopherslol** [endless-sky/endless-sky#6418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are a few spots in the FW missions where Katya and Katerina seem to be used interchangeably. As far as I can tell, they refer to the same person. Is this intentional?

### Steps to Reproduce

1. Start FW secret cargo mission
2. Passenger refers to Katya as Katerina

### Expected Behavior

Replacement of Katerina with Katya

### Operating System

Solus

### Game Source

Other (please describe)

### Game Version

0.9.14 from Solus repo

**Comment by Amazinite** [comment]
Katerina is her full first name while Katya is a shortened nickname that she mostly goes by. Similarly to how Jean-Jacques goes by JJ.
