### ISSUE TITLE
There's 2 hads in lines 1468 of Freeworlds reconciliation 

### ISSUE THREAD

**Issue by Drl-Omniar** [endless-sky/endless-sky#6436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

see issue title above

### Steps to Reproduce

play the Freeworlds campaign Reconciliation and go to the deep after talking with the parliament after acquiring the jumpdrive and talking to the pug

### Expected Behavior

none

### Screenshots

![Endless Sky 12_25_2021 9_22_11 AM](https://user-images.githubusercontent.com/43642799/147388234-7dd82896-2b40-477d-88f8-71fa3beadacc.png)

### Operating System

seems to be an oversight, but windows 10

### Game Source

ESLauncher2

### Game Version

Nightly - ES launcher

**Comment by MCOfficer** [comment]
Pretty sure this is correct past-perfect. 

They had claimed XYZ in the past, and even before that they had contact with the Deep. Since both of these exist in the same sentence, past-perfect (basically doubly-past) has to be used when referring to the contact, thus "had had".

**Comment by Drl-Omniar** [comment]
saying it out loud still doesn't make any sense, it could be changed to: "The aliens claimed that they (have) had dealings with the Deep in the past." instead of  "The aliens claimed that they (had) had dealings with the Deep in the past."

**Comment by EjoThims** [comment]
This is correct, but awkward.

**Comment by Zireael07** [comment]
Correct, but awkward. The best fix would be to rephrase the "had dealings" to some other verb.

**Comment by Ferociousfeind** [comment]
Y'all are weird. "had had" is a fine and functional grammatical structure, the first "had" gets minimized and very much likes to become a suffix onto the end of a previous noun- "they'd had dealings with the deep" for example.

**Comment by roadrunner56** [comment]
Should this be closed now that #6445 has been merged?
