### ISSUE TITLE
Fighters repair only when thrusting/turning

### ISSUE THREAD

**Issue by Ben-Wise** [endless-sky/endless-sky#6437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I've captured korath fighters (as you do...) when farming JDs for extra cash I've noticed that they are only repaired when my flagship is either thrusting or turning.

I don't know why this is but I don't expect my engines to be linked to my repair systems.

I don't know whether or not this effects the ship itself but it's quite possible it does.

From my observations this effects the flagship, not sure about escorts.

### Steps to Reproduce

Using a flagship with fighter bays and a
1: Disable a fighter (preferably where someone else won't shoot it down and kill it)
2: Board with intent to capture
3: sit still and don't touch the movement keys and observe no repair (shields regen though if carrier has full shields)
4: move and observe the fighter start repairing!

### Expected Behavior

Fighters should repair even if the carrier is not moving (providing said carrier has repair facilities of course)

### Screenshots

Below is a link to a video capture of me boarding a fighter and it repairing abnormally as described.

[Fighter repair video - https://1drv.ms/v/s!AhEogbCmotiYg5M5MT_iRh5q9pSD9A?e=oWfVMF](https://1drv.ms/v/s!AhEogbCmotiYg5M5MT_iRh5q9pSD9A?e=oWfVMF)

### Link to save file

Any save will do, but here is mine:
[Elijha Letney~fighter raid.txt](https://github.com/endless-sky/endless-sky/files/7776189/Elijha.Letney.fighter.raid.txt)

### Operating System

Windows 10 Home

### Game Source

GitHub Releases

### Game Version

V0.9.13

**Comment by quyykk** [comment]
Thanks for the report! I believe this was fixed in #6252; I cannot reproduce the issue with your save file anymore. It will be in 0.9.15.

**Comment by Ben-Wise** [comment]
Ok, thanks for looking into it!
As it's going to be fixed with #6252 I'll close this issue
