### ISSUE TITLE
v0.9.14's tag is not an annotated tag

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#6452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `0.9.14` tag is a lightweight tag as opposed to an annotated tag.

### Steps to Reproduce

Run `git cat-file -t v0.9.14` and see that it prints `commit`.

### Expected Behavior

It should print `tag` like it does for `v0.9.13` and earlier.

### Operating System

N/A

### Game Source

Built from source

### Game Version

N/A

### Additional Information

This affects, for instance, `git describe origin/master`: currently, that command outputs `v0.9.13-390-gc9cc144bd` rather than `v0.9.14-230-gc9cc144bd`.

**Comment by tehhowch** [comment]
Is there an impact on external tooling? Otherwise I don't see any issue at all. IIRC I used the GitHub tag creation webpage to create 0.9.14, and I plan to do the same for 0.9.15 in a few weeks.

**Comment by jostephd** [comment]
I'm not aware of specific impacts on external tooling. However, it can affect bug hunting. Suppose somebody bisects a bug to `v0.9.13-390-gc9cc144bd`. They will naturally assume that commit to have been first released in v0.9.14, even though that commit will actually first be included in v0.9.15. They might then incorrectly report the range of releases affected by the bug, or they might test the v0.9.14 tarball and find it doesn't have the bug and lose a bit of time on figuring out why, etc.

Using annotated tags is also what Git's documentation recommends. See, for instance,
https://github.com/git/git/blob/e83ba647f7c61cf945690d6a0bd8c172a6498dc8/Documentation/git-tag.txt#L46-L55.
Commands such as `git push --follow-tags` will also ignore plain tags.

I'd suggest to use annotated tags for releases going forward. I'd even suggest to consider force-pushing `v0.9.14` as an annotated tag. But then again, if you disagree, feel free to just close this.

**Comment by tehhowch** [comment]
I'm not modifying the existing v0.9.14 tag. I'll keep this in mind for the next release, though.

**Comment by jostephd** [comment]
:+1:
