### ISSUE TITLE
Document turret tracking preference values

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#6453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The meaning of the two values of the "Turret tracking" preferences, "opportunistic" and "focused", is not documented.

### Steps to Reproduce

Look in tooltips, in this repository, in the wiki, in the github issues, and in the git history for documentation, and fail to find it.

I found commit ad959b11f7a732a65d1bd63f13a78c0d465f07ef by MZ which shows the preference is used as a parameter to `AI::AimTurrets`, but even comments in that function don't give a full answer, and in any case players shouldn't have to reach into the source to know what a preference is doing.

### Expected Behavior

Document the two values of the preference.

### Operating System

N/A, and I wish this field wouldn't be mandatory

### Game Source

Built from source

### Game Version

c9cc144bdb0a7118aa1ae56fcf65d173bbb48cc4

### Additional Information

Maybe go through the settings screen and give everything tooltips.

**Comment by lumbar527** [comment]
`focused` means that your turrets will only aim at the selected target. `opportunistic` means they operate semi-independently and shoot at targets closest to themselves. Not sure where I found this out.

**Comment by TomGoodIdea** [comment]
https://github.com/endless-sky/endless-sky/commit/de07d9e45bc505ed79f66d4712867ece72fc9734
