### ISSUE TITLE
Wrong snapshot names

### ISSUE THREAD

**Issue by sigus** [endless-sky/endless-sky#6468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you create a new snapshot while the most recent snapshot is a snapshot with a different name than the pilot's name, you get a wrong name of snapshot.

### Steps to Reproduce

For example:

1. Create a snapshot named "ababaca"
2. Then, immideately after step 1, create a snapshot named "abacaba"

Instead, you will get a snapshot named "ababaca~abacaba".

### Expected Behavior

In the example above you should get a second snapshot named "abacaba".

### Operating System

Arch Linux

### Game Source

Built from source

### Game Version

commit f40324f34cbf68bac523a55d6d33e1034545c630

**Comment by tehhowch** [comment]
I don't think your reproduction steps are detailed enough; I can't reproduce the situation.

Also note I'm not certain about this statement:
> while the most recent snapshot is a snapshot with a different name than the pilot's name

All files that represent snapshots for a given pilot will start with the pilot's name. Otherwise, they are not for that pilot.

**Comment by quyykk** [comment]
I can reproduce, I'm also on Linux. After creating a snapshot with the name "test" create another snapshot with the name "foobar". Instead of last snapshot created having the name "foobar", it has the name "test~foobar".

If I actually load the save file and then go back to the load menu to create the second snapshot then it works. It's really only when creating subsequent snapshots.

**Comment by tehhowch** [comment]
Probably this is actually an issue with `Files::Copy` having different behavior on Windows vs macOS / linux
https://github.com/endless-sky/endless-sky/blob/1cf4239517bf645dd4dbf723ac392ea6ed02b2d1/source/Files.cpp#L429-L433

**Comment by tehhowch** [comment]
As mentioned on the #6469, this issue is due to the above differing behavior between Windows and other platforms. I'd prefer we fix it by preserving the source file's timestamps when using `Files::Copy`, as is done by the Windows system call. I believe we can use `utime` / `utimesat` posix functionality to achieve this.

**Comment by sigus** [comment]
It looks like what you suggest won't help if I'm not mistaken because snapshots with the same timestamp are sorted lexicographically, so it might not be what you need at the top of snapshots list.

**Comment by tehhowch** [comment]
All snapshot file names are the same as the pilot, followed by the tilde. The tilde sorts after all allowed filename characters. So as long as the snapshots have the same timestamp as the source pilot file they will appear after it in the list of saves for a given pilot.

**Comment by sigus** [comment]
All these snapshots have the same timestamp.
![Screenshot_2022-01-10_15-19-24](https://user-images.githubusercontent.com/400036/148721318-d97df70c-cbca-44d9-b002-b64e1515e57d.png)

**Comment by tehhowch** [comment]
Ah yes, another disparity in the platform, likely stemming from the order in which the files are listed in the directory.

That is remedied by updating the section of code you linked: when the timestamps are equal, order the two files by name.

**Comment by sigus** [comment]
> That is remedied by updating the section of code you linked: when the timestamps are equal, order the two files by name.

Yes, it is a possible way to solve this problem.

> Ah yes, another disparity in the platform, likely stemming from the order in which the files are listed in the directory.

No, because Files::List already sort files by name.

**Comment by petervdmeer** [comment]
> As mentioned on the #6469, this issue is due to the above differing behavior between Windows and other platforms. I'd prefer we fix it by preserving the source file's timestamps when using `Files::Copy`, as is done by the Windows system call. I believe we can use `utime` / `utimesat` posix functionality to achieve this.

We can also consider if we even want to keep the Copy function in the first place; if we can switch to a system where autosaves get written once (based on a name and a timestamp) and we automatically remove older autosaves, then we would have functionality similar to what we have now (only a limited amount of autosaves) but without the need to ever copy the autosave files.
Or is there some benefit to copying the files that I'm missing?

**Comment by sigus** [comment]
`Files::Copy` is not used for autosaves (`PlayerInfo::Save`) nor for "previous" snapshots (`MoveFileExW`/`rename`), but all player-created snapshots are created by copying.
