### ISSUE TITLE
Impossibility to change the reputation of Quarg

### ISSUE THREAD

**Issue by Oeleo** [endless-sky/endless-sky#647]
I wanted to sell all of my Quarg's outfits but I need to be friendly with the Quargs first, because I'll lost several ships everytime I see one of their ship on the map. So I went on my save and I :
-Changed the reputation of the Quarg
-Remove the "planetvisited" on their planets
-Sell all of my Quarg's outfits
But everytime that I come back in the game, they stay hostile, and when I resave their reputation come back at ~ -9635 again.
So is it a bug or I just forgot something ?

**Comment by IFailAtGaming** [comment]
Are you closing the game before editing? Because if you don't it doesn't seem to work

**Comment by endless-sky** [comment]
You need to change the value in the "reputation with" section at the very start of the file. Changing the "condition" flag won't change anything, because that is auto-updated whenever a mission's condition checks are done.

**Comment by Oeleo** [comment]
Oh, my bad. It worked perfectly.
Thank you !
