### ISSUE TITLE
Throw error if non-ASCII letters used in phrases

### ISSUE THREAD

**Issue by a-random-lemurian** [endless-sky/endless-sky#6470]
### Problem Description

Endless Sky doesn't support unicode characters like `ū` or even accented characters like the accented `é` in `Padmé Amidala`, and they render as spaces if you try to render them anyway, if my limited knowledge of the codebase is correct, which likely it isn't.

I copied some Japanese town names from Wikipedia for my plugin, and some of the names had a weird space in them, which I figured was because the name lists had characters which were not yet supported.

### Related Issue Links

None.

### Desired Solution

Throw a parser error with `PrintTrace()`.

Message can be something like:

`Name contains character that cannot be rendered:`.

And when we finally have Unicode support, we can remove this.

### Alternative Approaches

- Add support for Unicode characters.
- Tell plugin authors to deal with it themselves.

**Comment by tehhowch** [comment]
Marking unlikely since we plan to support these characters, e.g. #4123
