### ISSUE TITLE
Bug - screen not refreshing

### ISSUE THREAD

**Issue by EndlessAdventures** [endless-sky/endless-sky#6472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bug fault- been playing game for years on laptops currently using Windows 10. Bug is the game is not refreshing screen so have to click on steam window and then click back to game so single frame update. As you can gather this is painfully slow, any suggestion would be greatly appreciated. 
Have uninstalled/reinstalled multiple time, deleted old games, change target directory, laptop has all current patches and updates.
Sound is unaffected and keeps updating itself just single static image available.  

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Game operates normally

### Screenshots

Due to no type of errors screenshots not needed

### Link to save file

just reinstalledx5 so default 

### Operating System

Windows  10 Home 21H1

### Game Source

Steam

### Game Version

V0.9.12

### Additional Information

Esc key does not work so no saves, scroll down then refresh for everything, very frustrating

**Comment by MCOfficer** [comment]
That sounds like something related to adaptive VSync. If you got into the setting, there's one called "VSync". Can you play around with that and see if it helps?

**Comment by tehhowch** [comment]
I've not heard of this behavior before.
Are you on a new computer? If not, has playing Endless Sky always been this way? If not, what has changed on your computer? What other games do you play on this computer? What sort of hardware does it have?

Is anything different if you run your game executable directly (from Windows Explorer), rather than launching it from Steam library?

**Comment by EndlessAdventures** [comment]
Vsync is ok and updated to latest Beta but no luck.

Repalced my old laptop early last year and have used this Lenova Ideapad for Endless before getting annoyed with mission failures glitches. The laptop is corei5 and MS & virus swr all current so should be good. Have tried from Windows but still only doing one frame updates each time.

**Comment by tehhowch** [comment]
About all I can recommend is that you try using newer runtime libraries:

https://www.libsdl.org/download-2.0.php

Without hardware specifics (e.g. "core i5" is nearly useless and tells us nothing about your actual processor), there isn't much else for us to recommend you to do.

Additionally, can you tell us more about what you can do with the computer? Any other installed computer games you can (or can't) play?

**Comment by quyykk** [comment]
This sounds like a hardware issue tbh, especially because of the "mission failure glitches". If you are still experience this with the latest Steam build, feel free to reopen or open a new issue!
