### ISSUE TITLE
Drug smuggling mission... to Coalition space

### ISSUE THREAD

**Issue by a-random-lemurian** [endless-sky/endless-sky#6473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been getting drug smuggling missions whose destinations are in Coalition space. The mission in question is "Drug Running 3".
```
mission "Drug Running 3"
	name "Drug Running"
	description "Bring a shipment of illegal drugs to <destination>. If you are caught with this cargo, you may be fined."
	minor
	repeat
	source
		attributes "near earth" "dirt belt" "north"
	destination
		attributes "urban"
		distance 1 100
	cargo "illegal drugs" 5 2 .1
	illegal 70000 `In addition to the fine, the illegal drugs are confiscated from your cargo hold.`
	stealth
	to offer
		random < 10
		has "Drug Running 2: done"
	
	on offer
		dialog `A well-dressed woman approaches you as you are walking through the spaceport and asks quietly if you would be willing to help facilitate the transport of some "naughty substances" to a certain individual on <planet>.`
	
	on visit
		dialog phrase "generic cargo on visit"
	on complete
		payment
		payment 120000
		"drug smuggler" ++
		dialog `You hand off the illegal "substances" to your contact on <planet>, who pays you <payment>.`
```

My plugin, LEESt, links Coalition space to Human space by hyperlane. We might want to reduce the "distance" attribute or only allow the destination to be in human space.

### Steps to Reproduce

Do a few drug running missions. You might need to link human space directly to Coalition space.

### Expected Behavior

I get the same mission, but the destination should be in human space.

### Operating System

Ubuntu 20.04.3

### Game Source

Built from source

### Game Version

continuous

**Comment by tehhowch** [comment]
Content written for vanilla is not expected to handle changes to the universe caused by plugins, given that plugins can arbitrarily change the entire game universe.

**Comment by a-random-lemurian** [comment]
We should reduce the distance attribute or restrict this mission to only Republic, Syndicate, Free Worlds, Pirate, Neutral, and Independent space.

**Comment by a-random-lemurian** [comment]
> Note that `distance 1 100` is used from within a region of space _not linked to alien regions_ to mean "anywhere in human space". Another way used to indicate this intent is `near "Sol" 100`. Distances were used to avoid needing to account for all the possible current and future governments in play.

Alright, so what should I do with this issue?

Close it or something?

**Comment by W1zrad** [comment]
> Close it or something?

Sounds like this concern is resolved, so yup!
