### ISSUE TITLE
AI ships repeatedly try to pick up the same piece of cargo

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#6476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A few AI ships were flying back and forth over a piece of dumped cargo trying to pick it up, and kept doing so until it disappeared.

### Steps to Reproduce

I saw this at the end of the fight in `Remnant: Defense 1`. A couple of Remnant ships were flying back and forth over a dumped cargo box. If the box were at the clock center, one ship was flying 1 o'clock to 7 o'clock and back, another 3 o'clock to 9 o'clock and back, and another probably 4 o'clock to 10 o'clock. They kept doing this until the box disappeared.

I managed to partially reproduce this and take a video, but it doesn't happen every time through the mission.

### Expected Behavior

AI ships shouldn't be trying to pick up cargo that they can't pick up, or that they've tried to pick up and failed.

### Screenshots

I didn't get this on video the first time. The second time I managed to catch a video of a Remnant trying to pick up a dumped cargo box and making a U-turn, but I accidentally picked it up myself before the remnant started accelerating to pick it up again. https://user-images.githubusercontent.com/24784687/148860727-ae7923e5-98b5-4e3c-ab6d-6b9ce056fd57.mp4

### Link to save file

This is a new pilot. I cheated myself a large warship and a teleport to Caelian, took the blood test normally, then played normally until I got the mission. The video was taken from this savefile.

[t4 t4.txt](https://github.com/endless-sky/endless-sky/files/7842737/t4.t4.txt)

### Operating System

Linux

### Game Source

Built from source

### Game Version

c9cc144bdb0a7118aa1ae56fcf65d173bbb48cc4

### Additional Information

I asked on Discord first.  From my post there:

> Hmm. Comparing AI::DoHarvesting and Engine::DoCollection, the latter compares the ship's and flotsam's governments but the former does not. So, I wonder if the cargo box was actually dumped by an `appeasing` remnant ship, and then other Remnant ships got stuck in a loop trying to pick it up?
> 
> i.e., should AI::DoHarvesting start to check `ship->GetGovernment() == flotsam.SourceGovernment()` whenever it checks that there's enough cargo space?

**Comment by Zitchas** [comment]
I can reliably have this happen if I just sit around in a Remnant system long enough. Just stay out of the way, let the Remnant eventually disable a Palavret, and then watch for them running back and forth over a piece of flotsam. It doesn't happen every time, but it seems to do it... Maybe one in four times, there abouts?

I'm running 0.10.0-Alpha from updated around February 10th.

**Comment by UnorderedSigh** [comment]
Fix is in #8528. It happened because the requirements for picking up flotsam were stricter than targeting it. Examples:

1. Pirate ship explodes into flotsam. Another pirate ship tries to harvest it, but can't, because the flotsam is from its own government.
2. Merchant ship dumps its cargo to distract the pirates. A miner (also merchant) tries to pick it up, but can't, since the flotsam is from its own government.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/2633fa12d95f11df5d765e08882ca77b8ea16e72
