### ISSUE TITLE
Original EV Title Screen Music

### ISSUE THREAD

**Issue by jansenart** [endless-sky/endless-sky#6478]
### Problem Description

I've managed to identify the original [Escape Velocity theme music.](https://www.youtube.com/watch?v=2YLQ4rZwRHQ) as a track on a Universal/BMI "Killer Tracks" album from 1993.

It's called "Face of the Enemy" by Larry Wolff, and I think it's available for licensing here: http://links.universalproductionmusic.com/FiRQKF

BMI is supposedly a nonprofit, and licensing fees are scalable, so it might be cheap for a free-to-play game? I saw somewhere in the range of USD 400-600 for a project like this. (Would probably merit a kickstarter, which could be linked on the tile screen... Just spitballing here)

### Related Issue Links

n/a

### Desired Solution

The goal would be to acquire a license for the original EV track.

### Alternative Approaches

Continued silence would be the status quo. Royalty-free music would be an alternative but I think fans of EV would appreciate the callback and anything less than the track would be disappointing.

**Comment by tehhowch** [comment]
We're not paying to license anything, and thus not going to use any content that requires paying for its license.

**Comment by Zitchas** [comment]
That's really cool that you found it. I'll have to track down that album just to listen to it again. It has so many good memories for me.

That being said, that is Escape Velocity's title music, not Endless Sky's. I like to keep my games straight, and having the same music on two games might conflate the two. 

That being said, we do actually have some talented people in the community working on making trailers and ambient music, and I think someone was making music that could be a theme for theme for the main menu.

**Comment by a-random-lemurian** [comment]
I would prefer that this be a plugin.

However, implementing the ability to play music in the title screen, is a separate thing on it's own.

**Comment by McloughlinGuy** [comment]
If someone knows how they could make a remix of the song for the title screen, that might work. You wouldn’t have to license it then.

**Comment by MCOfficer** [comment]
> If someone knows how they could make a remix of the song for the title screen, that might work. You wouldn’t have to license it then.

Not necessarily - Remixes don't fit neatly into any category of the established copyright system, so what most artists do is cite fair use or clear it with the copyright holder first. Fair use is not guaranteed to hold up in court though, which, to make it even more complicated, differs between countries.

Voting to close in favour of #6479 - if people *do* remix it and clear it with the copyright holder, they can still open a PR in spite of this issue being closed.

**Comment by jansenart** [comment]
I concur. Having just the ability to drop in an audio file would absolutely
solve this.

**Comment by pepoluan** [comment]
There are lots of royalty-free music on YouTube. You can check out the following channels:
* https://www.youtube.com/c/audiolibrary-channel
* https://www.youtube.com/c/RoyaltyFreeMusicNoCopyrightMusic
* https://www.youtube.com/c/NoCopyrightMusicForCreators

Usually the requirement is to just provide a text telling the source of the music, something we can put in the scrolling text in the Title Screen.

**Comment by MCOfficer** [comment]
Let's move all of this into one issue. Duplicates #6479
