### ISSUE TITLE
Can missions reward negative amounts of money?

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#649]
I had an idea for 'rentable escorts', where you would pay money for a ship to follow you around and defend your ship/fleet. I was going to put it on the job board, with a negative reward for completing the mission. The escort point would be the planet at which the mission was offered from, though your 'payment' would be 'given' on fail regardless of your location.

This depends on two things:
1. Can you give negative amounts for jobs?
2. If so, how would the game handle not having enough money at the end of the mission?

**Comment by lehgogh** [comment]
Never mind. I searched through `jobs.txt`, but there is no 'on fail' event. This would allow players to cheat their way out of paying by simply not returning to the original planet on time.

**Comment by LocalGod79** [comment]
fyi, you can give negative payment, and it behaves almost identically to removing outfits.

also, 'on fail' is indeed a mission trigger, and a negative payment will be enforced as soon as the player can afford it.

**Comment by lehgogh** [comment]
Yes, but what if the player has less money than is charged?

**Comment by LocalGod79** [comment]
the mission will not activate the trigger until the condition is satisfied.

you could always make the payment at the 'on offer' trigger, so that it would not be offered if the user cannot afford it.

**Comment by lehgogh** [comment]
@LocalGod79 Someone could then have just enough money to meet the 'on offer' condition but lose money afterw-

Idea! What if we could make it apply a mortgage when starting the mission? That way, they would still be forced to pay it, regardless of their starting/ending balance.

**Comment by LocalGod79** [comment]
applying mortgages was something i requested ages ago in the google group -
it is not currently possible for missions to impose/apply them.

**Comment by lehgogh** [comment]
I thought that it was given in the starting conversation, but it's actually given in `start.txt`.

**Comment by LocalGod79** [comment]
> Someone could then have just enough money to meet the 'on offer' condition but lose money afterw-

no, they can't - the mission won't offer if the on-offer trigger calls for an amount more than they have - and when they *do* have enough for it to trigger (and it's offered), the mission takes the payment immediately.

this method works if you have a pointer mission to a location, and then the second mission has the on-offer payment/withdrawl, and is demonstrated in the free worlds reconciliation plot when the player is told to visit Hephaestus, and (a quip about already having a jump drive or) their scram/hyperdrive is removed and replaced with a jump drive.

in a jobs situation, you could create a job-mission that tells the player to take off and land indicating the price and length of escort contract, and impose a condition signalling their intent to hire.  on the second landing, the offer trigger takes the payment (or doesn't offer) and clears the intent condition, and the npc takes off and follows them until their deadline runs out.  to complete; never;

i could even code this up pretty quickly, if you like.

**Comment by lehgogh** [comment]
I'm somewhat confused by your explanation, so it would be nice for you to show me an example of what you're talking about. However, the ability to apply mortgages (and negative mortgages, to pay over time) would still be a good modding feature, which I will try to work on.

**Comment by LocalGod79** [comment]
there's an example in my last post.

negative payment works exactly like outfit removal.

for instance;

to offer
_has "missionx: done"
on offer
_payment -10000
_dialog `would you like to spend 10k?`

the player must have completed "missionx", and have 10000 credits in their account for the mission to actually offer and the dialog to appear.

**Comment by LocalGod79** [comment]
so, i played around with a job a little bit - if you put the negative payment under "on accept" it will not be offered on the job board unless the player can afford it (the same as on offer).

in the below example the player pays on accept, cannot complete the mission, and the npcs will follow the player until they're dead or the deadline runs out.

here's what i had coded;
mission "Hired Escort I"
	name "Hired Marauder Fleet I"
	description "You have paid <payment> to have a Marauder fleet help protect yours until <date>."
	repeat
	job
	deadline 7
	destination Earth
	source
		government "Republic" "Syndicate" "Free Worlds" "Neutral"
	to offer
		random < 90
	npc save
		fleet "Marauder fleet I"
		personality escort heroic waiting
		government "Merchant"
	on accept
		payment -10000000
	to complete
		never

**Comment by endless-sky** [comment]
This question seems to be answered, so I'm closing this issue.
