### ISSUE TITLE
Wormholes disappeared.

### ISSUE THREAD

**Issue by aka47775** [endless-sky/endless-sky#6506]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Terminus and the Remnant wormholes are disappeared.

### Steps to Reproduce

Go to the Deep and  do the  "Deep: Remnant line" missions until you reach that stage where you have to get the Forge-Class Steering and Forge-Class Thruster,then get the "Keystones" mission from the Remnant.After that buy 50 keystones from the Hai with 2 Osprey.

### Expected Behavior

Then the wormholes maybe disappear.

### Screenshots

![bug1](https://user-images.githubusercontent.com/98411504/151017631-125901a7-9a50-4d2f-9b79-ba642dcc13d5.PNG)
![bug2](https://user-images.githubusercontent.com/98411504/151017653-efb40510-2ee7-471b-8fc9-2a6e83480f6e.PNG)
![bug3](https://user-images.githubusercontent.com/98411504/151017674-55ef7b31-d83a-4e01-b4e3-ae975a6486cf.PNG)

### Link to save file

[Joe Mael~3023-06-05.txt](https://github.com/endless-sky/endless-sky/files/7935266/Joe.Mael.3023-06-05.txt)

### Operating System

Windows 10 Home,21H2,19044.1466

### Game Source

GitHub Releases

### Game Version

V.0.9.14

**Comment by Amazinite** [comment]
Your flagship doesn’t have a keystone installed.

**Comment by aka47775** [comment]
> Your flagship doesn’t have a keystone installed.

It's solved.Thank you.
