### ISSUE TITLE
landing on wyvern Station

### ISSUE THREAD

**Issue by sailor-aus** [endless-sky/endless-sky#6520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've attempted to land on Wyvern Station in the Izar system before the whole FW arc begins and my game crashes on landing. I've tried in different ships and from different planets but i can't seem to do it anyway

### Steps to Reproduce

Jump into the Izar System.
Set autopilot to land on wyvern station
see your game crash.

### Expected Behavior

game crashes

### Operating System

mac OS High Sierra. Version 10.13.6

### Game Source

GitHub Releases

### Game Version

v0.9.14

**Comment by sailor-aus** [comment]
actually it appears to be any station. just landed on charon station in the aldhiban system and the same thing happened.

**Comment by MCOfficer** [comment]
We've had a couple fixes for crashes since 0.9.14; if you don't want to wait for the experts you might want to try out the continuous build. 

Note that this could in theory alter your savefile, so you cannot go back to 0.9.14 afterwards. So backup your savefile before you do it.

**Comment by quyykk** [comment]
I've seen this bug like at least 2 times before. It's caused by either missing or faulty audio drivers on oldish MacOS hardware I believe (or maybe it's something wrong on our side), which cause our music playing code to crash somewhere. I'm not sure where exactly though.

It crashes on stations because stations are the only planets where music is played in the background.

**Comment by a-random-lemurian** [comment]
I once played Endless Sky on an ancient MacBook Air from the early 2010s, for now I recommend opening Endless Sky.app and modifying the game files to remove all sounds from the stations.

I also recommend you get the continuous build, as mentioned by MCOfficer.

**Comment by McloughlinGuy** [comment]
> I've seen this bug like at least 2 times before. It's caused by either missing or faulty audio drivers on oldish MacOS hardware I believe (or maybe it's something wrong on our side), which cause our music playing code to crash somewhere. I'm not sure where exactly though.
> 
> It crashes on stations because stations are the only planets where music is played in the background.

The music is really creepy too, I wouldn’t mind if they removed it.

**Comment by Zireael07** [comment]
Wouldn't an option switch for "no music" (which would be welcome for the people who have babies/flatmates that shouldn't be disturbed) fix the problem?

**Comment by sailor-aus** [comment]
> I once played Endless Sky on an ancient MacBook Air from the early 2010s, for now I recommend opening Endless Sky.app and modifying the game files to remove all sounds from the stations.
> 
> I also recommend you get the continuous build, as mentioned by MCOfficer.

how does one open Endless Sky.app? when i try it just launches the game itself. I know how to access my save files but i haven't figured out how to access the game files.

**Comment by sailor-aus** [comment]
> > I once played Endless Sky on an ancient MacBook Air from the early 2010s, for now I recommend opening Endless Sky.app and modifying the game files to remove all sounds from the stations.
> > I also recommend you get the continuous build, as mentioned by MCOfficer.
> 
> how does one open Endless Sky.app? when i try it just launches the game itself. I know how to access my save files but i haven't figured out how to access the game files.

never mind. i figured it out. Thanks all for helping me.

**Comment by a-random-lemurian** [comment]
> Wouldn't an option switch for "no music" (which would be welcome for the people who have babies/flatmates that shouldn't be disturbed) fix the problem?

Pretty sure they'd just control the volume of the speakers through the operating system itself or their sound equipment (in real life), I suppose?

**Comment by a2dodger** [comment]
> > > I once played Endless Sky on an ancient MacBook Air from the early 2010s, for now I recommend opening Endless Sky.app and modifying the game files to remove all sounds from the stations.
> > > I also recommend you get the continuous build, as mentioned by MCOfficer.
> > 
> > 
> > how does one open Endless Sky.app? when i try it just launches the game itself. I know how to access my save files but i haven't figured out how to access the game files.
> 
> never mind. i figured it out. Thanks all for helping me.

Can you explain how you fixed it?  I can't figure it out.
