### ISSUE TITLE
Interdiction and Combat Instancing for slower, more tactical combat 

### ISSUE THREAD

**Issue by Victor239** [endless-sky/endless-sky#6523]
### Problem Description

Endless Sky gets a lot of things right (trading, ship upgrades, fleet management etc) but one area I find lacking is the combat which has aged quite a bit, especially after having recently played Starsector. It's too arcadey, reaction-dependent and lacks tactical gameplay which is incongruent in a game that is otherwise far more focused on strategic thinking. 

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/4034 is the most obvious one. This isn't an issue in Starsector, because in the combat instance as you might expect, small fighter ships are faster and more nimble than larger ships. 

https://github.com/endless-sky/endless-sky/issues/6518 strafing is also a feature here, and it's not overpowered because different ships have different speeds, fuel, etc.

### Desired Solution

An [example video](https://youtu.be/87AVJvztUmg) of the combat.

Instead of combat being constant whilst in space, Starsector instead allows pirates (or other enemies) to interdict your fleet if their fleet has the speed or the weaponry able to do so. If they do reach your fleet, then you'll be put into a separate instance of space that allows for great tactical control of your fleet. 

In this combat instance you're able to:
- Pause during the battle, which allows greater tactical co-ordination.
- Choose which of the ships in your fleet you wish to use in the battle (ships cost resources to use and repair, and may be lost so it's not always wise to use them all).
- Control your flagship (main ship chosen before each combat) via WASD and cycle through it's weapons/shields, whilst your other fleet ships are controlled via AI.
- You can also direct your fleet to specific locations in the battlefield via a map overview, and set the AI to different behaviours like guard, harass, etc.
- Instead of controlling your fleet as one blob moving at a similar speed (as in the non-combat space travel mode), the speed, agility and other characteristics of each ship matters much more. 
- Attempt to flee if the battle is going really poorly. 

Combat as a result feels MUCH better in Starsector, which is a shame because all the rest of the systems in Endless Sky are great. 

Having a separate combat mode also allows for more options in normal space travel, such as:
- Afterburners to give your ships a quick burst of speed at the cost of additional resources
- Turning off your transponder, which makes you harder to detect by other ships but space police may fine you if you're caught
- EMPing enemy fleets
- Jettisoning cargo in the middle of space if necessary

### Alternative Approaches

I don't think you can simply reduce the combat speed and leave out the combat instancing since it would be a jarring change and prevent taking advantage of additional abilities that are normally only available in either mode. 

### Additional Context

Some videos of what combat looks like:
- [Combat (Basic) Tutorial](https://youtu.be/87AVJvztUmg)
- [Advanced Combat and Fleet Command Tutorial](https://youtu.be/r97IWLy2b-k)
- [Massive fleet battle](https://youtu.be/K9iInS5vC_E)

**Comment by Amazinite** [comment]
If I wanted to play Star Sector then I'd play Star Sector. Adding "combat instancing" would be a massive overhaul to how Endless Sky works and would just be a blatant rip of what Star Sector does.

**Comment by Victor239** [comment]
> Adding "combat instancing" would be a massive overhaul to how Endless Sky works

Not particularly, space combat would work the same except separated out into a separate slower instance and the basic features needed are only really being able to pause and to direct individual ships to specific areas on the battlefield. Additional features can be added later if desired but are not essential.

> would just be a blatant rip of what Star Sector does.

And ES is a rip-off of Escape Velocity so I'm not sure I see your point. The advantage of an open-source game in constant development is it can always improve and borrow ideas from everywhere, regardless of the source. One feature does not make a game besides.

**Comment by Amazinite** [comment]
> And ES is a rip-off of Escape Velocity so I'm not sure I see your point.

I'd say there's a pretty big distinction to be made between being a spiritual successor to a game who's last title released almost a decade and a half prior to Endless Sky's first release and copying major/signature mechanics from a contemporary title.

**Comment by Zireael07** [comment]
The only advantage Starsector has over ES IMHO is the ability to pause AND then issue orders.
