### ISSUE TITLE
Option to disable person ships or disable author ships

### ISSUE THREAD

**Issue by samrocketman** [endless-sky/endless-sky#6528]
### Problem Description

Person ships tend to spoil outfits, content, and can ruin immersion for new players.  It would be nice to have an in-game option in settings which allow the player to disable author ships.

While playing with friends the author ships were initially kind of neat but quickly became bothersome with their spawn rate and outfits usage.

### Related Issue Links

None

### Desired Solution

Option in settings to prevent person ships from spawning.  No author ships would spawn if the setting is turned on.

### Alternative Approaches

On discord, it was recommended I delete `./data/persons.txt` and rebuild.  This is fine for my case but when I play with players on other platforms who do not build from source it is more complex.  [Link to Discord conversation][1].

[1]: https://discord.com/channels/251118043411775489/308902312741568512/934286231913779201

**Comment by Zitchas** [comment]
This sounds like an excellent thing to have in the proposed Gamerules:
https://github.com/endless-sky/endless-sky/pull/5978

**Comment by tehhowch** [comment]
This could be done on a granular level with #3996, too

**Comment by tehhowch** [comment]
This is possible to do at a granular level now.

**Comment by DeciduousBeard** [comment]
@samrocketman, just wondering what you mean by these phrases: "While playing with friends" and "when I play with players on other platforms". This is a single-player game, how are you playing with others? Is there some feature I've missed that allows some sort of collaborative or competitive gameplay?

**Comment by samrocketman** [comment]
I created a plugin for disabling author ships.  It would be nice to have a toggle but this could potentially be closed in order to avoid too many niche options.  https://github.com/samrocketman/endless-sky-disable-author-ships

**Comment by samrocketman** [comment]
@DeciduousBeard said:

> just wondering what you mean by these phrases: "While playing with friends" and "when I play with players on other platforms". This is a single-player game, how are you playing with others? Is there some feature I've missed that allows some sort of collaborative or competitive gameplay?

I sometimes host "let's play" parties with local and remote people.  We all get a single-player copy of the game and try to the best of our ability to line up our games will talking through gameplay.  Some fun activities to share with friends include:

* Everyone playing together outfits their ship the same.  This means you can discuss as a group how to spend money and build your fleet.  With the end goal that your fleets will always match.
* "Iron man" run.  Last friend to die in-game wins the iron man run.  When everyone except for one person has died then the iron man run is over and everybody deletes their save game.
* Reading the story together out loud.  This can be a fun activity for some such as reading each other books.  Taking turns reading the story and sometimes even acting out the voices.  This play style isn't for everyone but it's a fun way to play if you have theatrical friends.

**Comment by samrocketman** [comment]
Closing since a plugin exists.
