### ISSUE TITLE
Day condition that counts from 1 to 365/366

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#6553]
### Problem Description

The game currently has three conditions that keep track of the date, those being "day" for day of the month, "month" for the numerical month of the year, and "year" for the year that the save is in. Should you want to have something occur over a date range that spans across a month, you end up needing to make use of a rather lengthy ConditionSet.

For example, say you have a mission that you want to have offer between February 13th and April 20th. The offer conditions for just this date range would be the following:
```
to offer
	or
		and
			month == 2
			day >= 13
		month == 3
		and
			month == 4
			day <= 20		
```

### Related Issue Links

Nothing directly related to this idea. I suppose #5017 could be tagged as this would be an auto-generated condition.

### Desired Solution

Have a new condition that marks the number of days since the start of the year. This would simplify the example above to just the following (let's just call the condition "days" for now):
```
to offer
	"days" >= 43
	"days" <= 110 # Ignoring leap years.
```

### Alternative Approaches

N/A

### Additional Context

While simpler, I suppose the "days" condition would be less readable, as one would then need to reverse engineer the offer conditions to figure out when exactly the 43rd and 110th days of the year are. Where I imagine I'd end up using this more though is in saving the current "days" value to a variable to be used later, akin to my suggestion [here](https://github.com/endless-sky/endless-sky/pull/6550#discussion_r806596147) on #6550 to record the current year to a variable so that we can guarantee that the next mission will happen X years after the first without the need of an event. (And the benefit of using a saved condition over an event is that we can potentially branch a conversation based off of just how long it's been since the condition was saved by comparing the current date to the saved value.)

Might also be worth having a "leap year" condition that is either 0 for false or 1 for true. That'd just be another condition that would cut down on condition comparisons that a mission needs to make should a mission want to know if it's a leap year. So with the above example if we didn't ignore leap years, the second line of the offer conditions would become `"days" <= 110 + "leap year"`

**Comment by DownsB** [comment]
That would be a convenient feature for "repeat yearly" missions.

To record dates for one-shot missions like in [#6550](https://github.com/endless-sky/endless-sky/pull/6550#discussion_r806596147) , another auto-generated condition could be an "epoch" (number of days since the start of the game). 
The recorded dates would be more compact and allow fine-grained calculations, even across year boundary, possibly combined with more "calendar-like" conditions  (month, day) if need be.

**Comment by jostephd** [comment]
> For example, say you have a mission that you want to have offer between February 13th and April 20th. The offer conditions for just this date range would be the following:

Couldn't you do it already like this?

```
to offer
	"month" * 100 + "days" >= 213
	"month" * 100 + "days" <= 420
```

**Comment by jostephd** [comment]
> To record dates for one-shot missions like in [#6550](https://github.com/endless-sky/endless-sky/pull/6550#discussion_r806596147) , another auto-generated condition could be an "epoch" (number of days since the start of the game).
> The recorded dates would be more compact and allow fine-grained calculations, even across year boundary, possibly combined with more "calendar-like" conditions (month, day) if need be.

:+1: 

Thinking of this, do we allow missions to change the date? Like, can a mission do `"year" -= 10` if the mission's story involves time travel 10 years into the past? If someone ever wants to do this, at that point we might need two conditions, one for "number of days since epoch" and one for "number of take-offs since this pilot was created", I suppose?

I'm overengineering, yes :laughing:

**Comment by DownsB** [comment]
> Couldn't you do it already like this?
> ```
> to offer
> 	"month" * 100 + "day" >= 213
> 	"month" * 100 + "day" <= 420
> ```

Indeed you can!
That may be the easiest way to go...

I also tried the year-=10 trick, and it worked (in the save file). But I was not equipped with those fancy devices sold by Pug outfitters, and the next day I was back to current time.
ES is not yet ready for time travel!

**Comment by jostephd** [comment]
> I also tried the year-=10 trick, and it worked (in the save file). But I was not equipped with those fancy devices sold by Pug outfitters, and the next day I was back to current time.
> ES is not yet ready for time travel!

#6567

**Comment by Amazinite** [comment]
> Couldn't you do it already like this?

That works until you want to measure an arbitrary difference in the number of days as opposed to two fixed dates (as seen in #6626), as months don't all have the same number of days.

**Comment by jostephd** [comment]
Adding an "epoch" condition that increases by 1 every day, as suggested by @DownsB, would make this possible, wouldn't it?

**Comment by eebop** [comment]
It would be best to just not have leap days as leap days can causes bugs without any sort of reward (and it would make sense to standardize the year to 365 days after people don't only live on earth).

**Comment by warp-core** [comment]
1c52f95
