### ISSUE TITLE
Merganser first flight: Dredger leaves Farnius and mission pointer doesn't update

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#6558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While playing the Merganser first flight, we were headed to Farnius (where the marker and description pointed us). We encountered the dredger in Cinxia and destroyed it. The dredger was marked as the mission objective and the dialogue box said to return to Viminal. I had to bounty missions at the time. The mission marker stayed at Farnius. I returned to Viminal and landed and the job stayed active in my job list. Checking the spaceport, I got the standard messages. I departed, and the merganser flight flew with me. We passed through Farnius, which was empty, and returned to Viminal. When I landed, the mission dialogue continued.

### Steps to Reproduce

This will be tricky to reproduce as it depends on the dredger's behaviour. 

### Expected Behavior

I expected that the dredger would be in Farnius, as with marauder bounties, as the system was specified. Failing that, I would expect the mission to status to be tied to destroying the dredger rather than entering the system, particularly since the 'destroyed raider' dialog box tells me to return to Viminal. 

### Operating System

Manjaro Linux/MacOS

### Game Source

ESLauncher2

### Game Version

b2d6798a791c5a5da650c3b4bc54e14bf5167d26

**Comment by McloughlinGuy** [comment]
Yeah, encountered the same bug. The dredger should have the staying personality, but it doesn’t seem to. Might try to fix this.

**Comment by warp-core** [comment]
Fixed by #6905.
