### ISSUE TITLE
Let projectiles make sound while in-flight

### ISSUE THREAD

**Issue by ghost** [endless-sky/endless-sky#656]
I think that projectiles need to have sounds attached to them, like a missle making a quiet swooshing noise and torpedos/typhoons making a low humming sound. Also, projectiles need explosion sounds, like a faint explosion noise when it is tapped down by an anti-missle turret or when it hits a ship. Blaster weapons and laser weapons need to make an impact sound, like the ion cannon.

**Comment by DingusShingleton** [comment]
For what it's worth, NASA has a large repository of audio that is free to use, might come in handy for this or other sound needs. 

This article has all the relevant links 
http://createdigitalmusic.com/2014/10/nasa-posts-huge-library-space-sounds-youre-free-use/

**Comment by Wrzlprnft** [comment]
Depends on how noisy fights should be in the end.

**Comment by tehhowch** [comment]
It wasn't made explicitly clear here, but the game already supports in-flight projectile noises - just add a [**sound**](https://github.com/endless-sky/endless-sky/wiki/CreatingEffects) to a projectile's `"live effect"`, and when the effect is generated in-game, the sound will be played.

Effect usage (as a part of moving the projectile):
https://github.com/endless-sky/endless-sky/blob/d6b92f48810c4b36f109e8e49e1e29e5a9f34d6d/source/Projectile.cpp#L123-L125

Visual's constructor (called by the above):
https://github.com/endless-sky/endless-sky/blob/d6b92f48810c4b36f109e8e49e1e29e5a9f34d6d/source/Visual.cpp#L35-L36

The same applies for the other requests here too - add sounds to the relevant `die effect` and `hit effect` definitions, and they'll play when the effect is created.

**Comment by monticore162** [comment]
heavy rockets need a katyusha rocket sound effect.

**Comment by CaptKrevor** [comment]
Sorry, but, if no one can hear you scream in space.......

Sound effects are only logical intra-atmo.

**Comment by quyykk** [comment]
As mentioned by tehhowch, this is already possible!
