### ISSUE TITLE
Improvements to info menu

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#6564]
### Problem Description

It's very difficult to go around and click on individual ships you want to unpark/park, and then move your mouse all the way down to the unpark/park button in the menu. Because of this, I have devised a couple hotkeys and a new button that will make the info menu easier to navigate. I created this issue because I was unable to bring a lot of my fleet to do the wanderer storyline, and I was annoyed when I had to individually park and unpark all of my ships to avoid my other ships I had stored trying to come to me, especially when I left part of my fleet in hai space to go kill the alpha carrier.

### Related Issue Links

#735 sounds similar, honestly I'm not entirely sure what the person who wrote it was asking.
#2195 is also similar. The feature was added so not sure why it's still open.

### Desired Solution

Two hotkeys: P to park a selected ship, U to unpark a selected ship (or just let P unpark and park ships, depending on whether or not they are parked or unparked. If it is parked, P will unpark it, and if it is unparked, P will park it.). This way you don't have to move your mouse all the way down to the unpark button. I also think there should be a new button which allows you to unpark all ships in the current system/planet. That way if you left part of your fleet on one planet, and another part on another planet, you can unpark just that one part and not have to deal with all of your other ships you don't want to use at the moment trying to join you. I also thank the normal park/unpark all should be hotkeyed, maybe Shift + A or something, a for All.

### Alternative Approaches

The button which allows you to unpark all the ships on the system/planet you are in could be a hotkey rather than a button. If it was a button you would also need a hotkey for it, maybe Alt + P to park all the ships in the system and Alt + U to unpark ships in the system. Or just Alt + P to unpark/park, P as in planet.

### Additional Context

Nothing else I would like to say.

**Comment by McloughlinGuy** [comment]
> 'Shift - a' toggles all ships between parked/unparked and 'Shift - p' toggles the selected ship(s).

Thanks for pointing that out. I think that having to press shift shouldn't be necessary though.

**Comment by Amazinite** [comment]
As pointed out, you can already park/unpark all with a hotkey. You can also ctrl+click on ships to select multiple ships at once, or shift+click on ships to select all ships between two points, instead of needing to individually click on and unpark each ship. And with sorting in the ship info panel now a thing, you could sort your ships by the system they're in and shift+click the first and last ship in the system of choice to select and park or unpark them all.
