### ISSUE TITLE
Sprites for Quarg and Pug outfits

### ISSUE THREAD

**Issue by ghost** [endless-sky/endless-sky#657]
Could outfit sprites For pug, Korath, and Quarg ships be made? I would really like to see what they would look like. Quarg would be all sleek and shiny, Korath would look overexessive, but really cool, and Pug would have lots of wires and would have three claw-shaped prongs at the end of each of their weapons. I really hope this gets added as just looking at question marks on most of my ships kind of reduses asthetic effect.

**Comment by Wrzlprnft** [comment]
@endless-sky if you have already any ideas or sketches or whatever, could you tell us?

**Comment by Gkramme** [comment]
I've got a few cool ideas, but i can only sketch them.

**Comment by Wrzlprnft** [comment]
I could try to model them, but that would probably fit better in the google group

**Comment by endless-sky** [comment]
Working on [Korath](https://github.com/endless-sky/endless-sky-high-dpi/commit/40b929d80ffbdb341b2b5f8e6c612a9aac194772) [outfits](https://github.com/endless-sky/endless-sky-high-dpi/commit/f8b24de8e1598252b0a5a9f0ca8de2f2777ba3cb) right now for inclusion in 0.9.0.

**Comment by Pointedstick** [comment]
Done now.
