### ISSUE TITLE
[Bug] If an outfit reduces required crew to 1 (the player), the game still charges crew wages of 100

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#6578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Flying a solo ship:
If the required crew is 1, then the game does not charge a crew wage.
If the required crew is >2, then the game charges a crew wage equal to the required crew,
If the required crew is >2, and using an outfit such as the "NDR-114 Android" to reduced required crew down to 1, then the game charges a crew wage equal to 1.

Digging into this a bit more, it seems that if a flagship has a crew of 1, then that is the player's pilot. If the flagship has a base required crew of more than 2, then on launch the game adds +1 to the total crew of the ship on launch. Unless the bunks are full, in which case the total crew remains at max bunks.

In this picture both Starlings are stock, but the one that is acting as flagship has +1 crew over the other one.
![Captain is counted](https://user-images.githubusercontent.com/32169904/155849874-c45f0141-7ef5-4ab0-8e6b-255a1cf6beda.PNG)

I'm not sure if the "sometimes add the player's pilot as an additional person, sometimes don't" is desireable behavior. The bug, however, is that if a ship's required crew is decreased down to 1 using outfits, I would expect that it would now fall into the first category, where that single required crew is the player.

Worth noting that, when buying androids to reduce the required crew, the player can actually buy enough to reduce the required crew to 0, but the display continues to list 1 required crew. This matches the Android's description of them still needing a captain. If one does buy enough to reduce the minimum crew down to 0, then the ship's crew after launch will be 1, but no wages will be charged for that crew.

### Steps to Reproduce

1. Buy a ship with a single required crew. Launch, and see that the ship still has just a single crew.
2. Buy a ship with >2 required crew. Launch, and see that the ship's total crew has increased by 1.
3. Buy a ship with >2 required crew, then add "NDR-114 Android" to bring the required crew down to 1.
4. Launch, and see that the ship's crew complement has increased to 2.

Note: I don't actually know exactly where the cutoff is, as I haven't tried finding ships with exactly 3, 4, or 5 required crew. I just know that there is no +1 crew on the shuttle (1 required) or Petrel (required 2); but there *is* an extra +1 crew on Starlings (required 6) and anything larger than that.

### Expected Behavior

That when the ship's required crew is reduced to 1, that single crew will be the player's pilot; as per the normal behavior when the player flies a ship with only 1 or 2 required crew.

### Operating System

Windows 10 Pro

### Game Source

GitHub Releases

### Game Version

9f91615 (2022-Feb-26)

**Comment by quyykk** [comment]
> Buy a ship with >2 required crew. Launch, and see that the ship's total crew has increased by 1.

Am I doing something wrong? This is in-flight with 2 stock Gulls.

![zitchas-crew-bug](https://user-images.githubusercontent.com/85879619/156594029-1b032efa-9047-4bea-b1be-bfa31fc2ff10.png)

Same thing if I buy 2 stock Starlings (both have 6 crew).

**Comment by Zitchas** [comment]
Interesting. And odd.
