### ISSUE TITLE
Ship bug after being repaired.

### ISSUE THREAD

**Issue by masterpierround** [endless-sky/endless-sky#659]
After you repair a disabled ai ship, it goes back to a planet to repair. Then, it gets stuck in an infinite (I think, although I've not watched it for >10 minutes) loop of landing and taking off again. It's not a big issue since it doesn't really affect gameplay that much, but it is a weird thing to see.

**Comment by mrec** [comment]
Do pirates ever plunder outfits from ships? If they'd pinched the hyperdrive then this could be #710 again.

**Comment by endless-sky** [comment]
Was the ship a drone or fighter? If so, this is fixed by commit f48ec26.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
