### ISSUE TITLE
Remnant Quarg visit chooses Esqualine as a desination and can't be completed without a gaslined ship

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#6594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is in regards to "Remnant: Expanded Horizons Quarg 3". On completing the mission in Tarazed, I was instructed to take the team of researcher to Esqualine. This will require a gaslined ship to complete. At present, I have a puffin and a penguin and neither has the capacity for 3 passengers.

### Steps to Reproduce

There was no user input in the destination planet selection. 

### Expected Behavior

I expected the destination to be one of the inhabited Remnant systems accessible by normal ships. As it stands, only gaslined ship guaranteed to be available to the player is the puffin, which doesn't have sufficient passenger capacity to complete the job.

### Screenshots

![Screenshot_2022-03-09_20-59-50](https://user-images.githubusercontent.com/70952724/157548904-3039ff87-3faa-4bf9-b202-ccb91a84576b.png)
![Screenshot_2022-03-09_21-53-38](https://user-images.githubusercontent.com/70952724/157548931-d70cc423-7749-41a7-b7f4-87a6cb870f17.png)

### Link to save file

[Trevor  Christianson.txt](https://github.com/endless-sky/endless-sky/files/8218619/Trevor.Christianson.txt)

### Operating System

Linux EmberWastrel-8088i 5.16.11-2-MANJARO #1 SMP PREEMPT Fri Feb 25 11:27:31 UTC 2022 x86_64 GNU/Linux

### Game Source

ESLauncher2

### Game Version

Endless Sky commit 898df94cf1bccc6b523cc126838cd2308f59ef3c

**Comment by williaji** [comment]
I've duplicated this issue with another pilot. Entirely by accident, of course. 
![Screenshot_2022-03-18_15-44-33](https://user-images.githubusercontent.com/70952724/159036092-396217ae-fdc2-47c3-b7c9-3ccbc6312dc9.png)
[Johnny  NoLicense.txt](https://github.com/endless-sky/endless-sky/files/8305901/Johnny.NoLicense.txt)

**Comment by pepoluan** [comment]
I forgot, how many passengers to carry in that mission chain?

If 1 or 2, then the mission chain needs to be locked until player gets the Penguin or Merganser.

But I much prefer the mission chain to just exclude gas planets. Because not all people will get the Penguin if they opt for the Void Rifle...

**Comment by williaji** [comment]
There are 3 passengers with this mission. It cannot be completed with the Puffin or Penguin.  I hit it again today, so that make 3 for me personally, I'm not sure why it's listed as 'unconfirmed.' This was on continuous updated within 3 days.
![Screenshot_2022-08-07_11-28-04](https://user-images.githubusercontent.com/70952724/183290501-14045298-0977-44c7-b67d-ad3995b758c2.png)

**Comment by Zitchas** [comment]
That's surprisingly out-of-sequence to get the initial Dawn mission *after* esquiline is a known station.

But obviously still a possibility. I'll work something out.
