### ISSUE TITLE
Visual elements appear / disappear while on screen

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#6603]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Sometimes the background haze or the colored outline of a planet appears or disappears while on screen. This might also happen for other assets, however asteroids, ships, planets seem to render just fine.

This usually happens around the edges, with the innermost part of the visuals being up to a couple hundred pixels inside the screen. The planet outline seems to fade normally, but then just disappears before it is completely transparent.

The issue seems to occur with both minimum and maximum zoom, however it is far more common when fully zoomed in.

### Steps to Reproduce

1. Fly around systems
2. Observe

Honestly, I'm not sure how easy this issue is to reproduce; using this exact version of ES on the same hardware using Windows did not produce this issue, but I'll do some further testing to make sure.

### Expected Behavior

Well, I didn't expect objects to just randomly disappear from the screen tbh. 

### Screenshots

![Planet outline showing (kinda bad example)](https://user-images.githubusercontent.com/68112292/158163646-0bf0c7ef-c868-4b19-a8f4-d3d9ca8d95ea.png)
![Planet outline not showing (kinda bad example)](https://user-images.githubusercontent.com/68112292/158163654-e31f948b-12ee-480c-89f3-123a7e983cf9.png)
![Haze showing](https://user-images.githubusercontent.com/68112292/158167976-db2eeb48-92ac-4282-984f-fecc3c804dcb.png)
![Haze not showing](https://user-images.githubusercontent.com/68112292/158167983-cbf014a3-e5c1-4bcf-b428-2ea8c8282df9.png)
The starts highlighted with the red circle are the same stars on both image. The screenshots were taken ~ 2 seconds apart.

### Link to save file

This issue is independent of the save file used.

### Operating System

Ubuntu 20.04 LTS

### Game Source

ESLauncher2

### Game Version

v0.9.14

### Additional Information

Screen resolution: 1280x1024 (5:4), 75 Hz
<details>
 <summary>OpenGL version: 4.6</summary>

- server glx version string: 1.4
- client glx version string: 1.4
- GLX version: 1.4
- OpenGL core profile version string: 4.6.14800 Core Profile Context 21.50
- OpenGL core profile shading language version string: 4.60
- OpenGL version string: 4.6.14800 Compatibility Profile Context 21.50
- OpenGL shading language version string: 4.60
- OpenGL ES profile version string: 4.6.14800 Compatibility Profile Context 21.50
- OpenGL ES profile shading language version string: 4.60

</details>

GPU: Radeon RX 750 series

**Comment by Amazinite** [comment]
Haze culling early was an issue because it would disappear instantly upon passing a certain distance from the haze center. But I see zero issue with the planet markers disappearing before the planet is fully off screen, as the planet markers actually fade out the further away you get from the planet.

**Comment by tibetiroka** [comment]
> I see zero issue with the planet markers disappearing before the planet is fully off screen, as the planet markers actually fade out the further away you get from the planet.

Yes, they should fade out. However, I wrote
>  The planet outline seems to fade normally, but then just disappears before it is completely transparent.

Basically, they start to fade out, but they don't fade out completely; instead, they just disappear. It is difficult to show on images only.

**Comment by tibetiroka** [comment]
The fog seems to be working fine in the continuous build.

**Comment by Amazinite** [comment]
@Terin Sounds like the same root cause as the haze culling. Might want to take a look at the planet labels too to see if you spot anything.
