### ISSUE TITLE
[Feature] Add fighter launch definitions to all ships

### ISSUE THREAD

**Issue by Saugia** [endless-sky/endless-sky#6608]
### Problem Description

Currently, Carriers & Cruisers and similar bay ships (Aerie) have a fighter bay launch effect (smoke), which is defined in effects.txt, but the actual implementation of the effect seems to be hard coded. The effect can be edited to have a sound, and it's possible to change the effect's graphic reference so it can be something else other than the smoke effect. However, these ships seem to be the only ones with this editability. 

Part of what was prominent in older Escape Velocity games was having different fighter launch sounds to denote what carried ship was launched and by what faction. Not only were they just sounds, but to the player they could be a sign of warning before even seeing the ship that launched them, or the opposite where the player is excited a carrier is in the system they just took off in/jumped into.

A fighter launch sound adds another layer of interaction in combat- if a missile exiting a hardpoint makes a sound, it would make sense design-wise if a fighter were to also. Having this sort of editability would be great for content creators and possibly vanilla as well. 

### Related Issue Links

There doesn't seem to be any issues referencing fighter sounds. 

### Desired Solution

I personally am not fluent in code at all, so I don't know of a very specific way to go about this, if the code is able to (and if it doesn't significantly affect the rest of the code):

Allow ships to have a "bay launch" line in their code that references an effect (which in turn would reference a sound). This would move the hard coded bay effect to the ship files and allow further customization of ships while not hurting any sort of combat balance or other values. Purely cosmetic. 

### Alternative Approaches

An alternative approach could be to give every carrier ship in the game the same hard code the human bay ships have so any carrier ships could have a launch effect. For example, the human ships have the de-pressurization, but ships such as the haulers and korath ships could have an invisible effect that could be changed later on, and given some sort of "detach" sound.

**Comment by quyykk** [comment]
> but the actual implementation of the effect seems to be hard coded.

If there is no effect specified then the `"basic launch"` effect is used. However, you can use `"launch effect"` to change it:

```
bay ...
    "launch effect" something
```

So I think the feature you request already exists.
