### ISSUE TITLE
Proposal: Code optimization while compile

### ISSUE THREAD

**Issue by mdziczkowski** [endless-sky/endless-sky#6612]
### Problem Description

I would like to propose to optimise the code for speed and size while the compilation process. In the "Desired solution" are example compilator flags that could help with it.

**Note**: Because the mentioned will enable more optimization flags, the other ones won't be listed

### Related Issue Links

none

### Desired Solution

CFLAGS="-O3 -Os -pipe"

The mentioned bellow flags need to be referenced to the CFLAGS listed above:

CPPFLAGS, CXXFLAGS, GPPFLAGS, GXXFLAGS, GFLAGS

### Alternative Approaches

none

### Additional Context

Explanation of the used flags parameters:

-O3 : optimise for speed
-Os : optimise for small size
-pipe : optimise for speed thru pararell compilation

**Comment by quyykk** [comment]
It's not possible to specify both O3 and Os. It's either one or the other. This is a game, so speed is more important than size.

I've never heard of -pipe but it seems like it doesn't make much of a difference for smallish projects (and apparently 5 years ago it was buggy, don't know of that is still accurate).

**Comment by MCOfficer** [comment]
> It's not possible to specify both O3 and Os. It's either one or the other. This is a game, so speed is more important than size.


FWIW -O3 should be the default in release mode:

https://github.com/endless-sky/endless-sky/blob/749fe9ba85484e78b3e3f1a580fec02216a2e10d/SConstruct#L54-L56

**Comment by mdziczkowski** [comment]
@quyykk:

> It's not possible to specify both O3 and Os. It's either one or the other. This is a game, so speed is more important than size.

Try to check if your like compillers (c++, g++, etc.), linkers, etc. does not need an update to the latest version, because under the one I use on my Linux (based on Debian 11), it works fine ;-)

> I've never heard of -pipe but it seems like it doesn't make much of a difference for smallish projects (and apparently 5 years ago it was buggy, don't know of that is still accurate).

I allow myself disagree in this one as well because I use it even in bigger projects and it fasten up the compilation process in compare to the one without this parameter

**Comment by quyykk** [comment]
Yeah it works, but the compiler uses the last flag and not both. It's the same if you specify `-O0 -O3`; only -O3 will get used, not both.
