### ISSUE TITLE
Feature Request: Allow plugin to see if another plugin is installed.

### ISSUE THREAD

**Issue by 1010todd** [endless-sky/endless-sky#6617]
### Problem Description

Right now ability for plugin to support each other is very limited. One of the problem is there's no way to detect if the other plugin is installed or not. 

Example for the use includes:
* Using other plugin ships in fleets.
* Adding other plugin ships to shipyard.
* Using outfits from other plugins.

### Related Issue Links

Short conversation on Discord:

https://discord.com/channels/251118043411775489/266345072554016768/953650077015097355

### Desired Solution

Allowing plugin to identify itself in about.txt with something like `"plugin id" <plugin name>` which the game would read and generate condition from. Then other plugin can create mission to check for these conditions and do their things. Obviously the condition should be removed when plugin is uninstalled.

### Alternative Approaches

Generate id from folder name if the `"plugin id"` doesn't exist, however as mentioned by Amazinite on Discord people can rename the folders for various reason. So it may or may not actually work. 

Checking if specific ship or outfit exist as mentioned by Hector on Discord could partially help. There is possibility plugins can attempt to add ships with the same name which can cause false positive. Also not sure how difficult it would be to make this and if generated as condition this might bloat the save file as there are plugins that add hundreds of ships.

**Comment by tehhowch** [comment]
I don't think conditions are the way forward here. The game will eventually compose definitions _before_ loading a pilot instance, and will be able to identify "content races" where multiple plugins want to modify the same identifier. In that light, adding "runtime" checks doesn't make sense.

There's an issue or two around here with some comments on this matter of load-time compatibility checking.

**Comment by pepoluan** [comment]
The way I see it there are 2 subfeatures here:

1. Plugin dependency -- if a plugin really needs another plugin, the dependency should be listed, and game will just not load plugins whose depedency(-ies) are not met

2. Plugin detection -- if a plugin _optionally_ needs another plugin, say to customize conversation text / requisites, then there should be something like "if_has_plugin <plugin_name>"

**Comment by 1010todd** [comment]
Solved by https://github.com/endless-sky/endless-sky/pull/9076
