### ISSUE TITLE
Auto turn during landing and jump

### ISSUE THREAD

**Issue by Nixxen** [endless-sky/endless-sky#662]
The auto turn / orientation of the ship before jump and landing sometimes turns the ship the wrong way.
For example (these numbers are made up and is for illustration); 0 deg is right. You are facing 90 deg(up), landing is 45 deg(roughly up/right). Instead of turning 45 deg clockwise,  the ship spins counterclockwise 315 deg. 

On faster ships this won't be as noticeable, but on haulers it can be the difference of making the jump or getting ganged.

**Comment by Gkramme** [comment]
True. It's happened to me many times

**Comment by endless-sky** [comment]
Are you sure that it isn't just because you have a scram drive, and it's
turning in a certain direction in order to match your velocity to the jump
vector?

Also, is this something you only see with very slow ships? I haven't seen
it myself, but I tend to fly more maneuverable ships.

**Comment by Gkramme** [comment]
@endless-sky, yes that may be it. I have a bac with enough reverse thrusters to slow down the ship, and align itself for hyperspace travel, but the less powerful thrusters do it in more time. The only time they are used are when landing, using a jump drive, and during the inital jump (when taking off from a planet). Is this because I have a scam drive?

**Comment by Nixxen** [comment]
There is a scram drive on the ship, but if I let the ship drift and realign it manually before jumping it never (at least the times I've tested) does the "long way turn". It still sometimes does some course and thrust corrections to fix the speed, but never a full rotation. This could be just coincidence, since I have not been testing it for a very long time (bought a new freighter). 

Most of the time it does turn the right way. Makes the burn and turns back. The times it doesn't turn the "right way" it either goes the longest way to the burn direction or after the burn direction (instead of turning back to the jump direction it continues to spin)

**Comment by endless-sky** [comment]
I'm pretty sure the only time this happens is if you're taking weapons fire that accelerates your ship (so that your ship has to keep trying to steer to slow itself to a stop, again). I've never seen this happen in other circumstances.

**Comment by jafdy** [comment]
I have some times had half my fleet turn one way to slow down and the other half turn the other. one group must be going the long way as half my fleet is ready before the other half.
