### ISSUE TITLE
Add cost to remove outfits

### ISSUE THREAD

**Issue by GefullteTaubenbrust2** [endless-sky/endless-sky#6623]
### Problem Description

Negative cost for outfits right now is very illogical. The game straight up does not allow NPCs to even have such outfits, and they can just be put in cargo or storage, avoiding the cost of selling them altogether.

### Related Issue Links

None found

### Desired Solution

So instead, we could add a "Cost to remove" statistic, that is entirely separate from cost. This would strictly be the cost for removing an outfit from the outfit space and would have to be paid even when moving these outfits into cargo or storage. It would allow for mulitple mechanics:

- For one, there could be outfits useful outfits that are "hard-wired" into the ship, so that removing them would come at a cost. This would make installing or removing such outfits a more permanent decision. It would also allow us to limit how readily the player can just change every aspect of a ship's default outfits, especially for ships like the Emerald Sword that are obtained in missions. Maybe the ship you just got has an amazing outfit, but moving it to your other ships would be very expensive.

- But also, there could be outfits that are actively harmful to the player, like maybe they would decrease shield power. Then ridding your ship of these burdens would come at a cost, that you have to be able to pay. Such outfits would probably best find use in missions and i can imagine many ways they could come in handy.

### Alternative Approaches

Of course, to some extent the issues i mentioned can be mitigated by just removing some of the restrictions around negative cost. Why should NPCs not be able to carry outfits with negative cost? Just remove that limitation. Then again, that still would not fix the fact that such outfits could still be moved to cargo or storage.

**Comment by JanErikAhrens** [comment]
Works now. I don't know man github is being very weird today.

**Comment by Amazinite** [comment]
Expanding upon my comment from https://github.com/endless-sky/endless-sky/pull/8700#issuecomment-1627641650, while such attributes would allow for the two examples provided, I feel like these examples aren't very fitting with the game's spirit of customization. The second example is practically a "[curse of binding](https://minecraft.fandom.com/wiki/Curse_of_Binding)"-like effect that sounds like it'd just result in a negative gameplay experience.
