### ISSUE TITLE
Allow Heavy Shuttle to use reverse thrusters: increase weapon capacity from 15 to 16

### ISSUE THREAD

**Issue by 3519421** [endless-sky/endless-sky#6624]
### Problem Description

The addition of ion and plasma reverse thrusters has made reversing a viable option for small commercial ships. Using weapons space instead of engines has created a strange early-game situation: a converted Star Barge has almost as much capacity as a Shuttle, and much better performance (faster hyperspace cycle time, lower energy requirements), trading off against a higher cost and more effort outfitting it.

Right now a Heavy Shuttle still has the edge in maximum capacity (especially with the recent tweaks), but it's slower and more expensive. Allowing it to use the smallest (ion) reverse thruster would give it better performance than either starter ship without sacrificing much carrying capacity.

### Related Issue Links

Tangentially related: Autopilot/Escort AI doesn't know how to handle ships with reverse thrusters and no standard thrusters in some situations, sometimes even causing the ship to disappear from the map (including the player's flagship, requiring a restart).

https://github.com/endless-sky/endless-sky/issues/6604

### Desired Solution

Increasing the weapons capacity from 15 tons to 16 tons would allow the Heavy Shuttle to use reverse thrust, with minimum impact on balance. It looks like the only other effect would be allowing both gun ports to be used with Gatling Guns, Beam Lasers, and/or Torpedo Pods (right now it's a maximum of one of those and a Modified Blaster), but since it can already mount a Heavy Laser, this seems like a small change.

### Alternative Approaches

Another option would be to make the reverse thrusters use a smaller fraction of its total outfit size in the weapons category, similar to some Remnant and Ka'het outfits. This would also allow smaller ships (particularly Interceptors) to use both reverse thrust and larger weapons, which may be disruptive (positive or negative) to current combat balancing.

### Additional Context

![S1647531569](https://user-images.githubusercontent.com/101584135/158838762-89e694e7-2aae-485d-a803-ce426e7a65d7.png)

![S1647531582](https://user-images.githubusercontent.com/101584135/158838807-3db3680f-6e89-44b6-a9a5-9cffba5c2a38.png)

![S1647531592](https://user-images.githubusercontent.com/101584135/158839573-699f67f8-bd79-4fbd-a49f-86616942e307.png)

**Comment by Zitchas** [comment]
As per the PR I just made to resolve this, I think the idea of making the weakest two thrusters in the game slightly better is a bigger improvement to the game than tweaking the Heavy Shuttle directly. As you say, with a slightly smaller reverse thruster, it may enable other ships to have small amounts of reverse thrust, and I think increasing options in this regard is a good thing.

**Comment by 3519421** [comment]
Ah, that is a nice alternative. I wasn't sure messing with a standard human engine's stats was on the table, but this change has already made several other starter-level small ship builds I had considered (and rejected) viable.
