### ISSUE TITLE
The ships:<category> condition is ambiguous.

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#6628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The ES Wiki describes the following for the `"ships: <category>"` conditions:
```
"ships: <category>" is the number of ships you have of each category (Transport, Light Freighter, Heavy Freighter, Interceptor, Light Warship, Heavy Warship, Fighter, Drone).
```
But the current code for calculating the "ships: <category>" condition doesn't count parked and disabled ships, and it doesn't count out-of-system ships. (It currently also doesn't count loaded fighters when the automatic conditions are calculated after fighter loading.)

### Steps to Reproduce

1. Look at [the wiki](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#conditions) to see what was specified.
2. Check what was [implemented](https://github.com/endless-sky/endless-sky/blob/2380cdfd9b4aae12ef9976dbab0f15b0a2649b6a/source/PlayerInfo.cpp#L2617).

### Expected Behavior

Not counting fighters seems wrong, so the minimal fix should be to also count loaded fighters.

My suggestion would be to keep `"ships: <category>"` for "Only active (non-disabled, non-parked) in-system ships" and update the Wiki to reflect this. The conditions are used by missions and I would expect most mission-writers to only be interested in active in-system ships.

We can also consider to add the following conditions to the game (to allow mission-writers to also act on such conditions and combinations of them):
- `"fleet: <category"` All active ships of the given category anywhere. Including non-disabled parked ships, excluding disabled ships.
- `"parked: <category"` All parked ship of the given category anywhere. Excluding disabled parked ships.
- `"disabled: <category"` All disabled ships of the given category anywhere. Including parked disabled ships.

This set of conditions would not allow missions to query for locally parked ships or locally disabled ships, but I don't know if that is desired for content creators. (And they currently also don't have the option for such ships.)

### Link to save file

The test in https://github.com/endless-sky/endless-sky/pull/6291 comes with a save file, but I expect the complete test to be more useful than the save file by itself.

### Operating System

Not relevant for this issue

### Game Source

Built from source

### Game Version

2380cdfd9b4aae12ef9976dbab0f15b0a2649b6a

### Additional Information

The implementation of [on demand conditions](https://github.com/endless-sky/endless-sky/pull/5244) would also be affected by the ambiguity.

**Comment by Amazinite** [comment]
Updated the wiki to specify that the "ships" condition only checks a subset of ships, and added new information about the conditions from #7210.

**Comment by petervdmeer** [comment]
The Wiki update is incomplete, since both https://github.com/endless-sky/endless-sky/wiki/Player-Conditions and https://github.com/endless-sky/endless-sky/wiki/CreatingMissions refer to the `"ships: <category>"` section.

I'm also not seeing any reference to a fix that ensures that fighters are properly counted. Maybe I just missed the update that fixed fighter counting, but it looks to me that some work is still open.

**Comment by Amazinite** [comment]
>The Wiki update is incomplete, since both https://github.com/endless-sky/endless-sky/wiki/Player-Conditions and https://github.com/endless-sky/endless-sky/wiki/CreatingMissions refer to the `"ships: <category>"` section.

The missions page should probably only point to the conditions page instead of duplication info. I'll touch it up.

> I'm also not seeing any reference to a fix that ensures that fighters are properly counted. Maybe I just missed the update that fixed fighter counting, but it looks to me that some work is still open.

That was addressed by creating the GetActualSystem function in Ship and calling that instead of the normal GetSystem function.

**Comment by petervdmeer** [comment]
Cool, then I'm fine with having this ticket closed.
