### ISSUE TITLE
Storylines, storylines.

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#663]
I think the next update should be focused on bugfixes and starting up a syndicate and navy storyline. This game has so much content, but it just needs to have more storyline!!! I would like to join the navy and the syndicate, scince all my captians are part of the free worlds.

**Comment by Pointedstick** [comment]
I'm currently working on a Syndicate storyline.

**Comment by Gkramme** [comment]
@Pointedstick That sounds great! Im excited to see the finished product!

**Comment by BuildBruh** [comment]
Didn't he say that .9 was going to be a bunch of 'stable' updates introducing and fleshing out missions. Or am i remembering incorrectly.

**Comment by Wrzlprnft** [comment]
I am working on a republic storyline, but at the moment i am just collecting ideas, mine, others, and so on and so forth
In a month, after studysuff and exams are hopefully over, ill try to produce first real results

**Comment by Gkramme** [comment]
@BuildBruh Yea, I would just like to see more storylines before more content.

**Comment by jamaican117** [comment]
While the overarching new storylines will be very fun to play, I'd love to see more side quests like the Deep Archeology mission. That series of missions really blew me away with how the bad guys chased me, and it was genuinely exciting to run away because I was outgunned. Thought stuff like that really fleshes the universe out and is interesting to explore.

**Comment by endless-sky** [comment]
The goal of the 0.9 series is indeed to flesh out other story lines, but I'm closing this particular issue because it doesn't represent the sort of limited, concrete change request that works in the issue list - i.e. no matter how much story is added, there will always be a need for more.
