### ISSUE TITLE
Getting a bactrian causes ALL hyperdrives to vanish

### ISSUE THREAD

**Issue by feyone** [endless-sky/endless-sky#6631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I just got the world ship licence and went to an outfitter to shift my jump drive from my dual drive Behemoth (Scram drive AND Jump drive) to the Bactrian, only to find when I enter the outfitter, NO hyper drives of any sort are visible on either ship OR in the outfitters (even though they are supposed to sell them according to the outfitter map).
I opened a (much, like 5 days) earlier save, and the drives appear as expected.

In existing issues, I found something similar but it dated from 2015.  If have played the game right through 5 of 6 times, but this is the first time this has happened to me.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Hyperdrives, Scram drives and Jump drives to appear in the ships they are fitted in when in an outfitter

I am running this from Steam = steam://rungameid/404410

### Screenshots

![Bactrian](https://user-images.githubusercontent.com/13388315/159120144-6fcad979-03b8-4fde-a82b-1a40e9066420.jpg)

### Operating System

Windows 10 Pro, Vers. 21H2, Build 19044.1586

### Game Source

Steam

### Game Version

0.9.12

**Comment by feyone** [comment]
When I look at the ship info - the drives are there, but ships don't use them, they default to operating as if a standard hyperdrive is fitted.

**Comment by quyykk** [comment]
Could you post the problem save file here? That would greatly help.

**Comment by tehhowch** [comment]
Your screenshot shows the "System" section of the outfitter is "collapsed". Is that the issue? You can click that caret to reopen the section.
