### ISSUE TITLE
Launching the game without a pilot loaded doesn't play docking sound

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#6635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the game launches and there isn't a pilot loaded, the "docking" sound won't play after loading finishes.

### Steps to Reproduce

1. Load a pilot
2. Delete the pilot
3. Restart the game

### Expected Behavior

There shouldn't be any inconsistencies in when the landing sound plays and doesn't on the main menu.

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

9c3d02cc143848574546143ce45e6d412e3e8e69

**Comment by tehhowch** [comment]
Is it not perhaps a bug in the other direction? Why should we play the landing sound just because there was also a pilot to load?

**Comment by tehhowch** [comment]
That was kinda what I expected to hear. What's really warranted is 1) loading sounds; 2) a change to the sounds when loading is done; 3) another change to the sounds when the player takes action. Most games have title music that would qualify, along with optimal audio feedback when using menus.

In that world I would really expect a short, loopable tune (perhaps baked into the binary to ensure availability during load, or with a two-stage load) played by the game loading panel and then a transition to title music whenever the menu panel is up. For those with music turned off, we could play a sound in the animating panel that we add to contain the "shrinking progress circle." Maybe we use the landing sound there now, maybe we change it in the future.

**Comment by quyykk** [comment]
Sure that works. On the other hand, I actually quite like the current behavior that the title screen is customized based on the planet/system you're on (haze + planet music).

So I think we should still fix this for consistency; if/when we change the title screen sounds/music we can change this behavior.
