### ISSUE TITLE
Menganser/Remnant Lab are abnormally dark

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#6638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The sprites for the Merganser and the Research Laboratory are abnormally dark. See the attached images to see what I mean. This darkness appears to be the result of having the images stored in a 64 bit colour profile, instead of the 32 bit the rest of the game uses.

### Steps to Reproduce

N/A

### Expected Behavior

The images for these two sprites should be stored in 32 bit colour. Alternatively, support for 64 bit colour images could be added.

### Screenshots

Merganser vs the Gull and Pelican.
![image](https://user-images.githubusercontent.com/60202690/159237710-397914bc-08fd-4747-91f6-21a9bd45e851.png)

Merganser vs its top-down
![image](https://user-images.githubusercontent.com/60202690/159238353-4423d555-156c-4524-9eac-f38347a7f178.png)

Research Laboratory vs the Salvage Scanner and Emergency Ramscoop.
![image](https://user-images.githubusercontent.com/60202690/159237778-04f4e370-90e7-4e34-b825-e7943e2e2b49.png)

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

8fa7541cd3c12be2a2815fc0b8e8530d6ac444b2

**Comment by Zitchas** [comment]
hmmm... I've never actually encountered this problem. What are the circumstances that cause it to occur?

**Comment by pepoluan** [comment]
They are also very dark in my game.

I'm playing on Linux btw.
