### ISSUE TITLE
Value per ton in the boarding screen

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#665]
It would be nice to be able to quickly ascertain which outfit/commodity will bring the best return when I am looting a ship. A simple Value/Ton column would do wonders.

**Comment by natangold** [comment]
It's already organized in that fashion, with (IMHO) the Hyperdrive marking the point below which you should go loot another ship. Supercapacitors are usually near the top, atomic and ionic engines near the bottom, commodities dead last.
