### ISSUE TITLE
[Feature Request] Have Shipyard and Outfitter treated as locations like the Spaceport currently is.

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#6652]
### Problem Description

Currently, planets have basically two locations: Landing, and Spaceport. This leads to some recurring problems, such as the fact that people keep reporting Trinket as bugged because it sells nerve gas. 

On the same token, planets have dreadfully little description; and it would be nice to be able to provide descriptions for these two areas that captains visit on a regular basis.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/6225

### Desired Solution

Two parts to this:
1) On the technical side, I would like to see the outfitter and spaceport considered locations, so we could have missions with the `outfitter` and `shipyard` attributes, causing them to only trigger in those locations.
2) On the descriptive side, I would like to be able to specify a shipyard and an outfitter description in the planet definitions, in the same way that we currently define spaceports. This description would be visible in the outfit / ship column where we currently just have "nothing selected" displayed:
![Empty Area in Outfitter](https://user-images.githubusercontent.com/32169904/160316125-07e939ce-75eb-4a4d-9d2e-f77573545d8f.PNG)

### Alternative Approaches

-

### Additional Context

As a content creator, I would very much appreciate the opportunity to specify descriptions for these two key areas of planets. After all, the player spends a lot of time in both outfitters and shipyards, so giving these places their own unique flavor would be much appreciated.

**Comment by rovermicrover** [comment]
Will take a shot at this next week

**Comment by rovermicrover** [comment]
Had some time tonight and took a shot at writing a Rough Draft of what might work for getting missions to be offered in the shipyard and outfitter. Work in progress of course.

https://github.com/rovermicrover/endless-sky/pull/23

**Comment by rovermicrover** [comment]
PR for missions being offered is done, will start work on the descriptions. That’s going to be a little more delicate and require more thought.

**Comment by Zitchas** [comment]
Great! Thank you for working on this!

**Comment by quyykk** [comment]
oh wait this is actually two issues, I'll reopen it.

**Comment by Amazinite** [comment]
Closing since the first request was merged and the second was rejected.

**Comment by ziproot** [comment]
Would this be closed as completed or not planned? First request was completed and second request is not planned.

**Comment by bene-dictator** [comment]
Completed, but there's not a noticable difference I think.
