### ISSUE TITLE
Declining Remnant: defence 2 prevents getting the remnant license

### ISSUE THREAD

**Issue by shawnc722** [endless-sky/endless-sky#6665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you complete the planetary defence for the remnant but don’t agree to track down the Korath ship, there’s no way to continue the remnant defence missions and get the license. 

### Steps to Reproduce

1. Complete remnant: defence 1
2. Decline remnant: defence 2

### Expected Behavior

If I’m reading the source right, it looks like declining the first defence mission just puts a 20 day timer on it happening again. It makes sense to me that the same thing would happen for the second mission - I actually went and did other stuff for a bunch of in game days from the assumption that’s how it would work before finally checking the source. 

### Operating System

Elementary OS Jólnir

### Game Source

GitHub Releases

### Game Version

Commit ab61d37 (latest build as of posting)

**Comment by Zitchas** [comment]
Yes, this is the way it works. If you decline the request to do stuff for the Remnant, the Remnant don't trust you to use their stuff.

**Comment by Amazinite** [comment]
This is the case with a majority of missions in the game: if you decline something then you can't continue. Defense 1 doesn't decline but instead defers, hence why it can reoffer. Alternative routes sometimes exist (although not in this case) and more may be added in the future, but that's more of a long term goal and not the same thing as allowing you to get missions that you declined to reoffer.

**Comment by shawnc722** [comment]
Oh fair enough, I don’t usually decline things in my playthroughs so I’ve never run into it before. I think it def makes sense for storyline-ending choices to be pretty explicit though, especially for something as big as the remnant. For reference, the choice dialogue is "Sorry, I don't have time to help you out." I definitely read that as a deferral given the circumstances (a routine attack by the Korath), so it makes sense to me for the mission (possibly starting from the planetary defence) to be offered again later. A lot of other missions have explicit “I don’t want to help you guys anymore” (paraphrased) choices though, so just changing the text would also make sense imo.
Also, thank you both for all the work you do on this game. It’s one of my favourite games and I see your names on tons of commits, so I really appreciate all the effort you’ve put in.

**Comment by Zitchas** [comment]
Thank you, I appreciate that. 

To be fair, when those missions were added (and for a long time afterwards) the Remnant were pretty small fry. It's probably time for me to go back through those and see about touching them up and adding things like the "You just ended the Remnant storyline. You may want to reload if this wasn't your intention" sort of things like the main campaign has.

Adding options so that getting the basic license is more a case of "do 3 out of 5 possible tasks" to earn it instead of "must do all these three tasks" is something on my list of things to do.

**Comment by shawnc722** [comment]
Either of those would work well imo, and in case anyone else runs into this in the meantime, I just removed two lines in the `Conditions` section of the save file to get the mission offered again:
```
"Remnant: Defense 2: declined"
"Remnant: Defense 2: offered"
```
Thanks!

**Comment by Zitchas** [comment]
Just be sure to use a proper text-editor. (such as notepad or notepad++) Using things like word or google docs or stuff like them risks corrupting it.
