### ISSUE TITLE
Aliens use....credits?

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#667]
So you go to wanderer space and they've never heard of a human before...but your money is still good? I've mentioned this before on google discussions but it seems a plot inconsistency for non hai aliens to accept credits (or any alien space without humans). To fix this perhaps the game could have some kind of universally traded commodity that has an equivalent value in credits. This would allow trading in alien space to make sense.

**Comment by erprice** [comment]
Spice, obviously.

**Comment by Gkramme** [comment]
Credits are a uneversal form of currency.

**Comment by Nightmareman** [comment]
Could just say that lore wise the credits came from the Quarg so everyone accepts it that way you don't have to worry about installing unnecessary mechanics that will just make things annoying.

**Comment by endless-sky** [comment]
Just think of it as the same as "gold" in most RPGs; it just represents items of value that can be traded. Or, it could just be that there's an exchange rate between any two currencies and you exchange them automatically. It's one of those cases where realism is not the goal, necessarily; having to deal with multiple currencies would make the game more complicated and not necessarily more enjoyable.

**Comment by mdsmestad** [comment]
I like the quarg idea..that would atleast have some consistency..Or maybe explain that the galactic currency was set by the Drak. That'd work
