### ISSUE TITLE
Proprietary files still remain

### ISSUE THREAD

**Issue by throwaway1037** [endless-sky/endless-sky#6673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Despite #6659 and commit `1de5aa...`, proprietary files still remain.

Sorry for a very similar issue, but #6659 was locked due to people discussing the issue (which I thought was the whole point of an issue forum thread).

### Steps to Reproduce

There are numerous proprietary files, as listed in `copyright`; any -NC license is proprietary.

### Expected Behavior

Zero proprietary files.

### Operating System

This bug affects all systems

### Game Source

Built from source

### Game Version

Bug spotted in 0.9.14

### Additional Information

This bug also affects the `-high-dpi` repo.
Whilst an initial commit which semi-fixed the issue was made to this repo, no commit was made to the aforementioned `-high-dpi` repo.

It's also worth mentioning that the commit in question deleted the entries in the `copyright` file for proprietary files which still exist in the repo, namely `sounds/jump*`.

**Comment by Amazinite** [comment]
Only the `jump*red` sounds were NC. The normal jump sounds are not. There are no remaining NC marked assets in the copyright file.
