### ISSUE TITLE
Display view range differently on the map from the jump range

### ISSUE THREAD

**Issue by pepoluan** [endless-sky/endless-sky#6676]
### Problem Description

After the SSil Vida station comes online, the jump range of Jump Drive is reduced. However, the Map UI now shows two circles:

![image](https://user-images.githubusercontent.com/642259/161465183-e61fc1d9-3828-4332-986a-258cf1d0011e.png)

This is a bit confusing when I first activated the SSil Veda generator.

### Related Issue Links

Somewhat Related to #6639 

### Desired Solution

I suggest removing the larger circle and showing the smaller circle only when in the Postverta subcluster.

Edit: Or, in relation to #6639 , use the smaller circle if either the destination or the source is in the Postverta subcluster.

### Alternative Approaches

Alternatively, have the original jump distance as hashed lines. This is still confusing, though. Better to just remove the larger (original) jump distance circle, to clearly indicate that the "physics rule" of the Postverta subcluster pocket dimension is different.

**Comment by Amazinite** [comment]
One is the view range and the other is the jump range. Normally you only have one circle because the view range is the same as the jump range.

**Comment by pepoluan** [comment]
> One is the view range and the other is the jump range. Normally you only have one circle because the view range is the same as the jump range. Removing the view range won't happen; instead we should change the view range indicator to not look like the jump range, so hashed lines might work.

Ahhh, that's new to me!

Okay then I agree with using hashed/dotted line for the view distance.
