### ISSUE TITLE
Plugin toggle

### ISSUE THREAD

**Issue by trentbuck** [endless-sky/endless-sky#6677]
### Problem Description

I ship Endless Sky to prisoners.
Prisoners have extremely restricted internet access; they cannot download plugins themselves.
I would like to ship (a curated subset of) plugins in /usr.
From initial testing on Debian 11 (Endless Sky 0.9.8), it seems like this turns on those plugins for *all* users.
Is there a way to turn a plugin off, other than "move the plugin out of the plugins folder"?
If not, can we please add a simple enabled/disabled toggle for each plugin, under Preferences > Plugins?

I am mentally thinking of a basic checkbox like Morrowind had: https://www.tamriel-rebuilt.org/sites/default/files/trloadorder2.jpg
I'm not asking for something super fancy like the Nexus Mods "Vortex" app.
(Morrowind's UI also allows for reordering plugin load order, and inter-plugin dependencies, but I don't think ES needs those.) 

PS: one of the plugins I tested was the first-party high-dpi plugin.  That says "High DPI mode: inactive", but it's on top of a planet icon, and clicking it didn't do anything, so I'm not sure how I'd toggle that *on*, either :-)

### Related Issue Links

https://endless-sky.github.io/plugins.html
https://www.tamriel-rebuilt.org/sites/default/files/trloadorder2.jpg
https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins#the-structure-of-a-plugin
https://steamcommunity.com/app/404410/discussions/search/?gidforum=496879865901678011&include_deleted=1&q=plugin+toggle (no matches)

### Desired Solution

1. I ship third-party plugins in /usr to all prisoners (similar to "apt install endless-sky-high-dpi" right now).
2. Prisoner can opt-out of an unwanted plugin via `Preferences > Plugin > Frobozz > Disable`.

It would be slightly nicer for me if third-party plugins were off by default, especially "cheat" plugins.
But I don't really care if they're opt-out or opt-in.

### Alternative Approaches

1. I tell prisoners "sorry, extra content is too hard" (i.e. status quo)
2. I put plugins somewhere like /usr/share/endless-sky/plugins-DISABLED/ and tell prisoners "manually browse there, then copy-paste those folders into ~/.local/share/endless-sky/plugins/".
3. As approach 2, but I write a GUI launcher app that automates this.  (I don't really want prisoners fiddling around in hidden folders.)

**Comment by tehhowch** [comment]
"Runtime plugin selection" and "pilot specific plugins" are in the plans, but not happening soon. An interactive utility that copies plugins into the respective `~/.local/share/endless-sky/plugins` folder, next to the user's saves directory, will be the fastest way to get this functionality for your distribution.
As noted though, plugins apply to all the user's pilots at the same time.

Re: high dpi, the plugin image is not interactive. When the UI is rendering in high-dpi mode (UI/menu zoom > 1 or true high-dpi monitor), the game will select the `"@2x"` image, which has different text than the standard image.
