### ISSUE TITLE
Inconsistent pronoun use for Gavriil, the Remnant engineer

### ISSUE THREAD

**Issue by shawnc722** [endless-sky/endless-sky#6678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This isn't really a bug, and may even be intentional, but the Remnant engineer introduced in `Remnant: Cognizance 9` is referred to with both "he" and "they" pronouns. From the usage, I can tell the "they" is definitely intentional, so I started editing the file to do a pull request before I realized the "he" usage may be intentional too. @Zitchas, he/they seem(s) to be your character so if you'd like me to keep working on that pull request just let me know.

### Game Source

GitHub Releases

### Game Version

Commit 469b32f

**Comment by Zitchas** [comment]
Gavril is technically male, but is deliberately described as androgynous. So changing them all to "they" might make things simpler, but technically speaking the mix of "he" and "they" is correct.

**Comment by shawnc722** [comment]
Alright cool, I won't continue with the pull request then. Thanks!
