### ISSUE TITLE
Make fighters and interceptors more useful and dangerous

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#668]
Right now, fighters and light interceptors (Sparrow, Wasp) are more or less useless against larger ships and generally un-fun, for a variety of reasons:
- They're so fragile that they are shredded like tissue paper by defensive turrets, especially ubiquitous Heavy Laser Turrets
- Their typical standard weapons (beam lasers) are so short-ranged that by the time they can be used, the fighters are in jeopardy from defensive fire, and these guns are not especially powerful or intimidating to begin with
- They are not cost-effective to swarm because of their relatively high cost despite their disadvantages; you lose some in every battle at great expense, whereas using the same sum to purchase larger, more powerful ships would allow you to keep those ships around, and with greater capabilities (large cargo bays, turrets, anti-missile fire, torpedo launchers)

This would seem to present three avenues of improvement:

1. Make them tougher. This doesn't seem appropriate, because they're supposed to be weak and easy to destroy; they're fighters!
2. Make them cheaper. This makes a certain amount of sense, but how much cheaper should they really be? I imagine there's a lower limit on the price of even a small spacecraft. The prices *feel* right.
3. Give them more appropriate default armament and weapons capacities. The Hawk variant with two rocket launchers already does this *perfectly;* it's basically a high-speed delivery vehicle for 1,400 points of shield damage per shot. Devastating, and fun to play yourself. This is exactly the kind of armament that fighters have in the real world: Heavy-hitting rocket/missile weaponry that gives them a high offense-to-weight ratio. The Fury variant with four Meteor launchers embodies this as well. **It's the high offense-to-weight ratio that's key; if fighters didn't consistently punch above their weight class, there'd be no reason to have them, which is exactly the problem that fighter-sized ships have in Endless Sky.** The other fighters should be armed accordingly, with a default armament of a powerful gun for close-ranged fighting and at least one missile-type weapon for long-range damage. This will become even more appropriate once you implement jamming and missiles can do more damage. Being armed with missile weaponry, especially homing missile weaponry, allows fighters to threaten larger ships from beyond the range of their defensive turrets. I think the Sparrow should be armed with one Meteor launcher and two Blasters; the Wasp with a Meteor launcher and a Proton Gun; the Fury with two Meteor launchers and a Plasma Gun, etc. The Dagger and Lance should at least have a Sidewinder launcher in addition to any other armament. Regardless of the details, I think you get the picture, because those little beam lasers just aren't cutting it. With these changes, a couple of fighters could launch an enormous swarm of missiles very quickly, overwhelming anti-missile defenses and closing in for the kill with powerful guns. With this change, I could see it being necessary to reduce the magazine sizes for each individual launcher, and then make a new "expanded missile magazine" outfit to increase the capacity for non-fighter ships that mount missile weaponry but be too large to mount on most fighters.

**Comment by Pointedstick** [comment]
In summary:
* Give all fighter-sized craft 2-3 more gun hardpoints but don't give them any more weapon capacity
* Implement the missile changes in #669 
* Arm every fighter-sized craft with 1-3 of the now-smaller missile launchers, but don't give them any missile magazines
* Fill the remaining gun hardpoints with small guns (blasters, beam lasers) for the lighter craft, or a single larger gun (proton gun, plasma gun) for the heavier ones

**Comment by endless-sky** [comment]
Think of it this way:

stat | Stock Leviathan | Stock Daggers, 62x
---- | ---- | ----
cost | 17.1M | 17.1M
shields | 14,400 | 55,800
hull | 5,000 | 18,600
shield DPS | 1,368 | 7,440
hull DPS | 1,656 | 14,880

Which one do you think will win in a fight? Obviously the Daggers will suffer casualties, but there's no way the Leviathan will win if both are being flown with equal skill. And if turrets are changed to have a limited turn rate, that will make those fighters even more powerful - especially if combined with a better fighter AI, which might be possible eventually.

Also, the existing fighters can already be loaded with 2 meteor missile launchers or 1 heavy rocket (although the latter does not end well for them). And giving more than two hardpoints to a ship that's supposed to be smaller and cheaper than a shuttle just doesn't make sense.

**Comment by endless-sky** [comment]
Here's an example of how much damaged souped-up fighters can do. In this case, I gave them each one Hai Pulse Cannon. But the most effective change seems to be that I gave them very quick steering (which was only possible by installing the tiny Wanderer thrusters to free up more engine space). So, maybe making fighters stronger would just be a matter of increasing their engine space by a tiny bit so that the same thing could be done without Wanderer tech.

https://youtu.be/k0Fn8a__VdM

**Comment by Pointedstick** [comment]
I think you're kind of illustrating my point. The fighters you showed in that video are indeed souped up! Hai pulse cannons are far better, more effective weapons for fighters than beam lasers (longer range, higher DPS). See what happens with standard Dagger fighters, and engage a fleet, don't just pick on a couple of Argosies. Engage a fleet that costs as much as all of those fighters with all of the ships climbed up and see what happens. Probably you'll be left with very few fighters if you win.

**Comment by Pointedstick** [comment]
I've never seen a swarm of 40 fighters in the game like you show in your video. Republic carriers have like four and a couple of worthless drones that die if you look at them funny. If 40 fighters are required to illustrate that fighters are powerful enough, then maybe carriers should carry 40 fighters! Also, Hai Pulse Cannons are far superior fighter weapons than Beam Lasers (higher shield DPS, longer range), so you're kind of proving my point that fighters' default armament is problematic.

Stepping back, I think the basic point I want to make is that I believe you've set up a game universe in which a couple of the basic details of how fighters are armed and used don't make sense because they don't fit within the parameters of the universe you've made.

Imagine you're a Republic fighter pilot. You're launched from a Carrier and alongside three of your buddies, most likely facing Heavy Laser Turret fire from your target. Maybe just quad blaster turrets; nearly as bad. In this game universe, going up against these turret-armed adversaries is suicide: you'll have lost half your shields to defensive fire before you can even turn on your short-ranged Beam Lasers. A common pair of Heavy Laser Turrets (standard armament on 5 ships; another 5 have 3 or more) destroy a Dagger in 2.42 seconds and a Lance in 2.07. All 3 or 4 of you will be space debris in moments; your fighter is a suicide machine. Maybe it wouldn't be suicide if there were 40 of you, as you showed in your video, and you could overwhelm your target with numbers, but there aren't, because you were launched from a ship with far lower capacity than that. If you were this pilot and had control over your ship's armament but not how many other fighters were in your attack squadron, you'd ditch the Beam Lasers and put on some missile launchers, because they outrange the Heavy Laser Turrets. It's a no-brainer if you want to live: as soon as your ship is launched, you'd hang back and pummel your target from long range with missile fire, then maybe return to your parent ship to repair and re-arm. Since your fighter might as well be made of tissue paper, you want to be *far away* from the deadly and unerringly accurate defensive turret fire of your adversaries. If replacing the Beam Lasers with missile launchers of some sort is such a no-brainer… maybe they ought to be a part of fighters' standard load-out. It just makes sense given fighters' fragility and the ubiquitousness of powerful but short-ranged defensive turret weaponry.

**Comment by DingusShingleton** [comment]
I had an idea. Allow fighters currently docked in your ship to reload missiles that are in your cargo bay. That way, the low capacity wouldn't be an issue, and as you say it gives 2 or 3 fighters an actual purpose. With tweaked fighter ai, they just scoot around, unloading rounds into your targets flanks, then return to the mothership to reload.

And it gives looted ammo a cool new purpose. You would probably want to ads a way to buy missiles into your cargo bay though.

**Comment by jafdy** [comment]
What about if fighters got to doge perhaps 90% of incoming turret fire and were unaffected by ships blowing up. An interesting expansion on this would be to allow anti-missile turrets to always hit and to deal some damage. 
This would make 10 fighters at least a little problematic for the largest ships.
