### ISSUE TITLE
groups.google.com Content unavailable

### ISSUE THREAD

**Issue by Xphere-Skylighter** [endless-sky/endless-sky#6692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Subject pretty much says it all.

I've tried 3 different email accounts. 
I've tried 3 different browsers: Vivaldi, Chrome and Firefox.

### Steps to Reproduce

1. Go to 'https://groups.google.com/group/endless-sky'
2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

I was hoping to get to join the group conversation.

### Screenshots

![image](https://user-images.githubusercontent.com/103284735/162513132-d9053bfd-74e1-44b0-afe7-f23a6648c28d.png)

### Operating System

Win 10 Pro

### Game Source

Steam

### Game Version

v0.9.12

**Comment by quyykk** [comment]
The readme says this

> Endless Sky's main discussion and development area was once Google Groups, but due to factors outside our control, it is now inaccessible to new users.

You can join the Discord instead (link in the credits and in the readme).
