### ISSUE TITLE
Submunitions not accepting parent munition velocity – Mac Continuous Build

### ISSUE THREAD

**Issue by DeBlister** [endless-sky/endless-sky#6695]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Any weapon with submuntions (Proton/Annihilator Turrets, Drak Antimatter Cannon, and most missiles (not Javelins or other secondary weapons like Railguns and Gatling Guns because no submunitions)) does not fire the submunitions accurately if the munition has some velocity in addition to its own.  That is, if they are fired from a moving ship, the submunitions will not accept the velocity of the parent munition (which does accept it from the parent ship) and will miss left, right, short, or long depending on the orientation of the weapon in comparison to the velocity of the ship.

- 0º – **SHORT** as the submuntions will be traveling slower than they should be and perhaps more slowly than the ship itself, depending on the ship and weapon of course.
- 90º Couterclockwise – **LEFT** as the submutions will fall behind the primary munition stream.
- 180º – **LONG** as the submunitions will not "lose" speed to follow the primary munitions and parent ship.
- 90º Clockwise – **RIGHT** as the submunitions will fall behind the primary munition stream.

Obviously a combination of two adjoining categories will result in hybrid behavior, though none of it will be correct.

### Steps to Reproduce

1. Select a flagship with a high (1000+) max speed to make the test results more obvious.
2. Equip any of the weapons listed to your flagship, preferably only 1 type.  I tend to use Ka'Het Annihilators.
3. Travel in any direction until you reach max speed.
4. With no targets, fire weapons and view projectiles.
5. See error.

### Expected Behavior

Submunitions should inherit primary munitions' velocity before applying their own velocity.  I have seen the previous PRs (such as #6160) that address a purposeful change in velocity from primary munition velocity for submunitions, but this is not that issue, as far as I can tell.

### Screenshots

My ship was traveling to the right in all screenshots.

![0](https://user-images.githubusercontent.com/80174383/162547661-189df320-d509-4d83-afc3-1ebe496bfbee.png)
![90 CCW](https://user-images.githubusercontent.com/80174383/162547663-a10a0a55-5730-45f5-a9ae-a1df464f1507.png)
![90 CW](https://user-images.githubusercontent.com/80174383/162547665-16c39b6d-1e31-4132-8545-7e925956ae28.png)
![180](https://user-images.githubusercontent.com/80174383/162547666-83076926-68da-479f-85f8-25697678ec24.png)

### Link to save file

~~This can be done with any save as it an issue in combat/functionality and I can resolve the issue by using the same save with an app that I build myself from the source code.~~

I don't believe the save file affects this issue, but I had a very outdated version of the source code, as noted below in Additional Information.

### Operating System

macOS 10.14.6

### Game Source

GitHub Releases

### Game Version

Continuous retrived on 04/08/22; commit ea1dacf372b45c929c10f500db8b83a814058f50

### Additional Information

~~When I build my own app in Xcode, I don't see this behavior, which implies that something is wrong with the Continuous release for macOS.  (I have confirmed that changes I make in the code I build do affect the executable: if I quadruple the velocity of submunitions in Projectile.cpp and build that, Ka'Het Annihilator Turrets fire much further.)~~

I had a very outdated version of the source code.  At the moment I can't seem to build the source code from master that I just merged to my fork due to an SDL issue, but hopefully I can resolve that and test if the issue does appear, in which case I will attempt to resolve it myself and maybe make a pull request.  So, the issue could still be with either the source code or just the macOS Continuous build.

**Comment by DeBlister** [comment]
I was able to bypass the issue (curl & bad certs) and build from the current source and the issue persists.  I'm new to C++ so after fiddling around with minor changes seeing if anything would work, the best I've come up with so far is some pseudocode.  Some of the definitions may be redundant but it should be self-explanatory because of that.

The below logic is meant as a workaround to not carrying parent velocity with munitions in the code (so that it could be applied to child munitions).  It should derive the velocity that should be shared with child munitions from its own velocity and its weapon statistics.  This would still be a necessary calculation for missiles or other munitions with acceleration *even if* that information were retained, so this may be the more elegant solution anyway.  I don’t think overloading the Projectile method again would help in that sense either.

So, as it stands it should apply adequately to both guided and unguided munitions, barring some alternate intention for missile behavior.  From #6160, I gather that explosions of munitions are intended to inherit the parent velocity in this manner as well.


- PM = primary munition
- SM = submunition
- totalVelocity = the velocity with which a parent ship/munition is traveling
- sharedVelocity = the velocity which a projectile inherits from its parent ship/munition (this is the key value that seems to be missing/flawed in the current calculation)
- firingVelocity = the combination of firingAngle and firingSpeed to make a vector
- totalAngle = the angle portion of totalVelocity
- firingAngle = the angle at which the submunition applies its own speed when launched, generally associated with the “inaccuracy” stat
- firingSpeed = the speed at which the submunition launches itself according to the firing angle, generally associated with the “velocity” stat
- inaccuracy = the “inaccuracy” stat

1. Find velocity of PM not due to PM: sharedVelocity
	⁃	Find PM.firingVelocity as = PM.firingAngle * PM.firingSpeed
	⁃	Find PM.sharedVelocity as = PM.totalVelocity - PM.firingVelocity
2. Find totalVelocity of SM
	⁃	Find SM.firingAngle as = PM.totalAngle + SM.inaccuracy
	⁃	Find SM.firingVelocity as = SM.firingAngle * SM.firingSpeed
	⁃	Find SM.sharedVelocity as = PM.sharedVelocity
	⁃	Find SM.totalVelocity as = SM.sharedVelocity + SM.firingVelocity

**Comment by Amazinite** [comment]
Relabeling as "mechanics" as this seems to be dealing with some of the questions raised in [tehhowch's review](https://github.com/endless-sky/endless-sky/pull/5515#discussion_r541648909) from the last time we touched how submunitions are created, namely how exactly we want submunitions to be emitted.

**Comment by Amazinite** [comment]
Thinking about it a little more, this definitely isn't a bug and seems like it's entirely the expected behavior given how submunitions are created.

The following arrows represent velocity vectors. The red arrow is the velocity of the parent projectile. The blue arrow is the velocity of the submunition projectile. The yellow and green arrows are the x and y components respectively of the submunition projectile. When a submunition is created with inaccuracy and zero added velocity, it maintains the speed (i.e. length) of the parent, represented by the red and blue arrows being the same length. But when tilting the velocity vector of the submunition while applying inaccuracy, the component of the submunition's velocity that matches the direction of the parent velocity is now smaller, meaning that in the direction of fire the submunition is now going slower than the parent was. *This* is exactly why when firing perpendicular to the direction of travel the submunition lags behind, as it actually is going slower in the direction of fire.
![submunition inaccuracy](https://user-images.githubusercontent.com/17688683/163891473-091f72bf-71ce-4d27-a317-ac7d059bb9de.png)

In order to not have submunitions lag behind, we'd need that green arrow to have the same length as the red arrow, meaning the blue arrow would need to increase in length, which would mean that submunitions fired with inaccuracy would actually get faster than they should, and the higher the inaccuracy the faster they'd get.
