### ISSUE TITLE
Problems while compilation from sources on Linux

### ISSUE THREAD

**Issue by mdziczkowski** [endless-sky/endless-sky#6700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had cloned the GitHub repo of the game and while attempting to compile, I had recieved following errors:

```
source/ImageBuffer.cpp: In function ‘bool {anonymous}::ReadJPG(const string&, ImageBuffer&, int)’:
source/ImageBuffer.cpp:290:28: error: cannot convert ‘bool’ to ‘boolean’
  290 |   jpeg_read_header(&cinfo, true);
      |                            ^~~~
      |                            |
      |                            bool
In file included from source/ImageBuffer.cpp:19:
/usr/include/jpeglib.h:1040:15: note:   initializing argument 2 of ‘int jpeg_read_header(j_decompress_ptr, boolean)’
 1040 |       boolean require_image));
      |       ~~~~~~~~^~~~~~~~~~~~~
/usr/include/jpeglib.h:877:22: note: in definition of macro ‘JPP’
  877 | #define JPP(arglist) arglist
      |                      ^~~~~~~
source/ImageBuffer.cpp:291:27: error: ‘JCS_EXT_RGBA’ was not declared in this scope; did you mean ‘JCS_BG_RGB’?
  291 |   cinfo.out_color_space = JCS_EXT_RGBA;
      |                           ^~~~~~~~~~~~
      |                           JCS_BG_RGB
scons: *** [build/ImageBuffer.o] Error 1
scons: building terminated because of errors.
```

### Steps to Reproduce

1. Clone the repository on Debian linux
2. Try to compile with Scons
3. See error

### Expected Behavior

Sucessfull compilation

### Link to save file

n/a

### Operating System

Debian (64-bint)

### Game Source

Built from source

### Game Version

0.9.15

**Comment by quyykk** [comment]
Are you sure you have the right packages? More specifically, do you have libjpeg-dev installed? Check out the following link for the complete list of packages you need: https://github.com/endless-sky/endless-sky/blob/master/readme-developer.md

**Comment by mdziczkowski** [comment]
@quyykk I guess so. As far as I know, the "jpeglib.h" (and some other header files) have become included from my anaconda instance

**Comment by quyykk** [comment]
I think you also need libjpeg62-turbo-dev. Try installing that.
