### ISSUE TITLE
Give loans a grace period to make them a viable option for recovering from running out of money

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#671]
It's often been explained that you don't want the player to ever run out of money and be stuck. However, this game has a bank; you can always take out a loan to get yourself back on your feet if this happens. And if you run out of fuel, other ships will give you free fuel so you can land on a planet with a bank. To make this an even more reasonable solution of the problem of getting stuck with no money, I propose that all loans (including your starting mortgage) have a several-week-long grace period before you have to start making payments, so if you literally have zero credits, you have some time to amass the money you'll need to make the payments without missing payments and damaging your credit rating.

Hopefully this will alleviate the worry that people could get totally stuck if they run out of money, which will open the door to flavorful balance changes like depreciation, proportionally-sized ship repair fees, fuel fees, landing fees and taxes levied by those snooty paradise planets, etc.

**Comment by thenerdfreak** [comment]
They already are-- borrow more than you'll immediately spend so you'll have extra money to pay off the loan, and make money to cover it with what you borrowed

**Comment by Pointedstick** [comment]
You are confusing my proposal with the ability and necessity to work around its absence.

**Comment by thenerdfreak** [comment]
I get what you're saying, but it would only apply to loans that are absolutely tiny, large loans it wouldn't even matter on

**Comment by endless-sky** [comment]
The player could still have all their money drained by crew salaries. Or they could have such a low credit rating and income history that they can't qualify for a loan. So, this wouldn't really keep the player from running out of money.
