### ISSUE TITLE
Cannot purchase or collect outfits into cargo

### ISSUE THREAD

**Issue by samrocketman** [endless-sky/endless-sky#6717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This bug was first [reported by me April 6th in discord][1].  This problem was [reported again by another user in discord][2].

* No longer able to purchase outfits directly into cargo.
* No longer able to move outfits stored on a planet into cargo.

[1]: https://discord.com/channels/251118043411775489/536900466655887360/961309232462975058
[2]: https://discord.com/channels/251118043411775489/308902312741568512/963927006125363210

### Steps to Reproduce

1. Go to outfitter
2. Click on show outfits in cargo along with show outfits for sale
3. The buy button is no longer available for purchasing cargo.

Alternately, with outfits stored on a planet you used to be able to do the following.

1. Go to outfitter
2. Uncheck show outfits in cargo and show outfits for sale (nothing checked)
3. When selecting an outfit stored on a planet the "install" button would turn into a "cargo" button which would move outfits from planet to cargo; this is no longer the case.

### Expected Behavior

* Outfits would be able to be purchased into cargo.
* Outfits should be able to move from planet into cargo.

### Operating System

Linux

### Game Source

Built from source

### Game Version

master branch 9fb0beb6d0e8319900ba2f8f5f6e28c4fda73730

### Additional Information

This bug was introduced by https://github.com/endless-sky/endless-sky/commit/949760972eb3053173f2c89001b4ab936e29c500

<details><summary>How I found the root cause (click to expand)</summary>

---

I found this with `git blame`.  I learned that `HEAD~50` did not suffer this issue.

```
git checkout upstream/master -b bugfix-cargo
git blame HEAD HEAD~50
```

I also recorded [a youtube video on how to use git blame with endless-sky](https://www.youtube.com/watch?v=gsl8Rrw9_zs&t=546s).

</details>

---

**Comment by Amazinite** [comment]
Isn't this just #6668?

**Comment by samrocketman** [comment]
Looks the same.  I found the root cause and will comment in the other issue
