### ISSUE TITLE
Wanderer-Korath relations?

### ISSUE THREAD

**Issue by JasonnZhang** [endless-sky/endless-sky#672]
I know there's a lot of other story arcs planned that have a much higher priority (republic, syndicate, etc.) but somewhere down the line wouldn't it be cool if you could tell the wanderers about Far'en Lai (the last remaining Korath world) and get them to help fix the planet? 

That's the first thing I thought of when the Wanderers say that they fix broken worlds. It would make sense within the lore, since the Korath believe fixing Far'en Lai will redeem them, and it makes everything more cohesive. Then maybe even the Korath would become friendly and you could buy Korath outfits on the planet, or something.

**Comment by mdsmestad** [comment]
This would be a cool idea.

**Comment by brick96** [comment]
Maybe ask them to fix hope?

**Comment by mdsmestad** [comment]
The wanderers would actually be excellent for many parts of the story that require terraforming. Its already an important part of the game so the wanderers will work well in so many other things

**Comment by DingusShingleton** [comment]
It would be cool if you go to the wanderers but they are like "sorry, can't help you. We go where the wormhole goes." And then you have to go deal with the pug and get them to direct the wanderers in that direction somehow

**Comment by psychiclegume** [comment]
Could you like have to sell them Jump Drives, like the Unfettered Hai, before they can help with terraforming and rebuilding?

**Comment by endless-sky** [comment]
Coming sometime in the 0.9 series.
