### ISSUE TITLE
Remnant ships say "Please take my cargo and leave me alone" in particularly strong ion storms

### ISSUE THREAD

**Issue by DisableGraphics** [endless-sky/endless-sky#6720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's weird that the Remnant are saying those lines to, _you know_, an ion storm, instead of, for example, Korath attackers or something.

### Steps to Reproduce

1. Go to the Ember Waste (remnant systems preferably)
2. Wait for a strong ion storm.
3. Laugh at the Remnant that says "Please take my cargo and leave me alone" to the ion storm

### Expected Behavior

The Remnant should not say those lines to the ion storm. Adding a way to check if they're being attacked by a space weather phenomenon or not could probably solve this issue.

### Operating System

Arcolinux (rolling release)

### Game Source

GitHub Releases

### Game Version

Compiled in 2022-03-28 11:56 UTC

### Additional Information

I downloaded the version last month and I can't really say which commit was. I've tried to include in the Game Version the date of compilation (Displayed in the menu).

**Comment by Amazinite** [comment]
This probably always happened, but was made more obvious by https://github.com/endless-sky/endless-sky/commit/dd4641f8027e863ccb28e405ab59a0b099fadd1e. What's happening is that the ion storm is getting their health below 50%, which is all that it takes to trigger the appeasing personality that Remnant ships have. So it's likely that appeasing ships should also check if there's a hostile in the system to even appease.
