### ISSUE TITLE
Remnant Coginznce 32 Extra Dialogue 

### ISSUE THREAD

**Issue by Luuiscool4567** [endless-sky/endless-sky#6722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug in question-related to "extra" dialogue relating to finishing the Shergai Archaeology. When you land it doesn't seem to cover the branch related to the Emerald Sword arc and skips over it which is related to the station in Ssil Vida. Playing on the latest continuous build.

### Steps to Reproduce

1. Complete the Shergai archaeology.  
2. Finish Remnant: Cognizance 31 via landing on Viminal
3. Continue by clicking spaceport.
4. See the "extra" dialogue not trigger when you already have done the Shergai archaeology. 

### Expected Behavior

The "extra" dialogue is supposed to show up instead of dialogue when you haven't done it which specifically talks about the fusion reactor being the same as a Shergai one and how the same reactor has to have a specific fuel to be able to work. 

### Link to save file

[Orion  Pax~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/8492984/Orion.Pax.previous-1.txt)

### Operating System

Windows 11 

### Game Source

ESLauncher2

### Game Version

Continuous 

### Additional Information

Just ping on the [Endless Sky discord](https://discord.com/channels/251118043411775489/430311083274928130/463128412823748618) if you need me. Probably in #bug-reporting or #ember-waste-chat.

**Comment by warp-core** [comment]
Fixed by ee1d8b6.
