### ISSUE TITLE
Build fails when using clang on Ubuntu

### ISSUE THREAD

**Issue by ceeac** [endless-sky/endless-sky#6728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang++-12 -o endless-sky -O3 -flto build/release/main.o lib/release/libendless-sky.a -lSDL2 -lpng -ljpeg -lGL -lGLEW -lopenal -lpthread -lmad
/usr/bin/ld: lib/release/libendless-sky.a: error adding symbols: archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [endless-sky] Error 1
scons: building terminated because of errors.
```

GCC works fine.

### Steps to Reproduce

1. Install dependencies according to build instructions
2. Install clang: ```sudo apt install clang-12```
3. Build: ```CC=clang-12 CXX=clang++-12 scons -j8```

### Expected Behavior

No build failure.

### Screenshots

n/a

### Link to save file

n/a

### Operating System

Ubuntu 20.04

### Game Source

Built from source

### Game Version

58c7501d..master

### Additional Information

I managed to git-bisect the bad commit to 58c7501d (#5509).

**Comment by quyykk** [comment]
That's weird; can you try building in debug mode (add argument `mode=debug`)? I think it has to do with LTO.

**Comment by quyykk** [comment]
Another thing you can try is to use lld instead of ld.

**Comment by ceeac** [comment]
`mode=debug` works fine; using lld does not make a difference (i.e. still fails in release mode).

**Comment by quyykk** [comment]
One last thing you can try: use llvm-ar instead of ar.

**Comment by tehhowch** [comment]
Clang is not supported.
