### ISSUE TITLE
Many stock loadouts for various ships have unused outfit space

### ISSUE THREAD

**Issue by Hecter94** [endless-sky/endless-sky#6733]
### Problem Description

Quite a few stock loadouts aren't making effective use of their available outfit space, for a couple of examples:
<details>
<summary>Splinter has 49 outfit space unused</summary>

![image](https://user-images.githubusercontent.com/15916854/163689344-4834dab7-8d58-4dab-8fee-f3a00bef2088.png)

</details>
<details>
<summary>Leviathan has 59 outfit space unused</summary>

![image](https://user-images.githubusercontent.com/15916854/163688745-2295634e-de21-46f4-b7cf-c5f1e39eea30.png)

</details>
<details>
<summary>Saryd Traveler has 319 outfit space unused</summary>

![image](https://user-images.githubusercontent.com/15916854/163688771-6e21c5e7-0e46-4e92-9b4a-2638741cfb8a.png)

</details>
<details>
<summary>Pug Maboro has 83 outfit space unused</summary>

![image](https://user-images.githubusercontent.com/15916854/163688797-7a3a94a3-dea1-41b7-ae07-cdc258e2737f.png)

</details>
<details>
<summary>Summer Leaf has 52 outfit space unused</summary>

![image](https://user-images.githubusercontent.com/15916854/163688809-5ce0cf47-e4e9-4a49-a9d5-aa6b70c4c84a.png)

</details>

<details>
<summary>Riptide has 52 outfit space unused</summary>

![image](https://user-images.githubusercontent.com/15916854/163689328-68846523-a7c8-4817-884b-9499ee0c690e.png)

</details>

This means that these ships aren't functioning as well as they could be, and raises the question as to why these ships are being manufactured with more space than they need and why this extra space isn't being used.

### Related Issue Links

I checked GitHub issues, Steam Forum, Reddit and asked on Discord, the google groups link is broken. 
I did not find related issues, however a reply I received on Discord stated that most of these "issues" are likely due to outfit changes over time and thus unintentional. 

### Desired Solution

Stock loadouts should be tweaked so that the extra space is used up, whether it be by adding cargo expansions, bunks, extra shield generators or other outfits that would be mechanically and lore appropriate for that ship to have equipped assuming it doesn't increase the cost of the ship too much so as to not impact the player experience. 

### Alternative Approaches

Alternatively the total available outfit space on these ships could be lowered to match what their currently installed outfits require, this would be a much simpler solution than re-doing the stock loadouts for each ship, but would also constitute a fairly massive sweeping balance change across many ships. 
While this would work, and would be the simpler solution for the given problem, I feel it is overall much better to leave the ship stats alone and just tweak the stock loadouts instead.

### Additional Context

I plan to go through these myself and adjust the stock loadouts so that they make better use of their available outfit space. 
Mainly opening this issue for tracking purposes, and also to see if there's any reason why anyone feels like I shouldn't attempt to change this.

A couple of notes:
Certain ships, such as the Clipper, specifically states that it comes with free space for the purpose of customization, any ships where this is mentioned, I will not change. Those ships will be left with unused space in their stock config with the idea that it is intentionally left partially empty so that they can be upgraded. 

[I've already spoken with Arachi](https://discord.com/channels/251118043411775489/747839420115189801/964976604721844274) regarding the Coal civilian ships, he is fine with them being updated as long as the changes are reasonable, stock loadouts are not given expansions or bunks and some space is left free for any future civilian outfits he wishes to add. 

I will *not* be making any substantial changes to stock loadouts, only minor changes and additions. 
Heliarch, Remnant, Ka'het and Korath ships are largely unaffected by this issue so I do not have any plans to change them.
Drak and Quarg will be left unchanged due to being placeholders.

**Comment by Amazinite** [comment]
I don't think that it needs to be the case that stock ships use up every last drop of outfit space that they can. Realize that using more outfit space means using more outfits, which increases the cost of the ship when it comes to the player purchasing it. Perhaps think of it like a prebuilt computer: the case is your ship hull, and the parts are your outfits. Not every prebuilt computer uses up all the space it can, as many leave room for the consumer to expand should they want to buy new parts in the future. In the same way, I don't find it unreasonable for some ships to be sold with a decent amount of excess space and the expectation that the person who buys the ship will upgrade. You even highlight the Clipper as a ship that explicitly states this in its description, but I don't see why that logic can't be extended to other ships or why all ships that leave free space would need to say why they leave that free space in their description in order for them to be left as is. And I certainly don't see why we'd take the route of *shrinking* the outfit space on ships just because their stock variant doesn't use it all.

The Coalition ships are the biggest outlier in this regard, but that's very clearly as a result of none of the Coalition ships having weapons, therefore leaving all the outfit space that would have otherwise been filled with weapons and the other outfits needed to support them empty. I don't think it makes sense to then pump that space full of shield generators, batteries, or anything else.

**Comment by Hecter94** [comment]
> I don't think that it needs to be the case that stock ships use up every last drop of outfit space that they can. Realize that using more outfit space means using more outfits, which increases the cost of the ship when it comes to the player purchasing it. Perhaps think of it like a prebuilt computer: the case is your ship hull, and the parts are your outfits. Not every prebuilt computer uses up all the space it can, as many leave room for the consumer to expand should they want to buy new parts in the future. In the same way, I don't find it unreasonable for some ships to be sold with a decent amount of excess space and the expectation that the person who buys the ship will upgrade. You even highlight the Clipper as a ship that explicitly states this in its description, but I don't see why that logic can't be extended to other ships or why all ships that leave free space would need to say why they leave that free space in their description in order for them to be left as is. And I certainly don't see why we'd take the route of _shrinking_ the outfit space on ships just because their stock variant doesn't use it all.
> 
> The Coalition ships are the biggest outlier in this regard, but that's very clearly as a result of none of the Coalition ships having weapons, therefore leaving all the outfit space that would have otherwise been filled with weapons and the other outfits needed to support them empty. I don't think it makes sense to then pump that space full of shield generators, batteries, or anything else.

I fully support what you're saying, and I think it's fine if some bit of outfit space is left unused. 
However certain ships like the Leviathan which I highlighted, have enough outfit space free to substantially improve their capability by adding an extra shield generator or a similar outfit without any downside.

For instance, in the case of the Leviathan it could have a second D67-TM to bring it's unused outfit space down from 59 to 14 to double it's stock shield regen while only increasing its price from 17.097m to 17.217m, a  0.7% increase in its price, which is far from substantial.

I also don't think it's unreasonable that _some_ ships are purposefully left partially empty, which is why I'll be leaving ones like the clipper or the argosy alone, since they mention that part of their design philosophy is to be upgradable. 

But for other ships, such as the Leviathan or Summer leaf, I don't think it makes much sense for those to be left with space still unused _especially_ when those same stock loadouts will be what they actually use in combat. 

If it was solely stock loadouts for purchase that didn't use all of their space, and any ships that were actually utilized for their role had their outfit space filled completely, I could accept the idea that it is purposefully left partially empty with the expectation that it will be filled later, However I have a hard time believing that a captain would willingly take their ship out and use it, especially for combat, with space left empty. I don't think that makes sense, and I don't think other players would either. 

However, if you still feel that there's no reason to go through these loadouts, adjust them and PR it, I will hold off on doing so.

**Comment by Amazinite** [comment]
Then it sounds more like you're asking for new variants than to make the stock variants more expensive.

> But for other ships, such as the Leviathan or Summer leaf, I don't think it makes much sense for those to be left with space still unused especially when those same stock loadouts will be what they actually use in combat.

I could perhaps see a case for adding to the Summer Leaf's stock fitting, but not so much so the Leviathan; the Summer Leaf could be argued to have a fully utilized stock fitting as the Wanderers are currently using it in a war with the Unfettered. The Leviathan though goes back to the prebuilt computer example: some people for a certain amount of time are still going to be using the prebuilt without any upgrades to it. It's not as if everyone buys a prebuilt then immediately upgrades it.

**Comment by Hecter94** [comment]
> Then it sounds more like you're asking for new variants rather than to make the stock variants more expensive.
> 
> > But for other ships, such as the Leviathan or Summer leaf, I don't think it makes much sense for those to be left with space still unused especially when those same stock loadouts will be what they actually use in combat.
> 
> I could perhaps see a case for adding to the Summer Leaf's stock fitting, but not so much so the Leviathan; the Summer Leaf could be argued to have a fully utilized stock fitting as the Wanderers are currently using it in a war with the Unfettered. The Leviathan though goes back to the prebuilt computer example: some people for a certain amount of time are still going to be using the prebuilt without any upgrades to it. It's not as if everyone buys a prebuilt then immediately upgrades it, so it is reasonable to see Leviathans in use that only have the stock outfits.
Okay, understood. I'm still not sure I agree in regards to the Leviathan, mainly as upgrading my computer isn't generally a matter of life or death, however I will respect your judgement on the matter.

Would you be fine with me still going through these and making the changes I feel are appropriate in order to open up the discussion as to which changes are reasonable and which should be reverted? I definitely want to at least look at the Coal ships as they are the big outlier here.

**Comment by Zitchas** [comment]
From my perspective, stock loadout is the bare minimum for the dealer to show off the ship: Minimum necessary to operate. Now, I fully agree we need more variants of pretty much all ships, and we should definitely have some that max them out.

**Comment by Hecter94** [comment]
> From my perspective, stock loadout is the bare minimum for the dealer to show off the ship: Minimum necessary to operate. Now, I fully agree we need more variants of pretty much all ships, and we should definitely have some that max them out.

I'm okay with this, my main issue is just the question of why that unused space wouldn't immediately get filled. When installing a second shield generator could literally be the difference between a ship captain living or dying, I just can't reasonably accept that they would choose not to, and go fight pirates with a bunch of empty space in their ship. 
I recognize the comparison to a prebuilt PC not using all of its available space, but I can't accept that comparison as long as the stakes are so much higher.

Not to mention _most_ ships already do use all of their available outfit space, I just want to go through and update the ones that don't so that they match with the rest. 

Now the *ideal* might be to make it so that "stock" loadouts only show in the shipyard and then the properly outfitted "variants" are the only ones that actually spawn out in the world. 

But I figure updating the stock loadouts fixes this issue immediately and we can look at a more permanent solution later.

**Comment by Zitchas** [comment]
Despite the fact that it might not make sense to us to, say, buy a stock leviathan and take it straight into combat without filling up its outfit space, people can and do just that. Maybe the captain can only just afford the base model and doesn't have any spare credits to fill up the rest of that space? Maybe it's left courteously open by the manufacturer online the lines of "Comes with a decent chunk of empty space to fit *your* personal favorite outfits."

Worth noting that we sporadically have people asking for stock ships that are actually close to being bare minimums. Strip off the weapons, shield regen, and basically every other outfit that isn't strictly necessary for the ship to take off and fly to the next planet. 

Trying to ensure that ships are full to the brim just drives up the cost of buying said ship, de-values a core gameplay element, and doesn't really add much. Actually, the only real value I can see is making life easier for people who just want to be able to quickly buy a decently optimized ship to drop into their fleet without having to mess with it.
