### ISSUE TITLE
Bactrian Heat/Cooling Bug

### ISSUE THREAD

**Issue by Nakroxis** [endless-sky/endless-sky#6741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Installing additional cooling on bactrian doesn't reduce its heat value while the same outfit works properly on water bugs and shield beetles. 

### Steps to Reproduce

Loadout:
ship: Bactrian
guns: 2x flamethrower, 2x thunderhead launcher
turrets: 2x dual sunbeam turret, 2x wanderer anti-missile

systems: Cloaking device, 2x fuel processor, jump drive, 2x Large heat shunt, large radar jammer, 16x outfit expansions, quantum keystone, salvage scanner, systems core(large), wanderer ramscoop

power: white sun reactor
engines: a120 atomic thruster, a255 atomic steering, smelter-class steering, smelter-class thruster
h-t-h:  245x frag grenades

### Expected Behavior

Installing/removing Large heat shunt/hai wiliwaw cooling should change heat value by 3240/500 respectively.

### Screenshots

![Screenshot from 2022-04-17 21-28-51](https://user-images.githubusercontent.com/69113948/163732121-f96cfedc-202b-420b-a667-1307638d189f.png)
![Screenshot from 2022-04-17 21-28-39](https://user-images.githubusercontent.com/69113948/163732131-3302a082-59c2-4757-9b0e-51d584ecf445.png)

### Link to save file

[painful experience.txt](https://github.com/endless-sky/endless-sky/files/8502456/painful.experience.txt)

### Operating System

Pop!_OS 21.10 

### Game Source

GitHub Releases

### Game Version

Continuous build (.appimage) on April 10

**Comment by Amazinite** [comment]
Outfits expansions harm cooling, and you have 16 of them.

**Comment by Zitchas** [comment]
This is working as intended... If you remove the outfit expansions, you should be able to add cooling and see the proper change. If cooling didn't have an impact when you don't have outfit expansions, though... Then there is a problem.

**Comment by Nakroxis** [comment]
> 

Sorry didn't realize the effect they have on cooling. Could you explain how it works exactly?  does it have an equation ?

**Comment by Zitchas** [comment]
I don't have my computer right now to bring out formulas, but the general gist is that while you can add one or two outfit expansions without much issue, each outfit expansions renders the effectiveness of cooling somewhat weaker. Eventually, enough expansions renders cooling virtually useless. It is a scaling sort of thing.
