### ISSUE TITLE
Reordering Ships Inflight Inconsistent

### ISSUE THREAD

**Issue by MagicMuscleMan** [endless-sky/endless-sky#6744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Reordering the ships in the PlayerInfoPanel is deactivated inflight (variable "canEdit") on mouse click via drag and drop.

However, reordering is still possible with control + shift + arrow up/down. This allows changing the flagship when both the current and the new flagships are in the same system.

There are two consistent solutions:
Either deactivate reordering inflight via keyboard, too.
Or activate reordering inflight with the mouse.

Being able to change the flagship inflight seems to open up interesting strategic opportunities, which I just began thinking about (moving different ships next to disabled ships and then quickly varying your flagship to directly border them, change flagship when deactivated, board other ships by sequentially using crew members from different flagships, ...).
However, it's not very plausible, that this should be possible (or at least teleporting/beaming of captains should be mentioned somewhere).

As I am currently working on that panel anyway, I can implement the change, but please tell me, which behavior is the intended one.

### Steps to Reproduce

1. Depart with at least one escort
2. Open the PlayerInfoPanel
3. Scroll down to the second ship
4. Press control + shift + arrow up
5. Close PlayerInfoPanel
6. Have fun with your new flagship

### Expected Behavior

Either deactivate reordering inflight via keyboard, too.
Or activate reordering inflight with the mouse.

### Operating System

Linux

### Game Source

Built from source

### Game Version

commit 8fa7541cd3c12be2a2815fc0b8e8530d6ac444b2 with some local changes (in the relevant file, but (hopefully) not in the keyboard logic)

**Comment by petervdmeer** [comment]
> As I am currently working on that panel anyway, I can implement the change, but please tell me, which behavior is the intended one.

The discussion from https://github.com/endless-sky/endless-sky/pull/5231 still seems relevant; for now we just don't want any possibility of sorting "in-flight" (mostly due to the high risk of issues and the currently still low test-coverage).

**Comment by MagicMuscleMan** [comment]
> for now we just don't want any possibility of sorting "in-flight"

Ok, thanks, then I will implement it accordingly.

**Comment by MagicMuscleMan** [comment]
With the merge of f5f638c7c4a94b2b37d4c2006e0c50d4e8666c7f, this seems to be already implemented.

**Comment by Zitchas** [comment]
I never knew that I could switch flagships like this. I must admit, it's fun to be able to do it. It does do some odd things to the AI (for instance, I had a route plotted when I switch ships, and after I switched ships, my fleet just took off along the route plotted while my new flagship just sat here.)

Probably for the best that it has been removed, but it does kind of make me wish we had some way to switch flagships. There are plenty of game balance reasons why we don't allow it, but it'd be *really* handy to have this feature shifted over into the debug testing mode.

**Comment by MagicMuscleMan** [comment]
> I must admit, it's fun to be able to do it. It does do some odd things to the AI

Yes, definitely, it's fun to try what the possibilities are. When boarding, using the "my defense is stronger than your attack" trick makes much more sense when it's okay to lose the flagship, because even after you are dead, you can change the flagship and continue the flight. Of course, it all ends when you land, but ...

Also sometimes, all your ships stop defending themselves, because they are confused as they don't know who is in command, but you can switch back and then they get it again. :-)
