### ISSUE TITLE
Author ships shouldn't have authority to fine

### ISSUE THREAD

**Issue by samrocketman** [endless-sky/endless-sky#6747]
### Problem Description

Authors probably shouldn't scan your fleet cargo holds.  Even if they do they shouldn't have the authority to fine player.

### Related Issue Links

#6528

### Desired Solution

Author ships no longer scan

### Alternative Approaches

Author ships are not able to fine player if they do scan.

### Additional Context

Author ships on more than one occasion ruined play throughs by fining, accidentally attacked them because they were in the way, and generally displaying spoiler ships and outfits.

**Comment by tehhowch** [comment]
No, they absolutely should be able to do anything a regular ship can do.

**Comment by Zitchas** [comment]
This sounds more like a problem with the fining system as a whole.

Examples: 
- I'm a Free Worlds captain who is explicitly at war with the Republic. Why should Republic authorities have any ability to fine me at all?
- I've disavowed any loyalty to the mainstream human governments, haven't made a single credit in ancestral space in years, and exclusively work with the Remnant. Why should Navy get to fine me anything? Why should fines imposed by them be deducted from the logistics allotments received from the Remnant?

**Comment by samrocketman** [comment]
Ideally, author ships could be turned off entirely... but that's a different matter.
