### ISSUE TITLE
Move fixed coordinates from BankPanel/PlanetPanel/SpaceportPanel/TradingPanel into interfaces.txt

### ISSUE THREAD

**Issue by thewierdnut** [endless-sky/endless-sky#6750]
### Problem Description

As part of my mobile/android port, I am creating a plugin to re-skin the MainPanel and its related panels so that they are readable on a smaller screen. This mostly works, except that several of the other panels use hard-coded pixel coordinates to position content within the main ui. 

### Related Issue Links

I couldn't find any related issues. 

### Desired Solution

It would be nice if the BankPanel, PlanetPanel, SpaceportPanel, and TradingPanel would position their custom content via a "box" element in interfaces.txt, so that they could be overridden from a plugin. I have this code working already in my fork, but I didn't know if you guys wanted a PR before your upcoming release, or if you had a better approach in mind. 

### Alternative Approaches

It may also be possible to create a new "table" element to handle some of the tables drawn in the BankPanel or the TradingPanel, or to replace the content in the SpaceportPanel and the PlanetPanel with a "string" element that could have its content set in the code.

**Comment by petervdmeer** [comment]
Changing from hardcoded coordinates to coordinates defined through interfaces.txt sounds like a good improvement.

**Comment by bene-dictator** [comment]
Is this closed by #8535?

**Comment by thewierdnut** [comment]
yes
