### ISSUE TITLE
Proposal: New commodity type "Military"

### ISSUE THREAD

**Issue by dorbarker** [endless-sky/endless-sky#6755]
### Problem Description

`Military` could be a useful commodity type that is not well covered by the existing ones. `(Highly) Illegal Cargo` have some weapon-y entries, but would be inappropriate to use for this case, because you would end up delivering "stolen yachts" and "knockoff designer clothing" to the Navy fairly often. Because you would be moving the cargo under the auspices of the source government, these would be legal.

I could imagine jobs being offered to transport military hardware around if you are a member of or just on good terms with a faction, _e.g._ during the FW campaign.

### Related Issue Links

None that I could find.

Search terms for `is:pr` and `is:issue`:

- `new commodity`
- `commodity military`
- `commodity weapons`
- `commodity types`
- `cargo weapons`
- `cargo military`

### Desired Solution

A new `Military` commodity type. Subtypes should cover conventional weapons, materiel, and logistics equipment, but nothing that could be interpreted as an atrocity.
e.g.
```
commodity Military
    "surface-to-air missiles"
    "combat vehicles"
    "ammunition"
    "field rations"
    etc
```

### Alternative Approaches

Jobs that need these commodity types could instead be handled through hard-coded cargo strings.
_e.g._
```
mission "Military transport"
    description "Bring <cargo> to the frontlines at <destination>"
    job
    repeat
    cargo "combat vehicles" 20 
    <...>
```

### Additional Context

As far as I can tell, this proposed change shouldn't break any existing code or content.

I can put together a PR, but I figured it was still a big-enough change that it was worth discussing first.

**Comment by Amazinite** [comment]
Well we already have a "garbage" commodity type that's used only for jobs, so no reason a "military" type can't also exist for the same purpose.
