### ISSUE TITLE
Home and End keys should be supported in the panels

### ISSUE THREAD

**Issue by MagicMuscleMan** [endless-sky/endless-sky#6757]
### Problem Description

When having a lot of ships or items, it's frustrating to scroll through the whole list.

### Related Issue Links

None found.

### Desired Solution

Support both keys.

### Alternative Approaches

Holding the page  up and page down keys for some time also solves the problem, but is more time consuming and tedious.

### Additional Context

A pull request will follow soon.

**Comment by petervdmeer** [comment]
Closing; merged/fixed in #6758
