### ISSUE TITLE
"Behemoth (Heavy)" variant has a Plasma Turret......

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#676]
......before storyline even starts?

i.e. Player can actually obtain the Plasma Turret by plundering them :smile:

**Comment by IFailAtGaming** [comment]
"ship "Behemoth"
	sprite "ship/behemoth"
	attributes
	outfits
		"Heavy Laser Turret" 4
		"Heavy Anti-Missile Turret" 2"
but... it doesn't?

**Comment by Wrzlprnft** [comment]
ship "Behemoth" "Behemoth (Heavy)"
	    outfits
		    "Torpedo Launcher" 2
		    Torpedo 60
		    "Quad Blaster Turret" 2
		    "Plasma Turret" 2
		    "Heavy Anti-Missile Turret" 2
		"Laser Rifle" 16
		"Breeder Reactor"
		"Fission Reactor"
		"Supercapacitor"
		"D94-YV Shield Generator"
		"Mass Expansion" 9
		"Liquid Helium Cooler"
		"Liquid Nitrogen Cooler"
		"Greyhound Plasma Thruster"
		"Impala Plasma Steering"
		"Hyperdrive"
	turret "Quad Blaster Turret"
	turret "Heavy Anti-Missile Turret"
	turret "Plasma Turret"
	turret "Plasma Turret"
	turret "Heavy Anti-Missile Turret"
	turret "Quad Blaster Turret"

**Comment by IFailAtGaming** [comment]
oh sorry didn't see that

**Comment by endless-sky** [comment]
Fixed in ba6af8a. That variant was only meant to be used for missions in the Free Worlds string, but I must have added it to some stock fleets by mistake.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
