### ISSUE TITLE
[enhancement] Carrying spares and swapping parts

### ISSUE THREAD

**Issue by funkybob** [endless-sky/endless-sky#677]
So, I went to plunder a pirate ship, then changed my mind and took it over.

But never had the chance to put the hyperdrive back in it, so now I have a ship in space that can't jump.  And it's in a system with no Outfitter, so I can't remedy this.

Kudos for ensuring the game mechanics don't assume a hyperdrive, but I need a way to fix this.

In the rest of my time in this game I've realised one thing I feel it's lacking is the ability to carry parts and fit them myself when landed, sort of bypassing the Outfitter.

Whilst I can understand the idea that "you need the tools, etc, of an outfitter to do such work", it would also be nice if I can carry extra parts to upgrade plundered ships, for instance...

**Comment by endless-sky** [comment]
So, you ripped open a disabled ship and tore some parts out of it, and now you're complaining that it doesn't fly well? :)

This will probably eventually supported by just always making the "outfitter" tab available if the player has plundered outfits in cargo.

**Comment by funkybob** [comment]
Great.

Now the other idea is allowing to buy, but not fit, parts at an outfitter...

**Comment by rktaylor** [comment]
Huge fan of the "always-on Outfit tab", but can we also land on uninhabited planets? It seems logically consistent that a damaged ship might land on an abandoned planet to install spares.

Also can we have an option to "Buy Outfit and Store in Cargo"?

**Comment by endless-sky** [comment]
Buying "spare" outfits directly into cargo is now supported (as of 0.9.1). But, I don't intend to change the fact that you can "scuttle" a ship by ripping out necessary bits of it.
