### ISSUE TITLE
Cargo checkbox error

### ISSUE THREAD

**Issue by pilover100** [endless-sky/endless-sky#6776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you enter the outfitter, the "in cargo" checkbox doesn't always match up to if you're buying into cargo or not.
Possible related issues:
#6717 
#5992
Possible related Pull request:
#6718

### Steps to Reproduce

1. Go to the outfitter
2. ctrl click any selected ships to enter "in cargo" mode
3. observe that the status of the "in cargo" checkbox does not change

### Expected Behavior

The checkboxes automatically change if the purchasing mode changes and alters their affiliated attribute.

### Screenshots

Entering outfitter:
![image](https://user-images.githubusercontent.com/65236599/165557070-89d32a06-7edd-48d6-acd6-a416bf437d76.png)
Unselected the ship via ctrl click:
![image](https://user-images.githubusercontent.com/65236599/165557304-5d14b7b6-1fbd-430c-bd57-c6d09f5e18f1.png)

### Link to save file

Any should do, but here's mine (on the planet where I did the screenshots):
[Katie Hanley.txt](https://github.com/endless-sky/endless-sky/files/8573503/Katie.Hanley.txt)

### Operating System

Windows 10

### Game Source

GitHub Releases

### Game Version

Continuous: Commit #6763

**Comment by Amazinite** [comment]
Those checkboxes control which outfits should be displayed. That isn't the same as the purchasing mode. Toggling some of the checkboxes can automatically change the purchasing mode, but if you manually shift your purchasing mode then that shouldn't change which outfits are displaying.

**Comment by pilover100** [comment]
Ok... just seems quite confusing, especially when the old behaviour *was* to show what you're dealing with and not the other. Perhaps an ideal solution is to add a column for "purchase into" as well? i.e.

Show: |   Mode    |  Purchase:
   [ ]    |   for sale  |     [ ]
   [ ]    |    cargo    |     [ ]
   [ ]    |   storage  |     [ ]

**Comment by Amazinite** [comment]
It seems to be like display mode and purchase mode would be two separate lists, not two checkbox columns with the same titles, as "purchase mode: for sale" doesn't make much sense; it would be "purchase mode: install".

**Comment by pilover100** [comment]
Well, I'm no designer, but I'm pretty sure that the current system is a tad awkward, especially for new players who may not know about the behaviour (or even veteran plays who don't know that this is intended behaviour like myself).

Overall though, this is definitely something that either needs documenting or otherwise changing to a more intuitive system.

**Comment by pilover100** [comment]
Playing around a bit more with the outfitter, I've found that trying to use it in either direction (checkboxes or ctrl + click) is both confusing and annoying. For example, if I'm outfitting a ship and I don't want to see stuff in cargo for any reason (if I'm stripping components say) then I have to hit the checkbox (no other option) and then also *reselect* the ship(s) I'm working on. It's a huge waste of time having the checkboxes try and do both jobs of purchasing mode and outfit listing filters simultaneously in this very odd manner.

Overall, I think the best option is to commit fully to either one or the other:

The checkboxes are purely to show stuff, they don't ever touch purchasing mode
#### OR
The checkboxes use the old system and change purchasing mode and change with purchasing mode

**Comment by alex116** [comment]
So confusing we should think of something to fix this now. 

Right now, checking the "show outfits in cargo" also shows your installed items. How am I supposed to sell off stolen parts quickly and easily? I have to look for the 'in cargo: 1' label. That's not cool.

![Screenshot from 2022-04-28 14-16-29](https://user-images.githubusercontent.com/2493621/165847609-b8a6c94f-b519-4a65-9c78-c6efe956f34e.png)


Why not add another checkbox 
- Show installed outfits <----
- Show outfits for sale
- Show outfits in cargo
- Show outfits in storage

and only show checked items?

With regards to buying/installing - I suggest using what is checked and if it is ambiguous (i.e. could be installed but also stored in cargo) then ask the user with a dialog where it should be put. Alternatively make a triangle like drop down menu on the buy button to select where to buy to before clicking.

**Comment by petervdmeer** [comment]
Issue #3604 seems related as well.

**Comment by alex116** [comment]
thanks for that link @petervdmeer I just read that and really like the 4 checkbox approach of @DingusShingleton here: https://github.com/endless-sky/endless-sky/issues/3604#issuecomment-411096496

**Comment by alex116** [comment]
I created a draft PR to show how I would like the checkboxes.  
It doesn't address the issue of making it easier to buy to cargo/storage.  
It removes the automatic deselection of the ship when clicking the 'show items in cargo' checkbox. 
This is done because it's confusing when clicking the checkbox and having things disappear!.  
This happens when the 'show installed outfits' is checked and a ship is selected so its items are shown and the 'show items in cargo' checkbox is clicked which deselects the ship thereby having the 'show installed outfits' implicitly deselected because no ship is selected. This is too confusing so I removed that functionality. You can Ctrl+Click your ship to deselect it and buy to cargo.   
Like I said it doesn't address the buy to cargo issue, only the checkboxes and making things show up as expected issue.
https://github.com/endless-sky/endless-sky/pull/6808

**Comment by Amazinite** [comment]
Direct any discussion on this to #3604.
