### ISSUE TITLE
Michael's ship is to easy to kill.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#679]
Since its the author's ship, shouldn't it be represented as kinda the pinnacle. Of course if you just make the stats of the ship numerically better, but you could still write a plugin that would one up it. I propose that Michael's ship should be hard written into the program to be pretty well invincible. That way only someone with suffiecient programming experience could kill it.

**Comment by Pointedstick** [comment]
Captain Hector from the EV games was always invincible, yeah.

**Comment by mdsmestad** [comment]
My thoughts exactly, his ship is representing the game..I dont care how many bacterian's I've amassed, it should still destroy me.

**Comment by endless-sky** [comment]
Actually, at least in Nova, it was possible to kill Hector. But each time you did he would come back in an even tougher ship.

**Comment by mdsmestad** [comment]
There ya go, do that :D

**Comment by brick96** [comment]
How hard would it be to add variables to outfits? Say I want add a minigun like weapon. I would want the reload (r) to decrease over time (t). Perhaps something like r=15-t/0.75
