### ISSUE TITLE
[Question] buy a ship without outfits

### ISSUE THREAD

**Issue by daggs1** [endless-sky/endless-sky#6800]
### Problem Description

I was wondering if there is a way to buy a ship without any outfits?

### Related Issue Links

this site: https://endless-sky.fandom.com/wiki/Human_Ships shows hull price

### Desired Solution

when in shipyard, I can select between skeleton and fully equipped

### Alternative Approaches

build fully equipped ship and sell all outfits at value cost

**Comment by quyykk** [comment]
Duplicate of #6693 I believe.

**Comment by daggs1** [comment]
I guess that answers my question, thanks
