### ISSUE TITLE
Move RFCs procedure from ES-community to here (endless-sky)

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#6801]
### Problem Description

The RFC procedure was setup in [ES-community](https://github.com/EndlessSkyCommunity) to be able to discuss and align high-impact changes before they would be implemented in the game here.

But ES itself is now a community driven project, so I feel it makes sense to move this community activity also over to here. Having the design-processes moved to here will make them a lot more visible.

### Related Issue Links

All PRs and issues on https://github.com/EndlessSkyCommunity .

### Desired Solution

Move all design processes (which currently is mostly the RFC creation and review process) from ES-community to ES.

### Alternative Approaches

There are some alternatives to consider, like separate repos for design and code or a single repo with a design subdirectory. I don't have a strong preference there and would like to hear feedback from others on what will work best.

### Additional Context

I feel we should also do more than RFCs, we should also write some common/generic design documentation which will document the features we want to support and the features we explicitly don't want to support. (Such documentation makes reviewing also a lot simpler, since coders and reviewers can refer to such documentation as guidance.)

But let's not try to change everything at once and start with moving the RFC process here.

**Comment by Zitchas** [comment]
I think this makes sense. ES-community served a very valuable purpose while we didn't have full access to the repository, and probably still does. But as we shift to being an actual community-driven project, having these documents be more centrally located and easily visible to contributors and people just finding the project would be a definite good thing.

**Comment by petervdmeer** [comment]
Re-opened, because moving the RFCs to a separate repository or to https://github.com/endless-sky/docs indeed makes a lot of sense.

**Comment by quyykk** [comment]
I made a separate repo: https://github.com/endless-sky/rfcs
