### ISSUE TITLE
Modular Ships

### ISSUE THREAD

**Issue by thvk-net** [endless-sky/endless-sky#6806]
### Problem Description

The title is modular ships but it could also be described as fighters being able to shoot of bays. What i want to create is a ship that is build of modules and they can gight connected or in open formation.

### Related Issue Links

Nothing found

### Desired Solution

I would like to have a tag in a ships/fighters definition that enables it to shoot from their bays.

### Alternative Approaches

The other more complicate approach is to support modular ship designs but this would be a lot more difficult

**Comment by AvianGeneticist** [comment]
If we do do this, it should be an option, not a blanket.

I.E. By default, carrier bays do not allow the fighters to shoot from them, but you can add "weapons free" as a child attribute of the bay to allow fighters/drones to fire when docked.
