### ISSUE TITLE
disown ship and reorder causes crash

### ISSUE THREAD

**Issue by alex116** [endless-sky/endless-sky#6807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After landing, press 'i' to see ships, double click a ship, click disown, then click next and the same ship appears. disown again and click next and the same ship appears - WEIRD

then go back to the overview of all ships and reorder any ship and click "save order" - weird error appears.   
Terminal displays:  
`Cannot reorder ships because the new order does not contain the same ships` and the application crashes. 

![Screenshot from 2022-05-08 12-40-19](https://user-images.githubusercontent.com/2493621/167313634-5f2f2270-baf0-49cb-843c-4590da77be78.png)

### Steps to Reproduce

1. Load my pilot file and click 'enter ship'. You are on the Seginus system.
2. Press 'i' to see ships
3. DOUBLE-Click on ship 'yellow eight' - a combat drone in the Rastaban system.
4. Click 'Disown' and 'OK' to confirm. You will see Ship 'Hellish Tower' displayed. 
5. Click 'Next' and you will see ship 'Yellow Eight' AGAIN!!! <- it should not be there because it has been disowned.
6. Click 'Player Info' tab at the top left
7. Drag and drop ship 'Forest of the Forge' or any other ship anywhere else to change the order.
8. Press 'Save Order' button 
9. See error dialog
10. Press "OK" and the application closes.
11. Find crash reason in the terminal

### Expected Behavior

remove the ship from the list and update the displayed information accordingly. 
also, don't crash :-)

### Screenshots

![Screenshot from 2022-05-08 12-39-54](https://user-images.githubusercontent.com/2493621/167313584-43e877f3-4384-4385-9f09-5b19578693bf.png)

### Link to save file

[Alex Wolf.txt](https://github.com/endless-sky/endless-sky/files/8647680/Alex.Wolf.txt)

### Operating System

Linux xps-alex 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux

### Game Source

Built from source

### Game Version

sha 91eab9f14158d0b7f46778c7fff3709bf3ce9167

**Comment by quyykk** [comment]
Very likely this is caused by InfoPanelState copying the player's ship list that doesn't get updated when disowning a ship, causing a mismatch.
