### ISSUE TITLE
Escorts not responding to Gather command

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#681]
When I land on Arachne Station in Tarazed, leave, and jump into another system with ships following me, they no longer respond to the "gather around flagship" command, but do respond to others

**Comment by endless-sky** [comment]
By "ships following me" do you mean escorts? Fleet commands don't apply to any ship you do not own (or at least, they shouldn't, unless there's a bug).

**Comment by thenerdfreak** [comment]
Escorts

**Comment by endless-sky** [comment]
Can you post a saved game that allows me to reproduce this?

Does it still show the "Your fleet is gathering around your flagship." message?

**Comment by thenerdfreak** [comment]
Yes it does, and here, I'll post a save game where I'm right at the place where the glitch occurs: (lemme get there)

**Comment by thenerdfreak** [comment]
It's weird, it isn't happening anymore at all, but it happened consistently yesterday (I had more ships yesterday, so maybe that's why?) I really don't know what it could be 
[Speedrunning Bank Interest.txt](https://github.com/endless-sky/endless-sky/files/94821/Speedrunning.Bank.Interest.txt)

**Comment by thenerdfreak** [comment]
Okay, so there's no way to reproduce it directly from a save file, but I remember what happened before it started happening. I was attacking and trying to capture Quarg Ships, and my save point had been at the station, when I died and reloaded there my ships wouldn't  respond to G
