### ISSUE TITLE
[Bug]Buying an outfit into cargo that is too big for any one ship's cargo results in it vanishing

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#6817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am flying a fleet of stock Starlings (36 cargo space each), and I bought an Aeon cell into cargo (160 space). The game let me do so, as I have a combined total cargo space available of 300+. When I arrive on the next planet over, the Aeon cell is gone. Checking back on the original planet, it isn't there either. Searching the pilot file shows an Aeon Cell in the depreciation list, but isn't listed anywhere else.

### Steps to Reproduce

1. Go to any planet
2. Have a fleet of ships whose combined cargo space can fit a really big outfit.
3. Buy an outfit into cargo that is too big to fit on any single ship, but that fits in your fleet's combined cargo space.
4. Travel to another planet.
5. See if you can find the outfit in question anywhere.

### Expected Behavior

I expect one of two things to happen:

A: The outfit is left behind in storage on the planet, as it does not fit in any of the available ships.

B: The outfit is broken down into discrete packages for transport and is thus carried across multiple ships and reassembled whenever it is sold/installed/etc at another planet.

(A is my preference)

### Operating System

Windows 10 Pro

### Game Source

Other (please describe)

### Game Version

Github testing builds for Continuous as of April 29th

### Additional Information

Will retest with a clean pilot file using the latest continuous within the next 24h, but can't do so right now. (and will upload the clean pilot file at that time.)

**Comment by Amazinite** [comment]
#4483

**Comment by Zitchas** [comment]
Thank you. I knew it had been reported somewhere, but couldn't find it.
