### ISSUE TITLE
It would be great to see multiple variants of ships with slightly different sprites.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#684]
For example, I'd love to see ships that have the same shape, but the sprite is a slightly different shade or texture and/or that variant has a decal on it. On that note it would be great if you could buy different variants with a slightly different appearance. 

I realize that that there is at least 1 ship like this, the modified argosy. Though that ship uses a whole different model for the sprite, and all I'm proposing is changing the color or shad of some ships or adding some kinda cool sprite tattoo like stripes across some models.

**Comment by thenerdfreak** [comment]
What you're talking about is already supported in the game (such as Korath World Ships) and I would like to see this as well. You can make a mod if you'd like, everyone appreciates those

**Comment by LocalGod79** [comment]
pull #831

**Comment by LocalGod79** [comment]
and #854

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
