### ISSUE TITLE
When will we be able to demand tribute from Wanderers?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#685]

**Comment by Pointedstick** [comment]
Is your goal to just conquer the entire galaxy? :p

**Comment by thenerdfreak** [comment]
Yes. I already conquered all of the Republic except for two planets (Because apparently two planets of Buddhist monks are more intimidating than the fleet guarding Earth, smh)

**Comment by endless-sky** [comment]
I'll get around to it eventually, but as I've mentioned elsewhere, the tribute system is really just intended for bored end-game players, so I'm much more focused on adding new stories and content than on defining defense fleets everywhere...

**Comment by thenerdfreak** [comment]
The main reason I was asking is because, in its current state, it isn't possible to capture large wanderer ships and take them out of the wanderer systems because you can't land on any planets to fit a jump drive on it   (They're all hostile as soon as you disable the first good ship)

**Comment by endless-sky** [comment]
There's now a mission string that lets you buy most of their ships (ab449c0). To get access to the medium warship, plus whatever sort of heavy warship the Wanderers can design and build once the conflict with the Unfettered gets more serious, you'll have to wait for future releases...

**Comment by thenerdfreak** [comment]
oohhhhh foreshadowing. and alright, i didn't see that in the code changes

**Comment by Hurleveur** [comment]
Could be nice to allow tributing them in the context of the unfettered invasion (with the idea of the wanderers recognizing those claims even if they dont want to give the planet *yet*)
Idk if one should be able to do it just like that by themselves though, but ig it depends on how we view tributes. (Players allied to the wands prob wouldnt tribute them anyway?)

**Comment by thenerdfreak** [comment]
> Could be nice to allow tributing them in the context of the unfettered invasion (with the idea of the wanderers recognizing those claims even if they dont want to give the planet _yet_) Idk if one should be able to do it just like that by themselves though, but ig it depends on how we view tributes. (Players allied to the wands prob wouldnt tribute them anyway?)

Funny to receive a reply on this from 8 years ago when I've just been on another Endless Sky bender lol. 

Tbh tributing wanderers breaks their storyline so thoroughly that it shouldn't be a thing until after you completely finish their storyline, even then I don't think I'd do it since I really like their last ship's base model and outfits for mass purchasing and murdering all the quarg

**Comment by Hurleveur** [comment]
The uhai campaign I'm talking about would lock you out of wand content eventually anyway, I'm just thinking tributing all worlds could be a way to speedrun it

**Comment by Saugia** [comment]
Tributing is a non-canon sort of "mini-game style" beyond the main story of the game. It's mostly present in human space, however it was never intended to be present on every single planet, and it should not be used for story purposes. If anything at all, perhaps it is given to planets after all story is complete, but aside from that, isn't appropriate to use otherwise.

**Comment by Hurleveur** [comment]
Yeah I know we arent using the mechanic to its potential right now, and I'm still hoping the fact it was done in a minimal way for human space doesnt mean we have to keep doing that forever. ~~why is it even in if it isnt cannon~~

If players want to tribute everything we could just have an official plugin for that, but it limits story content for me.

**Comment by tibetiroka** [comment]
I'm not sure how alien tributes will be handled. I know some people are against that.

**Comment by Saugia** [comment]
The main reason why certain planets don't have tribute fleets yet is, well, we haven't got around to it. Feel free to open a PR/work on them for the Wanderers, and we can visit any balance concerns then.
