### ISSUE TITLE
Suggestion: New Race Type Pug(Unhindered)

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#687]
How the Quarg said the Pug limit themselves based on their enemy, maybe a scene where the Pug agree they underestimated the Humans, and go full force against you?
Would add cool new ships and weapons

**Comment by jafdy** [comment]
And probably get you killed. I think that this would have to be much later on.

**Comment by thenerdfreak** [comment]
I doubt that they could possibly be much stronger (if stronger at all) than Quarg, and Quarg are easysauce lategame. Would create an "in-between" from Pug/Korath to Quarg
