### ISSUE TITLE
OpenGL 3 needed on capable hardware

### ISSUE THREAD

**Issue by MagicMuscleMan** [endless-sky/endless-sky#6871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On some hardware, e.g. the Raspberry Pi 4, the hardware supports everything from OpenGL 3 which is currently needed to run the game. However, as there are some things in OpenGL 3, which the hardware does not support (not currently used in Endless Sky), only a lower supported OpenGL version is returned and the compatibility check fails.

In such a case, you can start the game on Linux from the command line with the command
`env MESA_GL_VERSION_OVERRIDE=3.0 endless-sky`

This might obviously break in the future, if more advanced OpenGL 3 features are used. However, as this probably works since quite some years, it might also still work in some years and might be worth a try if you want to play the game for example on a Raspberry Pi 4.

### Steps to Reproduce

1. Start Endless Sky
2. Observe that your system is not fully OpenGL 3 compatible 
3. Try the approach from above, maybe it works

### Expected Behavior

Trying something like the above automatically, could be a future development.

### Operating System

Linux

### Game Source

Built from source

### Game Version

master

**Comment by quyykk** [comment]
I think the rp4 supports OpenGL ES 3.0, which we also provide support for. You'll have to compile the game from source however, with `opengl=gles`.

**Comment by MagicMuscleMan** [comment]
Is there any easy way to check which one runs faster? Obviously compiling twice with the different options, but what then?

**Comment by quyykk** [comment]
Maybe the GPU percentage inside the game? Not very accurate but should be enough.

**Comment by MagicMuscleMan** [comment]
@quyykk Thanks! However, i tried both ways and it does not make a noticeable difference, neither in perceived speed nor in GPU percentage (ca. 50% on RPI 4), so I guess everyone who compiles themself can use opengles and everyone who uses a packaged version, can try their luck with the environment variable.
