### ISSUE TITLE
Allow Coalition thrust modules as reverse thrusters

### ISSUE THREAD

**Issue by 3519421** [endless-sky/endless-sky#6874]
### Problem Description

Given the Coalition's reliance on civilian solar/battery, non-Scram drives, and general focus on energy efficiency and modular design, it seems odd that they wouldn't use their thrust modules as reverse thrusters in the empty weapons compartments to improve the time and energy efficiency of their merchant shipping. I whipped up a quick-and-dirty plugin for testing, and it seems reasonably balanced as-is.

### Related Issue Links

This doesn't seem to violate anything I saw in the explanation for #6686, so hopefully it doesn't cause any new issues.

### Desired Solution

[coalition-reverse.txt](https://github.com/endless-sky/endless-sky/files/8787272/coalition-reverse.txt)

The names are too long and I simply re-used the standard images (both would need fixing), but I did attempt some reasonable description text.

```
outfit "Small Thrust Module (Reverse)"
	category "Engines"
	licenses
		Coalition
	"cost" 66000
	thumbnail "outfit/small thrust module"
	"mass" 9
	"outfit space" -9
	"weapon capacity" -9
	"reverse thrust" 6.6
	"reverse thrusting energy" 0.46
	"reverse thrusting heat" 3
	"reverse flare sprite" "effect/coalition flare/small"
		"frame rate" 4.8
	"reverse flare sound" "atomic tiny"
	description "Placing this tiny thruster in the front of a freighter or transport allows Coalition merchants to considerably improve their energy efficiency, which is of great benefit when relying on solar power."
	description "	Because a reverse thruster must be facing forwards, it must be installed in the weapon section of your ship instead of the engine section."

outfit "Large Thrust Module (Reverse)"
	category "Engines"
	licenses
		Coalition
	"cost" 292000
	thumbnail "outfit/large thrust module"
	"mass" 32
	"outfit space" -32
	"weapon capacity" -32
	"reverse thrust" 26.2
	"reverse thrusting energy" 1.7
	"reverse thrusting heat" 11
	"reverse flare sprite" "effect/coalition flare/large"
		"frame rate" 3.5
	"reverse flare sound" "atomic small"
	description "With their significant weapons capacity left unused in peacetime, captains of larger Coalition freighters and transports can use large thrust modules to rapidly slow their ships, allowing them to save both time and energy."
	description "	Because a reverse thruster must be facing forwards, it must be installed in the weapon section of your ship instead of the engine section."

outfitter "Coalition Basics"
	"Small Thrust Module (Reverse)"

outfitter "Coalition Advanced"
	"Small Thrust Module (Reverse)"
	"Large Thrust Module (Reverse)"
```

### Alternative Approaches

I suppose the Coalition might have some reason for not re-using the thrusters as reversers (either creating new outfits or forbidding it entirely), but I'm not sure how that would fit in lore-wise.

### Additional Context

Balance notes:

The small engine package comes in at 25 tons versus the 26-ton anvil, and has better energy efficiency but much lower performance and produces more heat. That doesn't seem game-breaking for small late-game ships.

The large thruster produces almost twice the thrust of the AR120 for a 50% increase in tonnage at roughly the same energy input, but creates over three times the heat and twice the cost. That seems doable for very large merchant ships and a bad deal for warships, which probably shouldn't break anything.

Given the open space in the default Coalition ship configurations, it would be fairly easy to drop some of these into the default designs and have the locals use them.

**Comment by 3519421** [comment]
Second version of the testing plugin with Coalition merchant ship main thrusters duplicated into reverse thrusters: 
[coalition-reverse.txt](https://github.com/endless-sky/endless-sky/files/8788927/coalition-reverse.txt)

Even on the smallest ships, they have tons of room left over, and (given the energy efficiency of reverse versus turn-slow-turn) none of them seem to have any power issues (I watched them for a while, using tac scan to monitor energy).

**Comment by Arachi-Lover** [comment]
I think that for the names, `Small Reverse Module` and `Large Reverse Module` would work better.

**Comment by 3519421** [comment]
Demo with placeholder images (mirrored thruster) and fixed names (the shorter ones fit, thanks [Arachi-Lover](https://github.com/Arachi-Lover)!): [Coalition Reverse Thrust.zip](https://github.com/endless-sky/endless-sky/files/8789361/Coalition.Reverse.Thrust.zip)
