### ISSUE TITLE
Sloppy save game deletion

### ISSUE THREAD

**Issue by pilover100** [endless-sky/endless-sky#6882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Reported on discord by @matthew.najmon](https://discord.com/channels/251118043411775489/536900466655887360/980143833239142471)

When deleting a pilot, the dialogue asks the player to enter the pilot name to confirm deletion, however in reality the save *file* name is required.

### Steps to Reproduce

1. Create a test save game/download one
2. Alter the filename so that the pilot name and file name do not match
3. Attempt to delete the pilot and enter the *pilot* name, observe that it does *not* work
4. Attempt to delete the pilot and enter the *file* name, observe that it *does* work

### Expected Behavior

Entering the pilot name allows deletion

### Screenshots

![image](https://user-images.githubusercontent.com/65236599/170834704-a53bb8ab-27df-4ca2-ac6f-540eaa5f6a7a.png)
Deletion is still blocked when the pilot name is entered (the `ok` button is inactive)

### Link to save file

Any save will do, but here's a throwaway save you can use: (file name and pilot name don't match)
[recent.txt](https://github.com/endless-sky/endless-sky/files/8791493/recent.txt)
 

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

cd27c56cfef27b96ba1b08cd9eebbfb26a6a6f98

**Comment by pilover100** [comment]
I can write a patch for this, but would it be preferred to prompt the player for the file name or actually check the pilot name? I can do either methods.

**Comment by quyykk** [comment]
Probably the pilot name, not the file name.

**Comment by pilover100** [comment]
Ok, I'll work on a patch then
