### ISSUE TITLE
[Question] what is the mass and volume of a fighter bay?

### ISSUE THREAD

**Issue by daggs1** [endless-sky/endless-sky#6884]
### Problem Description

I was wondering, what is the mass and volume of a fighter bay?
is there a way to calculate what is the affect on a ship with and without?

Thanks

### Related Issue Links

None

### Desired Solution

an explanation would suffice

### Alternative Approaches

maybe the game has that feature already?

**Comment by quyykk** [comment]
I believe bays have 0 mass if they are empty. If a fighter/drone is docked though then its mass is added to the carrier's total mass.

**Comment by Zitchas** [comment]
The volume is probably somewhere around 200 (units), but also has the problem of "which kind of bay?" We have bays where the fighter is just clamped to the outside of the ship, and we have bays that are proper bays inside the ship. The former technically are infinite in volume.

**Comment by daggs1** [comment]
thanks for the explanation, is there a way to know which bay is which?

**Comment by Zitchas** [comment]
The main way would be the obvious one: Look at a ship with fighters/drones in its bay. If you can see the ships stuck to the outside, it's an external style. (Ibis, for example).

**Comment by daggs1** [comment]
so given a ship, the best way is to zoom in and look if I can see them on the ship?

**Comment by Zitchas** [comment]
It's either that or dig through the code.
` (fighter | drone) <x#> <y#> [over | under] [left | right | back]`: specify a fighter or drone bay at the given (x, y) coordinates, e.g. drone -14 64.

If the bay doesn't specify over or under; then the fighter isn't displayed at all. But there's really no concrete way to tell from the shipyard stats whether a bay is the internal or external type, unless the description happens to mention it.

**Comment by daggs1** [comment]
no problem to dig into the code. just thought it can be easy to find out

**Comment by daggs1** [comment]
thanks for confirming, all in the code, see: https://github.com/endless-sky/endless-sky/blob/master/source/Ship.cpp#L705

**Comment by daggs1** [comment]
btw, what does 200 (units)? doe example, the Aerie class has 50 tons for cargo, what is the ratio between units and cargo?

**Comment by Zitchas** [comment]
Sorry, don't read too much into that. I'm just poking at the fact there are a lot of different ways to measure cargo in real life, lots of different kinds of tons too. Some are volume, some are mass. It isn't actually nailed down in ES exactly which kind of it is.

**Comment by daggs1** [comment]
is there any radio? 1 to 1 is reasonable scenario?

**Comment by daggs1** [comment]
how about this ratio, each ship with internal bay can host one ship which is the heavyset of all.
so imho, the value should be 0.8 of the weight of that ship * num of internal bays. I assume that there isn't any limitation of which ship to enter in which bay, correct?

**Comment by Zitchas** [comment]
Only fighters can enter fightery bays. Only drones can enter drone bays. So long as those categories match, there are no other restrictions currently.

**Comment by daggs1** [comment]
so there are internal bays for fighters and bays for drones?

**Comment by Zitchas** [comment]
As in there are bays that those specific so categories go inside, yes.
