### ISSUE TITLE
Escorts ordered to jump out of system first hunt down and attack everything they can

### ISSUE THREAD

**Issue by alextd** [endless-sky/endless-sky#6889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you use the Map screen to issue orders to jump to another system, your escorts instead first attack whatever they can in the current system.

### Steps to Reproduce

1. Have escorts.
2. Go to any system with moderate pirate presence (enough hostiles to show up soon but few enough to destroy quickly)
3. Wait for hostiles to appear.
4. Open Map screen (M), select another system, right click on the top-right system map to order escort jump to that system (see that the order reticle appears)
5a. Escorts will first hunt down and attack any hostiles in the system <- bug
5b. Escorts will jump, only once there are no hostiles in the system.

### Expected Behavior

5a should be skipped. Escorts should just jump, as that is the order.

### Screenshots

![image](https://user-images.githubusercontent.com/101399/171078052-200ae38b-fd9c-41e5-bbf9-f0a43d68b560.png)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.9.13

### Additional Information

Well! I have poked into the Code. It appears the escorts follow the `MoveIndependent` code, which pretty simply attacks ships before it even considers leaving the system. That's normal AI for any NPC ships, but not good for escorts with orders. 

So honestly the only section of `MoveIndependent` that the escort should use is the `if(ship.GetTargetSystem())` clause. So instead of Calling `MoveIndependent` from `FollowOrders`, those 4 lines of code should just be copied into there (as I'm seeing they are repeated in a few places in the code)

**Comment by daveeater** [comment]
I can confirm that I've seen this behavior (in Mesuket) with captured Korath drones - where there are _usually_ hostiles to attract their attention.  My standard procedure with such captures is to issue a "gather" command (G), and lead the captured drone well away from the system center, at which time they will respond properly to a map-issued order to go to another system (usually Sevrelect).

**Comment by alextd** [comment]
Okay I made the code for this. Instead of copying code out of MoveIndependent, I added the check for escorts to ignore targets.

**Comment by tehhowch** [comment]
This was a known issue with the implementation of the feature
https://github.com/endless-sky/endless-sky/pull/2678#pullrequestreview-457117403
