### ISSUE TITLE
Why can we no longer tell our escorts to finish off a ship?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#689]
When I first started playing, a useful feature was that we could click on a ship and press F again to make them finish it off. It was mainly useful for smaller ships attacking bigger ships, where you could remotely make them explode and not wipe your smaller ships out later when they aren't expecting it

**Comment by endless-sky** [comment]
That's a result of the fix for bug #97 (change 640353c). I suppose I could make it so that if you order an attack on a disabled ship, that overrides the normal behavior where disabled ships are left alone.

**Comment by thenerdfreak** [comment]
oh, attacking your own ships was a bug too? i found it extremely useful for keeping ships you didn't want to get rekt out in deep space while the other ones were still fighting

**Comment by endless-sky** [comment]
This should be fixed in 7b5ebe9.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
