### ISSUE TITLE
Mass Expansion is a plunderable outfit

### ISSUE THREAD

**Issue by rktaylor** [endless-sky/endless-sky#690]
Not sure how this would be fixed, but it is kind of funny that you can plunder Mass / Cargo expansions from captive ships.

**Comment by thenerdfreak** [comment]
At least you can't plunder your own ships, or this could be used to make any other heavy warship into a bactrian

**Comment by ph2000bis** [comment]
@thenerdfreak I'm sorry, I don't see how plundering your own ships can increase your cargo capacity or mass expansion, since it is stored in the cargo

**Comment by johndh** [comment]
Plundering a ship's mass expansions and then capturing said ship is the only way I know of to have negative outfit space.

**Comment by thenerdfreak** [comment]
@johndh that's what I was talking about lol

**Comment by egilburg** [comment]
@endless-sky Perhaps make explicit `plunderable `attribute on outfits, and only outfits with that attribute should be plunderable. 

Besides bugs like this, I feel it's both cheesy and too easy money-wise to steal stuff like reactors from disabled but non-boarded ships. Only externally-mounted outfits should be plunderable (guns, thrusters, steering, fuel pod, ramscoop). Stuff inside the ship, including reactors, batteries, jump drives, arguably shield generators (the shield force field is outside the ship, but presumably the generator itself is inside the ship hull), etc. should not be plunderable, but only stealable once you capture the ship itself.

**Comment by endless-sky** [comment]
Fixed in 0.9.0.
