### ISSUE TITLE
Outfit Image from Plugin Renders Incorrectly

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#6938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As part of a plugin I am writing, I have created a new license, with its own image. Opening the outfitter, the image appears, but is squished horizontally. The remainder of where the image used to be is replaced by either a transparent rectangle or one filled with random noise. Additionally, the channels appear to be swapped, since what remains of the image is now blue-purple with a transparent instead of black background.

### Steps to Reproduce

1. Install the plugin by placing the attached folder unzipped into the plugins folder.
[settlers-start.zip](https://github.com/endless-sky/endless-sky/files/8886140/settlers-start.zip)
2. Start a "Dawn of Exploration" game.
3. Land on Luna.
4. Check the outfitter.

### Expected Behavior

I expected that the image I had produced, having the same dimensions as all the other licenses, would properly render with the same dimensions and colours as the original.

### Screenshots

![license-TU@2x](https://user-images.githubusercontent.com/73318970/173240304-85ea911f-b6e9-4ed0-bb7a-0c81adecb66b.png)
^ 2x image of the license ^
<img width="391" alt="Screen Shot 2022-06-12 at 8 16 54 AM" src="https://user-images.githubusercontent.com/73318970/173240344-79c9c1f1-84c5-46c3-920c-4840cbeeed12.png">
^ The license in-game beside the pilot's license. ^

### Operating System

macOS Monterey 12.4

### Game Source

GitHub Releases

### Game Version

v0.9.14

### Additional Information

It is possible, since replacing the image with any other image not from that set worked, that the bug is a bug in Affinity Designer, the software I used to create the images. Nonetheless, everything else (including GitHub) appears to render them correctly.

The bug also occurs if I place the image in the application itself, rather than in the plugin folder, or if I place the image in a folder named "outfit" and then reference it.

**Comment by quyykk** [comment]
Not sure exactly what Affinity Designer is doing, but if I open the license with my image editor (Pinta) and save it again without any modifications then the outfit appears correctly.

**Comment by quyykk** [comment]
Seems like your images are saved without an Alpha channel. Not sure how that would cause them to appear like that though.

**Comment by alextd** [comment]
And a big chunk of confusion here is that the comments for DistanceMap assume one direction but it used in both directions. 'center' is either the destination or the source. Aiee.
