### ISSUE TITLE
Empty systems around Tarazed stay Republic-aligned during FW quest

### ISSUE THREAD

**Issue by airportation** [endless-sky/endless-sky#6949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems that when you progress the quest line and manage to take basically all Republic-controlled space within 5 jumps of Tarazed and then some to the north, the empty ones never actually say that you took them, despite being surrounded by Free Worlds aligned systems everywhere around them. This doesn't feel as if it should be the case.

### Steps to Reproduce

1. Do the FW quests in a way that annexes any number of worlds around Tarazed and Rand
2. Click on any uninhabited system in this region
3. At no point during the storyline will they change from saying they belong to the Republic

### Expected Behavior

For the empty systems to also be taken, provided the Free Worlds control the systems around them, which is the case for all the ones I have underlined in my screenshot.

### Screenshots

![republic systems](https://user-images.githubusercontent.com/67428677/174490131-4b71029d-8929-4d93-8466-46cf7a93f981.png)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

0.9.15, build 0a94bee

**Comment by DJ-EGG** [comment]
While 2 of the systems (orvala and boral) do now show correct alingment, there are still at least 10 others (Sadr, Lurata, Umbral, Eltanin, Tais, Naper, Hintar, Alpha Arae, Eber, and Alnasl) which have yet to be corrected. I have created edited versions of the governments and human events files in the unstable branch that provide a band-aid level of relief. changes are documented with coments that are marked by "PATCH/egg". 

These changes do not cover the Checkmate branch as I'm not familiar enough with the path to warrant it's alteration. as a result, this is not at all workable for Checkmate runs.

Fleets are left mostly unaltered as I don't trust myself to have the correct judgement when it comes to balancing this.

As stated before, this is just a band-aid level patch. it should not at all be used in the current version's place (especially the stable branch)

If there is anything I have done wrong, I apologize as this is my first time using github for anything of this significance. If there is something else I should have done, please let me know

this was done on the steam version of the game. I don't know if there are any differences between the github download and the steam download, but if their are, I would bet that this patch will break.

[governments.txt](https://github.com/endless-sky/endless-sky/files/11325094/governments.txt)
[events.txt](https://github.com/endless-sky/endless-sky/files/11325095/events.txt)
