### ISSUE TITLE
Scientific Descriptions/Behaviors Update

### ISSUE THREAD

**Issue by rktaylor** [endless-sky/endless-sky#695]
I'm a big fan of how scientifically accurate the outfit descriptions are, so I wanted to make a suggestions for engines/reactors.

FUSION REACTOR
Almost all practical fusion designs (inertial confinement aside) require huge magnets, which use superconductors and therefore have to be very cold... 
The Hai Ion Cannon should be able to actually REDUCE energy production (and not just energy storage) for ships with Fusion Reactors. Similarly, plasma guns ought to also degrade Fusion energy production. Fusion reactions themselves are about four times as efficient as fission reactions, so one could increase fusion power output but add the limitation that Plasma and Ion weapons dramatically decrease their energy output.

PLASMA THRUSTERS
It's interesting that ion and plasma thrusters are different categories, as ion engines (irl) produce steady plasmas as propellant. There is one scientific line to draw between ion/plasma propulsion: "fusion" rockets. A Z-Pinch fusion rocket would produce much more power than an ion rocket (see: https://www.researchgate.net/publication/256935157_Z-Pinch_fusion-based_nuclear_propulsion ) but also require much more electrical power to operate. Perhaps the description could be altered to reflect this distinction?

ILLEGAL FISSION REACTORS
Since the lore of the story forbids nuclear weapons, maybe have a Plutonium Reactor? Since Plutonium is man-made and weapons-grade, it would be an illegal (but high performance) outfit.

**Comment by endless-sky** [comment]
There's real science, and then there's sci-fi science. :) The way the
existing outfits work is designed to be a simple as possible to understand
(minimizing "special rules" and unexpected interactions), with complexity
added only where it will make game play more interesting.

Note that "ion thrusters" and "plasma thrusters" are indeed two (somewhat
overlapping) classes of thrusters that exist today:

https://en.wikipedia.org/wiki/Ion_thruster
https://en.wikipedia.org/wiki/Plasma_propulsion_engine

But of course, neither of those can produce anywhere near the amount of
thrust that the ES engines do. Also, in real life those thrusters consume
fuel. The "atomic thrusters" are intended to be a thruster where the
exhaust is accelerated via some sort of nuclear reaction (similar to that
fusion rocket article).

**Comment by rktaylor** [comment]
Touche! I guess I'm just antsy to find something to contribute, especially since you've been very methodical about emphasizing the sci in your scifi. (Hence, using high-specific impulse thrusters so you can simplify fuel requirements in ES.)

**Comment by Hyratel** [comment]
considering the three thruster classes are Ridiculously OP compared to their RL namesakes, Atomic thrusters sounds more like Nuclear Thermal Rockets in this case
