### ISSUE TITLE
Final battle screen assist requests flood the chat

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#696]
http://steamcommunity.com/sharedfiles/filedetails/?id=603717230

If this is still the case, maybe turn it of? It seems a little extreme

**Comment by endless-sky** [comment]
I guess the right solution would be to keep track of how many ships have already asked for help recently and limit that to a reasonable number...

**Comment by Wrzlprnft** [comment]
I guess, in a real space battle, especially when several merchant ships are part of it, a flood of help-messages would be correct, i guess, but not in a military strike

**Comment by endless-sky** [comment]
In commit 4c31096 I've limited the requests for assistance to no more than one every 2 seconds, so at most 9 of them will be on-screen at once.

**Comment by Wrzlprnft** [comment]
Should address the issue.
