### ISSUE TITLE
Add family names to the human names file

### ISSUE THREAD

**Issue by LazerLit** [endless-sky/endless-sky#6968]
### Problem Description

We have male names and female names but no family names, so if you want to give a character who is generated for a mission a full name, you currently can't.

### Related Issue Links

N/A

### Desired Solution

Add a list of family names to the names file. I have already sourced a list of names from the US Census bureau and formatted them so they can be pasted in, they are in the comment below.

### Alternative Approaches

N/A

**Comment by a-random-lemurian** [comment]
By the way you can use codeblocks
```
Like this
```

Since I had to endure that long wall of family name text.

**Comment by LazerLit** [comment]
> By the way you can use codeblocks
> 
> ```
> Like this
> ```
> 
> Since I had to endure that long wall of family name text.

Thanks! I edited the previous comment to make it a code block, but it didn’t collapse it for me. I can see that it is possible to do that using;
`<details>
  <summary>Click to expand</summary>
  whatever
</details>`
…but my intention was for the comment to be easy to just copy-paste for whoever can resolve the issue.

**Comment by LazerLit** [comment]
PR #6910 fixed this issue.
