### ISSUE TITLE
Remote ship capture

### ISSUE THREAD

**Issue by zwparchman** [endless-sky/endless-sky#697]
A newly captured escort can be used to remotely capture a ship.

To reproduce: Use a cloaking device to avoid the attack of a ship attacking you. When this ship goes to board another ship (both ships were pirates in this case) de-cloak and disable the ship going to board. After capturing the boarding ship it will go on and board it's target that it had before you attacked. The player can then use the flagship's crew and outfits to remotely capture a ship.

**Comment by BuildBruh** [comment]
Maybe this can become a mechanic in the game? It'd be nice to not have a bunks-only bactrian as my 'fearsome' flagship ;u;

**Comment by rktaylor** [comment]
Yeah I'd be a big fan of having "Use Escort to Capture" (or even any level of ship micromanagement) so I could have a Flagship Bactrian and a Bunk Bed Castle Bactrian.

**Comment by endless-sky** [comment]
Fixed in commit eee19de.

The idea of allowing escorts to capture ships has been brought up before, but given how overpowered ship capture already is, I'd prefer not to add a new mechanic that makes it even easier.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
