### ISSUE TITLE
Unable to change flagship

### ISSUE THREAD

**Issue by zwparchman** [endless-sky/endless-sky#699]
I can not change my flagship via the normal methods.

Moving it to the first slot in both the outfitter and shipyard has no effect. My flag ship remains unchanged.  There is also weird behavior when selling the flagship. I expected to be put into the next escort ship but instead I was not given a ship upon departing. Loading seems to have fixed that.

**Comment by endless-sky** [comment]
Is the ship you are trying to switch to a fighter or a drone? If so, you
can't use it as your flagship.

**Comment by zwparchman** [comment]
It was the medium warship "Corvette" I was attempting to replace another medium warship.

**Comment by endless-sky** [comment]
Found the bug. Commit 3d34444 should fix this.
