### ISSUE TITLE
If a systems outermost planet has rings, the rings will sometimes go off the map

### ISSUE THREAD

**Issue by eebop** [endless-sky/endless-sky#6999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a systems farthest-out planet has rings, those rings can go over the edge of the minimap 

### Steps to Reproduce

Go to map, click on Miaplacidus and then ports, and sometimes (if the ringed planet is at the very bottom), it will go off the map

### Expected Behavior

The rings wouldn't go off the map
I think that this is just because the 

### Screenshots

![Screenshot from 2022-07-02 12-04-56](https://user-images.githubusercontent.com/68796004/177013595-6a1deee4-2462-4c8b-8358-15d789c312f9.png)

### Operating System

Ubuntu 22.04

### Game Source

GitHub Releases

### Game Version

0.9.15 alpha 2a024ed

**Comment by eebop** [comment]
This is probably just because the shrinking of the map to fit the planets doesn't take into account the size of the rings of the outermost planet

**Comment by thvk-net** [comment]
I am working on this right now.
