### ISSUE TITLE
Ship communication: you can ask your own ship for help

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#7]
By cycling through target ships in the vicinity, you can target yourself and speak with yourself.

**Comment by endless-sky** [comment]
I can't seem to reproduce this. I tried both the "cycle through nearby ships" key, and "cycle through player's ships" (which is SHIFT + that key) both when the player's ship is active and when it is disabled. The "select nearest" command doesn't seem to do this either. Are you sure you weren't just talking to another ship of the same type as your own?

**Comment by akien-mga** [comment]
I'm pretty sure it had the same type as my ship but also the same name "The Kestrel". I'll see if I can reproduce or not.

**Comment by akien-mga** [comment]
Well it does look like there is a ship named "The Kestrel" in data/kestrel.txt, so maybe I just encountered my doppelgänger :-) Closing as invalid then.
