### ISSUE TITLE
Stuck in mission "Remnant: Cognizance 1"  ->  "Follow-up Observations"

### ISSUE THREAD

**Issue by taschenlampe** [endless-sky/endless-sky#7008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems like I got stuck in this mission, I have all needed(?) scanner for analyse the system.
I have scanned the lifeforms, but there is no success while doing it.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

I would have supposed to scan some lifeforms, then get a feedback about it, then return to mission planet and continue.

### Link to save file

https://susepaste.org/56841942

### Operating System

OpenSuse TW

### Game Source

ESLauncher2

### Game Version

continuous

### Additional Information

Please tell me how I could provide more info that would help tracking down this issue.
Cheers!!

**Comment by Zitchas** [comment]
Have you landed on Nasqueron and Slylandro? Those are the two stopovers on this mission.

**Comment by taschenlampe** [comment]
Hi!
Thanks for the swift feedback.
Ah....I need a the "special" ship to land on the planets. 
Maybe it would make sense to add a little hint that one has to use this research ship in order to land on these planets maybe I have over-read this info while accepting the mission, I thought that having the 8t equipment + scanning the "lifeforms" would do the trick (I didn't play ES for quite a while and i forgot what ships would be able to to so)
