### ISSUE TITLE
New to game, please be kind

### ISSUE THREAD

**Issue by revjim2000** [endless-sky/endless-sky#701]
I just started playing the game, but was a huge escape velocity player back in the day. Is there a story board that can help me find the storylines to play through? I've been playing sandbox style for a few days, managed to get the Kestrel built and take over a few pirate planets, but I would like to find more storylines. If this is the wrong board for this kind of request, just point me to the right one. Thanks!

**Comment by natangold** [comment]
The [forum](https://groups.google.com/forum/#!forum/endless-sky) is a better place for this - this place here is for @endless-sky to keep track of bugs, issues, and feature requests (and for the rest of us to help contributing to the game). As for finding more storylines, there's a good chance you've already found most if not all - the Free Worlds is the only storyline fully implemented as yet.

**Comment by mdsmestad** [comment]
And please close this issue. Thankyou
