### ISSUE TITLE
Remnants faction never ending mistrust

### ISSUE THREAD

**Issue by tukoz** [endless-sky/endless-sky#7023]
### Problem Description

Upon saving dozens of Remnant ships in the Ember Waste and the somehow dangerous Graveyard, and before that having received their Military license, toured their prefects up and down the galaxy and back home, showed them a Quarg ship's outfits, as well as a few other services I've forgotten the details: I would think they kinda trust us, right?

Yet they keep: 1) keep scanning each of my ships after each jump (you know, that continuous biii biiii sound all the time one of their ships is around and biii biiii biii biiii biii if there are more than one of their ships). 2) Declare war and shoot at us the very instant we dare scan one of their ship.

I know of -- and understand -- their initial fears and precaution. Though how many friends (and trust) would one has if he or she kept on checking their pockets *all-the-time* ?

### Related Issue Links

I searched for a similar suggestion and have found none so far. Maybe it's me alone getting sensitive upon being scanned for the ten millionth time lol.

### Desired Solution

A faction that trusts a player enough to give him or her their Military license (including most advanced techs) should stop being so adamant on scanning their ship every freaking tick. And probably not declare open war the instant the player dare scan one of their ships.

### Alternative Approaches

Maybe the (story) goal is to be avoided at all cost. E.g. to show the damage fear and distrust can have on a whole people's psyche. Though this would make the Remnants a dead end once a player has got enough, even he understood the cause.

**Comment by quyykk** [comment]
Related #6947

**Comment by warp-core** [comment]
There is currently a PR, which I assume is the only quyykk just linked above this, which will show the Remnant telling you that they will allow you to scan their ships.
As for scanning your ship, the content of that PR explicitly states that the Remnant view scanning your, and each others' ships an added security measure, they may trust you but that doesn't mean your ship can't be contaminated/infiltrated/taken over, etc.

**Comment by Zitchas** [comment]
My PR solves the lore trust issue, but the non-stop scanning is a function of the game engine. Every faction that scans ships first the same thing. It would be good if we could set a scanning frequency or limit it to one scan per faction per system or something, but that would be a coding change.

**Comment by Hurleveur** [comment]
I can take care of the code side of it, if you just want each of the ships in the system to get scanned once at most by a faction.

**Comment by tukoz** [comment]
@Hurleveur Ah wooow, that could even help (audiophile) players count their ships, nice feat' !o)

**Comment by Zitchas** [comment]
Best case scenario, I think, would be the ability to define a default in the government, with the option to override it with a personality in the fleet definition. Perhaps easier might be to have the government determine the frequency of scanning, and the "scanning" personality determines *if* the ship scans.

At the government level, I can see three options:
- Each government scans every ship once.
- Each fleet scans every ship once.
- Each ship scans every ship once.

For sanity, I would prefer/expect the first option "Each government scans every ship once" to be the default. Given the opportunity, I'd probably have the Remnant start out as the "each ship scans every ship once" option, then quickly shift to "each fleet scans each ship once" once the player has the basic license; and then move to "Each government scans every ship once" once they reach the trusted state currently included in the PR.

**Comment by Hurleveur** [comment]
Yeah that sounds good, we dont want to be changing the syntax of personalities to add a number to it so best do the parameters in the government itself

**Comment by Joachim-Otahal** [comment]
I know I am posting on a old thread, but google search shows this in the first hits.
I don't care about the scanning per se, but as for 0.10.10 the constant beeping goes for over 5 minutes to 15 minutes each time I (re-)enter a remnant system with 46 ships.
Solution for me: Rename "\Endless Sky\sounds\scan~.wav" to "\Endless Sky\sounds\scan~_.wav"
Enjoy the sound of silent scanning.
