### ISSUE TITLE
Remnant: Dawn Aescolanus mission offers in Postverta/Ssil Vida

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#7026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have just taken Dusk to Ssil Vida and he has asked me to bring an Aeon cell. We are the only two people on the station. This mission offered immediately after.

 

### Steps to Reproduce

I'm not sure you could easily reproduce as it would be dependent on mission timing.

### Expected Behavior

This mission should only offer on the Remnant home worlds, not Ssil Vida, and probably not Esqualine.

### Screenshots

![Screenshot_2022-07-12_18-22-49](https://user-images.githubusercontent.com/70952724/178555479-bd2fe4a0-3fa0-4945-ace1-670177a93e01.png)

### Link to save file

[Scrappy Doo.txt](https://github.com/endless-sky/endless-sky/files/9095442/Scrappy.Doo.txt)

### Operating System

Linux EmberWastrel-8088i 5.18.10-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Jul 7 16:55:16 UTC 2022 x86_64 GNU/Linux [williaji@EmberWastrel-8088i ~]$

### Game Source

ESLauncher2

### Game Version

49477739dc57c8ac78d199139ef72e23017e358d

**Comment by tibetiroka** [comment]
Resolved by #8853
