### ISSUE TITLE
Development Diaries

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#703]
Something that outlines future planned locations, races, storylines, etc to ensure people who are writing stories don't basically do everything you're doing and waste time

**Comment by Gkramme** [comment]
I like this idea, but this is a bug tracker. (Before endless-sky does this)

**Comment by natangold** [comment]
Something similar, at least insofar as map-space is concerned, is already in place in the [forum](https://groups.google.com/forum/#!forum/endless-sky).

**Comment by endless-sky** [comment]
Yes, in particular check out [this thread](https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/arUG0bsx4Pw) which has a map of planned additions to the map.
