### ISSUE TITLE
Outfitter stats for bulk freighter are labeled wrong

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#704]
The stats are being displayed as

mass:   1262
cargo:   0/615
fuel:      700/700

With other ships and in other places with this ship the it would be displayed as 

mass with out cargo:    1262
cargo space:                 615
fuel capacity:                 700

It also isn't showing movement with and with out cargo.
This is only a small inconsistency.

**Comment by endless-sky** [comment]
Did you buy this ship from the shipyard, or did you edit it into your saved game? The only way I can see that it would do that is if the ship has neither a name nor a planet defined.

**Comment by jafdy** [comment]
I got it from a ship yard.

**Comment by jafdy** [comment]
The problem seems to have expanded to include all but one of my other ships as well.

**Comment by endless-sky** [comment]
Can you post a saved game?

Does the problem persist from planet to planet?

**Comment by jafdy** [comment]
[Jon Lake.txt](https://github.com/endless-sky/endless-sky/files/102230/Jon.Lake.txt)

It is persisting from planet to planet.

**Comment by endless-sky** [comment]
Fixed in commit 3d09e98. The game wasn't counting the ships as being landed on the planet if they did not land along with you, and when a ship is not landed the format of the info display changes.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
