### ISSUE TITLE
Create some way to custom organize ships and outfits in the shop

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#7046]
### Problem Description

Currently, ships and outfits in the shop are organized first by category, then alphabetically. This alphabetical sorting has led to a convention where we attempt to name outfits in a series (i.e. a set of engines, shields, batteries, or any other outfit of similar design) such that they appear in either ascending or descending size order in the outfitter. Not all outfit series are named this way, but many are.

Going even further beyond naming outfits in a series such that they sort this way, there have also been attempts in naming outfits such that outfits of a series always appear, well, in series, not broken up by any other outfits that could potentially be visible in the outfitter. A good example of this is how all Hai engines start with B, or all ion engines start with X, or all human atomic engines start with A, but the biggest culprit of this is among some Korath outfits, including their engines, system cores, and weaker generators, whose names are stuff like "System Core (Small/Medium/Large)," "Generator (Candle Class)," "Steering (Asteroid Class)."

I believe that it is desirable to sort outfits such that they appear in ascending or descending size order and appear in series as opposed to being broken up by other outfits, but I do not think we should limit ourselves to needing the names to be alphabetical in order to achieve this. 

### Related Issue Links

N/A

### Desired Solution

Create some way of ordering outfits (and ships) in the shop that is not connected to the names.

My first thought is to allow ships and outfits to have an index number. All items with an index number appear in the shop in ascending order of their index number. All items without an index number appear alphabetically after all indexed items. Any two items with the same index are sorted alphabetically within their index.

The main pitfall with this approach though would be that should we want to insert a new item into the middle of the index list, we'd need to increment the index of all items above it. Although this could perhaps be avoided by not having every index position be occupied. For example, human ion engines could occupy indices 0-6 (tiny, small, medium, large, huge, combo, tiny reverse), but human plasma engines would occupy 10-15 (tiny, small, medium, large, huge, tiny reverse), leaving index room between the two series so that we have space to add more if necessary. Then something like Hai engines might start at index 100.

To avoid that pitfall, instead of just an index number, we could have a series number then an index number. Using the example above of human engines and alien engines, human ion engines could be series 0 then indexed 0-6. If we add any new human ion engines then they would also be series 0 and get a new index number. Human plasma engines would then be series 1 with their own index numbers. So items would be sorted first by series in ascending order, then by index in ascending order. Something like Hai engines then might start at series 5. 

But then say that human engines have series 0-4 (ion, plasma, atomic, misc) and the Hai engines start at series 5, but we want to add a new series of human engines; we're back to the same issue that simply indexing all items has. So I think that in the end what we could have is three rank-ordered numbers for each item: a faction # (allow us to sort entire factions of items), a series # (allow us to have multiple series of a similar outfit in the same faction), and finally an index # (allow us to sort items within a series). This would give us as much space as we could ever need to say add more engine types to human space and never have to mess with the sorting numbers on any alien tech, as human tech would always appear first. And since factions are added much less commonly than anything else, we could create the faction numbers such that there's always room to place factions between one another if we desire to do so. For example:

Faction | Faction #
---|---
Humans | 100
Hai | 200
Remnant | 300
Ka'het | 400
Korath | 500
Wanderers | 600
Coaliton | 700
Quarg | 1000
Pug | 2000
Drak | 3000
Misc | 10000

If we wanted to sort a new faction below humans, we'd then give then the faction number 50, leaving room above and below for more new factions, and so on for any new factions placed at any point. (If you wanted to get more fancy with it, we could have faction numbers increment by 128 so there's always an even midpoint to add to.)

### Alternative Approaches

Instead of a purely numbered approach, we could perhaps have a list somewhere that defines how sets of items should be sorted. With the above suggestion, I'm imagining `faction`, `series`, and `index` number attributes on all items that we want to sort. But we could perhaps have `faction` and `series` be names instead of numbers.

It is currently possible for us to create new categories of ships and outfits. Categories are special word attributes attached to outfits and ships that determine the category they appear in in the shop, but the order that those categories appear in is defined by the order that the categories are listed in categories.txt. So perhaps the ordering system for items within a category could look something like this:

```
category "faction"
	"Misc"
	"Human"
	"Hai"
	"Remnant"
	...
	"Quarg"
	...

# One possible way of defining a series:
# A single "series" category that all items can look at to determine how they should be sorted.
# Since items are sorted by faction first, then series, but we only have one series category,
# we can use the same series name across multiple factions, or define series names
# wherever we want in the list so long as they're sorted how we want within a category
# and faction.
category "series"
	# Engines
	## Human engines
	# Despite the comment, there's nothing stopping you from using these series names
	# on items that aren't in the engines category or the human faction.
	"Ion"
	"Plasma"
	"Atomic"

	# For the sake of example: with only one series of Hai engines, we don't need to define
	# a series name for them, as the faction name alone would handle the sorting. But say
	# that the Hai had "Atomic" and "Super Atomic" engines. The "Atomic" series is already
	# defined above under the human engines comment, but we could define a separate
	# "Super Atomic" series here. Hai engines could then use the "Atomic" and "Super Atomic"
	# series names, and the "Atomic" engines would always show up before the "Super Atomic"
	# engines.
	## Hai engines
	"Super Atomic"

	# Power
	"Battery"
	"Solar"
	"Fuel"
	"Nuclear"
	"Exotic"
	
	# A catch-all series that could be used across multiple categories or factions and would
	# always appear at the end of a list.
	"Misc"

# Another possible way of defining a series that avoids having one massive list that all
# categories share:
# The series list for the Engines category. Only outfits in the Engines category could use these series.
category "series: Engines"
	"Ion"
	"Plasma"
	"Atomic"
	"Super Atomic"
	"Misc"

# The series list for the Power category. Only outfits in the Power category could use these series.
category "series: Power"
	"Battery"
	"Solar"
	"Fuel"
	"Nuclear"
	"Exotic"
	"Misc"

outfit "X1100 Ion Thruster"
	category "Engines" # Categories already exist; this is the first layer of ordering.
	faction "Human" # Human faction is defined first; will appear before all other engine factions.
	series "Ion" # Ion series is defined first; will appear before all other engine series in the human faction.
	index 0 # First position among the ion series.

outfit "Capybara Plasma Thruster"
	category "Engines"
	faction "Human"
	series "Plasma" # Will appear after all ion engines in the human faction.
	index 5 # 5th position among the plasma series, assuming indices 0-4 are used and present.

outfit "Ionic Afterburner"
	category "Engines"
	faction "Human"
	series "Misc" # Will appear after all other engines in the human faction.
	index 1

outfit "Bellows-Class Afterburner"
	category "Engines"
	faction "Remnant" # Remnant is defined after human in the faction category; will appear later in the list
	series "Misc" # Uses the same series as the Ionic, but the faction has already sorted it after all human outfits.
	index 0
```

While this approach would probably be easier to work with in vanilla since changing the order of entire factions or series of items is as simple as copying and pasting a name into a different position in a list instead of going to all items that are affected and changing their faction and series number, I imagine this approach would be less useable for multiple plugins that all want to sort their factions and series between preexisting ones, as only the last loaded plugin would get to enforce its ordering and all other plugins would have their items out of place of where they want them; with the numbered approach, plugins could guarantee where their items would appear relative to vanilla items.

### Additional Context

In the past there's been requests to add more outfit categories, as the Systems category is rather bloated with different types of outfits right now. This issue would allow us to sort outfits within the Systems category so that for example all scanners show up next to each other and all shield generators and hull repair show up next to each other, making searching through the Systems category when you have a lot of outfits much easier without needing to split the category up.

**Comment by warp-core** [comment]
I like the approach of using species and series names (though, I would suggest changing 'species' to 'creator', the Coalition and Heliarch, for example, aren't species).

To address the plugin issue, instead of defining the ordering of the names, could we instead assign each species and series an index value? That way, a plugin can update the indices of existing sets and assign new ones indices. If a set already has that index, then both sets get it and are sorted alphabetically.

**Comment by Amazinite** [comment]
So change the category node from
```
category <name>
	<category>
```
to
```
category <name>
	<category> [<index>]
```
where not listing an index uses the previous index + 1 (with the starting index being 0)? That could work. By adding to the "category" node instead of creating some new node, we'd also make multiple plugins defining new ship and outfit categories better.

**Comment by Amazinite** [comment]
After thinking about this a bit more, I think a single `"series"` tag (or whatever we want to call it) would be enough, instead of having a `"faction"` tag on top of that, particularly when paired with Warp's idea/the feature from #7047 for ease of editing the organization of items. When writing up this issue, I was mainly thinking in terms of the Engines category, which you would likely first separate by faction before going any deeper, but when it comes to categories like Systems or Power, organizing by faction becomes less helpful. For example, I imagine it'd be better to first sort Power by batteries then reactors, then break that down by faction, but instead of having a faction tag followed by a series tag or the reverse, we could just have series tags that we decide to order by faction, e.g. "Battery: Human", "Battery: Hai", "Battery: Coalition", ..., "Reactor: Human: Solar", "Reactor: Coalition: Solar", "Reactor: Human: Fuel Cell", "Reactor: Hai: Fuel Cell", "Reactor: Human: Nuclear," etc. We might then do something similar with Systems, showing all scanners, then all shield generators, then all hull repair, then all core stat modifiers (e.g. bunks, expansions), then all drives, etc, with each subcategory (hey, that'd be another name besides `"series"`) being sorted by faction.

**Comment by Zitchas** [comment]
I'd definitely like to have some kind of attribute that identifies the faction, manufacturer, or source. Especially if I could *test* for outfits with that attribute.

Expanding a bit beyond that, it'd be good to have a flexible attribute system that can handle many descriptors that can then be used to filter, sort, or test for.

Ex. A heavy laser turret having. `attributes "beam" "human" "turret" "deep"`

And then being able to filter the outfitter to only show things with the "deep" attribute.

I realize that filtering isn't quite the same as sorting, but it could be much more useful in some circumstances.

**Comment by warp-core** [comment]
I don't think giving outfits (and ships?) a bunch of attributes/tags like planets and systems already get would be particularly difficult, but yes, that is different to this feature request.
