### ISSUE TITLE
Syndicate Test Dummies will respond to hails, ask for money

### ISSUE THREAD

**Issue by AbsolutelyLudicrous** [endless-sky/endless-sky#7049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Syndicate disable-dummy-and-scan missions, the dummy can be hailed and will respond with "If you want us to leave you alone, it will cost you 0 credits" - then clicking the bribe button will have your offer turned down.

### Steps to Reproduce

1. Go to Syndicate space with a sufficient combat rating to get target practice missions
2. Go to target system
3. Hail
4. Marvel at the robot's sense of self preservation

### Expected Behavior

It's a target dummy, why should you be able to talk to it in the first place? Propose changing to "(The ship does not respond to your hail)".

If talking is intentional, it probably shouldn't be asking for a bribe it won't take anyway.

### Operating System

Linux

### Game Source

Other (please describe)

### Game Version

0.9.14 Flatpak

### Additional Information

Target practice Vanguard also has laser rifles onboard for some reason. Could be explained as just standard Vanguard equipment, but it doesn't make much sense for a ship without a crew.

**Comment by mOctave** [comment]
Do you have a save file for this?

Generally test dummies have witty, philosophical dialogue when you talk to them.
The problem _might_ be that the NPC in the mission should have a "marked" personality attribute but only has a "target" one.

**Comment by leklachu** [comment]
>phrase "hostile test dummy"
>   word
>        "I'm not a robot, I'm a real boy!"
>    word
>        "...please don't kill me."

>on board
>    dialog \`The young captain of the <npc-name> runs onto your ship in terror, thinking you're about to blow up his ship. At last you have discovered the truth of the Syndicate test 'dummies'. You'll never fight one again.\`


.... So that's what Alondo meant by "they have many human rights abuses on record"

---

(no, I just made that up)

But I did take a quick look in the data and source files for 0.9.14 and it seems the test-dummy-specific hails are there, and the code to not ask for a bribe. I tried it out on 0.9.15 (built recently-ish from git) and 0.9.14 from flathub I don't see any request for a bribe no matter how many times I hail. As mOctave said, if you can provide a save file, or a definite set of steps to reproduce, that might help track it down. Are you sure you're updated to 0.9.14?

**Comment by warp-core** [comment]
Anyone able to reproduce this?

**Comment by xX-Dillinger-Xx** [comment]
@warp-core
I can not confirm this using 0.9.14 on windows.
I never received any messages reading "If you want us to leave you alone, it will cost you 0 credits" 
Every time I click on the `offer bribe` button I get "I don't want your money"
Sounds more like pirate hails. I wonder if the OP also had bounty missions accepted and got them mixed up. Anyway, this is so old we may never know. I vote close it. 

@AbsolutelyLudicrous Are you still having this issue? It would be nice if this issue could be closed.

**Comment by xX-Dillinger-Xx** [comment]
@warp-core 
No response from the OP and no confirmations in almost 2 years. I think it can be closed.

**Comment by Saugia** [comment]
For above reasons, closing this issue. If this behavior is rediscovered, please feel free to re-open it, and if possible, with a description of what happened prior to the occurrence.
