### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#7056]
### Problem Description

In the game the player has always to do jobs for other people. But why cant they hire services of other captains like escorts or other.
Therefore a service type of mission should be added to the game that can be seen on the job board.

### Related Issue Links

-

### Desired Solution

I do not want content that provides service missions but the possibilty to create them. Therefore I could imagine a `service` tag that works similar to the `job` tag.

### Alternative Approaches

I dont know.

### Additional Context

This was sparly discussed in PR #7016

**Comment by thvk-net** [comment]
Something I could think of could be an easy way to check if the player has running a special services, that enables him to accept other missions.
