### ISSUE TITLE
Mistake in wiki: CreatingMissions

### ISSUE THREAD

**Issue by leklachu** [endless-sky/endless-sky#7064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the Wiki, the information on Creating Missions

https://github.com/endless-sky/endless-sky/wiki/CreatingMissions

The section on 'jobs' within 'basic mission characteristics' has what's surely a mistake:

> This specifies where this mission will be shown, if someplace other than the spaceport. If it is a job, it will appear only if included in the job board (which only happens if the current planet matches the [destination filter](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#filters)).

Surely it will appear in the job board if the current planet matches the *source* filter?

(Apologies if there's a different place I should report/fix this.)

### Steps to Reproduce

Go to https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#basic-mission-characteristics

Scroll to the section on `(job | landing | assisting | boarding)` or search for

> This specifies where this mission will be shown, if someplace other than the spaceport. If it is a job, it will appear only if included in the job board (which only happens if the current planet matches the [destination filter](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#filters)).

### Expected Behavior

> This specifies where this mission will be shown, if someplace other than the spaceport. If it is a job, it will appear only if included in the job board (which only happens if the current planet matches the [source filter](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#filters)).

### Operating System

N/A

### Game Source

Built from source

### Game Version

N/A

**Comment by warp-core** [comment]
Yes, the current planet would need to match the source filters.
While whoever does it is there, I think the rest of the line could be made a bit clearer:

`If it is a job, it will only appear in the job board (and only if the current planet matches the [source filter](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#filters)).`

**Comment by Amazinite** [comment]
Got it.
