### ISSUE TITLE
The new map planet UI needs work

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#7065]
### Problem Description

The new map planet UI is incongruous with UI design from other panels in the game. Previously, and seen in other panels, the ribbons between UI elements would connect to one another, with UI elements at the end of a chain having no ribbons, having the ribbons wrap back into the edge of a UI element or of the screen, or having the ribbons fray off.

But as you can see from below, the new UI has ribbons in a straight cut that look like they should be attached to something on the top UI element, and overlapping ribbons between the two bottom UI elements.
![ui](https://user-images.githubusercontent.com/17688683/181850508-a7a36a33-af3e-423f-8310-c6a30debc1d6.png)

You can also see from the above image that I have Mars selected, but the "(not yet visited)" text is escaping the lighter selection box at the bottom.
![image](https://user-images.githubusercontent.com/17688683/181855068-d861a604-3643-492e-b515-3cc0ae134d58.png)

And the bottom and right edges aren't aligned.
![image](https://user-images.githubusercontent.com/17688683/181854888-26a02ae4-38ee-47cf-b618-16f158ca8c7b.png)

Beyond that, I do not think that the scrolling behavior is obvious enough. I thought something was broken when I tried to ~~use the scroll wheel to scroll~~ (nvm that works), then click and drag the panel to scroll, and also to use the arrow keys (which toggled the currently selected trade instead of moving pages on the planet panel), three methods which can be done for any other UI which can scroll. As it turns out, it's these two little blips that you have to click on in order to scroll, one of which is nearly colliding with the text of one of the planets.
![image](https://user-images.githubusercontent.com/17688683/181852651-59d70cde-872c-4bec-ba80-2f3c13ea3cd3.png)

### Related Issue Links

#2230
#6355

### Desired Solution

Redesign the UI to keep with the style of other UI panels. Perhaps do something akin to the following, moving the map system UI to the right instead of overlapping the planet list, and with the map trade UI being at the bottom of the screen instead of just below the planet list. This would still require that the map system UI and the trade panels be redone slightly to account for the ribbons no longer attaching to anything.
![image](https://user-images.githubusercontent.com/17688683/181853619-938b23c2-d0f7-409c-a84e-9fc6fa7d7df1.png)

For the scrolling behavior, perhaps if the system has four planets, the UI is extended so that you just barely see the top of the fourth planet, making it obvious that "hey, there's more here to look at." Then, clicking and dragging and using the arrow keys to change which planet is selected should be supported ways of scrolling the list.

### Alternative Approaches

Go back to the drawing board and just copy the shipyard/outfitter map panel UI, looking something like this, but with planets instead of ships.
![ui](https://user-images.githubusercontent.com/17688683/181854288-8b699105-f471-44cc-8f59-022cfcb88c6c.png)

This would give us better scrolling behavior, but the map system and map trade UI elements would still need reworked, and I think a big downside of this approach would be that for most systems the list would be very empty, which doesn't look good.

**Comment by Amazinite** [comment]
I also seem to have run into a bug. I added Mercury, Venus, Europa, Titan, and Oberon to Sol. When I select the system, Earth's sprite is missing on the first page.
![image](https://user-images.githubusercontent.com/17688683/181854979-20960d1f-0de9-48eb-8ad4-cbb2a48c433f.png)

And when I advance to the second page, it appears as it should.
![image](https://user-images.githubusercontent.com/17688683/181855020-c5b5c478-b39a-4114-ab09-51f8c32bc741.png)

**Comment by Terin** [comment]
Lots of cosmetic issues I'm working on, but there's also a loss of functionality: You can no longer select the government name to have government colors on the map, past the default start. Going to look into that now.

**Comment by Hurleveur** [comment]
I got scared a bit seeing this issue but it looks like there isnt any really broken thing its just about adjusting a few values which is quite easy to do, some of them even are in the interface.txt

The Earth image wasnt appearing necause there wasnt enough place to display it completely (it would have had the bottom go slightly over the UI)

I really dont want the UI to look like the shipyard's one as, yeah, that is easy to code but I already coded the hard part for it work this way.

**Comment by Hurleveur** [comment]
Also it would be really nice to be able to cut down the planet sprite to only display what fits on the UI, I tried doing it but couldnt really understand the complexity around drawing sprites partly

**Comment by leklachu** [comment]
This looks really cool! Though it threw me at first because I'm used to the old style so this immediately looks less clean until I get used to it.

Bug though: I can no longer click to see what planets I've visited - if I select "(has been visited)", it also selects the gvmt and the map colours according to government. I appreciated being able to see in the map which systems I've landed on every planet etc.

**Comment by Hurleveur** [comment]
Those bugs are already fixed by the PR linked to this issue, but thank you for mentioning them still!

**Comment by leklachu** [comment]
Ah, great. Sorry I didn't check those first :)

**Comment by gendalv** [comment]
Radar interactivity is pointless and unintuitive, it's tiny, whereas the planet&station list is an obvious place for interactivity. Currently you have to click on the planet/station on the list, then click on the tiny highlighted dot on the radar on the other side of the screen, then click done on another side of the screen, just to land on it.

**Comment by Hurleveur** [comment]
I never thought of selecting a planet to land on from the map view; I didn't even know that was a thing, which explains why that wasn't changed.

That extra feature you mention can be added by 2 simple lines so I'd be down for it.

**Comment by Hurleveur** [comment]
@gendalv https://github.com/endless-sky/endless-sky/pull/7316 I opened this PR to add that extra functionality

If smbd thinks of other things that could be improved... Shoot!
