### ISSUE TITLE
Event only triggered properly by date

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I attempt to trigger a complicated event (modifies systems, planets, shipyards, outfitters; visits systems; sets values; 2223 lines long) with a mission, I get the following error:
`Instantiation Error: Action "on offer" in mission "Dawn Intro 0" uses invalid event "remap universe"
`
However, when I comment out that part and instead add a date for the event to be triggered, it runs just fine.
Unfortunately, I can't just use a date for my purposes, because the event is supposed to happen before the beginning of the normal game and I don't want it to trigger when someone starts the vanilla game. 

### Steps to Reproduce

1. Download and install the plugin at https://github.com/mOctave/es-dawn/
2. Start up Endless Sky with debug information.
3. Start a new "Dawn of Exploration" game.
4. Look at the error message and the lack of either event or triggering mission in-game.

__To reproduce the event being triggered by date:__
1. Uncomment the second line of the events.txt file.
2. Comment out the 27th and 28th lines of the missions: intro.txt file
3. Follow steps 2 to 4 above.

### Expected Behavior

I expected that the event would be handled by the mission the same way it worked with the date.

### Operating System

macOS Monterey (12.4)

### Game Source

GitHub Releases

### Game Version

v0.9.14

### Additional Information

I haven't encountered this issue before, so I'm thinking maybe the problem is that Endless Sky can't handle having such a big event triggered by a mission. My smaller events in the same plugin have worked just fine when triggered by missions.

**Comment by mOctave** [comment]
I decided to split my event up into four chunks to see what would happen. It turns out that all of the event works except for the following part:

	government "Escort"
		swizzle 0
	government "Pirate"
		"attitude toward"
			"Independent" -.01

	set "Intro [0]: offered"
	set "Intro [0]: declined"
	set "Expedition to Hope 1: offered"
	set "Expedition to Hope 1: declined"
	set "Smuggler's Den, Part 1: offered"
	set "Smuggler's Den, Part 1: declined"
	set "event: war begins"
	set "chosen sides"
	set "main plot completed"
	set "FW Vanilla Escort Removed A: done"

	visit Sirius
	visit Procyon
	visit Pollux
	visit Talita
	visit Alphard
	visit Zosma
	visit Gomeisa
	visit Epsilon Leonis

And upon splitting that even further, into three more chunks, everything suddenly started working again, except that none of the systems marked for visiting got visited, and the player didn't launch at the end of the mission conversation as they were supposed to.

I'm guessing from this that the bug might be something about how the "visits" are handled in the code.

**Comment by quyykk** [comment]
>     visit Epsilon Leonis

You need to put the system name in quotes. Although, the error message can certainly be improved.

**Comment by mOctave** [comment]
Thanks for catching that. Sure enough, that was all that was causing the problem.

Looking through everything again, I found the following error message:
```Warning: system "Epsilon" is referred to, but not fully defined.```
I do hope that the error message does get improved (possibly describing why the event is invalid, instead of just saying that the event itself is invalid).
