### ISSUE TITLE
Game hangs on start if you click "Enter Ship" before the loading throbber is complete

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#709]
0.8.10, Windows 7, launching via Steam. Reproduced multiple times.

Task Manager shows zero CPU for the process, game doesn't respond to any input, doesn't even paint if you alt-tab away and then come back.

Doesn't seem to cause any problems for subsequent, more patient starts.

**Comment by mrec** [comment]
Probably related to #705, but definitely a hang rather than a crash, and *does* happen when launching via Steam.

**Comment by endless-sky** [comment]
I still haven't figured out #705, but this one is probably the bug that was fixed in commit 005041e.

**Comment by mrec** [comment]
Yup, unable to reproduce in 0.8.11; closing.
