### ISSUE TITLE
"Reason with the Syndicate" breaks if you already have a jump drive

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#711]
Starting this mission triggers the event `"fw syndicate welcoming"` with a delay of 11. Presumably the idea is to keep the tension high by continuing to show the Syndicate as hostile as the player takes the assumed roundabout Northern route via Moktar, but not actually kill them once they arrive, since reaching the nearest red system (Mirfak) takes 11 days.

However, if the player **already** has a jump drive, the default plotted route to Achernar via Fomalhaut puts them in a red system in only 4 days, and sure enough the Syndicate hits them like a ton of bricks. If they bull through anyway and land on Foundry as instructed (thanks to `clearance`) they get a nice apologetic speech and a request for help and the "Install a Jump Drive" mission, but as soon as they take off it's ton-of-bricks time again, everything's still red and Hephaestus won't let them land to complete that mission. At this point I assumed either the game was broken or my save file was corrupted.

If you want to keep tension for the normal case, is it possible to add a second (invisible) mission to insta-trigger `"fw syndicate welcoming"` when the player arrives in a system near (within 3 steps) of Achernar?

Workaround: edit savefile, set event trigger date to tomorrow so that it fires as soon as you take off.

**Comment by endless-sky** [comment]
Fixed in commit 0c7c8cc.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
