### ISSUE TITLE
Missed Category in "Creating Ships" Wiki Page

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The wiki page for creating ships says the following:
```"category": the type of ship: "Transport", "Light Freighter", "Heavy Freighter", "Interceptor", "Light Warship", "Heavy Warship", "Fighter", or "Drone".```
This misses Medium Warships entirely.

### Steps to Reproduce

1. Go to the Creating Ships wiki page.
2. Go to the "category" attribute.

### Expected Behavior

I would expect the line to read:

```"category": the type of ship: "Transport", "Light Freighter", "Heavy Freighter", "Interceptor", "Light Warship", "Medium Warship", "Heavy Warship", "Fighter", or "Drone".```

### Operating System

macOS Monterey (12.5)

### Game Source

GitHub Releases

### Game Version

N/A

**Comment by warp-core** [comment]
It would actually need to contain `Space Liner` and `Utility` for 0.9.15 as well.

**Comment by quyykk** [comment]
Done!
