### ISSUE TITLE
Allow "cargo," "commodities," and "outfitters" to be a child of npc

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#7112]
### Problem Description

It is currently possible to specify the commodity and outfit cargo that fleets carry. `fleet`s can be defined as a child of `npc`, meaning that mission npcs can be given commodities and outfits. But `npc` can also have children which are `ship`s with exact names given to them instead of names randomly given to them by a `fleet`. In this case, these ships can't be given cargo since they aren't a child of `fleet`.

### Related Issue Links

Resolving #3503 without ruining the naming of the ships in those missions would require this.

### Desired Solution

Allow `cargo`, `commodities`, and `outfitters` to be a child of `npc` as they are a child of `fleet`. These lines would apply to all `fleet`s and `ship`s in the npc block, just as is the case with `personality` being both an `npc` child and `fleet` child.

### Alternative Approaches

N/A

### Additional Context

N/A

**Comment by warp-core** [comment]
Should the 'cargo' properties of the NPC totally override whatever cargo a child fleet has (most relevant in the case of a named fleet), even if the NPC was not given any cargo (requiring `cargo 0` to ensure that any named child fleets  that may have cargo on their own won't have any when spawned by this NPC)?
