### ISSUE TITLE
Ember Waste Tour assigns unrevealed systems

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#7118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Ember Waste Tour missions can select systems from the Ssil Vida systems before they have been revealed on the map.
![Image 12-08-2022 at 20 22](https://user-images.githubusercontent.com/70952724/184436725-78d143d9-a3e0-4444-ba7e-ee83fbf6a24b.jpg)
You can see the indicated system at the top. It is currently inaccessible to this pilot.

### Steps to Reproduce

The systems are selected at runtime, so it's not predictable. 

### Expected Behavior

Missions should only cover accessible systems. Ssil Vida and Patir should not be in scope until the events have revealed them.

There is a separate possible issue in that the missions will select systems that the user hasn't visited, (e.g. in the Graveyard). However, this is consistent with missions in human space that show up on the map without a route and encourage exploration. 

### Operating System

Mac OSX current

### Game Source

ESLauncher2

### Game Version

Continuous within the last week

**Comment by Zitchas** [comment]
Are you running any plug-ins? Because I have no memory of this mission; and searching reveals no instances of "tour the Ember Waste" anywhere in the data files.

**Comment by williaji** [comment]
My mistake. I'm playing through the Midnight plugins just now and forgot to account for that. Sorry for the confusion.
