### ISSUE TITLE
Navcomp shouldn't plan jumps when escorting non-jump-capable ships

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#713]
Jump Drive jumps, not normal hyperdrive jumps.

This was particularly annoying during the FW storyline, since you seem to spend the majority of your time forced to escort something or other, and if you accept the navcomp's suggested routes you'll keep leaving them behind. Sometimes a long, long way behind.

I wouldn't want to disable jump drives altogether; if you're getting pummeled you might **want** to abandon your convoy and take the shortest route to safety. Maybe when there are non-jumpers in your fleet the navcomp should only plot jumps when holding down Shift (waypoint), which already sort of means "override your default behaviour". I don't know how discoverable this would be, though. Neither the Preferences screen nor the wiki mention the Shift-for-waypoint affordance as it is; I think I only discovered it by accident.

**Comment by endless-sky** [comment]
In general I try to avoid adding "special rules" to the game's behavior - it's better for the same action to always produce the same result, than for it to sometimes produce different results for reasons that are not clear to the player.

So, I think making a change like this would just be a recipe for confusion. Would it always trigger when you have friendly NPC escorts, or only when you must accompany those escorts to the mission destination? What if the player has purchased escorts with no jump drives? What about when an NPC is secretly following the player and is non-hostile? If there are suddenly a bunch of situations where, from the player's perspective, the jump controls stop "working" the way they normally do, and the rules for when that happens are complicated, that will just frustrate people.

**Comment by mrec** [comment]
That's a good rule of thumb, and makes sense.

I suppose you could add an explicit "no jumps" mode to the navcomp, e.g. Alt-click (which is currently unbound as far as I know), but since nobody would ever discover it it's hard to get too excited about.
