### ISSUE TITLE
Endless Sky will not install or run on Ubuntu 22.04.1 (Jammy)

### ISSUE THREAD

**Issue by jonathancutting** [endless-sky/endless-sky#7136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

_Endless Sky_ v0.9.12 will not install on Ubuntu 22.04.1 (Jammy) from the PPA, because the package depends on _libglew2.1_, and this library is not supported on Jammy. Additionally, the PPA directory for Focal needs to be used, because the directory for Jammy produces an error when polled by _apt_.

The _Endless Sky_ v0.9.12 AppImage will not run on Jammy, because it requires _FUSE_, and this is no longer supported on Jammy, which now uses _FUSE3_.

### Steps to Reproduce

1. Add repository _ppa:mzahniser/endless-sky_ to Jammy installation.
2. Open _Software & Updates_, and change the PPA distribution to _focal_.
3. In a terminal window, run **sudo apt update | sudo apt install endless-sky**.
4. See error... "The following packages have unmet dependencies: endless-sky : Depends: libglew2.1 (>= 1.12.0) but it is not installable."

### Expected Behavior

For the PPA install, the expectation is that _apt_ will automatically install all dependencies from the Ubuntu repositories.

For the AppImage, the expectation is that _FUSE3_ will be used, instead of _FUSE_.

### Operating System

Ubuntu 22.04.1 (Jammy Jellyfish)

### Game Source

Other (please describe)

### Game Version

Linux PPA from Launchpad

**Comment by quyykk** [comment]
I'm not sure what the current state of the PPA is, but it's probably not being maintained anymore.

Every AppImage is currently broken on Jammy. We have to wait for upstream to fix this.

**Comment by roadrunner56** [comment]
I'm on Kubuntu 22.04.1, and I'm able to run the game (continuous) through ESLauncher2 (https://github.com/EndlessSkyCommunity/ESLauncher2/releases). I'm no expert on ESLauncher2, but I believe it also uses appimages. You could perhaps use that as a workaround, although I'm not sure what the technical differences are.

**Comment by Pointedstick** [comment]
> because the package depends on libglew2.1, and this library is not supported on Jammy

This is an Ubuntu issue; please report there.

> The Endless Sky v0.9.12 AppImage will not run on Jammy, because it requires FUSE, and this is no longer supported on Jammy, which now uses FUSE3.

This is an AppImage issue; for cultural reasons, the AppImage people prefer to only support the oldest possible version of things, which often conflicts with distros, apps, and users who want to use newer versions.

I would recommend that you use the Flathub package, which should work fine.

**Comment by quyykk** [comment]
AppImages built starting from now can be run on Jammy without having to install anything.
