### ISSUE TITLE
Surveillance Pod sold with cargo Sell All, even though quest item

### ISSUE THREAD

**Issue by stonetoad** [endless-sky/endless-sky#714]
If you collect a Surveillance Pod for the drone hunting mission (FW Katya 3) and do "Sell All" at any planet before you land on Rand you will sell off the pod with no message or warning.

The fact that  cargoed outfits don't show up in the trade window makes this worse, since normally quest items arn't sellable.

**Comment by stonetoad** [comment]
Solving Issue #712 might also solve this issue sufficiently.

**Comment by mrec** [comment]
#712 is about selling specific things deliberately, this one is about *not* selling specific things accidentally. As you say, mission cargo isn't normally sellable, so this feels like a bug.

**Comment by endless-sky** [comment]
The thing is, there's actually nothing to mark that surveillance pod as a "quest item." You can pull it out of any surveillance drone, and can go and grab another if you sell the first one. And, it's easy to imagine situations where a player *would* want to sell them - e.g. they disable a drone, discover it's a cheap way of making money without making permanent enemies, and start collecting large numbers of drone outfits and selling them.

**Comment by stonetoad** [comment]
@mrec I was thinking of your saying 'I'm trying to sell "everything except X"' in that issue.  Which is basically what this issue boils down to aside from the quest item question.

I see your point about not making *every* surveillance pod a "quest item".  And from a quick glance at the source, it looks like it would be a huge job to make it able to flag the first one you get as a quest item (or rather, convert it to mission cargo).  So I think that's not a viable solution.

I'd be happy with just some kind of of warning or heads up, so you don't sell it accidentally and only realize after flying back to Rand and wondering why the quest isn't updating.

If the selling of cargo-ed outfits via the trading window was less opaque, I think this would clear up nicely.  Since you'd see the surveillance pod there in the list to be sold (and ideally would be able to buy it back if you noticed it having gotten sold by accident, like you can in the outfitting screen).  But that is probably a separate issue....

**Comment by jafdy** [comment]
Could you use a hidden mission so that as soon as you land on a planet after getting your first surveillance pod that turns it into mission cargo? 
Maybe something like:
"Now I have the surveillance pod I will need to take it back to Rand.
For the time being I will have to leave it in the cargo hold."

**Comment by Wrzlprnft** [comment]
or a event(which removes the first surveillance drone of your cargo) stating you have a surveillance drone instead of it checking the cargo hold?

**Comment by masterpierround** [comment]
I like the idea of turning it into mission cargo. Actually, now I'm curious. What happens if you equip the surveillance pod to your ship before returning to Rand?

**Comment by natangold** [comment]
You can use it as a cargo/outfit scanner, and it gets unequipped when you land on Rand; it only counts, though, if you install it on your flagship.

**Comment by ph2000bis** [comment]
Maybe you can only sell plundered outfits at an outfitter ?
Maybe then make all planets have outfitters (that can sell nothing) ?
