### ISSUE TITLE
bug: README file contains invalid links

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#7152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the [integration test README file](https://github.com/endless-sky/endless-sky/blob/master/tests/integration/README.md) there are two links to directories, and neither of them actually exist. This may be due to the refactoring of tests performed in #7017 and similar PRS.

### Steps to Reproduce

Go to https://github.com/endless-sky/endless-sky/blob/master/tests/integration/README.md and click on the links

### Expected Behavior

The links should point to the proper test directories. That would probably be https://github.com/endless-sky/endless-sky/tree/master/tests/integration/config/plugins/integration-tests/data/tests in both cases and the file should be reworded, but I'm not entirely sure.

### Operating System

Not relevant

### Game Source

GitHub Releases

### Game Version

commit SHA 4f4eac9

**Comment by thvk-net** [comment]
I can confirm this
