### ISSUE TITLE
Fix typo - Ivan/Wormhole Questline

### ISSUE THREAD

**Issue by grumpymunky101** [endless-sky/endless-sky#7158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Text says: "The team of scientists is already waiting in the spaceport when you arrive. They remove the equipment from your ship and immediately **being** analyzing the results after returning to the lab"

### Steps to Reproduce

Happens during the questline where Ivan has you navigate wormholes in the Ember Wastes

### Expected Behavior

"being" should be replaced with "begin"

### Screenshots

![typoReport](https://user-images.githubusercontent.com/111706621/185808660-3dc64ed2-57c9-4a12-9076-6f0a7bd6ef3d.PNG)

### Operating System

Win 10 Home

### Game Source

Steam

### Game Version

v0.9.14

**Comment by Zitchas** [comment]
I can't find this in continuous, but I know this section was subject to a fair bit of changes for 0.9.15, so this *may* already be solved.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/blob/c27eb67b20dc4a450b2e8aa0241b1c9204af5527/data/human/deep%20missions.txt#L1623
It does indeed appear to already be fixed.

**Comment by grumpymunky101** [comment]
Thanks for confirmation - keep on being awesome and thanks for coding/contributing to such a fantastic game!
