### ISSUE TITLE
Enable and Disable plugins from in-game settings menu

### ISSUE THREAD

**Issue by samrocketman** [endless-sky/endless-sky#7171]
### Problem Description

Enabling and disabling plugins is inconvenient.  You must either remove or move plugins out of the plugin folder.

### Related Issue Links

None I could find.

### Desired Solution

Have an in-game plugin menu for enabling and disabling installed plugins.  This would require a `~/.local/share/endless-sky/plugins.txt` file which contains what plugins are enabled or disabled.  An example of this is the following:

```
AES-Omnis 1
ES-news-portraits 0
ESLampyridStart 0
Lost-in-Midnight 1
Mega-Freight 1
Midnight-Scrapyard 1
all-content-plugin 1
endless-sky-high-dpi 1
```

The contents of `plugins.txt` should match what is in `~/.local/share/endless-sky/plugins/` folder because it will help the game determine if loading should be skipped or not.  The following is an in-game UI mock which matches the above `plugins.txt`.

![es-plugins-with-checkboxes](https://user-images.githubusercontent.com/875669/186804355-31bbb469-3c24-4a8a-8428-034b42c2128b.png)

A warning dialog should appear once every launch when a user changes plugin settings.  The purpose of the dialog is to remind the user that they must restart the game before changes take effect.  The following is a mock warning when a user checks or unchecks a plugin.

![es-plugins-with-checkboxes-warning](https://user-images.githubusercontent.com/875669/186804540-840cf3bd-3a53-4e97-85ec-a337afdf5059.png)

Here's the dialog txt.

```
help "plugin warning"
	`Enabling or disabling plugins requires you to restart the game.  Quit and restart for plugin changes to take effect.`
	``
	`Warning: If you're disabling a plugin that provides content for your current save game then the content will not be available unless you re-enable the plugin.`
```

### Alternative Approaches

N/A

**Comment by AvianGeneticist** [comment]
This would be **unimaginably** helpful for testing stuff. Big want

**Comment by MasterOfGrey** [comment]
I cannot express how much I need this.

**Comment by Hurleveur** [comment]
Until now I used two folders and moved the plugins around when needed.
It would be nice to eventually be able to link some plugins to a savefile, or automatically detect and activate plugins from a savefile(they're now written in it, I believe)

**Comment by samrocketman** [comment]
https://github.com/endless-sky/endless-sky/pull/7192 implements this feature.

> It would be nice to eventually be able to link some plugins to a savefile, or automatically detect and activate plugins in a savefile > (they're now written in it, I believe)

This would likely require a deeper refactor in how endless sky handles game data in general (not just plugin data).  For now, this feature merely skips loading the plugin into the general game data if it is disabled by user preference.

**Comment by Hurleveur** [comment]
Yes it's definitely a step in the right direction, I'm just saying what I'd like the end feature to look like.

**Comment by samrocketman** [comment]
@Hurleveur regarding save games I think we can approach this two ways:

* If plugins have changed prevent save game from loading until game has restarted.
* When loading a dialog prompting the player two options:
  1. Continue and overwrite plugin set for the save file.
  2. Update plugin selection to match the save game.  This would then require a restart and block loading save games until restart occurs.

@kestrel1110 these are some thoughts around your question in my PR as well.

**Comment by warp-core** [comment]
> @Hurleveur regarding save games I think we can approach this two ways:
> 
> * If plugins have changed prevent save game from loading until game has restarted.
> * When loading a dialog prompting the player two options:
>   
>   1. Continue and overwrite plugin set for the save file.
>   2. Update plugin selection to match the save game.  This would then require a restart and block loading save games until restart occurs.
> 
> @kestrel1110 these are some thoughts around your question in my PR as well.

Blocking loading seems pretty unacceptable.
Presenting a dialog warning that plugins have changed and giving the option to continue anyway or restart with the appropriate set of plugins enabled sounds good.

This would perhaps need to handle if a plugin is no longer present (as in, cannot be enabled because it's not there) differently; restarting isn't going to help.

**Comment by samrocketman** [comment]
> Blocking loading seems pretty unacceptable.

This is if there's changes in the plugin UI.  In this case only plugins installed and those which the user has changed would block.  Undoing plugin state changes would unblock.

With regard to plugins not being available that would still be the same warning to continue and overwrite the known plugins in the save file.

**Comment by Hurleveur** [comment]
I think it shouldnt really ever prevent loading, just have a warning dialog like "the following plugins are missing, do you want to load still" and if you say no it'll query again when you try to load another time. If you say yes it overwrites the plugins in the savefile. If you say activate plugins (and restart?) it'll do that.

**Comment by trentbuck** [comment]
Hi, I ship Endless Sky to detainees in Australian prisons.
This comment is just a bit of "user story" feedback about how I'd use this feature.
I would probably give detainees ALL existing plugins if

- plugins could live in `/usr` (and `~/.local/share/endless-sky/plugins/` just has a symlink)
- plugins are off-by-default, so they don't wreck the vanilla experience for new users
- users can toggle plugins via the GUI.

I can fudge the first two with scripts, but the last one (i.e. this ticket) is beyond my time budget.
So currently, they just don't get any plugins. :-)

In one prison, in the last year, detainees have collectively played Endless Sky for 8 months 9 days 8 hours 33 minutes.
It is the second most popular game on site (after Solitaire, but before Wesnoth, OpenTTD, SuperTuxKart, &c)

**Comment by samrocketman** [comment]
@trentbuck would it be easier for you if I added a preference to set the default?  You could then toggle that preference and the default will apply to all plugins.

Generally, I try to match vanilla behavior but I am open to changing the default as well.  This seems like it would be a useful preference to have (auto-load new plugins on first launch)

**Comment by samrocketman** [comment]
@trentbuck another caveat is the plugin UI does not scroll. So if you add so many plugins that it scrolls off screen then it will only be possible to enable some plugins by editing `~/.local/share/endless-sky/plugins.txt`

There is also a global `plugins.txt`

When the PR is merged I would like to add scrolling to the plugin UI.

**Comment by samrocketman** [comment]
@trentbuck here is an example of the feature as it exists now.  The global `plugins.txt` disables plugins on first launch but the user can later enable them.  This shouldn't require any scripting on your end once the feature is merged.

https://github.com/samrocketman/endless-sky/blob/mining-complete-plugins/plugins.txt

**Comment by trentbuck** [comment]
On Thu 27 Oct 2022 13:29:08 +0000, Sam Gleske wrote:
> @trentbuck would it be easier for you if I added a preference to set the default?  You could then toggle that preference and the default will apply to all plugins.
> 
> Generally, I try to match vanilla behavior but I am open to changing the default as well.  This seems like it would be a useful preference to have (auto-load new plugins on first launch)

The experience I particularly want to avoid is this:

  1. user alice says "can you provide <cheat plugin X>?"
  2. I drop it into /usr
  3. user bob has cheats enabled, without ever asking for cheats, or even knowing about them.

If bob opened Endless Sky and a popup said "hey, a new plugin was found called Cheat Plugin X, enable it? [Y/n]",
I guess that would be OK.
I was imagining more like they just start playing ES with no knowledge of plugins at all, and
eventually they notice the plugins panel in Preferences and start playing around.
