### ISSUE TITLE
[Request] Capability for adding to credits in plugins

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7173]
### Problem Description

The data to display in the credits is stored in the "credits.txt" file as plain text, which gets added to the game menu in the MenuPanel.cpp file. It would be nice if plugin authors could add to the credits so as to credit contributors to plugins used in the game.

This is definitely a minor issue, but it _would_ be nice to have.

### Related Issue Links

None found.

### Desired Solution

Allow any added credits.txt file in a plugin to be appended to the end of the main one, with the same formatting rules. This would require the code to search through the plugins folder for any file titled "credits.txt" in each plugin folder, then add its content to an array of items that all get added, then add them.

### Alternative Approaches

Write the credits up as a datafile, that can then be modified with another credits listing. Example:
```
credits
	Welcome to Endless Sky!
	version 0.9.14

	This game is open source.
	To report bugs, give feedback,
	or contribute to story writing,
	artwork, or programming, visit:
	- https://endless-sky.github.io
	- The game's Steam forums
	- Discord (invite: ZeuASSx)

	Creator and Lead Programmer
		Michael Zahniser

	Developers
		Amazinite
		Benjamin Hauch
		Pointedstick
	...
```

This solution would probably be much harder to implement.

**Comment by thvk-net** [comment]
I like the alternative approach because it fits more into the endless sky stricture

**Comment by quyykk** [comment]
Plugins have the about text that can be used to credit plugin authors, so I'm not too sure this feature is needed.

**Comment by Zitchas** [comment]
As quyykk said, plug-ins have their "about the plug-in" thing that can be used to give credit.

That being said, and especially for big plug-ins with lots of contributors (here's hoping that, someday, we get really big TC plug-ins like EV/O/N eventually did), having some way to tack that on to the regular game credits would be good.

My caveats would be to make a clear line between the game credits and the plugin credits. 

For example, once it has scrolled through the regular game credits, have a solid bar across the credits pane, then it states "Credits from X plug-in:" and displays that plug-in's credit file. Then repeat that for every plug-in.

That would make it clear where the credits are coming from and what they apply to; not to mention also serving as a reminder of what plug-ins are active.

**Comment by thvk-net** [comment]
On what base is credits.txt created?
