### ISSUE TITLE
[Request] Change Unfettered Hai Colour

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7186]
### Problem Description

The colours for Unfettered Hai and normal Hai are very similar. It is possible to tell them apart, but only with some difficulty, especially when the map is zoomed out.

<img width="263" alt="Hai-Unfettered Comparison" src="https://user-images.githubusercontent.com/73318970/187584284-daf693c2-072f-442c-9db5-82a58cb77783.png">

### Related Issue Links

@Zireael07 suggested that I raise this as an issue here: https://github.com/endless-sky/endless-sky/discussions/7170

### Desired Solution

I would like the Unfettered Hai's colour to be changed to contain more blue and less red.

### Alternative Approaches

Alternatively, the colour of the Hai could be changed to be more red.

### Additional Context

I can fork ES and open a pull request to change this myself, but there should probably be some discussion first.

**Comment by Zitchas** [comment]
That could be a good thing to do. Could be good for improving accessibility by those with problems with similar colors, too.

**Comment by AvianGeneticist** [comment]
In my experience, changing value (lightness) is a better way of making things distinct for accessibility. Though it wouldn't work in system (planet labels seemed to be fixed above a certain lightness value for some reason), making the Uhai a darker purple would likely be the better move as far as making it as obvious as possible which is which.
