### ISSUE TITLE
Jumping always favors hyperdrives, even if they require more fuel than jump drives

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#7189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When both a hyperdrive and a jump drive are equipped, ships will always favor using the hyperdrive when jumping between two linked systems, even if the jump drive would be cheaper.

### Steps to Reproduce

1. Equip a hyperdrive and a jump drive, with the hyperdrive's jump fuel being greater than the jump drive's.
2. Travel between systems and observe how the hyperdrive is used when jumping between linked systems, even though using the jump drive would be cheaper.

### Expected Behavior

The cheapest jump method should always be used. The game should not assume that a hyperdrive will always cost less than a jump drive.

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

https://github.com/endless-sky/endless-sky/commit/931bd903b1d2cfa501fb7972021cdebfcef82ab4

### Additional Information

The relevant code is here:

https://github.com/endless-sky/endless-sky/blob/931bd903b1d2cfa501fb7972021cdebfcef82ab4/source/Ship.cpp#L3148-L3168

Particularly on line 3160, you can see that if the systems are linked, the hyperdrive is always used if available.

Anyone want to refactor Ship to move all the methods that worry about finding the best jump method to a new class? `Navigation`?

**Comment by thvk-net** [comment]
I would like to do this

**Comment by thvk-net** [comment]
I think i will have a pr finished today

**Comment by thvk-net** [comment]
But why a new class?
I think some smaller changes should be enough.
And if a new class what name should it have?

**Comment by Amazinite** [comment]
Go ahead and just fix this bug if you're looking to address this issue. The mention of a new class is because Ship has way too many responsibilities, and we've been seeking to reduce those by refactoring certain bits out into different classes. See https://github.com/endless-sky/endless-sky/pull/6557 as an example. Any such refactoring can be done after this bug is fixed, though.

**Comment by thvk-net** [comment]
I have no problem with creating a new class but I need some infos before doing it.
First: class name?
Second: What functions should be exported into it?
I think it will be this block of functions:
        ```
int JumpsRemaining(bool followParent = true) const;
	// Get the amount of fuel expended per jump.
	double JumpFuel(const System *destination = nullptr) const;
	// Get the distance that this ship can jump.
	double JumpRange(bool getCached = true) const;
	// Get the cost of making a jump of the given type (if possible).
	double HyperdriveFuel() const;
	double JumpDriveFuel(double jumpDistance = 0.) const;
	// Get the amount of fuel missing for the next jump (smart refuelling)
	double JumpFuelMissing() const;
```
