### ISSUE TITLE
Not seeing any more new jobs on the board

### ISSUE THREAD

**Issue by funkybob** [endless-sky/endless-sky#719]
I thought it was something to do with how far down the storyline I'd got, so I started all over again.

But now, after I've purged the save directory, started a new game... nothing.

No new missions, not even the overly jolly introductory captain to show me about...

This changed some time in the last 2 or 3 days.

**Comment by endless-sky** [comment]
See if 9db961d fixes this for you.

**Comment by alley-oop** [comment]
I can confirm that your hint help me.
With this small change I can see the initial story again too.

Thank you for your help.

**Comment by funkybob** [comment]
Seems to be working again. Thanks.
