### ISSUE TITLE
Too hard to track what is going on when several missions are active

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#72]
I started to be handed the pirate hunt missions...

I accepted several of them, but there is no clear indication of what ones I already killed the pirate so I can return to the planet that ordered the mission.

This is not an issue only with this though, the Free Planets mission to scan all ships in another system I had the same problem, I went there, and scanned all ships I could find, the red marker disappeared, then I flew back, and nothing happened, then I flew AGAIN to the place where I was supposed to go, and scanned much, much more ships, and eventually got a message saying I could go back.

I think the markers should change (specially because the red markers are also confusing).

Current system:

Green: accepted mission
Yellow: Mission you can do
Orange: Mission you cannot do
Red: Waypoint

Problems with it:

green marker in many instances is useless, it only end showing the origin point of the mission
the yellow marker is mission you can do, orange you can't, and red looks like it would proceed from orange (thus something that maybe you should not do at all).

My suggestion:

blue: accepted
yellow: can do
red: can't do
green: "Go there", this is where to go next, always, for pirate hunting missions this mean the marker stay blue, until you kill the pirate, then it becomes green, for the scouting missions, the origin marker is blue, and green markers spawn showing where you should go, when it is time to return to the planet, it turns from blue to green.

Also I suggested dropping orange for two reasons: one, many people have vision problems and can't see the different between the orange and yellow marker. Second, on some monitors (like my monitor) that are "budget", the contrast is low, and the orange and yellow marker look too similar to each other.

A second suggestion is maybe change the mission text as needed (ie: before killing a pirate it says the current text, after killing the pirate it says you  can go back, also applies to any "fetch" mission, like the one to steal a drone scanner).

**Comment by johndh** [comment]
With the repetition of ship names and the abundance of this kind of mission (I've got dozens of them at any given time), a notification would be very helpful when destroying a mission target.  "Bloodwrought destroyed, return to Mars in the Sol system to collect your reward", accompanied by a change in the marker on the galaxy map.  Alternatively, since the bank seems to operate across systems with no problem, you could just automatically receive the reward next time you land anywhere with a bank?

**Comment by endless-sky** [comment]
There ought to be a message shown when a target of a bounty hunting mission is destroyed (6d88f47). I'll work on also changing the color of the mission marker to indicate whether it is possible to complete yet or not, but that could get rather complicated in some cases.

**Comment by speeder** [comment]
There IS a message already, the message just don't help much, specially if you kill several pirates in a row in a trip, since there is no message log that you can use.

Thus why I suggested the marker colours, and also they would be useful in other contexts than the pirate missions.

**Comment by endless-sky** [comment]
Here's a partial solution: 9b771ad. I'm trying to avoid having too many different pointer colors, so right now the colors are:

* bright gold: job that is available, and you can accept it
* dim gold: job that is available, but you cannot accept it
* bright green: job that you have accepted, and nothing is blocking it from being completed
* dim green: job that you have accepted, but an NPC condition or waypoint is not satisfied yet
* red: waypoints

That is, all I did was to add the "dim green" option. I'm figuring that dim vs. bright for inactive vs. active is a design language I use elsewhere and that should be relatively intuitive, whereas for a new player figuring out what green vs. blue or red vs. yellow means would be more difficult. (But, it sounds like on your monitor at least, maybe I'd need to use a different "dim gold" color to make it clearer that it's meant to be a dimmed-out version of the gold pointers.)

**Comment by speeder** [comment]
I personally hated your colour choices.
Yes, there is the problem on my monitor that there is no difference between dim and bright version of gold, and now green.

But you also forgot a serious problem: about 5% of the humans see red, green and "gold" (the tone you used) as the exact same colour.

I personally don't have this problem, but I know some hardcore games that do, and they get very pissed off at it, it is just outright bad PR (Bioshock got some flak on the news because of this, they had a puzzle where it was critical to see the difference between a yellow, green and red spot on the screen)

And red for waypoints, for someone that CAN see red, is a strange choice (red usually means danger, or "don't go there", a waypoint that is red makes no sense).

And sorry if I sound like some nagging asshole, it is that I have a degree in that stuff, and it saddens me to see something that could be done right, being done wrong.

![Colourblind](http://i.kinja-img.com/gawker-media/image/upload/s--SPErGdwu--/c_fit,fl_progressive,q_80,w_636/quaistgh0cj4hw88qono.gif)

**Comment by endless-sky** [comment]
I suppose the simplest solution would be to switch the "active mission" pointers to dim and bright blue, and the "waypoints" to white, and keep the "available job" pointers yellow. Then everything would be at a different place on the blue-yellow spectrum. What would you think of that?

**Comment by speeder** [comment]
Better :)

Still, I don't think you need a different colour for waypolnt and and non-blocked accepted job, the meaning to the player is the same: "Go there"


Suggestion then using the grayscale + yellow + blue

Job available: bright yellow
job available but not acceptable: less-bright red (colour blind people would see this as dark-yellow)
job you can deliver + waypoints = light blue (to contrast with the background that is dark blue or black)
job that is accepted, but you can't deliver = grey

**Comment by endless-sky** [comment]
Here's an example showing what blue and grey pointers would look like. The grey pointers are very hard to distinguish from the map background, and at least on my monitor, the dark blue pointer is almost impossible to see. To make the blues more visible I need to mix in more green (shifting them towards cyan, which would presumably be indistinguishable from grey for a color-blind person).

![map](https://cloud.githubusercontent.com/assets/11450262/9028379/ba5c6d12-3944-11e5-92f0-38b388d34adb.jpg)

For comparison, here's the map using the current color scheme:

![original](https://cloud.githubusercontent.com/assets/11450262/9028380/c5d5710c-3944-11e5-8b06-711ace828e3f.jpg)

I think the only way for the blue-yellow-grey pointers to stand out enough would be if I took out the background galaxy image and just drew everything on a black background, instead.

**Comment by endless-sky** [comment]
I've committed a chance (843ede5) that allows you to modify the pointer colors by changing the data files, instead of needing to modify the source code. That means, for example, that a plugin containing this text...

```
galaxy "Milky Way"
	sprite none

galaxy "label south"
	sprite none

galaxy "label rim"
	sprite none

galaxy "label dirt belt"
	sprite none

galaxy "label earth"
	sprite none

galaxy "label core"
	sprite none

galaxy "label deep"
	sprite none

galaxy "label paradise"
	sprite none

galaxy "label north"
	sprite none

color "available job" 1. 1. 0. 1.
color "available back" .5 .5 0. .5
color "unavailable job" .6 .6 0. 1.
color "unavailable back" .3 .3 0. .5
color "active mission" 0. .4 1. 1.
color "active back" 0. .2 .5 .5
color "blocked mission" .6 .6 .6 1.
color "blocked back" .3 .3 .3 .5
color "waypoint" 0. .4 1. 1.
```

...will modify the map to look like this, which should be easier for color-blind people:

![colorblind](https://cloud.githubusercontent.com/assets/11450262/9028477/3fce3d6a-3948-11e5-83e7-436baededb91.jpg)

Actually, that kind of makes me think that I should consider eliminating or de-emphasizing the background image anyways, since without it the map is much easier to read.

**Comment by speeder** [comment]
I will experiment here.

Also... yes, the map is much easier to see now, on my monitor the grey text and lines on the grey background is particularly bad, maybe instead of removing the bg make it very dim? Or use something else...

Or leave without bg anyway, function must win against form, when there is doubt.

**Comment by endless-sky** [comment]
Here's how it looks if I tone down the brightness of the galaxy image considerably:

![reduced](https://cloud.githubusercontent.com/assets/11450262/9028862/bf5e791c-3954-11e5-9001-0a27725c0b4f.jpg)

I think I actually like that better than the original:

![original](https://cloud.githubusercontent.com/assets/11450262/9028380/c5d5710c-3944-11e5-8b06-711ace828e3f.jpg)

And, there's still enough detail that the broad shape of the galaxy is visible, just not so much the individual stars.

**Comment by speeder** [comment]
Yep, it is as I tought, looks much better.

**Comment by speeder** [comment]
Made some colour fiddling here... found our your renderer darken some colours too much.

I went and ahead and request a blue colour beyond 1.0 ( 0.1 0.4 1.6 1.0 to be exact) and now it is actually visible :) Also happy to know I don't broke your code.

**Comment by endless-sky** [comment]
The pointers are gradient-filled, with the specified color at the "point" and fully transparent at the base of the triangle. So, by specifying a color greater than 1, basically that means the gradient is "above" 100% blue for part of the distance.

**Comment by endless-sky** [comment]
![teardrop](https://cloud.githubusercontent.com/assets/11450262/9048878/87119fa6-3a0a-11e5-88de-0e09445ff24e.jpg)

What would you think of modifying the pointers to look like this? (A solid "teardrop" shape instead of a triangle that fades off on one end.) I'm thinking that brighter pointers with less fuzzy edges will be less prone to fading into the background.

**Comment by speeder** [comment]
For usability is better, much better, but I sort of disliked it.

Maybe you could adjust the triangle gradient instead (instead of fading to zero, fade to 50% or 30%)

**Comment by endless-sky** [comment]
Well, here's what I've switched it to for now:

![final](https://cloud.githubusercontent.com/assets/11450262/9050893/6d192e04-3a21-11e5-87a7-8a0a0d6c3e68.jpg)

According to an online [color blindness simulator](http://www.color-blindness.com/coblis-color-blindness-simulator/), that color scheme ought to allow both red-green and blue-yellow color blind people to distinguish between the three different hues. I also switched the pointers back to "fading out" at the far end, but still with the tapered effect because I think it looks more interesting than a plain triangle.

**Comment by speeder** [comment]
That looks interesting :)

**Comment by endless-sky** [comment]
I'm closing this for now. The new changes fix the color-blindness issue and make it clear which bounties you have successfully killed so you can collect the payment, and the darker backdrop makes the map easier to read.
