### ISSUE TITLE
Disabling should wipe all ship commands

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#720]
If you've commanded your ship to land, then get disabled, and then get repaired, your ship will continue with the landing command. 

The downside of this is if you get disabled by a pirate right over the planet you were trying to land on, then another ship disables the pirate, then you get repaired (and you obviously want to board that pirate instead of landing because you're still flying around in a Star Barge!), your ship will land before you have a chance to hit another key.

Disabling should wipe all commands.

**Comment by Gkramme** [comment]
But at the same time, that would confuse new players. I like the idea though!

**Comment by brendanjones** [comment]
I think it's more confusing that your ship suddenly does something that was commanded a couple of minutes ago! I mean, it surprised me, as an experienced player, that my ship suddenly got sucked down into the planet. I was very much looking forward to pillaging a Leviathan with my 1/2 hr old pilot :'(

I wonder -  if you hit other commands while you're disabled, would it overrule the landing command you gave before being disabled? It should...

**Comment by lehgogh** [comment]
@brendanjones: I can't test it right now, but if it remembers commands inserted before you get disabled, it should also remember commands given while you're disabled (including the command to board the targeted ship).

**Comment by endless-sky** [comment]
This should be fixed in 0.9.0.
