### ISSUE TITLE
Error in Republic Carrier description

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#721]
The text says "the Carrier is slightly less well shielded than the Republic Cruiser", but a Carrier actually has more shields than a Cruiser.

**Comment by Gkramme** [comment]
Already made. Fixed in update already.

**Comment by brendanjones** [comment]
Ah, my bad, didn't see that. Carry on, everyone.

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
