### ISSUE TITLE
Proposal for a species without hyperdrive

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#7211]
### Problem Description

Referring to this point of the Development Roadmap:
>  Universe:
> 
>     Fill the rest of the galaxy with various sized clusters of systems, with a jump drive needed to travel between them.
>     More alien species.
I want to propose an alien species without a hyperdrive. Furthermore it should be a species that come from a gas giant.
Until now this is only a very draft version of a plugin that barely adds the map changes and some little stuff, because I first want to know if there is a general interest for something like that or not before I put a lot of work into it.

### Desired Solution

For now I have called the species the Incipias, what is a little bit Latin and means the beginners/starters.

Anatomy:
The Incipias are the end of the evolution line of a species that is formed like hot air balloons. They are approximately half an meter in diameter(they are a round/eclyptic species), and have a lot of tentacle like smaller extremities. They are comparable to humans in intelligence. They can move freely in the clouds of their home world thanks to a swim bladder alike organell, that is filled with a very light gas. They communicate with light signal that they emit from their "skin" but in a wavelength that humans cant see.

Early history:
Their history began with them building their first homes. Until then  they were just moving around in the clouds of their home world. From that time on they were moving fast forward in science. But what also happened were a lot of wars about resources. Because  the only heavy metals on their planet came from meteorites. At some point all of the different factions decided that they could not afford to waste any further resources and made a peace agreement, that all conflict should be solved by a neutral board of persons that  were elected by the people. With the time passing this board gained more and more might and the factions were loosing importance. That is how the global government of the Incipias was founded.

Recent history:
The Incipias send their first object into space two hundred years ago. To that time all space traveling was under the restriction of the planetary wide government of the Incipias. But, as time was going on, another player showed up in space traveling scene, the Hicemus. They were an organization of people who wanted to go on faster than the
government, because the government was very careful and took it slow. As a great organization the Hicemus were able to obtain the right to do space travel. They were going faster, but also more reckless as the government and they did not care about any possible losses. It happened what had to happen, a great catastrophe where hundred of them died on a space ship. The government wanted to prohibit more events like this and they removed the right to space travel of the Hicemus. The Hicemus grew very angry about and declared their independence from the government. The government, who was not used to such things took to hard counter messures and a civil war began. The war was going on for ten years, until the Hicemus decided it for themself, because they were more technical advanced than the government. They claimed all rights for space travel for them selfs, but because they did not want more rumors they let the old government
exist, but only on their home world. Ten years after the war the Hicemus began building the first greater space station of the Incipias, the Pon'tes. When it was finished they made it their headquarters and a lot of their members leaved their
home world.

Content in game:
First of all the player will have to get some scientist to learn their language. But then the storyline will form around the Incipias searching for the hyperdrive but also about the conflict between the Hicemus and the old government.

Preciser _**(warning, if this ever gets in game this is a spoiler)**_ :
At first the player wont be able to land on either the station nor the gas giant(even with a remant gaslining) because they are restricted.And because the Incipias do not speak human language no contact will be available. 
And here comes something I have to decide: The first possibility would be to have a mission start as soon as the player enters the system that says: "Get yourself a language scientist to make contact." Or the other option is, that the player meets the Quarg and they provide the player with some communication device( I prefer the first ).
In any case after the player has talked to the Incipias, a Quarg ship will show up and forbid the player to sell them advanced technology.
But it is too late, the Incipias have already seen the Hyperdrive and got some rough idea how it works. The Hicemus will start too build test ships for that. 
--pause--
At some point when the player is landing on the space station a mysterious person will approach him, a member of the old government. They also heard about the Hyperdrive and now they are scared that the Hicemus will be as reckless as when they were discovering space travel. They ask the player to help them to build the Hyperdrive first in a more carefull way. At this point the player has to decide which faction of the Incipias he will support. His choice will have an impact on the power balance and on which faction will settle in other systems.

**Comment by thvk-net** [comment]
Oh, i forgot to link this: https://github.com/thvk-net/Incipias

**Comment by thvk-net** [comment]
Adding Azures Paraphrase here:

> I really like this idea, and a pre-hyperdrive civilization is something that I think would fit very well in the galaxy.
> 
> Paraphrasing our discussion from Discord:
> 
> You aren't going to be finding metals on a gas giant unless the Incipias can swim to the bottom of the metallic hydrogen ocean and mine the core somehow. Instead, what if they were experts at nonmetallic materials science, drawing elements from the gas giant's atmosphere like hydrocarbons and ammonia?
> 
> This could range from highly advanced plastics, composites, and other materials, to even using the extreme pressures of a gas giant's lower atmosphere to forge tools and components of out diamond. Or, the Incipias could have a biology allowing them to produce materials akin to spider silk, which could have been the key to starting their tool-using civilization.

**Comment by thvk-net** [comment]
Here you can checkout the first contact mission: https://github.com/thvk-net/endless-sky/tree/Incipias

**Comment by RisingLeaf** [comment]
Some first art:
![image](https://user-images.githubusercontent.com/85687254/189014622-3c02b359-1cbe-4266-b8bf-8b738d9a2c4d.png)

**Comment by RisingLeaf** [comment]
There is now a PR for this
