### ISSUE TITLE
Remnant Graveyard search and rescue mission can choose Patir before it is revealed

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#7227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Graveyard search and rescue mission can choose Patir as a destination before the Ssil Vida and Patir reveal. It is also problematic as it requires a jump drive which Remnant ships don't have by default. I've check the ship in my save and no jump drive is listed in the outfits. Oddly, neither is a hyperdrive.

### Steps to Reproduce

This is randomly assigned so cannot be directly duplicated. Save file is attached.

### Expected Behavior

Only the hyperdrive accessible systems in the Graveyard should be chosen for these missions.

### Screenshots

![Screenshot_20220908_224900](https://user-images.githubusercontent.com/70952724/189235056-7e73ad4d-12b8-4a2b-86fe-d6f84ffc8601.png)
![Screenshot_20220908_225301](https://user-images.githubusercontent.com/70952724/189235067-5e41b9f5-12af-4624-973a-75f5ff9962cf.png)

### Link to save file

[Zara Viscari.txt](https://github.com/endless-sky/endless-sky/files/9530936/Zara.Viscari.txt)

### Operating System

5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux

### Game Source

Built from source

### Game Version

Endless Sky ver. 0.9.15-alpha - compiled in my fork

**Comment by williaji** [comment]
I did confirm that Patir was not visible to the routing system from either Fereti or Ritilas, so the job cannot be completed in my current save.

**Comment by ChekPuk** [comment]
Hello there. I have finaly found Patir and have now TWO rescue missions there. But ships that needs to be rescued are without jump drives. Is it normal? There is empty station, I tried to bring spare Jump drives with me, but how to pass it to them? I think all my Remnant missions are stuck to this. (or this is a dead end?)

**Comment by warp-core** [comment]
> Hello there. I have finaly found Patir and have now TWO rescue missions there. But ships that needs to be rescued are without jump drives. Is it normal? There is empty station, I tried to bring spare Jump drives with me, but how to pass it to them? I think all my Remnant missions are stuck to this. (or this is a dead end?)

What version of the game are you on?

This should have been fixed by 8137bbd9120d3d9dd77b8ec8a0fcc9b9e176461c.

**Comment by williaji** [comment]
> Hello there. I have finaly found Patir and have now TWO rescue missions there. But ships that needs to be rescued are without jump drives. Is it normal? There is empty station, I tried to bring spare Jump drives with me, but how to pass it to them? I think all my Remnant missions are stuck to this. (or this is a dead end?)

You should abort these missions as you cannot complete them. These missions will not block your progress through the Remnant story line.

**Comment by ChekPuk** [comment]
Sorry for delay. Sloooow connection, pulled fresh git and recompiled.
> What version of the game are you on?
During compilation on Arch Linux it said "downgrading endless-sky-git (0.9.13.r1046.g1c2a44753-1 => 0.9.12.r767.g1af961037-1)" whatever this means :)
> This should have been fixed by [8137bbd](https://github.com/endless-sky/endless-sky/commit/8137bbd9120d3d9dd77b8ec8a0fcc9b9e176461c).
As I understand, this won't change anything if I already have this mission, right?
As @williaji suggested I just aborted mission. Wish all the best to abandoned mission ships crews :)
Thanks everyone.

**Comment by warp-core** [comment]
Closing this because I'm almost certain it is fixed. If anyone encounters it in a version after 8137bbd, please comment here.
