### ISSUE TITLE
Warehouse storage for outfits

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#724]
(I thought I'd seen someone mention that this request had come up before, but I can't find anything either by searching or in any of the open issues.)

A player may acquire outfits that aren't immediately usable or useful, but which they don't want to lose. This mostly applies to "special" outfits that aren't normally available, e.g. I have a couple of Ionic Afterburners captured during the storyline that aren't for sale anywhere; I don't have any particular need for them but am reluctant to sell them. Ditto with Pug gear (assuming you don't want to restart the war at Pug Iyik). It may also apply to outfits that are only available at some out-of-the-way spot far from where your fleet is usually based and where replacements need to be equipped; you may want to buy/transport them in bulk (see #570) and stockpile them somewhere more convenient.

Currently there's no way to store these things other than buying lots of junk ships, installing the outfits and parking them, which is expensive and generates a lot of clutter.

Cheap and cheerful proposal: introduce a new ship called "Warehouse", which:

1. Has a huge capacity, e.g. 5000 outfit/weapon/engine space
2. Isn't too expensive
3. Starts off parked **and cannot be unparked** (I think this is the only bit that would require code changes)

**Comment by jmhorjus** [comment]
The cases in which you'd want to do this are rare enough that I'd feel weird adding a new ship type to every shipyard in the game.  Also a bit counter-intuitive to find a warehouse in a shipyard.  

It would be easy and kinda interesting to add them in a few places though, like faction capitals or a few major shipyard planets.  

If, however, the idea of an outfit warehouse were added seamlessly into the GUI (including the option to buy outfits and place them directly into flagship cargo) it would open the door to wider/generic use of "outfit recovery" missions (currently there are only a few select storyline missions that require landing on a planet with a certain outfit installed or in cargo).  For instance, someone might pay you to get something like an Armageddon Core or a particular Atomic booster engine and deposit it into a certain warehouse. You could then just go buy the part and bring it back or try and acquire it from boarding NPC ships.

**Comment by LocalGod79** [comment]
perhaps a ship that is so massive (1megaton+), with so little shields and hull that moving it from system to system is so difficult (and is completely combat ineffective), the user requires exorbitant effort to do so?  available at "advanced" shipyards?

**Comment by mrec** [comment]
I think as soon as you make it mobile you run into balance issues. Even with very low shields, the amount of outfit space needed to make it useful as a warehouse would allow you to load it up with enough shield regenerators to make it impossible to make a dent. The immobile idea was intended to bypass all that.

To @jmhorjus' earlier point, I don't see anything counterintuitive about finding a warehouse in a shipyard, any more that it's counterintuitive to find storage lockers in a train station. It's an easily-provided service that's valuable to people using the facility; it's arguably more unintuitive to *not* find one.

**Comment by lehgogh** [comment]
If we can store outfits in normal storage space (the same space used by trade goods) and limit/disable the ability to equip and unequip outfits and weapons, this becomes a non-issue. Also, it would need to start with shields or have a very high hull strength.

If you chose to give it a high hull health instead of using shields, then the implementation of healing weapons (which I am currently working on; check my repositories) would be useful.

**Comment by mrec** [comment]
I'm not sure storing outfits in cargo space is quite the simple fix it's being made out to be. You'd still have the problem of getting the outfits placed in the cargo of your "storage" ship rather than one of your other escorts, and you wouldn't be able to park the storage one while still using it as a store. (Since parked ships don't currently count toward cargo, and there's no concept of cargo separated from the flagship+escorts.)

Obviously I'm biased, but I think I still prefer my original proposal in this thread.

**Comment by lehgogh** [comment]
Eventually, the ability to equip/transfer outfits between ships without landing will be implemented. Other than that, I'm not sure how to make this work while preventing the "OP amount of shield generators" scenario.

**Comment by jmhorjus** [comment]
Agree that the original idea is workable and only requires a small bit of C++ code (add an attribute that can be used to make a ship "always parked".  Call the new attribute "always parked".). 
If someone made something smoother that was fully integrated into the GUI that would be better.  But just adding support for the "always parked" attribute would be easy and would let mod makers figure out the rest themselves.

**Comment by Isaacssv552** [comment]
Being able to store cargo on planets and move outfits to cargo as in #570 are the two features I would most like to see added. I actually use a custom plugin that adds a variant of the Locker from the Alphean Boolean expansion just to have somewhere to stow all my loot.

**Comment by jmhorjus** [comment]
The ability to purchase outfits and have them placed in cargo is currently in https://github.com/endless-sky/endless-sky/pull/852.  (If you don't have outfit space available to install something you are asked "would you like to put this in cargo?".  Cargo is still taken with you if possible when you leave the planet, with priority given to loading it on non-flagship ships first so you have room to plunder more.)

**Comment by mrec** [comment]
#852 doesn't feel like a long-term solution. Carting outfits around in cargo for storage would effectively make "Sell All" permanently unusable, which would be a big step back for the UI.

**Comment by jmhorjus** [comment]
Depends why you are doing so; I figured having the option to put them there was better than not having that option.  
You wanted warehouses plus the option to move outfits to cargo so I figured I'd let you know I'd made one of those things, if not the other (since the other is already available in a plug-in).

**Comment by Isaacssv552** [comment]
The buy key already changes to install when you have outfits in your cargo, maybe make it "install" by default, using the current behavior of installing first from cargo and only buying if necessary, with hotkeys changing it to "buy & install", for direct installation without moving through cargo, or "buy", for moving to cargo. The same could be done for the sell button. By default it could be "uninstall" and move it to cargo, unless there wasn't enough space, in which case it could be sold. Hotkeys would give "sell", gives the current behavior of selling first from cargo, and "uninstall & sell" for directly selling the outfit without moving it through cargo.

This still wouldn't solve the inability to decide which cargo is left on-planet, but it would at least make buying and selling to and from cargo much easier.

**Comment by jmhorjus** [comment]
The trouble with any hotkeys based approach is that all the usual hotkeys (shift, alt, and ctrl) are already in use as multiplier keys (shift-click buys 5 at a time ctrl-click buys 20, etc).
