### ISSUE TITLE
[Request] Heat Generated on Death

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7240]
### Problem Description

One of the things that seems to have been a bit og a focus over the past little while (https://github.com/endless-sky/endless-sky/pull/6260) seems to be to make missiles more missile-like. It would be nice if, in keeping with this, the temperature of your ship was raised by the explosion effects and flame leaks triggered on death so that any heat-seaking missiles in the area got attracted to you instead of just zipping off into space.

### Related Issue Links

I haven't found any issues related to this, but I may have not searched deeply enough.

### Desired Solution

Have each explosion raise heat by a certain (fixed or fixed+random) value. If necessary, rewrite the missile code to see dying targets as still targets.

### Alternative Approaches

Alternatively, make heat-seaking missiles blinded by or slightly attracted to nearby dying ships. This seems a lot more complicated, though.

**Comment by Zitchas** [comment]
Right now the damage done by ships exploding is handled by a `weapon` node in the ship description. While I don't know for sure, if this node is the actually the same as the weapon node in the outfits/weapons data, then theoretically we should be able to include anything in the `weapon` category, which includes all the normal damages and DoT, etc.

**Comment by mOctave** [comment]
That sounds interesting, but wouldn't that only create heat in the final explosion?

This may have been unclear, but my idea was that heat would be created during the build-up to the final explosion, not during the explosion itself.

**Comment by mOctave** [comment]
Yes, I think that's how it works.

It's just the use of the `weapon` node that I don't think works... doesn't the weapon node only work during the final explosion?

**Comment by vitalchip** [comment]
This is an interesting idea but the surrounding mechanics don't exist to make it useful.

The initial explosions are just effects but there's nothing stopping us from adding heat to aa ship as these happen, however, nothing is going to respond to that heat.

A heat tracking missile will be more likely to retain its lock if its target is 'hotter' but it won't re-target to something else, regardless if the something else is 'hot' or 'hotter'.  That would require a rework of missile tracking.

There's also no mechanism to determine if 'ship a' is hotter than 'ship b' as heat is just a percentage of a given ship's capacity. we'd need a rework of heat which gave some equivalent of hull temperature on an absolute scale.

**Comment by warp-core** [comment]
Is the request for the dying ship to receive the heat or for nearby ships to receive?

**Comment by mOctave** [comment]
Looking back at this, it seems somehow less valuable then it did when I opened this issue, and more just a neat gimmick. It would still be a neat thing to have, but it wouldn't really add too much to the game compared with many other potential changes. I'm going to close it now, and if it looks more feasible in a few years then I may open it again.
