### ISSUE TITLE
Taking fighter as a flagship makes it impossible to use in a carrier later

### ISSUE THREAD

**Issue by ScienceDiscoverer** [endless-sky/endless-sky#7248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you use fighter ship as a flagship and leave the planet, then after landing back, fighter becomes "regular" ship and it cannot be loaded into the carrier any more (same as you can't load Sparrow, for example). See screenshot for how the ship list looks after this.

I guess this is not the #1 importance bug, maybe I'm the first player who got this crazy idea to use fighter as flagship, but still it would be nice if this could be fixed!

### Steps to Reproduce

1. Buy any carrier
2. Buy a bunch of fighters
3. Place one fighter in top spot in ship list
4. Park all other ships
5. Leave the planet and fly around
6. Land back
7. Look at the ship list and confirm that fighter is now bugged

### Expected Behavior

After landing a fighter it should retain it's grey colour in the ship list and it should be possible to use it in the carrier as usual.

### Screenshots

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/29157485/190617858-480d0f3c-21bc-4a18-a893-1e2a68402643.jpg)

### Operating System

Windows 10 Home 21H2 19044.1889

### Game Source

Steam

### Game Version

v0.9.14

**Comment by vitalchip** [comment]
Sounds like the same bug this PR addresses?

https://github.com/endless-sky/endless-sky/pull/7030

**Comment by pilover100** [comment]
From my playings with fighter/drone flags (yes, I have made drones my flagship) this does happen and can be mitigated by reloading the save with a different flagship (even reloading the same save when landed is enough). This looks like that the fighter is treated differently when it is a flag and is never moved back to normal upon a new flag being assigned.

**Comment by warp-core** [comment]
#6519 does indeed include the issue highlighted here, and #7030 should fix this.
Closing because duplicate (if #7030 doesn't actually fix this, someone should reopen.)
