### ISSUE TITLE
[suggestions] Outfitter UI.

### ISSUE THREAD

**Issue by gendalv** [endless-sky/endless-sky#7253]
- Add "C" hotkey to buy module to cargo, regardless of ship selection.
- Add "Uninstall" module as a button.
- "Uninstall" button shouldn't move module from cargo to local planet storage. You're outfitting your ship, not managing storage.
- Cargo should either be its own button or you should be able to just click again on a selected ship icon to deselect it, instead of ctrl+click.
- Moving modules from/to cargo to/from local storage should be done from the cargo screen only (no ships selected).
- Cargo screen should list the modules and their number on the bottom right and color code or segregate them (stored locally, stored in ships). This list's items should be selectable to then press "move to local storage" button or "move to cargo" button.
- Copy/paste outfits between ships (show a message if some are missing).
- (not sold here) should be displayed on uninstalled items as well.

- The "player info" screen should have a tab that lists cargo of the whole fleet.
- "Sell all" in "Trading" menu should only sell trade goods and mined resources, NOT the outfits in cargo (like that generator or gun you're caring around).

 It's annoying to be going to the map and back - just to check, if any outfitter modules are left there. Since uninstall action always puts them into local storage from cargo first, while currently installed is uninstalled last and also to storage. It's good to know what I have as a list and have an easy way of moving it back and forth, while not selling it all by accident in the trade menu.

**Comment by MasterOfGrey** [comment]
There's a template for putting forward suggestions in an issue. Please use it.

**Comment by Zern9528** [comment]
Are you saying you should be able to store outfits on a planet?

"Sell all" doesn't sell outfits, when it says sell outfits it sells outfits.

**Comment by gendalv** [comment]
@Zern9528 it's in the same button place, that appears right after trade goods have been sold, the button placement is just weird and dangerous. The only time it's been useful is early game to sell asteroids, but it could be done by adding its own button. I don't want to sell tens of millions of stored outfits by accident.

**Comment by Zern9528** [comment]
I see, yes the placement is a little strange.
But when you aren't carrying important outfits in cargo, it's really convenient to be able to double click the button to get rid of random cargo and supplies you just got from capturing ships.

You can store outfits on a planet if you select it in the outfitter and press "u", so just store important outfits on planets and it solves that problem.

**Comment by ixPost** [comment]
Also I think there should be a outfit button on all planets. The job-board should show planets with no outfits as with out a outfitter.

**Comment by MasterOfGrey** [comment]
It should have a "Sell ores" button instead, and put the "<sell other outfits>" button to the right, only drawn if you're actually carrying any

**Comment by MasterOfGrey** [comment]
At any rate, it's been 11 days. This is closed; insufficient support or reasoning for the proposed changes.

If you edit the description to utilise the features of the template which specify the details you need in a suggestion I will reopen this.
**Do not** create a new issue as a duplicate.
