### ISSUE TITLE
[suggestion] All text boxes should support standard basic text editing operations.

### ISSUE THREAD

**Issue by gendalv** [endless-sky/endless-sky#7255]
Renaming ship text box, search system box. (Also ships should be renamable in outfitters and shipyards.)
Shift-select.
ctrl+v/c/x/a.
Moving the carriage with arrow keys.
Clicking mouse anywhere inside the words to move the carriage there.

**Comment by MasterOfGrey** [comment]
Well, it's been 11 days. This is closed; insufficient support or reasoning for the proposed changes.

If you edit the description to utilise the features of the template which specify the details you need in a suggestion I will reopen this.
**Do not** create a new issue as a duplicate.
