### ISSUE TITLE
[suggestion] Add info about total fleet crew and cargo. Also show it on the "Ports" screen.

### ISSUE THREAD

**Issue by gendalv** [endless-sky/endless-sky#7256]
For passenger space: 20/100.

Cargo options:
- 300/1000. Instead of "free: 300".
-
Keep "free: 300". Tooltip says: 
1000 fleet cargo total. 
500 occupied with mission cargo and outfits.

- 300/500/1000.

**Comment by warp-core** [comment]
Please fill out the template. As it is, this issue is likely to be closed; you haven't even given reasons for your proposed changes.

**Comment by MasterOfGrey** [comment]
Well, it's been 11 days. This is closed; insufficient support or reasoning for the proposed changes.

If you edit the description to utilise the features of the template which specify the details you need in a suggestion I will reopen this.
**Do not** create a new issue as a duplicate.
