### ISSUE TITLE
Allow triggering missions/events when boarding a ship

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#726]
Feature request; probably falls under enhancement and content.  

One of the most flavorful events in EV was the "derelict ship" in an uninhabited sector.  Maybe it's a merchant captain who will pay you handsomely for rescuing him.  Maybe everyone on board has been killed by pirates or died after their reactor was looted and they ran out of energy for life support. Or maybe it's a trap and a fleet of pirates are waiting for you to dock before jumping into the system to attack!   

Once the ability exists to trigger a new mission or activate event code when boarding a ship (perhaps also when clicking the "attempt capture" button or when succeeding in the capture of a ship), you could add some really cool story code.  For instance, the first time you board a ship of faction <X> you could have a simple flavor event describing what their ship is like, what you see when the airlock is blasted open, who the defenders are, etc.

**Comment by natangold** [comment]
Umm... already exists. Not many boarding missions have been written yet, but the ability exists. See the [creating missions](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions) page for info.

**Comment by jmhorjus** [comment]
Awesome - thanks for the pointer.  I hadn't seen any missions begin on a ship after playing through the whole game and boarding pretty much every kind of ship there is, so assumed it was just something that didn't happen. Going to try my hand at creating some. :)
