### ISSUE TITLE
After loading save with mission cargo split between ships, unable to leave planet without failing as escort ship is in another system

### ISSUE THREAD

**Issue by nighanxiety** [endless-sky/endless-sky#7267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Problem summary:** 
I currently have two ships in my fleet:
1. Flagship - Clipper with cargo space of 70  (not 0/70, its just showing 70 on the info screen)
2. Sparrow with cargo space showing 0/15

I picked up a mission to take 77 tons of household waste from Charon Station in Aldhibain to Placer in the Mirach system, and the game had no problems with me taking the mission or making several landings afterwards. 
Then I took a break from playing, with my flagship was at Hopper in Kaus Australis, while my escort ship was still in the system Peacock - it was routinely falling behind and not jumping in before I landed.
  **Upon loading/resuming my game**, the Trading screen shows I have a cargo space of -7, and when I try to depart from the planet I get a warning that due to a lack of cargo space I will automatically fail the mission. 
    All of my previous 3 snapshots have the same issue while in different systems - my escort ship is still in the previous system, so its cargo space is not being counted in my total capacity, even though some of the mission cargo must have previously been loaded onto it.
    

### Steps to Reproduce

1) Pick up a Delivery mission where your fleet has the required cargo capacity, but no single ship in the fleet does.
   1.5) Not sure if required, but it may be necessary to have a few tons of additional goods on your flagship when you take the mission.
2) Jump a few systems and land your flagship on a planet/station before the other ships in your fleet arrive. Confirm you can land and takeoff without issues.
3) Save and quit Endless Sky while your escorts are still in another system
4) Relaunch Endless Sky and load the save
5) Try to leave the planet and see the Mission Fail due to lack of cargo space warning.

The issue can be worked around by modifying the save file to put the escort ships in the same system as the flagship before loading.

### Expected Behavior

1) Allow flagship to stay landed while summoning other ships in the fleet to your current system, waiting a day per jump as needed, which _should_ hopefully get past this issue, as long as fleet cargo capacity updates when they arrive.
2) Actually split the mission cargo between the ships in the fleet so that, for example, it knows I have 70 tons on 1 ship and 7 tons on the other, and doesn't think I'm over capacity.
3) Add some warning when you try to land but the rest of your fleet hasn't jumped in yet - suggest waiting until all have arrived.
   
   I see there is warning text within the mission data of the save files if not all your ships have arrived in the target system, but no such warning when stopping along the way or quitting the game.

### Link to save file

[Crag Tyrson~3016-03-05.txt](https://github.com/endless-sky/endless-sky/files/9626532/Crag.Tyrson.3016-03-05.txt)

### Operating System

Windows 10 Home; Version: 21H1;  Build: 19043.2006;  Experience: Windows Feature Experience Pack 120.2212.4180.0

### Game Source

Steam

### Game Version

v.0.9.14

**Comment by warp-core** [comment]
Pretty sure this is a duplicate of #1624.

**Comment by nighanxiety** [comment]
Agreed that looks like a match.  I guess I shouldn't have limited my searches to "mission cargo"
