### ISSUE TITLE
Killing Oathkeepers doesn't anger government

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#727]
I noticed when I was (yes, I admit it) cheating in an op Korath World-Ship and going on a rampage, angering every government I could, when I came down from the Hai and Wanderers, I started attacking Oathkeeper fleets. I killed several cruisers and a dozen or so gunboats, but looking at my map, Syndicate and/or Republic are still a medium-dark blue, not as dark as the FW, but they should have been at LEAST yellow.

Edit: this is after campaign, don't know if that has anything to do with it.

**Comment by jmhorjus** [comment]
Yep, looks like by default "Navy (Oathkeeper)" and "Republic" have no "attitude toward" one another;  they both only like Merchant and Militia, and dislike Pirate.  Not sure in what ways their attitudes change during the story, but it doesn't appear that they ever gain an "attitude toward" one another.  

If the Oathkeepers cared about republic ships, then they would likely get on your case as a result of your actions during the story, which would be counter to the narrative.  However it seems that the republic should have a positive "attitude toward" the Oathkeepers, probably .5 or so.

**Comment by Bladewood** [comment]
After the campaign is complete, if we attack the Republic, the Oathkeepers don't care.
Which means free refills of fuel on my way to the pirate worlds at the far top :)

**Comment by egilburg** [comment]
Should Oathkeepers even exist as separate faction from Navy once the campaign is over? Their oath is not to participate in the Free World rebellion, and once peace is reached they are released from their oath so they should just become part of the Navy.

**Comment by Bladewood** [comment]
According to Danforth (or some other Oathkeeper, I'm not sure about the name), they became so well known for defeating the Pug that everyone wants to join them.

**Comment by rktaylor** [comment]
Keeping Oathkeepers as a separate faction fits well into the lore. The Republic emerged from a very fractious union of what were essentially feudal states, namely Earth, outer-Core worlds, and The Deep after the Alpha War.

This would make a very quick fix, though. Just add Attitude between Republic Navy / Oathkeepers AFTER the campaign. I imagine Oathkeepers don't suffer attitude loss from the player killing Navy ships because then Oathkeepers would kill-on-sight FW ships, which defeats the point, but that should change when the Civil War ends.

**Comment by endless-sky** [comment]
Fixed in 90f00c4. Killing an Oathkeeper ship will now anger the Republic, but not vice versa. (So, in the campaign the Oathkeepers will remain non-hostile no matter how many Republic ships you kill.)

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
