### ISSUE TITLE
Add a "Show installed outfit" button in the outfitter

### ISSUE THREAD

**Issue by Drasli-Tana** [endless-sky/endless-sky#7278]
### Problem Description

In version 0.9.14, the "Show outfits in cargo" tickbox was showing only outfits in the cargo hold, but in version 0.9.15, commit 36f37be, it also shows installed outfits. When wanting to see which outfit is in your cargo such as plundered ones, you have to search it among your own equipement, this can be a bit annoying when transfering outfits from a system to another and want to check if you have everything when refueling, especially since some outfits seems to be sold silently. 

### Related Issue Links

I found nothing about it on Github nor Steam.

### Desired Solution

I suggest adding another tickbox, to enable or disable showing the installed outfit on a ship, and bringing back the old way the "Show cargo" button worked.

### Alternative Approaches

I don't have other ideas to improve this.

### Additional Context

![ui ong (2)](https://user-images.githubusercontent.com/100795666/192351423-e36e5559-1c8d-45ec-8e25-69fb69fdc2da.png)

What it looks like now:
![image](https://user-images.githubusercontent.com/100795666/192352374-d336e9f3-16fb-4580-a167-4c51e05c6720.png)

What it looked likes back then:
![image](https://user-images.githubusercontent.com/100795666/192352584-95f54934-e009-4516-b44f-9eeced759c4e.png)

**Comment by Drasli-Tana** [comment]
I forgot to add a caption to the picture, but this is to what I think this should look like

**Comment by warp-core** [comment]
You can deselect a ship by holding down control and clicking it in the top right of the screen.
This means it no longer shows the outfits installed on that ship.
If you wish to only see the outfits installed on a ship, untick all the boxes and select the relevant ship.

**Comment by Drasli-Tana** [comment]
Well, this is a bit less intuitive than before, but if it works...
