### ISSUE TITLE
Documentation Bugs

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've found a few bugs on the GitHub wiki that probably need to be resolved. I'm sure there's more, these are just the ones I'm aware of.

I'd do a PR for this, but as far as I'm aware you can't do a PR for wiki pages.

## Creating Outfits
~~Some mention of the new "display name" attribute would be a good idea.~~

> You can download the original Blender and GIMP files for any of the graphics [here](https://drive.google.com/open?id=0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk).

Should probably link to the community assets repository, not MZ's google drive.

## Creating Ships
>"category": the type of ship: "Transport", "Light Freighter", "Heavy Freighter", "Interceptor", "Light Warship", "Medium Warship", "Heavy Warship", "Fighter", or "Drone". Since 0.9.15: "Space Liner`, or "Utility".

Grave tick after "Space Liner" should probably be replaced with double quotes. Formatting "Since 0.9.15" would probably be a good idea too.

~~Same thing with "display name" as above.~~

## ~~Creating Missions~~

~~The page doesn't mention anything about `branch`, which I'm pretty sure is a real thing because I've seen it being used, but I can't be sure because it isn't on the wiki.~~

## MapData

I've found something called `arrival` in the map files, but it isn't mentioned in the wiki.

### Steps to Reproduce

1. Look through the GitHub wiki.
2. Find the issues.

### Expected Behavior

I'd expect any links to link to somewhere easily accessible, complete data to be provided for all the new things that have been added recently, and typos to be fixed.

### Link to save file

N/A

### Operating System

macOS Monterey (12.6)

### Game Source

GitHub Releases

### Game Version

Doesn't apply to the game

### Additional Information

Edit: Removed error about `branch`
Edit: I thought `display name` had been implemented, but it looks like that's still in progress.
Edit: Added error about `arrival`

**Comment by Zitchas** [comment]
The branch used in missions is actually detailed in the "creating conversations" page. But yes, the rest look like they are probably things that need updating/fixing.

**Comment by quyykk** [comment]
Fixed all the issues you mentioned, except the "arrival" because that one is mentioned in the wiki already (although it's possible someone else fixed it).
