### ISSUE TITLE
Korath use same Intrusion Countermeasures as Quarg

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#731]
The Korath have the same defense systems as the Quarg. However, the Intrusion Countermeasures description implies that this technology belongs to the Quarg and the Quarg only.

**Comment by brick96** [comment]
The korath were reduced to nothing but scavengers. A large enough fleet would take down a quarg fleet. I believe its mostly as a place holder though

**Comment by rktaylor** [comment]
I love how they're basically nearly-extinct, yet we all farm them for jump drives...

**Comment by onnikyla** [comment]
Is there going to be a korath replacement for the quarg countermeasure in the korath updates stable release? also its quite unrealistic that the korath are not extinct because i have destroyed about 1000 world ships but they still keep coming.

**Comment by Bladewood** [comment]
Stations and planets are larger than worldships.
Much, much larger.
