### ISSUE TITLE
Feature Request: Collapsable Categories

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#732]
outfitter, shipyard, map views of the same - clicking on the category title hides/displays all the outfits/ships in/below it.

i think this an easy solution to a variety of problems people seem to be having.

**Comment by endless-sky** [comment]
Added to the maps in commit 5595210. Not yet added to the planet's shipyard and outfitter.

**Comment by endless-sky** [comment]
Added to the shipyard and outfitter in commit f531580.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
