### ISSUE TITLE
allow phrases within conversation

### ISSUE THREAD

**Issue by Hurleveur** [endless-sky/endless-sky#7322]
### Problem Description

Currently if we want to give a dialog phrase to a conversation, the only way is to end it and do `dialog phrase` on the next line. This is pretty ugly for the player.
Conversations are sometimes required in order to do actions.

### Related Issue Links

I didnt find any

### Desired Solution

Allow writing phrase "" in a conversation to have the dialog phrase appear there.

### Alternative Approaches

I cant think of any

**Comment by Anarchist2** [comment]
Can't you just use the `${<phrase>}` syntax?

**Comment by Hurleveur** [comment]
Pretty sure we can't? I'm on phone but when I looked I at the code I couldnt find a way to do it
I couldnt find it not in the wiki either

**Comment by oo13** [comment]
We can use `${<phrase>}` only in the phrases.
Can you replace #6356 with the phrase within the conversation? Probably #6356 will be a major barrier to translate.

**Comment by Hurleveur** [comment]
Even if we could do it with a substitution it would stjll require to set that substitution at the start of the mission which is an extra step I'd prefer to avoid.
I dont think we can even do that with substitution currently actually?

**Comment by oo13** [comment]
I'm sorry for my poor English.

I would suggest this:
1. Introduce this feature
2. Remove #6356

**Comment by Hurleveur** [comment]
The substitutions still are interesting because they can have different values based on conditions

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/53b2382d9a1708ffd5e802492f1b697a8917aa1a
