### ISSUE TITLE
[suggestion] Order outfits.

### ISSUE THREAD

**Issue by gendalv** [endless-sky/endless-sky#7328]
### Problem Description

It's expensive to travel, when each day costs 100k+ in crew pay. After a while, I have accumulated lots of modules scattered around different systems, (some of) which I'd like to consolidate in one spot (or deliver to another system); and it would be nice to be able to order, for example, a few Hai shields and reactors to be delivered to a location I know I'll get to at some point.
Player should be able to order outfits for themselves with 2 player-placed job options:

### Related Issue Links

////

### Desired Solution

- Order consolidation: Take outfits from the local storage of one location, deliver them to another. Pay for delivery.
- Order purchase: deliver to location. This one is with advance pay for purchase + pay for delivery.
(delivery price is according to cargo space within existing mission prices.)

### Alternative Approaches

////

**Comment by petervdmeer** [comment]
This was already discussed in https://github.com/endless-sky/endless-sky/issues/3921
