### ISSUE TITLE
Outfit durability and repairs 

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#7333]
### Problem Description

Currently, outfits depreciate in value over time, but otherwise keep working perfectly forever. Replacing these with a system of equipment durability and breakdown would add richness to various game elements, making some things seem less arbitrary and curbing some cheese strategies.

For example, depreciation, instead of being a simple degradation over time, could be based on what condition the outfit is in.

Captured outfits could have considerable wear and tear already, making their reuse possible but more risky (which is very plausible; if you grab an engine out of a random pirate vessel, don't be surprised if it breaks down a week later).

Disabling a ship, instead of being all or nothing, could involve rapid damage to outfits as the hull takes damage, so you're literally taking out the systems that they could use to fight you off - and, naturally, when you loot the hull, those systems will not be pristine and ready to take, but will instead be wrecked. It might even be possible to disable a ship's engines but not its weapons, so you have to either inflict further damage and risk destroying it, or approach extremely carefully.

Exponential freighter growth would be penalised by the simple fact that maintaining a huge fleet means constant repairs are needed. Depending on the exact implementation, it might even mean regularly facing engine breakdowns in deep space and having to do in-field repairs.

Capturing vessels would be both more and less valuable; less, because you don't necessarily want to use pirates' worn-out stuff (although high-class vessels might actually have really good gear), and more, because picking up spare copies of critical parts like engines could be a lifesaver. Frequent combat might also mean wearing out your weapons and shields faster.

And it would introduce an extra way of balancing different outfits against each other, by increasing or decreasing the amount of wear and tear an outfit can take relative to others of similar types. A laser that's not the strongest or cheapest, but will keep working reliably for a long time, could be an attractive choice for occasional use.

### Related Issue Links

I'm aware that simply putting a maintenance cost on outfits has been repeatedly rejected in issues like #3659 and #4284, for adding complexity without enriching gameplay. However, this proposal isn't about just attaching a fixed daily cost; it's about presenting the player with a realistic problem to be solved (equipment eventually wears out), and how they address that is up to them.

This would provide a possible mitigation for the exponential freighter growth mentioned in #173 and #7237, an extra way to balance engine types as mentioned in #271, and a potential extra drawback of overheating (#5976; overheating a ship could damage parts you want to loot).

### Desired Solution

I think a system along the lines of Diablo 1 could work well, where each outfit has maximum and current durability values. Using the outfit decreases the current value; repairing it sets the current back to the maximum, but might also permanently decrease the maximum, so the outfit will wear out a little bit faster in future. Rather than simply breaking at durability zero, however, I'd suggest having a random chance of breaking each day, with the chance based on what percentage of the maximum is left.

There would likely need to be an option for in-field repairs, but it could be penalised compared to an outfitter, eg only partially repairing the current durability, and/or having a bigger penalty to maximum durability.

There would also need to be some adjustments to shopping, so that the player has the option to buy new outfits, if they want, instead of buying back a secondhand one. There would need to be an outfitter option for repairing outfits, likely including bulk repairs ("just fix everything on every ship and send me the bill"). It would probably also be helpful to have more options for purchasing and carrying outfits without installing them, and then later using them for in-field repairs.

### Alternative Approaches

A simple percentage, instead of having a decreasing maximum, could also work, but would have less opportunities for things like improving the depreciation calculation.

**Comment by ThrawnCA** [comment]
There might also be scope for this to nerf stolen alien weaponry; without having access to Quarg shipyards, you presumably can't do proper maintenance on that Sunbeam...

Or, alternatively, alien outfits could be buffed by being much more durable than human tech, especially for races that are hundreds of thousands of years old.

**Comment by Anarchist2** [comment]
Item durability, and a reduction in efficiency due to wear and tear is a staple of the survival genre. The reason it works well there is due to how games of that genre are structured. The player is given a limited number of resources, meaning that any damage done to items can't be easily fixed, and often has to be worked around. The only way around this is to either find resources to fix your items, or find new items, both of which can only be accomplished by playing the game and exploring. This accomplishes two goals: one is the encouragement of active strategies that take risks and bring back equipment, as acting idly will only result in your items wearing down for no benefit. The second is the creation of a gameplay loop: you go out an explore to find more resources. However, while exploring, you use up durability, meaning you need more resources to repair/replace your stuff, meaning you need to go out and explore again.

Endless Sky is not a survival game. There is no scarcity of outfits beyond what your wallet can buy, meaning that any durability issues can just be ignored by visiting the nearest outfitter and paying a small fee for repairs. Rather than encouraging active, creative gameplay, it encourages players to only use a specific set of outfits, and to work near a specific planet to reduce the difficulty of making repairs. Nor does it contribute to any enjoyable gameplay loop; all it does is add busywork for the player to manage.

> There might also be scope for this to nerf stolen alien weaponry; without having access to Quarg shipyards, you presumably can't do proper maintenance on that Sunbeam...

I hardly see this as a problem. To get these outfits, you have to plunder them, which often means besting that ship in combat, which means being better than them, which reduces the usefulness of those outfits.

**Comment by ThrawnCA** [comment]
> Endless Sky is not a survival game.

Not in the sense of literally dying, no. But it certainly does have "can't just stay put or you'll run out of money" mechanics, right from day 1, so I don't see this as an obstacle.

> Rather than encouraging active, creative gameplay, it encourages players to only use a specific set of outfits, and to work near a specific planet to reduce the difficulty of making repairs.

Actually, I would have said it could encourage the opposite. If your outfits will eventually break down completely (maximum durability gradually decreases) and need to be replaced, then you can't just set and forget them; you have to actually go shopping at least once in a while.

And players who are naturally cautious already have plenty of incentives to be homebodies, in the form of pirates. Those who are more adventurous will have no difficulties finding outfitters wherever they need to go. Or, if you find an area of space that doesn't have them - well then, when exploring that kind of territory it is very reasonable to say that you need to bring along spare parts for emergency repairs.

> Nor does it contribute to any enjoyable gameplay loop; all it does is add busywork for the player to manage.

I actually think it could make plundering and capturing ships more rewarding. Even if you have enough outfits already, you would always need more, so everything you capture has more potential to either be installed, or to be sold to pay for what you'll install.

At the same time, it would provide an avenue to prevent plundering from becoming _too_ lucrative, because heavily used outfits will have less value. And then there's the possibility that Navy ships and merchants will have outfits in better condition than pirates do, so you have an extra factor to weigh up the relative benefits...

> Crew costs don't curb freighter growth; why would maintenance costs work?

Because it's not just an extra item on your bank statement, to be ignored if you know you're in the black. It requires actual effort, to go to an outfitter and repair or replace worn out parts. The more ships you have, the more time-consuming it would become to regularly inspect them all to know which ones are still worth repairing, vs which ones are becoming too flaky and need to be sold off; or, alternatively, you could just regularly sell your outfits _en masse_ and replace them with new ones, but that's going to cost you a lot more. And there is also the possibility of ships breaking down in space and needing field repairs, which again, requires interaction, as well as introducing new actions that wouldn't occur otherwise.

> This runs into similar issues as the "nerf more" mindset: instead of making the game more fun by having bad options be usable, you make the game more annoying by having good options require constant management of the unfun kind.

Depends on what you mean by "good" options. If an option becomes so good that it makes others redundant, then nerfing it may encourage variety.

> > There might also be scope for this to nerf stolen alien weaponry; without having access to Quarg shipyards, you presumably can't do proper maintenance on that Sunbeam...
> 
> I hardly see this as a problem. To get these outfits, you have to plunder them, which often means besting that ship in combat, which means being better than them, which reduces the usefulness of those outfits.

It's just an option. As mentioned, it could even go either way; perhaps Quarg outfits could be far more durable than human ones. Having the mechanic just means that the possibility is there.

**Comment by ravenshining** [comment]
I have longed for such a mechanic....  the current never having to worry about anything as your bank account increases forever style of gameplay is just incredibly boring to me.  I love writing for and making art for this game, but I hate actually playing it for that.

Maintenance issues could be another great point of lore differentiation.  Buy Syndicate, it's cheaper than the competition and very effective... until those cost-saving measures rear their ugly heads and you break down a month later.  Buy Southbound, and you're not getting much performance for your credit, but you can be sure your great-grandchildren will be enjoying that reliable old widget.

And then, by not applying these sorts of things universally, we can accommodate people with different playstyles.  Those who *do* enjoy "fit and forget and let the credits roll in" will buy reliable, others who demand the most cutting edge or exotic equipment may find the extra effort required to keep everything running properly rewarding.

Sidenote, it might do for regular maintenance to be able to prevent an item from falling into an unrecoverable broken state, particularly for rare or hard to obtain hulls and outfits.  You can still lose them if you're not careful, but it should be avoidable, I think.

Someday in ES I'd love to have a Firefly "Out of Gas" moment.

**Comment by ThrawnCA** [comment]
> Sidenote, it might do for regular maintenance to be able to prevent an item from falling into an unrecoverable broken state, particularly for rare or hard to obtain hulls and outfits. You can still lose them if you're not careful, but it should be avoidable, I think.

A rare outfit could potentially be given an extremely high maximum durability value, so that it would essentially never break down.
