### ISSUE TITLE
Feature request: More accurate personal information

### ISSUE THREAD

**Issue by rktaylor** [endless-sky/endless-sky#734]
When we press I for info in-game, could we get a more specific Combat Rating? Because it's saved as a raw number in the save.txt file, but appears as a rank in the personal information screen, which makes things like grinding to unlock Kestrels a hard thing to predict.

(Also, am I missing something, or is it impossible to check Government Reputation standing in-game?)

**Comment by Bladewood** [comment]
For the last sentence, open the map and click the system's name.
