### ISSUE TITLE
The `wontfix` label has no description

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#7345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The [wontfix](https://github.com/endless-sky/endless-sky/labels/wontfix) label is missing a description, while all other (even descriptive) labels have one.

### Steps to Reproduce

1. Go to https://github.com/endless-sky/endless-sky/labels
2. Scroll down to the bottom of the page
3. See the missing description for `wontfix`

### Expected Behavior

All labels should have descriptions.

### Operating System

why do you care lol

### Game Source

Other (please describe)

### Game Version

Independent of the game version.

**Comment by petervdmeer** [comment]
I added some text on the `wontfix` label. Please close this issue if you agree with the new text.
