### ISSUE TITLE
Mission escorts in "The Defector" not attacking Syndicate ships

### ISSUE THREAD

**Issue by I-Am-Solaris** [endless-sky/endless-sky#7349]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

During the mission "The Defector", escort ships granted by the mission do not attack the Syndicate fleet after they attack the player. The player has to overpower the entire Syndicate fleet on their own.

### Steps to Reproduce

1. Recieve the mission "The Defector" in the Reconciliation branch
2. Bring FW fleet to Alioth
3. Watch as the fleet does not shoot any Syndicate ships

### Expected Behavior

The Free Worlds fleet should defend the player when they are attacked, helping the player destroy the Syndicate fleet.

### Screenshots

![Capture](https://user-images.githubusercontent.com/115196996/194739825-36e446a4-ee4c-44c7-88de-0a6a4938b286.PNG)

### Link to save file

[Solaris Castor.txt](https://github.com/endless-sky/endless-sky/files/9740814/Solaris.Castor.txt)

### Operating System

Windows 10 Home, version 21H2

### Game Source

Steam

### Game Version

v0.9.15

**Comment by I-Am-Solaris** [comment]
Forgot to search closed issues, this has been noted by others and looked at already. My bad.

**Comment by I-Am-Solaris** [comment]
Never mind, the other issue (#7217) was actually the opposite, where the FW escorts fought Syndicate ships while the player had good reputation.

**Comment by RisingLeaf** [comment]
It seems like this happens because there is no set reputation between syndicate and freeworlds. Would be easiest to create a under government of the syndicate that hates the freeworld. I will do this.

**Comment by Amazinite** [comment]
This new issue-PR linking UI is just straight up broken.

**Comment by RisingLeaf** [comment]
Is it something only members or collaborators can do?
