### ISSUE TITLE
Request: Buttons in the player info menu to individually (un)park ships.

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#735]
I want to bring all of my skylance ships with me, and leave out my plasma turret ships. But, it's very tedious when I have to click on every single ship and (un)park them in their ship info screens. I want separate buttons for each ship that are part of the player info menu.

**Comment by Gkramme** [comment]
like that idea.

**Comment by jafdy** [comment]
You could try using 'next' and 'previous' (hotkey 'n' 'p').

**Comment by JiBB** [comment]
I'd love to be able to shift-select a group of ships and park/unpark them all from the player info menu.
