### ISSUE TITLE
Greenview, Due Yoot description is very close to "spilling out of the UI"

### ISSUE THREAD

**Issue by a-random-lemurian** [endless-sky/endless-sky#7357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/74448738/194783421-39be2321-8ddf-4c3c-9a4d-974597c60031.png)

The bottom margin of the planet description on Greenview, Due Yoot is a little bit too thin.

### Steps to Reproduce

Go to Greenview, Due Yoot.

### Expected Behavior

For the bottom margin to not be too thin.

### Operating System

Ubuntu 20.04

### Game Source

Built from source

### Game Version

https://github.com/a-random-lemurian/endless-sky/commit/1480215ceaf417545608d00d536e5a10660482c8

**Comment by mOctave** [comment]
I can fix this.

**Comment by a-random-lemurian** [comment]
Fixed by https://github.com/endless-sky/endless-sky/commit/58b581f6f0ff199600e46994903cc8d812f87be3
