### ISSUE TITLE
Small problem on Hai Pirate Troubles [3]

### ISSUE THREAD

**Issue by RicCakes** [endless-sky/endless-sky#7363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Mission description's target npc is one random ship in Scab's fleet. The mission will still progress after you destroy/capture Keloid. My man Scab trying to hide from the duel.

### Steps to Reproduce

1. Start Pirate Troubles [3]
2. Land on Scar's Hideout
3. Decline tribute and be launched to space to fight Keloid
4. Press the map button and look at the missions then select Scar's Legion
5. See error

### Expected Behavior

Target npc is supposed to be Keloid and not one other ship in the fleet

### Screenshots

![image](https://user-images.githubusercontent.com/70306227/195008208-0df93390-77bc-4ec2-8926-72bfbf82ea16.png)
![image](https://user-images.githubusercontent.com/70306227/195008272-1ecb1123-62b5-45b4-a426-7cfe6933e7d4.png)

### Link to save file

[Aryn Cremy.txt](https://github.com/endless-sky/endless-sky/files/9751608/Aryn.Cremy.txt)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

v0.9.15 (abc64c2b)

### Additional Information

This isn't really big or anything since it only shows when you do go to the map to view the mission, which most people most likely don't.

I haven't tried it on other playthroughs yet, so I'm not sure if this is just one thing on this save.

**Comment by mOctave** [comment]
> With the given save, I take off from the planet and the ship there is called Keilod. Problem not confirmed

I believe the problem @RicCakes had was not that a ship called Keloid didn't appear in orbit, but that the ship mentioned in the mission dialogue wasn't Keilod's ship but was instead a different ship in his fleet. The ship appeared, but the mission was telling the player to target the wrong ship.
