### ISSUE TITLE
Option not to destroy ships after looting

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#7365]
### Problem Description

After looting a ship, my flagship automatically fires on it and kills it. I'd like the option not to do that.

From a pragmatic perspective, I might have realised I don't have enough space, and want to dump cargo to take their outfits. I'd also rather be further away when the ship blows up.

From a storytelling perspective, if I've disabled a pirate in an inhabited system, I'd like to be able to just remove their guns and leave them to law enforcement, instead of summarily executing them.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/1959 raises the moral dubiousness of boarding and killing everyone.

https://github.com/endless-sky/endless-sky/issues/3863 proposes taking crew alive, which is also appealing from a non-homicide perspective.

### Desired Solution

A checkbox in the preferences to control the automatic shoot-after-looting behaviour would be enough for me.

### Alternative Approaches

If looting disabled ships at all is considered immoral - even just taking the guns from a pirate - then that would also work. But I'd like to be able to still make money from beating pirates, without having to kill them all.

**Comment by bene-dictator** [comment]
I've never accidentally destroyed a ship I've boarded and left uncaptured. I don't play with automatic firing on though. You can always press I while you're at the boarding menu to select your flagship and dump cargo. 

The whole looting system never made sense to me but it's not the point here.

**Comment by ThrawnCA** [comment]
> I don't play with automatic firing on though.

That's worth a try. I do think, though, that even with automatic firing enabled, your flagship shouldn't just immediately shoot a ship after boarding it, while right on top of said ship and liable to be caught in the blast.

**Comment by bene-dictator** [comment]
That makes sense, automatic firing should be adjusted.

**Comment by petervdmeer** [comment]
Can you tell us which version of the game you are running?

A similar issue was reported in https://github.com/endless-sky/endless-sky/issues/5382 and fixed, so this is either already fixed, or a regression.

**Comment by ThrawnCA** [comment]
Ah, I didn't see that one when searching before I posted this, but I'm on quite an old version, so that's likely it. Thanks.
