### ISSUE TITLE
Remnant Distress Signal job issue

### ISSUE THREAD

**Issue by RicCakes** [endless-sky/endless-sky#7386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After accepting a Distress Signal mission, you can land after departing and finish the mission without going to the Remnant ship in said system.

### Steps to Reproduce

1. Accept a Remnant Distress Signal job
2. Depart
3. Land on planet again

### Expected Behavior

Like other Remnant Rescue jobs, we go to the system/find the system the missing/stranded Remnant ship and repair them then lead them back to mission origin world.

### Link to save file

[Aryn Cremy~3029-08-31.txt](https://github.com/endless-sky/endless-sky/files/9792613/Aryn.Cremy.3029-08-31.txt)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

version 0.9.16-alpha (ab118c6)

### Additional Information

It makes sense that the Remnant ship is in your fleet (like other mission NPCs do) since they sent a distress signal and sending telemetry data to you, but that being said, for some reason, after accepting the mission and landing back without the npc in the system, the mission still completes.

note: tried it on other Remnant Rescue job, and I noticed some of them completes itself without searching for the missing npc too. It shows dialogue of the Remnant captain thanking you

**Comment by warp-core** [comment]
I can't replicate this with your save file.
I accept the available distress signal job and take off. I see the disabled Ibis in Lire in my escort display at the bottom lefft.
I land and get the expect "on visit" message telling me I haven't finished the mission, and the mission remains in my active missions list.

Are you using any plugins?

**Comment by RicCakes** [comment]
No plugins installed. I'll try downloading my own save and see if there's anything different from what I currently have.

**Comment by RicCakes** [comment]
Downloaded it, loaded it, it still completes for me automatically even without bringing said NPC back in the origin. I tried accepting distress signal jobs in the other two worlds and results the same thing.

I'm not sure if it's my continuous build having a bug because I updated it instead of downloading another one (in ESLauncher).

![image](https://user-images.githubusercontent.com/70306227/195999583-5d56156a-51f5-4799-8dcf-11fa32e35dc9.png)
^just accepted it in this screenshot, and landing again completes it

**Comment by warp-core** [comment]
Can you upload the save file after taking off with the job?
(Accept the job, take off, close the game (without landing), upload the current save file.)

**Comment by RicCakes** [comment]
[Aryn Cremy.txt](https://github.com/endless-sky/endless-sky/files/9792747/Aryn.Cremy.txt)

**Comment by warp-core** [comment]
Still works fine for me.
Could you try downloading the continuous release from the release page here, unzipping it somewhere, running the executable in that and then testing this?

**Comment by RicCakes** [comment]
Downloaded the continuous release from here, loaded in and ended with the same result after loading in:
![image](https://user-images.githubusercontent.com/70306227/196001039-cfcaeeb6-eb48-4646-866a-b3a014b4b0d9.png)

Trying to update my ESLauncher version too, but it's probably gonna be the same result. After that, I tried accepting distress signal jobs on other worlds, but it ends on the same result.

If it's not the versions, I wonder if it's on my end somewhere. I haven't fiddled with any game files, nor downloaded plugins either.

**Comment by warp-core** [comment]
A recording would be great.

**Comment by RicCakes** [comment]
https://youtu.be/OtKcVJHTCN8

Don't know how to get it to 10mb without making the tiny texts unreadable, but this is what I did.

**Comment by RicCakes** [comment]
After trying a couple more tries, I only get more and more confused. I noticed that sometimes when I accept the mission while fast forward is on then off, it proceeds normally (need to bring missing ship back to system). But also sometimes it doesn't like what I showed. I'll try to get a recording of it, since I'm confused on how it happens. I'll edit it here

**Comment by RicCakes** [comment]
I'm not sure how it happens, but whenever I load in, accept in the job, turn on fast-forward, reload the save, it goes back to normal and I need to go to the mission system, but this isn't always the case. But after that, I can accept other distress signal missions and it goes back to the issue I mentioned.

![image](https://user-images.githubusercontent.com/70306227/196016792-c3c1b5cd-96a2-41ab-8abd-be4482310459.png)
![image](https://user-images.githubusercontent.com/70306227/196016795-352aade7-aba2-4fdc-8dd5-1eeaf9f141f5.png)
![image](https://user-images.githubusercontent.com/70306227/196016802-07ca750a-be72-4093-87f8-c252f9bc8276.png)
![image](https://user-images.githubusercontent.com/70306227/196016813-0f316065-ca02-44dd-b28c-a3f7bf14ae99.png)
(apologies for the amount of screenshots)

Seeing how warp-core can't really replicate what I'm experiencing, I'm going to close this thread. It might be a different issue about fast-forward, but I haven't tested this in any other jobs aside from the Remnant Rescue jobs.
