### ISSUE TITLE
Remnant Distress signal job offered to hidden "Patir" system

### ISSUE THREAD

**Issue by jeremymcox** [endless-sky/endless-sky#7388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While playing a Remnant rescue/distress mission job, the distress signal is from the Patir system. At this point in the game, Patir has not been discovered yet (I haven't done the mission to discover it), but this rescue mission is offered. There is no way to complete the mission, so it must be aborted. 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Don't offer rescue job for hidden system (yet)? 

### Screenshots

![image](https://user-images.githubusercontent.com/22696544/196010890-5b6e055c-0cb3-464a-abf3-6f23967ccad5.png)

### Link to save file

[Will Mason.txt](https://github.com/endless-sky/endless-sky/files/9793286/Will.Mason.txt)

### Operating System

Windows 11 Pro, 25217

### Game Source

GitHub Releases

### Game Version

v0.9.15

**Comment by jeremymcox** [comment]
![image](https://user-images.githubusercontent.com/22696544/196011046-65286ecc-6b44-4f9a-b01c-21e7bddb3b13.png)
Bottom ship shows location of distress signal.

**Comment by warp-core** [comment]
This should be fixed by #7380.
