### ISSUE TITLE
Command Center Cannot be Uninstalled With 1 Required Crew

### ISSUE THREAD

**Issue by Hecter94** [endless-sky/endless-sky#7390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Any ship with `Automaton` which has had a command center installed can not remove that Command Center unless the ship has more than one required crew. 

Meaning that if you have an Automaton ship without any outfits that add required crew, you will not be able to uninstall the Command Center until after you've added an outfit that increases the required crew of the ship. 

You can, however, install one, and will be unable to uninstall it immediately after. 

### Steps to Reproduce

1. Load [this](https://github.com/endless-sky/endless-sky/files/9793467/Command.Bug.txt) save.
2. Open outfitter
3. Attempt to remove Command Center
4. See the error

### Expected Behavior

If attempting to remove an outfit that would reduce your required crew to zero, which would normally not be allowed, but also add automaton, you should be able to do so.

### Screenshots

![image](https://user-images.githubusercontent.com/15916854/196014686-c8e441b7-b62b-4c32-a42c-dba2c9dbab4c.png)

### Link to save file

[Command Bug.txt](https://github.com/endless-sky/endless-sky/files/9793468/Command.Bug.txt)

### Operating System

Win11

### Game Source

Built from source

### Game Version

Commit: 1d0976d231ac9e11ec6299a4514363d3b4548d59

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/3bd0c763d2d17f53a324dfdec974fe6087d7fc83
