### ISSUE TITLE
Build instructions for windows are out of date

### ISSUE THREAD

**Issue by animoose** [endless-sky/endless-sky#7396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The build instructions for Windows appear to be out of date. The refer to EndlessSky.cbp. There are actually 3 .cbp files, this one for main, EndlessSkyLib.cbp and EndlessSkyTests.cbp. I had to build EndlessSkyLib and then EndlessSky. The solution to this is to create a dependency by going to the EndlessSky project, and under Project->Properties->Project Dependencies, select EndlessSkyLib.

In addition, you must use the MSVCRT version of mingw64. If you use the UCRT version, you will get a linker error:

```
undefined reference to `__imp___iob_func'
```

This is due to a change in how Microsoft implements stdin/stdout/stderr.

### Steps to Reproduce

Set up Windows build as described at https://github.com/endless-sky/endless-sky/wiki/BuildInstructions and build the project in codeblocks.

### Expected Behavior

Build should complete successfully.

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

v0.9.15

**Comment by quyykk** [comment]
Those instructions are wildly out-of-date. I would be in favor of simply deleting them, because the up-to-date instructions are located in https://github.com/endless-sky/endless-sky/blob/master/readme-developer.md.

**Comment by quyykk** [comment]
Done!
