### ISSUE TITLE
Why the landscape changes?

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#74]
I cloned the repository and went over looking at the landscape changes, except a particular one that I cringed every time I saw in-game (it was a station landscape that looked like a medieval prison, instead of a station, with a corridor with several iron-reinforced doors), I don't saw a reason to replace most of them.

In fact several I think the replacement looked worse, instead of better.

And other several, the replacement was just different, not better, or worse, it would have been nicer to isntead add those pictures as more landscapes possible instead (ie: if there is 7 "desert" files instead of replacing the old 7, just have 14 instead).

But that is just my opinion, I wrote an issue because I found no better way to communicate in public. (I guess the project don't have a mailing list/forum/irc?)

**Comment by endless-sky** [comment]
I'm working on creating double-resolution versions of all the graphics (for large / high-DPI monitors), and for some of the existing landscapes looked really bad at 1440 x 720 resolution (blurry, JPEG compression artifacts, etc.). There are also a few for which I simply couldn't track down the original photos.

If there are any new ones that you think are particularly ugly, I can either try harder to find the originals or look for a higher-quality alternative.

I've got a mailing list (endless-sky@googlegroups.com), but the issue tracker is just as convenient.
