### ISSUE TITLE
Make unique items harder to accidentally sell

### ISSUE THREAD

**Issue by aradapilot** [endless-sky/endless-sky#7404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Tear of Skade" outfit, a permanent one like a license, is not preserved like a license when a ship is sold, and is therefore permanently lost by the player when they change ships (unless they know about this issue and go work around it in outfitter before departing the planet).

### Steps to Reproduce

1. Go through the skadenga questline until you get this reward
2. Trade your ship in for a new one
3. Leave the planet

### Expected Behavior

Unique outfits (licenses being the easiest example) persist to the player, not to the chassis

### Operating System

ubuntu 22.04

### Game Source

Steam

### Game Version

0.9.16

**Comment by aradapilot** [comment]
I forget if the void rifle is also affected by this or if it works correctly - but that's another similar one

**Comment by quyykk** [comment]
This sounds more like a feature request. Only licenses (and maps in a way) get preserved, since both aren't really an outfit. Every other outfit is treated the same.

**Comment by Amazinite** [comment]
Actually already in the works somewhat. v0.9.15 added a new "Unique" category for certain outfits, the Tear of Skade included. The next step is to make it so that such outfits are harder to lose track of.

**Comment by Hurleveur** [comment]
I lost my tracking device once and the void rifle another time, would be nice indeed to have such a feature.

**Comment by a-random-lemurian** [comment]
This might be obvious already but this can be temporarily mitigated by file-editing your unique item back until we add a more permanent solution for this.
