### ISSUE TITLE
Possible to accidentally decline Katya's offer due to ambiguous dialogue

### ISSUE THREAD

**Issue by frymaster** [endless-sky/endless-sky#741]
It is not at all obvious that the line ``Fair enough, but I don't like working with people who start conversations by pointing guns at my head. Even unloaded guns.`` will decline Katya's offer.  To me, the phrases "fair enough" and "working with" imply "conciliatory" and "if you want me to work with you don't do this again" - in other words, it implies I want to accept, or am at least still negotiating

Since declining seems to be an irreversible action it would be nice if it were telegraphed better.  ``Sorry, but I won't work with people...`` or similar.

**Comment by Gkramme** [comment]
I'll add a PR for this.

**Comment by Gkramme** [comment]
Fixed this. Proposed PR.

**Comment by endless-sky** [comment]
It's actually _not_ an irreversible action; if you choose that response but later help the Free Worlds in other ways, she'll seek you out and apologize for how she behaved toward you the first time around, and make you another, more polite job offer.
