### ISSUE TITLE
Cannot reset jump path when clicking on current system with jump drive

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#744]
With a hyperdrive, if you are at a planet and click on a system using the map, if you leave the planet, you can reset the path by clicking on your current system. But, if you have a jump drive, you cannot reset it. It is stuck at the first system on your path.

**Comment by endless-sky** [comment]
Actually, it looks like it does the same thing if you have a hyperdrive. The issue is that if your ship already has a destination system set, the game will fill in that system as your jump path if you have not specified a path to override it.

**Comment by endless-sky** [comment]
This should be fixed by commit 81ceac7.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
