### ISSUE TITLE
Quarg moon in Tarazed can be visited with a bad reputation

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#745]
The Quarg moon Echo in orbit of Wayfarer, being part of a Republic/neutral system (depending on where you are in the plot), can still be visited even if you have angered the Quarg.

**Comment by Gkramme** [comment]
Thats because you cannot make a system with planets from a different government.

**Comment by jmhorjus** [comment]
I made a pull request to address this:
https://github.com/endless-sky/endless-sky/pull/777

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
