### ISSUE TITLE
New India / Albaldah stays as part of the Republic after Tarazed becomes neutral

### ISSUE THREAD

**Issue by bene-dictator** [endless-sky/endless-sky#7459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

New India / Albaldah stays as part of the Republic after Tarazed becomes neutral when Tarazed Diplomacy is completed.

### Steps to Reproduce

1. Complete Tarazed Diplomacy.
2. Click on the map.
3. Select Albaldah.

### Expected Behavior

New India and Albaldah should become neutral, like Girtab, Dabih, and Tarazed.  

### Screenshots

![Screenshot_20221024_215236](https://user-images.githubusercontent.com/115441627/197487676-b3b66930-7367-4aeb-84cf-06cdf2edbf9f.png)

### Operating System

Fedora 36

### Game Source

ESLauncher2

### Game Version

Continuous build on 24/10/22

**Comment by Anarchist2** [comment]
Tarazed only has jurisdiction over itself and the surrounding systems. Albaldah is outside of that. Girtab is also unrelated, and becomes neutral due to religious reasons.

**Comment by bene-dictator** [comment]
Those reasons aren't mentioned in the dialogue of the game, and New India is one of the planets that defect with Tarazed later too, so I had thought it was just an oversight. Even so, why can't Albaldah be in Tarazed's jurisdiction? It's a tiny colony and it's closest to Tarazed than any other regional centre. That explanation doesn't make that much sense to me. I see that Girtab becomes neutral because of the militia and the Navy being on friendly terms. 

Really I'm annoyed about the gap in the map, but it's not a big deal if it's intentional.
