### ISSUE TITLE
Deep Security will happily arrest First Last during FW reconciliation

### ISSUE THREAD

**Issue by AbsolutelyLudicrous** [endless-sky/endless-sky#7465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the player has done Deep Archaeology & gotten chased out of the Deep, but has not yet returned by the time the war is cooling down, Deep Security will happily nab them from the spaceport, even if they're on a diplomatic mission & have a Navy Intelligence escort.

### Steps to Reproduce

In the attached savefile, continue FW reconciliation as normally, and be very surprised when the spaceport cops nab you in the middle of a diplomatic mission. If you've the patience to wait for the ramscoop to refill the tanks enough to get all the way to Valhalla, First Last is then described as opening the door to their ship, getting nabbed, getting interrogated, and getting thrown out on the street, then going back to their ship, and meeting the governor of Valhalla as if his goons totally didn't just kidnap you.

### Expected Behavior

Propose auto-failing Deep: Interrogation after a set period of time, or after the war ends.

### Link to save file

[Acid Burn~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/9862850/Acid.Burn.previous-1.txt)

### Operating System

Fedora

### Game Source

Other (please describe)

### Game Version

0.9.16 Flatpak

### Additional Information

The drones in the savefile include some homebrewed outfits that will error out, but shouldn't influence play in any other way.

**Comment by SimulatedKnave** [comment]
This quest is rather flawed in a few ways, since it also can gloss over the bit where Deep Security blew up your escort ships, killing people (over what they admit to be nothing illegal), and they act like you're the jerk.

**Comment by Amazinite** [comment]
We'll make it so that this mission can't offer during the main campaign.
