### ISSUE TITLE
AppImage won't run

### ISSUE THREAD

**Issue by kxygk** [endless-sky/endless-sky#7476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't seem to run the AppImage on Ubuntu

```
> chmod +x ./endless-sky-x86_64-v0.9.16.1.AppImage 
> ./endless-sky-x86_64-v0.9.16.1.AppImage 
execv error: No such file or directory
```

Similarly if I launch through AppImageLauncher

```
> AppImageLauncher Downloads/endless-sky-x86_64-v0.9.16.1.AppImage 

(process:6672): GLib-CRITICAL **: 18:59:33.700: g_file_test: assertion 'filename != NULL' failed
execv error: No such file or directory
```

### Steps to Reproduce

Download AppImage, change permissions to executable, run

### Expected Behavior

Expected to launch the application

### Operating System

Ubuntu 22.04 Jammy

### Game Source

GitHub Releases

### Game Version

AppImage

**Comment by quyykk** [comment]
It works just fine on a clean Ubuntu 22 VM. Apparently this is a problem with the AppImageLauncher for some reason. From what I can tell, you have two options:

- Uninstall AppImageLauncher and install it using the [official PPA](https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian#use-the-ppas). (unless that is how you installed it already)
- Uninstall AppImageLauncher and reboot

Related issues: https://github.com/TheAssassin/AppImageLauncher/issues/461 and https://github.com/TheAssassin/AppImageLauncher/issues/518

**Comment by kxygk** [comment]
Oh well this is embarrassing... 
I somehow missed that in my Googling. But yeah, uninstalling did the trick. I'll try their PPA next. Very strange.. it'd worked for all my other AppImages in the past. Hope this helps anyone else that hits this issue!

 I really appreciate the help here. Sorry for making you debug my system.

PS: The offical PPA is out of date btw
