### ISSUE TITLE
CTD when firing missiles

### ISSUE THREAD

**Issue by bene-dictator** [endless-sky/endless-sky#7487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When my ship (a wasp) is firing sidewinder missiles at a bounty pirate, the game crashes to desktop. 

### Steps to Reproduce

1. Open save.
2. Jump to Scheat where a bounty pirate is waiting. 
3. Select missile and the enemy ship, then fire missiles.
4. Crash to desktop before missiles collide with bounty pirate. 

### Expected Behavior

No crashing, the missile makes contact (update: sometimes some missiles make contact but crash will happen shortly after)

### Link to save file

[Stavro Mueller.txt](https://github.com/endless-sky/endless-sky/files/9895482/Stavro.Mueller.txt)

### Operating System

MacOS Monterey 12.6, M1 Macbook

### Game Source

ESLauncher2

### Game Version

commit 41186b5bbd8af2b02f735cedbd3ff5d0ad6fb7d8 (downloaded 28/10/22). 

### Additional Information

Also occurs on v0.16.1 downloaded from Steam.

**Comment by bene-dictator** [comment]
I think this is an issue with MacOS because I've tried the save on linux (latest continuous) and it did not crash. But if someone else has a Macbook and can replicate it it'd be good.

**Comment by mOctave** [comment]
Running MacOS Ventura 13.0 on an M1 Macbook, I can't replicate the issue with the latest continuous version downloaded using ESLauncher 2 (`83e99e8`). It is using around 5GB of memory and 30-40% CPU, but it does not crash nor does the CPU/memory usage change with the launch of the sidewinder missile. What happens when you try it on `83e99e8`?

**Comment by quyykk** [comment]
> I think this is an issue with MacOS because I've tried the save on linux (latest continuous) and it did not crash. But if someone else has a Macbook and can replicate it it'd be good.

MacOS has more runtime checks than on Linux and Wndows, so it is not surprising to me. Did you save the crash log? that would be very helpful. Thanks!

**Comment by bene-dictator** [comment]
Yes, it still crashes on the latest Continuous [83e99e8](https://github.com/endless-sky/endless-sky/commit/83e99e8e01e5e1d7ecfa095135a1b7ec9176e667). I didn't see anything change with performance. Where can I find the crash logs?

**Comment by quyykk** [comment]
Application -> Utilities -> Console. They should be there from what I can tell (I don't own a Mac so I can't verify)

**Comment by bene-dictator** [comment]
There is a ton of logs (all within 20s). It is quite long and I'll put it into a .txt file. In Console I searched for everything to do with "Endless", the rest (a ton more) is to do with the system I'm guessing. 
[Console log.txt](https://github.com/endless-sky/endless-sky/files/9897112/Console.log.txt)

**Comment by quyykk** [comment]
Those are the logs from the ESLauncher2 (and they're not important since it was the game that crashed). You can zip them if it's easier for you.

**Comment by bene-dictator** [comment]
I'm not getting a crash report at all whether I launch it from the standalone, Steam, or ESLauncher2, and no crash reports are coming up in Console. ESLauncher2 reports that the Endless Sky is exiting with exit status 0.

**Comment by mOctave** [comment]
Can you launch it using the executable file?

Right click the standalone, click "Show Package Contents," and find the executable named "EndlessSky." Launch that (either by double-clicking it or by dragging it into Terminal, and you should get debug of what's going on. I don't think it will give a full crash report, but it should at least provide some background information.

---

<img width="306" alt="Screenshot 2022-11-03 at 7 00 44 PM" src="https://user-images.githubusercontent.com/73318970/199869024-90fca681-45f8-4f1c-962a-b957549bdd4e.png">

---

<img width="724" alt="Screenshot 2022-11-03 at 7 01 19 PM" src="https://user-images.githubusercontent.com/73318970/199869093-a86fdbc6-9334-47d7-b7f9-4ddc0d03f878.png">

**Comment by bene-dictator** [comment]
Haha, I've only realised now. This is because of my keybinds. Firing missiles is bound to command and I'm pressing W to move forward, so it's closing it every time I press both at the same time. I should have known! Thanks for your help.
