### ISSUE TITLE
Navy Generals or Admirals

### ISSUE THREAD

**Issue by psychiclegume** [endless-sky/endless-sky#749]
"Four of the Navy generals who are stationed here have agreed to meet with you."
Wouldn't it be Navy Admirals, just like in most English navies? Just nagging at me.

**Comment by endless-sky** [comment]
Yes, that's technically correct - just something I have not gotten around to fixing yet, since it means changing every time where they are mentioned.

**Comment by psychiclegume** [comment]
Couldn't you Ctrl+F and replace all at once on each Free Worlds mission .exe?

**Comment by LocalGod79** [comment]
they can (and probably will), but as you can see, the open issues number is approaching a thousand, while there are maybe a couple of dozen people resolving them in their spare time...

**Comment by thomasballinger** [comment]
I've taken a shot at this, @psychiclegume or anyone else it'd be great if you could proofread the diff (see https://github.com/endless-sky/endless-sky/pull/751/files) to see if all the changes make sense.

**Comment by thomasballinger** [comment]
Oh @psychiclegume, unless you're currently playing and don't want spoilers – don't read if you don't want to know what happens!

**Comment by psychiclegume** [comment]
already finished the storyline twice

**Comment by psychiclegume** [comment]
Now that I look it over, it looks fine either way

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
