### ISSUE TITLE
Game compiled by me won't launch

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#75]
I compiled the game on windows using mingw.

It does not launch, I spent now about 5 hours trying to track the bug, and reached a certain area where I cannot go forward it seems.

Basically, the file DataFile.cpp has an error probably in the function void DataFile::Load(const char *it, const char *end) (the error might be in the function that calls this instead)

Using the debugger, I get the error when it is attempting to read the file "data/free worlds checkmate.txt" or righter after reading this file (thus while trying to read the next file, that is probably "free worlds epilogue")

The error is stored on windows as the error 0xC0000374 that from google searches are a heap corruption error, usually caused by buffer underruns

GDB instead reports the error as SIGTRAP In ntdll!RtlpNtMakeTemporaryKey () (C:\WINDOWS\SYSTEM32\ntdll.dll)

**Comment by speeder** [comment]
I decided to "debug" the txt file, I went deleting parts of it, until I could find the exact line that crashes.

The line is line 987, that has as content two backticks ( `` )

If I delete this line, the file loads, if the line is there, the whole program crashes.

**Comment by speeder** [comment]
Found the line that causes the error: line 143 of datafile.cpp, `node.tokens.emplace_back(start, it);` I don't found out why yet, only that commenting it makes the error go away.

**Comment by endless-sky** [comment]
This might be related to the missing close-quote on the line following that one (bdfeb53).

What compiler and C++ library are you using?

**Comment by speeder** [comment]
After fixing taht stuff, compiling here still won't work (I get lots and lots of segfaults and runtime errors, for example "Uniform colour not found")

I used Mingw64, and Winbuilds for most part, and codeblocks (since you had a codeblocks project already there...)

**Comment by endless-sky** [comment]
Are you following the [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions) from the wiki? In particular, there is a link there to a set of [development libraries](http://endless-sky.github.io/win64-dev.zip) that are known to work for compiling on Windows.

**Comment by speeder** [comment]
Oh, nope :) I was trying to follow the build instrunctions on the file, that only explain the OSX stuff... I have not seen that there was also instructions on the wiki, I wish I had seen that earlier (it was a pain the ass to find all the libraries on my own)

**Comment by speeder** [comment]
Alright, got your libraries, told git to revert all my local changes, and tried to compile.

The good news is: it compiled REALLY, REALLY easily, I should have done that from the start!

Bad news is, lots of 0xC0000374  errors.

**Comment by speeder** [comment]
I went in sublimetext, did a find and replace in all files, and replaced all ``  with ` `  (I put a space between the two things).

Now the game works fine.

I went to look more at why this is happening, although commenting a certain line makes the error don't happen, it instead crashes the game because of missing data (but that was expected).

Anyway, you are calling a string constructor with 2 pointers, the constructor builds a new string object with first thing on the pointer included, and the last not included.

when your program finds a `` the first, and last pointer are the same, you then are telling the constructor to build a string that includes something, but does not include the same thing, something that is logically impossible.

Somehow linux and osx tolerates this, windows on my case, is breaking the heap, probably what it is doing is allocating 0 bytes and returning a pointer to the place where it allocated 0 bytes, then the destructor destroy a string object, with more than 0 bytes, pointed by that pointer, and the OS kills the program and emits the 0xC0000374 error (it means heap corruption, it happens when you free() a pointer that is pointing to the heap)

If I figure how to fix it I will send a pull request.

**Comment by endless-sky** [comment]
That sounds like a library bug - constructing a string with an empty iterator range should create an empty string, without any heap corruption problems. What version of MinGW are you using?

**Comment by speeder** [comment]
I believe it is 4.8.2 (x86_mingw64)

**Comment by endless-sky** [comment]
See if commit #519ae2b allows your compiled binary to run even if you revert your changes to the data files.

**Comment by speeder** [comment]
Issue fixed! =D
