### ISSUE TITLE
Add Title Guidelines to PR Template

### ISSUE THREAD

**Issue by Hecter94** [endless-sky/endless-sky#7504]
### Location

PR Template

### Describe the issue

Right now, there is no standard for writing meaningful PR titles, leading to most of our PRs being titled based on the author's whim. 

This leads to a degree of confusion as to what a PR is doing or editing, which requires opening the PR and reading the description to get a good grasp of what the PR is doing. 

This also often results in a maintainer needing to manually change the title of the PR to match our standard. 

### Expected content

An additional section in the PR template at the top which describes how the PR should be titled to follow our style guide. 
Zitchas suggested: `<type>[scope][faction]: Title` e.g. feat(content): Remnant intro missions
per the following guide: https://www.conventionalcommits.org/en/v1.0.0/

I would suggest a layout such as this:

## Proper Titling

PRs must be titled to conform to our style guidelines. 
A good PR title will use the following structure:
`<type>(<scope>): [optional faction] Title`

<details>
 <summary>Suggested Types</summary>

- `build`: Changes that affect the build system or external dependencies.
- `chore`: Changes to the build process or additional tools and libraries such as documentation generation.
- `ci`: Changes to our CI configuration files and scripts.
- `docs`: Documentation only changes
- `feat`: A new feature
- `fix`: A bug fix
- `perf`: A code change that improves performance
- `refactor`: A code change that neither fixes a bug nor adds a feature
- `style`: Changes that do not affect the meaning of the code (white space, formatting, missing semi-colons, etc.)
- `test`: Adding missing tests or correcting existing tests

</details>

<details>
 <summary>Suggested Scopes</summary>

-   `content`: Additional missions, ships, outfits, or other content that doesn't require code changes
-   `balance`: Addition or modification of existing ship/outfit stats
-   `mechanics`: Modifications to the game engine which affect gameplay
-   `UI`: Modifications of existing User Interface elements
-   `enhancement`: Additional features added to the game engine

</details>

<details>
 <summary>Suggested Factions</summary>

-   `Human`
-   `Hai`
-   `Wanderer`
-   `Remnant`
-   `Builder`
-   `Korath`
-   `Coalition`
-   `Quarg`
-   `Drak`
-   `Pug`
-   `Sheragi`
-   Others not listed are allowed; use your best judgment when necessary.

</details>

<details>
 <summary>Title</summary>

- Provide a clear, concise, and descriptive title of your PR's function without repeating information already provided with the previous tags.

 </details>

**Comment by Zitchas** [comment]
Some clarity and definitions would be good, I think. For instance, what is "chore"? I've seen it used for some routine things, but it's not super clear.

**Comment by Hecter94** [comment]
I added some definitions in the example.

**Comment by petervdmeer** [comment]
Some automated CI/CD check that verifies if the title matches our guidelines would also be nice.

**Comment by quyykk** [comment]
I don't think we should be so strict for PR titles. And I don't think it's possible for CI to check a PR's title? Unless it's possible through GitHub API calls but it's seems unnecessary to me.

**Comment by Hecter94** [comment]
I would appreciate having some simple guidelines with definitions when opening a PR because I want my PR titles to be meaningful and informative but I don't know what format to use or what keywords to add to the title. 

So having a standardized reference in the PR template that I can refer to would be something I would appreciate, and I imagine others would as well. 

It's not so much a "Rule"; it's not like we're going to close PRs that don't follow the proper naming scheme; it's just guidelines and a quick reference for the benefit of contributors. 

In terms of a CI/CD check, it looks like we could set up something like this?
https://github.com/marketplace/actions/pr-title-checker

We'd just need to make a valid Regex query that titles should match, it looks like we could even automatically label ones that are in the right format, which could reduce the load on our reviewer team somewhat.

**Comment by ravenshining** [comment]
Yeah, I would appreciate a guide, because I do put effort into trying to name my PRs as close to how to the commit ought to be titled as possible, but I don't always know what exactly to put.

At the same time, having a hard and fast rule would be a bit much, just like how sometimes the template doesn't work for a PR and the section order and names need to be tossed.  The only concrete bits IMO ought to be the sections about attribution, high-dpi, and assets.

**Comment by Hecter94** [comment]
The PR for this was closed as not a desired change, so closing this issue as well.
