### ISSUE TITLE
Build broken by undefined erf in 201bc0

### ISSUE THREAD

**Issue by thomasballinger** [endless-sky/endless-sky#752]
The build is broken for me by undefined `erf` in https://github.com/endless-sky/endless-sky/commit/201bc0cf381483e9e80cb77cd1ed3e1e9a24004c#diff-4bd5672e0815e4b2e529600f60836d6eR511

**Comment by endless-sky** [comment]
See if commit fb94c4c fixes that for you.

**Comment by thomasballinger** [comment]
Yep, thanks!
