### ISSUE TITLE
Millions of ships for defense fleet?

### ISSUE THREAD

**Issue by bchis17** [endless-sky/endless-sky#755]
I don't like that there are millions of ships just protecting the most worthless planet in the system I'd like just like to downsize defense fleets a bit just to keep it fair for example The most poorest pirate world in the galaxy and it has hundreds of ships it's not like pirates have a private shipbuilding company.

**Comment by masterpierround** [comment]
I haven't run into a single planet that has anywhere near 100 ships protecting it, although I will admit that I have only dominated 4 pirate systems. Could you elaborate on which systems you are referring to?

**Comment by endless-sky** [comment]
The whole point of planetary domination is for it to be the one challenge left for a player who is strong enough that everything else is easy. Decreasing the fleet strengths would work against that.

**Comment by brendanjones** [comment]
Agreed. Considering that with only 20 (Quarg'd out) Bactrians you can take over the hardest planet in the solar system - Earth - I don't think there's a problem here. If anything, make them harder (until Quarg weapon DPS is nerfed)!

**Comment by Gkramme** [comment]
They are addng drak systems, and fighting one of their ships is harder than demanding tribute from a big republic planet.

**Comment by lehgogh** [comment]
There aren't "millions" of ships. You're likely fighting ships that are jumping in and joining the fight.

**Comment by jmhorjus** [comment]
Most defense fleets are actually pretty small, like a few dozen ships at most.  Earth is the hardest of them all and I think it has 50 big capital ships.
However, if the system has a high rate of ships of that faction flying in over time, they will *all* join the fight continually, which can make the fight impossible if you can't kill them faster than they arrive.

**Comment by bchis17** [comment]
Shaula, pirate world this my first attempt to capture a planet and it has been unsuccessful but I'm bored but just to ask is there going to be a navy storyline.

**Comment by jmhorjus** [comment]
Yep, navy story will definitely exist, but I don't know if anyone is in the process of writing it yet. 

You should look at the forum (https://groups.google.com/forum/#!forum/endless-sky) to see what sorts of things people are working on currently.  That's a great place to find mods and ask questions that aren't "bug reports" and thus don't really fit in the bug-tracking database here.

**Comment by natangold** [comment]
Shaula is, IIRC, the strongest pirate system in the South by a long shot, plus it has pirate ships warping in every dozen seconds or so.
