### ISSUE TITLE
Steam Workshop Implementation

### ISSUE THREAD

**Issue by DaRealSparky** [endless-sky/endless-sky#7559]
### Problem Description

I saw that Steam Cloud support was added and thought, "Maybe they can do the same (or similar) to add workshop support for the steam release." You could point it to the 'Plugins' folder next to 'Saves' or the one in the installation folder.

This would give Plugin Authors an easy way to share their plugins with everyone and new(Steam) players a place to browse extra/new content for the game. And the Plugins would also sync between devices because Steam would auto download the workshop items when it starts or installs a new copy of the game.

### Related Issue Links

N/A

### Desired Solution

N/A

### Alternative Approaches

In game Plugin browser that points toward a database with links to download and install Plugins automatically.

**Comment by Hecter94** [comment]
From my understanding, the Steamworks SDK is incompatible with OSS, and would require either wrapping the game in a launcher, which could be problematic or getting permission from all of the current copyright holders (of which there are 100+) to modify the game license to one that is supported by Steamworks. 
So it seems like it will be difficult to implement something of the sort, though it would be cool.

**Comment by DaRealSparky** [comment]
That's why I suggested an alternative that was an entirely in-game, Steam-independent Plugin Browser. It would work regardless of where you play the game. Steam, GitHub, Windows, Mac, Linux, it would work on anything easily and (I'm assuming) wouldn't require a license change. Authors would just register their Plugins in the database and the the game would be able to find and install them with the push of a button. There could also be a version system so the game could automatically download updates for plugins so people don't have to worry about missing new content. 

This whole idea popped into my head awhile back but wasn't really certain about the details until I started typing it out. Should have done this sooner. LOL

**Comment by mOctave** [comment]
Another issue is that, while the game is on Steam, not all plugin authors are. Additionally, not all plugins are worth playing with (there's around 400 plugins, but probably at most a quarter of these are both polished and not jokes).

The alternative method would work however, and I think it may have been suggested before. It would definitely be a really useful feature, but it would probably require some pretty extensive coding. I'd love to see the feature, but it will probably take a while, even presuming that there are no major problems.

**Comment by Zireael07** [comment]
> From my understanding, the Steamworks SDK is incompatible with OSS, and would require either wrapping the game in a launcher, which could be problematic or getting permission from all of the current copyright holders (of which there are 100+) to modify the game license to one that is supported by Steamworks.
So it seems like it will be difficult to implement something of the sort, though it would be cool.

Many open source games are on Steam, and I believe at least one uses the workshop.

**Comment by Zireael07** [comment]
@Hecter94 Yes, as re-licensing requires 100+ people to agree to it, I agree it's not practical for ES
