### ISSUE TITLE
Crash on opening map

### ISSUE THREAD

**Issue by Drasli-Tana** [endless-sky/endless-sky#7564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During the "Hai diplomacy" mission, once I've lift off from Hai-Home, the game crash every time I try to open the star map, either through the assigned key ("M") or with the job board button if landed.

### Steps to Reproduce

I've no idea of how to reproduce, maybe complete the Devil-Run's quest-chain and open the map during travel to Mountaintop.

### Expected Behavior

The star or jobs map should open and the game shouldn't crash.

### Screenshots

https://user-images.githubusercontent.com/100795666/201442405-bb032e1f-ece1-4531-b402-7486700635e1.mp4

https://user-images.githubusercontent.com/100795666/201442410-1f17c046-54c2-4ba9-9e45-efd4718fa3d5.mp4

### Link to save file

The file after the landing in the video
[a a~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/9993599/a.a.previous-1.txt)

and the save before take off from Hai-Home
[a a.txt](https://github.com/endless-sky/endless-sky/files/9993600/a.a.txt)

### Operating System

Windows 10 Pro

### Game Source

GitHub Releases

### Game Version

V0.9.17 commit 1c8cd7f from continous build zip download

### Additional Information

When emerging from the wormhole, Moutaintop doesn't exists anymore.

Maybe related to this too: https://github.com/endless-sky/endless-sky/issues/7495

**Comment by warp-core** [comment]
This seems to have been as a result of https://github.com/endless-sky/endless-sky/pull/7492#issuecomment-1300411068.
It does highlight an unsafe pointer dereference, probably in MapPanel, that I'll try to find and make safer.
[a.a.txt](https://github.com/endless-sky/endless-sky/files/9993653/a.a.txt)
I have edited your save file to update the changes so that it no longer crashes.

**Comment by warp-core** [comment]
Should be fixed by 7e4b03d.
