### ISSUE TITLE
Afterburners are too good

### ISSUE THREAD

**Issue by dukc** [endless-sky/endless-sky#7574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In mid-to-endgame, despite their fuel usage, afterburners are just too good for anything else to be practical.

I have not tested, but at start of the game afterburners might be quite balanced, since outfit space is constrained and ramscoops are inefficient. However, when one gets access to wanderer ramscoops and/or fuel processors in a capital ship, used fuel can be replenished so quickly that afterburners become overpowered. Even the Caldera afterburner, alone, will give most capital ships more acceleration and top speed than most interceptors have.

One does not even need a lot of extra fuel. Around 1000 fuel (for Hurricane) is easily enough for most battles, assuming the tank has been topped at previous star system. The reason why no more fuel is needed is that almost nothing can keep up. A few seconds of acceleration away from the heat of battle, and then one can coast away with no further fuel usage, as far as needed. This also means the heat from the afterburner is far less of an issue.

With a cloaking device, recharging fuel in battle is easy too: fly towards the star with a slow speed, and cloak before being attacked. With three or so Wanderer ramscoops, fuel will be harvested faster close to the centre than the cloaking device consumes.

This all applies even with human afterburners only. They are already better than any Korath, Hai or Remnant regular engine, and there is no reason to use those except perhaps for reverse thurst or maneuvering while cloaked. Korath afterburners are, obviously, even more overpowered.

### Steps to Reproduce

1. Have a capital ship with a jump drive.
2. Install maybe 20 of ramscoop capacity.
3. Upgrade your fuel capacity to 1000 or more.
4. Install enough afterburners for top speed of 1000 or more, and sell other thrusters.
5. Install powerful steering to go with the huge thrust.
6. Equip otherwise for battle as you see fit.
7. Go to battle.
8. Compare how it does versus regular engines.

### Expected Behavior

Afterburners should be less powerful in the end game. Probably still better than they were in 0.9.14 though.

### Operating System

NixOS 22.05

### Game Source

Other (please describe)

### Game Version

Revision 6512315312381e6d12b2b3702a1e7cd69c98073c

### Additional Information

It's the [standard Nix packaging of Endless Sky](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/endless-sky/default.nix#L33), custom-modified to build said revision instead.

**Comment by Hurleveur** [comment]
I agree that afterburners are too strong currently, I'm finding myself equipping only afterburners instead of using thrusters at all on all big ships, whenever I want speed.
Do note that they sometimes cost a lot of fuel (remnant ones) and sometimes heat you up a lot (Korath)

**Comment by binaryspica** [comment]
But is it really meaningful to add one if it wasn't powerful that much? And why we need for the fast speed in the first place? 200~300 is already enough for the escorts, and even the flagship is doing well on 250~300. Make it faster doesn't gives you much other than enjoy the space ride - it doesn't do much in combat either.

Also Ramscoop bonus is not simple add, and you need to have the good relation with Wanderers as well. Ah, don't forget that firing that afterburners easily makes you have far distance with the star therefore you may hard to collect the fuel again if you didn't check your fuel reserve.

**Comment by dukc** [comment]
> Make it faster doesn't gives you much other than enjoy the space ride - it doesn't do much in combat either.

I quess it depends on your play style. I find speed makes it easier to survive. I often want to retreat to recharge my shields, or just to not deal with all the enemies at one time. It's a lot easier with strong thrusters than with a hyperdrive since I don't have to worry about being able to stop for the jump.

> Also Ramscoop bonus is not simple add

True, but still with 3-5 Wanderer ramscoops you get a LOT of fuel.

> and you need to have the good relation with Wanderers as well

Not necessarily. Fuel processors and catalytic ramscoops, while not as good, already are enough to make afterburners OP on a big ship that can fit many of them.

**Comment by binaryspica** [comment]
If you want to retreat then you should have great distance with the star but did your ramscoop gives enough fuel for this?

Well, at least it is true that its fuel/thrust ratio is too efficient. You don't need to fire it all the time either.

**Comment by dukc** [comment]
> If you want to retreat then you should have great distance with the star but did your ramscoop gives enough fuel for this?

It does not have to. The fuel tanks will last a for a good time before the ramscoop is needed. With 1000 fuel there's plenty of time to figure out something, often even kill the enemies.

**Comment by Hurleveur** [comment]
> But is it really meaningful to add one if it wasn't powerful that much? And why we need for the fast speed in the first place? 200-300 is already enough for the escorts, and even the flagship is doing well on 250-300. Make it faster doesn't gives you much other than enjoy the space ride - it doesn't do much in combat either.

I was able to beat 2 arfectas at once with one ship using this speed. Now, that is the biggest afterburner but that means the medium one makes you go at normal speed at very little outfit cost

A bit too little if you ask me

**Comment by binaryspica** [comment]
> > If you want to retreat then you should have great distance with the star but did your ramscoop gives enough fuel for this?
> 
> It does not have to. The fuel tanks will last a for a good bit of time before the ramscoop is needed. With 1000 fuel there's plenty of time to figure out something, often even kill the enemies.

With 1000 fuel points as OP, yes. But you did already pay for this, don't you? Also afterburners makes the ship too fast and I don't think that you can stop where you want so easily. You need good turn rate, turn the ship and fire afterburner again. Although the game supports to automatically try to stop the ship, but still I don't think that it is quite easy for you need to fire afterburner to the opposite direction if you want to stop so quickly. Just for run from the enemy you don't need to desperately slows down your ship so fast, though, but if you want more than leave the engage and jump you also needs the manauvering capability, not only speed. 


> > But is it really meaningful to add one if it wasn't powerful that much? And why we need for the fast speed in the first place? 200-300 is already enough for the escorts, and even the flagship is doing well on 250-300. Make it faster doesn't gives you much other than enjoy the space ride - it doesn't do much in combat either.
> 
> I was able to beat 2 arfectas at once with one ship using this speed. Now, that is the biggest afterburner but that means the medium one makes you go at normal speed at very little outfit cost
> 
> A bit too little if you ask me

How did you do that? Their turret is not a beam weapon so you could dodge with great speed but how you can deal any damage? The speed is enough to easily overshoot them.

**Comment by Hurleveur** [comment]
I used 10 skylances on a 618 and I then even capped both xD
I wasnt dodging I was rushing them to gun them down, also I dont think its a beam weapon

**Comment by Zitchas** [comment]
I don't think after burners themselves are too powerful, rather I think the mechanic trust allows them to utterly blow past their normal max speed is the problem. If after burner max speed was capped at, say, 300% of the ship's non-afterburner MSC speed... I think that would solve it. Or even 500%. Even that would require a ship at least have *some* normal propulsion..

**Comment by Hurleveur** [comment]
That would make sense ~~smbd made the game support afterburner only for no reason I guess~~

**Comment by Zitchas** [comment]
Hmm... Maybe give all ships built in thrusters and steering equivalent to about half the strength of the weakest thruster/steering available in their ecosystem. Actually,. Seriously, that would be great for improving fighters, and have minimal impact on bigger ships, and allow for establishing a call this way on "no engine" builds. Call it the atmospheric grav repulsors or something.

**Comment by dukc** [comment]
> I don't think after burners themselves are too powerful, rather I think the mechanic trust allows them to utterly blow past their normal max speed is the problem.

Yes, I think that is the core of the problem. Or maybe it's more that one can coast at that speed with no further fuel usage. If the drag would slow the ship to dry-thrust max speed when the afterburners are turned of, I'd imagine the afterburners would already be clearly less overpowered.

But anyway, you're the developers here so I won't try to overrule what you best see fit.

**Comment by binaryspica** [comment]
> I don't think after burners themselves are too powerful, rather I think the mechanic trust allows them to utterly blow past their normal max speed is the problem. If after burner max speed was capped at, say, 300% of the ship's non-afterburner max speed... I think that would solve it. Or even 500%. Even that would require a ship at least have _some_ normal propulsion..

Agreed. If around 200~300 is a max for a ship but with the afterburner it easily over 1000+ seems something weird.

----------------------------------
Also, even if the afterburner is powerful that much, but is it only meaningful if you don't have an escort and you have to survive and fight by a single ship? Consider the routine of the escorts, even if you dodge every attempt to kill you your escorts are don't follow the same thing and got easily dying out against superior force. 

Not all players are bring a ton of escort, but this is usually stable than only play with a single ship. So, allow some fun to the players without an escort seems not so bad.

**Comment by Zitchas** [comment]
I am inclined to agree there. While I think afterburners should be reigned in a little, I am also good with them being a means of ensuring that solo players have a shot at surviving without a big fleet to back then up. Of course, as the AI is improved, this is likely not work as well in this regard.

**Comment by binaryspica** [comment]
If the AI is improved and they actively dodge the enemy attacks, then the nerf is inevitable I think. Still, if you want to keep the advantage to the players without an escort when it was done, you may give a 'better' outfits with limited quantity instead. Then you can't spread it to the whole escorts.

**Comment by ravenshining** [comment]
I don't think afterburners are terribly over*powered* (apart from the Remnant ones) on a thrust/weight basis, but I think you do have a point about their fuel economy.  To me, I think it's more a matter of *ramscoops* are overpowered.  But, failing a decrease in scooping, an increase in fuel usage wouldn't be amiss.

Not a fan of all these notions of thrust caps and such.  If people want to have only engines that consume fuel, I think that should be a choice we don't discourage.

This especially is working the wrong angle:
> Or maybe it's more that one can coast at that speed with no further fuel usage. If the drag would slow the ship to dry-thrust max speed when the afterburners are turned off

Why should afterburner thrust act different from regular thrust?  That makes no sense.  I really enjoy building up to a speed and then coasting in towards a destination, it makes the game more fun and realistic that way.

**Comment by Zitchas** [comment]
> Why should afterburner speed act different from regular speed? That makes even less sense than the drag does in the first place. I really enjoy building up to a speed and then coasting in towards a destination, it makes the game more fun and realistic.

I fully agree with that.

I rather think the solution is to bring afterburners inside the standard movement limits instead of being outside them. Afterburners should be a faster way to reach max speed, not a magical capacity to vastly exceed max. But for this to be meaningful, we need a vastly larger disparity between max speed and acceleration. Right now, most stick sis can accelerate to their max speed in, what, a second? Two or three? I haven't measured, but I doubt any ship takes more than ten seconds to reach max speed. Reducing acceleration across the board (which the mass rebalance does), in combination with decreasing drag significantly could accomplish this. I'm not sure if it would play well, but it sounds good, and it would allow afterburners a role in helping ships reach their to speeds fast instead of being a magical override. I would envision to speeds two or three times higher than currently, but acceleration low enough to take over a minute to reach that top speed as a starting point, at least for slow ships.

**Comment by Saugia** [comment]
Afterburners have now been nerfed by around 50% through https://github.com/endless-sky/endless-sky/pull/8080, so I'll be closing this issue. If you believe afterburners to still be too strong, feel free to open a new issue discussing the newer stats of them.

**Comment by dukc** [comment]
Sounds about right to me. I'm unlikely to open further issues about this. Thanks.
