### ISSUE TITLE
Boarding Korsmanath A'awojs crashes the game

### ISSUE THREAD

**Issue by DisableGraphics** [endless-sky/endless-sky#7578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When boarding Korsmanath A'awojs, the game freezes for about 2~5 seconds and then crashes. I've not found any issues boarding "smaller" ships, like the Kasichara A'awoj, so maybe the issue lies in somewhere related to crew calculations.

### Steps to Reproduce

1. Go to a Korath Exiles system.
2. Disable a Korsmanath A'awoj.
3. Board it.
4. The game will freeze and crash.

### Expected Behavior

Boarding Korsmanath A'awojs shouldn't crash the game.

### Operating System

Arcolinux (Arch Linux derivative)

### Game Source

GitHub Releases

### Game Version

Latest Continuous

**Comment by warp-core** [comment]
It looks like the variants don't have `uncapturable`.

**Comment by Amazinite** [comment]
> I've not found any issues boarding "smaller" ships

Boarding is very memory intensive at large crew values because of the capture odds calculations, hence why you haven't seen this before.

#5811
