### ISSUE TITLE
Captured ships can get stuck in a system

### ISSUE THREAD

**Issue by marcweil** [endless-sky/endless-sky#758]
I recently ran into a scenario where I boarded a disabled ship and accidentally removed the hyperdrive from it. I then captured the ship, turning it into an escort. The system I was in didn't have an outfitter, which means I can't install the hyperdrive into the new escort ship upon landing. So now I have an escort ship permanently stuck in that system and I can't get rid of it.

Perhaps the solution is to either prevent the plundering of the hyperdrive, or to allow it but then prevent the capture of the ship?

**Comment by endless-sky** [comment]
You can always just destroy the ship, but sooner or later I'll probably also add a button to "fire" escorts...

**Comment by mrec** [comment]
Semi-related to #677

**Comment by lehgogh** [comment]
Or, we could allow the equipping of stored outfits (and vice versa).

**Comment by brendanjones** [comment]
"Or, we could allow the equipping of stored outfits (and vice versa)."
While I do love that idea (I want me a Korath Worldship!), can you imagine how complicated it would be to add a jumpdrive (or even just a hyperdrive) to another ship while both still flying in space?! I'm not sure it's realistic. I mean, imagine if you brought the wrong allen key...
