### ISSUE TITLE
Please Add a Sum of Energy/Heat Usage

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#7584]
### Problem Description

I'm tired of doing the math to figure out if I'm generating enough energy or too much heat. I just want to know if my ship is going to die on me.

### Related Issue Links

I couldn't find anything similiar.

### Desired Solution

I'd like a sum of usage underneath the energy and heat stats on ships.

**Under energy**: Energy generation - Energy usage = Net energy usage (what is going to come out of the batteries when moving and firing).

It would also be nice if it told me how long the batteries would last. Like: max: 2164 (10 sec), but that's not as important.

**Under heat**: Add up all the heat usage and tell me if I'm going to overheat if I'm moving and firing at the same time.

![Screenshot from 2022-11-12 19-37-00](https://user-images.githubusercontent.com/11021683/201502916-7cdf2eca-f899-4450-8b42-5e60619c7607.png)

### Alternative Approaches

No alternate solutions are coming to mind.

**Comment by Hecter94** [comment]
This would indeed be nice to have

**Comment by mOctave** [comment]
I'm also tired of having to do mental math just to figure out if my ship is going to die on me. I'll see if I can find a way to fix this.

**Comment by Hurleveur** [comment]
as I said on the PR:
>This will cause people to make ships generating too much energy and having too much heat capacity even more than now, and mean ppl doing less quick math (which I personaly never had a problem with) so I really dont see the point. However we can improve this a lot:

>Ships don't always have full shield regenerating + hull regen + all shooting + afterburning + cloaking + active cooling + steering + thrusting. So if we do something like this I'd much prefer a new category named "expected" that would display something like this:
since you either thrust or afterburn or steer and generally afterburn no more than this ratio
+ ( ( (thrusting * 4+afterburning) / 5 + steering ) / 2 +
+   (shields * 2 + hull) / 3 + turret shooting (non anti missile) + (gun * 2 + AM) / 3) ) / 1.5
Generally when you shoot you dont move as much and guns dont shoot all the time.
+ active cooling/2 (or how much it is turned on at your average heat)

>Same thing applies for heat and energy. The formula can be tweaked ofc.

Posting it here for discussion

**Comment by mathwhiz1212** [comment]
I'm going to comment on the PR to keep everything in the same place.

**Comment by bene-dictator** [comment]
Closed with #7597.
