### ISSUE TITLE
[Minor] Log message is wrong for Agent Kopkow in Hai Reveal

### ISSUE THREAD

**Issue by animoose** [endless-sky/endless-sky#7592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This statement in Hai reveal 5 is incorrect:
		log `Agent Kopkow` `A Republic Intelligence officer who intercepted your investigation with Giti before involving you with Syndicate Internal Affairs.`
It causes "Agent Kopkow" to appear in the leftmost column of the log panel. It should be preceded by "People" or "Minor people".
 The text wrapping is also wrong, but this is probably a knock-on effect.

### Steps to Reproduce

Play Hai reveal up to chapter 5.
Inspect the logbook.

### Expected Behavior

The log statement should be under People or Minor People.

### Screenshots

![capture_001_13112022_095929](https://user-images.githubusercontent.com/35618085/201537020-23aa00f0-87db-4afb-852b-c31c365345c9.jpg)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

v0.9.17-alpha

### Additional Information

Bigger picture issue: maybe we need a "linter" to catch cases like this.

**Comment by warp-core** [comment]
Fixed by [0a0420f](https://github.com/endless-sky/endless-sky/commit/0a0420fd4555ec947601cc1737f261b01833c375)
