### ISSUE TITLE
Coalition mission "Longcow Antibiotics 1" refers to a nonexistent escort

### ISSUE THREAD

**Issue by damerell** [endless-sky/endless-sky#7595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you land on the destination for "Longcow Antibiotics 1" without picking up the cargo, you are told that you "realize that your escort carrying the longcow antibiotics" is missing. This mission does not involve an escort.

### Steps to Reproduce

Accept this mission from a Coalition system. Fly to "Corral of Meblumen" without first going to "New Finding".

### Expected Behavior

Receive a message which does not presume the existence of an escort.

### Operating System

Windows 7 (yes, I know; no, it isn't)

### Game Source

GitHub Releases

### Game Version

v0.9.14 but AFAICT the issue unchanged now

**Comment by bene-dictator** [comment]
Do you have your own fleet with you?

**Comment by damerell** [comment]
FWIW, I have no fleet to have with me, just a flagship.
