### ISSUE TITLE
Friendly Syndicate Extremists

### ISSUE THREAD

**Issue by natangold** [endless-sky/endless-sky#760]
I'm not sure who it is I keep killing to achieve this (probably buttloads of Syndicate ships because hey, they attacked me first), but each of the three times I've run through the Free Worlds story line, when I get to Buccaneer Bay, the nuke-happy extremists are perfectly friendly towards me, forcing me to fire on them before they'll launch against me, which forces me to save-scum since I get hit at close range by several dozen nukes before I can engage my cloak. Can we add `"reputation: Syndicate (Extremist)" = -1000` to either `mission "FW Syndicate Extremists 1B"` or `event "battle of algenib"`?

**Comment by Bladewood** [comment]
Then we can just kill lots of Republic ships for the lulz, and they will be friendly again.

**Comment by natangold** [comment]
While this is true, once the mission is offered and the event begins, the player isn't *necessarily* at war with anyone at war with the Extremists.

**Comment by endless-sky** [comment]
This should be fixed in commit ca266dd.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
