### ISSUE TITLE
Assigned keys should be saved in user folder

### ISSUE THREAD

**Issue by gendalv** [endless-sky/endless-sky#7601]
### Problem Description

It's annoying to reassign keys on every reinstall.

**Comment by MCOfficer** [comment]
Please use the issue template.

Skimming through the code, it seems like this already supported - all you have to do is move the keys.txt to the config folder (the one containing "saves" and "plugins").
https://github.com/endless-sky/endless-sky/blob/f518ecff9598af745cb50b8ccd5a5d28f7940bfe/source/GameData.cpp#L171-L172

**Comment by quyykk** [comment]
Assigned keys *are* saved in the user folder already. Are you on Steam? I'm not sure if Steam deletes the user folder for games (probably not, but idk).
