### ISSUE TITLE
Casualty Estimates and Reports Are Inaccurate in v0.9.16

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#7607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I go to capture a ship and I have a significant advantage (say 200 attack v. 4-20 defense) I lose a lot more crew than the game estimates. I've lost as many as 17 crew when no more than 1 crew was estimated to be lost.

1. I always lose at least 1 crew no matter what (often more) even if it's 245 crew with grenades v. 1 crew with 0.1 expected casualties. That being the case, why not always estimate at least 1 causality all the time?
2. It seems like I lose approximately the same number of crew as the ship I'm boarding sometimes. Like the game will say "You lost 1 crew, they lost 14 crew." Except I lost 10-12 crew as well. And that's true for each round of combat as well as the total outcome.

It might be too easy to capture ships with a Bactrian if the casualty estimates I'm getting are true, but casualties don't seem to be estimated or reported correctly.

Thanks for making an amazing game! I love the storylines.

### Steps to Reproduce

1. Board a ship where you have something like a 150 v. 15 or 150 v. 50 crew advantage.
2. Observe the casualty estimate.
3. Attempt capture.
4.  Compare the estimated and reported casualties with the actual casualties.

### Expected Behavior

I expected the casualty estimates to be close to what happens. 

If it estimates ten casualties, then twelve is reasonable. But I shouldn't lose a hundred crewers if it estimated I would lose ten. That leaves awkward situations where I thought I could capture a ship but I can't.

I also expected the report of "You lost x crew" to be correct.

### Screenshots

This is an example where I think it estimated around 50 casualties. The reported casualties are 33. But the actual casualties are 245 - 112 = **133**. I lost about a 100 more crewers than estimated or reported.

![Screenshot from 2022-11-12 22-37-08](https://user-images.githubusercontent.com/11021683/201795137-7d9849ef-0d9c-41fd-94e5-d379cf47309c.png)

### Link to save file

This is months later in the game than my taking (and subsequently losing) the Bactrian.
[No Way 2.txt](https://github.com/endless-sky/endless-sky/files/10008016/No.Way.2.txt)

### Operating System

Linux Mint 20 (Based on Ubuntu 20.04) using the 5.4.0-131-generic kernel.

### Game Source

GitHub Releases

### Game Version

v0.9.16

**Comment by vitalchip** [comment]
When you capture a ship you've killed all their crew and so some of your people transfer over to operate it, is that your missing number?

**Comment by mathwhiz1212** [comment]
@vitalchip

Interesting, not quite.

In the example above, it's reporting 100 less than actual causalities and 74 crewers transferred over. So I'm still missing 26.

It would be good to say that "74 crew went over to take control of the ship" for new players like me who might not realize that's what is happening.

**Comment by ThrawnCA** [comment]
Did you definitely have 245 crew when you started the fight? Remember that if you lose some in a fight, you need to hire replacements next time you land.

**Comment by mathwhiz1212** [comment]
@ThrawnCA I had auto-recrew turned on and jumped directly from Hai space to Nihil with no fighitng that I can remember. I can check the save file to be sure.

**Comment by mathwhiz1212** [comment]
@ThrawnCA @vitalchip I think you're both right. I'm putting this down to a noob misunderstanding. Combat seems to work as expected.
