### ISSUE TITLE
Tell The Player Crewers Left Your Ship to Take Possession of a Boarded Ship.

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#7608]
### Problem Description

I figured some crewers transferred to take possession of a ship, but I didn't realize how many. I thought I was losing a lot more crew than I actually was.

I get that the crewers that transferred are mentioned in the "enemy ship" crew count after combat after it was explained to me, but I was confused before then (I started playing a few days ago).

### Related Issue Links

I thought it was a bug until I got more experience with the game: https://github.com/endless-sky/endless-sky/issues/7607#issuecomment-1314609658

### Desired Solution

It would be nice to add a message just after "You have succeeded in capturing the ship" where it tells you something like "50 crewers transferred to the boarded ship to take control of it."

It would make it easier for new players to understand what's going on.

### Alternative Approaches

None come to mind.

**Comment by the2nake** [comment]
Could this be combined with a mechanic to choose how many crew members leave your flagship? I would love to leave just one crew member on the captured ship, especially when I need to capture multiple ships at a time.

**Comment by warp-core** [comment]
[ab5efbf](https://github.com/endless-sky/endless-sky/commit/ab5efbfc28bd1e8f1306e1a022a450d7e952b40e)

**Comment by ThrawnCA** [comment]
Would it also be feasible to give the player an indication in advance of how many crew will be needed to transfer, before they start combat? It's possible to see how many are *currently* on the target ship, but that doesn't tell you the minimum crew requirement, which would be useful to know when deciding whether or not to start hostilities.

(A reminder of the player's own minimum crew requirement would be nice to have, too. Maybe even a projected crew number after combat+transfer, so you can see at a glance whether you'll probably be understaffed.)
