### ISSUE TITLE
Fleet is scattered, but not all ships are shown

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#762]
Whenever my fleet (which happens to be made of 32 shield beetles) is scattered, I only see 13 ships, which I assume is limited by my resolution. That does not make sense, however. If just one of my ships is missing, I should see a ship with the number 31 next to it and another ship, but as I say, I only see part of my fleet.

**Comment by endless-sky** [comment]
Are you talking about the escort icons? Could you post a screenshot or something?

**Comment by endless-sky** [comment]
Never mind, I think I see what you're talking about. See if commit 3455df3 fixes this for you - it allows escort icons for ships in other systems to merge together, as well as icons for ships in the current system.

If your Shield Beetles are in more than 13 different systems, you'll still not see all of them in the list, but getting your ships scattered *that* widely would be rather uncommon.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
