### ISSUE TITLE
Patrol Systems Near Postverta Not Completing

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#7627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Even though I visited the systems that it told me to visit in order to patrol the systems around postverta, for some reason it doesn't seem to be letting me complete the mission.

### Steps to Reproduce

1. Do the mission to patrol systems around Postverta
2. After patrolling the systems, it won't mark the mission as completed.

### Expected Behavior

You won't be able to complete it.

### Screenshots

![Screenshot (186)](https://user-images.githubusercontent.com/70719891/202318765-d5ae0d57-8d71-4ddd-9178-75b81122abb1.png)

### Link to save file

[Red Susatonia.txt](https://github.com/endless-sky/endless-sky/files/10026481/Red.Susatonia.txt)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v0.9.16

### Additional Information

This is a weird save file, that has experienced multiple updates and continuous builds. I wouldn't be surprised if this is just an error because of the save file's age.

**Comment by warp-core** [comment]
There are some ships (three 'olofezes (Korath Chasers)) in one of those systems that you have to kill.

**Comment by McloughlinGuy** [comment]
> There are some ships (three 'olofezes (Korath Chasers)) in one of those systems that you have to kill.

Why is that a requirement? Thats really vague and seemingly unspecified?

**Comment by McloughlinGuy** [comment]
> There are some ships (three 'olofezes (Korath Chasers)) in one of those systems that you have to kill.

I see. Thank you. I missed that while flying through, and I hadn't played in a while so I completely forgot. I think that a text box when you enter the system where the chasers are or a mention to the Palavret in the mission description would help anyone else who is confused by this.
