### ISSUE TITLE
Recoil

### ISSUE THREAD

**Issue by hut** [endless-sky/endless-sky#763]
A little recoil when shooting missiles or blasters would add some realism.

**Comment by lehgogh** [comment]
This would make turrets *really* annoying.

**Comment by Gkramme** [comment]
Yes, and plus this is a giant starship. A turret would not affect it anyways. Also, these weapons would recoil within themselves, like a motar.

**Comment by lehgogh** [comment]
That makes more sense.

**Comment by hut** [comment]
I'm no expert on weapons, but I digged a little into that stuff and it seems to be perfectly feasable to reduce the recoil to unnoticable levels - even when firing heavy missiles. So, nevermind^^

**Comment by endless-sky** [comment]
Also, recoil is already supported by the engine, and several weapons have it (the particle cannon, in particular). But missiles don't have a particularly high mass, and they accelerate under their own power, so recoil doesn't make much sense for them.
