### ISSUE TITLE
Bug: Planet label is off-center when landed on a planet

### ISSUE THREAD

**Issue by Koranir** [endless-sky/endless-sky#7631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When landing on a planet, if "Show planet labels" is enabled, the planet label will be offset. This bug is most noticable on small planets.

### Steps to Reproduce

1. Go to a small planet
2. Land on it
3. Look past the planet landing panel
4. Yo will see the planet label offsetted.

### Expected Behavior

The planet label should be centered on the planet.

### Screenshots

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/101683475/202421742-49d39a69-1913-4035-8e7d-cc8fa361a4e2.png">

### Operating System

Windows 10 Education, version 21H2, build 19044.2130

### Game Source

Built from source

### Game Version

commit SHA d8fff42

### Additional Information

I suspect that the planet label is still using an old position for were it's drawn, and it is not updated for one frame, because the drawn frame is always one behind the current. This bug could be fixed by drawing the game panel once more before the planet panel opens, or forcefully setting the planet label's position to the center.

**Comment by tibetiroka** [comment]
Fixed by #9692.
