### ISSUE TITLE
Remnant tech retrieval mission more clarity needed for the player

### ISSUE THREAD

**Issue by jpretori** [endless-sky/endless-sky#7636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On Vimnial, the player can meet Taely who offers the mission with the name "Remnant Human Tech Retrieval".Taely does list the kinds of technology she is interested in, but that listing never makes it to the missions interface in the map UI.

### Steps to Reproduce

1. Go to Vimnial to get the mission called Remnant Human Tech Retrieval.
2. Go through the dialogue until where she says "We need to know what sort of weapons they will be wielding, how their ships will be protected, and how fast they can travel in deep space"
3. Go to the map view, Mission tab
4. Go to Taely's mission - notice how it only says "bring them examples of advanced technology"
5. Feel confused about which of the 100's of possible outfits they want samples of

### Expected Behavior

List Taely's requirements for the mission "Remnant human tech retrieval" in the map interface.  It can be as simple as just copying part of her dialogue: "We need to know what sort of weapons they will be wielding, how their ships will be protected, and how fast they can travel in deep space"

### Screenshots

![2022-11-17_scrot](https://user-images.githubusercontent.com/16192343/202534629-6e6f2f44-df65-47e3-9534-37cb3c8ee7d6.png)

### Link to save file

[Tavis Khan.txt](https://github.com/endless-sky/endless-sky/files/10034707/Tavis.Khan.txt)

### Operating System

Arch Linux

### Game Source

Other (please describe)

### Game Version

0.9.16.1 as per Arch repo's

**Comment by Zireael07** [comment]
Seconding @jpretori and actually looks like a use case for outfit tags or something similar...

**Comment by jpretori** [comment]
> all tech unlocked in FW, pretty muc

Maybe the problem is that I got this mission without starting the freedom worlds campaign.  I stuffed up something in the initial dialogues and never got started on the campaign.  Kept playing, hoping there was something I could do to recover.  Eventually started doing Remnant missions and ended up in this situation.

**Comment by Hurleveur** [comment]
Wait I just looked at it and I'm confused. I assume these were FW since you didnt manage to do it, but here is the list:
You can bring them heavy lasers actually, or plasma cannons, a catalytic ramscoop, or the biggest shield regenerator.

**Comment by Hurleveur** [comment]
Honestly, the way to address this is simple:
-have the remnants hint that laser weapons would be of interest to them (because they heard that humans somehow have some)
-have the missions take more diverse kinds of outfits, namely atomics, turret versions and the typhoon

**Comment by Zitchas** [comment]
There are currently *six* potential outfits. And yes, there is intended to be more. I have been waiting for the mechanics to catch up so that, for example, the laser option would accept either heavy or regular laser canon, and trigger on the turrets too (but only ask for the guns to be delivered)

The current set are intended to cover a range of what the player is likely to already have in their ship, and will be expanded.

From the mission, here are the six current options: Heavy Laser, Catalytic Ramscoop, Plasma Cannon, Electron Beam, D94-YV Shield Generator, S-970 Regenerator.

**Comment by cryo-es** [comment]
Just chiming in - I came across this mission today and found it quite confusing. Having not done the FW campaign yet, I thought that with all Taely said about ramscoops I should bring her some of those for sure, but I hadn't discovered the catalytic ramscoop yet. I was also pretty sure I should take her the best shield, and then maybe a particle cannon or proton gun, because those are the best human weapons available to me. I think the ramscoop part should be changed at the minimum, to not assume that the player has completed the FW campaign, and yeah it should 100% accept turret versions because in general those tend to be more powerful than the gun versions, and she asked for the best technology.

**Comment by Hurleveur** [comment]
The catalytic ramscoop is available from the start, in republic space

**Comment by jpretori** [comment]
> The catalytic ramscoop is available from the start, in republic space

If the wiki article (https://endless-sky.fandom.com/wiki/Catalytic_Ramscoop) is correct, this is not true.

I've been to many of those systems, the catalytic ramscoop isn't available there.

**Comment by Hurleveur** [comment]
Oh yeah its not nvm its just weird mission wise then because it seemed to assume it was available for some time

**Comment by Zitchas** [comment]
It is a tad confusing: Catalytic Ramscoops *are* available from the Deep without being explicitly mentioned in the FW story, but they only appear there after being triggered by an event in the FW story. 

So they appear in the Deep silently, and then there's FW missions to get info on how to make them, and then they are basically announced and appearing in the Delta V Advanced outfitter list, so they appear in many more places after that. So if someone doesn't pay much attention and/or doesn't really visit the Deep, it is entirely possible that during this mission is the first time they really pay attention to the Deep outfitter, in which case it will appear like the Deep has always had them.

(Catalytic Ramscoops also show up on 11 ship variants and 1 person ship. So if the player gets their hands on any of those, they may be able to get them outside of the story. I haven't checked to see where those ships show up, so maybe, maybe not.)

**Comment by jpretori** [comment]
@Zitchas I don't think it gets said enough: you and the others working on ES have done (and are doing!) a fantastic job.  Most open source games compare poorly in their genre.

I can't put ES down. The story and depth and how the mechanics work are just fantastic.

Thank you.

**Comment by Zitchas** [comment]
It is a minor addition; but would you care to take a look at it and see if it is enough to point you in the right direction?

**Comment by jpretori** [comment]
Sorry it took so long!  Looks like a very useful tweak, thanks.  I added a bit more detail in the PR conversation thread.  Basically, is it possible to prevent the mission from appearing if catalytic ramscoops don't exist yet?  E.g. I was able to get the mission before starting the FW campaign, meaning I couldn't get the required ramscoop.  Or maybe I'm misreading the mission definition (not 100% sure I understand the syntax); and just showing up with a heavy laser will trigger mission success.

**Comment by Hurleveur** [comment]
You dont need the ramscoop, a heavy laser is enough to succeed the mission, and proceed to the next ones although you can still bring a ramscoop later on

**Comment by Zitchas** [comment]
As Hurleveur said, you don't *need* all the outfits, only one. It's basically a multiple choice requirement: To complete the mission the player must have completed any one of the listed missions:
- the heavy laser retrieval
- the catalytic ramscoop retrieval
- etc.

You *can* complete all of them, but you only *need* to complete one.

Worth noting that the catalytic ramscoop is easily accessible in the FW campaign, and presumably will be in the Republic/Navy campaign too; but will probably be hard to access in the Syndicate campaign. Conversely, one of those shields is quite hard to access in the FW campaign, but would probably be significantly easier to access in the Syndicate campaign. Other outfits are fairly easy to access in general outside any of the campaigns.
