### ISSUE TITLE
It's possible to park disabled escorts

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#765]
They end up in a kind of zombie state - show as Parked, but aren't repaired/recharged.

If you then unpark them the results are inconsistent - sometimes they reappear (still disabled) when you take off, sometimes they don't. This may be related to the same randomizer (?) that determines whether disabled escorts get permanently garbage-collected or not.

**Comment by endless-sky** [comment]
This should be fixed in commit 011244a.

**Comment by mrec** [comment]
Looks good.

For parking (but not unparking!) you might also want to check that ships being parked are in the same system as the player, otherwise I can't see anything to stop them being parked in systems with no landable planets.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
