### ISSUE TITLE
CI/CD: Test names are too long

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#7653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The quick overview of test-results on PRs don't show the timing information on tests if the test-name is longer than a certain amount of characters, an example:
![tests_longnamed](https://user-images.githubusercontent.com/35403542/202870327-28c1249e-d503-4da3-93e0-c920c60bd5a5.png)

This is normally not an issue, but one of the ubuntu integration tests was taking 28 minutes, while other ubuntu integration tests (even on the same ubuntu version) took 5 minutes to finish. Being able to quicky see in the overview of a few PRs if this is structural would be valuable.

### Steps to Reproduce

1. Create a PR
2. Wait for all CI-tests to finish
3. Click on the quick overview and notice that for some tests the duration cannot be seen.

### Expected Behavior

Shorter test-names with less duplication in them. 
We don't need to mention both windows and win64 in a test-name, similar for ubuntu tests.
And we might want to abbreviate "integration" to "int".

### Screenshots

See description.

### Link to save file

N/A

### Operating System

GitHub runners online

### Game Source

Other (please describe)

### Game Version

Latest master on GitHub (https://github.com/endless-sky/endless-sky/commit/71c870c70dfa386d5f76d41291d333173ca54799)

### Additional Information

The test taking 28 minutes while related tests take 5 minutes could also be an issue (if it is structural over PRs).

**Comment by quyykk** [comment]
The CI jobs now have better names, #7857. They're a bit shorter as well.

**Comment by quyykk** [comment]
@petervdmeer With the switch to cmake for CI the names should be a lot shorter now

**Comment by quyykk** [comment]
Additionally, GitHub now provides an interface to see the usage times at a glance

![image](https://user-images.githubusercontent.com/85879619/213888877-91e633f0-a094-4ebb-9adc-9d752eb9fbcd.png)
