### ISSUE TITLE
Get "on visit" message for Hai Reveal [B02] Join the Fleet when all marauders are dead and all "npc accompany" fleets are alive.

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#7662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hai Reveal [B02] Join the Fleet is sporadically unplayable. I don't get "on fail" message, but I do get "on visit." All NPC accompany fleets are still alive, and all marauders are dead. 

**EDIT**: *With the merge of #7866, this should be fixed. To fix a broken save, depart the planet, repair the disabled fighters, and land again. I'm leaving this PR open a little longer to see if people find the mission breaking in new ways.*

### Steps to Reproduce

1. Play mission "Hai Reveal [B02] Join the Fleet"
2. Kill all the marauders
3. Land.
4. "on visit" message appears since mission is not completed, but no "on fail" message

### Expected Behavior

Mission completes when all objectives are met:

1. Marauders are defeated
2. At least one ship from each "npc accompany" fleet survives
3. Visited the waypoint.
4. Deadline is not reached

### Link to save file

Times it did happen:
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048461/Friction.Diction.txt)
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048847/Friction.Diction.txt)
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048855/Friction.Diction.txt) - all NPC escorts survived
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048870/Friction.Diction.txt)

Times it did not happen:
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048848/Friction.Diction.txt)
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048851/Friction.Diction.txt)
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048869/Friction.Diction.txt) - all NPC escorts survived
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048871/Friction.Diction.txt)
- [Friction Diction.txt](https://github.com/endless-sky/endless-sky/files/10048872/Friction.Diction.txt)

These are save files just before the mission begins. Visit the spaceport to start the mission
- [Friction Diction~3026-02-20 TRY10 part 5 begin with armada.txt](https://github.com/endless-sky/endless-sky/files/10048874/Friction.Diction.3026-02-20.TRY10.part.5.begin.with.armada.txt)
- [Friction Diction~3026-02-19 TRY10 part 5 begin.txt](https://github.com/endless-sky/endless-sky/files/10048875/Friction.Diction.3026-02-19.TRY10.part.5.begin.txt)

### Operating System

```
Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Game Source

Built from source

### Game Version

a82899f0

### Additional Information

- This doesn't happen 100% of the time. See the save files for examples.  I'd guess it's about 50% of the time.
- Sometimes (but not always) landing again after the "on visit" message will cause the mission to succeed.
- In one of my tests, this happened even though no NPC escort ships died.
- Removing "accompany" from the "npc accompany" fleets does not solve the problem.
- Waiting for all escorts to reach the waypoint does not solve the problem.
- I have not checked all saves, but in at least one, the Marauder ships are still alive, despite negative hitpoints

**Comment by Hurleveur** [comment]
I tried multiple times it seems to always work if you just wait a bit for all of them to explode.
Changing it to disable the marauders as an objective and making them target should fix this.

**Comment by UnorderedSigh** [comment]
I played this seven times, and it worked each time. Whatever was wrong, isn't wrong anymore.

**Comment by UnorderedSigh** [comment]
When I switch to "disable" or merge the marauders into one npc, the mission will sporadically fail.

Also, "target" doesn't seem to 100% work with these npcs. They don't blink on the radar, but they do have four blinking arrows when I select them.

**Comment by Hurleveur** [comment]
Maybe it is because of the sheer amount of npcs, can't think of anything else. Or your build has some issue.

**Comment by Hurleveur** [comment]
I tried it whilst changing it to disable it indeed bugs out this is really weird, once its bugged and you land it'll never fix itself for me
But waiting a bit more time before landing often makes the mission work... really puzzling

**Comment by UnorderedSigh** [comment]
I have a fix for at least one way this can fail, in #7845

**Comment by UnorderedSigh** [comment]
I'm about 99% certain the mission will still fail if you land while something other than a fighter is disabled in an NPC "accompany" fleet. The problem can only be completely corrected if HasSucceeded calls ship->IsDisabled() instead of checking the "DISABLED" event.

What confuses me is this comment:

```
// The success status calculation can only be based on recorded
// events (and the current system).
```

That sounds like nonsense to me. I can't see any way `ship->IsDisabled()` would break.

Why can't we do this?

```
isImmobile = (it->second & ShipEvent::DISABLE) && ship->IsDisabled();
```

instead of this:
```
isImmobile = (it->second & ShipEvent::DISABLE);
```

??

**Comment by UnorderedSigh** [comment]
Sorry to answer my question, but the reason you have to use the `DISABLED` event is that, if the ship is able to land in the system, it'll stop being disabled when you land.

The complete fix, then, is to clear the `DISABLED` event if the ship ceases to be disabled.

**Comment by UnorderedSigh** [comment]
EDIT: The deeper I dig, the weirder it gets. It seems that, when a ship is assisted, the `DISABLED` event is cleared by the ASSIST event, but not if a ship docks and is repaired. The player cannot dock a disabled ship, so it is not possible to trigger the "DISABLED fighter" bug yourself. You have to wait for an npc fleet to do it for you.

**Comment by UnorderedSigh** [comment]
I've opened an issue just for the disabled fighters problem, since I cannot be certain that fixing that will fix all situations where the Stormhold battle can fail. #7862

**Comment by UnorderedSigh** [comment]
With the merge of #7866, this should be fixed. To fix a broken save, depart the planet, repair the disabled fighters, and land again.

I'm leaving this PR open a little longer to see if people find the mission breaking in new ways.

**Comment by ziproot** [comment]
Should this still be open?

**Comment by UnorderedSigh** [comment]
> Should this still be open?

I haven't heard any complaints. Thank you for reminding me of the issue.
