### ISSUE TITLE
Don't offer Earth Day jobs while Republic is hostile

### ISSUE THREAD

**Issue by SirTechSpec** [endless-sky/endless-sky#7663]
### Problem Description

When you're at war with the Republic during the FW storyline (and they are currently hostile, i.e. not one of the cease-fire or "safe passage" days), you will not be offered routine (randomly generated) jobs to Republic space, even if on a Republic planet - cargo/transport jobs will be for FW- or Syndicate-controlled destinations. This is appropriate. 

However, the "Earth Day" jobs introduced in #3220 (as far as I can tell) appear to be exempt from this restriction, and I don't think they should be. 

### Related Issue Links

I have not found any relevant issues mentioning "earth day". 

### Desired Solution

Whatever prevents routine human jobs from having hostile Republic destinations (I don't know the actual mechanism) should be extended to cover Earth Day.

### Alternative Approaches

Earth Day jobs could have a `to offer` clause added requiring that the player not be in the middle of the FW storyline, similar to the Deep missions (but not identical b/c those also exclude players taking the Navy's side, which wouldn't be appropriate here.) This would mean they also wouldn't come up during a "safe" period that was about to expire.

**Comment by mOctave** [comment]
It might be reasonable to just have:
```
to offer
    not
       "reputation: Republic" < 0
```
For these jobs, and similar ones as well.

**Comment by ThrawnCA** [comment]
> It might be reasonable to just have:
> 
> ```
> to offer
>     not
>        "reputation: Republic" < 0
> ```
> 
> For these jobs, and similar ones as well.

The complication with that is that if you put Republic worlds to tribute and regain access to them that way, then you can once again get missions there, which seems appropriate. Putting in a reputation check would remove that.

**Comment by ziproot** [comment]
How about instead of `destination "Earth"` it says:
```
destination
    planet "Earth"
```
