### ISSUE TITLE
Question:Best trade route with 1000 tons of cargo space?

### ISSUE THREAD

**Issue by bchis17** [endless-sky/endless-sky#767]
Ok,so I've been playing and upgraded to two bacterians now I have 1000 cargo space does anyone know a good trade that route pays nearly a million credit's any infested pirate routes are fine my bacterians can handle themselves.

**Comment by natangold** [comment]
Check the [forum](https://groups.google.com/forum/#!forum/endless-sky). This isn't the right place for this type of question.
