### ISSUE TITLE
Remnant questline "quantum keystone" not starting

### ISSUE THREAD

**Issue by spd91** [endless-sky/endless-sky#7674]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Found nothing matching this issue while searching : After a while in remnant space and multiple questlines done, the mission chain about providing quantum keystones will not start.

I have no quantum keystone in my inventory BUT have the Shield Beetle Pendant (awarded at the end end of Nanachi's mission chain). Despite it having the effets of a keystone, it does not trigger the mission. Any other ship in my fleet is equiped with keystones. If I swap my main ship for any of it, the quest starts indeed.

Also, it seems that I also qualify for another way in (`mission "Remnant: Key Stones (Hai)"`), since it requires exactly 0 qk but does it count only on the main ship or for the entire fleet ? (in this case, as all other ships are equiped, works as intended)

### Steps to Reproduce

1. Make sure to have no quantum keystone, but the Shield Beetle Pendant.
2. Do the qualifying mission for this quest (defense, void sprites, etc...)
3. Quest will not start
4. Equip a qk instead of the pendant
5. Quest will start

### Expected Behavior

Should this mission start with the pendant ? Or is it intended not to ?
Also, does the `require "Quantum Keystone" 0` apply only to main ship ?

### Operating System

Window 10

### Game Source

Steam

### Game Version

v0.9.16.1

**Comment by Hurleveur** [comment]
Yes it only applies on the main ship, but now we can easily check for it being on any ship if we want to.
Also I dont think the pendant should start any of those missions although having them on your escorts probably should.

**Comment by Zitchas** [comment]
Would you happen to have a pilot file available for this? The PR should fix it, but it would be good to test with the pilot file that was running into the problem.

**Comment by spd91** [comment]
I do. 
[Melina Makalania - Copie.txt](https://github.com/endless-sky/endless-sky/files/10096739/Melina.Makalania.-.Copie.txt)

So now, the pendant will trade it's qk effet for a maneuvrability buff right ? Good.
Like @Hurleveur mentionned in the PR, won't this change trigger the "Lost in then EW" mission even if the rest of the fleet can actually jump or slip through the wormhole ? (`require` vs `outfit:` if I understand right ? If so, same may happen with the coalition or the wanderers, tough, I didn't find a mission like this in the files for this last one)

Thanks for the fix !
