### ISSUE TITLE
Typo: FW pirates 3.1 , FW pirates 3.2 , FW alphas 1.2A

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#769]
There are mentions of 'a diplomacy' in 3.1 and 'a diplomacy government' in 3.2. I think you meant 'a democracy' and 'a democratic government' . I found these by chance so it may be worth checking for other typos.

**Comment by jafdy** [comment]
Also FW alphas 1.2A the Poisonwood governor is female so should be 'unable to conceal **her** anger' not 'his anger' .

**Comment by endless-sky** [comment]
Fixed in dc2b581. Thanks!

**Comment by jafdy** [comment]
Anytime.
