### ISSUE TITLE
Remnant Void Sprite missions can have dialogue referring to information the player missed

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#7696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Remnant: Void Sprites 3" mission includes dialogue where the player refers to having been told that any Remnant ship near the void sprites gets attacked.

However, if the player accepted "Remnant: Void Sprites 1" without asking more questions, then they were not, in fact, told that. The only information about it that can't be skipped is "Certain mistakes were made, certain underestimations, and we can no longer safely approach these organisms." Perhaps the message could be adjusted to reflect that more generic information?

### Steps to Reproduce

1. Accept "Remnant: Void Sprites 1" by selecting "Yes, I'd be glad to." without asking more questions.
2. Complete the mission and also complete "Remnant: Void Sprites 2"
3. The "Didn't you say before that anyone entering that system in a Remnant ship gets attacked?" dialogue option is visible, but the player was never told that specific information before.

### Expected Behavior

Either the dialogue option about Remnant ships being attacked should not be visible when that dialogue tree was skipped in mission 1, or it should be a more generic "Didn't you say it's unsafe?" question (although that would be odd when the player has already approached the sprites and even launched a scanning beam at them), or the information about Remnant ships being specifically attacked should be provided regardless of the player's dialogue choices.

### Operating System

Ubuntu Linux 22.04

### Game Source

Other (please describe)

### Game Version

Commit 80c414ea095c485518474c9ceb6b3777be7f0fda

### Additional Information

Encountered in 0.9.8, verified in code review of latest master.

**Comment by ThrawnCA** [comment]
Also, the "Remnant: Logistics 1" success dialogue, referring to the player carrying a generator, can be confusing if they didn't closely examine the cargo beforehand (since all they were told previously was that it's 39 tons of cargo). When I first saw that line, I wondered if I'd skipped or forgotten a mission.

**Comment by warp-core** [comment]
849653f
