### ISSUE TITLE
Why the audio manual engine?

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#77]
Why you create your own manual audio engine? I mean using low level OpenAL functions directly...

It is hard to get that right (example: fire a laser, and spin your ship, you will notice that it change the side that it is playing in a very obvious and harsh manner).

Also make maybe harder to add some nice libraries (for example to play non-waveform music files, with the proper libraries you can have many hours of music without balooning the size of the download, also some of the best music artists like working on those formats and may even agree to make original music for free).

**Comment by endless-sky** [comment]
If the game gets to the point where someone wants to write music for it,
I'll certainly use a library for reading compressed audio.

In the meantime, most of what the Audio class does (looking up sounds by
name, tracking looping sounds, coalescing multiple instances of the same
sound that start at the same time) is probably not something a library
would cover (SDL_mixer certainly doesn't). So, using a higher-level library
would only save about 20-40% of the effort of writing that one class.

And, you've seen for yourself how hard it is to track down compatible
libraries to link against, especially on Windows. Multiply that by 3
operating systems and possibly also multiple architectures and compiler
ABIs, and if that effort takes longer than implementing that 20-40% of the
class (which only took a few hours), it's not worth it.
