### ISSUE TITLE
Remnant research expedition can choose Devil-Hide before it's revealed

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#7702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Remnant research job asked me to scan Devil-Hide but the system hasn't been exposed on the map so there is not access. This pilot is currently pre-FW.

![Screenshot_2022-11-24_19-30-21](https://user-images.githubusercontent.com/70952724/203854950-96223085-1ff4-4021-a443-fb8ec4ec6488.png)
![Screenshot_2022-11-24_19-33-09](https://user-images.githubusercontent.com/70952724/203854963-d732f865-46a3-4f89-b328-21c6f880fdc4.png)

### Steps to Reproduce

These are selected at random so are difficult to reproduce. 

### Expected Behavior

Only systems accessible on the map should be selected for these jobs. This is a spoiler of sorts, though it gives no actual information other than the system name.

### Operating System

Linux EmberWastrel-8088i 6.0.8-1-MANJARO

### Game Source

ESLauncher2

### Game Version

Recent continuous

**Comment by Zitchas** [comment]
The jobs check for specific attributes identifying systems that are not accessible before missions. It appears these missions were not given this attribute.

**Comment by warp-core** [comment]
Your job probably shouldn't put a burden on everyone else to ensure that all their systems conform to this.
You should instead pick a system in each region of connected systems and have the LocationFilter select a system `near` that one, to guarantee that, as long as your "anchor" systems are accessible, so is the target.

**Comment by Amazinite** [comment]
#5395/#5415

**Comment by Zitchas** [comment]
The jobs in question are intentionally set up to be able to go *anywhere* that a player could conceivably be able to reach using a JD. I anticipate that the vast majority of systems added to the game fit into this category. 

While I haven't done the missions in question here, if they are truly and utterly inaccessible to anyone with a HD+keystone+JD combo, then they should have the appropriate tag to label them as inaccessible. Otherwise, they are fair game for the Remnant job.

**Comment by warp-core** [comment]
> edit: Also, the location filter you describe to effectively encompass every accessible system in the galaxy would be... Rather large, and suffer from the same updating requirements. Either the job needs to be updated everytime more systems are added that are accessible (probably going to be fairly common), or the systems need to include that tag when they are *not* accessible (probably the more rare situation, since hidden and suddenly appearing systems should probably not be a common thing.

I'm not afraid of a big LocationFilter.

Needing to update a single LocationFilter is a little different to needing to add an attribute to a bunch of systems, and then also set up an event to remove that attribute, and potentially re-add it later.
Putting the burden on this job to account for other systems also means the updating is in a single place. And, not updating the LocationFilter isn't really an issue, it just means the job won't have the possibility to go everywhere you want it to.

Expecting *everything* else to account for your job is unreasonable. If the features do not exist to do it in a reasonable way that you also consider acceptable, (for example, I have a PR that would get us some of the way towards being able to expand on the `near` keyword to consider more than just standard hyperlinks) the job should not exist.

**Comment by Zitchas** [comment]
I like the sounds of that PR. Being able to specify something along the lines of "JD near" <source> 100000 and have it pick randomly from anywhere within 100000 JD jumps away would be great. Or even better, if one could simply state "is accessible via JD" and not bother with calculating ranges, simply querying if a ship with a JD could reach it."

**Comment by McloughlinGuy** [comment]
![Screenshot (243)](https://user-images.githubusercontent.com/70719891/208809195-d334636e-3953-4e55-8b42-47be983c60b5.png)
I just encountered this bug, I was gonna make an issue on it but it already exists. It's not specific to just devil hide; it can show up in any hai reveal system, which is a problem.

**Comment by ziproot** [comment]
This is also a problem with the Sheragi system. This is even worse as it can be accessed, but shouldn't be before the mission. Now I can go find the Emerald Sword early. 
![sequence breaker](https://user-images.githubusercontent.com/109186806/215281354-0cec4cc0-e467-4f40-bd63-680cbd97784d.png)
[Sequence Breaker.txt](https://github.com/endless-sky/endless-sky/files/10527854/Sequence.Breaker.txt)

**Comment by Zitchas** [comment]
I'm working on this, but I needed a clean fresh playthrough to actually find all the systems and see how they are revealed (and when). Almost done Hai Reveal, so I should have a fix for this soon.

That being said, despite the Emerald Sword's size, it is still nothing more than a spec of dust compared to the size of a solar system. Not finding it when you don't know where to look or what to look for is, to be honest, expected, and not a plot hole in and of itself. There could be a thousand Emerald Swords tucked behind asteroids or in valleys on the planet, and I'd still not expect someone just casually stopping by the system to find anything.

**Comment by ziproot** [comment]
I am pretty sure those are accessible systems
