### ISSUE TITLE
bugs: middle and checkmate threads

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#771]
middle: you can get the mission to take alondo to bloodsea before danforth is safely escorted to longjump (if you leave danforth behind and land before he arrives in system), dooming him to follow you until he dies or you land at longjump with him in system...

checkmate: if the user visits the Vara Pug spaceport (wanderer space), prepared to accept the mission (on silver) for the final push to earth, mission "FW: Pug 1" activates.

**Comment by jafdy** [comment]
I think you mean New Tibet not Longjump.

**Comment by LocalGod79** [comment]
indeed - my mistake

**Comment by endless-sky** [comment]
I can't find an explanation for that second issue. Are you sure it was the "FW Pug 1" mission?

**Comment by LocalGod79** [comment]
now, looking at the code and dialogue, it might have been FWC: Pug 1 -
apologies.

i had landed on Silver, having cruised through an empty Vegan system.  the
landing dialogue said "...meet us in the spaceport when you're ready", i
departed, went to vara pug, clicked on the spaceport button, and after the
dialogue, was launched into a hopeless battle.

-iaz

**Comment by endless-sky** [comment]
Fixed the first issue in e0f9fc3.

**Comment by endless-sky** [comment]
And, the second issue is fixed in 9b29c95.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
