### ISSUE TITLE
Some Hai spaceport missions don't make sense after Hai Revealed is completed

### ISSUE THREAD

**Issue by bene-dictator** [endless-sky/endless-sky#7713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After completing the Hai Revealed campaign, missions like Arthur and Kiru, and the human wanting to go back to their home planet, which rely on the public not knowing about the Hai, don't make sense anymore. 

There are also problems that happen with Mountaintop; since Mountaintop is governed by the Hai, Hai missions can occur there, and sometimes the dialogue won't make sense. 

It seems like the only mission that has been changed is David Turner's outfitter on Greenwater. 

### Steps to Reproduce

1. Go to Mountaintop after the Hai Revealed campaign
2. Get a mission from the spaceport. 

### Expected Behavior

Depending on whether you've finished Hai Revealed, the dialogue would change. People would notice Kiru is a Hai on Vinci, that guy asking for intelligent squirrels wouldn't sound so off, etc. 

### Operating System

Linux Fedora 36

### Game Source

ESLauncher2

### Game Version

commit 4a33edd697be99848477e39c5f5c1747de15d0d4

**Comment by MasterOfGrey** [comment]
The original PR definitely attempted to account for a set of these but there's also probably some missed, and also a wider set of checks on Hai missions firing on stations and such which I think has been unaddressed for both Mountaintop and the other stations.

**Comment by Amazinite** [comment]
Fixed by #7889.
