### ISSUE TITLE
bug: fine for having illegal outfits given while on Hope

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#775]
Landing on Hope in the Wei system I was given the 1 mil fine for having illegal outfits...by a penguin. Well, I assume it was a penguin, because nobody else lives there.

**Comment by endless-sky** [comment]
Fixed by giving Hope a security level of 0.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
