### ISSUE TITLE
Bug: can't land on Oblivion after getting jump drive

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#776]
I had already talked to the planet but I still can't land. I fixed this by jumping out system and then back in.

**Comment by LocalGod79** [comment]
i've noticed this in 0.8.11 as well - if you get into a fight with a ship of the same government as the system, the planet will turn hostile and demand a bribe (until you jump out and back in, or bribe them again) - i think even mission "clearance" gets overridden at times...

**Comment by endless-sky** [comment]
Fixed in 918e900.

**Comment by jafdy** [comment]
OK thanks. Closing.
