### ISSUE TITLE
[Bug] Duplicate Payment lines in the human jobs.txt

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#7779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The wiki provides no information or description that would imply any kind of benefit to having multiple payment lines within a single section; and I can't find anywhere else in the game that has back-to-back payment sections. Within the jobs.txt file, however, there are 36 instances where there are such back to back payment lines. In every case that I have found the first line is empty, and the second one has a value attached. Furthermore, it is not consistent across jobs, even within a group. Some have two payment lines, some do not. 

The git blame shows a merge a very long time ago where the second payment line was added with a value, but no description that I can see that would imply that this was anything other than a merge that should have overwrote the previous payments instead of adding a new line with it.

As an example, here is the full entry for mission Passengers [0] demonstrating the duplicate payment lines in the `on complete`
```
mission "Passengers [0]"
	name "Passenger transport to <planet>"
	job
	repeat
	description "Bring <fare> to <destination>. Payment is <payment>."
	passengers 1 10 .9
	source
		government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent"
	destination
		distance 2 10
		government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent"
	on visit
		dialog phrase "generic passenger on visit"
	on complete
		payment
		payment 2000
		dialog phrase "generic passenger dropoff payment"
```

### Steps to Reproduce

1. Go to 'jobs.txt'
2. Go to line 1455
3. Look at the on complete section
4. See a blank payment line followed by a payment line with a value.

### Expected Behavior

That there would be a single payment line.

### Operating System

Windows 10 Pro

### Game Source

GitHub Continuous

### Game Version

0.9.17 alpha, up to date with continuous as of Dec 05

**Comment by warp-core** [comment]
From the wiki:

```
payment [<base#> [<multiplier#>]]
This specifies the payment for a mission, which depends on the number of jumps between the source and destination and the amount of cargo and passengers. If the mission has waypoints or stopovers then the number of jumps needed to visit all waypoints and stopovers before reaching the destination is used. The exact formula is used to determine the final payment:

base + multiplier * (jumps + 1) * (10 * (# of passengers) + (tons of cargo))
If no base or multiplier is given, the default is base = 0, multiplier = 150. If a single value is given, it denotes a flat payment (i.e. multiplier = 0).
```

The purpose of the first `payment` is to use the default payment values (0 base, 150 multiplier). The purpose of the second `payment` is to add the flat payment with no distance based amount.

**Comment by warp-core** [comment]
From the wiki:

```
payment [<base#> [<multiplier#>]]
This specifies the payment for a mission, which depends on the number of jumps between the source and destination and the amount of cargo and passengers. If the mission has waypoints or stopovers then the number of jumps needed to visit all waypoints and stopovers before reaching the destination is used. The exact formula is used to determine the final payment:

base + multiplier * (jumps + 1) * (10 * (# of passengers) + (tons of cargo))
If no base or multiplier is given, the default is base = 0, multiplier = 150. If a single value is given, it denotes a flat payment (i.e. multiplier = 0).
```

The purpose of the first `payment` is to use the default payment values (0 base, 150 multiplier). The purpose of the second `payment` is to add the flat payment with no distance based amount.

**Comment by Zitchas** [comment]
Our wiki should probably be changed to indicate that it is acceptable to have multiple payment lines. Most other places having multiple attributes of the same kind results in stacking or overwriting.
