### ISSUE TITLE
Impossible to anger "Neutral" planets no matter what you do.

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#778]
Right now it is impossible to anger them.  You can sit in orbit around Tarazed and kill all the ships in the system (merchants primarily) for as long as you want and they still let you land, which seems strange, since almost nowhere else is like this.

**Comment by masterpierround** [comment]
Unless I'm misunderstanding the files, this fix should be as simple as adding a positive attitude towards Merchant for "Neutral" in governments.txt. This should also be added for the Hai, as I think you can kill merchants in Hai space as well without consequences.

**Comment by jmhorjus** [comment]
Ok, I just realized that Tarazed, Dabih, and Albireo are actually not Neutral until after the player has started the story line - they begin the game as part of the republic.  

So "Neutral" when it's used there means specifically not taking sides between Republic and Free Worlds, not that they are always neutral in all ways by principle or something.  

Yes, giving "Neutral" a positive attitude toward merchants and probably a negative one toward pirates like everyone else in the game would probably be a good addition.

**Comment by jmhorjus** [comment]
I'll make a pull request for this myself since it's such a small issue.

**Comment by jmhorjus** [comment]
Added pull request: https://github.com/endless-sky/endless-sky/pull/783
