### ISSUE TITLE
[bug]Fixing erroneous "1" values in scan speed for Local God and a few misc others

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#7781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I was flying around I noticed that Local God was trying to scan me... and couldn't. Even their regular movement passing back and forth overtop of me when I wasn't really doing anything (just mining, slowly drifting alongside an asteroid).

I checked the data file, and Local God had a scan speed of 1 (for reference, the standard human outfit scanner has a speed of 15)

Upon looking around, found a few other instances of things having a scan speed of 1

### Steps to Reproduce

1. Play the game
2. Discover that Local God can't scan you.

### Expected Behavior

That Local God should be at least as capable of scanning as the average ship with an outfit scanner.

### Operating System

Windows 10 Pro

### Game Source

GitHub Releases

### Game Version

0.9.17 alpha, up to date with continuous as of Dec 05

**Comment by warp-core** [comment]
It seems pretty unnecessary to open an issue for something that you are then immediately going to open a PR to address.

It arguably wastes the time of people following the repo.

**Comment by Zitchas** [comment]
Agreed. But every now and then people seem to prefer to have the formality of it. I can't predict ahead of time when someone is going to go "Why are you creating a fix for something no-one has reported as a bug?" The solution, it seems, is to file an issue wherever possible. 

(I'm not going to do so for typos, but something like this someone could argue, I suppose, that it *might* be intentional to have Local God, Grey, and the Ember Node have a scan speed of 1. So, I'm filing the issue so people can, if so desired, discuss why they aren't a bug.)

**Comment by warp-core** [comment]
> Agreed. But every now and then people seem to prefer to have the formality of it. I can't predict ahead of time when someone is going to go "Why are you creating a fix for something no-one has reported as a bug?" The solution, it seems, is to file an issue wherever possible.

I don't think "I reported it in this issue I opened 10 seconds before this PR," is meaningfully better than "I'm reporting it right now."

> (I'm not going to do so for typos, but something like this someone could argue, I suppose, that it _might_ be intentional to have Local God, Grey, and the Ember Node have a scan speed of 1. So, I'm filing the issue so people can, if so desired, discuss why they aren't a bug.)

I really think opening a PR immediately defeats the point of this: that discussion can just as easily be had on the PR. Creating the issue and PR simultaneously just splits that discussion. And, if you legitimately aren't sure, then I don't know why you'd be opening a PR immediately anyway?

**Comment by Zitchas** [comment]
*sigh* **I** am sure, I just have no way of knowing if anyone else is sure. But if it's generally acceptable to report bugs in the PR they are in, then I'm good with that.
