### ISSUE TITLE
More Dangerous Black Holes (Sag A* +)

### ISSUE THREAD

**Issue by Saugia** [endless-sky/endless-sky#7788]
### Problem Description

I believe the state of black holes in the game currently is too weak. At the moment, we only have Sag A*, which is a beautiful sight, and is easily viewable from a safe distance. However, if you aren't in say, the first 10 obtainable human ships, you can easily get out of the center, or if you are in anything else, it actually takes quite some time for you or anything to die.

### Related Issue Links

Not sure if there are related issues here. 

### Desired Solution

I would like for us to revisit black hole system hazards and either give them stronger hazards, more layered hazards, or some combination of both. There should be a much larger exponential factor when it comes to falling towards the center of one, and we can always leave far enough away from them safe so you can still visit them.

### Alternative Approaches

If we don't want to do a different scope to having more layered system hazards, or even perhaps code edits for more exponential damage (fall-off, exists, doesn't it? maybe more of that?), we can just increase the numbers of the current hazard and use that as a basis (with keeping in mind Sag A* should be *the* strongest by *far*).

### Additional Context

Future black holes in both Gegno space and planned for Builder story should also follow this logic. If anything, these black holes should be as strong as the current Sag A*, and the current Sag A* should be much stronger. Though, of course, I'd like to see the above options, especially exponential increase in hazard dangerousness.

If we're worried that a player would just casually fly in a small ship through the system jumping and it accidentally kills them, then I feel that's sort of the players fault for not navigating around the biggest dang black hole in the galaxy for a safer jump. Space is scary, man.

**Comment by rovermicrover** [comment]
The center could one shot ya, as long as you add a check to not spawn the player in on top of it.

**Comment by Saugia** [comment]
I like the mini-game and think it should be kept, I just think black holes should be more deadly than a Model 64.

**Comment by ravenshining** [comment]
How about both?

Not every black hole need be a supermassive one like Sagittarius A*.  Perhaps we can have a scattering of smaller black holes and neutron stars, which have a similar level of difficulty to escape as Sag A* currently does, and once those are in the game, we can rework the mechanics of Sag A*.

**Comment by vitalchip** [comment]
Not a fan of the black holes.

We don't crash into planets or get burned up when flying across a star so they feel inconsistent.

The Ai doesn't know how to handle them.

Now, in fairness Sag A is well out of the way but I think it's a mistake to have it at all for the reasons above.

I won't be bothered though if more get added, just an observation.

**Comment by Saugia** [comment]
That's fair. Also, yes, two new lesser ones are now in the game from #6610. Seeing Derpy fly through them with a Tempest, they actually seemed okay.
