### ISSUE TITLE
laser and blaster turret angle slightly more vertical than standard.

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#779]
i was just gimping together some new beam/turret outfitter sprites, so i put all the weapons that have turret variants on their own layers, and found that the blaster turret and laser turret angle appears slightly more to vertical than the others.

kinda lost in blender, or i'd have rendered new ones for you already.

**Comment by lehgogh** [comment]
I wish I could use Blender...

**Comment by endless-sky** [comment]
I never really did define a "standard" angle for the turrets, so I basically just positioned each one at whatever angle looked good to me.
