### ISSUE TITLE
Losing captured ships re-disabled while landing is annoying

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#78]
It happened to me a couple times, enough to me write an issue.

Basically, I disabled some ship, boarded, captured, went to land on a planet (usually after finishing the battle) and while the animation of landing is happening, some enemy arrives from outside the system, land a single hit on that ship, and the landing animation ends and the ship is completely gone.

**Comment by endless-sky** [comment]
The basic question is: if you land on a planet when one of your ships (in this system or in another system) is disabled, what should happen to that ship? I see three options:

* The ship gets magically repaired.
* The ship remains in the system, disabled.
* The ship is lost.

The last option is the most "realistic." The first option really doesn't make sense. I'd be open to switching to the second option, I suppose.

**Comment by speeder** [comment]
To me the second option always made more sense.

It is not like ships disappear when you land, even if they are adrift on space, they will stay there adrift.

Of course, if you wanted you could instead make a special case handling (ie: detect when a ship got disabled just before a landing, and land it too, to be lenient on the player, since it probably happened too fast to react).

But from an engineering standpoint adding more edge cases it usually bad idea.

**Comment by endless-sky** [comment]
In the real world, if you left a disabled million-credit starship floating
in pirate-infested space for a day, I'm pretty sure it would indeed
"disappear." :)

**Comment by endless-sky** [comment]
In commit 38b17fd, I've changed it so that disabled escorts and NPCs are no longer lost completely if you land - instead, they just remain floating in space disabled until you take off again. I still think that's a bit unrealistic, but I agree with you that from the player's perspective, it's worth sacrificing some realism for the sake of avoiding the annoyance of losing ships.
