### ISSUE TITLE
Hai Reveal landing missions claim you are in the spaceport.

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#7804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Throughout the "hai reveal 1 intro.txt" there are landing missions that claim to be spaceport missions, even though the player hasn't pressed the spaceport button. Not only do they say they're spaceport missions, but several have you wandering around the spaceport talking to people, which is the sort of thing you'd do to look for spaceport missions. Whatever threshold of writing there is to pass the Spaceport button, these landing missions have definitely passed it.

1. Pug media coverage: "As you walk through the spaceport..."
2. Free Worlds news: "You are relaxing within the spaceport while your ship refuels..."
3. Republic or Syndicate news: "You are relaxing at the spaceport while your ship refuels..."
4. Hai Tour [5] Tour Ends: "After looking around Cloudfire for some time, you stop in the spaceport for a moment..."
5. Hai Leaks Response 1: "A small crowd of Hai gather to peek at you on the short walk from the spaceport..."
6. Hai Leaks Response 2: "On approach to the spaceport on Earth..."
7. Hai Leaks Response 2A: "You look around at the busy spaceport and see the workers haven't even noticed your ship waiting for refueling yet."

A PR for a new mission adds another one of these bugs: https://github.com/endless-sky/endless-sky/issues/7771

### Steps to Reproduce

Play Hai Reveal 1 Intro and see how many "spaceports" you visit without visiting spaceports.

 -or-

Read "hai reveal 1 intro.txt"

### Expected Behavior

I'm not in the spaceport until I enter the spaceport.

### Operating System

`Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### Game Source

Built from source

### Game Version

47c1a3240

**Comment by EjoThims** [comment]
Spaceport is generally also where you land.

**Comment by UnorderedSigh** [comment]
> Spaceport is generally also where you land.

Then what is the "spaceport" button for? I shouldn't get spaceport missions until I enter the spaceport.

**Comment by UnorderedSigh** [comment]
Throughout Endless Sky stories, you are told to "visit the spaceport" after you land, as if you start in a different area than "the spaceport." If I start in the spaceport, how am I avoiding all of these spaceport missions when I don't press the "spaceport" button?
