### ISSUE TITLE
heat shunt isn't changing heat correctly

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#7809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When outfitting this ship, equipping or removing a heat shunt has almost no effect on the heat generation or capacity of the ship.

### Steps to Reproduce

See attached file. Buy and sell a heat shunt and observe the heat stats of the ship. Idle heat only changes by 3.4 and capacity changes by 17.3, if my math is correct.

### Expected Behavior

I'd expect it to be changed by 3240.

### Screenshots

![Screenshot_20221208-123151](https://user-images.githubusercontent.com/692397/206539667-27c7f1e5-2b8d-4b6b-8829-6947ef9563e9.png)
![Screenshot_20221208-123157](https://user-images.githubusercontent.com/692397/206539684-a6133d5e-3f98-474f-afe7-8cb241c7c3a5.png)
![Screenshot_20221208-123212](https://user-images.githubusercontent.com/692397/206539687-026a6186-9088-4d2f-bc58-1ae5568f2cf5.png)

### Link to save file

[Maverick Bleak_exported-20221208.txt](https://github.com/endless-sky/endless-sky/files/10188543/Maverick.Bleak_exported-20221208.txt)

### Operating System

Android 

### Game Source

Other (please describe)

### Game Version

0.9.16.1

### Additional Information

This ship is egregiously min maxed, so maybe it has something to do with mass and outfit space?

**Comment by warp-core** [comment]
Yes, this is the result of the outfits expansions. You have rather a lot of them installed.
The reasoning is to limit the amount of cargo space that can be realistically be converted to outfit space and used for other stuff.
You can find some recent discussion on the topic in #7756.

**Comment by EjoThims** [comment]
It makes more of a difference the more of them you have.

It's a balancing thing, so that cargo capacity isn't freely convertible.

**Comment by vitalchip** [comment]
I've lost count of the number of times this comes up. It's not well understood and no wonder.

Bunks has to be the issue, I think. Boarding is just a money machine already and allowing cargo space to be converted to outfit space to then install bunks without any drawback would make it worse.

Fix boarding is the answer to that one, always has been.

Does anything else matter?  If you want to effectively fill your cargo hold with power/cooling/shield generators then go for it, all you'll have is a well shielded chunker of a ship which isn't really any use for anything except a mobile shield and that seems reasonable.

Remove most of the cargo capacity from warships, they shouldn't really have it anyway, give ships a 'design purpose' and 
if someone wants to strip out all of the weapons and get the cargo capacity back again then fair enough.

**Comment by Zitchas** [comment]
I must admit, I kind of liked EV's distinction: Cargo & Outfit expansions: Permanent, irrevocable, one way transformation into the other thing at something like a 20 to 17 or 18 rate. Cargo pods were removable, but less efficient at 20 to 15. I rather miss cargo pods. They made sense. 

I'm not sure about have warships be 100% outfit space with an appropriate number of cargo expansions. But an appropriate number of cargo pods just makes sense to me. A few pods for storing stuff in tacked on the outside makes more sense than an industrial transformation of the interior. I'd be in favor of doing that for warships.

**Comment by vitalchip** [comment]
I'd leave some cargo space on warships, just that a lot of them have too much as is. Bearing in mind that for the purposes of the game cargo space is what's commercially available to haul goods, we don't count or even mention the cargo space needed for the crew supplies, which there would be but we just assume is included.

So, for a "Hevy Warship" to be flying around with 142 cargo space (looking at you Shield Beetle) as standard while we have freighters with less makes no sense to me.

20 or 30 tons on a warship is plenty, if you want to haul cargo use a cargo ship and *protect* it with a warship.

**Comment by Zitchas** [comment]
That's true, yeah. That being said, I sort of consider the Shield Beetle to be one of the ships in the game conceived along the same lines as the Bactrian - Namely, a ship intended for a solo player who wants to be able to sometimes fight stuff, sometimes run cargo missions, sometimes carry people. And sometimes do them all at once. But yeah, the fact that the SB has more cargo space than most dedicated freighters (not more than any heavy freighter, though) seems a bit much.

**Comment by vitalchip** [comment]
Yes, I think that's where I have a different take. I don't think any ships should be designed for the player but rather they should be designed as ships, in universe.

It's very similar to the Albatross. If I were designing it I'd forget about the cargo bay which would make the ship even more agile (now it doesn't have this cavernous hold and mass of the associated material to create and support it) and now it's even better able to defend the Pelican which has twice it's cargo capacity anyway.

**Comment by vitalchip** [comment]
Cargo pods would make the most sense for a warship. Keeps the spaceframe smaller, lighter aand probably stronger by not having a large empty space inside and a set of doors to be vulnerable on the outside.

I don't think they'd make a great del of difference to performance. but they'd be detachable anyway so if you reaally needed every last bit of agility they'd be gone.

Looking at my current ship, adding 4x 50 ton cargo pods (lets say combined the containeds are a further 50 tons) so 250 extra mass. Acceleration 217 down to 197 and turning 64 down to 59. I'm not sure I would know the difference in a blind test.

That's 250 tons extra tied to a 2,500 ton ship, so 10% cargo/mass.

**Comment by Zitchas** [comment]
2500 is a fairly large ship. The Bactrian only clocks in at a little over 2100, I believe. Well, it's large in Endless Sky's paradigm, anyway. I know it's not really realistic, but we'd probably have to have more mass for the structure, just for balance.

That being said, how does it affect your top speed?

**Comment by warp-core** [comment]
> That being said, how does it affect your top speed?

Max speed is totally independent of mass. Only affected by thrust and drag.

**Comment by Zitchas** [comment]
D'oh. yep.

**Comment by SimulatedKnave** [comment]
And drag is invisible to the player for some reason. 

I literally ran into this same problem today, and it would be nice if there was some way of making it evident what was happening. A "outfit expansions are reducing your heat efficiency to like nothing" warning might be good.
