### ISSUE TITLE
bug(code): Manual selecting of a hyperjump in flight locks in a nav route that has to be cleared in the map.

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#7817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I select a hyperjump by aligning my ship along one of the hyperlanes leaving the system (using the arrows around the minimap), sometimes there are two options close together and I accidentally pick one instead of the other. Realizing this, I break the autopilot sequence, correct my alignment to the other hyperland, and restart the jump. However, this doesn't work, as the initial starting of the hyperjump appears to lock-in or set a hyperjump route to the next system, so nothing short of opening the map and removing that hyperroute will enable me to jump anywhere else but to the initial erroneously selected system.

### Steps to Reproduce

1. Be flying in space.
2. Make sure you have no hyperlanes selected and no route planned in the map.
3. Align your ship with a hyperlane.
4. Hit "jump"
5. Use a movement key to cancel the hyperjump sequence.
6. Align yourself with a different hyperlane.
7. Hit jump.
8. See how you return to jumping out the initially selected hyperlane.

### Expected Behavior

When free-jumping or manually navigating around the galaxy, I expect that canceling a jump and reorienting towards a different hyperlane would result in my new jump using the new orientation, not returning to the old canceled hyperjump.

### Operating System

Windows 10 Pro

### Game Source

Built from source

### Game Version

0.9.17 alpha, up to date with continuous as of Dec 09

### Additional Information

Immediately preferred solution:
1. Manually targeted hyperjumps always hyperjump along the route the ship is aimed at. In other words, manually targeting a hyperjump never locks in a route.

Alternative solution:
2. Provide a shortcut key for clearing the current route, setable in the preferences.
3. Provide a setting to determine whether or not a manually targeted hyperjump locks in a route, or always uses where the ship is pointing.

**Comment by vitalchip** [comment]
I think the best solution to this one is to not push the destination into the player's travel plan when a system is not selected  via the mp (ie jump on the fly)  and then to always run the code selecting the closest link (wrt to ship facing) when the ship is holding a jump command but has an empty travel plan.

Minor changes to Engine::Step() to not push the destination system and to AI::MovePlayer() should be sufficient.

I'm on older code, I doubt this has changed much but the line numbers will certainly be different! A quick search will locate the sections.

Engine: Remove two lines.
<img width="657" alt="Screenshot 2022-12-09 at 17 49 13" src="https://user-images.githubusercontent.com/65342577/206765440-7bfff6fc-54e3-4a45-baa7-bf1690639672.png">
AI: Alter one line.
<img width="683" alt="Screenshot 2022-12-09 at 18 06 17" src="https://user-images.githubusercontent.com/65342577/206765448-ad7cf9fd-3aba-423b-8f8b-b6b8ff927b1f.png">

**Comment by Zitchas** [comment]
So, just add in that `(... || player.TravelPlan().empty()| ) bit? I could try that. It'd be nice to poke at the code again.

Thanks!

**Comment by vitalchip** [comment]
Yeh,add that and comment out the two lines in Engine.

I think probably there's no situation where a TravelPlan could have an entry and the ship would not have a TargetSystem but I was playing it safe and keeping the original check in there.

**Comment by Zitchas** [comment]
Just so I understand the code. The first part in Engine looks like it is checking to see if the player already has a travel plan, and if so, pushes that back as the destination instead of wherever the player is pointing. Am I understanding that correctly?

**Comment by vitalchip** [comment]
The code in AI is what will give the ship a TargetSystem, if the ship does not already have one but has a jump command then it looks at local links (or neighbour systems if you have a jump drive) and selects one. This then gets picked up by the two lines in Engine(Step) and pushed into the TravelPlan.

This is where it goes wrong for you because when you cancel the jump the ship is still holding the TargetSystem and the player has a TravelPlan with the same destinaation.

Removing the two lines in Engine stops the destination going into the TravelPlan but the code in Ai would still block picking of a closer link because of the !ship.GetTargetSystem check (the ship will still be holding this).  So the alternative of TravelPlan().empty() lets the link selecting code run because now the only way the TravelPlan gets filled is via the map.

**Comment by Zitchas** [comment]
@vitalchip I've got a branch with a PR to build it over on my fork

https://github.com/Zitchas/endless-sky/pull/123

I haven't actually been able to test it yet, but hopefully soon.

**Comment by Zitchas** [comment]
Great, it works!

**Comment by Hurleveur** [comment]
We could also have a way to press J twice quickly to change targets without having to align to it
But this seems like a good change regardless

**Comment by vitalchip** [comment]
It won't affect anything entered via the map as MapPanel pushes the destinations back using it's own method. Engine only picks up the singular case of the TrvelPlan currently being empty but the ship has a TargetSystem, the only way I know of that happening is when Ai sets the system based on your ships heading wrt to links/neighbours.

I didn't have a lot of time last night and I couldn't work out why there would be a need to push a single 'on the fly' jump into the travel plan but this morning I've realised that the travel plan is used to set which systems the player has seen, I'm just checking this with a new player..

**Comment by vitalchip** [comment]
Well, it still sets the system as visited when jumping manually, Engine::CalculateStep() calls PlayerInfo::SetSystem and in turn this calls layerInfo::Visit() So I don't see a problem but I'm still left wondering why the parallel paths?

 Why push a destination into the travel plan just so it can be read out and mark the system as visited when it's going to happen anyway when you enter the system..  where's the missing edge case here?
