### ISSUE TITLE
"Buy All" and "Sell All" are not actually opposites of each other

### ISSUE THREAD

**Issue by SimulatedKnave** [endless-sky/endless-sky#7836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Buy All, obviously, buys all of the resource you have selected that you can fit. 

Sell All, meanwhile, sells everything in your damn hold. So it's either sell ALL THE STUFF or sell it one item at a time. This is annoying, inefficient, and means the word 'All' means two different things on the same screen. 

Seriously, this is almost entirely the reason I never bother trading once I'm out of the Shuttle. 

### Steps to Reproduce

Buy two kinds of goods, click "Sell All," wonder why this is a thing. 

### Expected Behavior

Clicking "Sell All" should sell all of the currently selected good (or all goods in hold when no good is selected). 

### Operating System

Windows 10. I promise it doesn't matter in this context.

### Game Source

Steam

### Game Version

0.9.16.1

**Comment by Amazinite** [comment]
> one item at a time

You can hold ctrl, alt, shift, or any combination of those to add multipliers to how many units you're buying or selling.

**Comment by SimulatedKnave** [comment]
This game do love its undocumented keyboard shortcuts...

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/wiki/PlayersManual#keyboard-shortcuts

**Comment by johndh** [comment]
Maybe "sell" should sell all of the selected commodity, "sell all" should remain as it is, and a new "empty flagship" button should do what it says. I've never wanted to sell *some* goods but not all, unless it's to empty just my flagship for looting purposes, so I can't think of any use case for selling 5, 20, 100, etc.

**Comment by SimulatedKnave** [comment]
If "Buy All" were changed to "Buy" that would seem perfectly sensible. 

I just...the world "All" is literally used to mean two different things within an inch of screen space. That's not right.

**Comment by ThrawnCA** [comment]
In what scenario would you want to sell all of only a single cargo type?

The current Sell All functionality is very useful when combining cargo trading with boarding and looting. I always reserve enough cargo space for my flagship to grab the tastiest bits of any pirates/hostiles I meet during the trip, plus there's the possibility of capturing ships with their cargo still on board, so it's common to end up with a scattering of miscellaneous cargo types when I land. Having a Sell All button to liquidate it all is nice and convenient.

About the only time I might want a Sell All Of This Type would be when I've headed out into the unknown with an assortment of whatever was cheap, in hopes that some of it will be profitable next time I land somewhere, and one was profitable while another was not. Even then, though, the loss is usually small enough that it's worth selling it all just to make space for something more profitable on the next run.

**Comment by SimulatedKnave** [comment]
>In what scenario would you want to sell all of only a single cargo type?

Where the price for one is low and a price for another is high? 

I'm not saying the current function is useless. It's extremely convenient. It's just misnamed, and the function that that name would logically belong to (when you compare to Buy All) doesn't exist.

**Comment by Zireael07** [comment]
Agreed, I think it's a matter of naming, not that the current Sell All is bad

**Comment by Zireael07** [comment]
+1 to Sell Cargo (I was actually going to suggest "Sell All (in) Hold", but "Sell Cargo" sounds better

**Comment by vitalchip** [comment]
There should be space on the standard panel to fit in some [all] options. I've got an altered panel and an altered trading system but the idea would be the same.

<img width="761" alt="Screenshot 2022-12-13 at 07 52 20" src="https://user-images.githubusercontent.com/65342577/207257681-180a28b4-3810-4131-819a-cf37ce22cb62.png">

I think though that in most cases the x50,000 modifier would be functionally equivalent to "buy/sell all"  Fleets with more capacity than that must be fairly rare.

**Comment by ThrawnCA** [comment]
My current fleet has about 200k capacity. 200+ Bactrians with 3 enhanced Boxwings each.

The modifier keys are also less convenient on mobile. A one-click or two-click Buy All and Sell All is better.

**Comment by ziproot** [comment]
Can you please explain why you closed this PR as "completed?"
