### ISSUE TITLE
fail to build from source

### ISSUE THREAD

**Issue by alley-oop** [endless-sky/endless-sky#784]
Hi,
I'm triyng to buid endless-sky from git and the process failed with this error:

```
source/ImageBuffer.cpp: In function 'ImageBuffer* {anonymous}::ReadJPG(const string&)':                                              
source/ImageBuffer.cpp:210:27: error: 'JCS_EXT_BGRA' was not declared in this scope                                                  
   cinfo.out_color_space = JCS_EXT_BGRA;                                                                                             
                           ^                                                                                                         
scons: *** [build/ImageBuffer.o] Error 1                                                                                             
scons: building terminated because of errors.
```

**Comment by lehgogh** [comment]
I'm pretty sure this is a question for [the forums](https://groups.google.com/forum/#!forum/endless-sky).

**Comment by jmhorjus** [comment]
If you make a post on the forums, I'll look into it.  I'm not able to build successfully either, but I **can** get all the way to the linker stage - so I can help with compile problems. :)

**Comment by endless-sky** [comment]
As noted in the [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions), you need to use libjpeg-turbo, not plain libjpeg. The reference implementation of libjpeg does not support decoding straight into BGRA format.

**Comment by alley-oop** [comment]
Yeah, my bad.
I've installed libjpeg-turbo-dev and the build is fine now.

Sorry for the noise.

**Comment by lehgogh** [comment]
You should close this if everything's working now.

**Comment by alley-oop** [comment]
Closed.

Thank you for your support.
