### ISSUE TITLE
When out of fuel and cannot land, ships do not move at all

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#786]
I have a fleet. When I jump into a system without a friendly planet, my fleet does not move at all. (until a hostile ship jumps in, or maybe when a friendly ship with spare fuel, haven't checked)
I can still move.
Also, they can move when they get fuel.

**Comment by LocalGod79** [comment]
the a.i. is trying to make it easier for a) the user to identify which ships need fuel, and b) for refueling ships to board and refuel.

**Comment by Bladewood** [comment]
Ramscoop?

**Comment by LocalGod79** [comment]
until they have enough fuel for their next jump, the a.i. appears to sit in a "waiting to refuel" attitude, regardless of their equipment

**Comment by lehgogh** [comment]
This could be partially fixed by setting the AI to start moving when it's out of fuel and has a ramscoop.

**Comment by endless-sky** [comment]
I think this is fixed in 0.9.0. The issue was that they're all waiting around for someone to refuel them.
