### ISSUE TITLE
Request: ctrl+B or +R to cycle through boardable and hostile ships

### ISSUE THREAD

**Issue by HamsterBoo** [endless-sky/endless-sky#787]
Right now R is nearest hostile ship, B is nearest boardable ship, and N is cycle through all ship types. Could we possible get a modifier (shift probably) that would make R and B cycle through that type of ship? There are lots of times when I'm trying to board a big (off screen) ship I just disabled but keep going to fighters and interceptors instead. Can't cycle normally either, since so many ships are flying around.

**Comment by brick96** [comment]
B is board ship, with priority following target, nearest hostile, nearest escort, nearest ship. shift+b is nearest escort

**Comment by HamsterBoo** [comment]
Ah, I didn't realize shift was already used. Ctrl then?

**Comment by Pointedstick** [comment]
Ooh, yes.

**Comment by jafdy** [comment]
You can double click a disabled ship to board it.

**Comment by Bladewood** [comment]
You can also click a ship and press B to board it.

**Comment by warp-core** [comment]
Is merging #6346 (https://github.com/endless-sky/endless-sky/commit/08c13dc710c80835f486e74ef0934cb189fb819d) enough to complete this?
It provides a way to cycle boardable ships, but not hostile ships. Is that part still desired?

**Comment by Amazinite** [comment]
The PR linked above allows you to cycle through boardable ships now. While you can't cycle through hostile ships still, there hasn't been any expressed interest over the years in having a key to do that. If there is still a desire to have a means of cycling through hostile ships with the keyboard, I'd suggest opening a new issue.
