### ISSUE TITLE
Destroy Korath mission in Remnant questline doesn't make sense when the fleet has already been destroyed

### ISSUE THREAD

**Issue by the2nake** [endless-sky/endless-sky#7880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you destroy the Korath fleet at Aescolanus when you arrive, the prefect shouldn't send a fleet out to destroy a fleet that is already destroyed, and when you reach that system, the game shouldn't tell you to find it (you were the one to destroy it, after all).

### Steps to Reproduce

1. Go to the "Search for the Korath" mission
2. Jump to Aescolanus
3. Obliterate the Korath fleet
4. Land on Caelian in the Cinxia system
5. Receive the quest (which shouldn't be given)
6. Jump to Aescolanus
7. Receive the mission text (which makes no sense)

### Expected Behavior

I expected the mission to be skipped after I destroyed the Korath fleet (or to get a quest for sweeping the rest of the systems in Remnant space).

### Operating System

Linux Mint 21

### Game Source

Built from source

### Game Version

v0.9.17 alpha

**Comment by warp-core** [comment]
#5944

**Comment by the2nake** [comment]
Ah, sorry, I didn't know the questline was named Cognizance. I think it's a duplicate.

**Comment by quyykk** [comment]
That is in fact a duplicate, nonetheless thanks for reporting! :smile:
