### ISSUE TITLE
Huygens dialogue inappropriate if you have a jump drive

### ISSUE THREAD

**Issue by damerell** [endless-sky/endless-sky#7883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In "free worlds 1 start.txt": "The correct answer," she says, "was, 'nothing whatsoever; they are entirely different disciplines.' Now, hurry up, I hope to be on Bourne a week from now." You consider explaining to her that it's impossible to get there that fast, but decide against it.`

If I have a jump drive, I know that it is perfectly possible. I might choose not to mention my super alien technology to Huygens, but I might have a slightly different internal monologue.

### Steps to Reproduce

Normal progression of early FW campaign.

### Expected Behavior

I would hope the last sentence of the quoted dialogue was different if I have, or am aware of, jump drives.

### Operating System

Windows 7 (yes, I know; no, it isn't)

### Game Source

GitHub Releases

### Game Version

v0.9.16.1

### Additional Information

I checked the current source tree before reporting to see if this was fixed post-0.9.16.1.

**Comment by McloughlinGuy** [comment]
If you get there on time with a jump drive there is an acknowledgement for it, however it is strange that there isn't an acknowledgement for it when she says to get there in 7 days,

**Comment by damerell** [comment]
On reflection I can see it would be tricky to add a flag everywhere the player comes to know jump drives exist, but interrogating the player's current outfits should be possible.

**Comment by SimulatedKnave** [comment]
Honestly, just throw in "isn't possible with a normal hyperdrive" or "following normal hyperlanes" and it works for either case, IMO. The player certainly should know of the concept of jump drives, wormholes, etc - whether there is or isn't one on the ship, her request is still ridiculous. 

When I played through it I noticed that it's only eight days away, and I think maybe adjusting the number she asks for a little lower so it's clearly unreasonable without the player going and counting the actual jumps might be good.

**Comment by ThrawnCA** [comment]
What if the player's internal monologue called it "unrealistic" or "unreasonable" instead of "impossible"?

Under normal circumstances it's unreasonable because it's an impossible demand, and if the player actually has a jump drive then she's demanding that you use super alien technology to overcome her poor planning, which is unreasonable. So the wording works in either case.

**Comment by lumbar527** [comment]
I made a PR (#8866) to fix this. Can you tell me if the changes make sense?

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/17c70825e403440b553ebef4f1d8f9d36b8bc36c makes some changes to the conversation to make it fit a little better if you have a jump drive.
