### ISSUE TITLE
No warning given if "Add Snapshot" fails

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#789]
Exact steps to trigger will be OS-dependent, but on Windows:

* Add Snapshot
* Enter e.g. `What to do next?` as the snapshot name (`?` is an illegal char for Windows filenames)
* No snapshot is saved, but there's no indication of this except that the list doesn't update. If you already have lots of snapshots and the new one would be offscreen, there's no indication at all.

**Comment by endless-sky** [comment]
This should be fixed by commit be9438d.
