### ISSUE TITLE
Game compiled by me has issues

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#79]
First, activating -O1 onwards (I don't tested plain -O, forgot that one) makes the heap corruption error happen again.

And the game sometimes has some severe slowdowns, once it actually got REALLY, REALLY, REALLY slow to the point of being hilarious, it was so slow that I could sort of become one-man-army because I could manuever the ship better than any AI due to having several frames available to make decisions and act, unfortunately I don't profiled that one (I started profiling later).

Mosts slowndowns happen when there are drones flying around (the biggest slowdown happened when 5 cruisers showed-up at once and released all their drones at the same time), and when shooting lasers.

Maybe not being a coincidence, the profiler pointed that the most CPU time is used by asking the government of ships (also it has a staggering amount of calls!!! much more than any other function, just the stack handling to run this function must be crazy)

Then there are some sleep functions...

Then the drawfont, and the LineShader::Draw functions.

**Comment by endless-sky** [comment]
Well, again that sounds like you may have issues with either your compiler or the C++ libraries. If your computer is anything newer than a Core 2 Duo or so, you shouldn't be seeing slow-downs of that magnitude, even in debug mode.

Unless, of course, you press the secret, undocumented "slow motion" key (caps lock), which I should probably disable by default.

**Comment by speeder** [comment]
I will see if any my musician friends already want to contribute music, if they do, I might figure how to implement the DUMB library on the game (it will ship with the library .c files directly on the project, that library was made that way on purpose).

Its purpose is NOT to run compressed music files (the ogg library does that, and with easier portability than the mp3 libraries available), but to run "music sheet" files (sort of), I made a game using it once, and the game had about 20 music tracks, but the whole download was 6mb, most of it graphics.

**Comment by akien-mga** [comment]
> Its purpose is NOT to run compressed music files (the ogg library does that, and with easier portability than the mp3 libraries available), but to run "music sheet" files (sort of), I made a game using it once, and the game had about 20 music tracks, but the whole download was 6mb, most of it graphics.

Which probably means the tracks were MIDI files, and then players will need a MIDI synthesizer library which can be quite a heavy dependency (hundreds of MB for freesynth IIRC), so I'm not sure it would be a real gain over plain OGG files. I might be mistaken though :)

**Comment by speeder** [comment]
Ooops, commented on the wrong thread. (the music discussion should be on the thread about audio engine).

But no, not MIDI! Hell no.

I am talking about the technology that came from Amiga era, a true music player, lots of indie games use it, but some AAA games also use it (examples:Deus Ex, several of the Unreal series games, almost all console games before the invention of the CD, some late Origin System games, and so many games before the 2000s that writing a list would be too long).

I learned about that file format personally trying to see the music files of the game Clash'n'Slash desktop version (link to it, mind you the flash version has the same music, but I believe converted to mp3, it sounds muddled http://www.miniclip.com/games/clash-n-slash/en/ )

**Comment by endless-sky** [comment]
There are *very* few games that have music good enough that I don't just
turn the game's music off and play my own choice of music in the background
instead. Especially if I disagree with the designer's choice of what genre
of music to pair with the game: does being a space merchant make you think
of orchestral music (Star Wars), folk music (Firefly), jazz music (Cowboy
Bebop), techno, heavy metal, or something completely different? I suspect
individual tastes will vary a lot.
