### ISSUE TITLE
Famous Earth buildings in landscapes

### ISSUE THREAD

**Issue by sfiera** [endless-sky/endless-sky#790]
Of course, whether or not a building is recognizable varies from person to person, but for me, the culprits are:
* [city0.png](https://github.com/endless-sky/endless-sky/blob/0566cf5550d69cc8e361c4892b8672f8f6e562ff/images/land/city0.jpg) (Hong Kong's IFC Two)
* [city8.png](https://github.com/endless-sky/endless-sky/blob/0566cf5550d69cc8e361c4892b8672f8f6e562ff/images/land/city8.jpg) (New York's Empire State Building)
* [city11.png](https://github.com/endless-sky/endless-sky/blob/0566cf5550d69cc8e361c4892b8672f8f6e562ff/images/land/city11.jpg) (also New York's Empire State Building)

I'm happy to contribute photos of my own to replace them. I threw together [a set of my photos that might fit in Endless Sky](https://www.flickr.com/photos/sfiera/sets/72157664024827649); I can crop and adjust colors too. 2x versions should go to the high-dpi project, right?

**Comment by Pointedstick** [comment]
Beautiful! Love the snowy pictures.

**Comment by LocalGod79** [comment]
first off, beautiful photos.

second, i don't know that there *should* be famous or easily recognizable buildings - endless sky is set about a millenium in the future and none of our buildings have been designed to last even close to that long.  that's even ignoring other events that might submerge the bases of many of those buildings in ocean, or destroy entire metropoli during ensuing wars or natural disasters...

**Comment by sfiera** [comment]
Sorry, I wasn't clear in my phrasing. I think that it's a bug to have famous Earth buildings in landscapes. When I land on [New China](https://github.com/endless-sky/endless-sky/blob/0566cf5550d69cc8e361c4892b8672f8f6e562ff/images/land/city12.jpg), I think "this is an interesting urban planet" (good). When I land on [Bourne](https://github.com/endless-sky/endless-sky/blob/0566cf5550d69cc8e361c4892b8672f8f6e562ff/images/land/city8.jpg), I think "…this is a picture of New York City" (bad). Of course, it's possible that Bourne built a replica of the Empire State Building, but it seems odd to pick that replica to represent the planet.

**Comment by Nightmareman** [comment]
I imagine when humans leave earth they will probably build replicas of all sorts of stuff all over the galaxy more then enough space so no reason for us not to do it. Look at it this way U.S government buildings are based off roman architecture so when humans get to space I imagine there will be planets where all the architecture looks like old Roman, Chinese, Japanese, or medieval Europe style for no other reason other then because they can and it looks cool. So would seeing replicas of current monuments and cities really be all that strange?

**Comment by Gkramme** [comment]
I agree with @Nightmareman. People would probably build replicas of buildings for the effect.

**Comment by natangold** [comment]
Las Vegas IRL has replicas of numerous famous buildings; it also has a significantly different skyline than any of the cities from which it has replicated those buildings. Landing on Bourne and seeing a photo of the Empire State Building in a New York skyline has a significantly different impact than landing on Bourne and seeing a photo with the Empire State Building [and the Willis Tower and the Burj Dubai and…] in a skyline 'shopped by merging elements of the Charlotte, Sydney, and Oklahoma City skylines.

**Comment by LocalGod79** [comment]
this is all fair - except that today's available pictures of famous buildings will be undoubtedly be part of famous landscapes, and while it's likely that replicas of buildings/building styles will be built, it is unlikely that we would replicate entire cities...

**Comment by sfiera** [comment]
Right. city8.jpg and city11.jpg look like photos of NYC—because that's what they are.

**Comment by jafdy** [comment]
If nothing else lets add the pictures @sfiera has to the collection. If nothing else we will have less planets with the same pictures.

**Comment by lehgogh** [comment]
In the ES map editor, I'm already seeing that some pictures are used several times, while others haven't been used at all.
