### ISSUE TITLE
Passenger for mission to gas giant doesn't care where their bunk is

### ISSUE THREAD

**Issue by damerell** [endless-sky/endless-sky#7909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Remnant Cognizance 9, I am to land on Esquiline, a gas giant. The only gaslined ship I have access to is the Puffin, which lacks space for a passenger or outfit space for a bunk room. Presumably I could remove the hyperdrive or cut down on engine/energy provision to fit one... or I can bring an escort for the passenger to sit in and deliver their dialogue, oblivious to the fact that I have not actually landed them anywhere.

### Steps to Reproduce

Run Remnant Cognizance 9 with an escort.

### Expected Behavior

The passenger should require that they are actually landed on the planet in question.

### Operating System

Windows 7 (yes, I know; no, it isn't)

### Game Source

GitHub Releases

### Game Version

v0.9.16.1

### Additional Information

I submit also a cheap and dirty fix would be to give the Puffin a bunk space. If that was done I would never have noticed the issue.

**Comment by Zitchas** [comment]
The Puffin *does* have a spare bunk. Only one, though. (total of two bunks onboard. One for you, one for a passenger, or crew member, which is possible as the research lab requires a crew member.

**Comment by damerell** [comment]
Oh no. I must have had one passenger aboard for some _other_ job. My apologies, I think this was raised in error.
