### ISSUE TITLE
Always show hostile hails and have offer bribe bring up the payment option

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#7915]
### Problem Description

Whenever you hail a hostile ship (that you can bribe) it doesn't show their hostile hail text, it just shows how much they want you to pay them. This means that the only way to see their hostile hail is to look in the bottom left corner where it might show up. It seems kind of pointless to have hostile hails if you can barely see them. Also, the option to pay the bribe is called "offer bribe" rather than 
"pay bribe" so it would make sense if "offer bribe" was what brought up the option to pay them rather than it being there by default.

### Related Issue Links

I searched the word "bribe" and looked at the title of every issue that contained that word somewhere. I didn't find anything that this would be a duplicate of or that was that related to.

### Desired Solution

I think it would be a lot better if rather than having a hostile ship just tell you "If you pay me X credits I'll leave you alone" when you first hail them, they would show their hostile hail when you first hail them and the "offer bribe" button would bring up the "pay me X credits to leave you alone" text, then you could have an option to either pay them or refuse, if you paid them it'd display the normal text and if you refused they'd also probably say something.

### Alternative Approaches

You could just change "offer bribe" to "pay bribe" then it'd make more sense since technically they're the ones proposing the bribe.

### Additional Context

Two things:
1. This wouldn't change anything for non-bribeable ships since they say "I do not want your money" when you offer them a bribe, which makes perfect sense and causes no confusion whatsoever.
2. Originally mentioned this on a stream a while back but didn't make this for a while since I didn't want to look for potential duplicates at the time.

**Comment by Hurleveur** [comment]
I was annoyed by this a lot too tbh.
That said I don't think we need an accept/decline for the bribe, just keep it as is and change the offer bribe text to pay bribe, if you want to refuse just close the hail.

**Comment by Hurleveur** [comment]
There also is a bug with the bribes: if you bribe them and ask for help whilst still in the panel they say dont push your luck but if you close the hail and ask again they do it gladly. They should either always or never do it.

Also I think they should not display the friendly hails once they've been bribed but thats smth else entirely.

**Comment by McloughlinGuy** [comment]
> There also is a bug with the bribes: if you bribe them and ask for help whilst still in the panel they say dont push your luck but if you close the hail and ask again they do it gladly. They should either always or never do it.
> 
> Also I think they should not display the friendly hails once they've been bribed but thats smth else entirely.

MZ actually commented this on an old issue saying he wanted to keep it that way. It's weird.

**Comment by Hurleveur** [comment]
I didnt touch that in the PR but we dont have to follow MZ weirdness anymore.
Also I think that bribed hails would make sense?

**Comment by McloughlinGuy** [comment]
> I didnt touch that in the PR but we dont have to follow MZ weirdness anymore. Also I think that bribed hails would make sense?

Yeah those would be nice
