### ISSUE TITLE
"line" coordinates are incorrect

### ISSUE THREAD

**Issue by thewierdnut** [endless-sky/endless-sky#7918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I think that `Interface::LineElement::Draw()` is passing the wrong coordinates to `FillShader::Fill()`.

While trying to add a new interface, I've noticed that in `Interface::LineElement::Draw()` it passes `rect.TopLeft()` to `FillShader::Fill()`, but the shader argument is called "center", and the shader seems written to expect the coordinate to be the center of the rect. 

The consequence of this is that when specifying the corners of lines, They are centered over where you expect the top left corner to be. This messes with my ability to rewrite some of these dialogs as resizable full-screen dialogs for the android port, as I can't correctly anchor line elements to the sides of the screen. My only recourse is to absolutely position the elements by eye, which doesn't fix the problem of variable sized small screens. 

### Steps to Reproduce

In interfaces.txt, I added the following config to the end of the "info panel" section:

```
	visible
	line "test"
		from 0 50 top left
		to 0 60 top right
		color "bright"
```

Bringing up the info panel, I see the line being drawn from the left side to the screen midpoint. 

### Expected Behavior

Specifying the alignment to go from the left side to the right side should draw a line across the whole screen. 

### Screenshots

Current Behavior, line anchored to both left and right side only goes halfway across the screen: 
![image](https://user-images.githubusercontent.com/9004013/208987647-32efd497-9229-4eb7-949c-577b765366b3.png)

Expected behavior, line anchored to left and right side covers the whole screen:
![image](https://user-images.githubusercontent.com/9004013/208987916-e2193ccc-34b6-4472-9ef8-c85200b9a59e.png)

### Operating System

debian bullseye

### Game Source

Built from source

### Game Version

latest master

### Additional Information

The bug itself is trivial to fix. Just change:
```
// Draw this element in the given rectangle.
void Interface::LineElement::Draw(const Rectangle &rect, const Information &info, int state) const
{
	// Avoid crashes for malformed interface elements that are not fully loaded.
	if(!from.Get() && !to.Get())
		return;
	FillShader::Fill(rect.TopLeft(), rect.Dimensions(), *color);
}
``` 

to 

```
// Draw this element in the given rectangle.
void Interface::LineElement::Draw(const Rectangle &rect, const Information &info, int state) const
{
	// Avoid crashes for malformed interface elements that are not fully loaded.
	if(!from.Get() && !to.Get())
		return;
	FillShader::Fill(rect.Center(), rect.Dimensions(), *color);
}
```

However, it appears that many of the line elements in other interfaces appear to be hand-aligned by eye, and fixing the bug messes with the alignment: 

![image](https://user-images.githubusercontent.com/9004013/208988581-241db36b-7299-495e-b01a-0f5eef9b9218.png)

I'm certain that there will be other alignment errors that need to be corrected as well. 

I don't mind fixing these and submitting a merge request, but I do have a few questions: 
1. Is this behavior really a bug, or is it intentional?
2. Is this worth fixing? (This will need a lot of adjustments in interfaces.txt, and I don't know how many plugins overwrite this file)

**Comment by quyykk** [comment]
> Is this behavior really a bug, or is it intentional?

definitely not intentional

> Is this worth fixing? (This will need a lot of adjustments in interfaces.txt, and I don't know how many plugins overwrite this file)

Yes please do! It's actually not that bad because you can simply replace the `from` with `center` in the existing line definitions and it should work. I think there are only like 2 or 3 lines defined in the interfaces.txt, so it shouldn't be that bad. It does technically break backwards compatibility but in this case it's probably fine.
