### ISSUE TITLE
Documentation: How to fix "invalid path" git errors on windows. 

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#793]
On Windows certain files with "~" in the file name may be spontaneously deleted by git with a "error: Invalid Path" message when pulling or merging.
The solution is to set "**git config core.protectNTFS false**".  
Making a note of this in the windows section of the build instructions wiki page would be a good idea.

**Comment by endless-sky** [comment]
Added to the build instructions.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.

**Comment by ccwanggl** [comment]
solve my problem, thanks

**Comment by arnaldoperez** [comment]
Solve my problems, I was migrating a repo from Win7 to Win10 and this was the only thing that worked for me

**Comment by ahmad753** [comment]
Thank you

**Comment by a0x0** [comment]
Four lines of Text, one line of code, solved my problem immediatley. Thank you so much

**Comment by KomalVerma09** [comment]
error: invalid path 'Icon?'
Updating bd7512d..5760200 
please solve this error

**Comment by HiIcy** [comment]
other version may fix it
