### ISSUE TITLE
Request: Option to not report the scanning attempt to your ships.

### ISSUE THREAD

**Issue by binaryspica** [endless-sky/endless-sky#7932]
### Problem Description

We all know that when we enter the system with a patrol fleet with any scanner, the patrols will scan our ships.

The problem is, they keep scans again and again when we have many escorts. Because of this, the report section on the bottom left is usually spammed by 'faction ship x scans your ship' and I can't read anything others.

### Related Issue Links

-

### Desired Solution

So can you add an option to switch it off?

### Alternative Approaches

Else what about to simply remove the scanning attempt from the reports?

**Comment by vitalchip** [comment]
Possibly a quick answer would be to provide a preference to only show important messages.  In the realm of scanning this would mean you wouldn't see all the attempted scans as they're marked not important but you would see any completed scans.

I always founf the messages to be too busy and chopped out all non important messages, don't think I've missed anything.

**Comment by Hurleveur** [comment]
Maybe only show the attempted scans at your flagship or at ships that have illegal cargo?

**Comment by Ferociousfeind** [comment]
Maybe simply only show the first scan attempt and the first scan completion of each government each day, regardless whether it's on your flagship or on an escort. After the first, we get it.

**Comment by warp-core** [comment]
After https://github.com/endless-sky/endless-sky/commit/f4ed6f2300debd9d54bf6a65c470521132199bc8, scan messages for your escorts that aren't carrying something illegal are no longer shown.
