### ISSUE TITLE
Break up the uses of the "radar hostile" color into separate color definitions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#7944]
### Problem Description

As noted in #7869, the "radar hostile" color is used for more than just the radar. From this image, the outline on the selected ship UI, the blips for the targeted hostile ship, and the blips for the targeted hostile planet all use the "radar hostile" color in addition to the radar using it. On top of that, the "radar hostile" color is also used for the blips when you target a restricted planet; it seems weird to me to use the hostile color for a non-hostile entity.
![image](https://user-images.githubusercontent.com/17688683/209620128-890bedc1-9ba7-4cd4-b58a-3788c24610b7.png)

### Related Issue Links

#7869 

### Desired Solution

Split these uses of "radar hostile" out into their own colors:
* "targeted ship hostile"
* "targeted planet hostile"
* "targeted planet restricted"
* "selected ship outline hostile"

Other radar colors may also be used in more than just the radar and should similarly be split up.

### Alternative Approaches

N/A

**Comment by warp-core** [comment]
Should dominated planets have different coloured crosshairs? Or, just the same as friendly?

**Comment by Amazinite** [comment]
I think ideally, almost everything should have its own color definition, because even if two uses might end up having the same values, having separate definitions allows us to change individual UI colors without recompiling.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/751b0ff3d25333257ad3e94b3a4f76a843c00769
