### ISSUE TITLE
You can click on invisible mortgages when you have more than 7 or 8

### ISSUE THREAD

**Issue by allocater2** [endless-sky/endless-sky#795]
The draw-code draws up to 7 or 8 mortgages but the click-code does not care. It interprets any click within the (theoretical) positions beyond the 8th mortgage as click on invisible mortgages. From user perspective you click on empty GUI or the [apply] button and get the mortgage extra pay back popup.

BankPanel::Click(int x, int y) probably needs something like:

```
bool hasSalaries = (player.Salaries() != 0);
int maxVisibleMortgages = 8 - hasSalaries;
int maxY = FIRST_Y + 25 + 20 * min(maxVisibleMortgages, player.Accounts().Mortgages().size());
```

**Comment by jmhorjus** [comment]
Good catch. If you make a pull request I'd be happy to review/test it for you.

**Comment by swifter9748** [comment]
I don't know why you would ever have that many loans taken out, but ok one more big to be fixed.

**Comment by DingusShingleton** [comment]
Every time illegal goods are detected or crew members are killed you get a new mortgage. Once I have a few hundred million in the bank I no longer care about a million credit fine so the mortgages really start piling up

**Comment by swifter9748** [comment]
its easy just dominate all the planets and they wont fine you,( i know its
not easy)

**Comment by jmhorjus** [comment]
This same issue happens with the list of snapshots in the save/load screen if you have a lot of snapshots.

**Comment by db47h** [comment]
PR #850 should fix this.
