### ISSUE TITLE
[bug]When buying Keystones into cargo, can only buy 391 keystones in 40 cargo space.

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#7951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am currently in the Remnant mission where we are supposed to loadup on 50 keystones to bring back to the outfitter. My character is enthusiastic, and decided to fill the cargo hold with them. Kept clicking, and discovered that my ship can hold a lot more than the 40 keystones I was expecting: Instead, it can fit 391. Which I thought was odd. Keystones have a mass of 0.1. So assuming that the game uses outfit mass for cargo space instead of outfit space (which is reasonable), then my ship should be able to fit 400, not 391...

Anyway, so, that's the bug: Where.s the remaining 0.9 space going? My assumption is that the game is rouding down the free space, so the instant I buy that 391st keystone, the remaining space becomes 0, and it doesn't check whether the item I am buying could actually fit in the remaining 0.9 space.

### Steps to Reproduce

1. Go to an outfitter where you can buy keystones
2. Click on Fill up your cargo hold with keystones.
3. See that you can't fill the last .9 space (but the game says is 0)

### Expected Behavior

That in 40 cargo space, I would be able to fit 400 keystones.

### Screenshots

![3024-01-07 Osprey with Keystone Cargo](https://user-images.githubusercontent.com/32169904/209711279-fee7bed3-b595-40d7-91f9-8e96a0283ac4.png)

### Link to save file

[Rebbia Rampart~3024-01-07 Loading up Keystones.txt](https://github.com/endless-sky/endless-sky/files/10310260/Rebbia.Rampart.3024-01-07.Loading.up.Keystones.txt)

### Operating System

Windows 10 Pro

### Game Source

Other (please describe)

### Game Version

0.9.17 alpha, up to date with continuous as of Dec 27

### Additional Information

Parked my Osprey and bought a Scarab, and I can buy 431 keystones on it. (which again, is 0.9 short of cargo space)

**Comment by warp-core** [comment]
This almost certainly is because of the 0.9 value being rounded down (or, probably truncated in a cast from double to integer) so it thinks you have no free space.
