### ISSUE TITLE
Delete users from system

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#796]
# PLEASE DELETE THIS ISSUE

### mistakenly added to endless sky repository instead of my work's

**Comment by jafdy** [comment]
I might just be asking a stupid question here but is this endless sky related at all?

**Comment by brendanjones** [comment]
hahaha omg this is embarrassing. Sorry everyone, didn't even look at which repository I was adding to - all my other tabs open are my work's repository. Good thing it's not company secrets :/

I'd delete this, but don't think I have access privileges, right?

**Comment by lehgogh** [comment]
Click "close issue" down here. |
                                                V
