### ISSUE TITLE
Bug: mission failure condition posted immediately to save file

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#797]
there was a similar problem back in 0.8.1 or 0.8.4, where a player who had been plundered by a hostile would still have their outfits missing when they reloaded from their last save...

**Comment by Gkramme** [comment]
I'm pretty sure you cannot get plundered in the latest update. Are you up to date in your game?

**Comment by LocalGod79** [comment]
yes, currently 0.8.11

please read carefully - i'm having issues with a chain of missions breaking
because a mission failure requirement (killed 'npc save') is saved to the
pilot file before the player lands.

some odd four months ago, in versions prior to 0.8.4, the player *could* be
plundered, which would also be saved to the pilot file before the player
landed - until it was fixed.

i may be new to github, but i've been playing this game, trolling the
google group, and developing content independently for quite a while...
