### ISSUE TITLE
Capturing a Palavret for the Remnant is counted as a fail

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#7975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Remnant: Salvage 4" mission informs the player that capturing a Palavret is unlikely to be possible and they'll settle for disabling and looting it, but it doesn't warn the player that capturing the ship will count as a fail.

### Steps to Reproduce

1. Start "Remnant: Salvage 4"
2. Disable and capture the target Palavret.
3. Mission failed.

### Expected Behavior

The Remnant should ask the player to sell the ship to them for study, just as they would normally ask you to sell any outfits you picked up so they can be studied.

### Operating System

Ubuntu Linux 22.04

### Game Source

GitHub Releases

### Game Version

0.9.16.1

**Comment by Hurleveur** [comment]
We cant ask to sell a ship for study until [the take ship PR is merged](https://github.com/endless-sky/endless-sky/pull/6484)

**Comment by ThrawnCA** [comment]
Okay, then perhaps the mission text, instead of saying "capture isn't feasible", should say "thou shalt not capture"? Which would fit with their goals anyway, because they want to keep the ship for themselves rather than let the player potentially keep it.

Of course, the ship is actually worth much more than the 700k they're offering...

It also wouldn't hurt to clarify in advance that destroying the ship, while not preferred, will not derail the whole Remnant mission chain.

**Comment by Zitchas** [comment]
I'm not sure how much this is a bug as a limitation of our mechanics when the mission was made. Generally speaking, for most people, capturing a Palavret is not typically an option. 

That being said, yes, I can definitely tweak the wording to clarify that capturing it is likewise not desirable.
