### ISSUE TITLE
UniverseObjects should allow implicit 1 for alpha value on root color definitions

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#7978]
### Problem Description

The Color constructor allows for the alpha channel to be implicitly 1. The `color` root object does not.

https://github.com/endless-sky/endless-sky/blob/e5412a088465dab21c75d2ff7c802c9093bfe1aa/source/Color.h#L30-L31

https://github.com/endless-sky/endless-sky/blob/e5412a088465dab21c75d2ff7c802c9093bfe1aa/source/UniverseObjects.cpp#L341-L343

### Related Issue Links

#7967 

### Desired Solution

Check for node size >= 5. Then if node size >= 6, use token value 5, otherwise use a value of 1.

https://github.com/endless-sky/endless-sky/blob/e5412a088465dab21c75d2ff7c802c9093bfe1aa/source/UniverseObjects.cpp#L341-L343

### Alternative Approaches

N/A

### Additional Context

Remove all the alpha values from the colors in governments.txt while you're at it. The previous method of directly defining the color within the government doesn't even support an alpha channel.

https://github.com/endless-sky/endless-sky/blob/e5412a088465dab21c75d2ff7c802c9093bfe1aa/source/Government.cpp#L215-L217

**Comment by warp-core** [comment]
I was about to ask about this myself.

**Comment by warp-core** [comment]
Should we do what you've described or should Color::Load() default the alpha to 1. like the constructor does?
~~Why doesn't Color::Load() take a DataNode like everything else?~~

**Comment by Amazinite** [comment]
~~Make it take the DataNode and go from there.~~

**Comment by warp-core** [comment]
[5542d4f](https://github.com/endless-sky/endless-sky/commit/5542d4f5d03755000ea832874b397e59a9be5b0c)
