### ISSUE TITLE
Bug(UI)-Star is the same color as the hostiles that aren't actually targeting me

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#7979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't tell the difference between the star(s) in a system and the hostile ships that aren't directly targeting me. Likewise, when I have a ship selected, if it doesn't happen to be moving I can't tell the difference between it and either of the previous two objects either.

### Steps to Reproduce

1. Go to any system  that has hostiles
2. Fly away such that they lose focus on you.
3. Select some random ship.
4. See problem

### Expected Behavior

I would expect that stars should have something that clearly identifies them as stars that is unambiguous.
I would expect that hostile ships should be colored/signed such that they are clearly always recognizeable at a glance as being hostile.
I expect that the ship I have selected should stand out from everything else in a way that is unique.

### Screenshots

![3025-02-22 Radar with hostiles - Which yellow dot is not hostile to me](https://user-images.githubusercontent.com/32169904/209978004-646c45af-c742-4cee-bf5a-107dbc13ff9c.png)

So, of all these yellow dots, which one(s) are the ones that will shoot me, and which one(s) are the ones I want to be near in order to boost my solar power (if I had any onboard)?

### Operating System

Windows 10 Pro

### Game Source

Other (please describe)

### Game Version

0.9.17 alpha, up to date with continuous as of Dec 29

**Comment by Amazinite** [comment]
Those are the stars. They're white, not yellow.
![image](https://user-images.githubusercontent.com/17688683/209980438-05a708eb-32c1-4d76-9853-3c63ca9dec40.png)

**Comment by warp-core** [comment]
For reference, the colours are:
Stars use the "radar special" colour: 1. 1. 1.
Hostile ships that are not targeting you use the "radar unfriendly" colour: .8 .8 .4

> which one(s) are the ones I want to be near in order to boost my solar power

Solar energy and ramscooping are based on distance from the system centre, not any particular star. (The stars just tend to be at or near the centre.)

**Comment by vitalchip** [comment]
I think the question got a bit muddled because the first bit was comparing stars to selected ships, which are both white. The second part about the yellow dots is really an issue of size, although they are different colours they're also a little similar at that size.

So maybe stars should be white and selected ships red (or something else we've not used..)

**Comment by Zitchas** [comment]
Well, kind of muddled, but also kind of not: My honest impression is that all three of those things are the same color, and can only see the difference when Amazinite magnified the image. 

Being hollow dots is good. Being supposedly hollow circles that are too small to be able to tell that they are hollow defeats the purpose.

**Comment by Zitchas** [comment]
Question: What else uses the "radar special" color?

**Comment by Hecter94** [comment]
> Solar energy and ramscooping are based on distance from the system centre, not any particular star. (The stars just tend to be at or near the centre.)

Is the system center marked in any way? That could be useful to show on the minimap since it's the most mechanically useful information for solar panels/ramscoops.

**Comment by warp-core** [comment]
> Is the system center marked in any way? That could be useful to show on the minimap since it's the most mechanically useful information for solar panels/ramscoops.

I don't think so, but again, our stars are all either at or very close to the centre.
Any marker for the centre would most likely conflict with the star icon in most cases.
If you are far from the centre, it might perhaps be useful, but I've never had any difficulty finding the direction to go based on the stellar object icons on the radar.

**Comment by vitalchip** [comment]
Question: What else uses the "radar special" color?

Your target ships and asteroids, enemy projectiles, the system pointer on the circumference of the radar display.

I think that's it.

**Comment by Hecter94** [comment]
> If you are far from the centre, it might perhaps be useful, but I've never had any difficulty finding the direction to go based on the stellar object icons on the radar.

Toggleable UI option to put a small arrow on your ship which points towards the system center? Could be useful for when you're far away, or the few systems that have non-standard stars or star layouts. 
Newer players especially seem like they could find it confusing to determine where they should go to get the maximum possible ramscoop/solar power.

Something like, as a super quick mockup, 
<img width="953" alt="Screenshot 2022-12-29 115544" src="https://user-images.githubusercontent.com/15916854/209985411-39dd59ea-f1e3-42cc-8041-b11216d3e72e.png">

Would have to be just outside where the status overlay would be drawn, and would only be for the flagship.

**Comment by Amazinite** [comment]
> Any marker for the centre would most likely conflict with the star icon in most cases.

I can think of two possible markers that wouldn't conflict:
1. Lines that are drawn under the other objects on the map, much lighter than in this example. The difficulty there would be choosing a transparency that's bright enough to be spotted but not too bright as to obscure other stuff on the radar.
2. Add an arrow to the edge of the radar that points toward the system center, similar to the arrows used for marking linked systems but larger and noticeably different.

![image](https://user-images.githubusercontent.com/17688683/209985142-ca00a297-bbff-464b-a2ca-4a2892f104f4.png)

**Comment by Zitchas** [comment]
As far as helping people find the center goes, two ideas:

1) Repurpose the "land" button. Or give it added functionality. If the player hits "land" and there's no viable place to land, it instead directs the player to the center of the system. If there *is* a valid place to land, have the center of the system be one of the options (probably last on the list) that the player can cycle through by repeatedly tapping "land".
2) Have an optional UI element that traces a line from the player (center of the radar) toward the center of the system. Perhaps a dashed line, maybe even with an "AI target" label on it. All faded, of course. This would show up whenever the autopilot is engaged, and point to whatever the AI is piloting to. If the target is on the radar, the line would go to the target, and end there. Of course, this would need to be togglable.

**Comment by vitalchip** [comment]
I went for holding left and right points the ship to the system centre. You can normally tell which way is 'in' by where is busiest on the radar edge butit's a small convenience if you're really far out in a system with spread out planets.

I added it at the same time as holding forward and back to spin the ship 180 (when the ship has reverse thrust)
