### ISSUE TITLE
Boarding Mission Bug + No way to "defer+flee"

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#798]
I have code to fix both these things already; they are all issues I ran into when trying to make complex boarding missions, which I don't think have been tried much before.  

Issue 1: ConversationPannel::KeyDown() handles boarding mission outcomes correctly when pressing "enter" to select a conversation node, but the same logic is missing from ConversationPanel::Click(). Refactored and moved common code into a separate function so that behavior is consistent regardless of whether you use use mouse or keyboard. 

Issue 2: There is currently no way to "defer" a mission and at the same time cause the player to immediately leave the location in the manner of a "launch" or "flee".  I added a new keyword "**depart**"(defer+leave location) to mirror "launch"(accept+leave location) and "flee"(decline+leave location). Added one or two short comments to clarify in the code what keywords do what. 

Issue 3: The code wasn't supporting "on defer" callbacks in missions.  No new infrastructure was needed, it was just missing the "defer" case in Mission::Load() at around line 185.  

DOES ANYONE HAVE A BETTER NAME FOR THE "defer+leave location" KEYWORD THAN "DEPART"?  I would have loved to call it "defer_leave" to make it clear that this triggers the "on defer" callback.  But "launch" and "flee" are not called "accept_leave" and "decline_leave" so it wouldn't match.  Maybe "withdraw" or "postpone" or just "leave"?  Probably not "vamoose". :)  
@endless-sky As always, I "defer" to your preference on this. :)

**Comment by Wrzlprnft** [comment]
Good job!
How about "relinquish"?
somehow i would switch "launch" and "flee" to the other side

**Comment by LocalGod79** [comment]
if you're looking for a descriptive variable name, i like 'deferredlaunch' or 'deferlaunch', rather than the default [accept]launch - won't really matter, if it makes it into the wiki...

**Comment by LocalGod79** [comment]
have you tried something like the below?
(and you'll need to imagine the indents)

on offer
conversation
`wanna go there?!`
choice
`another time...`
flee
`right now!`
launch

on decline
clear "<mission name>: offered"

**Comment by jmhorjus** [comment]
Yes, using on decline to clear mission: offered does make "decline" function more or less like "defer" and thus "flee" function like "defer+leave location".

But what if someone wanted to use "on decline" for when the mission is actually declined?  The game engine should support that.

**Comment by endless-sky** [comment]
Merged your PR, and added your changes to the wiki.

**Comment by jmhorjus** [comment]
Awesome, thanks!
