### ISSUE TITLE
Make Mountaintop the default landing site for Ultima Thule

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#7997]
### Problem Description

Once the spaceport is active at Mountaintop, it should become the default landing site for Ultima Thule. The purpose of mountaintop is to be a barrier to the wormhole and the holographic projection is there to hide it. Therefore, ships should naturally gravitate to it. At the end of Hai reveal it becomes an immigration checkpoint and stopping becomes mandatory, so bypassing it should require a choice on the part of the player.

### Related Issue Links

none

### Desired Solution

As above, make Mountaintop the default landing zone.

### Alternative Approaches

n/a

**Comment by EjoThims** [comment]
That makes sense, yea.

**Comment by MasterOfGrey** [comment]
Landing target is defined by a great many factors that aren't controlled by any data-file contents though.
So this would likely require some kind of code change to facilitate a priority attribute of some kind.
