### ISSUE TITLE
My escort ship was blown up but I still pay the crew

### ISSUE THREAD

**Issue by Shadowscall** [endless-sky/endless-sky#80]
Maybe I am misunderstanding something so I will explain exactly what happened in case I am. I had just gotten a hawk and I was taking it out for a joy ride and I got attacked in the Persian system by a pirate flying a Fury. I disabled him and boarded him. I was able to capture the ship and they lost one crew, I lost none. However, we instantly got attacked and he was disabled again. The attacking pirate was killed and I flew back to the planet at Alnair to unload the loot I had. I landed, did the trade and took back off. At this point I realized that the Fury I captured had been disabled back in the Persian system and I didn't repair him before jumping back to Alnair and landing. I went back to the Persian system and boarded the Fury to repair him, however, when I finished repairing him, he would not move for about 10 seconds or so and then would only go forward, he would not follow me. I tried to jump to the Alnair system to see if he would follow me, but he did not. I went back to the Persian system and saw that the Fury was flying forward and would not follow me or jump, even with me holding the J key for several seconds. I caught up to him and blew him up and I was ready to just count it as a loss and move on with the game. But then I noticed that the Fury was still in my ships info pane and the name was red. I also noticed that I was also paying for the crew on the Fury ( at least I think I was, when I got the hawk it was 100 crew costs, since the hawk has 2 crew, but when I got the Fury it jumped to 200 crew costs and even after the Fury was blown up, I was still paying the 200 crew cost.) Like I said, I may just be missing some obvious thing or something, but I thought I should post this to find out.

**Comment by endless-sky** [comment]
You're right, that is a bug - the salary calculation was including any destroyed ships that were in the list. (They don't get removed from the list until you land.) Fixed in commit fca49e7.

The Fury probably had its steering system stolen by a pirate while it was disabled. That would explain why it couldn't follow you.

**Comment by Shadowscall** [comment]
Ok, thank you and I just wanted to say that when I found this game I was really happy. There may have been some schoolgirl squeals of glee (I won't confirm or deny). :) I really loved EV: NOVA and this is a worthy successor. I can't wait until more stories get developed.

**Comment by endless-sky** [comment]
Unfortunately, if a ship's engines have been stolen it is basically scuttled and useless. However, if you are in an inhabited system that has an outfitter or shipyard, you can repair the ship and then land and it will end up on the planet with you. You can put new engines in it (or sell it).

You've probably gathered that I was a big EV fan too. I spent a decade waiting around for someone to create a sequel that I could respond to with those same squeals of glee, then finally decided I'd just have to do it myself (after briefly pinning my hopes on NAEV, then seeing it drift away from EV in terms of game mechanics and then go idle for years).
