### ISSUE TITLE
New Interstellar Drive Suggestions

### ISSUE THREAD

**Issue by GalacticRuler** [endless-sky/endless-sky#800]
Starting one step _down_ from hyperdrive: Warp drive - a smaller engine that moves monstrously slower than a hyperdrive but uses energy instead of fuel.

Next, a step up from jump drive: Wormhole Generator - a drive that pops open an unstable wormhole to point B. Huge, uses lots of fuel, but moves instantly a large distance bypassing hyperdrive lanes. You have to thrust into it, imparting inertia on exit.

Finally an unlootable final system: Quantum Slip-Drive - uses loads of fuel, not much space, generates a lot of heat, but can move any distance bypassing hyperdrive lanes instantly imparting no inertia on exit.

**Comment by LocalGod79** [comment]
warp drive can probably be coded in a plugin.  you should try it.

wormhole generator would require a significant coding effort for relatively little gain

somebody is already working on code that would enable "quantum slip drive" to be created in plugins.

**Comment by GalacticRuler** [comment]
Warp I tried but I cant make it only draw energy on use and can't stop it's fuel consumption.

The QSD I was unaware of, any links to a post or anything? And wouldn't the wormhole generator be a slight change to the QSD?

**Comment by brick96** [comment]
The wormhole generator would have to be able to create 2 same named planets (the current way to make a wormhole) one in system and another in the destination system

**Comment by GalacticRuler** [comment]
By that I meant an effect, so its not dropping planets everywhere and not going to require as many code changes.
