### ISSUE TITLE
Ships belonging to "Uninhabited" faction

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#801]
I noticed this a while back and I initially figured it was just a temporary placeholder, but after coming back I still see ships marked in red and orange paint and listed as "Uninhabited".  Is this supposed to exist?  When hailed, they have nothing to say.
![uninhabited ship](https://cloud.githubusercontent.com/assets/692397/13167039/13682536-d69d-11e5-8bc2-7659103b2031.jpg)

**Comment by Gkramme** [comment]
I've never seen that.

**Comment by GalacticRuler** [comment]
Any plugins installed?

**Comment by lehgogh** [comment]
What version did it start at?

(Enough questions yet?)

**Comment by Bladewood** [comment]
25 kestrels? Impressive.
I have 32 shield beetles.
[end]
But, anyway, systems belonging to the "Uninhabited" faction can only be found in the Pug galaxy.
They shouldn't have any ships, though, and even if they do, the last place they would be found is in our galaxy.

**Comment by johndh** [comment]
No plugins installed... not sure what version it started at.  I seem to see it the most often near the FW/Republic border.  The only thing weird I've done is I accidentally opened my save file in an old version of ES once upon a time, and I suppose that may have corrupted the file(?), but this is just wild conjecture on my part.

@Bladewood My fleet used to be much larger, but it slowed the game down too much. ;)

**Comment by GalacticRuler** [comment]
Is there any mention of a "Uninhabited" gov in the files?

**Comment by lehgogh** [comment]
For only map.txt: `uninhabited` is used as a flag for the planets Watcher and Hope. It does not appear to be a government.

**Comment by Bladewood** [comment]
As I said, the "Uninhabited" faction is only found in the Pug galaxy.
`government "Uninhabited"`
	`color .3 .3 .3`

`galaxy "pug empty galaxy"`
	`pos 10000 7000`
	`sprite ui/pleiades`

`system "Over the Rainbow"`
	`pos 9904 7176`
	`government Uninhabited`
	`...`

`system "Terra Incognita"`
	`pos 9921.5 7086.5`
	`government Uninhabited`
	`...`

`system "World's End"`
	`pos 9966.5 7017.5`
	`government Uninhabited`
	`...`

@johndh The only times for me when the game is slow is when I am fighting Earth for tribute, or when I am jumping.
