### ISSUE TITLE
Program crashes when ship is lost (failed takeover)

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#8011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

December 30 continuous Build.
Testing some of the new game balance tweaks.
I accidentally forgot to rehire max crew with a Kimek Spire, attacked a crippled Korath vessel (Remnant storyline) - as soon as the ship is lost, the program crashes out.

### Steps to Reproduce

Load savefile.
Depart Viminal.
Wait for the crippled Pavralet to arrive; escorts will (likely) disable. 
Attack disabled Korath ship.... keep going until the bitter end
program will crash.

### Expected Behavior

The usual process where I lose the ship (die) and the game goes on without me.

### Link to save file

[Philthy McNasty~3015-08-14 - system crash.txt](https://github.com/endless-sky/endless-sky/files/10328176/Philthy.McNasty.3015-08-14.-.system.crash.txt)

### Operating System

Ubuntu 21

### Game Source

GitHub Releases

### Game Version

Dec. 30 continuous release

**Comment by warp-core** [comment]
Can you try this on the latest continuous (or at least, after https://github.com/endless-sky/endless-sky/commit/afc91c1edb4a0c21eb5c3f4dc3c31809494e5a1a)?

**Comment by movingpictures** [comment]
Well, dang. Not able to replicate with the latest build (today, b2fdc99) 
I will consider this a non-starter.

**Comment by warp-core** [comment]
> Well, dang. Not able to replicate with the latest build (today, [b2fdc99](https://github.com/endless-sky/endless-sky/commit/b2fdc99a681340b7d9b6f4601405773c46e71192)) I will consider this a non-starter.

It's not that the issue wasn't present, it's just that I fixed it since yesterday's build.
~~And, I don't think this crash was the one I caused.~~

**Comment by movingpictures** [comment]
Oh, no issue here....

(I've been testing PRs and continuous builds for years, and my capacity to
find glitches has been .... lacking. So it is entirely on brand for me to
find something that has already been fixed, even if the glitch wasn't in
the bug reports previously.)
