### ISSUE TITLE
Trade level missing for sells.

### ISSUE THREAD

**Issue by hmglasgow** [endless-sky/endless-sky#8013]
### Problem Description

I'm very much enjoying playing Endless Sky. One little niggle I have is with the Trading panel. The trade level (low, medium, etc) is displayed next to the commodity when you are buying, but when selling, this gets replaced by the profit.

### Related Issue Links

-

### Desired Solution

Although profit is good information, it would be helpful to also know the trade level, so that you can decide whether to sell now or perhaps hold out for a better deal in another system.

![tradeLevel1](https://user-images.githubusercontent.com/102213051/210165949-a8112a1b-87aa-4b7e-8a89-95b7b59a8a61.PNG)

![tradeLevel2](https://user-images.githubusercontent.com/102213051/210165961-d6853ab3-e25b-454e-813f-2da1d123192e.PNG)

### Alternative Approaches

I've included two alternative screen mock-up of how it might look. Thank you.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/097b2d36e71e1f5a9dc3fb0231b30add019cee00

Profit is now displayed separately to the trade level.
