### ISSUE TITLE
Create "Fleet Stances" to alter fleet behavior

### ISSUE THREAD

**Issue by Hyratel** [endless-sky/endless-sky#802]
A lot of games where you have a Pet/Summon/Ally allow you to define that Ally's "Stance", such as:
- Aggressive: Attack hostiles on sight, regardless of threat level
- Defensive: Attack hostiles only if damage is received
- Passive: Do not attack, even if fired upon

I can see more than a few cases where it would be beneficial to the player to be able to set either Defensive or Passive Stances on the Fleet Escorts (Where current behavior would classify as Aggressive), allowing for hurrying through a system at maximum speed. I would also suggest the following stance, or a variant of:
- Averse: Actively avoid combat (run away in-system)

Additionally, i'd like to be able to fine-tune, though this perhaps treads into mod territory
- Attack to disable vs destroy
- Focus Fire Player's Target vs Nearest Target vs Highest Threat Target

**Comment by nylki** [comment]
I'd like to take on this issue to get a feeling for the code base. Just to clarify *defensive*, I can imagine two mechanics:
after damage is received (by flagship only? or any fleet member?):

- Should the escorts target only those ships that have actually delt damage to the players fleet / flagship
- or should the escorts *temporarily* switch to being *aggressive* until no hostile ships are in the system anymore (then switch back to being *defensive*)

What makes more sense?

**Comment by brick96** [comment]
Most of these behaviours/stances are already in game as personalities, just need to be applied to your fleet and a way to change, either as whole via options or individual through fleet screen

**Comment by nylki** [comment]
@brick96 ah ok, I noticed "timid" and "heroic". Still isn't the same as reacting directly to taken damage or the proposed "evasive" stance to run away from opponents.

**Comment by Hyratel** [comment]
I think being able to set per-ship behaviors through either Fleet or Outfitter makes sense, as well as an override in the flight scene - eg, you can set the basic behaviors such as Aggressive/timid and Avoid for individual ships, and say for ex, in-flight "Agg/Def/Pas" (aggressive/defensive/passive) would always override each other but not Averse. 
there's honestly a lot of interaction between "Behaviors" and "Stances" that can have some interesting results from a player's perspective. maybe set Behaviors from the fleet screen and Stances from flight

**Comment by nylki** [comment]
I imagine it could become a bit too much micromanagy or confusing if you are able to assign stances to single ships *additionally* to also setting basic behaviours, the interface would have to make it clear and transparent how each ship is set otherwise this could become quite a mess.

For now stances for the complete escort fleet might be a better start, in my opinion. Then see how it plays out ingame to decide on individual ship stances. maybe? :)

**Comment by Hyratel** [comment]
no, "Stances" would always be fleetwide. but behaviors define how ships react to the stances in predictable and roughly configurable ways.

like, you've got a merchant fleet, with a few combat escorts - you want your cargo ships to stand off out of beam range and bombard with missiles, while your combat escorts mix it up nose to nose. but you want to be able to set that up.

**Comment by nylki** [comment]
Ok, I started to work on the code.
You can test my fork here: https://github.com/nylki/endless-sky/tree/fleet-stances
Going open a PR later to discuss some particular changes and code style.

I started to work on a defensive fleet stance.
Press `2` to toggle the defensive fleet stance:
- your escorts will now imitate the already existing `timid` behaviour: staying around 500 (meters?) around your ship
- escorts will only fire shots at opponents, if the playership got attacked in the last 5 seconds

The last point is only for testing. That way it's easier to see if the command is actually applied :) Later I will change it, so escorts only fire shots if any player escort got attacked in the last n seconds.

**Comment by wargwargwarg** [comment]
@ nylki
could you include a defensive behavior (fire on enemies as normal, until the max distance from flagship then return to it? Perhaps to a predesignated position?

**Comment by nylki** [comment]
@wargwargwarg 

> could you include a defensive behavior (fire on enemies as normal, until the max distance from flagship then return to it? Perhaps to a predesignated position?

Sure, will do for testing, it's actually a minimal change to apply that behaviour, as in my changes they already return to the flagship if it is too far away. :)
But if it comes to merging the code into the main code base @endless-sky will have to decide which stances fit best. Having too many stances would clutter the code and preferences.


> tried to run your code, it get's compiled but on starting it it cries for glew32.dll,OpenAL32.dll,libjpeg-62.dll and libpng15-15.dll.

I didn't change anything, that would cause those errors. My guess is, that you need to install the dependencies outlined in https://github.com/endless-sky/endless-sky/blob/master/readme-developer.txt

**Comment by Amazinite** [comment]
We already have means of selecting escorts and telling them to focus fire, hold position, move to a specific location, etc. These fleet commands effectively encompass anything you'd want to do with these fleet stances. If you feel there are commands you'd wish to give your escorts that are missing, then those should be separate fleet commands. Hold fire, as an example, is still a command that is in the works.
