### ISSUE TITLE
Suggestion: "Buy Quantity".

### ISSUE THREAD

**Issue by GalacticRuler** [endless-sky/endless-sky#803]
Just asking if its easily doable. I've grown tired of clicking an excessive number of times to buy multiples of anything.

Also, as a side question: Can you multi select ships and buy parts for all of them at once?

**Comment by mrec** [comment]
Shift-click buys/sells 5, Ctrl-click 20, Shift+Ctrl 100, Alt 500, Shift+Alt 2,500, Ctrl+Alt 10,000, Shift+Ctrl+Alt 50,000.

Multi-selecting ships in the Outfitter can be done with Ctrl-click (select individuals) or Shift-click (select range).

And yes, there's a gaping hole in the in-game help for this sort of thing.

**Comment by GalacticRuler** [comment]
Thank you for the information!
