### ISSUE TITLE
Untranslated random interval hails don't happen

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#8037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Untranslated hails are entirely disabled in the code, including for random interval hails.

### Steps to Reproduce

1. Visit the wanderers before you know their language
2. Witness the lack of untranslated hails.

### Expected Behavior

Untranslated random interval hails should happen, but no other untranslated hails should happen (like stations or asking ships for help)

### Operating System

`Linux nose 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### Game Source

Built from source

### Game Version

02a280c1c

### Additional Information

This, presently broke, feature is important when races are trying to communicate, even though they can't do so effectively. I use that in #8036, where Korath try to communicate with you when they need to: give us your cargo, and we'll let you live (raiders), please don't use nerve gas on us (disabled raiders), the Quarg and Drak protect us (Efret). They have terribly mispronounced human speech, and their grammar is bordering on non-existent, but it is clearly important to them that they communicate in those situations.

**Comment by Amazinite** [comment]
That's intended.

**Comment by UnorderedSigh** [comment]
> That's intended.

That makes sense for requesting help or asking to land, but they have no way of knowing that you can't understand them when sending a hail. Surely races would want to warn you off or offer kindness if that is in their personality.

**Comment by UnorderedSigh** [comment]
> If anything, the bug is that we have untranslated Wanderer hails.

In the case of my PR #8036, the Korath hails are partially translated. They're attempting to communicate, vai the few human words they know, that they want your cargo (Korath raids) or claim to be protected by the Quarg and Drak (Kor Efret).

**Comment by UnorderedSigh** [comment]
> If anything, the bug is that we have untranslated Wanderer hails.

I can do another PR to remove Wanderer hails, if you feel it appropriate. In my PR though, it makes sense for the Korath to send hails, because they truly are attempting to communicate, and use what few human words they know, or words in common between languages, like "Quarg" and "Drak"

**Comment by UnorderedSigh** [comment]
>  If anything, the bug is that we have untranslated Wanderer hails.

PR #8039 removes the wanderer untranslated hails from governments.txt

**Comment by UnorderedSigh** [comment]
So it seems that this is the solution:

1. Disable untranslated hails from the Wanderers in #8039
2. Allow untranslated hails (from nobody, at that point) in #8038
3. Let the Korath send their (partially translated) hails in #8036

**Comment by UnorderedSigh** [comment]
Also, logically speaking, there is no reason why someone who doesn't speak your language would be unable to send you a hail. We have to disable some things for game mechanics reasons, but random interval hails are not among them. If trying to communicate with you fits the personality of a race, then they certainly should be able to do it.

**Comment by mOctave** [comment]
> Also, logically speaking, there is no reason why someone who doesn't speak your language would be unable to send you a hail.

They may well be able to send you a hail, but you may not _understand_ it. Suppose a certain species communicates with high-pitched, very fast clicking. You might think that it's just static, and your ship might even filter it out, until you actually meet the aliens and discover that what you thought was static is actually a complex language. This doesn't necessarily apply to the Wanderers specifically, but aliens in general.

**Comment by UnorderedSigh** [comment]
> They may well be able to send you a hail, but you may not understand it. Suppose a certain species communicates with high-pitched, very fast clicking. You might think that it's just static, and your ship might even filter it out, until you actually meet the aliens and discover that what you thought was static is actually a complex language. This doesn't necessarily apply to the Wanderers specifically, but aliens in general.

You are, indeed, correct. I can't imagine the player understanding the Korath nanites. Their form of sentience is probably so different from ours that we probably couldn't even relate.

**Comment by UnorderedSigh** [comment]
Also, some aliens simply don't want to talk to you. I think it's completely appropriate for Archons to never send random hails, since their personality is somewhat aloof.

The Korath and Wanderers have legitimate reasons to speak to you, so they certainly would make the effort to be understood.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/e3839276196dad0af04318690477060c566e2167
