### ISSUE TITLE
Balance: Make Quicksilver cheaper

### ISSUE THREAD

**Issue by 1010todd** [endless-sky/endless-sky#8048]
### Problem Description

When choosing my Light Warship I noticed that Quicksilver is just horrible in everyway compared to other ship of same price range especially as combat ship. Here's some of the stats between Quicksilver, Headhunter, and Clipper

<table>
<tr>
	<td>Stats
	<td>Quicksilver
	<td>Clipper
	<td>Headhunter
<tr>
	<td>Shields/Hull
	<td>3000/800
	<td>2700/800
	<td>3800/700
<tr>
	<td>Hardpoints
	<td>2 Guns
	<td>4 Guns
	<td>4 Guns, 1 Turret
<tr>
	<td>Outfit/Wep/Engine Space
	<td>240/60/70
	<td>260/60/80
	<td>250/60/80
<tr>
	<td>Cargo Space
	<td>10
	<td>70
	<td>50
<tr>
	<td>Crew Req/Bunk
	<td>3/6
	<td>3/9
	<td>2/4
<tr>
	<td>Fuel
	<td>400
	<td>500
	<td>400
<tr>
	<td>Price(Hull/Outfitted)
	<td>1.090M/2.012M
	<td>0.900M/1.270M
	<td>1.850M/2.660M
</table>

Headhunter is quite a lot better than Quicksilver in everyway(+800 shields, turret, more space) for just 660K credits more but even worse *Clipper* is just better for cost of 300 shields which you could probably make back with outfit expansion and bigger shield generators. In fact, I can outfit a Clipper to use 2 Particles like Quicksilver but also use biggest shield generator by installing 3 outfit expansion(no cooling needed), Radiothermal instead of Fuel Cell, and still have 40 spaces to spare (also while using a bigger battery than Quicksilver) and it sits at 2.135M outfitted, merely 125K above stock Quicksilver. Oh wait the turn is slightly less, anyway I can swap Greyhound for Impala steering and now it turns 28 units faster than stock Quicksilver, actually still faster than Quicksilver with A250+A255 atomics as well (by 8 units). So with that Clipper cost 2.178M total outfitted, a bit more than Quicksilver for everything + versatility of being able to just go back to merchanting whenever you want. The only thing Clipper is worse at is top speed and acceleration but nobody care about that when star systems are so tiny you can fly across it in like 10 seconds anyway.

Anyway as you can see Quicksilver is just worse than even a cheaper freighter *at combat* (and I may have accidentally proved instead that Clipper is just OP.)

### Related Issue Links

Talked about abit on Discord
https://discord.com/channels/251118043411775489/266345072554016768/1059575308493258852

### Desired Solution

Outfitted, Quicksilver probably should sell a bit cheaper, maybe 1.6M~1.8M or something so it might be more of a choice for cheap and combat effective ship.

### Alternative Approaches

Not sure how but maybe Clipper could be nerfed instead.

### Additional Context

-

**Comment by vitalchip** [comment]
Drop two gun ports from the Clipper, it has too many for a (very) light freighter. Reduce the weapon capacity and outfit capacity to match, this will make it lighter and therefore quicker on it's toes.

Make the Quicksilver toughher, double the hull. It's pathetic for what is supposedly a Light Warship. 

Personally I don't consider it makes the grade as a warship of any flavour, it's an interceptor with a higher than normal weapon capacity, specifically to fit the two Particle Cannons but that's another story.

**Comment by mOctave** [comment]
I'm not sure that removing gun ports from the Clipper is necessary, but the weapon space should definitely be nerfed. 32 weapon space (for 4 lasers max) would seem reasonable.

**Comment by Saugia** [comment]
Yeah, there are plans to buff several small human ships to have more gunports actually, but *not* touch their weapon space. I don't feel like removing mounts is the way to go.

Also, preferably keep the Clipper able to have two heavy rocket launchers/pods like the one Hawk variant. Those are pretty iconic in early gameplay.

**Comment by Zitchas** [comment]
> Also, preferably keep the Clipper able to have two heavy rocket launchers/pods like the one Hawk variant. Those are pretty iconic in early gameplay.

If by "iconic" you mean much hated and the source of a *lot* of player deaths, then yes, very iconic. (I'm not arguing to change it, I'm just saying I only consider it "iconic" in as much as that specific build has basically translated to "never ever go near a clipper, they are the scourge of the galaxy, and aren't worth the risk. Oh, and that was a light **freighter**?!?! Why aren't our light warships this good?)

In any case, the proposed 32 weapon space would be plenty to fit two heavy rocket pods and still have space to fit a pair of lasers in the other two gun ports. Or blasters, or some other options.

----

The larger point, however, is yes, I do think the Quicksilver needs a buff. Reducing the price is probably the best and easiest option, but taking a look at how it fits into the game and deciding whether or not it should be a good interceptor or a really cheap light warship would be good to do too.

**Comment by Zitchas** [comment]
For comparison, adding in the Hawk to the comparison table:

<table>
<tr>
	<td>Stats
	<td>Hawk
	<td>Quicksilver
	<td>Clipper
	<td>Headhunter
<tr>
	<td>Shields/Hull
	<td>2500/500
	<td>3000/800
	<td>2700/800
	<td>3800/700
<tr>
	<td>Hardpoints
	<td>2 guns
	<td>2 Guns
	<td>4 Guns
	<td>4 Guns, 1 Turret
<tr>
	<td>Outfit/Wep/Engine Space
	<td>200/50/70
	<td>240/60/70
	<td>260/60/80
	<td>250/60/80
<tr>
	<td>Cargo Space
	<td>20
	<td>10
	<td>70
	<td>50
<tr>
	<td>Crew Req/Bunk
	<td>1/4
	<td>3/6
	<td>3/9
	<td>2/4
<tr>
	<td>Fuel
	<td>300
	<td>400
	<td>500
	<td>400
<tr>
	<td>Price(Hull/Outfitted)
	<td>0.670M/1.078M
	<td>1.090M/2.012M
	<td>0.900M/1.270M
	<td>1.850M/2.660M
</table>
