### ISSUE TITLE
"Remnant: Celebration 1" can have source and destination the same

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#8068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Remnant: Celebration 1" mission is supposed to involve carrying a recording of a celebration to the Ssil Vida station. However, the mission prerequisites are too broad (attributes "remnant primary"), allowing it to be offered _at_ Ssil Vida.

### Steps to Reproduce

1. Complete the Remnant: Cognizance missions until you reach the calm.
2. Land on Ssil Vida repeatedly until you receive the "Remnant: Celebration 1" mission.
3. This mission makes no sense on multiple levels: It talks about rocky caverns and stalactites, which don't exist on the station; it states that the recording is to be taken to "those who are not present" at Postverta, even though the player is at Postverta; and of course the source and destination are the same.

### Expected Behavior

"Remnant: Celebration 1" should only trigger on the core Remnant worlds.

### Operating System

Ubuntu Linux 22.04

### Game Source

GitHub Releases

### Game Version

0.9.16.1

### Additional Information

#7026 has a similar "mission should not be offered at Ssil Vida" problem.

I suspect that this mission could also trigger at Esquiline, and the references to caverns and stalactites wouldn't make sense there either.

**Comment by warp-core** [comment]
Fixed (in continuous) by https://github.com/endless-sky/endless-sky/commit/f7f0cd2318c85ab9a224d9f1cfa6ae499bccf857
