### ISSUE TITLE
Jump with disabled ship

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#8079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you get disabled just as start jumping your ship keep's on going.

### Steps to Reproduce
#1: Get disabled.
#2: Ask a ship to repair you and (obviously) let it repair you.
#3: Hold down the jump button.
#4: When a missile comes very close to you and in the opposite direction let go of the jump key!

### Expected Behavior

The ship doesn't continue jumping and you find yourself somewhat far from where you started jumping, or you jump slower(takes 2 or more days to get to the next system).

### Screenshots

![Jump with disabled ship](https://user-images.githubusercontent.com/93033911/211207313-b259c18c-fd24-4ea8-8664-b2fbb4882826.png)

### Operating System

Ubuntu 22.04.1

### Game Source

Other (please describe)

### Game Version

0.9.8 Got it from Ubuntu Software sourse: ubuntu-jammy-universe (deb))

### Additional Information

Make sure to think through about how the Hyperdrive works/does.

**Comment by vitalchip** [comment]
I.m going to suggest that ships which become disabled during a jump should be destroyed. Collapsing hyperspace etc.

**Comment by TomGoodIdea** [comment]
You trigger `a nuclear fusion reaction powerful enough to level an entire city`, but your ship is disabled and can't handle that properly…
To me, that sounds like an instant death.

**Comment by quyykk** [comment]
#5058

**Comment by vitalchip** [comment]
It's a fairly rare thing but I suppose it depends how you view hyperspacing, does the drive just 'get you in' or is it needed throughout?  Does the drive need a functioning ship around it?

I reckon a failed drive / disabled ship should be disastrous mid jump but I don't think it's ever actually happened to me, so not exactly a burning issue.

If we had some sort of hyperdrive disruption weapon though..


https://user-images.githubusercontent.com/65342577/211329985-bc0529d6-7544-4479-b844-2978e74d0035.mov

**Comment by ixPost** [comment]
I guess that having your ship destructed is a good idea, but there is a problem:
Shouldent disabling a ship mean disabling the outside stuff(besides in the outfitter it says "This mysterious box sitting quietly at the **heart of your ship**").

**Comment by TomGoodIdea** [comment]
No, if your ship is disabled, all internal and external outfits are disabled, you don't even have power generation.

**Comment by johndh** [comment]
I've seen this happen multiple times to ships I've been attacking, where they'll escape while disabled.

**Comment by ixPost** [comment]
I guess the Hyperdrive should be disabled due to the fuel tanks being disabled.

**Comment by ThrawnCA** [comment]
I have encountered this. It was certainly convenient, but not logical.

**Comment by lumbar527** [comment]
Maybe it's the hyperdrive stops working, but you just need it to activate and you keep going. It could be like how you drift while you're disabled. (Just a thought)

**Comment by ThrawnCA** [comment]
> Maybe it's the hyperdrive stops working, but you just need it to activate and you keep going. It could be like how you drift while you're disabled. (Just a thought)

Typically that would result in a ship being left behind while the rest of the fleet jumps. Unless you're unlucky enough for it to be your flagship.

**Comment by TomGoodIdea** [comment]
> This would be an interesting feature to have, but the technical difficulties of coding that are pretty high (probably?)

I don't think it would be too hard to implement, but there's no agreement whether the current lore and mechanics should be changed.

**Comment by Saugia** [comment]
Judging from where this discussion has gone, as well as the original link to the issue, there doesn't still seem to be a strong impression of one way or the other. For gameplay purposes and ease, it is fine that this sort of behavior remains the same. 

The only two important cases I can think of currently is one being the player jumping away, in which keeping the current behavior assists in this and makes this experience more forgiving, or when attempting to capture/destroy a ship, the ship gets away. There aren't any story missions where this is a detrimental existence, so I can only think of capturing, in which I don't believe this is reason enough for a code chance for such behavior.
