### ISSUE TITLE
Feature request: Ability for escorts to transfer crew onto your ship

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#808]
Quarg hunting. Disabling them is easy, capturing them is hard.
My strategy: Attack until I am weak enough for them to fight back. Then defend until they stop attacking. Then attack again. Then defend. And so on.
Eventually, I once managed to bring a ship down to 17 crew.
But then they killed me. And stole my ship. Which was promptly annihilated.
I want the ability to order my escorts to transfer their crew members to my ship. And then I can legitimately capture a Quarg ship. (Who cares if they limp back to port? They're godships!)

**Comment by thenerdfreak** [comment]
I agree, if we can attack and transfer crew to an enemy ship, why not our own? It would open up new venues and since quarg are finna be outdated by the release of Draki it won't be op anymore

**Comment by endless-sky** [comment]
As with other recommendations that would make it easier to capture ships: capturing is already an overpowered way to earn money compared to just about anything else, so changes to make it even easier don't make sense.

**Comment by thenerdfreak** [comment]
If this were implemented it would also have to change the way the crew killed/ amount you have to pay thing works. Maybe give a chance of  *losing* money
