### ISSUE TITLE
Storage breaks in-game licensing mechanic

### ISSUE THREAD

**Issue by vkr-13** [endless-sky/endless-sky#8089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Putting an outfit into storage allows you to bypass the license requirement for that outfit and buy as many of said outfit as you want till you take it out of storage.

### Steps to Reproduce

1: Loiter around a contested area (this'll work for Gegno, Wanderers vs. Unfettered Hai, or Remnant vs. Korath)
2: wait for "raided parts" that require licenses to drop from a destroyed ship.
3: head to your nearest retailer and put the outfit into storage by pressing "u".
4: you should now be able to buy as many of that outfit as you want, regardless of license requirement.
5: Once done, simply take out of storage and the licensing is reinstated.

### Expected Behavior

When one salvages parts from space, one should not get licensing immunity. That's how white collar crimes are committed.

But fr, it doesn't really make sense to be able to put an item into storage and then go ahead and buy <n> amount after.

### Screenshots

![Screenshot 2023-01-10 053821](https://user-images.githubusercontent.com/65760431/211384938-85ea73b5-cf69-40a6-9c4d-ee04f5e9d638.png)
![Screenshot 2023-01-10 053923](https://user-images.githubusercontent.com/65760431/211384945-8a6f618f-76f5-40cf-b324-b059dfb8b7d7.png)
![Screenshot 2023-01-10 053938](https://user-images.githubusercontent.com/65760431/211384950-81f8f9f1-e001-40ac-9612-4ec1f6f1b36a.png)
![Screenshot 2023-01-10 053952](https://user-images.githubusercontent.com/65760431/211384952-8d41bc7f-5cb5-40b0-9f95-83f65b156568.png)

### Link to save file

[Frankfurt Oda'am~Frank stole the partyboat!.txt](https://github.com/endless-sky/endless-sky/files/10376087/Frankfurt.Oda.am.Frank.stole.the.partyboat.txt)

### Operating System

Windows 11 Home, Version 22H2

### Game Source

ESLauncher2

### Game Version

"v0.9.17-alpha (82ea3cb)"

### Additional Information

Don't say "Hai", say "Korath"!

**Comment by warp-core** [comment]
Fixed by https://github.com/endless-sky/endless-sky/commit/9737d36891ff5aede0a058dd6b4834abe39c23a6.
