### ISSUE TITLE
Loophole lets you obtain unlimited Emerald Swords

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#8101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

By repeatedly reloading your latest save at a particular point in the Emerald Sword story line, you can obtain any number of the ship, as well as its fighters. Each iteration gives you one more set of ship+fighters. I went up to 50 (and so 300 fighters!).

### Steps to Reproduce

- Save at the planet before boarding Emerald Sword just in case.
- Board Emerald Sword. Finish the dialogue and land on the planet.
- More dialogue comes up. Don't do anything.
- Reload the latest save N times.
- Finish the dialogue.
- Open the fleet details screen.
- Count N Emerald Swords. And N*6 fighters.

### Expected Behavior

Reloading the save should still only give you one set of ship+fighters.

### Operating System

N/A

### Game Source

GitHub Releases

### Game Version

0.9.16.1

**Comment by quyykk** [comment]
I'm betting money this is https://github.com/endless-sky/endless-sky/issues/3746 again

**Comment by Amazinite** [comment]
Repeated logs were just an example in #3746. In this case the mission action that's repeatedly giving you the ship doesn't have a log.
