### ISSUE TITLE
starting with release 0.9.15, I get this error when trying to run the appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by charmparticle** [endless-sky/endless-sky#8103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I cannot launch any of the .appimage releases since release 0.9.15 because I get the error:

endless-sky-x86_64-v0.9.15.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by endless-sky-x86_64-v0.9.15.AppImage)
endless-sky-x86_64-v0.9.15.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by endless-sky-x86_64-v0.9.15.AppImage)
endless-sky-x86_64-v0.9.15.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_endlesb3fn4h/usr/bin/../lib/libSDL2-2.0.so.0)
endless-sky-x86_64-v0.9.15.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_endlesb3fn4h/usr/bin/../lib/libpng16.so.16)

OS is Ubuntu 18.04.6 LTS bionic

### Steps to Reproduce

install ubuntu bionic

download the appimage file

chmod +x the appimage file

run it

### Expected Behavior

endless sky should launch

### Operating System

Ubuntu 18.04.6 LTS bionic

### Game Source

GitHub Releases

### Game Version

v0.9.15

### Additional Information

same applies for v0.9.16 and v0.9.16.1

**Comment by RisingLeaf** [comment]
stupid question, but di you try to install libm?

**Comment by charmparticle** [comment]
@RisingLeaf from the error message, it seems like a libc version problem rather than a missing libm. The libc on my system is older than the one that was used to create the most recent appimage (I think)

**Comment by MCOfficer** [comment]
We build the appimage on Focal, so that is the latest OS it supports. Bionic goes EOL in 3 months, so I'd strongly recommend updating. If you really want to stick to bionic, you'll have to compile from source.
