### ISSUE TITLE
Ion cannon outfit space 

### ISSUE THREAD

**Issue by swifter9748** [endless-sky/endless-sky#811]
The ion cannon takes up much more space than any other forward facing gun, and Because of its low damage and questionable usefulness I think that moving the outfit space down to 30 would make it more competitive.

**Comment by GalacticRuler** [comment]
I think its to keep you from loading down fighters withe them to disable fleets easily.

**Comment by brick96** [comment]
It makes up for its low damage with "ion" damage, which applies a fading DoT to their energy that stacks(?) With every hit. No energy means no shield recharge or weapons :)

**Comment by lehgogh** [comment]
Perhaps we could balance it by slightly increasing the fire rate?

@endless-sky should add the "balance" label to this.

**Comment by DingusShingleton** [comment]
The ion cannon is devastating actually. A smaller ship with two just ion cannons can take down ships many times its size. Its massive range easily outranges every other gun and turret and pairing it with an anti missile turret or two and some fast engines is an incredibly effective strategy. One you drain a ship of energy it can no longer turn or thrust effectively, so it basically becomes a sitting duck. 

The thing is, it's not a weapon that you throw into a loadout, you really have to design the ship around it for it to pay off. But boy, when you do, it does.

**Comment by endless-sky** [comment]
I agree with others that the ion cannon really is powerful enough to justify its large size. If nothing else, it's got a longer range than any other non-missile weapon.

The way ionization works is that every frame (1/60th of a second), the ship loses energy equal to its ionization value, and then the ionization value is reduced by 1%. So, 5 ion damage adds up to 500 energy lost before the effect fades away completely (5 + .99*5 + .99*.99*5 + ... = 5 / (1 - .99)).

**Comment by DingusShingleton** [comment]
I think what people are encountering is that they add one ion cannon to their ship, which doesn't end up having enough firepower to really drain enemy ships. If the enemy ship never hits 0 energy, it would be easy to not realize the devastating effect that ion damage has. That, in turn, makes ion cannons seem really underpowered at 47 tons, which is even big for a turret, let alone a fixed gun.

**Comment by lehgogh** [comment]
@endless-sky Should we close this?
@swifter9748 If you still feel that the ion cannon is underpowered, try creating a plugin that reduces its outfit space.

**Comment by lehgogh** [comment]
Wait! I have an idea!

In #772, the 'piercing' attribute was added. Perhaps we can give the Ion Cannon some piercing? 5-10% piercing would make it slightly more attractive as a generic weapon without making ion cannon-based ships even more OP.
