### ISSUE TITLE
Hai Reveal does not recognise Remnant Quantum Key Stones

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#8113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Traveling with the Unfettered fleet to Mountaintop I receive a message saying that I need to have a Quantum Keystone installed. My flagship has a Quantum Key Stone purchased from the Remnant, which is equivalent. 

### Steps to Reproduce

1. Install a Quantum Key Stone from the Remnant
2. Play the Escort mission

### Expected Behavior

Since both keystones permit travel through the red wormholes, both should be recognized for this mission.

### Screenshots

![Screenshot_2022-03-15_09-14-57](https://user-images.githubusercontent.com/70952724/212370559-db3af313-4efe-41e2-b939-c6ffdf54fc01.png)

### Link to save file

[Virgil Cyan.txt](https://github.com/endless-sky/endless-sky/files/10413450/Virgil.Cyan.txt)

### Operating System

Linux EmberWastrel-8088i 6.0.8-1-MANJARO

### Game Source

ESLauncher2

### Game Version

recent continuous

**Comment by EjoThims** [comment]
We could change it, but I don't really think this is a bug so much as highlighting that while they do the same thing, they are not themselves, the same, and the Hai usage of it is indeed superstitious.

Just having a Remnant one may get you through the wormhole, but Sayari is still insisting on the installation of a proper Hai charm.

**Comment by Hecter94** [comment]
If it is supposed to be highlighting that the two keystones are supposed to be different, then the two keystones should actually be different in some way that the player can see, or that difference should be expanded out in dialogue. 
How does Sayari know they're different? What are the differences? Why is she okay with one and not the other?

As it is now, just saying that you need a "Quantum Keystone" but only accepting one of the two with no explanation as to why isn't a good user experience.

**Comment by williaji** [comment]
How would Sayari even know the difference between one and the other? It's installed as an outfit, that is an an integral component of the engineering part of the ship. While it might be visible on the outside of the ship, this isn't really specified. And the only people who ever notice a difference between the two are the Remnant, who are highly attuned to such things. Sayari is a diplomat, not an engineer.

**Comment by williaji** [comment]
If you want to introduce the distinction, you could do something like a certificate of authenticity to guarantee that no one is using counterfeit keystones. This would actually fit as the "Wealthy Hai" jobs require a Hai Keystone and don't recognize the Remnant one. Ideally this could be added to the outfit description "comes with certificate of authenticity" and perhaps with spaceport news to reiterate the distinction. Sayari could say, "make sure you have one from a reputable source."

**Comment by Hurleveur** [comment]
We could just use the new "flagship attribute" autocondition to make it require keystone capabilities.
has "flagship attribute: quantum keystone" would make sure of this

**Comment by Zitchas** [comment]
> We could just use the new "flagship attribute" autocondition to make it require keystone capabilities.
> has "flagship attribute: quantum keystone" would make sure of this

That would solve the check, yes, but that doesn't solve the story. Sayari expects a Hai Keystone. Not just any old crystal rock that happens to look like a Keystone.

**Comment by Hurleveur** [comment]
I think that if both keystones look the same, they should be same or we'll confuse players.

**Comment by Zitchas** [comment]
By the time they are this deep in Hai Reveal or reach Chapter 3 of the Remnant campaign, I'm 100% confident that they will usually be able to tell the difference. I'm perfectly alright getting some different outfit pictures, though.

**Comment by Hurleveur** [comment]
I'd be alright with naming them "Hai Quantum Keystone" and Quantum Keystone but we need to change smth if that's what we're going with because its clear everything in the game is done to show them being the same thing +-.

**Comment by Hurleveur** [comment]
We have display names for outfits.

**Comment by Hurleveur** [comment]
I think that to completely resolve this issue both keystones should have different sprites?

**Comment by Baustelle17** [comment]
Having the keystones as separate doesn't make sense considering the remnant mission -- obtaining and selling 60 hai keystones, implying both "types" of keystones have the same functionality. If the hai keystones are supposedly different then this mission would also not make sense. The mission also explains that the keystone is obtained through mining, additionally implying that the hai keystones could also have been obtained at a similar mine in hai space. The Nanachi missions also result in the player obtaining a quantum keystone (the Shield Beetle Pendant) -- which Nanachi explains was mined at the mine she sets up during her missions. I'd say its pretty hard to refute these two "types" of keystones' connection -- and it seems that the story so far implies they are the same object/mineral/ore/key stone, just from different places. 
The only obvious contrary to the keystones being one and the same is that the hai keystones come with a certificate of purchase -- a "certificate of authenticity certifying its origins." However I feel like requiring this certificate for the hai-human-Sayari missions is still pretty egregious. 
Additionally, the remnant key stones are significantly more expensive than the hai keystones, so the chances of a player actually using the remnant keystones over the hai are already slim. Having the hai and remnant keystones both be applicable for the hai reveal missions would _probably_ not even be a noticeable aspect of the mission to the average player.
