### ISSUE TITLE
Hai Reveal: Spruiking mission fires on system you are currently on

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#8115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At the end of the long mission to visit every Hai system and sell them on coming to Mountaintop to participate in the movie, Terry says that if you stop anywhere along the way, she will make you give another talk. This last "spruking" mission then fires immediately, before you've left the last stop.

### Steps to Reproduce

Finish the visit the planets missions. The spruiking mission will fire immediately. Use the save file and travel to Darkmetal.

### Expected Behavior

From the description, this mission should only trigger if you make an intermediate stop between the last waypoint and Mountaintop.

### Link to save file

[Zara Viscari.txt](https://github.com/endless-sky/endless-sky/files/10415189/Zara.Viscari.txt)

### Operating System

manjaro linux

### Game Source

Built from source

### Game Version

0.9.17-alpha built now a97f33537cfaef5f6b83d1bd70de41e6905dc6ba

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/a1049067b63a418ee98912dd61e288c960af2a09
