### ISSUE TITLE
Mission option says part of the game hasn't been implemented yet, but it has.

### ISSUE THREAD

**Issue by mouseas** [endless-sky/endless-sky#8119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Landed on Winter in Yed Prior after completing the Free Worlds story line, and progressing well into the Hai and Wanderer story lines. It offered me to see what Ijs and Katya are up to, then gave me this conversation. Note option 3:

![image](https://user-images.githubusercontent.com/1171633/212468373-380f2843-1938-4411-8570-0ba227d83ebe.png)

Selection that option results in:

![image](https://user-images.githubusercontent.com/1171633/212468553-ff221718-eb38-441e-b2c9-8b4e7951a66e.png)

### Steps to Reproduce

1. Complete the Free Worlds story line
2. Explore some of the larger, alien galaxy, make some progress in some of those story lines.
3. Visit Winter in the Yed Prior system.
4. When prompted to check up on Ijs, select "Yes".
5. Read conversation branch option 3, and the resulting story text.

### Expected Behavior

It looks like it's a call to action to recruit more contributors, which is a great idea. It's just the text is no longer accurate, because there's a much larger galaxy and storylines than just what's in human space.

### Link to save file

[Mike Wazowski.txt](https://github.com/endless-sky/endless-sky/files/10417179/Mike.Wazowski.txt)

### Operating System

Windows 11 Home, version 22H2, build 22621.1105

### Game Source

Steam

### Game Version

Stable Release 0.9.16.1

**Comment by ThrawnCA** [comment]
Well, what has been implemented is still very tiny compared to the number of stars in a galaxy.

**Comment by Ferociousfeind** [comment]
The galaxy hasn't been entirely filled out- there is still the huge swath of space to the east that is completely unreachable because there are no systems there

**Comment by mathwhiz1212** [comment]
Still, the way it's worded might lead someone to believe there's nothing beyond human space and maybe the Hai.

**Comment by mOctave** [comment]
> Still, the way it's worded might lead someone to believe there's nothing beyond human space and maybe the Hai.

Perhaps, but you can see for yourself all the little dots that mark unexplored systems, and sooner or later, you'll end up going to one of them. I agree that this should be kept in as a bit of an easter egg.

**Comment by lumbar527** [comment]
There will probably be many more alien species once 1.0.0 comes out.
