### ISSUE TITLE
Suggestion: Replace Swizzle with defined RGBA->RGBA values.

### ISSUE THREAD

**Issue by GalacticRuler** [endless-sky/endless-sky#812]
By this I mean instead of locked swizzles, why not use a system like:
Colors
  "Red" 1
  "Green 0.7
  "Blue" 0
Not sure how it'd handle gradients, which the swizzle does nicely...
This would allow more freedom to create new government colorsets.

An alternative would be to use Hue,/Saturation/Brightness/Alpha instead allowing smooth gradients and millions of colors.

**Comment by Pointedstick** [comment]
+1

**Comment by Bladewood** [comment]
+1

**Comment by endless-sky** [comment]
The OpenGL functionality I'm using ["texture swizzle"](https://www.opengl.org/registry/specs/ARB/texture_swizzle.txt) doesn't let you blend color channels; all it does is let you specify which channel is the source for each color. It would be possible to switch to a different mechanism (e.g. doing hue shifts in the shader itself), but that would be a much heavier burden on the GPU.
