### ISSUE TITLE
Fleet nesting similar to phrase nesting, to allow for easier use of fleets

### ISSUE THREAD

**Issue by bene-dictator** [endless-sky/endless-sky#8131]
### Problem Description

It takes a long time to create fleets or add new ships to fleets right now, as I have to pair up every single ship or variant or multiple ships or variants. Allowing fleets to be nested would cut down on this by allowing me to define a fleet of a specific type of ship, then use that fleet within another fleet.

### Related Issue Links

[Discord conversation started by me on this](https://discord.com/channels/251118043411775489/266345072554016768/1059336230883577908)

### Desired Solution

For example:
Say I wanted to add a new set of Modified Argosy variants, like the PR I have as a draft. Right now, I have to add them all manually like this:
`fleet "Medium Southern Pirates"`
`  fleet variant 30`
`    "Modified Argosy (Twin Modified Blaster)"`
`  fleet variant 20`
`    "Modified Argosy (Twin Modified Blaster)"`
`    Clipper`
`  fleet variant 10`
`    "Modified Argosy (Twin Modified Blaster)"`
`    "Clipper (Speedy)"`
`  fleet variant 15`
`    "Modified Argosy (Particle Cannon)"`
`  fleet variant 10`
`    "Modified Argosy (Particle Cannon)"`
`    Clipper`
`  fleet variant 5`
`    "Modified Argosy (Particle Cannon)"`
`    "Clipper (Speedy)"`
`  fleet variant 15`
`    "Modified Argosy (Plasma)"`
`  fleet variant 10`
`    "Modified Argosy (Plasma)"`
`    Clipper`
`  fleet variant 5`
`    "Modified Argosy (Plasma)"`
`    "Clipper (Speedy)"`

So I have to think up of every possible way the Modified Argosies would go with Clippers, how often they spawn, other ships I need to consider, how many ships spawn, et c.

Instead, if I could just add the "Modified Argosy (Particle Cannon)" to a list (fleet) of rare modified Argosy variants (or others), I wouldn't have to go to this trouble:
`fleet "rare modified argosy"`
`  fleet variant 2`
`    "Modified Argosy (Twin Modified Blaster)`
`  fleet variant 1`
`    "Modified Argosy (Plasma)"`
`  fleet variant 1`
`    "Modified Argosy (Particle Cannon)"`

Then, using that new fleet of ship variants:
`fleet "Medium Southern Pirates"`
`  fleet variant 15`
`    fleet "rare modified argosy"`
`  fleet variant 10`
`    fleet "rare modified argosy"`
`    Clipper`
`  fleet variant 5`
`    fleet "rare modified argosy"`
`    "Clipper (Speedy)"`

Now, this takes into account all three possible "rare modified argosy" variants. It could even be paired with a fleet "clipper" and then all the variants of the Clipper would also be considered.

While the length of fleets.txt may be overall longer, there is far more possible variety and the creation or modification of fleets would take a shorter time. 

### Alternative Approaches

I can't say that there is a better option that would make fleet modification easier. Other than getting the computer to do it for me.

**Comment by Amazinite** [comment]
This is effectively redundant with #4668, which is implemented by #4704. Although that PR is closed, I do intend to reopen it and finish it at some point in the future, and probably sooner rather than alter with the introduction of the various pirate variant ships.

**Comment by bene-dictator** [comment]
Should I close this?
