### ISSUE TITLE
Unintended? drains batteries:  autopilot for "Boarding" action engage Constant-Acceleration, even after reaching top-speed / drains batteries

### ISSUE THREAD

**Issue by jwmh** [endless-sky/endless-sky#8156]
I tested in both the latest stable, as well as the Continuous, App-Images.
Behavior appears identical in both.

### Problem Description

[gameplay/mechanics] 

For example, I'm at least 10 seconds of traversal-time away from:
- ```[Land]``` player taps the [land] key; 
- ```[Board]``` players taps the [board] key.

 I press the key-button;   I let the game's AI autopilot work...

... And my expectation is that the game's AI (whether for Landing or Boarding),

i.e.,
`Engage-autopilot to X location, in-system`

 will **not** continue to constantly fire my engines, 
**if I'm already traveling at maximum velocity**

 for my ship in a straight line directly toward the location-target  (whether a port to land/dock on,  or a ship to board/repair/refuel/etc).

#### Why this is (potentially) bad
An undesired consequence of this behavior,
 is it can drain my ship's batteries 
(depending on configuration).

See attached save-file,
if you want to test this out.

### more context

OK,
there's a couple possible case-studies & maybe ways to fix this.

I don't know if this behavior is intentional, or otherwise.

to reiterate...

### Current behavior:

Continuous-Acceleration action
 uses constant energy from the batteries.

(via either holding the key,
 *or* via the Boarding-Action autopilot/AI.
~~I haven't tested other autopilots just yet~~.)

### Expected behavior:
Ship / AI / Gameplay mechanics,
*after maximum-ship-velocity is reached*,
shall NOT continue to use energy
 **or at least particularly that the AI _[when real-player taps the ```['Board']``` key]_ "should know better / be smarter" than to just drain the batteries for literally no reason.**

So,
 either,

#### Possible Fix #A:
Once maximum-velocity is reached,
the Game AI, while on autopilot (e.g. for landing / boarding),
should *cease* using the 'Accelerate' action in its AI autopilot on the player's behalf...

 and/or

#### Possible Fix #B:
Once maximum velocity is reached in *any* circumstance -- autopilot/AI, or manual/player-key-hold --
the game causes the "Accelerate" action to no longer have any effect.

#### In both case A and/or case B: 

I imagine one possible algorithm for the game-engine to detect could be (but perhaps not the only means-test?)
:
True/False:
1. the ship's current-velocity is in a straight-line, **and**
2. ship has reached maximum/peak velocity along that vector, **and**
3. any active thruster-action is also on that same vector.

THEN:
Cancel said thruster-action.

[put another way:
In that scenario,  where all (3) conditions == true,
(when a ship has reached top-velocity (speed+direction+oriented-thruster-direction) must all match)
]

##### I guess the difference between Fix A vs Fix B is:

Fix A only does it for Autopilot (Land/Board) type actions.
whereas
Fix B calculates it for *every* situation.

The latter would probly add *massive* performance loads....

**The latter, Fix #B, could be true regardless of whether it's the Autopilot/AI, 
 *or*
 the humanplayer manually holding the [accelerate] key.**

_NB.: be sure to handle both forward-thruster, as well as reverse-thrusters!  If they're just running in Reverse-Gear all the way up the street <lol> _ 

### caveats:
So IDK what y'all wanna do about this (*if anything!).

Obviously there are issues that can complicate this easily; 
e.g. weapons or other ship-conditions that affect velocity (direction and/or speed; e.g. weapon-blasts; environmental hazards; etc.).

##### Another caveat B:

Seems like attempting to fix this behavior...

... could easily produce unintended (unforeseen) negative consequences down the road.

##### Caveat D.: possible performance issue 
During heavy combat,
this could get CRAZY intense on the CPU / GPU!
... especially, if (as I'm now thinking down the road / extrapolating further...) folx would inevitably say,
"Well, look, if you're doing that for the Human Player,  then it's obviously an unfair advantage / balance-issue to their ship (assuming a type of "strict mode" play),  if all the non-player ships dont *also* have that!  I mean, assuming there are (or could be in the future!) NPC-ships which are min-maxed, i.e. constant usage of all-systems (engines/shields/weapons) during a battle....
... or during a flight (e.g. coward-merchant personality that runs away...)
...
 could drain their batteries,
thus 
leaving the NPC ship a sitting duck!

IDK
# Question:
What's the current AI / NPC behavior in this regard??

#### Possible beta-test:

A plug-in with an Outfit which modifies ship's AI behavior,
by
 cutting-off all engines whenever the above three (3) conditions are evaluated as == True
?
Could
 be a nice carrot-stick for players to do some QA / beta-testing for this!
(i.e.,
 for folks who heavily min-max / mod their ships out (such that constant-acceleration results in drained batteries)).

Thoughts???

### Related Issue Links

none found,
but there are so many tickets on the topic of "boarding" but unrelated that it's hard to filter thru / find if this is a duplicate or not.

### Desired Solution

see above...

### Alternative Approaches

also see above...

### Additional Context

[profile-and-plugins-save-folder.tar.gz](https://github.com/endless-sky/endless-sky/files/10446081/profile-and-plugins-save-folder.tar.gz)

**Comment by Zitchas** [comment]
Constantly pushing the acceleration after the ship has reached max speed does seem like a problem for battery-only builds. 

While I don't think this will be solved by the PR that improves fighter behavior for battery-only builds, this latter does include mention of calculating flight time and a lot of other battery related AI behavior, so it would probably be useful in improving and/or solving the situation.

**Comment by vitalchip** [comment]
@Zitchas The build I sent you reduces engine thrust as max velocity approaches. Provided your vector is very close to the ship facing. 



 

https://user-images.githubusercontent.com/65342577/213196076-de31376f-3bc7-4a92-8318-eba07ed3ec4e.mov

**Comment by jwmh** [comment]
> 
> Constantly pushing the acceleration after the ship has reached max speed does seem like a problem for battery-only builds.

I so appreciate both your replies!
This is awesome!

Just for the sake of completeness,
point to add:
 Not strictly a problem **solely**
 for battery-only builds,
but also
for any build
 where power-_generation_
 **is_less_than** than that of engine-consumption.

I did this as sorta a bridge between no-generation and ample-generation.

Why?
A: Smaller reactors meet *some* needs,
*and*
take up less outfit-space.

**Comment by samrocketman** [comment]
Your ship would become disabled, experience drag, stop, and you can flag NPCs for help

**Comment by Ferociousfeind** [comment]
Calculating velocity is not very expensive, and we already know max speed. This would not be difficult to implement at all- if the ship is facing within some number of degrees of its velocity vector, and the velocity is at maximum, don't waste energy thrusting.

However, ships are never at their max speed. Really! They asymptotically approach it, but never actually reach it. That's kind of a problem for something like this, which might be naively implemented as "stop if speed == max speed", because speed is always less than max speed.

Also, which angle? 90 degrees? 10 degrees? 1? Both the % of max speed we deem acceptable, and the angle measure we deem acceptable, are arbitrary decisions which would have to be hashed out.

Otherwise, this is a good thing to implement. Those just need to be arbitrarily decided.

**Comment by samrocketman** [comment]
https://github.com/endless-sky/endless-sky/pull/8489

calculates it at 99% of max velocity
