### ISSUE TITLE
Bug: Crew members on escorts should be automatically fired

### ISSUE THREAD

**Issue by macfreek** [endless-sky/endless-sky#816]
**Summary**
Additional crew members are not automatically fired when the flagship is changed. Thus some escorts have additional crew members, above what is required to man the ship and weapons systems. There are some miscalculations and misreportings about the number of additional crew members in escorts. Sometimes, these crew members are accounted for, sometimes they are not.

**Suggested fix**
My suggestion is to automatically fire additional crew members on escorts, when the flagship is changed, possibly after migrating some of them to the new flagship.

**Detailed example**
Let me explain based on the following table of my fleet.

Ship     | Bunks | req'd crew (base) | req'd crew (w/ weapons) | crew
-------- | ----- | ---------- | ---------- | ----
Kestrel (flagship) |  128  |     72     |     76     |  80
Raven    |   13  |      6     |      6     |   6
Raven    |   13  |      6     |      6     |   6
Raven    |   13  |      6     |      6     |   6
Osprey   |   24  |      9     |     11     |  24
Osprey   |   24  |      9     |     11     |  11
Osprey   |   24  |      9     |     11     |  11
Osprey   |   24  |      9     |     11     |  11
Mule     |   43  |      6     |      9     |  10
Manta    |   10  |      6     |      6     |   6
**Total**    |  **316**  |    **138**     |    **153**     | **171**

In addition, I have 146 passengers.

Now, 171 + 146 = 317 people last time I checked. Now if two of my passengers decide to become 'cozy' in one bunk aboard my ship, that's perfectly fine with me. But I do expect some more disipline from my crew members, and from the game source code as well. ;)

The base required crew is what is listed as "required crew" in the configuration of a ship. The "required crew w/ weapons" also takes into account the number of crew required to man all weapon systems.

Note that two escorts have additional crew hired, above what is required. This is because I hired crew when they were my flagship, but I never fired them before changing my flagship.

**Current behaviour**
The bank dialog displays 15600 as salary. This is based on the number of required crew members (including weapon systems), and the additional crew member on the flag ship, minus myself as captain: 153 + 4 - 1 = 156 crew members. Additional crew members on escorts don't get paid.

In the player info screen (brought up by pressing 'i'), when I drag around the ships, the "crew" columns lists the total crew amount for the flagship, but the required crew for all escorts. So in the above fleet, the crew number of a ship indeed changes when I drag an escort in this info screen, making it my flagship. The number of available bunk thus changes too. This means that the "passenger space" can suddenly become negative. The game currently does not compensate for that. _This is the first actual bug._

The Hire Crew screen let's me hire between 0 and 17 (= 316 bunks - 153 crew req'd - 146 passenger) additional crew members. 

So apparently, additional crew members are just ignored in the bank, player info and hire crew screens.

The mission (job board) screen displays: "Passenger space: -1 bunks". Unlike the above, this is the amount based on the actual number of crew (last column), including additional crew on escorts. It is thus perfectly possible to hire more crew and end up with negative passenger space. _This is inconsistent, and the second actual bug._

**Comment by Gkramme** [comment]
That's strange. I thought that bug was fixed already.

**Comment by macfreek** [comment]
I tested with version 0.8.11. There have been earlier bugs (#58 and #159) about negative cargo, but since those were prior to 0.8.11, they're different bugs.

Unfortunately, 0.8.10 and 0.8.11 don't have tags in the source code, so I can't check if it was fixed later.

Feel free to check out the described behaviour yourself. I uploaded the save file to https://pastebin.com/bCQai1uE.

**Comment by Gkramme** [comment]
That is strange. It may be a bug based on selling a ship with cargo in it, and the game automaticaly transmits that to a ship with available cargo space, regardless if it has less space than the total cargo transmitted.

**Comment by Gkramme** [comment]
The extra members bug may be that the game keeps extra members when you change your flagship.

**Comment by endless-sky** [comment]
There are a couple of things going on here:

* You are allowed to take on a mission you do not have space for, if all that is necessary to free up that space is to sell ordinary commodities or fire extra (non-required) crew.
* Bunks free can go negative for a variety of reasons (e.g. because you just sold a ship or a bunk room).
* If a flagship is turned into an escort, it "remembers" how many extra crew it had so that it can restore its crew to that number if it is ever made your flagship again.

The only actual bug here is that the mission panel was basing the bunks free on your escort's "memory" of its full flagship crew complement; that is fixed in commit ad085af.

**Comment by macfreek** [comment]
Thanks for the fix in ad085af!

I now understand that the negative bunk space (like negative cargo space) conditions are taken as unavoidable (e.g. when taking on some missions, or changing flag ships), to pervent too many dialogs that may annoy users. I appreciate that approach.

If this is not yet done, I would only suggest the following check before departure:
- if the number of available bunks is negative, fire as many as possible crew members. Optionally alert the user in a dialog.
- if this is not enough, alert the user that it not possible to depart.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
