### ISSUE TITLE
Documentation: List of key shortcuts

### ISSUE THREAD

**Issue by macfreek** [endless-sky/endless-sky#817]
I would love to see a list of keyboard shortcuts in the documentation, beyond what is already listed in the preferences.

In particular, I would like to see these shortcuts mentioned somewhere:
* Press "I" while landed in a space port brings up player screen, where it is possible to switch main ship, and park ships, even if there is not a shipyard.
* Keep "J" pressed longer to synchronize the jump time of all ships in the fleet.

**Comment by Gkramme** [comment]
I would like to see that too. It was really confusing as a new player.

**Comment by LocalGod79** [comment]
your second point is addressed in the last paragraph of this section in the wiki
https://github.com/endless-sky/endless-sky/wiki/PlayersManual#travel

**Comment by Gkramme** [comment]
It does not actualy say that in the game, so someone who does not know the existance of the github will be clueless on the tips and tricks in the game.

**Comment by LocalGod79** [comment]
while that's fair, my first stop any time i open a new game (especially one like this), is to immediately open the key binding preferences, where there's more than even the wiki...

**Comment by mrec** [comment]
`I` for player info is already listed in Preferences, though as a newbie it took me a while to find it. It's not just while landed, btw; you can use it in space too. Even from the plunder/capture dialog; it's very handy for dumping low-value cargo to make room for better loot.

Preferences does list `J`, but not hold-`J`.

I also haven't seen Shift+Click (to set waypoints in the map) documented ***anywhere***. Only found that by blind guesswork.

**Comment by lehgogh** [comment]
I remember hearing Shift+Click somewhere online (either the ES forums or the Player's Manual).
