### ISSUE TITLE
No place that tells you where to post ideas for story contributions (or other parts)

### ISSUE THREAD

**Issue by TheShadowOfHassen** [endless-sky/endless-sky#8197]
### Location

wiki

### Describe the issue

I want to help with writing story for the game, but nothing tells me where I should start. Do I post an Issue with my story idea do I put it in discussions? I'd rather get feedback and see if my ideas will actually work.

### Expected content

Just point me to the right place (in github please) but if you could clarify that for other people it'd be great.

**Comment by Zitchas** [comment]
Here on GitHub, the Discussions area (under the "Idea" tag) would be the best place to post them. In the past people have used issues, but with the recent introduction of Discussions, things like this would be better off there.

I'm looking forward to seeing what ideas you have to share?

**Comment by TheShadowOfHassen** [comment]
OK Thanks
