### ISSUE TITLE
game crashes when departing Follower

### ISSUE THREAD

**Issue by donotwant** [endless-sky/endless-sky#82]
I sold my 2 Scouts and bought a Mule and a Dagger to go with it.
Departing crashes the game
If I sell the Dagger I can Depart in the Mule and if I sell the Mule I can Depart in the Dagger
Snapshot here:
http://s000.tinyupload.com/?file_id=45621349225812249228

**Comment by endless-sky** [comment]
That should be fixed by commit 06267b6.
