### ISSUE TITLE
Blast radius missiles used to kill without angering

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#821]
I don't know if it's really an issue or not (hehehe,) but:

If you use a missile with a blast radius (nuke, torpedo, heavy missile, etc) and shoot it into an asteroid near an enemy, it can damage them, even kill them, without angering anybody. It only angers enemies if you select them and they're caught in the blast, but if they aren't selected, they aren't mad that you just fired a nuke at them...

**Comment by Gkramme** [comment]
Considering this could also unintentionally hurt your allies and turn them against you, I don't think that this is a bug and it shouldn't be changed.

**Comment by jafdy** [comment]
although this is a bit of a problem I can't think of a way to change it with out friendly ships turning on you if they get clipped by the blast. But I'm no programmer so it may be doable.

**Comment by masterpierround** [comment]
You could keep track of the damage you've dealt to a ship. If it's greater than a certain amount (a nuke, probably, or many, many torpedoes) and you manage to disable that ship, then other ships of that government get angry. This could cause problems with using nukes though, as a single nuke that clips an ally ship would turn them hostile.

**Comment by endless-sky** [comment]
It's intentional, just because it's less problematic than having allies get mad at you right in the middle of a major fight just because one of them got caught in your heavy rocket's blast area.
