### ISSUE TITLE
Bug: "on enter" mission trigger does not function if you entered system by wormhole

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#822]
not really sure that this is a bug (or if it's been reported before), but the functionality is desired, and using the wormhole as a stopover was unsuccessful as well.

(edit: mission waypoints appear to fall into the "on enter" problem, as well)

**Comment by endless-sky** [comment]
I've added a fix for this in commit eb73f61. Although, I suppose I should also consider whether "on enter" should also trigger when leaving a planet (say, for a mission that wants to show an "on enter" as soon as you leave the planet that offered the mission).

**Comment by endless-sky** [comment]
And, in commit e311dd6 I've added support for "on enter" conditions to also trigger when you leave a planet.
