### ISSUE TITLE
[BUG][severe] NPCs cannot hyperjump

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#8221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All non players no longer hyperjump. They *arrive* from hyperspace, they take off, and mine, and fight. And when it comes time for them to leave, they do their usual spin around and come to a stop, then point the direction they want to go.... And nothing happens. They just sit there, drifting every so slightly. 

As a "possibly related" problem, I jump around, and found two freighters fighting off a sparrow pirate. They defeated it, and then then went and started trying to park on the sun. Just sitting there, back and forth as if trying to land or something.

### Steps to Reproduce

1. Load a pilot (or create a new one)
2. Take off
3. Observe NPC ships (haven't checked mission ships, focused on regular spawns)
4. Note that they act mostly as normal, except when they go to hyperjump.

### Expected Behavior

Ships should be able to hyperjump out of the system like normal.

I don't know what's happening, but #8220 seems to fix this.

### Screenshots

![2023-01-27 NPCs don't hyperjump](https://user-images.githubusercontent.com/32169904/215112186-9d5c14f4-9e92-4f5b-aa63-cafa80b3ca4c.png)

### Link to save file

Brand new pilot. (originally discovered on older pilot, retested on brand new one)

### Operating System

Windows 10 Pro

### Game Source

GitHub Releases

### Game Version

0.10.0 alpha, continuous release triggered by 0505ec7

### Additional Information

![Continuous build used](https://user-images.githubusercontent.com/32169904/215112906-358715b0-bc12-4e57-adcb-f8c45cce2441.png)

I downloaded the windows zip file from here, verified no plug-ins used (not even high-dpi), and created a new pilot.

**Comment by Zitchas** [comment]
Multiple people on discord have verified this problem, and 8220 does appear to be a fix for it.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/3b2085a4f904b6380b76441bc24492cbc3f1241a
