### ISSUE TITLE
Missing documentation for "apparent payment"

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#8227]
### Location

wiki

### Describe the issue

The "apparent payment" attribute is not documented for missions on the github wiki.

### Expected content

It should say that "apparent payment" is used for sorting jobs that don't have a payment / have a different payment than what's in the description.

**Comment by warp-core** [comment]
![image](https://user-images.githubusercontent.com/20605679/215194566-40305d69-3fda-4d7e-8f59-1e255e2049ab.png)

**Comment by tibetiroka** [comment]
I think that's about right, yes. Maybe it's worth mentioning that `<payment>` doesn't show the apparent payment, even if there isn't any actual payment.

**Comment by warp-core** [comment]
@tibetiroka I've updated the wiki with the details of the text replacement support for "apparent payment" now.
