### ISSUE TITLE
NPCs unable to board cause traffic jam

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#8228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some NPCs (notably, Remnant ships) appear to be too fast to stop and position themselves over small disabled ships accurately, and effectively get stuck in an infinite loop of boarding attempts. This issue causes a whole lot of ships to effectively get stuck in a small corner of space, doing nothing of importance.

### Steps to Reproduce

1. Go to a Remnant system
2. Wait for a hostile raider to spawn in, and get disabled
3. Wait for them to group up on the disabled fighters

### Expected Behavior

NPCs should either thrust more carefully, not have so powerful engines, or disengage from their boarding attempts.

### Screenshots

![image](https://user-images.githubusercontent.com/68112292/215203466-73208ab5-a608-4015-a78b-27ee3d73c212.png)
![image](https://user-images.githubusercontent.com/68112292/215203522-1d6dbc1f-97a7-4762-ab7e-d99d7e821125.png)
![image](https://user-images.githubusercontent.com/68112292/215203553-292d6052-b743-4a16-9fe3-67ee2c9c3f75.png)

### Link to save file

[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10710384/Test.Pilot.txt)

### Operating System

EndeavourOS (kernel: 6.1.8-zen1-1)

### Game Source

ESLauncher2

### Game Version

3b2085a4f904b6380b76441bc24492cbc3f1241a

**Comment by Zitchas** [comment]
As of the latest continuous today, this continues to be a problem, and #8305 doesn't appear to have fixed anything.

Does anyone know why this appeared? This didn't happen until fairly recently, so it seems that something must have changed in the code that handles movement and/or boarding.

**Comment by tibetiroka** [comment]
#8305 only fixes it for fighters/drones taking off from a planet, it doesn't affect regular ships, nor fighters/drones released from ships.

I can confirm the issue in 0.9.16.1, so this was likely introduced quite some time ago.

**Comment by tibetiroka** [comment]
I can confirm the issue in 0.9.15, although the exact behaviour seems slightly different. In 0.9.14 it doesn't happen, because the ships that do board successfully destroy the fighter, so there isn't a chance for other ships to group up.
