### ISSUE TITLE
Code Enhancment: Allow Special Characters

### ISSUE THREAD

**Issue by GalacticRuler** [endless-sky/endless-sky#824]
Eg °, ∞, ╩,Φ and more. There's no support that I can tell for these in the name system currently used. I attempted to use a special character in a system name and it just dumped in a sort of "Purgatory".

**Comment by db47h** [comment]
The fonts are pre-rendered, and only the first half of the ISO charset. So yes, anything that's not visible on the face of an English American keyboard won't display. For now. I believe this is on the roadmap, but the game would need a new font engine for this.
