### ISSUE TITLE
Incorrect indentation on wiki

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#8247]
### Location

wiki

### Describe the issue

https://github.com/endless-sky/endless-sky/wiki/MapData#planets has a line indented with four spaces instead of a tabulator.

![image](https://user-images.githubusercontent.com/68112292/215345567-a670a0fa-82fa-4eb4-9b59-936231924ba5.png)

### Expected content

A tab instead of four spaces.

**Comment by warp-core** [comment]
I have replaced every instance of four consecutive spaces (that VS Code could find) in the wiki with a tab.
