### ISSUE TITLE
Error reporting is erroneous

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#825]
recently looked at my errors.txt for the first time, and found a new plugin debugging resource (it's all been trial and error for me until now - surprisingly few actual problems)

it seems that the engine produces errors even though it processes and handles properly some "to offer" trigger condition expressions - ie. has > # credits, "net worth" produce errors. (i realize that this is sloppy coding, and have rectified it)

additionally producing errors, but being processed properly,  "and"/"or" and associated "has random > # " conditions - which would just be "random > # " when at the first indent past "to offer", but won't function after "or"/"and" trigger condition modifiers (so, random condition req's contained within "and"/"or" require "has" to function, but reports an error)

i suppose this is the true issue

hope that makes sense

**Comment by GalacticRuler** [comment]
It also seems to glide through missing closing "

**Comment by endless-sky** [comment]
Can you post the exact error messages and the code that caused them?

The error check will indeed report some things that the parser is able to handle (like missing closing quotes); the idea is to report those things just in case it means that you left something out.

Note that `has "key" > <value>` is incorrect syntax and will not work; that condition will probably be ignored.

**Comment by LocalGod79** [comment]
i arrived at "has 'key' > <value>" for at least these two conditions (random - after or/and - and credits - always) through trial and error (when proper syntax produces no errors or mission offer) - i recognize that it is poor syntax and shouldn't work however, the fact remains that it seems to be the only way to check these two conditions under these circumstances...

feel free to try creating a mission with;
to offer
 credits > 0
 or
  random < 100
  has "anyothercondition"

*should* offer *every* time...

the UPMissions.txt file is responsible for all of the errors below, and can be found in the data folder here (it's a 100K+ text file - didn't think you wanted me to paste it here);
https://drive.google.com/folderview?id=0B92_vuqiHabWX3pvYzFYOTFyTXM&usp=sharing

below is a copy of my errors.txt, which has the condition expressions as they are (because they work.)
-----------------------------------------------

Unrecognized condition expression:
  mission OS3
    to offer
      has > 150000000 credits

Unrecognized condition expression:
  mission OS4
    to offer
      has > 10000000 credits

Unrecognized condition expression:
  mission OS6
    to offer
      has > 5000000 credits

Unrecognized condition expression:
  mission OS12
    to offer
      has > 20000000 credits

Unrecognized condition expression:
  mission OS13
    to offer
      has > 20000000 credits

Unrecognized condition expression:
  mission OS14W
    to offer
      has > 150000000 credits

Unrecognized condition expression:
  mission OS14F
    to offer
      has > 150000000 credits

Unrecognized condition expression:
  mission OS15W
    to offer
      has > 75000000 credits

Unrecognized condition expression:
  mission OS15F
    to offer
      has > 75000000 credits

Unrecognized condition expression:
  mission OS17A
    to offer
      has > 300000000 credits

Unrecognized condition expression:
  mission OS17V
    to offer
      has > 300000000 credits

Unrecognized condition expression:
  mission OS17W
    to offer
      has > 300000000 credits

Unrecognized condition expression:
  mission OS18H
    to offer
      has > 75000000 credits

Unrecognized condition expression:
  mission OS18A
    to offer
      has > 75000000 credits

Unrecognized condition expression:
  mission OS18V
    to offer
      has > 75000000 credits

Unrecognized condition expression:
  mission OS18W
    to offer
      has > 75000000 credits

Unrecognized condition expression:
  mission OS21N
    to offer
      has > 100000000 credits

Unrecognized condition expression:
  mission OS22N
    to offer
      has > 100000000 credits

Unrecognized condition expression:
  mission OS21
    to offer
      has > 50000000 credits

Unrecognized condition expression:
  mission OS22
    to offer
      has > 500000000 credits

Unrecognized condition expression:
  mission OS23
    to offer
      or
        and
          has random > 69

Unrecognized condition expression:
  mission OS25b
    to offer
      or
        and
          has random < 68

Unrecognized condition expression:
  mission OS25b
    to offer
      has > 50000000 credits

Unrecognized condition expression:
  mission OS25
    to offer
      or
        and
          has random < 68

Unrecognized condition expression:
  mission OS25
    to offer
      has > 350000000 credits

Unrecognized condition expression:
  mission OS26
    to offer
      has > 350000000 credits

Unrecognized condition expression:
  mission OS27
    to offer
      has > 100000000 credits

Unrecognized condition expression:
  mission OS28
    to offer
      or
        and
          has random > 30

Unrecognized condition expression:
  mission OS29
    to offer
      or
        and
          has random < 29

Unrecognized condition expression:
  mission OSC6
    to offer
      or
        and
          has random < 40

**Comment by endless-sky** [comment]
If a conditional expression is not in a recognized format, it is simply ignored. The result is that the condition is *always* satisfied. So, it will look to you like it is "working," but the reason is because the game simply ignored the conditions it did not understand.

**Comment by LocalGod79** [comment]
i see - as it turns out, the negative payment behaves exactly as outfit removal does, so the intended functionality in the mission exists (and gave me the illusion that the condition check was taking place properly.)

that said, using "has random" after "or/and" condition modifiers does seem to function as intended, since they are used to select either OS23 or OS25, and again OS28 or OS29 at random, and if it were skipped entirely, both missions would be offered.

unless this can be explained as well?

**Comment by endless-sky** [comment]
Well, I can tell you for certain that if the game says it doesn't recognize the syntax, it will just ignore that line of the code:

```C++
void ConditionSet::Add(const DataNode &node)
{
	if(node.Size() == 2)
	{
		if(!Add(node.Token(0), node.Token(1)))
			node.PrintTrace("Unrecognized condition expression:");
	}
	else if(node.Size() == 3)
	{
		if(!Add(node.Token(0), node.Token(1), node.Value(2)))
			node.PrintTrace("Unrecognized condition expression:");
	}
	else if(node.Size() == 1 && node.Token(0) == "never")
		entries.emplace_back("", "!=", 0);
	else if(node.Size() == 1 && (node.Token(0) == "and" || node.Token(0) == "or"))
	{
		children.emplace_back();
		children.back().Load(node);
	}
	else
		node.PrintTrace("Unrecognized condition expression:");
}
```

In particular, any line that has four tokens in it will be ignored. And, any line with three tokens where the middle token is not an operator will also be ignored. And, the "random" condition is set to a new random number every time it checks if a mission can be offered, so what you're trying to do with "random < 68" in one mission and "random > 69" in another won't work anyway.

If it appears to work, it's probably just because the other conditions are making it so that only one of the two missions is offered.

**Comment by LocalGod79** [comment]
i'm no longer 100% on this issue - will investigate further.
