### ISSUE TITLE
Bug: hung when trying to land on Solace

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#827]
when landing on Solace directly after dominating it the game hangs still showing space. best I can tell is that it is at the moment when the game would bring up the planet screen.

**Comment by db47h** [comment]
Does the bug persist when you quit/reload the game? if so, your savegame could be helpful.

**Comment by jafdy** [comment]
No. My best theory was that it had something to do with the fact that I left my ship in a landing cycle through the entire fight so it landed as soon as the planet surrendered but this didn't result when I did it  on other planets. I'm going to try that fight again to see if I can reproduce the problem.
