### ISSUE TITLE
Accidentally Hitting T After Hailing a Planet Demands Ransom Resulting in Escorts Killing You

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#8276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was playing one of the Pug missions where I had a bunch of navy escorts and accidentally hit T after hailing a republic planet. I was significantly outnumbered so my escorts would kill me if I stayed in one place. I ended up editing my save file.

Adding an "Are you sure?" prompt would be nice so I don't demand tribute by accident and get killed by my escorts.

### Steps to Reproduce

1. Hail a planet
2. Bump T
3. Die

### Expected Behavior

1. Hail a planet.
2. Bump T
3. Prompt: "Are you sure you want to commit suicide [Demand Tribute]? No? Ok."

### Link to save file

I didn't want to dig up my original save, so I recreated it on purpose. Same behavior. I just hit T on purpose instead of by accident.

[Josh M_exported~3022-12-02 Hostile Republic.txt](https://github.com/endless-sky/endless-sky/files/10608171/Josh.M_exported.3022-12-02.Hostile.Republic.txt)

### Operating System

Linux Mint 20 (essentially Ubuntu)

### Game Source

GitHub Releases

### Game Version

v0.9.16

### Additional Information

This issue is related https://github.com/endless-sky/endless-sky/issues/5293 but I don't want the key changed, I just want it to be a little harder to accidentally demand tribute.

**Comment by mathwhiz1212** [comment]
There's discussion on this topic in https://github.com/endless-sky/endless-sky/issues/8277

**Comment by UnorderedSigh** [comment]
Fix is here: https://github.com/endless-sky/endless-sky/pull/8875

![confirm-tribute](https://github.com/endless-sky/endless-sky/assets/116329264/13eb115d-14be-4464-a823-2dd54f1f9f97)

**Comment by mathwhiz1212** [comment]
@UnorderedSigh Thank you!
