### ISSUE TITLE
Your Escorts Won't Kill You During the Pug Missions

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#8277]
### Problem Description

I have not successfully made it through the Pug Missions without having a hostile escort fleet. Re: https://github.com/endless-sky/endless-sky/issues/8276 and https://github.com/endless-sky/endless-sky/issues/7617

I don't want to be killed by my escorts or need to edit my save file.

### Related Issue Links

Hostile escorts in general: https://github.com/endless-sky/endless-sky/issues/5154

### Desired Solution

I want to be able to go through the Pug Missions without hostile escorts.

That would likely require either setting the reputation with the Republic and Syndicate really good and resetting it after the missions or somehow interrupting the reputation system for the missions.

### Alternative Approaches

Those are the only solutions I can think of.

**Comment by Hurleveur** [comment]
You just shouldnt be hostile to those governments or the whole mission makes little sense?

**Comment by vitalchip** [comment]
T for talk followed by T for tribute is a bad combination but really Tribute should just be removed altogether to a plugin or at the very least behind a preference defaulted to off.

It's meant as a sort of bonus, for when you've run out of other things to do and you want to test your fleet it's not an 'in game' thing so why is it there, in game?

**Comment by Zireael07** [comment]
> T for talk followed by T for tribute is a bad combination

Agreed

**Comment by TomGoodIdea** [comment]
Even with the tribute disabled by default (which would require Elenchus rework), it's still a bad combination. What about changing the tribute key to "dEmand" or "tRibute", or similar?

**Comment by UnorderedSigh** [comment]
Fix is here: https://github.com/endless-sky/endless-sky/pull/8875

![confirm-tribute](https://github.com/endless-sky/endless-sky/assets/116329264/13eb115d-14be-4464-a823-2dd54f1f9f97)

**Comment by mathwhiz1212** [comment]
@UnorderedSigh Thank you!
