### ISSUE TITLE
not really an issue, but...

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#828]
didn't really know where else to ask:

would you rather have the new marauder ships as variants (e.g. kestrel with new sprites each), or whole new ships (i.e. argosy / mod'argosy)?

i understand that this basically just affects how the ship type appears when selected in orbit (and that my previous submission was premature)

**Comment by Wrzlprnft** [comment]
whole new ships like the argosy->mod.argosy

(yeah... github is being github)
