### ISSUE TITLE
Blender files assets issues

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#829]
I was recreating some chopped together weapons for LocalGod by editing them together in blender, however, as i downloaded the heavy laser, it appeared to be the normal laser. the gimp file is the right one, though.

Can someone double-check this?

**Comment by LocalGod79** [comment]
further, the blaster and blaster turret blender files are not as labeled

**Comment by lehgogh** [comment]
Where did you find the Blender files?

**Comment by LocalGod79** [comment]
they're not here; github charges money for data storage that this project can't make (and assets are getting larger)

https://drive.google.com/folderview?id=0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk&usp=drive_web

**Comment by asl97** [comment]
@LocalGod79 github doesn't force user to use the Git LFS, you can just dump binary file into the repo (at no cost).

the only reason why not to do it is cause it permanently bloat the repo with the binary files.

**Comment by lehgogh** [comment]
Is it okay to use these files to 3D print a ship (Sparrow)?

**Comment by Wrzlprnft** [comment]
as long as you don't sell it it should be okay i guess

**Comment by endless-sky** [comment]
Yes, Blender has an annoying feature where it doesn't prompt you to save before quitting, so there were a few times early on when I failed to save the final model after exporting the images.

@lehgogh, the Blender and GIMP files are under the same license as their final PNG versions, CC-BY-SA 4.0. A quick Google search shows that no one is quite sure what "attribution" looks like in terms of printing a 3D model. I'm not a lawyer, but I'd say that if you 3D print a model, that's a "derivative work" created by you, and you can do anything you want with it (even sell it) as long as you don't try to pass it off as completely your own work (the attribution requirement). If you create computer files using the model and give those to other people, those would have to be under the same license as the original.

**Comment by lehgogh** [comment]
Thanks for the info!

**Comment by endless-sky** [comment]
Fixed the Blender file on Google Drive.

**Comment by Wrzlprnft** [comment]
Fission reactor missing one of those boxes on the left side.

**Comment by LocalGod79** [comment]
A250/A255 engines missing fins for one quadrant of main body (port side).

**Comment by Wrzlprnft** [comment]
since MZ's blender skills transcended this level (or maybe since blender introduced the "do you want to save before exiting" dialog) no more mistakes seem to plop up
