### ISSUE TITLE
Remove "Hai Reveal [C05C] Cleanup Check?"

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#8295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a comment claiming this clean-up mission is not necessary. We need to test if it is necessary, and either remove the comment or remove the mission.

```ruby
# TODO: delete this mission and event before next steam build - just to fix up saves running on continuous.
mission "Hai Reveal [C05C] Cleanup Check"
        landing
        invisible
        to offer
                has "Hai Reveal [C05] Cleanup: done"
                has "Hai Reveal [A11-A] Permanent Fleets: active"
        on offer
                fail "Hai Reveal [A11-A] Permanent Fleets"
                fail "Hai Reveal [B02-A] The Blockade Goes Up"
                event "stormhold unsuppressed"

event "stormhold unsuppressed"
        system "Alcyone"
                add fleet "Small Core Pirates" 400
                add fleet "Large Core Pirates" 600
                add fleet "Korath Large Raid" 50000
                remove fleet "Human Wormhole Guards"

```

I'm pretty sure it can be removed, but I'd rather not have missing fleets or extra fleets by accident.

### Steps to Reproduce

Read `hai reveal 6 end.txt`

### Expected Behavior

No unnecessary clean-up missions that say they should be removed before the release.

### Operating System

Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Game Source

Built from source

### Game Version

5ed683523

**Comment by warp-core** [comment]
Looking at the data, the C05 mission fails the missions this one fails in its on complete and the event it calls includes the Alcyone changes that are in a separate event here.

**Comment by UnorderedSigh** [comment]
I know. I'm testing this now.

**Comment by UnorderedSigh** [comment]
Yes, I can confirm it is safe to remove.

**Comment by warp-core** [comment]
Do you want to open the PR or should I?

**Comment by UnorderedSigh** [comment]
Opening now.

**Comment by UnorderedSigh** [comment]
https://github.com/endless-sky/endless-sky/pull/8300
