### ISSUE TITLE
Hai Reveal [B05-short] The Road Not Taken offers well after Hai Reveal

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#8298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Well after Hai Reveal, I landed on Earth and received a message saying to report to a specific planet or became a fugitive. This mission was part of Hai Reveal and was not supposed to offer as I had already talked to Syndicate Internal Affairs well in the past.

### Steps to Reproduce

1. Load my save file
2. Go to Earth
3. See the mission to go to a specific planet or become a fugitive
4a. Fail the mission and become a fugitive, with a message stating you are one, OR
4b. Pass the mission and nothing happens

EDIT: Incomplete sentence

### Expected Behavior

The mission does not offer if you took the long route.

### Link to save file

[Timmerson Timmy~Pre Glitch.txt](https://github.com/endless-sky/endless-sky/files/10613857/Timmerson.Timmy.Pre.Glitch.txt)

EDIT: The above save file is broken. Use the below one instead

[Timmerson Timmy~Pre Glitch.txt](https://github.com/endless-sky/endless-sky/files/10669427/Timmerson.Timmy.Pre.Glitch.txt)

### Operating System

MX Linux 21 + Devuan Chimaera

### Game Source

ESLauncher2

### Game Version

Continuous

### Additional Information

There is an active PR #8185 which will fix this issue by replacing the mission entirely, but this is still a bug and since it can be fixed earlier, it might as well be.

**Comment by UnorderedSigh** [comment]
@ziproot - if you could test the fix in #8306 and let me know if it works for you, that would be great.

**Comment by ziproot** [comment]
The "fix" clears out every mission after that one as well...

**Comment by UnorderedSigh** [comment]
> The "fix" clears out every mission after that one as well...

It should ensure you can only traverse one path through Hai Reveal part 5. What happens when you try it?

**Comment by UnorderedSigh** [comment]
To clarify: there are two routes through Hai Reveal part 5:

1. You didn't know about Quantum Keystones, so you have to learn about them from smuggled Hai.
2. You *do* know about Quantum Keystones, so you skip that bit.

In either case, you are arrested at the beginning, in one of the two B05 missions.

The bug you're encountering is that the two B05 missions don't exclude each other, so when you finish one route, it is possible to start it again. You get arrested, but nothing more happens since you already finished the later missions.

My fix ensures the B05 missions exclude each other, which prevents you from starting part 5 a second time.

**Comment by ziproot** [comment]
OK, looks like my game is bugged somehow. Any time I load a save and depart it clears out a good chunk of my save file.

**Comment by UnorderedSigh** [comment]
It is glitched. You have an extra "g" at the beginning of one line:

```
g       "Hai Reveal [B03] Contact Giti: offered"
```

**Comment by ziproot** [comment]
OK, I can now confirm that the PR given fixes the bug. Sorry about that.

**Comment by ziproot** [comment]
Done.

**Comment by UnorderedSigh** [comment]
Excellent. Thank you.

Also, thank you for finding this bug!

**Comment by ziproot** [comment]
No problem!
