### ISSUE TITLE
Departing from Longjump crashes after the first official FW fight

### ISSUE THREAD

**Issue by Shadowscall** [endless-sky/endless-sky#83]
I was on Longjump after trying to find Katya when the Republic took Kornephoros and it tells you to go back to Longjump. I did and I met with the leaders and I repainted my ship and then I got a notification about the Republic attacking Longjump. I took off to help and we won the fight. I then landed on the planet again. However, now whenever I try to Depart the planet, the game crashes. Also, another quick question, is it possible to leave ships on a planet, like for example I have some  freighters in my fleet but I obviously don't want them with me when I go pirate hunting. I tried telling them to hold position in another system while I take my combat ships with me and that works, however if at any point I tell my fleet to gather around me or anything, the freighters also want to do it and they jump to the system I am fighting pirates in.
This is the problem signature it gives when the game crashes, if it helps:
Problem Event Name:	APPCRASH
  Application Name:	EndlessSky.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	EndlessSky.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	000000000002e34d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	c988
  Additional Information 2:	c988a77befb2bca821889d36c85f1161
  Additional Information 3:	f001
  Additional Information 4:	f00189f4c304332a1260ad12ceb46791

I have tried closing and relaunching the game numerous times and it crashes every time I press Depart. I also had boarded and captured a disabled republic fighter after the fight but before I landed on Longjump and I have no fighter bays or anything. I thought Longjump had a shipyard so I was just going to sell the fighter there, but it does not so I could not sell it.

**Comment by endless-sky** [comment]
I think this may be the same bug as #82, related to special ships carrying fighters. If you built from source, grabbing the latest from Git should fix it; otherwise, I'm going to try to push out a bug fix release by Tuesday night.

**Comment by Shadowscall** [comment]
Thank you for doing that. On an unrelated note, I was wondering, is it possible to leave ships on a planet, like for example I have some freighters in my fleet but I obviously don't want them with me when I go pirate hunting. I tried telling them to hold position in another system while I take my combat ships with me and that works, however if at any point I tell my fleet to gather around me or anything, the freighters also want to do it and they jump to the system I am fighting pirates in.

**Comment by endless-sky** [comment]
In the "view player info" panel (which is mapped to the "i" key by default), when you are on a planet you can click on a ship and click the "Park" button. Or in the main info panel (the one listing all ships in your fleet) you can click "Park All" or "Unpark All." You do not have to pay for crew for a parked ship, and when you unpark it, as with any "lost" escort it will try to fly to where you are.

**Comment by Shadowscall** [comment]
I wanted to do a quick update on this issue. I parked my fighter on the planet and then I was able to take off and play the game.

**Comment by endless-sky** [comment]
This should be fixed in release 0.8.2.
