### ISSUE TITLE
enhancement: firing ion damage

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#830]
i'd like to propose a new potential balance point for weapons - shooter takes ion damage on firing.

it might be little bit like building a battery/capacitor attribute into weapons (which i understand is already possible), except the effect is diminishing (or stacking in the case of rapid fire or beam outfits).

i suppose this could be applied to engines as well.

i think better than half the code should already be there.

thoughts?

**Comment by endless-sky** [comment]
It would be a sort of cool effect, but in terms of mechanics it's not significantly different than just giving the weapon a higher firing energy. And, it would be annoying that the weapon has an energy cost that will not show up in your ship's energy usage tables.

**Comment by LocalGod79** [comment]
i did understand that it would not be significantly different than adding more firing energy, and that it would not show up in the usage tables (and be annoying as a result).

that said, the annoyance would make it a pretty effective balance point, wouldn't it?

e.g. - i've created a power plant that produces tons of energy and very little heat at idle.  it also provides the thrust of A120/A125, which while in use produces twice the heat of those engines.  so, effectively, i've made the powerplant only generate tons of heat while thrusting.

e.2.g. - a mass driver weapon i've built claims in the weapon description that it does 1800+ shield damage per shot, but if the target is just range 500, that figure is closer to 200.

the shift in the expected sources/timing of balance attributes can drastically alter the efficacy of an outfit under different circumstances - beam laser and energy blaster are virtually equal, despite drastically different numbers on paper.
