### ISSUE TITLE
Can't change flagship

### ISSUE THREAD

**Issue by codrus** [endless-sky/endless-sky#8315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my ship list window (aka 'i' menu), dragging my flagship down to a lower spot does not change my flagship to the top ship. My flagship line remains yellow as well and can't be changed.

In the shipyard or outfitters windows I see no option to sell any of my escorts, nor can I drag and drop anything. Only my flagship is shown on the far right and while I can drag its icon around, it doesn't drop anywhere that does anything.

I've tried holding the ctrl key while clicking on all possible places and that doesn't seem to do anything other than provide the option to sell bulk amounts, which has no use since only my flagship is shown...

I see no way to sell any of my escorts, nor can I select any (other than to park them) in order to sell one or their outfits...

### Steps to Reproduce

See above.

### Expected Behavior

I should be able to switch flagship to some other ship, and I should be able to sell my escorts and/or their outfits.

### Screenshots

![cant-change-flagship](https://user-images.githubusercontent.com/212144/217063415-57c9c650-c054-4e25-ba87-991fdfa4bc45.jpeg)

### Link to save file

Not sure where the save file is. Installation via Flatpak...

### Operating System

Ubuntu 22.04 (using a flatpak for game install)

### Game Source

Other (please describe)

### Game Version

0.9.16.1

**Comment by warp-core** [comment]
It looks like all your other ships are in a different system.
You are in Zubeneschamali, they are in Phecda (and most of them are parked.)
Try unparking them (select them the unpark button at the bottom, or use the park/unpark all button to park or unpark all of them at once), then take off and wait for them to get to you (there'll be icons in the bottom left corner of the UI for each ship including what system they're in if they're not in the same system as you), then land again.

**Comment by codrus** [comment]
You are correct, that was my problem. Thank you for the help!

This ticked can be closed.
