### ISSUE TITLE
Documentation: 'apply' and 'branch' conversation condition triggers

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#832]
are apparently undocumented in the CreatingMissions page of the wiki and are an extremely powerful story multi-threading tools.

people hoping to create content for E.S. *need* to know about this feature.

**Comment by endless-sky** [comment]
They're described in the [writing conversations](https://github.com/endless-sky/endless-sky/wiki/WritingConversations) wiki page. (Which is mentioned in the page on creating missions, in the section on conversations.)
