### ISSUE TITLE
New outfit 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#833]
outfit "Battle Exoskeleton"
	category "Hand to Hand"
	cost 10000000
	thumbnail "outfit/unknown"
	"mass" 3
	"outfit space" -1
	"capture attack" 15
	"capture defense" 3
	description "If you are having trouble taking over enemy ships without casualties, you probably need a bigger gun . . . or tougher crew. This heavily armed military exoskeleton will allow you to take even the largest ships with ease."

Its ready to go directly in to the game but it may need some rebalancing first. note the price (10m) and the outfit space before dismissing it. I created in an attempt to create a way of getting Quarg ships without making capturing for profit to easy. I outfitted a Bactrian for max capture power including this and got a 76% chance of caping a Skylark.

**Comment by lehgogh** [comment]
Perhaps increase mass to 3-5? Exoskeletons would probably be heavy, even if they don't take up much space

Also, in the description, there should be a comma after "casualties" (first sentence).

**Comment by LocalGod79** [comment]
why are we trying to further break an already broken game element?

**Comment by jafdy** [comment]
@lehgogh good idea i'l edit that in (mass increase form 1 to 3)

@LocalGod79 to be able to buy 2 of these you need 20m, that is more than most basic ships in the game. for the effect to be noticeable outside of fighter to fighter combat then you will probably need at lest 100 costing around 1B credits. When you have that sort of cash caping a 5-10m ship will barely register. Also the size and mass of the thing will mean that you are basically be building a ship around using this outfit.

**Comment by LocalGod79** [comment]
you didn't answer my question: if capture/plunder is already causing problems, why even make outfits that make it easier, regardless of their balance points?

**Comment by lehgogh** [comment]
@LocalGod79 I previously suggested in a different issue making ships deprecate 20% instantly as soon as you depart (but not if you buy a ship and sell it back before you leave the planet). This would help begin balancing capturing ships (but not plundering).

**Comment by LocalGod79** [comment]
so your suggestion is based on another, as yet unimplemented, suggestion?

i don't want to get into a big thing about this - i really don't have time
- so i won't say anything further than this:

let's work on what's here, and worry about crossing bridges when we get to
them.

**Comment by jafdy** [comment]
The problems you have mentioned are fair points but (if I remember correctly) they are mostly in relation to the caping of very small ships along with reactor plundering. As this will only effect caping then reactors are a mute point and as it is cheaper to get a bigger ship then to buy 1 of these and that by the time you can get several one larger ship won't make much difference I thought  that it would only be good for getting ships that you normally can't.

**Comment by lehgogh** [comment]
@jafdy I agree with @LocalGod79 that we should worry about balancing the existing system first. Also, it's "moot", not "mute".

**Comment by jafdy** [comment]
I'm amazed that's my first spelling mistake. 
I was explaining my thought process as to why it would not further unbalance the system. The intention  was to get a way of getting quarg ships and republic capitals without needing to hack the game. 
Even so i'm inclined to agree with @LocalGod79 on his last statement.

**Comment by lehgogh** [comment]
Besides, if I'm thinking correctly, we *need* Quarg gear to cap/kill Drak ships, once they get added.

**Comment by jafdy** [comment]
I never thought of that but yes your probably right. For the time being I think we should try to get it to the point where it can be put in the game for everyone to use.

**Comment by LocalGod79** [comment]
no, not probably right - *if* war with the drak is a part of the grand scheme, then we're probably not their only enemies, and the user will get their help in that story arc.

it is highly doubtful that capturing korath world ships and quarg ships (which aren't even theirs, if i understand correctly) is going to be a necessary storyline function, especially without also providing means to do so (which the creator of that arc will provide.)

when someone says "hey, i need an outfit that you'd have to specialize a bactrian to get 75% cap odds on a skylark - help, please" - *that's* when this discussion needs to take place.

otherwise, this outfit belongs in a plugin "where it can be put in the game for everyone (who wants to) to use"

**Comment by jafdy** [comment]
If you don't want to use it then don't.
But for me I would like to have some way of getting these great looking and very tough ships in to my fleet.

**Comment by LocalGod79** [comment]
in case you didn't notice, this is where development of Endless Sky takes place.

not so much 'plugins designed to work with the Endless Sky engine.'

you are watering down actual content creators efforts to ensure maximum functionality of the Endless Sky engine, content creation wiki, and existing content with proposals based on other unimplemented proposals for outfits to accomplish personal goal tasks.

i believe the google group or steam discussion is a more appropriate means to distribute/discuss this kind of content.

please close this and any other irrelevant issues you have open, so that people working to solve existing problems don't have as much nonsense to wade through.

**Comment by jafdy** [comment]
Charming.

**Comment by jafdy** [comment]
The implication of saying that this and things like this belong in plugins is that the only outfits, maps, missions, ships and so on that are ever added to the main game are ones made by @endless-sky. Is that what you mean? If it is it would completely defeat the point of an open source game.

Most of the new outfit ideas on here are just that, ideas, but I am proposing something that can be put in _now_ and that would not be a major change in the balance. I accept that it is not yet perfect, it is hard for one person to create a good and well balanced input.

**Comment by endless-sky** [comment]
A lot of people have proposed outfits that make capturing easier, but as others have said, it's already an overpowered game mechanic.

My long-term plan is that there will eventually be mid-tier ships and technologies in between humans and the Quarg. For example, in 0.9.0 (which could still be a month or two out) there will probably be a way to buy Korath World-Ships, which hold a ton of crew and would thus greatly increase your odds of capturing ships.

**Comment by jafdy** [comment]
@endless-sky you are alot better at saying someone is wrong than @LocalGod79.
Fair enough I still think it is a good idea but I can see your point. I recon that if you can set the cost high enough you could stop it from over balancing the mechanic.

**Comment by Hyratel** [comment]
Per the commentary on "not noticing 5-10m cred ships", with a fleet consisting of 8 each Leviathans and Falcons, all outfitted for Capturing, with maximised Atomic engines and Heavy Lasers+, there is effectively zero risk to the player/Player Fleet in performing Bounty-based capture trawling, even on High Threat bounty targets.

**Comment by LocalGod79** [comment]
as long as you're referencing #828 , make sure you see #831 - actual collaborative content contribution

**Comment by jafdy** [comment]
I think this thread has just about come to an end, we'll have to see what 0.9 brings. I'l leave it here if you want to use it or add it.
