### ISSUE TITLE
Documentation: CreatingOutfits: effects

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#837]
the wiki has a fairly complete CreatingOutfits page, but does not provide hopeful content creators with instructions for making effects to terminate their projectiles.

specifically, a section defining the following should be sufficient (as other attributes seem to be shared with projectiles);
• random angle
• random velocity
• random spin
• velocity scale
• random frame rate

**Comment by endless-sky** [comment]
There's now a [wiki page](https://github.com/endless-sky/endless-sky/wiki/CreatingEffects) on creating effects, and the page on creating outfits and weapons links to it whenever effects are mentioned.
