### ISSUE TITLE
Pug ships at Pug Iyik still speak human language

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#839]
When you travel to Pug Iyik, you find Pug ships. And they talk about "bringing peace", in the human language. When you land on Vara Pug and grab a Pug's arm, the text says "it begins to babble in a language you do not know".
Inconsistencies.
Thoughts?

**Comment by endless-sky** [comment]
I suppose I could have them be a different Pug faction, or change the landing mission. What I was thinking is that sort of like the Hai, some of them speak your language and so do all their ships, but the locals on a given planet might not.

**Comment by jafdy** [comment]
If only some of the pug on planet speak your language then you would expect one (or more) of them to come over to get rid of you.
