### ISSUE TITLE
Sound does not play from plugins.

### ISSUE THREAD

**Issue by KAWilley** [endless-sky/endless-sky#84]
I've run into an issue with plugins and sound; if I put the sound directly into the base directory of the game, it plays fine, but if it's in the plugin subfolder it simply fails to load the sound and nothing happens.

(See: https://groups.google.com/forum/#!category-topic/endless-sky/pNbDJBiRtYE)

**Comment by endless-sky** [comment]
Thanks for the bug report! This is fixed in commit 918def7, which will be included in the next bug-fix release (hopefully on Tuesday).

**Comment by endless-sky** [comment]
If you get a chance, can you check if sounds in plugins are working for you now in release 0.8.2? Thanks!
