### ISSUE TITLE
Adding piercing to various weapons

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#841]
We've added the piercing attribute in #772, but we haven't used it yet. Perhaps beams could have 2.5-5% piercing, and the ion cannon (and other ion weapons) 5-10%? (The exact numbers are up to you guys.)

**Comment by DingusShingleton** [comment]
Well, I'd love to test this since I largely contributed to the concept, but I'm not entirely sure how I would go about doing that. Do I have to download modified game files to tinker with it? I've messed around with adding custom outfits to the game, but that's about it.

**Comment by lehgogh** [comment]
You can just use a plugin. The attribute is already there, so you only need to edit `weapons.txt` and add `piercing` followed by a number 0-1 (0-100%).

**Comment by DingusShingleton** [comment]
It's in 0.8.11? I didn't realize that. Ok!

**Comment by lehgogh** [comment]
@DingusShingleton Whoops; I forgot that we haven't released the update yet. You will need to download the repository and follow the build instructions detailed in the wiki.

**Comment by DingusShingleton** [comment]
...I knew it! :D Ok, I'll dive into that tonight probably.

**Comment by Hyratel** [comment]
so what does Piercing damage /do/? When I saw the post title, my first thought was "does it add a possibility to kill crew?"

**Comment by DingusShingleton** [comment]
It ignores a (usually very small) percentage of shields, and directly damages the hull. For the vast majority of weapons, it would be such a small percentage that it wouldn't really affect a single combat. That is, yes you will take hull damage all the time, but it will only really add up to anything significant if you are fighting for a very long time without landing.

**Comment by DingusShingleton** [comment]
So I managed (seemingly) to download all the libraries and Code::Blocks, and Build and Run the endless-sky-master that I dl'd from here, and it is up and running... but I can't seem to find any evidence of piercing. I added it to some weapons within the weapons.txt inside endless-sky-master, but it doesn't seem to be working. 

I should add that I am in way, way over my head right now, having never touched any kind of coding beyond basic HTML in high school (lol). So, yeah. Is there some key detail that I am missing perhaps?

**Comment by lehgogh** [comment]
If shields are up and the shield damage is lower than the shield health, then (100 * piercing value)% of the shield damage will be dealt to the hull. The remainder will be dealt to the shields. For example, if a weapon deals 100 shield damage and has the attribute `piercing 0.25`, then it will deal 75 shield damage and 25 hull damage (assuming the shields have at least 100 health).

@DingusShingleton Did you specify the attribute as `piercing 0.25` (as an example value)? If not, how did you specify it?

**Comment by DingusShingleton** [comment]
Aha, I figured it out. I had entered "Piercing"-- with the capital P. I switched it to lower case and now it's working fine. A key detail indeed haha. Thanks for the help

**Comment by lehgogh** [comment]
Thanks for testing it. I haven't actually been able to get Code::Blocks to find my installation of SDL2 on Windows, but I'm glad it's working for you.

**Comment by LocalGod79** [comment]
how exactly do you give a weapon/munition the piercing attribute?

actually, an example weapon in a .txt file posted in the google group would go a long way to filling the gap until the weapons wiki is updated.

**Comment by DingusShingleton** [comment]
In weapons.txt, adding

`"piercing"` .01

to a weapon's attributes will give it 1% piercing, for example. Note that you need to download and compile the current development version in order to do this, ie *not* version 8.11 that is on steam.

**Comment by LocalGod79** [comment]
it seems all the 0.9.0 branches have been recently merged, i expect an indication that a new release is imminent.

the Mass Driver and Inertia Buffered Slug outfits in my plugin required this attribute (i've always felt it was incomplete) - the former as a part of weapon damage, the latter as a balance point (ammo should cause a small - amount of hull damage per minute while flying, which of course can be remedied by firing it)

**Comment by LocalGod79** [comment]
i think these numbers are probably a good starting point - perhaps they could stand to be higher, even.

the way i see it, better to be high, and have the community feedback their outrage (and make adjustments), than too low and get a trickle of bug reports "when i fly around for long periods of time, my hull gets damaged a tiny bit".

> We've added the piercing attribute in #772, but we haven't used it yet. Perhaps beams could have 2.5-5% piercing, and the ion cannon (and other ion weapons) 5-10%? (The exact numbers are up to you guys.)

**Comment by endless-sky** [comment]
I think I would prefer to have piercing be a special ability that only a few weapons have, rather than something that many weapons have in tiny amounts.

In particular, I really like the idea that there are things the player does not even know the engine supports, until they discover certain alien territories: "Wait, why are there sparks and my weapons won't fire? Wait, how is that beam damaging my hull when my shields are still up?" etc. That way, new species are not just an incremental step in technology, but can have completely new capabilities.

**Comment by DingusShingleton** [comment]
That's understandable. Honestly I was surprised that people were as open as they were to the idea of baseline piercing when I suggested it. I tested it with 1% on every weapon, and it really didn't change much. Anything that did enough damage to affect your hull would just blast you out of the sky anyway.

I think your approach makes plenty of sense

**Comment by lehgogh** [comment]
@endless-sky, that seems like a good idea for future races.
