### ISSUE TITLE
Steering controls not functional in 0.10.0

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#8419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

(4) and (6) keys on the number pad do not steer the vessel. (8) and (5) work as expected.

### Steps to Reproduce

Load any savefile to verify.... or start a new game.

### Expected Behavior

That I'd, you know, not be limited to a straight line.

### Operating System

Ubuntu 21

### Game Source

GitHub Releases

### Game Version

0.10.0 (just released)

**Comment by warp-core** [comment]
Is your ship turning towards your mouse cursor?

**Comment by Hecter94** [comment]
Works for me, using the Num4 and Num6.

**Comment by movingpictures** [comment]
> Is your ship turning towards your mouse cursor?

Yes.....

**Comment by warp-core** [comment]
Use right alt to toggle that off.
You can change the key for it in the controls panel.

**Comment by movingpictures** [comment]
Well, for some reason, the right-alt wasn't working. Problem solved - but if I (a fairly seasoned player) can get caught on that, I suspect others will as well.

**Comment by samrocketman** [comment]
I recommend we do the following.

- Keep left alt shortcut
- Remove toggle behavior (right alt) completely.
- Surface a preference for mouse control a player would have to turn on via preferences UI for “always on” mouse control.
- If the preference is on we launch a tutorial for the player.  Explain the mode, controls, etc so there’s no hidden behavior by mistake.

@movingpictures how does this sound?

**Comment by movingpictures** [comment]
> @movingpictures how does this sound?

Yeah, the idea to toggle that as a preference makes sense. Tutorial also makes sense - like I said, this caught me quite by surprise.

I will leave it to others as to when to close....

**Comment by IsocratesGrey** [comment]
I wanted to add on something here, it seems like on load it automatically turns on mouse control even if it was off when you closed the game. Is that happening to anyone else?

**Comment by samrocketman** [comment]
Looking at the game code looks like it uses the preference to determine mouse turning even for hold.

Do recall holding left alt and exiting the game (such as alt tab)?  In that case, hold-alt would cause the preference to persist.

We should probably change the behavior to not explicitly set the preference when left alt is held down.

**Comment by IsocratesGrey** [comment]
> 

Yes, it looks like it's when I've used alt-tab to go to other windows open, or alt-f4 to close the app that it defaults to mouse control when I re-enter the game.

**Comment by samrocketman** [comment]
We'll probably want to move mouse-hold away from setting a preference.  There's no need it should do that.

**Comment by samrocketman** [comment]
@IsocratesGrey this should address the issue you experienced https://github.com/endless-sky/endless-sky/pull/8519

**Comment by samrocketman** [comment]
Also in discord, I shared a patch for using middle mouse click as toggle.  Unfortunately, that can’t be used in key bindings https://discord.com/channels/251118043411775489/285540320823869441/1082537460204056596

**Comment by samrocketman** [comment]
This should be closed when #8620 is merged.  It addresses the rest of the feedback and concerns listed here.

* r-alt shortcut removed.
* mouse control is a preference instead of shortcut.
* If a player enables mouse control on purpose (or mistake), then player will be shown a help tutorial on the feature.
