### ISSUE TITLE
Content/Balance: (Ionic) Afterburners

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#842]
further to #597, both outfit sprites imply that they could be standalone engines, but the game engine does not allow this (requires a standard thruster to be installed) - i feel like their use would be greater if this were the case (as their provided thrust is often much less than the efficiency gains between larger engine steps).

**Comment by masterpierround** [comment]
Perhaps they could be standalone engines for non-hyperspace ships? That could be the reason you can't install them on your bigger ships: they can't handle hyperspace jumps.

**Comment by LocalGod79** [comment]
why would an afterburner generating 99,000+ thrust be incapable of handling hyperspace, but an X1700 ion thruster generating only 21,000 is?

i guess i'm proposing that either they take up less or no engine capacity (hyperdrive and fuel pods don't - this is a modification to those systems as well, isn't it?), or they should be counted when the check for primary thrusters happens on leaving the outfitter.

**Comment by endless-sky** [comment]
The purpose of the flight check is mostly to keep new players from getting stuck. I suppose I could do something like allowing afterburners in place of normal engines as long as the player has a ramscoop. But, the AI would also have to be updated to recognize that a ship has no thrusters and use the afterburners instead, which is a lot of added complication for something that 99.9% of players will never attempt anyway.

Note that the game *will* allow you to create engines that serve both as a normal thruster and as an afterburner, so you could always do that instead.

**Comment by LocalGod79** [comment]
would you be averse to adding tiny thrust figures to the afterburners so that extra checks/AI programming were not necessary?
