### ISSUE TITLE
Pact Recon 3's objective disagrees with description, and may want other reworking

### ISSUE THREAD

**Issue by waterhouse** [endless-sky/endless-sky#8422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Pact Recon 3 mission, the briefing says:
> Once again, you receive a message from Freya Winters. "We have another mission for you," she says, "this one a bit more dangerous. We've heard rumors of a pirate fleet amassing in one of the seldom-visited systems in the Dirt Belt, and we need to know where they are. Interested in helping to track them down? As before, you don't need to fight, just observe them."

And the description says:
> Fly through the <waypoints> systems, searching for a gathering pirate fleet. Report to the Pact on <destination> when you are done.

I visited the Hintar system, finding little, then the Naper system, and found a big pirate fleet there (much larger than any I've encountered in this playthrough).

From my perspective, I've clearly found the pirate fleet, so I should go to Glaze and collect my reward.  However, the mission insists that I visit the remaining two systems first.  Just to be sure, I try going to Glaze and it complains I haven't visited all the systems.  This feels discordant; I roll my eyes at clumsy implementation, sigh, and prepare to do what it asks—and file a bug report.

I would recommend either that the mission's objective be completed by visiting Naper only (perhaps having it get aborted and start a new one upon observing the pirate fleet—perhaps with a text box popup saying approximately "You see a bunch of pirate ships. This must be the fleet Freya was looking for"); or that the briefing and description be changed so that the player understands "I must check all four systems even if I find the fleet in the first system".  The first approach is less work for the player and seems the most natural.

Also, separately, the fleet is sufficiently big and dangerous that I feel like 80k is insufficient.  (The previous mission was 70k to poke your head into each of four pirate systems.)  Note that this mission, if completed at all, must be done before the war begins, so any players actually doing this mission are probably in a shuttle or other very weak ship and may be newbies; I'm in a heavy shuttle with maxed-out plasma engines giving 700 top speed.  The fleet attacks you immediately when you enter the system, unless other non-pirates happen to be there (which is maybe 40% of the time).  Subsequent testing shows that "turning to the side while dodging missiles and fighters as best I can until I'm out of missile range, then jumping" works maybe 85% of the time; with normal shuttle engines I'd expect much less success.  "Hitting the jump key immediately upon entering the system" reliably works, but often by small margins, and I feel like it goes against the "observe" directive from the briefing.

Anyway, suggestions:
1. Raise the pay to 100k, perhaps 120k.
2. Do have a text popup when you enter the system, telling the player they've seen the fleet and they should GTFO.
3. Ensure that there's some hapless civilian ship in system as well, so the pirates (probably) attack it first.  (Maybe code it so they _definitely_ attack it, and incorporate "You see a big pirate fleet plundering a civilian freighter ship" into the popup.)

### Steps to Reproduce

1. Accept the Pact 3 Recon mission
2. Visit Naper
3. Observe that the map still shows that you need to visit the other systems
4. Try landing back at Glaze
5. Observe that the mission isn't completed

### Expected Behavior

That the map, after step 2, would no longer show the required other systems; and that step 4 would complete the Pact 3 Recon mission.

### Link to save file

[Jethro Tull.txt](https://github.com/endless-sky/endless-sky/files/10779044/Jethro.Tull.txt)

(after "step 2" above)

### Operating System

Mac OS Monterey 12.6.2

### Game Source

Built from source

### Game Version

2e713b142198c971ec93a67a998d443082979e73

**Comment by ziproot** [comment]
This brings up a bigger issue with waypoints in general: There should be a way to have indicators without requiring the ship visits that system. Another mission that comes to mind is the Anglerfish one, where taking out the Anglerfish early means you still have to enter Umbral. In the case of this mission, 3/4 could be indicators, with the real system being a waypoint, and in the Anglerfish one, Umbral could just be an indicator.
