### ISSUE TITLE
Ka'het ships sends english hail on the system message.

### ISSUE THREAD

**Issue by binaryspica** [endless-sky/endless-sky#8437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/endless-sky/endless-sky/issues/8211

Same as the closed issue.

### Steps to Reproduce

Go to Graveyard and find out any Ka'het ship.

### Expected Behavior

It must not do this.

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.10.0

**Comment by Amazinite** [comment]
Fixed by #8444.
