### ISSUE TITLE
Mention errors.txt on the CreatingPlugins page.

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#8449]
### Location

Wiki

### Describe the issue

Mention the `errors.txt` file on the CreatingPlugins wiki page: https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins

It's probably obvious to y'all that if your plugin doesn't work, you should check the `errors.txt` file. 

*I didn't know there was an errors.txt file.*

I wasted hours.

### Expected content

**Please double-check the paths for accuracy.**

# Plugin Isn't Working?

If your plugin isn't working, check your `errors.txt` file. Here's where you can find it:

Windows: `%APPDATA%\endless-sky\errors.txt`

Mac: `~/Library/ApplicationSupport/endless-sky/errors.txt`

Linux: `~/.local/share/endless-sky/errors.txt`

If you still have questions, ask in the #content-creating channel on Discord. You could include a link to the Discord here if you post that publicly.

**Comment by TomGoodIdea** [comment]
I think `%APPDATA%\endless-sky\errors.txt` for Windows is better (you don't have to change anything).

**Comment by mathwhiz1212** [comment]
@TomGoodIdea Edited to reflect your suggestion.

**Comment by mOctave** [comment]
This is definitely a good idea to mention. I've never used errors.txt myself, since I also was not aware it existed and have been launching ES from the command line instead (which gives the same debug information), however it appears to be a much more accessible solution for non-programmers.

**Comment by mathwhiz1212** [comment]
> This is definitely a good idea to mention. I've never used errors.txt myself, since I also was not aware it existed and have been launching ES from the command line instead (which gives the same debug information), however it appears to be a much more accessible solution for non-programmers.

I would have been fine with the CLI option, I didn't know that existed either. But as you say, `errors.txt` is more accessible.

**Comment by TheGiraffe3** [comment]
Should this issue be transferred?

**Comment by TheGiraffe3** [comment]
~that's why I mentioned it~ okay, if you say so. Just because of automatic closing.

**Comment by TomGoodIdea** [comment]
https://github.com/endless-sky/endless-sky-wiki/commit/c57cacb86f40b6e22808e72a94bd5260cb3d1fad
