### ISSUE TITLE
Weapon recoil

### ISSUE THREAD

**Issue by Hyratel** [endless-sky/endless-sky#845]
I was thinking about how some of the bullet-based weapons (as opposed to beams) impart kinetic to the target - is it possible to impart kinetic to the firing ship? my reasoning is for, for example - a heavy railgun. massive recoil, sends your ship off course, knocks you back a nontrivial amount, very long refire time, on the order of 0.9-1.5 seconds. main application would be for non-fleet play, eg "i'm flying solo in a bactrian/Dreadnought/Kestrel and I need something that can blow away most anything in a few shots". it might even classify as a  missile-system

**Comment by lehgogh** [comment]
#763?

**Comment by lehgogh** [comment]
TL;DR - It's already supported by the engine and is used by some weapons such as the Particle Cannon. However, most weapons would have so little knockback that it would have almost no effect. Additionally, missiles accelerate under their own power, so they wouldn't provide recoil.

**Comment by DingusShingleton** [comment]
So am I to understand the particle cannon et. al. have knockback specifically coded into them? Or is it dependent on one of the weapon's attributes?

**Comment by lehgogh** [comment]
It's the "firing force" attribute.

**Comment by Hyratel** [comment]
for clarity - is this force imparted onto the Firing ship or the Target?

**Comment by DingusShingleton** [comment]
Firing force affects the ship that is firing, hit force affects the ship that is hit. :)

**Comment by Hyratel** [comment]
Closing because I'm a silly who doesn't know how to read sauce cood.

**Comment by lehgogh** [comment]
Also, if you want a really OP weapon, you could try the Drak Antimatter Cannon (see `drak.txt`).

**Comment by db47h** [comment]
The mass of the ship vs. the mass of any kinetic projectile fired are so disproportionate that the "firing force" is negligible. Well, for any projectile that would be practical to carry in useful quantities and practical to fire.

Suppose that you have a 400 metric tons Clipper equipped with a big a** railgun that fires 10Kg kinetic projectiles at 2500m/s (that's gotta hurt!). Simplifying a good bit, every shot would accelerate your ship by 0.0625m/s in the opposite direction... Nothing that couldn't be accounted for in proper ship design (compensating thrusters, etc.). Same thing for the target by the way: basic kinetic projectiles should not impact significant "hit force" to their target, especially if penetrating the hull.

As for special, space-time bending, alien voodoo projectiles... everything's possible, so it's good that the engine can handle these forces (just don't abuse them ;-).

For more info, see the [Wikipedia article on recoil](https://en.wikipedia.org/wiki/Recoil).
