### ISSUE TITLE
Appimage won't start in Linux mint

### ISSUE THREAD

**Issue by my-T1** [endless-sky/endless-sky#8456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After downloading and integrating the provided appimage neither v0.9.16, v0.9.16.1 nor v0.10.0 do start. My system is Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy with  Kernel: 5.19.0. 
The older version v0.9.15 works like a charm.

When starting from terminal an error message states "execv error: No such file or directory".

### Steps to Reproduce

1. Download Appimage
2. Run and integrate appimage via doubleclick
3. start endless sky either from menu (no reaction) or terminal (see error message above)
4.  execv error: No such file or directory

### Expected Behavior

Game should start normally.

### Operating System

Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy with  Kernel: 5.19.0

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by MCOfficer** [comment]
Probably #7476, please try the fix provided there.

**Comment by my-T1** [comment]
Many thanks. Uninstalling the appimagelauncher helped (surprisingly).
