### ISSUE TITLE
The missions panel should not select the first mission in the list

### ISSUE THREAD

**Issue by db47h** [endless-sky/endless-sky#846]
When on the map view and switching to the missions panel, the first mission is selected by default. More often than not, the destination system is off screen and I tend to wrongly assume the destination for the displayed mission is on the currently selected system. So I end up accepting missions to areas I don't intend to visit.

**Comment by db47h** [comment]
I've been working on a workaround for this (PR incoming):

1. When switching from the map view to the missions panel (that's the biggest source of confusion), auto-select the first available or accepted mission in:
  - the selected system
 - the player's current position
 - along the travel plan (going out)

  If no mission was found, display the missions panel with NO mission selected.

2. When switching from the planet view to the missions panel, auto-select the first available or accepted  mission in:
 - the player's current system
 - along the travel plan (going out)
  
  If a mission was found, auto-select the system and center the map on it, otherwise, display the panel with no mission selected.

If the panel displays with no mission selected, just pressing the up/down arrow keys initiates navigation through the missions.

**Comment by db47h** [comment]
Another thing that could also improve user experience is to somehow keep track of the last system that was selected on any map panel (store that in PlayerInfo and invalidate it on jump?)

**Comment by db47h** [comment]
Well, without programming, if people who can at least least build from source could test and provide feedback on pull requests, that could be very helpful :)

I'm not sure to understand what you mean by

> don't change the mission in a way that is different from the current system once the mission panel is open

After playing for a while with this patch (playing the game, not hacking code...), the behavior of the mission panel really feels more intuitive, so I don't plan on changing it any further (besides keeping track of the last selected system, but that would be another PR).

**Comment by jafdy** [comment]
If you already did it then it dosen't mater.

**Comment by jmhorjus** [comment]
I've pulled your change into my own test branch and can vouch for it being nice to start with no mission selected.  I did used to occasionally accept a mission thinking its destination was one place when in fact it wasn't.

**Comment by endless-sky** [comment]
I've merged in your PR.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
