### ISSUE TITLE
Can still change flagship on Nenia or Slylandro - with comical results

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#8476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I know I posted this ages ago, and I guess that post was quietly put aside, however ... it is still possible to take a fleet to Nenia or Slylandro, then "swap" the Puffin out for a different flagship.

In the case of the save-files below, I was able to swap from a Puffin to a Rano'erek, and, more amusingly, when I moved the Rano'erek into the flagship slot, I re-crewed for capping pirates/Korath ships with 200 plus mercenaries recruited from a gas giant with zero population.

### Steps to Reproduce

Check out the two save-files.

### Expected Behavior

Should not be able to change flagship on a gas giant.

### Link to save file

[Speedy McSpeed~3017-12-29-Slylandro Swapping.txt](https://github.com/endless-sky/endless-sky/files/10845579/Speedy.McSpeed.3017-12-29-Slylandro.Swapping.txt)
[Speedy McSpeed~3017-12-29-Nenia-swapping.txt](https://github.com/endless-sky/endless-sky/files/10845580/Speedy.McSpeed.3017-12-29-Nenia-swapping.txt)

### Operating System

Ubuntu 21

### Game Source

GitHub Releases

### Game Version

0.10.0 (just released)

**Comment by warp-core** [comment]
I believe your old issue still exists. #5663
There's also #5210 which is related.
