### ISSUE TITLE
Remnant Expedition mission reveals the system that is not allowed to access right now

### ISSUE THREAD

**Issue by binaryspica** [endless-sky/endless-sky#8477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Hai Reveal mission is not active right now, but despite of this the Remnant issue the expedition mission to check the system related with this quest line.

### Steps to Reproduce

1. Go to Remnant territory.
2. Check the Research Expedition mission and see if it issue the expedition mission that is not meant to access right now.

### Expected Behavior

The system needs to have some tag such as unreleased, and such systems are exempt for the target system for the Research Expedition mission target issued by Remnant.

### Screenshots

https://steamcommunity.com/sharedfiles/filedetails/?id=2938729931

### Operating System

Windows 10.

### Game Source

Steam

### Game Version

0.10.0

**Comment by TomGoodIdea** [comment]
Similar to #7702.

**Comment by binaryspica** [comment]
> Similar to #7702.

Thank you for note this. Then the topic should be closed due to duplicate.
