### ISSUE TITLE
Documentation: "PlayerConditions" wiki page does not mention `"event: <event name>"` as a possible modifiable condition

### ISSUE THREAD

**Issue by bene-dictator** [endless-sky/endless-sky#8497]
### Location

wiki (PlayerConditions)

### Describe the issue

The "PlayerConditions" wiki page does not mention `"event: <event name>"` as a possible modifiable condition. It might trip some people up, like me this morning. It is found in the data files, but it's not immediately obvious that it's possible. 

I see that the CreatingEvents does mention `"event: <event name>"`, but it's at the bottom of the page. It would make more sense if it were in "PlayerConditions".

### Expected content

Add something like:
* "event: `<event name>`", where `<event name>` is replaced with the name of any event. It is set when the event is fired.

**Comment by warp-core** [comment]
Done. https://github.com/endless-sky/endless-sky/wiki/Player-Conditions/_compare/8c8e807ef57c874352b1b16819108345f3a97c3a
