### ISSUE TITLE
Scanning: Government Jurisdiction

### ISSUE THREAD

**Issue by daerogami** [endless-sky/endless-sky#851]
Feature Request: Ships only scan on behalf of their Government when in their own territory.

I have been flying around the southern sector in the "Free Worlds" systems and noticed there is a strangely large number of Republic Gunboats flying around this expanse of the galaxy.
Given the fallout between the Free Worlds and the Republic, why is the Republic enforcing their contraband laws outside of their domain? Even in uninhabited areas?

Related Issues: #556 #576

**Comment by endless-sky** [comment]
In their defense, from the Republic's perspective the Free Worlds systems *are* their territory.

**Comment by tehhowch** [comment]
The simplest method of doing this is to add a check inside AI::DoSurveillance that the current system is of the same government as the ship.

This could be expanded by defining a new node to the government definition, that identifies the system governments in which this government can exercise authority:
```
government "Republic"
    enforces
        "Republic"
        "Free Worlds"
        "Syndicate"
        not "Pirate"
        ...
```
This structure is just a LocationFilter, making its use and customization very intuitive for modders and other content creators

**Comment by jjhankins** [comment]
The AI already doesn't scan hostile ships, so the Republic isn't going to scan pirate ships no matter where they are - though perhaps this should be changed? In practice, playing as a pirate, being scanned (by Captain Parrot) is more of a threat than being attacked. You can run from an attack, but if you're fined they just reach into your account and take the money out.

Hm. If fines are simply another avenue of enforcement (which is more true to the story, imo) then they'd fine anyone they're hostile enough with to attack, whether or not they carry contraband. This would open up some interesting story possibilities. Pirates would want to keep their funds out of reach of the republic, so give them a new outfit (a ship safe) and the ability to purchase jewels and coins, and suddenly there's the possibility of treasure caches.

**Comment by tehhowch** [comment]
That filter was meant as an example of possible syntax. Note that defining an inclusive filter for one property means any exclusive filters on that same property that mention new values are automatically satisfied.

**Comment by KiLEdEnNis** [comment]
@jjhankins the only thing I'd do with pirates toward the Republic & other factions is being able to accumulate a large bounty & when ya pay it off they become friendly again, but doing that per government and everything doesn't seem worth it

**Comment by jjhankins** [comment]
I'm thinking more when you're playing as a pirate, really - the buried treasure mission was just a thought. I've been working on a pirate mod, and so I've been playing a lot as a pirate. Once the Republic (and Syndicate, etc) is hostile to you, the only way you ever get fined is from Captain Parrot. That's kind of strange if you think that you're building up a huge balance in a Republic bank, and they're just letting you do it even though you're public enemy number 1. But I'm not sure what the right solution is, and I suspect it's off topic by now.

**Comment by KiLEdEnNis** [comment]
tbh Captain Pester is basically a meme
there was some idea to make things illegal to some but not all governments, but that got shot down I think

**Comment by tehhowch** [comment]
Closing since with the merge of #3187 this is doable for plugins or future base content, using the syntax example [here](https://github.com/endless-sky/endless-sky/issues/851#issuecomment-340650509)
