### ISSUE TITLE
Nanotech Battery description still references LP576a size from before the battery buff

### ISSUE THREAD

**Issue by northeast-eph** [endless-sky/endless-sky#8515]
### Problem Description

Currently, the description of the Nanotech Battery states that they can store "a third more energy than the best human batteries while being less than a third the size". Since the battery buff halved the size of human batteries, the Nanotech Battery is now 5/8ths the size of a LP576a.

### Related Issue Links

Could not find any by searching open and closed issues and PRs for varioations upon "nanotech", "quarg", "description", and "battery".

### Desired Solution

The description could be updated to something along the lines of "while being just over half the size."

### Alternative Approaches

The description could also be changed to state that Nanotech Batteries have over double the energy density of human batteries, or the Nanotech Battery could be made smaller, but that would likely necessitate additional balancing changes.

**Comment by Hurleveur** [comment]
Well I had some suggested changes notably to the battery in https://github.com/endless-sky/endless-sky/pull/7544, feel free to take them over.
I think the Quarg should stay that much more efficient honestly, instead of just tweaking the description.
