### ISSUE TITLE
Brig works from Cargo

### ISSUE THREAD

**Issue by EgorKa239** [endless-sky/endless-sky#8516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is possible to accept Job bord's "Prisoner transport" mission having a Brig only in cargo, not installed on your ship.

### Steps to Reproduce

1. Look for a "Prisoner transport" mission in the Job board having a Brig with you
2. Put  the Brig into your cargohold
3. Check the Job board again
4. See that the mission is still available 

### Expected Behavior

A Brig would have to be installed on the ship rather then just put in cargo in order to be able to accept those missions.

### Operating System

Windows 

### Game Source

GitHub Releases

### Game Version

0.10.0

**Comment by northeast-eph** [comment]
Just tried this out and can confirm that a brig in cargo works for prisoner transport missions. I tried both moving the bring to cargo on the same planet that offered the job, and landing with a brig already in cargo. You can also successfully complete prisoner transport missions if you sell the brig after accepting it and take off without one.

**Comment by Hecter94** [comment]
This would be easy enough to fix with the new autoconditions I believe, we just need to swap from `has "outfit: Brig"` to `"outfit (installed): brig"`

**Comment by Hurleveur** [comment]
that would be a good temporary fix (although dont forget flagship installed for the capture X that escaped in a ship)
eventually we should have bunk types though, I think RisingLeaf had a PR for that?

**Comment by alexpyattaev** [comment]
Sorry to revive necro bug, but does brig work when installed on escort ships?
