### ISSUE TITLE
Outdated/missing keybinds in the player's manual

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#8533]
### Location

wiki

### Describe the issue

https://github.com/endless-sky/endless-sky/wiki/PlayersManual#key-bindings-and-shortcuts
This is missing multiple shortcuts, including mouse hold/toggle keybinds.

I'm not sure how many things are missing, especially that certain shortcuts (like `u` for storage) are mentioned in text, but are not in the actual list.

### Expected content

The contents should be updated after the merging of every PR that adds key bindings.

**Comment by tibetiroka** [comment]
The wiki page is still incomplete.

**Comment by warp-core** [comment]
I've updated the controls list on that page. Did I get everything?

**Comment by tibetiroka** [comment]
All the ones I noticed, at least.
