### ISSUE TITLE
Warp Inhibitor

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#855]
I was thinking about a random event where you get ambushed by pirates, but thought that that'd be too easy to avoid by just landing or jumping out of the system. Then my thought right after that was: "What if there were a way to stop ships from jumping out of a system?" I'm sure such an item could be useful for certain story missions later on and a really fun thing for plug in makers to mess around with. Warp inhibitors could expand upon combat in the game, as right now it's just a matter of jumping/warping away when you get too damaged. So is a warp inhibitor something that could possibly be implemented into the game?

**Comment by LocalGod79** [comment]
this can already be accomplished through hit force and ion damage...in fact, there's already a weapon that does both...

**Comment by Wrzlprnft** [comment]
I think he doesn't mean weapons, more like the star wars interdictor class star destroyer.

**Comment by Amazinite** [comment]
Pirates don't exactly use ion damage and it's easy to fly out of range and then jump so hit force isn't a problem for you, so that isn't exactly a solution to the problem. You're assuming that you're going to constantly be under fire and taking damage. I'm taking about something that will completely block all jumps and warps inside of a system until the ship with the warp inhibitor is destroyed.

**Comment by LocalGod79** [comment]
i feel like this could be used just once.

an outfit that provided this attribute would stop the user from jumping, and make whichever system they take off in into a black hole - ships jump in, cannot jump out.

it seems like this feature is required to *force* the user to do something - seems contrary to the overall theme of the game so far.

missions can be aborted, all other situations have a few ways to deal with them - this one: fight your way to landing or hope you kill the right ship on the way.

**Comment by Amazinite** [comment]
Like I said in my main post, it's was mainly conceptualized to be used it something like an ambush event. Say you're pretty late on in the game. You've obviously made quite a few enemies at this point. You warp into an uninhabited system and find yourself face to face with a ton of pirates that want some revenge. They know that you're tough and hard to kill, so they have to bring new technology to try and take you down. In comes the warp inhibitor. A marked ship has a warp inhibitor on it that stops you from leaving until you kill it. You can take just the marks ship out and leave, or have fun killing everything. 

It's not about forcing the player to do something, it's more about giving the player a higher risk combat experience in the later game, and possibly with high rewards. Maybe an event like this would have you under attack by a few marauder ships out to get you, who have a smaller ship behind them that's stopping you from leaving. You could easily kill this one ship and leave without much of a problem, but you've got that option to stay and try and bag yourself some rare ships. 

If anything, someone else could probably use it to make something interesting. I'm more of an idea engine guy when it comes to making outfits, so this might not be the best use for something like a warp inhibitor, but I'm sure someone would have a good use for it that could still have the same feel of the game.

**Comment by Amazinite** [comment]
I'm not sure if there is an issue about this here, but I recall someone on the Steam forums mentioning something about difficulty levels. This would be a perfect item to use in a "hardcore" difficulty setting, making you really plan out your combat to try and survive instead of just jumping out of the system when you see some pirates.

**Comment by toilethinges** [comment]
It could have configurable ammunition and lifetime, so that it wouldn't be a complete fight or die.

**Comment by LocalGod79** [comment]
@toilethinges he wants an engine function that inhibits jumps based on the presence of an npc - not a weapon that does the job ('cause they already exist)

@Amazinite it does force the player to engage in combat.  further, said combat will take place on terms dictated by the mission writer.  further, "hardcore" mode is still only a proposition - i believe proposing something based on otherwise unimplemented features is premature.

my last words on this: i don't believe that the required coding will yield substantial content.  how many times in how many stories are really going to lock a player into that combat situation?

**Comment by toilethinges** [comment]
@LocalGod79 I understand perfectly well what he wants - I was talking to him earlier. What I'm saying is an outfit (similiar in style, however to a secondary weapon - secondary outfits?) that does exactly that, yes, but requires ammunition, and each usage could have a set lifetime variable.

6000 lifetime - 100 seconds of being forced to stay in that system. You could make it have, say, two ammunition. That's, in all, 200 seconds.

> my last words on this: i don't believe that the required coding will yield substantial content. how many times in how many stories are really going to lock a player into that combat situation?

The Free Worlds storyline does it several times, actually. The battle of Kornepheros, for example?

**Comment by Amazinite** [comment]
I see what you're saying on the difficulty thing, but it was just a suggestion on how it could be used and not saying that this is how it should be used and what it should be made for. 

But I really don't see how it's any different in "forcing you into combat" than some of the story missions. In the story, you have to fight if you want to complete it, unless there's some way to get through the campaign without needing to fight that I'm unaware of. Yes, the decision is there to not do it, but if you want to finish the story than you must fight. 

My original reason for thinking of this was for combat after the campaign has been finished, so the player will already be familiar with combat. It would really force you into combat less so than some of the story missions, since you have the option to only destroy the warp inhibitor ship then leave, unlike some missions where you need to take on entire fleets. I was also thinking of something like what Toilet suggested, where the warp inhibitor only lasts so long. This give you the other option to not engage in combat and simply fly out to the edge of the map until say a minute passes, then you may leave. So this could be designed to not force the player to have to do something they may find highly inconvenient, while also being something interesting to players that decide to engage. 

In all honesty, I'm fine if this never gets added, I just think that it would be something interesting to consider, even if it is only implemented later down the road.

**Comment by Hyratel** [comment]
make it AoE with a large range, say... 10x the length of the Bactrian in radius? you'd have to work your way out. perhaps it would cause other problems as well - increased firing delays on blaster weapons?

**Comment by Amazinite** [comment]
I do agree on the idea of giving it a range limit, but I don't think it should do anything other than inhibitor jumping. Something like reducing fire rate or decreasing velocities on enemy weapons could be a different form of electronic warfare.

**Comment by brick96** [comment]
Perhaps the range of the system? That is, the invisible boundary that npc ships lose interest

**Comment by Amazinite** [comment]
I've created a warp inhibitor like weapon. It applies a hit force to most of the system around the ship, causing the AI to have some trouble jumping away. Depending on how you adjust the hit force, it changes the max size of the ship that can be affected. The hit force is so small that it doesn't affect combat, so it still achieves the desired effect. It is fueled by dark matter, so there is both a time limit that it will last and a distance at which it works. Perfect.

**Comment by Wrzlprnft** [comment]
Can you show us the code?

**Comment by Amazinite** [comment]
What, can't wait until I update my mod with it?  ( ͡° ͜ʖ ͡°) 
`outfit "Warp Inhibitor"
	category "Turrets"
	cost 0
	thumbnail "outfit/known"
	"mass" 100
	"outfit space" -100
	"weapon capacity" -100
	"turret mounts" -1
	"dark matter capacity" 6000
	weapon
		sound "skylance"
		ammo "Dark Matter"
		icon "icon/"
		"inaccuracy" .1
		"velocity" 1
		"lifetime" 1
		"reload" 1
		"firing energy" 0
		"firing heat" 0
		"blast radius" 5000
		"trigger radius" 5000
		"firing force" -10
		"hit force" 10

outfit "Dark Matter"
	category "Ammunition"
	cost 0
	thumbnail "outfit/known"
	"dark matter capacity" -1
	"mass" 0.5`

**Comment by Amazinite** [comment]
Upon further testing, the AI does not like to use this weapon. It attempts to get out of the blast radius so that it doesn't hit itself, so it never actually uses it... Going to need to change it up a bit, or try and make the AI go "suicidal" and use it despite hitting itself.

**Comment by Amazinite** [comment]
Okay, so the AI seems to be fine with this code here. 

```
outfit "Warp Inhibitor"
	category "Turrets"
	cost 0
	thumbnail "outfit/known"
	"mass" 100
	"outfit space" -100
	"weapon capacity" -100
	"turret mounts" -1
	"dark matter capacity" 6000
	weapon
		sound "skylance"
		ammo "Dark Matter"
		icon "icon/dark matter"
		"inaccuracy" .1
		"velocity" 10
		"lifetime" 10
		"reload" 1
		"split range" 50
		"firing energy" 0
		"firing heat" 0
		"firing force" -10
		"submunition" "inhibitor" 1

outfit "inhibitor"
	weapon
		"lifetime" 5000
		"blast radius" 5000
		"trigger radius" 5000
		"hit force" 10
```
