### ISSUE TITLE
License definitions in variants are not applied.

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#8562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you place a `licenses` entry in `add attributes` in a variant, it does nothing.

### Steps to Reproduce

```
ship "Shuttle" "Shuttle (Navy)"
	add attributes
		"shields" 1
		licenses
			Navy


shipyard "Basic Ships"
	"Shuttle (Navy)"
```
This adds a shuttle which does correctly have 501 shields, so the added shields attribute is working, but does not require a Navy license, so the added navy license is not.

### Expected Behavior

Placing a license in `add attributes` should add the license as a requirement for that variant.

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

Continuous

**Comment by UnorderedSigh** [comment]
The bug was in Outfit::Add which wasn't appending the license list.

```C++
// For tracking a combination of outfits in a ship: add the given number of
// instances of the given outfit to this outfit.
void Outfit::Add(const Outfit &other, int count)
{
        cost += other.cost * count;
        mass += other.mass * count;
	for(const auto &at : other.attributes)
        {
         	attributes[at.first] += at.second * count;
                if(fabs(attributes[at.first]) < EPS)
                        attributes[at.first] = 0.;
        }
```

It works when I add the missing line in #9682

```C++
licenses.insert(licenses.end(), other.licenses.begin(), other.licenses.end());
```

See?

```julia
ship "Archon" "Navy Archon"
	add attributes
		licenses
			Navy
	description `"Lieutenant, are we prepared for the Third Alpha War?"`
	description `	"Yes, sir. I think our new ships are up to the task."`
```

![add-attributes-licenses](https://github.com/endless-sky/endless-sky/assets/116329264/2cf43be9-cad0-4aa4-bbc8-0b985ee035f4)
