### ISSUE TITLE
Companion mode

### ISSUE THREAD

**Issue by Blqtent** [endless-sky/endless-sky#8569]
### Problem Description

I wanna play this with my friend, but it is impossible since this is not multiplayer.

### Related Issue Links

None

### Desired Solution

I know that servers with lots of people connecting is nearly impossible, but you guys could implement a system that connects two computers together to have a companion mode. Just have them give each other a code, so they can connect together.

### Alternative Approaches

None

### Additional Context

None

**Comment by Zitchas** [comment]
Similar suggestions:
#327
#266
#149

**Comment by MonkeyMatrix** [comment]
I thought the save system used in No Man's Sky was a nice take on multiplayer. You essentially bring your own save into another multiplayer game (although hosted by a server), which includes your ships, upgrades, stats, discovered systems, etc. We would still need to determine how to handle missions (per-player/all online player starting, requirements, completion, etc.), dialogs, and probably many other things I am not thinking of right now.

(Just thought of this off the top of my head; I haven't looked through other suggestions yet.)

**Comment by Zireael07** [comment]
Where can I read more about that NMS idea?

**Comment by MonkeyMatrix** [comment]
The best I can find with the time I have right now is the wiki page on multiplayer. If you have any questions about it that you are unable to find answers to, I will answer them the best I can when I get time later today.

[No Man's Sky Multiplayer Wiki Page](https://nomanssky.fandom.com/wiki/Multiplayer)

I will also be adding to my first post over the next few days as I come up with more ideas.

**Comment by Zireael07** [comment]
Kinda related (but not true multiplayer): https://github.com/endless-sky/endless-sky/discussions/9497
