### ISSUE TITLE
Virtual on-screen joystick for android port? 

### ISSUE THREAD

**Issue by genry718** [endless-sky/endless-sky#8577]
### Problem Description

Any plans to adding virtual on-screen joystick for android port? its very hard to play on current touch controls when u play on large tablet pc. but i'm playing another 2d-space-sims and all them have virtual joy and it good enough

### Related Issue Links

no

### Desired Solution

adding virtual joystick

### Alternative Approaches

no

**Comment by mOctave** [comment]
This seems like an issue best raised on the GitHub page for the android port of the game, rather than here. I believe that is located at https://github.com/thewierdnut/endless-mobile. Also @thewierdnut, you might want to see this.
