### ISSUE TITLE
TDR Graphics Card Error, CTD

### ISSUE THREAD

**Issue by pootthedestroyer** [endless-sky/endless-sky#858]
Windows 7 64 Home, Bootcamp, running on an Intel i7-3770 3.40 GHz. 8 GB RAM.

Graphics Card is an Nvdia GeForce GTX 680MX. Tested with 361 and 364 version drivers.

Game constantly crashes with a TDR error relating to the graphics card. Error type 7, links to info on Nvdia's site. Most often occurs on Shipyard and Outfitter pages, and can even occur if idling on those pages without interaction.

Manually adjusted the max delay tolerance through RegEdit to 4 seconds from 2 seconds, with little noticeable effect.

This is a major, gamebreaking issue, as any significant outfitting or fleet management through those windows is impossible, as the game crashes and forces you back to the save on whatever planet you landed on previously.

**Comment by db47h** [comment]
Did it send you to this page? [OpenGL message “TDR detected”](http://nvidia.custhelp.com/app/answers/detail/a_id/3633/)

If that's the case, the workload sent to the graphics card by Endless Sky should hardly be greater than what a low end graphics card can process in the normal timeout of two seconds (and your card is definitely NOT low end).

You mention Bootcamp... does the game run under OSX on your hardware?

**Comment by pootthedestroyer** [comment]
I actually installed it on OSX just to test it out. The answer is that yes,
it does run, but it encounters a similar problem. The only difference, I
think, is that OSX's settings don't include an automatic timeout crash. I
do end up getting the rainbow-spiral-of-danger, followed by a total screen
freeze, and then everything sorts itself out for a while longer.

However, I tested a theory, and got some disappointing results: leaving my
game on the Outfitter screen and walking away (no interaction with the
computer whatsoever) eventually caused Endless Sky to crash, likely due to
the same graphics-card-related issue. Unfortunately there was no explicit
error, but I did send the report to Apple.

This issue therefore should be reproducible on OSX just by going to the
outfitter page and... waiting. First you'll get the rainbow wheel -> freeze
-> recovery, then eventually the crash. Clicking around on the outfitter
page does sometimes seem to speed up the process of receiving the first
error, but honestly, that might just be my imagination.

For the record, running (on same hardware) Yosemite, 10.10.5

**Comment by endless-sky** [comment]
Are you running the latest release (0.8.11)? Prior to that release there was an issue with the outfitter screen using up a lot of CPU and GPU time.

**Comment by pootthedestroyer** [comment]
Yup, 0.8.11. Just double-checked by opening up the application.

**Comment by endless-sky** [comment]
Unfortunately, if this only affects your particular graphics card it could be rather hard to debug.

Are you using any plugins, or just the base game?

**Comment by pootthedestroyer** [comment]
The issue persisted across Win7x64 and OS X 10.10.5 with just the base game.

As an additional note, on OSX the Endless Sky process is reporting 22.2%
CPU usage while idling on the outfitter screen. I have no way to tell if
that's normal, but it's data.

**Comment by db47h** [comment]
That's odd, I'm at 16-18% CPU usage on any static screen with a much slower CPU (AMD FX6300 & GeForce GTX560), but that's on linux so it may not be indicative of anything. With your setup I assume you play other, more power hungry games. Any problems with those?

On the other hand, I've seen this kind of error on Windows on a machine with a faulty memory module (see [this page](http://windows.microsoft.com/en-us/windows7/diagnosing-memory-problems-on-your-computer)) and on another with SLI enabled (never bothered to troubleshoot properly, just pulled one of the cards out). Testing the video card might be worthwhile (a shader heavy stress test like FurMark comes to mind). I'm not saying Endless Sky is not the sole culprit, but that'd get suspicions on the hardware out of the way.

**Comment by pootthedestroyer** [comment]
I've played quite a few games that are (should be?) much more CPU/GPU
intensive than Endless Sky, without any significant issues. Granted, they
were all on Windows, but this issue (or some version of it) is persisting
cross-platform.
