### ISSUE TITLE
Capturing a ship does not count as it being killed for new ship actions

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#8592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Capturing a ship does not result in it counting as "killed" when using the "on kill" ship event, despite it doing so for mission requirements.

### Steps to Reproduce

1. Load my save file
2. Depart
3. Disable and capture "D.P.S. Wyrd"
4. Let "D.P.S Wyrd" die
5. Continue deep archaeology
6. See how the ship attacks you

### Expected Behavior

Capturing a ship results in it counting as "killed" when using the "on kill" ship event.

### Screenshots

![bug1](https://user-images.githubusercontent.com/109186806/227809918-cc7661f3-38e5-4253-ad08-d157431f17ed.png)
![bug2](https://user-images.githubusercontent.com/109186806/227809920-013871cf-fa08-4dc0-9b1f-77a9b9659860.png)
![bug3](https://user-images.githubusercontent.com/109186806/227809923-b191d5e8-9d58-455e-a82c-abecb560e7d6.png)
![bug4](https://user-images.githubusercontent.com/109186806/227809924-681052cd-21b5-4db6-8d92-c48dd55cd0ba.png)
![bug5](https://user-images.githubusercontent.com/109186806/227809926-b5bcda2b-aeb8-4d92-9df9-1bb54033b1ac.png)

### Link to save file

[Endless-Sky any%~Deep Archaeology.txt](https://github.com/endless-sky/endless-sky/files/11073272/Endless-Sky.any.Deep.Archaeology.txt)

### Operating System

Devuan 4 Chimera + MX Linux 21

### Game Source

Other (please describe)

### Game Version

da351cc

### Additional Information

The version listed is from my PR. The save file has the mission hardcoded with "on kill" but not "on capture," however, so standard Continuous can be used.

**Comment by Amazinite** [comment]
Captured ships counting as killed for objective purposes makes sense, because we wouldn't want capturing an NPC to soft lock missions. But for NPC action purposes, it makes sense to strictly divide "on kill" and "on capture" so that you can use one, the other, or both, instead of capturing implicitly triggering "on kill".

**Comment by ziproot** [comment]
That's what I ended up doing. Thank you for explaining this.

**Comment by ziproot** [comment]
99a69a7ae1cab14f5b098775e6af16bad282155b fixed this.
