### ISSUE TITLE
Disallow random spaceport events from setting the current planet as the destination

### ISSUE THREAD

**Issue by davidneedham** [endless-sky/endless-sky#8595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When receiving a mission from a spaceport event the desired destination was the planet we were already on. Specifically it was the one with the deadbeat man not having the credits to pay the captain to travel off world. 

### Steps to Reproduce

I don't know enough about how this works, but I assume that most spaceport events like this happen randomly. So I'm not sure if this is even possible to recreate without some luck, but here's what I did:

1. I land on Maelstrom in Nihal and visit the spaceport. 
2. The random event triggers 
3. I engage and his destination is... the same planet we're on. 
4. So I depart and land and the mission completes.

### Expected Behavior

Due to the story the man pitched I expected him to want to travel to some other planet far away to get a fresh start.

### Screenshots

I didn't think to grab a screenshot in the initial dialog box, but here's the conclusion:

<img width="564" alt="Screenshot 2023-03-27 at 9 42 31 PM" src="https://user-images.githubusercontent.com/1323278/228115025-821a8c1e-6af3-42ff-9619-05de184b3a4c.png">

### Link to save file

[John Dough~3014-08-20.txt](https://github.com/endless-sky/endless-sky/files/11084765/John.Dough.3014-08-20.txt)

### Operating System

macOS Ventura 13.2.1

### Game Source

Steam

### Game Version

v0.9.16.1

**Comment by bene-dictator** [comment]
Thanks for the report, however this has been fixed in the latest unstable version (#7846).

If you want, you can play the v0.10.0 unstable version on Steam by opting into the beta.

**Comment by davidneedham** [comment]
I'm glad to hear it. Thanks for the follow up.
