### ISSUE TITLE
Condition set in on visit to cause failure is not available in on fail trigger

### ISSUE THREAD

**Issue by sbfast** [endless-sky/endless-sky#8596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A condition set in the "on visit" trigger to cause a mission to fail, is not available in the "on fail" trigger

### Steps to Reproduce

```
mission "Test Conditions"
	on offer
		dialog "Don't come back!"
	to complete
		has "Some other condition"
	to fail
		has "No Return"
	on visit
		set "No Return"
	on complete
		dialog "Done"
	on fail
		dialog "Failed <message>"
substitutions
	"<message>" "No condition set"
	"<message>" "No return set"
		has "No Return"
```

Accept mission, launch and land

### Expected Behavior

The mission should fail and the message should say "Failed No return set". Instead the mission fails, indicating that "No Return" is indeed set, but the message is "Failed No Condition set". 

Looking at save files, the "No Return" condition is saved in the player file on next launch, and any subsequent mission using the same substitution gets the correct phrase.

### Operating System

MacOS X

### Game Source

GitHub Releases

### Game Version

0.9.16.1

### Additional Information

Also applies to conditions set in "on daily" and "on accept"

**Comment by Amazinite** [comment]
Custom substitutions are currently executed when the mission is instantiated, i.e. before it is offered. Therefore, nothing you do during the mission will change the the substitutions, because the substitutions have already made their text replacements. So the condition is set, and you could branch on it if your `on fail` had a conversation, but the substituted text will still reflect what it was before the mission offered.

**Comment by sbfast** [comment]
Thanks; that makes sense from a coding perspective - but may be useful to note that in the create mission and/or substituions documentation.

I got round the immediate issue by moving the failure dialog to a subsequent mission

**Comment by Amazinite** [comment]
I've added the following paragraph to the [Creating Substitutions](https://github.com/endless-sky/endless-sky/wiki/CreatingSubstitutions) page:
> Note that currently, the condition sets for substitutions are evaluated when the mission is instantiated. This means that actions taken during a mission can not change the outcome of any substitutions, as they have already made their text replacements. If you wish to change the outcome of text based on conditions that could have changed during the mission, then you should instead use `branch` or `to display`.
