### ISSUE TITLE
Looted outfits seem to sell for nothing (unless installed prior to sale).

### ISSUE THREAD

**Issue by KAWilley** [endless-sky/endless-sky#86]
I'm not the original person who reported this over on the forum, but we both have the same issue.

Both on Mac and Windows, selling captured ammunition and outfits seems to pay nothing unless they are installed, though selling captured cargo increases money as normal.

See: https://groups.google.com/forum/#!category-topic/endless-sky/GOPCYeUFe4s

**Comment by endless-sky** [comment]
Fixed in commit 781d263. This will be part of the 0.8.2 bug fix release in a few days.
