### ISSUE TITLE
Merchant Behavior

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#860]
In my experience, merchants don't seem to act like they're trying to make a living trading goods. If you attack a merchant or a pirate enters the system, then all merchants in the system will attack you or that pirate, even the freighters and haulers. To me, this doesn't make all that much sense. If I were a merchant, my first thought would be to get the heck out of the system so I don't get blown up, but the NPC merchants seem to try and fight their aggressor regardless of size. This leads to a lot of merchants getting killed and losing a lot of goods, when they should be jumping out of the system immediately and leaving the pirates to the local police force, be it syndicate ships, navy, or free world militia.

**Comment by LocalGod79** [comment]
i rationalized this behaviour that the merchants are part of a guild, which may put a bounty on your ship if you wronged their members.  this would encourage freighter captains to help damage the bounty and/or gang up to collect the bounty together.

at least in the early going, a group of merchant ships can easily overpower an overly ambitious pirate play style user.

that said, the player continuing to fly merchant colours once their reputation with them is less than 0 is somewhat troubling.

perhaps as a part of a more comprehensive introduction mission set, the player could be introduced to the merchant guild, and given the option to join their ranks/fly their colours.  if the player declines, independent swizzle and loses some of the job board - i.e. bounty hunting?  others related to the guild?

**Comment by Amazinite** [comment]
That does make sense. The only reason they would truly need to attack a ship would be if destroying that ship gets them more cash than if they fled the system to continue trading. It would make sense then to at least have something in the story to explain this behavior, like a mission that introduces you to them as you suggested.

But this still doesn't solve the "regardless of size" thing. I've seen a group of three or four pirate warships come in and attack a group of three small, lightly armed freighters, and the freighters still try and take them on, even though they would obviously lose in that situation.

**Comment by endless-sky** [comment]
Merchants only try to fight if the pirate is close enough to attack them. They won't go out of their way to join a fight, but if they're cornered they need to fight back because they are seldom fast enough to outrun a pirate.

**Comment by lehgogh** [comment]
I'm not sure if this is implemented yet, but there could be a fleet type that consists of a few large freighters and several smaller fighters. The fighters could attack enemy ships, while the freighters try to land until the enemy ships are destroyed or leave.

**Comment by wargwargwarg** [comment]
I agree with Amazinite, this needs tweaking. Traders are not combat crazy. They would hire a mercenary for the dirty job. Or would assess the situation and engage if favorable.

One way top fix it is add a new check to the traders behavior: jump away if:
1) trader shield strength would be depleted before emergency stop and jump away, based on an estimated 1 blaster in every slot and turret of the enemy ship(s). Or include a ratio (own shield would be under 50% in the time it took to prepare the jump, based on the estimated damage potential of the pirate). Estimated being the operative word. 
2) trader lost x% of shield strength in the last y seconds

better yet, make it shield strength related
