### ISSUE TITLE
A way to complete or fail a mission on player ship disabled

### ISSUE THREAD

**Issue by sbfast** [endless-sky/endless-sky#8603]
### Problem Description

For a mission mechanic it would be useful to have either: 
- a "flagship: disabled" condition which could be accessed in "to fail" or "to complete" 
- a trigger "on disabled" which allows action to be taken if the players ship is disabled

### Related Issue Links

https://discord.com/channels/251118043411775489/431496424992014347/1090029721925984326
https://discord.com/channels/251118043411775489/431496424992014347/1090175838235922452

### Desired Solution

Specific use case is for a mission set of friendly dogfights which end when either the npc or the player is disabled.

Could also be useful in weapons testing missions.

### Alternative Approaches

Currently the player can hail the npc and bribe to repair, and complete/fail set in the "on visit" or mission deadline but that allows player to have another go at disabling the npc as the mission is neither completed or failed until either landing or leaving the system.

**Comment by Amazinite** [comment]
Resolved by #8606.
