### ISSUE TITLE
Bunrodea planets are restricted - can't complete first Bunrodea mission

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#8609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After exploring Bunrodea space I landed on a human planet (Stormhold in Alcyone, I think) and was given what I assume is the first Bunrodean mission, "An intriguing invitation". I've been tasked to land on Erabuthro in Erabu Lemeta. Problem is, all Bunrodean planets are restricted to me and I can't land. If you're being given a mission by the Bunrodeans themselves, should you be allowed to land at least on Erabuthro?

My reputation with them is 0. I haven't intentionally attacked any of their ships, though I know my escorts blasted some ships that were hostile to me at some point when exploring these new areas of space in the galactic North East. No idea if the ships were Bunrodean or not.

I haven't tried this mission with a new pilot so I'm not sure if using an existing pilot file affected this.

### Steps to Reproduce

As above

### Expected Behavior

As Above

### Screenshots

<img width="1469" alt="Screenshot 2023-03-31 at 12 46 54" src="https://user-images.githubusercontent.com/16049594/229100117-d919aaf1-e08f-4d47-bdfb-54d81a695946.png">

### Link to save file

[Gizmo Atomic.txt](https://github.com/endless-sky/endless-sky/files/11120980/Gizmo.Atomic.txt)

### Operating System

MacOS 13.2.1

### Game Source

Steam

### Game Version

0.10.0 (beta)

**Comment by ziproot** [comment]
Hail the planet (try to land, then press T).

**Comment by brendanjones** [comment]
Duhhhhh. Righto, thanks.

**Comment by movingpictures** [comment]
Same issue - except I do not recall my escorts attacking anything.

**Comment by movingpictures** [comment]
That's part of it. The other is that I do not recall being attacked. If
this is critical to the storyline, some dialog box at that point is called
for.
