### ISSUE TITLE
Feature Request: Negative damage AI support

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#861]
New edit: Better idea
Maybe instead make an attribute on weapons that causes the ships they're on to friendly fire with them. This way you could make a weapon that say repairs target health but also heats them up as a trade off.

Edit: Cutting it down.
If a weapon has negative attack values (hull, shield, ion, etc.), have the AI realize that it is a weapon that would be used to heal a target, and have them use it on friendlies.

Original:
In my plug-in, I have special turrets that will repair and assist the ship that they fire on. There's a Hull Repair Turret that fires nanobots that repair hill, Energy Transfer turret that charges the ships battery, and I'm also planning on adding a Water Cannon that can reduce heat. The only thing is that these will only work on your flagship, as placing them on your escort will cause them to repair enemy ships.

So I was wondering if there could be a special "Support Escort" type of government that would "attack" your own ships with these assistance weapons to help them, or possibly make it so that your escorts can tell the difference between which of their weapons will do damage and which ones will heal, and then allow them to utilities their support weapons to fire on their own ships. 

I'm not entirely sure how this could be done, but possibly you could have the game detect if shield damage, hull damage, ion damage, or heat damage are negative on a weapon. If all the values are 0 or negative, then the escort would know that this is a weapon to be used on its allies. They could then select that weapon and fire it on their own if a certain ship is in dire need of help. This would obviously be highly taxing in both heat and energy on the supporting ship, just to keep it balanced. 

Something like this could also be used for other factions, such as an "Enslaved Engineer" faction that helps pirates, or "Navy Mechanic" that helps navy ships. (The whole point of them being different factions is that you know which ones you might want to focus on first instead of having to wait and see which ones are healing their own ships). 

This could also make combat more dynamic, instead of it being just a slug fest on who has more shields and does more damage, and also open up customization for your fleet. Instead of balancing out your ships to not overheat or run out of energy, you could decide to nearly max them out and have other ships keep your main combat ships cool and charged up. This obviously has its ups and downs, in that you might have a lot of fire power in one ship, but it relies on another ship not dying to work.

**Comment by lehgogh** [comment]
These support weapons could be made small enough to fit on fighters, making fighters somewhat useful in large-scale combat.

**Comment by LocalGod79** [comment]
i think this might be mislabeled/misdescribed

you appear to be hoping for an ai personality that is triggered by net negative weapon heat/ion/shield/hull damage, which fires on friendlies rather than hostiles.

**Comment by Amazinite** [comment]
Yes, that's about what I would be looking for. If heat/ion/shield/hull damage are 0 or negative then that weapon will help the ship that it is firing on in game, so I want the AI to be able to realize that the weapon that they are using will heal their target, causing them to use it on allies as opposed to enemies.

**Comment by Amazinite** [comment]
#517
"The AI still won't use them correctly (i.e. it won't use them to heal friendly ships) but at least it's a start."

So it looks like this could happen.

**Comment by Amazinite** [comment]
Maybe instead make an attribute on weapons that causes the ships they're on to friendly fire with them. This way you could make a weapon that say repairs target health but also heats them up.

**Comment by Amazinite** [comment]
Closing this given that it's basically a combination of two other closed issues.
#334
#748

**Comment by tux2603** [comment]
Me Gusta
