### ISSUE TITLE
Impact of piracy by the player on the economy

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#862]
[One of the reviews on steam](http://steamcommunity.com/profiles/76561198080814877/recommended/404410/) -unfortunately negative because of the lack of dynamic prices in 0.8.11- added a new facette to the idea of a said trading system:

> I'd love to feel like pirating a freighter has an impact on the economy

i am not talking about raising the price of goods for each disabled merchant, since the prices probably already reflect the piracy by npcs, but a certain number of stopped ships by the player might change the prica balance a little out of the ordinary.
Once the dynamic trade system is solid, there could be something that reacts on one or more of the following things:

- Number of disabled merchants
- Location of disabled merchants
- Cargo of disabled merchants

I have no relevant idea how to accomplish something like that, but i liked the idea so i threw it in the pot. It's quite low priority i guess, because most player pirates wont notice, except there are bounty hunters or a small side mission. But for those who notice it brings more depth to the game.

**Comment by wargwargwarg** [comment]
lot of coding for a minor detail. I guess there are many more important ones on the line, waiting for programmer time...

Other than that, I'd like to be able to rid a system of pirates, improving the prices of the goods or your rating (and the mission rewards from that planet)
