### ISSUE TITLE
enhancement: new ai personality tag "circling"

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#863]
"gathering"?

i'd like to see some drones which always try to stay next to their flagship.

this behaviour is demonstrated in numerous sci-fi movies and shows, as either supplementary sensor or expendable point defence systems.

this behaviour would indicate a balance point allowing turrets on drones with said behaviour.

**Comment by toilethinges** [comment]
So you're proposing single-turret drones that always stay near the ship containing them? That sounds interesting... very interesting...

+1

**Comment by LocalGod79** [comment]
indeed - nothing crazy - enough for an anti missile turret (maybe as high as mod-blaster) - or perhaps a shield variant with a small regenerator that just takes the odd hit for you...the behaviour could be implemented in a number of ways...

i think coding wise, that the personality would be easiest to implement if they were following the player (just add another personality tag calling an existing behaviour), but following the parent ship would be ideal.

**Comment by lehgogh** [comment]
Would the drone be simply following the flagship, or would it circle the flagship? *insert FTL anti-missile drone here*

**Comment by wargwargwarg** [comment]
nice ideea but for balancing add a power drain when using them or some other limitation. Price alone would not impede spamming some 100 drones :)

**Comment by jafdy** [comment]
You could use fighter bays to limit numbers. As drones are smaller than maned fighters how about 4 drones per bay.

**Comment by toilethinges** [comment]
They would just go in a drone bay like others, I assume. That way it would take less coding and make them less over-powered - they wouldn't be swarming everywhere in unlimited numbers, because they're not jump-capable, meaning they have to be stored in a drone bay.

**Comment by LocalGod79** [comment]
all i'm proposing is an a.i. personality tag calling an existing behaviour - for a ship to follow its flag similarly to the way surveillance drones fly around checking everyone.  it's been a *long* time since i did any C++ coding, and i'm too intimidated by that and the existing code to add it myself (in addition to my life's responsibilities).

i offered a couple of examples of how the personality tag could be used with mildly extrapolated drones, to add context to the request - yes, the drones would fit in the existing drone bays in the o.p.

of course, there are other uses for the tag - off the top of my head, it could be a huge balance drawback to a heavy turret carrying fighter - that cannot actively engage its targets, but must try to follow its flag around - even build huge engines into the hull, and give no outfit space for engines (so that it can always keep up with the flagship), and the explanation almost writes itself...e.m. tether, or something.

or a type of close escort missions/hires, where specially outfitted ships try to stay as close to the player as possible.

lots of uses...

**Comment by endless-sky** [comment]
I've added a "swarming" personality for patrol ships that gather around friendly ships to protect them.

The complication with an escort ship that does this is that if it is that it would need to stop circling the flagship whenever it is time to jump or land - and except when they are in combat, AI ships are *always* either jumping or landing. And when fighting, circling the flagship would interfere with aiming of fixed guns. So, the uses would be limited to ships with only turrets, and only during combat.

**Comment by LocalGod79** [comment]
or as "meatshield" blockers...
