### ISSUE TITLE
Red ship echo appearing

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#8632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm repeatedly seeing some kind of anomaly, a copy of one of my ships (specifically, a Shield Beetle, in systems where there definitely aren't any native Shield Beetles), but all in red, and not selectable.

Clicking on the red ship does nothing, but it flies around like an AI-controlled ship; I've seen it land on a planet, and request refuelling from other ships.

### Steps to Reproduce

Not sure how to reproduce this. It wasn't immediately visible after exiting and restarting the game.

### Expected Behavior

Visible ships should be clickable.

### Screenshots

![Screenshot from 2023-04-05 22-09-13](https://user-images.githubusercontent.com/3080440/230077626-5c436a20-223e-4e26-a9bf-1e41e9bc53e0.png)

### Link to save file

[endless-sky-red-ship.txt](https://github.com/endless-sky/endless-sky/files/11158591/endless-sky-red-ship.txt)

### Operating System

Ubuntu Linux 22.04

### Game Source

GitHub Releases

### Game Version

v0.10.0

### Additional Information

Can't reproduce from the save file.

**Comment by TomGoodIdea** [comment]
I've looked at your savefile, and one of your Shield Beetles, "Vai e Sen" has a Cloaking Device installed. Accidentally enabling the cloaking (the default key is [C]) could be the cause of the described behavior. But iirc cloaked ships can't interact with other ships, so they shouldn't get refueled by them.

**Comment by ThrawnCA** [comment]
Interesting idea. But as mentioned, I've also seen the red ship land on a planet, when I had not given any landing instructions. And in that screenshot, it didn't gather with the others. It's acting like an AI controlled ship. So I don't think it can just be an accidental cloak.

**Comment by Hurleveur** [comment]
It definitely simply is a cloaked ship. Only your cloaked escorts show red like that.
It lands to refuel
As to why it doesnt come mb its out of energy or mb its bugged

**Comment by ThrawnCA** [comment]
> Only your cloaked escorts show red like that.

That's useful information, thankyou.

> As to why it doesnt come mb its out of energy or mb its bugged

It has to be bugged in some way, because as mentioned, I've seen the red ship land on a planet before without being instructed to do so.

I also couldn't click on it to select it.

**Comment by TomGoodIdea** [comment]
> I also couldn't click on it to select it.

If your escort is cloaked, you can't select it by clicking on it, only by drawing a selection box (I guess it's something that should be fixed).

> It has to be bugged in some way, because as mentioned, I've seen the red ship land on a planet before without being instructed to do so.

Was it landing to refuel, or landing and not taking off anymore?

**Comment by ThrawnCA** [comment]
I didn't hang around and check... Is landing to refuel a thing that escorts automatically do?

**Comment by ThrawnCA** [comment]
Sounds like this is intended behaviour, then, I just wasn't familiar enough with cloaking.
