### ISSUE TITLE
Game time adjust

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#865]
Please include an adjust bar for game time, so that players may adjust the speed of the ships to a comfortable level.
I have a fast enough CPU and fights are over almost instantly or much too quick. It can only enhance gameplay if the player had time to try and evade some of the incoming fire.

**Comment by wargwargwarg** [comment]
Nobody had this issue?

**Comment by DingusShingleton** [comment]
I have at times wished there was a time boost function as there was in EVN. I support it.

**Comment by tiennou** [comment]
Yeah, I had the same inverse reaction to the OP — why doesn't Caps Lock speed up the game clock :wink:.

**Comment by Pointedstick** [comment]
Game sped is constant, not controlled by your CPU speed. That would be ridiculous, since everyone has a different CPU speed. If this is reproducible, it's a bug.

**Comment by jafdy** [comment]
60 frames per second is the maximum. It will go lower if a lot is going on but I've never seen it go higher.

**Comment by lehgogh** [comment]
Perhaps @wargwargwarg just has a better CPU than us and can actually reach 60 frames per second?

**Comment by jafdy** [comment]
My game runs at 60 fps until 100+ ships use jump drives or I demand tribute from Earth.

**Comment by wargwargwarg** [comment]
It's hard to quantify. The game stays in 100fps at all times and the movements are too fast for my taste.

Here's a zipped avi from Bandicam, very dumbed down res. Also not my brightest moment.
[EndlessSky 2016-03-25 05-30-31-147.zip](https://github.com/endless-sky/endless-sky/files/189043/EndlessSky.2016-03-25.05-30-31-147.zip)

I'd enjoy it better at some 60% speed, more time to actually think what I'm doing, not just press A and look at the fireworks.
Those ships are heavy, big chunks of metal. It takes time to defeat inertia (imagine some ice skaters instead of ships and you'll get my meaning).

**Comment by endless-sky** [comment]
Unless you've got an odd operating system bug, the game should run at no more than 60 FPS, and combat should progress slowly enough that a ship fighting an equally powerful ship will last at least ten seconds even if they're constantly firing on each other the whole time. A lot of the strategy against larger ships, of course, consists of spotting trouble coming and avoiding it. :)

**Comment by brick96** [comment]
Open up a lot of things, that will slow it down eventually :P

**Comment by wargwargwarg** [comment]
The fights do take at least 10 seconds against an equally powerful ship. Perhaps this is the normal speed of the game and if so, I believe it's unbalanced.
It's much too fast, your ship took 6 months to build, the reason being to make it hard to destroy. 10 seconds is a bit short.
In my view, a fight between comparable ships should take a minute or so, and piloting should matter: evading, positioning just as the charge got to 100%, shooting, evading again, boosting, protecting your weak side, and so on . After shields are down, yes, a powerful torpedo could finish the fight in one shot but otherwise it should take significantly more time.

This time adjust would be an easy first step.

**Comment by DingusShingleton** [comment]
I think what you are looking for is a more intimate, dogfighting type of game, which this is not. With what you are describing, a battle between larger fleets could take hours. With that level of combat, I would think the the whole game would have to be rebalanced so that far fewer ships are around at any given time, and perhaps even limiting the size of your fleet. It would be almost a different game at that point. One which sounds pretty cool actually, but it's a heckuva lot of work.

**Comment by wargwargwarg** [comment]
Is there a rush to blow any one ship in 3 to 10 seconds flat?  Where skill means almost nothing because there is almost no time to display it?

And, i think this change can be done in 2 steps: point and click orders and either decreasing the speed of the game or decreasing the weapon damages (or both).

**Comment by jafdy** [comment]
How about an option that slows the game to half speed, then everyone's happy. (I like it the way it is)

**Comment by wargwargwarg** [comment]
if it get's done, ok. If it doesn't get done, NOT OK.

**Comment by Pointedstick** [comment]
How long does it take a modern tank to knock out another tank? It can be a matter of seconds. Nothing unrealistic about that. If you don't like the feel of the game, play a different game.

**Comment by wargwargwarg** [comment]
Don't be... 
I like the game  but it can be improved.
Also, my point exactly: Can't have high damage at no mass (blaster, laser). The shell is effective because of the pound of  HE propelling it chemically at what, 2km at mach 1.5? But at 100km? 1000km?

**Comment by DingusShingleton** [comment]
> If it doesn't get done, NOT OK.

When you are asking someone to do something for you, it behooves you to be polite. You aren't going to get people to want to help you by acting childish.

If you want to lower weapon damage, by all means, create a plugin. It's extremely easy. Get notepad++, navigate to your endlesssky directory, copy the weapons.txt file into the "Plugins" folder, and then edit it to your hearts content. Set the weapon damages to any number you like and test it. Then you can share it and get feedback, and if people actually like it, you will have something to back you up other than "NOT OK"
