### ISSUE TITLE
Leave unique outfits at the outfitter you accidently sold it to

### ISSUE THREAD

**Issue by thewierdnut** [endless-sky/endless-sky#8660]
### Problem Description

I've accidentally sold my ship containing my tear of skade several times, and if I navigate away from the system before I remember, then its gone forever if I don't restore my save file. 

### Related Issue Links

na

### Desired Solution

It would be nice if unique items stayed at the outfitter if its sold, so that you can pick it up later when you remember it. 

### Alternative Approaches

An alternative might be a warning message, something like "If you leave now, you won't be able to re-purchase this unique outfit later"

**Comment by TomGoodIdea** [comment]
#7404

**Comment by thewierdnut** [comment]
duplicate of #7404
