### ISSUE TITLE
Rename Trading Steam Forum

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#867]
Since the trading steam forum has no real purpose, people start to using it as mod collection.
Maybe rename it, until we have a proper platform for mods(described in the roadmap).

**Comment by Amazinite** [comment]
👌

**Comment by LocalGod79** [comment]
the trading forum is defined by steam - they cannot rename it.  users will infer our purpose re-appropriation.

the best m.z. could do is perhaps pin a topic at the top of the forum.

**Comment by toilethinges** [comment]
Actually, you can make a new forum for modding. Here's an example: http://steamcommunity.com/app/233250/discussions/
Notice how there are:
General Discussions!
Bug Reporting!
Official FAQs!
Suggestions!
Trading!

So actually, you can rename the trading forum, and you can make others.

**Comment by endless-sky** [comment]
Huh. It wouldn't let me delete the "Trading" forum, but it turns out I'm allowed to rename it. So, I changed it to "mods."

**Comment by Wrzlprnft** [comment]
Since it is a transitional solution, it is good enough. Thanks!
