### ISSUE TITLE
Asteroid moving too fast

### ISSUE THREAD

**Issue by Porous2053** [endless-sky/endless-sky#8675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Asteroids are moving so fast that even fighters are having a hard time hitting them.

### Steps to Reproduce

1.  Enter game
2. Attempt to mine anything
3. The asteroids are moving faster than interceptors and fighters.

### Expected Behavior

Asteroids should move slow enough that people are able to mine them.

### Operating System

RHEL 9

### Game Source

ESLauncher2

### Game Version

b51dc84c and later

**Comment by TomGoodIdea** [comment]
There are many systems with asteroids moving so slow that you can mine even with a heavy warship.
Could you write where exactly you've been trying to mine?

**Comment by quyykk** [comment]
Did you have fast forward on?

**Comment by Saugia** [comment]
Varying speeds are intended; some systems do have slower mineables and others have noticably faster mineables; for AI purposes certain systems have a lower speed. but as for the player and in general, there is a decent discrepancy. If there are any specific systems of note, feel free to make an issue on them or comment it.
