### ISSUE TITLE
Upgrade issue after long delay.

### ISSUE THREAD

**Issue by Bag72** [endless-sky/endless-sky#8676]
### Problem Description

I've played the game for some time.   I stopped early 2020 when I found it was getting repetitive for me and I awaited new campaigns and story.
Fast forward to now.  Seen the community and thought time to go back lots of new stuff there.   I've upgraded my PC so lost v.97 something and just loaded the new version.   Looked, everything looked familiar but when I try to exit it gives the systems check and says my thrusters are not working.   It does this for every ship I tried including stock ships.    Yet I have the same kit as when I mothballed the ships three years ago.
I'm guessing that I can't just use the save files from then in the new version.   As I have lots of ships all heavily modified I'd prefer not to go back to the start.  Some of those robot ships were very hard to capture and I spend months on them.  Is there a way to update the save files and keep my fleet?  Either a script or perhaps and old version with an upgrade path.

### Related Issue Links

Don't see any

### Desired Solution

Update to save files.

### Alternative Approaches

Start from Scratch.

**Comment by Bag72** [comment]
Forgot to mention.  I had been backing up the save files and simply restored the 2020 save files to the saved directory after the install of the latest version.

**Comment by Hurleveur** [comment]
Plz provide the savefile

**Comment by Bag72** [comment]
Here is the latest save file.
[Bag The.txt](https://github.com/endless-sky/endless-sky/files/11299433/Bag.The.txt)

**Comment by mOctave** [comment]
That save works just fine for me.

**Comment by Bag72** [comment]
Thank you for testing it.    I've just reinstalled and copied the data across again and it worked fine.   Obviously something I did wrong on the previous install.

@Hecter94 Can you close this as a bug.  It clearly was something I did.  Sorry for wasting everyones time.

**Comment by bene-dictator** [comment]
No problem, better to report something that seems off than leaving it if it was a real problem : )
You can close the issue yourself with the "Close with Comment" button I think.
