### ISSUE TITLE
Choosing which drones/fighters deploy

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#868]
A useful mechanic for the future would be that when you press the deploy key, you get a menu that pops up that allow you to choose which drone/fighters deploy and how many. Either that, or be able to map different keys to different fighters and drones (maybe 1-0). This would mainly be useful for when there are more drone and fighter types and you might want to deploy different drones or fighters for different situations.

**Comment by Wrzlprnft** [comment]
I like the idea with 1-0. but since you would need a extra screen where you can groupd fighters to keys, sit may take a while to work that out. maybe acessable via the pilot info screen? However this develops, i think the D-key should remain as it is.

**Comment by LocalGod79** [comment]
perhaps clicking on the ship icon in your fleet in the bottom left of the h.u.d. to deploy/recall would work?

**Comment by Amazinite** [comment]
I'd open a new issue but there's really no point since this is exactly the issue for it: currently, clicking on a group of fighters or drones on the left-side ship list and hitting deploy will deploy all your fighters and drones, but the fighters that you selected will deploy highlighted with the green markers and only they will follow the orders you give them. As such, I think it would make sense if when you hit deploy, only the selected fighters or drones would deploy instead of all of them.
