### ISSUE TITLE
Add Extra AutoFire Types

### ISSUE THREAD

**Issue by 3agleEmpire** [endless-sky/endless-sky#8683]
### Problem Description

It would be nice if we could add an "AutoFire Turrets" and "AutoFire Guns/Missiles" As Seperate Toggles, Personally I dont know how to add that or I would just do it, I was wondering if one of you ES coders could take a look at this.

### Related Issue Links

(Filler Because I dont know what to put here)

### Desired Solution

If Possible, make the guns/missiles seperate from turrets Autofire, Like 2 Seperate toggle buttons in the Settings screen.

### Alternative Approaches

(Filler Because I dont know what "Alternative Approaches would be [Useful, Helpful] Here)

**Comment by mOctave** [comment]
This should be pretty easy to do. We could just replace the on/off switch with (all, turrets, guns, off) and write some code to check what kind of port something's installed on and determine autofire that way.

If this still hasn't been dealt with in a couple of weeks, please remind me about it and I'll see if I can find time to attempt it myself.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/a81b103007baed68f1d3087784b42cacf6163b0f expands the autofire options so it can be applied to turrets only, guns only, both, or neither.
