### ISSUE TITLE
[BUG] Ships sometimes fail to enter hyperspace.

### ISSUE THREAD

**Issue by 1010todd** [endless-sky/endless-sky#8693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ships fail to jump with randomly, mostly occurring with heavier ships(5000 tons+) with low turn but not always.

Occurs with both Hyperdrive and Scram Drive.

UPDATE: After further tested it seems to be caused by 725b1b2b777818e62fe1b788d9af207424e2cc24 as ships thought it's aligned making no further adjustment but the hyperdrive doesn't consider it aligned yet (escort bar highlights the ships in yellow).

Update 2: Currently trying to cobble up a fix but I'm too incompetent at math to do, so it will take a while. (If anyone can fix it, just go ahead. I'm doing this because I really need to fix it to work on the thing I want to work on.)

<details>
<summary>Full Testing Details</summary>

Some ships fail(aligned at correct speed but never enter hyperspace) to enter hyperspace semi-randomly. Mostly seems to occur with ships heavier than vanilla standard (5000tons+) consistently, heaviest ship I could get to jump is ~3000tons even then it somehow can't jump in some system like Sol, also noted a Container Transport at 1200tons mass failing to jump (My 3k tons ship also failed to jump here).

After further testing with several Bulk Freighters + custom outfit to increase mass (each ship with different mass), engine+outfit cap (for several atomic steering) every ship seems to be able to jump for a while until some randomly cannot anymore. Uninstalling 2~3 atomic steering seems too cause heavier ships to fail to jump on the first jump. Those ships is 19k tons+ with less than 25 in game turn rate.

</details>

### Steps to Reproduce

1. Get very heavy ships. (5000tons+, with low turn.)
2. Jump somewhere.
3. See if it jumps.

### Expected Behavior

All ships with FTL drive when aligned can jump.

### Screenshots

N/A

### Operating System

Windows 10 Pro

### Game Source

Other (please describe)

### Game Version

Self compile(836b719794cc0b52db9585606a1000948a9545ab) and downloaded with tib's ESManager(8ae7a0c3e6121be4e0cb063e127803b0b9799e6e)

### Additional Information

Does not occur with Sam's mining-complete fork which is 2180 commits behind. (https://github.com/samrocketman/endless-sky)

I have suspicion it's commit 725b1b2b777818e62fe1b788d9af207424e2cc24 that causes this, will test with a game prior to this commit to confirm.
UPDATE: Tested, it seems to be the problem. Every ship jumped fine in previous commit.

**Comment by petervdmeer** [comment]
Fixed by merge of #8701.
