### ISSUE TITLE
(Windows): Using the title bar to maximize the game crashes/freezes the game.

### ISSUE THREAD

**Issue by KAWilley** [endless-sky/endless-sky#87]
On Windows, using the title bar to maximize the game window will cause the game to crash.

This does not happen when the game is made to run in full-screen via alt-enter.

See: https://groups.google.com/forum/#!category-topic/endless-sky/qoJQkt29jSY

**Comment by mikezila** [comment]
Just tried this myself.  It only crashes if you click on the frozen game after it's maximized.  If you restore the window to it's previous size the game resumes without issues.  But I am seeing this issue as well.  Win10.

**Comment by endless-sky** [comment]
Could one of you check if this still happens in version 0.8.2? I made a change to how window resizing is done that should make it more robust, but this bug wasn't happening on my Windows 7 machine, so I have no way of knowing if I fixed it.

**Comment by KAWilley** [comment]
Seems to be working on Windows 10 now.

**Comment by mikezila** [comment]
The issue is fixed for me on 0.8.2 on Win10 x64.
