### ISSUE TITLE
First Contact: Bunrodea not starting with Emerald Sword

### ISSUE THREAD

**Issue by my-T1** [endless-sky/endless-sky#8709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When contacting the Bunrodea with the Emerald Sword the storyline doesn't move on when coming back to human space. Switching to a different ship in my fleet made the difference and the contact took place. Switching back to the emerald sword and following the mission to Erabuthro again would make no progress.

### Steps to Reproduce

Try playing the new storyline for the Bunrodea missions with the Emerald Sword.

### Expected Behavior

Missions make progress with the Emerald sword.

### Operating System

Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy with  Kernel: 5.19.0

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by waterhouse** [comment]
Checking the data files (specifically data/bunrodea/bunrodea missions.txt):
```
mission "First Contact: Bunrodea (Hostile)"
        landing
        name "An Intriguing Invitation"
        description "You have received an invitation, or summons, to the marked system by some mantis-like aliens who seem to have been following you around human space."
        source
                near "Sol" 0 100
                not attributes "urban" "station"
                attributes "spaceport"
        destination "Erabuthro"
        clearance "After hailing the planet the map pointed you towards, you hear an alien voice respond. Before you can think of what to say, the small device that the aliens threw at you on <origin> responds for you. The voice on the other end says something short, then cuts the feed. It seems like you've been cleared to land."
        to offer
                random < 10
                or
                        "reputation: Bunrodea" < 1
                        "reputation: Bunrodea (Megasa)" < 1
                        "reputation: Bunrodea (Erabu)" < 1
                        "reputation: Bunrodea (Guard)" < -1
        
```
It doesn't seem to specify anything about the ship you're piloting.  It does have a "random < 10", a 10% chance.  Is it possible you just got unlucky?  You could try editing the data file to give a much higher random chance (or remove the "random" part entirely) to make it easier to test.

**Comment by Amazinite** [comment]
As noted, there's nothing specifically about the Emerald Sword that would prevent this mission from offering. Going to chalk it up to the randomness of the mission offering.
