### ISSUE TITLE
Not enough bunks, too many required crew

### ISSUE THREAD

**Issue by starpengiun** [endless-sky/endless-sky#8727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Recently, I captured a ship that had a problem.  It has a requirement of 9 crew, but only 7 available bunks.  I suspect this was due to the addition of a security station on the ship.  

I ended up disowning the ship because I landed on a planet with no outfitter.  The game would not allow me take the ship into orbit with this problem.  So, without a way to get rid of the security station, I disowned the ship.  This has happened 3 times since this issue popped up.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

If possible, I hope one of these fixes can be put into place:

Maybe a fix where a message indicates a problem, and the mechanics rigged a temporary fix, but the ship must be taken to an outfitter within a set amount of time before it breaks up and blows apart in orbit or something like that?  

Or set up a way to transfer the problematic system(s) into cargo without having to be at an outfitter (if there is room) or to discard it on the planet and leave it (if no room)?

### Operating System

Linux

### Game Source

GitHub Releases

### Game Version

V10.0 

### Additional Information

This issue was discovered while issue #8663 was being worked on.  One bug leads to another, I guess. :-)

**Comment by 1010todd** [comment]
Do you have plugins installed? I also found this problem but I checked and vanilla Security Station do not have any additional required crew and when I strip out plugins for testing something that problem is also gone.

**Comment by TomGoodIdea** [comment]
The game allows you to have less crew due to capturing, so IMO it should also allow you to have more required crew than bunks.

**Comment by starpengiun** [comment]
1010todd, 

I am running multiple mods, and one of those mods modified the Security Station (I am 90% certain it was BetterVanillaPirates , since it was part of a fleet generated by one of its quests, but I have not verified that as of yet).  For some reason, the affected ship in my situation had 2 Security Stations, and each required a person to run it.  

However, in #8663, the same problem was discovered by someone else who was probably testing for it in the vanilla game.  The bug-seeker also received messages regarding too many required crew and not enough bunks for one or more NPC ships.  I do not know what the configuration of his bunk-shorted ships were,though.  

So, if I stripped the mod out of my game, that probably would solve my specific problem, but since the game tester discovered it as well, there may be a slippery little bug in the vanilla game as well.  The person who worked on the #8663 issue mentioned it might be a good idea to open another report for this issue as well.

**Comment by Amazinite** [comment]
Fixed by #8764.
