### ISSUE TITLE
Bug: Ships with 0 hull will not be attacked by the AI

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#873]
I've just noticed that the AI won't attack me when my ship has 0 hull. I guess they think I'm dead already. I'm talking about ships that are set to 0 hull but can still move around.

**Comment by jafdy** [comment]
But why would you want a ship with 0 hull strength?

**Comment by DingusShingleton** [comment]
Yeah I don't know if this would really be considered a bug. A ship with 0 hull SHOULD be dead.

**Comment by LocalGod79** [comment]
indeed - the bug is not that the ai is not attacking you - it's that your ship is not dead.

**Comment by Amazinite** [comment]
Who needs hull when your ship is literally nothing but shields?

Yeah, I thought the same thing Local. 0 hull ships should honestly explode on takeoff.

**Comment by lehgogh** [comment]
It could be an interesting feature to have 0 hull ships with invincible shields. They wouldn't get attacked, but they would still be able to, say, spectate a massive fleet fight between two A.I. fleets.

**Comment by Wrzlprnft** [comment]
Until a AOE-piercing-weapon "happens".

**Comment by LocalGod79** [comment]
any piercing damage, really...which is set to be in the next release...

**Comment by LocalGod79** [comment]
to clarify, this is in reference to ships that have been specified with 0 hull, or reduced to 0 hull?

**Comment by Amazinite** [comment]
Ships that have their hull specifically set to 0, not ships who have been reduced to 0 but still live.

**Comment by Amazinite** [comment]
A possibly work around could be that if your hull equals 0, it won't even let you take off. Similar to if you have no engines or not enough energy. I'll see if I can make that later.

**Comment by jafdy** [comment]
The game doesn't currently have and isn't planed to anything that changes the hull or shield strength so it probably wont be worth the trouble
.

**Comment by LocalGod79** [comment]
agreed - creating and flying a ship with 0 hull will dangerous enough with piercing that this issue can probably be closed (and remain an "easter egg" for whoever tries it)

**Comment by lehgogh** [comment]
@jafdy Modders will probably get around to hull-reducing outfits eventually. It's best that we create this safeguard just in case...

**Comment by jafdy** [comment]
I wont stop you if you want to try but it feels like a pointless exercise to me.

**Comment by Amazinite** [comment]
My own mod has one or two hull and shield reducing items, which is the way I found this bug, but I haven't seen anyone else with them. I'll figure something out myself, and if I get something then I'll make a pull request as a "just in case" kind of thing that wouldn't hurt to add otherwise.

**Comment by Amazinite** [comment]
So i made the ship with 0 hull my escort. It looks like the reason that they cant be attacked is because they can't even be selected to be shot at.

**Comment by Amazinite** [comment]
Yeah, I have no idea how to make something that stops you from launching. So.... *reopen*

**Comment by DingusShingleton** [comment]
Just prevent the player from leaving the outfitter with a ship that has 0 hull. There's no logical reason that a ship with 0 hull would even be able to exist, let alone fly around, so this is the only reasonable answer.

**Comment by endless-sky** [comment]
Fixed in commit ba81681. A ship is not "destroyed" until its hull becomes negative, but in one place I'd been counting a ship with exactly zero hull as non-targetable.

**Comment by Amazinite** [comment]
Nice.

**Comment by Amazinite** [comment]
Keeping open till release

**Comment by Amazinite** [comment]
Confirmed fixed
