### ISSUE TITLE
Map related

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#874]
here's the thing:
In the map screen, before checking the available missions in a system towards the story destination, I usually check the prices for a compound shipment (-20K per jump kinda' hurts). Only, when I finally click the mission tab, the cursor jumps to some other system with a mission... and time and again I accept it and have to abort it afterwards.

Please fix this. Make the mission screen retain the previously selected system (if, of course, it has any missions).

**Comment by LocalGod79** [comment]
if you are on the map screen while landed, and click the 'missions' button in the bottom right, your map cursor will not move.  to return to your price comparison, click 'ports'

**Comment by jafdy** [comment]
I think someone is already working to improve the map but I can't remember who.

**Comment by wargwargwarg** [comment]
I checked and, at least on Steam version, it is as I said:
while landed, press M to enter "Ports" screen, check prices to a nearby system that has a few missions available (found some 150...200 profit per ton from the current port) , click the "Missions" button and....suddenly the selected system differs from my previous selection.

The cursor always auto selects the first mission in the top down list on the left (bulk.... or delivery ....)

**Comment by jafdy** [comment]
Working on and not yet implemented. Sometime in 0.9 I think.

**Comment by jmhorjus** [comment]
Is this similar to what you're looking for?  https://github.com/endless-sky/endless-sky/pull/847

**Comment by wargwargwarg** [comment]
@jmhorjus 
about the same, though in #847 if I selected a destination system 3 jumps away, the mission screen would auto select the first available mission in the current system or intermediary jumps. A lot of ifs to implement that.

My suggestion would work with just a registry cell written when exiting Ports screen and read when opening Missions screen

**Comment by jafdy** [comment]
That's the one I was thinking of.

**Comment by db47h** [comment]
@wargwargwarg 
about #847, it was a test better IMHO than the current implementation but far from ideal. I think you're right, it should indeed just remember the last system the player has selected on any panel, and keep it selected when switching between panels (even going back to the planet view). So when switching to the missions panel, if no mission is available on that (remembered) system, just don't display any mission.

**Comment by jmhorjus** [comment]
If you want it to be remembered everywhere, you could just put a new variable into GameData - then it is effectively global, and can be accessed from any panel.  @db47h

**Comment by endless-sky** [comment]
It's already true that the system "selection" stays the same when switching from one map panel to another. The only thing is that in the missions panel there are two separate selections:

* the currently selected system
* the currently selected mission, which may be in a different system from that one

The current behavior is:

* If you select a different mission, the system it is in is also selected.
* If you select a system, if it contains any missions, the "next" mission it contains is selected.

So maybe the only necessary change would be:

* When the missions panel opens, act as if the currently selected system has been "clicked" - that is, if it contains any missions, select the first mission it contains.

**Comment by wargwargwarg** [comment]
As long as it does not change the selected system when switching screens, it's ok, yes

**Comment by endless-sky** [comment]
I've merged in #847, which I think fixes the main issue here.
