### ISSUE TITLE
[Mac][Minor] Scrolling on Initial Screen

### ISSUE THREAD

**Issue by 20zinnm** [endless-sky/endless-sky#875]
You are able to scroll on the first screen where you give your name, such that the form becomes invisible. It's easily undone but annoying for trackpads.

**Comment by db47h** [comment]
@endless-sky could you assign this one to me? Could be a side effect of #809 / f5168a0

**Comment by endless-sky** [comment]
@db47h: sure, you can take a look at this if you want.

It's also possible I just didn't put an upper limit on scrolling the conversation panel.

**Comment by endless-sky** [comment]
I can't seem to reproduce this. Can you post a screenshot? Also, are you running 0.8.11 or the latest code?
