### ISSUE TITLE
Unstable release being marked as latest is messing with package managers across distributions

### ISSUE THREAD

**Issue by superusercode** [endless-sky/endless-sky#8759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some distributions (and wikidata) are marking 0.10.0 as stable and providing it via their repositories (see https://repology.org/project/endless-sky/versions ). It's not clear if that is actually desired by either this project or the involved package mirrors (as they likely just check the latest tag on github). If this isn't intended, marking 0.10.0 as a prerelease is probably how this could be avoided in the future. 

### Steps to Reproduce

n/a see repology link for examples

### Expected Behavior

Package manager uses the latest stable version.

### Operating System

n/a

### Game Source

Other (please describe)

### Game Version

n/a

**Comment by quyykk** [comment]
Thank you! We are doing this now (but we'll not change old releases, so it's still kinda misleading rn). The latest release should be the last stable one.
