### ISSUE TITLE
Better shield indicator

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#876]
This must have been said before: why not have the shields as a halo surrounding the ship, as a circle at least if not the contour. Something like in Master of Orion 2 (that masterpiece)
![moa2](https://cloud.githubusercontent.com/assets/15882273/14038166/aee9d058-f255-11e5-86b3-4850e909eee8.jpg)
Not necessarily have 4 shields in quadrants (though I'd love that, as it would add some complexity to maneuvering). If it could be done then, it can be done now, right?

**Comment by jmhorjus** [comment]
Are you saying every ship would be flying around in a blue bubble on the main view-screen?
In your screenshot, just as in ES currently, a ship's shield status is displayed in the selection box, not on the main screen.

**Comment by lehgogh** [comment]
Like this? http://tinysubversions.com/pics/KILLEDBOSS2.png

**Comment by wargwargwarg** [comment]
@jmhorjus 
Yes, the shields would be on every ship in the main screen, not on  the small status one. MoA was a turn based game so time to gauge enemy strengths was plentiful. In Endless Sky there is no time to waste.. Not necessarily blue bubble, a greish nuance will do, if not the that outline whose thickness would depend on strength shield at that moment

@lehgogh 
Something like that, though it is also inferior to what MoA did 20 odd years ago

In my opinion, it would add a bit of luster to the visuals and would distract from the static images of the ships.

**Comment by jmhorjus** [comment]
This could be cool, if done well - but as you said, if done clumsily it would distract from the static images of the ships and merely be clutter.  What I would prefer would be a subtle visual effect which was only shown when shields **took damage**.  So when you see a ship taking fire you can see whether the shields are up or down (and perhaps even some subtle difference between hits to a full shield and hits to a critically low shield?), but you wouldn't have all ships constantly flying around in bubbles or something outside of combat.  

I'm not sure if there's any active contributors with the skill-set to pull something like this off well.  I'm no artist myself.

**Comment by wargwargwarg** [comment]
all valid ideas. from what I read, though, the game is struggling already in battles and such finesse requires many more code

The shield contour whose thickness varies with the strength at that moment uses one function (outline) perhaps a few times to simulate the strength.
By shield strength I mean absolute strength. The best shield at full charge would have a thick contour (those 14k, 17K shields). A weak shield at full strength and a strong shield near collapse would have a thin line.

**Comment by LocalGod79** [comment]
@jmhorjus perhaps you could incorporate your idea into #595 , where a lighter shade/hue shift is applied near the impact point?

i really have no idea what i'm talking about, but #595 seems like it could add a lot of visual pizzazz that people are looking for - coupled with shield impact effects - could bring this game to a whole new level, visually.

this issue also seems loosely related to #504

**Comment by Alkallid** [comment]
For actual usefulness and not asthetics, just turn on status overlays. Also, the thing lehgogh mentioned actually goes against lore, as it states in some shield descriptins that it is hull-integrated.

**Comment by jmhorjus** [comment]
"Just turn on status overlays" ... holy crap I've never seen that before. >_< 
Good point.

**Comment by Alkallid** [comment]
Never thought of it? Really?

**Comment by wargwargwarg** [comment]
I'll not try to discuss what the game lore would declare or how fast that could change. 
I'm trying to convince the dev this would be a step forward, with a small to negligible impact on game performance.
Here are 2 variants, shield emanating from the hull and shield projected close to the hull, beside the 2 images with status overlay.
![shield concept](https://cloud.githubusercontent.com/assets/15882273/14058005/1fb31d02-f31a-11e5-9df0-415848604c12.jpg)

If this has been thought out and excluded on some grounds, someone should say so.

**Comment by endless-sky** [comment]
I think it's a matter of aesthetics. My goal has been to keep the display as uncluttered and minimal as possible, and also to avoid anything that looks cartoony or like an arcade game. So, in my opinion glowing green outlines around every ship would not improve the aesthetics, and as others have noted the status overlays are already available for people who want information more than they want aesthetics.

**Comment by brick96** [comment]
Maybe instead of "shields emanating from hull", why not just blue shift the ship, or coursing blue lines over the hull, like in vega conflict

**Comment by wargwargwarg** [comment]
I agree my variants are a bit too cheesy. 
I dislike those circles no end, though, but I need the info they provide. 
How about that blue shift or some other graphical representation. shown only when shift is pressed? Like a scanner, energy consuming,  but showing shield strengths, armaments and so on?

**Comment by Wrzlprnft** [comment]
If i got it right, you do not want some fancy but busy shield to be shown with normal settings, but instead of the status circles a better shield indicator?
For a beginning, the game could stretch those circles to elipsoids around a ship?

**Comment by wargwargwarg** [comment]
Once someone starts thinking for serious and tweaking various ways to better represent the shield strength, progress will be made fast. I won't exclude any option beforehand. It just has to "click", you know?
