### ISSUE TITLE
[Aesthetics] Ability to view larger/full screen images of ships

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#8762]
### Problem Description

The ship images in the Shipyard UI etc. are of a fixed size, which doesn't let you see much detail. But there are certain missions where you get to see much larger photos of ships, such as the Puffin/Penguin (don't remember which) in Ember Waste.

I want to see the game's ships in much more detail than what is available. Their designs are incredible and deserve to be displayed proudly in full screen.

The best one can do right now is to buy each ship and leave the planet, and zoom in completely. But even this only lets you see a top-down view of the ship, nothing else.

### Related Issue Links

N/A

### Desired Solution

A 'gallery view' or 'zoom in' option that lets you view the ship model in much larger detail, from multiple angles.

Maybe even a free-form 3D view that you can rotate/zoom to your heart's content. (Since I read somewhere that the ship models were made in Blender?)

### Alternative Approaches

Put up ship model images somewhere on the website, I suppose.

### Additional Context

If something like this is possible, maybe it could be extended to Outfits as well.

**Comment by Saugia** [comment]
>I want to see the game's ships in much more detail than what is available. Their designs are incredible and deserve to be displayed proudly in full screen.

Actually, ships are designed to be displayed at the specific zoom they currently are and not much more in detail than that, especially when in space. DPI is for seeing the details a bit clearer, otherwise, most models actually aren't designed to be displayed much larger because there will be visual artifacts, model parts that are intentionally not visible at much larger zooms, etc..

**Comment by lumbar527** [comment]
> Maybe even a free-form 3D view that you can rotate/zoom to your heart's content. (Since I read somewhere that the ship models were made in Blender?)

The ships you see in-game have post-processing, which means that a 3D view would not show you everything you see normally.

**Comment by mOctave** [comment]
Although the desired solution would be very difficult, the alternate approach has sort of already been done. It would be cool, though, to extend it, with actual gallery-style images available for some of the more detailed/impressive ships (there's a couple already, sort of, on the website, but only four? of them).

> The ship models are technically in our asset repo. Blender is a free program, and anybody can open it and look at the models in depth at any given time without needing any blender knowledge aside from rotating the view.

Yes, but not everyone has the time/computer storage/tech skills/permission to install Blender and start opening files in it.
