### ISSUE TITLE
Icons do not show up in high-dpi

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#8765]
### Is there an existing issue for this?

- [x] I have searched the existing issues (on GitHub)

### Describe the bug

I cannot see icons that are not high-dpi in the plugins view.

### Steps to Reproduce

1. Have a high-dpi monitor.
2. Have a plugin with only a regular icon
3. Go to the plugins view in Endless Sky.

### Expected Behavior

I expected to see the icon, even though it wasn't high-dpi.

### Screenshots

<img width="1680" alt="I have high-dpi" src="https://github.com/endless-sky/endless-sky/assets/125756761/18b57025-9e4d-4bce-8af2-e2ee413885ec">
I do have high-dpi.

Lost in Midnight has a regular icon, but it does not show.
<img width="1680" alt="Lost in Midnight has an icon" src="https://github.com/endless-sky/endless-sky/assets/125756761/35f68d21-0e14-4046-8003-188c9d60213b">

<img width="169" alt="Lost in Midnight's icon" src="https://github.com/endless-sky/endless-sky/assets/125756761/a84f5057-d47a-4942-92fb-54d631d24c53">

### Operating System

MacOS 10.15.7

### Game Source

GitHub Releases

### Game Version

0.10 to continuous, but I think I've seen this before.

**Comment by lumbar527** [comment]
Closed so I can have more time to search for copies.

**Comment by lumbar527** [comment]
Has anyone else seen this?

**Comment by warp-core** [comment]
Yes
