### ISSUE TITLE
Addition to the Wiki

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#877]
I'm not sure if everyone has seen this yet, but I created spreadsheets of all the ships and outfits in the game with their stats and data. I've posted it to the Google group and the steam forum, but I don't think those are the best places since they can be easily pushed down the forum over time. So I was wondering if it could be pinned at the top of those two forums and/or have a link provided in the wiki for everyone to use, making it easier to build balanced items for mods or to maximize the effectiveness of your fleet.

https://drive.google.com/open?id=0B635z_nU19WfQllrM2V2dWpFSFk

**Comment by LocalGod79** [comment]
perhaps less an "optimize your ship" resource in the forums (which *should* get pushed down - someone looking for this info should have to look at least a little bit, compared to the work you've put in) and more as a "balance metric" resource in the CreatingOutfits/Weapons wiki page?

**Comment by Amazinite** [comment]
Well it could be used as both, but my original idea was to do that where it was just meant for balancing. I only noticed that it was a really good optimization tool after creating everything and finding some interesting outliers that would be really helpful to have. Like how the graviton thrusters are the best thrusters in the game when to comes to thrust per ton, or that the Tek'far Korath fighter reactor is better than almost every other reactor while also being super small.

**Comment by LocalGod79** [comment]
my last words:
it's incomplete as a balance metric (e.g. need heat in power systems), and contains spoilers - you're the only other person i've heard mention the powerful/hot/small Tek'far reactor on their own.

i.m.h.o.;
•should not be pinned (contains spoilers)
•should be added to OutfitCreation wiki as a balance metric (once it's more complete/unified)

**Comment by Amazinite** [comment]
Fair enough, given the spoilers it does make sense to keep it as only a balancing source on the wiki.

And what do you mean that it needs heat in power systems? I have the heat that the system generates and the amount of heat that it generates per each energy that it generates. What all is missing? I have stated in the other two places that I posted it to tell me anything missing or needed, so it would be helpful to have specifics.

**Comment by LocalGod79** [comment]
apologies - i glanced at the energy storage, and the wanderer reactors threw me off...

**Comment by Amazinite** [comment]
Lol, okay. All good. I did put the wanderer items in a few places due to their hybrid nature.

**Comment by Amazinite** [comment]
I've updated the weapons section of the spreadsheets with lifetime and velocity columns that are then used to calculate the range, as well as a reload column that now calculates the RPS, instead of just putting in the RPS and ranges themselves.

**Comment by endless-sky** [comment]
Note that all this information can be dumped from the game itself using the "--ships" or "--weapons" command line options.

**Comment by LocalGod79** [comment]
i think that you need to update the shield energy statistics, now that all generators have the stat...

**Comment by Amazinite** [comment]
Is that coming up in the next update?

**Comment by Amazinite** [comment]
Nvm, found the information on the new shield energy stats. Is the attribute itself being changed in any way, or is it the same as before?

**Comment by Amazinite** [comment]
> "all this information"

Does that include engines, power systems, shield generators, cooling systems, etc? I would check, but I have no idea what a command line is.

**Comment by Amazinite** [comment]
Updated the shield energy stats on the energy generator and renamed the table "Shield Generators (v0.9.0)" I've also added the inaccuracy, hit force, and firing force on all weapons, acceleration and drag on secondary weapons, split the anti-missile turrets from the other turrets, and formatted the columns to mirror the way that the attributes are set up in the text files.
