### ISSUE TITLE
Unlimited Unfettered Hai Equipments

### ISSUE THREAD

**Issue by whoisem** [endless-sky/endless-sky#8771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Once the unfettered Hai start giving weapons for swapping jump drives, if we go without a jump drive but an escort ship has a jump drive, it will give us swapping mission with the reward of Hai weapons. But the jump drive does not get removed from the escort ship. If I keep leaving the system and re-entering, I'm able to get unlimited Hai weapons and a hyperdrive everytime. 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

The jump drive from the escort ship should be removed.

### Operating System

Microsoft Windows 11 Pro - Version	10.0.22621 Build 22621

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by Hurleveur** [comment]
not sure why this was closed I just tested it and the issue is indeed there
since the PR to fix it is rd it wont be left open for long, but still
