### ISSUE TITLE
Unfettered attack player at Everhope in Bote Asu

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#8788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During Hai Reveal. I travel to Everhope to meet the Unfettered fleet. When I take off again the fleet attacks.

Prior to this I have raided the Unfettered worlds and captured ships, so a negative reputation is to be expected. However, I had no issues traveling to Darkcloak with Teneep to ask the Unfettered for aid. I have also run missions to each of the Unfettered planets after taking Teneep and have not encountered hostilities. I checked the systems and they show as friendly before I take off.

### Steps to Reproduce

Leave the planet

### Expected Behavior

I should be on good terms with the Unfettered at this point as we are on our way to Mountaintop.

### Link to save file

[Bradley Boxter.txt](https://github.com/endless-sky/endless-sky/files/11534483/Bradley.Boxter.txt)

### Operating System

Linux

### Game Source

ESLauncher2

### Game Version

0.10.1-alpha e3aa335

**Comment by Hecter94** [comment]
This should be fixed with #8791 being merged. Feel free to open a new issue if you're still seeing the problem.
