### ISSUE TITLE
Missing captured items after consecutive missions

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#879]
After taking 2 pirate hunting missions, having disabled and looted the first (4 particle cannons, Yes!!, said I at the time) and having destroyed the other, I returned to an outfitter to sell the loot. 
What loot? No loot, neither the weapons, powerplant or the tiles from the pirate's bathroom (I had stripped the hull bare)

It isn't the first time to happen.

**Comment by endless-sky** [comment]
Is it possible you already sold the loot in the outfitter (by clicking "sell all")?

**Comment by wargwargwarg** [comment]
Somehow I've not been able to duplicate the problem. No matter how many eliminate pirate missions I took, I did not encounter even one target ship in 1 hour play today.
Also I don't see any sell all button in outfitter (sell all uninstalled, I presume?)

**Comment by IFailAtGaming** [comment]
The sell all button is in the trade screen, it sells everything in the cargo hold

**Comment by jmhorjus** [comment]
I've never had cargo or outfits go missing on me. 
But I have seen the occasional bounty mission where the target ship just didn't seem to be anywhere. I usually just abandon them eventually.

**Comment by jafdy** [comment]
If you need to find the ship for a bounty mission you could look in your save file. The mission will be saved there and you can read off the system the ship is in.
