### ISSUE TITLE
Pirate deterrence isn't recalculated when buying/selling ammo

### ISSUE THREAD

**Issue by waterhouse** [endless-sky/endless-sky#8799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Beyond the title, the problem is best described by the repro steps below.

### Steps to Reproduce

1. Open the attached pilot.
2. Observe that we have 6 Sparrow escorts, each with 4 meteor missile pods and no ammo.
3. Observe that the player info box shows "fleet: sitting duck (-0.0)".  This is currently intended behavior, because Ship::CalculateDeterrence() deliberately avoids counting weapons for which the ship has no ammo.
4. Go to the outfitter, select all the escorts, and buy a bunch of meteor missiles.
5. Look back at the player info box, and observe that it still says "fleet: sitting duck (-0.0)".  This is wrong; it should be higher than that.
6. Go to the outfitter and sell just one of the missile pods per escort.
7. Observe that the player info box now says "fleet: puny defenses (-2.6)".
8. Buy back up to 4 missile pods per escort.
9. Observe that the info box says "fleet: somewhat vulnerable (-3.0)".
10. Sell all the missiles.
11. Observe that we're _still_ at "fleet: somewhat vulnerable (-3.0)".  This is bad; it should be back to 0.
12. Reload the pilot.
13. Observe that we're now back to "fleet: sitting duck (-0.0)".  So reloading does trigger recalculation.

### Expected Behavior

I would have expected that, when buying ammo, it would immediately update the pirate deterrence values; that I wouldn't have to either reload the pilot or buy/sell weapons to make it recalculate.

(I encountered this when buying Sparrows and filling them with missiles, and consulting the info box to see how many I would need, and ... finding that the value was not updated.)

The obvious fix would be to add a recalculation trigger when buying ammo.  I don't know how easy that is.

An alternative fix would be to change the logic so that "whether you have any ammo" no longer counts.  I think this would be logical—given that pirates can't tell whether you're carrying any cargo (when deciding whether to attack you—perhaps they're out of system at the time), I don't see why they could tell whether you're carrying any ammo.  If they can see whether there's a missile loaded into the tube—well, traders who have run out of ammo are probably _extra_-motivated to put a fake missile into there.  I suspect military tactics in general favor weapon systems that conceal how much ammo they have left.

I prefer the second fix.  It _reduces_ code and I feel it has the right flavor.

### Link to save file

[Deterrence Test.txt](https://github.com/endless-sky/endless-sky/files/11571887/Deterrence.Test.txt)

### Operating System

Mac OS Ventura 13.3

### Game Source

Built from source

### Game Version

commit 842291f1b43c3bc08cba4dfd2f5ba245fd2bb84a

**Comment by TomGoodIdea** [comment]
The first fix would be pretty easy to code, but I'd vote for the alternative one.

**Comment by quyykk** [comment]
The alternative sounds reasonable to me too

**Comment by mOctave** [comment]
Me too: it makes sense, especially since cargo attractiveness depends on the cargo space and not your actual cargo, as well.
