### ISSUE TITLE
Cannot unmount weapons

### ISSUE THREAD

**Issue by eltiare** [endless-sky/endless-sky#880]
It'd be nice to be able to unmount weapons and put them into storage. That way we can switch out weapons in places where they're not sold.

**Comment by Amazinite** [comment]
Putting outfits into storage is something that has been requested multiple times before, and is already on the 1.0.0 milestone.

**Comment by jmhorjus** [comment]
This functionality is also included in this pull request: https://github.com/endless-sky/endless-sky/pull/852.

**Comment by endless-sky** [comment]
There are also already several feature requests for this: #677 and #570.

**Comment by eltiare** [comment]
I apologize. I did search for it and didn't find it. :/
