### ISSUE TITLE
Bulk Freighters getting stuck during FW Stack Core 1B

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#8804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After leaving Zeta Aquilae, the bulk freighters from the mission appear to be unable to jump. No amount of time appears to be sufficient for them to align and jump out of the system.
If you stay in the system and hold J, the ships drift off in random directions, appear to be aligned correctly, may appear white or yellow on the escort list with no apparent consistency, and do not jump out with you.

### Steps to Reproduce

Start FW Stack Core 1B
Attempt to leave Zeta Aquilae with the bulk freighters from the mission.

### Expected Behavior

Freighters leave the system after aligning for jump.
If the player is out of the system, Freighters leave the system after some time which they presumably spend aligning for travel.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/18634983/c83f920c-07a9-4ee3-a40a-100df9976749)

### Link to save file

[William Nucleararmament.txt](https://github.com/endless-sky/endless-sky/files/11591443/William.Nucleararmament.txt)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

PR #8670

### Additional Information

(Noticed while running through FW in an attempt to test the nuke changes in #8670)

**Comment by warp-core** [comment]
Can you reproduce this after reloading the save and/or after landing and taking off again?
Can you reproduce this on master?
Can you reproduce it with this commit (https://github.com/Azure3141/endless-sky/commit/7f053fb373ba34d4c675aa492b28f21743a5524d) (which is not currently present on the branch for #8670)?

**Comment by Quantumshark** [comment]
Reloading the save and landing and taking off on the branch don't fix it.
Does seem to be fixed on master, so I'm guessing that commit you mentioned fixes this.
