### ISSUE TITLE
Redundant planet reference in prologue dialog

### ISSUE THREAD

**Issue by aromer** [endless-sky/endless-sky#8813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When meeting Freya Winters in the Pact Recon mission, there is a chance for the same planet appearing in the dialog twice.

```
"Nice to meet you, Captain <last>. Glad to have another helping hand. I'll be heading to <planet> after I've finished 
my business on <origin>, so see you there."
```

This appeared in game as:
_"Nice to meet you, Captain <last>. Glad to have another helping hand. I'll be heading to Glaze after I've finished my business on Glaze, so see you there."_

### Steps to Reproduce

```
mission "Pact Recon 0"
        minor
        name "Pirate Reconnaissance"
        description "Fly through the <waypoints> systems, then report to <destination> so the Southern Mutual Defense Pact can analyze your logs of pi
rate activity (if any)."
        source
                attributes "rim" "south"
                not government "Pirate"
                not system "Alniyat" "Atria" "Lesath" "Han"
        destination "Glaze"
        waypoint "Alniyat"
        waypoint "Atria"
        waypoint "Han"
        waypoint "Lesath"
        to offer
                random < 60
                not "event: war begins"
```

### Expected Behavior

The text could be changed to be less specific regarding Freya's travel plans, or Glaze could be excluded from a possible mission origin.

### Screenshots

<img width="567" alt="Screen Shot 2023-05-29 at 8 04 02 PM" src="https://github.com/endless-sky/endless-sky/assets/5738301/891683e1-530c-4f3e-9fc8-741782398812">

### Operating System

MacOS

### Game Source

Steam

### Game Version

v10.0.1

**Comment by UnorderedSigh** [comment]
My fix in #8846 blocks the mission from offering on Glaze. I did it that way because the story doesn't make sense if she's already on glaze.

Quoting my own PR description,

> In `Pact Recon 0`, Captain Last stumbles upon a recon officer that just happened to be away from Glaze at the moment. She asks you to fly through four systems, and then head to Glaze to meet her upon her return there. The story makes no sense if she is already on Glaze.

**Comment by UnorderedSigh** [comment]
@aromer - My PR #8846 to fix this has been merged. Could you please confirm that it fixes this issue for you?

**Comment by warp-core** [comment]
5031fc7
