### ISSUE TITLE
Help dialog "try out fighters transfer cargo" refers to a settings category which no longer exists

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#8817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This help dialog says to go to the AI section in the settings. This section no longer exists.
https://github.com/endless-sky/endless-sky/blob/1245bfa7d487adfb4e16ecba67c74ed10f8752c7/data/_ui/help.txt#L126-L129

### Steps to Reproduce

Check the settings. No AI section.
![image](https://github.com/endless-sky/endless-sky/assets/17688683/ff0b63c0-a07a-4e23-8994-575c7539fedd)

### Expected Behavior

Fix the help dialog. Should say "Gameplay section."

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v0.10.1

**Comment by warp-core** [comment]
Fixed by https://github.com/endless-sky/endless-sky/commit/e85b9664631f1ca845e1f59a8d2710d9586cd33c
#8890
