### ISSUE TITLE
Update the display of the unbind tooltip

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#8818]
### Problem Description

The "Press 'x' over keybind to unbind" text feels out of place.
![image](https://github.com/endless-sky/endless-sky/assets/17688683/74198d04-f0ce-4a25-9ab4-42a3d8ac26d9)

### Related Issue Links

N/A

### Desired Solution

Add some extra UI element for this text to be on top of instead of having it float in space.

### Alternative Approaches

Create a help dialog that appears the first time you enter the controls page that describes this mechanic, along with other behavior on this page (such as overloading keys).

**Comment by lumbar527** [comment]
I don't actually understand the use of unbinding. If you want to change something, you can do that. Why would you want to have no setting for it?

**Comment by Amazinite** [comment]
There are only so many keys on a keyboard, and you might not want to accidentally press something you'll never intentionally use.
