### ISSUE TITLE
Better Fighter Indicator

### ISSUE THREAD

**Issue by 20zinnm** [endless-sky/endless-sky#882]
Often times, I will forget I had my fighters deployed and leave them behind. It'd be nice to have some visual indication of their status (as my fleet is rather large and it's easy to loose track of the fighters).

**Comment by jafdy** [comment]
Lower left corner. if white then fighters deployed if blue then fighters docked or out system. Do you know about this?

**Comment by 20zinnm** [comment]
No. Is this documented?


Sent from Outlook Mobile






On Sun, Mar 27, 2016 at 2:26 PM -0700, "jafdy" <notifications@github.com> wrote:












Lower left corner. if white then fighters deployed if blue then fighters docked or out system. Do you know about this?

**Comment by endless-sky** [comment]
Right now when you're preparing to jump, escort icons turn green when they're ready to jump with you. I could modify that pretty easily to have them turn red if they're unable to jump with you; that would fix this issue.

**Comment by endless-sky** [comment]
I've added this in commit cbfaa48:

![escorts](https://cloud.githubusercontent.com/assets/11450262/14068920/28d15bc4-f45f-11e5-8e90-9b663455a169.jpg)

**Comment by brick96** [comment]
Maybe a message at the bottom of the screen would be better? Its easy for ships to be pushed off and not be displayed

**Comment by DingusShingleton** [comment]
@endless-sky  Love it

**Comment by 20zinnm** [comment]
Great idea! Even just a status indicator would be nice.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
