### ISSUE TITLE
Using DALL-E to generate images

### ISSUE THREAD

**Issue by ASmoliak** [endless-sky/endless-sky#8829]
### Problem Description

There's a lot of planets in the game, but many of them use Stock earth images. This hurts immersion.

### Related Issue Links

https://openai.com/product/dall-e-2

### Desired Solution

Advancements in AI now allow you to create images based on textual description, I'm not certain about the licensing, but given that this is a free and open-source game, it is probably fine. Here's an example of a picture that's fully AI generated by DALL-E 2,  looks like a badlands of sorts:

![thebadlands](https://github.com/endless-sky/endless-sky/assets/26040470/9314fab8-e8e9-4098-8f55-65a930fa9c9e)

If we can start using AI to generate the images, it could really add to the immersion, you could keep developing things for a long time as well. You can even try plugging in the description of the planet into the AI as well, and it might actually work, though so far it takes me several tries before I get a good enough image.

### Alternative Approaches

I guess you could try using some other AI that can generate images, like Midjourney. Here's a list of a few more: https://www.androidauthority.com/best-dall-e-alternatives-3230514/

**Comment by MCOfficer** [comment]
At this point, the community is not looking to use AI images, see https://github.com/endless-sky/endless-sky/discussions/8787 for more details. Plug-Ins authors are of course free to make their own choices.
