### ISSUE TITLE
Allow arbitrary conditions expressions

### ISSUE THREAD

**Issue by tiennou** [endless-sky/endless-sky#883]
I'm opening this because it's in the roadmap, and I'd be interested in tackling that, I just need a clearer definition for "arbitrary" :wink:.

Does it mean that there should be some `set variable value` "action", and that those user-defined variables can be tested for ?

**Comment by LocalGod79** [comment]
this may be related to #825 - but i'd wait for @endless-sky to confirm

**Comment by endless-sky** [comment]
My idea was that they should be able to handle arbitrary arithmetic expressions. Right now all you can check is `<condition> <compares> <number>`, e.g. `"combat rating" > 1000` or `karma <= 2`. Ideally you would be able to test something like `"combat rating" + 100 * karma + 200 * "ships: Heavy Warship" > 1000 * "offer threshold"`.

**Comment by tehhowch** [comment]
This is achieved in #3128, with the exception of the exponentiation operator. Parentheses are supported.

**Comment by Amazinite** [comment]
Should this be marked as having been done for v0.9.11?

**Comment by tehhowch** [comment]
It is, and it isn't. We don't allow every kind of arbitrary expression (e.g. exponentiation), and there is no run-time token substitution, e.g. accessing mission variables. I don't know that there is a huge request for the former, and I think there is an existing issue requesting condition substitution.

Probably it is fine to close this with 0.9.11

**Comment by Amazinite** [comment]
>I think there is an existing issue requesting condition substitution.

#4173
