### ISSUE TITLE
Explain Controls in the Wiki

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#8834]
### Location

Wiki

### Describe the issue

There are some controls/commands I did not know how to use/activate. One of them was about the `system map send move orders`, which I can't find explained anywhere other than the PR that added it (#2678). The wiki does not explain them.

### Expected content

I think there should be a Wiki page about these controls.

**Comment by TomGoodIdea** [comment]
Related: #4195

**Comment by lumbar527** [comment]
And that's another example of why we should have a page for this!
