### ISSUE TITLE
Dump cargo before looting; "Helpful" navy ships

### ISSUE THREAD

**Issue by nurahtic** [endless-sky/endless-sky#884]
_Hello - I signed up just to leave feedback, as I cannot code. I haven't been this hooked by an open source game since I discovered freeciv! I'm pretty thrilled overall, the team has done fantastic work so far and I think the project has incredible potential!_

Anyway, boarding and looting ships is very important to a combative playstyle, but I see two problems with it.

When docking to a disabled ship, all cargo that it carried is automatically added to your ship's hold. I wanted to take that sweet 9M Armageddon Core, not 160 tons of pumpkins and surgical supplies! There is no way to dump cargo without undocking and re-docking. **A way to dump cargo from the looting screen is my first request.**

In republic controlled systems, navy ships are trigger happy and will destroy disabled pirate vessels, thus denying the player any loot. I can kind of understand this from a thematic standpoint - the republic is vast and it's easier just to execute pirates on the spot as a matter of policy. From a gameplay standpoint, there might be reasons for it too - it would prevent the player from opportunistically looting powerful ships they could have never brought down themselves.

**My second request** - if the difficulty of privateering in republic sectors is not an intentional design decision - is a work-around for this. It is kind of egregious when navy ships warp in to an uninhabited sector and destroy the pirate ships that I took down on my own. Perhaps I'm being trolled.  I can suggest some possible implementations:

- An "assist" flag that determines whether or not navy ships will try to finish off pirates. In my "empty sector" example, they would leave the player be if the pirate has been disabled already. This might have a certain damage threshold that navy ships must reach before they are flagged - perhaps 20%? This way, if the player can only take down the ships quickly enough, their loot is secure.
- Change the usual AI of navy ships in uninhabited sectors to merely disable pirate ships, as they are usually just passing through and there are less navy ships there as a rule. This gives the player some "free zones."

Apologies for the long post. Thoughts?

**Comment by DingusShingleton** [comment]
You can a matter of fact dump cargo while boarding. At the boarding screen, press i. Then simply click on something in your cargo hold, or  "dump all cargo" at the bottom of that panel.

**Comment by jmhorjus** [comment]
Yeah, it's not super obvious that this is an option, but it is supported.  You have to bring up the player-info pannel on top of the boarding pannel to do it.

**Comment by jmhorjus** [comment]
As for friendly ships killing your targets...I'm not sure.  I know having your kills stolen is super aggravating when it happens to a ship you were really hoping to capture or get something good from.  

On the other hand we should make sure any improvements we make to eliminate "annoyances" during play actually add to immersion rather than just subtracting from the (already very low) difficulty.  It's not in character for a navy ship to ever disable and board a pirate.  (The current AI seems to be "don't pick an already disabled ship as your next target, and be willing to switch targets from a disabled ship to a greater threat, but in the absence of other targets always finish off your current target no matter what")

**Comment by wargwargwarg** [comment]
+1 on choosing what to dump and how much. maximize the value per ton: that 9M core insteag of cabbage of same weight but I'd not dump that other medium core also in my hold if I should can only dump some cheap loot

-1 on the second. I've a hunch it's a game device to keep clutter to a minimum (aka drifting ships). Enough ships remain lootable, though rarely the good ones.

**Comment by nurahtic** [comment]
Thanks for the replies.

An interface for selectively dumping cargo seems like the no-brainer, low-hanging fruit here, I expected everyone would be on board with it.

As for the loot conundrum, I would agree that the solution must not further subtract from balanced gameplay, or cause behavior that doesn't make sense thematically. An alternative set of changes came to me last night that make more sense, would be more challenging to implement, no doubt. I propose...

- Scrap fleets. They would be non-playable ships (?), which fill the role of scavenger in the spacefaring ecosystem. The player would compete with them instead of the navy for being the first to descend upon disabled pirate ships.

Still... Not having ships which are essentially auto-disintegrated _would_ increase the potential for free loot in the form of ship components, when the player didn't have to do anything to disable the ships. It presents a balance issue, but I believe this can be amended.

For starters... It doesn't make sense to me that a reactor - likely the component located deepest in the bowels of a ship, and most shielded by the hull to prevent explodey death - can be bloodlessly yoinked from a disabled ship without entering through the airlocks. Leading to...

- External and internal flags for components that determine whether or not they can be taken without first boarding a ship. Reactors and hyperdrives should definitely require boarding, which makes particular sense from a balance standpoint as reactors tend to be the most valuable components anyway. It will be quite impossible to a starting player in their shuttle to take an armageddon core. Weapon mounts are located on the exterior of the hull and can be swiped. Engines and systems are ambiguous, we can arbitrarily flag them as internal to make things harder. 

We're getting somewhere, now. The player needs to take some risk by boarding to get the truly good stuff, and there are less consequences to allowing ships to persist for a while. There is more that can be done, however.

- Make pirates less suicidal. The total civilian and navy firepower of a system can be quantified to determine what sort of forces the pirates throw at systems. Above a certain threshold of lawful firepower, let's say navy bases and adjacent systems, there should be no pirate fleet large enough to succeed in an assault on these systems, and attacks should not occur here. The pirates should have a decent chance at winning, by being scrupulous about their engagements.

Less foolish pirates equates to less freebies, unless the player desires to wade through a dangerous fleet to board civilian ships and be branded a pirate themselves. I maintain that the player should have to work for their loot, an already disabled pirate ship waiting to have its weapons taken should be considered a stroke of luck.

There are further advantages to quantifying local defense... If the strength of pirate attacks are derived from this value, this allows the player to intuitively estimate their strength, and provide a smoother, more granular sense of "leveled areas" beyond Core > Free Worlds > Republic. A starting, freelance bounty hunter in a weak ship would frequent quiet and remote systems on the assumption that pirate attacks would be smaller.

I'd love to volunteer my time to implementing something like this myself, if only I could... I am learning to code though - maybe in the future. Again, I apologize for the wall of text.

**Comment by endless-sky** [comment]
What you're asking for already exists. When you have boarded a ship, press 'I' to bring up the ship info panel, then click on your flagship. In the flagship's info, click on the cargo you want to jettison:

![select](https://cloud.githubusercontent.com/assets/11450262/14162513/704b9b38-f6ba-11e5-96c5-2bfc1a284005.jpg)

Then, click the "Dump Cargo" button to jettison that particular item:

![dump](https://cloud.githubusercontent.com/assets/11450262/14162525/87f2ef0c-f6ba-11e5-8931-56d0e7c79f8c.jpg)

A dialog will pop up confirming that you really want to dump that particular cargo.

There are also several game mechanics already to address your other points. For example, when Navy ships (and all other governments, as well) are looking for something to attack, they will not choose to attack a ship that is already disabled. If you disabled it before the Navy arrived, it's yours, and no one else will interfere.

Also, if you want to do some brawling with pirates, you should do it far enough from the system center or inhabited planets that other ships won't keep appearing nearby and interfering.
