### ISSUE TITLE
Fuel bar animation is too slow

### ISSUE THREAD

**Issue by FliegendeWurst** [endless-sky/endless-sky#885]
This only happens when using a scram drive or jump drive:

![example](https://cloud.githubusercontent.com/assets/12560461/14143510/ef05fa24-f68b-11e5-8522-a39e9b13cb0c.gif)

**Comment by LocalGod79** [comment]
i noticed this, but it never really bothered me.  is this especially annoying to anyone else?

the engine has an animation for 100 fuel consumption (which all interstellar drives consume), which runs in the wind-up of a jump - the scram/jump take their extra fuel requirements (50/100) on jump...

perhaps the scram/jump could have a smooth flow for their remainder 'on enter'?  or would that just set up "why does the scram/jump drive continue using fuel after the jump is completed?"?

it really is no-win, isn't it?

**Comment by Wrzlprnft** [comment]
Maybe calculate the speed of the consumption with the amount?
base speed + (1-100/amount) or something like that?

**Comment by endless-sky** [comment]
Fixed in 36cf5ca.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
