### ISSUE TITLE
Overlapping Galaxies

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#8859]
### Problem Description

I am working on a plugin that adds the Large Magellanic Cloud. I also made a label, which did not show up because it was underneath the other image. Changing the order in `map.txt` does nothing.

### Related Issue Links

N/A (though I don't use Discord)

### Desired Solution

I would like there to be a way for you to set a level for galaxies. For example, there would be the galaxy at 0, then a galaxy that covers it slightly at 1, then a label on to top of both at 2.

### Alternative Approaches

1. Make everything in the `label` file go on top of things in the `ui` file.
2. Have the order in `map.txt` make a difference.

### Additional Context

Covering up the label:
<img width="1680" alt="covering" src="https://github.com/endless-sky/endless-sky/assets/125756761/9d8b58ee-ee0d-4bde-817b-fd7304f68819">
Sprite changed so the label can show:
<img width="1680" alt="hidden" src="https://github.com/endless-sky/endless-sky/assets/125756761/ea8994d2-9da4-4f1d-98cf-7c602e5ef50c">

**Comment by TomGoodIdea** [comment]
How did you name your label in the map file? Does it start with an uppercase `L`?

**Comment by lumbar527** [comment]
The Large Magellanic Cloud is capitalized, the label I called "label" in `map.txt`.

**Comment by TomGoodIdea** [comment]
Have you seen such behavior in the game or only in the plugin editor?

**Comment by lumbar527** [comment]
Haven't checked that yet. I'll do that quick.

**Comment by lumbar527** [comment]
<img width="1680" alt="Screen Shot 2023-06-07 at 4 48 54 PM" src="https://github.com/endless-sky/endless-sky/assets/125756761/03e236ca-29ce-42e7-8cb9-069d830571aa">
As seen in newest continuous.

**Comment by lumbar527** [comment]
Actually, I named the label with a capital "L".
