### ISSUE TITLE
Planet labels are sometimes drawn in bad places

### ISSUE THREAD

**Issue by waterhouse** [endless-sky/endless-sky#8862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="1512" alt="Screenshot 2023-06-07 at 1 39 49 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/27ff5535-ec31-4ecf-a70c-351f6b815b15">
Naively, it looks like Wayfarer and Arachne Station's labels are swapped.  If we zoom in, it becomes clearer:
<img width="1512" alt="Screenshot 2023-06-07 at 1 39 51 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/2ecd1874-36ef-462e-a8ea-be0b2939051e">
<img width="1512" alt="Screenshot 2023-06-07 at 1 39 53 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/758761ae-eca0-4f93-a2ae-f985834f9f83">
The labels are _attached_ to the right planets/stations, it's just that they're sometimes drawn in places that make them closer to the wrong planets/stations.

It isn't always this way.  Sometimes the labels are in good, distinct places:
<img width="1512" alt="Screenshot 2023-06-07 at 2 08 09 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/bc568f58-225c-4cab-b646-d903dd139ad2">

And then sometimes they're in quite unfortunate places.  Echo's label is almost fully hidden:
<img width="1512" alt="Screenshot 2023-06-07 at 2 08 18 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/9bdc8efb-ef00-459b-9323-cb2c902a3c1b">

And sometimes they overlap:
<img width="1512" alt="Screenshot 2023-06-07 at 2 08 26 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/e2fd719c-8803-483b-8b21-f6d0c42e64c2">

(I'm not entirely sure how the orientation is chosen.  It doesn't seem to be randomized every time you land and take off; often it's oriented the same many days in a row.  It does seem like there are 4 different orientations it chooses from: up-right, up-left, down-right, down-left.)

You can also see problems in Kornephoros.  Here we have the label being occluded by another planet:
<img width="1512" alt="Screenshot 2023-06-07 at 2 26 43 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/7bc07d32-a816-4104-91b2-8063888c6517">

And here, on a different day, we have the labels overlapping (I zoomed in a bit, which made it worse here):
<img width="1512" alt="Screenshot 2023-06-07 at 2 27 09 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/690fc0db-c3ac-433f-bd56-ba17d52dbbdd">

Quarg ringworlds technically can be much worse, but since they're all the same label for the same planet it isn't that much of an issue.
<img width="1512" alt="Screenshot 2023-06-07 at 2 33 09 AM" src="https://github.com/endless-sky/endless-sky/assets/160180/80018bdf-f273-4266-9309-f2350a0ac86f">

### Steps to Reproduce

1. Go to Tarazed, Kornephoros, or likely other systems with multiple labeled planets/stations close to each other.
2. Zoom out.
3. See if the labels of the planets are in unfortunate places—overlapping each other, being occluded by planets, and/or looking like they're labeling the wrong thing.
4. If not, land and take off, and go to step 3.

### Expected Behavior

Ideally, when the game decided in what direction to orient a planet's label, it would make some effort to find a direction such that the label would not overlap with either any other planet or any other label.  (Accounting for all potential zoom levels—the current behavior is that the direction does not change when you zoom in, and I think this is good behavior.)  This is not necessarily always possible—e.g. Quarg ringworlds are likely to be a sh*tshow for some algorithms—but the above examples are mostly cases where the label placement was clearly suboptimal.

Spitballing an algorithm:
- For each labeled planet, consider the planets/stations/stars/space objects within some radius (yes, O(n^2), but n is usually small), plus the locations of any labels we've already chosen, and rule out a portion of the 360° arc based on the position (and distance) of that object.
- The non-ruled-out remainder of the 360° arc we call "acceptable".  If we've ruled out the entire 360° arc, then declare the entire arc "acceptable".
- Now we can choose our favorite direction out of the acceptable arc.  We might choose "that which points farthest away from system center", or pick the first acceptable direction starting from clockwise north, or whatever.
 
Implementation-wise, it may be simpler to enumerate directions starting from the most favorite, and use the first one that passes the acceptability checks.  For further simplicity, we could represent the 360° arc using just 8 (or even 4) test points from a compass.

### Operating System

Mac OS Ventura 13.3

### Game Source

Built from source

### Game Version

a14bdff9ce843485f6f3d38a7ebc760aa25171d7

**Comment by quyykk** [comment]
Oh wow I thought we fixed this a while back, apparently not.

> It doesn't seem to be randomized every time you land and take off; often it's oriented the same many days in a row. It does seem like there are 4 different orientations it chooses from: up-right, up-left, down-right, down-left.

yes and yes

> Ideally, when the game decided in what direction to orient a planet's label, it would make some effort to find a direction such that the label would not overlap with either any other planet or any other label. (Accounting for all potential zoom levels—the current behavior is that the direction does not change when you zoom in, and I think this is good behavior.) 

The game does do a check to verify that no labels overlap already. Not sure what is going wrong here :sweat_smile: The direction should change if you zoom in and the labels overlap too.

> it may be simpler to enumerate directions starting from the most favorite, and use the first one that passes the acceptability checks. For further simplicity, we could represent the 360° arc using just 8 (or even 4) test points from a compass.

That's basically what happens in the current algorithm, for the 4 possible directions.

**Comment by flowers9** [comment]
Using the current build (57c08a7), sitting on Tarazed and Kornephoros, I couldn't get this to happen.  None of the nearby unnamed planets was ever close enough to risk an overlap, and the labelled planet/moon pairs always had the tags rotate to prevent overlap.  Sometimes the labels for the pair overlapped, but that's not being checked, just overlap with the object.

I only had the pairs do one loop around each other, so it's possible longer time periods may result in other planets moving close enough to overlap.

**Comment by waterhouse** [comment]
@flowers9 , try editing the date in your pilot file to the date in my screenshots; the date is conveniently the second line in a pilotfile.  For example, to reproduce the first screenshot, I made a fresh pilot on 57c08a7df9, navigated to Tarazed, and edited in the following line:
```
date 17 1 3025
```
Upon reloading, I got this:
<img width="1512" alt="Screenshot 2023-08-13 at 6 11 19 PM" src="https://github.com/endless-sky/endless-sky/assets/160180/8451bae0-ae58-41aa-b6ef-375c1e7d1d9d">
Actually, that's from the following day, since the day increments when you take off.  For an exact repro, edit the date to the previous day, `date 17 1 3025`.  Thus:
<img width="1512" alt="Screenshot 2023-08-13 at 6 16 21 PM" src="https://github.com/endless-sky/endless-sky/assets/160180/fbe36722-2211-438a-86ed-81d512196e9e">

**Comment by Hecter94** [comment]
![image](https://github.com/endless-sky/endless-sky/assets/15916854/136d5dc0-b4b8-4891-bea2-504ca4d0a84e)

Can confirm

**Comment by flowers9** [comment]
That said, nothing checks if labels overlap other labels.

**Comment by quyykk** [comment]
Fixed by d0564f906459ecf0c79c6bc59f3b50598cb66a5d
