### ISSUE TITLE
Wrong Link in Wiki

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#8864]
### Location

Wiki

### Describe the issue

In the [homepage](https://github.com/endless-sky/endless-sky/wiki) in the wiki, under `Playing Endless Sky`, there is a link to the `CONTRIBUTING.md` file - except the path is directly inside `endless-sky`.

### Expected content

I expected the path to correctly reach the file (`docs/CONTRIBUTIN.md`).

**Comment by warp-core** [comment]
Thanks, I updated the link.
