### ISSUE TITLE
Allow Conditions to be pushed directly to Substitutions

### ISSUE THREAD

**Issue by AvianGeneticist** [endless-sky/endless-sky#8865]
### Problem Description

Not too long ago, the ability to customize Substitutions was added, which is a really nice feature for making custom displays and whatnot. However, trying to push specific numbers is a nightmare, as there's no way to directly push a Condition to a Substitution, meaning that if you want a dynamic display to update digit-by-digit, you have to specify a `condition = x` block for every possible value, which starts reasonable and very quickly balloons into insanity working with anything greater than double digits.

I can't think of many uses for vanilla, save for an expanded finances menu (via mission) where the player is able to see their daily credit changes broken down in detail (total tribute, total salary, total crew cost, total maintenance, et cetera).

### Related Issue Links

None that I can find.

### Desired Solution

I don't think this would be too hard on a technical level? The game already knows how to read Conditions from the Substitutions node; the hard part would be how to specify in the data files that you want the game to push a Condition's value rather than its name. My best idea is something like:

![image](https://github.com/endless-sky/endless-sky/assets/64111606/9f77ced2-b938-4e76-ae1f-28c3edfbef17)

### Alternative Approaches

Another way to notate reading a condition's number would be to use a special symbol, like the $ used for calling phrases in conversations. Perhaps a %?

**Comment by UnorderedSigh** [comment]
The syntax is `&[format@condition]` but it only works in conversation text. You can't even put phrases in substitutions.

**Comment by UnorderedSigh** [comment]
This PR might do what you want, indirectly.

- https://github.com/endless-sky/endless-sky/pull/8283

Putting conditions in substitutions everywhere would require having access to PlayerInfo everywhere. This PR makes PlayerInfo accessible:

- https://github.com/endless-sky/endless-sky/pull/8529

I'm working on a way to directly assign calculated text to a global substitution in a GameAction, but I'm still working out the details.

It'll look like this:

```ruby
mission "My Mission"
    on offer
        conversation
             `We're going to rig the election. Who should win?`
             choice
                 `"Me."`
                     goto me
                 `(Point to a random person on the street.)`
                     goto bo
                 `"Stop bugging me, fool"`
                     decline
              label me
              action
                  # Tokens in [braces] have their substitutions, conditions, and phrases expanded.
                  # Then all tokens are appended to make the final string
                  "<Prime Minister>" := "Captain " "[<first> <last>]"
                  # substitutions
                  #     "<Prime Minister>" "Captain First Last"
              branch decline
              label bo
              action
                  # Assignments are processed in the order they're declared.
                  "<Bo Insult>" := [${shakespearean insults}]
                  "<Prime Minister>" := "That " "[<Bo Insult>]" " Old Man Bo"
                  # substitutions
                  #     "<Bo Insult>" "loathsome fool"
                  #     "<Prime Minister>" "That loathsome fool Old Man Bo"
              branch decline
```

**Comment by AvianGeneticist** [comment]
That looks like pretty much exactly what I want.

**Comment by AvianGeneticist** [comment]
> The syntax is `&[format@condition]` but it only works in conversation text. You can't even put phrases in substitutions.

I can't seem to get it to work; is there any documentation I can look at?

**Comment by UnorderedSigh** [comment]
> I can't seem to get it to work; is there any documentation I can look at?

https://github.com/endless-sky/endless-sky/wiki/WritingConversations

**Comment by AvianGeneticist** [comment]
Thank you.
