### ISSUE TITLE
Crash when accomplishing this mission definition.

### ISSUE THREAD

**Issue by Pshy0** [endless-sky/endless-sky#8870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The game crashes when accomplishing the following mission definition (see steps).
EDIT: It crashes when using the AppImage version, but does not crash in all configurations (or it's chaotic). It does crash in `linux-gles-release` / `linux-gles-debug` configurations.

Note that if `on enter "Rutilicus"`, or the last conversation line, are not present, the crash does not happen. The `on enter` does not need to be empty for the crash to happen.

The crash message is as follow (after clearing the mission definition a bit, longer versions will simply result in a segfault):
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```
**EDIT:** Sometime it's this message, sometime it's a segfault.

### Steps to Reproduce

1. Use the `AppImage` or build endless-sky with a `linux-gles-*` configuration.
2. Install this mission:
```endless-sky
mission "CRASH TEST"
	landing
	source "New Boston"
	on offer
		conversation
			"Depart and board the derelict Freighter."
				launch
	on enter "Rutilicus"
	npc save
		government "Team Red"
		ship "Freighter"
		personality staying derelict nemesis
		system "Rutilicus"
		on board
			conversation
				`	If the line 'on enter "Rutilicus"' is not present in the mission, it does not crash.`
				`	Pick the first option cause a crash.`
				choice
					`	(Crash.)`
				`	If this line is not present, no crash happen. Also, if the line 'on enter "Rutilicus"' is not present, it does not crash.`
```
3. Either use an existing pilot, or start a new one and land on New Boston.
4. The mission will cause you to take off, asking you to board the ship. Do that.
5. Click the first option from the conversation: The game crashes.
**EDIT: It's chaotic, sometime it crashes, sometimes not.** Several attempts doing the exact same thing sometimes cause the crash, sometimes not, and with different error messages.

### Expected Behavior

The game should not crash.

### Screenshots

Not applicable.

### Link to save file

Works with new pilots too.

### Operating System

Ubuntu

### Game Source

Github Releases (AppImage)

### Game Version

v0.10.1-alpha (e3aa335)

**Comment by Pshy0** [comment]
Apparently, it does not crashes when built from source, but when using the AppImage from releases.

It still crashes in latest (226df69).

**Comment by Pshy0** [comment]
> Can you post a save file? It is not crashing for me (yet) and it may depend on your ships, conditions, etc.

It happens with new pilots. With the configurations I mentioned, it often crashes at the second attempt (I make a new pilot, do the step, it does not crash, I make another pilot without restarting the game, do the step, and now it crashes).

**Comment by UnorderedSigh** [comment]
Although I was unable to get a crash, I am seeing an abundance of memory access errors from Valgrind about things that can cause a crash.

**Comment by Pshy0** [comment]
![image](https://github.com/endless-sky/endless-sky/assets/44928041/d1e3fb00-fecc-443a-91ad-6ac4ca1420af)
![image](https://github.com/endless-sky/endless-sky/assets/44928041/b8583620-a1df-498f-b8ce-f38fc2babf6e)
Looks like `conversation.Text(node)` does not return a valid reference

**Comment by UnorderedSigh** [comment]
Somehow the `const Conversation &` in the ConversationPanel no longer refers to a valid Conversation object. The NPC class isn't managing its memory correctly.

**Comment by UnorderedSigh** [comment]
I found it. This is what happens:

1. Mission is instantiated, creating a new NPC with a MissionAction that contains the Conversation.
2. The action is triggered. It sends a `const Conversation &` of its conversation to a new ConversationPanel
3. NPC deletes the MissionAction, which deletes the Conversation.
4. The ConversationPanel uses the now-deleted Conversation object.

This is why you should *never* have reference members.

**Comment by UnorderedSigh** [comment]
I did not need the "on enter" event to cause the crash. It's entirely a problem with NPC MissionAction Conversations.

**Comment by UnorderedSigh** [comment]
PR #8877 fixed this for me.

Please test it on your own machine, and let us know if it works.
