### ISSUE TITLE
Sestor ships (Alphas) in Host system have hyperdrive but no jump drive

### ISSUE THREAD

**Issue by CodeKatta** [endless-sky/endless-sky#8878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Actually, it's more of a minor inconsistency than a bug.
The Sestor ships used by the Alphas that appear when you take off from _Avalon_ together with the Navy Cruiser (Danforth) are only equipped with a hyperdrive but not with a jump drive.
However, the _Host_ system is pretty isolated and can only be reached with jump drives. So the Alphas must have put some jump drives into those ships to get them there in the first place. But even if one accepts that they removed them again because they needed them elsewhere (e.g. for their carrier or selling them to the Unfettered Hai) why put the hyperdrive back after you had to take it out for the jump drive in a system where they are superfluous anyway?

### Steps to Reproduce

1. Go to _Host_ system with Adm. Danforth to destroy the Alpha base
2. Land on planet (_Avalon_)
3. Take off again and disable the KIV349 and two MPT53 (take care that Danforth's ship doesn't destroy them)
4. Scan/capture them (repeat if they self destruct)

### Expected Behavior

I'd expect that the Alphas would equip at least the bigger ship (KIV349) with a jump drive so they can take it out of the system if the need should arise (especially as they don't seem to be short on jump drives).
And the hyperdrives could be taken out so they don't waste valuable space. That way you also don't have to unmount it again if you need to leave the system on short notice.

### Screenshots

With the current configuration they can't have both drives (or something else has to go):

![Endless Sky_KIV349_Avalon](https://github.com/endless-sky/endless-sky/assets/26285588/6c997ae0-fac4-48b2-8bfe-affcefad99e5)

### Operating System

Windows 10 Pro version 22H2 build 19045.2965

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by AvianGeneticist** [comment]
This is probably less of a "bug" and more just laziness to not give all the Sestor ships jump drive variants (since Sestor ships already have a large amount of variants already).

**Comment by EjoThims** [comment]
Not even laziness, it's actually a plot point that they play switcheroo to move ships around with fewer JDs than ships. They're not sitting on a high enough number of them to keep stationed defenses outfitted with them, and it's plot relevant later.

If anything, these particular ones don't need HDs, but variants just for that would be bloatful and ruin this early hint to those swaps.

**Comment by CodeKatta** [comment]
> Not even laziness, it's actually a plot point that they play switcheroo to move ships around with fewer JDs than ships. They're not sitting on a high enough number of them to keep stationed defenses outfitted with them, and it's plot relevant later.

Yeah, I mentioned that option in the first post. Game-mechanics-wise the situation is also pretty clear: you just generate those ships _in situ_ according to some template (which probably all contain an HD) and that's it.

However, from an in-game perspective reinstalling a device you just removed for an other one (which is probably a lot of work and not just the click of a button) and whose sole purpose in this environment seems to be to take up space until it has to be removed again, seems to not make a lot of sense. At least that's what you have to think of if you have ever replaced some non-trivial parts on a ship/car/other vehicle.
The most sensible solution in that situation would be to just leave if off altogether, stow it away or sell it.

But maybe I'm just overthinking it a bit 😁

**Comment by waterhouse** [comment]
My brain generates: Maybe a jump drive has a bunch of housing and plumbing that's deeply plugged into the ship, plus a magical crystal core to it, and it's actually less effort to pull out that crystal core and replace it with a less-magical mundane hyperdrive crystal, than it would be to unplug and remove the entire thing.

**Comment by ziproot** [comment]
Should I make a PR that removes their hyperdrive, or is this not going to be implemented? In the latter case, this issue should probably be closed as not planned.
