### ISSUE TITLE
overlapping buttons

### ISSUE THREAD

**Issue by jcq333** [endless-sky/endless-sky#8888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

buttons overlap

### Steps to Reproduce

1. Go to missions on a screen size of 1024x768
2. See error

### Expected Behavior

no overlapping buttons

### Screenshots

![Screenshot from 2023-06-12 08-54-45](https://github.com/endless-sky/endless-sky/assets/81051943/3fb7f256-1510-48a2-a6af-a2d9f9ccfd11)

### Link to save file

[jc jcson.txt](https://github.com/endless-sky/endless-sky/files/11730221/jc.jcson.txt)

### Operating System

Ubuntu 22.04.2 LTS

### Game Source

GitHub Releases

### Game Version

0.10.0

```[tasklist]
### Tasks
- [x] make buttons not overlapp on smaller screens
```

**Comment by TomGoodIdea** [comment]
We can organize the map mode buttons in two rows, like in the Android port.

**Comment by TomGoodIdea** [comment]
Would it be better to change the layout for all screens or leave it as is for larger screens and change only for smaller screens?

**Comment by mOctave** [comment]
Probably to leave it as is for larger screens, if it's possible and memory-efficient enough, as it's more aesthetically pleasing that way.
