### ISSUE TITLE
Long-term Mercenaries

### ISSUE THREAD

**Issue by Fzzr** [endless-sky/endless-sky#8894]
### Problem Description

I propose we add a way to hire temporary mercenary escorts with lower upfront cost, no need for a loan, and no impact on credit rating as compared to acquiring ships directly. There are two main use cases I see:

There is a period in the early-mid game where a trade focused player comes under increased pirate attack. This effectively forces them to start acquiring combat ships, either as flagship or escorts. The increased costs in terms of either upfront cash or large loans runs against that gameplay style. Mercenaries would be a lower-commitment way to fill that need.

Separately, there are certain large scale battles that punish players who haven't been building up a strong flagship or fleet. Being able to bring in a temporary fleet would help those players through such missions.

### Related Issue Links

In #8780 we added a mission where an escort betrays you.
In #8206 hired escorts were also discussed.

### Desired Solution

Mercenaries hiring would happen at the job board. They would be jobs that have either an upfront cost and fixed term or daily upkeep cost with no time limit. That cost should be approximately the crew cost of the ship(s) plus some percent of the cost of the ship(s) hired. The mercs available would be appropriate to the port in question, including in frequency and power of escorts available. This has the potential added benefit of giving players access to the power of not-for-sale ships without resorting to excessive capturing, eg by having Marauder escorts available on pirate worlds.

### Alternative Approaches

I also had an idea for spaceport missions where you buy "used ships" which would be variants at a significant discount but worse base stats. This would be less predictable, but still a more efficient way to add some pirate deterrence than capturing or buying full price. I don't like that idea as much due to the luck and reduced player agency in what they get.

We may need to consider limits on how many mercenaries the player can hire, to prevent them from becoming another way to cheese the game.

### Additional Context

In my mind only, this is also in preparation for a hypothetical future "EV mode" where your fleet size is restricted to 6 owned escorts. Mercenaries would be a way to increase your available force, with a cost.

**Comment by lumbar527** [comment]
I actually want to add this to my plugin, which has short-term escort hiring. ([Fire Corporation](https://github.com/lumbar527/fire-corporation))

Interesting idea!

**Comment by Anarchist2** [comment]
I'm going to reiterate my comments on the linked PR:
>I've always felt that hiring escorts is unnecessary with the existence loans. Both serve as a way to increase your defences beyond your current liquid credits at the cost of future credits. However, escorts are inflexible (especially here, where the destination is predetermined) and, in this implementation, require awkward use of the spaceport. Compare this to loans, which are much more flexible (you can spend the money on more escorts, but also on more freighters or on ship upgrades) and are already in the game.
>
>The big flaw in the betrayal mission is that there's little reason in terms of strict gameplay to actually take the mission: you've already learnt about the profitable trade route, so why would you shell out 80k for the possibility of being a little safer? I think it'd work better if it paid out more like a normal mission, where the escort can hook you up with a bulk freight job to the destination.

It's mentioned that "[paying] upfront cash or large loans runs against that gameplay style," but what is that "gameplay style?" How is it supposed to play? Why is paying a continuous sum for a loan different from paying a continuous sum for an escort?

**Comment by Fzzr** [comment]
So, there are a couple of differences:
- Hiring escorts gives you access to stronger ships sooner, since you're not paying full price.
  - this allows growing your transport fleet faster since you can increase deterrence without having to pause fleet growth regularly for more combat escorts
  -  can also give you access to non-purchasable ships without requiring capping (by way of eg. pirate mercs).t
- since you aren't taking out a loan nor experiencing depreciation on them, you can focus your loan money on transport ships to raise your income faster instead of diverting some to combat ships that take up investment without increasing capacity

**Comment by Anarchist2** [comment]
Is there a problem with forcing the player to find a balance between spending money on combat ships and transports/freighters? In a game system like ES's, there should be advantages and drawbacks to going all in on a strategy, or balancing safety and profit. Having just one "correct" answer doesn't lead to interesting gameplay.

**Comment by Fzzr** [comment]
If we balance it right, they'll still be making a meaningful choice. I think it actually opens up more options. Someone who is deliberately mixing in combat missions probably will still pick a mixed fleet for example. Right now the optimal way to snowball trade is to do it in Hai space, where piracy risk is irrelevant. The player is still choosing not to gain capital in combat ships after all, and will eventually need to get some the normal way. Mercenaries open up a different path to that same ending.

**Comment by quyykk** [comment]
> There is a period in the early-mid game where a trade focused player comes under increased pirate attack. This effectively forces them to start acquiring combat ships, either as flagship or escorts

Not necessarily. You could buy better shielding and/or better engines, a scram drive too.

Here's some recent discussion on a similar feature request: https://github.com/endless-sky/endless-sky/pull/6536
