### ISSUE TITLE
Win32bit Installer

### ISSUE THREAD

**Issue by eghetto** [endless-sky/endless-sky#89]
Please provide a compiled 32bit version

**Comment by KAWilley** [comment]
I'll try to maintain one once I get Code::Blocks going. Right now I've got an issue with the compiler, which I think is because the dependencies aren't set up right.

**Comment by endless-sky** [comment]
I've uploaded a 32-bit Windows release of Endless Sky. As far as I can tell, it is working, but my only Windows machine is 64-bit, so I cannot be certain. Please download it and let me know if it works for you:

https://github.com/endless-sky/endless-sky/releases/download/v0.8.3/endless-sky-win32-0.8.3.zip

**Comment by eghetto** [comment]
Works like a charm - thank you!:)
