### ISSUE TITLE
8 `Pirates Occupying Girtab` mission from Tarazed

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#8904]
### Is there an existing issue for this?

- [X] I have searched the existing issues (On GitHub and Steam)

### Describe the bug

I have too many copies of the same mission (`Pirates Occupying Girtab`), gathered from the same source.

### Steps to Reproduce

1. Go to Tarazed
2. Click on the spaceport for many years, every time you land.
3. Accept `Pirates Occupying Girtab` missions.

### Expected Behavior

I expected there to be some variation on what planet the pirates attack. This may be a quirk of filtering out systems.

### Screenshots

<img width="1680" alt="Screen Shot 2023-06-14 at 10 16 04 AM" src="https://github.com/endless-sky/endless-sky/assets/125756761/e6f52ae9-9e52-41b5-b8fb-bff0955bd1fa">

### Link to save file

[Jimmy Bubbles~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/11748387/Jimmy.Bubbles.previous-1.txt)

### Operating System

MacOS 10.15.7 (Catalina)

### Game Source

ESLauncher2

### Game Version

f51d8d04664d0751ecc1dbafb91e1247 (according to the launcher)

**Comment by warp-core** [comment]
It is indeed the case that Harmony in the Girtab system is the only place that can be selected as a destination for this mission if it is offered in the Tarazed system.

The mission could perhaps be prevented from offering if an instance is already active, or it could be given a deadline, to prevent having many instances active at the same time, though I'm not sure I'd necessarily consider this a bug.

**Comment by lumbar527** [comment]
I think that there shouldn't be 8 pirate groups occupying one system; they would just fight or something. I'm going to make a PR for deadlines, as per your idea.

**Comment by warp-core** [comment]
Closing now that #8905 is merged.
