### ISSUE TITLE
Better error pathing

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#892]
Not sure if this was requested before, but I couldn't find anything talking about it.

Having 18 plugins in my folder, each with dozens of their own text files, it can be hard to find errors without repeatedly removing plugins and launching the game. For example, I have an error telling me that it can not recognize the condition "1." That single one could be anywhere, so it takes a while to debug plugins a lot of the time. It would be nice if the errors file actually said the name of the actual text file that the error is located within and the folders that that file are located within.

So instead of looking like this:
```
Conversation contains unused label "attacks":
  mission "First Contact: Servorum Dei"
    on offer
      conversation
```
an error would look something like:
```
Shields Up
	data
		first contact missions.txt
			Conversation contains unused label "attacks":
				mission "First Contact: Servorum Dei"
					on offer
						conversation
```

This would be a lot more helpful to clean out the errors file without needing to constantly remove plugins and files to find the error.

**Comment by endless-sky** [comment]
If you run the game with the "--debug" command line option, the error log will include file names.

Or, you could just use "grep", or your particular OS's equivalent program for searching a bunch of text files. For example, to track down that error I would just type this in the console on Linux or Mac OS X:

`$ grep -r "First Contact: Servorum Dei" ~/.local/share/endless-sky/plugins/`

(The plugins path would be different on OS X, of course.)

**Comment by Amazinite** [comment]
Is there a list of all the useable commands somewhere?

**Comment by LocalGod79** [comment]
in c.l.
<help>

**Comment by endless-sky** [comment]
```
~/sky$ ./endless-sky --help

Command line options:
    -h, --help: print this help message.
    -v, --version: print version information.
    -s, --ships: print table of ship statistics.
    -w, --weapons: print table of weapon statistics.
    -t, --talk: read and display a conversation from STDIN.
    -r, --resources <path>: load resources from given directory.
    -c, --config <path>: save user's files to given directory.
    -d, --debug: turn on debugging features (e.g. caps lock slow motion).
```
