### ISSUE TITLE
`minables` without a `payload` crash the game while using the `value` option for targeting nearby asteroids

### ISSUE THREAD

**Issue by Saugia** [endless-sky/endless-sky#8929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the `value` option to target nearest asteroids, the game crashes if you attempt to target an "unknown" asteroid (known as the Bioroid found in select Vyrmeid systems). This is likely due to the Bioroids not having a payload, therefore the game is likely crashing from attempting to calculate a value for them.

### Steps to Reproduce

Set "Target Asteroid Based On" to `value`.
Visit "Ae Il M-77", "Is Ce G-460", or "AE Ce L-332" with an asteroid scanner equipped.
Attempt to target nearest asteroid.
Game crashes.

### Expected Behavior

Game does not do the crash thing.

### Link to save file

This save has been provided by Squiddy on Discord.
[Nai_Not (1).txt](https://github.com/endless-sky/endless-sky/files/11783943/Nai_Not.1.txt)

### Operating System

Windows 10; reporter uses Linux.

### Game Source

Continuous Build on Github; reporter uses Steam.

### Game Version

v0.10.2

### Additional Information

The `proximity` option does not have this issue.

Perhaps they should have a value, though I had intended for them to not have one. Preferably, if possible, we edit the code to allow a lack of payload. If not, I could come up with something.

**Comment by RisingLeaf** [comment]
I might have looked at it wrong, but the value was not the problem, as it is default to 0.
The problem was that there was only one minable in the system.

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/138de2fc3aa2d495b325e42814f6c82d09d26dae
