### ISSUE TITLE
missing space in hail

### ISSUE THREAD

**Issue by flowers9** [endless-sky/endless-sky#8942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Minor typo in one of the human hail text.

### Steps to Reproduce

Wait for a long time in Sol (or other human navy heavy system).
Eventually, you'll get a hail that contains " forthree centuries ", " forthree hundred years ", or " forten generations".

### Expected Behavior

Should be a space in there.

### Operating System

Ubuntu 22.04.02 LTS

### Game Source

GitHub Releases

### Game Version

commit 205ca22079866de599fd8325337386d57870266e

### Additional Information

```
--- a/data/human/hails.txt
+++ b/data/human/hails.txt
@@ -2409,7 +2409,7 @@ phrase "friendly navy"
                "the Republic for"
                "the Navy for"
        word
-               "" 6
+               " " 6
                " providing "
                " ensuring "
                " giving you "
```

**Comment by lumbar527** [comment]
I don't see the problem in up-to-date files, and your commit doesn't make a link. Did you make a typo in the commit name?

**Comment by flowers9** [comment]
I certainly might have. ;)  But I checked the up-to-date files first, and it's still there.  If you search on "three centuries", and the word list before that, the first entry is an empty "" , and it should be a space " " (compare it to the other entries, which all start and end with a space).

**Comment by flowers9** [comment]
Looks like someone updated the rest of the list last week (adding spaces), and missed the first entry.

**Comment by flowers9** [comment]
Bug was introduced in this commit:

https://github.com/endless-sky/endless-sky/commit/339eae2e80cbb7ebc8e4710e5888ee7d426c2207

**Comment by lumbar527** [comment]
Sorry, I missed where the error was; thanks for giving me the precise position. (Also, sorry for forgetting a hail there—[339eae2](https://github.com/endless-sky/endless-sky/commit/339eae2e80cbb7ebc8e4710e5888ee7d426c2207) was mine.)

**Comment by Hurleveur** [comment]
For these kind of issues like a space you can just open a PR fixing it, I think.

**Comment by lumbar527** [comment]
I made a change on my fork but it seemed a fairly small thing to make a PR. I'll bring it out.

**Comment by Hurleveur** [comment]
Small PRs just get merged very quickly, especially when they're fixes like thus
