### ISSUE TITLE
Astral Cetacean scan text not consistent with other lifeforms 

### ISSUE THREAD

**Issue by nathan-b** [endless-sky/endless-sky#8947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was exploring some of the new sectors and I found a creature called an Astral Cetacean. Its description is "Indigenous Lifeform", but when I scan it with my outfit scanner, instead of getting the usual "your scanners can't make any sense of this creature's interior", I get an actual readout of the "outfits" the creature is equipped with.

Feel free to close if not a bug, but I figured I'd report it in case it was.

### Steps to Reproduce

* Explore the new sectors in the North-northeast section of the map. 
* If you see a large dot on your scanner, it's probably this guy (I found it in Is-Ce-J591)
* Scan it with an outfit scanner

### Expected Behavior

"Your scanners cannot make sense of this creature's interior"

### Operating System

Linux

### Game Source

Other (please describe)

### Game Version

v0.10.2

### Additional Information

Running from my distro's package manager.

**Comment by Saugia** [comment]
Good catch! It seems I overlooked this attribute on the Cetaceans, they should have `inscrutable`. Will open a PR on it sometime tomorrow.

Hope you enjoyed finding one though, they were a blast to make. ;)

**Comment by nathan-b** [comment]
The solar critters certainly make that stretch of space more interesting!
