### ISSUE TITLE
Enhancement: longer persons cycle

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#895]
with the ability to specify multiple "frequency" attribute specs to increase frequency within the cycle (if this isn't already possible).

reasoning;
@Wrzlprnft and i are working on a character, "Java Joe" (in his coffee machine spaceship - the hull is spoken for, but the name is up for suggestion) who reminds the player to keep track of time, take breaks to go to the washroom, walk around a little, step outside for a breath of fresh air, and of course - get some coffee.

for your health, of course.

but 10 minutes is too short a cycle for "Java Joe" to appear (or you'll end up with some pretty burned out players).  a reminder to stop playing for a minute every 10 will get ignored.

thoughts?
(my first ones: low priority, but something to consider for 1.0.0)

**Comment by endless-sky** [comment]
Every ten minutes, *some* person is spawned. If there are many persons, the average spawn rate for any one of them is much lower, especially if that person's frequency is lower.
