### ISSUE TITLE
bug: Plundered special outfits only show up after reloading save

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#8952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When landing after plundering special outfits with mass, the trading panel doesn't show them as taking up cargo space and they don't appear at all in the outfitter.

When the save is reloaded, they appear correctly.

### Steps to Reproduce

1. Disable the target ship
2. Plunder the gold bars
3. Land

The outfits still show up in the player info panel, and affect the displayed cargo space in the boarding panel.

### Expected Behavior

Reloading the save should not be necessary, the outfits should just show up.

### Link to save file

[Space Shuttle.txt](https://github.com/endless-sky/endless-sky/files/11856538/Space.Shuttle.txt)

### Operating System

EndeavourOS (kernel version: 6.3.9-zen1-1-zen)

### Game Source

Built from source

### Game Version

continuous with 6416

**Comment by TomGoodIdea** [comment]
probably #8941
