### ISSUE TITLE
bug: shield energy

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#896]
in spite of the wiki's suggestion otherwise, shield energy cannot be negative. it triggers the negative value error at flight check.

(i previously believed this to be intentional)

**Comment by endless-sky** [comment]
Oops, forgot that that would happen. Let me think about the right way to work around that.

**Comment by LocalGod79** [comment]
would it be possible to set the attribute's value to 1 if it were undefined, and make the whole variable/attribute a multiplier instead of an additive property?

**Comment by LocalGod79** [comment]
okay, once i actually looked at the code, my previous comment looks ridiculous.

it's a little more obvious than before, but it actually cleans the code up a little bit, doesn't it?

**Comment by LocalGod79** [comment]
it's an exception in the negative value check

**Comment by endless-sky** [comment]
I've checked in a fix for this (33a1999). It requires all shield generators to specify how much energy they use, but it makes the math a whole lot simpler and cleaner than any other option I could think of.

**Comment by LocalGod79** [comment]
@endless-sky don't forget to update the wiki!

**Comment by endless-sky** [comment]
Updated.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
