### ISSUE TITLE
Seems easy to accidentally make entire Hai space hostile

### ISSUE THREAD

**Issue by Wedge009** [endless-sky/endless-sky#8962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I did search existing issues but couldn't find anything related. Apologies if I missed any prior reports.

I note additional Hai factions were added in #6500, included from 0.9.15 onwards. But I didn't notice this problem until 0.10.2 release - while playing 0.9.16.x I don't think I spent much time in Hai space as I recall much of the new content was in other areas. I revisited the Hai, including the Unfettered, as part of the Hai Reveal story (looks like only the prologue is available as of 0.10.2).

With the additional Hai factions, I was unpleasantly surprised when I saw on my map that even 'normal' Hai systems were suddenly marked as hostile. I think what happened was, defending myself against the Unfettered caused the sympathiser Hai merchants to become hostile, and defending myself against them negatively affects my reputation with every other Hai faction. Thus, all Hai factions ultimately become hostile as a result of combat against the Unfettered.

Is this an intentional consequence? I understand the additional factions form part of the Hai Reveal story that, presumably, will become accessible eventually. Fortunately I was able to revert to an earlier save game and thereafter travel in Hai space without escorts to avoid killing the sympathiser merchants (they appear seemingly everywhere in Hai space).

### Steps to Reproduce

1. Attack Unfettered Hai (as seems normal, given default reputation is -1000).
2. Observe player's reputation with 'Hai Merchant (Sympathizers)' faction deteriorate.
3. Attack sympathiser merchants and observe player's reputation with all other Hai factions similarly deteriorate until all Hai space becomes hostile.

### Expected Behavior

I'm not sure what expected behaviour is, hence my question as to whether this is intentional. I was accustomed to the simpler 'normal' Hai vs Unfettered Hai hostilities where fighting the Unfettered did not adversely affect relations with normal Hai. While the additional factions (and the 'normal' Hai sympathy for their more violent brethren) make sense from a lore perspective, in terms of game-play it does not feel nice to unintentionally lose access to a whole chunk of space because of the way this has been implemented.

### Operating System

Linux, but this seems non-OS specific.

### Game Source

Steam

### Game Version

0.10.2

**Comment by Hecter94** [comment]
This _is_ intentional, so I'm removing bug, but it's worth a discussion on wether or not it _should_ be this way.

**Comment by Zireael07** [comment]
If this is intentional, it shouldn't be as easy to cause accidentally.

**Comment by Wedge009** [comment]
> This _is_ intentional, so I'm removing bug, but it's worth a discussion on wether or not it _should_ be this way.

Okay, thanks for the confirmation. As a player, it just wasn't something I was expecting. I assume once the Hai Reveal story is available things will sort themselves out in terms of long-term stability of reputation.

**Comment by mOctave** [comment]
Personally, I find this annoying as well. It's a neat mechanic to keep the player from farming the Unfettered, but at the same time it offers no warning that suddenly the merchants are hostile. At first, I didn't realize that I had made the sympathizers hostile until my fleet had killed them all off and suddenly the normal Hai were attacking me, at which point I looked at my save and was only then able to figure out what was going on.

I think maybe there's been discussion about adding some sort of explanation in-game of what's happening, but I can't recall where that was. Such an explanation would be _very_ useful (maybe, for example, a mission where there's a mob of angry sympathizers when you land somewhere protesting your utter disregard for sentient life, offered automatically once your rep with the sympathizers drops below 0).

**Comment by Wedge009** [comment]
> ...it offers no warning that suddenly the merchants are hostile...
> a mission where there's a mob of angry sympathizers when you land somewhere...

Yes, the lack of information on what's going on and how I had caused the Hai rejection was what disturbed me, not so much the mechanism itself (as I said, from a lore perspective it makes sense). I had my interaction with the Hai and Unfettered so long ago (possibly around 0.9.12) I almost forgot that the normal Hai don't actually dislike their Unfettered brethren but rather see them as misguided. What stuck in my memory was the almost never-ending battles between the Hai and the Unfettered in Wah Ki, so there's a bit of a disconnect between lore and game-play experience there.

**Comment by Hurleveur** [comment]
https://github.com/endless-sky/endless-sky/pull/8944 this PR adds that

**Comment by Wedge009** [comment]
Good. I was looking for a way to do that, and just settled on parking escorts while in Hai space in the end.

**Comment by Wedge009** [comment]
A thought: does fighting off the Unfettered in the Wanderer story have an adverse impact on standing with normal Hai and sympathisers to the Unfettered?

**Comment by MasterOfGrey** [comment]
No, sympathisers only get aggro when they see it happening. Actual rep loss then only occurs when you blow up a sympathiser.

**Comment by Hurleveur** [comment]
@MasterOfGrey I think it would be a good idea to add hails to not interfere in the conflict?
Or maybe a mission that triggers a dialog the first time, although thats mb not needed with the PR you have.

**Comment by Hurleveur** [comment]
From quick testing I noticed something I never did before - and I'm not sure of: does provoke only trigger when the faction is friendly again (say, after bribing) and you shoot them?

Can someone confirm? I can kill a beetle in front of symps and they do nothing but by bribing and then attacking they seem to get provoked.

**Comment by MasterOfGrey** [comment]
> I think it would be a good idea to add hails saying to not interfere in the conflict?

By the time we sort out the warning mission and the provoke only on boarding there should be no problem.
