### ISSUE TITLE
Documentation: persons

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#897]
there is currently nothing on the wiki

specifically,
how often they spawn (and relative to each other), their "hardcore" status, "frequency" attribute, and anything else you can think of that's relevant.

**Comment by endless-sky** [comment]
I've added a [page](https://github.com/endless-sky/endless-sky/wiki/CreatingPersons) describing how persons work.

**Comment by LocalGod79** [comment]
the wiki mentions specifying spawn system by location (implying "dirt belt", "near earth", "core", etc.) - is there a list of these attributes? (as they don't seem to actually be be attached to the systems within map.txt)

otherwise, is it possible to define an npc's spawn location by commodities as an alternate? (e.g.the dirt belt has low food and high plastic - a combo that is nearly exclusive)

**Comment by endless-sky** [comment]
Attributes only apply to planets, so they can only be used for planet filters (used for mission source and destination), not system filters.

For persons, you're limited to filtering by government, by proximity to a named system, or by a list of every system they can appear in.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
