### ISSUE TITLE
[enhancement] [balance] Allow fighters to depart without engine

### ISSUE THREAD

**Issue by NanzeRT** [endless-sky/endless-sky#8979]
### Problem Description

It would be logical to allow fighters to have no engines or energy since they cold just stay in carriers at al time.
It will mainly affect Boxwings since you can throw additional cargo expansion in them.

### Related Issue Links

#7973

### Desired Solution

Allow fighters to depart without engine and/or energy.

### Alternative Approaches

Reason that they require working engines to get into carrier on landing pad or something like so.

### Additional Context

Now it tells to you that "you've heard enough horror stories", so you decide just not to take off. Maybe then it'd be better to mention that ship just physically unable to take off without engines.

**Comment by Hecter94** [comment]
ref: https://github.com/endless-sky/endless-sky/pull/7108

Seems this isn't a desired change.

**Comment by Hurleveur** [comment]
I dont think its a good idea either, the idea isnt to litteraly transform bays into cargo with 100% efficiency

**Comment by 1010todd** [comment]
I think maybe we could write something about a law requiring every manned vessel to have engines or somesort of movement system as safety precaution into the flight check (and maybe the Boxwing description). This would also add a bit to the worldbuilding as well.

**Comment by Hurleveur** [comment]
Yes, mb smth like they should be able to be used as emergency escape pods
