### ISSUE TITLE
Documentation: Build Mac OS X

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#898]
the link in the wiki to sourceforge's libpng 1.4.14 seems to be out of date (now that it's an "older release").

https://sourceforge.net/projects/libpng/files/libpng14/older-releases/1.4.14/

**Comment by endless-sky** [comment]
I'll upgrade to a newer library eventually, as mentioned in #202. I've just been putting it off because I don't want to break anything. :)

**Comment by tiennou** [comment]
Here's [a patch](https://gist.github.com/tiennou/4c4ce1815ee6a2d12dcbf922b470de9b) that uses Homebrew on OS X. Note that release doesn't work because install_path and stuff, but other than that, I haven't had any issue building and running. Would a PR to use Homebrew be acceptable, provided the release can be fixed ?

**Comment by LocalGod79** [comment]
@endless-sky there's nothing wrong with the library - if it works, why mess with it?

it's just the link you've given in the wiki leads to a place where a user may get lost, and install the wrong version. (and the install was clean - i did not need to take any of the extra steps you described)

@tiennou i've managed to get everything together and have compiled another branch of the game.

**Comment by tehhowch** [comment]
This may or may not be resolved

**Comment by tiennou** [comment]
> I'm not sure what the best way to permanently fix the issue is, though.

Stop using Xcode "objects" to keep track of the link dependencies (as they use absolute, realpath-ed references), and instead use linker options. Something like `OTHER_LINKER_FLAGS=-L/usr/local -lsdl2 …`.

This won't do anything for the packaging/`@rpath` issue though — you'll still need to copy those libraries in the final package and `install_name_tool` all references, so end users with "missing" dependencies can still run the final executable.

**Comment by quyykk** [comment]
> This may or may not be resolved

This has in fact already been resolved.
