### ISSUE TITLE
Inconsistent ship description for "Marauder Manta (Weapons)"

### ISSUE THREAD

**Issue by Pshy0** [endless-sky/endless-sky#8988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I quote the ship's description:
> This Manta has undergone extensive modification, **featuring extra gun ports**, ...

Yet, the ship has 6 gun ports, like the non-marauder Manta.

### Steps to Reproduce

Not relevant.

### Expected Behavior

Either the Manta should indeed have more gun ports, or the description should not mention that.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/44928041/2c630c5f-a1e3-4407-9176-b0568ec18698)
![image](https://github.com/endless-sky/endless-sky/assets/44928041/f2cb4768-2fe9-400a-b26d-0f55b4149599)

### Operating System

Not relevant.

### Game Source

Steam

### Game Version

v0.10.2

### Additional Information
Note: All Marauder Mantas have an extra turret mount.

_No response_

**Comment by Hurleveur** [comment]
I think the description should just say it has an additional turret mount - we shouldnt really be buffing these Marauders further.

**Comment by Pshy0** [comment]
Fixed by #8992
