### ISSUE TITLE
Unmarked star system in the interactive map.

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#8993]
### Location

endless-sky.fandom.com

### Describe the issue

There is this circle in the interactive map that has no name or location icon.

![Unmarked star system with pointers](https://github.com/endless-sky/endless-sky/assets/93033911/9d47c4eb-68ff-4b2a-9f6a-9168459ce30a)

### Expected content

I expect it to have a name tag and a "more info pointer symbol".

**Comment by Saugia** [comment]
I will ping @Corraban2, since they maintain our fandom page.

**Comment by warp-core** [comment]
We appreciate the interest, but, as Saugia mentioned, this isn't really the best place for issues with the fandom wiki.
The wiki maintainers have a Discord server: https://discord.gg/du27FkN5jy (also linked on the main page of the wiki.)
I've shared this issue there and you can join to report any other issues you find. It's also possible to leave comments on the wiki pages themselves.
