### ISSUE TITLE
Graphical glitches on Linux in fullscreen mode with Intel HD Graphics

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#9]
As shown in this screenshot: 
![fullscreen](https://cloud.githubusercontent.com/assets/4701338/7184198/321d76d6-e45c-11e4-9cfe-eee30d069e44.jpg)

I also saw it once in windowed mode, but it's a lot easier to reproduce in fullscreen.

My system: Mageia 5, 64 bits
Linux 3.19.4
X.org 1.16.4
Intel HD Graphics with the latest X.org driver (2.99.917)
Mesa 10.4.7

I'll see if I can reproduce with my Nvidia GPU too.

**Comment by endless-sky** [comment]
Does it flicker in and out of this state, or does it stay this way frame
after frame?

Are you able to select items in the conversation panel shown there, or is
the UI unresponsive?

What frame rate is your monitor running at? If you are not running at 60
Hz, does the glitch go away if you switch to 60 Hz?

It looks like the "space objects" layer is somehow being drawn on top of
the other layers of the interface. I haven't seen that before in my
testing, and I'm not sure what would cause it, but I can go through the
code to looks for any obvious race conditions, etc.

**Comment by akien-mga** [comment]
Sorry my initial report was a bit limited, I was in a hurry when posting :)

> Does it flicker in and out of this state, or does it stay this way frame
after frame?

It does flicker. The UI looks fine and sometimes a flickering such as the one shown in the screenshot appears. I'll see if I can grab it when recording the desktop and upload a video.

> What frame rate is your monitor running at? If you are not running at 60
Hz, does the glitch go away if you switch to 60 Hz?

My monitor is running at 59.93 Hz according to the output of ```xrandr```, for a screen resolution of 1920x1080. It seems my monitor is also configured for 1280x960 with a refresh rate of 60.00 Hz, I can try that to see if a perfect 60 Hz fixes the issue.

**Comment by akien-mga** [comment]
Here is a screen recording that exhibits the issue, 1920x1080 with a refresh rate of 59.93 Hz: http://remi.verschelde.fr/files/misc/endless-sky-glitch.mkv

You can see at the beginning of the video that I also reproduced the issue when playing around with the UI while in windowed mode. But it's much more visible in fullscreen.

I've tried with my Nvidia GPU using nvidia's proprietary Linux drivers (version 346.59), and then I can't reproduce the issue anymore. So this looks like an issue with the intel drivers. As to whether it's a bug in the intel drivers, or a bug in your application, I can't say :)

**Comment by endless-sky** [comment]
Thanks for the video. That's really helpful!

My only guess of what could cause this is that maybe your OS is creating the window with Z buffering enabled, so rather than appearing in the order they are drawn, OpenGL is occasionally trying to keep some objects (the stars and the planets) in front of others. I checked in a code change that explicitly disables Z buffering; let me know if you still see this bug in the latest code from Git.

**Comment by akien-mga** [comment]
It looks like 3b4fb17a is not enough to fix the issue. I've confirmed that it happens also if I don't do any input with the mouse or keyboard. And as you said, it tries to put the stars and the planets in front of the HUD, as in:
![fullscreen1](https://cloud.githubusercontent.com/assets/4701338/7197818/d0153e6c-e4e5-11e4-83dc-958359c879ba.jpg)

**Comment by akien-mga** [comment]
I can still reproduce the issue in the current master branch, on the same hardware, and as software:

Mageia 5, 64 bits
Linux 4.1.12
X.org 1.16.4
Intel HD Graphics X.org driver 2.99.917
Mesa 10.5.7

**Comment by Wrzlprnft** [comment]
i recently purchased a laptop with Intel graphics, i run windows 10 and DON't have these issue, however, some other games (like star wars the force unleashed blur bug) have bugs that appear (without any solution) with intel graphics.

**Comment by 5hutd0wn** [comment]
I also have this problem with Intel hd graphics im running ubuntu 16.04 while exploring the korath areas (i did slightly edit my save file to give my self a drak ship :)

**Comment by o11c** [comment]
This is looks Vsync related, not Z-buffer related. The flickering only occurs in the top inch or so of the screen, as if the wait returned slightly too early.

**Comment by 5hutd0wn** [comment]
...That was from last year... I fixed the problem a long time ago.  Although I have no clue how.

**Comment by tehhowch** [comment]
Is this still an issue with the latest official release?

**Comment by Pointedstick** [comment]
I saw this a few times several years ago but haven't seen it in ages. Let's call it fixed until we get another report.
