### ISSUE TITLE
Add fleet pick up flotsom settings

### ISSUE THREAD

**Issue by OcelotWalrus** [endless-sky/endless-sky#9003]
### Problem Description

When you're flying with a fleet, sometimes they automatically pick up flotsoms and it is pretty annoying to get rid of it because, if you dump the cargo of one of your ship, an other ship of your fleet will pick up the cargo you just dumped...

### Related Issue Links

I didn't found any.

### Desired Solution

Add a parameter in the settings to enable/disable fleet pick up flotsom.
The option would be called "fleet flotsom pickup" (or something like that) and the possibilities would be 'flagship only', 'whole fleet' or 'none'. 'flagship only' is for that only the flagship would be able to pick up flotsoms, 'whole fleet' is for that the whole fleet can pick up flotsoms and finally, 'none' is for that either the flagship and the fleet won't be able to pick up flotsoms.

### Alternative Approaches

The parameter could also be only a 'enable' or 'disable' setting.

**Comment by OcelotWalrus** [comment]
Edit: There is actually a setting for the flagship don't collect fotsoms. But there is no setting for the whole fleet.

**Comment by TomGoodIdea** [comment]
When there's flotsam dumped by one of your escorts, your other escorts shouldn't pick it up, since they all share the same government (`Escort`) and the game prevents collection in such situation.

But I'm not sure how it behaves when you've manually ordered them to harvest.

**Comment by OcelotWalrus** [comment]
For me, when I dump one of my ship cargo through the menu that you access by pressing the I key, the other ships if they come over the flotsoms, they pick it up automatically.

**Comment by OcelotWalrus** [comment]
See, the flagship don't pick up after dumping cargo but the other ships of the fleet are:

https://github.com/endless-sky/endless-sky/assets/87318892/fb6422f4-aa5f-422d-ad71-6f01a9e0c01f

**Comment by TomGoodIdea** [comment]
Alright, that's a different case: if you're dumping your *flagship's* cargo, your escorts can collect it. This is useful if you actually want to transfer the cargo, but if you find it annoying, we can of course make it optional.

I think making a preference that prevents escorts from collecting cargo dumped by the flagship would be enough, we don't need to block all collecting.

**Comment by OcelotWalrus** [comment]
Okay that look good!

**Comment by TomGoodIdea** [comment]
> Okay that look good! But I think it's always good to have a setting to block all collecting.

What would such setting be used for?

**Comment by OcelotWalrus** [comment]
If you don't want your fleet to collect flotsam accidentally.

**Comment by OcelotWalrus** [comment]
I actually code the parameter to make that your whole fleet won't pick up any flotsam if it's disabled.

**Comment by OcelotWalrus** [comment]
See https://github.com/endless-sky/endless-sky/pull/9007
