### ISSUE TITLE
Missing category in CreatingShips wiki page (again)

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#9006]
### Location

wiki

### Describe the issue

> "category": the type of ship: "Transport", "Light Freighter", "Heavy Freighter", "Interceptor", "Light Warship", "Medium Warship", "Heavy Warship", "Fighter", or "Drone".
>
> Since v. 0.9.15: "Space Liner", or "Utility".

This is missing Superheavy.

### Expected content

Superheavy should be there.

Also, the "Since" section should be more like

> Since v. 0.9.15: also "Space Liner", or "Utility".

or just add these to the list and put the version behind the category in parentheses, like in most other wiki entries.

**Comment by warp-core** [comment]
Done
