### ISSUE TITLE
Weapons with charge-up

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#902]
I'd like the option to make charge-up weapons to be added to the weapons file. 
It could open up  a new type of weapons and, perhaps, gameplay.

Charge-up as in it takes a number of seconds to progressively charge the capacitor for each such weapon. Discharge in one shot or maybe a burst of shots over 2 seconds, when and if the fire button is pressed.

Over time, the same amount of damage is inflicted, just not in the continuous "rain" of shots we have now.

Also, I'd like the fixed weapons to have a small cone of fire so that the player has to choose when to fire (aka expend the hard rationed energy).

**Comment by LocalGod79** [comment]
https://github.com/endless-sky/endless-sky/commit/46cc7f52a9aad6e01d07615da610e74a08ae1cb4

**Comment by Alkallid** [comment]
This was also a thought of mine- of course, there should be be effects to make it look cooler while charging(Hexad-Partican!) and maybe there would be weapons that don't need to charge, but doing so builds up damage/range/shots/whatever.
Some key attributes to add would maybe be an entirely new block for charge weapons, with the new standard stats and new ones, like: charge time, charge limit(how long it'd be sustained) charge energy and heat, sustain energy and heat(after reaching max) new sprites, an entirely new block for the charge.
Also, maybe there'd be levels of charge, or limit one charging weapon at a time?
The charge guns would act like Secondary weapons, Tab would fire some that don't need to charge like normal, and selecting one with W and pressing the charge key, maybe space, would begin so for all copies of that weapon. Maybe it'd slow or cost more to do multiple at once, and there could be a charge all weapons key.

**Comment by Alkallid** [comment]
Also, will burst be documented in the wiki? I want to be sure on how to build one.

**Comment by Alkallid** [comment]
Oh, and release cost, release time, and releasing force and stuff. Charging could also have force. Perhaps release self-damage.

**Comment by LocalGod79** [comment]
@Alkallid while it's difficult to read your post, i believe everything you've requested is already possible.  yes, 'burst' and 'burst reload' are already documented in the CreatingOutfits wiki (if not in the released game just yet).

@wargwargwarg please close this issue, as it has already been resolved.

**Comment by wargwargwarg** [comment]
**@LocalGod79** read that wiki, thanks (https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits)

While burst is implemented, my suggestion was rather focused on charge-up and fire at specific times, burst being a side thought.
I did not see those options in the Wiki. If I'm wrong, please show me how a blaster should look to do what I said. Thanks

**Comment by LocalGod79** [comment]
all weapons will wait in a "charged" state (unless they're "burst reloading" or "charging") - rather than waiting for a 'death star' 'primary ignition sequence' style wind-up after the player hits the 'fire' key.

if your weapon had the following attributes;
...
"burst count" 6
"burst reload" 51
"reload" 3
...

it would fire six shots (three frames apart), and then "charge" for 51 frames (one second) before firing another six shot burst.

this weapon would have the same dps if the reload was 10, and fired at a constant rate (rather than employing the burst attributes).

**Comment by LocalGod79** [comment]
it's further possible to employ the "stream" or "cluster" attributes to either stagger each weapon's bursts, or to force them to burst-fire simultaneously...

**Comment by LocalGod79** [comment]
further, if you *really* must create a weapon that has a delayed firing mechanism, i suggest you create a firing effect using information from here;
https://github.com/endless-sky/endless-sky/wiki/CreatingEffects
