### ISSUE TITLE
Swizzle masking

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#9021]
### Problem Description

Some ships in the game have parts that should not change colour while applying swizzle. Parts like solar panels are blue and should not appear green or red.

### Related Issue Links

Didn't find anything.

### Desired Solution

Have an optional swizzle mask sprite that shows which areas of a sprite are to be swizzled.
I imagine the plugin author would just have to add a second sprite with a certain ending, maybe swizzle:
osprey~.png
osprey~swizzle.png
This swizzle mask would just be in black and white where white is swizzle and black is no swizzle.

### Alternative Approaches

Maybe reserve some colors from all over the spectrum to not be swizzled? sounds like a bad idea, dunno

**Comment by lumbar527** [comment]
Great idea! I once made a plugin that had a ship with a plasma weapon thing that was visible, but it changed color (Just a usage example)
