### ISSUE TITLE
Missing Aliens in Wiki

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#9027]
### Location

Wiki (StoryIdeas)

### Describe the issue

In the [StoryIdeas](https://github.com/endless-sky/endless-sky/wiki/StoryIdeas#advanced-alien-civilizations) wiki page, alien races are listed with their tiers. The aliens Gegno and Bunrodea are missing from the list.

~From @TomGoodIdea: The Hai could also be move up to T1.5. Refer here for comment suggestion: https://github.com/endless-sky/endless-sky/issues/9027#issuecomment-1631496783~
Edit: Sounds like they aren't that high.

### Expected content

I expected the list of tiers to contain all of the current aliens.

**Comment by TomGoodIdea** [comment]
Maybe also move the Hai from T1 to T1.5.
(I'm not a balance expert though)

**Comment by Quantumshark** [comment]
I would say the Hai fall somewhere between T1 and T1.5 - they're definitely above humanity, but they aren't quite as strong as a midpoint between T1 and T2, which is what T1.5 would imply.

**Comment by Hecter94** [comment]
They're generally considered 1.2, I typically consider them T1 for simplicities sake. T1.5 would definitely be too high.

**Comment by Quantumshark** [comment]
I think it'd be reasonable to call them T1.2

**Comment by TheGiraffe3** [comment]
1: I can make a PR to fix this if needed.
2: Should this be transferred to the wiki repository now?

**Comment by lumbar527** [comment]
Actually, I just checked and this seems to be fixed:
> - Tier 0.8: Gegno
> - Tier 1: Humans
> - Tier 1.2: Hai
> - Tier 1.5: Coalition, Remnant, Korath Exiles and Efreti
> - Tier 1.9: Bunrodea
> - Tier 2: Wanderers, Korath Automata, Ka'het
> - Tier 2.5: Heliarch
> - Tier 3: Quarg
> - Tier 4: Drak
> - Tier ???: Pug (they have ships of different tiers depending on who they are fighting)
