### ISSUE TITLE
CreatingGovernments lacks or contains incorrect documentation

### ISSUE THREAD

**Issue by shitwolfymakes** [endless-sky/endless-sky#9028]
### Location

https://github.com/endless-sky/endless-sky/wiki/CreatingGovernments

### Describe the issue

The wiki page for Governments lacks a block explaining the `illegals` and `atrocities` sections of the grammar.

Additionally, the `atrocities` node in the grammar lacks the ellipsis to denote that the node can contain a list of outfits that are considered such (as I assume is the case)

### Expected content

Explanations and corrected information

**Comment by warp-core** [comment]
I've added the ellipsis to the atrocities in the overview list. https://github.com/endless-sky/endless-sky/wiki/CreatingGovernments/_compare/4c673656f49d52f17c93f29c69665110d90807b4

It looks like the section on the illegals and atrocities nodes was first added in November 2022: https://github.com/endless-sky/endless-sky/wiki/CreatingGovernments/_compare/d7117f6d101500c904ddb301a2a36bfc291eb5f0

And later modified in September 2023: https://github.com/endless-sky/endless-sky/wiki/CreatingGovernments/_compare/4d2c09e5e9882da1638112def70fbd7532349736

Here's a link directly to that section: https://github.com/endless-sky/endless-sky/wiki/CreatingGovernments#illegals-and-atrocities
