### ISSUE TITLE
Wiki entry for CreatingEvents incomplete (unnamed argument)

### ISSUE THREAD

**Issue by SomeTroglodyte** [endless-sky/endless-sky#9030]
### Location

https://github.com/endless-sky/endless-sky/wiki/CreatingEvents

### Describe the issue

Game data contains syntax the wiki does not cover, e.g.: `event "rim archaeology results" 97`

### Expected content

Explain the unit of measurement, receiver, effect... of that second unnamed parameter of the `event` keyword.

ID=97T? 97 Dalmatians? Date 3097-01-01? 97 ticks? 97 days? 97 landings? 97 credits???

My guess: "Any arguments after the name are ignored and may occur in existing game data for purely historical reasons"?
Edit: `GameEvent::Load` never calls `node.Token(2)` so that may even be a good guess...

**Comment by Hecter94** [comment]
The creating events page you have linked is specifically for "creating" events; that syntax you have is triggering an event, which is covered separately:
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#triggers

So, with the example you gave, the event `"rim archaeology results"` is created here:
https://github.com/endless-sky/endless-sky/blob/4bc718ccae8629e6794d35c6211fa0af166f3cca/data/sheragi/archaeology%20missions.txt#L639-L643

And then triggered here:
https://github.com/endless-sky/endless-sky/blob/4bc718ccae8629e6794d35c6211fa0af166f3cca/data/sheragi/archaeology%20missions.txt#L619

Creating the event uses the syntax defined in https://github.com/endless-sky/endless-sky/wiki/CreatingEvents
Triggering the event uses the syntax defined in https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#triggers

So to answer your question, that parameter is the event delay, defined as:
> If a delay is given, the event will occur that number of days from now, instead of happening immediately. If both a minimum and a maximum delay is given, the number of days from now will be chosen randomly from within that interval.
