### ISSUE TITLE
Add an encyclopedia in game

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#904]
Add something that could act as a repository for non-essential information.

It could be used to give large amounts of background info on planets, ships, outfits, whatever. The cloaking device description (#838) I came up with would be the sort of thing that could go in here so you could keep the 'Where is it?' version and have a more detailed description for people who want to read it.

**Comment by Wrzlprnft** [comment]
This could fit in a tab or something of the pilot's logbook

**Comment by LocalGod79** [comment]
would this be a developer, or user populated area?

if it's the latter, were you thinking something like;
https://github.com/endless-sky/endless-sky/wiki/HumanSpace ?
or were you writing the 'large amount of background info'/'more detailed descriptions'?

**Comment by jafdy** [comment]
No,no, this would be in the game. As for who creates it...that's a bit harder. I guess that it would be created by people who want to do it and then approved by @endless-sky before being put in to the game.

**Comment by jafdy** [comment]
I could do some of the legwork in populating it but I would want to know that my work would get used before I put much time in to it.

Also here's some more stuff I came up with:
[Extendid descriptions.docx](https://github.com/endless-sky/endless-sky/files/199918/Extendid.descriptions.docx)

**Comment by wargwargwarg** [comment]
I like the ideea, and @jafdy's take to individual background stories. Usually, in game encyclopedias are the cherry atop the cake for very well thought out and only passion made games. While this is game written with passion, the universe is too static and undifferentiated to actually need an encyclopedia.

**Comment by jafdy** [comment]
We could try it. I'm no programmer but if someone could create a basic form of it in game I could at start to populate it and we can look at the feedback before improving it (if needed). You could use the info menu already in the game so less new GUI is needed.

**Comment by jafdy** [comment]
OK some more stuff if your interested
[Extendid descriptions.docx](https://github.com/endless-sky/endless-sky/files/221610/Extendid.descriptions.docx)
.

**Comment by Amazinite** [comment]
Does the logbook achieve the desired effect or would something more be wanted for this (like an additional section of the logbook for specific ships, outfits, planets, etc. as asked for in OP)?

(Don't mind me, just looking through the least recently updated open issues.)
