### ISSUE TITLE
Documentation: CreatingShips: Variants

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#905]
after [variant hard point redefinition fix](https://github.com/endless-sky/endless-sky/commit/a48ac0a20dd35904327765fae81734f7e797c55b), perhaps an update to the wiki is in order?

**Comment by endless-sky** [comment]
Done.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
