### ISSUE TITLE
outfits in cargo can be shifted to storage without notice when departing

### ISSUE THREAD

**Issue by flowers9** [endless-sky/endless-sky#9056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Outfitter, when putting outfits into cargo only the sum total of cargo space in the fleet is checked.  However, when departing, outfits are placed into specific ships, but this is limited by each ships cargo space, and may leave some outfits unable to fit in depending on how things get arranged.  Any outfits that can't fit are left in planetary storage on the planet.  This happens without any notice or warning.

### Steps to Reproduce

1. Create a fleet of Sparrows (cargo size 15).
2. Go to the Outfitters and buy lots of Hyperdrives (mass 20).
3. Check player info to see that the hyperdrives are all shown in cargo.
4. Depart the planet.
5. Check player info again, and see that there is nothing in cargo.

### Expected Behavior

There should at least be a notice that outfits have been left behind, if not a warning that outfits will be left behind.

Alternatively, fleet cargo space could remain fluid, allowing the same behavoir as on planet (trickier than it sounds, I know).

### Operating System

Ubuntu 22.04.2 LTS

### Game Source

Built from source

### Game Version

current master plus all my PR's

**Comment by TomGoodIdea** [comment]
I think #7645 implements the warning

**Comment by flowers9** [comment]
Yep, that would be it.  Curse my poor searching abilities for missing it. ;)
