### ISSUE TITLE
shipyard missions can be offered in the spaceport

### ISSUE THREAD

**Issue by flowers9** [endless-sky/endless-sky#9057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The shipyard and outfitter tags for missions are not saved.  This can result in a saved shipyard/outfitter mission firing in the spaceport.

### Steps to Reproduce

The only shipyard mission I'm familiar with is one introduced in #9024, which is intended to fire the first time a player visits a non-starter shipyard.  However, if the player saves the game and reloads, it will instead fire in a spaceport.

### Expected Behavior

Shipyard missions should fire in the shipyard, not the spaceport.

### Operating System

Ubuntu 22.04.2 LTS

### Game Source

Built from source

### Game Version

current master + my PR's

### Additional Information

Should be an easy fix, unless there's some reason why those tags aren't saved (which is why I didn't submit a PR instead).

**Comment by Hurleveur** [comment]
I think this was just an oversight

**Comment by flowers9** [comment]
Well, PR time it is, then. ;)

**Comment by Hurleveur** [comment]
I'd wait for the PR to be merged before closing this?

**Comment by flowers9** [comment]
Eh, I figure the PR is as good as an issue for highlighting it?  And we've got tons of issues, so I don't want to clog the list?  Or does it look weird in the PR because the issue is marked closed?

**Comment by Hurleveur** [comment]
For this issue its fine I think but see it this way:
The issue speaks about how we should fix it, and the PR implements one way

**Comment by Saugia** [comment]
Yes, please do not close/solve issues until the relevant PR is merged. This can cause issue or confusion down the line.
