### ISSUE TITLE
occasional overlapping messages

### ISSUE THREAD

**Issue by flowers9** [endless-sky/endless-sky#9060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the message area when in space, every so often two messages will get printed on the same line, making them both effectively unreadable.

### Steps to Reproduce

Don't know how to reproduce.  I suspect some message is missing a \n or something, but it's hard to see which one.

### Expected Behavior

Messages should appear one per line, without overlap.

### Screenshots
![Screenshot from 2023-07-21 18-27-07](https://github.com/endless-sky/endless-sky/assets/11161996/c4e63fef-a6c6-4323-865f-4736ca384473)

### Link to save file
Right after it happened:
[Karla Hoffman.txt](https://github.com/endless-sky/endless-sky/files/12135393/Karla.Hoffman.txt)
Shortly before it happened:
[Karla Hoffman~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/12135394/Karla.Hoffman.previous-1.txt)

### Operating System

Ubuntu 22.04.2 LTS

### Game Source

Built from source

### Game Version

current master + my PR's

### Additional Information

**Comment by TomGoodIdea** [comment]
I've been seeing this bug for a while, too.
I don't know what causes this error, but I think messages don't require having any endline markers.

**Comment by OcelotWalrus** [comment]
Yes, it happens to me too sometimes. Maybe adding a sort of a cooldown to the text that appears could fix the problem?

**Comment by Hecter94** [comment]
Just FYI, one of the messages appears to be: `"You can land on more than one moon or station in this system. Landing on Fenris Station"`
https://github.com/endless-sky/endless-sky/blob/3860eca102a93b77df41c94658a64ea6d85bc7a1/source/AI.cpp#L4075-L4087

I can't make out what the other message in.

**Comment by Amazinite** [comment]
I know this has occurred in the past, but I can't seem to find a related issue or PR. If I recall correctly, the cause is actually a hail with a trailing space.

**Comment by Hecter94** [comment]
Hm, I still can't make out the other overlapping message, but it appears to end in "the paradise worlds."
There are a couple of hails that end with that, but none seem to have trailing spaces:
https://github.com/endless-sky/endless-sky/blob/3860eca102a93b77df41c94658a64ea6d85bc7a1/data/human/hails.txt#L1332-L1333

**Comment by flowers9** [comment]
Pretty sure you're correct, Amazinite.  Many thanks for the pointer.

**Comment by flowers9** [comment]
Yep - I put a space at the end of most of the navy hails, hung around in Sol on fast-forward, and saw regular overwrites.
