### ISSUE TITLE
Debian package outdated

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#9064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The debian package of endless-sky(https://tracker.debian.org/pkg/endless-sky) is quite outdated and even marked for removal this august.
It seems like it had been maintained by MZ, who is not active anymore, and is now without a maintainer. It has nearly a thousand downloads (https://qa.debian.org/popcon.php?package=endless-sky) and I think having an actual debian package is just a nice thing. I personally like to be able to update and maintain my software over the package manager.

### Steps to Reproduce

N/A

### Expected Behavior

I think it would be nice if it was under maintenance.

### Screenshots

N/A

### Operating System

Debian

### Game Source

Other (please describe)

### Game Version

0.9.8-1.2

**Comment by TomGoodIdea** [comment]
It's probably a much larger problem, since other Debian-based distros are likely to use the version provided by Debian (I know Ubuntu does, not sure about others).
But that means updating the package in Debian repos should result in other instances being updated, too.

**Comment by Hecter94** [comment]
#4630 seems relevant.

We also had someone from the Debian community reach out to us about getting someone to help maintain the Debian package back in November of last year, but, afaik, nothing came of it.

**Comment by quyykk** [comment]
The Debian package has been updated! https://packages.debian.org/sid/endless-sky
