### ISSUE TITLE
Pilot's Logbook

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#907]
One issue involving the idea of the logbook ( #237 ) is marked for the 0.9.0 milestone.
since there's not much information out there, i made this issue to move it to attention, and for @endless-sky to share his ideas, as well as others to contribute.
As far as i know it shall contain the following ideas in some form:
- entries to major storyline events ([-> Roadmap](https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap))
- player made notes to e.g. planets and systems. ( #237 )
- some sort of commendations, similar to medals or something you actually gain ingame, not a steam-like array of artifical-replay-value-achievements ( #350 )

**Comment by LocalGod79** [comment]
i think that the roadmap goal and 350 are the same thing
