### ISSUE TITLE
Missing double quotes in dialoges

### ISSUE THREAD

**Issue by DarkSpir** [endless-sky/endless-sky#9080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During my last playthough I noticed a few missing double quotes in dialoges of free worlds 0 prologue and free worlds 3 reconciliation. So I quickly made a fork and fixed the strings whenever I noticed a typo.

### Steps to Reproduce

First typo is in mission FW Escort 3 at the beginning when choosing the dialoge option "What exactly is the Council?". Every line in the response of Tomek starts with a double quote but does not end with one.

Second typo is in mission FW Syndicate Extremists 1A also at the beginning when choosing the dialoge option "Was the information from the Oracle accurate?". In the response Alastair snaps at Danforth and that one also starts with a double quote but does not end with one.

### Expected Behavior

Character lines that start with a double quote also end with one.

### Operating System

Linux

### Game Source

GitHub Releases

### Game Version

v0.9.16.1

### Additional Information

Since its an old version I checked the recent mission files before opening this bug report and did not find any changes yet. I open this bug report to post a pull request with my fixes for the typos.

**Comment by EjoThims** [comment]
> Makes sense for the Free Worlds 0 Prologue change. But in that case the beginning double quotes on the next line are the typo?

Nope, always starts with quotes to show it's still spoken text.

https://style.mla.org/speech-paragraphs-quotation-marks/

> But for Free Worlds 3 Reconciliation the next line starts with a reply from Danford, at least that's how I read it here. In that case Alastairs text should end with a double quote. If the second line also comes from Alastair, it should not start with a double quote.

Also nope, Alastair is continuing to explain why he accepted the Alpha's help. Specifically "... why I'm telling you all this" can -only- be done by Alastair here, since Danforth doesn't know that information.

Closing this, since all of these are correct as is.
