### ISSUE TITLE
Repeatable missions with "fail" fail all instances

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#9093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a mission action calls for a mission to fail, it fails all instances of that mission. This is relevant because a `fail` action without any other parameters defaults to `fail "<mission name>"`, meaning that, if a repeatable job uses `fail`, it fails every other job with the same name.

Right now, this only affects the refactored bounty jobs. Every other failing mission is either non-repeating or fails upon being accepted.

### Steps to Reproduce

1. Download and load the savefile attached to this issue.
2. Check the map and see that there are three missions active.
3. Jump to Dschubba and destroy the bounty ship there.
4. Land your ship and look at the map to find only one mission active.

### Expected Behavior

`fail` without any other qualifiers should only fail the mission it is in, and not any other missions with the same name. If this isn't possible, then the original bounty job behaviour should be restored.

### Link to save file

[Star Light~3013-12-16.txt](https://github.com/endless-sky/endless-sky/files/12206525/Star.Light.3013-12-16.txt)

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

4b8cbe960bee318275b5118fc631e503e381c6df

**Comment by Amazinite** [comment]
`fail` without a mission name should be changed to grab the UUID of the mission that the fail action is for, ensuring that we're not accidentally failing other missions.

We could also probably introduce a new keyword that intentionally has this "fail all instances" behavior. But seeing as how the existing `fail` keyword isn't really behaving as described, I think it makes sense to have that be the keyword that changes its behavior as opposed to keeping it the way it is and creating a new keyword that fails based off of the UUID of the mission.
