### ISSUE TITLE
Submunitions not behaving as expected?

### ISSUE THREAD

**Issue by KAWilley** [endless-sky/endless-sky#91]
I'm not sure if this is a glitch with the game, or with my content. I'm working on a minelayer that fires a lot of relatively small projectiles. Right now the following happens when it should be firing five mines per launcher (the current ship has four minelayers, so it should be leaving 20! projectiles in its wake). 

These are the outfits:

outfit "Dandelion Minelayer"
	category "Secondary Weapons"
	cost 200000
	thumbnail "outfit/dandelionminelayer"
	"mass" 15
	"outfit space" -15
	"weapon capacity" -10
	"gun ports" -1
	"dandelion mine capacity" 100
	weapon
		sprite "projectile/dandelion"
			"frame rate" 10
		sound "minelayer"
		icon "icon/dandelion"
		ammo "Dandelion Mine"
		"submunition" "Dandelion Pod" 4
		"die effect" "missile death"
		"hit effect" "small explosion"
		"inaccuracy" 45
		"velocity" -1
		"lifetime" 3000
		"reload" 20
		"hit force" 20
		"shield damage" 60
		"hull damage" 60
		"missile strength" 10
	description "The Dandelion Minelayer is named after the packaging that its munitions come in as well as the potential the weapon has for area control; putting out additional "pods", each mine actually leaves five projectiles in the user's wake."

outfit "Dandelion Pod"
	weapon
		sprite "projectile/dandelion"
			"frame rate" 10
		hit effect "small explosion"
		"inaccuracy" 45
		"lifetime" 3000
		"hit force" 20
		"shield damage" 60
		"hull damage" 60
		"missile strength" 10		

![fourminelayersfourmunitions](https://cloud.githubusercontent.com/assets/14035739/9649445/fa51fa2c-51a9-11e5-8f5b-5d5f9d2189d1.png)

**Comment by endless-sky** [comment]
Submunitions are created if the projectile reaches the end of its "lifetime" without hitting anything. So, what you really want is to give the mine a very short "lifetime" (e.g. 60 frames, for 1 second) and have it create 5 long-lasting submunitions at the end of that time.

Also, note that you can format code snippets by enclosing them in triple backticks, e.g.:

    ```
    this
        is a block
        of code
    ```

becomes:

```
this
    is a block
    of code
```
