### ISSUE TITLE
Creating new laser turrets

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#910]
Took a hint and started (again) tweaking.
I've created, bought and equipped 3 variants of laser turret, with different maximum ranges ( png of 600, 800 and 1000 length and corresponding half values for velocity). I'll further differentiate them by energy, weight, number of slots etc. Anyway, each behaves ok, alone.
A few issues:
1. I cannot mount 2 or more of the same type. Only 1 beam is shown from each type.
3. When mounting 1 small, 1 medium and 1 long range turrets, only beam small and medium are rendered. If I mount the small and long range, they are displayed correctly, same for small and medium.
![all 3 beams](https://cloud.githubusercontent.com/assets/15882273/14224915/d6ed7142-f8b6-11e5-9861-70f521dd80aa.png)
![small and big beams only](https://cloud.githubusercontent.com/assets/15882273/14224916/daa20b4a-f8b6-11e5-86e3-b9c453804008.png)
2. When steering the ship, only the small beam is rendered, the other beam disappears.
Whenever I mount the games laser turrets, things are ok.

What could be the cause?

P.S. one way to have turrets that track the target would be to paint the turret on the beam png.Of course, the turrets disappear when not firing

**Comment by LocalGod79** [comment]
this question is probably more appropriate for the google or steam forums, rather than the engine development bug reporting system.

**Comment by endless-sky** [comment]
Is it possible that your turrets just use more energy than your ship produces? That would explain why one stops firing when you are steering, and why the largest beam would not fire when you have three mounted.

**Comment by LocalGod79** [comment]
this was my first guess for that problem as well, however - there are apparently others (not being able to mount more than one copy) - if i see the outfit coding in a more appropriate forum, i'll do my best to help.

i felt like even starting to debug _@wargwargwarg plugin's_ problem would encourage more posts of the like (his problem got solved when he did this - ergo, if i want my problem solved...)

**Comment by wargwargwarg** [comment]
The problem was power related, thanks!
