### ISSUE TITLE
Documentation: Table of Ships/Weapons

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#911]
has not been updated with Wanderers, Marauders.

perhaps consolidate the pages into one 'Tables' and use the set provided;
https://groups.google.com/forum/#!category-topic/endless-sky/WreOFi8Q3gY

**Comment by toilethinges** [comment]
#877

**Comment by LocalGod79** [comment]
indeed - when i went back looking for it, the vague nature of its subject made it difficult to track

**Comment by endless-sky** [comment]
I really think the best solution is the command line option to export a fresh copy of the table. Any version that exists online will get out of date almost immediately, and the command line export has the advantage that it will also include any plugins you have installed.

**Comment by LocalGod79** [comment]
with that said, perhaps just provide instructions for dumping the table on a unified "Tables" wiki page, rather than making more work for yourself every time ships or outfits get added/adjusted - at least until that content stabilizes?
