### ISSUE TITLE
Escape pods

### ISSUE THREAD

**Issue by 3agleEmpire** [endless-sky/endless-sky#9113]
### Problem Description

Not sure how easy this would be, or if its even possible, but is there a way we could add some kind of escape pods? Or even like a special fighter bay type thing for such escape pod, I would be willing to try to help develop such a thing. Although I recall Todd saying something about not being able to do something while in space, dont know if that applies to this as well.

### Related Issue Links

I didnt see any, I may have missed though bc words.

### Desired Solution

Escape pods to be added. Or something like that

### Alternative Approaches

idk? if scientist cant figure it out, how can I?

**Comment by Hecter94** [comment]
related: 
https://github.com/endless-sky/endless-sky/issues/362
https://github.com/endless-sky/endless-sky/issues/1150
https://github.com/endless-sky/endless-sky/issues/5845
https://github.com/endless-sky/endless-sky/pull/5977
(these should have come up in your search)

**Comment by mOctave** [comment]
Also, may I mention the following quote from the [development roadmap](https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap):
```
Game Engine:
(...)
- [ ] Escape pods and other changes to support "hard core mode."
```

It's planned, although having it brought up here again may make it happen faster.

**Comment by 3agleEmpire** [comment]
oh sh-- im sorry, I didnt realize there was more, my bad, I completely missed them :(
