### ISSUE TITLE
Hai Leaks Response 3 mission `to offer` condition is never met

### ISSUE THREAD

**Issue by justinnhli** [endless-sky/endless-sky#9121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Hai Leaks Response 3 mission (in `data/hai/hai reveal 1 intro.txt`) has a `to offer` condition of `"has "Hai Leaks Response 2: done"` (https://github.com/endless-sky/endless-sky/blob/3860eca102a93b77df41c94658a64ea6d85bc7a1/data/hai/hai%20reveal%201%20intro.txt#L67). However, the Hai Leaks Response 2 mission was removed in 5f451436c6981305cc60b8c90344e7ee8ee6dc38 (https://github.com/endless-sky/endless-sky/commit/5f451436c6981305cc60b8c90344e7ee8ee6dc38#diff-8c4d4bf6ad242d9d3ecb9e2cb4fa01d30778c34ebffafcf8d55bcb257b46678aL547). No mission with that ID currently exists, and so players are stuck after the "prologue" missions.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

The Hai Leaks Response 3 mission should have it's offer condition changed to `has "Hai Reveal: Meet the Team: Sayari 2: done"`

### Operating System

Arch Linux

### Game Source

Steam

### Game Version

0.10.2

**Comment by Hurleveur** [comment]
I think that keeping it at the prologue is indeed intended until we clean things up a bit more

**Comment by Amazinite** [comment]
The prologue is all that is intended to be available at the moment.

**Comment by justinnhli** [comment]
Ah, I didn't realize that. Feel free to close this issue in that case!
