### ISSUE TITLE
Launching the game is very slow

### ISSUE THREAD

**Issue by principis** [endless-sky/endless-sky#9126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Launching endless sky lags my computer a lot. At 90% my cursor freezes for a minute.
It seems to be some kind of memory issue. I looked at htop while starting endless-sky and when my pc freezes, only 3.3G of 7.51G is in "use", but the memory is being filled with buffer pages. Earlyoom is also confused on what to kill, so it tries to kill steam instead of endless-sky.

I believe there is also a memory leak somewhere. My computer freezes after hours of playing. (I'll check next time if this is actually the case)

### Steps to Reproduce

Launch the game

### Expected Behavior

Load really quickly.

### Operating System

Fedora 38 kernel 6.4.6 on Wayland

### Game Source

Steam

### Game Version

v0.10.2

### Additional Information

PC Specs:
CPU: i5-8250u
ram: 8GB

This issue does not occur on the Fedora build of 0.9.16.1 or 0.10.2

**Comment by quyykk** [comment]
Are you using the high dpi plugin?

**Comment by lumbar527** [comment]
There are some very large plugins that are very big, not just hight dpi, such as Ember369's Star Wars plugin (forgot the name) and 1010todd's Galactic War. They will slow the loading when it gets near the end.

(thanks to quyykk for making me think of this)

**Comment by principis** [comment]
> Are you using the high dpi plugin?

Ah yes, thank you! I installed it for my desktop... I'll test the Fedora Version with the plugin.

**Comment by principis** [comment]
This was indeed the issue! Thank you and sorry for wasting your time! :slightly_smiling_face:

**Comment by Zireael07** [comment]
If the issue is the high dpi plugin, shouldn't it come with some pre-warning when launching the game with it?

**Comment by principis** [comment]
I guess that would be difficult to implement. I wouldn't have installed it, because I know my laptop can't handle it, but steam installed it automatically (I think) due it being a DLC.

**Comment by Zireael07** [comment]
Can steam be prevented from doing so? (I imagine lots of people's rigs can't handle it)

**Comment by quyykk** [comment]
I'm pretty sure Steam doesn't install DLCs by itself. However, we should definitely better handle the game running out of memory yeah.
