### ISSUE TITLE
ship won't brake out of auto pilot

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#913]
I got this flying towards Ultima thule worm hole. 
The ship worked as normal but would revert to auto pilot as soon as i stop telling it what to do.

**Comment by jafdy** [comment]
It appears to have something to do with preset routs through wormholes as i could take back control by removing the rout from the map.

**Comment by endless-sky** [comment]
Good catch. Fixed in 620fd8d.

**Comment by Alkallid** [comment]
Slightly related, should afterburners also stop auto-pilot?

**Comment by endless-sky** [comment]
Yes, I suppose it should Fixed in 839973e.

**Comment by jafdy** [comment]
Sounds good. Closing.
