### ISSUE TITLE
Wrong Link In Wiki (BlendingModes)

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky#9130]
### Location

[Wiki](https://github.com/endless-sky/endless-sky/wiki/BlendingModes#input-files)

### Describe the issue

On the BlendingModes wiki page, there is a link to the [blend.cpp](https://github.com/endless-sky/endless-sky-tools/blob/master/source/blend.cpp) file in the `endless-sky-tools` repo. However, the path in the link has not been updated since the `source/` directory was added to the `endless-sky-tools` repo. So the link gives the `404: File Not Found` error.

### Expected content

I expected the path in the link to be updated when the path to the file is.

**Comment by Anarchist2** [comment]
Should be fixed.
