### ISSUE TITLE
Segmentation Fault when demanding tribute to a planet with a non-fully-defined tribute fleet

### ISSUE THREAD

**Issue by Pshy0** [endless-sky/endless-sky#9135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The game crashes when demanding tribute to a planet with a defense fleet that only defines variants.

While such a fleet definition would be invalid anyway, this still should not cause the game to crash, so this may indicate other problems.

### Steps to Reproduce

1. Install this data:
```
mission "Free Combat Rank 14"
	landing
	invisible
	on offer
		"combat rating" = 1202604 + 1

fleet "Segfault Test Fleet"
	variant
		"Freighter"

planet "New Boston"
	tribute 1000000
		fleet "Segfault Test Fleet"
```
2. Start a new game
3. Demand tribute to New Boston

At this point you should get a segmentation fault or memory access violations

### Expected Behavior

The game should not crash with a segmentation fault.
Either a non-fully-defined fleet should have default fields or cause a crash with a proper message.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/44928041/9513afb4-2986-4667-a111-8a7723176d95)

### Link to save file

Can be reproduced on a new save.

### Operating System

Ubuntu 23.04

### Game Source

GitHub Releases

### Game Version

8d3c807 (latest build)

**Comment by lumbar527** [comment]
You might need to define the government, cargo, and names for the fleet. That could be the problem.

**Comment by Hecter94** [comment]
> You might need to define the government, cargo, and names for the fleet. That could be the problem.

This issue is that the game shouldn't crash even when the fleet isn't fully defined. 
I agree. Throw an error, sure, but not crash.

**Comment by Pshy0** [comment]
> You might need to define the government, cargo, and names for the fleet. That could be the problem.

I know that, the fleet definition is incorrect on purpose to show the issue. The thing is that this still should not cause a crash.

**Comment by lumbar527** [comment]
Sorry, didn't realize that.

**Comment by Hurleveur** [comment]
I already reported this bug as well, can confirm
