### ISSUE TITLE
Bulk Freighters intermittently get stuck

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#9136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a group of bulk freighters will intermittently get stuck somewhere along the way. It only resets with landing and take off. I've tried holding and un-holding and using move actions. The ship has fuel and the other freighters make it along the same path. All freighters have an identical build.

### Steps to Reproduce

Buy a block of bulk freighter and trade. 

### Expected Behavior

All ships should respond to move actions unless blocked.

### Screenshots

![Screenshot_20230806_180243](https://github.com/endless-sky/endless-sky/assets/70952724/4e6fb29e-bf4b-4188-bc26-f6edcad09931)

See the Olympus Clubs in this listing
![Screenshot_20230806_183611](https://github.com/endless-sky/endless-sky/assets/70952724/7f0a4fe6-c768-4122-b1d8-42603cb818d4)
It's the Heavy King in this listing. A different ship. Same issue.

### Link to save file

[T-Bone Hunt.txt](https://github.com/endless-sky/endless-sky/files/12270067/T-Bone.Hunt.txt)

### Operating System

6.2.8-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Mar 22 21:14:50 UTC 2023 x86_64 GNU/Linux

### Game Source

Built from source

### Game Version

Endless Sky ver. 0.10.3-alpha

### Additional Information

I've been having this problem for some time. I've not tested it to see if it happens with other heavy freighters.

**Comment by flowers9** [comment]
I can confirm this.  I parked 30 Bulk Freighters (stock build plus keystone) on Bore Fah, went to Arculus, unparked them, and waited on fast-forward.

1. Entire fleet made it to Tani Australis at which point I was destroyed by a Korath.  Whoops.
2. One got stuck in Bore Fah, one got stuck in Betelgeuse after refueling (but that one eventually got unstuck).
3. One got stuck in Algieba.
4. They all made it.
5. One got stuck in Betelgeuse after refueling, one got stuck in Canopus.

I generally only wait about a minute for them to unstick.

**Comment by flowers9** [comment]
I think this may caused by fast-forward.  I had 4 perfect runs without fast-forward on (technically, I turned ff on after they left Tani, but still).

@williaji, did you use fast-forward?  Did you travel with your ships?

**Comment by flowers9** [comment]
As these use scram drives, I tried disabling the direction requirement for jumping (in Ship::IsReadyToJump), but they still got stuck.  If I swap out for hyperdrives, no sticky so far.  Also, giving them 5 fuel pods.  (But both those could use more testing.)

I took a look at where the ships that got stuck ended up, and it turns out they seem to cover a fair distance in-system by the time the rest of the fleet reaches the destination (from two separate runs):

>position -6436.789 4654.2269
position -16058.182 -4209.6931
position 6534.8122 -5585.5086

>position -26477.659 11374.791
position -10152.076 -2999.6693

So they don't seem to be coming to a stop.

**Comment by williaji** [comment]
> @williaji, did you use fast-forward? Did you travel with your ships?

I was not playing on fast forward.

**Comment by williaji** [comment]
I find that using <shift>J can hang the fleet jump with the Bulk Freighters never aligning for the jump. They show yellow in the display.

**Comment by 1010todd** [comment]
I also found this bug while using some plugin (very) heavy freighters, though usually it sort of solves itself when I press J again to jump without waiting, the ships that got stuck will jump right after.

**Comment by williaji** [comment]
While not a resolution for the bug, I've changed the engines to use  Impala Plasma Steering and Greyhound Plasma Thruster and I've not had any ships hang.

**Comment by pepoluan** [comment]
> While not a resolution for the bug, I've changed the engines to use Impala Plasma Steering and Greyhound Plasma Thruster and I've not had any ships hang.

What were the original engines?

**Comment by quyykk** [comment]
#9147
