### ISSUE TITLE
Suggestion: give all ships a tiny amount of ramscoop ability

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#914]
With the new Korath territory, there are large regions of space with no friendly ships around. And, there are lots of uninhabited planets you can land on. Because the game saves when you land on a planet, it's suddenly super easy to get your player into a state where you have no fuel and no way to acquire any (except hoping a special "person" ship shows up).

That could be fixed by not saving the game on uninhabited planets, but that would cause other problems because players expect the game to be auto-saved on every planet. So, I'm proposing giving all ships a tiny bit of ramscoop ability so that if you wait several minutes, you can accumulate enough fuel to jump to another system. Thoughts?

**Comment by endless-sky** [comment]
I suppose the other option is to just create occasional Quarg fleets in any uninhabited system where there are planets you can land on.

**Comment by Disiuze** [comment]
So something like all ships having 0.1 ramscoop? The Quarg fleet sounds like a good plan but knowing how many mods some people have it could end bad seeing as the Quarg also don't offer a bribe option.

**Comment by tiennou** [comment]
I can remember that dreaded feeling while drifting aimlessly in EVN ;-). I'd say that departing on a trip through uninhabited space *and* not having a ramscoop is not a good idea, so it should not have a nice, sweet, "I'll just wait for n minutes and I'll be good".

I think then at the time you could depend on Captain Hector for that, and I have a fuzzy memory of being refuelled (!) by EVN's Krypt alien.

**Comment by endless-sky** [comment]
The trouble is that it can literally put a saved game into a state where your only escape is to edit the game file. I suppose technically the same is true of various actions which cause you to fail the main story line, though.

**Comment by ItsNickBarry** [comment]
Failing a story quest is part of the story.  Getting stuck is the end of the story.  This is a good idea.

**Comment by endless-sky** [comment]
Well, I've added it in, as an experiment (a50ec31). I made the built-in ramscoop fall off as you go away from the star at a much higher pace than the ramscoop outfits, meaning that if you don't want charging to take an hour you need to stay near the system center where you're vulnerable to attack. This will let an unprepared player limp back to civilization, but it won't be fast or easy for them.

**Comment by Wrzlprnft** [comment]
you could also add a help hotline, once you are stranded in a uninhabited system, the government which you sided with, will send you a ship to patch you up, which will arrive after, like 5 minutes.

**Comment by DingusShingleton** [comment]
I was thinking a distress beacon which once activated has a certain chance to attract pirates or other hostiles (e.g. korath). Difficulty could be variable but based on your combat strength.

This makes it faction neutral, as any friendly can pick up the beacon and intercede, be they quarg or a merchant or whoever. 

Of course, that's much more complicated than adding a ramscoop. So I support it either way.

**Comment by LocalGod79** [comment]
i think that adding ramscoops to hulls devalues the outfit(s) dramatically - previously, i would _always_ sacrifice at least the 10 tons (usually the 16) to make sure my fleet doesn't get stuck.  with this change, i would probably add further combat optimization instead.

bottom line - it's foolish to go jumping into the unknown while unprepared - i would argue that if a player starts wandering unexplored space without a ramscoop and gets stuck, they probably deserve it - how many earthbound explorers have perished through history because they were underprepared?  i don't see this as very different.

that said, i understand why you wouldn't want to strand a player. (even though the player would probably be happy for the opportunity to start a new game, and not make the same mistake again ;)

out of curiosity, what proportion of 'scoopage' do the hulls have relative to the outfit(s)?

**Comment by jafdy** [comment]
A dramatically different idea here but would it be possible to create a different auto save when landing on an uninhabited planet whilst keeping the save from the last inhabited planet you where on as well.

**Comment by LocalGod79** [comment]
i believe that incremental saves has been proposed

**Comment by endless-sky** [comment]
@LocalGod79, at present I've set it so that if you're hovering right near the star, you get about 1/10th the fuel generation of a regular ramscoop - i.e. it will take 4.6 minutes to regenerate 100 fuel, compared to 25 seconds with a regular ramscoop. But, the built-in ramscoop also drops off much more quickly as you fly farther from the star: at 1000 pixels away, it will take 18.5 minutes to recharge 100 fuel, vs. 53 seconds for the ramscoop outfit. And if you're using a jump drive, of course, those times double.

In general, it's such a slow effect that no one would want to use it as anything but a last resort.

**Comment by LocalGod79** [comment]
last question on this (i think): does the a.i. try to stay closer to the star when out of fuel?

**Comment by endless-sky** [comment]
No, this is really just a change to help the player. The AI does already stay (relatively) near the system center unless engaged in combat, though.

**Comment by ItsNickBarry** [comment]
@endless-sky I tested this right on top of a star, and it took about 1.5 minutes.  That's a long time to spend just sitting there, but I don't think it's enough to make the situation as uncomfortable as it should be.

Perhaps additional consequences for running out of fuel could be added.

Also, it might be useful to hint at this mechanic in-game somewhere, such as during the introductory missions with James.

**Comment by DingusShingleton** [comment]
I have a question but it is slightly off topic: How hard would it be to adapt the "distance from star" property to another outfit, like solar panels?

**Comment by ItsNickBarry** [comment]
@DingusShingleton #922 

If the effectiveness of the built-in ramscoop is as low as I think it should be (I would reduce it slightly from the current rate), the fuel recovery might not be evident to a stuck player until he or she has given up.  I didn't even know that ramscoops worked better when closer to stars until I read this.

**Comment by LocalGod79** [comment]
@ItsNickBarry ramscoops did not perform better when closer to the system centre until very recently.  if you haven't compiled from source since, you will not have experienced this effect.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
