### ISSUE TITLE
Loading save on clearance planet prevents departure

### ISSUE THREAD

**Issue by danaris** [endless-sky/endless-sky#9144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the middle of the "Scan Sestor Planets" mission, I had to stop and save. I landed on Sestor Ikfar, saved and quit, and when I later returned and loaded my game, the "Depart" button was missing, and I could not leave.

Further investigation revealed that the Emerald Sword, which I had been using as my flagship at the time, appeared as one of my escorts in the bottom-left corner, and no ship appeared as my flagship in the top right, nor did any of the stat gauges (fuel/energy/shield) have anything on them. Clearly, the game had decided that I did not have a flagship—and even going into the Ship Info panel and dragging ships around did not fix this. (It is possible that this is because the only other unparked ships were fighters; I didn't investigate that angle any further.)

### Steps to Reproduce

1. Have active any mission that gives clearance to a planet that you otherwise have a negative reputation with
2. Land on that planet
3. Save and quit
4. Load the saved game and observe that you cannot depart.

### Expected Behavior

When loading the game with a valid flagship, you should always be able to fly it.

### Screenshots

<img width="1547" alt="Screenshot 2023-08-08 at 10 58 10 AM" src="https://github.com/endless-sky/endless-sky/assets/1781491/bedda44b-79c4-4ff8-b44e-45ba3dbc3494">

### Link to save file

[Hannah Derinden.txt](https://github.com/endless-sky/endless-sky/files/12292930/Hannah.Derinden.txt)

### Operating System

macOS 13.5 Ventura

### Game Source

Built from source

### Game Version

commit SHA 8d3c807094f117069e6881f52d9979d4cfe8cf33

### Additional Information

I have a fix prepared, and will PR it shortly.

**Comment by danaris** [comment]
Heh, that's WIP plugin content. Forgot that was in there!

**Comment by Pshy0** [comment]
I tried reproducing it using the following data, but it did not happen:
1. Install this data:
```
mission "Clearance Bug"
	landing
	on offer
		event "New Boston Requires Clearance"
	destination "New Boston"
	clearance `You are allowed to land`
	to complete
		never

event "New Boston Requires Clearance"
	planet "New Boston"
		"required reputation" 1000000
```
2. Take off, ask for clearance, and land back
3. Close and reopen the game
4. Load the save

**Comment by Pshy0** [comment]
Creating a new pilot with this data triggers the bug:
```
government Republic
	"player reputation" -10

mission "Clearance Bug"
	landing
	on offer
		event "New Boston Requires Clearance"
	destination "New Boston"
	clearance `You are allowed to land`
	to complete
		never

event "New Boston Requires Clearance"
	planet "New Boston"
		"required reputation" 1000000
```

**Comment by warp-core** [comment]
https://github.com/endless-sky/endless-sky/commit/3155c1bc7d30ee00fb848ed34b23500e0e240cd6
