### ISSUE TITLE
Crash Bug when loading a mission ship under certain conditions

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#915]
[test_mission.txt](https://github.com/endless-sky/endless-sky/files/201166/test_mission.txt)

This test mission used to work with master branch code from a few weeks ago - it created up to 2 little watcher drones that would follow you around.  

But it looks like something in recent code changes has caused the drone generated by this mission to generate a seg fault in the following callstack:

![callstack](https://cloud.githubusercontent.com/assets/1497842/14230738/3ac1eb64-f932-11e5-95dd-64007416b9ab.jpg)

I wasn't immediately able to see why but I did test to confirm that it is definitely a new bug in master branch code by starting at my old issue_798 branch, confirming that it worked, then doing a "pull endless-sky master", rebuilding, and confirming that the crash reproduced.  If I do figure it out I'll make a pull - otherwise I'll just leave this here.
I'm not sure whether other mission ships may be effected.

**Comment by sfiera** [comment]
Per `git bisect`, the first bad commit is f48ec26. Haven't done any further investigation; I just figure I should put out a PSA for `git bisect` whenever I can.

**Comment by endless-sky** [comment]
Give it a test, but this should be fixed by commit 8688846.

**Comment by jmhorjus** [comment]
Yes that fixes the crash.  The follower drone refuses to follow me anymore though - unless I change it's ship category to something other than fighter or drone.  

That's fine though - I guess the "Fighter" and "Drone" categories just can't be used for ships with their own hyperdrive anymore, which kinda makes sense since lack of an independent hyperdrive is a defining feature of those categories.    
A fighter with a hyperdrive logically becomes an interceptor and a drone with a hyperdrive becomes...something else I guess.  Maybe a new category?
