### ISSUE TITLE
`fw escorts abandon timer` blocks `FW Commitment` without warning

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#9156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After declining missions in two of the three intro chains to FW, including leaving Longjump after `FW Escort 1B`, the player can go through the whole Katya chain, and then be left without access to `FW Commitment` and any way to get that access, and without any notice that they've been locked out of the Free Worlds mission chain.

While this isn't exactly a bug, the intro chains don't appear at first glance to be vital, and so it can easily lead to a softlock situation, especially with the timer on `FW Escort 1B` that requires you to accept the mission immediately or else never be offered it again.

This issue was originally raised by Eevi on Discord, and the full discussion is available starting here (and going on for about two hours):
https://discord.com/channels/251118043411775489/308902312741568512/1139387488364929064

### Steps to Reproduce

1. Complete one of FW Recon or FW Bounty, but decline a mission in the other.
2. Accept the first FW Escort missions, completing up to `FW Escort 1B`.
3. Take off without accepting the next mission.
4. Complete up to `FW Katya 7C`.
5. Be eternally locked out of the Free Worlds campaign, despite helping gather evidence for their innocence, volunteering for a convoy mission, and either doing risky reconnaissance missions or blowing up pirates for them.

### Expected Behavior

Having no timer on the escort mission, or some redemption mission for if you finish the Katya chain but still have `assisted free worlds` of 2.

### Operating System

N/A

### Game Source

Other (please describe)

### Game Version

Continuous (`e978841`)

### Additional Information

Tangentially related: https://github.com/endless-sky/endless-sky/issues/2640 and https://github.com/endless-sky/endless-sky/issues/104

**Comment by Amazinite** [comment]
Noting that there's nothing special about the abandon timer event that's blocking FW commitment. The declining of too many missions, regardless of what they are, will prevent you from getting the FW campaign, and not continuing this mission counts as declining (as Tomek does say that he needs more pilots in the spaceport immediately, so leaving is effectively declining).

Say that we have something extra that happens if you're stuck at 2 out of 3 missions, though. What if you also decline that mission? Regardless of how many opportunities we give, declining missions will still block you out of other missions.

**Comment by mOctave** [comment]
True. I suppose it boils down to two problems then:
(1) We need the other campaigns to provide alternate paths; and
(2) Just about every other mission in the game is either one you can pick up whenever you have time or offered on landing. Here, Tomek says "The convoy is heading out again immediately," but there are a lot of places where such urgency is stressed but it doesn't actually matter how long you take in the game.

I would suggest removing the timer, or making it much more clear that you can't launch and expect to be given the mission later on.
