### ISSUE TITLE
Documentation: 0.9.0 wiki update

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#916]
a cursory look at commits in 2016, in addition to some code segments (where i was perusing to add "circling" ai tag), a short list of shortcomings in the wiki from a mod/content developer perspective.  i've skipped player manual related commits, as that content is due to change more drastically (and suggestions i saw seem likely to become obsolete or become more elaborate).

so without further ado;
CreatingEffects
•”live” effects

CreatingMissions
•npc personalities:
--coward
--frugal
--vindictive

CreatingOutfits
• ramscoops (star proximity)
• "disruption" (shield)
• "slowing" (mass?)

CreatingShips
• automaton
• ”final explode”

CreatingSystems/Planets (new/expansion)
as yet, there is no instruction at all for creating systems, and the code contained within maps could be quite mysterious to the less inquisitive.

Unsure of appropriate home;
• “self destruct"

**Comment by endless-sky** [comment]
`"live effect"` is explained in the page on [creating outfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits#weapon-attributes).

I've moved ship personalities to a [separate page](https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities) and added those three flags.

The exact behavior of slowing and disruption may change before the release, but I've added info on how they work right now, along with the ramscoop and self destruct info.

I've updated the ship page to include "automaton" and "final explode".
