### ISSUE TITLE
mission "deadline" appears not working well?

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#917]
So I am tweaking the mission deadlines...

```
mission "Cargo [0]"
	...
	deadline 1 4
	...
```

And this results in the mission deadline being the next day the mission is offered :scream: The value `4` appears ignored as it should be as indicated in the documentation

Looking into the code it appears there is a typo https://github.com/endless-sky/endless-sky/blob/master/source/Mission.cpp#L93 :confused:

**Comment by endless-sky** [comment]
Good catch. 002d947 should fix that.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
