### ISSUE TITLE
FEATURE: Ship AI Capture Personality

### ISSUE THREAD

**Issue by OcelotWalrus** [endless-sky/endless-sky#9179]
### Problem Description

It's not really a problem  but a game enhancement. For example, pirates fleets only board ships, but it would be better if they would capture ships if they have the `captures` personality.

### Related Issue Links

#8074 is in some way related to this.

### Desired Solution

What I would like is a new ship personality that would be called `captures` or something like that.

It will make so that ships with that personalities will try to captures enemies instead of boarding.

### Alternative Approaches

Maybe make so that the ship AI automatically tries to capture ships. But it's definitively better to add a ship personalities.

### Additional Context

It would be also a good add-on for plugin creators for various reasons.

For example, I'm currently working on a plugin that introduce a new extincted species that left behind them an powerful AI that want to destroy the Milky Way. So by adding `captures` personality to that 'AI' fleets, it would make them captures/infect enemy ships.

I've tried coding that but I had problem to make the ship AI try to capture a ship if an enemy ship is disabled and capturable. I'm sure I could code that but I would definitively need help.

**Comment by lumbar527** [comment]
#8194 does some stuff about that.

**Comment by OcelotWalrus** [comment]
> #8194 does some stuff about that.

Thanks! It will help me a lot and I should be able to make what I want now.

**Comment by TomGoodIdea** [comment]
#580
