### ISSUE TITLE
Weaponry designs

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#918]
Don't know if it's a bug or feature but it's much to technical for Steam forum.
I am trying to make an ammunition based turret cannon as secondary weapon, hard hitting and power hungry. 
Thing is, I've modified the Javelin launcher and ammo and it works as secondary weapon but only forward (after selecting the ammo) but when I try to write the lines for turret and ammo, it is firing  still only forward and together with the primary guns (not what I want)

So, please, throw a glance at those 2  weapons...

This works as secondary fixed cannon:
outfit "Ja"
	category "Ammunition"
	cost 50
	thumbnail "outfit/javelin"
	"Ja capacity" -1
	description "A JA"

outfit "Japod"
	category "Secondary Weapons"
	cost 20000
	thumbnail "outfit/javelin pod"
	"mass" 40
	"outfit space" -40
	"weapon capacity" -40
	"gun ports" -1
	"Ja capacity" 200
	weapon
		sprite "projectile/MD_3shot"
		sound "canon"
		ammo "Ja" 
		ammo "Ja" 
		ammo "Ja" 
		icon "icon/javelin"
		"hit effect" "tiny explosion"
		"inaccuracy" 0
		"velocity" 15
		"lifetime" 100
		"burst" 3
		"reload" 60
		"firing energy" 2300
		"firing heat" 300
		"shield damage" 2000
		"hull damage" 2000
		missile strength" 1
	description "The JA Pod"

This doesn't work as secondary or turret:
outfit "Mass_Driver_Ammo"
	category "Ammunition"
	cost 10
	thumbnail "outfit/javelin"
	"Mass_Driver_Ammo capacity" -1
	description "Ammumition for the Mass Driver Cannons."

outfit "Mass_Driver_turret_x3"
	category "Secondary Weapons"
	cost 16000
	thumbnail "outfit/blaster"
	"mass" 40
	"outfit space" 40
	"weapon capacity" 40
	"turret mounts" -1
	"Mass_Driver_Ammo capacity" 200
	weapon
		ammo "Mass_Driver_Ammo"
		sound "canon"
		sprite "projectile/MD_3shot"
		"hit effect" "tiny explosion"
		"inaccuracy" 0
		"velocity" 15
		"lifetime" 100
		"reload" 3
		"firing energy" 2300
		"firing heat" 300
		"shield damage" 2000
		"hull damage" 2000
	description "Mass Driver Turret, one of the terifying weapons from a far away galaxy. Fortunately, it's very far away"

I have a hunch I need to define a "Secondary Weapon - Turret" Category...but where?

Thanks

**Comment by LocalGod79** [comment]
change "gun ports" to "turret mounts"

**Comment by LocalGod79** [comment]
the steam community contains several modders that would have been able to answer this question.

also; https://groups.google.com/forum/#!forum/endless-sky

**Comment by Amazinite** [comment]
Change it from "gun ports" -1 to "turret mounts" -1. Done. And this really is something better fitted for the steam forum. We've got plenty of info over there.

**Comment by wargwargwarg** [comment]
Aaaa, that was the forum? Somehow it escaped me. I'll post there. Thanks

**Comment by LocalGod79** [comment]
also see #95
