### ISSUE TITLE
Color the pop-up text differently for "you have mission planets to land on"

### ISSUE THREAD

**Issue by pepoluan** [endless-sky/endless-sky#9191]
### Problem Description

Currently, the line telling the player that "you have a planet to land on in this system" is colored the same as other messages.

### Related Issue Links

Not sure if there's any linked issue.

### Desired Solution

Color that particular message differently. Say, light green. So it will stand out better among the chaff information.

I believe this should be doable as currently the message that I've lost a ship is already colored differently.

### Alternative Approaches

N/A

**Comment by RisingLeaf** [comment]
Which messages would that be?
