### ISSUE TITLE
Path for preferences / savegames / etc. folder should be configurable

### ISSUE THREAD

**Issue by Thilo21** [endless-sky/endless-sky#92]
Hi,

It would be great if the location of the preferences / savegames / etc. folder could be configurable. This would make the game truly portable. You could just put it in your dropbox and play at home at your desk or on your laptop when travelling.

Great project, I'm already addicted!

cheers,
Thilo

**Comment by endless-sky** [comment]
Have you tried just replacing the preferences folder with a link / alias to a dropbox folder or whatever? I know that's doable on Linux because that's something I do when testing plugins, and I assume it would work on other operating systems too.

**Comment by Thilo21** [comment]
Actually that's what I did as a workaround.

**Comment by endless-sky** [comment]
The workaround is not much harder than doing this in-game would be, so I'm not going to add this as a feature to the game itself.
