### ISSUE TITLE
Assist/boarding missions triggered on drones

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#920]
Missions sourced by assisting (the assisting mission) can be triggered when assisting drones, although they are unmanned and do not have anyone inside to pay you. Probably goes for boarding tag too. Is there any way to prevent this? Because it interferes with the storyline I'm writing for my plug-in, as well as being illogical if civilians ever get drones.

**Comment by jmhorjus** [comment]
Perhaps just make it possible for boarding/assisting missions to specify more specific "source" filters?

I'm not sure what conditions are supported now that apply to ships, other than "government".  It'd be nice to be able to have a mission be offered based on some specific attribute of the ship you are dealing with, like it's category, it's number of crew, it's value, etc.

**Comment by KiLEdEnNis** [comment]
simply adding a string that prevents it from triggering on ships with the "automaton" would fix it
good luck :)

**Comment by tehhowch** [comment]
This restriction would be possible with #3140
