### ISSUE TITLE
Reloading mission with `launch` causes mission to disappear

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#9200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the player reloads their save while a mission that expects the player to launch afterwards is loaded, the mission will disappear completely, sometimes soft-locking the save.

### Steps to Reproduce

1. Get a mission that results in you launching from the planet (like Bunrodea First Contact)
2. Exit to the menu and load the most recent save
3. See bug

### Expected Behavior

The mission should load and offer normally, just like how missions that don't launch the player do.

### Operating System

Win10

### Game Source

Built from source

### Game Version

23a7aaf0a77e264e8ec4980f0f21630d3da10510

**Comment by warp-core** [comment]
Save file?

**Comment by Anarchist2** [comment]
[test 3.txt](https://github.com/endless-sky/endless-sky/files/12385742/test.3.txt)

**Comment by warp-core** [comment]
The Bunrodea first contact mission only seems to launch you in the on complete, at which point the mission is finished anyway, so it should disappear.
Wanderers: Mind 6 is currently affected by #9144. A particularly problematic case of it where your ship has been placed on a different planet to you.
Editing the save file to put you on Korbatri Eska and loading that, the mission is offered, I am launched, and I can reload the latest file and am launched again, and the mission still appears in my mission list.

**Comment by Anarchist2** [comment]
It seems that most of this issue's scope is covered by #9144, so I'll close this.
