### ISSUE TITLE
Allow raid fleets to be defined per-system instead of per-government

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9205]
### Problem Description

Raid fleets are currently defined on a per-government basis. That is, a government defines which fleets appear as raids in that government's systems when your raid attraction is high enough. This is a very unmalleable system, though, as if you want only a few systems in a region to have raid fleets, you need to create a new government just to get the raid fleets to only appear there.

### Related Issue Links

#8784 is an example of this issue.

### Desired Solution

Allow systems to define raid fleets with a `raid <fleet name>` keyword.

### Alternative Approaches

N/A

**Comment by Hurleveur** [comment]
I'm already coding this but I'm wondering how both should interact - should the system fleet override government fleets or stack up with them?

**Comment by Amazinite** [comment]
I'd say have the system fleet override the government fleet. Although that then begs the idea of creating some method of a system explicitly stating that no raid fleets spawn there to override the government saying that it has raid fleets. (Say you have a government with 100 systems but 1 shouldn't have raids, we could just mark that 1 system as not having raids instead of having to mark 99 systems as having raids).

**Comment by Zitchas** [comment]
What about having the government be the main definition, with the system defining modifiers to it?

So you'd have Republic that is X sensitive to cargo and defines everything.

Then you'd have a system attribute, say "trade route security" that is a value greater than 0. 0 (or the attribute not being present) has the system go with the standard government defined value. Any positive value acts as a multiplier. So 0.1 would result in pirates being attracted to cargo amounts as small as shuttles, and something like 5 would result in even larger light freighters not attracting much attention even without any weapons at all. Negative values would specify that there's no raids.


That being said, expanding on this a bit, it'd be interesting if we could have multiple raids. What if somewhere is contested territory, and multiple groups would be interested in raiding ships with lots of cargo in it, but are enemies of each other?

**Comment by Hurleveur** [comment]
We can already have multiple raids for one government/system

**Comment by Zitchas** [comment]
Great! So just need a way to specify a modifer value, then.

**Comment by Hurleveur** [comment]
Then instead of no raid we should use "raid modifier" that can be equal to 0?

**Comment by Hurleveur** [comment]
That raid multiplier would make things more complicated and I'm not really sure how to code it - if we want extra safety somewhere that should probably come as an increase/decrease to attraction and no matter what no raid will still be useful
So I'll just let that part for later
