### ISSUE TITLE
Documentation: 0.9.x wiki update

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#921]
(i'll leave this one open to keep track as features get added until 0.9.0 release - don't know what i was thinking when i closed it)

from the #916 (which was nearly entirely addressed)

CreatingSystems/Planets (new/expansion)
as yet, there is no instruction at all for creating systems, and the code contained within maps could be quite mysterious to the less inquisitive/deductive.

**New:**

CreatingMissions
•depart (with launch/flee)

**Comment by LocalGod79** [comment]
CreatingOutfits
•"solar generation"

**Comment by endless-sky** [comment]
The "depart" conversation ending is covered in the page on [writing conversations](https://github.com/endless-sky/endless-sky/wiki/WritingConversations), and "solar collection" is already up on the CreatingOutfits page.

**Comment by LocalGod79** [comment]
"unplunderable" and changes to hand-to-hand

**Comment by LocalGod79** [comment]
CreatingShips
fighter bays - visible/invisible carry, launch direction, over/under placement

**Comment by LocalGod79** [comment]
(Unsure of category)
phrasing, recursive phrasing, usable conversation tags (`<ship>, <first>, <last>`?)

**Comment by LocalGod79** [comment]
CreatingOutfits
hull repair rate still states the energy requirement

**Comment by endless-sky** [comment]
Added fighter bays to the ship creation page.

The hull and shield repair documentation has been updated.

Updated the stream and cluster descriptions.

**Comment by toilethinges** [comment]
This is probably extremely obvious, but there is nothing about governments, at all, except that they are mentioned vaguely in just about every page. For example, what does the attitude toward really do?

**Comment by Alkallid** [comment]
What about tracking?

**Comment by endless-sky** [comment]
Added the tracking parameters to the wiki.

**Comment by LocalGod79** [comment]
new animated sprite parameters "frame time" and "delay" for both ships and outfits wikis.

also, as an aside `"frame rate" 0` now produces errors, where it did not before...

**Comment by LocalGod79** [comment]
"priority", "minor" in Missions wiki.
