### ISSUE TITLE
Flagship status for Kor Sesor Ships 

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#9215]
### Problem Description

This suggestion aims at trying to convince the author of the game to allow a For Sesor ship to be the flag ship of a fleet of ship after such a ship had been captured. Currently, the game wouldn't allow a for sensor ship to be a flagship as it is said to be automated by remote control., even when bunks are added manually to the ships.

### Related Issue Links

N/A

### Desired Solution

The author of this post suggest the elevated status of the For sensor and Martin ships to enable them to be controlled by the player, allowing for more challenging space travels and as beating up alien ships while not being able to capture them would be frustrating on the players part, especially after the main story ends and the player founds him or her almost invincible under the majority of circumstances.

### Alternative Approaches

N/A

### Additional Context

N/A

**Comment by ProNooberEX** [comment]
Below are the evidence for such a problem:
<img width="1440" alt="截屏2023-08-24 22 30 32" src="https://github.com/endless-sky/endless-sky/assets/110284440/79a33a2a-ce1e-435b-961d-58f0922a6ded">

**Comment by warp-core** [comment]
You can acquire "Command Center" outfits from Laki Nemparu in the Kashikt system and Setar Fort in the Sevrelect system (both at the southwest end of old Korath space, the same region where the Kor Sestor and Mereti drones are present).
Installing one of these outfits on an automated ship such as the Kor Sestor and Mereti ships will allow you to use that ship as your flagship, though you will likely need to install additional bunk rooms for any required crew from turrets or other outfits.

**Comment by ProNooberEX** [comment]
<img width="1337" alt="截屏2023-08-24 22 31 55" src="https://github.com/endless-sky/endless-sky/assets/110284440/d5d8abbc-ea08-41d6-a872-5ea1b17b3510">
<img width="1337" alt="截屏2023-08-24 22 31 38" src="https://github.com/endless-sky/endless-sky/assets/110284440/0f415d59-85ba-44d0-8834-ce6e6bfd4a63">
<img width="1337" alt="截屏2023-08-24 22 31 09" src="https://github.com/endless-sky/endless-sky/assets/110284440/1bf18f75-15ad-450e-9b70-99d8f43cb44e">
<img width="1337" alt="截屏2023-08-24 22 31 03" src="https://github.com/endless-sky/endless-sky/assets/110284440/9e1b69f3-ce93-4d8f-ad9f-9efa18f737da">
<img width="744" alt="截屏2023-08-24 22 30 37" src="https://github.com/endless-sky/endless-sky/assets/110284440/b0e474d4-030c-45dd-8c8f-9bdb5650efe1">
<img width="1440" alt="截屏2023-08-24 22 30 32" src="https://github.com/endless-sky/endless-sky/assets/110284440/44aa4745-5d09-40e3-bde7-b7dee91ec978">

**Comment by lumbar527** [comment]
> By they way how to you make friends with the quart again after beating them up? I can't proceed with the Wanderers mission as the quargs won't let me into their ring structure.

I don't think you can.
