### ISSUE TITLE
Cognizance 7 description is too sparse

### ISSUE THREAD

**Issue by flowers9** [endless-sky/endless-sky#9224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The description for Cognizance 7 is

>Plume wants to witness firsthand what is going on in Nenia.

Except you actually need to land on Nasqueron with a specialized ship.  True, the title of the job mentions Nasqueron ("Take Plume to Nasqueron"), but that could simply be going to the same system as it, rather than landing on it.

### Steps to Reproduce

Accept the mission "Remnant: Cognizance 7".
Check the mission description.

### Expected Behavior

The mission description should mention the requirements to complete it.  In this case, it should mention having to land on Nasqueron.

### Operating System

Ubuntu 22.04.3 LTS

### Game Source

Built from source

### Game Version

fd241fe

**Comment by lumbar527** [comment]
Attempted fix: #9225
