### ISSUE TITLE
Create a "balance" issue template

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9233]
### Location

Issues

### Describe the issue

I want to complain about balance but there is no "balance" template, only bug reports, feature requests, and documentation issues. Balance doesn't really fit under any of those categories exactly.

### Expected content

Create a balance issue template.

**Comment by DarcyManoel** [comment]
What would a balance issue consist of?

**Comment by Amazinite** [comment]
Honestly, it'd be largely the same things that the feature request template has, so maybe we just rename that template to "Feature Request/Balance Issue" or something like that.
