### ISSUE TITLE
Allow acceleration and turn rate to be altered independently of one another by a ship's stats

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9234]
### Problem Description

Currently, the equations for acceleration and turn rate are as follows:
* acceleration = thrust / mass
* turn rate = turn / mass

Both thrust and steering are controlled by the outfits that are installed on a ship, but the mass of a ship isn't something that the player really has much control over. You can drop your mass for the sake of having a higher acceleration and turn rate, but you're generally sacrificing a lot to do so. This also only really has a major impact on the smallest of ships, and it seems weird to me that we'd create a situation where in order to make a small ship better, you have to leave empty outfit space to keep your mass down.

What makes matters worse is that the max speed of a ship is defined as follows:
* max speed = thrust / drag

This means that thrust is tied up in both max speed and acceleration.

The primary issue is that we have two attributes, thrust and mass, which are tied up in multiple stats of a ship. This means that if we want to tweak one attribute for the purpose of changing one stat (e.g. change mass or thrust to change acceleration), we're forced to consider how that change impacts the second stat that the attribute we're changing effects (e.g. a change to mass for acceleration also changes turn rate, or a change to thrust for acceleration also changes max speed).

While it's not impossible for us to maneuver this balancing act (no pun intended), it is a difficult situation that we could solve for ourselves. Having one attribute which is tied up in multiple stats without any alternative method of tweaking one without tweaking the other is something we should avoid.

### Related Issue Links

#9167 talks about lowering the mass of the stock Lance in order to increase its acceleration a decent amount by changing its loadout.
#5271 is the general "speed sucks right now" issue.
#5779 introduced an acceleration multiplier for just this case.

### Desired Solution

Create acceleration and turn rate multipliers that can be applied to the hulls of ships. These attributes, as the name describes, would multiply a ship's acceleration or turn rate. The equations for the various handling stats of a ship would then be as follows:
* acceleration = thrust * (1 + acceleration multiplier) / mass
* max speed = thrust / drag
* turn rate = turn * (1 + turn rate multiplier) / mass

Say that these attributes existed and we wanted to increase the acceleration of a ship without affecting its max speed, we could then simply increase that ship's acceleration multiplier. If we wanted to increase the turn rate without increasing acceleration, then we'd use the turn rate multiplier. And we can already increase max speed without touching either of the other two handling stats by decreasing drag.

This also means that changing a ship's mass still has an impact on both acceleration and turn rate, meaning that tactics like decreasing your ship's mass would still be a viable way to increase your acceleration and turn rate.

### Alternative Approaches

Stick with what we have now.

My end goal is to greatly expand the accelerations of ships with ship size without creating as big a gulf in turn rate with ship size. In order to increase the acceleration of small ships any higher than we current have (without drastically changing how small ships are outfitted, which is something I want to avoid), we'd need to greatly increase the thrust of all smaller engines. We can't just make the ships any lighter, as most of their mass is already tied up in their outfits and lowering their hull masses any more starts to become absurd.

So by increasing the thrust of smaller engines, that creates a knock-on effect of needing to increase the thrust of larger engines, lest the smaller engines become more powerful than the larger ones. There is some wiggle-room to flatten the thrust/mass curve of engines further than what #8842 did, but at a certain point we'd need to raise all thrusters up, which inherently makes larger ships faster. Such a change to engine thrust is also tied up with max speed, and if we wanted to keep the max speeds where they are now, then we'd need to increase the drag of all ships proportionally to the increase in thrust that would be given to the thruster that each ship is expected to have installed. 

Similarly, in order to decrease the acceleration of larger ships, we need to increase their mass. We could decrease the thrust of their engines, but that just has the reverse issue of increase the thrust of smaller engines in that eventually we can't bring the large engines any lower without also nerfing small engines, and that also affects max speed and therefore requires drag changes. And as stated, increasing mass means decreasing turn rates, which would then require us to increase the turn rate of all larger engines.

While I don't want us to entirely fix this issue with acceleration and turn rate multipliers, meaning I do see us making mass changes and tweaks to the thrust and turn stats of existing engines and the drag stats of ships, what I mainly want to avoid is the need to create drastic changes in these stats to get what we want out of ship handling vs ship category/size. The introduction of multipliers simply gives us more knobs and dials to twist and turn in order to get everything where we want it to be.

### Additional Context

A perfect case study of the difficulties this situation of having one attribute affect multiple stats creates can be seen in Destiny 2. In that game, weapons have a "range" attribute that is tied up in multiple statistics, including when the weapon begins experiencing damage falloff. But another attribute which affects that same exact statistic was the "zoom" of a weapon. This mean that two weapons of the same type with the same range attribute but different zoom attributes could behave wildly differently from one another, as the weapon with the higher zoom had much better damage falloff stats. This meant that the game was stuck in a situation where Bungie, the developers, had to avoid releasing weapons with wildly different zoom stats from the norm. While zoom affects a lot more than just the damage dropoff of a weapon, the fact that it did affect that stat, which is such an important stat of the weapon for competitive balance, meant that zoom basically always had to have the same value for weapons of the same type. Recently, Bungie rectified this situation by making it so that zoom no longer affects a weapon's damage dropoff, instead creating a new damage dropoff scalar attribute that weapons can be given, allowing zoom to be tweaked without increasing or decreasing the weapon's effective range.

There's also a similar issue in overloading of attributes that I discussed in one of my review comments on [#9112](https://github.com/endless-sky/endless-sky/pull/9112#discussion_r1281320512). The basic idea is you simply don't want one knob that affects too many other things, as that creates a headache when you want to change one of those things but not the other. I run into this a lot at work and it's painful. 😞

**Comment by Amazinite** [comment]
Between these two proposed multipliers, I only really see us using the acceleration multiplier since turn rates can be more easily tweaked by only tweaking the power of steering, but I figured I'd propose both just for the sake of completeness.

**Comment by Zitchas** [comment]
I definitely like the idea of having a multiplier; although that being said, I also like the idea of having flat modifiers. By that I mean, being able to specify that a ship or outfit has a fixed change (positive or negative) to acceleration, max speed, or turning; individually. 

Ex. Being able to have an outfit that gives +50 max speed. Doesn't matter if it's on a ship with 1 drag or 50, or 10 mass or 5000, it still just gives exactly +50 max speed on top of whatever it might otherwise have.

This would be particularly useful for alien outfits that are aren't just different kinds of thrust or other "basic human T0 physics" type effects.

---

I would prefer an option to change max speed that doesn't touch drag, because that's such a variable number across our ship spectrum. Having an outfit that reduces drag by 1 will have a minimal effect on some of our larger ships; while breaking the game by pushing the total drag value into the negative for some of the fastest ships. Especially on any outfit that is obtainable outside of specific mission gifts, something that actually reduces drag is far too abuseable to be usable in vanilla.

**Comment by Quantumshark** [comment]
I believe the concept here is that these attributes would be used primarily - if not exclusively - on ships, not outfits. At the level of the ship, drag can be customised in whatever manner is desirable. The primary use case I can see for these multipliers is a more streamlined and elegant implication of #8957 or something similar to it - rather than trying to work with different scaling on the steering outfits, and then running into major problems with edge-cases like the coalition, you could just give heavier ships higher masses and matching `turn multiplier` (or slightly less than matching, to make a sensible reduction to turning), and then you'd get the wider range of acceleration stats without breaking anything.

Outfits that interact with drag do so using `drag reduction` rather than flat adjustments for `drag` for precisely the reason you stated - the multiplicative effect of `drag reduction` is consistent in utility across different ships, whereas subtracting `drag` is not. 
The same is true of multiplicative vs additive changes to mobility - using your +50 max speed outfit as an example, two of that outfit would more than double the top speed of a Container Transport, but would be a difference of less than 10% to a Finch. A multiplier is consistent in its _relative_ effect, and therefore in its utility, across different ship types.

More problematically, an outfit that gave a flat addition to handling stats would be disproportionately useful for larger ships. Currently, a larger ship needs to use larger engines, and therefore more outfit space, to gain the same increases in mobility that a smaller ship gains. With outfits that made flat changes to handling stats, a larger ship would be able to fit more such outfits, and would thus always be much more mobile than a smaller ship. So such flat handling modifiers are definitely not 'easier to balance and harder to abuse' - rather, they completely break the game.

**Comment by Zitchas** [comment]
You provide some good detail regarding drag reduction; however I disagree with your assessment of flat additions both mechanically and in terms of lore. Forcibly restricting all of our changes to max speed, acceleration, and turning to be done in the context of tweaking thrust, mass, and the completely meaningless and invisible "drag" attribute is effectively mandating that everything in the game must, without exception, abide by a weirdly limited version of classic physics as known in 2023, and that future/alien exceptions to this are flat out impossible. There is, of course, the rather clunky `"inertia reduction"` that is an "all or nothing" attribute and incapable of being fine tuned to only affect a single aspect of manoeuvrability.

But yes, that is *exactly* the point: Sometimes, we don't want relative variation. Relative and multiplicative variation is great for anything that is touching on classic physics. Tweaking thrust, mass, and the mysterious drag. But we're dealing with a sci-fi environment and factions that have far eclipsed humanity of the 2023's understanding of physics. We should at least have the capability of things that don't play by those rules. 

Likewise, for story purposes, sometimes we may not want to give the player access to something that gives an extremely tightly controlled change. Not something that changes thrust, or mass, or drag; or makes one or more of these more effective. But something that enacts an absolute change. I likewise accept that such flat modifications to purchasable outfits should likely be rare, perhaps even none at all. But it doesn't change the potential utility for some actually unique outfits and effects that would be very useful from a storytelling perspective.

For a quick off the top of my head example, having a warp field that changes how a ship interacts with normal space. It isn't increasing the effectiveness of anything, it's merely warping reality such that everything within it can go 50 faster. No change to acceleration or turning, just that the ship can reach a higher max speed before whatever imaginary effect that provides our max speed kicks in. Doesn't matter what it is, it has the same effect. 

As an addendum to this, I would also find it very useful to have an override ability. Something that doesn't add or subtract from a ship's manoeuvrability statistic, but rather overrides it entirely, setting it exactly to a specific value. I don't see such an override ever being used as a purchasable or acquirable outfit; but very useful for story-provided things. Thinking particularly of "outfits" that aren't actually outfits, but rather just labels identifying external effects that are semi-permanently attached specifically to the ship. Thinking about things like, for example, ships operating inside the Ring in the Expanse. For most ships, operating in that area is an extreme limit on their max speed. That effect doesn't care about a ship's mass or thrust or anything, it's an absolute. Yes, some ships will find it *much* more limiting than other ships. Of course, I'm not interested in recreating the Expanse, but being able to implement specific effects in the course of the story that have similar impacts in both general and specific situations.

**Comment by Quantumshark** [comment]
That's a fair point; I was looking at the idea from a balance perspective, not a lore one.
It would be necessary to be very cautious about the balance implications of any such outfit, but it wouldn't be the first attribute we've added support for that needs to be handled cautiously to avoid unbalancing things.

**Comment by Amazinite** [comment]
A semi-related idea: what if turret turn rates could be effected by the ship the turrets were installed on? So say a heavy warship has a 25% turret turn rate debuff, or fighters (for the few that have them) could have a 50% turret turn rate buff.

**Comment by lumbar527** [comment]
> A semi-related idea: what if turret turn rates could be effected by the ship the turrets were installed on? So say a heavy warship has a 25% turret turn rate debuff, or fighters (for the few that have them) could have a 50% turret turn rate buff.

Sounds interesting!

**Comment by Zitchas** [comment]
Sure, that sounds like an interesting idea.

On a related aspect, having turret arcs would also provide as sort of "debuff" to larger ships: A small ship having a single turret that is unbounded vs a large ship that might have large numbers of turrets, but many of which have restricted arcs would make for an interesting difference between the two.

**Comment by Ferociousfeind** [comment]
> More problematically, an outfit that gave a flat addition to handling stats would be disproportionately useful for larger ships. Currently, a larger ship needs to use larger engines, and therefore more outfit space, to gain the same increases in mobility that a smaller ship gains. With outfits that made flat changes to handling stats, a larger ship would be able to fit more such outfits, and would thus always be much more mobile than a smaller ship. So such flat handling modifiers are definitely not 'easier to balance and harder to abuse' - rather, they completely break the game.

It should be noted that an "additive to max speed" attribute would have disproportionately large effects on ships with low speed, not necessarily ships with high mass. While it does affect big ships more, it affects any ship with lackluster speed stats. And, as speed increases, the disproportionate effects of the stat taper off quite quickly. For example of why they aren't that broken, ask yourself "what does it take to double my speed with this outfit?" (assuming you're only using these outfits)

It takes, of course, double the outfits! So, I think you can conceptualize these as mass-ambivalent engines which do not interact with thrusters until the step where their effect is added to the regular thruster effect.

Now, having mass-ambivalent engines sounds like a recipe for disaster, but they don't have as much of an impact (especially not a positive one) when used for max speed, as opposed to thrust which would be very useful/game-breaking. That'd just make big ships a lot slidier than they usually are, capable of reaching higher top speeds if you're willing to invest the crazy amount of time into getting them up to those speeds.

**Comment by Quantumshark** [comment]
> What about a `moment of inertia` type attribute that is multiplied with `mass` for use in turning calculations?

That's just 1/`turn multiplier`.
