### ISSUE TITLE
Plugins with a custom name in `plugin.txt` are always displayed as enabled.

### ISSUE THREAD

**Issue by Pshy0** [endless-sky/endless-sky#9237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Plugins with a custom name in `plugin.txt` are always displayed as enabled. **They can be disabled**, but they are **displayed as enabled**.

Additionally, the content of `plugins.txt` (not the file in the plugin, the file listing enabled plugins) does not look right, because it have an entry for both the plugin folder and the plugin name.

### Steps to Reproduce

1. Install a plugin in a folder:
  - The plugin must define a custom name in `plugin.txt`
  - The folder name of the plugin must be different
  - [This is the plugin I tested with](https://github.com/Pshy0/es-empty-plugin), put it in a `es-empty-plugin` folder.
2. Launch the game and try enabling / disabling the plugin: it stays checked.

### Expected Behavior

Disabled plugins should not be displayed as enabled.

### Screenshots

- Initial state:
![image](https://github.com/endless-sky/endless-sky/assets/44928041/3ca8214f-bfa3-49a4-8683-a95d3005b81c)
- Clicking the checkbox (game knows it needs to reload but the checkbox didnt update appropriately):
![image](https://github.com/endless-sky/endless-sky/assets/44928041/fa60cae5-5c09-4ee5-8d6e-b7f838f1ed31)
- Current plugins state:
![image](https://github.com/endless-sky/endless-sky/assets/44928041/ddc33372-2cbc-4d9f-a7e4-0e594a157863)
- After closing the game:
![image](https://github.com/endless-sky/endless-sky/assets/44928041/97015e77-8a48-4a71-a975-81bb06ac37fa)

Note that `Ruin The Sky` is also supposed to be disabled here, but is displayed as enabled.

### Operating System

Ubuntu 23.04

### Game Source

GitHub Releases

### Game Version

7c815e1a7ab84a847df227d907d046afa562e20b (continuous)

**Comment by Amazinite** [comment]
Could you also check the behavior of the new `"installed plugin: <plugin name>"` auto-condition when dealing with plugins that have their name in a plugins.txt file? I looked at that condition yesterday and realized there might be an issue with it and the plugins.txt file, but haven't tested it yet. If there is an issue, I imagine that the problem is in the disconnect between the display name of the plugin and its folder name.

**Comment by Pshy0** [comment]
Tested with this data:
```
mission "Plugin Test"
	landing
	repeat
	on offer
		conversation
			`tests:`
			`	has "installed plugin: Empty Plugin"`
				to display
					has "installed plugin: Empty Plugin"
			`	has "installed plugin: es-empty-plugin"`
				to display
					has "installed plugin: es-empty-plugin"
```
When the plugin is disabled:
![image](https://github.com/endless-sky/endless-sky/assets/44928041/1509662c-a6e9-4ee8-a240-4fc72b702f10)

When the plugin is enabled:
![image](https://github.com/endless-sky/endless-sky/assets/44928041/87260db3-0125-45f9-bd42-22a24ffe0ee9)
