### ISSUE TITLE
Plume's missions bugged ? v0.10.2

### ISSUE THREAD

**Issue by Kuzu404** [endless-sky/endless-sky#9245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This concerns the Remnant's missions involving the Void Sprites.

Here is my experience:
I encountered **2** hostile Archons in Nenia at the beginning of the missions that consist in studying the Void Sprites.
They **remained hostile** all through the sequence of missions.
I have now reached the point where a Korath raider must be taken down to protect the Void Sprites and I am stuck here.
Since Archons aren't hostile with the Korath but are still hostile with me and my fleet we are being torn to shreds with no chance of survival.

2 reasons why I suspect a bug :
- The narrative of the missions suggests strongly that the initial threat of the Archon is no longer a problem after the first few missions to prove our peaceful intentions to the Archons.
- I do not see how it is possible to take out a Korath warship while dodging fire from 2 Archons. Game cannot be meant like that, it's just plain slaugther.

### Steps to Reproduce

1. Go to 'Remnant space' and do the missions involving Void Sprites.
2. 2 Archons show up in Nenia.
3. They stay there and will attack player every time they enter the system.

### Expected Behavior

According to the storyline, 1 Archon is to be expected, not 2. 1 was already hard enough to dodge.
According to the storyline, those Archons are smart and they should understand that we are not harmful to the Void Sprites, especially when we bring back eggs... That they stay in Nenia is okay, but they should stop being hostile with the player.
As others mentioned in other posts, the behavior of the Archons towards Korath is ambiguous. One would expect some retaliation from present Archons on to raiding Koraths. It make no sense that the player is their only target.

### Link to save file

[Shigeshige Tokugawa.txt](https://github.com/endless-sky/endless-sky/files/12474288/Shigeshige.Tokugawa.txt)

### Operating System

Windows 10 Family, version 22H2

### Game Source

Steam

### Game Version

v0.10.2

### Additional Information

None

**Comment by Zitchas** [comment]
Hmmm, this does sound problematic.

For starters, the Archon should start out not hostile, and shouldn't become hostile until you get the gascraft and go to land on one of the planets. It'll be hostile for a bit, and then it becomes non-hostile again for further missions.

The fact that you are seeing two hostile archons suggests that you may have somehow angered them before reaching this mission. Have you attacked any archons or void sprites previously?

**Comment by EjoThims** [comment]
Reputation from the save lists `Drak -11.5` and `"Ember Waste" -12.5` in addition to `"Drak (Hostile)" -1013.5` but `"Indigenous Lifeform" 1`.

So my guess is attacking Drak directly? Especially if the one the missions spawn is `"Drak (Hostile)"` when it's meant to be hostile and then just `Drak` when meant not to be instead of resetting the `"Drak (Hostile)"` rep.

**Comment by Kuzu404** [comment]
Thank you.

As far as I remember they were not hostile the first time I explored Nenia. I could scan a void sprite without issue. It only when I had to land on gaz giant that they showed up and attacked me. In a previous playthrough (older version of the game) I remember dodging 1 Archon that eventually stopped attacking me as the missions went on.

This time I was greeted by 2 of them and they won't cut me any slacks.

About angering them. I really don't know what I could have done.
This is what comes to my mind:
- I asked all the questions I could when I visited a system with nano-swarms. The Archon seemed a bit unamused but I don't think it sent its buddies to sick me just because I was curious.
- I attacked one once in one of the isolated nova system near galactic core. It destroyed me swiflty and I had to load my save.
- Every other Archon I meet is just ignoring me.
- I never attacked any Void Sprites (only scanned once).
- I may have killed other space born life forms in galactic North East but I had already advanced to the stage where the Nenia's Archons should have stopped attacking me.
- I defended my self against hostile Ka'het in Graveyard. 

What else could I have done to get a bad reputation with them?
Can I make peace? I wanna be friends.

**Comment by warp-core** [comment]
I believe this is the result of disabling and/or destroying ships (or, rather, creatures) with the "Indigenous Lifeform" government.
While that government itself does not impose any penalties, the "Drak", "Drak (Hostile)", and "Ember Waste" governments all have an attitude towards it of 1 and do have their own penalties, which they use for actions against the other government they have a strong attitude towards.

This government is used by:
- The Void Sprites in the first two "Remnant: Void Sprites" missions (prior to the first encounter with the hostile Archon, which is in the third mission.)
- The Void Sprites in the mission "Deep: Remnant 3: Secret" (though your save file indicates this mission has not been offered and so is not relevant to your case.)
- The fleets "Subsidurial", "Void Sprites", "Embershades", and "Embersylphs".
  - The fleet "Subsidurial" doesn't appear to ever be used.
  - The fleet "Void Sprites" appears in Nenia (except for special missions where you need to scan Void Sprites there where the fleet is removed so the only Void Sprites present are the mission targets.)
  - The fleet "Embershades" appears in: Caeculus, Peragenor, Segesta, and Stercutus.
  - The fleet "Embersylphs" has not appeared in your game so far.
- And, the person "Subsidurial".

Additionally, while it is no longer used for these fleets in continuous, it was used in the following places in 0.10.2, I expect it is  your actions against these creatures that have caused you this issue:
- "IIje (Uninterested)", "IIje (Swarming)", and "Iije (Surveillance)".
- "Vyrmeid (Plankton)", "Vyrmeid (Boomerang)", and "Vyrmeid (Cephalapod)".
I'm not going to list the systems these appear in, but they are in the north east.

**Comment by Kuzu404** [comment]
Yes, it worked! Problem solved, I can move on with my mission.

Nenia has suddenly become a much friendlier system!

Thank you very much!!

**Comment by Sceppie** [comment]
Ran into the same problem. Yes, I've killed some indigenous lifeforms in the past, but I didn't think their momma was gonna be upset, because they were on the complete right side of the map.

Solved it for me


> Changing the values for "Drak" and "Ember Waste", in the "reputation with" section to be positive should fix it for you.

**Comment by ziproot** [comment]
This has been solved as of 0.10.4: you cannot lose reputation with the Drak for attacking "indigenous lifeform" species outside the ember waste.
