### ISSUE TITLE
"Creating Ships" wiki has two "automaton"

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#925]
https://github.com/endless-sky/endless-sky/wiki/CreatingShips This page has two paragraphs mentioning the attribute `automaton` with different contents

**Comment by luiges90** [comment]
While we are on it, https://github.com/endless-sky/endless-sky/wiki/CreatingIssues this page has a typo

> balance: A ship or weapon that seems too powerful or useless, or a mission that seems **to** easy or hard.

**Comment by endless-sky** [comment]
Fixed, and fixed. Thanks!

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
