### ISSUE TITLE
Fleet Movement Mode

### ISSUE THREAD

**Issue by pepoluan** [endless-sky/endless-sky#9255]
### Problem Description

Sometimes I ride the most maneuverable ship in my fleet, which means that if I want to keep my fleet "in formation", I have to hold <kbd>J</kbd> at least on the final hyper.

However, the slower ships will lag behind quite severely if I only do that on the final hyper, so I ended up having to hold <kbd>J</kbd> on every step of the travel.

### Related Issue Links

Not that I know of.

### Desired Solution

A "Fleet Movement Mode" toggle that practically does the following:
* Ensure all fighters and drones are docked to their carriers
* Ensure all ships are ready to hyper/jump (all white, no yellow)

... on every step of the travel.

Kind of like "Automatically hold down <kbd>J</kbd> for you on every step".

### Alternative Approaches

Can also do this, like, pressing <kbd>Shift</kbd>+<kbd>J</kbd> on a leg will activate the "Fleet Movement Mode" for the next legs until destination is reached and/or autopilot is interrupted using the movement keys.

**Comment by Hecter94** [comment]
If I understand your request correctly, Shift+J actually will do what you want.
![image](https://github.com/endless-sky/endless-sky/assets/15916854/f4b0a1b5-5e7d-4707-8f30-a41235504dc1)

https://github.com/endless-sky/endless-sky/assets/15916854/d22bd522-8cc4-4fc5-a6ed-5db8da5a42bb

**Comment by pepoluan** [comment]
> If I understand your request correctly, Shift+J actually will do what you want. ![image](https://user-images.githubusercontent.com/15916854/265273354-f4b0a1b5-5e7d-4707-8f30-a41235504dc1.png)
> Untitled.1.mp4

Wow! Is that new? I'm on 0.10.2 stable and I don't think I ever see the "Jump as a Fleet" option documented somewhere...

**Comment by Tecmes** [comment]
Running 10.6. Is shift+J supposed to work still? When I try it, it does nothing. If I hold Shift-J, it does as holding J, except the fleet doesn't jump when released.
