### ISSUE TITLE
Minor issue - windows application has no icon when running

### ISSUE THREAD

**Issue by localzuk** [endless-sky/endless-sky#926]
When Endless Sky is running on Windows, the process has no icon in the task bar, or in the top left of the window. (See circled in attached image).
![icons](https://cloud.githubusercontent.com/assets/998988/14245832/dd9c14f2-fa5b-11e5-8fe5-c10d4823425e.png)

I'm running the latest Windows 10 Pro 64bit release.

**Comment by endless-sky** [comment]
This should be fixed as of commit 9f98ff9.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
