### ISSUE TITLE
Enhancement: outfit variants

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#927]
it's been raised before that the Hai and Lovelace sell the same Fusion Generator.  There are other examples of outfits that seem to merely be "similar enough to x to be represented by it", and lose potential character (and player immersion) as a result.

similar to ship variants, perhaps slightly different spec outfits that carry the same name - the Syndicate sells stuff that falls closer to the lower end of their quality threshold to distributers in far flung markets, or the Hai/Lovelace fusion generators, or the Deep has begun using a new material for their Laser lenses, and the old stock is still being cleared from outfitters carrying only their "basic" offerings, or the 'prototype' ebeams on the upper tier Marauder variants...just a couple of applications off the top of my head...

i haven't thought this idea out very thoroughly, so forgive me if there are potentially fatal flaws in it.

**Comment by DingusShingleton** [comment]
Actually, there is precedent within the game already.... Modified blasters! 

I think it's a cool idea, although it risks becoming an uncontrollable leviathan of outfit variants that could overwhelm newer players and introduce a lot of complication into what is now a relatively straightfoward system. 

Although it would be really cool to load up a bunch of advanced weaponry and ship it to systems that don't have access to it. Lord of war style.

**Comment by LocalGod79** [comment]
i considered that you could just make additional outfits that carry slightly different names...

you could look at the hyper/scram/jump as variants of the same outfit, as well...

i'm trying to think of ways to increase the depth while maintaining the existing simplicity - as i've said, this idea is only half-baked, and might just be more fluff...

regarding 'lord of war'; i've always thought that if you were selling outfits at venues that didn't normally carry them, they should carry a slightly higher price tag - rudimentary outfit merchantism.  that said, margins would need to be pretty small, given the base per-ton value of outfits in general...perhaps this is another issue entirely, though...opening now...

**Comment by Wrzlprnft** [comment]
Am i getting your request right?
A way to implement two outfits with the same stats, same name but different sprites with a minimum of code like variants do?

**Comment by LocalGod79** [comment]
that was the original idea...

perhaps in my initial expression, a brainstorm took hold of me and expressed more of a stat direction.

**Comment by endless-sky** [comment]
The truth is that I was being lazy when I created the Hai, which is why they have so many outfits in common with humans. I suppose you could claim that a few of those outfits were Hai technology that humans copied and explain it that way, but really they should have gotten their own engines, generators, etc.

**Comment by LocalGod79** [comment]
further expression of @Wrzlprnft thought - the variants (i see two here) would be "same characteristics, different sprite *and* name in the outfitter." (the other idea is really just multiple outfits that bear resemblance to each other)

i've been rationalizing to myself that the Hai outfits were similar enough to the Humans' that it didn't make sense to duplicate a pile outfit coding for an image change...that said, the image forms the bulk of the data, so real efficiency is not being gained.

did you want new images/outfits for the "generic" Hai outfits?  if so, you should add that to your road map (with Pug and Quarg outfit sprites), so that volunteers know to take a crack at them, too.

i could to take a look at duplicating and "smudging" some new Hai outfits, so they're not quite the same as the human equivalents.

**Comment by Wrzlprnft** [comment]
i would volunteer for the images ;)

**Comment by warp-core** [comment]
Closing because this seems to have only been reopened because a PR was opened for it, and that PR has been closed for a long time now.

**Comment by Amazinite** [comment]
This is a milestoned issue.

**Comment by lumbar527** [comment]
> What issues would outfit variants solve?

In my PR (#8721), this could be very useful, as `require "Jump Drive"` would refer to any variant of a Jump Drive.

**Comment by Zireael07** [comment]
IIRC tags were proposed but rejected?

**Comment by lumbar527** [comment]
Outfit tagging would be helpful, but it wouldn't cover removing outfits.

**Comment by Amazinite** [comment]
Any reasons that we would have wanted outfit variants are now pretty effectively resolved by the existence of auto-conditions that let you check how many of a specific outfit that the player has.
