### ISSUE TITLE
Setting to auto-rehire extra crew is missing on mac

### ISSUE THREAD

**Issue by j55blanchet** [endless-sky/endless-sky#9273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In endless sky 0.10.2, on the mac, I don't seen a settings option to automatically rehire extra crew members that have been lost while boarding other ships.

### Steps to Reproduce

1. Install endless sky 0.10.2 on mac (open dmg, drag to applications folder, launch).
2. Go to preferences > settings.
Option for rehiring lost crew is missing.

When playing the game and capturing ships, I have to keep manually rehiring the crew.

### Expected Behavior

There should be a visible on/off setting for automatically rehiring lost crew.

### Screenshots

<img width="1130" alt="image" src="https://github.com/endless-sky/endless-sky/assets/4062772/89707655-2eb0-4e3b-90b6-4b8b44aa09c5">

### Operating System

MacOS Ventura

### Game Source

GitHub Releases

### Game Version

v0.10.2

**Comment by warp-core** [comment]
That setting is on the next page, in the "Gameplay" category.

**Comment by j55blanchet** [comment]
Didn't see that! Thank you
