### ISSUE TITLE
Enhancement: outfit trading

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#928]
e.g. - outfits carry a 2-5% premium when not part of the normal stock for that outfitter.

this would allow you to trade with your outfit space as well as your cargo space.

edit: this cannot work currently because of hand to hand outfits.

**Comment by jafdy** [comment]
Seems like a good idea but . . . 
Instinctively I can feel that 2% profit on a 9M credit reactor is going to be a lot. So I've run the numbers:

5% premium, 130 outfit space:
72692 credits per ton per run

2% premium, 130 outfit space:
70615 credits per ton per run

2% premium, 170 outfit space:
54000 credits per ton per run

That is quite a bit more than I was expecting.

**Comment by LocalGod79** [comment]
agreed (i just threw the numbers out there as an example - thank you for running the math) - perhaps 0.1-1%?

**Comment by jafdy** [comment]
Ok so sticking with the 170 outfit space and keeping profit in ton per run:

0.1%: 52994 credits
0.01%: 52946 credits

hang on I've made a mistake.

**Comment by jafdy** [comment]
Right this is more reasonable.
170 outfit space, profit in per ton per run:

2%: 1059 credits
1%: 529 credits
0.1%: 53 credits

That's better. Its still a lot.

**Comment by LocalGod79** [comment]
that's okay - most ships don't have a ton of outfit space, and you can't "sell all" because you still need to be able to leave...

**Comment by DingusShingleton** [comment]
Yeah, i see this as more of a nice little touch of immersion, and maybe a couple extra credits spending money here and there to make you feel good rather than a legitimate source of income

**Comment by jafdy** [comment]
It will need to be set low as my numbers assume one Armageddon reactor and one Lqu He that your not selling. 
If you get 300 outfit space you can trade with 2 reactors and 1 cooling so with:

1%: 600 credits per ton
0.1%: 60 credits per ton

You could do that on a 4 day cycle, the best trade rout I can find is 800 credits per ton over 12 days. Outfit trading will be much more available than a commodity trade rout like that one.

**Comment by LocalGod79** [comment]
i just proposed the idea - you've apparently got the math skills to find a reasonable number.  typical good  commodity exchanges can be 250+ credits/ton.

so perhaps a 0.2% (120credits/ton) increase is reasonable - you want to be able to make a living off of it, but not better than if you were traditionally trading commodities.

as D.S. pointed out, it's more an immersion option than a legitimate track (for the moment)...

**Comment by jafdy** [comment]
Sounds good, I just wanted to make the numbers fit so we don't get another money spinner like capping.

**Comment by LocalGod79** [comment]
indeed - we're all on the same side, and @endless-sky can make the choice on the exact number if/when the commit is merged - thanks again for providing the math!

**Comment by LocalGod79** [comment]
if #927 evolves, it could facilitate a more comprehensive 'outfits as commodities' model, so that it would be worth a little more if one took some giant batteries from Rust all the way up to the Deep or Lovelace outfitters.

**Comment by toilethinges** [comment]
Buying stuff and putting it in cargo is a planned feature, is it not? Then you could buy ton upon ton of missiles, which take 0 cargo space, and sell them one jump away for immeasurable profit.

**Comment by LocalGod79** [comment]
@toilethinges the "buy outfits into cargo" should theoretically still have the ammo capacity of the outfits stored there, to keep that missile bug under control (should outfits as commodities become a thing).  that said, missiles are pretty widely available, and button wear becomes a concern (at least for me - i'd sooner just hack the save) if you're just buying and selling masses of them.

the idea with this issue is that outfits that are not sold at a particular outfitter would carry a flat premium - so that they cost same to buy as sell at *that* outfitter, even if the price point is slightly higher than outfitters where that outfit *is* sold normally.

i.e. the ArmaCore at Ada costs 9M credits, and is both bought and sold at that price point.  The same ArmaCore is not available at Relic, so would be sold *and* bought at (9M + 0.2%) 9.018M credits.

**Comment by DingusShingleton** [comment]
@toilethinges Nobody is suggesting buying and selling for a different price at the same outfitter. That would be madness.

@LocalGod79 By button wear, are you referring to clicking sell a bunch of times? Cause you can hold crtl shift and alt to sell like 50,000 of a thing at a time.

Missiles are the rub though, aren't they? The only way I can see to fix this is by giving missiles mass, which makes perfect sense but I assume up until now was a point of realism that just wasn't necessary. 

If we assume that any given launcher is mostly magazine, we can estimate the masses of the ordinance and come up with some data to work from. I assume 75% of launcher mass as magazine, and extrapolated profit/ton for the different ammunitions. At .2% profit, here is what I came up with:

   Ammo           $/Ton
Heavy rocket	  53
Javelin	          22
sidewinder	  76
meteor	          47
torpedo	          45
thunderhead  	  74
hai tracker	  79

As you can see, they are all quite reasonable. Perhaps for the sake of simplicity missiles could be counted as having mass only if they are loaded into cargo?

**Comment by LocalGod79** [comment]
the problem with adding mass without occupying capacity is that it is still possible to load up unreasonable numbers of the thing, and in the process unintentionally alters the heat characteristics of the ship.

because of the way dissipation works, adding enough mass can effectively replace a cooler (if rendering your ship a little sluggish).

**Comment by DingusShingleton** [comment]
But you still only have x tons of cargo space right? Whether your 100 tons of cargo is one reactor or 10000 missiles doesn't matter, as long as you can't reload your launchers from your cargo hold.

**Comment by LocalGod79** [comment]
@DingusShingleton perhaps i was unclear - mass, outfit space, engine capacity, weapons capacity, cargo capacity - are all independent attributes.  i ran with the term you used.

**Comment by DingusShingleton** [comment]
Oh I'm sorry, but I never intended for them to not take up capacity except for when they are in a launcher. While loaded into a launcher would act as they do now (which is they don't take up anything but launcher capacity). Missiles loaded into a cargo hold however would act like any other thing in a cargo hold, IE if it is 1 ton of mass, it takes up 1 ton of cargo space. That way, you couldn't fit any more tons of missiles in your cargo than any other outfit or commodity.

**Comment by LocalGod79** [comment]
so why not continue the launcher capacity theme and just make it so that to transport missiles, you need to also be transporting the launcher/magazine (if the mag is indeed the vast majority of the outfit)?

**Comment by DingusShingleton** [comment]
You certainly could do that, but it doesn't make much sense. Plus, not every place that sells launchers sells the equivalent ammo, and vice versa. But that is a simpler way to do, so I support it.

**Comment by LocalGod79** [comment]
i'm just concerned that the amount of work required to make missiles an independently traded outfit would show minimal payoff, given the generally widespread availability of ammo...

**Comment by DingusShingleton** [comment]
Right, but that's the problem with trying to introduce outfit trading. You have to do *something* with missiles to keep the system consistent, or else what's the point? Especially since, as we agreed, this is mostly for immersion.

**Comment by LocalGod79** [comment]
and why not making much sense?  your words: "...I assume 75% of launcher mass as magazine..."  would it be so unreasonable to think that appropriate shipping packaging (for explosives) would be significantly less massive/voluminous?  i believe this is another case for weapons variants.

**Comment by DingusShingleton** [comment]
>so unreasonable to think that appropriate shipping packaging (for explosives) would be significantly less massive/voluminous

No, it's not, what I meant was that, for example, if I go to an outfitter that sells javelins but not javelin pods, I would be unable to purchase javelins. That doesn't make sense to me, because clearly Joe Outfitter is getting the javelins without pods, so why wouldn't I be able to?

**Comment by LocalGod79** [comment]
because Joe Outfitter isn't actually shipping them - that his supplier has appropriate equipment (javelin pods in their cargo hold, which Joe isn't interested in, because they're not a hot seller) for the storage and transportation of those Javelins, which are then transferred to Joe's static storage facilities.

**Comment by DingusShingleton** [comment]
I guess.. it just seems like if coke only sold coke already inside a vending machine. It's not efficient. But ultimately, this is a game, which is why, again, I said I would support this workaround.

**Comment by LocalGod79** [comment]
in your coke example, the vending machine is the outfitter, and the owner supplies the machine from "magazines" (cartons), which do not stay within the vending machine - a convenience store who's stock level was low, could not buy a case of coke to stock their shelves...

**Comment by LocalGod79** [comment]
and discourse is always welcome - i've usually thought out more than i've posted, and the opportunity to express the idea more wholly is appreciated!

**Comment by DingusShingleton** [comment]
Well I have always assumed that packaging was a given. I mean, it's not like I'm just shoveling a thousand tons of loose wheat into my cargo holds, right? 

And thank you. I mean, this community is why I'm still even thinking about endless sky, and the ability to contribute to its development is just amazing.

**Comment by LocalGod79** [comment]
i think that our discussion went well beyond the scope of the rudimentary immersion of having a 0.2% flat increase on the price of outfits not normally sold at a particular outfitter, and began the discussion of a more comprehensive outfit trading system.

since nobody else seems to be discussing it, let's try to bounce some more ideas around to illustrate different ways to approach #570 - specifically missiles.

that way M.Z. will have some differing cross-ex to decide on an approach.

this also may be an opportunity to hack at #341

**Comment by LocalGod79** [comment]
further, i think this could all integrate well into #852 with used outfits and ships being more available further away from their production sources

**Comment by Hyratel** [comment]
here's a clarification-idea: any Cargo'ised ammo (either loot or purchased beyond the magazine capacity of your current equips) is not available for loading. So those 50 Javelins you just looted becomes "Crated Javelins", with a distinct Outfitter icon, and possibly weighing a fraction more than the equivalent "loaded ammo". These would be consumed preferentially when you land at an outfitter and are prompted for missile resupply, and would help with the problem of Massless Ammo because it's a different *kind* of item.

**Comment by toilethinges** [comment]
@DingusShingleton - in response to your reply to me.

Not buying and selling at the same one, but buying at one, and then jumping once, to a planet which does not have that outfit in it's outfitter. Because there are places that don't have missiles... it wouldn't be on the same planet, but just one day.

@Hyratel: I like that idea.

**Comment by LocalGod79** [comment]
@toilethinges could you identify the outfitter that sells missiles one jump away from another that doesn't?

**Comment by toilethinges** [comment]
@LocalGod79 - For Heavy Rockets: Alphecca, Seginus. For Javelins, the same, plus Caph and Diphda. Other places have two jumps between - you can still make tons and tons of money.. plus, most are a Jump Drive jump away. You can even, without a Jump Drive, buy Typhoons in Alphard and sell them in Talita.

**Comment by LocalGod79** [comment]
@toilethinges the player would make 2 credits per equipped *Javelin Pod* running between Diphda/Caph or Seginus/Alphecca (and pay two days crew salaries in the process - one for takeoff, one for jump).

Heavy Rockets are a little more profitable, but at 80 credits per equipped Launcher - still very reasonable...

**Comment by toilethinges** [comment]
@LocalGod79: remember, if you read my original post, that I am saying this _with being able to buy into cargo._ Since rockets take no cargo space and take up no mass, you could carry infinite loads, meaning infinite profit. Anyway, several people have had good ideas as to how we could limit this, so my point is void.

**Comment by LocalGod79** [comment]
@toilethinges several suggestions have been made to deal with that eventuality - either requiring the outfit (and its capacity), or 'crating' missiles that go into cargo, giving them a capacity.

as the moment, besides the possible missile solutions outlined, a more comprehensive "outfits as commodities" model is required if it were to be implemented alongside "outfits as cargo"...i've mentioned this before - perhaps an algorithm that escalates an outfits value based on the number of jumps from the nearest outfitter where that outfit is available might work...

**Comment by jafdy** [comment]
what about hand to hand weapons. apart from the security station they take up no room.

**Comment by LocalGod79** [comment]
it's always *something*...

well, at least we had a discussion about a more comprehensive outfit trading model...

**Comment by wambat1** [comment]
i see this conversation is in the context of variable outfitter prices, and the resulting trade possibilities. my suggestion was more in the context of an attractive missile missile system (the two Kor weapon systems) whose ammunition cannot be purchased. do i take it from the above discussion that it is possible to make an outfit hat is a large capacity "launcher" that lacks the ability to launch missiles? failing that the player has to park large numbers of ships packed with Kor launchers to maintain a reasonable reserve of missiles. if so, so be it, but fleet management already feels out of hand to me with the number of ships i have to keep parked around to hold various outfits.

**Comment by jafdy** [comment]
You can keep as much ammo on your flagship as you like. So long as you avoid the sell all button.

**Comment by wambat1** [comment]
that's just the thing. it is hard to avoid pressing "sell all" out of habit, and you often do not catch yourself until well too late. i thought a simple outfit to address this problem, and be balanced by the sacrifice of whatever outfitter space was felt to be needed for balance. a player who spends hours building up a missile reserve can be very discouraged when it is lost from a momentary laps of attention.

**Comment by jafdy** [comment]
It's become a bit of a different issue but I believe it is possible to increase your ammo capacity. Don't know if that will increase the number you can fire. This has been asked for before so check that you don't open a duplicate.

**Comment by LocalGod79** [comment]
@wambat1 i think the point i was making was that ... 13 posts ago by Hydratel:

> here's a clarification-idea: any Cargo'ised ammo (either loot or purchased beyond the magazine capacity of your current equips) is not available for loading. So those 50 Javelins you just looted becomes "Crated Javelins", with a distinct Outfitter icon, and possibly weighing a fraction more than the equivalent "loaded ammo". These would be consumed preferentially when you land at an outfitter and are prompted for missile resupply, and would help with the problem of Massless Ammo because it's a different kind of item.

which seems to be exactly what you asked for in a new issue.

**Comment by jafdy** [comment]
Ether one will need a code change to implement and just cargoised ammo is not what this issue is about. It was a facilitating idea. This issue flopped at hand-to-hand outfits.

**Comment by LocalGod79** [comment]
@jafdy as i understand it, @wambat1 wants "ammo crates" so that he can hit "sell all" and not lose ammo he cannot get any other way but plundering.

i was pointing out that it's a pretty crucial point of this issue (missiles as cargo), and therefore is addressed (and on the "roadmap")

**Comment by VonZorch** [comment]
The problem of unintentionally selling outfits in cargo can be fixed by having the first <sell all> not selling outfits the first time you <sell all>, then selling outfits on a second <sell all>.
