### ISSUE TITLE
Allow ships to define their center of rotation

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9285]
### Problem Description

The center of rotation of a ship is currently defined by the center of the image sprite. This means that if you want a ship with a center of rotation that is higher or lower on the ship's body, you need to leave a lot of empty space in the top or bottom of the ship sprite to shift the center of the image.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/4814#issuecomment-586590010 Similar to the "effect offset" that tehhowch mentions here.

### Desired Solution

Allow ships to define a point for their center of rotation. If a center of rotation is not defined, continue to use the center of the image.

### Alternative Approaches

N/A

**Comment by RisingLeaf** [comment]
This one is done right?
