### ISSUE TITLE
Postverta/Ssil Vida Exit After Powering On Space Station

### ISSUE THREAD

**Issue by MonkeyMatrix** [endless-sky/endless-sky#9287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After activating the Ssil Vida space station, the player is able to escape this small part of the universe to return to Edusa. The player is able to jump back into Postverta to disable the station or complete any missions outside of the set of systems.

### Steps to Reproduce

Go to the Ssil Vida station in Postverta.
Power on the space station.
Go into the map to set your destination to Edusa, which requires one jump.
Depart from the station. (When viewing the map in space, I did not see a line from Postverta to Edusa.
Initiate your jump.
You should be outside of the universe powered by Ssil Vida.

### Expected Behavior

You should not be able to jump out of the universe powered by Ssil Vida while the power to the station is active.

### Link to save file

[Monkey Matrix.txt](https://github.com/endless-sky/endless-sky/files/12570626/Monkey.Matrix.txt)

### Operating System

Pop!_OS 22.04 LTS

### Game Source

GitHub Releases

### Game Version

v0.10.2

### Additional Information

I am fairly sure the player should not be able to jump out of Postverta into the rest of the universe while Ssil Vida is activated. It seems that the game is not updating the jump route to ensure the player cannot jump to Edusa after departing from Ssil Vida. If the player makes any amount of jumps inside the small universe, the jump route is updated. This also occurs on the mobile version of the game.

**Comment by warp-core** [comment]
It looks like the existing travel plan is not checked after the jump range is reduced and, after that point, there is nothing that checks the validity of the planned jump.

**Comment by Zitchas** [comment]
You are correct, the player shouldn't be able to jump out. Thanks for spotting and reporting this!

**Comment by warp-core** [comment]
I'm unclear on what the meaning of adding this issue to the Ember Waste proje t is. Would you be able to elaborate?

The problem may be demonstrated by content relating to the Ember Waste, but it is not exclusive to that content. A plugin could also demonstrate it.
The actual problem occurring isn't in the Ember Waste game data, nor does the solution lie in modifying any data related to the Ember Waste (unless we simply remove the remove the reduced jump range from these systems, which wouldn't actually solve the problem, simply remove the opportunity to demonstrate it in the vanilla game).

**Comment by Zitchas** [comment]
Sure. I tag anything that impacts those missions. If the problem isn't resolved, then it's breaking those. It's not an indication of being restricted to that area.
