### ISSUE TITLE
Person Governments

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#930]
I've added a pull for a person #929 #934 , which doesn't really fit into the "author" government, but was not special enough to be worth a own government. So i had 3 options:

- Add it to government as a first start and open a issue
- Add a government without swizzle and hails with a neutral name for all no-belonging persons
- Add a government especially for this person

Since i am kind of lazy, and i don't want to spam the governments.txt, i made this issue.

**Comment by endless-sky** [comment]
A government is a rather lightweight object - they don't really do much aside from reflecting who's hostile toward whom. So, you should go ahead and create new governments if you want one with a different name.
