### ISSUE TITLE
Documentation: CreatingOutfits: Hand to hand attributes

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#931]
Not sure if I am missing something but a description of "capture attack" and "capture defense" is nowhere to be found. Thought that might be an oversight. While I'm here, can hand to hand outfits have any other attributes, or are they limited to those two? The reason I ask is because I'm trying to figure out a boarding droid outfit that increases capture A/D but doesn't require a crewmember to operate.

**Comment by LocalGod79** [comment]
i've heard of people adding crew compliments to their hand to hand outfits (space ship siege engines, to describe them).

i imagine most non-weapon attributes could be attached to an outfit in the "hand-to-hand" category, but it would probably then more accurately fit in another category.

i have added "capture defense" to other outfits without issue.

**Comment by endless-sky** [comment]
Added to the ["creating outfits"](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits) page.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
