### ISSUE TITLE
Flathub page claims the game is proprietary and not open source

### ISSUE THREAD

**Issue by popcar2** [endless-sky/endless-sky#9312]
### Location

https://flathub.org/apps/io.github.endless_sky.endless_sky

### Describe the issue

The Flathub page for the game claims it's a proprietary game, even though it's open-source.

![Screenshot showing the game tagged as proprietary](https://github.com/endless-sky/endless-sky/assets/16920817/84fddba8-93b9-476f-bcd7-ae738c1cbe52)

### Expected content

It should be tagged as an open-source game with a GPL-3 license.

**Comment by MCOfficer** [comment]
Let's move this to the [flatpak package](https://github.com/flathub/io.github.endless_sky.endless_sky/issues/28), since it's not officially supported (#7143)
