### ISSUE TITLE
Excessive CPU Usage when readying to jump?

### ISSUE THREAD

**Issue by VaelophisNyx** [endless-sky/endless-sky#9316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whenever I have a fleet of ships (even as few as 6?), holding J to prep to jump with all of them at once causes my CPU usage to rocket up from ~10-20% to >200%, often well in excess of 400%, while the game thus slows to a crawl.
The more ships in the player fleet prepping to jump, the worse it gets.

Important notes

- Modded JD with 900 range*
- system manually chosen, not randomly selected by hitting J
- if one simply taps J and jump immediately, then wait for escorts to catch up this does not occur, but does leave the flagship vulnerable while it waits
- my plugins list contains 9 plugins, of varying size and age, though none of them should be causing this issue
- *still occurs with vanilla JD ranges, just requires far more escorts (upward of 80+)

this also occurs when you have escorts, and is particularly bad in the Hai Reveal mission set, due to the quantity of escorts for one particular mission.

Hardware wise, I'm sitting on 32Gb of RAM and for my processor, see this screenshot:
![image](https://github.com/endless-sky/endless-sky/assets/1534478/e927f72c-b78b-4301-b236-0983c1ea194b)

GPU is not a concern here, it never exceeds 15% utilization in any event.

### Steps to Reproduce

1. Assemble a fleet of 6+ ships
2. attempt to prime a jump by holding J
3. Watch the CPU utilization jump abnormally high

### Expected Behavior

CPU utilization during jump priming shouldn't be greatly effected

### Link to save file

[Vaelophis Nyx.txt](https://github.com/endless-sky/endless-sky/files/12668479/Vaelophis.Nyx.txt)

also a copy of my plugins folder, for exact-case diagnosis
https://drive.google.com/file/d/1OLFFxujwl-ri9ay3I1W5AMw0ud-YtduK/view?usp=drive_link

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.10.2

**Comment by VaelophisNyx** [comment]
honestly, from my limited coding knowledge (of a different game, but still), and player perspective, it feels like some sort of path finding is being called every single frame for every ships while J is held down...which I really hope isn't the case

**Comment by VaelophisNyx** [comment]
oh and this is semi-inconsistent, it's frequent but not omnipresent

**Comment by Amazinite** [comment]
Confirming that this still occurs on 0.10.3.

> it feels like some sort of path finding is being called every single frame for every ship while J is held down...which I really hope isn't the case

Pretty sure it is. 🙃
It isn't an issue for vanilla because the search space of the jump drive is so small, but when dealing with larger jump ranges, it starts to become noticeable.

**Comment by VaelophisNyx** [comment]
my question then, if that's right, is "why is there path finding being done when the systems are already chosen and the most complicated thing involved is to have your escorts slow down"

**Comment by VaelophisNyx** [comment]
Should also note, this occurred with a normal JD too, when I had a fleet with....I think it was 80 escorts

**Comment by mOctave** [comment]
> my question then, if that's right, is "why is there path finding being done when the systems are already chosen and the most complicated thing involved is to have your escorts slow down"

The answer is probably simply that way back in the dawn of ES Michael Zahniser wrote it that way by accident or for some no-longer relevant reason, and it wasn't a big issue considering that the game is balanced around solo-ship play, especially since by default you'd need so many escorts to run into issues.

This is definitely something that should be fixed now, of course.

**Comment by Ferociousfeind** [comment]
This is a prevalent issue if you use Omnis, and have at least 1 escort with the Omnipresence outfit (has a JD range high enough to cross the entire galaxy), the single ship causes the game to come to a crawl during the whole jump animation, and causes no lag at all if you tell your escorts to wait, and call them to you once you're at your destination.
