### ISSUE TITLE
During jumping, a landable planet will flash for a moment

### ISSUE THREAD

**Issue by bene-dictator** [endless-sky/endless-sky#9331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During hyperspace travel, a landable planet (apparently in the destination system) will flash at the location of your flagship. This does not always happen, ~~and seems to be connected to whether you have a mission at a planet in the system.~~ (not sure of this)

### Steps to Reproduce

Jump to a planet with an inhabited planet that you have a mission to. Use a hyperdrive, not a jump drive.

### Expected Behavior

No planet flashes during hyperspace jump.

### Screenshots

https://github.com/endless-sky/endless-sky/assets/115441627/84f337f4-5411-49b1-848e-59f1274f8f4e

I have no mission to Follower, but it flashes.

https://github.com/endless-sky/endless-sky/assets/115441627/8bb89077-4541-4950-82f0-6d3d0e7e015c

I have no mission to Vinci and it doesn't flash. I have a mission to Vail but it doesn't flash, instead Calda flashes.

### Operating System

MacOS Ventura 13.4.1

### Game Source

Built from source

### Game Version

a576744235474c7c1c8055703e5bcc10bdc8da12

**Comment by quyykk** [comment]
Can you post a save file? I'm having trouble reproducing

**Comment by bene-dictator** [comment]
[Ford Prefect.txt](https://github.com/endless-sky/endless-sky/files/12706310/Ford.Prefect.txt)
[Ford Prefect~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/12706311/Ford.Prefect.previous-1.txt)
[Ford Prefect~~previous-2.txt](https://github.com/endless-sky/endless-sky/files/12706312/Ford.Prefect.previous-2.txt)
[Ford Prefect~~previous-3.txt](https://github.com/endless-sky/endless-sky/files/12706313/Ford.Prefect.previous-3.txt)

Unfortunately not the same location, if that will matter.

**Comment by danaris** [comment]
Does it still happen if you turn off "Extended jump effects" in the preferences?

**Comment by bene-dictator** [comment]
Doesn't look like it does happen with 'Extended jump effects' off.
