### ISSUE TITLE
Make weapons not fire if target is out of range

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#935]
If a target is out of range for some weapons, those weapons should not fire and conserve ammo and energy and heat. 
Better yet (perhaps worth an option in the game menu): firing at targets of opportunity in range for those weapons for whom the primary target is out of their respective ranges (or possibly fire arc, perhaps, in the future)

**Comment by LocalGod79** [comment]
ummm...autofire?

**Comment by LocalGod79** [comment]
i think what may end up happening is the "auto aim" ( #314 ) feature will become the default if the target is out of range, and then standard "fire" will take over once the target is in weapon range...

**Comment by endless-sky** [comment]
Yes, I'm confused... both these things are already supported, both by the AI and by player ships if auto-firing is turned on.

**Comment by wargwargwarg** [comment]
let me explain: automatic aiming and firing both on, target selected. 
If within range, turrets will blast it on auto. If within range and aligned, fixed weaponry will auto fire. OK to both.
But when I press primary fire button , all primary weapons (fixed and turrets) will fire, no matter if the target is within or out of range. Lots of wasted energy, heat  and expectation. 

That's what I referred to. 

Hm, to refine on what I said in my initial post,if out of range and if distance to target can be compared between this frame and the last, a prediction algorithm could be made:
- if closer, than fire if the shots at their velocity would connect with target at the end of their range
- if farther or same distance, don't fire, shots will be wasted

**Comment by endless-sky** [comment]
If automatic firing is on, your ship will fire only when it calculates that it can hit something, and will take opportunity shots at enemies other than your current target. That's the exact behavior you seem to be requesting. So, the only thing you need to do is turn automatic firing on and never touch the "fire" key.

**Comment by wargwargwarg** [comment]
No, it's not the same thing.
I like the turrets on autofire, they're turrets after all. But not to use "fire" key is a bit much. Where's the heat of the chase? Captain's hot tempered, computer is coolheaded and economical .

Forgot to mention last time: imagine 2 fixed weapons, range 300 and 800. Target at 700 range. "Fire means both fire, short range weapon fire (ammo, heat, energy, time) being wasted.

It's an additional  "if within range" to be added somewhere but if you don't want to, you don't want to...

**Comment by LocalGod79** [comment]
use secondary weapons (they don't auto fire), and chase to your heart's content.

i think from M.Z.'s perspective, you seem to be asking for opposing features.
i.e. you want to optimize (weapons only fire when they can hit) without optimizing (keeping a homo-sapien on fire control).

**Comment by wargwargwarg** [comment]
@LocalGod79, it's called automation, having a machine do mundane, repetitive and boring tasks, as a basis for more precise, economical, productive tasks. It's aiding the human reach the desired outcome.

it's also a small bother, not worth taking chaff from you at a personal level.

**Comment by LocalGod79** [comment]
my intention was not to "chaff" at you on a personal level.

my intention was to point out that your request is either already available (auto fire) or already requested (auto aim).

the point is: an efficiency feature has already been made available - if you're not happy with it's behaviour, feel free to write another.
