### ISSUE TITLE
Duplicated station image

### ISSUE THREAD

**Issue by quyykk** [endless-sky/endless-sky#9356]
`land/station7` and `land/station15` are duplicated.

**Comment by ziproot** [comment]
Openverse is a website I found that has creative commons images. Now, not all of these are free licenses, but you can check "use commercially" and "modify or adapt" to only select free licenses, e.g. https://openverse.org/search/?q=space%20station&license_type=commercial,modification (not a great search but it's a start). So if you're trying to find images that have free licenses, this is a website I've found useful.
