### ISSUE TITLE
Make it possible to get a good rep with all Wanderer planets

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#936]
I've noticed through playing that you cannot land on some Wanderer planets because of high security. Could there be a way to get a better rep with them?

**Comment by LocalGod79** [comment]
i'm gonna guess: "eventually" ;)

**Comment by jafdy** [comment]
I think It's coming in 0.9.0

**Comment by Gkramme** [comment]
I hope so. Maybe if you performed certian missions for them, you could increase your rep.

**Comment by endless-sky** [comment]
I'm planning for there to be quite a long string of Wanderer missions, perhaps even as involved as the Free Worlds. So, I want your reputation to increase gradually over the course of the intro missions, which is why some planets are still off-limits at present.

**Comment by endless-sky** [comment]
As of 9308888, completing the most recent Wanderer missions will make all but one of their worlds accessible to you.

**Comment by Gkramme** [comment]
Alright, closing this.
