### ISSUE TITLE
The explanation of the add and remove event keywords is confusing

### ISSUE THREAD

**Issue by hexagonrecursion** [endless-sky/endless-sky#9367]
### Location

wiki

### Describe the issue

I find this phrasing confusing:

> https://github.com/endless-sky/endless-sky/wiki/CreatingEvents
> For data elements that can take a list of an arbitrary number of values (such as the attributes of a system or planet), if an event modifies that element, by default it replaces all of the previous values. **To make it clearer whether that is your intention or not, starting in version 0.9.7 you can use the add and remove keywords:**

### Expected content

For data elements that can take a list of an arbitrary number of values (such as the attributes of a system or planet), if an event modifies that element, by default it replaces all of the previous values. **Starting in version 0.9.7 you can modify such elements without replacing the previous value by using the add and remove keywords:**

### P.S

Unfortunately I can't edit the wiki myself :(

**Comment by quyykk** [comment]
Fixed thanks!
