### ISSUE TITLE
Alien Escort Missions

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#937]
One of the things I would really like to see in this game is the ability to escort alien ships. This would add some sort of diversity to the game and give alien-inhabited areas more monetary value.

**Comment by psychiclegume** [comment]
What aliens?
The Quarg are super powerful, the Hai and Wanderers have no pirates, and the Korath hate you. what is there to escort?

**Comment by lehgogh** [comment]
What about, for example, escorting scientists into alien territory?

**Comment by psychiclegume** [comment]
From deep to Hai or wanderers?

**Comment by Gkramme** [comment]
@psychiclegume, the Hai have the Unfettered as an enemy and the Wanderers do too.

**Comment by jafdy** [comment]
The Hai have bottled the Unfettered in the north of there space and Wanderer cargo ships can jump before they are destroyed.

**Comment by psychiclegume** [comment]
If you have made peace with the unfettered, than what difference does if make to have you escort them? The unfettered would not attack you because you are friendly.

**Comment by lehgogh** [comment]
I was thinking of escorting humans into and out of alien space. (scientific research, tourism, etc.)

**Comment by Gkramme** [comment]
@lehgogh good idea, but how do these scientists know about alien space? (Besides Quarg space)

**Comment by lehgogh** [comment]
@Gkramme, here's a possible idea:

Two men in lab coats approach you as you step off your ship, claiming to have found an unexplored planet inhabited by aliens. They ask if you can escort them there to collect samples and examine the foreign species and return them to their research lab.

Humans can still have observatories, satellites, probes, etc. that find alien planets. I'm sorry if this isn't possible within the storyline; I still haven't finished the FW missions. Should I have done that before coming here?

**Comment by Gkramme** [comment]
The Free Worlds storyline doesn't add too much, so you're fine there. I think the possible discovery of aliens would throw off the in-game lore and require a whole other storyline to make sense. I guess you could escort republic people to Hai space, but that woundn't be very exciting.
