### ISSUE TITLE
Default "Extended jump effects" + "Render motion blur" causes noticeable GPU usage

### ISSUE THREAD

**Issue by Saugia** [endless-sky/endless-sky#9391]
### Problem Description

Following our release of v0.10.3, several players have indicated that jumping causes excessive lag. After some suggestions, disabling "Extended Jump Effects" seems to alleviate those concerns. However, while testing this, I've noticed that the GPU spike only occurs if both "Extended Jump Effects" and "Render Motion Blur" are enabled at the same time.

Note that a lot of this is coming from having the game zoomed out more/all the way, which is expected.

### Related Issue Links

N/A

### Desired Solution

A less GPU-intensive defaulted preference setup to be more friendly to the overall player base. Either have "Extended Jump Effects" disabled by default, or "Render Motion Blur" disabled by default, as both are currently enabled by default.

### Alternative Approaches

Keep the current settings if we believe that this is something that should remain defaulted and cases be handled individually.

### Additional Context

I'm running a RTX 3060ti, and when I have both options enabled then zoom out all the way for a jump, I'm jumping to ~58% GPU usage from ~10%, which is going to be comparatively noticeably more on average and especially lower-end GPUs.

Note that we've also recently updated our system requirements, but if I'm getting this jump in GPU usage, perhaps it's better we avoid lower-end systems defaulting to it.

**Comment by Hecter94** [comment]
Interestingly, I'm running an RTX 3060, which should be a weaker card, yet even when I have both options enabled, my GPU usage barely changes—going from 1% to 2-3%.
I feel like there is some other bug that's not entirely related to hardware performance here. Perhaps driver/OS related? 

(Sorry for the low-quality video; GitHub is limited to 10mb uploads)
https://github.com/endless-sky/endless-sky/assets/15916854/92be1b0c-22c3-4563-9d6a-7da078ec856a

**Comment by RisingLeaf** [comment]
Short info where the problem is coming from:
"extended jump effects" virtually increases the velocity of the ship, drawing the starfield we extend the area that virtually gets drawn to include stars that could still be drawn because of motion blur, with extended jump effects this increases the draw area in X direction by 3500 pixels in each direction which is total overkill drawing more stars by a factor 9

**Comment by RisingLeaf** [comment]
I suggest disabling the effect by default or greatly decreasing the amount

**Comment by RisingLeaf** [comment]
For reference during a normal jump without extended effects the draw area only gets increased by up to 200 pixels
