### ISSUE TITLE
Endless-sky crashed after update 0.10.3

### ISSUE THREAD

**Issue by daenguma** [endless-sky/endless-sky#9399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello and thanks for this amazing game! I love it.

Want to report a bug after last update (0.10.2), the game start crashes when I launch it. I found this log in the system registry:

 8:35:40 AM systemd-coredum: Process 4210 (endless-sky) of user 1000 dumped core.

Found module /app/games/endless-sky with build-id: bc67ba4599adcf4372bcd4560bcee9977319432c
Found module /usr/lib/x86_64-linux-gnu/GL/nvidia-390-157/extra/libnvidia-glcore.so.390.157 without build-id.
Found module /usr/lib/x86_64-linux-gnu/GL/nvidia-390-157/extra/libnvidia-tls.so.390.157 without build-id.
Found module /usr/lib/x86_64-linux-gnu/GL/nvidia-390-157/extra/libGLX_nvidia.so.390.157 without build-id.
Found module /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0 with build-id: df774fa2322949cee7662f1effa5d3e96985b869
Found module /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0 with build-id: 6d615905cc2964d436cd6724f41dbaf87f766d65
Found module /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0 with build-id: b138b2742981891a75cb1972b25cf6e02afee7fa
Found module /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0 with build-id: 7b13f007febc61e6c5e106f86f2f75eeb91b2976
Found module /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2 with build-id: cf2a081ae0cb9d623734943f3253a97b7405f3e5
Found module /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.34.0 with build-id: 66cc26d5493ce374c98594c6a0401b5babc949e2
.
.
.

I don't know what it means, but I was able to playing before this update, and at this moment I'm not able to launch it because the error.

I hope you guys can fix it. 

Greetings.

### Steps to Reproduce

1. Launch the game

or via terminal:

flatpak run io.github.endless_sky.endless_sky

Result:

*** stack smashing detected ***: terminated

### Expected Behavior

Start the game succesfully.

### Operating System

Linux Mint: Linux 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Game Source

Built from source

### Game Version

Version 0.10.2

### Additional Information

The game source is flathub

**Comment by quyykk** [comment]
@daenguma Is it possible you are running out of memory? How much RAM do you have?

**Comment by daenguma** [comment]
Hello Nick, thank you! I was wrong with te issue, i'm getting problems with
0.10.3 version. The same that i described, i'm getting error over steam and
flatpak. My pc have 8GB RAM.

I was able to install AND launch version 0.10.2 from github sources with no
problems.

Maybe the last update requires More ram?

**Comment by quyykk** [comment]
The Flathub version contains the High DPI plugin which requires a lot of RAM, so I'm not surprised that one crashes if you only have 8GB of RAM. We'll fix this soon. 

However, the Steam version should not crash, unless you have installed the High DPI DLC on there. If so, I suggest uninstalling it :smile: 

While every update requires more RAM, 8GB is more than enough to run the normal game without the High DPI plugin.

**Comment by Zireael07** [comment]
IMHO Flathub shouldn't contain the High DPI by default to avoid bad first user experience (lots of people have 8 GB of RAM still)

**Comment by MCOfficer** [comment]
https://github.com/flathub/io.github.endless_sky.endless_sky/pull/27

**Comment by Wedge009** [comment]
Interesting. I never noticed any high memory usage on my main machine (64 GiB RAM). But using ES for testing on an old machine (16 GiB RAM) I was concerned about the significant memory usage - thought it was a bug with my hardware. I confirm the memory usage is much more reasonable with the High DPI DLC disabled.

**Comment by quyykk** [comment]
That latest flatpak version on FlatHub doesn't come with the High DPI plugin enabled anymore.
