### ISSUE TITLE
All extra cargo apparently loaded into 2nd ship (or fighter!) in fleet, exceeding its capacity

### ISSUE THREAD

**Issue by DMA57361** [endless-sky/endless-sky#94]
Having a play with the 0.8.2 release; thanks to it's fixes I've managed to use some fighters in my flagship successfully, and have discovered what I think is a bug. When I carry more cargo than my flagship will hold alone, such that it should probably end up spread among the other ships in my fleet, what I see is all that excess cargo seems to be loaded into only the second ship in my fleet - regardless of if it has space for that (or any!) cargo.

Here's a screenshot of that fighter on the info screen when flying, note the cargo in the top-right (I've an additional 270 units of Equipment, which only appears on the flagship's info screen).

![endles_sky_bug_screenshot](https://cloud.githubusercontent.com/assets/1375133/9706106/dc6d95d0-54d2-11e5-83e7-52fed9dd6413.png)

I'd seen this before and just assumed it was just a UI display issue, but that fighter clearly flies like a brick whenever I've got a full cargo load - it turns so slowly and can barely move, this is how I noticed it as it failed to dock with my flagship when my other fighters did. It will perform normally whenever I have little or no cargo.

I can also see the same behaviour if I park all my flagship's fighters and fly with full cargo, as one of my regular escort ships (which are all identical) is then obviously slower than the others - you can see it turning and decelerating slower when jumping.

**Comment by endless-sky** [comment]
You're right, that is a bug. Specifically, when a ship had zero cargo 
space, it was treating it as if it had unlimited space. That will be 
fixed in the next release.

**Comment by endless-sky** [comment]
This is fixed in release 0.8.3/
