### ISSUE TITLE
Consistant (boring) escort missions

### ISSUE THREAD

**Issue by psychiclegume** [endless-sky/endless-sky#940]
Would it be possible to create escort missions that have different variants of ships, such as the fancy Bulk and regular freighters instead of just base model every time. Sure there is some variation on whether you will get a Bulk Freighter or a Behemoth, but that is only on the large missions. At the least it would make sense to have missions with Argosys in the south and rim where you don't find many syndicate ships. Does anyone know if this is possible? And if so could someone as inept at coding as I am do it?

**Comment by jmhorjus** [comment]
Yes! Not only is it possible, but you don't even need to know any code to make new jobs and missions!  
Check out the [wiki](https://github.com/endless-sky/endless-sky/wiki) specifically the Creating Missions section.  

Look in [jobs.txt](https://github.com/endless-sky/endless-sky/blob/master/data/jobs.txt) in the data directory for examples of escort missions to start from.  

And if you have any questions about how to get something working the way you want, ask questions on the [google forums](https://groups.google.com/forum/#!categories/endless-sky/content-creation). Lots of mod makers hang out there and will be happy to give you some pointers!

I'd love to see more variations on existing jobs, especially higher end ones with more difficulty/reward than the current highest tier of missions in all categories.

**Comment by LocalGod79** [comment]
i think this is more a matter of defining some "cargo escort" fleets, and then calling them in the escort missions for the npc save.

i'll take a look at this...

**Comment by psychiclegume** [comment]
Thank you!

**Comment by psychiclegume** [comment]
[merchant_fleets.txt](https://github.com/endless-sky/endless-sky/files/216167/merchant_fleets.txt)
First shot at a set of fleets for the missions. My thinking behind the repetition of some ships is that some captains will have a greater problem than others and will pay more for an escort.

**Comment by LocalGod79** [comment]
why exactly do captains that already have Aeries, Bactrians and Mules (with fighters!) need the player to escort them?

i'd say stick to mostly/completely helpless freighters, so that the fleet the player is supposed to be escorting doesn't do all the work for them...

there doesn't need to be a *ton* of variation - there were only two kinds of ships in those missions before - keep it simple, and just make the existing content more 'colourful'.

**Comment by psychiclegume** [comment]
[fleets.txt](https://github.com/endless-sky/endless-sky/files/216230/fleets.txt)
[jobs.txt](https://github.com/endless-sky/endless-sky/files/216231/jobs.txt)
Wrote up one mission . . . It will let me accept the mission and will give me 60 k when I arrive, but it will not have any ship.
any ideas?

**Comment by psychiclegume** [comment]
oops

**Comment by psychiclegume** [comment]
That was for a massive fleet out of the deep that would have several large pirate fleets waiting for them . . . more than they could fight off. I was going to have the reputation needed be high enought that the player had likely completed the Free Worlds plot and had several heavy warships.

**Comment by LocalGod79** [comment]
look at how the pirate fleet is called, and call the merchant fleet the same way.

**Comment by psychiclegume** [comment]
ok I'll try that

**Comment by psychiclegume** [comment]
[jobs.txt](https://github.com/endless-sky/endless-sky/files/216317/jobs.txt)
This seems to work . . . Only problem is that the ships do not come up on your escort list like a regular escort. Is this a feature limited to base game escorts?
![20160412203332_1](https://cloud.githubusercontent.com/assets/16767844/14481251/612caadc-00ee-11e6-8b77-a155a83746b6.jpg)
![20160412203957_1](https://cloud.githubusercontent.com/assets/16767844/14481302/cd9b9476-00ee-11e6-8ffa-e2fc2a018eaa.jpg)
The Queen Caroline is the first mission ship, but none of them appear in the bottom left with other escorts.

**Comment by LocalGod79** [comment]
hmmm...try setting the government to "escort"

**Comment by psychiclegume** [comment]
I'll giver that a shot

**Comment by psychiclegume** [comment]
Tried setting the government to "Escort."
Set the merchants to Free Worlds colors. VERY confusing. I'm going to look at the base game missions to see if there is any difference.

**Comment by endless-sky** [comment]
If you give a ship the "escort" personality flag, it will be displayed in your escort icons regardless of what its government is. That's generally a better option than assigning it to the player's government ("Escort").

**Comment by psychiclegume** [comment]
Didn't even think to add it to personality. I guess I will give it a try.

**Comment by psychiclegume** [comment]
I think that It already has the escort personality tag. Could you look over the mission [jobs.txt](https://github.com/endless-sky/endless-sky/files/216317/jobs.txt) and see if I left anything out that would do this?

**Comment by Amazinite** [comment]
@Pointedstick redid the escort jobs in #1777 a while back, which included having a variation in the ship that you escort. Is that good or is something else desired to spice escort jobs up more?

**Comment by Pointedstick** [comment]
I'm planing on adding even more escorted ship diversity, but yes, this issue can probably be closed.
