### ISSUE TITLE
Some R.N.S. hails are missing a space

### ISSUE THREAD

**Issue by backwardsEric** [endless-sky/endless-sky#9401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In 0.10.2 on macOS, I occasionally see hails from R.N.S. ships like this, "Thank the Republic forthree hundred years ...", which omit the space between "for" and "three".  From a quick glance at data/human/hails.txt it was not clear if it was an issue with line 2412 in that file or the code that assembles the phrases from data/human/hails.txt.

### Steps to Reproduce

1. Go to a system where Republic navy ships commonly enter and leave the system.
2. Look at their hails.

### Expected Behavior

There is a space between "for" and "three" in that hail when one of the "providing ...", "ensuring ...", or "giving ..." phrases is not used.

### Screenshots

<img width="1248" alt="forthree" src="https://github.com/endless-sky/endless-sky/assets/55062581/e082514b-0625-41e3-8d8e-68456eaddb3a">

The hail in question is the one from R.N.S. Azufral which happened before the R.N.S. Colorado attempted a scan and my ships docked at a planet.

### Link to save file

[Niko Varnok.txt.zip](https://github.com/endless-sky/endless-sky/files/12785329/Niko.Varnok.txt.zip)

### Operating System

macOS 12.6.8

### Game Source

GitHub Releases

### Game Version

0.10.2

**Comment by lumbar527** [comment]
Already resolved: #8942, #8976

**Comment by quyykk** [comment]
Thanks lumbar. Fixed in the beta v0.10.3
