### ISSUE TITLE
New types of shields with animations.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#941]
How about we see different types of shields with animations for firing on them. I'd like see my shot's get sucked into a purple quarg shield or a light orange korath shield, etc.. Also, an extra layer shield bubble with it's own animation could be used for high tier ship shields (this would give an extra status circle around the player's ship compass thing) 

The game would draw a bubble around an existing sprite that would not apear on its outline, when the ship is fired upon the round shield would soak up the shots but would only animate when fired upon.

**Comment by endless-sky** [comment]
This sounds very similar to #876 - maybe post ideas there instead?
