### ISSUE TITLE
deadline and stopover

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#942]
Using `deadline` along with `stopover` will result in impossible missions, as it appears that `deadline` ignore any stopovers and just take the number of jumps starting point and the final destination...

I just added two `deadline` lines on the `"Provide security for pleasure cruise"` mission, and it broke

**Comment by endless-sky** [comment]
This is another aspect of #540, so the two will probably be fixed at the same time.

**Comment by endless-sky** [comment]
Closing this because it will be addressed as part of #540.
