### ISSUE TITLE
Bug Report/Enhancement: Map Searching Doesn't Always Output Desired System

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#943]
Example: Searching for Han will direct you to Al D**han**ab. It would appear that the search feature is searching all systems/planets in alphabetical order, then just outputting the first match. I haven't been able to make it output the Han system for me in any way. I'm sure that this would occur with searching for other systems that have names within names or the same first few letters. 

So a nice enhancement would be to have the game output and highlight all matches or to allow you to click through different matches instead of just outputting the first match, which is making it difficult to find certain systems if you don't already know exactly where it is.

**Comment by LocalGod79** [comment]
i think this might be why it's an undocumented feature - it's not complete.

@endless-sky 
if exact match (or only CASE mismatch): output that instead?

**Comment by endless-sky** [comment]
I've checked in a partial fix: b467a2e. That will make it so that if multiple strings match, it prefers the one that starts with the string you entered, rather than any strings that contain that text later on.
