### ISSUE TITLE
Clarifications for Linux build instructions

### ISSUE THREAD

**Issue by shitwolfymakes** [endless-sky/endless-sky#9450]
### Location

https://github.com/endless-sky/endless-sky/blob/master/docs/readme-cmake.md#linux

### Describe the issue

This issue is regarding compilation on Ubuntu 20.04.06 LTS

1) Ubuntu 20.04.06 LTS is sufficiently out of date, even with updates packages repositories enabled, that configuration with `-DES_USE_SYSTEM_LIBRARIES=OFF` is mandatory.

2) Project configuration fails due to silent dependency of `curl` as part of `vcpkg` configuration step

### Expected content

- [ ] A short note reminding the user to do this should be sufficient. 
- [ ] Add curl to the list of dependencies

**Comment by TomGoodIdea** [comment]
We could just list what versions of the dependencies we need, the user should figure out if their distro provides them.

**Comment by quyykk** [comment]
I decided to add a mention to use at least Ubuntu 22 instead. The list of dependencies (like curl) needed to build the libraries is pretty long, and it seems like it would be better to recommend people to update instead. Thoughts?

**Comment by shitwolfymakes** [comment]
Yeah I like that
