### ISSUE TITLE
Confusion with pierce mechanics

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#946]
So currently, the wiki states that pierce shield damage is equal to (1-pierce)x(Shield damage) while pierce hull damage is (pierce)x(Shield damage). Using these two equations ends up leading to strange situations like this. 

Shield damage 100
Hull damage 0
Pierce 1

1 pierce*100 shield damage=100 damage to the hull, which doesn't make all that much sense given that the weapon would normally do absolutely no hull damage without the pierce attribute. 

My confusion is in how this works logically. Why is it that shield damage is what is used to calculate the amount of damage done to the hull? Due to this, weapons can do more hull damage if the shields of a ship are active as opposed to if the shields are gone, and this doesn't make all that much sense.

To me, it would make more sense that the pierce hull damage is (pierce)x(hull damage), and not shield damage. If there is some sort of reasoning as to why pierce hull damage is (pierce)x(shield damage), then please enlighten me. 

This is how I thought piercing would work within the universe and why it would use base hull damage to calculate pierce hull damage:
The projectile is "piercing" through the shield and directly damaging the hull. The process of puncturing the shield removes some energy from the projectile, which causes it to do reduced damage, but once it punctures the shield then it would be as if the shield was not there in the first place and it is just hitting the hull at a lower energy level, hence using base hull damage to calculate the pierce hull damage.

**Comment by endless-sky** [comment]
Sorry, that's a typo. Hull damage should be listed as `piercing * hull damage`, not `piercing * shield damage`. I've updated the wiki page.

**Comment by Amazinite** [comment]
Thanks so much, because the steam forums were on fire for a bit.
