### ISSUE TITLE
Cooling while overheated is unbalanced: some things are buffed a lot, others are nerfed a lot, and flamethrowers are still really powerful

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#9470]
### Problem Description

I don't think the changes made to overheating, or rather, being overheated, in #8968 are positive.
Quoting from the description of that PR:
> This makes it much harder to keep a ship overheated, so is ultimately a nerf to heat damage, and thus a step in the right direction to fix https://github.com/endless-sky/endless-sky/issues/5976. Unlike the nerf to heat damage in https://github.com/endless-sky/endless-sky/pull/7042, this does not alter the behaviour of overheating in itself, it just makes it harder to consistently maintain a ship in an overheated state.
> Also, cooling switching off when your ship is overheated really just didn't make sense.

While it may "make sense" for cooling to continue to be enabled, I don't think it works very well in practice.

Many of the complaints about heat damage are that it is not particularly difficult to completely shut down a ship and keep it shut down, especially with Flamethrowers. In fact, Flamethrowers are the main source of contention. This can be seen echoed in the linked issues and PRs. Other weapons that do heat damage are generally considered reasonable. The recent changes, however, affect the performance of all weapons that deal heat damage, making them all much less effective, at least against ships with large amounts of cooling. Perhaps the most obvious examples of this are the Kar Ik Vot 349 and Met Par Tek 53.
In the case of a stock 349, the amount of heat damage required to keep it overheated has more than tripled. For context, previously, five Dual Sunbeam Turrets were necessary apply enough heat damage to keep it overheated with its shields down (with 9-10 necessary to achieve this while its shields are still up), or a single Flamethrower (or two, while its shields are up.)
With its cooling, approximately 15 Dual Sunbeam Turrets are necessary to keep it overheated with now shields. Or, a grand total of 3 Flamethrowers.
Five Dual Sunbeam Turrets was already not a trivial weapon configuration to bring to a fight with a 349, being able to just barely keep it overheated *after* getting through its shields is, I think, not unreasonable in that case.
I think the 15 necessary now are a ridiculous requirement, especially when it is intended that Sunbeams should effectively overheat these ships once their shields are depleted.
The 3 Flamethrowers necessary to keep it overheated now, on the other hand, doesn't seem that difficult to bring. Six may be a bit more complicated, but, I think, still fairly doable. Most ships can still be overheated with their shields up by only 4 Flamethrowers. The 349 is an extreme example, but a particularly relevant one for some of the content in the game.
A Heliarch Punisher, as an example of a high performance ship that it has been mentioned can be "cheesed" with Flamethrowers only requires marginally more than 2 Flamethrowers to keep it overheated with its shields up. Not much of a nerf to Flamethrowers.
Most ships aren't even affected this much because they use even less cooling.

The changes are particularly visible when fighting the Kor Sestor ships, during various Wanderer missions, where it is now nigh impossible to complete the battle in fairly reasonable ships that were previously able to complete them just fine. For example, defending Desi Seledrak. You can have a go for yourself using this save file:
[warp core~~previous-35.txt](https://github.com/endless-sky/endless-sky/files/12922716/warp.core.previous-35.txt)
With this change, I cannot win this battle, without it, the same tactics can achieve a quick victory.

Another point is that some ships, such as the aforementioned 349 and 53, will overheat on their own while operating at full capacity (or, for the 53, from just its weapons). This seems to be an intentional design choice. They are extremely powerful sihps, especially the 53, which is capable of dealing similar levels of damage to the much larger 349. The fact that they will eventually overheat themselves and need to cooldown before re-engaging, even if you do not apply any heat or burn damage, is a deliberate aspect of their design. This change means that their cooldown period is now less than a third of what it previously was. This is a significant buff, I think, an inappropriate one, given that there doesn't seem have been a belief that these ships were too weak because of their tendency to overheat and the time it takes them to recover. In fact, most people seem to consider fighting these ships in the Wanderer story too difficult.

I will note that Plasma Turrets deal more heat damage out of less space than DSTs, but it's not a whole lot more. You'd still need about 10 Plasma Turrets to do as much heat damage as 15 DSTs, which is certainly a much lower requirement, but it is still a lot, and those Plasma Turrets do much less shield damage than DSTs.

Overall, this change doesn't really address the issue of Flamethrowers being extremely powerful, they still are, but, against some ships, other weapons that already were not considered problematic have been nerfed significantly. Additionally, ships such as the 349 and 53, and many Korath Exile ships, have been buffed a lot more than other ships, while not really needing to be, making missions that were generally considered on the more difficult side already even more difficult.

### Related Issue Links

Some recent PRs:
#7042 - An attempt to make heat damage less powerful (that didn't work out and was later reverted in #7776) by making being overheated only disable energy generation and heat generation, instead temporarily disabling the ship entirely until it cools down enough.
#7606 - A nerf to the flamethrower.
#8968 - The most recent change: cooling and active cooling still operate while a ship is overheated. What this issue is about.
Older issues:
#625 - A suggestion that the flamethrower should have more firing heat.
#5976 - A long discussion about the problems with heat damage and some ideas on how to improve hte situation.
#5982 - A proposed halving of heat damage for all weapons, with the Flamethrower's heat damage being quartered, which was closed with the following reason:
> Closing because I don't think this is the way to go on heat damage. At the very least, the Wanderer and Korath weapons don't need their heat damage addressed. Even the plasma cannons aren't too bad, as it's mainly the flamethrower that's the issue.
Which I think is a particularly relevant comment.

### Desired Solution

I think the changes from #8968 should be reverted. Heat damage on most weapons isn't actually overpowered, the weapons where it is considered overpowered should be changed, rather than buffing cooling and active cooling as has been done.

### Alternative Approaches

- Buff all the previously reasonable heat damage weapons so they are not left so ridiculously far behind. While this would make them perform more reasonably against some ships, they would become overpowered against many others, so not a great approach.
- Nerf the ships that have received excessive buffs. Given that these ships were not really a problem before, and worked well within their ecosystems, far away from the Flamethrower, I don't think this is a very good option, either.

**Comment by EjoThims** [comment]
Also related alternative: https://github.com/endless-sky/endless-sky/issues/7783
