### ISSUE TITLE
Shortcuts on trading menu in planet window

### ISSUE THREAD

**Issue by ethanskemp** [endless-sky/endless-sky#9473]
### Problem Description

The shortcuts in this game are on the whole quite good, however a missing one that frustrates me are "Buy All" and "Sell All" from the "Trading" menu in the planet screen. Everything else can be navigated from the keyboard, but not that. It doesn't necessarily need to be in shortcuts menu, similar to how "Trading" or "Job Board" are not for example, but just adding the shortcut and underlining a letter to let us know would be perfect. 

This addition seems feasible because "Hire Crew" 's "Fire" and "Hire", and "Bank" 's "Pay All" button all have shortcuts and appear in the same place on the screen, even though those would probably be less used shortcuts (based on my experience).

Screen shots attached. Running full vanilla, steam version, 0.10.2

![image](https://github.com/endless-sky/endless-sky/assets/25338564/5d8fb439-cafb-4369-b31b-57ecebc910cb)
![image](https://github.com/endless-sky/endless-sky/assets/25338564/12c7ac16-66b9-45a4-b16e-756f57f3b60c)

### Related Issue Links

N/A

### Desired Solution

A shortcut and underline added to the "Trading" menu for "Buy All" and "Sell All" buttons.
![image](https://github.com/endless-sky/endless-sky/assets/25338564/1b275265-c671-4e4f-907c-a3d9d5a2855e)

### Alternative Approaches

N/A

**Comment by TomGoodIdea** [comment]
Actually, these buttons have keyboard shortcuts: <kbd>Shift</kbd> <kbd>B</kbd> for "Buy All" and <kbd>Shift</kbd> <kbd>S</kbd> for "Sell All" / "Sell outfits". We could show the underlines when Shift is held if that would help, or change the shortcuts not to require Shift (but we can't use B[ank] and S[hipyard]).

**Comment by ethanskemp** [comment]
Hmm, did not know about the Shift hotkeys. Not sure how that would be shown to the user either. 

I don't randomly press and hold Shift, Ctrl, Alt, etc and check buttons to see their impact on otherwise unlabeled buttons. I only do those for bulk buying/selling, which Shift already has a function on that screen for the commodity buy/sell buttons, so I feel like the Shift-Key shortcuts are unnecessarily opaque.

Maybe "u" and "e" could be mapped instead? It's the second letter of each and doesn't appear to have any conflicts, and would allow underlining to show which keys to hit.
