### ISSUE TITLE
Difficulty setting for earning money

### ISSUE THREAD

**Issue by MedysMKA** [endless-sky/endless-sky#9478]
### Problem Description

I enjoy stories in Endless Sky a lot, but I do not have a lot of time to play and would like to spend less time grinding for money and worrying about my expenses.

### Related Issue Links

Could not find.

### Desired Solution

Add a difficulty setting in form of a multiplier for how much money is paid for:
- Trading
- Jobs
- Missions
- Mining
- Tribute

### Alternative Approaches

I think this would be quite a simple and semi-balanced way to reduce grinding.

**Comment by MedysMKA** [comment]
Oh, and I'd be happy to work on developing it, I would need a quick intro into what is where in the code though. My coding skills are quite low :)

**Comment by lumbar527** [comment]
#1386
#362
#9346
#7079 - This seems to be basically what you're asking

**Comment by MedysMKA** [comment]
Damn.. I've scroled through 15 pages of open issues and 5 of closed and did not find the #7079 ...
Well this can be closed a duplicate then..

**Comment by Hecter94** [comment]
Duplicate
