### ISSUE TITLE
Suggestion: Add request to check for duplicates to documentation issue templates

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#9479]
### Location

documentation/feature request issue template

### Describe the issue

I noticed after another duplicate was posted that the template for feature requests and documentation issues doesn't ask to check for duplicates. This is unlike the bug report template, which does ask to check for duplicates. As a result, newcomers to bug reporting may not know to check for duplicates, leading to potentially many feature requests and/or documentation issues that are duplicates of each other.

(I checked for duplicates of this issue myself)

EDIT: It looks like the feature request template does ask to check for duplicates. It doesn't make this a checkbox which means people (like me apparently) may skip over it. At the same time, I have seen people post duplicates anyways even with a checkbox in other repos, so this may not be necessary. The documentation issue template should still be updated, though.

### Expected content

I think that the templates for ~~feature request and~~ documentation issues should ask to check for duplicates, just like the bug report ones.

EDIT: I noticed that the CONTRIBUTING.md file asks to check for duplicates for issues. However, the readme file that  everyone would see seems to imply that this is for developers, and people may not think that posting a feature request or documentation issue makes them a developer. Otherwise, this file is hidden in the "docs" folder and its name also doesn't suggest that it should be read by those posting feature requests/documentation issues. An alternative approach is to therefore update the readme file to suggest that people posting to issues should also read the CONTRIBUTING.md file.

**Comment by Hecter94** [comment]
The feature request template does ask that you check for duplicates:
![image](https://github.com/endless-sky/endless-sky/assets/15916854/e81b77d7-2153-4275-88cc-5fa3ebcb04f5)

It could probably be added to the documentation issue template though.

**Comment by ziproot** [comment]
Oh, right, I didn't notice that. Sorry. In that case I think it should also be made a checkbox as that ensures that it is actually read.
