### ISSUE TITLE
Menkent Cruiser Scanning not completing mission

### ISSUE THREAD

**Issue by whoisem** [endless-sky/endless-sky#9481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Free World Campaign, I get a mission on Glaze to scan the cruisers with similar outfits in Menkent system. Even if I scan all of them cruisers titled Mission Objective in Menkent, upon landing in Glaze it says that I have not scanned it as yet thus not able to complete the mission. It is happening to me for the first time in many times that I have played this game.

### Steps to Reproduce

1. Go to Menkent.
2. Scan cruiser ship
3. Go to Glaze

### Expected Behavior

Mission should have completed

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/58987212/c22f3e29-178d-492c-83dd-f5c1340250de)

![image](https://github.com/endless-sky/endless-sky/assets/58987212/557096de-1b4a-410d-866d-fed22052dda2)

### Link to save file

[em stars.txt](https://github.com/endless-sky/endless-sky/files/13051497/em.stars.txt)

### Operating System

Microsoft Windows 11 Pro - Version	10.0.22621 Build 22621

### Game Source

GitHub Releases

### Game Version

v0.10.3

**Comment by bene-dictator** [comment]
A dialog will pop up when you have scanned all the cruisers. There are often other cruisers you may have missed.

**Comment by whoisem** [comment]
Yes. The mission was completed once I scanned all the ships. But the mission description says "Scan any ships in the Menkent system that are equipped like the combat-ready Cruiser you scanned previously, then return to Glaze in the Aldhibain system." I suggest we change it from "any" to "all" to avoid this confusion.

![image](https://github.com/endless-sky/endless-sky/assets/58987212/981a4ec0-635b-441e-846d-d3acad5d0ba2)

**Comment by bene-dictator** [comment]
To be fair the cruisers that the FW want you to scan are marked "mission target", and there's only four of them.

**Comment by whoisem** [comment]
Well. If one looks at it that way. I must have gotten it right in my previous runs. I guess I am becoming lazier over time.

**Comment by bene-dictator** [comment]
No worries.
