### ISSUE TITLE
Fighters automatically get sold off even when left in an uninhabited system

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#950]
So I noticed something that could be considered a bug, not entirely sure. I was testing the new southern carrier and I deployed my 4 fighters in an uninhabited system, Mora. I then accidentally left them there and jumped to the next system, Delta Valorum, where I landed on Bounty. Upon leaving Bounty, the game informed me that I had nowhere to keep my fighters, and they were sold. 

Now, I'm assuming that the game makes a check whenever the player leaves any port, and fighters that isn't already in a bay are sold automatically, which is normally is fine because it can only happen at a port that has a shipyard. But when those fighters are already flying around an uninhabited system, and I leave even from a port that has no shipyard, I don't think it makes a whole lot of sense for them to be sold off. 

It's not a huge issue, but it is something that I think could be very frustrating for a player who wants to use fighters and is trying to make a go of it. Perhaps the check could only apply to the system the player is in?

**Comment by lehgogh** [comment]
This seems like it should be a dialog that _asks_ if the player wants to sell their deployed fighters, not force it upon them.

**Comment by jmhorjus** [comment]
And perhaps a warning sound effect for when you issue a jump command and still have deployed fighters.

**Comment by Alkallid** [comment]
The new red icon is for that;
Also, if you park fighters you buy, jump somewhere else, and unpark them, they disappear with no sell.

**Comment by endless-sky** [comment]
Fixed in 31c82bd.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
