### ISSUE TITLE
Wiki: Continuous weapons

### ISSUE THREAD

**Issue by SomeTroglodyte** [endless-sky/endless-sky#9536]
### Problem Description

[CreatingOutfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits) does not explain when a weapon is marked as continuous by the game and a few related tidbits

### Related Issue Links

Didn't find any (all 18 https://github.com/endless-sky/endless-sky/issues?q=is%3Aissue+wiki+continuous hits don't relate judged by title)

### Desired Solution

Amend entries for velocity, sprite, and I believe both lifetime and reload. Correct me if I'm wrong about the following - also not sure whether burst continuous can exist and how.
* A weapon with reload = 1 and lifetime = 1 is a continuous one
* Values < 1  for both are ignored / treated as 1
* A continuous weapon has a range equal to velocity
* A sprite for a continuous weapon must be exactly 2`*`velocity (4`*` for the `@2x` versions) pixels high (to look nice)

By the way, it's a bit curious that the `@2x` projectiles for the inferno exist, but not those for the blaze-pike. All of them are also suspiciously large files, simply re-exporting in gimp reduces size by factor ~5.

### Alternative Approaches

n/a

**Comment by OcelotWalrus** [comment]
Yes, this should definitely be on the wiki.
