### ISSUE TITLE
Allow player to toggle credits.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#954]
If I have a billion credits, sometimes I'd like the display to show 1000000000 instead of 1.B. Give players the option to see how much money they have exactly

**Comment by Gkramme** [comment]
The reason it shows that is because 1,000,000 would not fit in the box that displays credits.

**Comment by DingusShingleton** [comment]
If you want to know exactly how many credits you have, buy 50,000 laser rifles (hold shift+ctrl+alt at the same time and it's one click). This costs 400,000,000 credits. Then you will see the exact number and can just add 400,000,000 back to that to get your total. Or if 400mil isn't however much you need. The principle is what matters.
