### ISSUE TITLE
Clink and Mutiny are missing location attributes

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#9565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clink does not have the "south" attribute, unlike most other planets in that area of space. Similarly, Mutiny does not have the "core" attribute. Neither of these planets are uninhabited.

### Steps to Reproduce

1. Go to a folder with an endless sky binary
2. Run endless sky with the "matches" flag, passing in the following location filter:
```
location
    not attributes "south" "core" "dirt belt" "near earth" "north" "deep" "rim" "paradise" "uninhabited"
    government "Pirate" "Republic" "Syndicate"
```
3. See how "Clink" and "Mutiny" are printed out

### Expected Behavior

No planets are printed out when running the command, as they are have a location attribute or the "uninhabited" attribute.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/109186806/e6966aac-82bf-42e4-8a39-bbc08037d954)

### Link to save file

No save file is needed, as the "matches" flag ignores save files anyways.

### Operating System

Debian 12

### Game Source

GitHub Releases

### Game Version

v0.10.4

### Additional Information

There are numerous jobs and missions that rely on location attributes. Adding in location attributes to Clink and Mutiny may make them choose Mutiny or Clink as locations, which may not be wanted.

**Comment by bene-dictator** [comment]
I just realised it might be because they don't have spaceports? You might want to check Watcher as well.

**Comment by ziproot** [comment]
Watcher has the "dirt belt" attribute.

**Comment by bene-dictator** [comment]
Strange.
