### ISSUE TITLE
Not receiving credit for completing "Visit void sprite planets" mission

### ISSUE THREAD

**Issue by bMorgan01** [endless-sky/endless-sky#9567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have landed on both gas giants in Nenia with the Puffin. When I landed on the second one, I got a confirmation message with a bit of story and an ending that stated I should return to Aventine (the planet that gives the mission). When I returned to Aventine, I got a message that said I still needed to visit the gas giants and as such would not receive the award. I then returned, landed on the planets again, went back to Aventine, same result. I've reloaded saves from when I landed on Slylandro, no luck.

### Steps to Reproduce

1. Unlock and accept "Visit void sprite planets" mission from Aventine in the Pantica system.
2. Switch flagship to Puffin.
3. Jump to Nenia
4. Get killed by Archon several times, repeat 3 and 4
5. Land on Slylandro
6. Take off from Slylandro
7. Get killed by Archon several times, repeat 6 and 7
8. Land on Nasqueron.
9. See confirmation and lore message
10. Take off from Nasqueron.
11. Get killed by Archon several times, repeat 9 and 10
12. Jump back to Pantica
13. Land on Aventine
14. See message stating that the mission has not been completed.

### Expected Behavior

I get credit for completing the mission.

### Screenshots

I can't replicate the confirmation again, even after reloading older saves

### Link to save file

[Ben Morgan.txt](https://github.com/endless-sky/endless-sky/files/13446084/Ben.Morgan.txt)

### Operating System

Win 10

### Game Source

Steam

### Game Version

See below

### Additional Information

Game version: ![image](https://github.com/endless-sky/endless-sky/assets/27574085/b555b7ab-da0c-442f-ae22-3fcb796c8e90)

**Comment by warp-core** [comment]
You have cargo from that mission (scanning equipment) in one of your escorts (the Shield Beetle named "Mon Oo") which you will need with you at the destination (Aventine) in order to complete the mission.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/blob/9d8dfc4fcb27b90f5eee55b4be1d52359b2a7c95/data/remnant/remnant%201%20introduction.txt#L722-L723
The mission should be using `"generic missing stopover or cargo"`.
