### ISSUE TITLE
No information on "ignore clearance"

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#9577]
### Location

wiki

### Describe the issue

The missions wiki page doesn't have any mention on the "ignore clearance" flag, which allows a mission to have a destination that the player normally wouldn't be allowed to land on without a bribe.

### Expected content

The missions wiki page describes the "ignore clearance" flag.

**Comment by OcelotWalrus** [comment]
true.

**Comment by warp-core** [comment]
Done https://github.com/endless-sky/endless-sky/wiki/CreatingMissions/b3ee37062fd9496efa12a13c263a96aba768ace1
