### ISSUE TITLE
Bug: Fighters in external bays continue to render thruster flares

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#958]
...if they were firing their engines when they entered the bay.

**Comment by endless-sky** [comment]
Should be fixed in e4f852f.

**Comment by LocalGod79** [comment]
the effect was kinda neat - it looked like the fighters were trying to help the carrier go faster, but alas - still looks and moves like a caterpillar...

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
