### ISSUE TITLE
fleet jump dosen't work on free worlds missions

### ISSUE THREAD

**Issue by eatsomedust4** [endless-sky/endless-sky#9580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

basicly I press shift then j and then its about to work but then the fleet turns suddenly then i wrap into a margor battle without the escorts and die in 5 seconds I have spent 5hours alone constently retrying a mission but only to load a save because they didn't fleet jump PLS FIX THIS ITS THE MOST ANOYING THING!!!!!!!!!!!!!!!!!!!!!!!!!

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

fleet jump as it sounds is suppost to be a fleet jump

### Screenshots

.

### Operating System

windows 11

### Game Source

Steam

### Game Version

latest

### Additional Information

.

**Comment by eatsomedust4** [comment]
to reporduce the error you have to try to fleet jump to a magor battle

**Comment by Koranir** [comment]
Uh... To fleet jump, you hold 'J' until all your escorts are pointing in the same direction, then release and everybody will jump at the same time.

**Comment by Amazinite** [comment]
Shift+J only works on the escorts you won. Mission escorts don't apply. For mission escorts, you still need to hold J.

**Comment by eatsomedust4** [comment]
thanks
