### ISSUE TITLE
Mission "npc disable" tag not working

### ISSUE THREAD

**Issue by ItsNickBarry** [endless-sky/endless-sky#959]
As demonstrated in #953, a mission with the "npc disable" tag is not able to be completed.

In the case of #953, there are no such problems when using the "npc kill" or "npc board" tag.  I am alsu unable to complete "FW Flamethrower 2" and "Kestrel Testing" on an old save file.

**Comment by LocalGod79** [comment]
could this be related to #797 ?

**Comment by endless-sky** [comment]
Looks like my optimization of the IsDisabled() check messed that up. Commit 2307fcd should fix it.
