### ISSUE TITLE
Geminus Spaceport 

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#960]
After completing the main campaign, the Geminus Spaceport description still implies that there is an ongoing investigation trying to find out who nuked the place, despite it being over.

> The Navy Officers who are in charge here have no time for anyone who is not enlisted in the Navy and participating in the ongoing investigation.

**Comment by LocalGod79** [comment]
#634

**Comment by Amazinite** [comment]
Aight.

**Comment by Amazinite** [comment]
It's not an exact duplicate, as I'm mentioning how it talks about the investigation while he's talking about the destroyed shipyard. But I guess they would both by fixed at the same time anyways.
