### ISSUE TITLE
Punctuation error during pilot creation conversation.

### ISSUE THREAD

**Issue by Durzai** [endless-sky/endless-sky#9605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a minor punctuation error in start.txt on line 38, a comma is used at the end of the dialogue instead of a period.

"Sign here. Now here,"

### Steps to Reproduce

1. Reference the github repository, your own local game files, or start a new pilot save file and read the conversation.

### Expected Behavior

I expected there to be a period at the end of that dialogue.

### Screenshots

![IntroTypo1](https://github.com/endless-sky/endless-sky/assets/105894839/983f0600-4161-4167-b480-8fc9f3724179)

### Operating System

Windows 10

### Game Source

GitHub Releases

### Game Version

v0.10.4

**Comment by Hurleveur** [comment]
I think thats intentional and smth you can find in other places of the game too

**Comment by OcelotWalrus** [comment]
Well I think it should be replace by a period. You can't end a dialog with a comma. That's just grammatically false.

**Comment by Amazinite** [comment]
The common grammatical convention is that if a quotation ends in a period but the sentence continues after the quotation, the period becomes a comma. You can find hundreds of examples of this across the game.
