### ISSUE TITLE
Jumpdrive and Hyperdrive share the jump speed attribute 

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#961]
Jump speed is cumulative (i think). A ship equipped with 3 jumpdrives and 1 hyperdrive can use the hyperdrive at a higher speed than a ship with one of each. I think that it is the `jump speed` attribute that makes this happen.

**Comment by Wrzlprnft** [comment]
Related to #683

**Comment by jafdy** [comment]
Didn't spot that. Its the fact they stack with each other that strikes me as odd.

**Comment by Wrzlprnft** [comment]
That's why it is no real duplicate: The other thread was about if and how (with which maths behind it) they stack, with being resolved as they stack as they are supposed to. Your position is not, why they stack, but why jumpdrives and hyperdrives not stack on their own, as opposite as together, if i got it right.

**Comment by jafdy** [comment]
That's about it.

**Comment by Wrzlprnft** [comment]
how about the scramdrive?

**Comment by jafdy** [comment]
No that has `scram drive` with a similer effect (any velocity along jump vector, limited velocity along other vectors).

**Comment by Wrzlprnft** [comment]
Yeah, but i wanted to know your opinion if the scramdrive should stack with the hyperdrive, but the jumpdrive not with the other two, since the topic is more about which kinds of drive should stack.

**Comment by jafdy** [comment]
Why ask such a hard question.

No, the hyperdrive wouldn't normally work at nearly the same speed as a scramdrive, therefor they work in a slightly different way and the gravitational waves would act in less predictable way so would be more dangerous.
