### ISSUE TITLE
Next mission stage does not start - "Travel to the designated system"

### ISSUE THREAD

**Issue by Ninetailed** [endless-sky/endless-sky#9611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After picking up the alien (Gegno?) from the Nssryos system and transporting them to Dueyu Eitch, was directed to the Aleit system. Landing on the highlighted segment of Giaru Gegno causes the mission ("Travel to the designated system as instructed") to silently end. There is no text shown on landing besides the usual planet interface, and no further mission development occurs.

This is my first playthrough, so I'm not sure what further context information affects this mission.

### Steps to Reproduce

1. Load attached save file
2. Travel to Aleit
3. Land on highlighted Giaru Gegno

### Expected Behavior

Next mission section should begin.

### Link to save file

[Asdif Jekel~3018-07-03.txt](https://github.com/endless-sky/endless-sky/files/13692810/Asdif.Jekel.3018-07-03.txt)

### Operating System

Windows 10 Home 10.0.19045 Build 19045

### Game Source

Steam

### Game Version

v0.10.4

**Comment by Saugia** [comment]
Sorry for not seeing this sooner. The reason the mission silently ends is because in order to continue the Quarg route of the story, you needed to have already met the Quarg in human space. If you skipped right past other content to go straight to the new stuff then this is what happens as most players run into the Quarg before then.

I'll do a workaround on it soon.

**Comment by Ninetailed** [comment]
Thanks for the workaround! I had no concept of what was "the new stuff", I just went exploring beyond inhabited space because it was there.

**Comment by Amazinite** [comment]
Addressed by https://github.com/endless-sky/endless-sky/pull/9684.
