### ISSUE TITLE
Map detail panel clips government name

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#9615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The map detail panel can clip the names of long (vanilla) governments, such as `Hai (Unfettered)`.

### Steps to Reproduce

1. Get the map to display government names
2. Look at the display

### Expected Behavior

Government names should not be clipped; maybe the panel could be dynamically sized or something?

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/68112292/ed38fe8b-b0d4-481b-824a-a991dcaacaf0)

### Operating System

EndeavourOS (kernel: 6.6.7-zen1-1-zen)

### Game Source

Built from source

### Game Version

3eebb2c2c9e886ecc124dc38794ff067fbac279f

**Comment by Hurleveur** [comment]
Maybe we could move it a bit to the left so that government displays properly, and then follow the same ... logic of the ship select panels?
