### ISSUE TITLE
How can I translate the game into other languages?

### ISSUE THREAD

**Issue by ketronix-dev** [endless-sky/endless-sky#9626]
### Problem Description

I, like many other people, want to play the game in my native language, but we don't have the opportunity yet. I have done professional translation of 0 A.D., and I want to translate your game.

### Related Issue Links

I have no links

### Desired Solution

I can translate your game into Ukrainian.

### Alternative Approaches

You can provide an example of how to edit an English localization.

**Comment by Zitchas** [comment]
Yes, you can. Unfortunately we don't have a localisation file, so translating is a matter of going through the data files and translating all the player-visible text. Doing all the missions and story and descriptions should be quite easy. A bit harder doing UI and info panels.

**Comment by danaris** [comment]
Also worth noting is that a) the only simple way to provide this will be in a plugin, and b) this will mean that those files will need to be manually kept up to date with the vanilla files as those change.

**Comment by MCOfficer** [comment]
Support for translations is being tracked in #558 , we can track individual languages once we know how we'll go at it.

**Comment by ThundySGI** [comment]
look at my post
https://github.com/endless-sky/endless-sky/issues/558#issuecomment-3640843414
