### ISSUE TITLE
Nita is introduced twice

### ISSUE THREAD

**Issue by Zeadrasil** [endless-sky/endless-sky#9630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was ferrying shipments through human space, and I noticed that Nita appears to be introduced twice here. I believe that it is either two alternate paths or events that are supposed to happen at different times that are being combined into one.

### Steps to Reproduce

1. Complete the mission where you ferry Tom to his fiance
2. Come back later to the planet you dropped him off at and leave
3. Come back again later

### Expected Behavior

It appears as if two different introductions for Nita are smushed into each other, and I am not sure which but one of them should be the only introduction.

### Screenshots

<img width="377" alt="image" src="https://github.com/endless-sky/endless-sky/assets/73188667/b293042d-443a-43b5-a880-c85b9aa09c4f">

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.10.4

**Comment by bene-dictator** [comment]
Thank you for your bug report! This issue has been fixed in the latest nightly version in PR #9516, but we still appreciate every report. We will leave this issue open until the bugfix is in the next Steam release.
