### ISSUE TITLE
Typo in MapData Wiki Page

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#9635]
### Location

Development Wiki

### Describe the issue

There's a line in https://github.com/endless-sky/endless-sky/wiki/MapData#planets that reads:
```The description text of a port behaves the same way as the text following a "spacpeort" node, and is the text that appears when you click the port button.```

The word "spacpeort" is a typo, I presume.

### Expected content

```
The description text of a port behaves the same way as the text following a "spaceport" node, and is the text that appears when you click the port button.
```

(instead of spacpeort)

**Comment by Amazinite** [comment]
Fixed. Thanks for the report.
