### ISSUE TITLE
Multiple weapons nodes on a single outfit

### ISSUE THREAD

**Issue by Azure3141** [endless-sky/endless-sky#9640]
### Problem Description

Currently, a weapons outfit can only have a single weapon node. This essentially means the outfit can only have one behavior, which limits potential weapon options.

If you could define multiple weapon nodes for a single outfit, it would open up uses such as turrets that can both act as weapons and as antimissiles, or tractor beams that use the new tractor beam mechanic as well as being able to attract other ships. You could even create missile launcher outfits capable of using multiple types of missiles, allowing players to use more specialized missiles without needing several different outfits.

### Related Issue Links

N/A

### Desired Solution

Allow outfits to define multiple weapon nodes.

### Alternative Approaches

You can make really janky weapons that use fractional gun ports for example, but they don't work properly. I guess this could be fixed if we wanted to go with this route, but it would end up being much messier than the above solution.

**Comment by bene-dictator** [comment]
SMH didn't check related issues. Exterminate.

#7408
