### ISSUE TITLE
Shader Compilation Failed Error

### ISSUE THREAD

**Issue by xX-Dillinger-Xx** [endless-sky/endless-sky#9648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After a recent "continuous" update, I receive a "shader compilation error" as soon as I open the game. I can still play 0.10.4 Stable without any issues. This started about 1 week ago and I just updated "continuous" today. Here is a the relevant clip from the error log. 

#version 330
// fragment blit shader
precision mediump float;
precision mediump sampler2D;
uniform sampler2D tex;
uniform vec4 fade;
in vec2 tpos;
in vec2 vpos;
out vec4 finalColor;
void main() {
  float epsilon = .001;  float weightTop = clamp((vpos.y + epsilon) / (fade[0] + epsilon), 0.0, 1.0);
  float weightBottom = clamp(((1.0 - vpos.y) + epsilon) / (fade[1] + epsilon), 0.0, 1.0);
  float weightLeft = clamp((vpos.x + epsilon) / (fade[2] + epsilon), 0.0, 1.0);
  float weightRight = clamp(((1.0 - vpos.x) + epsilon) / (fade[3] + epsilon), 0.0, 1.0);
  float weight = min(min(min(weightTop, weightBottom), weightLeft), weightRight);
  if(tpos.x > 0.0 && tpos.y > 0.0 &&
      tpos.x < 1.0 && tpos.y < 1.0 )
    finalColor = texture(tex, tpos) * weight;
  else
    discard;
}
Fragment shader failed to compile with the following errors:
ERROR: 0:4: error(#228) Type should be float or int
ERROR: error(#273) 1 compilation errors.  No code generated

Shader compilation failed.

### Steps to Reproduce

Launch the game using ESLauncher

### Expected Behavior

I expected the game to launch

### Operating System

Windows 10 Pro, 10.0.19045 Build 19045

### Game Source

ESLauncher2

### Game Version

 continuous and 10.4 Stable

**Comment by xX-Dillinger-Xx** [comment]
Any ideas? 10.4 still works, but  10.5 does not. I'm concerned the error will end up in 10.4, so I'm not going to update. 
It appears to be something to do with using "precision mediump sampler2D;" in version 3.3. This is only allowed in 4.0 and up.  Beyond that, I do not know enough about Opengl to fix it myself.

**Comment by Amazinite** [comment]
@thewierdnut This is your code. Could you give it a look? We do still only require OpenGL 3/recommend OpenGL 3.3, so if there's some method of doing the same thing in that version then we should do that instead of needing to raise the minimum specs.

**Comment by thewierdnut** [comment]
@xX-Dillinger-Xx What graphics chipset/driver do you have?

**Comment by bene-dictator** [comment]
In addition, could you use ESLauncher2 to download the PR 9667 and test whether that PR fixes your error?

**Comment by xX-Dillinger-Xx** [comment]
@thewierdnut https://gpuz.techpowerup.com/24/01/15/wye.png  It's an older card but still does what I want, most of time. LOL
@bene-dictator I will give that a try and let you know.

**Comment by xX-Dillinger-Xx** [comment]
Looks like you guys solved it, and I learned a little in the process. Thanks.

**Comment by Amazinite** [comment]
Thanks for the report. :+1:
