### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#965]
Elek Kartanu description (line 16475): 'recent **past**' not 'recent _path_'
Firka Tesk description (line 16589): if the crust cracked you would expect cliffs or mountains with a 90 degree point. could expand.
Karek Fornati spaceport (line 17052): 'trees that look like pines' not 'pine trees' . its unlikely that the Korath have the same pine trees as Earth.

**Comment by endless-sky** [comment]
In my opinion, once we start discovering life on other Earth-like planets, we'll probably use Earth names for things: we'll call things that look like pine trees, pine trees, etc. It's the same as how we use the term "eye" for human eyes and squid eyes even though they were shaped by different evolutionary processes.

If I said that the forests were Douglas firs or ponderosa pines, specifically, that would certainly not make sense though.

**Comment by endless-sky** [comment]
Looks like the Elek Kartanu typo was already fixed.

**Comment by jafdy** [comment]
Fair enough. Closing
