### ISSUE TITLE
Fleet able to get help from aliens

### ISSUE THREAD

**Issue by Bulinus** [endless-sky/endless-sky#9679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When traveling around with my fleet I have noticed that when I am in a system with alien ships that I am not able to communicate with, my escorts seem to be able to get refueled by them but I cannot.  It appears that even though when I try to talk to them I get the message that I don't understand the language and cannot ask for help but the rest of my fleet of ships is able to ask for help and get fuel.

### Steps to Reproduce

1. Go to Mego Seo in Bunrodea space and run yourself out of fuel
2. Click on any Bunrodea ship
3. hit T to talk to them
4. Observe you can't ask for help
5. Observe your fleet does end up getting fuel from them somehow.

### Expected Behavior

  If you cannot understand the alien ship and thus cannot ask for help your fleet should not get help from the alien ships either as they also do not speed the language.

### Operating System

Windows 10 Pro

### Game Source

Steam

### Game Version

0.10.4

**Comment by TomGoodIdea** [comment]
#1153

**Comment by Bulinus** [comment]
Not sure how I missed that.  I searched for a good 15 minutes trying different terms to find a similar issue.  It is very similar but specific to the wanderers.  You could close this as a duplicate if you want I suppose though in this case there are other aliens aside from the wanders that seem to exabit this behavior too.  I understand the comment that it is an anti-frustration behavior but personally I think it would be better if the behavior of aliens was consistent between the player and escorts when it comes to refueling.  The ships won't be stranded as long as they have a ramscope.
