### ISSUE TITLE
0.8.7 tag vs v0.x.y tags, exception naming convention vx.y.z, minor formal

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#968]
It is just a minor thing, but the git tag for 0.8.7 is missing the v in front of it.
Since the 0.8.1x are before the 0.8.x anyway, the list of tags is not in the right order, but the 0.8.7 escapes completely and flees on top.
![git tags](https://cloud.githubusercontent.com/assets/15857993/14594821/5354ba9e-053a-11e6-8411-d632a87dbeea.png)

**Comment by endless-sky** [comment]
I'm not sure what github would do with the release that's tied to that tag if I changed it. I worry that if I fixed it the simplest way (creating a new tag and linking it to that old release), github might suddenly push that release to the top of the "releases" list or something like that.

**Comment by Wrzlprnft** [comment]
So you could try it right before the 0.9.0 release, or -since it is not that important- take notice and let it be the way it is.
