### ISSUE TITLE
Scanning: The Incessant and Unending Nightmare

### ISSUE THREAD

**Issue by QuantumTux** [endless-sky/endless-sky#9706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is more a design problem rather than a coding bug; specifically, this problem diminishes playability and enjoyment.

My fleet (currently about 10 ships) is getting scanned incessantly; by the Hai, the Remnant and even the Republic Navy. They simply don't quit. Often before one NPC ship finishes scanning all of my ships, another NPC (from the same Faction) comes along and starts scanning them. In many cases, multiple ships are constantly scanning my ships. It literally never ends.

Aside from the constant noise of the scanning sound F/X, I've repeatedly lost Cargo that I dumped for one of my other ships to pick up; instead, one of the ships scanning grabs it.

This problem puts "Cap'n Pester" to shame. The scanning just keeps going and going and going and going and going and going and going......

### Steps to Reproduce

1. Have a fleet of ships (the more ships, the worse the nightmare)
2. Go visit: (a) the Hai in the vicinity of Allhome; or, (b) the Remnant in the vicinity of Vinmal; or, (c) almost any Republic system with a lot of Navy ships hanging around
3. Not have completed whatever Faction-specific gameplay is necessary to avoid all scanning
4. Loiter
5. Experience incessant and unending scanning
6. If you try to drop cargo to transfer to another ship in your fleet, expect that one of the scanning ships will snag some of it

### Expected Behavior

The scanning needs to end at some point. I'm not sure how to construct this within the ES code, but there needs to be a
cut-off point.

The only idea I have is that when an NPC ship scans a player ship in a star system, the NPC's Faction gains "Information Points". Once the Faction in question has gained X Information Points, they cease scanning. Jumping to a new star system zeros out the count for all Factions.

### Operating System

OpenSUSE LEAP 15.5

### Game Source

Other (please describe)

### Game Version

endless-sky RPM v0.10.4-lp155.26.1

### Additional Information

This isn't a discussion about how long it should take to scan, or are scans balanced with Interference Plating, or the effect of "ship density" or "cargo density" on how scanning works.

The problem here is about how much scanning goes on, and how it turns game play into an unpleasant and frustrating experience.

## Related Issues

[Issue #851](https://github.com/endless-sky/endless-sky/issues/851) - Scanning: Government Jurisdiction
[Issue #6947](https://github.com/endless-sky/endless-sky/issues/6947) - feat[content]: Remnant will now trust the player after a certain point
[Issue #7023](https://github.com/endless-sky/endless-sky/issues/7023) - Remnants faction never ending mistrust
[Issue #7640](https://github.com/endless-sky/endless-sky/issues/7640) - Scanners have been nerfed too much
[Issue #8447](https://github.com/endless-sky/endless-sky/issues/8447) - Only one scan attempt possible per ship

**Comment by Amazinite** [comment]
Something that's been noted in the past is that ships that scan other ships are supposed to not scan ships that have already been scanned by their government. That is, if a Navy ship scans you, another Navy ship shouldn't try to scan you as well.

Checking the code and testing in game, this is actually true... unless the ship has the surveillance personality. For ships with the surveillance personality, which some Navy, Hai, and Remnant ships have, they must *personally* scan a ship in order to not scan it again. This means that if you remain in systems where surveillance fleets can spawn, you will constantly be scanned as new surveillance ships spawn.

I'll be releasing a PR later to change this behavior, among a few other changes to how scanning ships behave (e.g. only scan so many ships and spend so much time scanning before deciding to do something else) that should resolve this and other NPC scan behavior issues.

**Comment by QuantumTux** [comment]
@Amazinite Thanks for tracking down the cause - I'll eagerly await the fix.

**Comment by QuantumTux** [comment]
Since a PR has been created I'll Close this Issue

**Comment by Amazinite** [comment]
That's not how it works.

**Comment by Amazinite** [comment]
#9714 limits surveillance fleets to scanning each ship once just like non-surveillance fleets.

**Comment by Joachim-Otahal** [comment]
I know I am posting on a old thread, but google search shows this in the first hits.
I don't care about the scanning per se, but as for 0.10.10 the constant beeping goes for over 5 minutes to 15 minutes each time I (re-)enter a remnant system with 46 ships.
Solution for me: Rename "\Endless Sky\sounds\scan~.wav" to "\Endless Sky\sounds\scan~_.wav"
Enjoy the sound of silent scanning.
