### ISSUE TITLE
No pirate Bacterians?

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#971]
It just occurred to me that I've never seen a pirate bacterian..There really should be a few scattered about.

**Comment by Wrzlprnft** [comment]
Given the point that they are qutie limited in the lore, i guess a pirate bactrian would be handled as number 1 priority insult to the deep and they try to get it back. Additionally, they awere not built as warships. But given their strength, you have a point there.

**Comment by mdsmestad** [comment]
Maybe there could be a couple of hero pirates with bacterians..Could be part of a pirate campaign

**Comment by jafdy** [comment]
You could also give them Beatles but more to the point there isn't a pirate campaign at the moment.

**Comment by Alkallid** [comment]
Why do you spell "Bacterians"? I've seen you do it multiple times.

**Comment by DingusShingleton** [comment]
I see people all over the internet write Bacterian

**Comment by LocalGod79** [comment]
i think "people" is "person" - i've only ever seen @mdsmestad make that spelling error (all over the internet).

**Comment by mdsmestad** [comment]
Ok fine so I've been spelling it wrong for ages now....for some reason Bacterian just sticks in my mind better than Bactrian. It sounds better to me too.

**Comment by toilethinges** [comment]
@mdsmestad - A Bactrian is a breed of critically endangered camel, which (although thought to be extinct in the wild) lived just to southwest of Mongolia.  Unlike other camels, it has two humps.

Just letting you know, the reason it's a Bactrian and not a Camel or some other such name. Bactrian sounds much cooler than "Camel," although Camel would fit with the appearance. Makes sense that the smaller variant of the Bactrian is called the Mule.

**Comment by mdsmestad** [comment]
@toilethinges Wow I had know idea that Bactrian was the name of a type of camel, though in retrospect that makes too much sense. As for pirate bactrians, I might do this in a mod. It would be fun to see some powerful pirate fleets that newb players would want to avoid.

**Comment by Disiuze** [comment]
@mdsmestad Force the player to be even more careful? I like that idea a lot!

**Comment by lehgogh** [comment]
Perhaps have it be dependent on both fleet size and combat rating? That would begin to balance giant fleets for "capture, sell, repeat" schemes, but give merchant fleets more of a break.

**Comment by DingusShingleton** [comment]
I mean a pirate storyline would be awesome, and it could involve all the politics between different pirate worlds, and really give them different flavors and whatnot. Give interference plating a chance to be an essential outfit. And then cap it off with a ridiculous pirate bactrian and co as the final boss.

**Comment by LocalGod79** [comment]
as a further side note on camels, the single hump variety is 'dromedary'

many moons ago, someone in the google forum mentioned starting a pirate storyline - i wonder how far they got...

**Comment by endless-sky** [comment]
> The domesticated Bactrian camel has served as a pack animal in inner Asia since ancient times. With its tolerance for cold, drought, and high altitudes, it enabled the travel of caravans on the Silk Road... As pack animals, these ungulates are virtually unsurpassed, able to carry 170–250 kg (370–550 lb) at a rate of 47 km (30 miles) per day, or 4 km/h (2 mph) over a period of four days.

(Wikipedia)

**Comment by endless-sky** [comment]
I've added them to appear occasionally in the North (a6ef4a2), but not in other parts of the galaxy (where Bactrians of any sort are extremely rare).
