### ISSUE TITLE
Various wiki issues

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#9719]
### Location

wiki

### Describe the issue

1. Wrong numbering in [CreatingShips](https://github.com/endless-sky/endless-sky/wiki/CreatingShips) - GitHub is smart enough to fix it on the frontend, but the numbers are wrong in the raw text.
2. [WritingConversations](https://github.com/endless-sky/endless-sky/wiki/WritingConversations#text) links to a missing https://github.com/endless-sky/endless-sky/wiki/PlayerConditions file.
3. The `Points and Boxes` link in [CreatingInterfaces](https://github.com/endless-sky/endless-sky/wiki/CreatingInterfaces) is broken
4. [CreatingMissions](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#conditions) links to a missing anchor in PlayerConditions: https://github.com/endless-sky/endless-sky/wiki/Player-Conditions#reserved-conditions
5. The `Planet and System Links` link in [LocationFilter](https://github.com/endless-sky/endless-sky/wiki/LocationFilters) is broken
6. Typos:
   - [CreatingGovernments](https://github.com/endless-sky/endless-sky/wiki/CreatingGovernments):
   > A change in the player's reputation with any of these 4 specified governments results in a equivalent change in the player's reputation with the "United Kingdom" government.
   
   Should be `an equivalent`
   > This example usage indicates the the government "Daelaam" will have scanning and fining authority for
   
   `the the` should be `the`
   - [CreatingOutfits](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits)
   > how many credits per day are gained from from this outfit
   
   `from from` should be `from`
   - [CreatingShips](https://github.com/endless-sky/endless-sky/wiki/CreatingShips)
   > the swizzle value that this ship uses, overriding the the ship's government swizzle
   
   `the the` should be `the`
   - [DataFormat](https://github.com/endless-sky/endless-sky/wiki/DataFormat)
   > to signify that is is a single token
   
   `is is` should be `it is`
   - [Dotations](https://github.com/endless-sky/endless-sky/wiki/Donations)
   >  Rather, we are an loose grouping of individuals who work together to create this game.
   
   `an loose` should be `a loose`
   - [HumanSpace](https://github.com/endless-sky/endless-sky/wiki/HumanSpace)
   > You life is comfortable, in some ways
   
   `You life` should be `Your life`
   - [MapData](https://github.com/endless-sky/endless-sky/wiki/MapData)
   > then its orbit will be fade from light to dark blue the further it is
   
   `will be fade` should be `will fade`
   > The sprite listed here is the sprite of the star that will effect ships in the system.
   
   `effect` should be `affect`
   - [Player Conditions](https://github.com/endless-sky/endless-sky/wiki/Player-Conditions)
   > travel from the your current location to the specified planet or system
   
   `from the your` should be `from your`
   - [StoryIdeas](https://github.com/endless-sky/endless-sky/wiki/StoryIdeas)
   > they simple chose to focus their efforts in other areas
   
   `they simple` should be `they simply`
   - [CreatingEffects](https://github.com/endless-sky/endless-sky/wiki/CreatingEffects)
   > identical effects created at the same moment do not end up perfectly in synch
   
   `synch` should be `sync`
   - [CreatingInterfaces](https://github.com/endless-sky/endless-sky/wiki/CreatingInterfaces)
   > The requirement will be appllied to all subsequent elements
   
   `appllied` should be `applied`
   > the game may only partially complete the bar or ring, or segment it, for exammple, the ship hull status ring
   
   `exammple` should be `example`
   - [MapData](https://github.com/endless-sky/endless-sky/wiki/MapData)
   > the port of a planet behaves can be controled more precisely
   
   `controled` should be `controlled`
   > this planet has when the player has illegal goods or outifts
   
   `outifts` should be `outfits`
   
   - [Player Conditions](https://github.com/endless-sky/endless-sky/wiki/Player-Conditions)
   > the number of bays for the given cateogyr of ship the player's flagship has
   
   `cateogyr` should be `category`
   

### Expected content

See above.

**Comment by tibetiroka** [comment]
~~I don't even get to make a typo fix PR.~~

**Comment by warp-core** [comment]
1. https://github.com/endless-sky/endless-sky/wiki/CreatingShips/_compare/a990f66406d09ae1dc0eb6d0d87efe1a5da3b79c
2. https://github.com/endless-sky/endless-sky/wiki/WritingConversations/_compare/61dde1ddaf3a23183f1a19f53f70bc77f7f0b137
3. https://github.com/endless-sky/endless-sky/wiki/CreatingInterfaces/_compare/36a82924aeb69319bdad5b1131401dc436a337bb
4. https://github.com/endless-sky/endless-sky/wiki/CreatingMissions/_compare/50f26a3a799b0b8b3e43cbc1cdb100709c4ac9fa
5. https://github.com/endless-sky/endless-sky/wiki/LocationFilters/_compare/835952d855d2a840253347611045bbcc46ab4553
6. https://github.com/endless-sky/endless-sky/wiki/CreatingInterfaces/_compare/cae505dc5fe01310bdabdca80b3e31a7f546e8a0
I think you might have to go through each file that was changed in the last commit to see those changes, or look at the commit in GitHub desktop.

**Comment by tibetiroka** [comment]
All good now.
