### ISSUE TITLE
Info Panel with overlapping text

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#972]
![20160418151511_1](https://cloud.githubusercontent.com/assets/16338814/14618986/dd41bbcc-057a-11e6-9327-e849d60b483e.jpg)

If you create a ship with too many turrets or guns, the weapons placement will overlap with the ship info. This could be fixed by moving the ship outline into it's own tab or having a subsection below the info text.

**Comment by endless-sky** [comment]
Or by not creating a ship with so many guns. :)

**Comment by mdsmestad** [comment]
Nonsense! XD

**Comment by DingusShingleton** [comment]
There it is again! The Mega Bacterian! A la #971

**Comment by ItsNickBarry** [comment]
@DingusShingleton It's like an epidemic.

**Comment by jmhorjus** [comment]
You can get this to happen with ships in the vanilla game if you just give them enough different outfits that their outfit list doesn't fit in the space provided.

**Comment by endless-sky** [comment]
As of 0.9.4, the info panel can handle twice as many gun hardpoints, and doesn't allow text to overlap when there's not enough space for everything.
