### ISSUE TITLE
Outfit licenses propagated incorrectly and repeatedly to ships

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#9722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ships with license-locked outfits display an extremely long, duplicated list of licenses when you view them in the shipyard. Upon closer inspection, these seem to be every license required by any outfits they have equipped.

### Steps to Reproduce

1. Go to a shipyard that sells ships that have outfits that require licenses (e.g. Coalition or Wanderer space, or Omnis)
2. Look at the section of the description that refers to licenses.

### Expected Behavior

I believe the intended behaviour is that outfit license requirements don't propagate to the ship _at all_, but either way the same license should never appear more than once in this section.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/18634983/697d1199-4f5c-42e5-871c-2303d2b1d792) ![image](https://github.com/endless-sky/endless-sky/assets/18634983/4711df6f-b6eb-4aee-8b63-a1cf5409ff7f) ![image](https://github.com/endless-sky/endless-sky/assets/18634983/c223f6d9-ec83-4884-abdf-b2f324c839bf)

### Link to save file

todo

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

Continuous as of 11PM GMT 2024-01-24

**Comment by TomGoodIdea** [comment]
@warp-core Are there any practical differences between your implementations?
