### ISSUE TITLE
Library error preventing game from launching on NT 5.2

### ISSUE THREAD

**Issue by TomGoodIdea** [endless-sky/endless-sky#9729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to run the game executable, it says that `The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll` and refuses to launch.

### Steps to Reproduce

Just try to launch the game.

### Expected Behavior

Perhaps it could start without errors?

Alternatively, if we don't want to support x86-64 WinXP, we should update our system requirements. ~~Well, I think we should do it anyway since we dropped win32 releases.~~

### Operating System

Windows XP x86-64 SP2

### Game Source

Other (please describe)

### Game Version

v0.10.4 from GOG

### Additional Information

I have the newest (available for this OS) MSVC++ Redistributable package installed.

"Game details" section on our GOG page says the game is compatible with WinXP.

**Comment by warp-core** [comment]
The GoG store page really do say "Works on Windows XP".

**Comment by Hecter94** [comment]
![image](https://github.com/endless-sky/endless-sky/assets/15916854/6670c8bc-10f8-4122-9f12-792a44117a27)
GOG no longer claims that Endless Sky works on XP or Vista.

**Comment by TomGoodIdea** [comment]
> GOG no longer claims that Endless Sky works on XP or Vista.

Did anyone say it doesn't work on Vista?

**Comment by Hecter94** [comment]
I wasn't able to get it to run on Vista when I tried, and I wasn't able to find any accounts of anyone saying that they were successfully running it on Vista.
(I was able to find accounts of individuals saying that they were running it on the other OS' listed)

**Comment by TomGoodIdea** [comment]
> I wasn't able to get it to run on Vista when I tried, and I wasn't able to find any accounts of anyone saying that they were successfully running it on Vista.

Fully updated (SP2 + UCRT)?

**Comment by Hecter94** [comment]
> Fully updated (SP2 + UCRT)?

Not sure; I was running a freshly installed trial version for testing purposes since none of my existing devices still run Vista. 
With that said, even if it is possible to run on Vista, do we really want to list that as an OS we officially support? Given its age, lack of automated testing, and the small number of people using it?

**Comment by TomGoodIdea** [comment]
Well, we have things like Ubuntu 14 listed, how many people use those?

But yeah, I get your point.
