### ISSUE TITLE
Add a way for governments to care about the cost of their ships that you destroy instead of just the crew

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9764]
### Problem Description

Increases in combat rating are based on the cost of the ships that you disable, while changes in reputation are based on the number of crew in the ship you are interacting with. Originally, both of these systems were based on the crew, but this changed with the introduction of the Korath automata, with which you would never gain combat rating with due to their lack of crew.

There is no way though for a government to care about the cost of the ships that you are destroying. Imagine a government where some of their ships are crewed and some are automated (aside from just drones). It's not unreasonable to assume that the government should have its reputation change if you are attacking only its automated ships.

### Related Issue Links

#1322 talked about adding "greedy" government personality that would behave like this.

### Desired Solution

Add some mechanism to change how a government's reputation is effected by interactions taken against its ships. The default would be for governments to only care about the crew of their ships, but we could also have them care about the cost of their ships (with some conversion rate between ship cost and crew), or only care about the cost of their ships without any care for the number of crew.

### Alternative Approaches

N/A

**Comment by Anarchist2** [comment]
Isn't this what `"crew equivalent"` is supposed to fix?

**Comment by Amazinite** [comment]
You know what. You right.
