### ISSUE TITLE
Allow the creation of "aura" weapons that deal AOE damage around the weapon's hardpoint

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9765]
### Problem Description

We currently have the ability to make weapons whose projectiles create an AOE effect when they impact something using the "blast radius" weapon attribute. In some cases, we want weapons with an area of effect to emanate from the weapon itself rather than from the projectile. In such cases, we'll normally have the weapon's trigger radius match or exceed its range so that it explodes moment it is fired. The problem with this is that the AI will avoid damaging itself with its own blast radius weapons by default. We can somewhat get around this by adding the explosion to a submunition, as the AI only considers the first step of a projectile, but this is not the most elegant solution and can come with its own issues.

### Related Issue Links

#2847 is the issue that reminded me of this feature, but the idea of "aura" weapons has been discussed many times before, although I can't find any formal issue on it.
#1428 talks about adding a personality to override the normal ship behavior of avoiding damaging itself with AOE weapons.

### Desired Solution

Create a new weapon attribute "aura" that causes the projectile fired from the weapon to immediately explode and causes the firing ship to ignore whether or not the firing of the weapon will hurt itself. These would require the "blast radius" attribute in order to actually do anything. Lifetime and velocity would be ignored; the range override attribute would need to be used to determine the range at which the AI fires the weapon. All other attributes would behave as normal.

### Alternative Approaches

Add a personality for ships that ignore whether their weapons will damage them and continue using blast radius weapons with high trigger radii.

Add a weapon attribute that causes weapons that run out of lifetime to explode on death. (Currently, a blast radius weapon that reaches the end of its lifetime will just disappear/create a die effect without creating its explosion.)

**Comment by Hurleveur** [comment]
The ramming personality should already mean ship ignore blasting themselves iirc tho it does do other things like ignore all AI

**Comment by Amazinite** [comment]
Turns out we also have a "safe range override" weapon attribute that was never documented. Setting that to zero on a blast radius weapon should make the AI ignore the blast radius on that weapon alone without any personality changes.
