### ISSUE TITLE
bug: Hail panel does not preserve animation attributes

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#9766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Animated sprites lose their animation attributes in the hail panel, leading to unpredictable behaviour.

### Steps to Reproduce

I recommend using Omnis to see planets with animated sprites, since there aren't any in vanilla afaik.

1. Go to the arena planets
4. Hail the planet and look at the icon

### Expected Behavior

The panel should preserve the animation.

### Operating System

EndeavourOS (kernel: Linux 6.7.3-zen1-1-zen)

### Game Source

Built from source

### Game Version

d12301477d6fc2a6231d90004ce4daed4ed5b5fd

**Comment by Amazinite** [comment]
> The planet itself doesn't do the full animation cycle; frames seem to follow each other much slower than in regular sprites, and then jerk back to the starting position without finishing the animation

Are you using the same animation attributes? The jerking sounds like you're not using "rewind", and the slow behavior sounds like the frame rate is just low.

**Comment by warp-core** [comment]
```
		"frame rate" 14.3
		"random start frame"
		rewind
```
Add these as children of the sprite in the object definition.

> In the planet dialog thingy, the animation is really fast. Like, really, really fast.

Is "planet dialog thingy" the hail panel?

**Comment by Saugia** [comment]
If not given a frame rate, sprites default to 2/60 (in the code). None of the Omnis planets have a defined framerate which is why they look strange in their animations.

**Comment by alexrovw** [comment]
It is indeed pretty weird in the planetary hail window. I don't see any issues on the normal space view, though.

https://github.com/endless-sky/endless-sky/assets/98854112/83770481-c5b9-4e65-bc46-9358a8ea7f2e

**Comment by tibetiroka** [comment]
Oh. It is using the wrong framerate/rewind, but that still does not explain why it looks different in the popup panel from the planet itself.

**Comment by Amazinite** [comment]
The hail panel is losing the animation properties of the stellar object.

**Comment by tibetiroka** [comment]
Does that mean it affects animated ship sprites as well as planet sprites?

**Comment by Saugia** [comment]
Considering the Void Sprites as an example don't bug out when targeting them, or Archons, that's different, no?

**Comment by tibetiroka** [comment]
~~What a clever workaround.~~

**Comment by Amazinite** [comment]
> Does that mean it affects animated ship sprites as well as planet sprites?

No. Ships aren't losing their animation properties in the hail panel. It's only planets that are.
