### ISSUE TITLE
No documentation on autosave for creating missions

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#9783]
### Location

wiki

### Describe the issue

The wiki page for "[Creating Missions](https://github.com/endless-sky/endless-sky/wiki/CreatingMissions)" doesn't describe the `autosave` tag, which updates the autosave to what the save file was at the time that mission was offered.

### Expected content

The wiki page for "Creating Missions" accurately describes the `autosave` tag.

**Comment by warp-core** [comment]
I've added this information.
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions/_compare/2b299e99c7c591650c41416d7f8ae26059bded40
