### ISSUE TITLE
Lunarium Quarg Interview: questions don't disappear after being selected

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#9792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In this mission, when you're seated with the Lunarium leaders and get to ask questions, the questions remain there indefinitely even after they've been answered.

Comparing to other questions dialogues, this seems to be due to missing "to display" and "set action" functions.

### Steps to Reproduce

1. Play this mission until you reach the room of Lunarium leaders and get to ask questions.
2. Select a question.
3. See that the question is still shown even after being answered.

### Expected Behavior

The questions should disappear like usual after being answered.

### Operating System

Win 10 21H2

### Game Source

GitHub Releases

### Game Version

0.10.4

**Comment by Arachi-Lover** [comment]
This was intentional so as to allow one to ask everything before resuming with the mission.
Iirc the mission predates the existence of `to display`, and I forgot to account for it there after that became a thing.

**Comment by xX-Dillinger-Xx** [comment]
I have seen this behaviour in some other dialogues as well. I believe one was in a Remnant side mission and maybe some other places in the game. I also thought it was some sort of bug, but never thought to report it.

**Comment by ziproot** [comment]
The james dialogue does this as well.

**Comment by Hurleveur** [comment]
James could just mention it honestly, if we dont break character/immersion too much by doing it.
Smth like "you know your datapad records the conversation, you can see what was said before on it"
