### ISSUE TITLE
Capture ships -> crew lost very (too?) often

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#98]
It constantly happens, that I loose crew members on capturing a ship even if I have a probability to win > 99%. 

Is there another probability involved when calculating the death of own crew members? Or is this probability somehow recalculated to generate the number of dead crew members? If yes, it would be great to display the number of expected dead crew members (e.g. something like 0.1 if you can expect no dead or 2.5 if you expect between 2 or 3 dead crew members, not sure what the correct statistical term should be used here but I hope you get the point).

If the win probability should be directly involved in calculating the dead crew members, there might be some bug in the calculations.

**Comment by endless-sky** [comment]
The expected casualties are displayed in the boarding panel right under your expected chance of victory (e.g. "expected casualties: 1.3").

In terms of how casualties are calculated, in each round of combat your odds of losing a crew member are equal to the ratio of your "attack" strength to the other ship's "defense" strength. For example, if your strength is 4 and their strength is 6, you have a 60% chance of losing a crew member in the first round of combat. If both ships have a lot of crew, multiple rounds of combat are merged into one, so multiple crew members on each side may die when you click "attack."

**Comment by schlamar** [comment]
> The expected casualties are displayed

Ah weird, not sure how I missed this.

Nevertheless, in this case the win probability is pretty confusing. There is sometimes the scenario, that there is a win probability > 99% and expected casualties for example 0.6. If there is only one round it can likely happen that I loose one crew member while the defender doesn't loose anyone. This doesn't feel like a win to me ;)

**Comment by akien-mga** [comment]
AFAIU the win probability refers to the whole battle; it says that you have more than >99% chances to win the battle (i.e. to kill all enemy crew members before loosing all of your own crew), but does not take into account whether you will have casualties or not.

Casualties are handled on a per round basis as shown in the expected casulaties field.

**Comment by schlamar** [comment]
Yes, that would make sense. 

However, if the win probability refers to the whole battle, what about the expected casualties? Refers this to the whole battle or the next round?

**Comment by akien-mga** [comment]
Only the next round IIUC. But there might be room for improvement in the UI to make it all clearer indeed.

**Comment by endless-sky** [comment]
Both numbers refer to the entire battle. So, for example, 95% odds mean a 5% chance that everyone on your ship will die.
