### ISSUE TITLE
Game crashes in Sayaiban

### ISSUE THREAD

**Issue by uexkull** [endless-sky/endless-sky#980]
Game crashes when any option is selected in the first contact with the Drak in Sayaiban

**Comment by Disiuze** [comment]
How many times has this happened?

**Comment by endless-sky** [comment]
Are you using the very latest code? A week or two ago I fixed an issue that
was causing a crash with that particular mission (or, any conversation
displayed as the result of an "on enter" action). That fix was made at the
same time as I added the Drak mission, but if you updated your data files
without rebuilding the code, that would explain the crash.

**Comment by uexkull** [comment]
just about every time I enter Sayaiban @Disiuze

**Comment by uexkull** [comment]
Ah, that might be it...I'll try that tomorrow @endless-sky

**Comment by uexkull** [comment]
@endless-sky  JUST TO CLARIFY, I'll download the whole endless sky master file again and just replace all the current package contents... is that the right thing to do?

**Comment by Wrzlprnft** [comment]
You have to rebuild, re-compilate, remake the executeable, since it seems to be(was) a engine issue.

**Comment by uexkull** [comment]
@Wrzlprnft how... haha I'm so sorry but if its got anything to do with code I'm less than expert to say the least

**Comment by uexkull** [comment]
@Wrzlprnft @endless-sky  FYI running Mac OSX 10.10, would also just like to know what the file name of the engine is, I've found XCode and engine.h and engine.cpp, is it any of those?

**Comment by Wrzlprnft** [comment]
How were you testing the new stuff? Were you just copying all the data around a official release executable, or did you follow the [build instructions](https://github.com/endless-sky/endless-sky/wiki/BuildInstructions)? In either case, you have to rebuild the game, because the fix for your crash was not in the data files(which are loaded everytime the game starts), but in the game itself(which is officially compiled from the source code in the downloadable releases).

**Comment by uexkull** [comment]
Okay, I'll give it a shot. But anyway, here's the errors.txt
[errors copy.txt](https://github.com/endless-sky/endless-sky/files/230427/errors.copy.txt)

**Comment by Wrzlprnft** [comment]
It indicates other new game elements added to the games core code, like new weapon attributes.

**Comment by endless-sky** [comment]
This bug was fixed in ebb66c3, so it's present in 0.8.11 but will be fixed in the 0.9.0 release (or if you recompile the executable from the source code).

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
