### ISSUE TITLE
Enhancement: auto-masking for external bay shadows

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#981]
pull #939 has raised the issue of parent ship shadows on fighters in bays carrying the "under" token (or even "over", if placed near a vertical feature on the parent ship.)

i'm not sure how easy it would be to have a sprite (the shadow) render (or not) on the condition that there is a fighter in the bay?  a specific sprite (masked to specific fighters) for a specific fighter in-bay?

the latter of those two questions would mean rendering a shadow for each fighter, for each carrier that has external bays - it would make the future of fighters/external carriers bleak (with the amount of work that needed to be done to add either)...(edit: which would really just be more intimidation than actual work)

another option would be to try to integrate fighters in-bay into #595 so that 'shadows' are less prominent in general, and shading takes precedent...not sure how that would work, though...

**Comment by LocalGod79** [comment]
this problem could probably use some discussion to find the best solution.

@endless-sky - Photoshop and GIMP handle the "overlay" blending mode slightly differently, in that PS will render a layer overlaying transparency, while GIMP appears to not (allowing the overlay to "fall through" the transparency).  perhaps the solution lies in the way GIMP handles that blending mode...

**Comment by endless-sky** [comment]
I just don't think it's feasible to cover all the combinations of fighters and bays. That is, every carrier would need to have a custom sprite defined for each of its bays for each fighter type that might be in that bay. For the tiny amount of graphical nicety you gain, it's just not worth it, especially since ship sprites tend to be dark on the edges anyway, which makes the ship outlines pretty clear even without extra shadows:

![sestor](https://cloud.githubusercontent.com/assets/11450262/14727944/440180ce-07fe-11e6-8d77-d0b79ebb3c4e.jpg)

**Comment by LocalGod79** [comment]
ideally, the creator of the carrier would provide unmasked shadows with the sprite e.g.
![skeinshadow](https://cloud.githubusercontent.com/assets/16969517/14729779/c5ed9310-080e-11e6-8fc0-45260452f884.png)
and then the game engine automatically masks the appropriate fighter using GIMP-style "overlay" blending while creating the "fuller carrier" sprite, allowing the excess shadow to "fall through" the transparent sections of the [u]fighter sprite[/u], and not be rendered on anything else below the parent ship.

i'm not sure i'm communicating my thought clearly...

**Comment by LocalGod79** [comment]
okay, i believe the above expression is clearer, except that the shadow would have to be a separate sprite from the ships for the game engine to be able to selectively mask it.

**Comment by Wrzlprnft** [comment]
Just to get it right:
Local, you want a feature that allows you to define a shadow-image-file for a bay, which, given the attribute is selected and the shadow file path is defined, the game only renders additionally when a fighter is docked. Doesn't matter which fighter, since the shadow is fairly small. And you were only talking about below-rendered fighters.

**Comment by LocalGod79** [comment]
i believe that 'above' rendered fighters could employ the feature as well, if they were placed near a vertical fin, or in an alcove...

i think an important distinction: the shadow image (supplied with ship sprite) is unmasked, and the game engine masks it to the fighter - so that the carrier creator doesn't need to create a new masked shadow (to make sure that the shadows fall appropriately on all possible fighters-in-bay) every time a new fighter is added to the game.

**Comment by Wrzlprnft** [comment]
With which of the existing [blending modes](https://github.com/endless-sky/endless-sky/wiki/BlendingModes) this would be best covered in your opinion? additive?

**Comment by LocalGod79** [comment]
actually, as long as the shadow sprite is semi-transparent, the alpha blending mode is probably best - the real challenge is getting the game engine to only blend areas of the shadow that are also occupied by a fighter sprite, and discard the rest (auto-masking).

**Comment by Wrzlprnft** [comment]
since the game is able to determine outlines, maybe we can go back and use that function? So only the part of the shadow "colliding" with the fighter is drawn.

**Comment by LocalGod79** [comment]
indeed - i always felt like my expression was poor.

perhaps this is better:
a feature that automatically masks an optional shadow layer (attached to carriers with external bays) and renders it when fighters are in-bay.

**Comment by lehgogh** [comment]
This should be an option for players that want to use low/high quality graphics, as this may introduce more lag.
