### ISSUE TITLE
Borderline issue with ship depreciation when the ship is a variant with `add attributes cost`

### ISSUE THREAD

**Issue by SomeTroglodyte** [endless-sky/endless-sky#9835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You won't see this in a vanilla game, so I've mocked up a mod that demonstrates (in the save box).

Depreciation with completely empty records will respect a cost changed through 'add attributes' for the percentage display comparison, but output a price where that attribute change is ignored. That is, you will pay the base ship's price (+/- outfit differences), and see that as percentage depreciation against the configured variant's price.

### Steps to Reproduce

1. Install test ~mod~ plugin
2. Start a new pilot with the Test start from the plugin
3. Look at the ship prices and depreciation percentages.

### Expected Behavior

Variant A:
* Document that it is a bad idea to offer a ship variant that has add attributes cost in a shipyard

Variant B:
* Ship is sold at the price that includes the 'add attribute cost' value, and depreciation is thereby back to 100% counting down once depreciation records are recorded

### Screenshots

<details>

![image](https://github.com/endless-sky/endless-sky/assets/63000004/f7aeebe0-f63e-456b-b8ac-108ea039f8a3)

```
ship "Sparrow" "Bargain Sparrow"
	name "Bargain Sparrow"
	add attributes
		"cost" -200000
		"shields" -900
		"hull" -100

```

Note the percentage is correct for a comparison of the actually asked price, which is the price of a normal Sparrow, relative to the  true price of the "Bargain Sparrow" you get for it. The other ships in the demo have outfit differences which show they are correctly respected in the overall calculation.

It's not the sign - a more expensive variant starts at <100% depreciation and sells for a rebated price.

The rest of the plugin is more or less a weak little joke as sign of respect for an amazing project.
</details>

### Link to save file

[Test-depreciation.zip](https://github.com/endless-sky/endless-sky/files/14315636/Test-depreciation.zip)

### Operating System

Mint 21.2

### Game Source

Built from source

### Game Version

0.10.6 alpha up to PR # 9831

**Comment by Hurleveur** [comment]
I think its just going to treat the ship as if it had reached that depreciation amount already, and go down from there to 25%, in which case idk if its worth changing code over, tho we could want the variant for other things eventually
One can always just define a new ship thats the same as the old one btw and with a different cost
