### ISSUE TITLE
Fw-Intro-Missions spaceport 2 missions pop-up

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#984]
I was doing the "Scan that cruiser in the orbit" mission, but as i entered the spaceport to continue the chain, i was confronted with the temptation of doing the karate move, which confused me quite a lot until i noticed that that intro missions-start just popped in between the "go to the spaceport" and "get the next mission". Maybe, if a mission requires you to go to the spaceport, it would be better to handle that one first?

**Comment by Wrzlprnft** [comment]
That's a weird day today: it happened again. I was on Rand with Katya and Ijs, as right after they finished their frozen milkshakes, the rand terraforming mission popped up. This time it was the expected order(even if i did not expect the mission to come up)

**Comment by endless-sky** [comment]
I've made a change in commit 242c1b5 so the very first mission in these various strings won't show up if a continuation of another mission string is also being shown in the same spaceport. So, that should address this issue.

**Comment by Wrzlprnft** [comment]
With my ususal luck, i wouldn't have encountered  such a situation ever again anyway.
Thx for taking a look at it.
