### ISSUE TITLE
Add sound for unlandable objects.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#985]
Just like it describes..Objects like gas giants or stars should create a sound that signifies being unlandable.

**Comment by Amazinite** [comment]
So pretty much just an error sound to go along with the message?

**Comment by mdsmestad** [comment]
@Amazinite yep, pretty much. Some little "nope" kinda clinking sound is what I'm thinking

**Comment by LocalGod79** [comment]
perhaps change the issue subject to something more concise, like "Enhancement: Add error/fail sounds"

this could also be employed when you fail a mission, when you try to fire a secondary weapon that is out of ammo, jump without fuel (is there already one?  i play with the sound off)

**Comment by Amazinite** [comment]
There aren't any error sounds right now, at least not that I know of. I feel like an error sound would be especially useful if you fail a mission or job.

**Comment by mdsmestad** [comment]
@Amazinite @LocalGod79 I bet this will be implemented sooner or later

**Comment by endless-sky** [comment]
Added in commit dde2fe9.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
