### ISSUE TITLE
Outfit/Weapon logic is borked

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#9852]
### Problem Description

So I was trying to implement something and an interesting detail caught my eye that makes no sense to me.
Why is the weapon class parent to the outfit class? That is in no way a representation of how that works in data or even in the game in general, I suggest to change this.

### Related Issue Links

None found

### Desired Solution

Remove the inheritance of outfit and make weapon a member in the outfit class.

### Alternative Approaches

No, its that or leave it like it is.

**Comment by Amazinite** [comment]
I too have encountered this headscratcher.

**Comment by RisingLeaf** [comment]
I would be happy to change it if it is something that we can agree on.
Hens I opened an issue first because I thought there might be some thought behind it.

I looked on a git blame and it came from MZ direct commit.

**Comment by Amazinite** [comment]
> So I was trying to implement something

@warp-core would like to know what it was that you were attempting to implement. And from the PR:

> Usage examples
> makes some changes a lot easier

What changes?

**Comment by RisingLeaf** [comment]
> @warp-core would like to know what it was that you were attempting to implement

I was trying to add more than one weapon node to outfit to create a double effect gun or a gun that shoots two different projectiles that are not timed the same way, which is difficult to do with sub-munitions especially the timing thing

> What changes?

~~refer to the top~~
changes that require you to use weapon as a separate object from outfit, fr example multiple weapon nodes or maybe even a gun that can use different types of ammo but that would be even more complex

**Comment by Hurleveur** [comment]
Cant we just have 2 weapons taking the same turret mount?

**Comment by RisingLeaf** [comment]
Ye but no? I want an outfit that shoots two things not a dual turret mount, thats something different no?

> (And you'd be surprised what you can do with submuns)

Yes but we can also just make things easier
