### ISSUE TITLE
[BUG/ENHANCEMENT] Acceleration/Drag/Submunitions not displaying properly in Outfitter Screen

### ISSUE THREAD

**Issue by pootthedestroyer** [endless-sky/endless-sky#987]
Acceleration and drag do not appear to be taken into account when displaying a weapon's range in the outfitter screen. For weapons with any significant acceleration, this causes a wide discrepancy between the reported range and the actual range, which gets progressively wider as the acceleration "tail," for lack of a better term, gets stronger (either because it lasts longer due to less drag, or the original number is higher, or both.)

Likewise, submunitions wreak havoc with damage display numbers.  This may not have any easy solution. In order to give players accurate info about a weapon with submunitions, new display entries may be required. If there's no room for that many new entries, perhaps a universal warning about submunitions causing inaccuracies would be a compromise solution.

**Comment by LocalGod79** [comment]
i had not noticed range discrepancies so much as damage but didn't see a solution, so left it unreported.

**Comment by endless-sky** [comment]
If you set the acceleration and drag so that a projectile's steady-state velocity is the same as its initial velocity (as is the case with all human missiles, for example) the range display works correctly.

I'd rather not change how it works in other cases, because it's actually useful to be able to apply drag so that a weapon's calculated "range" is actually much greater than its effective range. For example, that's how I got the AI to deploy Kor Mereti mines when enemies are approaching, even though the true range of the mines is not very far.

**Comment by endless-sky** [comment]
The damage numbers that are displayed are accurate, unless there's a bug there. It adds the damage of the base projectile to any damage done by its submunitions, recursively - e.g. if you have 3 submunitions that each do 50 damage, the weapon is reported as doing 150 damage per shot.

**Comment by pootthedestroyer** [comment]
I suspected the overall damage numbers might be accurate in that sense, which is why I cross-labeled this as a bug/enhancement. If I'm reading the documentation correctly, submunitions only spawn at end-of-life, not also on-impact. That means that the more submunition stages a weapon has, the less truly accurate the displayed numbers will be.

For example, my submunition weapon divides as such: 1 -> 2 -> 4 -> 8, with significant inaccuracy and some extra acceleration/velocity on each split. A ship that gets hit by even 2 submunitions from the final wave isn't taking anywhere near the damage reported in the outfitter screen.

**Comment by endless-sky** [comment]
Submunitions don't spawn on impact, *but* the damage that would be dealt by any submunitions that are still "inside" the projectile is applied along with the damage done by the projectile itself.

So, if you want the weapon to do the same damage regardless of which "wave" hits, you can put all the damage in the final submunitions. If not (e.g. if you want to do more or less damage depending on what stage it's in) you can add damage amounts to the non-final submunitions as well.

**Comment by pootthedestroyer** [comment]
It's good to know how these types of weapons will work. I think this
information needs to be added to the documentation.

Off topic... this system is going to make balancing my weapon really,
really difficult >.<

**Comment by pootthedestroyer** [comment]
Don't suppose negative shield/hull/ion damage numbers will interact
properly on submunition weapons? That'd solve the problem, though not
particularly elegantly.

**Comment by LocalGod79** [comment]
they do, and are employed on the new korath mines (not ion damage, though)
