### ISSUE TITLE
Significant nerfs cause play issues for existing users (Lasher pistol)

### ISSUE THREAD

**Issue by VA1DER** [endless-sky/endless-sky#9871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The recent "rebalance" of the Lasher pistol illustrates what I suggest is a procedural bug.  A radical nerf like this, even if the new stats are correcting a long-standing bug, leaves players who made in-game decisions high and dry.  For me personally, as an example, I had recently adopted the lasher pistol over the (irreplacable) Pug Peacekeeping staves.

This rises to the point of being a procedural bug.

When it is contemplated to radically alter a well-known item like the Lasher pistol, please consider one or more of the following procedures:
1) Consider grandfathering in the original stats for existing players.  Simply create a new item with the same picture/description and updated stats, and replace that as the item for sale.  This leaves existing players with their original stats intact, but prevents them from obtaining more and enforced the new stats for all new plays.
2) Warn players ahead of time with a message on the forums.
3) With as radical of a change as was made with this particular item, a deprecation notice in-game is appropriate.  Something like "NOTE: The Lasher Pistol which you have 245 of is now deprecated.  It will be replaced with an item that has the following changed stats in the next release: _________________".  The first-time help subsystem would be an eminently appropriate method to employ for this.

### Steps to Reproduce

1. Sell something you can never replace because you find something that is objectively better.
2. Install new version with unwarned nerf.
3. Regret step 1

### Expected Behavior

1. Warning
2. Grandfathering

### Operating System

Windows 10, Windows 11

### Game Source

GitHub Releases

### Game Version

0.10.6

**Comment by Quantumshark** [comment]
There isn't anything stopping you from reading the changelog before updating, or from following development on Github and seeing commits as they're made. If you are concerned about being 'caught out' by changes to the game, you can look at those changes. Changes are not obfuscated in an attempt to catch people by surprise.

Supporting deprecated versions of outfits and renaming the real version whenever we changed them would be extremely messy, and ultimately counterproductive to whatever the reasoning behind the change was in any given case. We have done this in the past in one specific case, that of the outfits expansion, but I don't think it would be reasonable to do so for every balance change ever made. Having to rename outfits every time we changed one of their stats would be hugely inconvenient, and the only effect would be making balance changes, which have been decided on and felt to improve the game, non-binding.

**Comment by Hecter94** [comment]
A couple of things to bear in mind, 

1. Endless Sky is a game currently in development. It is expected that parts of it will change, sometimes quite significantly. I don't necessarily feel a "warning" is necessary, given that the assumption should be that things will change.
2. This change was suggested in #8559 in March of 2023 and wasn't in a release until February of 2024, giving almost a full year of notice.
3. All of our releases are available on our [releases page](https://github.com/endless-sky/endless-sky/releases), so players can always choose to continue playing on their current version if they don't want their play experience to change.
4. Endless Sky's data is stored in plain text files, which are easily modifiable and can be modified via plugins. While this isn't always possible, such as with engine changes, in most cases, especially with balance changes, a user who disagrees with the change can easily edit it back to its original values or to whatever values they feel are appropriate.

While I understand that losing access to something you had can be frustrating, I don't see any actionable steps that can be taken here. Moving forward I'd suggest keeping an eye on our [issues](https://github.com/endless-sky/endless-sky/issues), [pulls](https://github.com/endless-sky/endless-sky/pulls) and [changelog](https://github.com/endless-sky/endless-sky/blob/master/changelog) so you can stay informed of any upcoming changes.

Also check out our [wiki](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins) if you'd like to revert the change locally.

**Comment by Hurleveur** [comment]
You can modify your savefile to get the Pug weapons back, and nerve gas is just as good

**Comment by xX-Dillinger-Xx** [comment]
Just my 2 cents, 
Although, I agree with the Devs on this one, I do, kinda get the OP's point. 
Sometimes, people are just simply players, and can feel left in the dark after an update. Expecting every player to create a Github account just so they can follow along seems a little unreasonable. It kinda feels a little like your blaming the players for not closely following development. Sometimes, people just want to play and aren't interested in the development. Well, at least until something ticks them off. 

The idea of using the first time help system to display highlights of the changes, on first load, after an update, would actually be very helpful to players. Yes, they can read the changelog, but sometimes all they need are the highlights. I suggested something very similar involving a new "players console" .
