### ISSUE TITLE
Game speed drops

### ISSUE THREAD

**Issue by xX-Dillinger-Xx** [endless-sky/endless-sky#9881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I select any korath ship with a large crew count my game speed drops. I'm guess anything over 300. The higher the crew count the greater the drop. It's hard to say but if had to guess, I'd say the drop ranges from 10% - 20% 

### Steps to Reproduce

- go to any exiles worlds 
- select any thing bigger then a 577.  some 577 do it as well.  Echo-Galleon does not cause any issue, at least the few I attacked for testing.
- does not matter if you have any tactical scanners or not. I used a rano, peregrine and, kestral for testing. The rano had approx. 400 crew. All flagships show the same results.
- ships in lower end of this range, you can have speed toggle back and forth, at random, if the distance apart is great enough
- for A'awoj  the distance apart does not matter and even if they leave the system the speed is reduced until I unselect it.

### Expected Behavior

No reduction in speed

### Operating System

Windows 10 Pro, 10.0.19045 Build 19045

### Game Source

ESLauncher2

### Game Version

10.4, 10.5, continuous, and PR9797

### Additional Information

- I tested with Hurleveur's PR9797 to see if that made any difference because I believe he removed the odds calculations. The results where the same. I think those calculations only happened during boarding anyway, but figured, what the heck.
- My CPU is an i5 quad core, although I don't the CPU is the issue.  <<**<<< EDIT**
- My GPU is an XFX AMD Radeon HD 4350 1 GB  https://gpuz.techpowerup.com/24/01/15/wye.png
- I know my GPU isn't the greatest. It's an older card but still does what I want, most of time. LOL
- in game monitor
  - CPU runs between 3 - 5 %
  - GPU runs between 8 % unselected and jumps to as high as 12 % selected
- using FRAPS
  - FPS is 60 with nothing selected and drops to the 30's  with a large ship selected. 
- video appears stable everything just slows down
- I feel like the GPU is being used to make some calculation for some reason. The surrounding action and number of asteroids does not have an effect on the issue. 

**EDIT:** I will continue to test and give updates, so some of ideas my become irrelevant.

**Comment by Koranir** [comment]
> FPS run in the higher 90's with nothing selected and drop to the 80's with large ship selected.

Strange, Endless Sky should be locked to 60fps, the game isn't built to go any higher.

Also, do you have highdpi enabled?

**Comment by xX-Dillinger-Xx** [comment]
Well I wouldn't count on the _xbox game bar overlay_ in windows for accuracy. Lets assume it was wrong.
No, I don't use highdpi and my zoom is set at 100.
I don't feel it's a video issue because, like I said, the surrounding action, number of asteroids, nor numbers of enemy and escort ships have an effect on the issue. 
Ship selection seems to be the only factor.

**Comment by xX-Dillinger-Xx** [comment]
I edited the stats for a Korsmanath A'awoj and set the max bunks and crew to 19 and the problem still occurs. 
Scratch crew size off the list..
I'll do some more testing tomorrow

**Comment by warp-core** [comment]
Do you know what components your computer has? Particularly, CPU, graphics card/GPU, and system memory capacity (RAM)?

[Outline Test.txt](https://github.com/endless-sky/endless-sky/files/14482297/Outline.Test.txt)
If you load this save file, take off, and select your Embersylph escort, what happens to the in game CPU and GPU usage readings?

**Comment by xX-Dillinger-Xx** [comment]
@warp-core
Test Results:
- drifting 
  - escort unselected  CPU 1%  GPU 7%
  - escort selected CPU 1% GPU 8%
  - toggled back and forth. same result each time

![cpu-2794](https://github.com/endless-sky/endless-sky/assets/153941034/aa1ef0c0-11c8-42d2-b6e6-1da3c564f774)
![graphics](https://github.com/endless-sky/endless-sky/assets/153941034/6fe23cc4-2c37-4a8a-8621-eecf067d9adf)
![memory-1994](https://github.com/endless-sky/endless-sky/assets/153941034/5dd022db-a833-4378-8a6c-a029fa874929)

**Comment by xX-Dillinger-Xx** [comment]
Added a Heron to Kor Fel'tar  and confirmed that I get the same behavior.
- roughly the same reduction in speed as a Korsmanath A'awoj
- and the reduction stays until I unselect, even if I jump back to Misam, and even if the targeted ship lands.

**Comment by xX-Dillinger-Xx** [comment]
I'm leaning towards it being a cumulative effect of several attributes with large numbers. 
The ships that cause issues all have large numbers for several of the key attributes.
They all have high cargo space, high mass, high outfit space, a lot of weapons, etc. 
I looked at the code and there seems to be several different calculations being done while a ship is selected.  But, I really don't understand what I'm looking at.  I also don't know why it's only effecting me. The cpu load doesn't spike.
Today, I noticed that while I had a 577 targeted the, speed would be slow until I increased my distance to 2000 units. It then went to normal.  When I moved back closer then 2000 the game slowed down again.

**Comment by xX-Dillinger-Xx** [comment]
> > FPS run in the higher 90's with nothing selected and drop to the 80's with large ship selected.
> 
> Strange, Endless Sky should be locked to 60fps, the game isn't built to go any higher.
> 
> Also, do you have highdpi enabled?

I switched to FRAPS and I'm getting 60. When I select one of the problem ships it drops to 30.

**Comment by xX-Dillinger-Xx** [comment]
I think I've come to the conclusion that this may not be a bug. It may very well be that I have exposed the minimum requirements related to a GPU. I'm making an assumption that the GPU is doing a lot of calculations while a ship is selected and my weak GPU just can't handle the load.  I don't know enough, to know how easily it would be to change the code so that the CPU does more of the work. I suspect it will be WAY too much work. 

If someone has the time, I would appreciate some clarification surrounding my assumptions, and maybe try and explain what's happening in the code.

**Comment by Koranir** [comment]
> If someone has the time, I would appreciate some clarification surrounding my assumptions, and maybe try and explain what's happening in the code.

The only thing that would use more GPU when targeting a large ship would be the ship outline [1], which is known to be pretty computationally expensive, but not to the point of halving your frames. Try:
- Seeing if enabling the ship outline affects your performance
- Disabling VSync

[1] ![image](https://github.com/endless-sky/endless-sky/assets/101683475/f7aaf907-297c-463d-9647-4c006ceff3df)

**Comment by xX-Dillinger-Xx** [comment]
I need to have vsync on, I get screen tearing with it off.
'ship outline' on then off, did seem to do something but only in the shipyard. I never really noticed it before and isn't an issue. 
I turned off "rotate ship in HUD" that seemed make a bigger difference. It's passable, reduced the FPS drop to less then 10. 
I also noticed that even as the game is loading the GPU load and FPS bounce all over the place. It stabilizes once the main menu comes up.

**Comment by warp-core** [comment]
How does it behave if you launch the game with the following in a plugin?

```
interface "hud"
	# Player status.
	anchor top right
	
	sprite "ui/status"
		from 0 0
		align top right
	
	string "location"
		from -160 25
		color "medium"
		align right
		width 140
		truncate back
	string "date"
		from -20 45
		color "medium"
		align right
	string "credits"
		from -20 65
		color "medium"
		align right
	
	outline "player sprite"
		center -75 155
		dimensions 70 70
	ring "shields"
		center -75 155
		dimensions 120 120
		color "shields"
		size 1.5
	ring "hull"
		center -75 155
		dimensions 110 110
		color "hull"
		size 1.5
	ring "disabled hull"
		center -75 155
		dimensions 110 110
		color "disabled hull"
		size 1.5
	bar "fuel"
		from -53.5 425
		dimensions 0 -192
		color "fuel"
		size 2
	bar "energy"
		from -33.5 415
		dimensions 0 -192
		color "energy"
		size 2
	bar "heat"
		from -13.5 403
		dimensions 0 -192
		color "heat"
		size 2
	bar "overheat"
		from -13.5 403
		dimensions 0 -192
		color "overheat"
		size 2
	bar "overheat blink"
		from -13.5 403
		dimensions 0 -192
		color "dim"
		size 2

	# Targets.
	anchor top left
	visible if "red alert"
	sprite "ui/red alert"
		from 10 10
		align top left
	visible
	sprite "ui/radar"
		from 0 0
		align top left
	point "radar"
		center 128 128
	value "radar radius" 110
	value "radar pointer radius" 130
	
	sprite "ui/navigation"
		from 200 0
		align top left
	string "navigation mode"
		from 215 20
		align left
		color "medium"
	string "destination"
		from 230 40
		align left
		color "medium"
		width 135
		truncate back
	
	sprite "ui/target"
		from 0 240
		align top left
	point "target"
		center 75 315
		dimensions 140 140
	value "target radius" 70
	image "target sprite"
		center 75 315
		dimensions 70 70
	ring "target shields"
		center 75 315
		dimensions 120 120
		color "shields"
		size 1.5
	ring "target hull"
		center 75 315
		dimensions 110 110
		color "hull"
		size 1.5
	ring "target disabled hull"
		center 75 315
		dimensions 110 110
		color "disabled hull"
		size 1.5
	
	visible if "range display"
	sprite "ui/range"
		from 130 263
		align top left
	string "target range"
		from 160 260
		align top left
	visible if "tactical display"
	sprite "ui/tactical"
		from 130 290
		align top left
	string "target crew"
		from 162 298
		align top left
	string "target fuel"
		from 162 318
		align top left
	string "target energy"
		from 157 338
		align top left
	string "target heat"
		from 147 358
		align top left
	visible
	
	string "target name"
		center 75 395
		color "bright"
		width 150
		truncate middle
	string "target type"
		center 75 415
		color "medium"
		width 150
		truncate middle
	string "target government"
		center 75 435
		color "medium"
		width 150
		truncate middle
	point "faction markers"
		center 75 435
	string "mission target"
		center 75 455
		color "medium"
	
	# Other HUD elements:
	box "escorts"
		from 0 460 top left
		to 120 0 bottom left
	box "messages"
		from 120 0 bottom left
		to -110 -200 bottom right
	box "ammo"
		from -110 450 top right
		to 0 0 bottom right
	value "ammo icon height" 30
	value "ammo icon width" 80
	anchor top
	point "mini-map"
		center 0 100
```

**Comment by xX-Dillinger-Xx** [comment]
@ warp-core Will test when I get a little time. I know it goes in the plugin folder, but what file name should I use?

**Comment by warp-core** [comment]
File name doesn't matter. It just needs to be in a `.txt` file in the `data` folder within the plugin.

**Comment by xX-Dillinger-Xx** [comment]
Ok thanks.  Just to clarify, above text in `test.txt` in` data` folder in `plugins` folder   Do I need anything else? I've not made any plugins yet.  Sorry warp, I'm still learning, but fear not I learn fast.

**Comment by warp-core** [comment]
The `data` folder needs to be inside a folder (name doesn't matter) inside the `plugins` folder.
If you're on Windows, by default:
```
C:
Users
<your user name>
AppData
Roaming
endless-sky
plugins
<any name>
data
test.txt
```

**Comment by xX-Dillinger-Xx** [comment]
Thanks for the above info. I got it working. Here's something odd, when I copied all your text into notepad++ it saved it as 
global conditions.txt

Any way, that's seems way better no impact at all selecting the 'planted' ships.   Korsmanath A'awoj and Herons in Kor Fel'tar

I had
- flagship = arfecta, escorts = emerald sword, 1 merganser  < just what was close.  I'll try with bigger fleet later, however I don't expect it will make any difference. It didn't before. 
- star field on 
- haze on
- Rotate ship in HUD on
- parallax off

GPU only spiked to 99% briefly and that was because a battle broke out. 2 Korsmanath A'awoj launched all their fighters at my escorts. The rest of the time my GPU bounced around 90% < externally measured. In game lies. 

I'll leave this installed from this point on and report back after a longer play. For now, I think it is as good as it gets.

**Comment by xX-Dillinger-Xx** [comment]
Oh Crap, I forgot to thank you for your efforts, so Thank-you.

**Comment by xX-Dillinger-Xx** [comment]
I think it is safe to say this solved my issue and will close it. 
@warp-core
 _When and if_ you have time, could you give me an explanation as to what was happening and why your fix works?

Also, should there be an expanded "video settings" in the preferences to accommodate players that may have the same issue?

**Comment by xX-Dillinger-Xx** [comment]
Appears to be resolved for now.

**Comment by warp-core** [comment]
I believe the issue is related to the outline.
Converting from a normal sprite to the outlines can be difficult for older computers.
You've already seen this with the "Ship outlines in shops" option.
A single outline may not be too difficult, but the shop may feature many outlines, so the performance impact has been apparent there for a long time.
More recently, with some particularly large or complex sprites, it seems the single target outline (alongside the flagship outline) can also noticeable impacts on performance.

#9942 adds settings to switch between the sprite and outline modes.
