### ISSUE TITLE
Missing specified format in music node

### ISSUE THREAD

**Issue by orbitalsupershell** [endless-sky/endless-sky#9890]
### Location

Creating systems and planets

### Describe the issue

In Creating systems and planets > System > Music node
There seems to be missing what format you need for the music to play correctly
Ive had to troubleshoot to find out that i needed to use an mp3
![Image](https://github.com/endless-sky/endless-sky/assets/73935250/3fa4c4af-30a4-4012-b801-628d394c97c8)

### Expected content

Use mp3 files for in-system music

**Comment by danaris** [comment]
It would probably be worth noting:

1. here in MapData, that music still needs to go in the `sounds/` subdirectory, and
2. in the CreatingPlugins page, where it mentions the `sounds/` subdirectory, that both music and sounds go there, and their respective file formats.
