### ISSUE TITLE
Remnant: Cognizance 28

### ISSUE THREAD

**Issue by rocky8u** [endless-sky/endless-sky#9918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The mission is not progressing upon landing on Baianus with sufficient cargo and passenger space. Does it require sufficient space on one ship like a previous mission with the Aeon Cell or can you use multiple ships to meet the requirements?

The game allows you to progress the mission with multiple ships. If you try to leave Caelian without sufficient bunks or cargo space it tries to abort the mission.

### Steps to Reproduce

Steps:
1. Get mission on Caelian in Cinxia system. Mission requires 280 tons of cargo space and 20 bunk space
2. Gather 3 ships: 1 Shield Beetle and 2 Gulls: total cargo space 432 tons, 81 total bunks available.
3. Fly directly to Baianus in the Parca system.
4. Use cloaks to bypass the Korath ships in the system, land on the planet (all ships have cloaks)
5. Nothing happens
6. Take off and land again, nothing happens,
7. Deadline expires, mission fails.

### Expected Behavior

I expect the dialog to progress the mission to trigger upon landing on Baianus. With sufficient cargo and bunks in the fleet it should trigger. If there is some other requirement or it requires a single ship, this should be indicated.

### Operating System

Windows 10 Pro

### Game Source

Steam

### Game Version

v0.10.6

### Additional Information

No mods installed.

**Comment by bene-dictator** [comment]
I'm pretty sure you need a single ship with >=230 cargo space to complete missions that transport large outfits. It's not indicated very well, in fact I've come across the same issue in a different part of the Remnant campaign. We should at least look into writing a note to say that the cargo has to be transported on one ship.

The reason this is so is because you can't transfer partial outfits, it is unlikely to be changed as it will create problems with boarding and plundering.

**Comment by rocky8u** [comment]
Is the thing being loaded when you reach Baianus an outfit? The game only refers to it as "equipment". I assumed this was divisible cargo. I understood enough that when asked to take an Aeon Cell to a place you cannot divide that. If the cargo in this mission cannot be divided then the game should try to abort on takeoff if a single ship in your fleet cannot handle the mission cargo, as it does if you try to leave with less space and bunks than are required.

This basically means you have to bring a freighter or something like a Bactrian to do this mission, the player should know that going in so that they can prepare a ship to accept the mission.

**Comment by warp-core** [comment]
Can you upload your save file?
This mission shouldn't require all the cargo space be on a single ship, nor the passenger space.

Have all of your ships landed at Baianus?
The first of the two missions (from Caelian to Baianus) adds actual cargo and passengers. In order to complete this mission, that payload needs to be at Baianus. If you have multiple ships, some of it may be assigned to your escorts. If those escorts do not arrive at Baianus with you, you will not be able to complete the mission.

**Comment by rocky8u** [comment]
I do not recall the mission to Baianus where I had to deliver the cargo. The mission I received is the one to retrieve cargo. Is that Cognizance 27? If so I don't recall doing it but it is marked "done" in the save file.

Perhaps I should try to abort this mission and trigger the first one?

"Ken ." is right after a received the mission but had not left yet. 

"previous-1" is after I landed on Baianus where nothing happened.

The deadline is the next day.
[Ken .~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/14595288/Ken.previous-1.txt)
[Ken ..txt](https://github.com/endless-sky/endless-sky/files/14595285/Ken.txt)

**Comment by warp-core** [comment]
> I do not recall the mission to Baianus where I had to deliver the cargo. The mission I received is the one to retrieve cargo. Is that Cognizance 27? If so I don't recall doing it but it is marked "done" in the save file.

I was referring to Cognizance 28. You aren't actually taking that cargo or passengers to Baianus, but the mission involves cargo and passengers. I believe the idea is to reserve space so you have the space for the next mission.

https://github.com/endless-sky/endless-sky/blob/42fef63bb8bde4fd69c79c2b3297d664551292c9/data/remnant/remnant%202%20cognizance.txt#L1231-L1240

Looking at your save file, it looks to me like the cargo from Cognizance 28 has indeed been assigned to on of your escorts.
The Hauler III named "Startrain" currently in the Edusa system.
This is why the mission won't complete. You'll need that "cargo" with you at Baianus, even if you have enough free space for the next mission.

**Comment by rocky8u** [comment]
OK, assuming I don't want to take that Hauler III, can I abort the mission and re-trigger it later with appropriate vessels?

I didn't realize that that ship would be inadequate until I got to the system with it. I guess there is no way to re-allocate that "reserved space" among your escorts after the mission has begun?

**Comment by warp-core** [comment]
> OK, assuming I don't want to take that Hauler III, can I abort the mission and re-trigger it later with appropriate vessels?

No. If you abort or fail the mission, you can't try again (without editing your save file).

> I didn't realize that that ship would be inadequate until I got to the system with it. I guess there is no way to re-allocate that "reserved space" among your escorts after the mission has begun?

Also not without editing your save file.

You can go back to your save before you left Caelian and park whatever ships you don't want to bring the Baianus, then proceed with the rest.

Here is an edited version of your save file at Baianus. If you take off and land you should be offered Cognizance 29 (assuming you have enough space for all its cargo and passengers with you, I haven't checked that).

[Ken Cog 28~Baianus modified.txt](https://github.com/endless-sky/endless-sky/files/14595565/Ken.Cog.28.Baianus.modified.txt)

**Comment by rocky8u** [comment]
OK, thank you for clarifying. I was able to complete the mission by buying a second Gull and parking the Hauler III.
