### ISSUE TITLE
Plugin checkbox click zone misaligned

### ISSUE THREAD

**Issue by warp-core** [endless-sky/endless-sky#9920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The click zone for the checkboxes on the plugins page is too far right and down.

### Steps to Reproduce

1. Install a plugin.
2. Launch Endless Sky.
3. Go to Preferences->Plugins.
4. Click around the checkbox for the plugin and see that the click zone is not properly centred on the checkbox sprite.

### Expected Behavior

The click zone should be centred on the checkbox sprite.

### Link to save file

No save file required. A save file wouldn't help reproduce this anyway.

### Operating System

Windows 10

### Game Source

Built from source

### Game Version

42fef63

**Comment by xX-Dillinger-Xx** [comment]
### Confirmed: 
However, for me the zone was just too long. I can click on the box or below it. The click zone seems to be approximately twice as long as the box.
