### ISSUE TITLE
Afterburners cause issues with turning

### ISSUE THREAD

**Issue by Kamikaze4228** [endless-sky/endless-sky#9925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you use an afterburner along with your thrusters it seems to lock you out of the ability to turn left, however you can still turn to the right under the same conditions. This has happened to me on both linux and windows versions of the game, and i dont use any plugins.

### Steps to Reproduce

1. Equip afterburner on your ship, as far as i can tell it doesnt matter which afterburner or engine you use.
2. Engage forward thrust
3. Engage afterburner
4. Attempt to turn left while holding thrust

### Expected Behavior

You should be able to turn while at speed, especially since turning right seems to work fine.

### Screenshots

N/A

### Link to save file

[Grug Nosebreaker.txt](https://github.com/endless-sky/endless-sky/files/14640110/Grug.Nosebreaker.txt)
[Marvin Heemeyer.txt](https://github.com/endless-sky/endless-sky/files/14640111/Marvin.Heemeyer.txt)

 Either one of these files should work to reproduce, just take off and try it.

### Operating System

Its happened on both my debian linux and windows 10 machines

### Game Source

Steam

### Game Version

v0.10.6

**Comment by warp-core** [comment]
Testing with both of those save files on 0.10.6, I am able to turn both left and right while thrusting with normal engines and using the afterburner.

Is it possible that your keyboard is not able to read the forward thrust, afterburner, and turn left keys at the same time?

What happens if you swap the binding of turn left and turn right and try both while thrusting and afterburning?

**Comment by Kamikaze4228** [comment]
I dont think its the keyboard just because ive tried it on a couple now but idk. I swapped the bindings and it reversed the issue, so right was locked out and left was fine.

**Comment by warp-core** [comment]
Are you able to turn in both directions while thrusting normally (no afterburner)?

If so, what happens if you bind the afterburner control to the same key as forward thrust and then try turning in each direction with the thrust key held down?

**Comment by xX-Dillinger-Xx** [comment]
It sounds like a keyboard issue. I used to have a keyboard that did the exact same thing in a different game. Certain keyboards are not able to accommodate certain simultaneous key presses. I used some tester, I can't remember the name of, to confirm it. I'll see if I can find it.

**Comment by Kamikaze4228** [comment]
> If so, what happens if you bind the afterburner control to the same key as forward thrust and then try turning in each direction with the thrust key held down?
Tried this and it did work, also tried the keyboard tester site and confirmed that the boards are the issue. I have another one ill check when i get home but i suspect its the same thing. I appreciate the help!
