### ISSUE TITLE
how to get navy license

### ISSUE THREAD

**Issue by owdeodie** [endless-sky/endless-sky#9934]
### Location

not an issue just didnt know what to put

### Describe the issue

google and the fandom says u cant but that post is 2020 so

### Expected content

update if if its wrong? ig

**Comment by Saugia** [comment]
The Navy License is currently unobtainable, and has been such for several years now. It will be a part of the Republic side of the Main Campaign (So FW except siding with the Republic) once we get around to writing it.

**Comment by TheGiraffe3** [comment]
The answer has been given. Should this issue be closed?
Or will we keep it open to remind people about the Republic writing side of things?
