### ISSUE TITLE
Offering Bribes to Aliens

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#996]
When attempting to offer bribes to alien races (in my case the Korath) that speak an entirely different language they will still say in English "I don't want your money." 

I'm not sure if this would also occur if you attempted to give bribes to the Wanderers before you got the translator.

**Comment by lehgogh** [comment]
Should you even be able to bribe aliens without being able to speak the language?

**Comment by endless-sky** [comment]
I can't reproduce this. When I hail any of the Korath factions, I get this:

![korath](https://cloud.githubusercontent.com/assets/11450262/14804602/f8682c8e-0b32-11e6-80ca-4036b9df533a.jpg)

**Comment by mdsmestad** [comment]
@Amazinite what version are you running?

**Comment by Amazinite** [comment]
The latest steam version, I attempted to bribe a Raider. It might be important to know that when I just hailed the raider without clicking offer bribe, the text box was completely blank.

**Comment by mdsmestad** [comment]
@Amazinite this is not an issue on the main branch any more. The changes just haven't been released to steam yet
