### ISSUE TITLE
Add missing mission location info to Remnant mission description

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#9967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the mission "Remnant: Cognizance 4" you get asked to destroy a Korath fleet last seen in Parca. However once you have accepted the mission, there's no blue mission pointer on any system on the map, and there's no info in the mission description telling you to which system you need to travel.

So if you're forgetful like me then you don't know where to go to complete the mission - I had to search the code repo to find it: https://github.com/endless-sky/endless-sky/blob/810a8d5d26642f8f427e001cf1f2421db361a48d/data/remnant/remnant%202%20cognizance.txt#L145

### Steps to Reproduce

Accept mission "Remnant: Cognizance 4", then go to your map.

### Expected Behavior

There's enough info in the mission description to complete the mission.

### Screenshots

<img width="1470" alt="Screenshot 2024-04-05 at 14 42 10" src="https://github.com/endless-sky/endless-sky/assets/16049594/9aad125c-d076-42b7-8edb-88ff547a9132">

### Operating System

MacOS

### Game Source

Steam

### Game Version

0.10.6

### Additional Information

Add info to the description "Prefect Chilia has asked you to track down a Korath fleet before returning to <destination>." to give the player more of an idea of where to go.

The mission intro tells the player that the fleet was last seen in Parca but adding Parca to the mission description would not be helpful, given the fleet appears in Aescolanus, which isn't even in the same system cluster. I also wouldn't tell the player to go to Aescolanus, because the Remnant don't know exactly where the fleet is -  this is supposed to be a search.

How specific should we be? Would something like this be enough? "Prefect Chilia has asked you to track down a Korath fleet in the Ember Waste before returning to <destination>."

**Comment by xX-Dillinger-Xx** [comment]
I remember being frustrated during this mission as well. I started looking in Parca and then searched in a more direct line towards Nenia and didn't think to look towards N.W. section of The Ember Waste. Narrowing down the search to "The Ember Waste" might not be a bad idea. It still preserve the mystery but reduce the frustration. 

I wouldn't necessarily call this a bug but I can I confirm it may be an issue. Should the Label be switched to `content`?

**Comment by brendanjones** [comment]
Fine by me!

**Comment by OcelotWalrus** [comment]
Perhaps just `Prefect Chilia has asked you to track down a Korath fleet in The Western Ember Waste before returning to  <destination>."` would be fine?

**Comment by brendanjones** [comment]
Afaik the compass points aren't used to refer to parts of The Ember Waste anywhere else, so using them here in this one mission is maybe confusing? Also TEW is a bit of an odd shape so I don't know that 'west' is super helpful, especially as four systems are further west than Aescolanus (and one is level with it).

I think it might be better to edit the mission intro somewhat, from
`"It is imperative that all the Korath involved in this exploration be located immediately. According to our surveillance, that ship was part of a fleet that recently passed through Parca. Locate the fleet and report back."`
to
`"It is imperative that all the Korath involved in this exploration be located immediately. According to our surveillance, that ship was part of a fleet that recently passed through Parca, though the fleet will likely be on the move through The Ember Waste. Locate the fleet and report back."`

and then go with the more generic:
`Prefect Chilia has asked you to track down a Korath fleet in The Ember Waste before returning to  <destination>."

Mission text is [here](https://github.com/endless-sky/endless-sky/blob/acde3d27531c24dca4496811dc11a8058662a95f/data/remnant/remnant%202%20cognizance.txt#L143).

**Comment by OcelotWalrus** [comment]
I'd say: `Prefect Chilia has asked you to track down a Korath fleet detected in The Ember Waste before returning to <destination>.`
