### ISSUE TITLE
Variable inconsistency between Patir Mystery and Cognizance

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#9969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cognizance and Patir Mystery were in part written at the same time, and as such, they share the addition of some characters, plot points and attributes. One of them was supposed to be "explorationinterest", a counter used to determine the player's interest in exploration as opposed to, say, science; during the review of Patir Mystery, under [Anarchist's suggestion](https://github.com/endless-sky/endless-sky/pull/6153/commits/020c8a2fd58db37e31a60c5bb6d656dd116e0e03#r682283673) and following the examples set in the past, it was changed to "exploration interest" with a space, but the same was not done with Cognizance. As such, each of them increases its own attribute with no relation to each other

### Steps to Reproduce

1. Do the two mission chains
2. Open the save file
3. Scroll to the variables saved in it

### Expected Behavior

The two missions increase the same attribute, which based on the review should have the space between the words. Given the time passed since, an invisible mission to transform one into the other will be necessary on top of fixing the missions themselves asap

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

current

**Comment by OcelotWalrus** [comment]
What do you mean by "Given the time passed since, an invisible mission to transform one into the other will be necessary"?
