### ISSUE TITLE
Request: Automatically unpark a ship if it is moved to position 1 in the fleet list

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#9984]
### Problem Description

This is a very small problem but still, it'd be a nice usability fix IMO: I can't count the number of times I've been switching ship so I've moved a parked ship to position 1 in my fleet list, and then taken off, completely forgetting to unpark it first meaning it stays on the planet instead of it being the ship I'm flying.

After all, it's impossible to park a ship when it's in position 1, so why is it possible to move a parked ship there without it being unparked in the process?

### Related Issue Links

Plenty related to (un)parking but none specific to this.

### Desired Solution

If a ship is parked and it is moved to the number 1 spot in the fleet list, then unpark it.

This should apply no matter where the ship position is changed (shipyard, outfits, player info). 

### Alternative Approaches

-

**Comment by xX-Dillinger-Xx** [comment]
I have had the same issue and vote yes for this request.

**Comment by Hyratel** [comment]
> ...and make "unpark/park local" treat fighters as part of their mother ship - oh wait they don't know what that is... 😸

treat first N=Bays fighters/drones in the list *immediately after* a Carrier && Same System as "its wing", up to NumBays. any Hyper-capable Ship halts check.

**Comment by moonliiiqhte** [comment]
Hey guys, i have tried to work on your problem for a bit. Please consider checking it out and let me know if there is something that needs to be adjusted :)

**Comment by TomGoodIdea** [comment]
Implemented in https://github.com/endless-sky/endless-sky/commit/b9ec212ff9f1a0b806ce8550a2964b6788eca66c
