### ISSUE TITLE
Don't display the "you have missions that require landing on [planet]" notice for bounty hunter missions

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#9992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You are no longer required to return to the planet of origin in order to complete bounty hunter (including marauder) missions. Therefore it doesn't make sense to display the notice "Note: you have missions that require landing on [planet] in the system you are jumping to." for these missions.

### Steps to Reproduce

1. Accept any mission that requires you to destroy down pirates/marauders.
2. Jump out of the system
3. Jump back into the system
4. You get shown the notice

### Expected Behavior

Don't display the notice.

### Screenshots

<img width="605" alt="Screenshot 2024-04-15 at 11 39 35" src="https://github.com/endless-sky/endless-sky/assets/16049594/b0cada91-b76a-4114-b365-a4917b6a074d">

### Link to save file

Any pilot.

### Operating System

MacOS

### Game Source

Steam

### Game Version

0.10.6

### Additional Information

Related? https://github.com/endless-sky/endless-sky/pull/8779

**Comment by OcelotWalrus** [comment]
Could you please tell which missions for example the bug works with? "Accept any mission that requires you to destroy down pirates/marauders." doesn't really help.

**Comment by brendanjones** [comment]
Start at line [2930](https://github.com/endless-sky/endless-sky/blob/acde3d27531c24dca4496811dc11a8058662a95f/data/human/jobs.txt#L2930) and work your way down to line 4032. All of those missions.

**Comment by OcelotWalrus** [comment]
> Start at line [2930](https://github.com/endless-sky/endless-sky/blob/acde3d27531c24dca4496811dc11a8058662a95f/data/human/jobs.txt#L2930) and work your way down to line 4032. All of those missions.

Ooh! I looked under the missions files, instead of the jobs one. Thanks.

**Comment by brendanjones** [comment]
Hah yeah I did the same, was getting confused why I couldn't find the damn missions.

**Comment by OcelotWalrus** [comment]
How I'd fix this easily is b modifying the code so that these messages can't be displayed if the mission has an `apparent payment` attribute, as they're used only in bounty and marauder missions in the game vanilla data. But a better way to do this would be to add an attribute to missions, like `no landing` or `no landing message`, that'd disable these messages.

I'd like to get your opinion on that before working on a fix and creating a PR.

**Comment by brendanjones** [comment]
My opinion? That's very kind but I'm not a dev, so my opinion isn't so useful here :)

Worth noting that if a `no landing` attribute is added it might also allow https://github.com/endless-sky/endless-sky/issues/9993 to be solved.

**Comment by OcelotWalrus** [comment]
> My opinion? That's very kind but I'm not a dev, so my opinion isn't so useful here :)
> 
> Worth noting that if a `no landing` attribute is added it might also help with solving #9993.

It won't help with this other issue, as the problem of this other issues is just that in the game engine, failed missions get removed from the list only after changing of system or landing.

**Comment by OcelotWalrus** [comment]
This has been fixed by the PR, you can close the issue.
