### ISSUE TITLE
Request: add the ability to click-and-drag to reposition multiple selected ships at once in outfitter and shipyard

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#9998]
### Problem Description

When in player info, you can select multiple ships and drag them to a new position in your fleet list. Yay! Can we have the ability to do the same in the Shipyard and Outfitters?

You can currently select multiple ships but you can't click and drag them. Attempting to do so will simply reduce your selection to the one ship clicked on.

### Related Issue Links

Can't find any.

### Desired Solution

Exact same mechanic as in the player info fleet list. Once multiple ships are selected, clicking and dragging would move all ships selected.

### Alternative Approaches

Don't think so.

**Comment by warp-core** [comment]
Is this #2038?

**Comment by brendanjones** [comment]
Ughhhh yes, thank you. Didn't come across that in my search.
